### ISSUE TITLE
GENERAL NOTE

### ISSUE THREAD

**Issue by seerge** [seerge/g-helper#10]
Hello dear app users (and forkers)

I see that app gets some traction, and some of you try to help and introduce new features. That's very cool.

But first of all, I would like to propose some of own ideas, that I personally have not much time / resources implementing

**1. Anime matrix control** At least basic switching of loading / sleep / modes would give a good start

**Comment by jhelmink** [comment]
https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast?tabs=uwp

For whoever might pick this up.

**Comment by seerge** [comment]
> 

This is irrelevant

**Comment by seerge** [comment]
> https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast?tabs=uwp
> 
> For whoever might pick this up.

This is irrelevant, as won't work in games

**Comment by MinikPLayer** [comment]
Maybe we can somehow detect if an app is fullscreen and if there's one try using RivaTuner Statistics Server to display an overlay? I've found a repository in C# that uses this method and works fine even for fullscreen games - https://github.com/damob-byun/OpenRtssText
With this without a fullscreen app notification method could be used instead.

**Comment by seerge** [comment]
Ok, closing this as I did by myself animatrix, fan profiles, and all other stuff I listed here .... :D
