### ISSUE TITLE
Hide some features from G14 2020

### ISSUE THREAD

**Issue by barsikus007** [seerge/g-helper#1000]
There is no Fn+F4 aura key on 2020 edition of G14, so it's better to hide that setting on that models
![image](https://github.com/seerge/g-helper/assets/37113583/d80c3734-5afb-495d-a725-a582b90c3650)
Also, I don't know what should the whole "Laptop Backlight" section do (no information in FAQ). These settings could probably not available on 2020 edition of G14.
![image](https://github.com/seerge/g-helper/assets/37113583/1af65b6b-163c-4b77-a30b-c8798a996747)

**Comment by seerge** [comment]
- Fn-F4 still exists on this device and can be assigned via app to some other function (as was requested in https://github.com/seerge/g-helper/issues/42) 
- Backlight section turns on / off backlight modes in awake / sleep / boot / shutdown modes (it's quite self explanatory, it works on 2020 devices as well)

**Comment by barsikus007** [comment]
- I remapped Fn+F4 to PrntScr to test if remapping is available and its doesn't
- When I slide slider after section title -- my keyboard brightness changed -- so I guessed that it is keyboard animation settings (which is not presented at 2020 edition of G14). Then I disabled sleep checkbox and put my laptop to sleep, and keyboard turned off (Anime matrix animation started after my laptop slept FYI). When I turned back sleep checkbox nothing changed, so I still don't know, what this section does for my generation of laptop.

**Comment by seerge** [comment]
- then i can hide Fn-F4 for GA401I devices
- as for backlight - you probably have some restricted version of 2020 that doesn't have even that, while others do

[GHelper.zip](https://github.com/seerge/g-helper/files/12261902/GHelper.zip)

**Comment by barsikus007** [comment]
- The Fn+F4 setting disappeared, thanks!
- About this, I just don't know what it supposed to do. Is that setting leave my keyboard lights turned on after shutdown (if I choosed shutdown)? What does animation speed do? (Blinking keyboard speed?). I really want to get what it is...

**Comment by seerge** [comment]
Keyboard backlight can blink (once or twice) on shutdown or boot
Animation speed is a speed for backlight effects (like strobbing or breathing)

**Comment by barsikus007** [comment]
Sorry for bothering, but OD seems doesn't work at GA401I too (according to [that post on reddit](https://www.[reddit.com/r/ZephyrusG14/comments/i5cf4j/asus_software_is_kind_of_bad/](https://www.reddit.com/r/ZephyrusG14/comments/i5cf4j/asus_software_is_kind_of_bad/)))
