### ISSUE TITLE
Zephyrus G14 can't use some buttons without services working

### ISSUE THREAD

**Issue by mniert** [seerge/g-helper#1009]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**

Cannot use m3, m4, keyboard light buttons, aura keybind, fan control, trackpad on/off and brightness up and down without enabling asus services
**Clear scenario to Reproduce**
Disable asus services and use the keys

**Expected behavior**
The keys should be able to be used without the services(at least i was using in that way)
**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/12267033/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Laptop model
Windows 11 Asus Zephyrus G14 GA402RJ-L4125
**Asus software**
- Armoury Crate (or it's services installed)
- No
- MyASUS installed
- No
- Other Asus services running in background
- No(optional)

**Additional context**

**Comment by seerge** [comment]
@mniert hello,

I see that it actually works in the beginning (you press M4 for example), but then windows just shuts down whole keyboard by some reason and terminates connection with the app :) 
```
5.08.2023 15:00:59: Key: 56
5.08.2023 15:01:05: Key: 56
5.08.2023 15:01:14: Listener terminated
5.08.2023 15:01:14: Listener stopped
```

I don't know why it's happening on your specific system, but it looks like windows is missing some drivers ? at least it can't connect to GPU driver as well (at all) :)

```
5.08.2023 15:00:52: dGPU not found
```

Mb time for a fresh reinstall of all drivers? or a whole windows?

**Comment by seerge** [comment]
The only thing that comes to my mind, mb it's bugged drivers / multiple usb devices connected, can you run this build and post a log from it (it wil just show how many detectable input devices you have)
[GHelper.zip](https://github.com/seerge/g-helper/files/12267059/GHelper.zip)

**Comment by mniert** [comment]
well i just did a quick sfc scan and a restart and for now everything works 

here is the log file btw 
[log.txt](https://github.com/seerge/g-helper/files/12267440/log.txt)

**Comment by seerge** [comment]
@mniert great to hear ;) I will close this as completed then
