### ISSUE TITLE
Release 0.31 flagged as virus by Microsoft Defender

### ISSUE THREAD

**Issue by ajamro** [seerge/g-helper#101]
**Describe the bug**
Cannot run program, it gets put in the quarantine flagged as Win32/DefenseEvasion.A!ml by Microsoft Defender.
the file in question: https://www.virustotal.com/gui/file/39ae553bd7cd053bb7c56303e7ad941c377dd1772608bb9784408d948d96cf05/behavior

**To Reproduce**
1. Download 0.31 release
2. Unzip the file
3. See the warning preventing any kind of interaction.

**Expected behavior**
No false positives by the av software.

It seems like false positive, but since there do exists attacks on developers i decided do post this issue anyway (maybe behaviour of a dependency have changed, so it looks more shady to the av scanner).

**Comment by seerge** [comment]
I just recompilled it again under different built name 0.32. Defender seem to like this one https://github.com/seerge/g-helper/releases/tag/v0.32
