### ISSUE TITLE
Cpu&gpu temp/fan not showing up after installing atlas os.

### ISSUE THREAD

**Issue by WheatGrasses** [seerge/g-helper#1011]
first time using github bug report so i might have messed up with uploading files.
After installing atlas os v0.2.0 i cannot see my cpu/gpu temps or fan rpm/speed%. There are no asus services running.
Rog strix g15 advantage edition qhd 
g helper version 0.103.0
[log.txt](https://github.com/seerge/g-helper/files/12268518/log.txt)
![image](https://github.com/seerge/g-helper/assets/114834043/2d7313fc-c364-4a29-8300-b1ed6dbd3903)

**Comment by seerge** [comment]
@WheatGrasses hello,

By looking at the log ALL ACPI requests to the device has failed. I can only imagine that Atlas OS is trimmed / limited so much that it blocks Asus System Control interface completely, so app can't neither read nor set any settings :) 

```
8/5/2023 6:23:11 PM: ASUS BIOS rejected fan curve, resetting mode to 1
8/5/2023 6:23:11 PM: Reset Mode = 1 : 0
8/5/2023 6:23:11 PM: Eco flag : -65536
8/5/2023 6:23:11 PM: Mux flag : -65536
```

There is nothing to fix it, as it's a problem with OS meeting requirements, not the app. Most probably Armoury Crate also won't work in this conditions.
