### ISSUE TITLE
Keyboard lighting And GameVisual

### ISSUE THREAD

**Issue by Maneeha1234SL** [seerge/g-helper#1012]
Asus Zephyrus G15 2022 GA503RM's keyboard lighting works only with the option given below
Static
Breathe
strobe

Pressing the Aura button without the Fn key requires pressing the Aura button multiple times to change the light patterns.
The reason for that
Color cycle
Rainbow
Heatmp has 3 light patterns (not compatible with my computer)

So this is what I am trying to explain
If possible, if you add keyboard light patterns to select under extra setting, you can easily control the keyboard light patterns without Fn key under G helper.

Another problem is that there is no GameVisual option (Fn+V) when ASUS Services is disabled, it is almost completely unusable.
This app would be perfect if it could support GameVisual as well.

<img width="302" alt="Screenshot 2023-08-06 114137" src="https://github.com/seerge/g-helper/assets/83775004/c5269a28-9756-4359-b023-322b33233d85">
<img width="1278" alt="Screenshot 2023-08-06 120831" src="https://github.com/seerge/g-helper/assets/83775004/36d81c33-4339-468d-971b-227918eb5d8a">

**Comment by seerge** [comment]
@Maneeha1234SL hello,

In general  G15 2022  supports colored backlight. But I can imagine your specific device (not model!) have only white backlight ? :) If this is the case - then it's how things are. I can't hide colored options from  dropdown for your model, cause it will break behavior of other G15s.

Visual styles are proprietary thing, and it's covered in FAQ https://github.com/seerge/g-helper#how-do-i-set-different-visual-styles

**Comment by seerge** [comment]
Added in latest release https://github.com/seerge/g-helper/releases
