### ISSUE TITLE
Battery Charge Limiter does not work as expected

### ISSUE THREAD

**Issue by scrazzz** [seerge/g-helper#1013]
**Describe the bug**
As the title says, Battery Charge Limiter does not work as expected. It only works when it is set to 80%. If I change the value to 85% or even 90% it keeps charging until it's at 100%.

I did read the README and understand what may cause this issue. But I have [stopped all Asus services](https://github.com/seerge/g-helper#battery-charge-limiter-is-not-working) and have [uninstalled MyAsus application](https://github.com/seerge/g-helper#can-i-use-myasus-app-along-with-g-helper) from my machine. I have uninstalled Armory Crate and furthermore did some more cleanup using [BloatyNosy](https://github.com/builtbybel/BloatyNosy).

**Clear scenario to Reproduce**
1. Plug in charger
1. Open g-helper
1. Set Battery Charge Limiter to 90%
1. Wait for it to charge and you'll notice that it keeps charging beyond 90%

**Expected behavior**
To not charge the battery beyond 90%.

**App Logs**
n/a

**Screenshots or screencasts**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ASUS TUF GAMING F15

**Asus software**
- NO Armoury Crate (or it's services installed)
- NO MyASUS installed
- NO Other Asus services running in background

**Additional context**
n/a

**Comment by seerge** [comment]
@scrazzz hello,

It's possible that some devices just don't support 85% or 90% on **hardware level** :) Since you have ignored requested logs, i can't really say more.

Since 80% is working - there is nothing to "fix" here

**Comment by scrazzz** [comment]
> It's possible that some devices just don't support 85% or 90% on hardware level

Hmm I see, thanks for the info.

> Since 80% is working - there is nothing to "fix" here

Well, then why have a slider to adjust it on hardwares that don't support it? I'd much rather prefer a checkbox to avoid the confusion :)

**Comment by seerge** [comment]
@scrazzz because there is no way to know in advance if does support or not :) wast majority of devices do support any values here

**Comment by scrazzz** [comment]
I'll try to get the logs later and open a new issue which links here.
