### ISSUE TITLE
[Feature Request]Auto-hide feature request

### ISSUE THREAD

**Issue by Mofimg** [seerge/g-helper#1022]
It is hoped that the window auto-hide function can be added. When the mouse clicks outside the G-helper window, the window will be automatically hidden, just like the auto-hide logic of the Action Center of win11.

**Comment by seerge** [comment]
@Mofimg hello, it’s not practical as app has child windows like fans+power or extra settings, which will also close main window following this logic

Did you know that app has a right-click context menu with all main functions? Just make tray icon always visible and right click on it

**Comment by Mofimg** [comment]
> @Mofimg hello, it’s not practical as app has child windows like fans+power or extra settings, which will also close main window following this logic
> 
> Did you know that app has a right-click context menu with all main functions? Just make tray icon always visible and right click on it

@seerge Thanks for your attention and reply! I had noticed that the right-click function of context menu before, it's for sure this function is very convenient, but I think it's a little inconvenient to close main window with only two ways of  M-key or close bottom with mouse click.
 
If child windows auto closed with main window may cause confusion, we may add customized hotkey for common function, such as  Ctrl+W could not valid for the current program.
