### ISSUE TITLE
Back paddle option remaps volume down button

### ISSUE THREAD

**Issue by fennectech** [seerge/g-helper#1023]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**
ROG ally volume down button is altered when modifying “back paddles” in g-helper. 
**Clear scenario to Reproduce**
1. Go to 'ghelper'
2. Click on 'extras'
3. Alter remapping of “back paddles” 
4. Volume down now does what you set back paddles to do
5. 
**Expected behavior**
Remap back paddles.  Not volume down
**App Logs**
(Placeholder.  Must retrieve them)
 
**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - ROG Ally

**Asus software**
- Armoury Crate (or it's services installed)
- MyASUS installed
- Other Asus services running in background
- Handheld Companion
 (Asus services stopped with g-helper 

**Additional context**

**Comment by fennectech** [comment]
[log.txt](https://github.com/seerge/g-helper/files/12287134/log.txt)

**Comment by seerge** [comment]
@fennectech hello, this was a very specific issue only in 0.105 , just update to the latest release (107 atm) and it will be fine:)

**Comment by fennectech** [comment]
Oh. I never noticed there was an update!  Would you consider adding an update checker?

**Comment by fennectech** [comment]
Never mind. I am blind.
