### ISSUE TITLE
Fan RPM shown wrong for G14 2021

### ISSUE THREAD

**Issue by hkaancaliskan** [seerge/g-helper#103]
**Describe the bug**
I have 7200 RPM fans also can be seen in screenshot but while tuning them it shows 5800RPM as maximum

![resim](https://user-images.githubusercontent.com/17825767/226180880-4eb9b71b-38d8-40f1-98d1-be46b4f0ecf4.png)

G14 2021 GA401QC-BM205

**Comment by seerge** [comment]
That's why i was initially against showing exact values on chart axis (despite people asked). Asus bios can treat them differently depending on the model. There is not much I can do here to be honest :)

**Comment by hkaancaliskan** [comment]
But before showing exact values of points, it's also shown wrong on chart via 5400-5000 etc on the left.

**Comment by seerge** [comment]
@hkaancaliskan , right cause Y-axis is absolutely subjective (i have set it manually based on my own observations on G14 2022 model). It can be different on others. Alternative - i could show % there (as BIOS takes settings in % anyway)

**Comment by hkaancaliskan** [comment]
If applicable, showing true RPM values should be the goal but if thats not possible percentage is of course much more meaningful.

**Comment by seerge** [comment]
What is the minimum RPM that you can set ? (i.e. if you set a point on a chart to 1 (from 0...100 scale) ? And what is the maximum?

**Comment by hkaancaliskan** [comment]
7200 RPM is the maximum.
I can set to 1800 RPM on chart.

**Comment by hkaancaliskan** [comment]
Oh, with latest version, when i change fan curve, they're not saved.
1. Change fan curve
2. Apply changes and switch to another mode
3. Come back again to see changes not saved.

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11011287/GHelper.zip)
I have literally hardcoded a max RPM to be 7200 for model name containing 401 (your case).

As for saving curves, they are saved only when you click apply (by design)

**Comment by hkaancaliskan** [comment]
Now they're running at 7200-1800RPM range correctly for my case.

For saving curves, as i said at steps in my comment, i clicked apply. I checked log and looks like app is saving and applying correct values but at the chart that's showing previous values.

1.     Change fan curve
2.     Apply changes and switch to another mode
3.     Come back again to see changes not saved.

**Comment by seerge** [comment]
@hkaancaliskan i can't really reproduce it, as app indeed saves and loads params in my case. I need more specific scenario :|

**Comment by hkaancaliskan** [comment]
https://www.youtube.com/watch?v=WRlFKEQBK-8
I recorded it.

**Comment by seerge** [comment]
Can you try a normal fan curve, when dots don't overlap each other ? :)

**Comment by hkaancaliskan** [comment]
@seerge hehe it works fine that way, what's wrong with my way lmao

**Comment by seerge** [comment]
I didn't change anything between 0.31 and 0.32. But I will try to include fan y-axis in next release.
