### ISSUE TITLE
Fan problem in rog ally changing the performace mode by disconnecting the charger

### ISSUE THREAD

**Issue by madkep** [seerge/g-helper#1034]
What happens is that when changing the performance mode by connecting or disconnecting the charger, it does not respect the ventilation curve of the mode.
So you have to activate it manually anyway.

1.- In AC use the windows mode connected to the power supply and with the battery.
2.- In Ghelper activate the silent mode using the battery.
3.- In Ghelper use the turbo mode connected to the power supply.
4.- Run a game or a strees test with the battery and then connect the charger. you will notice that the fan does not exceed 56% even at high temp but the tdp is correctly assigned.
5.- Now If you activate the ghelper turbo mode manually, the fan now works correctly and reaches a higher percentage.

Expected behavior:
When the profile is changed by connecting the charger, it is expected that the fan curve belonging to the profile will also be activated.

**Comment by madkep** [comment]
Sorry, I was collecting the data to get a better view of the problem.
I also think AC is overwriting the fan profile. But the TDP is assigned correctly so something strange is going on there.

[log.txt](https://github.com/seerge/g-helper/files/12293246/log.txt)

**Comment by madkep** [comment]
You are right, with AC off it works correctly but because of the triggers I can't turn it off.
Isn't there an option to add a delay so that the ghelper changes are activated a little after the AC changes?
The strange thing is that it is only related to the fan curve because the tdp is assigned correctly.

**Comment by seerge** [comment]
(Custom) Power limits are applied 1 second after main profile / fans (as on some asus laptops, due to issues with bios it won't be accepted).

I'm not a big fan of adjusting the app in order to "fight" with AC (as it has never been designed to work along AC in a first place)

What is the "Triggers" that you use in AC ?

**Comment by madkep** [comment]
I understand, However, it is not annoying to activate the mode every time I unplug the charger.

it happens that the two triggers (RT-LT) of the rog ally work with hall sensor.
I had a heat problem and the magnet inside the right trigger got very hot so it lost magnetic force and became weaker.
So to get it to press 100% I have to set different deadzones inside AC for LT and RT.

So I can't completely get rid of AC at the moment.
Until I change the right trigger at some point.

thanks for replying anyway, for everything else the app has worked perfectly for me.

**Comment by seerge** [comment]
Most probably controller (triggers) are "controlled" by AC via USB interface. You can try to manually stop AC services (from windows Services app), but keep launching AC to set your deadzones. Don't they remember settings after setting them once?

Alternatively you can contribute to G-Helper and add support for deadzone controls in the app itself. There is a whole topic where you can submit request for peripherals support https://github.com/seerge/g-helper/discussions/900 (atm only mice are supported). But they all are controlled in a similar way (via USB commands).
