### ISSUE TITLE
Asus ROG Strix SCAR 16 Multi-zone not enabled after resuming from "sleep" / "Modern Standby" 

### ISSUE THREAD

**Issue by Siebzehn88** [seerge/g-helper#1036]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**

**Clear scenario to Reproduce**
1. On 2023 Asus SCAR 16 Model just set system to sleep, and then exit out of sleep back into Windows
2. Click on '.Multizone' and system stays on "single zone" functionality instead. Reboot solves this, but once system is set to sleep the behavior resumes

**Expected behavior**
Normally would expect same functionality being able to select Multi-zone and see the desired result. Just thought it was interesting as G-helper log seems to indicate that multizone is set to "1" even with the display stuck in single zone state

**App Logs**
Please see my paste of the logs below, I am showing the system change from "0" for display (single zone) to "1" for (multizone) but once the system exists standby/sleep you can see that the system states it's only in "1" which is multizone. Every time clicking "multizone" within G-helper it doesn't set back to "0" but it is definitely stuck in "0" or "single zone" back lighting for the mini-LED:
8/8/2023 2:51:45 PM: USB-KB 64|32HID-compliant vendor-defined device\\?\hid#vid_0b05&pid_19b6&col05#6&234535b2&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-03-FF-FF-FF-F5-00-00-FF-FF-FF-00-00-00-00
8/8/2023 2:51:45 PM: Session:SessionUnlock
8/8/2023 2:51:45 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 2:51:45 PM: ScreenOverdrive = 1 : OK
8/8/2023 2:51:46 PM: Power Mode:StatusChange
8/8/2023 2:51:52 PM: Latest version 0.107.0.0
8/8/2023 2:51:56 PM: Design Capacity: 90001mWh, Full Charge Capacity: 85780mWh, Health: 0.953100521105321051988311241%
8/8/2023 2:51:57 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 2:51:57 PM: Miniled = 0 : OK
8/8/2023 2:51:57 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 2:51:57 PM: Miniled = 1 : OK
8/8/2023 2:51:59 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 2:51:59 PM: Miniled = 0 : OK
8/8/2023 2:51:59 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 2:51:59 PM: Miniled = 1 : OK
8/8/2023 3:00:59 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:00:59 PM: Miniled = 0 : OK
8/8/2023 3:01:06 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:01:06 PM: Miniled = 1 : OK
8/8/2023 3:01:07 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:01:07 PM: Miniled = 0 : OK
8/8/2023 3:01:07 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:01:07 PM: Miniled = 1 : OK
8/8/2023 3:01:21 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:01:21 PM: Miniled = 0 : OK
8/8/2023 3:01:22 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:01:22 PM: Miniled = 1 : OK
8/8/2023 3:03:08 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:03:08 PM: Miniled = 0 : OK
8/8/2023 3:03:18 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:03:18 PM: Miniled = 1 : OK
8/8/2023 3:03:23 PM: Monitor Power Off
8/8/2023 3:03:23 PM: Backlight:5D-BA-C5-C4-00
8/8/2023 3:03:23 PM: Power Mode:Suspend
8/8/2023 3:04:54 PM: Power Mode:Resume
8/8/2023 3:04:54 PM: Monitor Power On
8/8/2023 3:04:54 PM: AutoSetting for Online
8/8/2023 3:04:54 PM: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&234535b2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
8/8/2023 3:04:54 PM: Mode = 0 : OK
8/8/2023 3:04:54 PM: Eco flag : 0
8/8/2023 3:04:54 PM: Mux flag : 1
8/8/2023 3:04:54 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:04:54 PM: ScreenOverdrive = 1 : OK
8/8/2023 3:04:54 PM: BatteryLimit = 80 : OK
8/8/2023 3:04:54 PM: USB-KB 0x19B6:5D-BD-01-FF-1E-FF-FF-FF
8/8/2023 3:04:54 PM: Auto:5D-BA-C5-C4-03
8/8/2023 3:04:54 PM: USB-KB 64|32HID-compliant vendor-defined device\\?\hid#vid_0b05&pid_19b6&col05#6&234535b2&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-03-FF-FF-FF-F5-00-00-FF-FF-FF-00-00-00-00
8/8/2023 3:04:58 PM: Monitor Power Off
8/8/2023 3:04:58 PM: Backlight:5D-BA-C5-C4-00
8/8/2023 3:04:58 PM: Power Mode:Suspend
8/8/2023 3:06:00 PM: Monitor Power On
8/8/2023 3:06:00 PM: AutoSetting for Online
8/8/2023 3:06:00 PM: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&234535b2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
8/8/2023 3:06:00 PM: Mode = 0 : OK
8/8/2023 3:06:00 PM: Eco flag : 0
8/8/2023 3:06:00 PM: Mux flag : 1
8/8/2023 3:06:00 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:00 PM: ScreenOverdrive = 1 : OK
8/8/2023 3:06:00 PM: BatteryLimit = 80 : OK
8/8/2023 3:06:00 PM: Power Mode:Resume
8/8/2023 3:06:00 PM: USB-KB 0x19B6:5D-BD-01-FF-1E-FF-FF-FF
8/8/2023 3:06:00 PM: Auto:5D-BA-C5-C4-03
8/8/2023 3:06:00 PM: USB-KB 64|32HID-compliant vendor-defined device\\?\hid#vid_0b05&pid_19b6&col05#6&234535b2&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-03-FF-FF-FF-F5-00-00-FF-FF-FF-00-00-00-00
8/8/2023 3:06:04 PM: Session:SessionUnlock
8/8/2023 3:06:04 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:04 PM: ScreenOverdrive = 1 : OK
8/8/2023 3:06:18 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:18 PM: Miniled = 1 : OK
8/8/2023 3:06:20 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:20 PM: Miniled = 1 : OK
8/8/2023 3:06:21 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:21 PM: Miniled = 1 : OK
8/8/2023 3:06:21 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:21 PM: Miniled = 1 : OK
8/8/2023 3:06:29 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:29 PM: Miniled = 1 : OK
8/8/2023 3:06:30 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:30 PM: Miniled = 1 : OK
8/8/2023 3:06:30 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:30 PM: Miniled = 1 : OK
8/8/2023 3:06:34 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:34 PM: Miniled = 1 : OK
8/8/2023 3:06:34 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:34 PM: Miniled = 1 : OK
8/8/2023 3:06:35 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:35 PM: Miniled = 1 : OK
8/8/2023 3:06:35 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:35 PM: Miniled = 1 : OK
8/8/2023 3:06:35 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:35 PM: Miniled = 1 : OK
8/8/2023 3:06:36 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:36 PM: Miniled = 1 : OK
8/8/2023 3:06:36 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:36 PM: Miniled = 1 : OK
8/8/2023 3:06:36 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:36 PM: Miniled = 1 : OK
8/8/2023 3:06:39 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:06:39 PM: Miniled = 1 : OK
8/8/2023 3:07:00 PM: Design Capacity: 90001mWh, Full Charge Capacity: 85780mWh, Health: 0.953100521105321051988311241%
8/8/2023 3:24:52 PM: Design Capacity: 90001mWh, Full Charge Capacity: 85780mWh, Health: 0.953100521105321051988311241%
8/8/2023 3:26:38 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:26:38 PM: Miniled = 1 : OK
8/8/2023 3:26:39 PM: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
8/8/2023 3:26:39 PM: Miniled = 1 : OK

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Laptop model: G634JY

**Asus software**
- MyASUS installed
- Other Asus services running in background- None I disable all Asus services unless using MyAsus, and then I disable them when I close the app

**Additional context**
I have double checked my power plan settings, device manager, and tried to see if event viewer shed any further light on this but nothing specific unless I am not linking an event to a more obvious cause. Like i  said just found this interesting and didn't see anyone else reporting this type of odd issue. Thank you for your support and I love this application by the way, you guys do an incredible job offering an alternative solution to Armory Crate!

**Comment by seerge** [comment]
@Siebzehn88 hello.

It's strange, as app clearly sends command to set Miniled ON. 

1. Does chaning display resolution or pressing Ctrl+Shift+Win+B (to reset windows video adapter) help anyhow?

2. You can try to run it manually via Powershell as admin (1 to set ON, 0 to set OFF) : 
```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x0005001e, 1)
```

If it doesn't work - i'm out of ideas :) 
You can try to install AC and see if situation happens there as well (after proper sleep of course)

**Comment by Siebzehn88** [comment]
@seerge  yes so I did attempt ctrl+shift+windows key+ b to reset the graphics driver manually and i have attempted resolution change and that did not correct it, nor did cycling through refresh rates either. 

Thank you for suggesting the powershell command but that hasn't worked either. I will keep digging, just seems to be a kind of super particular odd type of issue.

**Comment by seerge** [comment]
Do you have latest BIOS ? you can also try to do a [hardware reset](https://github.com/seerge/g-helper#how-do-i-do-a-hardware-reset-on-a-laptop) but i doubt it wil help :)

My guess would be it's some issue on bios level, and display just keeps thinking that laptop is still sleeping, so it ignores miniled-flag.

**Comment by Siebzehn88** [comment]
yes i am on the latest BIOS, also it's a clean install as of last Friday.

long story short, Asus sleep state out of the box is broken. I had issues with apps hanging, and not recovering out of sleep and resuming OS function, until I unplugged all of my USB ports. Then my applications would resume functioning, but my USB ports would not function again until reboot and device manager wouldn't function either to help recover the USB ports from within windows, so I had to reboot after every sleep cycle .

I recently fixed that as I found that Asus' power plans are very broken, and they aren't utilizing S3/Modern Standby correctly, I have seemed to fix that and now I have pretty much perfect resume from standby across the board. Except for ability to switch from single zone to multi zone of course haha. 

I am also on the latest Nvidia and intel graphics drivers as well as the latest windows updates as well.

**Comment by seerge** [comment]
Well, given all that, I'm afraid app can't do anything on it's side (as it sends the command). 

NVidia driver's shouldn't matter. As command exists in bios , and it shouldn't matter what GPU is now active / or what driver is used.

**Comment by Siebzehn88** [comment]
yeah you may be correct, just thought it was interesting and worth sharing such a unique type of issue, but yeah it seems Asus has more work to do with their BIOS considering it took quite a bit of effort just to get sleep working correctly on the unit as it is. 

thank you for being so quick to respond though, I absolutely love G-Helper and i've been recommending it quite a bit to folks to substitute Armory Crate with. Very impressed with the functionality from this single executable.

**Comment by seerge** [comment]
Thanks for a nice feeback :) 

I'm closing this, as there is nothing app can do in this scenario.
