### ISSUE TITLE
GA401IV Anime Matrix hibernation

### ISSUE THREAD

**Issue by barsikus007** [seerge/g-helper#1038]
**Describe the bug**
On a GA401IV Anime Matrix stops responding after hibernation (LEDs just tuns off, only restart fixes that)
This problem might exist because I removed all Asus bloatware (all features are working btw, so it might be a bug).
(Also I found some conflicts with my pwsh config in the logs, sorry for that 🥲)

**Clear scenario to Reproduce**
1. Remove or don't install asus services
2. Set smth on Anime Matrix
3. Hibernate laptop
4. Matrix won't work after boot

**Expected behavior**

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12299311/log.txt)

**Desktop (please complete the following information):**
 - Windows 11
 - GA401IV

**Asus software**
- Only ASUSSoftwareManager (I can't delete this service bcs it restores)

**Additional context**

**Comment by seerge** [comment]
@barsikus007 i can't reproduce anything of this. 

1. Does restarting G-Helper help anyhow? (it would send init command to matrix on start)
2. Is AC able to wake up matrix after hibernate?

**Comment by barsikus007** [comment]
1. Restarting helps with that issue, here is a log file:
[log.txt](https://github.com/seerge/g-helper/files/12300108/log.txt)

2. I can't install AC (I really dug into this (tried to decompile installers and decipher logs), but it still won't install on my system, and I really don't want to reinstall Windows for that)

**Comment by seerge** [comment]
@barsikus007 this build will send init commands to matrix after hibernation as well

[GHelper.zip](https://github.com/seerge/g-helper/files/12300683/GHelper.zip)
