### ISSUE TITLE
Ghelper does not change windows Power Mode when switching to silent, Turbo, Balanced modes

### ISSUE THREAD

**Issue by Maneeha1234SL** [seerge/g-helper#1040]
## NOTE
Ghelper does not change windows Power Mode when switching to silent, Turbo, Balanced modes

**Describe the bug**

**Clear scenario to Reproduce**
4. Explanation of an error or a bug

**Expected behavior**

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12303576/log.txt)

**Screenshots or screencasts**
<img width="1280" alt="Screenshot 2023-08-09 192628" src="https://github.com/seerge/g-helper/assets/83775004/d88f5148-f5d4-40ed-bb30-5bc288bdc8b0">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GA503RM

**Asus software**
- Armoury Crate install
- MyASUS installed
- Other Asus services running in background -no

**Additional context**

**Comment by seerge** [comment]
@Maneeha1234SL hello,

It actually does
```
8/9/2023 7:26:11 PM: Mode = 1 : OK
8/9/2023 7:26:11 PM: Power mode: ded574b5-45a0-4f42-8737-46345c09c238
8/9/2023 7:26:40 PM: Mode = 2 : OK
8/9/2023 7:26:40 PM: Power mode: 961cc777-2547-4f9d-8174-7d86181b8a7a
```
You mix **Power Modes** and **Power Plans**

You need to select "Balanced" Power plan in Control panel, and just stick to that (it's the most optimal way)

This is what G-Helper changes
![Screenshot 2023-08-07 184557](https://github.com/seerge/g-helper/assets/5920850/94e041d8-e2dd-4556-80c7-a71f8edd01f1)
