### ISSUE TITLE
Laptop keyboard color and 2 lighting options are gone

### ISSUE THREAD

**Issue by Alejuakbark** [seerge/g-helper#1041]
Coming from version 0.106 to 0.107 I experienced a loss with the color option and animation with he keyboard backlight. On version .107 I lost the "Rainbow" and "color cycle" animation as well as the choice to choose colors. With .107 I am locked with the color white and left without the 2 previously mentioned animation options. I am running a G15 GA503RM
<img width="379" alt="Screenshot 2023-08-09 083633" src="https://github.com/seerge/g-helper/assets/138835597/4a0e4847-7428-4e75-be4e-9e0859e01e30"><img width="323" alt="Screenshot 2023-08-09 083718" src="https://github.com/seerge/g-helper/assets/138835597/87840bb6-7762-417f-a87d-b1727afbac58">

P.S I have no idea when it comes to coding so sorry if I can't provide scripts to show what is happening in the background

**Comment by seerge** [comment]
@Alejuakbark Hello, this is a dublicate of https://github.com/seerge/g-helper/discussions/1033

I was desinformed by another user :) you can use build from that thread or wait for 108
