### ISSUE TITLE
Ability to Disable M1-M4 Keys

### ISSUE THREAD

**Issue by XyKER1** [seerge/g-helper#1043]
**Is your feature request related to a problem? Please describe.**
So today I cleaned my keyboard with rubbing alcohol, and it broke my M1 and M3 keys.  More specifically, the M3 (mute mic) key doesn't register any input, and the M1 key (volume down) is always being held.  I used a program called KeyTweak to disable the M1 key so I could at least adjust volume in the settings.  However, I am having numerous issues now that I think are related to this key (even though it is disabled, it looks like Windows is still getting a "null" input).  My laptop is unable to go to sleep, clipboard history instantly disappears, the Windows key doesn't do anything 3/4 of the time, and window previews disappear instantly.

**Describe the solution you'd like**
Since I saw you had options to rebind these keys, I was wondering if there was some way you could disable these keys (hopefully in a way that prevents them from sending a "null" input to Windows).  Also, it would be neat if I could bind M4 to volume up and then bind volume down to M2.

Update: it turns out Microsoft PowerToys keyboard manager is able to fully disable it so that my laptop can go to sleep and the Windows key always works.  However, this decreases gaming performance according to Microsoft, so a fix through G-Helper would probably result in no performance impact as it goes through the BIOS.  Also, it looks like the disappearing window previews were probably caused by the latest Windows update, as a workaround is to click on the taskbar before hovering your mouse over a taskbar program.

**Comment by seerge** [comment]
@XyKER1 you can just set action for those keys to Custom and leave text field empty, it will male them doing nothing (under Extra)

**Comment by XyKER1** [comment]
OK, thanks, I'll just use PowerToys then since I would prefer my laptop being able to sleep (if you could call Modern Standby that).

**Comment by XyKER1** [comment]
@seerge As a side note, is there anyway to change M4 to volume down instead (it doesn't show up in the list of options in G-Helper)?

**Comment by seerge** [comment]
@XyKER1 its possible via custom hotkey actions https://github.com/seerge/g-helper#custom-hotkey-actions

check for codes of vol up / down
