### ISSUE TITLE
Add option under laptop screen to toggle on/off the laptop screen

### ISSUE THREAD

**Issue by Ireheart** [seerge/g-helper#1046]
Add option under laptop screen to toggle on/off the laptop screen.

This would be useful if you want to use an external display only, avoid further heat generation with the laptop display.

**Comment by seerge** [comment]
@Ireheart hello,

There’s so such individual command to disable only laptop screen

What you want is called Windows Project
https://support.microsoft.com/en-gb/windows/project-to-a-screen-c35a75e2-f8e2-ad5a-9d78-9cf3fb739b59

In Win 11 you can add it to the quick access menu literally next to g-helper icon in tray :)
https://www.elevenforum.com/t/project-display-in-windows-11.3779/
