### ISSUE TITLE
Auto re-apply on start

### ISSUE THREAD

**Issue by JefFan4YC** [seerge/g-helper#1047]
Hi, thanks for your great work. To ensure the changes made to the power limit, fan curve and undervolting are applied, I have to click the modified preset every time I restart.

Could you give me advice on automatically reapplying at the start/running scenario, just like what people may do in Task Scheduler?

**Comment by seerge** [comment]
@JefFan4YC hello, app already has a Run on startup checkbox on the main screen that will make it start with system.

All settings that you have applied will be always applied on start and when needed
