### ISSUE TITLE
[Feature Request] Toggle for Mini-LED Backlight Zones

### ISSUE THREAD

**Issue by kafalier** [seerge/g-helper#105]
On the models with Mini-LED screens, there is a toggle for Backlight Zones in Armory Crate at System Configuration section. This acts as a switch between Multi-zone Backlight Control and One Zone Backlight Control. 

![image](https://user-images.githubusercontent.com/11706884/226205620-e8c69e09-8316-4f91-90a1-d2887efb6e31.png)

It is quite a relevant toggle that can be added to Laptop Screen section on G-Helper and as a use-case it can come in handy to switch between these as multizone is better for content viewing while one zone is much preferable for normal usage.

**Comment by seerge** [comment]
I wish I have a miniled screen :) I will look if I can find something related to this ...

**Comment by seerge** [comment]
@kafalier 
[GHelper.zip](https://github.com/seerge/g-helper/files/11012222/GHelper.zip)
can you try this build ? i can't test it, but i have found an endpoint, and added a button (that works as ON/OFF switch)

**Comment by kafalier** [comment]
That was very fast! I can confirm that it is the right endpoint, Backlight Control toggles between One Zone and Multi-zone as expected. Great work.

**Comment by seerge** [comment]
Ok, so it just works as you expected ?

**Comment by kafalier** [comment]
Yes. Though if you plan to add this to the app, something to consider UX wise: When HDR is active, the toggle must be on at all times. On Armory Crate, it can't be disabled when HDR is active, it's always on. It can only be disabled/enabled when HDR is not active.

Right now, when HDR is on, G-Helper's Miniled button does nothing (as expected). So if there is a way to read the HDR state from the system, that button can be disabled in such state.

**Comment by seerge** [comment]
Ok, i will check if thats easy to do. Otherwise i will add a switch as is to the next build
