### ISSUE TITLE
Can't Open/Crashing G-Helper after Sleeping

### ISSUE THREAD

**Issue by Evatriae** [seerge/g-helper#1051]
**Describe the bug**
I closed my laptop's lid, putting it into sleep mode. About an hour later I came back to my laptop, opened it up, tried to open G-Helper from hidden icons on taskbar, and it doesn't open. This has happened twice now: once yesterday and once this morning. The previous time, the G-Helper window was open when I left, and wasn't responding when I came back.  This time, my laptop was unplugged and on a low-powered custom mode. Both times, I tried to restart my laptop but it wouldn't. It got stuck in the restarting screen, so I shut it down and powered it back up. G-Helper launches normally afterward.

**Clear scenario to Reproduce**
1. G-Helper must be open, in windowed or in background.
2. (Optional) Unplug laptop.
3. Close lid or sleep.
4. (Optional) Wait for a few minutes at least
5. Open it back up and check if G-Helper window is unresponsive or unable to be opened from hidden icons.
6. (Optional) Try to restart laptop.

**Expected behavior**
G-Helper window will be either unresponsive or unable to be opened from hidden icons in taskbar. If you try to restart, laptop will get stuck in restarting screen and will need to shut down and power back on to launch G-Helper normally.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12318532/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ASUS TUF Dash F15 2022 FX517ZR

**Asus software**
- Followed recommended uninstallation of ASUS software.

**Comment by seerge** [comment]
@Evatriae hello,

I see that windows insanely spams app with events about being plugged / unplugged
```
11/08/2023 10:36:18 am: Power Mode:StatusChange
11/08/2023 10:37:00 am: Power Mode:StatusChange
11/08/2023 10:37:01 am: Power Mode:StatusChange
11/08/2023 10:37:27 am: Power Mode:StatusChange
11/08/2023 10:37:28 am: Power Mode:StatusChange
11/08/2023 10:37:57 am: Power Mode:StatusChange
11/08/2023 10:37:58 am: Power Mode:StatusChange
11/08/2023 10:38:38 am: Power Mode:StatusChange
11/08/2023 10:38:39 am: Power Mode:StatusChange
11/08/2023 10:39:12 am: Power Mode:StatusChange
11/08/2023 10:39:13 am: Power Mode:StatusChange
11/08/2023 10:39:44 am: Power Mode:StatusChange
11/08/2023 10:39:45 am: Power Mode:StatusChange
11/08/2023 10:40:16 am: Power Mode:StatusChange
11/08/2023 10:40:17 am: Power Mode:StatusChange
11/08/2023 10:43:13 am: Power Mode:StatusChange
11/08/2023 10:43:14 am: Power Mode:StatusChange
```

It's absolutely not normal behaviour (from system side). But I can't really fix that from the app side :)

1. Do you have charger connected ? 
2. Do you plug / unplug laptop during sleep ?
3. I see that you have Optimized mode selected (it will by definition try to enable / disable GPU every time laptop is plugged / unplugged). Try just to set Standard and see if it becomes better?

**Comment by Evatriae** [comment]
Hello, to answer your questions:
1. I keep my laptop plugged in, with G-Helper charge limit set to 80%.
2. The second time it happened, I unplugged it before sleep.
3. I will set it to standard mode and write back if it happens again.

Thank you.

**Comment by Evatriae** [comment]
![crash](https://github.com/seerge/g-helper/assets/141985729/bf361fe6-0557-4ab7-a404-3bedeba0f8af)
![taskbar](https://github.com/seerge/g-helper/assets/141985729/fede1f93-2f73-49d1-94cd-afb7a75bcb72)

It happened again after leaving it for 30 minutes. The second picture is me trying to left click and right click the G-Helper icon in the taskbar.

**Comment by seerge** [comment]
> Edit: I realized that the plugged/unplugged spam may be coming from the AVR my laptop is plugged into. Could that be the problem?

I have no idea, mb try to unplug it ?

1. What are the last events in the log ?
2. Does just normal switching between modes like Silent and Turbo work ok for you?

**Comment by seerge** [comment]
@Evatriae  

This is unrelated, but I have also noticed that app doesn't see (i.e. windows doesn't report any) windows input devices (for hotkeys)
```
10/08/2023 10:58:00 pm: Input device not found
```
Does hotkeys work for you ? It looks like something is wrong with your system in general (given all this spam of power mode changes, and absence of input)

I would advice to try to check whole system for being corrupt
https://support.microsoft.com/en-au/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e

And also try to hardware reset https://github.com/seerge/g-helper#how-do-i-do-a-hardware-reset-on-a-laptop

**Comment by Evatriae** [comment]
`11/08/2023 8:06:47 pm: ------------
11/08/2023 8:06:47 pm: App launched: ASUS TUF Dash F15 FX517ZR_FX517ZR :0.107.0.0en-US.
11/08/2023 8:06:48 pm: NVIDIA GeForce RTX 3070 Laptop GPU
11/08/2023 8:06:49 pm: CPU: -1 - 12th Gen Intel(R) Core(TM) i5-12450H - Intel64 Family 6 Model 154 Stepping 3
11/08/2023 8:06:49 pm: AutoSetting for Online
11/08/2023 8:06:50 pm: Input device not found
11/08/2023 8:06:50 pm: Mode = 0 : OK
11/08/2023 8:06:50 pm: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
11/08/2023 8:06:50 pm: SET GPU CLOCKS: 0, 0
11/08/2023 8:06:51 pm: FanCPU = 1E-3A-3D-40-48-4D-51-62-00-08-11-16-22-29-30-45 : OK
11/08/2023 8:06:51 pm: FanGPU = 1E-3A-3D-40-48-4D-51-62-00-0C-16-1D-26-2D-34-4A : OK
11/08/2023 8:06:51 pm: Eco flag : 0
11/08/2023 8:06:51 pm: Mux flag : 1
11/08/2023 8:06:51 pm: :DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
11/08/2023 8:06:51 pm: Screen = 144Hz : OK
11/08/2023 8:06:51 pm: ScreenOverdrive = 1 : OK
11/08/2023 8:06:51 pm: BatteryLimit = 80 : OK
11/08/2023 8:06:51 pm: TUF Brightness = 129 : OK
11/08/2023 8:06:51 pm: Monitor Power On
11/08/2023 8:06:51 pm: TUF_KB = 16712125 : OK
11/08/2023 8:06:51 pm: TUF RGB = B4-00-80-FF-FF-EB-00-00-00-00-00-00 : 0
11/08/2023 8:06:51 pm: Display configuration changed.
11/08/2023 8:06:52 pm: PowerLimit A0 = 25 : OK
11/08/2023 8:06:52 pm: PowerLimit A3 = 25 : OK
11/08/2023 8:06:53 pm: Power Mode:StatusChange
11/08/2023 8:06:54 pm: PowerLimit C0 = 25 : OK
11/08/2023 8:06:54 pm: PowerLimit C2 = 81 : OK
11/08/2023 8:06:59 pm: Latest version 0.107.0.0
11/08/2023 8:08:58 pm: Design Capacity: 76000mWh, Full Charge Capacity: 77514mWh, Health: 1.0199210526315789473684210526%
11/08/2023 8:11:22 pm: HID Device Event: Checking for new ASUS Mice
11/08/2023 8:11:24 pm: HID Device Event: Checking for new ASUS Mice
11/08/2023 8:11:26 pm: HID Device Event: Checking for new ASUS Mice
11/08/2023 9:34:42 pm: Monitor Dimmed
11/08/2023 9:34:57 pm: Monitor Power Off
11/08/2023 9:34:57 pm: TUF Brightness = 128 : OK
11/08/2023 10:19:06 pm: HID Device Event: Checking for new ASUS Mice
11/08/2023 10:19:07 pm: Monitor Power On
11/08/2023 10:19:07 pm: AutoSetting for Online
11/08/2023 10:19:55 pm: WMI event 196
11/08/2023 10:19:55 pm: TUF Brightness = 130 : OK
11/08/2023 10:34:06 pm: ------------
11/08/2023 10:34:06 pm: App launched: ASUS TUF Dash F15 FX517ZR_FX517ZR :0.107.0.0en-US.
11/08/2023 10:34:07 pm: NVIDIA GeForce RTX 3070 Laptop GPU
11/08/2023 10:34:08 pm: CPU: -1 - 12th Gen Intel(R) Core(TM) i5-12450H - Intel64 Family 6 Model 154 Stepping 3
11/08/2023 10:34:08 pm: AutoSetting for Online
11/08/2023 10:34:09 pm: Input device not found
11/08/2023 10:34:09 pm: Mode = 0 : OK
11/08/2023 10:34:09 pm: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
11/08/2023 10:34:09 pm: SET GPU CLOCKS: 0, 0
11/08/2023 10:34:10 pm: FanCPU = 1E-3A-3D-40-48-4D-51-62-00-08-11-16-22-29-30-45 : OK
11/08/2023 10:34:10 pm: FanGPU = 1E-3A-3D-40-48-4D-51-62-00-0C-16-1D-26-2D-34-4A : OK
11/08/2023 10:34:10 pm: Eco flag : 0
11/08/2023 10:34:10 pm: Mux flag : 1
11/08/2023 10:34:10 pm: :DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
11/08/2023 10:34:10 pm: Screen = 144Hz : OK
11/08/2023 10:34:10 pm: ScreenOverdrive = 1 : OK
11/08/2023 10:34:10 pm: BatteryLimit = 80 : OK
11/08/2023 10:34:10 pm: TUF Brightness = 130 : OK
11/08/2023 10:34:10 pm: Monitor Power On
11/08/2023 10:34:10 pm: Display configuration changed.
11/08/2023 10:34:10 pm: TUF RGB = B4-00-80-FF-FF-EB-00-00-00-00-00-00 : 0
11/08/2023 10:34:10 pm: TUF_KB = 16712125 : OK
11/08/2023 10:34:10 pm: Power Mode:StatusChange
11/08/2023 10:34:11 pm: PowerLimit A0 = 25 : OK
11/08/2023 10:34:11 pm: PowerLimit A3 = 25 : OK
11/08/2023 10:34:11 pm: PowerLimit C0 = 25 : OK
11/08/2023 10:34:11 pm: PowerLimit C2 = 81 : OK
11/08/2023 10:34:19 pm: HID Device Event: Checking for new ASUS Mice
11/08/2023 10:34:34 pm: HID Device Event: Checking for new ASUS Mice
11/08/2023 10:34:36 pm: HID Device Event: Checking for new ASUS Mice`

When I tried to restart, it got stuck on the restart screen for a few minutes, then bluescreened and restarted properly.

2. I can switch between profiles if that's what you were asking. I'd rather use a custom profile though.

I also followed the microsoft guide and hardware reset.

**Comment by Evatriae** [comment]
>     1. What are the last events in the log ?
[log.txt](https://github.com/seerge/g-helper/files/12326170/log.txt)
>     2. Does just normal switching between modes like Silent and Turbo work ok for you?
I can switch between modes normally when it isn't unresponsive.
>     3. What Windows Power plan do you use right now ?
Balanced

> Does hotkeys work for you ? It looks like something is wrong with your system in general (given all this spam of power mode changes, and absence of input)
All hotkeys on my keyboard work.
> I would advice to try to check whole system for being corrupt https://support.microsoft.com/en-au/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e
I followed this,
![Screenshot (3)](https://github.com/seerge/g-helper/assets/141985729/8e877cb2-d681-4943-8a71-eae8ec57eac9)
> And also try to hardware reset https://github.com/seerge/g-helper#how-do-i-do-a-hardware-reset-on-a-laptop
and this, as well as updated my Nvidia drivers. I think that solved the issue? I tried to reproduce the problem twice, but ghelper seems to be working as intended now.

Thank you. It seems as though the problem was on my side all along though, so sorry for wasting your time.

**Comment by seerge** [comment]
Ok, I'm glad it's solved now. Cheers.
