### ISSUE TITLE
fn keys are always on when Ghelper installed

### ISSUE THREAD

**Issue by Trodenn** [seerge/g-helper#1052]
My current device is the 2021 variant of the Zephyrus G15 and I have being experiencing a weird phenomenon recently which I can only associate with the usage of Ghelper one way or another

The bug that I am experiencing is that the "fn" keys are somehow always on. when I press fn + f1 and other, I still get the intended functions, but when I interact with f1 f2....etc without fn, I somehow also get to access the functions, which was not present before. 

Is there perhaps a settings page in the Ghelper app to modify this? or is this related to something with windows itself?

**Desktop (please complete the following information):**
 - OS: win 11
 - GA503QR

**Asus software**
- Armoury Crate uninstalled
- MyASUS installed

**Comment by seerge** [comment]
@Trodenn 

Cause you have turned on FN-Lock.

Press FN+C or go to Extra -> and uncheck FN-Lock there :)

**Comment by Trodenn** [comment]
OHHHHHHHHHHHHHHHHHHHHHHH, so that is why, thank you so much! and amazing reply speed

**Comment by seerge** [comment]
@Trodenn I have added FN-Lock indicator (and toggle at the same time) to main screen to prevent situations like this one
[GHelper.zip](https://github.com/seerge/g-helper/files/12322119/GHelper.zip)

**Comment by Trodenn** [comment]
Wonderful!

Sincerely,

Pierre Nanquette
