### ISSUE TITLE
Battery Charge Limit Option

### ISSUE THREAD

**Issue by Maneeha1234SL** [seerge/g-helper#1054]
I think it would be better if there was a separate option in Extra Setting to enable and disable the Battery Charge Limit Option, then we can use the My Asus App without interruption.

**Comment by seerge** [comment]
You can just set same limit as my asus and it won “interfere “ by definition:)

**Comment by seerge** [comment]
But it doesn't harm anyhow if you will set same 80% in G-Helper as well. 

Charging is handled by hardware and BIOS, not by app. Both apps can just set a simple setting. That's it.

You can set same in powershell as admin even :

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00120057, 80)
```
