### ISSUE TITLE
Custom Fan curver messed with the fan

### ISSUE THREAD

**Issue by MessyTower** [seerge/g-helper#1055]
WHen i apply custom fan curve, the fan will go to the lowest rpm on the curve and overheats the laptop

**Clear scenario to Reproduce**
apply custom fan curve

**Expected behavior**
the fan rpm lowers

windows 11
rog m16

**Asus software**
all asus software disabled

**Comment by seerge** [comment]
> ## NOTE
> Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer.  Please respect the time of the developer. Thanks.
