### ISSUE TITLE
Ghelper shuts down when switching between windows (11 home) accounts ( Asus flow x13 2023)

### ISSUE THREAD

**Issue by tk1312** [seerge/g-helper#1056]
Hi Seerge :).
first of all.thanks for the hard work my friend.
very appreciated.
i dont know if you aware. but Ghelper wont work continuously when switching between accounts on my laptop (2 active accounts. both administrators privilege).and running Ghelper as administrator as well. 
need to open manually everytime.
ps: i did copy Ghelper to both accounts. thought it will work as individual app inside each account...no good. :\
am i missing something?

thanks in advance.

T.K

**Comment by seerge** [comment]
It's a app with UI (few forms), so yes, it probably won't be able to work at 2 accounts at the same time :)

This is how things are.

You can create 2 separate Tasks in Task Scheduler to run G-Helper on logon for each user (as admin or not) and then it will launch automatically
