### ISSUE TITLE
GPU FAN RPM:0 always says 0 not showing... :(

### ISSUE THREAD

**Issue by Deathxrost** [seerge/g-helper#1059]
GPU FAN only show temprature ,problem in Fan rpm:0  not showing... always zero im just confused is that my GPU fan working or not...? i changed to every profiles balance-turbo 
standard-ultimate
not showing my fan RMP 0 always of GPU
even i restarted my lapto many times...same well no problem or fps drop while gaming session even i don't know how to understand my GPU fan actually working or not...help mann <3
![Evdj194feY](https://github.com/seerge/g-helper/assets/142084498/c468a14c-39b4-4541-bca9-3bbe13cc7f03)

ASUS TUF Dash F15 (2022) 
Model: FX517ZC
Windows: 11 Edition Windows 11 Home Single Language
Version: 22H2

Checked all the requirement for ghelper armoury crate removed cleanly, option from ghelper Extra: close all asus services done.

**Comment by seerge** [comment]
@Deathxrost hello. If it says probably it is 0 (check with your 👂:) does it ever show something not 0?

Try to reboot laptop, TUF series have a bit bugged bios and can act sometimes

**Comment by Deathxrost** [comment]
> 

man i think my gpu fan dead not working anymore i tired everything except open the panel and clean the fans...i hope so it's preety alive...let me try..lol

**Comment by seerge** [comment]
@Deathxrost any updates on the matter ?

**Comment by Deathxrost** [comment]
> @Deathxrost any updates on the matter ?
man i checked it mnn... i found out that my GPU fan is not working it's clogged and stiff and simply not rotatating properly hang hang and stop while testing through MYASUS app from microsoftstore in MYASUS checking FAN TEST stress there while back panel open i noticed CPU FAN working great reaches to it's max 6500RPM but GPU showing 0 constanly little bit move then stop the FAN is malfunctioning power is not a issue i guess motor or bearing issue i tried to clean it properly plug out socket of GPU fan out loose screw plug in properly again test through MYASUS no success....
soon going to buy a new one..... :(

G-HELPER has no issue <3  seerge  :)👍 🥇 

well actually i have to tell people i use a coolpad for my laptop that's reason sound & vibration why i don't never notice about my GPU fan sound i simply thought everything is working and i don't even know when it stopped working...i'm using armoury crate before G-HELPER i never noticed too...lol about my RPM of both CPU & GPU i know it also show there but i ignored playing sometimes games at night after work so i was careless fed up with of armoury crate already uninstall it INSTLL G-HELPER actually that cause the issue now i was happy that G-HELPER actually helps me to clearly notice about my RPM lol i'm goona burn my RTX 3050 actually i can already we warned about my GPU by looking temperature but my COOLPAD works so good lol never increase my GPU temp above 92C it's ggood plus curse too......thankx seerge for G-HELPER

**Comment by seerge** [comment]
Ok, good that you have figured it out.

Closing this then :)
