### ISSUE TITLE
App doesn't do anything

### ISSUE THREAD

**Issue by wumpus6969** [seerge/g-helper#106]
When I launch the GHelper.exe from the folder, the app launches (can see it in task manager) but nothing actually opens, I tried disabling all windows protections and launching it as admin, but it is still the same.
my model is the 2021 g15

**Comment by seerge** [comment]
Most probably you don't noticed that it stays in tray? :)

**Comment by wumpus6969** [comment]
yes, that's why I closed the ticket a couple of minutes later when I figured that out, sorry for the trouble lol
