### ISSUE TITLE
No Mapping Key: Macro1, Macro2 etc on Fresh Installed Windows ROG Ally

### ISSUE THREAD

**Issue by 1stblood** [seerge/g-helper#1061]
Hi Developer,
I just want to report that I have no such key in the screenshot you mention about Macro1, Macro2, ROG Button, etc. It looks like Ghelper was detecting as ROG Computer rather than a ROG Ally device. I think this happens to newly fresh installed Windows.

Thanks and Regards

**Comment by seerge** [comment]
@1stblood what screenshot are you talking about?

**Comment by 1stblood** [comment]
this one. I don't have it on my ROG Ally
https://user-images.githubusercontent.com/5920850/254018349-e450e124-1589-4787-bce8-7c37ffe72fbd.png

**Comment by seerge** [comment]
That’s screenshot for a laptop, if you have ally you will see only 3 bindings 

- Back pedal
- Rog key
- Control center key
