### ISSUE TITLE
G17 Series missing Keybind?

### ISSUE THREAD

**Issue by Constrat** [seerge/g-helper#1065]
**Describe the bug**
The G17 Series has M1, M2, M3, M4 and M5 (ROG). G-Helper currently shows only M1, M2, M3, M4.
In my G17, M4 works correctly and changes Mode (looks like default?), but there's no way to change that keybind.
![image](https://github.com/seerge/g-helper/assets/56174894/4a32c46b-29cc-413e-b4cc-67a5f537c5ad)
_An image describes more than a thousand words..._

**Clear scenario to Reproduce**
4. Explanation of an error or a bug

**Expected behavior**
What I expected to happen is:
![image](https://github.com/seerge/g-helper/assets/56174894/6ee804c9-fe8b-43e2-8392-54d3a747022d)
_An image describes more than a thousand words..._

**App Logs**
A new M5/ROG that opens G-Helper by default and the M4 that has Modes by default
[log.txt](https://github.com/seerge/g-helper/files/12327660/log.txt)

**Desktop (please complete the following information):**
 - OS: Win11
 - Asus ROG Strix G17 Series: G713RW

**Asus software**
No Asus softwares, and no running services

**Comment by seerge** [comment]
For your ROG = M5 (it's actually also called ROG on your device)
M4 binding is also there, it's same as FN+F4 on your device (button emits same code)

**Comment by Constrat** [comment]
> M4 binding is also there, it's same as FN+F4 on your device (button emits same code)

My FN+F4 when used changes the Aura but as G-Helper shows, but when I change M4/ROG it only changes what happens with M5 (ROG), I can't change what M4 does

**Comment by seerge** [comment]
Sorry, correction. Your M4 does same as FN+**F5** (i.e. it would toggle modes) :) (and it also emits same code as FN+F5)

**Comment by Constrat** [comment]
Aah ok makes sense as they have the same logo on top: the "fan"

**Comment by seerge** [comment]
It's missing for other devices as well :) as it's hard-binded to cycling between modes (and honestly i'm not a big fan of changing that) as you have to toggle modes somehow ...

**Comment by Constrat** [comment]
Ah makes lot of sense know! tyvm
