### ISSUE TITLE
[Feature request] Change keyboard backlight colour based on GPU mode "Eco, Standard, Ultimate"

### ISSUE THREAD

**Issue by zakimohzani** [seerge/g-helper#1068]
Hello Serge,

Thanks so far for what you've done. Now, I have a request that's based on your keyboard-heatmap idea.

Basically, I don't like to look at any control/monitoring software while I'm using the laptop. My taskbar is always hidden and G-helper is hidden within that 'hide icons' section of the Windows taskbar. But it would be cool if I could see what state the GPU is in from just looking at the keyboard.

The ideal scenario would be:
Eco --> Green
Standard --> Gold
Ultimate --> Red

That way I can easily monitor what "Optimised" mode is doing whilst I'm on the go and without opening G-helper.

Cheers

**Comment by seerge** [comment]
@zakimohzani hello, i can try to add something like that

**Comment by seerge** [comment]
@zakimohzani this build should do the thing : 

[GHelper.zip](https://github.com/seerge/g-helper/files/12336554/GHelper.zip)

**Comment by seerge** [comment]
Live in 0.111

**Comment by zakimohzani** [comment]
Thanks seerge. This is great.
