### ISSUE TITLE
Optimized mode bug fix

### ISSUE THREAD

**Issue by Billvass** [seerge/g-helper#1072]
On Asus Tuf f15 fx506hc optimized mode works great while on battery. The thing is that after restarting the system (while remaining on battery power) the system lags while on windows (basic windows animations such as maximizing, minimizing, opening start etc. lag). I believe that this issue is similar to the issue described about the 2023 G14 and has something to do with the drivers since about a year ago this didn't happen. So, I believe that giving the option ''Enable GPU on shutdown'' for this model, as you did with G14 2023, will fix this issue. Note that what I do now in order to fix it is after the restart I select standard and then optimized. This happens on both Armoury Crate and Ghelper.

**Comment by seerge** [comment]
@Billvass Optimized mode just switches between Eco on battery and Standard when plugged. That's it. Nothing else.

G14 2023 has very specific issue, when you can't disable GPU neither in AC nor in G-Helper as it's being held by system for whatever reasons. I don't think it's related to you.

In what state do you boot your system ? With GPU on or off? Does just setting Eco mode, and rebooting behave same?

**Comment by Billvass** [comment]
Thank you for the fast response. I reboot the system while the gpu is off (optimized mode on battery) and the problem appears. I strongly believe that having the option to enable gpu on shutdown would solve the issue since I wouldn't need to go to ghelper myself and change to standard and then back to optimized.

**Comment by seerge** [comment]
@Billvass i have added your model to the list, so you can experiment yourself.
[GHelper.zip](https://github.com/seerge/g-helper/files/12329386/GHelper.zip)

**Comment by Billvass** [comment]
Thank you!!! I enabled the option and the issue has been fixed! You have done a great good to the fx506hc users since this has been a known issue for some time among the reddit pages, but Asus hasn't cared to provide a solution yet. I suggest that you implement this option on the normal release of ghelper so that all users can benefit from it. Once again a big thank you!

**Comment by seerge** [comment]
Oke, i’ll keep this change in next releases then.
