### ISSUE TITLE
Is it possible to add the battery level of the peripheral in the panel？

### ISSUE THREAD

**Issue by szy854136968** [seerge/g-helper#1073]
I have some ROG wireless device including mouse and keyboard.Now I want to know their battery level as in the ARUA.Is it possible to add the battery level indication of the peripheral in the panel？That will be awesome.

**Comment by seerge** [comment]
@szy854136968 
It's already the case for supported mice. You can check the list and submit a request for one that are not in the list yet in a following topic https://github.com/seerge/g-helper/discussions
