### ISSUE TITLE
[Features Request] mV and MHz display

### ISSUE THREAD

**Issue by Constrat** [seerge/g-helper#1076]
**Describe the solution you'd like**
Next the CPU usage and Fan RPM / % having the mV of the CPU and GPU 
Armoury Crate has it why shouldn't G-Helper have it?
Could be useful for experimenting with UV.

Looking at the AC info display, maybe even adding the MHz of the CPU / GPU (maybe this is overkill and the CPU is shown in the Task manager)
(could be toggleable if users don't want those kind of info)

![image](https://github.com/seerge/g-helper/assets/56174894/25f9f1bd-3e05-494f-a656-fbe8ac8cf734)

**Comment by manciuszz** [comment]
Pointless hardware polling. If you want those stats use dedicated tools - ThrottleStop, MSI Afterburner.

**Comment by Constrat** [comment]
Why would I want other software if it can be only in one? Also considering the current update rate of cpu usage and fan speed two more stats won't change anything (especially if you can disable them)

**Comment by seerge** [comment]
@Constrat hello, i'm not a big fan of overloading UI with info that is not helpful for wast majority.

Your voltage will  vary along frequencies, and in game / heavy load you won't see app window anyway. For that purpse people use performance overlays (like nvidia one or afterburner/rtss) :)
