### ISSUE TITLE
V0.110.0 Resets the windows power plan

### ISSUE THREAD

**Issue by arizotaz** [seerge/g-helper#1077]
I do not see a need for the rest of the information as this is a very simple issue.

In the latest update, I noticed that you added the "Set Windows power mode" option.  However, is there a way to add a toggle to this?

I have my own custom power plan that I use instead of the default Windows one.  Every time I change modes, or the device is unplugged, it will reset the Windows power mode back to "Balanced"

A simple fix for this is to add a menu in the "extra" to disable this.

**Comment by seerge** [comment]
@arizotaz hello,

Power Modes were set by app all the time, now you just have UI control over that :)

If next to that you want to force a custom power plan (why btw?) you can set it in config : 
https://github.com/seerge/g-helper#custom-windows-power-plans-with-each-mode
