### ISSUE TITLE
Not running with Windows

### ISSUE THREAD

**Issue by abdullamuthana** [seerge/g-helper#1079]
The app won't start with Windows 11 this issue has been happened before like 3 updates 

[log.txt](https://github.com/seerge/g-helper/files/12331741/log.txt)

 - OS: [ Windows 11]
 - Laptop model : Zephyrus M16 GU603ZW

All Services of Asus are uninstalled 

Noted: The check box of Start With windows already checked

**Comment by seerge** [comment]
@abdullamuthana hello,

Did you try to uncheck/check run on startup checkbox? and also check FAQ section https://github.com/seerge/g-helper#app-refuses-to-run-on-startup-or-runs-without-any-icon-in-tray-on-startup ?

**Comment by seerge** [comment]
@abdullamuthana hello, any updates?

**Comment by abdullamuthana** [comment]
> @abdullamuthana hello,
> 
> Did you try to uncheck/check run on startup checkbox? and also check FAQ section https://github.com/seerge/g-helper#app-refuses-to-run-on-startup-or-runs-without-any-icon-in-tray-on-startup ?

Thank you so much the check and uncheck worked fine for me appreciate your hard work m8

**Comment by seerge** [comment]
Great
