### ISSUE TITLE
[Feature request] Allow auto-switching performance mode on (any) app launch.

### ISSUE THREAD

**Issue by musab-olurode** [seerge/g-helper#1080]
Hello.

Thanks for the amazing work so far. I was wondering if it would be possible to add an option to link specific applications to the individual performance modes so that they are automatically applied when any of the apps are launched. This would mean there would be no need to manually change the power profile when needed for a specific app.

Cheers

**Comment by seerge** [comment]
@musab-olurode hello, i was thinking about that, but properly (and without any issues) detecting specific applications can be a very cumbersome task in windows. 

Even AC for example often had problems (in my use cases) realizing that certain game is running and especially realizing that it is not running anymore. + Scanning a game library for new games, is super difficult and usually task for a dedicated game launchers apps :)

So for now, to keep app light and simple I don't plan to do that

**Comment by mmmjie** [comment]
> @musab-olurode hello, i was thinking about that, but properly (and without any issues) detecting specific applications can be a very cumbersome task in windows.
> 
> Even AC for example often had problems (in my use cases) realizing that certain game is running and especially realizing that it is not running anymore. + Scanning a game library for new games, is super difficult and usually task for a dedicated game launchers apps :)
> 
> So for now, to keep app light and simple I don't plan to do that


The strategy of the previous official program was to switch to the corresponding configuration only when the game is in the foreground, such as during enhancement. However, during actual gameplay, there are occasional switches to other windows to check information, and the frequent mode switching can be annoying.

I think as long as the configured game process is present in the process list, it should switch to the configured mode regardless of whether it is in the foreground or background. Would this approach be more user-friendly? I apologize as I'm not familiar with the implementation technology in this area, but based on my limited understanding, is it easier to detect whether the configured process is in the process list?

**Comment by mmmjie** [comment]
> > However, during actual gameplay, there are occasional switches to other windows to check information, and the frequent mode switching can be annoying.
> 
> This is exactly one of the reasons why detecting games properly is "cumbersome" as there is no definitive way to understand if currently running process is a game that user plays now, or not. As game could be alt-tabbed, hanging, or just have some launcher with same name running in background.
> 
> AC struggles with detection of processes (I experience this by myself on rog ally) so custom detection would struggle as well

Ah, I see. Thank you very much for your response.
