### ISSUE TITLE
Rear light bar not activated in Heatmap Aura mode on Rog Strix SCAR 18 2023

### ISSUE THREAD

**Issue by AuroraRock** [seerge/g-helper#1081]
Rear light bar not activated in Heatmap Aura mode, other Aura modes work fine.

[issue#858](https://github.com/seerge/g-helper/issues/858) fixed the problem with other Aura modes not lighting up the rear light bar, so it may be possible to fix the problem in the same way.

[log.txt](https://github.com/seerge/g-helper/files/12334639/log.txt)

**Comment by seerge** [comment]
@AuroraRock hello,

I'm afraid it's not the same thing :) Heatmap sets colors in a different way from pre-defined modes. It uses per-key (per-led) approach.

I can only assume that rear-led has different payload, that is not known yet / and can't be reached. 
So it's only guessing.

Try this build [GHelper.zip](https://github.com/seerge/g-helper/files/12334708/GHelper.zip)

**Comment by AuroraRock** [comment]
> @AuroraRock hello,
> 
> I'm afraid it's not the same thing :) Heatmap sets colors in a different way from pre-defined modes. It uses per-key (per-led) approach.
> 
> I can only assume that rear-led has different payload, that is not known yet / and can't be reached. So it's only guessing.
> 
> Try this build [GHelper.zip](https://github.com/seerge/g-helper/files/12334708/GHelper.zip)

Thanks for your quick reply :)  But the problem still remains.

**Comment by seerge** [comment]
@AuroraRock then it will remain as is :) I don't have a G16 strix with per-key leds, so can't debug or test anything w/o it

Sorry

**Comment by AuroraRock** [comment]
> 



> @AuroraRock then it will remain as is :) I don't have a G16 strix with per-key leds, so can't debug or test anything w/o it
> 
> Sorry

That's fine, thanks for your hard work. It is still a good software. By the way, OpenRGB doesn't allow the rear light bar to light up either, so this issue may not be fixed for a while.
