### ISSUE TITLE
ASUS services re-enabling themselves

### ISSUE THREAD

**Issue by space-alien** [seerge/g-helper#1082]
Thank you for this amazing tool!

Some time ago I had `Disabled` all ASUS services via Windows Services. Recently, I noticed that they had re-enabled themselves. Perhaps this was due to an automatic Windows Update, but I'm not sure.

Since then, I discovered that G-Helper can disable/enable ASUS services.

So, I wonder if G-Helper could detect if the ASUS services have re-enabled themselves, and automatically re-disable them in that case? (Apologies if G-Helper does this already.)

If this is not a good idea, perhaps there could be an option to have a notification if G-Helper detects that the ASUS services have re-enabled themselves.

The reason for all this is that my 2021 G15 ROG Strix is regularly hanging due to a HYPERVISOR_ERROR (20001), and I'm trying to figure out what could be causing it!

**Comment by seerge** [comment]
@space-alien hello,

This would happen only when you update Asus  System Control Interface (via windows update or myasus or manually via g-helper)

Then you need to stop services again as it would reinstall them.

It’s being updated quite rarely anyway, so i don’t see any reasons to actually add constant checks for that in the app on this stage :)

**Comment by space-alien** [comment]
Thanks! Yes, that makes sense.

For me this issue happened a couple of times this year, due to automatic Windows Updates. I had no idea that the services had re-enabled themselves, or how long ago.

So, I'm considering writing some kind of startup script to detect and notify for this.

**Comment by seerge** [comment]
Sure! :) You can try to do some script, if it bothers you :)
