### ISSUE TITLE
v0.111 Limit GPU Core Clock for G14 2022 possible?

### ISSUE THREAD

**Issue by EvilKilla** [seerge/g-helper#1090]
Hi seerge. I'm using the G14 2022 with AMD 6800s. Is there any way to limit the GPU Core Clock. I found out, that the coils are whining when the clock is over 1,6 GHz, but never find a solution to hard limit the clock.

tyvm

**Comment by seerge** [comment]
@EvilKilla hello, unfortunately AMD gpu is totally locked, you can set something only for NVidia :(
