### ISSUE TITLE
Add a AniMe Matrix (.matrix file) import function

### ISSUE THREAD

**Issue by LEveLiQ** [seerge/g-helper#1094]
**Is your feature request related to a problem? Please describe.**
Some models like the G14 I own has AniMe Matrix which you can customize using Armoury Crate, and I created one using it, but AC was so bad that I decided to switch to GHelper, but its gif importing function is.... bad.

**Describe the solution you'd like**
Make GHelper be able to import .matrix or .webmatrix file

**Describe alternatives you've considered**
The only alternative I could consider was using AC and GHelper together which is not very ideal

**Additional context**
none

**Comment by LEveLiQ** [comment]
contrary to using custom .matrix files, setting gif files are a pain because of following reasons:
- you can't really move or zoom the file so you don't have a single idea about what it would look like on the matrix
- it looks hella blurry
- it speeds up itself no matter what the original gif file speed was

**Comment by seerge** [comment]
Well, reading that matrix file will make no change, cause it looks different cause whole algorithm of showing is image is probably different :) it has nothing to do with your format.

**Comment by seerge** [comment]
@LEveLiQ you may want to check latest https://github.com/seerge/g-helper/releases/tag/v0.119 I have added a bit more control over Anime Matrix pictures , including native GIF speed, scaling quality (that affects if it will fit picture smoothly or sharper), and position controls

**Comment by LEveLiQ** [comment]
@seerge works pretty nice, in fact it is even better than AC since I could see how's the animation in real time instead of boilerplate of saving multiple files
would appreciate it if there are some description of what each quality does

**Comment by seerge** [comment]
@LEveLiQ you can read about interpolation methods here
https://learn.microsoft.com/en-us/dotnet/api/system.drawing.drawing2d.interpolationmode?view=dotnet-plat-ext-7.0

**Comment by LEveLiQ** [comment]
@seerge nice, also it would be great if you could add an approximate overlay to the editor
appreciate your work as always
