### ISSUE TITLE
Detect G14 2020 GPU power draw

### ISSUE THREAD

**Issue by x864** [seerge/g-helper#1095]
One of the biggest issues with the 2020 G14 is that sometimes, even if there aren't any apps using the NVIDIA GPU, it doesn't go to sleep automatically and keeps drawing power, which leads to battery drain. 
Since we don't have the GPU modes in the 2020 version, and since disabling the GPU in the device manager leads to high CPU temperatures for some unknown reason, this can be quite frustrating since there's no actual solution.

The only solution to force the GPU to go to sleep is to :
- disable it in device manager
- wait 2 seconds
- enable it again

the gpu then stays active for a few seconds, then goes to sleep, and the power draw is fixed.
This process is similar to the "Reset GPU" button in G14ControlV2 (the electron version)

When the GPU goes to sleep, it isn't detectable in HWInfo, except if you check the "wake disabled GPUs" in the settings before starting it. Since this project also uses WinRing0, this should be doable if I'm not wrong. 

A fix/solution that could be implemented for the 2020 model could be:
- if the laptop isn't plugged in, watch if the GPU is active/drawing power. If so, disable it (like in the device manager) and enable it again. Then the GPU should go to sleep after a few seconds and the power draw should be fixed.

**Comment by seerge** [comment]
@x864 hello, app doesn't "monitor" or "control" your computer anyhow actively in real-time :) it can just set a bunch of modes and some limits, the rest of the it just stays silently in tray and does nothing.

Therefore it will be way too much to force it monitor power of GPU, and restart it , etc

Restart via device manager is already in the app, but it's being offered as "last resort" in some VERY rare cases for newer models, when they refuse to disable GPU (set eco) normally. And I have found this "operation" is a bit tricky, as once my laptop literally got BSOD from disabling GPU in device manager.

I can add a button (next to stop all GPU apps) that will offer a manual restart of GPU, but I'm not sure if this is a good idea. As average Joe will start clicking it, manage to get a crash and will go on reddit blaming bad G-Helper as usual :)

**Comment by x864** [comment]
@seerge I understand the concern on monitoring GPU activity, and BSOD for the average joe. It could be optional though? HWInfo stays in the background when minimized, and doesn't seem to be using much resources. A check could be done every minute, or even every five minutes. Some "experimented" users only checkmark in the settings? I don't know.
Thanks for your hard work anyway :)

**Comment by seerge** [comment]
@x864 it's very not transparent logic :) How would app know that GPU is not needed anymore? 

I have digested it a bit, and I won't be adding it explicitly in UI for now.

But there is a solution for you to do it quickly

Just create a bat file (or ps file) that has to be run as admin with a following command, it restarts GPU in device manager (with 5 sec waiting delay between starting it again)

```
$device = Get-PnpDevice | Where-Object { $_.FriendlyName -imatch 'NVIDIA' -and $_.Class -eq 'Display' }; Disable-PnpDevice $device.InstanceId -Confirm:$false; Start-Sleep -Seconds 5; Enable-PnpDevice $device.InstanceId -Confirm:$false
```

**Comment by x864** [comment]
@seerge thanks for the quick answer. 
To clarify the idea; I think it should be an optional feature where the app should consider that GPU is not needed on battery. 
I don't think that a lot of people use the GPU when the laptop is not plugged in, since it is a huge power drain. 
Anyway, I understand your choice to not implement it.
