### ISSUE TITLE
Bsod after instaling

### ISSUE THREAD

**Issue by EugeneNey** [seerge/g-helper#1097]
- OS: Windows 11
 - Laptop model asus tuf gaming f15 fx507zv

**Asus software**
- Armoury Crate deleted
- MyASUS installed deleted

**Additional context**
After installing the application according to the instructions, in some games I received a bsod, here is the error code - 0x0000013a, what could be the reason for this? 
![image](https://github.com/seerge/g-helper/assets/36205733/7578e939-cd69-4f17-8a9f-d2a37637e71a)

[log.txt](https://github.com/seerge/g-helper/files/12353655/log.txt)

**Comment by manciuszz** [comment]
Are you using any undervolt/overlock? That could lead to memory corruption which in turn could BSOD. 

I don't think this is G-Helper related though. I'd start from checking the drivers as there's a high chance that a recently updated driver is causing [0x13A KERNEL_MODE_HEAP_CORRUPTION](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x13a--kernel-mode-heap-corruption). Try reinstalling GPU drivers using [Display Driver Uninstaller](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html).

**Comment by seerge** [comment]
@EugeneNey i have no idea why you get your baods :) app just sets one of 3 predefined performance modes, and fan curves. 

It’s not related anyhow.

Check your drivers and system.

**Comment by EugeneNey** [comment]
when I get back from work, check the drivers, but it confuses me that the problems started after installing ghelper, before that there were no such problems
