### ISSUE TITLE
Updates notification

### ISSUE THREAD

**Issue by MDowski** [seerge/g-helper#1098]
Would it be possible - and by this I mean: _does it make sense_ - to indicate new updates? This is the thing that I'm missing from Armoury Crate or MyASUS - touch of red that shows there is something.

It could be done either by making updates icon red, or adding a symbol after "Updates" text string (either superscript or inline), like:
**[ Updates 🔴 ]** or **[ Updates ⭕ ]** or **[ Updates🔺]**.

**Comment by seerge** [comment]
@MDowski may be, but currently app doesn't check for them at all unless you click on a button. And whole check process takes a bit of resources, so i'm not 100% sure - when to run it (in order not to hammer battery life or some gaming experience)

**Comment by MDowski** [comment]
@seerge maybe like 30-60 seconds after the app starts? As we run G-Helper on startup, and this is a time where a lot of apps usually fight for resources, that delay could be handy. Checking it once shouldn't make a difference and this seems to be sufficient. 

Or maybe even once a G-Helper starts, but not more often than once 24/48 hours?

This could be convenient as we wouldn't have to check updates at all, to see if there are new.

**Comment by AudreyAP** [comment]
On my machine (and most) driver updates are almost entirely handled by windows update with the exception of bios - I definitely don't need it to auto-check at startup. A toggle for this would be great to keep ghelper light :)

**Comment by MDowski** [comment]
@AudreyAP I believe that adding a toggle for every-single-thing is what can clutter G-Helper the most. Not some background activity that takes 2 seconds every other day.

**Comment by seerge** [comment]
@MDowski @AudreyAP actually bios update check worth literally nothing, it’s drivers that are resource heavy cause it doesn’t only load list of available stuff but also compares versions with each device in device manager 

Mb check only for BIOS updates automatically?

**Comment by MDowski** [comment]
@seerge Interesting, because I haven't got for example System Interface in my Windows Update, but my BIOS. Different thing for different model years?

**Comment by seerge** [comment]
@MDowski I guess when Asus releases each "driver" they kind of mark what device should be affected. So they may just forget you ... :)

Windows indeed updates BIOS as well btw. But same as with the drivers, usually with a small delay after they appear on asus website.

**Comment by MDowski** [comment]
If so, maybe then this update check isn't necessary at all?

**Comment by seerge** [comment]
@MDowski may be :) for me personally it's not crucial to get a badge with updates, i would just click a button once in a week by myself 

+ most important drivers are actually for GPU + Chipset. And those I get from AMD / NVidia directly anyway, as ones form Asus are outdated.

**Comment by MDowski** [comment]
@seerge I think you're right. :) It wasn't the best Idea as I can see.

**Comment by seerge** [comment]
I would just put it on hold for now. Mb one day I can add a call to startup for this.
