### ISSUE TITLE
Feature Request: Some way to mark a performance mode as “should be ignored”

### ISSUE THREAD

**Issue by hotbarlo** [seerge/g-helper#1101]
I think it’s GREAT that the original performance modes are read only. But whenever I’m selecting my custom performance mode I have to select them before I get to the ones I want. Would be great not having to do this.

Could be a power user setting in the json file. Honestly, I know this is very specific to my use cases, just wanted to raise the question.

Once again, thanks for all the hard work!

**Comment by seerge** [comment]
You can select them directly via fans+power dropdown. I'm not a fan of overloading UI with million of buttons.

You can customize default modes with same success as well.
