### ISSUE TITLE
G17 Power Limits not applying

### ISSUE THREAD

**Issue by Constrat** [seerge/g-helper#1103]
**Describe the bug**
Customizing CPU power limit -> `Apply Power Limits` will not apply them.
To apply them you also need to toggle "Apply custom fan curve"

**Clear scenario to Reproduce**
1. Go to `Fans + Power`
2. Set custom power limits (I've tested lower limits)
3. Tick the `Apply Power Limits`
4. Power limit should get applied and CPU should get throttled down to a low GHz.
This doesn't happen.
To make it happen you ALSO need to tick `Apply Custom Fan Curve`

**Expected behavior**
Custom power limits should get applied already with ticking the  `Apply Power Limits`.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12363537/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - Win11, G713RW (ROG STRIX G17 Series), G-H 0.112.0

**Asus software**
- No Asus services running
- Only G-Helper

**Comment by seerge** [comment]
@Constrat welcome to the club of devices that require both checkboxes to work :) You seem to be a long term user, did you spot it only now, or was it happening before ?

**Comment by seerge** [comment]
@Constrat 

Try this build. The fix i'm adding for such cases - is it will just silently apply a fan curve next to power limits (as in AC you can them only together 

G14 2023 (including mine) are also "suffer" from same thing. 

[GHelper.zip](https://github.com/seerge/g-helper/files/12363651/GHelper.zip)

**Comment by Constrat** [comment]
> 

Now that you mention it. It was when I first tried G-Helper. The first implementation of the custom power limits were working as "expect" if I do remember correctly. I'll try the build right now. Tomorrow (as I'll be a bit more awake XD I'll try the older build to check if it was working properly before)

**Comment by Constrat** [comment]
> GHelper.zip

Works as expected. Have you perhaps noticed a pattern of which devices are "locked" as in can't be controlled singularily and have to power limit + custom fan?

I wasn't expecting the Zephyrus of suffering from this considering it's a completely different model from the, say, G15, G17, SCAR15, SCAR17. Have you noticed other issues regarding these devices?

**Comment by seerge** [comment]
@Constrat so far it's only 2 https://github.com/seerge/g-helper/blob/592c4aa07aa6ffb83240d7b5d48f586cdb199ff6/app/AppConfig.cs#L355 + yours

I guess majority just don't spot it as they apply both at the same time (as they did in armoury)
