### ISSUE TITLE
Add Advanced features for Intel processors

### ISSUE THREAD

**Issue by andreazann** [seerge/g-helper#1104]
Is it planned to add the Advanced tab also for Intel processors? With the Target temperature feature and undervolting for Intel.

Thank you,
Andrea

**Comment by seerge** [comment]
@andreazann hello, it's not planned :) as Intel has absolutely functional https://www.intel.com/content/www/us/en/download/17881/intel-extreme-tuning-utility-intel-xtu.html

+ some new devices from Asus has undervolting for intel via bios even

While AMD has none, so I had to add it :) 

Sorry
