### ISSUE TITLE
Low target value of CPU temp limit

### ISSUE THREAD

**Issue by russellmm** [seerge/g-helper#1105]
**Is your feature request related to a problem? Please describe.**
no problem

**Describe the solution you'd like**
Currently g-helper only allows a temp limit of 75c to be set in the advanced menu.  UXTU allows for a much lower setting. I try to keep my laptop below 45C when on battery to keep it runner cooler.

**Describe alternatives you've considered**
I could use UXTU to set this limit lower but would rather be able to use g-helper and then I really have no need for UXTU. 

**Additional context**
a few screen shots provided for clarity. 

![2023-08-16 14_42_55-Universal x86 Tuning Utility](https://github.com/seerge/g-helper/assets/35648773/7f0071c1-8609-4b57-a50d-881f744b9400)
![2023-08-16 14_40_42-Fans and Power](https://github.com/seerge/g-helper/assets/35648773/619f6b80-47c1-4d0b-97bb-9e153a14bcb5)

**Comment by seerge** [comment]
@russellmm hello,

I have added 2 optional params for ``%appdata%\ghelper\config.json`` that let you override (in exotic cases) min temp limit and min uv slider values in the app. Edit config before launching app.

```"min_temp" : 45,```
```"min_uv" : -40,```

[GHelper.zip](https://github.com/seerge/g-helper/files/12367330/GHelper.zip)

**Comment by russellmm** [comment]
Thanks!

**Comment by Moorole** [comment]
finally i can go wild on my undervolt... :D
