### ISSUE TITLE
Incorrect power scheme after exiting sleep mode.

### ISSUE THREAD

**Issue by extremalex** [seerge/g-helper#1106]
Issue appeared in the recent version 0.100 or 0.110.

Description:

1. Enter sleep mode (automatic or manually).
2. Exit from sleep mode.
3. Current power scheme is set to Advanced Battery (not sure of the exact title in English, it is placed between Power Save / Economy scheme and Balanced) regardless of the previously used scheme.

Expected behavior:

Power scheme after exiting sleep mode remains unchanged.

Log:

17.08.2023 01:05:31: Monitor Power Off
17.08.2023 01:05:31: Backlight:5D-BA-C5-C4-00
17.08.2023 01:05:41: Monitor Power On
17.08.2023 01:05:41: AutoSetting for Online
17.08.2023 01:05:42: Input: \\?\hid#vid_0b05&pid_1866&col03#7&289d55ad&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
17.08.2023 01:05:42: Mode = 2 : OK
17.08.2023 01:05:42: GET CLOCK LIMIT: 0
17.08.2023 01:05:42: GET GPU CLOCKS: -250, 0
17.08.2023 01:05:42: Power Plan 381b4222-f694-41f0-9685-ff5bb260df2e:OK
17.08.2023 01:05:42: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
17.08.2023 01:05:42: Eco flag : 0
17.08.2023 01:05:42: Mux flag : -65536
17.08.2023 01:05:42: DELL S2721DS:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_HDMI: \\.\DISPLAY1
17.08.2023 01:05:42: BatteryLimit = 100 : OK
17.08.2023 01:05:42: USB-KB 0x1866:5D-BD-01-00-00-00-00-FF
17.08.2023 01:05:42: USB-KB 8273HID-совместимое устройство, определенное поставщиком\\?\hid#vid_0b05&pid_1866&col04#7&289d55ad&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-00-00-00-00-EB-00-00-FF-FF-FF-00-00-00-00
17.08.2023 01:05:42: Auto:5D-BA-C5-C4-00
17.08.2023 01:05:43: UV: -20 OK

OS: Windows 10 Pro
ASUS G733QR
Installed Armoury Crate (or it's services installed)

**Comment by seerge** [comment]
@extremalex from the log it sets everything absolutely correctly. 

https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/customize-power-slider

```
961cc777-2547-4f9d-8174-7d86181b8a7a: Sets the slider to the Better Battery mode
```

**Comment by extremalex** [comment]
But I use extended (by AMD or ASUS) power modes - mostly Silent.  They are not included in the proposed list of power modes.

**Comment by seerge** [comment]
You mix power modes and power plans

**Comment by extremalex** [comment]
Nice! Will try to do this, thanks.
