### ISSUE TITLE
OD problem

### ISSUE THREAD

**Issue by EugeneNey** [seerge/g-helper#1111]
**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: win 11 pro
 - Laptop model - asus tuf gaming f15 fx507zv

**Asus software**
- Armoury Crate (or it's services installed) - deleted
- MyASUS installed - deleted
- Other Asus services running in background  -  no

**Additional context**
There were problems with bsod, I did a clean installation of Windows, installed ghelper, but when you turn on the 144Hz-Od mode, you get the feeling that the od mode does not work correctly, before that everything worked smoothly in games (without loops), now in the same game there are loops when turning quickly. Maybe I didn't install some driver?
[log.txt](https://github.com/seerge/g-helper/files/12372576/log.txt)

**Comment by seerge** [comment]
@EugeneNey hello, this is not "help with my computer" support line.

Overdrive setting is the same for ALL devices. App is able toggle it on or off.

```
17.08.2023 21:00:03: ScreenOverdrive = 1 : OK
```

Your device supports it. I have no idea what does "loops" mean.

If you don't like overdrive , you can completely disable it from Extra menu.

**Comment by EugeneNey** [comment]
If "everything works great" in your application, why does crate od work correctly when using armory?

**Comment by seerge** [comment]
@EugeneNey you can set it with armoury, if it's better.

I don't tolerate rudeness here as well.
