### ISSUE TITLE
GPU section disappears after resuming from sleep (TUF FX506LU)

### ISSUE THREAD

**Issue by thepriyamkalra** [seerge/g-helper#1112]
**Describe the bug**
This is an issue I have had for quite a while, but never got around to reporting.
The entire "GPU" section of the app goes missing whenever I resume from sleep
I thought it had something to do with the GPU "sleeping",
but even after launching a game, which surely uses the GPU, the issue persists.
**Restarting G-Helper resolves the issue**.

**Clear scenario to Reproduce**
1. Open G-Helper
2. Put laptop to sleep
3. Resume from sleep
4. Open G-Helper

**Expected behavior**
GPU section should be unaffected.

**App Logs**
[log_copy.txt](https://github.com/seerge/g-helper/files/12373529/log_copy.txt)

**Screenshots or screencasts**
After resuming from sleep:
![Screenshot (150)](https://github.com/seerge/g-helper/assets/43999863/340de404-c88d-426b-8c63-396e385f53a6)

Before putting laptop to sleep (or after restarting the app):
![image](https://github.com/seerge/g-helper/assets/43999863/ca24b55b-7d79-4a7f-9646-b6558ebd51f3)

**Desktop:**
 - OS: Windows 11
 - TUF FX506LU

**Asus software**
None

**Comment by seerge** [comment]
@thepriyamkalra it was hidden by the app cause your bios has reported that both Eco and Mux switches are not supported at all

```
8/18/2023 2:23:22 AM: Eco flag : -65536
8/18/2023 2:23:22 AM: Mux flag : -65536
```

Looks like another bug in bios

Does it happen after every sleep ?

**Comment by thepriyamkalra** [comment]
> @thepriyamkalra it was hidden by the app cause your bios has reported that both Eco and Mux switches are not supported at all

Yes, this is a 2020 TUF which does not have any "GPU modes" (the display is hardwired to iGPU) but hiding the entire section including thermals and fan speed is not needed.

> Can you check this build (after sleep) and post a log here ? (it will behave same, i have added some debugging)
> [GHelper.zip](https://github.com/seerge/g-helper/files/12376780/GHelper.zip)

Here you go, put to sleep and resumed once after starting new build: [log_copy.txt](https://github.com/seerge/g-helper/files/12384781/log_copy.txt)

**Comment by seerge** [comment]
@thepriyamkalra this build should behave OK
[GHelper.zip](https://github.com/seerge/g-helper/files/12385604/GHelper.zip)

**Comment by thepriyamkalra** [comment]
> @thepriyamkalra this build should behave OK [GHelper.zip](https://github.com/seerge/g-helper/files/12385630/GHelper.zip)

Yup. All good. Thanks!
