### ISSUE TITLE
Keystone light is always on with G17 G733ZX

### ISSUE THREAD

**Issue by mntawfik** [seerge/g-helper#1113]
**Describe the bug**
After installing G Helper, the keystone light on the laptop right side won't turn off (although the key is outside)

**Clear scenario to Reproduce**
1. Disable all ASUS services via msconfig. 
2. Install G Helper on ASUS ROG Strix Scar G17 series.
3. Play around with the F4 button (AURA) until you reach the 1 exactly before static. Keystone light turns on.

**Expected behavior**
This light should always be off except when the keystone key is plugged inside the laptop for a short time then switches off.

**Logs**
[log.txt](https://github.com/seerge/g-helper/files/12373546/log.txt)

**Screenshots or screencasts**
![keystone issue](https://github.com/seerge/g-helper/assets/52463433/c7d26fe2-191b-4307-b59e-0e086de657ae)

**Desktop (please complete the following information):**
 - OS: Edition	Windows 11 Pro 22H2 build 22621.2134
 - Laptop model: ASUS ROG Strix Scar G17 G733ZX

**Asus software**
- MyASUS is installed
- Armoury Crate installed but completely disabled via msconfig (M5 button calls G Helper)
- No ASUS services working in the background (Asus services running: 0 as per below image)
<img width="687" alt="image" src="https://github.com/seerge/g-helper/assets/52463433/6c7965a7-8622-49f0-a467-f9f6abec4d7c">

**Additional context**
This keystone issue never happened before. 
Workaround is to stay for sometime on the AURA style just before static. Keystone light will go off (sometimes).
Another forceful workaround is to completely shutdown the laptop as restarting doesn't work.

**Comment by seerge** [comment]
@mntawfik hello,

You have a similar issue someone else was mentioning as part of https://github.com/seerge/g-helper/issues/967

Problem is that keystone has some strange and unknown to me (and to open source community) code in payload to be turned off. And without device itself, it's practically unrealistic for me to figure it out.

I assume openRGB also can't turn off keystone individually ? https://openrgb.org/ 

As far as I remember, it will light up only from Heatmap mode, others don't affect it.

So my simple advice would be to turn it off using AC (once :) and then just not use heatmap in the app :) other modes shouldn't touch it.

**Comment by mntawfik** [comment]
I believe that our laptop models should have a specific version of GHelper that doesn't have heatmap. so cycling through the AURA won't turn on the keystone light.. Is that doable? thanks in advance. This is amazing anyway.

BTWM, I found another issue: FN+V used to cycle through the Dolby Vision modes.. same goes for the Dolby Access program. Now both are not working. So long for the Dolby Vision feature.

**Comment by seerge** [comment]
@mntawfik there is a special "heatmap" for you even, check this topic how to turn it on 
https://github.com/seerge/g-helper/discussions/1027

As for Fn+V , it's not "Dolvy Vision", it's visual styles . This is addressed in FAQ https://github.com/seerge/g-helper#how-do-i-set-different-visual-styles . App doesn't do it, but there is other solutions including asus standalone app

**Comment by mntawfik** [comment]
another issue found, G17 have M5 button. Now mapping M4/ROG goes to our M5 instead. And M4 is not customizable.

**Comment by seerge** [comment]
@mntawfik in upcoming release I changed label for Strix'es to M5/Rog. 

M4 does same as Fn+F5 (it emits same code even) - i.e. cycles through profiles. It's intentionally not customisable as some combination for that have to exist. Also Shift + FN + F5 (or Shift + M4) will cycle through profiles backwards.

**Comment by mntawfik** [comment]
Regarding the keystone issue:
1. I've shutdown GHelper
2. Added ""old_heatmap" : 1," at the top of the *.json file and saved.
3. Started GHelper and cycled through still the keystone light is on.. 

do I have to shutdown? or am I missing something..

For the visual styles.. Yes, I downloaded the app "Game Visual" but still FN+V is not working. So need to manually select the style.. which is not perfect but OK.

Thanks a lot for your help.

**Comment by seerge** [comment]
@mntawfik it won't turn your keystone OFF unfortunately. You have to do it somehow else (via AC probably). 

But what it will do - that "olad" heatmap won't affect keystone anymore (As it works in a different way)

**Comment by mntawfik** [comment]
Keystone issue is resolved after restarting.. 

But I found a new one.. Airplane mode button / F12 doesn't work even when FN-Lock is ON! except if you click FN+F12..

**Comment by seerge** [comment]
@mntawfik F12 is always reserved by Windows. It’s impossible to re-bind it for software fn-lock

I’m closing this as completed then

**Comment by mntawfik** [comment]
sorry if I'm bothering you but how can I change the GPU temperature target that's currently locked at 87C only? also what about the dynamic boost locked at 25W?

**Comment by seerge** [comment]
@mntawfik by dragging sliders down in GPU section?

**Comment by seerge** [comment]
@mntawfik you can't do that, ranges are locked by Asus for AC
