### ISSUE TITLE
Wrong Chinese translation of "Auto adjust Windows Power Modes"

### ISSUE THREAD

**Issue by Mofimg** [seerge/g-helper#1116]
The translation on strings is correct, but it is wrong in the program.
<img width="382" alt="屏幕截图 2023-08-18 172657" src="https://github.com/seerge/g-helper/assets/28688116/3301d887-85d1-4eb9-a1bb-b6444c6c3a74">
<img width="636" alt="屏幕截图 2023-08-18 172823" src="https://github.com/seerge/g-helper/assets/28688116/e4f4c413-4828-4b2e-ade8-ab786608a2f3">

**Comment by seerge** [comment]
@Mofimg hello,  adjust power modes label is removed in last versions at all :)

Its not relevant anymore
