### ISSUE TITLE
Shift + Volume changes keyboard backlight

### ISSUE THREAD

**Issue by ItxWeird** [seerge/g-helper#1119]
**Describe the bug**
Holding shift and changing the volume changes the keyboard backlight

**Clear scenario to Reproduce**
1. Hold shift
2. Use any physical volume buttons, e.g. External keyboard knob in my case

**Expected behavior**
Should just change the volume and not the keyboard backlight

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12379498/log.txt)

**Desktop (please complete the following information):**
 - Windows 11 Home
 - G14 2021 (GA401QM)

**Asus software**
None

**Additional context**
Hasn't occurred before, could just be something in a newer update, if it is, can we have a toggle for this option.

**Comment by seerge** [comment]
@ItxWeird it indeed does, as this is one of the bindings . Check readme please https://github.com/seerge/g-helper#extra-keybindings :) you can turn it off if you don't like it.

**Comment by ItxWeird** [comment]
Is it possible just to disable this keybind? Because I do use the Open G-Helper keybind, and from understanding adding that setting would disable all extra keybinds

**Comment by ItxWeird** [comment]
I've tried several times now adding the line `"skip_hotkeys":1,` to my config.json, and the hotkeys just keep on working. I try restarting the app, editing the json when the app is closed, etc, but the setting does not persist. I've made sure the json is valid making sure there are no extra commas, but I just can't disable it.

**Comment by seerge** [comment]
@ItxWeird can you upload here full config ? And do you use latest release?

I just tried and it all works ok

```
  "skip_hotkeys": 1,
```
