### ISSUE TITLE
App Freezes when charger is unplugged while external display is connected through XGMobile USB-C Port

### ISSUE THREAD

**Issue by gokulbalram** [seerge/g-helper#1124]
Device: Flow X16

From what I understand, the USB-C port in the XGMobile port is directly connected to the dGPU, so I connect my display to the device using said port. Issue is, when I set the GPU Mode to Optimized, and proceed to unplug the charger, the app completely freezes up, and won't work until I either connect the charger, or disconnect the display

**Comment by seerge** [comment]
@gokulbalram  hello, post a log here as it was asked in issue description.

Do you have "Keep GPU disabled on USB-C" checked under Extra ?
Does it behave ok when you have it in Standard instead of Optimized ?

**Comment by gokulbalram** [comment]
Hmm weirdly enough, I am unable to replicate this again, in an attempt to give you a clean log, I deleted the older log, and attempted to recreate it, but as of now, the app has no issues when I unplug the charger.
