### ISSUE TITLE
Fans control not working properly on Strix G15 

### ISSUE THREAD

**Issue by H1m4ru** [seerge/g-helper#1128]
**Describe the bug**

Since a recent (and unknown) update, my laptop is not handling well with fans control, setting it to 0% most of the time with high enough temperatures to activate them and only applying the power modes correctly using the Apply custom curve option, and even with that workaround, some power modes can't turn on the fans at all. Also, sometimes iGPU temperature shows up for only a few seconds and then disappears. 

**Expected behavior**
I was expecting that fans control and power modes could work together fine and without these random bugs which are happening to me, avoiding high temperatures and thermal throttling.

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/12384388/log.txt)

**Screenshots or screencasts**

![image](https://github.com/seerge/g-helper/assets/103531824/701c6b7b-898e-45fd-9895-5edc2ad0a252)
![image](https://github.com/seerge/g-helper/assets/103531824/7ab3810b-cb9f-41d7-aa54-8389354914e3)
![image](https://github.com/seerge/g-helper/assets/103531824/b236bbf7-90da-4a8a-a162-19eccebff23c)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Laptop model: ROG Strix G15 G513IE-HN004W

**Asus software**
- Armoury Crate (or it's services installed): NO
- MyASUS installed: NO
- Other Asus services running in background: NO

**Additional context**
I don't know if that's important to tell, but i debloated Windows 11 and NVIDIA drivers a bunch of days ago, using BloatyNosy and NVCleanstall.

**Comment by cosmicAP** [comment]
while my laptop (asus tuf dash 2022) fans are working they work when reaching critical temp. there are way too high and i am don't feel safe operating at these temps 

![Screenshot 2023-08-19 061836](https://github.com/seerge/g-helper/assets/142401105/3a35f5b0-6f95-437b-a3ed-d4edf90928e0)

**Comment by H1m4ru** [comment]
> can you tell how to get the %app data?
Press Win + R, then write %appdata% and press Enter

**Comment by cosmicAP** [comment]
> > can you tell how to get the %app data?
> 
> Press Win + R, then write %appdata% and press Enter

thanks man , hope your issue get resolved asap

**Comment by seerge** [comment]
@H1m4ru hello, your fans are controlled by BIOS not by the app.

I didn't change anything related to fans over last 5 months and based on your screenshots in ALL 3 cases it behaves correctly.

The first non-zero (and non-OFF) dot on fan on 2nd and 3rd screenshot start at 60C, before it's OFF. So it's indeed OFF.

Also please keep in mind, that even in case of custom fan curves BIOS can follow them only approximately, or with hysteresis. It depends on how it's programmed there inside.
