### ISSUE TITLE
[Feature request] Match keyboard backlight with Windows accent color.

### ISSUE THREAD

**Issue by Arakhor** [seerge/g-helper#1130]
I have an app that rotates my wallpapers depending on the time of day, and have Windows set to pick accent color automatically.
Would be really nice if my keyboard backlight matched current accent.

**Comment by seerge** [comment]
@Arakhor hello,

Detecting each change in accent color is quite cumbersome task by itself :) So I'm afraid it's an extremely exotic and narrow case, sorry.

You can try to write some script by yourself tho, as setting color for keyboard is not that difficult

Closing as not planned
