### ISSUE TITLE
Got an update for a BIOS that I’m not sure is supported

### ISSUE THREAD

**Issue by midnightgospel** [seerge/g-helper#1133]
Was told to update to version 415 of bios for my GA503QR. According to Asus's site it doesn't exist. So I’m not sure where it's pulling from. Also, after updating to it, I have some bad bugs. I'd say it should probably be blocked.

**Comment by seerge** [comment]
@midnightgospel 

Your update is taken from same feed as MyASUS. And it is also available on asus website

<img width="1224" alt="Screenshot 2023-08-20 at 01 13 20" src="https://github.com/seerge/g-helper/assets/5920850/486041d2-fb61-49e0-bc51-d86700fbd77f">

**Comment by ke1ne** [comment]
I use BIOS 415 on GA503QR. Got some BIOS settings reset after updating, but G-Ghelper works stable.

**Comment by midnightgospel** [comment]
Yeah I’m not sure how I didn't see it. I went to Asus's site and it wasn't there. But then someone mentioned it on discord and it was there. Maybe I had an old cached page or something. Regardless I see it now. Just not sure on my keyboard/wifi issues 🤷🏻‍♂️

Thank you for the comments though
