### ISSUE TITLE
About the rear light effect of the box cover

### ISSUE THREAD

**Issue by Trovoy** [seerge/g-helper#1134]
How do I turn off the charging light effect when the box is powered on behind the lid, I was not able to find that setting in the options. I may have missed it, sorry for the trouble.

**Comment by seerge** [comment]
@Trovoy what is “box”?

**Comment by Trovoy** [comment]
What I mean is that the U-shaped light strip still blinks after the computer closes the lid, with the power adapter connected. Can this light be turned off? Because he doesn't blink without the power adapter connected, but it blinks when it's connected.

**Comment by seerge** [comment]
@Trovoy no, as i have mentioned it can’t be turned off

**Comment by Trovoy** [comment]
Can't you turn off the U-shaped light strip after hibernation?

**Comment by seerge** [comment]
@Trovoy what is "U-shaped light strip" ? what model do you have ?

**Comment by Trovoy** [comment]
![photo_2023-08-20_19-01-46](https://github.com/seerge/g-helper/assets/105072381/631d8b85-eca8-4464-8d4c-2c93d6afb71a)

**Comment by Trovoy** [comment]
Turning off the strip after hibernation comes as an option in AC
