### ISSUE TITLE
will it going to have some thing like Aura Creator?

### ISSUE THREAD

**Issue by rremo888** [seerge/g-helper#1135]
The Aura Creator is awful to use,and it can't be used after I start using ghelper(I delected Armoury Crate).keyboard rgb sets in ghelper are too simple,so I hope there can be a rgb controller in ghelper like Aura Creator,but better

**Comment by seerge** [comment]
@rremo888 hello, the idea of G-Helper is to be a lightweight alternative for AC Nd not overbloated “do every small thing possible” alternative 

So I don’t plan recreating auta crrator on this stage
