### ISSUE TITLE
Disable Power Plan Switching

### ISSUE THREAD

**Issue by TrooperZ** [seerge/g-helper#1143]
Could you add a toggle setting in the Extras to disable automatic power plan switching? I have a custom power plan that I always use and it's not convenient having to switch back and forth between the Balanced and my plan when switching power settings.

**Comment by seerge** [comment]
@TrooperZ hello, you already can set a custom power plan in config https://github.com/seerge/g-helper#custom-windows-power-plans-with-each-mode for any mode (or for all of them)
