### ISSUE TITLE
About keyboard color change according to power mode status.

### ISSUE THREAD

**Issue by Donghaen** [seerge/g-helper#1145]
I will be one of the happiest people with this application. Thanks to the developer for their efforts. 

In my case, I always use the GPU mode as ultimate, but change the cpu mode often. Is it possible to add a function to adjust the keyboard color according to the cpu mode? If it can be implemented technically, it would be perfect if we could assign a color to each mode in the fan+power tab.

**Comment by seerge** [comment]
@Donghaen hello,

Why don't you use Heatmap instead ? it would color keyboard proportional to temp (and therefore to current CPU load in most of the cases)

I don't want to overload UI with adding infinite amount of small dropdowns and checkboxes to cover every possible exotic use-case :) As whole idea of the app is to be simple, sorry.
