### ISSUE TITLE
Keyboard backlight fully bright after startup even though 0% on G-helper

### ISSUE THREAD

**Issue by OliverArensbach** [seerge/g-helper#1148]
Hello!
The issue that i experience is that the keyboard backlight on my pc i set to 100% on startup and once i open the app it says that it is set to 0%
It is only when i change the backlight to 30% and back to 0% that it goes to 0% lighting

Windows 11, deleted armoury crate but still have myAsus program
Rog zephyrus G14 GA402RJ

Happens every startup and i can't see anything useful in the log

hope i provided enough information!

**Comment by seerge** [comment]
@OliverArensbach can you upload a log? i have lost my telepathic skills .

**Comment by OliverArensbach** [comment]
ohh sorry 😅 i did indeed think you had telepathic powers
[log.txt](https://github.com/seerge/g-helper/files/12398581/log.txt)

**Comment by seerge** [comment]
@OliverArensbach thanks, well, according to the log app intentionally sets brightness to 0 (after setting RGB mode)

```
21/08/2023 18:24:21: USB-KB 0x19B6:5D-BD-01-FF-1E-FF-FF-FF
21/08/2023 18:24:21: USB-KB 2HID-kompatibel leverandørdefineret enhed\\?\hid#vid_0b05&pid_19b6&mi_00&col04#8&18c99fbc&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
21/08/2023 18:24:21: Monitor Power On
21/08/2023 18:24:21: Auto:5D-BA-C5-C4-00 (brightness to -> 00)
```

I can only assume some strange hardware behaviour of a keyboard itself. You can try to disable RGB commands completely on startup y adding following line to ``%appdata%\ghelper\config.json`` (saving it while app is closed, and starting app again)

```
"skip_aura" : 1,
```

**Comment by OliverArensbach** [comment]
Ok 👍

**Comment by seerge** [comment]
@OliverArensbach let me know if it has any effect

**Comment by 123dqwkhjk** [comment]
Hello!

I have met similar issue on zephyrus g15 ga503rm(2022), when I disable keyboard backlight during boot, it still light up. However, it will turn off after the application launch. Can this solve my issue. Thanks!

**Comment by seerge** [comment]
@123dqwkhjk 

"Boot" checkbox is responsible for (double) blink of keyboard when laptop starts (same applies for "Shutdown"). The rest - is just normal "Awake" state.

App sets last remembered mode and brightness of keyboard on start. 
You can try to follow same advice as I gave in this topic https://github.com/seerge/g-helper/issues/1148#issuecomment-1686652087

**Comment by 123dqwkhjk** [comment]
Hello sir! Really thanks a lot! It is fixed!

**Comment by seerge** [comment]
@OliverArensbach did it help you as well ?

**Comment by TheToby1** [comment]
Hi @seerge, I'm having this issue and the suggested fix hasn't changed anything. 
[log.txt](https://github.com/seerge/g-helper/files/12565853/log.txt)

**Comment by seerge** [comment]
@TheToby1 may be it’s not related to g-helper at all then? :)

**Comment by TheToby1** [comment]
Spooky keyboard ghosts? :) I guess I can't rule it out, I don't have any of the ASUS services running though and nothing else which controls my keyboard backlight.

**Comment by seerge** [comment]
@TheToby1 can you post a log here? if you have turned off aura init, app won’t do anything to your keyboard on start except setting brightness (to last remembered level)

**Comment by TheToby1** [comment]
I posted the log above.

**Comment by seerge** [comment]
@TheToby1 ok, so in last app start it has set backlight to 0 

‘’’
2023-09-08 01:32:10 PM: Auto:5D-BA-C5-C4-00
‘’’

If it’s not respected - i can’t do much :|

**Comment by seerge** [comment]
@TheToby1 can you try this build ? I have added 1 second delay before it will set backlight brightness on start
[GHelper.zip](https://github.com/seerge/g-helper/files/12565938/GHelper.zip)

**Comment by TheToby1** [comment]
Damn, thanks for looking into it. I'll test that out!

**Comment by seerge** [comment]
@TheToby1 does it make any difference ?

**Comment by TheToby1** [comment]
Yes that has seemed to fix it.
