### ISSUE TITLE
[Feature Request] Refresh apply custom Fan Curves & Power settings

### ISSUE THREAD

**Issue by pcwizard7** [seerge/g-helper#1151]
**Is your feature request related to a problem? Please describe.**
Amour crate still seems to be undoing my Fan Curves & Power settings.  As with fan curves, it will return to zero rpm and I have to go to fan+power and uncheck and recheck apply my custom settings and my fan curves start working again

**Describe the solution you'd like**
add an ability to do this automatically and the option to set how long to wait between refresh  

thanks

**Comment by russellmm** [comment]
you are not supposed to run G-Helper and Armory Crate at the same time as they will write over each other. The intent of G-Helper is to replace Armory Crate.

**Comment by pcwizard7** [comment]
I have the services disabled tho

**Comment by russellmm** [comment]
I am not sure those are disabling Armory Crate though. Go into task manager and see if anything related to ASUS or armory crate is still running.

**Comment by seerge** [comment]
@pcwizard7 hello, it's not recommended to run AC along app for a long time (for test it's ok). You need to choose something one.

https://github.com/seerge/g-helper#recommendations-optional
