### ISSUE TITLE
开发者大大，能不能换一个任务栏图标？ Developer big, can you change a taskbar icon?

### ISSUE THREAD

**Issue by Tongnier** [seerge/g-helper#1152]
能不能换一个和windows系统相配套的任务栏图标？ 
Can I change the taskbar icon that matches the Windows system?

任务栏图标不美观，希望换一个任务栏图标。并且与windows10/11系统相配套，图标分为透明底的黑色和白色。或者增加一个隐藏任务栏的按钮，谢谢开发者大大能考虑一下。英语是机翻的，请见谅。
The taskbar icon is not aesthetically pleasing, and I want to change it to a taskbar icon. And with Windows 10/11 system, the icons are divided into black and white with a transparent bottom. Or add a button to hide the taskbar, thanks to the developer for thinking about it. English is machine-translated, please forgive me.

**Comment by seerge** [comment]
@Tongnier hello, taskbar icon is intentionally colored to indicate current GPU mode (blue - is standard, green - eco, red - ultimate)
