### ISSUE TITLE
Touch pad issue

### ISSUE THREAD

**Issue by Skorpeus** [seerge/g-helper#1158]
I have an asus tuf f15 2023 laptop, after installation I ran into a problem that I can’t turn on the touch pad, every time I press fn + f10 it displays Off. 
AC deleted
MyAsus deleted
services stopped
Win 11

[log.txt](https://github.com/seerge/g-helper/files/12412755/log.txt)
![image](https://github.com/seerge/g-helper/assets/142940415/21fabf69-6ab1-403d-8aad-14954d70c4c1)

**Comment by seerge** [comment]
@Skorpeus hello, this is a dublicate of https://github.com/seerge/g-helper/issues/738 

Unfortunately there is no known info on how to disable / enable touchpad on TUF models (they do it differently from ROG) . If you really need this hotkey to work - you can start Asus Optimization service (from windows Services). And it will handle hotkeys for you instead of G-Helper.

**Comment by Skorpeus** [comment]
I tried to turn on optimization, but when I click m4, I see the ac installation window

**Comment by seerge** [comment]
@Skorpeus you need to make sure that ArmouryControlInterface service is NOT running :)

**Comment by Skorpeus** [comment]
I turned on the optimization and turned off the Armory Control Interface, but it still prompts me to install (

**Comment by Skorpeus** [comment]
Did I disable the right service?
![image](https://github.com/seerge/g-helper/assets/142940415/c8943f67-2804-46cf-87f1-3f632db2ec89)

**Comment by seerge** [comment]
@Skorpeus yes, you need only Asus Optimization for hotkeys

**Comment by Skorpeus** [comment]
everything except optimization is disabled, but the ac window still appears

**Comment by seerge** [comment]
@Skorpeus it means that it's app is still running somewhere :) 

Navigate to:
C:\Windows\System32\

Find the folder: ASUSACCI and either move or delete it somewhere (if it's not letting you to - try to kill ArmouryCrateKeyControl in task manager)

**Comment by seerge** [comment]
You can also try more radical step and disable Armoury Control Interface in bios (f2 on boot)
