### ISSUE TITLE
random max fan speed on ROG g15

### ISSUE THREAD

**Issue by jfayre** [seerge/g-helper#1160]
Hello,
I know this isn't strictly related to gHelper, but wondering if you can point me in the right direction. Asus has been useless unfortunately.
On my Rog Zephrus G15, the fans will spin up to max occasionally on startup. When this happens, the CPU seems to throttle as well. I just updated to bios 415, and am still seeing the issue occasionally. It does seem to happen less since I uninstalled Armory Crate though. When this happens, I need to do a full shutdown to reset the fans. Also, the system is very cool when this happens.
In reading the forums, this seems to be a very well known issue, but I haven't seen a good solution. Asus claims not to know anything about it.
System Model: ROG Zephyrus G15 GA503QR

**Comment by seerge** [comment]
@jfayre hello,

G-Helper doesn't control fans anyhow in realtime, your BIOS does. It can only switch between 3 predefined modes and optionally set a custom fan curve.

It's probably some issues in fan control in BIOS itself and even [mentioned in FAQ](https://github.com/seerge/g-helper#i-have-g15-2022-and-my-gpu-refuses-to-disableenable-or-my-fans-misbehave) (for 2022 model, but i can imagine that 2021 is also affected)

You can check this topic https://github.com/seerge/g-helper/discussions/404 where another user with a similar problem has solved it by rolling back to older BIOS (i don't know if 2021 model has any "good" BIOS version tho)
