### ISSUE TITLE
Using GHelper may cause CPU frequency lock (machine translation)

### ISSUE THREAD

**Issue by Dakness** [seerge/g-helper#1161]
**Describe the bug**
Using GHelper may cause CPU frequency lock;
The CPU voltage is also not going up;
CPU power reaches default value.
After this problem occurs, no matter how you switch modes, you cannot recover;
Can be restored after restarting the computer.

**Clear scenario to Reproduce**
It will appear after playing Cyberpunk 2077 in balance mode for a while，
Or when the graphics card is under a certain load
This doesn't happen when using the Armory crate

**Expected behavior**
Fix the problem

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12415897/log.txt)

**Screenshots or screencasts**
![1](https://github.com/seerge/g-helper/assets/43392565/246916b6-6ea8-49b2-8c3e-c46965b9d71f)
![2](https://github.com/seerge/g-helper/assets/43392565/9636b8d7-dda6-44eb-bdbd-f422e0ac22a8)
<img width="1280" alt="3" src="https://github.com/seerge/g-helper/assets/43392565/c7dc5a78-0017-464d-b42c-7937f9b29eca">

restart
![3](https://github.com/seerge/g-helper/assets/43392565/625b3e4d-840e-4e6f-9200-d75262bc03d5)

**Desktop (please complete the following information):**
 - OS:Windows 11
 - Laptop model:FA507XV

**Asus software**
- MyASUS installed

**Comment by seerge** [comment]
@Dakness hello,

I don't think that this is related to G-Helper anyhow at all. G-Helper doesn't control clocks of your CPU anyhow.

On your screenshots your CPU is simply loaded on 100% by something. So check windows task manager for a process that takes all resources. It's very logical that after restarting that process is not running anymore, and not loading your computer :)

**Comment by Dakness** [comment]
CPU 100% is because FPU is in progress
I am not limited to 40W
CPU power consumption cannot be increased anymore

**Comment by seerge** [comment]
@Dakness as I have explained - when you load your CPU to the max (with benchmark or a game) - of course CPU frequencies will go up as well. 

This is how computers work.

G-Helper is not a driver, it doesn't control your CPU anyhow at all in realtime. They are controlled by windows / chipset drivers / bios.

App can only set a power limit via same endpoints that AC uses. If you don't set any custom limits BIOS will use defaults (i.e. what asus engineers have hardcoded for each mode)

**Comment by Dakness** [comment]
I have discovered that the cause of the problem may be due to CPU voltage drop
I used UXTU voltage reduction for the same test, which resulted in the voltage not being able to rise
Thank you, developer

**Comment by seerge** [comment]
Ok, i'm glad you have figured out your problem :)
