### ISSUE TITLE
Service restart should include ArmoryCrateSEService 

### ISSUE THREAD

**Issue by Keven44977** [seerge/g-helper#1162]
The start/stop asus services feature should include the ArmoryCrateSEService service as it is causing issues in some games and would avoid the need to manually start/stop it. 

![image](https://github.com/seerge/g-helper/assets/65184919/c826e55f-7571-43f8-a7d5-b8caaed5c966)

**Comment by seerge** [comment]
@Keven44977 hello,

Start / Stop button affects only Asus Services that are installed by default with system (i.e. with asus system control interface). 

It doesn't touch Armoury Services intentionally, as it can be absolutely safely uninstalled using own uninstaller :) 

Please check other requirements from readme 
https://github.com/seerge/g-helper#recommendations-optional
