### ISSUE TITLE
nvidia gpu undervolt 

### ISSUE THREAD

**Issue by 123dqwkhjk** [seerge/g-helper#1163]
**Describe the bug**
   I set gpu core clock limit to 1950MHz in ghelper, however, the curve is not limit to 1950MHz in msi afterburner.

**Clear scenario to Reproduce**
1. Go to 'ghelper gpu section'
2. set core clock limit to 1950 mhz
3. open the curve editor in msi afterburner

**Expected behavior**
It should lock the maximum core clock.

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/12418033/log.txt)

**Screenshots or screencasts**
<img width="451" alt="螢幕擷取畫面 2023-08-23 181007" src="https://github.com/seerge/g-helper/assets/130690113/49ce34a3-938c-4ffa-ac80-a7660a20dfaa">

**Desktop (please complete the following information):**
 - OS: windows 11 22621.2134
 - Laptop model: zephyrus g15 ga503rm

**Asus software**
- Armoury Crate: uninstalled
- MyASUS: uninstalled
- Other Asus services running in background:no

**Comment by seerge** [comment]
@123dqwkhjk hello. It doesn't edit the curve in that way. 

It just sets a limit to a clock using nvidia-smi utility from nvidia itself :) But effect will be same - clock won't go higher than set value (monitor it with afterburner overlay if you want)
