### ISSUE TITLE
Mod malfunction on vivobook pro 2022 model

### ISSUE THREAD

**Issue by Donghaen** [seerge/g-helper#1168]
Thanks to the developers.

**Describe the bug**
Error in which the turbo mode operates when the quiet mode is selected, and the quiet mode operates when the turbo mode is selected

**Clear scenario to Reproduce**
Steps to reproduce the behavior:  Choose mode

**Expected behavior**
Changing the mode of the vivobook working fine.

**App Logs**

2023-08-24 오후 5:01:17: Mode = 0 : 0
2023-08-24 오후 5:01:18: VivoMode = 0 : OK
2023-08-24 오후 5:01:18: GET CLOCK LIMIT: 1500
2023-08-24 오후 5:01:18: GET GPU CLOCKS: 250, 100
2023-08-24 오후 5:01:18: Power Mode 00000000-0000-0000-0000-000000000000:OK
2023-08-24 오후 5:01:34: Mode = 1 : 0
2023-08-24 오후 5:01:34: VivoMode = 1 : OK
2023-08-24 오후 5:01:34: GET CLOCK LIMIT: 1500
2023-08-24 오후 5:01:34: GET GPU CLOCKS: 250, 100
2023-08-24 오후 5:01:34: Boost 3
2023-08-24 오후 5:01:45: Mode = 2 : 0
2023-08-24 오후 5:01:45: VivoMode = 2 : OK
2023-08-24 오후 5:01:45: GET CLOCK LIMIT: 1500
2023-08-24 오후 5:01:45: GET GPU CLOCKS: 250, 100
2023-08-24 오후 5:01:45: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
2023-08-24 오후 5:01:45: Boost 0

It was originally silence, so log is about 'silence-> balanced-> turbo -> silence'. on Ghelper display

**Screenshots or screencasts**
No screenshots. But I checked the mode by checking the GPU TGP in the OCCT program. When use modes on MyAsus, silence 30w, balanced 45w, turbo 50w. 

**Desktop (please complete the following information):**
 - OS: Winodws 11 22H2
 - Laptop model
Asus vivobook pro 2022 `(N7401ZE)`

**Asus software**
- Other Asus services running in background to chance my keybord backlight. When I shut down all asus servieces, keybord backlight didn't changed.

**Additional context**

**Comment by seerge** [comment]
@Donghaen hello, that's literally opposite to what was in https://github.com/seerge/g-helper/issues/1089 that @satellitemx asked for 2023 model

I can swap mode numbers of course, but I need to know what models are affected. Is it same for all 2022 models ? or for all older devices as well ?

**Comment by satellitemx** [comment]
> 

Hi there,

I actually didn't mention this in previous issue of the build as I thought maybe very few people are using G-helper. 
I can confirm that for Vivobook, 0 = standard; 1 = silent; 2 = turbo; as outlined in my reply in #1089 
https://github.com/seerge/g-helper/issues/1089#issuecomment-1678792113

Apologies for not bringing this upfront.

**Comment by seerge** [comment]
@satellitemx oke, so they are swapped for you in 2023 model in a same way as for @Donghaen  ?

This build should swap 1 and 2
[GHelper.zip](https://github.com/seerge/g-helper/files/12428143/GHelper.zip)

**Comment by satellitemx** [comment]
> @satellitemx oke, so they are swapped for you in 2023 model in a same way as for @Donghaen ?
> 
> This build should swap 1 and 2 [GHelper.zip](https://github.com/seerge/g-helper/files/12428143/GHelper.zip)

Yes on my 2023 K6604 it behaves this way as well. 
I've been using this feature knowing the modes are swapped in my head😄
Thank you for your hardwork.

**Comment by seerge** [comment]
@satellitemx that's actually good, way easier than building a list of models that behave differently

**Comment by Donghaen** [comment]
Thanks for your help! The problem is solved and it works very well.
