### ISSUE TITLE
M-key Not work properly on G733CW

### ISSUE THREAD

**Issue by kingsznhone** [seerge/g-helper#1169]
**Describe the bug**
M-key doesn't work properly on ROG G733CW

**Clear scenario to Reproduce**
1. Open g-helper
2. Press M-key

**Expected behavior**
M1 for Vol- 
M2 for Vol+
M3 for mute
M4 for profile change
M5 for open g-helper

**Actual behavior**
M1 for vol-
M2 for mute 
M3 for vol+
M4 for vol-
M5 for mute

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit 22h2
 - G733CW

**Asus software**
- AC is fully uninstalled.
- MyASUS uninstalled
- None Asus services running in background

**Additional context**
I've using  vs debug  to check trigger of M-key.
When Press M2& M5. ``` InputDispatcher.KeyProcess(string name) ``` Triggered.
```name = "m3"``` for both key press.
I track them to ```Program.acpi.SubscribeToEvents(WatcherEventArrived);```
I found ACPI doesn't send M1&M3&M4 events.
It seems to be processed by windows.

Then I use self-made kernel  keyboard hook to check what happened when pressing M1/M3/M4.
This is what i got.

When pressing M1.
KBDLLHOOKSTRUCT.vkcode  ==174

When pressing M3
KBDLLHOOKSTRUCT.vkcode  ==175

When pressing M1.
KBDLLHOOKSTRUCT.vkcode  ==174

I have no idea about why this happened after unisntall AC
.

**Comment by seerge** [comment]
@kingsznhone hello, can you please include log as it was asked in Issue template ? and prior to that press M1 .. M5 one by one, so it's clearly visible in a log what keycodes they generate.

**Comment by kingsznhone** [comment]
> @kingsznhone hello, can you please include log as it was asked in Issue template ? and prior to that press M1 .. M5 one by one, so it's clearly visible in a log what keycodes they generate.

Thanks for reply. 
After 10 times more reinstall and uninstall AC . M-Key finally work properly.
I would recommend a full install and uninstall  cycle before using g-helper
