### ISSUE TITLE
A way to solve one of ASUS biggest issues with USB-C charging

### ISSUE THREAD

**Issue by russellmm** [seerge/g-helper#1178]
**Is your feature request related to a problem? Please describe.**
It is well known amongst ASUS G14 (and other models?) uers that the way USB-C power delivery is handled it does not bypass the battery like the Barrel plug does. So when using USB-C power delivery it is constantly cycling charge events which rapid degrades the battery. I.E. if you have G-Helper set to stop charging at 80%, as soon as the battery drops to 79%, USB-C charging will kick in.

**Describe the solution you'd like**
I think you can easily fix this in G-Helper (Dell does something like this). Create a lower bound limit and an upper bound limit for charging. If your lower bound limit is set for 40% (or preferrably lower) while on USB-C power you would allow it to run off battery until the battery gets to 40% at which point you would charge it back to the upper bound. I think you can easily implement this within SW and just swap the 2 values into the BIOS depending on which phase you are in. Put 40% into BIOS and monitor the battery until it hits 40% and then swap that value with 80% (or whatever your upper bound is) which would engage charging until it hit 80%. Then swap back in the lower bound so it drains until it hits that.... and continue to repeat this process while on USB-C power.

**Describe alternatives you've considered**
You could technically manually do this by simply setting G-Helper to 40% (its current lowest allowed value) and then raising it manually once it hits a point you want to charge it.

**Additional context**
There are numerous posts on Reddit related to this issue as it is well known.

**Comment by brambedkar59** [comment]
> You could technically manually do this by simply setting G-Helper to 40% (its current lowest allowed value) and then raising it manually once it hits a point you want to charge it.

I am seeing weird behavior when doing this on normal charger on my ASUS TUF F17 FX706HE (not USB-C charger). My current battery status is 60% charged with G-helper set to 60%, with this battery is not being charged, all good. But when I lowered the value in G-helper to 40% it started charging.

![image](https://github.com/seerge/g-helper/assets/33904491/aa8bd54f-04f9-402d-9c61-feaa5b828f1c)

![image](https://github.com/seerge/g-helper/assets/33904491/ab17663e-116a-4749-a56b-2092e4f3b2a6)

**Comment by russellmm** [comment]
Do you have Armory Crate, My ASUS, and all the services stopped through G-Helper?

**Comment by brambedkar59** [comment]
> Do you have Armory Crate, My ASUS both uninstalled in addition to having and all the services stopped through G-Helper?
@russellmm Both Armory Crate & My ASUS are uninstalled, and all ASUS services are disabled as well.

**Comment by russellmm** [comment]
You might want to start a new thread and open it as a bug with the specifics of your system, your logs and the other things he needs for bug related issues.

**Comment by brambedkar59** [comment]
@russellmm Done.

**Comment by seerge** [comment]
@russellmm hello, to make such things work properly you need support from hardware level. This is not the case with ASUS.

They have a very simple charge limit setting, that is same for all devices and can be set even in powershell as admin (where 80 is your desired limit)

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00120057, 80)
```

I was already answering [very similar question in this thread ](https://github.com/seerge/g-helper/discussions/1030) so you may check it  as well :)

Closing as not planned.

**Comment by russellmm** [comment]
Attached is the Psuedo code I am thinking of. I really think it will work. I have confirmed that I can set the Charge Slider down to 20% and it WILL NOT charge (while plugged into USB-C) until it gets down to that 20% level. If I then raise the slider up to 80% it will charge it up to 80% like normal. The big problem we are all having with USB-C charging is that if you have the charge limit set to 80%, as soon as it goes to 79% it will start charging. We do not want that. We want to let the battery drain down to 20% or less before we start charging on USB-C to protect our batteries.

public class Laptop
{
    public bool IsChargingOnUSBCPort { get; set; } // Find out if laptop is Charging on USB-C
    public int BatteryLevel { get; set; } // get the current battery charge level.
    public const int Min_Value = 20; // get the actual value from the Min_Value slider
    public const int Max_Value = 100; // get the actual value from the Max_Value slider

    public void CheckAndChargeBattery()
    {
        if (IsChargingOnUSBCPort && BatteryLevel <= Min_Value)
        {
            ChargeBattery(); // Allow Battery to Charge off the USB-C until it reaches the Max_Value
        }
    }

    private void ChargeBattery()
    {
        while (BatteryLevel < Max_Value)
        {
            BatteryLevel = Read the battery level here
            // Continue allowing it to charge until Max_Value
        }
    }
}
<img width="295" alt="2023-08-28 22_11_26-GHelper - Microsoft Visual Studio" src="https://github.com/seerge/g-helper/assets/35648773/606f8123-4e71-480a-a742-1f1a5084301b">

The ONLY problem I see is that with the USB-C Charger plugged in, the laptop is not showing you the discharg rate even though it actually *is* discharging down to what you have the slider set to.

I would try to implement this myself but my coding days were 35 years ago... :)

**Comment by seerge** [comment]
@russellmm, thanks for your effort and donation, but what is the practical purpose of this ? charging from 20% to 80% will only increase charge cycles.

Also lots of devices simply neglect charge limit lower than 50%. Some don't support anything except 80% and 100% even. So it won't work for them.

I already get a ton of a very negative feedback on reddit (and here) that "charge limiter is not working" (while in most of the cases people just have asus optimizations service overriding a limiter, or don't realize that after reboot some models start charging no matter what due to how it's done on hardware level)

Making whole charge limiter logic complicated and not transparent will create even more issues than now.

**Comment by russellmm** [comment]
Maybe I am doing a really poor job of explaining the problem we face. ASUS, at least on the G14 (2022 and 2023) does not power the laptop off the USB-C when you are using that as a power source. It simply uses the USB-C to charge the battery. So when people use USB-C instead of the Barrel Plug Power brick what is actually happening is the G14 will discharge "1%" below its current charge level (say from 80% to 79%) and then it will charge it back to 80% and repeat this cycle endlessly and destroy your battery's life cycle in the process.  People "think" they are powering off USB but they are not. They are running on battery. 

There are many people who do not want to always carry the large brick charger with them so they want to be able to use a small 100W USB-C "Charger" but they can't because of the problem above.

If my idea where implemented it would allow the battery to gracefully discharge, while on USB-C, and then charge back up completely 1 cycle over an ~6 hour period (if you are just streaming youtube) as opposed to 100's of charge cycles that occurs now.

I understand your concern that it may confuse some people because they do not follow directions as it is. Maybe it could be in the extra menu or hidden and requires enabling it in the advanced config file. Worst case, I'll try to figure out how to implement it myself but my brain is old after 8 years of retirement. :)

Here is a reddit post that shows a picture of the problem 
https://www.reddit.com/r/ZephyrusG14/comments/v1js23/is_that_normal_battery_discharging_and_charging/?utm_source=share&utm_medium=web2x&context=3

Kind Regards
Russell

**Comment by seerge** [comment]
@russellmm hello. I know that USB-C can't power laptop directly, it always powers battery. This is how things are done.

But I doubt that small charge/discharge cycles are more harmful for the battery than big ones. And I don't think that engineers on asus are that stupid neither. Effectively time spent on charging / discharging will be same in both cases :) 2023 model doesn't seem to support values lower than 50% btw.

Next to that main reason why I don't see practical application in this - is cause it will make whole process of settings and behaviour extremely not transparent and **guarantee** storm of complains reddit / etc (i.e. it will do much more harm to the app reputation than good)

**Comment by russellmm** [comment]
No worries. I undertand your concerns. I will try to do it myself :)

By the way, I have the 2023 model and I was able to able to go all the way down to 20% (you can see it in the picture I posted above) and it worked just fine. It may even go lower, I just did not try it. 

<img width="291" alt="2023-08-29 11_23_27-A way to solve one of ASUS biggest issues with USB-C charging · Issue #1178 · se" src="https://github.com/seerge/g-helper/assets/35648773/63af325d-057d-4dc6-a1c5-84086d27548c">

thanks again for the great program!

Regards
Russell

**Comment by seerge** [comment]
@russellmm then I have probably missead DSDT file, when I was looking into interpretation of that command for 2023 model or they have changed it now :)

Btw on a side note : did you consider just getting a USB-C to barrel-plug adapter for your charger instead ? 
Like https://www.amazon.com/Cablecc-Adapter-Emulator-Trigger-4-01-3mm/dp/B07SK6QWQY?th=1

**Comment by russellmm** [comment]
hiya Serge,
I have the adapter coming from China (ordered on ebay) as Amazon does not seem to sell the 6mm x 3.7mm needed for the G14. I have read peope have had issues, we'll see. The SlimQ is also an option, its just bigger than I want :)

Kind Regards
Russell

**Comment by seerge** [comment]
@russellmm i see. I'm also curious if it will work with regular usb-c charger (as SlimQ could have some "logic" under the hood to actually support barrel charging)

**Comment by tristan-k** [comment]
Will the battery still be drained if plugged in through USB-C on the G14 2024?

**Comment by seerge** [comment]
@tristan-k it depends on how much power device consumes. When I had G14 2024, it was running via USB-C passthrough (i.e. w/o draining battery) on most of the light tasks (i.e. < 60-80W total)

**Comment by S41G0N** [comment]
> Will the battery still be drained if plugged in through USB-C on the G14 2024?

No, 2024 models have passthrough capability, it will not drain the battery if plugged through USB-C in light use. Heavy tasks however, are a lot more intensive, which might lead to battery drain if the brick won't provide enough power.

**Comment by iceeemperor** [comment]
> Will the battery still be drained if plugged in through USB-C on the G14 2024?

it does but still face the same problem, when charging to 80%, you will see the battery drop to 79 and go back up to 80 again, it still use the battery
