### ISSUE TITLE
Battery Charge Limit doesn't work below 55% on TUF F17

### ISSUE THREAD

**Issue by brambedkar59** [seerge/g-helper#1179]
**Describe the bug**
When you set Battery Charge Limit below 55% it starts charging the battery

**Clear scenario to Reproduce**
1. Set Battery Charge Limit to 40% (anything below 55% doesn't work) 
2. Battery starts charging even though battery level is >60%

**Expected behavior**
Battery should not be charged when above the Battery Charge Limit set in G-helper

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12436900/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/33904491/6d5b5d68-2150-4061-93e9-cf1b1bbe4576)
![image](https://github.com/seerge/g-helper/assets/33904491/662c4b42-1883-43dd-8880-bff38ddb1665)
![image](https://github.com/seerge/g-helper/assets/33904491/3cb498e1-dfec-4a50-98d6-2a6f9ecc2154)

**Desktop (please complete the following information):**
 - OS: Windows 11 Build 22621.2134
 - Laptop model: TUF F17 FX706HE

**Asus software**
- Armoury Crate uninstalled
- MyASUS uninstalled
- All other Asus services disabled

**Additional context**
Running Throttlestop in the background, don't know if it's relevant.

**Comment by seerge** [comment]
@brambedkar59 hello,

Not all devices support all possible charge limits. Some support only 80% for example, some flexible scale between 50 - 100, etc :)

This is how it's done on hardware / bios level.

Therefore I can't change anything here.

**Comment by brambedkar59** [comment]
@seerge I understand. Thanks for replying so fast. You are amazing.
