### ISSUE TITLE
Touchpad problem

### ISSUE THREAD

**Issue by Balagurguru** [seerge/g-helper#1181]
Sergey, thank you for the work that you put into the work on this program. I really feel much more comfortable using your app when working with my laptop. I have an Asus rog g15, there is a small problem with turning the touchpad off and on. Sometimes it refuses to switch and only reboot helps. This problem is on two laptops of the same model. If possible, please see how to solve this issue. Thank you very much!

**Comment by seerge** [comment]
> ## NOTE
> Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. Please respect the time of the developer. Thanks.
