### ISSUE TITLE
g-helper disconnects Nvidia graphics card!

### ISSUE THREAD

**Issue by BenPseudo** [seerge/g-helper#1183]
**Describe the bug**
Using g-helper disconnects my Nvidia graphics card

**Clear scenario to Reproduce**
1. Run g-helper
2. Nvidia graphics card is disconnected

**Expected behavior**
g-helper and Nvidia graphics card operate as intended

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``

**Desktop (please complete the following information):**
 - OS: Windows 10
 - ASUS ROG Zephyrus G15 GA503RM

**Asus software**
- Armoury Crate - not installed
- MyASUS installed
- Other Asus services running in background - yes

**Additional context**
[log.txt](https://github.com/seerge/g-helper/files/12443124/log.txt)

**Comment by seerge** [comment]
@BenPseudo hello, I see that you have Eco mode selected. It by definition disables your dGPU.
You need to use Standard or Ultimate if you want to have your dGPU enabled.
