### ISSUE TITLE
Auto Select Profile on unplug/plug in

### ISSUE THREAD

**Issue by chirrupted** [seerge/g-helper#1184]
**Is your feature request related to a problem? Please describe.**
I've set up a custom mode called "Battery", where i lower the power limit and disable boost to save battery. Whenever I want to use it, I have to manually switch over to the mode myself, instead of being able to tell G-Helper to automatically switch over to my custom mode (And vice-versa, where if I plug my device back in while it was on the Battery mode, I have to manually switch over to Balanced.).

**Describe the solution you'd like**
I'd love for there to be an option in the G-Helper settings to automatically switch over to a selected mode on unplug/plug in, such as the aforementioned custom "Battery" mode. My idea is to have 2 check boxes in the Extra menu, one for automatically setting a mode on unplug and one for plugging in the charger. The mode would be able to be selected in a drop-down menu next to the respective checkbox.

**Describe alternatives you've considered**
Setting the modes manually.

It'd be incredibly useful if you could consider this feature, as I'm sure many other people would enjoy it as well!

**Comment by seerge** [comment]
@chirrupted hello,

G-Helper already remembers last used mode per battery / plugged in case.

Just set them once, and it will be switching automatically.

**Comment by chirrupted** [comment]
oh, thank you! I never realized that :P
