### ISSUE TITLE
Since updating to 0.115.0 my CPU temperature is always over 70 degress and power drain is dramatic

### ISSUE THREAD

**Issue by armsp** [seerge/g-helper#1185]
**Describe the bug**
Since the past few days, I have noticed that no matter what profile I use, and even when the CPU usage is 3-4 %, the temperature is always over 70 degrees. Before the updates my laptop was silent and the temp would always be in check. I have not changed any setting at all. I understand that this information does not really help much, but its such a clear observation after the update that I had to report this. I like to use my laptop in Silent Mode to have the best battery life since I am often without power. But it has been impossible to do that since the update.

In Silent mode I get a power drain of more than 50W.
![Screenshot 2023-08-26 110322](https://github.com/seerge/g-helper/assets/12681262/5ec76961-7d1f-4978-a7c9-08bdb1eacd28)

![Screenshot 2023-08-26 105952](https://github.com/seerge/g-helper/assets/12681262/82ea7898-2fb7-49c7-a8ad-1a714f067c4b)

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12444766/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: G15 GA503RM
 - BIOS - 315 for both

**Asus software**
- Armoury Crate (or it's services installed) - No
- MyASUS installed - Yes
- Other Asus services running in background - No

**Additional context**

**Comment by seerge** [comment]
@armsp hello, app doesn't control your CPU temperature anyhow (and especially in real-time). 

0.115 contains mostly cosmetic or mouse-support related changes. If you by some reason believe that older version was better - you can always download it from https://github.com/seerge/g-helper/releases (but it won't affect your temperatures anyhow)

Looking at your screenshot it seems like despite Eco mode dGPU is on and working. G15 are known to have a notoriously bugged bios, and sometimes fail to disable GPU. You may want to try to reboot and enable / disable it again .

There is nothing to fix here.

**Comment by seerge** [comment]
P.S. I'v heard that some G15 users roll back to BIOS 311 to sort out their GPU issues https://github.com/seerge/g-helper#i-have-g15-2022-and-my-gpu-refuses-to-disableenable-or-my-fans-misbehave
