### ISSUE TITLE
Zephyrus M16 2022 rtx 3060 stuttering

### ISSUE THREAD

**Issue by june26** [seerge/g-helper#1188]
Hi, I have a very annoying problem since 1 month of having this laptop 1 year ago
every time I play games, even old school games with left-aligned graphics settings in turbo mode with a 240W charger I experience stuttering. I heard my friend's suggestion to uninstall AC and use G-helper, but after I use it. I'm still experiencing it. is there something wrong with my laptop or the g-helper settings are not right?

fwi 
I already upgrade memory,  so my total memory now is 40GB

**Comment by seerge** [comment]
@june26 hello,

I don't think that it's anyhow related to the app, given that it happened with AC as well.

I would just advice to not to limit anything, and just set Factory Defaults for your mode. 
You can try to do a fresh reinstall of NVidia drivers with DDU.

Good luck
