### ISSUE TITLE
I have a suggestion

### ISSUE THREAD

**Issue by SHIKO-ZHOU** [seerge/g-helper#1189]
Hello boss, I am using a translator to communicate with you. My computer is the ROG 13 of 2021. I would like to mention a feature that allows the fan to rotate even in centralized display mode, reducing the temperature of the copper tube and better sharing the temperature of the CPU

**Comment by seerge** [comment]
@SHIKO-ZHOU hello,

G-Helper doesn’t control your fans https://github.com/seerge/g-helper#how-does-g-helper-control-my-fan-speeds

It can only set a custom fan curve, the rest is up to your BIOS behaviour in each mode for Rog Flow or any other model.
