### ISSUE TITLE
After changing from Eco mode to Ultimate mode, the GPU tab in Fans + Power menu disappeared.

### ISSUE THREAD

**Issue by tr4shstar** [seerge/g-helper#1190]
**Describe the bug**
I changed to Silent CPU mode and Eco GPU mode while on battery for a couple hours and GPU tab in Fans + Power menu disappeared as it should I think, then I plugged in and changed to manual CPU mode and Ultimate GPU mode and GPU tab didn't appear. Plus, now the G-Helper app takes much more time to open (from 1s to like minute), I did delete all G-Helper files and installed the app again but it didn't fixed any issue, it still takes a minute to open and GPU tab is inaccessible.

**Clear scenario to Reproduce**
1. Unplug the laptop
2. Click on "Silent"
3. Click on "Eco"
4. Reboot
5. Plug in the laptop
6. Click on Fans + Power and choose manual mode
7. Click on "Ultimate"
8. Reboot

**Expected behavior**
GPU tab in Fans + Power menu now doesn't appear.

**Desktop:**
 - OS: Windows 11
 - ROG STRIX G15 G513RW

**Asus software**
- Asus System Control Interface v3
- No other Asus services running in background

**Additional context**
[log.txt](https://github.com/seerge/g-helper/files/12446157/log.txt)

![Screenshot of the problem](https://github.com/seerge/g-helper/assets/143237548/ac5d38ae-76e7-4ab7-88ef-5f5a73753f61)

**Comment by seerge** [comment]
@tr4shstar hello, can you upload a log after a moment you open a fans+power section ? as the one you have posted here is only when your computer was in ECO mode at all

**Comment by tr4shstar** [comment]
@seerge Thanks! You were right, it was stuck in iGPU only mode, I chose Eco mode, rebooted, then chose Standard and only then Ultimate, rebooted and GPU tab is there, again thank you very much. (Idk ifanyone need log but I'll upload it anyway)
[log.txt](https://github.com/seerge/g-helper/files/12446351/log.txt)

**Comment by seerge** [comment]
@tr4shstar good, there is a list of the models that don't switch to Ultimate directly from Eco, and app can "fix" that by silently setting Standard prior to rebooting into Ultimate.

I have added G513 to the list 

So this build should switch from Eco -> Ultimate correctly

[GHelper.zip](https://github.com/seerge/g-helper/files/12446352/GHelper.zip)
