### ISSUE TITLE
ROG Flox x16 Randomly Deep Sleeps

### ISSUE THREAD

**Issue by corsair20141** [seerge/g-helper#1192]
**Is your feature request related to a problem? Please describe.**
My ROG Flox x16 will randomly deep sleep. Typically it happens under load, but not always. It happens without warning, laptop will just go into deep sleep (where you have to push power button to turn back on and you get the ROG logo). Something similar used to happen with a Zenbook I had too. I always have my laptop docked behind my monitor (screen closed) so not sure if it has something to do with that. I have other issues with the external monitor stream not being enabled after screen times out, having to open the laptop, login, then close it again to reactivate the external monitor. Really frustrating. Perhaps GHelper can do something to rectify these issues?

**Describe the solution you'd like**
I would like to disable/fix whatever bug is causing the laptop to randomly sleep, especially under load. Fans don't even get to 100%.

I would also like to fix the bug where the laptop sometimes won't re-enable the external display upon screen timeout.

**Comment by seerge** [comment]
@corsair20141 hello, G-Helper can not help you with your issues anyhow.
