### ISSUE TITLE
Some requests / suggestions

### ISSUE THREAD

**Issue by fscottcopeland** [seerge/g-helper#1193]
Hey, 

Would it be possible to support a HUD popup for the Zephyrus Duo's arrow key / page up control? It's a button which changes the effect of the arrow keys, from arrow keys to PgUp/PgDn etc.

Also, in a similar way, would you be able to add the functionality to support the Zephyrus Duo's keyboard button to turn the lower screen on/off?

Could we perhaps also have the ability to have specific GPU power / CPU boost to hotkeys? As an example, I currently use afterburner just to control GPU wattage with hotkeys - Ctrl+Shift+1 sets the wattage to 75w, ...2 to 100w, ...3 to 125w, ...4 to 150w, ...5 to 175w. And I have an autohotkey command ties to Ctrl+Shift+6 to enable/disable turbo boost.

Thanks!

**Comment by seerge** [comment]
@fscottcopeland hello,

1. I believe that fn+up/down mimicing a pgup/pgdown are handled purely by keyboard itself on hardware level.
2. App already can set Screenpad brightness UP / Down, you can bind any of existing M-keys to that via Extra settings
3. You can link all your power settings to Modes (including custom ones that you can add) via Fans+Power. And then simply switch between them using FN+F5 (forwards) / FN+Shift+F5 (backwards)

**Comment by fscottcopeland** [comment]
Hey @seerge 
Thanks for responding.

Understood re. point 1. In that case there's no way to have the HUD work with this then?

For point 2, I suppose perhaps my question is more with regards to increasing the number of valid hotkeys. Zephyrus Duo doesn't have "M" keys, only FN modifiers. 

For point 3, yep dynamic boost can be controlled, however I'm thinking more about reducing power limits beyond that. On the Duo 16 2023, the DB is +25w, from 150w to 175w, so that's the maximum control available currently. I'm wondering if we could fine tune the power limit, so that we can set rates below this.

**Comment by seerge** [comment]
@fscottcopeland 

1. What kind of HUD support do you want here ? Notification when PgUp is pressed ?
2. Do you have any "extra" unused hotkeys ? do they generate any code in ``%appdata%\ghelper\log.txt`` when you press them ?
3. Dynamic boost range is hardcoded in BIOS, i think it's between +5 to +25W range for all devices. There is no way to lower it. General power limits are locked completely for nvidia GPU on driver level (you can try running ``nvidia-smi -pl 100`` in powershell as admin)

**Comment by fscottcopeland** [comment]
@seerge Yeah something like that would be good. Annoyingly I can't find a screenshot of what the stock OSD shows, but it was a pop up to say either "Arrow Keys" or "PgUp/PgDn" mode, with a visualisation of what each of the 4 arrow keys would then do.

The Arrow Keys / PgUp/PgDn buttont triggers WMI event 75.
There's also WMI event 106, which is the button which connects/disconnects the lower screen. As I have vitually no ASUS services installed, this button currently does nothing.

Ah sorry, I'm talking more about general power limits. As in currently, I use afterburner to set my power limits as mentioned above but it would be great to have a hotkey to cycle between various wattages. Can confirm that nvidia-smi -pl 100 works.

**Comment by fscottcopeland** [comment]
Ah also, another thing I've spotted. If HDR is enabled, and by virtue, MiniLED, the Multizone button gets correctly highlighted.

If you click the Multizone button without first turning off MiniLED, the button visually shows Multizone as being disabled, whereas it isn't actually disabled.

If HDR is disabled already, then this button works as intended. With this in mind, Is it possible to also change HDR settings by use of this button, to achieve the desired effect of enabling / disabling MiniLED?

**Comment by seerge** [comment]
@fscottcopeland 

> The Arrow Keys / PgUp/PgDn buttont triggers WMI event 75.

Same event for both ON / OFF states ? I can add notification, but it will be something universal (w/o telling current state)

> There's also WMI event 106, which is the button which connects/disconnects the lower screen. As I have vitually no ASUS services installed, this button currently does nothing.

I can "hardcode" Screenpad brightness to it then (so it will cycle through it for example)

>Can confirm that nvidia-smi -pl 100 works.

Not for me, i assume you use some old nvidia drivers and have nvidia control disabled in device manager ? as otherwise it's locked for vast majority of the cases . And I'm not a fan of adding a sliders that won't work in the app :)

**Comment by seerge** [comment]
> If HDR is disabled already, then this button works as intended. With this in mind, Is it possible to also change HDR settings by use of this button, to achieve the desired effect of enabling / disabling MiniLED?

I think it's too much on this stage. When HDR is ON, miniled state of the screen is always ON (no matter what toggle sets). This is how it works on hardware level.
