### ISSUE TITLE
G-Helper changes my desktop icon spacing

### ISSUE THREAD

**Issue by asafheller1** [seerge/g-helper#1194]
**Describe the bug**
Since I installed the G-Helper my desktop icon spacing changed to -1128, I only know this since I googled how to reverse back to -1125 in regedit.

**Clear scenario to Reproduce**
Every time I change it it keeps changing it back after few resets of my laptop.

**Expected behavior**
The G-Helper itself works fine.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12447172/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/143304413/2d3bbabc-5d98-445e-97d4-b7ddc8835241)

**Desktop (please complete the following information):**
 - OS: Windows 11 Ghost Spectral Super Light
 - Laptop model: Asus fz507zi

**Asus software**
- I don't have any Asus software beside framework and Rog Live service

**Additional context**
I didn't wanna make a post about this, but it just keep repeating every time I change it.
I didn't isolate it to make sure its from the G-Helper because I haven't installed anything when I removed the Armoury Crate and started using G-Helper, so it was kinda obvious for me what is the cause.

Thank you for your fantastic work, I really love this software feels so nice not to be using the Asus bloatware.

**Comment by seerge** [comment]
@asafheller1 hello,

G-Helper obviously doesn't change any spacings (you can literally check app code on github).

I see that you have Nvidia GPU and use external monitor. I can only imagine it's some windows shenanigans with it's display management / connecting disconnecting external monitors or as a reaction on Ultimate mode (when nvidia is driving internal display as well).

I can't fix anything here, as this is not related.
