### ISSUE TITLE
 ghelper flagged with "HackTool.VulnDriver/x64!1.D7DB" file as malicious on virustotal

### ISSUE THREAD

**Issue by PriyanshuKhaliya** [seerge/g-helper#1195]
Security vendor "Acronis (Static ML)" has flagged "ghelper zip" with "HackTool.VulnDriver/x64!1.D7DB" as malicious file on virustotal.
it's false positive or not, any reason why it got flagged ?

**Comment by seerge** [comment]
@PriyanshuKhaliya hello

https://github.com/seerge/g-helper#windows-defender-marks-app-as-malware--virus
