### ISSUE TITLE
CPU fans speed not matching curve

### ISSUE THREAD

**Issue by uzhao** [seerge/g-helper#1198]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**
CPU fans speed not matching curve

**Clear scenario to Reproduce**
1. Apply Turbo mode
2. CPU fan runs at pretty random speed

**Expected behavior**
CPU fan runs at certain speed

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12448548/log.txt)

**Screenshots or screencasts**
![fanissue](https://github.com/seerge/g-helper/assets/5157125/9ecc6fb3-2e1d-448b-95f6-0c22329bf57c)
![fanissue2](https://github.com/seerge/g-helper/assets/5157125/732dccfe-d66a-4f3c-ad84-866d2bb0efc8)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 22H2
 - asus zephyrus g14 2020 (BIOS 220)

**Asus software**
- MyASUS installed
- No other Asus services running in background

**Additional context**
I applied custom fan curve once and later I choose turbo mode to copy the curve and applied again. According to my memory this issue happened since then

**Comment by seerge** [comment]
@uzhao hello, on both your screenshot Apply Fan Curve **is not checked**, therefore it will use default (hardcoded in BIOS fan curve for turbo mode)

**Comment by uzhao** [comment]
> @uzhao hello, on both your screenshots Apply Fan Curve **is not checked**, therefore it will use default (hardcoded in BIOS fan curve for turbo mode)

Hello @seerge. It's unchecked after reboot. I checked it before and clicked apply under advanced tab. Fan speed still higher than curve in most time and time to time lower than curve under same temp. Is it possible the new curve rejected by BIOS for some reason? This mode doesn't provide curve in BIOS so I can't check it there. 

![fanissue3](https://github.com/seerge/g-helper/assets/5157125/3529c3f0-723f-4bad-93e3-8dfe142487ec)

**Comment by seerge** [comment]
@uzhao try to compare RPMs, they are more accurate.

Asus has strange interpretation of settings in %, 0 - is OFF, and 1% immediately means ~ 1800-2000RPM, which would be 30%+ actually.

**Comment by seerge** [comment]
@uzhao I double checked - your dot at 65C stands for ~ 3600RPM (if you would use RPM scale)

Fan sensor also reports something like that ~ 3600-3700RPM (or 0.6 * 5600) so it's fine.

Anyway, fans are always controlled by BIOS, and depending on model it can follow curve very approximately (even for custom curves).
