### ISSUE TITLE
Undervolt error

### ISSUE THREAD

**Issue by lokepeter** [seerge/g-helper#1202]
First of all, thank you for this app, it really elevated my experience with this device :)

**Describe the bug**
Undervolting doesn't seem to work on my unit even though it is supposedly supported. I tried up to CPU(-30) iGPU(-20) with no apparent difference in stability and temps. On the log, whenever I set a value, it registers as "UV Error: System.TypeInitializationException: The type initializer for 'Ryzen.SendCommand' threw an exception". 

My current power limits: Platform 60W, CPU 30W. Boost disabled. Baseline temps 88C max, 82-85C average during gaming

**Clear scenario to Reproduce**
1. Adjust undervolting value for both CPU and iGPU as desired
2. Monitor stability and the temps

**Expected behavior**
Instability by -20 or lower, lower temps upon undervolting

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/12454385/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 11 22621.2134
 - ASUS ROG Zephyrus G14 2022 GA402RJ Ryzen 9 6900HS 6700s

**Asus software**
- Armoury Crate uninstalled
- MyASUS uninstalled
- Other Asus services running in background: NONE

**Comment by seerge** [comment]
@lokepeter hello,you need to unzip  all files into same folder. Make sure that winring0 files are next to exe when you run it

**Comment by lokepeter** [comment]
> @lokepeter hello,you need to unzip all files into same folder. Make sure that winring0 files are next to exe when you run

That solved the issue! Thanks again @seerge :)
