### ISSUE TITLE
Custom fan curves are rejected by Asus BIOS. ASUS ROG Strix G531GU

### ISSUE THREAD

**Issue by NooB9496** [seerge/g-helper#1206]
**Describe the bug**
Custom fan curves are rejected by Asus BIOS. I can't set custom fan curves. 

**Expected behavior**
Can You please fix this? I want to use custom fan curves for games.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12455558/log.txt)

**Screenshots or screencasts**
![ghelper](https://github.com/seerge/g-helper/assets/96725805/c290fa6f-7f9d-499a-a12d-7f5cee91771e)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 22H2
 - Compilation: 19045.3393
 - Laptop model: ASUS ROG Strix G531GU
 - BIOS: 311 modded with all possible function unlocked.
 - Drivers: All possible drivers are updated.

**Asus software**
- Armoury Crate installed
- MyASUS installed
- Other Asus services stoped using G-Helper

**Comment by seerge** [comment]
@NooB9496 hello,

I assume you didn’t had a custom fan curves in Armory as well? If so - they are simply not supported by your device

**Comment by NooB9496** [comment]
> @NooB9496 hello,
> 
> I assume you didn’t had a custom fan curves in Armory as well? If so - they are simply not supported by your device

In Armory Crate i have custom fan curves and works perfectly.

**Comment by seerge** [comment]
@NooB9496 try to set a curve exactly same as you have in AC (and posted screenshots here of ac one and one in g-helper)

Does it make any difference?

**Comment by NooB9496** [comment]
![ghelper1](https://github.com/seerge/g-helper/assets/96725805/4d6c5592-fc61-44e6-9b08-c6c304e85c53)
Still don't works.

**Comment by seerge** [comment]
@NooB9496 well, it doesn’t look like a fan curve :) So no wonder that it doesn’t work in G-Helper.

i can only imagine that there is some other endpoint for a very old devices like yours that can set a minimum and maximum setting for a fan

If you want you can check this topic on how to discover endpoints https://github.com/seerge/g-helper/issues/38

**Comment by NooB9496** [comment]
> @NooB9496 well, it doesn’t look like a fan curve :) So no wonder that it doesn’t work in G-Helper.
> 
> i can only imagine that there is some other endpoint for a very old devices like yours that can set a minimum and maximum setting for a fan
> 
> If you want you can check this topic on how to discover endpoints #38
> 
> Fan editor won’t work for you as is

I will try. Also i will check games with G-Helper Turbo Mode, maybe is enough and temps will be good.

**Comment by seerge** [comment]
@NooB9496 default fan behaviour will be exactly same as for all 3 modes in armory. It’s baked in bios

**Comment by seerge** [comment]
@NooB9496 and try to do a second method from #38 (i.e DSL dump), it sheds more light on what each endpoint does (at least approximately)

**Comment by NooB9496** [comment]
> @NooB9496
> 
> 110013 / 14 is just a fan speed readings :) that's what you see in g-helper already
> 
> Try to do a second method from #38 (i.e DSL dump), it sheds more light on what each endpoint does (at least approximately)
> 
> I see 2 "suspicious" endpoints, that could be max fan speeds for your case
> 
> ```
> 110022 : ff (255)
> 110023 : ff (255)
> ```
> 
> You can even try to "test" them by running following in PowerShell as admin, where `255` is desired setting (in a range between 0 and 255)
> 
> ```
> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110022,255)
> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110023,255)
> ```

Yep this works, fans works on 97% speed.

**Comment by seerge** [comment]
@NooB9496 but on your AC screenshot sliders have 2 edges, do they both work ? cause if this is minimum speed setting - what is maximum? :)

**Comment by NooB9496** [comment]
> @NooB9496 but on your AC screenshot sliders have 2 edges, do they both work ? cause if this is minimum speed setting - what is maximum? :)
> 
> And does AC allow setting CPU and GPU fan's separately ? or it's same values for both ?

Both sliders works, in AC i can manually change fan speed for CPU and GPU.

**Comment by NooB9496** [comment]
> 

PS C:\Windows\system32> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110022,0x0F
>>
At line:1 char:80
+ ... ject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110022,0x0F
+                                                                          ~
Missing ')' in method call.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndParenthesisInMethodCall

PS C:\Windows\system32> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110022,0xFF)


__GENUS          : 2
__CLASS          : __PARAMETERS
__SUPERCLASS     :
__DYNASTY        : __PARAMETERS
__RELPATH        :
__PROPERTY_COUNT : 1
__DERIVATION     : {}
__SERVER         :
__NAMESPACE      :
__PATH           :
result           : 1
PSComputerName   :



PS C:\Windows\system32>



CPU fan works on 97%, GPU fan 0%. After using second command.

**Comment by seerge** [comment]
@NooB9496 you didn't copy-paste first correctly. They both should affect CPU

**Comment by NooB9496** [comment]
Now after using first command CPU fan use 7% but I can't hear him, he's not turning.

**Comment by NooB9496** [comment]
> > @NooB9496 but on your AC screenshot sliders have 2 edges, do they both work ? cause if this is minimum speed setting - what is maximum? :)
> > And does AC allow setting CPU and GPU fan's separately ? or it's same values for both ?
> 
> Both sliders works, in AC i can manually change fan speed for CPU and GPU. Max RPM is 5400.

My bad, only CPU fan works. GPU fan 0%.

**Comment by NooB9496** [comment]
> > > @NooB9496 but on your AC screenshot sliders have 2 edges, do they both work ? cause if this is minimum speed setting - what is maximum? :)
> > > And does AC allow setting CPU and GPU fan's separately ? or it's same values for both ?
> > 
> > 
> > Both sliders works, in AC i can manually change fan speed for CPU and GPU. Max RPM is 5400.
> 
> My bad, only CPU fan works. GPU fan 0%.

Ah, sorry, both works.

**Comment by NooB9496** [comment]
> @NooB9496 well, may be it just runs slow :) so it seem to work
> 
> Try (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110022,0x7F)
> 
> I can imagine fan will run somewhere in the middle (like 50-60%)

CPU fan 57%

**Comment by seerge** [comment]
@NooB9496 does 
```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110022,0x7F)
```

Make CPU fan run between 50% and 100% only ?

**Comment by NooB9496** [comment]
> @NooB9496 does
> 
> ```
> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110022,0x7F)
> ```
> 
> Make CPU fan run between 50% and 100% only ?

Only 57%, don't goes up.

**Comment by seerge** [comment]
@NooB9496 well, it will go up if your temp goes up i assume :)

**Comment by NooB9496** [comment]
> @NooB9496 well, it will go up if your temp goes up i assume :)

unfortunately no, I loaded the processor, the temperature increased but the fan speed didnt.

**Comment by seerge** [comment]
@NooB9496 then 22 and 23 are just minimum fan speeds, and we need endpoint for maximum as well :) try to do a DSL dump, mb it will be more clear from there

**Comment by NooB9496** [comment]
> 

DSL dump?

**Comment by seerge** [comment]
@NooB9496 yes, as I have asked. Method 2 from https://github.com/seerge/g-helper/issues/38

**Comment by seerge** [comment]
@NooB9496 or actually, try following command 

may be it's just 2 bytes, first minimum, second - maximum

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110022,0xF0FF)
```

**Comment by seerge** [comment]
@NooB9496  https://www.intel.com/content/www/us/en/download/774881/acpi-component-architecture-downloads-windows-binary-tools.html

**Comment by NooB9496** [comment]
> @NooB9496 https://www.intel.com/content/www/us/en/download/774881/acpi-component-architecture-downloads-windows-binary-tools.html

i have dsdt file, upload it here? Does it contain sensitive data?

**Comment by NooB9496** [comment]
> @NooB9496
> 
> > CPU fan 95%
> 
> On what temps ?
> 
> Try this build : there is no slider , but it will use first curve point as min value, and last - as max value. And set range using my 2 byte assumption.
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/12456669/GHelper.zip)
> 
[dsdt.zip](https://github.com/seerge/g-helper/files/12456689/dsdt.zip)

> DSDT doesn't contain any "sensitive" data ...

regardless of the temperature, it always works at 95% of the speed

**Comment by seerge** [comment]
@NooB9496 try the build i have linked

**Comment by NooB9496** [comment]
> @NooB9496 try the build i have linked

it works, awesome
![ghelper2](https://github.com/seerge/g-helper/assets/96725805/d319bd7d-f049-4e96-aeb5-adc81f631115)

**Comment by seerge** [comment]
@NooB9496 can you try something more "normal" like 50% to 100% ? (btw Y-axis in RPM most probably won't be accurate, as it's calibrated for normal fan curves for other devices, and there whole logic is a bit different)

**Comment by NooB9496** [comment]
> @NooB9496 can you try something more "normal" like 50% to 100% ? (btw Y-axis in RPM most probably won't be accurate, as it's calibrated for normal fan curves for other devices, and there whole logic is a bit different)

Works
![ghelper3](https://github.com/seerge/g-helper/assets/96725805/bbb880da-1431-4453-8d9c-4eaef1f60d2d)

**Comment by seerge** [comment]
@NooB9496 good, then I consider this as "completed" :) and will include this fallback approach in next release.

Thanks for checking

**Comment by NooB9496** [comment]
> @NooB9496 good, then I consider this as "completed" :) and will include this fallback approach in next release.
> 
> Thanks for checking

Thank You, Awesome job.

**Comment by ev-i** [comment]
Confirming. ASUS TUF 15 (2021) FX516PR with versions before 1.117 was unable to set custom curve with message "Custom fan curves are rejected by Asus BIOS"
Not it works properly.

**Comment by seerge** [comment]
@ev-i good to know, but keep in mind that it's pretty much same as on @NooB9496 screenshot from armoury, i.e. you can just set min / max RPM for the fan (i.e. the range), actual temperature points won't be accurate for you :)

**Comment by khtpro** [comment]
i own tuf 2021 too but still didnt fix the fan curve :(

**Comment by seerge** [comment]
@khtpro it means your device doesn't support that at all. There is nothing to "fix" here .

**Comment by cybercrimeworld** [comment]
@seerge Why some device does not support custom fan curve.

**Comment by cybercrimeworld** [comment]
@seerge In you're code can you tell me how the fan is rotate and determine its speed and changes it's rpm. How this decision are happened. Please tell me the section only on you're code

**Comment by glclaritas** [comment]
@NooB9496 hello! sorry to hiject the thread. But can I have the bios file? coz I am on 311 of my G531GU and I can't undervolt my laptop(i7-9750h+GTX1660ti).

**Comment by NooB9496** [comment]
> [@NooB9496](https://github.com/NooB9496) hello! sorry to hiject the thread. But can I have the bios file? coz I am on 311 of my G531GU and I can't undervolt my laptop(i7-9750h+GTX1660ti).

Hi, no problem.I asked someone else to unlock the BIOS. After a few days, I received the finished BIOS to install.
