### ISSUE TITLE
Rename "clamshell mode" to "sleep on lid close"

### ISSUE THREAD

**Issue by TheBestPessimist** [seerge/g-helper#1207]
I have seen multiple questions on the topic "G-Helper is putting my laptop to sleep on lid close, even though i set it multiple times to do nothing".
And then you had to teach every person about clamshell and what it is.

Could it be renamed to something better (or have a tooltip). My suggestion would be: 
```
Sleep on lid close and internal monitor
```

but maybe there is a better phrasing.

All in all, i, too, find "Auto Toggle Clamshell Mode" unintuitive.

**Comment by seerge** [comment]
It's @IceStormNG 's idea ;) thing is that checkbox will actually **disable** sleep on lid close when external monitor + power is connected, and enable it back when either monitor or power is disconnected

**Comment by IceStormNG** [comment]
I called it that way, because Apple calls it like this on Macs, which have that feature built-in. This is usually the common term most people refer to when they talk about this behavior (not sleeping on lid close when power + external display is connected).
Windows has no such feature, so I made it myself and gave it the same name.

**Comment by seerge** [comment]
Well, for me it's also clear (as i'm a mac user mostly). But I will probably add some kind of tooltip to this checkbox as i have noticed few times already, that not everyone gets what does it mean and do :)

**Comment by russellmm** [comment]
yea, a tooltip would be cool. I did not realize what it was until I was reading all of the past code release notes earlier today.

**Comment by TheBestPessimist** [comment]
@seerge  @IceStormNG sorry for not knowing, i'm not a mac user `¯\_(ツ)_/¯`.

FWIW, i hate it when lid closed = sleep. It makes moving around with my laptop a chore as i have to always keep it open 🙄 .

As for the tooltip i don't know how to explain it better than @seerge 's initial reply.

**Comment by seerge** [comment]
@TheBestPessimist @russellmm @IceStormNG 

I have added tooltip, this should do the thing

[GHelper.zip](https://github.com/seerge/g-helper/files/12462849/GHelper.zip)

**Comment by TheBestPessimist** [comment]
_funny how when editing the markdown, the `code` is monospaced, but when published, it is not_
![image](https://github.com/seerge/g-helper/assets/4482210/c86a6a86-5c40-42ac-91bb-76f15485fc1d)

**Comment by seerge** [comment]
@TheBestPessimist i have spelled literally what it does. It disables sleep. If it's already set to do nothing - nothing would change for you :)
