### ISSUE TITLE
Vivobook 14X keyboard backlight / mic mute indicator light broken

### ISSUE THREAD

**Issue by rumifloss** [seerge/g-helper#1208]
**Describe the bug**
Keyboard backlight toggle key / indicator light on mic mute key is broken on Vivobook 14X. OSD shows modes changing upon key press but keyboard / mic indicator remains unlit.

**Clear scenario to Reproduce**
1. Go to Extra settings in G-Helper GUI
2. Kill all Asus services
3. Press keyboard backlight toggle key (F7) / mic mute key (F9) 

**Expected behavior**
Keyboard backlight toggle key toggles lighting levels with corresponding OSD outputs
Indicator light on mic mute key turns on/off with corresponding OSD outputs

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12456932/log.txt)

**Desktop (please complete the following information):**
 - Vivobook 14X (K3405VFB)
 - Windows 11

**Asus software**
- Armoury Crate: uninstalled
- MyASUS: uninstalled
- Other Asus services: disabled (enabled services do not display this issue)

**Additional context**
There are most definitely Vivobook users using this software! Thanks a ton for the great work.

**Comment by seerge** [comment]
@rumifloss check what keycode or wmi event does F7 and F9 specifically produce

What do you understand under backlight toggle? just on off? does backlight slider under extra work for you?

**Comment by rumifloss** [comment]
> @rumifloss check what keycode or wmi event does F7 and F9 specifically produce
How do I get the keycode or check the wmi event?
 
> What do you understand under backlight toggle? just on off? does backlight slider under extra work for you?
The backlight toggle key has one off and three lit levels, which the OSD shows as off, low, mid, and max. The backlight slider isn't doing anything either.

**Comment by seerge** [comment]
@rumifloss you can check codes in a log as you posted (they are added in realtime) 

Like I see
```
28-08-2023 22:55:14: WMI event 196
28-08-2023 22:55:14: WMI event 199
```
And it's generally FN+F2 / FN+F3 for ROG laptops (which set keyboard backlight up / down)

But difference is that in your case it seem to be no known information to control brightness

**Comment by seerge** [comment]
@rumifloss as for backlight control - try this build, it could be that vivobook just has different usb device id for keyboard, so app will try to connect to all ASUS devices here 

[GHelper.zip](https://github.com/seerge/g-helper/files/12457900/GHelper.zip)

And post a log please

**Comment by rumifloss** [comment]
>you can check codes in a log as you posted (they are added in realtime)

I get this when I press the key:
`29-08-2023 02:03:34: WMI event 196`

> And post a log please

[log.txt](https://github.com/seerge/g-helper/files/12458046/log.txt)

**Comment by seerge** [comment]
@rumifloss

> 29-08-2023 02:03:34: WMI event 196

What key is that ? Backlight (i.e. F7?)

> [log.txt](https://github.com/seerge/g-helper/files/12458046/log.txt) 

Is it from the built that I linked ? If so - it still doesn't see your keyboard, i have no idea how it's controlled honestly. And without physical device it's unrealistic to find out

And I see that mic toggle action is actually working (it's ``WMI event 124``)

**Comment by rumifloss** [comment]
> What key is that ? Backlight (i.e. F7?)

Yep. That's F7 with the Fn lock on. 
 
>Is it from the built that I linked ?

It is, yes. 

> And I see that mic toggle action is actually working (it's `WMI event 124`)

The toggle works alright. There's a small indicator in the key (F9) that lights up in red when the mic is muted. That light doesn't work. Maybe the keyboard backlight and mic indicator light are connected?

>i have no idea how it's controlled honestly. And without physical device it's unrealistic to find out

Shucks. Thanks once again.

**Comment by seerge** [comment]
@rumifloss can you check this build ? i have added alternative way to control backlight used on TUF models. Mv it makes sense for vivobooks

And I have also added some test command to set micmute led

[GHelper.zip](https://github.com/seerge/g-helper/files/12458398/GHelper.zip)

(and post a log again) :)

**Comment by rumifloss** [comment]
> @rumifloss can you check this build ? i have added alternative way to control backlight used on TUF models. Mv it makes sense for vivobooks

It works! I can toggle through all the backlight levels. The slider in the Extra options works too.
 
> And I have also added some test command to set micmute led 

This works too. There is a slight delay in the light turning on after the keypress but it's just cosmetic. Functionality is spot on.

[Here's the log just in case.](https://github.com/seerge/g-helper/files/12458459/log.txt)

Cheers mate! 🥂

**Comment by seerge** [comment]
@rumifloss double kill then.

Delay for mic-led (also for OSD notification) is for the reason, windows is sometimes slow with updating mic status, and some people complained about reading / showing incorrect status

Closing as completed
