### ISSUE TITLE
Alternative Fan Speed Control

### ISSUE THREAD

**Issue by TeccnoW** [seerge/g-helper#121]
Hi.
Sorry to bother you, but I have another request. 
![image](https://user-images.githubusercontent.com/128497481/226740540-e6678315-0dc9-49b6-b87c-266d5aad18b7.png)

I want alternative fan control controlled based by cpu temperature. 

It is a very nice feature to be able to control the cpu and gpu fan separately, but when this happens, the left fan makes a lot of noise in light games because the CPU load is high.

With the common heat pipe the system splits the heat, I want to run all the fans for the cpu at the same time for the cpu.

That way my CPU fan will spin 4800 while my Gpu fan will spin 1800 and this is noisy, both will spin 2200-2400 and be quiet.

I wonder if you can add this feature ? 

I would be very happy if you put a target CPU temperature button under the auto fan button. Thank you in advance. 
Thank you also for the window that always stays on top.

**Comment by TeccnoW** [comment]
When doing this, we need to check if we are on battery or if the adapter is plugged in.

I think a lot of people use eco mode on the battery, so it would be advantageous to enter fan control mode separately on the battery. Single fan consumes less energy.

**Comment by seerge** [comment]
Unfortunately that's not how it's done on hardware/bios level. You can only set a separate fan curve in a form of 8 temp + fan% pairs to CPU and GPU. It's not g-helper that controls the fans, it's bios.

So short answer - that's not possible :)

**Comment by TeccnoW** [comment]
hmmm... 

Here's a scenario:
Now, Cpu 70 degrees, GPU 55 degrees

Cpu's spinning 4800RPM at 70 degrees.
Gpu spins 2200RPM at 55 degrees.  
(Gpu is set to spin 4800 at 70 degrees)
We set it up like this.

İf we cancel the GPU fan curve. And show the cpu temperature as the GPU temperature. And cancel the GPU graph and connect the Cpu graph to the GPU fan. Could that be a solution?

**Comment by TeccnoW** [comment]
After all, we tell the bios to return at this temperature with this percentage. Can't we just map the cpu graph to the gpu graph?

**Comment by TeccnoW** [comment]
I just imagined it, I don't know if it's very difficult to do or, as you say, impossible.

**Comment by seerge** [comment]
It's not possible due to hardware implementation of a fan control. Again - app doesn't control fans, bios does. App only applies settings once.

**Comment by seerge** [comment]
You are free to play with fan curves as you want ofc, but that's maximum laptop supports.

**Comment by TeccnoW** [comment]
"App only applies settings once." Okay thats the anwser, thanks. 
![image](https://user-images.githubusercontent.com/128497481/226747322-14b9467d-3dff-48ed-b5c3-0dd19a1d31a5.png)

**Comment by seerge** [comment]
Great :) I will close this topic for now then as there is nothing else can be done for you

**Comment by TeccnoW** [comment]
![image](https://user-images.githubusercontent.com/128497481/226854031-d859ae0a-24c4-4991-b9a7-df08f922c017.png)
