### ISSUE TITLE
Type in text and display on animetrix

### ISSUE THREAD

**Issue by thduc87** [seerge/g-helper#1212]
**Is your feature request related to a problem? Please describe.**
This is a suggestion to allow user to enter text and display the text on the animetrix panel

**Describe the solution you'd like**
Basically i'd imagine to have a text editor or a small input text panel so that user can enter any text/ character and display it on the animetrix panel accordingly

**Describe alternatives you've considered**

**Additional context**

**Comment by seerge** [comment]
@thduc87 this is a duplicate of https://github.com/seerge/g-helper/issues/706
