### ISSUE TITLE
M1-M3 only visible function mapping keys on strix scar 18 2023

### ISSUE THREAD

**Issue by JosephSchansberg** [seerge/g-helper#1213]
f## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**
Pretty Self Explanatory my rog strix scar 18 has 5 mappable M function keys and did fresh g helper install and there is only M1,M2,M3, and M5/ROG. 4 is missing and I have no clue why. 
**Clear scenario to Reproduce**
1. Go to extra settings 
2. Click on key bindings
3. Scroll down to m3 and m4 can be seen as missing.
4. Hard to tell whether this is a bug or not.

**Expected behavior**
n/a

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
n/a
**Screenshots or screencasts**

**Desktop (please complete the following information):**
Windows 10 pro 22h2
Asus Rog Strix 18 2023 g8314j
**Asus software**
- Armoury Crate (or it's services installed)
- MyASUS installed
- Other Asus services running in background
my asus isntalled
armoury crate fresh uninstall
**Additional context**
<img width="692" alt="Capture" src="https://github.com/seerge/g-helper/assets/143499863/9b1b22fb-5751-49d0-a127-bdc7871eef39">

**Comment by JosephSchansberg** [comment]
Ah i gotcha. So it can’t be changed regardless

**Comment by JosephSchansberg** [comment]
Also i just did a fresh uninstall of armory crate and i want to get all of
the leftovers off my computers. is this safe to do and is their an easier
way to do it. i used revo uninstalled for a good portion of armoire crate
and some of its leftover files

**Comment by seerge** [comment]
@JosephSchansberg it's way easier to use AC own uninstaller
https://github.com/seerge/g-helper#recommendations-optional

Closing as completed then
