### ISSUE TITLE
Performance dips after switching between power modes on Vivobook 14X

### ISSUE THREAD

**Issue by rumifloss** [seerge/g-helper#1214]
**Describe the bug**
If G-Helper is set to Turbo mode and then switched to another mode, all GPU apps dip in performance after about 30 seconds of mode changing. Switching to another mode or clicking on Turbo mode again (or changing fan profiles when MyASUS is installed) brings back expected performance but goes back to low performance again after 30-ish seconds

**Clear scenario to Reproduce**
1. Switch to Turbo mode in G-Helper
2. Switch to any other mode
3. Switch back to Turbo mode / to any mode

**Expected behavior**
GPU applications continue functioning as expected of the mode selected

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12468165/log.txt)

**Screenshots or screencasts**
<img width="314" alt="Screenshot 2023-08-30 001030" src="https://github.com/seerge/g-helper/assets/16689247/03b12603-04e8-40f4-9a32-dc6218af5c5a">

**Desktop (please complete the following information):**
 - Windows 11
 - Vivobook 14X K3405VF

**Asus software**
- Armoury Crate: uninstalled
- MyASUS: installed/uninstalled (same issue either way)
- Other Asus services running in background: yes/no (same issue either way)

**Additional context**
After encountering problem for first time, rebooted laptop without G-Helper starting and tested for about 30 minutes and found no issues. Opened G-Helper and tested and found no issues. Changed modes in G-Helper and faced the issue. Was not fixed even if G-Helper was quit. Rebooted with G-Helper opening on start-up and did same testing; everything worked fine until power modes were toggled in G-Helper. GPU performance tested using Assetto Corsa and Bright Infinite Memory Benchmark on Steam

**Comment by seerge** [comment]
@rumifloss i didn't get it from your description. If you would set Balanced or Silent, obviously your performance will be lower.

Does same happen if you would switch modes in MyAsus ? (or what did  you use to set modes before g-helper?)

P.S. Restarting laptop without G-Helper doesn't actually mean anything, as you don't change modes then anyhow :)

**Comment by seerge** [comment]
@rumifloss how did you set max performance before g-helper then ? 

G-Helper doesn't turn off your turbo mode anyhow after 30 seconds obviously. So I don't really know why performance drops.

If it's CPU performance, it could be that it's different power limits are set - PL1 (sustained load) / PL2 (short boost for 30 seconds for example) set by asus itself. That would explain a drop.

Check for limits with Throttlestop app :)

**Comment by rumifloss** [comment]
> @rumifloss how did you set max performance before g-helper then ?

I wasn't able to. Do you think it might be broken for me because my CPU doesn't support it? Everything else about the power modes works fine
 
>If it's CPU performance, it could be that it's different power limits are set - PL1 (sustained load) / PL2 (short boost for 30 seconds for example) set by asus itself. That would explain a drop.

I'm afraid I don't understand what you mean. May I ask for an explanation?
 
> Check for limits with Throttlestop app :)

Not sure how to use that app. I did take screenshots of before and after the drop with ThrottleStop running.

Before the drop:

<img width="1440" alt="BeforeDrop" src="https://github.com/seerge/g-helper/assets/16689247/cca38c95-d2c9-4e01-82bb-e4f3b29db1d2">

After the drop:

<img width="1440" alt="AfterDrop" src="https://github.com/seerge/g-helper/assets/16689247/d69eff8c-0386-4568-ae64-e62e698c81de">

Thank you so much for helping me here!

**Comment by seerge** [comment]
@rumifloss looking at 8fps after 44fps it looks like it's GPU then :) It could be that there is some "hardcoded" limit in asus bios, that allows it to run on max power only for 30 seconds .

Try to run in powershell as admin following command, it's what turbo mode sets

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110019, 2)
```

**Comment by rumifloss** [comment]
> Try to run in powershell as admin following command, it's what turbo mode sets
> 
> ```
> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110019, 2)
> ```

Same result as before. Performance drops after a brief period of time.

[log.txt](https://github.com/seerge/g-helper/files/12473683/log.txt)

**Comment by seerge** [comment]
@rumifloss then it's probably how it's hardcoded in bios. I'm afraid this is out of reach for the app then.

Do I understand correctly, that if you reboot and just set Turbo mode and don't change anything after, it will still drop after 30 seconds ?

**Comment by seerge** [comment]
You can program powershell to run command every 25 seconds if you want

```
while($true) {  (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110019, 2) ; Sleep 25 }
```

**Comment by seerge** [comment]
@satellitemx hello, you have similar device, do you also experience similar behaviour ?

**Comment by seerge** [comment]
@rumifloss It could be something from asus is actually overriding them.

In your log I have noticed 
```
29-08-2023 23:46:23: Optimization service is running
```

Go to Extra -> and Stop all asus services

**Comment by rumifloss** [comment]
>Go to Extra -> and Stop all asus services. You can start them back with same button.

Just turned the services off. Right now, with Asus services disabled, Silent gives me ~42 FPS, Balanced ~44 FPS, and Turbo ~47 FPS. This is strange because normally Silent makes everything screech to a halt and Balanced has a ~10 FPS difference at least. Could the CPU Boost settings be doing something? Silent is Disabled‚ Balanced is Efficient Enabled, Turbo is Aggressive.

[Here's the log just in case.](https://github.com/seerge/g-helper/files/12477218/log.txt)

**Comment by seerge** [comment]
@rumifloss well, if it's indeed runs with 0 asus services, and still drops - i'm out of ideas.

If you say that Performance in MyASUS is same - does it maintain itself, or also drops ?

**Comment by rumifloss** [comment]
>If you say that Performance in MyASUS is same - does it maintain itself, or also drops ?

Seems to maintain itself so far. I'll test it over a day and see. Midnight here 😄

**Comment by satellitemx** [comment]
> @satellitemx hello, you have similar device, do you also experience similar behaviour ?

Hi, similar behaviour has not occured on my device. 
I have just tested using FurMark under 3 modes and GPU can sustain the power draw according to the limit (GPU Board Power 80/90/120W). 
The numbers are slightly different to the testing in issue #1089, that is because I was not familiar with different power usage readings (GPU Chip Power vs GPU Board Power).

![Standard Mode](https://github.com/seerge/g-helper/assets/11451311/f1792919-7bed-4dbd-87d1-92ce1c0a1975)
![Silent Mode](https://github.com/seerge/g-helper/assets/11451311/c84f48bc-7c70-4e29-a263-f2ef0311ac49)
![Turbo Mode](https://github.com/seerge/g-helper/assets/11451311/f1b61a04-a9b1-4b9d-9db2-a8351bba557a)

However, recently I have observed some interesting behaviour and they may be related to the issue described by OP @rumifloss .
I have reinstalled the OS multiple times in the past month, and each time it may take a moment (few minutes to 1 hour) before the performance mode can fully take effect. The fan profile will change but the power limit of CPU will not. Before that CPU power is limited to 30W (on an i9-13980HX) as reported by Intel Power Gadget realtime readings. I assume in my case this may be because Intel Dyamic Tuning Technology Driver or Intel Integrated Sensor Solution Driver not being installed yet on a fresh OS install. 

I also observed that sometimes Intel Innovation Platform Framework Service (ipf_cpu.inf) is chugging 100% of single core non-stop and I had to terminate it in Task Manager. 

Hope that helps. Thank you for the hardwork @seerge .

**Comment by rumifloss** [comment]
>Silent gives me ~42 FPS, Balanced ~44 FPS, and Turbo ~47 FPS

I sought and deleted all Asus software like the plague. Getting these results consistently. GPU isn't affected by the modes as described but the CPU benchmarked 97% on Turbo and 70% on Silent in UserBenchmark. If that is intended behaviour then everything is good. 

>However, recently I have observed some interesting behaviour and they may be related to the issue described by OP @rumifloss. I have reinstalled the OS multiple times in the past month, and each time it may take a moment (few minutes to 1 hour) before the performance mode can fully take effect.

This is still an open problem. But I suppose it's out of G-Helper's domain.

>Hope that helps. Thank you for the hardwork @seerge.

Yes! Thanks for the hard work @seerge. I have never seen someone respond so promptly on GitHub before :D
