### ISSUE TITLE
Custom keyboard colors not being saved?

### ISSUE THREAD

**Issue by Stardust-Rapture** [seerge/g-helper#1217]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**
Defining custom keyboard colors does not save them in the swatch menu for colors.

**Clear scenario to Reproduce**
1) Laptop Keyboard -> Color -> Define Custom Colors
2) Create custom colors
3) "Ok"
4) Returning to custom colors menu shows the color(s) did not save.

**Expected behavior**
Defined custom colors being saved in the menu.

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Asus ROG Zephyrus S17 GX703H

**Asus software**
- Armoury Crate (or it's services installed): No
- MyASUS installed: Yes
- Other Asus services running in background: No

**Additional context**
The keyboard RGB does actually work correctly and the custom color set will show on the keyboard. All color modes also work.

Files:
[log.txt](https://github.com/seerge/g-helper/files/12473591/log.txt)
![iss01](https://github.com/seerge/g-helper/assets/24393539/0e42c267-8998-48b8-bd55-ddc9f28fcef6)
![iss02](https://github.com/seerge/g-helper/assets/24393539/bee42b9c-0bbf-4fce-b88a-9e2ac7b42344)

**Comment by seerge** [comment]
@Stardust-Rapture hello, app doesn't try to save custom colors :) It's quite a lot of extra logic, with putting each color into config, then fetching them. But it saves last used color, it should be enough.
