### ISSUE TITLE
Failed to turn off screen using custom hotkey

### ISSUE THREAD

**Issue by AuroraRock** [seerge/g-helper#1218]
**Describe the bug**
I've bound Toggle Screen to Fn+F4, but my screen turned off and then turned on again.
The log said 
> Failed to turn off screen. Error code: 0

**Expected behavior**
Turn off screen.

**App Logs**

> 2023/8/30 16:54:13: ------------
2023/8/30 16:54:13: App launched: ROG Strix G834JY_G834JY :0.115.0.0zh-CN.
2023/8/30 16:54:14: NVIDIA GeForce RTX 4090 Laptop GPU
2023/8/30 16:54:16: CPU: -1 - 13th Gen Intel(R) Core(TM) i9-13980HX - Intel64 Family 6 Model 183 Stepping 1
2023/8/30 16:54:16: AutoSetting for Online
2023/8/30 16:54:16: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&15ae9f2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/8/30 16:54:16: Mode = 0 : OK
2023/8/30 16:54:16: Eco flag : 0
2023/8/30 16:54:16: Mux flag : 1
2023/8/30 16:54:16: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/8/30 16:54:16: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/8/30 16:54:16: ScreenOverdrive = 1 : OK
2023/8/30 16:54:16: GET CLOCK LIMIT: 0
2023/8/30 16:54:16: BatteryLimit = 80 : OK
2023/8/30 16:54:16: GET GPU CLOCKS: 0, 0
2023/8/30 16:54:16: Monitor Power On
2023/8/30 16:54:16: Auto:5D-BA-C5-C4-03
2023/8/30 16:54:17: PowerLimit C0 = 25 : OK
2023/8/30 16:54:17: PowerLimit C2 = 87 : OK
2023/8/30 16:54:20: Latest version 0.115.0.0
2023/8/30 16:54:43: Hibernate after 2147483647
2023/8/30 16:54:58: Key: 179
2023/8/30 16:54:58: Screen off toggle
2023/8/30 16:54:58: Failed to turn off screen. Error code: 0. 操作成功完成。 
2023/8/30 16:55:01: Monitor Power Off
2023/8/30 16:55:01: Backlight:5D-BA-C5-C4-00
2023/8/30 16:55:02: Monitor Power On
2023/8/30 16:55:02: AutoSetting for Online
2023/8/30 16:55:02: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&15ae9f2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/8/30 16:55:02: Mode = 0 : OK
2023/8/30 16:55:02: Eco flag : 0
2023/8/30 16:55:02: Mux flag : 1
2023/8/30 16:55:02: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/8/30 16:55:02: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/8/30 16:55:02: ScreenOverdrive = 1 : OK
2023/8/30 16:55:02: GET CLOCK LIMIT: 0
2023/8/30 16:55:02: GET GPU CLOCKS: 0, 0
2023/8/30 16:55:02: BatteryLimit = 80 : OK
2023/8/30 16:55:02: Auto:5D-BA-C5-C4-03
2023/8/30 16:55:03: PowerLimit C0 = 25 : OK
2023/8/30 16:55:03: PowerLimit C2 = 87 : OK
2023/8/30 16:55:05: Design Capacity: 90001mWh, Full Charge Capacity: 88146mWh, Health: 0.979389117898690014555393829%
2023/8/30 16:55:05: Hibernate after 2147483647
2023/8/30 16:56:33: Hibernate after 2147483647

**Desktop:**
 - OS: Windows 11
 - Laptop model: ROG Strix G834JY

**Asus software**
None

**Comment by seerge** [comment]
@AuroraRock it just runs windows own command to do that :) if it was rejected by windows, apparently it's some settings that prevent it (mb some strange user permissions / etc). I can't really change anything here.

**Comment by seerge** [comment]
@AuroraRock you can try to run following powershell command (it does same as app when turns off screen)
https://superuser.com/questions/1397941/how-to-turn-off-screen-with-powershell

If it won't work  neither - check what's wrong with windows settings

**Comment by AuroraRock** [comment]
> @AuroraRock you can try to run following powershell command (it does same as app when turns off screen) https://superuser.com/questions/1397941/how-to-turn-off-screen-with-powershell
> 
> If it won't work neither - check what's wrong with windows settings

@seerge 

> (Add-Type '[DllImport("user32.dll")]public static extern int SendMessage(int hWnd, int hMsg, int wParam, int lParam);' -Name a -Pas)::SendMessage(-1,0x0112,0xF170,2)

This command from the website worked, but not only did it close my screen, it put the computer to sleep.

**Comment by AuroraRock** [comment]
@seerge I always run the app as admin, but it's still not working.
I reinstalled windows several days ago, and i don't think there's anything wrong with my Windows settings.

**Comment by AuroraRock** [comment]
After I unplug the power adapter, I can use this shortcut to put the computer to sleep. That's strange. So is there any way to just turn the screen off without going to sleep?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Serge ***@***.***>
发送时间: Wednesday, August 30, 2023 5:25:43 PM
收件人: seerge/g-helper ***@***.***>
抄送: Aurora ***@***.***>; Mention ***@***.***>
主题: Re: [seerge/g-helper] Failed to turn off screen using custom hotkey (Issue #1218)


@AuroraRock<https://github.com/AuroraRock> and does running same thing in G-Helper work now? If not - try to run app as admin.

―

**Comment by seerge** [comment]
@AuroraRock does this build make any difference ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/12474202/GHelper.zip)

**Comment by AuroraRock** [comment]
@seerge This build also put the computer to sleep. When I tried to wake up the computer, the screen flashed several times and took a long time.

**Comment by seerge** [comment]
@AuroraRock so this build works same as powershell command ? Then it's maximum that can be done here. There is no other ways to turn off screen on windows. 

If you do know other methods - feel free to contribute :)

**Comment by AuroraRock** [comment]
@seerge i think

> (Add-Type "[DllImport(""user32.dll"")] public static extern int PostMessage(int hWnd, int hMsg, int wParam, int lParam);" -Name "Win32PostMessage" -Namespace Win32Functions -PassThru)::PostMessage(0xffff, 0x0112, 0xF170, 2)
works best.

The app and other 3 commands in the website can make it hard to wake up my computer, you can see the monitor being turned on and off many times in the log.

> 2023/8/30 17:43:08: Key: 179
2023/8/30 17:43:08: Screen off toggle
2023/8/30 17:43:08: Screen off toggle
2023/8/30 17:43:10: Monitor Power Off
2023/8/30 17:43:10: Backlight:5D-BA-C5-C4-00
2023/8/30 17:43:12: Monitor Power On
2023/8/30 17:43:12: AutoSetting for Online
2023/8/30 17:43:12: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&15ae9f2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/8/30 17:43:12: Mode = 0 : OK
2023/8/30 17:43:12: Eco flag : 0
2023/8/30 17:43:12: Mux flag : 1
2023/8/30 17:43:12: GET CLOCK LIMIT: 0
2023/8/30 17:43:12: GET GPU CLOCKS: 0, 0
2023/8/30 17:43:24: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/8/30 17:43:24: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/8/30 17:43:24: ScreenOverdrive = 1 : OK
2023/8/30 17:43:25: PowerLimit C0 = 25 : OK
2023/8/30 17:43:25: PowerLimit C2 = 87 : OK
2023/8/30 17:43:44: BatteryLimit = 80 : OK
2023/8/30 17:43:44: Monitor Power Off
2023/8/30 17:43:44: Monitor Power On
2023/8/30 17:43:44: AutoSetting for Online
2023/8/30 17:43:44: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&15ae9f2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/8/30 17:43:44: Mode = 0 : OK
2023/8/30 17:43:44: Eco flag : 0
2023/8/30 17:43:44: Mux flag : 1
2023/8/30 17:43:44: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/8/30 17:43:44: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/8/30 17:43:44: ScreenOverdrive = 1 : OK
2023/8/30 17:43:44: GET CLOCK LIMIT: 0
2023/8/30 17:43:44: GET GPU CLOCKS: 0, 0
2023/8/30 17:43:44: Backlight:5D-BA-C5-C4-00
2023/8/30 17:43:44: Auto:5D-BA-C5-C4-03
2023/8/30 17:43:44: BatteryLimit = 80 : OK
2023/8/30 17:43:44: Monitor Power Off
2023/8/30 17:43:44: Monitor Power On
2023/8/30 17:43:44: Monitor Power Off
2023/8/30 17:43:44: Monitor Power On
2023/8/30 17:43:44: Monitor Power Off
2023/8/30 17:43:44: Monitor Power On
2023/8/30 17:43:44: Monitor Power Off
2023/8/30 17:43:44: Monitor Power On
2023/8/30 17:43:44: Monitor Power Off
2023/8/30 17:43:44: Auto:5D-BA-C5-C4-03
2023/8/30 17:43:44: Backlight:5D-BA-C5-C4-00
2023/8/30 17:43:44: Backlight:5D-BA-C5-C4-00
2023/8/30 17:43:44: Backlight:5D-BA-C5-C4-00
2023/8/30 17:43:44: Backlight:5D-BA-C5-C4-00
2023/8/30 17:43:44: Backlight:5D-BA-C5-C4-00
2023/8/30 17:43:45: PowerLimit C0 = 25 : OK
2023/8/30 17:43:45: PowerLimit C2 = 87 : OK
2023/8/30 17:43:46: Monitor Power On
2023/8/30 17:43:46: Monitor Power Off
2023/8/30 17:43:46: Backlight:5D-BA-C5-C4-00
2023/8/30 17:43:55: Monitor Power On
2023/8/30 17:43:55: AutoSetting for Online
2023/8/30 17:43:55: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&15ae9f2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/8/30 17:43:55: Mode = 0 : OK
2023/8/30 17:43:55: Eco flag : 0
2023/8/30 17:43:55: Mux flag : 1
2023/8/30 17:43:55: GET CLOCK LIMIT: 0
2023/8/30 17:43:55: GET GPU CLOCKS: 0, 0
2023/8/30 17:43:55: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/8/30 17:43:55: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/8/30 17:43:55: ScreenOverdrive = 1 : OK
2023/8/30 17:43:55: BatteryLimit = 80 : OK
2023/8/30 17:43:55: Monitor Power Off
2023/8/30 17:44:00: Auto:5D-BA-C5-C4-03
2023/8/30 17:44:00: Backlight:5D-BA-C5-C4-00
2023/8/30 17:44:01: PowerLimit C0 = 25 : OK
2023/8/30 17:44:01: PowerLimit C2 = 87 : OK
2023/8/30 17:44:01: Monitor Power On
2023/8/30 17:44:01: AutoSetting for Online
2023/8/30 17:44:01: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&15ae9f2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/8/30 17:44:01: Listener stopped
2023/8/30 17:44:01: Listener stopped
2023/8/30 17:44:01: Mode = 0 : OK
2023/8/30 17:44:01: Eco flag : 0
2023/8/30 17:44:01: Mux flag : 1
2023/8/30 17:44:01: GET CLOCK LIMIT: 0
2023/8/30 17:44:01: GET GPU CLOCKS: 0, 0
2023/8/30 17:44:01: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/8/30 17:44:01: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/8/30 17:44:01: ScreenOverdrive = 1 : OK
2023/8/30 17:44:01: BatteryLimit = 80 : OK
2023/8/30 17:44:01: Monitor Power Off
2023/8/30 17:44:07: Backlight:5D-BA-C5-C4-00
2023/8/30 17:44:07: Auto:5D-BA-C5-C4-03
2023/8/30 17:44:07: Monitor Power On
2023/8/30 17:44:07: AutoSetting for Online
2023/8/30 17:44:07: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&15ae9f2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/8/30 17:44:07: Mode = 0 : OK
2023/8/30 17:44:07: Eco flag : 0
2023/8/30 17:44:07: Mux flag : 1
2023/8/30 17:44:07: GET CLOCK LIMIT: 0
2023/8/30 17:44:07: GET GPU CLOCKS: 0, 0
2023/8/30 17:44:07: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/8/30 17:44:07: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/8/30 17:44:07: ScreenOverdrive = 1 : OK
2023/8/30 17:44:07: BatteryLimit = 80 : OK
2023/8/30 17:44:07: Auto:5D-BA-C5-C4-03
2023/8/30 17:44:08: PowerLimit C0 = 25 : OK
2023/8/30 17:44:08: PowerLimit C2 = 87 : OK
2023/8/30 17:44:09: PowerLimit C0 = 25 : OK
2023/8/30 17:44:09: PowerLimit C2 = 87 : OK
2023/8/30 17:46:04: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/8/30 17:46:04: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/8/30 17:46:06: Screen = 240Hz : OK
2023/8/30 17:46:06: ScreenOverdrive = 1 : OK
2023/8/30 17:46:06: Display configuration changed.
2023/8/30 17:46:08: Hibernate after 1800
2023/8/30 17:46:19: Key: 179
2023/8/30 17:46:19: Key: 179
2023/8/30 17:46:19: Screen off toggle
2023/8/30 17:46:19: Screen off toggle
2023/8/30 17:46:19: Screen off toggle
2023/8/30 17:46:19: Screen off toggle
2023/8/30 17:46:21: Monitor Power Off
2023/8/30 17:46:21: Backlight:5D-BA-C5-C4-00
2023/8/30 17:46:23: Monitor Power On
2023/8/30 17:46:23: AutoSetting for Online
2023/8/30 17:46:23: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&15ae9f2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/8/30 17:46:23: Mode = 0 : OK
2023/8/30 17:46:23: Eco flag : 0
2023/8/30 17:46:23: Mux flag : 1
2023/8/30 17:46:23: GET CLOCK LIMIT: 0
2023/8/30 17:46:23: GET GPU CLOCKS: 0, 0
2023/8/30 17:46:23: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/8/30 17:46:23: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/8/30 17:46:23: ScreenOverdrive = 1 : OK
2023/8/30 17:46:49: PowerLimit C0 = 25 : OK
2023/8/30 17:46:49: PowerLimit C2 = 87 : OK
2023/8/30 17:46:54: BatteryLimit = 80 : OK
2023/8/30 17:46:54: Monitor Power Off
2023/8/30 17:46:54: Monitor Power On
2023/8/30 17:46:54: AutoSetting for Online
2023/8/30 17:46:54: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&15ae9f2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/8/30 17:46:54: Backlight:5D-BA-C5-C4-00
2023/8/30 17:46:54: Auto:5D-BA-C5-C4-03
2023/8/30 17:46:56: Mode = 0 : OK
2023/8/30 17:46:56: Eco flag : 0
2023/8/30 17:46:56: Mux flag : 1
2023/8/30 17:46:56: GET CLOCK LIMIT: 0
2023/8/30 17:46:56: GET GPU CLOCKS: 0, 0
2023/8/30 17:46:56: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/8/30 17:46:56: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/8/30 17:46:56: ScreenOverdrive = 1 : OK
2023/8/30 17:47:35: PowerLimit C0 = 25 : OK
2023/8/30 17:47:35: PowerLimit C2 = 87 : OK
2023/8/30 17:47:38: BatteryLimit = 80 : OK
2023/8/30 17:47:38: Monitor Power Off
2023/8/30 17:47:38: Monitor Power On
2023/8/30 17:47:38: AutoSetting for Online
2023/8/30 17:47:38: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&15ae9f2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/8/30 17:47:38: Mode = 0 : OK
2023/8/30 17:47:38: Eco flag : 0
2023/8/30 17:47:38: Mux flag : 1
2023/8/30 17:47:38: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/8/30 17:47:38: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/8/30 17:47:38: ScreenOverdrive = 1 : OK
2023/8/30 17:47:38: GET CLOCK LIMIT: 0
2023/8/30 17:47:38: GET GPU CLOCKS: 0, 0
2023/8/30 17:47:39: Auto:5D-BA-C5-C4-03
2023/8/30 17:47:39: Backlight:5D-BA-C5-C4-00
2023/8/30 17:47:40: PowerLimit C0 = 25 : OK
2023/8/30 17:47:40: PowerLimit C2 = 87 : OK
2023/8/30 17:47:41: BatteryLimit = 80 : OK
2023/8/30 17:47:41: Monitor Power Off
2023/8/30 17:47:41: Monitor Power On
2023/8/30 17:47:41: Monitor Power Off
2023/8/30 17:47:41: Monitor Power On
2023/8/30 17:47:41: Monitor Power Off
2023/8/30 17:47:41: Monitor Power On
2023/8/30 17:47:41: Monitor Power Off
2023/8/30 17:47:41: Monitor Power On
2023/8/30 17:47:41: Monitor Power Off
2023/8/30 17:47:49: Auto:5D-BA-C5-C4-03
2023/8/30 17:47:49: Backlight:5D-BA-C5-C4-00
2023/8/30 17:47:49: Backlight:5D-BA-C5-C4-00
2023/8/30 17:47:49: Backlight:5D-BA-C5-C4-00
2023/8/30 17:47:49: Backlight:5D-BA-C5-C4-00
2023/8/30 17:47:49: Backlight:5D-BA-C5-C4-00
2023/8/30 17:47:51: Monitor Power On
2023/8/30 17:47:51: AutoSetting for Online
2023/8/30 17:47:51: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&15ae9f2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/8/30 17:47:51: Mode = 0 : OK
2023/8/30 17:47:51: Eco flag : 0
2023/8/30 17:47:51: Mux flag : 1
2023/8/30 17:47:52: GET CLOCK LIMIT: 0
2023/8/30 17:47:52: GET GPU CLOCKS: 0, 0
2023/8/30 17:47:53: PowerLimit C0 = 25 : OK
2023/8/30 17:47:53: PowerLimit C2 = 87 : OK
2023/8/30 17:47:54: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/8/30 17:47:54: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/8/30 17:47:54: ScreenOverdrive = 1 : OK
2023/8/30 17:47:58: BatteryLimit = 80 : OK
2023/8/30 17:47:58: Monitor Power Off
2023/8/30 17:47:58: Monitor Power On
2023/8/30 17:47:58: AutoSetting for Online
2023/8/30 17:47:58: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&15ae9f2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/8/30 17:47:58: Mode = 0 : OK
2023/8/30 17:47:58: Eco flag : 0
2023/8/30 17:47:58: Mux flag : 1
2023/8/30 17:47:58: GET CLOCK LIMIT: 0
2023/8/30 17:47:58: GET GPU CLOCKS: 0, 0
2023/8/30 17:47:58: Auto:5D-BA-C5-C4-03
2023/8/30 17:47:58: Backlight:5D-BA-C5-C4-00
2023/8/30 17:47:59: Listener stopped
2023/8/30 17:47:59: Listener stopped
2023/8/30 17:47:59: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/8/30 17:47:59: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/8/30 17:47:59: ScreenOverdrive = 1 : OK
2023/8/30 17:48:07: PowerLimit C0 = 25 : OK
2023/8/30 17:48:07: PowerLimit C2 = 87 : OK
2023/8/30 17:48:11: BatteryLimit = 80 : OK
2023/8/30 17:48:11: Monitor Power Off
2023/8/30 17:48:11: Monitor Power On
2023/8/30 17:48:11: AutoSetting for Online
2023/8/30 17:48:11: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&15ae9f2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/8/30 17:48:11: Auto:5D-BA-C5-C4-03
2023/8/30 17:48:11: Backlight:5D-BA-C5-C4-00
2023/8/30 17:48:12: Mode = 0 : OK
2023/8/30 17:48:12: Eco flag : 0
2023/8/30 17:48:12: Mux flag : 1
2023/8/30 17:48:13: GET CLOCK LIMIT: 0
2023/8/30 17:48:13: GET GPU CLOCKS: 0, 0
2023/8/30 17:48:14: PowerLimit C0 = 25 : OK
2023/8/30 17:48:14: PowerLimit C2 = 87 : OK
2023/8/30 17:48:16: Listener stopped
2023/8/30 17:48:16: Listener stopped
2023/8/30 17:48:16: Listener stopped
2023/8/30 17:48:16: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/8/30 17:48:16: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/8/30 17:48:16: ScreenOverdrive = 1 : OK
2023/8/30 17:48:16: BatteryLimit = 80 : OK
2023/8/30 17:48:16: Monitor Power Off
2023/8/30 17:48:16: Monitor Power On
2023/8/30 17:48:16: AutoSetting for Online
2023/8/30 17:48:16: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&15ae9f2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/8/30 17:48:16: Backlight:5D-BA-C5-C4-00
2023/8/30 17:48:16: Auto:5D-BA-C5-C4-03
2023/8/30 17:48:17: Mode = 0 : OK
2023/8/30 17:48:17: Eco flag : 0
2023/8/30 17:48:17: Mux flag : 1
2023/8/30 17:48:17: GET CLOCK LIMIT: 0
2023/8/30 17:48:17: GET GPU CLOCKS: 0, 0
2023/8/30 17:48:17: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/8/30 17:48:17: \\?\DISPLAY#BOE0B35#4&9fbf4ff&1&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/8/30 17:48:17: ScreenOverdrive = 1 : OK
2023/8/30 17:48:17: BatteryLimit = 80 : OK
2023/8/30 17:48:17: Monitor Power Off
2023/8/30 17:48:17: Monitor Power On
2023/8/30 17:48:17: Monitor Power Off
2023/8/30 17:48:17: Monitor Power On
2023/8/30 17:48:17: Monitor Power Off
2023/8/30 17:48:17: Monitor Power On
2023/8/30 17:48:17: Monitor Power Off
2023/8/30 17:48:17: Monitor Power On
2023/8/30 17:48:17: Auto:5D-BA-C5-C4-03
2023/8/30 17:48:17: Backlight:5D-BA-C5-C4-00
2023/8/30 17:48:17: Backlight:5D-BA-C5-C4-00
2023/8/30 17:48:17: Backlight:5D-BA-C5-C4-00
2023/8/30 17:48:17: Backlight:5D-BA-C5-C4-00
2023/8/30 17:48:18: PowerLimit C0 = 25 : OK
2023/8/30 17:48:18: PowerLimit C2 = 87 : OK
2023/8/30 17:48:20: Hibernate after 1800

**Comment by AuroraRock** [comment]
Now it seems that all these commands sleep the computer, the same as what Fn+F11 does, so hiding this feature on unsupported laptops should be the best solution :)

**Comment by seerge** [comment]
@AuroraRock you mix "Turn off display" and "Sleep". It's 2 separate actions (even in control panel)

![Screenshot 2023-08-30 124129](https://github.com/seerge/g-helper/assets/5920850/42ba9c80-01c4-4251-85a9-c4924c2666d4)

When you turn off display in windows, it will lock you (assuming you have default windows settings) and most probably require PIN / faceid when you enable screen. This is how things work in the system.

> so hiding this feature on unsupported laptops should be the best solution :)
It has nothing to do with supported / unsupported laptops. As this is windows behavior. And cause this function was requested by multiple users, I will keep it :) 

Closing as completed, as it seem to do what it's supposed to do in your case as well.

**Comment by AuroraRock** [comment]
Unfortunately, it still doesn't work. I will look for the reason on my computer and Windows. Thank you for your help.
