### ISSUE TITLE
keyboard malfunction after changes to m1 - m3 and fn lock in ga401 model (2021)

### ISSUE THREAD

**Issue by rval-11** [seerge/g-helper#1219]
**Describe the bug**
After making changes to m1-m3 and turning on fn lock, keyboard keys q, t, y, and o were not working.

**Clear scenario to Reproduce**
Make changes to m1 -m3 in the extra tab for the keyboard binding options and turn on fn lock. Then q, t, y, o was not working on my specific build of ga401. 

**Expected behavior**
After looking at the windows page for the expected behavior of the m1 to m3 keys, I was hoping to properly use volume up and down and the mute mic button. 

**App Logs**

[log.txt](https://github.com/seerge/g-helper/files/12473888/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ga401qm

**Asus software**
- Armoury Crate uninstalled
- MyASUS uninstalled
- Disabled all Asus services running in background

**Additional context**
For some time, my q, t, y, and o button were not working. I removed the asus display app from my system and removed the m1 - m3 from the config file. After restarting, the t, y, and o buttons were working again. The problem was that q was still not working. Q is still sluggish in working (I have to press q quite a bit to getting it working). I got it working after removing the fn lock option from the config file but is still not working as it should (was not working at all before removing the fn lock option from the config file). After not using q for some time, it will begin to lag heavily again. I can't pinpoint the issue exactly, but I am putting it here because I believe my keyboard keys not working was a software issue and not a hardware issue as the keys clearly work after removing some small things from the config file. I really love the app and would hope to help make the app usable for everyone to enjoy. Thanks for your time, and appreciate the hard work from all who contribute to this app.

**Comment by seerge** [comment]
@rval-11 hello, app doesn't touch your m,q,t, etc buttons anyhow :) 
Do keys start working immediately if you quit app ? If not - your problem is somewhere else.

**Comment by rval-11** [comment]
Yeah I believe the issue is elsewhere, the working t, y, and o keys was short lived. After leaving the keyboard alone for some time, the keys began to malfunction again. I uninstalled the keyboard driver and restarted the computer, which seemed to fix the issue. But I'm sure the problem will return. Thanks for the quick reply, I appreciate it.
