### ISSUE TITLE
cpu fan not working

### ISSUE THREAD

**Issue by wdweng** [seerge/g-helper#1221]
**Describe the bug**
cpu fan is not working under all modes using factory defaults
its speed is slower than the curve speed

**Clear scenario to Reproduce**
just found that and i dont konw why

**Expected behavior**
fan should be faster

**App Logs**

[log.txt](https://github.com/seerge/g-helper/files/12474209/log.txt)

**Screenshots or screencasts**
<img width="828" alt="5682ed2b72779f752032881a7d699ee" src="https://github.com/seerge/g-helper/assets/79965876/50a4f38f-b416-4a6e-83c7-a78dc6114536">

**Desktop (please complete the following information):**
windows 11
asus g16 2023

**Asus software**
no asus software running 

**Additional context**

**Comment by seerge** [comment]
@wdweng what do you mean under "not working"? It's at 3600RPMs on your screenshot.

G-Helper doesn't control your fans anyhow https://github.com/seerge/g-helper#how-does-g-helper-control-my-fan-speeds . Modes are baked in BIOS along with fan settings.
