### ISSUE TITLE
[Feature request] Asus Page UP DOWN toggle

### ISSUE THREAD

**Issue by squee666** [seerge/g-helper#1224]
didnt realise this was a thing as well

30/08/2023 04:30:29 PM: Key: 75

Pressing the dedicated key toggles the arrow keys into  home/pg down/page up and end

https://i.imgur.com/7jdxRYS.png

https://i.imgur.com/6Wby6oc.png

PGUP/PGDN Mode

 Key: 75 

seems be a feature on all zeph duo models from 15 upwards 

https://i.imgur.com/LSDhzIR.png

Heres how it works by default

- Arrow Keys Mode
- Left Arrow
- Up arrow
- Down Arrow
- Right Arrow

pressing the key toggles it on until turned off

- PGUP/PGDN Mode
- Home Key (left arrow)
- Page Up (up arrow)
- Page Down (down arrow)
- End (right arrow)

**Comment by seerge** [comment]
@squee666 does FN+up / down generate PgUP / PgDown commands on your keyboard ? 

I'm honestly not a big fan of adding this to the app, as it can cause problems for others. As app would have to register all arrow keys as keybindings ...

**Comment by squee666** [comment]
Yes FN does allow the keys to work, I suppose can map the key to an FN toggle lock.

I just assumed it would not be an issue of it remapping the arrow keys as it would only remap the keys when the button is pressed and undo the mapping when pressed again
basically an FN lock for only 4 keys

**Comment by seerge** [comment]
@squee666 try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/12480230/GHelper.zip)

**Comment by squee666** [comment]
yup that works exactly as intended

**Comment by seerge** [comment]
Great
