### ISSUE TITLE
Allow fan curve changes via arrow keys

### ISSUE THREAD

**Issue by fscottcopeland** [seerge/g-helper#1225]
Just a small request... It's a bit of a pain trying to use the mouse to drag around the fan curve points, especially on higher DPI screens with low scaling. It would be great if we could select a point and use the arrow keys to move it around that way.

Also, is it possible to support a greater number of individual curve points? Or is there a hard limit?

**Comment by seerge** [comment]
@fscottcopeland number of points is always 8. 

App uses microsoft charts component to plot curves, so it will be very difficult to make it keyboard editable.  But you can hold SHIFT to drag whole curve points all together :)

**Comment by fscottcopeland** [comment]
Ah okay got you. Thanks
