### ISSUE TITLE
Backlight state not saved

### ISSUE THREAD

**Issue by thduc87** [seerge/g-helper#1226]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**
Sometimes after restart pc, backlight state is not saved from last session, i.e. blacklight is on when restart but in was off previously, it's supposed to stay off.

**Clear scenario to Reproduce**
4. Explanation of an error or a bug

**Expected behavior**
Backlight state should be the same as last session.

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``

[log.txt](https://github.com/seerge/g-helper/files/12485454/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Laptop model

**Asus software**
- Armoury Crate (or it's services installed)
- MyASUS installed
- Other Asus services running in background

**Additional context**

**Comment by seerge** [comment]
@thduc87 at what moment in your log it was not saved ?

App has 2 separate backlight settings for battery / plugged in states. So if you power off on battery , and then power on plugged - app will obviously set last remembered plugged brightness. 

From the log i see that app ALWAYS over last multiple times set brightness to OFF intentionally 

```Auto:5D-BA-C5-C4-00```

**Comment by briliggt** [comment]
Hello, due to my poor English you may not understand my question, let me explain it：
 When I use G-Helper to change the color of my keyboard, I always fail to save my customized color. If I customize two colors of the keyboard, I could only save the color I am using after turning off G-helper. And the other color seems to disappear with no reasons. And I want to know that is it possile to save all of my customized keyboard colors（used and unused ones） even after turning off the G-Helper？

**Comment by briliggt** [comment]
you can see this picture
<img width="1004" alt="image" src="https://github.com/seerge/g-helper/assets/143986920/aa312049-8c2e-4795-aca1-61f2dcca8ce4">

**Comment by briliggt** [comment]
You can see that I saved a custom color. When I close the color selection page, the saved colors will be cleared, leaving only the G-helper preset colors.

**Comment by seerge** [comment]
@briliggt ah, that is absolutely fine. As it would require quite a lot of extra stuff to save them.

I have already answered this in same duplicate topic https://github.com/seerge/g-helper/issues/1217
