### ISSUE TITLE
Keyboard Backlight Malfunctioning

### ISSUE THREAD

**Issue by pav-li** [seerge/g-helper#1230]
2023 Zephyrus G14 GA402NV
Keyboard backlight malfunctioning. Will not show a backlight when setting keyboard backlight effect to static under any circumstance. However, backlight will do breathe effect ONLY IF the left colour is set to white, and the right colour is set to black. It will not work in any other configuration. After the breathe effect has been set, no matter what other effect I choose it will continue to do the breathing effect, UNLESS I set the effect to static, after which the backlight turns off.

[log.txt](https://github.com/seerge/g-helper/files/12489602/log.txt)

![Screenshot 2023-08-31 203339](https://github.com/seerge/g-helper/assets/143750707/cb61a0df-e4d7-46f6-86cf-69fa23a667df)
Above is the only configuration in which I can get a backlight to occur.

**Desktop:**
 - OS: Windows 11
 - Zephyrus G14 GA402NV

**Asus software**
-All ASUS software uninstalled
-ASUS control interface latest driver installed

**Comment by seerge** [comment]
@pav-li hello

I assume you have single color backlight on your device
Try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/12490501/GHelper.zip)

**Comment by pav-li** [comment]
Yes, I have the single colour backlight, however this build was no different unfortunately and I am suffering from the same issue.

**Comment by seerge** [comment]
@pav-li can you post a log from running a new build ? Also try to set color to pure RED

**Comment by pav-li** [comment]
[log.txt](https://github.com/seerge/g-helper/files/12490569/log.txt)
Here is the log, changing the colour to pure red actually made the backlight appear back thank you!

**Comment by seerge** [comment]
@pav-li try this build, it should work with all colors
[GHelper.zip](https://github.com/seerge/g-helper/files/12490674/GHelper.zip)

**Comment by pav-li** [comment]
Yes it's working perfectly now, thank you for your help.

**Comment by seerge** [comment]
Bingo
