### ISSUE TITLE
G helper keeps popping on task bar on every other key press especially Ctrl, Enter or keys like them

### ISSUE THREAD

**Issue by shivam-gamitronics** [seerge/g-helper#1232]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**

**Clear scenario to Reproduce**
1. Start G Helper
2. Setup your desired profile
3. Now open any other app and start typing
4. It keeps on popping in taskbar

**Expected behavior**

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12494239/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Zephyrus G14 

**Asus software**
- MyASUS is installed

**Additional context**
I don't have Armory crate installed, I have uninstalled it

**Comment by seerge** [comment]
@shivam-gamitronics what do you mean under “popping up”?

I see that you spam M4 key 

‘’’
01-09-2023 09:49:49: WMI event 56
01-09-2023 09:50:31: WMI event 56
01-09-2023 09:50:32: WMI event 56
01-09-2023 09:50:33: WMI event 56
01-09-2023 09:50:33: WMI event 56
01-09-2023 09:50:33: WMI event 56
01-09-2023 09:50:34: WMI event 56
01-09-2023 09:50:34: WMI event 56
01-09-2023 09:50:34: WMI event 56
01-09-2023 09:50:35: WMI event 56
01-09-2023 09:50:37: WMI event 56
01-09-2023 09:50:39: WMI event 56
01-09-2023 09:50:48: WMI event 56
01-09-2023 09:50:49: WMI event 56
01-09-2023 09:50:49: WMI event 56
01-09-2023 09:50:50: WMI event 56
01-09-2023 09:50:50: WMI event 56
01-09-2023 09:50:50: WMI event 56
01-09-2023 09:50:51: WMI event 56
01-09-2023 09:50:51: WMI event 56
01-09-2023 09:50:51: WMI event 56
01-09-2023 09:50:52: WMI event 56
01-09-2023 09:50:52: WMI event 56
01-09-2023 09:50:53: WMI event 56
01-09-2023 09:50:53: WMI event 56
01-09-2023 09:50:53: WMI event 56
01-09-2023 09:50:53: WMI event 56
01-09-2023 09:50:54: WMI event 56
‘’’

Also make sure to stop Asus services under Extra -> Stop services

**Comment by shivam-gamitronics** [comment]
by popping up I mean it keeps on restarting.
![image](https://github.com/seerge/g-helper/assets/34132236/83fcdda9-20a3-4140-aa10-e414e883ceb5)
like this in task bar

**Comment by shivam-gamitronics** [comment]
by popping up I meant it keeps opening/restarting. 
![image](https://github.com/seerge/g-helper/assets/34132236/1fef7802-bd5f-4643-9cd3-b70e85bfa30f)

**Comment by seerge** [comment]
@shivam-gamitronics hello. From log it's clear that app is not "restarting".

But your keyboard keeps spamming M4 (ROG) key that by default would hide / show main app window. 

I don't know why it's happening in your case. It's either broken hardware or asus services behave inadequately. 

1. I have already advised you to stop them ``Extra -> Stop services ``
2. If your keyboard is broken on hardware level, you can set M4 key to do nothing at all : set M4 to ``"Custom"`` action under ``Extra`` settings
