### ISSUE TITLE
[Feature request] Static fan speed

### ISSUE THREAD

**Issue by Cooper11223** [seerge/g-helper#1234]
**Problem:**
Hey, would it be possible to implement selectable static fan speed? E.g set the fan speed to 2000rpm and it never increases no matter the temperature. I record music in my room and the laptop fan noise often ruins it. I get somewhat around it by setting the fan curves low, but the curve is forced to go up according to the temperature. After 80 degrees, the fan curve is forced to increase, thus increasing the speed and the noise
![ss1](https://github.com/seerge/g-helper/assets/143805315/2858bc33-ed7b-4e79-acd6-96dc1f12e168)
**Solution:**
A simple slider that lets you select the desired fan speed.

**Problem:**
Another feature I was thinking of was an option to select which fan profiles to cycle from when using the shortcut key. Out of my 4 profiles, 2 are situational and don't get used in my day to day activities
**Solution**
An option to add or remove the profile from the profile shortcut cycle. Maybe something like a tick mark on every profile that adds or removes the profile from the shortcut cycle.

Laptop: Asus Zephyrus M GU502GU 2019 model
Bios: 306

**Comment by seerge** [comment]
@Cooper11223 you can drag all fan dots together by holding SHIFT key, so drag the most left dot with shift to the top to make line flat, then move it down to your required level.

That would be your "static" fan
