### ISSUE TITLE
Disabling XG Mobile always put's it in Eco mode

### ISSUE THREAD

**Issue by moritzbeck01** [seerge/g-helper#1235]
**Describe the bug**
Title basically

**Clear scenario to Reproduce**
1. GHelper is in Standard mode (or Optimized and plugged in)
2. Enable XG Mobile
3. whatever
4. Disable XG Mobile
5. GHelper is in Eco mode
6. XG Mobile cannot be actived in Eco mode
7. Have to return to Standard (or Optimized) mode

**Expected behavior**
GHelper returns to the previous mode (which currently can only be Standard or Optimized) or at least a mode where the last action (disabling the XG mobile) can be reverted (by activating it) -> idempotence 

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12501493/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: X13 2023

**Asus software**
- Armoury Crate (or it's services installed): no
- MyASUS installed: no
- Other Asus services running in background: stopped

**Additional context**
I only have a iGPU and no onboard dGPU. Not exactly sure what Eco vs. Standard even does then, why the XG Mobile can only be activated from Standard mode (or Optimized when plugged in) and if and how any of this plays into it here.

**Comment by seerge** [comment]
@moritzbeck01 hello, i have checked a log and it looks like it's hardcoded like that in BIOS (G-Helper doesn't set eco mode)

```
01.09.2023 22:58:54: Eco flag : 0 - app checked current status - ECO WAS OFF
01.09.2023 22:58:54: Mux flag : -65536
01.09.2023 22:59:02: WMI event 190
01.09.2023 22:59:02: WMI event 194
01.09.2023 22:59:05: GPU XGM = 0 : OK - disabling XGM
01.09.2023 22:59:05: WMI event 123
01.09.2023 22:59:05: WMI event 123
01.09.2023 22:59:15: Design Capacity: 75001mWh, Full Charge Capacity: 72870mWh, Health: 0,971587045506059919201077319%
01.09.2023 22:59:20: Eco flag : 1 - app checked current status and ECO is suddenly ON
01.09.2023 22:59:20: Mux flag : -65536
```

I can add some extra command after disabling XGM, to set dGPU on ... but i'm not sure if I should, as it's clearly asus engineers did that on purpose

**Comment by seerge** [comment]
@moritzbeck01 closing as not planned, as there is nothing to fix here :) in your case eco = standard (you see the switch in a first place because app just sees that eco flag exists in bios)

**Comment by moritzbeck01** [comment]
Thanks, so changing into what mode it goes is not possible, right? But can you remove the restriction to only enable from Standard mode and allow Eco aswell? Would fix my problem too.

**Comment by seerge** [comment]
@moritzbeck01 what's your specific model name ? you have uploaded only fraction of the log, so it's not there

**Comment by seerge** [comment]
I can only assume it's GV301RA

This build should allow enabling XG Mobile with this model even in eco
[GHelper.zip](https://github.com/seerge/g-helper/files/12505980/GHelper.zip)

**Comment by moritzbeck01** [comment]
> what's your specific model name ?

GV302XA, but is it not possible to make this model independent?

**Comment by seerge** [comment]
@moritzbeck01 no, cause you app reports a dGPU on/off flag (eco), so i can't separate it from other devices

Check this build

[GHelper.zip](https://github.com/seerge/g-helper/files/12507150/GHelper.zip)

**Comment by Wolper321** [comment]
GV302XA is the model without dGPU the same as mine. So check first if you even have the GPU modes in AC. I am almost sure you have no switch and this makes your laptop constantly in eco.

**Comment by seerge** [comment]
@moritzbeck01 because for devices that have dGPU - it has to be in "Standard" mode prior to enabling XGM. At least according to another user who asked about that limitation explicitly :) 

https://github.com/seerge/g-helper/issues/423#issuecomment-1556144313

Does the build i linked here work fine for you ?

**Comment by moritzbeck01** [comment]
@seerge 

> Does the build i linked here work fine for you ?

Yes, seems to work.

> because for devices that have dGPU - it has to be in "Standard" mode prior to enabling XGM.
Could you then allow changing from Eco mode but also set Standard mode flag in BIOS when enabling XG Mobile? I think even for users with dGPU it would be broken in Optimized mode otherwise.

**Comment by moritzbeck01** [comment]
> I think its better to not to create a new potential point of failure

👍


> and do it same as ac does :)

But Armory Crate does it exactly that way?

**Comment by moritzbeck01** [comment]
@seerge I think the newest update broke something - I cannot disable the XG Mobile anymore.

**Comment by seerge** [comment]
@moritzbeck01 "newest update" is what version? and in what version it still works (can you test it again?)

As i didn't change anything in the app related to xgm at all since this discussion

**Comment by moritzbeck01** [comment]
Seems like it's related to something else, it isn't working on any recent older version either. I probably just noticed it now since I tried to disconnect after updating. Enabling works fine though. 
[log.txt](https://github.com/seerge/g-helper/files/12718281/log.txt)

**Comment by moritzbeck01** [comment]
Should I open a new issue for this or is it unrelated to G-Helper? @seerge

**Comment by seerge** [comment]
@moritzbeck01 what do you mean under not being to disable it ? How do you know it's not disabled after ?

In a log disable command seem to go though (with a positive response)

```
25.09.2023 19:42:41: GPU XGM = 0 : OK
```

**Comment by moritzbeck01** [comment]
@seerge Well my screen connected to it is still on, for starters. Also G-Helper still displays it as connected. It seems to load something and then just silently fail.

**Comment by seerge** [comment]
@moritzbeck01 i see, but since it worked before and then stopped i don't think it's something i can "fix" as the command is the same for all devices

**Comment by moritzbeck01** [comment]
Okay, I understand. Is there any starting point to look why this is happening?

**Comment by seerge** [comment]
@moritzbeck01 i don’t know:) try to do hardware reset of a laptop may be?

**Comment by Wolper321** [comment]
> Okay, I understand. Is there any starting point to look why this is happening?

When I was testing different XGM activation commands I was also unable to disable XGM in Ghelper. Exactly in the way you have described. 
I just ended up manually unplugging it and continued with the system warning. With the correct activation command (the special one for 6850M XT), I have never experienced it again.

**Comment by moritzbeck01** [comment]
I have a 3080 though. Maybe they changed it in a driver update?

**Comment by Wolper321** [comment]
> I have a 3080 though. Maybe they changed it in a driver update?

Check in your config if you have "xgm_special": 1. Maybe this messing with your 3080.

**Comment by moritzbeck01** [comment]
> Check in your config if you have "xgm_special": 1. Maybe this messing with your 3080.

I had to restart before it worked, but that did the trick. Thank you very much! Now I just wonder why this was set. I can't remember doing that...

**Comment by seerge** [comment]
@moritzbeck01 app would set ``xgm_special`` flag automatically , but only if it spots a 6850M connected (this is for @Wolper321 's case as 6850M requires special connection command)

https://github.com/seerge/g-helper/blob/03944dc20865b83d15421b9bc8a6ed00c0c0cc06/app/HardwareControl.cs#L270

Did you by any chance used 6850M as well (before) ?

**Comment by moritzbeck01** [comment]
Not really, but my 3080 was connected to another laptop that uses the 6850M.

**Comment by seerge** [comment]
@moritzbeck01 haha, i don't think it spreads like that. 

Anyway unless you have set flag by yourself, it was added by G-Helper cause it has spotted 6850M in the system.

As you see in the code, it's quite explicit check :)

**Comment by moritzbeck01** [comment]
Maybe I absent-mindedly changed it when I wanted to do something else, idk :D
