### ISSUE TITLE
Manual Mode Throttling CPU and GPU Since V0.112

### ISSUE THREAD

**Issue by XyKER1** [seerge/g-helper#1237]
**Describe the bug**
When using a manual mode (apply power limits checked) in the latest version of G-Helper, the CPU and GPU are throttled from 160W combined to 130-135 W.  If I change back to the default turbo mode, combined power goes back up to 160 W.  As you can see in the video linked below, I downloaded G-Helper v0.69 (which is the first one I open), and the CPU and GPU are unlocked to 160 W with that version of G-Helper.  However, when I open up the second one (which is v0.115), the CPU and GPU are clearly being limited heavily.

**EDIT: I narrowed it down to v0.112.  v0.110 exhibits normal behavior, v0.112 is when the weird throttling begins.  I saw you added in clock limiting, I tried playing around with this slider (set it to 2100 Mhz, which is around where my overclock is), and it didn't make a difference.  I can only assume it has something to do with the Windows Power Plan modification you made in v0.112 then, since it seems like it might be in power saving mode (note that in the video, power plan is set to Best Performance already).**

**Clear scenario to Reproduce**
1. Create a custom profile
2. Check "apply power limits" to apply
3. Use MSI Afterburner to check CPU and GPU power draw

**Expected behavior**
CPU and GPU should be unlocked to 160 W combined like they always were in previous versions of G-Helper (again, as you can see from the video).

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12503070/log.txt)

**Screenshots or screencasts**
https://youtu.be/4-LLYzKreps

**Desktop (please complete the following information):**
Windows 11 Home
i7-12700H
32 GB 4800 Mhz DDR5
RTX 3060 Laptop
FX507ZM

**Asus software**
Armoury Crate is not uninstalled, only Asus service running are Asus Hotplug Controller and Asus Smart Display Control (disabled the rest with G-Helper).

**Additional context**
Also, I reset my BIOS and enabled everything in device manager, so this is not being caused by any of the modifications I have been doing to stop the EDP throttling that I'm sure your notifications have been filled with.
I also have not made any modifications in MSI Afterburner that could've been affecting this.
I have checked this with multiple games, it's not just this one.

**Comment by seerge** [comment]
@XyKER1 I have added "manual" mode flag (the one [you could set in config](https://github.com/seerge/g-helper/issues/511)) to be automatically on for your model, because of this request https://github.com/seerge/g-helper/discussions/1064 
(user was complaining that power limit doesn't work otherwise)

You are actually were asking about almost same thing before https://github.com/seerge/g-helper/issues/511

But in your log i see that in old version you had "manual" flag off completely (i assume cause you don't need to limit CPU ?) you can just uncheck "Apply" under CPU section in Fans+Power

**Comment by XyKER1** [comment]
@seerge So you're saying in v0.112 you added this auto manual mode apply?  Like I said, the issue is not present in v0.110 and earlier.  I like using manual mode because I can reach a higher GPU overclock than in Turbo mode.  With Armoury Crate and v0.110, manual mode doesn't have these limits.
I also noticed that in Balanced mode without apply power limits checked, the behavior is the same as in Turbo mode with apply power limits checked.  So I think it has something to do with the wrong Windows power mode being applied.

**Comment by seerge** [comment]
@XyKER1 

As it follows from #511 and #1046 your specific model requires a special “manual” mode to be enabled prior to setting CPU power limits in order to actually male them work

If you don’t apply CPU power limits, you sill use Silent , Balaned or Turbo. As soon as you click apply - it becomes Manual

**Comment by XyKER1** [comment]
@seerge I know that.  There's something you changed about manual mode from v0.110 to v0.112 that seems to cause issues with my laptop though, as you can see in the video.  I guess I can always just use v0.110, but I'm pretty sure I remember you implementing that manual mode change before v0.112.

**Comment by seerge** [comment]
@XyKER1 As i told i have added your model to the list that would turn on manual mode as soon as power limit is applied in 0.112

**Comment by seerge** [comment]
In your log you run 0.69 in Turbo mode (without custom power limits)

And then run 0.115 in Manual mode with custom power limits 

That’s what is different

**Comment by XyKER1** [comment]
@seerge Thanks for trying to help!  Right now, I'm not interested in any games where my GPU hits the max OC limit, so Turbo vs Manual mode doesn't make a different anyway.  I'll just use default Turbo mode (uncheck power limit) for now.  In the future, I might compare G-Helper with Armoury Crate to compare performance (since manual mode in AC allows for full power draw along with custom fan curve and GPU tweaking) if I find a game where it makes a difference.

**Comment by seerge** [comment]
Your GPU is untouched anyhow on 0.112, unless you set different mode

**Comment by seerge** [comment]
@XyKER1 do power limits on CPU work for you in 110 or 69 ? w/o setting "manual" mode ?

**Comment by XyKER1** [comment]
Sorry for the late response, I forgot to test this last weekend.  However, I found a way to allow Throttlestop to change power limits without having to restart my laptop, which is why I requested that fix (so I didn't have to restart).  So if you could "undo" that manual mode fix for my model in the next release, that would be great!

**Comment by XyKER1** [comment]
@seerge I know that, but I prefer to have fan and GPU control.  I think the only thing that check mark does is allow power limits to work, but I don't need that anymore.  I think I'm the only one with this model that cared about this, so surely you can remove my model from the list of models that applies this fix instantly (since it causes my CPU and GPU to be throttled down to a lower power level).  If you don't want to do this, I understand, I'll just use v0.110 from now on.  Or is there some way for me to disable this fix in the config file?

**Comment by seerge** [comment]
@XyKER1 not applied power limits has absolutely nothing to do with your GPU and fan control

**Comment by XyKER1** [comment]
Ah, OK, for some reason I thought it did.  One last question.  Since v0.112, does clicking apply power limits do the exact same thing as pasting "manual_mode:1" into the G-Helper config file for my model?  Or does it do something completely different?

**Comment by seerge** [comment]
@XyKER1 yes, it does that (next to actually trying to apply CPU power limits)
