### ISSUE TITLE
Strange mode switching

### ISSUE THREAD

**Issue by TeccnoW** [seerge/g-helper#124]
**Describe the bug**
When I turn off the device in eco mode, it turns on in standard mode.

**To Reproduce**
1. Go to 'Ghelper'
2. Click on 'Eco'
3. Shut down pc
4. Turn on pc
5. See error

**Expected behavior**
When I did the same in Armoury create, it opened in whatever mode I turned it off in.

**Desktop (please complete the following information):**
 - OS: [Win11]
 - Zephyrus G15
 
**Additional context**
Normally the ı think bios keeps in memory that it is in Eco mode, but sometimes the video card crashes because Ghelper forces it to return to standard mode.

It's a bit tiring to always put the computer in standard mode before shutting it down.

![image](https://media.tenor.com/phNtnXgDQqcAAAAC/sorry-anime-anime-sorry.gif)

**Comment by seerge** [comment]
Hello, i"m not able to reproduce what you explain here. G-helper doesn't "force" standard modes on start at all. If you are not happy with app performance - you can always use armory of course.

**Comment by TeccnoW** [comment]
ı like G-helper, thank you.

**Comment by seerge** [comment]
Closing due to absence of an issue in the app.
