### ISSUE TITLE
Undervolting Intel CPU?

### ISSUE THREAD

**Issue by finalmakerr** [seerge/g-helper#1241]
I would be happy to dish Throttlestop for that.
Even if it's just a basic undervolt it's will be great as i use GHelper for almost everything now 🙏

**Comment by seerge** [comment]
@finalmakerr hello, i'm not aware about any of the reliable open source library / or solution that would allow you to do that.

Why don't you use Intel Extreme Tuning Utility ? It's from intel itself, and works well.

**Comment by seerge** [comment]
But to undervolt you don't need to run it constantly :) You just set it once and forget.
Also for some new models with Intel (Stirxes at least) asus has undervolt option in BIOS as well (f2 on boot)
