### ISSUE TITLE
CPU Boost

### ISSUE THREAD

**Issue by ari0508** [seerge/g-helper#1242]
How do you use CPU Boost? I use an Asus Zephyrus G15 GA503RS and I change the CPU Boost feature from aggressive to disabled, but every time I open my laptop or restart it refreshes back to Aggressive. How to solve this?

**Comment by seerge** [comment]
@ari0508 hello, it means something else is changing CPU Boost setting inside your windows power plan.

> ## NOTE
> Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. Please respect the time of the developer. Thanks.
