### ISSUE TITLE
Eco and Standard brightness differences

### ISSUE THREAD

**Issue by hustich** [seerge/g-helper#1244]
**Describe the bug**
When switching to Eco mode from Standard, even though the brightness slider in Windows remains unchanged, the brightness always seems to be slightly higher on Eco. Switching back to Standard from Eco lowers the brightness, without affecting the Windows brightness slider. The same behavior happens on the Optimized setting, when unplugging the power the brightness increases, and when plugging back the power, the brightness decreases. This brightness change is not visible if the screen brightness is set to lowest or highest.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - G733PZ

**Asus software**
- Armoury Crate was never installed
- MyASUS was never installed
- All Asus services are stopped using GHelper

**Additional context**
Only tested with the laptop's main display and no other secondary screen.
Tried with both "Automatic Select" and "Optimus" mode in Nvidia's Control Panel
[log.txt](https://github.com/seerge/g-helper/files/12506335/log.txt)

**Comment by seerge** [comment]
@hustich hello,

That's normal i think (you would have same in armoury). On Eco your dGPU is completely powered off, and therefore display is connected directly to iGPU on AMD

And on Standard dGPU is enabled, and all this shenanigans with Nvidia optimus begin , so Nvidia can interfere with brightness.

There is nothing G-Helper can do here :)

**Comment by hustich** [comment]
@seerge Thank you for your quick response :)

I see, so if I understand right, even if the dGPU is enabled but not in use, the brightness controls are passed to the dGPU? I was trying to look issue up online but all I could find were issues related to power plans and auto-brightness, are you aware of a potential fix that could make the dGPU and iGPU match brightness, perhaps an Nvidia or AMD drivers setting? Or maybe a topic somewhere else that discusses this issue? Thanks again for your help :)

**Comment by seerge** [comment]
@hustich i think they are passed to "Nvidia Optimus" (i.e. a Nvidia's own software/hardware solution to route display to iGPU/dGPU depending on circumstances)

I don't know how to fix it, but honestly don't see it as a big problem in a first place :)

**Comment by hustich** [comment]
@seerge I understand, so then nobody but Nvidia could do something about it.

It's true that not a big issue, I can learn to live with it. I just didn't know if it was normal since I couldn't find anyone else having this problem. Thanks again for the clarifications :)

**Comment by seerge** [comment]
@hustich you can try to do a clean and fresh reinstall of both AMD and Nvidia drivers using DDU to uninstall them first. Mb that will make situation better.

**Comment by NickProkoArt** [comment]
@hustich Hello! Were you able to somehow solve this problem?

**Comment by hustich** [comment]
@NickProkoArt I did not manage to find a solution unfortunately, I have been using Ultimate mode ever since.

**Comment by NickProkoArt** [comment]
Hmm... Reinstalled the video drivers. Did not help.
@hustich, @seerge Is it possible to somehow automatically press the hotkeys several times when switching to Eco GPU mode? (For example, fn+F7 is pressed twice automatically to lower brightness) After switching to standard mode, again hotkey worked a couple of times (fn+F8) to raise the brightness back. 
Or even better, maybe I can set automatically the brightness through Windows, for example, 42 in eco mode and 60 in standard mode? I would be grateful for any hint on how to do this.
