### ISSUE TITLE
Battery health decrease after using g-helper

### ISSUE THREAD

**Issue by xiyivan** [seerge/g-helper#1245]
## NOTE

[battery-report.pdf](https://github.com/seerge/g-helper/files/12506393/battery-report.pdf)

**Describe the bug**
The battery health quickly decreased to  63.3% after I use g-helper.

**Clear scenario to Reproduce**
I downloaded and started to use the software since 9/25, and as you can see from the battery report I included , the health had decredased rapidly for the next few days. I wonder whether that is related with the batery charging strategy used by the g-help or is it just a bug with the windows os.
I also found that the bar used to adjust the max charging percentage is rather hard to operate. By that I mean it is not responing for the majority of time when I try to scroll it. 

I used to the g-helper alongside with the Myasus cuz I need some funcationality provided by that software from asus, but I keep the restriction in the g-helper as 80% as well. I had changed that to different values at the very begining because the bar wasn't responsing to my operation, but the time was short- shorter than 2hours.

**Expected behavior**
I keep my laptop connected to the power supply for the majority of time, and I am using the stock adapter, so I expect the battery health decreases as previous days recorded in the battery report, rather than the sharp decrease after I installed the g-helper.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12506390/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model : rog flow x13

**Asus software**
- Armoury Crate removed
- MyASUS installed

**Additional context**
After I noticed this problem, I contact the asus costomer service. However, the diagnose performed by MyAsus shows that my battery is now "Good".
<img width="826" alt="image" src="https://github.com/seerge/g-helper/assets/112043984/2208bdde-5721-4c44-95d6-0a274f2e30f0">
I plan to visit the local store this week, but they previous told me that it is very hard for me to get a replacement in this situation.

**Comment by xiyivan** [comment]
I don't think the image I attached in my previous thread is visible, so I am uploading it again here.
<img width="826" alt="屏幕截图 2023-09-03 232656" src="https://github.com/seerge/g-helper/assets/112043984/69cd8351-33e5-4e73-ac70-14f252e863c8">

**Comment by xiyivan** [comment]
I also noticed that the maximum capacity now is a constant 47,485 mWh, so I suspect that is a software issue rather than my battery actually decrease that much.

**Comment by seerge** [comment]
@xiyivan g-helper can set charge limit via same endpoint myasus uses, and I see that you set it to same value 80% :) So it's all good.

Your battery health could be very incaccurate as windows calibrates it, you may want to discharge and recharge battery again to full, it often can start showing different health :)

Keep in mind, that even if you run g-helper it doesn't mean that everything that happens with your computer is related to that.

**Comment by seerge** [comment]
@xiyivan check this topic https://www.reddit.com/r/ZephyrusG14/comments/164jxrf/battery_replacement_2020/ 

Recalibrating helped him a lot

**Comment by xiyivan** [comment]
yeah, I am currently using BetteryMon to perform the recaliberation process, hope that work.
