### ISSUE TITLE
Greaphical fan curve issues

### ISSUE THREAD

**Issue by MaixGit** [seerge/g-helper#1248]
**Describe the bug**
The fan curves randomly freak out when adjusting them and end up in a configuration that is physically impossible, additionally the curves don't accurately control the fan speed at the temperature I set them (see Additional Context).

**Clear scenario to Reproduce**
1. Go to 'Fans + Power'
2. Randomly click on the fan curves until they freak out

**Expected behavior**
The graphical fan curve should follow a logical linear correlation between the temperature and fan speed as defined by the points.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12508281/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/43832909/9c73f423-4a14-4c07-bcc0-476ef98dd3c1)

**Desktop (please complete the following information):**
 - Windows 10 Version 10.0.19045 Build 19045
 - ROG Zephyrus G14 GA401IU

**Asus software**
- Armoury Crate (or it's services installed)
- MyASUS installed

**Additional context**
I previously used Atrofac which worked perfectly for the fan curve but unfortunately stopped switching power plans after a windows update, and after switching to GHelper often the fans don't actually follow the curve I defined in GHelper, sometimes turning off when they are suppsoed to be on, or even running way above the defined curve. e.g. On the curve below, at 32c the fans run at 3600rpm when they are clearly supposed to be at 2400rpm. Additionally sometimes the numbers on hover suddenly change slightly (from 40c to 39c) after switching plans or reloading the config, I think this is all just due to the graphical implementation of the curves.
![image](https://github.com/seerge/g-helper/assets/43832909/aa4451b7-4aec-4c31-88c6-6db12c470fb0)

In my opinion the graphical curve is very finicky and would either need a rework or a manual button in which there are fields or even just a text/config file where I can assign percentages/rpm to temperatures like in Atrofac (Screenshot below). If this option already exists, sorry I didn't know, but the graphical curves are still messy.
![image](https://github.com/seerge/g-helper/assets/43832909/01cd1efc-d9c7-4632-bd72-82ca434ff77d)

All screenshots were taken with no Asus services running, after stopping them in GHelper.

**Comment by seerge** [comment]
@MaixGit hello,

No matter how much i randomly click on fan chart - I didn't manage to reproduce anything close to that.

I would advice just to click on "Factory defaults" then it would load what BIOS reports as your default fan cuve, and edit it from there by dragging dots.

1. Atrofac / Armoury and G-Helper use literally same endpoint to set fan curves (as this is the only one existing)
2. If you want to edit curve  in % values instead of RPM you can click on Y-axis and it will show %
3. As for following fan curve - it's up to BIOS algorithms on how to interpret a curve, from my experience it's mostly tries to follow it, but don't expect pixel-to-pixel accuracy anyway.

**Comment by MaixGit** [comment]
Thank you for the quick reply and sorry for asuming the programs use a different method for fan control. For me it's pretty easy to recreate the bug so I've recorded a video and the logs along with it below

https://github.com/seerge/g-helper/assets/43832909/94b7158b-6b43-4361-a93e-2b399baec0f4

[log.txt](https://github.com/seerge/g-helper/files/12517269/log.txt)

Is there any way to edit the fan curve within the bios? When I tried I didn't have a cursor to interact with, and not even a mouse helped, and navigating via arrow keys I couldn't find any fan curve options.

I know about the % to RPM switch when clicking the side column but I was more referring to the text input instead of a graphical input, with either rpm or % for certain temperature.

**Comment by seerge** [comment]
@MaixGit check this build, I have made some adjustments, so when you move mouse out of chart bounds it shouldn't shift dots.

[GHelper.zip](https://github.com/seerge/g-helper/files/12521216/GHelper.zip)

As for text-editing of the fan settings, it's quite exotic, but you can manually open ``%appdata%\ghelper\config.json`` and edit fan curves there. But keep in mind that values are in HEX not in decimals there.

**Comment by MaixGit** [comment]
Thank you, this build fixes the issue and works as expected. I'll keep woking on the fan curve to figure out how the bios algorithms follow it. One idea I've had so far is that on my pc instead of 8 points I only had 4 points for curve adjustments in the bios.
