### ISSUE TITLE
Question about custom lighting effect memory

### ISSUE THREAD

**Issue by briliggt** [seerge/g-helper#1249]
Hello, after I set the custom color of the keyboard lighting effect, if I don’t use it, the custom lighting effect I recorded will be cleared when I restart the computer. Can you try to make g-helper record my settings? The set lighting effect

**Comment by seerge** [comment]
@briliggt hello, I didn't really get what you want under "record lightning effect". It's not possible to "read" current color from keyboard at all.

If you set (by some reason) backlight settings using some other app, you can configure G-Helper to  [disable Aura initialisation on startup](https://github.com/seerge/g-helper#skip-keyboard-aura-initialisation-on-startup) at all  - by adding following line to config 

```
"skip_aura" : 1,
```
