### ISSUE TITLE
Battery, Optimize setting, aura lightning issues

### ISSUE THREAD

**Issue by kito30** [seerge/g-helper#1250]
So my current device is Asus Tuf A16, I have experience a few bugs and crahses with Ghelper. 
First of all, the change aura lightning seem to not work on Ghelper.
Secondly, the limit charger is not working eventhough I have stop all of the asus service and delete MyAsus and still seem not work.
Thirdly, when I leave the mode on optimize and when I plug in the laptop or unplug the laptop. The computer just blue screen and restart.
[log.txt](https://github.com/seerge/g-helper/files/12509862/log.txt)

**Comment by seerge** [comment]
@kito30 hello,

1. I tried to google your model FA617NS and on all pictures (and video reviews) it's being shown only with white backlight. Does it support Aura colors in a first place ? In the log I see that it simply rejects aura/color initialisation 
```
4/09/2023 3:23:20 PM: TUF RGB = B4-00-FF-FF-FF-EB-00-00-00-00-00-00 : 0
```
2. Charge limiter on new TUF models [supports only 80%](https://github.com/seerge/g-helper#battery-charge-limiter-is-not-working) (so if you would set any other value - it would ignore it). This is how it works on hardware level for you. Also make sure that you have Asus services stopped under Extra (as otherwise they would override charge limit settings) (also applies to @kingdom-of-warriors )

3. When you use Optimized and plug / unplug it would enable / disable your dGPU correspondingly. 
In a log i see lot's of times when you do that, and app kept running / being used fine after that so it clearly didn't get any crashes.

```
4/09/2023 4:02:29 PM: GPU usage: AMD Radeon RX 7600S %
4/09/2023 4:02:29 PM: Running eco command 1
4/09/2023 4:02:30 PM: GPUEco = 1 : OK
```
```
4/09/2023 4:02:28 PM: Running eco command 0
4/09/2023 4:02:29 PM: GPUEco = 0 : OK
```

If your computer crashed after disabling dGPU once, it could be some hiccup with drivers / windows as well (as the command itself to disable GPU is always same). 

You can turn dGPU on / off even in powershell as admin w/o any g-helper 
```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00090020, VALUE)
```
Where Value is 1 to disable dGPU (eco mode), and 0 to enable (Standard)

I would do a clean driver reinstall (for both AMD / NVidia) with DDU to make sure they are up date and clean.

**Comment by kito30** [comment]
Regarding the aura, what I mean is that not the rgb but the lighting mode like strobbing, breathing,.. not working.
Secondly, I have already set the battery limit on 80% and disable all of the service and still not working.

**Comment by seerge** [comment]
@kito30 
1. Do strobbing / breathing modes work in Armoury for you?
2. What is the definition of "not working" ? If it's already above 80% it won't discharge automatically. Also as it says in readme, many models start charting on reboot immediately, until app starts in windows and sets limit again.

**Comment by kito30** [comment]
1. Nothing works for me. In amoury crate it works.
2. About the charging. I've leave the charging rate at 80% but it keep charging up to 100%.

**Comment by kingdom-of-warriors** [comment]
But all the light modes does work in my Asus Tuf A15.

**Comment by seerge** [comment]
@kito30 

1. Can you try to set color to pure RED (and then check all modes and post a log from that here?)
2. Command to set charge limit is same for all laptops, try to run it manually in powershell as admin, does it make any difference ? Does MyASUS charge limiter work instead ?
```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00120057, 80)
```

@kingdom-of-warriors A15 is different device than A16 :)  so no wonder

**Comment by kito30** [comment]
1. The lightning still can not change anything.
2. The battery icon illustrate that it is smart charging but still reach 100%.

**Comment by seerge** [comment]
@kito30 

Oke, then it could be that in your specific case there is some unknown command that controls backlight modes on your device. I'm simply not aware of it :) (so far it was same command for all TUF models)

As for charger - does myasus able to set it to 80% ? if not - then i'm also out of ideas :) mb it's simply not working at all ?
Try to do a [hardware reset ](https://github.com/seerge/g-helper#how-do-i-do-a-hardware-reset-on-a-laptop) , mb it will help (it won't affect data anyhow)

**Comment by kito30** [comment]
Thank you, hard reset does not help. :((

**Comment by seerge** [comment]
@kito30 as for your backlight modes, I did a test build where I have removed all colors from command completely (as you don't have them anyway)

Can you check if it makes any difference ?

[GHelper.zip](https://github.com/seerge/g-helper/files/12514488/GHelper.zip)

**Comment by kito30** [comment]
I still can not changing the liht mode :((

**Comment by seerge** [comment]
@kito30 then I'm afraid I can't help you :) as I don't have your device, and it seem to be quite unique in a way it sets backlight.

**Comment by seerge** [comment]
@kito30 i have made one more change, can you check if this build makes any difference ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/12526327/GHelper.zip)

**Comment by seerge** [comment]
@kito30 if it doesn't, you can try to submit a DSDT dump (i.e. list of asus commands that your computer actually supports)

Please follow a guide from this topic https://github.com/seerge/g-helper/issues/38 and use **Method 2** (Method 1 is also helpful, but much less)

**Comment by kito30** [comment]
The patch you've sent me does not affect the aura lightning. Following your guide here is the dump file.
/// 


60024 : 8c308086 (2351988870)                                                                                           6005c : ffffffffffff0000 (-65536)                                                                                       6005d : ffffffffffff0000 (-65536)                                                                                       60061 : ffffffffffff0000 (-65536)                                                                                       60095 : 1 (1)                                                                                                           Invoke-CimMethod : Generic failure                                                                                      At line:5 char:20                                                                                                       + ...  $result = (Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -Cl ...                                         +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                 + CategoryInfo          : NotSpecified: (AsusAtkWmi_WMNB...PNP0C14\ATK_0"):CimInstance) [Invoke-CimMethod], CimExc     eption                                                                                                                   + FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand                                                                                                                          60096 : ffff0000 (-65536)                                                                                               80041 : ffffffffffff0000 (-65536)                                                                                       80042 : 0 (0)                                                                                                           80043 : ffffffffffff0000 (-65536)                                                                                       90014 : 0 (0)                                                                                                           90016 : 1 (1)                                                                                                           9001d : ffffffffffff0000 (-65536)                                                                                       90020 : 1 (1)                                                                                                           90029 : 0 (0)                                                                                                           90030 : 50 (80)                                                                                                         Invoke-CimMethod : Generic failure                                                                                      At line:5 char:20                                                                                                       + ...  $result = (Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -Cl ...                                         +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                 + CategoryInfo          : NotSpecified: (AsusAtkWmi_WMNB...PNP0C14\ATK_0"):CimInstance) [Invoke-CimMethod], CimExc     eption                                                                                                                   + FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand                                                                                                                          100031 : ffff0000 (-65536)                                                                                              100046 : ffffffffffff0000 (-65536)                                                                                      100054 : 0 (0)                                                                                                          100055 : ffffffffffff0000 (-65536)                                                                                      10005a : 0 (0)                                                                                                          110013 : 0 (0)                                                                                                          110014 : 0 (0)                                                                                                          110015 : ffffffffffff0000 (-65536)                                                                                      11001c : ffffffffffff0000 (-65536)                                                                                      Invoke-CimMethod : Generic failure                                                                                      At line:5 char:20                                                                                                       + ...  $result = (Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -Cl ...                                         +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                 + CategoryInfo          : NotSpecified: (AsusAtkWmi_WMNB...PNP0C14\ATK_0"):CimInstance) [Invoke-CimMethod], CimExc     eption                                                                                                                   + FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand                                                                                                                          110022 : ffff0000 (-65536)                                                                                              Invoke-CimMethod : Generic failure                                                                                      At line:5 char:20                                                                                                       + ...  $result = (Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -Cl ...                                         +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                 + CategoryInfo          : NotSpecified: (AsusAtkWmi_WMNB...PNP0C14\ATK_0"):CimInstance) [Invoke-CimMethod], CimExc     eption                                                                                                                   + FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand                                                                                                                          110023 : ffff0000 (-65536)                                                                                              Invoke-CimMethod : Generic failure                                                                                      At line:5 char:20                                                                                                       + ...  $result = (Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -Cl ...                                         +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                 + CategoryInfo          : NotSpecified: (AsusAtkWmi_WMNB...PNP0C14\ATK_0"):CimInstance) [Invoke-CimMethod], CimExc     eption                                                                                                                   + FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand                                                                                                                          110024 : ffff0000 (-65536)                                                                                              Invoke-CimMethod : Generic failure                                                                                      At line:5 char:20                                                                                                       + ...  $result = (Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -Cl ...                                         +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                 + CategoryInfo          : NotSpecified: (AsusAtkWmi_WMNB...PNP0C14\ATK_0"):CimInstance) [Invoke-CimMethod], CimExc     eption                                                                                                                   + FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand                                                                                                                          110025 : ffff0000 (-65536)                                                                                              110026 : ffffffffffff0000 (-65536)                                                                                      110027 : ffffffffffff0000 (-65536)                                                                                      120057 : 880000 (8912896)                                                                                               120061 : 20000 (131072)                                                                                                 12006c : 0 (0)                                                                                                          12006d : 0 (0)                                                                                                          120072 : fffeffff (4294901759)                                                                                          Invoke-CimMethod : Generic failure                                                                                      At line:5 char:20                                                                                                       + ...  $result = (Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -Cl ...                                         +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                 + CategoryInfo          : NotSpecified: (AsusAtkWmi_WMNB...PNP0C14\ATK_0"):CimInstance) [Invoke-CimMethod], CimExc     eption                                                                                                                   + FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand                                                                                                                          120075 : ffff0000 (-65536)                                                                                              120076 : ffffffffffff0000 (-65536)                                                                                      120077 : ffffffffffff0000 (-65536)                                                                                      Invoke-CimMethod : Generic failure                                                                                      At line:5 char:20                                                                                                       + ...  $result = (Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -Cl ...                                         +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                 + CategoryInfo          : NotSpecified: (AsusAtkWmi_WMNB...PNP0C14\ATK_0"):CimInstance) [Invoke-CimMethod], CimExc     eption                                                                                                                   + FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand  
120079 : ffff0000 (-65536)
12007e : 1 (1)
120094 : 2d (45)
120097 : 0 (0)
1200a0 : 0 (0)
1200a3 : 0 (0)
1200b0 : 0 (0)
1200b1 : 0 (0)
1200c1 : 0 (0)
130021 : 20004 (131076)
130024 : 1 (1)
130026 : 1 (1)
Invoke-CimMethod : Generic failure
At line:5 char:20
+ ...  $result = (Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -Cl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (AsusAtkWmi_WMNB...PNP0C14\ATK_0"):CimInstance) [Invoke-CimMethod], CimExc
   eption
    + FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand

130031 : ffff0000 (-65536)
130041 : ffffffffffff0000 (-65536)
///

**Comment by seerge** [comment]
@kito30 try this build and post a log from it
[GHelper.zip](https://github.com/seerge/g-helper/files/12536536/GHelper.zip)

**Comment by kito30** [comment]
[log.txt](https://github.com/seerge/g-helper/files/12536707/log.txt)
It works, thank you.

**Comment by seerge** [comment]
@kito30 great news, can you check if this build still works ? (i have removed some redundant commands)
[GHelper.zip](https://github.com/seerge/g-helper/files/12536799/GHelper.zip)

And another question - in last log I see that you have reverted charge limit to defaults (i.e. it doesn't set anything) . Is that correct ? If so - try to set it again to 80% with a slider in the app (and check in a log if it runs a command after that)

If that happens - app already does maximum it can do for charge limiter :)

**Comment by kito30** [comment]
@seerge The charge limits problems fixed, I just have to reconnect the battery. I did not see any redundant in commands, the mode in this A16 only have 3 modes which is static, strobe and breathing only.

**Comment by seerge** [comment]
@kito30 so last build works? closing as completed then
