### ISSUE TITLE
Temp sensor issues in Strix G15 AE

### ISSUE THREAD

**Issue by yohannesakd** [seerge/g-helper#1251]
Sort of a very personal issue but my Asus ROG Strix G15 AE has an issue with the temperature sensor. Basically any time the laptop is idling for 15 or more minutes, the temperature sensor stops reading values and only displays the last read value. This happens both in Armory Crate and G-Helper(I assume G-Helper hooks into the same interface), but HWINFO reports the proper temp values, any time this happens i notice the PC is basically burning and hard throttling and I have to hibernate or restart the PC for the sensor to start reading again. I'm thinking the sensor times out for some reason. But i wanted to know if its possible for me to modify your code to make the temperature sensor hook into the interface that HWINFO uses, I'm pretty unfamiliar with this type of programming so i just want to know if it's a possibility.

**Comment by seerge** [comment]
@yohannesakd hello, if you say that CPU sensor keeps reporting same value with both G-Helper and AC, then it's probably some issue on bios level, as both apps take reading from same endpoint.

Please keep in mind that your fans / throttling  /etc is also controlled on hardware level not by the app, so even if G-Helper will get temperature from some other source your computer will still behave same as before. 

Therefore I don't plan to turn G-Helper into hardcore monitoring app with millions of readings :)

**Comment by yohannesakd** [comment]
Alright, thank you for the response!
