### ISSUE TITLE
USB-C to External Monitor on Hibernation 

### ISSUE THREAD

**Issue by CodeIota** [seerge/g-helper#1256]
Hi, I recently installed G-Helper on my Asus Zephyrus G15 2022 GA503RM.
Description of the issue
I have an external monitor connected via USB-c to DP, when I had Armoury Crate installed, I used the settings when I closed the lid in Hibernate. When I opened the lid and pressed the power button and it automatically detected the external monitor and displayed the image on it. 
Now with G-Helper when coming out of hibernation it only shows image on the laptop, I have to disconnect and connect the USB-C from the DP to show image on my external monitor, it is as if it does not detect an external monitor.

Here are my logs
[log.txt](https://github.com/seerge/g-helper/files/12524786/log.txt)

**Comment by seerge** [comment]
@CodeIota hello.

G-Helper doesn't turn on or off your screen, same as Armoury crate doesn't. It's handled by Windows and GPU drivers. 

So check what have changed there in your settings.
