### ISSUE TITLE
Boot up sound switch

### ISSUE THREAD

**Issue by dimenybence** [seerge/g-helper#1257]
I think a switch would be good for the boot up sound:))

**Comment by seerge** [comment]
@dimenybence hello, this is a dublicate https://github.com/seerge/g-helper/issues/261
You can toggle it in bios

**Comment by dimenybence** [comment]
oh thank you

**Comment by seerge** [comment]
@dimenybence added in https://github.com/seerge/g-helper/releases/tag/v0.120
