### ISSUE TITLE
Make Anime Matrix clock look more like Armoury Crate's clock

### ISSUE THREAD

**Issue by Secreto31126** [seerge/g-helper#1260]
**Is your feature request related to a problem? Please describe.**
I would love having an option to pick among different clock styles, in particular to make it look like AC's clock design which I'm too used to.

**Describe the solution you'd like**
Since you are working on gif's customization support for the Anime Matrix, maybe adding more clock options could work nice.

**Describe alternatives you've considered**
Long shot idea, but adding a fully customizable clock style would be awesome. Position, rotation, size and font could be some basic settings. An option to show the date would also be cool.

**Additional context**
![image](https://github.com/seerge/g-helper/assets/46955459/06992dcd-6267-4f4d-9fa2-ea036d248c54)

P.S.: One dumb extra detail comparing to AC, their clock shows padding zeros in the hours (01:49 rather than 1:49).

P.S.2: I have seen #706, but I believe this is more an extension rather than a duplicate of it.

**Comment by Secreto31126** [comment]
It's not working on my machine. The other animations do work, so I guess it's an issue with the clock.

**Comment by seerge** [comment]
@Secreto31126 what model do you have ? did clock work for you before ?

**Comment by Secreto31126** [comment]
ROG Zephyrus G14 GA401QM

Yes, the clock did work on v0.118

**Comment by seerge** [comment]
@Secreto31126 for older devices it could be much more problematic, as I don't have it to test

You can check this build 
[GHelper.zip](https://github.com/seerge/g-helper/files/12538159/GHelper.zip)

**Comment by Secreto31126** [comment]
That looks exactly like I want! Give me 5 and I try it out

**Comment by Secreto31126** [comment]
Tried to record a video, but it was too big for GitHub

It looks weird on my PC, the numbers are... Scary, to say the least

![VideoCapture_20230906-112419.jpg](https://github.com/seerge/g-helper/assets/46955459/23e0daf0-fea9-4abb-bf16-964bef0a2ed7)

**Comment by Secreto31126** [comment]
In half an hour I'm free so yeah, I would love to help

**Comment by seerge** [comment]
@Secreto31126 you can start with this build 
[GHelper.zip](https://github.com/seerge/g-helper/files/12539017/GHelper.zip)

Please set this static picture in it's default position
![icons8-data-grid-100](https://github.com/seerge/g-helper/assets/5920850/40254a2c-b220-4eda-8ef3-fc8976f859ce)

And post a picture of a result

And post your discord ID :) It will be better (faster) to continue there

**Comment by seerge** [comment]
@Secreto31126 it's not letting me message you directly, i have send a "friend request" in discord tho

Try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/12539221/GHelper.zip)

**Comment by seerge** [comment]
@Secreto31126 this is latest build from discord.

I will include changes in next release

Thanks for testing 

[GHelper.zip](https://github.com/seerge/g-helper/files/12540520/GHelper.zip)
