### ISSUE TITLE
GPU section not appearing in Fans and Power tab

### ISSUE THREAD

**Issue by ItzManan** [seerge/g-helper#1261]
Hey there
I have a 2022 G14 6700S. The GPU section in the Fans and Power section in not appearing even after switching to ultimate mode. I tried following the steps in issue#1190 but still couldn't get the menu. Also, I was watching a GHelper tutorial on youtube and the guy had sPPT and fPPT in the CPU tab. I don't know if these options have been removed in the latest versions of GHelper, so please provide an insight into the same. I have 0 Asus services running.
[log.txt](https://github.com/seerge/g-helper/files/12536340/log.txt)
<img width="827" alt="image" src="https://github.com/seerge/g-helper/assets/74382092/d1647b6a-4501-4acd-aef5-eaaa1a360c7f">

**Comment by seerge** [comment]
@ItzManan AMD gpus are completely locked, there’s not to tune there.

What you see in app is absolutely correct for your device

**Comment by ItzManan** [comment]
@seerge And what about the CPU power settings, sPPT and fPPT? Don't really know the technical terms.

**Comment by seerge** [comment]
@ItzManan it’s same, you have CPU power limit slider which does same for you
