### ISSUE TITLE
P/E core management

### ISSUE THREAD

**Issue by armyman2870** [seerge/g-helper#1263]
Armory Crate has a feature for Intel CPU's where E cores and P cores can be disabled/enabled, probably to save battery.

It'd be nice to have a feature in G-Helper where you can select and disable cores but also an Auto function where you can choose how many cores you would like to disable on battery and it'd save it. So when i unplug the charger it automatically disables selected cores. The option exists in the BIOS so i hope it'd be possible through G-helper as its a lot more convenient. 

I'm on a 2023 Zephyrus M16 with the latest updates and latest BIOS.

Thanks and Regards!

**Comment by armyman2870** [comment]
New BIOS version (310) came out, ill be updating it in a bit

**Comment by seerge** [comment]
@armyman2870 hello, I don't have M16 so can't really help here. 

But as I remember enabling / disabling cores require reboot anyway. And you can also enable/disable them via BIOS ? (F2 on boot)

**Comment by armyman2870** [comment]
Oh alright, thats fair. thanks for your time, i shouldve done my research before asking haha.
