### ISSUE TITLE
Asus G18 fans most of the time doesn't respond to manual fan curves 

### ISSUE THREAD

**Issue by blackace515** [seerge/g-helper#1275]
![Screenshot (8)](https://github.com/seerge/g-helper/assets/94751213/4fd8937d-bc1a-4874-8f45-38dec2712f32)
![Screenshot (8)](https://github.com/seerge/g-helper/assets/94751213/1421659e-eeaf-4f89-a3e4-c300f4ef649b)

**Describe the bug**
fans  not responding to custom manual  curve 

**Clear scenario to Reproduce**
1. Go to any graphically demanding app
2. gpu temp raises to 65 to 70 
3. fans ramp up to a very high speed despite low temps in the sixties 
4 - gpu and cpu fans ramp up to 4500 rpm ( which should be in the 3000s rpm according to manual curve ) 
 , sometimes just the gpu ramps up 

started the pc at 20 min mark 
rpm 0 for both gpu and cpu under 60 degrees
luanched a game at the 30 min mark , cpu and gpu fans ramps up to 4000 despite temperature of both the cpu and gpu at the 60s 
stopped the game at the 31 min mark
**App Logs**
9/8/2023 4:19:16 PM: BatteryLimit = 75 : OK
9/8/2023 4:20:00 PM: ------------
9/8/2023 4:20:00 PM: App launched: ROG Strix G814JZ_G814JZ :0.120.0.0en-US.
9/8/2023 4:20:00 PM: NVIDIA GeForce RTX 4080 Laptop GPU
9/8/2023 4:20:01 PM: CPU: -1 - 13th Gen Intel(R) Core(TM) i9-13980HX - Intel64 Family 6 Model 183 Stepping 1
9/8/2023 4:20:02 PM: AutoSetting for Online
9/8/2023 4:20:02 PM: Optimization service is running
9/8/2023 4:20:02 PM: Mode = 0 : OK
9/8/2023 4:20:02 PM: FanCPU = 1E-35-3B-3F-4A-4D-51-5A-00-00-03-07-1D-26-39-59 : OK
9/8/2023 4:20:02 PM: FanGPU = 1E-31-3A-40-44-49-53-5A-00-00-03-07-0C-13-35-5A : OK
9/8/2023 4:20:02 PM: FanMid = 1E-32-39-3D-48-4E-52-53-00-00-00-03-06-14-23-35 : OK
9/8/2023 4:20:02 PM: Eco flag : 0
9/8/2023 4:20:02 PM: Mux flag : 1
9/8/2023 4:20:02 PM: \\?\DISPLAY#BOE0B35#4&6a21f43&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
9/8/2023 4:20:02 PM: \\?\DISPLAY#BOE0B35#4&6a21f43&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
9/8/2023 4:20:02 PM: ScreenOverdrive = 0 : OK
9/8/2023 4:20:02 PM: BatteryLimit = 75 : OK
9/8/2023 4:20:02 PM: BatteryLimit = 75 : OK
9/8/2023 4:20:02 PM: USB-KB 0x19B6:5D-BD-01-08-00-00-00-FF
9/8/2023 4:20:02 PM: USB-KB 786HID-compliant vendor-defined device\\?\hid#vid_0b05&pid_19b6&col05#6&15ae9f2&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-02-00-80-80-F5-00-00-FF-FF-FF-00-00-00-00
9/8/2023 4:20:02 PM: Monitor Power On
9/8/2023 4:20:02 PM: Auto:5D-BA-C5-C4-00
9/8/2023 4:20:03 PM: PowerLimit A0 = 35 : OK
9/8/2023 4:20:03 PM: PowerLimit A3 = 35 : OK
9/8/2023 4:20:09 PM: Session:SessionUnlock
9/8/2023 4:20:09 PM: \\?\DISPLAY#BOE0B35#4&6a21f43&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
9/8/2023 4:20:09 PM: \\?\DISPLAY#BOE0B35#4&6a21f43&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
9/8/2023 4:20:09 PM: ScreenOverdrive = 0 : OK
9/8/2023 4:30:08 PM: Display configuration changed.
9/8/2023 4:30:34 PM: Latest version 0.120.0.0
9/8/2023 4:30:42 PM: GET GPU CLOCKS: 0, 0
9/8/2023 4:30:42 PM: GET CLOCK LIMIT: 0
9/8/2023 4:30:43 PM: FanCPU = 1E-35-3B-3F-4A-4D-51-5A-00-00-03-07-1D-26-39-59 : OK
9/8/2023 4:30:43 PM: FanGPU = 1E-31-3A-40-44-49-53-5A-00-00-03-07-0C-13-35-5A : OK
9/8/2023 4:30:43 PM: FanMid = 1E-32-39-3D-48-4E-52-53-00-00-00-03-06-14-23-35 : OK
9/8/2023 4:30:56 PM: FanCPU = 1E-35-3B-3F-4A-4D-51-5A-00-00-03-07-1D-26-39-59 : OK
9/8/2023 4:30:56 PM: FanGPU = 1E-31-3A-40-44-49-53-5A-00-00-03-07-0C-13-35-5A : OK
9/8/2023 4:30:56 PM: FanMid = 1E-32-39-3D-48-4E-52-53-00-00-00-03-06-14-23-35 : OK
9/8/2023 4:31:01 PM: FanCPU = 1E-35-3B-3F-4A-4D-51-5A-00-00-03-07-1D-26-39-59 : OK
9/8/2023 4:31:01 PM: FanGPU = 1E-31-3A-40-44-49-53-5A-00-00-03-07-0C-13-35-5A : OK
9/8/2023 4:31:01 PM: FanMid = 1E-32-39-3D-48-4E-52-53-00-00-00-03-06-14-23-35 : OK
9/8/2023 4:31:03 PM: Hibernate after 2147483647

![ramp](https://github.com/seerge/g-helper/assets/94751213/8aa376d8-f0be-48d5-91b1-da030feb7b1f)

**Desktop (please complete the following information):**
 - . Windows 11 home
 - Asus G18 Bios 318 

**Asus software**
- same problem with crate installed and uninstalled
- MyASUS installed
- same problem with Asus services stopped and runing

solutions tried 
- applying a custom curve through atrofac solves the problem 
-  I tried to update the bios from 317 to 318 hoping that it solves the problem but nothing changed

**Comment by seerge** [comment]
@blackace515 Y-axis on fan curve editor is indication only. Under the hood it's in % (you can click on it to see % well)

By default it assumes that max fan RPM is 5800RPM, but as soon as app will see your fans actually spinning faster - it will remember that and adjust axis next time you open it (i.e. recalibrate)

Atrofac / Armoury and G-Helper use exactly same **and the only one** endpoint to set fan curves. 

Just switch fan editor to % and re-create your fan curve from atrofac :) it will behave same.

**Comment by seerge** [comment]
@blackace515 for situation like yours, I have added a special "Calibrate" button to the Fans+Power, that will try to measure maximum RPM that custom fan curve allows, and adjust Y-axis accordingly

Check this build

[GHelper.zip](https://github.com/seerge/g-helper/files/12562452/GHelper.zip)

**Comment by seerge** [comment]
Published this in https://github.com/seerge/g-helper/releases/tag/v0.121
