### ISSUE TITLE
Only Total slider works on CPU but cant figure out CPU slider works for.

### ISSUE THREAD

**Issue by MuratDugan** [seerge/g-helper#128]
I have Rog Flow X13 GV301RE ryzen 7 6800hs 50W,  3050ti  40W

When I make slider CPU on 5W on and total 10W, CPU is turn 10W
total 35 CPU 5, CPU PPT is 35

slider of "Total" is working affect on CPU but CPU slider is nothing work on.

I have acpi on Volunteers Section on https://github.com/seerge/g-helper/issues/38#issuecomment-1468047558

Your program is perfect thanks for your time <3

![image](https://user-images.githubusercontent.com/111883464/227009333-507998ea-a4a5-4686-a787-c04108cf6e05.png)

**Comment by seerge** [comment]
@MuratDugan thanks for letting me know :) as you have probably seen in https://github.com/seerge/g-helper/issues/38#issuecomment-1468047558 every laptop seem to react differently to the sliders.

If you are feeling adventurous (and on your own risk!) you can do some testing as your acpi reports full package of endpoints

```
1200a0 : 0 (0) - current TOTAL slider in app
1200a1 : 0 (0)
1200a2 : 0 (0)
1200a3 : 0 (0)
1200b0 : 0 (0) - current CPU slider in app
1200b1 : 0 (0)
1200c0 : 0 (0)
1200c1 : 0 (0)
1200c2 : 0 (0)

```

And try to set some values to them (as I have explained in a topic), may be your will find values that affect total power in your case (then i can implement them in the app)

**Comment by seerge** [comment]
@MuratDugan what sliders do you have in armory btw ?

**Comment by MuratDugan** [comment]
CPU:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/111883464/227017519-7daba7b6-4803-46c6-844d-9caa03d30859.png">


GPU:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/111883464/227017581-ab074d20-85d3-4496-bee7-4463ab764c54.png">

**Comment by MuratDugan** [comment]
normally armoury crate and service disabled cause Im using ur program only and getting better fps on bf2042. On turbo with armoury crate bf2042 is 60-75 fps. with g-helper turbo and selfconfigured 40W cpu 35W gpu (gpu sometimes 30 cant edit lock on 75C ) 80-100 fps

**Comment by seerge** [comment]
If you are willing to discover endpoints (if they exist) that adjust GPU settings - that could be cool. Some people are also asking about it https://github.com/seerge/g-helper/issues/38 but since I don't have a device - i can't do much atm.

**Comment by MuratDugan** [comment]
I'm not advanced user I can only basics. I changed some values and saved and scan acpi again but output always same. (except fan values)

**Comment by seerge** [comment]
ok :) no problems. I have renamed Total PPT into Platform PPT in https://github.com/seerge/g-helper/releases/tag/v0.36 this is exactly as it's called in armory (at least on my model). I think it's more universal.

**Comment by MuratDugan** [comment]
nope I test 0.36 but sliders same.Anyway there is no problem here. best thing is on v0.28 (as i remember) 5W limit. My pc have 10 hour battery life. <3

**Comment by MuratDugan** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/111883464/227035586-f0fd3226-443c-447a-ba07-29e4cf49d3c7.png">

This is output of performance. I have 13.3" really tiny laptop with bf2042 low 1920x1200 100Fps (cause of small screen Im not bothered with graphics).
With armoury crate turbo or manual settings I was getting fps drops etc. Armoury crate is making only termal throttling. its working on 20W cpu on even turbo. and 75-77 C. "Performance mode" is giving same power and results too.
With this I able to make CPU 30-40W and 95C termal throttling. but it makes +30-40 fps.

**Comment by seerge** [comment]
That's great :) I wish more people would now about the app from reddit or so ...
