### ISSUE TITLE
Got new default fan curves after resetting

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#1280]
I always used default fan curves for power profiles. But unexpectedly, today, after hitting the Reset button, I got other curve forms.
I have no additional software, no curve experiments, etc.
Previously, "resets" gave another form. Could this be a result of fans calibration?

1. Open "Fans and Power" section.
2. Click on "Reset"
3. Got new default fan curve instead of default one(?).

**Expected behavior**
No curve changes because it should be already default.

**App Logs**
[log v121.txt](https://github.com/seerge/g-helper/files/12564033/log.v121.txt)

**Screenshots or screencasts**
Current Balanced:
![image](https://github.com/seerge/g-helper/assets/8934421/964511de-3a95-46d7-944e-ce7298b0dc76)

Current Turbo:
![image](https://github.com/seerge/g-helper/assets/8934421/07ab9111-fb0a-4141-adf2-6fe8f934068a)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ROG Zephyrus G15 GA503QR

**Asus software**
None.

**Comment by seerge** [comment]
@ke1ne that's actually correct :) like 10-15 versions before I have fixed one issue, where it would fail to read "default" curve from BIOS (and then it was defaulting to hardcoded G14 curve that i did for backup)

What you see is correct default curve reported by your BIOS (i'm sure it will be same in 0.120, 0.118, etc ..) :)

**Comment by ke1ne** [comment]
@seerge Ironically, but (just) MAYBE, that "wrong" curve worked better. =) Or not; will test more.
Thanks!

**Comment by seerge** [comment]
@ke1ne when you click "reset to defaults" (i.e. apply is not checked) it will use curve that was baked in bios. And now it shows it (at least that's how BIOS reports it)

It would use custom curve only if you click apply :)

**Comment by ke1ne** [comment]
@seerge Sure, I understand this. I meant that old default curve.
