### ISSUE TITLE
Force disable AMD Video Profile

### ISSUE THREAD

**Issue by yashgorana** [seerge/g-helper#1287]
**Is your feature request related to a problem? Please describe.**
There have been cases where AMD graphics driver makes videos appear washed out. This is triggered when playing DRM content like Netflix/Prime video; AMD driver kicks in and forces a color profile on the video that makes the video look awful. See 'Additional Context' below for some examples and complaints.

**Describe the solution you'd like**
Would it be possible to force disable the video profile like AMD VariBright in the 'Extra' options in G-Helper?

**Describe alternatives you've considered**
Disabling hardware acceleration _fixes_ it but it's not an ideal solution. AMD should be fixing this but 🤷‍♂️

**Additional context**
- The specific issue in action: https://www.reddit.com/r/ZephyrusG15/comments/xik1ht/videos_getting_washed_out_weirdly_fixes_on/ 
- https://www.reddit.com/r/ZephyrusG15/comments/12r2pve/weird_color_change_on_videos_when_scrolling_or/
- https://www.reddit.com/r/ZephyrusG15/comments/xa2bvb/web_videos_flickering_like_hell_zephyrus_g15/
- https://www.reddit.com/r/ZephyrusG14/comments/j4vjjw/washed_out_colours_when_playing_video/
- https://community.amd.com/t5/graphics/washed-out-video-when-hardware-acceleration-is-on/m-p/511785
- https://community.amd.com/t5/graphics/washed-out-videos-when-using-gpu-video-acceleration/td-p/365007

One way to confirm this is open AMD Radeon Software. Switch to "Video Profile", set a custom profile with -50% and play any DRM content :)

**Comment by seerge** [comment]
@yashgorana do you have any open source information on how to control that ? (as i don't)

Why don't you just disable this within Adrenaline software ? (i.e. set video profile to default)

**Comment by yashgorana** [comment]
Unfortunately, no I don't have that information. Default profile itself creates the issue :|

**Comment by seerge** [comment]
@yashgorana well, then there is a good chance it's not really possible.

What kind of AMD device do you have ? as on my G14 2022 with latest 23.9.1 driver everything looks absolutely fine.

Mb try to cleanup everything with https://www.amd.com/en/support/kb/faq/gpu-601 ?

**Comment by yashgorana** [comment]
Zephyrus G15 2021 with the 30.0.13002.1001 (05 Aug 2021):
![image](https://github.com/seerge/g-helper/assets/11070218/f43416b2-b941-4e24-9361-e7158cf2053e)

**Comment by seerge** [comment]
@yashgorana try to cleanup old driver and install latest official from AMD. Yours is literally ancient :)

**Comment by yashgorana** [comment]
Ah so this is the latest "official" version. Performed a cleanup, but DCH auto-installed the same version. I'll try to pull the latest official from AMD instead.

![image](https://github.com/seerge/g-helper/assets/11070218/33eee1d9-c561-493a-9c1f-d046346725aa)

**Comment by yashgorana** [comment]
Display driver cleanup + latest official driver-only installation fixes the issue =)
I'll close this issue

**Comment by yashgorana** [comment]
Thank you so much @seerge
