### ISSUE TITLE
Add user remap FN+F6 combo for real print screen key

### ISSUE THREAD

**Issue by jasonnovak** [seerge/g-helper#1288]
It appears Function+F6 snip button remaps to win+shift+s to open the built-in windows snipping tool.

I use a 3rd party tool the uses the print screen key, techsmith snagit

You already allow remapping fn+f4, so it would be nice to integrate f6 as well so I can map it to the regular print screen button and use the button labelled for screen shots

**Comment by seerge** [comment]
@jasonnovak hello, it's just a windows setting that you can change 

Check this duplicate topic for more info https://github.com/seerge/g-helper/issues/602

**Comment by jasonnovak** [comment]
I don't believe this is  the same question as the one referenced. 

I don't want to use either of Microsoft's built-in snipping tools, but a 3rd party app. I am already familiar with the accessibility / keyboard option, since I had to turn it off on my desktop PC recently when Microsoft enabled it by default, disabling my 3rd party app. However, on my desktop it's fine since I have a real Print screen key.

The issue is Fn-F6 doesn't simulate print screen key, from what I can see it simulates the windows key shortcut for the snipping tool. So it makes no difference if that setting is on or off, since there isn't a physical print screen button to use.

**Comment by seerge** [comment]
@jasonnovak what app does it tells keyboard to run whatever command is hardcoded for FN+F6. If it simulates snip-tool hotkey combination, then this is how things are on your device.

But you can try Sharpeys or Windows Power Toys to remap this hotkey-combination to whatever you need :)
