### ISSUE TITLE
GPU Activity Monitor

### ISSUE THREAD

**Issue by unrealJune** [seerge/g-helper#1295]
Add a GPU activity monitor to determine at a glance if the GPU is active. On older models without a GPU eco feature, being able to tell if the GPU is active (much like NVIDIA's GPU Activity indicator does) would be a good feature, since the NVIDIA one is janky at best.

**Solution**
Add section to RefreshSensor code block that checks for programs running on the GPU, and adds that text to the trayIcon text. Alternatively, change the trayIcon at runtime to indicate the activity (maybe turn the icon red?)

I'd be willing to work on this, but I'd like to garner feedback before starting.

**Comment by seerge** [comment]
@unrealJune I'm not a big fan of turning app into a monitoring tool as there is lots of good dedicated utilities for that :)

As far as I remember seeing what apps use GPU is actually perferctly handled by Nvidia Control panel (they even have a special system tray icon for that) ;)

**Comment by unrealJune** [comment]
That's fair! I had a few weird issues with the NVIDIA tray icon crashing, so I figured integration would be a neat workaround.

**Comment by unrealJune** [comment]
I only notice that behavior after using the "Stop GPU apps" in G-Helper, perhaps it would be worthwhile to whitelist this process. As it is, issue can be closed!

**Comment by seerge** [comment]
@unrealJune do you have process name? (i don't have laptop with nvdia atm) :)

**Comment by seerge** [comment]
Closing as abandoned
