### ISSUE TITLE
How can I make a mode the default one so that it is automatically selected at startup?

### ISSUE THREAD

**Issue by Paco-Rubio** [seerge/g-helper#1297]
As explained in the title, i want to set a default mode so that anytime I start the laptop, the selected mode is applied (in my case it would be silent)

**Comment by seerge** [comment]
@Paco-Rubio App already remembers last mode used, and sets it on start :)

**Comment by Paco-Rubio** [comment]
Wait, it's true, I had just tweaked some windows power plan setting and fans were going crazy at startup. Sorry
