### ISSUE TITLE
[Feature Request] Themes / Transparency / Glass effect skins

### ISSUE THREAD

**Issue by rez3vil** [seerge/g-helper#1302]
**Is your feature request related to a problem? Please describe.**
It's not a problem, but I would love to have a glass effect like those olden school Aero themes to the overall app.

**Describe the solution you'd like**
A small drop down button with skin options like Glass, Transparent, Android Material UI and others

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by seerge** [comment]
@rez3vil hello, current app is done using Winforms (to keep it light on memory and resources). I don't think that it's possible to change a theme of this controls so easily. 

So sorry, I won't be adding this for now ;)
