### ISSUE TITLE
fan speed direct selection

### ISSUE THREAD

**Issue by marcinion** [seerge/g-helper#1306]
Hi

Could you please consider to add to your amassing soft one option - direct selection of the fan speed ?
<img width="149" alt="Screenshot 2023-09-12 153142" src="https://github.com/seerge/g-helper/assets/144902392/f06d6a12-6eb4-49fc-be33-b1ff0f5bbcbe">

**Comment by seerge** [comment]
@marcinion hello, I didn't get your question.

You can already select any mode with appropriate fan curves in the app.

**Comment by seerge** [comment]
I have already answered you in other topic that you created https://github.com/seerge/g-helper/discussions/1305

Closing as duplicate
