### ISSUE TITLE
Muting Microsoft Teams also mute the microphone entirely and vice-versa

### ISSUE THREAD

**Issue by Kowken** [seerge/g-helper#1307]
**Describe the bug**
When I click on the m3 button to mute my mic it also mute it in Teams (contrary to Discord for instance) but muting teams also mutes my mic totally, meaning I cannot be mute in Teams while speaking in an other app.

**Clear scenario to Reproduce**
1. Launch Microsoft Teams
2. Click on M3 (both GHelper "Muted"and Teams mute icon activate)
3. Click again (both deactivate)

**Expected behavior**
I expected the mute button not to affect the Teams feature and vice versa

**App Logs**

Behaviour: Muted my mic in Teams and then unmuted it with GHelper. After that, muted my mic with GHelper and then unmuted it in Teams.

13/09/2023 12:46:50: Key: 124
13/09/2023 12:46:50: Microphone (HD Pro Webcam C920):True
13/09/2023 12:46:50: Microphone (HD Pro Webcam C920):True
13/09/2023 12:46:50: Microphone (HD Pro Webcam C920):True
13/09/2023 12:47:10: Hibernate after 2147483647
13/09/2023 12:47:30: Key: 124
13/09/2023 12:47:30: Microphone (HD Pro Webcam C920):True
13/09/2023 12:47:30: Microphone (HD Pro Webcam C920):True
13/09/2023 12:47:30: Microphone (HD Pro Webcam C920):True
13/09/2023 12:47:35: Key: 124
13/09/2023 12:47:35: Microphone (HD Pro Webcam C920):True
13/09/2023 12:47:35: Microphone (HD Pro Webcam C920):True
13/09/2023 12:47:35: Microphone (HD Pro Webcam C920):True
13/09/2023 12:47:47: Hibernate after 2147483647

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2 22621.2134
 - Laptop model: ASUS ROG STRIX SCAR 15 G533ZW-AS94

**Asus software**
No ASUS software installed except the drivers downloaded from GHelper update feature and MS Store GameVisual

GHelper version: 0.123

**Comment by seerge** [comment]
@Kowken so it actually works? :) It mutes mic everywhere ? 

Your request is literally opposite to this https://github.com/seerge/g-helper/issues/744 (where I have intentionally adjusted a function to mute all)

**Comment by Kowken** [comment]
> @Kowken so it actually works? :) It mutes mic everywhere ?
> 
> Your request is literally opposite to this #744 (where I have intentionally adjusted a function to mute all)

Okay I fixed it. Teams actually has a "sync" button enabled by default which happens to device muting and teams software muting. Disabling this feature fixes the issue (tested and confirmed).

**Comment by seerge** [comment]
@Kowken great!
