### ISSUE TITLE
[Feature request] X13 Flow 2023 FN buttons remap

### ISSUE THREAD

**Issue by anton2dan** [seerge/g-helper#1309]
Hello.

I have the X13 Flow 2023 and I find it a bit frustrating to have two Fn buttons for keyboard backlight (one for increasing it and one for decreasing it). My old Dell and Lenovo laptops had only one button that cycled the keyboard backlight settings. I don't think it is necessary to have two buttons for this as the backlight setting has only 3 states.

A possibility would be to remap all/specific Fn buttons and to set one of the keyboard backlight Fn buttons (F3 or F4) to cycle the backlight states.

Thank you.

**Comment by seerge** [comment]
@anton2dan hello, I'm afraid your request is very specific to your case. 

I'm not a big fan of changing behaviour of default hotkeys, as app can also work along with Asus Optimization Service (and that would create conflicts) or do FN-lock (that would create extra complications as well)

FN+F4 already cycles through backlight modes btw, while FN+F2/F3 change brightness.

**Comment by anton2dan** [comment]
@seerge 

FN+F4 cycles through backlight modes, but I was referring to have a button that cycles through keyboard brightness levels and to have the possibility to remap FN+F2/F3 maybe.

Also, most of the Asus laptops that are supported in g-helper have the same button configuration, not only the X13.

Seeing that g-helper already supports the extra buttons remapping, I thought I could ask :)

Anyway, if it's not possible, I understand.
And thank you for creating this great app.
