### ISSUE TITLE
Add an option to disable "overdrive" for 144+ mode

### ISSUE THREAD

**Issue by Hitrene** [seerge/g-helper#131]
Hi. Could you add option to disable OD panel mode for 144hz+ mode? Might be useful

**Comment by seerge** [comment]
Hello, out of curiosity - what is the scenario when you will need this ?

**Comment by Hitrene** [comment]
Well, I do not particularly need it (I am not a cybersport related), but I think it's nice to have, mb someone will find it useful. But you did a great job with this app, so if it cost you any significant time, so maybe it's not worth it

**Comment by Hitrene** [comment]
(Not-ticket related)

Buy the way, do you have PayPal or smth like that to send to you a donation?) You did a great job

**Comment by seerge** [comment]
> Well, I do not particularly need it (I am not a cybersport related), but I think it's nice to have, mb someone will find it useful. But you did a great job with this app, so if it cost you any significant time, so maybe it's not worth it

main reason i didn't add it - i wanted to keep ui as simple as possible (it's already too many buttons) . you don't see it - but there is also a 4th button for mini-led screens. I may add a 144 (120hz) and without overdrive for cases when there is NO miniled

**Comment by lucidnx** [comment]
Maybe it will be better to put all advanced or not regulary used buttons/sliders to sub-menu. This way app can be clean with just few buttons normally, but many settings behind the scenes :)

**Comment by Gear-dev-sudo** [comment]
Potentially OD will cause the panel to overload, which may harm the lifetime of the panel

**Comment by seerge** [comment]
Added a checkbox to disable overdrive under Extra in https://github.com/seerge/g-helper/releases/tag/v0.40
