### ISSUE TITLE
G14 2021 : Can't switch dGPU from standard to eco 

### ISSUE THREAD

**Issue by TEA-AIR-E** [seerge/g-helper#1311]
**The bug**
I'm not sure when this happened but I can no longer switch from standard to eco- I had it set to optimized previously.
I noticed my battery would drain incredibly fast on optimized, tried switching to eco, I would see "changing" but it would always revert to standard.

**to Reproduce**
1. Run G-Helper
2. Click on 'eco'
3. App would hang and then revert to standard.
4.  Also - Optimized, when running on battery, is showing the dGPU temperature/fan speed, which should mean the dGPU isn't off.
 
**Expected behavior**
Switch to eco when selected.
Turn dGPU off when optimized selected and not charging.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12605432/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/19786399/8a550cb4-c11f-4be9-95e9-ef9c9f64b881)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GA401QM_GA401QM

**Asus software**
- SystemControlInterfaceDriver V3.1.12.0 (for OSD)

**Comment by seerge** [comment]
@TEA-AIR-E hello, i see that app tries to set Eco but BIOS refuses to do so 

```
9/14/2023 2:16:17 AM: GPUEco = 1 : 0
```

I assume app would offer to restart gpu via device manager for you, did you try that?

If it doesn't help try to reboot device or do a [hardware reset](https://github.com/seerge/g-helper#how-do-i-do-a-hardware-reset-on-a-laptop) it may refresh things :)

**Comment by TEA-AIR-E** [comment]
@seerge I appreciate you checking into this.

I tried reinstalling myASUS/armory but not even armory could manage the dGPU.
I wanted to see if I needed some asus service to run to get the functionality back but myASUS was stunted w/ the error "Some functions cannot be used, please restart this application or the computer".

I suspect the issue arose post the BIOS update.
I ran Ghelper again, I saw I had an out-of-date nvidia driver. 
Installing the latest ASUS nvidia driver seemed to resolve everything. 
I hadn't realized but even my keyboard backlight wasn't working before, but with the new nvidia driver installation, it, along with OSD and dGPU functionalities, were restored.

Really weird! So at the end of the day I had to **update the nvidia drivers.**

**Comment by seerge** [comment]
@TEA-AIR-E great, I'm glad you have figured it out
