### ISSUE TITLE
The touchpad does not turn off using the keyboard shortcut.

### ISSUE THREAD

**Issue by geHorse** [seerge/g-helper#1313]
Hello. The touchpad does not turn off with the keyboard shortcut.

**Describe the bug**
When I press Fn+F10 on my ASUS FX505DT laptop, only "On" is triggered, but pressing it again does not turn off the touchpad.

**Clear scenario to Reproduce**
1. Press the Fn+F10 key combination (for FX505FT) simultaneously.
2. Press the Fn+F10 key combination (for FX505FT) at the same time.
3.  Etc...

**Expected behavior**
1. The touchpad will turn on.
2. The touchpad will turn off.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12621134/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - Laptop model: Asus FX505DT

**Asus software**
- Armoury Crate is off (latest version).
- MyASUS installed
- GHelper said everything was off (completed through it).

**Comment by seerge** [comment]
@geHorse hello, this was asked before https://github.com/seerge/g-helper/issues/738 (and couple of other similar issues)

Unfortunately I don't know how to toggle touchpad on TUF devices, as same approach as app runs for ROG doesn't work there :)

If it's critical for you - you can manually enable Ausus Optimization Service from Services app in windows (then it will handle hotkeys, including this one instead of G-Helper)

If you really want to experiment

You can run endpoint discovery script from https://github.com/seerge/g-helper/issues/38 for 2 separate situations - when touchpad is enabled and disabled (via asus optimisation). If one of endpoints will change - may be it will shed some light on how to set it :)

**Comment by geHorse** [comment]
> You can run endpoint discovery script from #38 for 2 separate situations - when touchpad is enabled and disabled (via asus optimisation). If one of endpoints will change - may be it will shed some light on how to set it :)
[test.zip](https://github.com/seerge/g-helper/files/12627427/test.zip)

**Comment by seerge** [comment]
@geHorse thanks, try to run following in powershell as admin and check if it affects TP status

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00100013, 1)
```

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00100013, 0)
```

**Comment by geHorse** [comment]
> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00100013, 1)
> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00100013, 0)

Hello. Checked your commands - none of them gave any result. 
I also noticed that your program responds to touchpad status. If it is turned off via Armory Crate, the program also displays the state of the touchpad. 
Perhaps the touchpad is not controlled by the bios, but by the drivers?

**Comment by seerge** [comment]
@geHorse g-helper reads touchpad status from windows :) so toast notification will show correct status.

I have no idea how Optimisation Service (or AC) controls it then. 

I have added a fallback method to disable touchpad via registry to the app (but it has no effect on my device). Try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/12641657/GHelper.zip)

**Comment by geHorse** [comment]
@seerge Hello, I checked your build and unfortunately there is no result. Everything continues to work the same way. 
Just in case, I have sent a request to ASUS support, which may help with this problem.

**Comment by seerge** [comment]
@geHorse i have added another alternative way to toggle touchpad by emitting CTRL+WIN+F24

It works for my device, let me know if it works on TUF
[GHelper.zip](https://github.com/seerge/g-helper/files/12642520/GHelper.zip)

**Comment by geHorse** [comment]
@seerge Wow! CTRL+WIN+F24 not works, but FN+F10 at your version works correctly.

**Comment by seerge** [comment]
Great
