### ISSUE TITLE
Unable to remap m4 - ROG Strix SCAR 17

### ISSUE THREAD

**Issue by TheBossMagnus** [seerge/g-helper#1314]
**Describe the bug**

My model has five M-keys, at default:
* M1= Volume up
* m2= Volume down
* m3 =mute mic
* m4 = Power mod
* m5 = Rog button

I want to create a music control with the keys m3 (pause),m4(back), and m5 (next).
I'm unable to remap the m4 key (see screen). Currently, it does the default function (Power mod).

**Expected behavior**

**App Logs**
15/09/2023 17:29:25: Key: 124 (m3)
15/09/2023 17:29:27: Key: 124
15/09/2023 17:29:31: Key: 174
15/09/2023 17:29:31: Mode = 1 : OK
15/09/2023 17:29:31: Power Mode ded574b5-45a0-4f42-8737-46345c09c238:OK
15/09/2023 17:29:32: Key: 174 (m4)
15/09/2023 17:29:32: Mode = 4 : OK
15/09/2023 17:29:32: FanCPU = 1E-40-44-47-50-54-58-5B-00-01-02-05-1D-28-2F-35 : OK
15/09/2023 17:29:32: FanGPU = 1E-40-44-48-50-54-58-59-00-01-01-06-0D-16-22-22 : OK
15/09/2023 17:29:32: Power Mode 00000000-0000-0000-0000-000000000000:OK
15/09/2023 17:29:32: Key: 174
15/09/2023 17:29:32: Mode = 0 : OK
15/09/2023 17:29:48: Key: 56 (m5)

**Screenshot**
![image](https://github.com/seerge/g-helper/assets/92474350/c76f9532-d24c-4e62-823e-d8689835daac)

**Desktop (please complete the following information):**
 - OS: Win 11 22H2
 - Laptop model: ROG Strix SCAR 17 (2023) G733PZ-LL025X

**Asus software**
- Services installed
- MyASUS not installed
- 0 Asus services running in background

**Comment by seerge** [comment]
@TheBossMagnus hello, this is fine (and it's a dublicate of https://github.com/seerge/g-helper/issues/1213 )

M4 does same (and emits same key code even) as Fn+F5 on Scar models. And since Fn+F5 needs to be reserved for mode toggling, I don't plan to make it editable :) 

So I don't plan to change it.

**Comment by TheBossMagnus** [comment]
what do you mean "needs to be reserved for mode toggling" because iirc on Armoury crate it was possible to remap it

**Comment by seerge** [comment]
@TheBossMagnus when you bind M4 via AC, does it also affect Fn+F5 action?

As they produce same keycode (you can literally open ``%appdata%\ghelper\log.txt`` and press M4 and Fn+F5, and see that's both identify itself in a same way

**Comment by TheBossMagnus** [comment]
> When you bind M4 via AC, does it also affect Fn+F5 action

I'll try, but it's going to mess with G-Helper?

**Comment by seerge** [comment]
@TheBossMagnus AC sets same settings as G-Helper does, but you can just try to do a bind :)

**Comment by TheBossMagnus** [comment]
Fn+f5 still works with f4 binded to something else (play/pause)

**Comment by seerge** [comment]
@TheBossMagnus oke, but then I don’t know in what way AC does that :)
