### ISSUE TITLE
Error on Idle close app

### ISSUE THREAD

**Issue by RaZer0k** [seerge/g-helper#1315]
I got a close with error in idle status
i got Flow x13 2022 with XGM 3070

![image](https://github.com/seerge/g-helper/assets/10209770/77f9360a-f739-4f23-83b6-609f89cc517d)

**Comment by seerge** [comment]
@RaZer0k hello, i see that this happened when you pressed M4/ROG key on keyboard (i.e. ones that toggles g-helper window), but window was not there.

Did you had app in any kind of energy saving more or so ? (i.e. mb windows does it's tricks here)

**Comment by RaZer0k** [comment]
None that i can remember... i was off from the computer like all the mornings

15-09-2023 08:42:13: Auto:5D-BA-C5-C4-02
15-09-2023 09:13:22: XGM Activated flag: 1
15-09-2023 09:13:22: XGM Activated flag: 1
15-09-2023 09:13:24: Latest version 0.123.0.0
15-09-2023 09:13:29: AMD Chipset ACPI\AMDI0010 1.2.0.119 vs 1.2.0.121 = -1
15-09-2023 09:13:29: AMD Chipset ACPI\AMDI0010 1.2.0.119 vs 1.2.0.121 = -1
15-09-2023 09:13:29: Realtek Audio HDAUDIO\FUNC_01&VEN_10EC&DEV_0294 6.0.9373.1 vs 6.0.9427.1 = -1
15-09-2023 09:13:29: Realtek Audio Driver HDAUDIO\FUNC_01&VEN_10EC&DEV_0294 6.0.9427.1 vs 6.0.9427.1 = 0
15-09-2023 09:13:29: NVIDIA Graphic Driver PCI\VEN_10DE&DEV_249D&SUBSYS_218B1043 31.0.15.3645 vs 31.0.15.3713 = -1
15-09-2023 09:13:29: AMD Graphics Driver PCI\VEN_1002&DEV_1681&SUBSYS_1D321043&REV_02 31.0.12028.2002 vs 31.0.21031.1005 = -1
15-09-2023 09:13:29: ASUS System Control Interface v3 ACPI\ASUS2018 3.1.18.0 vs 3.1.18.0 = 0
15-09-2023 09:13:29: Fingerprint Driver USB\VID_04F3&PID_0C6E 3.5.12201.11401 vs 3.5.12201.11401 = 0
15-09-2023 09:22:42: BatteryLimit = 75 : OK
15-09-2023 14:07:42: Key: 56
15-09-2023 14:07:42: System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at GHelper.Input.InputDispatcher.KeyProcess(String name) in D:\a\g-helper\g-helper\app\Input\InputDispatcher.cs:line 391
   at GHelper.Input.InputDispatcher.HandleEvent(Int32 EventID) in D:\a\g-helper\g-helper\app\Input\InputDispatcher.cs:line 508
   at GHelper.Input.KeyboardListener.<>c__DisplayClass1_0.<.ctor>b__0() in D:\a\g-helper\g-helper\app\Input\KeyboardListener.cs:line 48

**Comment by RaZer0k** [comment]
I only remember update .NET Core 8 RC1 yesterday

**Comment by seerge** [comment]
@RaZer0k oke, I have suppressed this exception in this build, so should be fine now

[GHelper.zip](https://github.com/seerge/g-helper/files/12623848/GHelper.zip)
