### ISSUE TITLE
Unable to control anime matrix on G14 GA401IU

### ISSUE THREAD

**Issue by Schreckgespenst** [seerge/g-helper#1316]
**Describe the bug**
Unable to control the Anime Matrix behavior through G-Helper despite removing armoury crate prior to the install. Can't turn it off or change brightness or change the animation type. The anime matrix has been stuck on a pulsating ROG logo animation since install. Did a hardware reset too but it didn't help either.

**Expected behavior**
I expected to control the behavior through the G-Helper Anime Matrix menu.

**App Logs**
Attached log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/12640290/log.txt)

**Screenshots or screencasts**
![Screenshot 2023-09-16 144807](https://github.com/seerge/g-helper/assets/51400556/e2901cdd-750b-4bbf-8a4a-33f4a870f48d)
![WhatsApp Image 2023-09-16 at 14 50 05](https://github.com/seerge/g-helper/assets/51400556/bdb7b3ea-217d-4dc5-a37f-94ee3480a079)

**Desktop (please complete the following information):**
 - Windows 10
Version	22H2
OS build	19045.3448
Experience	Windows Feature Experience Pack 1000.19044.1000.0

 - Laptop model
 G14 GA401IU

**Asus software**
- Armoury Crate uninstalled
- MyASUS installed
- Other Asus services running in background

**Comment by seerge** [comment]
@Schreckgespenst hello, in a log i see that you were first setting your own picture and then turned matrix off (app sends corresponding commands to matrix)

```
16-09-2023 2.26.27 PM: Matrix C:\Users\gupta\OneDrive\Pictures\Screenshot (118).jpg
16-09-2023 2.27.55 PM: Matrix Off
```

If it doesn't react on that, are you sure that you don't have leftowers from AC running ? Check for ``Lightning Service`` under windows Services.

**Comment by Schreckgespenst** [comment]
You are right, I had Lightning Service running in the background. Stopping it gave the app control over Anime Matrix. It works as intended now. Thank you!
