### ISSUE TITLE
Backlit doesn't turn on during battery mode

### ISSUE THREAD

**Issue by SyedAffnan** [seerge/g-helper#1318]
On version 0.123.0 my asus tuf f15(2022) doesn't turn on when it runs on battery mode

**Comment by seerge** [comment]
@SyedAffnan hello, what do you mean under "doesn't turn" ? Can you control backlight with Fn+F2/F3 or slider under extra? Post a log.

**Comment by SyedAffnan** [comment]
> @SyedAffnan hello, what do you mean under "doesn't turn om" ? Can you control backlight with Fn+F2/F3 or slider under extra? Post a log.

When it goes to battery mode backlit turns off not able to turn on and tried fn+f2/f3 to adjust the brightness but doesn't respond but on power it works fine

**Comment by seerge** [comment]
@SyedAffnan given that you have ignored initial (in issue template) request to provide log and my second question I can't help here anyhow and closing this.

**Comment by SyedAffnan** [comment]
> @SyedAffnan given that you have ignored initial (in issue template) request to provide log and my second question I can't help here anyhow and closing this.

[log.txt](https://github.com/seerge/g-helper/files/12642790/log.txt)

**Comment by seerge** [comment]
@SyedAffnan app saves 2 separate brightness levels for battery / plugged states.

I see that for battery, it's explicitly set to be OFF

```
9/17/2023 5:40:44 PM: TUF Brightness = 128 : OK
```

You need to set it to ON via hotkey or brightness slider under Extra

Do FN+F2/F3 hotkeys work for you only when it's plugged ? or they don't work at all ? as i don't see any signs of you pressing the buttons in the log in a first place (they should appear as ``WMI event 196`` , ``WMI event 197``

I also don't see any signs that you were dragging slider under Extra when laptop was on battery

**Comment by SyedAffnan** [comment]
> @SyedAffnan app saves 2 separate brightness levels for battery / plugged states.
> 
> I see that for battery, it's explicitly set to be OFF
> 
> ```
> 9/17/2023 5:40:44 PM: TUF Brightness = 128 : OK
> ```
> 
> You need to set it to ON via hotkey or brightness slider under Extra
> 
> Do FN+F2/F3 hotkeys work for you only when it's plugged ? or they don't work at all ? as i don't see any signs of you pressing the buttons in the log in a first place (they should appear as `WMI event 196` , `WMI event 197`
> 
> I also don't see any signs that you were dragging slider under Extra when laptop was on battery

Ok I forgot 😅 the app saves 2 separate brightness for battery and plugged status thanks for reminding me
