### ISSUE TITLE
BUG: Unplugging the poweradapter switches off multizone dimming and inverts the settings

### ISSUE THREAD

**Issue by KSodR** [seerge/g-helper#1319]
When using G-helper on a Asus M16 2023 with Mini-led the program "inverts" the Multizone button when unplugged.

**Steps to reproduce the behavior:**
1. Set Laptop Screen to Auto and multizone while plugged in with the ac-adapter
2. Unplug the power-adapter
3. The screen now switches to 60hz
4. Multizone will now turn off but will show in g-helper as on
5. Turning off multizone dimming in g-helper now instead turns it on.

**Expected behavior**
Expected behavior would be that Mini-led dimming settings would be kept when unplugged as well as turning it on should not turn it off and vice versa.

**App Logs**
See included log if needed.

**Desktop (please complete the following information):**
 - OS: WIn11
 - Asus M16 2023 RTX4080
 
**Asus software**
- No Asus software installed
[log.txt](https://github.com/seerge/g-helper/files/12640769/log.txt)

**Comment by KSodR** [comment]
After playing around with this it has to do with the windows HDR-settings. However now the multizone button is permanently reversed. The button only works if HDR is disabled.

**Comment by seerge** [comment]
@KSodR hello.

Miniled switch is indeed works only when HDR is disabled :) (so when it's ON, miniled is always on). This is how Windows/BIOS switch for multizone work

Even now app gets a status for miniled button by reading it's status from BIOS as well. So it shows, what system tells it.

I have made a small tweak here, let me know if it makes a difference 

[GHelper.dll.zip](https://github.com/seerge/g-helper/files/12641460/GHelper.dll.zip)

**Comment by Sontarr** [comment]
> Even now app gets a status for miniled button by reading it's status from BIOS as well. So it shows, what system tells it.

But how often does it check that?

How HDR/Multizone behaves if plugged in:
- Win+Alt+B switches to HDR/Multizone
- Win+Alt+B again switches HDR off and switches _back to the mode selected before_, be it Multizone or Singlezone!

I work on the desktop with Singlezone on and switch HDR/Multizone on for gaming. After that I switch back to Singlezone with Win+Alt+B. Which mode GHelper shows seems to purely depend on what was selected when the program was started. 

Now, if you unplug the Laptop with HDR/Multizone on, it also switches back to the last selected mode! Always Singlezone in my case. No change of the button in GHelper.

If HDR/Multizone is on, clicking on the Multi-Zone-Button in GHelper does nothing (as it should), but it switches the button itself on and off (which it shouldn't do - "Multi-Zone" should stay on). 

Does GHelper check the BIOS state after clicking the button? 
Does GHelper check the BIOS state after plugging/unplugging?

Armoury Crate just disables the Multi-Zone-Button when HDR ist on. 

Is there any way for you to check the HDR state?
Or to fetch when Win+Alt+B is pressed? 

Not sure what the version from two days ago should change.... I see the same behavior as before.

Thanks for your great work with GHelper, Seerge!

**Comment by seerge** [comment]
@Sontarr hello,

App checks for a Multizone status in pretty much all situations that you have listed : 
- every time g-helper window is being shown
- every time power status is changed
- every time you change screen setting via app (i.e. change refresh  rate or click multizone button) 

I also suggest to check build that I have posted here (as it will check for multizone status also a moment prior to button click)

If you change something in windows, and even after hiding / showing g-helper window it still shows incorrect status, it's probably BIOS reporting it wrong :) 

Just in case you can query current multizone status by yourself via powershell as admin
```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DSTS(0x0005001e)
```

**Comment by Sontarr** [comment]
Thanks for the quick reply. The new version doesn't change anything. The result of the PowerShell command also doesn't change. If I switch from Singlezone to HDR/Multizone and back to Singlezone with Win+Alt+B, the result always reads as:

PS C:\Windows\system32> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DSTS(0x0005001e)


__GENUS          : 2
__CLASS          : __PARAMETERS
__SUPERCLASS     :
__DYNASTY        : __PARAMETERS
__RELPATH        :
__PROPERTY_COUNT : 1
__DERIVATION     : {}
__SERVER         :
__NAMESPACE      :
__PATH           :
device_status    : 65536
PSComputerName   :

**Comment by Sontarr** [comment]
I tested a bit more and I can't get the reversed behavior KSodR was reporting.

1. Laptop unplugged/Singlezone with GHelper showing Singlezone
2. I plug the Laptop in and it switches to HDR/Multizone. GHelper still showing Singlezone.
3. I click the button in GHelper and it now shows Multizone, without actually changing anything visually. But it changes the result of your PowerShell command!
4. I unplug the laptop. The screen doesn't go back to Singlezone, but to Multizone!

So maybe the BIOS is not wrong, but that's how the BIOS is supposed to work, to remember the state you are coming from if you switch HDR off.

I assume there is no way for you to check the HDR state, to report "Multi-Zone/HDR" whenever that is on?

**Comment by seerge** [comment]
@Sontarr ```device_status : 65536``` should change to 6553**7** when Miniled is turned ON (via g-helper) :)

**Comment by Sontarr** [comment]
@seerge Yeah, I figured that much. I also figured that the PowerShell result does indeed change if you press the button in GHelper with HDR on. It doesn't change the display output, with is HDR/Multizone, but it _does_ change to which mode the display goes back if you turn HDR off eventually. 

The BIOS state is not wrong, it just serves another purpose as we thought: If HDR is on, it remembers the state to go back when you switch HDR off. That is actually useful: It allows to switch between Singlezone and Multizone/HDR with a single command. 

So it would be ideal if GHelper could detect if HDR is on and perhaps disable the button and show "Multi-Zone/HDR". Showing the BIOS state when HDR is on is not useful.

**Comment by seerge** [comment]
@Sontarr I have added a HDR detection, that will render mini-led button disabled when HDR is on.

It runs checks at the same time it checks for mini-led flag itself (i.e. when window is being shown, power status changed, etc). 

Let me know if this build works for you
[GHelper.zip](https://github.com/seerge/g-helper/files/12647081/GHelper.zip)

**Comment by Sontarr** [comment]
@seerge 

- With the latest build the button is always deactivated. Doesn't matter if plugged in or not, if HDR is on or not. Can't test what happens if I switch between Single-Zone and Multi-Zone, because I don't have Armoury Crate installed anymore.
- The difference between the enabled and the disabled button is quite small. Button looks the same and the text is dark grey instead of black. Perhaps change the text to "HDR" or the color to light grey?
- If the checks run at the same time, what happens if I switch to HDR with Win+Alt+B? It wouldn't be triggered, right?

**Comment by seerge** [comment]
@Sontarr check happens in situation I listed above. 

If it's always deactivated even when HDR is off in your system, it looks like approach to detect HDR is not working. 
I'm not able to provide any other solution then as I don't have internal HDR display to test even.

**Comment by seerge** [comment]
@Sontarr I have managed to find alternative way to detect HDR, let me know if this version works for you : 

[GHelper.zip](https://github.com/seerge/g-helper/files/12651849/GHelper.zip)

**Comment by Sontarr** [comment]
@seerge Yes! It works beautifully! 

One edge case: If I switch HDR on or off while the G-Helper window is open it doesn't recognize that. You talked in an [earlier post](https://github.com/seerge/g-helper/issues/1319#issuecomment-1723012166) about checking the status right before the button click. Maybe thats a way to solve this without needing to check the HDR status all the time?

Personal preference: Right now there may be a red line around the button when HDR is on, depending on if Multi-Zone was on or off before switching to HDR. I would love it to be more visually clear that HDR is on. 

Thank you again for your great work!

**Comment by seerge** [comment]
@Sontarr good to know

As for detecting HDR toggle in realtime it's a bit more tricky, as I don't think that app gets any notifications about that from windows (check app log, if "display configuration event" is triggered by HDR toggle or not)

This build should keep Red border around Multi-Zone button always when HDR is on (despite button being disabled) for clarity
[GHelper.zip](https://github.com/seerge/g-helper/files/12652510/GHelper.zip)

**Comment by Sontarr** [comment]
@seerge Red border in the newest build works fine.

In the app log, I get a
`19.09.2023 09:49:59: Display configuration changed`
whenever I switch with Win+Alt+B, even if the G-Helper window is open.

But no further lines!

When I open the window and HDR is on:
`19.09.2023 09:52:30: Key: 56
19.09.2023 09:52:30: NE160QDM-NM4 HDR: True`

When HDR is off and I switch modes in the app:
`19.09.2023 09:54:13: \\?\DISPLAY#BOE0B74#4&3813296b&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
19.09.2023 09:54:13: \\?\DISPLAY#BOE0B74#4&3813296b&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
19.09.2023 09:54:13: Miniled = 1 : OK
19.09.2023 09:54:13: NE160QDM-NM4 HDR: False
19.09.2023 09:54:14: \\?\DISPLAY#BOE0B74#4&3813296b&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
19.09.2023 09:54:14: \\?\DISPLAY#BOE0B74#4&3813296b&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
19.09.2023 09:54:14: Miniled = 0 : OK
19.09.2023 09:54:14: NE160QDM-NM4 HDR: False`

If you need more info or a complete log file, please let me know.

**Comment by seerge** [comment]
@Sontarr this build should update status on display configuration changed event as well

[GHelper.zip](https://github.com/seerge/g-helper/files/12658962/GHelper.zip)

**Comment by Sontarr** [comment]
@seerge works like a charm!

**Comment by seerge** [comment]
@Sontarr 

Ok, I consider it completed then

As it looks like @KSodR  has disappeared. And I have added an extra check-up with bios before toggling multi-zone status. That's maximum I can do to prevent inverted actions.

I will include changes in next release
