### ISSUE TITLE
[Bug] v0.37 - All program actions work much slower and CPU/GPU temps are higher (+5-10degs)

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#132]
**Describe the bug**
Just as described in the title. Got new version and restarted it. Laptop restart didn't help too.
No "overloaded" processes in task manager, etc.
v0.36 is OK.

**To Reproduce**
1. Install the new version v0.37
2. Run it.

**Desktop (please complete the following information):**
G15 2021, Win 11 22H2

**Comment by seerge** [comment]
@ke1ne i don't know even what to say :) in 0.37 i only tweaked auto-update checker ... could it be cause of updated drivers / any other things (like AMD released new drivers yesterday evening)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11052872/GHelper.zip)
@ke1ne Can you try this one? I have literally restored old "update" checker .. even tho it's not related

**Comment by ke1ne** [comment]
With 0.38, it seems to be ok now. Have no idea what was wrong. Thanks!

**Comment by seerge** [comment]
Closing as it seem to be resolved :)
