### ISSUE TITLE
Self auto-updater

### ISSUE THREAD

**Issue by musm** [seerge/g-helper#1320]
**Describe the solution you'd like**
Auto-download  and update g-helper instead of requiring manual download and overwrite of existing installation.

**Additional context**
related: https://github.com/seerge/g-helper/issues/23

**Comment by seerge** [comment]
@musm hello. This is already done, for every Final Release app would offer you to update (on start / main window open) . That update is completely automatic, replaces old exe with new one and starts it ;)

**Comment by Scarlaid** [comment]
should add an option for pre-release update too

**Comment by ke1ne** [comment]
> should add an option for pre-release update too

@seerge Hi, I would vote for some "get pre-release updates" checkbox too. But with no critical rush, etc. Thanks

**Comment by seerge** [comment]
I'm intentionally keeping pre-releases away from update, cause I don't want to push them to everyone ;)
