### ISSUE TITLE
Link the GPU & CPU fan speed like default fan curve?

### ISSUE THREAD

**Issue by tanyiok1234** [seerge/g-helper#1322]
I noticed that the beviour between the default curve and customized fan curve are different:

The default curve seems like having some kind of cooperation between cpu and gpu fan. When CPU get hot, even if the gpu is not hot, the gpu fan speed still increase to the level of CPU fan speed. This totally make sense as the heat pipe are connected so it do helps the cooling.

Interestingly, the custom fan curve cannot do this, not only the g-helper but also almost all fan curve adjustment tools as far as I know. This sometimes can be annoying: some workload may leads to fan speed like 5000rpm/2500rpm, which are way more noisy, but the cooling may not be better than 4000rpm/4000rpm. 

Also, the factory setting sometime is not satisfactory to me, the turbo is too noisy at idle, the slient mode is not good at dealing with short period of heavy loads. The performance mode is neither slient nor high performance.

So I am wondering if it is technically possible to link the fan speed like the default setting ... if it is, then I personally believe it is something great to have.

**Comment by IceStormNG** [comment]
Sadly, this is not possible. GHelper does the same as what AC does when setting the fan curve. And manual mode in AC behaves the same way.
The predefined curve mostly work on heatsink temperature as it seems, which can a) not be read out and b) cannot be defined as a control source for custom fan curves.

The fan curve itself is just sent to the firmware and the EC does all the fan control. To get what you want, you would have to ask ASUS to add that to the firmware (good luck with that, they "cannot" even fix their longstanding firmware bugs).

**Comment by tanyiok1234** [comment]
> Sadly, this is not possible. GHelper does the same as what AC does when setting the fan curve. And manual mode in AC behaves the same way.
> 
> The predefined curve mostly work on heatsink temperature as it seems, which can a) not be read out and b) cannot be defined as a control source for custom fan curves.
> 
> 
> 
> The fan curve itself is just sent to the firmware and the EC does all the fan control. To get what you want, you would have to ask ASUS to add that to the firmware (good luck with that, they "cannot" even fix their longstanding firmware bugs).

Thx for you answer，this explain why it happens. 

Btw, would it be possible if we change the curve dynamically according to the CPU/GPU temperature/fan speed?
It may sounds a little bit hacky, but since we have both the sensor for temperature and fan speed, it sounds pretty practical.

For example, we define both the GPU/CPU reference curve: for every second, if CPU fan curve follow the refence curve, but GPU fan is slower than CPU, then the GPU curve is compensated to CPU fan speed by adjusting the GPU fan curve until the speed becomes the same at current GPU temperature. And similar for the GPU.
By doing so we may have the same function, but with full control of it.

What I don't know is that if this could lead to some unknown bugs, since the curve is designed to be updated once, not every time.

How do you think about this idea?

**Comment by seerge** [comment]
@tanyiok1234 hello, I don't plan to add anything like that.

Every mode treats custom fan curves differently. It will cause 100 times more problems for users.

Thanks
