### ISSUE TITLE
Toggle to make the right Fn key into Win key

### ISSUE THREAD

**Issue by NIGHTFURY2111** [seerge/g-helper#1324]
**Is your feature request related to a problem? Please describe.**
It is  very frustrating when you have to access some shortcut that requires you to hold the win key along with any key on the right side of the keyboard

**Describe the solution you'd like**
A shortcut to toggle the right fn key into the Win key

**Describe alternatives you've considered**
You can also consider a straight-up toggle in the app instead

**Additional context**
This can save you from using two hands for a shortcut that should have been easily accessible with one hand

**Comment by NIGHTFURY2111** [comment]
Now that I'm reading this out loud, I realize that it might not be possible to differentiate the left or right function keys from each other thus making this impossible :(

**Comment by seerge** [comment]
@NIGHTFURY2111 hello, fn key doesn’t generate any keycodes by itself. It’s impossible to bind it to anything.
