### ISSUE TITLE
Silent mode when unplugged

### ISSUE THREAD

**Issue by Magniflex99** [seerge/g-helper#1326]
Currently, when G-Helper is running, and the Notebook is disconnected from the power supply, the profile is automatically set to "balanced" mode, however, it would be much more convenient if "silent" mode is preferred instead. given that its main objective is to lower hardware consumption, and consequently, it would save something in terms of autonomy, since with high-performance Notebooks, it is always inconvenient to be able to afford high loads, on the move. Perhaps even more useful would be a customizable setting, with which you can set the profile you prefer by default, based on the power status. I hope I have been clear enough, and that it is not a problem with the configuration I currently work with: Asus Rog G532LWS 
Windows 11 Home Edition (latest stable build) 
All drivers updated

**Comment by seerge** [comment]
@Magniflex99 hello,

App already remembers and automatically sets last mode used when unplugged and plugged in :) Just set Silent once on battery, and it will set it automatically next time you unplug.
