### ISSUE TITLE
Isolated illumination of the function keys 

### ISSUE THREAD

**Issue by Magniflex99** [seerge/g-helper#1329]
As happens, for example, in MSI and Lenovo notebooks, equipped with RGB keyboards, it would be very useful if it were possible to illuminate the function keys red, interrupting the rest of the backlighting, or turning on an isolated backlighting only on those keys, by holding down the key “Fn.” So as to better highlight all the "special" keys. I hope I have explained myself.

https://youtu.be/tv9ifmgL9Cg
At minute 7:41, you can observe the isolation of the illumination on the function keys, when they are called.

**Comment by seerge** [comment]
@Magniflex99 hello :)

That can be a good idea, but main trouble is that it won't work on majority of ASUS devices as they simply don't support per-key backlight controls (only Strix models do, and not all of them even)

And main thing - FN key when pressed by itself, doesn't trigger any keycode, so it's not possible to detect when it's pressed (only when a combination FN+something is)

So sorry, but that's not possible on this hardware.
