### ISSUE TITLE
[Bug] v0.35-0.36 - No GPU temperature shown. Shows at start and then disappears

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#133]
**Describe the bug**
At app startup, GPU temperature appears near the fans value, but disappears after 1-2 seconds. Also empty in the tray tooltip.

**To Reproduce**
1. Run the GHelper.
2. Click on icon to show the main window.
3. Hover the icon to show the tooltip.

**Expected behavior**
CPU and GPU temps appearing both.

**Screenshots**
![image](https://user-images.githubusercontent.com/8934421/227222058-9df01492-2047-4195-ba0f-1e77599893ad.png)
![image](https://user-images.githubusercontent.com/8934421/227222182-7c57931c-fac5-47ec-b9ae-54b183117f96.png)

**Desktop (please complete the following information):**
 - G15 2021
 - Win 11 22H2

**Comment by seerge** [comment]
Hmm, i didn't really change anything specific to this area in 0.37 :) 

@ke1ne  - can you try [GHelper.zip](https://github.com/seerge/g-helper/files/11051693/GHelper.zip) ?

Also after that can you open log at %AppData%\GHelper and see if there is any errors there ?

**Comment by ke1ne** [comment]
Got this using Standard and Optimized modes both:
```
23.03.2023 17:40:36: Failed reading GPU temp
23.03.2023 17:40:36: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_GPU_NOT_POWERED
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at GHelper.Gpu.NvidiaGpuTemperatureProvider.GetCurrentTemperature()
   at HardwareMonitor.ReadSensors()
```

**Comment by seerge** [comment]
Ok, and the temperature is still not showing ?

**Comment by ke1ne** [comment]
The same error in the latest 0.38:
```
23.03.2023 18:02:03: Failed reading GPU temp
23.03.2023 18:02:03: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_GPU_NOT_POWERED
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at GHelper.Gpu.NvidiaGpuTemperatureProvider.GetCurrentTemperature()
   at HardwareMonitor.ReadSensors()
```

**Comment by seerge** [comment]
Ok, it's strange, but what it says - that it simply can't read temp from a driver. Did you update / change drivers recently ? Could it be related to your other topic with temps ?

**Comment by ke1ne** [comment]
After reboot, the result is the same: the temp shows at start but disappears then.

**Comment by seerge** [comment]
@ke1ne ok, can you try older versions like 0.32 or so, does it work there for you now?

**Comment by seerge** [comment]
Ok, but that rather shows that problem is not with the version of the app … :) mb try to refresh gpu drivers? do other gpu monitoring apps like libre hardware monitor show temps?

**Comment by ke1ne** [comment]
HWINFO & LibreHardwareMonitor are showing all temps. All drivers are fresh.

**Comment by seerge** [comment]
Well, i don't know how to help you tbh :) as this is definitely something that was changed in the app (as old builds work same) :|

**Comment by seerge** [comment]
Just googled for your error and got this https://github.com/Rem0o/FanControl.Releases/issues/30 they say it could be that dGPU is in low power mode in windows (and therefore not used). I think it's a setting in a windows power plan.

**Comment by ke1ne** [comment]
Yeah, Nvidia GPU is kind of turned off automatically when not being used. Have no idea how it worked previously.
Maybe, it will be safer to add some check in code to avoid unnecessary temperature request when it's "disabled" anyway.
Thank you!

**Comment by seerge** [comment]
So if you wake up GPU does g-helper (if started again) show readings? 

What you see in a log is actually a message from a nvidia reading library, saying that GPU is sleeping (NVAPI_GPU_NOT_POWERED). So that is the check :) Reason why it goes to log - is to be able to investigate cases like yours of course.

By the way, from what i remember HWinfo deliberately wakes up GPU to get readings (that's what I definitely don't want to do in my app)

**Comment by ke1ne** [comment]
Hey, I had to test it from the beginning!
Yes, when GPU is in use, GHelper shows its temperature:
![image](https://user-images.githubusercontent.com/8934421/227336645-aa9caed1-9802-434a-b5ee-d6e17d548078.png)
