### ISSUE TITLE
uninstall?

### ISSUE THREAD

**Issue by matteomontipo** [seerge/g-helper#1331]
I installed this tool because I thought Armory Crate was the cause of keyboard random weird behaviors, like delay with keys and then repeated key on loop, but I saw even with ghelper it does the same thing.

So in your documentation it mentions to use the official AC uninstall tool to uninstall ghelper, I've done it but both ghelper folder and icon are still there, and it opens normally.

Should I first delete its folder and then run the AC uninstall again? does that suffice? or like it happens for AC I'll have ghelper traces around like unused registry etc?

thank you

**Comment by seerge** [comment]
@matteomontipo hello, I don't say anywhere that you need to use AC tool to uninstall g-helper.

G-Helper can be just deleted, that's it.

I suggest you to check readme 
https://github.com/seerge/g-helper#how-do-i-uninstall-g-helper
