### ISSUE TITLE
Keyboard Backlight on Startup/Restart and GPU Standard Mode

### ISSUE THREAD

**Issue by Gebirgskuchen89** [seerge/g-helper#1333]
Hello,

I'm using G-helper in my 2023 Asus G14 (uninstalled all Asus Software and deactivated all Asus Services, except the Asus Optimisation Service)

Problem 1:
When I start or I restart my Laptop, the keyboard backlight turns on, until I'm logged into Windows.
Is there any way to completely deactivate the keyboard backlight, also for boot on/restart?

Problem 2:
When I choose Eco Mode for my GPU, it always switches ack to Standard Mode after I restart or shut down/Turn on my Laptop.
The Optimised Mode however stays on even after restarting the Laptop, but the Eco Mode only stays until I restart the Laptop.

Is there a workaorund/fix for thisdo I have to set specific settings in the nVidia Control Panel?

 - OS: Windows 11
 - Laptop model: Asus G14 2023 (RTX 4090)

Thanks in advance!👍

**Comment by NJinsei** [comment]
My Flow X16 2022 also has the same issue that is described in problem 1, even though I have the option for backlight on boot in extras toggled off.

**Comment by Gebirgskuchen89** [comment]
Yes, I also toggled this option Off in Ghelper, BUT this programm only ist active after logging into Windows. So No Wonder that it doesnt have any effect.

**Comment by seerge** [comment]
@Gebirgskuchen89 hello, 

1. If you have Asus Optimization Service starting - i think it's the one responsible for turning backlight on. Try to disable it.
2. If Eco mode refuses to turn on it means BIOS refuses to turn off dGPU and it's used by something

- Make sure that you have "Enable GPU on shutdown" checked in Extras as explained in https://github.com/seerge/g-helper/discussions/1042
- Next to that try to do a [hardware reset](https://github.com/seerge/g-helper#how-do-i-do-a-hardware-reset-on-a-laptop), it can help if dGPU is stuck by some reason

P.S. Sometimes it could be driver-related, you can check a similar issue where user has fixed that by reinstalling drivers https://github.com/seerge/g-helper/issues/1311

**Comment by seerge** [comment]
@Gebirgskuchen89 

1. Since you didn't provide a log, I don't know what exactly is happening. But when launched app would set same backlight level as it remembers last. So if it was OFF prior to shutting down, as soon as app starts it will set backlight to OFF. What happens before (i.e. while windows is booting) is out of control of the app obviously

2. This is exactly that that checkbox does. It sets dGPU ON on shutdown, to prevent some possible misbehaviour in future (explained in the topic I linked). You can uncheck it - and then app won't touch dGPU on shutdown.

**Comment by Gebirgskuchen89** [comment]
1) "What happens before (i.e. while windows is booting) is out of control of the app obviously". 

This is weird!
When I check the "awake" box under extras-keyboard backlight, no matterwhich level of light I set it to... 
![Pic 1](https://github.com/seerge/g-helper/assets/145532057/b5e5fe37-0f39-4ad2-9910-5ea443ac98d1)

...the keyboard backlight turns on, when I restart the Laptop.
![Pic 2](https://github.com/seerge/g-helper/assets/145532057/61f52239-9237-45cf-bab0-baf20eddbf5a)

When I uncheck the the "awake" box under extras-keyboard backlight...
![Pic 3](https://github.com/seerge/g-helper/assets/145532057/f7744d2c-702c-41a4-ae2f-35b06525a66a)

... they keyboard stays off when restarting.
![Pic 4](https://github.com/seerge/g-helper/assets/145532057/9b6797a2-ad8f-46d8-8ca9-cf2e242ceec6)

This doesn't make sense to me, beacuse there is already a "bootup" option.
When I uncheck "awake" I cannot use the keyboard after starting the laptop.

2) Ok, I get it. So for my use case I simply uncheck "Enable GPU on shutdown" and switch  to eco mode. When I want to game I simply switch to Standard Mode and after that I have to reboot, to be able to switch back to Eco Mode. 
This is fine by me!

**Comment by seerge** [comment]
Boot / Shutdown states for the keyboard happen before the actual boot starts and after shutdown. 

Rest is "awake" (including when UEFI and Windows loads) This is how things are. 

Generally, keyboards remember their last state on the hardware level, and if they were set to 0 brightness after the restart they will maintain it. But anyway - there is nothing I can do here, as the app is not running at that moment :)

**Comment by seerge** [comment]
@Gebirgskuchen89 you can try to do 1 experiment

Set backlight to 0 (with FN+F2 for example) and after that also change RGB mode to something (static will work) and reboot.  Does it boot with backlight ON ?

**Comment by Gebirgskuchen89** [comment]
No, it doesn't.

**Comment by seerge** [comment]
@Gebirgskuchen89 so it works as it should ? and if you don't change mode after setting backlight to 0 - it would turn on on boot no matter what ?

**Comment by seerge** [comment]
@Gebirgskuchen89 in this build I have added save "save" command that app sends after setting Aura/RGB mode to backlight brightness.

Let me know if it saves backlight state on reboot for you
[GHelper.zip](https://github.com/seerge/g-helper/files/12677256/GHelper.zip)

**Comment by Gebirgskuchen89** [comment]
> @Gebirgskuchen89 so it works as it should ? and if you don't change mode after setting backlight to 0 - it would turn on on boot no matter what ?

It always depends wheter "awake" is checked on or off. If checked on the keyboard Lights Up when I restart my Laptop and shuts down when Windows is started completely, including Ghelper.

If checked Off the keyboard stays Off, No Matter what and I have to Check "awake" on to be able to use the keyboard Backlight function.

**Comment by seerge** [comment]
@Gebirgskuchen89 but that's not what i was asking? :) Of course if you turn OFF awake it will turn OFF whole keyboard completely. 

I asking if setting aura mode after 0 brightness affected saving state on reboot, you seem to approve that ? If it's not the case (and build that I linked here doesn't change it ?) there is nothing i can do here.

**Comment by seerge** [comment]
@Gebirgskuchen89 did you had a chance to check a build linked ?

**Comment by Gebirgskuchen89** [comment]
Hey,

I'll try this evening.

Thanks you!

**Comment by Gebirgskuchen89** [comment]
I checked it, but it didn't help. Nevertheless thanks for your help and your effort in this nice app!
