### ISSUE TITLE
Unable to Change Windows Power Mode

### ISSUE THREAD

**Issue by SimplexShotz** [seerge/g-helper#1336]
**Describe the bug**
Going to "Fans + Power" -> "Windows Power Mode" -> Attempt to change it from "Balanced" to "Best Power Efficiency" does not seem to actually change anything--closing the window and then reopening it shows "Balanced" as the selected mode again, not "Best Power Efficiency."

CPU Boost also resets itself to "Aggressive" sometimes, although this happens less frequently; when this occurs, setting it back to "Efficient Enabled" ONLY works if the setting is changed, and then "Apply Power Limits" is deselected and reselected. This same "fix" does not work for the Windows Power Mode, it always resets to "Balanced."

**Clear scenario to Reproduce**
1. Select "Fans + Power"
2. Change "Windows Power Mode" from "Balanced" to "Best Power Efficiency"
3. Change "CPU Boost" from "Aggressive" to "Efficient Enabled"
4. Close the window
5. Neither setting is saved. The "CPU Boost" setting is only saved if the setting is changed, and then "Apply Power Limits" is deselected and reselected. I am unable to get "Windows Power Mode" to ever save.

**Expected behavior**
Both settings should be saved when the window is closed.

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/12673456/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/44213379/8b06eb90-6753-4383-9e04-23eae3463835)
![image](https://github.com/seerge/g-helper/assets/44213379/6a45cc27-087d-45e0-9746-6f6470c27ff6)
![image](https://github.com/seerge/g-helper/assets/44213379/9d28b61f-5deb-4310-9991-fb8c3740c01e)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home (10.0.22621 Build 22621)
 - Laptop model: 2022 G14 (6900HS + 6700S)

**Asus software**
None

**Additional context**
N/A

**Comment by seerge** [comment]
@SimplexShotz hello,

I believe you are in Battery Saver mode in windows in this case? Then windows just reports incorrect power mode back to the app at all (as it overrides it)

You can download https://github.com/seerge/g-helper/releases/tag/v0.124 where I have addressed this in UI (it will disable dropdown with powermodes in battery saver state for windows)

As for CPU Boost settings - double check if you keep using same (i.e. Balanced) windows power plan :)

**Comment by SimplexShotz** [comment]
I am in battery saver mode, that's correct. Thanks for releasing the update so quickly!
