### ISSUE TITLE
GPU Temp Limit and Screen Flickering

### ISSUE THREAD

**Issue by Timeslides** [seerge/g-helper#1338]
If I activate my custom profile in the Fans and Power window my GPU sets the temperature limit at 75 degrees (verified in GPU-Z), and not the maximum of 87 which is what I am wanting, despite what options I choose regarding power mode etc. Armoury Crate is removed and no Asus services are running. Model is GA401QM.

Another issue I have is screen flickering when at 60hz refresh rate on battery. This can only be fixed by enabling Asus services and restarting.
[log.txt](https://github.com/seerge/g-helper/files/12677558/log.txt)

**Comment by seerge** [comment]
@Timeslides hello, old G14 doesn't have any separate control over temperature limits (as that endpoint in asus firmware is simply not present for your model). So what you have - is the way it's hardcoded OR (probably) this is set by Nvidia driver itself.

Given that you say that you screen also flicker it looks something wrong with the drivers honestly, and I would advice to do a clean reinstall of them using [DDU](https://www.guru3d.com/download/display-driver-uninstaller-download) . As G-Helper has nothing to do with that flicker (it can only set refresh rate in windows, same as you can manually set in windows settings)

**Comment by Timeslides** [comment]
Alright great, thanks for the quick reply Seerge.
