### ISSUE TITLE
Font color bright in dark mode

### ISSUE THREAD

**Issue by lucidnx** [seerge/g-helper#134]
Text is too bright in dark UI, usualy it's better with slightly darker white, maybe #F0F0F0 or #F2F2F2 instead of #FFFFFF, so it does not stand out that much. Especially in titles (Performance mode, GPU mode....)

**Comment by seerge** [comment]
@lucidnx I agree, is this better?
[GHelper.zip](https://github.com/seerge/g-helper/files/11053107/GHelper.zip)

**Comment by seerge** [comment]
I have re-uploaded 0.38 with this changes (font color is #F0F0F0) so closing this topic as completed :)
