### ISSUE TITLE
FN+F2, FN+F3 and FN+F4 doesn't work with ASUS ROG FLOW Z13 2023

### ISSUE THREAD

**Issue by JohnJohn45** [seerge/g-helper#1341]
First of all, sorry for my English (not my language)

**Describe the bug**
FN+F2, FN+F3 and FN+F4 doesn't work with ASUS ROG FLOW Z13 2023
FN+C work well

**Clear scenario to Reproduce**
Use the shortcut do nothing never mind shortcut I select (screenshot, vol+....)

**Desktop (please complete the following information):**
 - WINDOWS 11 22H2
 - ASUS ROG FLOW Z13 2023 (ROG Flow Z13 GZ301VIC_GZ301VIC)

**Asus software**
- Armoury Crate not installed
- MyASUS not installed
- Other Asus services running in background --> 0 service running

<img width="376" alt="Capture d’écran 2023-09-21 091604" src="https://github.com/seerge/g-helper/assets/26327298/fd45de72-6179-4173-8e35-58a840285e3e">

[log.txt](https://github.com/seerge/g-helper/files/12681568/log.txt)

**Comment by seerge** [comment]
@JohnJohn45 hello, i don't see any signs of keys pressed in a log at all

Every time you press a key or fn+key, if it's processed - it will add a line like
```
9/21/2023 9:38:28 AM: Key: 179
```
So check what keycodes your FN+F2/F3/F4 generate in a log

**Comment by JohnJohn45** [comment]
I press key before sending log.

Here a new log, I press FN+F1 FN+F2 FN+F3 FN+F4 FN+F5 FN+F6  before sending log

FN+F1 --> "silence" as expected
FN+F2 --> do nothing
FN+F3 --> do nothing
FN+F4 --> do nothing
FN+F5 --> change performance mod as expected
FN+F6 --> mute as expected
[log.txt](https://github.com/seerge/g-helper/files/12681805/log.txt)

**Comment by seerge** [comment]
@JohnJohn45 hello, ok 

Well, I see that ``FN+F4`` seem to work ok as well (it muted / unmuted microphone) :) you should also see a notification about that in a center of the screen. So it works

```
21/09/2023 09:47:37: Key: 124
21/09/2023 09:47:37: Réseau de microphones (Realtek(R) Audio):True
21/09/2023 09:47:38: Réseau de microphones (Realtek(R) Audio):True
21/09/2023 09:47:38: Réseau de microphones (Realtek(R) Audio):True
21/09/2023 09:47:39: Key: 124
21/09/2023 09:47:39: Réseau de microphones (Realtek(R) Audio):False
21/09/2023 09:47:39: Réseau de microphones (Realtek(R) Audio):False
21/09/2023 09:47:39: Réseau de microphones (Realtek(R) Audio):False
``` 

As for FN+F2/F3 i think they just generate a volume down / up keycodes on hardware level (as they are analogues of M1/M2 keys on other devices that do same). So by default they would just do windows volume controls, and app doesn't interfere with that :)

If you will set them to other actions you should see keycodes like in a log after pressing them with a following action
```
9/21/2023 9:54:00 AM: VolumeUp
````

**Comment by JohnJohn45** [comment]
- Close ghelper
- delete log
- Open ghelper
- select shortcut like on the screenshot
- press FN+F2, FN+F3 and FN+F4
- close ghelper



[log.txt](https://github.com/seerge/g-helper/files/12681924/log.txt)

<img width="371" alt="Capture d’écran 2023-09-21 091604" src="https://github.com/seerge/g-helper/assets/26327298/15195511-7711-4818-b2fa-771bc00e7b3b">

**Comment by seerge** [comment]
@JohnJohn45 in new log i don't see any keycodes at all (means app was not notified about keypresses). Even for Fn+F4.

While in previous log Fn+F4 action was there :)

I don't know why it happens on your device. As far as I remember Z13 has that detachable bluetooth keyboard, mb it just doesn't always connect properly ?

You can try to start  Asus Optimization Service (from window Services app) that handles hotkeys for asus apps, and see if it will make a difference

**Comment by JohnJohn45** [comment]
It is an "USB" keyboard (not bluetooth) so no connection problem. And I haven't disconnect it between tests.

- Close ghelper
- delete log
- activate asus optimisation service
- open ghelper (it said 1 service is activate)
- press FN+F2, FN+F3 and FN+F4
- nothing happened
- close ghelper

[log.txt](https://github.com/seerge/g-helper/files/12682132/log.txt)

**Comment by seerge** [comment]
@JohnJohn45 ok.

With Opimisation Service running, it will be handing hotkeys instead (so no keycodes in the log, but this time it's expected) :) 
If nothing happens - it looks like that service also doesn't get notifications about key-presses.

I guess you can stop it again (via Extra -> Stop). As apparently that had no effect.

Try to experiment / and figure out why in a first log FN+F4 was working, and then it stopped. May be reboot will help?

**Comment by JohnJohn45** [comment]
sorry if I'm wrong but FN+F4 never work, the key you see in firsts log is FN+F6 I press too and cut mic
I think it help you to see difference between key that work and key that doesn't.

I already reboot a lot of time since I use your wonderful software 1 week ago. I use V123 and now v124 and this 3 shortcuts never work. As far as I can test all other function work as expected so it is not a big deal, but I wanted to point this out to you to perfect your software.

**Comment by seerge** [comment]
@JohnJohn45 ``keycode 124`` is ``Fn+F4`` (and app even did a mic-mute action in a log). So it looks like it worked fine :) 
![keyboard](https://www.trustedreviews.com/wp-content/uploads/sites/54/2022/04/Asus-ROG-Flow-Z13-8-1024x768.jpg)

For ``Fn+F2`` and ``Fn+F3``  - as I mentioned unless changed to something else they just produce a native windows volume up / down commands that are not handled by software at all (neither by G-Helper nor by Asus), but handled directly by windows (or even linux :) ). So they should work even if G-Helper is not running at all. 

Other laptops work in a same way (except they have M1 and M2 buttons for that)

So if even volume changes don't work in your case - it looks more like a hardware problem, not a software ...

But if you will change default action for Fn+F2/F3 to something else - app registers volume buttons as own hotkeys, and runs another action when windows lets it know that hotkey is pressed. But again - if volume controls don't work in a first place, custom actions won't work neither

**Comment by JohnJohn45** [comment]
I close ghelper, delete log, open ghelper and press FN+F6 and then close Ghelper.
Log said key 124 is FN+F6 on my keyboard.

21/09/2023 12:19:16: ------------
21/09/2023 12:19:16: App launched: ROG Flow Z13 GZ301VIC_GZ301VIC :0.124.0.0fr-FR
21/09/2023 12:19:18: CPU: -1 - 13th Gen Intel(R) Core(TM) i9-13900H - Intel64 Family 6 Model 186 Stepping 2
21/09/2023 12:19:18: AutoSetting for Online
21/09/2023 12:19:18: Input: \\?\hid#vid_0b05&pid_1a30&mi_00&col01#7&391df2e&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
21/09/2023 12:19:18: Mode = 2 : OK
21/09/2023 12:19:18: Eco flag : 1
21/09/2023 12:19:18: Mux flag : 1
21/09/2023 12:19:18: \\?\DISPLAY#TMX0001#4&2c34b09a&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
21/09/2023 12:19:18: \\?\DISPLAY#TMX0001#4&2c34b09a&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
21/09/2023 12:19:18: ScreenOverdrive = 1 : OK
21/09/2023 12:19:19: BatteryLimit = 80 : OK
21/09/2023 12:19:19: USB-KB 0x1A30:5D-BD-01-08-1E-00-00-FF
21/09/2023 12:19:19: USB-KB 2Périphérique fournisseur HID\\?\hid#vid_0b05&pid_1a30&mi_00&col04#7&391df2e&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
21/09/2023 12:19:19: Monitor Power On
21/09/2023 12:19:20: Auto:5D-BA-C5-C4-01
21/09/2023 12:19:20: Latest version 0.124.0.0
21/09/2023 12:19:27: Key: 124
21/09/2023 12:19:28: Réseau de microphones (Realtek(R) Audio):True
21/09/2023 12:19:28: Réseau de microphones (Realtek(R) Audio):True
21/09/2023 12:19:28: Réseau de microphones (Realtek(R) Audio):True

**Comment by seerge** [comment]
@JohnJohn45 that's strange then. May be it's some random specific of a French (AZERTY?) keyboard? :) then it means you can bind Fn+F6 action with Fn+F4 setting in the app.

But anyway 
1. Do Volume up / down (Fn+F2/F3) work with G-Helper running or quitted ? 
2. Did they work with Armoury Crate ?

**Comment by JohnJohn45** [comment]
my keyboard if it can help : 
![IronHrt_20230921_122527140~2](https://github.com/seerge/g-helper/assets/26327298/5c0e028c-841a-4f22-9be0-8b05a71d71cc)

1 : no
2 : they work like expected in media player for play/pause, previous/next with or without armoury crate but I can't reassign

these keys are not dedicated to sound initially. They work for play/pause, next and previous in media player if I open VLC or other media player. But If I want change there function with ghelper nothing work.

**Comment by seerge** [comment]
@JohnJohn45 Oh, screenshot explains a lot!

That's not standard keyboard then ... :))

You don't have volume controls on it, and Fn+F6 is indeed micmute on yours (so app processes it)

Then I'm afraid you won't be able to rebind Fn+F2/Fn+F3 as they simply are different buttons in your case :|

**Comment by seerge** [comment]
@JohnJohn45 if the only thing you want is to assign them to volume controls you can just use http://www.randyrants.com/category/sharpkeys/

Currently they probably produce standard windows media controls (play/payse next/previous). You can just rebind any standard key to any another with Sharpkeys :) 

The only thing I can do is to hide Fn+F2/F3 bindings in Extra for your (GZ301VIC ARCNM model) and rename Fn+F4 label to Fn+F6 (cause that what it does in reality)

**Comment by JohnJohn45** [comment]
this is origial keyboard of this ASUS model
https://rog.asus.com/laptops/rog-flow/rog-flow-z13-acrnm-rmt02/

Ok, not a big deal if I can't reassign keys.
**Actually, all FN +function keys work as it is written on the keyboard so it's good for me.**

If I can Help with log or other things to hide FN+ F2 F3 and F4 bindings for this model tell me.

**Comment by seerge** [comment]
@JohnJohn45 this build will hide unsupported bindings for you

[GHelper.zip](https://github.com/seerge/g-helper/files/12683689/GHelper.zip)

Fn+F1 .. F4 are just regular windows media keys for you, they work on hardware level (i.e. not processed by app at all).
As I have mentioned you can rebind them using standard apps like Sharpkeys (or Autohotkey)

**Comment by JohnJohn45** [comment]
thank you with new build I have FN+F6 and FN+C in key in the list. They can be resassign and works normally.

<img width="382" alt="Capture d’écran 2023-09-21 091604" src="https://github.com/seerge/g-helper/assets/26327298/235d9042-1e6f-4b64-8606-53cb12a785eb">

If it can help to add other key for this model, with the build you send to me I have in log : 
FN +F1 --> no key in log
FN +F2 --> no key in log
FN +F3 --> no key in log
FN +F4 --> no key in log
FN +F5 --> Key: 174
FN +F6 --> Key: 124
FN +F7 --> Key: 16
FN +F8 --> Key: 32
FN +F9 --> no key in log
FN +F10 --> Key: 107
FN +F11 --> Key: 108
FN +F12 --> no key in log

**Comment by seerge** [comment]
@JohnJohn45 great, thanks for checking.

All keycodes you have listed area already known (and processed) by the app.

I'm closing it as completed then. I will include label changes in next release.
