### ISSUE TITLE
XG Mobile 4090 LED control not working.

### ISSUE THREAD

**Issue by sgandy2989** [seerge/g-helper#1344]
I have 2 versions of the XG Mobile Dock for my Flow X13 2023, the led control works for the 3080 version just not the 4090 version. I also have tried the XG Mobile with a different Flow X13 and the problem seems only effect the 4090. 

Thank you so much for all of your hard work and effort you have have put in, its amazing what you are capable of accomplishing compared to Asus! Keep up all the hard work, it is truly appreciated!

**Comment by sgandy2989** [comment]
Sure, I have no problem helping debug. I have time over the next 2 days, thanks for the quick response.

**Comment by seerge** [comment]
Closing as abandoned
