### ISSUE TITLE
The AC can synchronize 3MS Settings to GHelper, but GHElper cannot synchronize OD Settings to AC

### ISSUE THREAD

**Issue by KizzWang** [seerge/g-helper#1346]
## NOTE
Hello, when I stop or start the OD option from GHelper, then open AC, screen OD cannot sync to 3MS of AC. 
But when I started or turned off AC 3MS and then open GHleper, GHelper's screen can change. If 3MS of the AC is enabled, the OD of GHelper can be opened.

The AC can synchronize 3MS Settings to GHelper, but GHElper cannot synchronize OD Settings to AC

**Comment by KizzWang** [comment]
GHelper seems to have only the ability to read OD without the ability to change it. When I turn off 3MS from AC, open gh and turn on OD, GH shows 165+OD, but when I turn on AC again, 3ms is not turned on. At this time I restart the computer, the first time to open GH, only 165 display, and 3MS in AC not open.

**Comment by KizzWang** [comment]
The premise of doing this is to shut down all Asus services.

**Comment by KizzWang** [comment]
Desktop (please complete the following information):

OS: win 10 ltsc
Laptop model - G14 2023
Asus software

Armoury Crate (or it's services installed) - yes
MyASUS installed - no
Other Asus services running in background - no

**Comment by seerge** [comment]
@KizzWang hello, 

How do you know that G-Helper doesn't set overdrive? 
Armoury just don't read any overdrive settings. It just shows what it has set last.

G-Helper reads and sets OD :)

**Comment by KizzWang** [comment]
Well, you are right, after deleting AC, all become perfect.

**Comment by seerge** [comment]
Great
