### ISSUE TITLE
Different brightness settings when plugged and unplugged

### ISSUE THREAD

**Issue by himankpathak** [seerge/g-helper#1352]
**Is your feature request related to a problem? Please describe.**
When using Armoury Crate (not sure whether AC or Windows controlled this), the app used to remember the previous brightness level I set on plugged and unplugged. On plugging the charger the brightness would automatically switch to the last brightness level I set.
I like to keep brightness low when unplugged to extend my battery life and it's a hassle to do it manually when previously it used to work perfectly.

**Describe the solution you'd like**
G-Helper can remember different brightness settings and update the level when the charger is plugged and unplugged.

**Describe alternatives you've considered**
None

**Additional context**
This feature can be made optional in extra settings

**Comment by seerge** [comment]
@himankpathak hello, it's windows that controls brightness and saves them as part of windows power plan :)

If you just want to dim brightness a bit on battery -> there is setting for that in windows

If you want something absolutely custom, just create a second copy of "Balanced" windows power plan in Control Panel and then assign it manually to one of the modes in G-Helper that you use for battery https://github.com/seerge/g-helper#custom-windows-power-plans-with-each-mode

**Comment by himankpathak** [comment]
Thanks, this resolved it for me.
