### ISSUE TITLE
[Feature request]Music keyboard backlight

### ISSUE THREAD

**Issue by oflg** [seerge/g-helper#1357]
On my device  G-Helper does not have the Music function in Aura Effects, which is one of the reasons I switched to armoury crate!

![image](https://github.com/seerge/g-helper/assets/42492105/fced2b2f-cb17-4a67-88f2-f8ea3ea8d43c)

![image](https://github.com/seerge/g-helper/assets/42492105/da8b23c6-9d78-45f6-a706-d2aa2c968ede)

Is this feature not being developed right now, or is it just a bug on my device?

**Comment by seerge** [comment]
@oflg hello

There is no such hardware mode in keyboard as "music" obviously.

To do that app would need analyze audio stream in background in real-time + set backlight color like 10 times every second (to have some reasonable effect) . Even current "Heatmap" mode that sets backlight every 2 seconds (20 times less frequent) is already quite resource heavy. 

So I'm not a big fan of overloading app with things like that and then getting shitstorm on reddit that "OMG G-HELPER DRAINS MY BATTERY!!!111"

**Comment by oflg** [comment]
Haha, it does drain the battery very much. It makes total sense not to have that feature.
