### ISSUE TITLE
Not starting with windows and settings not saving

### ISSUE THREAD

**Issue by Zumux** [seerge/g-helper#1359]
**Describe the bug**
I recently got a laptop and would like to use G Helper instead of the Asus bloat it comes with. G Helper isn't starting up with windows and settings don't seem to be saving. I have tried what is [here](https://github.com/seerge/g-helper#app-refuses-to-run-on-startup-or-runs-without-any-icon-in-tray-on-startup) in the faq but since it doesn't save what I put when the app is completely closed and reopened I'm not really sure what to do. I have looked in task schedular and do not see anything names g helper or similar. 

**Clear scenario to Reproduce**
1. Open g helper and turn on startup or set any setting
2. Close g helper and close from tray or restart computer
3. G helper wont start when starting windows
4. Open g helper and see that no setting were saved

**Expected behavior**
G Helper to start with windows and settings to save

**App Logs**
log.txt: https://pastebin.com/S41AJF69
config.json: https://pastebin.com/2Jj1kawq

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2
 - Laptop model: Asus Vivobook 15 OLED (M1505)

**Asus software**
- None

**Comment by seerge** [comment]
@Zumux did you click on "Run on Statup" checkbox ? then it will create a task under Task Manager for itself

**Comment by seerge** [comment]
@Zumux P.S. It could be also some weird user-permission settings in your windows setup. Try to run G-Helper as admin, and then set it to run on startup.

**Comment by seerge** [comment]
@Zumux does F12 open MyASUS on Vivobooks ? Check if it generates any special key code (open app log and press F12 to see if app sees it). If not - then regular F12 can not be assigned cause it's reserved by windows itself.

But you can already use ``Ctrl + Shift + F12`` to open G-Helper window (assuming it's running in tray)
