### ISSUE TITLE
Windows Defender not allowing download

### ISSUE THREAD

**Issue by skanderbegv2** [seerge/g-helper#136]
![image](https://user-images.githubusercontent.com/74790210/227335026-22dd761a-aef5-4e56-859c-3f19c73df82b.png)

**Comment by seerge** [comment]
What version is that ? (I'm not getting it on latest 0.38 for example). Alternatively you can download a previous build :)

**Comment by skanderbegv2** [comment]
Yes latest 0.38 :)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11055371/GHelper.zip)
I just recompilled the same thing again just in case

**Comment by skanderbegv2** [comment]
This one works :) many thanks!

**Comment by seerge** [comment]
Great
