### ISSUE TITLE
Allow other programs to react to "special" key presses.

### ISSUE THREAD

**Issue by Varriount** [seerge/g-helper#1363]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use a program like AutoHotkey in combination with the "hidden" keyboard keys, like the _Function_ (_Fn_) key. Due to how these keys are implemented, this is only possible by listening to HID codes (which is *not* something that would be easy to implement in AHK).

**Describe the solution you'd like**
Since G-Helper already handles processing "special" keys, it would be nice if it could also broadcast to the system when these keys are pressed. This could be via simulating presses of the OEM keycodes (it looks like there are *just* enough for all the special keys), sending of window messages, etc.

**Comment by seerge** [comment]
@Varriount hello, you can already do that, just set M-keys to emit unpopular F-keys like F23 as explained https://github.com/seerge/g-helper#custom-hotkey-actions 

And then just process them in AutoHotkey

**Comment by Varriount** [comment]
Oh! My apologies. I had read that section of the README, but hadn't quite processed the fact that it could be used for my use-case.

(By the way, reading the HID events directly is very clever!)

**Comment by Varriount** [comment]
So, there some problems with the above solution:
  - G-Helper doesn't have a hotkey entry for an individual press of the Function key.
  - There's no way for other applications to send Function key presses to G-Helper without giving up one of the pre-existing hotkeys combinations.

**Comment by seerge** [comment]
@Varriount 

> G-Helper doesn't have a hotkey entry for an individual press of the Function key.
Function key doesn't emit any keycodes at all. It's not possible to intercept it

Everything else you have listed here depends on that as well.

**Comment by seerge** [comment]
@Varriount all HID codes that app gets - it adds to the log file. You can try that yourself.

**Comment by Varriount** [comment]
Hm, while the `Fn` key isn't logged in G-Helper, [HID Data Watcher](https://github.com/djlastnight/HidRawDataWatcher) appears to pick up the key presses just fine:
![image](https://github.com/seerge/g-helper/assets/524596/d7c75cba-7830-4e8d-9a7b-07345fd263a2)

(The first line was logged when I pressed the `Fn` key, and the second was logged when I released it.)

Other observations:
  - [HIDLibrary](https://github.com/mikeobrien/HidLibrary/blob/master/src/HidLibrary/NativeMethods.cs#L130) (used by G-Helper) obtains HID device data by using the [Setup Device APIs](https://learn.microsoft.com/en-us/windows/win32/api/setupapi/) to enumerate available devices, and then uses the standard file APIs (CreateFile, WriteFile, etc.) to read information from the device.
  - [HIDRawData](https://github.com/djlastnight/HidRawData/blob/master/HidRawData/Win32/Win32RawInput/NativeMethods.cs) (used by HID Data Watcher) obtains HID device data by using the [Raw Input APIs](https://learn.microsoft.com/en-us/windows/win32/inputdev/about-raw-input). These APIs are used both to enumerate available devices and read device data. Key presses from the device are received and decoded from window messages.
  - Both programs use the same device ID to open/select/read data.

I'll continue looking into this, but would value any thoughts you may have.

**Comment by seerge** [comment]
@Varriount that's an interesting find, but I don't want to listen for all possible raw data from the device. As it will de-facto turn app into a keylogger (and may be as a side effect slow down input processing in windows even? i don't know much about it)

But you seem to be technical :) You can write a mini-app that will catch all raw events and propagate them further to Autohotkey / etc. You are already half-way there ;)

**Comment by Varriount** [comment]
@seerge Good suggestion! I'm hoping that I can do what the Raw Input API is doing using the HID API, and that whatever technique I use works on more than just Asus laptops.

**Comment by Varriount** [comment]
Aha! I made a mistake last night - in fact, the device HID Data Watcher is reading from _isn't_ the one that G-Helper is reading from!

G-Helper is reading from 
<pre>
\\\\?\\HID#VID_0B05&PID_19B6&<b><i>Col03</i></b>#6&19e2ad7&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
</pre>,
while HID Data Watcher is reading from 
<pre>
\\\\?\\HID#VID_0B05&PID_19B6&<b><i>Col04</i></b>#6&19e2ad7&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
</pre>

What confused me was the assumption that the USB-KB device in G-Helper's logs (and the device HID Data Watcher was reading) was the one that it was reading keyboard data from.

**Comment by Varriount** [comment]
Aha! I made a mistake last night - in fact, the device HID Data Watcher is reading from _isn't_ the one that G-Helper is reading from!

G-Helper is reading from a device with a hardware ID of
<pre>
\\\\?\\HID#VID_0B05&PID_19B6&<b><i>Col03</i></b>#6&19e2ad7&0&<b><i>0002</i></b>#{4d1e55b2-f16f-11cf-88cb-001111000030}
</pre>
while HID Data Watcher is reading from a device with a hardware ID of
<pre>
\\\\?\\HID#VID_0B05&PID_19B6&<b><i>Col04</i></b>#6&19e2ad7&0&<b><i>0003</i></b>#{4d1e55b2-f16f-11cf-88cb-001111000030}
</pre>

<small>(side note - I wonder what each "component" of a hardware ID represents)</small>

What confused me was the assumption that the USB-KB device in G-Helper's logs (the device HID Data Watcher was reading) was the one that it was reading keyboard data from.

Now, what will be tricky is the fact that any utility wanting to make function key presses available will have to heuristically detect which device to read from, since I can't find any meaningful indicator for the "full" keyboard HID.

Oh, and by the way, I found an additional key combination reported for the function key - "Fn + v". I don't know if it does anything with Armoury Crate, but I figured you could add it to G-Helper's key combo list. It looks like it's represented as `138` in the second byte of the output data.

---

For anyone wanting to play around with this, here's a quick Python script that uses [hidapi](https://pypi.org/project/hidapi/) library:
```python
import hid

for index, device_dict in enumerate(hid.enumerate()):
    keys = list(device_dict.keys())
    keys.sort()

    print(f"Device #{index + 1}")
    print("-------------------")
    print("Metadata:")
    for key in keys:
        print(f"    {key!r}: {device_dict[key]!r}")
    
    device = hid.device()
    try:
        device.open_path(device_dict['path'])
        print("Output data (press ctrl+c to stop):")
        while True:
            result = device.read(128, 100)
            if result:
                print(f"    {result}")
    except KeyboardInterrupt:
        pass
    except OSError as error:
        print(f"Error reading from device: {error}")
    finally:
        device.close()

    print()
```
