### ISSUE TITLE
Need a color switch button for the software itself

### ISSUE THREAD

**Issue by MJSummer** [seerge/g-helper#1371]
**Is your feature request related to a problem? Please describe.**
I hope there is a button that can switch between black and white colors in the software. I think the software text readability is higher in black mode.

**Describe the solution you'd like**
Just an extra switch or button

**Describe alternatives you've considered**
Nope.

**Additional context**
Nope.

**Comment by seerge** [comment]
@MJSummer hello, if you mean UI dark / light themes they can be [set via config already ](https://github.com/seerge/g-helper#override-ui-theme)

**Comment by MJSummer** [comment]
Thank you so much. It works well.
By the way, I think the "config" is at %AppData%\Roaming\GHelper\config.json
I'm wondering why there is something different.

**Comment by seerge** [comment]
@MJSummer ``%AppData%`` is the alias of ``Roaming`` :)
