### ISSUE TITLE
Automated Profiles

### ISSUE THREAD

**Issue by armyman2870** [seerge/g-helper#1376]
**Describe the solution you'd like**
An option to set a 'profile' which automatically applies based on criteria (unplugged/plugged in, etc). It basically can change CPU and GPU mode (maybe HDR, etc) to what we set based on if we plugged in the charger for example. It could also enable/disable game mode.

**Describe alternatives you've considered**
As of now, its all manual so we need to select the mode we'd like. 

It would be great to have, making life a lot easier

**Comment by seerge** [comment]
@armyman2870 hello, 

App already remembers (Performance) Mode per plugged in / on battery state and will switch automatically every time plug or unplug.

As for GPU "mode" - you have Optimized that literally disables GPU on battery and enables it back

**Comment by armyman2870** [comment]
Alright, thanks!
