### ISSUE TITLE
i can't change my led mode in tuf dash 

### ISSUE THREAD

**Issue by phamquy68** [seerge/g-helper#1380]
static , breath , strobe is defaut but i can't use this

**Comment by Scarlaid** [comment]
you might wanna provide more information or this likely getting ignored
![image](https://github.com/seerge/g-helper/assets/90851437/faa68b20-79f8-43c4-8a05-b652709119e0)

**Comment by seerge** [comment]
> ## NOTE
> Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. Please respect the time of the developer. Thanks.
