### ISSUE TITLE
Fans not turning on after waking up from sleep/hibernate in optimized mode/eco mode

### ISSUE THREAD

**Issue by githubuser832** [seerge/g-helper#1381]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**
fans wouldn't turn on if I set the GPU mode to either eco or optimized mode after waking up from sleep/hibernate mode. laptop temp then kept on rising until it's throttling. 

**Clear scenario to Reproduce**
1. Set the GPU mode to either eco or optimized.
2. let the laptop to enter sleep/hibernate mode 
3. wake up the laptop after some time (about 30mins maybe)
4. use the laptop as usual (I was using blender and gaming)
5. the fans wouldn't run at all no matter how hot it got.
6. laptop shut down after reaching 100 c

**Expected behavior**
fans should turn on after reaching a certain point of temp (60 c)
i tried to switch the gpu mode to no avail

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/12745640/log.txt)

**Screenshots or screencasts**

![Screenshot (12)](https://github.com/seerge/g-helper/assets/85854900/c267bd3e-883c-49ec-b43d-511e7aca5d63)
![Screenshot (14)](https://github.com/seerge/g-helper/assets/85854900/635c3a4d-fa23-488e-9e4e-6f6c3fdaba8e)
![Screenshot (15)](https://github.com/seerge/g-helper/assets/85854900/71bbd6e2-f183-470c-b201-b83d5fa27d32)
![Screenshot (13)](https://github.com/seerge/g-helper/assets/85854900/c305da87-badd-426c-b45b-759a38a74ef2)

**Desktop (please complete the following information):**
 - Windows 11 Home 22H2 build 22621.2283
 - Laptop model: TUF Gaming F15 FX506HM

**Asus software**
- Armoury Crate uninstalled
- MyASUS uninstalled
- Other Asus services disable in G helper
- 

**Additional context**
fans will run just fine if I set the GPU mode to standard only.

**Comment by seerge** [comment]
@githubuser832 hello, does changing mode (or restarting app) wake up your fan in that situation ?

**Comment by githubuser832** [comment]
hi, changing modes used to work, but not anymore. the only way to solve this problem was to either leave the GPU mode to standard only or to restart the laptop. which can be inconvenient at times.

**Comment by seerge** [comment]
@githubuser832 I see. Well, if changing mode or restarting app (as on restart it also sends "init" command to firmware/bios) doesn't help - there is nothing I can do here.

Just in case - it's some kind of a hiccup with specific firmware on your model, that just "forgets" about fans on wake up.

- You can try to do a [hardware reset ](https://github.com/seerge/g-helper#how-do-i-do-a-hardware-reset-on-a-laptop) 
- Do you have Armoury Control interface enabled in BIOS ? (try to enable or disable it, depending on current state)
- Do you use latest BIOS version ? If so - may be try to downgrade to a previous version ?

**Comment by githubuser832** [comment]
i did the hardware reset, still same issue.
disabled the armoury crate in bios, same issue
i couldn't find older bios version on asus website so I am not sure where to find one. I checked on the EZ flash, it says that i'm on bios ver. 315.
I can switch GPU modes and the fans will work just fine as long as the laptop does not enter sleep/hibernate while on iGPU mode. so for now the workaround is going back to standard mode before entering sleep/hibernate :/

**Comment by seerge** [comment]
@githubuser832 sad to hear.

Does switching GPU mode (i.e. enabling / disabling) GPU wake up your fan by any chance ?

**Comment by githubuser832** [comment]
hey, want to give an update that now it's working fine. Downgrading the bios to 313 made the fans run again even after sleep/hibernate. Switching to either modes are now working as intented. Problem solved, thanks for your help!

**Comment by seerge** [comment]
@githubuser832 oke, glad to hear that BIOS downgrade helped! :)

**Comment by seerge** [comment]
@githubuser832 Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks
