### ISSUE TITLE
Constant disk activity

### ISSUE THREAD

**Issue by lanmower** [seerge/g-helper#1382]
The tool appears to be locking the disk activity display in windows to 0.1MB/s, indicating that there is some reading or writing constantly occuring to the drive, is this neccesary?

**Comment by seerge** [comment]
@lanmower why do you think so ? Check task manager for what apps are using your disk.

**Comment by lanmower** [comment]
Task manager reports ghelper is

**Comment by seerge** [comment]
@lanmower the only thing G-Helper can write a line or two to the disk is own log. 

That happens every time you would change some settings there OR you would change windows power mode (like plug / unplug / wake up from sleep / etc).

But that doesn't happen "constantly" obviously and doesn't "lock" any disk activity as you claim.

Given that you didn't provide any logs or extra information as it was clearly asked in template issue, I'm closing this.

**Comment by lanmower** [comment]
![image](https://github.com/seerge/g-helper/assets/657315/62a20e16-733f-4ad2-aa37-ac1d1f2a35f9)
its permanently using the disk, please read my report I didn't claim that it's locking disk access, but I do claim that writing or reading at least once a second will affect battery life.

You didn't need logs, you could have just looked at task manager to see that for yourself 🙏

![image](https://github.com/seerge/g-helper/assets/657315/d17f9c0a-65c5-4f17-8d2f-04a094ebdf34)

io other appears to be the statistic being recorded that bumps it's mbps from 0.0 to 0.1

![image](https://github.com/seerge/g-helper/assets/657315/58b36a5e-1ab0-4847-a033-0dd0e2b1ab6b)

Since I'm not sitting on the source open with a profiler or something, is that enough?
