### ISSUE TITLE
Fan not turning on in silent mode with iGPU

### ISSUE THREAD

**Issue by JohnJohn45** [seerge/g-helper#1383]
Sorry for my english

**Describe the bug**

**Clear scenario to Reproduce**
Start PC with ghelper 126 autostart
Use Silent mod + ECO
Fan Never turning ON

I use factory default for fan curves (never change it)

Restart PC and bug persist

Use Balanced CPU mod activate CPU fan according to the curves
Use standard GPU mod (DGPU) + silent mod activate CPU fan according to the curves

**Expected behavior**
Fan turning on when CPU temp is > 54°C

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12749064/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - Windows 11
 - ROG Flow Z13-ACRNM RMT02 GZ301VIC

**Asus software**
- Armoury Crate not installed
- MyASUS not installed
- 0 Asus services running in background

<img width="833" alt="Capture d'écran 2023-09-28" src="https://github.com/seerge/g-helper/assets/26327298/ef77295b-968c-4b10-bc11-d2751902b7ce">
<img width="819" alt="Capture d'écran 2023-09-28 134027" src="https://github.com/seerge/g-helper/assets/26327298/dae9fa97-69a6-4703-8a2e-1f2c7a5ddf2e">
<img width="818" alt="Capture d'écran 2023-09-28 134343" src="https://github.com/seerge/g-helper/assets/26327298/efbb7733-eef9-4821-b669-9164ad6c6a7c">

**Comment by seerge** [comment]
@JohnJohn45 hello,

This is probably how Silent mode fan behavior is hardcoded in your BIOS :) I assume Asus wanted to keep device really silent.

- Does it turn on the fans when temperatures get even higher ? like 90C?
- Does custom fan curve (i.e. when you click apply) change the behavior ?

**Comment by JohnJohn45** [comment]
In silent mod CPU and GPU fan first level is 54°C with fan curve factory default .

1) I use OCCT to stress PC and fans seem to activate only when CPU temperature is more than 80°C
IGPU fan not turn on at 54°C but only when CPU fan turn on (GPU was around 60°C)

2) apply curve in ghelper change the behavior and fans seems to work like defined on curves, so it seem factory default curves for silent mod are not good. Maybe i can help you to correct this ?

<img width="809" alt="Capture d'écran1" src="https://github.com/seerge/g-helper/assets/26327298/2bc5d2a2-aa2c-44d0-9cff-6ca98f97c3cc">
<img width="815" alt="Capture d'écran 2" src="https://github.com/seerge/g-helper/assets/26327298/790dcc54-d320-4638-9db6-ed25ecb88245">

**Comment by seerge** [comment]
@JohnJohn45 if after applying a custom fan curve it follows it - then everything is fine :)

As for default fan behaviors, as i have mentioned - this is how asus have programmed them initially. You can't change that.

G-Helper shows whatever BIOS reports as "default",  and it's indeed may not always match actual behavior (because asus is asus). Or actual behavior may be more complicated than a simple chart at all (for example, it can wait for a long time for temperature to stay high and only then actually set fans). That's how things are :)

There is nothing to "fix" here, therefore closing this issue.

**Comment by seerge** [comment]
@JohnJohn45 Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks
