### ISSUE TITLE
FN+C key bindings do not work for ASUS TUF A16 Advantage.

### ISSUE THREAD

**Issue by KHP86** [seerge/g-helper#1384]
**Describe the bug**
FN+C key bindings do not work for ASUS TUF A16 Advantage. I am unable to toggle between FN-Lock and FN-Unlock modes.

**Clear scenario to Reproduce**
Pressing "FN" button and character "c" button does not invoke key binding function. 

**Expected behavior**
Pressing "FN" button and character "c" button should toggle FN-Lock and FN-Unlock modes.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12751823/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 22H2 - OS Build 22621.2283
 - Laptop model: ASUS TUF Gaming A16 Advantage - FA617NS

**Asus software**
- Armoury Crate - Uninstalled using official ASUS Uninstaller Utility 
- MyASUS - Uninstalled through control panel app manager
- Used GHelper to disable ASUS processes and displays "0" Asus Services Running
- Other Asus services running in background:
  * ASUS Smart Display Control (32 bit)
  * ASUS Monitor Control
  * ASUS Hotplug Controller

**Comment by seerge** [comment]
@KHP86 hello

``Fn+C`` generates key-code (or WMI event) ``158``

I don't see it anywhere in your log, so I can imagine that Fn+C combo is simply not supported on your keyboard (i.e. it doesn't emit anything in this situation)

You can just bind any other supported hotkeys to Fn-Lock instead :)
