### ISSUE TITLE
Ally home button

### ISSUE THREAD

**Issue by fennectech** [seerge/g-helper#1386]
**ally has no steam / home button but one button thats not commonly used**

**allow us to map a button to the steam home button**

**Comment by seerge** [comment]
@fennectech hello.

Ally has 4 buttons, 2 of them belong to built-in controlled and already handled by windows (view and menu). You can rebind them with any controller-related software (including steam or https://www.rewasd.com/ )

Command center / AC (rog) buttons are asus-proprietary and can be set via G-Helper under Extra settings

**Comment by fennectech** [comment]
I know they can. But they cannot be set to the home button / guide button / steam button in G-Helper. Thats what i mean

**Comment by seerge** [comment]
@fennectech i can't emulate controlled buttons, as you literally need to write a driver for that. But you can set this buttons to emit some unpopular F-keys (for example F22 and F23) [under Extra ](https://github.com/seerge/g-helper#custom-hotkey-actions)

And then use dedicated software (like REWASD i mentioned above) to emulate controller actions from F-key presses

**Comment by fennectech** [comment]
Apperently steam detects input from Ctrl + 1 as guide button. Can i do a key combo?

**Comment by seerge** [comment]
@fennectech try to bind guide button to some other key combination :) you can't set g-helper to emit key combinations, only single keys

**Comment by fennectech** [comment]
may i make this a feature request for key combinations? and i will use ahk or smth until its implimented   Less software running the better    ive been using handheldcompanion for it  but the issue is hidhide is broken on insider windows.   So it results in duplicate inputs to steam and games  but thank you

**Comment by seerge** [comment]
@fennectech this build should allow 1,2 or 3 key combos
[GHelper.zip](https://github.com/seerge/g-helper/files/12776782/GHelper.zip)

Just fill in ``0x11 0x31`` as command (``0x11`` is ``Control``, ``0x31`` is ``1``)

Custom field now supports up to 3 keys from https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes in a row (that will be emitted as simultaneous keypress)

**Comment by fennectech** [comment]
Holy moly!   I didn’t even get a chance to set rewasd up!  Leme get into the thing with TeamViewer

**Comment by fennectech** [comment]
it doesnt seem to be working    the input is not being detected by steam   i have verified that ctrl + 1 over teamviewer worked

**Comment by seerge** [comment]
@fennectech so it works in teamviewer but not in steam? then i can’t help

I tested key combinations and they do work (in windows and other apps), but steam could listen for real hardware input- therefore you can’t initiate it :)

**Comment by fennectech** [comment]
i mean  i did inputs over teamviewer (machine has no keyboard) and steam picked them up

**Comment by seerge** [comment]
@fennectech i don’t really understand what do you mean, but if it works - thats good.

If it doesn’t - you can test different key combinations

**Comment by fennectech** [comment]
TeamViewer is a Remote Desktop app.  I can use it to input Ctrl + 1 from another computer and steam responds to this.   Do you know any tools i can use to debug this?  (Something that shows scan codes in windows perhaps

**Comment by seerge** [comment]
@fennectech well, that's quite exotic way to emit a hotkey combo :)

What I meant try to set an easy to test hotkey combox (like Alt + F4) ``0xA4 0x73``. For me they work fine (i.e. close active window) 

As I have mentioned I have no idea how Steam processes a hotkey, but current way of emitting them (via windows api) is the only way I can add and added.

**Comment by MessiahMozgus** [comment]
This is the one reason I cant use g-helper. I need that xbox guide button function. Absolutely nothing stated above works with Steam. Its really weird. No key combinations. SHIFT+TAB or CTRL+1 just dont work like pressing them on a real keyboard does.
