### ISSUE TITLE
Win key stop working on my laptop i suspect g-helper

### ISSUE THREAD

**Issue by finalmakerr** [seerge/g-helper#1387]
I remember Armoury Crate has Win key toggle but cant find that in g-helper.
win key works fine on external keyboard.
it's been like that since update 0.123 i am on 0.126 now

**Comment by seerge** [comment]
@finalmakerr G-Helper doesn't touch your Win-key. Quit the app - if nothing changes, here you go.

> ## NOTE
> Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. Please respect the time of the developer. Thanks.
