### ISSUE TITLE
AnimeMartix is not shown correctly

### ISSUE THREAD

**Issue by TheDiebOfSpargels** [seerge/g-helper#1388]
Hello Seerge,

first of all thank you for this amazing software and the work you put into it.
Finally removed the ArmoryCrate and saved me like 20° .

Im running the Asus Zephyrus G14 2022 (GA402RJ) (AMD Ryzen 7 6800hs / RX 6700s)
Currently on Windows 11 Pro  (10.0.22621 Build 22621)

The AnimeMatrix feature is not working correctly on my machine.
When choosing the Clock / GIF / Audio Visualizing the leds flash on and off (attached Videos)

Also when completely turned off a few leds flash in the lower right corner. (also attached)

The ROG Logo is working without a flaw tho :D

It would be amazing if you could look into this.
Thanks alot, and have a nice weekend.
 
 Chris

https://github.com/seerge/g-helper/assets/146424897/06da3c58-b939-4508-88dc-a765600f0bdc

https://github.com/seerge/g-helper/assets/146424897/3153374a-a373-493c-9c07-1ac020040542

**Comment by seerge** [comment]
@TheDiebOfSpargels hello. You just have leftovers from Armoury running in background resetting matrix.

Stop Lightning service under windows Services and you will be fine.

**Comment by TheDiebOfSpargels** [comment]
@seerge well, that was fast, solved it.
Thank you very much !

keep up the good work.
