### ISSUE TITLE
[Feature Request] Mapping Fn-F4 to "Open G-Helper Window"

### ISSUE THREAD

**Issue by kosma** [seerge/g-helper#1389]
I'm using M3/M4 for brightness. I would love to be able to access G-Helper via Fn-F4 since Aura is useless on my laptop anyway.

**Comment by seerge** [comment]
@kosma hello, this build should allow g-helper toggle for any hotkey
[GHelper.zip](https://github.com/seerge/g-helper/files/12770771/GHelper.zip)

**Comment by kosma** [comment]
Thank you so much !!
