### ISSUE TITLE
[Feature Request] power profiles for easy one-click settings changes

### ISSUE THREAD

**Issue by Bukethead** [seerge/g-helper#1391]
It would be awesome to have either customizable, or preset power profiles for G-Helper; What I mean by this is, that instead of having to select Performance, GPU, and screen refresh modes individually, you'd specify in a profile which options you want and hit one button to change all three at once. 

just to illustrate a use case, I'd have one for extended battery life, one for performance, and one set in the middle.

**Comment by seerge** [comment]
@Bukethead hello, you can already create as many custom modes (profiles) as you want They include all CPU / GPU settings and fan curves.

The only thing that is separate is refresh rate, as Auto setting in that section does all the switching already when you plug / unplug
