### ISSUE TITLE
Recreation of the constant disk write issue because it was closed without checking first.

### ISSUE THREAD

**Issue by lanmower** [seerge/g-helper#1393]
![image](https://github.com/seerge/g-helper/assets/657315/62a20e16-733f-4ad2-aa37-ac1d1f2a35f9)
its permanently using the disk, please read my report I didn't claim that it's locking disk access, but I do claim that writing or reading at least once a second will affect battery life.

this is a screenshot of the process running

![image](https://github.com/seerge/g-helper/assets/657315/cde143e7-e48a-40ad-b3f1-f9f40225b83a)

and this is 5 seconds later

![image](https://github.com/seerge/g-helper/assets/657315/8271988f-a2e7-415c-9e1e-977cf68a544f)

it is incurring io writes and io others.

I don't know the details, but if its writing to the same space over and over again, how long before it reaches 5 million and kills the ssd? 60 days unless your manufacturer protects against it with 3d spreading or something.

**Comment by seerge** [comment]
@lanmower hello,

As I have answered in previous issue G-Helper doesn't write anything constantly to your SSD. App's code is open, **and therefore can be monitored** from A to Z.

To "check" issue you need to provide a clear and reproducible scenario. You didn't provide log (where i would be able to check at least what app was writing in this log itself)

I'm not able to recreate your explanation, for me app stays on 0 writes almost all the time (except i intentionally start spamming some mode changes or so)
![Screenshot 2023-09-30 103234](https://github.com/seerge/g-helper/assets/5920850/476d5909-8e53-4b7a-8328-8bc73c19900f)

So please provide more debug information of what exactly app is writing in your situation.

**Comment by seerge** [comment]
@lanmower 

> I don't know the details, but if its writing to the same space over and over again, how long before it reaches 5 million and kills the ssd? 60 days unless your manufacturer protects against it with 3d spreading or something.

I would like to receive a valid proof on this matter as well (especially gaining some raw access to SSD bypassing it's internal controller)

**Comment by seerge** [comment]
App's activity with disk reads (and writes) check timestamps
![Screenshot 2023-09-30 111310](https://github.com/seerge/g-helper/assets/5920850/3f664917-e491-45ae-bd13-1310736edf01)

If you would compare it with general amount of disk writes windows and all it's apps do per second, it's literally nothing.

**Comment by lanmower** [comment]
@seerge the proof is that if there is one write a second (which there was every second, writing never ever drops to 0.0), then 5 million seconds passes in 60 days.

do you want me to record a video for you? I've already given you the screenshots of the application itself doing disk writes, windows wont attribute system writes to the app

**Comment by lanmower** [comment]
there you go, writing writing writing
https://github.com/seerge/g-helper/assets/657315/d8b49554-d766-43fd-91cb-839dde2a9351

**Comment by seerge** [comment]
@lanmower you can check what kind of writes is that via Process Monitor

**Comment by lanmower** [comment]
do you want me to find out for you what kind of writes your program is making with a program called process monitor?

**Comment by lanmower** [comment]
![image](https://github.com/seerge/g-helper/assets/657315/ea323a70-1646-497f-aace-7d8ddfbdd573)
there you go, downloaded it

**Comment by lanmower** [comment]
there's a whole lot of them

**Comment by seerge** [comment]
@lanmower i don’t see a single file write on your screenshot :)

**Comment by lanmower** [comment]
what do you want me to do then, please instruct me

**Comment by seerge** [comment]
@lanmower filter file writes that happen every second as you say (while app is iddle)

**Comment by lanmower** [comment]
![image](https://github.com/seerge/g-helper/assets/657315/5e8e2a57-5397-4c47-96d6-ceef0f8af9e4)
ok I've filtered by app name and scrolled, this appears to be a file write

**Comment by seerge** [comment]
@lanmower i see only single write to a log (again as i have explained on multiple occasions)

I would like to see 

1. All file writes for at least 10 consecutive seconds (while app is idle) 
2. Log file itself that was asked already

**Comment by lanmower** [comment]
Sure I'll give you the log itself, the level of sys info I'm expecting to expose is kind of intrusive but I'm happy to help

**Comment by lanmower** [comment]
[Logfile.LOG](https://github.com/seerge/g-helper/files/12774993/Logfile.LOG)
renamed pml to log

**Comment by lanmower** [comment]
Should I be sharing the logs? they appear to say TUF RGB and some hex

**Comment by seerge** [comment]
@lanmower in your ProcessMonitor log i see that it writes app log once per 2 seconds. It could be that there is some even happening in the system in your situation

Can you upload the app log file I have asked before ? ``%appdata%\GHelper\log.txt``

**Comment by lanmower** [comment]
Yes, as described in my previous comment, it says TUF RGB and some hex... 
9/30/2023 4:37:53 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:37:55 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:37:57 PM: TUF RGB = B4-00-E0-F0-00-00 : OK
9/30/2023 4:37:59 PM: TUF RGB = B4-00-E0-F0-00-00 : OK
9/30/2023 4:38:01 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:38:03 PM: TUF RGB = B4-00-E0-F0-00-00 : OK
9/30/2023 4:38:05 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:38:07 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:38:09 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:38:11 PM: TUF RGB = B4-00-E0-F0-00-00 : OK
9/30/2023 4:38:13 PM: TUF RGB = B4-00-E0-F0-00-00 : OK
9/30/2023 4:38:15 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:38:17 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:38:19 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:38:21 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:38:23 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:38:25 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:38:27 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:38:29 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:38:31 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:38:33 PM: TUF RGB = B4-00-D6-EB-00-00 : OK
9/30/2023 4:38:35 PM: TUF RGB = B4-00-D6-EB-00-00 : OK

**Comment by lanmower** [comment]
Alright, since it looked like a color code, I figured it must have something to do with the keyboard... I switched heatmap to static and it stopped writing the log file

**Comment by seerge** [comment]
@lanmower yes, it's a color code command, from your Heatmap backlight settings.

If you would simply follow issue guide and post a log instead of fighting and accusing me here it would be 10 times easier to figure out.

This build won't be writing log entries for Heatmap color changes : 
[GHelper.zip](https://github.com/seerge/g-helper/files/12775380/GHelper.zip)

Closing as completed.
