### ISSUE TITLE
Immediately Crashes upon opening

### ISSUE THREAD

**Issue by lavahawk** [seerge/g-helper#1396]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**
App is crashing immediately upon launch. Occasionally give popup "index is out of range".

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/12775917/log.txt)

**Event Viewer**
Error	9/30/2023 10:03:35 PM	Application Error	1000	Application Crashing Events
-
Faulting application name: GHelper.exe, version: 0.126.0.0, time stamp: 0x64e841c5
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2215, time stamp: 0x83983b0b
Exception code: 0xe0434352
Fault offset: 0x000000000006531c
Faulting process id: 0x0x32FC0
Faulting application start time: 0x0x1D9F40B7B3500E4
Faulting application path: C:\Users\2awso\Downloads\GHelper.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 01eecdf3-f959-455e-b7fc-113b0123f13e
Faulting package full name: 
Faulting package-relative application ID: 

Error	9/30/2023 10:03:35 PM	.NET Runtime	1026	None
-
Application: GHelper.exe
CoreCLR Version: 7.0.22.51805
.NET Version: 7.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AsusACPI.SetFanRange(AsusFan device, Byte[] curve) in D:\a\g-helper\g-helper\app\AsusACPI.cs:line 379
   at GHelper.Mode.ModeControl.AutoFans(Boolean force) in D:\a\g-helper\g-helper\app\Mode\ModeControl.cs:line 152
   at GHelper.Mode.ModeControl.SetPerformanceMode(Int32 mode, Boolean notify) in D:\a\g-helper\g-helper\app\Mode\ModeControl.cs:line 90
   at GHelper.Mode.ModeControl.AutoPerformance(Boolean powerChanged) in D:\a\g-helper\g-helper\app\Mode\ModeControl.cs:line 40
   at GHelper.Program.SetAutoModes(Boolean powerChanged) in D:\a\g-helper\g-helper\app\Program.cs:line 187
   at GHelper.Program.Main(String[] args) in D:\a\g-helper\g-helper\app\Program.cs:line 100

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Asus Zephyrus G15 GA503RM

**Asus software**
- Deleted Armoury Crate
- Deleted MyASUS
- Other Asus services running in background (Yes) but I don't know how to stop them without G-helper

**Additional context**

**Comment by lavahawk** [comment]
I might have fixed this just by deleting the config file in appdata

**Comment by seerge** [comment]
@lavahawk hello,

Crash was coming from incomplete (or absent) fan curve in a ``config.json`` (did you manually edit it?)

Anyway this build should prevent exception even for that situation
[GHelper.zip](https://github.com/seerge/g-helper/files/12776669/GHelper.zip)

**Comment by lavahawk** [comment]
Nope I never manually edited config.json, I didn't even know it existed until finding the log file for this. Thanks for the help.
