### ISSUE TITLE
Fan Curve

### ISSUE THREAD

**Issue by Akalikaton** [seerge/g-helper#1398]
Thanks for your work first. It is very helpful for me to minimal my laptop G14 2020.I am a student in Germany and not very good at english, please forgive me. 

Sometimes I do some light work like read PDF. On that case i will chose silent mode, which turns off the Fanwith 9W CPU when lower than 60 degrees, it seems perfect! 

But now I notice, we can  custom the fan only from 1800RPM. But if I use [atrofac](https://github.com/cronosun/atrofac/tree/release_2020_05_26#atrofac), I can change it from 5% or 10%, which is 1000RPM and almost no sound. Unfortunately, now I use my CPU with 35 degrees and 2500 rpm. Its too loud or normal? (I have open PC and clean the fan with high preasure Airdose.)

So I think it would be better if the fan starts adjusting from 1000 rpm and from a technical point of view it should be easy to take this feature.

**Comment by seerge** [comment]
@Akalikaton hello.

G-Helper uses exactly same approach to set fan curve as atrofac, and under the hood curve is being set in % , not in RPM

For Asus 0% = OFF, and 1% is immediately minimal fan speed , which is around 1800-2000RPM. You can’t set 1000 neither with atrofac nor with g-helper :)

**Comment by Akalikaton** [comment]
Hi, thanks for the reply. You are right, I realized I was fooled by the RPM display on the aida64. When the RPM is 2000, it is basically inaudible. But at 2200 it is very noticeable. In balanced mode, I set all 20 to 50 degrees to 1% and it worked fine.

I replaced the Honeywell 7950 at 2022 and it works great. Maybe I need to consider greasing the fan bearings or replacing the fan now, after all it has been working for three years.

**Comment by seerge** [comment]
@Akalikaton sometimes i have a feeling that fan sensor is actually also lying, as on my G14 2022 1800RPM is literally silent, while 2200RPM is indeed much more audible.

But since fan sensor reports values in RPMs, i take it for granted :) and therefore calibrated y-axis on fan chart just to match those RPMs :)

**Comment by seerge** [comment]
@Akalikaton Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks

**Comment by Akalikaton** [comment]
Hi, yeah, i am glad to test it. It is my pleasure to contribute.
