### ISSUE TITLE
No cpu temp

### ISSUE THREAD

**Issue by MGSDS** [seerge/g-helper#140]
**Describe the bug**
There is no cpu temp shown on asus rog strix scar 15(2022)

**Expected behavior**
Cpu temp is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/40380619/227733265-e829f324-4618-47f4-8735-c95a41ab286a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - asus rog strix scar 15(2022) g533zx

**Comment by seerge** [comment]
You  should check if "Thermal Zone Information", "Temperature", @"\_TZ.THRM" is available in performance monitor on windows. App gets temperature from there.

**Comment by seerge** [comment]
Closed due to absence of an issue in the app.
