### ISSUE TITLE
Are you sure all services disabled? Now it's not working and even the slow iGPU takes over except during high load games.

### ISSUE THREAD

**Issue by YomamaNow** [seerge/g-helper#1403]
I have asus g14 amd processor and radeon graphics. i kept some services running and i think it used to work, but then I also saw that you 're supposed to turn off access to the computer's armoury interface from the bios, which I did, and I also shut down all asus and armoury services, including even armoury control interface service. I have the  latest ASUS System Control Interface driver, but I know of no corresponding  service to see if that's running (all that might are off). What do I do? Thanks.

PS: This is WITH it on turbo, ultimate, and all cpu overclocks (boosts) OFF.

**Comment by seerge** [comment]
@YomamaNow I didn't really get your question

You can stop/disable and start/enable set of asus services via Extra. Then you can just verify that via windows Services app (by looking at their status)

But I don't say that you need to disable "Armoury Crate control interface" in BIOS tho :) you can keep it ON

**Comment by YomamaNow** [comment]
thank you. does your software need armoury control interface at least from the bios? Cuz I've just kept it off.

**Comment by seerge** [comment]
@YomamaNow generally speaking - no, it doesn’t need that.

But I remember someone with old G15 model was saying that disabling AC in bios stopped custom fan curves from working (while rest worked ok)

So it’s safe to keep it on, it doesn’t harm :)
