### ISSUE TITLE
ASUS laptop RGB keyboard control

### ISSUE THREAD

**Issue by andrew-fletcher-asus** [seerge/g-helper#1404]
**Is your feature request related to a problem? Please describe.**
Can you add in some feature around setting up the RGB keyboard lights? I like the standard functions you have like static, rain, etc but can you add in something like armour create so I can select just 3 or 4 keys (WASD) and change these to blue and the rest is red for example. I did like having just the keys I use within my games to be different colour but I hate armour create it does the keyboard bits OK, but Ghelper is far superior on the temp, watts, fans speed control, etc

**Describe the solution you'd like**
As above

**Describe alternatives you've considered**
I've tried OpenRGB but this is more for keyboards, mouses, RBG in the case, but doesn't support keyboards within the laptop :(

**Additional context**

**Comment by seerge** [comment]
@andrew-fletcher-asus hello, 

I don't have any device with per-key backlight support. Therefore I can't add it anyhow.
Just in case, only (some) ROG Strix models support per-key RGB, the rest (vast majority) - don't.

If you really want - you can look at sources of OpenRGB and try to implement per-key lightning by yourself and do a PR

OR

Just disable [G-Helper's RGB initialization ](https://github.com/seerge/g-helper#skip-keyboard-aura-initialisation-on-startup) and use OpenRGB to set whatever key colors you want ;)

**Comment by andrew-fletcher-asus** [comment]
Thank you @seerge
