### ISSUE TITLE
Not working: "skip_hotkeys":1, 

### ISSUE THREAD

**Issue by Creolord** [seerge/g-helper#1405]
I'm using key binding "Ctrl + Shift + F12" in my work.
But with GHelper running, only its window opens.
Adding "skip_hotkeys":1, to config.json does not change anything, the GHelper window still opens.

Here's appropriate part of the config.json file:

{
  "ui_mode": "dark",
  "skip_hotkeys": 1,
  "performance_mode": 2,
...

**Comment by seerge** [comment]
@Creolord hello, try to set 

```
"keybind_app" : <SOMETHING>,
```

Where <SOMETHING> is a code for key different from F12  
List of key codes https://www.oreilly.com/library/view/javascript-dhtml/9780596514082/apb.html
