### ISSUE TITLE
G-Helper's run-on-log-in task isn't updated if  its executable is moved

### ISSUE THREAD

**Issue by Varriount** [seerge/g-helper#1410]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**
G-Helper will not update its run-on-log-in task (handled by Task Scheduler) if its executable is moved (and it is set to run on login). More specifically, G-Helper will *only* update its run-on-log-in task if the "Run on Startup" checkbox is un-checked and then re-checked.

**Clear scenario to Reproduce**
1. Download and run G-Helper on a system with no "G-Helper" task in Task Scheduler.
2. Modify G-Helper's settings so that it is set to run on log-in.
3. Exit G-Helper.
4. Move G-Helper's executable.
5. Start G-Helper.
6. Log out.
7. Log in.
8. Notice that G-Helper isn't running.

**Expected behavior**
G-Helper should update its run-on-log-in task when it is starting up and "Run on Startup" is checked.

**App Logs**
Please include and attach log.txt from ``[log.txt](https://github.com/seerge/g-helper/files/12786921/log.txt)``

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Asus Zephrus M16

**Asus software**
- Armoury Crate (installed, disabled)
- MyASUS installed

**Comment by seerge** [comment]
@Varriount hello, this is actually intentional

I have noticed that sometimes people download zip with updates and for example can run exe single time directly from zip (resulting running it from temp folder). Or some similar "strange" situations. 

Therefore I don't want app to override existing startup job that most probably points at some established exe location ;)

**Comment by Varriount** [comment]
It could check that the executable defined by the task actually exists.

**Comment by seerge** [comment]
@Varriount ok, this specific check could be valid

Try this build, it will re-schedule app on startup if ``current path`` != ``scheduled path`` and if ``scheduled path`` doesn't exist

[GHelper.zip](https://github.com/seerge/g-helper/files/12791528/GHelper.zip)
