### ISSUE TITLE
[Feature Request] Restart/Boot Directly to Eco Mode

### ISSUE THREAD

**Issue by XyKER1** [seerge/g-helper#1411]
I know this is a very minor QoL request, but it would still be nice to have it.  Basically, have the ability to boot and restart from Ultimate mode directly to Eco mode.

When I click on Eco mode and restart using the prompt, it just stays in Standard mode until I manually open G-Helper and click on the Eco button again.

Also, it would be nice to have the option for G-Helper to switch to Eco mode on boot, as it always defaults to Standard mode.

Even in standard mode when the GPU is not doing anything, it still draws 18 W of power, which increases CPU temperatures and wastes electricity, so I prefer to stay in Eco mode unless I'm playing games.

**Comment by seerge** [comment]
@XyKER1 hello, you can already "force" Eco mode on boot (if it was last one used) by adding following param to the beginning of ``config.json``:

```
"gpu_mode_force_set" : 1,
```

Let me know if it works for you

**Comment by Scarlaid** [comment]
> @XyKER1 hello, you can already "force" Eco mode on boot (if it was last one used) by adding following param to the beginning of `config.json`:
> 
> ```
> "gpu_mode_force_set" : 1,
> ```
> 
> Let me know if it works for you

It doesn't for me, bootup is still *Standard* despite `"gpu_mode_force_set": 2`, I still have to manually changing it to Eco
My log here [log.txt](https://github.com/seerge/g-helper/files/12791903/log.txt)

**Comment by seerge** [comment]
@Scarlaid what does ``2`` stand for ? you just entered a wrong setting, so of course it doesn't work.

As I have explained - ``"gpu_mode_force_set" : 1,`` option would force GPU mode to Eco if Eco was the last mode used prior to this boot

**Comment by Scarlaid** [comment]
> @Scarlaid what does `2` stand for ? you just entered a wrong setting, so of course it doesn't work.
> 
> As I have explained - `"gpu_mode_force_set" : 1,` option would force GPU mode to Eco if Eco was the last mode used prior to this boot
> 
> P.S. If you want to "override" what app remembers as last used mode you need to adjust it as well :
> 
> ```
> "gpu_mode_force_set" : 1,
> "gpu_mode" : 0,    <---- this param already exists in your config, just set 0 for eco
> ```

Ahh, I misread the "[Custom windows power plans](https://github.com/seerge/g-helper#custom-windows-power-plans-with-each-mode)" part in the document, it worked now, thanks and sorry 😅

**Comment by seerge** [comment]
Assume it's solved then

**Comment by XyKER1** [comment]
I can't restart my PC now but I'm sure this works; I just didn't know that parameter was a thing.  Have you ever thought of putting it in the extra options as a checkbox for people who don't know about this?  It seems like something that's worthy of being in there.

**Comment by seerge** [comment]
@XyKER1 majority of params are actually covered in readme :) this one is very specific and was there for debug reasons.

I can add it too

**Comment by Scarlaid** [comment]
Add it as an option imo 👍

**Comment by XyKER1** [comment]
Hey @seerge, just curious if there is a way to reboot to Ultimate mode next time the PC turns on.  For example, I don't want to restart to Ultimate right now and will have to shut down my PC to go somewhere (since Modern Standby means your battery still drains quickly when sleeping) but would prefer it to turn back onto Ultimate mode.  Right now I would have to restart to Ultimate mode and then shut down, which takes longer.
