### ISSUE TITLE
GPU Core Clock Offset do not apply after reboot

### ISSUE THREAD

**Issue by Stardusstt** [seerge/g-helper#1412]
Related : [https://github.com/seerge/g-helper/issues/347](https://github.com/seerge/g-helper/issues/347)

**Describe the bug**
the GPU Core Clock Offset that set in the UI don't apply after reboot.

Steps:
1. set GPU Core Clock Offset in UI.
2. reboot
3. open g-helper window
4. the GPU Core Clock Offset show the previous values(i.e. 0MHz).

**Expected behavior**
The user-set GPU Core Clock Offset should preserve change after reboot.

**App Logs**
in Additional context

**Desktop (please complete the following information):**
Windows 11 23H2 22631.2338
Zephyrus G15 GA503QR

**Asus software**
- Armoury Crate installed
- MyASUS installed

**Additional context**
Seems g-helper will fail to set the value of GPU Core Clock Offset after reboot (run on startup), because G-Helper not run as admin.
> 2023/10/4 上午 01:36:46: GET GPU CLOCKS: 0, 0

But if I manually close and restart the program, the UAC prompt for admin and things worked as expected (show the correct value which I previously modified).
> 2023/10/4 上午 01:33:05: GET GPU CLOCKS: 100, 0

---
> Reboot (run on startup) -----------------------
2023/10/4 上午 01:35:20: App launched: ROG Zephyrus G15 GA503QR_GA503QR :0.127.0.0en.
2023/10/4 上午 01:35:21: NVIDIA GeForce RTX 3070 Laptop GPU
2023/10/4 上午 01:35:22: CPU: 7 - AMD Ryzen 9 5900HS with Radeon Graphics         - AMD64 Family 25 Model 80 Stepping 0
2023/10/4 上午 01:35:22: AutoSetting for Online
2023/10/4 上午 01:35:22: Optimization service is running
2023/10/4 上午 01:35:22: Mode = 0 : OK
2023/10/4 上午 01:35:22: Eco flag : 0
2023/10/4 上午 01:35:22: Mux flag : -65536
2023/10/4 上午 01:35:22: GET CLOCK LIMIT: 0
2023/10/4 上午 01:35:22: GET GPU CLOCKS: 0, 0
2023/10/4 上午 01:35:22: SET GPU CLOCKS: 100, 0
2023/10/4 上午 01:35:22: \\?\DISPLAY#CMN152A#5&2c3487dd&6&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/10/4 上午 01:35:22: Screen = 165Hz : OK
2023/10/4 上午 01:35:22: ScreenOverdrive = 1 : OK
2023/10/4 上午 01:35:23: USB-KB 0x19B6:5D-BD-01-FF-1E-FF-FF-FF
2023/10/4 上午 01:35:23: USB-KB 2符合 HID 標準的廠商定義裝置\\?\hid#vid_0b05&pid_19b6&mi_00&col03#8&3a080f36&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
2023/10/4 上午 01:35:23: Monitor Power On
2023/10/4 上午 01:35:24: Auto:5A-BA-C5-C4-01
2023/10/4 上午 01:35:24: Auto:5D-BA-C5-C4-01
2023/10/4 上午 01:35:24: UV: -19 OK
2023/10/4 上午 01:36:45: Design Capacity: 90005mWh, Full Charge Capacity: 79553mWh, Health: 0.8838731181601022165435253597%
2023/10/4 上午 01:36:46: Latest version 0.127.0.0
2023/10/4 上午 01:36:46: GET GPU CLOCKS: 0, 0
2023/10/4 上午 01:36:46: GET CLOCK LIMIT: 0

---
> restart the program and the UAC prompt for admin -----------------
2023/10/4 上午 01:33:03: App launched: ROG Zephyrus G15 GA503QR_GA503QR :0.127.0.0en.
2023/10/4 上午 01:33:03: NVIDIA GeForce RTX 3070 Laptop GPU
2023/10/4 上午 01:33:04: CPU: 7 - AMD Ryzen 9 5900HS with Radeon Graphics         - AMD64 Family 25 Model 80 Stepping 0
2023/10/4 上午 01:33:04: AutoSetting for Online
2023/10/4 上午 01:33:04: Optimization service is running
2023/10/4 上午 01:33:04: Mode = 0 : OK
2023/10/4 上午 01:33:04: Eco flag : 0
2023/10/4 上午 01:33:04: Mux flag : -65536
2023/10/4 上午 01:33:04: \\?\DISPLAY#CMN152A#5&2c3487dd&6&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/10/4 上午 01:33:04: \\?\DISPLAY#CMN152A#5&2c3487dd&6&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/10/4 上午 01:33:04: GET CLOCK LIMIT: 0
2023/10/4 上午 01:33:04: GET GPU CLOCKS: 0, 0
2023/10/4 上午 01:33:04: SET GPU CLOCKS: 100, 0
2023/10/4 上午 01:33:04: Screen = 165Hz : OK
2023/10/4 上午 01:33:04: ScreenOverdrive = 1 : OK
2023/10/4 上午 01:33:04: USB-KB 0x19B6:5D-BD-01-FF-1E-FF-FF-FF
2023/10/4 上午 01:33:05: USB-KB 2符合 HID 標準的廠商定義裝置\\?\hid#vid_0b05&pid_19b6&mi_00&col03#8&3a080f36&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
2023/10/4 上午 01:33:05: GET GPU CLOCKS: 100, 0
2023/10/4 上午 01:33:05: GET CLOCK LIMIT: 0
2023/10/4 上午 01:33:05: Monitor Power On
2023/10/4 上午 01:33:06: Auto:5A-BA-C5-C4-01
2023/10/4 上午 01:33:06: Auto:5D-BA-C5-C4-01
2023/10/4 上午 01:33:06: UV: -19 OK
2023/10/4 上午 01:33:06: Latest version 0.127.0.0

**Comment by seerge** [comment]
@Stardusstt you need to schedule app to run as admin then (usually it would resubscribe itself to run as admin automatically tho)

1. Run app as admin
2. Uncheck and check again "Run on startup" checkbox

:)

**Comment by Stardusstt** [comment]
Try but problem same here .
still need to manually restart the program.

---

> 2023/10/4 上午 02:09:20: App launched: ROG Zephyrus G15 GA503QR_GA503QR :0.127.0.0en.
2023/10/4 上午 02:09:20: NVIDIA GeForce RTX 3070 Laptop GPU
2023/10/4 上午 02:09:21: CPU: 7 - AMD Ryzen 9 5900HS with Radeon Graphics         - AMD64 Family 25 Model 80 Stepping 0
2023/10/4 上午 02:09:21: AutoSetting for Online
2023/10/4 上午 02:09:21: Optimization service is running
2023/10/4 上午 02:09:22: Mode = 0 : OK
2023/10/4 上午 02:09:22: Eco flag : 0
2023/10/4 上午 02:09:22: Mux flag : -65536
2023/10/4 上午 02:09:22: GET CLOCK LIMIT: 0
2023/10/4 上午 02:09:22: \\?\DISPLAY#CMN152A#5&2c3487dd&6&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/10/4 上午 02:09:22: \\?\DISPLAY#CMN152A#5&2c3487dd&6&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/10/4 上午 02:09:22: SET GPU CLOCKS: 100, 0
2023/10/4 上午 02:09:22: Screen = 165Hz : OK
2023/10/4 上午 02:09:22: ScreenOverdrive = 1 : OK
2023/10/4 上午 02:09:22: USB-KB 0x19B6:5D-BD-01-FF-1E-FF-FF-FF
2023/10/4 上午 02:09:22: USB-KB 2符合 HID 標準的廠商定義裝置\\?\hid#vid_0b05&pid_19b6&mi_00&col03#8&3a080f36&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
2023/10/4 上午 02:09:22: Monitor Power On
2023/10/4 上午 02:09:23: Auto:5A-BA-C5-C4-01
2023/10/4 上午 02:09:23: Auto:5D-BA-C5-C4-01
2023/10/4 上午 02:09:23: UV: -19 OK
2023/10/4 上午 02:11:50: Latest version 0.127.0.0
2023/10/4 上午 02:11:50: GET GPU CLOCKS: 0, 0
2023/10/4 上午 02:11:50: GET CLOCK LIMIT: 0

**Comment by seerge** [comment]
@Stardusstt from log i see that app actually SETS clocks (and it passes through as otherwise it would be error message in a log)

```
2023/10/4 上午 02:09:22: SET GPU CLOCKS: 100, 0
```

I have no idea what else resets your clocks 2 minutes after

```
2023/10/4 上午 02:11:50: GET GPU CLOCKS: 0, 0
```

Do you have afterburner or any leftovers from Armoury Crate running ? if so AC will RESET your clocks.

**Comment by Stardusstt** [comment]
@seerge 
> I have no idea what else resets your clocks 2 minutes after

That is because I open the g-helper window to check value.
 or are there other ways to check that the GPU Core Clock Offset is applied?

---
details
>  2023/10/4 上午 08:00:08: ------------
2023/10/4 上午 08:00:08: App launched: ROG Zephyrus G15 GA503QR_GA503QR :0.127.0.0en.
2023/10/4 上午 08:00:08: NVIDIA GeForce RTX 3070 Laptop GPU
2023/10/4 上午 08:00:09: CPU: 7 - AMD Ryzen 9 5900HS with Radeon Graphics         - AMD64 Family 25 Model 80 Stepping 0
2023/10/4 上午 08:00:09: AutoSetting for Online
2023/10/4 上午 08:00:09: Optimization service is running
2023/10/4 上午 08:00:09: Mode = 0 : OK
2023/10/4 上午 08:00:09: Eco flag : 0
2023/10/4 上午 08:00:09: Mux flag : -65536
2023/10/4 上午 08:00:09: \\?\DISPLAY#CMN152A#5&2c3487dd&6&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/10/4 上午 08:00:09: \\?\DISPLAY#CMN152A#5&2c3487dd&6&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/10/4 上午 08:00:09: GET GPU CLOCKS: 0, 0
2023/10/4 上午 08:00:09: SET GPU CLOCKS: 100, 0
2023/10/4 上午 08:00:09: Screen = 165Hz : OK
2023/10/4 上午 08:00:09: ScreenOverdrive = 1 : OK
2023/10/4 上午 08:00:10: USB-KB 0x19B6:5D-BD-01-FF-1E-FF-FF-FF
2023/10/4 上午 08:00:10: USB-KB 2符合 HID 標準的廠商定義裝置\\?\hid#vid_0b05&pid_19b6&mi_00&col03#8&3a080f36&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
2023/10/4 上午 08:00:10: Monitor Power On
2023/10/4 上午 08:00:11: Auto:5A-BA-C5-C4-01
2023/10/4 上午 08:00:11: Auto:5D-BA-C5-C4-01
2023/10/4 上午 08:00:11: UV: -19 OK

---open g-helper window

> 2023/10/4 上午 08:02:22: GET GPU CLOCKS: 0, 0
2023/10/4 上午 08:02:22: GET CLOCK LIMIT: 0
2023/10/4 上午 08:02:23: Latest version 0.127.0.0

**Comment by seerge** [comment]
@Stardusstt opening g-helper window doesn’t reset your clocks

**Comment by seerge** [comment]
You have mentioned that 
> Asus software -> Armoury Crate installed

Manually go to windows Services app and stop Armoury Crate service. And then restart your laptop :)

**Comment by Stardusstt** [comment]
ok, problem solved!👍
I'm looking forward to Microphone modes being implemented so I can uninstall the Armory Crate.

**Comment by Stardusstt** [comment]
ok, problem solved!👍
I'm looking forward to Microphone modes being implemented so I can uninstall the Armory Crate.

**Comment by seerge** [comment]
@Stardusstt microphone modes are covered here https://github.com/seerge/g-helper/issues/18

Many models have an option available under Realtek control panel, some don't (and here i can't help cause apparently asus use some proprietary software for that instead)
