### ISSUE TITLE
[BUG REPORT] Incorrect Bindings on Tuf A15 2021 with Fn lock enabled

### ISSUE THREAD

**Issue by aliazhar-id** [seerge/g-helper#1413]
**Describe the bug**
When Fn lock is disabled, all the F1-12 hotkeys work as expected **except F6 (the screen doesn't turn off and does nothing)**, however when Fn lock is enabled the behaviour for some keys is incorrect

- F1-5: works as expected
- F6 should turn the display off,  but pressing it opens the snipping tool
- F7 and F8 have behaviour inverted, F7 should reduce brightness but it increases it, vice versa for F8 where it should increase the brightness but reduces it
- F9-12 works as expected

**Clear scenario to Reproduce**

1. Enable Fn lock with Fn+C
2. Use the Fn keys

**Desktop (please complete the following information):**

OS: Windows 11
Tuf A15 2021 FA506IC

**Asus software**
- NA

Attaching a pic of the laptop's keyboard for reference
![image](https://user-images.githubusercontent.com/37792939/258202679-d280c557-1137-4738-9571-8fd3703c358b.png)

my case is similar to #990 issue but there are different cases so I recreated it and copied some. and this case also happened to my friend's TUF F15 2020

**Comment by seerge** [comment]
@aliazhar-id hello,

This build should have correctly working F7/F8
[GHelper.zip](https://github.com/seerge/g-helper/files/12801139/GHelper.zip)

As for F6 - all newer models use F6 for PrintScreen, isn't it better and more useful?
