### ISSUE TITLE
Keyboard backlight animation

### ISSUE THREAD

**Issue by ArthurCyy** [seerge/g-helper#1420]
**Is your feature request related to a problem? Please describe.**
My laptop model is ROG Strix G614JV, it has a keyboard with only four zones of RGB instead of single key RGB, so when adjusting the laptop keyboard backlight animation in G-Helper a few of these options (Star, Rain, Highlight, Laser, Ripple, Comet, Flash) are not available (the keyboard backlight will be stuck after selecting these options), is it possible to directly hide these unavailable options in the laptop keyboard backlight animation?

**Describe the solution you'd like**
Identify models with four zones of RGB and hide unavailable options in the laptop keyboard backlight animation.

**Describe alternatives you've considered**
Provides the option to hide specific keyboard backlight animations.

**Additional context**

**Comment by seerge** [comment]
@ArthurCyy hello, this build should hide ``Star ... Flash`` modes from dropdown for your model
[GHelper.zip](https://github.com/seerge/g-helper/files/12822942/GHelper.zip)
