### ISSUE TITLE
Keyboard Backlight Settings Does Not Match Model TUF DASH F15 (2022)

### ISSUE THREAD

**Issue by chislon** [seerge/g-helper#1425]
**Is your feature request related to a problem? Please describe.**
Laptop keyboard is not RGB, but RGB options appear in options, model is FX517ZC

**Describe the solution you'd like**
Toggle RGB keyboard options off

**Describe alternatives you've considered**
N/A

**Additional context**
https://wiki.archlinux.org/title/ASUS_TUF_DASH_F15_(2022)#:~:text=on%20these%20laptops.-,Keyboard%20RGB%20control,-The%20keyboard%20does

**Comment by seerge** [comment]
@chislon hello, this build should hide color selection and unsupported animation modes for FX517Z

[GHelper.zip](https://github.com/seerge/g-helper/files/12828957/GHelper.zip)
