### ISSUE TITLE
Laptop Backlight

### ISSUE THREAD

**Issue by ArthurCyy** [seerge/g-helper#1428]
**Describe the bug**
My laptop only has backlight for the keyboard and lightbar, but the laptop backlight sometimes comes up with a four-part setting (keyboard, logo, lightbar, lid), sometimes only one.

**Clear scenario to Reproduce**
1. Go to 'G-Helper'
2. Click on 'Extra'
3. It's always been these two conditions. Sometimes comes up with a four-part setting (keyboard, logo, lightbar, lid), sometimes only one.

**Expected behavior**
Only the keyboard and lightbar settings appear.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12827860/log.txt)

**Screenshots or screencasts**
<img width="374" alt="1" src="https://github.com/seerge/g-helper/assets/37627147/896a7cb7-111a-4716-bcb7-bd72bbea0c03">
<img width="370" alt="2" src="https://github.com/seerge/g-helper/assets/37627147/1ea418fd-d091-419a-b6a8-832591eab080">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: ROG Strix G614JV

**Asus software**
- ASUS Hotplug Controller
- ASUS Monitor Control

**Comment by seerge** [comment]
@ArthurCyy hello, this build should hide Logo & Lid columns for your device under Extra
[GHelper.zip](https://github.com/seerge/g-helper/files/12828858/GHelper.zip)

**Comment by ArthurCyy** [comment]
@seerge Thank you! But there is a small problem: the word "Keyboard" is not displayed.
<img width="375" alt="1" src="https://github.com/seerge/g-helper/assets/37627147/4061b58b-480b-4bda-bd14-a346afb22fc7">

**Comment by seerge** [comment]
@ArthurCyy this should build should show label
[GHelper.zip](https://github.com/seerge/g-helper/files/12829600/GHelper.zip)
