### ISSUE TITLE
FN lock Issue

### ISSUE THREAD

**Issue by Niloy-Sarker** [seerge/g-helper#1429]
**Describe the bug**
FN-Lock does not work as expected.

**Clear scenario to Reproduce**

When Fn-Lock enabled using FN+C:

1. F1-5: works as expected
2. F6 should turn the display off, but pressing it opens the snipping tool
3. F7 and F8 have behaviour inverted, F7 should reduce brightness but it increases it, vice versa for F8 where it should increase the brightness but reduces it.
4. F12 should toggle airplane mode on/off but does nothing.

When Fn-Lock disabled:

All Fn+key works as expected except FN+F10. It should toggle touchpad on/off, but the behavior is random. When trackpad is on, first and second FN+F10 keypress remains trackpad on, then off then on.
Most of the time the pattern is: on-on-off-on-on-off. But sometimes the pattern also changes (sorry could not figure it out when it changes pattern)
Sometimes, it works fine as well.

**Trackpad toggle works fine when Fn-lock enabled.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12827913/log.txt)

**Screenshots or screencasts**

https://github.com/seerge/g-helper/assets/69155993/5cdefcc0-ae1e-49a9-ac10-d67a7b2cd72f

keyboard layout:
![image](https://github.com/seerge/g-helper/assets/69155993/20c82694-bcd4-4c59-a51c-9ff9435b5c48)

**Desktop:**
 - OS: Windows 11
 - Laptop model: TUF F15 FX506LH 

**Asus software**
- Armoury Crate uninstalled
- MyASUS installed
- Other Asus services NOT running in background
- G-Helper V0.128.0

**Also, a small feature request**
If a real-time clock speed of CPU and GPU added along the side of CPU and GPU temperature and fan speed, it would be great.

**Comment by seerge** [comment]
@Niloy-Sarker hello

This build should have correct brightness behavior for ``F7/F8``

[GHelper.zip](https://github.com/seerge/g-helper/files/12828917/GHelper.zip)

As for ``F6`` - all new models do a ``PrintScreen`` action for ``F6``, isn't it better and more useful? (this is a [duplicate ](https://github.com/seerge/g-helper/issues/1413)) 

As for your ``Fn+F10`` behavior, when Fn-lock is OFF - that action is handled by keyboard on hardware level (it emits a command to touchpad by itself, you can't intercept  or control it). And when Fn-lock is ON app literally processes F10 by itself, and apparently does it better than asus :) I can't really change that

**Comment by Niloy-Sarker** [comment]
@seerge Thanks for responding.
On windows 11, PRTSC button on numpad does the same thing.Thats why I was asking.

**Comment by Deep-Duck-Fantasy** [comment]
Thank the author so much for this amazing widget,and I have met similar problem as mentioned before.
When Fn locked, only press F6 can't work,still should use "fn + f6" to start screenprint.
And,when Fn locked,I can't use any original fn1-fn12. For example, I assume that when Fn locked, then I press "fn+f1", it may work as primary “f1”(open the help information in most apps), but it doesn't.
My model is GV301RA, hoping for your reply.
