### ISSUE TITLE
flow x16 in tent/tablet mode.

### ISSUE THREAD

**Issue by musabr274** [seerge/g-helper#1431]
The flow x16 annoyingly automatically goes in to turbo mode on the fans if you use it in tent/tablet mode while gaming. In laptop mode the laptop is significantly quieter and less hot. Someone asked an asus technician and apparently in the bios it is set to turbo fans when it is in tent/tablet mode. Any way G-helper can override this? it is annoyingly loud when playing games and I much prefer the noise when its in laptop mode.

**Comment by seerge** [comment]
@musabr274 hello, G-Helper obviously doesn't set a turbo mode when your laptop enters a tablet mode :)

If it's like that on hardware / bios level, then probably this is how things are. Try to change mode to Balanced / Silent when laptop is already in tablet mode, and see if it makes a difference

There is nothing else I can do here.
