### ISSUE TITLE
Mapping a key comb to Open G-Helper window

### ISSUE THREAD

**Issue by odano27** [seerge/g-helper#1433]
I'm using an external keyboard with my touchscreen device in keyboard-down mode, so I don't have the M4 key that opens the G-Helper window.

Is it possible to implement the feature in the title? If possible, it'd be nice to make the key comb editable in the config.json file. If this issue could be addressed with external key mappers like AutoHotkey or PowerToys, could you point me to what command I should use?

Thanks in advance. I only heard of this recently when asking around on Reddit after an AC update increases idle power consumption by 50%, ruining the battery life.

**Comment by seerge** [comment]
@odano27 hello.
It already exists ``Ctrl + Shift + F12``, and can be changed https://github.com/seerge/g-helper#extra-keybindings
