### ISSUE TITLE
A new method of controlling fans

### ISSUE THREAD

**Issue by wgetnz** [seerge/g-helper#1435]
When I was using g-helper to control fan speed, I received an error "ASUS BIOS rejected fan curve". I reviewed many issues and realized it was due to hardware not being supported. However, when I used MY ASUS for fan diagnosis, I discovered that MY ASUS could control fan speed. I searched through a multitude of projects and found that the project https://github.com/Karmel0x/AsusFanControl is effective. Below is the introduction of the project:
----------------------------------------------------------------------------------------------------------------------------
Run
Command line activation: AsusFanControl.exe <fan speed percentage>
Command line deactivation: AsusFanControl.exe 0
GUI: AsusFanControlGUI.exe

AsusFanControlGUI

Why is it needed?
My laptop does not support the Fan Profile option, but it often overheats. I looked for apps to control the fans, but none worked.

Compatibility
This program should work on any laptop with x64 windows where Fan Diagnosis in MyASUS application is working as it is using the same library.

The included AsusWinIO64.dll is licensed to (c) ASUSTek COMPUTER INC., which can be found in C:\Windows\System32\DriverStore\FileRepository\asussci2.inf_amd64_-\ASUSSystemAnalysis\ if you have MyASUS installed.
----------------------------------------------------------------------------------------------------------------------------

It worked on my FX706HM notebook, although I don't have custom curves in armoury. I hope you can integrate this feature into g-helper, so that machines not supporting fan control can gain the fan control functionality.thx.

**Comment by seerge** [comment]
@wgetnz for me that app doesn't work at all 

From what I understood tho, it just lets you set a "test" (or overboost) mode for fans in a laptop same as MyASUS does. It's designed for testing fans , not for using like that in a long term ;)

That mode just runs fans at max speed, and can be turned on w/o a  single app at all by a simple PowerShell command as admin : 

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110013, 1)
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110014, 1)
```


```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110013, 0)
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110014, 0)
```

I don't plan adding it in the app, as there is no sense for that .

Therefore closing as not planned

**Comment by 228864718** [comment]
> @wgetnz for me that app doesn't work at all
> 
> From what I understood tho, it just lets you set a "test" (or overboost) mode for fans in a laptop same as MyASUS does. It's designed for testing fans , not for using like that in a long term ;)
> 
> That mode just runs fans at max speed, and can be turned on w/o a single app at all by a simple PowerShell command as admin :
> 
> ```
> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110013, 1)
> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110014, 1)
> ```
> 
> ```
> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110013, 0)
> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110014, 0)
> ```
> 
> I don't plan adding it in the app, as there is no sense for that .
> 
> Therefore closing as not planned

this app in my laptop is work very good, and it can  runs fans at 40-100% ！ 。

![image](https://github.com/seerge/g-helper/assets/25221660/1c4a1cff-e2e9-431e-9135-a8280bcff7fe)

**Comment by wgetnz** [comment]
> > @wgetnz for me that app doesn't work at all
> > From what I understood tho, it just lets you set a "test" (or overboost) mode for fans in a laptop same as MyASUS does. It's designed for testing fans , not for using like that in a long term ;)
> > That mode just runs fans at max speed, and can be turned on w/o a single app at all by a simple PowerShell command as admin :
> > ```
> > (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110013, 1)
> > (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110014, 1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110013, 0)
> > (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110014, 0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't plan adding it in the app, as there is no sense for that .
> > Therefore closing as not planned
> 
> this app in my laptop is work very good, and it can runs fans at 40-100% ！ 。
> 
> ![image](https://private-user-images.githubusercontent.com/25221660/287155254-1c4a1cff-e2e9-431e-9135-a8280bcff7fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDQ0NzAsIm5iZiI6MTcwMTc0NDE3MCwicGF0aCI6Ii8yNTIyMTY2MC8yODcxNTUyNTQtMWM0YTFjZmYtZTJlOS00MzFlLTkxMzUtYTgyODBiY2ZmN2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAyNDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYTFjMGUxMmUwMGNjYTk2OWI0MDA1Nzk1OTkyNmUwN2JkZmQ3MTU0ODllNzQ5MjUzN2ZmNDExNzQwMjk4YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gXLKuelg_idTL0OxwBonqNAPxImlqXjfYhpyx0YTeIo)

Yes, but looking at seerge's reply, I don't want to explain too much...
