### ISSUE TITLE
Fan control glitched and running at 52434800RPM

### ISSUE THREAD

**Issue by ankur-612** [seerge/g-helper#1437]
**Describe the bug**
Fan speeds glitched and running at maximum.
This issue began a couple of months ago after the v0.7 or v0.8 update

**Clear scenario to Reproduce**
Steps to reproduce the behaviour:
1. Open any game that requires high usage
2. Play for 30min -1 hour
3. Fan Speed will now show 100% or 52434800 RPM
4. This also happens when the laptop is woken up from sleep.

**Expected behaviour**
Fan Speed should stay within the limits.
GPU fan stabilises on its own sometimes but the CPU fan does not.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12838183/log.txt)
Uploaded the config.json file as .txt -> 
[config as txt.txt](https://github.com/seerge/g-helper/files/12838185/config.as.txt.txt)

**Screenshots or screencasts**
(https://imgur.com/a/pb0dfk1) 
OR 
![Screenshot 2023-10-07 211714](https://github.com/seerge/g-helper/assets/141929387/63214815-4e03-4b5f-b784-c4e03f714c24)
![Screenshot 2023-10-07 205729](https://github.com/seerge/g-helper/assets/141929387/1def8d8c-704a-48db-b3c4-c283c235ecbc)

**Desktop (please complete the following information):**
 - OS: Windows 11 [Build 22621.2283]
 - Laptop model: ASUS TUF FX505DT

**Asus software**
- No Asus Software or services running in the background.

**Comment by seerge** [comment]
@ankur-612 hello,

It looks more like fan sensors report nonsense in your case (your fans clearly don't do that crazy number of RPMs). App just shows what it gets as is. 

I didn't change anything related to fans neither month ago, nor 6 months ago, it stays same. 

Furthermore [fans are controlled by bios](https://github.com/seerge/g-helper#how-does-g-helper-control-my-fan-speeds) (by predefined fan curves baked with each mode), not by the app

Closing this, as there is nothing that you can "fix" here :)
