### ISSUE TITLE
Feature Request: Lock Screen Hertz Mode

### ISSUE THREAD

**Issue by JustinMacGregor** [seerge/g-helper#1438]
**Is your feature request related to a problem? Please describe.**
Yes, when I use the optimized preset, the screen refresh rate frequently switches to 60Hz. 

**Describe the solution you'd like**
I would like a feature that allows me to lock the screen refresh rate at 144Hz and keep it at that rate, regardless of the selected preset.

**Describe alternatives you've considered**
An alternative could be having a lock button next to the laptop screen options that locks the screen refresh rate at the given hz amount.

**Additional context**
This feature would provide a better user experience as it would allow for smoother visuals at all times.

**Comment by seerge** [comment]
@JustinMacGregor hello. 

Optimized GPU mode has nothing to do with refresh rate. It just turns on dGPU when plugged in and off when on battery, that's it :) 

Just set refresh rate to 144 in display section and keep it like that.

If it changes by itself - it means there is some other app on your laptop responsible for this.  Most probably it's [Smart Display Control from asus that you need to disable as readme says](https://github.com/seerge/g-helper#recommendations-optional) :)
