### ISSUE TITLE
Fan curves - Coupled mode possible?

### ISSUE THREAD

**Issue by x-iso** [seerge/g-helper#1439]
**The problem with current custom fan control implementation**
I've noticed that when using custom fan curves in G-Helper, it strictly separates control of the fan on CPU side and GPU side with respective temperatures, and it becomes a problem on systems where heatsink is linked between CPU and GPU or both are sharing same vapor chamber like on Flow Z13. So when dGPU is not active, it doesn't respond to it's fan curve so I have just CPU side fan trying cool down the whole vapor chamber on it's own and it's not doing well at all.

**Proposed solution**
When I disable fan control, cooler on the GPU side kicks in even if GPU is not used, so for systems that share vapor chamber or heatpipes, we need option to set GPU fan to follow CPU fan graph when GPU is not in use, maybe with % reduction of speed overall, considering that with 2 fans you might be fine with less rpm on both.

One way or the other, for devices like Z13 we need both fans to be engaged at all times when they're needed.

**Comment by seerge** [comment]
@x-iso hello, you can't control fans anyhow. They are [controlled by BIOS, even in case of custom fan curves. ](https://github.com/seerge/g-helper#how-does-g-helper-control-my-fan-speeds)

There is nothing that can be done here :)

**Comment by x-iso** [comment]
yet, fan curves work, so the graph is read by BIOS then? It does work different compared to disabled custom fan curves, or is it that the problem lies with inability to 'redirect' temp reading from GPU to CPU on second fan?

**Comment by seerge** [comment]
@x-iso fan curves work, but the way they are being interpreted and how actually fans are being controlled depends on firmware (BIOS).
