### ISSUE TITLE
Missing some options in afterburner for gpu temp/power.

### ISSUE THREAD

**Issue by jzhang802** [seerge/g-helper#144]
They were there when i was using armoury crate.

I see temp in g-helper just fine too.

And those options for gpu2... which i assume is the igpu? its 0% when using in a game.

I assume power is grouped with cpu power?

2022 g14 7600s. 

<img width="290" alt="image" src="https://user-images.githubusercontent.com/20910909/227752066-417b4dbf-891b-42e5-9b05-ae338730cd26.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/20910909/227752111-d32ed3b2-b3bf-40e4-acc9-c0e023482be2.png">

**Comment by seerge** [comment]
G-helper gas nothing to do with afterburner. It’s probably something that armoury has uninstalled .

I would recommend having latest gpu drivers too

Closed due to absence of an issue.
