### ISSUE TITLE
Support for RGB For Wallpaper Engine and/or other RGB controlling apps like openRGB & Reactive rgb keys

### ISSUE THREAD

**Issue by Sanaan01** [seerge/g-helper#1442]
Hi I have the Asus Strix G16 2023 some RGB modes work others do not is Full support possible?

Also this feature I'm missing a lot as Wallpaper engine integration allowed for like audio rgb sync and looked cool.
Reactive keys is also a cool rgb mode. 

I think this should be added as a plugin to ghelper to reduce bloat and let the people decide if they want this feature taking up recourses

**Comment by Sanaan01** [comment]
Oh no worries Thanks for such a great program

The following rgb modes weren't working everything below 

Rain didn't work besides heatmap and strobe

**Comment by seerge** [comment]
@Sanaan01 what specific model do you have? Not all Strix G16 support all modes. I assume they also didn't work for you in Armoury ?

**Comment by Sanaan01** [comment]
Some did but but Armory didnt show  most 

My exact model is
ROG Strix G614JV_G614JV

**Comment by seerge** [comment]
@Sanaan01 your model simply doesn't support them and i have removed unsupported modes in latest release specifically for your model, cause someone else already asked about same thing https://github.com/seerge/g-helper/issues/1420
