### ISSUE TITLE
Switching eco and standard mode back and forth causing crash

### ISSUE THREAD

**Issue by anh-duypham** [seerge/g-helper#1443]
My current spec is ASUS TUF Gaming A16 FA617NS_FA617NS
AMD Ryzen 7 7735HS with Radeon Graphics , RX 7600S
I am having a problem with the eco mode and standard mode in the G-helper. To be specific, every time switching from eco to standard and standard to eco, the laptop just blue screen and reboot, reset every setting in G-helper, the same thing happen with optimize mode. 
[log.txt](https://github.com/seerge/g-helper/files/12850816/log.txt)

**Comment by seerge** [comment]
@anh-duypham hello, 

> To be specific, every time switching from eco to standard and standard to eco, the laptop just blue screen and reboot

Your log actually tells something else. There is a log of entries when GPU is being turned ON or OFF like
```
0/10/2023 08:39:24: GPUEco = 1 : OK
```
After which your computer seem to work for a long time (so it's clearly not "every time")

More over, i see that you were also trying to switch there an back like 20 times (?) in a row. No surprise that eventually windows or GPU drivers went nuts.

There is nothing I can do here , as i don't see anything strange here. GPU swtiching command is same for all models of laptops.

If you experience issues, I would advice to do a clean reinstall of AMD drivers using https://www.amd.com/en/support/kb/faq/gpu-601

**Comment by alibk94** [comment]
@anh-duypham I have the same exact laptop model, I want to ask u some general questions regarding the laptop. Anywhere else I can reach u?
