### ISSUE TITLE
Latest Stable Update Crashing on New Windows 11 Installation

### ISSUE THREAD

**Issue by udegbunamchuks** [seerge/g-helper#1446]
It's been 48hrs since I installed and configured the app properly on my 2020 ASUS G14. I just tried opening the app from the taskbar tray and it crashed showing the error image and text below

I'm running a week old fresh installation of Windows 11 Home 22H2 with no armoury crate. ASUS drivers and MyASUS were automatically installed by Windows Update.

I'm running the latest stable GHelper. Thanks

<img width="331" alt="Microsoft NET Error" src="https://github.com/seerge/g-helper/assets/45827666/0b707d42-4954-4aea-95f9-b3a570a7e589">
<img width="962" alt="Services" src="https://github.com/seerge/g-helper/assets/45827666/d8d4aef6-9412-4091-8b92-4e732ba60acb">

[log.txt](https://github.com/seerge/g-helper/files/12870127/log.txt)

[Microsoft.NET Error LOG.txt](https://github.com/seerge/g-helper/files/12870124/Microsoft.NET.Error.LOG.txt)

**Comment by Kikimahe** [comment]
Have you tried installing [Microsoft.NET7](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.202-windows-x64-installer) again?

**Comment by iChiillz** [comment]
My TUF F15 2022 was running on v0.128, Ghelper was running fine until clicking on 'Updates', which triggered the .NET error. Restarting the app fixed it though.

**Comment by seerge** [comment]
@udegbunamchuks hello, 

From .NET log it looks like your crash is happening somewhere deeply inside .net library itself (i.e. not due to some "bug" in the app). So I can't really "fix" much here

```
   at System.Windows.Forms.Application.get_OpenForms
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at GHelper.Program.SettingsToggle(String action)
```

Given that you have fresh win install, I would advice to reinstall [latest .net 7.0 ](https://dotnet.microsoft.com/en-us/download/dotnet/7.0) , may be it's corrupt on your system or something like that :)

**Comment by udegbunamchuks** [comment]
Thanks everyone. I'll reinstall and see if the problem reoccurs 😊👌
