### ISSUE TITLE
Error with new mouse function

### ISSUE THREAD

**Issue by an0thee** [seerge/g-helper#1447]
The app promted me to update, after that a new button appeared with my mouse ASUS TUF Gaming M5. After clicking I get this:

![weaDOtZHO5](https://github.com/seerge/g-helper/assets/42778023/1528f11d-419e-44b7-bdbc-9ebf38c32473)

Clicking "Continue" or "X" does nothing, clicking "Quit" closes the app

There is my Microsoft.NET error log: [Microsoft.NET7_error.txt](https://github.com/seerge/g-helper/files/12872336/Microsoft.NET7_error.txt)
There is the app log file: [log.txt](https://github.com/seerge/g-helper/files/12872350/log.txt)

My PC: ASUS TUF GAMING A15 FA506QM
OS: Windows 11 Pro 22H2 (build: 22621.2428)

What about ASUS software:
I checked at Settings->Apps by typing "ASUS" and "Armoury", but got nothing, also I don't have MyASUS app.

What I found at Task Manager -> Details
![Taskmgr_Q2sMTBpr3V](https://github.com/seerge/g-helper/assets/42778023/f418169a-3ecd-409b-b4f2-b5c5abb620f8)

And at Task Manager -> Processes
![image](https://github.com/seerge/g-helper/assets/42778023/1c378c1d-478f-487b-81ac-a29ee435e337)

**Comment by seerge** [comment]
@an0thee hello, try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/12872578/GHelper.zip)

**Comment by an0thee** [comment]
> @an0thee hello, try this build [GHelper.zip](https://github.com/seerge/g-helper/files/12872578/GHelper.zip)

It works, thanks!
