### ISSUE TITLE
Zephyrus Duo - Screenpad Toogle only mode

### ISSUE THREAD

**Issue by phu54321** [seerge/g-helper#1450]
**Is your feature request related to a problem? Please describe.**

Screenpad currently alternates between "Brightness 100%", "Hidden (brightness 0%)", "Off". I want an option to alternate only between "On" and "Off".

**Describe the solution you'd like**

I usually set second screen brightness using ScreenXpert button. I don't want g-helper to change the screenpad brightness. I only want to toggle it on/off (for battery)

![image](https://github.com/seerge/g-helper/assets/775265/52ac03ab-ba3d-4dae-ac24-3e1fe4ce57e3)

**Describe alternatives you've considered**

Add `ToggleScreenpad` function to `InputDispatcher.cs`

```c#
        public static void ToggleScreenpad(bool enable)
        {
            string toast;
            if (enable) {
                toast = "On";
                Program.acpi.DeviceSet(AsusACPI.ScreenPadToggle, 1, "ScreenpadOn");
            }
            else {
                toast = "Off"
                Program.acpi.DeviceSet(AsusACPI.ScreenPadToggle, 0, "ScreenpadOff");
            }

            Program.toast.RunToast($"Screen Pad {toast}", delta > 0 ? ToastIcon.BrightnessUp : ToastIcon.BrightnessDown);
        }
```

**Additional context**

Testing available.
If you accept PRs, I'm willing to create one.

**Comment by seerge** [comment]
@phu54321 hello,

So you want to remove one of the steps from the list ? Thing is that current scenario I have recreated according to what another Duo user was asking https://github.com/seerge/g-helper/issues/1215 :) and that will break it

I can add an optional config param, that will allow that. As this is quite specific usecase that you want. 

Will that work ?

**Comment by seerge** [comment]
@phu54321 this build should do the thing. Apparently I did this accidentally by trying to sort [other request ](https://github.com/seerge/g-helper/issues/1491#issuecomment-1771641130)

[GHelper.zip](https://github.com/seerge/g-helper/files/13052383/GHelper.zip)
