### ISSUE TITLE
Brightness control doesnt work while charging 

### ISSUE THREAD

**Issue by T-Bukovy** [seerge/g-helper#1454]
**Describe the bug**
After pluggin my laptop the brighness slider/buttons doesnt do anything and its set to almost the lowest value. On battery it works fine 
When forcing on plugged to use ECO mode it works correctly but on Standart or Ultimate it doesnt work.

**Clear scenario to Reproduce**
1. Plug laptop in
2. Click on F8 button to higher screen brighness or F7 to lower .... it doesnt change 
3. Lowering does nothing too 

**Expected behavior**
Brightness should change, after disconnection it goes back to proper level set before pluggin it 

**App Logs**
12.10.2023 16:54:59: \\?\DISPLAY#BOE0B33#4&330fdc27&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
12.10.2023 16:54:59: \\?\DISPLAY#BOE0B33#4&330fdc27&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
12.10.2023 16:54:59: Screen = 60Hz : OK
12.10.2023 16:54:59: ScreenOverdrive = 0 : OK
12.10.2023 16:55:06: WMI event 88
12.10.2023 16:55:06: WMI event 123
12.10.2023 16:55:06: AutoSetting for Online
12.10.2023 16:55:06: Input: \\?\hid#vid_0b05&pid_19b6&col03#6&19e2ad7&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
12.10.2023 16:55:06: Mode = 0 : OK
12.10.2023 16:55:06: ChargerStatus: 1
12.10.2023 16:55:06: Running eco command 0
12.10.2023 16:55:06: BatteryLimit = 95 : OK
12.10.2023 16:55:06: USB-KB 0x19B6:5D-BD-01-FF-1E-FF-FF-FF
12.10.2023 16:55:06: USB-KB 1046Dodavatelem definované zařízení standardu HID\\?\hid#vid_0b05&pid_19b6&col04#6&19e2ad7&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-00-00-80-40-EB-00-00-FF-FF-FF-00-00-00-00
12.10.2023 16:55:06: GPUEco = 0 : OK
12.10.2023 16:55:07: Eco flag : 0
12.10.2023 16:55:07: Mux flag : 1
12.10.2023 16:55:07: \\?\DISPLAY#BOE0B33#4&330fdc27&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
12.10.2023 16:55:07: \\?\DISPLAY#BOE0B33#4&330fdc27&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
12.10.2023 16:55:07: ScreenOverdrive = 0 : OK
12.10.2023 16:55:07: Auto:5D-BA-C5-C4-00
12.10.2023 16:55:10: NVIDIA GeForce RTX 4050 Laptop GPU
12.10.2023 16:55:39: Key: 32
12.10.2023 16:55:39: Key: 32
12.10.2023 16:55:39: Brightness = 32 : OK
12.10.2023 16:55:39: Brightness = 32 : OK

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Zephyrus G16 GU603ZU (i7 12700h, 4050 with 1200p screen) 

**Asus software**
- Armoury Crate was uninstalled with the proper tool
- MyASUS installed but not running 
- All Services were stopped using g-helper

**Comment by seerge** [comment]
@T-Bukovy hello, from log buttons actually trigger brightness up / down commands. If they don't work - it could be nvidia driver acting.

Check this topic https://github.com/seerge/g-helper/discussions/1042 - this happens if you shut down laptop in eco mode (i.e. with dGPU disabled) and then when it boots, driver may not work properly even if dGPU got enabled after

The "fix" for that is to always shut down in "standard" (or ultimate) modes. There is a special checkbox under Extra that will make sure that happens :)

**Comment by T-Bukovy** [comment]
Sadly, i cant see the check box in the ```Extras```... Why is that? 
![obrazek](https://github.com/seerge/g-helper/assets/86479575/d7ed7748-e239-4981-89f6-d750e3de5528)

**Comment by seerge** [comment]
@T-Bukovy probably cause your model had different name ``GU603Z`` comparing to other G16s (they are ``GU603U``)

Try this build, i have added your device to the list

[GHelper.zip](https://github.com/seerge/g-helper/files/12884456/GHelper.zip)

**Comment by T-Bukovy** [comment]
Yes, this one works :) thank you

**Comment by seerge** [comment]
@T-Bukovy does it help?

**Comment by T-Bukovy** [comment]
@seerge seems like it works ... cant reproduce it anymore even after turning laptop off multiple times
