### ISSUE TITLE
Request for a option to disable the config of keyboard backlight setting

### ISSUE THREAD

**Issue by tanyiok1234** [seerge/g-helper#1455]
Is it possible to add a option to determine if backlight option should be applied or not?
G-helper is consistently overwiriting my config in aura creator on senarios like startup or etc, when I plug-in AC I think resources is not very concerning to me.

**Comment by seerge** [comment]
@tanyiok1234 hello,

You can disable aura settings on startup of the app completely 
https://github.com/seerge/g-helper#skip-keyboard-aura-initialisation-on-startup

And then (unless you manually change modes in dropdown) it won't affect your keyboard anyhow :)
