### ISSUE TITLE
Lower RPM?

### ISSUE THREAD

**Issue by SynStark** [seerge/g-helper#1456]
After update 0.126 I noticed my fans and especially GPU are always on at 2000RPM on idle and it's getting a little annoying because of the fan noise. So my question is:

Is it possible to lower the minimum RPM in the graph Fans+Power Window? The lowest I can go is 1800. So it's either Off or 1800 at the very least, which is still kinda noisy in a quiet room. Can we make the lowest RPM available to be around 1000rpm at least for CPU and GPU?

**Comment by SynStark** [comment]
> @SynStark hello, I haven't changed absolutely anything related to custom fan curves neither in 0.126 nor in any version over last few months :)
> 
> Minimal RPM depends on your specific model. Just set a custom curve point to be as low as possible (but not 0), that would be your minimum RPM. Rest depends on BIOS as it controls the fans.
> 
> Good luck.

I'm using Scar 18 4090.
https://i.imgur.com/GbyB2cS.png
This is how it looks like. CPU,GPU and MID fan, lowest RPM is 1800. So either OFF or 1800 on all 3 of them. So there is no way to lower the minimum RPM limit?

**Comment by seerge** [comment]
@SynStark the Y-axis on fan-curve-editor are "indication" only for convenience, as under the hood fan curves are set in some abstract % (same as it happens in armoury).

When you set curve to lowest non-zero point (i.e. to 1%) that would be your minimum, and you can't set it lower.

You can click on Y-axis to switch to % btw :)

**Comment by SynStark** [comment]
Got it, thank you for all the help and great program!

**Comment by seerge** [comment]
@SynStark Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks

**Comment by SynStark** [comment]
> @SynStark Hello, if you are interested you can try an experimental build with actual "manual" fan control #2272 . Thanks

Oh yeah! I tried that immediately after seeing your message! Thank you for it!

BUT

I uptaded it and now the version is 0.162.1. But when I got to the fans and power options, the minimum RPM is either OFF or 2000. Is it because I'm on balanced mode? Or I'm missing something to see in that window?

I'm attaching a screenshot.

<img width="1114" alt="Untitled" src="https://github.com/seerge/g-helper/assets/140649954/1c3133db-d6d8-451c-b74e-8a54db1ca3b1">

**Comment by seerge** [comment]
@SynStark app sets fan speed in a range from 25% to 100% (its set in percentage points not rpm), as lower speeds seem to behave strangely.

So what you see is approximate min rpm calculated as 25% of a measured maximum

**Comment by SynStark** [comment]
> @SynStark app sets fan speed in a range from 25% to 100% (its set in percentage points not rpm), as lower speeds seem to behave strangely.
> 
> So what you see is approximate min rpm calculated as 25% of a measured maximum
> 
> What is actual minimum fan speed in your case?


The lowest I can set it manually is 2000RPM. Currently in idle and doing absolutely nothing it's showing 1800RPM.

**Comment by seerge** [comment]
@SynStark then it looks about right :) If it would be a gap between y-axis value and actual measurement in something like 500+ rpm it would be a reason to check

**Comment by SynStark** [comment]
> @SynStark then it looks about right :) If it would be a gap between y-axis value and actual measurement in something like 500+ rpm it would be a reason to check

Oh I see. So what did you mean when you said "experimental build with actual "manual" fan control" when still my only option is OFF or 1800?

**Comment by seerge** [comment]
@SynStark "manual" means that app sets fan speed every second, instead of letting BIOS do that.

You can update to latest build from https://github.com/seerge/g-helper/discussions/2272 i have lowered minimum speed to 20% there

**Comment by seerge** [comment]
@SynStark  if you want to you can try build that will allow to set minimum fan speed to as low as 1% :) i wonder if it will affect actual minimum speed in your case or it will stay around 2400RPM or so

[GHelper.zip](https://github.com/seerge/g-helper/files/14746268/GHelper.zip)

**Comment by SynStark** [comment]
Yes, setting the fan speed at 1% stops all fans apparently for me.

![Screenshot 2024-03-25 192312](https://github.com/seerge/g-helper/assets/140649954/fb5d142c-0f3b-4d23-8f70-15381dbc4bfe)

**Comment by seerge** [comment]
@SynStark that’s normal, for me they start spinning from 10% or so
