### ISSUE TITLE
Key combinations in a single Macro key press

### ISSUE THREAD

**Issue by PGRjoystick** [seerge/g-helper#1459]
**Is your feature request related to a problem? Please describe.**
Hi, my laptop Flow X16 2022 (GV601RM) doesn't have a printscreen button. and i always take a screenshot with windows + PrintScreen key combinations. i can set my ROG key to printscreen button, but when i press windows + ROG key to take a screenshot and release a windows keys, the start menu always show up. i also sometimes take a screenshot twice (press ROG Key twice) without releasing the windows keys. but sadly this is doesn't works. i have to release the windows keys and do the combination again which is annoying because of the start menu that always showed up.

**Describe the solution you'd like**
im thinking about implementing a key combination press with a single macro keys (ex. when i press ROG Keys, do the key combination like windows + PrintScreen )

**Describe alternatives you've considered**
well, the alternative one would be prevent a start menu showing up when im releasing windows keys or make a multiple screenshot in a single hold of windows key. but my main solution is always preferred.

**Additional context**
I do Take a full screenshot a lot, A LOT. maybe 1 to 4 screenshot in a single hold of windows key. so this feature would be very helpful to me

**Comment by seerge** [comment]
@PGRjoystick hello

This is already possible, you can make 1, 2 or even 3-key combos for macro keys

Check the readme on how to do that https://github.com/seerge/g-helper#custom-hotkey-actions

**Comment by PGRjoystick** [comment]
Sorry, my bad, i thought setting up custom hotkey action to PrintScreen + windows in g helper doesn't work. because it's just showing up start menu like a single windows key press. its turns out that combo is inverted, it should windows + PrintScreen (0x5B 0x2C)

and i need to disable windows animations to do a fast screenshot (twice or more screenshot in just a second)

Thank you.
