### ISSUE TITLE
Whopss..

### ISSUE THREAD

**Issue by TeccnoW** [seerge/g-helper#146]
Last update bug i think.

![image](https://user-images.githubusercontent.com/128497481/227774036-0dd1d7c8-a238-437e-abd7-526ffb1f7b96.png)

**Comment by seerge** [comment]
You just started an app multiple times in a row.

**Comment by TeccnoW** [comment]
Can you disable it ?

**Comment by ke1ne** [comment]
Yeah, that's true, avoiding of multiple instances could nice feature. Not necessary, anyway.

**Comment by seerge** [comment]
Yes, i will add a notification in a next build

**Comment by jamieernest** [comment]
> Yes, i will add a notification in a next build

Was about to make an issue for it cos after a while it would error out when it tries to read config.json
