### ISSUE TITLE
s-key just funtions when pressing prtsc key

### ISSUE THREAD

**Issue by Moorole** [seerge/g-helper#1460]
I noticed that, at one point my s-key is not working anymore but noticed i am able to create a ß with the same key. also the s is working sometimes, but sometimes just if i press prtsc. same with capslock. i am using the en-int layout on a g14 from 2020 with Windows 10 on newest updates.  Don't know if it is this program but I thought it must be a software problem and g-helper would be the only program which would affect keys. Maybe you guys know an answer. Thank you so much and have good week all together
Moorole
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Comment by seerge** [comment]
@Moorole hello,

G-Helper doesn't touch your regular keys anyhow :) So i'm afraid your problems lies somewhere else.

The easiest way to test that it's unrelated is to quit the app, and see if the problem persists.
