### ISSUE TITLE
The whole program is not responding when the charging cable is unpluged

### ISSUE THREAD

**Issue by jetstreaml** [seerge/g-helper#1466]
The whole program is not responding for approximately 30s regardless of whether the window is opened or not.(latest version 0.129)

1. Launch Ghelper
2. Unplug the charging cable.

**Expected behavior**
Ghelper will be no responding immedtely when the charging cable is unpluged and the window is not moveable when it is opened, then it will recover after about 30s.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12896819/log.txt)

**Desktop :**
 - OS: Windows 11
 - ROG Zephyrus G14 GA402XU

**Asus software**
No Asus software is running when the error happens

**Additional context**
This error start exist just few days ago.
There is a config.json.
[config.json](https://github.com/seerge/g-helper/files/12896830/config.json)

**Comment by seerge** [comment]
@jetstreaml hello,

When you have Optimized GPU setting it means app will try to turn off dGPU every time you unplug.

Disabling dGPU command unfortunately locks whole process.  Furthermore i see that eco command has failed in your case by some reason (i.e. BIOS has refused to do that)

```
2023/10/14 1:29:49: Running eco command 1
2023/10/14 1:30:39: GPUEco = 1 : 0
```

Most probably it's related to a known issue with the way 2023 models act https://github.com/seerge/g-helper/discussions/1042

I would advice check that topic, and make sure that you have "Enable GPU on shutdown" selected under extra, and make sure that you have GPU enabled while rebooting or shutting down :) then it seem to work fine.
