### ISSUE TITLE
Screen artifacts at 60hz

### ISSUE THREAD

**Issue by Nobylo** [seerge/g-helper#1468]
**Description**
Switching the screen refresh rate to 60hz via G-helper introduces screen artifacts at the bottom of the screen. This has been tested with the following G-helper versions:
-0.74
-0.107
-latest version

Setting the refresh rate via the Windows display settings does not have the same effect.

G-helper seems to be setting the refresh rate to 60hz flat, rather than 60.1hz. 60hz is only visible in the Windows display settings when G-helper has already switched to it. (see attached image) The issue is not present when running the screen at 60.1hz.

**Clear scenario to Reproduce**
0. Set screen refresh rate to 144 via G-helper, or any refresh rate via the windows display properties
1. Switch to 60hz via G-helper, either automatically or manually
2. Screen artifacts usually associated with an incorrect refresh rate start appearing
[this will likely not be reproducible]

**Expected behavior**
G-helper should be switching to 60.1hz instead of 60hz

**Screenshots**
![ApplicationFrameHost_UueR7pouH8](https://github.com/seerge/g-helper/assets/93540280/af5e901b-8d1e-4d22-a4a8-382293e36f30)

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12899872/log.txt)

 -OS: Windows 11
 -Laptop model: TUF Gaming F17 FX706HEB

**Asus software**
-Armoury Crate not installed
-MyASUS not installed
-8 Asus services running in background

**Additional context**
I've never posted a bug report on github, sorry for any missteps

**Comment by seerge** [comment]
@Nobylo hello

G-Helper just uses windows API to set refresh rates. It's pretty straightforward procedure, and doesn't have any specifical options.

And i see that it works fine in your case

```
14/10/2023 00:34:07: \\?\DISPLAY#AUO8294#4&2cae7e3&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
14/10/2023 00:34:07: \\?\DISPLAY#AUO8294#4&2cae7e3&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
14/10/2023 00:34:07: Screen = 60Hz : OK
14/10/2023 00:34:07: ScreenOverdrive = 0 : OK
```

```
14/10/2023 00:34:14: \\?\DISPLAY#AUO8294#4&2cae7e3&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
14/10/2023 00:34:14: \\?\DISPLAY#AUO8294#4&2cae7e3&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
14/10/2023 00:34:14: Screen = 144Hz : OK
14/10/2023 00:34:14: ScreenOverdrive = 1 : OK
```

There is nothing that can be added to that.

Given that you have this strange options with ``60.01hz`` in your supported resolutions - it looks like some quirks with GPU drivers, I would advice to do a clean reinstall of them using DDU.

Or just use windows to switch refresh rates :)

I can't really do anything here :) Sorry.
