### ISSUE TITLE
Can you make a dedicated app only for fan control?

### ISSUE THREAD

**Issue by CxDxVER** [seerge/g-helper#1469]
It would be great if you built a GHelper only for fan controls with custom curve support, this would help the guys control there fan speed who want to use armoury crate

**Comment by Kikimahe** [comment]
I don't understand your request.
You can already create a custom profile for fan curves in Ghelper. :-)
![Capture d'écran 2023-10-14 082844](https://github.com/seerge/g-helper/assets/142881210/c8ed726a-b3e0-4852-a6b2-8ff369ea80ac)

Ghelper isn't a plugin that you can use with Armory crate..
It's a small, lightweight, complete alternative to Armory crate. \o/

**Comment by seerge** [comment]
@CxDxVER hello. G-Helper [doesn't control your fans](https://github.com/seerge/g-helper#how-does-g-helper-control-my-fan-speeds) . Custom fan curves are closely connected with performance modes, and will be immediately overwritten by Armoury each time you would change mode

**Comment by CxDxVER** [comment]
> I don't understand your request. You can already create a custom profile for fan curves in Ghelper. :-)
> 
> ![Capture d'écran 2023-10-14 082844](https://user-images.githubusercontent.com/142881210/275153163-c8ed726a-b3e0-4852-a6b2-8ff369ea80ac.png)
> 
> Ghelper isn't a plugin that you can use with Armory crate.. It's a GREAT small/lightweight/complete alternative to Armory crate. \o/

I was just asking if the dev could make a separate app for fan controls to be used adjacent to armoury create.
but i got the answer for which i have been looking for thx.
