### ISSUE TITLE
Windows Defender flags v0.39 as 'Trojan:Script/Wacatac.H!ml'

### ISSUE THREAD

**Issue by DanWiseProgramming** [seerge/g-helper#147]
**Describe the bug**
v0.38 is not flagged by Windows Defender but v0.39 is flagged as soon as one downloads the ZIP archive.
I'm not saying that this archive contains a trojan - just thought I'd provide a notification.

Perhaps it's flagging the updater logic changes as the Windows Defender output says that 'This program ... executes commands from an attacker': https://github.com/seerge/g-helper/commit/85e02549f1616dc6c656bd16af18137376bad689

**To Reproduce**
1. Activate Windows Defender.
2. Download latest version archive.

**Expected behavior**
Should not be flagged as trojan.

**Screenshots**
![GHelper](https://user-images.githubusercontent.com/22768251/227775272-8fbeca2e-7f43-4f3f-8e4e-7345b0ef4bf9.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
- Windows Defender Security Intelligence Version: 1.385.1161.0

**Comment by seerge** [comment]
Windows defender is a big pain for me with it's false positives. I have recompilled same thing and uploaded again - seem to be ok now https://github.com/seerge/g-helper/releases/tag/v0.39

**Comment by DanWiseProgramming** [comment]
The new archive is good, thanks.

**Comment by seerge** [comment]
I have also submitted it to microsoft for a review, usually it helps to defeat defender
![Screenshot 2023-03-26 143613](https://user-images.githubusercontent.com/5920850/227776083-be84aa61-1bef-4342-b268-fe509d97de02.png)

**Comment by seerge** [comment]
I have also submitted it to microsoft for a review, usually it helps to defeat defender
