### ISSUE TITLE
Toggle Ultimate gpu mode shortcut 

### ISSUE THREAD

**Issue by anilabhadatta** [seerge/g-helper#1470]
Is there any shortcut to toggle between standard and ultimate gpu mode.
I enabled ultimate gpu mode and now i can only see black screen, i cannot switch back to standard again.
Laptop is always starting in dgpu mode.
Asus zephyrus g15 rtx3080
I recently flashed a rom and then went into ultimate mode which now causes black screen, 
Even external display is not showing up

**Comment by anilabhadatta** [comment]
@ZimM-LostPolygon can you help me in providing some cmd commands so that if i enter those commands i can switch from ultimate to eco mode?
Since you know how to use the ghelper to switch gpu modes, can it be do by running some commands in cms

**Comment by seerge** [comment]
@anilabhadatta hello, i suggest to do a [hardware reset](https://github.com/seerge/g-helper#how-do-i-do-a-hardware-reset-on-a-laptop) , it would set MUX switch back ON and reset other settings.

**Comment by anilabhadatta** [comment]
@seerge how to hard reset?

**Comment by anilabhadatta** [comment]
If you could provide some commands or a powershell script that could switch back mux and restart system as well, it would have been helpful.
I tried many things but couldn't work.
Only thing i could open is cmd and run few commands that too in black screen

**Comment by anilabhadatta** [comment]
@seerge i tried the 30-40 second hard reset but didn't do anything.
I could open the Ghelper using M4 key and i was able to take a screenshot and copied the files to pd to see my current ghelper settings.
I saw that my Ultimate setting is still switched on.

**Comment by seerge** [comment]
@anilabhadatta you can also enable MUX with following powershell command (as admin)

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00090016, 1)
```

**Comment by anilabhadatta** [comment]
@seerge will it disable the ultimate mode and enable standard?

**Comment by anilabhadatta** [comment]
@seerge also should i delete the config from Appdata/Roaming?

**Comment by seerge** [comment]
> @seerge will it disable the ultimate mode and enable standard?

Yes, it’s same command as app runs

Config is not important here

**Comment by anilabhadatta** [comment]
@seerge it didn't work, i will try again

**Comment by anilabhadatta** [comment]
@seerge i fixed it finally.
Installed splashtop streamer, logged in my account blindly using keyboard.
Connected my display from separate laptop remotely.
Switched back to standard mode .
Display is back now in igpu mode, reflashed my original vbios.
I would like a feature in ghelper where there is a shortcut toggle key which can auto switch between standard and ultimate mode and also automatically force reboot the laptop in such scenarios.
Because the reboot option is coming in a separate window, i was not able to click OK in that dialogue box.

**Comment by Raneszxc** [comment]
Hi have the same case, I flashed vbios in dGPU mode and after I had black screen, but I can interact with windows. How I can disable dGPU mode and switch to optimus instead?(I don't have MUX switch) Maybe I can use key combination 'tab' or arrow keys for navigation in G-Helper? (sorry for my bad Endglish)
