### ISSUE TITLE
Power Plan Mode

### ISSUE THREAD

**Issue by AllenSmithee** [seerge/g-helper#1471]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hi seerge, I am using your gHelper and it is a such a great app, and I really appreciated all of your hard work!!

Okay now more I use your great app, more I really want some function to be included.
It is about the each power mode's option edit settings. I really want to manually change the CPU power limit ( percentage of min/max processor ) and power setting about intergraited gpu for battery mode and AC mode parts.

I would like to see all the power mode setup to be shown in the power option windows(with regedit and cmd code doesn't work because of the arm64 base notebook won't work) but if it is hard to show every power plan options, I really hope can get the option to be visible like armory crate one each power option shown when you change the power mode(silent, balanced, turbo). 
At the moment, I can only see and can setup balanced option only and I want to use other options for cpu power limiting with each modes.

I hope you have a great coding life mate~!

**Comment by AllenSmithee** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/windows-10-lacking-power-options-only-balanced/ba5d468c-cdf4-4a3d-b8fe-c0e92f179f2b

this won't work because of arm64 base system.

**Comment by seerge** [comment]
@AllenSmithee hello, i don't want to overload app with things you can already set inside power plan.

If you want to use different settings for each mode - i would recommend creating more custom power plans in windows control panel and setting them in a way you want. 

After that you can assign custom power plan for each mode individually (or one for all)
https://github.com/seerge/g-helper#custom-windows-power-plans-with-each-mode 

Good luck
