### ISSUE TITLE
Can't open "Extra" menu( error)

### ISSUE THREAD

**Issue by Autobiography59** [seerge/g-helper#1473]
Hello, I'm getting an error when I try to log into Extra. "Unhandled exception has occurred in your application".

[log.txt](https://github.com/seerge/g-helper/files/12907985/log.txt)
[error code.txt](https://github.com/seerge/g-helper/files/12907986/error.code.txt)

**Comment by seerge** [comment]
@Autobiography59 does it happen all the time you open Extra? (if you restart app) or did it happen only once ?

**Comment by Autobiography59** [comment]
@seerge When I restarted app, I was able to open the Extra tab and saw that one Asus service was running, even though I had disabled everything before. Could that have had an effect?

I reinstalled windows today, new system. On my other laptop I have never encountered this before.

**Comment by seerge** [comment]
@Autobiography59 no, it's unrelated. Exception is from one of the comboboxes (for bindings) and getting settings from config. But it's not reproducible, and seem to be random.

So that's my question, did it happen once ? Or does it happen all the time ?

**Comment by Autobiography59** [comment]
@seerge Only once

**Comment by seerge** [comment]
@Autobiography59 well, then I can't really do much about it :) I can suppress that specific exception in a code of the app, but then one of the bindings dropdowns probably won't work in that specific Extra screen open.

So lets leave it as is.

Let me know if it starts happening all the time (i.e. in scenario where you can recreate it)
