### ISSUE TITLE
Switch GPU mode and shutdown

### ISSUE THREAD

**Issue by ice42cream** [seerge/g-helper#1476]
**Is your feature request related to a problem? Please describe.**
I use my ASUS laptop both at home and work. Personally, I use _Ultimate GPU Mode_ at home and _Eco GPU Mode_ at work. This requires a restart when I arrive home or office. I do not mind doing this, as Windows 11 has some screen scaling bugs when I switch between my home monitor and office monitor and a restart can fix it. Everything is ok to me so far.
The problem is, my laptop only supports S0 sleep mode, which may cause overheat when I store it in my backpack. What's worse, overheat could cause liquid metal (a thermal interface material, I'm not sure about its English name) to leak and destroy the motherboard. So I have to do a shutdown before I commute, and then a turn-on when I arrive, and then a restart to switch GPU Mode. This is a little bit silly.

**Describe the solution you'd like**
When I switch from or to _Ultimate GPU Mode_, give me a pop-up with 3 buttons: _Confirm and restart_, _Confirm and shutdown_ and _Cancel_. Maybe we can add a switcher for this, as I knew my case is rare and most people do not need this.
Thanks for reading and considering my request.

**Comment by seerge** [comment]
@ice42cream hello, I don't want to overcomplicate UI with shutdown options.

But when you select restart - windows will show a warning that system is about to restart with a cancel button. You can click that and just shutdown instead :) That would fit your case.
