### ISSUE TITLE
reopen request : XG Mobile 4090 LED control not working. #1344

### ISSUE THREAD

**Issue by JYW-D** [seerge/g-helper#1477]
Hello awesome developer!
I used the debugging tool suggested to find a solution to the above problem, but failed to extract packets from all USB-related devices.
As an alternative, the following information was obtained from USB packet capture using Wire Shark.
I am using XG Mobile 4090, and I captured packets work in Armory.

I hope this information will help you activate XG mobile's led on off function, but it seems to be the same as the packet value you know, so it's confusing to me.

Data Fragment: 5ec550
Data Fragment: 5ec500

Frame 1277: 336 bytes on wire (2688 bits), 336 bytes captured (2688 bits) on interface \\.\USBPcap2, id 0
    Section number: 1
    Interface id: 0 (\\.\USBPcap2)
    Encapsulation type: USB packets with USBPcap header (152)
    Arrival Time: Oct 16, 2023 13:43:45.723154000 대한민국 표준시
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1697431425.723154000 seconds
    [Time delta from previous captured frame: 0.005013000 seconds]
    [Time delta from previous displayed frame: 0.005013000 seconds]
    [Time since reference or first frame: 10.405214000 seconds]
    Frame Number: 1277
    Frame Length: 336 bytes (2688 bits)
    Capture Length: 336 bytes (2688 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: usb:usbhid]
USB URB
    [Source: host]
    [Destination: 2.11.0]
    USBPcap pseudoheader length: 28
    IRP ID: 0xffffc886314807e0
    IRP USBD_STATUS: USBD_STATUS_SUCCESS (0x00000000)
    URB Function: URB_FUNCTION_CLASS_INTERFACE (0x001b)
    IRP information: 0x00, Direction: FDO -> PDO
    URB bus id: 2
    Device address: 11
    Endpoint: 0x00, Direction: OUT
    URB transfer type: URB_CONTROL (0x02)
    Packet Data Length: 308
    [Response in: 1278]
    Control transfer stage: Setup (0)
    [bInterfaceClass: HID (0x03)]
Setup Data
    bmRequestType: 0x21
        0... .... = Direction: Host-to-device
        .01. .... = Type: Class (0x1)
        ...0 0001 = Recipient: Interface (0x01)
    bRequest: SET_REPORT (0x09)
    wValue: 0x035e
        ReportID: 94
        ReportType: Feature (3)
    wIndex: 0
    wLength: 300
    Data Fragment: 5ec550000000000000000000000000000000000000000000000000000000000000000000…

Frame 1287: 336 bytes on wire (2688 bits), 336 bytes captured (2688 bits) on interface \\.\USBPcap2, id 0
    Section number: 1
    Interface id: 0 (\\.\USBPcap2)
    Encapsulation type: USB packets with USBPcap header (152)
    Arrival Time: Oct 16, 2023 13:43:46.075911000 대한민국 표준시
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1697431426.075911000 seconds
    [Time delta from previous captured frame: 0.004750000 seconds]
    [Time delta from previous displayed frame: 0.004750000 seconds]
    [Time since reference or first frame: 10.757971000 seconds]
    Frame Number: 1287
    Frame Length: 336 bytes (2688 bits)
    Capture Length: 336 bytes (2688 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: usb:usbhid]
USB URB
    [Source: host]
    [Destination: 2.11.0]
    USBPcap pseudoheader length: 28
    IRP ID: 0xffffc8862c188280
    IRP USBD_STATUS: USBD_STATUS_SUCCESS (0x00000000)
    URB Function: URB_FUNCTION_CLASS_INTERFACE (0x001b)
    IRP information: 0x00, Direction: FDO -> PDO
    URB bus id: 2
    Device address: 11
    Endpoint: 0x00, Direction: OUT
    URB transfer type: URB_CONTROL (0x02)
    Packet Data Length: 308
    [Response in: 1288]
    Control transfer stage: Setup (0)
    [bInterfaceClass: HID (0x03)]
Setup Data
    bmRequestType: 0x21
        0... .... = Direction: Host-to-device
        .01. .... = Type: Class (0x1)
        ...0 0001 = Recipient: Interface (0x01)
    bRequest: SET_REPORT (0x09)
    wValue: 0x035e
        ReportID: 94
        ReportType: Feature (3)
    wIndex: 0
    wLength: 300
    Data Fragment: 5ec500000000000000000000000000000000000000000000000000000000000000000000…

Added: I found the answer in USB HID.
Please check whether it has changed from USB type to HID. I am not the developer involved, so it is difficult to find the exact change.
We succeeded in detecting packets from ITE Device (8910) in Device Monitoring Studio.

00000001	2023-10-16 13:58:22.9421318	+1.6992464	DOWN	0x00000000	URB_FUNCTION_CLASS_INTERFACE
000001: Class-Specific Request (DOWN), 2023-10-16 13:58:22.9421318 +1.6992464 (1. Device: ITE Device(8910))
Destination: Interface, Index 0
Reserved Bits: 34
Request: 0x9
Value: 0x35e
Send 0x12c bytes to the device

 5E C5 50 00 00 00 00 00 00 00 00 00 00 00 00      ^휪.............

00000003	2023-10-16 13:58:23.7574336	+0.8133149	DOWN	0x00000000	URB_FUNCTION_CLASS_INTERFACE
000003: Class-Specific Request (DOWN), 2023-10-16 13:58:23.7574336 +0.8133149 (1. Device: ITE Device(8910))

Destination: Interface, Index 0
Reserved Bits: 34
Request: 0x9
Value: 0x35e
Send 0x12c bytes to the device

 5E C5 00 00 00 00 00 00                           ^?......

I hope my information will help improve the feature.

**Comment by seerge** [comment]
@JYW-D hello, your information doesn't really help anyhow :) 

``5E C5 50`` is exactly same as app already sends to XGM to turn light on, and ``5E C5 00`` - to turn light off. So it's already there :)

I honestly doesn't know why it doesn't work in your specific situation. But since I don't have the device I can't help anyhow here .
