### ISSUE TITLE
Per profile CPU Boost setting

### ISSUE THREAD

**Issue by ArnavVarshney** [seerge/g-helper#148]
**Is your feature request related to a problem? Please describe.**
I usually enable CPU Boost when gaming on Turbo, but otherwise, I like to keep it disabled when I work (on Silent usually). On Silent, with Boost enabled, the fans toggle on/off a lot more.

**Describe the solution you'd like**
It would be perfect if the CPU Boost setting could be associated with the currently activated profile. I know it's just 2 additional clicks otherwise, but if it's not too much work for you, maybe this would be a good idea. 

Thanks for the dev work on this project!

**Comment by seerge** [comment]
I was answering this few times already. Since CPU boost is part of a (single) power plan, not any of the asus settings I don't plan to change it all the time.

Also you can just limit PPTs per mode, that has exactly same thermal /silent effect.

**Comment by ArnavVarshney** [comment]
Appreciate it. Thanks!
