### ISSUE TITLE
Screen off shortcut does not work on FA506IV

### ISSUE THREAD

**Issue by kazink** [seerge/g-helper#1480]
**Is your feature request related to a problem? Please describe.**
Hi, and first thank you for the app, it's super useful to be able to get rid of the bloated Armoury Crate and have everything in this simple app instead. Especially since the latest version of AC seems to take over some Alt+Ctrl+letter combinations despite the fact that they are used for some characters in my native language, essentially making typing text impossible. 
I am using it on the Asus TUF FA506IV laptop, and all the functions seem to be working, except one: the screen off shortcut under Fn+F6. It worked fine with Armoury Crate, but does not do anything after switching to G-Helper. The shortcut's purpose is to turn off the screen immediately without putting the system to sleep or hibernation. It is useful when I want to leave the laptop with a long task (a backup process or video rendering) with the screen turned off to save power and prolong the backlight life. 

**Describe the solution you'd like**
It would be great if G-Helper supported this shortcut for this laptop model.

**Describe alternatives you've considered**
I tried to find out how to do that by editing the config.json, but couldn't find any option for this there.
I tried to find an undocumented option by adding `"keybind_screenoff": 117` to the config.json file, but without success.
The last alternative I can think of, is going back to AC, but that's out of the question. I would rather live without the shortcut.

**Additional context**
This is how the key looks like on my keyboard:
![obraz](https://github.com/seerge/g-helper/assets/5015039/24bf0519-a5a0-4877-8d20-48f9ff4d3477)

Also it would be super-useful, if the app had an option to remap all of the shortcut keys. I would like to be able to switch brightness control (F7,F8) with aura keys (up/down arrows), because it would be much more convenient.

**Comment by seerge** [comment]
@kazink hello,

I was already answering this in other similar "issue". On all modern devices ``Fn+F6`` does print-screen action. And I believe it's more useful thing than locking your screen in windows :) So i'm keen to keep things like they are now.

Screen lock option is available as an action under ``Extra`` for macro-buttons tho, if you really need it.

As for backlight-brightness controls, you can also use ``Shift +M1/M2`` 
https://github.com/seerge/g-helper#extra-keybindings

**Comment by kazink** [comment]
Thank you for the answer, but I would still kindly ask for that feature.

First, there are no Macro keys on this laptop. I could assign the screen lock to a Fn+NumLk or Fn+F4, as I rarely use these features, but having the function under its designated key would be superior. 
Second, I already have a separate key for print-screen, so having that also under Fn+F6 makes no sense. 

Could you implement this as a configurable key binding in the Extra settings or as the config.json option? Please? :)

If not, could you tell what software I need to build the app? I would be willing to try and add the feature myself.

**Comment by seerge** [comment]
@kazink when Fn+F6 is pressed on modern laptops it emits print-screen on hardware level (i.e. app doesn't handle that in a first place)

What does Fn+F6 emit in your case? If it emits any special key-code - it will be added to the ``log.txt`` in realtime. Can you check ?

**Comment by seerge** [comment]
@kazink try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/12999786/GHelper.zip)

**Comment by kazink** [comment]
@seerge works perfect

**Comment by seerge** [comment]
Great

**Comment by kazink** [comment]
I guess that means the feature will make it into the app. Thank you very much :)
