### ISSUE TITLE
UI overlap on battery charge limit

### ISSUE THREAD

**Issue by ItxWeird** [seerge/g-helper#1483]
**Describe the bug**
The battery charge limit slider clips the `One time charge to 100%` button. I'm assuming this is just a simple UI bug that can be easily fixed by moving the `100%` button over the right or shortening/moving the battery limit charge slider to the left

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/62679764/be70b773-04f6-4da6-9f9f-b8decec3ba6e)

**Comment by seerge** [comment]
@ItxWeird hello, what UI scaling do you have in windows ?

**Comment by ItxWeird** [comment]
I believe it's 125%. On a 1080p screen if that affects anything. But it's also present in my 1440p display

**Comment by seerge** [comment]
@ItxWeird this build should fix it
[GHelper.zip](https://github.com/seerge/g-helper/files/12999612/GHelper.zip)

**Comment by ItxWeird** [comment]
Well, I downloaded the build that you linked, and it doesn't seem to open at all

**Comment by seerge** [comment]
@ItxWeird then it's probably your windows defender acting :) you should unblock this exe

**Comment by ItxWeird** [comment]
Just turned all of windows defender off and added an exclusion for GHelper and still no launch

**Comment by seerge** [comment]
@ItxWeird well, i don't know what happens specifically on your computer :) I don't have extrasensory skills

I can only upload recompiled version again

[GHelper.zip](https://github.com/seerge/g-helper/files/13013812/GHelper.zip)

**Comment by ItxWeird** [comment]
Hmm, really odd, not working again. The proper releases of GHelper are signed .exe's right? It might be something to do with that. Hopefully when the next release comes out it fixes everything, after all this is just a minor UI bug 😂

**Comment by ItxWeird** [comment]
Okay I just decided to replace my current ghelper install with the build you provided, and that didn't work so I decided to replace it back with the current version, that being 0.129 and now it still won't open

**Comment by seerge** [comment]
@ItxWeird you need to right click on exe and in properties unblock it

All exe are same

**Comment by ItxWeird** [comment]
Oh my god I am so very dumb, I will try this with the build you linked

**Comment by ItxWeird** [comment]
Can confirm that the build you linked fixes the problems!
