### ISSUE TITLE
Clicking  X in right corner should minimize app  to tray, not exit.

### ISSUE THREAD

**Issue by fcientymeh** [seerge/g-helper#1484]
Exit from app should be only, when clicking (right click) on icon in tray , and selecting exit. 
Its a little thing, but after changing some params people usually close window using X. I thing app should still running in tray. 
Great light app.
![image](https://github.com/seerge/g-helper/assets/122584230/ac2deb81-2e8c-4505-a740-49209c1e6897)

**Comment by seerge** [comment]
@fcientymeh hello, this is exactly what ``[X]`` does - it hides main window into system tray.

``Quit`` button closes app completely :)
