### ISSUE TITLE
Button to do one time charge to 100% does not automatically clear (i.e. go from blue to grey) when laptop battery 100% charged.

### ISSUE THREAD

**Issue by GavinCrate42** [seerge/g-helper#1485]
The Button to do one time charge to 100% does not automatically clear (i.e. go from blue to grey) when laptop battery 100% charged. Whilst the laptop does stop charging when the battery reaches 100% the button remains blue.
My understanding is the when the battery is 100% full the button (to do one time charge to 100%) should go grey.

**Comment by seerge** [comment]
@GavinCrate42 hello

App doesn't monitor battery charge all the time (to preserve resources), but I have added a condition in a situation when it does check for charge (i.e. when you have main window open) and if it's > 99% it will turn 100% charge button / setting OFF

[GHelper.zip](https://github.com/seerge/g-helper/files/13042645/GHelper.zip)
