### ISSUE TITLE
Zephyrus G15 2022 GA503RM turning off dGPU

### ISSUE THREAD

**Issue by Jelm123** [seerge/g-helper#1486]
**Describe the bug**
dGPU is getting disabled after logging into a session in Windows when the laptop turns on( I have a second display connected to a USB C hub) shows the login screen on the secondary screen once inside the dGPU gets disabled and it will only show on the laptop screen and windows nor Nvidia will recognize the GPU, I need to open G helper switch to standard and then back to optimized and that gets the GPU active again and the second screen works as well.

**Clear scenario to Reproduce**
1. Start Laptop
2. Login
3. Open G  Helper
4. Switch between Standard and Optimized

**Expected behavior**
Keep dGPU active

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Zephyrus G15 2022 GA503RM

**Asus software**
- MyASUS installed
- Other Asus services running in the background

[log.txt](https://github.com/seerge/g-helper/files/13030026/log.txt)

**Comment by seerge** [comment]
@Jelm123 hello. 

App just sets last remembered dGPU mode on start. Before reboot it was Eco (or Optimized with unplugged display), so it has set Eco again :)

If you will shut down / reboot in Standard - it won't change it on reboot.

**Comment by Jelm123** [comment]
thank you very much :)
