### ISSUE TITLE
XGM 4090 doesn't disconnect

### ISSUE THREAD

**Issue by lawrstay** [seerge/g-helper#1487]
**Describe the bug**
GHelper doesn't successful disconnect XGM 4090 dGPU. With 6850m it works everytime. 

**Clear scenario to Reproduce**
1. With XGM 4090 connected to ROG Ally, click on XGM icon in GHelper, and click confirm to disconnect
2. The status will say "changing" but after few minutes nothing happens
3. On the same Ally, using the XGM 6850m disconnects flawlessly everytime. 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - ROG Ally Z1 Extreme

**Asus software**
- ACSE 1.3.15
- Tried with both Asus XGM 4090 driver (V31.0.15.3645)
 & also latest Nvidia driver updates via Geforce Experience

**Comment by seerge** [comment]
@lawrstay hello.

> With 6850m it works everytime.

This is the reason :) You have quite exotic setup with 2 different XGMs

6850m requires a special "connect" command which is different from other models, and as soon as app spots it connected - it will add a special flag to own config, to know that it needs to run this command next time.

Apparently that command doesn't fit 4090 :)

Just open ``config.json`` and remove following line completely

```
"xgm_special" : 1,
```

And then restart app
