### ISSUE TITLE
UI elements flickering

### ISSUE THREAD

**Issue by bogdamel** [seerge/g-helper#1488]
When I open an app, by pressing the M4 button or the app icon all elements on the UI (buttons, sliders, etc.) quickly change color from white to black. I have a dark theme set in Windows Settings, and UI elements change from a light theme to a dark one every time I open it. It's very annoying.

https://github.com/seerge/g-helper/assets/24360830/8edc9545-2b3c-4382-9671-351362f02ed6

[log.txt](https://github.com/seerge/g-helper/files/13031594/log.txt)

Laptop:
 - OS: Windows 11
 - Asus Zephyrus G14 (2023)
- Armoury Crate
- MyASUS installed
- Asus services stopped

**Comment by seerge** [comment]
@bogdamel hello,

UI doesn't change from light to dark in your case, it just takes some time to get drawn :) (elements appear blank if you will play your video slowly)

I can't really change anything here, as this is apparently how Winforms applications work sometimes.

**Comment by bogdamel** [comment]
Thanks for the quick answer anyway)
