### ISSUE TITLE
Zephyrus Duo ScreenPad

### ISSUE THREAD

**Issue by trinhkc** [seerge/g-helper#1490]
**Is your feature request related to a problem? Please describe.**
Hello, is there a way to bind the screenpad brightness to any of the F keys above F4?

**Describe the solution you'd like**
Is it possible to bind the screenpad brightness to F7 and F8 but with a modifier like "shift"? To keep the original function of the keys.

i.e.
FN F7 = Primary monitor brightness down
FN F8 = Primary monitor brightness up
Shift FN F7 = Screenpad brightness down
Shift FN F8 = Screenpad brightness up
or
CTRL FN F7 = Screenpad brightness down
CTRL FN F8 = Screenpad brightness up

Any suggestion on how to do this?

Thank you

**Comment by seerge** [comment]
@trinhkc hello

This build should support ``Shift + Fn + F7`` / ``Shift + Fn + F8`` to control screenpad brightness

[GHelper.zip](https://github.com/seerge/g-helper/files/13042569/GHelper.zip)

**Comment by trinhkc** [comment]
Thank you so much @seerge ! it works perfectly

**Comment by fscottcopeland** [comment]
Will this be released on a stable build too? Currently use AHK to bind the screenpad brightness to CTRL+ALT F7/F8, but would be nice to be able to utilise the FN key (with shift) as a modifier too. The more hotkey options, the better!

**Comment by seerge** [comment]
@seerge yes, all completed issues are usually in next release :)
