### ISSUE TITLE
Zephyrus Duo ScreenPad Touch Toggle (Feature Reques)

### ISSUE THREAD

**Issue by squee666** [seerge/g-helper#1491]
**Is your feature request related to a problem? Please describe.**
Toggle to Turn off touch on the screenpad

Basically Armoury Crate had a feature to turn off the touch element of the screenpad altogether as its a secondary display

![image](https://github.com/seerge/g-helper/assets/628576/e6df4462-5380-4898-baf2-7171ef606033)
![image](https://github.com/seerge/g-helper/assets/628576/3ce16cfa-0ffa-46bf-9324-c8e26433184c)

Optional feature, make it a toggle with FN+Key: 106   (the key that toggled the display turning off/on)

**Comment by seerge** [comment]
@squee666 hello,

But this is literally what we did for you already https://github.com/seerge/g-helper/issues/1215 ?

You can cycle through ON, ON w/o touch and OFF states ?

**Comment by squee666** [comment]
> @squee666 hello,
> 
> But this is literally what we did for you already #1215 ?
> 
> You can cycle through ON, ON w/o touch and OFF states ?

this is different

this cycles the Touch Control Only
nothing else

**Comment by squee666** [comment]
im guessing you cant make it a Tick box under Extra?
and a hidden Toggle with FN+Key: 106 which normally just toggles the screens on/off

**Comment by seerge** [comment]
@squee666 

Fn+Key won't be readable, cause Fn by itself doesn't emit anything

But I have added a ``Shift + Screenpad key`` combination that should just toggle it ON or OFF

[GHelper.zip](https://github.com/seerge/g-helper/files/13045039/GHelper.zip)

**Comment by seerge** [comment]
@squee666 then I simply don't know how is that controlled

For Screenpad there are 2 endpoints only, for toggle and for brightness
https://github.com/seerge/g-helper/blob/main/app/AsusACPI.cs#L106

I assumed that toggle would toggle input. Apparently it doesn't

Does disabling touchpad (via Fn+F10) disable screenpad input as well ?

**Comment by squee666** [comment]
unfortunately it doesnt and i dont know how to measure it

**Comment by squee666** [comment]
![image](https://github.com/seerge/g-helper/assets/628576/b746341c-5625-4625-a247-427783f3cbe9)

heres the hardware ID i dunno if it disables it through that

**Comment by seerge** [comment]
@squee666 well, then i'm out of ideas as well :)

**Comment by seerge** [comment]
@squee666 since I have started doing this , I have updated build with appropriate toast notification (now it will show backlight icon instead of touchpad) when toggles on / off

I still have no idea how actual input disabling works, but i really doubt it's done by disabling device in device manager

[GHelper.zip](https://github.com/seerge/g-helper/files/13052434/GHelper.zip)
