### ISSUE TITLE
Feature Request: The ability to disable or enable turbo boost using a hotkey/keyboard shortcut

### ISSUE THREAD

**Issue by nsilvias** [seerge/g-helper#150]
**Describe the solution you'd like**
The ability to Disable or Enable turbo boost using a hotkey. Many games don't need turbo at all to run at acceptable framerates but Windows and other applications do benefit from turbo so being able to switch it on or off on demand would be nice to maintain a good balance between temps/low fan noise in game and performance during general use.

Also, i forgot to thank you for your work on tuf keyboard backlight implentation in the other thread so thanks for that! very much appreciate your work

**Comment by seerge** [comment]
Why don't you just set PPTs for your CPU to limit temps per different mode?

**Comment by seerge** [comment]
I have added experimental saving of CPU boost setting per each Performance mode in https://github.com/seerge/g-helper/releases/tag/v0.40 

And you can change modes with a hotkey :)

**Comment by seerge** [comment]
FN+F5 or M4 can cycle modes

**Comment by seerge** [comment]
@nsilvias you just have to manually set it (in a dropdown) at least once for each mode to be saved
