### ISSUE TITLE
Missing an important feature after replacing Armoury crate with Ghelper. (FN+V)

### ISSUE THREAD

**Issue by Samsung2023** [seerge/g-helper#1500]
While using Armoury crate I was always use FN + V shortcut to change screen colors, but after deleting armoury crate and installing Ghelper instead I wasn't able to use FN + V shortcut, is there a way to bring it back without installing the shitty armoury crate again?

**Comment by seerge** [comment]
@Samsung2023 hello,

Your question is [already answered in FAQ](https://github.com/seerge/g-helper#how-do-i-set-different-visual-styles)

Next to that this is a dublicate of this issue https://github.com/seerge/g-helper/issues/520
