### ISSUE TITLE
G-Helper Search for app in the Store? issue

### ISSUE THREAD

**Issue by erogluuefe** [seerge/g-helper#1503]
**Describe the bug**
The photo explains the bug clearly. I cannot start the application. I've followed all the necessary steps to run the app but it doesn't start and redirects me to windows store to download the app. The windows store returns nothing.

**Clear scenario to Reproduce**
1. Fresh download of Windows.
2. Run the app.

**App Logs**
Since the applications doesn't start itself its impossible to get the logs.

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/45459558/4fc4ba7e-49ec-4ff5-903e-d8c9b7a63a20)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 22H2 (Fresh)
 - OS Build : 22621.2361
 - Laptop model : ROG Strix G531GV

**Asus software**
- No asus software installed just the ones that are written on the necessary steps.

**Additional context**
I did a fresh install to windows. Before the fresh install i was able to use the app without any problems. Sorry for not being able to provide any log but I'm not able to retrieve them. I'm a developer myself and would like to help fix this problem.

**Comment by seerge** [comment]
@erogluuefe hello, this is windows defender acting.

Check this topic on how to deal with that https://github.com/seerge/g-helper/discussions/778

**Comment by erogluuefe** [comment]
Thanks for the instant reply on the topic. Sorry for not checking previous issues.
