### ISSUE TITLE
Vivobook 16X GPU settings not showing up

### ISSUE THREAD

**Issue by electro2040k** [seerge/g-helper#1505]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

GPU settings not showing up, even though I have a MUX switch and a dedicated GPU

GPU settings should be showing up, but neither right clicking on app icon or looking at the GUI shows it

Can reproduce by opening app

[log.txt](https://github.com/seerge/g-helper/files/13062675/log.txt)

https://github.com/seerge/g-helper/assets/107386628/488caaf1-9a5b-4155-95df-9d79550dc960)

 Windows 11
Vivobook 16X K3605ZC-N1103W

**Asus software**
- Armoury Crate Installed
- MyASUS installed
- Other Asus services running in background

**Comment by seerge** [comment]
@electro2040k hello,

Not all devices support disabling dGPU :)  Vivobooks - don't, so you won't see a GPU modes here. 

You also didn't have them in MyASUS / Armoury
