### ISSUE TITLE
Switching from silent to turbo mode overrides turbo mode's CPU boost values

### ISSUE THREAD

**Issue by Kawler** [seerge/g-helper#1506]
If you switch from silent to turbo mode, turbo mode's "CPU Boost" parameter gets overridden by value from silent mode
  
1. Setup different cpu boost values in turbo and silent mode
2. Switch to silent
3. Switch to turbo (value gets changed)
*While switching from silent->balanced->turbo everything works as expected. Meaning if you get this bug, and than switch to balanced->turbo displayed value is correct
**Actually affects cpu boost behavior 

Switching from silent to turbo shouldn't change turbo's cpu boost
 - OS: Windows 11
 - Asus TUF A15 FA506QM

- only G-Helper 
- 0.129.0

[log.txt](https://github.com/seerge/g-helper/files/13063024/log.txt)

**Comment by seerge** [comment]
@Kawler you just don’t have any boost setting for Balanced mode, so it just uses whatever boost setting that was already 

It works as intended

**Comment by Kawler** [comment]
This clearly doesn't work as intended. And I do have boost setting for Balanced mode, although I don't understand why are you focusing on this.
Silent(Boost: disabled) - > Turbo(should be: Boost: efficient enabled)  Boost:disabled
Silent(Boost: disabled) -> Balanced(Boost: efficient enabled) -> Turbo(Boost: efficient enabled, as it should be!)
If I switch to Turbo(Boost: aggressive) than
Silent(Boost: disabled) -> Balanced(Boost: efficient enabled) -> Turbo(Boost: aggressive , as it should be!)
Silent(Boost: disabled) -> Turbo(Boost: disabled)

**Comment by seerge** [comment]
@Kawler 

Mode 0 (Balanced) is paired with Boost 3 (Efficient enabled)

```
22.10.2023 13:49:37: Mode = 0 : OK
22.10.2023 13:49:37: Power Mode 00000000-0000-0000-0000-000000000000:OK
22.10.2023 13:49:37: Boost 3
```

Mode 1 (Turbo) is not paired with anything (you haven't explicitly selected a boost setting for it), so just open dropdown and select something
```
22.10.2023 13:49:27: Mode = 1 : OK
22.10.2023 13:49:27: Power Mode ded574b5-45a0-4f42-8737-46345c09c238:OK
```

Mode 2 (Silent) is paired with Boost 0 (Off)
```
22.10.2023 13:49:26: Mode = 2 : OK
22.10.2023 13:49:26: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
22.10.2023 13:49:26: Boost 0
```
