### ISSUE TITLE
Core Disabling on Intel CPUs

### ISSUE THREAD

**Issue by xB-r** [seerge/g-helper#1507]
Not exactly a problem, but it would be nice to be able to prolong battery life by disabling cores without using the BIOS everytime.

A button to disable cores (we could select which to disable using a slider maybe)

Armoury Crate has this feature but it sucks and as of now, the BIOS is the only way to do it.

**Comment by xB-r** [comment]
INFO:
Laptop: Zephyrus M16 w/ 13900H and 4070
Latest BIOS ver. 312

**Comment by seerge** [comment]
@xB-r i don’t know how it’s controlled.

But taking into consideration that disabling cores (even in AC) you need to reboot after anyway , i don’t see as a big problem :)

**Comment by xB-r** [comment]
The reboot isnt an issue, but its annoying having to visit the bios each time and digging in for the setting, im on the move on weekdays so this would be convenient with just a click, the bios takes me like 10 mins to find the setting and change.

**Comment by seerge** [comment]
@xB-r you can try to run a scan script from here https://github.com/seerge/g-helper/issues/38 

For different situations (when cores are enabled / disabled / partially enabled / etc)

And try to find out endpoint that is responsible for that (by reported values)
