### ISSUE TITLE
Cannot enable Eco mode

### ISSUE THREAD

**Issue by nodomw** [seerge/g-helper#151]
**Describe the bug**
I can't enable Eco mode / Disable the dGPU.
**To Reproduce**
1. Attempt to enable Eco mode for GPU.

**Expected behavior**
After switching to Eco mode, it switches right back to Standard. Doesn't happen with Optimized visually, however.

**Screenshots**
![G-Helper-1679862330](https://user-images.githubusercontent.com/47635446/227802648-d25f95b1-4acc-49b6-94fb-ca8b81479818.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 22H2
 - Zephyrus G14 2020 GA401IV
 - 
 
**Additional context**
I've been having an issue with atrocious battery life (30-40wH discharge) for a while now and I don't have any idea why it could be happening. If the issue doesn't turn out to be with G-Helper, please consider this a kind of cry for help. I have a feeling it may have something to do with my drivers but I've reinstalled them so many times that I have no clue what else could be causing it.

**Comment by nodomw** [comment]
nevermind.

**Comment by cosmanee** [comment]
I first downloaded an old release, and this was working fine for me fine until I updated the app.
