### ISSUE TITLE
Add a toggle to disable connectivity in S0 standby

### ISSUE THREAD

**Issue by wowitsmartin** [seerge/g-helper#1511]
**Is your feature request related to a problem? Please describe.**
Many modern laptops, including the one I'm currently using (the 2021 G14 ga401qm), have disabled S3 sleep mode and are instead using S0. This can be either 'connected standby' or 'disconnected standby'. By default, it is connected when the computer goes to sleep while connected to AC power. It could also be connected when using battery power, depending on Windows' decision, possibly related to battery levels. Connected standby can cause several problems, including the laptop possibly overheating when placed in a backpack and battery drainage. If the computer goes into sleep mode while plugged in, and then gets unplugged, it will not change its state.

On most laptops, it is not possible to re-enable S3. However, you can force S0 to always use the 'disconnected' mode.

In order to do this power plan settings need to be changed as follows:
For AC mode:
`powercfg /setacvalueindex scheme_current sub_none F15576E8-98B7-4186-B944-EAFA664402D9 0` 
For DC mode:
`powercfg /setdcvalueindex scheme_current sub_none F15576E8-98B7-4186-B944-EAFA664402D9 0`

**Describe the solution you'd like**
Add a toggle in the 'extras' menu to set the current plan to always use the disconnected S0.

**Describe alternatives you've considered**
The manufacturer has disabled S3 in the BIOS, leaving no simpler alternatives.

**Additional context**
[Information about issues with connected standby](https://www.makeuseof.com/windows-modern-standby-flaws/)

`powercfg -a` will verify that only 

> "Standby (S0 Low Power Idle) Network Disconnected"

is supported after changing the settings above.

**Comment by seerge** [comment]
@wowitsmartin hello,

That's quite specific request :) I'm trying to not overload app with things that you can do somehow (i.e. they are not asus specific) and that are not in AC functionality.

You can set this setting via windows power plan (if you unlock them via registry) or as ``powercfg`` command indeed. 

But that's something you set once and forget :) So I won't be adding this to the app
