### ISSUE TITLE
F5 (F5-12) Customization

### ISSUE THREAD

**Issue by ConsueTerra** [seerge/g-helper#1513]
**Is your feature request related to a problem? Please describe.**
Currently F1 to F4 are customizable, F5 controls the power mode, however I would like to change that to something more standard (ie I currently have F4 on Previous Track, and I would like to set F5 to Next Track)

**Describe the solution you'd like**
Add FN F5 to the keyboard customization options, and if possible all function keys.

**Describe alternatives you've considered**
Some other hotkey mapper would have to be used ontop of G-helper (like PowerToys) and there might be an issue with priorities, also this would break Fn -lock functionality (ie if FN lock is off, then the hotkey action would still happen. not F5)

**Comment by seerge** [comment]
@ConsueTerra hello

App lets you bind macro keys (M1-M4) :) which is the case for vast majority of the devices, not the Fx keys.

You see it as F1-F4 probably cause you have some old TUF model or G14 from 2020

I prefer to not to clutter (and overload) app with millions of bindings, cause it will make things even more confusing

**Comment by seerge** [comment]
P.S. Some Fn+Fx keys actually work on hardware level only (like print-screen or presentation mode), they are not handled by the app at all
