### ISSUE TITLE
UI artifact when opening the app

### ISSUE THREAD

**Issue by mrunknown9999** [seerge/g-helper#1514]
Every time I open the app (even if the app is running in the background) I get this artifact for about 1 second (at 60hz and at 165 hz).
Laptop Flow X13 RTX4060 running Windows 11

![Screenshot 2023-10-24 123420](https://github.com/seerge/g-helper/assets/128497652/260f85de-2742-4698-a23a-02b559fffea2)
[log.txt](https://github.com/seerge/g-helper/files/13113183/log.txt)

**Comment by seerge** [comment]
@mrunknown9999 that's how winforms app draws it's stuff :) i can't really fix that anyhow
