### ISSUE TITLE
Temporary Discharge Notification Despite Battery Limit

### ISSUE THREAD

**Issue by udegbunamchuks** [seerge/g-helper#1516]
Recently I stopped all Asus services running using the Extra feature but I've noticed that on reboot of my laptop despite battery limit set, the app would show Discharging for some minutes then go away.

Note that battery isn't actively charging while this notification is showing.

Is this normal? Thanks

<img width="303" alt="Screenshot 2023-10-24 191151" src="https://github.com/seerge/g-helper/assets/45827666/597babaf-5af6-4388-93fd-02046fa84e9d">

**Comment by seerge** [comment]
@udegbunamchuks hello, that's absolutely normal :) Charging is controlled by hardware, app just shows whatever windows reports

**Comment by udegbunamchuks** [comment]
Thanks @seerge
