### ISSUE TITLE
Add anti-ghosting key feature from MyASUS app

### ISSUE THREAD

**Issue by b4lance-d** [seerge/g-helper#1517]
When I pressed the combination of keys Fn + [ or Fn + ] enabled mode Anti-ghosting key Full and Anti-ghosting key 30 (I do not know exactly what this mode is), when you turn on this mode noticeably increased the responsiveness of the keyboard, my laptop - Asus ROG Zephyrus G15 2020 (GA502), I hope to add this feature.

**Comment by seerge** [comment]
@b4lance-d hello , i honestly have no idea how that works :) (and why would keyboard be non responsive in a first place ?) 

Why don't you just turn it once in MyASUS and forget ? (it's absolutely fine to keep the app next to g-helper just in case)

**Comment by b4lance-d** [comment]
@seerge Exactly in the MyASUS application it worked only when I pressed this combination of keys when starting Windows (that is, it as I understand it is disabled automatically at reboot and the responsiveness of the keyboard really improved), if you do not press this function is not active, I just got rid of the use of bloatware from Asus (namely ArmoryCrate and MyASUS), so I would very much like to see this feature in new versions :)

**Comment by seerge** [comment]
@b4lance-d that's a very strange and odd solution from asus. I assume it's applicable only to very old devices :)

Anyway, I don't know how it's controlled

You can try to switch the thing ON and OFF and run a [scan script from this thread ](https://github.com/seerge/g-helper/issues/38) and see if any values change

**Comment by seerge** [comment]
@b4lance-d hello, you need to run scan script twice (when your feature is ON and OFF) and see if one of the values changes :)

**Comment by b4lance-d** [comment]
@seerge Done!

Anti-Ghosting mode N:
60023 : ffffffffffff0004 (-65532)
60024 : a36c8086 (2741796998)
60026 : 0 (0)
60061 : ffffffffffff0000 (-65536)
80041 : ffffffffffff0000 (-65536)
80042 : ffffffffffff0000 (-65536)
80043 : ffffffffffff0000 (-65536)
80044 : ffffffffffff0000 (-65536)
100051 : 1 (1)
110013 : 11 (17)
110014 : 0 (0)
110015 : ffffffffffff0000 (-65536)
110016 : ffffffffffff0000 (-65536)
110022 : ff (255)
110023 : ff (255)
Invoke-CimMethod : Generic failure 
At C:\Users\zephyrus\Desktop\scan-atkacpi.ps1:5 char:20
+ ...  $result = (Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -Cl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (AsusAtkWmi_WMNB...PNP0C14\ATK_0"):CimInstance) [Invoke-CimMethod], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand
 
110024 : ffff0000 (-65536)
Invoke-CimMethod : Generic failure 
At C:\Users\zephyrus\Desktop\scan-atkacpi.ps1:5 char:20
+ ...  $result = (Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -Cl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (AsusAtkWmi_WMNB...PNP0C14\ATK_0"):CimInstance) [Invoke-CimMethod], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand
 
110025 : ffff0000 (-65536)
110026 : ffffffffffff0000 (-65536)
110027 : ffffffffffff0000 (-65536)
120057 : 80000 (524288)
120061 : 1 (1)
12006c : 1 (1)
120075 : 3 (3)
130021 : 2 (2)
130022 : 1 (1)

[AGM-N.txt](https://github.com/seerge/g-helper/files/13220568/AGM-N.txt)

Anti-Ghosting mode 30:
60023 : ffffffffffff0004 (-65532)
60024 : a36c8086 (2741796998)
60026 : 0 (0)
60061 : ffffffffffff0000 (-65536)
80041 : ffffffffffff0000 (-65536)
80042 : ffffffffffff0000 (-65536)
80043 : ffffffffffff0000 (-65536)
80044 : ffffffffffff0000 (-65536)
100051 : 1 (1)
110013 : 0 (0)
110014 : 0 (0)
110015 : ffffffffffff0000 (-65536)
110016 : ffffffffffff0000 (-65536)
110022 : ff (255)
110023 : ff (255)
Invoke-CimMethod : Generic failure 
At C:\Users\zephyrus\Desktop\scan-atkacpi.ps1:5 char:20
+ ...  $result = (Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -Cl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (AsusAtkWmi_WMNB...PNP0C14\ATK_0"):CimInstance) [Invoke-CimMethod], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand
 
110024 : ffff0000 (-65536)
Invoke-CimMethod : Generic failure 
At C:\Users\zephyrus\Desktop\scan-atkacpi.ps1:5 char:20
+ ...  $result = (Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -Cl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (AsusAtkWmi_WMNB...PNP0C14\ATK_0"):CimInstance) [Invoke-CimMethod], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand
 
110025 : ffff0000 (-65536)
110026 : ffffffffffff0000 (-65536)
110027 : ffffffffffff0000 (-65536)
120057 : 80000 (524288)
120061 : 1 (1)
12006c : 1 (1)
120075 : 3 (3)
130021 : 2 (2)
130022 : 1 (1)

[AGM-30.txt](https://github.com/seerge/g-helper/files/13220578/AGM-30.txt)

I don't think the values have changed, what could this mean and what else can I try?

**Comment by seerge** [comment]
@b4lance-d it means that it's not being set via ACPI driver (like all other settings that Armoury / G-Helper set)

Nay be it's some other way, that I have zero ideas about. Why don't you just keep MyASUS specifically for that thing ? It's not very taxing for your laptop ...

**Comment by b4lance-d** [comment]
@seerge These values have been changed:
110013 : 0 (0) -> 110013 : 11 (17)
![librewolf_pEHG2yMsiv](https://github.com/seerge/g-helper/assets/53311537/dba0b159-d762-4d01-9f26-6f8f7c4f10e8)

**Comment by seerge** [comment]
@b4lance-d that's CPU fan speed :) 
https://github.com/seerge/g-helper/blob/f49e2ee1e8e466e3be36e1d73cc3d204bb4cd1c2/app/AsusACPI.cs#L55C1-L55C1

**Comment by rishavvroy** [comment]
Hey @b4lance-d  By mistake I pressed multiple keys On my asus laptop and this pop up appears 'anti ghosting' and after that I am not able to use my laptop keyboard only function keys are working. Can you help me to disable this.
