### ISSUE TITLE
Random dot in the update screan [Minor issues]

### ISSUE THREAD

**Issue by TheBossMagnus** [seerge/g-helper#1518]
**Describe the bug**
There is a random dot on the update screen in its default size:
<img width="459" alt="image" src="https://github.com/seerge/g-helper/assets/92474350/16505e2a-5f92-48e3-9380-e3a5bf90054f">
(Under BIOS update)
If I make the window wider at some point it disappears.

**Clear scenario to Reproduce**
1. Open updates windows

**Expected behavior**
No dot.

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Rog Strix G733PZ
 
 I KNOW IT'S REALLY MINOR, so feel free to close it

**Comment by seerge** [comment]
@TheBossMagnus hello, it's not a random dot, but part of a longer name ``BIOS Update ... <something>`` just make whole window bigger to read it full :)

This is how label resizes if it's too long and can't fit into 1 string ...
