### ISSUE TITLE
Asus Vivobook Pro 14x Support

### ISSUE THREAD

**Issue by jesvijonathan** [seerge/g-helper#1519]
This specific model of [asus creators laptop](https://www.asus.com/in/laptops/for-home/vivobook/vivobook-pro-14x-oled-m7400-amd-ryzen-5000-series/) is not fully supported.. 

- I there a way we could get gpu mode for this model ?
- also like some other model that g-helper supports.. add an option to disable igpu/dgpu  & run one at a time
- fan curves are not available, this variant 4 predefined fan profiles
- option to change display color profiles
- also a way to deal with trackpad/dialpad bloats ?

most importantly, a single button to reset everything back to factory default would be great !

**Comment by seerge** [comment]
@jesvijonathan 

- As far as I'm aware Vivobooks don'ts support disabling of dGPU. Do you have that option in Armoury / any other software ?
- Same applies to fan curves / do you have them natively ?

For color profiles you can just save and switch ICC profiles in windows color management app.

**Comment by jesvijonathan** [comment]
- nope, there ainth an option to disable gpu via myasus/creatorHub
- fan curves : no | fan profiles : yes
- ;(
- so, the 14x variant, like the pro Art, has dialpad on the trackpad..., there are some software from asus that are used to control the dialpad mode... those bloats are clunky, and would be nice if we had em in the ghelper

**Comment by seerge** [comment]
@jesvijonathan then it's obviously not possible to add GPU modes or curves, cause they are not supported by your device.

As for dialpad - I can imagine it's a separate USB input device and very specific. Since I don't have ProArt laptop I can't add anything :) If you want - you can implement it and add it as a PR

Closing then
