### ISSUE TITLE
Feature Request: Save keyboard backlighting brightness depending on power state

### ISSUE THREAD

**Issue by meowmeoe** [seerge/g-helper#152]
I'm not sure how possible this would be but I would love if the backlighting would be on while charging and off while on battery.  Between the refresh rate saving and the gpu power modes, this would provide more functionality while charging but also max battery life otherwise.

**Comment by seerge** [comment]
Added option to lower brightness on battery in https://github.com/seerge/g-helper/releases/tag/v0.40

**Comment by meowmeoe** [comment]
Awesome - can't believe how fast that was.  Could you make it go to max brightness on power and turn all the way off on battery as opposed to just lowering once?

**Comment by seerge** [comment]
@meowmeoe it's actually more tricky than it sounds :) I know a command to set +1 or -1 step of brightness, but don't have a way to a) read current brightness (i.e. to save it for future), b) set any (max or 0) brightness at the moment :)

That's why it's done in that way
