### ISSUE TITLE
ASUS TUF Gaming F15 cant enable dGPU at all

### ISSUE THREAD

**Issue by Lanevskyi** [seerge/g-helper#1520]
Hello!
I ran into the problem that when I launch any games (official or not), my video card does not work properly. The maximum that happens is that it is blocked at 210Mhz, which actually does not give any feeling that you bought a gaming laptop.
I really hoped that in your application the “Ultimate” button in setting GPU modes would help me with this problem, but I don’t have it...
Is this a problem on my end or does the app not support my laptop?
Thank you in advance for your response!

**Comment by seerge** [comment]
@Lanevskyi hello,

If you don't have ``Ultimate`` then your device doesn't have a MUX switch

As for the rest you should check your windows (gaming) settings :) and make sure that your game uses dGPU. App has nothing to do with that, it can only completely disable dGPU (``Eco`` mode), which as I understand is not your problem.

You have completely ignored issue requirements and didn't post a log, so I can't help anyhow here.
