### ISSUE TITLE
Customs Modes in GHelper Right click

### ISSUE THREAD

**Issue by alexonpeace** [seerge/g-helper#1522]
As the title states, right now only the inbuilt modes are available to change on right-clicking ghelper
right now the fastest way to change custom modes are either the hotkey (multiple times) or 3 clicks away and a 4th click to close the ghelper menu
it would be nice if the custom modes the user adds also were available to change in the right click menu

also how about something like this
![image](https://github.com/seerge/g-helper/assets/47172928/687c7b40-ec63-4c48-b552-2a1f4947984c)

**Comment by seerge** [comment]
@alexonpeace hello, 

I was already answering [exactly same question here ](https://github.com/seerge/g-helper/discussions/1444)

I don't want to overload (already cluttered) UI even more :) hotkeys should be enough

**Comment by alexonpeace** [comment]
What's the hotkey for previous mode, couldn't find in FAQ

**Comment by seerge** [comment]
@alexonpeace ``Fn + Shift + F5``

**Comment by alexonpeace** [comment]
@seerge 
There is no Fn Key in keyboard

**Comment by seerge** [comment]
@alexonpeace there should be according to how your model looks like on a pictures https://rog.asus.com/laptops/rog-strix/2021-rog-strix-scar-15-series/

Anyway for backwards mode cycling just press Shift + your usual key that you use for modes

**Comment by alexonpeace** [comment]
@seerge 
Ctrl + Shift + F5 for cycling forward and Fn + Shift + F5 for cycling backward
but what about external keyboards

**Comment by seerge** [comment]
@alexonpeace for external keyboard you can use ``Ctlr+Shift+Alt+F5``
