### ISSUE TITLE
Backlight settings for FlowX13 2023

### ISSUE THREAD

**Issue by mrunknown9999** [seerge/g-helper#1523]
The keyboard backlight settings for FlowX13 2023 have no effect for Boot ,Sleep and Shut down.
Is it normal for the battery charge limit slider to be very laggy? It does not move in realtime with the mouse.
[log.txt](https://github.com/seerge/g-helper/files/13164554/log.txt)

**Comment by seerge** [comment]
@mrunknown9999 hello,

Sleep is a double-blinking animation (happens only when laptop hardware is properly sleeping, i.e. after few minutes windows goes to sleep). It could be that your device simply doesn't have that mode at all (after all X13 has only limited white backlight). 

I assume AC also can't change that anyhow? :)

As for battery charge limiter being "laggy". I have noticed similar on Rog Ally. It's cause a "call" to set charge limit is a very slow on response, and unfortunately it can't be parallelized anyhow (so UI will also lag until call is running). Unfortunately I can't really "fix" that anyhow + you don't change charge limit that often. 

Sometimes rebooting helps to speed that thing up.
