### ISSUE TITLE
Power Modes Fan FlowX13 2023

### ISSUE THREAD

**Issue by mrunknown9999** [seerge/g-helper#1525]
I looks to me as if the power mode fans do not work correctly with FlowX13 2023. The Balanced mode for example does not stop the fans even if the temp is at 30 degrees C. The fan is always on in this mode. Turbo and Silent turn the fans off until the 50 degree mark.
If I stopped G-Helper, under balanced mode the fans are quiet until the 50 ish degree mark gets hit.
![Screenshot 2023-10-25 140358](https://github.com/seerge/g-helper/assets/128497652/d5c3d4a7-7d33-405d-a69b-5e4499c8d9d3)
[log.txt](https://github.com/seerge/g-helper/files/13164900/log.txt)

**Comment by seerge** [comment]
@mrunknown9999 hello

G-Helper d[oesn't control your fan speeds ](https://github.com/seerge/g-helper#how-does-g-helper-control-my-fan-speeds) . Apparently this is what the default fan behavior for your laptop :)

There is nothing to "fix" here
