### ISSUE TITLE
Keyboard Backlight turning on during boot even when the option is unchecked in Extras 

### ISSUE THREAD

**Issue by XynoCrest** [seerge/g-helper#1527]
**Describe the bug**
- My laptop only has a White Backlight.
- The issue is with the options under the Laptop Backlight Section inside Extras, I feel like they don't work as intended.
             <img width="366" alt="image" src="https://github.com/seerge/g-helper/assets/140979619/95ae151f-b361-4bd5-93f3-ed2b69a8b87b">

- I only have Awake check-marked and I want the laptop backlight to only turn On and Off using the Fn+F2/F3 keys which controls the backlight brightness. 
- However, when I have only Awake check-marked the backlight also turns on during boot and turns off only after logging into windows.
- The only way to stop the backlight from turning on during boot is to uncheck everything, but when I do that I can no longer control the backlight using Fn+F2/F3.

**Expected behavior**
The keyboard backlight shouldn't turn on during boot, when boot is unchecked. 

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13170556/log.txt)

**Desktop**
 - OS: Windows 11, Version 22H2 (0S Build 22621.2428)
 - Laptop model: ROG Zephyrus G15 GA503RM, (G15 2022)

**Asus software**
- Armoury Crate and MyASUS UNinstalled
- No Asus services running in background

**Comment by seerge** [comment]
@XynoCrest everything after splash logo is "awake" state, even when windows is loading.

App saves  and remembers backlight, and as soon as you log in - it turns keyboard off, before that is out of control, and is up to your hardware

**Comment by XynoCrest** [comment]
Thank you so much for the explanation. 

I have another question though - 
- If you have everything disabled, the laptop boots without any backlight. 
- But if you want to turn on your backlight using Fn+F2/F3, you need to go into Ghelper and checkmark the awake button. 
**So my question is** - is it possible to make it so that pressing Fn+F2/F3 automatically turns on the Awake option without you having to go into Ghelper and turning it on manually?

**Comment by seerge** [comment]
@XynoCrest that's a bad idea imho :) as 99% of the devices simply remember backlight status. And setting keyboard "power modes" (checkboxes under extra) every time user changes backlight can cause lots of unpredictable consequences

**Comment by XynoCrest** [comment]
Ah I see, makes sense. Thank you!
