### ISSUE TITLE
Battery charge limit problem

### ISSUE THREAD

**Issue by MahyarSFI** [seerge/g-helper#1528]
I have a G15 2022 (GA503RM, Bios 315, Windows 11 22H2 Build 2428) and have a problem with Battery charge limit feature on G-Helper, So if I stop and disable all of the Asus services and set battery charge limit on 50% battery will go over 50% and won't stop (MyASUS only support 60%, 80% and 100%) but if I set battery limit to 55% it will stay on 55%
[log.txt](https://github.com/seerge/g-helper/files/13187896/log.txt)

**Comment by Kikimahe** [comment]
Hi

If My ASUS defines a load limit at 60% and Ghelper at 55%, the two software programs may conflict.
MY ASUS and GHELPER must have the same charge limit (60).

@Seerge will confirm, but I think if you want to keep the load limit at 55, you need to uninstall MY ASUS.

**Comment by seerge** [comment]
@MahyarSFI hello

From log i see that you have Asus Optimization service running, and it sets own charge limit

```
10/27/2023 11:14:22 AM: Optimization service is running
```

So I would advice to stop it from ``Extra`` -> ``Stop Services`` :) (and after that set a custom limit in the app)

On a side note, not all devices support any custom values for charging, it could be that yours supports only 60% for example, and above :)

Good luck
