### ISSUE TITLE
Fan speed issue 

### ISSUE THREAD

**Issue by Orsso** [seerge/g-helper#1530]
## NOTE

**Describe the bug**
Fan curve does not apply when set speed to 0

**Clear scenario to Reproduce**
Set fan speed to 0 RPM until 65°C
Apply curve 
Fans rotate at 4500 RPM at 60°C (with non constant speed on constant temperature)

**Expected behavior**
Use only passive cooling until CPU reach 65°C

**App Logs**

[log.txt](https://github.com/seerge/g-helper/files/13192602/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/106078665/5dc4e929-a477-45cb-afae-58925ddb8552)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - G14 2020 (R7 4800HS/ RTX 2060)

**Asus software**
- Armoury Crate not installed
- MyASUS not installed
- No ASUS services running

**Additional context**
The curves apply in my "Ultra Cooling" mode with a maximum speed fan configuration but with the other modes it seems approximate. What is very strange is that in my "passive" mode with speed 0 configured, the speeds are lower when I do not apply the curves (around 2500 RPM at 55°C vs 3500 with curve applied). To summarize : 

When a higher speed than factory is requested > curves apply

When a lower speed than factory is requested > 
Speed ​​is higher than when custom fan curve is disabled

![image](https://github.com/seerge/g-helper/assets/106078665/6f52b79e-7751-4adc-92fd-fae1f1fab51f)

![image](https://github.com/seerge/g-helper/assets/106078665/dcd03822-caed-40b9-a32e-933558505d6f)

Any idea where the problem come from ? BIOS up to date.

**Comment by Orsso** [comment]
Update: Apparently the problem seems to mainly occur when the computer is charging. However, even on battery, sometimes the fans start to spin randomly. Tweaking the curve in the software and setting it back to 0 (where it was) makes them stop again. It therefore seems that the BIOS sometimes bypasses G-Helper instructions and sends random fan speeds.

**Comment by seerge** [comment]
@Orsso hello,

G-Helper doesn't control your fans :) it's absolutely possible that BIOS will decide to obey your custom settings, especially such custom ones when it forces fans to stay off up to 70C

Try to modify curve so it's more dots in 70C+ zone that are not zero, may be it will help.

Anyway I can't do anything about it

On a side note: I see that you are setting GPU clock to negative -250, it's actually makes it run on higher power for normal clocks (extra reason to get hotter). unless you have some hardcore crashing issues in games i wouldn't do that ;)
```
27/10/2023 22:21:19: SET GPU CLOCKS: -250, -250
```

**Comment by seerge** [comment]
@Orsso Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks
