### ISSUE TITLE
Core configuration tool

### ISSUE THREAD

**Issue by Fusuy100** [seerge/g-helper#1531]
I noticed that armory crate allows you to enable and disable cores on 13th gen intel laptops, I was wondering if it's possible to add this to g-helper. This could open the door for improved battery life and higher boost clocks

**Comment by seerge** [comment]
@Fusuy100 hello, this is a duplicate of https://github.com/seerge/g-helper/issues/1507 and couple others,

If you want you can follow advice from that topic with a scan script :)
