### ISSUE TITLE
Feature for performance bug of asus

### ISSUE THREAD

**Issue by MyBadWorld** [seerge/g-helper#1532]
There is a bug on 2021 asus tuf gaming laptops, ( mine is tuf gaming 2021 f17 ).  These laptops work so slowly ( averagely 1- 1.3 ghz) on battery mode, even though battery plans and settings are max and gpu off and battery left more than 70%.  To fix this problem, there is a bug that I ve learned on reddit or smw :  turn on the discrete gpu, then turn on eco mode immediately. Then we reach 2ghz  cpu clock speed.   But both armory crate and ghelper encounter with problem when switching, ghelper stops and if we click, it crashes.  Can we add a feature to do this process ( that bug)  automatically, when the laptop is plugged out?  Specially, when the screen goes off while changing the refresh rate, this process may also happen simultaneously.

**Comment by seerge** [comment]
@MyBadWorld hello. I don't plan to add such extremely exotic things to the app.

But you can create a macro with autohotkey or similar app to do that
