### ISSUE TITLE
Multizone Zephyrus G14 4090 miniled

### ISSUE THREAD

**Issue by Drewligarchy** [seerge/g-helper#1534]
Hi -

Excuse me if this is posted in the wrong area but hoping you can help.

I installed g-helper alongside armorycrate, amongst other reasons, because the multizone toggle in AC is greyed out, so I thought it wasn’t selected.

in g-helper, however, there is a red box around multizone and a grey box around 165+OF. Does this mean multizone is in fact on? Can I verify, because if so AC and g-helper are reporting different info.

all my drivers are up to date including Nvidia/AMD from their respective sites.

Thanks in advance for any help you can provide.

**Comment by seerge** [comment]
@Drewligarchy hello,

Yes - it means multizone is ON
Selected refresh rate button just marks current refresh rate.
