### ISSUE TITLE
Additional key bindings for Fn keys

### ISSUE THREAD

**Issue by hockinsk** [seerge/g-helper#1538]
On an ASUS Z13 keyboard there's functions for F1-Volume Mute, F2/F3-Volume Level, F4 Mute Mic, F5-Fan Control, F6-Screenshot, F7/F8-Brightness, F9-Screenshare, F10-Touchpad Enable/Disable, F11-Keyboard Backlight, F12-Airplane Mode

F4, F5, F7, F8, F10 & F11 do not function after switching to g-helper which only allows control of F2,F3,F4 bindings. Is it possible to enable more function keys? Thanks.

**Comment by seerge** [comment]
@hockinsk hello,

All those keybindings will be processed by app if you will stop Asus Optimization Service (from ``Extra`` menu or manually), cause otherwise that service handles them

Cause you have ignored issue template and didn't include any log I can't help further

**Comment by hockinsk** [comment]
Thanks for the response. I have everything disabled I beleive, or is there another service calls Asus Optimization under another name?
![image](https://github.com/seerge/g-helper/assets/1609513/8c7d38f0-0193-4f03-b832-605213b18f4a)

**Comment by seerge** [comment]
@hockinsk then after restarting g-helper it will take over hotkeys.

But keep in mind that such things Fn+F6 (screnshot) or Fn+F9 (presentation mode) are handled purely by hardware (they just emit appropriate windows hotkey combination), so if even they don't work - it's something with keyboard or it's connection itself :)

![image](https://github.com/seerge/g-helper/assets/5920850/4324fc5f-a648-40c5-b3ca-ba6eff07171e)

**Comment by hockinsk** [comment]
OK, thank you. This is a fantastic utility, many thanks for developing it!
