### ISSUE TITLE
[Not-a-BUG] Windows power plans not switching

### ISSUE THREAD

**Issue by LoreAPC** [seerge/g-helper#154]
**Describe the bug**
When I switch performance modes in G-Helper windows power plan doesn't switch (feature from v0.28).
IMPORTANT: Armoury Crate still installed. Power plans correctly switches when changing modes in AC. In itself possible cause of the problem, see hypothesis below.

**To Reproduce**
1. Check actual Windows power plan
2. Change performance mode in G-helper
3. Check windows power plan again. For me it was the same from point 1.

**Expected behavior**
Windows power plan should change.

**Desktop (please complete the following information):**
Zephyrus G14 5800HS + RTX 3060
Windows 10
 
**Additional context**
As I said I'm testing G-Helper with AC still installed, so I don't exclude an incompatibility between the two.

Here are the outputs of the command "powercfg /l" for every mode in AC:

silent
GUID combinazione risparmio energia: 115e0175-ebfe-409a-a7f8-5dd42cb737d3  (ASUS Recommended)
GUID combinazione risparmio energia: 381b4222-f694-41f0-9685-ff5bb260df2e  (Bilanciato)
GUID combinazione risparmio energia: 64a64f24-65b9-4b56-befd-5ec1eaced9b3  (Silent) *

Performance
GUID combinazione risparmio energia: 115e0175-ebfe-409a-a7f8-5dd42cb737d3  (ASUS Recommended)
GUID combinazione risparmio energia: 381b4222-f694-41f0-9685-ff5bb260df2e  (Bilanciato)
GUID combinazione risparmio energia: 64a64f24-65b9-4b56-befd-5ec1eaced9b3  (Silent)
GUID combinazione risparmio energia: 27fa6203-3987-4dcc-918d-748559d549ec  (Performance) *

Turbo
GUID combinazione risparmio energia: 115e0175-ebfe-409a-a7f8-5dd42cb737d3  (ASUS Recommended)
GUID combinazione risparmio energia: 381b4222-f694-41f0-9685-ff5bb260df2e  (Bilanciato)
GUID combinazione risparmio energia: 64a64f24-65b9-4b56-befd-5ec1eaced9b3  (Silent)
GUID combinazione risparmio energia: 6fecc5ae-f350-48a5-b669-b472cb895ccf  (Turbo) *

If I interpret your code correctly, the last lines of NativeMethods.cs calls for power plans with totally different GUIDs.

My hypothesys are:
1. Armoury Crate messes with the default power plans, changing the GUIDs and adding/deleting them at every power mode switch.
2. Every version of the notebook has slightly different power plans in Windows. I've never formatted the pc so this is the default Windows build of the machine.

Let me know If you need any help in troubleshooting.

Also I second the request from another reported issue that you share your Paypal account so we can make a donation as a thank for your continuous effort.

**Comment by seerge** [comment]
Hello, g-helper never switched windows power plans (as they almost deprecated in windows11). It switches "Power modes" under System -> Power & Battery as they have real impact.

<img width="580" alt="Screenshot 2023-03-14 205953" src="https://user-images.githubusercontent.com/5920850/225153907-f9b89220-5882-475c-ac87-ca01899aa827.png">

Make sure that you use windows power plan that allow that switching (as I remember armory's Turbo/Silent lock that setting completely)

**Comment by LoreAPC** [comment]
Man I was sooo off the tracks! Thanks I just verified that the bar changes its position when changing power modes in G-Helper.

As you have noticed I'm not very familiar with W11 (vertical taskbar gang) so I didn't know they removed the classic power plans.

Thank you very much for the fast reply and for sharing your work!
