### ISSUE TITLE
gpu mode change automatically

### ISSUE THREAD

**Issue by forgethekidneys** [seerge/g-helper#1540]
**Describe the bug**
I choose eco gpu mode, then I turn the laptop off and on. When the laptop is turned on, standart mode is turned on.

**Clear scenario to Reproduce**
1. choose eco gpu mode
2. turn off laptop and turn on laptop
3. open g helper
4. switched from eco mode to standart mode automatically

 - OS Windows 11
 - ASUS TUF FA507RM

**Asus software**
- just ghelper
- no myasus or armory crate
- closed asus services from ghelper

**Comment by forgethekidneys** [comment]
I want the mode I choose to be permanent.

**Comment by seerge** [comment]
@forgethekidneys hello

Most devices just remember dGPU state (enabled / disabled) after restart as well. If it doesn't in your case - this is how it's programmed in BIOS. 

You can manually force GPU mode by adding following line to app config

```
"gpu_mode_force_set" : 1,
```

**Comment by forgethekidneys** [comment]
it doesn't work i changed then restart and it automatically change eco mode to standart mode [https://prnt.sc/vTW1-lyWpe7w](url)
here

**Comment by forgethekidneys** [comment]
i disable dgpu then it turns standart mode when i turn off on

**Comment by seerge** [comment]
@forgethekidneys you need to set ``1``, not 0

```
"gpu_mode_force_set" : 1,
```

I means that app will remember last used GPU mode (Eco / Standard) and force it every time it restarts (if a different one is set)

**Comment by forgethekidneys** [comment]
it works thank you so much
