### ISSUE TITLE
Dynamic Refresh Rate on Battery Support

### ISSUE THREAD

**Issue by Sanaan01** [seerge/g-helper#1541]
Hi,

I am wondering if the following feature **dynamic refresh rate** can be added in Auto mode so it switches to that instead of 60 hertz on battery. A tick box in the extra section may look good

![image](https://github.com/seerge/g-helper/assets/81903566/0e6e07a4-bd8f-4231-8a31-36fed28075be)

https://devblogs.microsoft.com/directx/dynamic-refresh-rate/ 
it seems that its in the middle, it doesn't affect battery life that much while still giving the high hertz experience.

Ik it says 83 hertz on ghelper and other apps as well but it doesn't feel like 83 hertz it feels the same and 165 hertz

**Comment by seerge** [comment]
@Sanaan01 hello,

It doesn't seem to be possible to set dynamic refresh rate via windows API that app uses to detect displays / set / get refresh rates.

Next to that I simply don't have a single device that would support that at the moment :)

Why wouldn't you just set dynamic refresh rate in windows and forget about it ? G-Helper won't interfere in settings as far as Auto refresh mode is ``OFF``
