### ISSUE TITLE
Toggle boost based on temperature feature

### ISSUE THREAD

**Issue by PhucHauDeveloper** [seerge/g-helper#1542]
I hope you will add a feature similar to toggle boost based on temperature, I see a similar software for G14 at https://github.com/furui/g14boost
but it doesn't work on my GA402RK (because it's too old, hasn't been updated for 3 years), I hope you can integrate it because this is quite nice as I can boost cpu in daily tasks and stop boost when the temperature is too high (especially when I play games) to avoid overheating but still ensure general performance. Turning it off can cause low clock speed while turning it on can cause overheating. I found this feature won't be confusing because the CPU menu on my GA402RK code doesn't have too many options. Your Ghelper software is very good and I hope you continue to develop it, thank you<3

**Comment by seerge** [comment]
@PhucHauDeveloper hello

Your temperatures are result of power consumed by components, not the clocks :) And windows / chipset drivers is way better in deciding what clocks to use and when.

Next to that wild swings in temperature will lead to constant boost ONs and OFFs.

**Comment by seerge** [comment]
PS. There is a also a CPU limit setting (throttle temp) in the app, that will literally drop power (and clocks) if your CPU reaches target temperature

**Comment by PhucHauDeveloper** [comment]
Thank you @seerge for taking the time to reply to me. Aggressive CPU acceleration can cause overheating and shutdown on my laptop, and many Reddit users have the same problem. The solution they gave was to disable it. That can reduce up to 10 degrees when gaming and doesn't affect fps much, but it helps quite a bit when I work(like code and VM) normally. Limiting the CPU temperature reduces fps. I have to create many profiles for daily use (40–50 degrees), watch movies (35–40), code (45–50), and play games (75–90). This takes time every time. When converting, automating it will help a little. I hope you should check out the software and see if it's possible, and if I'm wrong, I'm sorry for bothering you.

**Comment by AudreyAP** [comment]
>  Aggressive CPU acceleration can cause overheating and shutdown on my laptop

The issue you are having is that the cpu temp is overshooting the cooler, hitting 96c or whatever AMDs emergency threshold is, and then the CPU is immediately shutting down to protect itself. 

The solution to this is to use ghelper to limit CPU temp to 95 or 94. This will stop the overshoot issue. Disabling to boost this is ridicuous, Reddit subs should be ignored 95% of the time as they generally have no clue what they are talking about. 

> I have to create many profiles for daily use (40–50 degrees), watch movies (35–40), code (45–50), and play games (75–90). This takes time every time. 

There is absolutely no need to create a bunch of profiles for different usage scenarios, just use silent/balanced in ghelper and fix your power plan. The default Asus power plan forces the cpu to sit at 80% of max clock when plugged in to AC. Change it to match this and you will have no heating issues. 

![image](https://github.com/seerge/g-helper/assets/130399040/022d42e1-c726-4327-b7b3-fa28667791d6)

**Comment by PhucHauDeveloper** [comment]
Thank you for answering me<3
