### ISSUE TITLE
`Enable GPU on shutdown` Function will reset windows `When I close the lid` setting

### ISSUE THREAD

**Issue by rainbowflesh** [seerge/g-helper#1543]
**Describe the bug**
`Enable GPU on shutdown (prevents issue with Eco mode)` function will reset windows power setting `Power and sleep buttons and lid settings` > `Plugged in` option to `sleep`, which I manually change to `Do nothing`.

**Clear scenario to Reproduce**
1. Go to Ghelper `Extra` panel and enable `Enable GPU on shutdown`
2. Go to Windows Control Panel\Hardware and Sound\Power Options, and change `Plugged in, When I close the lid:` to `Do nothing`
3. Lid your laptop when GPU mode in `Eco`
4. Ghelper will automatically change GPU mode to `Standard` and windows will go sleep

**Expected behavior**
No reset to sleep, lid will `Do nothing`, aka `Clamshell Mode`.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13206105/log.txt)

**Screenshots or screencasts**
![20231030215724](https://github.com/seerge/g-helper/assets/20819692/b19ed28a-8487-419b-950e-05996b38d242)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: ROG Flow Z13 GZ301VV

**Asus software**
- Nothing, clean system.

**Additional**
- This reset only effect `Plugged in` side.
- `Auto Toggle Clamshell Mode` not work?

**Comment by seerge** [comment]
@rainbowflesh GPU on shutdown has nothing to do with your lid and sleep :)

You have Clamshell mode enabled, and app adjusts lid close action

```
2023/10/30 22:04:50: Changed Lid Action to 1
2023/10/30 22:04:50: Disengaging Clamshell Mode
```

If you don't want your lid close action to change, just uncheck Clamshell mode :)
