### ISSUE TITLE
Additional Asus to Disable/Stop(GameSDK)

### ISSUE THREAD

**Issue by Rinzler081** [seerge/g-helper#1546]
**Is your feature request related to a problem? Please describe.**
N/A
**Describe the solution you'd like**
Add "C:\Program Files (x86)\ASUS\GameSDK Service\GameSDK.exe" to be disabled.. Assuming it doesn't do anything useful that g-helper doesn't do

**Describe alternatives you've considered**
N/A
**Additional context**
"C:\Program Files (x86)\ASUS\GameSDK Service\GameSDK.exe" service runs even after disabling all asus services

**Comment by seerge** [comment]
@Rinzler081 hello,

App is not designed to fight or uninstall Armoury, it has own (and absolutely fine) uninstall tool :) Just use that as [recommended in readme](https://github.com/seerge/g-helper#recommendations-optional)

> It's not recommended to use the app in combination with Armoury Crate services, because they adjust the same settings. You can [uninstall it using AC own uninstall tool](https://dlcdnets.asus.com/pub/ASUS/mb/14Utilities/Armoury_Crate_Uninstall_Tool.zip?model=armoury%20crate). Just in case, you can always install it back later.

**Comment by Rinzler081** [comment]
@seerge  understood..
On a side note.. do you know what GameSDK even does?

**Comment by seerge** [comment]
@Rinzler081 most probably responsible for searching for new games (in steam / xbox library / etc) and letting you create custom profiles for each game in AC
