### ISSUE TITLE
(Since new Flow Z13 System Control Interface?) fn f7 / f8 for screen brightness don't work unless Asus services are running

### ISSUE THREAD

**Issue by jorismak** [seerge/g-helper#1547]
**Describe the bug**
I don't know for sure if this is happening since the latest Asus Z13 System Control Interface update that was released Oct 26th (give or take), but before this was working fine.

Now the fn f7/f8 buttons don't work for screen brightness.

When I start the MyAsus app, it says it needs to repair things (because G-Helper stopped all the services). Once this is done, the brightness keys work again.

If I click the 'stop' button in G-Helper to stop all the services again, the brightness keys stop working.

Also, clicking the 'start' button to let G-Helper start the Asus services, makes the buttons work again.

When the buttons are _not_ working, the brightness slider in the Windows taskbar _is_ working fine. So it appears to be a keybinding issue, not a control issue.

**Clear scenario to Reproduce**
Like described above

**Expected behavior**
Like described above

**App Logs**
Included as zip
[logs_and_config.zip](https://github.com/seerge/g-helper/files/13213826/logs_and_config.zip)

**Screenshots or screencasts**
N/A

**Desktop (please complete the following information):**
 - OS:  Windows 11 22H2 
 - Laptop model Asus Flow Z13 2022 GZ301ZE bios 317

**Asus software**
```
Item                       Version     
----                       -------     
Armoury Crate UWP App      5.7.3.0     
ROG Live Service           2.2.5.0     
Aura Service (Lighting Service)  3.07.25     
Armoury Crate service      5.7.3       
Aura Wallpaper Service     Not installed
Aura SDK                   3.04.39     
ASUS Aac_NBDT HAL          2.5.30.0    
```

- MyASUS installed 3.1.29.0, Control Interface 3.1.20.0

**Comment by seerge** [comment]
@jorismak hello,

I see how you were pressing only brightness down keys on Oct 29

```
29/10/2023 19:49:06: Key: 16
29/10/2023 19:49:06: Brightness = 16 : 0
29/10/2023 19:49:06: Key: 16
29/10/2023 19:49:06: Brightness = 16 : 0
29/10/2023 19:58:47: Key: 16
```

And it seem to work. Try to stop all services and then restart app, to make sure it's aware that Asus Optimization service is not running.

> When the buttons are not working, the brightness slider in the Windows taskbar is working fine. So it appears to be a keybinding issue, not a control issue.

If it's indeed the case, then it's probably some windows / driver issues. As G-Helper just sends same brightness up / down commands to keyboard as asus service. Brightness adjustment is done by windows, and since slider moves - it's happening already.

**Comment by jorismak** [comment]
I made a reply and it seems gone.. maybe forgot to hit submit.. here we go again:

I made sure all asus services are disabled (including the 'asus optimization' service that seems to be the one making brightness work or not).

Then rebooted the machine, so it all starts up clean. And then pressed the brightness buttons (both of them) multiple, multiple times.
[log.txt](https://github.com/seerge/g-helper/files/13216217/log.txt)


> If it's indeed the case, then it's probably some windows / driver issues. As G-Helper just sends same brightness up / down commands to keyboard as asus service. Brightness adjustment is done by windows, and since slider moves - it's happening already.

You misunderstood. When I drag the slider _with my mouse_, the brightness does change. So the Windows brightness slider works. But if I press the buttons, the slider doesn't change (and the brightness doesn't change, and I don't see the OSD prompt for the brightness change).

Volume does still work BTW.

Starting the 'AUS Optimization' service and the brightness buttons work again. Stopping it, and they stop working again.
(And yes, I tried restarting g-helper after that).

I'm trying to see if I can downgrade my ASUS Control Interface driver.  3.1.20.0 seems to change this.

**Comment by seerge** [comment]
@jorismak 

I don't see a single entry of a keypress for brightness in the log (apparently they don't reach the app). May be it's something that new Asus Control Interface has changed? Do you have your keyboard connected via BT or physically ?

At the same time app connects and listens for new key events : 
```
31/10/2023 13:21:32: Input: \\?\hid#vid_0b05&pid_18c6&mi_02&col01#7&11e16951&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
```

Volume controls are emitted on hardware level :) they are not processed by the app

**Comment by jorismak** [comment]
No other keyboards connected (at the moment, I can try if that helps you ).

**Comment by seerge** [comment]
@jorismak well, ``hid#vid_0b05&pid_18c6`` is your correct keyboard :) it supposed to emit special HID events (i.e keys) when you press most (not all) Fn+FX keys, and some key combos like Fn+C or Fn+V

**Comment by jorismak** [comment]
Only the normal windows things work (like volume, snipping tool, project).
mousepad on/off, keyboard brightness, power-profile buttons don't work.
(and yes, they start working when the 'asus optimization' service is started).

So this maybe 'not working' for quite some time, and I didn't notice it because I was running with Asus services enabled (they got re-enabled with an MyAsus app update or something).

Or, the only change I recently made to the OS, is installing Razer Synapse for mouse control.

Or, installing Control Interface 3.1.20.0 updated some firmware and things now just work differently on a hardware level :).

**Comment by jorismak** [comment]
(I tried removing the devices under 'Keyboard' and rebooting).
It lists 3 'hid keyboard device' entries and a regular PC/AT Enhanced ps/2 keyboard. After removing+reboot, they appear back and no change in behaviour.


Going back to 3.1.18.0 also seems to restored my 55watt power limits. Or maybe that's another reason. It's a real mistery to me when this device limits itself to 30 watts even though throttlestop is setup for 55w, and other times suddenly the 55watt limits work and I get full performance.

Maybe the external monitor connected changes some things, maybe I started 'MyAsus' and it wanted to install 3.1.20.0 again but my power limits are now locked to 30watts again :(.  (cinebench r23 with 30watts is +/- 7500 to 7700 score, cinebench r23 with 55watts is +/- 11000 score. Connecting official asus charger, setting 'turbo profile' in armory crate (which is locked out otherwise) and I get cinebenchr23 scores of close to 14000)

**Comment by seerge** [comment]
@jorismak try this build, and post a log from it (i have added more verbose logging where it searches for available input devices for keyboard and will list them if it's more than one by some reason)

[GHelper.zip](https://github.com/seerge/g-helper/files/13216828/GHelper.zip)

**Comment by seerge** [comment]
@jorismak apparently there are 2 input devices in your case

Try this build, it should connect to another one 
[GHelper.zip](https://github.com/seerge/g-helper/files/13217117/GHelper.zip)

**Comment by jorismak** [comment]
hey, success!
[log.txt](https://github.com/seerge/g-helper/files/13217184/log.txt)

When I go to stop the asus-services through G-Helper, after clicking 'stop' it still lists 1 service. I tried restarting and trying again, but still 1 service remains (this wasn't the case on earlier builds?, even earlier today).

But I've looked through the services list in `services.msc`, and I can't seem to find anything that's still running :).

**Comment by seerge** [comment]
@jorismak try if this build still works 

[GHelper.zip](https://github.com/seerge/g-helper/files/13217443/GHelper.zip)

**Comment by jorismak** [comment]
Still works!
[log.txt](https://github.com/seerge/g-helper/files/13218103/log.txt)

**Comment by seerge** [comment]
@jorismak great, I will include it in next release then

**Comment by jorismak** [comment]
Thanks so much for helping!
