### ISSUE TITLE
Add ability to schedule battery charge limit for specific days of the week

### ISSUE THREAD

**Issue by himankpathak** [seerge/g-helper#1549]
**Is your feature request related to a problem? Please describe.**
I personally like to keep my laptop charge limit at 60% but on the days I am going to uni, I need it to be at 80% or more to last till the end of the day.

**Describe the solution you'd like**
I am pleased with the one-time 100% charge feature added with [v0.129](https://github.com/seerge/g-helper/releases/tag/v0.129). This feature can be a follow-up to that feature.
We can add a new popup in the battery charge section from where the users can open a popup and enable an advanced scheduler.
The scheduler will allow users to set specific charge limits for Monday - Sunday. Users can select a checkbox for a particular day of the week and set a specific limit. We don't need to be too aggressive with day checks, we can check about every hour and every time the computer starts or wakes from hibernate/sleep to flip the charge limit.
If we want to allow even granular control, we can add two more drop-downs for start and end times for that particular day.

**Describe alternatives you've considered**
I found no alternatives for this.

**Comment by seerge** [comment]
@himankpathak this is very exotic request to be honest :) And I don't want to overload app UI with such specific things, sorry

Easiest solution personally for you would be write a script that would swap 2 config.json files (with 60 / 80 charges) based on a day of the week and start app after ;)

**Comment by himankpathak** [comment]
Yeah, it is very specific. Maybe if more people need this they can upvote this.

Thanks for the suggestion about swapping the config.json file. I will look into it. 👍

**Comment by bourbonbourbon** [comment]
@himankpathak hey I have created a simple python script for the featured that you requested. Feel free to check it out here and start it if you like it https://github.com/bourbonbourbon/ChangeChargeLimit . Check the README for proper setup/installation.
