### ISSUE TITLE
Clock not centered and weird font

### ISSUE THREAD

**Issue by Arcenus** [seerge/g-helper#155]
**Describe the bug**
When selecting clock mode for the Anime Matrix the clock is situated on the top and is small and not legible. Photo: https://imgur.com/a/6XFkdfq

**Expected behavior**
Expected behaviour like in the picture of seerge's clock mode here: https://github.com/seerge/g-helper/releases 
If possible I would like to use the original ASUS font for the clock, I think it is more pleasing, but that is subjective. I've uploaded the font installer, if it helps.
[Font_ROG_ASUS_V100.zip](https://github.com/seerge/g-helper/files/11088558/Font_ROG_ASUS_V100.zip)

**Laptop:**
 - Windows 11 up to date.
 - G14 2020 model, GA401IV, with Ryzen 7 4800HS and RTX2060

**Comment by Arcenus** [comment]
Sure, my user on Discord is Arcenus#0911

I'll delete this last message when we chat, so it's not out there :3

**Comment by yudapedia** [comment]
I am using G14 2022, and I have the same problem.
