### ISSUE TITLE
Fans do not switch on unless I restart

### ISSUE THREAD

**Issue by Shuaib-S** [seerge/g-helper#1552]
Whenever I start an application that requires the fans i.e the temp of cpu and gpu have it the required level, the fans do not swtich unless I restart the pc. Many times will I see 85 degress cpu and 0 rpm.  If the temp drops back to levels that dont require fans and later on do , I will have to restart it. This is not a hardware issue as I don't face this problem with the armoury crate.

**Comment by seerge** [comment]
> ## NOTE
> Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. Please respect the time of the developer. Thanks.

> [How does G-helper control my fan speeds?](https://github.com/seerge/g-helper#how-does-g-helper-control-my-fan-speeds)
It doesn't. Your BIOS does (same as in case with Armoury). What G-helper can do - is (optionally) set a custom fan profile to current performance mode consisting of 8 pairs of temperature + fan speed % via same endpoint armoury seem to use.

**Comment by seerge** [comment]
@Shuaib-S Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks

**Comment by Shuaib-S** [comment]
Hey , thank you this is actually very cool!  I found out afterwards btw that my specific Asus model model comes with a BIOS bug that means the computer still thinks it's sleeping after closing the lid , so now I just  changed the behavour of what closing my lid does to avoid the issue .

**Comment by Shuaib-S** [comment]
very random sidenote, my mouse dpi on G-helper is reset every time the laptop restarts to the same 2 profiles(1600 dpi) and (400 dpi) . I can change it but when I restart it'll revert.  My guess is it's the dpi that was set from Armoury crate before I deleted it? Not sure .
