### ISSUE TITLE
RGB Timer does not work when Laptop lid is closed

### ISSUE THREAD

**Issue by xSimone** [seerge/g-helper#1553]
**Describe the bug**
RGB Timer does not work when Laptop lid is closed

**Clear scenario to Reproduce**
1. Go to Laptop Keyboard > Extra > Set off time
2. Close Lid

**Expected behavior**
RGB should turn off after X seconds, but does not when lid is closed.

 - OS: Windows 11
 - Laptop model Scar 18

**Asus software**
None 

I leave my laptop running when I sleep, but the RGB does not turn off after X time.

**Comment by seerge** [comment]
@xSimone when laptop lid gets closed, windows goes to sleep and suspends all apps. So G-Helper is effectively suspended (along all other apps on your computers) and it can't turn anything on or off.

But if your hardware functions properly, it will turn off lights as soon as windows will tell bios that its actually sleeping :)

**Comment by xSimone** [comment]
> @xSimone when laptop lid gets closed, windows goes to sleep and suspends all apps. So G-Helper is effectively suspended (along all other apps on your computer) and it can't turn anything on or off.
> 
> But if your hardware functions properly, it will turn off lights as soon as windows will tell bios that its actually sleeping :)

<img width="470" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/c8f08b4c-cc58-4685-b2d7-8ef069d467e5">

Mine does not go to sleep.

When the lid is closed after timer turns RGB off, it stays off.

When lid is closed BEFORE RGB turns off, the RGB actually goes brighter, level three and stays on.

When I close my lid, nothing should happen with Windows except realise the panel to project an image is no longer available.

My Asus G752VS had no issue turning its lights off after 2 mins of inactivity. The Scar 18 should be able to do the same.

**Comment by seerge** [comment]
@xSimone can you post a ``log.txt`` (and config) as was asked in issue template? :)

**Comment by seerge** [comment]
@xSimone Just double-checked it

If laptop is not sleeping, and timeout for "plugged" state is set to some value, it works and turns backlight off 
![Screenshot 2023-11-02 102648](https://github.com/seerge/g-helper/assets/5920850/2d08c2fa-bf47-4b16-bf40-d8e7e284aedd)

You can verify it by yourself by opening ``%appdat%\ghelper\log.txt`` in some normal editor that updates when file changes, leave laptop w/o any input activity and in X seconds you will see something like

```
11/2/2023 10:19:10 AM: Timeout:5D-BA-C5-C4-00
```

Which is a command to turn off keyboard by timeout :)

**Comment by xSimone** [comment]
[log.txt](https://github.com/seerge/g-helper/files/13247027/log.txt)


Okay, I will try take a video to show what I mean.  I also noticed some issues on my end.

Set timer to 5 seconds. 

Wait 5 seconds RGB turns off, close Laptop Lid, RGB stays off. IF mouse is bumped while lid is closed, RGB turns on, timer doesn't work and doesn't turn RGB back off.

Do not wait 5 seconds, close Laptop Lid while RGB is on. RGB stays on. 

In both of these scenarios, the RGB is also changing from whatever brightness it is currently set, to maximum brightness when lid is closed.

So for me, I need to wait for the timer to kick in while the lid is closed, then close it, then make sure my mouse isn't bumped, or the RGB will turn on, and not turn off until I open the lid.

**Comment by seerge** [comment]
@xSimone hello

In a log it looks like a timeout seem to be working ? 

```
3/11/2023 4:48:21 PM: Timeout:5D-BA-C5-C4-00
3/11/2023 4:48:22 PM: Auto:5D-BA-C5-C4-01
3/11/2023 4:48:36 PM: Timeout:5D-BA-C5-C4-00
3/11/2023 4:49:00 PM: Auto:5D-BA-C5-C4-01
3/11/2023 4:49:10 PM: Timeout:5D-BA-C5-C4-00
3/11/2023 4:49:57 PM: Auto:5D-BA-C5-C4-01
3/11/2023 4:50:08 PM: Timeout:5D-BA-C5-C4-00
3/11/2023 4:51:11 PM: Auto:5D-BA-C5-C4-01
3/11/2023 4:52:16 PM: Timeout:5D-BA-C5-C4-00
3/11/2023 4:52:19 PM: Auto:5D-BA-C5-C4-01
3/11/2023 4:52:30 PM: Timeout:5D-BA-C5-C4-00
3/11/2023 4:52:37 PM: Auto:5D-BA-C5-C4-01
```
At least it kept going on (when keyboard / mouse is active) and off after?

My guess when you close a lid - it physically presses one of the buttons on keyboards or touchpad (so it doesn't let system go idle)

I have added a verbose idle-timer logging to this build (once in a second it will write how many seconds windows reports to be idle). And as soon as it's idle > desired amount it command to shut down backlight will appear. 

So try to check the build, open a log and monitor it in realtime w/o touching external mouse or with it :)
[GHelper.zip](https://github.com/seerge/g-helper/files/13248760/GHelper.zip)

P.S. Your video is private, so it's not possible to watch it  :)

**Comment by xSimone** [comment]
Stupid Vimeo.. uggh.

Sorry, I've used a different website.

https://streamable.com/vcvs4q

I will download and install this new version and share the log as soon as I can.

Thank you so much for believing in me and helping me try to explain the issue I'm having.

**Comment by seerge** [comment]
@xSimone from your video it looks like it was only lightbar being ON, while actual keyboard backlight has turned off correctly while lid was closed ? 

Then it could be indeed some hardware specifics (i.e. asus bugs) of your device.

Does dragging ``Laptop Backlight`` slider under ``Extra``  (you can do that with external monitor for example) actually control Lightbar backlight while lid is closed ?

**Comment by xSimone** [comment]
The Lightbar AND the rear was on. 

I'll do another video with all RGB active if you'd like later on to properly cover all corners.

I usually have the Logo off always, but I'll put that on too. Sorry for the confusion. Will try all this with your latest update then post the log.

**Comment by xSimone** [comment]
> Does dragging `Laptop Backlight` slider under `Extra` (you can do that with external monitor for example) actually control Lightbar backlight while lid is closed ?

I will try this later. I do not have a spare screen currently.. I'll see what I can do.

I might be able to hold the slider with my mouse, then close the lid.

**Comment by seerge** [comment]
> I will try this later. I do not have a spare screen currently.. I'll see what I can do.

@xSimone you can also turn Fn-Lock ON and then press F2/F3 (backlight down / up) on external keyboard

**Comment by seerge** [comment]
@xSimone then it's just a hardware specifics of backlight (lightbar and rear). It ignores settings when lid is closed.

I can't do much about that. 

The only real solution for you would be manually set backlight to 0 (with Fn+F2 or slider) prior to closing lid.

**Comment by xSimone** [comment]
I switched from Standard mode to Ultimate. It is now worse. Closing the lid after letting RGB turn off, it turns it back on a second after the lid is shut.


3/11/2023 10:18:41 PM: Iddle: 119.546
3/11/2023 10:18:42 PM: Monitor Power Off
3/11/2023 10:18:42 PM: Backlight:5D-BA-C5-C4-00
3/11/2023 10:18:42 PM: Monitor Power On
3/11/2023 10:18:42 PM: AutoSetting for Online
3/11/2023 10:18:42 PM: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&15ae9f2&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
3/11/2023 10:18:42 PM: Mode = 0 : OK
3/11/2023 10:18:42 PM: FanCPU = 1E-32-39-3D-45-49-4C-53-00-01-05-0E-1E-24-35-5A : OK
3/11/2023 10:18:42 PM: FanGPU = 1E-32-39-3D-45-49-4D-54-00-01-0B-0F-1D-23-29-48 : OK
3/11/2023 10:18:42 PM: FanMid = 1E-32-39-3D-45-49-4D-55-00-01-0A-17-21-25-25-44 : OK
3/11/2023 10:18:42 PM: Eco flag : 0
3/11/2023 10:18:42 PM: Mux flag : 0
3/11/2023 10:18:42 PM:  DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
3/11/2023 10:18:42 PM: Default internal screen
3/11/2023 10:18:42 PM: ScreenOverdrive = 0 : OK
3/11/2023 10:18:42 PM: Default internal screen
3/11/2023 10:18:42 PM: GET GPU CLOCKS: -125, -125
3/11/2023 10:18:42 PM: BatteryLimit = 80 : OK
3/11/2023 10:18:42 PM: Iddle: 0.125
3/11/2023 10:18:42 PM: Auto:5D-BA-C5-C4-01
3/11/2023 10:18:42 PM: USB-KB 0x19B6:5D-BD-01-0C-04-22-22-FF
3/11/2023 10:18:42 PM: USB-KB 786HID-compliant vendor-defined device\\?\hid#vid_0b05&pid_19b6&col05#6&15ae9f2&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-03-FF-00-00-E1-00-00-FF-FF-FF-00-00-00-00
3/11/2023 10:18:43 PM: PowerLimit A0 = 30 : OK
3/11/2023 10:18:43 PM: PowerLimit A3 = 30 : OK
3/11/2023 10:18:43 PM: Iddle: 0.875
3/11/2023 10:18:43 PM: Auto:5D-BA-C5-C4-01
3/11/2023 10:18:44 PM: PowerLimit C0 = 5 : OK
3/11/2023 10:18:44 PM: PowerLimit C2 = 87 : OK
3/11/2023 10:18:44 PM: Iddle: 1.859
3/11/2023 10:18:45 PM: Iddle: 2.875
3/11/2023 10:18:46 PM: Iddle: 3.875
3/11/2023 10:18:47 PM: Iddle: 4.875
3/11/2023 10:18:48 PM: Iddle: 5.875
3/11/2023 10:18:48 PM: Timeout:5D-BA-C5-C4-00
3/11/2023 10:18:49 PM: Iddle: 6.875
3/11/2023 10:18:50 PM: Iddle: 7.875
3/11/2023 10:18:51 PM: Iddle: 0.594
3/11/2023 10:18:51 PM: Auto:5D-BA-C5-C4-01
3/11/2023 10:18:52 PM: Iddle: 1.594
3/11/2023 10:18:53 PM: Iddle: 2.594
3/11/2023 10:18:54 PM: Iddle: 0.094
3/11/2023 10:18:55 PM: Iddle: 0.406
3/11/2023 10:18:56 PM: Iddle: 0
3/11/2023 10:18:57 PM: Iddle: 0

**Comment by seerge** [comment]
> I switched from Standard mode to Ultimate. It is now worse. Closing the lid after letting RGB turn off, it turns it back on a second after the lid is shut.

Ultimate mode has absolutely nothing to do with backlight.

> Also 'Idle' is spelled as 'Iddle' just in case that is a mistake

Indeed, but debug build with extra logging is not needed anymore, as your problem is not with that. But cause backlight apparently can't be controlled when lid is closed

**Comment by xSimone** [comment]
Well I would assume Ultimate mode would be bypassing the CPU, and directly powering the screen. The screen given it's now powered by the GPU would be handled differently by sensors in windows, the same sensors that trigger whether or not the screen is open or closed, and thus, turns on the RGB.

Putting it into Ultimate mode has given me a different behaviour and result, I'm telling you this result in case something comes to your mind.

**Comment by xSimone** [comment]
Hbbbbt.. forget the Extreme / Standard mode thing I guess.

I went back to Standard, now the RBG comes back on after closing the lid now.

I must have changed a different setting. Sorry.

**Comment by alien2003** [comment]
Experiencing exactly the same problem on Scar Strix 2025 16" 5090. Backlight switches to the max brightness and not switch off after the timeout when lid is closed.

I've also tested it with a second screen (iPad with Moonlight and virtual screen). When lid is closed, slider adjustment is not working at all, stuck on max, but you changing the type of animation and turning on and off RGB zones (logo, lightbar) still works.

@seerge can you please take a look? Maybe it's possible to add an advanced option to turn off zones on lid close and turn on on open?

**Comment by seerge** [comment]
@alien2003 can you adjust backlight with a slider under `Extra` when lid is closed ? If not - it's just a firmware limitation (i.e. it ignores brightness setting completely on lid close)

**Comment by alien2003** [comment]
> [@alien2003](https://github.com/alien2003) can you adjust backlight with a slider under `Extra` when lid is closed ? If not - it's just a firmware limitation (i.e. it ignores brightness setting completely on lid close)

No, slider is not working, but turning on and off lightbar and logo using checkboxes still works
