### ISSUE TITLE
Refresh rate options don't include Windows default dynamic refresh rate

### ISSUE THREAD

**Issue by BeamingNG** [seerge/g-helper#1556]
![image](https://github.com/seerge/g-helper/assets/105561183/334238c6-2985-44f4-888a-b09a2ac69746)  
![image](https://github.com/seerge/g-helper/assets/105561183/210358b2-beb5-4270-8367-f832d1f228ff)

GHelper includes the automatic refresh rate option and the highest & lowest one, but doesn't have support for dynamic refresh rate. Even if you manually select it in settings it will revert back to my highest refresh rate after bootup. Dynamic refresh rate is a nice compromise between screen smoothness and battery life so that's why I find it helpful.

**Comment by seerge** [comment]
@BeamingNG hello, I have already answered exactly same question here https://github.com/seerge/g-helper/issues/1541
