### ISSUE TITLE
M3 key - Microphone on/off keeps functioning whilst another function is assigend in ghelper

### ISSUE THREAD

**Issue by mrjmg** [seerge/g-helper#156]
Not sure if this is a request or a bug, but what I see happening is the following:
M3 key keeps switching on and off the Microphone (in W11) when pressed. When g-helper is set to, for instance, mute the system volume it also does that.

So this means the key will always (also) switch the microphone. Is there a way to disable this, or make only the g-helper assigned function active? Or maybe show a toast/overlay the microphone is being switched on/off?

I noticed this as I uninstalled MyASUS (and rebooted!), the microphone on/off overlay didn't show anymore (so at first I thought it didn't function). I just installed MyASUS again, basically it only shows the overlay (also in case of e.g. kb brightness up/down).

Let me know if I can help in any way, I just uninstalled MyASUS again (and rebooted, it stays active. Your debloat script might work, although I didn't check that).

**Comment by seerge** [comment]
It's Asus Optimization Service that is muting your microphone, not g-helper :) I don't control it and can't do much here.

G-helper indeed has ability to bind M3 for something else (and by default M3 does nothing in the app) as that's only for the situation when you don't use mute handled by asus.

**Comment by mrjmg** [comment]
I see you're right, stopping the Asus Optimization Service also stops those keys (M3 but also keyboard backlight etc) from doing anything.
I'll close this one!
