### ISSUE TITLE
GPU fan does not spin when a custom fan curve is applied

### ISSUE THREAD

**Issue by karkinissan** [seerge/g-helper#1563]
**Describe the bug**
This happens randomly. The GPU fan does not spin when a custom fan curve is applied, even though it is set to spin at the GPU's current temperature. Un-applying the fan curve starts the GPU fan again.

**Clear scenario to Reproduce**
1. Create custom fan curve and apply.
2. Wait for GPU to hit target temps. Observe that fan does not spin. 
3. Uncheck "Apply Custom Fan Curve" and observe the fan spinning. 

**Expected behavior**
The fan should spin when it reaches the temperatures defined in the curve.

**App Logs**
https://pastebin.com/raw/Ud58RZ5G

**Screenshots or screencasts**
Curve applied and fan not spinning: https://i.imgur.com/6EEB9J4.png  
Curve not applied and fan spinning: https://i.imgur.com/ciBw3hb.png  

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ASUS Zephrus G14 2021 w/ 3060

**Asus software**
- Only Asus Hotplug Controller

**Comment by seerge** [comment]
@karkinissan hello, it's up to BIOS how to behave. App doesn't control that

> [How does G-helper control my fan speeds?](https://github.com/seerge/g-helper#how-does-g-helper-control-my-fan-speeds)
It doesn't. Your BIOS does (same as in case with Armoury). What G-helper can do - is (optionally) set a custom fan profile to current performance mode consisting of 8 pairs of temperature + fan speed % via same endpoint armoury seem to use.

You can check older (or newer) BIOS versions, they may behave differently like for this user https://github.com/seerge/g-helper/discussions/448

**Comment by karkinissan** [comment]
How come the fan only stops spinning when I apply the custom fan curve? Sounds like a bug in GHelper to me and not in the BIOS.

**Comment by seerge** [comment]
@karkinissan cause this is how your BIOS threats custom fan curves.

If you are believe there is a "bug" PR are more than welcome.

**Comment by seerge** [comment]
@karkinissan Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks
