### ISSUE TITLE
MATLAB tries to call dGPU in GPU Eco Mode

### ISSUE THREAD

**Issue by Dictation354** [seerge/g-helper#1568]
**Clear scenario to Reproduce**
Open MATLAB in GPU Eco Mode and try to produce an image. Then it crashes saying it's using an uninitialized hardware.

**App Logs**
Configuration:
  Crash Decoding           : Disabled - No sandbox or build area path
  Crash Mode               : continue (default)
  Default Encoding         : UTF-8
  Deployed                 : false
  Graphics Driver          : Uninitialized hardware 
  Graphics card 1          : NVIDIA ( 0x10de ) NVIDIA GeForce RTX 3060 Laptop GPU Version 31.0.15.4601 (2023-10-26)
  Graphics card 2          : Intel Corporation ( 0x8086 ) Intel(R) UHD Graphics Version 31.0.101.4952 (2023-10-31)
  Interpreter 0            : Executing request: 7372632F647443616C6C6261636B2E637070
  JAWT Patch Status:       : Patch applied
  Java Version             : Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  MATLAB Architecture      : win64
  MATLAB Entitlement ID    : 3439096
  MATLAB Root              : C:\Program Files\MATLAB\R2023b
  MATLAB Version           : 23.2.0.2409890 (R2023b) Update 3
  OpenGL                   : hardware
  Operating System         : Microsoft Windows 11 专业工作站版
  Process ID               : 14884
  Processor ID             : x86 Family 6 Model 141 Stepping 1, GenuineIntel
  Session Key              : 10ac7bee-a559-4813-a4c2-6491eacf338e
  Window System            : Version 10.0 (Build 22631)

Fault Count: 1

Additional Log Files:
  Java Crash Report        : C:\Users\huang\AppData\Local\Temp\hs_error_pid14884.log

Assertion in void __cdecl `anonymous-namespace'::mwJavaAbort(void) at B:\matlab\src\jmi\jmi\javainit.cpp line 1464:
Fatal Java Exception. See this file for details: C:\Users\huang\AppData\Local\Temp\hs_error_pid14884.log

Current Thread: '' id 2124

Register State (captured):
  RAX = 00007fff1bdbcd58  RBX = 00007fff1bdbcd58
  RCX = 000000ad9acf86e0  RDX = 0000000000000000
  RSP = 000000ad9acf8620  RBP = 00000000000005b8
  RSI = 000001d51fac1c80  RDI = 00007fff1bdbcd58
 
   R8 = 0000000000000003   R9 = 000000ad9acf8598
  R10 = 0000000000000014  R11 = 000000ad9acf8418
  R12 = 000000ad9acf8d20  R13 = 000000ad9acf9850
  R14 = 00007ffef4a71318  R15 = 00007fff1bdacc88
 
  RIP = 00007fff1bcb168a  EFL = 00000202
 
   CS = 0033   FS = 0053   GS = 002b

Stack Trace (captured):
[  0] 0x00007fff1bcaaca3 C:\Program Files\MATLAB\R2023b\bin\win64\libmwfl.dll+00044195
[  1] 0x00007fff1bca9278 C:\Program Files\MATLAB\R2023b\bin\win64\libmwfl.dll+00037496
[  2] 0x00007fff1bcade8e C:\Program Files\MATLAB\R2023b\bin\win64\libmwfl.dll+00056974
[  3] 0x00007fff1bcac891 C:\Program Files\MATLAB\R2023b\bin\win64\libmwfl.dll+00051345
[  4] 0x00007fff1bcb0efb C:\Program Files\MATLAB\R2023b\bin\win64\libmwfl.dll+00069371
[  5] 0x00007ffef49d8af1   C:\Program Files\MATLAB\R2023b\bin\win64\jmi.dll+00690929
[  6] 0x000000005eeb9ead C:\Program Files\MATLAB\R2023b\sys\java\jre\win64\jre\bin\server\jvm.dll+02727597
[  7] 0x000000005eea208b C:\Program Files\MATLAB\R2023b\sys\java\jre\win64\jre\bin\server\jvm.dll+02629771
[  8] 0x000000005eebac26 C:\Program Files\MATLAB\R2023b\sys\java\jre\win64\jre\bin\server\jvm.dll+02731046
[  9] 0x000000005eebf52d C:\Program Files\MATLAB\R2023b\sys\java\jre\win64\jre\bin\server\jvm.dll+02749741
[ 10] 0x000000005ef55d98 C:\Program Files\MATLAB\R2023b\sys\java\jre\win64\jre\bin\server\jvm.dll+03366296
[ 11] 0x00007fffac43441f                      C:\Windows\SYSTEM32\ntdll.dll+00672799
[ 12] 0x00007fffac3ae466                      C:\Windows\SYSTEM32\ntdll.dll+00124006
[ 13] 0x00007fffac43340e                      C:\Windows\SYSTEM32\ntdll.dll+00668686
[ 14] 0x00007ffedd696c89 C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_e6ace74673553eb5\nvoglv64.dll+11496585
[ 15] 0x00007ffedd696515 C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_e6ace74673553eb5\nvoglv64.dll+11494677
[ 16] 0x00007ffedd5e5fa4 C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_e6ace74673553eb5\nvoglv64.dll+10772388
[ 17] 0x00007ffedd5e63ec C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_e6ace74673553eb5\nvoglv64.dll+10773484
[ 18] 0x00007ffedd5ebe06 C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_e6ace74673553eb5\nvoglv64.dll+10796550
[ 19] 0x00007ffedd5e7b8d C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_e6ace74673553eb5\nvoglv64.dll+10779533
[ 20] 0x00007ffedd5c87cd C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_e6ace74673553eb5\nvoglv64.dll+10651597
[ 21] 0x00007ffedd5c963c C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_e6ace74673553eb5\nvoglv64.dll+10655292
[ 22] 0x00007ffedd52b75b C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_e6ace74673553eb5\nvoglv64.dll+10008411
[ 23] 0x00007ffedd52a30e C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_e6ace74673553eb5\nvoglv64.dll+10003214
[ 24] 0x00007fff710ceda5                   C:\Windows\system32\opengl32.dll+00126373
[ 25] 0x00007fff710cf1b9                   C:\Windows\system32\opengl32.dll+00127417
[ 26] 0x000000006455396e C:\Program Files\MATLAB\R2023b\bin\win64\jogl_desktop.dll+00342382
[ 27] 0x000001d569e69f2e                                   <unknown-module>+00000000

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ROG Zephyrus M16 2021

**Asus software**
None

**Comment by seerge** [comment]
@Dictation354 in Eco mode dGPU is powered off completely. So no wonder.

Use Standard mode if you need your dGPU
