### ISSUE TITLE
CPU Boost effecting both plugged in and battery.

### ISSUE THREAD

**Issue by gloatoriginal** [seerge/g-helper#157]
**Describe the bug**
The CPU mode is effecting both Battery & Plugged in CPU mode.
**To Reproduce**
I was able to set the boost to disabled in power plan for battery, than I set the plan to disabled in ghelper, than back to efficient enabled in ghelper, bother battery and plugged in were set to efficient enabled under power plan settings.

**Expected behavior**
Expected for the drop-down to only effect plugged in cpu boost option not both battery & plugged in.
**Screenshots**

**Desktop (please complete the following information):**
Zephyrus G14 2022 Windows 11 Release build

**Comment by gloatoriginal** [comment]
This is on 0.40.0.0 build

**Comment by gloatoriginal** [comment]
I think I maybe confused, is the cpu boost associated with the profile?

**Comment by seerge** [comment]
Lots of people were continuously asking for that, so I gave up - and now app changes boost setting with modes (and remembers them)

That's why i have made boost setting affecting both battery/plugged in state now (cause you can link no boost to one mode, and full boost to other for example)

**Comment by gloatoriginal** [comment]
Sounds good, I was confused on functionality.

**Comment by seerge** [comment]
Yeah, mb i need to adjust some wording tho
