### ISSUE TITLE
Screen and Sleep

### ISSUE THREAD

**Issue by Akalikaton** [seerge/g-helper#1570]
Thanks for your working. It is very useful.

And I want to know, if it's possible, every mode have an own screen and sleep plan. For example, 
Mode: Silent, Screen turn off after 5min, Sleep after 10min
Mode: Balanced, Screen turn off after 10min, Sleep after 20min
Mode: Silent, Screen turn off never, Sleep never

Or when I switch to Silent Mode, ghelper run silent.bat with Admin backgrund. It's also a way to custom.

I used to take every Mode a Powerplan, but some Powerplan not very useful.

**Comment by xSimone** [comment]
Could I just jump into this and ask, is G-Helper accidentally reverting the changes to 'Choose what closing the lid does' settings? 

I put mine to 'Nothing' with closing lid when laptop is plugged in. 

Every reboot it reverts to 'Sleep'.

**Comment by seerge** [comment]
@Akalikaton hello, you can do that with copying your power plan in windows and configuring each one for appropriate time to sleep / turn off screen.

And then you can assign each power plan to appropriate mode as explained in readme
https://github.com/seerge/g-helper#custom-windows-power-plans-with-each-mode

@xSimone If you have "Clamshell mode" checked in in ``Extra`` it would enable sleep when laptop doesn't have external monitor or on battery, and disable when it does have external monitor and is plugged in. If "Clamshell mode" is unchecked - it won't touch your lid action anyhow at all.

**Comment by xSimone** [comment]
@seerge THANK YOU!! Yes I did have that activated by accident, thank you.

Fixed.
