### ISSUE TITLE
Keyboard backlight doesnt work on Tuf Dash F15 FX516PM

### ISSUE THREAD

**Issue by T0biasCZe** [seerge/g-helper#1571]
**Describe the bug**
On Asus Tuf Dash F15 FX516PM, the keyboard backlight control doesnt work on boot. When you press the F2-F3, it shows the brightness overlay, but it doesnt change the actual keyboard backlight (the backlight is still off). Only after you first try to start armoury crate, and change the brightness from that, the control in ghelper starts to work

**Clear scenario to Reproduce**
start windows
open ghelper
try to change the brightness
the backlight is still off
open armoury crate
modify the brightness there
the keyboard light up
fully close armoury crate (eg no services or exes running on background)
GHelper can now properly control the backlight of the keyboard

**Expected behavior**
ghelper should be able to control the backlight without having to open armoury crate first

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13276851/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Laptop model: Asus Tuf Dash F15 FX516PM

**Asus software**
- Armoury Crate yes
- MyASUS yes

also, simirarly to FX517 https://github.com/seerge/g-helper/issues/1425, the backlight is single colour blue, not RGB, yet ghelper shows the color options

**Comment by seerge** [comment]
@T0biasCZe hello,

There is only one known to me endpoint that controls brightness (and it's same for all devices), and app uses it and gets positive response from BIOS, so it should be working

```
07/11/2023 08:14:11: TUF Brightness = 129 : OK
07/11/2023 08:14:11: TUF Brightness = 130 : OK
07/11/2023 08:14:11: TUF Brightness = 131 : OK
```

Does changing backlight mode or setting color to red or checking/unchecking backlight checkboxes under ``Extra`` do anything in your case (when backlight is not working) ?

**Comment by T0biasCZe** [comment]
when the backlight is not working, clicking the checkboxes doesnt do anything, and putting the colour to red also doesnt do anything. changing the backlight effect mode also doesnt work
but even when the backlight is working, the backlight effect or the colour option doesnt do anything

**Comment by seerge** [comment]
@T0biasCZe then I don't know what I can offer here, may be it's some unique specific of your model (cause it's quite old + apparently don't support colors / effects unlike other TUFs) . 

And your keyboard need some kind of initialization in order to be turned ON.

I can't do much here 

Is OpenRGB able to "wake up" your keyboard ? (after reboot) ?

Also do you have Fast Boot enabled or disabled in BIOS ? Try to change setting to opposite.

**Comment by seerge** [comment]
@T0biasCZe try to set fast boot on :) mb it won't require initialization via AC then to start working.

Besides that I can't offer anything

**Comment by seerge** [comment]
@T0biasCZe any luck with checking if backlight stays working after fast boot on?

Anyway I have added your model to the list that don't support colors 
[GHelper.zip](https://github.com/seerge/g-helper/files/13299348/GHelper.zip)

**Comment by seerge** [comment]
Closed as abandoned
