### ISSUE TITLE
fan customization not working on asus tuf a15 2021 FA56IC laptop

### ISSUE THREAD

**Issue by quynhdino** [seerge/g-helper#1572]
I have adjusted the fan level to 100% according to my wishes but it seems to not work according to what I have customized. The fan speed at the temperature levels still seems to be the default according to the manufacturer. I use Windows 11 has removed armory crate and my asus. Looking forward to your help.
![Screenshot (70)](https://github.com/seerge/g-helper/assets/93974590/9c7b98c4-1b47-408d-a9cb-ce2f12ab6b52)

**Comment by seerge** [comment]
@quynhdino hello,

App doesn't control fans in realtime anyhow, they are controlled by firmware (BIOS).  And it's up to BIOS how to treat even custom fan curves, if it thinks that it doesn't need to spin fans to the max - it wont :)

This is how things are.

**Comment by seerge** [comment]
@quynhdino Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks
