### ISSUE TITLE
Asus ROG Strix G15 (G512LI) has only keyboard and lightbar backlight

### ISSUE THREAD

**Issue by Kugumin** [seerge/g-helper#1575]
**Describe the bug**
It shows all zones in Extra settings, though the model has only keyboard and lightbar

**Clear scenario to Reproduce**
Open Extra settings and check

**Expected behavior**
To keyboard and lightbar zones visible only

**App Logs**
Not needed I guess?

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/42800753/f67cab2b-b4d8-419e-bd2f-831f18deccbd)

**Desktop (please complete the following information):**
 - OS: Windows 10 (19045.3570)
  - Laptop model: Asus ROG Strix G15 (G512LI)

**Asus software**
- Asus services installed, not running)

**Additional information**
![image](https://github.com/seerge/g-helper/assets/42800753/1bc61027-4630-4324-8183-624417ec1dc0)

**Comment by seerge** [comment]
@Kugumin hello, I have added G512LI to the list of models that don't have logo / lid backlight
[GHelper.zip](https://github.com/seerge/g-helper/files/13307540/GHelper.zip)
