### ISSUE TITLE
Shift or Ctrl combinations with custom M1/M2 etc. keys don't work

### ISSUE THREAD

**Issue by RyzenFromFire** [seerge/g-helper#1576]
**Describe the bug**
I have set custom keybinds (specifically `Home` and `End` as I use them frequently) for M1 and M2 keys on ROG Flow X16. I have also set `skip_hotkeys: 1` in the `config.json` that should prevent G-Helper from intercepting CTRL+M1/M2 or SHIFT+M1/M2. However, either of these key combinations simply decrements or increments the volume, respectively.

**Clear scenario to Reproduce**
1. Go to G-Helper 'Extra' Settings
2. Set M1 (or other key) to "Custom" and set a virtual keybind (KEY) as described in `README`
3. Set `skip_hotkeys: 1` in `config.json`
4. Press CTRL+M1 or SHIFT+M1
5. Volume decrements instead of performing CTRL+KEY or SHIFT+KEY.

**Expected behavior**
I expected that with the hotkeys disabled, pressing SHIFT+M1 would result in SHIFT+HOME (in my case), and so on for CTRL and M2.

**App Logs**
https://pastebin.com/JmQd7FBU

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Laptop model: ROG Flow X16 (2022)

**Asus software**
- Armoury Crate (or it's services installed): No
- MyASUS installed: Yes
- Other Asus services running in background: 0, but happened with 7 as well

**Comment by seerge** [comment]
@RyzenFromFire hello,

``Ctrl+M1`` and just ``M1`` are different combinations.

You can rebind only M1/M2 keys themselves (i.e. the ones that emit volume up / down by default)

If you want to emit ``Shift + Home`` you can just bind M1 to do that directly to a whole combination by setting ``0xA2 0x24`` in custom action field (i.e. shift + home)

**Comment by RyzenFromFire** [comment]
I figured that was the reason why it didn't work, but that doesn't solve my issue. I use the home and end keys heavily, and the functionality is different when pressing home vs. shift+home (select) vs. ctrl+home (jump to top) and similarly for end. So the functionality I expected was for the modifiers to translate to the key I selected. If this would better be represented as a feature request, I can do that. If it's not something you're willing to implement, I'll just fork and do it myself when I have time.

**Comment by seerge** [comment]
@RyzenFromFire well, your use-case is very exotic. And I would have to modify quite a lot in the app to accommodate this.

M1 and M2 actually emit windows native ``VolumeUp`` / ``VolumeDown`` keycodes (you don't need g-helper or any asus-specific software to process them). 

Why don't you just make a binding from ``Ctrl+VolumeUp`` to ``Ctrl+Home`` using Autohotkey (or Sharpkeys) or something like that ?

**Comment by seerge** [comment]
More over, to handle ``Ctrl+M1`` in G-Helper - it needs to explicitly register a ``Ctrl+VolumeUp`` as own hotkey in windows (that's what it does when ``skip_hotkeys`` is not set), or app won't get notified about that keypress at all.

And whole purpose of ``skip_hotkeys``  is to actually free up all extra hotkeys, and leave them to windows.  If it will keep reserving ``Ctrl+VolumeUp`` even when skip hotkeys is ON, it would be contrary to what user would expect :)

**Comment by RyzenFromFire** [comment]
I see, that wasn't particularly clear to me from reading the README, but perhaps I misinterpreted. Autohotkey is a good shot, I haven't played with it in a while but I didn't think of it so thanks for the idea - I'll see if that works.
