### ISSUE TITLE
Touchscreen ON/OFF

### ISSUE THREAD

**Issue by johnytd7** [seerge/g-helper#1577]
Can you please add option to disable/enable touchscreen for X16?

**Comment by seerge** [comment]
@johnytd7 hello, I can't as there is no "normal" way to do that in windows anyhow :)

From what I was reading the only way to do it is by going do device manager and manually disabling corresponding device
https://support.microsoft.com/en-us/windows/enable-and-disable-your-touchscreen-in-windows-b774e29d-be94-990f-c20f-e02892e572fc
