### ISSUE TITLE
Fan Sync

### ISSUE THREAD

**Issue by Moorole** [seerge/g-helper#1578]
Am again and again very happy using this peace of software :) 
I was wondering if it is possible to sync the speed of the fans because the loudness of the system is in general determined by the fastest turning fan. As the GPU and the CPU are connected via a heatpipe, it should be possible to lets use the slower turning fan to help the other one in unbalanced loads towards cpu and gpu. So rather then having one on 5000 rpm and the other one on 3000rpm it would be good to maybe have both on 4200 rpm which in total gives a more quiter system.
Alternatively it would be possible to set both fans to the same speed for a wider temperature range but i just thought that a fan sync would be the more elegant solution.
Thank you so much and have a good week(end)

Ole

**Comment by seerge** [comment]
@Moorole hello,

That is not possible. Fans are controlled by firmware (BIOS) not by the app.

Maximum that you can set yourself - is a custom fan curve. So you can try to experiment with that
