### ISSUE TITLE
Fan reading inconsistent or Fan Curve set wrong

### ISSUE THREAD

**Issue by gloatoriginal** [seerge/g-helper#158]
![image](https://user-images.githubusercontent.com/47373236/228368585-f6127218-2521-4fcf-9dd3-daa3f262d692.png)
I have my laptop in silent mode & Eco, and you can see the fan curve should only start at 60 celcius on either GPU or CPU. Currently my fans are running I can hear so I believe the 60% fan is correct, but why is it not following the fan curve for silent mode?
Model: Zephyrus G14 2022 6700s
OS: Windows 11

**Comment by seerge** [comment]
As FAQ says : "As soon as you click Apply in fan + power section bios will be considering fan profile as "custom"! (no matter if you modified it or not)"

You have Auto apply set, therefore it applies that chart. And I assume  cause there is no point before 60 bios decides to spit fan on a level of 60 all the time before it too. This is how bugged asus bios is :) 

Just click factory defaults and it will behave normally
