### ISSUE TITLE
Power plan related things like screen brightness or sleep time do not saved with modes in g-helper

### ISSUE THREAD

**Issue by PhanTinhKhang** [seerge/g-helper#1583]
hello guys.
Does g-helper have the ability to save the config of brightness and sleep time with each mode: silent, balanced, turbo?
I mean if i switch to turbo it should be 70% brightness and never sleep, or if i switch to silent mode it should be 30% brightness and sleep after 3 minutes.
Armoury crate has this thing i want, but when i try ghelper, i cannot figure out how to do it. I do not know that g-helper does not have that function or Im doing something wrong.
Can anyone help? Dont blame me pls.

**Comment by seerge** [comment]
@PhanTinhKhang hello,

If you want to change power-plan specific settings with each mode you should better create 3 separate power plans and configure them accordingly in windows

You can assign your own custom power plans for each mode via config
https://github.com/seerge/g-helper#custom-windows-power-plans-with-each-mode

Good luck :)
