### ISSUE TITLE
G14 2022 Low GPU power draw

### ISSUE THREAD

**Issue by SkaMasta** [seerge/g-helper#1585]
[log.txt](https://github.com/seerge/g-helper/files/13322805/log.txt)

**Describe the bug**
Out of nowhere my G14 (6700S) is not performing as it should. First it was drawing around 30w. After a reinstal of an old version of Ghelper (0.9xx) it was fine for a minute or two but than it fell to around 50w. In games I should be using aroung 80-90w with my settings. It came out of nowhere. I was fiddling with some setting in windows and helper, but I tried to revert everything. Reinstalled drivers with DDU, older versions of helper etc.  In 3DMark time spy, It did as you would it expect it to today, yesterday even in 3D mark it was stuck at 30W. 

**Clear scenario to Reproduce**
4. Explanation of an error or a bug

**Expected behavior**

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model : Asus Zephyrus G14 2022 R7+RX6700S

**Asus software**
- uninstalled everything 

**Additional context**
Recently did the 23H2 win update.

**Comment by seerge** [comment]
@SkaMasta hello, G-Helper is not a driver and not a windows, it doesn't control how apps use your hardware anyhow.

It can only switch between predefined modes in bios, and also set (optional) power limits via endpoints prepared by asus. But I assume it's not what worries you :)

I would advice to reinstall GPU drivers completely using [amd cleanup utility](https://www.amd.com/en/support/kb/faq/gpu-601) or do a [hardware reset ](https://github.com/seerge/g-helper#how-do-i-do-a-hardware-reset-on-a-laptop)

**Comment by SkaMasta** [comment]
Thanks for the reply. So you point to that it cant be Ghelpers fault ? Will try the reset.

Cheers.

**Comment by seerge** [comment]
@SkaMasta yes :) it’s not g-helpers fault unless you have intentionally limited power by a lot (which you didn’t according to the log)

**Comment by SkaMasta** [comment]
could it be thermal throttling ? i did the reset, a minute in a game all fine than drop to 50ishW. gpu hot spot hit 101 celsius, the gpu temp is in the low 80s.

**Comment by seerge** [comment]
You can check with hwinfo, i think it shows amd gpu is throttling

**Comment by SkaMasta** [comment]
I dont think it is throttling. Or at least I did not see anything like that in HWinfo..
