### ISSUE TITLE
Support for Keybind option for Mouses (especially the Keris Wireless EVA Edition)

### ISSUE THREAD

**Issue by Boylenoid20** [seerge/g-helper#1586]
### Key Bind Option Implementation
**Issue**
I love how clean GHelper is and how everything is in one place, but not being able to change my keybinds for my mouse is very annoying since you can do this in Armoury Crate. 

**Implementation**
I would like for there to be an option when you press on the mouse peripheral box (since I have a mouse, I have used it as an example) and go into the options for it, to have another tab for changing side button keybinds, similar to how the laptop keyboard key bindings could be changed as well as being able to set them back to their default bindings.

**Alternative**
Making a new option/section for keybinds on the main interface where all the keybinds from your laptop to your mouse to other peripherals can be viewed would be a great alternative which could be tried.

**Context & Evidence**
I received a ROG Keris Wireless EVA Edition from a friend but they had binded the side button keybinds to left click and right click which is a bit of an inconvenience as I use them for returning and going forward on websites as well as in game keybinds. I have tried to reinstall Armoury Crate in desperation but it just would not download it. I would preferably not need to use Armoury Crate for reconfiguring the key bindings.

The tab has no options for reconfiguring key binds.
![image](https://github.com/seerge/g-helper/assets/110370839/e9c8430f-01c3-44e6-a676-336296230288)

Something like this image, being used for the mouse keybinds would be very helpful.
![image](https://github.com/seerge/g-helper/assets/110370839/4a6339df-5d56-44f1-be3a-a8123df0ad82)

**Comment by seerge** [comment]
@Boylenoid20 hello, as far as I remember it's quite tricky to do for mice, right @IceStormNG ?

By the way, why don't you try https://rog-forum.asus.com/t5/technologies-explained/armoury-crate-gear-is-now-available/ba-p/957266 - a "lightweight" armoury for peripherals only ?

**Comment by Boylenoid20** [comment]
Ah ok I'll give it a go then. Though it would be great if you could intergrate the key bind stuff into the GHelper app to the best of your abilities. But even so thank you for putting your time and effort into this app, much appreciated.

**Comment by seerge** [comment]
@Boylenoid20 i have read your topic on reddit, if you need to just unbind buttons once - you can try to install AC on virtual machine, or on other laptop even (just to set bindings once).

**Comment by Boylenoid20** [comment]
Like I mentioned in the Reddit post it couldn't download Armoury Crate on another PC which was odd. I'll give the virtual machine a go and see if there are any issues with it though.
