### ISSUE TITLE
Fan calibration not working properly and ruining fan speed

### ISSUE THREAD

**Issue by plaintativetrain** [seerge/g-helper#1588]
I don't have any logs or reports since I just deleted it. But on my zephyrus g14 GA401QM-0162E5900HS when I do fan calibration it maxes out at around 7200RPM for both my cpu and gpu whereas when I run a diagnostic test from MyAsus I hear it be noticeably louder and armoury crate as well works at 8000RPM. That would be fine if I could reset the fan speed limit after calibration but I couldn't do that either

**Comment by seerge** [comment]
@plaintativetrain fan calibration just sets fan curve 100% to establish how much RPM that would be and adjust y-axis on charts. And it does exactly that.

MyASUS fan test has nothing to do with that, as that fan speed can't be sustained in fan curves.

It doesn't "ruin" your fans. I'm not gonna tolerate insults here.

**Comment by plaintativetrain** [comment]
Oh ok nevermind then sorry
