### ISSUE TITLE
Fn+Touchpad lock(F10) takes a screenshot.

### ISSUE THREAD

**Issue by DarkEdgeXD** [seerge/g-helper#1589]
Describe the bug
Fn+Touchpad lock(F10) takes a screenshot.

Clear scenario to Reproduce
Pressing Fn+Touchpad lock(F10)

Expected behavior
It should lock/unlock the touchpad.

Desktop:

OS: Windows 11 23H2
ASUS TUF Gaming A15 FA507RM_FA577RM

Log:
[log.txt](https://github.com/seerge/g-helper/files/13327819/log.txt)

ASUS Software:
None

**Comment by seerge** [comment]
@DarkEdgeXD i think this is a dublicate of https://github.com/seerge/g-helper/discussions/1504

try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/13327905/GHelper.zip)

**Comment by DarkEdgeXD** [comment]
Sorry, it does appear to be a duplicate. The build you provided fixes the screenshot issue, but it doesn't reliably toggle between on and off.

**Comment by seerge** [comment]
@DarkEdgeXD well, problem is that windows hotkey combinations to do a screenshot and toggle touchpad simply overlap.

I have added 100ms delay between pressing keys as someone suggested in other topic, apparently it doesn't help.

You can try this build, with 50ms delay, mb it will be better
[GHelper.zip](https://github.com/seerge/g-helper/files/13327997/GHelper.zip)

**Comment by DarkEdgeXD** [comment]
@seerge Thanks for the reply. The thing is that single tapping Fn+F10 does nothing except bringing up the osd, double tapping on the other hand toggles the touchpad twice bringing it back to what it originally was. I have found that with function lock enabled, the hotkey works perfectly.

**Comment by seerge** [comment]
@DarkEdgeXD well, i don't have a fix for you then. Do you by any chance have asus optimization service running in the background as well ? cause it will mess up things.

For me it works fine all the time. And toggles correctly.

**Comment by DarkEdgeXD** [comment]
@seerge ASUS Optimization is disabled. The hotkey does in fact run as expected with G-Helper off.

**Comment by seerge** [comment]
@DarkEdgeXD then something else is handling it, i assume hardware itself (if you say that works even w/o the app running) ?

**Comment by DarkEdgeXD** [comment]
@seerge It does seem to be handled by the hardware.

**Comment by seerge** [comment]
@DarkEdgeXD try this build, it won't do anything for your model for Fn+F10 (but still will for F10 with fn-lock on)

[GHelper.zip](https://github.com/seerge/g-helper/files/13328822/GHelper.zip)

**Comment by DarkEdgeXD** [comment]
@seerge Sorry for the late reply. This build works flawlessly.
