### ISSUE TITLE
Asus ROG Strix G15 2022 (G513RS) has only keyboard and lightbar backlight

### ISSUE THREAD

**Issue by bourbonbourbon** [seerge/g-helper#1591]
Similar to #1575

**Describe the bug**
It shows all zones in Extra settings, though the model has only keyboard and lightbar

**Clear scenario to Reproduce**
Open Extra settings and check

**Expected behavior**
To keyboard and lightbar zones visible only

**App Logs**
N/A

**Screenshots or screencasts**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11 Build 22621.2428
 - Laptop model -  ROG Strix G15 (2022) G513 G513RS-HQ032X 

**Asus software**
- Asus services installed and running

**Additional context**
[The last laptop in this lineup](https://rog.asus.com/laptops/rog-strix/rog-strix-g15-2022-series/spec/)

**Comment by seerge** [comment]
@bourbonbourbon hello, this build should hide unsupported checkboxes for you

[GHelper.zip](https://github.com/seerge/g-helper/files/13328798/GHelper.zip)
