### ISSUE TITLE
Disabling numberpad function on Zenbook 14 Flip OLED UN5401 laptop and question about debloat script operation

### ISSUE THREAD

**Issue by m1804-code** [seerge/g-helper#1593]
My Zenbook 14 Flip OLED UN5401 laptop has a numberpad function, which displays a numeric keypad on the touchpad. It's activated by either holding a finger on the calculator icon in the top right corner of the touchpad or by swiping from the top left corner, which also brings up the calculator (see: https://www.youtube.com/watch?v=CNpD6IQQf50). This gesture often gets triggered accidentally, which is extremely annoying.

I have searched extensively online, including on Reddit, and found only two solutions: disabling the numberpad in the myASUS app or disabling the "AsusNumPadService". In the first case, the numpad function ceases to work, and in the second case, the gesture activation is disabled while the numberpad still functions normally, but only until the system is rebooted. Would adding "AsusNumPadService" to the debloat script and running it at system startup be a viable solution?

Additionally, I have a concern about the debloat script. Does it inadvertently disable the pixel refresh feature on OLED panels, which I believe is an Asus technology? It would be useful if the functions of the scripts disabled by debloat.bat were described.
Here are the Asus services I have:
![image](https://github.com/seerge/g-helper/assets/59769586/8527e6fc-c2a9-4495-8b58-a44ccbf4ae21)

**Comment by seerge** [comment]
@m1804-code hello,

I honestly have no idea how it's controlled, and if there any endpoints responsible for that 

If you want - you can run a scan script from this thread https://github.com/seerge/g-helper/issues/38 twice - once for enabled and second time for disabled numpad

**Comment by m1804-code** [comment]
@seerge Unfortunately nothing changes except 110013 - fan speed. I tried with shutdown by myasus and by disabling the service and with numberpad on and off

**Comment by m1804-code** [comment]
`@echo off
:loop
sc query AsusNumPadService | find "RUNNING"
if %errorlevel%==0 (
  echo AsusNumPadService jest uruchomiony. Zatrzymywanie usługi...
  sc stop AsusNumPadService
  goto end
) else (
  echo AsusNumPadService nie jest uruchomiony. Uruchamianie usługi...
  sc start AsusNumPadService
  timeout /t 5 /nobreak >nul
  goto loop
)
:end
exit`

**Comment by seerge** [comment]
@m1804-code it could be that numpad is controlled via USB, it's possible to debug that and intercept protocol using https://www.hhdsoftware.com/device-monitoring-studio but it could be tricky ...

**Comment by seerge** [comment]
@m1804-code did you had any luck figuring out how numpad is toggled via USB ? cause if not - i can't do anything here

**Comment by seerge** [comment]
Closing as abandoned :)
