### ISSUE TITLE
Games crashing

### ISSUE THREAD

**Issue by dhineshrockstar** [seerge/g-helper#1598]
Just uninstalled Armory crate and installed the G helper, any game that I try to play is crashing stating file verification failed. I tried to restart the game, laptop but still same crash.

**Comment by seerge** [comment]
How is it related to g-helper ?

**Comment by dhineshrockstar** [comment]
This is occurring just after installation. This is what shown up in event viewer if it can help.

```
The description for Event ID 0 from source nvlddmkm cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

\Device\Video13
Error occurred on GPUID: 100

The message resource is present but the message was not found in the message table
```

**Comment by seerge** [comment]
@dhineshrockstar there is no "installation", you just run exe that can can switch some predefined modes on your laptop. 

Reason you games are crashing are somewhere else.

**Comment by dhineshrockstar** [comment]
I understand this. Idk why but immediately after uninstalling AC and trying G helper I'm facing this. I guess it is something tied to the AC and the game itself. Anyways sorry for the misunderstanding, thank you again.

**Comment by seerge** [comment]
You probably have broken drivers or something like that. ``nvlddmkm`` is nvidia driver.

Make sure that your GPU is enabled to start with (i.e. in Standard mode)

**Comment by dhineshrockstar** [comment]
Got it. I'll do that.
