### ISSUE TITLE
Profiles based on battery/plugged in

### ISSUE THREAD

**Issue by narker** [seerge/g-helper#1599]
**Describe the solution you'd like**
I'd like for ghelper to automatically switch modes based on whether or not the laptop is connected to power. For instance have it switch to ultimate/balanced when plugged in and silent/eco when on battery.

**Comment by seerge** [comment]
@narker this is already the case

App remembers last used mode for battery / plugged in cases and switches it next time you plug / unplug.

For dGPU mode - there is Optimized mode that does exactly that.

**Comment by seerge** [comment]
https://github.com/seerge/g-helper#gear-automatic-switching-when-on-battery-or-plugged-in
