### ISSUE TITLE
[Feature Request] GPU power draw monitoring in "GPU Mode" text info section

### ISSUE THREAD

**Issue by AudreyAP** [seerge/g-helper#1600]
I was playing around with nvidia-smi and found that you can very easily get the current power draw of the GPU in plaintext, without formatting:

`nvidia-smi --query-gpu=power.draw --format=csv,noheader,nounits`

I think it would be fun to have this information shown in ghelper alongside the GPU temperature and fan lines. There is no technical reason for this, I just think it would be cool and maybe useful for troubleshooting nvidia power saving issues, like the ones they have introduced in a few recent driver updates. 

Thank you :)

**Comment by seerge** [comment]
@AudreyAP hello 

I think it's also possible to get power draw from nvidia driver itself (via same methods app currently gets temperatures)

But my main practical question - is why ? As on desktop use scenario, when you can open app window and see it - your power draw most probably be minimal.

And in game (when you most probably want to see it), any overlay (like nvidia's own or afterburner) is much more convenient ? :)

**Comment by AudreyAP** [comment]
Mostly for troubleshooting. Nvidia drivers recently have had numerous power saving bugs and it has become really annoying to pull out a terminal to grab the power usage to see if I need to reboot. 

Not an essential feature, but if Nvidia keeps releasing broken drivers it might become necessary 😂

**Comment by Kikimahe** [comment]
Hi @AudreyAP 

You can use HWinfo64 for example.

You will be able to see GPU consumption (and much more).
And above all **you can set an alert** if GPU consumption decreases. ;-)

![Screenshot 2023-11-19 092054](https://github.com/seerge/g-helper/assets/142881210/d251dae4-d0ef-48a0-b7e9-935710e43122)

**Comment by AudreyAP** [comment]
Thanks @Kikimahe but I'm aware of hwinfo - I just don't want to pull it out every time someone seems off with the GPU.

**Comment by faslanetech** [comment]
It's a good idea I think as well. Saves from using another app when (if it was easy to do) you could see at a glance in Gheloer and not have to pull up a second app. :-) I was raised in the U. S. and think Fahrenheit or Celcius temps would be a great option. As most hardware monitoring software offers the choice in the preferences but it's not THAT important. Just easy for people who weren't raised where the metric system was prevalent but the imperial system was.. like I. The U. S. But alas, it's still a great lil app :-)

**Comment by seerge** [comment]
I will put this on hold for now, as i simply don't have laptop with nvidia atm :) so can't even test if driver readings work ...

**Comment by faslanetech** [comment]
I'm on an Nvidia RTX 3070 and the temps are quite accurate actually. :-)

**Comment by faslanetech** [comment]
If you'd like me to test anything in future just say the word happy to help.

I have an Asus ROG M16 2021 model 16.4" With RTX 3070Ti 8GB, 40GB RAM, 2x2TB NVME Samsung 990 Pro at 7100MB/s read and roughly 6700MB/s Write speeds. Panel is a 165Hz FYI .. If I can test anything I'm happy too. Cheers 

Fas

**Comment by IceStormNG** [comment]
> Mostly for troubleshooting. Nvidia drivers recently have had numerous power saving bugs and it has become really annoying to pull out a terminal to grab the power usage to see if I need to reboot.
> 
> Not an essential feature, but if Nvidia keeps releasing broken drivers it might become necessary 😂

Btw: for my laptops, only the ASUS drivers have proper power management and sleep. The Nvidia drivers randomly wake up the GPU for no reason and keep it awake for minutes. Like, any driver from Nvidia that was released after the one that ASUS supplied.
Also Nvidia Container going south every now and then and pegging one CPU core.
If you don't need anything from the newer drivers (like game support), I would recommend to stick with the driver that ASUS supplied (or grab one from another newer ASUS laptop, there is only one Nvidia package for laptop drivers after all).

**Comment by seerge** [comment]
@IceStormNG I wonder what do they actually change in a driver comparing to stock . Cause for AMD drivers they just strip it from some extras (coming in a package)

**Comment by IceStormNG** [comment]
I honestly do not know. I guess there are just some presets they can change or some components they can remove. I guess Nvidia does not allow for in-depth modifications.
But whatever ASUS can change shows, because whatever Nvidia driver I test, only the ASUS one works without weird issues or situations where the GPU does not go to sleep.
Could also be that the ASUS certified is just the latest Nvidia driver that isn't full of bugs.

**Comment by AudreyAP** [comment]
@IceStormNG I've had no issues while using nvcleanstall - i simply dont install container!

![image](https://github.com/seerge/g-helper/assets/130399040/650875e2-7db1-42dc-bc21-39a8d59a395f)

These are the only required components. Works great.

**Comment by IceStormNG** [comment]
I do need the NVContainer though. As this one is required for the Nvidia Control panel to work. This adds the taksbar icons to togglet he MUX or to show whether the NVGPU is online.

**Comment by AudreyAP** [comment]
All of that works for me, with no weird thread behavior or anything as you describe.

**Comment by Diego-JRH** [comment]
Anyone knows what they actually change in the drivers when they make "X" game compatible? Is it really that necessary that the drivers oficially support that specific game for the game to run good?

**Comment by IceStormNG** [comment]
They add a game profile. This can range from enabling/disabling driver features to actually making some improvements in the driver to mitigate performance issues or crashes in the game.

**Comment by seerge** [comment]
@AudreyAP some updates.

Launching

```
nvidia-smi --query-gpu=power.draw --format=csv,noheader,nounits
```

every 2 seconds to show power usage, seem to be quite resource-heavy procedure with huge amount of overhead.

As for getting power usage directly from driver api - it seems to be more difficult than I thought, as it's simply not there ... :

**Comment by seerge** [comment]
@AudreyAP I have digested everything, and for now I have to take a decision not to do it on this stage at all.

Reasons are simple

Running nividia-smi every 2 seconds or so, is just too resource-heavy (+ it could wake up GPU sometimes). On each run that app would run own initialization,  check all GPUs, get power draw, etc.

Doing via NVAPIWrapper is not possible, as it's not covered.

Doing it via [NVidiaML](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Interop/NvidiaML.cs) library seem to be possible, but I will have to integrate whole new library just for one minor metric in the app, + again I was reading somewhere that there is a chance this queries can wake up GPU (i.e. do more harm than good)

So closing as not planned. Sorry
