### ISSUE TITLE
Cursor moves to center of screen when using multi monitors

### ISSUE THREAD

**Issue by YiQuSi** [seerge/g-helper#1601]
**Describe the bug**
When using multi monitors, cursor will be moved to center of main monitor on G-Helper first starting.

**Clear scenario to Reproduce**
1. Keep a extra monitor on (will start with laptop)
2. Turn on the laptop
3. Move cursor to somewhere
4. Wait G-Helper starting automatically (or run it manually)
5. The position of cursor changes

**Expected behavior**
The position of cursor will not change when app starting.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13372722/log.txt)

**Screenshots or screencasts**
null

**Desktop**
 - OS: Windows 11 Build 25967.1010
 - Laptop model: ASUS TUF Gaming F15 FX507ZM

**Asus software**
- Armoury Crate (or it's services) installed - NO
- MyASUS installed - NO
- Other Asus services running in background
  ASUS Hotplug Controller
  ASUS Smart Display Control

**Additional context**
- Position changing will not happen in second starting of G-Helper.
- Same thing happens when I turn on my extra monitor without G-Helper running. After it happened, the cursor will not be move again when G-Helper starting.

**Comment by seerge** [comment]
@YiQuSi hello, I can only guess it's just strange behavior of windows due to refresh rate change.

Change laptop screen setting to constant 165Hz instead of Auto. Does your problem keep happening?

And you don't need **ASUS Smart Display Control** at all, as it will only interfere with exactly same refresh rate changer inside g-helper itself

**Comment by YiQuSi** [comment]
@seerge Thank you for your answer.

I have uninstalled **ASUS Smart Display Control** and changed the setting to 165Hz. Now there is no problem in my daily use.

But the position changing still happens when changing the setting to **Auto** for the first time. I do not know why it just happens once after laptop startup.

**Comment by seerge** [comment]
@YiQuSi as I have mentioned before, it's probably happening cause your refresh rate changes.

Why your windows boots in some other than 165Hz refresh rate in a first place - I have no idea. I can only recommend to do a clean GPU driver reinstall, mb it will change that :)

**Comment by YiQuSi** [comment]
@seerge My statement may have caused some misunderstanding because of my awful English.

The setting is **165Hz** after Windows boot. After I change the setting to **Auto**, position changing happens.

Now I found position changing can happen without extra monitor. Anyway this little problem just happens when the setting is **Auto**. Maybe I do need to do a clean reinstall…

**Comment by seerge** [comment]
@YiQuSi - does your cursor jump to center when you manually select 165Hz inside app ? (even when it's already 165hz)

**Comment by YiQuSi** [comment]
@seerge I think I cannot do that because the setting in G-Helper is **165Hz** (165Hz + OD) after system boot. I tried to click the button and nothing happened.

Now I prefer to see if others have the same problem. Whether they are using G-Helper or Armoury Crate. And whether they are using multi-monitor or not.

By the way, there is one thing I have forgot to mention. When display refresh rate changes, screen turns to black for a while. But there is no black when change the setting from **165Hz** to **Auto**, so it looks strange.
