### ISSUE TITLE
Create independent configuration files for specific situations

### ISSUE THREAD

**Issue by jhzgjhzg** [seerge/g-helper#1602]
May I ask if it is possible to create independent configuration files for specific situations, such as when I want to disable the touchpad while playing games, similar to the profile function of the armoury creat.

**Comment by seerge** [comment]
@jhzgjhzg hello, touchpad can already be disabled via very easy to reach hotkey :) it's status is not stored anyhow config as this is just a windows setting

**Comment by jhzgjhzg** [comment]
> @jhzgjhzg hello, touchpad can already be disabled via very easy to reach hotkey :) it's status is not stored anyhow config as this is just a windows setting

This is just an example. I hope to apply different fan curves and overclocking settings in different games. Can this be achieved :)

**Comment by seerge** [comment]
@jhzgjhzg fan curves and clock offsets are already part of profiles :) (and you can create as many as you want under ``fans+power`` screen)

You can't set profile automatically based on game, cause game detection is a separate story (and difficult task), but you can easily switch between profiles with FN+F5 / Shift+FN+F5  (forward / backward)

**Comment by jhzgjhzg** [comment]
> You can't set profile automatically based on game, cause game detection is a separate story (and difficult task), but you can easily switch between profiles with FN+F5 / Shift+FN+F5 (forward / backward)

Thanks a lot :)
