### ISSUE TITLE
ROG Strix G513RM keyboard lighting and missed keys bug

### ISSUE THREAD

**Issue by Solforge** [seerge/g-helper#1603]
**Describe the bug**
When I got this laptop the keyboard had a problem where it would miss inputs as described in this reddit thread
https://www.reddit.com/r/ASUS/comments/10p1cvy/weird_rog_strix_g15_laptop_keyboard_problem/

The solution of using a keyboard lighting pattern from the aura sync tab instead of the device tab in armory crate fixed the problem and the keyboard would work perfectly fine for months. The past few days I tried swapping to g-helper, but unfortunately it has made this missed input keyboard bug come back.

I tried to see if changing the keyboard lighting pattern in g-helper would fix it like in armory crate, but in a possibly related problem it seems in g-helper the star, rain, highlight, laser, ripple, comet and flash patterns don't work. Static, breathe, color cycle rainbow, strobe, heatmap and ambient patterns work fine. (though I haven't tested to see if the heatmap pattern is actually changing with temperature).

So I don't really care about what the keyboard lights are, and obvoiusly the keyboard bug being there in the first place is ASUS's fault not G-helpers. But I'm hoping there might be some fix this keyboard missing inputs bug without me reinstalling armory crate again and deleting g-helper. 

**Clear scenario to Reproduce**
1. Change keyboard light to one of the patterns listed as not working above
2. keyboard light will remain stuck on whatever exact colors it had at the moment of the switch. (so animated ones like breathe will pause in place)
3. lighting won't change until one of the patterns listed as working is selected.

**Expected behavior**
All lighting patterns work. 
(And hopefully make it so the keyboard never does the missed inputs bug without switching back to armory create, I'm fine if there is a clever way to fix this even without fixing the lighting patterns)

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13387556/log.txt) That's me going down the list selecting each lighting pattern

**Desktop (please complete the following information):**
 - Windows 11

**Asus software**
- Armoury Crate uninstalled
- MyASUS uninstalled
- Other Asus services disabled

**Comment by seerge** [comment]
@Solforge so you just want to remove unsupported backlight modes for your model ? Do you know if all G513RM don't have "Star", "Rain" , etc modes at all ?

**Comment by Solforge** [comment]
> Do you know if all G513RM don't have "Star", "Rain" , etc modes at all?

Oops I didn't know that sorry. I didn't pay much attention to the list of patterns before and reinstall armory crate to check the list available there. Thought it not working was related to my keyboard bug

Armory crate had keyboard light patterns on the device tab, and patterns on the aura sync tab. When it was using a pattern from the device tab I got an annoying bug with my keyboard missing inputs, and when I selected "aura sync" on the device tab so it was using a pattern selected from the aura sync tab my keyboard would never do that bug. I want G-helper to do whatever armory create was doing whenever an aura sync pattern was active that stopped the keyboard bug.

I have no idea why this bug worked this way it makes no sense to me. Multiple people in that reddit thread had that bug, and the same solution worked for them, so it is not just me. I know it is unlikely, but I thought I would ask here to see if somebody would have a solution to this problem besides switching back to armory crate instead of g-helper.

**Comment by seerge** [comment]
@Solforge G-Helper has nothing to do with your keys not registering sometimes. It doesn't control your keys in a first place. It's purely on hardware side. 

As for backlight modes - everything listed (except newly added Heatmap and Ambient), are hardware modes. Keyboard just runs that backlight mode by itself, w/o any involvement from the app side. G-Helper can only send command to switch between the modes. If they are not supported by your model - they won't work.

I have added your model to the list of Strix devices that have only limited RGB support
https://github.com/seerge/g-helper/commit/69757ff46023d676c22fcee9a9bdde94551629f2

This build should show only supported modes
[GHelper.zip](https://github.com/seerge/g-helper/files/13390315/GHelper.zip)

**Comment by Solforge** [comment]
> G-Helper has nothing to do with your keys not registering sometimes. It doesn't control your keys in a first place. It's purely on hardware side.

That makes sense and I believe that is true. That is why my first post said this bug was Asus's fault, not g-helpers. The problem is Asus is incompetent enuogh to make this keyboard that by default has this annoying bug, yet mysteriously stops doing the bug when armory crate is doing a pattern from the aura sync tab. And unfortunately Asus's incompetence is going to work out in their favour and force me to switch back to armory crate so I can click on the aura sync button to avoid the bug. It sucks!

I was hoping somebody here might have some clever insight or knowledge on what could be going on with this bug and a way to try to stop it without reinstalling armory crate, but it is understandable if not.

Thanks for fixing the backlight list, at least my dumb mistake about the list has at least made the program a bit better for some other users.

**Comment by seerge** [comment]
@Solforge Heatmap and Ambient modes use same approach as aura sync app does (i.e. they constantly send color command to keyboard)

You can try them and check if that fixes your specific problem

**Comment by Solforge** [comment]
Hey. I've been using heatmap and can confirm it does fix my specific keyboard problem when it is active, so I don't have to switch back. Thanks for your help. 

Unfortunately I do have to report that sometimes it seems like the heatmap and ambient modes break, and it will just do the last lighting pattern selected that isn't one of those two modes. When this happens fixing it is as simple as relaunching g-helper (Specifically with G-helper open so it appears i the task bar, I right click on the icon in the task bar and then click on the Ghelper option in the pop up and it seems to reset it and it goes back to doing heatmap). 

Also between heatmap and ambient there is a new GPU mode option that seems like it never does anything. Is that supposed to be there?

**Comment by seerge** [comment]
@Solforge most probably you have aura service from asus still running and overwriting backlight settings :)

As for GPU mode - it just colors keyboard into a single color based on current GPU status (ultimate / standard / eco)

**Comment by KentNguyen132** [comment]
@seerge I also have a G15RM (G513RM-HQ055W to be exact), and my heatmap and ambient mode do not work. In ambient mode, the light bar under the laptop works as expected, but the whole keyboard just turns off completely. The same goes for heatmap mode.

After reviewing this thread and trying out the build that you gave:

> This build should show only supported modes [GHelper.zip](https://github.com/seerge/g-helper/files/13390315/GHelper.zip)

It does help fix the heatmap mode, but the ambient mode doesn't fully work; only parts of the keyboard light up.

https://drive.google.com/drive/folders/1uF8Rz0AsX0yVd2AkPdWFocFDGhnuRofG?usp=sharing (both build is shown)

[log.txt](https://github.com/seerge/g-helper/files/13931542/log.txt)

**Comment by seerge** [comment]
@KentNguyen132 hello,

Does your device have per-key RGB or just 4 zones?

It seems like G513 exists in 2 variants (while 4-zone options dominate), and it's not possible to distinguish them cause model names are literally same

Please check this build from this comment https://github.com/seerge/g-helper/discussions/1906#discussioncomment-8114075

(and add param that I listed there)

**Comment by KentNguyen132** [comment]
@seerge omg yes! It works perfectly now; thank you so much!
