### ISSUE TITLE
Small icon bug on v0.132 

### ISSUE THREAD

**Issue by Kikimahe** [seerge/g-helper#1604]
Hi, 

With **v0.132**, the Ghelper icon is replaced by a small blue icon in the Windows taskbar.
Maybe it's intentional (?), but it's not indicated in the changelog. :-)

Have a nice day.

v.0.132
![132](https://github.com/seerge/g-helper/assets/142881210/7243eef3-1b9a-4bae-82ac-941ea3157adc)

v0.131
![131](https://github.com/seerge/g-helper/assets/142881210/ea4fa1a5-de74-4d5d-9d84-1d05dec60f6a)

**Comment by seerge** [comment]
@Kikimahe this is a side effect of added main window icon. I have removed that (and just re-uploaded a fixed build over existing)
https://github.com/seerge/g-helper/releases/tag/v0.132
