### ISSUE TITLE
[Feature Request]Setting the polling rate of discharging rate

### ISSUE THREAD

**Issue by L00I** [seerge/g-helper#1605]
I use a laptop so I care about the wattage of the computer, ghelper really helpful and convenient,  but i want to have a more frequent result. 
The discharging rate result takes a lot of time to change. It usally takes more than one minite.
I hope there can be an option to set the polling rate of discharging rate. Or there is one and i don't know. If so, please tell me.

**Comment by seerge** [comment]
@L00I app requests discharging rate once in 2 seconds from windows. 

Rest is up to windows and hardware controller that actually measures it. On some devices it updates fast enough (like every 5 seconds), on some (especially on G14) discharge rate in windows is a moving average from actual one over last 2 minutes or so.

That's how things are
