### ISSUE TITLE
Per-core Curve Optimizer?

### ISSUE THREAD

**Issue by fscottcopeland** [seerge/g-helper#1606]
Just a quick one...

Would it be possible to add per-core curve optimizer functionality (perhaps as an 'advanced' mode or something)? Currently all-core works great, but I know I could certainly tune things further if I could fiddle with each core separately. 16 core 7945HX if I can help test at all. I can't actually find any other software that allows this yet.

Thanks!

**Comment by seerge** [comment]
@fscottcopeland hello, you can try UXTU https://github.com/JamesCJ60/Universal-x86-Tuning-Utility , i think it offers per core optimization :)

As for adding this to g-helper, i think it's extremely niche use-case. So I don't plan it :)

**Comment by fscottcopeland** [comment]
I'd like to re-request this please...

See https://github.com/irusanov/ZenStates-Core

Dual CCD CPUs often have 1 CCD which can work with a much lower negative CO offset. A global CO setting can therefore reduce the amount of performance one can extract. Here are my stable(ish) settings using the above tool:
![image](https://github.com/seerge/g-helper/assets/91984658/c7ebd3aa-9be3-4de0-994c-b439b85f13c4)

Most people don't know G-Helper exists. So people who do use G-Helper over Armory Crate are more likely the "Power users" or tweakers anyway. I don't think I'd be alone in wanting this feature...pretty please! G-Helper is already a niche tool :)
