### ISSUE TITLE
Any way to get this to work with peripherals without using an Asus laptop?

### ISSUE THREAD

**Issue by Bokaii** [seerge/g-helper#1607]
Hi! I own a Asus Azoth keyboard that I want to customize. But the absolut CANCER of a program that is Armory Crate is in the way of that. Is there any way I can use your application to configure it, despite my computer not being an Asus Laptop?

(I tried to install it anyway, but it complains about Asus System Control Interface and will not start.)

Regards,
Bokai

**Comment by seerge** [comment]
@Bokaii hello,

Currently G-Helper supports [only some Asus mice ](https://github.com/seerge/g-helper#mouse-asus-mouse-and-other-peripherals-support). Adding keyboard support is much more difficult, and (technically) impossible, cause I don't have your device :)

So for now I don't plan it.

If you want to control RGB only - you can try OpenRGB, it should work ... :)

**Comment by seerge** [comment]
@Bokaii hello, 

If you are interested you can test external keyboards support in a new build https://github.com/seerge/g-helper/discussions/5710 

Thanks!
