### ISSUE TITLE
Command Center mapping not working

### ISSUE THREAD

**Issue by JGtm** [seerge/g-helper#1608]
On Asus Rog Ally, when setting up Command Center mapping to certain value like 0x11 0x12 0x5A, all mappings seems to stop working. ROG button is not calling G-helper anymore. Have to restart the app to make it work again. If I map CC to 0x5A, there’s no issue. I can use both mappings in any case. Once I remap it to something else, seems like remapping feature is disabled. 
Tried a fresh install with both 0.129 and 0.132. Same results

**Comment by seerge** [comment]
> ## NOTE
> Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer.  Please respect the time of the developer. Thanks.

**Comment by seerge** [comment]
@JGtm actually, despite you have ignored logs, I have figured out what cold be a reason.

This build should work fine

[GHelper.zip](https://github.com/seerge/g-helper/files/13394485/GHelper.zip)
