### ISSUE TITLE
GHelper v0.132, Airplane Mode

### ISSUE THREAD

**Issue by UnknownLOL** [seerge/g-helper#1609]
Pushing any keyboard key switches Airplane mode on and off.

**Clear scenario to Reproduce**
1. Press any key

**Expected behavior**
Only Fn+F12 should do this.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13399038/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11 latest update
 - Flow Z13 GZ301ZE

**Asus software**
- Uninstalled

**Additional context**
v0.131 doesn't do this. Although I do remember Airplane Mode being randomly turned on when I launch laptop in the morning (I pretty much don't touch it ever) in previous GHelper versions as well. Not sure if it's related.

**Comment by seerge** [comment]
@UnknownLOL hello, that's disappointing of course.

If you mean that Fn+F12 - then G-Helper doesn't handle that key in a first place :) it just emits ``Win+A`` hotkey on hardware level.

It looks more like some hardware problems with your keyboard?

**Comment by UnknownLOL** [comment]
This behavior is not present in v0.131 though. It may be coincidental (an interraction with some other app / setting). I'll try to test some more.

**Comment by seerge** [comment]
@UnknownLOL well, as I told, quit g-helper and your airplane mode hotkey will keep working :)

Anyway, to make 100% sure I have removed a F12 binding from the app at all , try this build if it makes a "difference" in your case

[GHelper.zip](https://github.com/seerge/g-helper/files/13400145/GHelper.zip)

**Comment by UnknownLOL** [comment]
This may be result of some weird app interraction or just a coincidence. I do have key remapping software installed. Just now I reinstalled GHelper 0.132 and I don't get this problem any longer. Tried to restart a few times even, everything works as it should. Not sure what might have happened.

**Comment by seerge** [comment]
Ok, great! Closing as completed then
