### ISSUE TITLE
0.132 GPU

### ISSUE THREAD

**Issue by HuanMeng913** [seerge/g-helper#1610]
When I updated to version 0.132, the GPU frequency in balanced mode could not run the target frequency of 2760mhz after overclocking, and could only be around 2100mhz to 2500mhz

**Comment by seerge** [comment]
@HuanMeng913 G-Helper is not touching your GPU frequency anyhow, unless you have intentionally and manually set a limit. And even in case of a limit - it's just a driver cap, not a "target".

Given that  you have totally ignored issue requirements, I'm closing this

> ## NOTE
> Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. Please respect the time of the developer. Thanks.
