### ISSUE TITLE
Battery Depletion while Gaming in Turbo

### ISSUE THREAD

**Issue by XynoCrest** [seerge/g-helper#1611]
**Describe the bug**
This bug has been bothering me for months and I would be over the moon if this could be resolved -
- So whenever I am gaming with Turbo mode on and plugged into the grid my charge percentage will deplete, although very slowly. (like it takes over half an hour to go from 80.0 to 79.4). 
- But, when it does get to 79.4%, my battery charge indicator light switches to yellow, the laptop starts charging and goes back to 79.5% and the light switches back to white.
-  This process keeps repeating and my laptop's charging indicator will keep bouncing from yellow to white every minute until I close out of the game. 
- Now, it's not like it's a hardware problem where the power brick isn't powerful enough to supply the power needed that the laptop needs to pull the charge from the battery. 
- Because after the introduction of the 1-time 100% charge button (great feature by the way!) - I press the button and the laptop starts charging normally (meaning it could have supplied enough power in the first place) and if I let it charge like 1%  before turning the button back off, the frequent light changing stops until it once again depletes back to 79.4%.

**Expected behavior**
- I wish the laptop's charge stayed the same even when gaming in Turbo.
- Or there should be buffer (of charge percentages) between when the laptop starts charging and when the charging indicator light turns yellow. (Like the laptop could start charging from 79.5% and the light would only change color when it depletes to 79.0%).

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13399529/log.txt)

**Desktop Information:**
 - OS: Windows 11 - Version 23H2 (0S Build 22631.2715)
 - Laptop model - ROG Zephyrus G15 GA503RM

**Asus software**
- Armoury Crate Uninstalled using its uninstaller tool
- MyASUS Uninstalled
- Asus services stopped through the setting inside Extra

**Additional Notes**
- I don't know if this could be related or not, but my charging limiter slider also doesn't work for custom percentages, only works when setting to 80% or 100%.

**Comment by seerge** [comment]
@XynoCrest hello, this is purely hardware issues of your device and it's not related anyhow to G-Helper. 

Probably your power brick is not powerful enough to handle laptop demands. See other user explaining this in detail here
https://github.com/seerge/g-helper/discussions/864#discussioncomment-7548647

Alternatively you can just try to limit your total power a bit, to match power brick :)

**Comment by XynoCrest** [comment]
I initially thought the same thing and I even did a poll on reddit (results attached) asking people if their battery drains while gaming in turbo and lot of people seem to have the same issue. 
![IMG_2154](https://github.com/seerge/g-helper/assets/140979619/46aba2a5-75e9-4e76-9d8e-d48960be6d9a)

But if the power brick not being powerful enough is the issue, why does it successfully charge up the laptop when I toggle on the 100% charge button while gaming.

**Comment by seerge** [comment]
@XynoCrest i don't know :) but some app on windows doesn't control that in a first place. It's controlled by hardware as it should.

**Comment by XynoCrest** [comment]
Can you think of any specific thing that could be messing it up?

- When I first got the laptop in September of 2022 this issue wasn’t there
- I first noticed it when I switched to Ghelper after uninstalling armory crate. (naturally I thought it was the issue, but it wasn’t )
- I then tried switching back to armory crate by reinstalling windows to the default image using MyAsus in WinRE
- I also tried switching BIOS settings back to default.
- I tried rolling back the BIOS to every version 311, 313, 315

Nothing I tried was able to fix, after the issue started :(

**Comment by seerge** [comment]
@XynoCrest 

As you say, if all software changes that you have tried (including reverting to original state of windows with AC) doesn't help - probably it's not software related then? :)

Why don't you just try more powerful power brick ? I think they cost like nothing on Amazon :)

**Comment by XynoCrest** [comment]
Thank you for the suggestions! It’s not an issue that would warrant a new purchase in my opinion, because although it’s hella annoying to see the light change every minute, my battery percentage effectively stays the same because it keeps charging and discharging. It’s just a minor inconvenience really!

The issue also goes away completely in other modes except Turbo. And I am fairly convinced that it’s not the hardware exclusively because it can charge the laptop when it needs to under the same power load.

**Comment by seerge** [comment]
@XynoCrest it goes away in other modes, cause (most probably) then laptop just uses less power and therefore enough to stay away from depleting battery next to power brick.

Try to limit power a bit (at least for CPU), may be it will help

**Comment by XynoCrest** [comment]
What CPU power limits would you recommend for turbo?

**Comment by seerge** [comment]
@XynoCrest it's up to you :) but since you have same CPU as I do on my G14, anything more than 35-40W really doesn't worth it.

P.S. What you also can do, is before starting your game, charge battery on full and then set charge limit to minimum (like 40%). Then, even if your laptop will be draining battery next to power brick - it won't start charging immediately after at least :)

**Comment by XynoCrest** [comment]
That’s a pretty good idea, thank you so much for the suggestions! I will first try your suggested power limits, and if it does fix the issue try to increase it bit by bit from there :)

**Comment by XynoCrest** [comment]
Hey, I just wanted to ask if there is a way to automate switching to 60% battery mode when I open a game and switching back to 80 when I close out of it? 

Like can you interact with GHelper using the command line, then perhaps I can make an AHK script to automate it?

**Comment by seerge** [comment]
@XynoCrest you can just run a powershell command to set a limit

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00120057, 60)

```

**Comment by XynoCrest** [comment]
I get an error while trying to run the command - 
<img width="675" alt="Screenshot 2023-12-04 171627" src="https://github.com/seerge/g-helper/assets/140979619/2f04e03a-2485-4748-a018-c4bb4459eaf4">

**Comment by XynoCrest** [comment]
Do you need MyAsus installed for this command to work? because I don't - also my custom battery limit percentages do not work.

**Comment by XynoCrest** [comment]
I get the same error when attempting 80. Also GHelper can set the battery limit to 60 just fine

**Comment by seerge** [comment]
@XynoCrest then you can try to write some macro in autohotkey to actually click on a slider for 60/80 :) but honestly this is veeeeery specific desire that you have

**Comment by XynoCrest** [comment]
Hey I was able to write a script that achieves what I want by changing the Ghelper config file in %appdata%. 

(What I am doing currently is launching the game and when the game window exists, the script closes Ghelper, changes the config file and reopens Ghelper - does the same thing when the game closes).  

Thank you so much for you help thus far! I still have some questions, if you could please help me answer them -
- You do need to relaunch Ghelper for any manual changes in the config.json to take effect right?
- Will relaunching Ghelper after launchigng a game cause any issue with things like power, fan curve, performance modes, etc?
- Also, does Ghelper launch with admin rights when it opens at windows startup?

**Comment by XynoCrest** [comment]
I see, thank you so much for the info! You have been a big help!

**Comment by XynoCrest** [comment]
Hey so I also decided to make my ahk script disable turbo boost before a game launch and switch it back to aggressive when the game's closed by using the same method (modifying the config.json). 

I was wondering if switching turbo boost modes like this can lead to any sort of problems, especially because the mode is switched miliseconds before a game is launched?

**Comment by seerge** [comment]
@Maneeha1234SL 330W is original. It's supposed to be like that by design.
