### ISSUE TITLE
Keyboard backlight and Fans stop working

### ISSUE THREAD

**Issue by SanmayJoshi** [seerge/g-helper#1612]
**Describe the bug**
Upon waking the laptop from sleep,
1. Keyboard backlights either start oscillating or stay turned off, regardless of the levels set.
2. Fans do not work (G-Helper does not report fan speeds)

**Clear scenario to Reproduce**
1. Set the GPU mode to 'Optimized' in G-Helper and run on startup is enabled. Please see configuration under screenshots.
2. Make sure that laptop is switched to wall power.
3. Put the laptop to sleep. Let the laptop be completely in sleep mode. The keyboard backlight start oscillating in my case.
5. Now turn the wall power off.
6. Wait for some 45 sec. You would notice a change in keyboard backlight pattern.
7. Wake the laptop up by pressing any key.

**Expected behavior**
1. Backlights should be under control as usual.
2. Fans should work as expected.

**App Logs**
Full Log file: [log.txt](https://github.com/seerge/g-helper/files/13399956/log.txt)
Limited Log containing only the details post reproducing the issue: [limited log.txt](https://github.com/seerge/g-helper/files/13399958/limited.log.txt)

**Screenshots or screencasts**
Configuration under which bug is reproduced:
![image](https://github.com/seerge/g-helper/assets/26383381/ad6fe4a1-fb0a-49f7-a950-2afabe91e993)
![image](https://github.com/seerge/g-helper/assets/26383381/01077b1a-98e2-41e3-8f87-9a25e0ce7f67)

**Desktop**
 - OS: Windows 11
 - Laptop model: ASUS TUF Gaming F15FX506HC

**Asus software**
- MyASUS installed
- Armory Crate uninstalled
- Other Asus services: NOT running in background

**Additional context**
None

**Comment by seerge** [comment]
@SanmayJoshi hello, it's just hardware / firmware issues of your specific device.

G-Helper doesn't control your fans in realtime anyhow. Please check readme.

**Comment by SanmayJoshi** [comment]
In case someone stumbles upon this issue in future:

This is an issue in the *FX506HC* model (2021). The issue occurs when GPU Mode is set to *Optimised*. The issue occurs even on *Armoury Crate*.

**Workaround:** Set the GPU Mode to 'Standard'.

**Extra info:** This model (FX506HC) doesn't also allow setting custom fan speed profiles.

**Comment by seerge** [comment]
@SanmayJoshi Optimized mode is just automatic switch between Standard when plugged in and Eco when on battery :)

I assume it would be fine with Optimized as well, as far as you are plugged

**Comment by SanmayJoshi** [comment]
Just did a few more tests and confirmed that the issue occurs if the device boots/wakes with iGPU. If the device boots/wakes with dGPU then the issue doesn't occur. Thanks @seerge .

Is it a possibility in gHelper to ensure that the device boots/wakes with dGPU always? And only upon boot/wake the user-specified GPU configuration (Eco-iGPU/Standard-dGPU) is applied.

Will stick with 'Standard' GPU mode for now.

**Comment by seerge** [comment]
@SanmayJoshi it's possible - https://github.com/seerge/g-helper/discussions/1042

**Comment by SanmayJoshi** [comment]
> @SanmayJoshi it's possible - just check 'Enable GPU on shutdown' #1042

Thanks. I have set the option in 'Extra'. The issue however persists when putting the device to sleep in 'Eco mode' and then waking up in 'Eco mode'.

**Comment by seerge** [comment]
@SanmayJoshi of course it "persists" in sleep :) how do you  expect app to act while windows is in sleep?
