### ISSUE TITLE
Color change when CAPS or NUM locked

### ISSUE THREAD

**Issue by SanmayJoshi** [seerge/g-helper#1613]
**Description**
It is sometimes a little difficult to know whether NUM Lock is on or off.

**Solution**
Might help if a color change is there. So when NUM Lock is on, only the NUM Lock key on keyboard would light up to the color of user's preference. The color may be set in G-Helper.

**Alternatives considered**
Not much to my mind :)

**Additional context**
CAPS lock does have a red LED that lights up when it is on. To my observation, its behavior is regardless of the color we set in G-Helper.

**Comment by seerge** [comment]
@SanmayJoshi hello, it's not possible to control backlight of num-keys individually anyhow
