### ISSUE TITLE
Flow Z13 Keyboard issues, GHelper v0.133 \ 0.132

### ISSUE THREAD

**Issue by UnknownLOL** [seerge/g-helper#1616]
I've tested v0.132 and v0.133 some more and found that I can not control keyboard backlight settings with GHelper. Any changes I do through the app don't do anything - brightness, animation speed, animation mode, colors, etc. Everything works as soon as I roll back to v0.131.
I tried reconnecting keyboard, restarting and shutting down laptop, restarting GHelper. Only rolling back to v0.131 restores the aforementioned functions.
Sorry for spaming bug reports. I'm afraid something that was changed in 0.132 gives me problems with keyboard still. 

1. update GHelper v0.131 to v0.132 or v0.133.
2. try to change any keyboard settings in GHelper menus.

**Expected behavior**
Settings should change keyboard behavior.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13402410/log.txt)

 - Windows 11 latest
 - ROG Flow Z13 GZ301ZE

- Asus software uninstalled 
- 0 Asus processes running

**Comment by 123dqwkhjk** [comment]
the keyboard backlight is broken for me on ga503rm either.(vesion 0.133)

**Comment by seerge** [comment]
@UnknownLOL @123dqwkhjk 

try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/13403099/GHelper.zip)

**Comment by 123dqwkhjk** [comment]
[log.txt](https://github.com/seerge/g-helper/files/13403128/log.txt)

**Comment by seerge** [comment]
@123dqwkhjk does it mean it still doesn't work for you? I have made log a bit more verbose, post it from this build please

[GHelper.zip](https://github.com/seerge/g-helper/files/13403166/GHelper.zip)

**Comment by UnknownLOL** [comment]
@seerge 
The first build you've posted works for me after brief testing. I've done a restart and shut down just to be sure. Everything functions, no "Airplane Mode bug" either. Looks like it's fixed for good, thanks.

I've not tried the second one.

**Comment by 123dqwkhjk** [comment]
> @123dqwkhjk does it mean it still doesn't work for you? I have made log a bit more verbose, post it from this build please
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/13403166/GHelper.zip)

yes, it is not working sir even I reboot my laptop.
[log.txt](https://github.com/seerge/g-helper/files/13403185/log.txt)

**Comment by seerge** [comment]
@123dqwkhjk does this build make a difference ?
[GHelper.zip](https://github.com/seerge/g-helper/files/13403218/GHelper.zip)

**Comment by 123dqwkhjk** [comment]
no still broken
[log.txt](https://github.com/seerge/g-helper/files/13403237/log.txt)

**Comment by seerge** [comment]
@123dqwkhjk and this ?
[GHelper.zip](https://github.com/seerge/g-helper/files/13403250/GHelper.zip)

**Comment by 123dqwkhjk** [comment]
The light is on now but unfortunately it cannot turn off
2023/11/19 21:05:44: App launched: ROG Zephyrus G15 GA503RM_GA503RM :0.133.0.0zh-TW
2023/11/19 21:05:44: dGPU not found
2023/11/19 21:05:45: CPU: 8 - AMD Ryzen 7 6800HS with Radeon Graphics          - AMD64 Family 25 Model 68 Stepping 1
2023/11/19 21:05:45: AutoSetting for Online
2023/11/19 21:05:45: Input: \\?\hid#vid_0b05&pid_19b6&col05#7&2635b6bc&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/11/19 21:05:45: Mode = 2 : OK
2023/11/19 21:05:45: Clocks: Eco
2023/11/19 21:05:45: Eco flag : 1
2023/11/19 21:05:45: Mux flag : 1
2023/11/19 21:05:45: \\?\DISPLAY#CMN1540#5&2b412772&2&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/11/19 21:05:45: \\?\DISPLAY#CMN1540#5&2b412772&2&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/11/19 21:05:45: Screen = 165Hz : OK
2023/11/19 21:05:45: ScreenOverdrive = 0 : OK
2023/11/19 21:05:45: BatteryLimit = 60 : OK
2023/11/19 21:05:45: BatteryLimit = 60 : OK
2023/11/19 21:05:45: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
2023/11/19 21:05:45: USB 19B6: 5D-B3-00-00-FF-00-00-EB-00-00-FF-FF-FF-00-00-00-00
2023/11/19 21:05:45: USB 19B6: 5D-B4
2023/11/19 21:05:45: USB 19B6: 5D-B5-00-00-00
2023/11/19 21:05:45: USB 19B6: 5D-B9
2023/11/19 21:05:45: USB 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2023/11/19 21:05:45: USB 19B6: 5D-05-20-31-00-1A
2023/11/19 21:05:45: Error writing USB to HID device: Operation failed early: 參數錯誤。
2023/11/19 21:05:45: Monitor Power On
2023/11/19 21:05:46: Auto 19B6: 5D-BA-C5-C4-03
2023/11/19 21:05:46: Error writing Auto to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:46: Error writing Auto to HID 19B6 device: Can't write to this device.
2023/11/19 21:05:47: PowerLimit C0 = 5 : OK
2023/11/19 21:05:47: PowerLimit C2 = 87 : OK
2023/11/19 21:05:47: Latest version 0.133.0.0
2023/11/19 21:05:48: Key: 197
2023/11/19 21:05:48: HotKey 19B6: 5D-BA-C5-C4-02
2023/11/19 21:05:48: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:48: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:05:48: Key: 197
2023/11/19 21:05:48: HotKey 19B6: 5D-BA-C5-C4-01
2023/11/19 21:05:48: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:48: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:05:48: Key: 197
2023/11/19 21:05:48: HotKey 19B6: 5D-BA-C5-C4-00
2023/11/19 21:05:48: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:48: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:05:49: Key: 197
2023/11/19 21:05:49: HotKey 19B6: 5D-BA-C5-C4-00
2023/11/19 21:05:49: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:49: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:05:50: Key: 196
2023/11/19 21:05:50: HotKey 19B6: 5D-BA-C5-C4-01
2023/11/19 21:05:50: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:50: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:05:50: Key: 196
2023/11/19 21:05:50: HotKey 19B6: 5D-BA-C5-C4-02
2023/11/19 21:05:50: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:50: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:05:50: Key: 196
2023/11/19 21:05:50: HotKey 19B6: 5D-BA-C5-C4-03
2023/11/19 21:05:50: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:50: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:05:51: Key: 197
2023/11/19 21:05:51: HotKey 19B6: 5D-BA-C5-C4-02
2023/11/19 21:05:51: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:51: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:05:51: Key: 197
2023/11/19 21:05:51: HotKey 19B6: 5D-BA-C5-C4-01
2023/11/19 21:05:51: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:51: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:05:51: Key: 197
2023/11/19 21:05:51: HotKey 19B6: 5D-BA-C5-C4-00
2023/11/19 21:05:51: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:51: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:05:52: Key: 196
2023/11/19 21:05:52: HotKey 19B6: 5D-BA-C5-C4-01
2023/11/19 21:05:52: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:52: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:05:52: Key: 196
2023/11/19 21:05:52: HotKey 19B6: 5D-BA-C5-C4-02
2023/11/19 21:05:52: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:52: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:05:52: Key: 196
2023/11/19 21:05:52: HotKey 19B6: 5D-BA-C5-C4-03
2023/11/19 21:05:52: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:52: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:05:56: Varibright: 1,2
2023/11/19 21:05:56: Hibernate after 2147483647
2023/11/19 21:05:57: Slider 19B6: 5D-BA-C5-C4-02
2023/11/19 21:05:57: Error writing Slider to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:57: Error writing Slider to HID 19B6 device: Can't write to this device.
2023/11/19 21:05:58: Slider 19B6: 5D-BA-C5-C4-01
2023/11/19 21:05:58: Error writing Slider to HID 19B6 device: SetFeature failed.
2023/11/19 21:05:58: Error writing Slider to HID 19B6 device: Can't write to this device.
2023/11/19 21:06:00: Slider 19B6: 5D-BA-C5-C4-00
2023/11/19 21:06:00: Error writing Slider to HID 19B6 device: SetFeature failed.
2023/11/19 21:06:00: Error writing Slider to HID 19B6 device: Can't write to this device.
2023/11/19 21:06:01: USB 19B6: 5D-BD-01-F7-1E-FF-FF-FF
2023/11/19 21:06:02: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
2023/11/19 21:06:03: Key: 196
2023/11/19 21:06:03: HotKey 19B6: 5D-BA-C5-C4-01
2023/11/19 21:06:03: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:06:03: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:06:03: Key: 196
2023/11/19 21:06:03: HotKey 19B6: 5D-BA-C5-C4-02
2023/11/19 21:06:03: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:06:03: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:06:04: Key: 196
2023/11/19 21:06:04: HotKey 19B6: 5D-BA-C5-C4-03
2023/11/19 21:06:04: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:06:04: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:06:04: Key: 196
2023/11/19 21:06:04: HotKey 19B6: 5D-BA-C5-C4-03
2023/11/19 21:06:04: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:06:04: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:06:04: Key: 197
2023/11/19 21:06:04: HotKey 19B6: 5D-BA-C5-C4-02
2023/11/19 21:06:04: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:06:04: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:06:04: Key: 197
2023/11/19 21:06:04: HotKey 19B6: 5D-BA-C5-C4-01
2023/11/19 21:06:04: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:06:04: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:06:04: Key: 197
2023/11/19 21:06:04: HotKey 19B6: 5D-BA-C5-C4-00
2023/11/19 21:06:04: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:06:04: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:06:05: Key: 197
2023/11/19 21:06:05: HotKey 19B6: 5D-BA-C5-C4-00
2023/11/19 21:06:05: Error writing HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:06:05: Error writing HotKey to HID 19B6 device: Can't write to this device.

**Comment by seerge** [comment]
@123dqwkhjk if this build won't work - I'm out of ideas.

Your device is absolutely horrible in terms of implementation. 
As ``GA503`` is the only model of all asus devices for all years, that requires special unique brightness control.

[GHelper.zip](https://github.com/seerge/g-helper/files/13403275/GHelper.zip)

**Comment by 123dqwkhjk** [comment]
still not working sir. :(
Would you mind that let g15 users use the old method? Or is there anyway that I can help you?

**Comment by seerge** [comment]
@123dqwkhjk I can't restore old method, as whole thing was reworked in order to make new Aura modes possible and speed things up

Try this build, it will simply write needed payload to all possible asus USB devices
[GHelper.zip](https://github.com/seerge/g-helper/files/13403308/GHelper.zip)

**Comment by 123dqwkhjk** [comment]
2023/11/19 21:32:38: App launched: ROG Zephyrus G15 GA503RM_GA503RM :0.133.0.0zh-TW
2023/11/19 21:32:38: dGPU not found
2023/11/19 21:32:39: CPU: 8 - AMD Ryzen 7 6800HS with Radeon Graphics          - AMD64 Family 25 Model 68 Stepping 1
2023/11/19 21:32:39: AutoSetting for Online
2023/11/19 21:32:39: Input: \\?\hid#vid_0b05&pid_19b6&col05#7&2635b6bc&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/11/19 21:32:39: Mode = 2 : OK
2023/11/19 21:32:39: Clocks: Eco
2023/11/19 21:32:39: Eco flag : 1
2023/11/19 21:32:39: Mux flag : 1
2023/11/19 21:32:39: \\?\DISPLAY#CMN1540#5&2b412772&2&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/11/19 21:32:39: \\?\DISPLAY#CMN1540#5&2b412772&2&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/11/19 21:32:39: Screen = 165Hz : OK
2023/11/19 21:32:39: ScreenOverdrive = 0 : OK
2023/11/19 21:32:39: BatteryLimit = 60 : OK
2023/11/19 21:32:39: BatteryLimit = 60 : OK
2023/11/19 21:32:39: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
2023/11/19 21:32:39: USB 19B6: 5D-B3-00-00-FF-00-00-EB-00-00-FF-FF-FF-00-00-00-00
2023/11/19 21:32:39: USB 19B6: 5D-B4
2023/11/19 21:32:39: USB 19B6: 5D-B5-00-00-00
2023/11/19 21:32:39: USB 19B6: 5D-B9
2023/11/19 21:32:39: USB 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2023/11/19 21:32:39: USB 19B6: 5D-05-20-31-00-1A
2023/11/19 21:32:39: Error writing USB to HID device: Operation failed early: 參數錯誤。
2023/11/19 21:32:39: Monitor Power On
2023/11/19 21:32:40: Auto 19B6: 5D-BA-C5-C4-00
2023/11/19 21:32:40: Error writing Auto to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:40: Error writing feature Auto to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:40: Error writing Auto to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:40: Error writing feature Auto to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:40: Error writing Auto to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:40: Error writing feature Auto to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:40: Error writing Auto to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:40: Error writing feature Auto to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:41: PowerLimit C0 = 5 : OK
2023/11/19 21:32:41: PowerLimit C2 = 87 : OK
2023/11/19 21:32:41: Latest version 0.133.0.0
2023/11/19 21:32:42: Key: 197
2023/11/19 21:32:42: HotKey 19B6: 5D-BA-C5-C4-00
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:42: Key: 197
2023/11/19 21:32:42: HotKey 19B6: 5D-BA-C5-C4-00
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:42: Key: 197
2023/11/19 21:32:42: HotKey 19B6: 5D-BA-C5-C4-00
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:42: Key: 196
2023/11/19 21:32:42: HotKey 19B6: 5D-BA-C5-C4-01
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:42: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:42: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Key: 196
2023/11/19 21:32:43: HotKey 19B6: 5D-BA-C5-C4-02
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Key: 196
2023/11/19 21:32:43: HotKey 19B6: 5D-BA-C5-C4-03
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Key: 197
2023/11/19 21:32:43: HotKey 19B6: 5D-BA-C5-C4-02
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Key: 197
2023/11/19 21:32:43: HotKey 19B6: 5D-BA-C5-C4-01
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Key: 197
2023/11/19 21:32:43: HotKey 19B6: 5D-BA-C5-C4-00
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:43: Error writing HotKey to HID 19B6 device: Operation failed early: 功能錯誤。
2023/11/19 21:32:43: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:44: Error writing HotKey to HID 19B6 device: Can't write to this device.
2023/11/19 21:32:44: Error writing feature HotKey to HID 19B6 device: SetFeature failed.
2023/11/19 21:32:45: Design Capacity: 90006mWh, Full Charge Capacity: 87230mWh, Health: 0.9691576117147745705841832767%
2023/11/19 21:32:46: Varibright: 1,2
2023/11/19 21:32:46: Hibernate after 2147483647
p.s. "功能錯誤" means some functions not working.

**Comment by seerge** [comment]
@123dqwkhjk try this one 
[GHelper.zip](https://github.com/seerge/g-helper/files/13403402/GHelper.zip)

**Comment by 123dqwkhjk** [comment]
[log.txt](https://github.com/seerge/g-helper/files/13403420/log.txt)
<img width="696" alt="image" src="https://github.com/seerge/g-helper/assets/130690113/0ef87b8d-1776-4401-9dd4-5adaeedf17e5">
not working

**Comment by seerge** [comment]
@123dqwkhjk try another one
[GHelper.zip](https://github.com/seerge/g-helper/files/13403435/GHelper.zip)

**Comment by 123dqwkhjk** [comment]
it is working now great

**Comment by seerge** [comment]
@123dqwkhjk does this one STILL work ?
[GHelper.zip](https://github.com/seerge/g-helper/files/13403454/GHelper.zip)

**Comment by 123dqwkhjk** [comment]
work like a charm!!!

**Comment by seerge** [comment]
Ok, closing as completed then
