### ISSUE TITLE
keyboard backlight not working

### ISSUE THREAD

**Issue by 123dqwkhjk** [seerge/g-helper#1617]
**Describe the bug**

keyboard backlight is not working

**Clear scenario to Reproduce**

1.use fn+f2/f3

**Expected behavior**

keboard backlight should turn on

**App Logs**

[log.txt](https://github.com/seerge/g-helper/files/13403121/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11  22631.2715
 - Laptop model ga503rm

**Comment by seerge** [comment]
@123dqwkhjk I have already answered you in duplicate issue https://github.com/seerge/g-helper/issues/1616 

Please check build there
