### ISSUE TITLE
Screen brightness is not restored to the previous state after resuming from hibernation

### ISSUE THREAD

**Issue by Henning742** [seerge/g-helper#1618]
**Describe the bug**
Screen brightness is not restored to the previous state after resuming from hibernation

**Clear scenario to Reproduce**
(All operations done with `Fn+F7, F8`)
1. Set the screen brightness to the lowest.
2. Hibernate.
3. Wake up the laptop, the screen is brighter than normal.
4. Try to `Fn+F7`, the brightness status bar appears and shows it's already at the lowest, so it won't change the brightness.
5. Try to `Fn+F8`, the brightness status bar appears and shows it's now at the 2nd lowest value. The screen brightness is set to the according value successfully.

**Expected behavior**
The screen brightness should stay at the lowest value after resuming from hibernation.

**App Logs**
https://pastebin.com/nBW659WX

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: Strix 16

**Asus software**
- MyASUS installed
- Asus services running in background: No.

**Comment by seerge** [comment]
@Henning742 hello 

G-Helper is not handling your brightness anyhow. Windows does.

It just offers hotkeys (same as native asus service) to send commands to windows to increase / decrease brightness.

So I would advice to look into windows brightness settings (automatic brightness?), power plan settings, mb even reset it completely  with ``powercfg -restoredefaultschemes`` ? :)
