### ISSUE TITLE
{Feature Request] Detect whether laptop is 2020/2021/2022 and only display aura keyboard backlighting options available to each system.

### ISSUE THREAD

**Issue by fiifichristian** [seerge/g-helper#162]
I think it would be cool if only lighting options that are available for the system could be picked. For example, I have a 2021 G14 which only has white backlighting and 3 backlighting options (static, breathe and strobe). However, I also have rainbow and color cycle which I assume is for the 2022 version and I can't use. Thanks!

**Comment by seerge** [comment]
Hello, @fiifichristian  do 2021 and 2020 have same (i.e. white only) backlight?

**Comment by TomBonnot** [comment]
yes, only 2022 have colors, 2021 and 2020 are white only

**Comment by ke1ne** [comment]
> Hello, @fiifichristian do 2021 and 2020 have same (i.e. white only) backlight?

G15 2021 (ga503qr) has colors available for keyboard backlight

**Comment by fiifichristian** [comment]
> Hello, @fiifichristian do 2021 and 2020 have same (i.e. white only) backlight?

As far as I'm aware, for G14s, 2020 and 2021 have identical white keyboard backlighting as well as the 2020 and 2021 G15s (I think but I'm less experienced with G15s so I'm not too sure) with the 2022 variants of both having the multicoloured options.

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11105823/GHelper.zip)

I have added a switch that will remove unsupported modes for models containing "401" (i.e. 2020/2021). That should do a thing.

**Comment by theo-j22** [comment]
I have G15 2021 GA503QM, only has white backlight. I will last 2 letters define in this series if it has color or not!? I can be wrong.

**Comment by marcelomijas** [comment]
> [GHelper.zip](https://github.com/seerge/g-helper/files/11105823/GHelper.zip)
> 
> I have added a switch that will remove unsupported modes for models containing "401" (i.e. 2020/2021). That should do a thing.

Where is the switch? I am still seeing the options (GA401IV).

**Comment by seerge** [comment]
@marcelomijas in the code, you just shouldn’t see rainbow and color cycle options in a dropdown :)

**Comment by marcelomijas** [comment]
Oh, sorry then @seerge . I was also expecting to not see Static/Breathe/Strobe and color options anymore since they do nothing to my model. :)

**Comment by seerge** [comment]
@marcelomijas even Strobe/Breathe do nothing ? I.e. white color doesn't "flash" ?

**Comment by marcelomijas** [comment]
@seerge No, it's always static, whatever the option. I didn't have that options either in AC, the 2020 models only have 4 keyboard light states by default, and they are all static: off, on-low, on-med, on-high.

**Comment by seerge** [comment]
@marcelomijas ok, clear :) well for now I will remove only color-related options, to not to mess with other models
Changes are live in https://github.com/seerge/g-helper/releases/tag/v0.43 .

Closing as solved
