### ISSUE TITLE
Package with scoop

### ISSUE THREAD

**Issue by Arakhor** [seerge/g-helper#1621]
And/or winget/choco, but scoop seems like an ideal candidate.

**Comment by kxxoling** [comment]
@seerge And also many people even don't know what GitHub is. Do you mind if we have a pull request to add automatic winget release hook or someone commits this to WinGet repository?

**Comment by seerge** [comment]
@kxxoling  many don't know what github is, but it's first link in google for "g-helper" or "ghelper" :) (+ they hear about app from reddit / etc)

And if app will be in winget it won't promote it anyhow :| 

I can add it there, but my point is that it won't change much

**Comment by kxxoling** [comment]
In my personal experience, people who knows g-helper and prefer it than the pre-installed Aura will have more intend to use/try WinGet which is distributed with Windows 11. And I'd like to help with automate WinGet releasing.

**Comment by squee666** [comment]
also going for a straight up install means that more people will miss vital steps on the github page explaining stuff like properly disabling armoury crate and the uninstaller linked also how to change values , that and its requirements to work in first place.

ghelper is pretty basic just extract put folder in c drive start it and never touch again

**Comment by seerge** [comment]
@squee666 yeah, agree :) that's also important

**Comment by nopeless** [comment]
Same opinion here, the majority of the users will not see benefit and definitely not worth his time. I would appreciate winget installation if it is supported though (over choco or scoop). If you ever need help with this, I'm willing to set up CI and testing for it.

**Comment by Elkiwa** [comment]
@Arakhor Someone already requested on the scoop side : [Issue link](https://github.com/ScoopInstaller/Extras/issues/11306)
The effort was already made, but it probably won't be merged in the near future! If you already know github and `scoop` command well enough, then you can install it.

**Comment by seerge** [comment]
Closing this for now then, as I won't be adding it by myself, and if someone will do a PR - i will check it :)

**Comment by bshor** [comment]
This is on Chocolatey -- but when I install it, I don't see the icon.

[https://community.chocolatey.org/packages/g-helper](https://community.chocolatey.org/packages/g-helper)

It's also on Scoop, and it does seem to work.

https://scoop.sh/#/apps?q=g-helper

**Comment by seerge** [comment]
@bshor hello, i have no relation neither to chocolatey nor to scoop. Why don't you just download actual release from github or official website and run ?

**Comment by bshor** [comment]
Thanks for creating this awesome utility! Coming from the Linux world, I like the package manager paradigm, which is now becoming a bigger deal in Windows. chocolatey was the classic one, then winget, and now scoop.

Easiest selling point is programs update automatically!

And of course the packagers don't have to be the authors. I don't know who packaged it for scoop, but someone did, and it works great.
