### ISSUE TITLE
Ghelper v0.134, Flow Z13 keyboard lighting again

### ISSUE THREAD

**Issue by UnknownLOL** [seerge/g-helper#1622]
Looks like v0.134 breaks keyboard lighting controls for my ROG Flow Z13 once more =)
If I roll back to v.0131 it works. If I then upgrade to v0.134 it works until shut down. After that it doesn't work again.

1. Update GHelper to v0.134

**Expected behavior**
Lighting should remain under control)

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13415511/log.txt)

Windows 11 latest
ROG Flow Z13 GZ301ZE
Asus software uninstalled
0 Asus processes running

**Comment by seerge** [comment]
@UnknownLOL but 0.134 literally includes all the changes i did for you in https://github.com/seerge/g-helper/issues/1616

And from the log i see that it sees USB devices and sends commands as it should

```
11/20/2023 4:38:27 PM: USB 18C6: 5D-BD-01-CF-1E-BB-BB-FF
11/20/2023 4:38:27 PM: USB 1A30: 5D-BD-01-CF-1E-BB-BB-FF
11/20/2023 4:38:27 PM: USB 18C6: 5D-B3-00-02-FF-FF-FF-E1-00-00-FF-FF-FF-00-00-00-00
11/20/2023 4:38:27 PM: USB 18C6: 5D-B4
11/20/2023 4:38:27 PM: USB 18C6: 5D-B5-00-00-00
11/20/2023 4:38:27 PM: USB 1A30: 5D-B3-00-02-FF-FF-FF-E1-00-00-FF-FF-FF-00-00-00-00
11/20/2023 4:38:27 PM: USB 1A30: 5D-B4
11/20/2023 4:38:27 PM: USB 1A30: 5D-B5-00-00-00
11/20/2023 4:38:27 PM: USB 18C6: 5D-B9
11/20/2023 4:38:27 PM: USB 18C6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
11/20/2023 4:38:27 PM: USB 18C6: 5D-05-20-31-00-1A
```

**Comment by UnknownLOL** [comment]
@seerge 
Tried switching from 0.134 to yesterday's build - lighting control doesn't work. 
Switched from that to 0.131 - lighting works. 
Switched to 0.134 - it works. 
Shut down computer - it stops working (remains stuck with highest brightness).

**Comment by seerge** [comment]
@UnknownLOL so it looks like yesterday's changes didn't help you, correct ?

Can you try to change brightness up / down (with hotkeys for example) and check what it writes to the log when you do that and post here ?

**Comment by UnknownLOL** [comment]
@seerge 
Hm, all keyboard shortcuts (except volume up \ down and mute) don't work after shut down as well. Brightness (Fn + F11) doesn't work either.
Here's my log after moving slider.
[log.txt](https://github.com/seerge/g-helper/files/13415991/log.txt)

It looks like something fails to reestablish controls over keyboard functions (lighting and hotkeys) after system shut down in particular.

**Comment by UnknownLOL** [comment]
It is both backlight and hotkeys)

New build seems to work... I'm going to shut down pc and let it chill for some time, then start it up and we'll see what happens.

**Comment by seerge** [comment]
@UnknownLOL if hotkeys don't work, of course they won't control backlight. That's why I have asked  if slider in extra works or not :)

**Comment by UnknownLOL** [comment]
@seerge 
Ok, Hotkeys work now after shut down but backlight still doesn't. 
The thing is - Fn+F11 displays keyboard brightness switch but actual brightness is not changed. The same is with the slider in extra.
Here's the log
[log.txt](https://github.com/seerge/g-helper/files/13417023/log.txt)

**Comment by seerge** [comment]
@UnknownLOL well, it's strange cause app detects and sends payload for brightness. And to 2(!) devices in your computer (it sends to all that identify themselves as aura)

```
11/20/2023 7:00:41 PM: Key: 199
11/20/2023 7:00:41 PM: HotKey 18C6: 5D-BA-C5-C4-03
11/20/2023 7:00:41 PM: HotKey 1A30: 5D-BA-C5-C4-03
```

If you run v.0131 instead of 0.134, do you immediately become able to control backlight brightness ?

**Comment by seerge** [comment]
@UnknownLOL I have only 1 idea that you can try, check this build

[GHelper.zip](https://github.com/seerge/g-helper/files/13418776/GHelper.zip)

**Comment by UnknownLOL** [comment]
@seerge 
This new build immediatly works, and seems to work fine after shut down as well. For now atleast)

About 2 aura devices, that may be because Z13 has back window which is also RGB. Or maybe it's key remapping software (I have ReWASD and Autohotkey, though both should be inactive during my testing) duplicates devices to simulate key presses.

**Comment by seerge** [comment]
@UnknownLOL ok, good to know. I have pushed this changes to existing 0.134 (and re-uploaded it with a fix)
