### ISSUE TITLE
Search for app in the store?!

### ISSUE THREAD

**Issue by mrunknown9999** [seerge/g-helper#1623]
I have a Flow X13 2023, and was using g-helper version 0.131 without any issue, but after I did a fresh reinstall of windows, running any version higher than 0.129 (which works ok) i get the following issue. Btw I have the .NET runtime 7.0.14 x64. What am I missing?

![Screenshot 2023-11-21 153319](https://github.com/seerge/g-helper/assets/128497652/43b63bd0-e078-44ff-adcc-a3efd997e7dd)

Thanks!

**Comment by seerge** [comment]
@mrunknown9999 hello, it's your windows defender acting. You need to unblock exe
https://github.com/seerge/g-helper/discussions/778
