### ISSUE TITLE
High Battery Usage

### ISSUE THREAD

**Issue by Evatriae** [seerge/g-helper#1624]
**Describe the bug**
The power limit I set for the CPU is 10W, using the silent fan curves preset with Best Power Efficiency and disabled CPU Boost. GPU is set to Eco, Screen is set to 60Hz and half-brightness, laptop keyboard set to lowest brightness. The power consumption shows a constant ~38W or higher when, at least a few weeks ago, it would've been at ~15W. I have no idea what could be consuming power. Task Manager CPU Usage is at ~3%, Memory at ~18%, power usage of processes at low or very low.

I've used the offline scan option on Windows Defender, didn't turn up anything.

I don't know if or how this can be reproduced.

**App Logs**

[log.txt](https://github.com/seerge/g-helper/files/13428776/log.txt)

**Screenshots or screencasts**

![Screenshot (9)](https://github.com/seerge/g-helper/assets/141985729/8a815591-5385-41f8-9ee0-4343dc4a09db)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ASUS TUF Dash F15 FX517ZR_FX517ZR

**Asus software**
- MyASUS installed

**Additional context**

**Comment by seerge** [comment]
@Evatriae hello,

It's most probably that BIOS has failed to turn off dGPU (but reports that it's off afterwards, while it's not)

```
22/11/2023 12:13:31 am: Running eco command 1
22/11/2023 12:13:46 am: GPUEco = 1 : 0
22/11/2023 12:13:46 am: Eco flag : 1
22/11/2023 12:13:46 am: Mux flag : 1
```

I would recommend to restart and turn dGPU on and off again, to make sure that it's indeed disabled (you can double check in device manager)

There is nothing i can "fix" here :) some models have issues and can act sometimes.

Alternatively you may want to completely reinstall nvidia drivers using [DDU](https://www.guru3d.com/download/display-driver-uninstaller-download/), they can be locking GPU and preventing it from being disabled
