### ISSUE TITLE
2022 Strix G17 - 0.134 Ambient & Heatmap issue.

### ISSUE THREAD

**Issue by Constrat** [seerge/g-helper#1625]
**Describe the bug**
0.132 and 0.133 Heatmap & Ambient light mode, light the entire keyboard up.
With 0.134 they will not light up the `numpad`, the `<>`. 
Probably related: the same issue happens with OpenRGB when the layout is not correctly identified (15'' vs 17'' have different layouts because of numpad presence)

**Clear scenario to Reproduce**
1. Go to Laptop Keyboard
2. Choose Ambient or Hetmap
3. Parts of the keyboard will not light up.

**Expected behavior**
Entire keyboard should light up.

**App Logs**
log has the light up actions for the 3 different version. I noticed that for 0.134 an error is shown:
`21/11/23 20:45:25: Error writing USB: Operation failed early: The parameter is incorrect. `
[log.txt](https://github.com/seerge/g-helper/files/13430414/log.txt)

**Screenshots or screencasts**
![IMG_20231121_205147](https://github.com/seerge/g-helper/assets/56174894/e76b9c76-946c-4cc5-8a7f-c0c1558ed7c4)
_Image looks ugly my bad_

**Desktop (please complete the following information):**
 - OS: Win11 Enterprise
 - ROG Strix G17 `G713RW`

**Asus software**
Completely free from Asus Bloat (Thank you Seerge)

**Comment by seerge** [comment]
@Constrat does your laptop has per-key RGB or with zones ? if with zones try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/13430609/GHelper.zip)

**Comment by Constrat** [comment]
Only the lightbar lights up.
This laptop has per-key coloring possible if that's what you mean.

**Comment by seerge** [comment]
@Constrat then i'm inviting you to participate :) instead of blindly sending colors to all possible (and impossible) hotkeys i took per-key implementation from openrgb (so no wonder you have same experience as there)

This is array with addresses of each key in the payload
https://github.com/seerge/g-helper/blob/22bfc77a7a13ae9d07b6184ab05e911d5785624c/app/USB/Aura.cs#L362

I have tried to fill in gaps with assumed num-lock buttons (but i have no idea if they are correct)
You can try this build and check which buttons light up

[GHelper.zip](https://github.com/seerge/g-helper/files/13431262/GHelper.zip)

**Comment by Constrat** [comment]
But we're there any big changes between 0.133 and 0.134? Because it was working properly before.
Also. The ORGB fork is still unmerged (with the 17'' fixes)

**Comment by seerge** [comment]
@Constrat yes, for 0.134 I have added proper per-key mapping for RGB *check discussion) https://github.com/seerge/g-helper/pull/1582 before it was just setting same color to all possible addresses (which was making proper ambient with multiple zones impossible)

Does build that I have linked here light up some of numpad keys ?

**Comment by Constrat** [comment]
You'll have to wait tomorrow morning / lunch, because I've already turned off everything as I'm about to go to bed. Tmr in uni I think I have 1 hour free. I should be able to give you everything/ test the key values

**Comment by Constrat** [comment]
Ok so most of the numpad now lights up (<> 0 num and . num are still missing) also the 1 num and ctrl don't seem to be in the correct place.
I'll see what I can do with https://github.com/seerge/g-helper/blob/main/app/USB/Aura.cs#L362
is this update to the .zip you passed me?

**Comment by seerge** [comment]
@Constrat then i guessed in more-or-less right direction. Don't forget second array 

https://github.com/seerge/g-helper/blob/main/app/USB/Aura.cs#L397

that marks which zone (i..e color) should new keys represent. It should be 3 (last 4th zone). So when you add a new key - you need to add it to both arrays in same position :)

**Comment by Constrat** [comment]
So for example the `NUM1` that has the "wrong" color just needs to be changed zone?
Thank you for the input :)

**Comment by seerge** [comment]
@Constrat only if numpad 1 key is identified correctly :)

**Comment by Constrat** [comment]
I'm making it work :) this is so cool, seeing the keys light up based on the numbers.

**Comment by Constrat** [comment]
@seerge I think I fixed everything. I only have one question: zone 4, 5, 6, 7 are for the bottom half of the screen and should be used in the lightbar. 
Bottom - Left is 5
Bottom - Left middle is half 4 half 5 (seems like)
Bottom - middle is 6
Bottom - right middle is half 6 half 7 (seems like)
Bottm - Right is half 6 half 7 again.

4 and 5 seem to be working as expected. 6 could be the ONLY middle zone but somehow it reaches all the way to the bottom far right, I don't think this is supposed to happen.

**Comment by seerge** [comment]
@Constrat yes, 0-1-2-3 are keyboard zones, 4-5-6-7 are lightbar zones

**Comment by Constrat** [comment]
Where are the screen zone defined? Zone 6 seems too big compared to the others

**Comment by Constrat** [comment]
fix with [8bcac73](https://github.com/seerge/g-helper/commit/8bcac73824c7f3ffe7c6ce4fe42f0c142d210746) (#1636)

**Comment by seerge** [comment]
@Constrat great!
