### ISSUE TITLE
ROG Strix G15 doesn't apply most of the RGB keyboard modes

### ISSUE THREAD

**Issue by H1m4ru** [seerge/g-helper#1627]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**
I noticed that around 90% of the RGB keyboard modes included on G-Helper doesn't work at all.
I thought that was a matter of my laptop being a old 2021 model or something, but after installing the old Aura Sync app, i noticed that all of the features were supposed to work perfectly fine, and that G-Helper is missing a bunch of other modes, like Music Sync and Glowing Yoyo.

The modes that doesn't work are:
- Star
- Rain
- Ripple
- Highlight
- Laser
- Comet (works on Aura Sync)
- Flash (renamed as Flash and Dash on Aura Sync, also works)

**Clear scenario to Reproduce**
1. Install the old Aura Utility on ASUS' website.
2. Open it and turn it on.
3. Check all the RGB modes.
4. Compare it with G-Helper's same feature.

**Expected behavior**

I expected all the features to work properly, and having way more options and customization than Aura Sync provides, also recognizing which modes doesn't work with my laptop.

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/13432155/log.txt)

**Screenshots or screencasts**

https://github.com/seerge/g-helper/assets/103531824/f8c69ec4-f8d2-45f1-a0fb-f850a4b6ab73

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Laptop model: ROG Strix G15 G513IE-R74BRTSPS2

**Asus software**
- Only the old Aura Sync application.

**Additional context**
Nah.

**Comment by seerge** [comment]
@H1m4ru your device simply don't support them

I have added your model to the list of devices that has limited RGB support, and you won't see those options anymore
[GHelper.zip](https://github.com/seerge/g-helper/files/13435938/GHelper.zip)

**Comment by H1m4ru** [comment]
> @H1m4ru your device simply don't support them
> 
> I have added your model to the list of devices that has limited RGB support, and you won't see those options anymore [GHelper.zip](https://github.com/seerge/g-helper/files/13435938/GHelper.zip)

Hi! Thanks so much for that fix!
Just wondering if you can activate the other RGB modes that are available in Aura Sync app in a possible future.
And also i noticed two new modes (Ambient and GPU Mode). What they exactly does?

**Comment by seerge** [comment]
@H1m4ru they need to be supported by hardware :) i assume your device doesn't have per-key rgb at all. 

Ambient colors keyboard into current main screen colors, GPU just sets keyboard proportionally to current GPU mode (i.e. green for eco, red for ultimate, etc)

**Comment by H1m4ru** [comment]
> @H1m4ru they need to be supported by hardware :) i assume your device doesn't have per-key rgb at all.
> 
> Ambient colors keyboard into current main screen colors, GPU just sets keyboard proportionally to current GPU mode (i.e. green for eco, red for ultimate, etc)

Well, i have some specific modes that actually works only on Aura Sync, like Starry-Night, Glowing Yoyo, Comet, Flash and Dash and Wave, and these effects aren't per-key based at all.
Btw, thanks for the explanation!

**Comment by SAJT500** [comment]
Hello @seerge ! I have the same issue too! 

Can you add my laptop model  Asus ROG STRIX G513QC-HN1135T  to the list of devices that has limited RGB support? 

Thanks if you can help
