### ISSUE TITLE
다운로드 하여도 인식불가

### ISSUE THREAD

**Issue by HIKARISWET** [seerge/g-helper#1629]
![KakaoTalk_20231122_054024400](https://github.com/seerge/g-helper/assets/151703635/ed9af0d5-d10d-4113-aa8f-e16750e907b6)

.net desktkop runtime을 다운로드 하여도 작동하지않는문제

**Comment by seerge** [comment]
@HIKARISWET hello. Then it's damaged or not seen by windows by some reason.

Try to uninstall it and download / reinstall again :) 

Good luck

**Comment by HIKARISWET** [comment]
제거후 다운로드/재설치 하였습니다
재부팅도 많이 했습니다
G helper를 사용하다 문제가 생겨, 윈도우 복구를 한 후 재다운로드하였지만 저런 에러가뜨며 다운로드가 되지않습니다.
이런 경우는 어떤것인가요?

**Comment by seerge** [comment]
I don't know :) but it's clearly something wrong with the system/.net in your case.

I would advice to tinker with the setup more.

**Comment by HIKARISWET** [comment]
나는 .net desktop driver의 다운로드 링크를 원합니다.
사진의 에러 의 YES를 눌러도 다운로드가 되지않습니다

**Comment by seerge** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.404-windows-x64-installer
