### ISSUE TITLE
M16 2022 GPU Eco issue

### ISSUE THREAD

**Issue by ohmin1** [seerge/g-helper#163]
i think the GPU eco mode doesnt work well in M16(maybe in all intel laptops). and when can intel laptop support this app perfectly?

**Comment by seerge** [comment]
What happens when you click Eco ?

**Comment by ohmin1** [comment]
it change to standard again but dGPU turns off.

**Comment by ohmin1** [comment]
yeah it worked well in armoury but not on this.

it disappear but in program it is on standard.

**Comment by seerge** [comment]
Wait, if you "try" eco in g-helper (button goes back to standard, that's i understand) but it disappears in device manager ? so actually it rusn off?

**Comment by ohmin1** [comment]
yes exactly
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/129293725/228562216-c5bdb0b2-4488-4a7d-a56c-75cdf2d377df.png">

**Comment by seerge** [comment]
Ok, so it works ! just when app checks if status has changed - bios seem to report a wrong value.

Can you open powershell as admin and run following command there

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DSTS(0x00090020)

``` ?

**Comment by ohmin1** [comment]
yeah i did

**Comment by seerge** [comment]
Well, i need an output of that command 😄 ...

**Comment by ohmin1** [comment]
ah ok wait

**Comment by ohmin1** [comment]
__GENUS          : 2
__CLASS          : __PARAMETERS
__SUPERCLASS     :
__DYNASTY        : __PARAMETERS
__RELPATH        :
__PROPERTY_COUNT : 1
__DERIVATION     : {}
__SERVER         :
__NAMESPACE      :
__PATH           :
device_status    : 65537
PSComputerName   :

**Comment by seerge** [comment]
Actually, reading says that dGPU is disabled. May be (by some reason) it doesn't update immediately in your case after switch (so app things it didn't work).

Can you check this build ?

[GHelper.zip](https://github.com/seerge/g-helper/files/11101949/GHelper.zip)

**Comment by ohmin1** [comment]
i think it doesnt work...

**Comment by seerge** [comment]
What happens when you launch re-launch app ? does it show ECO mode selected?

**Comment by ohmin1** [comment]
no same as original

**Comment by seerge** [comment]
Ok, great. I just updated 0.42 with this fix https://github.com/seerge/g-helper/releases/tag/v0.42 (you can re-download it there or keep using zip from this thread).

I'm closing this as solved
