### ISSUE TITLE
FN+F6 key screen issue on ASUS TUF Gaming F15 FX506HF

### ISSUE THREAD

**Issue by laminaung96** [seerge/g-helper#1632]
OS: Windows 11 Home Single Language
Laptop model: ASUS TUF Gaming F15 FX506HF

Asus software
Armoury Crate is NOT installed
MyASUS is NOT installed
ALL Other Asus services is NOT running in background

Dear GHelper Team,

Firstly, I would like to express my appreciation for this application as an alternative to Armoury Crate. I am currently using it and found a bug on my ASUS TUF Gaming F15 FX506HF laptop. 

The FN+F6 key combination, which is use to turn off the screen and keyboard backlight, is causing an issue.

When I use Ghelper and press FN+F6, the screen and keyboard do turn off. However, when I attempt to turn them back on by pressing keys on keyboard, the screen starts flickering with a black screen, and the keyboard light also flickers. Like when I press the key, the screen turns on, then goes black, also same for keyboard light. Then I need to press the power button to restart. 

I closed the Ghelper application and press FN+F6, then the key won't do anything, like nothing happened. 

I just wanna clarify is this bug from Ghelper or is it something wrong with my laptop since I bought it recently T_T .

Best Regards,

**Comment by seerge** [comment]
@laminaung96 hello, 

There only one way to "turn off" screen via windows API, and app uses that already :) this is the same action in windows if you would quickly press power button (windows turns off laptop screen and then eventually goes to sleep)

It looks more like windows is acting :)

What happens if you start asus services (via ``Extra`` menu) and just press Fn+F6 there (w/o g-helper running) ?

**Comment by laminaung96** [comment]
Hi Seerge,

I did like you said, start asus services and try FN+F6 , the screen works normally. 

Actually I don't really need to use that fn+f6 key anyway. When I just saw that my screen flickering, I thought my laptop might has an error and I just wanna know the root cause. Thank u :D

Now I stopped asus services again and use ghelper again.

**Comment by laminaung96** [comment]
Yeah, like I mentioned, I don't have to use Fn+F6, so it's not a problem at all. I appreciate your response, and keep up the good work. Thank you !!

**Comment by seerge** [comment]
Ok, then i'm just closing this
