### ISSUE TITLE
Remove github fail-safe - it is interfering with crash diagnosis

### ISSUE THREAD

**Issue by YomamaNow** [seerge/g-helper#1633]
I have ASUS g14, the most sensitive, crashing, insanity-provoking laptop model perhaps in history, but in any case, it doesn't  help that Ghelper, perhaps in some false protective hope is returning the laptop to balanced from turbo and reducing the battery bar from max. I always keep mine on turbo. always battery power full. any problem with that I should know? Please remove this protective feature designed so that the system does not explode when rreturning from a blue screen error. thank you. and if you have any idea what's causing my crashes, that would really be something. often it's the balanced, because i have a power plug issue, where my laptop under its current setting cannot run on battery without crashing. the problem with balanced and not full power is the state is re-provoked.

what is this note down here? I'm known. g14 is known and famous I think by now. And thanks again. oh except, I do have to say AMD. everything is AMD, processor and graphics.

**Comment by seerge** [comment]
@YomamaNow I didn't get what you want to remove. App doesn't have any "fail safe" protection or so.

**Comment by YomamaNow** [comment]
what happens is if disconnected or bsod it goes back to balanced (I don't know which of these as the bsod is related to being off AC power), so I have to put it back on ultimate so my laptop works after returning.
