### ISSUE TITLE
API access for third party application

### ISSUE THREAD

**Issue by coffandro** [seerge/g-helper#1637]
**Is your feature request related to a problem? Please describe.**
On my laptop I often use programs which completely break in the most extreme manner possible if I change power mode while working. 
because of this I would like to make a few AHK scripts to watch the status of if the app is open, this is completely out of the scope of G-Helper in my opinion so I would like to request some sort of communication protocol to, for instance, change power mode or something like that automcatically

**Describe the solution you'd like**
I would like a feature kinda like the windows `Interprocess communication` so that the community would be able to extend G-Helper without bloating this beautiful application you've made

**Describe alternatives you've considered**
An alternative way would be to for instance allow hotkeys like F13 to do things inside G-Helper

**Additional context**
I have previously mentioned something similar in #357 but now I'm trying to explain it better

**Comment by seerge** [comment]
@coffandro hello,

It's not that easy to do. I simply can't add any CLI as whole app is designed to run in background, and act on certain events in the system (like plugging / unplugging power, pressing hotkey, etc). 

Same applies to external API.

If you want to re-use certain G-Helper's actions you can simply re-use code for your own solution :) main (and unique to asus) things are in https://github.com/seerge/g-helper/blob/main/app/AsusACPI.cs 

If you have more specific requests regarding hotkeys, that can be useful for a big range of people - i can consider them as well (even tho app already offers big amount of automatization) :)

**Comment by coffandro** [comment]
Well a hotkey for changing CPU mode could be quite useful

**Comment by seerge** [comment]
@coffandro if you mean performance modes - then it's ``Fn+F5 / Fn+Shift+F5`` or ``Ctrl+Shift+F5 / Ctrl+Alt+Shift+F5`` to change them forwards / backwards? :)

**Comment by coffandro** [comment]
Oh no I meant dgpu Vs egpu not performance modes

**Comment by seerge** [comment]
@coffandro there is no eGPU modes, if you mean XG Mobile toggle it's handled - it needs physical interaction anyway, so clicking on extra button in the app is not a big deal here.

As for enabling / disabling dGPU - it's already can be automated an called Optimized mode :)

**Comment by coffandro** [comment]
![image](https://github.com/seerge/g-helper/assets/75324436/7e68c4ec-2852-4511-8e42-db55362e26cb)
I was more thinking hotkeys for these two buttons.

Optimized mode doesn't work because of the reasons I mentioned, it changes on power mode and I need something more complicated than the default option, there for I would at least like the option to add a hotkey for that

**Comment by seerge** [comment]
@coffandro optimized mode doesn't change power modes :) it only turns dGPU on or off .

Can you explain your scenario why do you want to disable / enable dGPU so often if you don't unplug your laptop ?

**Comment by coffandro** [comment]
@seerge in all cases except for if I'm running the "creation kit" I want it to switch to the egpu when I unplug, if it is running the CK I want it to keep dgpu+egpu

**Comment by coffandro** [comment]
so if I the application is open I want it to be on DGPU while if it's closed I want it to be on optimized mode

**Comment by seerge** [comment]
@coffandro try this build 

``Ctrl+Shift+Alt+F14`` will set Eco mode
``Ctrl+Shift+Alt+F15`` will set Standard mode

[GHelper.zip](https://github.com/seerge/g-helper/files/13452441/GHelper.zip)

**Comment by coffandro** [comment]
That works perfectly!

**Comment by coffandro** [comment]
or not? it gives me a bluescreen if i switch it while having win 11 notepad open lol

**Comment by seerge** [comment]
Asus has implemented disabling and enabling GPU by literally powering it off :) thats one more reason i don’t encourage constant switching here

**Comment by seerge** [comment]
@coffandro alternatively you can just run as admin following thing in powershel

1 - to set eco, 0 - to set standard :)

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00090020, 1)

```

Results will be the same, cause this is same asus command that g-helper is using

**Comment by coffandro** [comment]
Thank you!
