### ISSUE TITLE
RPM not showing on TUF FX506

### ISSUE THREAD

**Issue by JackB111** [seerge/g-helper#164]
![image](https://user-images.githubusercontent.com/129295334/228546409-7d49f78c-a8b7-4cc7-ab2a-2492b0569647.png)

The RPM value appeared in Armoury Create. But it does not appear in G helper. What could be the reason, can it be fixed?

**Comment by seerge** [comment]
It could be that on your laptop endpoints are different (as it's quite old). I'm inviting you to participate in this topic https://github.com/seerge/g-helper/issues/38 and post your dump - then I can try to help :)

**Comment by seerge** [comment]
@JackB111 as a quick test - can you check this build tho ?
[GHelper (2).zip](https://github.com/seerge/g-helper/files/11101415/GHelper.2.zip)

**Comment by JackB111** [comment]
yes it is fixed even though it shows as a percentage, will this fix be added in future updates?
Or should I come and ask for a file every update?

**Comment by seerge** [comment]
@JackB111 - it's already live in https://github.com/seerge/g-helper/releases/tag/v0.42
You can click on fan label and it will switch to RPM and back to %

Marking this as solved
