### ISSUE TITLE
"Ambient" doesn't work well

### ISSUE THREAD

**Issue by Hari0s** [seerge/g-helper#1641]
in the version of GHelper v0.132 everything worked fine, now the keyboard is flickering, I sent you a video

https://github.com/seerge/g-helper/assets/32242189/386afb4f-dfd3-4f8b-b220-91d9f7f41401

**Comment by Hari0s** [comment]
now I have the GHelper version v0.134

**Comment by DLdota** [comment]
write your laptop model
need to add it to the IsStrixLimitedRGB function

**Comment by Hari0s** [comment]
everything worked well before
Model: G513QM

> write your laptop model need to add it to the IsStrixLimitedRGB function

**Comment by seerge** [comment]
@Hari0s try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/13452003/GHelper.zip)

**Comment by Hari0s** [comment]
> @Hari0sпопробуйте эту сборку
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/13452003/GHelper.zip)

Now even the previous backlights that did not work have disappeared, thank you!

**Comment by seerge** [comment]
@Hari0s does the Ambient mode work?

**Comment by Hari0s** [comment]
> @Hari0sрежим Ambient работает?

yes, yes, thanks!

**Comment by seerge** [comment]
@Hari0s ok, as for other "missing" modes, did they work for you in a first place ? You have a model with basic 4 zone RGB, and those modes usually don't work on such devices.

**Comment by Hari0s** [comment]
> @Hari0sок, а что касается других «отсутствующих» режимов, они у вас вообще работали? У вас модель с базовым 4-зонным RGB, и эти режимы обычно не работают на таких устройствах.

yes, they didn't work. They just didn't turn on. If I turned them on, then the previous mode worked, which worked.

**Comment by prakharb5** [comment]
On my Strix G15 (2022) G513RC (4 zone RGB), ambient mode flickers whenever the screen changes color. But it supports Aura Adaptive color pretty smoothly. Is there a way to fix the flickering?

**Comment by DLdota** [comment]
> On my Strix G15 (2022) G513RC (4 zone RGB): Ambient mode flickers whenever the screen changes color, but the colors change properly. But It supports Aura Adaptive color pretty smoothly. Is there a way to fix the flickering?

yes, ur model should be in IsStrixLimitedRGB function.

**Comment by seerge** [comment]
@prakharb5 try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/13675030/GHelper.zip)

**Comment by prakharb5** [comment]
> @prakharb5 try this build
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/13675030/GHelper.zip)

Thank you! This works perfectly well.

**Comment by prakharb5** [comment]
After using for a while, I must say, it runs more smoothly than Asus' implementation. Kudos to the dev!

**Comment by prakharb5** [comment]
Just noticed a small issue. Opening the window now makes it flicker white for a split second before loading😓 
https://github.com/seerge/g-helper/assets/51435948/b76cacf7-303c-44fe-9ca9-93514b75cfa1

**Comment by seerge** [comment]
@prakharb5 that's how winforms UI works for dark theme, how is it related to backlight ?

**Comment by prakharb5** [comment]
> how is it related to backlight ?

No, it was just something I noticed. Nevermind

**Comment by bourbonbourbon** [comment]
Ambient mode not working on G513RS and GPU Mode, and Heatmap also doesn't seem to work as nothing lights up.
Strobe, Rainbow, Color Cycle, Breathe, Static works

**Comment by andrey6060** [comment]
In my G18, numpad and some other buttons rgb not working in ambient mode (v137)

**Comment by seerge** [comment]
@Robertserpentain do you have per-key or 4-zone backlight on your device ?

**Comment by Robertserpentain** [comment]
I think it's 4-Zone and thank you very much

**Comment by bourbonbourbon** [comment]
Mine is per-key but ambient mode does not work.

**Comment by seerge** [comment]
@Robertserpentain try this build, I have added your model to the list with limited RGB
[GHelper.zip](https://github.com/seerge/g-helper/files/15324311/GHelper.zip)

**Comment by seerge** [comment]
@bourbonbourbon your case could be opposite. App assumes that your model has limited 4-zone RGB cause your model (G513RS) has that on most of the markets. 

If you have per-key RGB instead, you can enforce that by adding following line to the beginning of ``config.json`` (quit app before making edits)
```
"per_key_rgb": 1,
```

**Comment by Robertserpentain** [comment]
> @Robertserpentain try this build, I have added your model to the list with limited RGB [GHelper.zip](https://github.com/seerge/g-helper/files/15324311/GHelper.zip)

Perfect!! Thank you very much :)

**Comment by bourbonbourbon** [comment]
> @bourbonbourbon your case could be opposite. App assumes that your model has limited 4-zone RGB cause your model (G513RS) has that on most of the markets.
> 
> If you have per-key RGB instead, you can enforce that by adding following line to the beginning of `config.json` (quit app before making edits)
> 
> ```
> "per_key_rgb": 1,
> ```

Yes thank you it is working! But I see Lightbar and Logo as option under Laptop Backlight. I cannot control those
![image](https://github.com/seerge/g-helper/assets/109749723/d4824415-ef84-47b9-a85c-453c90dd1269)

**Comment by Robertserpentain** [comment]
> > @Robertserpentain try this build, I have added your model to the list with limited RGB [GHelper.zip](https://github.com/seerge/g-helper/files/15324311/GHelper.zip)
> 
> Perfect!! Thank you very much :) I've made you a small donation thanks again

Well, I'm also having problems with the logo now. I don't get the option to control it in Ghelper and it's fixed on blue but the keyboard and bar are working perfect :) thanks and sorry

**Comment by seerge** [comment]
@Robertserpentain this build should still show all checkbox columns as before, but still use 4-zone RGB for your model
[GHelper.zip](https://github.com/seerge/g-helper/files/15324709/GHelper.zip)

**Comment by seerge** [comment]
@bourbonbourbon cause full-zone backlight is linked with that UI :) just ignore those checkboxes.

**Comment by Robertserpentain** [comment]
> @Robertserpentain this build should still show all checkbox columns as before, but still use 4-zone RGB for your model [GHelper.zip](https://github.com/seerge/g-helper/files/15324709/GHelper.zip)

Perfect thank you very much :)

**Comment by seerge** [comment]
@bourbonbourbon actually, try this build. It should separate 4-zone RGB setting from those checkboxes

[GHelper.zip](https://github.com/seerge/g-helper/files/15324789/GHelper.zip)

**Comment by bourbonbourbon** [comment]
> @bourbonbourbon actually, try this build. It should separate 4-zone RGB setting from those checkboxes
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/15324789/GHelper.zip)

yes this works! thank you for implementing this!

**Comment by CURSED-PEARL** [comment]
Hi guys . my laptop dosent seem to work with ambient or heatmap . 
it's asus tuf f15 i5 11gen. 
it didn't work with aura . so by hardly finding a sol. i get your Ghelper at start it worked smooth but clashes with armory carate
so i dissabled armory carate . but some time later it stoped working so i reinstalled Ghelper and it worked for some time but after that reinstalling also not working .
please ignore grametical mistakes.

**Comment by CURSED-PEARL** [comment]
> Hi guys . My laptop dosen't seem to work with ambient or heatmap . It's asus tuf f15 i5 11gen. It didn't work with aura ' so by hardly finding a sol. I get your Ghelper at start it worked smooth but clashes with armory carate so i dissabled armory carate , but some time later it stoped working so I reinstalled Ghelper and it worked for some time but after that reinstalling also not working . Please ignore grametical mistakes.

umm Guys after stoping asus servises it started working fine . for now no problem . It's good to use . Thanks for making this.

**Comment by selfish-imp** [comment]
@seerge, hello! Similar problem, please help. My laptop: G713QM (4 RGB zones): ambient screen flickers.
