### ISSUE TITLE
Keyboard backlight on when unplugged

### ISSUE THREAD

**Issue by laminaung96** [seerge/g-helper#1642]
OS: Windows 11 Home Single Language
Laptop model: ASUS TUF Gaming F15 FX506HF

Asus software
Armoury Crate is NOT installed
MyASUS is NOT installed
ALL Other Asus services is NOT running in background

Hi Ghelper team,

I would like to know if there's an option for the keyboard backlight. I want to turn off the keyboard backlight when unplugged and have it on when the charger is plugged in. I saw an option in the extra settings, but it only sets a timeout for the backlight rather than turning it off completely on battery. When I type, the light comes on, and I want it to be completely off when unplugged to prevent battery drain. Appreciate if you could help, is there any way to do this? 

Best regards!

**Comment by seerge** [comment]
@laminaung96 hello, app remembers backlight brightness separately for plugged / battery cases.

Just set it once in each case, and it will switch

**Comment by laminaung96** [comment]
Hi Seerge,

Thanks for reply. But I try already in extra setting and it didn't switch automatically. T_T

**Comment by seerge** [comment]
@laminaung96 its not in Extra, app just remembers 2 brightness leveles
