### ISSUE TITLE
F2 key function (volume down) not working on Vivobook 14X

### ISSUE THREAD

**Issue by rumifloss** [seerge/g-helper#1644]
**Describe the bug**
Pressing Fn + F2 (or Volume down key) with or without Fn lock does nothing. Next key in sequence (Volume up / Fn + F3) works fine, so does Mute / Fn + F1 key

**Clear scenario to Reproduce**
1. Stop all Asus services via GHelper
2. Press Volume down key / Fn + F2

**Expected behavior**
Pressing Volume down / Fn + F2 lowers system volume

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Laptop model: Vivobook 14X K3405VF

**Asus software**
- Armoury Crate not installed
- MyASUS not installed
- Other Asus services running in background: no

[log_for_F2+modes.txt](https://github.com/seerge/g-helper/files/13459891/log_for_F2%2Bmodes.txt)

**Comment by seerge** [comment]
@rumifloss hello, volume up / down keys are not handled anyhow by the app. They just emit windows native volume commands directly on hardware level.

Did those keys work before for you ? :)

I see that app registers those keypresses inside. Do you have any custom actions set for M1/M2 (volume keys) under ``Extra``?

**Comment by rumifloss** [comment]
> I see that app registers those keypresses inside. Do you have any custom actions set for M1/M2 (volume keys) under `Extra`?
Thank you! For some reason my M1 key was mapped to something else. Changing it worked flawlessly. 

Out of curiosity, is there some way to know what keys the key binds translate to on a laptop like mine? I mean, how do you know M1 and M2 are F2 and F3 respectively for me?

**Comment by seerge** [comment]
M1/M2 are volume controls on ROG laptops :) so app can offer to rebind M1/M2 by simply catching volume hotkeys in windows and doing something else instead.
