### ISSUE TITLE
Implementing Full Speed mode from ProArt Creator Hub on Vivobook 14X

### ISSUE THREAD

**Issue by rumifloss** [seerge/g-helper#1645]
**Is your feature request related to a problem? Please describe.**
The Vivobook 14X has two sets of controls for CPU/fan modes. One of them is in the MyASUS app (which the Silent → Balanced → Turbo modes correspond to) and the other set is tucked away in the Armoury Crate–like ProArt Creator Hub (Whisper → Standard → Performance → Full Speed)

<img width="1440" alt="14X_ProArt_Modes" src="https://github.com/seerge/g-helper/assets/16689247/c301b7cd-bf65-4540-a364-869ecb98e3a4">

The first three modes in ProArt Creator Hub correspond 1:1 to the options in MyASUS. The fourth mode, Full Speed, seems to switch on fans permanently and changes the PBP of the processor to 65W, instead of 55W with the Performance/Turbo mode. There is a Notebookcheck review of the Vivobook 14X that lists the Creator Hub power modes of the i5-13500H as follows:

<img width="273" alt="14X_modes" src="https://github.com/seerge/g-helper/assets/16689247/f6c24e1e-0ade-479a-930f-637f9f60abd4">

Here are the CPU readings corresponding to the Performance mode and the Full Speed mode respectively:

<img width="1051" alt="PBP_GHelper_ProArt_Performance" src="https://github.com/seerge/g-helper/assets/16689247/32324f0d-1d1a-4955-84f4-02eb3dc2c099">

<img width="1073" alt="PBP_GHelper_ProArt_FullSpeed" src="https://github.com/seerge/g-helper/assets/16689247/a263f5c1-91df-4496-bbf5-e5721507dba2">

And here is a CPU reading of the Turbo mode in GHelper (55W, same as Performance in Creator Hub):

<img width="1259" alt="PBP_GHelper_Turbo" src="https://github.com/seerge/g-helper/assets/16689247/76ebd705-936f-4a55-8c60-21662373d8b6">

**Describe the solution you'd like**
It would be great to have a mode that corresponds to Full Speed inside GHelper, or maybe tweak the existing Turbo mode to change PBP to 65W instead of current cap 55W

**Additional context**
MyASUS is uninstalled. The ProArt Creator Hub controls only work with the Asus services enabled in GHelper

**Comment by seerge** [comment]
@rumifloss hello, you can already do that by adding a custom mode, and setting corresponding setting a config file

Check this comment for explanation https://github.com/seerge/g-helper/issues/1301#issuecomment-1715814968 :)
