### ISSUE TITLE
Fans fail to kick in when it should until restarted (issue only exists with G-helper)

### ISSUE THREAD

**Issue by Shuaib-S** [seerge/g-helper#1647]
**Describe the bug**
Upon reaching a CPU temp, or GPU temp, that exceeds that minimuc temprature required for the fans to turn on - my fans won't turn on. Only when the laptop is restarted will the fans kick back in. The issue will re-appear after the CPU/GPU tempratures reach a level where the fan is no longer required.

**Clear scenario to Reproduce**
1. Open an app that is heavy , thus increasing the temprature of the CPU (i.e a game)
2. The CPU temprature would rise  (for example 45 C to 80 C - this would mean the fans should now kick in)
3. The CPU would be at (as stated in the example) at 80 C but the fans at 0%/ 0rpm.
4. Restart the computer
5. The fans now kick in to the  appropiate rpm required.
6.  Upon the next time using the laptop the above steps would happen all over again thus meaning in order to use heavy apps ,  a restart is always needed.

**Expected behavior**
Fans to automatically turn on when reaching the CPU/GPU  tempratures 
**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13439995/log.txt)

**Screenshots or screencasts**
![Screenshot 2023-11-24 185616](https://github.com/seerge/g-helper/assets/149627329/54e65c72-df53-4456-a15a-bda1e7992021)
![Screenshot 2023-11-24 190302](https://github.com/seerge/g-helper/assets/149627329/05f1d049-a7df-41ae-9632-a225e606868d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model : Asus TUF F15 FX506HC ( RTX 3050, i5 11th gen)

**Asus software**
- Armoury Crate ( deleted the app but i still see its app data on file explorer )
- MyASUS installed

**Additional context**
It may seem not to be Ghelper related , but I believe it is as I decided to try deleting G-Helper and downloading armoury crate again. The issue did not exist ( fans turn on automatically). Upon re-dowloading G-Helper and deleting armoury crate the issue re-appears.

**Comment by seerge** [comment]
@Shuaib-S hello, G-Helper doesn't control your fans anyhow. They are controlled by firmware / BIOS and hardcoded for each mode individually.

If they behave like that - then this is how things are, you may try to do a hardware reset to install a bit older version of bios, may be that will help.

I can't change anything here

**Comment by Shuaib-S** [comment]
alright thank you. any suggestions?

**Comment by seerge** [comment]
@Shuaib-S suggestions are as I mentioned to try hardware reset or older bios.

My wild guess here, would be that if your laptop goes to sleep, and then wakes up - fans could be acting (and still thinking it's sleeping), as I remember other user with old TUF model had something similar before :)

**Comment by Shuaib-S** [comment]
Oh wow, your correect , the issue is with sleeping mode. Unfortunately the only fix i can seem to find is to keep it on dGPU (standard) which would practically make the iGPU useless and wear out my dGPU quicker.

**Comment by seerge** [comment]
dGPU doesn't "wear off" :) only physically moving parts could do (like fans), but if your dGPU is not loaded fans will be off anyway
