### ISSUE TITLE
Pixel art mode for AniMe Matrix

### ISSUE THREAD

**Issue by KelseyHigham** [seerge/g-helper#1648]
**Is your feature request related to a problem? Please describe.**
i'd like to draw pixel art on the AniMe Matrix, but G-Helper's diagonal setting defaults to showing images at less than the full width of the Matrix.

**Describe the solution you'd like**
i'd like to pick a gif that's the Matrix's exact resolution (on the 2023 G14, that's 64x39), click diagonal, leave the slider at 100%, and have the image occupy the whole Matrix.

**Describe alternatives you've considered**
a checkbox for "pixel-perfect" that's independent of the slider would work too. or have the slider snap to a full-Matrix value.

**Additional context**
this 2023 G14 template works without modification on Armory Crate. it would be cool if it worked perfectly on G-Helper too, so that people can share images that work in both programs.
> ![G14-2023-template-AC](https://github.com/seerge/g-helper/assets/286211/09477bfe-26c1-470d-a00f-70ea375282b4)　![G14-2023-template-AC-blank](https://github.com/seerge/g-helper/assets/286211/326221c7-5662-4d9d-91d6-15144b2b5805)

Armory Crate, diagonal, default scaling:
> ![Armory Crate](https://github.com/seerge/g-helper/assets/286211/ca8c111e-17c0-47e7-85ce-a25e1b880410)

**Comment by KelseyHigham** [comment]
in the meantime, for people like me, here's a 2023 G14 G-Helper template:
> ![G14-2023-template-GH](https://github.com/seerge/g-helper/assets/286211/1aac05bf-69ea-4156-93a0-1f14117ab870)

it looks like this:
> ![IMG_5085](https://github.com/seerge/g-helper/assets/286211/23493f79-0731-40f6-a785-67e377827e15)

but it would be nice to have access to the three corners!

**Comment by seerge** [comment]
@KelseyHigham hello, cool that you have figured out how to resize template :) current logic was that origin on a matrix is bottom left corner.

I may look into shifting it to the left (outside of visible space), and extending width to cover other side as well.

**Comment by seerge** [comment]
@KelseyHigham hello, try this build. Your original template should work fine now as well, as other pictures.

It was quite difficult to find a good middle-ground between automatically fitting any filling matrix with picture
[GHelper.zip](https://github.com/seerge/g-helper/files/14041971/GHelper.zip)

**Comment by KelseyHigham** [comment]
it's mostly correct! but there's a bit of bleed from the far left column to the column immediately to the right of it
![6ED45B4F-9172-46EA-985E-E617C1AE73A0](https://github.com/seerge/g-helper/assets/286211/8248aed5-1cb9-4aef-939b-f7dbb164db70)

**Comment by KelseyHigham** [comment]
i don't see similar bleed anywhere else

**Comment by KelseyHigham** [comment]
oh actually, it's weirder than that
in this image, the green column is inside the matrix, and the blue column isn't visible.
but for some reason, the green column is lit by both pixels in the green column, and pixels in the blue column
![G14-2023-template-broken](https://github.com/seerge/g-helper/assets/286211/4fe6469b-637c-4b3e-a018-fbe891f86dad)
![G14-2023-template-broken-upscaled](https://github.com/seerge/g-helper/assets/286211/89da2aad-e059-45d9-bcf8-2d70feb70760)

**Comment by seerge** [comment]
@KelseyHigham hello, just select different scaling method from a dropdown :) image is resized / fitted anyway, it's not being shown on a pixel perfect level.

**Comment by KelseyHigham** [comment]
changing the scaling method doesn't work! the issue isn't scaling
it's that the data for those pixels is getting drawn from the wrong part of the image

**Comment by KelseyHigham** [comment]
if i make the pixels in the blue column completely white, then the pixels in the green column become completely white. they're not like gray from bleed, they're just taking the data directly from the blue column

**Comment by seerge** [comment]
@KelseyHigham well, i don't know the reason for that. I have tried bunch of different pictures and they look ok, so i looks extremely minor as for me :)

If you want to tinker with it by yourself 
https://github.com/seerge/g-helper/blob/cda04d3c3b9e390addb82671f87415b2b62f6636/app/AnimeMatrix/AnimeMatrixDevice.cs#L487

:)

**Comment by KelseyHigham** [comment]
got it! there's a pretty easy workaround so it's not a huge deal, and it's a big improvement from before.

thank you! it's nice to have the full canvas to work with now :)

**Comment by seerge** [comment]
@KelseyHigham i guess I have actually figured it out.

Try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/14073808/GHelper.zip)

**Comment by KelseyHigham** [comment]
that works! hell yeah thank you!
