### ISSUE TITLE
More keyboard backlights

### ISSUE THREAD

**Issue by alimahran2612** [seerge/g-helper#1649]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
more controls to backlight options, specially transition speed

**Describe alternatives you've considered**
adding more backlight options

**Comment by seerge** [comment]
@alimahran2612 hello,

All backlight modes (except Heatmap / Ambient with specific logic) are handed purely by hardware. I.e. your keyboard needs to support them in a first place. So I can't add "more".

Same applies to transition speed, keyboard modes have 3 predefined speeds, all of them are available already
