### ISSUE TITLE
[Bug] Fan curves disappeared in GHelper v0.42

### ISSUE THREAD

**Issue by mAto0o1** [seerge/g-helper#165]
**Describe the bug**
My custom fan curves disappeared after installing the latest 'pre-release [GHelper v0.42](https://github.com/seerge/g-helper/releases/tag/v0.42)' version of G-helper. 

To Reproduce
1. Reinstalling the G-helper by swapping the .exe files

**Expected behavior**
You will have to re-apply the CPU/GPU Fan curve again.

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 x64
 - Laptop model G15 GA503RW.311
 
-This is my first post ever on GitHub. I hope I have not forgotten anything, or gotten anything wrong. Thanks!

**Comment by seerge** [comment]
What do you mean under "disappeared" what do fan editor show?

**Comment by mAto0o1** [comment]
I had to re-apply them, they got set to default. Sorry for the misunderstanding.

**Comment by seerge** [comment]
Well, i didn't change anything in 42 (and in previous builds) that is even closely related to that :) may be you just accidentally clicked "factory defaults" button?

As for export/import - it's already possible. Just copy ``%AppData%\GHelper\config.json`` somewhere , that will be your export :) (and put it back - that will be import)
