### ISSUE TITLE
Automatically switch performance modes

### ISSUE THREAD

**Issue by zylzyl1029** [seerge/g-helper#1650]
**Describe the solution you'd like**
automatically switch performance modes according to different applications (such as games), similar to the scenario profiles in Armoury Crate

**Comment by seerge** [comment]
@zylzyl1029 hello, I was answering this question already, properly detecting games / applications running on windows is a cumbersome and not reliable process.

I believe it's already very easy to switch between profiles with hotkeys (Fn+F5 and Shift+Fn+F5)
