### ISSUE TITLE
Ambient backlight mode doesnt work

### ISSUE THREAD

**Issue by NeutronOrg** [seerge/g-helper#1652]
Sometimes while switching between backlight modes ambient mode/color doesnt seem to work and it doesnt change keyboard backlight color.
version: v0.134

**Comment by seerge** [comment]
> ## NOTE
> Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer.  Please respect the time of the developer. Thanks.
