### ISSUE TITLE
Fan speed

### ISSUE THREAD

**Issue by BlackCherryCat** [seerge/g-helper#1654]
**Describe the bug**
After clicking on turbo mode, the gpu fan will go slowly decreasing from 100% to 75%

**Clear scenario to Reproduce**
1. Click on 'Turbo mode'
2. Wait 5 minutes or so
3. GPU fans will get decreasing until it reached 75%
4. Click again on turbo mode and all fans will go up to 100% again

**Expected behavior**
While in turbo mode, all fans to 100%

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13464991/log.txt)

**Screenshots or screencasts**

After clicking:
![image](https://github.com/seerge/g-helper/assets/68470515/6aeb1f72-725a-478b-afd0-530537b1dc88)

After 5 minutes:
![image](https://github.com/seerge/g-helper/assets/68470515/19731cab-bf24-46d8-ba91-85f06f7167f8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: Asus ROG Flow X13 GV301QH-K6069T

**Asus software**
I only have GHelper with it's dependencies

**Additional context**
Using original charger all the time and always plugged. This happens in any situation, gaming or not. Months ago this behavior did not happen. Also tried downgrading BIOS. This will happen in any other mode you want to have the 100% of speed of both fans, not only in turbo mode

**Comment by seerge** [comment]
@BlackCherryCat hello,

I see that you have set a custom fan curve

```
25/11/2023 19:34:14: FanCPU = 1D-30-38-3C-43-48-49-48-64-64-64-64-64-64-64-64 : OK
25/11/2023 19:34:14: FanGPU = 1E-30-38-3C-43-48-49-48-64-64-64-64-64-64-64-64 : OK
```

And it indeed seem to work :) But please keep in mind, that G-Helper doesn't control your fans in realtime anyhow, as this is done by firmware / BIOS, and it's up to BIOS how to treat them.

Most probably there is some protection from fan abuse, that lowers speed on a long run :)

There is nothing to fix here on the app side

**Comment by seerge** [comment]
@BlackCherryCat Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks
