### ISSUE TITLE
Removing other GPU Mode option for models that do not have a dGPU "enhancement"

### ISSUE THREAD

**Issue by yasutakatakumi** [seerge/g-helper#1658]
Model name: ROG Flow x13 GV302XA_GV302XA
My model is only equipped with an iGPU and _**does have a second fan**._

```
__GENUS          : 2
__CLASS          : __PARAMETERS
__SUPERCLASS     :
__DYNASTY        : __PARAMETERS
__RELPATH        :
__PROPERTY_COUNT : 1
__DERIVATION     : {}
__SERVER         :
__NAMESPACE      :
__PATH           :
device_status    : 65537
PSComputerName   :
```

<img width="301" alt="image" src="https://github.com/seerge/g-helper/assets/74696514/85da3f79-d979-48c7-b78f-3a3db39defc9">

Cheers!

**Comment by seerge** [comment]
@yasutakatakumi i'm sure it does have a second fan :) as there are separate reading for it.

**Comment by yasutakatakumi** [comment]
Just received my laptop and this is also my first time using your tool!
Thank you! Hoping to have a clean UI soon!
<img width="405" alt="image" src="https://github.com/seerge/g-helper/assets/74696514/9a6e586a-bf12-4016-878e-8dce11f707c3">
Will be donating more in the future!
