### ISSUE TITLE
Power Limits not applied correctly in some instances

### ISSUE THREAD

**Issue by TLD99** [seerge/g-helper#166]
**Describe the bug**
Essentially, when shifting profiles where custom power limits have been updated and auto-applied, upon monitoring via RTSS or similar, it's visible that the power limit just applied via G-Helper is not taking effect. I.E. If I've just applied a 25W PPT, the value still touches 30W.

Tested in Ultimate mode.

**To Reproduce**

1. Stay on any performance mode
2. Update PPT for CPU (unclick and click the auto-apply again to be sure)
3. Click Apply
4. Tab back into the game, even few seconds later, notice the PPT didn't take effect.

Optionally, going to different profiles and/or clicking auto-apply/changing PPT values and applying again seems to force G-Helper to recognize PPTs have been changed for the current profile, but this is a hit or miss.

**Expected behavior**
Every time I change the PPT and have auto-apply checked, the new PPT should take effect immediately. If auto-apply is not checked, then clicking the apply button below should do the same instead.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Windows 11 Version 22H2 Build 22621.1485
Asus Zephyrus G15 2022 w/RTX 3070Ti and AMD Ryzen 9 6900HS

**Comment by seerge** [comment]
1. Do you have 2 PPT sliders available (platform + cpu) on your laptop or only CPU ?
2. Can you measure CPU PPT with HWinfo ? For me that app was a reference, as MSI Afterburner / RTSS  seemed to mix numbers.
3. Do armoury manual mode limiter apply and work correctly with RTSS measurements?

**Comment by JackB111** [comment]
I have the same problem. I use the same model, there is 1 slider. ( just cpu )

<img width="765" alt="image" src="https://user-images.githubusercontent.com/129295334/228791441-1afd7696-292b-4d90-8282-1277381f1356.png">


<img width="61" alt="image" src="https://user-images.githubusercontent.com/129295334/228791143-7541c159-c2ce-486b-b65f-69d63625a63b.png">


And I wish there was a dynamic boost slider. :D

**Comment by seerge** [comment]
@JackB111 same question to you - can you post HWinfo measurements ?

**Comment by JackB111** [comment]
> 

I sent it to you. hwinfo wattage at the bottom left.

**Comment by JackB111** [comment]
> > 
> 
> I sent it to you. hwinfo wattage at the bottom left. 7.152W @seerge

**Comment by seerge** [comment]
@JackB111 can you make a normal screenshot ? i have zero idea on this stage what happens on your laptop, may be it just doesn't support PPT limits that low, do other values work ?

**Comment by JackB111** [comment]
after v0.43, problem solved for me, idk what happened

**Comment by seerge** [comment]
Based on a powershell output (it says result = 1) / log (says OK), app sends power limit command it it's accepted. So there is no bugs here and not much I can do neither.

Why your system is not reacting on that sometimes and sometimes does, I don't know. Does power limits work differently when you apply it with armoury?

You may try to reinstall Asus System Control interface (asus "driver" that actually handles this commands) as explained here https://github.com/seerge/g-helper/discussions/145#discussioncomment-5431447

Also try to not to smash apply button all the time immediately btw (may be it "confuses" asus driver / bios). 
as i see it in log
```
03-Apr-23 10:10:49 PM: PowerLimit A = 150 : OK
03-Apr-23 10:10:50 PM: PowerLimit A = 150 : OK

03-Apr-23 10:13:01 PM: PowerLimit A = 15 : OK
03-Apr-23 10:13:02 PM: PowerLimit A = 15 : OK
03-Apr-23 10:13:02 PM: PowerLimit A = 15 : OK
```

If "auto apply" is checked, there is no need to click apply at all, app will do it automatically when mode is selected

**Comment by seerge** [comment]
I did some changes for power limits. They don't directly target what is explained here (as i simply can not reproduce anything of that), but it would be good to check this build , if it behaves better:

[GHelper.zip](https://github.com/seerge/g-helper/files/11186388/GHelper.zip)
