### ISSUE TITLE
Can't change gpu mode on G17 G712LW

### ISSUE THREAD

**Issue by olivkauwu** [seerge/g-helper#1661]
System Model	ROG Strix G712LW_G712LW

I don't have a gpu mode selection in ghelper.
I'm not sure is it supposed to support it, but i think it was here earlier ( I don't remember exactly, but I'm pretty sure, that it was here)

![image](https://github.com/seerge/g-helper/assets/152069398/209bb830-d4fb-41fd-8a0b-81ae79960a32)

Windows 11, 0 asus services
[log.txt](https://github.com/seerge/g-helper/files/13474606/log.txt)

**Comment by seerge** [comment]
@olivkauwu if you don't see modes, it means they are not supported by your hardware

**Comment by seerge** [comment]
In your case no. You can just set power plan settings to force power saving graphics on battery

![image](https://github.com/seerge/g-helper/assets/5920850/a48c67d9-1e5d-4948-bc75-64bc84b5faef)
