### ISSUE TITLE
Volume buttons

### ISSUE THREAD

**Issue by dimenybence** [seerge/g-helper#1665]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**
I have a G14 and the volume buttons stopped working with this release. I tried to reprogram to other functions like mode switch but it doesnt work either.

**Clear scenario to Reproduce**
4. Explanation of an error or a bug

**Expected behavior**

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/13488873/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Asus Zephyrus G14

**Additional context**

**Comment by seerge** [comment]
@dimenybence hello, g-helper never controlled volume buttons :) they emit windows volume up / down commands on hardware level. And they work even when no app is running at all.

So most probably it's some hardware issue, or you have other app running that intercepts volume buttons.
