### ISSUE TITLE
Tie Fans speed together button.

### ISSUE THREAD

**Issue by xSimone** [seerge/g-helper#1666]
Could you create a button that links all the fans together?

Some Laptops utilise a thermal bridge and share the heatsink with different components, example the Scar 18 has a bridge that connects the entire rear fin to both the CPU and GPU

Sometimes, only the GPU fan spins because the CPU isn't getting hot, so one side of the heatsink isn't being cooled.

It'd be awesome that if there's a fan spinning, then all the other fans will catch up and match the speed for even cooling.

Do you think this is possible?

**Comment by seerge** [comment]
@xSimone hello, that's not possible as app doesn't control fans in a first place :) it can only (optionally) set custom fan curves. Fans are controleld by firmware / bios.

Sorry

**Comment by xSimone** [comment]
Thank you anyway. :c 

It was only an example, but yes sometimes I have CPU heavy tasks, but GPU is not being used at all.
