### ISSUE TITLE
[Feature Request] Matrix display editor

### ISSUE THREAD

**Issue by Tornado-F5** [seerge/g-helper#167]
**Is your feature request related to a problem? Please describe.**
I have a library of images and gifs, that I can use on the matrix display. In Armmoury crate I was able to resize it and move it on the matrix display, but that is not a feature in Ghelper, which makes most of these images look bad because they are in the wrong posigtion on the display or too big or small.
**Describe the solution you'd like**
An editor with options to resize and move the media before applying it to the matrix display, also being able to change the speed of a gif would be nice, as they play in slo-mo on the display.
**Describe alternatives you've considered**
Using armoury crate, but that isn't an option

**Comment by Tornado-F5** [comment]
I don't have Armoury crate installed anymore, but I found an image online of the screen with the functionality I'm missing: 
![image](https://user-images.githubusercontent.com/102478143/228800798-43dd25f6-7324-4c1f-8194-7f9e773d4cad.png)
So I can change where on the display teh image is shown, if you get what I mean.
I am currently using v42.

**Comment by seerge** [comment]
I'm aware how armory image editor looks like. You have mentioned that g-helper is not rendering images properly (comparing to armoury), so I have asked you to demonstrate the differences.

Currently g-helper sizes image to fully fit the animatrix display + aligns it to the top-right to have as much screen real estate is possible. 

And creating a fully functional picture editor as part of a small (and lightweight!) open source app is absolutely not feasible :)

**Comment by seerge** [comment]
If you really want to have a custom positioning you can just edit image by yourself a bit, i think "perfect" canvas for G14 2022 would be 102 x 61 px

**Comment by lucidnx** [comment]
I think he meant that GIFs are not showing whole image that's in it. but he need to add gaps to left and bottom of gif itself, to move whole image to correct place/rotate it when needed.
![image](https://user-images.githubusercontent.com/53317668/228866170-b57d3e1c-2f52-4b55-b235-a3fc8fe5fd51.png)

**Comment by seerge** [comment]
Then correct template would look something like this (in original size) 😄 
![Slice 2](https://user-images.githubusercontent.com/5920850/228895174-c2b48107-6588-4a24-ab07-b40ba02919a3.png)

**Comment by Tornado-F5** [comment]
Sorry for my late response, but something like this would be awesome to have, even if it's made really basic, it would make the matrix functionality much better.
![image](https://user-images.githubusercontent.com/102478143/230322269-df3509d6-5551-45d3-ada6-99be195c4601.png)

**Comment by seerge** [comment]
Hello, i'm afraid that's quite out of scope atm :)
