### ISSUE TITLE
Asus ZephyrusDuo 4k 120hz , 240hz change botton

### ISSUE THREAD

**Issue by HIKARISWET** [seerge/g-helper#1670]
i use Zephyrusduo 4K 120, 240hz display
i want change switch

**Comment by seerge** [comment]
@HIKARISWET hello, current logic of 60hz / max refresh rate switch is to preserve battery only. I don't really see any point in listing all possible refresh rates in the app, you can use windows settings for that ;)

So I don't plan it, as I don't want to overload already cluttered UI
