### ISSUE TITLE
FN lock

### ISSUE THREAD

**Issue by tayebom** [seerge/g-helper#1671]
**Describe the bug**
fn lock when enabled makes fn keys function all the time
either you press fn button or not

**Clear scenario to Reproduce**
1. Go to 'g-helper'
2. Click on 'FN-lock'

**Expected behavior**
it should make fn keys only function when fn button is not pressed

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13497775/log.txt)

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Laptop model asus tuf f15 2021 fx516pe

**Asus software**
- Armoury Crate not installed
- MyASUS not installed
- There is no Other Asus services running in background

**Additional context**
only g-helper 0.134 installed

**Comment by seerge** [comment]
@tayebom hello, unfortunately this is not possible, and I was answering exactly same question already couple of times here.

It's a software imitation of the fn-lock, so app just registers F1-F11 as own "hotkeys" in windows when fn-lock is on, and runs corresponding actions when they are pressed :)
