### ISSUE TITLE
Provide wider range for Nvidia Memory Clock Offset.

### ISSUE THREAD

**Issue by THEBOSS619** [seerge/g-helper#1672]
**Is your feature request related to a problem? Please describe.**
It's not a problem, but i would rather have more freedom or wider range of Nvidia Memory Clock Offset rather than installing & using MSI Afterburner just for that. I would rather use 1 tool for all :)

**Describe the solution you'd like**
Having more than 250Mhz (-/+) range for Nvidia Memory Clock Offset. For example like having 500Mhz or 750Mhz (-/+) range.

**Describe alternatives you've considered**
Maybe have a checkbox to remove the limits for advanced users but I would rather prefer 500Mhz or 750Mhz (-/+) range just for safety and new users.

**Additional context**
This is what I mean about it. If possible & if you don't mind to consider this. Thank you.
![image](https://github.com/seerge/g-helper/assets/32247935/213c150e-999a-4e4d-b64b-7d0742db6ad3)

**Comment by seerge** [comment]
@THEBOSS619 you can already do that 
https://github.com/seerge/g-helper#higher-maximum-gpu-clock--memory-offsets

**Comment by THEBOSS619** [comment]
> @THEBOSS619 you can already do that https://github.com/seerge/g-helper#higher-maximum-gpu-clock--memory-offsets

Thank you so much, forgive me for wasting your time.

**Comment by THEBOSS619** [comment]
> @THEBOSS619 you can already do that https://github.com/seerge/g-helper#higher-maximum-gpu-clock--memory-offsets

I have tried that but it doesn't allow me to go lower than -250Mhz, I would like to go for like -500Mhz if possible. Thank you.

**Comment by seerge** [comment]
Why would you want to go lower ? It will only increase your power consumption

**Comment by THEBOSS619** [comment]
> Why would you want to go lower ? It will only increase your power consumption

@seerge What you are saying is true about the **Core** Clock Offset.

But I only need to go lower for the **Memory** Clock Offset not the **Core** Clock Offset.

**Comment by seerge** [comment]
@THEBOSS619 then you can set  :) 

```
"min_gpu_memory" : - 500,
```

https://github.com/seerge/g-helper/blob/main/app/Gpu/NVidia/NvidiaGpuControl.cs

**Comment by THEBOSS619** [comment]
> @THEBOSS619 then you can set :)
> 
> ```
> "min_gpu_memory" : - 500,
> ```
> 
> https://github.com/seerge/g-helper/blob/main/app/Gpu/NVidia/NvidiaGpuControl.cs

Thank you so much, it works! Just a small correction... to remove the space between **-** and **500** to prevent problems :)

`"min_gpu_memory" : -500,`
