### ISSUE TITLE
“ASUS BIOS rejected fan curve”What should I do with it?

### ISSUE THREAD

**Issue by Silvicultori** [seerge/g-helper#1674]
When I try to change the fan speed, it will display like this:“ASUS BIOS rejected fan curve”
What should I do with it?
My laptop model is:ASUS Vivobook S15 OLED

**Comment by seerge** [comment]
@Silvicultori you can start from [checking FAQ](https://github.com/seerge/g-helper#when-i-try-to-apply-a-custom-fan-curve-i-get-bios-rejected-fan-curve) :) most probably your laptop doesn't support custom fan curves at all

**Comment by seerge** [comment]
@Silvicultori Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks

**Comment by Silvicultori** [comment]
> @Silvicultori Hello, if you are interested you can try an experimental build with actual "manual" fan control #2272 . Thanks

Oh my God, thank you so much for remembering my question, this is already six months ago, and you have closed my issue, I am glad. Thank you very much for solving that problem, I have tested G-Helper and it works perfectly!

**Comment by seerge** [comment]
@Silvicultori glad it's working. I have informed everyone who has created issues about fans (that g-helper doesn't control by default) over last year
