### ISSUE TITLE
Nvidia GPU does not enable itself / apply overclocks when it wakes from sleep/hibernate

### ISSUE THREAD

**Issue by RahulVivekNair** [seerge/g-helper#1683]
**Describe the bug**
I've noticed that the nvidia gpu disappears from the device list when waking up from sleep/hibernate. Sometimes you can enable it again by switching from optimized to standard mode and back. Sometimes this does not work and so quitting g-helper and starting it again enables it. Sometimes this this does not work either and the only option left is to reboot the laptop.

Another associated problem is that in case the gpu is enabled the overclocks i've applied reset and shows as 0 in the UI after waking up from sleep/hibernate. You then have to switch from turbo mode to any other mode and then switch back and then the previously set overclocks apply correctly and shows up in the ui. This is a very frustrating experience as it feels like i'm manually enabling and applying overclock everytime.

**Expected behavior**
The nvidia gpu should be enabled when plugged in even when waking up from sleep/hibernate. The overclocks should also apply properly.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13536367/log.txt)
[config.json](https://github.com/seerge/g-helper/files/13536386/config.json)

**Screenshots or screencasts**
https://imgur.com/a/O0fWoEn
the above screen recording shows having to switch gpu modes to enable the gpu.
I have to wait to the overclocks reset to upload the overclock problem recording.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Asus Tuf f15 506HM
 - 11400h + 3060

**Asus software**
- All Asus apps uninstalled

**Comment by seerge** [comment]
@RahulVivekNair hello, i think it's some hiccup with nvidia driver that stopped responding at all :) (probably due to frequent dGPU enabling / disabling or after waking up from laptop sleep)

I see that in the beginning everything was detected and even clocks were checked (and would be applied if they would be set)

```
01-Dec-23 2:22:53 PM: Running eco command 0
01-Dec-23 2:22:53 PM: GPUEco = 0 : OK
01-Dec-23 2:22:53 PM: Eco flag : 0
.....
01-Dec-23 4:03:16 PM: NVIDIA GeForce RTX 3060 Laptop GPU   ->  driver detected, and responding 
01-Dec-23 4:03:16 PM: GET GPU CLOCKS: 0, 0
01-Dec-23 4:03:16 PM: GET CLOCK LIMIT: 0
```

Later

```
02-Dec-23 5:03:34 PM: Running eco command 0
02-Dec-23 5:03:34 PM: GPUEco = 0 : OK
02-Dec-23 5:03:35 PM: Eco flag : 0
02-Dec-23 5:03:35 PM: Mux flag : -65536
....
02-Dec-23 5:03:35 PM: ScreenOverdrive = 1 : OK
02-Dec-23 5:03:38 PM: Clocks: NotNvidia  -> driver is not responding / not detected at all
```

I would recommend just to reboot laptop as there is nothing app can do if driver is not responding :)

**Comment by RahulVivekNair** [comment]
Yup, interestingly I had similar problems with armoury crate too but only occasionally , just wanted to see if others are facing it too.

But the clocks not applying when the gpu is active is a bit weird, it happens consistently and I've made sure the driver is responding too, might be trying to apply just before the gpu is woken up, need to debug and check.

**Comment by seerge** [comment]
@RahulVivekNair you can try to do a clean nvidia driver install using [DDU](https://www.guru3d.com/download/display-driver-uninstaller-download/), it may help :)
