### ISSUE TITLE
PL1 + PL2 Power limits seem to not work

### ISSUE THREAD

**Issue by Sanaan01** [seerge/g-helper#1685]
[log.txt](https://github.com/seerge/g-helper/files/13538534/log.txt)

The power limits seem to not apply even when I check the box on ROG Strix G614JV. I only noticed this recently as i was using the laptop on the go and realised the temperatures did not change even if i set the cpu to 5 watts or even the max 150 watts and discharge rate didnt change as well.

I expected a drop in temps and lower discharge rate.

**Comment by seerge** [comment]
@Sanaan01 hello, how do you check  that power limit is working or not ? 

Your discharge rate is NOT your CPU power limit, it's a rate of how fast battery is loosing it's charge and also consists of lots of other things.

**Comment by Sanaan01** [comment]
I don't know how to exactly check power limit but i thought them to be not working correctly as ive seen other people on reddit etc with massive decrease in idle temps while mine don't even change.

**Comment by seerge** [comment]
@Sanaan01 your temperatures depend on lots of factors and on what is actually running on your laptop.

You can monitor your CPU power consumption by loading it with benchmark like Cinebench and then checking actual CPU power usage with HWinfo or so :)

**Comment by Sanaan01** [comment]
Do the power limits in hwinfo have to be the same as ghelper?
![image](https://github.com/seerge/g-helper/assets/81903566/1116b590-79dc-4f35-a68e-96ba37969625)

**Comment by Sanaan01** [comment]
I am not sure if its working because even without the power limit total package power is at 30 watts unless if i go turbo mode. 
![image](https://github.com/seerge/g-helper/assets/81903566/12414e37-6bcc-48d9-bdae-06d039bf549d)
but it doesnt drop below 30 watts even if i give it 50 watts it doesnt change 
![image](https://github.com/seerge/g-helper/assets/81903566/dfa71b3e-e0a3-46f9-a193-0590a26e8e53)

**Comment by seerge** [comment]
@Sanaan01 that's probably how modes are hardcode in BIOS on your device :) silent may not go higher than some values.

In AC Manual mode is actually Turbo (with extra settings), so if you want to test max power you should indeed user Turbo :)

Anyway, this is how power limits are done by asus itsef.

If you want to set power limits in other way, via driver - you can try Throttlestop app.

**Comment by Sanaan01** [comment]
Okay thanks for the clarification so it looks like my cpu can't drop below 30 watts.

**Comment by seerge** [comment]
@Sanaan01 please keep in mind that this amounts are just limits, if not loaded - your CPU will consume much less :)

So if you want to preserve battery, you should mainly make sure that there is no strange things running in a background, like windows indexing all files for search, some strange apps, etc.
