### ISSUE TITLE
Laptop Keyboard effects and colors

### ISSUE THREAD

**Issue by AlexmograineThird** [seerge/g-helper#1686]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**
After updating to version 0.135.0 I lost most of the Laptop Keyboard effects ( rainbow... etc). Also once i select a mode and try to change colors nothing happens keyboard either stays red or goes dark ( yes it is an aRGB keyboard)

**Clear scenario to Reproduce**
On a G14 2023 select any laptop keyboard mode and try to change colors.

**Expected behavior**
Usually more modes are available ( other than Static/Breathe/Strobe)

**App Logs**

[log.txt](https://github.com/seerge/g-helper/files/13538542/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/58644818/ff27b3dd-16bc-4758-8d10-f0ed200bfb0f)
![image](https://github.com/seerge/g-helper/assets/58644818/dc47f267-5deb-4d4f-b59b-0b25d17c4563)

**Desktop (please complete the following information):**
 - OS: Windows 11]
 - G14 2023

**Asus software**
- MyASUS installed
No services running in background
![image](https://github.com/seerge/g-helper/assets/58644818/ff27b3dd-16bc-4758-8d10-f0ed200bfb0f)

**Comment by seerge** [comment]
@AlexmograineThird hello, does your model has multi-color backlight in a first place ? as I remember some of 2023 models are white only?

**Comment by seerge** [comment]
@AlexmograineThird try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/13538598/GHelper.zip)

**Comment by AlexmograineThird** [comment]
> @AlexmograineThird hello, does your model has multi-color backlight in a first place ? as I remember some of 2023 models are white only?

That is correct however I have an aRGB version for sure. Just redownloaded v0.134.0 and when I put color cycle mode it correctly cycles every possible color

**Comment by AlexmograineThird** [comment]
> @AlexmograineThird try this build [GHelper.zip](https://github.com/seerge/g-helper/files/13538598/GHelper.zip)

This one works :) Is it possible to add a "reset" switch for the color tab next to the keyboard effects?

**Comment by AlexmograineThird** [comment]
So the issue I faced was, I selected "rainbow" mode and then clicked on a color with the adjacent menu, and no color change would happen (nor rainbow effect). I thought it might have been something I touched in the settings and wanted to "reset" to default the keyboard effect profiles.
