### ISSUE TITLE
Unable to update GHelper or drivers via GHelper

### ISSUE THREAD

**Issue by Magicienghost** [seerge/g-helper#1687]
## Unable to update

**Describe the bug**
- GHelper tells me it can be updated, so I download the new version, replace the old one and run the new one. Except that after restarting my computer, GHelper is back in its previous version. 
- I'm also unable to update my drivers via GHelper: it prompts me to download the new driver, I install it and restart my computer to finalize the installation, and GHelper detects the driver as still out of date. 

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13538824/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ROG Strix G513IM

**Asus software**
- All asus services are switched off

**Comment by seerge** [comment]
@Magicienghost you probably have app running from some other location at startup :) Just launch latest (updated) version and uncheck / check Run on Startup checkbox, it will update startup task to a location of current exe

**Comment by seerge** [comment]
@Magicienghost what kind of driver is that ? App just checks local version installed on your computer, and what version is available on asus website (by asus own words)

**Comment by Magicienghost** [comment]
Perfect! Thanks for your help and congratulations on GHelper, it's great!
