### ISSUE TITLE
Help permanently turning off the Anime Matrix

### ISSUE THREAD

**Issue by droza888** [seerge/g-helper#1694]
**Is your feature request related to a problem? Please describe.**
Yes, I'm having trouble permanently disabling Anime Matrix. Even though I have Anime Matrix set to "off", sometimes (maybe once a week?) some random pixels will turn on. Activating an option like Clock and then turning it off will successfully deactivate the Anime Matrix again. I'm not sure what causes it to activate some random pixels, but Anime Matrix reactivating itself for no apparent reason when deactivated is a somewhat common issue reported with the G14:
https://www.reddit.com/r/ZephyrusG14/comments/grc3vz/anime_matrix_turns_on_automatically_after_restart/
https://www.reddit.com/r/ZephyrusG14/comments/u989so/anime_matrix_is_annoying_keeps_enabling_itself/
https://www.reddit.com/r/ZephyrusG14/comments/pfncix/how_to_turning_off_anime_matrix_permanently_it/
https://www.reddit.com/r/ZephyrusG14/comments/qbgm81/how_do_i_permanently_disable_animatrix/

**Describe the solution you'd like**
I'd like the software to try to reapply the Anime Matrix setting you have chosen (in my case "Off") every time you wake up from sleep, from hibernate, or reboot. Or a checkmark option to have it do so. My hope is that this will permanently fix the issue. 

**Describe alternatives you've considered**
I've tried all suggestions on the Internet I could find with and without Armoury Crate (for example, disabling the Lightning Service or renaming it, uninstalling Armoury Crate, configuring Armoury Crate correctly to have it completely off, etc.). In every case, it stays off for a few days, then mysteriously turns back on at some point. 
GHelper has been helpful. I have it fully updated, and all ASUS software, Armoury Crate, etc. uninstalled and/or disabled, per the GHelper installation recommendations. I have had greater success with GHelper than I did with Armoury Crate, but even so it comes back occasionally. GHelper is helpful to deactivate it when it does turn back on (I have to select Clock, and then reselect Off).  

**Additional context**
Thanks for such an amazing app! It has made my G14 experience much more enjoyable!

**Comment by seerge** [comment]
@droza888 hello, app already does that. It sets matrix on or off every time it's started or laptop wakes up / changes power source

https://github.com/seerge/g-helper/blob/3848ef9a43512ed014252b17dacc5054441b17ad/app/Program.cs#L227C16-L227C16
