### ISSUE TITLE
Question about iGPU and dGPU modes

### ISSUE THREAD

**Issue by Konnos998** [seerge/g-helper#1703]
**Describe the bug**
In G-Helper app I don't see any GPU Modes. The only thing I see is "Stop GPU applications", which was present in AC too. I don't know if it's a problem or my laptop just doesn't support any further modes.

**Clear scenario to Reproduce**
1. Go to G-Helper app
2. See GPU Mode: iGPU + dGPU (either has modes or, like in my case, only has the option to stop gpu applications)

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/13605811/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home, 22H2 version
 - Asus Rog Strix G531GV (i7-9750H, RTX 2060)

**Comment by seerge** [comment]
@Konnos998 hello , your device simply doesn't support any of that
