### ISSUE TITLE
Zephyrus G15 ga503rm 2022 freezes randomly when using G Helper

### ISSUE THREAD

**Issue by Maneeha1234SL** [seerge/g-helper#1706]
Zephyrus G15 ga503rm 2022 freezes randomly when using G Helper.
The system will not respond.After a few minutes, the system restarts automatically.
Below are the log files of the event viewer and a video taken at the time of the problem to make it easier to identify the problem.

Time the problem started .: -  12/8/2023 10:35AM
The problem occurred after ghelper pops up menu to check cpu gpu temps while playing games.

**Desktop (please complete the following information):**
 - OS: Windows 11 22h2
 - Laptop model zephyrus G15 Ga503rm

**Asus software**
- All Asus apps uninstalled

Ghelper Configs:-
[log.txt](https://github.com/seerge/g-helper/files/13610651/log.txt)
[config.json](https://github.com/seerge/g-helper/files/13610653/config.json)

event viewer logs
https://drive.google.com/file/d/1J-U6MJm4WOPsOXR45u4TyrlVw02yIwEb/view?usp=sharing

video :-

https://drive.google.com/file/d/1UgO9ZN60zZDq84l0Bgq59QeSQIwckFxK/view?usp=sharing

**Comment by seerge** [comment]
@Maneeha1234SL hello. G-Helper is not a Windows, Driver or Firmware. It doesn't "run" your system anyhow, and doesn't do anything in background neither unless you change something in the settings.

If your computer hardware has issues, you may try to do a fresh install, or reinstall drivers at least.

Good luck

**Comment by seerge** [comment]
@Maneeha1234SL "Mouse Detection" just gets a list of USB devices from windows , I really doubt it has any effect on case.

Bluetooth mouse is NOT USB, so it doesn't trigger that :)
