### ISSUE TITLE
NVIDIA-SMI has failed and Skip aura:1 failed

### ISSUE THREAD

**Issue by 123dqwkhjk** [seerge/g-helper#1707]
**Describe the bug**
1. When laptop boot it will disable dgpu even charging.
2. "skip_aura" : 1 didn't look working on my laptop now, it still light up.

**Clear scenario to Reproduce**
Steps to reproduce skip aura:1 failed
1. Add "skip_aura" : 1 to config
2. Boot.

**Expected behavior**
For the first case, the dgpu should enable default.
For the second case, the keyboard backlight should turn off.

**App Logs**
2023/12/8 17:41:29: App launched: ROG Zephyrus G15 GA503RM_GA503RM :0.135.0.0zh-TW.
2023/12/8 17:41:30: NVIDIA GeForce RTX 3060 Laptop GPU
2023/12/8 17:41:32: CPU: 8 - AMD Ryzen 7 6800HS with Radeon Graphics          - AMD64 Family 25 Model 68 Stepping 1
2023/12/8 17:41:32: AutoSetting for Online
2023/12/8 17:41:32: Input: \\?\hid#vid_0b05&pid_19b6&col05#7&2635b6bc&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023/12/8 17:41:32: Mode = 0 : OK
2023/12/8 17:41:32: GET CLOCK LIMIT: 0
2023/12/8 17:41:32: GPU usage: NVIDIA GeForce RTX 3060 Laptop GPU 0%
2023/12/8 17:41:32: BatteryLimit = 60 : OK
2023/12/8 17:41:32: BatteryLimit = 60 : OK
2023/12/8 17:41:32: nvidia-smi -lgc 0,2000
2023/12/8 17:41:32: USB 19B6: 5D-B9
2023/12/8 17:41:32: Running eco command 1
2023/12/8 17:41:32: USB 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2023/12/8 17:41:32: USB 19B6: 5D-05-20-31-00-1A
2023/12/8 17:41:32: Monitor Power On
2023/12/8 17:41:33: Display configuration changed.
2023/12/8 17:41:33: NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running. This can also be happening if non-NVIDIA GPU is running as primary display, and NVIDIA GPU is in WDDM mode.
2023/12/8 17:41:33: GET GPU CLOCKS:NVAPI_NVIDIA_DEVICE_NOT_FOUND
2023/12/8 17:41:33: SET GPU CLOCKS: 35, 0
2023/12/8 17:41:33: SET GPU CLOCKS: NVAPI_API_NOT_INITIALIZED
2023/12/8 17:41:33: GPUEco = 1 : OK
2023/12/8 17:41:33: Auto 19B6: 5D-BA-C5-C4-00
2023/12/8 17:41:33: Auto Feature 19B6|63: 5A-BA-C5-C4-00
2023/12/8 17:41:34: PowerLimit C0 = 18 : OK
2023/12/8 17:41:34: PowerLimit C2 = 87 : OK
2023/12/8 17:41:34: Eco flag : 1
2023/12/8 17:41:34: Mux flag : 1
2023/12/8 17:41:34: \\?\DISPLAY#CMN1540#5&2b412772&2&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2023/12/8 17:41:34: \\?\DISPLAY#CMN1540#5&2b412772&2&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2023/12/8 17:41:34: Screen = 165Hz : OK
2023/12/8 17:41:34: ScreenOverdrive = 1 : OK
2023/12/8 17:41:34: Display configuration changed.
2023/12/8 17:41:43: Key: 56
2023/12/8 17:41:44: Latest version 0.135.0.0
2023/12/8 17:41:52: Varibright: 1,2
2023/12/8 17:41:52: Hibernate after 2147483647

**Desktop (please complete the following information):**
 - OS: Windows 11 22631.2792 23h2
 - Laptop model: GA503RM

**Asus software**
NO

**Comment by seerge** [comment]
@123dqwkhjk hello, 

```
2023/12/8 17:41:33: NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running. This can also be happening if non-NVIDIA GPU is running as primary display, and NVIDIA GPU is in WDDM mode.
``` 

is an error from your driver and nvidia-smi utility :) I have no idea why it happens and is definitely outside of control for the app. Just restart a laptop and make sure that GPU is enabled

As for ``skip_aura`` it just disables aura modes on start (to prevent interferece with other RGB apps that you may run)
Backlight brightness is still being set, and is set to 0 (last value used)

```
2023/12/8 17:41:33: Auto 19B6: 5D-BA-C5-C4-00
2023/12/8 17:41:33: Auto Feature 19B6|63: 5A-BA-C5-C4-00
```
