### ISSUE TITLE
Clock showing twice in the Anime Matrix

### ISSUE THREAD

**Issue by Arcenus** [seerge/g-helper#171]
**Describe the bug**
The clock function in the Matrix display shows the clock twice, with and without seconds. 

**Expected behavior**
To show the clock once, preferably without seconds in my case.

**Screenshots**
![WhatsApp Image 2023-03-31 at 09 59 56](https://user-images.githubusercontent.com/102511125/229061361-b1acbe02-223e-4cdc-a420-03887e3342b7.jpeg)

**Desktop (please complete the following information):**
 - OS: W11
 - Laptop model: G14 2020 Model, GA401IV
 - G-Helper Version 0.43

**Comment by seerge** [comment]
Can you try this one ?
[GHelper.zip](https://github.com/seerge/g-helper/files/11120468/GHelper.zip)

**Comment by Arcenus** [comment]
Yep, this one works!
![WhatsApp Image 2023-03-31 at 11 44 26](https://user-images.githubusercontent.com/102511125/229086328-61467965-3597-49c2-b85b-eb3995bd9f02.jpeg)

**Comment by seerge** [comment]
Good, i will push this changes to the next release then
