### ISSUE TITLE
Overlaying the mode of the laptop when the computer is in full screen

### ISSUE THREAD

**Issue by opiipo0** [seerge/g-helper#1710]
When using my laptop, I have notice if I have to change the mode (Silent, performance, turbo) when I am playing a game in fullscreen, the Ghelper will not display my computer status. Recommend Ghelper team to add a feature that can display the mode the laptop is runing when the laptop is in full screen mode.

**Comment by opiipo0** [comment]
maybe there is, but I can't find it

**Comment by opiipo0** [comment]
ok, thank you

**Comment by seerge** [comment]
@opiipo0 hello,

I have found a way to show both overlay and OSD over old games.

Get latest (pre)release https://github.com/seerge/g-helper/releases 

And you need to place GHelper.exe into `C:\Program Files` folder. It's such weird windows requirement.

Thanks

**Comment by opiipo0** [comment]
Hello,

Thank you seerge for replying. Unfortunately , I have sold my Asus laptop.
I will definitely give a try when I get a new one in the future. Your
software is much more stable and efficient than Armory crate. Thank you for
remembering my suggestions!

Opiipo0

Serge ***@***.***>于2026年5月23日 周六下午8:22写道：
