### ISSUE TITLE
AniMe Matrix smooth dimming

### ISSUE THREAD

**Issue by KelseyHigham** [seerge/g-helper#1713]
**Is your feature request related to a problem? Please describe.**
When I'm using AniMe Matrix at night, or in a public place, I want to dim the Matrix to the point where it's not distracting. But the Dim setting is still too bright!

**Describe the solution you'd like**
I'd like a slider to artificially dim the Matrix by dimming the image itself before sending it to the Matrix. This wouldn't help with the brightness of built-in images and animations, but it would help with custom ones.

**Describe alternatives you've considered**
Replacing the discrete brightness values with a smooth slider, which automatically sets the Off/Dim/Medium/Bright values for the built-in animations, would be *really* cool.

**Additional context**
I've used a dimmed image on my Matrix, and it's a lot nicer. It takes up a negligible amount of battery, and it's not distracting, so I can leave it on full-time.
![waso-Keli-GH](https://github.com/seerge/g-helper/assets/286211/62e1865d-e1e4-4f25-8949-e62a6cfe49f5) <- too bright
![waso-Keli-bold-GH](https://github.com/seerge/g-helper/assets/286211/fa201258-c91c-437b-8792-4c760503edd4) <- just right

**Comment by seerge** [comment]
@KelseyHigham hello, this build should have a "Contrast" slider in Picture settings, which is effectively a multiplier for each pixel brightness. Just set it to something like 30% and you should be good
[GHelper.zip](https://github.com/seerge/g-helper/files/13624245/GHelper.zip)
