### ISSUE TITLE
Keyboard effects and colors

### ISSUE THREAD

**Issue by Maneeha1234SL** [seerge/g-helper#1714]
My laptop has a white backlight on the keyboard.
But Ghelper detects the presence of an RGB keyboard.
color cycle
Rainbow
heatmap
GPU Mode
ambient
There are several additional light patterns.
But nothing happens with those light patterns.

If possible, identify and provide the relevant keyboard for only the three light countries as shown in the image below

<img width="299" alt="Screenshot 2023-12-09 111530" src="https://github.com/seerge/g-helper/assets/83775004/59f23c3d-6123-4ac4-8a7f-5d20b50bf394">
<img width="297" alt="Screenshot 2023-12-09 111343" src="https://github.com/seerge/g-helper/assets/83775004/7c0b1d2a-b2d0-4e52-9f8d-fcbb9cc8987a">

Logs :-

12/9/2023 11:14:41 AM: ------------
12/9/2023 11:14:41 AM: App launched: ROG Zephyrus G15 GA503RM_GA503RM :0.136.0.0en-US
12/9/2023 11:14:42 AM: NVIDIA GeForce RTX 3060 Laptop GPU
12/9/2023 11:14:43 AM: CPU: 8 - AMD Ryzen 7 6800HS with Radeon Graphics          - AMD64 Family 25 Model 68 Stepping 1
12/9/2023 11:14:44 AM: AutoSetting for Online
12/9/2023 11:14:44 AM: Input: \\?\hid#vid_0b05&pid_19b6&col05#7&2635b6bc&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
12/9/2023 11:14:44 AM: Mode = 0 : OK
12/9/2023 11:14:44 AM: Power Mode 00000000-0000-0000-0000-000000000000:OK
12/9/2023 11:14:44 AM: Eco flag : 0
12/9/2023 11:14:44 AM: Mux flag : 1
12/9/2023 11:14:44 AM: \\?\DISPLAY#CMN1540#5&2b412772&2&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
12/9/2023 11:14:44 AM: \\?\DISPLAY#CMN1540#5&2b412772&2&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
12/9/2023 11:14:44 AM: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
12/9/2023 11:14:44 AM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
12/9/2023 11:14:44 AM: USB 19B6: 5D-B4
12/9/2023 11:14:44 AM: USB 19B6: 5D-B5-00-00-00
12/9/2023 11:14:44 AM: USB 19B6: 5D-B9
12/9/2023 11:14:44 AM: USB 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
12/9/2023 11:14:44 AM: USB 19B6: 5D-05-20-31-00-1A
12/9/2023 11:14:44 AM: Monitor Power On
12/9/2023 11:14:45 AM: Design Capacity: 90006mWh, Full Charge Capacity: 83630mWh, Health: 0.929160278203675310534853232%
12/9/2023 11:14:45 AM: Auto 19B6: 5D-BA-C5-C4-01
12/9/2023 11:14:45 AM: Auto Feature 19B6|63: 5A-BA-C5-C4-01
12/9/2023 11:14:45 AM: Latest version 0.136.0.0
12/9/2023 11:15:02 AM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
12/9/2023 11:15:02 AM: USB 19B6: 5D-B4
12/9/2023 11:15:02 AM: USB 19B6: 5D-B5-00-00-00
12/9/2023 11:15:04 AM: Key: 197
12/9/2023 11:15:04 AM: HotKey 19B6: 5D-BA-C5-C4-00
12/9/2023 11:15:04 AM: HotKey Feature 19B6|63: 5A-BA-C5-C4-00
12/9/2023 11:15:21 AM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
12/9/2023 11:15:21 AM: USB 19B6: 5D-B4
12/9/2023 11:15:21 AM: USB 19B6: 5D-B5-00-00-00

**Comment by seerge** [comment]
@Maneeha1234SL can you post a log from this build ?
[GHelper.zip](https://github.com/seerge/g-helper/files/13624196/GHelper.zip)

**Comment by seerge** [comment]
@Maneeha1234SL this build should mark your device as white-only
[GHelper.zip](https://github.com/seerge/g-helper/files/13624989/GHelper.zip)

**Comment by seerge** [comment]
@Maneeha1234SL cause it breaks RGB for other users with exactly same model and same keyboard version as yours https://github.com/seerge/g-helper/issues/1734

I'm sure you will survive with few extra options in a dropdown
