### ISSUE TITLE
Default GPU Mode changes at Standard mode rather than Eco mode on Boot.

### ISSUE THREAD

**Issue by pritamdas7** [seerge/g-helper#1715]
I have noticed that the default GPU Mode changes to "Standard" (iGPU+dGPU) when I restart my computer, even if I had previously changed it to "Eco" (iGPU only) mode. This issue occurs both when my laptop is plugged in and when it's running on battery power. Could you let me know if there's a fix for this?

I think Kikimahe meant this file:- 
[log.txt](https://github.com/seerge/g-helper/files/13623285/log.txt)

**Comment by Kikimahe** [comment]
Hi, 

Edit your post and add Ghelper's **log.txt**.
`C:\Users\*yourname*\AppData\Roaming\GHelper`

Drag and drop the file following your text.

Otherwise Seerge won't be able to see what's happening.

**Comment by seerge** [comment]
@pritamdas7 hello. This is how your firmware / BIOS is programmed by ASUS. They have decided that it's better to always boot with enabled GPU.

If you want app to forcely change GPU mode, you can either set Optimized mode (it will simply disable GPU every time laptop is on battery, including when it's being restarted)

Or manually add 
```
"gpu_mode_force_set": 1,
```

In ``config.json`` of the app, then it will force last used mode on start
