### ISSUE TITLE
Dgpu runs on eco mode

### ISSUE THREAD

**Issue by ROY-DAG** [seerge/g-helper#1717]
Dear Serge

My dgpu runs always when i start my pc, even when i am on eco mode. I must manually change form eco to standart and back to eco to disable it. I use a Zhyperhus G15 GA503RW (BIOS 131) with the latest g-helper version (0.134.0), deleted myasus, armoury crate and disabled via g-helper all asus services.
I tried to reset my sytem and it didnt help, the only thing that worked was to use the old BIOS (311) but then i had other problems with wlan, battery limit etc.

My log : 
[log.txt](https://github.com/seerge/g-helper/files/13624556/log.txt)

The screenshot is after i searchet for the log
[
<img width="889" alt="Screenshot 2023-12-09 163523" src="https://github.com/seerge/g-helper/assets/153376666/aa0dd04b-de02-42c1-9db7-ad95fcf53401">
](url)

Thank you for your time

**Comment by seerge** [comment]
@ROY-DAG hello, it's probably bugs in asus BIOS on your model :)

As BIOS itself reports GPU to be off 

```
09.12.2023 15:32:34: NVIDIA GeForce RTX 3070 Ti Laptop GPU <---- WINDOWS DRIVE SAYS GPU IS ON
09.12.2023 15:32:35: CPU: 8 - AMD Ryzen 7 6800HS with Radeon Graphics          - AMD64 Family 25 Model 68 Stepping 1
09.12.2023 15:32:35: AutoSetting for Offline
09.12.2023 15:32:35: Input: \\?\hid#vid_0b05&pid_19b6&col05#7&2635b6bc&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
09.12.2023 15:32:35: Mode = 2 : OK
09.12.2023 15:32:35: Eco flag : 1 <--- BIOS SAYS GPU IS OFF
09.12.2023 15:32:35: Mux flag : 1
```

I would recommend just set standard and back to eco again, and if it doesn't help - you can do [hardware reset](https://github.com/seerge/g-helper#how-do-i-do-a-hardware-reset-on-a-laptop) . As a last resort you can  or may be try older BIOS version ? :)

Anyway, I can't help here anyhow, as asus endpoints in BIOS say ECO is on :)
