### ISSUE TITLE
TUF A15 2023 battery charge limit not working over 80%

### ISSUE THREAD

**Issue by arifesat** [seerge/g-helper#1718]
I can use the charge limit when I set it to 80% but I can't use it with over 80 or below 50.

Using version 0.134.0

Device is TUF A15 FA507NU

[log.txt](https://github.com/seerge/g-helper/files/13625280/log.txt)

**Comment by seerge** [comment]
@arifesat hello, because your device simply doesn't support anything else probably :) that happens

**Comment by arifesat** [comment]
I'd like to use 85% cap but that's ok I guess. Thanks anyways. Great project!
