### ISSUE TITLE
Battery Charger Limiter

### ISSUE THREAD

**Issue by Yusuf8810** [seerge/g-helper#1719]
Battery Charge Limiter isn't working

A set it to 80% but it goes above that and reaches 100%

[log.txt](https://github.com/seerge/g-helper/files/13626044/log.txt)

![image](https://github.com/seerge/g-helper/assets/69922444/59708a81-2676-4894-ac3f-44a460cb39b9)

 - OS:Windows 11
 - Asus TUF A15 FA507NV

**Comment by seerge** [comment]
@Yusuf8810 hello, if laptop has already charged to 100% it won't discharge to 80 of course :)) You need to discharge it by yourself.

Also keep in mind, that some models BIOS forgets setting, and will start charging laptop when you reboot it for example (till the moment windows loads, and g-helper starts)

**Comment by Yusuf8810** [comment]
It was not happening in the previous version. And yes, even when I discharge it, it still exceeds 80%

**Comment by seerge** [comment]
@Yusuf8810 there is no change in this setting in the app for last year or so :)

**Comment by Yusuf8810** [comment]
Weird. I will try to downgrade and see how it goes.

**Comment by seerge** [comment]
@Yusuf8810 anyway, whole "charge limit" is literally 1 powershell command

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00120057, 80)
```

You can't do anything more than that, and app does exactly same thing on start / wake up :)

Good luck checking
