### ISSUE TITLE
Bug with ui on TUF laptops

### ISSUE THREAD

**Issue by LJGJM** [seerge/g-helper#172]
**Describe the bug**
Bug on TUF keyboard rgb

**To Reproduce**
1. change your keyboard RGB to breathing.
2. Click on 'the secondary rgb color'
3. change it
4. See error (nothing happens)

**Screenshots**
![image](https://user-images.githubusercontent.com/88922474/229084646-7deee98b-b91a-4205-a81a-fac05a2a8109.png)

**Expected behavior**
The option wouldnt be available
![image](https://user-images.githubusercontent.com/88922474/229085949-b01697fe-4e8b-4f21-a72f-e95a8de5be4b.png)

**Desktop (please complete the following information):**
 - OS: Win 10 Enterprise 20h2 19042.631
 - ASUS TUF Gaming A15 FA506IHRB 2021
 
**Additional context**
the keyboard doesnt support this option

**Comment by seerge** [comment]
What about newer TUFs ? (like from 2022 or 2023 even?)

**Comment by LJGJM** [comment]
> What about newer TUFs ? (like from 2022 or 2023 even?)

I dont have the 2022/3 version so i cant test it but they should have the same keyboard

**Comment by LJGJM** [comment]
> Anyway I have added a check for a TUF in model name in 0.44 . And if it exists - it will hide second color.

Thanks!
