### ISSUE TITLE
Backup option for curves and custom modes and OCs

### ISSUE THREAD

**Issue by alexonpeace** [seerge/g-helper#1720]
**Is your feature request related to a problem? Please describe.**
Kinda I suppose since if I change ram, or windows bsods, ghelper resets to default which is super annoying since I do a lot of customizing 

**Describe the solution you'd like**
a one click backup/restore feature would be great

**Describe alternatives you've considered**
copying and pasting the config from Appdata folder, but it's annoying

**Comment by seerge** [comment]
@alexonpeace you would lose config only if app was writing something in it in a moment of the crash, which is difficult by definition. 

What is the difficulty in making a bat file copying config?
