### ISSUE TITLE
[Question] Undervolting with Memory Integrity and Virtual Machine Platform on Windows 11

### ISSUE THREAD

**Issue by BynariStar** [seerge/g-helper#1725]
Does the undervolting feature work when Memory Integrity and/or Virtual Machine Platform are enabled? I recall ThrottleStop running into the issue where it wouldn't work on Windows 11 (though not Windows 10) when these features were enabled.

Thanks!

**Comment by seerge** [comment]
@BynariStar it should work i think :) you are free to test
