### ISSUE TITLE
Too many features on ASUS ROG Flow Z13 Acronym

### ISSUE THREAD

**Issue by JohnJohn45** [seerge/g-helper#1728]
Hello, and sorry for my poor English

**Describe the bug**
Too many features for Z13 ASUS ROG Flow Z13 Acronym with software 0137 and previous

All feature in red circle don't exist on this model.
Keyboard backlight is only white
No logo or hood with backlight on this model

<img width="694" alt="Capture d'écran 2023-12-12 095235" src="https://github.com/seerge/g-helper/assets/26327298/45e41bdb-ad00-475c-ae3b-2983396893e9">

**Expected behavior**
I don't want to see this feature

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/13645976/log.txt)

**Desktop (please complete the following information):**
Windows 11
ASUS ROG Flow Z13 Acronym

**Asus software**
- Armoury Crate (or it's services installed) -->no
- MyASUS installed --> no
- Other Asus services running in background --> no

**Comment by seerge** [comment]
@JohnJohn45 hello, do ALL Arconym models come w/o RGB and that back-window on the case ?

**Comment by JohnJohn45** [comment]
As far as I know there is only one Z13 acronym model with regional variation (azerty, qwerty...) none of them have any RGB and all have white only Backlit Keyboard.

**Comment by seerge** [comment]
@JohnJohn45 this build should hide unsupported backlight options for you then

[GHelper.zip](https://github.com/seerge/g-helper/files/13647509/GHelper.zip)

**Comment by JohnJohn45** [comment]
Yes, it's ok with this build. Thank you.
