### ISSUE TITLE
Small list of problems found on my platform.

### ISSUE THREAD

**Issue by Magniflex99** [seerge/g-helper#173]
I have an Asus Rog G532LWS, tenth generation Intel and Nvidia RTX 2000. I state that for using this program I have uninstalled all the previous Asus software, and disabled the few remaining services. In activity management, I no longer have any service that refers to Asus, and every software and driver left in Windows 11 Home is updated to the latest version available. I will list in bullet points all the problems and shortcomings that I have encountered in this version.

-The gpu fan, in some cases, stops for no apparent reason. I couldn't find a direct cause for this, but most of the time it happens when I switch from one profile to another (Manual-Performance-Turbo-Silent). I also had this problem in Armoury Crate, but much less frequent.

-It would be useful to introduce an option that can disable CPU turbo boost, depending on the fan management mode selected. For example, in "silent" mode, it would save battery, and reduce the heat generated, as well as further reduce fan rotation and consequently the noise generated.

-The CPU Boost is applied globally to all profiles, and not as a setting of the current profile that has been decided to modify.

-On the main screen, it would also be useful to see the temperature of the GPU, in addition to that of the CPU, such as the total RAM memory usage, and the capacity of the disks in %.

-It would be useful and nice, to have in the program settings, a link that can redirect you to the GitHub page of the same, or even better, to its download page, to check the possible availability of new versions.

-The program, when the PC screen is deactivated (NO SUSPENSION-NO HIBERNATION ONLY DISPLAY STANDBY), no longer has control over the rotation of the fans, which decreases a lot. Once the screen is reactivated, the fans stop and then restart normally, on the profile set in the program.

-The section, concerning the customization of the RGB backlight of the Notebook keyboard, is in my opinion to be reviewed. ' very clear operation, and the amount' of selectable effects, and' quite lacking.

-It would be useful to have a setting to automatically select the type of profile to use, based on the power supply of the notebook, or the type of program running.

-It would be useful to have available the customization of some keys, according to which, to be able to recall and activate a certain profile, or recall the program practically as it happens in Armoury Crate).

-No support for other languages (it's not a problem for me, but it would be a feature that would surely enrich the value of this project, and I'd be willing to offer full support for Italian translation).

These are all the critical points I have been able to identify so far. The same problems were also present in the previous version. I have not put in order of importance the points listed above, and I hope not to be out of place, for having also included shortcomings, being still in full development, I hope it can still improve a lot. There would be many things to put in, such as the presence of a MUX Switch. I conclude by congratulating seerge, for the great commitment, because this is exactly what every owner of an ROG Notebook would need, and I will not fail to actively support this project, if it continues to improve over time.

**Comment by Magniflex99** [comment]
> > I have an Asus Rog G532LWS, tenth generation Intel and Nvidia RTX 2000. I state that for using this program I have uninstalled all the previous Asus software, and disabled the few remaining services. In activity management, I no longer have any service that refers to Asus, and every software and driver left in Windows 11 Home is updated to the latest version available. I will list in bullet points all the problems and shortcomings that I have encountered in this version.
> > -The gpu fan, in some cases, stops for no apparent reason. I couldn't find a direct cause for this, but most of the time it happens when I switch from one profile to another (Manual-Performance-Turbo-Silent). I also had this problem in Armoury Crate, but much less frequent.
> 
> If that happens without any clear reproduceable scenario - I would advice not to apply any custom fan curves, and use default (i.e. auto apply checked OFF)
> 
> > -It would be useful to introduce an option that can disable CPU turbo boost, depending on the fan management mode selected. For example, in "silent" mode, it would save battery, and reduce the heat generated, as well as further reduce fan rotation and consequently the noise generated.
> 
> App already saves CPU boost per each mode, just set it once and it will be remembered (as this was asked numerous times by different users)
> 
> > -The CPU Boost is applied globally to all profiles, and not as a setting of the current profile that has been decided to modify.
> > -On the main screen, it would also be useful to see the temperature of the GPU, in addition to that of the CPU, such as the total RAM memory usage, and the capacity of the disks in %.
> 
> App already tries to read and show GPU temp (and actually does in 99% cases). If in your case it's not accessible, i can't help much, it gets it either from bios or from GPU driver
> 
> > -It would be useful and nice, to have in the program settings, a link that can redirect you to the GitHub page of the same, or even better, to its download page, to check the possible availability of new versions.
> 
> It's already the case for a long time. App checks for a new updates on start (and version label will become red and mention new download) . Version label itself is a link to github
> 
> > -The program, when the PC screen is deactivated (NO SUSPENSION-NO HIBERNATION ONLY DISPLAY STANDBY), no longer has control over the rotation of the fans, which decreases a lot. Once the screen is reactivated, the fans stop and then restart normally, on the profile set in the program.
> 
> App doesn't control fan speeds, your bios does. If it decides to stop fans when screen is off / laptop is going to sleep - this is how it is set there. https://github.com/seerge/g-helper#how-does-g-helper-control-my-fan-speeds
> 
> > -The section, concerning the customization of the RGB backlight of the Notebook keyboard, is in my opinion to be reviewed. ' very clear operation, and the amount' of selectable effects, and' quite lacking.
> 
> App lists all known BUILT IN effects. Does your keyboard support mode built in options?
> 
> > -It would be useful to have a setting to automatically select the type of profile to use, based on the power supply of the notebook, or the type of program running.
> 
> App already remembers mode per plugged/battery states and does auto switch every time. Just set correct mode once.
> 
> > -It would be useful to have available the customization of some keys, according to which, to be able to recall and activate a certain profile, or recall the program practically as it happens in Armoury Crate).
> 
> You can use FN+F5 (or bind M4) to cycle through modes, please check readme
> 
> > -No support for other languages (it's not a problem for me, but it would be a feature that would surely enrich the value of this project, and I'd be willing to offer full support for Italian translation).
> > These are all the critical points I have been able to identify so far. The same problems were also present in the previous version. I have not put in order of importance the points listed above, and I hope not to be out of place, for having also included shortcomings, being still in full development, I hope it can still improve a lot. There would be many things to put in, such as the presence of a MUX Switch. I conclude by congratulating seerge, for the great commitment, because this is exactly what every owner of an ROG Notebook would need, and I will not fail to actively support this project, if it continues to improve over time.

Understood. Thank you for the clarification and I apologize if I was not properly informed. It's recently that I decided to switch to GHelper, and I'm afraid I missed some features during use...

**Comment by seerge** [comment]
@Magniflex99 you may also want to try https://github.com/seerge/g-helper/releases/tag/v0.44 where i have extended AURA dropdown with more built in modes that i was able to find for strix/scar models.

**Comment by Magniflex99** [comment]
> @Magniflex99 you may also want to try https://github.com/seerge/g-helper/releases/tag/v0.44 where i have extended AURA dropdown with more built in modes that i was able to find for strix/scar models.

I'll download immediately, and if I ever encounter REAL critical issues, I won't hesitate to report them to you! However, already now, I can tell you that the thing I find least intuitive is the backlight management interface. I think however, it is not easy to find a graphic design that is easy to integrate, and compatible with most of the Rog notebooks. To be clear, something similar to the Armory Crate interface dedicated to backlighting (Aura Crate is too complicated and confusing, I don't need to waste hours googling with the lights!).

**Comment by seerge** [comment]
Ok. Backlight "interface" is just a dropdown of all supported modes. If you have better and specific ideas you can create a feature suggestion with details.

I'm closing this issue as there is nothing to fix atm.
