### ISSUE TITLE
[flow z13] remove gpu mode selection for models without dGPU

### ISSUE THREAD

**Issue by Bobla-2** [seerge/g-helper#1730]
I have laptop without discrete GPU, only iGPU, therefore GPU mode selection useless, can you remove this chose for users with same laptops?

![image](https://github.com/seerge/g-helper/assets/103276078/c14f3dcf-37c9-4594-b37e-eb5994d61686)

**Comment by seerge** [comment]
@Bobla-2 hello, app shows GPU modes section if your system has endpoint to turn dGPU on or off. 

Apparently in your case it exists for a reason :) Same as with ROG Ally (there it also exists). It could be the case for XG Mobile connection and management.

So it's better to keep UI accessible just in case, as it doesn't harm ;)
