### ISSUE TITLE
2022 G15 (GA503RM) Keyboard RGB not available on 0.137

### ISSUE THREAD

**Issue by nbeh1** [seerge/g-helper#1734]
**Describe the bug**
Keyboard RGB mode (rainbow, color cycle, etc.) not available after updated g-helper to 0.137, only static, strobe and breathe left.
GA503RM does support keyboard backlight RGB, just not per-key RGB.

**Clear scenario to Reproduce**
1. Update g-helper to 0.137
2. Keyboard RGB mode gone

**Expected behavior**
Able to set keyboard to other RGB backlight modes.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13659400/log.txt)

**Screenshots or screencasts**
0.136
![image](https://github.com/seerge/g-helper/assets/139955754/882c49e3-a31a-4b75-abe6-5b9dbf01d599)
0.137
![image](https://github.com/seerge/g-helper/assets/139955754/1119899b-0265-45f4-8107-745894e215f5)

**Desktop (please complete the following information):**
 - Windows11
 - G15 2022 (GA503RM)

**Asus software**
-None

**Comment by seerge** [comment]
@nbeh1 hello, I assume this is due to this user with exactly same model as yours and more over, with same keyboard version
https://github.com/seerge/g-helper/issues/1714

All this requests are extremely confusing.

**Comment by seerge** [comment]
@nbeh1 this build should revert the changes
[GHelper.zip](https://github.com/seerge/g-helper/files/13659448/GHelper.zip)

**Comment by nbeh1** [comment]
> @nbeh1 this build should revert the changes [GHelper.zip](https://github.com/seerge/g-helper/files/13659448/GHelper.zip)

I suspect the model might have different specs in different countries? 

Thank you as always!

**Comment by seerge** [comment]
@nbeh1 I have just pushed it as a hotfix to 0.137 , so you can just re-download it
