### ISSUE TITLE
Have keyboard flash every 0.5s when charger is unplugged but dGPU is on

### ISSUE THREAD

**Issue by zakimohzani** [seerge/g-helper#1735]
**Is your feature request related to a problem? Please describe.**
So imagine that my G14 2022 is plugged to a USB-C charger and a TV. Once in awhile, G-helper detects that the USB-C charger is disconnected for just 1 second, so it flips to "Eco" mode and then flips back to "Optimised" mode. Unfortunately, this option "Stop all apps using GPU when switching to Eco" is ticked. I mean it's a great option and it has prevented me from draining the battery quickly. But it will actually kill any application that uses the dGPU. For example, I'm playing a game and then the glitch happens and then suddenly my game is dead.

**Describe the solution you'd like**
I would like to untick "Stop all apps using GPU when switching to Eco" but I need a notification that my dGPU is still ON whilst the laptop is on battery mode. So the solution is to make the keyboard flash frequently. That way I know that the dGPU is still engaged and I should kill an application. However, if it is just a glitch, I know that yes, I'm on battery but I can just wait 1-2 seconds until the USB-C charger re-engages.

**Describe alternatives you've considered**
The laptop keyboard option labeled "GPU Mode" does help but sometimes my brain can ignore a static colour.

**Additional context**

**Comment by seerge** [comment]
@zakimohzani hello, I'm afraid your use case is extremely exotic :) 

If you have unstable power supply or usb just set your GPU mode to Standard, and it won't turn off at all 

Good luck

**Comment by zakimohzani** [comment]
Hey seerge, I know that but if I unplugged the charger and forget to set it back to Eco or Optimised, I would drain my battery in minutes

**Comment by seerge** [comment]
@zakimohzani i understand :) but if I will be adding such "fixes" for everyone from 60K users app currently have, it will render it into unusable heavy bloat

**Comment by zakimohzani** [comment]
OK, I see. Then is it possible for me to change the keyboard colours of the various GPU modes via a text file or Windows registry key? That way I can experiment with some colours which might catch my attention better. 
________________________________

**Comment by zakimohzani** [comment]
@seerge another question. With regards to the keyboard's GPU mode. Is it possible to make it be based on whether the dGPU is on or off? For example, if dGPU is ON, keyboard is red. if dGPU is OFF, keyboard is green. So instead of it being based on user-selected modes, it will be based on the state of the dGPU.
