### ISSUE TITLE
Getting flagged by Windows Defender

### ISSUE THREAD

**Issue by kaelib12** [seerge/g-helper#1738]
<img width="376" alt="image" src="https://github.com/seerge/g-helper/assets/51917083/bf5fb27c-1a3c-4abc-9963-b36bf161c7d0">

Getting this when downloading the newest update

**Comment by seerge** [comment]
@kaelib12 this question was already answered many times, and is covered in FAQ

> Windows Defender marks app as malware / virus
False positives from Windows Defender (or any other similar system that uses machine learning for detection) is possible as the application is not digitally signed with a certificate. You can always download a version below or compile the app by yourself. All application sources are open and can be monitored from A to Z :)
