### ISSUE TITLE
The keyboard backlight turns off when the laptop is unplugged

### ISSUE THREAD

**Issue by 1hvh** [seerge/g-helper#1739]
[log.txt](https://github.com/seerge/g-helper/files/13663940/log.txt)
**Describe the bug**
The keyboard backlight turns off when the laptop is unplugged. (after update to 0.137.0)
Attempts to fix:
1. Stop all Asus services
2. Some attempts with "Laptop blacklight" slider - absolutely nothing (works fine when plugged in)
3. Change light intension using hotkeys (fn+arrow_up/fn+arrow_down)
4. Check/uncheck all checkboxes in "Laptop blacklight" group.

(The backlight turns on immediately after the GHelper.exe process completes)

P.S. In "Plugged in" mode everything works stably and correctly

**Clear scenario to Reproduce**
1. Start GHelper.
2. Unplug laptop
3. shit happens (keyboard lighting turns off)

**Expected behavior**
1. Start GHelper.
2. Unplug laptop
3. nothing happened to keyboard lighting

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/34618575/924cc585-8c5d-4f5a-b2bb-cec21a0ca523)

**Desktop (please complete the following information):**
 - OS:  Windows 11 Pro 10.0.22621 Build 22621
 - ASUS TUF GAMING F15 FX506HC

**Asus software**
- Armoury Crate fully uninstalled
- MyASUS installed
- No other Asus services running in background

**Comment by seerge** [comment]
@1hvh hello, app remembers last used backlight brightness when plugged in and on battery.

It just means that before that you had backlight brightness on battery set to 0, and this is exactly what app has set when you unplugged

```
12/13/2023 10:39:34 PM: AutoSetting for Offline
12/13/2023 10:39:35 PM: Input device not found
12/13/2023 10:39:35 PM: Mode = 0 : OK
12/13/2023 10:39:35 PM: GPU usage: NVIDIA GeForce RTX 3050 Laptop GPU 0%
12/13/2023 10:39:35 PM: BatteryLimit = 100 : OK
12/13/2023 10:39:35 PM: TUF_KB = 16712125 : OK
12/13/2023 10:39:35 PM: TUF RGB = B4-00-FF-FF-FF-EB : OK
12/13/2023 10:39:35 PM: Running eco command 1
12/13/2023 10:39:38 PM: GPUEco = 1 : OK
12/13/2023 10:39:38 PM: TUF Brightness = 128 : OK  --> BRIGHTNESS SET TO 0 (128 is 0, 131 i maximum)
```

So everything works as it should :)
