### ISSUE TITLE
Detect only dimmable white color keyboard on GA502IU

### ISSUE THREAD

**Issue by nicola02nb** [seerge/g-helper#1740]
**Describe the bug**
The software is not detecting that my laptop has an only dimmable white color keyboard.

**Clear scenario to Reproduce**
1. Opening software

**Expected behavior**

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13664556/log.txt)

**Screenshots or screencasts**
![Screenshot 2023-12-13 195904](https://github.com/seerge/g-helper/assets/61830443/9b470de9-ebae-4a57-bd44-faef26739056)

**Desktop:**
 - OS: Windows 11
 - Zephyrus G15 GA502IU

**Asus software**
- Armoury Crate (or it's services installed)
- MyASUS installed
- No Asus services running in background

**Comment by seerge** [comment]
@nicola02nb hello, this build should hide color options

[GHelper.zip](https://github.com/seerge/g-helper/files/13666197/GHelper.zip)

**Comment by nicola02nb** [comment]
@seerge it the build works, thanks.

I think also that the effects dropdownlist should be rmoved in my case because It doesn't/won't work on this model.

![Screenshot 2023-12-14 001254](https://github.com/seerge/g-helper/assets/61830443/605a9123-d15e-4bc8-8e61-5b9c098812ae)

**Comment by seerge** [comment]
@nicola02nb which ones are not supported in the list ?

**Comment by nicola02nb** [comment]
@seerge Evryone, in my laptop version the keyboard is only dimmable, it comes without any effect.
