### ISSUE TITLE
hi, what is the meaning of 'Added M16, G16 2023 to the list of devices that support GPU enabling on shutdown'

### ISSUE THREAD

**Issue by briliggt** [seerge/g-helper#1741]
My computer is the ROG M16 2023, so maybe this choice is useful for me, but I can't understand what the meaning 
![image](https://github.com/seerge/g-helper/assets/143986920/7987f4d1-3f28-4ae5-a05b-e9692343d81d)

**Comment by seerge** [comment]
@briliggt hello, you can check what it's about here https://github.com/seerge/g-helper/discussions/1042 :)
