### ISSUE TITLE
G-helper compatibility with MyAsus?

### ISSUE THREAD

**Issue by mahmouddello** [seerge/g-helper#1742]
Hello sergee, I just wanted to know if g-helper compatible with MyAsus.
I saw that in MyAsus the battery charging limit is on full capacity mode, while on g-helper the battery limit charging was %80.
Another question how g-helper really calculate the battery health? my laptop is like 4 months old and the battery health shown as %88, is that normal while i have a limit for charging always?
Thanks in advance.

**Comment by seerge** [comment]
@mahmouddello hello, your question is already covered in FAQ
https://github.com/seerge/g-helper?tab=readme-ov-file#can-i-use-the-myasus-app-along-with-g-helper

Battery health is taken from windows, and based on your current and maximum capacity. You can run HWINfo to compare and verify if you want

**Comment by Kikimahe** [comment]
> my laptop is like 4 months old and the battery health shown as %88, is that normal while i have a limit for charging always?

This is normal battery wear.
https://www.asus.com/support/FAQ/1038475/
