### ISSUE TITLE
M1 & M2 hotkeys are not working as expeceted

### ISSUE THREAD

**Issue by bxfy1** [seerge/g-helper#1743]
**Describe the bug**
Non-default key bindings for M1 and M2 are not working. Under extra settings, no matter what it is set to (Custom/Volume Mute/PrintScreen and so on...), it will only send Volume_Down and Volume_Up events respectively. Strangely, M3 and M4 does not have this issue. Also note that the hidden extra keybindings (Ctrl + M1 / M2 - Screen brightness Down / Up, Shift + M1 / M2 - Backlight brightness Down / Up) are working so it definitely can see M1 and M2 keys.

**Snip configs from %AppData%\GHelper\config.json**
  "m1": "custom",
  "m1_custom": "0x7C",
  "m2": "custom",
  "m2_custom": "0x7D",

**Snip logs from `%AppData%\GHelper\logs.txt**
2023/12/15 11:17:51 AM: Couldn’t register VolumeDown
2023/12/15 11:17:51 AM: Couldn’t register VolumeUp

**G-Helper version**
0.137.0

**Desktop**
 - OS: Windows 10 Home, 22H2, Build 19045.3803
 - Flow X13 2021 (GV301QE)

**Asus software**
- Armoury Crate: not installed
- MyASUS: not installed
- Other Asus services running in background: 0

**Comment by seerge** [comment]
@bxfy1 the answer is in your log literally

```
2023/12/15 11:17:51 AM: Couldn’t register VolumeDown
2023/12/15 11:17:51 AM: Couldn’t register VolumeUp
```

Windows is not allowing app to make bindings from ``Vol up`` / ``Vol down``. May be this is a quirk of your windows 10 ? Anyway I can't help, as this is a problem on the side of your windows here
