### ISSUE TITLE
Option to bind GPU fan to CPU temp when using XGM

### ISSUE THREAD

**Issue by norwayman22** [seerge/g-helper#1746]
**Is your feature request related to a problem? Please describe.**
I got the the 2021 Supernova Edition x13 (5980hs) with a 3080 XGM and when gaming it's pretty easy to hit a CPU bottleneck, with the CPU temp reaching its 97 degree max. Whenever that happens, the CPU fan is blowing at full speed, but the GPU fan isn't, because the dGPU is not being used. Using the XGM, this doesn't make much sense as the only job of the two internal fans should be to cool the CPU (Internally, they are connected to heat pipes going over both the CPU and dGPU.

**Describe the solution you'd like**
I would like a setting to be able to bind the GPU fan speed to the CPU temp when using the XGM, so that both internal fans spin at the same speed (in percentage at least, since i'm pretty sure their RPMs differ). That way the entire laptop cooling gets utilized to cool the CPU.

**Describe alternatives you've considered**
I could increase the GPU fan curve of course, however the dGPU isn't in use, and so the temp delta isn't really high enough for the GPU fan to be able to spin fast while gaming, and slow when doing other things.

**Comment by seerge** [comment]
@norwayman22 hello,

That is physically impossible unfortunately, as neither G-Helper nor AC don't control fans directly anyhow, they are controlled by BIOS (based on default or custom fan curves)

You can try to set a very aggressive GPU fan curve, that may solve your problem :)
