### ISSUE TITLE
Do not switch to Turbo/higher hz on USB-C charging

### ISSUE THREAD

**Issue by johnrobledo** [seerge/g-helper#1750]
Hello. I would like to request the option to not switch to turbo and a higher screen hz on USB-C PD, similar to the option that prevents GPU swap. Thanks.

**Comment by seerge** [comment]
@johnrobledo hello. App remembers last used mode for both cases, when plugged in and on battery, so just set it once to something else from Turbo while being plugged in, and it will use that next time too :)

**Comment by johnrobledo** [comment]
Hi. Hi! I understand that but does it remember different settings for USB-C
and regular barrel charging, like it can for t he gpu setting? That is what
I wanted, so that it would stay on silent for USB-C but on barrel charging
swap to turbo automatically

**Comment by johnrobledo** [comment]
Because it doesnt do so for me

**Comment by seerge** [comment]
@johnrobledo no, it doesn't. But I don't want to overcomplicate things, it's extremely easy to switch between the modes now. Fn+F5 / Fn+Shift+F5 - forwards / backwards :)
