### ISSUE TITLE
CPU Slow (sPPT) Limit doesn't apply

### ISSUE THREAD

**Issue by jontomy** [seerge/g-helper#1753]
**Describe the bug**
When applying a CPU power limit the sPPT slider is ignored and all limits (fast, slow, sustained) are set to the value the SPL slider is set to.

**Clear scenario to Reproduce**
1. Go to Fans+Power, CPU tab
2. Change values of the SPL and sPPT sliders
3. Saturate CPU and observe the CPU PPT, or check the CPU Power Sensors

**Expected behavior**
Slow power limit being applied.

**App Logs**
This is what gets logged when I change the SPL and sPPT sliders to 20W and 30W respectively:
_17-Dec-23 2:07:50 PM: STAPM: 20 OK
17-Dec-23 2:07:50 PM: STAPM2: 20 OK
17-Dec-23 2:07:50 PM: SLOW: 20 OK
17-Dec-23 2:07:50 PM: FAST: 20 OK
17-Dec-23 2:07:50 PM: UV: -30 OK_

And this is what gets written on the config file:
  _"limit_total_1": 20,
  "limit_slow_1": 30,
  "limit_cpu_1": 19,
  "limit_fast_1": 125,
  "auto_apply_power_1": 1,_

**Screenshots or screencasts**
<img width="937" alt="Screenshot 2023-12-17 140405" src="https://github.com/seerge/g-helper/assets/135830574/2101e0cf-9b4e-4439-aedf-49923791f0b8">

Here I tried to set the SPL to 20W and the sPPT to 30W. As can be seen from the HWiNFO when stressing the CPU it just goes directly to 20W and stays there. Checking the CPU Power Sensors with Renoir Mobile Tuning, it can be seen that all 3 limits (STAPM, PPT LIMIT FAST and PPT LIMIT SLOW) are set to 20W

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: ROG Zephyus G14 GA401IV
 - CPU: AMD Ryzen 7 4800HS

**Asus software**
- No Armoury Crate or MyASUS installed
- No other Asus services running in background

**Additional context**
I'm using Turbo as the base preset so there are no "hidden" limits.

Using Renoir Mobile Tuning I can set a Slow Limit of 30W and a Sustained Limit of 20W and it will get properly applied and work as intended.

<img width="960" alt="Screenshot 2023-12-17 140646" src="https://github.com/seerge/g-helper/assets/135830574/3d6df6ad-7c66-47cb-82c7-2c8aa01bf719">

**Comment by seerge** [comment]
@jontomy hey, this is just a side effect of a newly added slider :) you actually shouldn't see it on your device.

For models that don't support CPU limits via asus native way, i use UXTU's approach, and just set same (sustained) limit to all 3 values 

```
17-Dec-23 2:07:50 PM: STAPM: 20 OK
17-Dec-23 2:07:50 PM: STAPM2: 20 OK
17-Dec-23 2:07:50 PM: SLOW: 20 OK
17-Dec-23 2:07:50 PM: FAST: 20 OK
```

Do you really need a separate sliders for SPL / SPPT / FPPT ?

**Comment by jontomy** [comment]
I see, I just thought to test the newly added slider and realized it wasn't applying on my machine.

Yes, I don't think it's really needed to have the separate sliders, anyway it's quite easy it's to change the one slider if/when necessary. Wouldn't hate to have the three sliders there since one can simply choose to not touch them, but don't think it's necessary to spend the time to implement it.

I guess just hiding the slider for the devices where it doesn't do anything is fine. Thank you for you time!

**Comment by seerge** [comment]
@jontomy hello, I think it will be easier to keep things simple for devices where there is no dedicated asus endpoints for SPL/SPPT/FPPT :)

This build should just hide new slider for your case : 

[GHelper.zip](https://github.com/seerge/g-helper/files/13697391/GHelper.zip)
