### ISSUE TITLE
ROG Button(Customed to PrtSC) is not triggered when press with more than one time. need to press Fn+F6(M16 is PrtSC) again then the M4 will be triggered.

### ISSUE THREAD

**Issue by LeonardoYang** [seerge/g-helper#1754]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**

**Clear scenario to Reproduce**
Steps to reproduce the behavior:(software: Snipaste)
1. Go to G-help, extra,
2. Click on M4 to CUSTOM, then set the key value to 0x2C(PrtSC)
3. Press M4 for one time, will trigger normally
4. then press again, it won't trigger normally.
5. Press Fn+F6(which is the default PrtSC in M16), it can trigger normally.
6. then Press M4 for PrtSC, it can be re-activated.
7. Press M4 again, it won't trigger the PrtSC.

**Expected behavior**
The M4 which be set to CUSTOM(0x2C) should trigger normally everytime. in logs, Fn+F6 triggers PrtSC which is right and M4 should also triggers the same (which in logs is 56, not PrtSC);

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
log file: 
[log.txt](https://github.com/seerge/g-helper/files/13696894/log.txt)

**Screenshots or screencasts**
ScrennShot:
[image](https://github.com/seerge/g-helper/assets/15136678/53ae45fd-a7c8-4d3e-9ffc-61dcb42fe6ab

**Desktop (please complete the following information):**
 - OS: win 11 23H2 bulid(22631.2792)
 - Laptop ASUS ROG M16 2023 GU604VI

**Asus software**
None, clean install

**Additional context**

Great Thanks

**Comment by seerge** [comment]
@LeonardoYang hello. How do you check if it's working or "it won't trigger normally" ?

Log shows what event came to the app (i.e. what key was pressed) not what happens after

**Comment by LeonardoYang** [comment]
@seerge In the log, it shows 56 not PrtSC, my suppose is that if the value of the key is not right?

**Comment by seerge** [comment]
@LeonardoYang 56 is a keycode of M4 as I have mentioned.

**Comment by LeonardoYang** [comment]
@seerge Then I think the key is right triggered. I will look into the Application level. Great thanks anyway.

**Comment by LeonardoYang** [comment]
I tested with usb external keyboard, it can trig right everytime. :=)
