### ISSUE TITLE
Eco Mode Inconsistency and GPU Activation in Zephyrus G15 GA503 with BIOS 313/315

### ISSUE THREAD

**Issue by Maneeha1234SL** [seerge/g-helper#1755]
Description:
I am encountering an issue with the Eco Mode functionality on the Zephyrus G15 GA503 laptop, specifically when the computer is started after being in hibernation or shut down. The problem manifests as follows:

Problem:

After resuming from hibernation or starting up from a shutdown with Eco Mode enabled, the dedicated GPU (dgpu) activates, despite Eco Mode being selected.

Attempting to resolve this issue involves following a set of steps outlined in a video, which is cumbersome and inconvenient.

Video :- https://clipchamp.com/watch/DL5Daree1By

Suggested Solution:
To address this problem, I propose the following solution:

Implement a mechanism to forcibly switch to Standard Mode if Eco Mode is enabled during computer hibernation or shutdown.

Upon startup following the above conditions, enable the system to revert to the previous GPU mode, ensuring that the dedicated GPU (dgpu) is activated properly.

Observation:
I believe that updating the BIOS to version 313 or 315 on the Zephyrus G15 GA503 has the potential to bypass the issues described above.

This report is intended to assist in resolving the Eco Mode inconsistency and GPU activation problem. If additional information or clarification is required, please feel free to request it.

[log.txt](https://github.com/seerge/g-helper/files/13697363/log.txt)

**Comment by seerge** [comment]
@Maneeha1234SL hello,

I have added your model to the list that offer this "workaround" https://github.com/seerge/g-helper/discussions/1042

You will find option to enabled GPU on shutdown under ``Extra``

Keep in mind, that it may not always work for Hibernate, as while windows is sleeping it supreses apps as well

[GHelper.zip](https://github.com/seerge/g-helper/files/13697396/GHelper.zip)

**Comment by seerge** [comment]
@Maneeha1234SL it should

**Comment by seerge** [comment]
@Maneeha1234SL it will destroy sleep then

**Comment by anhkhoa0906** [comment]
I also encountered the same situation but on a TUF A15 fa506ihr laptop.
I have to always use standard mode to use instead of optimized mode because when I shutdown or hibernate with dgpu off, when I start up I will encounter a similar situation as the video above.
I hope the developer can add the GPU on shutdown enabling feature to this laptop model.

**Comment by seerge** [comment]
@anhkhoa0906 added yours as well

[GHelper.zip](https://github.com/seerge/g-helper/files/13715022/GHelper.zip)
