### ISSUE TITLE
GHelper - There is no GPU Modes

### ISSUE THREAD

**Issue by z3r0gr4v17y** [seerge/g-helper#1757]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**
Hi. In my previous OS (Win10 ltsc 21h2) i haved GPU modes, right now i formatted my notebook to win 10 22h2, and now i lost gpu mode section. Please help. 

**Clear scenario to Reproduce**
4. Explanation of an error or a bug

**Expected behavior**

**App Logs**
Please incl[log.txt](https://github.com/seerge/g-helper/files/13697558/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - Win 10 22h2 x64
 - asus rog strix g18 (nvidia rtx 4080)

**Asus software**
- Armoury Crate (or it's services installed) - Not exists.
- MyASUS installed - NOT
- Other Asus services running in background - No one exists.

**Additional context**

**Comment by seerge** [comment]
Asus control interface is required for app to run, you are missing it.
Check readme https://github.com/seerge/g-helper?tab=readme-ov-file#requirements-mandatory
