### ISSUE TITLE
Is it possible to add an extra button for screen refresh rate?

### ISSUE THREAD

**Issue by Marxis95** [seerge/g-helper#1758]
**Is your feature request related to a problem? Please describe.**
Right now if I use auto mode, the only two options for refresh rate are 60 Hz on battery and 360 Hz on power.

**Describe the solution you'd like**
I would like an option to make the screen on power run at 180 Hz instead of 360 Hz (it is supported by the screen) if possible

**Comment by seerge** [comment]
@Marxis95 hello, you can set any refresh rate you want in windows. As far as ``Auto`` is not turned on in G-Helper it won't interfere with that :) 

I don't plan to overload UI with all possible resolutions your system has.

**Comment by Marxis95** [comment]
ok noted no problem, thanks for the reply and good job on this app it works great
