### ISSUE TITLE
NV GPU temperature is wrong

### ISSUE THREAD

**Issue by kenneth7058** [seerge/g-helper#176]
**Describe the bug**
3080 Ti temperature is different when compared with MSI Afterburner and HWInfo

**Clear scenario to Reproduce**
1. Start a game
2. Compare GPU temperature with HWInfo and MSI Afterburner

**Expected behavior**
Temperature should be same between different monitoring software

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/11123734/log.txt)

**Screenshots or screencasts**
![Screenshot 2023-03-31 112808](https://user-images.githubusercontent.com/43233478/229171394-7fa2964c-85e9-46e5-adde-67ae5c9c9ef0.png)
![Screenshot 2023-03-31 112910](https://user-images.githubusercontent.com/43233478/229171414-39c9cc4f-e7c9-41ac-a134-ea0f34dd5ecb.png)
![Screenshot 2023-03-31 114454](https://user-images.githubusercontent.com/43233478/229171467-d2e98e3d-056b-4ab7-b938-2238e9af6956.png)

**Spec:**
 - Windows 11 22H2
 - Zephyrus M16 (2022) GU603ZX
 - GPU: RTX 3080 Ti, driver version 531.41
 - G-Helper version 0.43.0.0

**Asus software**
- ASUS Smart Display Control
- ASUS On Screen Display
- MyASUS installed
- (Uninstalled Armory Crate with the uninstaller, not sure what else is left)

**Comment by seerge** [comment]
@kenneth7058 Hello, I recently changed from driver temp sensor to asuse's native (that bios reports), cause it seems to be used by armoury too. It could be that on your laptop bios sensor reports incorrectly.

Can you quickly test older version that still had driver sensor https://github.com/seerge/g-helper/releases/tag/v0.38 and check if temps are correct there ? Thanks

**Comment by JackB111** [comment]
<img width="218" alt="image" src="https://user-images.githubusercontent.com/129295334/229209081-e5dae81e-2dba-4b91-8cff-6667b1296f8c.png">

GPU temperature goes crazy when the video card is disabled in standard mode.

**Comment by kenneth7058** [comment]
@seerge Yeah the older version has correct temp
![Screenshot 2023-03-31 151321](https://user-images.githubusercontent.com/43233478/229210014-71c9d29d-102c-46d2-b2e5-216078a78820.png)

![Screenshot 2023-03-31 151651](https://user-images.githubusercontent.com/43233478/229210028-a52d9bf2-9da7-4fb7-9918-75b9343155f6.png)

**Comment by seerge** [comment]
Ok, clear. I will give gpu-sensor priority then.

You can use this build or wait for the next release :)
[GHelper.zip](https://github.com/seerge/g-helper/files/11125426/GHelper.zip)

**Comment by seerge** [comment]
https://github.com/seerge/g-helper/releases/tag/v0.45
