### ISSUE TITLE
Only Turbo mode correctly applies limits

### ISSUE THREAD

**Issue by SkaMasta** [seerge/g-helper#1760]
**Describe the bug**
I was having issue when my GPU power draw never was above 50ish watt. I already had a pool about this but did find nothing. I reinstalled win, got it working properly. Today I was playing W3 and had a feeling that I have low FPS so I checked AMD overlay and saw that power draw was again around 30-40w. Playing around I found that if I use TURBO instead of manual and set my limits there it works as it should. 

**Expected behavior**

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Laptop model 2022 G14 

**Asus software**
nothing

**Additional context**
Cant find the log.txt somehow?

**Comment by seerge** [comment]
@SkaMasta hello. Your power draw depends on specific game, drivers and other things. All 3 modes are hardcoded in BIOS and not in the app, so it's not related anyhow.

Since you have ignored issue requirements i can't help anyhow else
