### ISSUE TITLE
Help: Balanced mode power limits are not restored on laptop/GHelper start

### ISSUE THREAD

**Issue by TheBestPessimist** [seerge/g-helper#1761]
**Describe the bug**

I keep my laptop generally on Balanced mode. After i turn off my laptop, then turn it back on, the power limits seem to stay at 30W no matter the load. If i switch power mode to `silent -> balanced` or `turbo -> balanced`, the power goes back to ~55W (which, i guess is the default for my model, but i can't say for sure).

BUG: it seems that on starting the laptop/ghelper, the correct power limits aren't set.

**Clear scenario to Reproduce**
1. Set the laptop on mode `Balanced`
2. Shut down
3. Start laptop
4. Check power limits

**Expected behavior**
I expect the correct power limits from Balanced (or "the current mode", whichever that is) to be set after GHelper starts.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13712063/log.txt)

**Screenshots or screencasts**
It can be seen exactly at what time i changed the power modes (in this case  `Silent -> Balanced`)
![image](https://github.com/seerge/g-helper/assets/4482210/be08ada2-1ec7-4181-b2f3-bf286d788624)

**Desktop (please complete the following information):**
 - OS Windows 11
 - Laptop model: ROG Flow X16 GV601VI - 2023 with 4070

**Asus software**
- Armoury Crate (or it's services installed): no. Fresh windows install without any asus bloatware except for what is installed by windows automatically + what's shown in the `updates` page of GHelper
- MyASUS installed: no
- Other Asus services running in background: no

**Comment by seerge** [comment]
@TheBestPessimist hello, hello

App always sets last used mode on startup, and since you don't have custom power limits it doesn't set anything else

```
Tuesday, 19 December, 2023 08:26:25: ------------
Tuesday, 19 December, 2023 08:26:26: App launched: ROG Flow X16 GV601VI_GV601VI :0.137.0.0en-GB.
Tuesday, 19 December, 2023 08:26:27: CPU: -1 - 13th Gen Intel(R) Core(TM) i9-13900H - Intel64 Family 6 Model 186 Stepping 2
Tuesday, 19 December, 2023 08:26:29: AutoSetting for Online
Tuesday, 19 December, 2023 08:26:29: Input: \\?\hid#vid_0b05&pid_19b6&mi_00&col01#7&1518b9ff&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
Tuesday, 19 December, 2023 08:26:29: Mode = 0 : OK    <------ Balanced mode
```

It looks more like something else is limiting CPU in your case. 

Do you have any throttlestop or any other apps that can do that ?

Also I see that you use custom power plans, could it be that in one of them CPU boost is disabled ? as 30w looks more like max power but w/o boost. Try to use default balanced power plan.

```
Tuesday, 19 December, 2023 08:39:50: Power Plan 287309a6-37c9-4d48-a6ae-f7c71c5dd9a6:87
Tuesday, 19 December, 2023 08:39:50: Clocks: Eco
Tuesday, 19 December, 2023 08:39:50: Key: 56
Tuesday, 19 December, 2023 08:39:51: PowerLimit C0 = 25 : OK
Tuesday, 19 December, 2023 08:39:51: PowerLimit C2 = 87 : OK
Tuesday, 19 December, 2023 08:39:56: Key: 56
Tuesday, 19 December, 2023 08:39:56: NE160QDM-NM4 HDR: False
Tuesday, 19 December, 2023 08:39:58: Mode = 2 : OK
Tuesday, 19 December, 2023 08:39:58: Clocks: Eco
Tuesday, 19 December, 2023 08:39:58: Power Plan c3536a01-7427-46f0-af27-5003894e9728:87
Tuesday, 19 December, 2023 08:39:58: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
```

Anyway, I'm afraid I can't "fix" it anyhow on the app side, and this is not the app limiting something in a first place :)

**Comment by TheBestPessimist** [comment]
> Do you have any throttlestop or any other apps that can do that ?

no.

> Also I see that you use custom power plans, could it be that in one of them CPU boost is disabled?

I assume no, since when i move back to balanced, it works as expected. The power plans that i have set are "Battery saver", and "High performance". For some stupid reason, asus hides those by default and leaves only the "balanced" profile.

What i have is

silent - battery saver
balanced - high perf
turbo - high perf

**Comment by seerge** [comment]
@TheBestPessimist cause in win11 power modes replaced power plans :) (and you can select them in windows settings or even in g-helper under fans+power).

**Comment by seerge** [comment]
> I assume no, since when i move back to balanced, it works as expected (all i do is click Silent then click Balanced, nothing else -- and the power is back up).

Well, you also set power plan in windows back and forwards :) so that could be a reason 

I once had some hiccup in windows power plans that disabled boost and was refusing to restore. Resetting power plan via powershell helped tho

**Comment by seerge** [comment]
```
powercfg -restoredefaultschemes​
```

**Comment by seerge** [comment]
@TheBestPessimist did it help ?

**Comment by seerge** [comment]
Closing as abandoned

**Comment by TheBestPessimist** [comment]
restoring the default balanced profile seems to have fixed it, though, something odd regarding perf is still happening, but i cant really explain it.

**Comment by TheBestPessimist** [comment]
Hey, i'm wrong and there seems to be a different issue.

I'm not sure this is related to GHelper, at this point i'm just asking for help.

The issue with power limits seems to be after starting from hibernate. My usecase:
- restart laptop on battery
- plug laptop in on usbc charger(asus provided one)
- hibernate laptop
- unplug laptop after it's off
- start laptop
- plug laptop in normal charger (the 280W one)

At this point, my power limits are broken and the only solution to restore them is to reboot. After reboot, everything is ok and laptop boosts OK.

Do you have any ideas what's going on here? What could i try to fix resuming from hibernation?

![image](https://github.com/seerge/g-helper/assets/4482210/c63a204e-33f4-4fc7-a576-23885aab77d0)

**Comment by seerge** [comment]
@TheBestPessimist does selecting appropriate performance mode in G-Helper restore the things to normal ?

**Comment by TheBestPessimist** [comment]
Nope.
What seems to be happening is, it boosts to 55W for a little, then drops to 30W. No matter the Mode (silent, balanced, turbo), it stays at 30W
![2024-01-11-0000006664](https://github.com/seerge/g-helper/assets/4482210/7864a454-5be2-4fb1-b04b-45d6caad2338)
![2024-01-11-0000006665](https://github.com/seerge/g-helper/assets/4482210/16b1ebc0-448b-4804-b09c-5451e5f7d7f6)

**Comment by TheBestPessimist** [comment]
> try to check `Enable GPU on shutdown in Extra`

I will try.


Side topic: I used that feature right after you enabled it for all laptops and found a different bug with GH: when my laptop restarts, it switches to `Standard` mode, and doesn't stay on `Optimized` or `Eco`, as i set it before shutdown.

**Comment by seerge** [comment]
@TheBestPessimist glad it was the reason

As for forgetting Optimized, the only case it would happen (besides you simply forgetting something and missclicking) is if config file would get corrupt while app was involuntarily shut down while writing (i.e. due to windows crash?)

And even that I tried to tackle in latest https://github.com/seerge/g-helper/releases/tag/v0.145

**Comment by TheBestPessimist** [comment]
@seerge It still happens for me, even though no setting was reset: `Standard` when laptop restarts.

logs
[log.txt](https://github.com/seerge/g-helper/files/13904700/log.txt)

**Comment by seerge** [comment]
@TheBestPessimist so after restart at 16:42 something happens to you?

```
Thursday, 11 January, 2024 16:42:04: Forcing Standard Mode on shutdown / hibernation
Thursday, 11 January, 2024 16:42:04: WMI event 123
Thursday, 11 January, 2024 16:42:05: GPUEco = 0 : OK
Thursday, 11 January, 2024 16:42:06: BatteryLimit = 75 : OK
Thursday, 11 January, 2024 16:42:43: ------------
Thursday, 11 January, 2024 16:42:50: App launched: ROG Flow X16 GV601VI_GV601VI :0.145.0.0en-GB.
Thursday, 11 January, 2024 16:42:54: NVIDIA GeForce RTX 4070 Laptop GPU
Thursday, 11 January, 2024 16:42:56: CPU: -1 - 13th Gen Intel(R) Core(TM) i9-13900H - Intel64 Family 6 Model 186 Stepping 2
Thursday, 11 January, 2024 16:42:56: AutoSetting for Online
Thursday, 11 January, 2024 16:42:56: Input: \\?\hid#vid_0b05&pid_19b6&mi_00&col01#7&1518b9ff&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
Thursday, 11 January, 2024 16:42:56: Mode = 0 : OK
Thursday, 11 January, 2024 16:42:56: Eco flag : 0
Thursday, 11 January, 2024 16:42:56: Mux flag : 1
```

Thing is that you use all default settings :) and g-helper literally doesn't set anything beisdes actual (default) balanced mode 

```
Thursday, 11 January, 2024 16:42:56: Mode = 0 : OK
```

**Comment by seerge** [comment]
Are you sure it's not some other stuff running in windows and adjusting settings ? :|

**Comment by TheBestPessimist** [comment]
how do i check if it's something else in windows?

how do i check the current GPU mode? I can test that after a restart: disable GH from autostart, restart my laptop while in eco mode, and run that command to see what the current status is.

Besides GH, i dont have anything else which manages my laptop, so i think there should be nothing else which interferes.

if it helps, here's my config: [config.json](https://github.com/seerge/g-helper/files/13906491/config.json)

**Comment by seerge** [comment]
@TheBestPessimist then you can just check windows device manager :) if GPU is there or not.

**Comment by TheBestPessimist** [comment]
i tried to check in device manager: 
- disable GH startup
- turn on eco mode
- check DM: no nvidia ✅ 
- restart
- GH is not started ✅ 
- check DM: nvidia GPU appears (expected because GH feature `Enable DGPU on shutdown`)
- start GH as admin manually
- GH DGPU: `Standard` and not `Eco` ❌ 

I expected GH on startup to set my laptop back into `Eco` mode, as it was when i shut it down.

**Comment by seerge** [comment]
@TheBestPessimist cause that is not programmed :)

If you want Eco back you can

- Set Optimized mode on (then it would shutdown GPU on battery) on app start

OR 

- Add `` "gpu_mode_force_set" : 1,`` to ``config.json``
