### ISSUE TITLE
[feature] Fn+F12 toggles airplane/offline mode

### ISSUE THREAD

**Issue by nicola02nb** [seerge/g-helper#1765]
**Is your feature request related to a problem? Please describe.**
On my Zephyrus GA502IU there is an airplane/offline button, but when I'll use it, nothing happends.

**Describe the solution you'd like**
I'll need that when she shortcut occurs, it toggles the aiplane/offline mode in windows.

**Describe alternatives you've considered**
I don't see any alternatives, rahter than not using the key combination.

**Additional context**
![20231220_180027](https://github.com/seerge/g-helper/assets/61830443/379bd214-524e-4b96-b645-c288777481f7)

**Comment by seerge** [comment]
@nicola02nb that key just produces a windows hotkey for airplane mode on hardware level :) app is not involved here anyhow as it works w/o app

**Comment by nicola02nb** [comment]
@seerge I dont think so.. because if I lounch all Asus services the key will work.

Sorry for desagreing with you, but thats how it behaves this button on my laptop.

**Comment by seerge** [comment]
@nicola02nb can you include a log at least as it was asked in an issue template ? and check what keycode does Fn+F12 produce in a log

**Comment by nicola02nb** [comment]
@seerge sorry for not attatching it, but it wasn't mentioned in the Feature template.

Thats the log file:
[log.txt](https://github.com/seerge/g-helper/files/13741433/log.txt)

The key pressed is No. 136

**Comment by seerge** [comment]
@nicola02nb oke, thanks. 

Problem is that I don't know what is a windows own hotkey combo to actually toggle airplane mode ON or OFF (to emit it within the app). Are you aware of any ? 

Can you check following command in powershell as admin and see if it toggles airplane mode by any accident ?

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00100021, 0x88)
```

**Comment by nicola02nb** [comment]
@seerge I don't know any command to toggle it, sorry...

But i just tried the one you just sended me and it works.

![Screenshot 2023-12-21 134116](https://github.com/seerge/g-helper/assets/61830443/98ff35af-5855-4d75-8521-f8c6e745eedc)

**Comment by seerge** [comment]
@nicola02nb then try this build, it should do the same thing
[GHelper.zip](https://github.com/seerge/g-helper/files/13741957/GHelper.zip)

**Comment by nicola02nb** [comment]
@seerge Good, it works
