### ISSUE TITLE
FAN RPM GOES MAXOUT for GPU when switching to TURBO mode

### ISSUE THREAD

**Issue by finalmakerr** [seerge/g-helper#1767]
**Describe the bug**
Title explain it better, check screenshots for better understanding.

**Clear scenario to Reproduce**
I guess it's related to the Asus services running = 0? 

**Expected behavior**
I expect the fan RPM to be a.. normal speed? Or close to the default custom fan curve.

**App Logs**
https://drive.google.com/file/d/1vwwXCbX3i994YoftLxaS5j7uKu-n89G3/view?usp=sharing

**Screenshots or screencasts**
👎MAX-OUT ![image](https://github.com/seerge/g-helper/assets/7450109/91d6a288-b340-4e3f-b1f5-9cd9325cad3f)
👍GOOD ![image](https://github.com/seerge/g-helper/assets/7450109/30583fa9-6738-4d8a-9d62-3d2e134be07a)
👍GOOD ![image](https://github.com/seerge/g-helper/assets/7450109/8ce9e34e-cc57-482a-9d9f-0a80c47b9b90)
🛠️FIX by enabling Asus services ![image](![image](https://github.com/seerge/g-helper/assets/7450109/2b843ec5-c6fa-405f-bce9-cef3dd18767b))
Still fix when stopping Asus services!
![image](https://github.com/seerge/g-helper/assets/7450109/58a641dd-fcba-467e-99c8-002469d8242f)

But it's will happen again in the future as always..

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: ASUSTeK COMPUTER INC. ROG Zephyrus M16 GU603HR_GU603HR

**Asus software**
- Armoury Crate (or it's services installed) 👍 service disable but installed
- MyASUS not installed 👍
![image](https://github.com/seerge/g-helper/assets/7450109/cbbf1ea6-d5d4-4ae4-82f9-7dcc1c5256f8)

**Additional context**
I said enough ;) , thx man!

**Comment by seerge** [comment]
@finalmakerr hello, 

Fans are controlled by BIOS, not by the apps.

On your **first** screenshot with "max out" you don't apply a custom fan curve, so BIOS uses whatever default fan behavior for turbo is. I assume it goes to 6000+ RPM :) which is up to Asus engineers why it's like that (and honestly i don't see any problems there)

On **second** screenshot you use default BIOS fan behavior for balanced, and on **third** - you apply a custom fan curve to Tubro, and based on screenshot it even seem to follow it so all seems good :) 

So what's wrong here ? everything seem to work as it should.

As for your observations with asus services, most probably it just sets Balanced mode when starts overriding g-helper :)

**Comment by seerge** [comment]
> The 1st (👎MAX-OUT) and last (🛠️FIX) are identical modes with different fan speed, why is that? 

I'm almost certain that when you launched Asus Optimization service it has set balanced mode under the hood, it won't be reflected in UI anyhow, as you can't "read" mode, only "set".

6800RPM is fine imho. And again - this is default mode with default fan behavior, it's not controlled anyhow by the app

>Btw the Fan calibration result is even less then that!!

During calibration app would set a custom 100%-100% fan curve, and for many models custom fan curves are indeed interpreted a bit differently, and can reach lower max RPMs  :) this is how things are

I'm closing, as there is nothing I can "fix" or change here.

Good luck
