### ISSUE TITLE
Please Effective GHelper Uninstaller

### ISSUE THREAD

**Issue by Licht555** [seerge/g-helper#1768]
GHelper deeply interferes with the system, so disabling it does not restore the settings from before it was launched. Unfortunately, this lowers CPU performance significantly. The default PL2 for the i9-13980HX is 175 W, while in the GH it is 150 W.

**Comment by seerge** [comment]
@Licht555 hello, that is simply not true :) G-Helper is a single portable app, and it doesn't install absolutely anything in your system. This question is also [covered in FAQ](https://github.com/seerge/g-helper?tab=readme-ov-file#how-do-i-uninstall-g-helper)

All sources are open and can be simply monitored, so I don't get your take here.

It doesn't "lower" your power limits anyhow as well, as it just switches between 3 predefined hardcoded in BIOS modes. What you see in fans+power is just a UI slider, that has no effect until it's applied. Also have you ever seen your CPU actually consume 175W ? I would like to see a screenshot with hwinfo or similar monitoring app showing that, then I can just increase slider value :)

Furthermore on reboot, your laptop simply forgets all previous settings as well.

**Comment by Licht555** [comment]
If it was as you say, I wouldn't be writing about it here, and I'm not an IT newbie and I can't handle it. After starting and shutting down the GH, the result in Cinebench R23 dropped by 4000 pts. Bagatelle. And restats don't do anything.

**Comment by seerge** [comment]
@Licht555 After each restart your computer would revert to default Balanced / Performance (in AC) mode, so no wonder your scores are lower than they were in Turbo, as I understand:)

**Comment by seerge** [comment]
> If it was as you say, I wouldn't be writing about it here, and I'm not an IT newbie and I can't handle it. After starting and shutting down the GH, the result in Cinebench R23 dropped by 4000 pts. Bagatelle. And restats don't do anything.

@Licht555  Do you mind to post a screenshot of CPU consuming 175W in benchmark (for example in HWinfo or any other monitoring app of your choice) when you have set those settings Armoury Crate?
