### ISSUE TITLE
[Bug Report] misrepresentation of max cpu fan speed and charge limit not applied when not inside windows

### ISSUE THREAD

**Issue by m-jishnu** [seerge/g-helper#1771]
**Describe the bug**
1. misrepresentation of max cpu fan speed: After calibration the max cpu fan speed is 6300 but it shows max as 6400 in the graph

3. charge limit not applied  when not in windows: In the past when i used to set charge limit using myasus it stayed the same even when not in windows (reboot/starting/poweroff) but in case of ghelper it works fine while i am inside windows but when its reboot/starting/turned off but plugged to a charger  its not applied (myasus is installed and charge limit is set to 60 same in case of ghelper but asus services are stoped (extra --> stop)), i am not sure but myasus used to set it in bios level or something i think.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13749098/log.txt)

**Screenshots or screencasts**
1.
<img width="331" alt="Screenshot 2023-12-22 111229" src="https://github.com/seerge/g-helper/assets/83004520/c542b6d8-d8ea-469f-bd98-8d53395bdd96">
2.
<img width="294" alt="Screenshot 2023-12-22 111330" src="https://github.com/seerge/g-helper/assets/83004520/0fc5036e-7abd-4b4e-886b-4bf244429529">

**Desktop (please complete the following information):**
 - OS: windows 11 22h2
 - Laptop model: Asus Rog strix g15 advantage edition

**Asus software**
- MyASUS installed
- Other Asus services running in background: 7 were running but stopped using (extra --> stop)

**Comment by Kikimahe** [comment]
Hi, 

1- Your Fan must have exceeded 6300 RPM (6301, 6315, 6350 ....) 
The graph logically displays at 6400 RPM max.

**If you are really sure that your fan can't exceed 6300 RPM** (check in HWinfo64 first), 
Then you can correct it manually : 
- Exit Ghelper
- Go to `C:\Users\*yourname*\AppData\Roaming\GHelper`
- Open `config.Json `
- Adjust the scale values : 
`"fan_max_0": 62,`
`"fan_max_1": 64,`

(62 = 6200 RPM for CPU  and 64 = 6400 RPM for GPU)



2-  Charge limit is applied AFTER starting Ghelper, It's impossible before.
It is normal for the battery to charge for a few seconds upon Windows startup or restart.
After several starts/restarts you necessarily exceed the 60% load limit ;-)

**Comment by seerge** [comment]
@m-jishnu hello,

1. Chart rounds it to each 200RPM, so you have 6400. Also don't look at that precisely anyway, as it's still up to BIOS on how to interpret fan curve and run fans and deviate from that too if it's programmed like that

2. Many models reset charge limiter on reboot, it's normal. As soon as app starts - it will set it again :) It can't start w/o windows running obviously.

Closing as there is nothing to fix here :)

**Comment by m-jishnu** [comment]
thanks for the replies @Kikimahe, @seerge  also i have a question @seerge will it possible to change the undervolte value to floats as i can see its currently integers more over what does each value means if i set as -16 is it equal to -0.016V?

**Comment by seerge** [comment]
@m-jishnu most probably it's mV :) but anyway, this is just a value that app sends to AMD SMU

**Comment by m-jishnu** [comment]
> @m-jishnu most probably it's mV :) but anyway, this is just a value that app sends to AMD SMU

so will it be possible to make them float like if my system is stable in -17 in 99% time but sometime freezes i want to try values like -16.5, -16.8 etc does the amd smu accept such value ?

**Comment by seerge** [comment]
@m-jishnu no, that's not possible

**Comment by m-jishnu** [comment]
@seerge are you interested in implementing these features 

1. game/app detection, if I want particular apps/games to use certain profile with certain options(like turbo with display overdrive on fps games) when they launch automatically and switch back to my normal profile once I close/ changes the app. similar to the one found in AC

2. Implementing UI interface for dark theme and other advanced feature also it would be great if there was a button which opens confg.json too.

Also hats off to your dedication to the project!, never seen any maintainer be so much involved with the community.

**Comment by seerge** [comment]
@m-jishnu 

1. Game detection is very difficult, so - no

2. App already supports dark UI, and follows windows app settings. You can override that in a config https://github.com/seerge/g-helper?tab=readme-ov-file#override-ui-theme

**Comment by m-jishnu** [comment]
> @m-jishnu
> 
> 1. Game detection is very difficult, so - no
> 2. App already supports dark UI, and follows windows app settings. You can override that in a config https://github.com/seerge/g-helper?tab=readme-ov-file#override-ui-theme

oh i see so no game detection, in 2 what i mean was ui for changing those setting anyways thanks!
