### ISSUE TITLE
Some feautres are not exists

### ISSUE THREAD

**Issue by mastradamus87098** [seerge/g-helper#1778]
Hi. I needed to ask 2 mini questions. My notebook is rog strix g18,

1. Why i dont have anime matrix option like this?: https://i.ibb.co/86Nb9r0/image.png
2. Why we cant configure M4 button? (but we can configure M1/2/3/5. M4 in my notebook is changing Modes between Silent > Balanced > Turbo, at least can u add checkbox or something to disable M4 functionality or you have plan about customizing M4 button like other M buttons?)

**Comment by seerge** [comment]
@mastradamus87098 hello

1. It means that USB device with ID of anime matrix exists in your system (I have no idea why). So app just shows what it sees. I assume changing something there have no effect on you ?

2. M4 on Strix models produce same key-code as Fn+F5 (it's literally same function). And it's reserved to switching profiles forward (and backwards with Shift). Cause of that I don't want to change it :)

**Comment by mastradamus87098** [comment]
1. Thanks.
2. Can you give as option to configure M4 button too (im not using original M functionalities, i customized them all)?
