### ISSUE TITLE
Display Modes

### ISSUE THREAD

**Issue by sr2echa** [seerge/g-helper#1779]
**Is your feature request related to a problem? Please describe.**
Armory Crate has display presets for various games (racing,fps,rpg,etc) and for various use cases that actually are nice and impact the way things look.

**Describe the solution you'd like**
A menu to select those presets maybe?

**Comment by seerge** [comment]
>[How do I set different "Visual styles"?](https://github.com/seerge/g-helper?tab=readme-ov-file#how-do-i-set-different-visual-styles)
>Personally, I'm not a big fan of them, as they make colors very inaccurate. But if you want so - you can adjust display colors using either Nvidia Control panel or AMD Adrenaline (appropriate display sections). If you really want you can also use [own ASUS utility from MS Store](https://apps.microsoft.com/store/detail/gamevisual/9P4K1LFTXSH8?hl=nl-nl&gl=nl&rtc=1)

**Comment by seerge** [comment]
Added in latest release https://github.com/seerge/g-helper/releases
