### ISSUE TITLE
Error applying last GPU mode

### ISSUE THREAD

**Issue by vmkogeretla** [seerge/g-helper#178]
Video recording of program behavior:
https://youtu.be/rTDueisNcvM
**Expected behavior**
Keep previous mode after reboot, or force last GPU mode to apply after reboot. Maybe add it as an option?

**Comment by seerge** [comment]
Hello, i don't see any "Error" as you say here. App has correctly switched dGPU off. 
The fact that your hardware doesn't store settings after reboot is out of scope of the application. Try to check if there is any settings related to that in bios.
