### ISSUE TITLE
[Feature request] Add an OSD toast/indicator about FN + Win key lock

### ISSUE THREAD

**Issue by Not-to-Shabby** [seerge/g-helper#1783]
FN+WIN lock feature on some ASUS laptop I believe (Mine is ASUS TUF A15 2023), and it's been a useful tool, especially during gaming sessions or doing video editing specially with a large hand. However, I've noticed there's no visual cue or an indicator to tell whether the Windows keys are locked or not. 

It'd be awesome if we could add a small pop-up or something similar on the screen when the keys get locked using FN+WIN. This way, users would instantly know the status.

**Comment by seerge** [comment]
@Not-to-Shabby app is not handling that anyhow, most probably it just works on hardware level in your keybopard. So windows/ G-Helper doesn't even know if that combination is pressed :)

That's not possible
