### ISSUE TITLE
Displaying Incorrect Dynamic Boost

### ISSUE THREAD

**Issue by RevarloVlabius** [seerge/g-helper#1786]
**Describe the bug**
My Asus Tuf F15 has an rtx 3050 95w tgp (80w + 15w dynamic boost).  But ghelper by default shows dynamic boost to 25w in the slider located in Fans  + Power option. Even if I click on factory default button.

**Clear scenario to Reproduce**
1. Go to 'Fans + Power'
2. Click on 'GPU'.
3. Shows 25w dynamic boost.

**Expected behavior**
I expected the slider to show 15w instead of 25w.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13764049/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - FX507ZC4

**Asus software**
- Armoury Crate uninstalled. (Actually removed after a clean windows installation)
- MyASUS uninstalled.
- Other Asus services are not running in background

**Comment by seerge** [comment]
@RevarloVlabius hello,

What happens if you would set 20W in dynamic boost ? 

App shows 5-25W range in UI for al devices. Your BIOS has own hardcoded limits as well, so it will just ignore higher values if they are not supported.  It's same as with power sliders for CPU, and some other things. It's just unrealistic to hardcode sliders for each possible model on the market :)

**Comment by RevarloVlabius** [comment]
@seerge Hi,

Nothing really happens when I set it to 20w or even 5w. I don't think the slider works at all. In my nvdia control panel it shows 95w tgp no matter what I set in the slider.

Oh and another thing the after I restart my laptop the charge limiter stops working and I have to click on the same value again for it start working again.

**Comment by seerge** [comment]
@RevarloVlabius i don't think that's how dynamic boost works on Asus. You won't see anything new in control panel. It's how much power asus bios would let GPU to take.

You can run GPU heavy benchmarks like Furmark and check in Hwinfo how much power GPU consumes with 5W dynamic boost, or 15w, or 25W :)

As for charge limiter - many models reste it on reboot, so as soon as app starts it sets it again. 

It's also in your log, for example
```
24/12/2023 5:58:09 pm: BatteryLimit = 60 : OK
24/12/2023 5:58:09 pm: BatteryLimit = 60 : OK
```

So no need to drag slider each time

**Comment by seerge** [comment]
@RevarloVlabius actually, since someone else also asked to limit their boost to 5W on other model. I have made this param configurable.

This build will show range 5-15W for your device

[GHelper.zip](https://github.com/seerge/g-helper/files/13792969/GHelper.zip)
