### ISSUE TITLE
The app sometimes becomes extremely slow to open or to respond to input

### ISSUE THREAD

**Issue by MaxLebled** [seerge/g-helper#1788]
**Describe the bug**
Sometimes, the app will take several seconds to answer to the M4 key (or a double-click in the sys tray). Like half a minute.

Other times, it will open just fine; but every attempt to change a mode or get into the Fans+Power menu causes the app to freeze for several seconds, with a spinning cursor (and also for up to half a minute)

I **believe** this started happening sometime in November, as I used the laptop daily during October and didn't notice this issue a single time.

**Clear scenario to Reproduce**
I don't have a consistent repro case nor have I noticed specific conditions that cause this to happen, unfortunately.

It _seems_ like it's more likely to happen after waking up from hibernation?

**Expected behavior**
No slowdowns / instant launch as normal

**App Logs**
I just woke up my laptop from hibernation and updated from 0.140 to 0.141. Both before & after the update, the app took a very long time to answer the first few M4 presses.

It's fine now.
```

Here's the log that starts when I launched 0.141 for the first time and faced a long freeze

25/12/2023 14:28:57: ------------
25/12/2023 14:28:57: App launched: ROG Zephyrus G14 GA402XI_GA402XI :0.141.0.0en-GB
25/12/2023 14:28:58: dGPU not found
25/12/2023 14:28:59: CPU: 9 - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics      - AMD64 Family 25 Model 116 Stepping 1
25/12/2023 14:28:59: USB Version: 1049 4.19
25/12/2023 14:28:59: AutoSetting for Offline
25/12/2023 14:28:59: Input: \\?\hid#vid_0b05&pid_19b6&col03#7&17810770&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
25/12/2023 14:28:59: Mode = 2 : OK
25/12/2023 14:28:59: FanCPU = 2B-38-44-48-4D-5F-61-62-00-00-0D-12-20-33-64-64 : OK
25/12/2023 14:28:59: FanGPU = 1E-2A-39-48-4D-5F-61-62-00-00-00-10-20-33-5B-5B : OK
25/12/2023 14:28:59: GPU usage:  %
25/12/2023 14:28:59: BatteryLimit = 75 : OK
25/12/2023 14:28:59: BatteryLimit = 75 : OK
25/12/2023 14:28:59: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
25/12/2023 14:28:59: AuraMode: AuraStatic
25/12/2023 14:28:59: USB 19B6: 5D-B3-00-00-30-18-12-E1-00-00-FF-FF-FF-00-00-00-00
25/12/2023 14:28:59: USB 19B6: 5D-B4
25/12/2023 14:28:59: USB 19B6: 5D-B5-00-00-00
25/12/2023 14:28:59: USB 19B6: 5D-B9
25/12/2023 14:28:59: USB 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
25/12/2023 14:28:59: USB 19B6: 5D-05-20-31-00-1A
25/12/2023 14:29:00: Auto 19B6: 5D-BA-C5-C4-02
25/12/2023 14:29:13: Key: 56
25/12/2023 14:29:49: GPUEco = 1 : 0
25/12/2023 14:29:49: PowerLimit A0 = 15 : OK
25/12/2023 14:29:49: PowerLimit A3 = 15 : OK
25/12/2023 14:29:49: PowerLimit C1 = 20 : OK
25/12/2023 14:29:49: Matrix Off
25/12/2023 14:29:49: Monitor Power On
25/12/2023 14:29:49: AutoSetting for Offline
25/12/2023 14:29:49: Input: \\?\hid#vid_0b05&pid_19b6&col03#7&17810770&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
25/12/2023 14:29:49: Mode = 2 : OK
25/12/2023 14:29:49: FanCPU = 2B-38-44-48-4D-5F-61-62-00-00-0D-12-20-33-64-64 : OK
25/12/2023 14:29:50: FanGPU = 1E-2A-39-48-4D-5F-61-62-00-00-00-10-20-33-5B-5B : OK
25/12/2023 14:29:50: GPU usage:  %
25/12/2023 14:29:50: BatteryLimit = 75 : OK
25/12/2023 14:29:50: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
25/12/2023 14:29:50: AuraMode: AuraStatic
25/12/2023 14:29:50: USB 19B6: 5D-B3-00-00-30-18-12-E1-00-00-FF-FF-FF-00-00-00-00
25/12/2023 14:29:50: USB 19B6: 5D-B4
25/12/2023 14:29:50: USB 19B6: 5D-B5-00-00-00
25/12/2023 14:29:50: USB 19B6: 5D-B9
25/12/2023 14:29:50: USB 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
25/12/2023 14:29:50: USB 19B6: 5D-05-20-31-00-1A
25/12/2023 14:29:50: Running eco command 1
25/12/2023 14:29:50: Matrix Off
25/12/2023 14:29:51: Auto 19B6: 5D-BA-C5-C4-02
25/12/2023 14:29:51: Latest version 0.141.0.0
25/12/2023 14:29:56: Key: 56
25/12/2023 14:29:56: Key: 56
25/12/2023 14:29:56: Listener stopped
25/12/2023 14:30:40: GPUEco = 1 : 0
25/12/2023 14:30:40: Eco flag : 0
25/12/2023 14:30:40: Mux flag : 1
25/12/2023 14:30:40: PowerLimit A0 = 15 : OK
25/12/2023 14:30:40: PowerLimit A3 = 15 : OK
25/12/2023 14:30:40: PowerLimit C1 = 20 : OK
25/12/2023 14:30:40: \\?\DISPLAY#TMX1401#5&134316e&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25/12/2023 14:30:40: \\?\DISPLAY#TMX1401#5&134316e&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25/12/2023 14:30:40: Screen = 60Hz : OK
25/12/2023 14:30:40: ScreenOverdrive = 0 : OK
25/12/2023 14:30:40: Eco flag : 0
25/12/2023 14:30:40: Mux flag : 1
25/12/2023 14:30:40: \\?\DISPLAY#TMX1401#5&134316e&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25/12/2023 14:30:40: \\?\DISPLAY#TMX1401#5&134316e&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25/12/2023 14:30:40: Screen = 60Hz : OK
25/12/2023 14:30:40: ScreenOverdrive = 0 : OK
25/12/2023 14:31:21: Key: 56
25/12/2023 14:31:23: Key: 56
25/12/2023 14:31:23: Key: 56
25/12/2023 14:31:24: Key: 56
```

**Desktop (please complete the following information):**
 - Windows 11 23H2 22631.2861
 - G14 2023 with 7940HS (780M) & Nvidia 4070
 - Laptop was modified (non-stock SSD & Intel AX210 card, but this did not cause issues for over a month of usage)

Currently installed updates:

![image](https://github.com/seerge/g-helper/assets/3624123/1bd8bf21-c348-4568-a91c-0dcfacd10054)

(On bios 313 at this time)

Program settings:

![image](https://github.com/seerge/g-helper/assets/3624123/ed034df0-2bc4-4235-9480-f479b2d411ad)

**Asus software**
- Armoury Crate uninstalled manually through its own uninstaller
- MyASUS uninstalled
- G-Helper reports 0 ASUS services running
- Never ran any "debloating" or "privacy" scripts

**Comment by seerge** [comment]
@MaxLebled hello,

If it was "slow" after update (i.e. after literal restart), I would say it's just some hiccups on windows side (or on hardware side?)

You can also try to completely uninstall (from device manager) and reinstall Asus System Control Interface, as all "controls" happen via this thing, and if it's slow to respond - all actions will be slower correspondingly

**Comment by seerge** [comment]
@MaxLebled P.S. I see that you were on battery when launched app, so it tried to disable GPU (for Optimized mode), which were refused by bios (hello asus), that would be also a reason for "freeze". And is most probably [related to this ](https://github.com/seerge/g-helper/discussions/1042)

```
25/12/2023 14:29:49: GPUEco = 1 : 0
```

So I would also try to reboot here :)

**Comment by MaxLebled** [comment]
I see! I'd never run into that bug where the GPU configuration gets itself stuck in a bad state, and I'd assumed that I would notice brightness being stuck, not being able to set Eco, etc.

I *am* noticing now that I am indeed unable to set Eco now during this program run. Standard works, but choosing Eco/Optimized (on battery) just displays "Changing ..." for a while... and then GPU Mode continues displaying "iGPU + dGPU" anyway.

I'll keep an eye out for the other variant of this bug (where the app keeps being slow even after it opens, and it's a power mode change, not GPU mode change, that causes the app to freeze.

**Comment by seerge** [comment]
@MaxLebled well, on your screenshot Optimzed mode is ON and laptop is on battery at the same time Eco has failed (dGPU is on in title / Optimized button has blue border instead of green for eco)

Most probably your laptop managed to power off while having dGPU disabled (for example hibernated in sleep or just run out of power on battery). 

Simple restart will solve the thing for you

There is nothing I can do here, as this is bios/driver issue behind all this that app already tries to solve by "Enable GPU on shutdown feature" :)
