### ISSUE TITLE
Can't start g-helper

### ISSUE THREAD

**Issue by Olshan** [seerge/g-helper#179]
Faulting application name: GHelper.exe, version: 0.45.0.0, time stamp: 0x63ed82c1
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2728, time stamp: 0xe7e53a4e
Exception code: 0xe0434352
Fault offset: 0x000000000002cd29
Faulting process id: 0x2b58
Faulting application start time: 0x01d964b44f237d47
Faulting application path: C:\Users\Olshan\Desktop\GHelper.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: ae28bd03-98c1-48b1-b243-29b1c4b68a2b

I'm on AtlasOS 64bit (it's just debloated Windows 10)

**Comment by seerge** [comment]
It should be a second error in Event Log next to this one, containing actual reason of crash - can you post that too ?

**Comment by Olshan** [comment]
> It should be a second error in Event Viewer next to this one, containing actual reason of crash - can you post that too ?

Hello! Sure

Application: GHelper.exe
CoreCLR Version: 7.0.423.11508
.NET Version: 7.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementEventWatcher.Start()
   at ASUSWmi.SubscribeToEvents(Action`2 EventHandler)
   at GHelper.Program.Main()

**Comment by seerge** [comment]
It says it can not connect to asus WMI, you need to have https://dlcdnets.asus.com/pub/ASUS/nb/Image/CustomComponent/ASUSSystemControlInterfaceV3/ASUSSystemControlInterfaceV3.exe installed as readme says.

**Comment by Olshan** [comment]
> It says it can not connect to asus WMI, you need to have https://dlcdnets.asus.com/pub/ASUS/nb/Image/CustomComponent/ASUSSystemControlInterfaceV3/ASUSSystemControlInterfaceV3.exe installed as readme says.

Yes, but i already have it's installed in my system

**Comment by seerge** [comment]
Then it could be damaged, try to reinstall as explained in https://github.com/seerge/g-helper/discussions/145

**Comment by Olshan** [comment]
> Then it could be damaged, try to reinstall as explained in #145

I tried this method and it didn't work for me, so I just installed default Windows 10, and now it works. Thanks!
