### ISSUE TITLE
Ambient backlight mode not working on G-Helper version 1.40 & 1.41

### ISSUE THREAD

**Issue by YmmitZtrol** [seerge/g-helper#1790]
## Bug Description:

The ambient keyboard backlight mode is functioning correctly in version 1.39. However, starting from version 1.40 and continuing in version 1.41, the ambient light mode is not working as expected.

## Steps to Reproduce:
1. Open G-Helper Version 1.39.
2. Select the ambient light mode. (Confirmed working)
3. Update G-Helper to version 1.40 or 1.41.
4. Select the ambient light mode again.
5. Notice that a single color, light blue, is displayed on the keyboard backlight.
6. Attempt to change the backlight color by changing the solid colors on the screen (Red, Green, Blue). The keyboard backlight does not change.
7. Additionally, try adjusting the brightness of the backlight when the ambient mode is selected. The brightness remains constant, even when the "off" OSD (On-Screen Display) is shown.

## Observed Behavior:
When the Asus services are started, the keyboard backlight color changes from light blue to a reddish color. However, the color remains constant despite the screen cycling through various colors. The brightness key-bindings also do not work, as the keyboard backlight stays at a constant brightness even when the "off" OSD is shown. Stopping the Asus services and restarting G-Helper does not resolve this issue.

## Expected Behavior:
The ambient mode should change the backlight color, and the keybindings should be able to adjust the keyboard brightness accordingly.

## Additional Information:
- App Logs: [log.txt](https://github.com/seerge/g-helper/files/13766886/log.txt)
- Desktop:
   - Operating System: Windows 11 Home
   - Laptop Model: Zephyrus G15 GA503
- Asus Software:
   - Armoury Crate: NOT INSTALLED
   - MyASUS: NOT INSTALLED
   - Asus Services: NOT RUNNING

**Comment by seerge** [comment]
@YmmitZtrol hello, this is cause someone else has misinformed me about GA503 functionalities, and i added it to the list of devices with limited RGB support. 

This build should work 
https://github.com/seerge/g-helper/files/13761489/GHelper.zip

**Comment by YmmitZtrol** [comment]
@seerge Hello, thanks for your reply. Unfortunately the build you provided doesn't work and has the same issues as I reported before.

I forgot to mention that my exact model is the GA503RW-LN106W

**Comment by seerge** [comment]
@YmmitZtrol ok, can you try this build ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/13770595/GHelper.zip)

**Comment by YmmitZtrol** [comment]
@seerge I'm still experiencing the same issues. After launching the new version, my keyboard backlight turned off. I tried changing the mode to static, and it displayed the correct color. However, when I switched back to ambient mode, the static mode color persisted instead of changing. 

Log File: [log.txt](https://github.com/seerge/g-helper/files/13770890/log.txt)

**Comment by seerge** [comment]
@YmmitZtrol seems like your device really needs a special approach (it's actually the only one asus model that has "own" way to set backlight brightness from all devices ...)

Try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/13770916/GHelper.zip)

**Comment by YmmitZtrol** [comment]
Okay so after trying this build out, what seems to happen is that 'ambient' mode mirrors the previous backlight mode used. For example if I change from static to ambient, the static color is shown. If I change from strobe to ambient, the strobing effect is shown. This also happens when trying to use the 'heatmap' backlight mode.

Good news is that the brightness keybindings work even on ambient/heatmap mode.

Log file:
[log.txt](https://github.com/seerge/g-helper/files/13770970/log.txt)

**Comment by seerge** [comment]
@YmmitZtrol try this one

[GHelper.zip](https://github.com/seerge/g-helper/files/13771035/GHelper.zip)

**Comment by YmmitZtrol** [comment]
@seerge Thank you! That build fixes the issue!

Thank you so much for your time and for helping me out.

**Comment by seerge** [comment]
Great

**Comment by selfish-imp** [comment]
Similar problem, please help. My laptop: G713QM (4 RGB zones): ambient screen flickers.
