### ISSUE TITLE
[Feature Request] Current Fan Mode in settings and Full mode addition

### ISSUE THREAD

**Issue by NULL0B** [seerge/g-helper#1794]
Hi, Nice project and many thanks.

G-helper is showing as balanced mode for fan but is currently set in performance mode

Model: Asus vivobook pro k6604

![image](https://github.com/seerge/g-helper/assets/26231330/3cfc69a3-0294-4218-a702-b207f0c1db6c)

Also ProArt comes with a Full speed fan mode that can be useful as bios is rejecting fan curves.

**Comment by seerge** [comment]
@NULL0B hello.  

1. You can't "read" modes, only set them. So your ProArt app won't reflect settings set in G-Helper and vice-versa,
2. Your device doesn't support  custom fan curves in a first place
3. If you want to enable 4th ("full speed") mode - check how to do that in config https://github.com/seerge/g-helper/issues/1301#issuecomment-1715814968

**Comment by seerge** [comment]
@NULL0B Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks

**Comment by NULL0B** [comment]
Hi @seerge, sorry for the late reply. Thanks for the build. Will update you on this. Thanks
