### ISSUE TITLE
Optimized Mode on ROG Flow X13 GV301RE (2022) Doesn't Work

### ISSUE THREAD

**Issue by ajball4221** [seerge/g-helper#1797]
When Optimized Mode is enabled in GHelper and I plug in my laptop (I've tried both 65W and 100W chargers), the dGPU doesn't turn on. Switching to Standard and Eco mode works as expected though. 

1. Unplug laptop
2. Enable Optimized Mode
3. Plug in laptop 
(GPU Mode Remains iGPU only)
or
1. Have laptop plugged in and set to Standard Mode
2. Enable Optimized Mode
(GPU Mode Switches to iGPU only)

**Expected behavior**
When the laptop is plugged in, Optimized mode should switch the GPU mode to iGPU+dGPU or keep it in that mode if Standard was enabled previously

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13773283/log.txt)

**Screenshots or screencasts**
<img width="310" alt="image" src="https://github.com/seerge/g-helper/assets/108492173/61978e45-e2eb-4300-be39-7e9443cdb808">
<img width="308" alt="image" src="https://github.com/seerge/g-helper/assets/108492173/aeea2a2d-6028-47a1-a04f-f88dd6443247">

**Desktop (please complete the following information):**
Windows 11 22H2
ROG Flow X13 GV301RE (2022)

**Asus software**
Armory Crate uninstalled
MyAsus uninstalled
No asus services installed or running (according to GHelper)

Thank you for taking a look at this!

**Comment by seerge** [comment]
@ajball4221 do you have "Keep GPU disabled on usb-c" checked under extra settings?

**Comment by ajball4221** [comment]
Wow that's embarrassing, yes I did and it works now. Sorry for wasting your time
