### ISSUE TITLE
Question about temperature

### ISSUE THREAD

**Issue by IgoBa** [seerge/g-helper#1798]
I apologize in advance for my English and technical knowledge.
My laptop is ASUS TUF FX 706IU. After installing your program, the regular laptop freezes stopped. This is the second month now, I’m not afraid to launch any program or just turn on the laptop and see the blue screen of death (IRQL NOT LESS OR EQUAL and DPC_WATCHDOG_VIOLATION). You are a great man.
I have a question, purely out of curiosity.
I remember how, before installing your program, when I launched the game, streams of very hot air blew from the right and left sides of the laptop. Now there is a warm blow, only from the right side. The left hand does not feel warm. This is simple curiosity. Why is that?
When playing, CPU temperature 70C, GPU 60C
![Снимок экрана 2023-12-26 225947](https://github.com/seerge/g-helper/assets/153825154/3d5d2185-07e3-4ef0-b99a-ea0c37958e32)
![Снимок экрана 2023-12-26 230023](https://github.com/seerge/g-helper/assets/153825154/e1bd3942-a80e-44a4-a217-49f253072c7b)
![Снимок экрана 2023-12-26 230043](https://github.com/seerge/g-helper/assets/153825154/ab00e45e-6a10-4c46-af65-9d05962357f3)

**Comment by seerge** [comment]
@IgoBa probably your computer consumers less power and exhausts less heat.
