### ISSUE TITLE
On screen Display (OSD) for microphone

### ISSUE THREAD

**Issue by pratyakshm** [seerge/g-helper#180]
**Is your feature request related to a problem? Please describe.**
When ASUS apps (Armoury Crate & MyASUS) aren't installed, there's no OSD. Installing G-helper helped with the performance plans OSD (i,e. G-Helper displays OSD when we switch between Silent, Performance and Turbo). 
But when we press the Mic button, there's no OSD.

**Describe the solution you'd like**
G-helper displays OSD when Mic is toggled using the Mic button

**Describe alternatives you've considered**
N.A.

**Additional context**
Model: GA401QH

**Comment by seerge** [comment]
Hello, as readme says - you need to have https://dlcdnets.asus.com/pub/ASUS/nb/Image/CustomComponent/ASUSSystemControlInterfaceV3/ASUSSystemControlInterfaceV3.exe installed , it comes with OSD (you can later disable unrelated services with debloat.bat)

It's out of scope of g-helper

**Comment by seerge** [comment]
You may also check this
https://github.com/seerge/g-helper/discussions/168

**Comment by pratyakshm** [comment]
Understood, thanks @seerge!
