### ISSUE TITLE
Random color mode

### ISSUE THREAD

**Issue by ChaerilM** [seerge/g-helper#1801]
**Is your feature request related to a problem? Please describe.**
I would like to have ripple effect in random color, and or other keyboard effects

**Describe the solution you'd like**
well it works?, maybe with same resource usage

**Describe alternatives you've considered**
going back to buggy armoury crate.

**Additional context**
don't have it :(

**Comment by seerge** [comment]
@ChaerilM if you mean some software-emulated backlight mode for Strix model (with per-key RGB), i simply can't do that as I don't have a device to even test that :)

Also it would consume resources (pretty much same as Ambient / Heatmap does now)

Why don't you try https://openrgb.org/ ?

**Comment by ChaerilM** [comment]
@seerge I.. guess, i could be software emulated, since it change color when key is pressed. i will try. thanks

completely unrelated issue, but could you add this to [Scoop](https://github.com/ScoopInstaller/Scoop) or others like chocolatey? so i could get update easily and automatic instead of visiting github

**Comment by seerge** [comment]
@ChaerilM scoop is already answered here https://github.com/seerge/g-helper/issues/1621 , but app has own update-checker that will prompt to update every time a new final release is out

**Comment by seerge** [comment]
Closing as not planned, as it's impossible to do on this stage

**Comment by ChaerilM** [comment]
@seerge what about wave speed / travel speed, brightness setting, and an off mode
