### ISSUE TITLE
[Feature request] Auto-close when non-ghelper window is selected

### ISSUE THREAD

**Issue by pawelkondraciuk** [seerge/g-helper#1802]
**Is your feature request related to a problem? Please describe.**
I'd love to see an option to make GHelper popup-like so if you select other window (move focus outside the app, moving focus to settings should not close the app) then app window will close (but app will be still running in background).

**Describe the solution you'd like**
"Lose focus action" in settings with options: 
- No action (does nothing, app window will move to the background)
- Aways on top (same as current keep on top)
- Close (closes the window)

**Comment by seerge** [comment]
@pawelkondraciuk i didn't get what you want

If you just select other window it doesn't close g-helper's window. Furthermore if you close g-helper's window, it doesn't quit app, as it stays running in tray.

**Comment by pawelkondraciuk** [comment]
I'd like to close g-helper's window when other window is selected - basically when focus is lost.

**Comment by seerge** [comment]
@pawelkondraciuk i think it's an overkill :) + it will be difficult to do, as app has multiple windows.

If you want to visually change modes, why don't you just use right-click context menu from tray icon that already exists ? it closes like you want.

**Comment by updawg** [comment]
He knows how to close the window, he is asking for a QOL improvement to the
gui where if it loses focus it closes. This request is somewhat normal
behavior for a systray program window.

**Comment by pawelkondraciuk** [comment]
I tend to use ghelper like quick settings (when you click on wifi/sound/battery), open window, change something (like one time 100% charge or enable dGPU when charging through USB-C) and go back to the work by selecting different window. When "Alawys On Top" is not enabled then GHelper stays in open apps in menu bar. When it is then I need to close it manually. That is just to make life easier.

**Comment by seerge** [comment]
@pawelkondraciuk you already have a context menu that behaves like that

![Screenshot 2023-12-27 160721](https://github.com/seerge/g-helper/assets/5920850/3eb57c60-7026-4541-b188-5baefeb53726)

As for closing main window on loosing focus, I'm not in a favor of that behavior atm :)
