### ISSUE TITLE
When using battery standby, the laptop will appear in a false death state.

### ISSUE THREAD

**Issue by Vainglory-Vinda** [seerge/g-helper#1803]
When the battery is in standby mode, if the screen remains idle for a long time, it will go completely black and only display a mouse cursor. The only solution to this problem is to perform a forced restart. (My model is M16 2022)

**Comment by seerge** [comment]
> ## NOTE
> Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
> Please respect the time of the developer. Thanks.

**Comment by Vainglory-Vinda** [comment]
> > ## 注意
> > 没有明确信息或要重现的场景和日志的错误报告将被关闭而没有答案。请尊重开发者的时间。谢谢。`%AppData%\GHelper`

I am very sorry, I will try to provide detailed information for similar issues in the future. Thank you for your understanding and patience.
