### ISSUE TITLE
About the GPU default dynamic boost wattage value in ROG Flow Z13 2022 model

### ISSUE THREAD

**Issue by RyouAkino** [seerge/g-helper#1806]
Mr. Seerge

Hello, I really love G-helper, thank you very much for creating such amazing tool.

Problem: I have a small issue with the GPU default dynamic boost wattage value in my ROG Flow Z13 2022 model, it was set to 25W. However, the default value 2022 model was 5W according to offical site, when I used the 25W profile it would cause malfunction report of CPU behavior in Cyberpunk 2077, after I set it to 5W, the issue was gone forever. I hope you can change the default wattage value in new update.

 - OS: Windows 11
 - Laptop model: ROG Flow Z13 2022 i9 RTX3050ti
 - All Asus software uninstalled, no Asus service was runing in background

[log.txt](https://github.com/seerge/g-helper/files/13791045/log.txt)

Thank you for hard work.

RyouAkino

**Comment by seerge** [comment]
@RyouAkino hello, how do you know that default is 5W? 

As far as I remember you can't see settings in default modes, and what you see while open Manual - is just a default slider positions, that make no effect until actually applied (pretty much same as power sliders in g-helper mean nothing until Apply is clicked) ? 

But you can set any value of course :)

**Comment by RyouAkino** [comment]
Thanks for your rely. When I bought this laptop in Asus website show a default wattage of 35W and max boost of 40W, in MSI afterbunner 40W will be the max. In CPU section i do need to click apply but in GPU section I cannot find an apply button. I am pretty sure when I slide the bar the boost value will apply to the computer because the benchmark increase. The default in GPU dynamic boost section is 25W and I can see the frame time in cyberpunk fluctuates a lot in 25W than manually set to 5W.

**Comment by seerge** [comment]
@RyouAkino I meant "apply" in Armoury (as you can't see real value of a boost anyhow else) Do we speak about turbo ? :)

Anyway, I'm glad that you have figured out optimal settings for yourself for this specific game.

**Comment by RyouAkino** [comment]
The 35W default and 40W max is shown in the GPU information section in Armoury Crate,I cannot change the wattage in any mode include manual mode. I have not test in other mode but in turbo mode of Armoury it can only boost to 40W in 2022 model. The default max boost wattage in Armoury is 5W I think.

**Comment by seerge** [comment]
Do you mind to post a screenshot of how Armoury looks in your case ?

**Comment by RyouAkino** [comment]
<img width="330" alt="Screenshot 2023-12-29 195039" src="https://github.com/seerge/g-helper/assets/155130530/dfa216e8-8653-4146-a525-3ef485989b8a">
There shows a max TGP of 40W in the screenshot

**Comment by RyouAkino** [comment]
Sorry I got the screenshot from youtube. I do not want to install armoury again.

**Comment by seerge** [comment]
@RyouAkino i see. I think this is just part of Armoury's UI.  Most probably it's not a "real" measurements, but something they hardcoded in design. As it also says 0mv.

Have you tried running some GPU heavy benchmarks (like Furmark) and see if GPU in your device actually can go higher ? (like if you would set Dynamic boost to 15W or 25W?)

**Comment by RyouAkino** [comment]
I tried set it to 25W but the benchmark score will not go higher, 5W is max when boost.

**Comment by RyouAkino** [comment]
In Manual mode in armoury the GPU memory can overclock to 300 but in g-helper the max is 250, could I ask if it is possible to get a 300 boost in future update of g-helper? the gpu can run stably in 300 in manual mode.

**Comment by seerge** [comment]
@RyouAkino ok :) so I think it's just limited to 5W in BIOS for your model.

Do you still get that error in cyberpunk ? or it was just a random coincidence probably? :) 

You can increase clock offsets to anything you want via config
https://github.com/seerge/g-helper/wiki/Power-user-settings#higher-maximum-gpu-clock--memory-offsets

**Comment by RyouAkino** [comment]
I got error almost every time I play the game when set it to 25W but I did not get any error in 5W. Thank you for your reply.

**Comment by seerge** [comment]
@RyouAkino can you set it to something in the middle, like 10W or 15W?

**Comment by RyouAkino** [comment]
Yes I can, but the score stays the same. Max wattage is also 40W. Sorry that I have not test the stability in game, it usually need some time to get to crash depending on scence.

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/13793115/GHelper.zip) this build should limit slider to literalyl 5w only :)

I'm asking cause I don't want to "accidentaly" restrict it, if model supports different values

**Comment by RyouAkino** [comment]
Thank you very much for such rapid reply. G-helper will become better and better :)
