### ISSUE TITLE
[Feature request] synchronize cpu and gpu fan speeds

### ISSUE THREAD

**Issue by lyz000** [seerge/g-helper#1808]
Hi! thank you for your wonderful App. Would you consider implementing this function?

Some devices have a vapor chamber, if a cpu/gpu has a higher temp, the fan on other side could be helpful.
To do that, cpu and gpu together use a single fan curve, and both fan speeds are related to the higher temp in cpu and gpu.

Thank you :)

**Comment by seerge** [comment]
@lyz000 hello, that's not possible as you can't control fans manually anyhow :)
