### ISSUE TITLE
Add Per-core Curve Optimizer Feature

### ISSUE THREAD

**Issue by fscottcopeland** [seerge/g-helper#1810]
Referencing pervious discussions on https://github.com/seerge/g-helper/issues/1606

I'd like to re-request this pretty please...

See https://github.com/irusanov/ZenStates-Core

Dual CCD CPUs often have 1 "worse" CCD which can work with a much lower negative CO offset. A global CO setting can therefore reduce the amount of performance one can extract. Here are my stable(ish) settings using the above tool:

![image](https://github.com/seerge/g-helper/assets/91984658/b9754415-c02b-43ea-be49-ffa1cdaf0559)

Most people don't know G-Helper exists. So people who do use G-Helper over Armory Crate are more likely the "Power users" or tweakers anyway. I don't think I'd be alone in wanting this feature...pretty please! G-Helper is already a niche tool :)

**Comment by MrHumanRebel** [comment]
Would be very nice to have like in UXTU.
https://github.com/JamesCJ60/Universal-x86-Tuning-Utility

**Comment by seerge** [comment]
Hello, as I have answered before - from my point of view, this is too much for the app. Whole idea of G-Helper is to be lighter and easier to use alternative to AC :) I'm not targeting hardcore tinkerers. 

Current undervolting UX/UI is intentionally organized in as simple way as I could come up with. As 90% of the app users don't even use it in current form.

Therefore I don't think that making app look like a starship control panel in just to satisfy 10 people from ~ 60-70 000 (currently) active users and scaring rest is a good idea.

**Comment by MrHumanRebel** [comment]
Could be an "expert mode" toggle in the setings to enable these plus cool features, or disable is the user wants simple control.
Just an idea.
