### ISSUE TITLE
G-Helper not applying fan curves correctly.

### ISSUE THREAD

**Issue by fscottcopeland** [seerge/g-helper#1811]
Config and log files below:
[config.json](https://github.com/seerge/g-helper/files/13793908/config.json)
[log.txt](https://github.com/seerge/g-helper/files/13793909/log.txt)

G-Helper currently doesn't want to exactly respect the fan curves which I'm setting. It's confusing as I can untick the "Apply Custom Fan Curve" and the fans will actually **slow down** as they slow to the standard ASUS preset. I.e. the curve I'm setting isn't lower than what ASUS allows in th ebackground.

See image below for example:
![image](https://github.com/seerge/g-helper/assets/91984658/6ff8d1b0-63af-4b74-a908-f59ed956b743)
CPU @ 64c should have a fan speed of 30% according to graph, but instead it is 46%
GPU @ 45c should have a fan speed of 20% according to graph, but instead it is 40%

Zephyrus Duo 16 2023 on Windows 11 

No ASUS software installed apart from System Control Interface.

**Comment by seerge** [comment]
@fscottcopeland hello,

G-Helper is applying fan curves
```
2023-12-29 13:38:38: FanCPU = 28-32-3C-46-50-55-5A-5F-14-14-1E-28-32-3C-46-50 : OK
2023-12-29 13:38:38: FanGPU = 28-32-37-3C-41-46-4B-50-14-14-1E-28-32-3C-46-50 : OK
```
Rest is up to your BIOS. If you believe BIOS is not following cuves exactly you can contact Asus support about the matter.
https://github.com/seerge/g-helper/wiki/FAQ

Please check FAQ before submitting



Good luck.

**Comment by fscottcopeland** [comment]
Balls. You're right. Checking the RPM rather than percentage is more at parity with the graph. Thank you. Annoying that % scale doesn't work fully :(

**Comment by seerge** [comment]
For asus 0% = 0RPM, 1% = 1800RPM, 100% = 6000RPM (or whatever your max is)

Y-Axis in % is added by request from one of the users, to make it convenient to migrate custom curves from AC to the app. As in AC scale is done in exactly that way
