### ISSUE TITLE
Screen Brightness malfunction after dGPU ON (FX507ZV)

### ISSUE THREAD

**Issue by tonynadtochy** [seerge/g-helper#1812]
Device: ASUS TUF F15 2023 (FX507ZV)
OS: win 11 v. 23H2 build 22631.2861
_All drivers updated, full system reinstall tried before adding this report_

**Problem description:**
After powering on dGPU, screen brightness value becomes constant and can't be changed. Workarounds: 1) power off dGPU; 2) reboot laptop (however brightness control will malfunction after powering off dGPU until another reboot). 

**Video showcasing the problem:**
[YouTube](https://youtu.be/lP_cINPrpUQ)

**GHelper log:**
[log.txt](https://github.com/seerge/g-helper/files/13794515/log.txt)

**My two cents:**
I'm tired of Armoury Crate's cluttery interface, memory leaks and resource hunger. I love GHelper's clean interface, exclusive fnlock feature and ease of switching cpu boost modes. Nonetheless the bug described above makes it challenging to use. _Please pay attention to the last part of my video: Armoury turns on dGPU by activating and deactivating it multiple times on this laptop model. This might be the key to resolving the issue._ If any additional info is needed I'm willing to cooperate!

**Comment by seerge** [comment]
Nvidia bug is already covered here https://github.com/seerge/g-helper/discussions/1042
