### ISSUE TITLE
FN (lock) button behaviour

### ISSUE THREAD

**Issue by Crocktopus0** [seerge/g-helper#1813]
**Is your feature request related to a problem? Please describe.**
When enabling FN lock in the app, it makes sense to change FN lock button function to TOGGLE FN LOCK

**Describe the solution you'd like**
I think it's native on other (non Asus) laptops. This way there is no need to use FN+F4. 

**Describe alternatives you've considered**
-

**Additional context**
HUGE thanks for your work! I just sent you 10 Eur as a way to say thank you very much!

**Comment by seerge** [comment]
@Crocktopus0 hello, that's not possible. ``Fn`` button doesn't produce any key-code by itself, only in certain very limited combinations
