### ISSUE TITLE
Eco mode for GPU doesn't work

### ISSUE THREAD

**Issue by cosmanee** [seerge/g-helper#182]
Bug report: Eco mode not working.

Description: When I select Eco mode, the app does not apply the changes and reverts to Standard mode. This happens every time I try to switch modes.

Steps to reproduce:
1. Open the app.
2. Tap on Eco mode.

Expected result: The app should show Eco mode and reduce the battery consumption and data usage.

Actual result: The app shows Standard mode and does not change the performance.

Device information: G14 GA401II, Windows 11

No Armoury Crate, no My Asuss
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/129634849/229326304-728eb827-67a3-4933-b5fb-6c6a1853eeb8.gif)

Edit: decided to reopen the issue as I found this photo proving that Eco mode does work indeed on the 2020 G14. I have no clue which version of G-helper is this.
![IMG_2756](https://user-images.githubusercontent.com/129634849/229327213-064bce0e-1399-4e5e-96df-c5ab4f0a0f71.jpg)

**Comment by cosmanee** [comment]
Where do I find the app logs?

**Comment by seerge** [comment]
Hello, 2020 devices don't support dGPU disabling on hardware level
https://github.com/seerge/g-helper#i-cant-set-eco-mode-disable-dgpu-on-my-g14-2020

older version of the app could mistakenly show uncorrect UI.

**Comment by cosmanee** [comment]
The observed discharge rate indicates that the dGPU was not active. This is consistent with the estimated battery duration, which implies that Eco mode was enabled. However, in the newer versions of the application, I cannot deactivate the dGPU and the battery life is reduced to a maximum of two hours.

**Comment by seerge** [comment]
@cosmanee on your model dGPU is controlled by windows (it's called MSHybrid), not by asus bios - therefore it can not be disabled via the app. I assume in armory you also can't disable dGPU?

You power drain I would attribute rather to a coincidence / randomness, that windows was putting GPU to sleep (that it can do with any model). You can control that (to the certain extent) via windows power plan :

![Screenshot 2023-03-30 135950](https://user-images.githubusercontent.com/5920850/229374634-1661e36b-ab2b-41a3-a8ef-4efe731a73bd.png)

P.S. If you prefer placebo effect of old version of the app, where it was doing exactly the same as now, but NOT checking if GPU switch worked or not - you can download and use older versions, they are all available under releases :) 

You can also run following command in powershell as admin teling bios to disable gpu (that doesn't work tho)

``(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00090020, 1)``

**Comment by cosmanee** [comment]
Thank you for providing accurate information. I appreciate your patience. Good Luck!
