### ISSUE TITLE
On-screen notification for multizone toggle

### ISSUE THREAD

**Issue by cgarst** [seerge/g-helper#1822]
**Is your feature request related to a problem? Please describe.**
G Helper wonderfully allows us to key bind "Toggle Miniled". When using this key bind, we don't know if we're toggling miniled/multizone on or off. Depending on environment and screen content, it may be challenging to determine when multizone is already enabled or disabled. 

**Describe the solution you'd like**
When pressing the keybind, produce a state changing toast on-screen notification along the lines of "Multizone On" or "Multizone Off". 

**Describe alternatives you've considered**
Open and close G-Helper to see if "Multizone" has a red line around it.

**Additional context**
This should produce a more consistent experience to using other binds key such as keyboard brightness or fan speed.

**Comment by seerge** [comment]
@cgarst hello, this is really first world problems to be honest, but this build should show a toast notification for situation when Multizone is toggle via hotkey.

[GHelper.zip](https://github.com/seerge/g-helper/files/13801428/GHelper.zip)

**Comment by cgarst** [comment]
This works perfectly, thanks!

**Comment by cgarst** [comment]
@seerge Still working great in SDR, and noticed a minor UX bug involving HDR. When in HDR, multi-zone is always on by design. So, in this case where HDR is enabled the toast either shouldn't happen or always display "Multi-Zone" when the key is pressed. The toggle currently rotates the two toasts when HDR is enabled despite having no effect.

**Comment by seerge** [comment]
@cgarst this build should just skip whole action if HDR is on 
[GHelper.zip](https://github.com/seerge/g-helper/files/13818644/GHelper.zip)
