### ISSUE TITLE
unplugging crashes g14 - crash in 3 to 4 seconds on an eco restart unless quickly turbo

### ISSUE THREAD

**Issue by YomamaNow** [seerge/g-helper#1825]
At first I doubted something this fatal to it could be the app cuz I saw the joke before and was like nah, but then I saw the other guy having same problem too on earlier build, and apparently since .100 which would likely be when it about started for me. given that it is now likely ghelper, it has me nearly tempted to go back to the armoury bloat (since this never occurred with that). I have certainly loved ghelper otherwise, but dealing with constant bsods due to the additional problem that my cord gets regularly loose already  is an enormous frustration. any fix?

**Comment by seerge** [comment]
If your device struggles turning on Eco mode check this topic https://github.com/seerge/g-helper/discussions/1042 and always make sure that you turn off / reboot laptop while being in standard. It's nvidia driver issues

Also make sure to have latest and clean driver installation, check [Troubleshooting](https://github.com/seerge/g-helper/wiki/Troubleshooting)

Good luck

> ## NOTE
> Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. Please respect the time of the developer. Thanks.

**Comment by YomamaNow** [comment]
I am AMD and Radeon and my issue is a bit inverse to what you are mentioning. If anything it is more akin to this post: https://github.com/seerge/g-helper/issues/860

I keep G-helper always on Turbo and Ultimate 24 hours a day, 7 days a week. If I didn't also have a loose power cord, which eventually happens with all of them as my laptop is always on my lap, it might not be so frustrating. As soon as the cord disconnects from charging for about 3-4 seconds or just a bit longer - boom a random bsod will show up and the computer will reboot. this is an issue that is unique to g-helper in as much as I can tell and has yet to ever go away in all the versions i have tried since approximately .124. Perhaps I was lucky enough or this individual was  lucky enough that for a couple versions that didn't happen, but it has certainly happened for the bulk of them. Thus, please fix. thanks

**Comment by seerge** [comment]
@YomamaNow if you don't have Optimized mode, then you don't turn off GPU while uplugging and this is absolutely unrelated to other post anyhow.

Besides that app does literally nothing when you plug or unplug, so if your hardware crashes after unplugging - reasons are outside of the app. There is nothing to fix.

You have intentionally ignored (again) all requested debug information from the issue template.
