### ISSUE TITLE
Web-interface for GHelper

### ISSUE THREAD

**Issue by dszubov** [seerge/g-helper#1826]
Is possible to make the web-interface for GHelper? Sometimes it necessary to make some changes without AltTab.

Currently using RDPWrap and connecting to administrator session, where's GHelper working, for make changes. Web-page will be more effective.

**Comment by seerge** [comment]
@dszubov hello, that's not possible. G-Helper is desktop app and would require a lot of changes for such extremely exotic requirement.

You can do somthing by yourself by calling different WMI calls via web somehow tho
https://github.com/fumetsu0/Laptops/tree/main/Asus/WMI
