### ISSUE TITLE
Custom fan curve doesn't seem to be working on G18 G834JY

### ISSUE THREAD

**Issue by stormherz** [seerge/g-helper#1828]
Hi!

First of all, thanks for such a great piece of software!

I'm trying to apply custom fan curve on G18 G834JY (bios 321), but I'm not sure if it's working properly (though I assume I'm doing something stupidly wrong)

1. Set Mode to Balanced
2. Go to 'Fans + Power'
3. Click Apply custom fan curve
4. Run something heavy to load cpu/gpu
5. Verify if tracked CPU/fan RPM correlate with fan curve
6. Seems like CPU temp/fan RPM is not related to the fan curve (screenshot attached)

**Expected behavior**
It was expected to receive 2200 RPM for ~60C CPU temp. but it's tracked as 3700

**Desktop (please complete the following information):**
 - OS: Windows 11
 - G18 G834JY (bios 321)
 - g-helper 0.141.0

**Asus software**
- Armoury Crate (never been installed)
- MyASUS installed
- Asus services are disabled

Log file 
[log.txt](https://github.com/seerge/g-helper/files/13802667/log.txt)

Screenshot
![fan_curves](https://github.com/seerge/g-helper/assets/235075/d03fe6fb-2d8b-4186-abf2-6a5738c905a7)

**Comment by seerge** [comment]
@stormherz some models require to apply both power limits AND custom fan curves in order them to work (same as it happens in armoury).

If that doesn't have any effect - then this is how fans work on your device. App doesn't control them, they are controlled  by BIOS.
