### ISSUE TITLE
I extracted my endopoints but dont know what to do with them trying to get fan values

### ISSUE THREAD

**Issue by theblazinghood** [seerge/g-helper#1829]
this is what i got running the scan-atkacpi script
60023 : ffffffffffff0004 (-65532)
60024 : 15df1022 (366940194)
60026 : 0 (0)
60061 : ffffffffffff0000 (-65536)
80041 : ffffffffffff0000 (-65536)
80042 : ffffffffffff0000 (-65536)
80043 : ffffffffffff0000 (-65536)
80044 : ffffffffffff0000 (-65536)
100023 : 0 (0)
100054 : ffffffffffff0000 (-65536)
110013 : 27 (39)
110015 : ffffffffffff000
0 (-65536)
110016 : ffffffffffff0000 (-65536)
120057 : 0 (0)
120061 : 0 (0)

i have also attached the dsdt.dsl file
[dsdt_zip.zip](https://github.com/seerge/g-helper/files/13803718/dsdt_zip.zip)

**Comment by seerge** [comment]
You just did a scan, not extracted enpoints. And this issue should be just a comment in https://github.com/seerge/g-helper/issues/38
