### ISSUE TITLE
[Feature Request] GameVisual display profiles

### ISSUE THREAD

**Issue by nobubblegums** [seerge/g-helper#183]
Thanks for your great work! One thing I'm missing from AC is the GameVisual display profiles, they're mostly gimmick but Scenery can help when using outdoors or in a very bright room, and EyeCare is a bit easier on the eyes. 
I've found .icm profiles in "C:\ProgramData\ASUS\GameVisual", yet loading them with Windows Color Management tool did nothing. Thanks!

**Comment by seerge** [comment]
Hello, Visual styles are implemented purely software level in armoury, and when it's uninstalled - there is no way to get them back.

I would advice to use similar feature in AMD Adrenalin or NVidia control panel as they do same thing.

There are no plans to replicate that in app at the moment :)

**Comment by seerge** [comment]
Added in latest release https://github.com/seerge/g-helper/releases
