### ISSUE TITLE
Improved accessibility of the following features under screen readers

### ISSUE THREAD

**Issue by anmi2004** [seerge/g-helper#1830]
# There are a couple of other minor issues that I'm not sure can be optimized

- If I select Enhanced Mode or Silent Mode, can I broadcast the selected state when navigating to the control.
- When interacting with the lock fn key feature, I can't read if the state is locked or not.
- I was unable to determine if the Charge Limit feature was enabled or not, and the progress bar for that feature was not interacting properly.

Thank you very much for your prompt help, I didn't expect to solve this problem so quickly, it's much appreciated!

**Comment by anmi2004** [comment]
Most progress bars are interactive with screen readers

**Comment by seerge** [comment]
@anmi2004 hello.

> If I select Enhanced Mode or Silent Mode, can I broadcast the selected state when navigating to the control.

I believe this is already the case. Mode buttons are groupped under a single panel, that have following label when selected : "Mopde: <mode name>". I just double-checked it with NVDA app.

> When interacting with the lock fn key feature, I can't read if the state is locked or not.
Added, please check attached build

> I was unable to determine if the Charge Limit feature was enabled or not, and the progress bar for that feature was not interacting properly.
Unofrtunately, charge limit is not a progress bar UI component, it's a custom UI element that doesn't support keyboard controls at all. Chaning this would require rewriting a huge part of code, so I can't afford this on this stage.

Build : [GHelper.zip](https://github.com/seerge/g-helper/files/13804317/GHelper.zip)

**Comment by anmi2004** [comment]
> @anmi2004 hello.
> 
> > If I select Enhanced Mode or Silent Mode, can I broadcast the selected state when navigating to the control.
> 
> I believe this is already the case. Mode buttons are grouped under a single panel, that have following label when selected : "Mode: <mode name>". I just double-checked it with NVDA app.
> 
> > When interacting with the lock fn key feature, I can't read if the state is locked or not.
> 
> Added, please check attached build
> 
> > I was unable to determine if the Charge Limit feature was enabled or not, and the progress bar for that feature was not interacting properly.
> 
> Unfortunately, charge limit is not a progress bar UI component, it's a custom UI element that doesn't support keyboard controls at all. Changing this would require rewriting a huge part of code, so I can't afford this on this stage.
> 
> Build : [GHelper.zip](https://github.com/seerge/g-helper/files/13804317/GHelper.zip)
> 

When I interact with controls like Quiet Mode Performance Mode, he does read out to check Quiet Mode and such.But what I mean is that when I'm not sure what mode I'm in, I can't read out what mode is checked when I browse that panel.He does read the selected status after I click on that mode, but when I browse through the modes, he can't read out which mode I have checked!
当我与安静模式性能模式等控件交互的时候，他确实能读出以选中安静模式之类的内容。但我的意思是，当我不确定我处于什么模式的情况下，我在浏览该面板的时候，无法读出已选中什么模式。我点击了该模式之后，他确实会读出选中状态，但当我浏览这几个模式的时候，他却无法读出我选中了哪个模式

**Comment by anmi2004** [comment]
> @seerge 

Regarding the charging limit feature, if it is not possible to change the interactive control, could you add a combo box control on the right side of the progress bar to set a few levels to choose from, such as 60%, 80%, 90%, etc.?

关于充电限制功能，如果无法更改交互控件，您可以在进度条右侧添加一个组合框控件来设置几个级别以供选择，例如60%、80%、90%等。

**Comment by seerge** [comment]
@anmi2004 

>But what I mean is that when I'm not sure what mode I'm in, I can't read out what mode is checked when I browse that panel.

It does exactly that, when you open main window or set focus to modes panel it reads current mode. I.e. "Mode : Silent". At least NVDA does so perfectly for me

> Regarding the charging limit feature, if it is not possible to change the interactive control, could you add a combo box control on the right side of the progress bar to set a few levels to choose from, such as 60%, 80%, 90%, etc.?

No, that's not possible on this stage as I have explained.

**Comment by anmi2004** [comment]
@seerge 

> No, that's not possible on this stage as I have explained.

Would it be feasible to add a few fixed values in the settings?For example, 60%, 80% and 90%, we don't need to interact with the progress bar.

**Comment by seerge** [comment]
@anmi2004 it's already possible

You just need to open ``%APPDATA%\GHelper\config.json``

And modify ``charge_limit`` param there, that looks like

```
"charge_limit" : 80,
```

**Comment by anmi2004** [comment]
Thank you

**Comment by seerge** [comment]
@anmi2004 actually I have managed to add a keyboard controls for battery charge slider.

Now it can get focus from ``Tab`` key and ``Left / Down`` keys lower value, "Up / Right`` keys increase value. Every time value is changed - it will re-set focus on itself, to force narrator to re-read current value.

Check this build

[GHelper.zip](https://github.com/seerge/g-helper/files/13805633/GHelper.zip)
