### ISSUE TITLE
[Feature Request] The ability to replace custom modes with existing modes.

### ISSUE THREAD

**Issue by Skezsy** [seerge/g-helper#1831]
**Is your feature request related to a problem? Please describe.**
Not necessary but the ability to change turbo to a different logo, name would be neat. I know adding a custom mode is possible but if we could replace it with the Turbo button would be easier to access. I've recently got a type c to barrel jack charger so I wanted 1 mode for the 240W DC adapter and 1 for my 100W type c charger.

**Describe the solution you'd like**
The ability to create and name modes, and replace onto existing modes.

**Describe alternatives you've considered**
Using the (+) button to add custom modes.

**Comment by seerge** [comment]
@Skezsy you can customize your Turbo mode to everything you want already, so there is no need to replace it with something else.
