### ISSUE TITLE
Calculator opens two times while using hotkey

### ISSUE THREAD

**Issue by abs7001** [seerge/g-helper#1832]
https://github.com/seerge/g-helper/assets/147339034/7190a1e3-6b4d-40da-bf5e-34ff89dada58

I am facing issue in Asus tuf A15 FA506
Ghelper version: 0.141.0

The calculator is opening two times while pressing the hotkey for a single time

**Comment by seerge** [comment]
> ## NOTE
> Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. Please respect the time of the developer. Thanks.

**Comment by Meltryllis163** [comment]
I have the same problem. Maybe you didn't disable the ASUS services, so the hotkey (Fn+NumEnter) triggers both G-Helper and the ASUS service. Then you get two calculator processes.
