### ISSUE TITLE
GPU Dynamic Boost has no effect

### ISSUE THREAD

**Issue by mrunknown9999** [seerge/g-helper#1834]
Setting a Dynamic boost limit for the GPU has no effect. Tested on a Flow X13 2023 with 4060 GPU using the Cyberpunk benchmark.
Attached the log file.
[log.txt](https://github.com/seerge/g-helper/files/13805655/log.txt)

**Comment by seerge** [comment]
@mrunknown9999 hello,

In a log i see that sometimes your BIOS accepts value, sometimes it doesn't :) (hello asus)

```
01/01/2024 21:16:37: PowerLimit C0 = 5 : 0
```

```
30/12/2023 22:06:47: PowerLimit C0 = 25 : OK
30/12/2023 22:06:47: PowerLimit C2 = 87 : OK
```

What boost range did you have in Armoury ?

**Comment by seerge** [comment]
Try this build, it will set boost second time, if first time it was refused by some reason

[GHelper.zip](https://github.com/seerge/g-helper/files/13805677/GHelper.zip)

**Comment by mrunknown9999** [comment]
I uninstalled AC directly and used g-helper instead. I tried setting different boost limits, and all had no effect on the wattage, in cyberpunk balanced  mode = 40-45 watt range. I will try the new build you sent me. Thank you.

**Comment by mrunknown9999** [comment]
[log.txt](https://github.com/seerge/g-helper/files/13805694/log.txt)
 it is the same, boosting to 43 watt with dynamic boost set to 5 watt (balanced mode), same as without setting a limit.

**Comment by seerge** [comment]
@mrunknown9999 try to set 15 as limit (i think this is what your device supports maximum)

And also try to use https://geeks3d.com/furmark/downloads/ Furmark, as it loads only GPU and not CPU, so leaves much more headroom for GPU.

**Comment by seerge** [comment]
@mrunknown9999 ah, and also use Turbo mode! :) i think Balanced mode may be very limited in BIOS

**Comment by mrunknown9999** [comment]
I think there is a confusion, I want to limit the GPU wattage by using the limit boost feature, in order to use the laptop with a 100Watt charger without battery discharge and using Balanced mode.
If I remember correctly my 4060 GPU has a base wattage of 35 watt and up to 60 it's dynamic boosted. 
Using the 5 watt dynamic boost limit I was hoping to achieve a 40 watt max GPU wattage. 
Much better would be the ability to limit the boost to 0. But then again if it's not possible I can use the frequency limiter :)

**Comment by seerge** [comment]
@mrunknown9999 that's not possible.

Look at the specs of your device https://rog.asus.com/laptops/rog-flow/rog-flow-x13-2023-series/spec/

```
NVIDIA® GeForce RTX™ 4060 Laptop GPU
ROG Boost: 1520MHz* at 60W (1470MHz Boost Clock+50MHz OC, 45W+15W Dynamic Boost)
```

You can only adjust it in range from 45W to 60W. You can't limit it even more.

Alternative would be indeed either frequency limiter or just frame limiter via nvidia software

**Comment by mrunknown9999** [comment]
Ok, thank you for the clarification! I will close the bug then.

**Comment by seerge** [comment]
@mrunknown9999 btw, out of curiosity . What is maximum power that your GPU can consume ? Under turbo + 25W boost ? does it even work ? or it neglets everything above 15W of boost?

**Comment by mrunknown9999** [comment]
The max GPU consumption I saw in games was 55 watt max. I just tried to set Turbo mode and set the dynamic boost to 5 watt and was expecting 50 watt max but it shoot over at 53-55. So my conclusion, at least for my model the dynamic boost doesn't do anything.

**Comment by seerge** [comment]
@mrunknown9999 well, endpoint (for seting it) exists. 

But it could be that it's just hardcoded in each mode after that (like 45W for balanced and 60W for turbo)
