### ISSUE TITLE
Turning off laptop backlight on boot has no effect

### ISSUE THREAD

**Issue by Beck-919** [seerge/g-helper#1835]
**Describe the bug**
The feature to turn off keyboard backlight on boot available in the 'Extra' settings in the app does not work/.

**Clear scenario to Reproduce**
1. Go to Extra
2. Turn off 'Boot' under 'Laptop Backlight'
3. Shutdown system and wait for a minute (restart doesn't have issue; fast start-up off).
4. Turn on machine, keyboard backlight lights up on cold boot.

**Expected behavior**
No keyboard backlight on cold boot.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13805722/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/58395882/a90b323d-4e20-43a5-996d-ff3aabcd2f6a)

**Desktop (please complete the following information):**
 - OS: Windows 11 (23H2, build 22631.2861)
 - Laptop model: ROG Zephyrus G15 GA503RW

**Asus software**
- Armoury Crate: Uninstalled
- MyASUS installed: Yes
- Other Asus services running in background

**Additional context**
System is dual booted, but Ubuntu 22.04 doesn't seem to have any control over keyboard backlight whatsoever.
Due to this issue, keyboard backlight persists on Linux, with no actual way to turn it off.

**Comment by seerge** [comment]
@Beck-919 what do you understand under "boot"? This is a hardware setting for a keyboard, it applies only to double-flash of keyboard on start. 

After that, while your laptop is actually loading windows (or ubuntu), it's not "boot" anymore. It's a Awake

**Comment by Beck-919** [comment]
If I understand right the 'boot' option check is for whether or not keyboard lights up prior to jumping to Windows/Linux during power-on, yes?

I have it reduced the brightness to zero in Windows when awake and it works as intended.

Preferably I also need it to be off at boot. As mentioned in the issue, Ubuntu has virtually no control over this, so I need it off going into it.

Supporting this statement, I can get it off if I restart to Linux from Windows or shutdown from Windows then boot to Linux (as the Windows brightness setting seems to persist). But this doesn't work if I cold boot to Linux.

**Comment by seerge** [comment]
@Beck-919 it's not :) it's keyboard animation when you start your laptop.

Most of the devices remember brightness on reboot, and doesn't turn it ON again.

G15 is notoriosly buggy (in many senses), and apparently just forgets brightness on reboot. I can't do anything about that as as soon as G-Helper will start it will set brightness agian.

**Comment by Beck-919** [comment]
I think I am a bit confused by 'animation', I believe we are refering to the same thing. My G15 model only have white backlight and it turn on immediately on system power-on (when starting the laptop) then tuning off when booting to Windows (before login). 

There is no flashing/animation on boot. It is static for time on the ROG logo.

**Comment by seerge** [comment]
@Beck-919 everything after "rog logo" on your screen is "awake" state. 

You keyboard has no idea what your computer is doing, booting windows / linux / staying on boot-loader selection or playing games. It's all "awake" state.

**Comment by Beck-919** [comment]
It actually makes sense now. Turning off 'awake' turns everything off completely.

The other options doesn't seem to affect anything at all! Does that mean there is on 'boot' flashing for this model?

**Comment by seerge** [comment]
@Beck-919 all keyboards have same 4 flags. 

It could be that "boot" is just a single flash, or just responsible for the backlight the moment you see rog logo.

You can turn off Awake, and turn on Boot to see what it does :)

As for the rest - i can't change anything here, it's up to keyboard firmware.

**Comment by Beck-919** [comment]
Thanks for the quick response and all the work you put in this project!
