### ISSUE TITLE
Bugs, Temp Slider Support Model: Tuf F15 (FX507Z)

### ISSUE THREAD

**Issue by MaxHornet** [seerge/g-helper#1841]
Hello Dev , I have used the G helper and its really amazing!

Request:
1) I have an Asus Tuf f15 (FX507Z) which has an i7 cpu the temperatures get really high even with wattage limit, it cannot be undervolted but can you add cpu temp limit slider ? like the gpu temp limit this may help control the temperatures.

Bugs:
I am also getting a bug where after turning on gpu from eco, i cannot control the brightness it gets stuck.

Some Suggested Optional Features Request:
There are also some other ac features, cpu core configuration ,(legacy drm) which disables all e cores, and win key lock, which are very usefull for me.

Optional Feature to save Settings, Import and Export to a file  maybe? 

I will completely delete armory crate if those features gets added :) 

Right now i use armory crate alongside g-helper due to those mentioned ac fetures, works fine, that stop all asus services feature is neat!

**Comment by seerge** [comment]
@MaxHornet hello,

1. Intel CPU's can't be undervolted via software. You can check if there is an option for you in BIOS (F2 on boot)

2. Brightness / Eco mode - is an issue with nvidia drivers, check this topic and just enable ``Enable GPU on shutdown`` https://github.com/seerge/g-helper/discussions/1042

3. "cpu core configuration ,(legacy drm) which disables all e cores " can be configured in BIOS as well (they require reboot anyway)

4. To save settings, you can just make a copy of ``%appdata%\ghelper\config.json``

**Comment by MaxHornet** [comment]
Hey Thanks ,That was fast reply  xd. 

For the brightness bug Do i have to download the pre release version to get the extra option, Enable gpu on shutdown?

**Comment by MaxHornet** [comment]
> @MaxHornet no, its available for a long time

i am using version 0.141.0, there is no option for that

**Comment by seerge** [comment]
@MaxHornet I have added it for your device
[GHelper.zip](https://github.com/seerge/g-helper/files/13820332/GHelper.zip)

**Comment by MaxHornet** [comment]
@seerge Hey Thanks That was quick! 
I will try it out :)
