### ISSUE TITLE
Anime Matrix - stuck pixels

### ISSUE THREAD

**Issue by salembegic** [seerge/g-helper#1844]
**Describe the bug**
I've encountered a glitch with anime matrix on my 2023 Asus G14. If I leave the anime matrix turned on and close the laptop so that it goes to sleep, it first starts showing the "meteor" animation, but if I leave it like that for a long time (multiple hours), it glitches out and stops the animation, but a few pixels stay turned on and can't be turned off without a reset. I still haven't caught the moment when it happens, but I've noticed the glitched pixels a few times after I got home from uni, so around 5-6h. It also seems like it's the same pixels that stay stuck, or at least they are close, since it always seems to happen in that area. 

**Clear scenario to Reproduce**
1. Turn on anime matrix (I usually have it on medium brightness and on audio visualiser or ROG logo)
2. Close the laptop and don't touch it for multiple hours
3. After a while it glitches out, a few pixels stay turned on. Laptop work normally and even anime matrix animations work without a problem, but those pixels can't be turned off
4. After restarting the laptop, everything goes back to normal

**Expected behavior**
I guess the fix would be for the meteor animation to keep playing indefinitely, but honestly, I would appreciate it if you added a checkmark to completely turn off the anime matrix when the laptop goes to sleep. It happened multiple times that I had it set to audio visualiser, and since no sounds were playing, it looked like it was off. And just when I closed the laptop and went to bed, the meteor animation started, and I had to get back up to turn it off (hahahah sorry about the rant). 

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13825199/log.txt)

**Screenshots or screencasts**
![20231218_153110](https://github.com/seerge/g-helper/assets/75506370/edd2d495-71bf-4d20-9475-1f64ea20fce2)
This is what pixels that stay on look like.

https://github.com/seerge/g-helper/assets/75506370/0c19a8d8-3117-4d03-989a-cd3e2f21be8d
Other animations play normally over them, but those pixels stay on. I also tried turning on binary banner animation since it basically covers the whole matrix, thinking that it would refresh them, but they stay on even after that. I also tried fixing it with completely black photo, but no luck.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: Asus ROG G14 GA402XI-N2047W

**Asus software**
Both Armory Crate and MyAsus are uninstalled, and I stopped other Asus services via G-Helper

**Additional context**
I really haven't experimented too much with this since I needed the laptop for university, but I'll try to reproduce the glitch over the next few days, and I'll take some better photos and videos. If you need me to try anything, feel free to ask. I also have hibernation turned on after 60 minutes, so that might be related to it.

**Comment by seerge** [comment]
@salembegic hello,

It's a hardware or firmware glitch of the matrix itself :) you can't control that anyhow on app level.

Even ``meteor`` animation is just hardcoded in the matrix, and being played automatically when laptop is asleep.

The only solution for you would be just to turn matrix off if it bothers you :)  

You can also try hardware reset from https://github.com/seerge/g-helper/wiki/Troubleshooting, mb it will erase firmware glitch

I can't do anything from the app side here

**Comment by UncleSocks** [comment]
@RitamCODE 

I fixed a similar issue on my 2021 Zephyrus G14 by uploading a white background on AniMe Matrix, cranking up the contrast, and turning the brightness to -100. See attached screenshot of my settings below:
![image](https://github.com/user-attachments/assets/c34c94ea-7208-489f-aed5-f72ce00b4f53)


This was done using Armoury Crate but you can try the same method on G-Helper, and see if it fixes your issue.

**Comment by RitamCODE** [comment]
Tried it ... but it did not work for me
