### ISSUE TITLE
Click factory default button can significant decrease the input lag but after reboot the effect disappeared

### ISSUE THREAD

**Issue by RyouAkino** [seerge/g-helper#1845]
Mr. Seerge

Hello, recently I have some issuses with the factory default function.

Problem: I keep all settings default, when running a game, I found click the factory default in g-helper before or when running a game can significantly decrease the input lag in game (I test the game to run more than 10 mins), and the ram usage of g-helper increase from 18M to 23M and stays there. I am happy with that. However, after I reboot the computer or restart the app, the input lag turn back to normal, and I have to click the factory default button again to reproduce the same effect. I did not change the settings in g-helper and I think it should be the default setting. I really want to know what is happening here.

OS: Windows 11
Laptop model: ROG Flow Z13 2022 i9 RTX3050ti
All Asus software uninstalled, no Asus service was runing in background

[log.txt](https://github.com/seerge/g-helper/files/13827635/log.txt)

Thank you for the hard work.

RyouAkino

**Comment by seerge** [comment]
@RyouAkino hello,

"Factory defaults" , just sets same mode again without setting any (purely optional) custom limits that you can set after. 

You can create as many such modes in the app as you want, you don't need another button for this.

I don't know what causes input lag on your device, but GPU drivers are generally known to be a reason for mouse lags for example. 

I would advice to check https://github.com/seerge/g-helper/wiki/Troubleshooting

**Comment by RyouAkino** [comment]
Thank you very much. I try to clean install the Nvidia driver then the input lag was gone now. You are very helpful.
