### ISSUE TITLE
GHelper not opening, can't end process.

### ISSUE THREAD

**Issue by govarthenan** [seerge/g-helper#185]
### Description
GHelper can't be ended by the task manager. It doesn't appear in the tray. Can't be ended by `taskkill` either. Can't be opened.

When trying taskkill:
```cmd
C:\Windows\system32>taskkill /F /PID 15544
ERROR: The process with PID 15544 could not be terminated.
Reason: There is no running instance of the task.
```

When I try to open the exe by clicking on it:
![image](https://user-images.githubusercontent.com/81749104/229362606-a91ea432-4403-475c-b09c-4fb97353bd9b.png)

**Clear scenario to Reproduce**
I don't know how to. It has been working correctly for almost a week now, and then this happened.

**App Logs**
[Link to logs](https://pastebin.com/JuYBju2n)

**Screenshots**
- Taskmanager **Details** tab:
![image](https://user-images.githubusercontent.com/81749104/229362100-0aab1f22-5213-43a9-b05d-9a5e58e66acc.png)
- Taskbar tray area
![image](https://user-images.githubusercontent.com/81749104/229362124-0bffa2bc-2395-49e7-a978-04b331997730.png)

**Desktop:**
 - OS: Windows 10
 - Laptop model: G713QR-ES96 (Strix G17 2021)

**Asus software**
- Armoury crate uninstalled using ASUS's tool
- Armoury Crate interface is toggled OFF in BIOS
- MyASUS is left installed
- Other Asus services running in background
  - ![image](https://user-images.githubusercontent.com/81749104/229362462-aa943201-a2df-450a-a6cf-3ec9797dd64f.png)

**Comment by seerge** [comment]
Hello, i don't know what happened to process on your computer :) But it could be that it was either launched from other user or from different rights (check GHelper task in windows Task Scheduler if it is set as admin user mb?) You can try to restart if task has hanged by some reason.

App itself behaves correctly, it says that other process is running (which is true). 

Closing, cause there is nothing to fix.
