### ISSUE TITLE
An error appears when clicking on a peripheral, and the mouse drops frames.

### ISSUE THREAD

**Issue by zjfqcdb** [seerge/g-helper#1850]
**Describe the bug**
An error appears when clicking on a peripheral, and the mouse drops frames.

**App Logs**

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GHelper.AsusMouseSettings.VisualizeCurrentDPIProfile() in D:\a\g-helper\g-helper\app\AsusMouseSettings.cs:line 866
   at GHelper.AsusMouseSettings.VisualizeMouseSettings() in D:\a\g-helper\g-helper\app\AsusMouseSettings.cs:line 690
   at GHelper.AsusMouseSettings.RefreshMouseData() in D:\a\g-helper\g-helper\app\AsusMouseSettings.cs:line 470
   at GHelper.AsusMouseSettings..ctor(AsusMouse mouse) in D:\a\g-helper\g-helper\app\AsusMouseSettings.cs:line 111
   at GHelper.SettingsForm.ButtonPeripheral_Click(Object sender, EventArgs e) in D:\a\g-helper\g-helper\app\Settings.cs:line 1440
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Screenshots or screencasts**
<img width="325" alt="image" src="https://github.com/seerge/g-helper/assets/17118740/6a02a532-2a35-487c-be89-8b36a64683ee">

**Comment by seerge** [comment]
@zjfqcdb try this build, there shouldn't be an error, but please attach a full log from it (as was clearly described in issue template)

What mouse do you have ?

[GHelper.zip](https://github.com/seerge/g-helper/files/13840904/GHelper.zip)

**Comment by IceStormNG** [comment]
Please also let us know which mouse you use.

**Comment by zjfqcdb** [comment]
> @zjfqcdb try this build, there shouldn't be an error, but please attach a full log from it (as was clearly described in issue template)
> 
> What mouse do you have ?
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/13840935/GHelper.zip)

ROG Strix Impact Ⅱ （Wirelsee）

**Comment by seerge** [comment]
@zjfqcdb 
>  please attach a full log from it

**Comment by seerge** [comment]
Closed as abandoned

**Comment by zjfqcdb** [comment]
> @zjfqcdb
> 
> > please attach a full log from it

sorry， I haven't used the computer for a few days and only saw the message today. Here's my log file。
[Uploading log.txt…]()

**Comment by IceStormNG** [comment]
I see the mouse reporting error packets and taking between 40ms and 50ms to respond and then resoponds nothing anymore (and is considered "gone").
The part that shows what was sent last to the mouse is already overwritten. The log only keeps the last 1000 lines.

**Comment by martin6982** [comment]
Hi @seerge I got a user encounter the same situation, and I got his log file.
[log.txt](https://github.com/seerge/g-helper/files/14722790/log.txt)

he also mentioned that after he opend AC to adjust the DPI, this issue just disappeared.

hope the log file could help you to clarify the issue.

**Comment by IceStormNG** [comment]
```
2024/3/22 下午 08:30:10: TUF GAMING M3 (Gen II): Read DPI Setting 1: DPI: 1600, Color (255, 0, 0)
2024/3/22 下午 08:30:10: TUF GAMING M3 (Gen II): Read DPI Setting 2: DPI: 3200, Color (255, 0, 0)
2024/3/22 下午 08:30:10: TUF GAMING M3 (Gen II): Read DPI Setting 3: DPI: 6400, Color (255, 0, 0)
2024/3/22 下午 08:30:10: TUF GAMING M3 (Gen II): Read DPI Setting 4: DPI: 16000, Color (255, 0, 0)
```

I also see whey... The mouse apparently has a 7000 DPI sensor, so this reading makes not sense.
Do you know the DPI values that the mouse is supposed to be set to from Armoury crate?

**Comment by martin6982** [comment]
> ```
> 2024/3/22 下午 08:30:10: TUF GAMING M3 (Gen II): Read DPI Setting 1: DPI: 1600, Color (255, 0, 0)
> 2024/3/22 下午 08:30:10: TUF GAMING M3 (Gen II): Read DPI Setting 2: DPI: 3200, Color (255, 0, 0)
> 2024/3/22 下午 08:30:10: TUF GAMING M3 (Gen II): Read DPI Setting 3: DPI: 6400, Color (255, 0, 0)
> 2024/3/22 下午 08:30:10: TUF GAMING M3 (Gen II): Read DPI Setting 4: DPI: 16000, Color (255, 0, 0)
> ```
> 
> I also see whey... The mouse apparently has a 7000 DPI sensor, so this reading makes not sense. Do you know the DPI values that the mouse is supposed to be set to from Armoury crate?


I don't have M3 gen2, but according to the [official website](https://www.asus.com/accessories/mice-and-mouse-pads/tuf-gaming/asus-tuf-gaming-m3-gen-ii/), I think it's between 100 & 8000?

<img width="485" alt="image" src="https://github.com/seerge/g-helper/assets/130006105/a7ae5617-9450-4696-b008-b1f87085c5be">

**Comment by IceStormNG** [comment]
Alrigt. I found the issue. The Gen II has 100-8000 but with 50 increments instead of 100.

Please test this build (or forward it to the person with the Gen II mouse and the issue that you reported)
[GHelper.zip](https://github.com/seerge/g-helper/files/14723256/GHelper.zip)

**Comment by martin6982** [comment]
> Alrigt. I found the issue. The Gen II has 100-8000 but with 50 increments instead of 100.
> 
> Please test this build (or forward it to the person with the Gen II mouse and the issue that you reported) [GHelper.zip](https://github.com/seerge/g-helper/files/14723256/GHelper.zip)

Okay I will give him this build, thank you so much!

**Comment by IceStormNG** [comment]
Great. Please let me know whether it fixes the issue or whether there is still something wrong.
