### ISSUE TITLE
No hotkey controls the screen brightness down/up on Flow X13 (2021)

### ISSUE THREAD

**Issue by supergungod** [seerge/g-helper#1852]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. Please respect the time of the developer. Thanks.

**Describe the bug**
With Asus AC, the hotkey Fn+F7/ Fn+F8 can control the screen brightness down/up.
With G Helper, Fn+F7/F8 can't control the screen brightness down/up anymore.
At least, this hotkey should workable.

**Expected behavior**
I hope the function hotkeys should workable well.
With AC on Flow X13, the following hotkey are the function
Fn+F7 = screen brightness down
Fn+F8 = screen brightness up
Fn+F11= sleep mode
Fn+F12= fly mode
With G-help
Four of them are not workable, it means they are no function.

**App Logs**
maybe not necessery

**Screenshots or screencasts**
It's just no function with the above hotkey, so I don't know how to provide screenshots

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: Flow X13 (2021) with AMD R9 5900HS, 32GB ram and 3050Ti

**Asus software**
No, I uninstall everything from Amoury Crate

**Additional context**
No

**Comment by seerge** [comment]
@supergungod neither AC nor G-Helper doesn't handle brightness hotkeys. They emit windows brightness up / down commands on hardware level.

Please check this topic for an issue that can be realted to you https://github.com/seerge/g-helper/discussions/1042

You have demonstratively ignored template issue and didn't include app logs, therefore I can't help anyhow further.
