### ISSUE TITLE
Option to change between Sleep/Hibernate for Auto Clamshell Mode 

### ISSUE THREAD

**Issue by BunniKaitlyn** [seerge/g-helper#1855]
**Is your feature request related to a problem? Please describe.**
There is no problem, just that I would prefer hibernating instead of sleeping, auto clamshell mode only sets it to sleep.

**Describe the solution you'd like**
I'd like a dropdown next to the Auto Clamshell Mode option so that you can select how you'd want to put the device to rest, e.g. "Sleep" and "Hibernate", with "Sleep" being the default.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by seerge** [comment]
@BunniKaitlyn actually app remembers your "original" setting for lid-close (which was sleep most probably) and when you turn clam-shell off (or just unplug / disconnect monitor) it would revert to that specific setting.

It's stored in ``%appdata%\ghelper\config.json`` under
```
"clamshell_default_lid_action" : 1,
```

You can replace it to 2 , it will be hibernate :)

https://github.com/seerge/g-helper/blob/48c6f4f6596be353c868527a2d3ec6e76c2644da/app/Helpers/ClamshellModeControl.cs#L130

**Comment by BunniKaitlyn** [comment]
Oh! That's neat to know, I did try to see if G-Helper would respect the original setting I had but in all of my testing it'd just go back to "Sleep". It might be worth exposing this setting in the UI :P

**Comment by seerge** [comment]
@BunniKaitlyn it saves that on it's first launch :) 

If config is already populated, it assumes that that was "original" value 

I don't want to expose such exotic things into UI, but I have added it to list of power-user settings
https://github.com/seerge/g-helper/wiki/Power-user-settings#lid-close-action-when-clamshell-mode-is-off
