### ISSUE TITLE
Sudden power drops / interruptions crash G helper

### ISSUE THREAD

**Issue by govarthenan** [seerge/g-helper#1858]
**Describe the bug**
Whenever I experience a power cut or a power drop (electricity is interrupted and restored in a second), G Helper crashes. It can be neither opened or closed, and the power profile indicator overlay on screen is just stuck there forever. I believe this might happen because the charging state of the device changes within a second and it causes G Helper to crash.

**Clear scenario to Reproduce**
1. Make sure G Helper is running.
2. Make sure Power profile, GPU state and Screen refresh rate change on connecting to power.
3. Quickly switch of charger and turn it back on within a second (flip power off and on)

**Expected behavior**
1. You should see the power profile indicator overlay stuck on screen like shown in below image
![image](https://github.com/seerge/g-helper/assets/81749104/24c8e050-cddc-4327-8247-188597655a27)
2. You can't open/close G Helper, through hotkeys, clicking on the icon in tray, or using task manager.
3. `End task` button in task manager does remove the power profile indicator overlay from the screen, and make the icon disappear from tray. But it still remains in task manager and I can't launch a new instance of G Helper.

**App Logs**
You can find the entries related to the bug on and after `1/6/2024 11:41:41 AM` in the logs: [log.txt](https://github.com/seerge/g-helper/files/13848609/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Laptop model: 2021 ROG Strix G17 (G713QR)
 - CPU: AMD Ryzen 9 5900HX
 - GPU: NVIDIA RTX 3070
 - Screen: FHD 300/60Hz

**Asus software**
- Armoury Crate not installed. AC service installed, not running.
- MyAsus installed. Haven't used in like 6 months.
- From ASUS, only `ASUS MultiAntenna Service` service running
- According to G Helper, 0 ASUS services are running. ( I stopped all ASUS services using G Helper)

**Additional context**
Happy to provide any more information. I'd like to get rid of this bug as this often breaks my workflow, and i guess for others too.
I'm a junior dev, so I'd love to help solve this issue.

**Comment by seerge** [comment]
@govarthenan you have Optimized GPU mode that turns GPU OFF when unplugged and ON when plugged in back. If you would do that very frequently it may act sometimes, due to the way it's implemented by ASUS.

I would recommend just to set Standard if you have unreliable power source.

I can't change anything here.

Good luck
