### ISSUE TITLE
GPU fan at 0rpm when on custom fan curve

### ISSUE THREAD

**Issue by DragoJess** [seerge/g-helper#1859]
**Describe the bug**
On my Zephyrus G14 GA401QM, When "Apply custom fan curve" is checked, the GPU fan always goes to 0rpm, both physically and reported by the software. This happens on both iGPU and dGPU, all power modes, and both plugged in and not plugged in to charger. It still behaves this way after using "Calibrate". The CPU fan does run at the selected speed.

**Clear scenario to Reproduce**
1. Go to "Fans+Power"
2. Check "Apply custom fan curve"
3. The GPU fan will then slow down until it reaches 0rpm. 

**Expected behavior**
Since the GPU is at 69 degrees, it should run the fan at ~4400rpm as I selected in the custom fan curve controls. 

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13848654/log.txt)

**Screenshots or screencasts**
Custom fan curve off, GPU fan at correct speed
![Custom fan curve off](https://github.com/seerge/g-helper/assets/113305843/88ccdcbe-c72a-4141-ba59-27a4a46b898b)

Custom fan curve on, GPU fan at 0rpm
![Custom fan curve on](https://github.com/seerge/g-helper/assets/113305843/c3a4b61b-4b03-49c1-a337-dcb3670070bd)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home version 22H2
 - Laptop model: ROG Zephyrus G14 GA401QM (Ryzen 9 5900HS, 16GB memory DDR4-3200, RTX 3060, Bios version 415)

**Asus software**
- Armoury Crate: Not installed
- MyASUS: Not installed
- Other Asus services running in background: All turned off

**Additional context**
Not sure

**Comment by seerge** [comment]
@DragoJess hello,

G-Helper doesn't control your fans anyhow in realtime, they are controlled by BIOS. Even with the custom fan curve (please check FAQ)

If BIOS decides to behave it like that, that's how it's programmed on your model.

Some models, start acting if you restart in Eco mode (i.e. with GPU being off), check similar issue https://github.com/seerge/g-helper/issues/1612#issuecomment-1876943224. People can experience that with AC or G-Helper, as it doesn't depend on the app in a first place.

You may just select "Enable GPU on shutdown", it may prevent that.

Good luck

**Comment by DragoJess** [comment]
I understand, thank you.

**Comment by seerge** [comment]
@DragoJess let me know if restarting (in Standard gpu mode) helps

**Comment by DragoJess** [comment]
@seerge 
Restarting with standard GPU mode doesn't help, and Turbo mode also doesn't, but I found that the GPU fan will always runs at the speed the lowest temperature point is set at in the fan curve. When I increase the minimum fan speed it runs at that speed. 
I think that'll be okay for now. Thank you for the help and quick responses

**Comment by seerge** [comment]
@DragoJess Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks

**Comment by DragoJess** [comment]
I will try that, thank you!
