### ISSUE TITLE
[Feature Request] Show Profile on all displays

### ISSUE THREAD

**Issue by Twel12** [seerge/g-helper#186]
Currently when the mode is switched then it only shows on main screen, would be nice to show on all of the displays as sometimes you are just focusing on second screen let's say of laptop connected to a monitor.

**Comment by seerge** [comment]
Hello, i'm afraid that's too specific use-case that you have. I don't have plans to add toasts to multiple displays for now :)

**Comment by Twel12** [comment]
understandable, thanks for the great project either way :)
