### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by xSimone** [seerge/g-helper#1861]
Nothing too big, thought it'd be something nice to fix. ♥

<img width="482" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/dd954bff-6b94-4e1e-8ebd-4972a68e0fc3">

Also, may I ask, what do the colours mean in updates? What is Grey colour meaning?

**Comment by Kikimahe** [comment]
Hi, 

Ghelper connects directly to the Asus server to check updates. I
t's the Asus server that has a spelling mistake. :)

- Green : Your driver is up to date
- Red : There is an update available.
- Gray : Ghelper could not determine the version of the driver on your laptop or it's software from the Microsoft Store.

**Comment by seerge** [comment]
@xSimone it's how it's spelled on asus website :) i can't fix that, sorry

**Comment by xSimone** [comment]
I had a feeling. :f 
No surprise from Asus. 
Evangenlion
