### ISSUE TITLE
Option to force gpu on

### ISSUE THREAD

**Issue by ErayOzcanUCLL** [seerge/g-helper#1863]
**Is your feature request related to a problem? Please describe.**
So it is sometimes hard to enable to gpu of my laptop asus g17, for example when i plug it into a monitor, i always have to put my laptop in hibernate and then turn back on cause it doesnt want to turn on the gpu when i connect the hdmi... situations like that where it would be nice to force the gpu on. 

**Describe the solution you'd like**
An option in ghelper to perhaps force the gpu on, but i have doubts that this isn't fixable with software and is hardwired because i can't even open nvidia control panel cause the nvidia gpu is fully turned off instead of on standby to be used.

**Describe alternatives you've considered**
I have considered leaving ghelper in ultimate mode so it always uses the gpu but this drains the battery too much.

**Comment by seerge** [comment]
@ErayOzcanUCLL ``Standard`` GPU mode is when it's ON, it already exists in the app from the very beginning :)

There is nothing else I can add, you may want to do a clean GPU driver reinstall as it sometimes helps in troubleshooting problems
https://github.com/seerge/g-helper/wiki/Troubleshooting
