### ISSUE TITLE
Keyboard Not fully lit when using heat and ambient modes

### ISSUE THREAD

**Issue by Prince11592** [seerge/g-helper#1864]
Laptop Make and Model: Asus Strix G533QS

Firstly, I appreciate the availability of this excellent tool. I would like to address a concern regarding the keyboard backlighting on my Asus Strix G533QS. The issue is that the keyboard is not fully illuminated when using the heatmap and ambient modes. Any assistance in resolving this matter would be greatly appreciated.
![ambient](https://github.com/seerge/g-helper/assets/120901070/17beb2bb-b1dc-476a-a409-649a7ce4e68e)
![heatmap](https://github.com/seerge/g-helper/assets/120901070/c81356ee-e8f2-4d72-aa7d-ec27505841b6)
![static](https://github.com/seerge/g-helper/assets/120901070/8c71510e-3272-43a5-9a03-736050c750ba)

**Comment by seerge** [comment]
@Prince11592 hello, your device is quite old (and as far as I understand not the most wide spread), probably asus has some different protocol for setting colors in your case.

Since I don't have it physically it will be extremely difficult for me to figure out how to light missing keys.

Does https://openrgb.org/ work well for you if you try to set per-key (not whole keyboard) lightning there ?

**Comment by seerge** [comment]
@Prince11592 actually, I have one idea - can you try this build ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/13858252/GHelper.zip)

**Comment by Prince11592** [comment]
@seerge, I've utilized the GHelper you shared and am currently using the latest version. I also experimented with OpenRGB. All modes function flawlessly, except for the heatmap and ambient modes. My laptop is a 2021 model, and I am currently using version 0.145. and in openrgb set per key is greyed out for me
![20240110_101452](https://github.com/seerge/g-helper/assets/120901070/8d91c10e-4725-46db-95c4-dad94c9142ac)
![20240110_101458](https://github.com/seerge/g-helper/assets/120901070/3f6e37f6-61bb-401e-a69a-8bd643b2ff11)

**Comment by seerge** [comment]
@Prince11592 but did the build I have linked here improve Ambient / Heatmap? or some keys are still missing light?

**Comment by Prince11592** [comment]
Yes i tried with the build you provided

**Comment by seerge** [comment]
@Prince11592 in the build I provided, Ambient mode would just set a static color for your whole keyboard same as Static does, so it if it was no change / lighted keys were missing - you probably didn't launch correct exe or something :)

**Comment by seerge** [comment]
@Prince11592 can you try build from this thread again, and post a photo for how keyboard looks in Ambient mode ?

**Comment by Prince11592** [comment]
i used the file which u have shared please check the video too

https://github.com/seerge/g-helper/assets/120901070/ea6aaa9f-ecef-4cec-ae9a-7d6077d86ab1

![20240110_153636](https://github.com/seerge/g-helper/assets/120901070/6e305717-75bd-4020-8541-f47c9d7a9a06)
![20240110_153644](https://github.com/seerge/g-helper/assets/120901070/7b9915cc-6a27-4863-a358-a4bf4885e1c2)

**Comment by seerge** [comment]
@Prince11592 oke, so (based on your last photo) it seems like it works and all keys are lit ? :)

**Comment by Prince11592** [comment]
First photo is ambient and second photo is static, so in static it works perfeclty

**Comment by seerge** [comment]
@Prince11592 oke, can you try this build instead ?
[GHelper.zip](https://github.com/seerge/g-helper/files/13891807/GHelper.zip)

**Comment by Prince11592** [comment]
no backlight in both ambient and heatmap remaining modes work including new gpumode
![20240111_093053](https://github.com/seerge/g-helper/assets/120901070/4447a578-129d-40de-81f0-1f077d3524b1)

**Comment by seerge** [comment]
@Prince11592 can you try this build ?
[GHelper.zip](https://github.com/seerge/g-helper/files/13901900/GHelper.zip)

**Comment by Prince11592** [comment]
> @Prince11592 can you try this build ? [GHelper.zip](https://github.com/seerge/g-helper/files/13901900/GHelper.zip)

heatmap is working but ambient mode still need to fixed

**Comment by seerge** [comment]
@Prince11592 how does ambient mode behave ?

**Comment by Prince11592** [comment]
> @Prince11592 how does ambient mode behave ?

same like before no change space key \ key and three arrow keys light missing

**Comment by seerge** [comment]
@Prince11592 try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/13905145/GHelper.zip)

**Comment by Prince11592** [comment]
all keys are working now  but only single colour is being dispayed in ambient mode 

> @Prince11592 try this build [GHelper.zip](https://github.com/seerge/g-helper/files/13905145/GHelper.zip)

**Comment by seerge** [comment]
@Prince11592 i know :) cause that's the only way i can "fix" it for you . By setting single color, as i have no idea how to set missing individual keys.

**Comment by Prince11592** [comment]
ok thanks 

> @Prince11592 i know :) cause that's the only way i can "fix" it for you . By setting single color, as i have no idea how to set missing individual keys.

thank you so much for your support
