### ISSUE TITLE
DRR option request (Dynamic Refresh Rate)

### ISSUE THREAD

**Issue by Aragamiz** [seerge/g-helper#1866]
In G14 2024 , system can provide Dynamic Refresh Rate ,It can save battery or sync multi monitor fresh rate to one .
Request a option to change or use it . thk a lot .
![屏幕截图 2024-01-08 111128](https://github.com/seerge/g-helper/assets/20516214/1e66dac9-b899-41d5-9af0-dfc95860e5f1)

**Comment by seerge** [comment]
@Aragamiz hello, unfortunately those settings are not accessible via Windows API, so app can't change them.

You can set dynamic refresh rate manually, and just turn off Auto in G-Helper, then it won't override.
