### ISSUE TITLE
The adaptive backlight on the keyboard is blinking

### ISSUE THREAD

**Issue by kKarandash** [seerge/g-helper#1868]
Hello, The adaptive backlight on the keyboard is blinking
Model: ROG Strix G513QM

if you need a video, I can send it, thanks for earlier!

**Comment by kKarandash** [comment]
everything used to work fine, but after the update it started blinking

**Comment by kKarandash** [comment]
Uploading video_2024-01-08_08-47-31.mp4…

**Comment by kKarandash** [comment]
Uploading video_2024-01-08_08-47-31.mp4…

**Comment by kKarandash** [comment]
[https://youtu.be/9XhQqC_-_2U](url)

**Comment by kKarandash** [comment]
https://youtu.be/9XhQqC_-_2U

**Comment by seerge** [comment]
@kKarandash try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/13858246/GHelper.zip)

**Comment by kKarandash** [comment]
yes, good. Thanks you!!!

**Comment by RAGE-HERO7** [comment]
Bro why is your laptop keyboard looks different than mine..I also have G513QM but it doesn't have transparent wasd keys in my keyboard it's transparent only on the letters 🤨.
Are you sure your model is G513QM bro😒

i mean i know there are 2 variants exists as G513QM, 1 that comes with 2k@165hz DCIP3-100% Display, per key RGB lighting support on keyboard(which is what i have)

another one that comes with 1080p@300hz or 144hz 100% srgb, but don't know about keyboard lighting( if it is single zone or per key RGB supported keyboard 🤔) 

@seerge if the model Rog strix g15 G513QM exists with 2 types of keyboard lighting (single zone/perkey Rgb)
this can be a problem for you right😕 
but is it possible by adding 
the number that represent specific model of the device like (G513QM-HQ403TS) to avoid conflict , i will show you three different G513QM and there specific model number

![Screenshot_20240113_012709_Samsung Internet](https://github.com/seerge/g-helper/assets/154586512/8d91a06f-a502-4b09-90f5-78faf4e88c6b)
![Screenshot_20240113_012623_Samsung Internet](https://github.com/seerge/g-helper/assets/154586512/d58121d9-ab81-4107-b5a7-d822b0948027)
![Screenshot_20240113_012604_Samsung Internet](https://github.com/seerge/g-helper/assets/154586512/67d435fa-362a-4591-a0d8-cae0c66faf52)

**Comment by RAGE-HERO7** [comment]
![Screenshot_20240113_013227_Samsung Internet](https://github.com/seerge/g-helper/assets/154586512/b5318309-c6d9-4810-8c8b-81bf9948b973)
