### ISSUE TITLE
The brightness adjustment function is mapped incorrectly on the FA506 model

### ISSUE THREAD

**Issue by peckbniff** [seerge/g-helper#1869]
As a chinese speaking user of you software, i have to say you did a great job to develop this commuinity and software,but i found a issue is that on my model,which is FA506IV with 320 bios,the brightness adjustment function is mapped incorrectly,specifically,while the Fn-lock is on,when the brightness reduction button (F7) is pressed, the screen brightness increases, while when the brightness increase button (F8) is pressed, the brightness decreases.this problem won't happen when fn_lock is off.I am not good at English,hope what i said could let you know what happened and help you fix this bug.Thank you.
model: FA506 IV 4900H
system:win11
i uninstall the ac,keep 华硕管家（which is My Asus's Chinese Mainland version)on my computer.

**Comment by seerge** [comment]
@peckbniff hello, this build should have correct order
[GHelper.zip](https://github.com/seerge/g-helper/files/13858218/GHelper.zip)

**Comment by peckbniff** [comment]
Well done!The problem has been solved!Thanks^v^
