### ISSUE TITLE
GPU Fans stop spinning after applying custom fan curve

### ISSUE THREAD

**Issue by LucaSch1910** [seerge/g-helper#1870]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. Please respect the time of the developer. Thanks.

**Describe the bug**
Sometimes I want to ramp up the fans to 100% after 68°, or any temp point for the matter, my GPU Fans stop spinning and don't come back up until I reset to factory defaults the fan curve.

**Clear scenario to Reproduce**
1. Go to 'Extra'
2. Click on 'any point of the fan curve that is over the factory default'
3. Apply custom fan curve
4. Fans can be at any point (6800, 5900, 4800 RPM) and immediately start winding down all the way to 0.

**Expected behavior**
For the fans to go max rpm and cool the pc better.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13860636/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: [Windows 11 Home 23H2 Build 22631.2792]
 - ASUS Rog Zephyrus G15 GA503RM_GA503RM

**Asus software**
- All disabled

**Additional context**

**Comment by seerge** [comment]
@LucaSch1910 hello,

G-Helper doesn't control your fans anyhow in realtime, they are controlled by BIOS. Even with the custom fan curve (please check FAQ)

If BIOS decides to behave it like that, that's how it's programmed on your model.

I can't do absolutely anything about that.

Some models, start acting if you restart in Eco mode (i.e. with GPU being off), check similar issue https://github.com/seerge/g-helper/issues/1612#issuecomment-1876943224. People can experience that with AC or G-Helper, as it doesn't depend on the app in a first place.

You may just select ["Enable GPU on shutdown", it may prevent that.](https://github.com/seerge/g-helper/discussions/1042)

Good luck

**Comment by seerge** [comment]
P.S. Try to set a custom fan curve in Turbo mode (as AC's "manual" mode is actually Turbo with custom settings).

**Comment by LucaSch1910** [comment]
Hi! Thanks for the quick response!
First of all, now I'm using Turbo Mode and works correctly, but was on the same turbo mode that made the fans stop. It's an erratic behavior that I haven't been able to pinpoint to anything yet.
I'll attach a SS just in case, but this exact config sometimes 'breaks' them d:

![image](https://github.com/seerge/g-helper/assets/70332531/7acda649-f58f-4114-ae6c-650a05e7156b)

**Comment by seerge** [comment]
@LucaSch1910 most probably a bug in BIOS connected with restarting / hibernating (or going to sleep even) w GPU being disabled

You have Optimized mode on, which would disable GPU while on battery, so probably you sometimes reboot with GPU off :) Try to check ``enable gpu on shutdown``, it will try to enable it when possible.

**Comment by LucaSch1910** [comment]
Thanks @seerge! I'll try that. Love your product, keep up the excellent work!

**Comment by seerge** [comment]
@LucaSch1910 np, try to reproduce it.

Just set Eco and reboot laptop. If fans will refuse to work properly - you have a scenario

**Comment by LucaSch1910** [comment]
Hey, I'm back, finally was able to reproduce it.
Attaching screenshot and log.
![image](https://github.com/seerge/g-helper/assets/70332531/19ed8ff0-a872-4f86-86bc-fc66661ad1cd)
[log.txt](https://github.com/seerge/g-helper/files/13969696/log.txt)


Cheers,

**Comment by seerge** [comment]
@LucaSch1910 well, it's probably some hiccup in bios with manual mode. 

Can you try to set first dot on a curve to 30C instead of 20C as now?

Or try to uncheck / check custom fan curve (that would set default turbo and manual again), or just reboot if that happens anyway.

Why do you use a custom fan curve btw (and such steep one)? Imho in most of the cases default fan modes work fine
