### ISSUE TITLE
Back Window RGB of Flow Z13 GZ301ZE does not work properly

### ISSUE THREAD

**Issue by DD742** [seerge/g-helper#1871]
**Describe the bug**
The Back Window RGB of Flow Z13 GZ301ZE does not work as intended when a static color is chosen or if the RGB is turned off i.e. one of the LED in back window still glows purple or red

**Clear scenario to Reproduce**

1. Go to 'G-Helper'
2. Click on 'Extra' and decrease the laptop backlit to zero for turning the RGB LED off or change the mode of RGB LED to static and choose any color other then purple or red
3. One of the Back Window RGB LED color is always set to purple or red even if the RGB's are turned off completely or changed to any modes like static, breathing, rainbow, etc.

**Expected behavior**
If the RGB's are turned off completely then the LED should also be turned off or if the RGB color is changed to some other color or mode then it should adjust accordingly.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13864511/log.txt)

**Screenshots or screencasts**.
![Image 1](https://github.com/seerge/g-helper/assets/46273201/8d23e2a6-fdc8-4ed7-9458-805fc9b6a51c)
![Image 2](https://github.com/seerge/g-helper/assets/46273201/84fe6e6c-ecab-48c2-a1fc-8fa6331cb700)
![Image 3](https://github.com/seerge/g-helper/assets/46273201/756e4c5d-a3bf-4f7e-9dfe-6fb28caa3c5f)

**Desktop**
 - OS: Windows 11 23H2
 - Laptop model:  ROG FLOW Z13 GZ301ZE-LC192WS

**Asus software**
- No Asus software installed or running in background other than the mentioned ASUSSystemControlInterfaceV3

**Additional context**
Note:- The RGB works as intended with ASUS Armoury Crate, I am only facing this problem with G-helper. Also I have tried to clean install windows which didn't solve the problem.

**Comment by seerge** [comment]
@DD742 i think that back led doesn't follow general brightness settings anyway. Does unchecking "awake" checkbox for Logo and Lid turn it off ?

**Comment by DD742** [comment]
Yeah it did thank you so much. Really appreciate you for developing this tool ☺️

**Comment by seerge** [comment]
Great

**Comment by DD742** [comment]
Well found out another problem now by unchecking the logo checkbox my back window RGB doesnt work only the keyboard RGB works 😓 and If I check it again then it works but the same problem arises.

**Comment by seerge** [comment]
@DD742 because as I told, backwindow has own checkbox, it's not connected to keyboard brightness anyhow.

**Comment by DD742** [comment]
So this issue can't be fixed 😕

**Comment by seerge** [comment]
What exactly do you want to fix?

This is how all models with extra lights work (like Strix series)

Logo / Lid / Lightbar (on some models) have own checkbox, they can be turned on or off there

**Comment by DD742** [comment]
> So this issue can't be fixed 😕?? It's just that sometimes I use rainbow mode and sometimes I turn off the RGB. But when using rainbow mode one of the LEDs colors remains red or purple like in the above photo. 

This is what I want to fix.

**Comment by DD742** [comment]
Let me try it with openrgb

**Comment by DD742** [comment]
So I just tried openrgb and unfortunately it doesn't show any devices tried rescanning multiple times any suggestions?

**Comment by seerge** [comment]
@DD742 then it means there is no open source information on how to set up "mode" for that window separately :) on all  devices RGB mode is set generally for whole device (all it's RGB components) and they just do same thing together. 

I have no idea if it's supposed to be like that in your case, or that window has same color. And since I don't have the device - I can't check it anyhow.

**Comment by DD742** [comment]
Hmm sad 😓. But anyways thank you for helping it's not a major issue 😅

**Comment by seerge** [comment]
There is Rainbow and Color Cycle modes, they mostly do same thing. Does second one make any difference ?

How does that window behave if you set Rainbow in Armoury?

**Comment by DD742** [comment]
Nope the color cycle does not fix the issue. 

In the armoury crate if I set it to rainbow all leds sync and it works fine. 

Wait let me add a video to show you the actual problem.

**Comment by seerge** [comment]
@DD742 well, i don't know how to turn that rainbow effect individually

**Comment by DD742** [comment]
Well even in static mode or as I told if the RGB is turned off, the led that I pointed out still keeps glowing either red or purple.

**Comment by seerge** [comment]
Cause led has own power control, which is that checkbox :)

As for your rainbow animations you can try to intercept what Armoury sends to keyboard over USB using https://www.hhdsoftware.com/device-monitoring-studio , but that's complicated

**Comment by DD742** [comment]
Yeah it might get complicated anyways thanks 😅
