### ISSUE TITLE
Gladius II Origin mouse is not detected by G-Helper

### ISSUE THREAD

**Issue by tiredElephant** [seerge/g-helper#1873]
**Describe the bug**
My Gladius II Origin mouse is not detected by G-Helper

**Clear scenario to Reproduce**
Seems to work for other people so the issue is propably on my end

**App Logs**
08.01.2024 16:03:52: ------------
08.01.2024 16:03:52: App launched: ROG Strix G712LW_G712LW :0.144.0.0de-DE.
08.01.2024 16:03:53: NVIDIA GeForce RTX 2070
08.01.2024 16:03:55: CPU: -1 - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz - Intel64 Family 6 Model 165 Stepping 2
08.01.2024 16:03:55: AutoSetting for Online
08.01.2024 16:03:55: Optimization service is running
08.01.2024 16:03:55: Mode = 2 : OK
08.01.2024 16:03:55: GET CLOCK LIMIT: NVAPI_GPU_NOT_POWERED
08.01.2024 16:03:55: nvidia-smi -rgc
08.01.2024 16:03:55: Mux flag : -65536
08.01.2024 16:03:55: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
08.01.2024 16:03:55: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
08.01.2024 16:03:56: Screen = 144Hz : OK
08.01.2024 16:03:56: ScreenOverdrive = 0 : OK
08.01.2024 16:03:56: BatteryLimit = 80 : OK
08.01.2024 16:03:56: USB 1866: 5D-BD-01-DF-16-BB-BB-FF
08.01.2024 16:03:56: AuraMode: AuraColorCycle
08.01.2024 16:03:56: USB 1866: 5D-B3-00-02-80-FF-00-EB-00-00-FF-FF-FF-00-00-00-00
08.01.2024 16:03:56: USB 1866: 5D-B4
08.01.2024 16:03:56: USB 1866: 5D-B5-00-00-00
08.01.2024 16:03:56: Init 1866: 5D-B9
08.01.2024 16:03:56: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
08.01.2024 16:03:56: Init 1866: 5D-05-20-31-00-1A
08.01.2024 16:03:56: Monitor Power On
08.01.2024 16:03:57: Auto 1866: 5D-BA-C5-C4-03
08.01.2024 16:03:58: All done.
08.01.2024 16:03:58: GET GPU CLOCKS: 0, 0
08.01.2024 16:12:02: Monitor Power Off
08.01.2024 16:12:02: Backlight 1866: 5D-BA-C5-C4-00
08.01.2024 16:23:32: Monitor Power On
08.01.2024 16:23:32: AutoSetting for Online
08.01.2024 16:23:32: Optimization service is running
08.01.2024 16:23:32: Mode = 2 : OK
08.01.2024 16:23:32: Eco flag : -65536
08.01.2024 16:23:32: Mux flag : -65536
08.01.2024 16:23:32: GET CLOCK LIMIT: 0
08.01.2024 16:23:32: GET GPU CLOCKS: 0, 0
08.01.2024 16:23:32: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
08.01.2024 16:23:32: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
08.01.2024 16:23:32: Screen = 144Hz : OK
08.01.2024 16:23:32: ScreenOverdrive = 0 : OK
08.01.2024 16:23:32: BatteryLimit = 80 : OK
08.01.2024 16:23:32: USB 1866: 5D-BD-01-DF-16-BB-BB-FF
08.01.2024 16:23:32: AuraMode: AuraColorCycle
08.01.2024 16:23:32: USB 1866: 5D-B3-00-02-80-FF-00-EB-00-00-FF-FF-FF-00-00-00-00
08.01.2024 16:23:32: USB 1866: 5D-B4
08.01.2024 16:23:32: USB 1866: 5D-B5-00-00-00
08.01.2024 16:23:32: Init 1866: 5D-B9
08.01.2024 16:23:32: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
08.01.2024 16:23:32: Init 1866: 5D-05-20-31-00-1A
08.01.2024 16:23:33: Auto 1866: 5D-BA-C5-C4-03
08.01.2024 17:24:26: HID Device Event: Checking for new ASUS Mice
08.01.2024 17:24:41: HID Device Event: Checking for new ASUS Mice
08.01.2024 18:02:22: Monitor Power Off
08.01.2024 18:02:22: Backlight 1866: 5D-BA-C5-C4-00
08.01.2024 18:04:33: Monitor Power On
08.01.2024 18:04:33: AutoSetting for Online
08.01.2024 18:04:33: Optimization service is running
08.01.2024 18:04:34: Mode = 2 : OK
08.01.2024 18:04:34: Eco flag : -65536
08.01.2024 18:04:34: Mux flag : -65536
08.01.2024 18:04:34: GET CLOCK LIMIT: 0
08.01.2024 18:04:34: GET GPU CLOCKS: 0, 0
08.01.2024 18:04:34: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
08.01.2024 18:04:34: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
08.01.2024 18:04:34: Screen = 144Hz : OK
08.01.2024 18:04:34: ScreenOverdrive = 0 : OK
08.01.2024 18:04:34: BatteryLimit = 80 : OK
08.01.2024 18:04:34: USB 1866: 5D-BD-01-DF-16-BB-BB-FF
08.01.2024 18:04:34: AuraMode: AuraColorCycle
08.01.2024 18:04:34: USB 1866: 5D-B3-00-02-80-FF-00-EB-00-00-FF-FF-FF-00-00-00-00
08.01.2024 18:04:34: USB 1866: 5D-B4
08.01.2024 18:04:34: USB 1866: 5D-B5-00-00-00
08.01.2024 18:04:34: Init 1866: 5D-B9
08.01.2024 18:04:34: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
08.01.2024 18:04:34: Init 1866: 5D-05-20-31-00-1A
08.01.2024 18:04:35: Auto 1866: 5D-BA-C5-C4-03
08.01.2024 18:26:32: Monitor Power Off
08.01.2024 18:26:32: Backlight 1866: 5D-BA-C5-C4-00
08.01.2024 18:26:46: Monitor Power On
08.01.2024 18:26:46: AutoSetting for Online
08.01.2024 18:26:46: Optimization service is running
08.01.2024 18:26:46: Mode = 2 : OK
08.01.2024 18:26:46: Eco flag : -65536
08.01.2024 18:26:46: Mux flag : -65536
08.01.2024 18:26:46: GET CLOCK LIMIT: 0
08.01.2024 18:26:46: GET GPU CLOCKS: 0, 0
08.01.2024 18:26:46: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
08.01.2024 18:26:46: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
08.01.2024 18:26:46: Screen = 144Hz : OK
08.01.2024 18:26:46: ScreenOverdrive = 0 : OK
08.01.2024 18:26:46: BatteryLimit = 80 : OK
08.01.2024 18:26:46: USB 1866: 5D-BD-01-DF-16-BB-BB-FF
08.01.2024 18:26:46: AuraMode: AuraColorCycle
08.01.2024 18:26:46: USB 1866: 5D-B3-00-02-80-FF-00-EB-00-00-FF-FF-FF-00-00-00-00
08.01.2024 18:26:46: USB 1866: 5D-B4
08.01.2024 18:26:46: USB 1866: 5D-B5-00-00-00
08.01.2024 18:26:46: Init 1866: 5D-B9
08.01.2024 18:26:46: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
08.01.2024 18:26:46: Init 1866: 5D-05-20-31-00-1A
08.01.2024 18:26:47: Auto 1866: 5D-BA-C5-C4-03
08.01.2024 18:38:36: Monitor Power Off
08.01.2024 18:38:36: Backlight 1866: 5D-BA-C5-C4-00
08.01.2024 18:38:40: Monitor Power On
08.01.2024 18:38:40: AutoSetting for Online
08.01.2024 18:38:40: Optimization service is running
08.01.2024 18:38:40: Mode = 2 : OK
08.01.2024 18:38:40: Eco flag : -65536
08.01.2024 18:38:40: Mux flag : -65536
08.01.2024 18:38:40: GET CLOCK LIMIT: 0
08.01.2024 18:38:40: GET GPU CLOCKS: 0, 0
08.01.2024 18:38:40: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
08.01.2024 18:38:40: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
08.01.2024 18:38:40: Screen = 144Hz : OK
08.01.2024 18:38:40: ScreenOverdrive = 0 : OK
08.01.2024 18:38:40: BatteryLimit = 80 : OK
08.01.2024 18:38:40: USB 1866: 5D-BD-01-DF-16-BB-BB-FF
08.01.2024 18:38:40: AuraMode: AuraColorCycle
08.01.2024 18:38:40: USB 1866: 5D-B3-00-02-80-FF-00-EB-00-00-FF-FF-FF-00-00-00-00
08.01.2024 18:38:40: USB 1866: 5D-B4
08.01.2024 18:38:40: USB 1866: 5D-B5-00-00-00
08.01.2024 18:38:40: Init 1866: 5D-B9
08.01.2024 18:38:40: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
08.01.2024 18:38:40: Init 1866: 5D-05-20-31-00-1A
08.01.2024 18:38:41: Auto 1866: 5D-BA-C5-C4-03
08.01.2024 18:41:11: Monitor Power Off
08.01.2024 18:41:11: Backlight 1866: 5D-BA-C5-C4-00
08.01.2024 18:41:11: Power Mode Changed:Suspend
08.01.2024 19:33:43: Monitor Power On
08.01.2024 19:33:43: AutoSetting for Online
08.01.2024 19:33:43: Optimization service is running
08.01.2024 19:33:43: Mode = 2 : OK
08.01.2024 19:33:43: Eco flag : -65536
08.01.2024 19:33:43: Mux flag : -65536
08.01.2024 19:33:43: GET CLOCK LIMIT: 0
08.01.2024 19:33:43: GET GPU CLOCKS: 0, 0
08.01.2024 19:33:44: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
08.01.2024 19:33:44: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
08.01.2024 19:33:44: Screen = 144Hz : OK
08.01.2024 19:33:44: ScreenOverdrive = 0 : OK
08.01.2024 19:33:44: BatteryLimit = 80 : OK
08.01.2024 19:33:44: USB 1866: 5D-BD-01-DF-16-BB-BB-FF
08.01.2024 19:33:44: AuraMode: AuraColorCycle
08.01.2024 19:33:44: USB 1866: 5D-B3-00-02-80-FF-00-EB-00-00-FF-FF-FF-00-00-00-00
08.01.2024 19:33:44: USB 1866: 5D-B4
08.01.2024 19:33:44: USB 1866: 5D-B5-00-00-00
08.01.2024 19:33:44: Init 1866: 5D-B9
08.01.2024 19:33:44: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
08.01.2024 19:33:44: Init 1866: 5D-05-20-31-00-1A
08.01.2024 19:33:45: Auto 1866: 5D-BA-C5-C4-03
08.01.2024 19:33:55: Session:SessionUnlock
08.01.2024 19:33:55: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
08.01.2024 19:33:55: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
08.01.2024 19:33:56: Screen = 144Hz : OK
08.01.2024 19:33:56: ScreenOverdrive = 0 : OK
08.01.2024 19:36:14: Monitor Power Off
08.01.2024 19:36:14: Backlight 1866: 5D-BA-C5-C4-00
08.01.2024 19:36:47: Monitor Power On
08.01.2024 19:36:47: AutoSetting for Online
08.01.2024 19:36:47: Optimization service is running
08.01.2024 19:36:47: Mode = 2 : OK
08.01.2024 19:36:47: Eco flag : -65536
08.01.2024 19:36:47: Mux flag : -65536
08.01.2024 19:36:47: GET CLOCK LIMIT: 0
08.01.2024 19:36:47: GET GPU CLOCKS: 0, 0
08.01.2024 19:36:47: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
08.01.2024 19:36:47: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
08.01.2024 19:36:48: Screen = 144Hz : OK
08.01.2024 19:36:48: ScreenOverdrive = 0 : OK
08.01.2024 19:36:48: BatteryLimit = 80 : OK
08.01.2024 19:36:48: USB 1866: 5D-BD-01-DF-16-BB-BB-FF
08.01.2024 19:36:48: AuraMode: AuraColorCycle
08.01.2024 19:36:48: USB 1866: 5D-B3-00-02-80-FF-00-EB-00-00-FF-FF-FF-00-00-00-00
08.01.2024 19:36:48: USB 1866: 5D-B4
08.01.2024 19:36:48: USB 1866: 5D-B5-00-00-00
08.01.2024 19:36:48: Init 1866: 5D-B9
08.01.2024 19:36:48: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
08.01.2024 19:36:48: Init 1866: 5D-05-20-31-00-1A
08.01.2024 19:36:49: Auto 1866: 5D-BA-C5-C4-03
08.01.2024 20:04:34: Monitor Power Off
08.01.2024 20:04:34: Backlight 1866: 5D-BA-C5-C4-00
08.01.2024 20:04:42: Monitor Power On
08.01.2024 20:04:42: AutoSetting for Online
08.01.2024 20:04:42: Optimization service is running
08.01.2024 20:04:42: Mode = 2 : OK
08.01.2024 20:04:42: Eco flag : -65536
08.01.2024 20:04:42: Mux flag : -65536
08.01.2024 20:04:42: GET CLOCK LIMIT: 0
08.01.2024 20:04:42: GET GPU CLOCKS: 0, 0
08.01.2024 20:04:42: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
08.01.2024 20:04:42: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
08.01.2024 20:04:42: Screen = 144Hz : OK
08.01.2024 20:04:42: ScreenOverdrive = 0 : OK
08.01.2024 20:04:42: BatteryLimit = 80 : OK
08.01.2024 20:04:42: USB 1866: 5D-BD-01-DF-16-BB-BB-FF
08.01.2024 20:04:42: AuraMode: AuraColorCycle
08.01.2024 20:04:42: USB 1866: 5D-B3-00-02-80-FF-00-EB-00-00-FF-FF-FF-00-00-00-00
08.01.2024 20:04:42: USB 1866: 5D-B4
08.01.2024 20:04:42: USB 1866: 5D-B5-00-00-00
08.01.2024 20:04:42: Init 1866: 5D-B9
08.01.2024 20:04:42: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
08.01.2024 20:04:42: Init 1866: 5D-05-20-31-00-1A
08.01.2024 20:04:43: Auto 1866: 5D-BA-C5-C4-03
08.01.2024 20:09:59: Monitor Power Off
08.01.2024 20:09:59: Backlight 1866: 5D-BA-C5-C4-00
08.01.2024 20:09:59: Power Mode Changed:Suspend
08.01.2024 20:36:16: Monitor Power On
08.01.2024 20:36:16: AutoSetting for Online
08.01.2024 20:36:16: Optimization service is running
08.01.2024 20:36:16: Mode = 2 : OK
08.01.2024 20:36:16: Eco flag : -65536
08.01.2024 20:36:16: Mux flag : -65536
08.01.2024 20:36:16: GET CLOCK LIMIT: 0
08.01.2024 20:36:16: GET GPU CLOCKS: 0, 0
08.01.2024 20:36:17: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
08.01.2024 20:36:17: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
08.01.2024 20:36:17: Screen = 144Hz : OK
08.01.2024 20:36:17: ScreenOverdrive = 0 : OK
08.01.2024 20:36:17: BatteryLimit = 80 : OK
08.01.2024 20:36:17: USB 1866: 5D-BD-01-DF-16-BB-BB-FF
08.01.2024 20:36:17: AuraMode: AuraColorCycle
08.01.2024 20:36:17: USB 1866: 5D-B3-00-02-80-FF-00-EB-00-00-FF-FF-FF-00-00-00-00
08.01.2024 20:36:17: USB 1866: 5D-B4
08.01.2024 20:36:17: USB 1866: 5D-B5-00-00-00
08.01.2024 20:36:17: Init 1866: 5D-B9
08.01.2024 20:36:17: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
08.01.2024 20:36:17: Init 1866: 5D-05-20-31-00-1A
08.01.2024 20:36:18: Auto 1866: 5D-BA-C5-C4-03
08.01.2024 20:36:24: Session:SessionUnlock
08.01.2024 20:36:24: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
08.01.2024 20:36:24: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
08.01.2024 20:36:24: Screen = 144Hz : OK
08.01.2024 20:36:24: ScreenOverdrive = 0 : OK
08.01.2024 20:37:51: Monitor Power Off
08.01.2024 20:37:51: Backlight 1866: 5D-BA-C5-C4-00
08.01.2024 20:39:20: Monitor Power On
08.01.2024 20:39:20: AutoSetting for Online
08.01.2024 20:39:20: Optimization service is running
08.01.2024 20:39:20: Mode = 2 : OK
08.01.2024 20:39:20: Eco flag : -65536
08.01.2024 20:39:20: Mux flag : -65536
08.01.2024 20:39:20: GET CLOCK LIMIT: 0
08.01.2024 20:39:20: GET GPU CLOCKS: 0, 0
08.01.2024 20:39:20: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
08.01.2024 20:39:20: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
08.01.2024 20:39:20: Screen = 144Hz : OK
08.01.2024 20:39:20: ScreenOverdrive = 0 : OK
08.01.2024 20:39:20: BatteryLimit = 80 : OK
08.01.2024 20:39:20: USB 1866: 5D-BD-01-DF-16-BB-BB-FF
08.01.2024 20:39:20: AuraMode: AuraColorCycle
08.01.2024 20:39:20: USB 1866: 5D-B3-00-02-80-FF-00-EB-00-00-FF-FF-FF-00-00-00-00
08.01.2024 20:39:20: USB 1866: 5D-B4
08.01.2024 20:39:20: USB 1866: 5D-B5-00-00-00
08.01.2024 20:39:20: Init 1866: 5D-B9
08.01.2024 20:39:20: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
08.01.2024 20:39:20: Init 1866: 5D-05-20-31-00-1A
08.01.2024 20:39:21: Auto 1866: 5D-BA-C5-C4-03
08.01.2024 21:21:02: Monitor Power Off
08.01.2024 21:21:02: Backlight 1866: 5D-BA-C5-C4-00
08.01.2024 21:24:07: Monitor Power On
08.01.2024 21:24:07: AutoSetting for Online
08.01.2024 21:24:07: Optimization service is running
08.01.2024 21:24:07: Mode = 2 : OK
08.01.2024 21:24:07: Eco flag : -65536
08.01.2024 21:24:07: Mux flag : -65536
08.01.2024 21:24:07: GET CLOCK LIMIT: 0
08.01.2024 21:24:07: GET GPU CLOCKS: 0, 0
08.01.2024 21:24:07: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
08.01.2024 21:24:07: \\?\DISPLAY#LGD065B#4&37a0ce87&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
08.01.2024 21:24:07: Screen = 144Hz : OK
08.01.2024 21:24:07: ScreenOverdrive = 0 : OK
08.01.2024 21:24:07: BatteryLimit = 80 : OK
08.01.2024 21:24:07: USB 1866: 5D-BD-01-DF-16-BB-BB-FF
08.01.2024 21:24:07: AuraMode: AuraColorCycle
08.01.2024 21:24:07: USB 1866: 5D-B3-00-02-80-FF-00-EB-00-00-FF-FF-FF-00-00-00-00
08.01.2024 21:24:07: USB 1866: 5D-B4
08.01.2024 21:24:07: USB 1866: 5D-B5-00-00-00
08.01.2024 21:24:07: Init 1866: 5D-B9
08.01.2024 21:24:07: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
08.01.2024 21:24:07: Init 1866: 5D-05-20-31-00-1A
08.01.2024 21:24:08: Auto 1866: 5D-BA-C5-C4-03
08.01.2024 21:27:54: WMI event 56
08.01.2024 21:27:55: Latest version 0.144.0.0
08.01.2024 21:27:56: Hibernate after 2147483647

**Desktop (please complete the following information):**
 - OS: Windows 11
 - G712LW

**Asus software**
- MyASUS installed
- Asus drives that come with Windows Update
- Armoury Crate is not installed (could this be the problem?)

**Comment by seerge** [comment]
@tiredElephant hello, because support for it was not added in 0.144 :)

You can try latest https://github.com/seerge/g-helper/releases/tag/0.145 it should be there
