### ISSUE TITLE
Battery charge limit doesn't work

### ISSUE THREAD

**Issue by cratu** [seerge/g-helper#1875]
**Describe the bug**
Seems battery charge limit doesn't work until g-helper is started.
After that battery can be charged above limit and limit doesn't work at all.

**Clear scenario to Reproduce**
*XG Mobile always connected
1. Shutdown PC at battery charged to limit
2. Power on PC
3. Battery charged over the limit and keep charging.

**Expected behavior**
Battery stop charging when charged over the limit.

**App Logs**
[GHelper.zip](https://github.com/seerge/g-helper/files/13873171/GHelper.zip)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/7173093/5240ef3d-5420-4eea-9994-d8f44d56e063)

**Desktop (please complete the following information):**
 - OS: Windows 10 19045.3803
 - ASUS ROG Flow X13 GV301QC

**Asus software**
- Armoury Crate installed
- MyASUS installed
- All disabled via g-helper

**Additional context**
Maybe charging keep going when laptop is off, but on original ASUS software this options works as expected.

**Comment by seerge** [comment]
P.S. I also noticed that you don't even have any charge limit selected, default is 100%
