### ISSUE TITLE
Camera & NumLock Indicator

### ISSUE THREAD

**Issue by B1ue-Dev** [seerge/g-helper#1878]
**Is your feature request related to a problem? Please describe.**
None.

**Describe the solution you'd like**
G-Helper is pretty nice to use so far, which remove the need of MyASUS for my laptop. However, there's something missing here, which is the Camera Indicator when pressing the Fn combo key on the keyboard. This is a thing with the MyASUS hotkey indicator though, would be nice if G-Helper also cover that.

Oh, and it would be nice to have a NumLock indicator for Numpad included with the keyboard as well.

**Additional context**
Camera Indicator
![image](https://github.com/seerge/g-helper/assets/60958064/b3126b10-ed26-4c52-a75b-2e1c8a4b119b)

**Comment by seerge** [comment]
@B1ue-Dev post a log from your device as it was asked in issue template please

**Comment by seerge** [comment]
@B1ue-Dev then I don't have any idea how to set it on or off :) 

You can try to submit a dump following instructions in this topic https://github.com/seerge/g-helper/issues/38 (method 2)

**Comment by seerge** [comment]
@B1ue-Dev Any chance to do a dump ?

**Comment by seerge** [comment]
@B1ue-Dev I see couple of other endpoints starting with 600 (60013 is endpoint that I have found in linux sources, saying it's a "Camera")
https://elixir.bootlin.com/linux/latest/source/include/linux/platform_data/x86/asus-wmi.h#L70


```
                    If ((IIA0 == 0x00060023))
                    {
                        Local0 = (IIA1 >> 0x09)
                        If (((Local0 & One) == One))
                        {
                            VBOF = One
                            Local0 = (IIA1 >> 0x18)
                            Local0 *= 0x0100
                            VBOF |= Local0 /* \_SB_.VBOF */
                        }
                        Else
                        {
                            VBOF = Zero
                        }

                        Local0 = (IIA1 & 0xFF)
                        ^^PC00.LPCB.EC0.STA9 (One, Local0)
                        Local0 = (IIA1 >> 0x08)
                        Local1 = ^^PC00.LPCB.EC0.STA8 (Zero)
                        If (((Local0 & One) == One))
                        {
                            Local1 |= 0x02
                            Local2 = (Local1 & 0x0F)
                            ^^PC00.LPCB.EC0.STA9 (Zero, Local1)
                        }
                        Else
                        {
                            Local1 &= 0xFD
                            Local2 = (Local1 & 0x0F)
                            ^^PC00.LPCB.EC0.STA9 (Zero, Local1)
                        }

                        Return (One)
                    }

                    If ((IIA0 == 0x00060026))
                    {
                        Local0 = ^^PC00.LPCB.EC0.STA8 (Zero)
                        If ((IIA1 == One))
                        {
                            Local0 |= 0x04
                            ^^PC00.LPCB.EC0.STA9 (Zero, Local0)
                        }
                        Else
                        {
                            Local0 &= 0xFB
                            ^^PC00.LPCB.EC0.STA9 (Zero, Local0)
                        }

                        Return (One)
                    }
```

So you can try to check if sending 1 or 0 to them turns off camera like

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x0060026, 0)

or

(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x0060026, 1)

```

But I have no idea what they do in reality :) so try this on your own risk :))

**Comment by seerge** [comment]
Closed as abandoned
