### ISSUE TITLE
FX516PE not working keyboard light mode

### ISSUE THREAD

**Issue by Pewful2021** [seerge/g-helper#1879]
Hi, so i wanted to change the light mode on the keyboard but it wont work

Steps to recreate :
1. Open G-Helper
2. Select Keyboard light mode

Here is the log 
[log.txt](https://github.com/seerge/g-helper/files/13886191/log.txt)

**Comment by seerge** [comment]
@Pewful2021 does your laptop support different backlight modes in a first place ? did you have them in AC ?

**Comment by Pewful2021** [comment]
No, its only one color and i always plug my laptop when I use it

**Comment by seerge** [comment]
@Pewful2021 but then no wonder that it's not working :) it has to be supported by your hardware.

Sorry, but I can't do anything here by obvious reasons
