### ISSUE TITLE
Aura/RGB support for Z13 2023 

### ISSUE THREAD

**Issue by harrisck** [seerge/g-helper#188]
**Is your feature request related to a problem? Please describe.**
Changing the RGB modes in G-Helper does not control the keyboard RGB keyboard.

**Describe the solution you'd like**
For the RGB drop menu selection to correctly control the RGB Keyboard. 

Happy to give you access to my machine or i can provide any Hardware ID's or device specific info you require.

**Comment by seerge** [comment]
Hello, do other open source rgb apps like openrgb work on your device?

**Comment by harrisck** [comment]
> Hello, do other open source rgb apps like openrgb work on your device?

Just tried OpenRGB, Aurora and SignalRGB and none of these pick up the keyboard or back cut out, they did pick up my Asus Pugio II mouse when connected but nothing else.

**Comment by seerge** [comment]
Then most probably no one knows how to control your keyboard yet :) If it will be some information (later?) i will try to add that

**Comment by seerge** [comment]
@harrisck can you download https://www.nirsoft.net/utils/usb_devices_view.html and list all devices with VendorID 0b05 (i think it's asus) here ?

**Comment by seerge** [comment]
Cause if the only difference between z13 2023 and others is just a device ID - it could be easy fix (otherwise - not) :)

**Comment by harrisck** [comment]
@seerge 
![image](https://user-images.githubusercontent.com/28593773/230659770-d3ea6265-0ce1-4775-b0e7-c04e5fed9d05.png)

Let me know if you need the full html export

Thanks for looking into this! Will send a donation your way!

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11180905/GHelper.zip)
I have added  0x1906, 0x1908, 0x18c6 (from your screenshot) to list of devices, you can try (on your risk) this build if it will work :)

**Comment by seerge** [comment]
Even tho 1908 is probably a mouse ... but I'm curious if mouse will also change color ? :|

**Comment by harrisck** [comment]
No color change on the keyboard or on the mouse

**Comment by seerge** [comment]
@harrisck oke, can you try this one then ? I have added last device in a list 1a30
[GHelper.zip](https://github.com/seerge/g-helper/files/11182886/GHelper.zip)

But if that also doesn't work, i think we will have to wait until someone on linux / openrgb actually does their implementation :)

**Comment by harrisck** [comment]
WINNER!!!!

That works for the keyboard and the rear RGB cutout.

**Comment by seerge** [comment]
Ok, good. I will include it in next release then :)

**Comment by seerge** [comment]
Live in https://github.com/seerge/g-helper/releases/tag/v0.49
