### ISSUE TITLE
Add the CPU model to the curves page. 

### ISSUE THREAD

**Issue by Kikimahe** [seerge/g-helper#1883]
**Is your feature request related to a problem? Please describe.**

_Hi Seerge,_ 

_We often see screenshots of the Ghelper curves page in community forum (reditt, Rog forum, Facebook, etc.). 
People who ask for help settings or offer settings._

_"I always get frustrated when" the CPU used in this screenshot is not directly displayed and I have to find the information elsewhere in the text (sometimes it is not even indicated...)_

**Describe the solution you'd like**
_Would it be possible to add display the CPU model to the curves page ?_ 

_Something Like this for example :_ 
![CPU](https://github.com/seerge/g-helper/assets/142881210/16dabe1f-8a11-4b96-af56-c97cdb89dc56)

**Additional context**
_I'm sure you can find this information in Windows and display it :)
I think it would be useful information to facilitate understanding and communication for Ghelper users._

Thanks.

**Comment by seerge** [comment]
@Kikimahe hello, try this build. I have added CPU name to the window title (same as laptop model is added to main window)

[GHelper.zip](https://github.com/seerge/g-helper/files/13891993/GHelper.zip)

**Comment by ke1ne** [comment]
Oh, nice. And GPU, in its tab, maybe?

**Comment by Kikimahe** [comment]
Nice @seerge  ! 👍 
Thanks.

@ke1ne  GPU is already display in GPU Tab.  ;-)

**Comment by seerge** [comment]
Exactly, closing as completed
