### ISSUE TITLE
Charge Limit Exceeded on Occassion

### ISSUE THREAD

**Issue by racingcirc** [seerge/g-helper#1887]
Despite having the charge limit constantly set to 65% for the last several months, my battery has ended up fully charged (or charged well beyond the limit) on several occasions. This is an intermittent issue, and so far I've been unable to reproduce it on demand. At this point I'm reporting this issue only to see if anyone else has come across this as well and see if there are any common elements.

I do not have any ASUS software installed and all ASUS services are disabled (as shown in screenshot).

**Expected behavior**
Battery charge never goes beyond my set point of 65%, regardless of restarts, unplug/plug-in status, etc.

**App Logs**
Attached: 
[log.txt](https://github.com/seerge/g-helper/files/13895052/log.txt)

**Screenshots or screencasts**
![Screenshot 2024-01-10 171306](https://github.com/seerge/g-helper/assets/145857730/1094ca68-141f-4e9f-8c5c-bfc7ad544c05)

**Desktop (please complete the following information):**
 - Windows 11 23H2 (build 22631.3007)
 - ASUS Rog Flow X13 (GV301-QE)

**Comment by seerge** [comment]
@racingcirc hello, every time app starts it sets a limit
```
2024-01-10 5:00:43 PM: BatteryLimit = 65 : OK
2024-01-10 5:00:43 PM: BatteryLimit = 65 : OK
```

But your laptop will be charging after start / restart till windows loads and start app.

It's normal, there is nothing i can do here

**Comment by racingcirc** [comment]
Thanks for the explanation, @seerge ! Do we know how Asus is able to stop the charging even when the laptop is not started? Is there a way to tap into their BIOS/Services for this?

**Comment by seerge** [comment]
Asus  has separate windows service, that starts before user login (but still with windows itself). G-Helper doesn't have any services running (it's portable and lightweight exe by design) so it can't do that.

If you just login to windows after reboot difference would be in few seconds of charging :) it's negligible

**Comment by racingcirc** [comment]
The charge limit is held by the BIOS before Windows starts up (while the laptop is powered off but plugged in), correct? Would there be a way to have the BIOS retain that limit even after Windows starts up?

In other words, can the charge limit can be implemented without G-Helper (or an associated service) having to run all the time?

**Comment by seerge** [comment]
@racingcirc charge limit is held by BIOS, but the way BIOS is programmed - it resets all settings including power mode, power limits, other stuff and **charge limit** to defaults every time you restart laptop.

Charge limit can be also set via powershell  as admin
```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00120057, 80)
```

(it's same thing that g-helper does)

**Comment by racingcirc** [comment]
Interesting. Thank you so much for the info and response, @seerge !
