### ISSUE TITLE
Unable to increase GPU memory clock to maximum

### ISSUE THREAD

**Issue by H1m4ru** [seerge/g-helper#1888]
0.145v increased a lil bit my memory clock slider to 500Mhz. However, if i try to increase it above 300Mhz, i get a NVAPI_NOT_SUPPORTED error for that, as i saw on the log file.
There is no other error than that, clock frequency slider works fine, and the core clock one aswell.
I have a ROG Strix G15 G513IE-R74BRTSP52, with a RTX 3050 Ti 95W.

**Comment by seerge** [comment]
@H1m4ru may be your GPU is simply locked and doesn't support that ? (pretty much what it says) If you were not able to do that before (including Armoury) then it it's probably the case :)

**Comment by seerge** [comment]
Just checked official nvidia api docs
https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/group__nvapistatus.html

```
NVAPI_NOT_SUPPORTED | Requested feature is not supported in the selected GPU.
```

So, sorry :) but that's how things are on your device.
