### ISSUE TITLE
[Feature Request] Apply battery limit only for PD charge

### ISSUE THREAD

**Issue by phu54321** [seerge/g-helper#1889]
**Is your feature request related to a problem? Please describe.**

Charging with USB-PD, Without a battery limiter the laptop drains on 100% and recharges on 98%, alternating between two levels. This **alternation** outside the 20~80% range may degrade the battery excessively, so **I want to limit the battery level with a PD charger**.

This alternation doesn't occur on AC charging, so I'd rather want a **full/higher battery capacity with an AC charger**.

![image](https://github.com/seerge/g-helper/assets/775265/b41a89b7-4ff9-46ce-a5a3-306dd6ba6826)

Image source: https://batteryuniversity.com/article/bu-808-how-to-prolong-lithium-based-batteries

**Describe the solution you'd like**

Apply different battery levels on AC charge (battery level doesn't change after full charge) & PD charge (alternating battery level).
For some laptops (flow x13), a higher-wattage PD charge acts as an AC charge, so it should be treated as an AC charge.

**Describe alternatives you've considered**

Just stick to the 90% limit on all cases.

**Additional context**

Laptop: Flow X16 (2022)

**Comment by seerge** [comment]
@phu54321 hello, you can already limit charge limit :) + you have a one time 100% charge button.

I don't see any reason to drastically overcomplicate UI add lots of different conditions, on when and how to set that poor limit.

Sorry, I won't be adding this.
