### ISSUE TITLE
Higher fan speed control 

### ISSUE THREAD

**Issue by J4W4D-21** [seerge/g-helper#1898]
I'm frequently dealing with overheating problems on my laptop as the max available fan speed is 6600rpm for the GPU and 6800rpm for the CPU in ghelper. I'd appreciate it if higher fan speed control options could be implemented in ghelper as my laptop fans are able to run at 8000rpm.

**Comment by seerge** [comment]
@J4W4D-21 hello, G-Helper can't control your fans directly anyhow. Please check FAQ

https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds

Good luck
