### ISSUE TITLE
[Feature Request] Control Keyboard Backlight in Sleep State

### ISSUE THREAD

**Issue by chrisrieth** [seerge/g-helper#19]
**Device:** 2022 Zephyrus G14 (AMD Ryzen 9 / 6700S)

## Issue:

After uninstalling Armory Crate, whenever the device goes into sleep mode the keyboard backlight defaults to a pulsing pattern (2 flashes of white color light every 3 seconds or so). Without Armory Crate, there's no way to change the Aura settings for sleep mode.

Love the project - thanks for sharing it and your time!

**Comment by seerge** [comment]
I would gladly change that if I would know what AMI or ACPI method is responsible for that ... :|

**Comment by seerge** [comment]
@chrisrieth ok, I have finally managed to add this under "Extra" tab. 

It's experimental, but works for my g14.
[GHelper.zip](https://github.com/seerge/g-helper/files/11069284/GHelper.zip)

**Comment by chrisrieth** [comment]
Oh wow! You found the API! I'll happily download an experimental build and give it a test. Thanks again for supporting this utility.

**Comment by chrisrieth** [comment]
Quick test for you - here's what I found:

`Awake` - checking / unchecking box works immediately ✅ 
`Boot` - unclear, I ran both restart and shut down / turn on, keyboard lit regardless of checkbox state ❓ 
`Sleep` - keyboard not lit regardless of checkbox state ❓ (maybe because i previously reinstalled Crate, shut this off, then deleted / some type of stored state)
'Shutdown' - keyboard not lit regardless of checkbox state ❓ 

*Other Findings*
I turned all checkboxes `on` and shut down - when it finished the power down cycle i saw it momentarily do its default 'double flash white', and then it powered off and did not repeat. But, when I hit power on, it did it again, before flipping back to "static" rgb which is what I have mine set to by default. 

I wonder if there's some kind of storage of state (my previous AC setting to turn that behavior off, or the current setting of static rgb) that it's recognizing ghelper settings but then quickly reverting to some saved state. I'll happily take the hit, reinstall AC, set it to default (on), and uninstall, re-test though - will have to be later. Again, appreciate what you're doing!

**Comment by seerge** [comment]
``Shutdown`` - is double flash AFTER laptop powers off (you have literally disabled it's behavior)
``Sleep`` - usually activates only when laptop is in sleep for a while (i think it's connected with way windows handles sleep itself), for me it starts blinking if ON (after like 5 mins of sleep) and doesn't blink when OFF
``Boot`` is again white flash BEFORE laptop starts booting, during boot itself - it's a regular backlight mode (with colors /etc)

And yes - there is a storage on hardware level, and G-helper should adjust same setting as armoury.

**Comment by chrisrieth** [comment]
`shutdown` and `sleep` - i didn't realize there was a bit of a delay. I will re-test. 

For `boot` - I did get 1 white double flash, so in that case, that would be a ✅

**Comment by seerge** [comment]
@chrisrieth well, we have same laptops so 95% that if it works for me (and it does) all 4 checkboxes should work for you. Anyway this changes are already live as 0.39

**Comment by chrisrieth** [comment]
Much appreciated context. I did go back and confirm this was working in sleep after some additional time just as you said! So ✅  all around.
