### ISSUE TITLE
Zephyrus G14 2021 Selecting TURBO mode with a custom fan curve enabled causes fans to constantly ramp up and down

### ISSUE THREAD

**Issue by BBGUNZ123** [seerge/g-helper#190]
**Describe the bug**
Zephyrus G14 2021 Selecting TURBO mode with a custom fan curve enabled causes fans to constantly ramp up and down on IDLE

**Clear scenario to Reproduce**
1. Open GHelper, select TURBO mode
2. Edit custom fan curve, then enable AUTO APPLY
3. Almost instantly this causes both CPU and GPU fan to fluxuate between 3000rpm and 3500rpm
4. This bug does not happen if I ONLY select TURBO mode (not messing with fan curve)

**Expected behavior**
The fans would ramp up and down on idle between 3000rpm and 3500rpm on TURBO mode, with auto applied custom fan curve.

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/11143734/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Laptop model GA401QM, G14 2021 with RTX 3060

**Asus software**
- Armoury crate COMPLETELY removed
- MyASUS installed
- NO other Asus services running in background

**Additional context**
The fans acts normal in silent and balance mode in idle. in TURBO mode, the instant I touch 'auto apply' fans ramps up and down constantly on IDLE.

## NOTE
Bug reports without clear information or scenario to reproduce will be closed without answer. 
Please respect time of the developer. Thanks.

**Comment by seerge** [comment]
Also i have loaded your custom fan profile and it literally sets speeds around 3000 (why do you complain that it rotates around that speeds then?)

![Screenshot 2023-04-04 115022](https://user-images.githubusercontent.com/5920850/229755409-f62872e6-ad67-42f1-8a85-15d8bd8fa54f.png)

**Comment by BBGUNZ123** [comment]
The default turbo mode, on idle stays at 3000rpm

Turbo mode, WITH fan curve applied, goes up and down

**Comment by BBGUNZ123** [comment]
the thing is, on the default profile of TURBO mode, it can sustain 3000rpm constant on idle and stays at 3000rpm. So i do not know what is going on. If only i was rich enough to donate my G14 2021 to you XD. thank you anyways

**Comment by seerge** [comment]
Well my advice is either try different curve itself (if you really want custom) + try similar thing on armoury :)

**Comment by BBGUNZ123** [comment]
Furthermore, I have just reinstalled Armory Crate, When I apply custom fan curve in MANUAL mode in armory crate. it stays 3000 rpm on IDLE. maybe Ghelper needs a MANUAL mode too? I think setting turbo mode and applying custom fan curves in ghelper is interferring with each other.

**Comment by seerge** [comment]
Can you post a screenshot of a curve in armory? As for modes - on hardware level - there is no manual mode, there is always one of 3 modes - silent/balanced/turbo as a "base" and then you can customize them with custom fan curve.

**Comment by BBGUNZ123** [comment]
![image](https://user-images.githubusercontent.com/129810417/229812165-21a80bc6-01e3-4d89-ac9a-09890266a42c.png)

**Comment by BBGUNZ123** [comment]
![image](https://user-images.githubusercontent.com/129810417/229812514-8d448684-2d29-404d-8044-0c958e0f1806.png)

**Comment by seerge** [comment]
Ok, can you try to edit config.json in ``%AppData%\GHelper``
and replace  following lines with this

```
  "fan_profile_cpu_1": "27-31-39-3D-45-4F-59-63-14-14-14-34-50-64-64-64",
  "fan_profile_gpu_1": "27-2E-3A-3E-44-4F-59-63-14-14-14-38-52-64-64-64",
```

It should be as close to that custom curves that you use as possible (i.e. first 3 dots on chart are exactly 20% or 14 in hex)

**Comment by BBGUNZ123** [comment]
Maybe ignoring the first 3 dots on the fan curve helped with my G14 2021 x

**Comment by seerge** [comment]
Glad it helped. I just replicated same curve as you had in armoury. Most probably there is still something wrong with fan controller on your side (cause for my device any curve works ok), and it can maintain 20% speed, but can't maintain 25%. 

P.S. Which in fact is not even 20%... (as armory shows) as 3000 RPM from max 7200 RPM on your device is 41.6%. That's how strange asus software is :))

**Comment by seerge** [comment]
Also update to 0.47

**Comment by seerge** [comment]
you can try to set 1% in armoury, theoretically - that's lowest. On G14 2022 it's 1% = 1800RPM (yes, asus maths is great)
