### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by seerge** [seerge/g-helper#1900]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

Test

### How to reproduce the bug?

Test

### Logs

Test

### Device and Model

GA402

### Asus Software

- [ ] Armoury Crate
- [ ] MyAsus
- [ ] Other Asus Services

**Comment by Kikimahe** [comment]
For information, with the dark theme, it's difficult to see if the box is checked or not. ;-)

![Capture d'écran 2024-01-12 202731](https://github.com/seerge/g-helper/assets/142881210/9c7768f9-6ed3-4212-95a8-24bd305b79e8)

![Capture d'écran 2024-01-12 203224](https://github.com/seerge/g-helper/assets/142881210/ab79e5c7-13fd-4f26-b921-8288d134e5e9)

**Comment by seerge** [comment]
@Kikimahe it looks fine, i'm not controlling that. It's github.
