### ISSUE TITLE
Fan curve limit issue

### ISSUE THREAD

**Issue by J4W4D-21** [seerge/g-helper#1901]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

The max speed on the fan curve change every once and a while and limits my fan speed to 6600 rpm for the gpu and 6800 rpm for the cpu, even though it let reach almost 8000 rpm before. 

### How to reproduce the bug?

basicaly every time i update or reastart the laptop

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13919979/log.txt)

### Device and Model

Asus Tuf dash f15 2021

### Additional information.

Edition	Windows 10 Home
Version	22H2
Installed on	‎5/‎01/‎2024
OS build	19045.3930
Experience	Windows Feature Experience Pack 1000.19053.1000.0

Bios version 321

### Asus Software

- [ ] Armoury Crate
- [ ] MyAsus
- [ ] Other Asus Services

### Version

0.146.0

### OS

windows 10 22H2

**Comment by seerge** [comment]
@J4W4D-21 hello, I have just answered you your question in your dublicate issue https://github.com/seerge/g-helper/issues/1898

G-Helper doesn't control fans directly anyhow

You have TUF model that doesn't even support custom fan curves, you just switch between 3 predefined modes, baked in BIOS. They work as they were programmed by engineers at asus.

**Comment by Kikimahe** [comment]
You can manually change the RPM value of the curve axes if you want. 
But anyway, it's your bios that controls the fans, not Ghelper.

Close Ghelper and increase the values to 80 (8000 RPM) in the file `C:\Users\yourusername\AppData\Roaming\Config.json`
`"fan_max_1": 68,`
`"fan_max_0": 64,`
