### ISSUE TITLE
Fn + C maccro on ACRNM Z13 2023 is preventing the Armoury shortcut from working

### ISSUE THREAD

**Issue by NairoDorian** [seerge/g-helper#1905]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

I can not deactivate the FN+C shortcut which was changing the color calibration of the screen in Armoury Crate
It was very useful and I'd like to be able to do that again
Please make it customizable or be able to deactivate this shortcut overwrite. 

Also, do you need some help or logs from my machine? Have you brought full support of Acrnm Z13 2023 ? Let me know if I can be of any help

Thank for the best tool ever made !

### How to reproduce the bug?

FN+C

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13922316/log.txt)

### Device and Model

ACRNM Z13 2023

### Asus Software

- [X] Armoury Crate
- [X] MyAsus
- [X] Other Asus Services

### Version

0.146

### OS

Windows 23H2

**Comment by seerge** [comment]
@NairoDorian hello, G-Helper doesn't have any color management inside :) But you can manually select color profile in windows instead (check this topic https://github.com/seerge/g-helper/issues/520)

Next to that, if you want to have Visual Styles - you can download separate app from asus that does same thing
Please check FAQ https://github.com/seerge/g-helper/wiki/FAQ#how-do-i-set-different-visual-styles 

Good luck

**Comment by NairoDorian** [comment]
I meant 
![image](https://github.com/seerge/g-helper/assets/8990554/37569ef8-1e4d-4462-ac9e-c2c648c5f421)

**Comment by seerge** [comment]
@NairoDorian i meant the same :) it's a proprietary part of AC, it can be replaced with a separate app from asus. Please check my answer and FAQ
