### ISSUE TITLE
Close all apps toggle not working properly and Some other bugs.

### ISSUE THREAD

**Issue by MaxHornet** [seerge/g-helper#1909]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

Hello @seerge , I have been using the g helper for a while now, found few bugs ,

First Bug :  When the auto close all apps toggle is ON, while switching to eco mode, it closes the apps and works properly but, if i turn the toggle OFF it still kills the apps using the gpu.

Request: Add a toast or popup giving a warning while switcing to eco when the toggle is ON for "close all apps"
And also maybe add a dedicated tiny button for killing apps form the menu.

Second Bug : The keybinding for Fn+c doesn't work.

### How to reproduce the bug?

Bug1 : Keep the "close all apps" toggle OFF, Play any game or app using gpu and then switch the gpu to eco, it kills those apps.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13927802/log.txt)

### Device and Model

Asus TUF F15 FX507ZV4

### Asus Software

- [X] Armoury Crate
- [X] MyAsus
- [x] Other Asus Services

### Version

0.146.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@MaxHornet hello

What apps are you expecting to get closed ? 

I see that it stopped 2 
```
1/13/2024 4:40:11 PM: Stopped: ASUSSmartDisplayControl
1/13/2024 4:40:12 PM: Kill:brave
1/13/2024 4:40:12 PM: Stopped: brave
```

If you don't select to close apps, G-Helper won't touch them. But since GPU is powered off anyway, windows itself can close them as well, or apps that were using GPU actively simply can quit / crash if they are not programmed to handle that.

But usually things like browsers or native windows apps usually are fine.

G-Helper already has a popup warning to stop GPU heavy apps before switching, if it detects a heavy GPU usage (>10%), for a game or so

--

As for ``Fn+C`` TUFs simply don't have that keybinding in a first place.

**Comment by MaxHornet** [comment]
@seerge I see, after 10% usage it shows a toast to turn off gpu if the tgoggle is OFF, if its ON there is no toast it closes forcefully.

I play some small cpu bounded games like krunker, it closes forcefully. Some other small apps too.

And yeah there is one more forgot to tell, i was using my gpu to drive my display using advanced optimus and have put my gpu mode to optimised , there was a power outage and my laptop got frozen for 10 seconds and display got black completely, GPU got closed forcefully due to optimised mode , there should be a toast too.

I suggest that the toggle off button should completely disable auto closing of apps even if gpu usage not exeeding 10%

**Comment by seerge** [comment]
@MaxHornet 

If you have unstable power - you can just stay on Standard. Then no one will touch your GPU at all.

Small apps, that you run in a browser probably don't use your GPU at all or use it on a same level as just watching youtube. 

> I suggest that the toggle off button should completely disable auto closing of apps even if gpu usage not exeeding 10%
As I have mentioned it's not G-helper closing them. Everything that it's closing - it writes to the log :)

**Comment by MaxHornet** [comment]
@seerge I see, but i still suggest a toast would be better even at low gpu usage while using optimised, like in armory crate we get a toast.

Please take time to rethink this. 

Thanks :)

**Comment by seerge** [comment]
@MaxHornet it is always some GPU usage. If app would just prevent disabling GPU while at least something is running, just whole Optimized mode will stop working. Pretty much as it does not work in Armoury (where you need to kill all apps with a button first)

It will kill whole purpose of Optimized mode :)
