### ISSUE TITLE
"default" bios fan curves do not match "default" visual plots

### ISSUE THREAD

**Issue by bootlegw137** [seerge/g-helper#191]
I was trying to adjust my fan curve on my 2022 G14 and realized that the default curve that GHelper shows for each profile, does not match what the default bios curve is actually doing.  

If you select factory default and then apply custom curve (essentially applying the default curve as a custom curve) the fan speed increases dramatically even though you have not moved any of the temp/speed points on the chart.

Any idea what the actual bios fan curves are?

**Comment by seerge** [comment]
Hello, this is indeed how bios answering to the app. The curve it answers is not exact as one that seem to be applied "by default". So if you want to apply a "custom" curve - you should use the one pre-loaded as basement, or don't apply anything - and default will work.

In short - this is how bios is coded :) I can't change it.
