### ISSUE TITLE
Keyboard randomly stops responding for a few moments in Ambient mode

### ISSUE THREAD

**Issue by newtsaet** [seerge/g-helper#1911]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

So,
my keyboard will sometimes stop responding randomly for a few moments, that can be from 30 secondes to three minutes where none of the keys are working except for the M1-M4 keys. 
This happens only when my keyboard is on Ambient mode (I don't know if it happens on other modes, but when it's on static or the issue never occured. I don't really use the other modes). 
It seems to happen only if I don't touch the keyboard for a short while (e.g. in loading screens, or if i stop typing for a minute or so, then i come back and the keyboard is not working for a moment). 
It doesn't happen consistently though, but at least once in every 25 minutes of heavy keyboard use or gaming.
I have v.0.146. Zephyrus M16 2023  - GU604VI-DS92-CA.
Thanks for the help ! :)

### How to reproduce the bug?

1. Use keyboard normally on ambient mode 
2. Don't use keyboard for a few secondes or more
3. When typing again on the keyboard, none on the keys will work except for the M1-M4 keys.
4. Wait a few moments and it will be working again.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13928340/log.txt)

### Device and Model

GU604VI-DS92-CA

### Asus Software Running

- [ ] Armoury Crate
- [ ] MyAsus
- [ ] Other Asus Services

### Version

0.146

### OS

Windows 11 23H2 22631.3007

**Comment by seerge** [comment]
@newtsaet hello, 

M16 2023 has some strange firmware, that can make keyboard unresponsive if you set color often.  And it seem to happen no matter if people use AC or G-Helper or any other app that can set backlight (based on topics on reddit, etc). 

Please check this issue and whole discussion there https://github.com/seerge/g-helper/issues/1769

It affects only modes that actually change colors on the fly by definition (in G-Helper it's Ambient only)
I have tried lots of things, with no effect :)

You can try to increase interval, between color refreshes (but then whole animation won't be smooth)

Just open ``config.json`` and add following line to the beginning, save and restart app

```
"aura_refresh" : 1000,
```

It's time between refreshes in milliseconds. 1000 - is refresh once in a second, you can try that  or 500.

**Comment by seerge** [comment]
@newtsaet did you had a chance to try higher refresh interval ? 

Also I had another suggestion for you, you can set keyboard backlight to go off in a short period of time (like 15 seconds) under ``Extra`` settings in the app.

When backlight is off - Ambient mode doesn't set any new colors (obviously)

And since you say, that it usually happens when you are away from keyboard, this can help.

**Comment by newtsaet** [comment]
Hey,
So yeah I set it to 500. So far it's been working, but I haven't got the occasion to heavy use it yet so I couldn't really witness any change, but I'll keep you posted if it happens again.
I'll set the setting like you suggested. I'm guessing it's the "Timeout plugged / on battery" setting ? by default it's set to 0 and 60. So I should input 15 in the first box, right ?

**Comment by seerge** [comment]
@newtsaet yes, to both boxes :) then your backlight will just turn off in 15 seconds (and won't update color ofc)

**Comment by seerge** [comment]
@newtsaet ok.

As I have explained, I can't do anything about it, until it will be fixed on firmware level. 
If in your case it's related to ambient mode - use any other mode.

**Comment by seerge** [comment]
@newtsaet did you try just sticking to Static mode (or any other besides Ambient / Heatmap) ? Cause if the situation would happen in those conditions, it's absolutely unrelated to G-Helper (as those modes are set and forget on hardware level).

**Comment by newtsaet** [comment]
Well yeah I can try sticking to static mode, I guess it's the only solution ! It's a shame cause ambient mode is so cool, especially for nightime use. Maybe some day a firmware update will fix it as you said. Thanks for trying to help anyways !

**Comment by seerge** [comment]
@newtsaet hello, if you are still there. I was experimenting with ways to send USB commands and had one idea to test. 

Can you please check this build and see if it by any accident solves your problem ?

[GHelper.zip](https://github.com/seerge/g-helper/files/14251199/GHelper.zip)

**Comment by newtsaet** [comment]
Hi @seerge,

Just tried the build for 2 hours. It happened again, only once though. Again, after not touching the keyboard for a moment (that moment can be as little as a few seconds).
But thanks for trying ! I feel like it's not happening as often as before, but maybe it's just me.

**Comment by seerge** [comment]
@newtsaet oke, thanks for trying. Another M16 user from other topic, says it seem to help him. So I'm not sure why yet.

Btw, I forgot to ask - but did it happen when you used Armoury's similar backlight mode (I forgot how it's called there) ?

**Comment by seerge** [comment]
@newtsaet can you try one more build - it should just stop Ambient mode changes 10 seconds after windows thinks input devices are inactive. 

I thought it might be reasonable to test since it happens when you don't touch keyboard

[GHelper.zip](https://github.com/seerge/g-helper/files/14271529/GHelper.zip)

**Comment by newtsaet** [comment]
thanks, I will try it and keep you posted. I don't know about Armoury Crate, because when I bought this laptop uninstalling AC and installing Ghelper was among the first things I did.

**Comment by seerge** [comment]
@newtsaet actually, if you want - can you test this build ?

What seem to be the reason, is that when keyboard backlight is OFF (due timeout shutdown or any other reason) - and color settings arrive, it doesn't handle them properly.

In this build, I have tried to stop all color commands when backlight is off (and start them again when it's on) for Ambient / Heatmap

[GHelper.zip](https://github.com/seerge/g-helper/files/14299014/GHelper.zip)

**Comment by seerge** [comment]
@newtsaet great! Just to clarify - under "new" build, do you mean build posted 3 hours ago, or yesterday? :)

**Comment by newtsaet** [comment]
I meant the one you just posted 3 hours ago ;)

**Comment by seerge** [comment]
@newtsaet did you manage to catch unresponsiveness yet ?

**Comment by seerge** [comment]
@newtsaet oke! It's already live in latest 0.154 as it doesn't harm anyone (only improves performance while backlight is off)
