### ISSUE TITLE
Control screen brightness of Zephyrus and Zenbook Duo devices

### ISSUE THREAD

**Issue by moldimolt** [seerge/g-helper#1919]
Hello. Would it be possible to control the screen brightness of the Zephyrus and Zenbook Duo devices, similar to the keyboard and AniMe matrix? Windows itself doesn't seem to be able to control this display's brightness, and instead it's managed by the ASUS ScreenXpert software. Other features ScreenXpert has that seem like they might be in-scope for G-Helper are: 

* **Task Swap:** One-click swap all windows between the displays.
* **Mouse Locker:** Lock the mouse pointer to the main display only
* **Microphone management:** One-click toggle to enable/disable the system microphone.
* **ScreenPad Plus battery saver:** Lower ScreenPad Plus brightness automatically when Windows battery saver mode is enabled, similar to the native Windows setting for the main display.

It has many other features as well, but they have complex UIs and functions that don't seem to be in-scope for G-Helper.

More info: https://www.asus.com/content/screenxpert3/

**Comment by seerge** [comment]
@moldimolt hello,

I didn't really get what you mean. Brightness is controlled by windows/drivers anyway. Other apps just utilize windows API to set it.

If you mean "screenpad" (secondary screen) brightness it's already possible via G-Helper for a long time and mentioned in readme

``Fn + Shift + F7 / F8`` - Screenpad brightness Down / Up

**Comment by moldimolt** [comment]
I see. My apologies, I was unaware of that feature! It does indeed work on my device. Since you mentioned this is controlled via a Windows API, would you happen to know why Windows seemingly cannot manage the brightness of the second display through its built-in brightness control settings? It only adjusts the brightness of the main display, selecting the ScreenPad Plus in Display Settings makes no difference. Ubuntu and Fedora appear to behave the same way, so I had assumed ASUS was using some non-standard brightness control mechanism.

**Comment by seerge** [comment]
@moldimolt Screenpad is Asus proprietary stuff :) you need either Asus own app or G-Helper to control that (pretty much as for any other proprietary things)
