### ISSUE TITLE
CPU Temp limit not working

### ISSUE THREAD

**Issue by sirring6** [seerge/g-helper#1920]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

CPU temperature ignores the CPU Temp Limit set in G-Helper.
I have it set to 85 degrees, yet G-Helper as well as HWInfo show my CPU heating up to around 96 degrees under load.

### How to reproduce the bug?

1. Adjust slider to desired temp limit in G-Helper
2. Put CPU under load and watch temperatures rise past the limit set on the Temp Limit slider

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13931295/log.txt)

### Device and Model

ASUS ROG Zephyrus G15 GA503QM (2021)

### Asus Software Running

- [ ] Armoury Crate
- [ ] MyAsus
- [ ] Other Asus Services

### Version

0.146

### OS

Win 11 22H2

**Comment by seerge** [comment]
@sirring6 Hello, I think you are missing winring0 files (that come with g-helper in same zip). You need to extract them into same folder.

As it says it can't access it 
```
14/01/2024 10:14:39 PM: UV Error: System.TypeInitializationException: The type initializer for 'Ryzen.SendCommand' threw an exception.
 ---> System.ApplicationException: WinRing OLS_DRIVER_NOT_LOADED
```
Also before i see that that Temperature command was simply rejected
```
14/01/2024 6:54:36 PM: CPU Temp: 85 BAD
14/01/2024 6:54:37 PM: APU Temp: 85 BAD
````

It could be that your device doesn't support it. So I can't do anything about it :)

**Comment by seerge** [comment]
P.S. Did you try rebooting? :)

**Comment by sirring6** [comment]
Hey, thanks for getting back to me!
So after double checking that the files are in the right folder, a couple reboots and running G-Helper in administrator mode,
it seems like the Temp Limiter is now working.
Not sure what the actual issue might have been, but thanks for your help regardless!

Have a great day!

**Comment by seerge** [comment]
Great, I'm glad it has resolved by itself.
