### ISSUE TITLE
Asus TUF A15 FA506-BQ200 Fan control not working

### ISSUE THREAD

**Issue by sezertrk** [seerge/g-helper#1921]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

custom fan curve setting not working

### How to reproduce the bug?

70° cpu fan work settings 
43°-70° fan 2200 rpm working disable fan rpm not working

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13932724/log.txt)

### Device and Model

Asus TUF A15 FA506-BQ200 

### Additional information.

![fa506](https://github.com/seerge/g-helper/assets/43032011/598d40c1-7c16-494a-bffc-49a17e45d952)

### Asus Software Running

- [X] Armoury Crate
- [X] MyAsus
- [X] Other Asus Services

### Version

0.146

### OS

Windows 10 64 bit

**Comment by seerge** [comment]
@sezertrk you didn't check FAQ

> ### When I try to apply a custom fan curve I get "BIOS rejected fan curve"
> TUF models from 2021 and older don't support custom fan curves at all. Most probably you didn't have them in the Armoury as well?
