### ISSUE TITLE
0.147 wont open,  seems to hang in the system tray

### ISSUE THREAD

**Issue by Draebor** [seerge/g-helper#1924]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

0.147 doesnt open at all from the system tray for me.

have to close it from task manager otherwise it sits there unresponsive

rightclick doesnt bring up menu, and leftclick doesnt bring up the ghelper interface.

### How to reproduce the bug?

bug happens anytime i install and run 0.147.

have rolled back to 0.146 for the time being.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13934420/log.txt)

### Device and Model

asus tuf gaming F17 FX706HC

### Asus Software Running

- [ ] Armoury Crate
- [ ] MyAsus
- [ ] Other Asus Services

### Version

0.147

### OS

Windows 11 Pro 23H2

**Comment by Kikimahe** [comment]
Hi,

Same problem here. (F17 FX707ZM)

Double-clicking the Ghelper icon doesn't open it, nothing happens.
After about 2 minutes, the Ghelper window finally opens.
[log.txt](https://github.com/seerge/g-helper/files/13935615/log.txt)

**Comment by Kikimahe** [comment]
It works fine Seerge, loading time is restored. 👍 

On the other hand, I also noticed the issue described in [#1925](https://github.com/seerge/g-helper/issues/1925) 

Switching from Standard to Eco caused a long loading Windows error that ask restarting Ghelper.
With this latest version it's better, but the swithch time in Standard->Eco and eco->Standard is longer than usual.

**Comment by seerge** [comment]
@Kikimahe that thing just depends on how fast BIOS is with doing it's job for GPU :) as I have answered there I can't do much about that.

I have just uploaded a quickfix over existing 0.147 so it should be fine. Thanks for spotting.

**Comment by Kikimahe** [comment]
> cette chose dépend simplement de la vitesse à laquelle le BIOS fait son travail pour le GPU :) comme je l’ai dit là-bas, je ne peux pas faire grand-chose à ce sujet.

I understand. 

This morning's patch V0.147 fixed the iddue, AFTER restart Windows.

Now, when switching from STANDARD mode to ECO mode
* Long "loading" issue for "igpu only" has been fixed.
* Windows popup issue prompting to restart Ghelper has been fixed.

Everything is fine. 👍
