### ISSUE TITLE
GPU Switch Process blocking the main thread and causing the process is not responding error

### ISSUE THREAD

**Issue by theDRB123** [seerge/g-helper#1925]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

Many times some issue occurs due to which the GPU switching becomes very slow and application stops responding until switching completes 
(occurs mostly when changing from standard to eco)

### How to reproduce the bug?

select standard mode, 
then select eco mode, 
during the change none of the buttons work and many times the proccess is not responding messages is shown

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13936202/log.txt)

### Device and Model

Asus Zephyrus G14 GA401QH_GA401QH

### Asus Software Running

- [ ] Armoury Crate
- [X] MyAsus
- [ ] Other Asus Services

### Version

0.146

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@theDRB123 hello, that could happen, but this is unfortunately how any call to ACPI affects application. 

This call is already running on a separate thread, but whole process got locked :) And I don't know if it's even possible to change that, w/o splitting app into separate service and a client (which i don't want to do to keep it portable and lightweight)

GPU switching command can take BIOS to take few seconds to do it's thing.

And on a side note, I don't know if it's bad or good. As I wouldn't allow user to do any other commands while GPU is turning OFF for example.

But if you know a better solution, please feel to offer a PR :)

Closing, as I can't do anything about that atm.

**Comment by theDRB123** [comment]
> @theDRB123 hello, that could happen, but this is unfortunately how any call to ACPI affects application.
> 
> This call is already running on a separate thread, but whole process got locked :) And I don't know if it's even possible to change that, w/o splitting app into separate service and a client (which i don't want to do to keep it portable and lightweight)
> 
> GPU switching command can take BIOS to take few seconds to do it's thing.
> 
> And on a side note, I don't know if it's bad or good. As I wouldn't allow user to do any other commands while GPU is turning OFF for example.
> 
> But if you know a better solution, please feel to offer a PR :)
> 
> Closing, as I can't do anything about that atm.

Sure, i will look at it ( i am a beginner so probably wont fix but still)...
