### ISSUE TITLE
Fan is not boosting beyond 2900RPM

### ISSUE THREAD

**Issue by phoniexx9** [seerge/g-helper#1926]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

I was on the update #0.144 and I updated to #0.146 and both my fans stopped boosting beyond 2900RPM in turbo profile, my laptop model is Asus Tuf F17 TUF706HE. I rolled back to 0.144 and everything is back to normal, restarting didn't fix the problem

### How to reproduce the bug?

Open G-Helper 
Run a stress test
temperature goes up to 95
fan starts ramping up till 2900RPM
temp is still high 
fan doesn't go any higher 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13936683/log.txt)

### Device and Model

 Asus Tuf F17 TUF706HE

### Asus Software Running

- [ ] Armoury Crate
- [ ] MyAsus
- [ ] Other Asus Services

### Version

0.146

### OS

Windows  11 22H2

**Comment by seerge** [comment]
@phoniexx9 hello,

G-Helper doesn't and can't control your fans :) They are controlled by BIOS, as it's mentioned in FAQ as well.

More over, you are not even setting a custom fan curves, and just use default balanced mode, which is just 1 command

```
15/01/2024 10:19:00 am: Mode = 1 : OK
```

There is absolutely nothing that has changed related to this in last few months in the app at all.

Did you try restarting ?

**Comment by seerge** [comment]
@phoniexx9 did you try doing https://github.com/seerge/g-helper/wiki/Troubleshooting#hardware-reset--cmos-reset ?

**Comment by seerge** [comment]
@phoniexx9 Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks
