### ISSUE TITLE
M16 GU604VI Anime Matrix Clock time display has issue

### ISSUE THREAD

**Issue by LeThe-Zhu** [seerge/g-helper#1928]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

Anime Matrix Clock time  can't display in the correct location
![Clock Time](https://github.com/seerge/g-helper/assets/23567962/7972ac5d-c284-47b3-9ccc-96afe16b94cd)

### How to reproduce the bug?

Chose Matrix Clock type

### Logs

![image](https://github.com/seerge/g-helper/assets/23567962/11c13647-68fe-476d-bb18-7717cdb27b0d)

### Device and Model

M16 GU604VI 

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.146

### OS

Win11 23H2 22631

**Comment by seerge** [comment]
@LeThe-Zhu what display scaling do you have in windows?

**Comment by seerge** [comment]
@LeThe-Zhu try this build and post a photo of a clock on your matrix again

[GHelper.zip](https://github.com/seerge/g-helper/files/13943160/GHelper.zip)

**Comment by IceStormNG** [comment]
I actually have the same issue on my M16 with the clock. all the other things are aligned correctly, but not the clock.

**Comment by seerge** [comment]
@IceStormNG my assumption was that ``MeasureString`` didn't return correct dimensions of a text by some reason (mb due to windows scaling) here

https://github.com/seerge/g-helper/blob/30fb32c3d5e930364f2f4a1d3023e1494aa1232e/app/AnimeMatrix/AnimeMatrixDevice.cs#L448C31-L448C31

Does the build I have linked "fix" it ? I have aligned text to the left instead of right

**Comment by IceStormNG** [comment]
> Does the build I have linked "fix" it ? I have aligned text to the left instead of right

For me, it does.

**Comment by seerge** [comment]
@IceStormNG oke :) If both lines fit to the width correctly - then I assume it's fixed. 

Thanks.
