### ISSUE TITLE
Support for XG Mobile

### ISSUE THREAD

**Issue by moritzbeck01** [seerge/g-helper#193]
Is there support for the XG Mobile? When connected to it, disabling the dGPU seems to disable the XG Mobile instead of my 3050 Ti. But changing the fan profile for the GPU seems to do nothing.

**Comment by Samer1FL** [comment]
i tried this but it didnt work for me.
just for your record, XG mobile isolates the dGPU whenever it connects, but it tried to adjust the fans using your software but it is not working at all for XG Mobile.

we will appreciate whatever you customize to activate XG Mobile through your app and adjust the clock and fans.

**Comment by seerge** [comment]
@Samer1FL what is the output from powershell after running disable or enable command?

**Comment by moritzbeck01** [comment]
Sorry, don't have notifications on and don't check on here too often. The commands works for me (XG Mobile 6850M XT), though my task bar is messed up/gone/hidden afterwards. Might be a Windows 11 bug though.

**Comment by seerge** [comment]
@moritzbeck01 under "commands" you mean setting fan curve?  

As for task bar - i have no idea what should happen there, app doesn't touch your task bar in any way. But I can imagine cause windows detects new device + new screen, it can act somehow  based on that.

**Comment by moritzbeck01** [comment]
> @moritzbeck01 under "commands" you mean setting fan curve - #301 ? Or just enabling / disabling XGMobile ?

I mean these:
> Can you try to run in power shell as admin
> 
> ```
> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00090019, 1) - to enable eGPU
> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00090019, 0) - to disable eGPU
> ```
> 
> do they work ?
I can do a more thorough test later.


> As for task bar - i have no idea what should happen there, app doesn't touch your task bar in any way. But I can imagine cause windows detects new device + new screen, it can act somehow based on that.

I think because I have my X13 in tent mode when with the eGPU, Windows thinks the new monitor, which is my main display output, is the same as the old one, which is the inbuilt display in tablet mode, which has the taskbar hidden by default. The inbuilt display is then has a normal taskbar.

**Comment by seerge** [comment]
@moritzbeck01 ah, cause you were answering so slow - i have already added a separate button for XG Mobile to the app :) so you can just download latest build and use it.
