### ISSUE TITLE
Back Window RGB Control Doesn't Work For Z13 2022

### ISSUE THREAD

**Issue by Zeberko1** [seerge/g-helper#1930]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

I have 2 issues:

1: When I set only Keyboard Backlight Awake to True, the rear RGB window brightness is locked to the same as the keyboard. Increasing / decreasing the brightness using the slider or shortcut applies to both. Disabling Logo or Lid backlight doesn't disable the rear RGB window, when it should.
![Keyboard Backlight On](https://github.com/seerge/g-helper/assets/156717636/91a3573e-3dc3-4868-8ba2-7943895ff6ff)

2: When disabling all Awake Backlights, the LEDs in the RGB window stay on, and are affected by the brightness slider and keyboard shortcut. When the brightness is reduced to 0, some stay on. It doesn't seem consistent which ones stay on, sometimes the left LEDs and sometimes the right LEDs.

### How to reproduce the bug?

1. Disable all backlights except Keyboard Awake. _Keyboard Backlight is on. Rear LEDs remain on._
![20240115_215237](https://github.com/seerge/g-helper/assets/156717636/98735439-e3a5-4c0c-96c1-0e1515364b41)

2. Disable Keyboard Awake, meaning that no RGB should be on. _Rear LEDs still on._
![Keyboard Backlight Off](https://github.com/seerge/g-helper/assets/156717636/3e49da54-78db-47d9-888a-4d19e2099d0d)

3. Change brightness to 0 using slider in GHelper or keyboard shortcut. _Some of the Rear LEDs are still on, while some turn off._
![Keyboard Backlight Off   Brightness Off](https://github.com/seerge/g-helper/assets/156717636/882410f8-5397-4d84-844f-142494ad7c81)

![20240115_215413](https://github.com/seerge/g-helper/assets/156717636/f73a64ec-3bea-4a53-94ef-9f8d05f18895)

_In the image, the left LEDs remain on._

### Logs

15/01/2024 22:05:37: ------------
15/01/2024 22:05:37: App launched: ROG Flow Z13 GZ301ZE_GZ301ZE :0.146.0.0en-GB
15/01/2024 22:05:38: NVIDIA GeForce RTX 3050 Ti Laptop GPU
15/01/2024 22:05:39: CPU: -1 - 12th Gen Intel(R) Core(TM) i9-12900H - Intel64 Family 6 Model 154 Stepping 3
15/01/2024 22:05:39: AutoSetting for Online
15/01/2024 22:05:39: Input: \\?\hid#vid_0b05&pid_1a30&mi_00&col01#7&391df2e&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
15/01/2024 22:05:39: Mode = 2 : OK
15/01/2024 22:05:39: Eco flag : 0
15/01/2024 22:05:39: Mux flag : 1
15/01/2024 22:05:39: \\?\DISPLAY#SHP154F#4&6b10be&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
15/01/2024 22:05:39: \\?\DISPLAY#SHP154F#4&6b10be&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
15/01/2024 22:05:40: Screen = 120Hz : OK
15/01/2024 22:05:40: ScreenOverdrive = 1 : 0
15/01/2024 22:05:40: BatteryLimit = 60 : OK
15/01/2024 22:05:40: BatteryLimit = 60 : OK
15/01/2024 22:05:40: USB 18C6: 5D-BD-01-08-1E-00-00-FF
15/01/2024 22:05:40: USB 1A30: 5D-BD-01-08-1E-00-00-FF
15/01/2024 22:05:40: AuraMode: AuraStatic
15/01/2024 22:05:40: USB 18C6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
15/01/2024 22:05:40: USB 18C6: 5D-B4
15/01/2024 22:05:40: USB 18C6: 5D-B5-00-00-00
15/01/2024 22:05:40: USB 1A30: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
15/01/2024 22:05:40: USB 1A30: 5D-B4
15/01/2024 22:05:40: USB 1A30: 5D-B5-00-00-00
15/01/2024 22:05:40: Init 18C6: 5D-B9
15/01/2024 22:05:40: Init 18C6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
15/01/2024 22:05:40: Init 18C6: 5D-05-20-31-00-1A
15/01/2024 22:05:40: Init 1A30: 5D-B9
15/01/2024 22:05:40: Init 1A30: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
15/01/2024 22:05:40: Init 1A30: 5D-05-20-31-00-1A
15/01/2024 22:05:40: Monitor Power On
15/01/2024 22:05:41: Design Capacity: 56002mWh, Full Charge Capacity: 49715mWh, Health: 0.887736152280275704439127174%
15/01/2024 22:05:41: Auto 18C6: 5D-BA-C5-C4-01
15/01/2024 22:05:41: Auto 1A30: 5D-BA-C5-C4-01
15/01/2024 22:05:42: Latest version 0.146.0.0
15/01/2024 22:05:42: Hibernate after 2147483647
15/01/2024 22:05:56: Slider 18C6: 5D-BA-C5-C4-02
15/01/2024 22:05:56: Slider 1A30: 5D-BA-C5-C4-02
15/01/2024 22:05:56: Slider 18C6: 5D-BA-C5-C4-03
15/01/2024 22:05:56: Slider 1A30: 5D-BA-C5-C4-03
15/01/2024 22:05:56: Slider 18C6: 5D-BA-C5-C4-02
15/01/2024 22:05:56: Slider 1A30: 5D-BA-C5-C4-02
15/01/2024 22:05:56: Slider 18C6: 5D-BA-C5-C4-01
15/01/2024 22:05:56: Slider 1A30: 5D-BA-C5-C4-01
15/01/2024 22:05:56: Slider 18C6: 5D-BA-C5-C4-00
15/01/2024 22:05:56: Slider 1A30: 5D-BA-C5-C4-00
15/01/2024 22:05:57: Slider 18C6: 5D-BA-C5-C4-01
15/01/2024 22:05:57: Slider 1A30: 5D-BA-C5-C4-01
15/01/2024 22:06:00: Key: 199
15/01/2024 22:06:00: HotKey 18C6: 5D-BA-C5-C4-02
15/01/2024 22:06:00: HotKey 1A30: 5D-BA-C5-C4-02
15/01/2024 22:06:01: Key: 199
15/01/2024 22:06:01: HotKey 18C6: 5D-BA-C5-C4-03
15/01/2024 22:06:01: HotKey 1A30: 5D-BA-C5-C4-03
15/01/2024 22:06:02: Key: 199
15/01/2024 22:06:02: HotKey 18C6: 5D-BA-C5-C4-00
15/01/2024 22:06:02: HotKey 1A30: 5D-BA-C5-C4-00
15/01/2024 22:06:05: Key: 199
15/01/2024 22:06:05: HotKey 18C6: 5D-BA-C5-C4-01
15/01/2024 22:06:05: HotKey 1A30: 5D-BA-C5-C4-01
15/01/2024 22:06:07: USB 18C6: 5D-BD-01-00-1E-00-00-FF
15/01/2024 22:06:07: USB 1A30: 5D-BD-01-00-1E-00-00-FF
15/01/2024 22:06:11: Key: 199
15/01/2024 22:06:11: HotKey 18C6: 5D-BA-C5-C4-02
15/01/2024 22:06:11: HotKey 1A30: 5D-BA-C5-C4-02
15/01/2024 22:06:12: Key: 199
15/01/2024 22:06:12: HotKey 18C6: 5D-BA-C5-C4-03
15/01/2024 22:06:12: HotKey 1A30: 5D-BA-C5-C4-03
15/01/2024 22:06:13: Key: 199
15/01/2024 22:06:13: HotKey 18C6: 5D-BA-C5-C4-00
15/01/2024 22:06:13: HotKey 1A30: 5D-BA-C5-C4-00
15/01/2024 22:06:15: Key: 199
15/01/2024 22:06:15: HotKey 18C6: 5D-BA-C5-C4-01
15/01/2024 22:06:15: HotKey 1A30: 5D-BA-C5-C4-01
15/01/2024 22:06:19: Slider 18C6: 5D-BA-C5-C4-00
15/01/2024 22:06:19: Slider 1A30: 5D-BA-C5-C4-00
15/01/2024 22:06:25: Slider 18C6: 5D-BA-C5-C4-01
15/01/2024 22:06:25: Slider 1A30: 5D-BA-C5-C4-01
15/01/2024 22:06:28: USB 18C6: 5D-BD-01-08-1E-00-00-FF
15/01/2024 22:06:28: USB 1A30: 5D-BD-01-08-1E-00-00-FF

### Device and Model

Z13 2022 GZ301ZE

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.146.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Zeberko1 hello, are you able to control back window with OpenRGB ?

**Comment by Zeberko1** [comment]
Also, changing the RGB mode from Static to Rainbow makes it so that Logo Awake works on the back window, but Breathe doesn't.

I can try downloading OpenRGB to see if it works.

**Comment by seerge** [comment]
@Zeberko1 then I'm afraid I don't know how to turn that off :) as there is no other open source information about it

Try this build, I have unlocked "lightbar" checkboxes from Strix models in Extra, mb they can turn it off ...

[GHelper.zip](https://github.com/seerge/g-helper/files/13943864/GHelper.zip)

**Comment by Zeberko1** [comment]
That helped with issue 1. When in Static RGB mode, disabling Lightbar turns off the rear window LEDs. However, now one of them is stuck a different colour when the LEDs are on.

**Comment by seerge** [comment]
@Zeberko1 well, I have no idea how to set a color honestly :) as it's also not available in OpenRGB

**Comment by Zeberko1** [comment]
This is already much better though, as I can turn the rear LEDs off. Thank you.

**Comment by seerge** [comment]
@Zeberko1 does changing Modes affect color of back window anyhow ?

**Comment by Zeberko1** [comment]
Yes. Changing RGB mode changes the LEDs on the back with the exception of that one currently stuck LED, and as previously mentioned changing to Rainbow makes the Window respond to the Logo toggle.

**Comment by seerge** [comment]
So it's multiple leds on the back, and some change except one ? I honestly have no idea how it looks even)) i don't have z13

**Comment by Zeberko1** [comment]
It's just a window pointed at part of the motherboard with an LED strip at the top.

**Comment by seerge** [comment]
Ok. Well, i'm glad you can turn it off now at least, closing as completed then

**Comment by SonNGUYEN515** [comment]
I would like to add a comment to this problem, I have the same problem with build 0.144, where 2 LED of the back window cannot be controlled. However, after digging around the forum, there is a custom build of version 0.101, which was meant to fix a back lightbar problem on another ROG, actually also fix ROG in the back of Z13. Hope this help you narrow the problem. Attached is the mentioned build 0.101
[GHelper.zip](https://github.com/seerge/g-helper/files/14071077/GHelper.zip)

**Comment by seerge** [comment]
@SonNGUYEN515 just get latest 0.148 (or even 0.150), it will shown all possible checkboxes for Z13. And based on what I have heard, "Logo" or "Lid" checkboxes are treated by Z13 as that back-window :)

**Comment by SonNGUYEN515** [comment]
I can confirm that latest version of 148 has fixed the problem. Thank you so much for your support.
