### ISSUE TITLE
Shortcut to set _specific_ custom profiles

### ISSUE THREAD

**Issue by MrThePlague** [seerge/g-helper#1931]
**Is your feature request related to a problem? Please describe.**

It would be great to have the capability of setting hot keys to set specific profiles. 

Use case: I would like to be able to configure Playnite to use a hotkey when a game launches in order to set a specific profile for a game. E.g.: set the 7W profile when XPlay is launched. Set the 12W profile when Cocoon is launched.

**Describe the solution you'd like**
Without a more complicated solution, simply the ability to map a specific hot key to each profile would probably do the trick.

**Describe alternatives you've considered**

**Additional context**

**Comment by seerge** [comment]
@MrThePlague hello, did you know that you can already cycle between profiles (even custom) forwards and backwards ?

``Fn + F5 / Fn + Shift + F5`` - Toggle Performance Modes forwards / backwards
``Ctrl + Shift + F5 / Ctrl + Shift + Alt + F5`` - Toggle Performance Modes forwards / backwards

**Comment by MrThePlague** [comment]
Yes, absolutely, thank you. 

What would be awesome though would be to be able to key bind specific profiles. 

The Playnite launcher allows you to run a script when launching a game, so I'd like to be able to set a specific per game by executing the keybind, e.g.: launch XPlay -> set 7W profile. Launch Cocoon -> set 12W profile, etc.

**Comment by seerge** [comment]
@MrThePlague try this build

I have reserved 5 hotkeys for mode switches

``Ctrl + Shift + Alt + F16`` - Silent
``Ctrl + Shift + Alt + F17`` - Balanced
``Ctrl + Shift + Alt + F18`` - Turbo
``Ctrl + Shift + Alt + F19`` - Custom 1 (if exists)
``Ctrl + Shift + Alt + F20`` - Custom 2 (if exists)

[GHelper.zip](https://github.com/seerge/g-helper/files/13966162/GHelper.zip)

**Comment by seerge** [comment]
@MrThePlague did you had a chance to check the build ?

**Comment by MrThePlague** [comment]
Yes, just tested it and it looks good! Thank you! Really appreciate the work you put into this tool.

**Comment by ggjiza** [comment]
I'm trying to use 0x11 0x10 0x12 0x82 = Ctrl + Shift + Alt + F19 in my M16 but it doesn't work. 
When using a software to detect keyboard and trying other keys besides F19/0x82 (Ctrl + Shift + Alt + X), the macro custom action doesn't seem to run.
0x11 0x10 0x12 registers Ctrl + Shift + Alt, 0x11 0x10 0x12 0x82/X doesn't register any key.

**Comment by seerge** [comment]
@ggjiza you mix 2 separate things.

Those are external hotkeys (i.e. something that you are supposed to emit from other app or game-launcher as issue starter requested).

You are talking about binding macro keys (M1-M4) to emit some key-combos :) they support only 3 keys simultaneously atm

**Comment by ggjiza** [comment]
I see, thank you for the clarification.
So if the macro binding supports 4 keys it should do what I expected.
That wouldn't be a bad feature to have in the next update :)

**Comment by seerge** [comment]
@ggjiza what are you trying to achieve? Bind M-key to specific profile ?

**Comment by ggjiza** [comment]
Yes, practically a faster way to reach a specific profile without having to toggle through them all.

**Comment by MrB0x** [comment]
Is there a way to disable the second set of bindings?

"Ctrl + Shift + F5 / Ctrl + Shift + Alt + F5 - Toggle Performance Modes forwards / backwards"

I have an fn key for the first set of bindings to toggle performance modes forwards / backwards but use the second set of key combination ctrl + shift + f1-12 for applications.

**Comment by seerge** [comment]
@MrB0x yes, [there is a way](https://github.com/seerge/g-helper/wiki/Power-user-settings#extra-keybindings)
