### ISSUE TITLE
Windows Defender reporting as trojan

### ISSUE THREAD

**Issue by scrazzz** [seerge/g-helper#1935]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

Windows Defender marked GHelper.exe as a Trojan, not sure why it started doing this today. I've had installed this program since last year.
![1705412239555](https://github.com/seerge/g-helper/assets/70033559/c5717229-e5e5-4175-bda1-1fc70eabb544)

### How to reproduce the bug?

N/A, Windows Defender run scans regularly

### Logs

N/A but here it is nonetheless because I've seen issues being closed for not providing the logs:
```
16/01/2024 5:05:19 PM: ------------
16/01/2024 5:05:19 PM: App launched: ASUS TUF Gaming F15 FX506H<REDACTED>0.146.0.0en-US.
16/01/2024 5:05:22 PM: NVIDIA GeForce RTX 3050 Laptop GPU
16/01/2024 5:05:23 PM: CPU: -1 - 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz - Intel64 Family 6 Model 141 Stepping 1
16/01/2024 5:05:23 PM: AutoSetting for Online
16/01/2024 5:05:24 PM: Input device not found
16/01/2024 5:05:24 PM: Mode = 0 : OK
16/01/2024 5:05:24 PM: Eco flag : 0
16/01/2024 5:05:24 PM: Mux flag : -65536
16/01/2024 5:05:24 PM: GET CLOCK LIMIT: 0
16/01/2024 5:05:24 PM: \\?\DISPLAY#<REDACTED>DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
16/01/2024 5:05:24 PM: \\?\DISPLAY#<REDACTED>\\.\DISPLAY1\Monitor0
16/01/2024 5:05:24 PM: GET GPU CLOCKS: 0, 0
16/01/2024 5:05:25 PM: Screen = 144Hz : OK
16/01/2024 5:05:25 PM: ScreenOverdrive = 1 : OK
16/01/2024 5:05:25 PM: BatteryLimit = 60 : OK
16/01/2024 5:05:25 PM: BatteryLimit = 60 : OK
16/01/2024 5:05:25 PM: TUF_KB = 16712125 : OK
16/01/2024 5:05:25 PM: AuraMode: AuraColorCycle
16/01/2024 5:05:25 PM: TUF RGB = B4-02-00-FF-FF-EB : OK
16/01/2024 5:05:25 PM: Monitor Power On
16/01/2024 5:05:26 PM: TUF Brightness = 129 : OK
16/01/2024 7:06:34 PM: Design Capacity: 48001mWh, Full Charge Capacity: 42523mWh, Health: 0.8858773775546342784525322389%
16/01/2024 7:06:35 PM: Latest version 0.146.0.0
```

### Device and Model

ASUS TUF Gaming F15

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.146.0.0

### OS

Win 11 22H2

**Comment by seerge** [comment]
@scrazzz  hello

> # Windows Defender marks app as malware / virus
> False positives from Windows Defender (or any other similar system that uses machine learning for detection) is possible as the application is not digitally signed with a certificate. You can always download a version below or compile the app by yourself. All application sources are open and can be monitored from A to Z :)

https://github.com/seerge/g-helper/wiki/FAQ#windows-defender-marks-app-as-malware--virus

**Comment by scrazzz** [comment]
Whoops, missed it. Thanks.
