### ISSUE TITLE
ESET Smart Security detection

### ISSUE THREAD

**Issue by MrHumanRebel** [seerge/g-helper#1938]
Have been using this program for a while now, today for some reason ESET marked it as suspicios for no reason, and cannot exclude it from detection. Do you have any ideas how to solve this?

Thanks.

![image](https://github.com/seerge/g-helper/assets/80947401/afb17d81-d7b8-48e7-9d2d-b4d3acda065a)

![image](https://github.com/seerge/g-helper/assets/80947401/2a6169ec-577b-477a-b85a-35ba7fb874a5)

**Comment by seerge** [comment]
@MrHumanRebel hello, try to download 0.147 :) 

> ### Windows Defender marks app as malware / virus
> False positives from Windows Defender (or any other similar system that uses machine learning for detection) is possible as the application is not digitally signed with a certificate. You can always download a version below or compile the app by yourself. All application sources are open and can be monitored from A to Z :)

**Comment by seerge** [comment]
Or actually 0.148 now)
