### ISSUE TITLE
AC charger issue

### ISSUE THREAD

**Issue by Ahhh-Mad** [seerge/g-helper#1940]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

when charging via the AC Adapter model - A20-240P1A of my G14-2022 version ,the battery stops charging

### How to reproduce the bug?

1.run G-Helper
2. plug the charger 
3. battery starts charging for a second then windows switch to "on Battery"
4. unplug the charger - open G-Helper > Extras , Force close services 
5. Run Asus Services again 
6. quit G-Helper 
7. Plug the charger 
8. viola - runs like a charm

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13969303/log.txt)

### Device and Model

Asus ROG Zephyrus G14 GA402RK

### Armoury Crate

Uninstalled

### Asus Services

8

### Version

0.146

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@Ahhh-Mad hello, I see that you have set 40% as battery charge limit. 
Try to set it to something normal like 80% or even to 100% for the test (in MyASUS you can setect only those 2 values)

Will it start charging ? :)

**Comment by Ahhh-Mad** [comment]
Hi There Seerge 
on myAsus , there is an option to limit the charge to 60% , as im always hooked to a charger  , to keep battery health to its optimum 
but will try and let you know , ill set it to 60% and test the app 


    On Thursday, January 18, 2024 at 12:27:16 AM GMT+2, Serge ***@***.***> wrote:  
 
 


@Ahhh-Mad hello, I see that you have set 40% as battery charge limit.
Try to set it to something normal like 80% or even to 100% for the test (in MyASUS you can setect only those 2 values)

Will it start charging ? :)

**Comment by sasaiber** [comment]
My battery icon and battery driver are completely gone :D
Also in Armory, Crate writes “maximum energy saving” in the GPU. =(

Asus ROG STRIX SCAR 15 G533GS(2021)

**Comment by Ahhh-Mad** [comment]
> @Ahhh-Mad hello, I see that you have set 40% as battery charge limit. Try to set it to something normal like 80% or even to 100% for the test (in MyASUS you can setect only those 2 values)
> 
> Will it start charging ? :)
> 
> Cause when you start Asus services they set other charge limit.

Hi There @seerge 

Have switched off the laptop .. plugged the charger till it was 60% ..
Tried gaming while G-Helper is running , had no issues so far 

Let me test it again in 4 hours and I'll update you with the final results 

Keep in mind I have updated to the latest stable version of G-Helper

**Comment by Ahhh-Mad** [comment]
Hi @seerge 
have updated the G-Helper to latest Version 148, and had the same issue, AC Adapter keeps disconnecting. 
Battery is charged to 60% Limit. 

> > @Ahhh-Mad hello, I see that you have set 40% as battery charge limit. Try to set it to something normal like 80% or even to 100% for the test (in MyASUS you can setect only those 2 values)
> > Will it start charging ? :)
> > Cause when you start Asus services they set other charge limit.
> 
> Hi There @seerge
> 
> Have switched off the laptop .. plugged the charger till it was 60% .. Tried gaming while G-Helper is running , had no issues so far
> 
> Let me test it again in 4 hours and I'll update you with the final results
> 
> Keep in mind I have updated to the latest stable version of G-Helper

Hi There @seerge 

Apologies , i have done a re-test again , started my game , after the battery is charged to 60% limit 

Charger disconnects again , and after stopping all the services , start them back again , and quitting G-Helper , the AC adapter is fully functional without G-Helper
[log.txt](https://github.com/seerge/g-helper/files/13981425/log.txt)

**Comment by seerge** [comment]
@Ahhh-Mad what charging limit do you have set in MyASUS currently (i.e. what asus service sets)?

Cause charge limit, is a single setting (just a number), that you can set. And it's not "managed" in realtime anyhow. Charging is always controlled by hardware / BIOS.

I could only guess some other reason. Is that when you play you use Turbo Mode with very high power limits (150 platform + 100 CPU)
```
1/18/2024 10:28:18 PM: PowerLimit A3 = 150 : OK
1/18/2024 10:28:18 PM: PowerLimit A0 = 150 : OK
1/18/2024 10:28:18 PM: PowerLimit B0 = 100 : OK
1/18/2024 10:28:38 PM: Mode = 1 : OK
```

And due to weak charger - your laptop simply doesn't have enough juice :) 

And when you "quit" g-helper, as you say - you would switch to default (i.e. Balanced) mode with much lower limits. And then it's enough power from the charger.

Try to play on Balanced, or at least set lower limits in Turbo (or just uncheck them and use defaults)

**Comment by seerge** [comment]
@Ahhh-Mad did you had a chance to try default Turbo without super high limits or Balanced?

**Comment by Ahhh-Mad** [comment]
> @Ahhh-Mad did you had a chance to try default Turbo without super high limits or Balanced?

@seerge , I will give it a try in 2 hours

**Comment by Ahhh-Mad** [comment]
@seerge , Thanks Lots , the issue has been resolved 
Turbo + battery less than 50% of battery will not be able to get the laptop to start games under load , thus the charger disconnects .

issue has been resolved and is no connection between G-Helper and the AC charger malfunction 

I thank you lots for all your support and timely responses , God Bless you

**Comment by seerge** [comment]
Great
