### ISSUE TITLE
Higher CPU PL1/2 (Scar 16 13980hx), currently lower than Armory Crate

### ISSUE THREAD

**Issue by Sloreo1131** [seerge/g-helper#1941]
Trying out G Helper on my Scar 16 Ive added water cooling to and love being able to set the fan speeds much lower than the minimums on Armory Crate. However, I noticed while setting it up that the PL1/2 options cap at 150w while Armory crate allows PL2 to go up to 175. I am hoping it would be possible to raise the PL1/2 limits to 175 if not higher for more extreme overclocking?

**Comment by seerge** [comment]
@Sloreo1131 do you use latest version of the app and what model of the laptop do you have ?

**Comment by Sloreo1131** [comment]
I am using a Scar 16 G634JY (4090 13980hx) and am on version .148 of G Helper. Armory crate is also on its latest, PL1 can go to 140 while PL2 can go to 175.

**Comment by Sloreo1131** [comment]
Just got a popup for an update when opening  and it allows 175/175 now. Apologies if I was somehow on a previous version, had downloaded the latest about an hour before commenting. Thank you if it was a hotfix.

**Comment by seerge** [comment]
Great
