### ISSUE TITLE
Lid Bar

### ISSUE THREAD

**Issue by fadi9711** [seerge/g-helper#1943]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

V0.148 does not show the Led bar control in the extra tab on Rog Strix G15 (G513RM) 2022, While V0.146 was showing it.

### How to reproduce the bug?

1. extra
2. does not show LED bar control

### Logs

![Screenshot 2024-01-18 160019](https://github.com/seerge/g-helper/assets/68429224/05e81605-27ba-47de-9fa8-682dd08343ba)
![Screenshot 2024-01-18 160310](https://github.com/seerge/g-helper/assets/68429224/c4b86a63-0313-49da-ae5c-623d4076d80b)

### Device and Model

Rog Strix G15 (G513RM)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.148

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@fadi9711 hello, can you try this build ?
[GHelper.zip](https://github.com/seerge/g-helper/files/13979464/GHelper.zip)

**Comment by fadi9711** [comment]
@seerge Hello, I tried it now it is showing the led bar controller again.
Thank you

**Comment by seerge** [comment]
@fadi9711 great
