### ISSUE TITLE
GPU Mode bar disappeared

### ISSUE THREAD

**Issue by martin6982** [seerge/g-helper#1944]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

Hi seerge, I got 2 users said that their GPU Mode bar suddenly disappeared when they update to  v.147, and the issue still exist when they get back to v.146, I checked their models(FA507RC & GZ301ZE) and I'm sure their models support MUX Switch, and the dGPU & iGPU in the Device Manager is both normal.
As a side note, the z13 user reinstalled his win11 and the issue is solved, so I can't get his log file.

### How to reproduce the bug?

The GPU mode bar disappeared from the main page of the G-helper.
![FA507-1](https://github.com/seerge/g-helper/assets/130006105/eb65e40d-ec83-45fd-9da8-2fd7fc4ce847)
![FA507-2](https://github.com/seerge/g-helper/assets/130006105/be528aa0-078c-42eb-8d69-eca0fc61253e)
![z13](https://github.com/seerge/g-helper/assets/130006105/1dc7322f-b19d-44e8-9538-bca5feabcd42)

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13978627/log.txt)

### Device and Model

FA507RC & GZ301ZE

### Armoury Crate

Uninstalled

### Asus Services

1

### Version

0.147

### OS

Windows 11

**Comment by seerge** [comment]
@martin6982 hello 

Log is from FA507RC

```
2024/1/16 下午 03:01:23: App launched: ASUS TUF Gaming A15 FA507RC_FA507RC :0.145.0.0zh-TW
2024/1/16 下午 03:01:23: NVIDIA GeForce RTX 3050 Laptop GPU
2024/1/16 下午 03:01:24: CPU: 8 - AMD Ryzen 7 6800H with Radeon Graphics          - AMD64 Family 25 Model 68 Stepping 1
2024/1/16 下午 03:01:24: AutoSetting for Online
2024/1/16 下午 03:01:25: Input device not found
2024/1/16 下午 03:01:25: Mode = 0 : 0
2024/1/16 下午 03:01:25: VivoMode = 0 : 0
2024/1/16 下午 03:01:25: Eco flag : -65536
```

And from what i see here, not a single Asus command works (for reading or for setting modes). 
Most probably something has happened with their Asus System Control Interface driver, and it's simply off. It's not G-Helper's fault in a first place, but it can't do anything.

I would advice to uninstall and re-install this driver as explained in 
https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-asus-system-control-interface

And also try other troubleshooting methods if it doesn't help :) 

I'm closing this, as I can't help anyhow else.

**Comment by martin6982** [comment]
OK I got it, I will tell him how to solve this, thanks for your explanation. :)

**Comment by seerge** [comment]
It could be either windows update overwriting that driver, or they did it by themselves. Or just some hiccup :) But that should help.
