### ISSUE TITLE
Little makeup fix 

### ISSUE THREAD

**Issue by Kikimahe** [seerge/g-helper#1946]
Hello Seege,

Nothing too serious, but maybe you could do a little makeup fix on the white frame of this drop-down :)
(The text is gray but that's normal).

![01](https://github.com/seerge/g-helper/assets/142881210/a1f384f3-d318-430c-a4bb-ce3f22c1045a)

The frame turns white when :
- Laptop runs on battery
- Battery saver is enabled in Windows (1) and power plan drop-down disappears (2)

![02](https://github.com/seerge/g-helper/assets/142881210/e09917a2-ddf6-4210-a268-20c9bf3b853a)

Again, nothing too serious. If you don't do anything, I could still sleep.. :)

**Comment by seerge** [comment]
@Kikimahe hello, unfortunately I can't fix that cause this is how windows native dropdown behaves while being in disabled state (app intentionally sets it to disabled when detects battery saver mode in windows)

All those native elements are quite bad in terms of supporting dark theme, despite being actually microsoft's native :(

**Comment by Kikimahe** [comment]
Oh I understand.

thanks :)
