### ISSUE TITLE
Add ability to set rog button as Xbox guide button

### ISSUE THREAD

**Issue by AwsomeFox** [seerge/g-helper#1947]
**Is your feature request related to a problem? Please describe.**

When setting actions for the rog buttons on the rog ally I'd like to be able to set the buttons as the Xbox guide button like a regular controller. You can currently set things like print screen, open g helper etc. If you were able to set the action as Xbox guide button the ally built in controller could work like a normal Xbox controller. 

**Describe the solution you'd like**
Recent updates have added controller button overrides for most other controller buttons but the rog buttons aren't included. Either add the Xbox guide to the key bindings extra setting or add the rog buttons as configurable in controller settings. 

**Describe alternatives you've considered**
I tried entering key codes for keyboard shortcuts in the key bindings but there's not a keyboard shortcut that works like the guide button for Xbox/steam. 

**Additional context**
I figured since a bunch of other really nice features have been added for the ally I'd add a quick request for this.

**Comment by seerge** [comment]
@AwsomeFox did you check latest release 0.148? It's alreadypossible to create bindings for any button on Ally controller now, including XBox/steam

Keep in mind, bindings work only in Gamepad or in Auto mode (while in game)

https://github.com/seerge/g-helper/releases

**Comment by AwsomeFox** [comment]
@seerge thanks for the quick reply, I was hoping to be able to set the rog or ctr center buttons to be the Xbox guide. They're only editable in the key binding not controller settings. Seeing the controller config updates is what pushed me to make the issue.

Off topic but it would be nice to edit the controller buttons when in mouse mode too.
<img width="835" alt="Screenshot 2024-01-18 163553" src="https://github.com/seerge/g-helper/assets/37641191/a8c02444-3856-4134-a29b-b77e897eaed2">
<img width="707" alt="Screenshot 2024-01-18 163630" src="https://github.com/seerge/g-helper/assets/37641191/9999bf75-bcf1-4c05-ab60-e7890f5f925b">

**Comment by seerge** [comment]
@AwsomeFox hello,

Unfortunately that doesn't seem to be possible. You can't map them in AC as well for that reason.

All buttons except CtrlCenter/ROG are just part of a native "XBOX Controller" that Ally has inside. And all mappings that you see on that newly adding screen happen on hardware level. I.e. controller will just start emitting correct button when it's pressed.

G-Helper sets it in a same way AC does. 

And CtrlCenter/ROG  are separate, they work like M1-M4 buttons on laptops :) so G-Helper just gets notified when those buttons are pressed and can do some sofware action (like show itself, or switch profile, etc)
