### ISSUE TITLE
RGB settings seem to not work - Scar 18 2024

### ISSUE THREAD

**Issue by xSimone** [seerge/g-helper#1949]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

The Scar 18 RGB doesn't seem to work, it is stuck on a normal blue colour, but it is rainbow or whatever I want it to be during bios boot up.

The Dimming Zones toggle doesn't seem to be anywhere either for MiniLED displays, unless this is a hot key I do not know of yet.

### How to reproduce the bug?

Not sure how to reproduce this. Fresh install of Win11

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13984757/log.txt)

### Device and Model

Asus Scar 18 G834JZR

### Additional information.

NA

### Armoury Crate

Never installed

### Asus Services

Disabled

### Version

148

### OS

Latest to date 22631.3007

**Comment by xSimone** [comment]
Installed Garbagoury Crap(e) and the RGB works.

Going to now reinstall Windows until G-Helper works. :c

**Comment by seerge** [comment]
@xSimone most probably something has changed for 2024 models in RGB protocol or they have added a new device ID for keyboard :)

Can you check this build (and post a log) ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/13987994/GHelper.zip)

**Comment by seerge** [comment]
@xSimone oke, thanks. Can you try this build instead (again with a log)
[GHelper.zip](https://github.com/seerge/g-helper/files/13990401/GHelper.zip)

If it won't work as well, can you check if https://openrgb.org/ app is able to control backlight modes on your device by any chance?

**Comment by xSimone** [comment]
Oh I forget to mention yes 

G-Helper does allow me to make keyboard brightness go up and down, but not change the RGB itself

If I set a static, it sometimes changes to it when rebooting.

**Comment by xSimone** [comment]
[log.txt](https://github.com/seerge/g-helper/files/13990589/log.txt)

The RGB change the moment I log in,

Seems like G-Helper setting RGB for BIOS, I change it and it works in BIOS, but inside Windows itself it do not work.. ';x

**Comment by seerge** [comment]
@xSimone i see that you first started a new version (149), but then returned back to old 148. Are you sure that you don't have older app running ?

Also can you check if you have Asus Aura / Lightning services running under Windows -> Services apps ? (it's part of Armoury package, so G-Helper does't stop those services from it's ``Extra``)

P.S. RGB is not set in BIOS. It's set via USB in windows :)

**Comment by xSimone** [comment]
I'm do not know.. :'c

<img width="240" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/aef4396d-0175-4334-909a-bdd7e3cd0940">

I'm try to use G-Helper you are link.

**Comment by seerge** [comment]
@xSimone can you scroll down to letter L, i think there is also one called Lightning service :)

As for the version - just unzip it somewhere, where you don't forget, run (make sure it says 149), and try to switch backlight modes and drag backlight brightness slider under ``Extra`` :)

**Comment by xSimone** [comment]
No Lightning Service :c

**Comment by seerge** [comment]
@xSimone oke, can you open windows Task Manager and just search for Asus word in search bar? :)

**Comment by xSimone** [comment]
Still no change with 149, brightness move, timer work, but cannot set different RGB lighting setting. :c

**Comment by xSimone** [comment]
<img width="456" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/fdfeb4fb-b3b6-4816-9848-de6c6255e054">

**Comment by seerge** [comment]
@xSimone oke! You are clean! :) 

Can you download https://openrgb.org/ and check if it's able to set modes?

**Comment by xSimone** [comment]
Yes I do and do not work. :c

**Comment by seerge** [comment]
@xSimone oke. Thanks

Then last resort would be actually check what Armoury Crate sends to keyboard (but it's a bit difficult)

1. You will have to install USB Device Monitoring Studio
https://www.hhdsoftware.com/device-monitoring-studio
2. Install Armoury Crate (again)
3. Then launch Device Monitoring, pick Asus device form the list, and start recording what is being sent to it.
4. Open Armoury and try to set some modes (like Static or Rainbow) 
5. Check what Armoury sends to keyboard, and post it here

**Comment by xSimone** [comment]
Aw :'c

**Comment by seerge** [comment]
@xSimone I actually have one more idea to test, before you do that

Check this build (and post a log again)

[GHelper.zip](https://github.com/seerge/g-helper/files/13990895/GHelper.zip)

**Comment by xSimone** [comment]
[log.txt](https://github.com/seerge/g-helper/files/13990913/log.txt)

**Comment by xSimone** [comment]
<img width="410" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/5d3fb51c-4a18-4999-b317-02928dd3bf01">

I think up to here my RGB came back. I didn't have the USB thingy running though.

**Comment by seerge** [comment]
@xSimone can you try if G-Helper is able to change RGB now ? after it came back ?

**Comment by xSimone** [comment]
Trying to change in Garbageoury Crate just makes the keyboard flicker once, then do nothing. It is stuck on rainbow. ':<

**Comment by xSimone** [comment]
I'm guess I need update BIOS? :f

**Comment by seerge** [comment]
@xSimone did you try if G-Helper is able to switch something now ?

Backlight settings are not stored in BIOS :) Did it work out of the box ?

**Comment by xSimone** [comment]
I'm do not know, because I'm just fresh install moment I receive Laptop. :c 

G-Helper do not change anything now.. I will try use USB scan.

**Comment by seerge** [comment]
@xSimone USB won't help you. If you can't set color in Armoury.

Just enable all asus services (via G-Helper's ``Extra``), restart, make sure all Asus stuff (including Armoury's own services) run in Services, and try to set backlight modes there

**Comment by xSimone** [comment]
After reboot G-Helper now work, and Garbageoury Crate

**Comment by seerge** [comment]
@xSimone ok, so G-Helper is also able to change modes?!

**Comment by xSimone** [comment]
Yes, but must install Garbageoury Crate first. :c

**Comment by xSimone** [comment]
[log.txt](https://github.com/seerge/g-helper/files/13991051/log.txt)

**Comment by seerge** [comment]
@xSimone then it means, it's just missing some wake up command from AC.

Can you

1. Stop services from ``Extra``
2. Manually stop / disable all remaining Asus services under Windows -> Services app
3. Restart your laptop (so you have a fresh start with no Armoury stuff running)
4. Check if G-Helper still works ?

**Comment by xSimone** [comment]
<img width="318" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/38af8c19-5474-42f8-acaa-4985e7e22b0c">

This?

**Comment by seerge** [comment]
@xSimone this, and everything starting with Asus / Armoury

**Comment by xSimone** [comment]
<img width="305" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/818782f9-0cb1-4308-b010-4c7cffb0be4d">
<img width="341" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/32b9e3df-21ee-4e74-828d-81d4e8cad4f3">

All this?

**Comment by seerge** [comment]
@xSimone yes, stop ArmouryCrateServce as well, reboot and check if G-Helper can set RGB

**Comment by xSimone** [comment]
It can set.. it reverted back to rainbow but I set again and it seem to stay.
[log.txt](https://github.com/seerge/g-helper/files/13991125/log.txt)

**Comment by xSimone** [comment]
I must sleep, I try later. :c

**Comment by seerge** [comment]
@xSimone that's strange :) (assuming that Armoury is disabled)

Try to shut down laptop (not reboot) and try again on fresh start. If RGB won't work - it was missing some wake up command

I have added one in this build
[GHelper.zip](https://github.com/seerge/g-helper/files/13992331/GHelper.zip)

**Comment by xSimone** [comment]
Humm, I think it is now worse. RGB turned off :c

**Comment by seerge** [comment]
@xSimone I can't read your thoughts :)

What does off mean ? You can't change brightness ? You can't set RGB modes?

**Comment by seerge** [comment]
P.S. Based on last logs you have posted, you don't seem to use the right build that I have linked here. It still says 0.148 there.

**Comment by xSimone** [comment]
I am using 149 at the moment.

What I said before was the RGB turned off, as in, it wasn't working at all. I rebooted however and it is back to static blue, as usual.

I also updated my BIOS to 312, up from 306, but it did not do anything to help.

**Comment by xSimone** [comment]
G-Helper can still turn brightness up and down, turn off parts of RGB like keyboard, lid, lightbar etc.

Still cannot change colours, still stuck on static blue.

[log.txt](https://github.com/seerge/g-helper/files/13996056/log.txt)

**Comment by KillerSnake89** [comment]
I can confirm this as well. That the strix scar 16 2024 model. I can change the rgb setting. My keyboard and all other rgb lights are blue.

**Comment by seerge** [comment]
@xSimone so even the latest build I have linked, is able to set RGB mode, as soon as you start Armoury Crate service ?

**Comment by xSimone** [comment]
I think so? Actually, I think G-Helper didn't change still, but Armoury Crate could.

I cannot test as I reinstalled Windows again, I hate Armoury Crate. HATE. :f

**Comment by xSimone** [comment]
> I can confirm this as well with the strix scar 16 2024 model. I can't change the rgb setting. My keyboard and all other rgb lights stay blue even when trying to change other colors.

But when you reboot, it changes yes? But then goes back to solid blue when you login?

**Comment by seerge** [comment]
@xSimone well, it's confusing, cause before you told opposite
> After reboot G-Helper now work, and Garbageoury Crate is still broken

Cause if you could change RGB with G-Helper's mode dropdown, it means that command itself is absolutely correct. And it's only some kind of extra initialization is missing (that AC does on start)

Write your discord ID, i will message you tomorrow (it's 2am here)

**Comment by xSimone** [comment]
Add Blue_Lady

**Comment by xSimone** [comment]
> @xSimone well, it's confusing, cause before you told opposite
> 
> > After reboot G-Helper now work, and Garbageoury Crate is still broken
> 
> Cause if you could change RGB with G-Helper's mode dropdown, it means that command itself is absolutely correct. And it's only some kind of extra initialization is missing (that AC does on start)
> 
> Write your discord ID, i will message you tomorrow (it's 2am here)

Oh, oops. I must have got mixed up then, G-Helper was maybe working then, because of some driver during install I think I sent picture of the stage

**Comment by xSimone** [comment]
Not sure why but the colour changed again. I left 'Solid Colour' to a different colour and without me noticing it, it has changed. ':<

**Comment by seerge** [comment]
@xSimone it doesn't change by itself. But when you select new mode in the dropdown or press hotkey 

```
20/01/2024 2:22:30 PM: AuraMode: AuraRainbow
20/01/2024 2:22:30 PM: USB 19B6: 5D-B3-00-03-FF-00-00-E1-00-00-FF-FF-FF-00-00-00-00
20/01/2024 2:22:30 PM: USB 19B6: 5D-B4
20/01/2024 2:22:30 PM: USB 19B6: 5D-B5-00-00-00
```

That's last one in your log.

If changes doesn't work for you now. Can you try to start Armoury Crate service again and see if after that **G-Helper** (not Armoury) is able to change all aura modes ?

**Comment by xSimone** [comment]
I DO THIS INSTEAD!

**Comment by xSimone** [comment]
Okay, I will try this later, I must find spare SSD to use instead for testing. Hopefully can share within 24 hour

**Comment by xSimone** [comment]
G-Helper works from stock install Scar 18 2024

[log.txt](https://github.com/seerge/g-helper/files/13998141/log.txt)

**Comment by seerge** [comment]
@xSimone what is "stock install" ? Is it with Armoury Crate running? So by changing any RGB mode inside G-Helper it immediately works ? (including color changes for Static mode)

**Comment by xSimone** [comment]
Stock Install is Operating System that come with machine, not fresh install of Windows.

Armoury Crate running, updating it now and will send new log.

G-Helper and all RGB related thing is working, Yes.

**Comment by xSimone** [comment]
[log.txt](https://github.com/seerge/g-helper/files/13998310/log.txt)

**Comment by seerge** [comment]
@xSimone thanks. Now we need to figure out what exactly Armoury sends to keyboard.

Can you please do following

Install https://www.hhdsoftware.com/device-monitoring-studio (will require reboot)

1. In Windows Services app - STOP ``Armoury Crate Service`` (don't disable it, just stop)\
2. Launch Monitoring Studio, pick AsusTek device from the list and double click on it
![Screenshot 2024-01-20 163125](https://github.com/seerge/g-helper/assets/5920850/e9a28802-08cb-423c-812b-7b526b051a5f)
3. Add ``Packet View`` to Procesing and click ``Start``
![Screenshot 2024-01-20 163136](https://github.com/seerge/g-helper/assets/5920850/354340f0-2fcb-473b-a49f-2e01b25d00a9)
4. START ``Armoury Crate Service`` from Windows Services (i assume your keyboard will change color to whatever was set in Armoury)
5. In Monitoring Studio select ``Tools`` -> ``Save to Log``, and save data

Upload this data here.

**Comment by xSimone** [comment]
<img width="362" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/ea892b50-7988-4da2-92e1-870a5d44b30f">

 Humm.. this is problem.. :<

**Comment by seerge** [comment]
@xSimone you need to reboot after installing Monitoring Studio

**Comment by seerge** [comment]
@xSimone also check if N-Key device says Asus in properties, it could be that as well

**Comment by xSimone** [comment]
It says Microsoft, but it also say USB, maybe it is apart of keyboard? :<

**Comment by xSimone** [comment]
[z.txt](https://github.com/seerge/g-helper/files/13998452/z.txt)

Well, it did something from Stupid Crate!

**Comment by seerge** [comment]
@xSimone no, it has to be Asus device. It's there cause both AC and G-Helper communicate with it over USB
![Screenshot 2024-01-20 170047](https://github.com/seerge/g-helper/assets/5920850/27a15d9e-a74b-42eb-9392-c3a1345f91e2)

**Comment by xSimone** [comment]
I do not have anything I think that is Asus :'c

**Comment by seerge** [comment]
> [z.txt](https://github.com/seerge/g-helper/files/13998452/z.txt)
> Well, it did something from Stupid Crate!

There is no data inside your fire, please follow my guide carefully :)

**Comment by xSimone** [comment]
Discord?

**Comment by seerge** [comment]
@xSimone Did you reboot before starting Monitoring Studio? Then go through all Human Interface Devices and look for one from Asus

**Comment by seerge** [comment]
May be @IceStormNG knows why there is no Asus devices there, he was using this app a lot as I remember :)

**Comment by xSimone** [comment]
Yes, I reboot two time :'c 
Maybe I must turn off FastBoot

**Comment by IceStormNG** [comment]
Please open USBTreeViewer and check what devices are there. Maybe post a screenshot with all trees expanded. I have a bad feeling they (ASUS) are screwing with us here.

**Comment by xSimone** [comment]
<img width="248" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/f64012a6-8d4e-460c-88a3-0de73e61b1f9">


Is this? :<

**Comment by xSimone** [comment]
Anyone Discord? I share? Or TeamViewer? :c

**Comment by IceStormNG** [comment]
Nope. I meant the tool USBTreeView https://www.uwe-sieber.de/usbtreeview_e.html

**Comment by xSimone** [comment]
<img width="426" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/2eab7976-8624-4a11-a2ed-2231f9c264be">
<img width="430" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/88254884-b399-4690-a427-44277086593f">

**Comment by IceStormNG** [comment]
From what I see here, I would say the device on Port3 is what could be our target. @seerge

**Comment by xSimone** [comment]
':x!

**Comment by seerge** [comment]
@IceStormNG @xSimone ye, but it's not visible in device monitoring studio

**Comment by xSimone** [comment]
<img width="566" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/3d7d900a-5026-4176-8db8-8063f080c9d8">

This is not help? :'c

**Comment by seerge** [comment]
@xSimone you need to export it and upload here 
> In Monitoring Studio select Tools -> Save to Log, and save data

**Comment by xSimone** [comment]
Oh, my text file is bad? I try again.

**Comment by IceStormNG** [comment]
> @IceStormNG @xSimone ye, but it's not visible in device monitoring studio

This can happen because The packet logger did not install the filter driver for those hubs. Either due to a system policy or a device that refused to unload during install.

**Comment by IceStormNG** [comment]
I guess it is the "USB Composite device" in the packet logger. You could verify that by checking the PID in treeviewer and the packet logger.

**Comment by xSimone** [comment]
[dsd.txt](https://github.com/seerge/g-helper/files/13998605/dsd.txt)

**Comment by seerge** [comment]
@xSimone I'm sorry, but I won't be able to help anyhow, if I don't have any data of what AC sends. 

File without any data  doesn't help, you need to save it as DMS log as explained.

Thanks.

**Comment by xSimone** [comment]
Can you screenshot button?

**Comment by xSimone** [comment]
<img width="731" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/f5d373f0-df1a-4223-9e69-3bdaa95ad3a6">

Or circle which one?

**Comment by seerge** [comment]
@xSimone it was in original message with the guide
![Screenshot 2024-01-20 163247](https://github.com/seerge/g-helper/assets/5920850/a6f5c8fc-c04a-4eb1-a435-a86a320a0b9c)

**Comment by xSimone** [comment]
https://file.io/AdUw1qjVOrbf

Oop, I fix!

**Comment by xSimone** [comment]
Is there anything else you are need, just want to give as much information before switch SSD :<

**Comment by seerge** [comment]
@xSimone oke, thanks. That one seem to be correct one.

Now, can you STOP and DISABLE ``Armoury Crate`` and ``Lightning`` services under Windows Services, and then shut down and start laptop again (not reboot preferrably)

And try if this build is able to switch RGB
[GHelper.zip](https://github.com/seerge/g-helper/files/13998636/GHelper.zip)

**Comment by xSimone** [comment]
Hmm, how to disable? Shutdown and Boot just make them start again

**Comment by seerge** [comment]
@xSimone double-click on service and select Startup Type = Disabled

**Comment by xSimone** [comment]
Oop, I was doing from Task Manager. I do from Services now. ';d

**Comment by xSimone** [comment]
Cannot find Lighting Service...

**Comment by seerge** [comment]
@xSimone it could be Asus Lightning or something. If you can't find it - shutdown and start as is. As far as Armoury Crate Service is stopped.

**Comment by xSimone** [comment]
<img width="180" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/0c3ea688-09d3-4bb6-add9-67144b09addb">

This one?

**Comment by seerge** [comment]
@xSimone yes

**Comment by xSimone** [comment]
I disable all 
I do NOT upgrade G-Helper
G-Helper can still change RGB colour

**Comment by seerge** [comment]
@xSimone did you shut down laptop or restart ? you need to shut down. And then start again. I think it resets keyboard.

**Comment by seerge** [comment]
@xSimone Anyway, you can now safely uninstall AC using it's own uninstaller, and stop all remaining services using G-Helper for a cleaner testing.

**Comment by xSimone** [comment]
I shut down. I turn off Fast Boot though.

I will try that though yes.

Can you link me correct uninstaller?

**Comment by seerge** [comment]
@xSimone https://dlcdnets.asus.com/pub/ASUS/mb/14Utilities/Armoury_Crate_Uninstall_Tool.zip?model=armoury%20crate

**Comment by xSimone** [comment]
Hmm, G-Helper still works without update.

**Comment by seerge** [comment]
@xSimone cause your keyboard is probably "woken up" by AC still. I don't know when it will stop working :) could be either after sleep or long shutdown

**Comment by xSimone** [comment]
yes sadly do not work.. but I must sleep now :c 

We try again later! :3

**Comment by xSimone** [comment]
Ready to test! :x

**Comment by seerge** [comment]
@xSimone I have copied pretty much all possible data to G-Helper, that AC sends to keyboard prior to setting actual RGB modes. 

Can you try this build, and post a log?

[GHelper.zip](https://github.com/seerge/g-helper/files/14001101/GHelper.zip)

**Comment by xSimone** [comment]
https://github.com/seerge/g-helper/assets/16178961/aa2e5145-439c-436b-ad1c-bc1a3a32a5ab

[log.txt](https://github.com/seerge/g-helper/files/14001512/log.txt)

**Comment by seerge** [comment]
@xSimone hello, does it mean it works now? that's good news and congratulations :)

Problem is that app now sends a lot of random data (copied from AC), that I have no idea what it does.

And since your keyboard is "awake" now with that commands, even old G-Helper will work,

Try this build , but use it extensively (like try to shut down laptop completely, or whatever you did last time to make it stop working)
[GHelper.zip](https://github.com/seerge/g-helper/files/14001581/GHelper.zip)

I have trimmed init commands only to 2 (that I suspect to be correct).
If it will keep working no matter what -  my guess was correct, if not - we will need another shot

**Comment by xSimone** [comment]
[log.txt](https://github.com/seerge/g-helper/files/14003331/log.txt)

Bork again. :c 

It is weird, something keeps forcing RGB back to some weird setting that sticks somewhere.

My static blue is now light brown. I set it to this a week ago and it just do not want to change. Even in last version, it goes to it before login.

**Comment by seerge** [comment]
@xSimone does rebooting and using a version with all possible AC commands help to resurrect it ?

> @xSimone I have copied pretty much all possible data to G-Helper, that AC sends to keyboard prior to setting actual RGB modes (based on your recording)
>Can you try this build, and post a log?
> [GHelper.zip](https://github.com/seerge/g-helper/files/14001101/GHelper.zip)

**Comment by xSimone** [comment]
I do not even need to reboot to make it work.

I changed it to green and pink while testing a while back, a version must have made solid colour change then it broke.

**Comment by seerge** [comment]
@xSimone 
> I do not even need to reboot to make it work.

I have to admit, it's extremely difficult to understand you sometimes. So it works or it doesnt?

**Comment by xSimone** [comment]
Yes. It work. I am sorry. :c

**Comment by seerge** [comment]
@xSimone what does 
>Bork again. :c
stands for ?

**Comment by xSimone** [comment]
OH! It broke again. New version do not work.

**Comment by xSimone** [comment]
The 'working version' of 149.1 seems to eventually stop working and reverts to static brown.

**Comment by seerge** [comment]
@xSimone oke, can you try this build instead ?

And let me know if stops working 

[GHelper.zip](https://github.com/seerge/g-helper/files/14008161/GHelper.zip)

**Comment by xSimone** [comment]
I will test first one, then new one, and share both log within a few day of use. 

I think the first working one accidentally kept being overridden by a different installation of G-Helper, but I am unsure. Will confirm soon!

Did you get gift? :3

**Comment by xSimone** [comment]
[log.txt](https://github.com/seerge/g-helper/files/14018270/log.txt)

Seems to revert back to solid brown despite the solid settings being different. Strange setting somewhere is preserving itself.

Trying new version now. :3

**Comment by xSimone** [comment]
New version is worse. Do not work. :c

Back to original issue, only brightness works, turning zones off and on while cannot change colours.

[log.txt](https://github.com/seerge/g-helper/files/14018301/log.txt)

**Comment by xSimone** [comment]
Stupid phone. Cannot edit post. Wanted to say reverted to solid brown after waking from sleep.

**Comment by seerge** [comment]
@xSimone so`` 0.141.1`` works, and ``0.141.2`` doesn't? 

Try this build then. It will send all data again, but I have limited it only to your and similar devices (i.e. Strix 2024)

[GHelper.zip](https://github.com/seerge/g-helper/files/14022038/GHelper.zip)

**Comment by xSimone** [comment]
[log.txt](https://github.com/seerge/g-helper/files/14023026/log.txt)

Works during Boot / Bios

Turns to brown in login screen still.

Works when logged in.

Rebooted, still works.

Will continue to use and see if it reverts to brown after some time. :3

**Comment by seerge** [comment]
@xSimone if it works after login (i.e. when G-Helper starts), it means everything is good.

I don't know why it reverts sometimes, but it's clearly not G-Helper doing that. It could be something else.

Do you have Dynamic Lightning in windows turned ON ? it could be that windows itself now can interfere and override

![Screenshot 2024-01-23 124719](https://github.com/seerge/g-helper/assets/5920850/2519604c-6bb2-4761-b316-251ed8e8c6cb)

**Comment by xSimone** [comment]
LOOOOOOOOOOOL

Yes it was this thanks you. :3

**Comment by xSimone** [comment]
Question, I notice Dynamic Lighting have a greater range of brightness toggle.

Can G-Helper take advantage of this, instead of.. Off, 1, 2, 3 

:x?

**Comment by seerge** [comment]
@xSimone but does it actually work (i.e. does it become brighter)? in asus settings there are only 4 levels

**Comment by xSimone** [comment]
Yes it does, it almost seems like it has 10+ or more levels.

**Comment by seerge** [comment]
@xSimone can you make a picture of same static color (for example red) with max brightness in G-Helper and using windows itself ?

**Comment by seerge** [comment]
@xSimone you don't seem to get my question, can you compare max level in windows and g-helper with 2 photos ? based on the video it still seem to have something like 4 real-life brightness levels.

**Comment by xSimone** [comment]
Sorry I make this video before Question.

**Comment by xSimone** [comment]
Brightness is same.

**Comment by seerge** [comment]
@xSimone then it's nothing to tweak :)

**Comment by xSimone** [comment]
At highest brightness yes.

**Comment by xSimone** [comment]
https://github.com/seerge/g-helper/assets/16178961/21664f2f-ba7f-4b4b-9aae-85e850768c86

You can see flicker between two. Max brightness.

**Comment by xSimone** [comment]
https://github.com/seerge/g-helper/assets/16178961/0f510147-cf63-43aa-9fe9-24ff81671eba

But can go much lower with Windows version than G-Helper, you can see here.

**Comment by xSimone** [comment]
Ah so it fake? It do not actually tune brightness, just makes colour darker and seem it is becoming less bright? :c

**Comment by xSimone** [comment]
Is it possible for G-Helper to do something similar? Sometimes lowest brightness still too bright. :<

**Comment by xSimone** [comment]
https://github.com/seerge/g-helper/assets/16178961/82cfd6bc-09f9-4c47-940d-f207f800e937

**Comment by seerge** [comment]
@xSimone i have already tried to do something like that for ROG Ally, and it actually causes some mismatches. I may consider that somewhere on the later stage.

**Comment by xSimone** [comment]
Okay! So much love, thank you for this fix!! <3 

Love love love. :3

**Comment by xSimone** [comment]
[log.txt](https://github.com/seerge/g-helper/files/14024592/log.txt)

**Comment by xSimone** [comment]
... I confirm, RGB is work with 148.. it was just because of stupid Windows Dynamic Lighting be on.. :'c

Sorry Seerge..

Maybe make new build with only MiniLED button fix for cleaner code?

**Comment by xSimone** [comment]
After lot of testing, it seem that it is still the same and works. Only reason was because Dynamic Lighting is on..

But on 2023 edition, Dynamic Lighting was also on but G-Helper works fine.

Do not know what the difference is between 2023 and 2024 to make Dynamic Lighting ruin G-Helper.

**Comment by seerge** [comment]
@xSimone oke, thanks for confirming :) I will keep it in mind, and if more people will encounter this problem - will add this to FAQ

**Comment by xSimone** [comment]
https://www.youtube.com/live/FKC8uF-S0xs?si=YrWF-EWiwtkaId7o&t=3830

https://www.youtube.com/watch?v=nqSZXB-Jruo

You can see in these two videos it turns Blue after login. 

Do not know why mine was brown, I must have change the settings in Dynamic Lighting one day when I was setting up Windows and did not notice.

**Comment by seerge** [comment]
@xSimone it's funny to see that, despite AC actually literally SPAMS keyboard with RGB packets all the time (G-Helper doesn't). And windows still manages to take over :)

**Comment by xSimone** [comment]
Yes. :f But it is confusing why this does not happen on 2023 edition with Dynamic Lighting on? Only 2024 one! Must be new method of sending messages to RGB controller? :<

Scary.. ':x

Thank you for adding to FAQ! Hope all others will see this! <3

**Comment by seerge** [comment]
@xSimone because Microsoft has broken dynamic lightning implementation. It simply does nothing for 2023 models apparently, it also exists but has no effect on my G14 2022.

**Comment by xSimone** [comment]
HA! I do not check to see if it actually WORK on 2023, maybe you are right! 

So stupid, but make sense. ';d

I will check next time and tell you for fun if it work next time I am with the 2023 edition.
