### ISSUE TITLE
System Freezes When Silent Mode is Enabled

### ISSUE THREAD

**Issue by SudoAra** [seerge/g-helper#1950]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

On an Asus ROG Zephyrus G14 (GA401QM) laptop, whenever the silent mode is activated the system will freeze and will not recover until a hard reboot is carried out.

### How to reproduce the bug?

The bug occurs anytime the Silent mode is activated, either right away or after a few minutes of use.

This happens also after rebooting if the power mode is kept to silent mode.

Additional context:

- The laptop can be either plugged or on battery.
- Any other combination of settings in the G-Helper app do not change the outcome.

<img width="302" alt="ga401qm_win11_silent" src="https://github.com/seerge/g-helper/assets/4848984/0e5c40ea-6e17-4bab-9259-6fee36d525bd">

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13986241/log.txt)

### Device and Model

Asus Zephyrus G14 GA401QM

### Additional information.

Laptop and system characteristics:

* A full clean install of Windows 11 Pro has been carried out, but this did not fix the issue.
* Latest drivers where also applied as part of the process.
* All the troubleshooting steps from the wiki have also been performed, unfortunately without fixing the issue too.
* The laptop was fully dusted and had both its battery and thermal paste replaced a couple of months ago (the issue just came up a few days ago though so this is probably unrelated).
* Probably this is the normal behaviour when in silent mode, but when this mode is active and the G-Helper app is launched the following line is shown in the logs:

```plaintext
19/01/2024 16:04:47: dGPU not found
```

<img width="383" alt="ga401qm_win11_extra_settings" src="https://github.com/seerge/g-helper/assets/4848984/f70695cd-1bf4-41b3-aed4-a023deb17429">
<img width="485" alt="ga401qm_win11_updates" src="https://github.com/seerge/g-helper/assets/4848984/e4dd2951-3088-4796-8a7c-53ad165eeae5">

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.148.0

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@SudoAra hello, 

I see that you have asus services running in background, can you stop them ?
```
18/01/2024 21:38:14: Optimization service is running
```

Also, are you sure that you don't mix Silent mode and Eco ? (or Optimized when unplugged)? Try to set Standard.

**Comment by seerge** [comment]
@SudoAra 
P.S. I have tried to look at the log further, I see few times last record before you restart app is

```
19/01/2024 14:45:31: Mode = 2 : OK
19/01/2024 14:45:31: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
```

This is app setting windows own power mode to "Best Power efficiency"
![Screenshot 2024-01-19 124322](https://github.com/seerge/g-helper/assets/5920850/1fdeff96-0c4f-4495-8379-724d4d47fcf0)


Can you try to go into window settings and change that setting manually back and forwards, if your system behaves ok with the changes ?

**Comment by SudoAra** [comment]
Hi,

Thanks so much for looking into this so quickly.

> **_I see that you have asus services running in background, can you stop them ?_**
> 
> Yeah sorry, I had them on but stopped them afterwards.

> **_Also, are you sure that you don't mix Silent mode and Eco ? (or Optimized when unplugged)? Try to set Standard._**
> 
> Tried this, it still freezes when in silent mode and GPU mode set to standard.

> **_Can you try to go into window settings and change that setting manually back and forwards, if your system behaves ok with the changes ?_**
> 
> This did it, setting it manually to "Best power efficiency" also freezed the system. I guess this means is something to do with Windows itself (maybe a hardware issue?) and not the app.

Sorry to bother you with this then, please feel free to close this ticket. Still, if you have any guesses as to what could be causing this please feel free to share them, feeling quite mad about it at the moment :) 

Thanks a lot!

**Comment by seerge** [comment]
@SudoAra Yes, it means something is with the system or hardware. I have no idea what.

You can try steps from https://github.com/seerge/g-helper/wiki/Troubleshooting

For now you can just set ``Windows Power Mode`` under ``Fans + Power`` to ``Balanced`` or above (even for Silent mode), so app won't switch that at least.

Good luck

**Comment by Ramz993** [comment]
> ### Rules
> 
>     * [x]  I made myself familiar with the [Readme](https://github.com/seerge/g-helper?tab=readme-ov-file), [FAQ](https://github.com/seerge/g-helper/wiki/FAQ) and [Troubleshooting](https://github.com/seerge/g-helper/wiki/Troubleshooting).
> 
>     * [x]  I understand that, if insufficient information was provided, my issue will be closed without an answer.
> 
> 
> ### What's wrong?
> 
> On an Asus ROG Zephyrus G14 (GA401QM) laptop, whenever the silent mode is activated the system will freeze and will not recover until a hard reboot is carried out.
> ### How to reproduce the bug?
> 
> The bug occurs anytime the Silent mode is activated, either right away or after a few minutes of use.
> 
> This happens also after rebooting if the power mode is kept to silent mode.
> 
> Additional context:
> 
>     * The laptop can be either plugged or on battery.
> 
>     * Any other combination of settings in the G-Helper app do not change the outcome.
> 
> 
> <img alt="ga401qm_win11_silent" width="302" src="https://private-user-images.githubusercontent.com/4848984/298001688-0e5c40ea-6e17-4bab-9259-6fee36d525bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MDYzMzUsIm5iZiI6MTcyMjcwNjAzNSwicGF0aCI6Ii80ODQ4OTg0LzI5ODAwMTY4OC0wZTVjNDBlYS02ZTE3LTRiYWItOTI1OS02ZmVlMzZkNTI1YmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDNUMTcyNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2JkYWRhMDE1OTQ0M2E4Y2JmMzIxYTE5MGU3OWI4MTcwZTg5ODQ5MzVmYzQ1MGM3NWY3NjBmYTFhNjdiODIyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Yexsyzj9Vk4hwvlOGRxnbDJ8QKQFzr4FMuFG1AShFMM">
> ### Logs
> 
> [log.txt](https://github.com/seerge/g-helper/files/13986241/log.txt)
> ### Device and Model
> 
> Asus Zephyrus G14 GA401QM
> ### Additional information.
> 
> Laptop and system characteristics:
> 
>     * A full clean install of Windows 11 Pro has been carried out, but this did not fix the issue.
> 
>     * Latest drivers where also applied as part of the process.
> 
>     * All the troubleshooting steps from the wiki have also been performed, unfortunately without fixing the issue too.
> 
>     * The laptop was fully dusted and had both its battery and thermal paste replaced a couple of months ago (the issue just came up a few days ago though so this is probably unrelated).
> 
>     * Probably this is the normal behaviour when in silent mode, but when this mode is active and the G-Helper app is launched the following line is shown in the logs:
> 
> 
> ```
> 19/01/2024 16:04:47: dGPU not found
> ```
> 
> <img alt="ga401qm_win11_extra_settings" width="383" src="https://private-user-images.githubusercontent.com/4848984/298001598-f70695cd-1bf4-41b3-aed4-a023deb17429.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MDYzMzUsIm5iZiI6MTcyMjcwNjAzNSwicGF0aCI6Ii80ODQ4OTg0LzI5ODAwMTU5OC1mNzA2OTVjZC0xYmY0LTQxYjMtYWVkNC1hMDIzZGViMTc0MjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDNUMTcyNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjMwZTExNGI4YTJmNjY4MjIxYjhlN2Y5MjAxNWRjMjc4NTgxNzJhNWM3OGM1OThkYTA1ZGQwNTIzMTI2NmI1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HGdPgXeQJPIGpsUwqk7AtWPTSmdOdf1HRVTqyYIkpk8"> <img alt="ga401qm_win11_updates" width="485" src="https://private-user-images.githubusercontent.com/4848984/298001612-e4dd2951-3088-4796-8a7c-53ad165eeae5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MDYzMzUsIm5iZiI6MTcyMjcwNjAzNSwicGF0aCI6Ii80ODQ4OTg0LzI5ODAwMTYxMi1lNGRkMjk1MS0zMDg4LTQ3OTYtOGE3Yy01M2FkMTY1ZWVhZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDNUMTcyNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTIzM2YxNWNlMTBkODQyOTJlMDAyZDg4NjU4MzBiNjc3ZWZjOWY5ZjI4OWVkMjlhMjcwMjM3MzQwNWVjNzc1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z9Hd7xpIDLpiGQBLR5HYTjHWnZD10V_Da0BrRXd15IU">
> ### Armoury Crate
> 
> Uninstalled
> ### Asus Services
> 
> None
> ### Version
> 
> 0.148.0
> ### OS
> 
> Windows 11 Pro 23H2



Hey, i have the same problem as you do. did already figure it out how to fix the problem?
