### ISSUE TITLE
[Feature Request] Disable option for gamepad control

### ISSUE THREAD

**Issue by codevski** [seerge/g-helper#1951]
**Is your feature request related to a problem? Please describe.**
Add a 4th option Disable along with (Gamepad | Mouse | Auto). At the moment for the Rog Ally users that use alternative input management completely overrides them. It even messes up with steam big picture right joystick is always a mouse and steam treats the controller as a mouse / keyboard

**Describe the solution you'd like**
Just add a disable / dont use the new input system you guys added

**Comment by seerge** [comment]
@codevski hello,

Generally speaking "Gamepad" mode will just leave controller in it's default state (i.e. acting as XBox controller). So if you use any 3rd party apps to emulate input on software level (like Steam Input), they should keep working as they were before.

The only difference would be that on launch G-Helper would send init command to the controller, actually setting it to it's default Gamepad mode still. For my testing it doesn't cause any interference.

However if really needed I have added a 4th state called "Skip".  Then app won't send any controller initialization commands at all.

You can try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/13990499/GHelper.zip)

P.S. As far as I understand this is also your comment  ?https://www.reddit.com/r/ZephyrusG14/comments/14lvzhn/comment/kil2ref/

**Comment by codevski** [comment]
I apologize for the language used I have edited the post and I will test out this build now and report thanks.

**Comment by seerge** [comment]
I still didn't get how exactly Gamepad mode affects Steam, as it literally doesn't change default controller behavior

**Comment by codevski** [comment]
> I still didn't get how exactly Gamepad mode affects Steam, as it literally doesn't change default controller behavior

It seems like it was overriding key binds for example in HC I've set guided button to be mapped to button (some Button) . For what ever reason having ghelper set to gamepad mode overrides the guide button. Usually relaunching HC fixes it (which ever is open last takes priority) and in auto mode it always acts as a mouse in steam regardless what option you set as steam input.

 I could potentially supply any logs if there are any for seeing what's going on.

**Comment by seerge** [comment]
That's not necessary, I just double checked Steam works absolutely fine in Gamepad mode, and sees controller as gamepad.
Furthermore big picture mode triggers Auto to gamepad setting as well

As for HC, it also overrides G-Helper's power profiles (HC literally uses G-Helper's code inside for that). So I have no idea why you use 2 apps that do 2 things.

Closing this.
