### ISSUE TITLE
[G513QY] GPU Mode not show up , always "stop GPU Applications"

### ISSUE THREAD

**Issue by kalimaenergy** [seerge/g-helper#1953]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

Hello,
[G513QY] GPU Mode not show up , always "stop GPU Applications", I don't know i can select more options, when i click on stop... nothing happens.

Thank you
![Capture d'écran 2024-01-19 205835](https://github.com/seerge/g-helper/assets/62940623/7f7a112b-7539-4b11-a901-e0282a7c919f)

### How to reproduce the bug?

Install 0.148 on G513QY and windows 11 23H2 and driver 23.12.1

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13993981/log.txt)

### Device and Model

Asus ROG Strix G513QY (G15 Advantage Edition)

### Additional information.

BIOS 331
Driver 23.12.1 (DDU Done before installation)

### Armoury Crate

Never installed

### Asus Services

1

### Version

0.148

### OS

Windows 11 23H2

**Comment by seerge** [comment]
You clearly didn't read FAQ
https://github.com/seerge/g-helper/wiki/FAQ#i-dont-see-gpu-modes-section
