### ISSUE TITLE
G834JYR - new 2024 18 inch SCAR with 4090 - Top keys (volume down, up etc) not working

### ISSUE THREAD

**Issue by sebastiaanvandingenen** [seerge/g-helper#1954]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

The top 5 keys are not working:
- Volume Down
- Volume Up
- Mute
- Performance Mode
- Armoury Crate (i assume this will just not work since this is uninstalled, maybe it should open g-helper?)
-

### How to reproduce the bug?

On a brand new strix 18 uninstall armoury crate, restart, install g-helper and try htiting the 5 keys on top of the keyboard, nothing will happen

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13993989/log.txt)

### Device and Model

Asus ROX Strix 18 - G834JYR

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

v0.148

### OS

Windows 11 -10.0.22621 Build 22621

**Comment by seerge** [comment]
@sebastiaanvandingenen hello,

Did you rebing ``M1`` - ``M5`` in Armoury to something custom?

Volume Up and Volume Down (``M1`` and  ``M2``) are handled on hardware level (i.e. keyboard just emits appropriate windows keycodes). So they should work without AC / G-Helper or any other apps installed. Did they work before ? 

As for ``M3`` ``M4`` ``M5`` buttons. Try to restart app after stopping asus services, press them one by one and check in app's log. they should produce keycodes in the log.

**Comment by xSimone** [comment]
Scar 18 2024 here, works for me fresh install from Windows without any Armoury Crate installation history.

**Comment by seerge** [comment]
@sebastiaanvandingenen hello, any updates on the matter? :)

**Comment by sebastiaanvandingenen** [comment]
It seems my replies were not arriving:

After reinstalling everything seems to work fine, all 5 buttons work. I had
not totally shut down the laptop after running all those installs and
uninstalls (only restarts), I guess this messed something up.

**Comment by seerge** [comment]
@sebastiaanvandingenen ok, great.

I consider this resolved then :)
