### ISSUE TITLE
emulationstation issue

### ISSUE THREAD

**Issue by greyhawk1123** [seerge/g-helper#1956]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

emulation on the rog ally shows the gamepad mode as a keyboard and thus unallowing any keybinds to be made  correctly even when keybinds on the controller portion are configured correctly

### How to reproduce the bug?

1: open emulation station
2: notice key input issues
3:go to input settings and bind controller
4: binding option shows keyboard and unable to fully follow through,

### Logs

n/a

### Device and Model

Asus Rog Ally

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

148

### OS

Windows 11

**Comment by seerge** [comment]
@greyhawk1123 given that you have demonstratively ignored issue template, and didn't include logs - I can't help you anyhow
