### ISSUE TITLE
Multi Zone / Single Zone button

### ISSUE THREAD

**Issue by xSimone** [seerge/g-helper#1957]
Hellu.

Because MiniLED is becoming more and more frequent to be seen on the Asus ROG Laptops, it would be nice if you could have the button like in Garbageoury Crate that allows you to toggle between Single and Multi Zone Lighting with MiniLED panels.

![5ydfg8dnk0ma1](https://github.com/seerge/g-helper/assets/16178961/968ce406-b22b-4f5a-ad12-4fb6083e4ec7)

**Comment by squee666** [comment]
you can manually bind it in extras

![image](https://github.com/seerge/g-helper/assets/628576/08fdc409-3b76-462e-970c-6e0a21b84783)

**Comment by xSimone** [comment]
Oh okay that is cool, though I kind of use all my hotkeys as they're (unfortunately) labelled as. Volume down, up, mute mic, fan speed and G-Helper.

I guess I can use Mic for now. :<

**Comment by seerge** [comment]
@xSimone that buttons exists in  the app for ages. @squee666 has it on screenshot (red Multizone).

If you don't see it - it means that Miniled Toggle endpoint in your system doesn't exist.

Do you you have this Miniled button in AC on your specific device, and does it work ?

**Comment by xSimone** [comment]
Aw I really do not want to reinstall armoury crate. :’c 

I have Asus Scar 18 2024 and it has miniLED. I am sure it should have toggle but unsure.

**Comment by seerge** [comment]
@xSimone well, then I have no idea if it's supported by your device or not. Easiest way is to check in AC.

Next to that you can also create a DSL dump of supported commands using Method 2 from this topic https://github.com/seerge/g-helper/issues/38 .

And upload here.

**Comment by xSimone** [comment]
I DO THIS INSTEAD!!

**Comment by xSimone** [comment]
I will get different SSD and make install just for testing, will do this tomorrow!

**Comment by xSimone** [comment]
@squee666 what machine do you have?

Maybe Scar 18 2024 do not have the button, because MiniLED 2k is small enough to avoid the bloom issue? So they do not add this?

Can you turn off MiniLED in Windows?

**Comment by seerge** [comment]
@xSimone you can just install second windows on same drive :| or run windows from virtual machine, if you don't want to infest computer with AC (even tho, AC uninstaller does it's job well in my experience)

**Comment by Sontarr** [comment]
> Edit: It doesn't work, pressing it only gives 'Multi Mode' no 'Single Mode'

Chance you have HDR enabled? With HDR on the screen always works in multizone. Singlezone is only available if HDR is off.

**Comment by seerge** [comment]
@xSimone thanks, you did Method 1, and I need Method 2. Can you upload that ?

Asus Endpoint responsible for Miniled toggle is ``5001E``,
https://github.com/seerge/g-helper/blob/ce0a1c0ed2529271dff93554151c78dddefc11bb/app/AsusACPI.cs#L76C39-L76C49

And in your scan i see them starting form
```
60024 : 8c308086 (2351988870)                                                                                           
60095 : 1 (1)                                                                                                           
```

So you clearly don't have that available, at least in a way it's done on all other miniled devices.

**Comment by xSimone** [comment]
I will try method two. I am installing windows right now though one moment ;x

**Comment by xSimone** [comment]
So on Scar 2024 model, there's THREE modes.

<img width="244" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/8d2ee403-8aba-41fd-b2c9-0078704368ea">
<img width="231" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/07154e30-1054-49f9-a8fc-cc9f166d79ad">
<img width="237" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/dfb5c476-f9d9-424f-9411-7546f2207cdb">

Using Armoury Crate sadly. :c

**Comment by seerge** [comment]
@xSimone is it for new windows install ? If so - can you check if button is available in G-Helper on it?

If not - please submit a dump using Method 2 (as I was asking)

**Comment by xSimone** [comment]
It do not show on G-Helper, it is stock install, I will try method 2, thank you!

**Comment by xSimone** [comment]
[bgrt.zip](https://github.com/seerge/g-helper/files/13998223/bgrt.zip)

I hope this is help. :<

**Comment by seerge** [comment]
@xSimone great, I have found a miniled toggle for your device :) it's ```0x0005002E```

Please try this build, and post a log from it
[GHelper.zip](https://github.com/seerge/g-helper/files/13998272/GHelper.zip)

**Comment by xSimone** [comment]
IT WORK! I love you. :3

**Comment by xSimone** [comment]
[log.txt](https://github.com/seerge/g-helper/files/13998274/log.txt)

**Comment by seerge** [comment]
Do all 3 statuses work ? Can you post a screenshot of how each one looks (it could be handy for a feature announcement)

**Comment by xSimone** [comment]
Yes they all work, but I think Multizone and Multizone Strong are back to front.

**Comment by xSimone** [comment]
<img width="313" alt="image" src="https://github.com/seerge/g-helper/assets/16178961/a57a4840-b2ea-4ce1-84bc-48bdb8397f2b">

**Comment by seerge** [comment]
@xSimone ok, can you check this build and see if they are named correctly now ?

[GHelper.zip](https://github.com/seerge/g-helper/files/13998358/GHelper.zip)

**Comment by xSimone** [comment]
Yaaay! :3

**Comment by xSimone** [comment]
Maybe rename the 'off' or 'Multizone without border' to 'IPS' or 'Onezone'

**Comment by seerge** [comment]
@xSimone, try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/13998377/GHelper.zip)

Can you double check if all 3 modes are displayed / named correctly ?

Multizone Off - should have no border
Multizone - blue border
Multizone Strong - red border

(also try to restart app and see if after that it still shows correctly)

After that

Can you turn on HDR in windows settings, and open app again -

**Comment by xSimone** [comment]
Yaaay! :3 

I test HDR now.

**Comment by xSimone** [comment]
HDR work! Switch is disable.
But I'm think Switch should be stuck on Multi Zone Strong

**Comment by seerge** [comment]
@xSimone in HDR yo can't turn Multizone Off (by definition), so whole button is disabled (as I told above). This is fine.

I assume this is completed then, thanks for testing :)

**Comment by xSimone** [comment]
Yaaaay :3 

![Blue-Heart-Emoji-Meaning](https://github.com/seerge/g-helper/assets/16178961/9047ce1e-3f94-43ba-b167-e3dc3abb5efe)

**Comment by seerge** [comment]
@xSimone hello,

Other user on reddit says that labels are swapped for this switch 

https://www.reddit.com/r/ASUSROG/s/SUO3evD7J5

My idea is that label should reflect currently active multizone state

Do you know what is different between your observations and theirs?

**Comment by seerge** [comment]
@xSimone i think I know from where the difference is coming from

You wanted to label buttons bases on NEXT state, not current. From my point of view its better to label actual state instead

This build should do that

[GHelper.zip](https://github.com/seerge/g-helper/files/15162425/GHelper.zip)

**Comment by xSimone** [comment]
Owh not, I'm wanted CURRENT state, not next.. I'm happy with how is work.

Maybe his specific model laptop profile with G-Helper is wrong order? 

![image](https://github.com/seerge/g-helper/assets/16178961/d5c1e4cb-b0d2-48d2-ba05-da37581bebeb)

I'm currently using Multi Strong, and is say Multi Strong.

**Comment by seerge** [comment]
@xSimone this build should correct labels for G16, but keep them same for G18

[GHelper.zip](https://github.com/seerge/g-helper/files/15170350/GHelper.zip)

**Comment by dimAmazing** [comment]
> [@xSimone](https://github.com/xSimone) this build should correct labels for G16, but keep them same for G18
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/15180516/GHelper.zip)

Hello i have the same issue with my Asus Rog Flow x16. 
Can you please help me?
I just bought it and doesn't know how to fix this problem with the multi zone control I tried to change it in armoury Crete then I instal G helper and removed armoury crate but nothing can help I still have this toggle with the red borders

p.s. im new on github So maybe I'm use reply form not correctly

**Comment by seerge** [comment]
@dimAmazing hello, all the changes from this topic are live long time ago :)

Does the button appear to be active or disabled in the UI for you? Do you have HDR turned on in windows ? cause if so - Multizone is always active as it's needed for HDR

**Comment by sheinwannahan123-commits** [comment]
Hello am having the issue with not seeing multizone and single zone in my ghelper i have a zephyrus m16 2023
