### ISSUE TITLE
FAN RPM doesn't lower after i exit a game. Temps lower to 50c but fan rpm remain at 4000rpm Rog g16

### ISSUE THREAD

**Issue by AndreiAlex2233** [seerge/g-helper#1959]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

FAN RPM doesn't lower after i exit a game. Temps lower to 50c but fan rpm remain at 4000rpm. Asus rog g16 fans, normally run at 4000rpm at 80c. I need to switch from balanced to silent to fix the issue

### How to reproduce the bug?

Idk what to say here.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13997636/log.txt)

### Device and Model

Asus Rog G16 G614JV

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.148.0

### OS

Windows 11 23h2

**Comment by Kikimahe** [comment]
It is noted in the [FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds): GHelper does not control the fans. :) 

They are controlled by the BIOS/Firmware.

**Comment by seerge** [comment]
@AndreiAlex2233 hello, G-Helper doesn't control your fans in realtime anyhow, your BIOS does. It could be that it's programmed in BIOS to keep fan speed high after load for some time. 

https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds

I can't change anything here :)

**Comment by seerge** [comment]
@AndreiAlex2233 P.S. I see that you are using default fan curve (which is absolutely fine), but you can also try to apply a custom one from ``Fans + Power``. May be that will change behavior in your case somehow.

**Comment by AndreiAlex2233** [comment]
@seerge , i ll try. thanks!

**Comment by AndreiAlex2233** [comment]
@seerge , Out of nowhere, it fixed itself... Works perfectly now. Very good software 👍

**Comment by seerge** [comment]
@AndreiAlex2233 miracle!

**Comment by AndreiAlex2233** [comment]
Another issue, i guess. Cpu full load 80c with default fan curve, if i click Apply custom fan curve, it reach 87c even at 4400rpm(default around 4000rpm). Does custom fan curve do anything to frequency or boost?

**Comment by seerge** [comment]
@AndreiAlex2233 no, it just tells bios to use that fan curve :) rest is up to bios

**Comment by AndreiAlex2233** [comment]
@seerge , thx for info. I hope bios isn't crazy to mess up with voltages or things lol

**Comment by seerge** [comment]
@AndreiAlex2233 well, when custom fan curve is enabled BIOS treats it as a manual mode probably (same as in ac). So may be for your model it increases power limits? (you can run some benchmarks and test)

So you may just set custom power limits next to fans to mitigate that

**Comment by AndreiAlex2233** [comment]
@seerge , on default it reach 4,20ghz, on custom fan curve, it reach 4,50ghz. I will limit some power i guess. Sorry for taking your time!

**Comment by seerge** [comment]
@AndreiAlex2233 Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks

**Comment by AndreiAlex2233** [comment]
@seerge , Thanks for informing me.

**Comment by AndreiAlex2233** [comment]
Hi @seerge , Sorry for taking your time. Could you add to G helper an option to auto switch profiles when i join a game, for example?

Thanks!

**Comment by seerge** [comment]
@AndreiAlex2233 hello, no i can't add that as G-Helper is not monitoring apps that launch in windows anyhow.

**Comment by AndreiAlex2233** [comment]
@seerge , Thanks for the information!

**Comment by AndreiAlex2233** [comment]
@seerge , I'm sorry because i am back here but if i may ask. Is there a difference between Balanced and Turbo(Except fans). I see that cpu/gpu settings are the same for both. One more question. Can i replace on of these with my custom power plan? Because i always need to go to settings(Fans + power to switch to my custom profile), would like to replace Turbo with Custom profile. Image attached.
![Screenshot 2024-04-18 201638](https://github.com/seerge/g-helper/assets/76516294/9d859eae-0829-4771-b100-c3ca38048b68)

**Comment by seerge** [comment]
@AndreiAlex2233 

Each mode is effectively a preset of multiple settings, including power limits , fan algorithm, etc. So they are different.

You can't replace Turbo with other profile, but you obviously can customize it to your needs.

**Comment by AndreiAlex2233** [comment]
@seerge , thanks!
