### ISSUE TITLE
Custom hotkey/macro for changing mode.

### ISSUE THREAD

**Issue by tradao2610** [seerge/g-helper#1961]
**Is your feature request related to a problem? Please describe.**
I have no problem at all.

**Describe the solution you'd like**
My keypad has VIA compatible, it has custom hotkey like F13, F14,...etc for keyboard to quickly do some custom tasks.

**Describe alternatives you've considered**
Maybe in key bindings tab has more "custom key" or macro to changing, switch between mode faster with keypad.

**Additional context**
![asdasdasd](https://github.com/seerge/g-helper/assets/112112934/971bffe2-592a-40d8-904e-f45d6c7be864)

**Comment by seerge** [comment]
@tradao2610 hello, it was recently added. Please check build from this topic https://github.com/seerge/g-helper/issues/1931

And bind your buttons to emit ``Ctrl + Shift + Alt + F16`` .. `F20`` as explained there :)

**Comment by tradao2610** [comment]
Btw I put `"skip_hotkeys":1,` in `json` file follow [this](https://github.com/seerge/g-helper/wiki/Power-user-settings#extra-keybindings) but it not working, `ctrl+alt+shift+f12` still opening app (it has the same keybind with some of my adobe software).

**Comment by seerge** [comment]
@tradao2610 cause that binding have own config line

https://github.com/seerge/g-helper/wiki/Power-user-settings#toggle-performance-mode-or-toggle-app-window-key-binding

You need to put 0 to disable or any code for other key

**Comment by tradao2610** [comment]
It works perfectly now, thank for supporting.
