### ISSUE TITLE
you can add gamevisual?

### ISSUE THREAD

**Issue by GYQC** [seerge/g-helper#1962]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by seerge** [comment]
@GYQC hello, it's already covered in FAQ :)

https://github.com/seerge/g-helper/wiki/FAQ#how-do-i-set-different-visual-styles

**Comment by seerge** [comment]
Added in latest release https://github.com/seerge/g-helper/releases
