### ISSUE TITLE
Mappable button combo for disconnecting XG Mobile

### ISSUE THREAD

**Issue by lawrstay** [seerge/g-helper#1964]
**Is your feature request related to a problem? Please describe.**
Disconnecting XG Mobile connection could have assessibility feature to assist carpal tunnel syndrome users. 

**Describe the solution you'd like**
I'd like to map a keyboard shortcut to allow convenient disconnection of XG Mobile, so that I could map that keyboard shortcut to a controller button, that would allow me to disconnect XGM without using mouse/keyboard when Asus device is docked via XGM.

**Additional context**
The use case for this is when Rog ALLY or Asus laptop is connected to a TV, and having this feature would allow user to disconnect XGM without turning on the TV , open GHelper window, use mouse to click disconnect. Instead user can just use keyboard shortcut with the TV turned off, and just observe the XGM connector's red light turn white, to know that it's safe to disconnect.  Thank you for considering.

**Comment by seerge** [comment]
@lawrstay hello, it's quite exotic requirement.

Since I don't have XGM. Don't you have to also set "GPU mode" switch to Standard prior to toggling XGM on Ally as well? (i know it doesn't really switch any real GPU, but that endpoint exists on Ally and G-Helper shows that buttons cause of that)

**Comment by lawrstay** [comment]
Thank you Seerge for your response. Yes that's true, if the mappable shortcut could be a toggle, that would be useful for both toggling connect & disconnecting XGM, as GHelper is always running in the taskbar.

**Comment by lawrstay** [comment]
Apologies, I edited my response to answer your question after rereading. It would toggle fine even when Eco is selected.

**Comment by seerge** [comment]
@lawrstay try this build, I have added binding below Alt-Tab option in a dropdown

[GHelper.zip](https://github.com/seerge/g-helper/files/14001657/GHelper.zip)

**Comment by lawrstay** [comment]
Thanks for the quick work on this request. 

It works well! 

Would it be possible to add an option in Extra section to "disable XG mobile warning" ? Currently  the popup still requires a mouse to select yes, making the disconnection not as seamless as the connection.

**Comment by seerge** [comment]
@lawrstay i have removed warning if toggle happens from hotkey

[GHelper.zip](https://github.com/seerge/g-helper/files/14001961/GHelper.zip)

**Comment by lawrstay** [comment]
Amazing, thank you so much. I'll give this a spin for few days and circle back if I find any issues.
