### ISSUE TITLE
Lightbar RGB settings disappeared after 0.148v update

### ISSUE THREAD

**Issue by H1m4ru** [seerge/g-helper#1965]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I have a ROG Strix G15 2021 G513IE and i noticed that the RGB settings related to the lightbar disappeared in the last update and only has keyboard settings available. On 0.146v, it's still there and works fine, i can set up standby mode (with that funny red animation) and turn off the lightbar separately.

### How to reproduce the bug?

1. Install 0.148v
2. See that lightbar settings are unavailable
3. Uninstall GHelper and install 0.146v instead
4. Now the lightbar settings are there

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14001468/log.txt)

### Device and Model

ROG Strix G15 G513IE-R74BRTSPS2 (RTX 3050 Ti/R7 4800H)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.148

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@H1m4ru hello, I think this is a duplicate issue https://github.com/seerge/g-helper/issues/1943 :) Please either use build from that topic or just wait for 0.149

**Comment by seerge** [comment]
https://github.com/seerge/g-helper/files/13979464/GHelper.zip
