### ISSUE TITLE
Button below MiniLED button to turn on HDR

### ISSUE THREAD

**Issue by xSimone** [seerge/g-helper#1966]
Can we have a button below the MiniLED button, to toggle on HDR?

Win + Alt + B sometimes doesn't work for me I do not know why. :<

**Comment by seerge** [comment]
@xSimone hello, the shortcut you have mentioned is the only known way to toggle it (next to manually setting in settings)

You can't set it anyhow programmatically to my knowledge.

Sorry

**Comment by xSimone** [comment]
Aw :c
