### ISSUE TITLE
Power Mode changes to silent when charge percent reaches limit even though it is still plugged in

### ISSUE THREAD

**Issue by funkyp1ckle** [seerge/g-helper#1967]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The power mode is changing when the laptop reaches the charge limit

### How to reproduce the bug?

1. Go to the main ghelper window
2. Set a charge limit
3. Let the laptop charge to the limit

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14002339/log.txt)

### Device and Model

Asus Zephyrus M16 2021 - GU603HM

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.148 but has been happening for a few versions. Worked properly before

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@funkyp1ckle hello,

It changes to "Silent", cause that's what you used last time when was on battery.

Both Windows (via own events) and ASUS BIOS (via WMI events) clearly signals app that your laptop is unplugged, so app does what it's designed to do in this

```
1/21/2024 1:11:27 PM: WMI event 123
1/21/2024 1:11:27 PM: WMI event 87
1/21/2024 1:11:28 PM: AutoSetting for Offline
```

You are either have faulty charger (that looses power at random) or literal unstable power at home.

There is nothing I can do, as this is not related to the app.

If power is unstable in your situation, set same mode for battery / plugged and it won't change :)
