### ISSUE TITLE
Keyboard brightness bug after laptop powers on - G14 2022

### ISSUE THREAD

**Issue by TBogdanE** [seerge/g-helper#1969]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When turning on the device, the keyboard brightness is set to medium(for example), and if I try to turn it off when I press the shortcut, it goes from Low to Off, instead of Medium to Low(because the brightness is on medium, and when I press the shortcut, it should go from Medium to Low, then Low to Off). So this is resulting in GHelper thinking the keyboard brightness is off, but the keyboard remains on Low brightness, and to repair this, I should turn the brightness to full, then turn it off again. Is annoying when you are in a very bright environment, a laptop on battery, you turn the brightness off because you don't need it, but it remains on Low, and because of the bright enviroment, you can't see it.

### How to reproduce the bug?

Is described in the detailed description

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14007247/log.txt)

### Device and Model

Asus Zephyrus G14 2022 GA402RJ

### Additional information.

It was the same in the previous versions

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.148.0

### OS

Windows 11 with latest updates

**Comment by seerge** [comment]
@TBogdanE hello,

It's because you have Asus Optimization service running, that also sets backlight brightness :) 

```
21-Jan-24 11:10:40 PM: Optimization service is running
```

You can stop asus services from ``Extra`` so they won't interfere :)

Good luck
