### ISSUE TITLE
CPU Temp limit not working

### ISSUE THREAD

**Issue by git-raccoon** [seerge/g-helper#1970]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

CPU temperature passes the set limits I have set, ranging from 85-87degrees, however G-Helper shows my CPU heating up to 98 degrees at most.

### How to reproduce the bug?

1. Set CPU Temp limits in G-Helper
2. Temperatures rise past limits regardless of if "apply" is clicked again or if auto-apply is enabled 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14017360/log.txt)

### Device and Model

Asus Zephyrus G14 GA402RJ

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.148.0

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@git-raccoon hello, did you click "Auto Apply" ?

**Comment by seerge** [comment]
@git-raccoon as a general remark : 

Default throttle temperature is 96C (i have same laptop as you). After hitting that CPU is supposed to drop power immediately w/o any apps or settings.

And since your CPU is already reaching 2 degrees above, it's likely just a bad hardware (i.e. bad liquid metal, etc). So it simply overheats even after it drops power :) So G-Helper won't fix that anyhow

I would recommend just to run cinebench23 or any other benchmark, and monitor temperature and power CPU consumes on a chart.

**Comment by git-raccoon** [comment]
> @git-raccoon hello, did you click "Auto Apply" ?

Hello, yes I did.



> @git-raccoon as a general remark :
> 
> Default throttle temperature is 96C (i have same laptop as you). After hitting that CPU is supposed to drop power immediately w/o any apps or settings.
> 
> And since your CPU is already reaching 2 degrees above, it's likely just a bad hardware (i.e. bad liquid metal, etc). So it simply overheats even after it drops power :) So G-Helper won't fix that anyhow
> 
> I would recommend just to run cinebench23 or any other benchmark, and monitor temperature and power CPU consumes on a chart.

I'll keep that in mind, thank you.

**Comment by seerge** [comment]
@git-raccoon oke,

And besides that app sets values, and they are accepted by device (based on log)
```
23/01/24 09:48:08: UV: 0 OK
23/01/24 09:48:09: CPU Temp: 86 OK
23/01/24 09:48:10: APU Temp: 86 OK
```

So there is nothing more I can add or change here :)

Good luck with experimenting.
