### ISSUE TITLE
Lightbar checkboxes not showing anymore on the app

### ISSUE THREAD

**Issue by STORMBLESSED10** [seerge/g-helper#1974]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

With the new version (0.148) the options to turn my lightbar on and off o my Strix G16 are no longer available in the app. 

### How to reproduce the bug?

1. Go to extra
2. Under the "Laptop Backlight" section there is no longer a column for lightbar. 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14033788/log.txt)

### Device and Model

Asus ROG Strix G614JV

### Additional information.

I downgraded to version 0.141 to try and the lightbar options were there. 

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.148

### OS

Windows 11

**Comment by seerge** [comment]
@STORMBLESSED10 hello, just get https://github.com/seerge/g-helper/releases/tag/v0.149 :)
