### ISSUE TITLE
Optimized option under GPU Mode doesn't turn Nvidia GPU on consistently and auto brightness issue

### ISSUE THREAD

**Issue by Quang-vip** [seerge/g-helper#1975]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I select the _Optimized_ mode under GPU Mode so that it'd turn the Nvidia gpu off when I unplug the laptop and turn it back on whenever the laptop's plugged in again. 
The gpu doesn't get enabled back when I plug the laptop in unless I explicitly switch to _Standard_ mode and it'd come back on (can verify through the absence of the gpu under device manager, task manager and opening nvidia control panel yields a message saying _there's no nvidia gpu in my system_).

The other way works well however. That is unplugging the laptop and the nvidia gpu would get disabled, leaving only the iGPU on.

But after unplugging and the nvidia gpu gets disabled, I think the nvidia tray icon should also disappear like it did when I still had Armoury Crate installed and used its optimized mode. 
In this case it still stayed there along with the gpu activity tray icon (hence the reason why I was still able to _try_ to open the control panel through the icon and it says _there's no nvidia gpu in my system_ afterwards) but it should go away knowing that there's "no" nvidia gpu in my laptop.
After a reboot it does disappear though.
But I think this should be the control panel's or Windows' behavior?

And apparently the screen's brightness doesn't automatically change according to the power modes.
i.e: For _Silent_ mode, it should remember the brightness level I last set when I unplugged the laptop and set it back to full brightness (as per my preference) when it goes back to _Balanced_ when I plug the laptop back in.

I still can freely change the brightness level but that'd mean I have to manually do it whenever I unplug and plug the laptop.
Back in AC it worked well, but I suppose the problem resides in my power plans configs? (I did run the power profiles reset command in powershell as said in _Troubleshooting_)

I would really appreciate any input on my issues! And those issues aside, **GHelper** really is better than AC in terms of lightweightness and functionalities so kudos for the app :DD

### How to reproduce the bug?

1. Open up GHelper
2. Select _Optimized_ under GPU Mode
3. Unplug the laptop from AC charging
  -> Nvidia GPU gets disabled but Nvidia tray icon still stays
  -> Brightness level doesn't get lowered (as per my preference) to the level I set prior when automatically switching to _Silent_ mode
4. Plug the laptop back to AC
  -> Nvidia GPU doesn't get turned back on (no presence under device manager or task manager) unless I manually select _Standard_ mode
  -> If the brightness was set to a lower level, it doesn't get set back on full after automatically switching to _Turbo_ mode

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14037883/log.txt)

### Device and Model

Asus TUF Gaming A15 - FA507NV

### Additional information.

+ _**Asus Smart Display control**_ was also uninstalled and **_MyASUS_** still remains but that shouldn't be part of the issue right?
+ **Display Mode** under nvidia control panel is currently set to **_Automatic Select_** (advanced optimus?)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.148.0

### OS

Windows 11 Home SL 22H2

**Comment by seerge** [comment]
@Quang-vip hello,

You have mixed multiple things up.

For **brightness** and sometimes not working Eco mode - check about [already known issue with Nvidia drivers](https://github.com/seerge/g-helper/discussions/1042), and check "Enable GPU on shutdown" under extra. It should prevent it (or just make sure that you always shut down / reboot / hibernate with GPU being on)

> Unplug the laptop from AC charging
> -> Nvidia GPU gets disabled but Nvidia tray icon still stays

Tray icon will stay there of course, cause it's part of Nvidia software package :) It doesn't reflect if GPU was toggled off or not anyhow :)

Good luck.

**Comment by seerge** [comment]
@Quang-vip Silent, Standard and Turbo are performance modes :) they are not related to brightness anyhow.

Do you see NVidia GPU after reboot in Standard mode?

**Comment by seerge** [comment]
@Quang-vip 

>Wait really? I just thought they were tied to brightness since it worked like that in AC. Welp guess it's different here.

AC changes windows power plans, and windows has a habit to save brightness levels per power plan :) so you could see brightness jumping as a side effect. G-Helper doesn't do that (you just stay on deault windows 'balanced' power plan)

>Yes, I can see it activated

Then it's happening :) try to set Eco , and if GPU is gone - it's working (according to your log that's the case, cause at least BIOS reports that it is)

**Comment by seerge** [comment]
> Yep, switching manually back and forth between eco and standard works just fine.
It's just in the Optimized gpu mode that when I plug the laptop back in it doesn't automatically turn the dGPU on for me. I thought that's a bug of some kind. (works fine when I unplug the laptop though, automatically disables the dGPU just fine)

Do you use USB-C charger or barrel ? If USB - do you have "Keep GPU disabled on USB-C" selected under ``Extra`` ? :)

**Comment by Quang-vip** [comment]
> Do you use USB-C charger or barrel ? If USB - do you have "Keep GPU disabled on USB-C" selected under `Extra` ? :)

I've been using barrel.
But wait, I have also been using that option. I just went and unchecked it and walla, it WORKED!!
Thank you for pointing it out!!

I first thought that option was explicitly meant to be for USB-C charging. 
But from how it behaved, I think the app can't differentiate between whether the machine is being charged via barrel (AC) or via USB-C PD (DC)?

**Comment by seerge** [comment]
@Quang-vip that option is explicitly meant to be for USB-C :) 

But in a log i see that your device reports charger to be non-barrel

```
1/24/2024 4:10:56 PM: AutoSetting for Online
1/24/2024 4:10:56 PM: Mode = 2 : OK
1/24/2024 4:10:56 PM: ChargerStatus: 0  <---- this should be 1 if it would be barrel charger
```

**Comment by Quang-vip** [comment]
> But in a log i see that your device reports charger to be non-barrel

Alright that seems weird...
I guess it's the BIOS's fault for that?

**Comment by seerge** [comment]
@Quang-vip yes

And sometimes (when app checks) it says it's a barrel
```
1/24/2024 6:08:18 PM: ChargerStatus: 1
```

I don't know why it's like that on your specific device (if it's a bug with bios reporting wrong data, or just random issue), but app relies on that - as it's the only way to actually separate USB-C from barrel

**Comment by seerge** [comment]
@Quang-vip you can try to run following as admin in powershell

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DSTS(0x0012006C)
```

It's a command that gets a reading, and it should be 1 for barrel, 0 for battery, and something else (usually 2) for USB-C

**Comment by Quang-vip** [comment]
> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DSTS(0x0012006C)

That command somehow threw this error at me:

```Exception calling "DSTS" : "Generic failure "
At line:1 char:1
+ (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DSTS(0x001 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WMIMethodException

**Comment by seerge** [comment]
@Quang-vip on some devices those commands are not available via WMI / Powershell (but available when G-Helper gets it directly) :)

You can check what app writes in a log at a line with
```
1/24/2024 6:08:18 PM: ChargerStatus: 1
```
But it checks for that only if that checkbox under ``Extra`` is ON and you are plugged-in (according to windows itself)

**Comment by seerge** [comment]
@Quang-vip then just turn off 'Keep GPU off on USB-C' option :) it seems that it's not really detectable in your case (unless you know other way)

What does ChargerStatus show when you plug in real USB-C ?

**Comment by Quang-vip** [comment]
Still says it's  0  when USB-C is plugged in

**Comment by seerge** [comment]
@Quang-vip oke :) well, it's clearly strange but since reading is like that I can't change much here :(

**Comment by Quang-vip** [comment]
Ah, is it possible though for the app to take note of the user's screen brightness preference for each mode then sets the according brightness whenever that mode is switched to?
That'd be a nice workaround for the power profiles thing =)

**Comment by seerge** [comment]
@Quang-vip i intentionally don't want to do that :) as I personally (+ I'v heard it from lots of other people), find it annoying when brightness jumps with each mode.

But you can just clone default windows "balanced" power plan twice, and assign "custom" plans to each mode as explained here
https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-windows-power-plans-with-each-mode

Then windows will be switching brightness same as it does in AC

**Comment by Quang-vip** [comment]
Thanks a lot again!
I just added 2 more power profiles and they work wonders now, just like in AC!

**Comment by Quang-vip** [comment]
@seerge An interesting find I just discovered

While still plugged in, if I manually switch to Eco mode then back to Optimized (with the Disable gpu on USB-C option ticked), the _ChargerStatus_ would have a value of **1**
What I'm guessing here is that after the laptop is plugged in, there's a certain delay before the value would turn to **1**
It's not set to **1** immediately after I plug the laptop in apparently

The same behavior could be seen in AC where the dGPU is only turned on after a few seconds (3-5secs probably) after I plugged the laptop in.

Perhaps you could make a delay after it detects that a charger is plugged in before it rechecks the _ChargerStatus_ and enable the dGPU?

**Comment by seerge** [comment]
That delay would destroy experience for other 70 000 people using app :)

**Comment by Quang-vip** [comment]
Ah I didn't mean for the fix to be applied to the whole master branch of the repo so everyone, regardless of their laptop models, experiences the same thing :D

If only you could insert the delay so the app only apples if it specifically checks if the machine it's running on is the model of my laptop (**FA507NV**) and the revision of the BIOS running being **312** (the current BIOS version my machine)

I think the delay before _ChargerStatus_  actually becomes **1** affects any laptops of the same model as mine, I'm not sure about the BIOS versions that the behavior resides in.
And I think I can make such changes to the code and make a pull request but it's been quite a long while since I last touched C#. So if I do I gotta take some grip first before actually modifying =))

The idea is actually quite subjective but that's as far as I can tell ;)

**Comment by seerge** [comment]
@Quang-vip it's still very exotic, as it is applicable only for your model and when USB-C option is toggled ON in settings (and it's not a default state) :)

Since ChargerStatus doesn't change to anything besides 0 and 1 (and it should be 2), it's still unreliable for detecting USB-C charger in a first place, so it's easier just to toggle off that option under Extra

**Comment by Quang-vip** [comment]
@seerge I just did some experimenting with the code and I got success in putting a delay before the `IsPlugged()` boolean is returned and now after plugging the laptop in, the dGPU is turned on automatically as expected.

And it turns out, just a _600ms_ delay is enough, no need to be longer as the BIOS already reported that the charger is present in the system after around that time.

For anyone wanting to check out:
https://github.com/Quang-vip/g-helper/tree/fa507nv

Thanks a lot for your help and suggestions!
And again, you've written great software ;))

Also, would you mind if I post the rebuilt app for anyone in the same case as mine to try out?

**Comment by Quang-vip** [comment]
> @seerge I just did some experimenting with the code and I got success in putting a delay before the `IsPlugged()` boolean is returned and now after plugging the laptop in, the dGPU is turned on automatically as expected.
> 
> And it turns out, just a _600ms_ delay is enough, no need to be longer as the BIOS already reported that the charger is present in the system after around that time (at least for my laptop model and current BIOS revision)
> 
> For anyone wanting to check out: https://github.com/Quang-vip/g-helper/tree/fa507nv
> 
> Thanks a lot for your help and suggestions! And again, you've written great software ;))
> 
> Also, would you mind if I post the rebuilt app for anyone in the same case as mine to try out?

**Comment by seerge** [comment]
@Quang-vip i see, great :) If I will have more information (if all FA507 models are like that or it's only isolated to your case), I can consider adding a delay like that as well.

**Comment by NatsuZoraKanata** [comment]
> 这非常令人沮丧：
> 
> `1/24/2024 9:54:19 PM: ChargerStatus: 0`
> 
> 我一直在重新插入充电器，但它一直在产生似乎真的是 BIOS

Hello! I found the same problem with my laptop, my laptop model is FA507XV. Thank you for trying to fix this!😊
