### ISSUE TITLE
Lightbar and Keyboard Issue

### ISSUE THREAD

**Issue by BL47E** [seerge/g-helper#1977]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

lightbar for Asus ROG Strix G15 2022 not showing up however when I downgraded back to 0.145 it worked.

### How to reproduce the bug?

Install version 0.148 on a Rog Strix G15 with light bar. Open G-helper then go to extra and you will notice that the customization options for lightbar is not showing up however when you downgrade to 0.145 this problem doesn't seem to exist.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14042126/log.txt)

### Device and Model

Asus ROG Strix G15 2022 AMD R7 6800H

### Additional information.

![V0 148](https://github.com/seerge/g-helper/assets/86646978/ac71b7b6-2cb0-4b40-9edd-931d701424ea)
![V0 145](https://github.com/seerge/g-helper/assets/86646978/0ac06171-c39a-4469-a1b8-6ec185135a9a)

### Armoury Crate

Never installed

### Asus Services

0

### Version

0.148

### OS

Windows 10

**Comment by seerge** [comment]
@BL47E hello, I have already fixed it in https://github.com/seerge/g-helper/releases/tag/v0.149 :)

**Comment by BL47E** [comment]
ohhhh YIPEEEEEEEEEE . Once again thanks a lot for creating such a great softwareI was really tired of armory crate being too heavy and slow and buggy
