### ISSUE TITLE
Zephyrus G16: Windows Log in screen black

### ISSUE THREAD

**Issue by francescobettucci** [seerge/g-helper#1979]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I noticed this bug after I started using  G-Helper.
Up to know it happened few times that when I was using  the pc on battery, after it goes automatically into sleep mode and I try to log in again, I have a black screen with only the windows hello animation on top and the cursor which is moving, but I am not able to log in and I have to restart the pc with the power button. I don't know if this could be related to G-Helper or not, I hope this message can be useful.
Thank you for your time 

### How to reproduce the bug?

- pc on battery
- enable GPU on shutdown is checked
- let the pc go in sleep mode
- and then try to log in

### Logs

25/01/2024 09:54:38: Monitor Power On
25/01/2024 09:54:38: AutoSetting for Offline
25/01/2024 09:54:38: Mode = 2 : OK
25/01/2024 09:54:39: Input: \\?\hid#vid_0b05&pid_19b6&col03#6&19e2ad7&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
25/01/2024 09:54:39: Eco flag : 0
25/01/2024 09:54:39: Mux flag : 1
25/01/2024 09:54:39: \\?\DISPLAY#TMX1603#4&b91bd33&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25/01/2024 09:54:39: \\?\DISPLAY#TMX1603#4&b91bd33&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25/01/2024 09:54:39: Screen = 60Hz : OK
25/01/2024 09:54:39: ScreenOverdrive = 0 : OK
25/01/2024 09:54:39: BatteryLimit = 100 : OK
25/01/2024 09:54:41: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
25/01/2024 09:54:41: AuraMode: AuraStatic
25/01/2024 09:54:41: USB 19B6: 5D-B3-00-00-FE-67-91-EB-00-00-FF-FF-FF-00-00-00-00
25/01/2024 09:54:41: USB 19B6: 5D-B4
25/01/2024 09:54:41: USB 19B6: 5D-B5-00-00-00
25/01/2024 09:54:41: Init 19B6: 5D-B9
25/01/2024 09:54:41: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
25/01/2024 09:54:41: Init 19B6: 5D-05-20-31-00-1A
25/01/2024 09:54:42: Auto 19B6: 5D-BA-C5-C4-01
25/01/2024 09:54:42: Session:SessionUnlock
25/01/2024 09:54:42: \\?\DISPLAY#TMX1603#4&b91bd33&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25/01/2024 09:54:42: \\?\DISPLAY#TMX1603#4&b91bd33&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25/01/2024 09:54:42: Screen = 60Hz : OK
25/01/2024 09:54:42: ScreenOverdrive = 0 : OK
25/01/2024 09:54:48: HID Device Event: Checking for new ASUS Mice
25/01/2024 09:54:48: HID Device Event: Checking for new ASUS Mice
25/01/2024 09:55:08: F8
25/01/2024 09:55:08: Brightness = 32 : OK
25/01/2024 09:55:08: F8
25/01/2024 09:55:08: Brightness = 32 : OK
25/01/2024 09:55:09: F8
25/01/2024 09:55:09: Brightness = 32 : OK
25/01/2024 09:55:09: F8
25/01/2024 09:55:09: Brightness = 32 : OK
25/01/2024 10:18:14: Latest version 0.148.0.0
25/01/2024 10:18:17: GPU usage:  %
25/01/2024 10:18:17: Running eco command 1
25/01/2024 10:18:43: GPUEco = 1 : OK
25/01/2024 10:18:44: Eco flag : 1
25/01/2024 10:18:44: Mux flag : 1
25/01/2024 10:18:44: \\?\DISPLAY#TMX1603#4&b91bd33&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25/01/2024 10:18:44: \\?\DISPLAY#TMX1603#4&b91bd33&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25/01/2024 10:18:44: Screen = 60Hz : OK
25/01/2024 10:18:44: ScreenOverdrive = 0 : OK
25/01/2024 10:42:54: Monitor Dimmed
25/01/2024 10:43:09: Monitor Power Off
25/01/2024 10:43:09: Backlight 19B6: 5D-BA-C5-C4-00
25/01/2024 11:01:16: ------------
25/01/2024 11:01:16: App launched: ROG Zephyrus G16 GU603VU_GU603VU :0.148.0.0en-GB.
25/01/2024 11:01:22: CPU: -1 - 13th Gen Intel(R) Core(TM) i7-13620H - Intel64 Family 6 Model 186 Stepping 2
25/01/2024 11:01:23: AutoSetting for Offline
25/01/2024 11:01:23: Mode = 2 : OK
25/01/2024 11:01:23: Input: \\?\hid#vid_0b05&pid_19b6&col03#6&19e2ad7&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
25/01/2024 11:01:23: Power Plan 381b4222-f694-41f0-9685-ff5bb260df2e:OK
25/01/2024 11:01:23: Eco flag : 1
25/01/2024 11:01:23: Mux flag : 1
25/01/2024 11:01:23: \\?\DISPLAY#TMX1603#4&b91bd33&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25/01/2024 11:01:23: \\?\DISPLAY#TMX1603#4&b91bd33&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25/01/2024 11:01:23: Screen = 60Hz : OK
25/01/2024 11:01:23: ScreenOverdrive = 0 : OK
25/01/2024 11:01:23: BatteryLimit = 100 : OK
25/01/2024 11:01:23: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
25/01/2024 11:01:23: AuraMode: AuraStatic
25/01/2024 11:01:23: USB 19B6: 5D-B3-00-00-FE-67-91-EB-00-00-FF-FF-FF-00-00-00-00
25/01/2024 11:01:23: USB 19B6: 5D-B4
25/01/2024 11:01:23: USB 19B6: 5D-B5-00-00-00
25/01/2024 11:01:23: Init 19B6: 5D-B9
25/01/2024 11:01:23: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
25/01/2024 11:01:23: Init 19B6: 5D-05-20-31-00-1A
25/01/2024 11:01:23: Monitor Power On
25/01/2024 11:01:24: Auto 19B6: 5D-BA-C5-C4-01
25/01/2024 11:05:14: Latest version 0.148.0.0
25/01/2024 11:29:32: Monitor Dimmed
25/01/2024 11:29:47: Monitor Power Off
25/01/2024 11:29:47: Backlight 19B6: 5D-BA-C5-C4-00
25/01/2024 11:33:13: Monitor Power On
25/01/2024 11:33:13: AutoSetting for Offline
25/01/2024 11:33:13: Input: \\?\hid#vid_0b05&pid_19b6&col03#6&19e2ad7&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
25/01/2024 11:33:13: Eco flag : 1
25/01/2024 11:33:13: Mux flag : 1
25/01/2024 11:33:13: \\?\DISPLAY#TMX1603#4&b91bd33&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25/01/2024 11:33:13: \\?\DISPLAY#TMX1603#4&b91bd33&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25/01/2024 11:33:13: Screen = 60Hz : -1
25/01/2024 11:33:13: ScreenOverdrive = 0 : OK
25/01/2024 11:33:13: BatteryLimit = 100 : OK
25/01/2024 11:33:16: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
25/01/2024 11:33:16: AuraMode: AuraStatic
25/01/2024 11:33:16: USB 19B6: 5D-B3-00-00-FE-67-91-EB-00-00-FF-FF-FF-00-00-00-00
25/01/2024 11:33:16: USB 19B6: 5D-B4
25/01/2024 11:33:16: USB 19B6: 5D-B5-00-00-00
25/01/2024 11:33:16: Init 19B6: 5D-B9
25/01/2024 11:33:16: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
25/01/2024 11:33:16: Init 19B6: 5D-05-20-31-00-1A
25/01/2024 11:33:17: Auto 19B6: 5D-BA-C5-C4-01
25/01/2024 11:33:21: Session:SessionUnlock
25/01/2024 11:33:21: \\?\DISPLAY#TMX1603#4&b91bd33&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25/01/2024 11:33:21: \\?\DISPLAY#TMX1603#4&b91bd33&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25/01/2024 11:33:21: Screen = 60Hz : OK
25/01/2024 11:33:21: ScreenOverdrive = 0 : OK
25/01/2024 11:33:38: Hibernate after 600
25/01/2024 11:38:22: Design Capacity: 90005mWh, Full Charge Capacity: 86912mWh, Health: 0.9656352424865285261929892784%

### Device and Model

Asus Zephyrus G16 GU603VU

### Armoury Crate

Installed

### Asus Services

0

### Version

0.148

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@francescobettucci hello, i don't think it's directly related to G-Helper anyhow, but rather some hiccup with windows sleep and it's wake up.

Do you plug / unplug laptop during sleep ? 

You can try to reset windows power plan settings to all defaults [as explained here](https://github.com/seerge/g-helper/wiki/Troubleshooting#resetting-windows-power-plan-to-defaults) , may be that would affect it somehow.

**Comment by seerge** [comment]
P.S. Since you are on battery and have dedicated GPU turned off, it could be also something related to Intel iGPU drivers not waking up after sleep. You can try to [reinstall them as well](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers)

**Comment by francescobettucci** [comment]
@seerge hey thank you for the quick answer, no the laptop did that when it was on battery, without plug/unplug.
I will try. But it happened either in eco mode and optimized, I should try with standard mode as well. 
I will let you know
Thanks

**Comment by seerge** [comment]
@francescobettucci any updates on the matter?

**Comment by seerge** [comment]
@francescobettucci ok, great. Closing as resolved then
