### ISSUE TITLE
App doesn't start anymore

### ISSUE THREAD

**Issue by cojocarucosmin** [seerge/g-helper#198]
**Describe the bug**
I've installed the app, worked fine.
I removed C:\Windows\System32\ASUSACCI\ArmouryCrateKeyControl.exe so that M4 button will not trigger anymore ArmoryCrate and played around with the advanced settings from the keyboard, G-Helper doesn't open anymore. 
It shows a blank screen and afterwards remains in system tray as being open but you cannot see it.
How can I eliminate all the configs G-Helper already did so I can reinstall a fresh version?

**Clear scenario to Reproduce**
1. Install G-Helper
2. Change performance mode to Silent
3. GPU mode optimized
4. Laptop screen Auto
5. Laptop keyboard Static 
6. Extra -> when pressing M4 show G-Helper
7. Uninstall ArmoryCrate 
8. Restart
9. Remove Armory Crate option from BIOS
10. Remove file C:\Windows\System32\ASUSACCI\ArmouryCrateKeyControl.exe
11. Check G-Helper from system tray if it still works

**Expected behavior**
I want to be able to either do a fresh install of the app or make the app work so I can see the options when the app is running.

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/11162233/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Laptop model: Asus Rog Zephyrus G14 (2021)

**Asus software**
- Armoury crate (or it's services installed): yes
- MyASUS installed: yes
- Other Asus services running in background: not the case

**Additional context**
(https://github.com/seerge/g-helper/files/11162228/log.txt)

## NOTE
Bug reports without clear information or scenario to reproduce will be closed without answer. 
Please respect time of the developer. Thanks.

**Comment by seerge** [comment]
Can you check windows Even Viewer for any crashes mentioning g-helper ? in log it looks like it was launched few times over last 30 mins?

**Comment by seerge** [comment]
Aside from that app seem to be alive, may be there is something with your windows that blocks clicks in system tray? Does app window open when you launch app manually from it's folder ?

**Comment by cojocarucosmin** [comment]
Yes, I was playing around with it and kept trying to also uninstall Armory Crate.
This is why there are a lot of logs. But it ran in the background; I couldn't see anything, no window appeared.
It showed a blank screen (like it tried to change resolution or refresh rate) and then the app started in system tray but the window didn't appear.

I managed to make it work by deleting the json from %AppData%\GHelper and deleting the GHelper task from Task Scheduler.
Maybe you should also define an uninstall procedure to be able to do a fresh install.
Even if you take the exe file again, due to the json already there in AppData, it will keep the settings and if these are conflicting with the Laptop ones, the app will still not work.

Also, as I have an older version of G14, it crashed several times (with the same recovery procedure of deleting the json) when playing around with Colour setting (I do not have RGB) or Animation Speed.

Hope all the feedback helps and thanks a lot for all the effort on this app! 
It is very useful and even if still in development, it is much better than Armory Crate one.

**Comment by seerge** [comment]
Ok. Glad that it worked out. Generally no matter what settings are in json app should start and do it's stuff (and according to log it happened) , not sure why main window was not visible in your case still tho :)

**Comment by seerge** [comment]
But i will take your experience with erasing config into consideration:)
