### ISSUE TITLE
 Shortcut for Display Refresh Rate Switching

### ISSUE THREAD

**Issue by Maneeha1234SL** [seerge/g-helper#1983]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

the feature request is related to the inconvenience users currently face when switching between display refresh rates. The existing process requires navigating through multiple menus, which can be time-consuming and less efficient. The proposed shortcut aims to address this problem by providing a quicker and more user-friendly method for users to switch between different display refresh rates based on their specific needs or activities.

### Describe the solution you'd like

I would like the implementation of a customizable keyboard shortcut that allows users to easily switch between display refresh rates. This solution would provide users with a more efficient and streamlined method for adjusting their display settings, enhancing the overall user experience. The ability to customize the shortcut would add flexibility, allowing users to assign a key combination that aligns with their preferences and workflow.

### Device and Model

ASUS ZEPHYRUS G15 GA503RM

**Comment by seerge** [comment]
@Maneeha1234SL hello, why would you want anything but max refresh rate when plugged in ? What is the real practical scenario in frequent refresh rate changes ?

**Comment by seerge** [comment]
@Maneeha1234SL i think you mix things up a bit :) 165Hz is **not** an overdrive. It's just a higher refresh rate (the one you can also select in windows display settings). 

And this is the first time I hear that refresh rate on display somehow affects your temperatures. It does affect battery life, but app has ``Auto`` setting exactly for that purpose.

I intentionally don't want to overcomplicate app with limitless settings, options  and bindings (as with 70K+ users everyone would want to have something super custom and fit for them)

If you really want to change refresh rates from keyboard, you can just try AutoHotkey app, it can do that. As refresh rate is just a setting in windows, and not specific to Asus laptops anyhow.

So, sorry. Closing as not planned :) 

Good luck
