### ISSUE TITLE
AniME Matrix Settings not listed on G14 GA401QM

### ISSUE THREAD

**Issue by Mahlarian** [seerge/g-helper#1984]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The control settings used to configure the AniMe Matrix are not listed in G-Helper, despite my laptop model supporting it. 

### How to reproduce the bug?

1. Open G-Helper
2. See no option to configure the Matrix display

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14069369/log.txt)

### Device and Model

Asus Zephyrus G14 GA401QM

### Additional information.

I've never seen the Matrix display work on this laptop. I recently bought it brand new, and when I received it immediately flashed it with a clean copy of Windows 10 (it came with Windows 11 and did not want to use it). I thought the display feature was cool, but since it was attached to ROG bloat, decided it wasn't worth the hassle. Found this tool, and it's been super helpful, but sad to see it wasn't showing the option for Matrix display.

My only guess for a potential cause is that I never installed Armoury Crate, maybe a driver didn't get installed that's needed for controlling it? I've done attempted basic troubleshooting, including restart, driver updates, and hardware reset, to no avail.
![image](https://github.com/seerge/g-helper/assets/32558416/db931c39-5fbb-475b-9551-19d6636e2e26)
 

### Armoury Crate

Never installed

### Asus Services

None

### Version

0.148.0

### OS

Windows 10 22H2

**Comment by seerge** [comment]
@Mahlarian hello,

If app doesn't show Anime Matrix section, it means that it doesn't see it among devices in windows. Anime Matrix identifies itself just as a USB device.

You can download this ancient utility to list all devices, and look for one with Vendor ID  ``0b05`` (it's Asus) and Device ID ``193B``
https://www.nirsoft.net/utils/usbdeview-x64.zip

If you don't see it there , then something is wrong with the device itself. May be it's cause of windows 10? 

Are you sure that your laptop has it in a first place?

Anyway, I can't really fix anything here, as if device is not there - app can't control it  :)
You can try to install AC, but I really doubt it will see it either.

![Screenshot 2024-01-26 224407](https://github.com/seerge/g-helper/assets/5920850/c9f17f93-faa4-4397-b717-a71499122d88)

**Comment by Mahlarian** [comment]
Thanks for your quick response! I tried looking at the device viewer, nothing matched, unfortunately. Also tried AC in the off chance that was it, as you said, that didn't fix it either.

The laptop has that dotted Matrix design on the top of the lid like it has it, the Asus site also says these models of laptops has it, but says only specific models. Just have a hard time understanding why'd they have the pattern but not the Matrix display. 

Oh well. I'll roll with the assumption that I just don't have it. Guess it seems kinda dumb that I don't even know the own feature set of my laptop, but thought itd be better to ask, just in case.

**Comment by seerge** [comment]
@Mahlarian dots on the top doesn't mean it's matrix. Even models w/o matrix has holes :)

Closing as completed then)
