### ISSUE TITLE
[Feature Request] Button "download all drivers"

### ISSUE THREAD

**Issue by artswanted** [seerge/g-helper#1986]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Easier driver downloads

### Describe the solution you'd like

Now, when reinstalling the windows, need to download all the files in advance, you either need to go to the Asus website and spend a lot of time, or click on each update individually in g-helper, but in the latter case, the problem remains that after clicking on downloading a selected driver, the update window is closes, the download begins and only the main g-helper window remains (not sure if this is not an error). Thus, each time you need to press the Update button, wait until it finds everything, click and repeat. A button to "download all", or at least not to close the window with updates, would greatly simplify life, both with a simple reinstallation of drivers, and with a clean installation of the system. That is, by installing a clean system, I can be sure that g-helper is enough for me to download the latest drivers in one click without any problems, all at once.

### Describe alternatives you've considered

As an alternative, add at least checkboxes about which drivers to download, no more than 5, if Asus has some kind of limit and they may consider this an attack when downloading files so en masse

### Device and Model

ASUS ROG Strix G17 2023 G713PV-LL068

### Additional information.

https://youtu.be/0wjVuyPsIT0

**Comment by seerge** [comment]
@artswanted hello, 

G-Helper doesn't download those drivers in a first place. It just opens a link with default browser in windows, and lets browser handle / download it 

Update window doesn't close when you click on download, it's just browser window pops up in front :) Try to set browser window to be smaller and on the left from Updates, then it won't overlap.

**Comment by artswanted** [comment]
Yes, you're right, but anyway. I understand that it just opens links, but why not give the opportunity to open all these links at once in a cycle with an interval of 1-2 seconds, click and that’s it, you get everything you need.

**Comment by seerge** [comment]
@artswanted because when you try to open multiple links at once, Edge or Chrome will simply stop opening them, thinking it's a spam :)

I honestly, don't see any real problem here, that would require a separate solution.

Please keep min mind, that you don't need to download **all** drivers / files there. Most of them will be already installed automatically by windows update. Others are just irrelevant (like like firmware updates, if you already installed them before)

And lastly - GPU drivers for both NVidia and AMD are usually much newer on actual Nvidia and AMD websites, than on Asus servers :)
