### ISSUE TITLE
ROG Strix G814JZ

### ISSUE THREAD

**Issue by pLaTEENum** [seerge/g-helper#1987]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I've noticed that since 0.148 i can't turn off lights no more, keyboard or either lightbar.
seems like battery charge limiter is not working also.
the power limits are working incorrectly. doesnt matter the limit, the CPU will draw much more power causing thermal throttling.

### How to reproduce the bug?

beats me.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14072553/log.txt)

### Device and Model

ROG Strix G814JZ

### Armoury Crate

Uninstalled

### Asus Services

0 

### Version

0.148

### OS

windows 10 22H2

**Comment by seerge** [comment]
@pLaTEENum hello,

I see that "input device" (USB device responsible for sending hotkeys to the app) is not available on your computer at all
```
27/01/2024 13:14:11: Input device not found
```

So backlight controls (up / down) won't work, cause app simply doesn't get notification when hotkey is pressed. Does it work with Asus services turned on (then they will handle it)? Did you try to shut down and start computer again?

As for the rest of your remarks, I see that battery limit is being set, and it's accepted. 
```
26/01/2024 19:00:26: BatteryLimit = 80 : OK
26/01/2024 19:00:26: BatteryLimit = 80 : OK
```

Same applies for power limits, rest is up to asus bios on how to handle that :)
```
26/01/2024 19:00:27: PowerLimit A3 = 115 : OK
26/01/2024 19:00:27: PowerLimit A0 = 115 : OK
```

How do you know that they are not working ? How much power does your CPU draw when you would launch come benchmark and monitor it with HWinfo ?

**Comment by pLaTEENum** [comment]
Hello Seerge,

I think i've found the issue for the lights, i've did some device manager tweaks disabling that usb device. oh well...
as for the battery, i usually leave it plugged when i turn it off. idk, im just lazy to unplug it xD 
as for the power draw, i did testing while in game and the cpu draws up to 1.35v (according to HWINFO), i've tried kinda everything to change it, but beats me.

**Comment by seerge** [comment]
@pLaTEENum 

Your battery would always start charging again on restart (even if you wake up from "hibernate"), until actually G-Helper (or corresponding Asus service) starts and sets it again
https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working

For power draw, I didn't really get what you mean. What is 1.35v ? Volts? Power limits are in Watts :) and according to your logs you were setting 115W.

Can you post a screenshot from HWinfo ?

**Comment by pLaTEENum** [comment]
[hwinfo log.CSV](https://github.com/seerge/g-helper/files/14087783/hwinfo.log.CSV)

Hi Seerge,

Sorry for the late reply, i've added a log from HWINFO. somehow now its not over exceeding the limits. I haven't made any changes tbh.

**Comment by seerge** [comment]
@pLaTEENum well, then everything is good ? :)

**Comment by seerge** [comment]
Closing as resolved then

**Comment by pLaTEENum** [comment]
thanks, my bad 💯  keep up the good work!
