### ISSUE TITLE
Cannot change some button functions in G-Helper

### ISSUE THREAD

**Issue by Rabcor** [seerge/g-helper#1988]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

<img width="701" alt="image" src="https://github.com/seerge/g-helper/assets/5684325/0268799a-2842-4f0a-a050-c690310b31a3">

Only M1, M2, M3, M5 and FN+C and FN+F4 can have their functions altered in G-Helper.

I would like to be able to edit M4 and FN+F5 (those two buttons on my laptop have the same exact function, it's a stupid ass design), and fn+f6 for that matter (cut? seriously? what's wrong with ctrl+x asus?!); but the one truly major thing is that i need to be able to change M4 or FN+F5 because those buttons by default have the same button which triggers me something fierce.

There's also FN+V which cycles color modes by default if armoury crate is installed.

### How to reproduce the bug?

1. Install G-Helper
2. Try to edit special key functions
3. Find some special keys missing
4. Sadness

### Logs

N/A

### Device and Model

ASUS ROG Strix G17 (2022) G713RW

### Armoury Crate

Uninstalled

### Version

0.148.0

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@Rabcor hello, I was already answering this multiple times.

Fn+F5 / M4 emit same keycode on Asus laptops, and this function toggle performance modes in G-Helper. So there is no need to rebind it, it's reserved :)
