### ISSUE TITLE
Implement Direct Keyboard Shortcuts for Specific Performance Modes

### ISSUE THREAD

**Issue by pynbbz** [seerge/g-helper#1989]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Implementation of direct keyboard shortcuts for switching to specific performance modes in ghelpers. Currently, there is a toggle shortcut that cycles through the modes, but having direct shortcuts for each mode would provide a faster and more efficient way to switch to a desired mode.

### Describe the solution you'd like

Introduce individual keyboard shortcuts for each performance mode, allowing users to switch directly to their desired mode with a single key combination. For example:
Ctrl+Alt+1: Switch to 'Silent' mode
Ctrl+Alt+2: Switch to 'Balanced' mode
Ctrl+Alt+3: Switch to 'High Performance' mode

### Device and Model

Asus Flow X13

### Additional information.

The option to customize these keyboard shortcuts in the ghelpers settings would be an added advantage, allowing users to set their preferred key combinations.

**Comment by seerge** [comment]
@pynbbz you clearly didn't check readme
https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings

**Comment by pynbbz** [comment]
Hi, I'm sorry my issue might not have been clear. I would like to customize these shortcuts:
Ctrl + Shift + Alt + F16 - Silent
Ctrl + Shift + Alt + F17 - Balanced
Ctrl + Shift + Alt + F18 - Turbo
I'm trying to automate switching between these profiles using AutoHotkey, but F16,F17,F18 are not being recognized. if possible, it'd be great to be able to change those to something like:
Ctrl + Shift + Alt + F10 - Silent
Ctrl + Shift + Alt + F11 - Balanced
Ctrl + Shift + Alt + F12 - Turbo

**Comment by seerge** [comment]
@pynbbz I don't want reserve "real" keys for such exotic bindings to be honest. 
But you can emit absolutely anything using Autohotkey
