### ISSUE TITLE
Asus Tianxuan 1 temperature control abnormal

### ISSUE THREAD

**Issue by 15060501338** [seerge/g-helper#1994]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When using the built-in GPU and the external GPU, the temperature is similar, but the CPU temperature is abnormal, and the difference between the two is 35 degrees, which leads to the abnormal fan scheduling.
![accbbdaeccec595e8c0001765890628](https://github.com/seerge/g-helper/assets/124861862/a0fcbf88-7758-414b-8970-ecc80fada9a0)
Personal guess: to know this cpu comes with a core display, core display temperature and gpu temperature similar, but in the same core cpu temperature and how the core display is so much different

### How to reproduce the bug?

Normal use of the computer, running load tasks

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14079309/log.txt)

### Device and Model

ASUS TUF Gaming A15 FA506IV

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.148.0

### OS

windows11 22H2

**Comment by seerge** [comment]
@15060501338 hello, I have absolutely no idea. 
How is this is connected to G-Helper ?
