### ISSUE TITLE
PowerLimit CPU 80W when "apply Curve" is check. 

### ISSUE THREAD

**Issue by Kikimahe** [seerge/g-helper#1997]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi, 

**Without applying a CPU limit**, if "apply curve" is checked, this results in a fixed limit PL1 & PL2 to 80W.

This is written in the log and confirmed by Cinebench and Hwinfo.
```
01/29/2024 2:34:23 PM: PowerLimit Fix A0 = 80: OK
01/29/2024 2:34:23 PM: PowerLimit Fix A3 = 80: OK
```

### How to reproduce the bug?

- Open Fan & Power
- Just check the “apply curve” box on any silent, balanced or Turbo
- The CPU is limited to 80W.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14085102/log.txt)

### Device and Model

TUF F17 (2022) FX707ZM

### Additional information.

Test Cinebench : 
![01](https://github.com/seerge/g-helper/assets/142881210/cbadfc5c-0fd1-4e85-a47c-728c74e57af9)

### Armoury Crate

Never installed

### Asus Services

None

### Version

0.148

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Kikimahe hello,

This is actually intentional :)

Your model (707 / 507 ) series have a bit bugged behavior. And when you apply only custom fan curve (but not a power), they would set power limits to 5W (or something ridiculously low).

In Armoury's manual mode - you set both fans + power limits at the same time as well (you can't set only one)

So app sets 80w as default then, as a workaround

https://github.com/seerge/g-helper/blob/e04c4cd46fec4785595cb53e05583eda6d360739/app/Mode/ModeControl.cs#L168

**Comment by seerge** [comment]
So this is not a bug, this is a feature :) and workaround.

**Comment by Kikimahe** [comment]
Thanks Seerge!

From the beginning I told myself that there was something that was not working correctly with these 2 check boxes. :)

I understand better now :
Apply limit + Apply curve must be checked for CPU limit work
Apply Curve is stuck at 80W if you do not apply a CPU limit with the correct CPU values (90/115 for mine).

The 507/707 models are strange unfortunately. :)

**Comment by seerge** [comment]
@Kikimahe yes, if you want different power limits AND a custom fan curve - you need to set them both.

All other devices don't have this hiccup tho :)

**Comment by Kikimahe** [comment]
Another thing about the curve. :

Who displays the endpoints of the curve for **factory settings**? You and Ghelper? The firmware? The Bios?

I tested Cinebench+Hwinfo in silent mode :

- My silence mode curve indicates that the CPU fan must go to 2200 RPM at 63°C (factory setting)
- At 63°C the fan don't move and the bios only starts the fan at 85°C.

I know the bios does what it wants. :)
But I don't understand what the factory settings endpoints are for, if the bios does something else.

**Comment by seerge** [comment]
@Kikimahe if you mean where G-Helper gets that fan curve, that it shows as "factory defaults" ? It gets it from BIOS for each mode. But it's not applied and has no effect until "apply" is checked.

But based on my observations, mostly this curves look adequate and very similar to how fans actually behave in default state (i.e. w/o any custom curve being set). But not always :)

**Comment by Kikimahe** [comment]
No there was no quick spike in silent mode. The increase in temperature was slow and gradual each time (several test).

I won't bother you anymore.
Thanks again for all these explanations. :)
Good evening.
