### ISSUE TITLE
Anime Matrix with an option to show battery charge percentage and charging status

### ISSUE THREAD

**Issue by keepitupsid** [seerge/g-helper#1998]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

At present there's no option to set the battery status in the Anime Matrix dropdown. 
Also, It would be wise to show them as checkboxes and display multiple pieces of information.  

### Describe the solution you'd like

1. Add a - Battery Status option in the Anime Matrix drop down.
2. Change the selection type to Multiselect Checkbox instead of dropdowns. 

### Device and Model

Asus Zephyrus G14 401QM

**Comment by seerge** [comment]
@keepitupsid hello,

What is practical sense of this? As when you are on battery, it's generally better to turn it off completely :) and when you are plugged in you don't care about battery percentage :)

**Comment by keepitupsid** [comment]
Well, anime matrix itself has little or no practical use :)
With that in mind, getting a snapshot of system status (specially when not plugged in, lid closed) could be of some use. Moreover, allowing multiple selection turns it into a custom and comprehensive tool.

**Comment by seerge** [comment]
@keepitupsid when lid is closed and your laptop is usually sleeping, it's impossible to update matrix. As windows suspends everything running.

**Comment by keepitupsid** [comment]
Some gap here. I'm referring to cases when a system is streaming content, plugged in to an external monitor, actively generating/rendering video, active downloads or similar scenarios. Basically when lid is closed - 'do nothing' setting. System state (idle/active application etc) would be another information of use here.

**Comment by seerge** [comment]
@keepitupsid but if you are plugged in, why do you need to know battery charge? :) G-Helper is not monitoring anyhow what apps you are running, etc. So to show that it needs to start doing that in a first place, which is a lot of work a very questionable outcome.

As I remember, AC was just showing battery next to the clock, i can add something like that there, I just don't see sense, and don't really want to overload it.

**Comment by keepitupsid** [comment]
Understandable, keeping the helper swift is a priority and I'll leave the quantification of work to you. I'm sure it is a lot as you said so.

PS: I was refering (in previous comments) ***NOT plugged in, lid closed***  state :)

**Comment by seerge** [comment]
@keepitupsid for NOT plugged in, lid closed - laptop is usually sleeping as I have mentioned. All apps are suppressed by windows, so it's simply impossible to update matrix. 

Then I'm closing this as not planned for now :) Thanks for an idea anyway
