### ISSUE TITLE
TUF gaming M3 Gen2 buggy lighting

### ISSUE THREAD

**Issue by CJ4lyf** [seerge/g-helper#1999]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Welp basically i have a Asus TUF gaming m3 gen II and a asus tuf f15 [12700H, rtx 4060 mobile], when i try to set the lighting thru G-helper [v0.148.0] it makes the mouse RGB very dim [the lighting slider is turned way to the right, mind], and then armoury crate doesn't recognize it [i don't run ghelper and armoury crate together, i installed one and uninstalled the other].

### How to reproduce the bug?

1. Open G-helper
2. Click on Peripherals
3. Try to set the lighting to any setting possible

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14092852/log.txt)

### Device and Model

Asus TUF gaming F15

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.148.0

### OS

Windows 11

**Comment by CJ4lyf** [comment]
If there's no fix, please do tell if there's a method to atleast unsync the peripheral

**Comment by seerge** [comment]
May be @IceStormNG knows? :)

**Comment by IceStormNG** [comment]
So it is just the brightness being super dimm, but everything else works fine?
Please try this build here: 
[GHelper.zip](https://github.com/seerge/g-helper/files/14099983/GHelper.zip)

**Comment by IceStormNG** [comment]
Great. I will push the changes for the next update then.

**Comment by seerge** [comment]
Merged in LED brightness fix for TuF M3 Gen II #2004
