### ISSUE TITLE
[Bug] Turbo mode randomly switched to Silent

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#20]
Hi, the app randomly switched the Turbo mode to the Silent with no obvious reasons or error messages in log.

Win 11 22h2, GHelper 0.9

**Comment by seerge** [comment]
May be you pressed Rog (M4) or FN+F5 ? it cycles through performance modes

**Comment by ke1ne** [comment]
> May be you pressed Rog (M4) or FN+F5 ? it cycles through performance modes

Definitely, no, used mouse to switch.

**Comment by seerge** [comment]
can your check if this still happens with latest version ?

**Comment by ke1ne** [comment]
> can your check if this still happens with latest version ?

Sorry, I had to go back to AC and can't delete it again because of possible issues. Hope it "just works" now.
Thank you for your work.

**Comment by seerge** [comment]
Ok 👍
