### ISSUE TITLE
add Chinese and more language

### ISSUE THREAD

**Issue by lswlc33** [seerge/g-helper#200]
As is well known, Asus laptops are widely used in China， You did a great job on this project， I really like it，  I spent some time translate a Chinese version of the software， These translations are not machine translation, but my manual translation. Can be used directly， But on my computer, the software does not display all the interfaces, so there may be a little problem，i haven't learnt C#，so i just change the  context and it runs well on my laptop  
[this is the link of my vision](https://github.com/lswlc33/g-helper)

**Comment by seerge** [comment]
Hello, that's cool. But currently app doesn't have multilingual support :) your changes will simply replace all english text with chinese.

I may consider adding multilinguality later, but after UI will stabilize, and it will be clear what needs to be translated.

**Comment by seerge** [comment]
@lswlc33 i'm now working on some translations and moved all texts into a separate resource files.
https://github.com/seerge/g-helper/blob/main/app/Properties/Strings.zh.resx here is Chinese (translated with Google).

If you want you can check it and post here a corrected version :)

**Comment by hkaancaliskan** [comment]
That’s great, i’ll check it out when i get home :)

**Comment by seerge** [comment]
And Spanish https://github.com/seerge/g-helper/blob/main/app/Properties/Strings.es.resx @marcelomijas ? :)

**Comment by marcelomijas** [comment]
@seerge I will work on it today ;)

**Comment by seerge** [comment]
> @seerge I could not find the values for translating this:
> 

I didn’t include that to keep sensors section short

**Comment by seerge** [comment]
@lswlc33 just fixed that (visual studio keeps replacing resources with old texts by some reason)
