### ISSUE TITLE
Keyboard backight blinking on Asus TUF Dash F15 2022

### ISSUE THREAD

**Issue by MaxManus** [seerge/g-helper#2002]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi, I have been having this problem for a few months. My laptop keyboard does not keep the backlight on when I have enabled "static mode" on Laptop keyboard settings. It just keeps blinking.
Please find my video recording here : https://www.youtube.com/watch?v=LH8O_H41tXU

Also, it is impossible to turn the keyboard backlight on via Fn shortcut keys when I have disabled the keyboard backlight in "Awake mode" (inside extra settings)
[log - Copy.txt](https://github.com/seerge/g-helper/files/14100044/log.-.Copy.txt)

I tried with and without MyAsus app installed as well. It works fine with just MyAsus running without G-helper.

### How to reproduce the bug?

Turn on the laptop -and it's there.

 

### Logs

[log - Copy.txt](https://github.com/seerge/g-helper/files/14100160/log.-.Copy.txt)

### Device and Model

ASUS TUF Dash F15 FX517ZE

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.148.0

### OS

Windows 11 Version 23H2

**Comment by seerge** [comment]
@MaxManus hello,

It's known hiccup on TUF models :) when windows goes to sleep and then wakes up, laptop's BIOS things it's still sleeping.

Your blinking is actually sleeping animation (you can turn it off from ``Extra`` settings). But I would advice just to reboot :)

I can't do anything about, as it's not cause by the app.

**Comment by seerge** [comment]
@MaxManus please, keep in mind that blinking is not the only "effect" of this sleep/wakeup BIOS thing. 
It can be also controlling fans differently (at least I remember hearing it from someone here). 

So I would still advice to restart if it happens.

Anyway. Good luck

**Comment by seerge** [comment]
@MaxManus P.S. I don't think MyASUS has something to do with it.

But if think that Asus Optimisation Service (stopped / started from ``Extra``) helps with that somehow, you can keep it running. It doesn't harm anyhow :)
