### ISSUE TITLE
Display which GPU is active

### ISSUE THREAD

**Issue by xcaliber93** [seerge/g-helper#2005]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

N/A

### Describe the solution you'd like

![image](https://github.com/seerge/g-helper/assets/36753272/769ab09a-e0c9-46d8-940c-958f0c13dad5)
perhaps have the app display which GPU(s) is/are active in the GPU setting

### Device and Model

GA503QR

**Comment by seerge** [comment]
@xcaliber93 hello,

It's already shown in the same line iGPU + dGPU.

As for what app uses which GPU, is purely up to those apps and windows to decide. iGPU is always active no matter what next to that :)
