### ISSUE TITLE
Doesn't remember keyboard backlight preferences, and always needs one up before down

### ISSUE THREAD

**Issue by monsieurpooh** [seerge/g-helper#2006]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

On startup, keyboard backlight is always on. When trying to lower brightness, it doesn't turn off. It only turns off after increasing brightness and then lowering again.

### How to reproduce the bug?

Set GHelper to start on startup. Turn off backlight. Restart computer

### Logs

1/30/2024 9:08:25 PM: ------------
1/30/2024 9:08:25 PM: App launched: ROG Zephyrus G14 GA402XV_GA402XV :0.148.0.0en-US
1/30/2024 9:08:28 PM: NVIDIA GeForce RTX 4060 Laptop GPU
1/30/2024 9:08:29 PM: CPU: 9 - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics      - AMD64 Family 25 Model 116 Stepping 1
1/30/2024 9:08:29 PM: USB Version: 1049 4.19
1/30/2024 9:08:29 PM: AutoSetting for Online
1/30/2024 9:08:29 PM: Optimization service is running
1/30/2024 9:08:29 PM: Mode = 0 : OK
1/30/2024 9:08:29 PM: Power Mode 00000000-0000-0000-0000-000000000000:OK
1/30/2024 9:08:29 PM: Eco flag : 0
1/30/2024 9:08:29 PM: Mux flag : 1
1/30/2024 9:08:29 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
1/30/2024 9:08:29 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
1/30/2024 9:08:29 PM: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
1/30/2024 9:08:29 PM: AuraMode: AuraStatic
1/30/2024 9:08:29 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
1/30/2024 9:08:29 PM: USB 19B6: 5D-B4
1/30/2024 9:08:29 PM: USB 19B6: 5D-B5-00-00-00
1/30/2024 9:08:29 PM: Init 19B6: 5D-B9
1/30/2024 9:08:29 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
1/30/2024 9:08:29 PM: Init 19B6: 5D-05-20-31-00-1A
1/30/2024 9:08:30 PM: Monitor Power On
1/30/2024 9:08:30 PM: Auto 19B6: 5D-BA-C5-C4-01
1/30/2024 9:08:31 PM: Latest version 0.148.0.0
1/30/2024 9:08:42 PM: Running eco command 1
1/30/2024 9:08:44 PM: Display configuration changed.
1/30/2024 9:08:44 PM: GPUEco = 1 : OK
1/30/2024 9:08:45 PM: Eco flag : 1
1/30/2024 9:08:45 PM: Mux flag : 1
1/30/2024 9:08:45 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
1/30/2024 9:08:45 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
1/30/2024 9:08:45 PM: ScreenOverdrive = 1 : OK
1/30/2024 9:08:49 PM: Running eco command 0
1/30/2024 9:08:50 PM: GPUEco = 0 : OK
1/30/2024 9:08:51 PM: Eco flag : 0
1/30/2024 9:08:51 PM: Mux flag : 1
1/30/2024 9:08:51 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
1/30/2024 9:08:51 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
1/30/2024 9:08:51 PM: ScreenOverdrive = 1 : OK
1/30/2024 9:08:54 PM: NVIDIA GeForce RTX 4060 Laptop GPU
1/30/2024 9:08:59 PM: Mode = 2 : OK
1/30/2024 9:08:59 PM: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
1/30/2024 9:09:04 PM: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
1/30/2024 9:09:04 PM: GET CLOCK LIMIT: NVAPI_GPU_NOT_POWERED
1/30/2024 9:09:07 PM: Mode = 1 : OK
1/30/2024 9:09:07 PM: Power Mode ded574b5-45a0-4f42-8737-46345c09c238:OK
1/30/2024 9:09:09 PM: Mode = 0 : OK
1/30/2024 9:09:10 PM: Power Mode 00000000-0000-0000-0000-000000000000:OK
1/30/2024 9:09:12 PM: Mode = 2 : OK
1/30/2024 9:09:12 PM: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
1/30/2024 9:09:16 PM: Mode = 0 : OK
1/30/2024 9:09:16 PM: Power Mode 00000000-0000-0000-0000-000000000000:OK
1/30/2024 9:09:38 PM: Design Capacity: 76000mWh, Full Charge Capacity: 76478mWh, Health: 1.0062894736842105263157894737%
1/30/2024 9:09:44 PM: Varibright: 0,0
1/30/2024 9:09:44 PM: Hibernate after 2147483647
1/30/2024 9:10:57 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
1/30/2024 9:10:57 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
1/30/2024 9:10:59 PM: Screen = 165Hz : OK
1/30/2024 9:10:59 PM: ScreenOverdrive = 1 : OK
1/30/2024 9:10:59 PM: Display configuration changed.
1/30/2024 9:11:08 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
1/30/2024 9:11:08 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
1/30/2024 9:11:10 PM: Screen = 60Hz : OK
1/30/2024 9:11:10 PM: ScreenOverdrive = 0 : OK
1/30/2024 9:11:10 PM: Display configuration changed.
1/30/2024 9:11:19 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
1/30/2024 9:11:19 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
1/30/2024 9:11:21 PM: Screen = 165Hz : OK
1/30/2024 9:11:21 PM: ScreenOverdrive = 1 : OK
1/30/2024 9:11:21 PM: Display configuration changed.
1/30/2024 9:11:37 PM: WMI event 87
1/30/2024 9:11:37 PM: WMI event 123
1/30/2024 9:11:38 PM: AutoSetting for Offline
1/30/2024 9:11:38 PM: Optimization service is running
1/30/2024 9:11:38 PM: Mode = 0 : OK
1/30/2024 9:11:38 PM: Battery Saver detected
1/30/2024 9:11:38 PM: Eco flag : 0
1/30/2024 9:11:38 PM: Mux flag : 1
1/30/2024 9:11:38 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
1/30/2024 9:11:38 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
1/30/2024 9:11:39 PM: Screen = 60Hz : OK
1/30/2024 9:11:39 PM: ScreenOverdrive = 0 : OK
1/30/2024 9:11:39 PM: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
1/30/2024 9:11:39 PM: AuraMode: AuraStatic
1/30/2024 9:11:39 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
1/30/2024 9:11:39 PM: USB 19B6: 5D-B4
1/30/2024 9:11:39 PM: USB 19B6: 5D-B5-00-00-00
1/30/2024 9:11:39 PM: Init 19B6: 5D-B9
1/30/2024 9:11:39 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
1/30/2024 9:11:39 PM: Init 19B6: 5D-05-20-31-00-1A
1/30/2024 9:11:39 PM: Display configuration changed.
1/30/2024 9:11:40 PM: Auto 19B6: 5D-BA-C5-C4-01
1/30/2024 9:11:48 PM: WMI event 88
1/30/2024 9:11:48 PM: WMI event 123
1/30/2024 9:11:48 PM: AutoSetting for Online
1/30/2024 9:11:48 PM: Optimization service is running
1/30/2024 9:11:48 PM: Mode = 0 : OK
1/30/2024 9:11:48 PM: Eco flag : 0
1/30/2024 9:11:48 PM: Mux flag : 1
1/30/2024 9:11:48 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
1/30/2024 9:11:48 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
1/30/2024 9:11:48 PM: Screen = 165Hz : OK
1/30/2024 9:11:48 PM: ScreenOverdrive = 1 : OK
1/30/2024 9:11:49 PM: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
1/30/2024 9:11:49 PM: AuraMode: AuraStatic
1/30/2024 9:11:49 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
1/30/2024 9:11:49 PM: USB 19B6: 5D-B4
1/30/2024 9:11:49 PM: USB 19B6: 5D-B5-00-00-00
1/30/2024 9:11:49 PM: Init 19B6: 5D-B9
1/30/2024 9:11:49 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
1/30/2024 9:11:49 PM: Init 19B6: 5D-05-20-31-00-1A
1/30/2024 9:11:49 PM: Display configuration changed.
1/30/2024 9:11:50 PM: Auto 19B6: 5D-BA-C5-C4-01
1/30/2024 9:11:56 PM: WMI event 87
1/30/2024 9:11:56 PM: WMI event 123
1/30/2024 9:11:57 PM: AutoSetting for Offline
1/30/2024 9:11:57 PM: Optimization service is running
1/30/2024 9:11:57 PM: Mode = 0 : OK
1/30/2024 9:11:57 PM: Battery Saver detected
1/30/2024 9:11:57 PM: Eco flag : 0
1/30/2024 9:11:57 PM: Mux flag : 1
1/30/2024 9:11:57 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
1/30/2024 9:11:57 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
1/30/2024 9:11:58 PM: Screen = 60Hz : OK
1/30/2024 9:11:58 PM: ScreenOverdrive = 0 : OK
1/30/2024 9:11:58 PM: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
1/30/2024 9:11:58 PM: AuraMode: AuraStatic
1/30/2024 9:11:58 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
1/30/2024 9:11:58 PM: USB 19B6: 5D-B4
1/30/2024 9:11:58 PM: USB 19B6: 5D-B5-00-00-00
1/30/2024 9:11:58 PM: Init 19B6: 5D-B9
1/30/2024 9:11:58 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
1/30/2024 9:11:58 PM: Init 19B6: 5D-05-20-31-00-1A
1/30/2024 9:11:58 PM: Display configuration changed.
1/30/2024 9:11:59 PM: Auto 19B6: 5D-BA-C5-C4-01
1/30/2024 9:12:05 PM: WMI event 88
1/30/2024 9:12:05 PM: WMI event 123
1/30/2024 9:12:06 PM: AutoSetting for Online
1/30/2024 9:12:06 PM: Optimization service is running
1/30/2024 9:12:06 PM: Mode = 0 : OK
1/30/2024 9:12:06 PM: Eco flag : 0
1/30/2024 9:12:06 PM: Mux flag : 1
1/30/2024 9:12:06 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
1/30/2024 9:12:06 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
1/30/2024 9:12:07 PM: Screen = 165Hz : OK
1/30/2024 9:12:07 PM: ScreenOverdrive = 1 : OK
1/30/2024 9:12:08 PM: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
1/30/2024 9:12:08 PM: AuraMode: AuraStatic
1/30/2024 9:12:08 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
1/30/2024 9:12:08 PM: USB 19B6: 5D-B4
1/30/2024 9:12:08 PM: USB 19B6: 5D-B5-00-00-00
1/30/2024 9:12:08 PM: Init 19B6: 5D-B9
1/30/2024 9:12:08 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
1/30/2024 9:12:08 PM: Init 19B6: 5D-05-20-31-00-1A
1/30/2024 9:12:08 PM: Display configuration changed.
1/30/2024 9:12:09 PM: Auto 19B6: 5D-BA-C5-C4-01
1/30/2024 9:18:53 PM: Monitor Dimmed
1/30/2024 9:19:09 PM: Monitor Power Off
1/30/2024 9:19:09 PM: Backlight 19B6: 5D-BA-C5-C4-00
1/30/2024 9:23:26 PM: Monitor Power On
1/30/2024 9:23:26 PM: AutoSetting for Online
1/30/2024 9:23:26 PM: Optimization service is running
1/30/2024 9:23:26 PM: Mode = 0 : OK
1/30/2024 9:23:26 PM: Eco flag : 0
1/30/2024 9:23:26 PM: Mux flag : 1
1/30/2024 9:23:26 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
1/30/2024 9:23:26 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
1/30/2024 9:23:26 PM: Screen = 165Hz : OK
1/30/2024 9:23:26 PM: ScreenOverdrive = 1 : OK
1/30/2024 9:23:26 PM: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
1/30/2024 9:23:26 PM: AuraMode: AuraStatic
1/30/2024 9:23:26 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
1/30/2024 9:23:26 PM: USB 19B6: 5D-B4
1/30/2024 9:23:26 PM: USB 19B6: 5D-B5-00-00-00
1/30/2024 9:23:26 PM: Init 19B6: 5D-B9
1/30/2024 9:23:26 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
1/30/2024 9:23:26 PM: Init 19B6: 5D-05-20-31-00-1A
1/30/2024 9:23:27 PM: Auto 19B6: 5D-BA-C5-C4-01
1/30/2024 9:30:11 PM: Monitor Dimmed
1/30/2024 9:30:27 PM: Monitor Power Off
1/30/2024 9:30:27 PM: Backlight 19B6: 5D-BA-C5-C4-00
1/30/2024 9:40:27 PM: Monitor Power On
1/30/2024 9:40:27 PM: AutoSetting for Online
1/30/2024 9:40:27 PM: Optimization service is running
1/30/2024 9:40:27 PM: Mode = 0 : OK
1/30/2024 9:40:27 PM: Eco flag : 0
1/30/2024 9:40:27 PM: Mux flag : 1
1/30/2024 9:40:27 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
1/30/2024 9:40:27 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
1/30/2024 9:40:27 PM: Screen = 165Hz : OK
1/30/2024 9:40:27 PM: ScreenOverdrive = 1 : OK
1/30/2024 9:40:27 PM: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
1/30/2024 9:40:27 PM: AuraMode: AuraStatic
1/30/2024 9:40:27 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
1/30/2024 9:40:27 PM: USB 19B6: 5D-B4
1/30/2024 9:40:27 PM: USB 19B6: 5D-B5-00-00-00
1/30/2024 9:40:27 PM: Init 19B6: 5D-B9
1/30/2024 9:40:27 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
1/30/2024 9:40:27 PM: Init 19B6: 5D-05-20-31-00-1A
1/30/2024 9:40:28 PM: Auto 19B6: 5D-BA-C5-C4-01
1/30/2024 9:40:56 PM: WMI event 197
1/30/2024 9:40:56 PM: WMI event 197
1/30/2024 9:40:57 PM: WMI event 197
1/30/2024 9:41:04 PM: WMI event 196
1/30/2024 9:41:04 PM: WMI event 196
1/30/2024 9:41:04 PM: WMI event 196
1/30/2024 9:41:04 PM: WMI event 196
1/30/2024 9:41:05 PM: WMI event 197
1/30/2024 9:41:06 PM: WMI event 197
1/30/2024 9:41:06 PM: WMI event 197
1/30/2024 9:41:06 PM: WMI event 197
1/30/2024 9:41:06 PM: WMI event 197
1/30/2024 9:41:06 PM: WMI event 197
1/30/2024 9:41:06 PM: WMI event 197
1/30/2024 9:41:07 PM: WMI event 196
1/30/2024 9:41:08 PM: WMI event 196
1/30/2024 9:41:08 PM: WMI event 196
1/30/2024 9:41:08 PM: WMI event 196
1/30/2024 9:41:08 PM: WMI event 196
1/30/2024 9:41:08 PM: WMI event 196
1/30/2024 9:41:08 PM: WMI event 196
1/30/2024 9:41:09 PM: WMI event 197
1/30/2024 9:41:09 PM: WMI event 197
1/30/2024 9:41:09 PM: WMI event 197
1/30/2024 9:41:09 PM: WMI event 197
1/30/2024 9:41:09 PM: WMI event 197
1/30/2024 9:41:09 PM: WMI event 197
1/30/2024 9:48:59 PM: WMI event 124
1/30/2024 9:49:01 PM: WMI event 124
1/30/2024 9:49:50 PM: WMI event 107
1/30/2024 9:49:52 PM: WMI event 107
1/30/2024 9:50:04 PM: WMI event 56
1/30/2024 10:04:09 PM: Forcing Standard Mode on shutdown / hibernation
1/30/2024 10:05:57 PM: ------------
1/30/2024 10:05:57 PM: App launched: ROG Zephyrus G14 GA402XV_GA402XV :0.148.0.0en-US
1/30/2024 10:05:59 PM: NVIDIA GeForce RTX 4060 Laptop GPU
1/30/2024 10:06:01 PM: CPU: 9 - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics      - AMD64 Family 25 Model 116 Stepping 1
1/30/2024 10:06:01 PM: USB Version: 1049 4.19
1/30/2024 10:06:01 PM: AutoSetting for Offline
1/30/2024 10:06:01 PM: Optimization service is running
1/30/2024 10:06:01 PM: Mode = 0 : OK
1/30/2024 10:06:01 PM: Eco flag : 0
1/30/2024 10:06:01 PM: Mux flag : 1
1/30/2024 10:06:01 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
1/30/2024 10:06:01 PM: \\?\DISPLAY#TMX1401#5&1f08c561&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
1/30/2024 10:06:01 PM: Screen = 60Hz : OK
1/30/2024 10:06:01 PM: ScreenOverdrive = 0 : OK
1/30/2024 10:06:01 PM: USB 19B6: 5D-BD-01-FF-1E-FF-FF-FF
1/30/2024 10:06:01 PM: AuraMode: AuraStatic
1/30/2024 10:06:01 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
1/30/2024 10:06:01 PM: USB 19B6: 5D-B4
1/30/2024 10:06:01 PM: USB 19B6: 5D-B5-00-00-00
1/30/2024 10:06:01 PM: Init 19B6: 5D-B9
1/30/2024 10:06:01 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
1/30/2024 10:06:01 PM: Init 19B6: 5D-05-20-31-00-1A
1/30/2024 10:06:01 PM: Monitor Power On
1/30/2024 10:06:02 PM: Auto 19B6: 5D-BA-C5-C4-01
1/30/2024 10:06:38 PM: WMI event 197
1/30/2024 10:06:39 PM: WMI event 197
1/30/2024 10:06:42 PM: WMI event 196
1/30/2024 10:06:43 PM: WMI event 197
1/30/2024 10:06:44 PM: WMI event 196
1/30/2024 10:06:44 PM: WMI event 197
1/30/2024 10:06:45 PM: WMI event 197
1/30/2024 10:06:45 PM: WMI event 197

### Device and Model

Zephyrus G14 2023

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

0.148.0

### OS

Windows 11

**Comment by seerge** [comment]
@monsieurpooh hello, you have Asus Optimization Service running, it also sets own backlight levels.

```
1/30/2024 9:08:29 PM: Optimization service is running
```

You need to stop it from ``Extra`` screen, and then only G-Helper will set backlight :)
