### ISSUE TITLE
BIOS version read incorrectly

### ISSUE THREAD

**Issue by xB-r** [seerge/g-helper#2009]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

In the updates section, it shows the wrong bios version than the one i have installed.
I have bios version 312 but it shows 310.
![image](https://github.com/seerge/g-helper/assets/84455199/05e45158-c952-4509-ba22-4d4f26e0ae9e)

### How to reproduce the bug?

Not sure if its exists on every model. But go to Ghelper > updates and wrong version is shown

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14114306/log.txt)

### Device and Model

Asus ROG zephyrus m16 GU604VI

### Additional information.

![image](https://github.com/seerge/g-helper/assets/84455199/cce89ca0-e9c7-44ce-9c53-4cf570e8f489)
![image](https://github.com/seerge/g-helper/assets/84455199/34fcc106-148e-4292-b0ca-81baaf6f5158)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.148

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@xB-r hello,

It just mirrors official ASUS website for your model https://rog.asus.com/laptops/rog-zephyrus/rog-zephyrus-m16-2023-series/helpdesk_bios/ 

And latest version there is 310
<img width="1392" alt="Screenshot 2024-01-31 at 17 22 25" src="https://github.com/seerge/g-helper/assets/5920850/f88156cf-4917-44d0-acbb-378723d3b007">

As far as I remember Asus has published 312 BIOS and then removed it by some reason :)

**Comment by xB-r** [comment]
oh ok, that makes sense, is version 312 faulty due to its removal?

**Comment by seerge** [comment]
@xB-r i don't know :) I can imagine they had some reasons to pull it off tho
