### ISSUE TITLE
V0.151 :  Error atiadlxx.dl in log file

### ISSUE THREAD

**Issue by Kikimahe** [seerge/g-helper#2010]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

With V0.151 there is a *.dll error which appears in the log when you click on `extra.`

`01/31/2024 9:10:37 PM: Unable to load DLL 'atiadlxx.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)`

### How to reproduce the bug?

Start Ghelper
Check the log: no error.
Click on extra
Check the log: the atiadlxx.dll error appears.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14116890/log.txt)

### Device and Model

TUF F17 (2022) FX707ZM

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.151

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Kikimahe hello,

That's normal :) App checks for both Nvidia / AMD GPU on start. I have just added a bit of logging when it can't connect to them (which happens in your case since you have Intel device) 

There is nothing to fix here :)

**Comment by Kikimahe** [comment]
You probably mean "what happens in your case since you have an **AMD** device"

My iGpu is Intel and dGPU Nvidia. :)

**Comment by seerge** [comment]
@Kikimahe i mean it (error) happens in your case since you have Intel (and not AMD)

There is a special checkbox called "AMD Varibright" (to disable terrible AMD color management on battery) under ``Extra``, so app checks for it via driver when you open that screen

**Comment by Kikimahe** [comment]
Oups, yes ! 
Je suis fatigué et je mal lu.
