### ISSUE TITLE
[Feature request] Add ability to remap secondary functions

### ISSUE THREAD

**Issue by ethan-br** [seerge/g-helper#2016]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I have a version of the G14 where the backlight controls are located on keys F2 and F3 but I would prefer to have different secondary functions in that place since I almost never use the backlight.

### Describe the solution you'd like

I would like to remap them to media keys like play/pause and next track and possibly rebind the backlight controls to secondary functions on my up and down arrow keys although I am not even sure if this is possible due to how the keyboard driver works.
Below is an example of my current keyboard and what I would like to rebind it to.

[Current keyboard](https://i.postimg.cc/7LMZHdwN/5177-Hn-Ssz-L-AC-SL1500.jpg)

[Rebindings](https://i.postimg.cc/0Qk2bnN1/51-Nu-Tc5ds-UL-AC-SL1000.jpg)

### Device and Model

Asus Zephyrus GA401QM

**Comment by seerge** [comment]
@ethan-br hello,

This is quite exotic request :) I intentionally don't want to overload app and it's UI with limitless options. You already can bind whole M-row of keys to anything you want in the app.

If you want to rebind anything else - you can just look into direction of Autohotkey or Sharpkeys.

For example you can bind ``Ctrl+F2/F3/F4`` to media keys (while ``FN+F2/F3/F4`` still doing backlight)

Good luck

**Comment by ethan-br** [comment]
Hi @seerge ,
I understand that my problem is very specific and expected it to be declined but could you let me know if what I want to do if even technically possible? If so, would you be willing to give me a few pointers should I decide to develop this myself?
I know this is sort of off topic but I would really appreciate it.
Thanks

**Comment by seerge** [comment]
@ethan-br easiest thing would be bind Ctrl + F or Shift + F keys with sharpeys as I explained above.

If you want to alter app purely for yourself you can modify code in this part
https://github.com/seerge/g-helper/blob/accb8e13d6e48ecd4ffe8ace22fa9753cf00d3cc/app/Input/InputDispatcher.cs#L665

Good luck

**Comment by ethan-br** [comment]
Hello again @seerge ,

Thank you for your response. 

I am currently trying to reverse engineer the code you linked above but I am not sure what the value of `EventID` corresponds to. I am trying to replace `197` with the code for PageDown and `196` with the code for PageDown but I tried the codes `34` and `33` which are the keycodes for PageDown and PageUp but those didn't seem to work.

You also commented in the code something about HID key-codes but I could not find any useful information on those.

I would appreciate any help you have in understanding this block of code.

Thanks

https://github.com/seerge/g-helper/blob/accb8e13d6e48ecd4ffe8ace22fa9753cf00d3cc/app/Input/InputDispatcher.cs#L629

**Comment by seerge** [comment]
@ethan-br hello, there is no need to reverse engineer anything. As code is open and published :)

You need to replace what app does for 196/197 code with something else, i.e. replace ``SetBacklight(-1);`` :)
