### ISSUE TITLE
Issue with "Keep GPU disabled on USB-C charger in Optimized mode" option

### ISSUE THREAD

**Issue by NatsuZoraKanata** [seerge/g-helper#2018]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Issue 1:
I have enabled both the "Keep GPU disabled on USB-C charger in Optimized mode" and "Optimized Mode" options. However, when I reconnect the barrel charger, the dGPU is not enabled automatically. I checked the logs and found that the BIOS reported a ChargerStatus of 0. This issue is similar to another one: https://github.com/seerge/g-helper/issues/1975
Issue 2:
I first used a USB C HUB with power delivery, then I plugged in the barrel charger, the dGPU did not activate. The log showed a ChargerStatus of 3 from the BIOS. I need the dGPU to enable automatically when it detects both type c charger and barrel charger at the same time.😊

### How to reproduce the bug?

1. Open up GHelper
2. Select Optimized under GPU Mode
3. Select "Keep GPU disabled on USB-C" under Extra
4. Unplug the laptop from AC charging
    ->dGPU gets disabled
5. Plug the laptop into a USB HUB with Power Delivery.
    ->dGPU did not start as expected
6. Plug the laptop into barrel charger
    ->dGPU did not start

### Logs

[log2.txt](https://github.com/seerge/g-helper/files/14143128/log2.txt)

### Device and Model

Asus TUF Gaming A15 - FA507XV

### Additional information.

1. Neither **_Asus Smart Display control_** or **_MyASUS_** were installed.
2. Display Mode under nvidia control panel is set to Optimus.

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.148.0

### OS

Windows 11 Enterprise 23H2 22631.3085

**Comment by seerge** [comment]
@NatsuZoraKanata @Quang-vip hello,

Oke, since it's at least two of you with same model who have similar situation. It looks like it's indeed specific to how it's done on your model, not just a hiccup of a single device.

I have added a small delay before checking for USB-C charger flag as @Quang-vip suggested

Try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14144935/GHelper.zip)

**Comment by NatsuZoraKanata** [comment]
@seerge Hi,
Thanks for your reply!
With the added delay, the automatic switching works fine in most cases. But occasionally it still doesn't work properly. Here is the failure log I captured.
```
2024/2/3 10:10:29: WMI event 88
2024/2/3 10:10:29: ChargerStatus: 0
2024/2/3 10:10:29: Eco flag : 1
2024/2/3 10:10:29: Mux flag : 1
2024/2/3 10:10:29: \\?\DISPLAY#BOE0B68#5&1824deba&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2024/2/3 10:10:29: \\?\DISPLAY#BOE0B68#5&1824deba&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2024/2/3 10:10:29: WMI event 123
2024/2/3 10:10:30: Screen = 165Hz : OK
```
[log-failed.txt](https://github.com/seerge/g-helper/files/14149420/log-failed.txt)
I increased the delay to 1s, I'm testing to see if it runs better with the added delay.
Are you considering increasing the delay? Or polling the charging status after plugging in the power?
Thanks!😊

**Comment by seerge** [comment]
@NatsuZoraKanata ok, try the build with 1second delay then

[GHelper.zip](https://github.com/seerge/g-helper/files/14151059/GHelper.zip)

**Comment by seerge** [comment]
@NatsuZoraKanata does it work ?

**Comment by NatsuZoraKanata** [comment]
@seerge Yes, as of now the one second delay I tested works fine
