### ISSUE TITLE
Keyboard Sleep / Delay issue?

### ISSUE THREAD

**Issue by xSimone** [seerge/g-helper#2019]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hello,

I have become aware that after 15 seconds the keyboard goes to sleep. The first key stroke takes 200ms to register, then the keyboard works without issue.

Sometimes, when the keyboard sleeps, attempting to wake the keyboard can fail, rendering the keyboard useless for sometimes up to a minute, until it finally decides to start working.

I've reported this online, and somebody said that it is possible Armoury Crate is meant to do something for the keyboard to stop this.

I have yet to test it, and will soon do so, but if this is true, could we please add something for G-Helper to stop the Keyboard from going to sleep?

Going to Device Manager and looking for Keyboard's "Power Management" does not exist, and is greyed out. 

### Describe the solution you'd like

Persistant Keyboard awakeness.

### Device and Model

Asus Scar 18 2023 and 2024 edition

**Comment by seerge** [comment]
@xSimone hello,

G-Helper is not putting your keyboard to sleep. What setting are you talking specifically ?

**Comment by xSimone** [comment]
Sorry, I maybe was not clear.

This is not a G-Helper bug, but was hoping G-Helper could fix by some sort of code to keep the Keyboard awake from going to sleep or standby. 

I timed it, seems like it does it after 5-6 seconds. After this, the first key press takes 1/5th of second to register. Bad for gaming. :<

**Comment by xSimone** [comment]
After hours research found it is a Human Interface Device which had a Power Management rule applied to it. Turned off. 

Everything works now. <3

**Comment by seerge** [comment]
@xSimone can you post a screenshot of that setting? I can add it to FAQ or Troubleshooting section.

So far closing this as resolved then :)
