### ISSUE TITLE
M4 key missing in G834 (strix scar 18 2023) model

### ISSUE THREAD

**Issue by PixelFox3** [seerge/g-helper#2022]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

My laptop has 5 macro keys, but G-helper skips the M4 key.
<img width="254" alt="185012" src="https://github.com/seerge/g-helper/assets/50619590/f57d9c9c-6829-487f-8ac1-d1a74911d62e">

### How to reproduce the bug?

Have an asus laptop with 5 macro keys
Open G-helper aditional settings
Watch the missing M4 key binding

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14152409/log.txt)

### Device and Model

strix scar 18 2023 G834

### Armoury Crate

Never installed

### Asus Services

None

### Version

0.151.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@PixelFox3 hello, I was answering this multiple times already

M4 and ``Fn+F5`` emit same keycode on Strix devices. This key is reserved for toggling profiles forward, and ``Shift + Fn + F5`` for toggling profiles backwards.

So It won't be bindable under ``Extra`` :)
