### ISSUE TITLE
TUF FA506IV/FX506IV Possible Support?

### ISSUE THREAD

**Issue by Astra060** [seerge/g-helper#2023]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Adding official support for the laptop

### Describe alternatives you've considered

Is this model compatible with other similar TUF Models

### Device and Model

FA506IV

**Comment by seerge** [comment]
@Astra060 why did you decide that your model is not supported?

**Comment by Astra060** [comment]
> @Astra060 why did you decide that your model is not supported?
> 
> P.S. Just checked comments of other users, there are people who have FA506 model and have G-Helper :)
> 
> Please keep in mind, that if some feature (like custom fan profiles or GPU modes) **was not available in AC** for you - it **won't be available** in G-Helper either, cause your hardware need to support that first.

My bad. Tnx
