### ISSUE TITLE
version 0.151 not working with Smart app control on in Windows (v0.148 works)

### ISSUE THREAD

**Issue by hmm-mm** [seerge/g-helper#2026]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

version 0.151 is supposedly blocked by Windows Smart app control

<img width="461" alt="Screenshot 2024-02-04 131304" src="https://github.com/seerge/g-helper/assets/131739165/3d87b46e-2e52-4c18-be46-7cece71fa920">

i could disable the smart app control but the version 0.148 works fine with it on. **so is the 0.151 release .exe missing a signature?**

### How to reproduce the bug?

from version 0.148, when prompted to update to version 0.151, click yes. and then after the update the app is blocked by windows

### Logs

not an in-app issue

### Device and Model

Zephyrus G15 GA503RM

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

151

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@hmm-mm neither of builds is signed. You clearly did not check FAQ 
https://github.com/seerge/g-helper/wiki/FAQ#windows-defender-marks-app-as-malware--virus

**Comment by hmm-mm** [comment]
i read FAQ, thats not the case here, windows did not mark it as malware/virus.

**Comment by seerge** [comment]
@hmm-mm it says that it's "unsafe" and not signed, which is the case for all builds.

**Comment by hmm-mm** [comment]
then how does v0.148 does not have this problem?

**Comment by seerge** [comment]
@hmm-mm what problem ? I get warning that app is not signed for any build.

What do you expect me to do ?

**Comment by hmm-mm** [comment]
nothing leave. i only wanted to know why windows doesn't block v.0148, but blocked v0.151

**Comment by seerge** [comment]
@hmm-mm because of windows own quirks and non-transparent ways for making such judgements

**Comment by hmm-mm** [comment]
alright, thankyou for replying and the app

**Comment by seerge** [comment]
Even Virustotal that is known for limitless false positives "likes" 0.151
https://www.virustotal.com/gui/url/c3504291bdf34d8d9cb273c9b13f66e0dee2f3903c672cd8c04b9f71d26eaff9
