### ISSUE TITLE
G-Helper periodically pops up on the taskbar with a red background (+1 #1232)

### ISSUE THREAD

**Issue by mcskatkat** [seerge/g-helper#2029]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I would like to +1 #1232, I have a similar issue but not related to typing in other apps.

Every certain (unknown) amount of time, G-Helper pops up on the taskbar with a red background. Usually this happens after I leave the computer idle for a while.
This is a nuisance because my taskbar is set to auto-hide, so if any app starts flashing it will unhide and obscure the lower part of other windows, forcing me to bring G-Helper to the foreground to "ack" the flashing.

95% of the time the laptop is not being physically used, it is connected to an external display, BT keyboard and BT mouse. Also usually with OEM power adapter connected. So I can't accidentally be touching any of the M1-M4 keys.

After reading #1232 now, I set the M4 key action to "Custom" with nothing under "action", just in case this would help. No idea yet if it resolves the problem.

Thanks for this great piece of SW, it is way better than the OEM!

### How to reproduce the bug?

1. Open G-Helper
2. Wait...
3. 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14156858/log.txt)

### Device and Model

ROG Zephyrus G14 GA401QM

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.148.0

### OS

Win 11 Pro 23H2

**Comment by seerge** [comment]
@mcskatkat hello, I didn't really get what you want me to do? It's not related to other issue you refer. 
I don't see a single entry in the app log saying that you have pressed M4 (Keycode ``56``)

If the app pops up in a taskbar it means you called it either with M4 or with external keyboard hotkey ``Ctrl + Shift + F12`` (that can be [disabled as well in config](https://github.com/seerge/g-helper/wiki/Power-user-settings#toggle-performance-mode-or-toggle-app-window-key-binding))

**Comment by mcskatkat** [comment]
I am not sure that I want you to do anything at this point other than be aware that this happens. There must be an underlying issue, and it may require a few more reports to pinpoint the source.
Perhaps it is not related to the other issue I referenced other than the symptom.

I know that I am not pressing M4. It is also very unlikely that I am pressing Ctrl + Shift + F12 as it is not part of my workflow on any app. I will disable that too anyway.
So I don't know what is causing G-Helper to pop up. But it does, I'm not imagining it ....
If there is nothing in the log indicating a reason, then just be aware that this is an issue for some people until there is enough information to find the cause.

**Comment by seerge** [comment]
@mcskatkat well, try to disable ``Ctrl + Shift + F12`` by adding to config

```
"keybind_app": 0,
```

It could be that some other apps running on your computer emit this hotkey by some reason, or something else clicks on G-Helper's sys-tray icon.

**Comment by mcskatkat** [comment]
Thanks, will do. 
FYI I have MS powertoys installed on this machine, just in case it correlates with something in the future, I've seen it mentioned in another issue while searching for "taskbar".

Keep up the good work, I hope everyone who enjoys this also donates.

**Comment by seerge** [comment]
@mcskatkat you can try this build, it will also write in a log if app gets triggered by Ctrl + Shift + F12.

But if yo have disabled it via config, it won't appear of course :)

[GHelper.zip](https://github.com/seerge/g-helper/files/14157219/GHelper.zip)

There is also a chance that powertoys do something to unhide windows, or send that command, and it's absolutely outside of my control

**Comment by seerge** [comment]
@mcskatkat did disabling that hotkey help you ?

**Comment by mcskatkat** [comment]
> @mcskatkat did disabling that hotkey help you ?

Sorry for the late reply, was sprinting at work...
No it did not solve the problem, I disabled ctrl+alt+F12 and the M4 key shortcuts, G-Helper still occasionally flashes red in the taskbar. I haven't tried the build you pointed me to. I will now.

Thanks for following up.
