### ISSUE TITLE
Requesting GPU power limit function

### ISSUE THREAD

**Issue by SauronSkywalker** [seerge/g-helper#2033]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Requesting GPU power limit function

### Describe the solution you'd like

I hope to add an option to limit the power consumption of GPUs according to the plan, which can be used to ensure that the working consumption of GPUs is within the limit in specific situations (such as using Nvidia RTX super resolution to enhance video without using too much power)

### Device and Model

ROG Zephyrus Duo 16  gx650py

**Comment by seerge** [comment]
Hello, that's not possible
