### ISSUE TITLE
Unable to run on win11 23H2

### ISSUE THREAD

**Issue by twilight0402** [seerge/g-helper#2034]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

After installing. net7, double-click on the exe program without any response
It's not folded, it's actually not running

### How to reproduce the bug?

null

### Logs

null

### Device and Model

天选5pro，amd r97940h, win11 pro

### Armoury Crate

Installed

### OS

win11 pro 23h2

**Comment by seerge** [comment]
@twilight0402 please post app own logs and logs from windows Event Viewer mentioning g-helper  as was asked
