### ISSUE TITLE
Anime Matrix Two Spots Bug

### ISSUE THREAD

**Issue by Thrakios** [seerge/g-helper#2036]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The anime matrix, when turned on through G-Helper in any setting either turns off, or only shows two bright dots.
Thank you for your assistance and the great support you've been providing.

### How to reproduce the bug?

1. Turn on GHelper
2. Turn on anime matrix in GHelper
3. Activate either Binary Banner, Rog Logo for two spots ; or Picture, Clock or Audio Visualiser for no light.
4. The issue takes place.

**Picture**: 
![thumbnail_image1](https://github.com/seerge/g-helper/assets/133026331/748948ea-1e5b-43c6-8d87-80559b4cbcd1)

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14182166/log.txt)

### Device and Model

G14 GA402XY

### Additional information.

I have tried both with Armoury Crate installed, uninstalled, and reinstalled (uninstall tool, then new installation).
I have also tried reinstalling Asus System Control Interface ; and the 40 seconds hardware reset.

### Armoury Crate

Installed

### Asus Services

7

### Version

0.151.0

### OS

Windows 11, up to date as of 6 February 2024

**Comment by seerge** [comment]
@Thrakios hello, is the Anime Matrix working in general on your device ? Can you set something in Armoury ? Cause looks like it's a broken hardware :)

**Comment by seerge** [comment]
@Thrakios well, if AC can't detect it even, it's probably hardware then :( 

You can try [hardware reset as explained here ](https://github.com/seerge/g-helper/wiki/Troubleshooting#hardware-reset--cmos-reset) 

Matrix is just a USB device in windows, it doesn't need any drivers or so, so reinstalling anything won't have any effect on it most probably

**Comment by seerge** [comment]
@Thrakios any updates on the matter? :)

**Comment by Thrakios** [comment]
A small update after some exchanges with ASUS support.
I thought you may find it interesting to understand a bit more how the Anime Matrix works.

The two dots is a software issue. It's something they encountered before, and seems like a problem indicator (they didn't confirm that point). The solution is installing firmware that only they have, and isn't available in the drivers list. So I'll have to resort to a RMA.

**Comment by seerge** [comment]
@Thrakios oke, thanks for an update.

It's a pity that you can't simply reset it or reinstall firmware directly anyhow :(
