### ISSUE TITLE
automatic keyboard light does not work after v0.48.

### ISSUE THREAD

**Issue by JackB111** [seerge/g-helper#204]
automatic keyboard light does not work after v0.48. Thats it.

**Comment by seerge** [comment]
I didn't change anything related to light over last builds, it doesn't turn off when you unplug or ?

**Comment by JackB111** [comment]
The keyboard light doesn't change or turn off when I unplug it, yeah.

**Comment by seerge** [comment]
And is the corresponding checkbox in "Extra" turned ON ?

**Comment by JackB111** [comment]
Yes

**Comment by seerge** [comment]
You can check https://github.com/seerge/g-helper/releases/tag/v0.49 
there i have added a log of keyboard backlit actions,

make sure to upload it here

**Comment by JackB111** [comment]
10.04.2023 12:48:47: WMI event 56
10.04.2023 12:48:59: WMI event 196
10.04.2023 12:49:00: WMI event 196
10.04.2023 12:49:00: WMI event 196
10.04.2023 12:49:00: WMI event 196
10.04.2023 12:49:04: Windows - Power Mode Changed
10.04.2023 12:49:04: AutoSetting for Offline
10.04.2023 12:49:04: BatteryLimit = 80 : OK
10.04.2023 12:49:04: PerformanceMode = 2 : OK
10.04.2023 12:49:04: FanCPU = 32-37-3C-3E-43-4B-59-64-00-00-00-1D-30-63-63-63 : OK
10.04.2023 12:49:04: FanGPU = 32-37-3B-3C-46-4B-59-64-00-00-00-0A-1D-63-63-63 : OK
10.04.2023 12:49:04: WMI event 123
10.04.2023 12:49:04: Boost 0
10.04.2023 12:49:04: Eco flag : 1
10.04.2023 12:49:04: Mux flag : 1
10.04.2023 12:49:04: Screen = 60Hz : OK
10.04.2023 12:49:04: ScreenOverdrive = 0 : OK
10.04.2023 12:49:05: WMI event 87
10.04.2023 12:49:05: USB-KB = 5D-BA-C5-C4-00
10.04.2023 12:49:05: PowerLimit A = 10 : OK
10.04.2023 12:49:10: Windows - Power Mode Changed
10.04.2023 12:49:10: AutoSetting for Online
10.04.2023 12:49:10: BatteryLimit = 80 : OK
10.04.2023 12:49:10: PerformanceMode = 0 : OK
10.04.2023 12:49:10: FanCPU = 14-31-3A-3E-41-48-50-64-00-00-01-1D-32-63-63-63 : OK
10.04.2023 12:49:10: FanGPU = 14-33-38-3C-44-46-50-64-00-01-14-28-33-63-63-63 : OK
10.04.2023 12:49:10: WMI event 123
10.04.2023 12:49:10: Boost 0
10.04.2023 12:49:10: Eco flag : 1
10.04.2023 12:49:10: Mux flag : 1
10.04.2023 12:49:10: Screen = 165Hz : OK
10.04.2023 12:49:10: ScreenOverdrive = 1 : OK
10.04.2023 12:49:10: USB-KB = 5D-BA-C5-C4-03
10.04.2023 12:49:10: WMI event 88
10.04.2023 12:49:16: Windows - Power Mode Changed
10.04.2023 12:49:16: AutoSetting for Offline
10.04.2023 12:49:16: BatteryLimit = 80 : OK
10.04.2023 12:49:16: PerformanceMode = 2 : OK
10.04.2023 12:49:17: FanCPU = 32-37-3C-3E-43-4B-59-64-00-00-00-1D-30-63-63-63 : OK
10.04.2023 12:49:17: FanGPU = 32-37-3B-3C-46-4B-59-64-00-00-00-0A-1D-63-63-63 : OK
10.04.2023 12:49:17: WMI event 123
10.04.2023 12:49:17: Boost 0
10.04.2023 12:49:17: Eco flag : 1
10.04.2023 12:49:17: Mux flag : 1
10.04.2023 12:49:17: Screen = 60Hz : OK
10.04.2023 12:49:17: ScreenOverdrive = 0 : OK
10.04.2023 12:49:17: WMI event 87
10.04.2023 12:49:17: USB-KB = 5D-BA-C5-C4-00
10.04.2023 12:49:18: PowerLimit A = 10 : OK
10.04.2023 12:49:22: Windows - Power Mode Changed
10.04.2023 12:49:22: AutoSetting for Online
10.04.2023 12:49:22: BatteryLimit = 80 : OK
10.04.2023 12:49:22: PerformanceMode = 0 : OK
10.04.2023 12:49:22: FanCPU = 14-31-3A-3E-41-48-50-64-00-00-01-1D-32-63-63-63 : OK
10.04.2023 12:49:22: FanGPU = 14-33-38-3C-44-46-50-64-00-01-14-28-33-63-63-63 : OK
10.04.2023 12:49:22: WMI event 123
10.04.2023 12:49:22: Boost 0
10.04.2023 12:49:22: Eco flag : 1
10.04.2023 12:49:22: Mux flag : 1
10.04.2023 12:49:22: Screen = 165Hz : OK
10.04.2023 12:49:22: ScreenOverdrive = 1 : OK
10.04.2023 12:49:22: USB-KB = 5D-BA-C5-C4-03
10.04.2023 12:49:22: WMI event 88

**Comment by JackB111** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/129295334/230878684-d0a13ab2-05c3-4797-b0e3-07ddfedf4ff4.png">

**Comment by seerge** [comment]
@JackB111 oke, thanks.

From log I see that each time laptop is plugged / unplugged app sends corresponding command to keyboard

`10.04.2023 12:49:05: USB-KB = 5D-BA-C5-C4-00` (to set brightness to min 00)

`10.04.2023 12:49:22: USB-KB = 5D-BA-C5-C4-03` (to set brightness to max 03)

So it should be working? Does other keyboard controls work for you ? What is the last version when backlit worked for you before ? can you download it again from https://github.com/seerge/g-helper/releases and see if it still works? cause may be reason is in something else ?

**Comment by seerge** [comment]
@JackB111 you can use it then :) 

https://github.com/seerge/g-helper/compare/v0.46...v0.49 - there is nothing changed that could affect backlight

I can not fix something i can't reproduce
