### ISSUE TITLE
Asus ROG Strix Impact (including Not For Sale edition)

### ISSUE THREAD

**Issue by agentb-7** [seerge/g-helper#2040]
### Mouse / peripheral model and version

Asus ROG Strix Impact

### Armoury Crate Screenshots

![ApplicationFrameHost_oEGBlgcT7V](https://github.com/seerge/g-helper/assets/74735422/46a9e65c-9af5-496d-9368-c96a4517cb5b)
![ApplicationFrameHost_SPpYWtcM42](https://github.com/seerge/g-helper/assets/74735422/107756a2-93eb-4575-8032-4c4cdffbb99c)
![ApplicationFrameHost_cIhHlAMfvR](https://github.com/seerge/g-helper/assets/74735422/1658bf18-a1ac-4da1-9c5e-4c0b410bc346)
![ApplicationFrameHost_UA6UAgfT7B](https://github.com/seerge/g-helper/assets/74735422/fdb5bc0f-de9f-4a8f-acbb-684864a07f88)

### USB Details

    =========================== USB Port2 ===========================

Connection Status        : 0x01 (Device is connected)
Port Chain               : 2-2-2
Properties               : 0x01
 IsUserConnectable       : yes
 PortIsDebugCapable      : no
 PortHasMultiCompanions  : no
 PortConnectorIsTypeC    : no
ConnectionIndex          : 0x02 (Port 2)
CompanionIndex           : 0
 CompanionHubSymLnk      : USB#VID_2109&PID_0813#5&2195fc25&0&20#{f18a0e88-c30c-11d0-8815-00a0c906bed8}
 CompanionPortNumber     : 0x02 (Port 2)
 -> CompanionPortChain   : 2-20-2

      ========================== Summary =========================
Vendor ID                : 0x0B05 (ASUSTek Computer Inc.)
Product ID               : 0x1847
USB Version              : 2.0 -> but Device is Full-Speed only
Port maximum Speed       : High-Speed (Companion Port 2-20-2 supports SuperSpeed)
Device maximum Speed     : Full-Speed
Device Connection Speed  : Full-Speed
Self powered             : no
Demanded Current         : 98 mA
Used Endpoints           : 5

      ======================== USB Device ========================

        +++++++++++++++++ Device Information ++++++++++++++++++
Device Description       : USB Composite Device
Device Path              : \\?\USB#VID_0B05&PID_1847#6&3107e60b&0&2#{a5dcbf10-6530-11d2-901f-00c04fb951ed} (GUID_DEVINTERFACE_USB_DEVICE)
Kernel Name              : \Device\USBPDO-10
Device ID                : USB\VID_0B05&PID_1847\6&3107E60B&0&2
Hardware IDs             : USB\VID_0B05&PID_1847&REV_0110 USB\VID_0B05&PID_1847
Driver KeyName           : {36fc9e60-c465-11cf-8056-444553540000}\0014 (GUID_DEVCLASS_USB)
Driver                   : \SystemRoot\System32\drivers\usbccgp.sys (Version: 10.0.22621.2506  Date: 2023-11-15  Company: Microsoft Corporation)
Driver Inf               : C:\WINDOWS\inf\usb.inf
Legacy BusType           : PNPBus
Class                    : USB
Class GUID               : {36fc9e60-c465-11cf-8056-444553540000} (GUID_DEVCLASS_USB)
Service                  : usbccgp
Enumerator               : USB
Location Info            : Port_#0002.Hub_#0005
Address                  : 2
Location IDs             : PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(2)#USB(2), ACPI(_SB_)#ACPI(PC00)#ACPI(XHCI)#ACPI(RHUB)#ACPI(HS02)#USB(2)
Container ID             : {7d1f21b8-485c-11ee-99a7-bc6ee266e382}
Manufacturer Info        : (Standard USB Host Controller)
Capabilities             : 0x84 (Removable, SurpriseRemovalOK)
Status                   : 0x0180400A (DN_DRIVER_LOADED, DN_STARTED, DN_REMOVABLE, DN_NT_ENUMERATOR, DN_NT_DRIVER)
Problem Code             : 0
Address                  : 2
Power State              : D0 (supported: D0, D1, D2, D3, wake from D0, wake from D1, wake from D2)
 Child Device 1          : USB Input Device
  Device ID              : USB\VID_0B05&PID_1847&MI_00\7&1D879F82&0&0000
  Class                  : HIDClass
  Driver KeyName         : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0024 (GUID_DEVCLASS_HIDCLASS)
  Service                : HidUsb
  Location               : 0000.0014.0000.002.002.000.000.000.000
  LocationPaths          : PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(2)#USB(2)#USBMI(0)  PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(2)#USB(2)#USB(2)  ACPI(_SB_)#ACPI(PC00)#ACPI(XHCI)#ACPI(RHUB)#ACPI(HS02)#USB(2)#USBMI(0)  ACPI(_SB_)#ACPI(PC00)#ACPI(XHCI)#ACPI(RHUB)#ACPI(HS02)#USB(2)#USB(2)
  SelectiveSuspEnabled   : 0
  EnhPowerMgmtEnabled    : 1
 Child Device 1          : ROG STRIX IMPACT
  Device Path 1          : \\?\HID#VID_0B05&PID_1847&MI_00#8&48aecda&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (GUID_DEVINTERFACE_HID)
  Device Path 2          : \\?\HID#VID_0B05&PID_1847&MI_00#8&48aecda&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd} (GUID_DEVINTERFACE_MOUSE)
  Kernel Name            : \Device\000000b0
  Device ID              : HID\VID_0B05&PID_1847&MI_00\8&48AECDA&0&0000
  Class                  : Mouse
  Driver KeyName         : {4d36e96f-e325-11ce-bfc1-08002be10318}\0004 (GUID_DEVCLASS_MOUSE)
  Service                : mouhid
 Child Device 1          : Mouse_Filter_01
  Device Path            : \\?\{dd0188d0-4609-4f6d-bcd7-d1c3547a0293}#MouseFilter#9&326f1648&0&01#{ddf31c51-a860-4e3d-960c-0ee87c53e9e4}
  Kernel Name            : \Device\000000b0_AsusFilter
  Device ID              : {DD0188D0-4609-4F6D-BCD7-D1C3547A0293}\MOUSEFILTER\9&326F1648&0&01
  Location               : Mouse Filter
 Child Device 2          : USB Input Device
  Device ID              : USB\VID_0B05&PID_1847&MI_01\7&1D879F82&0&0001
  Class                  : HIDClass
  Driver KeyName         : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0025 (GUID_DEVCLASS_HIDCLASS)
  Service                : HidUsb
  Location               : 0000.0014.0000.002.002.000.000.000.000
  LocationPaths          : PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(2)#USB(2)#USBMI(1)  ACPI(_SB_)#ACPI(PC00)#ACPI(XHCI)#ACPI(RHUB)#ACPI(HS02)#USB(2)#USBMI(1)
  SelectiveSuspEnabled   : 0
  EnhPowerMgmtEnabled    : 1
 Child Device 1          : ROG STRIX IMPACT
  Device Path 1          : \\?\HID#VID_0B05&PID_1847&MI_01&Col01#8&1f4c50e8&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd} (GUID_DEVINTERFACE_KEYBOARD)
  Device Path 2          : \\?\HID#VID_0B05&PID_1847&MI_01&Col01#8&1f4c50e8&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd (GUID_DEVINTERFACE_HID)
  Kernel Name            : \Device\000000b1
  Device ID              : HID\VID_0B05&PID_1847&MI_01&COL01\8&1F4C50E8&0&0000
  Class                  : Keyboard
  Driver KeyName         : {4d36e96b-e325-11ce-bfc1-08002be10318}\0004 (GUID_DEVCLASS_KEYBOARD)
  Service                : kbdhid
 Child Device 1          : Keyboard_Filter_01
  Device Path            : \\?\{A65C87F9-BE02-4ed9-92EC-012D416169FA}#KeyboardFilter#9&163f530e&0&01#{3fb7299d-6847-4490-b0c9-99e0986ab886}
  Kernel Name            : \Device\000000b1_AsusFilter
  Device ID              : {A65C87F9-BE02-4ED9-92EC-012D416169FA}\KEYBOARDFILTER\9&163F530E&0&01
  Location               : Keyboard Filter
 Child Device 2          : HID-compliant consumer control device
  Device Path            : \\?\HID#VID_0B05&PID_1847&MI_01&Col02#8&1f4c50e8&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} (GUID_DEVINTERFACE_HID)
  Kernel Name            : \Device\000000b2
  Device ID              : HID\VID_0B05&PID_1847&MI_01&COL02\8&1F4C50E8&0&0001
  Class                  : HIDClass
  Driver KeyName         : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0027 (GUID_DEVCLASS_HIDCLASS)
 Child Device 3          : USB Input Device
  Device ID              : USB\VID_0B05&PID_1847&MI_02\7&1D879F82&0&0002
  Class                  : HIDClass
  Driver KeyName         : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0026 (GUID_DEVCLASS_HIDCLASS)
  Service                : HidUsb
  Location               : 0000.0014.0000.002.002.000.000.000.000
  LocationPaths          : PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(2)#USB(2)#USBMI(2)  ACPI(_SB_)#ACPI(PC00)#ACPI(XHCI)#ACPI(RHUB)#ACPI(HS02)#USB(2)#USBMI(2)
  SelectiveSuspEnabled   : 0
  EnhPowerMgmtEnabled    : 1
 Child Device 1          : HID-compliant vendor-defined device
  Device Path            : \\?\HID#VID_0B05&PID_1847&MI_02#8&788c4a3&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (GUID_DEVINTERFACE_HID)
  Kernel Name            : \Device\000000b3
  Device ID              : HID\VID_0B05&PID_1847&MI_02\8&788C4A3&0&0000
  Class                  : HIDClass
  Driver KeyName         : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0028 (GUID_DEVCLASS_HIDCLASS)

        +++++++++++++++++ Registry USB Flags +++++++++++++++++
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\usbflags\0B0518470110
 osvc                    : REG_BINARY 00 00
 NewInterfaceUsage       : REG_DWORD 00000000 (0)

        ---------------- Connection Information ---------------
Connection Index         : 0x02 (Port 2)
Connection Status        : 0x01 (DeviceConnected)
Current Config Value     : 0x01 (Configuration 1)
Device Address           : 0x09 (9)
Is Hub                   : 0x00 (no)
Device Bus Speed         : 0x01 (Full-Speed)
Number of open Pipes     : 0x04 (4 pipes to data endpoints)
Pipe[0]                  : EndpointID=1  Direction=IN   ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x8     bInterval=1   -> 196 Bits/ms = 24500 Bytes/s
Pipe[1]                  : EndpointID=2  Direction=IN   ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x9     bInterval=1   -> 205 Bits/ms = 25625 Bytes/s
Pipe[2]                  : EndpointID=3  Direction=IN   ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x40    bInterval=2   -> 718 Bits/ms = 89750 Bytes/s
Pipe[3]                  : EndpointID=4  Direction=OUT  ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x40    bInterval=2   -> 718 Bits/ms = 89750 Bytes/s
Data (HexDump)           : 02 00 00 00 12 01 00 02 00 00 00 40 05 0B 47 18   ...........@..G.
                           10 01 01 02 00 01 01 01 00 09 00 04 00 00 00 01   ................
                           00 00 00 07 05 81 03 08 00 01 00 00 00 00 07 05   ................
                           82 03 09 00 01 00 00 00 00 07 05 83 03 40 00 02   .............@..
                           00 00 00 00 07 05 04 03 40 00 02 00 00 00 00      ........@......

        --------------- Connection Information V2 -------------
Connection Index         : 0x02 (2)
Length                   : 0x10 (16 bytes)
SupportedUsbProtocols    : 0x03
 Usb110                  : 1 (yes, port supports USB 1.1)
 Usb200                  : 1 (yes, port supports USB 2.0)
 Usb300                  : 0 (no, port not supports USB 3.0) -> but Companion Port 2-20-2 does
 ReservedMBZ             : 0x00
Flags                    : 0x00
 DevIsOpAtSsOrHigher     : 0 (Device is not operating at SuperSpeed or higher)
 DevIsSsCapOrHigher      : 0 (Device is not SuperSpeed capable or higher)
 DevIsOpAtSsPlusOrHigher : 0 (Device is not operating at SuperSpeedPlus or higher)
 DevIsSsPlusCapOrHigher  : 0 (Device is not SuperSpeedPlus capable or higher)
 ReservedMBZ             : 0x00
Data (HexDump)           : 02 00 00 00 10 00 00 00 03 00 00 00 00 00 00 00   ................

    ---------------------- Device Descriptor ----------------------
bLength                  : 0x12 (18 bytes)
bDescriptorType          : 0x01 (Device Descriptor)
bcdUSB                   : 0x200 (USB Version 2.0) -> but device is Full-Speed only
bDeviceClass             : 0x00 (defined by the interface descriptors)
bDeviceSubClass          : 0x00
bDeviceProtocol          : 0x00
bMaxPacketSize0          : 0x40 (64 bytes)
idVendor                 : 0x0B05 (ASUSTek Computer Inc.)
idProduct                : 0x1847
bcdDevice                : 0x0110
iManufacturer            : 0x01 (String Descriptor 1)
 Language 0x0409         : "ASUS"
iProduct                 : 0x02 (String Descriptor 2)
 Language 0x0409         : "ROG STRIX IMPACT"
iSerialNumber            : 0x00 (No String Descriptor)
bNumConfigurations       : 0x01 (1 Configuration)
Data (HexDump)           : 12 01 00 02 00 00 00 40 05 0B 47 18 10 01 01 02   .......@..G.....
                           00 01                                             ..

    ------------------ Configuration Descriptor -------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x02 (Configuration Descriptor)
wTotalLength             : 0x005B (91 bytes)
bNumInterfaces           : 0x03 (3 Interfaces)
bConfigurationValue      : 0x01 (Configuration 1)
iConfiguration           : 0x00 (No String Descriptor)
bmAttributes             : 0xA0
 D7: Reserved, set 1     : 0x01
 D6: Self Powered        : 0x00 (no)
 D5: Remote Wakeup       : 0x01 (yes)
 D4..0: Reserved, set 0  : 0x00
MaxPower                 : 0x31 (98 mA)
Data (HexDump)           : 09 02 5B 00 03 01 00 A0 31 09 04 00 00 01 03 01   ..[.....1.......
                           02 00 09 21 11 01 00 01 22 4C 00 07 05 81 03 08   ...!...."L......
                           00 01 09 04 01 00 01 03 00 00 00 09 21 11 01 00   ............!...
                           01 22 5A 00 07 05 82 03 09 00 01 09 04 02 00 02   ."Z.............
                           03 00 00 00 09 21 11 01 00 01 22 19 00 07 05 83   .....!....".....
                           03 40 00 02 07 05 04 03 40 00 02                  .@......@..

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x00 (Interface 0)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x01 (1 Endpoint)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x01 (Boot Interface)
bInterfaceProtocol       : 0x02 (Mouse)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 00 00 01 03 01 02 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 4C 00                        .!...."L.
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x004C (76 bytes)
Error reading descriptor : ERROR_INVALID_PARAMETER (due to a obscure limitation of the Win32 USB API, see UsbTreeView.txt)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x81 (Direction=IN EndpointID=1)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0008 (8 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 81 03 08 00 01                              .......

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x01 (Interface 1)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x01 (1 Endpoint)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x00 (None)
bInterfaceProtocol       : 0x00 (None)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 01 00 01 03 00 00 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 5A 00                        .!...."Z.
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x005A (90 bytes)
Error reading descriptor : ERROR_INVALID_PARAMETER (due to a obscure limitation of the Win32 USB API, see UsbTreeView.txt)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x82 (Direction=IN EndpointID=2)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0009 (9 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 82 03 09 00 01                              .......

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x02 (Interface 2)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x02 (2 Endpoints)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x00 (None)
bInterfaceProtocol       : 0x00 (None)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 02 00 02 03 00 00 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 19 00                        .!...."..
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0019 (25 bytes)
Error reading descriptor : ERROR_INVALID_PARAMETER (due to a obscure limitation of the Win32 USB API, see UsbTreeView.txt)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x83 (Direction=IN EndpointID=3)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0040 (64 bytes)
bInterval                : 0x02 (2 ms)
Data (HexDump)           : 07 05 83 03 40 00 02                              ....@..

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x04 (Direction=OUT EndpointID=4)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0040 (64 bytes)
bInterval                : 0x02 (2 ms)
Data (HexDump)           : 07 05 04 03 40 00 02                              ....@..

    ----------------- Device Qualifier Descriptor -----------------
Error                    : ERROR_GEN_FAILURE  (because the device is Full-Speed only)

      -------------------- String Descriptors -------------------
             ------ String Descriptor 0 ------
bLength                  : 0x04 (4 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language ID[0]           : 0x0409 (English - United States)
Data (HexDump)           : 04 03 09 04                                       ....
             ------ String Descriptor 1 ------
bLength                  : 0x0A (10 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language 0x0409          : "ASUS"
Data (HexDump)           : 0A 03 41 00 53 00 55 00 53 00                     ..A.S.U.S.
             ------ String Descriptor 2 ------
bLength                  : 0x22 (34 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language 0x0409          : "ROG STRIX IMPACT"
Data (HexDump)           : 22 03 52 00 4F 00 47 00 20 00 53 00 54 00 52 00   ".R.O.G. .S.T.R.
                           49 00 58 00 20 00 49 00 4D 00 50 00 41 00 43 00   I.X. .I.M.P.A.C.
                           54 00                                             T.

### Additional information.

Came with ROG Strix SCAR 17 SE.

**Comment by IceStormNG** [comment]
Alright. Please try this build and let me know what works and what not. If something does not work, please also send me the GHelper log file (from AppData).

[GHelper.zip](https://github.com/seerge/g-helper/files/14210532/GHelper.zip)

**Comment by agentb-7** [comment]
The lighting control doesn't seem to work, after I select the color and reopen the dialog, it just resets to whatever it was. Performance controls are working, but 1600dpi feels more like... 800dpi when selected in Armoury Crate? Also, it crashed at least once when selecting very low DPI. Including both log files.
[log.txt](https://github.com/seerge/g-helper/files/14212499/log.txt)
[log_crash.txt](https://github.com/seerge/g-helper/files/14212500/log_crash.txt)

**Comment by IceStormNG** [comment]
Hm.. the mouse errored out setting the lighting settings... Please try this build here:

[GHelper.zip](https://github.com/seerge/g-helper/files/14213335/GHelper.zip)

**Comment by seerge** [comment]
@agentb-7 did you have a chance to try a new build? :)

**Comment by agentb-7** [comment]
Hi, sorry, I'm a bit busy now, I'll try it over the weekend.

**Comment by agentb-7** [comment]
[log.txt](https://github.com/seerge/g-helper/files/14230805/log.txt)
The performance settings now work as intended, but RGB control still doens't work.

**Comment by IceStormNG** [comment]
Ok. Your mouse errors out whatever I send to it for lighting controls. This means, you would have to do a little packet capture for me to find out what Armoury Crate sends.


Alright. In this case, guessing numbers will not work. I would like to ask you to do the following. You said, you have another PC with AC installed to manage the mouse, right?
Please install the following software on the PC with AC https://freeusbanalyzer.com/
After the install you have to reboot. That software will allow you to read the USB traffic. The idea is: you change the lighting settings while the tool runs in AC and it logs what Armoury Crate sends to your mouse.

Make sure the mouse is connected during before reboot or the tool might have issues detecting it.

Opening the tool will show you multiple devices for your mouse. In most cases it is the first one that you have to connect to. 

You can find the right device by looking for the number of endpoints. The one you look for has 2 endpoints. The others have only 1.
<img width="259" alt="image" src="https://github.com/seerge/g-helper/assets/12786283/18932c0a-085f-4509-a9a4-f6401961ca43">



Double click it
<img width="779" alt="image" src="https://github.com/seerge/g-helper/assets/12786283/a6c12d02-da96-4df6-9e5e-dcd2f924f88c">

This dialog will appear. Double click on "packet view" on the right so it looks like this.
<img width="543" alt="image" src="https://github.com/seerge/g-helper/assets/12786283/cd7a5aba-25b3-48f2-9564-ed3bdf6f7a9c">

Click on start.
<img width="783" alt="image" src="https://github.com/seerge/g-helper/assets/12786283/efad369e-f3ad-4f1c-b215-e0d3b26e7734">

It will now start logging packets. Open AC and the packets should be alternating DOWN (blue) and UP (white). If you get spammed with only UP packets, it it was the wrong endpoint, then you either got the one for the mouse buttons or the ones for the mouse position. In that case just stop the sesesion (the red stop button in the toolbar) and select another device.

Then open AC and switch through the lighting settings.

Afterwards, save the log file with this:
<img width="650" alt="image" src="https://github.com/seerge/g-helper/assets/12786283/6d4b32ec-6983-4908-b665-6f47a0419eee">

In the dialog that appears, leave the default settings. Then upload the file here. So I can analyze what Armoury Crate sends to get this working.


When the implementation is done and finished, you can uninstall the USB analyzer software again.

**Comment by seerge** [comment]
@IceStormNG could it be that mouse requires packets to be sent as [SetFeature](https://github.com/seerge/g-helper/blob/8de06ce5ad86747af94338f0d34ec067615517f7/app/AnimeMatrix/Communication/Platform/WindowsUsbProvider.cs#L55) instead of [Write](https://github.com/seerge/g-helper/blob/8de06ce5ad86747af94338f0d34ec067615517f7/app/AnimeMatrix/Communication/Platform/WindowsUsbProvider.cs#L86) ? 

As some keyboards or for example Rog Ally accepts only SetFeature as well.

**Comment by agentb-7** [comment]
[Strix_Impact.zip](https://github.com/seerge/g-helper/files/14303490/Strix_Impact.zip)
Hi there, here's the log. I went through several settings, including static, breathing, different colors on both, and different brightness on Breathing. If you need anything else, let me know.

**Comment by agentb-7** [comment]
Oh, one more thing. I remember now that I managed to set lighting on the mouse with OpenRGB at some point, so they figured out at least a part of it. Hope it helps.

**Comment by IceStormNG** [comment]
Alright. I checked the log. Just to confirm something: if you set the mouse to "breathing" or anything besides static, does the mouse still breath when AC is not running? or when you connect the mouse to a PC that has no AC?
Because it looks like this mouse has no actual lighting modes in hardware besides static, but AC just spams lighting packets onto this mouse.

**Comment by IceStormNG** [comment]
Please try this build here:

[GHelper.zip](https://github.com/seerge/g-helper/files/14312063/GHelper.zip)

It sends the exact same packets as AC does.
Btw: AC is super spammy with lighting packets for this mouse. So AC might revert the settings while you change them in GHelper if you run both on the same machine.

**Comment by agentb-7** [comment]
> Just to confirm something: if you set the mouse to "breathing" or anything besides static, does the mouse still breath when AC is not running? or when you connect the mouse to a PC that has no AC?
Yeah no, it doesn't. Like I said, it came with the laptop, and has "not for sale" markings, so it probably wasn't designed to work without AC.
I'll try the new build when I can, thank you for your work guys.

**Comment by IceStormNG** [comment]
> Yeah no, it doesn't. Like I said, it came with the laptop, and has "not for sale" markings, so it probably wasn't designed to work without AC.

It has the same VID/PID as the regular one though. Not sure how AC determines which one is the not for sale and which is not.
It could be that it is the same mouse just that it is bundled with the laptop. 

Right now, GHelper does not store the settings of the mouse. The mouse does. Which means I would have to disable all settings in GH that the mouse cannot handle on its own.
Though.. I saw AC sending at least 3 different lighting modes to your mouse in the log you sent me. So maybe it can do stuff on its own, but ASUS decided not to do that.

**Comment by seerge** [comment]
@agentb-7  Did you had a chance to try latest build? :)

> I'll try the new build when I can, thank you for your work guys.

**Comment by agentb-7** [comment]
Hi, I'm sorry, I wasn't able to test the build, I'll try this week. Do I understand correctly that it can be tested on a non-Asus machine (just use it with the mouse)?

**Comment by agentb-7** [comment]
Hi again,

I can absolutely confirm that the mouse is working as intended in the build provided.

Again, sorry for the wait (my life has been a mess recently) and thank you for your amazing tool!

**Comment by IceStormNG** [comment]
No worries. Thanks for the feedback. I will push the changes then.

**Comment by seerge** [comment]
@IceStormNG @agentb-7 great :) closing as completed, and this will be included in next release then
