### ISSUE TITLE
Support for new refresh rate options

### ISSUE THREAD

**Issue by MaxLebled** [seerge/g-helper#2041]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

New refresh rate options have recently popped up on my 2023 G14.

Eco/Standard:

![Screenshot 2024-02-08 215819](https://github.com/seerge/g-helper/assets/3624123/0a99860f-b718-4010-adf6-66f2ff01cada)

Ultimate:

![Screenshot 2024-02-08 220005](https://github.com/seerge/g-helper/assets/3624123/7ad04321-b1eb-482f-bf5d-47f2c757a285)

I believe these started appearing after recent driver updates (possibly the January Radeon drivers) but I have no way to confirm that for sure, so take that hypothesis with a massive grain of salt.

More importantly, the screen does not black out when switching between 60 & 165 Hz, which is a great benefit.

With that being said, I figured it might be interesting to bring this to your attention, because it's possible it might be worthwhile to implement these in the UI of the app.

I don't know how exactly these refresh rates are implemented on the Windows side, how they work, in which way exactly they are "dynamic"... but it's possible they might be better trade-offs than fixed assignments?

### Describe the solution you'd like

If they turn out to be worth using, they could replace the existing buttons for 60 / 165 (on this model), or a new button could be added next to those.

### Device and Model

GA402XI (2023 G14, 7940HS w/ 780M + 4070)

### Additional information.

Software versions:

* AMD: 31.0.24002.92
* Nvidia: 551.46 (hotfix)
* Windows 11 build: 23H2 22631.3085

**Comment by seerge** [comment]
@MaxLebled hello,

I'm aware about this AMD changes :) but Windows API  that G-Helper uses to set refresh rates seem to be quite ancient and doesn't support anything but fixed values. Microsoft doesn't provide anything new :( 

https://stackoverflow.com/questions/63654012/programmatically-change-windows-laptops-refresh-rate

So I simply don't know if it's even possible to set that.

**Comment by MaxLebled** [comment]
Ah, that's too bad :)

Do you have more technical details about these changes? I couldn't find anything about them.

**Comment by seerge** [comment]
@MaxLebled i didn't, i assume this is something AMD just decided to introduce. On my (G14 2022) model it's only 60/120HZ, but change happens w/o black screen cause they have separated refresh rate and signal rates :)

**Comment by seerge** [comment]
@MaxLebled also, if that refresh rate is possible to set somehow - it would be via some AMD-specific library, i.e. via driver.  So it won't work when Nvidia or Intel GPU is running display.

While now G-Helper just sets refresh rate via windows itself. And it's simple and universal way

**Comment by seerge** [comment]
So I assume I have answered the question :) it's not possible to set that in current way. And digging deeply into AMD driver settings will cause more problems, cause it won't work on other GPUs :| 

I'm closing it as not planned then. Sorry

**Comment by KentNguyen132** [comment]
@seerge I just found out about this, so is there a way to just disable Auto and let me choose Dynamic refresh rate regardless of being plugged in or not? Thank you in advance!

**Comment by seerge** [comment]
@KentNguyen132 yes, just select any of the "non-auto" refresh rates, and then app won't be even trying to change it.
