### ISSUE TITLE
[Question] Green text vs Gray text on the G-Helper Updates screen

### ISSUE THREAD

**Issue by CaglarDeniz** [seerge/g-helper#2042]
Why are some drivers grayed out and some shown as green?

I assumed it would be related to that particular driver being out of date, but that doesn't seem to be the case as clicking on that link and updating doesn't change the color.

I know that this is not super important, but I couldn't see anything about it on the FAQ or the README and just wanted to ask .
![image](https://github.com/seerge/g-helper/assets/55607471/e06c949c-6cf5-40fa-a42c-707f29ea8aea)

**Comment by seerge** [comment]
@CaglarDeniz hello, please [check this topic for an answer ](https://github.com/seerge/g-helper/discussions/1350)

**Comment by CaglarDeniz** [comment]
Thank you so much! I apologize for not being able to find that topic
