### ISSUE TITLE
Lack of GPU mode for Rog Ally with eGPU

### ISSUE THREAD

**Issue by AleITDE1990** [seerge/g-helper#2043]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Since few versions the GPU mode was removed for the Rog Ally. I use it with an Oculink eGPU and it would be very useful to me. I could go back to the earlier version still supporting it for the Ally, but I would miss the improvements introduced in the latest versions.

### Describe the solution you'd like

Introducing an option in extra to re enable the menu on ROG Ally.

### Device and Model

Rog Ally

**Comment by seerge** [comment]
@AleITDE1990 hello, I have just removed Eco / Standard switch that did nothing on Ally (according to reports from other users).

XGM toggle is still there.

What exactly do you want to re-enable ?

**Comment by AleITDE1990** [comment]
I was hoping I would be able to disable the igpu through your "switch", when my eGpu is connected through oculink.

**Comment by seerge** [comment]
@AleITDE1990 but that switch never disabled eGPU in a first place, i think. Right ?

Last release before I have hidden it for Ally it's https://github.com/seerge/g-helper/releases/tag/v0.146 does Eco / Standard switch have any effect in your case? :)

**Comment by seerge** [comment]
@AleITDE1990 hello, any updates? :)

**Comment by seerge** [comment]
Closing as abandoned
