### ISSUE TITLE
Swapped curves on Zephyrus G15 2022 GA503RM

### ISSUE THREAD

**Issue by alxonk** [seerge/g-helper#2049]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

GPU and CPU are swapped in G-Helper, the GPU curve changes the rotation speed of the CPU fan, and the CPU curve changes the GPU fan 

### How to reproduce the bug?

If I turn the laptop upside down now, the left fan, which is above the CPU, spins: 
https://imgur.com/a/OMZi69B

the right fan, which is above the GPU, spins: 
https://imgur.com/a/0zro7yl 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14226286/log.txt)

### Device and Model

ASUS Zephyrus G15 (2022) GA503RM

### Armoury Crate

Uninstalled

### Version

0.151

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@alxonk hello,

Ok, as briefly discussed on reddit, it seems like Asus has (mistakenly?) swapped custom fan curves in this BIOS 317 for your model (GA503R). 

Try this build, that swaps curves back :) (i.e. it sets CPU curve to GPU endpoint and vice versa)

[GHelper.zip](https://github.com/seerge/g-helper/files/14226334/GHelper.zip)

**Comment by alxonk** [comment]
You are right, Asus really made a mistake with curves, armory has the same bag. Your fix works, thank you so much :)

Armory and your new GHelper version: 
https://imgur.com/a/SwW2DaZ

**Comment by alxonk** [comment]
> @alxonk hello,
> 
> Ok, as briefly discussed on reddit, it seems like Asus has (mistakenly?) swapped custom fan curves in this BIOS 317 for your model (GA503R).
> 
> Try this build, that swaps curves back :) (i.e. it sets CPU curve to GPU endpoint and vice versa)
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14226334/GHelper.zip)

You are right, Asus really made a mistake with curves, armory has the same bag. Your fix works, thank you so much :)

Armory and your new GHelper version: 
https://imgur.com/a/T7DEpiC

**Comment by seerge** [comment]
@alxonk ok, great! :) thanks for spotting. I will include it in next release then.

Your device / bios is the only model affected along all existing devices btw.

**Comment by alxonk** [comment]
This is because fans curve has not worked since release, they were bugged with a crooked bios, and only now it has been fixed with the new BIOS. It looks like even Asus didn’t know which curve was responsible for what before 317 update. But it’s really strange that on our laptop they are swapped, unlike the others Zephyrus laptops

By the way, I wrote that curves in armory work more correctly, but this is not so. Everything works well, thank you for responsiveness. Now on Reddit I will only praise GHelper :)

**Comment by dlonra55123** [comment]
Hi! I own GA503RW, the newest version of bios for me is 316. I have the exact same issue with reverted fan curves, thus I needed to go back to 313 where everything works. Is there any chance for bug fix in G-helper?

**Comment by seerge** [comment]
@dlonra55123 I have heard there is a BIOS 318 that fixes that :) App in windows can't fix BIOS issues unfortunately

**Comment by alxonk** [comment]
> Hi! I own GA503RW, the newest version of bios for me is 316. I have the exact same issue with reverted fan curves, thus I needed to go back to 313 where everything works. Is there any chance for bug fix in G-helper?

Are you sure that you REALLY could control your curves? I don’t know about RW, but on RM in BIOS versions 311, 313 and 315 there were problems with controlling the GPU fan. When setting a custom curve for the GPU, the RPM speed always dropped to 0 and never grow up until it custom, it could broke your GPU. I know this because I wrote to Asus myself and headquarters confirmed it. Therefore, BIOS 317 RM is marked on the website as critical and required. RW has BIOS 316, and it is also marked as critical, perhaps you have the same problem?

**Comment by dlonra55123** [comment]
Thank you for your answers! I did some additional tests:
BIOS 313: Custom fan curves work just fine so no issues
BIOS 316: When using eg Cinebench the GPU fan ramps up to max while CPU fan stays at 3000 RPM (idle speed) so the curves are obviusly swapped (proof: https://postimg.cc/z3yN27X7 )
For now, I'm going to stick with 313 and wait for an official release of 318 for my model.

**Comment by alxonk** [comment]
Asus has fixed the curve in the new bios update 318, you can return everything back :)

**Comment by seerge** [comment]
@alxonk i don't have to :) as it looks at BIOS version in a first place in a code https://github.com/seerge/g-helper/blob/0b2c962386905ba9b7ce7263df4e641c7bd16c77/app/AppConfig.cs#L538

And "swaps" curves only if it's 316 / 317

**Comment by alxonk** [comment]
> @alxonk i don't have to :) as it looks at BIOS version in a first place in a code
> 
> https://github.com/seerge/g-helper/blob/0b2c962386905ba9b7ce7263df4e641c7bd16c77/app/AppConfig.cs#L538
> 
> And "swaps" curves only if it's 316 / 317

Oh wow, it's so smart, but I use the version with alternative fan control, and for some reason the GPU curve controls the CPU and vice versa. Is it possible to fix this in it version as well? I get a instant fan response point by point

**Comment by alxonk** [comment]
That's why I thought it was the same in the main version

**Comment by seerge** [comment]
@alxonk  
> Oh wow, it's so smart, but I use the version with alternative fan control, and for some reason the GPU curve controls the CPU and vice versa. Is it possible to fix this in it version as well? I get a instant fan response point by point

On what BIOS is that ? cause on Experimental version app doesn't swap anything at all

**Comment by alxonk** [comment]
bios 318

https://imgur.com/a/V6m70Fl

**Comment by seerge** [comment]
@alxonk then it looks like they didn't fix it completely in BIOS 318. How did Experimental fan control behave on 317 ?

**Comment by alxonk** [comment]
> @alxonk then it looks like they didn't fix it completely in BIOS 318. How did Experimental fan control behave on 317 ?

Yes, but in basic version works correctly curves not swapped
https://imgur.com/a/b5Hw5QY

**Comment by seerge** [comment]
@alxonk then they have probably also "fixed" it by just swapping fan curves (in a way i did in an app), but didn't fix it on a real low level (when fans are actually controlled) :|

**Comment by seerge** [comment]
@alxonk can you check if in Experimental version it's indeed a wrong (i.e. CPU) fan spinning  and not GPU? by literally listening to device ? cause mb it's just swapped RPM-readings ?

**Comment by alxonk** [comment]
What the heck. This is insanely exciting

https://imgur.com/a/V6m70Fl - in this case CPU fan spins
https://imgur.com/a/b5Hw5QY - in this GPU fan

**Comment by seerge** [comment]
@alxonk as I just told in a "normal" release (non experimental) 0.164 - fans are controlled by BIOS, and since they swapped fan curves back - it's all correct, which is ok and as it should be

My question if in "experimental" version it's indeed CPU fan spins , or is it only CPU sensor reporting RPMs, while actually in a device it's GPU fan spinning ?

**Comment by alxonk** [comment]
> @alxonk as I just told in a "normal" release (non experimental) 0.164 - fans are controlled by BIOS, and since they swapped fan curves back - it's all correct, which is ok and as it should be
> 
> My question if in "experimental" version it's indeed CPU fan spins , or is it only CPU sensor reporting RPMs, while actually in a device it's GPU fan spinning ?

Sorry, it was worth clarifying that I don’t mean rpm values in g helper, but sound from laptop

https://imgur.com/a/V6m70Fl - in this case CPU fan spins (left side of open laptop)
https://imgur.com/a/b5Hw5QY - in this GPU fan (right side of open laptop)

**Comment by alxonk** [comment]
The experimental program shows that the gpu fan is spinning, but in fact the fan processor is spinning
In normal version everything works as should be

**Comment by seerge** [comment]
@alxonk i'm sorry, but I'm confused

This is your screenshot from **Experimental** build
![image](https://github.com/seerge/g-helper/assets/5920850/9faa5735-8cf4-4d9c-8b0d-57effcdc2d90)

Reading shows that CPU fan is spinning (and that's confirmed by the sound form laptop, right?) then it means that **sensor is correct,** but fan setting on low level is swapped in BIOS still

**Comment by alxonk** [comment]
> @alxonk i'm sorry, but I'm confused
> 
> This is your screenshot from **Experimental** build ![image](https://private-user-images.githubusercontent.com/5920850/318190631-9faa5735-8cf4-4d9c-8b0d-57effcdc2d90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTkxMzEsIm5iZiI6MTcxMTc5ODgzMSwicGF0aCI6Ii81OTIwODUwLzMxODE5MDYzMS05ZmFhNTczNS04Y2Y0LTRkOWMtOGIwZC01N2VmZmNkYzJkOTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzBUMTE0MDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODNiMTIwMDAxOWJkYTNkNTU2Y2E5YzQzODBiNGJmYmQ2ZWQ0OGRhZTMwYWEzMTgxYmNlYWUzNzQwMGEzNjliZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lGcYtDTuKCyfE32v6TTq47SOpBTqxtccGG_QffFpeyI)
> 
> Reading shows that CPU fan is spinning (and that's confirmed by the sound form laptop, right?) then it means that **sensor is correct,** but fan setting on low level is swapped in BIOS still

Yes, the sound comes from the CPU fan, but control the CPU fan with GPU curve

**Comment by alxonk** [comment]
Well looks like it's something with the bios
Asus apparently broke something again

https://imgur.com/a/PuiMeNz

**Comment by alxonk** [comment]
I think you shouldn’t do anything, I’ll watch for 318 a couple of days

**Comment by alxonk** [comment]
Well, I rebooted the laptop and checked and now the experimental and normal versions work the same. Seems that the BIOS decides how to spin up the fans, we can only give it approximate instructions. Perhaps the laptop somehow missed the point of the approximate instructions, because this was the first time it was turned on after updating the BIOS, so I could instantly control the fans in the experimental version 

 Thank you for trying to help, I really appreciate it, sorry for bothering you

**Comment by seerge** [comment]
@alxonk ok. Good to know. I have updated experimental build (in corresponding thread), so you may want to get a fresh one too

**Comment by dlonra55123** [comment]
Hallo again! First of all, thank you @seerge for your amazing job for the community!
I did some tests with the experimental version from #2272  on BIOS 316 (318 is not officialy available for my device).
In both cases the fan on the right side of the chassis spins loudly (GPU fan).

GHelper v0.164.1 from #2272:
![#2272 0 164 1](https://github.com/seerge/g-helper/assets/163341455/d1d74456-d6fc-4105-af1f-2d694c5724ae)

GHelper v0.164 - official release:
![0 164 0](https://github.com/seerge/g-helper/assets/163341455/3820081f-fedb-4984-8fd0-c6a97a9e8802)

In my understanding experimental version works as intended but ASUS messed the BIOS completly so it is not effective.
I think there is nothing else but going back to 313 and wating for an official ASUS fix.

**Comment by seerge** [comment]
@dlonra55123 **experimental** version is not swapping fans for you, it runs them as is.

But I can swap if needed, check this build
[GHelper.zip](https://github.com/seerge/g-helper/files/14817567/GHelper.zip)

**Comment by dlonra55123** [comment]
Amazing! Now everything works as intended on BIOS 316. Again thank you for your help!

**Comment by alxonk** [comment]
@seerge well, today I downloaded a new experimental version and again I can control the fans instantly. I just removed the old experimental 0.162 and installed a new experimental 0.164 version, and it changed the controls from normal to control without hysteresis, just in case I rebooted the laptop a couple of times, did a hard shutdown and so far I can still do control without hysteresis. But the problem is still the same. Sorry to bother you again, but is it possible to swap the fan curves on bios 318 ga503rm? Because in experimental version the GPU curve controls the CPU fan speed and vice versa, actually what I tried to explain yesterday

**Comment by seerge** [comment]
@alxonk check build 2 posts above here that I gave to @dlonra55123 . It's EXPERIMENTAL method that swaps fans.

**Comment by alxonk** [comment]
> @alxonk check build 2 posts above here that I gave to @dlonra55123 . It's EXPERIMENTAL method that swaps fans.

Thanks for the answer, I tried but nothing changes

**Comment by alxonk** [comment]
After reboot and hard shutdown no difference between EXPERIMENTAL method and just experimental version

EXPERIMENTAL method:
![изображение](https://github.com/seerge/g-helper/assets/122683623/87c317ab-c494-42e6-87c3-5d92acec4c11)

regular experimental version:
![изображение](https://github.com/seerge/g-helper/assets/122683623/d52b81c8-08d8-49d3-9275-123f6d3ac4c5)

**Comment by seerge** [comment]
@alxonk ok, right .. it swaps for a "bugged" bios, but since you already have a "good" bios (318). It doesn't swap fans for that version.

Apparently they have fixed it, but not completely ... I will upload another build that will swap fans even for 318 tomorrow

**Comment by dlonra55123** [comment]
I'm not sure if it is a coincidence but Asus has just officialy released a **BIOS 317** for **GA503RW** that fixes my problem with swapped fan curves. Now:
- stock GHelper v164.0 works as intended (GOOD)
- GHelper with EXPERIMENTAL method that you posted in this thread works as intended (BETTER - faster fan speed change with manual control)
- GHelper from #2272 version now swaps the fan curves the wrong way (BAD)

**Comment by seerge** [comment]
@alxonk @dlonra55123 I have updated Experimental build in #2272 (and here [GHelper.zip](https://github.com/seerge/g-helper/files/14822101/GHelper.zip)) so it should keep "swapping" bugged fans for you. Let me know if is now "correct"

**Comment by dlonra55123** [comment]
@seerge Yes, the updated version works correctly now!

**Comment by alxonk** [comment]
Yes, at now the cpu curve is control the cpu fan, but for some reason the gpu curve is not working at all

"Old" experimental version:
![изображение](https://github.com/seerge/g-helper/assets/122683623/7bba3753-26c8-4a9c-936e-b5d2d7b8125b)
![изображение](https://github.com/seerge/g-helper/assets/122683623/c0825244-18bb-4787-b6c8-068100144053)

"New" experimental version

![изображение](https://github.com/seerge/g-helper/assets/122683623/2558775a-4a34-4b9d-a2f5-6aa27f5f2f1e)
![изображение](https://github.com/seerge/g-helper/assets/122683623/3a5e9ea1-1933-41a9-bf19-66c6a464745a)

**Comment by seerge** [comment]
@alxonk try this build [GHelper.zip](https://github.com/seerge/g-helper/files/14822299/GHelper.zip) (also update in main thread)

Also I have fixed your "UI" bug with resizing :)

**Comment by alxonk** [comment]
Now everything works just perfect 
Thank you so much for your efforts :)
