### ISSUE TITLE
M3 Hotkey still being used to disabe/enable microphone in Realtek

### ISSUE THREAD

**Issue by Flex4249** [seerge/g-helper#205]
No matter what I do, Realtek Audio Panel still uses the M3 Hotkey as a Microphone mute switch.

I have it currently set as a Play/Pause but I can only use it as one when I use headphones whether it's Bluetooth or through the aux port.

I'd like it so that Realtek doesn't use it as a mute switch unless selected to as one of the hotkey options through the extras menu so that I can use my FN+F4 hotkey for something else.

**Comment by seerge** [comment]
Hello, it's not realtek - it's "asus optimization service" that handles all hotkeys, and the only to prevent that - is to stop it (but then other hotkeys like brightness will stop working as well) :) 

I don't know the way to control that, as it's not part of the app and there is nothing to fix there :|
