### ISSUE TITLE
Need application support for ASUS TUF F15

### ISSUE THREAD

**Issue by singhaniya1216** [seerge/g-helper#2051]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Need application support for ASUS TUF F15

### Describe the solution you'd like

Need application support for ASUS TUF F15

### Device and Model

ASUS TUF F15

**Comment by seerge** [comment]
@singhaniya1216 hello, your device is supported

Please keep in mind if some features were not available in Armoury they won't be in G-Helper neither, cause your hardware need to support them in a first place.
