### ISSUE TITLE
FN + F12 airplane mode bug

### ISSUE THREAD

**Issue by Niloy-Sarker** [seerge/g-helper#2052]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [x] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

FN + F12 triggers infinite airplane mode toggle causing hang the laptop. Immediately ending g-helper task make laptop useable again. FN+f12 works normally when g-helper is not running.

### How to reproduce the bug?

Press Fn + F12 key

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14229898/log.txt)

### Device and Model

Tuf F15 506lh

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.152.0

### OS

Windows 11 23h2

**Comment by seerge** [comment]
@Niloy-Sarker hello, try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/14230605/GHelper.zip)

**Comment by Niloy-Sarker** [comment]
@seerge Thanks. This build fixed the issue.
