### ISSUE TITLE
GHelper won't run

### ISSUE THREAD

**Issue by Crumpinator** [seerge/g-helper#2053]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I have installed Microsoft .NET 7, ASUS SYSTEM CONTROL INTERFACE and all other requirements, but after unzipping and running the exe file, the wait cursor appears for a second and nothing happens. The app just doesn't seem to launch. I also tried running as admin. In event viewer, there are no errors to do with the program it just doesn't seem to be starting. There is also no ghelper folder present in %appdata% so I am unable to attach a log file.

### How to reproduce the bug?

unknown

### Logs

unavailable

### Device and Model

Asus ROG Strix G15 G513QE-HF074T

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.151

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Crumpinator hello,

Can you double check in Event Viewer for any "Errors" (red) mentioning GHelper.exe ?

![image](https://github.com/seerge/g-helper/assets/5920850/6d5e9ff8-e0de-4150-89ed-f6e1edb29b51)

Cause if there is nothing there, your windows doesn't even start the app :)

I don't know why it's like that. Do you have any strange security or defender settings that would prevent exe from launching at all? 
Did you try checking ``Unblock`` in file properties as [explained in Requirements](https://github.com/seerge/g-helper/wiki/Requirements#how-to-start)?

**Comment by Kikimahe** [comment]
Hi,

Ghelper is blocked by Smartcreen and a popup should open to warn you. You can then choose "run anyway"
But sometimes it happens that this popup does not appear on Windows 11.
(This happened to me).

Try to disable **Windows Defender Smartscreen** before running Ghelper (you can enable it after)
Ghelper should run. ;-)

![22111303133525405118049075](https://github.com/seerge/g-helper/assets/142881210/db6929ab-7e86-4f5b-9cc3-2205dc3c0832)

**Comment by Crumpinator** [comment]
My mistake, I forgot to check unblock in properties, thank you so much for the help!
