### ISSUE TITLE
Hanging upon changing power mode.

### ISSUE THREAD

**Issue by parameter-u** [seerge/g-helper#2054]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Whenever the power mode is switched from balanced to silent, whether it is done manually or upon plugging the computer into the power, the application hangs.

### How to reproduce the bug?

Change from Balanced to silent or vice versa, or plug or unplug the computer to change the mode.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14233340/log.txt)

### Device and Model

G14 GA402XY

### Additional information.

Log Name:      Application
Source:        Application Hang
Date:          2024-02-11 10:55:56 AM
Event ID:      1002
Task Category: Hanging Events
Level:         Error
Keywords:      
User:          SYSTEM
Computer:      Higgs
Description:
The program GHelper.exe version 0.151.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Hang" Guid="{c631c3dc-c676-59e4-2db3-5c0af00f9675}" />
    <EventID>1002</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>101</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-11T15:55:56.3400630Z" />
    <EventRecordID>3057</EventRecordID>
    <Correlation />
    <Execution ProcessID="27492" ThreadID="24096" />
    <Channel>Application</Channel>
    <Computer>LuxEtVer1tas</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="AppName">GHelper.exe</Data>
    <Data Name="AppVersion">0.151.0.0</Data>
    <Data Name="ProcessId">0x23cc</Data>
    <Data Name="StartTime">0x1da5b7515d41978</Data>
    <Data Name="TerminationTime">4294967295</Data>
    <Data Name="ExeFileName">C:\Users\Param\Downloads\GHelper\GHelper.exe</Data>
    <Data Name="ReportId">2dec3180-0629-44a0-a630-dae647356925</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
    <Data Name="HangType">Top level window is idle</Data>
  </EventData>
</Event>

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.151

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@parameter-u hello,

It doesn't look that app hangs, at least from the log

Literally last session

```
2024-02-11 12:18:24 PM: Mode = 0 : OK                                 <---- BALANCED MODE
2024-02-11 12:18:24 PM: GET CLOCK LIMIT: NVAPI_GPU_NOT_POWERED
2024-02-11 12:18:24 PM: nvidia-smi -lgc 0,2250
2024-02-11 12:18:27 PM: GPU clocks set to "(gpuClkMin 0, gpuClkMax 2250)" for GPU 00000000:01:00.0 All done.
2024-02-11 12:18:27 PM: GET GPU CLOCKS: 30, 55
2024-02-11 12:18:27 PM: SET GPU CLOCKS: 100, 100
2024-02-11 12:18:30 PM: FanCPU = 1E-32-37-3C-4A-4E-52-53-00-01-0D-1E-2C-33-3B-64 : OK
2024-02-11 12:18:41 PM: FanGPU = 1E-32-37-3C-4A-4E-52-53-00-01-0B-12-2A-33-3B-5B : OK
2024-02-11 12:18:41 PM: Battery Saver detected
2024-02-11 12:18:41 PM: PowerLimit A3 = 10 : OK
2024-02-11 12:18:41 PM: PowerLimit A0 = 15 : OK
2024-02-11 12:18:41 PM: PowerLimit C1 = 15 : OK
2024-02-11 12:18:42 PM: UV: 0 OK
2024-02-11 12:18:44 PM: Mode = 2 : OK                                <----  SILENT MODE
2024-02-11 12:18:44 PM: GET CLOCK LIMIT: NVAPI_GPU_NOT_POWERED
2024-02-11 12:18:44 PM: nvidia-smi -lgc 0,1600
2024-02-11 12:18:46 PM: GPU clocks set to "(gpuClkMin 0, gpuClkMax 1600)" for GPU 00000000:01:00.0 All done.
2024-02-11 12:18:46 PM: GET GPU CLOCKS: 100, 100
2024-02-11 12:18:46 PM: SET GPU CLOCKS: 30, 55
2024-02-11 12:18:49 PM: FanCPU = 1E-40-44-48-4D-5F-61-62-00-01-0D-12-20-33-64-64 : OK
2024-02-11 12:19:00 PM: FanGPU = 1E-40-44-48-4D-5F-61-62-00-01-0B-10-20-33-5B-5B : OK
2024-02-11 12:19:00 PM: Battery Saver detected
2024-02-11 12:19:01 PM: PowerLimit A3 = 6 : OK
2024-02-11 12:19:01 PM: PowerLimit A0 = 6 : OK
2024-02-11 12:19:01 PM: PowerLimit C1 = 6 : OK
2024-02-11 12:19:01 PM: PowerLimit C0 = 5 : OK
2024-02-11 12:19:01 PM: PowerLimit C2 = 80 : OK
2024-02-11 12:19:01 PM: UV: -15 OK
2024-02-11 12:19:57 PM: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
2024-02-11 12:19:57 PM: GET CLOCK LIMIT: NVAPI_GPU_NOT_POWERED
2024-02-11 12:20:09 PM: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
2024-02-11 12:20:09 PM: GET CLOCK LIMIT: NVAPI_GPU_NOT_POWERED
2024-02-11 12:20:19 PM: Varibright: 0,0                        <---- EXTRA SETTINGS OPENED
2024-02-11 12:20:20 PM: Hibernate after 1800
```

I see that more than a minute after setting silent mode you have opened ``Extra`` settings 

How does this "hanging" looks like ? Do you see anything more specific mentioning GHelper in Windows Event Viewer? cause what you have copy-pasted doesn't mention any reasons :)

But what I see is ridiculously low power limits (5W?) that you have set to Silent. I could be that computer generally becomes unresponsive because of that. I would advice to set something higher, at least 10 or just reset it to Factory Defaults.

**Comment by parameter-u** [comment]
Even if power limits are changed to 10, it doesn't change anything. I didn't have any problems with this on the last G Helper version. I've changed them to 10 for now to help with debugging. The "hanging" looks like the application saying that it is not responding, and also, when the power mode is changed upon plugging in, the computer shows either "balanced" or "silent" pop up, not within G helper, and that sticks around on the screen for around a minute until G Helper starts working again. The rest of the computer is completely responsive, it's just that G Helper becomes unresponsive when switching.

I found more things in Event Viewer which was right before the Application Hang error I attached above. I tried to open the file that it mentions in the log, but it seems it cannot be found:

Log Name:      Application
Source:        Windows Error Reporting
Date:          2024-02-11 10:55:56 AM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      
User:          Higgs/Param
Computer:      Higgs
Description:
Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: GHelper.exe
P2: 0.151.0.0
P3: 655e0000
P4: 5130
P5: 67246080
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\Critical_GHelper.exe_3fc966bfba398e4e73a3fccab8010364911b0d8_e03e2c43_fea2accf-91d5-4886-a01f-8d17ae2bac77

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2dec3180-0629-44a0-a630-dae647356925
Report Status: 4
Hashed bucket: 
Cab Guid: 0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" Guid="{0ead09bd-2157-539a-8d6d-c87f95b64d70}" />
    <EventID>1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-11T15:55:56.3294664Z" />
    <EventRecordID>3056</EventRecordID>
    <Correlation />
    <Execution ProcessID="15980" ThreadID="25452" />
    <Channel>Application</Channel>
    <Computer>LuxEtVer1tas</Computer>
    <Security UserID="S-1-5-21-636824772-3513873024-3329200584-1001" />
  </System>
  <EventData>
    <Data Name="Bucket">
    </Data>
    <Data Name="BucketType">0</Data>
    <Data Name="EventName">AppHangB1</Data>
    <Data Name="Response">Not available</Data>
    <Data Name="CabId">0</Data>
    <Data Name="P1">GHelper.exe</Data>
    <Data Name="P2">0.151.0.0</Data>
    <Data Name="P3">655e0000</Data>
    <Data Name="P4">5130</Data>
    <Data Name="P5">67246080</Data>
    <Data Name="P6">
    </Data>
    <Data Name="P7">
    </Data>
    <Data Name="P8">
    </Data>
    <Data Name="P9">
    </Data>
    <Data Name="P10">
    </Data>
    <Data Name="AttachedFiles">
    </Data>
    <Data Name="StorePath">\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\Critical_GHelper.exe_3fc966bfba398e4e73a3fccab8010364911b0d8_e03e2c43_fea2accf-91d5-4886-a01f-8d17ae2bac77</Data>
    <Data Name="AnalysisSymbol">
    </Data>
    <Data Name="Rechecking">0</Data>
    <Data Name="ReportId">2dec3180-0629-44a0-a630-dae647356925</Data>
    <Data Name="ReportStatus">4</Data>
    <Data Name="HashedBucket">
    </Data>
    <Data Name="CabGuid">0</Data>
  </EventData>
</Event>

**Comment by seerge** [comment]
@parameter-u it could be not because of performance mode switch, but because when you unplug app tries to set Eco mode on, and Asus BIOS fails to do that in your case

```
2024-02-11 11:14:41 AM: GPUEco = 1 : 0
```

And here indeed (due to the way asus driver setting that command is done and way g-helper interacts with it) it would hang app's UI until it gets a response (and in your case it waits for a response for a long time)

It can happen if you shut down or reboot in Eco mode first, and then set Standard (check this [topic for more explanation](https://github.com/seerge/g-helper/discussions/1042)) . So you should make sure that ``Enable GPU on shutdown`` is checked under ``Extra``

Can you try to reboot your laptop and see if it solves problem still exists ?

**Comment by parameter-u** [comment]
That seems to have fixed it! Thank you very much!

**Comment by seerge** [comment]
@parameter-u oke, great :) just make sure that ``Enable GPU on shutdown`` is enabled.

But keep in mind, it may not work in some **rare** cases. For example if your laptop hibernates in sleep (while having GPU disabled already). Then app can't enable it, as windows suppresses everything in sleep.
