### ISSUE TITLE
Renaming default power modes

### ISSUE THREAD

**Issue by I-Would-Like-To-Report-A-Bug-Please** [seerge/g-helper#2055]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

No.

### Describe the solution you'd like

It would be great if we could rename default profiles and cycle through them alphabetically when switching them.

I've tried adding into the config `mode_name_0` but it didn't work.

### Device and Model

Usability request

**Comment by seerge** [comment]
@I-Would-Like-To-Report-A-Bug-Please hello. I'm not a big fan of that :) 

Currently default modes are hardcoded cause they are part of app translations (i.e. they are called differently in different languages) + they have own icons and colors.

You can already cycle via them in both directions (by holding Shift) and even directly toggle each via special hotkeys
https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings

**Comment by I-Would-Like-To-Report-A-Bug-Please** [comment]
Gotcha! Can I drag & drop somehow translations to the ghelper dir so it could read them dynamically? Or are they hardcoded during compilation into exe/dll's?

**Comment by seerge** [comment]
@I-Would-Like-To-Report-A-Bug-Please they are hardcoded during compilation.

**Comment by I-Would-Like-To-Report-A-Bug-Please** [comment]
Cool, thought could read them dynamically somehow maybe. I guess it is what it is, thanks for doing such a great job!
