### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by narker** [seerge/g-helper#2057]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I've been getting this popup every so often since updating to 0.151.0.

### How to reproduce the bug?

Unsure how to reproduce

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14241151/log.txt)

### Device and Model

Flow X13 GV301RE

### Additional information.

<img width="329" alt="Screenshot 2024-02-12 133904" src="https://github.com/seerge/g-helper/assets/38026522/7652b47c-4052-49a0-bc77-3fa133dad55a">

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.151.0

### OS

Windows 11

**Comment by seerge** [comment]
@narker can you copy and paste here  full contents of error box ?

**Comment by seerge** [comment]
@narker did you had a chance to try the build ?

**Comment by narker** [comment]
I got that error probably around 5 times the other day but I haven't encountered it since. I did not yet try the new build. I'll update here if I encounter the error again.

**Comment by seerge** [comment]
@narker oke, good. In that build I have added handling for the only possible situation where it would appear.

And it's already live in latest release 0.153.

Closing as completed
