### ISSUE TITLE
Can't set custom hotkeys to F13 (0x7C)

### ISSUE THREAD

**Issue by cakiya** [seerge/g-helper#2059]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I'm trying to rebind M3 or Fn+C to F13 (0x7C according to https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) but it doesn't work. The log seems to indicate that my M3 and Fn+C keys are working, it's just not sending any F13s.

I also tried rebinding one of my mouse buttons to F13 (i have a logitech g304) and it seems to work perfectly, discord detects f13 and it works all fine.

### How to reproduce the bug?

1. Go to "Extra" under "Laptop Keyboard"
2. Under "Key Bindings", change whichever key you want to "Custom", and input the value "0x7C" (this is F13)
3. Go to discord and try to make a new keybind by recording the keystroke or whatever key tester and see that it doesn't send F13 when you press the key
3.1. Rebind your gamer mouse to F13 and watch it input F13 instantly

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14254625/log.txt)

### Device and Model

ROG Zephyrus G14 GA402XV   (it's the 2023 4060)

### Additional information.

![image](https://github.com/seerge/g-helper/assets/43363058/66143397-2800-4bee-9e2d-9c314388ee4e)
![image](https://github.com/seerge/g-helper/assets/43363058/b03ea4bc-00a4-4824-aa44-1cf3a970460a)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.151.0

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@cakiya hello, it could be that windows is refusing to emit that (cause it's just windows API) or may be discord listens to the keys in some non-traditional way.

Try to run app as admin (mb it will help) or try to set different hotkey (or just key combination) in discord / bind it in app?

**Comment by seerge** [comment]
@cakiya ok, I have intentionally installed desktop Discord app, checked how it records "keybindings". It could be cause G-Helper would emit key press, but not key "unpress" after it. While Discord needs it.

Try this build that would do both press / unpress with 1ms delay in-between.

[GHelper.zip](https://github.com/seerge/g-helper/files/14258296/GHelper.zip)

**Comment by cakiya** [comment]
> @cakiya ok, I have intentionally installed desktop Discord app, checked how it records "keybindings". It could be cause G-Helper would emit key press, but not key "unpress" after it. While Discord needs it.
> 
> Try this build that would do both press / unpress with 1ms delay in-between.
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14258296/GHelper.zip)

this works, thank you!
(for the fix and also for making this piece of software ^-^)
