### ISSUE TITLE
Fn F10 (Camera on/off toggle) not working on Vivobook Pro K3500 OLED

### ISSUE THREAD

**Issue by Astrakancafe** [seerge/g-helper#2060]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Ghelper works ok with my Vivobook pro k3500 but not the toggle button Fn F10 which turns on/off the camera.
Nothing urgent, but could be good to have it working.
Thanks for this light tool !

### How to reproduce the bug?

Only using a Vivobook pro ?

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14270803/log.txt)

### Device and Model

Asus Vivobook Pro K3500 Oled

### Armoury Crate

Uninstalled

### Asus Services

Stoped

### Version

0.152

### OS

windows 11 23h2

**Comment by seerge** [comment]
@Astrakancafe hello, 

Can you try to press that Fn+F10 and check what WMI code it writes to app log. Cause on all other devices Fn+F10 is actually a touchpad toggle :) 

And i see that you pressed it few times : 

```
12/02/2024 18:54:04: WMI event 107
12/02/2024 18:54:04: Touchpad status:0
12/02/2024 18:54:05: WMI event 107
12/02/2024 18:54:06: Touchpad status:1
12/02/2024 18:54:09: WMI event 107
12/02/2024 18:54:09: Touchpad status:0
12/02/2024 18:54:11: WMI event 107
12/02/2024 18:54:11: Touchpad status:1
```

Next to that, I honestly don't really know how to toggle camera on your device as well.

Can you try to run following commands in powershell as admin and check if they toggle camera ON or OFF ? 

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00060013; Control_status=0}
```

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00060013; Control_status=1}
```

**Comment by Astrakancafe** [comment]
Hi!
First answer : WMI event 133
Second: these commands do not toggle the camera. 
Fn F9 is the microfone toggle (with a small led in the key) and it works ok.

**Comment by seerge** [comment]
@Astrakancafe oke. It's bad that camera toggle doesn't work as this is  the only known toggle for camera, and I have found it in linux sources 

https://elixir.bootlin.com/linux/v6.2-rc7/source/include/linux/platform_data/x86/asus-wmi.h#L66

May be it will work directly from the app, try this build 
[GHelper.zip](https://github.com/seerge/g-helper/files/14271311/GHelper.zip)

If it doesn't. Can you do a DSDT dump and a scan (method 1 and method 2) from this topic https://github.com/seerge/g-helper/issues/38 and upload them here ?

**Comment by Astrakancafe** [comment]
With this build, there is only the toast message Camera On / Camera Off. But it is not effective : camera is still active (after toggle Off) in skype or google meet for example.
Will try later to do what you asked...

**Comment by Astrakancafe** [comment]
Also, the led in the key that indicates camera Off, is not activated

**Comment by Astrakancafe** [comment]
[dsdt.zip](https://github.com/seerge/g-helper/files/14272608/dsdt.zip)
Method 1 didn't work : error message in powershell saying i'm not authorized to run scripts

**Comment by seerge** [comment]
@Astrakancafe oke, thanks.

If you want, you can try this commands in powershell as admin (in your own risk, cause i don't know what exactly those endpoints toggle)

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00060079; Control_status=0}
```

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00060026; Control_status=0}
```

And check if any of them turn camera OFF ? (``Control_status=1`` could toggle it back) ?

**Comment by seerge** [comment]
If scan will work, what ideally I would like to get is

Scan results with camera toggled ON (via MyASUS or where you can actually toggle it) and scan results with camera toggled OFF.

Then if one of the numbers flips - we know which one is responsible :)

**Comment by Astrakancafe** [comment]
Ok, it worked:
./scan-atkacpi                                                                            60023 : ffffffffffff0004 (-65532)
60024 : 34ec8086 (887914630)
60026 : 0 (0)
60059 : ffffffffffff0000 (-65536)
60061 : 0 (0)
60068 : ffffffffffff0000 (-65536)
60069 : ffffffffffff0000 (-65536)
60079 : 0 (0)
80041 : ffffffffffff0000 (-65536)
80042 : 0 (0)
80043 : ffffffffffff0000 (-65536)
80044 : ffffffffffff0000 (-65536)
100023 : 0 (0)
100054 : ffffffffffff0000 (-65536)
110013 : 23 (35)
110014 : ffffffffffff0000 (-65536)
110015 : ffffffffffff0000 (-65536)
110016 : ffffffffffff0000 (-65536)
110019 : 60002 (393218)
120057 : 80000 (524288)
120061 : 0 (0)
120078 : ffffffffffff0000 (-65536)
130041 : ffffffffffff0000 (-65536)


Did you saw the zip file I uploaded ? DSDT.zip

**Comment by seerge** [comment]
@Astrakancafe yes, thanks. I have even proposed you 2 new endpoints to test with a comment above based on that DSDT

Is this scan for case when camera is ON or OFF ? can you toggle it and try to scan agian?

**Comment by Astrakancafe** [comment]
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00060079; Control_status=0}
--> With Control status = 1 , F10 led is on, which indicates camera is off. But it is still active in google meet or skype
With Control status=0, F10 led truns off

**Comment by Astrakancafe** [comment]
> Is this scan for case when camera is ON or OFF ? can you toggle it and try to scan agian?

It was with Camera ON
I uninstalled MyAsus, so I can't for now toggle the camera

**Comment by seerge** [comment]
@Astrakancafe ok, amazing. We are getting closer. So ``0x00060079` is a LED at least.

Can you try (they come together in DSDT dump, so may be related)

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00040017; Control_status=0}
```

**Comment by seerge** [comment]
And does ``0x00060026`` command produce any results ?

**Comment by Astrakancafe** [comment]
> @Astrakancafe ok, amazing. We are getting closer. So `0x00060079` is a LED at least.
> 
> Can you try
> 
> ```
> Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00040017; Control_status=0}
> ```
> 
> ```
> Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00040017; Control_status=1}
> ```
> 
> (they come together in DSDT dump, so may be related)

These commands toggle F9 (microfone). But microfone still active in skype when toggle OFF

**Comment by Astrakancafe** [comment]
> And does `Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00060026; Control_status=0} ` command produce any results ? as actual camera toggle and camera led are probably separated

Nothing!

**Comment by Astrakancafe** [comment]
Ghelper toggles correctly the microfone : it turns off in skype and the led (on the F9 key) is ON

**Comment by seerge** [comment]
@Astrakancafe oke, strange.

Microfone toggle happens via windows API (i.e. on software level). But I have no idea how to do that for camera.

Can you also try
```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00060023; Control_status=0}
```

**Comment by Astrakancafe** [comment]
> @Astrakancafe oke, strange.
> 
> Microphone toggle happens via windows API (i.e. on software level). But I have no idea how to do that for camera.
> 
> Can you also try
> 
> ```
> Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00060023; Control_status=0}
> ```

Nothing

**Comment by seerge** [comment]
@Astrakancafe oke, what was happening when you disabled camera via myasus (or via hotkey there)? Did it disable device in device manager or just toggled camera access setting in windows somehow ?

**Comment by Astrakancafe** [comment]
Just an other thing, not related with this problem: could be good to be able to assign a function to Fn F12, used to launch MyAsus when installed.

**Comment by seerge** [comment]
@Astrakancafe does Fn+F12 produce any WMI code in a log ?

**Comment by Astrakancafe** [comment]
> @Astrakancafe does Fn+F12 produce any WMI code in a log ?

Yes : WMI event 134

**Comment by Astrakancafe** [comment]
> @Astrakancafe oke, what was happening when you disabled camera via myasus (or via hotkey there)? Did it disable device in device manager or just toggled camera access setting in windows somehow ?
> 
> Cause if you want to disable camera via device manager, you can try
> 
> ```
> Disable-PnpDevice -InstanceId (Get-PnpDevice -FriendlyName *webcam*  -Status OK).InstanceId    
> ```
> 
> In powershell (but it's kind of brute-force approach)

Not sure about that. Also because it is not a function I used. But I think it was like microfone, without disabling camera device.
I will see later this week or next week if I reinstall myasus. Myasus messes up the tool I use to maintain display color calibration. The reason I was happy to find your tool : hotkeys working without Asus stuff !!! Thanks for that !

**Comment by seerge** [comment]
@Astrakancafe ok, cause for now I can offer only disabling device (via the command I linked). But it's generally not the best way to do it.

I can't find any open information on how to toggle camera in windows :( 

Btw, you can just start only Asus Optimization Service - it handles hotkeys for asus. And they all will work (g-helper won't intrude then, if it sees that service running)

**Comment by Astrakancafe** [comment]
Ok, I will try and give a feedback. But not today.
Asus optimization service is also the one that handles oled display control, including calibration stuff, and my color profile loader does not like it ! :)
Thanks, see you soon to try to go further

**Comment by seerge** [comment]
@Astrakancafe ok,

I have added handling for event ``134`` (Fn+F12 in your case). It will do same as M4 / ROG key does in the app (i.e. open G-Helper by default) but you can change action under ``Extra``

And I have change handling for event ``133`` (Fn+F10 in your case). It will :
1. Set Camera LED toggle
2. Try to run powershell command to disable / enable PNP camera device (as I don't have other solution atm)
3. Show notification

Because enabling / disabling device requires admin permissions, you need to run app as admin as well. Otherwise ``133`` won't do anything.

Can you try this build?
[GHelper.zip](https://github.com/seerge/g-helper/files/14277131/GHelper.zip)

**Comment by Astrakancafe** [comment]
It's working ! Camera is disabled in device manager, key led on, and toast message ok
Kind of brutal but it's ok! :o)
I will reinstall asus stuff to see if it disable the device and i will re run the script with camera off. I'll inform you.
Thanks

**Comment by seerge** [comment]
@Astrakancafe it is "brutal" :) but i can't find any other way to set camera ON / OFF. 

You don't even need to install Asus stuff btw, you can just start Asus services via g-helper itself (and then check how FN+F10 is handled by Asus Optimization service)

**Comment by Astrakancafe** [comment]
CAMERA ON

./scan-atkacpi                                                                            60023 : ffffffffffff0004 (-65532)
60024 : 34ec8086 (887914630)
60026 : 0 (0)
60059 : ffffffffffff0000 (-65536)
60061 : 0 (0)
60068 : ffffffffffff0000 (-65536)
60069 : ffffffffffff0000 (-65536)
60079 : 0 (0)
80041 : ffffffffffff0000 (-65536)
80042 : 0 (0)
80043 : ffffffffffff0000 (-65536)
80044 : ffffffffffff0000 (-65536)
100023 : 0 (0)
100054 : ffffffffffff0000 (-65536)
110013 : 2b (43)
110014 : ffffffffffff0000 (-65536)
110015 : ffffffffffff0000 (-65536)
110016 : ffffffffffff0000 (-65536)
110019 : 60002 (393218)
120057 : 80000 (524288)
120061 : 0 (0)
120078 : ffffffffffff0000 (-65536)
130041 : ffffffffffff0000 (-65536)



CAMERA OFF

60023 : ffffffffffff0004 (-65532)
60024 : 34ec8086 (887914630)
60026 : 0 (0)
60059 : ffffffffffff0000 (-65536)
60061 : 0 (0)
60068 : ffffffffffff0000 (-65536)
60069 : ffffffffffff0000 (-65536)
60079 : 1 (1)
80041 : ffffffffffff0000 (-65536)
80042 : 0 (0)
80043 : ffffffffffff0000 (-65536)
80044 : ffffffffffff0000 (-65536)
100023 : 0 (0)
100054 : ffffffffffff0000 (-65536)
110013 : 2a (42)
110014 : ffffffffffff0000 (-65536)
110015 : ffffffffffff0000 (-65536)
110016 : ffffffffffff0000 (-65536)
110019 : 60002 (393218)
120057 : 80000 (524288)
120061 : 0 (0)
120078 : ffffffffffff0000 (-65536)
130041 : ffffffffffff0000 (-65536)

**Comment by Astrakancafe** [comment]
with asus services, camera is not disabled in device manager
the camera led is on (the one on the side of the sensor) but skype detects that camera is not available

**Comment by seerge** [comment]
@Astrakancafe well, most probably it has some tricky way to toggle it off. 

Can you check if it toggles this thing in windows settings ?
![Screenshot 2024-02-14 141904](https://github.com/seerge/g-helper/assets/5920850/5972447d-b5d3-47df-940b-e00c772251c9)

**Comment by Astrakancafe** [comment]
Nope. Asus service do not toggle the camera acces in windows settings
If I disable camera in win settings : camera is enabled in device manager, F10 led is off, camera led is off and skype gives a black image without saying camera is disabled.
Disabling camera in win settings works in a different way

**Comment by seerge** [comment]
@Astrakancafe oke, well, then I don't know how they do it.

But I have found a way to set "Camera Access" checkbox! via windows registry 
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam
```

Can you try this build and check if it works for you ? it should read current status of ``Camera Access`` in settings and set it to opposite. It will requires admin rights tho :)

[GHelper.zip](https://github.com/seerge/g-helper/files/14280232/GHelper.zip)

**Comment by Astrakancafe** [comment]
Working fine !

**Comment by seerge** [comment]
@Astrakancafe what option is better? device manager or camera access ?

**Comment by seerge** [comment]
@Astrakancafe can you also try one more endpoint ?

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00120078; Control_status=0}
```

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00120078; Control_status=1}
```

**Comment by Astrakancafe** [comment]
nothing seems to happen with these endpoints
dont't know which turnaround is better: maybe camera access ?

**Comment by seerge** [comment]
@Astrakancafe I think Camera Access is better, as it won't crash any apps using camera already + it's native windows setting (that you can always set directly as well)

**Comment by Astrakancafe** [comment]
Fine!

**Comment by seerge** [comment]
@Astrakancafe ok. Great. I will include this changes in next release then. Assuming this complete.

**Comment by Astrakancafe** [comment]
good job! thank you
