### ISSUE TITLE
Maybe not a Bug but Still need help since the program doesn't run

### ISSUE THREAD

**Issue by Galthariel** [seerge/g-helper#2063]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Every time I try to run the program I get the following error:

"You must install or update .NET to run this application..." as per the screenshot below

![GHelper_Error](https://github.com/seerge/g-helper/assets/51491805/79a688a1-6e00-4f7f-a2c1-69f5a464c1ea)

### How to reproduce the bug?

1. Uninstalled Armory Crate completely
2. Installed Asus System Control Interface
3. Reboot
4. Checked if have Microsoft .NET 7 and not only the 7 (7.0.16) is installed but also .NET 4, 5, 6, and 8 versions (all x64)
5. Tried to run the program and got the already-mentioned error.
6. I also checked if the .NET Framework was installed and confirmed that both 2.0 and 3.0 are and the 4.8. Checked by going to Turn Windows features on or off.

I did Google to find a solution but couldn't so I wanted to know if someone had a similar issue and share what they did to fix it.

**I few comments that I don't if are relevant:**

1. 1. I kept MyAsus installed
2. 2. Even after uninstalling Armoury Crate using Armoury_Crate_Uninstall_Tool, I found a couple left folders in Program Files, Program Data, and AppData/Local and I don't know if I need to manually delete those folders or leave them there.
3. Reinstalled .NET 7

Thanks in advance for any help

### Logs

All the logs show the same error as the screenshot provided above

### Device and Model

ROG Flow X13 (2022) GV301

### Armoury Crate

Uninstalled

### Asus Services

MyAsus

### Version

0.151

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@Galthariel well, apparently windows thinks that .net 7 is not there

Try to "uninstall" .net 7 (where you see it) and download / install again
https://download.visualstudio.microsoft.com/download/pr/03a5170a-a4cd-458c-b5d0-e5149ee4fdcf/e9026f6fe3c3fec4a774e034d4f98ead/dotnet-sdk-7.0.404-win-x64.exe 

After that

Try to run following in powershell and copy output here
```
dotnet --list-sdks
```

**Comment by Galthariel** [comment]
@seerge I will do it late tonight when I stop working however I do have a question. The .Net link you posted above is for the SDK version and the one I have installed is the Desktop Runtime version. Should I install the SDK version then?

**Comment by Galthariel** [comment]
@seerge  I will do it tonight when I stop working however I do have a question. The link you posted above is for the SDK version and the ones I have installed are the Desktop Runtime versions. Should I install the SDK version then?

![2024-02-14_15-11-37](https://github.com/seerge/g-helper/assets/51491805/151e82be-ffad-428f-adc4-70d1c56e5057)

**Comment by seerge** [comment]
@Galthariel I have included SDK link cause it has all components inside, so then you are 100% sure that everything possible related to .NET7 is installed :) 

https://dotnet.microsoft.com/en-us/download/dotnet/7.0

```
Included runtimes
.NET Runtime 7.0.16
ASP.NET Core Runtime 7.0.16
.NET Desktop Runtime 7.0.16
```

**Comment by Galthariel** [comment]
Will try that and keep you posted. Thanks a lot :-)

**Comment by Galthariel** [comment]
Installing the .NET SDK version did the trick. Thank you very much @seerge for the help and as well for the amazing app. LOVE IT.

**Comment by seerge** [comment]
@Galthariel great, my guess you had to install .NET runtime 7.0 next to desktop runtime (or may be instead)
