### ISSUE TITLE
Internal display doesn't turn on after reboot with XG Mobile and external monitor

### ISSUE THREAD

**Issue by moritzbeck13** [seerge/g-helper#2064]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

iGPU: AMD 680M
dGPU: NVIDIA 3050 Ti
eGPU: AMD 6850M XT

When I have an external monitor connected to the eGPU and then reboot, my internal display doesn't turn on. The boot logo appears on the external monitor instead of the internal display. There seems to be no way for me turn it back on.

I also noticed that no other GPU is listed in task manager, even though the iGPU is listed in device manager. Usually at least the iGPU shows up in task manager under normal operation with the eGPU.
(Is it possible to use the dGPU instead of the iGPU for the internal display and the eGPU for the external monitor?)

The internal display doesn't show up in device manager, the external monitor does though. Windows does not seem to recognize the internal display at all.

### How to reproduce the bug?

How to reproduce:
1. GPU mode: optimized
2. activate XG Mobile
3. reboot

How to fix:
1. disable XG Mobile
2. force reboot

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14290303/log.txt)

### Device and Model

Asus ROG Flow X13 2023 GV301RE

### Additional information.

[config.json](https://github.com/seerge/g-helper/files/14290311/config.json)

### Armoury Crate

Never installed

### Asus Services

0

### Version

0.151.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@moritzbeck13 hello, I see. But I'm afraid that's not something G-Helper can control in a first place. May be that's intended behavior ?

Did you try to do a fresh driver install (may be using AMDcleanup utility?)

And next to that, how it was with Armoury Crate? Any way to check?

**Comment by moritzbeck13** [comment]
I don't think that's intended since I'm literally left with no screen whatsoever after I disconnect the eGPU, so I have to force a reboot by holding down the power button.

I will try cleaning and reinstalling drivers.

I have never installed AC so I can't really tell.
But maybe this has something to do with changing GPUs on shutdown/boot/power disconnect?

**Comment by seerge** [comment]
@moritzbeck13 oke, I'm curious what happens with AC here.

Cause whole XGM control, is pretty much a single command to set it ON or OFF :) Maximum that I can offer - is to disconnect XGM on laptop shutdown ... but i think it might be too much for a default behavior

**Comment by moritzbeck13** [comment]
FWIW this only happens on reboot and not shutdown or standby though. Not sure how that would play out then.
Is there any way this is connected to optimized mode and it recognizing the eGPU as dGPU and then turning off the iGPU?

**Comment by seerge** [comment]
@moritzbeck13 it's not connected with Optimized mode. As Optimized disables / enables dGPU (via absolutely separate command if you unplug / plug in device) 

The only time it happened was at 15.02.2024 02:31:24, when dGPU was enabled again (i.e. set to Standard)
```
15.02.2024 02:31:24: Running eco command 0
15.02.2024 02:31:24: GPUEco = 0 : OK
```

If it happens only on reboot, and not on shutdown - may be it's connected with fast boot somehow? Can you try to enable / or disable it via BIOS settings?

**Comment by moritzbeck13** [comment]
@seerge Disabling fast boot in UEFI actually seems to have fixed it, at least for now. Thanks!
Isn't fast boot supposed to only do something if you are NOT rebooting?

**Comment by seerge** [comment]
@moritzbeck13 i don't know exact reasons :) but I know that G-Helper doesn't and can't control what screens are working. 

And since you mentioned it happens only on reboot, - fast boot was just an option to try.

I'm glad it's working now
