### ISSUE TITLE
TDP issue on battery

### ISSUE THREAD

**Issue by Domilanci** [seerge/g-helper#2065]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Asus TUF A15 2023; Ryzen 7940HS; the tdp of the CPU is 25w max on battery regardless of the slider configuration. With Armoury crate is just less as plugged. tryed to reinstall many time, also reflashed bios. By reinstalling and using armory crate the problem disappears; uninstalling it and using ghelper shows up again. With the pc plugged everything is fine. 
Asus app service and Asus system analisys running, also my asus installed but with autostart disabled

### How to reproduce the bug?

Unplugging the laptop  

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14291347/log.txt)

### Device and Model

Asus TUF A15 FA507 Ryzen 9 7940HS

### Armoury Crate

Uninstalled

### Asus Services

2

### Version

0.151

### OS

Windows 11 22631

**Comment by seerge** [comment]
@Domilanci hello,

1. How do you measure your TDP ? can you post a screenshot?
2. I don't actually see you setting any custom power limits for CPU, you only select one predefined modes (silent/balanced/turbo). Which is absolutely fine, but they are hardcoded in bios and should behave same. 
3. Do you have CPU Boost disabled or enabled under ``Fans+Power`` ? I don't see it log, which means it doesn't change per mode :) but it doesn't show what is current state.

**Comment by seerge** [comment]
P.S. Since you say it's different with AC and G-Helper, the only difference would be default balanced windows power plan. 

Can you try to reset this power plan to all defaults?

Copy and paste the command below into Windows Terminal or Powershell as Admininstrator
```
powercfg -restoredefaultschemes​
```

**Comment by Kikimahe** [comment]
@Domilanci 's answers interests me. :) 

This seems similar to the problem already identified on the AMD and Intel TUF series (and perhaps other series..) :

Laptop on battery or plugged in, if the battery is **<100%**, the bios will limit the TDP to 25W when the dGPU is used (in games for example). 

Armory Crate/Ghelper can't fix anything because ASUS programmed the BIOS like that ! :(((

We already discussed this issue in #864

**Comment by Domilanci** [comment]
@Kikimahe; is only similar because the tdp limit is 25w with only the CPU utilized, like in cinebench r23

**Comment by Domilanci** [comment]
@seerge The restore command results in an error in the cmd (Parametri non validi. Per ulteriori informazioni, provare "/?")
however, effectively creating a custom profile with the "best performance" option, the tdp remains at 45w even after several seconds, as with armory crate. However, by setting "best performance" in other preset modes such as "turbo" it remains at 25w. for the tdp i use HWmonitor with cinebech r23. Thanks for the suggestion, even if the inconvenience of having to create extra profiles to work decently on battery remains. I hope a more immediate way is found

**Comment by seerge** [comment]
@Domilanci 

You need to enter ``powercfg -restoredefaultschemes`` without any extra spaces in the end :) then it will work.

Custom profile (if it was originally created based on turbo) is no different from turbo. It's same thing technically.

Can you post screenshot of a profile that holds 45w and that doesn't here ?

**Comment by Domilanci** [comment]
i'm tryng, stamp rsist now work with such a load on cpu. However con custom Best efficency limit to 15w on long run; balanced on 25w and best performance to 45w. Resetting the profile has no effect; even in custom however the power option in ghelper seems to set the max tdp regardless of the slider (power efficency on custom with the slider all to 80w limit to 15w (obw with the apply button pressed)

**Comment by seerge** [comment]
@Domilanci power mode option in G-Helper is just a shortcut to corresponding setting in windows. You can change it in app - and see how it changes there :)

![Screenshot 2024-02-15 162731](https://github.com/seerge/g-helper/assets/5920850/db477eb2-c843-4f20-8808-31f183bf70ef)

**Comment by seerge** [comment]
@Domilanci so can you post a screenshot of ``Fans+Power`` page a profile that works ok and that doesn't?

**Comment by Domilanci** [comment]
![20240215_163050](https://github.com/seerge/g-helper/assets/160092740/a3c1fbe2-2368-4ddd-af41-022cd033b088)
![20240215_163415](https://github.com/seerge/g-helper/assets/160092740/cdd1ec63-7e82-4263-9c45-b7f0d503cc12)
@seerge after reset powerplan in cmd is blocked even in custom 1, with best performance at 25w

**Comment by seerge** [comment]
@Domilanci 

``Custom1`` is based on Silent profile in your case (i see it by green color). When you click (+) to create a new profile, it uses currently selected one as base. Try to use Turbo for that. 

Also I see that power limits are not applied in ``Custom``

`Turbo`` - Can you also try to click "Apply custom fan curve" ? (so both power and fan checkboxes are selected). Some models require both things to be applied in order to make power limits work.

**Comment by Domilanci** [comment]
![20240215_164154](https://github.com/seerge/g-helper/assets/160092740/9a12ef0c-3ffc-499a-85f1-ea69e88bedae)
@seerge thank you for the support, so even changing the power mode in the profile have no effect if is based on silent?
However seems to be a pattern: if when i unplug the pc is selected a standard profile, even changing it the cpu does not pass the 15w, or 25w depending on the power mode; if i select a custom profile and i unplug everything is normal; balanced limit to 35w and best performance to 45w (custom 1 and 2) work ok, also cyclink between custom 1 and 2, but selecting a standard profile make the problem come back, also reselect a custom profile didn't work, 25w max... so seems like the standard profile change something deep in the bios, so deep that on battery they limit all the profile when selected. Reconnect the pc on the charger and reselect a custom problem solved the problem again (until a standard one is selected on battery). i apologize for my english, but i'm italian

**Comment by Domilanci** [comment]
[log.txt](https://github.com/seerge/g-helper/files/14299042/log.txt)
this is the log since i reboot, if it can help

**Comment by seerge** [comment]
@Domilanci 

Did you try to click Apply next to Fan curve as well? Cause **it's not in** your log.

### For the reference

All ASUS devices come with 3 predefined (hardcoded in BIOS) modes - Silent, Balanced (Performance in AC) and Turbo. Each mode has it's own default power limits, fan curves, etc. Those power limits can be different for battery / plugged in situations. It could be that your device is programmed in BIOS to have 35W sustained limit on battery for example.

Both AC and G-Helper let you customize them, by applying custom power limits and fan curves (via special asus endpoints), but those limits are still handled by BIOS, and if it's set to stay below some level - it will.

Windows Power Mode only affects how actively windows itself would allow CPU to be used, but since it's set to "Best Performance", it should be ok in your case.

---

What power limits do you get when you run Silent / Balanced / Turbo in Armoury Crate on battery ?

**Comment by Domilanci** [comment]
@seerge 
from the test i done with Armoury crate before installing ghelper
in turbo it stay between 45w and 55w on battery, in silent i don't remember exactly but sure not less than 35w, probably 45.
if it come handy i can reinstall all the asus stuff and done more test but it requires time. However the cinebench scoore on battery was around 15000-15500 (on silent was almost the same, interestlingly), comparable with the Jarrod's tech one, and plugged around 17000. Now on turbo is the same plugged but 12500 on battery, on silent and battery almost the same again.
even in log file C0 is setted to 25 so there is something whrong for sure imho

**Comment by Kikimahe** [comment]
`PowerLimit C0 = 25 `est le dynamic Boost du GPU. ;-)

**Comment by seerge** [comment]
@Domilanci if you tested Armoury's default modes (i.e not custom), you should keep power limits not applied in G-Helper as well, just set Power mode to Best Performance and enable Boost.

I really doubt AC sets anything next to just selecting same modes.

I can't really "fix" anything here, as G-Helper is not limiting anything here :)

``C0`` is GPU dynamic boost, so has nothing to do with that :)

**Comment by Domilanci** [comment]
@seerge thanks again for the support and the program that is excellent; i'll go deeper in this question in the next week, i'll let you know if the problem is resolved. A last thing: Is there a way to know the power limit setting in general?

**Comment by seerge** [comment]
@Domilanci you can use HWinfo app, there it will show your current CPU usage (same as CPUID) and also percentage of current FAST / SLOW limits. So you can calculate limits from there.

Another way is to run this app https://github.com/FlyGoat/RyzenAdj/releases 

As admin
```./ryzenadj -i``

It will list your current limits reading it directly from AMD driver.

**Comment by seerge** [comment]
@Domilanci any updates here?

Just in case check this issue https://github.com/seerge/g-helper/issues/2073 (part related to power limits)

This is a good example how asus may just forget to implement power limits at all ... or how bios may decide to increase power limits to maximum when just custom fan curve is enabled :)

**Comment by seerge** [comment]
Closing as abandoned
