### ISSUE TITLE
"M" Hot keys not working as expected

### ISSUE THREAD

**Issue by riyanshlunia** [seerge/g-helper#2068]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I configured the hotkeys to play and pause but the problem I am facing is that it doesn't work on spotify when it is in background whereas If I use edge and play youtube on it it works like I can play and pause the video but same doesn't go with spotify when I try to play/pause spotify it doesn't work no matter if it's the only app playing media in the background

### Describe the solution you'd like

I want you to help me to find a way soo that I can pause apps like spotify directly using the key instead of having to go back to the app and pause it

### Device and Model

FX507ZE

**Comment by seerge** [comment]
@riyanshlunia that's not a feature request.

I have no idea why your spotify does't work. If Media keys work in other apps - it means G-Helper emits them correctly.

I was recently doing other tweak for custom hotkeys, so you can check build from this topic https://github.com/seerge/g-helper/issues/2059

And since you ignored correct issue template and didn't include logs, I can't help anyhow further

**Comment by riyanshlunia** [comment]
No it works fine until and unless their s application in the full screen then only the spotify stops other times it works perfectly fine even in the background

**Comment by riyanshlunia** [comment]
I didn't wrote the template completely cuz I have no idea what could you do to fix it

**Comment by seerge** [comment]
@riyanshlunia well, then it's clearly something with the spotify itself :) but i still advice to try build from that other issue.

**Comment by riyanshlunia** [comment]
alright thanks I'll try it out and let you know
