### ISSUE TITLE
Battery charge limit.

### ISSUE THREAD

**Issue by LeoRH123** [seerge/g-helper#2069]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Today my battery keeps charging above 60% limit, when I see I had 83% I opened G-helper and switch the limit to 55% then back to 60% and it stopped charging my battery.

### How to reproduce the bug?

1. put the laptop to sleep
2. wake up from sleep
3. check the current battery charge.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14305894/log.txt)

### Device and Model

ASUS TUF Gaming A15 FA506QM

### Additional information.

I don't know if this might cause the problem, but I had GameVisual from Asus installed (I uninstall it and stopped the 6 Asus services just in case this caused the issue), I let you the log file.

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.151.0

### OS

Windows 11 23H2

**Comment by Kikimahe** [comment]
Hi, 

You had this service running in your log.
`2/15/2024 6:55:40 PM: Optimization service is running`

Asus optimization service uses this file for charge limit settings.
`C:\ProgramData\ASUS\ASUS System Control Interface\AsusOptimization\Customization.ini`

You must stop the ASUS Optimization service or/and set the same load limit in My ASUS and Ghelper (60%) :)

**Comment by seerge** [comment]
@LeoRH123 hello, it is working, but you need to either stop asus service or use myASUS to set limit there as well as @Kikimahe said.

Please check corresponding FAQ section, it's covered in a high details there along with other related moments

https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working

Good luck
