### ISSUE TITLE
Sleep not working in ultimate mode.

### ISSUE THREAD

**Issue by Dexorv0** [seerge/g-helper#2078]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hello, I have an Asus Zephyrus M16 GU604VI,
This is not like a major issue rather a detail but I have noticed that when the laptop is in Ultimate mode and then goes to sleep, the screen is completely black, nothing moves but I see that the camera turns on for windows hello but that's it, I have to press the button to shut the laptop down and then reboot it, this sometimes happened also in optimized (unplugged) mode but not anymore.

### How to reproduce the bug?

Put the laptop in Ultimate mode and let it go to sleep or use the sleep button.

### Logs

[021724-14187-01.dmp](https://github.com/seerge/g-helper/files/14321677/021724-14187-01.dmp)
[log.txt](https://github.com/seerge/g-helper/files/14321678/log.txt)

It happened on the 02/18/2024 at 6:01pm

### Device and Model

Asus Zephyrus M16 GU604VI

### Additional information.

![Screenshot 2024-02-18 001858](https://github.com/seerge/g-helper/assets/137844420/191b1b17-ae1d-46ac-9e77-b61b99389435)
![Screenshot 2024-02-18 001949](https://github.com/seerge/g-helper/assets/137844420/c411e029-a30a-4ada-b8a2-0eef63490232)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.151.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Dexorv0 hello,

That's s a disappointment of course, but i'm afraid it's not connected to the app.

It's something happening between (often broken) windows sleep and NVidia drivers.

Try to do a clean drivers reinstall using DDU as suggested in Troubleshooting section?

And may be launch full cycle of windows maintenance via app with the same name? :) it sometimes helps to tackle sleep issues.

**Comment by seerge** [comment]
P.S. One more advice, before you reboot your ultimate mode - try to make sure that you have GPU enabled (i.e. set Standard mode or. plug in Optimized). It happens automatically, but may be windows / drivers will behave a bit differently if it that's done a bit beforehand:)

**Comment by Dexorv0** [comment]
I somewhat knew it wouldn't be related. 
Anyway I'll try that and post it here if that helps anyone.
By the way just wanted to say that the app is amazing so far thank you so much for doing that !

**Comment by seerge** [comment]
@Dexorv0 great, good luck!
