### ISSUE TITLE
When click Fn + F5 + Shift it uses reverse order for changing mode.

### ISSUE THREAD

**Issue by AgeStaR** [seerge/g-helper#208]
Hello! Thanks for your efford for this tool. 
I just want to change mode from balanced to silent via one action. Currently If I want to change mode from balanced to silent I have to do the following steps:
Balanced -> Turbo -> Silent. 
It will be nice if I use Fn + F5 (Fan mode button) + Shift and it return from balanced to silent mode.
And in general it will be look like this: balanced -> silent -> turbo.

**Comment by seerge** [comment]
Added in https://github.com/seerge/g-helper/releases/tag/v0.49 :)
