### ISSUE TITLE
FN+function key double press/register on press and release

### ISSUE THREAD

**Issue by PeekOFarad** [seerge/g-helper#2081]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When switching between fan profiles (FN+F5) a key press is recognized both on the depress and release of the key. This makes it impossible to set certain profiles. When changing brightness (FN+F7/F8) the input is recognized twice on pressing the button. 

### How to reproduce the bug?

FN+F5/F7/F8

I do not have clue how to reproduce it on other machines. It happened on mine after updating to the newest version of G helper.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14323485/log.txt)

### Device and Model

ASUS ROG SCAR II GL704G

### Armoury Crate

Uninstalled

### Asus Services

1

### Version

G-helper 0.151.0

### OS

Windows 10 22H2 19045.4046

**Comment by seerge** [comment]
@PeekOFarad hello, you have asus optimization service running in background that interferes.

Just stop it from 'Extra' settings  and it will be fine :)

**Comment by PeekOFarad** [comment]
> @PeekOFarad hello, you have asus optimization service running in background that interferes.
> 
> Just stop it from 'Extra' settings and it will be fine :)
Hi @seerge, I have already tried that (should've mentioned it, my bad). The service doesn't seem to want to stay dead tho, i.e.: there's always one asus service running even after clicking the stop button.

**Comment by seerge** [comment]
@PeekOFarad ok, try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/14323761/GHelper.zip)

**Comment by PeekOFarad** [comment]
This one works, thanks @seerge!

**Comment by seerge** [comment]
@PeekOFarad great
