### ISSUE TITLE
GX650PY 319 BIOS update breaks some G-Helper features

### ISSUE THREAD

**Issue by fscottcopeland** [seerge/g-helper#2082]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Seem to have lost ability to control MUX switch, as well as fan curves. Might be other things I can't control anymore which I'm not aware of.

### How to reproduce the bug?

I suppose just try and run G-Helper on BIOS 319.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14323672/log.txt)

### Device and Model

Zephyrus Duo 2023 GX650PY

### Additional information.

Let me know what else you need to help fix this!

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.151.0

### OS

Win 11 23H2 (OS Build 22631.3155)

**Comment by fscottcopeland** [comment]
Just updated to 0.154.0 and issues not resolved.

**Comment by seerge** [comment]
@fscottcopeland i see that Asus control interface is disabled on your device.  So neither G-Helper nor Armoury won't work on your device.

Try to reinstall it completely as explained in https://github.com/seerge/g-helper/wiki/Troubleshooting

Or even reinstall BIOS again if it won't help, as something clearly went wrong during your update 

I can't do anything here :)

**Comment by fscottcopeland** [comment]
How strange! Yes - all fixed now. I did a Windows update and a BIOS update. Somehow it must have nuked the ASUS control interface install.
