### ISSUE TITLE
G-helper blocks task bar when opening. 

### ISSUE THREAD

**Issue by skyhi69** [seerge/g-helper#2083]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

When G-helper is opened (clicking on the icon on the task bar) when it opens it blocks all but the lower 1/4 task bar and blocks all the icons for wifi, volume and time. (I am running Windows 11 on a asus rog zephyrus m16 ips screen with the task bar auto hidden) 

### Describe the solution you'd like

Have G-helper open up just a little higher so that it does not automatically block any of the task bar, thus avoiding having to move it to see the time or adjust the volume or wifi. 

### Device and Model

Asus rog zephyrus m16 gu604vi

**Comment by seerge** [comment]
@skyhi69 can you post a screenshot of?

Do you have taskbar set to autohide?

**Comment by skyhi69** [comment]
Yes on auto hide, but it's just a tad inconvenient to have to move G-helper up like a half cm to see the icons below. 
<img width="1280" alt="Screenshot 2024-02-18 183405" src="https://github.com/seerge/g-helper/assets/143546871/46e898fb-03db-46e7-9b84-1515fde0646a">
<img width="1280" alt="Screenshot 2024-02-18 183429" src="https://github.com/seerge/g-helper/assets/143546871/90c83d48-1c00-4973-bc90-930108bf99d8">

**Comment by seerge** [comment]
@skyhi69 P.S. I see that your browser behaves same as G-Helper, it is located lower than task bar

Just turn off Always on Top option from Extra in the app, so it will go behind task bar instead of above

**Comment by skyhi69** [comment]
Duh, on me.. I didn't realize what that setting actually meant. Thanks for your quick response and tolerance of ignorance! lol

**Comment by seerge** [comment]
@skyhi69 oke, then i assume you have found a workaround.

I can't fix position cause app just doesn't know if taskbar is hidden or not, and windows reports whole screen as working area.
