### ISSUE TITLE
"Disable screen overdrive" ?

### ISSUE THREAD

**Issue by titoBouzout** [seerge/g-helper#2084]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Can you please clarify what "screen overdrive" means?

### Describe the solution you'd like

A tooltip on the checkbox detailing a more understatable description sounds nice

### Device and Model

G713QR

**Comment by seerge** [comment]
@titoBouzout hello. It's actually quite self explanatory.

By default your maximum refresh rate will be paired with screen overdrive (for better response times)

That checkbox would remove overdrive from the equation

Keep in mind that on some old models where overdrive has never existed, that option has no effect:)

**Comment by titoBouzout** [comment]
> self explanatory

If it were self explanation I wouldn't have asked.. 


> By default your maximum refresh rate will be paired with screen overdrive (for better response times)

> That checkbox would remove overdrive from the equation

mmh, ok thanks, adding a short description to the checkbox would be welcome, I had no idea what overdrive means or does.  you already have a tooltiptext for 1 checkbox, adding another I guess is not a big deal?

**Comment by seerge** [comment]
@titoBouzout hello,

Overdrive is general term. It's not specific to G-Helper or Asus

https://en.wikipedia.org/wiki/Response_time_compensation

**Comment by titoBouzout** [comment]
Thanks, I didn't know that. When I searched google for overdrive that Wikipedia entry didnt show up. 

I still think it won't harm to add a simple tooltiptext.....  just like the clamshell is explained in a tooltiptext

**Comment by seerge** [comment]
@titoBouzout i also don't know why people need it, but multiple users has explicitly asked for that, so I have added it to extra (where other rarely used options are collected) :)
