### ISSUE TITLE
CPU temperature not showing near fan speed

### ISSUE THREAD

**Issue by skipster1337** [seerge/g-helper#2089]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The CPU temperature is not showing near the fan speed as expected. I believe an update to G-Helper broke it.
![2024-02-19 15_23_33-G-Helper — ASUS TUF Gaming A15 FA506IU](https://github.com/seerge/g-helper/assets/91155070/f2c529b2-91d9-458e-95cc-6c33c6f9e4f8)
![Untitled](https://github.com/seerge/g-helper/assets/91155070/8e550840-0de2-449a-a15f-fef9a8a2b0bf)

### How to reproduce the bug?

1. Have TUF A15 FA506IU
2. Update G-Helper around this week
3. See CPU temperature missing

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14331624/log.txt)

### Device and Model

ASUS TUF A15 FA506IU

### Armoury Crate

Never installed

### Asus Services

None

### Version

0.151.0

### OS

Windows 10 22H2

**Comment by seerge** [comment]
@skipster1337 hello, that part is unchanged in the app for like a year.

It tries to take temperature from Bios sensor, and if it's bot supported there - just from windows.

Dis you update any drivers recently?

Did you try rebooting? may be it's some hiccup in windows metrics

**Comment by skipster1337** [comment]
I powered off completely and started the laptop again and it still has the same problem. I don't remember updating any drivers recently, the rest of the app works just fine and apps like Afterburner and HWInfo can read the CPU temperature.

**Comment by seerge** [comment]
@skipster1337 you say its after some update, can you just download older version from Releases page and check if it's visible there for a sake of experiment?

**Comment by skipster1337** [comment]
I tried 0.149 and 0.145 and they also have the same issue, even though older versions displayed the temperature fine. I guess it's not a G-Helper-specific issue then, although I am confused at why it doesn't work anymore.

**Comment by ChitaJazz** [comment]
I also encountered a similar problem, when the cpu temperature is about 60 degrees, the fan speed will reach the maximum speed set, and it will return to normal speed after about 15 minutes.My device and model is the ROG strix G713PV.

**Comment by seerge** [comment]
@skipster1337 well, then i honestly don't know what to offer here

Try to run following command in powershell as admin 

Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DSTS -Arguments @{Device_ID= 0x00120094}

It's a CPU temp reading from bios (via asus driver)

Btw, mb try to reinstall Asus System Control Interface as explained in Troubleshooting section?

**Comment by seerge** [comment]
@ChitaJazz i don't think that your situation has anything common with the issue here :) 

Fans are always controlled by BIOS, and it could be programmed to behave like that for your model

**Comment by skipster1337** [comment]
> @skipster1337 well, then i honestly don't know what to offer here
> 
> Try to run following command in powershell as admin
> 
> Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DSTS -Arguments @{Device_ID= 0x00120094}
> 
> It's a CPU temp reading from bios (via asus driver)
> 
> Btw, mb try to reinstall Asus System Control Interface as explained in Troubleshooting section?

I ran the command, here's the output:
![2024-02-19 20_13_34-Administrator_ Windows PowerShell](https://github.com/seerge/g-helper/assets/91155070/66665676-a1b3-4e73-b3e7-b9921cb32cff)

I also tried reinstalling the Asus System Control Interface Driver and it didn't do anything.

**Comment by seerge** [comment]
@skipster1337 one, it means that bios sensor is not there at all (probably cause you have old device)

App has a fallback to windows readings

Can you check what Performance Monitor app reports as shown on screenshots?

Values there are in Kelvins :) so will be 300+

![Screenshot 2024-02-19 192902](https://github.com/seerge/g-helper/assets/5920850/02c21fca-481c-4913-9854-52b30a06fa57)
![Screenshot 2024-02-19 193057](https://github.com/seerge/g-helper/assets/5920850/e068fc79-384c-4ae5-83b0-29e69bcf31a7)

**Comment by skipster1337** [comment]
![2024-02-19 20_59_52-Window](https://github.com/seerge/g-helper/assets/91155070/05d7677f-b8dc-4739-960c-2a6d39e924f0)

**Comment by skipster1337** [comment]
Also I'm not sure if this is useful in any way but I can see the CPU temperature and voltage in the BIOS.

![2024-02-19 21_05_46-20240219_210337 jpg (JPEG Image, 4624 × 3468 pixels) — Scaled (27%) — Mozilla Fi](https://github.com/seerge/g-helper/assets/91155070/0376d3fa-51aa-45ba-8e3c-99bbf273f311)

**Comment by seerge** [comment]
@skipster1337 one, can you check this build and post a log from it

[GHelper.zip](https://github.com/seerge/g-helper/files/14336101/GHelper.zip)

**Comment by skipster1337** [comment]
> @skipster1337 one, can you check this build and post a log from it
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14336101/GHelper.zip)

[log.txt](https://github.com/seerge/g-helper/files/14336107/log.txt)

**Comment by skipster1337** [comment]
Ok, I fixed it. Looks like something broke the performance counters on my system somehow? I googled the error and found a Microsoft article which showed how to rebuild the counters. Now the CPU temp displays fine. What a weird issue.
https://learn.microsoft.com/en-us/troubleshoot/windows-server/performance/manually-rebuild-performance-counters
![2024-02-19 21_18_02-G-Helper — ASUS TUF Gaming A15 FA506IU](https://github.com/seerge/g-helper/assets/91155070/d6cbed20-605d-4ca3-b5d6-2dba6a744b44)

**Comment by seerge** [comment]
@skipster1337 it says 
19/02/2024 21:12:28: Failed reading CPU temp :Cannot load Counter Name data because an invalid index '' was read from the registry. Performance counters on the machine may need to be repaired.

So something is broken in windows
try to run restore as explained here https://github.com/seerge/g-helper/wiki/Troubleshooting#repair-corrupted-system-fails

**Comment by seerge** [comment]
@skipster1337 ok, great
