### ISSUE TITLE
Z13 Flow Program wont start 

### ISSUE THREAD

**Issue by Allenchens** [seerge/g-helper#2090]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The program does not start at all on 2023 z13 flow bios v310
I get the following errors in event viewer
Faulting application name: GHelper.exe, version: 0.151.0.0, time stamp: 0x655e0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3155, time stamp: 0x8c2ee5db
Exception code: 0xe0434352
Fault offset: 0x0000000000065b0c
Faulting process id: 0x0x2790
Faulting application start time: 0x0x1DA63A2B47E69F0
Faulting application path: C:\Users\c\Downloads\GHelper.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: f3502a69-8742-4724-b980-b1346682b4bf
Faulting package full name: 
Faulting package-relative application ID: 

Application: GHelper.exe
CoreCLR Version: 7.0.1624.6629
.NET Version: 7.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at AppConfig.GetModel() in D:\a\g-helper\g-helper\app\AppConfig.cs:line 96
   at GHelper.Program.Main(String[] args) in D:\a\g-helper\g-helper\app\Program.cs:line 70

### How to reproduce the bug?

click ghelper 

### Logs

2/19/2024 8:00:24 PM: ------------
2/19/2024 8:08:12 PM: ------------
2/19/2024 8:10:59 PM: ------------
2/19/2024 8:12:58 PM: ------------
2/19/2024 8:24:32 PM: ------------
2/19/2024 9:15:42 PM: ------------

### Device and Model

Z13 Flow GZ301VU

### Armoury Crate

Uninstalled

### OS

Windows 11

**Comment by Allenchens** [comment]
@seerge it seems my WMI was the problem, it was corrupted somehow , after fixing the WMI the program works fine now. Thank you!

Attaching log just in case you still want to see it.
![Screenshot 2024-02-20 031315](https://github.com/seerge/g-helper/assets/145303282/1b84ca25-afe9-45af-8d7e-e17062524529)

2/19/2024 8:00:24 PM: ------------
2/19/2024 8:08:12 PM: ------------
2/19/2024 8:10:59 PM: ------------
2/19/2024 8:12:58 PM: ------------
2/19/2024 8:24:32 PM: ------------
2/19/2024 9:15:42 PM: ------------
2/19/2024 9:29:40 PM: ------------
2/20/2024 3:10:59 AM: ------------
2/20/2024 3:10:59 AM: App launched:  :0.154.0.0en-US
2/20/2024 3:10:59 AM: Matrix control device was not found on your machine.
2/20/2024 3:11:00 AM: NVIDIA GeForce RTX 4050 Laptop GPU
2/20/2024 3:11:00 AM: Invalid class 
2/20/2024 3:11:00 AM: CPU: 99999 -  - 
2/20/2024 3:11:00 AM: AutoSetting for Online
2/20/2024 3:11:00 AM: Optimization service is running
2/20/2024 3:11:00 AM: Mode = 0 : OK
2/20/2024 3:11:00 AM: Power Plan 381b4222-f694-41f0-9685-ff5bb260df2e:OK
2/20/2024 3:11:00 AM: Power Mode 00000000-0000-0000-0000-000000000000:OK
2/20/2024 3:11:00 AM: Eco flag : 0
2/20/2024 3:11:00 AM: Mux flag : 0
2/20/2024 3:11:00 AM: \\?\DISPLAY#TMX0001#5&1745ffb8&0&UID4354#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
2/20/2024 3:11:00 AM: \\?\DISPLAY#TMX0001#5&1745ffb8&0&UID4354#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2/20/2024 3:11:00 AM: Init 1A30: 5D-B9
2/20/2024 3:11:00 AM: Init 1A30: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2/20/2024 3:11:00 AM: Init 1A30: 5D-05-20-31-00-1A
2/20/2024 3:11:00 AM: Init 18C6: 5D-B9
2/20/2024 3:11:00 AM: Init 18C6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2/20/2024 3:11:00 AM: Init 18C6: 5D-05-20-31-00-1A
2/20/2024 3:11:00 AM: USB 1A30: 5D-BD-01-FF-1F-FF-FF-FF
2/20/2024 3:11:00 AM: USB 18C6: 5D-BD-01-FF-1F-FF-FF-FF
2/20/2024 3:11:00 AM: AuraMode: AuraStatic
2/20/2024 3:11:00 AM: USB 1A30: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
2/20/2024 3:11:00 AM: USB 1A30: 5D-B5-00-00-00
2/20/2024 3:11:00 AM: USB 1A30: 5D-B4
2/20/2024 3:11:00 AM: USB 18C6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
2/20/2024 3:11:00 AM: USB 18C6: 5D-B5-00-00-00
2/20/2024 3:11:00 AM: USB 18C6: 5D-B4
2/20/2024 3:11:00 AM: Monitor Power On
2/20/2024 3:11:00 AM: Lid Open
2/20/2024 3:11:00 AM: Lid 1A30: 5D-BA-C5-C4-01
2/20/2024 3:11:00 AM: Lid 18C6: 5D-BA-C5-C4-01
2/20/2024 3:11:01 AM: Auto 1A30: 5D-BA-C5-C4-01
2/20/2024 3:11:01 AM: Auto 18C6: 5D-BA-C5-C4-01
2/20/2024 3:11:01 AM: Invalid class 
2/20/2024 3:11:01 AM: CPU: 99999 -  - 
2/20/2024 3:11:02 AM: Latest version 0.154.0.0
2/20/2024 3:11:10 AM: Design Capacity: 56002mWh, Full Charge Capacity: 53927mWh, Health: 0.9629477518660047855433734509%
2/20/2024 3:11:57 AM: WMI event 234

**Comment by seerge** [comment]
@Allenchens great, how did you fix the wmi? i may add it to faq

**Comment by Allenchens** [comment]
@seerge I used method 2 from this Method 1 did not work for me

https://answers.microsoft.com/en-us/windows/forum/all/cannot-access-the-windows-management/8849f190-cf4b-e011-8dfc-68b599b31bf5
