### ISSUE TITLE
G14 GA402RK - iGPU will not be disabled when the Ultimate mode is enabled.

### ISSUE THREAD

**Issue by DontCloseYourEyes** [seerge/g-helper#2091]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I ran into the problem that the laptop's integrated GPU will not be disabled when the Ultimate mode is enabled. The iGPU still consumes power.

### How to reproduce the bug?

1. Open GHelper
2. Turn the Ultimate mode on and reboot the laptop
3. Open Device Manager in Windows
4. Make sure AMD Radeon(TM) Graphics is enabled
5. Open AMD Software: Adrenalin Edition
6. Go to the Performance tab
7. Make sure AMD Radeon(TM) Graphics has metrics

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14339020/log.txt)

### Device and Model

Asus Rog Zephyrus G14 (2022) GA402RK

### Additional information.

AMD Software: Adrenalin Edition Version 24.1.1

![image](https://github.com/seerge/g-helper/assets/130186740/f2cc0751-03d0-44c5-a901-d223ddbb6856)
![image](https://github.com/seerge/g-helper/assets/130186740/941139d0-bb4f-4322-8132-46f46d43672c)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.154.0

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@DontCloseYourEyes hello,Ultimate mode is about routing internal display to dGPU.

It has nothing to do with disabling iGPU
