### ISSUE TITLE
Can't save Windows Power Mode

### ISSUE THREAD

**Issue by y547153** [seerge/g-helper#2094]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Windows Power Mode in any tab can't setting
![image](https://github.com/seerge/g-helper/assets/7712097/a31f4ae4-d08e-4619-b52a-8ed4a198b69e)

### How to reproduce the bug?

1.Choosed Windows Power Mode to Best Performance in Performance mode tab.
2.switch to Balanced mode
3.switch back to Performance mode
4.Windows Power Mode well return to Balanced

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14349775/log.txt)

### Device and Model

TUF A15 FA506IV

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

 151

### OS

win10 22H2

**Comment by seerge** [comment]
@y547153 hello, app sets "Best performance" power mode each time you select turbo

```
2024/2/21 å‘¨ä¸‰ 2:27:24: Mode = 1 : OK
2024/2/21 å‘¨ä¸‰ 2:27:24: GET CLOCK LIMIT: 0
2024/2/21 å‘¨ä¸‰ 2:27:24: GET GPU CLOCKS: 0, 0
2024/2/21 å‘¨ä¸‰ 2:27:24: SET GPU CLOCKS: 190, 90
2024/2/21 å‘¨ä¸‰ 2:27:24: Power Plan 6fecc5ae-f350-48a5-b669-b472cb895ccf:OK
2024/2/21 å‘¨ä¸‰ 2:27:24: Power Mode ded574b5-45a0-4f42-8737-46345c09c238:OK
```

So it does what it should do.

I see that you also use some custom power plan (set manually via config).

That power plan could be overriding that. 

Try to stick to default windows "Balanced" power plan.

**Comment by seerge** [comment]
@y547153 did you try using default power plan?

**Comment by seerge** [comment]
Closed as abandoned and cause there is nothing to fix in the app.

**Comment by y547153** [comment]
> @y547153 did you try using default power plan?

on TUF A15 FA506IV "Chinese ver. also called 天选1" only the default power plan High performance can boost the GPU clock and enhance CPU and GPU fan RPM .
G-helper can't max out the fan RPM so I need that power plan
My computer has already fried GPU power supply due to G-helper reset the power plan.
And on the newer version 154 G-helper, my config.json been reset.
I turn the G-helper off and modify the config , and I turn G-helper off my config got reset

**Comment by y547153** [comment]
restart a few times, now config works fine.

**Comment by y547153** [comment]
Is "Windows Power Mode" only showed Windows default power plan?
If is that, should add a hint that "is using custom power plan 'XXX' "

**Comment by seerge** [comment]
> on TUF A15 FA506IV "Chinese ver. also called 天选1" only the default power plan High performance can boost the GPU clock and enhance CPU and GPU fan RPM .

Fan RPM has absolutely nothing to do with windows power plans. That's nonsense. Fans are controlled by BIOS. 

> G-helper can't max out the fan RPM so I need that power plan
G-Helper doesn't control fans, they are always controlled by BIOS. Read FAQ.

>Is "Windows Power Mode" only showed Windows default power plan?
If is that, should add a hint that "is using custom power plan 'XXX' "

Windows power mode exists in all power plans, but some power plans may override that. It's outside of app control.

**Comment by seerge** [comment]
@y547153 

>the "High performance" power plan not the windows default High performance ,Is by the Asus

It doesn't change the fact that fans are controlled by BIOS.
