### ISSUE TITLE
Custom fan curves will support for more models if you use AsusWinIO64.dll

### ISSUE THREAD

**Issue by SenevirathneSMRH** [seerge/g-helper#2095]
### Is your feature request related to a problem? Please describe

I get an error when i try custom fan curve. it says rejected by bios 

### Describe the solution you'd like

fan curve will support for more many models if use AsusWinIO64.dll you can do it. because i have test some programs that uses this AsusWinIO64.dll and they worked. even most popular [Rem0o/FanControl](https://github.com/Rem0o/FanControl.Releases) not works with my laptop model.

### Describe alternatives you've considered

[Legend0fHell/FanControlPP](https://github.com/Legend0fHell/FanControlPP/tree/master) but it lacks features but it can control fans manually

### Device and Model

Asus Vivobook 15 X513

**Comment by seerge** [comment]
@SenevirathneSMRH hello,

G-Helper can optionally set fan curves in exactly same way as Armoury does it.

If they are not supported by your device in a first place, and you didn't have them in AC - they wouldn't magically work in g-Helper neither:)

I don't plan to add unofficial tricks to control fans, sorry. As whole idea of the app is to be lightweight ac replacement.

**Comment by seerge** [comment]
@SenevirathneSMRH Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks
