### ISSUE TITLE
decoupling core temp limit and undervolting

### ISSUE THREAD

**Issue by alex450** [seerge/g-helper#2098]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

the undervolting function is coupled with core temp limit 
and it overrides pbo setting（the curve optimizer)

### Describe the solution you'd like

make it possible to choose the function that would be applied and auto applied in the "Advanced"

### Describe alternatives you've considered

alternatives are not necessary

### Device and Model

TX5 pro ryzen

### Additional information.

the TX5 pro ryzen is basically TUF GAMING A16 changed its skin and upgraded to a hx cpu

**Comment by alex450** [comment]
![QQ截图20240222012529](https://github.com/seerge/g-helper/assets/17879601/be0cd47e-b3dd-442b-ad57-7550ee9bc2b9)

**Comment by seerge** [comment]
@alex450 hello, i'm not a big fan of over complicating UI even more here.

Where do you set undervolting instead of g-helper? And why don't you set temp limits there as well?

**Comment by alex450** [comment]
> @alex450 hello, i'm not a big fan of over complicating UI even more here.
> 
> Where do you set undervolting instead of g-helper? And why don't you set temp limits there as well?

the asus bios itself provided pbo settings without the temp limit :<

**Comment by alex450** [comment]
**
![ce8db54c5a1e962590d6ed5377d5890e](https://github.com/seerge/g-helper/assets/17879601/a5ff4ba8-7ca2-4a23-b4c1-920e4a856392)
** 
it doesnt make sense why they dont provide it，but it happens

**Comment by seerge** [comment]
@alex450 oke, but why don't you just set undervolting using g-helper then as well? I assume effect would be same?

**Comment by alex450** [comment]
> > @alex450 oke, but why don't you just set undervolting using g-helper then as well? I assume effect would be same?
> 
> after benchmarks,the all core frequency of undervolting in g-helper and bios didnt went the same i m not sure whether undervolting in g-helper would override the frequency setting

in benchmarks，all-core temp is 84，not max 90，so the temp limit should not influence on the results

**Comment by seerge** [comment]
@alex450 yes, it should skip UV command completely (but still run temp-limit) :)

**Comment by alex450** [comment]
> @alex450 yes, it should skip UV command completely (but still run temp-limit) :)

it seems didnt work
i got both 1.152v when aida64 cpu stress

![IMG_20240224_233111](https://github.com/seerge/g-helper/assets/17879601/f9bea41b-296c-4c3d-9f21-cd1634b13443)
![IMG_20240224_232907](https://github.com/seerge/g-helper/assets/17879601/a9c15ea8-7565-418f-b02c-b10100dde640)

allcore 4966 for uv -20 and 4816 for -1
maybe -1 is still undervolting

**Comment by seerge** [comment]
@alex450 try to set just 1 then

**Comment by alex450** [comment]
> @alex450 try to set just 1 then

value 1 is working 
thx a lot
