### ISSUE TITLE
System becomes unresponsive when pressing Media Keys 1 and 2 for volume

### ISSUE THREAD

**Issue by lifemare** [seerge/g-helper#2099]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

System slows down to a crawl every time i push the buttons. The mouse cursor renders at 2hz, the volume overlay GUI takes a good second to register every key press. System reverts to normal in a matter of seconds, up to a minute. I've tried switching between CPU and GPU modes, but nothing seems to be effective.

SPECS | DETAILS
-- | --
OS | Microsoft Windows 11 Home x64
Version | 10.0.22631 Build 22631
Model | ASUS ROG Zephyrus M16 GU603ZW
Processor | 12th Gen Intel i9-12900H 2500 Mhz
BaseBoard | ASUS GU603ZW 1.0
GPU | NVIDIA GeForce RTX 3070 Ti Laptop GPU
Driver Version | 31.0.15.5152
GPU2 | Intel Iris Xe Graphics
Driver Version | 31.0.101.5330

### How to reproduce the bug?

1. press media buttons

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14362861/log.txt)

### Device and Model

ASUS ROG Zephyrus M16 GU603ZW

### Additional information.

Fresh OS running at 130% Custom Scaling. Installed [StartAllBack](https://www.startallback.com/) and [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher).

Followed all the troubleshooting instructions, but ran into issues:

- sfc found and repaired corrupt files [CBS.log](https://github.com/seerge/g-helper/files/14363132/CBS.log). 
- Asus System Control Interface gave a warning message after installation that some components were not available on my system.
- `powercfg -restoredefaultschemes​` is not a valid command, these are the available arguments [powercfg.txt](https://github.com/seerge/g-helper/files/14363174/powercfg.txt)

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

0.151.0

### OS

Windows 11 Home x64

**Comment by lifemare** [comment]
Hi @seerge. Thank you so much for the quick reply. I tried killing the running service you mentioned to no avail :(

This behaviour just started happening after installing G-Helper and removing Armoury Crate... I'm in love with your app, seerge, i can never ever go back. Thank you a million for developing it. Guess i'll have to live with this little quirk. Beats dealing with the  ASUS cancerous bloatware catered to edgy gamers with eye-candy anime wallpapers plastering the basement, fully furnished with RGB xmas-lights, including duvets and socks.... Sorry. This software makes me angry XD

**Comment by lifemare** [comment]
But i'm aware from the troubleshooting experience my system is a bit wonky... So i accept your verdict. The culprit is hiding somewhere. If you have an inkling for the cause, please do advice. Feel free to mark this issue as you see fit.

**Comment by seerge** [comment]
@lifemare the easiest way to verify if it's related is to quit g-helper (by clicking in a button with same name)

Does volume control still work?

Does issue persist?

**Comment by lifemare** [comment]
Confirm issue persists after quitting g-helper.

**Comment by seerge** [comment]
@lifemare ok. 

I honestly don’t know what is the reason here. May be try to reinstall GPU drives? 

Anyway, closing this as I can’t help anyhow cause it’s not related to the app

**Comment by lifemare** [comment]
> the easiest way to verify if it's related is to quit g-helper

That was actually great advice, @seerge, thank you. Should have thought of trying that before anything else. After a bit of trial and error with task manager i managed to find the culprit: [tb-vol-scroll](https://github.com/dvingerh/tb-vol-scroll). Forgot i had it installed. 

Apologies for blemishing the webpage for your beautiful pristine app with this unrelated issue ;)
