### ISSUE TITLE
Battery Charge Limit not applying

### ISSUE THREAD

**Issue by sentfromthehub** [seerge/g-helper#21]
Hey!

For some reason, on my G401QC, ever since I installed G14 Helper v0.9.2, the battery charge limit of 80% I've set is not applying and thus, my laptop is charging fully to 100%. Also, for me, the laptop screen refresh rate doesn't automatically change from 144Hz + OD to 60Hz when I unplug my laptop even though the iGPU does. It may just be me though.

Thanks in advance

Edit: I've installed MyASUS which I used previously to set the battery charge limit. AC is also fully uninstalled.

**Comment by TomBonnot** [comment]
Make sure you give it the admin rights, even if it doesn’t need it to launch, it needs it for some features. 
Then unplug your laptop till 80% and replug it, to make sur it doesn’t charge more after this

**Comment by seerge** [comment]
Admin rights shouldn't be needed anymore. Did you had your laptop in hibernate state when plugged in ?

**Comment by sentfromthehub** [comment]
No, it was in sleep mode. I believe the battery charge limit is applying now, thank you. But, for some reason, the laptop screen refresh issue still stands as it looks like if I have the refresh rate set to 60Hz while on battery, it will switch to 144Hz + OD when plugged in but not vice versa (144Hz plugged in to 60Hz on battery). Any thoughts?
> Did you had your laptop in hibernate state when plugged in ?

**Comment by seerge** [comment]
Does the automatic GPU (eco/standard) switch work at the same time in both directions ?

**Comment by sentfromthehub** [comment]
Yes it does.
> Does the automatic GPU (eco/standard) switch work at the same time in both directions ?

**Comment by seerge** [comment]
And does manual 144Hz button work ? :)

**Comment by sentfromthehub** [comment]
Weird, it looks like it works when running w/ admin and on startup. Thanks for everything you do.

**Comment by sentfromthehub** [comment]
Oh hold up, I was able to replicate the issue again. So, when waking my G14 from sleep while the refresh rate is 144Hz and thereby disconnecting the power, it doesn't automatically go down to 60Hz refresh rate but the iGPU does.
