### ISSUE TITLE
Restoring default M3 setting

### ISSUE THREAD

**Issue by pratyakshm** [seerge/g-helper#210]
**Describe the bug**
I used G-Helper to bind something else to M3 key (Microphone mute). That worked as intended. But I am not sure how to restore the default setting to unbind custom actions and let M3 key toggle mic mute.

**Clear scenario to Reproduce**
1. Open G-Helper, go to Extras
2. Under Key bindings, change action for M3 key
3. Observe there's no way to restore the default system action for M3 key
4. 
![image](https://user-images.githubusercontent.com/54220235/230774760-857b664c-a84e-4c94-a098-9cfae98e38cc.png)

These settings did not work to restore microphone toggle mute functionality either.

**Expected behavior**
N.A.

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/11185518/log.txt)

- No ASUS software installed. Only ASUS optimization service is running.

**Comment by seerge** [comment]
It's asus optimization service responsible for muting mic from m3, not g-helper. You should make sure it's up and running ok.

When you select "---" in a dropdown as on your screenshot - g-helper will do nothing on m3 click (so that's correct).

There is nothing to fix here :)
