### ISSUE TITLE
Add "Enable GPU on sleep" Feature please

### ISSUE THREAD

**Issue by prashasth-nair** [seerge/g-helper#2110]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

When My Asus Tuf f15 Goes into sleep mode when it is in Optimize GPU mode and in battery power, The CPU and GPU fans stops working when I turn it on again. I have to doo a complete restart to start fans.

### Describe the solution you'd like

When Laptop goes to sleep in optimize mode , It should change to standard mode until I unlock my laptop again. I think this will fix the issue

### Device and Model

Asus Tuf F15 FX506HC

**Comment by prashasth-nair** [comment]
Is there any other way? Its very annoying to restart and laptop gets very hot after 10min because fans stops

**Comment by seerge** [comment]
@prashasth-nair are you using latest BIOS? may be asus has fixed that somehow ?

As for fans in sleep, if device is "properly" sleeping - it shouldn't be consuming much power and shouldn't need fans to run anyway.

**Comment by seerge** [comment]
So make sure that sleep is working in general :)

You can start with manually running all maintenance jobs (that may prevent windows from going into sleep)
![Screenshot 2024-02-24 134356](https://github.com/seerge/g-helper/assets/5920850/ad73a499-9828-41a2-968d-64652375164e)

And then run sleepstudy to check if there is something else waking up the laptop

**Comment by prashasth-nair** [comment]
Ya bios is latest and after waking up the device the fan doesn't start

**Comment by seerge** [comment]
@prashasth-nair did you try enabling / disabling GPU after wake up mb as a workaround? :)

**Comment by prashasth-nair** [comment]
@seerge Can You tell me how to enabling / disabling GPU. This is my first laptop with GPU. 😅
