### ISSUE TITLE
Provide building instructions

### ISSUE THREAD

**Issue by titoBouzout** [seerge/g-helper#2111]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I would like to build the exe from source

### Describe the solution you'd like

Probably a section in readme with some details about how to build the exe from source.

**Comment by seerge** [comment]
@titoBouzout hello, you just need Visual Studio, checkout sources from github and click build there :) It's pretty much straight forward if you are familiar with programming a bit.

If you are not - it's just better and easier to download exe :)

**Comment by titoBouzout** [comment]
Thanks a lot for adding the section to the FAQ, I will let you know whenever I give it a try.
