### ISSUE TITLE
CPU Throttled to 400Mhz when opening GHelper

### ISSUE THREAD

**Issue by midnightgospel** [seerge/g-helper#2113]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I recently replaced my battery. I have restored the Windows power configs, cleared CMOS, and ran the troubleshooter. Whenever I boot the computer on battery, everything is fine, until GHelper starts up. Then my CPU throttles to 400Mhz. If I change the power plan from balanced to power saver (or maximum performance) and back to balanced, it fixes it. Until the GHelper software restarts. I have removed all traces of the software and brought it back. I have also tried previous versions. Not sure if it's due to the battery, but it only occurs once the GHelper software starts up. I have never had issues until the new battery, and I'm not sure why this is all of a sudden an issue now. 
<img width="1280" alt="GHelper Initial Launch" src="https://github.com/seerge/g-helper/assets/25554881/5f9dafd7-0a29-4ec9-bf66-6c6dc65d1fd2">
<img width="507" alt="GHelper Settings CPU" src="https://github.com/seerge/g-helper/assets/25554881/fd2dd1f9-431f-44e3-a5a0-ca8dbecbad3e">
<img width="1280" alt="No GHelper" src="https://github.com/seerge/g-helper/assets/25554881/34965bc8-ade1-47f8-accc-3d8b5c7bb613">

### How to reproduce the bug?

Open GHelper.
CPU throttles to 400 Mhz.
Change Windows power mode from balanced any other mode.
CPU is back until GHelper is restarted. 

### Logs

2/24/2024 9:26:00 PM: ------------
2/24/2024 9:26:00 PM: App launched: ROG Zephyrus G15 GA503QR_GA503QR :0.154.0.0en-US
2/24/2024 9:26:01 PM: Matrix control device was not found on your machine.
2/24/2024 9:26:03 PM: NVIDIA GeForce RTX 3070 Laptop GPU
2/24/2024 9:26:04 PM: CPU: 7 - AMD Ryzen 9 5900HS with Radeon Graphics         - AMD64 Family 25 Model 80 Stepping 0
2/24/2024 9:26:04 PM: AutoSetting for Offline
2/24/2024 9:26:04 PM: Optimization service is running
2/24/2024 9:26:04 PM: Mode = 0 : OK
2/24/2024 9:26:04 PM: Power Mode 00000000-0000-0000-0000-000000000000:OK
2/24/2024 9:26:04 PM: Eco flag : 0
2/24/2024 9:26:04 PM: Mux flag : -65536
2/24/2024 9:26:04 PM: \\?\DISPLAY#CMN152A#5&2c3487dd&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2/24/2024 9:26:04 PM: \\?\DISPLAY#CMN152A#5&2c3487dd&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2/24/2024 9:26:04 PM: Init 19B6: 5D-B9
2/24/2024 9:26:04 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2/24/2024 9:26:04 PM: Init 19B6: 5D-05-20-31-00-1A
2/24/2024 9:26:04 PM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
2/24/2024 9:26:04 PM: AuraMode: AuraStatic
2/24/2024 9:26:04 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
2/24/2024 9:26:04 PM: USB 19B6: 5D-B5-00-00-00
2/24/2024 9:26:04 PM: USB 19B6: 5D-B4
2/24/2024 9:26:04 PM: Monitor Power On
2/24/2024 9:26:04 PM: Lid Open
2/24/2024 9:26:04 PM: Lid 19B6|64: 5A-BA-C5-C4-01
2/24/2024 9:26:05 PM: Auto 19B6|64: 5A-BA-C5-C4-01
2/24/2024 9:26:06 PM: Latest version 0.154.0.0
2/24/2024 9:26:16 PM: Design Capacity: 87395mWh, Full Charge Capacity: 89320mWh, Health: 1.0220264317180616740088105727%
2/24/2024 9:29:28 PM: ------------
2/24/2024 9:29:28 PM: App launched: ROG Zephyrus G15 GA503QR_GA503QR :0.153.0.0en-US
2/24/2024 9:29:28 PM: Matrix control device was not found on your machine.
2/24/2024 9:29:29 PM: NVIDIA GeForce RTX 3070 Laptop GPU
2/24/2024 9:29:30 PM: CPU: 7 - AMD Ryzen 9 5900HS with Radeon Graphics         - AMD64 Family 25 Model 80 Stepping 0
2/24/2024 9:29:30 PM: AutoSetting for Offline
2/24/2024 9:29:30 PM: Optimization service is running
2/24/2024 9:29:30 PM: Mode = 0 : OK
2/24/2024 9:29:30 PM: Eco flag : 0
2/24/2024 9:29:30 PM: Mux flag : -65536
2/24/2024 9:29:30 PM: \\?\DISPLAY#CMN152A#5&2c3487dd&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2/24/2024 9:29:30 PM: \\?\DISPLAY#CMN152A#5&2c3487dd&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2/24/2024 9:29:30 PM: ScreenOverdrive = 1 : OK
2/24/2024 9:29:30 PM: Init 19B6: 5D-B9
2/24/2024 9:29:30 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2/24/2024 9:29:30 PM: Init 19B6: 5D-05-20-31-00-1A
2/24/2024 9:29:30 PM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
2/24/2024 9:29:30 PM: AuraMode: AuraStatic
2/24/2024 9:29:30 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
2/24/2024 9:29:30 PM: USB 19B6: 5D-B5-00-00-00
2/24/2024 9:29:30 PM: USB 19B6: 5D-B4
2/24/2024 9:29:31 PM: Auto 19B6|64: 5A-BA-C5-C4-01
2/24/2024 9:29:33 PM: Monitor Power On
2/24/2024 9:29:33 PM: AutoSetting for Offline
2/24/2024 9:29:33 PM: Optimization service is running
2/24/2024 9:29:33 PM: Mode = 0 : OK
2/24/2024 9:29:33 PM: Eco flag : 0
2/24/2024 9:29:33 PM: Mux flag : -65536
2/24/2024 9:29:33 PM: \\?\DISPLAY#CMN152A#5&2c3487dd&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2/24/2024 9:29:34 PM: \\?\DISPLAY#CMN152A#5&2c3487dd&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2/24/2024 9:29:34 PM: ScreenOverdrive = 1 : OK
2/24/2024 9:29:34 PM: Init 19B6: 5D-B9
2/24/2024 9:29:34 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2/24/2024 9:29:34 PM: Init 19B6: 5D-05-20-31-00-1A
2/24/2024 9:29:34 PM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
2/24/2024 9:29:34 PM: AuraMode: AuraStatic
2/24/2024 9:29:34 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
2/24/2024 9:29:34 PM: USB 19B6: 5D-B5-00-00-00
2/24/2024 9:29:34 PM: USB 19B6: 5D-B4
2/24/2024 9:29:34 PM: Lid Open
2/24/2024 9:29:34 PM: Lid 19B6|64: 5A-BA-C5-C4-01
2/24/2024 9:29:35 PM: Auto 19B6|64: 5A-BA-C5-C4-01
2/24/2024 9:30:04 PM: Varibright: 1,3
2/24/2024 9:30:04 PM: Hibernate after 3600
2/24/2024 9:30:16 PM: ------------
2/24/2024 9:30:16 PM: App launched: ROG Zephyrus G15 GA503QR_GA503QR :0.153.0.0en-US.
2/24/2024 9:30:18 PM: Matrix control device was not found on your machine.
2/24/2024 9:30:24 PM: NVIDIA GeForce RTX 3070 Laptop GPU
2/24/2024 9:30:25 PM: CPU: 7 - AMD Ryzen 9 5900HS with Radeon Graphics         - AMD64 Family 25 Model 80 Stepping 0
2/24/2024 9:30:26 PM: AutoSetting for Offline
2/24/2024 9:30:26 PM: Optimization service is running
2/24/2024 9:30:26 PM: Mode = 0 : OK
2/24/2024 9:30:26 PM: Eco flag : 0
2/24/2024 9:30:26 PM: Mux flag : -65536
2/24/2024 9:30:26 PM: \\?\DISPLAY#CMN152A#5&2c3487dd&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2/24/2024 9:30:26 PM: \\?\DISPLAY#CMN152A#5&2c3487dd&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2/24/2024 9:30:26 PM: ScreenOverdrive = 1 : OK
2/24/2024 9:30:27 PM: Init 19B6: 5D-B9
2/24/2024 9:30:27 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2/24/2024 9:30:27 PM: Init 19B6: 5D-05-20-31-00-1A
2/24/2024 9:30:27 PM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
2/24/2024 9:30:27 PM: AuraMode: AuraStatic
2/24/2024 9:30:27 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
2/24/2024 9:30:27 PM: USB 19B6: 5D-B5-00-00-00
2/24/2024 9:30:27 PM: USB 19B6: 5D-B4
2/24/2024 9:30:28 PM: Auto 19B6|64: 5A-BA-C5-C4-01
2/24/2024 9:30:28 PM: Varibright: 1,3
2/24/2024 9:30:29 PM: Hibernate after 3600
2/24/2024 9:30:32 PM: Get-Service -Name "ArmouryCrateControlInterface" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:32 PM: Get-Service -Name "ArmouryCrateControlInterface" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:32 PM: Monitor Power On
2/24/2024 9:30:32 PM: AutoSetting for Offline
2/24/2024 9:30:32 PM: Optimization service is running
2/24/2024 9:30:32 PM: Mode = 0 : OK
2/24/2024 9:30:33 PM: Eco flag : 0
2/24/2024 9:30:33 PM: Mux flag : -65536
2/24/2024 9:30:33 PM: \\?\DISPLAY#CMN152A#5&2c3487dd&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2/24/2024 9:30:33 PM: \\?\DISPLAY#CMN152A#5&2c3487dd&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2/24/2024 9:30:33 PM: ScreenOverdrive = 1 : OK
2/24/2024 9:30:33 PM: Init 19B6: 5D-B9
2/24/2024 9:30:33 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2/24/2024 9:30:33 PM: Init 19B6: 5D-05-20-31-00-1A
2/24/2024 9:30:33 PM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
2/24/2024 9:30:33 PM: AuraMode: AuraStatic
2/24/2024 9:30:33 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
2/24/2024 9:30:33 PM: USB 19B6: 5D-B5-00-00-00
2/24/2024 9:30:33 PM: USB 19B6: 5D-B4
2/24/2024 9:30:33 PM: Lid Open
2/24/2024 9:30:33 PM: Lid 19B6|64: 5A-BA-C5-C4-01
2/24/2024 9:30:34 PM: Auto 19B6|64: 5A-BA-C5-C4-01
2/24/2024 9:30:38 PM: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
2/24/2024 9:30:38 PM: GET CLOCK LIMIT: NVAPI_GPU_NOT_POWERED
2/24/2024 9:30:42 PM: 
2/24/2024 9:30:42 PM: Get-Service -Name "ASUSOptimization" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:42 PM: Get-Service -Name "ASUSOptimization" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:44 PM: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
2/24/2024 9:30:45 PM: Power Mode 00000000-0000-0000-0000-000000000000:OK
2/24/2024 9:30:45 PM: 
2/24/2024 9:30:45 PM: Get-Service -Name "AsusAppService" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:45 PM: Get-Service -Name "AsusAppService" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:48 PM: 
2/24/2024 9:30:48 PM: Get-Service -Name "ASUSLinkNear" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:48 PM: Get-Service -Name "ASUSLinkNear" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:50 PM: Get-Service : Cannot find any service with service name 'ASUSLinkNear'.
At line:1 char:1
+ Get-Service -Name ASUSLinkNear | Stop-Service -Force -PassThru | Set- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ASUSLinkNear:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
 

2/24/2024 9:30:50 PM: Get-Service -Name "ASUSLinkRemote" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:50 PM: Get-Service -Name "ASUSLinkRemote" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:51 PM: Get-Service : Cannot find any service with service name 'ASUSLinkRemote'.
At line:1 char:1
+ Get-Service -Name ASUSLinkRemote | Stop-Service -Force -PassThru | Se ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ASUSLinkRemote:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
 

2/24/2024 9:30:51 PM: Get-Service -Name "ASUSSoftwareManager" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:51 PM: Get-Service -Name "ASUSSoftwareManager" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:52 PM: 
2/24/2024 9:30:52 PM: Get-Service -Name "ASUSSwitch" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:52 PM: Get-Service -Name "ASUSSwitch" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:53 PM: 
2/24/2024 9:30:53 PM: Get-Service -Name "ASUSSystemAnalysis" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:53 PM: Get-Service -Name "ASUSSystemAnalysis" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:54 PM: 
2/24/2024 9:30:54 PM: Get-Service -Name "ASUSSystemDiagnosis" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:54 PM: Get-Service -Name "ASUSSystemDiagnosis" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:55 PM: 
2/24/2024 9:30:55 PM: Get-Service -Name "AsusCertService" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:55 PM: Get-Service -Name "AsusCertService" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
2/24/2024 9:30:56 PM: Get-Service : Cannot find any service with service name 'AsusCertService'.
At line:1 char:1
+ Get-Service -Name AsusCertService | Stop-Service -Force -PassThru | S ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AsusCertService:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
 

2/24/2024 9:30:56 PM: USB 19B6|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2/24/2024 9:30:56 PM: Input: \\?\hid#vid_0b05&pid_19b6&mi_00&col01#8&3a080f36&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

### Device and Model

Asus Zephyrus G15 GA503QR

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.153, 0.154

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@midnightgospel hello.

If by just selecting "Balanced" power mode in the windows (or G-Helper) settings, you think that something is wrong with your CPU behavior - then it's probably a broken / corrupt power plan or windows setup :)

From the log I see that G-Helper literally sets nothing on launch, besides default power mode.

You can try following

1. Reset power plan to all defaults https://github.com/seerge/g-helper/wiki/Troubleshooting#resetting-windows-power-plan-to-defaults
2. Try to check / restore windows https://github.com/seerge/g-helper/wiki/Troubleshooting#repair-corrupted-system-fails

If it doesn't help, just set Best Performance power mode under ``Fans+Power`` and use that instead ? :)

**Comment by seerge** [comment]
@midnightgospel P.S. Since G-Helper has set Balanced power mode on start

```
2/24/2024 9:26:04 PM: Mode = 0 : OK
2/24/2024 9:26:04 PM: Power Mode 00000000-0000-0000-0000-000000000000:OK
```

means that it was not on Balanced on that moment.

Can you just check if changing power mode in windows settings have same result?
![image](https://github.com/seerge/g-helper/assets/5920850/0a7b89a5-c0c3-4f68-b8f3-d90dac19da4b)

**Comment by seerge** [comment]
@midnightgospel well, it looks like it's something wrong with power plan in windows. Did you try running ``powercfg -restoredefaultschemes​`` as I have proposed ?

Also please run this build and post a log from it. It would also record what power mode ID was before app sets it to balanced :) 

Cause apparently it was not in balanced (00000000-0000-0000-0000-000000000000) when you start an app for the first time. Since it checks for ID and changes mode only if it's different.

[GHelper.zip](https://github.com/seerge/g-helper/files/14396363/GHelper.zip)

**Comment by midnightgospel** [comment]
Yeah I ran through that, as well as completely reinstalled Windows. Something tells me the battery and Asus's power controller is the cause of the discrepancy. Guess I’m returning this battery.

**Comment by midnightgospel** [comment]
2/25/2024 7:58:49 AM: ------------
2/25/2024 7:58:50 AM: App launched: ROG Zephyrus G15 GA503QR_GA503QR :0.155.0.0en-US
2/25/2024 7:58:52 AM: Matrix control device was not found on your machine.
2/25/2024 7:59:04 AM: NVIDIA GeForce RTX 3070 Laptop GPU
2/25/2024 7:59:09 AM: CPU: 7 - AMD Ryzen 9 5900HS with Radeon Graphics         - AMD64 Family 25 Model 80 Stepping 0
2/25/2024 7:59:09 AM: AutoSetting for Offline
2/25/2024 7:59:09 AM: Mode = 0 : OK
2/25/2024 7:59:09 AM: USB 19B6|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2/25/2024 7:59:09 AM: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a -> 00000000-0000-0000-0000-000000000000:OK
2/25/2024 7:59:09 AM: Input: \\?\hid#vid_0b05&pid_19b6&mi_00&col01#8&3a080f36&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
2/25/2024 7:59:09 AM: Eco flag : 0
2/25/2024 7:59:09 AM: Mux flag : -65536
2/25/2024 7:59:09 AM: \\?\DISPLAY#CMN152A#5&2c3487dd&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2/25/2024 7:59:09 AM: \\?\DISPLAY#CMN152A#5&2c3487dd&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2/25/2024 7:59:09 AM: Init 19B6: 5D-B9
2/25/2024 7:59:09 AM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2/25/2024 7:59:09 AM: Init 19B6: 5D-05-20-31-00-1A
2/25/2024 7:59:09 AM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
2/25/2024 7:59:09 AM: AuraMode: AuraStatic
2/25/2024 7:59:09 AM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
2/25/2024 7:59:09 AM: USB 19B6: 5D-B5-00-00-00
2/25/2024 7:59:09 AM: USB 19B6: 5D-B4
2/25/2024 7:59:10 AM: Monitor Power On
2/25/2024 7:59:10 AM: Lid Open
2/25/2024 7:59:10 AM: Lid 19B6|64: 5A-BA-C5-C4-01
2/25/2024 7:59:10 AM: Auto 19B6|64: 5A-BA-C5-C4-01
2/25/2024 7:59:12 AM: Latest version 0.155.0.0
2/25/2024 7:59:25 AM: Mode = 2 : OK
2/25/2024 7:59:25 AM: Power Mode 00000000-0000-0000-0000-000000000000 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
2/25/2024 7:59:29 AM: Mode = 0 : OK
2/25/2024 7:59:29 AM: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a -> 00000000-0000-0000-0000-000000000000:OK
2/25/2024 7:59:31 AM: GetFan Mid :00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
2/25/2024 7:59:31 AM: GetFan CPU :37-3E-42-46-4A-4E-4E-4E-01-09-12-1B-24-3C-3C-3C
2/25/2024 7:59:31 AM: GetFan GPU :37-3E-42-46-4A-4E-4E-4E-01-0A-13-1C-25-41-41-41
2/25/2024 7:59:31 AM: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
2/25/2024 7:59:31 AM: GET CLOCK LIMIT: NVAPI_GPU_NOT_POWERED
2/25/2024 7:59:38 AM: Power Mode 00000000-0000-0000-0000-000000000000 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
2/25/2024 7:59:42 AM: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a -> 00000000-0000-0000-0000-000000000000:OK
2/25/2024 7:59:48 AM: Design Capacity: 87395mWh, Full Charge Capacity: 89320mWh, Health: 1.0220264317180616740088105727%

**Comment by seerge** [comment]
@midnightgospel ok,

So now on start it was in ``961cc777-2547-4f9d-8174-7d86181b8a7a`` ([Better Battery mode](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/customize-power-slider))

If you would set Fans+Power setting to Better Battery as well under "Balanced" mode, doe it resolve your problem ?

**Comment by seerge** [comment]
@midnightgospel ok, i wish you good luck with battery then

Closing as resolved as it's not related to the app
