### ISSUE TITLE
Colour "temp" changes when in fullscreen YouTube after touching the volume buttons on Flow X13

### ISSUE THREAD

**Issue by slikvik55** [seerge/g-helper#2116]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I admit this is a weird one but I'm sure it didn't do this when I was using Arnoury Crate. If I put a YouTube video into fullscreen, the white balance stays the same (somewhat yellow) but as soon as I tap the volume buttons a few times, the whites become much more blue! As soon as I cancel fullscreen, the colours go back to the yellow tint. 

I can figure out how the volume keys could trigger this, especially as you have to tap them a few times!

Unfortunately I can't pride screenshots because as soon as you try to do an image grab, it "cancels" whatever is going on an reverts to the yellow white warmth. 

### How to reproduce the bug?

Load YouTube.
Go fullscreen video.
Hit volume up or down a few times.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14396609/log.txt)

### Device and Model

Asus Rog Flow X13 2023

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.154

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@slikvik55 hello, this has nothing to do with G-Helper. 

You can quit app - and repeat all your steps. I'm sure you will get same results.

You can try to do a clean install of GPU drivers as explained in Troubleshooting
https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers

**Comment by seerge** [comment]
P.S. Make sure that you don' have Night Light on in windows
