### ISSUE TITLE
Refresh rate not changing correctly, only desktop mode changing and active signal mode not changing

### ISSUE THREAD

**Issue by AryanVerma1024** [seerge/g-helper#2117]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Ever since i "updated" to windows 11 my laptop's screen refresh rate doesnt change when i unplug the power.
Armoury crate wasn't able to do it after the update so I tried doing a clean windows install without armoury crate and it still didnt work.

The only thing changing is the "desktop mode" and not the "active signal mode", when i change the refresh rate manually it does change the active signal mode and the screen turns to black to indicate the change, whereas here, it just stays on.

Heres a video
https://github.com/seerge/g-helper/assets/80571430/b60d2cfd-1314-4857-815b-f26a503f4863

and yes the asus services are turned off
![Screenshot 2024-02-25 193603](https://github.com/seerge/g-helper/assets/80571430/a7be09f8-678e-4170-bf02-a50405d3ae3b)

### How to reproduce the bug?

I'm not sure if this is the case for everyone but "upgrade" to win 11 ig

### Logs

25-02-2024 19:28:39: WMI event 123
25-02-2024 19:28:39: Display configuration changed.
25-02-2024 19:28:41: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25-02-2024 19:28:41: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25-02-2024 19:28:41: Screen = 144Hz : OK
25-02-2024 19:28:41: ScreenOverdrive = 0 : OK
25-02-2024 19:28:43: Input device not found
25-02-2024 19:28:43: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25-02-2024 19:28:43: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25-02-2024 19:28:43: Screen = 60Hz : OK
25-02-2024 19:28:43: ScreenOverdrive = 0 : OK
25-02-2024 19:28:43: Display configuration changed.
25-02-2024 19:28:45: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25-02-2024 19:28:45: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25-02-2024 19:28:45: Screen = 144Hz : OK
25-02-2024 19:28:45: ScreenOverdrive = 0 : OK
25-02-2024 19:28:45: Display configuration changed.
25-02-2024 19:28:46: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25-02-2024 19:28:46: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25-02-2024 19:28:46: Input device not found
25-02-2024 19:28:46: Screen = 60Hz : OK
25-02-2024 19:28:46: ScreenOverdrive = 0 : OK
25-02-2024 19:28:47: Display configuration changed.
25-02-2024 19:28:48: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25-02-2024 19:28:48: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25-02-2024 19:28:48: Screen = 144Hz : OK

### Device and Model

Asus TUF F15 (FX516PC)

### Armoury Crate

Never installed

### Asus Services

0

### Version

0.154.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@AryanVerma1024 hello,

App uses WindowsAPI to set refresh rate, and it works according to the log (command is accepted)

```
25-02-2024 19:28:46: Screen = 60Hz : OK
....
25-02-2024 19:28:48: Screen = 144Hz : OK
````

You have AMD GPU and in latest AMD drivers they have separated Active Signal and Desktop signals, so WindowsAPI can affect only one of them. That's the reason why **AC also works in a same way** :)

I can't do anything about it, until AMD fixes that.

You can either roll-back to older AMD drivers (like 23.11.1) or set desktop signal manually. Or just use everything as it is now.

**Comment by AryanVerma1024** [comment]
But i have nvidia gpu (3050)

**Comment by seerge** [comment]
@AryanVerma1024 ok :) sorry, i thought your device also has AMD iGPU.

Usually it's visible in a log, but you have trimmed log by some reasons.

Anyway - my answer still stands. App sets refresh rate in the only possible way (and it's accepted by WindowsAPI).

The way actual change happens is out of apps control (and this probably a reason why AC's switch has same effect)

**Comment by AryanVerma1024** [comment]
I can send clean log after restart, I'm out atm

**Comment by AryanVerma1024** [comment]
heres the log after a restart
```25-02-2024 20:13:35: App launched: ASUS TUF Dash F15 FX516PC_FX516PC :0.154.0.0en-GB.
25-02-2024 20:13:38: Matrix control device was not found on your machine.
25-02-2024 20:13:38: NVIDIA GeForce RTX 3050 Laptop GPU
25-02-2024 20:13:39: CPU: -1 - 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz - Intel64 Family 6 Model 140 Stepping 1
25-02-2024 20:13:40: AutoSetting for Online
25-02-2024 20:13:40: Mode = 2 : OK
25-02-2024 20:13:40: Eco flag : 0
25-02-2024 20:13:40: Mux flag : -65536
25-02-2024 20:13:40: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25-02-2024 20:13:40: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25-02-2024 20:13:40: GET CLOCK LIMIT: 0
25-02-2024 20:13:40: Screen = 144Hz : -1
25-02-2024 20:13:40: ScreenOverdrive = 0 : OK
25-02-2024 20:13:40: GET GPU CLOCKS: 0, 0
25-02-2024 20:13:40: BatteryLimit = 60 : OK
25-02-2024 20:13:40: TUF_KB = 13566397 : OK
25-02-2024 20:13:40: AuraMode: AuraStatic
25-02-2024 20:13:40: TUF RGB = B4-00-FF-FF-FF-EB : 0
25-02-2024 20:13:40: TUF RGB = B4-00-FF-FF-FF-EB : OK
25-02-2024 20:13:40: Monitor Power On
25-02-2024 20:13:40: Lid Open
25-02-2024 20:13:40: TUF Brightness = 129 : OK
25-02-2024 20:13:41: TUF Brightness = 129 : OK
25-02-2024 20:13:45: Display configuration changed.
25-02-2024 20:13:45: Session:SessionUnlock
25-02-2024 20:13:45: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25-02-2024 20:13:45: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25-02-2024 20:13:46: Screen = 144Hz : OK
25-02-2024 20:13:46: ScreenOverdrive = 0 : OK
25-02-2024 20:13:46: Display configuration changed.
25-02-2024 20:13:50: Input device not found
25-02-2024 20:13:53: Latest version 0.154.0.0
25-02-2024 20:13:54: WMI event 123
25-02-2024 20:13:54: WMI event 87
25-02-2024 20:13:54: AutoSetting for Offline
25-02-2024 20:13:54: Mode = 2 : OK
25-02-2024 20:13:54: Eco flag : 0
25-02-2024 20:13:54: Mux flag : -65536
25-02-2024 20:13:54: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25-02-2024 20:13:54: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25-02-2024 20:13:54: GET CLOCK LIMIT: 0
25-02-2024 20:13:54: GET GPU CLOCKS: 0, 0
25-02-2024 20:13:54: Screen = 60Hz : OK
25-02-2024 20:13:54: ScreenOverdrive = 0 : OK
25-02-2024 20:13:54: BatteryLimit = 60 : OK
25-02-2024 20:13:55: TUF_KB = 13566397 : OK
25-02-2024 20:13:55: AuraMode: AuraStatic
25-02-2024 20:13:55: TUF RGB = B4-00-FF-FF-FF-EB : 0
25-02-2024 20:13:55: TUF RGB = B4-00-FF-FF-FF-EB : OK
25-02-2024 20:13:55: Display configuration changed.
25-02-2024 20:13:56: TUF Brightness = 129 : OK
25-02-2024 20:14:00: WMI event 207
25-02-2024 20:14:00: WMI event 88
25-02-2024 20:14:00: AutoSetting for Online
25-02-2024 20:14:00: WMI event 123
25-02-2024 20:14:00: Mode = 2 : OK
25-02-2024 20:14:00: Eco flag : 0
25-02-2024 20:14:00: Mux flag : -65536
25-02-2024 20:14:00: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25-02-2024 20:14:00: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25-02-2024 20:14:00: GET CLOCK LIMIT: 0
25-02-2024 20:14:00: GET GPU CLOCKS: 0, 0
25-02-2024 20:14:00: Screen = 144Hz : OK
25-02-2024 20:14:00: ScreenOverdrive = 0 : OK
25-02-2024 20:14:00: BatteryLimit = 60 : OK
25-02-2024 20:14:00: TUF_KB = 13566397 : OK
25-02-2024 20:14:00: AuraMode: AuraStatic
25-02-2024 20:14:00: TUF RGB = B4-00-FF-FF-FF-EB : 0
25-02-2024 20:14:00: TUF RGB = B4-00-FF-FF-FF-EB : OK
25-02-2024 20:14:00: Display configuration changed.
25-02-2024 20:14:01: TUF Brightness = 129 : OK
25-02-2024 20:14:03: WMI event 123
25-02-2024 20:14:03: WMI event 87
25-02-2024 20:14:03: AutoSetting for Offline
25-02-2024 20:14:03: Mode = 2 : OK
25-02-2024 20:14:04: Eco flag : 0
25-02-2024 20:14:04: Mux flag : -65536
25-02-2024 20:14:04: GET CLOCK LIMIT: 0
25-02-2024 20:14:04: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25-02-2024 20:14:04: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25-02-2024 20:14:04: GET GPU CLOCKS: 0, 0
25-02-2024 20:14:04: Screen = 60Hz : OK
25-02-2024 20:14:04: ScreenOverdrive = 0 : OK
25-02-2024 20:14:04: BatteryLimit = 60 : OK
25-02-2024 20:14:04: TUF_KB = 13566397 : OK
25-02-2024 20:14:04: AuraMode: AuraStatic
25-02-2024 20:14:04: TUF RGB = B4-00-FF-FF-FF-EB : 0
25-02-2024 20:14:04: TUF RGB = B4-00-FF-FF-FF-EB : OK
25-02-2024 20:14:04: Display configuration changed.
25-02-2024 20:14:04: Input device not found
25-02-2024 20:14:05: TUF Brightness = 129 : OK
25-02-2024 20:14:07: WMI event 207
25-02-2024 20:14:07: WMI event 88
25-02-2024 20:14:07: WMI event 123
25-02-2024 20:14:08: AutoSetting for Online
25-02-2024 20:14:08: Mode = 2 : OK
25-02-2024 20:14:08: Eco flag : 0
25-02-2024 20:14:08: Mux flag : -65536
25-02-2024 20:14:08: GET CLOCK LIMIT: 0
25-02-2024 20:14:08: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
25-02-2024 20:14:08: GET GPU CLOCKS: 0, 0
25-02-2024 20:14:08: \\?\DISPLAY#NCP004D#4&13177a2f&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
25-02-2024 20:14:08: Screen = 144Hz : OK
25-02-2024 20:14:08: ScreenOverdrive = 0 : OK
25-02-2024 20:14:08: BatteryLimit = 60 : OK
25-02-2024 20:14:08: TUF_KB = 13566397 : OK
25-02-2024 20:14:08: AuraMode: AuraStatic
25-02-2024 20:14:08: TUF RGB = B4-00-FF-FF-FF-EB : 0
25-02-2024 20:14:08: TUF RGB = B4-00-FF-FF-FF-EB : OK
25-02-2024 20:14:08: Display configuration changed.
25-02-2024 20:14:09: TUF Brightness = 129 : OK
25-02-2024 20:14:10: Input device not found
25-02-2024 20:14:14: Input device not found
25-02-2024 20:14:18: Input device not found```

**Comment by seerge** [comment]
@AryanVerma1024 i believe you, but as I have told - app sets refresh rate.

The rest is up to windows / drivers how to process that.

For me similar behavior started with recent AMD drivers (so i thought it's your case). But it could be that either Intel / Nvidia combo is also affected or it's something on windows level itself.

To verify, you can check other popular app for changing refresh rates
https://tools.taubenkorb.at/change-screen-resolution/

It also changes only Desktop Mode signal now.

**Comment by seerge** [comment]
You can try to follow Troubleshooting advice https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers

And completely uninstall / reinstall both Intel and NVidia GPU drivers, mb it will fix it for you
