### ISSUE TITLE
应用程序崩溃事件

### ISSUE THREAD

**Issue by ghostsowo** [seerge/g-helper#2118]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

应用程序安装时崩溃

### How to reproduce the bug?

应用程序安装时无反应，在windows日志中查看到错误日志

### Logs

日志名称:          Application
来源:            Application Error
日期:            2024/2/26 14:07:00
事件 ID:         1000
任务类别:          应用程序崩溃事件
级别:            错误
关键字:           
用户:            吴迪的电脑\70881
计算机:           吴迪的电脑
描述:
错误应用程序名称: GHelper.exe，版本: 0.154.0.0，时间戳: 0x655e0000
错误模块名称: KERNELBASE.dll，版本: 10.0.22621.1778，时间戳: 0x63f72683
异常代码: 0xe0434352
错误偏移量: 0x000000000006536c
错误进程 ID: 0x0x29C4
错误应用程序启动时间: 0x0x1DA687A02C07D83
错误应用程序路径: C:\Users\70881\Desktop\GHelper.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: 71d8e2f8-7eb5-456b-ac76-31ce786b064a
错误程序包全名: 
错误程序包相对应用程序 ID: 
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-26T06:07:00.4324514Z" />
    <EventRecordID>123010</EventRecordID>
    <Correlation />
    <Execution ProcessID="11088" ThreadID="11904" />
    <Channel>Application</Channel>
    <Computer>吴迪的电脑</Computer>
    <Security UserID="S-1-5-21-3841557522-3661988012-1532879922-1001" />
  </System>
  <EventData>
    <Data Name="AppName">GHelper.exe</Data>
    <Data Name="AppVersion">0.154.0.0</Data>
    <Data Name="AppTimeStamp">655e0000</Data>
    <Data Name="ModuleName">KERNELBASE.dll</Data>
    <Data Name="ModuleVersion">10.0.22621.1778</Data>
    <Data Name="ModuleTimeStamp">63f72683</Data>
    <Data Name="ExceptionCode">e0434352</Data>
    <Data Name="FaultingOffset">000000000006536c</Data>
    <Data Name="ProcessId">0x29c4</Data>
    <Data Name="ProcessCreationTime">0x1da687a02c07d83</Data>
    <Data Name="AppPath">C:\Users\70881\Desktop\GHelper.exe</Data>
    <Data Name="ModulePath">C:\Windows\System32\KERNELBASE.dll</Data>
    <Data Name="IntegratorReportId">71d8e2f8-7eb5-456b-ac76-31ce786b064a</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>

日志名称:          Application
来源:            .NET Runtime
日期:            2024/2/26 14:07:00
事件 ID:         1026
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           吴迪的电脑
描述:
Application: GHelper.exe
CoreCLR Version: 7.0.1624.6629
.NET Version: 7.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x80070422): 无法启动服务，原因可能是已被禁用或与其相关联的设备没有启动。

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementScope.InitializeGuts(Object o)
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at AppConfig.GetModel() in D:\a\g-helper\g-helper\app\AppConfig.cs:line 96
   at GHelper.Program.Main(String[] args) in D:\a\g-helper\g-helper\app\Program.cs:line 70

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-26T06:07:00.3959742Z" />
    <EventRecordID>123009</EventRecordID>
    <Correlation />
    <Execution ProcessID="10692" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>吴迪的电脑</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: GHelper.exe
CoreCLR Version: 7.0.1624.6629
.NET Version: 7.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x80070422): 无法启动服务，原因可能是已被禁用或与其相关联的设备没有启动。

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementScope.InitializeGuts(Object o)
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at AppConfig.GetModel() in D:\a\g-helper\g-helper\app\AppConfig.cs:line 96
   at GHelper.Program.Main(String[] args) in D:\a\g-helper\g-helper\app\Program.cs:line 70
</Data>
  </EventData>
</Event>

### Device and Model

ROG 枪神4plus

### Armoury Crate

Uninstalled

### Version

0.154.0

### OS

windows11

**Comment by seerge** [comment]
https://github.com/seerge/g-helper/wiki/Troubleshooting#rebuilding-wmi-repository
