### ISSUE TITLE
cpu performance is lower even in turbo

### ISSUE THREAD

**Issue by sharif221** [seerge/g-helper#2119]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

the balanced mode in armory crate clocked P cores at 4.2 GHz consistently and turbo does it same but sometimes hit 5.2 GHz as expected.

in G-helper it maxes at 2.9 GHz and stays at 2.2 for P cores and 2.1 and 1.8 for E cores.
but in default balanced and turbo mode its not the same.
i used Cinebench r23 to see what happens.

**results:**

-  on g helper turbo:
single core: 1671.280
multi core: 11054.210

- on armory crate:
singer core:  ~ 1780
multi core: ~ 13000

### How to reproduce the bug?

---

### Logs

---

### Device and Model

Rog flow z13 2022 (core i9-12900h) (3050ti) (FullHD 120hz)

### Additional information.

its somtimes jumps to 4.2 in normal use but not in benchmark.
i use hwinfo for checking clocks.
i tryed changing cpu power from 80w to max but no difference happened.

also i should mention that cpu boost was on *efficient aggressive*.

### Armoury Crate

Uninstalled

### Asus Services

0 service enabled

### Version

0.154.0

### OS

win 11 home build 22631

**Comment by sharif221** [comment]
the log file was too long i don't think this issue is something that can be determined with log files.
if there is something in log files that worth checking let me know

**Comment by seerge** [comment]
@sharif221 hello,

G-Helper is not managing your clocks anyhow. It's probably some differences in the settings of default windows "Balanced" power plan.

Since you have ignored issue template, and didn't attach log, it's impossible to say much. Most probably it's just different settings.

I can only advice to 
1. [Reset power plan to defaults ](https://github.com/seerge/g-helper/wiki/Troubleshooting#resetting-windows-power-plan-to-defaults)
2. Reset both Balanced and Turbo modes to factory defaults (with corresponding button under ``Fans+Power``)
3. Set ``Power mode`` dropdown under ``Fans+Power`` to Best Performance (even for Balanced mode)

Run your tests again, and check how much power your CPU consumes in HWinfo.

**Comment by sharif221** [comment]
now I see. I think it is because Armory Crate uses a custom power plan considering Asus edited hidden CPU options too, for example, an option called *processor performance boost mode* that you also add to the app is one of those.

so I need just to reinstall the armory crate, test each mode, back up all power plan settings, and create custom power plans based on them.

so how can I specify which power plan is used for each Mode?

**Comment by sharif221** [comment]
alright

I saw [this](https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-windows-power-plans-with-each-mode)

thanks for your response, this project is amazing 🔥

**Comment by seerge** [comment]
@sharif221 any updates here ? Did you try doing what I suggested?

**Comment by sharif221** [comment]
I'm sorry I was into some stuff.

I reset the balance mode using both Windows GUI and terminal but it didn't change the results.

I enabled *ultimate performance* profile using power shell command and ... i was right; unfortunately, windows default balance mode is not letting the CPU run a full load.
after that change the CPU clocks and benchmarks back to normal results.

the next step is seeing what setting from hidden power plan settings is different from balanced and ultimate performance profile.
I saw this helpful program called *PowerSettingsExplorer* on the web that lets u see settings in nice GUI windows with some description for each power option and also lets you export profiles.
[PowerSettingsExplorer](https://forums.guru3d.com/threads/windows-power-plan-settings-explorer-utility.416058/)

I couldn't find the exact one or more settings that let the CPU go full load yet.
I'll send updates here.

**Comment by seerge** [comment]
@sharif221 that's strange :) may it's specific to your CPU only. Cause there are a lot of users with Intel devices and I have seen a very good (and high) benchmark results with default plan.

You can export all power plan settings using ``powercfg /QH`` command and just compare 2 plans to each other, and figure out what setting is the reason.

Just in case you can set any custom power plans in the app as well https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-windows-power-plans-with-each-mode (including your High Performance)

**Comment by seerge** [comment]
@sharif221 any updates? Does assigning Ultimate Performance plan in config solve your problems ?

```
"scheme_1": "e9a42b02-d5df-448d-aa00-03f14749eb61",
```

**Comment by sharif221** [comment]
Yes you're right my cpu is a little bit different from general cpus, because of this Asus creates separate power profile for each laptops.

AMD CPUs are much easier to work with, because thay are one core type not E cores and P cores like Intel.

Assigning ultimate performance in G-helper config files fixed my problem as expected.

I'm working on creating some documentation on how to work with windows power profiles and what each option do.

there so little information in web in this topic. Its there but separated in different forums and need to look for.

I'll keep you updated, this might help g-helper
But this issue is totally fixed by adding custom power profile in g-helper config file.

Todo:
- [ ]  finding differences of Asus power profiles and default balanced mode for intel 12gen cpus,
- [ ] finding most impactful settings
- [ ] doing a little bit reverse engineering on asus armory crate to find the place that power profile datas stored in there

**Comment by seerge** [comment]
@sharif221 oke, great.

If you will find some very impactful settings, let me know :) I can add it to FAQ or something.

I'm closing this as completed then

**Comment by Xeph20** [comment]
Sorry to necro this but i thought it was stupid to open a new issue because i think i have the same problem.
I always noticed my turbo mode has less performence than balanced. Now i tried some diffrent things while watching CPU Z benchmark. 

Turbo ALWAYS has less performence than balanced even with the exact same settings and powerplan. what i did notice thought is that it only happens with multi thread benchmark. So i have a feeling Turbo isn't able to use all cores for some reason while balanced can. No idea how to solve or check this (as i said i tried the exact same settings and power plan so i don't feel like resetting power plan)
