### ISSUE TITLE
Request for Discrete GPU not to turn on USB C Charging

### ISSUE THREAD

**Issue by Derzz** [seerge/g-helper#212]
Hi,

Before I start with my issue, I want to say thank you for creating this application- it's very helpful and a lot less bulky than Armory Crate, so thank you for your hard work so far on this.

There's one thing that I wonder if it's possible- if I'm charging my Zephyrus G14 via USB-C, is it possible when on "optimized" GPU mode to not turn on the discrete GPU and remain on the integrated GPU? In Armory Crate, it would not turn on the discrete GPU unless there is a big enough power supply such as the provided barrel charger instead of a USB-C power source charging the laptop. I wonder if it's possible to recreate that in G Helper.

Thanks!

**Comment by seerge** [comment]
It's possible, but literally the opposite (to turn on dGPU on USB-C charger was asked by someone else) :)  Why don't you just use eco mode instead ?

**Comment by Derzz** [comment]
Oh, I mean it's just for convenience, when I'm charging at school it's via USB-C so I don't have a need to turn on the discrete GPU. Since my USB-C charger is at 60 Watts, I don't use anything graphically intense since it can potentially drain my battery. 

However, I did do your eco mode strategy before, but when I'm back at home and plug in the barrel charger, sometimes I forget that eco mode is still on so when I boot up a graphically intense game, I notice that the FPS is low so I have to quit the game, turn on the discrete GPU, and open the game again, which can get frustrating at times as it takes a while for these games to fully boot.

**Comment by seerge** [comment]
Hello, as I mentioned - changing this will break app behaviour that other people expect :)
