### ISSUE TITLE
[Feature] Save config and logs on same folder as exe

### ISSUE THREAD

**Issue by titoBouzout** [seerge/g-helper#2123]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

It would be nice if the config file and the log file could be saved to the same folder as the exe file. The reason for this is that makes it easy to use the app as a portable executable. (the portable folder with the exe has the config... so no need to do backups etc)

**Comment by seerge** [comment]
@titoBouzout hello, it's already possible. Just put config into same folder as exe and app will use that. Log is not supposed to be used by  the user anyway, so it will remain where it is.

**Comment by titoBouzout** [comment]
The log is useful and make it easy to find would be best I think. Btw, you are too quick to close issues, it makes it look like you dont want feedback.

**Comment by seerge** [comment]
@titoBouzout log can be opened with dedicated button from ``Extra`` section, and it's also explained how to get it in Issue template :)

**Comment by Kikimahe** [comment]
@titoBouzout 

You can quick open log file with this little ico. 
I discovered it recently. Shame on me :) 

![Capture d'écran 2024-02-27 190021](https://github.com/seerge/g-helper/assets/142881210/5c522712-e75d-4ff9-92fd-9044206d9de2)
