### ISSUE TITLE
[Feature] allow to disable update check

### ISSUE THREAD

**Issue by titoBouzout** [seerge/g-helper#2124]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

It would be nice if update-check could be disabled. Not a problem per se, but it creeps me out and sometimes I use mobile data and I would prefer if applications just do not fire network commands unless instructured. Thanks

**Comment by seerge** [comment]
@titoBouzout hello. What's the practical purpose of that ? Update check will  only trigger update popup, and if you say NO there - it won't bother you again.
