### ISSUE TITLE
[NOT SURE IF IT'S G-HELPER ISSUE] Randomly bluetooth,Keyboard and USB Disconnect.

### ISSUE THREAD

**Issue by Twel12** [seerge/g-helper#2125]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

So randomly on usage of my laptop my Internal Keyboard, USB Devices and Bluetooth devices disconnect. I'm mostly sure it's not a g-helper issue but if you could find anything on logs that would mean a lot that it's my hardware or some software intruding. My Trackpad keeps working and then rest of the devices comeback about in 15-20 second and upon that my g-helper key binds also stop working and the Hibernate timer also resets to 180 then I have to close and re-open g-helper to make it work normally. It happens like 2 times a day. Happens on Battery/charging both scenarios.

### How to reproduce the bug?

Just use the laptop normally, and randomly it happens. No certain methodology.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14417460/log.txt)

### Device and Model

ASUS ZEPHYRUS G15 GA503QM

### Armoury Crate

Installed

### Asus Services

0 Running

### Version

0.151

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Twel12 hello, G-Helper  has nothing to do with your bluetooth or USB. Log contains only own G-Helper actions. 

I see that you use external USB hub, that could be malfunctioning. 

I can't help you anyhow, you can try to do some steps from https://github.com/seerge/g-helper/wiki/Troubleshooting if you want

Good luck
