### ISSUE TITLE
Audio problem?

### ISSUE THREAD

**Issue by SynStark** [seerge/g-helper#2126]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hello, I don't know if it's connected in any way, but this morning my G-Helper update to 154 and since then the sound of my laptop is very muffled and when I connect headphones there's no sound at all. The Sound Bar in the Settings menu is moving so it's detecting them, but no sound comes from the headphones.

Any ideas please?

### How to reproduce the bug?

N/A

### Logs

N/A

### Device and Model

Scar 18

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

154

### OS

11

**Comment by seerge** [comment]
@SynStark hello, G-Helper **doesn't affect your sound anyhow** :) And it doesn't touch any settings in windows even closely related to this.

You can quit G-Helper and I'm sure your situation won't change.

You can try to reboot system or try some (relevant) steps from  general [Troubleshooting](https://github.com/seerge/g-helper/wiki/Troubleshooting) section.

You can also use system restore, and roll back to last point where sound worked ok.

Good luck
