### ISSUE TITLE
Laptop will not run dGPU

### ISSUE THREAD

**Issue by riley112** [seerge/g-helper#2127]
Laptop is running iGPU whether it is plugged in or not. dGPU will not even turn on when I change the settings to standard. Telling windows to run programs in high perfomance makes no difference. Downloaded new drivers today.

**Comment by seerge** [comment]
@riley112 please follow issue template, and submit all the information as was clearly requested https://github.com/seerge/g-helper/issues/new/choose

I'm not going to guess anything here.

**Comment by seerge** [comment]
P.S. Looks like you have fixed it [(if it's your thread)](https://www.reddit.com/r/ZephyrusG14/comments/1b1rgl6/comment/ksgk0v9/)

**Comment by riley112** [comment]
Lol, nice spot! That was indeed my thread. I thought I had everything deleted already, I'm not really sure why it became a problem, oh well its fixed now. -- Sorry for not following your posting requirements. Thanks for making this program :) Cheers!
