### ISSUE TITLE
Need support for Asus Rog Strix Impact II wired gaming mouse (DPI, lighting, forward/backward, mouse wheel click button mapping support)

### ISSUE THREAD

**Issue by arjun7809** [seerge/g-helper#2130]
### Mouse / peripheral model and version

Asus ROG Strix Impact II wired gaming mouse

### Armoury Crate Screenshots

I use ghelper lol!

### USB Details

![info2](https://github.com/seerge/g-helper/assets/97421381/83dbe80a-2b3e-4c0c-af19-1fd2700ba817)
![mousedetail1](https://github.com/seerge/g-helper/assets/97421381/4f6af7ae-098d-4ef5-a467-38f3bfb5d13c)
![mousedetail2](https://github.com/seerge/g-helper/assets/97421381/1b444ecc-6663-4614-8def-ec261879a119)
![mousedetail3](https://github.com/seerge/g-helper/assets/97421381/f899c1a2-ca2e-4913-8351-dfe6859d5ddd)
![mousedetail4](https://github.com/seerge/g-helper/assets/97421381/101b8845-fbda-4369-8dea-ece7dae6038f)
![mousedetail5](https://github.com/seerge/g-helper/assets/97421381/82f24093-5c54-4fe0-855a-abb53a3df197)
![mousedetail6](https://github.com/seerge/g-helper/assets/97421381/511c1409-c50a-4a1a-b304-c127f55c899a)
![otherinfo](https://github.com/seerge/g-helper/assets/97421381/8ee83cb1-6f4b-44dd-9cc3-b88faa9b536a)

### Additional information.

![rogstrixinfo](https://github.com/seerge/g-helper/assets/97421381/5186bde1-e934-41c5-9141-85f67db0234b)

**Comment by seerge** [comment]
@arjun7809 hello,

> Armoury Crate Screenshots
> I use ghelper lol!

Screenshots from Armoury are needed to see what options and settings mouse has.

**Comment by arjun7809** [comment]
> @arjun7809 hello,
> 
> > Armoury Crate Screenshots
> > I use ghelper lol!
> 
> Screenshots from Armoury are needed to see what options and settings mouse has.
> 

![images (4).jpeg](https://github.![images (5).jpeg](https://github.com/seerge/g-helper/assets/97421381/77dd9b1d-7180-420a-89b1-6bd8c4619de2)

1/de525d39-af42-42f1-b87c-75609fedd1bd)

![Uploading images (5).jpeg …]()

Hope this helps, the language is different in the second image but as far as I remember it's similar in my armoury crate.

**Comment by arjun7809** [comment]
> @arjun7809 hello,
> 
> > Armoury Crate Screenshots
> > I use ghelper lol!
> 
> Screenshots from Armoury are needed to see what options and settings mouse has.
> 

Is this enough,mine comes with a different language(English) but somehow I managed to get the image.

![images (4).jpeg](https://github.com/seerge/g-helper/assets/97421381/5169966b-4a96-4561-a0d4-d39d694804af)

![images (5).jpeg](https://github.com/seerge/g-helper/assets/97421381/fc45e88d-109f-497b-9309-0da865d2401a)

**Comment by IceStormNG** [comment]
If it is the same as the regular Strix Impact II, then this should do the trick.

[GHelper.zip](https://github.com/seerge/g-helper/files/14431704/GHelper.zip)

Button mapping is not supported for any mouse, yet because it is a nightmare to figure out for each mouse and needs way more packet logging from each user.

**Comment by arjun7809** [comment]
> If it is the same as the regular Strix Impact II, then this should do the trick.
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14431704/GHelper.zip)
> 
> Button mapping is not supported for any mouse, yet because it is a nightmare to figure out for each mouse and needs way more packet logging from each user.

I'll try.

**Comment by seerge** [comment]
@arjun7809 Ryzen 7  doesn't support undervolting at all. You can't do that.

Is everything working in the build for the mouse as expected ?

**Comment by arjun7809** [comment]
> @arjun7809 Ryzen 7  doesn't support undervolting at all. You can't do that.
> 
> Is everything working in the build for the mouse as expected ?

Yes bud, thanks for developing such an amazing software. You are a lifesaver for Asus community.
