### ISSUE TITLE
"The process can't accès the file C:\ Users \.... config.json.bak" 

### ISSUE THREAD

**Issue by Kikimahe** [seerge/g-helper#2133]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hello Seerge,

Since the functionality of saving the config.json.bak file appeared (v0.146 perhaps), I regularly see errors in the log : 
```
28/02/2024 15:23:08: System.IO.IOException: The process cannot access the file 'C:\Users\Pistache\AppData\Roaming\GHelper\config.json.bak' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at AppConfig.Timer_Elapsed(Object sender, ElapsedEventArgs e) in D:\a\g-helper\g-helper\app\AppConfig.cs:line 87
```

In these errors I see a path that is directed to my D:\ drive and Ghelper is installed on the C:\ drive )
`  D:\a\g-helper\g-helper\app\AppConfig.cs:line 87`

### How to reproduce the bug?

I don't know how to reproduce it. 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14439015/log.txt)

### Device and Model

Tuf F17 FX707ZM 

### Armoury Crate

Never installed

### Asus Services

Aucun

### Version

0.155 

### OS

W11 23H2.

**Comment by seerge** [comment]
@Kikimahe hello :) .bak config is actually something I have added in order to prevent from loosing config when your device crashes (for example as a result of idiotic undervolting)

As if config was already open and app was writing something during windows crash - contents would be lost.
What app does, it writes to config.bak first, and then in 0.5 seconds copies it to main config.

I personally don't get this errors, but I could imagine it's something to do with this "workaround".

I have added a small tweak (that would just retry to write config second time if it's busy)

Try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14439181/GHelper.zip)

**Comment by Kikimahe** [comment]
Thanks Seerge.

I will test and monitor the log.

Give me a few days of testing for feedback because these errors do not appear regularly. :)

**Comment by seerge** [comment]
@Kikimahe the D:\ path btw is cause actual .exe is assembled on github directly, and that's some internal deploy structure there

**Comment by IceStormNG** [comment]
It could be that some background process, like an anti-virus scanner, locks the file after creation.

**Comment by seerge** [comment]
@Kikimahe did you encounter this with new build ?

**Comment by Kikimahe** [comment]
Hello Seerge.

I needed a few days to test.
But so far no errors have appeared. :)

I think it's safe to say you fixed it. :)
We can close the topic and I will continue to monitor the log.
