### ISSUE TITLE
R9 7845HX Undervolting not working despite being in the "Supported" list

### ISSUE THREAD

**Issue by NinjaBlazin** [seerge/g-helper#2134]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When trying to undervolt my R9 7845HX it doesn't do anything despite the logs giving me the 'ok'.

> 28/02/2024 20:50:50: UV: -30 OK
> 28/02/2024 20:50:50: iGPU UV: -20 
> 28/02/2024 20:50:50: CPU Temp: 97 OK
> 28/02/2024 20:50:50: APU Temp: 97

The Voltage used by my CPU stays the same despite the changes.

The FAQ says my CPU is supported, do I have to enable some kind of setting in BIOS or something to get it to work? Or is my CPU not supported after all?

### How to reproduce the bug?

1. Go to Fans + Power 2. Go to Advanced 3. Set CPU to -30, iGPU to -20

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14439380/log.txt)

### Device and Model

Asus Rog Strix G17 G713PV

### Additional information.

OS Name	Microsoft Windows 11 Home
Version	10.0.22631 Build 22631
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	ASUSTeK COMPUTER INC.
System Model	ROG Strix G713PV_G713PV
System Type	x64-based PC
System SKU	
Processor	AMD Ryzen 9 7845HX with Radeon Graphics, 3001 Mhz, 12 Core(s), 24 Logical Processor(s)
BIOS Version/Date	American Megatrends International, LLC. G713PV.324, 11/07/2023
SMBIOS Version	3.5
Embedded Controller Version	0.65
BIOS Mode	UEFI
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	G713PV
BaseBoard Version	1.0
Platform Role	Mobile

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.154.0

### OS

Windows 11 Home 10.0.22631 Build 22631

**Comment by seerge** [comment]
@NinjaBlazin hello,

Actually that "OK" is answer from  Ryzen System Management Unit (from [UXTU ](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility)that app uses). It means that value was accepted :)

Your voltage won't drop unless you also limit CPU power :) what undervolting does (same as undervolting for GPU) it allows device to run with a tiny-bit higher clocks with **same** voltage

How do you test results ?

I would advice to run Cinebench23 (or something similar) with NO undervolting, and with -30 and compare.

**Comment by NinjaBlazin** [comment]
> @NinjaBlazin hello,
> 
> Actually that "OK" is answer from Ryzen System Management Unit (from [UXTU ](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility)that app uses). It means that value was accepted :)
> 
> Your voltage won't drop unless you also limit CPU power :) what undervolting does (same as undervolting for GPU) it allows device to run with a tiny-bit higher clocks with **same** voltage
> 
> How do you test results ?
> 
> I would advice to run Cinebench23 (or something similar) with NO undervolting, and with -30 and compare.

I use Cinebench23 already with HWInfo running in the background. I set a CPU Power Limit to 80W CPU Sustained (SPL), CPU Slow (sPPT) and CPU Fast (fPPT). Do I need to further reduce my Power Limit? The reason I want to undervolt is to lower my CPU temps without reducing overall performance that much. I have seen no difference in Cinebench23 score (only marginal).

**Comment by seerge** [comment]
@NinjaBlazin what do you understand under marginal?

I get like 14000 points on my G14 2022 6900HS w/o undervolting, and around 14500 with undervolting :) so around 3%. That's what you get

If you want to get lower temps in games, you can literally set limit to something like 40W and, most probably performance hit won't be significant.

Anyway, I can't "fix" anything here, as there is no bug :) values are applied and accepted

You can also try to undervolt with UXTU directly https://github.com/JamesCJ60/Universal-x86-Tuning-Utility (most probably with same outcome?) :)

**Comment by seerge** [comment]
Correction, I get 14170 without undervolting, and 14530 with maximum possible undervolting in my case. So 2.5% gain.

**Comment by seerge** [comment]
@NinjaBlazin any updates?

**Comment by seerge** [comment]
Closed as abandoned due to lack of response from issue starter

**Comment by seerge** [comment]
@MetalRex101 hello check this topic https://github.com/seerge/g-helper/discussions/736 

Ryzen 9 7845hx does support undervolting 

But following pattern that Ryzen 7 does not support for all other models, it's most probably the case for your device too

**Comment by MetalRex101** [comment]
@seerge sad to hear.. Anyway, thank you for the fast reply!

**Comment by seerge** [comment]
@MetalRex101 only for Asus devices
