### ISSUE TITLE
Scar 18 (2023) Generic Power Plans

### ISSUE THREAD

**Issue by Frub3L** [seerge/g-helper#2135]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hello,
I am aware that it isn't related to G-Helper.
Power Plans from when Armoury Crate is uninstalled dissapear (Windows, SIlent, Performance, Turbo). G-Helper only activates and uses in general 'Balanced' mode, it also duplicates it.
![image](https://github.com/seerge/g-helper/assets/139390959/721692da-f13e-4e42-86f4-9026759e47b9)

### Describe the solution you'd like

Would it be possible to incorporate the generic Power Plans from Armoury Crate in to G-Helper? No way of activating them works, so I would be forced to go back to Armoury Crate.

### Describe alternatives you've considered

Tried every possible way to add power plans but it did not work.

### Device and Model

Asus SCAR 18 (2023)

**Comment by seerge** [comment]
@Frub3L hello.

G-Helper doesn't dublicate Balanced plan :) it uses **default plan from windows**. The second one on your screenshot is apparently a copy that either you (or some app) did and called same.
![Screenshot 2024-02-28 211450](https://github.com/seerge/g-helper/assets/5920850/da74f8c8-f7b4-4532-af80-a7c1695a74fc)

You can already assign and use any other custom power plans, if you want. It's covered in readme https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-windows-power-plans-with-each-mode

Good luck

**Comment by seerge** [comment]
P.S. You need to export plans form AC if you want to use them.

But there is really no need for that as they don't give anything.
