### ISSUE TITLE
G14 2024 - Keyboard colors aren't changing & slash lighting isnt working

### ISSUE THREAD

**Issue by PixelEnthusiast15** [seerge/g-helper#2138]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I absolutely love G-Helper. It was a deciding factor in me buying an Asus laptop. They should be paying you.

That said, I have no ability to change my keyboard color. It is always on static and blue and my slash lighting isn't working.

I have noticed that when I am shutting down the color or starting up, the color will switch to whatever I have set, but then once windows has booted the color will be only blue. Everything else appears to be working properly.

I am on build 0.154.0

### How to reproduce the bug?

It simply doesn't change color no matter what I set it to. Slash lighting also doesnt work

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14442868/log.txt)

### Device and Model

G14 GA403UV (G14 2024)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.154.0

### OS

Windowss 11

**Comment by PixelEnthusiast15** [comment]
OK - So I did some digging, my keyboard color issue was being caused by "Windows Dynamic Lighting"

I simply turned that off with Settings -> Personalization -> Dynamic Lightning and toggling off. 

Slash lighting issue remains

**Comment by PixelEnthusiast15** [comment]
I updated to 0.155.0 and the no slash lighting issue persists.

**Comment by PixelEnthusiast15** [comment]
I got slash lighting working on 0.155.0

Very cool! 

I had to toggle disable on battery for it to start working at all. Right after I did that it all the sudden started working. Until I checked that box none of the settings were returning anything. 

Now the toggles works as intended.

Excellent work

**Comment by seerge** [comment]
@PixelEnthusiast15 make sure to turn off Dynamic Lightning in windows https://github.com/seerge/g-helper/wiki/FAQ#backlight-randomly-changes-color-or-brightness
