### ISSUE TITLE
Fan settings not working on TUF FX506LU

### ISSUE THREAD

**Issue by redhyper9** [seerge/g-helper#214]
Hello,

When I want to set a custom fan curve it appears that it set but it doesn't do anything at all. The fan speed stays around 2000 RPM no matter what fan curves I set.

Is there any way to fix this?

Thanks.

**Comment by seerge** [comment]
Hello, based on 0 debug info and reproduction info you provided, i have no idea :)

**Comment by redhyper9** [comment]
> Hello, based on 0 debug info and reproduction info you provided, i have no idea :)

Reproduction is just set any fan curve, it doesn't change anything xD

[log.txt](https://github.com/seerge/g-helper/files/11191614/log.txt)

I've attached log.txt

**Comment by seerge** [comment]
From log i see that 

```
4/10/2023 3:34:28 PM: FanCPU = 3B-41-40-46-46-4B-4B-62-00-0C-0B-16-15-22-21-29 : 0
4/10/2023 3:34:28 PM: FanGPU = 3C-41-42-46-47-4B-4C-62-08-11-11-1D-1D-26-26-2D : 0
4/10/2023 3:34:28 PM: Driver rejected fan curve, resetting mode to 2
```

It seems that asus drivers doesn't accept it at all. Does your device support custom fan curves in armoury ? if so - can you post a screenshot of **working** a curve in armoury ?
