### ISSUE TITLE
Fans not working

### ISSUE THREAD

**Issue by yesnt10** [seerge/g-helper#2140]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hello. Thanks so much for this lightweight version. I have a problem. Especially when I play games (valorant etc.) my processor temperature rises a lot. The fans are set to 100% in turbo mode, but they do not work at 100%.

![image](https://github.com/seerge/g-helper/assets/114935167/76fed46d-8ee8-4f51-b3d2-35205f3c15d8)

### How to reproduce the bug?

Hello. Thanks so much for this lightweight version. I have a problem. Especially when I play games (valorant etc.) my processor temperature rises a lot. The fans are set to 100% in turbo mode, but they do not work at 100%.

![image](https://github.com/seerge/g-helper/assets/114935167/76fed46d-8ee8-4f51-b3d2-35205f3c15d8)

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14446828/log.txt)

### Device and Model

Asus Tuf F15 FX506HC

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

0.154.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@yesnt10 hello,

Your device doesn't support custom fan curves.

And fans are always controlled by BIOS.

That's how Asus has programmed it. I can't do absolutely anything about it.

**Comment by seerge** [comment]
P.S. You should better set some power limits to CPU if they are available to prevent overheating

**Comment by yesnt10** [comment]
> P.S. You should better set some power limits to CPU if they are available to prevent overheating
> 
> Or disable CPU boost at least

![image](https://github.com/seerge/g-helper/assets/114935167/27d8b909-47d0-41b2-a41f-79d2566d159b)
What do you think? is it okay ?

**Comment by seerge** [comment]
@yesnt , since your device doesn't support power limits - think disabling boost is the only viable option :)
