### ISSUE TITLE
dGPU not detected by NVIDIA Control Panel when changing from Eco (when on battery) to Optimized (when plugged in) - 2024 G14

### ISSUE THREAD

**Issue by nathancdy** [seerge/g-helper#2143]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Starting up my 2024 G14 on battery with Eco as the last GPU Mode and plugging it in then changing the GPU mode to Optimized, the system itself detects my 4060 as seen in Device Manager (and in AC), but when clicking on the NVIDIA Control Panel notifies me that I am not using a display connected to a NVIDIA GPU.

Also, usually when using Optimized, the Tray application for my dGPU would show up, and hovering over it would show whether it is inactive or not and clicking it shows what applications are using my dGPU.

Some problems I would get with this issue is that some games would use my iGPU instead.

### How to reproduce the bug?

1. Turn on G14 when on battery and Eco mode on last startup.
2. Plug in G14 to power and change GPU Mode to Optimized
3.  dGPU is shown in Device Manager and AC but NVIDIA Control Panel (and some games) don't detect the dGPU.

Edit: Problem still occurs when starting up with Optimized, mode changes to Eco when clicking on Optimized again. My guess is that AC and GHelper are interrupting each other.

Edit 2: Upon testing on Optimized on startup after uninstalling AC, Problem still occurs where when plugging in, mode is on Optimized at 'iGPU only'. Clicking on Optimized changes to Eco but clicking Optimized again fixes my initial bug, where the GPU status and NVIDIA Settings tray applications show up. Reference photo in replies.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14456200/log.txt)

### Device and Model

ASUS Zephyrus G14 GA403UV

### Additional information.

![image](https://github.com/seerge/g-helper/assets/103626631/32dd7830-2237-4226-a9d5-3edb5d3f0f61)

![image](https://github.com/seerge/g-helper/assets/103626631/0fa0ec2e-efa0-4b65-974f-9ec8ead12c29)

![image](https://github.com/seerge/g-helper/assets/103626631/555b74d2-7c9d-44ba-b043-d4953aceaf8e)

### Armoury Crate

Installed

### Asus Services

0

### Version

0.155

### OS

Windows 11 23H2

**Comment by nathancdy** [comment]
![image](https://github.com/seerge/g-helper/assets/103626631/b8d0ecdf-3e89-495b-aec1-62a63725e687)

![image](https://github.com/seerge/g-helper/assets/103626631/10149f55-becd-40d0-8447-8edb783a42c6)

GHelper freezes and this pops up when unplugging the charger.

**Comment by nathancdy** [comment]
Edit 2 Tray Applications (Highlighted Tray icon + NVIDIA Settings was not showing up prior to uninstalling AC despite the dGPU showing up in AC and the Device Manager)

![image](https://github.com/seerge/g-helper/assets/103626631/ca23f14a-daf2-4fcf-a6f7-48247615e858)

**Comment by seerge** [comment]
@nathancdy hello, what you explain is most probably a Nvidia driver hiccup connected with booting up in eco mode. Please check this thread for an explanation https://github.com/seerge/g-helper/discussions/1042

Just set "Enable dGPU on shutdown" and make sure that you reboot in Standard (or Optimized but plugged in case)

Then you should be fine

**Comment by nathancdy** [comment]
@seerge I will test when I get home! Does the Enable dGPU on shutdown cause problems when booting on battery though? (As I typically only boot on battery as I am always out)

**Comment by seerge** [comment]
@nathancdy if you are on Optimized - it shouldn't as it would set Eco again on app start :)

If you want to force Eco anyway, there is a config param that has to be added 
https://github.com/seerge/g-helper/wiki/Power-user-settings#force-last-used-gpu-mode-ie-standard-or-eco-on-app-start--restart

**Comment by seerge** [comment]
@nathancdy if you are still there.

I have G14 2024 now too. And I tested this scenario for myself here, and even if I explicitly shutdown / reboot in Eco - I'm still able to switch between Eco - Standard as many times as I want w/o issues.

It could be that Nvidia has fixed that somehow with their recent drivers (I use latest ones from Nvidia itself)

What drivers did you use ?

**Comment by nathancdy** [comment]
@seerge I was on the stock Studio driver 546.28, I'm about to change to the Game-Ready Driver 551.76 and retest. 

Also, just restating my current scenario, I changed to setting the GPU mode to just Optimized with 'Enable dGPU on shutdown', and upon starting up then plugging in my charger, the GPU mode still says 'iGPU only', then clicking on Optimized again moves the highlighted frame/outline to Eco, then clicking Optimized a second time finally changes the mode to iGPU + dGPU.

**Comment by nathancdy** [comment]
> Also, just restating my current scenario, I changed to setting the GPU mode to just Optimized with 'Enable dGPU on shutdown', and upon starting up then plugging in my charger, the GPU mode still says 'iGPU only', then clicking on Optimized again moves the highlighted frame/outline to Eco, then clicking Optimized a second time finally changes the mode to iGPU + dGPU.

@seerge This problem is still occurring. I would have to click on Optimized twice for it to change the GPU mode to iGPU + dGPU when I plug in my charger. Here is my log for context.
[log.txt](https://github.com/seerge/g-helper/files/14776002/log.txt)

**Comment by seerge** [comment]
@nathancdy do you have “keep gpu disabled on usb-c” checked under Extra? It looks like BIOS reports charger as usb-c, so it doesn’t switch intentionally

**Comment by nathancdy** [comment]
@seerge That fixed it, Thanks!

Is this a new thing or also the same BIOS behaviour for USB-C for 2023 models? I'm curious since there are posts on Reddit saying that USB-C charging may have passthrough now.

**Comment by seerge** [comment]
@nathancdy no, it's not connected. It's just BIOS reporting wrong data. It says you are on battery ...

I have made a small tweak, check if this build works better for you

[GHelper.zip](https://github.com/seerge/g-helper/files/14776886/GHelper.zip)

**Comment by nathancdy** [comment]
@seerge Yup that fixed it! Launched that new build, re-enabled Keep dGPU off on Optimized Mode, plugged in the regular charger, and the GPU mode automatically changes to iGPU + dGPU now! Thanks again for your work

Here's the log for context if you need it.

[log.txt](https://github.com/seerge/g-helper/files/14783312/log.txt)
