### ISSUE TITLE
Max Fan Speed in GHelper is not being calculated correctly

### ISSUE THREAD

**Issue by rktfier** [seerge/g-helper#2145]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I can get my fans to run at 10200~RPM by enabling/disabling "Apply Custom Fan Curve" and hear them get faster, but when I attempt to calibrate with these values, measured CPU fan speed gets reported as -100 and doesn't change.

### How to reproduce the bug?

1. Put the computer under load, CPU Temp limit is set to 94 and turbo is stable.
2. View the fan speeds reported (9200RPM Max, also the max value available  on GHelper, Apply Custom Fan Curve is disabled)
3. Enable, and quickly disable Apply Custom Fan Curve
4. Monitor fan speeds reach 10200RPM and hear them go up in speed as well
5. Start a calibration while the fans are at their max speed (load is still being applied)
6. The calibration detects fan RPM as 10200 but during the calibration fan speeds drop down to 8800RPM
7. Calibration ends with reported fan speed for CPU: -100

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14464686/log.txt)

### Device and Model

Asus ROG Flow X13 GV301RC

### Additional information.

Calibration never reaches above 9200RPM by itself under no load. The fans are spinning slower than usual, I can hear them. A few versions back this wasn't an issue.

![image](https://github.com/seerge/g-helper/assets/75695425/b22a136b-ba1d-4a04-97f3-873cf37adb08)
Here is the calibration result.

Armory Crate and MyAsus are installed but they are not running, so I'm able to set my charge limits and such from GHelper. Another issue with GHelper is no matter what i do, the gyroscope is always broken and i'm forced to install MyAsus + Armory Crate to fix it, but i guess that deserves it's own issue.

### Armoury Crate

Installed

### Asus Services

8

### Version

0.154.0

### OS

W11 23H2

**Comment by seerge** [comment]
@rktfier hello,

As I understand you are comparing "default" fan behavior (i.e. w/o applying custom fan curve) with custom fan curves. 

In both cases fans are controlled by BIOS, but often Asus engineers have intentionally restricted maximum speed of a "custom" fan curve presumably to prevent abuse and wear, and it's good.

When you click ``Calibrate``, the only thing G-Helper does is sets a 100% fan curve and just waits until fan speed will reach it's **allowed** maximum. This is needed to more correctly show RPM values on Y-axis (as you set fans in %, not in RPMS)

Your fans go up to 9200RPM (by your own words) in calibration, and that is your maximum you can achieve with custom curve :) so there is nothing wrong with it.

When you "abuse" calibration, by spinning fans faster with default behavior and then just catching it with calibration button you just abuse system. You won't get correct values in that way anyway. 

---

As for Gyroscope G-Helper doesn't touch it anyhow :) As I understand it's supposed to be handled by windows / drivers natively ?

**Comment by seerge** [comment]
@rktfier the only thing i can "tweak" here is increase hardcoded ``INADEQUATE_MAX = 92`` value that would assume everything being above 9200 inadequate measurement to 102 :)

So you won't get -100 at least as a result

Try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14464820/GHelper.zip)

**Comment by rktfier** [comment]
Thanks for the quick reply @seerge,

I've taken your comments into consideration and tested this behavior in Armory Crate. When set to Turbo configuration in Armory Crate, my fans are able to run above the 9200RPM limitation, often averaging around 9700RPM and reaching 10200RPM under heavy load. I'd expect the same to happen when I disable "Apply Custom Fan Curve" under GHelper.

Currenly testing out if the RPM will stay the same during long CPU loads, as I've been able to set my fan curve to 10200RPM in the past without any issue for long periods of time (during long load sessions such as rendering/simulation).

**Comment by rktfier** [comment]
Hello @seerge, I've concluded my testing.

It does seem like you're right, there seems to be a soft limit at around 8900RPM where after a while turbo will settle in. I've been able to catch the initial spike at 10900RPM but after a short while it always seem to drop down to 8800RPM, probably so during the initial turbo peak the system doesn't shut down due to temperature.

I'm able to abuse this system by applying and reverting the custom fan curve setting and keep it stable at around 10200RPM-10600RPM range but I don't think It's worth wearing down the fan for the 0.2Ghz additional performance.

Thanks for your help and quick response!

**Comment by seerge** [comment]
@rktfier ok, does the build i linked here correctly show fan rpm after "calibration" ?

**Comment by rktfier** [comment]
Yes it does @seerge 

I'd include a screenshot but It appears that I've caused a thermal shutdown while calibrating since during the calibration the fan speed drops back to 8800RPM

**Comment by seerge** [comment]
@rktfier  Ok, great :) I'm closing this as completed then as rest (i.e. how fans run) is up to BIOS on specific model anyway
