### ISSUE TITLE
CPU Boost settings don't save (or keep reverting)

### ISSUE THREAD

**Issue by alexsighy** [seerge/g-helper#2146]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I like to disable CPU Boost as it's completely useless for me, I see no difference in FPS only in temperature, with it turned on (on any setting) my CPU hits 95 degrees. With it turned off I have 70 degrees and the same FPS if not less frame drops.

However, lately I've noticed that when I start a game, it goes back to the default settings. CPU Boost goes to aggressive mode and windows power mode goes to balanced (I set it to better power efficiency) and I have to set it manually every time...

Could you please help me figure out what's the problem or if it's a problem on my end

### How to reproduce the bug?

Open G-Helper
Make your desired changes
Open a game after it all goes back to default settings like explained above

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14465826/log.txt)

### Device and Model

ROG Zephyrus G14 GA401IHR

### Armoury Crate

Never installed

### Asus Services

6 services 

### Version

0.154.0

### OS

Windows 11 23H2 (Atlas OS)

**Comment by seerge** [comment]
@alexsighy hello,

I see that app disables boost every time you select mode where it's disabled.

But I also see that something else (not g-helper) is constantly changing power plan to something else. It could be some asus leftovers or any other app / windows settings you have, so make sure you always use Balanced power plan.

1. Just make sure that you have disabled boost in dropdown in EACH mode you use
2. Stop / remove any other software that interferes with power plan changes

Closing as there is nothing to fix here.
