### ISSUE TITLE
Mode with Unapplied Power Limits retaining Power Limit from Mode with an Applied Power Limit

### ISSUE THREAD

**Issue by nathancdy** [seerge/g-helper#2148]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Switching from Silent to Balanced or Turbo still keeps the Silent Power Limit at 10W. For Balanced and Turbo, I don't apply Power Limits.

### How to reproduce the bug?

1. Change from Silent to Balanced or Turbo (or in general, any mode that has an applied power limit to another mode with no applied power limit

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14468045/log.txt)

### Device and Model

ASUS Zephyrus G14 GA403UV

### Additional information.

**Silent Power Limit**
![image](https://github.com/seerge/g-helper/assets/103626631/17395315-89c4-401d-b169-fed06108054a)

**Balanced Power Limit**
![image](https://github.com/seerge/g-helper/assets/103626631/d8c84ffb-35b5-44c8-b268-76e2565fbdde)

**Turbo Power Limit**
![image](https://github.com/seerge/g-helper/assets/103626631/2618ce16-7a33-430b-931f-d51883293ff3)

**CPU Wattage Values in HWInfo when on all 3 Modes**
![image](https://github.com/seerge/g-helper/assets/103626631/048fd71b-9baf-4f00-9afc-bf5603ded57d)

I noticed this when I was doing benchmarks and my CPU was being capped at 10W regardless of mode if initially or changed on Silent. Restarting with Balanced or Turbo on before restart fixes the issue.

I also noticed that all 3 fans takes a while to ramp up compared to the values given in the fan curves in each mode (applied or unapplied), it's a bit slow until it ramps up, resulting in thermal throttling during benchmarks.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.156

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@nathancdy hello,

The way all Asus laptops work - when you set a new "mode" (Silent / Blanced / Turbo) BIOS would reset all power limits and fan curves and set whatever is hardcoded for each mode.

After that optionally app can apply a custom power limit and / or fan curve.

If it's not resetting by some reason - then it's just a bugged BIOS unfortunately. In AC you can't set a custom limits to anything but Turbo mode (called Manual), so they probably didn't even test that.

--

I see that you don't have custom power limits but you do have custom fan curves for each mode. Can you check if unchecking custom fan curve on Balanced / Turbo (or just clicking Factory defaults that does same) resets modes limits ?

**Comment by seerge** [comment]
@nathancdy did you had a chance to check if modes w/o custom curves reset to default power limits? As it depends on what I can offer next here + I need to know that this is not your observation / measurement error as well :)

I have prepared a build, where I have a added a small (100ms) delay between setting mode itself and applying custom fan curves. May be that will make difference.

[GHelper.zip](https://github.com/seerge/g-helper/files/14471021/GHelper.zip)

**Comment by nathancdy** [comment]
@seerge I've tested it just now, I'm not sure exactly which part fixed it but I applied power limits to Balanced and Turbo last night, and booted it up just now on Silent, removed the power limits AND custom fan curves for Balanced and Turbo and tried benchmarking, and it seems like the power limit is gone/fixed and is going over the 10W limit. I feel like I can recall last night that the power limit still remained at 10W with custom fan curves applied and unapplied though.

I'm still confused about the fans/temps at this point cause seeing other 2024 G14 reviews on Youtube, in CPU and GPU workloads and CPU only workloads the CPU doesn't run as hot (doesn't hit over 80 degrees whereas mine has hit 90+ in CPU and CPU+GPU workloads for benchmarking). I also updated the BIOS to 303 so that might've changed the power behaviour, I believe the reviews I've seen is the stock BIOS (301).

**Comment by seerge** [comment]
@nathancdy rebooting has nothing to do with that :) as it resets everything you had. And on each app start G-Helper anyway sets last used mode (and power / fans if they are checked)

Do I understand correctly that even **your existing build** (not the one I linked here) works fine ?

Temps depend a lot on how lucky you are with liquid metal, als on BIOS probably and actual power consumption.

As for fans - keep in mind that all reviewers test in default modes (i.e. Turbo or Balanced w/o applying any custom fan curves), so if you want identical settings - you should uncheck fans as I mentioned above.

**Comment by nathancdy** [comment]
Yeah, my existing build works. Also, unchecking fans and everything default, I still find that my temps are much higher as seen in reviews, I'm hoping since I'm on the updated BIOS that the power behaviour changed.

**Comment by seerge** [comment]
@nathancdy last year I returned G14 2023 that I bought, cause it had terrible LM. It couldn't sustain even 60W on CPU load (was hitting 96C in a second)

My current and old G14 **2022** manages sustain 85W on CPU only easily.

LM application varies from device to device a lot unfortunately due bad QC

**Comment by nathancdy** [comment]
@seerge Not sure if I want to return my model as the stock is very limited in my region at the moment (4060, 32GB RAM). I'll do some more additional testing and if I find it legitmately unusable for my routine use then I'll definitely consider it.
Thanks for your help!

**Comment by seerge** [comment]
@nathancdy 90C is OK temp for max load still. Unless you hit 96C and CPU starts throttling (i.e. dropping own power) - you are OK.

**Comment by nathancdy** [comment]
@seerge To be honest, in my Cinebench benchmarking, it was sustaining 90C+ max load (sometimes hitting 95) for 2 minutes straight in each attempt and I've stopped it at the 2 minute mark just because I didn't feel comfortable with it maintaining that temp for that long. Should I give it another shot and let it go for the full 10 minute benchmark? Or at least let it continue longer (i.e. 5 minutes)?

**Comment by seerge** [comment]
It's up to you :) just monitor it via HWinfo and check if it says throttling (or if wattage just drops)

**Comment by seerge** [comment]
@nathancdy since you are here, does the new [GPU Power slider](https://github.com/seerge/g-helper/discussions/2141) that I have added work for you ?  I was wondering if it's possible to push G14 a bit above default 90W (65 base + 25 boost)

**Comment by nathancdy** [comment]
@seerge I'll do a 3DMark Time Spy benchmark and I'll get back to you! I'll test it at 70 + 25 for now then test further if temps are okay

**Comment by nathancdy** [comment]
@seerge I was about to benchmark but I received this unhandled exception/error upon clicking 'Factory Defaults' while on Balanced Mode. 

![image](https://github.com/seerge/g-helper/assets/103626631/922e6ead-3084-452e-b1f3-580d400dac1c)

**Comment by seerge** [comment]
@nathancdy copy all contents from "details" here :)

**Comment by nathancdy** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '80' is not valid for 'Value'. 'Value' should be between 'Minimum' and '$Maximum'. (Parameter 'value')
Actual value was 80.
   at System.Windows.Forms.TrackBar.set_Value(Int32 value)
   at GHelper.Fans.ButtonReset_Click(Object sender, EventArgs e) in C:\Users\Serge\g-helper\app\Fans.cs:line 1122
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Private.CoreLib.dll
----------------------------------------
GHelper
    Assembly Version: 0.156.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.52009
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.14/System.Windows.Forms.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Threading.Thread.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.52009
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.14/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Collections.Specialized.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.14/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Diagnostics.Process.dll
----------------------------------------
System.Collections
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Collections.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Text.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Text.Json.dll
----------------------------------------
System.Threading
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Threading.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Collections.Concurrent.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Private.Uri.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Text.Encodings.Web.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Memory
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Memory.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Management
    Assembly Version: 7.0.0.1
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/Microsoft.Win32.Registry.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Security.Claims.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.14/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.14/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.52009
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.14/System.Drawing.dll
----------------------------------------
NAudio.Wasapi
    Assembly Version: 2.1.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.1423.52009
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.14/Accessibility.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.ComponentModel.dll
----------------------------------------
WinForms.DataVisualization
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
WinForms.DataVisualization.Utilities
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/netstandard.dll
----------------------------------------
HidSharpCore
    Assembly Version: 2.1.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Linq
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Linq.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Threading.ThreadPool.dll
----------------------------------------
Microsoft.Win32.TaskScheduler
    Assembly Version: 2.10.1.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ObjectModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.ObjectModel.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Text.RegularExpressions.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Private.Xml.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Runtime.Loader.dll
----------------------------------------
NvAPIWrapper
    Assembly Version: 0.8.1.100
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.PerformanceCounter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.14/System.Diagnostics.PerformanceCounter.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Threading.Overlapped.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Collections.NonGeneric.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Runtime.Intrinsics.dll
----------------------------------------
System.Net.Http
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Security.Cryptography.dll
----------------------------------------
System.Net.Quic
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Net.Quic.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Net.Sockets.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Net.NameResolution.dll
----------------------------------------
System.Data.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Data.Common.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.Collections.Immutable.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1423.51910
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.14/System.IO.Compression.dll
----------------------------------------

************** JIT Debugging **************

**Comment by nathancdy** [comment]
@seerge Sorry, wanted to note upon quitting/restarting GHelper, the error for Factory Defaults went away on Balanced, but occurs in Turbo.

**Comment by nathancdy** [comment]
@seerge Unfortunately the 70 + 25 power limit didn't work, Through HWInfo, GPU only went to max 88.5W.

**Comment by nathancdy** [comment]
Wanted to also note that my original issue still occurred, but fixed it by applying then unapplying power limits to Balanced and Turbo.

**Comment by seerge** [comment]
@nathancdy this build should fix it

Can you also click Factory defaults in this build on each mode and post a log from that ? (it reads current value from asus settings, and i want to check why it's out of slider range)

[GHelper.zip](https://github.com/seerge/g-helper/files/14472336/GHelper.zip)

As for 90w, i think it's cause you still have 90W VBIOS, so that's another limit ...

Arre you able to limit power to the lower amounts ? Like what is the absolute minimum it lets you to set ? and does it work ?

**Comment by nathancdy** [comment]
[log.txt](https://github.com/seerge/g-helper/files/14475450/log.txt)

@seerge I'll probably test the power limit in the future, but the absolute minimum it sets me for GPU is 55W.

**Comment by seerge** [comment]
@nathancdy ok, thanks :) 55W looks correct. As whole GPU Power setting consists of 2 components, 1st is like fixed minimum value (it's 55 for G14) and variable part that you can drag / set.

**Comment by seerge** [comment]
@nathancdy I'v got G14 2024 as well, tested it a bit and you were partially right in initial issue.

Current BIOS, has some bug when power limits will not reset to defaults from Manual mode. It happens in both AC / G-Helper (obviously, cause it's in BIOS).

Scenario to reproduce in AC

1. Apply Manual mode (it's Turbo under the hood) with some custom power limits (for example set 25W to all).
2. Select Turbo mode
3. Power limits will remain 25W ..

Scenario to reproduce in G-Helper
1. Apply custom power limits in any mode
2. Uncheck custom limits or just select same mode w/o limits

Main idea here, is that you select **same** base mode as you had before, just w/o limits

To reset limits - you need to select **other** mode. For example if you had Manual (Turbo) with limits - you need to select Balanced.

I have already pushed a new release https://github.com/seerge/g-helper/releases/tag/v0.156 where G-Helper would do that automatically for you.
