### ISSUE TITLE
Time scheduling of battery charge limits

### ISSUE THREAD

**Issue by sjain882** [seerge/g-helper#2152]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Not related to a problem - rather a UX enhancement

### Describe the solution you'd like

Hi,

I appreciate this feature might be considered bloat / non-essential, however it would still be a nice UX enhancement imo.

I only use my laptop away from its brick charger on two set days a week.

Often, I forget to set the charge limit from 50% to 100% the night before.

Even if I'm able to access USB-C PD charging, the work I do is somewhat intensive enough that the battery ends up needing to charge while using the laptop with USB-C PD. Plus, a low battery with unreliable access to a wall plug is not ideal.

It is hardly a priority, but it would be useful to be able to schedule a one-time charge limit change at a certain day & time of the week, to ensure the laptop is ready to go the next morning, but not on 100% constantly throughout the week, which would waste its life.

This could be presented as a simple table in the "Extra" section.

Let me know your thoughts!

### Device and Model

Asus Zephyrus G15 GA503-QM 2021

**Comment by seerge** [comment]
@sjain882 hello, I didn't really get what you want but you can already schedule one-time charge to 100% with appropriate button

![Screenshot 2024-03-02 183845](https://github.com/seerge/g-helper/assets/5920850/fb6012a3-9821-4f80-894f-959284ae77c1)

It will turn off automatically as soon as it spots 100% charge.

**Comment by sjain882** [comment]
I'm afraid you mis-understood my problem, I mean scheduling that feature to a user-specified value, on a specified time & day of the week.

**Comment by seerge** [comment]
@sjain882 i'm afraid this is extremely exotic thing :) If I will be adding this thing to the app, someone else would ask an option do disable GPU on fool moon, and set backlight off at 17:43, etc ...

You can manually automate this, by doing some autohotkey or powershell script that would modify ``config.json`` and then re-launch app.

This param is responsible for 100% charge, it needs to be set to 1

```
"charge_full" : 1,
```

**Comment by sjain882** [comment]
Fair enough, I didn't consider that possibility, that is definitely good enough. Thanks!
