### ISSUE TITLE
Option to re-enable dGPU on system shutdown / application quit

### ISSUE THREAD

**Issue by sjain882** [seerge/g-helper#2153]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

This problem can be best described with a full description of my use-case:

**Setup:**

I have an Asus Zephyrus G15 2021 GA503QM. This model does not have a MUX switch. Therefore, the HDMI port & built-in screen go to the AMD iGPU, and the USB-C ports go to the NVIDIA dGPU. You cannot change this behaviour.

At home, I have 2 external monitors: a side one plugged into the HDMI port (1080p 100% DPI), and a main one plugged into the USB-C port (1440p 125% DPI).

**Situation:**

I shut-down my laptop and take it outdoors.

I boot up the laptop. G-Helper automatically disables the dGPU as I always use "Optimised" mode.

I finish my work, then shut-down the laptop.

I come home, plug everything in, then boot up the laptop.

Because the dGPU is still disabled before G-Helper starts, when I log into windows, my main monitor which is connected to the dGPU via the USB-C port never gets connected.

Therefore, Windows sets the DPI to 100% instead of 125%, and the monitor arrangement messes up (duplicates the built-in screen and side monitor).

Eventually my main monitor comes on but the DPI is still wrong, so some applications look blurry or too large/small.

Every time this happens, I have to sign out and sign back in again to fix it. Not the end of the world but if you have a lot of auto-start applications can get a bit messy for them & slow.

### Describe the solution you'd like

I believe the solution in this case would be to add an option in the "extra" section to re-enable the dGPU on system shutdown / application quit. Feel free to suggest any better / more streamlined solutions!

### Device and Model

Asus Zephyrus G15 GA503-QM 2021

**Comment by seerge** [comment]
@sjain882 you already have this option. It's called ``Enabled GPU on shutdown`` under ``Extra``. It's purpose is very different (to prevent Nvidia driver issues from booting into Eco), but it does same thing.

Despite it's name "Hibernate" is also covered :) so you can just shutdown / hibernate your device after using on battery :)

**Comment by sjain882** [comment]
I see, thank you! My apologies, I should have tried that :)
