### ISSUE TITLE
Weird fnlock hotkey behavior on Zenbook UX6404 + Keyboard Backlight not working

### ISSUE THREAD

**Issue by FlashLightning67** [seerge/g-helper#2154]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [x] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

On my Zenbook Pro 14 OLED (UX6404), upon restarting the computer with asus services disabled, and ghelper set to start on startup, function lock seems to break. When with fnlock disabled in ghelper, each key is the normal function key (fn1-12). With fnlock enabled, things get messed up with the volume controls adjusting keyboard backlight up and down (it doesn't change anything because that doesn't work, but the popup shows up), brightness down changing the backlight mode, brightness up changing the performance mode, and so on. However both with fnlock on or off, holding down the fn key myself gives the expected hotkey behavior. Starting and stopping asus services fixes the issue temporarily, hibernation seems to make it break again but not entirely sure.

Additionally, adjusting the keyboard backlight on this device doesn't seem to work with ghelper. If I disable asus optimization, the button will show the popup from ghelper but the brightness doesn't change. The slider doesn't work either.

### How to reproduce the bug?

Fn key:
1. Disable all asus services using the button in ghelper.
2. Restart laptop
3. Open ghelper (if it wasn't already set to open on startup)
4. Try using function keys, with fnlock on and off and while holding down fn
Keyboard backlight:
1. Disable all asus services
2. Try adjusting keyboard backlight, both with the hotkeys and using the slider

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14471162/log.txt)

### Device and Model

Asus Zenbook Pro 14 OLED (UX6404)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

Latest

**Comment by seerge** [comment]
@FlashLightning67 did you had Fn-Lock in Asus software ? (i.e. was it hardware fn-lock) ?

Try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14471186/GHelper.zip)

**Comment by FlashLightning67** [comment]
That build works perfectly! The keyboard backlight is adjusting, and the fn lock is working properly* even after restarting the laptop. 

There is an fnlock option in myasus on this laptop if you still need that information. 

*One weird thing that I figured I’d mention, I’m not sure if this was after restarting the laptop or just restarting ghelper, but the camera toggle stopped working. It was working when I tried it initially, but won’t work again. Even when it was working it seemed a bit off as the led that indicates whether it’s disabled wasn’t turning on, while the mic mute led was turning on and off (and mic mute still works).

**Comment by seerge** [comment]
@FlashLightning67 glad to hear.

As for camera toggle, G-Helper can toggle camera only when app runs as admin unfortunately
Check this issue, where it was asked https://github.com/seerge/g-helper/issues/2060

As I simply don't know "traditional" way the asus does it. It is possible to "debug" it from AC / MyASUS by installing [special software](https://github.com/seerge/g-helper/wiki/_ACPI-Monitoring-and-Debugging) - but let me know if you want to bother with that :)

**Comment by FlashLightning67** [comment]
I'm not personally very bothered about the camera toggle, so it doesn't seem worth the effort to me to disable secureboot and bitlocker and all that.

Do the steps in #38 still work for this? Those seem easier and I'd be happy to give that a try instead.

**Comment by seerge** [comment]
@FlashLightning67 camera disable will work if you would just start app as admin. App would toggle appropriate setting in windows.

**Comment by FlashLightning67** [comment]
Gotcha, that should work perfectly if I ever do need that feature.

One thing I just noticed, this laptop has a dial built into the track pad that can be used to change the volume and what not, and it can be enabled or disabled with a swipe gesture. This dial lights up when it is enabled, but with ghelper running (after a restart with the asus dial services disabled), the light doesn't light up when it's on. It still does enable and disable, there is just no indication of that. Is that something that ghelper could do?

**Comment by seerge** [comment]
@FlashLightning67 I have no idea how does that dial work :) You can check app log ``%appdata%\ghelper\log.txt`` and try to do that swipe / toggle and see if it produces any WMI code in a log.

If not - I can't do much without having actual device on hand and debugging it

**Comment by FlashLightning67** [comment]
I see, unfortunately there is no WMI code in the log.

However I have found a relatively good solution. After uninstalling all the ASUS dial software, there is a service left behind called "ASUSDialPadService" which normally seems to integrate the dial with the ASUS software, but without the software it's only able to toggle the light (with the dial working as a normal windows dial, rather than the special ASUS one). Figured I'd mention that incase anyone else is ever looking for a solution for that. I'd disable the dial all together if I could, but disabling that service just makes the light stop turning on, while the dial still gets enabled.

**Comment by seerge** [comment]
@FlashLightning67 ok :) apparently there is a whole separate service for that thing. Then it's clearly I can't implement that w/o knowing more details.

As I understand original issue is resolved, therefore closing this as completed and will include this changes in next release
