### ISSUE TITLE
Swapped curves on Zephyrus G15 2022 GA503RW

### ISSUE THREAD

**Issue by FliesQQ** [seerge/g-helper#2155]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

GPU and CPU are swapped in G-Helper, the GPU curve changes the rotation speed of the CPU fan, and the CPU curve changes the GPU fan.
And power limit setting not working.

### How to reproduce the bug?

Set CPU Fan speed to max, GPU fan speed to max
Set GPU Fan speed to max, CPU fan speed to max
![GA503RW-1](https://github.com/seerge/g-helper/assets/33315357/e43fb755-0c72-4d5f-a7c8-6213398c51c2)
Custom power limit not working.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14471997/log.txt)

### Device and Model

ASUS Zephyrus G15 (2022) GA503RW

### Armoury Crate

Uninstalled

### Version

0.154

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@FliesQQ hello,

They are swapped not in G-Helper but in BIOS due to a bug from Asus. 

Check this Issue for example https://github.com/seerge/g-helper/issues/2049
Or even reddit thread https://www.reddit.com/r/ZephyrusG15/comments/1b22sju/i_got_fucked_over_by_the_new_bios_update/

What BIOS version do you have ?  As I have added a swap-back "tweak" for BIOS **317**

**Comment by FliesQQ** [comment]
> @FliesQQ hello,
> 
> They are swapped not in G-Helper but in BIOS due to a bug from Asus.
> 
> Check this Issue for example #2049 Or even reddit thread https://www.reddit.com/r/ZephyrusG15/comments/1b22sju/i_got_fucked_over_by_the_new_bios_update/
> 
> What BIOS version do you have ? As I have added a swap-back "tweak" for BIOS **317**

Bios version is 316
only ga503rw are 316,not 317

**Comment by seerge** [comment]
Try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/14472328/GHelper.zip)

**Comment by FliesQQ** [comment]
> @FliesQQ
> 
> Try this build [GHelper.zip](https://github.com/seerge/g-helper/files/14472328/GHelper.zip)

This one worked! CPU and GPU fan speed all worked correct.

**Comment by seerge** [comment]
@FliesQQ Great

**Comment by seerge** [comment]
@FliesQQ Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks

**Comment by seerge** [comment]
@FliesQQ in 0.161 same as any other release leaves fan controls up to BIOS. 

That's why I offered you a separate discussion thread with a special experimental build.

**Comment by FliesQQ** [comment]
> @FliesQQ in 0.161 same as any other release leaves **fan controls up to BIOS.**
> 
> That's why I offered you a separate discussion thread with a special experimental build.

I'd like to have a try, How do I do?

**Comment by seerge** [comment]
@FliesQQ download build from this thread https://github.com/seerge/g-helper/discussions/2272
