### ISSUE TITLE
Mode indicator on status bar icon.

### ISSUE THREAD

**Issue by Kikimahe** [seerge/g-helper#2156]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

hi, 

Very often, I forget to switch to silent mode when performing light tasks. 
And several times a day I have to open the Ghelper window to see the CPU mode used.

Would it be possible to have a CPU mode indicator, directly on the status bar icon?  :)

### Describe the solution you'd like

Add a discrete indicator to see the CPU mode used without having to open the Ghelper window.

Something like this for example :
Silent
![silence](https://github.com/seerge/g-helper/assets/142881210/7fa9e10d-4c7d-47ce-8ef9-04cf82fb58ef)

Balanced 
![equilibré](https://github.com/seerge/g-helper/assets/142881210/a98c984e-9fc1-4441-95b3-ff1bf1bf9cc7)

Turbo 
![turbo](https://github.com/seerge/g-helper/assets/142881210/848af167-0a7d-4bcd-935e-aa44425df699)

Custom mode 
![personalisé](https://github.com/seerge/g-helper/assets/142881210/84ddbaa5-040e-4747-af37-2172ce900961)

### Device and Model

Tuf F17 FX707ZM

**Comment by seerge** [comment]
@Kikimahe hello :) I was thinking about something like this before, not with checkmarks but with coloring circle in 2 halves or something like that.

Thing is I don't generate icons on the fly, and I would have to create like 9 different combinations. Next to that it will be a lot of questions (and screams) of what does that mean on reddit ...

What I can offer, is to show currently used mode in tooltip on mouse over tho

**Comment by Kikimahe** [comment]
Ah damn. I thought that like you did for the GPU, it would be easy to do for the CPU as well. :)

Indeed, a minimum of 9 combinations are required if this is to be added to the GPU icons (12 if custom mode is added).

In my opinion Reddit questions will be rare. 
By keeping the mode colors, the logic is very easy to understand.

The tooltip I think is not great because you will always have to move the mouse over the icon. Yes, I am very lazy. :)

Have a nice day.
