### ISSUE TITLE
Where is my M4??

### ISSUE THREAD

**Issue by LuzeBillan** [seerge/g-helper#2157]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I'm using strix 7 and I have FIVE function buttons. But I can only customise M1, 2, 3 and 5. So where is my M4?

### How to reproduce the bug?

ez to reproduce

### Logs

none.

### Device and Model

Strix 7

### Armoury Crate

Uninstalled

**Comment by seerge** [comment]
@LuzeBillan Hello, I was answering this **numerous of times.** 

On Strix models M4 and FN+F5 produce exactly same code. And this is reserved by the app for switching profiles forwards and backwards. Therefore there is no reason to rebind it as you can't separate it from FN+F5

**Comment by LuzeBillan** [comment]
> @LuzeBillan Hello, I was answering this **numerous of times.**
> 
> On Strix models M4 and FN+F5 produce exactly same code. And this is reserved by the app for switching profiles forwards and backwards. Therefore there is no reason to rebind it as you can't separate it from FN+F5

Really? But in Armoury Crate I do rebind my M3/M4 to control my screen brightness and it works properly without changing the function of Fn+F5

**Comment by seerge** [comment]
@LuzeBillan AC can rebind buttons on some hardware level, G-Helper doesn't use that cause it causes some unpredictable behavior, like keys stop working, etc.

**Comment by LuzeBillan** [comment]
I see.. thanks anyway

**Comment by satandidnowrong** [comment]
Is there then no way to rebind M4/FN+F5? There are rebinds for FN+F4 and FN+C.

**Comment by seerge** [comment]
@satandidnowrong FN+C is vacant :) and FN+F5 has complicated logic under the hood, it has backwards / forwards profile toggling, so i don't want to change that

**Comment by satandidnowrong** [comment]
I would like to disable its function. Would it be easy enough to add a disable toggle or drop down like the rest that just bind it to no thing?
