### ISSUE TITLE
Strix Carry Mouse DPI is half of what G-Helper reports

### ISSUE THREAD

**Issue by RogueDragon7274** [seerge/g-helper#2158]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Mouse dpi is only half of what G-Helper sets it to. If I have 6400 DPI then actual DPI is 3200, when I set it to 1600 it is actually 800 and so on.

### How to reproduce the bug?

Tested with both https://mousedpianalyzer.com/
as well as in game

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14473249/log.txt)

### Device and Model

Asus Zephyrus G14 2024

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.154

### OS

Windows 11

**Comment by IceStormNG** [comment]
Please try this build here:

[GHelper.zip](https://github.com/seerge/g-helper/files/14473309/GHelper.zip)

**Comment by RogueDragon7274** [comment]
Works! Thx!

**Comment by RogueDragon7274** [comment]
Works, Thx!

**Comment by IceStormNG** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/14473347/GHelper.zip)


Great. I made another change as I saw that the minimum DPI is 50 and not 100 for the carry.
