### ISSUE TITLE
charger_delay causes g-helper to hang when power source changes

### ISSUE THREAD

**Issue by gy123321** [seerge/g-helper#2160]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Laptop: Flow X13 2023 (GV302XV)
OS: Windows 11 23H2 22631.3155 (Windows Feature Experience Pack 1000.22684.1000.0)

If I insert for example `"charger_delay": 15000,` in the `config.json`, the delay function works as intended. But G-helper (both GUI and extra keybindings like ctrl+m1) will freeze for the entire delay time, counting from power source change.

Additionally, if I unplug, wait for 5s, then plug, G-helper will freeze for the set delay time, unfreeze for very short amount of time (less than 1s), then freeze again for the set delay time.

Disabling charger delay solves the problem. Shorter delay time (e.g. 5000) results in the same behavior.

### How to reproduce the bug?

1. Exit G-helper
2. Add `"charger_delay": 15000,` in `config.json`
3. Start G-helper
4. Plug in or unplug

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14481428/log.txt)

### Device and Model

ROG Flow X13 2023 (GV302XV)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.154.0

### OS

Windows 11 23H2 22631.3155 (Windows Feature Experience Pack 1000.22684.1000.0)

**Comment by seerge** [comment]
@gy123321 hello, it does cause it just adds a pause in a thread. I can try to remove that, but I actually don't know if this is a good idea.

Thing is that all actions that app would do as a result of power change (including possible enable / disable of dGPU) is currently carefully executed in correct and timed order. If UI would allow you to perform any other actions in that moment, that action can easily break something or cause other settings to fail.

**Comment by gy123321** [comment]
Got it. Thank you!
