### ISSUE TITLE
Fan Calibration Incorrect

### ISSUE THREAD

**Issue by satandidnowrong** [seerge/g-helper#2164]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

After calibration, reported fan rpm does not match setting.

### How to reproduce the bug?

Calibrate. Adjust fan.

### Logs

05 Mar 2024 12:26:20: ------------
05 Mar 2024 12:26:21: App launched: ROG Strix G733ZW_G733ZW :0.151.0.0en-US
05 Mar 2024 12:26:21: NVIDIA GeForce RTX 3070 Ti Laptop GPU
05 Mar 2024 12:26:22: CPU: -1 - 12th Gen Intel(R) Core(TM) i9-12900H - Intel64 Family 6 Model 154 Stepping 3
05 Mar 2024 12:26:22: AutoSetting for Online
05 Mar 2024 12:26:22: Mode = 4 : OK
05 Mar 2024 12:26:22: FanCPU = 14-1E-28-32-3C-41-46-64-00-06-19-42-64-64-64-64 : OK
05 Mar 2024 12:26:22: FanGPU = 14-1E-28-32-3C-41-46-64-00-06-1C-43-64-64-64-64 : OK
05 Mar 2024 12:26:22: Eco flag : 0
05 Mar 2024 12:26:22: Mux flag : 0
05 Mar 2024 12:26:22: \\?\DISPLAY#BOE0A69#5&2f35d5b2&0&UID4354#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
05 Mar 2024 12:26:22: \\?\DISPLAY#BOE0A69#5&2f35d5b2&0&UID4354#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
05 Mar 2024 12:26:22: ScreenOverdrive = 0 : OK
05 Mar 2024 12:26:22: GET CLOCK LIMIT: 0
05 Mar 2024 12:26:22: USB 19B6|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
05 Mar 2024 12:26:22: BatteryLimit = 60 : OK
05 Mar 2024 12:26:22: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&19e2ad7&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
05 Mar 2024 12:26:22: BatteryLimit = 60 : OK
05 Mar 2024 12:26:22: GET GPU CLOCKS: 0, 0
05 Mar 2024 12:26:22: Init 19B6: 5D-B9
05 Mar 2024 12:26:22: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
05 Mar 2024 12:26:22: Init 19B6: 5D-05-20-31-00-1A
05 Mar 2024 12:26:22: USB 19B6: 5D-BD-01-CF-17-BB-BB-FF
05 Mar 2024 12:26:22: AuraMode: AuraRainbow
05 Mar 2024 12:26:22: USB 19B6: 5D-B3-00-03-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
05 Mar 2024 12:26:22: USB 19B6: 5D-B5-00-00-00
05 Mar 2024 12:26:22: USB 19B6: 5D-B4
05 Mar 2024 12:26:22: Monitor Power On
05 Mar 2024 12:26:23: PowerLimit A3 = 80 : OK
05 Mar 2024 12:26:23: PowerLimit A0 = 80 : OK
05 Mar 2024 12:26:23: Auto 19B6: 5D-BA-C5-C4-01
05 Mar 2024 12:26:24: PowerLimit C0 = 25 : OK
05 Mar 2024 12:26:24: PowerLimit C2 = 75 : OK
05 Mar 2024 12:26:24: GET GPU CLOCKS: 0, 0
05 Mar 2024 12:26:24: GET CLOCK LIMIT: 0
05 Mar 2024 12:26:27: FanCPU = 14-1E-28-32-3C-41-46-64-00-06-26-42-64-64-64-64 : OK
05 Mar 2024 12:26:27: FanGPU = 14-1E-28-32-3C-41-46-64-00-06-1C-43-64-64-64-64 : OK
05 Mar 2024 12:26:28: FanCPU = 14-1E-28-32-3C-41-46-64-00-06-1B-42-64-64-64-64 : OK
05 Mar 2024 12:26:28: FanGPU = 14-1E-28-32-3C-41-46-64-00-06-1C-43-64-64-64-64 : OK
05 Mar 2024 12:26:29: FanCPU = 14-1E-28-32-3C-41-46-64-00-06-1B-42-64-64-64-64 : OK
05 Mar 2024 12:26:29: FanGPU = 14-1E-27-32-3C-41-46-64-00-06-27-43-64-64-64-64 : OK
05 Mar 2024 12:26:32: FanCPU = 14-1E-28-32-3C-41-46-64-00-06-1B-42-64-64-64-64 : OK
05 Mar 2024 12:26:32: FanGPU = 14-1E-28-32-3C-41-46-64-00-06-1A-43-64-64-64-64 : OK

### Device and Model

ROG Strix G733ZW

### Additional information.

Is it possible to increment rpm by 100 in stead of 200?

### Armoury Crate

Installed

### Asus Services

0

### Version

0.151

### OS

11 build 22000

### Image

![Animation](https://github.com/seerge/g-helper/assets/161235843/43a64dbb-96ab-472f-b5dd-16e8f7a6986f)

**Comment by seerge** [comment]
@satandidnowrong I didn't get where they are "reported incorrectly" ? both tooltip / chart show only approximate indication, as under the hood fans are set in percentage points. So they are not supposed to be precise :)

**Comment by satandidnowrong** [comment]
Setting in graph says 3k
GPU fan rpm in ui says 3500.
Set graph to 2400 rpm
GPU fan rpm in ui says 3000

**Comment by seerge** [comment]
@satandidnowrong fans are [always controlled by BIOS](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds),  if your BIOS decides to spin them a bit faster - then that's how it is :) 

As I have told, under the hood it sets fan curve in %, and then device does what it wants to do with that, don't expect exact precision here.

**Comment by satandidnowrong** [comment]
The precision is between the calibrated values displaying in the graph and the reported fan speed of the app.
I don't under stand. The app graph is reporting wrong or setting wrong or the display is reporting wrong?
How is this not the case. Percentages or not, when graph rpm is set, it is not the same rpm that is being applied. This is not an issue?

**Comment by seerge** [comment]
@satandidnowrong what do you propose me to do ? reprogram asus bios ?

**Comment by satandidnowrong** [comment]
I propose that when the calibration button is set, the graph formulates accurate setting values by comparing what the percentage value is making the bios use as fan speed.
In this instance, we would take the larger of the two rps, the setting and the reported speed, and find the difference.
3000 rpm (set) - 2400 rpm (setting) = 600 rpm difference
And adjust what the graph setting says.

Or it could be that if there is a difference between the rpm set by the bios and the graph setting, which would be checked for each value in calibration, the graph would just take the value of the real rpm.

So in this case, when %label 2400 == real rpm 3000, set %label to 3000.

**Comment by seerge** [comment]
@satandidnowrong it's not possible to do what you ask. 

BIOS algorithm is more complicated than just immediately ramping fans up to specific value, it has delays, depends on how fast temperature rises, etc.

Even if you set fan to 100% it can run slower on lower temps, because this is how it's done under the hood. G-Helper has no control over that, it can just show a very **approximate Y-axis with RPMS** to give you idea of what you should expect

That's the reason even in AC (manual mode) you can set fan curve very approximately in some abstract % values, you don't even see RPMs there at all. But you do see RPM in reading.

I cant change this anyhow on app side, therefore closing as not planned and not possible

**Comment by satandidnowrong** [comment]
I don't think you are under standing the issue.

The issue is the value DISPLAYED in G-H graph.
I am not asking for you to affect the bios.
I am asking that your program represends the correct data.
I am having issues finding where in your code the graph numbers are displayed. Please point me there.

**Comment by seerge** [comment]
@satandidnowrong I understand you perfectly.

It's not possible to create precise match between % and RPMs on the chart.  As same % can mean slightly different fan speed for BIOS in different circumstances.

Current implementation (including existing calibration procedure) is best that is possible to do.

If you don't like RPM scale, please click with a mouse on it and switch to % scale as you had in Armoury Crate.

**Comment by seerge** [comment]
@satandidnowrong 

> I am having issues finding where in your code the graph numbers are displayed. Please point me there.
>I am in fans at chartcpu/gpu. I will look here.

I pointed you to the appropriate line of code already few messages ago in this thead
> https://github.com/seerge/g-helper/blob/main/app/Fans.cs#L677

**Comment by satandidnowrong** [comment]
> @satandidnowrong I understand you perfectly.
> 
> It's not possible to create precise match between % and RPMs on the chart. As same % can mean slightly different fan speed for BIOS in different circumstances.
> 
> Current implementation (including existing calibration procedure) is best that is possible to do.
> 
> If you don't like RPM scale, please click with a mouse on it and switch to % scale as you had in Armoury Crate.

I don't under stand what you are saying.
The internal percentages do not need to change.
Only the display value of the percentages in the graph.

**Comment by satandidnowrong** [comment]
> @satandidnowrong
> 
> > I am having issues finding where in your code the graph numbers are displayed. Please point me there.
> > I am in fans at chartcpu/gpu. I will look here.
> 
> I have pointed you to the appropriate line of code already few messages ago in this thread
> 
> > https://github.com/seerge/g-helper/blob/main/app/Fans.cs#L677

I see now, thank you

**Comment by satandidnowrong** [comment]
> > @satandidnowrong
> > > I am having issues finding where in your code the graph numbers are displayed. Please point me there.
> > > I am in fans at chartcpu/gpu. I will look here.
> > 
> > 
> > I have pointed you to the appropriate line of code already few messages ago in this thread
> > > https://github.com/seerge/g-helper/blob/main/app/Fans.cs#L677
> 
> I see now, thank you

Is this where these are decided??

![image](https://github.com/seerge/g-helper/assets/161235843/df749ffd-2925-4223-b752-494dbee03a8f)
![image](https://github.com/seerge/g-helper/assets/161235843/ad2b74a4-c283-4bb4-97f9-288b475e1030)
![image](https://github.com/seerge/g-helper/assets/161235843/b740e4ec-63c3-4d8d-8700-222e36b37409)
![image](https://github.com/seerge/g-helper/assets/161235843/949d334a-c4d1-4506-9ee8-a59ff03ac3b4)

**Comment by satandidnowrong** [comment]
found this am looking now 
![image](https://github.com/seerge/g-helper/assets/161235843/d5bbfb80-d0d9-4217-b8ba-a04239e552e2)

**Comment by satandidnowrong** [comment]
![image](https://github.com/seerge/g-helper/assets/161235843/d524812f-ab8e-47f7-84f0-c364120f1c22)

FOUND IT ok gonna get to work i am gonna have a present for us
YEEhoo HECK yeah I am stoked awe some this will be fun
(meant to post this here mb)

**Comment by satandidnowrong** [comment]
![image](https://github.com/seerge/g-helper/assets/161235843/262163d0-e251-4f3a-beaf-25723ab226f1)

found the display
