### ISSUE TITLE
[Request] Add Vivobook Pro 15 OLED (M3500QC) to the list of OLED devices

### ISSUE THREAD

**Issue by teodor-matei** [seerge/g-helper#2168]
Hi,

I've noticed that support for flicker-free dimming has been added to G-Helper. I was wondering if it would be possible to add the Vivobook Pro 15 OLED to the list of supported devices, since the option doesn't show up in the current version (G-Helper reports the laptop as Vivobook_ASUSLaptop M3500QC, so no OLED in the name is probably the reason it doesn't display the slider).

Thanks in advance!

**Comment by seerge** [comment]
@teodor-matei try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/14515323/GHelper.zip)

**Comment by seerge** [comment]
@teodor-matei ok 

Can you

1. Download and launch https://learn.microsoft.com/en-us/sysinternals/downloads/procmon 
2. Go to filters in it and add 2 filters as on screenshot (with green checkbox)
![Screenshot 2024-03-06 223624](https://github.com/seerge/g-helper/assets/5920850/41dbf2ef-c32f-4e2c-a7dc-87682251ea5c)
3. Click on [CAPTURE] icon
4. Launch MyASUS and set Dimming to your desired level
5. Check what Process Monitor captured ?

**Comment by teodor-matei** [comment]
[Logfile.CSV](https://github.com/seerge/g-helper/files/14515957/Logfile.CSV)
These are the results after setting the dimming level to 50% and then back to 100%.

**Comment by seerge** [comment]
@teodor-matei try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/14516107/GHelper.zip)

**Comment by teodor-matei** [comment]
> @teodor-matei try this build [GHelper.zip](https://github.com/seerge/g-helper/files/14516107/GHelper.zip)

Outstanding work! It functions perfectly now.

Many thanks for the help!

**Comment by seerge** [comment]
@teodor-matei great, do you mind to run following in powershell and post an output here ? I want to see where MyASUS version stores ICC profiles

```
C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_f2eed2fae3b45a67\ASUSOptimization\AsusSplendid.exe 10 fd
```

**Comment by teodor-matei** [comment]
> @teodor-matei great, do you mind to run following in powershell and post an output here ? I want to see where MyASUS version stores ICC profiles
> 
> ```
> C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_f2eed2fae3b45a67\ASUSOptimization\AsusSplendid.exe 10 fd
> ```

[log.txt](https://github.com/seerge/g-helper/files/14516300/log.txt)

I've just uninstalled MyASUS, but if it makes a difference I can reinstall it and run the command again.

**Comment by teodor-matei** [comment]
> @teodor-matei no, it's fine. File is under `C:\ProgramData\ASUS\GameVisual\` same as for AC. Thanks
> 
> Can you try to move all ICC files from that folder somewhere (like your desktop)
> 
> And check if dimming will stil work ?
> 
> If not - can you actually install MyASUS again and see if files would reappear under GameVisual?

I can't actually find that folder, but I've managed to find ICC profiles in `C:\ProgramData\ASUS\ASUS System Control Interface\ASUSOptimization\Splendid`. I'll try moving these and report back.

**Comment by teodor-matei** [comment]
Ok. By moving those files, the dimming functionality of G-Helper was unaffected.

Reinstalling MyASUS did create 2 ICC profiles (same location, still no GameVisual folder), though I should mention I moved 6 profiles originally.

**Comment by seerge** [comment]
@teodor-matei ok, interesting :) removing ICC files on ROG devices, breaks functionality.

Now main problem is to debug from where MyASUS gets ICC profiles ...

**Comment by teodor-matei** [comment]
@seerge I can run a search for .icm files on the entire C partition if you want.

**Comment by seerge** [comment]
@seerge ye, but System32 is where it installs ICC after, for dimming AsusSplendid utility needs them locally , I assume under C:\ProgramData\ASUS\ASUS System Control Interface\ASUSOptimization\Splendid

**Comment by teodor-matei** [comment]
> @seerge ye, but System32 is where it installs ICC after, for dimming AsusSplendid utility needs them locally , I assume under C:\ProgramData\ASUS\ASUS System Control Interface\ASUSOptimization\Splendid

Yea, it would be these 2:
![image](https://github.com/seerge/g-helper/assets/93931774/1906d466-3693-47de-b5d5-cad9a0753fcc)

These were the ones I moved initially:
![image](https://github.com/seerge/g-helper/assets/93931774/37334a77-4a74-4e28-8187-813c079d0367)

G-Helper's dimming still worked without anything in that folder. Quite interesting.

**Comment by seerge** [comment]
@teodor-matei can you run
```
C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_f2eed2fae3b45a67\ASUSOptimization\AsusSplendid.exe 9 0 40 fd
```
and post a log here ?

**Comment by teodor-matei** [comment]
> @teodor-matei can you run
> 
> ```
> C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_f2eed2fae3b45a67\ASUSOptimization\AsusSplendid.exe 9 0 40 fd
> ```
> 
> and post a log here ?

[log.txt](https://github.com/seerge/g-helper/files/14516655/log.txt)

Here you go.

**Comment by seerge** [comment]
@teodor-matei yep, it uses 
```
[S_W] ColorU_InitColorU chICCPathName = C:\ProgramData\ASUS\ASUS System Control Interface\ASUSOptimization\Splendid\M3500QC_1002_834C4161.icm
```

So theoretically by deleting all ICM / ICC files under Splendid folder should break dimming

**Comment by seerge** [comment]
@teodor-matei and if you delete and run 
``
C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_f2eed2fae3b45a67\ASUSOptimization\AsusSplendid.exe 9 0 40 fd
``
(or just set dimming in g-helper) ?

**Comment by teodor-matei** [comment]
> @teodor-matei and if you delete and run `C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_f2eed2fae3b45a67\ASUSOptimization\AsusSplendid.exe 9 0 40 fd` (or just set dimming in g-helper) ?

[log.txt](https://github.com/seerge/g-helper/files/14516915/log.txt)

AsusSplendid seems to be the one creating them, so it's independent of MyASUS it seems.

**Comment by seerge** [comment]
@teodor-matei ok, cool. It seem just to copy it from installed files in windows color management

```
[S_S] [InitColorSpaceTable] [C:\ProgramData\ASUS\ASUS System Control Interface\ASUSOptimization\Splendid\M3500QC_1002_834C4161.icm] GMMP []
[S_W] [InitGlobalVariables] cmdef icm not exist (or force), try inf one !!!
[S_W] [InitGlobalVariables] inf one exist, copy.
[S_W] [InitGlobalVariables] cmdef icm - CopyFile -> [Ret: 1] [ErrCode: 0]
[S_W] [InitGlobalVariables] cmdef copied, add ACL !!!
[S_W] [LowerFilePermission] [C:\ProgramData\ASUS\ASUS System Control Interface\ASUSOptimization\Splendid\M3500QC_1002_834C4161_CMDEF.icm] File exist !!!
```

Btw AsusSplendid is very verbose in your case, on G14 2024 it just fails silently ...

**Comment by teodor-matei** [comment]
> @teodor-matei ok, cool. It seem just to copy it from installed files in windows color management
> 
> ```
> [S_S] [InitColorSpaceTable] [C:\ProgramData\ASUS\ASUS System Control Interface\ASUSOptimization\Splendid\M3500QC_1002_834C4161.icm] GMMP []
> [S_W] [InitGlobalVariables] cmdef icm not exist (or force), try inf one !!!
> [S_W] [InitGlobalVariables] inf one exist, copy.
> [S_W] [InitGlobalVariables] cmdef icm - CopyFile -> [Ret: 1] [ErrCode: 0]
> [S_W] [InitGlobalVariables] cmdef copied, add ACL !!!
> [S_W] [LowerFilePermission] [C:\ProgramData\ASUS\ASUS System Control Interface\ASUSOptimization\Splendid\M3500QC_1002_834C4161_CMDEF.icm] File exist !!!
> ```
> 
> Btw AsusSplendid is very verbose in your case, on G14 2024 it just fails silently ...

Interesting. The G14 might be using a newer version of the software I guess, but that's just how Asus software is to be honest. I'm running the fingerprint driver form a different laptop model currently, since the one for this model has been broken for months on newer versions of windows :)

**Comment by seerge** [comment]
@teodor-matei G14 uses same , as this software is just part of Asus System Control Interface

Just params for Splendid are different, on G14 it's ``19 0 [BRIGHTNESS]`` instead of ``9`` on yours. That's what I fixed for you.

Apparently method 9 is more logged than 19 :)

**Comment by d1g33k** [comment]
When I saw Vivobook Pro 15 OLED in the release notes, I thought the support would be there for my model as well (K6502VU) but that doesn't seem to be the case as the slider is not visible.

**Comment by seerge** [comment]
@d1g33k what's your model name ? I have added M3500 only

**Comment by seerge** [comment]
@d1g33k cause I'm adding by model code, issue author has different one

Try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14529720/GHelper.zip)

**Comment by d1g33k** [comment]
> @d1g33k cause I'm adding by model code, issue author has different one
> 
> Try this build
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14529720/GHelper.zip)

Works fine with the latest 0.158.0 release as well.

**Comment by AznDibs** [comment]
Hi, I have the Vivobook 16x OLED (K6604JI),  hoping I could request to add this model code to the list as well.

**Comment by savi0rr** [comment]
Hi, flicker-dimming doesn't work on Vivobook Pro 15 OLED (K6502). The slider is visible, but it does no changes.

**Comment by seerge** [comment]
@savi0rr hello, did you have flicker-free dimming in MyASUS or somewhere else ?

**Comment by savi0rr** [comment]
Yeah, i had dimming in MyAsus, but i deleted the app. I don't know how to post a log, i'm sorry, i am noob.

**Comment by seerge** [comment]
@savi0rr log is under ``%APPDATA%\GHelper`` folder.

Can you install MyASUS again and check if it still works there ?

**Comment by d1g33k** [comment]
It works fine with my K6502VU  normally. Only time the slider does nothing
is when HDR is enabled because flicker-free dimming doesn't work with HDR.
May be hiding or disabling the slider when HDR is enabled, like it happens
in the MyAsus app, would be a good addition.

**Comment by semklim** [comment]
If some one need OLED ICC profiles check my repo. I already uploaded profiles for Asus Vivobook Pro OLED.
[https://github.com/semklim/Asus-Vivobook-Pro-ICC-profiles](https://github.com/semklim/Asus-Vivobook-Pro-ICC-profiles)
