### ISSUE TITLE
AMD Display Varibright issue during Power Connecting

### ISSUE THREAD

**Issue by embracech** [seerge/g-helper#2171]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

ROG Zephyrus G14 2024 GA403UV.
Experiencing BLACKSCREEN after power replug-in when AMD Display Varibright enabled
![image](https://github.com/seerge/g-helper/assets/19525722/ab1d9e92-bef2-4a75-b789-88e5c328109d)

### How to reproduce the bug?

1.unplug power connector
2.enable AMD Display Varibright checkbox in More settings
3.plug-in power connector 
4.Screen turned in BLACK after screen flashing a white blank.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14521510/log.txt)

### Device and Model

ASUS Zephyrus G14 2024 GA403UV.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.154.0

### OS

Windows11 23H2

**Comment by seerge** [comment]
@embracech i have same device and can't reproduce anything you explain here. 

Also how is this related to G-Helper ? Varibright is AMD feature, and it's just a shortcut to the same setting inside AMD Adrenaline.
