### ISSUE TITLE
"GPU Max Operating Temp" is lowered to 75C when using custom profile (GA401WM / RTX 3060)

### ISSUE THREAD

**Issue by mntorankusu** [seerge/g-helper#2175]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I'm using a 2021 Zephyrus G14 with RTX 3060 (GA401QM). The default "Max Operating Temp" (listed when running nvidia-smi -q) for this GPU is 87C, but when using a custom profile in G-Helper, it is set to 75C. This can be changed in the ASUS GPU Tweak III app, where it is called GPU Temp Target, but this is different than what Nvidia officially calls the GPU Target Temperature. If you change the limit in GPU Tweak III, will be reset back to 75C when any GPU settings are changed in G-Helper, if the profile is changed to another one and then back to the custom one, or if the computer is restarted with that mode active.

When crossing this "Max Operating Temp" threshold, the GPU clock speed is throttled down, so it is a considerable inconvenience when gaming or using GPU-heavy applications. It would be good enough if G-Helper could avoid changing this at all when switching modes, but I would like the option to change this "Max Operating Temp" within G-Helper's GPU settings like you can in GPU Tweak III, especially if there's the possibility of setting it above the initial 87C limit.

### How to reproduce the bug?

Create a custom mode in G-Helper. Switching to that mode or changing GPU settings while in that mode will set the "Max Operating Temp" as reported by nvidia-smi -q to be 75C.

### Logs
This is a log of me switching to my custom mode, and then back to Turbo.

3/7/2024 1:42:00 PM: Mode = 2 : OK
3/7/2024 1:42:00 PM: FanCPU = 1E-30-45-64-65-64-65-64-00-2F-64-64-64-64-64-64 : OK
3/7/2024 1:42:00 PM: FanGPU = 14-24-4A-54-58-61-64-65-00-09-10-1A-46-64-64-64 : OK
3/7/2024 1:42:00 PM: GetFan Mid :00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
3/7/2024 1:42:00 PM: GET CLOCK LIMIT: 1150
3/7/2024 1:42:00 PM: GET GPU CLOCKS: 250, 0
3/7/2024 1:42:00 PM: GET GPU CLOCKS: 250, 0
3/7/2024 1:42:00 PM: GET CLOCK LIMIT: 1150
3/7/2024 1:42:00 PM: GET GPU CLOCKS: 250, 0
3/7/2024 1:42:00 PM: GET CLOCK LIMIT: 1150
3/7/2024 1:42:01 PM: PowerLimit A3 = 24 : OK
3/7/2024 1:42:01 PM: PowerLimit A0 = 24 : OK
3/7/2024 1:42:02 PM: UV: -15 OK
3/7/2024 1:42:17 PM: GetFan Mid :00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
3/7/2024 1:42:17 PM: GET GPU CLOCKS: 250, 0
3/7/2024 1:42:17 PM: GET CLOCK LIMIT: 1150
3/7/2024 1:42:20 PM: Mode = 1 : OK
3/7/2024 1:42:20 PM: FanCPU = 14-30-34-38-3C-40-44-46-0E-14-1C-22-28-2C-38-64 : OK
3/7/2024 1:42:20 PM: FanGPU = 14-30-34-38-3C-40-44-46-12-1B-1F-27-2C-2E-3A-64 : OK
3/7/2024 1:42:20 PM: GetFan Mid :00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
3/7/2024 1:42:20 PM: GET CLOCK LIMIT: 1150
3/7/2024 1:42:20 PM: GET GPU CLOCKS: 250, 0
3/7/2024 1:42:20 PM: GET GPU CLOCKS: 250, 0
3/7/2024 1:42:20 PM: GET CLOCK LIMIT: 1150
3/7/2024 1:42:20 PM: GET GPU CLOCKS: 250, 0
3/7/2024 1:42:20 PM: GET CLOCK LIMIT: 1150
3/7/2024 1:42:21 PM: PowerLimit A3 = 24 : OK
3/7/2024 1:42:21 PM: PowerLimit A0 = 24 : OK
3/7/2024 1:42:22 PM: UV: -15 OK

### Device and Model

Asus Zephyrus G14 GA401QM

### Additional information.

nvidia-smi -q output
Using "Turbo" mode
![image](https://github.com/seerge/g-helper/assets/13548364/f166bcf2-b77c-49e2-b40f-eca39d62a17c)

Using custom mode
![image](https://github.com/seerge/g-helper/assets/13548364/3e52dd60-f574-4524-b607-9189b089d951)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.154.0

### OS

Windows 11

**Comment by seerge** [comment]
@mntorankusu hello, G-Helper is not doing that. 

It's something that Asus engineers have hardcoded in BIOS and way it sets values.

From the log see that you have 2 custom modes - first is based on Silent, second is on Turbo. I would advice to use custom mode based on Turbo (either just customize turbo directly or click (+) when turbo is selected). Then it probably won't set such low temp limits :)

Also I see that you have drastically limited GPU clock (G-Helper uses nvidia-smi command under the hood for that), I would keep it unlocked 

Good luck.

**Comment by mntorankusu** [comment]
I see, that makes sense. I didn't realize that the custom mode would carry over unexposed/unsettable properties from the mode that it's based on.

In any case, the GPU Tweak III app does have the ability to set a specific value for the GPU Max Operating Temperature. Is there no way G-Helper could be made to mimic this and allow the user to set it manually?

**Comment by seerge** [comment]
@mntorankusu G-Helper can do that for majority of new models , cause asus have exposed that as their own endpoint :)

But on models that don't support it - it's not shown
