### ISSUE TITLE
Ghelper crashes on start

### ISSUE THREAD

**Issue by Dictation354** [seerge/g-helper#2177]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

源
GHelper

摘要
已停止工作

日期
‎2024/‎3/‎8 7:04

状态
已发送报告

描述
错误的应用程序路径:	C:\GHelper\GHelper.exe

问题签名
问题事件名称:	APPCRASH
应用程序名:	GHelper.exe
应用程序版本:	0.157.0.0
应用程序时间戳:	65a70000
故障模块名称:	KERNELBASE.dll
故障模块版本:	10.0.22621.3235
故障模块时间戳:	2b72307b
异常代码:	e0434352
异常偏移:	0000000000065b0c
OS 版本:	10.0.22631.2.0.0.256.161
区域设置 ID:	2052
其他信息 1:	9789
其他信息 2:	978957c298f4011e4b289079561ecfeb
其他信息 3:	c244
其他信息 4:	c244a896fae562246fe144b004ef2977

关于该问题的额外信息
存储段 ID:	6dc5aae289b55569325fbbe8669df88f (1323983422298650767)

### How to reproduce the bug?

Just try opening Ghelper v0.157

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14531177/log.txt)

### Device and Model

Asus Zephyrus M16 GU603HM

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.147

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Dictation354 hello, can you find a crashlog from EventViewer mentioning GHelper.exe but w/o KERNELBASE (there is usually 2 logs coming close to each other) and post here ? It's impossible to see a reason here

**Comment by seerge** [comment]
P.S. I have re-released 0.157 with a mini-fix, when app would crash if you don't have GameVisual folder. So just re-download it again https://github.com/seerge/g-helper/releases/tag/v0.157

**Comment by Dictation354** [comment]
> P.S. I have re-released 0.157 with a mini-fix, when app would crash if you don't have GameVisual folder. So just re-download it again https://github.com/seerge/g-helper/releases/tag/v0.157

Thank you very much. It now starts properly.
