### ISSUE TITLE
The M4 button pops up to download Armoury Crate.Keyboard light color cannot be adjusted

### ISSUE THREAD

**Issue by javazwz123** [seerge/g-helper#2179]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I am the latest G14 (2024), thank you for the updated version to support dimming, my question is.
1. Press the M4 button and the recommended download pop-up window will come out. G-helper will open normally, but the experience will be affected.
2. It is useless to adjust the light color of the notebook. I have given the highest priority to Armoury Crate in the dynamic light effect. I don't know why.

### How to reproduce the bug?

1. Press the M4 button.
2. Modify the keyboard light color

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14535731/log.txt)

### Device and Model

Zephyrus G14 GA403UV

### Additional information.

![微信截图_20240308163142](https://github.com/seerge/g-helper/assets/16428277/24a6a323-ed99-4c39-8561-bb5ceefd89c4)
![screenshot-20240308-161918](https://github.com/seerge/g-helper/assets/16428277/21ddc49b-5632-4181-8330-d211c8b34b74)

### Armoury Crate

Uninstalled

### Asus Services

8

### Version

0.157.0

### OS

Windows 11 23H2

**Comment by javazwz123** [comment]
M4 button problem I solved, the original is not completely uninstalled ArmouryCrate, there is an ASUSACCI folder in the system32 folder, there are some software, delete all of it, this will not be a problem, right?
The problem of keyboard lighting is still unsolved
![image](https://github.com/seerge/g-helper/assets/16428277/a8a9e777-285e-40db-912e-1ee2b776b1a8)

**Comment by seerge** [comment]
https://github.com/seerge/g-helper/wiki/FAQ
