### ISSUE TITLE
Plugged in / on battery actions delay

### ISSUE THREAD

**Issue by Maneeha1234SL** [seerge/g-helper#2181]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Plugged in / on battery actions delay
When you plug in or unplug your device it would set last remembered performance mode, disable or enable dPGU if you have Optimized mode on and change screen refresh rate if you have display mode set to Auto

If you have unstable power supply, or want to delay this automated actions, you can set a custom delay for it. Delay value is in milliseconds, so 1000 = 1 second.

### How to reproduce the bug?

After I set this up and save, ghelper deletes it.
This value should be moved to 20s.
How to solve this problem?

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14541451/log.txt)
[config.json](https://github.com/seerge/g-helper/files/14541452/config.json)

### Device and Model

ASUS ZEPHYRUS G15 GA503RM

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.158.0

### OS

windows 11 23h2

**Comment by seerge** [comment]
@Maneeha1234SL you need to quit app, add

```
"charger_delay" : 20000,
```

to config (maintaining json structure, so just add it as a first config line) and save it.

And start app over

Config is deleted, cause you don't maintain correct structure, so app can't read it and recreates from scratch.

**Comment by seerge** [comment]
P.S. I don't advice to set a delay for so long :) something like 3-5 seconds should be enough

**Comment by seerge** [comment]
@Maneeha1234SL it's not crashing. How it works - it just pauses whole process for X seconds.

It's intentional, as whole unplug chain of events (like disabling GPU / setting new power mode / setting new refresh rate) are carefully timed. And if you would start clicking something in UI in-between that, it would cause something wrong. 

That's why I don't advice to set delay to 20 seconds. Or if you do - just accept that app UI will be locked for you during that time.
