### ISSUE TITLE
Fan control won't work

### ISSUE THREAD

**Issue by jaydenchan1027** [seerge/g-helper#2184]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I can't control the fan speed, the fan speed is default speed (no control like armoury crate or ghelper).  

### How to reproduce the bug?

....

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14544394/log.txt)

### Device and Model

G15 GA503RS 6800hs 3080 laptop

### Armoury Crate

Uninstalled

### Asus Services

1

### Version

0.154.0

### OS

Windows 10 22H2

**Comment by seerge** [comment]
@jaydenchan1027 you clearly did not read the FAQ 
https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds

**Comment by seerge** [comment]
@jaydenchan1027 Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks
