### ISSUE TITLE
Ghelper Fails to Retain Visual Mode Settings on Restart

### ISSUE THREAD

**Issue by Maneeha1234SL** [seerge/g-helper#2185]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The specific visual mode "Cinema" is used as an example; however, the issue applies to all visual modes supported by Ghelper.

When using Ghelper to set the visual mode to "Cinema" and then restarting the PC, Ghelper incorrectly resets the visual mode to the default value instead of retaining the chosen "Cinema" mode. This behavior causes inconvenience as users have to manually re-select their preferred visual mode each time they restart their PC.

### How to reproduce the bug?

1.Open Ghelper.
2.Set the visual mode to "Cinema."
3.Restart the PC.
4.Upon reboot, observe that Ghelper displays the visual mode as "Cinema," but the actual mode is reset to the default value.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14545087/log.txt)
[config.json](https://github.com/seerge/g-helper/files/14545088/config.json)

### Device and Model

ASUS ZEPHYRUS G15 GA503RM

### Additional information.

Impact:
This issue disrupts user experience and workflow efficiency. Users relying on Ghelper for visual mode settings may find it frustrating to repeatedly reset their preferred mode after every PC reboot.

Resolution:
Investigate the cause of the failure to retain visual mode settings upon PC restart. Implement a fix to ensure that Ghelper accurately preserves the selected visual mode across system reboots, enhancing user satisfaction and usability.

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

v0.158

### OS

windows 11 23h2

**Comment by Kikimahe** [comment]
Hi,

Unless I'm mistaken, Ghelper doesn't use Visual Mode.
It is therefore not Ghelper which resets your Visual Mode settings.

You can check it by disabling Ghelper on startup.

**Comment by Kikimahe** [comment]
Yes I saw it after writing my message, which I deleted.

Sorry. :)

**Comment by seerge** [comment]
@Maneeha1234SL hello,

I actually can't reproduce it on my G14 2022 and 2024

Visual mode is set on the level of color profile, so unless something else is overriding it - it should be retained on reboot as well.

But I have added a command to set last used mode on app start (with the exception of Default), as I don't want to force any Visual mode for people who don't want it.

Try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14545984/GHelper.zip)

**Comment by seerge** [comment]
@Maneeha1234SL i can add that eventually

**Comment by seerge** [comment]
@Maneeha1234SL added FN-V
[GHelper.zip](https://github.com/seerge/g-helper/files/14561775/GHelper.zip)
