### ISSUE TITLE
A little advice

### ISSUE THREAD

**Issue by KizzWang** [seerge/g-helper#2186]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hello, I'm glad to see the new features (gamevisual)added. I have a few tips for you to consider. Firstly, add color temperature adjustment function for ghelp just like gamevisual in AC. If this function can be implemented, AC can be completely replaced by ghelper. Secondly, Change the path of the gamevisual folder read by ghelper. Put the "gamevisual" folder in the same directory as the ghelper files. This way, the "gamevisual" folder will not be cleared when the system is reinstalled. 

### Describe the solution you'd like

Above are my two suggestions, I hope you can consider, thank you.

### Device and Model

G14 2023 GA402XV

**Comment by seerge** [comment]
@KizzWang color temp can be added somewhere in the future, as for gamevisual folder - i can't really change that, as currently app relies on a small utility coming with Asus System Control Interface called ``AsusSplendid``.  And this utility expects color profiles to be in appropriate folder.

**Comment by KizzWang** [comment]
Ok, thanks for reply. I have understood. thank you for building such a good project

**Comment by seerge** [comment]
@KizzWang  this build should allow you to set color temperature next to visual mode
[GHelper.zip](https://github.com/seerge/g-helper/files/14546536/GHelper.zip)
