### ISSUE TITLE
Some malfunctions on G16 AIR 2024

### ISSUE THREAD

**Issue by lihe404** [seerge/g-helper#2196]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

1. The custom fan control does not work with G16 AIR 2024.
2. Under the auto switch mode, the screen would freeze for several seconds when switching between dGPU and iGPU.

### How to reproduce the bug?

1. Go to the fan control page and enable custom fan control.  The fan speed does not change.
2. Play a game requiring dGPU could reproduce the problem.

### Logs

Could not get the log for a moment.

### Device and Model

Asus Zephyrus G16 (2024) GU605MV

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.158

### OS

Windows 11 23H2

**Comment by seerge** [comment]
>  I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

**Comment by lihe404** [comment]
here is the log
[log.txt](https://github.com/seerge/g-helper/files/14558005/log.txt)

**Comment by seerge** [comment]
@lihe404 

App sets fan curves according to the log, and they are accepted
```
2024/3/11 14:43:59: FanCPU = 1E-3A-3D-40-48-4D-51-62-00-08-11-16-22-29-30-45 : OK
2024/3/11 14:43:59: FanGPU = 1E-3A-3D-40-48-4D-51-62-00-0C-16-1D-26-2D-34-4A : OK
2024/3/11 14:43:59: FanMid = 1E-28-32-3C-46-50-5A-64-00-05-09-0F-15-1D-23-28 : OK
```

Rest is up to BIOS, so to treat fans. 
https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds

You can check if Manual Fan curves work in AC in a first place for your device 

If they do - you can replicate that by setting Turbo Mode in G-Helper with custom fan curves and applying power limits next to them. As this is what AC's Manual mode dos (sets Turbo with all possible settings applied)

---

As for setting Eco mode, according to the log it also happens 

For example

```
2024/3/11 14:30:49: Running eco command 1
2024/3/11 14:30:50: GPUEco = 1 : OK
2024/3/11 14:30:50: Eco flag : 1
2024/3/11 14:30:50: Mux flag : 1
```

Please keep in mind, if you have Nvidia Display Mode (in NV Control Panel) set to "Nvidia GPU only" (and it's being used to drive display), upon disabling GPU display will go blank. This is normal.

To avoid that - **you can set Display Mode to Optimus.**
