### ISSUE TITLE
[Bug] Zenbook S 13 OLED - no OLED and Visual Mode settings appearing

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#2197]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi there, I'm using the latest version, 0.159. It doesn't show Visual Mode and OLED/dimming stuff.

### How to reproduce the bug?

1. Run the app.
2. Check its main window and settings:
![image](https://github.com/seerge/g-helper/assets/8934421/06b8de94-d0db-4ee6-903d-2a70898e535f)

### Logs

```
11.03.2024 15:28:31: ------------
11.03.2024 15:28:31: App launched: Zenbook UM5302LA_UM5302LA :0.159.0.0uk-UA
11.03.2024 15:28:31: Matrix control device was not found on your machine.
11.03.2024 15:28:32: C:\ProgramData\ASUS\GameVisual doesn't exit
11.03.2024 15:28:32: dGPU not found
11.03.2024 15:28:33: CPU: 9 - AMD Ryzen 7 7840U w/ Radeon 780M Graphics       - AMD64 Family 25 Model 116 Stepping 1
11.03.2024 15:28:33: AutoSetting for Offline
11.03.2024 15:28:33: BatteryLimit = 80 : OK
11.03.2024 15:28:33: BatteryLimit = 80 : OK
11.03.2024 15:28:33: FnLock = 1 : 0
11.03.2024 15:28:33: Eco flag : -65536
11.03.2024 15:28:33: Mux flag : -65536
11.03.2024 15:28:33: \\?\DISPLAY#SDC4172#5&16422b31&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
11.03.2024 15:28:33: \\?\DISPLAY#SDC4172#5&16422b31&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
11.03.2024 15:28:33: Mode = 0 : 0
11.03.2024 15:28:33: VivoMode = 0 : 0
11.03.2024 15:28:33: TUF_KB = 13566397 : 0
11.03.2024 15:28:33: AuraMode: AuraStatic
11.03.2024 15:28:33: TUF RGB = B4-00-FF-FF-FF-EB : 0
11.03.2024 15:28:33: TUF RGB = B4-00-FF-FF-FF-EB : 0
11.03.2024 15:28:33: Monitor Power On
11.03.2024 15:28:33: Lid Open
11.03.2024 15:28:33: TUF Brightness = 129 : OK
11.03.2024 15:28:34: TUF Brightness = 129 : OK
11.03.2024 15:28:43: Input device not found
```

### Device and Model

ASUS Zenbook S 13 OLED UM5302LA-LV152

### Armoury Crate

Never installed

### Asus Services

0

### Version

0.159

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@ke1ne hello, I have added your model to the list of OLEDs

[GHelper.zip](https://github.com/seerge/g-helper/files/14559594/GHelper.zip)

So dimming should be available, as for Visual Modes - they generally seem to work only for ROG / TUF models that have ``GameVisual`` folder. You can try to set them, and report if they have any effects

And attach a log please, thanks

**Comment by seerge** [comment]
@ke1ne does the dimming work ?

I see that it still don't show visual modes, try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14562703/GHelper.zip)

**Comment by ke1ne** [comment]
> @ke1ne does the dimming work ?
> 
> I see that it still doesn’t show visual modes, try this build
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14562703/GHelper.zip)

The Dimming is working (becomes brighter/darker).
And Visual Modes are appearing in UI but with no reaction to switches. So, as you said, it seems to be focused on ROG/TUF; I didn't know that before.

[log.txt](https://github.com/seerge/g-helper/files/14562828/log.txt)

**Comment by seerge** [comment]
@ke1ne ok, did you have any visual modes in myasus (or what zenbook uses for control by default)?

Cause if not, it could be that it's not possible as even asus utility that sets colors says that color profile is missing
```
11.03.2024 20:08:42: C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_f2eed2fae3b45a67\ASUSOptimization\AsusSplendid.exe 21 0 50
11.03.2024 20:08:42: !! ICM file not exist !!
```

You can try to manually run it, and try different parameters, mb something will work
```
C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_f2eed2fae3b45a67\ASUSOptimization\AsusSplendid.exe 1
```

(replace 1 with 2,3, etc)

**Comment by seerge** [comment]
@ke1ne did you had a chance to check if "AsusSplendid" with different params does something on your device ?

**Comment by ke1ne** [comment]
> @ke1ne did you had a chance to check if "AsusSplendid" with different params does something on your device ?

Not yet, will check later today.

**Comment by ke1ne** [comment]
Sorry, was too busy. In general, some modes did nothing, and some drop a lot of text with no visual changes.
However, Splendid in MyAsus did visual changes.

**Comment by seerge** [comment]
@ke1ne oke, thanks for checking.

If you want, you can repeat steps I have asked from other user in this thread https://github.com/seerge/g-helper/issues/2168#issuecomment-1981832945 

And post results from ProcMon here (it could be that Splendid just needs other params)

**Comment by ke1ne** [comment]
> @ke1ne oke, thanks for checking.
> 
> If you want, you can repeat steps I have asked from other user in this thread [#2168 (comment)](https://github.com/seerge/g-helper/issues/2168#issuecomment-1981832945)
> 
> But set MyASUS to different visual modes there
> 
> And post results from ProcMon here (it could be that Splendid just needs other params)

Yes, I will try this too.

P.S. BTW, after installation of MyAsus, my fans became always active for no reason, in all modes, with boost disabled.

**Comment by ke1ne** [comment]
@seerge Hi, here are events from ProcMon. I just switched different Splendid and dimming values to make some log records. Is it OK?
[Logfile.CSV](https://github.com/seerge/g-helper/files/14663332/Logfile.CSV)

**Comment by seerge** [comment]
@ke1ne great, thanks

I see that it still calls splendid but with different params, like

C:\Windows\System32\DriverStore\FileRepository\asussci2.inf_amd64_f2eed2fae3b45a67\ASUSOptimization\AsusSplendid.exe 6 0 50

6 - is a visual mode here, and 50 (default) color temp

Can you record / test which param is responsible for each mode? 

Like 6 - is Vivid (for example), etc?

Then I can add this to the app, as on ROG/TUF devices those parameters are different

**Comment by ke1ne** [comment]
> @ke1ne your device doesn’t report fan speed or cpu temperature unfortunately via standard endpoints :( Can you see them somewhere else in myasus?

![image](https://github.com/seerge/g-helper/assets/8934421/69adfe50-0636-4df0-8164-cb772fe4975d)

**Comment by seerge** [comment]
@ke1ne amazing.

Can you quit g-helper, add following line to beginning of config.json (don’t forget comma)
```
“debug”: 1,
```

Run app, go to extra and click on Zoom-glass icon there while your fans are working and post that scan results here?

**Comment by ke1ne** [comment]
> @ke1ne amazing.
> 
> Can you quit g-helper, add following line to beginning of config.json (don’t forget comma)
> 
> ```
> “debug”: 1,
> ```
> 
> Run app, go to extra and click on Zoom-glass icon there while your fans are working and post that scan results here?

```
Scan started 21.03.2024 20:22:37
00040017: 0001 (1)
00050021: 348001 (3440641)
00050042: 0036 (54)
00060079: 0001 (1)
00100023: 0000 (0)
00110019: 20000 (131072)
00120057: 880000 (8912896)
---------------------
```

**Comment by seerge** [comment]
@ke1ne ok, does 00050042 change with time? Cause it looks like CPU temp

As for fan speed, were fans on during this scan? try to ramp them up faster and run a scan again

**Comment by ke1ne** [comment]
> @ke1ne ok, does 00050042 change with time? Cause it looks like CPU temp
> 
> As for fan speed, were fans on during this scan? try to ramp them up faster and run a scan again

A bit higher temperature and speed:
```
Scan started 21.03.2024 20:29:24
00040017: 0001 (1)
00050021: 348001 (3440641)
00050042: 0036 (54)
00060079: 0001 (1)
00100023: 0000 (0)
00110019: 20002 (131074)
00120057: 880000 (8912896)
---------------------
```

**Comment by seerge** [comment]
@ke1ne ok, thanks. Looks like nothing has changed. Looks like it gets measurements somehow else…

**Comment by ke1ne** [comment]
Another try, with CPU test running:
```
Scan started 21.03.2024 20:33:54
00040017: 0001 (1)
00050021: 348001 (3440641)
00050042: 0036 (54)
00060079: 0001 (1)
00100023: 0000 (0)
00110019: 20000 (131072)
00120057: 880000 (8912896)
---------------------
```

**Comment by seerge** [comment]
@ke1ne can you check this build and tell if it shows CPU temp and fan speed ?

[GHelper.zip](https://github.com/seerge/g-helper/files/14733398/GHelper.zip)

**Comment by ke1ne** [comment]
> @ke1ne can you check this build and tell if it shows CPU temp and fan speed ?
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14733398/GHelper.zip)

Yeah! I confirm, it works.

**Comment by ke1ne** [comment]
As for color combinations, I'm still working on it. It's a bit crazy: same mixes are giving a bit different commands to run.
