### ISSUE TITLE
Seeking Assistance for CPU Undervolting Project

### ISSUE THREAD

**Issue by xyn0o** [seerge/g-helper#2198]
Dear Seerge,

I hope this message finds you well. My name is Samy Ait Djoudi, and I am a third-year engineering student based in France. Currently, I am working on a project that involves automating CPU undervolting.

Our project aims to implement undervolting for AMD CPUs, utilizing the FFT algorithm and the Chudnovsky formula to calculate pi as a stress test. Initially, we explored using software like UXTU but encountered difficulties. Subsequently, we turned to tools such as the SMU Debug Tool and RyzenAdjustApi; however, we have reached a deadlock in our progress.

Given your expertise and experience with developing gHelper, we are reaching out in the hopes that you might provide us with some guidance or assistance. Specifically, we are seeking advice on how to effectively control undervolting parameters through APIs, akin to the functionality you have developed in gHelper.

We admire the work you have done with gHelper and believe that your insights could significantly aid us in overcoming the obstacles we are currently facing. Your assistance would not only be immensely valuable to our project but also deeply appreciated by our team.

Thank you very much for considering our request. We eagerly await your response and hope to learn from your expertise.

Warm regards,

Samy Ait Djoudi

**Comment by seerge** [comment]
@xyn0o hello, thanks for your message.

For AMD Undervolting G-Helper uses UXTU's library under the hood https://github.com/seerge/g-helper?tab=readme-ov-file#libraries-and-projects-used - so it's same SMU commands via Winring0 driver as UXTU does.

I'm afraid if you have encountered difficulties with whatever you are trying to do with UXTU's approach, won't be different here :)

**Comment by xyn0o** [comment]
Thanks for your response. We'll look into it further.

Best regards

**Comment by seerge** [comment]
Great, good luck with that
