### ISSUE TITLE
Power Scheme issue

### ISSUE THREAD

**Issue by manciuszz** [seerge/g-helper#220]
I've installed a fresh Windows 11 build on **ASUS ROG SCAR 17 G732LXS**, so the system is clean of ASUS bloatware. After installing 'ASUS System Control Interface v3' AND DELETING **ALL** the unnecessary services and drivers except the 'ATKWMIACPI Driver'. I've noticed an issue. The 0.49 version of the app works fine, the fans do what you tell them to, however the Power Schemes are not getting applied. 

After glancing at the code, I've noticed where the issue lies - my system doesn't have these power plans with these GUIDS. Furthermore, I've exported the available **Silent**, **Performance** and **Turbo** power plans from ASUS Armoury Crate on my other OS, however their GUIDS are always different when I import them back...

```C#
public static void SetPowerScheme(int mode)
    {
        switch (mode)
        {
            case 0: // balanced
                PowerSetActiveOverlayScheme(new Guid("00000000-0000-0000-0000-000000000000"));
                break;
            case 1: // turbo
                PowerSetActiveOverlayScheme(new Guid("ded574b5-45a0-4f42-8737-46345c09c238"));
                break;
            case 2: //silent
                PowerSetActiveOverlayScheme(new Guid("961cc777-2547-4f9d-8174-7d86181b8a7a"));
                break;
        }
    }
```

I assume there's an ASUS service (probably ASUSOptimization.exe) which handles these? or maybe they are default system profiles and my Windows 11 build got gimped or something after messing with it. Regardless, I think the app needs a more robust way of handling power schemes other than just simply hit-or-miss solution like what we have now.

**Comment by seerge** [comment]
@manciuszz Hello, it's not a power plans, it's so called "power modes" that should exist in all windows10/11 . This is exactly why app changes this setting and not power plan (as by default in win 11 it will be only one "Balanced" plan)

They look like this

![Screenshot 2023-04-11 171054](https://user-images.githubusercontent.com/5920850/231207717-0f853189-b53c-43b8-9f0f-6ef5a45ae583.png)

You can change app modes in real time and see if this setting changes in your system

**Comment by manciuszz** [comment]
Ahh, I see. That seems to be indeed the case! However, does ASUS Armoury Crate really work like that? I see it creating and using it's own predefined power plans - Silent, Performance and Turbo. 

Furthermore, these power modes behave extra weird on my system, probably due to it being a custom Windows build.

Here's a video showing what I mean.
https://user-images.githubusercontent.com/2539661/231211745-48942f1e-dea0-41cd-af4b-222ddf06f3d6.mp4

**Comment by seerge** [comment]
@manciuszz armoury works differently, it installs 3 own power plans and switches them. But since g-helper is designed to work without armoury, it doesn't use that. Plus - those plans can break laptop sleep sometimes. So it's better to use power modes.

From your video - it looks like modes don't switch, it could be cause you have some custom power plan? Try to reset it to defaults to see if it's better.

As for scheme ids - they are from windows itself, and should exist on all systems. Check https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/customize-power-slider

**Comment by manciuszz** [comment]
I've completely reset all power plans now.
![image](https://user-images.githubusercontent.com/2539661/231214203-a9237fe1-4854-4314-b2aa-19272e9d64fa.png)

Which also sort of disabled the ability to use Power Modes:
![image](https://user-images.githubusercontent.com/2539661/231214851-0501a728-b71a-44d2-b267-492c18afd1ad.png)
![image](https://user-images.githubusercontent.com/2539661/231214758-ab85d2cf-a314-479c-bdc4-1392fdea371f.png)

powercfg -list displays:
```
Existing Power Schemes (* Active)
-----------------------------------
Power Scheme GUID: 381b4222-f694-41f0-9685-ff5bb260df2e  (Balanced) *
```
So I assume it's because the GUID is not '00000000-0000-0000-0000-000000000000'

**Comment by seerge** [comment]
Ok, but from your screenshot with available overlays i see that you actually have needed ids 

```
ded574b5-45a0-4f42-8737-46345c09c238
961cc777-2547-4f9d-8174-7d86181b8a7a
```

and 0000 - is just a default scheme (it also exists in any system)

**Comment by manciuszz** [comment]
hmm, something seems very broken with power modes in this windows build.
<video src='https://user-images.githubusercontent.com/2539661/231219498-b05d0947-3f08-4a17-8d8e-48a8726aa0d3.mp4' width=480/>

**Comment by seerge** [comment]
May be your custom build has something disabled? Anyway I can't help here, as I explained - app sets one of predefined power modes that supposed to exist in every windows.

**Comment by manciuszz** [comment]
Hmm, yea, it has to be something on the custom build side, what it is, it's going to be difficult to debug. 

However, in this particular case, it'd be nice if a user could configure and use their own power plans instead of power modes. Main reason being is that with power plans in general, a (power) user has more control over their power management. So 'Silent' button could apply the silent fan profile, but also 'Silent' power plan from ASUS Armoury Crate and etc...

**Comment by seerge** [comment]
Well, i can add it as a parameter in app config, so you can enter custom plan id there (as "power user")

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11202947/GHelper.zip)

You can try this build

In config.json (under %appdata/ghelper) you can manually add custom power plan GUID (it can be either "real" power plan that can be switched or "overlay" power plan like the ones g-helper sets by default)

Format is following : `` "scheme_<mode>" : "GUID"  ``

Where **mode = 0 (balanced), 1 (turbo), 2 (silent)**

```
  "scheme_0": "2ac1d0e0-17a7-44ed-8091-d88ef75a4eb0",
  "scheme_1": "381b4222-f694-41f0-9685-ff5bb260df2e",
```

**Comment by manciuszz** [comment]
Awesome. Works as intended.
<video src='https://user-images.githubusercontent.com/2539661/231236773-72aed32f-381e-491f-a5a2-6832273d6b9f.mp4' width=480 />
