### ISSUE TITLE
ZIP Archive name should contain version identifier

### ISSUE THREAD

**Issue by tendan** [seerge/g-helper#2200]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I don't know if it's a problem, but when you're updating GHelper, it downloads GHelper.zip and my operating system appends incrementing number to it and there's no information about software version inside it

### Describe the solution you'd like

Name of archive like "GHelper-0.158.0.zip" according to latest (as today) release

### Describe alternatives you've considered

Eventually names like "GHelper-0_158_0.zip" or README file with version specified.

### Device and Model

Asus ROG Zephyrus G15 GA503RM

**Comment by seerge** [comment]
@tendan hello, it will break autoupdate mechanism in the app and also lots of the links on github :) So sorry, but I can't afford doing that.

Why do you store old version anyway ? They are always available on on releases section of github anyway ? 

Closing as not planned. Sorry
