### ISSUE TITLE
[Request] Add OLED features support for Vivobook 16x OLED (K6604JI)

### ISSUE THREAD

**Issue by AznDibs** [seerge/g-helper#2201]
Hi, I have the Vivobook 16x OLED (K6604JI), I'd like to request for this model code to be added to the list of supported OLED devices.

[A recently closed issue ](https://github.com/seerge/g-helper/issues/2168) seems to have added support to several closely-related Vivobook models, hoping it should be a quick and straightforward addition.

**Comment by seerge** [comment]
@AznDibs hello, try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14565362/GHelper.zip)

**Comment by AznDibs** [comment]
Flicker-free dimming works perfectly, thank you!

![image](https://github.com/seerge/g-helper/assets/13837332/ada1e946-ac1f-4a62-bb18-c65d4d95c53b)

**Comment by seerge** [comment]
Great
