### ISSUE TITLE
Please add an option to change the gHelper icon

### ISSUE THREAD

**Issue by Rick-1242** [seerge/g-helper#2203]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

For those who want a B&W or color matched experience on their machine.

### Describe the solution you'd like

It would be nice if you could change the taskbar icon to a B&W option or even better add your own icon.
This would be great and Helper would blend in seamlessly with the windows icons like this:

![Screenshot 2024-03-12 100658-modified](https://github.com/seerge/g-helper/assets/71984096/f1d87940-f85c-4b24-ae10-2ed0c095d787)

### Device and Model

GA402RK

**Comment by seerge** [comment]
@Rick-1242 hello.

G-Helper icon changes it's color based on current GPU mode, Green for Eco, Blue for Standard and Red for Ultimate.

Also it's part of app's branding - same icon on webpage, etc.

So I'm not a big fan of changing that.

**Comment by seerge** [comment]
@Rick-1242 @goranovs try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/14579585/GHelper.zip)

**Comment by seerge** [comment]
@goranovs hello, actually app is checking for OS theme (it also recolors main window based on that). Do you use some unorthodox theming ?

**Comment by goranovs** [comment]
Hi, I use the "custom" option and my taskbar is dark while the rest of the UI is white.  It's like Windows 10 theme, but I do not use any external tools for the theme, just pure windows customization.

![image](https://github.com/seerge/g-helper/assets/2466340/f6bd1864-bd19-4985-9d8e-0074f85edc4c)

**Comment by seerge** [comment]
@goranovs ok, try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14586605/GHelper.zip)

**Comment by goranovs** [comment]
This one works, thanks!

![image](https://github.com/seerge/g-helper/assets/2466340/8d12404d-ba5e-4368-bbf5-c1ab0de4011e)

**Comment by seerge** [comment]
Live in https://github.com/seerge/g-helper/releases/tag/v0.160
