### ISSUE TITLE
g14 2023 4060 model Don't working power limit

### ISSUE THREAD

**Issue by SION001122** [seerge/g-helper#2204]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

title same
g14 2023 4060 model Don't working power limit

### How to reproduce the bug?

reference to my upload image

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14570356/log.txt)

### Device and Model

g14 2023 4060

### Additional information.

![image](https://github.com/seerge/g-helper/assets/163120715/f96769b9-9a3e-4498-a8fa-6f126641fe7f)
![image](https://github.com/seerge/g-helper/assets/163120715/b5d7f655-3c2a-47cc-a5cb-cf6450b4dfe0)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.158.0

### OS

windows 11 24H2

**Comment by seerge** [comment]
@SION001122 hello, how do you check that it's "not working" ?

**Comment by SION001122** [comment]
> @SION001122 hello, how do you check that it's "not working" ?

battery status Application & helper w value is my setting limit to over

**Comment by seerge** [comment]
@SION001122 battery drain can be higher than your CPU power limit :) It's normal.

Next to your CPU you have screen, memory, SSD and lots of other things in your computer that also consume power.

There is nothing to fix, you compare different things.

**Comment by SION001122** [comment]
> @SION001122 battery drain can be higher than your CPU power limit :) It's normal.
> 
> Next to your CPU you have screen, memory, SSD and lots of other things in your computer that also consume power.
> 
> There is nothing to fix, you compare different things.

thanks
