### ISSUE TITLE
Some GameVisual controls are missing on G533ZW 2022 model

### ISSUE THREAD

**Issue by Kowken** [seerge/g-helper#2205]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![image](https://github.com/seerge/g-helper/assets/78725741/2379db8f-dcff-48de-88bf-63afe1595810)
![image](https://github.com/seerge/g-helper/assets/78725741/048fb939-8532-4e82-a2c2-aabeb5de67a6)
![image](https://github.com/seerge/g-helper/assets/78725741/b9abc8b7-8b45-4c81-9168-f6900fd26d64)

I am missing the Color temperature (see picture 1 compared to picture 2) feature as well as the slider (see picture 3), although I'm not sure if the latter is only available for newer models.
The color profile features are working though.

### How to reproduce the bug?

1. Open Ghelper
2. See missing features

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14571774/log.txt)

### Device and Model

ASUS ROG STRIX SCAR 2022 G533ZW AS94

### Armoury Crate

Never installed

### Asus Services

None

### Version

0.158

### OS

Windows 11 23H2 22631.3155 Windows Feature Experience Pack 1000.22684.1000.0

**Comment by seerge** [comment]
@Kowken hello, as description says - if you don't have color profiles, visual modes are not available (and therefore not visible)

Please update to https://github.com/seerge/g-helper/releases/tag/v0.159 that can download correct color profiles for your model ;)

**Comment by Kowken** [comment]
> @Kowken hello, as description says - if you don't have color profiles, visual modes are not available (and therefore not visible)
> 
> 
> 
> Please update to https://github.com/seerge/g-helper/releases/tag/v0.159 that can download correct color profiles for your model ;)

Hi ! Are color profiles different from the profiles from GameVisual (FPS, Racing, etc.) ?
If they are the same, then everything works for me but the slider (Flicker-free/dimming) is missing (I don't know what it does though).

**Comment by seerge** [comment]
@Kowken 

GameVisual (from AC) uses same color profile for all modes, but it modifies it each time based on the selected mode.

But it has to be your correct color profile, that's why 0.159 will download it for you 
I just checked, and your model is in the list, so it will work.

Good luck.

Closing as it should work already

**Comment by Kowken** [comment]
Sorry for the late reply. Latest pre-release indeed fixed it. Regarding color profiles, my screen was replaced by a sidegrade due to a faulty monitor (happens a lot according to the ASUS technicians I was in touch with) and there is no compatible one in the list of file GHelper downloaded. 

Here is the screen reference: https://www.blisscomputers.net/asus-rog-strix-g15-g513qx-15-full-hd-1920x1080-sharp-lq156m1jw25-shp152c-lcd-screen-278813/

I happen to have a copy of the ICM profile they specifically made for me so I'll send it in case it may be useful.
[104D152C.zip](https://github.com/seerge/g-helper/files/14577047/104D152C.zip)

**Comment by seerge** [comment]
Ok, cool :) but obviously app can't handle such exotic cases. You can either rely on ASUS profiles, or replace them with yours (but you will have to rename yours into same name as asus one had if you want it to be picked up
