### ISSUE TITLE
color temperature color gamut profile and game visual

### ISSUE THREAD

**Issue by AayushV12** [seerge/g-helper#2206]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

1.could u please add color temperature numerical values along with the warmest warmer warm neutral cold colder coldest.
2.color gamut profile for me shous dcip3 and native.so if i select one do i have to add icc or icm profile in color management tab or it does that by itself.
3.when i downloaded game visual profiles it downloads multiple file in the game visual folder but does it apply them in windows color management by itself or through nvidia control panel.

### Describe the solution you'd like

1.could u please add color temperature numerical values along with the warmest warmer warm neutral cold colder coldest.
2.color gamut profile for me shous dcip3 and native.so if i select one do i have to add icc or icm profile in color management tab or it does that by itself.
3.when i downloaded game visual profiles it downloads multiple file in the game visual folder but does it apply them in windows color management by itself or through nvidia control panel.

### Device and Model

asus rog strix g15 g513rc hn062w

**Comment by seerge** [comment]
@AayushV12 hello,

> 1.could u please add color temperature numerical values along with the warmest warmer warm neutral cold colder coldest.

I don't know temperature values for those unfortunately. Under the hood it utilizes AsusSplendid utility from Asus System Control Interface driver, that sets color modes and color temps. Value is set in a range from 0 to 100, while 50 is default / neutral 

I have intentionally called them like this, as **it's not precise setting** anyway

>2.color gamut profile for me shous dcip3 and native.so if i select one do i have to add icc or icm profile in color management tab or it does that by itself.

When you select them in app **AsusSplendid would set them automatically in windows**, you don't need to do that manually

>3.when i downloaded game visual profiles it downloads multiple file in the game visual folder but does it apply them in windows color management by itself or through nvidia control panel.

Package contains all possible color profiles for your model (some models can have different panels). **AsusSplendid would pick and set correct color profile automatically** from the package for your specific panel  (it can read it)

**Comment by seerge** [comment]
@AayushV12 most probably not :) it depends on what profiles asus provides for your device
