### ISSUE TITLE
UI can not display collectly.

### ISSUE THREAD

**Issue by Diamondoard** [seerge/g-helper#2210]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

After version 1.5.7 which added _Visual modes and Gamut Modes_, The Top of the G-helper panel is floating above the screen, 
I can't rescale the G-gelper panel to solve the problem, restarting windows or changing DPI settings seems didn't work. 
![Work fine in 1 5 6](https://github.com/seerge/g-helper/assets/105638233/17c8579a-ca5e-4eec-a569-1c991ae2a634)
**Working well in ver 1.5.6.↑↑↑**
![goes wrong in 1 5 8](https://github.com/seerge/g-helper/assets/105638233/599335c8-6892-405f-ae19-60ec8f06f39f)
**Going wrong in ver 1.5.8.↑↑↑**
### How to reproduce the bug?

Update to 1.5.7 or later version.
Connect to a second screen with 1920x1080P resolution.
Open the G-helper panel.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14581782/log.txt)

### Device and Model

Asus rog zephyrus G14 GA402RK

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

1.5.7 or later

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Diamondoard hello, you have quite exotic case with a low res + peripherals section visible :)

I have added some minor tweaks, to make UI a bit more compact in your case, it would hide GPU / Sreen sections tooltip labels if window top position is outside of the screen

[GHelper.zip](https://github.com/seerge/g-helper/files/14586242/GHelper.zip)

**Comment by seerge** [comment]
Live in https://github.com/seerge/g-helper/releases/tag/v0.160

**Comment by Diamondoard** [comment]
> 住在 https://github.com/seerge/g-helper/releases/tag/v0.160

thanks, excellent work！
