### ISSUE TITLE
Support for Intel 12th Gen Core Options?

### ISSUE THREAD

**Issue by GriddyYet** [seerge/g-helper#2217]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hello, I would like to inquire about implementation of 'Set P-core and E-core' count on the Extras page. Are Intel 12th Gen CPUs supported on the said subject?

### Describe the solution you'd like

Is there a possible implementation in mind regarding the said generation of Intel CPUs?

### Device and Model

ASUS Strix Scar G15 G533ZX

**Comment by seerge** [comment]
@GriddyYet hello,

It doesn't depend on Intel generation, but if Asus has allowed that option in BIOS and exposed it for AC (and G-Helper correspondingly)

If app sees that possibility - it would shown a dropdown to disable P/E-cores under ``Extra``, if not - then it's not possible and most probably you didn't had that in AC neither :)
