### ISSUE TITLE
can u add a seperate setting to adjust rgb value slider or user define color temperature for next tim

### ISSUE THREAD

**Issue by AayushV12** [seerge/g-helper#2219]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

can u add a seperate setting to adjust rgb value slider or user define color temperature for next tim

### Describe the solution you'd like

can u add a seperate setting to adjust rgb value slider or user define color temperature for next tim

### Describe alternatives you've considered

can u add a seperate setting to adjust rgb value slider or user define color temperature for next tim

### Device and Model

asus rog strix g15 g513rc hn062w

### Additional information.

can u add a seperate setting to adjust rgb value slider or user define color temperature for next tim

**Comment by seerge** [comment]
@AayushV12 hello, all possible RGB Backlight settings are already can controlled via Keyboard section, you have a color choice there.

**Comment by AayushV12** [comment]
where

**Comment by AayushV12** [comment]
bro the color temperature rgb sliders
