### ISSUE TITLE
Texts cut at the end in Turkish

### ISSUE THREAD

**Issue by hkaancaliskan** [seerge/g-helper#222]
![resim](https://user-images.githubusercontent.com/17825767/231240480-9494180f-09ad-4299-852d-dcdc9978c320.png)

![resim](https://user-images.githubusercontent.com/17825767/231240527-a67631a0-3bdd-4b24-933a-21fdecf11c75.png)

Side note: https://github.com/seerge/g-helper/blob/32b83d724d8a024b34317e253dd46d0f07b3e365/app/Properties/Strings.tr.resx#L364 should be "Kapalı"

**Comment by seerge** [comment]
Welcome to the life of a localizator :) I think you need to come up with a bit shorter labels

**Comment by hkaancaliskan** [comment]
lmao they're already short, lemme see :/

**Comment by JackB111** [comment]
https://github.com/HamzaYslmn/g-helper-TR
@hamzayslmn

@hkaancaliskan  I already found a translated repo here you should take a look.

**Comment by JackB111** [comment]
> 

you have to download it and look at it.

<img width="307" alt="image" src="https://user-images.githubusercontent.com/129295334/231278481-86c3d966-7ac2-4bb3-a89f-525b5d6d3f5e.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/129295334/231278517-6bdc2af2-a722-4f6d-be67-06d36cbb7259.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/129295334/231278540-19ffcf04-2573-4939-9b15-f9d0a6e78eda.png">

<img width="310" alt="image" src="https://user-images.githubusercontent.com/129295334/231278612-e66c8a47-768e-440e-b599-f40940340de3.png">

<img width="456" alt="image" src="https://user-images.githubusercontent.com/129295334/231278636-1bfcac46-ecd8-4835-8e1f-11a7aa3697cc.png">

**Comment by hkaancaliskan** [comment]
> I wonder why he didn't participate in that translation.
> 
> 
> 
> https://youtu.be/d8g1XQUtG6o
> 
> 
> 
> he made a video for this app :D

hehe translation looks good but not 1:1

he should pr these changes :)

**Comment by hkaancaliskan** [comment]
oh wait a minute, whats that TRY symbol at version control text over there, is that some kinda funding? can you check that?

**Comment by JackB111** [comment]
> oh wait a minute, whats that TRY symbol at version control text over there, is that some kinda funding? can you check that?

I think he's collecting donations idk

**Comment by hkaancaliskan** [comment]
> > oh wait a minute, whats that TRY symbol at version control text over there, is that some kinda funding? can you check that?
> 
> I think he's collecting donations idk, But since mit is a licensed product, I guess such things are normal.

yep he's collecting donations but that's not ethical imo

yeah his translation is good, he should open pr with those

**Comment by hkaancaliskan** [comment]
and he also translated readme, he should also pr that too

**Comment by seerge** [comment]
@hkaancaliskan i have made labels a bit longer, so it seem to fit now
and i have replaced Kapalı

Reuploaded to 0.50 again :) so it should be fine

Thanks
