### ISSUE TITLE
Fn+V Isn't working as expected

### ISSUE THREAD

**Issue by riyanshlunia** [seerge/g-helper#2221]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

As the fucntion key + V is designated to change the visual mode it isn't doing soo and to clarify I've already configured it to change the visual mode in the extra settings

### How to reproduce the bug?

By pressing fn + v and noticing their's no change

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14596911/log.txt)

### Device and Model

FX507ZE

### Additional information.

![Screenshot 2024-03-14 103517](https://github.com/seerge/g-helper/assets/72033389/f75c2ae3-8eee-4473-a6cc-1fa85d5e7b28)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.160

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@riyanshlunia hello, your device simply doesn't have that hotkey on your device in a first place (you also didn't have it in AC).

FN-V produces keycode ``138`` in a log :) it's not in your log. So it won't work for you.

You can bind Visual Mode to any other supported hotkey combination tho

**Comment by seerge** [comment]
@riyanshlunia this build should hide unsupported FN-V binding on TUF devies
[GHelper.zip](https://github.com/seerge/g-helper/files/14600182/GHelper.zip)

**Comment by riyanshlunia** [comment]
When I am trying to download the above mentioned file it isn't letting me download it, It says virus detected You sure want me to download it by turning off the windows defender?

**Comment by seerge** [comment]
@riyanshlunia I have just removed FN-V from the list for TUF devices :) if you don't want to download - you don't have to, and just wait for a next release that will include that as well

**Comment by GhostasDead** [comment]
@seerge Sorry for the trouble, but my TUF device (FX505DD) does have the FN-V hotkey `138`, though it doesn't have FN-C but it appears in the list (doesn't work of course).
After trying the build in this thread, FN-V got removed from the list, but still works for the action I specified previously in the released build.

**Comment by seerge** [comment]
@GhostasDead hello, ok. I have restored it.

I have to admit it's incredibly confusing, when different people tell you different things :| 
[GHelper.zip](https://github.com/seerge/g-helper/files/14623043/GHelper.zip)
