### ISSUE TITLE
How to change or disable shortcuts?

### ISSUE THREAD

**Issue by LordDragon0815** [seerge/g-helper#2223]
I am already using the shortcut: Ctrl + Shift + F5. When I use this shortcut with G-Helper, it changes the CPU profile. How can I change or disable this shortcut for G-Helper?

**Comment by seerge** [comment]
@LordDragon0815 hello,

You can change that via config, please check readme 
https://github.com/seerge/g-helper/wiki/Power-user-settings#toggle-performance-mode-or-toggle-app-window-key-binding

Good luck

**Comment by LordDragon0815** [comment]
Hello, I have added the command "skip_hotkeys": 1, in config.json. The Keybind Ctrl + Shift + F5 is still working. 

![Screenshot 2024-03-14 210013](https://github.com/seerge/g-helper/assets/163449601/c7317f6d-dd05-45dc-a600-455cef3f6279)

**Comment by seerge** [comment]
@LordDragon0815 because you have added a wrong param, 

```
"keybind_profile": 0,
```

**Comment by LordDragon0815** [comment]
Thank you very much!!
