### ISSUE TITLE
[Feature request] Add a mirror checkbox for fan curves

### ISSUE THREAD

**Issue by dparson55** [seerge/g-helper#2225]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Could a "Mirror" checkbox be added to the BIOS Fan Curves so the user can set both the CPU and GPU fan curves by only editing the CPU curve alone? When it's checked the GPU curve could be grayed out and made to match the CPU curve, and any changes to the CPU curve would be reflected in the GPU curve. Maybe the fan speeds would need to be in percentages rather than absolute values but I'm not sure if that complication is needed if the fans are the same.

![image](https://github.com/seerge/g-helper/assets/19499747/645c6764-aaea-4ca4-90e6-9e87b94e68c7)

### Device and Model

Asus Zephyrus G14 GA402XV

**Comment by seerge** [comment]
@dparson55 hello,

With all the respect, I'm not a big fan of this idea as it's too exotic :) And even if you would make 2 same fan curves, fans will behave differently anyway, cause usually they follow temperature sensors + from my experience follow very approximately anyway.

You can just manually make similar curves, it's quite easy. Did you know you could hold ``Shift`` to drag all dots together ?

And UI under ``Fans+Power`` is already overloaded, and I don't want to overload it. 

Sorry, closing as not planned

**Comment by dparson55** [comment]
No worries, thanks for considering
