### ISSUE TITLE
Visual mode breaks color settings made in Intel graphics command center

### ISSUE THREAD

**Issue by Ragriod** [seerge/g-helper#2233]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I make some changes in color according to my needs in Intel graphics center but ever since I updated the Ghepler which had the Visual mode update, it reverts back to default setting. Since the color change in Intel command center and Asus app is different I think it's  breaking the functionality

### How to reproduce the bug?

1.  Open Intel graphics command center
2. Change color/hue/saturation
3. You can see the changes in the  display
4. After reboot the changes made in Intel command center will be gone and back to defaullt asus settings

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14622933/log.txt)

### Device and Model

ASUS TUF F15 FX506HC

### Armoury Crate

Installed

**Comment by seerge** [comment]
@Ragriod hello, G-Helper uses Asus Splendid utility to set Visual modes, exactly same as AC does. 

It applies custom color profile in combination with some other settings (like color temperature) using GPU APIs. How exactly it's done is implemented by Asus engineers and this is same as it was happening if you would do that in AC

If you don't like Visual Modes - just don't set them. If "Default" is selected, app would not run / set anything on restart.

Thanks

**Comment by seerge** [comment]
In your log last time app called splendid tool was (setting ``11`` Default mode)

```
16-03-2024 13:41:36: C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_f2eed2fae3b45a67\ASUSOptimization\AsusSplendid.exe 11 0 50
16-03-2024 13:41:36: UIGain: 1.000000 lutDcModeScale: 1.000000 Interval: 1.000000 RDLevels: 5.000000 index: 0.250000 Param: 2, Gamut mode: FFFF Gamut mapping process exit with return code 0 this->BiosDataStatus  = 0   ReadResult  = 0  Parsing version = 244 Use Method = 0   bios size = 0 CRCCheck Error CCTAPI_ERRORCODE = 0 CCT_Init  result = 0 Channel RGB[0]: smoothLv = 64 scatterLv = 0 diff = 0 lut type: 0 Channel RGB[1]: smoothLv = 64 scatterLv = 0 diff = 0 lut type: 0 Channel RGB[2]: smoothLv = 64 scatterLv = 0 diff = 0 lut type: 0 scale: 1.000000, Scale TH: 0.100000, nIndex: 26 New ScaleTH: 0.200000 New scale: 1.000000 outlut: [1.000000, 1.000000, 1.000000]
```

After that I see that you have restarted app couple of times, and it didn't call Splendid anymore, so it didn't touch your settings
