### ISSUE TITLE
G-Helper support: G16 No advanced options under Fans + Power

### ISSUE THREAD

**Issue by EssaMohamedali** [seerge/g-helper#2235]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

G16 GU603VV

Don't have advanced options under fans + power

Restarted computer after install

### How to reproduce the bug?

Installed G-helper 
Fans + power only showed CPU
restarted computer 
Fans + profile now shows CPU and GPU
Advanced still missing 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14623946/log.txt)

### Device and Model

Asus Zephyrus G16 GU603VV

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.158.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@EssaMohamedali hello,

Advanced Options is AMD undervolting, you have Intel CPU, so everything looks as it should.

For Intel undervolting you can try Intel’s official Extreme Tuning Utility 

Thanks
