### ISSUE TITLE
Fan speed

### ISSUE THREAD

**Issue by Tenta-dev** [seerge/g-helper#2236]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I apply the fan curve, the CPU fan ignores it and the GPU fan is disabled.
![image](https://github.com/seerge/g-helper/assets/45290336/1a486160-8d79-40fd-816b-794449506695)

### How to reproduce the bug?

1 - Go to Fan + Power
2 - Apply curve

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14624707/log.txt)

### Device and Model

ASUS TUF Dash F15 FX517ZR

### Armoury Crate

Never installed

### Asus Services

0

### Version

0.158.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Tenta-dev hello, [you clearly didn't read FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)

G-Helper doesn't control fans in realtime anyhow, same as AC.

You may want to experiment with a fan curve, like set first point higher, etc to see how BIOS will treat it then

**Comment by seerge** [comment]
@Tenta-dev Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks

**Comment by Tenta-dev** [comment]
@seerge Hello, yes i'll try it ! Thanks
