### ISSUE TITLE
Computer and hard disk crashes

### ISSUE THREAD

**Issue by masteryf** [seerge/g-helper#2237]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I run 3dmak, it can cause a crash, sometimes manifested as the hard drive not recognizing it. When using Armory Create, this issue is not present

### How to reproduce the bug?

When I install 3dmark on my second hard drive and run it, this issue occurs, causing me to have to force a restart

My computer model is GU603ZX, and the second hard drive model is Lexar SSD ARES 4TB

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14624857/log.txt)

### Device and Model

Asus Zephyrus M16 GU603ZX

### Armoury Crate

Uninstalled

### Version

0.160.0

### OS

Windows11 23H2

**Comment by seerge** [comment]
@masteryf hello, how is it connected to G-Helper ? it's not a driver, it's not running your system anyhow and definitely has nothing to do with your "second hard drive". 

So you should look what exactly you have changed in your system configuration

If your 3dmark crashes, it could be that you have overclocked your GPU too much, so try to reset all settings to defaults and use it like that.

**Comment by masteryf** [comment]
It seems that it is indeed due to overclocking, but strangely enough, this problem does not occur when I use MSIAfterBunner or Armory to overclock with the same parameters. It also does not occur when I install 3dmark on the first hard drive, only when I use g-helper to overclock and install the software on the second hard drive

Thank you for your reply. I can now use it normally

**Comment by seerge** [comment]
@masteryf great, I have no idea how is second hard distance connected to your 3dmark. May be app install there is just corrupt or something
