### ISSUE TITLE
Zephyrus G15 GA503QS keyboard backlight not working

### ISSUE THREAD

**Issue by reeson46** [seerge/g-helper#2238]
My keyboard backlight does not turn on. I'm 100% sure that the backlight works because previously I had Armoury Crate installed and I could set the color and everything. Today I had to reinstall the windows, and I didn't want to use AC, and then I found G-helper. Do I need to install any other additional app from Asus in order to get my backlight working? Cheers!

**Comment by seerge** [comment]
Please fill [issue template as it was asked](https://github.com/seerge/g-helper/issues/new?assignees=&labels=&projects=&template=bug_report.yml)

I don't have extrasensory skills to debug something with absolute zero information
