### ISSUE TITLE
High discharge rate (40W)

### ISSUE THREAD

**Issue by Muhiyaddeen** [seerge/g-helper#2239]
I Don't know if this is g-helper problem but the only this i did was download the new pre release (0.161) from github and delete my old version (0.157) and replaced with it that's when the problem started when i saw the new version g-helper discharge rate so i redownloaded my old version (0.157) it didn't go back normal and my cpu temp become high even in silent mode its at 60C and here i am please help i am a collage student i need my laptop battery to stay

Laptop - Asus Zephyrus G15 (2022)
GPU - RTX 3060
CPU - Ryzen 7 6800HS

![Screenshot 2024-03-17 031514](https://github.com/seerge/g-helper/assets/135968862/cbbce064-c3eb-4603-a54d-24d2a3c50976)

**Comment by seerge** [comment]
@Muhiyaddeen hello, it's not G-Helper problem. 

But on G15 you have a very bugged bios that sometimes forgets to disable GPU despite it says it did. 

Try to restart and enable / disable GPU. Good luck
