### ISSUE TITLE
Feature Request: Battery Wear Level & Remaining Capacity in Battery Section

### ISSUE THREAD

**Issue by nsilvias** [seerge/g-helper#224]
**Describe the solution you'd like**

The ability to see the Battery Wear Level at a glance in the battery section of Ghelper. Displaying the remaining capacity of the battery would also be nice but not as important if you'd like to keep things relatively clean looking.

**Describe alternatives you've considered**

HWiNFO

**Comment by seerge** [comment]
I'm not sure if such things as battery wear are needed for daily quick access (also battery wear is very approximate, and depends on calibration a lot). Adding this will cause a lot of people complaining and saying that it's incorrect or so.
