### ISSUE TITLE
Key binding Fn+F5 ROG Strix G15 (2022)

### ISSUE THREAD

**Issue by MDo94** [seerge/g-helper#2240]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

No problem at all, but in the keyboard of the ROG Strix G15 (2022) they are 2 keys that perform the similar actions (Mode selection) "Fn-F5" and "M5" even though, G-Helper only considers M5 and ROG keys as ONE key binding.
![71Eu](https://github.com/seerge/g-helper/assets/37194235/d2453a72-5c6e-414e-98d9-cebae52f892e)
![Screenshot 2024-03-16 203928](https://github.com/seerge/g-helper/assets/37194235/cd93b754-5fe1-462e-b1b8-84031a4f4f0b)

### Describe the solution you'd like

Add support for "Fn+F5" on Key binding...

### Device and Model

Asus ROG Strix G15 G513IM

**Comment by seerge** [comment]
@MDo94 hello,

This is a duplicate:)

Fn+F5 and M4 emit same keycode, so it's impossible to separate them unfortunately 

Check my answer here https://github.com/seerge/g-helper/issues/2157
