### ISSUE TITLE
Help: Touchpad Lock Setting can not be saved correctly

### ISSUE THREAD

**Issue by CNgBoNd** [seerge/g-helper#2241]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

computer type: ROG Flow X13 GV301QE
G-Help type: v0.158.0
question: I am used to turning off the laptop touchpad and using the mouse, but every time I restart the computer, the touchpad will be reopened. Can I try to record the on/off status of the touchpad through G-help?

### How to reproduce the bug?

1.press FN+F10 for turning off touchpad.
2.restart the computer.
3.you can find the touchpad has been turning on.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14626478/log.txt)

### Device and Model

ROG Flow X13 GV301QE

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

0.158.0

### OS

Windos11 22H2

**Comment by seerge** [comment]
@CNgBoNd hello, it's totally handled by windows itself. 

App just emits corresponding windows shortcut to toggle touchpad (win + ctrl + shift + f24) every time you press your hotkey. It can't save or restore its status.

There is nothing I can change here unfortunately.

Thanks
