### ISSUE TITLE
update centre

### ISSUE THREAD

**Issue by AayushV12** [seerge/g-helper#2244]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

i have updated a red driver multiple times but it doesnt go away
![Capture](https://github.com/seerge/g-helper/assets/163135158/a0bc926d-15da-480e-8832-04f7a84c5cf3)

### How to reproduce the bug?

a

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14626935/log.txt)

### Device and Model

asus rog strix g15 g513rc hn062w

### Additional information.

a

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

everyone

### OS

windows 10

**Comment by seerge** [comment]
@AayushV12 hello,

It’s because actual driver version (that you download and install) is different from how that file is marked on Asus servers

```
17-03-2024 15:14:11: Realtek LAN Driver PCI\VEN_10EC&DEV_8125&SUBSYS_208F1043&REV_05 1125.010.0720.2022 vs 10.54.1111.2021 = 1
```

Since it’s a problem on asus server, i can’t fix it.

You can just ignore it cause you have already installed it

Good luck
