### ISSUE TITLE
Requesting flicker-free dimming for ASUS VIVOBOOK PRO 16X OLED M7600QE.

### ISSUE THREAD

**Issue by Logisoc** [seerge/g-helper#2246]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Flicker-free dimming missing from the list of the compatible laptops.

### Describe the solution you'd like

Add the flicker-free dimming feature. Thanks in advance!

### Device and Model

ASUS VIVOBOOK PRO 16X OLED M7600QE

**Comment by seerge** [comment]
@Logisoc hello, try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14639861/GHelper.zip)

**Comment by Logisoc** [comment]
Thanks!
