### ISSUE TITLE
Very inconsistent Fn key and ROG key functionality

### ISSUE THREAD

**Issue by Faxanadus** [seerge/g-helper#2247]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The Fn key and ROG key usually do not work when starting the application.  Either they are both working, or they are both not working.

### How to reproduce the bug?

1. When starting the program for the first time, either manually (as administrator) or by using the Run on Startup option, the Fn key and ROG key will definitely not work.

2. With Fn-Lock ON, pressing F-keys (without Fn being held down) will work for increasing brightness, etc.

3. With Fn-Lock OFF, the Fn key will occasionally work as expected (where I need to actually hold down the Fn key while pressing the F-keys to increase brightness, etc.). I may have to close the program (by right clicking the icon in the taskbar and selecting Quit) and run it as administrator to make it work.  It may take 1-4 restarts before it starts working, and as mentioned in step 1. it will definitely not work the first time the program is started,

4. When the Fn-Key is not working (as in step 3), the ROG key to open the G-Helper window will also not work.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14644027/log.txt)

### Device and Model

Asus ROG Zephyrus S17 GX703HS

### Additional information.

![ghelper](https://github.com/seerge/g-helper/assets/163935254/f5049d03-4e36-45e6-9236-2f1105d28039)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.158.0  (also tried 0.161.0 and 0.151.0 - same behaviour)

### OS

Windows 10 Pro 22H2

**Comment by Faxanadus** [comment]
Hi, yes if I have Asus Optimisation Service running it appears to work every time.   Thanks!

**Comment by seerge** [comment]
@Faxanadus ok, my only assumption on this stage that you have 2 input devices that identify themselves as keyboard, and app connects to first one in the list, while correct one is other

Can you run this build and post a log from it?
[GHelper.zip](https://github.com/seerge/g-helper/files/14652137/GHelper.zip)

**Comment by Faxanadus** [comment]
Gave the new build a go, and this one works every time without Asus Optimization running and with an external USB keyboard plugged in too, though I did need to unplug the USB keyboard and start G-Helper without it plugged in one time before the hotkeys started working definitely, and from then on it worked regardless if I had the USB keyboard plugged in or not.  And yeah I did have the same external USB keyboard plugged in when the previous version's log file was recorded, good catch! :)  Here is the log for the new version:

[log.txt](https://github.com/seerge/g-helper/files/14655290/log.txt)

**Comment by seerge** [comment]
@Faxanadus ok, thanks. I was not aware about external keyboard...

Can you check if this build works correctly with an w/o keyboard connected, and also after reboot.

And post a log again. Thanks
[GHelper.zip](https://github.com/seerge/g-helper/files/14655527/GHelper.zip)

**Comment by Faxanadus** [comment]
I tested the new build while rebooting with the USB keyboard connected and without, and the hotkeys work the first time every time in all circumstances now.  Great job! Also sorry I blanked on mentioning the USB keyboard the first time!

[log.txt](https://github.com/seerge/g-helper/files/14656238/log.txt)

**Comment by seerge** [comment]
@Faxanadus ok, great
