### ISSUE TITLE
Zephyrus g15 2022 need cpu undervolted

### ISSUE THREAD

**Issue by ryrin17** [seerge/g-helper#2249]
My computer is Zephyrus G15 2022 (6800hs+3070ti).

I couldn't undervolted though anyway.

<img width="819" alt="G15" src="https://github.com/seerge/g-helper/assets/122677320/e3eb17f4-729d-461a-9e90-7b82143e94a7">

![表](https://github.com/seerge/g-helper/assets/122677320/edd122ee-c2e7-43b9-b03e-daf46b1ada08)

I heard that Zephyrus G14 2022（6800hs） could be undervolted.
<img width="552" alt="G14" src="https://github.com/seerge/g-helper/assets/122677320/266a1c54-d149-4af0-8f40-c6fcd79916cd">

### Describe the solution you'd like

Undervolted  Zephyrus G15 2022 6800hs

### Device and Model

Zephyrus G15 2022(GA503RW)

**Comment by seerge** [comment]
@ryrin17 hello, Ryzen 7 doesn’t support undervolting, sorry.

Check this topic

https://github.com/seerge/g-helper/discussions/736
