### ISSUE TITLE
SupportTPL PL1/PL2 setters

### ISSUE THREAD

**Issue by A-Amen** [seerge/g-helper#2255]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Have TPL power limits in G Helper rather than launch Throttlestop to set them.

### Describe alternatives you've considered

Throttlestop. But when launching it, it switches power plan so fan curves do not work anymore.

### Device and Model

Asus Tuf dash F15 FX516PC

**Comment by seerge** [comment]
@A-Amen hello, G-Helper can set power limits only via asus own endpoints.

PL1/PL2 are already available for models that support that, if you don't see sliders under Fans+Power it means your device doesn't support them in an asus way. So I can't do much here :) 

Thanks
