### ISSUE TITLE
Refine the Update window information for better clarity

### ISSUE THREAD

**Issue by julianxhokaxhiu** [seerge/g-helper#2256]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

It would be nice to filter out the components that do not really pertain to a specific model. For instance if you open the Update window you'll see that the ones that were found ( green ones ) were found and is checking for the latest update, but the ones not found ( gray ones ) are still available to be downloaded. I think this is misleading for the user thinking those items have to be installed when instead the component is really simply not even meant to be there ( eg. `Mediatek WLAN Driver` ).

Attached an example on my current ASUS ROG Laptop:
![image](https://github.com/seerge/g-helper/assets/1237070/6ecbb287-9eb0-4d99-9fd5-135bcda4c01e)

As you may notice also in the list also some false positives, for eg. `AMD Control Panel` which shows as gray, while it should be green since I have the latest AMD Adrenaline 24.1.1 driver installed.

### Describe the solution you'd like

It would be nice if you could filter out what is not matched as installed, or maybe group the items by "Installed/Not Installed" where the "Not Installed" ones could be grouped as "Mandatory/Optional". This would give a clear indicator on what is suggested to have and what you might want to have, assuming the component is meant to be installed for your own model.

And ideally fix false positives, by showing them as green if detected as installed.

### Describe alternatives you've considered

Ignoring them visually, but that's not really a solution I think...

### Device and Model

Asus ROG Strix G513QR

**Comment by seerge** [comment]
@julianxhokaxhiu hello,

This page is a mirror of an Asus website / API for your specific model. So if WAN driver is there - it means asus offers it for your device.

There is no false positives here

As for having some components in grey, is cause it’s just impossible to check a local version of that.

API provides list of component ids related to this specific driver, and app already checks with windows device manager if those components exist in the system and their local version. 

AMS control panel is NOT a driver, it’s an all from appstore, therefore it’s not feasible to compare its version. 

So app already does everything possible in this case.

Thanks
