### ISSUE TITLE
Fans remain running after lid closed, but only when applying custom fan curve.

### ISSUE THREAD

**Issue by zixiao-li** [seerge/g-helper#2257]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Fan would not stop spinning after closing lid if I apply custom fan curve. This is true on all three modes.
![Screenshot 2024-03-20 170747](https://github.com/seerge/g-helper/assets/109104046/802c970e-623b-4234-933e-1705a0e60b42)
If uncheck custom fan curve, fans stop spinning after closing the lid.

### How to reproduce the bug?

1. Click Apply Fan Curve
2. Close the lid
3. Fans stay on

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14676074/log.txt)

### Device and Model

ROG Zephyrus G16 GU605MI_GU605MI

### Additional information.

This is every ASUS service running.
![Screenshot 2024-03-20 171856](https://github.com/seerge/g-helper/assets/109104046/1115ca3e-6d22-437c-8037-3b273ddcb2e2)

### Armoury Crate

Uninstalled

### Asus Services

11

### Version

0.159.0.0en-US

### OS

Windows 11 Home 23H2

**Comment by seerge** [comment]
@zixiao-li hello,

You clearly didn’t read FAQ. G-helper doesn’t control your fans. If your BIOS has a bugged behaviour during sleep and keeps fans running I can’t change that.

You may try to stop asus services to see if it helps, or stick to default fan curves 

Thanks
