### ISSUE TITLE
game profiles

### ISSUE THREAD

**Issue by AayushV12** [seerge/g-helper#2260]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

game profiles

### Describe the solution you'd like

game profiles

### Describe alternatives you've considered

game profiles

### Device and Model

asus rog strix g15 g513rc hn062w

### Additional information.

game profiles

**Comment by seerge** [comment]
@AayushV12 I’m spending exactly same amount of time to respond to you as you have spent to write this.
