### ISSUE TITLE
Mode change pop keeps popping up when using battery charge limit feature

### ISSUE THREAD

**Issue by umerstar** [seerge/g-helper#2261]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When setting the battery charge limit to any amount (80% in my case) and charging using the type c port, after reaching 80% charging stops and the mode popup shows up (turbo set on battery and charging mode so turbo pops up). After a few seconds the charge level drops below 80% and charging resumes and this again shows the turbo pop up.

Now this constantly keeps happening when charge percent is around 80 and brings the current window out of context so if you are typing somewhere that stops.

Is this intended. Is it possible to disable the pop up or resume charging after it has drained 5% or something to 75 from 80

### How to reproduce the bug?

1. set charge limit to 80%
2. mode to any 
3. charge with type c and let it reach 80%

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14693232/log.txt)

### Device and Model

Asus Zephyrus G14 GA402XV

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.158

### OS

Windows 11 Home 22H2

**Comment by KelvinCrag** [comment]
@umerstar have you been able to fix the issue? I have the same issue on my Zephyrus M16 GU604VI.
