### ISSUE TITLE
Add UX8402V as supported OLED device

### ISSUE THREAD

**Issue by tetraflon** [seerge/g-helper#2262]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Flicker-free dimming missing from the list of the compatible laptops

### Describe the solution you'd like

Add the flicker-free dimming feature

### Device and Model

Zenbook Pro 14 DUO UX8402VV

**Comment by seerge** [comment]
@tetraflon hello, this build should do the thing
[GHelper.zip](https://github.com/seerge/g-helper/files/14697012/GHelper.zip)
