### ISSUE TITLE
Can't switch from intergrated graphics to dedicated graphics automatically in Optimized mode

### ISSUE THREAD

**Issue by caolonghao** [seerge/g-helper#2263]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

The model of my laptop is GU604VI, i.e. Zephyrus M16 2023 with RTX4070. Everything works fine on my machine, except the HDMI port in DC mode.
I usually use `Optimized` setting, as it can automatically switch to intergated graphics when there is no power pluged in. However, when it comes to HDMI connection, things can be a little different. At least for my machine, I have to turn mannually my dedicated GPU on (Standard Mode) to output HDMI signal. But the original ASUS Armoury Crate will automatically switch to hybrid mode for normal HDMI output.

### Describe the solution you'd like

Maybe we can add some detector, when a HDMI cable is plugged in, switch from pure iGPU to iGPU + dGPU?

### Device and Model

Asus Zephyrus M16 GU604VI

**Comment by caolonghao** [comment]
Same solution as you did. So is it possible to detect the plug in of HDMI? I guess there could be some available APIs so we can add the feature.

**Comment by seerge** [comment]
@caolonghao hello,

As @IceStormNG has already explained detecting HDMI devices on disabled(!) GPU is very cumbersome process and I simply don't know how to do that.

Also it would go against whole idea of Optimized mode that would keep GPU off if you are on battery. Such exceptions will cause only more confusion and problems (for example drain laptop s battery dead if you accidentally  left HDMI plugged but not charger)

If you often use external monitor and use laptop from battery - just set Standard mode. Luckily it's very easy to do :) 

So sorry, but i'm not planning this. Thanks
