### ISSUE TITLE
G-Helper and MyASUS download different versions of ASUS System Control Interface V3 from different sources

### ISSUE THREAD

**Issue by moldimolt** [seerge/g-helper#2267]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hello. On my GX650PY, G-Helper reports ASUS System Control Interface V3 driver 3.1.22.0 is the latest version and links this download URL: https://dlcdnets.asus.com/pub/ASUS/GamingNB/Image/Software/SoftwareandUtility/15528/ASUSSystemControlInterfacev3_ASUS_Z_V3.1.22.0_15528_2.exe?model=GX650PY

MyASUS reports the ASUS System Control Interface V3 version is outdated and installs a different version, 3.1.25.0. It appears this version comes from https://dlcdnets.asus.com/pub/ASUS/nb/Image/CustomComponent/ASUSSystemControlInterfaceV3/ASUSSystemControlInterfaceV3.exe. 

I think this is actually ASUS' fault for not updating the version of this driver on model-specific listings (https://rog.asus.com/laptops/rog-zephyrus/rog-zephyrus-duo-16-2023-series/helpdesk_download/), but maybe G-Helper should download ASUS System Control Interface V3 and V1 from the generic source as these drivers are intended to be device-agnostic (at least based on https://www.asus.com/support/faq/1047338/) and that's what MyASUS seems to do? 

Thank you.

### How to reproduce the bug?

1. Observe G-Helper reports 3.1.22.0 is the latest version of ASUS System Control Interface V3. 
2. Observe MyASUS reports 3.1.25.0 is the latest version of ASUS System Control Interface V3.

### Logs

N/A

### Device and Model

ASUS Zephyrus Duo GX650PY 

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.161

### OS

Windows 11 23H2 (22631.3296)

**Comment by seerge** [comment]
@moldimolt hello,

G-Helper uses official ASUS API to get list of drivers

ASUS API for your specific model reports 3.1.22 as latest version
https://rog.asus.com/support/webapi/product/GetPDDrivers?website=global&model=GX650PY&cpu=GX650PY&osid=52

There is nothing to fix for me here. They will eventually update API and add a new version there as well.

For now you can just download 3.1.25 manually :) But I don't think that something critical has changed there specifically for your device

**Comment by moldimolt** [comment]
Interesting. Is MyASUS using a different API?

**Comment by seerge** [comment]
@moldimolt when I was checking it last time - it was using exactly this API :)

**Comment by moldimolt** [comment]
Huh, strange. When I install 3.1.22.0 on this device and launch MyASUS, it complains that 3.1.22.0 is outdated and asks to install 3.1.25.0

**Comment by seerge** [comment]
@moldimolt well, you can update it there :) there is no harm in that for sure

**Comment by moldimolt** [comment]
Thanks! I was mostly just curious, maybe ASUS is using a different API for certain generic drivers now or something.
