### ISSUE TITLE
Add maximum frequency for CPU based on mode

### ISSUE THREAD

**Issue by aet08** [seerge/g-helper#2268]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

It would be helpful to add a maximum frequency based on the CPU profile selected to G helper

![image](https://github.com/seerge/g-helper/assets/15637131/e7348a42-84ab-427d-b037-12ab86ced42b)

### Device and Model

Asus X13 GV302XI.311

**Comment by seerge** [comment]
@aet08 hello, this is a duplicate, please check this topic for more info https://github.com/seerge/g-helper/discussions/1907
