### ISSUE TITLE
Add Vivobook M6500QC as supported OLED device.

### ISSUE THREAD

**Issue by CranenaZ** [seerge/g-helper#2269]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Flicker-free dimming missing from the list of compatible laptops.

### Describe the solution you'd like

Add the flicker-free dimming slider.

### Device and Model

ASUS Vivobook M6500QC

**Comment by seerge** [comment]
@CranenaZ hello, this build should have it, thanks.
[GHelper.zip](https://github.com/seerge/g-helper/files/14730909/GHelper.zip)
