### ISSUE TITLE
Flicker-free Dimming / Visual Mode display toggle

### ISSUE THREAD

**Issue by Constrat** [seerge/g-helper#2271]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

For devices that don't support `Flicker-free Dimming`, G-Helper (correctly) only shows `Visual Mode`.
![image](https://github.com/seerge/g-helper/assets/56174894/2c1d55a7-45d8-4787-83be-664293104ec8)
If users prefer the default screen coloring, downloading the Color Profiles, automatically default and applies to a different color profile, which would result in having to remove the colors from the system to go back.

### Describe the solution you'd like

If the device does not support `Flicker-free Dimming`, adding a toggle for Visual Mode would be much appreciated, to clear the UI and to prevent misinputs that would lead to coloring issues.

### Device and Model

Asus ROG Strix G713RW

**Comment by seerge** [comment]
@Constrat downloading Color Profiles - only gets correct ICC files into GameVisual folder :) it doesn't even apply that.

Also this is the most color accurate profile you can have on your display, so I don't see where the problem here ?

**Comment by Constrat** [comment]
Oh, I didn't notice it wasn't applying them (maybe I was too fast :P)
Regarding the color accuracy, maybe it's just personal preference, but the red looked ugly XD

**Comment by seerge** [comment]
@Constrat what mode did you select ? Default or something else ? Cause ICC from asus are actually good ones, and they are factory calibrated as far as I know.

Cause ``Default`` = just native ICC from asus w/o any modifications, rest modes adjust gamma / white point (in my point of view they are ugly, but lots of people were asking about that)

If you want to use other ICC - you select it again in windows color management app, and keep visual mode on "Defaut" (then it won't reapply anything)

**Comment by Constrat** [comment]
Yes, it's the `default` `neutral`.
Compared to the second monitor (an LG 27GP850 without any ICC) all the colors appear more dead.
Maybe my eyes just want super saturated colors, when in reality they are not.

**Comment by seerge** [comment]
@Constrat discord uses chromium under the hood, and chrome / chromium render colors based on currently active color profile

P.S. There is no such thing as "no ICC", it is always some, but windows may use own default icc instead

**Comment by Constrat** [comment]
I searched a bit and paint.net is not using color profiles, hence why the red (#FF0000) seemed identical to the second monitor.
Regarding the no ICC, I was meaning that there was no custom ICC.
From the looks of it, Windows uses the same ICC profile for all screens (hence the consistency) if there is no custom ICC enabled.

**Comment by Constrat** [comment]
@seerge I dug more deeper. Apparently, without any color profile the monitor is not in "wide gamut mode".
https://www.wide-gamut.com/test
Testing both the laptop screen and the an LG 27GP850 with and without their related "official" color profiles, makes the W disappear / appear.
Strange shenanigans happen if I take a screen of the W and open it with Photos. It seems like the profile color will be applied two times... Strange indeed.
Honestly all this comes at a cost of desaturated colors. All colors close to the peak (FF0000 for example) still appear more dead.
I might have been over saturated my entire life

**Comment by seerge** [comment]
@Constrat if you used standard gamut profile on wide gamut monitor, no wonder everything was oversaturated :) But if you do something related to color, it's always better to see it in a way as other users will do (i..e use correct color profile for your screen)

**Comment by Constrat** [comment]
So these last 3 years have been oversaturated wow :P
