### ISSUE TITLE
New Color temperature/Visual modes destroyed my colors

### ISSUE THREAD

**Issue by SynStark** [seerge/g-helper#2273]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

After updating to 0.161 I saw the option to download Color temperature settings in order to use the Visual profiles, but that immediately changed my colors. Now even at Default mode everything looks kinda worse. The white is gray-ish and everything looks bland like my contrast is down. If I raise my contrats to 90 in Nvidia Control Panel the white gets fixed but everything else looks crazy. Is there any way to revert all that even if I won't be able to use the Visual modes?

### How to reproduce the bug?

N/a

### Logs

N/a

### Device and Model

Scar 18

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.161.0

### OS

11

**Comment by Constrat** [comment]
Just go in Colour Management
![image](https://github.com/seerge/g-helper/assets/56174894/f2a66fb0-38d6-437c-a4ed-6d1051c8c479)
and toggle off the "Use my settings" for the laptop screen.

**Comment by seerge** [comment]
@SynStark hello, it just sets official Asus ICC color profile for your device (and if you set something different from "Default" adjusts gamma / etc.

All this is done not by G-Helper itself, but Asus own AsusSplendid utility (so it's exactly same as Armoury calls when sets own modes)

You may open windows Color Management and uncheck Asus color profile and select whatever you used before, or just disable windows color management completely. 

As far as you keep VIsual mode selected on Default ,app won't override anything 

Good luck

**Comment by seerge** [comment]
@SynStark hello,

I have recently discovered how Armoury can completely disable Game Visual by calling `AsusSplendid.exe` (responsible for it) and added it to G-Helper as new "Disabled" Visual Mode.

It is live in latest release https://github.com/seerge/g-helper/releases/tag/v0.196

Let me know if it changes something for you
