### ISSUE TITLE
G14 2024 issue with detection of plugged in switching from eco to standard in optimized mode

### ISSUE THREAD

**Issue by Croozal** [seerge/g-helper#2274]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

In the optimized GPU setting, when unplugging the laptop from power source, the GPU mode correctly switches from iGPU+dGPU to iGPU only (ECO). However, when plugging laptop back in, the laptop remain in eco mode (iGPU only) with the dGPU still disabled. The issue is fixed if optimized is clicked again to switch manually to the ECO mode, and then clicking optimized, it correctly determines that it's plugged in and turns on the dGPU. However, unplugging and replugging the laptop resets the issue.

### How to reproduce the bug?

1. Set laptop to optimized GPU mode, on charging
2. Unplug laptop
3. Plug in laptop

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14732932/log.txt)

### Device and Model

G14 GA403UI

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.161.0

### OS

Version	10.0.22631 Build 22631

**Comment by seerge** [comment]
@Croozal do you have "Keep GPU disabled on usb-c charger" checked under ``Extra`` ? 
Cause I see that it sees charger as usb-c and therefore keeps GPU off (by design)

```
23/03/2024 16:35:23: AutoSetting for Online
23/03/2024 16:35:23: BatteryLimit = 80 : OK
23/03/2024 16:35:23: Mode = 1 : OK
23/03/2024 16:35:23: Clocks: Eco
23/03/2024 16:35:23: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a -> ded574b5-45a0-4f42-8737-46345c09c238:OK
23/03/2024 16:35:23: Boost 2
23/03/2024 16:35:23: ChargerStatus: 0 <--- device reports itself as usb-c charged
```

**Comment by Croozal** [comment]
@seerge Indeed I do! I have a TB4 dock that has power delivery as well, which I use at work. However, at home I use the regular power brick and that's where I face this issue. I just checked, and having the 'disable GPU on USB C power' disabled fixes the issue, however, it's using the regular power brick so that's strange.

**Comment by seerge** [comment]
@Croozal well, may be it's some bug in bios, that it remembers that it was on USB-c before and keeps reporting it.

I can't "fix" it anyhow, as it will ruin behavior of whole feature on all devices.

And you can just uncheck ``disable GPU on USB C power`` then.

**Comment by Croozal** [comment]
I see, that's ok, I can totally live with that. Thanks for the help and thank you for making all our lives easier with this software!
