### ISSUE TITLE
Vivobook 14X OLED (K3405) - No OLED / colour profile settings 

### ISSUE THREAD

**Issue by rumifloss** [seerge/g-helper#2275]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I have a Vivobook 14X K3405VFB and I can't see any OLED features like FlickerFree or even the colour gamut and colour profile settings on the latest public build. 

Also, I'm sorry it's off-topic, but can I add a new profile to the Mode menu when one right-clicks the G-Helper system tray icon?

### How to reproduce the bug?

Open latest version of G-Helper on Vivobook 14X K3405VFB

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14732970/log.txt)

### Device and Model

Asus Vivobook 14X K3405VFB

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.161.0

### OS

Windows 11

**Comment by seerge** [comment]
@rumifloss I have added your model serie to OLED list, so you should see it now in this build
[GHelper.zip](https://github.com/seerge/g-helper/files/14733364/GHelper.zip)
