### ISSUE TITLE
Can G-Helper support ASUS TUF M4 Wireless（P310）（China Mainland Edition,aka ASUS TX GAMING MOUSE）?

### ISSUE THREAD

**Issue by Ne0W0r1d** [seerge/g-helper#2277]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Yep,I just wanna G-Helper can support my mouse, I don't wanna use ARMOUY CRATE to manage my mouse

### Describe the solution you'd like

Yep,I just wanna G-Helper can support my mouse, I don't wanna use ARMOUY CRATE to manage my mouse

### Device and Model

ASUS Zephyrus M16 GU603ZM & ASUS TUF M4 Wireless P310

**Comment by seerge** [comment]
@Ne0W0r1d hello, you need to fill template for Mouse support and include all requested information there.

https://github.com/seerge/g-helper/issues/new?assignees=&labels=&projects=&template=peripherals_request.yml

I'm closing this, as you used a wrong issue template :)
