### ISSUE TITLE
Incorrect key bindings on ASUS TUF A17 FA706IC

### ISSUE THREAD

**Issue by Xender0** [seerge/g-helper#2278]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Key Binding should work like ->

F1-Mute
F2-Volume Down
F3-Volume Up
F4-Disable Mic
F5-Mode
F6-Screen Off
F7-Brightness Low
F8-Brightness High
F9-Cast
F10-Disable Touchpad
F11-Sleep
F12-Airplane Mode

Also, it will be cool if we can customize these key ourselves

### How to reproduce the bug?

Use Key bindings as mentioned also try to add functionality of customizing the key bindings on our own

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14734895/log.txt)

### Device and Model

ASUS TUF A17 FA706IC

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.161.0

### OS

Windows 11

**Comment by seerge** [comment]
@Xender0 hello, this build should have correct FN-lock bindings for your device
[GHelper.zip](https://github.com/seerge/g-helper/files/14735156/GHelper.zip)

Please keep in mind, that F12 doesn't work with FN-lock as it's reserved by windows and can't be remapped

**Comment by xender0** [comment]
F7 is supposed to work to reduce the brightness but works opposite, same with F8, they both should be swapped, i have also attached the image for reference, Thank you
![key](https://github.com/seerge/g-helper/assets/66633718/8a9c9805-ad6b-4aff-9c58-5ef4f1c40a15)

**Comment by seerge** [comment]
@Xender0 this build should swap brightness controls
[GHelper.zip](https://github.com/seerge/g-helper/files/14735260/GHelper.zip)

**Comment by xender0** [comment]
Works well.
Thank you
