### ISSUE TITLE
G-Helper to be able to access settings through Start Menu

### ISSUE THREAD

**Issue by Zolio** [seerge/g-helper#228]
I just downloaded G-Helper and after closing it I go click on G-Helper to open it back up through the Start menu, but it says "G-Helper is already running. Check system tray for an icon" 
**This is completely understandable but I would really appreciate if I would be able to access G-Helper's settings even through the Start menu.**

**Comment by seerge** [comment]
G-Helper stays in system tray, you can open it from there.  https://github.com/seerge/g-helper#it-says-that-app-is-already-running
