### ISSUE TITLE
Explain the overdrive feature in g helper

### ISSUE THREAD

**Issue by AayushV12** [seerge/g-helper#2280]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Should I enable or disable it for my laptop display if I only use it for valorant or normal browsing and nothing else

### Describe the solution you'd like

If possible list me pros and cons for this feature on my laptop display

### Device and Model

Asus rog strix g15 g513rc hn062w

**Comment by seerge** [comment]
@AayushV12 hello,

Display Overdrive is a general term https://en.wikipedia.org/wiki/Response_time_compensation

It reduces response time at a cost of small ghosting 

So unless it causes troubles for you it’s absolutely to keep it on , as this is how asus have designed this screens
