### ISSUE TITLE
Charge Limit Issue

### ISSUE THREAD

**Issue by legoleigh** [seerge/g-helper#2281]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Charge limit won't work above 80%, anything above that will start charging the battery.

### How to reproduce the bug?

Move slider about 80%

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14737835/log.txt)

### Device and Model

Asus Zephyrus G16 2024

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.161.0

### OS

Windows 11 23H2

**Comment by lilrajoo** [comment]
this happens on asus f15 fx507vu4 model too

**Comment by seerge** [comment]
@legoleigh @lilrajoo hello, please read FAQ https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working

Some models support only 80% limit by hardware. 

Thanks.

**Comment by lilrajoo** [comment]
hmm my model does support it, it worked when i used myasus software

**Comment by seerge** [comment]
@lilrajoo in MyAsus you can not set charge limit above 80%

**Comment by lilrajoo** [comment]
yea mine is set to 75% but it never works for me, i kept my asus servises off and uninstalled them all

**Comment by lilrajoo** [comment]
just did a test, the power limit doesnt work still even with lower/higher values then 80
[log.txt](https://github.com/seerge/g-helper/files/14741271/log.txt)

**Comment by seerge** [comment]
@legoleigh as I have clearly explained, not all models support custom limits. So set it exactly to 80% as you were setting in myasus.

**Comment by lilrajoo** [comment]
@seerge i did set it exactly to 80% this time, i did a few more tests with other values

**Comment by seerge** [comment]
@legoleigh the last value you have set is 75% ,which with a high chance is not supported by your device, so it would just start charging with that setting.

**Comment by lilrajoo** [comment]
hmm ok lemme run another test and ill get back to u here appreciate the help a lot

**Comment by lilrajoo** [comment]
@seerge i have restarted a few times and tried everything, but unfortunatly it doesnt work. anything else i can try to make it work? could changes in the bios be an issue? i have toggled a few things there

**Comment by seerge** [comment]
@lilrajoo it just should stop charging as soon as battery level is over 80%. It will not discharge back to that level of course.

You can simply set same limit in MyASUS and keep asus services working, if you like that more. There is no harm.

**Comment by lilrajoo** [comment]
@seerge yep i understand, its the charging that continues, i guess ill use my asus app for now, i just have to keep the asus services on right?

**Comment by lilrajoo** [comment]
@seerge it stays orange/yellow, usually it was white when the charging limit works. 
Using myasus, the charging still continues, even with ghelper not running

**Comment by seerge** [comment]
@legoleigh did you start Asus services from ``Extra`` ? in particular you need Asus Optimization Service running

**Comment by lilrajoo** [comment]
@seerge yep they are started, and the Asus Optimization Service is running
![image](https://github.com/seerge/g-helper/assets/110761131/39c78c62-70b2-4d68-93bb-d5dca8843d8f)

**Comment by seerge** [comment]
@lilrajoo if it persists after reboot - then at least for you, it's clearly not software issue :) cause even asus own services have same effect

**Comment by lilrajoo** [comment]
hmmm ok guess ill just have to deal with it for now, maybe get it checked if my battery health drops quite low. thx for your help :>
