### ISSUE TITLE
Can G-Helper support ASUS TUF M4 Wireless（P310）（China Mainland Edition,aka ASUS TX GAMING MOUSE）?

### ISSUE THREAD

**Issue by Ne0W0r1d** [seerge/g-helper#2282]
### Mouse / peripheral model and version

ASUS TUF M4 Wireless（P310） / ASUS TX GAMING MOUSE

### Armoury Crate Screenshots

![屏幕截图(1)](https://github.com/seerge/g-helper/assets/93416867/87ead9ed-21c6-4fb4-b11d-ed522b2ad3e4)
![屏幕截图(2)](https://github.com/seerge/g-helper/assets/93416867/387b7202-7350-461b-a1cb-2d5d8e9d68e1)
![屏幕截图(3)](https://github.com/seerge/g-helper/assets/93416867/57d2e62e-79ba-474a-9d9d-d1ff509edc02)
![屏幕截图(4)](https://github.com/seerge/g-helper/assets/93416867/abef8fea-0759-4bc0-9bda-81b746536b41)

### USB Details

 Child Device 1          : USB 输入设备
  Device ID              : USB\VID_0B05&PID_1A8D&MI_00\6&304B424&0&0000
  Class                  : HIDClass
  Driver KeyName         : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0000 (GUID_DEVCLASS_HIDCLASS)
  Service                : HidUsb
  Location               : 0000.0014.0000.004.000.000.000.000.000
  LocationPaths          : PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(4)#USBMI(0)  PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(4)#USB(4)  ACPI(_SB_)#ACPI(PC00)#ACPI(XHCI)#ACPI(RHUB)#ACPI(HS04)#USBMI(0)  ACPI(_SB_)#ACPI(PC00)#ACPI(XHCI)#ACPI(RHUB)#ACPI(HS04)#USB(4)
  SelectiveSuspEnabled   : 0
  EnhPowerMgmtEnabled    : 1
 Child Device 1          : 符合 HID 标准的供应商定义设备
  Device Path            : \\?\HID#VID_0B05&PID_1A8D&MI_00#7&1977f412&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (GUID_DEVINTERFACE_HID)
  Kernel Name            : \Device\00000143
  Device ID              : HID\VID_0B05&PID_1A8D&MI_00\7&1977F412&0&0000
  Class                  : HIDClass
  Driver KeyName         : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0007 (GUID_DEVCLASS_HIDCLASS)
 Child Device 2          : USB 输入设备
  Device ID              : USB\VID_0B05&PID_1A8D&MI_01\6&304B424&0&0001
  Class                  : HIDClass
  Driver KeyName         : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0001 (GUID_DEVCLASS_HIDCLASS)
  Service                : HidUsb
  Location               : 0000.0014.0000.004.000.000.000.000.000
  LocationPaths          : PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(4)#USBMI(1)  ACPI(_SB_)#ACPI(PC00)#ACPI(XHCI)#ACPI(RHUB)#ACPI(HS04)#USBMI(1)
  SelectiveSuspEnabled   : 0
  EnhPowerMgmtEnabled    : 1
 Child Device 1          : HID-compliant mouse
  Device Path 1          : \\?\HID#VID_0B05&PID_1A8D&MI_01#7&2ca81050&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (GUID_DEVINTERFACE_HID)
  Device Path 2          : \\?\HID#VID_0B05&PID_1A8D&MI_01#7&2ca81050&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd} (GUID_DEVINTERFACE_MOUSE)
  Kernel Name            : \Device\00000144
  Device ID              : HID\VID_0B05&PID_1A8D&MI_01\7&2CA81050&0&0000
  Class                  : Mouse
  Driver KeyName         : {4d36e96f-e325-11ce-bfc1-08002be10318}\0000 (GUID_DEVCLASS_MOUSE)
  Service                : mouhid
 Child Device 3          : USB 输入设备
  Device ID              : USB\VID_0B05&PID_1A8D&MI_02\6&304B424&0&0002
  Class                  : HIDClass
  Driver KeyName         : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0002 (GUID_DEVCLASS_HIDCLASS)
  Service                : HidUsb
  Location               : 0000.0014.0000.004.000.000.000.000.000
  LocationPaths          : PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(4)#USBMI(2)  ACPI(_SB_)#ACPI(PC00)#ACPI(XHCI)#ACPI(RHUB)#ACPI(HS04)#USBMI(2)
  SelectiveSuspEnabled   : 0
  EnhPowerMgmtEnabled    : 1
 Child Device 1          : 符合 HID 标准的用户控制设备
  Device Path            : \\?\HID#VID_0B05&PID_1A8D&MI_02&Col01#7&43d6287&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (GUID_DEVINTERFACE_HID)
  Kernel Name            : \Device\00000145
  Device ID              : HID\VID_0B05&PID_1A8D&MI_02&COL01\7&43D6287&0&0000
  Class                  : HIDClass
  Driver KeyName         : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0008 (GUID_DEVCLASS_HIDCLASS)
 Child Device 2          : 符合 HID 标准的系统控制器
  Device Path 1          : \\?\HID#VID_0B05&PID_1A8D&MI_02&Col02#7&43d6287&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} (GUID_DEVINTERFACE_HID)
  Device Path 2          : \\?\HID#VID_0B05&PID_1A8D&MI_02&Col02#7&43d6287&0&0001#{4afa3d53-74a7-11d0-be5e-00a0c9062857} (GUID_DEVICE_SYS_BUTTON)
  Kernel Name            : \Device\00000146
  Device ID              : HID\VID_0B05&PID_1A8D&MI_02&COL02\7&43D6287&0&0001
  Class                  : HIDClass
  Driver KeyName         : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0009 (GUID_DEVCLASS_HIDCLASS)
 Child Device 3          : 符合 HID 标准的供应商定义设备
  Device Path            : \\?\HID#VID_0B05&PID_1A8D&MI_02&Col03#7&43d6287&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030} (GUID_DEVINTERFACE_HID)
  Kernel Name            : \Device\00000147
  Device ID              : HID\VID_0B05&PID_1A8D&MI_02&COL03\7&43D6287&0&0002
  Class                  : HIDClass
  Driver KeyName         : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0010 (GUID_DEVCLASS_HIDCLASS)
 Child Device 4          : HID Keyboard Device
  Device Path 1          : \\?\HID#VID_0B05&PID_1A8D&MI_02&Col04#7&43d6287&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd (GUID_DEVINTERFACE_HID)
  Device Path 2          : \\?\HID#VID_0B05&PID_1A8D&MI_02&Col04#7&43d6287&0&0003#{884b96c3-56ef-11d1-bc8c-00a0c91405dd} (GUID_DEVINTERFACE_KEYBOARD)
  Kernel Name            : \Device\00000148
  Device ID              : HID\VID_0B05&PID_1A8D&MI_02&COL04\7&43D6287&0&0003
  Class                  : Keyboard
  Driver KeyName         : {4d36e96b-e325-11ce-bfc1-08002be10318}\0001 (GUID_DEVCLASS_KEYBOARD)
  Service                : kbdhid

**Comment by IceStormNG** [comment]
If it is otherwise identical to the regular TUF M4 Wireless, then this should do the trick.

Please try this build and let me know whether it works.
[GHelper.zip](https://github.com/seerge/g-helper/files/14741022/GHelper.zip)

**Comment by Ne0W0r1d** [comment]
Yes,This build can manage my mouse,thx
![屏幕截图 2024-03-25 165228](https://github.com/seerge/g-helper/assets/93416867/21d23e4b-16db-4b0b-ae17-6eedb49122b2)
