### ISSUE TITLE
Update for drivers not working

### ISSUE THREAD

**Issue by lilrajoo** [seerge/g-helper#2283]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The update section in ghelper doesnt really work for drivers, but works for BIOS. here is a picture of an example where the bluetooth driver details are up to date on windows but not on ghelper

![Screenshot 2024-03-25 121207](https://github.com/seerge/g-helper/assets/110761131/5b51e07f-416c-48bd-a0ad-b7fa60813fe9)

### How to reproduce the bug?

Go to updates click on refresh, crosscheck with driver version using device manager

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14738743/log.txt)

### Device and Model

Asus Tuf Gaming F15, F15 FX507VU4

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.161

### OS

23H2

**Comment by riyanshlunia** [comment]
Refer to this https://github.com/seerge/g-helper/discussions/1350

**Comment by seerge** [comment]
@riyanshlunia hello, G-Helper's update section is a mirror of Asus drivers page.

It shows driver version available on asus server for your model. And based on your screenshot it looks absolutely fine.

Keep in mind, that not for all devices it's possible to check a local installed driver version. And when it's not possible device will be marked as grey.

Thanks

**Comment by lilrajoo** [comment]
ok thx

**Comment by seerge** [comment]
@lilrajoo actually, I have added a small tweak, that should compare device IDs ignoring upper/lower case. As ASUS seem to report some devices incorrectly in their API.

Check this build if it makes a difference

But keep in mind that "software and utility" and "appstore" downloads won't be compared still, as they don't have physical device in the system
[GHelper.zip](https://github.com/seerge/g-helper/files/14741671/GHelper.zip)

**Comment by lilrajoo** [comment]
hmm all of the asus drivers are now green so it seems theres a difference
![image](https://github.com/seerge/g-helper/assets/110761131/24f2bb23-37cd-46e9-8fff-6c80d772602b)

**Comment by seerge** [comment]
@lilrajoo can you post Device Instance Path for Intel Bluetooth driver under your device manager (details tab)?

Asus API reports this IDs for it

```
                        "HardwareInfoList": [
                            {
                                "hardwareid": "USB\\VID_8087&PID_0026&REV_0000"
                            },
                            {
                                "hardwareid": "USB\\VID_8087&PID_0026&REV_0001"
                            },
                            {
                                "hardwareid": "USB\\VID_8087&PID_0026&REV_0002"
                            },
                            {
                                "hardwareid": "USB\\VID_8087&PID_0029&REV_0000"
                            },
                            {
                                "hardwareid": "USB\\VID_8087&PID_0029&REV_0001"
                            },
                            {
                                "hardwareid": "USB\\VID_8087&PID_0032&REV_0000"
                            },
                            {
                                "hardwareid": "USB\\VID_8087&PID_0032&REV_0001"
                            },
                            {
                                "hardwareid": "USB\\VID_8087&PID_0033&REV_0000"
                            },
                            {
                                "hardwareid": "USB\\VID_8087&PID_0033&REV_0001"
                            }
```

![image](https://github.com/seerge/g-helper/assets/5920850/e5da7853-1a51-4d87-8df7-c32556b10c13)

**Comment by seerge** [comment]
@lilrajoo this build should also cover Bluetooth, as ASUS adds ``REV_0000`` to device IDs that don't exist in real device manager
[GHelper.zip](https://github.com/seerge/g-helper/files/14742159/GHelper.zip)

**Comment by lilrajoo** [comment]
yea intel bluetooth is now green so it should work now. thx
