### ISSUE TITLE
CPU and GPU Temperatures Increase When Plugged In

### ISSUE THREAD

**Issue by fbycl** [seerge/g-helper#2289]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

When my G14 2021 model notebook is not plugged in, the system is 35-40 degrees Celsius at idle, but when I plug it in, it goes up to the 60s. Is this normal with the same energy and performance settings? Does anyone have any solutions?

### Describe the solution you'd like

To avoid this, something could be developed so that when it is plugged in, everything can continue as it would when it is not plugged in.

### Device and Model

Asus Zephyrus G14 GA401QM

**Comment by seerge** [comment]
@fbycl hello, hos is this related to g-helper in a first place ? When you plug in your device is charging probably, so heats up a bit.

**Comment by fbycl** [comment]
Even if the charge is 100%, the temperature stays at that level even though I set a charge limit. Does anyone else have the same problem?

**Comment by seerge** [comment]
@fbycl it could be millions of reasons for that, starting from windows running something when you plug in, to GPU being enabled, etc.
