### ISSUE TITLE
Performance Mode switching when using a PD charger

### ISSUE THREAD

**Issue by JJVVVV** [seerge/g-helper#2295]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I know that the performance mode can be automatically switched when on battery or plugged in.
Is it possible to distinguish between PD chargers and original chargers? I want it to help me automatically switch to different performance modes under different power supply modes.

My device is G14 2024, and when using the PD charger, the AC will tell me that I am using PD charging. So, I think that this feature may be achievable.

### Describe the solution you'd like

.

### Device and Model

Zephyrus G14 GA403UV

**Comment by seerge** [comment]
@JJVVVV hello, I was answering this already and I'm not a fan of that. As it will significantly complicate whole logic and make it very confusing for vast majority of users to understand.

It's already extremely easy to switch between modes using hotkeys (FN + F5 or Shift+FN+F5 to cycle modes backwards) and via UI.

If you really want some custom automation, you can do some Autohotkey script that would emit hotkey setting specific mode in each situation https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings

So sorry, but I don't plan that as it will cause more harm than good in most of the cases.
