### ISSUE TITLE
Delay in Screen Pad On/Off/Disconnect action

### ISSUE THREAD

**Issue by rollercoaster** [seerge/g-helper#2296]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Currently it is very hard to go directly from, say, On to Disconnected or to simply cycle back to current value if you accidentally press the screen pad mode change button. It is quote jarring when the button is pressed and even before you can read the toast notification, the screen flicker.

### Describe the solution you'd like

Can we please have a delay (just like the charge delay) that delays the action once the screen pad mode change button / shortcut is pressed? If we cycle back to the current stage then no action should happen.

### Device and Model

ASUS Duo 15 SE

**Comment by seerge** [comment]
@rollercoaster hello, it's very hard to understand what are you asking, but you already can set screenpad brighter or dimmer (up to completely turning it off) with a hotkeys as [explained in readme ](https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings)

``Fn + Shift + F7 / F8`` - Screenpad brightness Down / Up

So I don't think that anything else next to that needs to be added.

If you want a delay between settings - just press buttons less frequent.

**Comment by rollercoaster** [comment]
Thank you for your prompt reply. Yes, I am aware of the brightness shortcuts and they are great.

But I am talking about the this button:
![image](https://github.com/seerge/g-helper/assets/578962/cd5ca1d1-5d1a-4805-ab8c-86b7f15461dc)

The actions are:
Screenpad ON, Screenpad Hidden, Screenpad Disabled

Each time the button is pressed the mode changes. It would be really great if the action for this button is delayed (as is the default behaviour in the Asus's terrible apps)

**Comment by seerge** [comment]
@rollercoaster what is the purpose of the delay ?

**Comment by rollercoaster** [comment]
Reduces the windows rearrangement and resolution/positing/refresh-rate change of the screen(s)

The most common use case is to go from Screenpad On to Screenpad Disabled but we cant do that in the current functionality as it will rapidly go from On to Off to Disabled

Another use case is accidental press, when the screen is off. It would go from Disabled  to On to Off to Disabled. 

A delay allows the user to settle of a final state of the action and the action then happens only once.

**Comment by seerge** [comment]
@rollercoaster I don't think that adding artificial delay to a very simple action is a good idea. It will just give impression that application is laggy.

You can also do ``Shift`` + ``Screenpad`` to just toggle Screenpad on or off.

**Comment by rollercoaster** [comment]
The way I have see it working is:

1. You press the button
2. You see the notification on the screen to indicate the change
3. After a second the action occurs
4. if you press again before the action, it cancels the pending action and goes to step 2

 Shift + Screenpad does indeed work to turn Off but does not turn On the 2nd screen

**Comment by seerge** [comment]
@rollercoaster check if this build does toggle screenpad on ``Shift + Sreenpad`` hotkey
[GHelper.zip](https://github.com/seerge/g-helper/files/14761456/GHelper.zip)

**Comment by rollercoaster** [comment]
Yes that fixes Shift + Sreenpad toggle. Thanks!

I would still suggest adding the delay.

**Comment by seerge** [comment]
@rollercoaster delay is much more difficult to do, and it can be very confusing for people who didn't get used to it.

**Comment by rollercoaster** [comment]
ok, thanks for everything! Love the app.

**Comment by rollercoaster** [comment]
FYI, not meaning to push, but anyone using this app is coming from Asus software and that has the delay built in so it shouldn't really confuse anyone.
