### ISSUE TITLE
[Feature Request] Automatic / Built In Updates (Or update Notifications)

### ISSUE THREAD

**Issue by mokshmridul** [seerge/g-helper#23]
Request if we could have have a built-in updater, or at least some sort of in-app notifications for new releases.

**Comment by flemesre** [comment]
You can get GitHub to send you an email notification for every new release, using custom Watch notifications if you don't want to see other activity on the repository.

**Comment by lucidnx** [comment]
I would like to see this too :) some kind of auto-update as people (me) are somewhat lazy to update every software in PC manually... I understand it is a bit more code, but it will be nice :)

**Comment by seerge** [comment]
For now i have added a version display with a link to releases page 
Added in https://github.com/seerge/g-helper/releases/tag/v0.9.8

**Comment by gloatoriginal** [comment]
I downloaded the latest binary ~30 minutes ago, than saw you did a release! :D I found out about the release from testing the github release api, @seerge do you think there'd be a good amount of merit checking current version vs. installed version at startup and prompt user about an updated version?

**Comment by seerge** [comment]
Added in https://github.com/seerge/g-helper/releases/tag/v0.21

**Comment by gloatoriginal** [comment]
Awesome! thanks for the addition, I literally played with this most of my morning, thanks for the hard work man!

**Comment by seerge** [comment]
Actually, just noticed a bug in 0.21 preventing a correct version check ... and pushed 0.22 with a fix.
