### ISSUE TITLE
Visual modes on M16 2023 Mini-LED while HDR is on

### ISSUE THREAD

**Issue by Sontarr** [seerge/g-helper#2301]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I change the visual mode, the color temp or the gamut _while HDR is switched on_, the resulting colors don't look correct. Cinema is extremely blue, Eyecare very orange and the gamuts just look washed out.

Now I installed Armoury Crate to look up a few translations and noticed that the whole Game Visual section is not accessible while HDR is on. Uninstalled Armoury Crate directly afterwards.

I believe at least the M16 Mini-LED machines shouldn't be able to change visual mode, color temp and gamut while HDR is on.

![Screenshot 2024-03-26 214209](https://github.com/seerge/g-helper/assets/10485542/9675c1e0-ba82-4201-88c4-f34a10b46bde)

### How to reproduce the bug?

1. turn HDR on
2. try to change visual mode, color temp and gamut

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14764535/log.txt)

### Device and Model

Asus Zephyrus M16 2023 GU604VY

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.161

### OS

Windows 11 Home 23H2

**Comment by seerge** [comment]
@Sontarr ok, that's a valid reason

Try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14764797/GHelper.zip)

**Comment by Sontarr** [comment]
@seerge It works when changing HDR via Win+Alt+B hotkey and when the HDR is automatically switched on/off when switching from battery to plugged in and back. Will test the external monitor later.

It does however not always get the height difference in the windows right.

[log.txt](https://github.com/seerge/g-helper/files/14769640/log.txt)

![Screenshot 2024-03-27 083002](https://github.com/seerge/g-helper/assets/10485542/654421cb-c64d-4ecd-b99b-6688cda5106f)
![Screenshot 2024-03-27 082950](https://github.com/seerge/g-helper/assets/10485542/334e14ae-6f43-48e1-9429-16ee6c34e9f3)

**Comment by seerge** [comment]
@Sontarr this build should have label in a same size as disabled buttons, it should prevent resizing. But actually in my case it auto-resizes correctly every time anyway :) 

[GHelper.zip](https://github.com/seerge/g-helper/files/14770288/GHelper.zip)

**Comment by Sontarr** [comment]
@seerge Yeah, when I close and open the window, the height is adjusted, in the old build and the new. But if the window is already open while switching the mode, it gets bigger. Strange. Even with the new build.

![Screenshot 2024-03-27 100025](https://github.com/seerge/g-helper/assets/10485542/769c7a6b-eb73-45d6-a0cc-5f3e3e7b2376)

**Comment by Sontarr** [comment]
Just a short check: This doesn't happen with 0.161. Its new behavior.

**Comment by seerge** [comment]
@Sontarr what UI scaling in windows do you use ?

**Comment by Sontarr** [comment]
125%

**Comment by seerge** [comment]
@Sontarr can you check if this build helps ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/14770845/GHelper.zip)

**Comment by Sontarr** [comment]
It's still a little bit bigger when HDR is on, but only a few pixels. Almost unrecognizable. It's okay, I think.

125% or 150% doesn't make a difference.

**Comment by seerge** [comment]
@Sontarr alternatively I can just keep whole UI as is (i.e. show dropdowns), but just skip actual action if HDR is on

**Comment by Sontarr** [comment]
Its strange. If I move the mouse over the GPU mode buttons, the help text of the buttons is shown and the window shrinks a few pixels. 🤪

Sure, disabling the dropdowns is an option.

**Comment by seerge** [comment]
@Sontarr can you check if this build changes anything ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/14771112/GHelper.zip)

**Comment by Sontarr** [comment]
@seerge Perfect!

**Comment by seerge** [comment]
@Sontarr I have changed UI one more time, so label will appear just on top of visual modes dropdowns. It won't trigger form resizing at all, so should always look correct

Can you check if this build behaves correctly for you ?

[GHelper.zip](https://github.com/seerge/g-helper/files/14771558/GHelper.zip)

**Comment by Sontarr** [comment]
@seerge Yes, works fine. 

Came around to test it with an external monitor. Works as expected too. 👍

**Comment by seerge** [comment]
Great, thanks for testing. It's already live in 0.163

**Comment by THEBOSS619** [comment]
If possible, and if you don't mind. At least provide a way to keep visual modes available while still using HDR as I have some use cases where I need to use both features HDR and visual modes at the same time.

Obviously, Armoury Crate wouldn't allow this mode to happen, but previously, ghelper allowed it, and I would like to have this back.

**Comment by seerge** [comment]
@THEBOSS619 but do visual modes work for you if HDR is on? or it screws up colors as for @Sontarr ?

**Comment by THEBOSS619** [comment]
> @THEBOSS619 but do visual modes work for you if HDR is on? or it screws up colors as for @Sontarr ?

@seerge Yes, it does work for me and makes a difference in color tone while using both HDR and visual modes. It doesn't screw up color for me.

**Comment by seerge** [comment]
@THEBOSS619 this build should allow clicking on label (saying it's not available) to remove it and enable visual modes again

[GHelper.zip](https://github.com/seerge/g-helper/files/14776827/GHelper.zip)

**Comment by THEBOSS619** [comment]
> @THEBOSS619 this build should allow clicking on label (saying it's not available) to remove it and enable visual modes again
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14776827/GHelper.zip)

@seerge thank you so much! it works! and I love the idea too!

**Comment by seerge** [comment]
@Sontarr can you try if this build STILL detects HDR correctly on your device ?

[GHelper.zip](https://github.com/seerge/g-helper/files/14781854/GHelper.zip)

And post a log from it

**Comment by Sontarr** [comment]
@seerge It works.

[log.txt](https://github.com/seerge/g-helper/files/14787523/log.txt)

The change from plugged in to battery seems to take unusually long if the G-Helper main window is open. The OSD is there for nearly 10 sec. (Changing from Balanced to Silent, Standard to Eco, 240Hz to 60Hz, HDR Multizone to SDR Singlezone)

**Comment by seerge** [comment]
@Sontarr oke, thanks

Delay in UI is not related to changes anyhow :) just switching to Eco sometimes takes time, but this is how things work in bios

**Comment by seerge** [comment]
@Sontarr @THEBOSS619 all changes are live in 0.164
