### ISSUE TITLE
[Feature Request] Add Lock option for battery charge limit slider.

### ISSUE THREAD

**Issue by bullz32** [seerge/g-helper#2308]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

sometimes randomly bumping the cursor on the g-helper window change the battery charge limit. it is clearly a user error but would be very easily solved by a software feature.

### Describe the solution you'd like

a lock battery charge limit option in the form of a check box which would lock the battery charge limit unless toggled off.

### Describe alternatives you've considered

just the above, or perhaps an options to move the battery charge limit slider in the extra settings.

### Device and Model

Asus Zephyrus G15 GA503QM

**Comment by seerge** [comment]
@bullz32 hello. Honestly I don't really see much sense in it.

If you randomly click any element on main window, you will change some feature (disable GPU, change mode, backlight, etc). Adding protection for each UI element will make UI only more cluttered.

Sorry, but I don't plan to do this
