### ISSUE TITLE
Battery Charge Limit seeming not to work

### ISSUE THREAD

**Issue by Zolio** [seerge/g-helper#231]
I'm confused, once I downloaded this program my battery started charging up to 100%, usually its supposed to be stuck at 60% because I have that limit feature on in MyASUS but now it just doesn't work anymore and its going back up to 100%. Even when I set the battery charge limit at the lowest point in G-Helper i don't think it works properly because I usually have my computer on sleep or completely shut down so i'm not sure G-Helper can actually limit the battery in those circumstances, but just for piece of mind I would really like to see a toggle button that stops G-Helper from tampering with battery charge limits and battery altogether, so the MyASUS feature can work by itself.

**Comment by seerge** [comment]
Based on 0 reproduction info that you have provided (no logs / no model name / etc), despite being explicitly asked to honour developer's time - I'm not able to check this.

There is only 1 known endpoint that is being used to set battery charge limit. It could be that other asus services interfere and erase that setting, which is out of reach for the app.

**Comment by Zolio** [comment]
Oh i'm extremely sorry, I just joined this platform today so i wasn't sure how to do this correctly

**Comment by seerge** [comment]
You can also set battery limit manually in powershell (as admin)

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00120057, 80)
```

Where 80 is your desired limit. MyASUS / G-Helper and any other similar apps use this "method".

**Comment by Zolio** [comment]
Thank you so much for this! I'll try this out at 60%, I have the G15 G503RM, not sure if that changes anything at the moment but i'll put it there just in case :)

**Comment by Zolio** [comment]
Hey, um i'm really not sure if I did this correct but I ran Windows Powershell in administrator mode and changed the limit from 80 to 60, and it came up with this:

`Exception calling "DEVS" : "Generic failure "
At line:1 char:1
+ (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x001 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WMIMethodException
`

Is this because I have a G15? I have Windows 11 Home installed.

**Comment by Zolio** [comment]
Hey, I actually deleted MyASUS because i realized i never really used it for anything and now the battery limit works completely! I haven't seen it go above 60% at all in the past 12 hours which is really nice
