### ISSUE TITLE
Generate battery report when clicking on battery health

### ISSUE THREAD

**Issue by marcelomijas** [seerge/g-helper#2311]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I think it would be useful to click on "battery heath" that is, below the "100%" button on the main window and open a generated windows battery report usnig the `powercfg /batteryreport` (cmd) command, the output could be saved on the GHelper folder using `/output` and then opened using the default html viewer.

I'd like to do it myself, but I still lack C# knowledge, so I'll stick to translations. I've watched this project grow almost from the beginning, I'm amazed at how far it's come. Thanks developers!

### Describe the solution you'd like

Clicking on "battery status", i.e. below the "100%" button in the main window, should open a generated Windows battery report saved in the GHelper folder within AppData.

Newly generated battery reports should replace previous ones or include the date and time in the name.

### Device and Model

Asus Zephyrus G14 G401IV

**Comment by seerge** [comment]
@marcelomijas hello, that's a good idea. I was thinking about something like that as well.

This build should do the thing

[GHelper.zip](https://github.com/seerge/g-helper/files/14776952/GHelper.zip)

**Comment by marcelomijas** [comment]
@seerge hi. I just tested it. It works like a charm! Thanks!

**Comment by seerge** [comment]
Great

**Comment by Sontarr** [comment]
@seerge Should that already work in the latest build I got for the HDR testing?

`powercfg /batteryreport` normally saves in C:\Users\myusername\battery-report.html

When I click on battery health, G-Helper opens the Windows Explorer with C:\Users\myusername\Documents, but there is no battery-report.html. It isnt in %Appdata%\GHelper nor the installation directory of GHelper either. Where does it save that thing?

**Comment by seerge** [comment]
@Sontarr can you check in a log where powercfg saved report ?

**Comment by Sontarr** [comment]
🤦‍♂️ Of course....

Okaaay... thats the very full log where it failed:
[log.txt](https://github.com/seerge/g-helper/files/14787815/log.txt)

I then closed GHelper, deleted the logfile, opened GHelper again - and now it works:
[log1.txt](https://github.com/seerge/g-helper/files/14787822/log1.txt)

**Comment by seerge** [comment]
@Sontarr @marcelomijas 

This build should explicitly generate report in user home directory (no matter from where you run app itself)

[GHelper.zip](https://github.com/seerge/g-helper/files/14789076/GHelper.zip)

**Comment by mjishnu** [comment]
<img width="653" alt="image" src="https://github.com/seerge/g-helper/assets/83004520/b5e82d18-ac9b-4f01-9fec-522245810d0b">

[log.txt](https://github.com/seerge/g-helper/files/14814341/log.txt)

battery health report not saving, also its opening the document folder rather than the home (also not found in document folder).

**Comment by seerge** [comment]
@mjishnu try this build 
[GHelper.zip](https://github.com/seerge/g-helper/files/14814957/GHelper.zip)

**Comment by mjishnu** [comment]
> @mjishnu try this build
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14814978/GHelper.zip)

works correctly now. btw in my opinion rather than storing in home it would be better to store in document folder as its far more easy to access

**Comment by seerge** [comment]
@mjishnu i guess it's fine as is :) as home is always writeable at least
