### ISSUE TITLE
dGPU does not disable when on battery

### ISSUE THREAD

**Issue by SnowyNate** [seerge/g-helper#2313]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Despite having GHelper open in system tray and GPU mode being set to Optimized, upon unplugging the device, the dGPU still stays enabled (can be seen actively being used in task manager). If GHelper is fully open though (bringing up the app through clicking on the icon in the system tray), optimized mode works correctly and the dGPU disables when unplugged.

### How to reproduce the bug?

1. Have GHelper open but running in the system tray (not focused as an open window)
2. Unplug the device
3. In task manager, dGPU is still being actively used

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14780870/log.txt)

### Device and Model

ROG Flow X13 2022 (GV301RC-PH74)

### Additional information.

BIOS is updated to the lastest version (327). There are other bugs in addition to this (dGPU # consecutively increasing), which will perhaps be posted about in a separate issue later.

### Armoury Crate

Installed

### Asus Services

None

### Version

0.161.0

### OS

Windows 11 Home 23H2

**Comment by seerge** [comment]
@SnowyNate hello,

By briefly looking into your log i see that every time you unplug app runs Eco command, and it succeeds 

```
3/27/2024 4:24:03 PM: AutoSetting for Offline
....
3/27/2024 4:24:04 PM: Running eco command 1
3/27/2024 4:24:04 PM: GPUEco = 1 : OK
3/27/2024 4:24:05 PM: Eco flag : 1
3/27/2024 4:24:05 PM: Mux flag : 1
```

```
3/27/2024 4:21:38 PM: AutoSetting for Offline
...
3/27/2024 4:21:42 PM: Kill:Windows10Universal
3/27/2024 4:21:42 PM: Stopped: Windows10Universal
3/27/2024 4:21:42 PM: Running eco command 1
3/27/2024 4:21:43 PM: GPUEco = 1 : OK <-- Successful GPU OFF command
3/27/2024 4:21:43 PM: Eco flag : 1 <-- BIOS says it's OFF too
3/27/2024 4:21:43 PM: Mux flag : 1
```

So BIOS reports that it's completely off

Where do you see the GPU ? If it completely disappears from device manager,  it's gone.

**Comment by SnowyNate** [comment]
> @SnowyNate hello,
> 
> By briefly looking into your log i see that every time you unplug app runs Eco command, and it succeeds
> 
> ```
> 3/27/2024 4:24:03 PM: AutoSetting for Offline
> ....
> 3/27/2024 4:24:04 PM: Running eco command 1
> 3/27/2024 4:24:04 PM: GPUEco = 1 : OK
> 3/27/2024 4:24:05 PM: Eco flag : 1
> 3/27/2024 4:24:05 PM: Mux flag : 1
> ```
> 
> ```
> 3/27/2024 4:21:38 PM: AutoSetting for Offline
> ...
> 3/27/2024 4:21:42 PM: Kill:Windows10Universal
> 3/27/2024 4:21:42 PM: Stopped: Windows10Universal
> 3/27/2024 4:21:42 PM: Running eco command 1
> 3/27/2024 4:21:43 PM: GPUEco = 1 : OK <-- Successful GPU OFF command
> 3/27/2024 4:21:43 PM: Eco flag : 1 <-- BIOS says it's OFF too
> 3/27/2024 4:21:43 PM: Mux flag : 1
> ```
> 
> So BIOS reports that it's completely off
> 
> Where do you see the GPU ? If it completely disappears from device manager, it's gone.

That was probably after opening GHelper as a window and focusing it when I was troubleshooting the issue. I'll try to get screenshots of the issue and will report back.

**Comment by seerge** [comment]
It goes back up to 25th of May, in all cases when laptop was unplugged it has set Eco mode successfully as well

**Comment by SnowyNate** [comment]
> It goes back up to 25th of May, in all cases when laptop was unplugged it has set Eco mode successfully as well

Did you mean March? Also, that's very strange, as the issue literally occurred just a few minutes prior to posting the issue, and I was able to reproduce it multiple times- where GHelper states that the system is in eco mode but Task Manager still reports the dGPU as active. However upon further testing it seems that I (ironically) can't intentionally reproduce the issue anymore. If I do encounter the issue again, I'll reopen this issue with screenshots.

I've got another question for you on this topic: When switching GPU modes, why does the screen go dim for a bit and then brighten back up? I did not see this mentioned in FAQ, unless I am mistaken.

Also, for the other issue mentioned in additional information, would you like me to state it here or open it in another post? I have a feeling it may just be a regular windows bug/feature but would just like to confirm with you.

**Comment by seerge** [comment]
@SnowyNate what do you mean under "active in Task Manager" ? Can you post a screenshot ? Check device manager for available devices, as I have mentioned in a previous message.

I don't know why your screen goes dim :) it's not something G-Helper is setting or doing, it could be that if your internal display was driven by NVidia dGPU gets driven by iGPU after, drives or windows are doing something under the hood.

Or if you just see that during unplugging, it could be some windows setting to lower brightness on battery, etc. You can try to reset windows power plan https://github.com/seerge/g-helper/wiki/Troubleshooting#resetting-windows-power-plan-to-defaults , it often "heals" such window's things ...

**Comment by seerge** [comment]
Given that it says GPU 5(!?!) or GPU 8(!?) it looks more like some hiccup of a Task Manager itself, or may be nvidia drivers are acting. There is nothing I can do here for sure.

I would just suggest to do a clean driver reinstall using DDU, it often solves lots of problems as explained in https://github.com/seerge/g-helper/wiki/Troubleshooting

**Comment by SnowyNate** [comment]
> Given that it says GPU 5(!?!) or GPU 8(!?) it looks more like some hiccup of a Task Manager itself, or may be nvidia drivers are acting. There is nothing I can do here for sure.
> 
> I would just suggest to do a clean driver reinstall using DDU, it often solves lots of problems as explained in https://github.com/seerge/g-helper/wiki/Troubleshooting

As I expected, windows being windows lol.

Sure, I'll try that. It doesn't look like it can be done quickly though, so I'll run it eventually in my own time, since it isn't a GHelper-related issue. I just hope it doesn't cause anything further to act up, as there currently aren't any severe bugs besides the ones I mentioned and I'd hate to use something I'm new to and cause new issues to arise.

Thank you so much, especially for your quick responses, and a big thank you to you and all of the devs for creating GHelper- it saved me from sending in my laptop to ASUS repair for another month after many weeks of constant repair.
