### ISSUE TITLE
Visual mode on Z13

### ISSUE THREAD

**Issue by Xenomorphys** [seerge/g-helper#2315]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Good morning,
On the previous version, Visual Mode worked perfectly, in fact, it was a nice addition.
But since the last update, it no longer works.
And when I go to Armory Crate, I know how to change the Visual Mode. So it works and HDR is disabled. Even though I don't have HDR.

### How to reproduce the bug?

Go to GHelper, Visual Mode is disabled.

### Logs

Je n en ai pas

### Device and Model

Asus z13

### Additional information.

I installed Armory Crate but it is disabled. And the option under GHelper worked on the previous version.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.163.0

### OS

Windows 11

**Comment by seerge** [comment]
@Xenomorphys do you have this setting on in windows  https://www.reddit.com/r/Asustuf/comments/185msyp/comment/kbd1k7q/ ? It's known to mess up windows API (so windows says it has HDR ON confusing both g-helper and AC)

**Comment by Xenomorphys** [comment]
Ho m'y god...
Without you, I would never have known about this option!
Many thanks and above all, sorry for the inconvenience.

**Comment by seerge** [comment]
@Xenomorphys do you generally have HDR on your device ? If so can you run this build with HDR on and post a log from it ?

[GHelper.zip](https://github.com/seerge/g-helper/files/14781851/GHelper.zip)

**Comment by Xenomorphys** [comment]
The Z13 does not have HDR. But thanks 😉

**Comment by seerge** [comment]
@Xenomorphys well, still check that build please. It should allow Visual modes even if that setting in windows is turned ON
