### ISSUE TITLE
Add a link to the Chinese version in README.md

### ISSUE THREAD

**Issue by pasical** [seerge/g-helper#2316]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

For Chinese users who are not familiar with GitHub, it is difficult for them to find README_zh_CN.md, so I hope to add a link to the English README.

### Describe the solution you'd like

Just use this:  [中文版点这里](https://github.com/seerge/g-helper/blob/main/docs/README.zh-CN.md)

### Device and Model

-

**Comment by seerge** [comment]
@pasical I had it before on main page, just removed cause that readme became outdated.

I have re-added it again. Thanks

**Comment by pasical** [comment]
> @pasical I had it before on main page, just removed cause that readme became outdated.
> 
> I have re-added it again. Thanks

Thank you, have a nice day🥰
