### ISSUE TITLE
Color Correction

### ISSUE THREAD

**Issue by riyanshlunia** [seerge/g-helper#2319]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Whenever I switch from standard to ultimate the colours of the screen feel a bit off and this only happens when I use g-helper when I use armoury crate software the colours feel right when I swtich to ultimate mode although rest all is good but the colours feel a bit dull

### How to reproduce the bug?

Go to g-helper and switch to ultimate mode and after the restart the colours are visibly dull 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14783939/log.txt)

### Device and Model

ASUS TUF F15 FX507ZE

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.161

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@riyanshlunia hello, 

It could be that windows uses other color profile by default when you select Ultimate (as from windows standpoint it's "different" display) :) 

You may try to select some Visual modes (including Default) that would call AsusSplendid to assign correct color profile in windows settings.

**Comment by IceStormNG** [comment]
There are different color profile per GPU for all laptops that have a mux switch or advanced optimus. By default, ASUS has already configured them so they should work. If you have re-installed windows, you have to manually assign them to the display first, because splendid will not configure the native profiles.

**Comment by seerge** [comment]
@riyanshlunia PS also you can turn OFF this setting in windows https://github.com/seerge/g-helper/wiki/FAQ#my-display-colors-seem-off-even-if-i-set-visual-mode-to-default

**Comment by riyanshlunia** [comment]
I just switched to ultimate mode again and now the colors seem to look perfectly fine without applying any of the above steps soo it's like it sometimes work doesn't also when yesterday the same happened I already tried switching the visual mode to default but nothing was changed

**Comment by riyanshlunia** [comment]
And about the setting you mentioned in the above article I don't see it on my device rn though I am sure I've seen it before when I just bought my laptop id
![Screenshot 2024-03-29 061638](https://github.com/seerge/g-helper/assets/72033389/1c02571f-29eb-4e75-b680-8471f8799de2)
k what is exactly happening

**Comment by seerge** [comment]
@riyanshlunia i’m glad it’s all good now
