### ISSUE TITLE
GPU Fan Curve changes to custom fan curve when applying power limits

### ISSUE THREAD

**Issue by Diego-JRH** [seerge/g-helper#2321]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When "Apply Power Limits" is checked manual fan curves are used instead of default ones, at least on the GPU fan.
Apply custom curves is unchecked.

### How to reproduce the bug?

Check "Apply Power Limits" box
GPU curve can be modified and fan will follow it even with custom fan curve option disabled.
Unchecking "Apply Power Limits" box will set fan curves to default again.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14787782/log.txt)

### Device and Model

Asus ROG Strix Scar 18 G834JY

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.163

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@Diego-JRH hello, it does, but it's by design.

Unfortunately many models require both power limits and fans to be applied together in order to make them work. As this is how AC sets Manual mode (you can't set only fans or only limits).

So G-Helper would also set fans next to it to make power limits work.

**Comment by Diego-JRH** [comment]
Oh I see. I thougt it was a bug because it didn't do it in the previous versions (or I didn't noticed)

**Comment by Diego-JRH** [comment]
Maybe they don't. I just assumed they were working. The max i've seen the CPU draw was 130 W in turbo mode. I didn't check if when applying a lower limit, It will respect that limit. If now it work as intended then it's fine.

**Comment by seerge** [comment]
@Diego-JRH oke, then I assume everything is as it should be already :)
