### ISSUE TITLE
Allow users to bind custom shortcuts to invoke Ghelper.

### ISSUE THREAD

**Issue by SulfurAcid** [seerge/g-helper#2322]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Yes, I hope it would be possible to add a feature to quickly open the Ghelper menu by custom hotkeys input by the user. Some third-party keyboards cannot change the key positions of hotkeys. While using a hotkey remapping tool is also a solution, it would be even better if such a function was built into the program itself!

### Describe the solution you'd like

Add custom shortcuts in Extra -> Key Bindings to open the main interface of Ghelper.

### Describe alternatives you've considered

Using Other Shortcut Key Mapping Programs

### Device and Model

ASUS TUF Gaming F16 FA607PI

**Comment by seerge** [comment]
@SulfurAcid hello, this is already possible by setting key in the config.

Please check readme https://github.com/seerge/g-helper/wiki/Power-user-settings#toggle-performance-mode-or-toggle-app-window-key-binding :)

Good luck
