### ISSUE TITLE
Fans are controlled, but only temporarily

### ISSUE THREAD

**Issue by Boneseiur** [seerge/g-helper#2326]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I own an ASUS Vivobook K3400PH with 8 gigs of 3200 MHz RAM, an i5-11300H and an NVDIA 1650 with 4 Gigs. My laptop ran some recent games i.e., Days gone, Uncharted 5, RE4 Remake at decent frames (50+ on medium settings) for around 6 months, and all was going good and then My laptop ran into a problem where the whole system would lag for around 3-12 seconds, and no inputs would be registered. I tried installing win 11 again, and it ran well for around 2 months and the issue persisted. I think it might be overheating, but I had my thermals checked at a warranted service center, replaced my thermal paste, cleaned fans but to no avail. I found that using G-Helper worked to a great extent, but I would have to alt-tab any application (Video editing, photoshop, games) every 2 MINUTES to ensure that G-Helper brings my fans back to high speeds, as my fans would basically go to sleep once I run my main application for 2 minutes plus, and the lag would ensure again. My laptop rejects any and all fan curves, and the service centres refuse to acknowledge my issue... Is there anything I can do with G-Helper to maintain/ lock my fans onto a certain speed?

### How to reproduce the bug?

1. Launch an application
2. Wait for the lag (usually in 10 mins at around 78°C )
3. Alt-tab to G-Helper to click on the apply custom curves (The fans ramp up, but only temporarily)
4. Come back to application to start work/ Gaming 
5. Issue repeats after 2 minutes

### Logs

-

### Device and Model

Asus Vivobook K3400PH OLED

### Armoury Crate

Never installed

### Asus Services

5

### Version

0.164

### OS

Win 11 Pro, 22H2

**Comment by seerge** [comment]
@Boneseiur hello, please check FAQ. [G-Helper doesn't control your fans in realtime anyhow](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds), they are controlled by BIOS. 

Since you have ignored template issue, and didn't upload log, I can't even say if you use a custom fan curves or default.

If you want to try a separate experimental build with manual fan control ,check this topic https://github.com/seerge/g-helper/discussions/2272

Thanks
