### ISSUE TITLE
[Bug] Cannot put fan to OFF in fan profiles v0.51

### ISSUE THREAD

**Issue by marcelomijas** [seerge/g-helper#233]
**Describe the bug**
v0.51 makes impossible to put the fan OFF in fan profiles (either CPU or GPU), when I drag a circle down, it drags until 2000RPM, not OFF, in version 0.50 I can do that.

If you set fan to OFF in v0.50, the profile is still working on v0.51 until you try to change it, then is impossible to put it back OFF.

**Clear scenario to Reproduce**
    Use GHelper 0.51
    In fan profiles, try to drag a circle down to OFF.

**Expected behavior**
The circle should reach the OFF height.

**Screenshots or screencasts**
This is the minimum I am able to reach.
![imagen](https://user-images.githubusercontent.com/62946623/231435206-001cb710-a12f-4377-98df-372ea2417bac.png)

**Desktop (please complete the following information):**

    OS: Windows 10 22H2
    Laptop model: ROG Zephyrus G14 GA401IV

**Asus software**

    Asus System Control Interface V3

**Comment by seerge** [comment]
@marcelomijas good one! thanks for quick testing :) Fixed and reuploaded again to [0.51](https://github.com/seerge/g-helper/releases/tag/v0.51)

**Comment by marcelomijas** [comment]
Thanks @seerge . Is working now.

Also, another thing, GitHub doesn't show a Bug issue template (I had to reuse the template from one of the bugs I posted before). These are the options that GitHub gives me:

![imagen](https://user-images.githubusercontent.com/62946623/231438884-ae7bae4b-0293-4da7-a147-f81efd2c800a.png)

**Comment by seerge** [comment]
@marcelomijas great

I have edited bug report template, reminding people to post more info / logs and apparently messed up with formatting :) it should be back now. Thanks again.
