### ISSUE TITLE
Full Screen App mouse pad on/off shortcut not working

### ISSUE THREAD

**Issue by Trodenn** [seerge/g-helper#2331]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

In my case, whenever a full screen app such as a video game is open; the Fn + "mouse pad key" F10 does not turn off the mouse pad. Instead, I see only "on" pops out despite repeatedly pressing Fn + F10 

### How to reproduce the bug?

1. Start a Full Screen app with mouse pad ON
2. Try to turn off mouse pad in game or in the Full Screen app
3. You should see it staying on "ON" despite repeated pressings 

### Logs

29/03/2024 15:51:42: Brightness = 32 : 0
29/03/2024 15:51:43: Key: 32
29/03/2024 15:51:43: Brightness = 32 : 0
29/03/2024 15:51:43: Key: 32
29/03/2024 15:51:43: Brightness = 32 : 0
29/03/2024 15:51:43: Key: 32
29/03/2024 15:51:43: Brightness = 32 : 0
29/03/2024 15:51:43: Key: 32
29/03/2024 15:51:43: Brightness = 32 : 0
29/03/2024 15:51:43: Key: 32
29/03/2024 15:51:43: Brightness = 32 : 0
29/03/2024 16:00:45: Key: 107
29/03/2024 16:00:45: Touchpad status:1
29/03/2024 16:00:47: Key: 107
29/03/2024 16:00:47: Touchpad status:1
29/03/2024 16:00:51: Key: 107
29/03/2024 16:00:51: Touchpad status:0
29/03/2024 16:11:22: HID Device Event: Checking for new ASUS Mice
29/03/2024 16:11:24: HID Device Event: Checking for new ASUS Mice
29/03/2024 16:40:50: C:\WINDOWS\system32\DriverStore\FileRepository\asussci2.inf_amd64_f2eed2fae3b45a67\ASUSOptimization\AsusSplendid.exe 13 0 50
29/03/2024 16:40:50: UIGain: 1.000000 lutDcModeScale: 1.000000 Interval: 1.000000 RDLevels: 5.000000 index: 0.250000 Param: 26, Gamut mode: FFFF Gamut mapping process exit with return code 0 HIT: ulOutBuffer[0] = 512 > 0 this->BiosDataStatus  = 0   ReadResult  = 0  Parsing version = 7 Use Method = 1   bios size = 49 CCTAPI_ERRORCODE = 0 ; HIT: DEF Gain E(0) W(0) ; HIT: Warm Gain E(0) W(0) ; HIT: Cold Gain E(0) W(0) ; HIT: RdW Gain E(0) W(0) ; HIT: RdS Gain E(0) W(0) CCT_Init  result = 0 ; HIT: GetGvModeLut() HIT: ulOutBuffer[0] = 512 > 0 ; HIT: Get bios[297]: 32  scale: 1.000000, Scale TH: 0.100000, nIndex: 26 New ScaleTH: 0.203922 New scale: 1.000000 outlut: [1.000000, 0.960784, 0.988235]
29/03/2024 17:06:08: Key: 174
29/03/2024 17:06:08: Mode = 1 : OK
29/03/2024 17:06:08: Power Mode 00000000-0000-0000-0000-000000000000 -> ded574b5-45a0-4f42-8737-46345c09c238:OK
29/03/2024 17:06:09: Key: 174
29/03/2024 17:06:09: Mode = 2 : OK
29/03/2024 17:06:09: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK

### Device and Model

Asus Zephyrus G15 GA503QR (2021)

### Additional information.

Haven't tested on other full screen games or app, but I was in Hell Divers 2

### Armoury Crate

Uninstalled

### Version

0.161.0

### OS

Windows 11 Home 23H2

**Comment by seerge** [comment]
@Trodenn hello,

This is due to windows permissions. It just doesn't allow to show some windows on top of everything (i.e. fullscreen games). You will see a notification if you would run game in maximized window tho

I can not overcome that. As to gain full access app needs to 
- be signed with a special certificate (bought for a lot of money)
- launched as admin
- located in "trusted" folder (i.e. Program Files or so)

I don't have a certificate, as this is non-commercial and free project. So it will be like that for now

Thanks and sorry

**Comment by Trodenn** [comment]
oi, no need for sorry!  I love this project! it's being a marvelous experience to use this. Thanks for the prompt reply and explanation.
