### ISSUE TITLE
Disc usage spikes after opening ghelper 

### ISSUE THREAD

**Issue by AZTRA081** [seerge/g-helper#2332]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

So before using or even opening ghelper my disc usage on idle is always 0% 
And I’m sure of it. Checked every time. 
but after I open it my disc usages always spikes to 7% repeatedly. 

### How to reproduce the bug?

Just opening up ghelper causes the Issue

### Device and Model

ASUS ROG STRIX G513

### Additional information.

..

### Armoury Crate

Uninstalled

### Asus Services

0 

### Version

0.161.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@AZTRA081 hello, I have already [answered you on reddit](https://www.reddit.com/r/ZephyrusG15/comments/1bqw2fh/comment/kx591cj/?context=3). If the only process causing disk activity is SYSTEM - that's just some regular windows activity.

I see that you have also demonstratively ignored issue template, and didn't upload logs. Without that it's impossible to assist you further.

**Comment by seerge** [comment]
@AZTRA081 Do you have Ambient mode toggled on ? Cause that measures your screen color by making mini-screenshots every now and then (same as similar mode in AC does)

**Comment by AZTRA081** [comment]
No. I just use the rainbow mode or just static sometimes

**Comment by seerge** [comment]
@AZTRA081 upload a log from the app as it was asked please.

Also does quitting g-helper (by clicking on Quit button) change your disk activity ?

**Comment by AZTRA081** [comment]
[log.txt](https://github.com/seerge/g-helper/files/14807996/log.txt)

**Comment by AZTRA081** [comment]
I've tried quitting the app and the disc usage stays the same but 
If I restart the system without g helper it goes away. 
But right after I open it again, it's back

**Comment by seerge** [comment]
@AZTRA081 I have checked into your log, and app literally does nothing after you set some settings there. It just stays absolutely inactive in system tray - so it doesn't cause any even hypothetical system activity.

When you quit app - its literally stopped, it's not even running.

If system is doing some activity - it's doing it independently form G-Helper. It could be some antivirus activity, or search indexing, etc. I simply can't change anything there, as it's not the app causing that.

**Comment by AZTRA081** [comment]
okey thanks for confirming my doubts btw i got these just in case
![Screenshot 2024-03-30 011820](https://github.com/seerge/g-helper/assets/165415457/2458304e-a167-4455-834f-71b51d66237b)

**Comment by AZTRA081** [comment]
![Screenshot 2024-03-30 012207](https://github.com/seerge/g-helper/assets/165415457/2b526b56-b46d-452a-b599-2abf0fe4051a)

**Comment by AZTRA081** [comment]
could this be any kind of armoury crate process causing this issue?

**Comment by seerge** [comment]
@AZTRA081 select Disk tab in ``Resource Monitor`` and check process there, form screenshot it's just windows writing it's own logs there. 

You can open Windows Event Viewer app and actually check those logs, to see what is there and if there is something repeating there very often

**Comment by AZTRA081** [comment]
![Screenshot 2024-03-30 012625](https://github.com/seerge/g-helper/assets/165415457/9b8d9bf5-2406-43b7-9cb8-871ab371c6b0)

**Comment by seerge** [comment]
@AZTRA081 i don't know :) just check if there are some event that appears like every couple of seconds? (reflecting your disk activity)

On Resource monitor sort disk activity by Total or Write (to see what file gets most writes from system)

**Comment by AZTRA081** [comment]
![Screenshot 2024-03-30 013735](https://github.com/seerge/g-helper/assets/165415457/c60b329e-261e-4095-a539-6c95d5b6c071)

**Comment by seerge** [comment]
@AZTRA081 i see a bunch of people had similar problem to yours (they are obviously not using g-helper)

https://forums.tomshardware.com/threads/system-process-is-constantly-writing-after-windows-10-last-update.3540651/#post-21479972

https://forum.cockos.com/showthread.php?t=178736

May be try to manually run System Maintentnace tasks (to let windows do it's things)?

**Comment by seerge** [comment]
@AZTRA081 also you can run some things from troubleshooting section

Like repair corrupt files https://github.com/seerge/g-helper/wiki/Troubleshooting#repair-corrupted-system-fails 
or rebuild WMI https://github.com/seerge/g-helper/wiki/Troubleshooting#rebuilding-wmi-repository

As I have no idea what exactly causes your system to write to c:\Windows\System32\config\SOFTWARE , but probably some hiccups in windows itself

**Comment by AZTRA081** [comment]
Okeyy Ill try these tomorrow and let you know if there's any difference...
If nothing changes I'll try downloading armoury crate again and see if it still happens 🫠
Anyway thank you so much for the help! 
I'm not really good with pc related things like these..

**Comment by seerge** [comment]
@AZTRA081 ok, it's up to you. Good luck

I'm closing this as there is nothing I can do here anyway besides googling and advising .

**Comment by seerge** [comment]
@AZTRA081 btw, did you uninstall AC using it's own official uninstall tool, correct ?

**Comment by AZTRA081** [comment]
Yup 
Should I try using Revo uninstaller to remove armoury crate again and reg left overs with it?

**Comment by seerge** [comment]
@AZTRA081 no, that's not needed. You don't need to turn  off anything in BIOS, just stopping services is enough to prevent AC popup (as one of them runs it)

**Comment by AZTRA081** [comment]
Ok👍
I had the same issue last year when I used G helper and at that time I couldn't pinpoint what was causing this issue. And I kept using my laptop like that until I took it to an authorised service centre for a quick cleanup. I don't know exactly what happened, but that day I give them my laptop for the cleanup and they came back, saying it had some kind of blue screen of death issue.. and my laptop kept restarting itself after every blue screen. I was really confused because I was using that laptop every single day without any single issue and at the time I also had this disk usage spike. it took them a month to fix that, but they ended up replacing the whole motherboard. so after that, I haven't gone to any service centre to fix anything🥲. but then after a few months, I decided to reinstall G helper and I saw this disk usage again and out of curiosity I just disable G helper from start-up and restarted. And it was gone..... I'm not saying that G helper is causing this issue..
I'm just worried if any kind of armoury crate process is left behind after the uninstall.

**Comment by AZTRA081** [comment]
![image](https://github.com/seerge/g-helper/assets/165415457/ec063764-250b-4b21-975f-2caac3e68f3d)

**Comment by AZTRA081** [comment]
Reinstalled armoury crate 
Now it's back to normal🫠
Ig I'll just stick with this for now..

**Comment by AZTRA081** [comment]
Ok so it's got nothing to do with g helper. It happens right after I uninstall armoury crate

**Comment by seerge** [comment]
@AZTRA081 cause it's something with windows itself. It was obvious that it has nothing to do with G-Helper cause it was happening even when you QUIT application 

I would appreciate if you would update all your reddit posts, as that simply scares random people.
