### ISSUE TITLE
Battery Limit not working

### ISSUE THREAD

**Issue by luqspy** [seerge/g-helper#2334]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The battery limit that I set within G-helper is not functioning. It always goes beyond that. I've already disabled all the asus services, and I've checked if any are still active. I have also checked the customization.ini file and set the value manually to 80 aswell.
![Screenshot 2024-03-30 022741](https://github.com/seerge/g-helper/assets/165427018/e4db7891-aa45-4b93-8949-9fbfc55ed5c3)

### How to reproduce the bug?

1. Go to ghelper.
2. Set the charge limit to 80
3. Plug in the charger
4. The charge crosses the limit

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14808477/log.txt)

### Device and Model

Asus TUF F15 FA507ZV4

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.161.0

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@luqspy hello, from log i see that app sets 80 limit every single time. 

Does the limit work if you would set it in MyAsus (so keeping asus services running) ? :)

**Comment by luqspy** [comment]
I have uninstalled the My Asus app. Are you suggesting to reinstall that and try from there?
Also, I recently used a debloat script from an app called bloatnosy. Could that have caused this?

**Comment by seerge** [comment]
@luqspy well, you try it with MyASUS. Cause you also say that 
> I have also checked the customization.ini file and set the value manually to 80 aswell.

And if both Asus Optimization Service (responsible for battery limiting) and G-Helper set limits, and it's not being honored - it could be something wrong with the device itself ignoring that.

**Comment by luqspy** [comment]
It still went beyond 80%. Do you think the debloat script could have caused this, cause it messed a little with my file explorer aswell.
here is my customization.ini
![Screenshot 2024-03-30 025136](https://github.com/seerge/g-helper/assets/165427018/a9f555fe-f7a1-4404-944d-ca4d33ee5f79)

**Comment by seerge** [comment]
@luqspy i have no idea what exactly the script did :) But if it still doesn't work, it means it's not G-Helper's fault.

You can try to reinstall Asus System Control interface https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-asus-system-control-interface

And hardware reset https://github.com/seerge/g-helper/wiki/Troubleshooting#hardware-reset--cmos-reset

If both won't help - I don't know what to suggest.

**Comment by luqspy** [comment]
Didn't work. I will use the media creation tool and start anew. also, I got this while installing the inteface driver,
![Screenshot 2024-03-30 025923](https://github.com/seerge/g-helper/assets/165427018/cfcda493-2556-4591-9431-fbb18762ca5b)
should that be concerning?

**Comment by seerge** [comment]
@luqspy you can try to download Asus Control interface from Updates section :) (but generally it should be same file)

**Comment by seerge** [comment]
@luqspy any updates  ?

**Comment by luqspy** [comment]
I'm sorry for the delayed reply. I used media creation tool to reinstall windows. I tried it once again, but sadly it didn't work.

**Comment by seerge** [comment]
@luqspy ok. Then it's probably some malfunction on hardware level in your device. Cause if even after fresh windows reinstall (with all drivers) it doesn't work with both MyASUS / Asus Optimization Service and G-Helper - it means it doesn't work at all :)

I'm sorry, but this is not related to G-Helper. Therefore closing.

**Comment by luqspy** [comment]
Yes, that seems to be the case. Thankyou for your help.

**Comment by codrutd** [comment]
start it once with elevated rights, it fixed the issue on my side
it used to stop smart charging once I started GHelper and to get it back I would open MyAsus set to Instant Full-Charging then back to Battery Care Mode, but now all OK

Asus software is not stopping NVidia but keeps it idle which adds at least 10W of usage

Amazing job with GHelper, thank you!
