### ISSUE TITLE
Backup / Restore settings

### ISSUE THREAD

**Issue by tsumaru720** [seerge/g-helper#2335]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Upon rebooting my laptop, it seems that G-Helper has forgotten all of my previous settings even though its been fine for a few weeks. I've been unable to debug if this is related to G-Helper/My laptop BSOD or a conflict with Armoury Crate, but not entirely relevant for this feature request

### Describe the solution you'd like

As mentioned, It seems that G-Helper has forgotten all of my previous settings. It'd be a nice feature to have where I can export my settings once I get them how I like, and then if G-Helper forgets them, I can simply import the file again instead of tuning all the sliders to get back to what I want

### Device and Model

ASUS Laptop ROG Zephyrus G14 GA402XZ

**Comment by seerge** [comment]
@tsumaru720 hello, G-Helper already has 2 layered config writing for a backup. If both configs failed, it means something really wrong happened with system so it has erased or corrupted config file.

You can manually copy ``%appdata%\GHelper\config.json`` somewhere, and then restore it :) That would be your backup / restore settings.
