### ISSUE TITLE
Ability to disable Game Visual

### ISSUE THREAD

**Issue by VinhCastle** [seerge/g-helper#2338]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

After applying Game Visual, my screen became something purple-ish in default neutral mode. So right now I can't go back to the "default white" I used to have before using Game Visual.

### Describe the solution you'd like

Add a function to disable/uninstall Game Visual

### Device and Model

G14 2022

**Comment by seerge** [comment]
@VinhCastle hello, 

Visual Modes are set by asus own ``AsusSplendid`` utility, as color profiles in the system. Setting mode to "Default" should set settings back to normal using official color profile from asus for your panel (same as it happens with AC). So there is nothing to "uninstall" next to that.

If you are want to use other color profiles you can do the following

1. Reset color profiles in Windows Color Management app back to whatever you want
2. Check your GPU control panel (i.e. Nvidia control panel or AMD Adrenaline) and reset color settings there, mb just drag some gamma up / down to reset, or select / unselect "color deficiency correction" in AMD
3. Uncheck [this setting as explained in FAQ](https://github.com/seerge/g-helper/wiki/FAQ#my-display-colors-seem-off-even-if-i-set-visual-mode-to-default)

If you want to hide Visual Modes from UI you can also do that https://github.com/seerge/g-helper/wiki/Power-user-settings#visual-modes-section

Thanks

**Comment by seerge** [comment]
@VinhCastle hello,

I have recently discovered how Armoury can completely disable Game Visual by calling `AsusSplendid.exe` (responsible for it) and added it to G-Helper as new "Disabled" Visual Mode.

It is live in latest release https://github.com/seerge/g-helper/releases/tag/v0.196

Let me know if it changes something for you
