### ISSUE TITLE
Battery charge limit not enforced after a restart

### ISSUE THREAD

**Issue by satvikmaurya** [seerge/g-helper#234]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**

I've configured G-helper to limit the battery charge at 80%. However, I noticed that after restarting the system, the battery starts charging beyond 80% even though G-helper has been configured to run on start-up. The last time this happened, the battery had reached 98% and it said "plugged in". When I opened G-helper and moved the slider back and forth, the "plugged in" message disappeared and the battery stopped charging beyond 98%.

**Clear scenario to Reproduce**
- restart the system
- Monitor battery levels, move battery charge slider and see the battery stop charging.

**Expected behavior**
G-helper should enforce the battery charge limit in all cases, even after the system has restarted.

**App Logs**
Attached log.
[log.txt](https://github.com/seerge/g-helper/files/11213398/log.txt)
Scroll down to 9:55pm on April 11. That's when the system was restarted. I noticed the battery had charged to 98% even though the battery limit was at 80% on G-helper at around 12:34am on April 12.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 2020 G14 (GA401ll)

**Asus software**
- No Armory Crate installed
- No MyASUS installed
- Only Asus optimization service running in the background.

**Additional context**
I have tried re-installing MyASUS since that's what I used for limiting the battery charge before. I noticed that that too did not work in enforcing the battery charge level after a restart.

**Comment by seerge** [comment]
@satvikmaurya hello :)

I see in logs that app on each start (including when it's launched on autostart) sends a limit  command (and even gets a 1 (OK) as response from bios / asus wmi driver). So it actually works as it should on the app level.

```
11-Apr-23 9:55:09 PM: App launched
11-Apr-23 9:55:09 PM: AutoSetting for Online
11-Apr-23 9:55:09 PM: BatteryLimit = 80 : OK
```

You can also set battery limit manually in powershell (as admin)
```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00120057, 80)
```
Where 80 is your desired limit. MyASUS / G-Helper and any other similar apps use this "method".

If still doesn't work - i can't do much to help :))
You say that MyASUS also doesn't work for you, mb your bios is acting by some reason? 

Side tip: It's not related to g-helper anyhow: but you can try to do a cmos reset : turn off laptop normally, press and hold power button for 30-40 seconds, then turn it on again as usual (it will take some time to boot)

**Comment by satvikmaurya** [comment]
@seerge Thanks for the tips! I've tried the manual method via powershell, let's see if that works (it should persist regardless of reboots right?). 

I'll close this for now, and update you in case there are other developments. Thanks!

**Comment by seerge** [comment]
@satvikmaurya - it should :) but same as myasus or g-helper's setting should (as they literally pull same string)
