### ISSUE TITLE
Disabling Asus services and pressing Fn+F6

### ISSUE THREAD

**Issue by BrightenedDay** [seerge/g-helper#2340]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Whenever i press Fn+F6 the screen flickers (mostly stays black), i hear a single error sound at the start and i either get lucky and it stops or i have to restart my device. I keep accidentally clicking it because it's next to the f7 key.

### How to reproduce the bug?

1. Stop Asus services
2. Press F6 or Fn+F6 (whatever works for you)

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14813004/log.txt)

### Device and Model

TUF Gaming F15 FX506HE

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.164.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@BrightenedDay hello,

``Fn+F6`` on old devices is supposed to turn screen off.

If you have Asus optimization service running - app would leave this hotkey to it, so it's not being involved

When it's not running it does what it's supposed to do. Calls Windows API method to turn  screen off. 
The only known way to do that is this https://stackoverflow.com/questions/713498/turn-on-off-monitor. And app does it.

If it doesn't work in your case, I'm afraid I can't really change much

**Comment by seerge** [comment]
@BrightenedDay I have only one small idea to test with this Screen Toggling

Let me know if this build changes anything
[GHelper.zip](https://github.com/seerge/g-helper/files/14813067/GHelper.zip)

**Comment by seerge** [comment]
@BrightenedDay did you try the build ?

**Comment by BrightenedDay** [comment]
I'll have to try it when i get back. Thanks for looking into this. :D

**Comment by BrightenedDay** [comment]
@seerge Whatever you did, it works! It's not perfect since i see the screen before it switches to the windows background thingy. But it no longer breaks. Thanks! But does this mean i should avoid updating ghelper or will it be included in the next update anyway? :D

**Comment by seerge** [comment]
@BrightenedDay yes, its already live in 0.165
