### ISSUE TITLE
Rog Ally Controller Disable Function Vanishing

### ISSUE THREAD

**Issue by Krodity** [seerge/g-helper#2341]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When using ghelper on the rog ally hooked to an external display, the function to disable controllers seems to vanish randomly without warning, happens after a short period of time, tried on separate ally’s both with and without armoury crate completely disabled, even uninstalled. 
![Screenshot_2024-03-30_115506](https://github.com/seerge/g-helper/assets/99015020/62f1f025-6b5e-4cbc-a073-9534d04efb07)

### How to reproduce the bug?

Connect rog ally to external display

set to only output to external

disable controller within ghelper

then the option will just vanish after resuming regular operation for a short period 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14813085/log.txt)

### Device and Model

ROG Ally Z1 Extreme

### Armoury Crate

Uninstalled

### Asus Services

0 but have tried with all of them 

### Version

Been an issue since function was added 

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Krodity i think it has to do something with windows scaling form incorrectly

Try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14813102/GHelper.zip)

**Comment by Krodity** [comment]
At first look seems to have fixed it, will continue for a couple hours then close if no issues further, thank you very much kind sir

**Comment by seerge** [comment]
Ok, great
