### ISSUE TITLE
Keyboard Not fully lit when using heat and ambient modes

### ISSUE THREAD

**Issue by Prince11592** [seerge/g-helper#2344]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Laptop Make and Model: Asus Strix SCAR G634JZR(2024 Model) 

The keyboard backlighting on my Asus Strix SCAR G634JZR isn't fully illuminated in the heatmap and ambient modes. Any assistance in resolving this would be appreciated.

### How to reproduce the bug?

changing to heatmap and ambient

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14816187/log.txt)

### Device and Model

Rog Strix SCAR G634JZR

### Additional information.

![20240331_193820](https://github.com/seerge/g-helper/assets/120901070/ee437d2e-838f-46c5-860c-035dd44bb066)

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.164

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@Prince11592 hello, as I understand only 3 arrow keys are not lighted ?

It looks like they use different key-codes on your device comparing to other per-key-RGB models

Unfortunately, I have to guess codes, as I don't have actual device ...

Can you check this build, if it lights up any of the missing arrows ?
[GHelper.zip](https://github.com/seerge/g-helper/files/14816377/GHelper.zip)

**Comment by Prince11592** [comment]
Still the Same, Except for the Heatmap and Ambient modes, the keyboard backlight works fully in all other modes.

**Comment by seerge** [comment]
@Prince11592 ok, and this ?

[GHelper.zip](https://github.com/seerge/g-helper/files/14817112/GHelper.zip)

**Comment by Prince11592** [comment]
Only UP arrow key backlight is missing
![20240401_010537](https://github.com/seerge/g-helper/assets/120901070/675d139d-4af1-49f1-bc9e-5fb1166f7a3b)

**Comment by seerge** [comment]
@Prince11592 try this

[GHelper.zip](https://github.com/seerge/g-helper/files/14817478/GHelper.zip)

**Comment by Prince11592** [comment]
still same, backlight for up arrow still not working in the above build for the Heat map and ambient

**Comment by seerge** [comment]
@Prince11592 ok, can you try this one instead ?
[GHelper.zip](https://github.com/seerge/g-helper/files/14821956/GHelper.zip)

**Comment by Prince11592** [comment]
working perfectly :)

**Comment by seerge** [comment]
@Prince11592 great! I will include it in next release, thanks for testing

**Comment by Prince11592** [comment]
HI @seerge LID led are not working in Heatmap and Ambient mode
Static mode
![20240415_103146](https://github.com/seerge/g-helper/assets/120901070/b3249474-d77d-4f45-8df8-341ed98a39ec)
Heatmap and ambient mode
![20240415_103153](https://github.com/seerge/g-helper/assets/120901070/48817991-3cd3-4fc0-8790-e7b622fa75d6)

**Comment by Prince11592** [comment]
In the 0.164 build, he resolved the keyboard issue for SCAR 16.

**Comment by seerge** [comment]
@Prince11592 if missing keys is something I could guess at least, then guessing a missing LID led id - is unrealistic without actual device :) so you will have to use it as is.

**Comment by Prince11592** [comment]
It is perfectly working in all modes except in heat map and ambient mode.

**Comment by Prince11592** [comment]
Any guide how to find the led id, i will try to find it.😊

**Comment by seerge** [comment]
@Prince11592 @xSimone 
Check if thuis build makes any difference 

[GHelper.zip](https://github.com/seerge/g-helper/files/14994858/GHelper.zip)

**Comment by Prince11592** [comment]
Still same..
