### ISSUE TITLE
Microphone indicator not showing up when clicked microphone on/off button

### ISSUE THREAD

**Issue by BfoAnims** [seerge/g-helper#2345]
When I first got G-Helper it was working correctly, i would click the microphone toggle and it would show up on screen as an indicator saying muted/unmuted, but for some reason it doesn't anymore. The fan mode switch button still has indicators though (turbo, silent, balanced)

I should add that the microphone toggle still works, there's just no indicator.

**Comment by seerge** [comment]
@BfoAnims please upload logs and other details as it was explicitly asked in issue template

**Comment by BfoAnims** [comment]
Okay I'm gonna open another issue sorry
