### ISSUE TITLE
ROG Ally, Armoury Crate button shows GHelper AND Armoury Crate installer :-(

### ISSUE THREAD

**Issue by dragonlordelite** [seerge/g-helper#2349]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi, pressing Armoury Crate button on ROG Ally opens Both Armoury Crate installer & GHelper. How i remove Armoury Crate totally ? How i fix this issue please ? Thx for help.

### How to reproduce the bug?

clicking AC button.

### Logs

i don't got log

### Device and Model

ROG ALLY Z1 EXTREME

### Armoury Crate

Uninstalled

### Asus Services

just AURA & Asus Hotplug are installed, i must remove em ?

### Version

last

### OS

Win11

**Comment by seerge** [comment]
@dragonlordelite you can do that by reading FAQ https://github.com/seerge/g-helper/wiki/FAQ#how-do-i-stop-the-armoury-crate-install-popup-appearing-every-time-i-press-the-m4--rog-key

**Comment by dragonlordelite** [comment]
pb solved : i went in GHelper parameters & stopped ASUS services. Works fine Now :)

should i uninstall all ASUS ? (ASUS Hotplug & Noise Cancelation.... i keep MyASUS soft for updates...)

just own ROG ALLY since 1 month...

**Comment by dragonlordelite** [comment]
> @dragonlordelite you can do that by reading FAQ https://github.com/seerge/g-helper/wiki/FAQ#how-do-i-stop-the-armoury-crate-install-popup-appearing-every-time-i-press-the-m4--rog-key

thx Seerge !! TY for great software !! :-D
