### ISSUE TITLE
Mute button (M3) for microphones

### ISSUE THREAD

**Issue by Raychan87** [seerge/g-helper#235]
First of all. Thanks for the great tool. Top work from you. This is exactly how the original tool from Asus should have been.

I would have simple if it is possible. On the G14 (2021) is the M3 button for muting the microphone. But about the extras is missing the possibility to set the one. Would be very happy.

**Comment by seerge** [comment]
@Raychan87 hello, by default that is handled by Asus Optimization service (that also handles all other main hotkeys) :)

It's a bit of a duplicate from https://github.com/seerge/g-helper/issues/210

**Comment by Raychan87** [comment]
Oh, I hadn't seen that. 

Thank you very much.
