### ISSUE TITLE
Does not open

### ISSUE THREAD

**Issue by AldrineG** [seerge/g-helper#2350]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I tried running GHelper after having to restart my laptop and it doesn't run at all. It does not appear in Task Manager or any where else I tried looking. It worked perfectly before restarting my laptop. The log files or from the last time I was able to use GHelper.

### How to reproduce the bug?

1. Run GHelper

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14818398/log.txt)

### Device and Model

Asus Zephyrus G14 GA401QM

### Armoury Crate

Never installed

### Version

0.164

### OS

Windows 11

**Comment by Kikimahe** [comment]
Hi 
It may be blocked by the intelligent application control (smartscreen), and the pop-up for "Run Anyway" does not appear. 

Right-click on Ghelper.exe and see if you have a checkbox to allow Ghelper.
Or temporarily disable Smartscreen before running Ghelper.exe

**Comment by seerge** [comment]
@AldrineG hello, can you check Windows Event Viewer for a possible crashes mentioning GHelper.exe and post details here? And if you don't have any - just re-download app again, and right click on it and click unblock as explained in Requirements. 

Cause it looks more like some windows / defender hiccups.

**Comment by AldrineG** [comment]
Description: A .NET application failed.
Application: GHelper.exe
Path: C:\Users\agatp\Downloads\GHelper.exe
Message: A JSON parsing exception occurred in [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.17\Microsoft.WindowsDesktop.App.runtimeconfig.json], offset 0 (line 1, column 1): The document is empty.
Invalid framework config.json [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.17\Microsoft.WindowsDesktop.App.runtimeconfig.json]

**Comment by seerge** [comment]
@AldrineG looks like .NET is broken on you system 

Try to download and install it again
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.407-windows-x64-installer

**Comment by AldrineG** [comment]
I reinstalled .NET and it still does not open.

Description: A .NET application failed.
Application: GHelper.exe
Path: C:\Users\agatp\Downloads\GHelper.exe
Message: A JSON parsing exception occurred in [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.17\Microsoft.WindowsDesktop.App.runtimeconfig.json], offset 0 (line 1, column 1): The document is empty.
Invalid framework config.json [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.17\Microsoft.WindowsDesktop.App.runtimeconfig.json]

Here is the most current Event Log.

**Comment by seerge** [comment]
Similar situations https://github.com/seerge/g-helper/issues/978 https://github.com/seerge/g-helper/issues/727

**Comment by AldrineG** [comment]
After reinstalling and repairing .NET, GHelper works perfectly!
