### ISSUE TITLE
About the customer key with “Win” key

### ISSUE THREAD

**Issue by unstoppable-xiaobai** [seerge/g-helper#2352]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

An interesting problem happened when I hoped to use the "M4" key to replace the action of "Win+L" in order to lock the computer, and I used the key-combination of "0x5B 0x4C", it didn't work correctly and just output the letter "l" in the textbox;
however, when I used the combination of "0x5B 0x52" ( the action of "Win+R"), the run windows appeared correctly.

the reason that I don't use the function of "Toggle Screen" is that it is useful to shut down the screen, but some shrink of the screen happens when I unlock my laptop. 

### How to reproduce the bug?

None.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14819708/log.txt)

### Device and Model

Rog Zephyrus M16 GU604VI

### Armoury Crate

Uninstalled

**Comment by seerge** [comment]
@unstoppable-xiaobai hello, 

I have checked and it's indeed the case 
- ``Win + R`` ("0x5B 0x52") launches Windows Run app
- ``Win + L`` ("0x5B 0x4C") doesn't lock screen

But actual key **is emitted**. You can check that with https://keyboardchecker.com/ for example

Most probably it's some internal windows protection from abuse, that doesn't allow lock screen from software hotkey :)
I can't change this unfortunately, as actual code works. Thanks

![Screenshot 2024-04-01 113251](https://github.com/seerge/g-helper/assets/5920850/2fde21eb-1ef4-4a90-b09d-d53a69a2ba54)

**Comment by unstoppable-xiaobai** [comment]
Thanks for your patience answer!

After asking for help from Microsoft with no satisfactory answer just now, a new idea popped up and is sufficient.

We can create a .bat file for our mission(for me is just "rundll32 user32.dll,LockWorkStation"), and then link to the custom key in G-helper, and we could reach our goal  :）

**Comment by seerge** [comment]
@unstoppable-xiaobai that's possible, try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14823309/GHelper.zip)

**Comment by seerge** [comment]
@unstoppable-xiaobai changes live in 0.165
