### ISSUE TITLE
Microphone indicator not showing up when clicked microphone on/off button

### ISSUE THREAD

**Issue by BfoAnims** [seerge/g-helper#2354]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I first got G-Helper it was working correctly, i would click the microphone toggle and it would show up on screen as an indicator saying muted/unmuted, but for some reason it doesn't anymore. The fan mode switch button still has indicators though (turbo, silent, balanced)

I should add that the microphone toggle still works, there's just no indicator.

### How to reproduce the bug?

1 Click microphone toggle button (M3)

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14822921/log.txt)

### Device and Model

ROG Strix G16 G614JU

### Armoury Crate

Uninstalled

**Comment by seerge** [comment]
@BfoAnims hello, I see that you have Asus Optimization service running. When it's running it handles hotkey by default, so app doesn't interfere. Just ``stop`` it from ``Extra`` and then G-Helper will handle hotkeys instead.

```
9.03.2024 12:37:29: Optimization service is running
```

Thanks

**Comment by BfoAnims** [comment]
Thank you! I can't believe it was that simple. Is there a way I can disable it on startup though?

**Comment by seerge** [comment]
@BfoAnims disabling service will stop it from startup. It was running cause either you or windows update has updated asus drivers and restarted it again.
