### ISSUE TITLE
Power limits reset randomly

### ISSUE THREAD

**Issue by skipster1337** [seerge/g-helper#2355]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I set the CPU power limit in the Fans + Power menu (20w for example), it works for a period of time then seems to reset back to default as seen in Afterburner's CPU power usage. The power limit can last from around five minutes to an hour, but it will eventually reset (I believe this is a BIOS related issue, reapplying the "stock" power settings at random, other apps like UXTU circumvent this by setting a reapply timer).  
Also the slow boost limit doesn't do anything because it gets set to the same value as the sustained limit as seen in the log. It's possible to set a separate boost limit through other apps, such as UXTU and Renoir Mobile Tuning, so it should be possible to implement it in G-helper as well.
![image](https://github.com/seerge/g-helper/assets/91155070/f3af114c-221b-4811-b518-4ba376f94c35)

![Untitled2](https://github.com/seerge/g-helper/assets/91155070/8f60f5c2-19dc-45fb-9c0f-d81e9279e101)

### How to reproduce the bug?

1. Go to Fans + Power and set a power limit (20w in this case)
2. Wait for some time
3. The power limit will reset and the system will continue consuming more power than set in the limit

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14823272/log.txt)

### Device and Model

ASUS TUF A15 FA506IU

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.164.0

### OS

Windows 10 22H2

**Comment by seerge** [comment]
@skipster1337 hello, try this build

Since you have a very old device, it doesn't support power limits in an "asus"-way, same as other models. So app already sets them in a same way as UXTU does.

It will re-apply power limits, but it will use existing re-apply timer from Advanced section (so you need to check it there)

[GHelper.zip](https://github.com/seerge/g-helper/files/14823544/GHelper.zip)

**Comment by skipster1337** [comment]
Okay, this is better. Now STAPM and slow boost get set correctly. It would also be great to have fast boost and duration sliders too, but that's picky of me.
![2024-04-01 15_59_06-](https://github.com/seerge/g-helper/assets/91155070/cc39878b-564f-4b6c-a144-6e92797680e9)
Though there doesn't seem to be an auto-reapply timer in the advanced section for some reason.
![2024-04-01 16_01_11-Fans and Power - AMD Ryzen 7 4800H with Radeon Graphics](https://github.com/seerge/g-helper/assets/91155070/e0fbe251-6931-4ff7-b01c-1a0966e34654)

**Comment by seerge** [comment]
@skipster1337 STAPM is SPL (so you have it). As for other - I don't want to overcomplicate it 

Can you check if this build works correctly, I have made few cleanups here 

[GHelper.zip](https://github.com/seerge/g-helper/files/14823742/GHelper.zip)

**Comment by seerge** [comment]
@skipster1337 default reapply timer is 30 seconds, but you can override that with in config.json

```
"reapply_time" : 30,
```

**Comment by skipster1337** [comment]
Hmm, there's no such option in the config, should it be added manually?

**Comment by skipster1337** [comment]
Ok, this should work. I set a 25w limit on the cpu and limited the frequency + undervolted my gpu so this poor old laptop doesn't burn up before I get to repaste it lol  
Thanks a lot!
