### ISSUE TITLE
Changing keyboard backlight mode doesn't work for ASUS ROG Zephyrus G16 GU603ZV

### ISSUE THREAD

**Issue by JTribiani** [seerge/g-helper#2357]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

 ASUS ROG Zephyrus G16 GU603ZV has only white backlight (my model) and modes like: static, breathe and etc dont working (but they r working from armory crate).
But in Extra tab, laptop backlight is working and it's changes the backlight intensity.

### How to reproduce the bug?

Try to use the feature on ASUS ROG Zephyrus G16 GU603ZV 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14823946/log.txt)

### Device and Model

ASUS ROG Zephyrus G16 GU603ZV 

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.164

### OS

win 11 pro

**Comment by seerge** [comment]
@JTribiani hello, did you check this FAQ section https://github.com/seerge/g-helper/wiki/FAQ#backlight-doesnt-change-color-or-stays-blue ?

**Comment by pasical** [comment]
I had the same problem. You should change the back light setting in Windows settings.

**Comment by nicebear1999** [comment]
> @JTribiani hello, did you check this FAQ section https://github.com/seerge/g-helper/wiki/FAQ#backlight-doesnt-change-color-or-stays-blue ?

problem solved! Thanks!

**Comment by seerge** [comment]
@JTribiani any updates ?

**Comment by JTribiani** [comment]
Thanks for your help, turning off the settings in Windows did not help. The
situation is as follows:
1. Ghelper can control the backlight intensity, but changing the mode does
not work
2. Armory crate can control the mode, but the intensity does not work
3. Windows can't control anything

ср, 3 апр. 2024 г. в 10:50, Serge <
***@***.***>:

**Comment by seerge** [comment]
@JTribiani try to set color to pure RED. Do modes change after that ?

**Comment by JTribiani** [comment]
yes,  mode changes, tnx for help

**Comment by seerge** [comment]
@JTribiani ok. It's a known "bug" of single-color keyboards. They require only first byte from RGB to be set, rest should be zero. That's why red color works.

Your model (GU603ZV ) mostly exists as RGB version so I can't "hardcode" it in the app anyhow, as it will break behavior on other devices. 

So just keep color red and it be fine.
