### ISSUE TITLE
Ambient Mode is not changing the keyboard color

### ISSUE THREAD

**Issue by silentman04** [seerge/g-helper#2359]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The color of the keyboard is not changing when I set to Ambient Mode. It only changes to just 2 colors, either the color from Static Mode or Yellow. 

### How to reproduce the bug?

1. Start with Setting to Static Mode (any color of choice example blue). Change to Ambient Mode or Heatmap Mode. The keyboard takes up the same color as what was set in Static Mode.

2. From any other mode (except GPU Mode) to Ambient Mode or Heatmap Mode, the keyboard takes up color from Static Mode. 

3. If during any of the above two steps, I select GPU Mode and then move to Ambient or Heatmap Modes, the color always defaults to Yellow unless I chose Static Mode again after which the Ambient and Heatmap Modes take up the color from the Static Mode.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14826234/log.txt)

### Device and Model

Asus Zephyrus M GU502GU_GU502GU

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

0.146

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@silentman04 try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14826274/GHelper.zip)

**Comment by seerge** [comment]
@silentman04 hello. Flicker is not from recalculation :)

Your device is quite old, and simply doesn't support real-time color changes - reason why heatmap/ambient didn't work at all before.

I have replaced realtime-color command, with just setting a "static" color mode with a new color each time as a fallback. So it's better than nothing.

Unfortunately I can't offer anything more

**Comment by silentman04** [comment]
I understand. The model is quiet old. But still works surprisingly well with G-Helper. Thank you so much for supporting older models like mine. I appreciate the quick responses and your explanation for the fix!
