### ISSUE TITLE
Wrong max rpm G531GW

### ISSUE THREAD

**Issue by Lewenhaupt** [seerge/g-helper#236]
I just switched to this app on my G532GW because armoury crate is absolute shit. However it seems this is hard capped at 5800 RPM. Armoury crate was able to get the Cpu fans up to 7000 RPM.
However, it does seem like this might just be a visual bug with with the editor because the fan starts spinning faster.

**Comment by seerge** [comment]
You can either set fans to max, and then it will recalibrate or i can hardcode 7000 somewhere in next builds

**Comment by Lewenhaupt** [comment]
No need, just wanted to confirm that it was just visual.

**Comment by seerge** [comment]
Real scale is actually same as in armory (i.e. 0 - 100%), app just tries to show correct labels on Y-axis based on max RPM i knows

**Comment by Lewenhaupt** [comment]
Makes sense! Thanks for the quick reply 😊
