### ISSUE TITLE
Hotkey not working

### ISSUE THREAD

**Issue by riyanshlunia** [seerge/g-helper#2364]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The hotkeys combination of FN+C, intended to activate the function lock on the ASUS TUF F15 laptop, is not functioning as expected. Additionally, other hotkey combinations for alternate functions are also not working as intended. This issue affects the usability and efficiency of the device, hindering the user experience.

### How to reproduce the bug?

Press the FN key located on the keyboard.
While holding the FN key, press the C key to activate the function lock.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14834858/log.txt)

### Device and Model

ASUS TUF F15 FX507ZE

### Additional information.

In addition to resolving the hotkey malfunction, we propose the implementation of a new hotkey combination, such as FN+V, for seamless switching between visual modes on the ASUS TUF F15 laptop. This feature would enhance user convenience, allowing swift adjustments to display settings for different usage scenarios, such as gaming, productivity, or multimedia consumption.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.164

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@riyanshlunia hello,

Your device simply don't support those hotkeys and you didn't have them in Armoury Crate neither. 

They don't emit any code.

FN+C is supposed to emit WMI-event ``158`` in a log
FN+V - ``138``

They are absent in a log. So I can't do anything about that.

You can bind any of the macro-keys via ``Extra`` to toggle FN-lock or Visual Modes instead

**Comment by riyanshlunia** [comment]
I read this article https://github.com/seerge/g-helper/wiki/Power-user-settings#extra-keybindings but I am unable to understand that how do I set the custom hotkeys for visual mode like their's no fn+v combination in extra panel how do I set fn+v to change the visual modes

**Comment by seerge** [comment]
@riyanshlunia you can't. As I just explained that hotkey is not supported by your hardware. It does nothing.

**Comment by riyanshlunia** [comment]
Alright thank you
