### ISSUE TITLE
USB-C charging implementation is suboptimal for battery health

### ISSUE THREAD

**Issue by CursedDog19** [seerge/g-helper#2366]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I use my laptop with a USB-C charger and the charge limit set to 80%. When the battery reaches 80%, the battery does not stop charging. Instead, the device alternates between draining the battery and utilizing 90 watts of wall power to charge the battery back up every minute or so. This full blast charge/discharge loop is suboptimal for battery health, because it puts unnecessary strain on the battery.

### How to reproduce the bug?

Device: 2022 M16 with G-Helper
Anker 317 or similar PD2.0 100W charger with E-marker cable
Set Charge Limit to 80%

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14841626/log.txt)

### Device and Model

Asus Zephyrus M16 GU603ZM

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.164.0

### OS

Windows 11 Home 22H2

**Comment by Sontarr** [comment]
... that's true, my M16 2023 works the same way, but I was always under the impression it is just the way the device works. Nothing related to G-Helper. Or is it?

**Comment by seerge** [comment]
@CursedDog19 hello, charging is handled by BIOS/firmware, it has absolutely nothing to do with G-Helper. 

Thanks.

**Comment by seerge** [comment]
@Sontarr  > ... that's true, my M16 2023 works the same way, but I was always under the impression it is just the way the device works. Nothing related to G-Helper. Or is it?

It's how the device works :) In 2024 model they have finally added proper pass-through for USB-C charging, but only if your device actually consuming less than 100w or something like that. So you can't really "game" on USB-C still
