### ISSUE TITLE
7735hs undervolting support

### ISSUE THREAD

**Issue by Nerd9d** [seerge/g-helper#2368]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I have seen that ghelper permits cpu undervolting on 2023 g14 models featuring the 7940hs. However my 2023 g14 comes with a 7735hs and ghelper doesn't provide me with the option to undervolt my cpu.

### Describe the solution you'd like

If possible, i would like to see cpu undervolting support for 2023 models featuring the 7735hs in ghelper.  In the case that my suggestion cannot be implemented due to technical limitations, i would like to know more regarding said technical limitations if possible that is. Your help here is most appreciated 

### Device and Model

Asus Zephyrus G14 GA402NU

### Additional information.

<img width="506" alt="image" src="https://github.com/seerge/g-helper/assets/165822760/210819bc-6ed7-456a-8725-affdf8c8a9f7">

**Comment by seerge** [comment]
@Nerd9d hello, Ryzen 7 does not support undervolting. It's locked .

Please check this thread https://github.com/seerge/g-helper/discussions/736 people have tried that and reported that it's not working, therefore it's hidden from the UI

Thanks

**Comment by Nerd9d** [comment]
I see. Thanks for the info
