### ISSUE TITLE
Battery charge limit not working anymore

### ISSUE THREAD

**Issue by LeyendaV** [seerge/g-helper#2370]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Charge limit was working flawlessly till, literally, yesterday. Now, although I've set a battery charge limit to 60%, it's now charging till 100%.

![image](https://github.com/seerge/g-helper/assets/7258518/e8421abb-5c7d-4bc7-aedd-7ca6724eb7a9)

### How to reproduce the bug?

1. Set a charge limit of 60%.
2. Plug your laptop.
3. Let it charging.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14846189/log.txt)

### Device and Model

ASUS TUF Dash F15 FX517ZM

### Additional information.

My configuration is already set according to [this](https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working), it was like that when the charge limit was working, and still is like that now that it suddenly stopped working.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.164.0

### OS

Windows 11 22H2

**Comment by Kikimahe** [comment]
Hi, 

The Asus Optimization service was running.
`02/04/2024 17:01:32: Optimization service is running`

This service uses the My Asus settings for the charge limit which are saved in this file:
`C:\ProgramData\ASUS\ASUS System Control Interface\AsusOptimization\customization.ini.`

If 100% is save in customization.ini, Ghelper charge limit will not work.

You should always stop the ASUS Optimization service `extra`

**Comment by seerge** [comment]
@LeyendaV hello, please read FAQ https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working 
Your question is covered there

You can also set charge limit in MyASUS app and use asus services.

Thanks

**Comment by LeyendaV** [comment]
@seerge As I mentioned in my op, that was the case both before and after encountering the problem, so that's not what's causing the issues.

@Kikimahe I don't use nor have MyASUS installed. ASUS services were killed and then they re-enabled themselves. Literally, the only single change in my laptop was updating GHelper to the latest version (164, I was still on 157).
But even then, I killed the services again before encountering this problem.
I'll monitor the charging behavior today.

**Comment by Kikimahe** [comment]
Unfortunately, every time you install an ASUS driver, ASUS services are reactivated. 
Maybe that's what happened.

I cross my fingers for you. ;-)

**Comment by seerge** [comment]
@LeyendaV it's not connected with app update anyhow. Asus Control Interface was probably updated by windows update itself, and re-enabled asus services. And by default they would set limit to 100% (unless other value is set in myasus or in ``C:\ProgramData\ASUS\ASUS System Control Interface\AsusOptimization\customization.ini`` directly :)
