### ISSUE TITLE
Battery limit not working properly on Asus TUF Dash F15 FX517ZM

### ISSUE THREAD

**Issue by PhanTinhKhang** [seerge/g-helper#2372]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Battery limit not working until i g-helper startup, which take a moment. When the laptop booting and waiting for me to login windows, the battery limit not working, so it keeps charging and fill up to 100%. Sometimes when i play game, the red light often turns red although the battery is above the limit.

### How to reproduce the bug?

1. Booting the laptop, the red light shows that the battery is charging.
2. When G-helper not startup yet, the battery also keeps charging.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14847041/log.txt)

### Device and Model

Asus TUF Dash F15 FX517ZM

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

Latest

### OS

Windows 11

**Comment by Kikimahe** [comment]
Hi, 

This is how the charge limit works.

Please read the[ FAQ.](https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working)
_"Keep in mind - after each restart, BIOS resets all settings to defaults, including charge limit. As soon as you log in and G-Helper starts it would apply charge limit again. Before app starting - your laptop may keep charging. This is normal and this is how things are"._

**Comment by PhanTinhKhang** [comment]
So i wonder why battery limit by Myasus working even though it booting

**Comment by Kikimahe** [comment]
The bios also continues to charge at startup with My ASUS :) 
But My Asus has a Windows service (Asus Optimization service) that starts on Windows before user login.

G-Helper has no service, it's just 1 executable file that starts after user login. 

If you connect after startup, the difference in charging is only a few seconds between the 2 ;-)

**Comment by seerge** [comment]
@PhanTinhKhang hello, as @Kikimahe answered already. Charge limit is applied as soon as app starts. Asus service starts faster cause it is service, and run's before user login

You can force app to launch a bit faster by adjusting setting mentioned in FAQ
https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working

Thanks
