### ISSUE TITLE
GPU constantly running despite "stopped all applications" / no applications running

### ISSUE THREAD

**Issue by Wailamm** [seerge/g-helper#2373]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi Serge, after I updated to latest stable version, I've noticed my GPU is constantly running despite there's no application/software that uses GPU which leads to high power draw when unplugged. 

Step/Things that I've tried:

- install an older version of G-helper
- tried running software that use GPU (AutoCAD, Lightroom, Photoshop), click "Stop GPU Applications", it does stop, however GPU still running despite no software is open.

Above are the things I've tried. Do refer to the attached screenshots and logs for your action.

<img width="695" alt="Screenshot 2024-04-03 145818" src="https://github.com/seerge/g-helper/assets/165879089/bf4b9cc3-acf3-4854-83ea-c959d53841ad">

### How to reproduce the bug?

N/A

### Logs

[G14_log.txt](https://github.com/seerge/g-helper/files/14848027/G14_log.txt)

### Device and Model

Asus Zephyrus G14 GA401IV_GA401IV

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.164.0

### OS

Windows 11 22H2

**Comment by Wailamm** [comment]
Hi @seerge, I've rolled back an older version of NVIDIA driver and now it's working properly. Thanks for helping, appreciated it!

**Comment by seerge** [comment]
@Wailamm glad you have sorted it out
