### ISSUE TITLE
Support .net 8/9

### ISSUE THREAD

**Issue by TOWUK** [seerge/g-helper#2375]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I install sdk .net 8 and ghelper needed 7.0+

### Describe the solution you'd like

Just support newest .net core or sdk

### Device and Model

Tuf gaming a15 2023 FA507XI

**Comment by seerge** [comment]
@TOWUK hello, currently G-Helper depends on .NET7. I may consider moving to other versions somewhere in the future, but not now as it will force lots of existing users to update.

**Comment by TOWUK** [comment]
> @TOWUK hello, currently G-Helper depends on .NET7. I may consider moving to other versions somewhere in the future, but not now as it will force lots of existing users to update.

maybe just add support 7/8/9 version? and next long time next to newer version .NET?

**Comment by ChaseGrant** [comment]
Just as a note ... as of today .NET 7 is out of support.
