### ISSUE TITLE
Function lock doesn't toggle airplane mode (F12)

### ISSUE THREAD

**Issue by aadish151** [seerge/g-helper#2377]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Function lock doesn't work with F12. It works with all other secondary functions (F1-F11).

Expected behavior: When function lock is on, pressing F12 once should toggle airplane mode

Actual behavior: When function lock is on, pressing F12 once doesn't toggle airplane mode. Need to hold down the function button to toggle airplane mode

### How to reproduce the bug?

1. Turn on function lock in G-helper
2. Press F12

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14856259/log.txt)

### Device and Model

Asus Zephyrus G14 GA401IV

### Additional information.

https://github.com/seerge/g-helper/assets/43163551/6061c5f4-0a11-4379-8926-97f63ba8dcd8

Added a video showing actual behavior with all function keys (Didn't show F11 as it's for sleep). Used keyviz for keystroke indicator.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.164

### OS

Windows 10 22H2

**Comment by seerge** [comment]
@aadish151 hello. 

It's a software fn-lock. App just registers F1-F11 as own hotkeys in windows and processes corresponding actions on click
F12 is **reserved** by windows and can't be used a hotkey for any apps.

So that's not possible to change.

Thanks
