### ISSUE TITLE
Key bindings explanation

### ISSUE THREAD

**Issue by manciuszz** [seerge/g-helper#238]
I find the 'Key Bindings' section in the 'Extra Settings' to be obscure. 

What is an M3, M4 keys? Are they mouse keys - Mouse3, Mouse4? 

I don't seem to have such keys on my laptop, furthermore what does 'action' in the input field's placeholder even mean? 
Did you want to not repeat yourself, so instead of copy/pasting `notepad /p "file.txt"`, you simply left it as 'action' ? or are they different?
If I don't have support for such keys, why are they being displayed? I'd assume they are key bindings for a few specific ASUS devices only, so displaying them there when they serve no purpose outside that scope makes no sense to me. Moreover, do these keys rely on 'ASUSOptimization.exe' ? If so, a user that deleted this service, won't be able to use these key bindings regardless, so why display them?

Anyways, there's a lack of clarity over this specific feature of the app, the capabilities and etc., that I'd thought someone had to point out.

---
EDIT: A bit off-topic, but don't want to create a new issue for this.

The tooltip message gets cut-off, which isn't really a big deal, but I had to point it out.
![image](https://user-images.githubusercontent.com/2539661/231801388-0158421d-032f-4386-a9b2-04276c3df963.png)
Furthermore, I'd like to mention that users with high resolution displays such as 1440p and higher might have issues viewing 'Fans and Power' section graphs and legends. The font is a bit too small.

**Comment by manciuszz** [comment]
Tooltip looks good
![image](https://user-images.githubusercontent.com/2539661/231837550-d516eb17-aef9-474f-a939-fcf3531089b9.png)
No idea what 'help icon' your talking about.
![image](https://user-images.githubusercontent.com/2539661/231837972-1ffa256c-fcd9-43d3-9020-f6fe577cd6be.png)

**Comment by manciuszz** [comment]
I can see the icon now 👍 
![image](https://user-images.githubusercontent.com/2539661/231839736-ff02b014-d70a-4141-8ee8-d443586587de.png)

Since we are on topic of the UI...

![image](https://user-images.githubusercontent.com/2539661/231839533-1775bf16-bd39-4eb5-a84b-430a79ed24a9.png)
I'm just nitpicking at the moment, but consider standardizing the UI elements. The buttons doesn't follow same style and are sort of misaligned.

**Comment by seerge** [comment]
Because on the right - it's not a button, it's a windows native checkbox with some paddings and colored background. Customizing those elements is a big pain in general. It's not as easy as web stuff ....

**Comment by manciuszz** [comment]
I understand your pain. Honestly, it doesn't change the functionality of the app, so it doesn't really matter. It was just something that caught my eye the first time I opened window and I found it ugly when everything else is sort of neat and tidy :)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11225191/GHelper.zip)
I have aligned some buttons, but for example when you want to re-align default checkbox (run on startup) with own label - you can ask microsoft to fix :)

**Comment by manciuszz** [comment]
I appreciate the effort :) Fans + Power looks a bit better now, unfortunately the rounded corners on that button still doesn't make it perfect, but whatever.

The new 'help icon' sort of pushed the UI elements to the left unintentionally.
![image](https://user-images.githubusercontent.com/2539661/231847361-0ba288f8-3a0f-467d-bb5d-1d113967e3ef.png)

**Comment by seerge** [comment]
Ok, great, I will made few more minor ui tweaks and push it as 0.52. Thanks
