### ISSUE TITLE
I hope to be able to provide hotkeys for graphics card mode.

### ISSUE THREAD

**Issue by 00susu00** [seerge/g-helper#2384]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Direct connection of a dedicated graphics card to many games greatly helps with the frame rate

### Describe the solution you'd like

I really hope developers can add the option to enable direct connection of the dedicated graphics card with the shortcut Ctrl+B

### Describe alternatives you've considered

I originally hoped to customize the hotkeys to achieve this purpose, but it's clear that it cannot be done

### Device and Model

ROG Flow X16 GV601RW

**Comment by seerge** [comment]
@00susu00 hello, what do you understand under

> enable direct connection of the dedicated graphics card

?

If you want to switch between Eco and Standard with a hotkeys it’s already possible 

https://github.com/seerge/g-helper#%EF%B8%8F-keybindings

**Comment by seerge** [comment]
If you want to bind other hotkeys to do same thing, you can just remap them to ``Ctrl + Shift + Alt + F14 / F15`` using Authotkey or Sharpkeys or similar app.

**Comment by 00susu00** [comment]
"I apologize for any misunderstanding in my expression. I hope to add a hotkey for switching to 'Ultimate' mode, instead of toggling between 'Standard' and 'Eco' modes.

**Comment by seerge** [comment]
@00susu00 Ultimate mode requires restart and user confirmation for that.

Therefore there is no o sense to bind it to hotkeys

**Comment by 00susu00** [comment]
"English is not my native language, so my expression may not be very clear."

**Comment by 00susu00** [comment]
"I know, and I hope to be able to perform all operations through the keyboard to avoid using the mouse to open the panel."
