### ISSUE TITLE
Integrated Display Not Detected After Unplugging External Monitor on ASUS M16 2022

### ISSUE THREAD

**Issue by Teodor5rov** [seerge/g-helper#2385]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The problem started when I was shutting down the laptop and closed the lid then immediately disconnected the external monitor. Then after a while when I turned on the laptop (without the external monitor) the laptop's internal display failed to turn on, despite the system seemingly running Windows normally. So I went back and connected the external display and the laptop was working fine except only on the external display and the internal display is undetected. The problem is that even the boot screen and the bios are on the external display, almost as if the internal display is non-existent. But, here comes the weird part: when I switch to "Ultimate mode" and restart everything goes back to normal and works as it should and the bios is on the correct screen.

### How to reproduce the bug?

I only managed to do it once soo.... :D 

1. External display is connected (mine was through the HDMI).
2. Laptop is in Standard mode (NOT using the NVIDIA GPU exclusively)
3. Shut down the laptop from the Windows start menu.
4. While the laptop is shutting down close the lid and immediately after disconnect the external display
5. Disconnect all other peripherals (headphones, charger)
6. Power back on the laptop (after approximately 20min if that matters)
7. You got yourself a laptop that does not detect its own screen

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14873392/log.txt)

### Device and Model

ASUS M16 2022 GU603ZM

### Additional information.

Attempted Solutions:

Tried to do the reverse actions (maybe the lid had to open while connected to the external display); no effect.
Completely uninstalled and reinstalled Nvidia GPU drivers; no effect.
Completely uninstalled and reinstalled Intel GPU drivers; no effect.
Completely uninstalled and reinstalled Armory Crate; no effect.
Completely uninstalled and reinstalled System Control Interface; no effect.
Uninstalled Armory Crate and tried to use GHelper; no effect.
Did a Hardware reset / CMOS reset; no effect.
BIOS reset while on Intel GPU; no effect.
BIOS reset while on Nvidia GPU; no effect.
BIOS rollback; no effect.

Additional info (screenshots + log below):

The Intel GPU functions correctly when an external display is connected via USB-C, the Intel GPU is working.
No physical hardware issues with the laptop.
In Windows Display Settings (with Intel GPU and external display), the interface for rearranging displays is missing.
When using the Intel GPU and external display Device Manager shows the integrated display as hidden with "Code 45" (hardware device not connected).
When I installed GHelper (and with Intel GPU and external display) it says Internal screen off.
No BIOS setting is available to change the display although it seems that the Asus BIOS has very limited settings.
In the BIOS (with Intel GPU and external display) under the LCD label it says the resolution of the external display - probably thinks that is the default.

It seems that you guys are my only hope of resolving this issue without having to go through Asus's support. If any other info is needed please write.
Any help is greatly appreciated!

On Ultimate mode:
<img width="305" alt="Screenshot 2024-04-04 164645" src="https://github.com/seerge/g-helper/assets/116370468/794043e4-56f4-4166-9afb-3650d1c31fd6">
<img width="653" alt="Screenshot 2024-04-04 165159" src="https://github.com/seerge/g-helper/assets/116370468/9be5b139-3335-4f22-a0cf-b544a148bb72">

On Standard mode:
![Screenshot 2024-04-04 164835](https://github.com/seerge/g-helper/assets/116370468/4cce8bf2-5d1b-431a-882b-7f146fb8483a)
![Screenshot 2024-04-04 164933](https://github.com/seerge/g-helper/assets/116370468/9f017c5c-0a7f-49d9-83f0-bb14411e8228)
![Screenshot 2024-04-04 164957](https://github.com/seerge/g-helper/assets/116370468/f911ef65-0e93-4923-9e32-a96c65de3025)
![Screenshot 2024-04-04 165010](https://github.com/seerge/g-helper/assets/116370468/7635d852-ecd4-434d-b28c-6af7953c5be3)

Unrelated: This issue led me to GHelper - it is amazing, so much better than the bloated armory crate from asus, def only using that going forward.

### Armoury Crate

Uninstalled

### Asus Services

8

### Version

0.164.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Teodor5rov hello, I'm sorry to read that. But how is it connected to G-Helper in a first place ? Especially if same situation happens with AC (as you write).

From my experience it's likely some nvidia optimus / driver issues, as they were recently releasing a driver update that specifically mentioned something like that https://tweakers.net/downloads/68040/geforce-game-ready-driver-55186-whql.html 

> [Advanced Optimus] Notebook may not wake up from sleep when in NVIDIA GPU only display mode [4454524]

I can advice only to try a [clean driver reinstall again using DDU](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers)

**Comment by Teodor5rov** [comment]
Thank you for the fast reply! 

I understand this is not a bug coming from G-Helper. I just figured that you might give me some clue on how to fix the issue as I think it is related.

I don't think the problem is from the Nvidia or Intel drivers as I already did a complete uninstall using DDU of both GPU drivers and the behavior is the same. Also is it possible that the drivers also affect where the BIOS is displayed? The issue happens when using the Intel GPU and not the Nvidia GPU. In fact, when using only the Nvidia GPU in Ultimate mode everything works as intended. 

The only way to change the mux config (which is also the only way to get the internal display to work) and all kinds of other settings is through G-Helper or AC. So I figured if you can interact with the system maybe you may know why this happened.

**Comment by seerge** [comment]
@Teodor5rov 

> Also is it possible that the drivers also affect where the BIOS is displayed? 

I didn't really get this.

> In fact, when using only the Nvidia GPU in Ultimate mode everything works as intended.
The only way to change the mux config (which is also the only way to get the internal display to work) and all kinds of other settings is through G-Helper or AC. So I figured if you can interact with the system maybe you may know why this happened.

Ultimate mode is when Asus BIOS routes internal display directly to dGPU (in an old-fashioned way) bypassing all that optimus stuff. So if in Ultimate mode everything is working well, most probably it has something to do with optimus shenanigans.

Try to set optimus swtich to Auto or to NvidiaGPU only (inside nvidia control panel). May be that will change something.

Beside that I can't help anyhow unfortunately.

Thanks and closing as answered.
