### ISSUE TITLE
More Keyboard Lightning

### ISSUE THREAD

**Issue by Covorus** [seerge/g-helper#2386]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hey seerge, i really like ghelper and i hope you can add more backlighting options. 

### Describe the solution you'd like

Some of the ac's lightning are pretty cool, like music, adaptive lightning, music and smart. I don't know if it would cause any optimization issues tho.

### Device and Model

Asus ROG G17 G713PV

### Additional information.

![image_2024-04-04_191519032](https://github.com/seerge/g-helper/assets/166044778/9ae1f7b1-2212-40da-bd94-5202fd782ad8)

**Comment by seerge** [comment]
@Covorus hello,

Smart and Adaptive lightning is already in the app if I remember what those actions did in AC

"Heatmap" mode color keyboard proportionally to CPU temperature (i think it's called Smart)
"Ambient" mode colors keyboard based on average color of the screen contents (that's Adaptive)

As for "music" it can be quite resource heavy to run (cause even Ambient is already very taxing), and against whole idea of g-helper being lightweight. So I don't plan to add that in the near future :)

Thanks.
