### ISSUE TITLE
Wrong Keybinding and screen "turned off"

### ISSUE THREAD

**Issue by Covorus** [seerge/g-helper#2387]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![image_2024-04-04_212255523](https://github.com/seerge/g-helper/assets/166044778/8e7a9da4-5a40-4e82-a9f4-1929abd1e8a7)
![image](https://github.com/seerge/g-helper/assets/166044778/c8a6215f-2879-43c8-aaaa-4455ef57dee8)
I can't use the keybindings, because it somehow denies the binded command. For example m1 and m4 does the same action and change m4 otherwise, m2 mutes my mic, m3 turns the volume up (so they have been intertwined) and m5 mutes the mic too.

As for the screen, it shows a weird warning before running ghelper.exe saying it had problems with SmartScreen and now i cant change visual mode, refresh rate or the brightness

### How to reproduce the bug?

1 Delete Ghelper
2 Reinstall and run the Ghelper

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14875740/log.txt)

### Device and Model

Asus rog strix G17 G713PV

### Additional information.

Yes, this is probably my problem.  I have disabled the iGPU and tried to delete ghelper, by deleting every folder. It became like this after i redownloaded and ran it at the same time as AC. Sorry about that.

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.164.0

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@Covorus hello,

You have mixed 2 separate things

**For bindings,** did you bind your keys somehow using AC before ? If so - "unbind" them in AC (even if you have uninstalled it you need to get it back). Cause it assigns keys on some strange hardware level. G-Helper won't help you here. 

Alternatively you can just [try hardware reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hardware-reset--cmos-reset) . That may reset bindings.

Especially for M1/M2 as by default they just emit vol down / vol up commands, G-Helper is not even involved in that.

[For defender smartscreen](https://github.com/seerge/g-helper/wiki/Troubleshooting#hardware-reset--cmos-reset) - [check readme](https://github.com/seerge/g-helper/wiki/Requirements#how-to-start)

> If you get a warning from Windows Defender on launch (Windows Protected your PC). Click More Info -> Run anyway.

**Comment by seerge** [comment]
@Covorus are other problems "resolved" ?

For brightness make sure not to boot in eco mode, as it makes nvidia driver go nuts. Check this topic https://github.com/seerge/g-helper/discussions/1042

**Comment by Covorus** [comment]
As of now, yes. Everything just got solved. Thank you a lot :)
