### ISSUE TITLE
Heat map Color stating with blue

### ISSUE THREAD

**Issue by FelipeAlma** [seerge/g-helper#2388]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hi Seerge, I have tried to find any help on configuring colors and temperature ranges for Heatmap. on the last build 0.164.0.

### Describe the solution you'd like

Is there a way to set even on code or text file, config file, mini window, that allows to select colors (Blue-Green-Yellow-Red) and the respective temp ranges?

### Describe alternatives you've considered

Went back to AC and now it doesnt shows CPU temperature as triger for INTELLIGENT aura effect, just CPU usage.

### Device and Model

2024 Rog strix scar 18 G834JZR

**Comment by seerge** [comment]
@FelipeAlma hello,

It starts with blue cause blue is cold! :) So it's actually logical from my point of view.

Current temps/color points are
```
int freeze = 20, cold = 40, warm = 65, hot = 90;
```

You can change them in the code
https://github.com/seerge/g-helper/blob/bbf4c10a2e00e6c5504e6ae9c5a3a146afd2d329/app/USB/Aura.cs#L723

But I don't want to edit them anyhow as I don't want to overcomplicate already complicated things and they seem to be quite logical and fitting most of the scenarios

**Comment by FelipeAlma** [comment]
Thanks Seerge... that is exacly what I was looking for... I don´t have a freezer to cool this thing down to 20 so I wasn´t able to see blue color... All I have to do now is modify the thresholds and let your magic flow.... thnaks for this awesome tool......

**Comment by FelipeAlma** [comment]
@seerge ,this is the edit I made and looks great... added another color scale.. with color White (ICE) before blue, not sure if the thresholds could be moded with numbers or sliders in the extras or fan setting window, thanks again fot the help and de tool
```
            public static void ApplyHeatmap(bool init = false)
            {
                float cpuTemp = (float)HardwareControl.GetCPUTemp();
                int freeze = 30, cold = 55, fresh = 65, warm = 75, hot = 83;
                Color color;

                //Debug.WriteLine(cpuTemp);

                if (cpuTemp < cold) color = ColorUtils.GetWeightedAverage(Color.White, Color.Blue, ((float)cpuTemp - freeze) / (cold - freeze));
                else if (cpuTemp < fresh) color = ColorUtils.GetWeightedAverage(Color.Blue, Color.Green, ((float)cpuTemp - cold) / (warm - cold));
                else if (cpuTemp < warm) color = ColorUtils.GetWeightedAverage(Color.Green, Color.Yellow, ((float)cpuTemp - cold) / (warm - cold));
                else if (cpuTemp < hot) color = ColorUtils.GetWeightedAverage(Color.Yellow, Color.Red, ((float)cpuTemp - warm) / (hot - warm));
                else color = Color.Red;

                ApplyDirect(color, init);
            }
```
