### ISSUE TITLE
Change Refresh Rate using Key Bindings

### ISSUE THREAD

**Issue by rramnel** [seerge/g-helper#2389]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Currently I would need to open the G-Helper app to change the refresh rate of the display

### Describe the solution you'd like

Would it be possible to set a Key Binding to toggle the refresh rate? 

### Device and Model

ASUS G14 2024

**Comment by seerge** [comment]
@rramnel hello, what is the practical purpose of that?

**Comment by rramnel** [comment]
To save battery life. Ideally I would like to see Dynamic Refresh Rate available in Windows 11, unfortunately that's not the case on the ASUS G14 2024 model. My use case would be switching the refresh rate to 60Hz when watching videos and then switching to 120Hz for web browsing, etc.

**Comment by seerge** [comment]
@rramnel well, to save battery you should stick to 60hz and just use Auto. And honestly on OLED screen that you have on 2024 model refresh rate doesn't really drain more power (may be something like extra 0.1-0.2W at max ...)

I see that you were asking about hotkeys for modes before, and I have added them eventually. But I'm not a fan of adding hotkey for every single button in the app tbh

**Comment by rramnel** [comment]
Thank you very much. I noticed that when I watch videos on YouTube having 120Hz on uses around 3-4 watts more.

**Comment by seerge** [comment]
@rramnel ok, try this build

It should support ``Ctrl + Shift + Alt + F13`` to toggle between Maximum (120) / 60 Hz refresh rates.

This is in line with other such [bindings app supports ](https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings)

You can bind your own hotkey using Sharpkeys or similar app to emit ``Ctrl + Shift + Alt + F13``

[GHelper.zip](https://github.com/seerge/g-helper/files/14884604/GHelper.zip)
