### ISSUE TITLE
[Feature request] Add delay before applying the mode

### ISSUE THREAD

**Issue by Bananalaw** [seerge/g-helper#2391]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

My issue that seerge don't understand first request, thinking about be delay of button press; Like you press the key combination and only after 1 seconds key works. I did not mean that. seerge understand my previous request wrong.

### Describe the solution you'd like

After pressing key combination (FN + F5) to change the modes, mode changes and applying immediately.
Request is: make delay to apply the mode.

Super-dum-version:
- You staying on a "Silent" mode. 
- You decided to change on "Super low BG3" mode, that you created for baldurs gate 3 to run on 30 fps. It's fifth on the list.
- Hit FN + F5 
- The "Balanced" pops on screen
- Ghelper do not applying "Balanced" mode, waiting 1 seconds before apply
- Hit FN + F5 again
- The "Turbo" mode pops on screen
- Ghelper do not applying "Turbo" mode, waiting 1 seconds before apply
- Hit FN + F5 again
- Name of the custom "Fair" mode pops on screen
- Ghelper do not applying "Fair" mode, waiting 1 seconds before apply
- Hit FN + F5 again
- Name of the custom "Super low BG3" mode pops on screen, that one you need
- Ghelper do not applying "Super low BG3" mode, waiting 1 seconds before apply
- You wait 1 second
- Ghelper apply the custom "Super low BG3" mode.

...

PROFIT

### Device and Model

FA507XI

### Additional information.

I don't like when my laptop immediatly applying every mode that is listing trough, especially when I considering to change it on THAT ONE specific of all my 45+ custom modes.

I think I made myself clear. *Dissapears*

**Comment by seerge** [comment]
@Bananalaw I have understood you perfectly.

But it's not that easy to do, and it can cause lots of unexpected behaviors. Cause I have explained mode setting is not a single command. It's a chain of ones (especially if you have customizations)

Did you know you can cycle between modes backwards if you also hold ``Shift`` ?

Why do you have 45 modes in a first place?

**Comment by seerge** [comment]
@Bananalaw you can try this build, but I'm not sure if it's reasonable to have this behavior as default for everyone

[GHelper.zip](https://github.com/seerge/g-helper/files/14884859/GHelper.zip)

**Comment by Bananalaw** [comment]
> @Bananalaw hello, I have understood you perfectly.
> 
> But it's not that easy to do, and it can cause lots of unexpected behaviors. Cause I have explained mode setting is not a single command. It's a chain of ones (especially if you have customizations)
> 
> Did you know you can cycle between modes backwards if you also hold `Shift` ?
> 
> Why do you have 45 modes in a first place?

Fine. Okay. I believe you.
Holding shift? Didn't knew that. Thanks.
45 modes? Not really 45. More like 10... Because im insane.

**Comment by seerge** [comment]
@Bananalaw does the build I linked above work for you? :)

**Comment by Bananalaw** [comment]
@seerge yes. Thank you very much for this.

**Comment by seerge** [comment]
@Bananalaw ok

I have turned it off by default, but you can set delay in a config.json by adding
```
"mode_delay" : 1000,
```

Delay is in milliseconds

[GHelper.zip](https://github.com/seerge/g-helper/files/14893036/GHelper.zip)

Closing as completed
