### ISSUE TITLE
[Feature Request] Black Screen Hotkey for OLED Displays

### ISSUE THREAD

**Issue by justincpresley** [seerge/g-helper#2392]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

There are many times in which the owner of a device simply steps away for a brief or extended period of time. Its in these cases which a static image is displayed which will cause wear and tear on OLED displays. While the owner could simply close the laptop, this could turn off applications or be simply inconvenient. 

### Describe the solution you'd like

A GHelper setting to bind a certain hotkey (e.x. `ALT-1`) to shut off all pixels protecting OLED displays. By shut off, it can just simply turn all pixels to being solid black due to OLED's deep blacks.
When a user enables this feature and presses the set key-bind, the display will shut off if GHelper is in the background. Once the screen is blackened, the display turns on if the key-bind is pressed again or any key is pressed (possibly another setting).

To help keep GHelper simple and easy to use, this feature could be a off-by-default feature only available on OLED displays.

### Describe alternatives you've considered

I am currently using the opensource C# BlackScreens on Github - (https://github.com/BlueBird67/BlackScreens) to have this exact feature. However, I think it is useful enough that other users of ASUS OLED Displays could greatly benefit from and that GHelper could provide. It also seems like a relatively simple feature.

### Device and Model

ASUS ROG Zephyrus G14 (2024) GA403

**Comment by seerge** [comment]
@justincpresley hello, I don't see any point to reinvent the wheel here.

You can just set windows to turn screen off on inactivity after 1-2-3  minutes, which is same.

You can also assign any of the macro keys to turn screen off, if you want to do that manually :)

Thanks
