### ISSUE TITLE
Keyboard color not working

### ISSUE THREAD

**Issue by duckude100** [seerge/g-helper#2393]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Just bought a new asus g16 zephyrus. installed g helper, uninstalled armory crate. 
The keyboard color feature is not working at all. it was working in armory crate, and is currently stuck in the setting i set it to in armory crate. 

### How to reproduce the bug?

click on color, set the color, the color changes in the little box in the main menu, but the keyboard color remains the same. 

### Logs

4/4/2024 8:21:59 PM: FanCPU = 14-39-44-47-4C-51-57-62-11-19-22-37-4B-5E-5E-64 : OK
4/4/2024 8:21:59 PM: FanGPU = 14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F : OK
4/4/2024 8:22:03 PM: Boost 3
4/4/2024 8:22:03 PM: Mode = 0 : OK
4/4/2024 8:22:05 PM: PowerLimit C0 (GPU BOOST) = 20 : OK
4/4/2024 8:22:05 PM: PowerLimit C2 (GPU TEMP) = 87 : OK
4/4/2024 8:22:17 PM: Display configuration changed.
4/4/2024 8:22:18 PM:  HDR: True 10 3 False
4/4/2024 8:22:18 PM: Display configuration changed.
4/4/2024 8:22:18 PM:  HDR: True 10 3 False
4/4/2024 8:24:07 PM: Display configuration changed.
4/4/2024 8:24:08 PM: Display configuration changed.
4/4/2024 8:29:32 PM: Key: 56
4/4/2024 8:29:32 PM:  HDR: True 10 3 False
4/4/2024 8:29:36 PM: Display configuration changed.
4/4/2024 8:29:36 PM: Display configuration changed.
4/4/2024 8:50:51 PM: Key: 56
4/4/2024 8:50:51 PM:  HDR: True 10 3 False
4/4/2024 8:50:57 PM: Display configuration changed.
4/4/2024 8:50:58 PM:  HDR: True 10 3 False
4/4/2024 8:50:58 PM: Display configuration changed.
4/4/2024 8:50:58 PM:  HDR: True 10 3 False
4/4/2024 8:51:13 PM: Display configuration changed.
4/4/2024 8:51:13 PM:  HDR: True 10 3 False
4/4/2024 8:52:15 PM: Key: 56
4/4/2024 8:52:15 PM:  HDR: True 10 3 False
4/4/2024 8:52:16 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
4/4/2024 8:52:16 PM: Mode = 2 : OK
4/4/2024 8:56:54 PM: Key: 196
4/4/2024 8:56:54 PM: HotKey 19B6|63: 5A-BA-C5-C4-02
4/4/2024 8:56:54 PM: Key: 196
4/4/2024 8:56:54 PM: HotKey 19B6|63: 5A-BA-C5-C4-03
4/4/2024 8:56:54 PM: Key: 196
4/4/2024 8:56:54 PM: HotKey 19B6|63: 5A-BA-C5-C4-03
4/4/2024 8:56:54 PM: Key: 196
4/4/2024 8:56:54 PM: HotKey 19B6|63: 5A-BA-C5-C4-03
4/4/2024 8:56:55 PM: Key: 196
4/4/2024 8:56:55 PM: HotKey 19B6|63: 5A-BA-C5-C4-03
4/4/2024 8:57:04 PM: Key: 32
4/4/2024 8:57:04 PM: Brightness = 32 : OK
4/4/2024 8:57:04 PM: Key: 32
4/4/2024 8:57:04 PM: Brightness = 32 : OK
4/4/2024 8:57:05 PM: Key: 32
4/4/2024 8:57:05 PM: Brightness = 32 : OK
4/4/2024 8:57:05 PM: Key: 32
4/4/2024 8:57:05 PM: Brightness = 32 : OK
4/4/2024 8:57:05 PM: Key: 32
4/4/2024 8:57:05 PM: Brightness = 32 : OK
4/4/2024 8:57:05 PM: Key: 32
4/4/2024 8:57:05 PM: Brightness = 32 : OK
4/4/2024 8:57:05 PM: Key: 32
4/4/2024 8:57:05 PM: Brightness = 32 : OK
4/4/2024 8:57:06 PM: Key: 32
4/4/2024 8:57:06 PM: Brightness = 32 : OK
4/4/2024 8:57:06 PM: Key: 32
4/4/2024 8:57:06 PM: Brightness = 32 : OK
4/4/2024 8:57:06 PM: Key: 32
4/4/2024 8:57:06 PM: Brightness = 32 : OK
4/4/2024 8:57:06 PM: Key: 32
4/4/2024 8:57:06 PM: Brightness = 32 : OK
4/4/2024 9:06:03 PM: HID Device Event: Checking for new ASUS Mice
4/4/2024 9:56:13 PM: Monitor Dimmed
4/4/2024 9:56:28 PM: Monitor Power Off
4/4/2024 9:56:28 PM: Backlight 19B6|63: 5A-BA-C5-C4-00
4/4/2024 10:42:24 PM: Monitor Power On
4/4/2024 10:42:24 PM: AutoSetting for Online
4/4/2024 10:42:24 PM: BatteryLimit = 85 : OK
4/4/2024 10:42:24 PM: Session:SessionUnlock
4/4/2024 10:42:24 PM: \\?\DISPLAY#SDC41A3#4&36409b60&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
4/4/2024 10:42:24 PM: \\?\DISPLAY#SDC41A3#4&36409b60&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
4/4/2024 10:42:24 PM:  HDR: True 10 3 False
4/4/2024 10:42:26 PM: Input available: \\?\hid#vid_0b05&pid_19b6&col05#6&2caf62d7&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 63
4/4/2024 10:42:26 PM: Eco flag : 0
4/4/2024 10:42:26 PM: Mux flag : 1
4/4/2024 10:42:26 PM: USB 19B6|63: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
4/4/2024 10:42:26 PM: Input: \\?\hid#vid_0b05&pid_19b6&col05#6&2caf62d7&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
4/4/2024 10:42:26 PM: \\?\DISPLAY#SDC41A3#4&36409b60&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
4/4/2024 10:42:26 PM: \\?\DISPLAY#SDC41A3#4&36409b60&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
4/4/2024 10:42:26 PM:  HDR: True 10 3 False
4/4/2024 10:42:26 PM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/4/2024 10:42:26 PM: Init 19B6: 5D-B9
4/4/2024 10:42:26 PM: Mode = 2 : OK
4/4/2024 10:42:26 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
4/4/2024 10:42:26 PM: Init 19B6: 5D-05-20-31-00-1A
4/4/2024 10:42:26 PM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
4/4/2024 10:42:26 PM: AuraMode: AuraStatic
4/4/2024 10:42:26 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
4/4/2024 10:42:26 PM: USB 19B6: 5D-B5-00-00-00
4/4/2024 10:42:26 PM: USB 19B6: 5D-B4
4/4/2024 10:42:26 PM: Slash:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
4/4/2024 10:42:26 PM: Slash:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
4/4/2024 10:42:26 PM: Slash:5E-D3-03-01-08-AB-FF-01-00-06-00-FF-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
4/4/2024 10:42:27 PM: Auto 19B6|63: 5A-BA-C5-C4-03
4/4/2024 10:42:51 PM: HID Device Event: Checking for new ASUS Mice
4/4/2024 10:42:57 PM: Display configuration changed.
4/4/2024 10:43:26 PM: Display configuration changed.
4/4/2024 10:43:27 PM: Display configuration changed.
4/4/2024 10:55:54 PM: Key: 56
4/4/2024 10:55:54 PM: Listener stopped
4/4/2024 10:55:54 PM:  HDR: True 10 3 False
4/4/2024 10:56:08 PM: Key: 56
4/4/2024 10:56:08 PM:  HDR: True 10 3 False
4/4/2024 10:56:10 PM: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a -> 00000000-0000-0000-0000-000000000000:OK
4/4/2024 10:56:10 PM: Mode = 0 : OK
4/4/2024 10:56:11 PM: PowerLimit C0 (GPU BOOST) = 20 : OK
4/4/2024 10:56:11 PM: PowerLimit C2 (GPU TEMP) = 87 : OK
4/4/2024 10:56:23 PM: Display configuration changed.
4/4/2024 10:56:24 PM: Display configuration changed.
4/4/2024 10:56:32 PM: Key: 56
4/4/2024 10:56:32 PM:  HDR: True 10 3 False
4/4/2024 10:56:43 PM: Display configuration changed.
4/4/2024 10:56:43 PM: Display configuration changed.
4/4/2024 10:57:37 PM: Key: 56
4/4/2024 10:57:37 PM:  HDR: True 10 3 False
4/4/2024 10:58:01 PM: Display configuration changed.
4/4/2024 10:58:01 PM: Display configuration changed.
4/4/2024 10:58:45 PM: Key: 56
4/4/2024 10:58:45 PM:  HDR: True 10 3 False
4/4/2024 10:58:48 PM: Boost 6
4/4/2024 10:58:48 PM: Mode = 1 : OK
4/4/2024 10:58:48 PM: FanCPU = 14-39-44-47-4C-51-57-62-11-19-22-37-4B-5E-5E-64 : OK
4/4/2024 10:58:48 PM: FanGPU = 14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F : OK
4/4/2024 10:59:49 PM: GET GPU CLOCKS: 0, 0
4/4/2024 10:59:50 PM: GET CLOCK LIMIT: 0
4/4/2024 10:59:50 PM: ReadGPUPowerBase: 80
4/4/2024 10:59:50 PM: ReadGPUPower (1): 25
4/4/2024 10:59:53 PM: FanCPU = 14-39-44-47-4C-51-57-62-11-19-22-37-4B-63-63-64 : OK
4/4/2024 10:59:53 PM: FanGPU = 14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F : OK
4/4/2024 11:00:14 PM: Display configuration changed.

4/6/2024 5:16:30 PM: Auto 19B6|63: 5A-BA-C5-C4-01
4/6/2024 5:16:31 PM: Lid Open
4/6/2024 5:16:31 PM: Lid 19B6|63: 5A-BA-C5-C4-01
4/6/2024 5:16:44 PM: Session:SessionUnlock
4/6/2024 5:16:44 PM: \\?\DISPLAY#SDC41A3#4&36409b60&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
4/6/2024 5:16:44 PM: \\?\DISPLAY#SDC41A3#4&36409b60&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
4/6/2024 5:16:45 PM:  HDR: False 10 9 False
4/6/2024 5:16:55 PM: Lid Closed
4/6/2024 5:16:55 PM: Monitor Power Off
4/6/2024 5:16:55 PM: Lid 19B6|63: 5A-BA-C5-C4-00
4/6/2024 5:16:55 PM: Backlight 19B6|63: 5A-BA-C5-C4-00
4/6/2024 5:17:08 PM: WMI event 88
4/6/2024 5:17:08 PM: WMI event 207
4/6/2024 5:17:08 PM: WMI event 123
4/6/2024 5:17:08 PM: AutoSetting for Online
4/6/2024 5:17:08 PM: BatteryLimit = 85 : OK
4/6/2024 5:17:08 PM: Monitor Power On
4/6/2024 5:17:09 PM: HID Device Event: Checking for new ASUS Mice
4/6/2024 5:17:10 PM: Input available: \\?\hid#vid_0b05&pid_19b6&col05#6&2caf62d7&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 63
4/6/2024 5:17:10 PM: USB 19B6|63: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
4/6/2024 5:17:10 PM: Input: \\?\hid#vid_0b05&pid_19b6&col05#6&2caf62d7&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
4/6/2024 5:17:10 PM: Mode = 0 : OK
4/6/2024 5:17:10 PM: Eco flag : 0
4/6/2024 5:17:10 PM: Mux flag : 1
4/6/2024 5:17:10 PM: \\?\DISPLAY#SDC41A3#4&36409b60&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
4/6/2024 5:17:10 PM: \\?\DISPLAY#SDC41A3#4&36409b60&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0

### Device and Model

asus g16 zephyrus 2024

### Armoury Crate

Uninstalled

### Asus Services

turned off in g helper

### Version

newest?

### OS

windows 11

**Comment by justincpresley** [comment]
Not saying this is the issue, but make sure `Dynamic Lighting` is turned off completely under Personalization in Settings. It likes to mess with things!

**Comment by duckude100** [comment]
Fantastic that worked!! The slash however still does not work... Lol will
try and figure that one out.
Thanks for the tip!
Cheers

**Comment by seerge** [comment]
@duckude100 as already mentioned, your [question is already answered in FAQ](https://github.com/seerge/g-helper/wiki/FAQ#backlight-doesnt-change-color-or-stays-blue)
