### ISSUE TITLE
[Feature request]Adding Windows Mode Default with Silent, Balanced, and Turbo Options

### ISSUE THREAD

**Issue by fullstackdevclubb** [seerge/g-helper#2394]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Users do not have the ability to set a default Windows mode with options such as Silent, Balanced, and Turbo.

### Describe the solution you'd like

Integrating a user-friendly interface into gHelper allowing users to easily set a default Windows mode with options for Silent, Balanced, and Turbo performance modes.

### Device and Model

Asus TUF A15

**Comment by seerge** [comment]
@fullstackdevclubb hello, there is no such thing as "windows" mode.

In AC "Windows" mode is Balanced (or Performance) BIOS profile + default windows power plan (i.e. balanced)

Here it's just balanced.
