### ISSUE TITLE
[Request] AC's power plan profiles on GHelper

### ISSUE THREAD

**Issue by H1m4ru** [seerge/g-helper#2399]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Something i've already noticed while using GHelper is how it constantly heats my device more than when i used Armoury Crate while gaming/browsing, and that's probably because GHelper handles power modes based on the deafult Windows power plan presets, which unfortunately aren't really optimized for laptops and specially for each different ASUS laptop, something that AC is known to do perfectly well.

### Describe the solution you'd like

It should have a option to import AC's power plan into some kind of compressed file and import to GHelper with a proper advanced option, or maybe already have those presets appliable via Powershell according to each device which is recognized by GHelper. 

### Device and Model

ROG Strix G15 2021 G513IE (N7NRKD00214729F)

### Additional information.

Using original Windows 11 Pro, with a mushroom stand and proper cleaning.

**Comment by H1m4ru** [comment]
Just to explain better why can't i just make the thing it's already included in the wiki. You just CAN'T.
The way Armoury Crate manages their power plans is about overwriting settings for one single power plan and making Silent mode as another exclusive power plan.
So even if you properly export your power plan and import it to Windows, only Silent mode will be applied properly, since it's not designed for being modified to be a new power plan, like it happens with Performance/Turbo modes.
So you cannot put all 3 power plans into the system and use them on GHelper, since this program immediately removes your new parameters after opening and changes it to the default Windows power plan.
So unfortunately, there's NO WAY to use a properly optimized power plan for your laptop with GHelper, and that will cause more heat and limited power, like i saw it indeed happened with some users around here.
The only proper way to solve this is via a software solution which monitores and keeps each power plan ALIVE in your system before/after reboot.

**Comment by seerge** [comment]
@H1m4ru hello, 

G-Helper **doesn't manage your power anyhow**. It can only set already predefined and stored in BIOS preset (Silent / Balanced / Turbo), and accompany it it with windows power mode.

If you want to assign custom windows power plans you can already do that. It's covered in readme
https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-windows-power-plans-with-each-mode

If you want to use AC power plans by some reason, [export them](https://www.majorgeeks.com/content/page/how_to_import_or_export_a_power_plan_in_windows_10.html) and reuse

Thanks.

**Comment by seerge** [comment]
You can also try https://www.coderbag.com/product/quickcpu to actually see in details each power plan, and spot a setting that makes a difference for you (if there is one)

**Comment by H1m4ru** [comment]
> @H1m4ru hello,
> 
> G-Helper **doesn't manage your power anyhow**. It can only set already predefined and stored in BIOS preset (Silent / Balanced / Turbo), and accompany it it with windows power mode.
> 
> If you want to assign custom windows power plans you can already do that. It's covered in readme https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-windows-power-plans-with-each-mode
> 
> If you want to use AC power plans by some reason, [export them](https://www.majorgeeks.com/content/page/how_to_import_or_export_a_power_plan_in_windows_10.html) and reuse
> 
> Thanks.

I already said about that in my previous comment. It's IMPOSSIBLE to reuse AC's power plan profiles due to how Windows manages these power plans. I already tried thousands of times, and GHelper still resets my configuration and won't make it work.

**Comment by H1m4ru** [comment]
> You can also try https://www.coderbag.com/product/quickcpu to actually see in details each power plan, and spot a setting that makes a difference for you (if there is one)
> 
AC's power plan profiles uses additional settings which you can't manage normally when adding a new power plan, so it will make SO MUCH WORK to replicate those settings properly, changing registry's parameters constantly and having to read and copy every single setting configured while using them with Armoury Crate installed.

**Comment by seerge** [comment]
@H1m4ru power plans in windows are just a collection of settings (most of which are obsolete and don't work btw). When you export power plan it exports all it's settings.

What settings are you speaking specifically ?

And what exactly do you expect form me?

**Comment by H1m4ru** [comment]
> @H1m4ru power plans in windows are just a collection of settings (most of which are obsolete and don't work btw). When you export power plan it exports all it's settings.
> 
> What settings are you speaking specifically ?
> 
> And what exactly do you expect form me?

I'll reinstall Armoury Crate and show those settings to you, just take a couple minutes.

**Comment by H1m4ru** [comment]
@seerge Here is a example of the difference between AC's power plans and Balanced mode.
There are a bunch of modified settings for every power plan.
![balanced](https://github.com/seerge/g-helper/assets/103531824/e44b654c-6374-47ff-a78d-9813986e1643)
![turbo](https://github.com/seerge/g-helper/assets/103531824/12804d8d-35c4-4a0e-a011-8f25296216fa)

**Comment by seerge** [comment]
@H1m4ru ok, but all those settings can be exported with ```powercfg -export``` or just get **AC power plan GUIDS directly** by grabbing them with ```powercfg /L `` and set to config so G-Helper would switch them as well :)

**Comment by H1m4ru** [comment]
> @H1m4ru ok, but all those settings can be exported with `powercfg -export` or just get **AC power plan GUIDS directly** by grabbing them with `powercfg /L ` and set to config so G-Helper would switch them as well :)

I'll make a video to show you how that doesn't work at all. Performance/Turbo profiles can't be applied because they're literally the same power plan but with different settings from each other, and even if i configure that in `config.json`, GHelper always delete the new lines after launch and replaces their power plans with Windows' default.

**Comment by seerge** [comment]
@H1m4ru 

> GHelper always delete the new lines after launch and replaces their power plans with Windows' default.

I think this is the culprit of your problem. You are doing something wrong in config itself. As G-Helper does not delete or erase config if it's all good.

Please check how it needs to be done here https://github.com/seerge/g-helper/wiki/Power-user-settings#general-note you need to keep commas and also quit app before editing (obviously).

**Comment by H1m4ru** [comment]
@seerge I hope this video will help you to understand my issue (sorry if you understand much, English is not my first language).
https://youtu.be/labUK50XYRE?si=BmxI3mCy6fbJ3oKu

**Comment by seerge** [comment]
@H1m4ru thanks, you just don't maintain correct json structure. All lines except last one need to have ``,``, also power plan GUIDS need to be in quotes.

```
"fan_max_1": 54,
"scheme_0": "8286a019-b671-4f01-a15-332247be1f4c",
"scheme_1": "ecbb187c-a468-43fe-b68c-e8779d5c7d80",
"scheme_2": "bbcac432-1dc5-4276-90c5-60491d23d0fe"
```

**Comment by H1m4ru** [comment]
> @H1m4ru thanks, you just don't maintain correct json structure. All lines except last one need to have `,` in the end also power plan GUIDS need to be in quotes.
> 
> ```
> "fan_max_1": 54,
> "scheme_0": "8286a019-b671-4f01-a1e5-332247be1f4c",
> "scheme_1": "ecbb187c-a468-43fe-b68c-e8779d5c7d80",
> "scheme_2": "bbcac432-1dc5-4276-90c5-60491d23d0fe"
> ```
> 
> (your screenshot) <img alt="Screenshot 2024-04-07 at 22 24 05" width="1127" src="https://private-user-images.githubusercontent.com/5920850/320311987-577e02e2-c470-43fb-80cd-21d1f8ad28ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MjI0OTQsIm5iZiI6MTcxMjUyMjE5NCwicGF0aCI6Ii81OTIwODUwLzMyMDMxMTk4Ny01NzdlMDJlMi1jNDcwLTQzZmItODBjZC0yMWQxZjhhZDI4Y2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDdUMjAzNjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGQ1NzM0ZGIyZWQ0M2E0OWRkNDI3ODhmZGY4MmZmNDY3YTk0OTg4ODcyYTY1YWQzZTU5ZTkxYzBiNTNhMGYzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BfghE-zo5QjnDA5Qkvq40qaq2ORGFeJkXQRJx3MD4Oo">

It worked, thanks! However, if i for example try to switch to Silent mode (the only power plan which is accessible, as you saw in my video), it's not applied in the power plan settings. Is that supposed to happen?

**Comment by H1m4ru** [comment]
Yeah, it's like i said before... Turbo/Performance modes aren't applied, so GHelper doesn't recognize them either :/
![image](https://github.com/seerge/g-helper/assets/103531824/da2cb803-bd99-486b-864e-53cfc67247dd)

**Comment by seerge** [comment]
@H1m4ru did you quit app (with quit button) before editing and saving config ?

Upload your edited config here. I will fix it for you if that's so difficult ...

**Comment by H1m4ru** [comment]
> @H1m4ru did you quit app (with quit button) before editing and saving config ?
> 
> Upload your edited config here. I will fix it for you if that's so difficult ...

Yes, i did exactly as you said. The problem is that i can't import Turbo/Performance modes on Windows, only Silent mode.
So apparently, GHelper thinks that those 2 power modes configured doesn't exist and only selects Silent as an valid power plan.

**Comment by seerge** [comment]
@H1m4ru G-Helper is not verifying plans anyhow, it just uses whatever you have entered in config. If they have disappeared from config - it's cause you either have app running while editing (so it just overrides config) or entered it incorrectly, corrupting structure and causing app to recreate it from scratch.

**Comment by H1m4ru** [comment]
> @H1m4ru G-Helper is not verifying plans anyhow, it just uses whatever you have entered in config. If they have disappeared from config - it's cause you either have app running while editing (so it just overrides config) or entered it incorrectly, corrupting structure and causing app to recreate it from scratch.

Actually this time, it didn't recreated their settings from scratch, they were configured as it should, but only Silent mode was enabled.

**Comment by H1m4ru** [comment]
Ok, i just figured out what happened and fixed it for myself... I'm sorry for that whole discussion for a simple thing, but i still thank you for making me figure out what's happening after all! Have a good day!

**Comment by seerge** [comment]
@H1m4ru so it's working now ?

**Comment by H1m4ru** [comment]
> @H1m4ru so it's working now ?

Yes, it is!

**Comment by seerge** [comment]
@H1m4ru ok. So whole thing is about reading readme and carefully copying IDs.

**Comment by H1m4ru** [comment]
> @H1m4ru ok. So whole thing is about reading readme and carefully copying IDs.

Alright, i promise i won't bother you next time, thanks again
