### ISSUE TITLE
Custom Fan Curve not working properly

### ISSUE THREAD

**Issue by JynoX** [seerge/g-helper#240]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
Cpu's Custom Fan Curve won't apply correctly on ROG Zephyrus G15 2022,  the first temp/RPM value doesn't get applied, meanwhile the GPU profile seems to be working correctly

**Clear scenario to Reproduce**
1. Setting a Custom Fan Curve
2. Setting the cpu fans to be at 0% if temp < 60C
3. Apply Custom Fan Curve
4. Temp < 60C but the fans are spinning at 40%

**Expected behavior**
CPU fans should turn off at temps < 60C but they don't unlike the GPU fans

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11227247/log.txt)

**Screenshots or screencasts**
![Screenshot 2023-04-14 012538](https://user-images.githubusercontent.com/40642679/231904067-08ce6f3c-5cd1-4ed1-be14-6f3fefaad2cd.png)
![Screenshot 2023-04-14 012623](https://user-images.githubusercontent.com/40642679/231904077-3def0f8f-02a7-4730-aea1-356db43165d7.png)
![Screenshot 2023-04-14 012709](https://user-images.githubusercontent.com/40642679/231904087-260ae3c7-dbe1-48f6-89e8-6d0fd837d216.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ROG Zephyrus G15 GA503RS

**Asus software**
- Asus Optimization Service open in the background (only Asus service enabled to still use properly the funtion keys)

**Additional context**

**Comment by paulusgi** [comment]
Hey @JynoX  I can clearly see Fan 0% under 60ºC here:
![image](https://user-images.githubusercontent.com/102924649/231973643-ff3e4202-2d2c-4d4b-9c0b-4b818295e91c.png)

According to your screenshots everything looks fine.

**Comment by JynoX** [comment]
@seerge @paulusgi I submitted the second screenshot exactly because Fan 0% is only being applied after the workaround of adding another dot on 0RPM, sorry for not stating this in the report

This "problem" only affects CPU fans and it wasn't happening before, it only appeared after updating bios to V. 313 and updating G-Helper itself

**Comment by seerge** [comment]
@JynoX so "workaround" works ?

**Comment by JynoX** [comment]
@seerge yes, even tho I had to use it for the GPU too because for some strange reason the Fans would ramp up from 0% to 40%

I’m planning on uninstalling AMD drivers with DDU and reinstalling them to see if that would fix some of the issues
