### ISSUE TITLE
60Hz Display Refresh Rate not working on Asus TUF FX505DT

### ISSUE THREAD

**Issue by AJRadaza** [seerge/g-helper#2400]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The 60Hz Display Refresh Rate button is not working because as I assume, the reason would be because my laptop Asus TUF FX505DT has only 2 refresh rate options and it is: 120Hz and 48Hz - no 60Hz option.

### How to reproduce the bug?

1. Open G-Helper
2. Select 60Hz Laptop Refresh Rate
3. Refresh Rate stays at 120Hz and disables Overdrive

### Logs

08/04/2024 1:38:33 am: ------------
08/04/2024 1:38:33 am: App launched: TUF Gaming FX505DT_FX505DT :0.164.0.0en-GB
08/04/2024 1:38:34 am: Matrix control device was not found on your machine.
08/04/2024 1:38:34 am: NVIDIA GeForce GTX 1650
08/04/2024 1:38:36 am: CPU: 1 - AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   - AMD64 Family 23 Model 24 Stepping 1
08/04/2024 1:38:36 am: AutoSetting for Online
08/04/2024 1:38:36 am: BatteryLimit = 85 : OK
08/04/2024 1:38:36 am: BatteryLimit = 85 : OK
08/04/2024 1:38:36 am: Power Plan b8ef2363-4daf-4127-8a06-7eadb27d5ebf:OK
08/04/2024 1:38:36 am: Power Mode 00000000-0000-0000-0000-000000000000 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
08/04/2024 1:38:36 am: Eco flag : -65536
08/04/2024 1:38:36 am: Mux flag : -65536
08/04/2024 1:38:36 am: \\?\DISPLAY#NCP0036#5&2e0e194d&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
08/04/2024 1:38:36 am: \\?\DISPLAY#NCP0036#5&2e0e194d&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
08/04/2024 1:38:36 am:  HDR: False 8 0 False
08/04/2024 1:38:36 am: Mode = 2 : OK
08/04/2024 1:38:36 am: TUF_KB = 16712125 : OK
08/04/2024 1:38:36 am: AuraMode: AuraStatic
08/04/2024 1:38:37 am: TUF RGB = B4-00-FF-00-FF-EB : OK
08/04/2024 1:38:37 am:  HDR: False 8 0 False
08/04/2024 1:38:37 am: Monitor Power On
08/04/2024 1:38:37 am: Lid Open
08/04/2024 1:38:37 am: TUF Brightness = 130 : OK
08/04/2024 1:38:37 am: TUF Brightness = 130 : OK
08/04/2024 1:38:40 am: Latest version 0.164.0.0
08/04/2024 1:38:42 am: \\?\DISPLAY#NCP0036#5&2e0e194d&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
08/04/2024 1:38:42 am: \\?\DISPLAY#NCP0036#5&2e0e194d&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
08/04/2024 1:38:42 am: Screen = 60Hz : -2
08/04/2024 1:38:42 am:  HDR: False 8 0 False
08/04/2024 1:38:46 am: Input device not found

### Device and Model

Asus TUF FX505-DT

### Additional information.

My laptop Asus FX505-DT only has 2 refresh rate options and it is: **120Hz** and **48Hz** - **no 60Hz option**

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.164.0

### OS

Windows 10 22h2

**Comment by seerge** [comment]
@AJRadaza hello, it's indeed not expecting some non-standard refresh rate. Why do you have 48Hz? It looks strange, and according to [laptop specs that I quickly googled](https://tweakers.net/pricewatch/1586976/asus-asus-tuf-gaming-fx505dt-bq613t/specificaties/) it seems that it supports 60hz. Did you try installing latest drivers (from AMD i assume) ?

<img width="522" alt="Screenshot 2024-04-07 at 19 46 31" src="https://github.com/seerge/g-helper/assets/5920850/f23df273-547f-400d-a9df-e861c5c01ceb">

**Comment by seerge** [comment]
@AJRadaza any update on the matter?

**Comment by seerge** [comment]
Closed as abandoned due to absence or response from issue starter.
