### ISSUE TITLE
Can't drive external display on "Optimized" GPU mode

### ISSUE THREAD

**Issue by lgarlati** [seerge/g-helper#2401]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Can't drive external display (monitor) over HDMI while on "Optimized" GPU mode and not connected to AC adapter. 

With Ghelper, when the Optimized mode is selected, and the laptop (in my case 2024 G16 4080) is connected to a display via the HDMI, the laptop will not detect and display to the monitor. However, it does wake it repeatedly, indicating that it is detecting it to some degree. With Armoury Crate, on Optimized and unplugged, the laptop will switch on the GPU and use it to drive the display.

This error is present both with and without armory crate installed, even while armory crate is running in parallel with ghelper.

Ideally, there would be a way to drive the external display on integrated graphics without needing to turn on the GPU, but if it must, then have a way to do that automatically. 

### How to reproduce the bug?

1. Unplug laptop from all AC adapters
2. Unplug all external displays
3. Open Ghelper
4. Set to "Optimized" GPU mode
5. Plug in an external display via HDMI port
6. External display should wake, wait for a signal, sleep, repeat

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14898208/log.txt)

### Device and Model

Asus Zephyrus G16 GU605MZ

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.164.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@lgarlati hello, this is how your laptop works from inside. 

Your HDMI is routed directly to dGPU, and when you disable it - obviously that port will not work. ``Optimized`` mode by definition turns off dGPU when you unplug.

So just set ``Standard`` mode if you need HDMI and dGPU port to work on battery.

Thanks
