### ISSUE TITLE
Power Limits and UV/OC Resets 

### ISSUE THREAD

**Issue by adelbtw** [seerge/g-helper#2404]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I have a G14 2024 (R9 8945HS and 4060) and I have been facing this issue where every time I set up my Power Limits and UV/OC, the settings will reset back to the defaults (80W on everything and no UV on the CPU) every time I turn my PC off and back on. 

### How to reproduce the bug?

Typically happens to me after I shut down and turn my laptop back on. 

### Logs

Log is completely empty. 

### Device and Model

Asus Zephyrus G14 GA403U

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.0164.0

### OS

Windows 11 Home 23H2

**Comment by seerge** [comment]
> I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.
> Log is completely empty.

No explanation - no answer.
