### ISSUE TITLE
Battery Charge limit sometimes will change

### ISSUE THREAD

**Issue by Tsc88** [seerge/g-helper#2405]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Each time i opened G-Helper, the battery charge limit sometimes will change.

### How to reproduce the bug?

Just open the G-helper.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14903242/log.txt)

### Device and Model

ASUS TUF A15 FA507N-ULP120W

### Additional information.

Before i stop asus service, i open "smart charge" feature which will limit battery charge to 80%. And also i set limit to 80% in G-Helper.

### Armoury Crate

Installed

### Asus Services

None

### Version

0.164

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Tsc88 hello,

I see in a log that it's changed by the user (i.e. from UI)

```
05/04/2024 13:36:17: BatteryLimit = 80 : OK
05/04/2024 13:36:23: BatteryLimit = 85 : OK
```

Most probably you are either misclick with a mouse over slider OR hit keyboard ``Left`` or ``Right`` keys while having slider  in focus :)

**Comment by seerge** [comment]
P.S. You may want to update to 0.165, I have added a tweak there that prevents app from getting focus on wake up, it may help in your situation if you uncontrollably hitting arrow keys by some reason.

**Comment by Tsc88** [comment]
Maybe is the problem of misclick. I will try to update to 0.165. Do i need to uninstall the current one before download new version or just download the new version. Thanks for your response.

**Comment by seerge** [comment]
@Tsc88 you just replace exe with a new one. There is installation / uninstallation. App is portable.

Thanks
