### ISSUE TITLE
Battery limit protect not work on my GU603ZM

### ISSUE THREAD

**Issue by taylorxiu** [seerge/g-helper#2406]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![image](https://github.com/seerge/g-helper/assets/48286322/c1013a4c-de01-4591-a521-ac3ce7ca3136)
![image](https://github.com/seerge/g-helper/assets/48286322/59bca9f7-b3ff-4525-90f9-5b97bcedb208)
I set battery limit at 80%,but it doesn't work.My GU603ZM have already keep 100% battery all day.

### How to reproduce the bug?

just using G-helper

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14904316/log.txt)

### Device and Model

ROG Zephyrus M16 GU603ZM

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.165.0&0.164

### OS

Windows 11  23H2

**Comment by seerge** [comment]
@taylorxiu hello, 

If your device has already charged to 100% it obviously will not discharge back to 80% anyhow, unless you use it on battery.

- Does battery limit work if you discharge ?
- Does it work if you set it in MyASUS ?

**Comment by markhofm** [comment]
Hi, just want to add that I also have this issue on my GA403UI (G14 2024).
The battery charge limit from ghelper did not work (charging from a discharged state always charges to 100%, regardless of the setting in ghelper).

When I have MyAsus installed and activate Battery Care Mode it works and charges only to 80%.
Windows 11 also shows a new icon on the battery indicator and says "Fully smart charged" at 80% which is not the case when I uninstall MyAsus or stop all Asus services from ghelper.

If you need any other information I'm happy to provide it.

**Comment by seerge** [comment]
@markhofm i don't think that your situation is related, as topic starter complains that charge is kept on 100% :)

You need to provide **logs** from the app, and make sure that you have 80% set, and that asus services are not overriding that value (or set to same charge limit) as often other values are not supported by the device.

**Comment by markhofm** [comment]
Oh, I assumed the topic starter also has the issue that it charges past the limit. Obviously, once the charge reaches 100% the charge is also kept at 100% for me.

I can open a new issue, just to answer your point about Asus services: when I install MyAsus and it's services the charge limit from MyAsus works. When I uninstall everything Asus but what is required for ghelper (stop services in extra and so on) the Battery Charge Limit from ghelper does not work.

**Comment by seerge** [comment]
@markhofm 

> You need to provide logs from the app

Thanks.

**Comment by markhofm** [comment]
Sorry, here's the log.
I re-installed MyAsus about two hours ago, before that nothing from Asus was installed.

[log.txt](https://github.com/seerge/g-helper/files/14906361/log.txt)

**Comment by markhofm** [comment]
Ah yes, I did play around with different limits today and the log doesnt cover a longer timeframe.
I had it set to 80% for the last couple of weeks.
I will set it to 80% again and get a log when I have time.

**Comment by taylorxiu** [comment]
> @taylorxiu hello,
> 
> If your device has already charged to 100% it obviously will not discharge back to 80% anyhow, unless you use it on battery.
> 
> * Does battery limit work if you discharge ?
YES
> * Does it work if you set it in MyASUS ?
YES

Yes,you are right.  I discharge my device under 80%, ghelper works!Thank you!

**Comment by seerge** [comment]
@taylorxiu of course it does.
