### ISSUE TITLE
Visual mode

### ISSUE THREAD

**Issue by flankerzo** [seerge/g-helper#2409]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Ghelper become the very thing i dislike about armoury crate,  visual profiles, are garbage, i was so happy that i find this and it havent touched colors, i have it calibrated by radiospectrometer, very fancy color analyzer. But now my custom profile is overiten by im sorry to say this, another wanna be problem solver for problem that never existed.

### Describe the solution you'd like

checkbox with ,,do not toch any color profiles settings,,.

### Describe alternatives you've considered

Only alternative is older ghleper, armoury crate is piece of junk.

### Device and Model

GA401QM, 2021 model with 3060

**Comment by seerge** [comment]
@flankerzo hello,

G-Helper just calls ``AsusSplendid`` utility from Asus System Control Interface package to set modes (same as AC or MyASUS does). If you select ``Default`` - that utility would set official color profile from Asus for your panel without any extra "customizations"

Also when ``Default`` is selected it won't reapply anything on app launch (i.e. will do nothing related to colors). So you can just set your own custom ICC profile and other settings you prefer.

If you don't like a dropdown itself you can hide that via config https://github.com/seerge/g-helper/wiki/Power-user-settings#visual-modes-section

Thanks.

**Comment by flankerzo** [comment]
Thank you for fast reply, 
is there any way to completly disable this feature please? i dont want any profile loading, just basic windows. 
or just finding old version?

**Comment by seerge** [comment]
@flankerzo did you read what I have answered ?

> When Default is selected it won't reapply anything on app launch (i.e. will do nothing related to colors). So you can just set your own custom ICC profile and other settings you prefer.

> If you don't like a dropdown itself you can hide that via config https://github.com/seerge/g-helper/wiki/Power-user-settings#visual-modes-section

**Comment by seerge** [comment]
@flankerzo hello,

I have recently discovered how Armoury can completely disable Game Visual by calling `AsusSplendid.exe` (responsible for it) and added it to G-Helper as new "Disabled" Visual Mode.

It is live in latest release https://github.com/seerge/g-helper/releases/tag/v0.196

Let me know if it changes something for you

**Comment by flankerzo** [comment]
hello, i downloaded it, and try it.

**Comment by flankerzo** [comment]
it looks like it works nicely. thank you
