### ISSUE TITLE
Anime Matrix display bug

### ISSUE THREAD

**Issue by yudapedia** [seerge/g-helper#241]
**Describe the bug**
G-helper Anime Matrix "Clock" is not properly displayed.

**Clear scenario to Reproduce**
1. Go to Anime Matrix'
2. Choose either Dim/Medium/Bright
3. Choose Clock

**Expected behavior**
Anime Matrix showing properly.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11228139/log.txt)

**Screenshots or screencasts**
![image](https://user-images.githubusercontent.com/61176703/231924895-29637504-9b3b-4608-a240-ced650eee465.png)
G-14 Setting; Bright, Clock

**Desktop (please complete the following information):**
 - OS: Windows 11
 - G14 2022 GA402RK (1080p 144 Hz) version

**Asus software**
- Armoury crate is NOT installed
- MyASUS installed
- Other Asus services running in background

**Comment by seerge** [comment]
Hello, can you try to set this picture on animematrix and make a photo of how it looks? Thanks

![icons8-data-grid-100](https://user-images.githubusercontent.com/5920850/232001082-70f4a39a-037f-4c19-a536-12f04db570d6.png)

**Comment by seerge** [comment]
@yudapedia can you try this build ?
[GHelper.zip](https://github.com/seerge/g-helper/files/11232029/GHelper.zip)

**Comment by yudapedia** [comment]
Both pictures are taken using the 0.53 build you attached.

![IMG_20230414_213046](https://user-images.githubusercontent.com/61176703/232074021-eda84b0d-d24f-4afe-be6b-5e09b2c93a7c.jpg)

![IMG_20230414_212820](https://user-images.githubusercontent.com/61176703/232074143-6611dd3f-0d97-4d07-b7c6-74ac483b132b.jpg)

**Comment by seerge** [comment]
Ok, so i assume clock looks ok now? :)

**Comment by yudapedia** [comment]
Thank you!

**Comment by seerge** [comment]
Great, i'll push it live along 0.53 then
