### ISSUE TITLE
G14 (GA401QM) M1 Key Functionality Failure: Potential Correlation with BIOS Settings Modified by GHelper

### ISSUE THREAD

**Issue by Waximell** [seerge/g-helper#2416]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The M1 key on my laptop (GA401QM5900) has lost its functionality, and I recall a bug report mentioning this issue in previous releases. Historically, the M1 key has become unresponsive after the laptop has been in sleep mode for an extended period, but it has always returned to normal after a reboot. However, recently, the M1 key has completely stopped working.

I have tried versions 164, 161, and 158, but none of them have improved the situation. Since the M1 key was functional on version 158 before upgrading to 161, I believe the issue is not related to the software version, and I have not continued to test earlier releases. Additionally, I have attempted to upgrade the BIOS to version 415, but it did not resolve the issue. I also tested the functionality of the M1 key on another operating system (chromeos) and found that it did not work properly.

However, after a complete reinstallation and update of Armoury Crate to the latest version, the M1 key resumed working, indicating that the issue is not hardware-related. Subsequently, when I switched back to the other system, the M1 key also resumed working. I suspect that some changes made to the BIOS by GHelper might have caused this issue, and it may be an ongoing process.

Therefore, I am submitting this issue and kindly request a fix. Thank you for your attention and assistance.

### How to reproduce the bug?

I'm not sure why this is happening, and it seems to be a chronic issue. 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14919323/log.txt)

### Device and Model

Asus Zephyrus G14 (GA401QM)

### Additional information.

Furthermore, I am not sure if the F11 and F12 keys (sleep mode and airplane mode) are also affected. Their behavior seemed inconsistent before and after reinstalling Armoury Crate, but I had not paid close attention to them previously, so I cannot provide any meaningful information.

Please note that I do not have the ability to read or write code, and I can only provide information based on logic and testing. I apologize for any inconvenience.

The language I use is not English, and the above is from AI translation. If there are any inaccurate or unclear expressions, please ask me.

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.164, 0.161&0.158

### OS

Windows11 23H2 22635 (Beta Release)

**Comment by seerge** [comment]
@Waximell hello,

By default G-Helper doesn't touch your M1/M2 keys at all.  They just emit Volume UP / DOWN keys for windows on hardware level.

Even you you make custom bindings, G-Helper would just listen for Vol UP / DOWN hotkeys in windows itself, and emit other commands instead. If G-Helper is not running, keys will do what they did before.

> The M1 key on my laptop (GA401QM5900) has lost its functionality, and I recall a bug report mentioning this issue in previous releases

There is no BIOS or even hardware interaction here, and have never been, and obviously there is no "bug reports" mentioning this before :) 

> However, after a complete reinstallation and update of Armoury Crate to the latest version, the M1 key resumed working, indicating that the issue is not hardware-related. Subsequently, when I switched back to the other system, the M1 key also resumed working. 

You have probably bindend keys with AC before, that does it on hardware level. After getting AC back you have reverted original bindings. You could also do that with a simple hardware reset.

> I suspect that some changes made to the BIOS by GHelper might have caused this issue, and it may be an ongoing process.

**That's not true.**

Closing as there is nothing to fix in a first place.

**Comment by Waximell** [comment]
Got it, I really appreciate your explanation. Regarding the key repair, I believe I might have misremembered things, and I had some misunderstandings about ghelper. In retrospect, it seems that during the reinstallation of Armoury Crate, it automatically performed a hardware reset, which solved my problem. I'm sorry for any inconvenience I may have caused, and thank you once again for your assistance.

**Comment by seerge** [comment]
@Waximell AC can bind (an unbind) keys on hardware level by sending some USB commands (it's not via BIOS anyway). It could be that when you reinstall AC it resets own bindings.

G-Helper doesn't bind keys on hardware level at all in a first place.
