### ISSUE TITLE
stuck on srgb gamut?

### ISSUE THREAD

**Issue by cakiya** [seerge/g-helper#2420]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I noticed the new Visual Mode feature, changed the gamut around a bit, but then I tried to set it back to Native from sRGB and it looked like nothing changed; yet the colors were still a bit washed? I think maybe the Native gamut isn't applying or something, otherwise it should be different, no?

### How to reproduce the bug?

1. have a pristine new g14
2. install ghelper
3. change gamut to sRGB
4. change gamut to Native
5. notice that the colors are washed compared to what Native was before doing anything to gamut setting?

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14936031/log.txt)

(I switched from Native to sRGB, then sRGB back to Native, then uploaded the log)

### Device and Model

Asus Zephyrus G14 GA402XV_GA402XV

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.164.0

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@cakiya hello, I have already replied to you on discord :)

```
4/10/2024 2:03:02 PM: C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_f2eed2fae3b45a67\ASUSOptimization\AsusSplendid.exe 200 0 50
4/10/2024 2:03:03 PM: UIGain: 1.000000 lutDcModeScale: 1.000000 Interval: 1.000000 RDLevels: 5.000000 index: 0.250000 Param: 2, Gamut mode: FFFF Gamut mapping process exit with return code 0 HIT: ulOutBuffer[0] = 512 > 0 this->BiosDataStatus  = 0   ReadResult  = 0  Parsing version = 7 Use Method = 1   bios size = 49 CCTAPI_ERRORCODE = 0 ; HIT: DEF Gain E(0) W(0) ; HIT: Warm Gain E(0) W(0) ; HIT: Cold Gain E(0) W(0) ; HIT: RdW Gain E(0) W(0) ; HIT: RdS Gain E(0) W(0) CCT_Init  result = 0 HIT: ulOutBuffer[0] = 512 > 0 ; HIT: Get bios[297]: 32  scale: 1.000000, Scale TH: 0.100000, nIndex: 26 New ScaleTH: 0.188235 New scale: 1.000000 outlut: [1.000000, 0.996078, 0.984314]
````

**AsusSplendid.exe 200 0 50** - is what Armoury runs under the hood when you set Native color gamut as well.

So check: 

- Do you have Visual mode set to Default / color temp to Neutral ? does changing it back and forward to something make a difference ? 
- Windows ``Color Management`` app, what color profile is set there for your display ? 
- Uncheck that profile at all (i.e. disable windows color management) - do you see changes ?

**Comment by cakiya** [comment]
**"fixed"?:I** think I am just dumb haha; I followed your P.S. and checked my wallpaper and switched from sRGB to Native and back and it seems like sRGB is just a bit duller... But on my grey/dimmed theme chrome and discord and file explorer and such I don't see a difference because it's not that colorful. Maybe my eyes are just tired today...

Checks:
- Yes, it's set to Default, Neutral, Gamut: Native. Changing from Default to Racing or other modes makes a difference, Neutral to Warmest/Coldest also makes a difference.
- some ASUS one
![image](https://github.com/seerge/g-helper/assets/43363058/0d87cd64-6530-4d2b-8df5-475a3c8e5da5)
![image](https://github.com/seerge/g-helper/assets/43363058/ea65dc52-15ea-42d6-b1a1-c0a994ca9864)
![image](https://github.com/seerge/g-helper/assets/43363058/4fd2dfb6-bbc2-4ed3-b6db-9b49b470b1a6)
- How do I disable windows color management?
My color profiles should also not be missing, since this is the stock windows (never reset)

**Comment by seerge** [comment]
@cakiya based on your screenshots you have correct (native) color profile. If you would set sRGB it would show ASUS_sRGB  profile there.

So everything is indeed good already.

Ideally you don't want to disable color management. If you want - you either delete ICC profile from the list or uncheck "Use my settings for device"

Closing as answered / resolved as there is nothing to fix.
