### ISSUE TITLE
Undervolting resets after laptop restart

### ISSUE THREAD

**Issue by chockokruasan** [seerge/g-helper#2422]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I use CPU UV -25 for all power modes in g-helper. But every time when I restart laptop UV canceling. It is still "-25" in g-helper settings, but it is "0" actually. I need to push "Apply" in undervolting section every time after restart.

### How to reproduce the bug?

I found this bug by checking CPU performance and CPU Clock speeds after restart and after I apply UV again.

### Logs

11.04.2024 1:48:53: ------------
11.04.2024 1:48:53: App launched: ROG Zephyrus Duo 16 GX650PZ_GX650PZ :0.164.0.0ru-RU
11.04.2024 1:48:53: Matrix control device was not found on your machine.
11.04.2024 1:48:54: NVIDIA GeForce RTX 4080 Laptop GPU
11.04.2024 1:48:54: CPU: 10 - AMD Ryzen 9 7945HX with Radeon Graphics         - AMD64 Family 25 Model 97 Stepping 2
11.04.2024 1:48:54: AutoSetting for Online
11.04.2024 1:48:54: Eco flag : 0
11.04.2024 1:48:54: Mux flag : 0
11.04.2024 1:48:54: \\?\DISPLAY#BOE0BC4#5&1154c9fb&0&UID4354#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
11.04.2024 1:48:54: \\?\DISPLAY#BOE0BC4#5&1154c9fb&0&UID4354#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
11.04.2024 1:48:54: Input available: \\?\hid#vid_0b05&pid_19b6&mi_00&col01#9&af66d83&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 64
11.04.2024 1:48:54: USB 19B6|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
11.04.2024 1:48:54: Input: \\?\hid#vid_0b05&pid_19b6&mi_00&col01#9&af66d83&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
11.04.2024 1:48:54: Miniled: 0 -65536
11.04.2024 1:48:54: NE160QDM-NM4 HDR: False 8 1 False
11.04.2024 1:48:54: Mode = 0 : OK
11.04.2024 1:48:54: Init 19B6: 5D-B9
11.04.2024 1:48:54: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
11.04.2024 1:48:54: Init 19B6: 5D-05-20-31-00-1A
11.04.2024 1:48:54: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
11.04.2024 1:48:54: AuraMode: AuraStatic
11.04.2024 1:48:54: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
11.04.2024 1:48:54: USB 19B6: 5D-B5-00-00-00
11.04.2024 1:48:54: USB 19B6: 5D-B4
11.04.2024 1:48:54: Miniled: 0 -65536
11.04.2024 1:48:54: NE160QDM-NM4 HDR: False 8 1 False
11.04.2024 1:48:54: Monitor Power On
11.04.2024 1:48:54: Lid Open
11.04.2024 1:48:54: Lid 19B6: 5D-BA-C5-C4-01
11.04.2024 1:48:55: Auto 19B6: 5D-BA-C5-C4-01
11.04.2024 1:48:55: Latest version 0.164.0.0
11.04.2024 1:48:59: AuraMode: AuraRainbow
11.04.2024 1:48:59: USB 19B6: 5D-B3-00-03-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
11.04.2024 1:48:59: USB 19B6: 5D-B5-00-00-00
11.04.2024 1:48:59: USB 19B6: 5D-B4
11.04.2024 1:49:01: Design Capacity: 90005mWh, Full Charge Capacity: 91179mWh, Health: 1,0130437197933448141769901672%
11.04.2024 1:49:03: Hibernate after 2147483647
11.04.2024 1:49:07: GET GPU CLOCKS: 0, 0
11.04.2024 1:49:07: GET CLOCK LIMIT: 0
11.04.2024 1:49:07: ReadGPUPowerBase: -65536
11.04.2024 1:49:15: ------------
11.04.2024 1:49:15: App launched: ROG Zephyrus Duo 16 GX650PZ_GX650PZ :0.164.0.0ru-RU.
11.04.2024 1:49:15: Matrix control device was not found on your machine.
11.04.2024 1:49:15: NVIDIA GeForce RTX 4080 Laptop GPU
11.04.2024 1:49:15: CPU: 10 - AMD Ryzen 9 7945HX with Radeon Graphics         - AMD64 Family 25 Model 97 Stepping 2
11.04.2024 1:49:15: AutoSetting for Online
11.04.2024 1:49:15: Eco flag : 0
11.04.2024 1:49:15: Mux flag : 0
11.04.2024 1:49:15: \\?\DISPLAY#BOE0BC4#5&1154c9fb&0&UID4354#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
11.04.2024 1:49:15: \\?\DISPLAY#BOE0BC4#5&1154c9fb&0&UID4354#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
11.04.2024 1:49:15: Miniled: 0 -65536
11.04.2024 1:49:15: NE160QDM-NM4 HDR: False 8 1 False
11.04.2024 1:49:15: Input available: \\?\hid#vid_0b05&pid_19b6&mi_00&col01#9&af66d83&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 64
11.04.2024 1:49:15: USB 19B6|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
11.04.2024 1:49:15: Input: \\?\hid#vid_0b05&pid_19b6&mi_00&col01#9&af66d83&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
11.04.2024 1:49:15: Init 19B6: 5D-B9
11.04.2024 1:49:15: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
11.04.2024 1:49:15: Init 19B6: 5D-05-20-31-00-1A
11.04.2024 1:49:15: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
11.04.2024 1:49:15: AuraMode: AuraRainbow
11.04.2024 1:49:15: USB 19B6: 5D-B3-00-03-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
11.04.2024 1:49:15: USB 19B6: 5D-B5-00-00-00
11.04.2024 1:49:15: USB 19B6: 5D-B4
11.04.2024 1:49:15: Miniled: 0 -65536
11.04.2024 1:49:15: NE160QDM-NM4 HDR: False 8 1 False
11.04.2024 1:49:15: GET GPU CLOCKS: 0, 0
11.04.2024 1:49:15: GET CLOCK LIMIT: 0
11.04.2024 1:49:15: ReadGPUPowerBase: -65536
11.04.2024 1:49:15: UV: -25 OK
11.04.2024 1:49:15: iGPU UV: -20 
11.04.2024 1:49:15: Monitor Power On
11.04.2024 1:49:15: Lid Open
11.04.2024 1:49:15: Lid 19B6: 5D-BA-C5-C4-01
11.04.2024 1:49:16: Auto 19B6: 5D-BA-C5-C4-01
11.04.2024 1:49:16: Latest version 0.164.0.0
11.04.2024 1:49:17: UV: 0 OK
11.04.2024 1:49:18: Power Mode 00000000-0000-0000-0000-000000000000 -> ded574b5-45a0-4f42-8737-46345c09c238:OK
11.04.2024 1:49:18: Mode = 1 : OK
11.04.2024 1:49:18: GET GPU CLOCKS: 0, 0
11.04.2024 1:49:18: GET CLOCK LIMIT: 0
11.04.2024 1:49:18: ReadGPUPowerBase: -65536
11.04.2024 1:49:21: UV: -25 OK
11.04.2024 1:49:21: iGPU UV: -20 
11.04.2024 1:49:23: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
11.04.2024 1:49:23: Mode = 2 : OK
11.04.2024 1:49:23: GET GPU CLOCKS: 0, 0
11.04.2024 1:49:23: GET CLOCK LIMIT: 0
11.04.2024 1:49:23: ReadGPUPowerBase: -65536
11.04.2024 1:49:25: UV: 0 OK
11.04.2024 1:49:27: UV: -25 OK
11.04.2024 1:49:27: iGPU UV: -20 
11.04.2024 1:49:28: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a -> 00000000-0000-0000-0000-000000000000:OK
11.04.2024 1:49:28: Mode = 0 : OK
11.04.2024 1:49:28: GET GPU CLOCKS: 0, 0
11.04.2024 1:49:28: GET CLOCK LIMIT: 0
11.04.2024 1:49:28: ReadGPUPowerBase: -65536
11.04.2024 1:49:30: UV: 0 OK
11.04.2024 1:50:36: ------------
11.04.2024 1:50:36: App launched: ROG Zephyrus Duo 16 GX650PZ_GX650PZ :0.164.0.0ru-RU.
11.04.2024 1:50:36: Matrix control device was not found on your machine.
11.04.2024 1:50:36: NVIDIA GeForce RTX 4080 Laptop GPU
11.04.2024 1:50:36: CPU: 10 - AMD Ryzen 9 7945HX with Radeon Graphics         - AMD64 Family 25 Model 97 Stepping 2
11.04.2024 1:50:36: AutoSetting for Online
11.04.2024 1:50:36: Eco flag : 0
11.04.2024 1:50:36: Mux flag : 0
11.04.2024 1:50:36: Input available: \\?\hid#vid_0b05&pid_19b6&mi_00&col01#9&af66d83&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 64
11.04.2024 1:50:36: USB 19B6|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
11.04.2024 1:50:36: Input: \\?\hid#vid_0b05&pid_19b6&mi_00&col01#9&af66d83&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
11.04.2024 1:50:37: \\?\DISPLAY#BOE0BC4#5&1154c9fb&0&UID4354#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
11.04.2024 1:50:37: \\?\DISPLAY#BOE0BC4#5&1154c9fb&0&UID4354#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
11.04.2024 1:50:37: Miniled: 0 -65536
11.04.2024 1:50:37: NE160QDM-NM4 HDR: False 8 1 False
11.04.2024 1:50:37: Mode = 0 : OK
11.04.2024 1:50:37: Init 19B6: 5D-B9
11.04.2024 1:50:37: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
11.04.2024 1:50:37: Init 19B6: 5D-05-20-31-00-1A
11.04.2024 1:50:37: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
11.04.2024 1:50:37: AuraMode: AuraRainbow
11.04.2024 1:50:37: USB 19B6: 5D-B3-00-03-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
11.04.2024 1:50:37: USB 19B6: 5D-B5-00-00-00
11.04.2024 1:50:37: USB 19B6: 5D-B4
11.04.2024 1:50:37: Monitor Power On
11.04.2024 1:50:37: Lid Open
11.04.2024 1:50:37: Lid 19B6: 5D-BA-C5-C4-01
11.04.2024 1:50:37: Session:SessionUnlock
11.04.2024 1:50:37: \\?\DISPLAY#BOE0BC4#5&1154c9fb&0&UID4354#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
11.04.2024 1:50:37: \\?\DISPLAY#BOE0BC4#5&1154c9fb&0&UID4354#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
11.04.2024 1:50:37: Miniled: 0 -65536
11.04.2024 1:50:37: NE160QDM-NM4 HDR: False 8 1 False
11.04.2024 1:50:38: Auto 19B6: 5D-BA-C5-C4-01
11.04.2024 1:50:41: HID Device Event: Checking for new ASUS Mice
11.04.2024 1:51:24: The process cannot access the file 'C:\Users\insgt\AppData\Roaming\GHelper\config.json.bak' because it is being used by another process.
11.04.2024 1:51:29: The process cannot access the file 'C:\Users\insgt\AppData\Roaming\GHelper\config.json.bak' because it is being used by another process.
11.04.2024 1:51:32: The process cannot access the file 'C:\Users\insgt\AppData\Roaming\GHelper\config.json.bak' because it is being used by another process.
11.04.2024 1:51:58: Miniled: 0 -65536
11.04.2024 1:51:58: NE160QDM-NM4 HDR: False 8 1 False
11.04.2024 1:51:59: Latest version 0.164.0.0
11.04.2024 1:52:07: Hibernate after 2147483647

### Device and Model

Asus Zephyrus duo 16 GX650PZ

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.146.0

### OS

Windows 11 23H2

**Comment by nathancdy** [comment]
@chockokruasan check the comment on here #2421

**Comment by seerge** [comment]
@chockokruasan hello, you need to check ``Auto Apply`` if you want it to be applied every time. 

It's absolutely intentional and done as idiot-protection to prevent people setting inadequate values w/o testing them with a regular ``Apply`` button.
