### ISSUE TITLE
밸런스 모드에서 게임을끄고난후 온도가 내려가도 팬 rpm 속도가 줄지 않습니다

### ISSUE THREAD

**Issue by Duck5436** [seerge/g-helper#2425]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

밸런스 모드에서 게임을끄고난후 온도가 내려가도 팬 rpm 속도가 줄지 않습니다
게임이 시작하면 rpm이 4000 까지 오르는데
게임을 끝후에 온도가 내려가도 팬 rpm속도가 줄지않고 한참뒤에 너무많은시간이 흐른뒤에 조금씩 줄어듭니다
이미 온도가 내려간지는 오래됫는데 너무시끄럽습니다 아무래도 버그같은데 확인좀 부탁드립니다

### How to reproduce the bug?

발란드 모드에서 고사양게임을 구동후 게임을끄고 팬 rpm속도가 줄어드는 속도를 확인해보십시요~

### Logs

시스템: ASUS ROG Strix G713PI_G713PI

### Device and Model

시스템: ASUS ROG Strix G713PI_G713PI

### Armoury Crate

Uninstalled

### OS

win 11

**Comment by Duck5436** [comment]
수동으로 모드를 바꾸면 팬속도가 정상적으로 줄어듭니다

**Comment by Duck5436** [comment]
수동으로 모드를 체인지해주면
온도가 정상적으로 줄어 듭니다

**Comment by seerge** [comment]
>  I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.
