### ISSUE TITLE
CPU Power Limit Sliders (PL1, PL2) have no effect on ASUS TUF F15 FX507VV

### ISSUE THREAD

**Issue by serhi000** [seerge/g-helper#2429]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

CPU Power Limit Sliders (PL1, PL2) have no effect on ASUS TUF F15 FX507VV (i7-13620H) (BIOS 327, also 325) in any power mode (Silent, Balanced or Turbo).  CPU still uses as much power as is set in BIOS for each Power Mode. CPU benchmark is run immediately after setting power values and applying. No effect.

Windows power plan is set to Balanced. Armoury Crate is uninstalled. [Microsoft .NET 7] and [Asus System Control Interface] installed. Asus Services running : 0.
GPU settings like Core Clock Limit, Dynamic Boots or Temperature Target all working.

![Screenshot 20240413-120500_cr](https://github.com/seerge/g-helper/assets/166917849/a7a14e51-7b85-4ba6-8eae-f7b7aa842dda)

However Throttlestop can limit PL1 and PL2 without problems. But then PL1 and PL2 stay the same regardless what power mode I use.

Regards,
Sergei

### How to reproduce the bug?

1. Go to "Fans + Power"
2. Set PL1 and PL2 to 45W and 55W accordingly. (Can be different values)
3. Tick "Apply Power Limits"

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14967268/log.txt)

### Device and Model

ASUS TUF F15 FX507VV

### Additional information.

{
  "performance_mode": 0,
  "charge_full": 0,
  "performance_1": 0,
  "gpu_mode": 1,
  "internal_display": "B156HAN15.H ",
  "screen_max": 144,
  "frequency": 120,
  "overdrive": 0,
  "mid_fan": 0,
  "xgm_fan": 0,
  "fan_profile_cpu_0": "1E-32-41-45-4D-51-60-61-00-01-07-0C-1E-29-33-64",
  "fan_profile_gpu_0": "1E-32-41-45-4D-51-60-61-00-01-05-0A-19-20-2C-64",
  "limit_total_0": 45,
  "limit_slow_0": 55,
  "limit_cpu_0": 43,
  "limit_fast_0": 80,
  "auto_apply_power_0": 1
}

Even if I set all limits to 45 it does not work:
  "limit_total_0": 45,
  "limit_slow_0": 45,
  "limit_cpu_0": 45,
  "limit_fast_0": 45,

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.165.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@serhi000 hello, 

Some models require both custom Fan Curves **and** Power limits to be applied together in order to make power limits work (as in Armoury's Manual Mode you apply all together)

Can you try to ``Apply Custom Fan Curve`` next to power limits and check if power limits work then ?

Thanks.

**Comment by serhi000** [comment]
It works! Thanks!

**Comment by seerge** [comment]
@serhi000 great, I have added your model to the list of devices that require custom fan curve. And now G-Helper will set it automatically under the hood if limits are applied (so you don't need to check it anymore)

Try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14967532/GHelper.zip)

Thanks
