### ISSUE TITLE
Excessive CPU power consumption

### ISSUE THREAD

**Issue by maxlokus** [seerge/g-helper#243]
## NOTE
Hi there. The app is amazing and much better than AC in many ways. But there is a severe problem that stops me from using it further.
Laptop - ASUS Rog Strix SCAR 18 (13980hx) 2023.

**Describe the bug**
In benchmarks and dozens of modern games with G-Helper enabled CPU behaves similarly or very close to how it does with AC profiles. It has all been great n fun until I started testing out BF2042.

While using G-Helper (Balanced or Turbo profile) in game CPU gets 'locked' in high power usage mode, which may seem ok since it's a high-end gaming laptop and it is kinda expected to reach the max performance possible. But it's not how it works when AC profile enabled instead. On average with G-helper CPU sits at 100-135W range, while with AC it stays around 60W at all times, rarely spiking to 80W or more.

Here's a G-Helper Balanced mode example after ~15s after game start
![image](https://user-images.githubusercontent.com/42637419/231990518-1b108156-4736-4120-8a28-7a8b5aeecf7f.png)
This is after a few minutes, when throttling fully kicks in (see FPS difference, temps are still insane)
![image](https://user-images.githubusercontent.com/42637419/231990716-f538281e-a32c-4dce-bbbd-f5dcc16bb1cc.png)
And this is if I quit G-helper and enable AC profile in the same game few seconds later 
![image](https://user-images.githubusercontent.com/42637419/231991306-53137a3a-fc82-47ad-926f-51385e46bcf6.png)

As you can see AC steers the clocks a bit lower and wattage **much** lower, while preserving same or better performance. 
_Note_: I've tested it more extensively over past two weeks: 
- with AC fully deleted and present
- playing short games and 1 hour or more (frying my CPU to a crisp) to eliminate turbo boost short term power limit differences and etc
- setting different profiles, restarting the system, letting it cool down fully to 40C and then trying again
- and many other scenarios
But eventually it all comes down to the same example above.
My main concern is that in this 'locked' mode it gets overheated (98-100C all the time) and throttled down pretty much instantly. I bet it's not even safe to be in this state for hours long.
I think important note is that this happens in only one game so far. The rest are totally fine as I said before. But I'm sure there should be more cases like this, I just ran out of SSD capacity at the moment to test more games lol.
Also there was one or two times when having G-helper profile enabled it was able to behave reasonably, but I couldn't quite catch the combination of events allowing that 😔.

**Clear scenario to Reproduce**
1. Enable G-Helper profile (Balanced or Turbo)
2. Launch BF2042 with 13980HX (or other high end CPU - or may be this CPU specifically though)
3. Wait a few seconds for CPU to start banging 100C

**Expected behavior**
CPU power and clocks should be adjusted reasonably like they do with Armoury Crate

**App Logs**
Log: 
[log.txt](https://github.com/seerge/g-helper/files/11230751/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 11 pro
 - Laptop model:  ASUS Rog Strix SCAR 18 (13980hx) 2023.

**Asus software**
- Armoury crate - tried with both installed and uninstalled
- MyASUS installed - yes
- Other Asus services running in background - those related to the above

**Additional context**
I'd imagine this is something real hard to debug, but I still have hope 😊

**Comment by seerge** [comment]
Hello, app doesn't control behavior of your CPU / GPU in real time, it just sets a setting the moment you click a button :)

What you explain here - could be related to "nvidia dynamic boost" when GPU takes some power from CPU. I think it can be controlled either in nvidia control panel / or msi afterburner (for example).

What you can do to tame CPU temps - is to limit corresponding PPTs in fans+power (to desired 80w for example or less), then it won't heat that much + you GPU will have more headroom to work.

I do literally that for my battlefield 2042 sessions (keep in mind that G14 is much less powerhungry so numbers are lower)
![Screenshot 2023-04-14 114815](https://user-images.githubusercontent.com/5920850/232010732-f33121f5-8ba3-457e-bc44-cec20c34df17.png)

**Comment by maxlokus** [comment]
I don't see how GPU boost is related. Being able to boost GPU means taking 25W away on rare occasions, not banging 120W on CPU instead of 60 all the time. 
Manually limiting CPU power is a solution, but a bad one for two reasons:
1. This is literally a limit meaning it won't be able to efficiently process random short CPU heavy scenarios (eg. a bunch of particles/explosions). Thus lower FPS or stutters even. During AC profile it does 65W most of the time, and if the need arises it spikes up for a second to handle the tight spot.
2. I tried different limits and the problem stays - it sits exactly at the limit 100% of time. Say, I set 80W so that it won't be 100C at least, but it stays 79-80W the whole time no matter what. If I set a lower value  I end up with a loss of performance for now reason as described in the point above. 
So eventually this still means higher temps, worse performance and this is not how modern CPU should behave.

**Comment by maxlokus** [comment]
@seerge Also the game often crashes or won't event launch with power limit set to 80W

**Comment by seerge** [comment]
Well, i can’t do much here . As i’ve mentioned app does do all that balancing you are talking about, your system/drivers do

**Comment by maxlokus** [comment]
Is there anything particular I can look into? CPU related. The only variable is see now is either G-Helper or AC active

**Comment by seerge** [comment]
what cpu sliders do you have in armory?

**Comment by maxlokus** [comment]
I don't use manual (where the sliders are). Not sure what settings are on performance mode

**Comment by seerge** [comment]
Then modes should be same , as they are stored in bios not in app.

You can also select each mode without any app at all by running following command in powershell as admin:

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00120075, Value)
```
Values: **0 - Balanced, 1 - Turbo, 2 - Silent.**

It could be that in your case armoury also applies some custom settings behind the scene (like limiting CPU power), that's why i suggested to do same :)

I'm not aware of any other settings you can set via asus driver / bios next to cpu limits that can limit cpu power

**Comment by maxlokus** [comment]
> It could be that in your case armoury also applies some custom settings behind the scene (like limiting CPU power), that's why i suggested to do same :)

Yes, this is what I hoped could be investigated
