### ISSUE TITLE
Custom keybind isnt working?

### ISSUE THREAD

**Issue by wyascorn** [seerge/g-helper#2430]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

So basically I want to set my m4 button to imiate the mouse middle button click. I tried putting in both the Constant and the keycode for it fromhttps://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes. It simply just doesn't work.

### How to reproduce the bug?

![image](https://github.com/seerge/g-helper/assets/84992554/17c0184f-c712-49d8-b161-91ee9ca68ef6)

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14968662/log.txt)

### Device and Model

ROG Zephyrus  G15 GA503RM

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.165

### OS

W11 22H2

**Comment by wyascorn** [comment]
Also do you have like a discord server related to ghelper

**Comment by seerge** [comment]
@wyascorn hello, i have checked. And apparently that windows API that app is using is working only for keys, not mouse events.
You can try to use Autohotkey or similar app to emit that tho.

What is the practical purpose of emitting mouse clicks ?

**Comment by wyascorn** [comment]
Uhh I smashed my dpi button on my mouse so I have to use the software to change it I was hoping I could change the m4 on keyboard to my middle button and change the actual middle button on my mouse to the dpi switch

Middle Mouse Button -> DPI Toggle
M4 On keyboard -> Middle Mouse Button

**Comment by seerge** [comment]
@wyascorn try this build, it should support Left (``0x01``), Right (``0x02``) and Middle (``0x04``) mouse button clicks from ``Custom``

[GHelper.zip](https://github.com/seerge/g-helper/files/14970248/GHelper.zip)

**Comment by wyascorn** [comment]
Thank you it works

**Comment by seerge** [comment]
@wyascorn great
