### ISSUE TITLE
Boost mode explanation: especially for efficient enable / effcient aggresive, which of these all more powerful ? perf rank of all modes ?

### ISSUE THREAD

**Issue by jiangying000** [seerge/g-helper#2433]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I want Boost mode explanation: especially for efficient enable / effcient aggresive, which of these all more powerful ? perf rank of all modes ?

### Describe the solution you'd like

doc or details on dropdown menus

### Device and Model

zenbook

**Comment by seerge** [comment]
@jiangying000 hello, please check this topic https://github.com/seerge/g-helper/discussions/916 

Thanks
