### ISSUE TITLE
Info on Keybinds 

### ISSUE THREAD

**Issue by rbgk** [seerge/g-helper#2441]
@johnsmith8124 as mentioned above (and in readme) profiles (with all settings inside including PPTs) you can switch with FN+F5 or Ctrl + Shift + F5 (for external keyboards)

_Originally posted by @seerge in https://github.com/seerge/g-helper/issues/357#issuecomment-1546751317_
            
Hey! Both FN+F5 and Ctrl+Shift+F5 work on my laptop, no external keyboard. Is this normal?

I'm also wondering if Ctrl+Shift+F5 is the default, or if it can be customized -- I have it as a keybind but it isn't being read since GHelper would use it to switch the modes instead.

**Comment by rbgk** [comment]
Solved upon actually searching further 

https://github.com/seerge/g-helper/issues/2223

**Comment by seerge** [comment]
@rbgk you can rebind them in config https://github.com/seerge/g-helper/wiki/Power-user-settings#toggle-performance-mode-or-toggle-app-window-key-binding
