### ISSUE TITLE
add support for Vivobook M1405

### ISSUE THREAD

**Issue by thinhkhuat** [seerge/g-helper#2445]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hi, my Vivobook M1405YA with AMD Ryzen 5 7530 and an OLED screen at 2880x1800 does not show the OLED features with the latest build of G-Helper. I tried downloading the source code and modified the app.config file with a || ContainsModel(M1405) to the isOLED() function and successfully got the OLED features showed up, including the flicker-free dimming (with the .icc profile put in the GameVisual folder manually). 
However, it seems the function-lock feature is not working correctly. I tried the script you posted in other threads that involving WMI method sth and it returned the 65636 - true values for both the ON and OFF states (triggered manually). Due to this problem, the hotkeys also doesn't work, not allowing any kind of hotkeys like fn+C, fn+V or fn+F4 .....
I tried disabled the fn lock in MyAsus, Bios but no luck. The fn lock status in GHelper always reports the other way comparing to the Asus fn lock status. 

### Describe the solution you'd like

For OLED features, it seems simple enough to add support for this Vivobook model. Please add support for it when you have time, I really appreciate your support and the quality of GHelper. It's an essential tool for me when using 2 Asus laptops now. 
for the fn-lock problem, I understand by reading other threads that support for fn lock will not work because GHelper couldn't get the status and sync its feature with Asus's implementation. 
However, it seems you could somehow reset the fn lock status at launch of GHelper and as I understand from the other threads, it worked for others. But in my Vivobook M1405, it does not. I tried reading and modifying the InputDispatcher to get a temp fix but couldn't do so, probably too complicated for me to do so :( 
Thank you very much!

### Device and Model

Asus Vivobook M1405YA

**Comment by seerge** [comment]
@thinhkhuat hello, you are mixing multiple things together.

### For Dimming / Visual modes 

Your model indeed needs to be added to config. Please check this build it should enable features on your model. I think for Vivobooks you don't need GameVisual folder even, as ``AsusSplendid.exe`` can fallback to other folder where Vivo / Zenbooks store their profiles as well

[GHelper.zip](https://github.com/seerge/g-helper/files/15008635/GHelper.zip)

### FN-Lock

Most Vivobooks / Zenbooks have own hardware FN-Lock. It's toggled via ``FN+ESC``. App already can handle that hotkey and process fn-lock accordingly. So please check that.

Keep in mind, that if you have Asus Services running - they will interfere (and also toggle fn-lock). So you need to stop them via ``Extra`` settings.

### Hotkeys

Most probably your device simply doesn't support FN+C or FN+V, as they produce no keycode. You can check app log in realtime after pressing them, if there are no WMI EVENT or KEY CODE appearing in the log, those hotkeys are not supported on your device and therefore can't be processed.

**Comment by thinhkhuat** [comment]
Hi, thank you very much for your swift reply. I do apologise for the mix up, bcoz English is not my 1st language so probably I couldn't make myself clear. Let me try to explain things to you again:

1. Your build you've given me indeed worked like a charm, with flicker-free dimming showed up, the gamut feature worked, with dimming the brightness kept the gamut option chosen intact. Thank you very much! 

2. Fn-lock: Thing is, when the Asus's Fn-lock ON, the status of that feature reported by G-Helper will be OFF, and vice-versa. And because I've disabled the Asus Services via the Extra menu, there'll be only 1 way to know the status of that Fn-lock feature and that is by the G-Helper's notifications. So, it will always be like this: Fn-lock feature is ON in reality but G-Helper will report it is OFF. And when I deliberately turned OFF Fn-lock by Fn-ESC, the notification from G-Helper will be that it is ON. 
This situation makes it quite confusing.
3. Regarding the hotkeys function, it seems my model will not work with any Fn+keys combos. 
My keyboard does not have any M key. 

It has F1 for Mute, F2 for Volume down, F3 for V-Up, F4 for Brightness down, F5 for B-up, F6 for touchpad On/Off, F7 is blank, F8 is for screen-mirror options, F9 for Mute the Mic, F10 is blank, F11 for screenshots, F12 is the MyAsus key. 

All of these keys will work when Fn-lock status reported OFF by GHelper (which is ON in reality). Keys that would work when binding by the extra menu will be the MyAsus key (F12) and by choosing the M4/ROG option. I can set it up to open GHelper, toggle different modes, screen on/off, lock screen, toggle fn-lock but that will be it.
None of the Visuals/Dimming option will work with F12 key, or any of the other fn-keys, like F2 or F3 to set the brightness. It will only work with Volume. (I assume that those F2-F3 will be M1 M2 accordingly since they all share the same Volume up/down function). The F9 for Mute the Mic will react to the M3 option in GHelper menu, and could respond to all the functions mentioned above, but not the Brightness up/down function.
And of course the Fn+C or V or F4 will not work, nothing showed up in logs.txt. 

Thank you so much for the time and effort you've spent to create this little wonderful tool. I really appreciate your work.
Have a nice day!

**Comment by seerge** [comment]
@thinhkhuat 

> So, it will always be like this: Fn-lock feature is ON in reality but G-Helper will report it is OFF. And when I deliberately turned OFF Fn-lock by Fn-ESC, the notification from G-Helper will be that it is ON.
This situation makes it quite confusing.

When FN Lock is turned OFF - you need to press FN + F-key in order to get special function
When FN Lock is turned ON - you just press F-leu to get that function

If it's not the case, it could be that your device has everything upside-down comparing to other Vivobooks. 
Please upload app logs here so I can check

Keep in mind, that FN-Lock in your case is **handled by hardware**, G-Helper can only send a command to toggle it. 

> And of course the Fn+C or V or F4 will not work, nothing showed up in logs.txt.

Then there is nothing I can do here.

**Comment by seerge** [comment]
@thinhkhuat any updates on the matter ?

**Comment by thinhkhuat** [comment]
> @thinhkhuat any updates on the matter ?

Hi, sorry i was overwhelmed with work, there was an emergency matter so I had to focus on that. Just when I was done, I got your message :) 
So to answer your questions, I have to make it VERY CLEAR that when I say ON in reallity, it's on by ASUS's system, and not reported by GHelper. 

When ON in reality, it works when pressing F1 for mute, F2 to decrease volume, and so on. 
When ON by GHelper, it will not do those things, and act like normal function rows with F1 to open help page .....

So yes, it might have the Fn thingy up side down as you reckoned. 
I've uploaded the log.txt here for your investigation. 

I really would like to bind some hotkeys to do flicker-free dimming, as the brightness control that Asus's Fn system does will engage the default Windows's method to +/- brightness, not the flicker-free method implemented by you or MyAsus. With that default method by Windows, anything below 60% will not be flicker-free, as you have known. 

Thank you, and apologise for the late reply again. 

[log.txt](https://github.com/seerge/g-helper/files/15027298/log.txt)

**Comment by seerge** [comment]
@thinhkhuat ok, 

Try this build, it should invert fn-lock for your model
[GHelper.zip](https://github.com/seerge/g-helper/files/15027462/GHelper.zip)

As for Flicker-free dimming you can hold CTRL + FN + F4/F5 it should do the thing.

**Comment by thinhkhuat** [comment]
> @thinhkhuat ok,
> 
> Try this build, it should invert fn-lock for your model [GHelper.zip](https://github.com/seerge/g-helper/files/15027462/GHelper.zip)
> 
> As for Flicker-free dimming you can hold CTRL + FN + F4/F5 it should do the thing.

Hi, now it does not enable Fn-lock somehow.  The notifications I get will be OFF and cannot get it to turn ON by any mean. 
For Ctr Fn F4/5 yes now it does change brightness but still by Windows' default method, not by flickerfree dimming. 

I re upload the log.txt for your references. 
[log.txt](https://github.com/seerge/g-helper/files/15027534/log.txt)

**Comment by seerge** [comment]
@thinhkhuat try this build instead for fn-lock

[GHelper.zip](https://github.com/seerge/g-helper/files/15027561/GHelper.zip)

> For Ctr Fn F4/5 yes now it does change brightness but still by Windows' default method, not by flickerfree dimming.

Problem is that FN+F4/F5 send brightness commands to windows directly on hardware level, so I can't really stop that anyhow from the app

**Comment by thinhkhuat** [comment]
Hi, Fn-lock now works as it should :) Thank you! 
For Ctrl Fn F4/5, it does not, and yes I understand the sending commands to windows thing. But doesn't matter Fn lock is ON or OFF, it does not seem to change brightness at all. But its a thing that can wait :) 
For now, I'm happy Oled features work, Fn-lock toggle works :) 

If you have more time, you could update it with the hotkeys fix in the future, if not - due to the hardware problem then it will still be fine though. You've been really nice and helpful person to all of us by now. Definitely will buy you a cup of coffee to express my gratitude towards your effort. I really appreciate it. 
Thank you again.
Have a nice day!

**Comment by seerge** [comment]
@thinhkhuat my point is that I can't "unbind" fn+F4/F5 from their default behavior.

What hotkeys do you suggest for dimming ?

**Comment by thinhkhuat** [comment]
> @thinhkhuat my point is that I can't "unbind" fn+F4/F5 from their default behavior.
> 
> What hotkeys do you suggest for dimming ?

Yes I understand your concern. I'm not asking you to bind Fn F4/5 to change brightness - that will interfere with windows commands. 
what I meant was to try to bind the OLED dimming actions to some other combos. I don't know, Something that is harmless - such as Fn + any dual keys like + - but I think that will not work. My laptop still has F7 and F10 empty. You could try bind to those empty F-keys it possible. But I'm not so sure that those suggestions of mine will be practical because I do not know the internal mechanism of how those hotkeys work. Juts some ideas on top of my head though :)

**Comment by seerge** [comment]
@thinhkhuat i can’t use fn+(any) combos as in your case they work on hardware level.

Let’s keep like this for now.

I’m closing this as resolved as oled / fnlock is working correctly now
