### ISSUE TITLE
Minor Slash Lighting Bug on Zephyrus G16

### ISSUE THREAD

**Issue by reckthaworlde** [seerge/g-helper#2447]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I uncheck the box "disable on battery", the slash lighting does not immediately start, and I have to then manually reselect one of the brightness modes (other than off), rather than having it just default back to whatever was selected before and turn on.

### How to reproduce the bug?

Have slash lighting set to "disable on battery" in g-helper with the laptop unplugged, and a brightness mode other than "off", then uncheck the box.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15018818/log.txt)

### Device and Model

Zephyrus g16 gu605mz, 2024

### Armoury Crate

Uninstalled

### Asus Services

8

### Version

0.165

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@reckthaworlde hello, what do you mean under "slash lighting does not immediately start" ?

If you had Slash lighting turned ON and just unplugged laptop, it just won't turn OFF when you unplug ? It doesn't have to start again as it would just keep running ?

**Comment by seerge** [comment]
@reckthaworlde check if in this build it behaves differently

[GHelper.zip](https://github.com/seerge/g-helper/files/15022420/GHelper.zip)

**Comment by seerge** [comment]
Great, closing as resolved.
