### ISSUE TITLE
Static Slash Lighting Mode

### ISSUE THREAD

**Issue by reckthaworlde** [seerge/g-helper#2448]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

No.

### Describe the solution you'd like

It was mentioned to me by many people that the Slash Lighting is striking, but also distracting. I think a simple animation that just glows statically would be much appreciated by many people who enjoy the back lighting but don't want to draw too much attention in public.

### Describe alternatives you've considered

The "bit stream" animation is about as close as possible to what I mentioned, but it still very animated and could be distracting.

### Device and Model

Zephyrus g16 gu605mz

**Comment by seerge** [comment]
@reckthaworlde as I was telling here few times, I don't have access to the device anymore, therefore it's extremely difficult to play a piano without actual piano.

I have added some test payload, that COULD BE static white, can you check if it makes a difference ?

It's a new option in Slash Modes dropdown

[GHelper.zip](https://github.com/seerge/g-helper/files/15022630/GHelper.zip)

And post a log from the app

**Comment by AlecMulder** [comment]
Tried this, doesn't seem to change from the previously selected option.

> 4/18/2024 10:02:24 PM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/18/2024 10:02:24 PM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:24 PM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:24 PM: Static:5E-D3-00-00-07-00-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:24 PM: Static:5E-D3-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:24 PM: StaticWhite:5E-D3-00-00-07-FF-FF-FF-FF-FF-FF-FF-00-00-00-00-
4/18/2024 10:02:32 PM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/18/2024 10:02:32 PM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:32 PM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:32 PM: SlashMode:5E-D2-03-00-0C-00-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:32 PM: SlashMode:5E-D3-04-00-0C-01-10-02-19-03-13-04-11-05-12-06-
4/18/2024 10:02:32 PM: SlashOptions:5E-D3-03-01-08-AB-FF-01-01-06-FF-FF-00-00-00-00-
4/18/2024 10:02:32 PM: SlashSave:5E-D4-00-00-01-AB-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:39 PM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/18/2024 10:02:39 PM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:39 PM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:39 PM: Static:5E-D3-00-00-07-00-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:39 PM: Static:5E-D3-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:39 PM: StaticWhite:5E-D3-00-00-07-FF-FF-FF-FF-FF-FF-FF-00-00-00-00-
4/18/2024 10:02:46 PM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/18/2024 10:02:46 PM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:46 PM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:46 PM: SlashMode:5E-D2-03-00-0C-00-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:46 PM: SlashMode:5E-D3-04-00-0C-01-12-02-19-03-13-04-11-05-12-06-
4/18/2024 10:02:46 PM: SlashOptions:5E-D3-03-01-08-AB-FF-01-01-06-FF-FF-00-00-00-00-
4/18/2024 10:02:46 PM: SlashSave:5E-D4-00-00-01-AB-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:53 PM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/18/2024 10:02:53 PM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:53 PM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:53 PM: Static:5E-D3-00-00-07-00-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:53 PM: Static:5E-D3-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/18/2024 10:02:53 PM: StaticWhite:5E-D3-00-00-07-FF-FF-FF-FF-FF-FF-FF-00-00-00-00-

**Comment by AlecMulder** [comment]
@seerge no change.

> 4/19/2024 7:40:14 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 7:40:14 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 7:40:14 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 7:40:14 AM: SlashMode:5E-D2-03-00-0C-00-00-00-00-00-00-00-00-00-00-00-
4/19/2024 7:40:14 AM: SlashMode:5E-D3-04-00-0C-01-1A-02-19-03-13-04-11-05-12-06-
4/19/2024 7:40:14 AM: SlashOptions:5E-D3-03-01-08-AB-FF-01-01-06-FF-FF-05-00-00-00-
4/19/2024 7:40:14 AM: SlashSave:5E-D4-00-00-01-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 7:40:25 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 7:40:25 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 7:40:25 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 7:40:25 AM: SlashMode:5E-D2-03-00-0C-00-00-00-00-00-00-00-00-00-00-00-
4/19/2024 7:40:25 AM: SlashMode:5E-D3-04-00-0C-01-1A-02-19-03-13-04-11-05-12-06-
4/19/2024 7:40:25 AM: SlashOptions:5E-D3-03-01-08-AB-FF-01-01-06-FF-FF-00-00-00-00-
4/19/2024 7:40:25 AM: SlashSave:5E-D4-00-00-01-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 7:40:34 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 7:40:34 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 7:40:34 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 7:40:34 AM: Static:5E-D3-00-00-07-00-00-00-00-00-00-00-00-00-00-00-
4/19/2024 7:40:34 AM: Static:5E-D3-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 7:40:34 AM: StaticWhite:5E-D3-00-00-07-FF-FF-FF-FF-FF-FF-FF-00-00-00-00-
4/19/2024 7:40:34 AM: Static:5E-D3-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 7:40:34 AM: SlashOptions:5E-D3-03-01-08-AB-FF-01-01-06-FF-FF-00-00-00-00-
4/19/2024 7:40:34 AM: SlashSave:5E-D4-00-00-01-AB-00-00-00-00-00-00-00-00-00-00-

**Comment by seerge** [comment]
@AlecMulder this is one more attempt. If this one still doesn't make any difference, i'm afraid that's not possible to do w/o having access to the actual device

[GHelper.zip](https://github.com/seerge/g-helper/files/15040182/GHelper.zip)

**Comment by seerge** [comment]
@AlecMulder ok, i'm not sure where the brightness is set,

Can you check if this build is able to change it ?
[GHelper.zip](https://github.com/seerge/g-helper/files/15041609/GHelper.zip)

**Comment by AlecMulder** [comment]
@seerge No Joy. Wish I could help you more but the rest of the app is outside my wheelhouse. 

Is there a simple way to send these commands to the hid device? (if that's even what's going on) Google wasn't much help. I know serial devices.

> 4/19/2024 10:20:11 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:20:11 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:11 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:11 AM: Static:5E-D2-02-01-08-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:11 AM: Static:5E-D3-03-01-08-AC-FF-FF-01-05-FF-FF-00-00-00-00-
4/19/2024 10:20:11 AM: Static:5E-D3-00-00-07-00-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:11 AM: Static:5E-D4-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:11 AM: StaticWhite:5E-D3-00-00-07-FF-FF-FF-FF-FF-FF-FF-00-00-00-00-
4/19/2024 10:20:13 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:20:13 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:13 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:13 AM: Static:5E-D2-02-01-08-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:13 AM: Static:5E-D3-03-01-08-AC-FF-FF-01-05-FF-FF-00-00-00-00-
4/19/2024 10:20:13 AM: Static:5E-D3-00-00-07-00-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:13 AM: Static:5E-D4-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:13 AM: StaticWhite:5E-D3-00-00-07-FF-FF-FF-FF-FF-FF-FF-00-00-00-00-
4/19/2024 10:20:16 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:20:16 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:16 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:16 AM: SlashOptions:5E-D3-03-01-08-AB-FF-01-00-06-00-FF-00-00-00-00-
4/19/2024 10:20:18 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:20:18 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:18 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:18 AM: Static:5E-D2-02-01-08-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:18 AM: Static:5E-D3-03-01-08-AC-FF-FF-01-05-FF-FF-00-00-00-00-
4/19/2024 10:20:18 AM: Static:5E-D3-00-00-07-00-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:18 AM: Static:5E-D4-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:20:18 AM: StaticWhite:5E-D3-00-00-07-FF-FF-FF-FF-FF-FF-FF-00-00-00-00-

**Comment by seerge** [comment]
@AlecMulder try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/15041860/GHelper.zip)

**Comment by seerge** [comment]
@AlecMulder and since you are responding faster than issue starter, can you check if it also fixes this issue https://github.com/seerge/g-helper/issues/2447 (i.e. unchecking "disable on battery" doesn't turn on lighting immediately)

**Comment by AlecMulder** [comment]
@seerge no change unfortunately.

Here I set to bounce and went thought brightness levels, works as expected. Then went to static and through the options, only change is it turns off when set to off.

> 4/19/2024 10:45:44 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:45:44 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:44 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:44 AM: SlashOptions:5E-D3-03-01-08-AB-FF-01-00-06-00-FF-00-00-00-00-
4/19/2024 10:45:46 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:45:46 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:46 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:46 AM: SlashOptions:5E-D3-03-01-08-AB-FF-01-00-06-00-FF-00-00-00-00-
4/19/2024 10:45:48 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:45:48 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:48 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:48 AM: SlashMode:5E-D2-03-00-0C-00-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:48 AM: SlashMode:5E-D3-04-00-0C-01-10-02-19-03-13-04-11-05-12-06-
4/19/2024 10:45:48 AM: SlashOptions:5E-D3-03-01-08-AB-FF-01-01-06-55-FF-00-00-00-00-
4/19/2024 10:45:48 AM: SlashSave:5E-D4-00-00-01-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:51 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:45:51 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:51 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:51 AM: SlashMode:5E-D2-03-00-0C-00-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:51 AM: SlashMode:5E-D3-04-00-0C-01-10-02-19-03-13-04-11-05-12-06-
4/19/2024 10:45:51 AM: SlashOptions:5E-D3-03-01-08-AB-FF-01-01-06-AA-FF-00-00-00-00-
4/19/2024 10:45:51 AM: SlashSave:5E-D4-00-00-01-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:53 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:45:53 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:53 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:53 AM: SlashMode:5E-D2-03-00-0C-00-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:53 AM: SlashMode:5E-D3-04-00-0C-01-10-02-19-03-13-04-11-05-12-06-
4/19/2024 10:45:53 AM: SlashOptions:5E-D3-03-01-08-AB-FF-01-01-06-FF-FF-00-00-00-00-
4/19/2024 10:45:53 AM: SlashSave:5E-D4-00-00-01-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:58 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:45:58 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:58 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:58 AM: Static:5E-D2-02-01-08-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:58 AM: StaticSettings:5E-D3-03-01-08-AC-FF-FF-01-05-FF-FF-00-00-00-00-
4/19/2024 10:45:58 AM: StaticSave:5E-D4-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:45:58 AM: Static White:5E-D3-00-00-07-FF-FF-FF-FF-FF-FF-FF-00-00-00-00-
4/19/2024 10:45:59 AM: Design Capacity: 90005mWh, Full Charge Capacity: 89766mWh, Health: 0.997344591967112938170101661%
4/19/2024 10:46:01 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:46:01 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:01 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:01 AM: Static:5E-D2-02-01-08-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:01 AM: StaticSettings:5E-D3-03-01-08-AC-FF-FF-01-05-AA-FF-00-00-00-00-
4/19/2024 10:46:01 AM: StaticSave:5E-D4-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:01 AM: Static White:5E-D3-00-00-07-FF-FF-FF-FF-FF-FF-FF-00-00-00-00-
4/19/2024 10:46:03 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:46:03 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:03 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:03 AM: Static:5E-D2-02-01-08-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:03 AM: StaticSettings:5E-D3-03-01-08-AC-FF-FF-01-05-55-FF-00-00-00-00-
4/19/2024 10:46:03 AM: StaticSave:5E-D4-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:03 AM: Static White:5E-D3-00-00-07-FF-FF-FF-FF-FF-FF-FF-00-00-00-00-
4/19/2024 10:46:06 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:46:06 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:06 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:06 AM: SlashOptions:5E-D3-03-01-08-AB-FF-01-00-06-00-FF-00-00-00-00-
4/19/2024 10:46:08 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:46:08 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:08 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:08 AM: Static:5E-D2-02-01-08-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:08 AM: StaticSettings:5E-D3-03-01-08-AC-FF-FF-01-05-55-FF-00-00-00-00-
4/19/2024 10:46:08 AM: StaticSave:5E-D4-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:08 AM: Static White:5E-D3-00-00-07-FF-FF-FF-FF-FF-FF-FF-00-00-00-00-
4/19/2024 10:46:10 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:46:10 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:10 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:10 AM: Static:5E-D2-02-01-08-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:10 AM: StaticSettings:5E-D3-03-01-08-AC-FF-FF-01-05-AA-FF-00-00-00-00-
4/19/2024 10:46:10 AM: StaticSave:5E-D4-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:10 AM: Static White:5E-D3-00-00-07-FF-FF-FF-FF-FF-FF-FF-00-00-00-00-
4/19/2024 10:46:12 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
4/19/2024 10:46:12 AM: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:12 AM: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:12 AM: Static:5E-D2-02-01-08-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:12 AM: StaticSettings:5E-D3-03-01-08-AC-FF-FF-01-05-55-FF-00-00-00-00-
4/19/2024 10:46:12 AM: StaticSave:5E-D4-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
4/19/2024 10:46:12 AM: Static White:5E-D3-00-00-07-FF-FF-FF-FF-FF-FF-FF-00-00-00-00-

**Comment by seerge** [comment]
@AlecMulder, brightness for hardcoded modes is set in a different way, so it it's not applicable

I'm trying to find what byte in this payload is brightness
```
StaticSettings:5E-D3-03-01-08-AC-FF-FF-01-05-55-FF
```

Try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/15042107/GHelper.zip)

**Comment by AlecMulder** [comment]
@seerge or perhaps dumb idea, make a bunch of options in that dropdown I can go through?

**Comment by seerge** [comment]
@AlecMulder ok, may be it's not even possible to set a general brightness

I can just set each led to be dimmer
[GHelper.zip](https://github.com/seerge/g-helper/files/15043070/GHelper.zip)

**Comment by AlecMulder** [comment]
@seerge works perfectly. Thanks!

**Comment by seerge** [comment]
@AlecMulder great, thanks for checking. 

Closing as resolved then.

Since you respond fast. If you want - you can try to record payloads from AC to disable slash lighting for sleep / lid closed states in this issues https://github.com/seerge/g-helper/issues/2381

**Comment by AlecMulder** [comment]
Happy to help! I'll check that in a few hours.
