### ISSUE TITLE
Macro

### ISSUE THREAD

**Issue by GuraNotFound** [seerge/g-helper#2449]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I want to use the Macro feature, but if I install Armory Crate it consumes a lot of RAM, some other macro software have to pay or have few features.

### Describe the solution you'd like

I only want to use the Macro feature on G-Helper (if possible)

### Device and Model

ASUS TUF Gaming A15 2021 FA506ICB

### Additional information.

![image](https://github.com/seerge/g-helper/assets/77947043/c0cf6b37-2062-4392-b946-bfefd89e2c37)

**Comment by seerge** [comment]
@GuraNotFound hello,

That's not possible. And this is against whole idea of the app being lightweight. 

If you really need that you can use Autohotkey or any similar app that can emit any macro commands you want :)

Thanks
