### ISSUE TITLE
 Winring0x64

### ISSUE THREAD

**Issue by orenblade** [seerge/g-helper#2453]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

everytime i started my  g14(2024) it will  attempt to open/download for no reason 

refer to image. ( im bad at explaining)

### How to reproduce the bug?

all i need to do is just restarting/turn on(after  shutdown) the laptop lol. kinda annoyed

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15037303/log.txt)

### Device and Model

Asus Zephyrus G14 GA403UU_GA403UU

### Additional information.

![image_2024-04-19_161749855](https://github.com/seerge/g-helper/assets/21033540/ef43e63f-f790-469c-830b-26f9a2ae1764)

### Armoury Crate

Installed

### Asus Services

  0 

### Version

0.166

### OS

11 23h2

**Comment by seerge** [comment]
@orenblade hello. This is simply not true.

App would download winring0 when you **manually** go to ``Fans+Power`` -> ``Advance`` and click ``Download Advanced Settings Pluging``. 

You can check why it's needed in faq https://github.com/seerge/g-helper/wiki/FAQ#whats-the-role-of-winring-file

Thanks
