### ISSUE TITLE
Battery Charge Limit

### ISSUE THREAD

**Issue by Spyxez** [seerge/g-helper#2458]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

it is not working on Asus TUF Gaming FX505DD or am i the only one experiencing this problem? i already set it to any % but it still charging till 100% and my "One time charge to 100%" is off

### How to reproduce the bug?

See Error

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15046934/log.txt)

### Device and Model

Asus TUF Gaming FX505DD

### Armoury Crate

Never installed

### Asus Services

6

### Version

0.165.0

### OS

Windows 10 22H2 OS Build 19045.4239

**Comment by Kikimahe** [comment]
hi,

In your log, you have the optimization service which is executed.
This service uses My ASUS battery limitations which are saved in a config file.

1. Disable all services in Extra.
2. In Ghelper test a charge limit of 80% only (Some models only support 80%.)
This should work.

**Comment by seerge** [comment]
@Spyxez hello, some models support only 80% as charge limit, [please check FAQ](https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working)

**Comment by Spyxez** [comment]
Oh i see.. no wonder i can't limit my charge to what i want(50%) because the model only supports 60% or 80% according to My ASUS Application.. Thank you guys

**Comment by Kikimahe** [comment]
If My Asus offers 60% and 80%, try the **55%** limit ;-)

On my laptop it works in the 55% to 85% range only
Outside of this range it does not work.

**Comment by MrTheenD** [comment]
> If My Asus offers 60% and 80%, try the **55%** limit ;-)
> 
> On my laptop it works in the 55% to 85% range only Outside of this range it doesn't work.

This solved my issue. However it would still say "Battery remaining XX" when hovering over the battery icon as opposed to "Smart charging on" at normal 80% limit. I double checked using HWinfo to be in fact running on AC Power.
