### ISSUE TITLE
GPU fan speed drops to 0 rpm and laptop starts to freeze.

### ISSUE THREAD

**Issue by mock741** [seerge/g-helper#2459]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

GPU fan speed drops to 0 rpm and laptop starts to freeze. Youtube videos becomes slideshow, windows user interface becomes frozen. GPU is in ultimate mode, but temperature does not exceed 55 degrees even when the fan is stopped. After running version 0.165.0 everything returns to normal. BIOS version: 325.

### How to reproduce the bug?

Run G-Helper v. 0.166.0

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15047029/log.txt)

### Device and Model

Asus Strix G16 G614JI

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.166.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@mock741 you clearly did not read FAQ
https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds
