### ISSUE TITLE
Feature request for adding insert and pause with some Fn key combination

### ISSUE THREAD

**Issue by sunilsunny087** [seerge/g-helper#2460]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Its not a problem actually, i work on mainframe terminal all the time and i use insert and pause key which is absent on zephyrus M16, it will be great if you can add it just like what you did with print screen. Please give two more option for key bindings.
Fn lock - when active it works same of you press fn or dont, shouldnt it reverse the keys when active like lets say if Fn lock is off, pressing the F1 will work as F1 and with Fn it will mute the speaker, with Fn lock on, whether you press Fn or not, it just mutes the speaker, F1  cant be achieved in Fn-lock on mode.

### Describe the solution you'd like

two more option for key bindings may be Fn+I and Fn+P. And may be the Fn-lock functionality as described above.

### Describe alternatives you've considered

i used autohotkey(ctl+key) to achieve this but somehow it doesnt pass through vmware. It also can be achieved by going to key binding and chane it there but i like the current bindings, If its not too much work, please consider this.

### Device and Model

Asus Zephyrus M16 2023

**Comment by seerge** [comment]
@sunilsunny087 hello, unfortunately it's not possible. Most of FN+(key) combinations don't emit any keycodes, so you can't bind them to anything.

Only FN+V and FN+C can be mapped to something, and you can already do that via ``Extra`` settings

You can assign them to emit any key you want as explained here
https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-hotkey-actions

Thanks.

**Comment by sunilsunny087** [comment]
Thanks for your reply, Can you please open the Extra Keybindings for editing if possible.

**Comment by seerge** [comment]
@sunilsunny087 

> Can you please open the Extra Keybindings for editing if possible.

What do you mean ? All possible bindings are already editable under ``Extra``

**Comment by sunilsunny087** [comment]
below ones:- 
Extra Keybindings
Ctrl + Shift + F5 / Ctrl + Shift + Alt + F5 - Toggle Performance Modes
Ctrl + Shift + F12 - Open G-Helper window
Ctrl + M1 / M2 - Screen brightness Down / Up
Shift + M1 / M2 - Backlight brightness Down / Up

**Comment by seerge** [comment]
@sunilsunny087 you can change that via config
https://github.com/seerge/g-helper/wiki/Power-user-settings#toggle-performance-mode-or-toggle-app-window-key-binding

I don’t plan adding it to UI to keep main functionality simple

**Comment by sunilsunny087** [comment]
Perfect..thanks so much.. appreciate your quick response

**Comment by Inqurity** [comment]
But also, why are the keys that the app uses (change modes button, disable touchpad button, dicable mic button) are not bindable?
![image](https://github.com/seerge/g-helper/assets/65112064/29fb5f82-5bb4-4f96-ad06-579e77d3f83c)
