### ISSUE TITLE
Black and White Tray Icon: Unsmooth and Jagged Outline

### ISSUE THREAD

**Issue by JuicyCologne** [seerge/g-helper#2463]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

See how it looks jagged, unless it's just me but it is definitely noticeable on my laptop
![Screenshot 2024-04-21 114733](https://github.com/seerge/g-helper/assets/154871924/85b426c8-06e0-4ef8-93e4-9292200747aa)

### How to reproduce the bug?

All I did was had Ghelper's icon on the Taskbar show up rather than being hidden.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15050557/log.txt)

### Device and Model

Asus Vivobook X1500EA

### Additional information.

Even the default icon looks more jagged
![image](https://github.com/seerge/g-helper/assets/154871924/1ee2c933-5334-4b07-bb53-ef2db3ca0e39)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.165.0

### OS

Windows 11 23H2

**Comment by Kikimahe** [comment]
Hi,

I had never seen this before you mentioned it. :)

If we compare to the Windows Defender icon for example, Ghelper's curves are less smooth.
![Capture d'écran 2024-04-21 083201](https://github.com/seerge/g-helper/assets/142881210/e74faf83-48d0-4b02-bcaa-088c5d3e340e)

**Comment by seerge** [comment]
@JuicyCologne hello, what UI scaling do you use?

**Comment by JuicyCologne** [comment]
> @JuicyCologne hello, what UI scaling do you use?
I assume if it was 1920 by 1080 it would be less noticeable? 
![image](https://github.com/seerge/g-helper/assets/154871924/59fbab34-05c3-4ba6-ba16-2c141c7e512f)

**Comment by seerge** [comment]
@JuicyCologne I have exported icons in multiple resolutions, so windows can match different scaling levels a bit better

Try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/15051240/GHelper.zip)

**Comment by JuicyCologne** [comment]
@seerge will try it once I get back home, thanks!

**Comment by JuicyCologne** [comment]
@seerge 
Black and White Tray Icon Issue: Fixed
![image](https://github.com/seerge/g-helper/assets/154871924/3919b7ff-e423-420b-a205-1c07b2eb74f6)
Default GHelper Tray Icon Issue: Still noticeable jagged outlines
![image](https://github.com/seerge/g-helper/assets/154871924/6e00388d-e9ee-4544-bfc7-f759504887b2)

**Comment by seerge** [comment]
@JuicyCologne @Kikimahe 

I have re-created all tray icons for the app from the same template, so they should have identical look

Check this build

[GHelper.zip](https://github.com/seerge/g-helper/files/15051670/GHelper.zip)

**Comment by JuicyCologne** [comment]
@seerge 
Fixed! Thank You!!!!!!!!!!!!!!!
![image](https://github.com/seerge/g-helper/assets/154871924/e988d5b4-d6cc-4094-a66d-22a7d4e0e5ec)

**Comment by Kikimahe** [comment]
Thanks Serge, it’s much smoother. 👍
