### ISSUE TITLE
ROG Strix Impact III Wireless Mouse Support

### ISSUE THREAD

**Issue by nday76** [seerge/g-helper#2464]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I would like a ROG Strix Impact III Wireless Mouse Support from Ghelper.

Currently the mouse is detected as "ROG Harpe Ace Aim Lab Edition".

All the features under "Harpe Ace" seems to work perfectly with Strix Impact III Wireless but I am not sure if they are correct features.

### Describe the solution you'd like

Correct name for the ROG Strix Impact III Wireless on Peripherals category along with correct features for the mouse settings.

### Device and Model

Asus Scar 16 4090 - G634JYR (2024)

**Comment by seerge** [comment]
@nday76 hello, your device is already supported. Can you upload the log form the app?

https://github.com/seerge/g-helper/blob/main/app/Peripherals/Mouse/Models/StrixImpactIIWireless.cs

Also there is a [separate template for peripherals ](https://github.com/seerge/g-helper/issues/new?assignees=&labels=&projects=&template=peripherals_request.yml) with details, can you fill that ?

**Comment by seerge** [comment]
@nday76 hello,

Please fill all requested information according to [Peripherals Issue Template ](https://github.com/seerge/g-helper/issues/new?assignees=&labels=&projects=&template=peripherals_request.yml)

Thanks

**Comment by nday76** [comment]
> @nday76 hello,
> 
> Please fill all requested information according to [Peripherals Issue Template ](https://github.com/seerge/g-helper/issues/new?assignees=&labels=&projects=&template=peripherals_request.yml)
> 
> Thanks

oh snap, i need to install AC?

this is gonna take a while since i dont' have VM set up haha

**Comment by seerge** [comment]
@nday76 well, this is mainly to see what options does your mouse have in AC.

**Comment by nday76** [comment]
> @nday76 well, this is mainly to see what options does your mouse have in AC.

[log.txt](https://github.com/seerge/g-helper/files/15051276/log.txt)

This is the log.(for the time being)

**Comment by seerge** [comment]
@nday76 closing this one, as correct issue is created https://github.com/seerge/g-helper/issues/2465:)
