### ISSUE TITLE
FX507V4 Keboard doesn't light up

### ISSUE THREAD

**Issue by elaine35002** [seerge/g-helper#2467]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

My laptop's keyboard backlight doesn't light up, no matter which mode it is

### How to reproduce the bug?

I used G-helper to make the power limit to 80%, after that, I restarted my laptop, them the keyboard doesn't light up anymore.
I tried  Hardware reset , Reinstalling Asus System Control Interface, and downloaded armouary create to make the keyboard light to defult, but it still doesnt work.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15051615/log.txt)

### Device and Model

Asus Tuf Gaming F15 FX507ZV4

### Armoury Crate

Installed

### Asus Services

9

### Version

0.166

### OS

Windows 10 22H2

**Comment by seerge** [comment]
@elaine35002 is AC able to change backlight settings ?

I also see that you have asus services running, can you stop them from ``Extra`` and try again ?

**Comment by elaine35002** [comment]
> @elaine35002 is AC able to change backlight settings ?
> 
> I also see that you have asus services running, can you stop them from `Extra` and try again ?

No, Ac is not able to turn on the keyboard light. I tried strop Asus Services from G-helper, and then started again, it doesn't help either. Sorry

**Comment by seerge** [comment]
@elaine35002 can you try to find this screen in AC check check / uncheck boxes there 
![image](https://github.com/seerge/g-helper/assets/5920850/93678dcb-9fb6-433c-be56-c17b0d0d1369)

Cause if it doesn't work in AC as well, most probably something is wrong with keyboard itself :) G-Helper won't help here

**Comment by seerge** [comment]
@elaine35002 also try this build and set backlight color to pure RED (this may help if you have non-RGB keyboard with single color)

[GHelper.zip](https://github.com/seerge/g-helper/files/15052174/GHelper.zip)

**Comment by elaine35002** [comment]
> @elaine35002 also try this build and set backlight color to pure RED (this may help if you have non-RGB keyboard with single color)
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/15052174/GHelper.zip)

![image](https://github.com/seerge/g-helper/assets/89692933/b7ea6cb9-0627-4c60-bb94-b0279f73ff98)
I tried to checked and unchecked the box , but it's doesn't help either.

I tried to set the backlight to red, it doesn't light up either :(

**Comment by seerge** [comment]
@elaine35002 ok. Then i'm afraid I can't help anyhow, as it's probably something with keyboard itself.

Try to reboot couple of times, or may be shutdown / start again ...

**Comment by seerge** [comment]
Closing this as unfortunately there is nothing G-Helper can do here, if backlight doesn't work in AC or by turning on / off asus services as well.

Sorry.

Feel free to post any updates, if you will manage to reset it somehow.

Thanks.
