### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Trodenn** [seerge/g-helper#2470]
![image](https://github.com/seerge/g-helper/assets/48042375/680a7c59-7c11-40bd-aba1-a7bd1af433dd)
Just to confirm, the options here refers to whether the keyboard backlight is on during those modes or phases?

**Comment by seerge** [comment]
@Trodenn yes, but keep in mind that boot / shutdown are applicable only for a brief keyboard animation when device starts / shuts down. When windows itself is loading - it's already "awake" state.
