### ISSUE TITLE
(Rog ally) is there a way for you to disable the armory crate button and not the command center button?

### ISSUE THREAD

**Issue by emddiid** [seerge/g-helper#2472]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

is there a way for you to disable the armory crate button and not the command center button?

### Describe the solution you'd like

a solution so I can use the command center button and remap the armory crate button

### Describe alternatives you've considered

I've been looking for a way to block apps but can't seem to figure it out so i idk if you guys can add this or not

### Device and Model

Asus Rog Ally Z1 Extreme

**Comment by seerge** [comment]
@emddiid hello,

I don't think that's possible. Both AC main app and Command center are part of same package, if asus stuff is running - they will keep launching. If it's stopped - they won't

Closing as answered. And this is not related to G-Helper honestly ...
