### ISSUE TITLE
On battry and GPU optimized mode NVDIA settion not disappear. 

### ISSUE THREAD

**Issue by devshahoriar** [seerge/g-helper#2475]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [x] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

![Screenshot 2024-04-22 134200](https://github.com/seerge/g-helper/assets/76418496/8ee1ffec-1b4f-4973-b877-37810d266cfe)

### Describe the solution you'd like

If armory create install when i switch optimized mode on battry nvdia setting auto disappear and they not visible in task meneger . after i plug in my laptop's nvdia software caome as before.

### Device and Model

ASUS TUF Gaming A15 FA507NU_FA507NU

**Comment by seerge** [comment]
@devshahoriar hello, AC may be just killing some nvidia control panel processes. I don't plan to do that to not to cause any unexpected behavior.

It's also better for nvidia stuff to be running already when you enable dGPU again aftwerards

So i don't plan to change that. Thanks
