### ISSUE TITLE
Cpu stuck at 100% when using any ghelper plan

### ISSUE THREAD

**Issue by TriTriTheCuber** [seerge/g-helper#2476]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The cpu is stuck at 100% when using any GHelper plan, but stops when using an armoury crate plan. It also lags out any game, making ghelper unusable.

### How to reproduce the bug?

I just open GHelper and select a power plan, (silent, balanced, etc) and the cpu skyrockets to 100% usage and lags my laptop.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15063603/log.txt)

### Device and Model

Asus Tuf Dash F15 (2022)

### Armoury Crate

Happens with AC installed and uninstalled, current installed

### Asus Services

This happens with any amount

### Version

0.165.0

### OS

Windows 11

**Comment by seerge** [comment]
@TriTriTheCuber hello.

What do you mean under "CPU stuck at 100%" ? Where do you see that ?

As for power plans, G-Helper doesn't have any own power plans. It just relies on very standard windows own "balanced" power plan, that comes with the system by default.

**Comment by seerge** [comment]
If you (or any other app running on your device) has modified default windows power plan, I suggest to [reset it as explained here ](https://github.com/seerge/g-helper/wiki/Troubleshooting#resetting-windows-power-plan-to-defaults)

**Comment by TriTriTheCuber** [comment]
![Screenshot 2024-04-22 095536](https://github.com/seerge/g-helper/assets/121834111/2fb10886-54e6-4de2-8747-311770f0a31a)

**Comment by seerge** [comment]
@TriTriTheCuber hello, this cropped rectangle is not helpful.

Can you please post a full screenshot from the app that shows this? If it's a Task Manager - check what actual tasks are consuming your CPU.

**Comment by TriTriTheCuber** [comment]
![Screenshot 2024-04-22 100403](https://github.com/seerge/g-helper/assets/121834111/1cfcde2d-05dc-49d3-82f6-67209e31025f)
![Screenshot 2024-04-22 100432](https://github.com/seerge/g-helper/assets/121834111/35fdbb56-197e-467c-af0b-a4d14b88c858)

**Comment by seerge** [comment]
@TriTriTheCuber ok. Looks like some hiccup in windows (or even with the task manager itself?) as on second Details screenshot  95% of CPU resources is free (System Idle)

Did you try resetting windows power plan to defaults https://github.com/seerge/g-helper/wiki/Troubleshooting#resetting-windows-power-plan-to-defaults ?

**Comment by TriTriTheCuber** [comment]
It said "Invalid Parameters -- try "/?" for help"

**Comment by seerge** [comment]
@TriTriTheCuber you need to copy command carefully and avoid extra spaces in the end :)

**Comment by TriTriTheCuber** [comment]
When i used /?, there was no "restroresystemschemes" param

**Comment by TriTriTheCuber** [comment]
nevermind

**Comment by TriTriTheCuber** [comment]
found it

**Comment by TriTriTheCuber** [comment]
lemme check if it works

**Comment by TriTriTheCuber** [comment]
That fixed my issue, thanks :)
