### ISSUE TITLE
Add overlay for mic and touchpad

### ISSUE THREAD

**Issue by solifice** [seerge/g-helper#2478]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I have laptop Asus TUF A15 that is FX506IH. I can use Fn+F4 to mute or unmute the microphone, but an overlay is not visible. Same goes with the Fn+F10 to disable/enable the touchpad, but an overlay is not visible.

### Describe the solution you'd like

Just add the overlays for it when mic is mute or unmute and touchpad is enabled or disabled.

### Device and Model

Asus TUF A15 FX506IH

**Comment by seerge** [comment]
@solifice in what circumstances is it not visible? If it's in full-screen games, then this is due to windows restrictions :) I can't change that.

**Comment by solifice** [comment]
> @solifice then you need to stop asus services from `Extra`, cause when they run they handle hotkeys, not G-Helper

Yeah now its working fine, just a quick question, stopping asus services will effect anything?

**Comment by seerge** [comment]
@solifice you will need them if you use myasus. G-Helper doesn’t need any of them

**Comment by solifice** [comment]
> @solifice you will need them if you use myasus. G-Helper doesn’t need any of them

thanks for the reply. Love your work ❤️.
