### ISSUE TITLE
could you add a way to add power plans like high performance ,ultimate performance in g helper

### ISSUE THREAD

**Issue by AayushV12** [seerge/g-helper#2479]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

could you add a way to add power plans like high performance ,ultimate performance in g helper

### Describe the solution you'd like

could you add a way to add power plans like high performance ,ultimate performance in g helper

### Describe alternatives you've considered

could you add a way to add power plans like high performance ,ultimate performance in g helper

### Device and Model

asus rog strix g15 g513rc hn062w

### Additional information.

could you add a way to add power plans like high performance ,ultimate performance in g helper

**Comment by seerge** [comment]
@AayushV12 this is already possible. Please check readme
https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-windows-power-plans-with-each-mode

**Comment by AayushV12** [comment]
can u add a screenshot step by step guide as it keeps resetting my json file again and again

**Comment by seerge** [comment]
@AayushV12 there is a 3 step guide already on top of the page
https://github.com/seerge/g-helper/wiki/Power-user-settings#general-note
