### ISSUE TITLE
  About Fan Speed adjust

### ISSUE THREAD

**Issue by lswlc33** [seerge/g-helper#248]
The bios  interface of some devices is like this. They do not have automatic adjustment function![IMG_20230415_204256.jpg](https://user-images.githubusercontent.com/86835895/232225049-b7ee2ecf-3a65-4de6-8a2e-7773ebfa8968.jpg)

So the custom adjustment function in the software does not take effect and show 'drvier rejected'in log

I hope to make a statistics on  devices which use these old bios and block this setting in it

**Comment by seerge** [comment]
@lswlc33 my bios is also like this, and custom fans work :) it's really not connected anyhow

**Comment by lswlc33** [comment]
> @lswlc33 my bios is also like this, and custom fans work :) it's really not connected anyhow

 Perhaps you can add a hint that may not necessarily take effect， To remind users, because I see many people who are not work

**Comment by seerge** [comment]
@lswlc33 perhaps :)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11241913/GHelper.zip)

Added a warning like this one

![Screenshot 2023-04-16 122041](https://user-images.githubusercontent.com/5920850/232296756-e0570ffe-4962-4c3d-a93c-15612b603401.png)

**Comment by Leedius** [comment]
I'm using tuf Dash 2022 version i5-12450h, but I'm getting an error with fans + power 
![image](https://user-images.githubusercontent.com/122840903/232976152-7b5e2690-f69b-4187-b401-c70f0863899d.png)

**Comment by SalvatoreCrobu** [comment]
Hi, i have an Asus F15 FX506HM, i don't see any warning option about fan control incompatibility but the fan curves don't work.  also have a custom bios with everything unlocked if you want know some settings.

Do you know how i can take control over fan curves? In armory crate there isn't the possibility to control the fans.

**Comment by seerge** [comment]
@SalvatoreCrobu what does it says about fans in the log ?

**Comment by SalvatoreCrobu** [comment]
Where i can find the log file?

**Comment by seerge** [comment]
@SalvatoreCrobu under %appdata%/ghelper

**Comment by SalvatoreCrobu** [comment]
"FanCPU = 14-32-44-48-4C-50-51-62-00-14-22-29-34-43-63-63 : 0
 FanGPU = 14-32-44-48-4C-50-51-63-00-12-26-2D-39-47-63-63 : 0
 ASUS BIOS rejected fan curve, resetting mode to 1"

**Comment by SalvatoreCrobu** [comment]
@seerge Nope, i can't adjust fan curves in Armory Crate, but having a modded unlocked BIOS you think i can find some setting to enable fan control?

I can attach some screenshot or photos of thermal management or other related settings

**Comment by seerge** [comment]
@SalvatoreCrobu no, that's not possible. If your device doesn't support fan curves setting in armoury, there is no way you can set them in g-helper neither

**Comment by lswlc33** [comment]
@seerge  I need a help 
it seems that my fan can't run at all
it awlays 0%
<img width="868" alt="image" src="https://github.com/seerge/g-helper/assets/86835895/dab2cde8-1ef3-429f-9976-eecdc45a19dc">
My computer is so hot with a edge and pychram background these day and it is summer now 
I am afraid that my pc burnt some days
do you know what happend to me 
i can provide what you need for check 
thanks
