### ISSUE TITLE
Fan speed change not reflected in MyASUS

### ISSUE THREAD

**Issue by kylagit** [seerge/g-helper#2480]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I change the fan speed in GHelper (Vivobook F1505ZA), You don't see the profile change in MyASUS. You see this even when you restart MyASUS. Is this expected behavior

### How to reproduce the bug?

1. Change the fan speed profile in Ghelper
2. Check the Device Settings section of MyASUS
3. You will see the fan profile does not match what was selected in GHelper

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15066689/log.txt)

### Device and Model

Vivobook F1505ZA

### Additional information.

This laptop has only an iGPU. So no GPU speed, just CPU speed.

### Armoury Crate

Never installed

### Asus Services

6

### Version

0.167.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@kylagit hello,

What exactly needs to be reflected in MyASUS  ? 

It's not possible to "read" current profile, only set it. So MyASUS will keep showing whatever it remembers setting last, not what you have set in G-Helper.

**Comment by kylagit** [comment]
> What exactly needs to be reflected in MyASUS ?

The mode I have set for the fan speed, such as quiet/balanced/turbo. These modes can be set both in Ghelper and in MyASUS, but when I change it in Ghelper, it doesn't change in MyASUS, and vice versa. Are you sure the fan profile option in your software is the same as the one in MyASUS?

**Comment by seerge** [comment]
@kylagit yes, it’s same and I have already answered your question above.

**Comment by kylagit** [comment]
Thank you for your help! But do the settings changed in Ghelper fully reset to default when I close the app then restart my PC?

**Comment by seerge** [comment]
@kylagit settings reset when you reset, but when you close the app
