### ISSUE TITLE
CPU Boost Settings Changing for All Power Profiles

### ISSUE THREAD

**Issue by plazski** [seerge/g-helper#2481]
When I try and change the CPU boost settings it seems to change them for all the power profiles, not individually.

For example if I want to disable cpu boost on silent profile it will disable it for balanced and turbo as well. It doesn’t seem to save it under each power profile.

I have a 2024 Asus Zephyrus G14 AMD ryzen 9 8945HS

Thanks

**Comment by seerge** [comment]
@plazski they are saved per profile, if you didn’t explicitly set boost settings for a profile- app will keep using a previous.

So just select something for each profile
