### ISSUE TITLE
灯光，电池及日常的一些小问题

### ISSUE THREAD

**Issue by lukas0128** [seerge/g-helper#2482]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

灯光自定义，电源限制失效，asus服务未关闭

### Describe the solution you'd like

采用两种配置，一种是插电的灯光设置，一种是不插电的灯光设置，其次我希望加入自定义灯光，而不是单纯的可选灯光，或许这是一个较大的工程量，但是rog通用！其次灯光亮度的调节是只有三个挡位，请问能否设计成线性的变化呢？其次这个笔记本充电限制存在bug，有时候还是会莫名冲到100%。最后，我在任务管理器中仍然发现有asus的服务在运转，服务并未完全停止。

### Describe alternatives you've considered

华硕自带的奥创中心可以自定义灯光。服务只能手动停止

### Device and Model

strixscar18g834jzr

**Comment by seerge** [comment]
>  I understand that, if insufficient information will be provided, my issue will be closed without an answer.
