### ISSUE TITLE
Visual Mode on G14 2023 IPS

### ISSUE THREAD

**Issue by Panda141298** [seerge/g-helper#2483]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Within the Visual Mode drop down, I usually switch between the default and vivid modes. However, within the last day, the vivid mode doesn't seem to do anything.

### How to reproduce the bug?

Just by swapping between the visual modes you can see that all the others work as they should, apart from the vivid mode.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15075713/log.txt)

### Device and Model

G14 GA402NV

### Armoury Crate

Uninstalled

### Asus Services

Tried with and without.

### Version

0.165

### OS

Windows 11

**Comment by Panda141298** [comment]
[log.txt](https://github.com/seerge/g-helper/files/15075774/log.txt)
log with vivid mode enabled

**Comment by seerge** [comment]
@Panda141298 hello,

Under the hood G-Helper just launches asus own "AsusSplendid.exe" to set different visual modes with param  ``13``  (Vivid), ``11``  (Default)

```
23/04/2024 11:45:17: C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_add427665a6c072f\ASUSOptimization\AsusSplendid.exe 13 0 15
23/04/2024 11:45:18: HIT: ulOutBuffer[0] = 512 > 0 this->BiosDataStatus  = 0   ReadResult  = 0  Parsing version = 7 Use Method = 1   bios size = 49 CCTAPI_ERRORCODE = 0 ; HIT: DEF Gain E(0) W(0) ; HIT: Warm Gain E(0) W(0) ; HIT: Cold Gain E(0) W(0) ; HIT: RdW Gain E(0) W(0) ; HIT: RdS Gain E(0) W(0) CCT_Init  result = 0 HIT: ulOutBuffer[0] = 512 > 0 ; HIT: Get bios[297]: 32  scale: 1.000000, Scale TH: 0.100000, nIndex: 26 New ScaleTH: 0.196078 New scale: 1.000000 outlut: [1.000000, 0.968627, 0.917647] Get dll path: [C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_add427665a6c072f\ASUSOptimization\AsusCCT.DLL] Get dll folder: [C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_add427665a6c072f\ASUSOptimization] UIGain: 0.650000 lutDcModeScale: 1.000000 Interval: 0.650000 RDLevels: 5.000000 index: 0.162500 Param: 2, Gamut mode: FFFF Gamut mapping process exit with return code 0
```

```
23/04/2024 11:46:46: C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_add427665a6c072f\ASUSOptimization\AsusSplendid.exe 11 0 15
23/04/2024 11:46:46: HIT: ulOutBuffer[0] = 512 > 0 this->BiosDataStatus  = 0   ReadResult  = 0  Parsing version = 7 Use Method = 1   bios size = 49 CCTAPI_ERRORCODE = 0 ; HIT: DEF Gain E(0) W(0) ; HIT: Warm Gain E(0) W(0) ; HIT: Cold Gain E(0) W(0) ; HIT: RdW Gain E(0) W(0) ; HIT: RdS Gain E(0) W(0) CCT_Init  result = 0 HIT: ulOutBuffer[0] = 512 > 0 ; HIT: Get bios[297]: 32  scale: 1.000000, Scale TH: 0.100000, nIndex: 26 New ScaleTH: 0.196078 New scale: 1.000000 outlut: [1.000000, 0.968627, 0.917647] Get dll path: [C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_add427665a6c072f\ASUSOptimization\AsusCCT.DLL] Get dll folder: [C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_add427665a6c072f\ASUSOptimization] UIGain: 0.650000 lutDcModeScale: 1.000000 Interval: 0.650000 RDLevels: 5.000000 index: 0.162500 Param: 2, Gamut mode: FFFF Gamut mapping process exit with return code 0
```

According to the log and what that utility outputs, it all goes w/o any errors.

Are you able to change Game Visual in Armoury Crate ?

**Comment by Panda141298** [comment]
I currently have Armoury Crate uninstalled. Would you like me to reinstall it?

**Comment by seerge** [comment]
@Panda141298 try to open powershell as admin and run following commands

```
C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_add427665a6c072f\ASUSOptimization\AsusSplendid.exe 10
```

```
C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_add427665a6c072f\ASUSOptimization\AsusSplendid.exe 10 4
```

That's "initialization" command for AsusSplendid). And try to change Visual Mode after that.

I also see that you are in Eco mode now, try to set Standard and see if it helps.

If it won't have any effect - indeed try to install AC and check if it will be able to set GameVisual.

**Comment by Panda141298** [comment]
I tried the commands, copied them and pressed enter. This didn't seem to do anything. I also re installed Armoury Crate and the vivid mode also isn't working from there. Nor did any change from standard to eco. It worked in both modes prior to this issue.

**Comment by seerge** [comment]
@Panda141298 ok. If it doesn't work in AC as well, probably something is wrong in general with your system.

Try to do a clean GPU driver reinstall as explained here 
https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers

**Comment by Panda141298** [comment]
Okay, tried that. Even rolled back to the previous nvidia driver and it still hasn't fixed the issue.

**Comment by seerge** [comment]
@Panda141298 and also you can delete
```C:\ProgramData\ASUS\ASUS System Control Interface\ASUSOptimization\Splendid```

**Comment by Panda141298** [comment]
Okay, I have deleted those files and that has caused all of the Visual modes to stop working including colour temperature and gamut. I dont see anywhere to re download it though.

**Comment by Panda141298** [comment]
Okay I have deleted those files and re downloaded them. However it still hasn't seemed to fix the issue. Still just vivid mode that doesn't work.

**Comment by seerge** [comment]
@Panda141298 also ``C:\ProgramData\ASUS\ASUS System Control Interface\ASUSOptimization\Splendid`` ?

Then I'm out of ideas :) But I'm afraid it's unrelated to G-Helper, as it doesn't work in AC as well. 

May be windows update has screwed up something, or some changes that you did with your device.

**Comment by seerge** [comment]
@Panda141298 try to reinstall Asus System Control Interface as explained here https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-asus-system-control-interface

**Comment by Panda141298** [comment]
Okay ill give it a go. Really appreciate the support Seerge. Ghelper is a godsend.

**Comment by seerge** [comment]
@Panda141298 any luck with that ?

**Comment by seerge** [comment]
Closing this as this is not G-Helper's issue in a first place (as it doesn't work in AC as well)

Feel free to post an update, if you will find what was the culprit tho. 

Thanks

**Comment by syh599** [comment]
Hi seerge,

I had the same problem on Zephyrus G15 2022

It seems to be a problem with the latest Asus system control interface 3.1.26.0 and 3.1.27.0
I reverted back to 3.1.25.0 and vivid mode works again

**Comment by seerge** [comment]
@syh599 ok, good to know.

I use G14 2022 and latest Control Interface (3.1.27) and don't have this issue.

But since ``AsusSplendid.exe`` responsible for that is part of this package, it could be indeed broken for some specific models :(

**Comment by sprutxz** [comment]
Rolling

> Hi seerge,
> 
> I had the same problem on Zephyrus G15 2022
> 
> It seems to be a problem with the latest Asus system control interface 3.1.26.0 and 3.1.27.0 I reverted back to 3.1.25.0 and vivid mode works again

Rolling back to 3.1.25.0 Also fixed my issue

**Comment by seerge** [comment]
@sprutxz looks like asus has changed something in 3.1.27 ... but for my device newest one works fine tho

**Comment by sprutxz** [comment]
Well the vivid mode stopped working again even on version 3.1.25. I will try to redownload the drivers and see what exactly is causing the issue

**Comment by sprutxz** [comment]
@seerge Vivid mode is working for me again on version 3.1.27 but seems to stop working sometimes. I am unable to figure out exactly why this issue occurs but I'll report back once I figure out cause or a fix
