### ISSUE TITLE
Anime Matrix either doesn't load or takes 30s+

### ISSUE THREAD

**Issue by dylanh724** [seerge/g-helper#2486]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Anime Matrix premade options instantly show previews, but custom images take up to 30 seconds+ or indefinitely won't show at all when selected.

### How to reproduce the bug?

1. Choose any custom picture of Anime Matrix
2. Wait for the laptop to reflect the change - or just simply not work

### Logs

4/23/2024 11:55:24 PM: ------------
4/23/2024 11:55:24 PM: App launched: ROG Zephyrus G14 GA402RJ_GA402RJ :0.165.0.0en-US
4/23/2024 11:55:24 PM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col02#7&2ce29178&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} 640
4/23/2024 11:55:25 PM: AMD Radeon RX 6700S
4/23/2024 11:55:26 PM: CPU: 8 - AMD Ryzen 9 6900HS with Radeon Graphics         - AMD64 Family 25 Model 68 Stepping 1
4/23/2024 11:55:26 PM: AutoSetting for Online
4/23/2024 11:55:26 PM: Optimization service is running
4/23/2024 11:55:26 PM: Eco flag : 0
4/23/2024 11:55:26 PM: Mux flag : 1
4/23/2024 11:55:26 PM: \\?\DISPLAY#TMX1481#5&30fcb328&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
4/23/2024 11:55:26 PM: \\?\DISPLAY#SAM7094#5&30fcb328&0&UID517#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
4/23/2024 11:55:26 PM: \\?\DISPLAY#TMX1481#5&30fcb328&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY2\Monitor0
4/23/2024 11:55:26 PM: TL140ADXP01 HDR: False 8 5 True
4/23/2024 11:55:26 PM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col02#7&2ce29178&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} 640
4/23/2024 11:55:26 PM: Mode = 0 : OK
4/23/2024 11:55:27 PM: Init 19B6: 5D-B9
4/23/2024 11:55:27 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
4/23/2024 11:55:27 PM: Init 19B6: 5D-05-20-31-00-1A
4/23/2024 11:55:27 PM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
4/23/2024 11:55:27 PM: AuraMode: AuraStatic
4/23/2024 11:55:27 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
4/23/2024 11:55:27 PM: USB 19B6: 5D-B5-00-00-00
4/23/2024 11:55:27 PM: USB 19B6: 5D-B4
4/23/2024 11:55:27 PM: Matrix Off
4/23/2024 11:55:27 PM: TL140ADXP01 HDR: False 8 5 True
4/23/2024 11:55:27 PM: Monitor Power On
4/23/2024 11:55:27 PM: Lid Open
4/23/2024 11:55:27 PM: Lid 19B6: 5D-BA-C5-C4-01
4/23/2024 11:55:28 PM: Auto 19B6: 5D-BA-C5-C4-01
4/23/2024 11:55:29 PM: Latest version 0.165.0.0
4/23/2024 11:55:30 PM: Design Capacity: 76000mWh, Full Charge Capacity: 61851mWh, Health: 0.8138289473684210526315789474%
4/23/2024 11:56:02 PM: \\?\DISPLAY#TMX1481#5&30fcb328&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
4/23/2024 11:56:02 PM: \\?\DISPLAY#SAM7094#5&30fcb328&0&UID517#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
4/23/2024 11:56:02 PM: \\?\DISPLAY#TMX1481#5&30fcb328&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY2\Monitor0
4/23/2024 11:56:02 PM: TL140ADXP01 HDR: False 8 5 True
4/23/2024 11:56:12 PM: Lid Closed
4/23/2024 11:56:12 PM: Lid 19B6: 5D-BA-C5-C4-00
4/23/2024 11:56:12 PM: Display configuration changed.
4/23/2024 11:56:12 PM: Internal screen off
4/23/2024 11:56:18 PM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col02#7&2ce29178&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} 640
4/23/2024 11:56:18 PM: Matrix builtin: 14
4/23/2024 11:56:29 PM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col02#7&2ce29178&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} 640
4/23/2024 11:56:29 PM: Matrix Clock
4/23/2024 11:56:36 PM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col02#7&2ce29178&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} 640
4/23/2024 11:56:36 PM: Matrix Audio
4/23/2024 11:56:39 PM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col02#7&2ce29178&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} 640
4/23/2024 11:56:39 PM: Matrix builtin: 15
4/23/2024 11:56:41 PM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col02#7&2ce29178&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} 640
4/23/2024 11:59:45 PM: GIF Delay:27750
4/23/2024 11:59:45 PM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/23/2024 11:59:52 PM: GIF Delay:27750
4/23/2024 11:59:52 PM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/23/2024 11:59:54 PM: GIF Delay:27750
4/23/2024 11:59:54 PM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/23/2024 11:59:58 PM: GIF Delay:27750
4/23/2024 11:59:58 PM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:02 AM: GIF Delay:27750
4/24/2024 12:00:02 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:03 AM: GIF Delay:27750
4/24/2024 12:00:03 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:05 AM: GIF Delay:27750
4/24/2024 12:00:05 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:06 AM: GIF Delay:27750
4/24/2024 12:00:06 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:07 AM: GIF Delay:27750
4/24/2024 12:00:07 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:08 AM: GIF Delay:27750
4/24/2024 12:00:08 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:09 AM: GIF Delay:27750
4/24/2024 12:00:09 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:17 AM: GIF Delay:27750
4/24/2024 12:00:17 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:24 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col02#7&2ce29178&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} 640
4/24/2024 12:00:24 AM: Matrix builtin: 14
4/24/2024 12:00:27 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col02#7&2ce29178&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} 640
4/24/2024 12:00:27 AM: Matrix builtin: 15
4/24/2024 12:00:29 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col02#7&2ce29178&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} 640
4/24/2024 12:00:29 AM: GIF Delay:27750
4/24/2024 12:00:29 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:34 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col02#7&2ce29178&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} 640
4/24/2024 12:00:34 AM: GIF Delay:27750
4/24/2024 12:00:34 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:37 AM: GIF Delay:27750
4/24/2024 12:00:37 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:41 AM: GIF Delay:27750
4/24/2024 12:00:41 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:42 AM: GIF Delay:27750
4/24/2024 12:00:42 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:49 AM: GIF Delay:27750
4/24/2024 12:00:49 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:50 AM: GIF Delay:27750
4/24/2024 12:00:50 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:53 AM: GIF Delay:27750
4/24/2024 12:00:53 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:54 AM: GIF Delay:27750
4/24/2024 12:00:54 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:57 AM: GIF Delay:27750
4/24/2024 12:00:57 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:58 AM: GIF Delay:27750
4/24/2024 12:00:58 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:58 AM: GIF Delay:27750
4/24/2024 12:00:58 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:00:58 AM: GIF Delay:27750
4/24/2024 12:00:58 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:01:09 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col02#7&2ce29178&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} 640
4/24/2024 12:01:09 AM: GIF Delay:27750
4/24/2024 12:01:09 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:01:14 AM: AuraMode: AuraStatic
4/24/2024 12:01:14 AM: USB 19B6: 5D-B3-00-00-00-80-FF-EB-00-00-FF-FF-FF-00-00-00-00
4/24/2024 12:01:14 AM: USB 19B6: 5D-B5-00-00-00
4/24/2024 12:01:14 AM: USB 19B6: 5D-B4
4/24/2024 12:01:16 AM: Varibright: 1,2
4/24/2024 12:01:16 AM: Hibernate after 2147483647
4/24/2024 12:02:02 AM: GIF Delay:27750
4/24/2024 12:02:02 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:02:04 AM: GIF Delay:27750
4/24/2024 12:02:04 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:02:53 AM: GIF Delay:27750
4/24/2024 12:02:53 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:02:59 AM: GIF Delay:27750
4/24/2024 12:02:59 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:03:02 AM: GIF Delay:27750
4/24/2024 12:03:02 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:03:29 AM: MediaTek WLAN Driver PCI\VEN_14C3&DEV_7922&SUBSYS_53001A3B 3.3.2.852 vs 3.3.2.852 = 0
4/24/2024 12:03:29 AM: AMD Chipset ACPI\AMDI0010 1.2.0.119 vs 1.2.0.124 = -1
4/24/2024 12:03:29 AM: Realtek Audio HDAUDIO\FUNC_01&VEN_10EC&DEV_0285 6.0.9373.1 vs 6.0.9373.1 = 0
4/24/2024 12:03:29 AM: AMD Graphics Driver PCI\VEN_1002&DEV_1681&SUBSYS_1DEC1043 31.0.12024.2005 vs 31.0.24027.1012 = -1
4/24/2024 12:03:29 AM: AMD Graphics Driver PCI\VEN_1002&DEV_1681&SUBSYS_1DEC1043 31.0.12024.2005 vs 31.0.24027.1012 = -1
4/24/2024 12:03:29 AM: AMD Graphics Driver PCI\VEN_1002&DEV_73EF&SUBSYS_1DEC1043 31.0.12024.2005 vs 31.0.24027.1012 = -1
4/24/2024 12:03:29 AM: Bayhub Card Reader Driver PCI\VEN_1217&DEV_8520 2.1.101.10580 vs 2.1.101.10580 = 0
4/24/2024 12:03:29 AM: Bayhub Card Reader Driver PCI\VEN_1217&DEV_8520&SUBSYS_202F1043 2.1.101.10580 vs 2.1.101.10580 = 0
4/24/2024 12:03:29 AM: MediaTek Bluetooth Driver USB\VID_13D3&PID_3568&MI_00 1.1036.2.368 vs 1.1036.2.368 = 0
4/24/2024 12:03:29 AM: ASUS System Control Interface v3 ACPI\ASUS2018 3.1.22.0 vs 3.1.25.0 = -1
4/24/2024 12:04:04 AM: GIF Delay:27750
4/24/2024 12:04:04 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
4/24/2024 12:04:08 AM: GIF Delay:90
4/24/2024 12:04:08 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\starfield-dark-background-sgli8iwvguwxzovr.gif
4/24/2024 12:04:13 AM: GIF Delay:90
4/24/2024 12:04:13 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\starfield-dark-background-sgli8iwvguwxzovr.gif
4/24/2024 12:04:16 AM: GIF Delay:90
4/24/2024 12:04:16 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\starfield-dark-background-sgli8iwvguwxzovr.gif
4/24/2024 12:04:17 AM: GIF Delay:90
4/24/2024 12:04:17 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\starfield-dark-background-sgli8iwvguwxzovr.gif
4/24/2024 12:04:18 AM: GIF Delay:90
4/24/2024 12:04:18 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\starfield-dark-background-sgli8iwvguwxzovr.gif
4/24/2024 12:04:19 AM: GIF Delay:90
4/24/2024 12:04:19 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\starfield-dark-background-sgli8iwvguwxzovr.gif
4/24/2024 12:04:28 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col02#7&2ce29178&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} 640
4/24/2024 12:04:28 AM: GIF Delay:90
4/24/2024 12:04:28 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\starfield-dark-background-sgli8iwvguwxzovr.gif
4/24/2024 12:04:29 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col02#7&2ce29178&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} 640
4/24/2024 12:04:29 AM: GIF Delay:90
4/24/2024 12:04:29 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\starfield-dark-background-sgli8iwvguwxzovr.gif
4/24/2024 12:04:34 AM: GIF Delay:90
4/24/2024 12:04:34 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\starfield-dark-background-sgli8iwvguwxzovr.gif
4/24/2024 12:04:36 AM: GIF Delay:90
4/24/2024 12:04:36 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\starfield-dark-background-sgli8iwvguwxzovr.gif
4/24/2024 12:05:41 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col02#7&2ce29178&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} 640
4/24/2024 12:05:41 AM: GIF Delay:90
4/24/2024 12:05:41 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\starfield-dark-background-sgli8iwvguwxzovr.gif
4/24/2024 12:05:41 AM: GIF Delay:90
4/24/2024 12:05:41 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\starfield-dark-background-sgli8iwvguwxzovr.gif
4/24/2024 12:05:45 AM: GIF Delay:30
4/24/2024 12:05:45 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\matrix-cat.gif
4/24/2024 12:06:31 AM: GIF Delay:30
4/24/2024 12:06:31 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\matrix-cat.gif
4/24/2024 12:06:35 AM: GIF Delay:30
4/24/2024 12:06:35 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\matrix-cat.gif
4/24/2024 12:06:40 AM: GIF Delay:30
4/24/2024 12:06:40 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\matrix-cat.gif
4/24/2024 12:06:42 AM: GIF Delay:30
4/24/2024 12:06:42 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\matrix-cat.gif
4/24/2024 12:06:46 AM: GIF Delay:30
4/24/2024 12:06:46 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\matrix-cat.gif
4/24/2024 12:06:47 AM: GIF Delay:30
4/24/2024 12:06:47 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\matrix-cat.gif
4/24/2024 12:06:47 AM: GIF Delay:30
4/24/2024 12:06:47 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\matrix-cat.gif
4/24/2024 12:06:48 AM: GIF Delay:30
4/24/2024 12:06:48 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\matrix-cat.gif
4/24/2024 12:06:48 AM: GIF Delay:30
4/24/2024 12:06:48 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\matrix-cat.gif
4/24/2024 12:06:49 AM: GIF Delay:30
4/24/2024 12:06:49 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\matrix-cat.gif
4/24/2024 12:06:49 AM: GIF Delay:30
4/24/2024 12:06:49 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\matrix-cat.gif
4/24/2024 12:06:49 AM: GIF Delay:30
4/24/2024 12:06:49 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\matrix-cat.gif
4/24/2024 12:06:50 AM: GIF Delay:30
4/24/2024 12:06:50 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\matrix-cat.gif

### Device and Model

Asus Zephyrus G14 2022

### Armoury Crate

Uninstalled

### Asus Services

8

### Version

0.165.0

### OS

Win11

**Comment by dylanh724** [comment]
> 4/24/2024 12:06:40 AM: GIF Delay:30

How come there's a 30s delay? I can't find an adjustment for this

**Comment by seerge** [comment]
@dylanh724 hello.

App just reads delay between GIF frames from the file directly, and plays them with that delay

I see that some file has a crazy high delay, so no wonder it plays slowly. You need to edit GIF prior to setting it if you want it to be faster
```
4/24/2024 12:02:02 AM: GIF Delay:27750  <--- 27 750 milliseconds (27.75 seconds)
4/24/2024 12:02:02 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\apertureScience.gif
```

This one should play fine (30ms)

```
4/24/2024 12:06:46 AM: GIF Delay:30
4/24/2024 12:06:46 AM: Matrix C:\Users\dylan\OneDrive\Pictures\Anime Matrix\matrix-cat.gif
```

**Comment by seerge** [comment]
@dylanh724 any updates on the matter ?

**Comment by dylanh724** [comment]
@seerge Ok so the delay issue was due to a bad GIF, since opening it up locally doesn't do what's expected.

As for another:

![matrix-cat](https://github.com/seerge/g-helper/assets/8840024/5ec95cca-01e5-4a48-ae9e-bc12ecdefd72)

I couldn't get this to show _at all_.

**Comment by dylanh724** [comment]
To add to GIF testing results: 

![aperture-wide-anim23](https://github.com/seerge/g-helper/assets/8840024/eb456b57-af40-4737-a0d1-8382acb2602e)

I also noticed that "diagonal" image rotation will vertically _squish_ the picture, not respecting the aspect ratio. At least in this one ^

**Comment by dylanh724** [comment]
Here's a comparison for the diagonal squish:

![image](https://github.com/seerge/g-helper/assets/8840024/c317284c-09f7-43fc-8e8d-8c4538fb5763)

![image](https://github.com/seerge/g-helper/assets/8840024/3f87c757-d003-4374-beb6-5662ff79aae1)

**Comment by dylanh724** [comment]
(PS: Your app is great! ⭐ just a small thing)

**Comment by seerge** [comment]
@dylanh724 ok, 

### For the cat image

It's actually just too dark by default. You would have to either increase it's brightness (along with contrast to keep actual blacks - black) or just try this build where I have added a ``Brightness`` slider next to ``Contrast``

[GHelper.zip](https://github.com/seerge/g-helper/files/15128589/GHelper.zip)

I was able to achieve acceptable result with following settings
![Screenshot 2024-04-26 115555](https://github.com/seerge/g-helper/assets/5920850/674835a8-5e0e-47fb-a8af-bfe3d69d9169)

![IMG_6269](https://github.com/seerge/g-helper/assets/5920850/9d4302cd-a11f-4626-bb2f-809a2695c1a4)

But keep in mind, that picture is just too detailed for a very-low resolution of anime-matrix in a first place. You obviously won't see 0 and 1 there anyway

### For diagonal alignment
It's intended to be like that, as this is how LEDs are actually located. So it aligns picture as close to pixel-perfect as possible.

Check [this topic for more info](https://github.com/seerge/g-helper/issues/1648)
