### ISSUE TITLE
Zenbook 2024 / UM3406HA | Power Limit issues

### ISSUE THREAD

**Issue by olos22** [seerge/g-helper#2487]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hello, as a bit of introduction, I love GHelper and have used it plenty of times on my G14 2021 model. 
Now let's get to the problem. I bought the newest Zenbook 14 with Ryzen 7 8840HS (UM3406HA) about a week ago. 
Obviously, I downloaded GHelper, and everything in it works perfectly: battery limiter, modes, etc. 
Except the Power limits... I wanted to limit my Silent mode's TDP a bit to prioritize battery in more demanding tasks (nothing really heavy at all, on G14 the same limits worked in same scenarios, not to mention the Zenbook should be even more energy efficient). But the TDP limits don't change at all. 
I've already tried seemingly everything to make it work: updated everything, turned off all Asus services, ran as an administrator, everything. 
After hours of trying to get this working and what seems like an eternity of looking through information, I have three theories. 
Since it's a new laptop, the BIOS might be bugged and not changing the TDP from GHelper (even though Asus's built-in modes change the TDP). 
Maybe something built-in from Asus is instantly overwriting the new TDP limits from GHelper? Or perhaps just the endpoints changed and GHelper doesn't support it yet.
I would be extremely grateful if this problem could be resolved as soon as possible.

### How to reproduce the bug?

1. Simply have Zenbook 14 OLED 2024 (UM3406HA)
2. Try to set the Power limits in GHelper
3. Doesn't work

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15082275/log.txt)

### Device and Model

Zenbook 14 OLED 2024 UM3406HA

### Additional information.

I have MyAsus since OLED protection, but I also tried with it disabled, all ASUS services disabled, and it didn't help.

### Armoury Crate

Uninstalled

### Asus Services

None, also nothing changed when they were enabled or disabled

### Version

0.165.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@olos22 hello,

I don't see you setting any power limits in the log, and most probably your device simply doesn't support them as they need to be implemented by Asus on firmware / BIOS level.

I assume you couldn't set any limits in AC / MyASUS neither, correct ?

Where do you set those limits ? How does Fans + Power page look like for you ?

**Comment by olos22** [comment]
I've tried to set the limits in GHelper, checked the apply box, and also tried applying the fans as well. 
Unfortunately, MyAsus doesn't have the power limit settings.
![image](https://github.com/seerge/g-helper/assets/51023680/10e2607d-c667-40a8-ab44-ce6ed19a8bf8)

**Comment by seerge** [comment]
@olos22 can you go to Advanced tab here and click ``Download Advanced Settings``? (then it will restart app as admin). If not - try to run it as admin manually and try again.

And post a log after.

**Comment by olos22** [comment]
Done. I also ran some tests shortly after downloading what you suggested, and I think the CPU limits started working. 
However, I'll do more tests tomorrow to confirm. If this one click truly resolved my issue, then I am very grateful and, at the same time, quite surprised by what the Advanced Settings actually changed.
[log (1).txt](https://github.com/seerge/g-helper/files/15082549/log.1.txt)

**Comment by seerge** [comment]
@olos22 ok, great.

Just in case your **device doesn't support power limits out of the box and done by Asus.** (so you did not have them in asus own apps)

But G-Helper has a fallback method for some AMD devices. For that you need to enable Advanced settings tho :) which you did.

Keep in mind that this fallback approach could be easily reset (at random time) by AMD driver. So if you want app to re-apply limits periodically for you - you need to check "Auto Apply" under Advanced.

Closing as resolved.

**Comment by olos22** [comment]
Alright, thank you very much for your help. I was really surprised you responded so quickly. If anything breaks again, I'll make sure to either comment here or create a new issue. Have a good night!

**Comment by seerge** [comment]
@olos22 np. Btw i advice to update to latest 0.167 as it will show visual mode dropdowns correctly for you

**Comment by olos22** [comment]
Alright
