### ISSUE TITLE
CPU power consumption wall issue

### ISSUE THREAD

**Issue by masteryf** [seerge/g-helper#2488]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Switching modes sometimes makes it impossible to adjust the power wall. When working normally, my computer has a power wall of 135W in turbo mode, 90W in balance mode, and 50/65W in eco mode. However, no matter how I adjust the mode now, the power wall is set at 90W
![屏幕截图 2024-04-24 124831](https://github.com/seerge/g-helper/assets/61418250/a22ab3a8-0a1b-4cfa-a724-3fa69a63f668)
![屏幕截图 2024-04-24 124926](https://github.com/seerge/g-helper/assets/61418250/57037c67-e410-4f8c-b522-38a0b222577a)

### How to reproduce the bug?

I am not sure how to trigger this. After using it for a while, I realized that I am unable to adjust the power consumption wall, and restarting cannot solve it

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15088000/log.txt)

### Device and Model

ASUS Zepgyrus M16 GU603ZX

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.165.0

### OS

Windows11 23H2

**Comment by seerge** [comment]
@masteryf hello,

I have no idea what does the "power consumption wall" is but if you mean power limits - then **both Armoury Crate and G-Helper** set power limits using asus own endpoints. And results **are not reflected** in HWinfo or similar app PL1/PL2 readings.

To see if limits work or not - you need to run some CPU benchmark (like Cinebench) and monitor actual power consumption in the same HWinfo for example.

On your screenshots power consumption is 15w and 6w accordingly, so clearly below limits that you have set.

From the log app sets limits and they are accepted
```
2024/4/24 12:47:25: PowerLimit A3 = 150 : OK
2024/4/24 12:47:25: PowerLimit A0 = 150 : OK
```
So everything works as it should.

Thanks.

**Comment by masteryf** [comment]
But my full load power is indeed limited to around 90w instead of the original 120w
![屏幕截图 2024-04-24 151328](https://github.com/seerge/g-helper/assets/61418250/75774eb7-665a-44a4-89b9-665675aca6dd)
![屏幕截图 2024-04-24 151347](https://github.com/seerge/g-helper/assets/61418250/f54ad49c-9ad5-480a-80d8-aeea8b685ce7)

**Comment by seerge** [comment]
@masteryf then your CPU is probably limited on a driver level as well (and that's what you see in HWINfo under PL1/Pl2).

Neither G-Helper nor AC (as a i'm aware) can't change that.

If you want to adjust those limits you can try [Throttlestop](https://www.techpowerup.com/download/techpowerup-throttlestop/) app

**Comment by seerge** [comment]
@masteryf to check if G-Helper's power limits are working (or not) try to set something lower and adequate (like 40W) and run a benchmark.

If CPU will be limited to 40W - then it's working as it should :)

**Comment by seerge** [comment]
@masteryf then you just have 2 different things limiting CPU

Proprietary Firmware / BIOS  limits - something that AC / G-Helper can set (via asus endpoints)
Driver level - something you can try to unlock using Throttlestop

**Comment by masteryf** [comment]
The turbo mode of Armory Create can unlock a limit of 135W. There was no problem using Armory Create and g-helper simultaneously. I encountered this issue after uninstalling Armory Create

**Comment by seerge** [comment]
@masteryf Turbo mode is just a preset in BIOS. Both apps just select same mode and then (optionally) allow customizing it.

If you like AC you are absolutely fine to use whatever you want.

Thanks.

**Comment by masteryf** [comment]
![image](https://github.com/seerge/g-helper/assets/61418250/f4e547c1-422b-4fc9-94bf-972158342f9b)
The limit I see in Throttlestop is 135w, which seems to correspond to the static PL1/PL2 in HWiNFO, but what really works seems to be the dynamic PL1/PL2

**Comment by seerge** [comment]
@masteryf well, you can tinker with throttlestop to disable that dynamic limit.

On a side note - why do you try run CPU on such high wattages ? You will probably gain something like 5-10% when going from 90W to 135W but it will cost a lot of heat / fan noise.

I didn't had any experience with 12900H CPU, but on 13900H that I used limiting it to something like 40-50W was more than enough in most of the real-life scenarios (including gameS)

**Comment by Kikimahe** [comment]
@masteryf 

Your [I9 12900H processor ](https://www.intel.fr/content/www/fr/fr/products/sku/132214/intel-core-i912900h-processor-24m-cache-up-to-5-00-ghz/specifications.html)seems to have the same specs as my Intel I7 12700H. The maximum TDP is 115W.
Have you ever seen your CPU go up to 135W in HWinfo?

And it's strange that Hwinfo & Trottlestop display the same values of 135W on PL1 and PL2. 
The value is lower on PL1 usually...

On the other hand, I also happened to observe a TDP lower than what I usually had (90-100W instead of 115W). And like you , restarting Windows didn't change anything.
(I think this problem happens when you apply a CPU limit and move the sliders several times while the CPU limit is checked)

To back to the usual TDP try this :
- In Ghelper, push Factory Reset button on all modes.
- Turn off your Laptop.
- Do a hardware reset (hold power on for 30-40sec then release the button)

Use Cinebench R23 + Hwinfo to do your tests instead of Aida64.
I feel like it stresses the CPU better.

Good Luck.

**Comment by masteryf** [comment]
Thank you. The hardware reset operation successfully restored the limit, and now the turbo mode can reach a normal limit of 135W. In fact, this computer will overheat at such high power consumption. It can maintain a power consumption of about 130W in winter and 110-120W in summer, and the temperature will reach the limit of 95 ° C. However, this is caused by heat. The limit is indeed the true 135W, and as you expected, the 12900h performance of around 120W is 110% of 90W. Maintaining this power consumption is not very meaningful. I am just curious about why there is such a limit and how to solve it
Thank you again for your help

**Comment by Kikimahe** [comment]
Great ! 👍 

Remember not to touch the sliders when the limit is checked in Ghelper and everything will go well. :)
