### ISSUE TITLE
Disabling certain Key bindings/shortcuts

### ISSUE THREAD

**Issue by kchawla-pi** [seerge/g-helper#2489]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Some of the Keyboard shortcuts interfere with my programming editor

Specifically: 
`Ctrl + Shift + F5 / Ctrl + Shift + Alt + F5` - Toggle Performance Modes forwards / backwards
`Ctrl + Shift + F12` - Open G-Helper window

### Describe the solution you'd like

A way to disable these/specific shortcuts.

### Describe alternatives you've considered

I would change the shortcuts in my editor instead of asking here, but they are muscle memory for many years and I arrived on them after trying a lot of other combos, so it would be great not having to change that.

Toggle Performance Modes forwards / backwards already has another shortcut anyway (`Fn + F5 / Fn + Shift + F5`)

### Device and Model

ROG Zephyrus GAUD2XV_GA4C2XV

**Comment by seerge** [comment]
@kchawla-pi hello,

This is already possible. Please check readme on how to do that https://github.com/seerge/g-helper/wiki/Power-user-settings#toggle-performance-mode-or-toggle-app-window-key-binding

Thanks

**Comment by kchawla-pi** [comment]
I am so sorry I missed that and wasted your time.

**Comment by kchawla-pi** [comment]
FYI, update: `"skip_hotkeys":1` did not work; `"keybind_profile": 0` did.

**Comment by seerge** [comment]
@kchawla-pi because skip hotkeys is for other things, it’s separated in the readme
