### ISSUE TITLE
App doing unnecessary work bug.

### ISSUE THREAD

**Issue by manciuszz** [seerge/g-helper#249]
After opening and exiting "Fans + Power" window, app is starting to do unnecessary work. Probably the app forgets to 'clean' up after itself.

<video src='https://user-images.githubusercontent.com/2539661/232237885-324fd12f-5109-47fb-9b58-0c830d0be807.mp4' width='480' />

**Comment by seerge** [comment]
App uses bunch of external libraries, like charts lib for fan editor, I have no control over that.

**Comment by manciuszz** [comment]
The momentary CPU cycle consumption is negligible, sure, but it really makes no sense that CPU cycles are being wasted like that for 'drawing', when the app is running in the background. The fact that if you close and open the app again fixes the issue also confirms that this shouldn't be happening. If you leave the computer turned on for long periods of time, CPU cycles wasted due to this becomes very significant.

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11240023/GHelper.zip)

In this build fans+power form should be closed by click X on it, you can try if it makes you happier

**Comment by manciuszz** [comment]
That build didn't fix anything. Furthermore, here's proof that what is happening here is truly unnecessary.
<video src='https://user-images.githubusercontent.com/2539661/232238784-9556d7d3-bd1d-4c6b-95fb-03d1c46abcb6.mp4' width='480' />

**Comment by seerge** [comment]
You are more than free to create a fork and make a pull request with a fix you are expecting here .

**Comment by manciuszz** [comment]
Done. 
https://github.com/seerge/g-helper/pull/251

**Comment by seerge** [comment]
@manciuszz instead of loading full gif in resources, and just creating a new bmp object over it, i just replaced it with static picture 
[GHelper.zip](https://github.com/seerge/g-helper/files/11240303/GHelper.zip)
does it work better for you now ? (changes are in main branch)

**Comment by manciuszz** [comment]
> @manciuszz instead of loading full gif in resources, and just creating a new bmp object over it, i just replaced it with static picture [GHelper.zip](https://github.com/seerge/g-helper/files/11240303/GHelper.zip) does it work better for you now ? (changes are in main branch)

Yes. Removing the **.gif** file altogether is the best solution in this case. I've tested the build you attached here and yes, it fixes the issue.

If you really want to use a meme .gif, I suggest to do it in a way that is controllable xD

**Comment by seerge** [comment]
Great, thanks. I will push it along 0.53 Closing issue then.
