### ISSUE TITLE
Power limits not working?

### ISSUE THREAD

**Issue by skuma01** [seerge/g-helper#2492]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I'm trying to change the power limit but nothing works.

### How to reproduce the bug?

Change the power settings (PL1 and/or PL2) and check all the boxes for custom power limits/low fans.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15103145/log.txt)

### Device and Model

ASUS ROG Zephyrus G16 GU605MY

### Additional information.

I believe I have tried all of the steps in the existing threads on this topic.

### Armoury Crate

Uninstalled

### Asus Services

8

### Version

0.165

### OS

Windows 11 22631

**Comment by seerge** [comment]
@skuma01 hello, did you migrate g-helper config from other device by any chance ? 

Can you upload your ``config.json`` here ?

Thanks

**Comment by skuma01** [comment]
I factory reset my device after having this issue, but that didn't resolve it. I did edit the config manually to add the first line after seeing another post where you recommended trying that.

Thank you for your help!

[config.json](https://github.com/seerge/g-helper/files/15118956/config.json)

**Comment by skuma01** [comment]
Ah, I had added that after seeing that it didn't work without it. I will
erase and try again but don't have high hopes.

I know that it's not working partially because even on gHelper it shows
that it's still kept at 80W (see this image) but more importantly, the
power draw consistently exceeds my set limits as measured in HWMonitor when
i put the system under load.

[image: image.png]

**Comment by seerge** [comment]
@skuma01 where did you see that ? :)

Anyway, image is not attached (it's missing)

Can you upload a log from the app after you have erased param (or ideally deleted config completely), and set power limits again ?

And screenshot of how you benchmark ? 

Thanks

**Comment by skuma01** [comment]
I meant seeing that it didn't work in my experience, sorry. I saw it originally in this post https://github.com/seerge/g-helper/discussions/667


This is the image I was trying to post 
![image](https://github.com/seerge/g-helper/assets/6689979/afe459ca-111a-4047-a4f3-33472df6677b)


Here are config and log after following your recommended steps.
[config.json](https://github.com/seerge/g-helper/files/15119245/config.json)
[log.txt](https://github.com/seerge/g-helper/files/15119246/log.txt)

This is how I configured it. After running silverbench with these settings, my wattages get up to around 45W
![image](https://github.com/seerge/g-helper/assets/6689979/cd4ef1dc-80fa-410f-a1af-ef52f38f8db4)

**Comment by seerge** [comment]
@skuma01 hmm, your config matches the log, 

```
25/04/2024 2:36:10 pm: PowerLimit A3 = 50 : OK
25/04/2024 2:36:10 pm: PowerLimit A0 = 39 : OK
```

```
  "limit_total_2": 50,
  "limit_slow_2": 39,
```

But since PL1 is 50W - your power will be limited to 50 :) it's normal that it goes above 45 obviously ...

as for UI showing incorrect value - can you update to the latest 0.167 and check if it persists there ?

**Comment by skuma01** [comment]
oh wow, okay idk why that didn't update. I'll update the config to be my desired settings!

thank you!

UI is still showing incorrect value 🤔

**Comment by seerge** [comment]
@skuma01 for UI check this build

[GHelper.zip](https://github.com/seerge/g-helper/files/15119517/GHelper.zip)

You don't need to edit config to set limits, dragging sliders is enough.

Please check if limits work.

Pl1 = is a permanent limit
PL2 = is a short (2 min) boost limit

When you run benchmark first 2 mins (or so) limit will be hitting PL2 then drop to PL1

For simplicity of testing just set PL1/PL2 to same value

**Comment by skuma01** [comment]
This fixed it! Thank you so much!

**Comment by seerge** [comment]
@skuma01 ok, so power limits work now ? Correct ?

**Comment by skuma01** [comment]
Yes, and the UI is fixing it. Thank you so much for such a quick solution!

**Comment by seerge** [comment]
Great, thanks for spotting
