### ISSUE TITLE
OD isnt available after i uninstalled armourycrate

### ISSUE THREAD

**Issue by ILikeLight** [seerge/g-helper#2497]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

OD isnt available anymore, it also doesnt show when im on gpu only mode

### How to reproduce the bug?

uninstall armoury crate and go to refresh rate options and overdrive isnt available anymore

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15127914/log.txt)

### Device and Model

Asus Zephyrus g16 2024 GU605MI

### Additional information.

![image](https://github.com/seerge/g-helper/assets/84566383/2b069811-62a9-4cc7-a50e-3f8521e58927)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.167.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@ILikeLight hello, 

You never had OD option. 
You have OLED model, they don't need any overdrive, it's almost instant response display  already

It has nothing to do with uninstalling AC as well

Thanks.

**Comment by ILikeLight** [comment]
i have the lcd version tho

**Comment by ILikeLight** [comment]
@seerge i have the ips panel.

i bought this laptop in the netherlands and there they have an option for a 4070 with oled and an option for a 4070 with an ips panel

thanks.

**Comment by seerge** [comment]
@ILikeLight ok. Valid point.

I was not aware that such thing even exists.

Try this build, I have explicitly removed your model from OLED list 

[GHelper.zip](https://github.com/seerge/g-helper/files/15140098/GHelper.zip)

**Comment by seerge** [comment]
@ILikeLight did you have a chance to try the build I posted here?

**Comment by ILikeLight** [comment]
i did try it and now it shows the OD option but i dont really have a way of validation that it works
![image](https://github.com/seerge/g-helper/assets/84566383/5d3fdc04-5489-4c27-837e-ee892548595f)

**Comment by seerge** [comment]
@ILikeLight if says Overdrive in the title it means device has reported back that it's enabled now :)

Thanks for spotting

**Comment by ILikeLight** [comment]
Thanks for fixing your already amazing software!!

**Comment by WuSiYu** [comment]
I have a GU605MV (Zephyrus G16 2024 U9+4060, OLED model), and found overdrive related options show up after 0.170.0 update, is this as expected?

**Comment by seerge** [comment]
@WuSiYu i have changed logic, so it will show Overdrive option if corresponding endpoint exists in Asus Driver / Firmware. 

It could be that Asus being Asus just kept endpoint for your device . It just won't have any effect on you.

**Comment by seerge** [comment]
@WuSiYu you can try to add to the beginning of  ``config.json`` following line
```
"debug" : 1,
```

Restart app. Open ``Extra`` and click on a new zoom-glass icon. It will list all available endpoints for your device.
Upload that list here

**Comment by WuSiYu** [comment]
```
Scan started 2024/5/5 16:39:09
00050019: 0001 (1)
00050020: 0000 (0)
00050021: 40000 (262144)
00060095: 0001 (1)
00090016: 0001 (1)
00090020: 0000 (0)
00090030: 0050 (80)
00100051: 0001 (1)
00100055: 0004 (4)
00100056: 0000 (0)
00100057: 0000 (0)
00110013: 0015 (21)
00110014: 0014 (20)
00110031: 002A (42)
00120057: 880000 (8912896)
00120061: 60001 (393217)
0012006C: 0002 (2)
00120070: 0000 (0)
00120075: 0003 (3)
0012007E: 0001 (1)
00120094: 0044 (68)
00120098: 0000 (0)
00120099: 0037 (55)
001200A0: 0000 (0)
001200A3: 0000 (0)
001200C0: 0000 (0)
001200C1: 0000 (0)
001200C2: 0000 (0)
001200D2: 0806 (2054)
001200D3: 0806 (2054)
001200D4: 0001 (1)
00130021: 20002 (131074)
00130022: 0001 (1)
00130024: 0001 (1)
00130026: 0001 (1)
00130031: 0001 (1)
---------------------
```

**Comment by seerge** [comment]
@WuSiYu great

```
00050019: 0001 (1)
```

Is Overdrive :) and your system even reports it as ON (1)

I can imagine your case is similar to @ILikeLight and your specific model also exists in IPS variant (at least in NL they clearly have one https://tweakers.net/pricewatch/2030606/asus-rog-zephyrus-g16-2024-gu605mv-qp101w/specificaties/ )

So they have kept this option in BIOS without allowing to separate them

**Comment by WuSiYu** [comment]
Yes, I also found there are IPS variant for this model, althroght is not avaliable in all region, with the model of `GU605Mx-QPxxxx` (while the OLED variants are `GU605Mx-QRxxxx`). It might be possible to distinguish them by their full model names.
ref: https://rog.asus.com/laptops/rog-zephyrus/rog-zephyrus-g16-2024/spec/

**Comment by seerge** [comment]
@WuSiYu full model name is not reported anyhow. Windows reports only "GU605MV" part :)

**Comment by WuSiYu** [comment]
That's pity

**Comment by nhuuphuoc123-cloud** [comment]
@seerge hey man i have the same problem now my model is asus rog strix g18 2023 ips panel and i only have 240hz option instead of 240hz+OD :((

**Comment by ysnkhn** [comment]
facing the same issue, i have the OLED panel and i had the the refresh rate + Overdrive option before but on the latest version of Ghelper (0.279) it doesn't appear anymore. the version of Ghelper shared here does have the option though, and i don't know since which version this OD disappeared
