### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by xB-r** [seerge/g-helper#2498]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

There is a spelling error in the update section. The word 'software' is mistyped as 'sotfware'

### How to reproduce the bug?

![Screenshot 2024-04-26 125713](https://github.com/seerge/g-helper/assets/84455199/2336dd40-0ab7-400c-bce3-b05b3e833f9f)
![Screenshot 2024-04-26 125718](https://github.com/seerge/g-helper/assets/84455199/5fbf92c2-2450-48b3-bab5-a3d7563c5d2f)

### Logs

not needed

### Device and Model

Asus ROG zephyrus m16 GU604VI

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.167

### OS

Windows 11

**Comment by seerge** [comment]
@xB-r hello,

It's indeed disappointing but that is how Asus has spelled it on their website and in API.
https://rog.asus.com/support/webapi/product/GetPDDrivers?website=global&model=GU604VI&cpu=GU604VI&osid=52

![Screenshot 2024-04-26 112235](https://github.com/seerge/g-helper/assets/5920850/697ee950-7005-464a-b659-137e1a1a05fc)

App just shows that as is. I can't fix every spelling error they do

**Comment by xB-r** [comment]
Oh ok, no worries, i didnt know its from asus.
