### ISSUE TITLE
G16 2024 Power limit does not work

### ISSUE THREAD

**Issue by KongCL82** [seerge/g-helper#2499]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

On my G16 with the Core Ultra 9 185H changing the power limit and check apply power limit no matter wut value u set it to it mode will say for example balanced + 80w. And when in game it will crashed and turn the machine off if you actually modified the power limit no matter what you set it to and start a game.

### How to reproduce the bug?

1.Go to Fans + Power.
2. Drag pl1 and pl2 value to anything.
3. Check the Apply Power Limits box.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15131008/log.txt)

### Device and Model

Asus Zephyrus GU605MZ

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

0.167.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@KongCL82 hello,

I see that you were setting power limits for your Balanced mode
```
26/4/2024 8:44:37 PM: Mode = 0 : OK
26/4/2024 8:44:38 PM: PowerLimit A3 = 40 : OK
26/4/2024 8:44:38 PM: PowerLimit A0 = 40 : OK
```

And app has set them :)
After that you have apparently unchecked (or has reset limits to defaults) ?

How do you test that limits don't work ? Where do you benchmark ?

**Comment by KongCL82** [comment]
> @KongCL82 hello,
> 
> I see that you were setting power limits for your Balanced mode
> 
> ```
> 26/4/2024 8:44:37 PM: Mode = 0 : OK
> 26/4/2024 8:44:38 PM: PowerLimit A3 = 40 : OK
> 26/4/2024 8:44:38 PM: PowerLimit A0 = 40 : OK
> ```
> 
> And app has set them :) After that you have apparently unchecked (or has reset limits to defaults) ?
> 
> How do you test that limits don't work ? Where do you benchmark ?

I tested in warzone and also granblue relink and both just turned the computer off after a while, granblue it crashed within 10 minutes. I unchecked it after i turned the laptop back on.

**Comment by seerge** [comment]
@KongCL82 well, but how is it related to power limit?

To test if limit is working, you would need to run some CPU benchmark (like cinebench) and monitor actual power usage using HWinfo for example.

Btw, I would advice to update to latest https://github.com/seerge/g-helper/releases/tag/v0.168 as there I did an UI fix (that would show incorrect value of power limit) on main screen (while correct limits were applied of course)

**Comment by KongCL82** [comment]
> @KongCL82 well, but how is it related to power limit?
> 
> To test if limit is working, you would need to run some CPU benchmark (like cinebench) and monitor actual power usage using HWinfo for example.
> 
> Btw, I would advice to update to latest https://github.com/seerge/g-helper/releases/tag/v0.168 as there I did an UI fix (that would show incorrect value of power limit) on main screen (while correct limits were applied of course)

ill give it a go thanks, but its weird no matter which mode its on silent, balanced or performance the pl1 pl2 is all at 80w? according to the intel whitepaper it range from 35-65w configurable from what i can find?

**Comment by seerge** [comment]
@KongCL82  

It's not set to 80W, it was just a bug in user interface (just showing 80w no matter what), while correct limit was in fact applied based on what you have selected with a slider

Check this issue https://github.com/seerge/g-helper/issues/2492 :)

**Comment by seerge** [comment]
@KongCL82 any updates on the matter?

**Comment by KongCL82** [comment]
> @KongCL82 any updates on the matter?
Seems resolved thanks.

**Comment by seerge** [comment]
@KongCL82 great
