### ISSUE TITLE
Feature to activate GPU fans when CPU is above specific temp for a set amount of time. (also option to turn off fans when GPU temp is low enough).

### ISSUE THREAD

**Issue by User198263321** [seerge/g-helper#2501]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Some laptops have heat pipes on the CPU that lead to the GPU heatsinks that are only useful when the GPU fan is on. However, when doing CPU only workloads, the GPU fan does not normally activate unless the GPU is turned on (the GPU temp is read at 0 otherwise). This would result in loss of cooling efficiency, and would also lead to the heatsinks on the GPU side to get very hot.

### Describe the solution you'd like

A feature could be present in the software. **When activated optionally,** it would trick the GPU fans into turning on (Literally named "Run GPU fan when CPU reaches specific temp"). The GPU would be activated by a dummy process, which uses the Nvidia/AMD GPU, ideally requesting the lowest power setting and clocks if that is the only thing running (likely controlled by the GPU driver anyways). This would be controlled by the software, not the BIOS. The preset GPU fan curve dictates how the GPU fan will behave until the GPU turns off, then it will be 0rpm.

When enabled, there are variables for the following:

![ghelper suggestion image](https://github.com/seerge/g-helper/assets/53535277/41dcad45-fa55-4236-841e-fb23c6390f62)
1. "CPU Set Temp" GPU dummy process will not activate unless CPU is above this temp
2. "CPU Temp Hold time" If the feature is currently disabled (GPU is not running), this option will track how long CPU is at this temperature until the GPU dummy process runs. If set to 0. GPU is turned on instantly from the dummy process to run the fans until temperature is below "Set CPU temp"
3. "Below GPU Temp to shutoff" Option is optional, but this would mean that instead of shutting off through low CPU temp, it will be dictated by the GPU temp, as that tends to get hot when the heatsink is hot. (for me, it is usually around 55c, and when it is cool, it would be around 37c while the GPU is running). When below the specified GPU temp, it will stop running the GPU process, thus turning off the GPU and the fans when the GPU is below the specified temperature.

4. (checkbox) "Still don't shut off unless CPU is below Set Temp" This checkbox is only exposed when "Below GPU Temp to shutoff" is also checked. This would mean the temperature for the GPU **and** CPU must be below the specific amount for the feature to shut off.

### Describe alternatives you've considered

Manually open any software that uses the dedicated graphics processor, and wait until the heatsinks cool off.

### Device and Model

ASUS TUF F15 2022

**Comment by seerge** [comment]
@User198263321 hello,

G-Helper just can only set a fan curve (optionally), it doesn't control your fans in realtime anyhow. Same as AC does not.

But you can try an [experimental build with manual fan control](https://github.com/seerge/g-helper/discussions/2272)

That one offers you to set an option for both fans to follow MAX from CPU/GPU temps :) (check readme there)

Thanks.

**Comment by seerge** [comment]
@User198263321 

What do you mean under "dummy process" ? Experimental build will run both fans following CPU temp if GPU temp is not available.

**Comment by seerge** [comment]
@User198263321 did you try Experimental build I linked ?

**Comment by seerge** [comment]
@User198263321 you can achieve that by adjusting that by setting GPU fan curve (assuming it will follow CPU temp in most of the cases)
