### ISSUE TITLE
unified fan control

### ISSUE THREAD

**Issue by dvdganon** [seerge/g-helper#2504]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

hi, great work on the Ghelper. i am using it and h really like some of the features.

i think that there is something that can make the fan control much better.
as i know, the GPU and CPU are sharing both fans. (i have Zephyrus duo 16 2023, but i believe this is something that exist in other ASUS models) 

### Describe the solution you'd like

My idea is to give the option to control both fans in a way that they keep the same RPM. so they are working the same. and the RPM will be controlled according to the highest temp (GPU or CPU)

for example: i can say to the both fans to work at 3000rpm when the cpu or gpu at 70 degrees.
in this case, if one of the cheeps will get to 70c . both of the fans will work at 3000rpm.

Regards,
David. 

### Device and Model

Zephyrus duo 16 2023 win11

**Comment by seerge** [comment]
@dvdganon hello,

G-Helper doesn't control your fans in realtime anyhow, [they are controlled by BIOS ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)

If you want - you can try an **[Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)**
 
Please read that topic carefully. It can allow you to do what you ask (if you would set identical curves for CPU / GPU)

Thanks.

**Comment by dvdganon** [comment]
Can I set both fans to be controlled by cpu ?

**Comment by seerge** [comment]
@dvdganon yes, you can

**Comment by dvdganon** [comment]
Can you tell me how ?  This is in bios ? or other software ?

**Comment by dvdganon** [comment]
I will try. Thanks.

**Comment by dvdganon** [comment]
hi, regarding the g-helper.

i am using it and i notice a problem:  the cpu temp are going over the max
temp. any idea how to fix it ?
