### ISSUE TITLE
Anime Matrix Animate a static image?

### ISSUE THREAD

**Issue by 88fingerslukee** [seerge/g-helper#2505]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Not a problem but it'd be awesome to convert an image into an animation. If there's already a tool for this somewhere I'd be happy to delete this request.

### Describe the solution you'd like

As an example, I have a logo that I'd like displayed but when sized down to fit the matrix display, the text is too hard to read. When it's large enough to read it's too big for the display. I'd love for it to scroll across the display.  Any thoughts on this?

### Device and Model

Zephyrus GA402XZ

**Comment by seerge** [comment]
@88fingerslukee hello.

Idea of G-Helper is to be simple to use and lightweight :) and not to copy functions of a Photoshop or so

If you want to animate your static image, you need to use some external tool, save it as a GIF and set in G-Helper.

Thanks.

**Comment by 88fingerslukee** [comment]
thank you for the quick reply. So if I put an animated GIF in there it'll act animated on the matrix? Thanks!!

**Comment by seerge** [comment]
@88fingerslukee yes, it can play animated GIFs
