### ISSUE TITLE
Asus TUF Dash F15 GPU Temp Target doesn't work

### ISSUE THREAD

**Issue by Vlxd1312** [seerge/g-helper#2508]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When on Ultimate mode and changing the Temperature Target slider the temperature never obeys the set target. Furthermore as seen from HWINFO no matter what i set it to, the GPU Temp Limit does not change and is fixed on 87°C, but when on standard mode the temp target works normally and the GPU temp does not exceed the set limit plus i can see the limit change on HWINFO to whatever i set it to.

### How to reproduce the bug?

1. Go to FANS + POWER
2.  Click on GPU
3.  Change the Temperature Target slider

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15138638/log.txt)

### Device and Model

ASUS TUF Dash F15 FX517ZE

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.167

### OS

Windows 11 21H2

**Comment by seerge** [comment]
@Vlxd1312 hello,

I have already answered that on reddit :)

App sets the limit every single time (you can check for this in the log)
```
04/27/24 18:29:55: PowerLimit C2 (GPU TEMP) = 80 : OK
```

If it works in Standard and does not work in Ultimate, most likely this is how Asus has programmed BIOS on your device.

Can you check if you would set same limit in Armoury in Ultimate mode, would it work ?

**Comment by seerge** [comment]
Closing as answered as this was already discussed on reddit https://www.reddit.com/r/Asustuf/comments/1cegvr1/asus_tuf_ghelper_temp_target_no_working/
