### ISSUE TITLE
g-helper not opening/running on 2024 G14 RTX4060 and keyboard backlights preference not working

### ISSUE THREAD

**Issue by aptx91** [seerge/g-helper#2509]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hello, G-helper is not opening or running on my 2024 G14 GA403UV. I restarted my laptop which ended up installing some updates and ran it as administrator and it ran and had an update which I installed vs. 0.167.0. Also of note is that my RGB keyboard backlight does not reflect the selection I have in settings. For example, while logged in and running my laptop, it is stuck on a solid static blue, even though in g-helper I have it set to rainbow. I tried setting it to breath, color cycle, even choosing static and changing the color doesn't change the keyboard backlight etc., and it does not reflect while the laptop is logged in and on. However, as soon as I lock the laptop or restart it/shut it off, it shows the selected preference.

### How to reproduce the bug?

Open GHelper > doesn't open > run as administrator > doesn't open
For keyboard lights: GHelper > select backlight style > stays on default static blue > lock screen and shows selected backlight preference > unlock PC and it reverts back to static blue

### Logs

[Ghelper_.net failure.txt](https://github.com/seerge/g-helper/files/15140349/Ghelper_.net.failure.txt)

### Device and Model

ROG Zephyrus G14 GA403UV_GA403UV

### Additional information.

https://github.com/seerge/g-helper/assets/168311987/e124ddfc-9bc2-4c6f-9789-e2f028d76cb7

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.167.0

### OS

Windows 11 23H2 Build 22631.3527

**Comment by seerge** [comment]
@aptx91 hello, 

1. You need to [install .NET7](https://download.visualstudio.microsoft.com/download/pr/8091a826-e1c4-424a-b17b-5c10776cd3de/8957f21a279322d8fac9b542c6aba12e/dotnet-sdk-7.0.408-win-x64.exe) as it pretty much says in the [readme](https://github.com/seerge/g-helper/wiki/Requirements#requirements-mandatory)
2.  Backlight question is [also covered in FAQ](https://github.com/seerge/g-helper/wiki/FAQ#backlight-doesnt-change-color-or-stays-blue)

Thanks.
