### ISSUE TITLE
cpu power limit reset when change GPU mode on G14 2024 with dc or type-c power mode

### ISSUE THREAD

**Issue by xt2357** [seerge/g-helper#2510]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I have set cpu power limits on both balance/silent mode, but it will be reset to some other values occasionally when GPU mode is changed from echo to standard or vice versa with type-c power(100w) connected or dc power (power unplugged). 

### How to reproduce the bug?

1. set cpu limits to 20w/20w/20w in balance mode, change GPU mode to standard, apply these settings.
2. unplug the power or connect type-c power
3. change GPU mode to echo and change back (it happens occasionally, try more times when not reproduced)
4. check cpu limits, it should be reset to higher values than 20w

### Logs

[log - copy.txt](https://github.com/seerge/g-helper/files/15140808/log.-.copy.txt)

### Device and Model

G14 2024 with 4060 GPU

### Additional information.

I use HW info to check limits on cpu (i also tried run cpu benchmarks for checking, but using HW info is more easy to elaborate the issue)

![image](https://github.com/seerge/g-helper/assets/7747908/3f4029e9-78bd-44a6-a69d-8040437f8fc4)
![image](https://github.com/seerge/g-helper/assets/7747908/3af3e9f2-3dbb-482d-bca6-7dfee5836083)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.168.0

### OS

windows 11 10.0.22621

**Comment by seerge** [comment]
@xt2357 hello, does clicking on Balanced mode button again make power limits work ?

**Comment by xt2357** [comment]
> @xt2357 hello, does clicking on Balanced mode button again make power limits work ?

yes, clicking on Balanced mode will set to the cpu power limits to the correct values again

**Comment by seerge** [comment]
@xt2357 ok, cause I can't reproduce it honestly

You have mixed 2 separate actions - unplugging / plugging and changing GPU mode

Can you check which one of them actually causes reset ?

**Comment by xt2357** [comment]
> @xt2357 ok, cause I can't reproduce it honestly
> 
> You have mixed 2 separate actions - unplugging / plugging and changing GPU mode
> 
> Can you check which one of them actually causes reset ?

I can reproduce the issue in both situations, you can try to reproduce it in the case of unplugging. That is: 

1. unplugging the laptop
2. set GPU standard mode, set to balance mode(cpu limit to 20w)
3. change GPU mode and check the limits

By the way, my bios version is 303.

**Comment by seerge** [comment]
@xt2357 my question was if just unplugging / plugging causes limit to reset. Based from your answer it's not - and it has to be changes of GPU mode

**Comment by xt2357** [comment]
> @xt2357 my question was if just unplugging / plugging causes limit to reset. Based from your answer it's not - and it has to be changes of GPU mode

 unplugging / plugging does not cause limit reset as far as I observed

**Comment by seerge** [comment]
Try to quit app and add following line to the beginning of ``config.json``

```
"mode_reapply" : 1,
```

**Comment by xt2357** [comment]
> @xt2357
> 
> Try to quit app and add following line to the beginning of `config.json`
> 
> ```
> "mode_reapply" : 1,
> ```

After adding this config, I observed that the limits will be reset to higher values first (issue reproduction) and then reset to correct values after 3-5 seconds when change GPU mode, it solves my issue, thanks!

**Comment by seerge** [comment]
@xt2357 great

**Comment by xt2357** [comment]
> @xt2357
> 
> Try to quit app and add following line to the beginning of `config.json`
> 
> ```
> "mode_reapply" : 1,
> ```

It seems that something other than Ghelper also tried to reset the cpu limits. I guess the "mode reapply" will reapply the limits when changing GPU mode?

**Comment by seerge** [comment]
@xt2357 yes, it reapplies mode after turning GPU on or off.

**Comment by seerge** [comment]
@xt2357 could be AMD driver .. but i don't know what exactly is doing that )

**Comment by xt2357** [comment]
> @xt2357 could be AMD driver (as when you set Eco it's your iGPU only + your CPU is AMD) ... but i don't know what exactly is doing that )

Yeah, your opinion is very reasonable, I guess that it is an AMD driver or asus bios compatibility problem, whatever the deep reason it is, your mode_reapply config solve it gracefully.
