### ISSUE TITLE
please add caps lock indicator and number lock indicator

### ISSUE THREAD

**Issue by requster** [seerge/g-helper#2511]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

it could be and it could be not

### Describe the solution you'd like

caps lock indicator and number lock indicator with shortcut
if u could add something for laptops that doesnt have number lock to play a game that need that like GTA V ONLINE
just like a button to change some button to number lock and then turn it back to defualt by some shortcuts

### Device and Model

ASUS ROG STRIX G15 G513QM 2021

**Comment by requster** [comment]
![LAUCHMANAGER-1856656742](https://github.com/seerge/g-helper/assets/168338410/5282da70-b393-422b-9f26-e2cd703befe9)

**Comment by seerge** [comment]
@requster hello,

I don't want to overload app with features that are not asus-specific and can be done with easily with existing utilities :)

Quick googling has led me to this topic
https://www.elevenforum.com/t/how-to-get-visual-caps-lock-notification-on-windows-11.15498/

Or this
https://cli.jonaskohl.de/

Thanks :)
