### ISSUE TITLE
Missing logo (back lid) RGB control

### ISSUE THREAD

**Issue by SilentShadow05** [seerge/g-helper#2512]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When i go into the "Extra" section in G-Helper, under the "Laptop Backlight" section I am missing controls for the lid logo, the controls that I do have available for me are for the keyboard and the lightbar only. I dot need that control option pretty bad since when the computer is in sleep mode the logo is pulsing red, in armoury crate I did had the option to turn off the logo while in sleep in mode.

### How to reproduce the bug?

1. Go to the Extra section.
2. Go to the laptop backlight section inside the extra section. 

![Screenshot 2024-04-28 132531](https://github.com/seerge/g-helper/assets/168339308/7c746ce4-a650-437f-b732-245deabe4790)

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15141751/log.txt)

### Device and Model

Asus ROG Strix Scar III G531GW

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

0.169.0

### OS

Windows 11 Pro 23H2

**Comment by SilentShadow05** [comment]
Hi Seerge! 

Thank you for the quick response, yup that did the trick, I've got the controls for the logo showing up now, also fully tested it and the logo control works exactly as expected.

Only thing is that I have a "lid" control checkbox's now as well and I do not think that's meant for my laptop since it doesn't seem to control anything, it's not an issue for me to have those extra checkboxes there, just wanted to give more info.

Thank you so much for such an amazing program!

**Comment by seerge** [comment]
@SilentShadow05 i'm glad it helped.

Again - since your device (with same model name) exists in multiple editions, i can't manually tweak UI for it :)

That flag that you have added to config unlocked extra options for you.

Lid just won't have effect on you, so you can simply ignore that

Closing as resolved
