### ISSUE TITLE
RTX 2060 Max-q power limited to 30W plugged in

### ISSUE THREAD

**Issue by linktheblack7** [seerge/g-helper#2514]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

While on AC power, the GPU (power limit of 65W) is limited to 30W when on Turbo or Balanced mode. It sometimes initially works on Turbo but once changing the mode (even back to Turbo) the GPU power is limited to 30W. I cannot restore the GPU to the high power state it is supposed to be in when on AC power. The 30W limit is normal for battery power. 

I also have the laptop connected to a monitor over USB-C that supplies up to 10W of power. I believe this turns off when I plug the AC adapter in. I've also run just a USB-C to HDMI adapter to the monitor while on AC power and I still do not get the full power from the GPU. 

### How to reproduce the bug?

Use a benchmark (I'm using Heaven) to run a 1080p ultra settings benchmark/stress test. Start in Turbo mode with AC adapter plugged in. 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15143168/log.txt)

### Device and Model

2020 Asus G14 GA401IV-BR9N6 

### Additional information.

I am on latest NVIDIA drivers (552.22 Released 4/16/2024). I've tried restarting my computer, I've tried switching from laptop display to external display via Display Port over USB-C. Sometimes the GPU will run at high power, but mostly it is limited to 30W, 2100 MHz core clock, and 810 MHz memory clock as indicated in Heaven. I did successfully run a benchmark at 1080p on the built in display and average FPS was 96.2 with a score of 2423.
GPU power limited benchmark average FPS was 21.2 with a score of 534.

![GPU 30W Limit Unigine_Heaven_Benchmark_4 0_20240428_1129](https://github.com/seerge/g-helper/assets/127129637/e0128582-7992-4d7c-9f52-b089fc80c8bd)
![Stock no OC Unigine_Heaven_Benchmark_4 0_20240428_1100](https://github.com/seerge/g-helper/assets/127129637/83bf792f-2774-47e4-a7c7-df9328d019a9)

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

0.0167.0

### OS

Windows 10 22H2 OS Build: 19045.4355

**Comment by seerge** [comment]
@linktheblack7 hello,

G-Helper doesn't control GPU power anyhow (and can't)

More over, you have a very old device, and for that model you can select only one of 3 predefined (and stored in BIOS) modes. That's pretty much it :)

It could be some hiccup with BIOS or with GPU drivers so I can advice to go through all steps in [General Troubleshooting Section](https://github.com/seerge/g-helper/wiki/Troubleshooting). 

Especially clean GPU drivers reinstall using DDU and hardware rest. May be that will help.

Besides that I can't do anything cause it's not directly related to G-Helper.

P.S. I have noticed that you were setting power limits for CPU, and they seem to be crazy high (150W?)
```
4/28/2024 11:05:55 AM: STAPM: 150 OK
4/28/2024 11:05:55 AM: STAPM2: 150 OK
4/28/2024 11:05:55 AM: SLOW: 150 OK
4/28/2024 11:05:55 AM: FAST: 150 OK
```

I would advice either to keep them default (i.e. uncheck apply). Or at least set something reasonable for your CPU like 40W

Thanks and good luck.

I'm closing this as answered. Feel free to post an update if you will find a solution for your case :)

**Comment by linktheblack7** [comment]
It’s not that old 🥺😭 lol jk

Hm. I think it must be an issue with the laptop detecting the low power usb c PD even though the AC adapter is connected. 

Unfortunately, I am running on a clean windows install with fresh install of drivers lol 

I’m not sure why the CPU power limit was super high. I know the cpu doesn’t go above like 65W or something. I probably slid it to the right thinking it would set it to default like some other setting do lol my bad.

Thank you for the feedback! Sorry for the confusion (ie. user error lol)

**Comment by seerge** [comment]
@linktheblack7 it's the first G14 in the series :) it doesn't have neither MU switch nor Eco mode.

Even CPU power limits that you see in app, you didn't had in Armoury. G-Helper uses a fallback method (using [UXTU](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility) "approach" for them). 

So it's very limited in terms of settings. Only 3 ready-made presets (modes).

Are you sure that your power supply is working well ? It was someone else here, with a broken adapter but G14 2022, and when his laptop was taking too much power - it was switching to battery (and therefore also behaving like the one on battery)

**Comment by linktheblack7** [comment]
That makes sense. 

Yeah my power supply is working fine. I noticed it has been working just fine on the AC adapter with an external display when I dont have any power coming in on the USB-PD. 

I know there's a setting in windows advanced power options regarding using the dGPU vs iGPU. Is there a way you can add a toggle to the Fans & Power settings that just turns off the dGPU for a particular mode? Since my G14 doesn't have the separate GPU modes? I know that there is a way to manually disable the dGPU. Maybe it's through nvidia control panel or the advanced power options (Switchable dynamic graphics?). Are you able to incorporate that setting into G-helper (for these older devices/devices that don't support the different GPU modes)? If not, then I understand. 

Thanks again! You're the best!
