### ISSUE TITLE
Mouse Scroll not working on GPU Core Clock Limit

### ISSUE THREAD

**Issue by Constrat** [seerge/g-helper#2515]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

All fans + powers sliders work correctly when mouse scrolling, the only one that does not have the scroll functionality is the Core Clock Limit in the GPU section.

### How to reproduce the bug?

1. Fans + Power
2. GPU
3. Slide on 
![image](https://github.com/seerge/g-helper/assets/56174894/1aa7e109-d902-4ed4-aaeb-47f581fe08e2)
4. Nothing happens

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15153044/log.txt)

### Device and Model

Asus ROG Strix G713RW

### Armoury Crate

Uninstalled

### Version

0.167.0

### OS

Win11 23H2

**Comment by seerge** [comment]
@Constrat i think it works, but cause for clock limit step is like 5mhz from 3000 you just don’t notice it moving? :)

**Comment by Constrat** [comment]
I just confirmed it doesn't move even when scrolling with free wheel.
As an example I'm at 1650MHz, spamming the scroll won't change the value no matter what.

**Comment by seerge** [comment]
@Constrat this build should change minimal change value from 50 to 5 (this is what preventing mouse-wheel scroll)
[GHelper.zip](https://github.com/seerge/g-helper/files/15180377/GHelper.zip)
