### ISSUE TITLE
Rebing M2 (Volume Up key) to other M key

### ISSUE THREAD

**Issue by inasense** [seerge/g-helper#2516]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

**Apologies for typo in title - if it could be corrected to Rebind/Rebinding that would be appreciated. Thanks.**

Good Day, 

Sadly, the M2 (Volume Up) function key on my 2022 G14 GA402RJ suddenly stopped working. The other three M keys work as they should. I went into g-helper hoping to rebind the volume up call to M4 instead, but saw it is not an option. I then noticed the "custom" setting, but from what I can tell programming Volume Up via this option is not possible? Apologies if this is just a case of ignorance; I browsed many threads but couldn't find an answer. Also, if anyone has any ideas about why that M2 key just...died suddenly I'd surely be keen to hear them.  Thank you. 

### Describe the solution you'd like

Being able to rebind the Volume Up call to another key, ideally another M/function key. 

### Describe alternatives you've considered

Using a custom keybinder to try and bind the key elsewhere on the keyboard. No success. 

### Device and Model

Asus Zephyrus G14 GA402RJ

**Comment by seerge** [comment]
@inasense hello, it's already possible, please check Readme on how to do that
https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-hotkey-actions

```
VK_VOLUME_UP | 0xAF 
```

https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

**Comment by inasense** [comment]
Thanks, @seerge!
