### ISSUE TITLE
ASUS Rog Keris Wired

### ISSUE THREAD

**Issue by eflaron** [seerge/g-helper#2517]
### Mouse / peripheral model and version

Asus Rog Keris Wired

### Armoury Crate Screenshots

![Screenshot 2024-04-29 171050](https://github.com/seerge/g-helper/assets/101951195/8a6fb896-b264-4bc6-a023-405090f01882)
![Screenshot 2024-04-29 171114](https://github.com/seerge/g-helper/assets/101951195/5db87f14-9158-4676-8c69-4249c310d281)
![Screenshot 2024-04-29 171120](https://github.com/seerge/g-helper/assets/101951195/acc540fa-7023-459c-a8d5-0ed4d5569b48)
![Screenshot 2024-04-29 171130](https://github.com/seerge/g-helper/assets/101951195/89a4c3d5-5cba-4e59-ad4c-0503e5656755)
![Screenshot 2024-04-29 171135](https://github.com/seerge/g-helper/assets/101951195/b5a8f334-3d67-423f-a452-47791357ddfb)

### USB Details

 =========================== USB Port2 ===========================

Connection Status        : 0x01 (Device is connected)
Port Chain               : 1-2
Properties               : 0x01
 IsUserConnectable       : yes
 PortIsDebugCapable      : no
 PortHasMultiCompanions  : no
 PortConnectorIsTypeC    : no
ConnectionIndex          : 0x02 (Port 2)
CompanionIndex           : 0
 CompanionHubSymLnk      : USB#ROOT_HUB30#4&3af0ece5&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}
 CompanionPortNumber     : 0x0D (Port 13)
 -> CompanionPortChain   : 1-13

      ========================== Summary =========================
Vendor ID                : 0x0B05 (ASUSTek Computer Inc.)
Product ID               : 0x195C
USB Version              : 2.0 -> but Device is Full-Speed only
Port maximum Speed       : High-Speed (Companion Port 1-13 is doing the SuperSpeed)
Device maximum Speed     : Full-Speed
Device Connection Speed  : Full-Speed
Self powered             : no
Demanded Current         : 100 mA
Used Endpoints           : 5

      ======================== USB Device ========================

        +++++++++++++++++ Device Information ++++++++++++++++++
Device Description       : USB Composite Device
Device Path              : \\?\USB#VID_0B05&PID_195C#5&242a2f40&0&2#{a5dcbf10-6530-11d2-901f-00c04fb951ed} (GUID_DEVINTERFACE_USB_DEVICE)
Kernel Name              : \Device\USBPDO-7
Device ID                : USB\VID_0B05&PID_195C\5&242A2F40&0&2
Hardware IDs             : USB\VID_0B05&PID_195C&REV_0109 USB\VID_0B05&PID_195C
Driver KeyName           : {36fc9e60-c465-11cf-8056-444553540000}\0008 (GUID_DEVCLASS_USB)
Driver                   : \SystemRoot\System32\drivers\usbccgp.sys (Version: 10.0.22621.3155  Date: 2024-04-25  Company: Microsoft Corporation)
Driver Inf               : C:\WINDOWS\inf\usb.inf
Legacy BusType           : PNPBus
Class                    : USB
Class GUID               : {36fc9e60-c465-11cf-8056-444553540000} (GUID_DEVCLASS_USB)
Service                  : usbccgp
Enumerator               : USB
Location Info            : Port_#0002.Hub_#0002
Address                  : 2
Location IDs             : PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(2), ACPI(_SB_)#ACPI(PC00)#ACPI(XHCI)#ACPI(RHUB)#ACPI(HS02)
Container ID             : {5eb48440-0434-11ef-b645-a002a5ab2745}
Manufacturer Info        : (Standard USB Host Controller)
Capabilities             : 0x84 (Removable, SurpriseRemovalOK)
Status                   : 0x0180400A (DN_DRIVER_LOADED, DN_STARTED, DN_REMOVABLE, DN_NT_ENUMERATOR, DN_NT_DRIVER)
Problem Code             : 0
Address                  : 2
Power State              : D0 (supported: D0, D1, D2, D3, wake from D0, wake from D1, wake from D2)

        +++++++++++++++++ Registry USB Flags +++++++++++++++++
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\usbflags\0B05195C0109
 osvc                    : REG_BINARY 00 00

        ---------------- Connection Information ---------------
Connection Index         : 0x02 (Port 2)
Connection Status        : 0x01 (DeviceConnected)
Current Config Value     : 0x01 (Configuration 1)
Device Address           : 0x06 (6)
Is Hub                   : 0x00 (no)
Device Bus Speed         : 0x01 (Full-Speed)
Number of open Pipes     : 0x04 (4 pipes to data endpoints)
Pipe[0]                  : EndpointID=3  Direction=IN   ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x40    bInterval=1   -> 718 Bits/ms = 89750 Bytes/s
Pipe[1]                  : EndpointID=3  Direction=OUT  ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x40    bInterval=1   -> 718 Bits/ms = 89750 Bytes/s
Pipe[2]                  : EndpointID=1  Direction=IN   ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0xB     bInterval=1   -> 224 Bits/ms = 28000 Bytes/s
Pipe[3]                  : EndpointID=2  Direction=IN   ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x11    bInterval=1   -> 280 Bits/ms = 35000 Bytes/s
Data (HexDump)           : 02 00 00 00 12 01 00 02 00 00 00 40 05 0B 5C 19   ...........@..\.
                           09 01 01 02 00 01 01 01 00 06 00 04 00 00 00 01   ................
                           00 00 00 07 05 83 03 40 00 01 00 00 00 00 07 05   .......@........
                           03 03 40 00 01 00 00 00 00 07 05 81 03 0B 00 01   ..@.............
                           00 00 00 00 07 05 82 03 11 00 01 00 00 00 00      ...............

        --------------- Connection Information V2 -------------
Connection Index         : 0x02 (2)
Length                   : 0x10 (16 bytes)
SupportedUsbProtocols    : 0x03
 Usb110                  : 1 (yes, port supports USB 1.1)
 Usb200                  : 1 (yes, port supports USB 2.0)
 Usb300                  : 0 (no, port not supports USB 3.0) -> but Companion Port 1-13 does
 ReservedMBZ             : 0x00
Flags                    : 0x00
 DevIsOpAtSsOrHigher     : 0 (Device is not operating at SuperSpeed or higher)
 DevIsSsCapOrHigher      : 0 (Device is not SuperSpeed capable or higher)
 DevIsOpAtSsPlusOrHigher : 0 (Device is not operating at SuperSpeedPlus or higher)
 DevIsSsPlusCapOrHigher  : 0 (Device is not SuperSpeedPlus capable or higher)
 ReservedMBZ             : 0x00
Data (HexDump)           : 02 00 00 00 10 00 00 00 03 00 00 00 00 00 00 00   ................

    ---------------------- Device Descriptor ----------------------
bLength                  : 0x12 (18 bytes)
bDescriptorType          : 0x01 (Device Descriptor)
bcdUSB                   : 0x200 (USB Version 2.0) -> but device is Full-Speed only
bDeviceClass             : 0x00 (defined by the interface descriptors)
bDeviceSubClass          : 0x00
bDeviceProtocol          : 0x00
bMaxPacketSize0          : 0x40 (64 bytes)
idVendor                 : 0x0B05 (ASUSTek Computer Inc.)
idProduct                : 0x195C
bcdDevice                : 0x0109
iManufacturer            : 0x01 (String Descriptor 1)
 Language 0x0409         : "ASUSTeK"
iProduct                 : 0x02 (String Descriptor 2)
 Language 0x0409         : "ROG KERIS"
iSerialNumber            : 0x00 (No String Descriptor)
bNumConfigurations       : 0x01 (1 Configuration)
Data (HexDump)           : 12 01 00 02 00 00 00 40 05 0B 5C 19 09 01 01 02   .......@..\.....
                           00 01                                             ..

    ------------------ Configuration Descriptor -------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x02 (Configuration Descriptor)
wTotalLength             : 0x005B (91 bytes)
bNumInterfaces           : 0x03 (3 Interfaces)
bConfigurationValue      : 0x01 (Configuration 1)
iConfiguration           : 0x00 (No String Descriptor)
bmAttributes             : 0xA0
 D7: Reserved, set 1     : 0x01
 D6: Self Powered        : 0x00 (no)
 D5: Remote Wakeup       : 0x01 (yes)
 D4..0: Reserved, set 0  : 0x00
MaxPower                 : 0x32 (100 mA)

Data (HexDump)           : 09 02 5B 00 03 01 00 A0 32 09 04 00 00 02 03 00   ..[.....2.......
                           00 00 09 21 11 01 00 01 22 22 00 07 05 83 03 40   ...!...."".....@
                           00 01 07 05 03 03 40 00 01 09 04 01 00 01 03 01   ......@.........
                           02 00 09 21 11 01 00 01 22 52 00 07 05 81 03 0B   ...!...."R......
                           00 01 09 04 02 00 01 03 00 00 00 09 21 11 01 00   ............!...
                           01 22 88 00 07 05 82 03 11 00 01                  .".........

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x00 (Interface 0)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x02 (2 Endpoints)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x00 (None)
bInterfaceProtocol       : 0x00 (None)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 00 00 02 03 00 00 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 22 00                        .!...."".
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0022 (34 bytes)
Error reading descriptor : ERROR_GEN_FAILURE (due to a obscure limitation of the Win32 USB API, see F1 Help)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x83 (Direction=IN EndpointID=3)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0040 (64 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 83 03 40 00 01                              ....@..

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x03 (Direction=OUT EndpointID=3)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0040 (64 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 03 03 40 00 01                              ....@..

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x01 (Interface 1)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x01 (1 Endpoint)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x01 (Boot Interface)
bInterfaceProtocol       : 0x02 (Mouse)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 01 00 01 03 01 02 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 52 00                        .!...."R.
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0052 (82 bytes)
Error reading descriptor : ERROR_GEN_FAILURE (due to a obscure limitation of the Win32 USB API, see F1 Help)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x81 (Direction=IN EndpointID=1)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x000B (11 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 81 03 0B 00 01                              .......

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x02 (Interface 2)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x01 (1 Endpoint)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x00 (None)
bInterfaceProtocol       : 0x00 (None)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 02 00 01 03 00 00 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 88 00                        .!...."..
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0088 (136 bytes)
Error reading descriptor : ERROR_GEN_FAILURE (due to a obscure limitation of the Win32 USB API, see F1 Help)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x82 (Direction=IN EndpointID=2)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0011 (17 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 82 03 11 00 01                              .......

    ----------------- Device Qualifier Descriptor -----------------
Error                    : ERROR_GEN_FAILURE  (because the device is Full-Speed only)

      -------------------- String Descriptors -------------------
             ------ String Descriptor 0 ------
bLength                  : 0x04 (4 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language ID[0]           : 0x0409 (English - United States)
Data (HexDump)           : 04 03 09 04                                       ....
             ------ String Descriptor 1 ------
bLength                  : 0x10 (16 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language 0x0409          : "ASUSTeK"
Data (HexDump)           : 10 03 41 00 53 00 55 00 53 00 54 00 65 00 4B 00   ..A.S.U.S.T.e.K.
             ------ String Descriptor 2 ------
bLength                  : 0x14 (20 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language 0x0409          : "ROG KERIS"
Data (HexDump)           : 14 03 52 00 4F 00 47 00 20 00 4B 00 45 00 52 00   ..R.O.G. .K.E.R.
                           49 00 53 00                                       I.S.

        +++++++++++++++++ Device Information ++++++++++++++++++
Device Description       : USB Input Device
Device ID                : USB\VID_0B05&PID_195C&MI_00\6&3340F9B&0&0000
Hardware IDs             : USB\VID_0B05&PID_195C&REV_0109&MI_00 USB\VID_0B05&PID_195C&MI_00
Driver KeyName           : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0021 (GUID_DEVCLASS_HIDCLASS)
Driver                   : \SystemRoot\System32\drivers\hidusb.sys (Version: 10.0.22621.3527  Date: 2024-04-25  Company: Microsoft Corporation)
Driver Inf               : C:\WINDOWS\inf\input.inf
Legacy BusType           : PNPBus
Class                    : HIDClass
Class GUID               : {745a17a0-74d3-11d0-b6fe-00a0c90f57da} (GUID_DEVCLASS_HIDCLASS)
Service                  : HidUsb
Enumerator               : USB
Location Info            : 0000.0014.0000.002.000.000.000.000.000
Address                  : 2
Manufacturer Info        : (Standard system devices)
Capabilities             : 0x80 (SurpriseRemovalOK)
Status                   : 0x0180200A (DN_DRIVER_LOADED, DN_STARTED, DN_DISABLEABLE, DN_NT_ENUMERATOR, DN_NT_DRIVER)
Problem Code             : 0
SelectiveSuspendEnabled  : 0
EnhancedPowerMgmtEnabled : 1
Power State              : D0 (supported: D0, D1, D2, D3, wake from D0, wake from D1, wake from D2)

        +++++++++++++++++ Device Information ++++++++++++++++++
Device Description       : HID-compliant vendor-defined device
Device Path              : \\?\HID#VID_0B05&PID_195C&MI_00#7&ac2af29&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (GUID_DEVINTERFACE_HID)
Kernel Name              : \Device\000000dd
Device ID                : HID\VID_0B05&PID_195C&MI_00\7&AC2AF29&0&0000
Hardware IDs             : HID\VID_0B05&PID_195C&REV_0109&MI_00 HID\VID_0B05&PID_195C&MI_00 HID\VID_0B05&UP:FF01_U:0001 HID_DEVICE_UP:FF01_U:0001 HID_DEVICE_UPR:FF00-FFFF HID_DEVICE
Driver KeyName           : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0024 (GUID_DEVCLASS_HIDCLASS)
Driver Inf               : C:\WINDOWS\inf\input.inf
Legacy BusType           : PNPBus
Class                    : HIDClass
Class GUID               : {745a17a0-74d3-11d0-b6fe-00a0c90f57da} (GUID_DEVCLASS_HIDCLASS)
Enumerator               : HID
Location Info            : -
Address                  : 1
Manufacturer Info        : (Standard system devices)
Capabilities             : 0xE0 (SilentInstall, RawDeviceOK, SurpriseRemovalOK)
Status                   : 0x0180200A (DN_DRIVER_LOADED, DN_STARTED, DN_DISABLEABLE, DN_NT_ENUMERATOR, DN_NT_DRIVER)
Problem Code             : 0
Power State              : D0 (supported: D0, D1, D2, D3, wake from D0, wake from D1, wake from D2)

             ++++++++++++++ HID Information +++++++++++++++
Manufacturer             : ASUSTeK
Product                  : ROG KERIS
UsagePage                : 0xFF01 (Vendor Defined)
Usage                    : 0x01 (unk)

        +++++++++++++++++ Device Information ++++++++++++++++++
Device Description       : ROG KERIS
Device Path 1            : \\?\HID#VID_0B05&PID_195C&MI_01#7&1df2cb67&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (GUID_DEVINTERFACE_HID)
Device Path 2            : \\?\HID#VID_0B05&PID_195C&MI_01#7&1df2cb67&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd} (GUID_DEVINTERFACE_MOUSE)
Kernel Name              : \Device\000000de
Device ID                : HID\VID_0B05&PID_195C&MI_01\7&1DF2CB67&0&0000
Hardware IDs             : HID\VID_0B05&PID_195C&REV_0109&MI_01 HID\VID_0B05&PID_195C&MI_01 HID\VID_0B05&UP:0001_U:0002 HID_DEVICE_SYSTEM_MOUSE HID_DEVICE_UP:0001_U:0002 HID_DEVICE
Driver KeyName           : {4d36e96f-e325-11ce-bfc1-08002be10318}\0003 (GUID_DEVCLASS_MOUSE)
Driver                   : \SystemRoot\System32\drivers\mouhid.sys (Version: 10.0.22621.1  Date: 2022-05-06  Company: Microsoft Corporation)
Driver Inf               : C:\WINDOWS\inf\oem88.inf
Legacy BusType           : PNPBus
Class                    : Mouse
Class GUID               : {4d36e96f-e325-11ce-bfc1-08002be10318} (GUID_DEVCLASS_MOUSE)
Service                  : mouhid
Enumerator               : HID
Location Info            : -
Address                  : 1
Manufacturer Info        : ASUSTeK Computer Inc.
Capabilities             : 0xA0 (SilentInstall, SurpriseRemovalOK)
Status                   : 0x0180200A (DN_DRIVER_LOADED, DN_STARTED, DN_DISABLEABLE, DN_NT_ENUMERATOR, DN_NT_DRIVER)
Problem Code             : 0
Upper Filters            : ROGMS
Power State              : D0 (supported: D0, D1, D2, D3, wake from D0, wake from D1, wake from D2)

**Comment by eflaron** [comment]
Seerge, Let me know if you need more usb details.

**Comment by eflaron** [comment]
![image](https://github.com/seerge/g-helper/assets/101951195/41a236df-5094-4ff0-832c-0e2b83ff55ec)
thanks for the build. the peripheral shows up when plugged in, but clicking on it does nothing.

**Comment by seerge** [comment]
May be @IceStormNG knows why? :)

**Comment by IceStormNG** [comment]
> @eflaron hello, try this build
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/15185940/GHelper.zip)

What exactly did you changed here? The wired variant of the keris is not implemented yet and needs a new profile. we only have the wireless one implemented.

**Comment by seerge** [comment]
@IceStormNG I have noticed that Wireless Profile had Wided class as well, I just added ProductID

https://github.com/seerge/g-helper/commit/2ff1a59ff971007d71419345597ee296c19d7356

**Comment by IceStormNG** [comment]
Yeah, that is the wireless variant when connected via cable. The Keris wired is a completely different mouse with different protocol.
When I find the time, I might write a class for that.

**Comment by IceStormNG** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/15482192/GHelper.zip)

Alright. I implemented a mouse profile based on the specs and screenshot. @eflaron please test it and let me know if everything works. If something does not work, please also send the GHelper.log file.

**Comment by eflaron** [comment]
all looks well! appreciate the work you all do 👍

**Comment by seerge** [comment]
@eflaron merged https://github.com/seerge/g-helper/pull/2655

Thanks again @IceStormNG :)
