### ISSUE TITLE
Add support for S5402Z

### ISSUE THREAD

**Issue by Mk007V2** [seerge/g-helper#2519]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Flicker-Free Dimming / Visual Mode option doesn't show up on my Vivobook S14 S5402Z. However, it does work on friend's Vivobook Pro M6500RC. We both can control it in MyASUS, but he also can in G-Helper.

### How to reproduce the bug?

![Screenshot 2024-04-30 145749](https://github.com/seerge/g-helper/assets/75898531/44526368-87d7-4b35-a115-aef8df6543af)

Running G-Helper 0.167.0 on my S5402Z. Windows 11 Pro. No Flicker-Free Dimming / Visual Mode option.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15161618/log.txt)

### Device and Model

ASUS Vivobook S 14X OLED S5402Z

### Armoury Crate

Never installed

### Asus Services

6

### Version

0.167.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Mk007V2 try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/15162259/GHelper.zip)

**Comment by seerge** [comment]
@Mk007V2 did you had a chance to try the build ?

**Comment by Mk007V2** [comment]
@seerge It worked ! Thank you a lot !
![image](https://github.com/seerge/g-helper/assets/75898531/8743b60a-d393-4b8d-99cc-9bcda2a39127)
