### ISSUE TITLE
[Bug report] Modifying CPU Boost setting in "Fans + Power" only adjusts "plugged in" boost behavior.

### ISSUE THREAD

**Issue by iwei20** [seerge/g-helper#252]
**Describe the bug**
Modifying CPU Boost setting in "Fans + Power" only adjusts "plugged in" boost behavior.

**Clear scenario to Reproduce**
1. Click "Fans + Power"
2. Set "CPU Boost" option to Efficient Aggressive

**Expected behavior**
Both "On battery" and "Plugged in" boost settings under "Processor performance boost mode" should be Efficient Aggressive.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11240500/log.txt)

**Screenshots or screencasts**
![image](https://user-images.githubusercontent.com/44007607/232250515-fe13849d-45af-41cb-980f-61e014521b50.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Model: Zephyrus G15 GA503RM

**Asus software**
- MyASUS installed
- ASUS Optimization service running
- No Armoury Crate, extra ASUS services disabled as listed in README

**Comment by iwei20** [comment]
Alternatively, might be a nice feature to be able to control both separately.

**Comment by seerge** [comment]
@iwei20 it's actually intentional :) on battery bios seem to limit power so much that cpu doesn't boost practically :) + you can just disable it for battery permanently if you want to

**Comment by iwei20** [comment]
Huh, that's weird - the method in which I originally found this was when I was on battery and the opposite of this happened. I was trying to disable boost in silent mode, but HWInfo still showed spikes to boost clock numbers, at which point I did the registry edit to show this power option and found this.

**Comment by seerge** [comment]
@iwei20 i can set it to affect both states, it's not a problem - but then it will trigger issues like this one https://github.com/seerge/g-helper/issues/157 :)) (literally opposite with to yours)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11241907/GHelper.zip)
This build will set both DC/AC CPU boost states. But then I need to explicitly explain it in readme probably (even tho no one will read that and will complain) :)
