### ISSUE TITLE
使用求助-屏幕亮度无法调节

### ISSUE THREAD

**Issue by shirogane5687** [seerge/g-helper#2520]
显卡模式调到自动切换之后，有的时候会出现屏幕亮度无法调节的情况，用快捷键也不行，拖动系统调节条也不行。有时候重启一下会恢复正常。请问您知道这种情况出现的原因吗？该如何解决呢？

**Comment by seerge** [comment]
@shirogane5687 checking readme helps

https://github.com/seerge/g-helper/discussions/1042
