### ISSUE TITLE
Vivid visual profile not working

### ISSUE THREAD

**Issue by Pedrwm** [seerge/g-helper#2523]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi there, I have noticed that the Vivid visual profile in G-Helper is not functional, it's practically the same as default mode when you choose it. The issue, however, is solved when using AC, so it's only with G-Helper where this happens.

### How to reproduce the bug?

Change the Visual mode to vivid and there will be no difference between the default and Vivid profiles.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15173293/log.txt)

### Device and Model

ASUS TUF A15 2023 FA507NV

### Additional information.

Tried removing and re-downloading the visual profiles, it didn't work.

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.167.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Pedrwm hello, does it work if you set it in AC?

**Comment by Pedrwm** [comment]
Yes, indeed. It's only like this when using G-Helper.

**Comment by seerge** [comment]
@Pedrwm if it’s indeed working in AC can you do following 


---

1. Download and launch https://learn.microsoft.com/en-us/sysinternals/downloads/procmon 
2. Go to filters in it and add 2 filters as on screenshot (with green checkbox)
![Screenshot 2024-03-06 223624](https://github.com/seerge/g-helper/assets/5920850/41dbf2ef-c32f-4e2c-a7dc-87682251ea5c)
3. Click on [CAPTURE] icon
4. Launch Ac and change Vivid mode there few times
6. Check what Process Monitor captured ?

**Comment by Pedrwm** [comment]
Now that's weird. I re-installed AC just now to follow the steps you mention, and it's also having the same issue.
Guess it's an issue from coding of the new AC update or something then?

**Comment by seerge** [comment]
@Pedrwm GameVisual / Visual modes are handles not by AC or G-Helper but by AsusSplendid utility from Asus System Control Interface driver.

Both apps just launch it under the hood to set mode. It could be that asus has changed something there in recent updates 

If it’s not working in AC as well, it means it obviously won’t work in G-Helper. So i can’t do anything here

Therefor closing this

**Comment by seerge** [comment]
@Pedrwm you can check this topic and try all advises I was giving to a user there

https://github.com/seerge/g-helper/issues/2483

May be one of them will help you
