### ISSUE TITLE
Aura Ready effects for Ghelper

### ISSUE THREAD

**Issue by Covorus** [seerge/g-helper#2529]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I am pretty sure you know what aura ready is, but just in case. Aura ready is a program that comes with AC, which makes your keyboard lights etc responsive to games.

### Describe the solution you'd like

I wonder if it's possible to maintain a low cpu usage with aura ready, but with a quick toggle option, it would be fantastic. As far as i know, that is the only cosmetic thing that Ghelper currently doesn't have.

### Device and Model

Asus rog strix G17 G713PV

**Comment by seerge** [comment]
@Covorus G-Helper already supports all possible backlight modes that your device supports on hardware level and some custom ones (like Ambient or Heatmap)

Aura is a proprietary software done by Asus, it's deeply integrated with AC and can't function without it.

It's impossible to make G-Helper compatible with other proprietary app anyhow.

I was advising you to use openRGB before, if you want to have a bit higher level of customization (for example set per-key backlight)

Thanks
