### ISSUE TITLE
Provides color gamut mode turning off function

### ISSUE THREAD

**Issue by 5kyfkr** [seerge/g-helper#2531]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hello, previously I forcibly disabled Asus's GameVisual and calibrated the screen color with Spyder X colorimeter. However, G-helper also has similar color switching like GameVisual. I hope there is an option to disable color rendering in G-helper as well.

### Describe the solution you'd like

![image](https://github.com/seerge/g-helper/assets/63196026/c38db818-4610-49bd-90cd-0a0465f6117e)
As shown in the picture, add a "Disabled" option.

### Device and Model

Zephyrus M16 GU603ZM

**Comment by seerge** [comment]
@5kyfkr hello

``Visual Modes`` are set by asus own ``AsusSplendid`` utility, as color profiles in the system. Setting mode to "Default" should set settings back to normal using official color profile from asus for your panel (same as it happens with AC).

As far as Default is selected, app will not try to apply anything every time it starts. 

If you are want to use other color profiles you can do the following

- Reset color profiles in Windows Color Management app back to whatever you want
- Check your GPU control panel (i.e. Nvidia control panel or AMD Adrenaline) and reset color settings there. For example just drag some gamma up / down to reset, or select / unselect "color deficiency correction" in AMD Adrenaline
- Uncheck [this setting as explained in FAQ](https://github.com/seerge/g-helper/wiki/FAQ#my-display-colors-seem-off-even-if-i-set-visual-mode-to-default)

If you want to hide Visual Modes from UI you can also do that https://github.com/seerge/g-helper/wiki/Power-user-settings#visual-modes-section

Thanks
