### ISSUE TITLE
Brightness adjustment 

### ISSUE THREAD

**Issue by Reddot911** [seerge/g-helper#2532]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

When uninstalling all the asus bloat we lose this feature. 

### Describe the solution you'd like

For all rog zephyrus duo models, can you please add a brightness adjustment bar for second screen only. Have it under laptop screen hz. Would be awesome. 

Duo community would greatly appreciate it.

### Device and Model

Asus zephyrus duo 16

**Comment by seerge** [comment]
@Reddot911 hello, this is already possible . You can either use your dedicated Screenpad button or ``Fn + Shift + F7 / F8 - Screenpad brightness Down / Up`` as explained in readme

**Comment by Reddot911** [comment]
Oh okay thanks. Any chance of getting a slider so we dont have to use key bindings?

**Comment by seerge** [comment]
@Reddot911 how dod you control that in AC ?

**Comment by Reddot911** [comment]
Screenxpert aka bloat controlled the brightness

**Comment by seerge** [comment]
@Reddot911 so it was a separate application for that ? Not AC ?

I don't see much sense in making things overcomplicated

Currently G-Helper can control main windows brightness with ``Fn + F7 / F8`` and SreenPad with ``Fn + Shift + F7 / F8 ``

You also don't have a slider for main brightness :) but that doesn't create any troubles for anyone

**Comment by Reddot911** [comment]
Just wonder. Thanks loving the app.
