### ISSUE TITLE
Ghelp fails to auto-start on boot with errors.

### ISSUE THREAD

**Issue by NatsuZoraKanata** [seerge/g-helper#2533]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Ghelp fails to auto-start on boot with errors.
When restarting, there are no errors, and Ghelper auto-starts normally. However, after shutting down and then booting up with fast startup enabled, Ghelper fails to auto-start.
2024/5/2 17:55:10: System.ComponentModel.Win32Exception (87): 参数错误(Parameter Error)。
   at GHelper.Display.ScreenInterrogatory.GetAllDevices()+MoveNext() in D:\a\g-helper\g-helper\app\Display\ScreenInterrogatory.cs:line 338
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at GHelper.Display.ScreenNative.FindInternalName(Boolean log) in D:\a\g-helper\g-helper\app\Display\ScreenNative.cs:line 169

### How to reproduce the bug?

1. Shut down the computer with fast startup on
2. Power on

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15186787/log.txt)

### Device and Model

Asus TUF Gaming A15 - FA507XV

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.169.0

### OS

Windows 11 Enterprise 23H2 22635.3566

**Comment by seerge** [comment]
@NatsuZoraKanata try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/15186941/GHelper.zip)

**Comment by seerge** [comment]
@NatsuZoraKanata does it work?

**Comment by NatsuZoraKanata** [comment]
> @NatsuZoraKanata does it work?

After updating to this version, the same error has not occurred so far. If there are still issues in the future, I will reply promptly. Thank you.
