### ISSUE TITLE
Is it possible to add the "Temperature Target' option for the CPU as well?

### ISSUE THREAD

**Issue by SynStark** [seerge/g-helper#2534]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hello,

Is it possible to add that option to the CPU as well? I love how no matter of which profile I'm using I can adjust the max temp I want my GPU to get to, so I think it would be amazing to put that slider in the CPU as well if possible.

Thank you!

### Describe the solution you'd like

Adding Temperature Target slider in the CPU window.

### Device and Model

Scar 18

**Comment by seerge** [comment]
@SynStark hello.

I assume you have Intel device.

It's not possible, as this option has to be implemented and be available on firmware level first (by asus).

You can check Intel Extreme Tuning Utility
https://www.intel.com/content/www/us/en/download/17881/intel-extreme-tuning-utility-intel-xtu.html

May be that one can offer you something

Thanks
