### ISSUE TITLE
幻14 air无法调整键盘灯颜色，设置颜色无效

### ISSUE THREAD

**Issue by qh3001** [seerge/g-helper#2535]
幻14 air无法调整键盘灯颜色，设置颜色无效，如图我设置红色，但是键盘还是之前用奥创设置的蓝色（奥创现在已经被我卸载）
请问是需要其他软件支持么，还是我哪里设置错误了，谢谢。
![无标题](https://github.com/seerge/g-helper/assets/29654197/b850a219-e516-42a4-836e-aa96feddecdd)

**Comment by seerge** [comment]
https://github.com/seerge/g-helper/wiki/FAQ#backlight-doesnt-change-color-or-stays-blue
