### ISSUE TITLE
Key Bindings Feature Request

### ISSUE THREAD

**Issue by XynoCrest** [seerge/g-helper#2538]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

- In the extras menu, can you please make it so that Sleep is one of the remappable options available in the dropdown for the key bindings. 

(I would like to remap FN + C to sleep, as I never use FN lock, and I put my laptop to sleep quite often, and the default keybinding FN + F11 requires the use of two hands, while FN + C would be a much more handy keybinding that I can trigger with one hand and by on my way!)

- I would also love it if there was an option to remap FN+F2 and FN+F3 from keyboard brightness up and down to screen brightness up and down respectively and vice versa, as most people with the white model would end up changing screen brightness way more often than keyboard brightness which I have permanently turned off, so those keys pretty much do nothing right now, and again having a one handed shortcut would be much more productive as I wouldn't have to take my hand off from my mouse just to change the screen brightness. 

Thank you!

### Device and Model

ROG Zephyrus G15 GA503RM

**Comment by seerge** [comment]
@XynoCrest hello,

You can already bind ``Fn+C`` to Sleep. You need to set ``0x5F`` to Custom binding. It's a sleep key according to https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes as explained in [Power User settings ](https://github.com/seerge/g-helper/wiki/Power-user-settings)

As for other keys, I don't plan to overcomplicate UI and make extra bindings there.

You can already change brightness with ``Fn+F7/F8`` and with ``Ctrl + M1 / M2``

Thanks

**Comment by XynoCrest** [comment]
Umm... setting it to `0x5F` doesn't seem to be working for me (also tried restarting the laptop) - 
![image](https://github.com/seerge/g-helper/assets/140979619/a8288708-537b-4d7d-8599-601754db5d14)

**Comment by seerge** [comment]
@XynoCrest you can also try Screen toggle option from the list, as it also (by fact) turns off screen and puts laptop to sleep eventually.
