### ISSUE TITLE
FN-Lock doesn't affect arrow keys

### ISSUE THREAD

**Issue by Velgus** [seerge/g-helper#2539]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hello, I'm not 100% sure this is a bug, but FN-Lock does not affect the arrow keys on my 2024 Zephyrus G14. They're mapped to PgUp, PgDown, Home, and End when the FN key is pushed.

### How to reproduce the bug?

1. Enable FN-Lock
2. Attempt to use arrow keys for PgUp, PgDown, Home, or End, without holding FN down.

### Logs

Not really relevant, but clearing the log then doing the steps to reproduce simply output:
```
5/3/2024 12:17:19 AM: Key: 56
5/3/2024 12:17:19 AM: ATNA40CU05-0  HDR: False 10 1 False
5/3/2024 12:17:41 AM: Key: 56
```

### Device and Model

Asus Zephyrus G14 GA403

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.170

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Velgus hello,

Fn-Lock is not supposed to affect those keys :) It affects only F-keys by design.

And I honestly don't want to change that behavior as it can cause much more trouble and confusion than good.

Sorry. Thanks.
