### ISSUE TITLE
Future Feature - Support desktop boards

### ISSUE THREAD

**Issue by jakenuts** [seerge/g-helper#2541]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

As one of a growing community of people who opted for an Asus motherboard - and then learned it wanted to kill my i9 chip and bury all utilities in a "Crate of Bloated UI Experiments" I'd heartily welcome an OS tool that did anything at all for my Strix z790-i Gaming board. Even just a temperature gauge or something would be great as I have no visibility into my new PC's very unstable foundation.

### Describe the solution you'd like

1. Provide minimal support for non-laptop boards
2. Temperature, speed gauges 
3. Anything that can be easily ported over

### Device and Model

Asus Rog Strix Z790-i WIFI Gaming Whatever

**Comment by seerge** [comment]
@jakenuts hello,

Armoury Crate for desktops and for laptops are de-facto 2 separate and very different applications under same name umbrella.

G-Helper is built around existing and known interface to control laptops, cause it's (almost) same for all mobile asus devices (including Rog Ally). 

I have no idea how desktop controls work and don't have any desktop asus devices. But I suspect it's absolutely different from what is done for laptops, as desktop is not a single component but rather a full zoo of different elements.

So sorry, but I don't have neither time nor resources for that.

You can use existing tools like https://getfancontrol.com/ for fans, HWinfo for sensors and OpenRGB for backlight.

Thanks.

**Comment by seba2282** [comment]
Someone know, who make that type project but for desktops PCs?
