### ISSUE TITLE
Switching custom windows powerplan

### ISSUE THREAD

**Issue by Retr0680** [seerge/g-helper#2545]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

i followed the instruction for power user settings where i have changed the "scheme_1" for ultimate performance power plan. i saved the file restarted ghelper but whenever i clicked on turbo the power scheme is still on high performance when it's not supposed to be there.

### How to reproduce the bug?

1. edit the config file for power settings
2. these where the lines i added: ```"scheme_0": "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c",
  "scheme_1": "e9a42b02-d5df-448d-aa00-03f14749eb61",
  "scheme_2": "381b4222-f694-41f0-9685-ff5bb260df2e"```
3. here is the config file itself: 
[config.json](https://github.com/seerge/g-helper/files/15210539/config.json)

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15210537/log.txt)

### Device and Model

Asus TUF Gaming A15 FA506QM

### Armoury Crate

Never installed

### Asus Services

None

### Version

0.170.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Retr0680 hello, I think that Ultimate Performance plan is simply not present on your system at all

From the log

```
5/4/2024 11:28:24 PM: Power Plan 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c:OK   <---  High Performance Is accepted
5/4/2024 11:28:29 PM: Power Plan e9a42b02-d5df-448d-aa00-03f14749eb61:50   <--- Ultimate Performance returns "50" (whatever it means, but clearly not OK)
```

So just use ``8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c`` , I think it's quite similar (after all in modern windows power plans are almost obsolete and are substituted with power modes instead)

**Comment by Retr0680** [comment]
@seerge whenever I use ghelper the ultimate performance plan just disappears even when I import it. It's like there for a second when I import and then it just completely vanishes

**Comment by seerge** [comment]
@Retr0680 can you set this Ultimate power plan manually using powercfg ?

**Comment by Retr0680** [comment]
> @Retr0680 can you set this Ultimate power plan manually using powercfg ? 

Yes but as I mentioned earlier it vanishes the moment I start ghelper

**Comment by seerge** [comment]
@Retr0680 well, I don't know how to help you here

Sause G-Helper just uses official windows API to set active power plans 
https://learn.microsoft.com/en-us/windows/win32/api/powrprof/nf-powrprof-setactivepwrscheme

https://github.com/seerge/g-helper/blob/8f2a13b1adea1a2fc0ee5cd8831e3a5c0d4e1d26/app/Mode/PowerNative.cs#L51C30-L51C50

And 50 is what this call returns (it's some error code). 

It looks like it's https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-
```
ERROR_NOT_SUPPORTED
50 (0x32)
```

Can you try to run app as admin ? May be that will change something ?

**Comment by seerge** [comment]
@Retr0680 what does running 
```
powercfg /s e9a42b02-d5df-448d-aa00-03f14749eb61
```

return to you ? cause for me i get

```
Attempted to write to unsupported setting
```

while

```
powercfg /s 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c
``` 
works fine

**Comment by seerge** [comment]
@Retr0680 check this topic for more info
Check this topic for more info https://superuser.com/questions/1716969/set-the-ultimate-performance-power-plan-on-windows-11 

You need to run ``powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61``
Then note GUID of new (duplicate) plan and use it (also in g-helper's config)

**Comment by Retr0680** [comment]
@seerge nah it's still the same

**Comment by seerge** [comment]
@Retr0680 did you use a NEW (duplicate) plan GUID ? For me it worked (while ``e9a42b02-d5df-448d-aa00-03f14749eb61`` was also returning error 50)

Post a log please

**Comment by Retr0680** [comment]
[log.txt](https://github.com/seerge/g-helper/files/15210695/log.txt)
i tried to import the armoury crate turbo powerplan that i had exported before reinstalling windows. I imported that power plan it showed me this:
![image](https://github.com/seerge/g-helper/assets/82796288/78f65881-98d4-4ca9-bedc-52898bd35f02)
 i changed the config file value for turbo to this guid it still didn't work.

**Comment by seerge** [comment]
@Retr0680 in your log, i see that you use original (old) plan GUID.

You need to set a **NEW GUID** in a ``config.json`` as I have mentioned above (i.e. 61af5de7-.....)
```
"scheme_1": "<YOUR NEW GUID HERE>", 
```

**Comment by Retr0680** [comment]
@seerge can you check if there's anything wrong with the config file?
[config.json](https://github.com/seerge/g-helper/files/15210728/config.json)

**Comment by seerge** [comment]
@Retr0680 it looks ok, assuming you want to use imported AC's Turbo plan (``dd617866-3401-4edd-954c-a986e727f7fe``)

But that plan was not present in your log :)

**Comment by Retr0680** [comment]
i changed the guid in the config multiple times the log is still showing the old guid

**Comment by seerge** [comment]
@Retr0680 you need to quit app, edit config (save it), and start app again.

**Comment by Retr0680** [comment]
@seerge how many commas are supposed to be there in the config i uploaded a few minutes ago?

**Comment by seerge** [comment]
@Retr0680 your config is fine. If you would break json structure, app won't be able to read it at all.

**Comment by Retr0680** [comment]
it's working now, the ultimate performance is there now. thanks for your help! 😊

**Comment by seerge** [comment]
@Retr0680 great
