### ISSUE TITLE
Different Keyboard Backlight for when the built-in screen is off

### ISSUE THREAD

**Issue by Razerlight** [seerge/g-helper#2546]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I just found out that when i connect an external monitor to my G14 (2024) the backlight of the keyboard in ambient mode still changes the colors. Its a little weird and i am a bit worry that the constant changing while gaming docked will be an issue.

### Describe the solution you'd like

A possible option to enable that the keyboard rgb is off while the built-in screen is off

### Describe alternatives you've considered

I considred linking the keyboard rgb to the performance modes so when running on battery (silent) i can have ambient while watching movie and so on. And when i go to my dock and want to game (balanced) i can turn off the keyboard rgb.

Problem is that when i rarely want to game on laptop screen itself then i would have the same problem with ambient mode.

### Device and Model

Asus Zephyrus G14 2024

### Additional information.

BTW: great app from yours. One of the main reasons i will keep the laptop and what sets it apart of the competition. I am an IT Sysadmin so i love the controls it gives me.

**Comment by seerge** [comment]
@Razerlight hello, I don't see point in stopping Ambient color calculation when external monitor is on :)  Cause it could be that you use your device keyboard along with that monitor too. Or you don't use keyboard, but still want your laptop to reflect screen color.

If you want to disable it completely, just set different backlight setting in the app.

I also don't plan to link backlight settings to modes, as modes are only about performance.

Sorry. Thanks.
