### ISSUE TITLE
GPU is cutting power at 100% usage, dropping clocks drastically. But thermals are fine.

### ISSUE THREAD

**Issue by kabbage0314** [seerge/g-helper#2547]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Every game I launch and play ends up having a weird reaction as seems to be jumping around deciding whether it wants to use the GPU. The GPU clocks will jump around normally and then drop to under 500 mHz even though the GPU is at 100% usage, not thermal throttling. The power to the GPU was also cut and this happened only after I updated to g-helper version 0.165.0. If I can get some insight and possible fixes that would be greatly appreciated. 

### How to reproduce the bug?

Might only be a bug on my computer. So I don't really know how you can reproduce it. 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15211253/log.txt)

### Device and Model

ASUS Zephyrus M16 GU603ZW

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.170.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@kabbage0314 hello,

G-Helper [does not run your hardware in realtime anyhow](https://github.com/seerge/g-helper?tab=readme-ov-file#-important-notice) and not lowering your clocks :)

It's either some strange Nvidia driver behavior, that you can try to fix by doing a clean driver install as [explained in Troubleshooting](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers) or some other unknown specifics of your system.

On a side note I have noticed that you are setting very low CPU power limits (15W)
```
5/4/2024 4:36:34 PM: PowerLimit A3 = 15 : OK
5/4/2024 4:36:34 PM: PowerLimit A0 = 20 : OK
```

I'm not sure what you are trying to achieve, but it's definitely restricts your performance in games. I would either reset them to defaults or set something like 40W. 

Besides that I can't help anyhow, as this is not related to the app or 0.165 or so :) You can always download older version to check.

Good luck figuring things out. Thanks.
