### ISSUE TITLE
Keyboard RGB not working on ASUS TUF FX505-DT

### ISSUE THREAD

**Issue by ujjwalkirorimal** [seerge/g-helper#255]
**Describe the bug**
Control of keyboard RGB lights using g-helper isn't working at all.

**Clear scenario to Reproduce**
1. Go to Laptop Keyboard option
2. Try selecting various modes like static/breathing/color cycle/strobe
3. Try adjusting color
4. Nothing happens

**Expected behavior**
RGB control should work as intended

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11241291/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Laptop model - Asus TUF FX505-DT

**Asus software**
- Armoury crate (or it's services installed)
- MyASUS isn't installed
- Other Asus services running in background

**Additional context**
OpenRGB stable version doesn't work but experimental version controls the RGB fine.
Output of endpoint discovery script :
[output.txt](https://github.com/seerge/g-helper/files/11241362/output.txt)

**Comment by seerge** [comment]
@ujjwalkirorimal hello
In your log I see that bios responds with 0 to keyboard payload (i.e. it's not supported?). It's not much I can do here then :) 

```
16-04-2023 10.51.17 AM: TUF RGB = 01-00-FF-00-00-EB-00-00-00-00-00-00 : 0
16-04-2023 10.51.20 AM: TUF RGB = 01-01-FF-00-00-EB-00-00-00-00-00-00 : 0
16-04-2023 10.51.21 AM: TUF RGB = 01-02-FF-00-00-EB-00-00-00-00-00-00 : 0
16-04-2023 10.51.22 AM: TUF RGB = 01-0A-FF-00-00-EB-00-00-00-00-00-00 : 0
```

**Comment by ujjwalkirorimal** [comment]
> @ujjwalkirorimal hello In your log I see that bios responds with 0 to keyboard payload (i.e. it's not supported?). It's not much I can do here then :)
> 
> ```
> 16-04-2023 10.51.17 AM: TUF RGB = 01-00-FF-00-00-EB-00-00-00-00-00-00 : 0
> 16-04-2023 10.51.20 AM: TUF RGB = 01-01-FF-00-00-EB-00-00-00-00-00-00 : 0
> 16-04-2023 10.51.21 AM: TUF RGB = 01-02-FF-00-00-EB-00-00-00-00-00-00 : 0
> 16-04-2023 10.51.22 AM: TUF RGB = 01-0A-FF-00-00-EB-00-00-00-00-00-00 : 0
> ```

But since openRGB's experimental branch is working, can't you use their implementation or something? I can provide you any other log/information required if possible.

**Comment by seerge** [comment]
@ujjwalkirorimal I use their implementation for TUF models exactly :) (as it works for other tuf models)
it could be that your model actually works with ROG type of protocol, not TUF, can you post your keyboard USB device / vendor IDs?

**Comment by ujjwalkirorimal** [comment]
> @ujjwalkirorimal I use their implementation for TUF models exactly :) (as it works for other tuf models) it could be that your model actually works with ROG type of protocol, not TUF, can you post your keyboard USB device / vendor IDs?

It shows up as ASUS TUF Keyboard in OpenRGB

![image](https://user-images.githubusercontent.com/38243573/232306002-6d5599d0-9563-42e0-b5de-385446073d5f.png)

I am talking about internal laptop keyboard here, device manager show two entries for keyboards so here are their hardware ID's
![image](https://user-images.githubusercontent.com/38243573/232306909-b63b2ba1-5510-419c-aeba-e254bf7d60b6.png)
![image](https://user-images.githubusercontent.com/38243573/232306967-fa0ea828-3548-4b55-8e61-a43dd060cdf0.png)

**Comment by seerge** [comment]
@ujjwalkirorimal if it's WMI - then you can just download app sources, and try to play with payload. For me it's almost impossible to debug what happens on your side :|

**Comment by seerge** [comment]
If you go to Keyboard -> Extra and check/uncheck "Awake" checkbox, does your backlit turn ON/OFF with it ?

**Comment by ujjwalkirorimal** [comment]
> If you go to Keyboard -> Extra and check/uncheck "Awake" checkbox, does your backlit turn ON/OFF with it ?

Yes that option is working fine

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11242159/GHelper.zip)
I have changed 1 byte in payload, can you try if it changes something ? 

Alternatively - this is how openRGB generates payload https://gitlab.com/CalcProgrammer1/OpenRGB/-/blame/master/Controllers/AsusTUFLaptopController/AsusTUFLaptopController.cpp#L22

This is g-helper 
https://github.com/seerge/g-helper/blob/main/app/ASUSWmi.cs#L263

It's a sequence of 6 bytes 
```
(save_val) + (mode) +  (red)  +  (green) + (blue) + (speed);
```

**Comment by ujjwalkirorimal** [comment]
> [GHelper.zip](https://github.com/seerge/g-helper/files/11242159/GHelper.zip) I have changed 1 byte in payload, can you try if it changes something ?
> 
> Alternatively - this is how openRGB generates payload https://gitlab.com/CalcProgrammer1/OpenRGB/-/blame/master/Controllers/AsusTUFLaptopController/AsusTUFLaptopController.cpp#L22
> 
> This is g-helper https://github.com/seerge/g-helper/blob/main/app/ASUSWmi.cs#L263
> 
> It's a sequence of 6 bytes
> 
> ```
> (save_val) + (mode) +  (red)  +  (green) + (blue) + (speed);
> ```

Yeah thanks man this build is controlling all RGB functions fine ^.^

**Comment by seerge** [comment]
Great, I have updated 0.53 with this fix as well.
