### ISSUE TITLE
GPU fan speed is always at 100%

### ISSUE THREAD

**Issue by Drew-Shunin** [seerge/g-helper#2550]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

GPU fan is always at 100% in the g-helper interface
Temps looks ok.

At load 
![image](https://github.com/seerge/g-helper/assets/75254296/3c04d410-bf00-44b7-81aa-1092eaca0e58)
At Idle
![image](https://github.com/seerge/g-helper/assets/75254296/b42a95b9-e5bb-4c8f-aead-a6373b359a60)

Updates are installed
![image](https://github.com/seerge/g-helper/assets/75254296/bba988e9-0365-4e06-86eb-a5c4589f4c05)

### How to reproduce the bug?

Open g-helper

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15213773/log.txt)

### Device and Model

Asus Zephyrus G16 2025 GU605MI

### Additional information.

Please let me know if you need some additional information

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.170.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Drew-Shunin hello,

G-Helper is not controlling your fans in realtime anyhow, they are controlled by BIOS ([check FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds))

I see that you use default Silent mode w/o any custom fan curves (which is fine). You can try to switch other modes, or reboot. May be BIOS will calm down then.

You can also try to set a custom fan curve, less aggressive.

And finally - If you really want to have more precise control over fan curves you can try [Experimental build with manual fan control](https://github.com/seerge/g-helper/discussions/2272).

Thanks.

**Comment by seerge** [comment]
@Drew-Shunin P.S. If it's stuch by some reason (or BIOS is bugged) you can try [hardware reset as explained in Troubleshooting](https://github.com/seerge/g-helper/wiki/Troubleshooting#hardware-reset--cmos-reset)

**Comment by Drew-Shunin** [comment]
Hello,
My request was not about speed of the GPU fan itself but about the fact that g-helper displays speed incorrectly. On the silent mode the fan is idling (0 rpm or somewhere close to it) but g-helper displays it at 100% all the time. 
Sorry if initial request is misleading in some way.
Thanks.

**Comment by seerge** [comment]
@Drew-Shunin G-Helper takes fan speed from BIOS / Asus Control interface endpoints.

What would AC show in same situation ?

**Comment by seerge** [comment]
@Drew-Shunin you can run following command in powershell as admin

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DSTS -Arguments @{Device_ID=0x00110014}
```

It should output GPU fan speed + 65536

**Comment by Drew-Shunin** [comment]
![image](https://github.com/seerge/g-helper/assets/75254296/ad9c350f-55e3-49d4-b37d-59eca0f4f19f)

**Comment by seerge** [comment]
@Drew-Shunin exactly, if you deduct 65536 - you will get 74 (00) RPM

You either have broken sensor (or bugged BIOS), try hardware reset as I suggested above

**Comment by Drew-Shunin** [comment]
Looks like hardware resed does nothing. Let hope that bios updates fix that in the future. Anyway, thanks a lot for the support and the g-helper. Great tool!

**Comment by seerge** [comment]
@Drew-Shunin try to check what AC reports (out of curiosity). Most probably it will be same tho. 

As both apps just get that value you had in powershell and display it.

**Comment by Drew-Shunin** [comment]
You are right. 7400 in the AC as well

![image](https://github.com/seerge/g-helper/assets/75254296/73400cc5-045e-4edc-bf22-d0f49a7a493d)

**Comment by seerge** [comment]
@Drew-Shunin well, looks like sensor is constantly reporting same value :(
