### ISSUE TITLE
Boot sound checkbox

### ISSUE THREAD

**Issue by horvatkm** [seerge/g-helper#2555]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi,
I've noticed small issue related to Boot sound checkbox in Extra Settings. After closing and reopening Extra Settings dialog, the checkbox is always off, no matter whether it was checked or not previously. But still, the checkbox kind of works. To turn boot sound on, I've to check it once. To turn boot sound off, I've to check it twice.

In Ghelper.log a new message is added each time I click the Boot Sound checkbox.

5/6/2024 4:39:43 PM: BootSound = 1 : OK
5/6/2024 4:39:44 PM: BootSound = 0 : OK

When opening Extra Settings dialog, a bit strange message is being logged into Ghelper.log regarding missing atiadlxx.dll, since my laptop has NVidia GPU.
5/6/2024 4:39:55 PM: Cores: 0x0806
5/6/2024 4:39:55 PM: CoresMax: 0x0806
5/6/2024 4:39:55 PM: Unable to load DLL 'atiadlxx.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
5/6/2024 4:39:55 PM: Hibernate after 420

### How to reproduce the bug?

1. Open Extra Settings
2. Check Boot Sound
3. Close Extra Settings
4. Open Extra Settings and see that Boot sound is unchecked, even though it was checked before closing

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15222322/log.txt)

### Device and Model

ASUS TUF Gaming F15 FX507ZV4

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.165

### OS

Windows 10 21H2

**Comment by seerge** [comment]
@horvatkm hello,

Currently app reads status of the boot sound from corresponding endpoint in asus driver / firmware every time you open ``Extra``. It's intentional, so app always show actual status. 

If checkbox is unchecked (i.e. OFF) every time you open it, it means that by some reason firmware reports it as OFF . It could be simply bugged firmware on your specific model.

You can try to run following command in powershell as admin , it should output checkbox status + 65536 (so 6553**6** for OFF and 6553**7** for ON)

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DSTS -Arguments @{Device_ID= 0x00130022;}
```

Does checkbox change status if you would reboot ?

--

> When opening Extra Settings dialog, a bit strange message is being logged into Ghelper.log regarding missing atiadlxx.dll, since my laptop has NVidia GPU.

This is unrelated :) ``Extra`` settings also has a checkbox for AMD Varibright setting, so app checks if you have AMD card for that. And just logs the fact that it's not . So it's normal.

**Comment by horvatkm** [comment]
Checkbox doesn't change status after reboot, it's still off.

The command "Invoke-CimMethod (Get-CimIn ... " is always returning value  4294967294, which is FFFFFFFE in hex.

```
PS C:\Windows\system32> Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DSTS -Arguments @{Device_ID= 0x00130022;}

device_status ReturnValue PSComputerName
------------- ----------- --------------
   4294967294        True

```

**Comment by seerge** [comment]
@horvatkm ah, ``FFFFFFFE`` explains it. So in your case it seem to report nothing. 

So unfortunately it's not possible to show actual state of the Boost Sound flag.

**Comment by horvatkm** [comment]
I don't mind not seeing actual state of the Boost Sound flag. I'm just reporting an issue I've encountered, so that others are not confused by strange sound, which laptop makes on boot, even though Boost Sound checkbox indicates, that it's disabled. Like I was for a while.

I guess there are a few ways how to deal with this issue.
- since setting the value works fine, maybe Extra dialog could show two buttons instead of checkbox when querying AsusACPI.BootSound returns 0xFFFFFFFE 
- or you could simply document the issue in FAQ

Thanks for great app and quick response.

**Comment by horvatkm** [comment]
Thanks, works perfectly.
