### ISSUE TITLE
Variable refresh rate (VRR)

### ISSUE THREAD

**Issue by doubledimensions** [seerge/g-helper#2557]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Intel ARC got the G16 2024 enabled with VRR, however this is not available yet from windows settings and G-Helper, wondering if this is something can be added to G-Helper? 

![image](https://github.com/seerge/g-helper/assets/49115293/2f979b7a-fd4c-4eb7-a6d7-af1949632203)

### Describe the solution you'd like

Under the laptop screen refresh rate can have a toggle to turn VRR on/off

### Device and Model

ROG Zephyrus G16 GU605MV_GU605MV

**Comment by seerge** [comment]
@doubledimensions hello,

G-Helper uses windows API when gives you access to refresh rate shortcuts in the UI. So unfortunately it's not possible to add it w/o full support on windows side.

If you want to keep VRR setting from Intel Arc app, just make sure **not to select Auto**  in G-Helper, and it won't try to change refresh rate.

Thanks.
