### ISSUE TITLE
The fan only recognizes the lowest speed

### ISSUE THREAD

**Issue by Skadino** [seerge/g-helper#2559]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![屏幕截图 2024-05-07 132839](https://github.com/seerge/g-helper/assets/57399604/a1f18b88-aa38-499a-8ab9-b2656561d150)
The fan only recognizes the lowest speed
![屏幕截图 2024-05-07 133100](https://github.com/seerge/g-helper/assets/57399604/99182031-fce1-483c-bec7-588347677ff3)

### How to reproduce the bug?

When the GPU temperature gets higher than 80 degrees, it still only recognizes the lowest speed

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15230175/log.txt)

### Device and Model

Zephyrus M16 GU603HM 2021

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.170

**Comment by seerge** [comment]
@Skadino hello, 

G-Helper (and AC) doesn't control your fans in realtime anyhow, they are controlled by BIOS. [Please check FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)

The fan curve that you have selected is set
```
2024/5/7 13:31:17: FanCPU = 1E-32-36-3B-41-4A-55-64-00-16-2A-3D-50-5D-64-64 : OK
2024/5/7 13:31:17: FanGPU = 1D-25-2B-30-37-3E-46-64-29-41-50-5A-61-62-64-64 : OK
```

If you are not happy how the BIOS controls fans on your device. You can always try [Experimental build with manual fan control](https://github.com/seerge/g-helper/discussions/2272)

Thanks.
