### ISSUE TITLE
ROG STRIX G15 G512LV: One Laptop LightZone is not lighting up (Left Side)

### ISSUE THREAD

**Issue by Crusiege** [seerge/g-helper#2560]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The left side of Laptop Light Zones are not turning on (It is enabled in extra settings). The front and right ones are only working. Tried installing AC to see if it was a hardware issue but then all 3 were working, Reverting back to G-Helper reproduced the issue.

### How to reproduce the bug?

1. Uninstall AC   2. Install G-Helper   3. Apply any light effect (Rainbow in my case)   4. Only 2 Sides are working, left one not lighting up for Laptop Light Zones.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15231361/log.txt)

### Device and Model

Asus ROG Strix G15 G512LV

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.170

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Crusiege hello,

I'm afraid you have a very old device, and way the RGB is set here may be different from all other modern models.

Can you check if https://openrgb.org/ is able to set backlight for your device ?

Also what exactly do you understand under "left" light zone ? Left part of keyboard keys ? As G-Helper doesn't have any separate settings for left and right ...

Thanks.

**Comment by Crusiege** [comment]
I did check OpenRGB and when using that only the keyboard is lighting up. The None of the Laptop Light Zone is lighting up.
From Left lightzone, what I mean is there is an underglow strip under my laptop which is common for ROG laptops, its just a strip attached to the bottom of the laptop on all 3 sides except the back. And the one on the left is not lighting up when G-Helper is controlling the RGB but when using Armoury Crate, all are lighting up. When using OpenRGB none is lighting up. I will upload a picture showing what I mean, in it I have labelled the front and right side of the Light Zones, for me only front and right ones are lighting up and the left one is not lighting up while using G-Helper.
![csm_3-4-scaled-e1585829325535_06_b35d7baae8](https://github.com/seerge/g-helper/assets/101250104/702b403a-02a4-4251-a58d-a91414688b76)

**Comment by seerge** [comment]
@Crusiege ok!

Looks like Logo flag on your device is responsible left Lightbar by some reason.

I'm not a big fan of changing the logic here, as it may break things for other models.

So if that's ok, I would advice to keep it as is. Just keep that checked.

Thanks and closing as resolved :)
