### ISSUE TITLE
Proble with Visual modes

### ISSUE THREAD

**Issue by Diego-JRH** [seerge/g-helper#2562]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I recently had a mayor windows update. Before everything was fine but now Visual Mode says it is unavaliable due to HDR being activated but my laptop screen doesn't support HDR, only HDR streaming, If I click on the text, the usual UI reappears but disappears again when closing the main G-Helper window. 
I'll also mention here a small UI bug that I have been seeing for some time now. The "240Hz + Overdrive" is partially hidden so the last "e" is cut.
In the screenshot below both bugs can be seen.

![image](https://github.com/seerge/g-helper/assets/18351723/dd649529-975c-4dd3-a636-88fd9871679a)

### How to reproduce the bug?

1. Mayor windows update
2. Open G-Helper
3. Visual modes options are gone

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15241144/log.txt)

### Device and Model

Asus ROG Strix SCAR 18 G834JY

### Armoury Crate

Uninstalled

### Asus Services

None

### OS

Windows 11 Pro 23H2

**Comment by Diego-JRH** [comment]
Oh, it was that setting, it turned itself on with the update. Thanks, now it's working fine as before.

**Comment by seerge** [comment]
@Diego-JRH great

As for label being to long, it's due to such translation in Spanish

As a native speaker, feel free to edit too long translations on Crowdin
https://crowdin.com/editor/g-helper/7/en-es?view=comfortable&filter=basic&value=0#q=pantalla

They will automatically update to repository and be changed in next release then

Closing as resolved then
