### ISSUE TITLE
Matrix brightness toast wrongly displayed on laptop without matrix

### ISSUE THREAD

**Issue by wpcwzy** [seerge/g-helper#2563]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Matrix brightness toast wrongly displayed on laptop without matrix when pressing hotkeys `Shift + M1/M2` , which is confusing since you can not tell the "Dim" on the toast indicates the brightness of keyboard backlight or the matrix backlight.
![image](https://github.com/seerge/g-helper/assets/16263217/010ea6cf-b476-45a7-a595-48ddfe1f221d)
What's more, ``Fn + Shift + F7 / F8`` also triggers this toast on laptop without matrix, which seems a little weird.

### How to reproduce the bug?

1. Launch G-Helper without setting `skip_hotkeys` to `1`
2. Press `Shift + M1 / M2` and you will see the toast displayed.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15245653/log.txt)

### Device and Model

ROG Zephyrus M16 GU604VI

### Additional information.

The description 

> ``Shift + M1 / M2`` - Backlight brightness Down / Up

in README.md might also need to be changed since it's hard to tell which "backlight" it refers to. In my case, it didn't change my keyboard backlight and left me confused.

### Armoury Crate

Installed

### Asus Services

None

### Version

0.170.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@wpcwzy hello,

``Shift + M1 / M2`` changes (keyboard) backlight brightness. It has absolutely nothing to do with anime matrix. There is only one backlight on the device.

So everything is correct and as it should be.

If you refer to anime matrix, it's not backlight at all.

**Comment by wpcwzy** [comment]
Thank you for your prompt reply! 
In my situation, the toast displayed but keyboard backlight isn't changed. In addition, I looked up the text displayed in toast and found it in `String.zh-CN.resx`, which has the name `MatrixDim` so I assume this function relates to anime matrix. I'm still a little confused about this.
I've attached a short video showing `Shift + M1 / M2` displays the toast but not changing my keyboard backlight.
https://github.com/seerge/g-helper/assets/16263217/34245457-5e20-4c62-baec-5b5cac261275
Sorry for my poor grammar!

**Comment by seerge** [comment]
@wpcwzy what do M1/M2 keys do on your device by default ? It should be volume controls.

If it's not the case - did you rebind them BEFORE using Armoury Crate to some other function ?

**Comment by wpcwzy** [comment]
> @wpcwzy what do M1/M2 keys do on your device by default ? It should be volume controls.
> 
> If it's not the case - did you rebind them BEFORE using Armoury Crate to some other function ?

By default, M1/M2 keys are volume controls

I've never rebinded any keys using Armoury Crate. I once rebinded M1/M2 to screen brightness control using G-Helper.

Another werid thing I just found is that I cannot change my M1/M2 back to volume controls using G-Helper, and it keeps adjusting my screen brightness even I bind M1/M2 back to volume control in G-Helper. All other key rebindings work fine in G-Helper.

Should I follow some manuals to reset all my settings? Or should I upload my latest log?

**Comment by wpcwzy** [comment]
Sorry, my bad!

I did once change the key bindings in AC and forgot that after a long time not using it. I just restarted ASUS services and went to AC to check it, and that's the cause of my issue. After rebinding M1/M2 to volume controls, my problem solved and `Shift + M1 / M2` works great on my laptop.

Thanks so much for all your efforts in developing such a wonderful software!

**Comment by seerge** [comment]
@wpcwzy your ``M1/M2`` buttons were emitting ``FN+F7/F8`` on hardware level (due to bindings done in AC), therefore when you hold shift app was acting accordingly.

**Comment by wpcwzy** [comment]
> @wpcwzy your `M1/M2` buttons were emitting `FN+F7/F8` on hardware level (due to bindings done in AC), therefore when you hold shift app was acting accordingly.

Thanks for your explanation!

Since `M1/M2` buttons were emitting `FN+F7/F8` by hardware, then my `Shift + M1 / M2` hotkey is equal to

> `Fn + Shift + F7 / F8` - Matrix / Slash Lighting brightness Down / Up

Thus all the "strange" behaviors happened on my laptop make sense now. XD

Again, thank you for your effort on this project!
