### ISSUE TITLE
True Burn software installed

### ISSUE THREAD

**Issue by cmlkirk89** [seerge/g-helper#2567]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Since installing ghelper, when I boot into my Asus Flow Z13, I get a popup for True Burn and CMD. I want to confirm this is expected behavior for the Ghelper application and not somehow unwanted software on my system.

### How to reproduce the bug?

I don't currently see True Burn on my system software list

### Logs

I don't have logs associated.

### Device and Model

ASUS Flow Z13

### Armoury Crate

Uninstalled

### Version

Current release

### OS

Windows 11

**Comment by seerge** [comment]
@cmlkirk89 what are you talking about? 

What is "true burn" ?
G-Helper doesn't install anything in your system.

Thanks.
