### ISSUE TITLE
Custom key binding not work :(

### ISSUE THREAD

**Issue by Pewful2021** [seerge/g-helper#2568]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Helo again 
so uhh i got a monitor and i just put my laptop vertically with the screen closed 
so its kinda not simple anymore to open G helper 
so i tried the keybinding in the sottings and i dint work :(
i tried everything  

### How to reproduce the bug?

1. go to settings 
2. set em keybindings
3. no work :(

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15269980/log.txt)

### Device and Model

Asus TUF dash F15 FX516PE

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.170.0

### OS

Windows 10 22H2

**Comment by seerge** [comment]
@Pewful2021 hello, I didn't completely get what you mean.

- What kind of keybindings are not working ? 
- How do you even press them with screen closed ?

**Comment by Pewful2021** [comment]
Keybindings in the setting section
Using an external keyboard

**Comment by seerge** [comment]
@Pewful2021 what is "setting section" specifically ?

**Comment by Pewful2021** [comment]
Well I know I can press that combination to open G helper but why can't I set any other keybindings to open the app
Also I have tried it with other actions still no work

https://github.com/seerge/g-helper/assets/147270429/c528293b-a083-4077-9bda-64c66a0672f7

**Comment by seerge** [comment]
@Pewful2021 hello. 

``FN + <something>`` keybindings are for internal keyboard laptop only, they use proprietary keycodes from asus :) They obviously won't work on 3rd party keyboard.

Please check for a full list of universal (working on all input devices) keybindings in readme 
https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings

Thanks.

**Comment by Kaliyuga03** [comment]
<img width="756" height="429" alt="Image" src="https://github.com/user-attachments/assets/a28584f1-666e-4d64-ae79-faae9473bd78" />

@seerge I’ve experienced a similar issue. I recently bought a brand new ROG Strix G16 (2023 model) about a month ago. After facing multiple crashes with Armoury Crate, I uninstalled it and switched to G-Helper, which has been a lifesaver—everything works great now.

However, I’m having trouble with the key bindings for the M1–M5 keys. The custom functions I assigned to them aren’t working. M1, M3, and M5 just control the volume (increase/decrease), while M2 and M4 mute/unmute the microphone—even when I try using them with Ctrl or Shift modifiers the volume keys are replaced with brightness. The cofiguration assigned  to thw FN combo keys are working perfectly.

I’m fairly new to this setup, so I’d really appreciate any guidance or solutions to get the custom key bindings working properly. Thank you!

**Comment by seerge** [comment]
@Kaliyuga03 hello, what you experience is nothing similar to the topic starter. 

Most likely you have installed Armoury and changed bindings for M-buttons using that on hardware level. Do a [EC-reset](https://www.asus.com/support/faq/1050239/) to reset them to all defaults

> - Turn OFF laptop
> - Press and hold the "power" button for 30-40 seconds
> - Then boot normally (it will take a bit longer to boot)

Thanks
