### ISSUE TITLE
Ambient color mode for tuf gaming m3

### ISSUE THREAD

**Issue by BLANK0104** [seerge/g-helper#2569]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

While i as using armory crate, i also had aura sync there. That feature provided really good lighting option for my mouse but g-helper doesn't have so many options available for my mouse. 

### Describe the solution you'd like

I would at least like ambient mode to be added or aura sync and if possible more color modes.

### Describe alternatives you've considered

in the past, i was using armory crate's aura sync. i have uninstalled it as it was interfering with g-helper, but as g-helper is better than armory crate, it only makes sense to use it. It would be great if at least ambient color mode can be added if not all the modes which are offered by aura sync.

### Device and Model

Tuf Gaming M3

### Additional information.

![image](https://github.com/seerge/g-helper/assets/115344345/b7f283c9-d98b-4dbe-b423-b537e6385106)

**Comment by seerge** [comment]
@BLANK0104 hello,

Currently G-Helper would list all backlight modes that your mouse supports on it's hardware/firmware level. I.e. it's a setting that you "set and forget", letting mouse keep that color or run that animation by itself without any app involvement.

Honestly, I'm not a big fan of changing this as constantly changing mouse color can cost resources and is kind off against idea of an app being lightweight. We talk about few times a second(!) for Ambient (if you mean reflecting average screen color on mouse backlight)

Have you tried https://openrgb.org/ ? It also supports lots of peripherals, including Asus mice .

**Comment by BLANK0104** [comment]
@seerge Hii there and thank you for the reply,

So I did try using openrgb but i get the same options

![image](https://github.com/seerge/g-helper/assets/115344345/e962737b-7c76-4387-ac95-332739f52766)

So it seems like the only option for me is to go back to using armory crate for aura sync right?
And as for ambient lighting, well....I do love it a lot....Because of its feel..Let me be honest, I can't have a good gaming setup without some rgb and if the rgb are not matching with each other then I guess its kind of a waste. I know that not many will agree with me but it is what I think and find appealing.

And yeah, if you have an alternate for me or a solution where I can just use aura sync and keep the entire armory crate disabled then please do let me know.

**Comment by seerge** [comment]
@BLANK0104 check this build, I have just extended Ambient mode on main screen (Laptop Keyboard).

Every time it sets color to laptop backlight - it will try to set color to all connected and recognized peripherals

Let me know it has any effect on your mouse
[GHelper.zip](https://github.com/seerge/g-helper/files/15285921/GHelper.zip)

**Comment by BLANK0104** [comment]
@seerge hello again,

Thanks a lot for your efforts for making this. I really appreciate it a lot, but as of right now, I am on a trip for a few weeks hence I'll be unable to test it out of it works or not (although I hope it does).
I'll test it out as soon as I am able to...

And again, thank you for this. The app is already amazing and if it does work, it will be the greatest one for me... seriously, thank you ...

**Comment by BLANK0104** [comment]
@seerge hii there,
So the build you sent does work. 
so, thanks a lot, I'm really happy because of this, its amazing...
i just can't express my happiness. Seriously thanks a lot.

**Comment by seerge** [comment]
Great!
