### ISSUE TITLE
Show current driver version

### ISSUE THREAD

**Issue by lucidnx** [seerge/g-helper#2572]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I don't see chipset driver version anywhere in system. There's nothing like "AMD Chipset" or whatever it may be called in device manager with version at least partialy similiar to usual versioning of chipset, as it's shown in G-Helper (1.2.0.119 as example)

### Describe the solution you'd like

It would be nice to show also current version of installed&running driver in new column dedicated for this in "Updates" window.

### Device and Model

GA402RK

### Additional information.

Actually I have installed latest BETA BIOS (V4) with new Agesa. ASUS also included some GPU and Chipset drivers in upgrade process. However I don't see which version of chipset I am using right now, so I can not even compare them. May be helpful in other situations too?

**Comment by seerge** [comment]
@lucidnx hello, 

I have added tooltip that will show both download and installed versions (with what g-helper compares it)
[GHelper.zip](https://github.com/seerge/g-helper/files/15279141/GHelper.zip)

**Comment by lucidnx** [comment]
well that was quick! :) seems to be working fine :)

**Comment by seerge** [comment]
@lucidnx did you notice any improvements from this BIOS 503? I have also installed it now, the only real difference i see - is that my external monitor connected via usb-c now shows a ROG logo on boot ... :D

**Comment by lucidnx** [comment]
Agesa is updated finally, so fTPM issues should be gone. that's major thing. I was playing game ~30minutes and it seems to be running smoother but it might be placebo.
BTW, that's good sign, because it's finally fully implemented (USB4). I have not tested it on dock, so I can not say anything about USB4 for now. I had BETA V3, Caldigit TS4 worked almost perfectly, ethernet too (it's PCI-e) but I had a lot WHEA errors from that ethernet. It's caldigit built-in 2.5gbps. hopefully it's solved now.  iTec USB4 dockwas working on V3 too.
