### ISSUE TITLE
More screen refresh rate options 

### ISSUE THREAD

**Issue by lilrajoo** [seerge/g-helper#2574]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

currently under ghelper have 2 refresh rates, 60 and 144hz, but under windows you have 4options  60,72,144, and dynamic(72or144hz)
this is while using the nvidia gpu

### Describe the solution you'd like

add a 72hz +OD button under laptop screen.

### Describe alternatives you've considered

maybe a drop down menu for the option

### Device and Model

Asus Tuf Gaming F15, F15 FX507VU4

### Additional information.

![image](https://github.com/seerge/g-helper/assets/110761131/337450f0-e070-4de7-94f9-ebaad482e980)
this is the current options under windows settings in windows 11 :>

**Comment by seerge** [comment]
@lilrajoo hello,

It doesn't show all possible refresh rates. It shows 60hz for battery-saving and maximum one. I don't plan to overcomplicate UI with more buttons, sorry

If you want to use 72Hz (why?) - you can always just set it in windows directly

Thanks.

**Comment by lilrajoo** [comment]
@seerge hmm ok, windows resets it back to like 144hz after waking up for hibernation,
some of my games dont have a fps cap, hence 72hz, cause not too choppy and its enough hz to make it look smooth.
thx anyways :>

**Comment by seerge** [comment]
@lilrajoo it looks more like GPU driver issue if it overrides / resets refresh rate rather than windows.

**Comment by lilrajoo** [comment]
im on latest drivers lol, using nvidia control panel also resets it, ill just google a solution thx :)

**Comment by lilrajoo** [comment]
@seerge is it possible for you to add a custom resolution option under extras, i checked and its actually g-helper that overrides the custom/windows refresh rate. i did check under my display propertires and it supports 75 hz, so its not my gpu driver. would like to hear your thoughts

**Comment by seerge** [comment]
@lilrajoo just turn off ``Auto`` in G-Helper (i.e. set 60hz or anything you want), then G-Helper will not set anything on wake up / restart.

G-Helper changes refresh rate automatically only when ``Auto`` is selected

**Comment by lilrajoo** [comment]
@seerge so any other refresh rate option will work? like 144hz+OD?

**Comment by seerge** [comment]
@lilrajoo yes, just set any non auto, and set what you want in windows.

**Comment by lilrajoo** [comment]
@seerge ok im gonna try this thx
