### ISSUE TITLE
ROG幻14 2023 显卡标准模式 无法调节屏幕亮度

### ISSUE THREAD

**Issue by dougzhi** [seerge/g-helper#2577]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

ROG幻14 2023 显卡标准模式 无法调节屏幕亮度，但是切换到集显模式或者独显直连，屏幕亮度就没调节了

### How to reproduce the bug?

显卡标准模式

### Logs

显卡标准模式

### Device and Model

Rog 幻14 2023

### Armoury Crate

Uninstalled

**Comment by seerge** [comment]
https://github.com/seerge/g-helper/wiki/FAQ#i-have-problems-turning-on-eco-mode-or-adjusting-brightness
