### ISSUE TITLE
Doesnt work for Asus ProArt Studiobook One W590

### ISSUE THREAD

**Issue by orionflame** [seerge/g-helper#2581]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I am changing the modes and fan profiles but no difference at all. I would have expected at least to see the fans to go low to max speed.

### How to reproduce the bug?

1. Use Asus ProArt Studiobook One W590
2. Play with parameters

### Logs

N/A

### Device and Model

Asus ProArt Studiobook One W590

### Armoury Crate

Never installed

### Asus Services

6

### Version

0.170

### OS

Windows 11

**Comment by seerge** [comment]
> I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

@orionflame hello, can you upload logs as it was explicitly asked in issue template ? Thanks

**Comment by orionflame** [comment]
[log.txt](https://github.com/seerge/g-helper/files/15287465/log.txt)

Hi, I just attached the logs now.
Actually I installed proart creator hub but I dont see any mode selection at all nor any fan profile, i.e. silent vs max fan speed.

![image](https://github.com/seerge/g-helper/assets/41400079/23d8af2e-0920-4da0-ba39-21adee256560)

All I remember is one time when I reinstalled Windows 11 brand new, the fans were running by themselves at full speed but after a while in the same session, they turned down in speed. I don't know if it's to do with the laptop somehow installing the processes that control the fans by itself.

**Comment by seerge** [comment]
@orionflame ok.

If you didn't have any modes or settings in asus apps, you won't have them in G-Helper as your device needs to support them in a first place :)

Your log kind of confirms that

```
1/26/2024 2:02:25 AM: Mode = 0 : 0 <--- FAILED ATTEMPT TO SET BALANCED MODE
1/26/2024 2:02:25 AM: VivoMode = 0 : 0
```

Unfortunately I can't add something, that doesn't exist on your device in a first place :) 

Thanks

**Comment by orionflame** [comment]
Thanks a lot for confirming it at least.

**Comment by orionflame** [comment]
Also another info you might find it useful. I found this app and to my surprise it does change the max speed I dont know how:
https://github.com/dominiksalvet/asus-fan-control

Do you know why that might be working? In any case I am glad because with very high CPU and GPU load the fans werent spinning up faster and thus was shutting down very quickly. Now I can use it without worrying about Asus' flawed design.

**Comment by seerge** [comment]
@orionflame you can just use [Experimental build with manual fan control](https://github.com/seerge/g-helper/discussions/2272) :) that has same approach

**Comment by orionflame** [comment]
Thanks a lot man will give it a try!
