### ISSUE TITLE
Any chance of Switch for Dark mode

### ISSUE THREAD

**Issue by steelsnarl** [seerge/g-helper#2588]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

This app seems to be alway in a dark mode at night and cannot switch to bright mode individually.
In some version, it would become bright mode sometime but there is no switch

### Describe the solution you'd like

Please add a switch to control bright/dark mode. For instance, always bright / always dark / follow the system
Thanks a lot

### Device and Model

G634JZ

**Comment by seerge** [comment]
@steelsnarl hello,

That's not true. App checks current windows theme and reflects it. 

You already can override / customize theme in UI as explained in readme
https://github.com/seerge/g-helper/wiki/Power-user-settings#override-ui-theme

Thanks.

**Comment by steelsnarl** [comment]
Thanks a lot and sorry for that I am a lazy man and do not read all the readme files at first.
However, is it possible to add this as a switch in UI at any chance?

**Comment by seerge** [comment]
@steelsnarl there is 2 automatic modes following "application" (default) theme setting and "windows" theme setting. 
It should be already enough to cover all needs.

I don't want to overload (already cluttered UI) with even more toggles that 99% app users won't even touch :)

**Comment by steelsnarl** [comment]
I have fully understood and thanks for your reply
