### ISSUE TITLE
nvidia smi message pops up on every restart

### ISSUE THREAD

**Issue by gaberilde** [seerge/g-helper#2592]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

nvidia smi message with the yes and no buttons appears on every reboot seems like it started happening when i updated to 0.170.0 because i dont think it was happening then, i set my clock limit to 1485 so my gpu has the correct clocks set

### How to reproduce the bug?

reboot pc and message appears asking to run nvidia smi which i need to also click yes on every time i reboot the computer

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15318868/log.txt)

### Device and Model

asus tuf gamimg f15

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.170.0

### OS

windows 10 22H2

**Comment by gaberilde** [comment]
> @gaberilde what kind of message is that ? can you post a screenshot ?

I cant take a screenshot of it 
It's asking me yes or no to open Nvidia smi every time I restart it
Forgot what it's called now

**Comment by seerge** [comment]
@gaberilde hello.

It's quite difficult to tackle a (possible) problem if I don't know the source of it.

Since you have set a GPU clock limit, G-Helper launches ``nvidia-smi`` command in order to achieve that. And according to the log it runs correctly

```
15/05/2024 09:21:44 AM: powershell nvidia-smi -lgc 0,1485
15/05/2024 09:21:45 AM: GPU clocks set to "(gpuClkMin 0, gpuClkMax 1485)" for GPU 00000000:01:00.0 All done. <--- RESPONSE
```

Keep in mind that this happens in background. And this is by design.

There is absolutely nothing that have changed in relation to this over last releases (you are free to download any older version to verify)

I don't know what kind of popup do you get, since you refuse to provide a screenshot. 
My assumption is it could be some weird windows permissions preventing launching other apps?

Thanks.

**Comment by gaberilde** [comment]
Not sure it doesn't actually let me take a screenshot of it 
It's this took it with my phone camera 
![17157672741213518890072671623717](https://github.com/seerge/g-helper/assets/6341453/867e46c7-1d90-48fc-b420-9501d4486875)
I pressed yes so  I guess it works if I do it's just rather annoying having to do that

**Comment by seerge** [comment]
@gaberilde thanks.

This is a windows permissions popup (cause nvidia-smi needs admin rights). But it should not appear while G-Helper runs with admin rights as well.

Do you run G-Helper as admin ? 

Does this popup appear every time you change clock-limit slider in GPU tab ? (cause every time you drag it - it would run nvidia-smi again to set a new value obviously)

Did you change anything in windows recently ?

**Comment by gaberilde** [comment]
> @gaberilde thanks.
> 
> This is a windows permissions popup (cause nvidia-smi needs admin rights). But it should not appear while G-Helper runs with admin rights as well.
> 
> Do you run G-Helper as admin ?
> 
> Does this popup appear every time you change clock-limit slider in GPU tab ? (cause every time you drag it - it would run nvidia-smi again to set a new value obviously)
> 
> Did you change anything in windows recently ?

Yeah it should run as admin I have it set to run on start up I think I ran apps from g helper and it said it was running as admin also

It doesn't always appear when I change the slider but it sometimes does
Doesn't always seem to happen though 

I don't think I changed anything in windows much maybe I can see if there is anything that could be doing this through

**Comment by seerge** [comment]
@gaberilde if it happens at random (i.e. not always?) most likely it's buggy user account control popup behavior of windows itself. I can't really change anything in the app to prevent that as nvidia-smi is needed if you want to limit clocks.

Try to check your current permission settings as explained in this article
https://www.cnet.com/tech/computing/how-to-run-everything-in-administrator-mode-and-why-you-shouldnt-do-it/

**Comment by seerge** [comment]
@gaberilde did adjusting UAC settings help you ?

I have also checked, and it's possible to allow individual apps to be run without prompt as well 
https://superuser.com/questions/1607838/disable-uac-for-a-specific-program-windows-10

**Comment by gaberilde** [comment]
> @gaberilde did adjusting UAC settings help you ?
> 
> I have also checked, and it's possible to allow individual apps to be run without prompt as well https://superuser.com/questions/1607838/disable-uac-for-a-specific-program-windows-10

Hey I went to that link and went to the reg that people were saying there and saw Nvidia smi was in it and I deleted that and it seems to have fixed it thanks!

**Comment by seerge** [comment]
@gaberilde great, did you add that to the registry before ? Or was it windows doing that by some reason?

**Comment by gaberilde** [comment]
> @gaberilde great, did you add that to the registry before ? Or was it windows doing that by some reason?

I never added anything like that so not sure what happened
