### ISSUE TITLE
M16 2023 external (laptop) display main screen locked 60Hz + overdrive

### ISSUE THREAD

**Issue by alphafortytwo** [seerge/g-helper#2593]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When connecting an external (laptop) display GHelper sets the main screen to 60Hz + overdrive which can't be changed back to 240Hz as long as the external display is connected. The external display is actually a Rog Strix 18 2024 MiniLED screen which is built into a seperate frame (not connected to the laptop it originated from). Maybe it also is a bug with Windows and HDR since I can"t select an HDR calibrated profile for the external screen and the built-on brightness control doesn't work when in HDR.

### How to reproduce the bug?

1. Connect another Asus MiniLED display to laptop
2. Go to GHelper laptop display settings
3. Try changing the refresh rate back to 240Hz

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15320541/log.txt)

### Device and Model

Asus Zephyrus M16 GU604VI (2023)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.171.0

### OS

Windows 11 (newest)

**Comment by seerge** [comment]
@alphafortytwo hello,

When you connect external screen your "display configuration" in windows changes, so windows itself would set last remembered refresh rates to each screen, including 60Hz to internal one.

I don't really see you trying to set 240hz in the log besides one single time, and there it worked fine

```
15.05.2024 00:12:18: \\?\DISPLAY#BOE0B74#4&35c05215&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
15.05.2024 00:12:18: \\?\DISPLAY#BOE0B74#4&35c05215&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY2\Monitor0
15.05.2024 00:12:18: ScreenOverdrive = 1 : OK
15.05.2024 00:12:18: Screen = 240Hz : OK
```

What do you mean that you can't set 240hz ? is it available in the app UI ?
Can you change 240Hz in windows itself ?

Thanks

**Comment by alphafortytwo** [comment]
I temporarily sent the display back because of some other issues. I'll receive a new one next week and get back to you on this issue. Thank you for the support.

**Comment by alphafortytwo** [comment]
[log.txt](https://github.com/seerge/g-helper/files/15455479/log.txt)
I was able to replicate the issue. It seems that it is caused when connecting the DP (external display) to USB-C (laptop) with the normal USB-C port and not with the DP port with power delivery.

**Comment by seerge** [comment]
@alphafortytwo hello,

My questions still stand - what options for that external display do you see in windows ? and what options do you have in the app for internal laptop display?

G-Helper is not able to change refresh rate for external monitors and it doesn't do that.

And for internal display - it changes refresh rate according to the Auto setting (so everything as it should be)

240HZ when plugged in 

```
27.05.2024 19:52:01: \\?\DISPLAY#BOE0B74#4&35c05215&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
27.05.2024 19:52:01: \\?\DISPLAY#BOE0B74#4&35c05215&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
27.05.2024 19:52:01: Screen = 240Hz : OK
```

60 Hz when on battery

```
27.05.2024 09:50:38: AutoSetting for Offline
27.05.2024 09:50:39: \\?\DISPLAY#BOE0B74#4&35c05215&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} 27.05.2024 09:50:39: \\?\DISPLAY#BOE0B74#4&35c05215&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
27.05.2024 09:50:40: Screen = 60Hz : OK
```

**Comment by seerge** [comment]
@alphafortytwo any updates on the matter?

**Comment by alphafortytwo** [comment]
I tried a few different connection configurations and noticed, that my described problem only occurs with the configuration mentioned before. GHelper and Windows 11 both give me the options to change the framerate to 240Hz but after selecting and applying, the framerate is still the same. I might be able to record it.

**Comment by seerge** [comment]
@alphafortytwo ok. But then it looks like something wrong with either drivers or with cable?

Cause if you set refresh rate in windows directly and get same result - it's not what G-Helper can ever solve :)

**Comment by alphafortytwo** [comment]
Seems like it. I'm glad there was a way for the configuration to work fine. Since this is a rather special case I think we can ignore it. Thank you for your support!

**Comment by seerge** [comment]
@alphafortytwo great
