### ISSUE TITLE
Slash Lighting in the corner of the slash when laptop is unplugged 

### ISSUE THREAD

**Issue by adelbtw** [seerge/g-helper#2595]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When unpugged, the bottom corner of the slash lighting is on "breathe" conastantly. 

### How to reproduce the bug?

Unplug laptop 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15326076/log.txt)

### Device and Model

GA403UV

### Additional information.

Here is a video showcasing the issue in case that helps. 
https://github.com/seerge/g-helper/assets/166368021/68ebb147-2678-48f3-a37c-9271002195d9

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.170.0

### OS

23H2

**Comment by seerge** [comment]
@adelbtw hello, that's not what G-Helper is doing. It's a hardcoded animation showing that you battery is low (most likely) or that battery is charging ?

Did you check "Disable on battery" checkbox ?

**Comment by adelbtw** [comment]
Disable on battery is checked yes, that does make sense though the laptop is on 15%,. I have never seen it do this before though.

**Comment by seerge** [comment]
@adelbtw i have returned my g14 2024, so can't check it anymore. But I remember that :)

I can't turn it off anyhow (and don't remember AC having that option neither) 

Imho it could be handy to remind that you need to plug it back :)

**Comment by seerge** [comment]
@adelbtw you may want to try latest 0.173 where I have added (one more) light toggle. And (theoretically) it should disable even this battery indication blinking
