### ISSUE TITLE
G-Helper refusing to boot up/suddendly crashes

### ISSUE THREAD

**Issue by Random4044** [seerge/g-helper#2596]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Started happening today, everytime I try to open G-Helper it immidietly crashes and won't finish loading. The only thing I might've done that might've caused it was my antivirus Malwarebytes targeting it as a malware, though I unflagged it and even deleted the antivirus just in case. 

Even tried updating all my drives and BIOS and still wouldn't boot up.

### How to reproduce the bug?

Unknown.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15326926/log.txt)

### Device and Model

ASUS TUF Gaming F15 FX507ZC4

### Additional information.

Now reading the logs, I think the line: "Matrix control device was not found on your machine" might have to do with the issue, thought I'm still unsure what to do about this

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.170

### OS

Windows 11 Home

**Comment by seerge** [comment]
@Random4044 hello, 

If it's crashing can you check for a crash events mentioning GHelper.exe in windows Event Viewer app ?

> Matrix control device was not found on your machine
Has nothing to with it. App just states the fact that there is no anime matrix on your laptop :)

**Comment by Random4044** [comment]
2 errors pop-up simultaneously:

1) 
**Event 1026, .NET Runtime**

Application: GHelper.exe
CoreCLR Version: 7.0.1824.16914
.NET Version: 7.0.18
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Microsoft.Win32.TaskScheduler.V2Interop.IRegisteredTask.get_Xml()
   at Microsoft.Win32.TaskScheduler.Task.GetV2Definition(TaskService svc, IRegisteredTask iTask, Boolean throwError)
   at Microsoft.Win32.TaskScheduler.Task.get_Definition()
   at Startup.StartupCheck() in D:\a\g-helper\g-helper\app\Helpers\Startup.cs:line 34
   at GHelper.Program.Main(String[] args) in D:\a\g-helper\g-helper\app\Program.cs:line 149

2)  
**Event 1000, Application Error**

Faulting application name: GHelper.exe, version: 0.170.0.0, time stamp: 0x65fa0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3527, time stamp: 0x83efbeab
Exception code: 0xe0434352
Fault offset: 0x000000000006543c
Faulting process id: 0x0x2100
Faulting application start time: 0x0x1DAA70C1F7C454A
Faulting application path: C:\Users\sebas\OneDrive\Documents\GHelper\GHelper.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 22563585-a04b-4330-bf7b-0fc4c4b6d378
Faulting package full name: 
Faulting package-relative application ID: 


> Has nothing to with it. App just states the fact that there is no anime matrix on your laptop :)

Relieved to hear! Thought I was missing something else

**Comment by seerge** [comment]
@Random4044 try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/15327117/GHelper.zip)

It was something wrong with startup task (in Task Manager) and when app checked for it, windows refused to return it's details (some internal windows things)

Post a log from the app.

And I suggest to uncheck / check startup checkbox to recreate startup task.

**Comment by Random4044** [comment]
Boots up properly!!

This is the log after unchecking / checking the startup checkbox on the app, and after restarting the device:
[log.txt](https://github.com/seerge/g-helper/files/15327201/log.txt)

I'll be reporting if I find any other issues with this build
Ty for your time!!

**Comment by seerge** [comment]
Great
