### ISSUE TITLE
Balanced Preset Changing GPU Clocks

### ISSUE THREAD

**Issue by 5-A-M-5** [seerge/g-helper#2601]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I am using an Asus Zephyrus G14 2023 Ryzen 7 7735HS and RTX 4060. Whenever I switch from silent or turbo preset to balanced mode, it retains the Core Clock Limit, Core Clock Offset and Memory Clock Offset of whatever I have set in Silent or Turbo Mode. My Silent mode has all of these set as low as possible as I use this on battery, and in Turbo everything is maxed out. Switching to Balanced mode does not copy the Dynamic boost set, the Temperature Target, fan profiles, or anything to do with the CPU. I have tried deleting and reinstalling G-Helper, I have tried switching to different GPU Modes to try and sort the issue, but none have worked.

### How to reproduce the bug?

1. Select Balanced Mode
2. Change to literally any other mode
3. Switch back to Balanced Mode
4. GPU Clocks Changed

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15334938/log.txt)

### Device and Model

Zephyrus G14 2023, 7735HS, RTX 4060

### Additional information.

I don't know if this will help at all, but this has only begun after I removed G-helper and reinstalled armoury crate, as I was experiencing another issue with G-Helper where the laptop would remain in sleep, and heat up dramatically in my bag. However, this caused the battery life to drop in half, so I have reinstalled G-Helper and uninstalled Armoury Crate. Attached is (hopefully) a screen recording of the issue

https://github.com/seerge/g-helper/assets/170001114/2c1e1057-e2ae-44dc-8fd5-45f8d3832fb5

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.170.0

### OS

Windows 11, 23H2

**Comment by seerge** [comment]
@5-A-M-5 hello,

> I am using an Asus Zephyrus G14 2023 Ryzen 7 7735HS and RTX 4060. Whenever I switch from silent or turbo preset to balanced mode, it retains the Core Clock Limit, Core Clock Offset and Memory Clock Offset of whatever I have set in Silent or Turbo Mode.

You are right. And this is intentional. 

All modes don't set / override any settings by default. And when it's possible to "read" current state of that setting - UI reflects them (which is the case for CPU boost that is just part of power plan, or GPU clock offsets). 

So every time you open ``Fans+ Power`` -> ``GPU`` it just shows current state of the things reported by Nvidia driver.

You need to explicitly set something for Balanced as well (i.e. drag / interact with a slider) then it will store that setting even if it's +0 util you click ``Factory Defaults`` that resets everything again.

**Comment by seerge** [comment]
@5-A-M-5 P.S. On a side note - setting a negative Core Clock offsets actually lowers GPU clocks for same (old) power consumption. 

There is no need to do that, unless you have a broken / unstable GPU that can't just run normally on it's default clocks :) You are not making it cooler or more silent in that way.

**Comment by 5-A-M-5** [comment]
Oh that makes so much sense, thank you so much for your help. I had simply been clicking factory defaults each time it changed the GPU Clocks, rather than dragging the sliders manually. Everything is working fine now, thank you
