### ISSUE TITLE
Battery limit broken

### ISSUE THREAD

**Issue by Vishvesh1542** [seerge/g-helper#2603]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The battery limit is not working after the latest update. Even if it is set to 60% it always charges till 100. This was not a problem before but it got introduced in the latest update.

### How to reproduce the bug?

Update to the version 0.170.0 of G-Helper and try to set a limit to the battery charge.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15337793/log.txt)

### Device and Model

ASUS TUF Gaming F15 FX506HE

### Additional information.

This bug seems to be caused by the latest update

### Armoury Crate

Uninstalled

### Asus Services

5

### Version

0.170.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Vishvesh1542 sorry to read that, but latest update has absolutely nothing to do with the battery limit. You are always free to download previous version to verify.

I see that you are setting battery limit to 40% (that may be simply not supported by your device) and furthermore have Asus services running that can override that

```
5/16/2024 9:13:24 PM: BatteryLimit = 40 : OK
5/16/2024 9:13:24 PM: Optimization service is running
```

I would advice to make yourself familiar with FAQ and set limit to 80% and stop asus services.
https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working

Thanks

**Comment by Vishvesh1542** [comment]
I did a really quick test with a previous version of G-Helper (0.167.0) and put the laptop on battery till it reached 98%. Now after I charge it, it does not charge beyond which is the intended behavior. It may not be the latest update but can you please test to check if any updates between 0.167 and 0.170 broke it? I might test it a bit more later.

**Comment by seerge** [comment]
@Vishvesh1542 there are no changes in a way limiter is set since it’s introduction

**Comment by Vishvesh1542** [comment]
weird. For me tho for some reason this version works but the latest version does not. No worries I'll just keep using this version

**Comment by seerge** [comment]
@Vishvesh1542 command to set battery limit is same for all asus laptops, it just sets value and then it's up to BIOS to hold the charge.

Keep in mind, that you have TUF device, and it usually doesn't support anything "custom" besides 80% (and sometimes 60%). If you set 40% - it will be just ignored by BIOS at all.

As soon as you see in log something like
```
5/16/2024 11:34:53 AM: BatteryLimit = 60 : OK
```

It means G-Helper has set limit (it does it on start / wake up and every time you change limit manually).

If Asus Optimization service is running in background it may also try to set limit by itself (based on setting set in MyASUS).
