### ISSUE TITLE
"Screen Toggle" option puts laptop to sleep instead of only turning off screen.

### ISSUE THREAD

**Issue by Wilk-22** [seerge/g-helper#2604]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

"Screen Toggle" when bound in my case to FN+V after using puts laptop into sleep instantly while automatic sleep after designated time in windows settings is disabled

### How to reproduce the bug?

1. Bind "Screen Toggle" to shortcut (FN+V)
2. Press the shortcut (FN+V)
3. [Bug here] Screen turns off and laptop goes to sleep

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15340202/log.txt)

### Device and Model

Asus Zepherus G14 GA402RJ

### Additional information.

Laptop is plugged in
<img width="217" alt="Untitled" src="https://github.com/seerge/g-helper/assets/133992897/266511b9-4681-49af-9618-8f1a524515a7">

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.170.0

### OS

Windows 10 build 19045

**Comment by seerge** [comment]
@Wilk-22 hello, it doesn't put laptop to sleep.

It turns off screen and locks it using the only one known windows API method
https://github.com/seerge/g-helper/blob/06b4df29cb0d822e7e2d6f5148ec82e229feb56a/app/NativeMethods.cs#L44

Why did you decided it's goes into sleep?

**Comment by seerge** [comment]
@Wilk-22 that's not sleep I think. But windows can stop apps from running if screen is turned off and locked.

When laptop is properly sleeping, you will have a power-led blinking. Also if you have keyboard sleep mode turned on - it will also be blinking :)

There is nothing I can do here anyway. This is how windows behaves.

Thanks

**Comment by Wilk-22** [comment]
Thanks for answer. I ran a dedicated stopwatch app in order to check, and it run just fine, it must be an app-windows problem
