### ISSUE TITLE
Custom Key Binding error - Brightness

### ISSUE THREAD

**Issue by neeraj-jain-27** [seerge/g-helper#2607]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

FN + C to brightness up, and FN + V to brightness down, does the opposite of each other. Brightness-up decreases brightness and Brightness-down increases brightness.

### How to reproduce the bug?

In Laptop keyboard > Extra >Key Binding > select FN + C to brightness down, and FN + V to brightness up 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15350452/log.txt)

### Device and Model

Asus Tuf Gaming A15 - 2021

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.170.0

### OS

windows 11 23H2

**Comment by seerge** [comment]
@neeraj-jain-27 hello, it just means that they are swapped on hardware level on your device (hello asus).

Just swap bindings under Extra and you will be fine.

Thanks.
