### ISSUE TITLE
ASUS ROG Flow Z13 - Can't change display brightness after plugging in laptop

### ISSUE THREAD

**Issue by SnowyNate** [seerge/g-helper#2609]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I have spent many hours troubleshooting this issue, but have come to a complete loss. Using my ASUS ROG Flow Z13 (GZ301VU-DS94), when I plug in the laptop, it appears to switch to the dGPU properly, but when I change the brightness using both the hotkeys and through Windows, the display doesn't actually change in brightness. This only happens after shutting down the laptop while it, being on the Optimized mode, is relying on the iGPU.

**Things I have tried but didn't work (list may be missing some methods, these are the ones that I remember doing):**
- Using DDU (I hope this did not make things worse)
- Reinstalling ASUS Smart Display Control
- Reinstalling ASUS System Control Interface
- Using different versions of NVIDIA GPU drivers
- Reinstalling Windows (this is a new laptop that I have factory reset)
- Enabling "Enable GPU on shutdown"
- Changing display refresh rate
- Manually reinstalling NVIDIA drivers
- Turning off Windows and Intel adaptive brightness settings

### How to reproduce the bug?

1. While on optimized mode and cable unplugged, shut down laptop
2. Turn on laptop
3. Brightness control works for iGPU, but upon plugging in laptop, brightness cannot be changed until laptop is unplugged

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15368101/log.txt)

### Device and Model

ASUS ROG Flow Z13 (2023) - GZ301VU-DS94

### Armoury Crate

Installed

### Asus Services

0

### Version

0.170.0

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@SnowyNate hello,

Brightness issue is still related to Nvidia driver behavior [I mentioned in this thread](https://github.com/seerge/g-helper/discussions/1042)

When you use Optimized mode - app would turn off GPU on battery and turn on when plugged in. So if you boot while GPU was off - it can happen.

``Enable GPU on shutdown`` is the only "option" I can offer to prevent that, enabling GPU when windows notifies app that it's about to shut down.

And I see that it seem to work (multiple entries like this)
```
5/18/2024 11:48:05 PM: Forcing Standard Mode on shutdown / hibernation
5/18/2024 11:48:05 PM: GPUEco = 0 : OK <--- GPU turned ON
```

But i see that in one of the restarts GPU was still off 
```
5/18/2024 11:06:40 PM: ------------
5/18/2024 11:06:40 PM: App launched: ROG Flow Z13 GZ301VU_GZ301VU :0.170.0.0en-US
5/18/2024 11:06:40 PM: dGPU not found
5/18/2024 11:06:42 PM: Eco flag : 1 <---- GPU OFF on start
5/18/2024 11:06:42 PM: Mux flag : 1
```

Unless you have unchecked Enable GPU on Shutdown, I guess windows has just turned off too fast not letting app to do it's thing (or did that in sleep?)

So my question, does your brightness issue happen **on every restart** (in Optimized mode on battery) ? Or happens randomly / rarely ?

**Comment by seerge** [comment]
@SnowyNate P.S. If you are so actively turning laptop on / off and plugging / unplugging. 

Did you just try to set Display mode in Nvidia Control Panel to Auto and keeping GPU mode in Standard.  

It's not that effective as Asus proprietary power off for GPU of course, but Nvidia Optimus can be still quite effective in power saving? :)

**Comment by SnowyNate** [comment]
Apologies for the late response.

> @SnowyNate hello,
> 
> Brightness issue is still related to Nvidia driver behavior [I mentioned in this thread](https://github.com/seerge/g-helper/discussions/1042)
> 
> When you use Optimized mode - app would turn off GPU on battery and turn on when plugged in. So if you boot while GPU was off - it can happen.
> 
> `Enable GPU on shutdown` is the only "option" I can offer to prevent that, enabling GPU when windows notifies app that it's about to shut down.
> 
> And I see that it seem to work (multiple entries like this)
> 
> ```
> 5/18/2024 11:48:05 PM: Forcing Standard Mode on shutdown / hibernation
> 5/18/2024 11:48:05 PM: GPUEco = 0 : OK <--- GPU turned ON
> ```
> 
> But i see that in one of the restarts GPU was still off
> 
> ```
> 5/18/2024 11:06:40 PM: ------------
> 5/18/2024 11:06:40 PM: App launched: ROG Flow Z13 GZ301VU_GZ301VU :0.170.0.0en-US
> 5/18/2024 11:06:40 PM: dGPU not found
> 5/18/2024 11:06:42 PM: Eco flag : 1 <---- GPU OFF on start
> 5/18/2024 11:06:42 PM: Mux flag : 1
> ```
> 
> Unless you have unchecked Enable GPU on Shutdown, I guess windows has just turned off too fast not letting app to do it's thing (or did that in sleep?)
> 
> So my question, does your brightness issue happen **on every restart** (in Optimized mode on battery) ? Or happens randomly / rarely ?

Yes, the brightness issue happens on EVERY restart while in optimized mode on battery, which is why it is such an annoyance.



> @SnowyNate P.S. If you are so actively turning laptop on / off and plugging / unplugging.
> 
> Did you just try to set Display mode in Nvidia Control Panel to Auto and keeping GPU mode in Standard.
> 
> It's not that effective as Asus proprietary power off for GPU of course, but Nvidia Optimus can be still quite effective in power saving? :)

The display mode in Nvidia Control Panel is already set to Auto. Is keeping the GPU mode in Standard is my only option left? Also, in Nvidia Control Panel, I don't understand the difference between Auto (advanced optimus?) and Optimus, perhaps you could explain?

**Comment by seerge** [comment]
@SnowyNate 

>Yes, the brightness issue happens on EVERY restart while in optimized mode on battery, which is why it is such an annoyance.

That's strange. Cause according to logs on restart device boots with GPU enabled (as it should be).

>The display mode in Nvidia Control Panel is already set to Auto. Is keeping the GPU mode in Standard is my only option left? Also, in Nvidia Control Panel, I don't understand the difference between Auto (advanced optimus?) and Optimus, perhaps you could explain?

Auto - is when Nvidia will use Optimus to drive internal display for desktop use and turn on NVidia GPU to drive internal display only for games / other apps that need it.

---

Can you in a situation when brightness is not working - open Windows Device Manger , check if all devices are enabled / active there (i.e. no driver issues)? And if so - manually **disable** and then **enable** Nvidia GPU ? To see if it helps by any chance?

Also can you try to set Nvidia Control panel -> Display mode to ``Nvidia GPU only`` (opposite to optimus). And just check if rebooting in Optimized still causes brightness issue ?

Thanks.

**Comment by SnowyNate** [comment]
> That's strange. Cause according to logs on restart device boots with GPU enabled (as it should be).
😅Great, ASUS sent me another broken device.

> Auto - is when Nvidia will use Optimus to drive internal display for desktop use and turn on NVidia GPU to drive internal display only for games / other apps that need it.
And what about the difference between this and the Optimus option?

> Can you in a situation when brightness is not working - open Windows Device Manger , check if all devices are enabled / active there (i.e. no driver issues)? And if so - manually **disable** and then **enable** Nvidia GPU ? To see if it helps by any chance?
> 
> Also can you try to set Nvidia Control panel -> Display mode to `Nvidia GPU only` (opposite to optimus). And just check if rebooting in Optimized still causes brightness issue ?
> 
> Thanks.

Sure! Let me try it out and I'll get back to you.

**Comment by SnowyNate** [comment]
@seerge 
> Can you in a situation when brightness is not working - open Windows Device Manger , check if all devices are enabled / active there (i.e. no driver issues)? And if so - manually **disable** and then **enable** Nvidia GPU ? To see if it helps by any chance?

All devices were enabled and active. Manually disabling and enabling the Nvidia GPU had no effect.
> Also can you try to set Nvidia Control panel -> Display mode to `Nvidia GPU only` (opposite to optimus). And just check if rebooting in Optimized still causes brightness issue ?
> 
> Thanks.
When I attempt to open Nvidia Control panel, it says "You are currently not using a display attached to an NVIDIA GPU." I'll have to restart while the computer is plugged in to test this, I'll post another comment once I have.

**Comment by SnowyNate** [comment]
> When I attempt to open Nvidia Control panel, it says "You are currently not using a display attached to an NVIDIA GPU." I'll have to restart while the computer is plugged in to test this, I'll post another comment once I have.

Setting the display mode to Nvidia GPU only did not fix the issue, and actually made things worse by introducing random short freezes of the OS, and when unplugging the computer, there would be a black screen for a moment and then the windows animation that plays as if you were connecting another display.

**Comment by seerge** [comment]
@SnowyNate

>And what about the difference between this and the Optimus option?

It just switches between Optimus / NvidiaGPU depending if game or not.

-----

Try to manually set Standard before shutting down. Does that help ? My guess was that windows just shuts down to fast, not letting GPU to turn off properly (but i can't speed it up anyhow, as G-Helper acts as soon as windows notifies it about it's intentions to turn off)

**Comment by SnowyNate** [comment]
@seerge 
> It just switches between Optimus / NvidiaGPU depending if game or not.

I see. I suppose Automatic Select would be the best option to go with then.
> Try to manually set Standard before shutting down. Does that help ? My guess was that windows just shuts down to fast, not letting GPU to turn off properly (but i can't speed it up anyhow, as G-Helper acts as soon as windows notifies it about it's intentions to turn off)

Let me try it out.

**Comment by SnowyNate** [comment]
> Let me try it out.

Yes, manually setting Standard before shutting down fixes the issue, but is a pain to do every time I shut down the device.

**Comment by seerge** [comment]
@SnowyNate well, here you get your answer. Either Windows just shuts down too fast (or GPU gets enabled too slowly?).

Unfortunately I can't really change neither first nor second. 

You can try to select "Stop all apps using GPU" under Extra, mb that will speed up shutdown somehow. 

Alternatively, did you try hibernating instead ? :)

**Comment by SnowyNate** [comment]
> @SnowyNate well, here you get your answer. Either Windows just shuts down too fast (or GPU gets enabled too slowly?).
> 
> Unfortunately I can't really change neither first nor second.

Oh well, that's a shame 😔. But thank you for your time helping with this!! I really do appreciate it, especially the workarounds that you have suggested, which I will use.
> You can try to select "Stop all apps using GPU" under Extra, mb that will speed up shutdown somehow.
> 
> Alternatively, did you try hibernating instead ? :)

Fortunately, I will mainly be using hibernation, which works, on this machine instead of shutting down. It would have been nice to know that the machine would work if I ever did need to shut it down while it isn't plugged in though.

**Comment by seerge** [comment]
@SnowyNate P.S. You can also try shutting down windows with a powershell command setting a small delay

https://www.lifewire.com/create-shutdown-timer-in-windows-10-5180369

**Comment by SnowyNate** [comment]
> @SnowyNate P.S. You can also try shutting down windows with a powershell command setting a small delay
> 
> https://www.lifewire.com/create-shutdown-timer-in-windows-10-5180369

Interesting idea. Let me try that.

**Comment by SnowyNate** [comment]
> > @SnowyNate P.S. You can also try shutting down windows with a powershell command setting a small delay
> > https://www.lifewire.com/create-shutdown-timer-in-windows-10-5180369
> 
> Interesting idea. Let me try that.

This did not work. Another strange behavior that I forgot to mention was that when plugging in the device, the screen gets brighter and then suddenly dims down. Does this signal anything, or is this just normal Windows behavior? If it's just normal WIndows behavior, I can't figure out how to disable the Windows feature of the screen brightness automatically adjusting when plugging in or out the device.

**Comment by seerge** [comment]
@SnowyNate then probably with delayed shutdown windows still notifies app about it's intentions only last second.

>  I can't figure out how to disable the Windows feature of the screen brightness automatically adjusting when plugging in or out the device.

You can try to reset power plan to defaults (it could be some windows setting there)
https://github.com/seerge/g-helper/wiki/Troubleshooting#resetting-windows-power-plan-to-defaults

And also make sure that there is no auto-screen dimming set under Settings -> Power in windows as well

--

Anyway, unfortunately I can't fix it for you cause it's outside of apps' control. Furthermore whole "Enable GPU on shutdown" is already a workaround for existing Nvidia issue. I hope they will eventually fix it, as this is clearly on a driver-side, not hardware-side

Closing this then.

Thanks
