### ISSUE TITLE
Add the ability to be able to enable and disable the bios startup sound (Take 2)

### ISSUE THREAD

**Issue by GavinCrate42** [seerge/g-helper#261]
Hi again!

it would be great if g-helper had the ability to be able to enable and disable the bios startup sound.

I raise this again, since there is no advanced options in the bios of the zephyrus g14 or g15 to toggle the start up sound. So please please add to option to g- helper :-)

**Comment by seerge** [comment]
@GavinCrate42 hello,

G14 and G15 do have that option, I have literally booted in bios right now on my G14 and made a couple of photos for you: 

![IMG_4359](https://user-images.githubusercontent.com/5920850/232339882-c92c64f5-5988-4b51-b566-949504717696.jpg)
![IMG_4360](https://user-images.githubusercontent.com/5920850/232339880-69a2c9e3-0679-4a15-a50b-2f9d86fa0219.jpg)

Next to that, I'm not aware about endpoint that can turn on/off this in bios, so i simply can't add it to the app :)

**Comment by seerge** [comment]
@GavinCrate42 added  in https://github.com/seerge/g-helper/releases/tag/v0.120

**Comment by ke1ne** [comment]
@seerge A rockstar!
