### ISSUE TITLE
[Feature request] Custom profiles for laptop backlight

### ISSUE THREAD

**Issue by devilrulz4ever** [seerge/g-helper#2611]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Checking and unchecking all those tick boxes for laptop backlight is a hassle. Is it possible to create profiles for the laptop backlight so it can be done in rather fewer clicks? This would make it very convenient for people who have to change their led mode often. In my case, I change my keyboard backlight to white static and turn rest of the backlights off. 

### Describe the solution you'd like

Having custom profiles where the user can define which set of lights (keyboard, logo, lightbar, lid) would turn on/off along with the colour mode and hue.

### Device and Model

Asus ROG Strix G18 G814JV

**Comment by seerge** [comment]
@devilrulz4ever hello,

What is the practical purpose of this ?

If you speak about backlight checkboxes under ``Extra`` you generally don't need anything except "Awake" state there for regular usage. Sleep / Boost / Shutdown settings are - "set and forget" :)

The only real things that worth toggling separately is awake state of Lightbar and Lid. And even this applies only to some Strix devices as rest doesn't have that.

I don't see much point in drastically overcomplicating UI and logic of the app just to bundle this together.

Thanks.
