### ISSUE TITLE
Malwarebytes now flags ghelper.exe as "Malware.AI.915370042".

### ISSUE THREAD

**Issue by raf-42** [seerge/g-helper#2612]
Just wanted to give y'all a heads up, as of this morning Malwarebytes flags the EXE (and accompanying registry entries) as "Malware.AI.915370042". AKA its new [AI detection](https://www.malwarebytes.com/blog/detections/malware-ai) flagged it.

I've been running Ghelper version 0.170.0 for at least a week now, without issue. I run daily Malware scans, it's never been picked up before.

Given that no changes have been made (It also now flags the install exe that I've had in my downloads folder for months now), I trust the folks here, plus virustotal shows *only* Malwarebytes has it flagged (https://www.virustotal.com/gui/file/bae74c6b1b4739dbbe98c74ac851daf35f218aadd9e293c5e44e2145a41c59c7 ), I'm going to assume it's a false positive, and you might want to get that figured out with MWB folks.

Keep up the great work!

Malwarebytes log info, if it's of use:

Malware.AI.915370042, C:\WINDOWS\SYSTEM32\TASKS\GHelper, No Action By User, 1000000, 915370042, 1.0.84861, F3C52C44D00D919B368F703A, dds, 02830864, C3F4D302DC4939E9B9D65CE1A7C046B6, 46B5DF209CA75D5E2C2D66BDCE9970C137BFA47E375FF0542FD06BCFB44CCF18

**Comment by seerge** [comment]
@raf-42 there is no "instal exe" and there is no "registry entries" for G-Helper, it doesn't write absolutely anything to the registry. So I don't really understand what do you mean.

As for the rest, please make yourself familiar with the FAQ. Thanks. 

> [**Windows Defender marks app as malware / virus**](https://github.com/seerge/g-helper/wiki/FAQ#windows-defender-marks-app-as-malware--virus)
> False positives from Windows Defender (or any other similar system that uses machine learning for detection) is possible as the application is not digitally signed with a certificate. You can always download a version below or compile the app by yourself. All application sources are open and can be monitored from A to Z :)

https://www.virustotal.com/gui/url/64bc4a9446705d29571219681966ddf84107600ce4a6770461bc1396c2387604

**Comment by raf-42** [comment]
> @raf-42 there is no "instal exe" and there is no "registry entries" for G-Helper, it doesn't write absolutely anything to the registry. So I don't really understand what do you mean.
> 
> As for the rest, please make yourself familiar with the FAQ. Thanks.
> 
> > [**Windows Defender marks app as malware / virus**](https://github.com/seerge/g-helper/wiki/FAQ#windows-defender-marks-app-as-malware--virus)
> > False positives from Windows Defender (or any other similar system that uses machine learning for detection) is possible as the application is not digitally signed with a certificate. You can always download a version below or compile the app by yourself. All application sources are open and can be monitored from A to Z :)
> 
> https://www.virustotal.com/gui/url/64bc4a9446705d29571219681966ddf84107600ce4a6770461bc1396c2387604

To be clear, I'm aware that it's not malicious, but given I had it flagged today, as have others (based on posts on different subreddits), I thought you might want to be alerted about it.

And now that I read the logs more clearly, what was flagged in the registry were the scheduled tasks relating to it autostarting.

**Comment by seerge** [comment]
@raf-42 i can't do absolutely anything to fight some AI reacting on some random byte-sequences. 

App is assembled directly on github from published sources, using github actions.
