### ISSUE TITLE
Please add Linear Correction for ROG Gladius III Wireless

### ISSUE THREAD

**Issue by HuanmengQwQ** [seerge/g-helper#2616]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

There is no Linear Correction in the current version, which to me is a more important feature.

### Describe the solution you'd like

add Linear Correction

### Describe alternatives you've considered

I had to install Armory Crate again to enable or disable this feature.

### Device and Model

ROG Gladius III Wireless

**Comment by seerge** [comment]
@HuanmengQwQ what is "Linear Correction" ?

**Comment by HuanmengQwQ** [comment]
> @HuanmengQwQ what is "Linear Correction" ?

Angel snapping. The translation software doesn't translate very well, I found the appropriate description in English. Sorry about that.

**Comment by seerge** [comment]
@HuanmengQwQ so it shows in the app, but you just didn't recognize translation?

Cause I see that Angle Snapping is enabled for Gladius III Wireless

https://github.com/seerge/g-helper/blob/1d1cef12c331f0e8904642428e6a08b7f48af7df/app/Peripherals/Mouse/Models/GladiusIIIWireless.cs#L69

**Comment by HuanmengQwQ** [comment]
> @HuanmengQwQ so it shows in the app, but you just didn't recognize translation?
> 
> Cause I see that Angle Snapping is enabled for Gladius III Wireless
> 
> https://github.com/seerge/g-helper/blob/1d1cef12c331f0e8904642428e6a08b7f48af7df/app/Peripherals/Mouse/Models/GladiusIIIWireless.cs#L69

I'm not sure if the following features that appear in the software are combined into one with these two features shown in Armoury Crate? Thank you!
![image](https://github.com/seerge/g-helper/assets/53703425/8d0ae03a-14ea-46f2-89c0-d575bc93bc79)

![image](https://github.com/seerge/g-helper/assets/53703425/b2a8e218-d1b9-47af-94d6-382e057b64f0)

**Comment by seerge** [comment]
@HuanmengQwQ it should be same. You have a checkbox for Angle Snapping in the app.

Please keep in mind that Armoury **does not read actual settings from the mouse**. It just shows whatever it has set last. 

So changes set in G-Helper will not be reflected in Armoury.

**Comment by HuanmengQwQ** [comment]
> @HuanmengQwQ it should be same. You have a checkbox for Angle Snapping in the app. So everything is correct already.
> 
> Please keep in mind that Armoury **does not read actual settings from the mouse**. It just shows whatever it has set last.
> 
> So changes set in G-Helper will not be reflected in Armoury.

Thank you for your answers. Hope you have a great day.
