### ISSUE TITLE
Strange behavior at GA401II with Type-C charger.

### ISSUE THREAD

**Issue by CooleRRSA** [seerge/g-helper#262]
Hello. It's very cool utility but I have some strange behavior at my GA401II while G-Helper running.
Without connecting charger dGPU have TGP limit 40W. After connecting 120W Type-C charger TGP limit switched to 30W.
Manually switching silent/balanced/turbo buttons have no any TGP effect.

**Comment by seerge** [comment]
I don't think this is related to the app, rather asus bios have different settings for working on barrel charger / type-c / battery

**Comment by CooleRRSA** [comment]
Without G-Helper TGP is limited to 40W without Type-C charger and up to 56W with Type-C charger. 
Seems that G-Helper have some effect.

**Comment by seerge** [comment]
You have nvidia GPU, it could be dynamic boost taking effect there :)

**Comment by seerge** [comment]
@CooleRRSA what you can also try to do is to limit CPU ppt a bit, this should theoretically free up space for your GPU power (cause bios balances that)
