### ISSUE TITLE
Battery charge limit is not working

### ISSUE THREAD

**Issue by mdmahib10** [seerge/g-helper#2622]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I've tries many times but the battery charge limit is not working in my asus tuf f15. It only works using armory crate. Please fix this issue

### How to reproduce the bug?

goto g helper use the slider to limit battery charge limit. It wont work

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15396409/log.txt)

### Device and Model

Asus tuf f15 rtx 3070 (2022 version)

### Armoury Crate

Installed

### Asus Services

None

### OS

Windows 11 23h2

**Comment by keifererikson** [comment]
I had a similar issue with me 2024 G14, but I discovered some models only work with setting the limit to 80%. Setting to 85%, 90%, or 95% did not work. Only 80% works.

Did you try setting yours to 80%?

**Comment by mdmahib10** [comment]
Thanks for the help. It does work on 80%.

**Comment by keifererikson** [comment]
Awesome! Glad it helped! 😁
