### ISSUE TITLE
Cannot detect latest bios version

### ISSUE THREAD

**Issue by liuhuoz** [seerge/g-helper#2623]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Literally, I don't know whether it is a bug.
MyASUS tell me I have a new bios update, which is version 318, and I update it and restart. However, it doesn't turn into the bios UI just circling in the boot screen,and then directly restart into the system. 
But when I open G-helper and check the bios version, it still show 317, though with installed 318 like this.
![image](https://github.com/seerge/g-helper/assets/49557868/c9bf374a-1c9c-495f-ae5e-f88d0a6dee42)
And I got 2 times that the system restart when the Windows locked after updating bios. 
I don't know it is relate to G-helper or this bios update. So I just report the problem here to see it anyone get similar problem.

### How to reproduce the bug?

1. Update bios with MyASUS
2. restart system
3. check G-Helper update 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15404366/log.txt)

### Device and Model

ROG Zephyrus G14 GA402XV

### Armoury Crate

Uninstalled

### Asus Services

8

### Version

orininal 0.170.0 and update to 0.171.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@liuhuoz hello, app just shows you a mirror of Asus website with drivers and BIOS. It means that for your region they did not publish version 318 yet (but usually they do it later)

https://rog.asus.com/support/webapi/product/GetPDBIOS?website=global&model=GA402XV&cpu=GA402XV

So everything is correct.

> And I got 2 times that the system restart when the Windows locked after updating bios.
I don't know it is relate to G-helper or this bios update. So I just report the problem here to see it anyone get similar problem.

BIOS updates has nothing to do with the app

Thanks

**Comment by liuhuoz** [comment]
> @liuhuoz hello, app just shows you a mirror of Asus website with drivers and BIOS. It means that for your region they did not publish version 318 yet (but usually they do it later)
> 
> https://rog.asus.com/support/webapi/product/GetPDBIOS?website=global&model=GA402XV&cpu=GA402XV
> 
> So everything is correct.
> 
> > And I got 2 times that the system restart when the Windows locked after updating bios.
> > I don't know it is relate to G-helper or this bios update. So I just report the problem here to see it anyone get similar problem.
> 
> BIOS updates has nothing to do with the app
> 
> Thanks

Thanks for your reply

**Comment by seerge** [comment]
@liuhuoz from what i see, API should be listing latest BIOS now
