### ISSUE TITLE
Reset G Helper

### ISSUE THREAD

**Issue by nabulsi08** [seerge/g-helper#2625]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Yes, it is. I accidentally changed some things in the CPU and GPU Silent and Turbo Plans I don't know about and cannot restore everything to default. 

### Describe the solution you'd like

Now the Fan Curves can be restored to default with the button. But all other things not. I don't know how to reset it. I've already restored BIOS Factory Settings. I also tried deleting and downloading the exe again but the settings are still applied. There should be a setting to restore everything of G Helper, or at least the Plan Settings. Maybe I'm just missing something...

### Device and Model

Asus ROG Strix G17 G713RS

**Comment by seerge** [comment]
@nabulsi08 hello,

All modes are baked into BIOS by manufacturer, they are not stored in the app anyhow ([please check readme](https://github.com/seerge/g-helper?tab=readme-ov-file#rocket-performance-modes)). 

If you don't check "Apply" for any custom power limits or fan curves, all settings are as default as they can be. And this is what "Factory Defaults" button does.

Also each time you reboot, all your settings reset to defaults as well unless they are set again by AC or G-Helper.

There is absolutely no need to delete exe or do any other very strange operations.

Thanks
