### ISSUE TITLE
Battery charge limiter is not working

### ISSUE THREAD

**Issue by JuneXIE001** [seerge/g-helper#2628]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Set the battery charge limiter to 80%，It works when the computer is turned on，But after restarting the computer, it will slowly charge and exceed the threshold，Exceeding 01% -0.3% each time. After one week, it will be 100%，Using MYASUS will prevent exceeding the threshold situation，I have also read a lot about the history of the problem, but there is no way to solve it，Can you provide instructions on how to turn off the battery limit of G-helper

### How to reproduce the bug?

![微信图片_20240523135950](https://github.com/seerge/g-helper/assets/170600737/8c7c874f-49bd-4aaa-b1c7-aa077b6c092c)
![微信图片_20240523140040](https://github.com/seerge/g-helper/assets/170600737/02d10c54-825a-4d4d-a554-51c4c3f72ca4)

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15412146/log.txt)

### Device and Model

ROG Zephyrus G14 GA403UV

### Armoury Crate

Installed

### Asus Services

8

### Version

0.171

### OS

windown 11 21h2

**Comment by JuneXIE001** [comment]
"in Windows SettingsSettings -> Account -> Sign-In optionsUse my sign-in info automatically "I have already set this up, but it still doesn't work

**Comment by JuneXIE001** [comment]
Because MYASUS is working properly, I would like to disable this feature of G-Helper and use this feature of MYASUS

**Comment by seerge** [comment]
@JuneXIE001 no matter what you use, your laptop will be charging when you reboot until windows starts and either asus services or g-helper set limit. Please read FAQ, it was answered multiple times already.

If you use MyASUS - it's up to you. You don't need to " disable this feature " in G-Helper, just keep it 80%.

https://github.com/seerge/g-helper/wiki/FAQ#can-i-use-the-myasus-app-along-with-g-helper
