### ISSUE TITLE
Visual Mode settings stopped working for some reason

### ISSUE THREAD

**Issue by GeorgyDesign** [seerge/g-helper#2629]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hey, folks!

Visual Mode stopped working in G-Helper for some reason. What can be the culprit? None of the settings there do not work.

My laptop is brand new, arrived without an OS, so I installed Windows 11 and updated it to 23H2 myself. G-Helper was installed according to the guide.

Again, Visual Mode did work, but it stopped for some reason. Not sure why.

That being said, I’m not sure it was installed before or after G-Helper, but I did install Dolby Vision/Atmos app, so it might’ve caused the issue. However, I did try changing settings there and it didn’t help. Moreover, uninstalling it didn’t help either.

P.S: Maybe the issue started to happen when I updated Windows to 23H2 version, but I’m not sure about it.

### How to reproduce the bug?

The Visual Mode settings do not work, e.g. switching “Default” to “Cinema” or “Neutral” to “Warmest” does nothing.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15418320/log.txt)

### Device and Model

ASUS ROG Strix G16 G614JZ-N4011

### Armoury Crate

Never installed

### Asus Services

0

### Version

0.170.0

### OS

Windows 11 23H2

**Comment by GeorgyDesign** [comment]
> @GeorgyDesign hello,
> 
> G-Helper runs `AsusSplendid.exe` utility from Asus System Control Interface package to set visual modes, same as Armoury Crate does.
> 
> If it's not working, it's probably broken on your device by some reason.
> 
> You can try following things
> 
> 1. Manually delete `C:\ProgramData\ASUS\` folder and re-launch G-Helper, it will offer you to re-download color profiles
> 2. Reinstall Asus System Control interface as explained in [Troubleshooting](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-asus-system-control-interface)

Thanks for such a quick reply — and thank you for making sch an amazing tool!

I have a question about the suggestions:

1. Will it affect my device anyhow? I have MyAsus installed, but I don’t run it (killed the processes by G-Helper).
2. Can it cause… ehm… device issues? Is it safe? Just curious :(

BTW, I did check if AsusSplendid.exe appears if I change Visual Mode setting — it does, but disappears immediately.

**Comment by seerge** [comment]
@GeorgyDesign 

1. No, that folder stores color profiles for splendid and some it's own settings
2. What ? Reinstalling drivers don't cause "device issues" as you claim.

**Comment by GeorgyDesign** [comment]
> @GeorgyDesign
> 
> 1. No, that folder stores color profiles for splendid and some it's own settings (p.s. you can make a backup of that folder if you are really afraid by some reasons)
> 2. What ? Reinstalling drivers don't cause "device issues" as you claim.

Actually, I think I found the root cause of the issue, but first:

1. Got it, thanks!
2. No, no, I didn’t claim it causes “device issues”, I was wondering if reinstalling the aforementioned driver can cause it — not saying it or every driver can do it, just guessed. It’s a new laptop, and I did have a lot of issues with my Legion 7. Don’t want the same to happen to this one T_T

As for the issue:

Yesterday I’ve noticed that I cannot change brightness via Windows quick-access popup (or whatever the name is). However, changing brightness via buttons did work.

I’ve tried to Google and fast forward to this moment: I have “Optimized” GPU Mode enabled since I can easily switch to iGPU without a restart if I decide to go unplugged. It works nicely, I think.

However, I’m using “NVIDIA GPU Only” in NVIDIA settings when I’m plugged in, hence “Visual Mode” and brightness settings do not work.

**_I’ve switched to “Advanced Optimus” and both Visual Mode and brightness settings started to work._**

Do you think it’s possible to have Visual Mode and brightness (which I still can change via the keyboard buttons, so no biggie) settings in “Optimized” but “NVIDIA GPU Only”?

I would really appreciate it, since Advanced Optimus is so convenient!

Thank you for the help in advance!

**Comment by seerge** [comment]
@GeorgyDesign as I have explained Visual modes are handled by ``AsusSplendid`` utility. How they work depends on it, not on G-Helper.

Brightness controls should be working in any mode, if they they don't by some reason you may want to update / reinstall latest drivers for both Intel (iGPU) and Nvidia from official websites

Also, Nividia drivers have a known hiccup when they struggle to control brightness if device boots with GPU disabled (i.e. Eco or Optimized on battery). To prevent that check this topic https://github.com/seerge/g-helper/discussions/1042

Thanks
