### ISSUE TITLE
[Bug report] TUF A15 FA506II doesn't have 120 Hz + OD capable screen but the option is shown

### ISSUE THREAD

**Issue by burakdede2001** [seerge/g-helper#263]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
120 Hz + OD screen option is shown even though the laptop has 60 Hz screen.

**Clear scenario to Reproduce**
1. Open the app.
2. Check the laptop screen section.
3. It has 120 Hz and OD option.
4. You can click 120 Hz + OD.
5. Screen will freeze for a sec and nothing will happen afterwards. (It will continue working in 60 Hz mode as it should be after a sec)

**Expected behavior**
It shouldn't show 120 Hz + OD option.

**App Logs**

[log.txt](https://github.com/seerge/g-helper/files/11250017/log.txt)

**Screenshots or screencasts**

![resim](https://user-images.githubusercontent.com/29973158/232482332-5b5f3d04-8981-4add-8865-02baa6bc205f.png)
![resim](https://user-images.githubusercontent.com/29973158/232482612-33bff7e0-4a58-470c-b67f-316a21a9b5e6.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Education 22H2
 - Laptop model: ASUS TUF A15 FA506II

**Asus software**
- Armoury crate (or it's services installed): Necessary services installed (Followed README guide of GHelper)
- MyASUS installed: No
- Other Asus services running in background: No

**Additional context**

**Comment by seerge** [comment]
@burakdede2001 hello, i assume that in this situation whole Screen section makes no sense for you (as Automatic button also has no effect). Will hiding section "satisfy" you ? :)

**Comment by burakdede2001** [comment]
Hi, I don't have any problems with it but I thought it could confuse other users, thats why I opened the issue. Hiding that section would be nice.

Sorry about nitpicking, I just wanted to make it better.

**Comment by seerge** [comment]
@burakdede2001 sure :) this build should hide shole screen section if max refresh rate of internal screen is <= 60hz (i.e there is nothing to switch)

[GHelper.zip](https://github.com/seerge/g-helper/files/11261146/GHelper.zip)

**Comment by seerge** [comment]
I'll include this change in v0.54

**Comment by burakdede2001** [comment]
Thanks.
