### ISSUE TITLE
Proposal for Fan Control Strategy

### ISSUE THREAD

**Issue by leeziy** [seerge/g-helper#2630]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Most of the cooling modules in notebooks use shared heat pipes, and I believe that the strategy of separately controlling the CPU fan and the GPU fan reduces the efficiency of the cooling module.
<img width="304" alt="image" src="https://github.com/seerge/g-helper/assets/139617474/9be5ade6-1cdd-4a80-85f3-7a6825ef49a2">

### Describe the solution you'd like

I suggest adding a new fan control strategy that both fans run at the same speed and are controlled by the highest temperature between the CPU and GPU.

### Device and Model

ASUS TUF Gaming A16 FA607PI

**Comment by seerge** [comment]
@leeziy hello,

G-Helper does not control your fans, they are controlled by BIOS as it's [explained in FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)

If you really want some custom control - you can try [Experimental build with manual fan control](https://github.com/seerge/g-helper/discussions/2272). Please check that post, it contains details on optional config params.

The one you need is 

```
"fan_shift" : 100,
```

Thanks
