### ISSUE TITLE
144+OD option missing on FA506QM

### ISSUE THREAD

**Issue by nilaysriv** [seerge/g-helper#2631]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

In older versions of G-Helper, 144Hz had overdrive support. Since the last few releases, that disappeared. Option to disable overdrive is gone too

### How to reproduce the bug?

1. Open G-Helper
2. Go to Extra
3. No option to Disable overdrive
4. No option for 144+OD. Only 60 and 144 show up.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15429750/log.txt)

### Device and Model

Asus TUF A15 FA506QM

### Additional information.
![Screenshot 2024-05-24 131207](https://github.com/seerge/g-helper/assets/76720071/a1d92507-4007-4672-b681-15fad211cb2a)

![Screenshot 2024-05-24 130553](https://github.com/seerge/g-helper/assets/76720071/6535d213-c6e7-4e41-98a7-f65e1d418c98)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.172.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@nilaysriv I think you never had support for it in a first place.
What I have changed - is added a check, if device supports that or not. And if not - it won't show it in UI.

Thanks.

**Comment by seerge** [comment]
@nilaysriv when you set it ON, app would check with device and read current overdrive status and output it in the title
![image](https://github.com/seerge/g-helper/assets/5920850/52256b73-7121-4e3c-bcd2-766892c557a3)

In your case it just says 144Hz. So most likely it's simply not there :) 

Also I don't see anywhere online that it would say this model supporting something like 3ms response rate (which is overdrive).

Can you check if Armoury Crate has this option ? Don't mix it up with Panel power saver just incase (it's just refresh rate toggle)

**Comment by seerge** [comment]
@nilaysriv np, did you check for that option in AC ?
