### ISSUE TITLE
Color modes for Strix G513RM

### ISSUE THREAD

**Issue by fram446742** [seerge/g-helper#2634]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

1. I've noticed that some color modes supported by my laptop are currently inactive. The model that I have, has per-key keyboard illumination with extra modes that can be enabled in Armoury Crate.

### Describe the solution you'd like

I've tried compiling the app with modified code (changing isStrixLimitedRGB), and all modes function except for heatmap and ambient. 

It would also be great to have an option to enable "random colors" for modes that currently lack it, such as breathing, star, rain, highlight, laser, ripple, stroboscopic, comet, or flash. 

and if you want to see the changes in a repo I forked this one, here is the link:
https://github.com/fram446742/g-helper

or if you prefer here is the build that I made:
[g-helper.zip](https://github.com/seerge/g-helper/files/15443738/g-helper.zip) 

### Device and Model

Asus ROG Strix G15 (2022) G513RM

**Comment by seerge** [comment]
@fram446742 hello, you don't really need to modify any code for that.

Unfortunately your model (G513RM) exists in both per-key and 4-zone versions, so it's not possible to automatically detect what modes to show. By default it would be limited list.

You can just add following line to ``config.json``

```
"per_key_rgb" : 1,
```

And it should threat your device as per-key RGB :)

**Comment by fram446742** [comment]
Thank you very much. I didn't know that that config would work in this case. I'll give it a try.

**Comment by fram446742** [comment]
Sorry for the inconvenience, but I added it and it doesn't seem to change anything.

<img width="303" alt="image" src="https://github.com/seerge/g-helper/assets/42354796/ad9694d6-a47d-42c9-9a91-68877ba88b65">

I added it, tryed deleting the files so new ones were generated and obviously used the original version, not mine.
![image](https://github.com/seerge/g-helper/assets/42354796/36cc536c-aa24-473a-b8e7-86585a13d8f8)


This is what my version shows:
<img width="314" alt="image" src="https://github.com/seerge/g-helper/assets/42354796/f56cf358-f9bd-40c8-865c-ce9c21678d00">

**Comment by seerge** [comment]
@fram446742 can you try this build ? 

[GHelper.zip](https://github.com/seerge/g-helper/files/15444186/GHelper.zip)

**Comment by fram446742** [comment]
It does work, thanks. What is the difference with the one that is posted on the releases page?

**Comment by seerge** [comment]
@fram446742 it was 2 separate flags

- Limited RGB affecting what modes are available in a dropdown
- 4-zone RGB (opposite to per-key RGB) - affecting how exactly app would set dynamic backlight colors for Ambient / Heatmap

In new build I have just extended ``per_key_rgb`` setting effect on both options (as it should be probably)

Closing as resolved then.
