### ISSUE TITLE
Battery charge limit not working

### ISSUE THREAD

**Issue by ccrrow** [seerge/g-helper#2635]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Battery charge limit not working  (checked that  the function from myAsus working and can hold charging at 80%)

### How to reproduce the bug?

1. Open the G-Helper app
2. Slide the Battery Charge Limit bar ( all seleted valve are unavailable to ctrl )

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15445839/log.txt)

### Device and Model

ROG Zephyrus G16 GU605MV

### Additional information.

![image](https://github.com/seerge/g-helper/assets/100426674/1b054dbb-1d5d-4164-b224-b514899d6059)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.170.0

### OS

Windows 11 23H2 Build 22631.3593

**Comment by seerge** [comment]
@ccrrow hello, 

You are setting 90% as a charge limit
```
2024/5/26 上午 10:12:08: BatteryLimit = 90 : OK
```

Some models support only **80% as a limit**, so you need to set that. Other values will be disregarded by BIOS.

Please check FAQ https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working

Thanks.
