### ISSUE TITLE
G14 - Silent mode not kept active when plugged in

### ISSUE THREAD

**Issue by Winceg** [seerge/g-helper#2636]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

In silent mode, whenever I plug a charger, be it the original charger or a USB-C charger, fans start(from 0% to 70%), CPU temp rise (from ~40 to ~70-80), and frame start to get hot just like if I switched to  turbo mode. In G-Helper, it still looks like it's in silent mode, except for the temp value.
Silent mode works perfectly fine on battery.

### How to reproduce the bug?

1. Select silent mode
2. Plug charger in

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15447284/log.txt)

### Device and Model

Asus Zephyrus G14 G401QM

### Additional information.

![Capture d'écran 2024-05-26 134423](https://github.com/seerge/g-helper/assets/125641313/0ce79337-1072-49c8-ade3-510203c57034)

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

0.170.0

### OS

Windows 11 Pro 22631

**Comment by seerge** [comment]
@Winceg hello,

When you plug in your GPU gets enabled cause you have Optimized mode and it therefore just heats up whole thing.
Next to that it's absolutely normal for a device to heat up **during charging**.

If you want to keep GPU disabled on USB-C charging - you can check corresponding checkbox under ``Extra``.

Everything else works absolutely fine and as it should :) There is nothing that I need to change in the app

Thanks
