### ISSUE TITLE
CPU power limits not working on a custom fan & power profile (stuck on 20watts) 2024 G16

### ISSUE THREAD

**Issue by ndrmini** [seerge/g-helper#2639]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![manual mode not setting cpu power](https://github.com/seerge/g-helper/assets/170881202/ee91bd69-3f9d-46ed-9845-ba767e49014f)

### How to reproduce the bug?

just make a custom profile, put a load on the cpu and check cpu power level with CPUID

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15448309/log.txt)

### Device and Model

2024 Zephyrus G16 GU605MY

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.170

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@ndrmini hello,

I see that you have CPU boost disabled, without it CPU clocks are limited to base clock and it simply won't consume a lot of power in a first place.

You need to enabled boost (i.e. set it to Aggressive or Efficient Aggressive) to test :)

**Comment by ndrmini** [comment]
That does the trick!   thank you very much

**Comment by seerge** [comment]
@ndrmini great! :)
