### ISSUE TITLE
PPT slider for GPU not present

### ISSUE THREAD

**Issue by figarro** [seerge/g-helper#264]
I love your software man. Armoury Crate drove me nuts too. I'm happy with GHelper and even wrote a review (https://binaryfork.com/ghelper-armoury-crate-alternative-10216/) so others will find your little gem easier.

I have one small issue and one suggestion for future versions:
1 - PPT slider for the GPU doesn't show on my FAN + Performance page. In Armoury Crate it shows up.

![ghelper-custom-fan-curves-cpu-power](https://user-images.githubusercontent.com/15104839/232531252-20e526bf-37dc-4ca8-af3b-63f8dd6565b2.jpg)

2 - Would it be possible to add a toggle for the Legacy DRM Mode on Intel Alder Lake and newer CPUs (this disables the E-Cores).

Thank you

**Comment by seerge** [comment]
@figarro hello, thanks for the review :) it would be cool to spell name as "G-helper" (as i'm trying to be consistent with naming for better SEO)

As for your questions

1. What kind of GPU slider do you have in armoury ? if it's frequencies for nvidia - then currently g-helper doesn't control them at all (as i don't own model with nvidia and can't add them safely). But lots of people just use msi afterburner, that is much more specialised for this things anyway :) 

2. I don't know what endpoint in asus bios is responsible for that at the moment and if it's even there. You can check endpoint discovery topic - https://github.com/seerge/g-helper/issues/38 and try to find it, then I can add it ofc :) (same applies for potential GPU sliders)

**Comment by seerge** [comment]
@figarro just thought you might be interested, in https://github.com/seerge/g-helper/releases/tag/v0.58 i have added GPU overclocking and some other things :) I assume those are "missing" GPU sliders :)

**Comment by figarro** [comment]
Thanks for letting me know. I think you were right: there was no GPU PPT slider in Armoury Crate, just the amount of Dynamic Boost.
