### ISSUE TITLE
Rog gladius III not recognised via Bluetooth

### ISSUE THREAD

**Issue by luna20090** [seerge/g-helper#2641]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

It seems that g-helper dus not see this version of the Mose if its connected via Bluetooth, how can i help to get my Mose settings working

### How to reproduce the bug?

I plug in the Mose or connect it via usb an open g-helper and see the mose, but if via Bluetooth no Mose shows up.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15458458/log.txt)

This was before the Mose magically showed up (still no Bluetooth tho)

### Device and Model

Rog gladius III wireless P706

### Additional information.

I will give whatever information is needed to help resolve the issue but i live in a different time zon the Americans so it might take a wile to respond.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.170.0 

### OS

23H2 win11 22631.3593

**Comment by seerge** [comment]
@luna20090 hello, this is intentional.

G-Helper supports USB connection. So you need to use a USB-dongle or connect mouse by USB-cable :) Then it will be recognised.

Thanks.
