### ISSUE TITLE
UI recommend

### ISSUE THREAD

**Issue by cs0tony** [seerge/g-helper#2642]
### Rules

- [ ] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [ ] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

The corners of the toast is jagged.
<img width="187" alt="e7f658a9-6fef-46bb-b39f-ee2a91ed492f" src="https://github.com/seerge/g-helper/assets/107676016/ce0f1309-d24c-4197-afab-2a90b0dde10b">

### Describe the solution you'd like

Can the jagged corners of the toast for the switch function key be optimized to resemble the smooth rounded corners of the Win11 style?

### Device and Model

VivoBook_ASUSLaptop M4600I

**Comment by seerge** [comment]
@cs0tony hello, good point. This build should have corners aliased
[GHelper.zip](https://github.com/seerge/g-helper/files/15466286/GHelper.zip)
