### ISSUE TITLE
No overlay when toggling between fan presets in-game

### ISSUE THREAD

**Issue by madethisaccountcauseigotaquestion** [seerge/g-helper#2645]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

While I am on chrome, desktop, spotify, etc, when i press M4 and toggle between my fan modes, I see a semi-transparent black box that pops up telling me which mode I have swapped to. While playing games in fullscreen, like BeamNG or Tomb Raider, when i press M4, the fans toggle, but the semi-transparent black box does not show up and some times it can be confusing which mode I am in. How can I make this overlay show up in-game? (also thank you for this nice and simple software, AC felt like a maze navigating and G-helper is just straight-up function, no balogne)

### How to reproduce the bug?

1.go into a game
2.enable fullscreen
3.toggle between fan presets

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15474713/log.txt)

### Device and Model

Asus Strix G18 G814JZ

### Additional information.

![Screenshot 2024-05-28 150118](https://github.com/seerge/g-helper/assets/171082239/713bc36d-d851-49db-99a7-344d3260808f)

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.170.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@madethisaccountcauseigotaquestion hello, it's not a bug, it's a limitation of windows full-screen games. 

Windows takes over full screen completely, and doesn't allow any other apps to be shown.

It is possible to overcome that, but app needs to be signed digitally with expensive certificate and also request special permissions from windows itself.

Therefore I can't change it anyhow on this stage.

Thanks
