### ISSUE TITLE
Driver updates are not accurate on G14 2020

### ISSUE THREAD

**Issue by varunyellina** [seerge/g-helper#2646]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I used the G-Helper to see if there are any updates pending. It shows that there aren't any. So I visit the Asus website only to find that there are updates. After installing them, G-Helper continues to show that an older version is installed, which is clearly not true as seen from the device manager Properties panel.

![Screenshot 2024-05-29 003547](https://github.com/seerge/g-helper/assets/1850730/fce34fcc-56fa-479e-9908-f8c56c728508)

This seems to be the case for other drivers too. Is this a bug or expected behaviour?

### How to reproduce the bug?

1. Install latest driver from Asus website.
2. Restart laptop
3. Open G-Helper (v 0.170.0)> Updates

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15474833/log.txt)

### Device and Model

Asus Zephyrus G14 GA401IV

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.170.0

### OS

Windows 11 23H2 22631.3593

**Comment by varunyellina** [comment]
Hey, thanks for pointing it out. I was only matching the Driver name **Goodix Fingerprint**. My bad, apologies.

Do you know of a better method to reliably download only the latest drivers the device needs instead of all the drivers(new & old) listed on Asus? Ex: There are multiple downloads for AMD & Nvidia drivers with different names.

**Comment by seerge** [comment]
@varunyellina i think website / in-app is already the best ways to get drivers. After all they update extremely rarely.

For Nvidia / AMD i personally just use Nvidia/AMD website respectively, as GPU drivers are much newer there anyway
