### ISSUE TITLE
per-key RGB option is missing (GX650PY)

### ISSUE THREAD

**Issue by ataffogato** [seerge/g-helper#2647]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Absolutely love that this project provides more necessary functions than Armoury Crate, but there is one minor problem I just found: the per-key RGB option isn't available in the keyboard settings menu.
It is the only problem that bothers me a lot, is there any way I can do to fix this problem?

### How to reproduce the bug?

<img width="245" alt="2024-05-29" src="https://github.com/seerge/g-helper/assets/77221430/3724ccd7-3d7a-4c05-bf03-0c9a12d6a943">

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15474855/log.txt)

### Device and Model

ROG Zephyrus Duo 16 GX650PY

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.173.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@ataffogato hello,

App lists modes supported by your keyboard on hardware level (+ Ambient)

There is no such hardware mode as "per-key RGB". If you want to manually customize color of each key you can try https://openrgb.org/

Thanks.
