### ISSUE TITLE
Gladius II can't be seen in G-Helper

### ISSUE THREAD

**Issue by cam1x08** [seerge/g-helper#2648]
### Mouse / peripheral model and version

ROG GLADIUS II ORIGIN PINK LTD (P504)

### Armoury Crate Screenshots

![image](https://github.com/seerge/g-helper/assets/104318171/773dcf65-d673-42cf-a8e0-0a4c8a145a8b)

### USB Details

-

### Additional information.

Hi, I'm using gladius 2 P504, iirc support for it should've been available since 0.14x but for all that time I'm just not able to see my mouse in G-Helper, what could be the issue?

**Comment by seerge** [comment]
@cam1x08 hello. Are you connecting it via USB cable or via dongle?

**Comment by cam1x08** [comment]
> @cam1x08 hello. Are you connecting it via USB cable or via dongle?

Yes, I never had wireless option, plugged in directly into laptop
![image](https://github.com/seerge/g-helper/assets/104318171/1527b10b-6294-421b-9236-8e1f1963d128)

**Comment by seerge** [comment]
@cam1x08 post a log form the app as it was asked in issue template, and next to that since this is about peripheral please upload information [from this template as well](https://github.com/seerge/g-helper/issues/new?assignees=&labels=&projects=&template=peripherals_request.yml)

**Comment by cam1x08** [comment]
> @cam1x08 post a log form the app as it was asked in issue template, and next to that since this is about peripheral please upload information [from this template as well](https://github.com/seerge/g-helper/issues/new?assignees=&labels=&projects=&template=peripherals_request.yml)

here's the USB tree view.
[usb tree.txt](https://github.com/seerge/g-helper/files/15475787/usb.tree.txt)

**Comment by cam1x08** [comment]
> @cam1x08 post a log form the app as it was asked in issue template, and next to that since this is about peripheral please upload information [from this template as well](https://github.com/seerge/g-helper/issues/new?assignees=&labels=&projects=&template=peripherals_request.yml)

Do you also need screenshots from AC? because I don't have AC nor MyAsus app installed

**Comment by seerge** [comment]
@cam1x08 can you try this build ?

[GHelper.zip](https://github.com/seerge/g-helper/files/15476098/GHelper.zip)

**Comment by cam1x08** [comment]
> @cam1x08 can you try this build ?
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/15476098/GHelper.zip)

still the same, mouse can't be seen

**Comment by seerge** [comment]
@cam1x08 hm, and this one ?
[GHelper.zip](https://github.com/seerge/g-helper/files/15476496/GHelper.zip)

Can you also upload a log from `%appdata%\GHelper` ?

**Comment by cam1x08** [comment]
[log.txt](https://github.com/seerge/g-helper/files/15476507/log.txt)
same, log file attached

**Comment by seerge** [comment]
@cam1x08 hm, then I don't understand what's wrong.

Do you have more devices that could be this mouse under USBTreeView ? Cause I have added ``18CD`` as a new device id (according to that data), as your mouse seem to be some special " PNK LTD" edition ?

**Comment by cam1x08** [comment]
> @cam1x08 hm, then I don't understand what's wrong.
> 
> Do you have more devices that could be this mouse under USBTreeView ? Cause I have added `18CD` as a new device id (according to that data), as your mouse seem to be some special " PNK LTD" edition ?

![image](https://github.com/seerge/g-helper/assets/104318171/e972522a-0fc8-4921-a3e7-e0b63f5d7bd3)
that's all I have in USB tree

**Comment by seerge** [comment]
@cam1x08 can you expand that Gladius II entry in USBTreeView, select mouse specifically - and copy that log here >?

**Comment by cam1x08** [comment]
[gladius 1.txt](https://github.com/seerge/g-helper/files/15476617/gladius.1.txt)
[gladius 2.txt](https://github.com/seerge/g-helper/files/15476618/gladius.2.txt)

There's 2 of them if expanded, I wasnt sure which one to send, so I did both. gladius 1 is first, gladius 2 is 2nd. 
![image](https://github.com/seerge/g-helper/assets/104318171/eecf6161-6bf3-4ae9-947c-51f12d3e8170)

**Comment by seerge** [comment]
@cam1x08 ok, try this build targeting first one (with a mouse icon)
[GHelper.zip](https://github.com/seerge/g-helper/files/15476638/GHelper.zip)

**Comment by seerge** [comment]
@cam1x08 or this one targeting one with keyboard icon ... :| 

[GHelper.zip](https://github.com/seerge/g-helper/files/15476643/GHelper.zip)

**Comment by cam1x08** [comment]
none of those seem to work for some reason :(
![image](https://github.com/seerge/g-helper/assets/104318171/e73e41a6-0bc5-4b5d-ada8-03f71f1f5074)

**Comment by seerge** [comment]
May be @IceStormNG knows :)

**Comment by seerge** [comment]
@cam1x08 is AC able to detect and control your mouse ?

**Comment by cam1x08** [comment]
> @cam1x08 is AC able to detect and control your mouse ?

yes

**Comment by etylix** [comment]
@cam1x08 Can I contact you by Facebook or Telegram? I may try to remote debug to see if it's can be fixed.

**Comment by IceStormNG** [comment]
@cam1x08  Please try this build here, if that does not work, please send me the full output of USBTreeView for the mouse. There is some info missing in your txt files about the interfaces.

[GHelper.zip](https://github.com/seerge/g-helper/files/15480350/GHelper.zip)

**Comment by cam1x08** [comment]
> @cam1x08 Please try this build here, if that does not work, please send me the full output of USBTreeView for the mouse. There is some info missing in your txt files about the interfaces.
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/15480350/GHelper.zip)

That build finally worked, and now mouse is showing up, but changing lightning modes doesn't work. What exactly do you need from USBTreeView? that's all I have in it regarding the mouse
![image](https://github.com/seerge/g-helper/assets/104318171/757648e8-8c6b-49c8-8d5b-249e6f4f3976)

**Comment by IceStormNG** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/15480747/GHelper.zip)

Please checkout this build. This mouse has the unique capability of setting two colors per LED, which is not supported but this greatly changes the packet structure. I might need a packet log later (the packet log is inside the ghelper.log file. Please upload it after playing a bit with the lighting settings).
Please also change the rainbow mode as this needed special handling for the regular Gladius II

**Comment by cam1x08** [comment]
> [GHelper.zip](https://github.com/seerge/g-helper/files/15480747/GHelper.zip)
> 
> Please checkout this build. This mouse has the unique capability of setting two colors per LED, which is not supported but this greatly changes the packet structure. I might need a packet log later (the packet log is inside the ghelper.log file. Please upload it after playing a bit with the lighting settings). Please also change the rainbow mode as this needed special handling for the regular Gladius II

Attaching log file. Rainbow mode works, but changing speed and all regarding it doesn't yet. Colors now seem to work as they should
[log.txt](https://github.com/seerge/g-helper/files/15480855/log.txt)

**Comment by IceStormNG** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/15480952/GHelper.zip)

Alright. I made some changes. Can you please test the different modes and send me the log file again?

**Comment by cam1x08** [comment]
> [GHelper.zip](https://github.com/seerge/g-helper/files/15480952/GHelper.zip)
> 
> Alright. I made some changes. Can you please test the different modes and send me the log file again?
[log.txt](https://github.com/seerge/g-helper/files/15480998/log.txt)

Here, played with everything I guess. Speed modes on "rainbow" still act weird, I can't really see difference between normal, fast and slow

**Comment by IceStormNG** [comment]
Question: Did AC even offer different speed modes for Rainbow? Maybe the mouse does not support speed settings for Rainbow.

**Comment by cam1x08** [comment]
> Question: Did AC even offer different speed modes for Rainbow? Maybe the mouse does not support speed settings for Rainbow.

Not sure on that one, as I never used rainbow mode until now to test, tbh

**Comment by IceStormNG** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/15481204/GHelper.zip)

Ok. The read out is also different for this mouse. The mouse stores the speed settings though, but it seems to ignore it. Does the Rainbow wave runs around at "normal" speed? 
Please also test setting different colors for different zones and also the "All" setting whether this works fine.

**Comment by cam1x08** [comment]
> [GHelper.zip](https://github.com/seerge/g-helper/files/15481204/GHelper.zip)
> 
> Ok. The read out is also different for this mouse. The mouse stores the speed settings though, but it seems to ignore it. Does the Rainbow wave runs around at "normal" speed? Please also test setting different colors for different zones and also the "All" setting whether this works fine.

Slow and Fast seems to be switched, because when selecting Fast rainbow runs slow, and when selecting slow, it runs faster then normal. Setting up different colors for mouse wheel and underglow works just fine.

[log.txt](https://github.com/seerge/g-helper/files/15481614/log.txt)

**Comment by IceStormNG** [comment]
Alright, then the mouse does not support that.
Is there anything else not working or does everything works as it should?

**Comment by cam1x08** [comment]
> Alright, then the mouse does not support that. Is there anything else not working or does everything works as it should?

Everything seems to be working as it should. Thank you very much for your help and time spent!

**Comment by seerge** [comment]
Closing as resolved then. Thanks a lot again to @IceStormNG https://github.com/seerge/g-helper/pull/2651

**Comment by gorkem-bulut** [comment]
Hey there. I just realized that G-Helper has mouse support and I happened to figure that out through a friend during screen share so I have Gladius II Origin Call of Duty - Black Ops 4 Edition, never appeared on G-Helper since day one. Wanted to let you know. IDK if there is smth wrong with this mouse or it has smth to do with Asus.

**Comment by seerge** [comment]
@gorkem-bulut can you upload log from `%appdata%\GHelper` here  ?

**Comment by gorkem-bulut** [comment]
Sure. Right here:  [log.txt](https://github.com/user-attachments/files/29626570/log.txt)

**Comment by seerge** [comment]
@gorkem-bulut thanks, i don't see mouse ID here,  can you run https://www.uwe-sieber.de/usbtreeview_e.html and post a full detailed page for the mouse device from it here ? I just need USB Product ID to add it to the list

**Comment by gorkem-bulut** [comment]
<img width="913" height="605" alt="Image" src="https://github.com/user-attachments/assets/cdabdca0-214f-4237-a8a5-527ee35a29f1" />

I copied everything from highlighted section in the screenshot: [cod ed.txt](https://github.com/user-attachments/files/29626903/cod.ed.txt)
And I'm using a USB HUB. Hopefully that won't cause any issues.

**Comment by seerge** [comment]
@gorkem-bulut great, try this build

[GHelper.zip](https://github.com/user-attachments/files/29627298/GHelper.zip)

**Comment by gorkem-bulut** [comment]
THANKS! Works like a charm. I'm no longer jealous over my friend!

<img width="1385" height="730" alt="Image" src="https://github.com/user-attachments/assets/84794554-4784-4b6d-b601-60a704d0814a" />
