### ISSUE TITLE
gaming performance 

### ISSUE THREAD

**Issue by yasmine0222** [seerge/g-helper#2649]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

i installed g helper last month to help with the battery drain that AC caused and it worked .but after being pluged in and tried playing fortnite the game was stuck on 2fps and there wass no perfomance at all ( g helper was on turbo mode and gpu boost ) , so i installed AC back and the game went smothly as usual , can you help me with this ? i really want to get rid of armoury crate , it damages my pc ( tuf f15 )

### How to reproduce the bug?

1 goto 

### Logs

i dont know 

### Device and Model

Asus TUF F15

### Armoury Crate

Uninstalled

### Asus Services

NONE

### Version

0.17

### OS

windows11

**Comment by seerge** [comment]
@yasmine0222 hello, 

I can only assume you were playing in Eco mode with GPU disabled, or something like that

- Can you upload a log from `%appdata%\GHelper` as it was explicitly asked in issue template? 
- Also upload screenshots of a settings you used in G-Helper and Armoury Crate for launching this specific game?

Without that it's impossible to assist you further

Thanks

**Comment by LeoRH123** [comment]
> i dont know

Click "Extra" then click this it'll open the log, or you can also go to:

`C:\Users\username\AppData\Roaming\GHelper
`

![image](https://github.com/seerge/g-helper/assets/33641164/c75715c0-6593-409b-93b5-f52a7720be87)

**Comment by seerge** [comment]
@yasmine0222 any updates on the matter ?

**Comment by seerge** [comment]
Closed as abandoned
