### ISSUE TITLE
Battery charge limit depending on an ASUS service.

### ISSUE THREAD

**Issue by syedrey** [seerge/g-helper#2652]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I have 8 services running even after uninstalling Armoury Crate and MyASUS. Out of the 8, I guess my battery charge limit depends on the ASUS Optimization Service. 

If ASUS Optimization Service is disabled using the Stop services button in G-Helper. The battery continues to charge to 100% on any limit.

I enabled all service and disabled them one by one, that's how I found this.

### How to reproduce the bug?

1. Stop all services using Stop button in Extra in G-Helper.
2. Set a charge limit that device actually supports(60% my case).
3. The battery goes on charging beyond the limit.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15488856/log.txt)

### Device and Model

TUF Gaming A15 FA506IHRB - AMD Ryzen 5 4800H & GTX 1650

### Armoury Crate

Uninstalled

### Asus Services

1(ASUS Optimization Service)

### Version

0.170.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@SreyasXd hello, 

Some devices doesn't support anything **except 80%** as a charge limit (in MyASUS you can set only that amount). So you need to set 80% specifically.

If you will set something that is not supported - BIOS will just ignore that, and keep charging your device.

Please check [FAQ for more info](https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working)

You can also check [this topic](https://github.com/seerge/g-helper/discussions/2408) where people report what limits work on their specific device 

Thanks

**Comment by syedrey** [comment]
So it doesnt depend on any ASUS service? 

In my case, I had an option for 60%, 80%, 100% inside MyASUS app and that is the intial percentage I tried with. The other percentages I set were just to check.

**Comment by seerge** [comment]
@syedrey 

Both Asus services and G-Helper do same thing - they set charge limit value in BIOS with a special command .

If you had 60% in MyASUS - it should also work in G-Helper. So set that specifically and observe (it should stop charging above that). Assuming Asus Services don't override that.

Anything besides 80 (and possibly 60) will be ignored by BIOS, resulting in resetting charge limit . At least this is how most of TUF models work (ROGs support any value)

**Comment by syedrey** [comment]
[Main]
legal=1
[BatteryHealthCharging]
version=2
value=60
[TaskFirst]
value=0
[WiFiSmartConnect]
value=0
[ASUSOLEDCare]
Taskbar=0


This the customization.ini file inside the ProgramData folder. Does changing the limit reflect instantly in this file?
Right now, I just set 80% in G-Helper, but this in this file its still 60.

**Comment by seerge** [comment]
@syedrey that's settings file for Asus Optimization Service (MyASUS adjusts that)

G-Helper does not rely on that service and does not adjust that file :)

**Comment by syedrey** [comment]
Ok. I'll try discharging and charging again.

Thanks.

**Comment by syedrey** [comment]
Hey @seerge , I discovered that charge limit is working indeed. But if the laptop is turned off and I plug in when off, its starts charging over the limit until I turn on the laptop and G-Helper autostarts with windows, then its stops charging.

**Comment by seerge** [comment]
@syedrey correct. All Asus devices reset all their settings when they reboot, including charging limit.

**Comment by syedrey** [comment]
Ok. Is there a workaround or will you doing something in the coming updates?

**Comment by seerge** [comment]
@syedrey this how hardware works on the laptops.

**Comment by syedrey** [comment]
@syedrey Ok thanks

**Comment by syedrey** [comment]
@seerge ok thanks
