### ISSUE TITLE
Minor bug when hovering over Optimized GPU mode

### ISSUE THREAD

**Issue by TheOnlyOnlyName** [seerge/g-helper#2653]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The text below the GPU mode buttons says "switch to ... Standard when plugged", while it should say "Standard when plugged in".

### How to reproduce the bug?

1. Hover over the Optimized GPU mode
2. Observe the text below the GPU mode buttons

### Logs

N/A

### Device and Model

G14 GA403UV

### Additional information.

![image](https://github.com/seerge/g-helper/assets/72286759/98a34fab-d510-48e6-842f-2b2e13d2678d)

### Armoury Crate

Uninstalled

### Version

0.173.0

**Comment by seerge** [comment]
@TheOnlyOnlyName hello, that's just a label in translations file :)

I have adjusted it 

[GHelper.zip](https://github.com/seerge/g-helper/files/15496498/GHelper.zip)
