### ISSUE TITLE
[Add Feature] Power Option 

### ISSUE THREAD

**Issue by Pewful2021** [seerge/g-helper#2656]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hello.
So i just disabled PlatformAoAcOverride on regedit to get the Ultimate power plan, but it keep getting changed to balanced mode,
so i tried to quit the G-Helper app and now it doesn't change it anymore and it keeps it on the Ultimate power plan.

### Describe the solution you'd like

Make a tick box on the Extra option in the app that disable G-Helper to change power plan 

### Describe alternatives you've considered

Just close the g helper app via the quit on the menu

### Device and Model

FX516PE

**Comment by seerge** [comment]
@Pewful2021 hello,

You can assign any power plan you want to each mode, please check readme
https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-windows-power-plans-with-each-mode

Thanks.

**Comment by Pewful2021** [comment]
oh thanks

**Comment by Pewful2021** [comment]
but how to add it to the config.json tho ?

**Comment by seerge** [comment]
@Pewful2021 [in the beginning of the page I linked](https://github.com/seerge/g-helper/wiki/Power-user-settings#general-note) there is a quick manual :)
