### ISSUE TITLE
Auto hide G-helper on window focus loss

### ISSUE THREAD

**Issue by martinville** [seerge/g-helper#2659]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Not related to a problem just a nice to have

### Describe the solution you'd like

It would be nice to have a checkbox that can enable a setting to auto hide the main g-helper screen when the the g-helper app loses focus. This way if I tap anywhere on the screen it will close automatically. (Rog Ally)

If I may be as bold to also ask to place the setting on the extras screen :-) 

And again I i may be selfish :-) could you move the "Load on startup" checkbox also to the "extras" screen. In my opinion its not a setting that is used all the time and is just taking up real estate. Could also be tapped by accident on a ROG ally.

### Device and Model

ROG Ally Z1 Extreme

### Additional information.

I believe the request is clear ;-)

**Comment by seerge** [comment]
@martinville hello, this was already asked before, so it's a [duplicate issue](https://github.com/seerge/g-helper/issues/2324).

Please check my response and argumentation here https://github.com/seerge/g-helper/issues/2324 

Thanks and sorry.

**Comment by martinville** [comment]
No worries at all thanks for responding so quickly, happy for it to be closed!
Thanks for the hard work.
