### ISSUE TITLE
G-helper does not disable GPU after bios update

### ISSUE THREAD

**Issue by mrcheldobreck** [seerge/g-helper#266]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
Basically g-helper does not switch off gpu when running on eco

**Clear scenario to Reproduce**
1. Upgrade bios on Asus G14 (serial N8NRKD00896633E)
2. open g-helper and switch to eco

**Expected behavior**
it should switch off the gpu

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/11252944/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: Asus Zephyrus G14 (serial N8NRKD00896633E)

**Asus software**
- Armoury crate not installed
- MyASUS installed

**Comment by seerge** [comment]
@mrcheldobreck hello, in your log i see that app sends eco command and gets response 1(OK) from bios that dGPU is turned off, see log with my comments

```
4/17/2023 12:13:00: ------------
4/17/2023 12:13:00: App launched: ROG Zephyrus G14 GA402RJ_GA402RJ
4/17/2023 12:13:00: AutoSetting for Offline
4/17/2023 12:13:00: BatteryLimit = 100 : OK
4/17/2023 12:13:00: BatteryLimit = 100 : OK
4/17/2023 12:13:00: PerformanceMode = 2 : OK
4/17/2023 12:13:00: ASUS BIOS rejected fan curve, resetting mode to 2
4/17/2023 12:13:00: PerformanceMode = 2 : OK
4/17/2023 12:13:00: Eco flag : 1  <---- on app start ECO was ON
4/17/2023 12:13:00: Mux flag : 1
4/17/2023 12:13:00: Screen = 60Hz : OK
4/17/2023 12:13:00: ScreenOverdrive = 0 : OK
4/17/2023 12:13:00: Monitor Power On
4/17/2023 12:13:36: GPUEco = 0 : OK <---- app turns eco OFF 
4/17/2023 12:13:37: Eco flag : 0 <-- apps checks, and bios says that ECO is indeed OFF
4/17/2023 12:13:37: Mux flag : 1
4/17/2023 12:13:37: Screen = 60Hz : OK
4/17/2023 12:13:37: ScreenOverdrive = 0 : OK
4/17/2023 12:13:47: GPUEco = 1 : OK <---- app turns eco ON
4/17/2023 12:13:47: Eco flag : 1 <-- apps checks, and bios says that ECO is indeed ON
4/17/2023 12:13:47: Mux flag : 1
4/17/2023 12:13:47: Screen = 60Hz : OK
4/17/2023 12:13:47: ScreenOverdrive = 0 : OK

````

How do you know that dGPU is not being switched off in this case ?

**Comment by seerge** [comment]
P.S. You can also switch with a following command in powershell as admin

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00090020, 1)
```

Set 1 for Eco = ON (i.e. disable GPU), and 0 for Eco OFF (i.e. enable GPU back)

**Comment by mrcheldobreck** [comment]
![image](https://user-images.githubusercontent.com/95464043/232550826-2838a43f-e918-46a9-a14d-b4c44f56f2ea.png)
Ghelper shows that dgpu is on + there is no swithing on and off of the display when the switch happens

**Comment by seerge** [comment]
@mrcheldobreck your screenshot actually tells that dGPU is disabled :) (i.e. integrated gpu only is working) and eco is on

**Comment by mrcheldobreck** [comment]
oh okay it just would switch gpu temp to 0° in the ghelper when I'd switch
to eco. thank you

**Comment by seerge** [comment]
GPU temp sensor comes from bios as well, so it could keep showing some data (it could be a sensor on motherboard next to GPU even or so), it doesn't mean that dGPU is actually on, it just means that it's still hot :)
