### ISSUE TITLE
Key Binding -  Cmd center and ROG Buttons repeat rate & combination virtual keys not working

### ISSUE THREAD

**Issue by martinville** [seerge/g-helper#2660]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

1. The repeat rate is too fast
2. When I set either the ROG or Cmd Center button to custom and enter 0x11 0x32 there is no effect when I press the Rog or CMD button. However If I just enter 0x32.  Key '2' is correctly sent.

### How to reproduce the bug?

REPLICATE Repeat Rate is too Fast
1. Set the CMD Center button to custom and add hex val 0x32 in the textbox next to it (0x32= the '2' key)
2. Start notepad (Keep it focused)
3. Press the CMD center button once
4. Review what was pressed in notepad and you will note that in notepad there are multiple key presses. Depending on how quick you are you will see less repeats. 

REPLICATE Combinations keys
1. Set the CMD Center button to custom and add hex val 0x11 0x32 in the textbox next to it (0x11 0x32= the CTRL + '2' key)
2. Start Steam in big picture mode
3. Press CTRL+2 to confirm the right hand side menu come up.
4. Press escape to close the right hand side menu
5. Press the CMD center button
6. Take note nothing happened (Obviously besides the cmd center opening). 
I unfortunately cannot confirm if this is due to combinations keys that does not work or if its due to the repeat rate that is too fast.

### Logs

I dont have a log for this, there are no errors as such.

### Device and Model

ROG Ally Z1 Extreme

### Additional information.

I'm aware the repeat rate issue is not actually an issue as such. And actually just preference. But I have an idea the combination may not be working due to the fast repeat rate. But could off coarse be wrong.

### Armoury Crate

Installed

### Asus Services

9

### Version

0.173.0

### OS

Win 11

**Comment by seerge** [comment]
@martinville i have tested this via https://www.keyboardtester.com/ and actually it emits both keys correctly.

It could be some strange Steam limitation.

Can you check this build with extra 10ms delay between key emits ?
[GHelper.zip](https://github.com/seerge/g-helper/files/15504032/GHelper.zip)

**Comment by martinville** [comment]
I tried this build. The repeat rate made a difference.

However I cannot get CRL+2 to work though. Could I be configuring it incorrectly ?

See attached screenshot.
![keys](https://github.com/seerge/g-helper/assets/7173957/8d3e8484-9153-4324-a0e3-28d3dd94cf94)

**Comment by martinville** [comment]
Forgot to mention, on the ROG buttons drop down the "---------------" option is now gone. (I'm sure it wont be an issue but incase you are not aware ;-)

Also on the repeat rate , please give it some thought, I didn't mean for you to change it, I just thought it could be the reason for the CTRL+2 combination not working.

Thanks for the assistance! you're awesome!

**Comment by seerge** [comment]
@martinville 

> However I cannot get CRL+2 to work though. Could I be configuring it incorrectly ?
See attached screenshot.

What are you trying to achieve?  What does``Ctrl + 2`` do in Steam ? It could be that Steam listens for keyboard on hardware level, therefore everything that app can emit via windows API is just neglected.

**Comment by seerge** [comment]
@martinville any updates here ?

**Comment by martinville** [comment]
Hi Apology for the late reply.

CTRL + 2 opens the quick menu in steam.
I still wasnt able to map ghelper to combination keys even using the online
keyboard tester site. But im going to give it a bash a little later today.

In a nut shell im on a journey to configure my ROG Ally to simulate a steam
deck environment but on windows.

I installed deckyloader with some plugins which i want to access using the
crate button.

Some background.
The asus armoury crate app is a uwp app. Which can only run whilst the
windows shell is running. The cmd center still works fine.

In my case i replaced the windows shell explorer.exe with steam.exe. So
therefore the armoury crate will no longer be able to open even though the
services are running., this kind of works out great because with GHelper i
can assign the crate button to something else like the quick menu.

Ultimatly i want to create a custom plugin that will pass commands to
Ghelper from the deckyloader to adjust tdp settings and all that. And im
aware that ghelper does not have the functionalaty to pass commands to it
whilst running.

Maybe i will emark learning visual studio's c# environment. Im a vb.net guy
and interface becomes slightly different. I loaded your code into the ide
and managed to compile it sucessfully so i guess im halfway there :-)

Cheers.

**Comment by seerge** [comment]
@martinville well for key-binding i can't really change anything else except adding a delay (which does not help in your case as I understand)

I can only advice to try Sharpkeys or Autohotkey to emulate something, may be that will be better.

Next to that I can't change much unfortunately.

> Ultimatly i want to create a custom plugin that will pass commands to
Ghelper from the deckyloader to adjust tdp settings and all that. And im
aware that ghelper does not have the functionalaty to pass commands to it
whilst running.

G-Helper supports a lot of custom hotkey-combinations for switching basic stuff (including performance modes)
https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings

You can just emit those combos from your game launcher :)

Closing this then. Thanks.
