### ISSUE TITLE
Updated to 1.7.3,and bricked.

### ISSUE THREAD

**Issue by y547153** [seerge/g-helper#2664]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [x] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Just, Bricked.

### How to reproduce the bug?

downloaded newest version.
Opened Cod mw 3
whoosh.

### Logs

Sadly nothing,I can't turn that up 

### Device and Model

TUF A15 FA506IV

### Additional information.

This issues is not for compensation.
But happed TWICE after updated software.
Also turned down some boost and voltage for hot summer.

### Armoury Crate

Uninstalled

### Asus Services

0, I clicked turn all off 

### Version

173

### OS

win10 22H2

**Comment by seerge** [comment]
@y547153 hello, 

What do you understand under "bricked" what is "whoosh"? 

Please check release notes related to 0.173, it contains minor additions for slash lighting, ROG Ally and translation updates only. You are always free to use any version of the app you want tho.

Also please make yourself familiar with readme, G-Helper is not a driver and [does not run your hardware in realtime anyhow](https://github.com/seerge/g-helper?tab=readme-ov-file#-important-notice)

>  I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

Since you have ignored issue template and demonstratively didn't provide any logs or clear reproduction scenario it's impossible to assist you further. 

Thanks.

**Comment by y547153** [comment]
It seems fry the GPU power supply like last time on January.
Suddenly shutdown for no reason.
I'm not blaming you, just wondering why will that happen. 
Did update will suddenly mess the overclock settings for a shot time so that happen?
This laptop really has the official GPU and fan boost depends on Power Schemes by Asus.
And can't tweak the fan RPM by Armour Create nor ghelper. It locked with the power schemes by Asus created.
![Screenshot_2024-05-31-21-41-39-924_com jingdong app mall](https://github.com/seerge/g-helper/assets/7712097/d2c7daa9-2e6a-44ef-adc9-365b1687e86b)

**Comment by y547153** [comment]
> @y547153 hello,
> 
> What do you understand under "bricked" and what is "whoosh"?
> 
> Please check release notes related to 0.173, it contains minor additions for slash lighting, ROG Ally and translation updates only [v0.170...v0.173](https://github.com/seerge/g-helper/compare/v0.170...v0.173)
> 
> You are always free to use any version of the app you want tho.
> 
> Also please make yourself familiar with readme, G-Helper is not a driver and [does not run your hardware in realtime anyhow](https://github.com/seerge/g-helper?tab=readme-ov-file#-important-notice)
> 
> > I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.
> 
> Since you have ignored issue template and demonstratively didn't provide any logs or clear reproduction scenario it's impossible to assist you further.
> 
> Thanks.

Yea. I checked the note first so I updated, it works so fine on previous version. And I honestly hope this software will be better.

**Comment by seerge** [comment]
@y547153 

>It seems fry the GPU power supply like last time on January.
Suddenly shutdown for no reason.
I'm not blaming you, just wondering why will that happen.

If your device had hardware issues before, you can check with service. Any application won't "fix" that :)

> Did update will suddenly mess the overclock settings for a shot time so that happen?
This laptop really has the official GPU and fan boost depends on Power Schemes by Asus.

As I have linked to you neither last update, nor bunch of previous ones has absolutely nothing related to overclocking

Furthermore - adjusting GPU clock offsets in Armoury / Afterburner or G-Helper does same thing - change one setting in NVidia driver, that lets GPU run a bit faster consuming **same old power amounts**. 

> And can't tweak the fan RPM by Armour Create nor ghelper. It locked with the power schemes by Asus created.

As I have answered to you in your previous "issue" fans are controlled by BIOS. Not by windows or it's powerplans. If you really want to have some custom fan curve you can try [Experimental build with manual fan control](https://github.com/seerge/g-helper/discussions/2272)

**Comment by y547153** [comment]
> @y547153
> 
> > It seems fry the GPU power supply like last time on January.
> > Suddenly shutdown for no reason.
> > I'm not blaming you, just wondering why will that happen.
> 
> If your device had hardware issues before, you can check it in service. Any application won't "fix" that :)

 I knew it , already sent to repair and replaced the GPU power supply for $99, seems need repair again.
> > Did update will suddenly mess the overclock settings for a shot time so that happen?
> > This laptop really has the official GPU and fan boost depends on Power Schemes by Asus.
> 
> As I have [linked to you](https://github.com/seerge/g-helper/compare/v0.170...v0.173) - neither last update, nor bunch of previous ones has absolutely nothing related to overclocking
> 
> Furthermore - adjusting GPU clock offsets in Armoury / Afterburner or G-Helper does same thing - change one setting in NVidia driver, that lets GPU run a bit faster consuming **same old power amounts**.
> 
> > And can't tweak the fan RPM by Armour Create nor ghelper. It locked with the power schemes by Asus created.
> 
> As I have answered to you in your previous "issue" fans are controlled by BIOS. Not by windows or it's powerplans. If you really want to have some custom fan curve you can try [Experimental build with manual fan control](https://github.com/seerge/g-helper/discussions/2272)

This laptop truly have this "problem". It fan will definitely not been maxed out when "Asus suggest" nor Windows "balance" is active. Tested on 3Dmark, the boost inside GeForce Experience, and many games.
