### ISSUE TITLE
Charge Limit not working.

### ISSUE THREAD

**Issue by xDeliMeat** [seerge/g-helper#2668]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

charge Limit is not working. I have it set at 70% when plugged in for gaming. I have my laptop plugged into a CalDigit TS4 (for my monitors, keyboard, mouse), and am also using the power brick. The charge limit works when using only one fo the two sources. but not both. 

### How to reproduce the bug?

1. set charge limit (in G Helper)
2. use both 100W USB4 PD + power brick
3. results in charging past charge limit

### Logs

[log.txt](https://github.com/user-attachments/files/15519516/log.txt)

### Device and Model

Asus Zephyrus G14 2024, 4070, 32gb ram

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.173.0

### OS

Windows 11

**Comment by seerge** [comment]
@xDeliMeat you clearly did not read FAQ https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working

Set limit to 80% and it will work
