### ISSUE TITLE
GPU is not at max potential 

### ISSUE THREAD

**Issue by dvdganon** [seerge/g-helper#2669]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

i played with the settings a bit.
and i tried "time spy" with g-helper and with "armory crate" 
it looks like the CPU is a little better with g-helper. but the GPU is worse.
there is not a lot to do in the settings also. so i can not see where i am wrong.  the power limit is maxed. and the overclock is beyond the overclock in "armory crate"

power plane is edited to give best performance, win 11 edited, NVidia control panel edited.  all to give best results.

i have:
Zephyrus duo 16 2023, win 11
all fan working at top rpm
i have iets gt626 cooling pad working at top rpm
room is with AC at 16c.   so very cool !!!

### How to reproduce the bug?

see pictures
![COMPARE](https://github.com/seerge/g-helper/assets/33452960/3221df8d-b094-4678-a6cc-91c8a86da37b)
![COMPARE_note](https://github.com/seerge/g-helper/assets/33452960/b6ffe04f-1ecb-47c6-b377-bd2d7ad80ab4)
![Screenshot 2024-06-01 070733](https://github.com/seerge/g-helper/assets/33452960/5cd22f43-9fff-4b22-b606-97d2931a4a5d)

### Logs

no logs

### Device and Model

Asus Zephyrus duo 16 2023 win11

### Additional information.

Asus Zephyrus duo 16 2023 gx650py
cpu: 7945hx
gpu 4090 16gb
64 ram

### Armoury Crate

Uninstalled

### Version

0.173.0

### OS

Win 11

**Comment by seerge** [comment]
@dvdganon hello,

Most probably you have set different settings - so you get different results. Like 150W for CPU is a lot, try to use same as you have in AC.

I would advice to compare apples to apples first and then step by step figure out what is different :) 

Set both AC to default Turbo and G-Helper to default Turbo (click ``Factory Defaults`` + add something like +200Mhz core/memory overclock cause AC does it anyway ) and compare scores on them. Are they different ?

**Comment by dvdganon** [comment]
i literally run both benchmarks one after the other and changed nothing.  only activated the gh profile one time and ac profile the other time.
also, my problem if with the gpu performance. so why the cpu should effect it ?

thanks.

**Comment by seerge** [comment]
@dvdganon your CPU and GPU share same power budget. According to your own explanation, you have set some custom power plan maxing out CPU clocks.

That's why I suggest to run identical tests :)

**Comment by seerge** [comment]
@dvdganon 

Look at CPU clocks I have highlighted. On the right they are maxed out (in power plan probably), so CPU uses more power than it needs in graphical benchmark.

![335776237-3221df8d-b094-4678-a6cc-91c8a86da37b](https://github.com/seerge/g-helper/assets/5920850/607a76d3-f753-4785-9d0f-a111d1a08693)

So please try to use default balanced power plan for the run.

Also did you monitor how much power does GPU consume in benchmarks ? You can check that in Furmark :)

**Comment by dvdganon** [comment]
i did what you said. i compared:
A. g helper turbo with 130w cpu (like in ac) 200mhz overclock gpu and 300mhz oc for the vram.
B. ac turbo
c. ac manual mode with maxed settings ( 130w cpu (like in ac) 200mhz overclock gpu and 300mhz oc for the vram.)

i also put the pc on same power plane in all situations. to make sure that it is not bothering with anything.
the plane i put was: balanced. but altered one, that is customized for best performance. (just like the plane used in g helper turbo)

the results:

g helper plane gave same results as always like what i sent before.
ac turbo plane gave a little worse results.
ac manual plane gave the best results. still.

so, the way i see it. the g helper is a little better than the ac turbo. but it  is still behand the manual plane. it is not squiring the most from the gpu, like the ac manual plane.

**Comment by dvdganon** [comment]
btw. i think that it will be really helpful if you can add clock reading to the software. 
now there is only temp and fan speed. 
also, some kind of widget that shows fps, clock, temps....  that can be turned on in games. will help a lot :)

![Screenshot 2024-06-01 215607](https://github.com/seerge/g-helper/assets/33452960/735f6077-431c-44ec-9166-d7ae56d3ed97)

**Comment by seerge** [comment]
@dvdganon for me it's extremely difficult to advice something to you here as there is so many customizations in each case.

Try to run a simple [Furmark](https://www.geeks3d.com/furmark/) test and just monitor actual **GPU power consumption** in Afterburner or any other suitable overlay.  

Check how much power it uses when maxed out with AC and when maxed out with GH ?

Furmark is GPU heavy, but practically does not depend on CPU, so it's easier to exclude that from the equation :)

**Comment by seerge** [comment]
@dvdganon and also please upload log from the app (from `%appdata%\GHelper`) as it was asked in issue template.

**Comment by seerge** [comment]
@dvdganon did you had a chance to : 

- Check how much power GPU uses  ?
- Upload log from the app ?

Thanks

**Comment by ivi4st3r** [comment]
@seerge @dvdganon 
I think I also had this problem on Zephyrus M16 2022 (a long time ago, still there).

My case:
I have created a custom mode for normal working, that is limit GPU and CPU power as well as fan speed. When I play games, I switch to Turbo, but the machine's performance is not at the maximum level like you. I solved this problem by selecting Turbo Mode > Fans + Power (the custom fan speed, GPU, CPU appear) > Factory Defaults.

I'm too lazy to reinstall everything from scratch and test it so since this worked, I'm fine with it :))

However, sometimes I get an error that the fan speed of Custom Mode is unstable (I set it at 2600rpm). It increases and then decreases continuously, creating instability > creating noise. I selected Silent > Fans + Power (the custom fan speed, GPU, CPU appeared) > Factory Defaults > Custom mode > Apply Custom Fan Curve > Apply Power Limits.
I noticed maybe this because of Asuck service is running. But it does happen sometime when there is no Asuck service is running.

[log.txt](https://github.com/user-attachments/files/15658264/log.txt)

**Comment by ivi4st3r** [comment]
@seerge 
Maybe I talked too much about fans so it was a bit off topic :)) What I mean is, sometimes I have to click on Factory Defaults when in Turbo Mode to get maximum performance even though I don't adjust anything in Turbo Mode. The other way is I have to restart my computer. I just realized that perhaps Factory Defaults is just returning the custom fan curve to default and not the Turbo Mode (power...) setting? That's also why I find it a bit strange.

**Comment by seerge** [comment]
@ivi4st3r ``Factory defaults`` unchecks custom power limits and fan profiles and sets default Turbo mode (modes are hardcoded in BIOS anyway). 

When you set custom fan curve BIOS threats that as a "manual" mode (same as with AC), and manual mode could have a bit different behavior comparing to default :) So if defaults work better - then great.

**Comment by ivi4st3r** [comment]
@seerge
Maybe we or it's just me misunderstood each other :))
The Custom Mode (CM) I mentioned is that I created another mode different from Silent, Balance, and Turbo. When I switch from that Custom Mode to Turbo Mode (TM), the TM doesn't work as expected (low performance). Therefore, when switching from CM to TM, I have to click on Factory Defaults.

Maybe @dvdganon also switched from another Mode and encountered the same problem?

Hope it's clearer this time

**Comment by ivi4st3r** [comment]
@seerge 
This is before update: 
[before.txt](https://github.com/user-attachments/files/15671373/before.txt)
after update:
[after.txt](https://github.com/user-attachments/files/15672212/after.txt)

After update I choose TM > Fan + Power (FP) > Factory Defaults 
Then I switch to my CM 
Then I switch to TM again
Looklike it's working but maybe just for now :)) However, everytime there's a update, I alway try switching between these 2 mode but it's still have that issue.

I will open a topic if I encounter this again. Or maybe not cus press Factory Defaults when changing from CM to TM is not a problem to me :))
Just want to remind @dvdganon that maybe he have same issue like me?

**Comment by seerge** [comment]
@ivi4st3r

> Looklike it's working but maybe just for now :)) 

Glad to hear

I see that after you have clicked ``Factory Defaults`` (once) - every time switching to Turbo mode doesn't include any custom params. Of course they will be applied - if you would adjust them again :)

```
Thu 06 06 14:00:01: Mode = 1 : OK <---- TURBO MODE
Thu 06 06 14:00:03: GET GPU CLOCKS: 0, 0  <--- NOTHING ELSE HERE (app just checks for current clocks)
Thu 06 06 14:00:03: GET CLOCK LIMIT: 0
```

**Comment by ivi4st3r** [comment]
@seerge 
I did adjust TM but it's an accident maybe long ago, but I change to Factory Defaults right away.
I think it's a pattern when I success to acctually in TM, everything will work. But after turn off/restart with different mode/changing mode, the issue may appear again. So the pre-release 0.175 solve this problem? Because i update app regulary, and still sometime it's happend.

**Comment by seerge** [comment]
@ivi4st3r for your case - yes

**Comment by seerge** [comment]
Due to lack of response and absence of requested log, closed as abandoned.
