### ISSUE TITLE
GPU Temperature not shown in Optmized or Standard mode

### ISSUE THREAD

**Issue by armsp** [seerge/g-helper#267]
**Describe the bug**
In general I have never seen my GPU Temps. In the Readme.md file of this project it shows a GPU temp but I do not see that ever.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11260308/log.txt)

**Screenshots or screencasts**
![image](https://user-images.githubusercontent.com/12681262/232736428-d0fb96f0-c0c2-41ee-be6f-1b488c791b52.png)

**Desktop**
 - OS: [e.g. Windows 11]
 - ASUS ROG Zephyrus G15 GA503RM (2022 Model)
 - Ryzen CPU and NVIDIA 3060 dGPU

**Asus software**
- MyASUS installed
- I had run the debloat bat file

**Comment by seerge** [comment]
Does temp appear again if you quit/start app again? In general : it could be that driver/bios is not reporting any temps and app can't do much in this cases.

**Comment by armsp** [comment]
Oh yeah, it looks like when I transition from Eco to other modes it does not show the temp automatically. But after restarting it did appear :)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11261408/GHelper.zip)
This build will try to re-establish connection wth gpu driver after standard mode is selected (from eco). But that also depends if windows / drivers will respond at all... :)

**Comment by seerge** [comment]
I'll include this change in v0.54

**Comment by HE4DEYES** [comment]
my gpu temp comes pops up for a sec or two when i check and uncheck the custom fan box.
