### ISSUE TITLE
XG mobile fan doesn't turn on after connecting

### ISSUE THREAD

**Issue by moritzbeck13** [seerge/g-helper#2670]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I try to connect my XG Mobile, the fan doesn't turn on only after rebooting the laptop. 
When I forget to do this, the XG Mobile eventually overheats and shuts down.

### How to reproduce the bug?

1. connect XG Mobile
2. open G-Helper
3. click on XG Mobile
4. wait
5. reboot

### Logs

[log.txt](https://github.com/user-attachments/files/15522416/log.txt)

### Device and Model

Flow X13 2023 GV301RE, XG Mobile 6850XT

### Additional information.

Tried with both xgm_special 1 and 0

### Armoury Crate

Never installed

### Asus Services

0

### Version

0.173

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@moritzbeck13 hello,

I see that you are setting a custom fan curves for XGM. How does it work with default ones (i.e. click Factory Defaults or uncheck Apply Custom Fan Curve) ?

**Comment by moritzbeck13** [comment]
Doesn't seem to work either. 
I also noticed my monitor is not getting detected sometimes, but that might or might not be a different issue on my side.

**Comment by seerge** [comment]
@moritzbeck13 looks like some issue with XGM itself then. Does it work if you would connect it using AC ?

**Comment by moritzbeck13** [comment]
If possible I would like to avoid installing that garbage again 😅
I also noticed that when trying to disconnect the XGM, the fans turn off before I confirm that I have "closed all apps running on the XG Mobile". When I leave the confirmation window open, the XGM stays connected without the fans on and overheats in the same way. If I hit no, the fans turn on again.

**Comment by seerge** [comment]
@moritzbeck13 ok, can you do a quick test

1. Connect XGM as normal
2. Wait for 15+ seconds
3. Restart G-Helper after

Does it change something with fan behavior ?

**Comment by seerge** [comment]
@moritzbeck13 or try this build

[GHelper.zip](https://github.com/user-attachments/files/15531780/GHelper.zip)

**Comment by moritzbeck13** [comment]
> 1. Connect XGM as normal

If by connect you mean physically connect and then connect in GHelper; that seems to make no difference.
The build seems to make no difference aswell.
FYI I tried it with a custom fan curve, since with the default one the fans sometimes are turned off naturally, so I wouldn't be able to notice the difference then.
Once the XGM is not only physically, but also logically connected, there seems to be no way to turn on the fans without rebooting.

**Comment by seerge** [comment]
@moritzbeck13

> If by connect you mean physically connect and then connect in GHelper; that seems to make no difference.

I meant enabling it in app :) (not physically)

What I wanted to test is an init command that G-Helper sends to a device after it's connected. I have added a 15 seconds delay to that init command in the build (re-launching g-helper would have same effect)

But apparently that has nothing to do with it :)

> I also noticed that when trying to disconnect the XGM, the fans turn off before I confirm that I have "closed all apps running on the XG Mobile". 

This is cause G-Helper resets fan curve prior to disconnecting device (and as you are saying default fan curves some times are just silent anyway)

---

On this stage I don't have any ideas what are the reasons here and if they are programmatic / fixable at all.

Did you have this behavior all the time or it started only recently ? (cause from your previous posts I see that you are using app for a while)

**Comment by moritzbeck13** [comment]
> Did you have this behavior all the time or it started only recently ? (cause from your previous posts I see that you are using app for a while)

I switched back and forth between the 3070, 3080, 6850XT, 3080 and now finally the 6850XT for a bit longer. Besides that I only really used the 3080 for a while, but I don't think I have ever had that problem with it. But I do think I have had that problem as long as I have the 6850XT. I also think I remember having that problem with one of the other models I owned and I nailed it down to the xgm_special command, but don't quote me on that. Maybe other XGM users can chime in here with their configs?

**Comment by seerge** [comment]
@moritzbeck13 i feel it's like 3-4 people who use XGM in total here :D 

My point is - that absolutely nothing has changed related to XGM since it was added in the app, and tweaked (ie. for last year or so)

And if it was working fine before - and now, it's not - could be something with XGM, firmware, etc (especially cause it works fine after reboot!). Also G-Helper does not even control fans, it can either tell it to use default fan profile or set custom, that's pretty much it.

If you want to test more - you can try AC, and see if behavior is same there or not.

**Comment by seerge** [comment]
@moritzbeck13 do any manipulations with the app (like changing modes, setting / unsetting custom curve, etc) "wake up" fans in a situation when they don't turn on ?

**Comment by Mikealll** [comment]
@seerge I experience the same issues. I think it is just xgm jank, if I recall at one point it would only occur with custom fan curves set. Now it occurs regardless so I have a habit of connecting hibernating, booting back up and good to go. (2022 X13 usb 4 beta bios, XGM 3080)

**Comment by moritzbeck13** [comment]
> @moritzbeck13 do any manipulations with the app (like changing modes, setting / unsetting custom curve, etc) "wake up" fans in a situation when they don't turn on ?

No, nothing besides rebooting seems to help.

I might install Windows on another partition and try with Armoury Crate. (Yes, I hate AC that much, so probs to you.)

Maybe some insight can be won by looking at the equivalent Linux project; asusctl/supergfxctl? Asus developers seems to contribute there.

**Comment by seerge** [comment]
@moritzbeck13 as far as I know asusctl doesn't support XGM :) furthermore now it uses lots of new endpoints discovered by me here for G-Helper.

If nothing seem to help - then it's extremely likely that app can't do anything here. Most probably it's some firmware hiccup of XGM itself. 

As for now I'm closing this as not planned as I can't do anything here.

If you will find time to check AC and if suddenly and magically it will behave different - let me know and feel free to re-open.

Thanks

**Comment by moritzbeck13** [comment]
> @moritzbeck13 as far as I know asusctl doesn't support XGM :)

asusctl alone doesn't, but with supergfxctl it apparently does:
https://gitlab.com/asus-linux/supergfxctl

And this is the issue I was talking about:
https://gitlab.com/asus-linux/supergfxctl/-/issues/37

**Comment by seerge** [comment]
@moritzbeck13 i see, but that one relies on same endpoint as G-Helper / AC uses :) 

In linux it works on kernel level i think https://elixir.bootlin.com/linux/latest/source/include/linux/platform_data/x86/asus-wmi.h#L123 

It's a simple ON / OFF switch. Not specific to your fans thing 

It is also not aware about this special flag for 6850XT that G-Helper uses to run it on full power.

**Comment by seerge** [comment]
@moritzbeck13 quick thing to check

Do you have regular dGPU enabled or disabled when connecting XGM ?

Can you try to disable it prior to that ?

**Comment by moritzbeck13** [comment]
Interesting: When I logically disconnect/reconnect without physically disconnecting/reconnecting, it works!
But I cannot test it with the dGPU disabled/in Eco mode, because G-Helper says it's "only possible in Standard mode".

**Comment by seerge** [comment]
@moritzbeck13 so if you physically connect device, and then enable in app - it does not work. And if you disable/enable XGM in the app again - it does ?

**Comment by moritzbeck13** [comment]
Yes, but only if it worked before logically disconnecting (e.g I rebooted at least once after logically connecting)

1. physical connect
2. logical connect
3. not working
4. reboot
5. working
6. logical disconnect
7. logical connect
8. still working
9. logical disconnect
10. physical disconnect
11. repeat

**Comment by seerge** [comment]
@moritzbeck13 can you check if following command (run in powershell as admin) has "same" effect as logical disconnect/connect

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00090019; Control_status=1}
```

(this is what g-helper runs under the hood to "connect" just in case)

**Comment by moritzbeck13** [comment]
I needed to run the command as admin, is that correct? Otherwise I would just get some errors and nothing would happen. 
The command only disconnected my monitor. The XGM plug connection LED stayed red (instead of turning white when disconnected) and the fans were still spinning. 
Also, is it supposed to be the same command for disconnecting/connecting, e.g. a toggle? Because I was only able to disconnect, not connect. After that I had to use G-Helper to connect again, which worked (for the fans too, since I didn't physically disconnect inbetween).

**Comment by seerge** [comment]
@moritzbeck13 yes, it's just a **connect**. Replace 1 with 0 and that would be disconnect.

That's the only thing happens when press XGM in G-helper as well :)

**Comment by moritzbeck13** [comment]
I tried it with 1 while connected. That disconnected something, but not like G-Helper does it.
I tried it again with 1 - that did nothing.
I tried it again with 0 - that also did nothing.
Am I doing something wrong?

**Comment by seerge** [comment]
@moritzbeck13 

Connect
```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00090019; Control_status=1}
```

Disconnect
```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00090019; Control_status=0}
```

**Comment by moritzbeck13** [comment]
Ah, got it.
The only difference now is the running as admin thing, the fan LED is not getting set and the fans only turn off after I physically disconnect (opposed to after logically disconnecting with G-Helper).

**Comment by seerge** [comment]
@moritzbeck13 LED is set separately (via USB command when device is already connected), but as I understand running second connect in a row does not solve your problem with the fans?

**Comment by moritzbeck13** [comment]
> but as I understand running second connect in a row does not solve your problem with the fans?

No, sadly not. Is there anything else I can investigate with the different behaviour of physically disconnecting?

**Comment by seerge** [comment]
@moritzbeck13 only by checking how it behaves with AC :)
