### ISSUE TITLE
Laptop keyboard lighting settings don't work on ROG Zephyras G16.

### ISSUE THREAD

**Issue by kangkang59812** [seerge/g-helper#2672]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Laptop keyboard lighting settings don't work on ROG Zephyras G16. 

### How to reproduce the bug?

1.Laptop keyboard lighting settings
2.when I change the mode or color, nothing happened.

### Logs

NOTHING

### Device and Model

ROG Zephyras G16

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.173

### OS

WIN11

**Comment by seerge** [comment]
@kangkang59812 please read FAQ
https://github.com/seerge/g-helper/wiki/FAQ#backlight-doesnt-change-color-or-stays-blue
