### ISSUE TITLE
Skin Temperature Limit

### ISSUE THREAD

**Issue by VinhCastle** [seerge/g-helper#2673]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

My device is G14 2022, I using GHelper to limit CPU temp right now, it working good, but sometime if I open some VMs, with a random game, the laptop may have a chance to shutdown due to heat. I tried many solutions, and found that using **Universal x86 Tuning Utility, Skin Temperature Limit to 41-45 degree** can solve the issue for me.

### Describe the solution you'd like

Anyway to integrate Skin Temperature Limit to GHelper?
![image](https://github.com/seerge/g-helper/assets/42990420/3bdf819d-bfc8-4dac-8352-1c4ed74f52ee)

### Device and Model

GA402RK

**Comment by seerge** [comment]
@VinhCastle hello,

It actually already sets that when you select Temp limit in Advanced settings

It sets ``set_tctl_temp`` and ``set_apu_skin_temp_limit``
https://github.com/seerge/g-helper/blob/53bb4b87603ab0ab7ec12b3ae375fc92c0fd3813/app/Mode/ModeControl.cs#L403

You can check that in app logs as well :)

**Comment by VinhCastle** [comment]
If I set the temp limit in GHelper to 90, does that mean Skin temp limit will be 90deg as well? If so, could we have separated setting for it? Because I want to limit the skin temp to 45deg, not 90deg like the CPU

**Comment by seerge** [comment]
@VinhCastle I don't want to overcomplicate UI (as it's already too much)

Why would you want to set such low temperature limits ? It's a throttle temps, i.e. after reaching them your CPU will just drastically drop it's power consumption to cool down. Nothing else.

If you have such serious problems with overheating, why don't you just set some reasonable power limits in general? Something like 10-20W will be more than enough for regular desktop use.

**Comment by VinhCastle** [comment]
Setting Skin temp limit would help people like me who facing heating issue which is common in G14 subreddit, I still able to use full CPU power with 45deg limit in Skin temp limit.
IMHO, skin temp should not close the CPU temp, if cpu temp is 90, skin temp is 90, so the laptop chasis will burned down, all the paint on the surface will melt down. Also, if you take a look on the "premade presets" of Universal x86 Tuning Utility, the skin temp limit always as low as I mentioned

**Comment by seerge** [comment]
@VinhCastle try this build
[GHelper.zip](https://github.com/user-attachments/files/15526813/GHelper.zip)

**Comment by VinhCastle** [comment]
Thank you so much! I will let you know if it's working good, thanks again

**Comment by VinhCastle** [comment]
Hi @seerge 
It seems working good, idk if it's placebo effect or not but all good so far, I tried with 1 VM and a game today.

**Comment by seerge** [comment]
@VinhCastle great

**Comment by seerge** [comment]
@VinhCastle hello, I was checking how this APU Skin temp limit works - and it doesn't seem to do anything (at least for my G14 2022, i.e. same device as yours)

I have created a build that allows to set it very low (like to 25C), but when skin temp goes above that - CPU doesn't start throttling / dropping power

![image](https://github.com/seerge/g-helper/assets/5920850/6ca3c78f-d9fe-42b9-bf71-a1841d1c2b32)

Looks like a placebo effect tbh

**Comment by VinhCastle** [comment]
Let me try with ghelper and Universal x86 Tuning Utility, I will come back here once got the result

**Comment by VinhCastle** [comment]
Hi @seerge,
I have tried testing again the settings. I can't do technical measurement like you, but this is what I got:
- When I ignore the skin temp, just set alone the CPU temp to 89 degree, the CPU temp is locked at 89 when I run CPU heavy things. But I did get random shutdown again when I try running games with Android Studio VM opened.
- On the other side, I tried to not set CPU this time, but I set skin temp to 41, no crash so far.

Then I go back to Universal x86 Tuning Utilities, I found the tooltip there showing something like this:
![image](https://github.com/seerge/g-helper/assets/42990420/6f4a855c-18de-44dd-bac9-f3fb2111dfb2)
Does that mean the laptop chasis temp, not the CPU temp?

The build I used:
([GHelper.zip](https://github.com/user-attachments/files/15526822/GHelper.zip))

**Comment by seerge** [comment]
@VinhCastle G-Helper uses UXTU's [library](https://github.com/seerge/g-helper?tab=readme-ov-file#libraries-and-projects-used) for undervolting / temp limits under the hood. (i.e. ``Advanced``).

So ``APU Skin temp limit`` there should have same effect. 

My point was that I just didn't notice any throttling, even when I set something ridiculously low as 25C. 

How does your device run w/o any temp limits at all? Cause it generally should not crash anyway (after all i have same laptop as you do and never had that)

**Comment by VinhCastle** [comment]
Mine is a defective one, I have been struggling with the temp issue and the BSOD issue like few people on our g14 subreddit. I used to use GHelper to limit the temp, it working well but will crash when something heavy on both CPU and GPU running like VM and games. My device can reach high CPU temp without problem, but if the apps use both cpu and igpu, it would trigger random heat crash, idk why was that.
Then I found UXTU have the other type of temp limit, I tried the skin temp, then the crashes gone (no idea why) lol, I thought my device crashed because of the laptop chasis or laptop frame thing too hot???

My current GHelper setting lol:
![image](https://github.com/seerge/g-helper/assets/42990420/21913034-9def-49aa-afb7-df358faac926)


Maybe not really related but just FYI and other AMD/G14 owners: I solved my BSOD problem by setting minimum CPU on battery to 80% (I haven't let everyone know about this fix yet, will make a post on reddit)

**Comment by seerge** [comment]
@VinhCastle can you just try latest 0.175 (that can set CPU temp limit, but does not set APU skin next to it) ?

**Comment by VinhCastle** [comment]
Hi @seerge,
I got crashes with the new v0.175. Was playing Pummel Party with Wallpaper Engine running, happen only when I played the game for like 1-2hours long
![image](https://github.com/seerge/g-helper/assets/42990420/dfd22b37-febd-4310-8112-af91451ad65e)

**Comment by VinhCastle** [comment]
I think I'll try again limiting the skin temp in few more days and let you know to be sure

**Comment by VinhCastle** [comment]
Hi @seerge,
So far I don't encounter any crashes when limiting the skin temp, idk why lol. Maybe my machine having a special issue. I can use ghelper together with UXTU

**Comment by seerge** [comment]
@VinhCastle that's cool, but I have a feeling that this setting actually limits something else, but not the skin temp, which still helps in your specific situation :)

**Comment by Lucid90** [comment]
@VinhCastle Did you manage to avoid unexpected shutdowns using the CPU Skin Temp limitation from GHelper or only from UXTU ?
