### ISSUE TITLE
Driver update not getting green label in g-helper updates tab

### ISSUE THREAD

**Issue by korkuttaha** [seerge/g-helper#2674]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hello,

No matter if i install more than 1 times this driver, its not getting green label and staying as red.

![image](https://github.com/seerge/g-helper/assets/7381040/e24ba002-4784-4966-9fd0-2892a650d849)

### How to reproduce the bug?

See error

### Logs

[log.txt](https://github.com/user-attachments/files/15526478/log.txt)

### Device and Model

Asus g17

### Armoury Crate

Never installed

### Asus Services

None

### Version

0.173.0

### OS

Windows 11  21h2

**Comment by seerge** [comment]
@korkuttaha hello,

When download is marked as ``Grey`` it means that it's impossible to check a local version and if it's installed at all. Cause Asus does not provide device ids for some drivers / downloads (mostly for software ones)

If you have installed it once - that's already fine, and you don't need to do it again.

So there is nothing to fix here :)

Thanks.
