### ISSUE TITLE
App won't start

### ISSUE THREAD

**Issue by emilka1337** [seerge/g-helper#2675]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Notebook: ASUS TUF A15 2023 FA507NU

App crashes on start without any error displayed.

Event viever log 1:

```
Faulting application name: GHelper.exe, version: 0.173.0.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4355, time stamp: 0xd7762934
Exception code: 0xe0434352
Fault offset: 0x000000000002ba99
Faulting process id: 0x528c
Faulting application start time: 0x01dab520496115aa
Faulting application path: C:\Users\ADmin\Desktop\GHelper\GHelper.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 36442314-3432-4337-9021-9f9881f66bb5
Faulting package full name: 
Faulting package-relative application ID: 
```

Event viever log 2:

```
Application: GHelper.exe
CoreCLR Version: 7.0.2024.26716
.NET Version: 7.0.20
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'System.Windows.Forms, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

### How to reproduce the bug?

Just open the app

### Logs

Event viever log 1:

```
Faulting application name: GHelper.exe, version: 0.173.0.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4355, time stamp: 0xd7762934
Exception code: 0xe0434352
Fault offset: 0x000000000002ba99
Faulting process id: 0x528c
Faulting application start time: 0x01dab520496115aa
Faulting application path: C:\Users\ADmin\Desktop\GHelper\GHelper.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 36442314-3432-4337-9021-9f9881f66bb5
Faulting package full name: 
Faulting package-relative application ID: 
```

Event viever log 2:

```
Application: GHelper.exe
CoreCLR Version: 7.0.2024.26716
.NET Version: 7.0.20
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'System.Windows.Forms, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

### Device and Model

ASUS TUF A15 FA507NU

### Armoury Crate

Uninstalled

### Asus Services

MyAsus

### Version

latest on June 2 2024

### OS

Windows 10 Home 22H2

**Comment by seerge** [comment]
@emilka1337 hello, exception says that something is broken in .NET library in windows. It's crashing outside of actual app code even.

Try to reinstall latest .NET
https://download.visualstudio.microsoft.com/download/pr/8091a826-e1c4-424a-b17b-5c10776cd3de/8957f21a279322d8fac9b542c6aba12e/dotnet-sdk-7.0.408-win-x64.exe

**Comment by emilka1337** [comment]
Thank you VERY much! It was very helpful, and app is launching now!
