### ISSUE TITLE
Automatically turn off Slash Lighting when the computer goes into sleep mode.

### ISSUE THREAD

**Issue by Charlizsz** [seerge/g-helper#2676]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hello,

In the Zephyrus G14/G16 (2024), ASUS introduced the "Slash Lighting" feature. The current version of GHelper already has an option to control this feature, but Slash Lighting has a very annoying problem in everyday use. The lights remain on even when the computer is in sleep mode, which is particularly bothersome for users who do not have the habit of closing the lid after using the computer. Could you please add an option to automatically turn off Slash Lighting when the computer goes into sleep mode, similar to how the keyboard lights are managed?

Thank you.

### Describe the solution you'd like

Add a toggle to automatically turn off Slash Lighting when the computer goes into sleep mode.

### Device and Model

ASUS Zephyrus G14 (2024)

**Comment by seerge** [comment]
@Charlizsz hello,

That's not possible unfortunately, cause when computer goes into sleep mode it suspends all apps (including G-Helper) and it simply can't run any commands to turn it off then :)

**Comment by Charlizsz** [comment]
@seerge Hi! I got it！

Thank you for your prompt response and reply. You have done a lot for us users, and we are very grateful! :)
