### ISSUE TITLE
adding support for ROG keyboards 

### ISSUE THREAD

**Issue by Aydin2741** [seerge/g-helper#2678]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Is it possible you add support for ROG keyboards?
I recently bought ROG Azoth, but don't want to install Asus software again... 

### Describe the solution you'd like

adding support for ROG Keyboards

### Device and Model

ROG Azoth

**Comment by seerge** [comment]
@Aydin2741 this is a dublicate of https://github.com/seerge/g-helper/issues/2544

**Comment by Aydin2741** [comment]
oh sorry, my bad

**Comment by seerge** [comment]
@Aydin2741 hello, 

If you are interested you can test external keyboards support in a new build https://github.com/seerge/g-helper/discussions/5710 

Thanks!

**Comment by seerge** [comment]
Live in the latest release https://github.com/seerge/g-helper/releases
