### ISSUE TITLE
Fan RPM does not seem to obey the custom Fan Speed vs CPU temperature curve

### ISSUE THREAD

**Issue by armsp** [seerge/g-helper#268]
**Describe the bug**
CPU fan speed does not correspond to what the speed should be according to the Fan curve.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11262567/log.txt)

**Screenshots or screencasts**
![image](https://user-images.githubusercontent.com/12681262/232800904-10c3b275-f7a3-4567-a3f5-afef66420f8b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ROG Zephyrus G15 GA503RM 2022 Model

**Asus software**
- MyASUS installed
- Ran the debloat bat file

**Comment by seerge** [comment]
@armsp you don't even have that curve enabled. Also as [readme](https://github.com/seerge/g-helper#how-does-g-helper-control-my-fan-speeds) says your fans are controlled by bios, not by app.

**Comment by armsp** [comment]
Ah yeah, I had it enabled for Silent mode and it used to work...somehow I missed it for other modes. My bad.
