### ISSUE TITLE
Random bluescreens, always when unplugging (G14 2024)

### ISSUE THREAD

**Issue by Classytagz** [seerge/g-helper#2682]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I've been having frequent bluescreens on my G14 2024 (RTX 4070), and I think G-Helper might have something to do with it.
The bluescreen goes away very quickly, so I'm not able to see an error code.

### How to reproduce the bug?

1. Have custom fan profiles enabled
2. Unplug laptop
3. Sometimes bluescreens

### Logs

[log.txt](https://github.com/user-attachments/files/15546116/log.txt)

### Device and Model

Asus Zephyrus G14 GA403UI

### Additional information.

<img width="451" alt="Screenshot 2024-06-04 114602" src="https://github.com/seerge/g-helper/assets/150660804/0aff1da3-9738-4993-9102-c1fa5b158221">
<img width="980" alt="Screenshot 2024-06-04 114637" src="https://github.com/seerge/g-helper/assets/150660804/5471de2e-a376-4ada-b2c8-cd6ee660d492">
<img width="410" alt="Screenshot 2024-06-04 114625" src="https://github.com/seerge/g-helper/assets/150660804/c59a08bf-6325-4107-8906-7acb0bbf31eb">

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.173

### OS

Windows 11 Home

**Comment by Classytagz** [comment]
Thank you for the information, I'll do all that!
Sorry for the broad question aha :)

**Comment by seerge** [comment]
@Classytagz by the way, since your GameSDK error says 

> The GameSDK Service service failed to start due to the following error:
**The system cannot find the file specified.**

It looks like windows install or some files there are corrupt (at least it can't find a file?). I would do this https://github.com/seerge/g-helper/wiki/Troubleshooting#repair-corrupted-system-files

**Comment by Classytagz** [comment]
It didn't find any corrupted files, so it may be a driver issue.
I have always had issues with the AMD chipset/iGPU drivers for some reason.
When i manually install the Adrenaline software and latest driver, it always gets uninstalled later, and I can't figure out why.
I notice it right away, because without the iGPU drivers, the entire screen has tearing, and just feels sluggish.

**Comment by seerge** [comment]
@Classytagz 

Try to use AMD Cleanup utility https://www.amd.com/en/resources/support-articles/faqs/GPU-601.html first

**Comment by Classytagz** [comment]
I'll follow the steps on the troubleshooting page you just mentioned, I'll get back to you with any updates, thank you! :)

**Comment by seerge** [comment]
@Classytagz any updates here ? :)

**Comment by Classytagz** [comment]
Sorry for the silence, I'm a bit busy with school atm, but I'll let you know as soon as I have any updates :)

**Comment by Classytagz** [comment]
Hi Seerge, I followed your steps, and have discovered that it was something related to Nvidia drivers. I uninstalled and reinstalled everything, after which my laptop bluescreened, and while booting it was "fixing corrupted files on C:/" or something.
Right now I haven't had any issues yet, but it seems this problem WAS related to that WMI thing, after i checked event viewer. Any idea what this was?
Thanks for the help so far :)

**Comment by seerge** [comment]
@Classytagz hello. Glad it's resolved. 

Windows is just being windows, with lots of components that sometimes malfunction.

As for WMI thing, if you mean rebuilding [WMI repository](https://github.com/seerge/g-helper/wiki/Troubleshooting#rebuilding-wmi-repository) - then it's something one of the users encountered, and suggested as a fix here, so I just added it to troubleshooting. But he just couldn't launch app at all, as windows was refusing to report laptop model name even. 

Do you use original windows install that came with laptop btw, or a clean one ?

**Comment by Classytagz** [comment]
I use the original Windows install, but removed a bunch of preinstalled software (AC, MyAsus, Aura, etc obviously).
But I'm contemplating installing a clean install of Windows 11, just to start fresh.
Is this smart to do, or will I miss some magic drivers that come preinstalled with the laptop that I won't be able to install seperately, and will cause issues?

**Comment by seerge** [comment]
@Classytagz I don't think you will miss any drivers. Majority gets auto-installed by windows, rest from Asus website (or G-Helper's ``Updates`` section, which is essentially it's mirror). And finally Nvidia / AMD - directly from their websites.

I did a clean install for my G14 2022, and it runs fine.

For G14 2024 (that I took for a couple of weeks to implement slash lighting and some other stuff) - I have kept original windows, and also didn't have any issues.

**Comment by seerge** [comment]
@Classytagz the reason I'v asked about windows install, is cause Asus ones obviously comes with their "own" proprietary 
NVidia drivers, and even if you have installed official ones from NVidia itself after - it could be some leftovers. 

But DDU should clean things up properly :)

**Comment by Classytagz** [comment]
What would be the clean install process, would it look like this?:
1. Install Windows 11
2. Let Windows updates install everything it can
3.download G-Helper, which installs any leftover drivers / chipset stuff
4. Download and install AMD drivers for the iGPU, and Nvidia drivers for the dGPU

**Comment by seerge** [comment]
@Classytagz yes, something like that :)

Ok, i'm closing this as completed as it's resolved and is not an issue with the app in a first place.

Thanks and good luck
