### ISSUE TITLE
Random bluescreens, always when unplugging (G14 2024)

### ISSUE THREAD

**Issue by Classytagz** [seerge/g-helper#2683]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I've been having frequent bluescreens on my G14 2024 (RTX 4070), and I think G-Helper might have something to do with it.
The bluescreen goes away very quickly, so I'm not able to see an error code.

### How to reproduce the bug?

1. Have custom fan profiles enabled
2. Unplug laptop
3. Sometimes bluescreens

### Logs

[log.txt](https://github.com/user-attachments/files/15546116/log.txt)

### Device and Model

Asus Zephyrus G14 GA403UI

### Additional information.

<img width="451" alt="Screenshot 2024-06-04 114602" src="https://github.com/seerge/g-helper/assets/150660804/0aff1da3-9738-4993-9102-c1fa5b158221">
<img width="980" alt="Screenshot 2024-06-04 114637" src="https://github.com/seerge/g-helper/assets/150660804/5471de2e-a376-4ada-b2c8-cd6ee660d492">
<img width="410" alt="Screenshot 2024-06-04 114625" src="https://github.com/seerge/g-helper/assets/150660804/c59a08bf-6325-4107-8906-7acb0bbf31eb">

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.173

### OS

Windows 11 Home | 23H2

**Comment by seerge** [comment]
@Classytagz hello, I see that you have created 2 identical topics. I have answered you in previous one https://github.com/seerge/g-helper/issues/2682 therefore closing this a dublicate
