### ISSUE TITLE
G-helper configured settings doesn't actually runs until you reapply yourself.

### ISSUE THREAD

**Issue by neeestle** [seerge/g-helper#2684]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

First of all, this App helps me completely get rid of BSOD i was getting every other minutes. And for that, thank you with all my heart.
After i did some research how to configure and undervolt my GPU using g-helper, the BSODs are no longer there.
I'm grateful for what you did for making this app, it makes my laptop usable again (even though i've re-clean everything and re-do thermal paste but nothing really solves my BSOD case)

But, somehow i need to reapply all the custom settings i did on g-helper everytime i booted up the laptop.
If i didn't/forgot to do that, my laptop is back to its constant BSOD state again.
So, is there a way to automatically apply settings you've applied before after every restart?

### How to reproduce the bug?

1. Open G-helper
2. Ronfigure settings that suit you best
3. Apply power limits and apply from advanced settings
4. Check list "Run on Startup"
5. Restart laptop
6. G-helper service is started on default, but the setting you've applied before doesn't apply by default until you reapply them/auto apply them.

### Logs

[log.txt](https://github.com/user-attachments/files/15549758/log.txt)

### Device and Model

ASUS TUF A15 FX506II (2021)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.173.0

### OS

Windows 10

**Comment by seerge** [comment]
@neeestle hello, I see that it says that it can’t find a winring dll needed for undervolting when app runs on startup 

```
System.TypeInitializationException: The type initializer for 'Ryzen.SendCommand' threw an exception.
 ---> System.ApplicationException: WinRing OLS_DLL_DRIVER_NOT_FOUND
```

Do run app on startup from the same location ?

Try to run app manually, make sure that undervolting is available (i.e. dll is downloaded from Advanced tab) and then unchecked/check Run on Startup checkbox

**Comment by seerge** [comment]
@neeestle open folder with GHelper.exe, it should be 2 winring files there. If it's only one, please delete manually, restart app - and re-download them via Advanced tab.

**Comment by neeestle** [comment]
@seerge Redownloaded 2 winring files. now it appeared exactly where GHelper.exe is.
but the issue still persists for me. i have to manually reconfigure in CPU tab "Apply Power Limits" after testing with several restarts, even though i've recheck the "Run on Startup".

When windows booted up, G-helper tray icon showed. But, when i check "Fans + Power" settings, the "CPU Boost" option was changed to "Aggressive" like it's default. After i recheck "Apply Power Limits", "CPU Boost" is changed to "Efficient Enabled" as it should be. I had to manually reapply undervolting too just in case both settings are what keeping my laptop alive.

I understand if nothing can be done about this, as i can just reapply it manually everytime. But if there's a way that it'll reapply itself to reduce a slight hassle i'm facing, let me know. 

Also here's an updated log in case you wanna take a look one more time?

[log.txt](https://github.com/user-attachments/files/15565562/log.txt)

thanks in advance.

**Comment by seerge** [comment]
@neeestle hello, app has applied everything that you have saved on start

```
6/4/2024 9:33:49 PM: ------------
6/4/2024 9:33:49 PM: App launched: ASUS TUF Gaming A15 FA506II_FX506II :0.173.0.0en-US.
...
6/4/2024 9:33:54 PM: AutoSetting for Online
6/4/2024 9:33:54 PM: BatteryLimit = 60 : OK   <-- BATTERY LIMIT
6/4/2024 9:33:54 PM: Mode = 0 : OK 
6/4/2024 9:33:54 PM: AuraMode: AMBIENT
6/4/2024 9:33:54 PM: GET CLOCK LIMIT: 0
6/4/2024 9:33:54 PM: powershell nvidia-smi -lgc 0,2100   <-- GPU CLOCK LIMIT
...
6/4/2024 9:33:56 PM: STAPM: 80 OK    <-- POWER LIMITS
6/4/2024 9:33:56 PM: STAPM2: 80 OK
6/4/2024 9:33:56 PM: SLOW: 80 OK
6/4/2024 9:33:56 PM: FAST: 80 OK
6/4/2024 9:33:57 PM: UV: -1 OK   <-- UNDERVOLT TO -1 ?
6/4/2024 9:33:57 PM: GPU clocks set to "(gpuClkMin 0, gpuClkMax 2100)" for GPU 00000000:01:00.0 All done.
6/4/2024 9:33:58 PM: GET GPU CLOCKS: 0, 0
6/4/2024 9:33:58 PM: SET GPU CLOCKS: 100, 0  <--- GPU CLOCK OFFSETS
```

So everything works as it should

As for CPU boost - by default ``fans + power`` just show current state of boost in power plan settings. If you would manually change it for each mode - it would remember that and adjust it automatically each time you select mode (including when app starts)

**Comment by neeestle** [comment]
yeah based on logs everything should be exactly work the way it should be, but idk why if i didn't do it manually reapply each time BSOD will appear again :)

this whole BSOD thing is weird though. I'm just glad someone did better than a multinational company developing such a shitty armoury crate that user have to seek alternative for the better. 

closed.
