### ISSUE TITLE
TDP

### ISSUE THREAD

**Issue by shimi135** [seerge/g-helper#2689]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

im on rog ally and when i set it to 30W it just goes where ever it wants between 10 to 40 W and never mind when i put it to any profile or TDP still not realy putting cap to the TDP also i downloaded the latest version of G helper and didnt help either and when i change fan curve it not realy working i hit 90c even at 100% fan speed at 30-35 W kinda weird

### How to reproduce the bug?

i dont know

### Logs

[log.txt](https://github.com/user-attachments/files/15570157/log.txt)

### Device and Model

Asus Rog Ally

### Additional information.

![Screenshot 2024-06-04 233440](https://github.com/seerge/g-helper/assets/171739475/30023157-57be-4b91-a131-b77df9247d04)

### Armoury Crate

Installed

### Asus Services

8

### Version

0.175.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@shimi135 hello,

App sets all 3 limits (SPL/SPPT/FPPT) to 30W 
```
04/06/2024 23:29:28: PowerLimit A3 = 30 : OK
04/06/2024 23:29:28: PowerLimit A0 = 30 : OK
04/06/2024 23:29:28: PowerLimit C1 = 30 : OK
```

But since you have Armoury Crate next to it running - it may simply override that :)

So you need to either stop it's services from ``Extra``, or choose something one (G-Helper or AC) and use only that.

**Comment by shimi135** [comment]
> @shimi135 hello,
> 
> App sets all 3 limits (SPL/SPPT/FPPT) to 30W
> 
> ```
> 04/06/2024 23:29:28: PowerLimit A3 = 30 : OK
> 04/06/2024 23:29:28: PowerLimit A0 = 30 : OK
> 04/06/2024 23:29:28: PowerLimit C1 = 30 : OK
> ```
> 
> But since you have Armoury Crate next to it running - it may simply override that :)
> 
> So you need to either stop it's services from `Extra`, or choose something one (G-Helper or AC) and use only that.

but armoury crate is set to 30 watts and its still runing on 35-40W its strange like its overide AC

**Comment by seerge** [comment]
@shimi135 if you use. default Turbo in Armoury its 30/45/53w.

Just try to click on Turbo mode again in G-Helper it would set its settings again on top of what AC have set
