### ISSUE TITLE
Directly control keyboard backlight + hotkey suggestions

### ISSUE THREAD

**Issue by lyndonguitar** [seerge/g-helper#269]
For some reason, my keyboard backlight brightness hotkey controls have stopped working for quite some time due to updates, but I can still control them on Armoury Crate (Asus messed up their driver support). I downloaded "[FlowOSD"](https://github.com/albertakhmetov/flowOSD) here, an app similar to this one, and that seems to have keyboard backlight brightness control properly working in and have fixed the issues, but is currently lacking features that **G-Helper** has and has some issues on its own.

**Describe the solution you'd like**
A simple slider or +/- button in the app to control keyboard brightness would be godsend (Ghelper already has some form of this, automated lowering of brightness when on battery, but no direct brightness control)

In addition, the ability to bind FN+F2(lower brightness), F3(increase brightness), F5(fan) would be highly appreciated.

extra suggestions for added actions/functions 
-  A dedicated microphone mute in addition to Volume mute would be useful for those who just want a native M3 function without relying on Asus Services)
- Direct bind to any of the performance modes (Eco, Silent, etc) instead of cycling. or maybe the ability to disable a profile in the cycle roster.
- An option to "tether" performance modes to any GPU modes. (e.g. Eco "tethered" to Silent, while Standard can be "tethered" to Turbo/Balance)

**Describe alternatives you've considered**
Armoury Crate backlight control works, but would like an alternative lightweight app to use like yours
FlowOSD has brightness controls, but is currently lacking on other useful functions like PPT control and battery limiter and is not as stable as yours

Anyway that's all, thanks a lot for this app!

**Comment by seerge** [comment]
Hotkeys are handled by asus optimization service (as readme says), you may want to reinstall it from scratch as explained here https://github.com/seerge/g-helper/discussions/145#discussioncomment-5431447 if it doesn't work by some reason.

There is no reason to implement functionality of this service completely in app, as then it will start conflicting with the service fighting for same things (+99% of the users use it). Same applies to micrphone mute / etc https://github.com/seerge/g-helper#how-do-i-set-mute-microphone-to-m3

**Comment by lyndonguitar** [comment]
> Hotkeys are handled by asus optimization service (as readme says), you may want to reinstall it from scratch as explained here [#145 (comment)](https://github.com/seerge/g-helper/discussions/145#discussioncomment-5431447) if it doesn't work by some reason.
> 
> There is no reason to implement functionality of this service completely in app, as then it will start conflicting with the service fighting for same things (+99% of the users use it). Same applies to micrphone mute / etc https://github.com/seerge/g-helper#how-do-i-set-mute-microphone-to-m3

Thank you for the tip. I have just about done anything I can do to try and fix this only short of a BIOS update, and unfortunately it still doesn't work with mine. (reinstalled it multiple times, new OS, even installed older versions going back to v2), eventually I end up with v3 still without backlight control. )

I tried it one more time in light of your suggestion, to no avail, but still works in armoury crate so yeah, but I wanna uninstall that. The only saving grace I have is via third party apps.  Anyway I hope you have plans of completely eliminating the need for asus optimization service.

Also, I do have other suggestions in the post I hope you can consider. Thank you.

**Comment by seerge** [comment]
@lyndonguitar do other hotkeys work ? like display brightness ? (fn+f7 / fn+f8)

**Comment by lyndonguitar** [comment]
> 

other hotkeys work, except for the brightness up and down.

**Comment by lyndonguitar** [comment]
> 

thanks alot man, I just tested it, and it works, I can finally change my brightness

there are 11 levels in the app, my backlight has 4 levels of brightness and works with the first 4 levels
1 - off
2- low
3- mid
4- high
5 to 11 - off

The only thing not working is ""lower backlight brightness when plugged", because it turns my backlight completely off when unplugged (in all brightness settings)

**Comment by seerge** [comment]
@lyndonguitar i just forgot to set a correct limit for a slider :) it's indeed OFF + 3 levels of brightness :) I will include this changes in upcoming v0.55 then

Lower backlight brightness is indeed sets brightness to 0 (as some other users previously asked) i may think about better UI solution to let user select desired brightness for battery tho :)
