### ISSUE TITLE
Ability to switch power profiles when certain application is opened

### ISSUE THREAD

**Issue by MrTheenD** [seerge/g-helper#2693]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Whenever I'm gaming I always find myself disabling CPU Boost feature found in my 7940HS as it adds virtually no performance benefit while also keeping temps low.

### Describe the solution you'd like

A simple power profile switch whenever a certain application is detected.

### Describe alternatives you've considered

I think it's a feature also found in AC but can't use concurrently with G-Helper.

### Device and Model

Asus TUF A15 FA507XI

**Comment by seerge** [comment]
@MrTheenD hello, I was answering this multiple times already.

G-Helper does not monitor your system and applications that you launch in realtime anyhow.

But you (already) can very easily switch between profiles (backwards and forwards) with multiple hotkeys 
https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings

Thanks
