### ISSUE TITLE
Discharge function for G533qs

### ISSUE THREAD

**Issue by code-Redot** [seerge/g-helper#2695]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

i noticed the issue since 0.165 not sure if it existed before,
the battery charge limit used to discharge when you lower the value. not anymore.

### How to reproduce the bug?

open the G-Helper application
move the battery charge slider to a higher value
once charged to the matching value
move the battery charge slider to a lower value
device will not discharge.

### Logs

[log.txt](https://github.com/user-attachments/files/15719002/log.txt)

### Device and Model

Asus Strix G533QS

### Additional information.

the Application states that my battery health is 79%, it might be a my device battery issue due to it's health but raised the bug ticket just in case.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.173

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@code-Redot hello, 

G-Helper does not start or stop charging of your device :)  It can only set a limit with a simple command and then firmware is supposed to hold it.

There is nothing changed in that regard in 0.165 (you are free to download older version and try)

Some models do not support some (custom) charge limits, please check FAQ
https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working

Thanks.
