### ISSUE TITLE
G533QS Highlight keyboard lighting mode extraFN buttons green light

### ISSUE THREAD

**Issue by code-Redot** [seerge/g-helper#2696]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

only on highlight keyboard lighting mode the rest are tested and working as intended; once the highlight mode is selected no matter what color you pick the extra function buttons row (volume down/up, mic control, fan speed, rog mode) all but the volume down are lit in a very dim green.

### How to reproduce the bug?

open G-helper application
change the laptop keyboard light mode to highlight.
either turn off room lights or cover the extra function row BTNs to see a dim green light on all but volume down

![20240607_101041](https://github.com/seerge/g-helper/assets/62650681/b01c7b02-4344-4ab0-b0ca-d3aef68ba066)
![20240607_100810](https://github.com/seerge/g-helper/assets/62650681/95fa4605-4fe4-4b45-995d-bac78fea1151)

### Logs

[log.txt](https://github.com/user-attachments/files/15721563/log.txt)

### Device and Model

Asus Strix G533QS

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.173

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@code-Redot hello, 

It is very difficult to understand what you are trying to say here. But I think your question is a duplicate https://github.com/seerge/g-helper/issues/1329

Please check my explanation there

Thanks.
