### ISSUE TITLE
Gpu Memory Slider

### ISSUE THREAD

**Issue by Domilanci** [seerge/g-helper#2698]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Good afternoon, 
as my video card is stable with an increase of 500MHz on the memory and it would seem that a good part of the 4000 series RTX cards reach +1000MHz without problems, is it possible to increase the offset slide?

### Describe the solution you'd like

Increase the memory offset slider from +500MHz max, to at least +1000MHz

### Device and Model

Asus TUF A15 FX507 Ryzen 9 7940HS, rtx4050

**Comment by seerge** [comment]
@Domilanci hello, this is already possible, but hidden from regular users intentionally. 

Please check readme on how to do that 
https://github.com/seerge/g-helper/wiki/Power-user-settings#higher-maximum-and-minimum-gpu-clock--memory-offsets

Thanks :)

**Comment by Domilanci** [comment]
You are the best!, thanks so much, also for the response speed. 
Have a nice day

**Comment by Domilanci** [comment]
There is a ploblem: in the json file, there is no max or min config. this is what is showed in the config.json.bak:
{
  "performance_mode": 1,
  "performance_1": 1,
  "gpu_mode": 1,
  "internal_display": "B156HAN15.H ",
  "screen_max": 144,
  "frequency": 144,
  "overdrive": 1,
  "charge_full": 0,
  "mid_fan": 0,
  "xgm_fan": 0,
  "fan_profile_cpu_2": "1E-3C-41-42-47-4B-4C-62-00-03-0C-0C-16-22-22-29",
  "fan_profile_gpu_2": "1E-3C-41-42-47-4B-4C-62-00-08-11-11-1D-26-26-2D",
  "limit_total_2": 45,
  "limit_slow_2": 45,
  "limit_cpu_2": 15,
  "limit_fast_2": 65,
  "fan_profile_cpu_0": "1E-3A-3D-40-48-4D-51-62-00-08-11-16-22-29-30-45",
  "fan_profile_gpu_0": "1E-3A-3D-40-48-4D-51-62-00-0C-16-1D-26-2D-34-4A",
  "limit_total_0": 55,
  "limit_slow_0": 55,
  "limit_cpu_0": 61,
  "limit_fast_0": 70,
  "auto_uv_2": 1,
  "cpu_temp_2": 85,
  "cpu_uv_2": -25,
  "igpu_uv_2": 0,
  "auto_uv_0": 0,
  "cpu_temp_0": -1,
  "cpu_uv_0": 0,
  "igpu_uv_0": 0,
  "fan_profile_cpu_1": "14-3F-44-48-4C-50-54-62-11-1A-22-29-34-43-51-5A",
  "fan_profile_gpu_1": "14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F",
  "limit_total_1": 80,
  "limit_slow_1": 80,
  "limit_cpu_1": 15,
  "limit_fast_1": 80,
  "auto_uv_1": 1,
  "cpu_temp_1": 95,
  "cpu_uv_1": -25,
  "igpu_uv_1": 0,
  "auto_apply_power_2": 1,
  "auto_apply_power_0": 0,
  "auto_apply_power_1": 1,
  "performance_0": 2,
  "screen_auto": 1,
  "gpu_auto": 0,
  "gpu_boost_2": 25,
  "gpu_temp_2": 80,
  "gpu_boost_0": 25,
  "gpu_temp_0": 87,
  "gpu_boost_1": 25,
  "gpu_temp_1": 85,
  "aura_mode": 0,
  "fn_lock": 0,
  "fnc": "",
  "keyboard_brightness": 2,
  "aura_color_custom": "16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215",
  "aura_color": -3604481,
  "keyboard_awake": 1,
  "keyboard_boot": 1,
  "keyboard_sleep": 0,
  "keyboard_shutdown": 1,
  "keyboard_awake_bar": 1,
  "keyboard_boot_bar": 1,
  "keyboard_sleep_bar": 1,
  "keyboard_shutdown_bar": 1,
  "keyboard_awake_lid": 1,
  "keyboard_boot_lid": 1,
  "keyboard_sleep_lid": 1,
  "keyboard_shutdown_lid": 1,
  "keyboard_awake_logo": 1,
  "keyboard_boot_logo": 1,
  "keyboard_sleep_logo": 1,
  "keyboard_shutdown_logo": 1,
  "no_overdrive": 0,
  "keyboard_brightness_ac": 2,
  "auto_uv_3": 1,
  "cpu_temp_3": 95,
  "cpu_uv_3": -25,
  "igpu_uv_3": 0,
  "topmost": 1,
  "charge_limit": 80,
  "gpu_clock_limit_3": 3000,
  "fan_max_1": 71,
  "auto_apply_2": 0,
  "auto_apply_1": 0,
  "gpu_core_1": 150,
  "gpu_memory_1": 500,
  "auto_apply_0": 0,
  "fan_rpm": 1,
  "igpu_uv_4": 0,
  "auto_uv_4": 1,
  "cpu_temp_4": 98,
  "cpu_uv_4": -25,
  "gpu_clock_limit_4": 3000,
  "toggle_clamshell_mode": 1,
  "visual": 11,
  "m4": "",
  "auto_uv_5": 1,
  "cpu_temp_5": 95,
  "cpu_uv_5": -30,
  "igpu_uv_5": 0,
  "color_temp": 50,
  "fnv": "mute",
  "fnf4": "",
  "bw_icon": 0,
  "auto_boost_1": 2,
  "skip_version": "0.170",
  "aura_speed": 1,
  "gpu_clock_limit_1": 3000,
  "powermode_2": "00000000-0000-0000-0000-000000000000",
  "gpu_core_0": 0,
  "gpu_memory_0": 0,
  "gpu_core_2": 0,
  "gpu_memory_2": 0,
  "gpu_clock_limit_2": 3000
}

**Comment by seerge** [comment]
@Domilanci you need to add that line (as explained in readme)
