### ISSUE TITLE
G-helper anticheat interference

### ISSUE THREAD

**Issue by plastics-eater** [seerge/g-helper#2699]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I noticed G-helper cause issues with some anticheat software, I have also expierenced other odd issues with G-helper (I wont detail them unless this issue is replicable), so its possible this is more of an issue with my hardware specifically.

### How to reproduce the bug?

1. Launch G-helper 
2. Launch Helldivers 2 (Gameguard), or The Finals (EAC) (the two games I tested)
3. The Finals will crash with a "certificate check failed" error while Helldivers 2 will crash with a file installation error (The Finals will start working after a restart (without G-helper running), while Helldivers 2 will (usually) work without a restart.

### Logs

[log.txt](https://github.com/user-attachments/files/15747195/log.txt)

### Device and Model

G14 GA402R

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

0.173

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@plastics-eater hello, G-Helper does not run your hardware in realtime anyhow. So I really doubt that.

I have same device as you do (G14 2022) and I was playing Finals (EAC) before without any issues same as bunch of other games with EAC . 

It's very simple to test - quit G-Helper and run your games again.

Thanks

**Comment by seerge** [comment]
P.S. I see that you use quite aggressive CPU undervolting that can simply cause CPU to crash. So I would advice not to do that.

**Comment by IceStormNG** [comment]
It could be WinRing0 which is used for undervolting. Some Anti-cheats are configured to not allow this. EAC is not always the same as game devs can configure it differently
Some ACs like Vanguard or ACE will simply unload the driver, and may cause BSODs or other stuff.

**Comment by seerge** [comment]
@IceStormNG yeah, but then it should be block that in all cases. I just tried to run Finals again as well as Apex Legends, and it runs fine on exact same device and even with some low (stable for my specific CPU) undervolting.

But when I crank undervolting too much (to -20 on my unit). I get almost guaranteed game-crash in pretty much any game, even something offline where there is no anticheats :) And reason is obviously - I just udervolt too much.

**Comment by IceStormNG** [comment]
Well, that for sure. If you undervolt too much, then everything will crash.

Though, the "certificate check failed" message is what is weird. Sure, it could be a calculation error due to unstable CPU. 
The AC in Helldivers is known to be a piece of junk though.

**Comment by plastics-eater** [comment]
Ok I just wanted to confirm, thanks.

**Comment by seerge** [comment]
@plastics-eater does resetting undervolting solve your problem ? :)

**Comment by plastics-eater** [comment]
Suprisingly yes, I had a very modest undervolt (-18mv) so I guess this means I lost the silicon lottery lol.

**Comment by seerge** [comment]
@plastics-eater mine crashes starting from -10 :) so you are more lucky.
