### ISSUE TITLE
[Feature Request] Game Visual / Color Profile

### ISSUE THREAD

**Issue by MrxSiN** [seerge/g-helper#27]
Im using G15 2021 and I notice, screen would look much more accurate with Default setting in Game Visual in armoury crate. Will it be possible to port it here?

**Comment by seerge** [comment]
I think you just need to save that windows color profile and set it manually. Once and forever.

**Comment by MrxSiN** [comment]
There already laptop specific windows color profiled installed. However, default game visual overwrite or somehow make a minor correction to it. There some color shifting after booting up windows when "Default" Game Visual pop up appear.

**Comment by seerge** [comment]
It just applies one more profile, try to search for GameVisual folder on your computer somewhere in Documents or Appdata (i don't remember exactly, cause uninstalled armory long time ago)]

Inside you will see something like this (https://imgur.com/a/QCxVzmf)

I can't add it to the app, cause profiles are specific for your laptop model.

**Comment by seerge** [comment]
Added in latest release https://github.com/seerge/g-helper/releases
