### ISSUE TITLE
[Feature request] Export/import fan curve and power settings

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#270]
No really necessary request, of course. I just saw a bunch of Reddit users who are sharing curves to compare and find the best for themselves.
It could be nice to have some user-friendly way to export and import, instead of using screenshots or manually copied files (with all settings, actually).
Thanks!

**Comment by seerge** [comment]
@ke1ne you can just save config file from ``%AppData%\GHelper`` (or take fan curve from there). Why do you need multiple fan curves per each mode in a first place ?

**Comment by ke1ne** [comment]
@seerge For me, it's not needed in every-day life at all. It's more control/performance/tweaking maniac stuff from community talks experience, when people are making fun showing their profiles, etc.

**Comment by seerge** [comment]
@ke1ne well, i'm not a big fan of overloading UI with features that 99% of the users won't use (especially considering that it can be done via configs) :)

**Comment by ke1ne** [comment]
@seerge sure, no problem. thank you for the app
