### ISSUE TITLE
When there is a new version message there is no way to see what's changed

### ISSUE THREAD

**Issue by mixtur** [seerge/g-helper#2701]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

When there is a new version message there is no way to see what's changed, other than going to the github manually. While when there isn't a new version, there is a link that leads to releases which does contain the cangelog.

My point is. The changelog is accessible when it is not needed. And unaccessible when it is needed. Which kind of makes no sense.

### Describe the solution you'd like

Do not replace the changelog link with download link. There must be a way to have both.

### Describe alternatives you've considered

One could of course manually go to the github and see the changelog oneself, but since you bothered to do it once, why not do it again.

### Device and Model

Irrelevant, but G713-PV 2023

**Comment by seerge** [comment]
@mixtur hello, you already have both. 

Update alert appears only for a "final" releases (pushed to everyone) and it's intentionally simple prompt to auto-update.
If you skip / reject this prompt, you will see a new version in red linking to Github releases page highlighting what's new.

Thanks.
