### ISSUE TITLE
Eco no Monitor

### ISSUE THREAD

**Issue by Calin201** [seerge/g-helper#2705]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Well, after some debugging i made an expected but unwanted discovery, my external monitor( i can not test with other cables) which has a dp to usb-c adapter is not recognised while i have my gpu in eco mode(eco disables the external gpu to function so, practicaly yes it works xD) but in this case it should only disable it while no external monitor is plugged in.

### How to reproduce the bug?

1. Change the gpu mode to eco
2. Enable the 

### Logs

10.06.2024 23:08:11: this->BiosDataStatus  = 0   ReadResult  = 0  Parsing version = 128 Use Method = 0   bios size = 0 CRCCheck Error CCTAPI_ERRORCODE = 0 CCT_Init  result = 0 Channel RGB[0]: smoothLv = 64 scatterLv = 0 diff = 0 lut type: 0 ; HIT: LutSmooth8Bit() failed!!! scale: 1.000000, Scale TH: 0.100000, nIndex: 26 New ScaleTH: 0.215686 New scale: 1.000000 outlut: [1.000000, 0.925490, 0.784314] Get dll path: [C:\WINDOWS\system32\DriverStore\FileRepository\asussci2.inf_amd64_07d00c3f6cf68f6e\ASUSOptimization\AsusCCT.DLL] Get dll folder: [C:\WINDOWS\system32\DriverStore\FileRepository\asussci2.inf_amd64_07d00c3f6cf68f6e\ASUSOptimization] UIGain: 2.000000 lutDcModeScale: 1.000000 Interval: 2.000000 RDLevels: 5.000000 index: 0.500000 Param: 7, Gamut mode: FFFF Gamut mapping process exit with return code 0
10.06.2024 23:08:11: dGPU not found
10.06.2024 23:08:12: CPU: 8 - AMD Ryzen 7 6800H with Radeon Graphics          - AMD64 Family 25 Model 68 Stepping 1
10.06.2024 23:08:12: AutoSetting for Online
10.06.2024 23:08:12: BatteryLimit = 100 : OK
10.06.2024 23:08:12: Optimization service is running
10.06.2024 23:08:12: Eco flag : 1
10.06.2024 23:08:12: Mux flag : 1
10.06.2024 23:08:12: \\?\DISPLAY#NCP004D#5&c7ac76c&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
10.06.2024 23:08:12: \\?\DISPLAY#NCP004D#5&c7ac76c&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
10.06.2024 23:08:12:  HDR: False 8 4 True
10.06.2024 23:08:12: Mode = 1 : OK
10.06.2024 23:08:12: Init 19B6: 5D-B9
10.06.2024 23:08:12: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
10.06.2024 23:08:12: Init 19B6: 5D-05-20-31-00-1A
10.06.2024 23:08:12: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
10.06.2024 23:08:13: AuraMode: AuraRainbow
10.06.2024 23:08:13: USB 19B6: 5D-B3-00-03-63-FE-FE-EB-00-00-FF-FF-FF-00-00-00-00
10.06.2024 23:08:13: USB 19B6: 5D-B5-00-00-00
10.06.2024 23:08:13: USB 19B6: 5D-B4
10.06.2024 23:08:13: Monitor Power On
10.06.2024 23:08:13: Lid Open
10.06.2024 23:08:13: Lid 19B6: 5D-BA-C5-C4-03
10.06.2024 23:08:13: Auto 19B6: 5D-BA-C5-C4-03
10.06.2024 23:08:14: PowerLimit C0 (GPU BOOST) = 25 : OK
10.06.2024 23:08:14: PowerLimit C2 (GPU TEMP) = 85 : OK
10.06.2024 23:08:14: CPU Temp: 85 OK
10.06.2024 23:08:14: APU Temp: 85 OK
10.06.2024 23:08:16: WMI event 192
10.06.2024 23:08:26: HID Device Event: Checking for new ASUS Mice
10.06.2024 23:10:09: WMI event 56
10.06.2024 23:10:09:  HDR: False 8 4 True
10.06.2024 23:10:13: Running eco command 0
10.06.2024 23:10:13: GPUEco = 0 : OK
10.06.2024 23:10:13: Eco flag : 0
10.06.2024 23:10:13: Mux flag : 1
10.06.2024 23:10:13: \\?\DISPLAY#NCP004D#5&c7ac76c&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
10.06.2024 23:10:13: \\?\DISPLAY#NCP004D#5&c7ac76c&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
10.06.2024 23:10:13:  HDR: False 8 4 True
10.06.2024 23:10:17: dGPU not found
10.06.2024 23:10:17: Display configuration changed.
10.06.2024 23:10:17: Internal screen off
10.06.2024 23:10:48: ------------
10.06.2024 23:10:48: App launched: ROG Strix G513RC_G513RC :0.173.0.0en-US
10.06.2024 23:10:48: Matrix control device was not found on your machine.
10.06.2024 23:10:48: Internal screen off
10.06.2024 23:10:48: NVIDIA GeForce RTX 3050 Laptop GPU
10.06.2024 23:10:49: CPU: 8 - AMD Ryzen 7 6800H with Radeon Graphics          - AMD64 Family 25 Model 68 Stepping 1
10.06.2024 23:10:49: AutoSetting for Online
10.06.2024 23:10:49: BatteryLimit = 100 : OK
10.06.2024 23:10:49: Optimization service is running
10.06.2024 23:10:49: Eco flag : 0
10.06.2024 23:10:49: Mux flag : 1
10.06.2024 23:10:49: Internal screen off
10.06.2024 23:10:49: Init 19B6: 5D-B9
10.06.2024 23:10:49: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
10.06.2024 23:10:49: Init 19B6: 5D-05-20-31-00-1A
10.06.2024 23:10:49: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
10.06.2024 23:10:49: AuraMode: AuraRainbow
10.06.2024 23:10:49: USB 19B6: 5D-B3-00-03-63-FE-FE-EB-00-00-FF-FF-FF-00-00-00-00
10.06.2024 23:10:49: USB 19B6: 5D-B5-00-00-00
10.06.2024 23:10:49: USB 19B6: 5D-B4
10.06.2024 23:10:49: Monitor Power On
10.06.2024 23:10:49: Lid Open
10.06.2024 23:10:49: Mode = 1 : OK
10.06.2024 23:10:50: Auto 19B6: 5D-BA-C5-C4-03
10.06.2024 23:10:51: PowerLimit C0 (GPU BOOST) = 25 : OK
10.06.2024 23:10:51: PowerLimit C2 (GPU TEMP) = 85 : OK
10.06.2024 23:10:55: Internal screen off
10.06.2024 23:10:57: Latest version 0.173.0.0
10.06.2024 23:10:57: Design Capacity: 55997mWh, Full Charge Capacity: 46375mWh, Health: 0,828169366216047288247584692%
10.06.2024 23:12:40: Stopped: EpicGamesLauncher
10.06.2024 23:12:40: Stopped: ASUSSmartDisplayControl
10.06.2024 23:12:40: Running eco command 1
10.06.2024 23:12:40: Display configuration changed.
10.06.2024 23:12:40: GPUEco = 1 : OK
10.06.2024 23:12:40:  HDR: False 8 4 True
10.06.2024 23:12:41: Eco flag : 1
10.06.2024 23:12:41: Mux flag : 1
10.06.2024 23:12:41: \\?\DISPLAY#NCP004D#5&c7ac76c&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
10.06.2024 23:12:41: \\?\DISPLAY#NCP004D#5&c7ac76c&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
10.06.2024 23:12:41:  HDR: False 8 4 True
10.06.2024 23:12:45: Running eco command 0
10.06.2024 23:12:53: GPUEco = 0 : OK
10.06.2024 23:12:53: Eco flag : 0
10.06.2024 23:12:53: Mux flag : 1
10.06.2024 23:12:53: \\?\DISPLAY#NCP004D#5&c7ac76c&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
10.06.2024 23:12:53: \\?\DISPLAY#NCP004D#5&c7ac76c&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
10.06.2024 23:12:53:  HDR: False 8 4 True
10.06.2024 23:12:55: Display configuration changed.
10.06.2024 23:12:55: Internal screen off
10.06.2024 23:12:56: NVIDIA GeForce RTX 3050 Laptop GPU

### Device and Model

Asus Rog G513rc

### Armoury Crate

Uninstalled

### Asus Services

8

### Version

0.173

### OS

Windows 11

**Comment by seerge** [comment]
@Calin201 hello,

When you set Eco mode and disable dGPU - all ports connected to it obviously won't work as well (like HDMI and one of USB-C). That's absolutely normal and that's how your computer works.

You need to use your second USB-C that is connected to iGPU. Or just use Standard mode when dGPU is enabled.

Thanks.
