### ISSUE TITLE
The battery life for me is very amazing now.....

### ISSUE THREAD

**Issue by Minemetero** [seerge/g-helper#2706]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![Screenshot 2024-06-11 090328](https://github.com/seerge/g-helper/assets/156386015/f62372de-16d7-430c-bc16-efcb9be80b55)
The battery life is 100.1%; it is not important, but it is still a bug.

### How to reproduce the bug?

Actually, I don't know, it just happened...

### Logs

It doen't really need log right?

### Device and Model

ROG Zephyrus G16 GU605MV

### Armoury Crate

Installed

### Asus Services

None

### Version

0.176.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
Battery health can be above 100%, its normal
