### ISSUE TITLE
Fn Key not functioning

### ISSUE THREAD

**Issue by UnforeseenHuman** [seerge/g-helper#2707]
Hi, 

Recently my fn key for most of F row keys are not working and it's weird. I first thought it was the Fn Lock feature itself. However it has been off the entire time, i also tried the FN + ESC, nothing changed. I only realised it had something to do with G-Helper, when i downloaded the pre-release version of 176 from the existing version 173. 

When i did that all the F keys (F1 - F12) began to work with the FN key, however it will work about 5 minutes and it will go back to the same issue. I tried redownloading G-Helper and the same happened again, where it will work for 5 minutes and go back to the same issue. 

The only F key that works with the Fn key at the moment is the F6 key which is the snapshot. Other than that everything does not work even my brightness keys (F6 & F7).

I hope someone knows how to fix this and any help will be appreciated. Thank you.

**Comment by seerge** [comment]
@UnforeseenHuman hello, please fill in issue [template with all the details. ](https://github.com/seerge/g-helper/issues/new?assignees=&labels=&projects=&template=bug_report.yml) 

I have recently lost my mind reading skills, and therefore can't assist you without any logs  :)

Thanks.
