### ISSUE TITLE
Fn Key + (F1 to F12) not functioning sometimes 

### ISSUE THREAD

**Issue by UnforeseenHuman** [seerge/g-helper#2709]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi,

Recently my fn key for most of F row keys are not working and it's weird. I first thought it was the Fn Lock feature itself. However it has been off the entire time, i also tried the FN + ESC, nothing changed. I only realised it had something to do with G-Helper, when i downloaded the pre-release version of 176 from the existing version 173.

When i did that all the F keys (F1 - F12) began to work with the FN key, however it will work about 5 minutes and it will go back to the same issue. I tried redownloading G-Helper and the same happened again, where it will work for 5 minutes and go back to the same issue.

The only F key that works with the Fn key at the moment is the F6 key which is the snapshot. Other than that everything does not work even my brightness keys (F6 & F7).

I have completely stopped the Asus Services via Extra as well. 

I hope someone knows how to fix this and any help will be appreciated. Thank you.

### How to reproduce the bug?

1. Download G-Helper 
2. Fn Key and row above functions properly for a few minutes 
3. Try to click Fn + (F1 to F12) nothing seems to work 
4. Tried this a few times and result has been the same

### Logs

[Log G-Helper.pdf](https://github.com/user-attachments/files/15793464/Log.G-Helper.pdf)

### Device and Model

Asus Zephyrus G15 GA503RM

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.173

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@UnforeseenHuman hello,

I see that when app gets notified about ``FN+F`` key presses, it runs actions properly

```
10/06/2024 22:43:44: Key: 197 <--- BACKLIGHT DOWN 
10/06/2024 22:43:44: HotKey 19B6|63: 5A-BA-C5-C4-01
10/06/2024 22:43:44: Key: 196 <--- BACKLIGHT UP 
10/06/2024 22:43:44: HotKey 19B6|63: 5A-BA-C5-C4-02
10/06/2024 22:43:46: Key: 32 <--- BRIGHTNESS UP
10/06/2024 22:43:46: Brightness = 32 : 0
```

But after some time keyboard just terminates connection, and stops sending any hotkeys to the app
```
10/06/2024 22:45:12: Listener exited: Operation failed after some time.
```

Furthermore, keyboard even stops accepting backlight commands at all (from automatic backlight ON / OFF by timeout)

```
11/06/2024 17:31:52: Auto 19B6|63: 5A-BA-C5-C4-01
11/06/2024 17:32:43: Error setting feature 63
\\?\hid#vid_0b05&pid_19b6&col05#7&2635b6bc&0&0004#{4d1e55b2-f16f-11cf-88cb-00111
1000030}: 5A-BA-C5-C4-00 SetFeature failed.
```

----

1. Does restarting app help? Cause if not - it could be just some strange hardware hiccups of the keyboard itself.
2. Try [hardware reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hardware-reset--cmos-reset), may be that will help somehow

Thanks

**Comment by UnforeseenHuman** [comment]
Hi, 

Thank you for help as I was half way through the hardware reset the key started working properly again. I am now reinstalling my drivers and will still monitor the behaviour of the key itself. However for now the issue has resolved by the uninstalling and reinstalling the drivers itself. Thank you once again for helping me sort this out quickly.

**Comment by seerge** [comment]
@UnforeseenHuman Ok, great. Do I understand correctly that it’s resolved for you now? :)

**Comment by UnforeseenHuman** [comment]
yes it has, appreciate it.
