### ISSUE TITLE
[Bug] There is a void between GPU modes v0.54

### ISSUE THREAD

**Issue by marcelomijas** [seerge/g-helper#271]
**Describe the bug**
In the new version v0.54, now there is a void between GPU modes Standard (Estándar) y Optimized (Optimizado). Now the grid is 1x4.

**Expected behavior**
In v0.53 the grid was 1x3, there were no voids between Standard and Optimized.

**App Logs**
```
19/04/2023 17:46:29: ------------
19/04/2023 17:46:29: App launched: ROG Zephyrus G14 GA401IV_GA401IV
19/04/2023 17:46:29: AutoSetting for Offline
19/04/2023 17:46:29: BatteryLimit = 100 : OK
19/04/2023 17:46:29: BatteryLimit = 100 : OK
19/04/2023 17:46:29: PerformanceMode = 2 : OK
19/04/2023 17:46:29: FanCPU = 14-28-31-3B-47-4B-4C-62-00-00-01-09-16-22-22-29 : OK
19/04/2023 17:46:29: FanGPU = 14-28-32-3B-47-4B-4C-62-00-00-01-09-1D-26-26-2D : OK
19/04/2023 17:46:29: Boost 0
19/04/2023 17:46:29: Eco flag : -65536
19/04/2023 17:46:29: Mux flag : -65536
19/04/2023 17:46:31: Screen = 60Hz : OK
19/04/2023 17:46:31: ScreenOverdrive = 0 : 0
19/04/2023 17:46:31: Monitor Power On
19/04/2023 17:50:18: GPUEco = 1 : 0
```

**Screenshots or screencasts**
![imagen](https://user-images.githubusercontent.com/62946623/233130365-98ce6a19-5e64-4083-92c9-e239ed58ee8e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Laptop model: ROG Zephyrus G14 GA401IV

**Asus software**
- Asus Optimization Service

**Additional context**
Is this a bug or a feature? Since my model doesn't support GPU modes it doesn't matter anyways... and those non-functioning options do not bother me a lot...

**Comment by seerge** [comment]
@marcelomijas thanks for spotting as usual :)
Should be fixed here (and i have re-uploaded it to 0.54)
[GHelper.zip](https://github.com/seerge/g-helper/files/11275206/GHelper.zip)

**Comment by marcelomijas** [comment]
@seerge thanks, but still the same

**Comment by seerge** [comment]
@marcelomijas oke, can you try this one ? it's all because i have added 5th button for XG Mobile support ...

[GHelper.zip](https://github.com/seerge/g-helper/files/11275521/GHelper.zip)

**Comment by marcelomijas** [comment]
@seerge Perfect. Solved! :)
