### ISSUE TITLE
Constant higher GPU fan?

### ISSUE THREAD

**Issue by SynStark** [seerge/g-helper#2710]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I've noticed since the last 2-3 updates that the gpu fan runs at 2500rpm all the time making it quite hot and noisy. It used to be around the 1700-1900 range and cool and quite. I'm using the program on Balanced mode with default setting without applying any power limit or custom fan curves.

<img width="421" alt="Screenshot 2024-06-12 025508" src="https://github.com/seerge/g-helper/assets/140649954/d423cba3-b744-45e5-8ac5-b2db3ace4810">

### How to reproduce the bug?

N/A

### Logs

N/A

### Device and Model

Scar 18 G834JY

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.173

### OS

11

**Comment by seerge** [comment]
@SynStark hello, as I was explaining [to you before](https://github.com/seerge/g-helper/issues/2358) fans are controlled by BIOS (assuming you don't use the experimental build with manual fan control and manual curve there)

If you don't set any custom fan curves / limits - fan behavior is default for that specific mode. It could be that BIOS is programmed to run fans a bit faster if ``Ultimate`` mode is ON.

If you have specific version since when it's supposedly changed - please post it.

Thanks

**Comment by seerge** [comment]
@SynStark any updates here ?

**Comment by SynStark** [comment]
> @SynStark any updates here ?

Sorry just saw your question.

Unfortunately, no. I'm on Bios 328 now and tried rolling back the older GHelper versions but same issue, so now I'm trying to find and download Bios 326 since that one was working amazing on the temps and fans but I cannot find it anywhere unfortunately even on the Asus website it jumps from 325 to 328.

**Comment by seerge** [comment]
@SynStark if app version does not affect it (which is expected), it's extremely likely something that Asus has changed with their BIOS release.

I can't affect it anyhow.

You can either try to set a custom fan curve or use experimental build with manual fan control if fan speed bothers you so much. 

Or use older BIOS from asus https://rog.asus.com/laptops/rog-strix/rog-strix-scar-18-2023-series/helpdesk_bios/ but I see that they have removed 326 by some reason, and kept only 325 :)

Closing as not planned, as default fan behavior does not depend on the app.

Thanks and good luck.
