### ISSUE TITLE
Fans are not working and temp is way up

### ISSUE THREAD

**Issue by erfanasbari** [seerge/g-helper#2711]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Plugged in, Turbo mode, No custom fan curves, CPU Fan and GPU Fan is not running (0 RPM) but cpu temp is 96
When I restart the system it goes back to working normal

### How to reproduce the bug?

I'm not completely sure but i think this bug happens when I switch GPU Mode. I'm not sure which mode but I think when I Switch to eco mode this happens.

### Logs

[log.txt](https://github.com/user-attachments/files/15801042/log.txt)

### Device and Model

ASUS TUF Gaming F17 FX706HEB

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.173.0

### OS

Windows 11

**Comment by seerge** [comment]
@erfanasbari hello, G-Helper does not control your fans [they are controlled by BIOS ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds). Furthermore your device does not even support any custom fan curves.

If fans are not working, you can try to reboot or do a [hardware reset ](https://github.com/seerge/g-helper/wiki/Troubleshooting#hardware-reset--cmos-reset). That may help.

If you are not happy with how BIOS controls fans you can try [experimental build with manual fan control](https://github.com/seerge/g-helper/discussions/2272)

Thanks.
