### ISSUE TITLE
Low Priority - Support for Windows 11 Dynamic Lighting

### ISSUE THREAD

**Issue by lucidnx** [seerge/g-helper#2712]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

-

### Describe the solution you'd like

Windows 11 added feature "Dynamic Lighting", it can sync effects/colors on all supported devices. Is there any way to add support for our devices (Keyboards, mouses, etc..) via G-Helper?

### Device and Model

G402RK

**Comment by seerge** [comment]
@lucidnx hello, this is a dublicate of https://github.com/seerge/g-helper/issues/2380

Specifically for your device - I don't think it's possible to add it. Cause to support dynamic lighting it needs to be implemented on firmware level to match new microsoft protocol for that.

For new devices - I can try to copy some data, but since issues stayed open for like 2 months and no one bothered to record payloads, I assume it's not that important :)

**Comment by lucidnx** [comment]
got it, thanks :)

**Comment by lucidnx** [comment]
@seerge oh, why did you returned 2024 model?

**Comment by seerge** [comment]
@lucidnx cause it costs 2400 EUR :)

**Comment by lucidnx** [comment]
> @lucidnx cause it costs 2400 EUR :)

Yeah, but it's same as 2022 model. I saw some tests, perfomance is almost identical? It seems that they sacrificed performance for slimmer design?
Have you encountered any issues?

**Comment by seerge** [comment]
@lucidnx performance is a bit better, you can check my mini-review https://www.reddit.com/r/ZephyrusG14/comments/1b799mh/g14_2024_4070_some_initial_benchmarks/ 

I didn't had any issues :) it's a nice laptop, better than 2022 model

**Comment by lucidnx** [comment]
Let's wait for 2025 :) It seems that there's no reason to upgrade now. I am thinking about 15-16" laptops, because of performance but it's kinda big for me on the go...
