### ISSUE TITLE
ghelper doesnt run

### ISSUE THREAD

**Issue by niannianqi** [seerge/g-helper#2717]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The application cannot run

### How to reproduce the bug?

Open the app

### Logs

错误应用程序名称: GHelper.exe，版本: 0.176.0.0，时间戳: 0x661e0000
错误模块名称: coreclr.dll，版本: 7.0.1824.16914，时间戳: 0x65fa1458
异常代码: 0xc0000005
错误偏移量: 0x00000000001bf6ec
错误进程 ID: 0x0x3120
错误应用程序启动时间: 0x0x1DABCD4AFEA407D
错误应用程序路径: C:\Users\wangh\Desktop\GHelper.exe
错误模块路径: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.18\coreclr.dll
报告 ID: b6fd7961-1f0e-4766-85f2-d3146dc0f9a5
错误程序包全名: 
错误程序包相对应用程序 ID: 

Application: GHelper.exe
CoreCLR Version: 7.0.1824.16914
.NET Version: 7.0.18
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at System.Globalization.CompareInfo.IcuCompareString(System.ReadOnlySpan`1<Char>, System.ReadOnlySpan`1<Char>, System.Globalization.CompareOptions)
   at System.Globalization.CompareInfo.Compare(System.ReadOnlySpan`1<Char>, System.ReadOnlySpan`1<Char>, System.Globalization.CompareOptions)
   at System.Globalization.CompareInfo.Compare(System.String, System.String, System.Globalization.CompareOptions)
   at System.String.Equals(System.String, System.String, System.StringComparison)
   at System.Resources.ManifestBasedResourceGroveler.CaseInsensitiveManifestResourceStreamLookup(System.Reflection.Assembly, System.String)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(System.Globalization.CultureInfo, System.Collections.Generic.Dictionary`2<System.String,System.Resources.ResourceSet>, Boolean, Boolean)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean)
   at System.Resources.ResourceManager.GetObject(System.String, System.Globalization.CultureInfo, Boolean)
   at GHelper.Properties.Resources.get_standard()
   at GHelper.Program..cctor()
   at GHelper.Program.Main(System.String[])

### Device and Model

ASUS-TUF-Gaming-F15-2022 fx507zm

### Armoury Crate

Uninstalled

### Version

0.176

### OS

windows 22h2

**Comment by seerge** [comment]
@niannianqi hello, 

It looks like there is something wrong with .NET installation on your system.

Try to download latest version and reinstall it again
https://download.visualstudio.microsoft.com/download/pr/6f7abf5c-3f6d-43cc-8f3c-700c27d4976b/b7a3b806505c95c7095ca1e8c057e987/dotnet-sdk-7.0.410-win-x64.exe

Thanks

**Comment by niannianqi** [comment]
I tried this method myself earlier, but unfortunately even using the version you provided did not fix the error

**Comment by seerge** [comment]
@niannianqi well, error trace shows that something happens outside of G-Helper's code, in .NET itself.

Try to uninstall .NET again and install this one https://download.visualstudio.microsoft.com/download/pr/08bbfe8f-812d-479f-803b-23ea0bffce47/c320e4b037f3e92ab7ea92c3d7ea3ca1/windowsdesktop-runtime-7.0.20-win-x64.exe

**Comment by niannianqi** [comment]
The problem still exists.I found more error messages
![屏幕截图 2024-06-12 231330](https://github.com/seerge/g-helper/assets/63998607/a5b3f4b6-a172-4acb-ab95-0fb74b597a21)
[Report.zip](https://github.com/user-attachments/files/15807236/Report.zip)

**Comment by seerge** [comment]
@niannianqi look for error messages mentioning specific lines of code in G-Helper itself. Example https://github.com/seerge/g-helper/issues/2596#issuecomment-2113465005

Cause as I've mentioned if error is in .NET itself - i can't fix it anyhow, as it's not the app in a first place :)

**Comment by niannianqi** [comment]
[log.txt](https://github.com/user-attachments/files/15807566/log.txt)

**Comment by seerge** [comment]
@niannianqi that's not error log from event viewer :) btw, try to delete app config from `%appdata%\GHelper\` completely

**Comment by niannianqi** [comment]
I looked for the earliest occurrence logs for all keywords with ghelper
1.- System 

  - Provider 

   [ Name]  Application Error 
   [ Guid]  {a0e9b465-b939-57d7-b27d-95d8e925ff57} 
 
   EventID 1000 
 
   Version 0 
 
   Level 2 
 
   Task 100 
 
   Opcode 0 
 
   Keywords 0x8000000000000000 
 
  - TimeCreated 

   [ SystemTime]  2024-06-03T21:16:13.5332439Z 
 
   EventRecordID 18704 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  14404 
   [ ThreadID]  14408 
 
   Channel Application 
 
   Computer Violet 
 
  - Security 

   [ UserID]  S-1-5-21-2148577000-3518967119-696696531-1001 
 

- EventData 

  AppName GHelper.exe 
  AppVersion 0.173.0.0 
  AppTimeStamp 661e0000 
  ModuleName coreclr.dll 
  ModuleVersion 7.0.1824.16914 
  ModuleTimeStamp 65fa1458 
  ExceptionCode c0000005 
  FaultingOffset 00000000001bf6ec 
  ProcessId 0x3678 
  ProcessCreationTime 0x1dab5fb43186d39 
  AppPath C:\Users\wangh\Desktop\GHelper.exe 
  ModulePath C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.18\coreclr.dll 
  IntegratorReportId e39f9cd4-e483-420f-9ab5-580a3e3f10d5 
  PackageFullName  
  PackageRelativeAppId  
2.- System 

  - Provider 

   [ Name]  .NET Runtime 
 
  - EventID 1026 

   [ Qualifiers]  0 
 
   Version 0 
 
   Level 2 
 
   Task 0 
 
   Opcode 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2024-06-03T21:16:13.4599310Z 
 
   EventRecordID 18701 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  13944 
   [ ThreadID]  0 
 
   Channel Application 
 
   Computer Violet 
 
   Security 
 

- EventData 

   Application: GHelper.exe CoreCLR Version: 7.0.1824.16914 .NET Version: 7.0.18 Description: The process was terminated due to an unhandled exception. Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. Stack: at System.Globalization.CompareInfo.IcuCompareString(System.ReadOnlySpan`1<Char>, System.ReadOnlySpan`1<Char>, System.Globalization.CompareOptions) at System.Globalization.CompareInfo.Compare(System.ReadOnlySpan`1<Char>, System.ReadOnlySpan`1<Char>, System.Globalization.CompareOptions) at System.Globalization.CompareInfo.Compare(System.String, System.String, System.Globalization.CompareOptions) at System.Globalization.TextInfo.PopulateIsAsciiCasingSameAsInvariant() at System.Globalization.TextInfo.ChangeCaseCommon[[System.Globalization.TextInfo+ToLowerConversion, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.String) at AppConfig.ContainsModel(System.String) at AppConfig.IsAdvantageEdition() at AsusACPI..ctor() at GHelper.Program.Main(System.String[])

**Comment by seerge** [comment]
@niannianqi did you try deleting app config ?

Also try 2 last steps from https://github.com/seerge/g-helper/wiki/Troubleshooting

Especially this one https://github.com/seerge/g-helper/wiki/Troubleshooting#rebuilding-wmi-repository

**Comment by niannianqi** [comment]
I have tried all the methods you mentioned and it still doesn't work. I give up fixing it. Maybe I should reinstall the system. I have downloaded armoury and can use it normally. Thank you for your help！~    ：）
