### ISSUE TITLE
Asus Zephyrus Keyboard gets unactive after some time if not used, need to restart to get it working

### ISSUE THREAD

**Issue by ShubhamShah1096** [seerge/g-helper#2718]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I have a Asus Zephyrus laptop and this is the details for the model number and the year: ROG Zephyrus G16 (2023) GU603 GU603ZU-BS71-CB, sometimes the keyboard stops working out of nowhere, I haven't found any reasons for this problem but restarting the device seems to fix it for the time being, but sometimes it does happen even after a restart just a hour or two after restarting, and this happens in daily use, not related to any games. 

### How to reproduce the bug?

It just happens out of nowhere, there is no step by step guide to reproduce that thing

### Logs

[log.txt](https://github.com/user-attachments/files/15807600/log.txt)

### Device and Model

Asus Zephyrus G16 GU603ZU-BS71-CB

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.176.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@ShubhamShah1096 hello, 

Some Asus keyboards (i think M16 and G16 are affected most) can start behaving strange if it's color is changed few times in a row. This happens with both AC or G-Helper.

I see that you use Ambient backlight mode. It by definition changes color of your keyboard based on screen contents. 

Just set any other backlight mode and it should be fine.

Thanks

**Comment by ShubhamShah1096** [comment]
Thank you for more information about this, will keep this in mind when using my laptop.
