### ISSUE TITLE
profile per application for gpu 

### ISSUE THREAD

**Issue by BladeJoe** [seerge/g-helper#2721]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

-

### Describe the solution you'd like

it would be nice if it was possible to switch between individual game profiles automaticly as in my case i want to run some games in normal mode with default frequencies and and some other games underclocked or overclocked

### Device and Model

TUF F15

**Comment by seerge** [comment]
@BladeJoe hello, I was answering this few times already https://github.com/seerge/g-helper/issues/2693

G-Helper does not monitor your system and applications that you launch in realtime anyhow.

But you (already) can very easily switch between profiles (backwards and forwards) with multiple hotkeys
https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings

Thanks
