### ISSUE TITLE
Problem with charge limits that used to work after installing the newest version (0.176.0)

### ISSUE THREAD

**Issue by ahmeddwalid** [seerge/g-helper#2722]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I used to put the my laptop (Asus TUF Gaming A15 FA507NV) on the desk plugged in with a charge limit of 55% and it stops charging at 54.5% as usual.
After installing version number 0.176.0, I found that the charge limit has gone up to 60% and can't be set below.
I'm aware of the discussion [#2408 ](https://github.com/seerge/g-helper/discussions/2408) and I didn't test limits above 80% for a prolonged amount of time, but I tested these limits and they worked fine:
- Limit 55%: stops charging at 54.5%
- Limit 60%: stops charging at 59.5%
- Limit 65%: stops charging at 64.5%
- Limit 70%: stops charging at 69.5%
- Limit 75%: stops charging at 74.5%
- Limit 80%: stops charging at 79.5%

### How to reproduce the bug?

1. Open Ghelper window
2. Set the charge limit below 60% (specifically at 55%)

### Logs

[log.txt](https://github.com/user-attachments/files/15810820/log.txt)

### Device and Model

Asus TUF Gaming A15 FA507NV

### Additional information.

I didn't uninstall Armoury Crate software but I have Asus services stopped from the Extra Settings menu in Ghelper and I disabled it from the Startup Apps in the system settings.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.176.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@ahmeddwalid hello, 

If you will check #2408  - lots of people reported that only 60-80 charge limit works. So to keep things simple and easy to communicate I have restricted range to 60-80 for all TUF laptops :)

What is the practical purpose of keeping it specifically on 55%? Your battery won't be healthier from that :)

**Comment by ahmeddwalid** [comment]
@seerge hey,

I thought maybe you could support this model to have finer controls over the charge limits as some TUF models support a wider range for charging limits :)

Agree that 55% won't make my battery healthier but it would put less strain on the battery over time as it's closer to 50% charge than 60% is

**Comment by seerge** [comment]
@ahmeddwalid i’m trying to keep simple and transparent to communicate.

Current logic is that all TUFs are treated same.

It’s like 600+ total asus laptops in their lineup, so if i will be hardcoding supported charge limits for each one of them - it will be very difficult 

So, sorry , but i would prefer to keep it as is for now.

Therefore closing as not planned

**Comment by ahmeddwalid** [comment]
@seerge Okay, thanks :)

Something else I don't know where to ask, I wanted to contribute to this project but I don't know what should I learn to be able to improve it.

I'm a college student and I did some projects before with JavaFX and C/C++ with microcontrollers, currently I'm learning android development with Kotlin. How can I help, I'm learning git & github so I can contribute to the opensource projects I use.

**Comment by seerge** [comment]
@ahmeddwalid you can contribute if you want, but i would suggest to check / ask if specific addition you have in mind is needed. 

My main point here - is that I'm trying to keep app as universal and as simple as possible (which already becomes more difficult due to existing amount of features)
