### ISSUE TITLE
System hang and BSOD with TURBO mode 

### ISSUE THREAD

**Issue by countingtls** [seerge/g-helper#2725]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I've been running into system hang several times today, when I change the G-help setting from Balanced to Turbo mode using v0.176. I was streaming and encoding videos using ffmpeg in the background, and the system would hang about a couple to tens of minutes in the workload. And it hung while I was performing different tasks (copy paste a text, watching a video, or starting a Go program). Out of all the hangs, only one of them eventually went into BSOD (which would take several minutes of hang, and then the BSOD suddenly appeared, and it was the error code Video TDR Failure, module nvlddmkm.sys, not sure it was the actual cause of this, it might be the hanging process eventually lead to it, not the cause of the hanging)

I was fine yesterday, and would be ok when I switched to Balanced mode, or downgraded to G-helper v0.173. The only thing that had been changed between then was I updated to G-helper v0.176 and a Windows update KB5039212. And if it is any help here is the only minidump for the one BSOD out of all the hangs. (I've dug into it a bit, and mostly just graphic card driver-related. But if that's the case why downgrade to v0.173 would solve the issue? What changed between v0.173 to v0.176 that is affecting only Turbo mode?)
[061324-16671-01.zip](https://github.com/user-attachments/files/15815730/061324-16671-01.zip)

### How to reproduce the bug?

Switch to Turbo mode using v0.176, and perform high CPU loading tasks like ffmpeg encoding, and high GPU load while streaming at the same time.

### Logs

[log.txt](https://github.com/user-attachments/files/15815978/log.txt)

### Device and Model

Asus ROG Flow Z13 GZ301VV

### Additional information.

I am not sure if it is relevant, but I had issues about a month ago when I suddenly got BSOD after updating the Nvidia driver (Nvidia GeForce GRD 555.85 from the stable 552.44). And it took me days to finally solve by downgrading not just the drivers, but also the BIOS from 3.11 to 3.10). And I seriously don't want to go into another unstable graphic card driver update 555.99 which a lot of people on the Nvidia forum were reporting as unstable as well like 555.85. Although one of the issues of the Asus BIOS 3.11 is related to CPU throttling, and I believe it was the main reason for my previous crash a month ago. And I've been using CPU-Z to check the CPU core speed and Multiplier which is how Turbo mode works right? So this hanging might also be related so how?

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.176

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@countingtls P.S. By digging deeper into the log, i see that in 0.173 you seem to had some customizations for GPU (even tho it's default values)

So "technically" it wasn't default Turbo mode, it was Manual mode with minimal changes (from BIOS perspective)

```
2024/6/13 下午 02:19:35: PowerLimit C0 (GPU BOOST) = 25 : OK
2024/6/13 下午 02:19:35: PowerLimit C2 (GPU TEMP) = 87 : OK
```

Try to just drag those sliders in 0.176 again and set them to same values. And see if it helps ?

**Comment by seerge** [comment]
@countingtls 

> Ya, during the crash last month, I suspected it might be related to overheating or power overdraw so I fiddled with the profiles and see if they made any changes. I don't think it helped previously since when I downgrade the BIOS it solved immediately. But it might still be the case now (I doubt it though, it doesn't feel like an overheating crash).

So you had crashes before, but solved that with BIOS downgrade? I would say it could be some (hardware?) underlying issue that pops up in certain circumstances then.

The BSOD you are talking about in this issue, is it the only one ? Or is it reproducible ?

That's why I suggested to use exactly same settings in new 0.176 as you used in 0.173. Namely just set GPU boost to 25 and temp limit to 87 (literally drag slider left and right there)

> Can I just apply the json profile from the earlier v0.173? They are all stored in the same format, right? I'll test it and see if it helps or not.

You generally don't need to change config :) I just noticed that you **had** some settings in 0.173 and **did not have them** in 0.176 - so I was wondering if you have manually reset config or so ...

**Comment by countingtls** [comment]
> @countingtls
> 
> > Ya, during the crash last month, I suspected it might be related to overheating or power overdraw so I fiddled with the profiles and see if they made any changes. I don't think it helped previously since when I downgrade the BIOS it solved immediately. But it might still be the case now (I doubt it though, it doesn't feel like an overheating crash).
> 
> So you had crashes before, but solved that with BIOS downgrade? I would say it could be some (hardware?) underlying issue that pops up in certain circumstances then (like when GPU overheats or so).
> 
> The BSOD you are talking about in this issue, is it the only one ? Or is it reproducible ?
> 
> That's why I suggested to use exactly same settings in new 0.176 as you used in 0.173. Namely just set GPU boost to 25 and temp limit to 87 (literally drag slider left and right there)
> 
> > Can I just apply the json profile from the earlier v0.173? They are all stored in the same format, right? I'll test it and see if it helps or not.
> 
> You generally don't need to change config :) I just noticed that you **had** some settings in 0.173 and **did not have them** in 0.176 - so I was wondering if you have manually reset config or so ...

It's sort of a mixed bag issue, first of all, the hanging is reproducible, but not BSOD, in fact of all the hanging/freezing, only one time leads to BSOD. And the condition that leads to freezing is actually not overloading with tasks, but after loading heavy loading (encoding, streaming, etc.) for a while (which is surprisingly stable, running at max temp), and leaving only the "background" high CPU task like video encoding, then just performing any trivial tasks (like even browsing the web) that doesn't utilize GPU, then it would freeze "mid-click" (while the background encoding is still running at Turbo mode). This wouldn't happen with Balanced mode.

And today after I fiddled with lots of options using 0.176 (like lowering the max W, max temp, etc), it crashed again and again (and at some point after rebooting, immediately crashed again), which eventually lead to a Nvidia Localsystem Container service unable to start, and I had to reinstall all the Nvidia services along with the drives again (took me half a day, I have CUDA and cudnn for machine learning models as well, and all the dependencies, it is a pain to reinstall all). It's only about a couple hour after the reinstall, but for now, it haven crashed yet.

I read somewhere there might be an issue for Nvidia tried to tune their driver, and it might cause issue not because high usage, but undervoltage issue, that sort of like GPU goes into semi-sleep mode, and cannot wake up properly after. This might explain why it is after the GPU load is done, that freezing actually happened. I might try using intel graphic only and see if it really is related to Nvidia graphic card. (or it might be the other way around that intel graphic driver has issue, and automatic switching to it causing the issue. Still need to test more.

**Comment by seerge** [comment]
@countingtls well, i don't know what to suggest to you on this point.

As I have mentioned before, changes in 0.176 are not even closely related to any modes or performance (added couple of new mice, dynamic lighting detection, etc). And furthermore - when app stays in tray, it does nothing - it only runs commands when you change mode, press hotkey, etc.

I have also noticed that in your 0.173 part of log for Turbo mode you had CPU boost set to Aggressive, 

```
2024/6/13 下午 01:26:25: Power Mode 00000000-0000-0000-0000-000000000000 -> ded574b5-45a0-4f42-8737-46345c09c238:OK
2024/6/13 下午 01:26:25: Boost 2              <--- AGGRESSIVE BOOST
2024/6/13 下午 01:26:25: Mode = 1 : OK   <---- TURBO MODE
```

And for Balanced - you had Enabled

```
2024/6/13 下午 02:02:33: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 00000000-0000-0000-0000-000000000000:OK
2024/6/13 下午 02:02:33: Boost 1              <---- ENABLED BOOST
2024/6/13 下午 02:02:33: Mode = 0 : OK  <---- BALANCED MODE
```

- May be that's what's triggering that ?

- Also did you try to resetting [power plan to defaults as explained in Troubleshooting](https://github.com/seerge/g-helper/wiki/Troubleshooting#resetting-windows-power-plan-to-defaults)?

- Or may be reinstalling [Nvidia Drivers using DDU ?](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers)

**Comment by seerge** [comment]
@countingtls P.S. just as experiment, there are 2 more intermediate versions between 0.173 and 0.176, can you try 0.174 and 0.175 ? to see if that makes a difference ?

**Comment by countingtls** [comment]
> @countingtls well, i don't know what to suggest to you on this point.
> 
> As I have mentioned before, changes in 0.176 are not even closely related to any modes or performance (added couple of new mice, dynamic lighting detection, etc). And furthermore - when app stays in tray, it does nothing - it only runs commands when you change mode, press hotkey, etc.
> 
> I have also noticed that in your 0.173 part of log for Turbo mode you had CPU boost set to Aggressive,
> 
> ```
> 2024/6/13 下午 01:26:25: Power Mode 00000000-0000-0000-0000-000000000000 -> ded574b5-45a0-4f42-8737-46345c09c238:OK
> 2024/6/13 下午 01:26:25: Boost 2              <--- AGGRESSIVE BOOST
> 2024/6/13 下午 01:26:25: Mode = 1 : OK   <---- TURBO MODE
> ```
> 
> And for Balanced - you had Enabled
> 
> ```
> 2024/6/13 下午 02:02:33: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 00000000-0000-0000-0000-000000000000:OK
> 2024/6/13 下午 02:02:33: Boost 1              <---- ENABLED BOOST
> 2024/6/13 下午 02:02:33: Mode = 0 : OK  <---- BALANCED MODE
> ```
> 
> * May be that's what's triggering that ?
> * Also did you try to resetting [power plan to defaults as explained in Troubleshooting](https://github.com/seerge/g-helper/wiki/Troubleshooting#resetting-windows-power-plan-to-defaults)?
> * Or may be reinstalling [Nvidia Drivers using DDU ?](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers)

Most solutions I found all revolved around some kind of reset, and I think I've tried most of them already, besides DDU intel graphic driver. And I've tested intel graphic only and GPU only, for at least one day each and they both work fine with v0.176 at Turbo mode for hours and hours, the only downside is that intel obviously cannot utilize CUDA, while then GPU only setup making the whole laptop extremely hot constantly (so hot that it affects the battery charging, and I have to do a battery calibration right now, since it only read 65% battery full charge health which previous day was still 94%). 

I found one post on reddit that has almost the exact same symptoms described except for different usage of GPU besides gaming. 

https://www.reddit.com/r/ZephyrusG14/comments/1c7v0lf/advanced_optimus_laptop_freezes_when_switching/

And instead of automatic, I think the Optimus mode was having trouble or somehow the system switched from Optimus mode to automatic mode and it simply cannot switch it back and freeze. I noticed previous sometimes the whole system bar would freeze and i had to restart the explorer.exe and G-helper was unresponsive which might lead to setup the graphic mode incorrectly somehow?

I will test other versions of G-helper after the battery calibration and before I reset graphic drivers or other reset options. For both graphic drivers running seemed perfectly fine on their own, this feels mainly a software issue.

**Comment by countingtls** [comment]
> I have also noticed that in your 0.173 part of log for Turbo mode you had CPU boost set to Aggressive,
> 
> ```
> 2024/6/13 下午 01:26:25: Power Mode 00000000-0000-0000-0000-000000000000 -> ded574b5-45a0-4f42-8737-46345c09c238:OK
> 2024/6/13 下午 01:26:25: Boost 2              <--- AGGRESSIVE BOOST
> 2024/6/13 下午 01:26:25: Mode = 1 : OK   <---- TURBO MODE
> ```
> 
> And for Balanced - you had Enabled
> 
> ```
> 2024/6/13 下午 02:02:33: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 00000000-0000-0000-0000-000000000000:OK
> 2024/6/13 下午 02:02:33: Boost 1              <---- ENABLED BOOST
> 2024/6/13 下午 02:02:33: Mode = 0 : OK  <---- BALANCED MODE
> ```

I fiddled with the customization turbo and balanced modes a lot last month during the last crashes and they might stick. What were the default options? I tried so many different profiles and setup I lost track

**Comment by seerge** [comment]
@countingtls 

>  think the Optimus mode was having trouble or somehow the system switched from Optimus mode to automatic mode and it simply cannot switch it back and freeze. I noticed previous sometimes the whole system bar would freeze and i had to restart the explorer.exe and G-helper was unresponsive which might lead to setup the graphic mode incorrectly somehow?

G-Helper is not interacting with Nvidia Optimus anyhow. Enabling or disabling of dGPU (i.e. Eco / Standard) mode is not dependent on that. But having NVidia Optimus freeze screen for a second or two - is normal, that's how Optimus works as I know.

>  I tried so many different profiles and setup I lost track and reset to factory default doesn't seem to reset them.

There is no "default" CPU boost mode, app would just show whatever you have currently in your power plan. But in windows - default value is Aggressive.

**Comment by countingtls** [comment]
> G-Helper is not interacting with Nvidia Optimus anyhow. Enabling or disabling of dGPU (i.e. Eco / Standard) mode is not dependent on that. But having NVidia Optimus freeze screen for a second or two - is normal, that's how Optimus works as I know.

freezing for a bit is expected, but not freeze the whole OS forever (and occasionally lead to BSOD), and indeed Optimus setup is in Nividia control panel. However, they don't seem to work that rigorously since the original AC did have an option of advanced Optimus, which I believe was also temping with Nvidia setup (there was an option somewhere I remember, I didn't have AC now, so couldn't check). So it is possible there is still some system setup can lead to problematic GPU switching??? (maybe not directly linked to G-helper or has anything to do with it at all, this is purely speculative, but the symptom is so similar with the reddit post I shared and reports I found, so just suspect they might somehow have similar causes)

And as I suspected I indeed set the Turbo mode CPU boost at the righ mode, I'll keep it in that mode for the testing of v0.174 and v0.175

**Comment by seerge** [comment]
@countingtls AC doesn't interact with Optimus neither. But it requires you have your GPU in actual Optimus state (and not Nvidia GPU only) when setting Eco. But that's already what you have.

**Comment by seerge** [comment]
@countingtls any updates, did you have a chance to check other versions ?

**Comment by countingtls** [comment]
> @countingtls any updates, did you have a chance to check other versions ?

After a lot of fiddling around with the Nvidia Control Panel, and manually set each program to dGPU or iGPU instead of automatic chosen by Optimus, I think I had a hypothesis about what was going on. Below v0.174, when I set to Turbo mode, the setting sometimes didn't take, and stuck in the "Balanced mode", but the newer version actually does. (the older version sort of stop responding when the high load start running). During the last month's crash I set a lot of programs to utilize iGPU instead of dGPU when I tried to isolate the issue. When I turned back on the Optimus notifications, I briefly saw the shadow of the pop up notification near the system bar right before the freeze. I kinda feel that it is an issue of NCP itself delays when Windows was too busy in the background at high CPU load.

Right now, I am testing 0.176 tweaking with NCP with various programs dedicated to iGPU or dGPU manually, and it is stable at the moment. And tried the beta version of the Nvidia app to see if the Optimus setting would be more stable instead of the original NCP seperated with Nvidia Experience Panel.

**Comment by seerge** [comment]
@countingtls 

There are no differences between 173 and 174 that would even remotely prevent mode changes https://github.com/seerge/g-helper/compare/v0.173...v0.174 

I'm glad you have figured it out, and it seem to work fine. 
If you will find any specific setting or so that is relevant in your situation - let me know, I may try to do something.

And for now - I'm closing this as it doesn't seem to be relevant to the app in a first place. Thanks.

**Comment by countingtls** [comment]
> @countingtls
> 
> There are no differences between 173 and 174 that would even remotely prevent mode changes [v0.173...v0.174](https://github.com/seerge/g-helper/compare/v0.173...v0.174)
> 
> I'm glad you have figured it out, and it seem to work fine. If you will find any specific setting or so that is relevant in your situation - let me know, I may try to do something.
> 
> And for now - I'm closing this as it doesn't seem to be relevant to the app in a first place. Thanks.

Thanks for all your assistance, and replies, even though it ends up been mostly issues of advanced Optimus (it's not even an Nvidia driver issue, since I updated several versions now, and still fine).
 
BTW, I just want to clarify I said "below 0.174" including 0.174 itself, and it behaves just like 0.173 from my testing. The difference I notice is between 0.175 and 0.174. (and not sure the differences between 0.176 and 0.175)

**Comment by seerge** [comment]
@countingtls the difference between https://github.com/seerge/g-helper/compare/v0.174...v0.175 is even smaller.

It's mainly couple of things added
- Dynamic lighting warning in app (for RGB controls on 2024 device) - irrelevant to your model
- Battery charge level indication for Slash Lighting - irrelevant to your model again
- Extended list of models that don't support anything but 60-80% charge limit
- Simplified CPU temp limiter (in `Advanced` tab for AMD devices)

None of this things is even closely related to optimus / power / etc :)
