### ISSUE TITLE
Mouse Asus TUF Gaming M4 AIR

### ISSUE THREAD

**Issue by phmmuller** [seerge/g-helper#2729]
### Mouse / peripheral model and version

Mouse Asus TUF Gaming M4 AIR (P307)

### Armoury Crate Screenshots

BUTTONS
![1 - Buttons](https://github.com/seerge/g-helper/assets/128853745/6ffb7b22-2c22-4471-b10d-01a69f09ad43)

PERFORMANCE
![2 - Performance](https://github.com/seerge/g-helper/assets/128853745/7c1f9b85-8263-4779-b248-f710c61b8be3)

CALIBRATION
![3 - Calibration](https://github.com/seerge/g-helper/assets/128853745/9704a043-5b22-420d-ba9d-90accd0be16f)

FIRMWARE UPDATE
![4 - Firmware Update](https://github.com/seerge/g-helper/assets/128853745/aa8ab4af-e2bc-4f56-9815-427d020737bb)

### USB Details

    =========================== USB Port2 ===========================

Connection Status        : 0x01 (Device is connected)
Port Chain               : 1-2
Properties               : 0x00
 IsUserConnectable       : no
 PortIsDebugCapable      : no
 PortHasMultiCompanions  : no
 PortConnectorIsTypeC    : no
ConnectionIndex          : 0x02 (Port 2)

      ========================== Summary =========================
Vendor ID                : 0x0B05 (ASUSTek Computer Inc.)
Product ID               : 0x1A03
USB Version              : 2.0 -> but Device is Full-Speed only
Port maximum Speed       : High-Speed
Device maximum Speed     : Full-Speed
Device Connection Speed  : Full-Speed
Self powered             : yes
Demanded Current         : 100 mA
Used Endpoints           : 5

      ======================== USB Device ========================

        +++++++++++++++++ Device Information ++++++++++++++++++
Device Description       : USB Composite Device
Device Path              : \\?\USB#VID_0B05&PID_1A03#5&1423acb5&0&2#{a5dcbf10-6530-11d2-901f-00c04fb951ed} (GUID_DEVINTERFACE_USB_DEVICE)
Kernel Name              : \Device\USBPDO-6
Device ID                : USB\VID_0B05&PID_1A03\5&1423ACB5&0&2
Hardware IDs             : USB\VID_0B05&PID_1A03&REV_0104 USB\VID_0B05&PID_1A03
Driver KeyName           : {36fc9e60-c465-11cf-8056-444553540000}\0019 (GUID_DEVCLASS_USB)
Driver                   : \SystemRoot\System32\drivers\usbccgp.sys (Version: 10.0.22621.3672  Date: 2024-05-30  Company: Microsoft Corporation)
Driver Inf               : C:\Windows\inf\usb.inf
Legacy BusType           : PNPBus
Class                    : USB
Class GUID               : {36fc9e60-c465-11cf-8056-444553540000} (GUID_DEVCLASS_USB)
Service                  : usbccgp
Enumerator               : USB
Location Info            : Port_#0002.Hub_#0002
Address                  : 2
Location IDs             : PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(2), ACPI(_SB_)#ACPI(PC00)#ACPI(XHCI)#ACPI(RHUB)#ACPI(HS02)
Container ID             : {8a7a65c5-29a8-11ef-b676-c88a9adb101a}
Manufacturer Info        : (Standard USB Host Controller)
Capabilities             : 0x84 (Removable, SurpriseRemovalOK)
Status                   : 0x0180400A (DN_DRIVER_LOADED, DN_STARTED, DN_REMOVABLE, DN_NT_ENUMERATOR, DN_NT_DRIVER)
Problem Code             : 0
Address                  : 2
EnhancedPowerMgmtEnabled : 0
Power State              : D0 (supported: D0, D1, D2, D3, wake from D0, wake from D1, wake from D2)

        +++++++++++++++++ Registry USB Flags +++++++++++++++++
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\usbflags\0B051A030104
 osvc                    : REG_BINARY 00 00

        ---------------- Connection Information ---------------
Connection Index         : 0x02 (Port 2)
Connection Status        : 0x01 (DeviceConnected)
Current Config Value     : 0x01 (Configuration 1)
Device Address           : 0x06 (6)
Is Hub                   : 0x00 (no)
Device Bus Speed         : 0x01 (Full-Speed)
Number of open Pipes     : 0x04 (4 pipes to data endpoints)
Pipe[0]                  : EndpointID=3  Direction=IN   ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x40    bInterval=1   -> 718 Bits/ms = 89750 Bytes/s
Pipe[1]                  : EndpointID=3  Direction=OUT  ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x40    bInterval=1   -> 718 Bits/ms = 89750 Bytes/s
Pipe[2]                  : EndpointID=1  Direction=IN   ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x6     bInterval=1   -> 177 Bits/ms = 22125 Bytes/s
Pipe[3]                  : EndpointID=2  Direction=IN   ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x15    bInterval=1   -> 317 Bits/ms = 39625 Bytes/s
Data (HexDump)           : 02 00 00 00 12 01 00 02 00 00 00 40 05 0B 03 1A   ...........@....
                           04 01 01 02 00 01 01 01 00 06 00 04 00 00 00 01   ................
                           00 00 00 07 05 83 03 40 00 01 00 00 00 00 07 05   .......@........
                           03 03 40 00 01 00 00 00 00 07 05 81 03 06 00 01   ..@.............
                           00 00 00 00 07 05 82 03 15 00 01 00 00 00 00      ...............

        --------------- Connection Information V2 -------------
Connection Index         : 0x02 (2)
Length                   : 0x10 (16 bytes)
SupportedUsbProtocols    : 0x03
 Usb110                  : 1 (yes, port supports USB 1.1)
 Usb200                  : 1 (yes, port supports USB 2.0)
 Usb300                  : 0 (no, port not supports USB 3.0)
 ReservedMBZ             : 0x00
Flags                    : 0x00
 DevIsOpAtSsOrHigher     : 0 (Device is not operating at SuperSpeed or higher)
 DevIsSsCapOrHigher      : 0 (Device is not SuperSpeed capable or higher)
 DevIsOpAtSsPlusOrHigher : 0 (Device is not operating at SuperSpeedPlus or higher)
 DevIsSsPlusCapOrHigher  : 0 (Device is not SuperSpeedPlus capable or higher)
 ReservedMBZ             : 0x00
Data (HexDump)           : 02 00 00 00 10 00 00 00 03 00 00 00 00 00 00 00   ................

    ---------------------- Device Descriptor ----------------------
bLength                  : 0x12 (18 bytes)
bDescriptorType          : 0x01 (Device Descriptor)
bcdUSB                   : 0x200 (USB Version 2.0) -> but device is Full-Speed only
bDeviceClass             : 0x00 (defined by the interface descriptors)
bDeviceSubClass          : 0x00
bDeviceProtocol          : 0x00
bMaxPacketSize0          : 0x40 (64 bytes)
idVendor                 : 0x0B05 (ASUSTek Computer Inc.)
idProduct                : 0x1A03
bcdDevice                : 0x0104
iManufacturer            : 0x01 (String Descriptor 1)
 Language 0x0409         : "ASUSTeK"
iProduct                 : 0x02 (String Descriptor 2)
 Language 0x0409         : "TUF GAMING M4 AIR"
iSerialNumber            : 0x00 (No String Descriptor)
bNumConfigurations       : 0x01 (1 Configuration)
Data (HexDump)           : 12 01 00 02 00 00 00 40 05 0B 03 1A 04 01 01 02   .......@........
                           00 01                                             ..

    ------------------ Configuration Descriptor -------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x02 (Configuration Descriptor)
wTotalLength             : 0x005B (91 bytes)
bNumInterfaces           : 0x03 (3 Interfaces)
bConfigurationValue      : 0x01 (Configuration 1)
iConfiguration           : 0x00 (No String Descriptor)
bmAttributes             : 0xE0
 D7: Reserved, set 1     : 0x01
 D6: Self Powered        : 0x01 (yes)
 D5: Remote Wakeup       : 0x01 (yes)
 D4..0: Reserved, set 0  : 0x00
MaxPower                 : 0x32 (100 mA)
Data (HexDump)           : 09 02 5B 00 03 01 00 E0 32 09 04 00 00 02 03 00   ..[.....2.......
                           00 00 09 21 11 01 00 01 22 22 00 07 05 83 03 40   ...!...."".....@
                           00 01 07 05 03 03 40 00 01 09 04 01 00 01 03 01   ......@.........
                           02 00 09 21 11 01 00 01 22 42 00 07 05 81 03 06   ...!...."B......
                           00 01 09 04 02 00 01 03 00 00 00 09 21 11 01 00   ............!...
                           01 22 88 00 07 05 82 03 15 00 01                  .".........

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x00 (Interface 0)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x02 (2 Endpoints)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x00 (None)
bInterfaceProtocol       : 0x00 (None)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 00 00 02 03 00 00 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 22 00                        .!...."".
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0022 (34 bytes)
Error reading descriptor : ERROR_GEN_FAILURE (due to a obscure limitation of the Win32 USB API, see F1 Help)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x83 (Direction=IN EndpointID=3)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0040 (64 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 83 03 40 00 01                              ....@..

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x03 (Direction=OUT EndpointID=3)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0040 (64 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 03 03 40 00 01                              ....@..

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x01 (Interface 1)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x01 (1 Endpoint)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x01 (Boot Interface)
bInterfaceProtocol       : 0x02 (Mouse)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 01 00 01 03 01 02 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 42 00                        .!...."B.
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0042 (66 bytes)
Error reading descriptor : ERROR_GEN_FAILURE (due to a obscure limitation of the Win32 USB API, see F1 Help)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x81 (Direction=IN EndpointID=1)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0006 (6 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 81 03 06 00 01                              .......

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x02 (Interface 2)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x01 (1 Endpoint)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x00 (None)
bInterfaceProtocol       : 0x00 (None)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 02 00 01 03 00 00 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 88 00                        .!...."..
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0088 (136 bytes)
Error reading descriptor : ERROR_GEN_FAILURE (due to a obscure limitation of the Win32 USB API, see F1 Help)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x82 (Direction=IN EndpointID=2)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0015 (21 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 82 03 15 00 01                              .......

    ----------------- Device Qualifier Descriptor -----------------
Error                    : ERROR_GEN_FAILURE  (because the device is Full-Speed only)

      -------------------- String Descriptors -------------------
             ------ String Descriptor 0 ------
bLength                  : 0x04 (4 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language ID[0]           : 0x0409 (English - United States)
Data (HexDump)           : 04 03 09 04                                       ....
             ------ String Descriptor 1 ------
bLength                  : 0x10 (16 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language 0x0409          : "ASUSTeK"
Data (HexDump)           : 10 03 41 00 53 00 55 00 53 00 54 00 65 00 4B 00   ..A.S.U.S.T.e.K.
             ------ String Descriptor 2 ------
bLength                  : 0x24 (36 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language 0x0409          : "TUF GAMING M4 AIR"
Data (HexDump)           : 24 03 54 00 55 00 46 00 20 00 47 00 41 00 4D 00   $.T.U.F. .G.A.M.
                           49 00 4E 00 47 00 20 00 4D 00 34 00 20 00 41 00   I.N.G. .M.4. .A.
                           49 00 52 00                                       I.R.

### Additional information.

![p2](https://github.com/seerge/g-helper/assets/128853745/2c95d208-235a-46c2-8b45-0948fd61a1d6)

**Comment by phmmuller** [comment]
MANUAL
[Q20920_P307_TUF_GAMING_M4_AIR_QSG_V3_WEB.pdf](https://github.com/user-attachments/files/15830294/Q20920_P307_TUF_GAMING_M4_AIR_QSG_V3_WEB.pdf)

**Comment by seerge** [comment]
@phmmuller can you try this build ?

[GHelper.zip](https://github.com/user-attachments/files/15840434/GHelper.zip)

**Comment by phmmuller** [comment]
@seerge the mouse settings appear and everything is working.
But when I restart the computer, the Performance setting reverts to DPI 1.
I'm a new user. G-Helper is really good and well-made. Thanks!

![ok_1](https://github.com/seerge/g-helper/assets/128853745/8f5a7580-4cf3-401d-ad5c-a1dc1ac05036)

**Comment by seerge** [comment]
@phmmuller do all settings work when you set them (like DPI) ? Can you upload log from new build ?

Thanks

**Comment by phmmuller** [comment]
As far as I can tell, everything is working. The only issue is that it doesn't keep the mouse settings when the computer restarts.
Log file:
[log.txt](https://github.com/user-attachments/files/15844877/log.txt)

**Comment by seerge** [comment]
@phmmuller thanks!

It's quite strange, cause on restart when app loads settings from the mouse it reports DPI profile 1 as active all the time 

```
14/06/2024 13:17:20: TUF GAMING M4 Air synchronising. Try 1
14/06/2024 13:17:20: TUF GAMING M4 Air: Write took 1ms
14/06/2024 13:17:20: TUF GAMING M4 Air: Read took 0ms
14/06/2024 13:17:20: TUF GAMING M4 Air: Active Profile 1, Active DPI Profile: 1 <<----- READS DATA FROM THE MOUSE
```

And when you set DPI profile manually in the app, and then synchronize with the mouse - it reports profile 3 correctly

```
14/06/2024 13:15:27: TUF GAMING M4 Air: DPI Profile set to 3 <---- SETTING PROFILE
14/06/2024 13:15:27: TUF GAMING M4 Air: Settings Flushed 
14/06/2024 13:15:27: TUF GAMING M4 Air: DPI for profile 3 set to 1600
....
14/06/2024 13:15:46: TUF GAMING M4 Air: Read took 0ms
14/06/2024 13:15:46: TUF GAMING M4 Air: Active Profile 1, Active DPI Profile: 3 <--- CORRECT DPI PROFILE REPORTED
```
----

Can you do 2 quick tests

1. Set DPI profile to 3  and then just quit and start G-Helper again ? What does it report as active profile ?
2 Set DPI profile to 3  and then unplug and plug mouse in again. What does it report as active profile ?

**Comment by phmmuller** [comment]
@seerge As requested, the attached files are videos to check if I did everything correctly..

1. It stays on profile 3.
[Test_1.zip](https://github.com/user-attachments/files/15847847/Test_1.zip)


2. I disconnected twice. The first time without restarting the application, and it stayed on profile 3. The second time I restarted the application, and it reverted to profile 1, just like when I restart the computer.
[Test_2.zip](https://github.com/user-attachments/files/15847848/Test_2.zip)

**Comment by seerge** [comment]
@phmmuller ok, clear!

1. So mouse remembers it's settings, as when you restart app - it re-reads all config from the mouse. And it's still correct DPI 3
2. When you reconnect mouse, it probably resets profile every time.

But does DPI really reset back to 600? or it stays 1600 and is only reported incorrectly ? 

-----
Can you check how it behaves when you set DPI profile in Armoury? Just set DPI 3 in it, then reboot and check if DPI remains high de-facto ?

As I remember, AC does not "read" profiles from the mouse, it just shows whatever was set last there. So you need to judge it from cursor speed :)

**Comment by phmmuller** [comment]
@seerge Yes, both the graphical interface and its configuration revert to DPI profile 1 (600). The mouse becomes much slower.
Thanks to you, I’ve never needed AC. This laptop doesn’t even know what that is! LOL
Kinda scared to install it and have the laptop start freaking out..
But if I really have to, I'll do it at night. My wife and I just had our second daughter.

Here's the log file from the tests I did earlier:
[log.txt](https://github.com/user-attachments/files/15848426/log.txt)

**Comment by seerge** [comment]
@phmmuller ok, i thought you already have AC, since you posted screenshots.

May be @IceStormNG knows or encountered it with other mice. Do they reset DPI profile on reboot ? Or is that normal behavior at all? 

Since a I don't have one even to test with :)

**Comment by IceStormNG** [comment]
[GHelper.zip](https://github.com/user-attachments/files/15849172/GHelper.zip)

Please try this build.

Try the following: Change DPI to 3. Click "Synchronize". Check whether GHelper still shows DPI3.
If so, unplug the mouse, plug it back in and check again.
Please send me the GHelper log. I enabled additional logging in this build so I can see what the mouse sends.

**Comment by phmmuller** [comment]
@seerge To be honest, I saw it was required and grabbed them from a recent YouTube review. Sorry for that.

I found a workaround with your build. I swapped the DPI values as shown in the image below. Now I can restart without worries; it'll boot up with the DPI I use daily: 1600.

![detour](https://github.com/seerge/g-helper/assets/128853745/b8d471dc-dd24-46ce-b85b-884d8008bd6a)

@IceStormNG Now, with your build:

I selected DPI 3 and synced it. It stayed on DPI 3, but when I disconnected and reconnected the mouse, the DPI was super slow. When I opened G-Helper, it had different DPI values and no profile was selected. Like that:

![1](https://github.com/seerge/g-helper/assets/128853745/a78acffe-1fcb-4bf2-93b9-bdfb6c8b65c2)

After I clicked one of the four profiles, the settings screen closed automatically and the option to configure the mouse disappeared from G-Helper.

![2](https://github.com/seerge/g-helper/assets/128853745/b7629a26-0feb-48d9-acca-048774712103)

So, I closed and reopened G-Helper, and the mouse settings showed up again.

![3](https://github.com/seerge/g-helper/assets/128853745/8e1d7ac7-f27d-48bc-85a2-5e13cc1aefc7)


And here is your log file:
[log.txt](https://github.com/user-attachments/files/15855818/log.txt)

**Comment by IceStormNG** [comment]
A few more questions:

When you connect the mouse to any other PC, that has no AC installed, does it do the same thing? Also when using AC before? It could be that the mouse simply doesn't keep the active DPI profiles stored when it turns off (for whatever reason).

Second question: How many profiles does the mouse offer in Armoury Crate? Just 1? 3? 5? I mean the dropdown at the top right.

I also saw that the mouse errors out when I try to read the lift off distance setting from it.

**Comment by phmmuller** [comment]
These are the values it came with. All 4 profiles worked without needing any software (AC or G-Helper).

![factory](https://github.com/seerge/g-helper/assets/128853745/a41f79c3-c4cf-459a-9464-d92b8efa2259)

But now, for some reason, the mouse is only switching between 3 profiles. Seems like it’s 600, 800 and 1600.

I just plugged it into a Lenovo laptop without AC. Windows downloaded the ASUS Mouse driver (no AC). The mouse still only has 3 profiles (600, 800 and 1600), ignoring its factory state of 4 profiles.

![test3_2](https://github.com/seerge/g-helper/assets/128853745/e56d643d-017d-4d65-a197-d27a4a9ccd62)

The default profile when I turn it on is 1600. I’m not sure if 1600 is DPI 1 or DPI 3. But if I change the profile and restart, it stays on the last profile I set. Aside from the fact that it now only has 3 profiles, switching between profiles is working fine and it stays on the last setting I configured.
In this test, I switched profiles using the mouse's physical button, not any software.

Since I went back to the stable version of G-Helper, I’m going to switch back to your build to test the lift. And then I’ll install AC too.

**Comment by phmmuller** [comment]
@IceStormNG I reinstalled your build.
I set the DPIs according to the factory defaults.
I synced it with the mouse.
I did a test by disconnecting and reconnecting the mouse.
I restarted G-Helper. There was an issue when I reconnected it; it didn’t recognize the mouse.
But when I reopened it, it recognized the mouse, and I proceeded with your lift test. It seems it doesn’t accept the change.

After this test, I restarted the computer. G-Helper managed to keep DPI 3 set as the default, which was the initial issue I noticed. It seems to be OK now.
I just don’t understand why it lost the default profile 4. When I press the physical button to switch, it only cycles between profiles 1, 2, and 3. Even when I connect it to the Lenovo laptop.

Log:
[log.txt](https://github.com/user-attachments/files/15858046/log.txt)

**Comment by IceStormNG** [comment]
Hm.. very weird. It looks like this mouse sets the lift off also differently.

You know what... I'm gonna ask amazon to "borrow" me an M4 Air... gonna find it out how this mouse works.


@ASUS: Could you please stop changing the mouse protocol for no f**king reason?

**Comment by phmmuller** [comment]
Kind like pharmaceutical industry.. LOL
Just to record, your support is top-notch @seerge and @IceStormNG .. I really appreciate your help.

So, I installed the AC:

![AC](https://github.com/seerge/g-helper/assets/128853745/53345deb-a2d7-4989-9df5-8c7d5a5ec4df)


The all 4 DPI factory profiles started working again by pressing the physical button.

![profiles](https://github.com/seerge/g-helper/assets/128853745/8ade9967-7640-4927-890a-f76ff36dc020)


In AC, it came pre-installed with 3 profiles. Here's the dropdown list:

![profiles_2](https://github.com/seerge/g-helper/assets/128853745/64eaab52-218a-43b6-906f-3cd6eb4f368f)


> Can you check how it behaves when you set DPI profile in Armoury? Just set DPI 3 in it, then reboot and check if DPI remains high de-facto ?

@seerge with AC, everything is working fine. If I set a value in DPI 3 and restart the computer, my setting remains active..

**Comment by seerge** [comment]
@phmmuller @IceStormNG 

Ok, if it persists in AC, it could be that it does something else that G-Helper can't do (yet).

I see 2 options then. Either @IceStormNG indeed "borrows" mouse from Amazon and looks into payload direcrtly.

OR

@phmmuller can just record payload that AC sends to the mouse and upload here. I'm attaching a manual (from other issue) on how to do that in case you want to bother with that

------

Install https://www.hhdsoftware.com/device-monitoring-studio (will require reboot)

1. Launch Monitoring Studio, pick Asus device with newly detected Product ID ``0x1A03`` (for TUF M4) from the list and double click on it
![Screenshot 2024-01-20 163125](https://github.com/seerge/g-helper/assets/5920850/e9a28802-08cb-423c-812b-7b526b051a5f)

2. Add ``Packet View`` to Procesing and click ``Start``
![Screenshot 2024-01-20 163136](https://github.com/seerge/g-helper/assets/5920850/354340f0-2fcb-473b-a49f-2e01b25d00a9)

3. Go to Armoury and change Mouse setting to something else (for example change DPI profile, etc)

4. Check if Monitoring Studio catching a lot of data (Armoury spams it like crazy). If NOT - you probably have selected wrong Asus device on step 2 (so need to re-do it)

5. In Monitoring Studio select ``Tools`` -> ``Save to Log``, and save data
![Screenshot 2024-01-20 163247](https://github.com/seerge/g-helper/assets/5920850/ad480dcf-05bc-43a7-9a80-2984fb68e8a8)

Upload this data here.

**Comment by seerge** [comment]
@phmmuller did you had a chance to try to record payload from AC ?

But even if you didn't, can you test one thing

1. Set DPI profile in AC
2. Plug mouse to some other device and check if DPI persists there ?

What I want to verify here , if AC indeed can "save" profile somehow. Or it just sets it again and again every time you restart laptop (or reconnect mouse) ... :)

**Comment by seerge** [comment]
@phmmuller any updates here ? cause there is a user with a similar problem [but with TUF M3](https://github.com/seerge/g-helper/issues/2776) , and it seems like there is a solution for it, but you need to record a payload from AC to check if it's the case :)

**Comment by seerge** [comment]
Closed as completed, since M4 support is in latest release. Feel free to reopen / comment if you will record a payload
