### ISSUE TITLE
Back and border lightning stoped working

### ISSUE THREAD

**Issue by arthur-lbchn** [seerge/g-helper#273]
Hello. First of all, thank you for your great app!

I've installed Asus ROG Strix SCAR 15 review (g533zx) and when I try to play with Keyboard Blacklights, my back and border lightings are completely off (so I have only keyboard). 

I remember, that it happened right after I click on:

![2023-04-20-00416](https://user-images.githubusercontent.com/9682681/233225017-465d5fa2-0130-4373-ac8f-f1b39dea4be1.png)

Hope it's something can be fixed and I can get all of my lightnings back.

Thank you!

OS Windows 11 Home (Build 22621.1555)

**Asus software**
- Armoury crate - Uninstalled
- MyASUS - still installed 
- Other Asus services running in background - Uninstalled by using .dat file

**Comment by seerge** [comment]
@arthur-lbchn can you try this build and check uncheck any backlit settings ? it should turn on ALL known lightning for your Lid and Lightbar

[GHelper.zip](https://github.com/seerge/g-helper/files/11285806/GHelper.zip)

**Comment by arthur-lbchn** [comment]
@seerge awesome, everything works now! 

Thank you very much!
