### ISSUE TITLE
Add HDMI connection status detection in automatic switching mode

### ISSUE THREAD

**Issue by G-jian** [seerge/g-helper#2731]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [ ] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

My computer is Zephyrus G14 2024. The graphics card is set to automatically switch. When using the battery, it switches to integrated graphics mode, so there is no response when connecting to HDMI. Can U add a feature to use the discrete graphics card when an HDMI connection is detected?

### Describe the solution you'd like

Can U add a feature to use the discrete graphics card when an HDMI connection is detected?

### Device and Model

Asus Zephyrus G14 GA403UV

**Comment by seerge** [comment]
@G-jian hello, this is a dublicate of https://github.com/seerge/g-helper/issues/909 . There is no reliable way to do that atm.

If you use laptop in Eco mode a lot, I would advice just to get a nice USB-C - to display port cable and connect your monitor via left USB-C port, it's much more convenient.

Or use Standard instead :)

Thanks
