### ISSUE TITLE
want to switch windows powerplan while changing mode in ghelper

### ISSUE THREAD

**Issue by szlysms** [seerge/g-helper#2732]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

i need a special powermode for bussiness trip(long using time with batteryonly)，and i found the hidden options in windows powerplan useful,(i'm not sure if my english is good ennough to be understood)

### Describe the solution you'd like

switch windows powerpaln while switching mode in ghelper

### Describe alternatives you've considered

![image](https://github.com/seerge/g-helper/assets/99026228/75f91ea2-57f2-46a6-b6fb-2c295a038925)

i made a keyboard shortcut to open it

### Device and Model

tuf a15

**Comment by seerge** [comment]
@szlysms hello. 

It's very hard to understand what exactly you want, but you can assign any custom power plans to each mode [as explained in readme](https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-windows-power-plans-with-each-mode). Even tho it doesn't make much difference.

Thanks.
