### ISSUE TITLE
CPU undervolting question. 

### ISSUE THREAD

**Issue by anders0nlin** [seerge/g-helper#2733]
Hello, 
I wanted to ask how the undervolting of the cpu worked. What does the -40 mean (like what are the units) and does it save battery for my laptop?  I would also like to ask how the GPU settings works and if you could recommened settings for me to maximize battery life. Thank you!
![image](https://github.com/seerge/g-helper/assets/172837105/d1166305-16d8-474d-901b-e54c2a7662ab)
![image](https://github.com/seerge/g-helper/assets/172837105/210d6eef-62d7-48f0-9068-1035c7048c3d)

**Comment by seerge** [comment]
@anders0nlin hello,

Undervolting is in milivolts. It allows your CPU to run a bit faster for same (old) power consumption. You can check that by running CPU-heavy benchmark like Cinebench23 and compare scores.

GPU settings allow you to increase clocks a bit for same (old) power consumption (again)

You can read a bit more [about it in FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-to-undervolt-gpu)

Thanks
