### ISSUE TITLE
Flicker Free Dimming Controls Via Key Bindings 

### ISSUE THREAD

**Issue by kiroAne** [seerge/g-helper#2735]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Not a problem, just thought if the Flicker-Free Dimming is better than how windows dims the screen, then I'd want quick access to it. 

### Describe the solution you'd like

Override FN-F7/F8 (windows brightness controls) to control G-Helper's Flicker-Free Dimming.

### Describe alternatives you've considered

If not F7/F8, I would want to use the Cntl-M1/M2 that's already set in G-helper for alternative brightness controls, or even use the keyboard backlight controls (FN-F2/F3) since I don't really change the backlight brightness.

### Device and Model

Asus Zephyrus G14 GA403UI

**Comment by seerge** [comment]
@kiroAne hello, it's already possible and [mentioned in readme](https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings)

``Fn + Ctrl +  F7 / F8`` - Flicker-free dimming Down / Up

So just add `Ctrl` to your regular brightness bindings.

Thanks.

**Comment by anventia** [comment]
Hello, would it be possible to add the ability to control Flicker-free dimming via another shortcut that doesn't involve the Fn key? It'd be amazing to be able to control the brightness from an external keyboard, as the Fn key isn't like a normal key and can only be used with the button on the laptop itself.
