### ISSUE TITLE
Allow separate lighting zone controls for battery/AC mode

### ISSUE THREAD

**Issue by IcePanther** [seerge/g-helper#2739]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

In Armory Crate, you can toggle different lighting zones on or off depending if you're on battery or AC power.
For instance, on battery mode, I had only enabled keyboard and disabled all other lighting to save power, whereas on AC all was on.
There is no way to set this in GHelper's current UI (not that I found ?)

### Describe the solution you'd like

Any way to select it, really.

Maybe for instance, either replace lighting zones checkboxes with picklists with "AC/Battery/Both/None" or change status of checkboxes depending on battery/AC power (like the power plan buttons change depending on AC/Battery power state)

### Device and Model

Asus G733CX

**Comment by IcePanther** [comment]
Another solution could be to have to checkboxes side by side, with little ac (lightning bolt) and battery icon over them to identify which is which.

**Comment by seerge** [comment]
@IcePanther how does it look in AC ? cause I had ROG Strix 16 for some time, and it didn't have such options there.

**Comment by IcePanther** [comment]
Screenshot :
![screenshot](https://github.com/seerge/g-helper/assets/28861505/5f7b81fc-025e-4e9d-842d-33338497732b)

Sorry for French, it reads :
>
> Startup, Shutdown
> 
>
> Powered on :
> * On battery
> Keyboard
> Laptop light zones
> Border light
> [x] Turn off after 1 minute when on battery
> * On AC power
> Keyboard
> Laptop light zones
> Border light
> 
>
> Sleep

It's been like that since I bought the laptop, I think.

Same for another device (Flow Z13) :
<img width="447" alt="screenshot2" src="https://github.com/seerge/g-helper/assets/28861505/13c0c668-6a06-40a3-b06e-56747a1d2619">

Name of light zones differ but otherwise identical.

**Comment by seerge** [comment]
@IcePanther try this build, I have added an extra checkbox called ``Battery`` which is responsible for each zone backlight when unplugged

[GHelper.zip](https://github.com/user-attachments/files/15912732/GHelper.zip)

**Comment by IcePanther** [comment]
It seems to work, thank you !

(I still had Armory Crate installed, but all Asus services were turned off by GHelper, Is that enough to prevent interference and ensure it was GHelper which toggled the light zones on or off ? 
It seems so, as it seemed to reflect the checkboxes I ticked or unticked in the GHelper UI, but I prefer to be sure)

**Comment by seerge** [comment]
@IcePanther great.

Stopping Asus services doesn't stop AC from working (it's only related to myasus services)

I don't recommend running AC and G-Helper along each other in a long term, as you won't know which app did set a settings so you should use official AC uninstaller if you don't plan to use it https://github.com/seerge/g-helper/wiki/Requirements#recommendations-optional

Closed as resolved. 

Thanks

**Comment by seerge** [comment]
@IcePanther can you check if this build still works correctly for you ? I have removed this setting for devices that don't have other backlight zones (anything that is not Strix), as they don't need it anyway

[GHelper.zip](https://github.com/user-attachments/files/15936240/GHelper.zip)

**Comment by IcePanther** [comment]
It seems to still work, yes. Thanks again.

(About AC running alongsite GHelper : I'm aware of that, and plan to uninstall it ; but I was testing another problem concurrently with Asus regarding color getting greyed out by AC's GameVisual (which happens with GHelper too when changing color profiles) which is in fact due to a regression in Asus System Interface 1.29 (1.27 works ok))
