### ISSUE TITLE
Windows Defender flags the 0.54 build as a virus

### ISSUE THREAD

**Issue by chrhasse** [seerge/g-helper#274]
Downloading 0.54 from the releases page results in Windows 10 quarantining the file as "Trojan:Script/Wacatac.B!ml"

[VirusTotal](https://www.virustotal.com/gui/file/f36164aabec5b704deb84691c40d652d1e9455220e0f04539580f34a1afa6c4f) doesn't detect anything, so I assume this is some odd heuristic failure from one of the new changes.

**Comment by ramius86** [comment]
> Downloading 0.54 from the releases page results in Windows 10 quarantining the file as "Trojan:Script/Wacatac.B!ml"
> 
> [VirusTotal](https://www.virustotal.com/gui/file/f36164aabec5b704deb84691c40d652d1e9455220e0f04539580f34a1afa6c4f) doesn't detect anything, so I assume this is some odd heuristic failure from one of the new changes.

Strange, are you sure is g-helper? I have windows 11 with everything updated and defender doesn't flag or quarantine the 0.54

**Comment by chrhasse** [comment]
I'm positive it was g-helper. I downloaded it directly from this repository on the releases page which I opened by clicking the version number in the latest stable g-helper, and when I clicked open through the firefox download menu it would tell me permission denied and quarantine the file [here's the quarantine page](https://i.imgur.com/Vv152a7.png). I don't have any updates available and it seems like a false positive, but I think it's worth putting on the radar.

**Comment by seerge** [comment]
@chrhasse seem to be your isolated case, but in general defender could act randomly for random people

You can use this build (same thing, juts recompiled with extra space in a code ...) or wait for 0.55 or use 0.53

[GHelper.zip](https://github.com/seerge/g-helper/files/11285754/GHelper.zip)

**Comment by dsevillamartin** [comment]
Just adding to this issue, as it is not isolated to the author. Windows Defender also quarantined my GHelper.zip download for the same reason. The build you recompiled was not caught. 

<details><summary>Screenshot</summary>
<p>

![image](https://user-images.githubusercontent.com/6401250/233396937-81c5a290-7907-4e6a-8e4f-4f3468e3eacd.png)

</p>
</details>

**Comment by seerge** [comment]
@dsevillamartin as i mentioned - it happens (randomly) :) you can always download newer version like https://github.com/seerge/g-helper/releases/tag/v0.55 or older or compile app by yourself
