### ISSUE TITLE
Rog Strix Evolve

### ISSUE THREAD

**Issue by KhayalZ** [seerge/g-helper#2741]
### Mouse / peripheral model and version

Rog Strix Evolve

### Armoury Crate Screenshots

SORRY)

### USB Details

        +++++++++++++++++ Device Information ++++++++++++++++++
Device Description       : ROG STRIX EVOLVE
Device Path 1            : \\?\HID#VID_0B05&PID_185B&MI_00#8&18b32870&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd} (GUID_DEVINTERFACE_MOUSE)
Device Path 2            : \\?\HID#VID_0B05&PID_185B&MI_00#8&18b32870&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (GUID_DEVINTERFACE_HID)
Kernel Name              : \Device\000000a6
Device ID                : HID\VID_0B05&PID_185B&MI_00\8&18B32870&0&0000
Hardware IDs             : HID\VID_0B05&PID_185B&REV_5001&MI_00 HID\VID_0B05&PID_185B&MI_00 HID\VID_0B05&UP:0001_U:0002 HID_DEVICE_SYSTEM_MOUSE HID_DEVICE_UP:0001_U:0002 HID_DEVICE
Driver KeyName           : {4d36e96f-e325-11ce-bfc1-08002be10318}\0001 (GUID_DEVCLASS_MOUSE)
Driver                   : \SystemRoot\System32\drivers\mouhid.sys (Version: 10.0.22621.1  Date: 2022-05-07  Company: Microsoft Corporation)
Driver Inf               : C:\Windows\inf\oem38.inf
Legacy BusType           : PNPBus
Class                    : Mouse
Class GUID               : {4d36e96f-e325-11ce-bfc1-08002be10318} (GUID_DEVCLASS_MOUSE)
Service                  : mouhid
Enumerator               : HID
Location Info            : -
Address                  : 1
Manufacturer Info        : ASUSTeK Computer Inc.
Capabilities             : 0xA0 (SilentInstall, SurpriseRemovalOK)
Status                   : 0x0180200A (DN_DRIVER_LOADED, DN_STARTED, DN_DISABLEABLE, DN_NT_ENUMERATOR, DN_NT_DRIVER)
Problem Code             : 0
Upper Filters            : ROGMS
EnhancedPowerMgmtEnabled : 0
Power State              : D0 (supported: D0, D1, D2, D3, wake from D0, wake from D1, wake from D2)

**Comment by seerge** [comment]
@KhayalZ hello, please include Armoury Crate screenshots as it was clearly asked in issue template. 
Thanks.

**Comment by seerge** [comment]
Closed as abandoned due to lack of requested info
