### ISSUE TITLE
Option for optimized GPU mode to keep using dGPU on battery if apps are using it

### ISSUE THREAD

**Issue by IcePanther** [seerge/g-helper#2742]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I enabled optimized GPU mode in GHelper, to use the intel GPU only when my laptop is on battery.
In Armory Crate, it would not disable the dGPU if some program was using it, instead it would pop open a notification.

Using GHelpher, I unplugged the laptop, and while it didn't exactly quit the application that was using the dGPU (a local LLM instance -- koboldCPP), it still seemed to disable the dGPU, and crashed the software with a VRAM error.

(I didn't know if this was a bug report or feature request, feel free to reassign if needed.)

### Describe the solution you'd like

Implement a detection that prevents disabling the dGPU in optimized mode as long as an application is still using it. It could be then disabled when no application is using it anymore.

### Describe alternatives you've considered

Workaround is not to use optimized mode, but this can be detrimental to battery life.

### Device and Model

G733CX

**Comment by seerge** [comment]
@IcePanther hello,

This is already the case.

Application already checks if GPU is being (actively) used before automatically disabling it. In case of that - it shows popup as well

https://github.com/seerge/g-helper/blob/ff92229ecb7d62d810e5bfca15f899ed8ead6e22/app/Gpu/GPUModeControl.cs#L229

Current treshold is 10% GPU Usage

Thanks

**Comment by IcePanther** [comment]
Hi, thanks for your quick answer.

However, this only works if the GPU is _under load_, not _used by an application_.
If, for instance, you're in the menu of a paused game (some do interrupt rendering when you do), or in this case, the LLM instance was between generations, so it didn't _load_ the GPU at that precise moment, but VRAM was still used by it, and when I tried to resume activity, it crashed.

Is there a way to detect if there are active handles pointing to the GPU instead of just the GPU load ? Or if it's simpler, maybe also detect if the dGPU's VRAM is being used ?

**Comment by seerge** [comment]
@IcePanther there is no way to detect is GPU is used but not used at the same time reliably.

Nvidia / AMD driver can report list of applications that "use" GPU atm - but it will almost always include harmless things like browsers, windows components, etc. Preventing dGPU swtich based on this list will stop this feature from working at all (what pretty much happens with AC all the time).

If you have some non-trivial usage for your GPU like running ML on it, i would just advice to stick to Standard mode.
