### ISSUE TITLE
DC Charging And PD Charging with Different Automatic Mode Switch？

### ISSUE THREAD

**Issue by kotoriinsky** [seerge/g-helper#2744]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I am accustomed to using the Balanced Mode in conjunction with PD charging while I'm at the library, but at home, I prefer the Enhanced Mode paired with DC charging. However, the current mode switching strategy fails to adequately differentiate between different types of chargers, causing me considerable inconvenience.

### Describe the solution you'd like

This situation underscores the need for a more intelligent recognition system that can adapt the device's operating mode according to both the charging mode (PD or DC) and my preferred settings in different environments. It would significantly enhance the user experience if the device could automatically switch to the Balanced Mode with PD charging when connected at the library, and then switch to the Enhanced Mode with DC charging upon connection at home. Thank you for your consideration.

### Device and Model

Asus Zephyrus G16 GU605MV

**Comment by seerge** [comment]
@kotoriinsky hello, I was answering this few times already. I don't plan to change that to keep things simple and trasnaprent

- There is no super-reliable way to detect if a device is on DC or PD charger
- Having and remembering different behavior for DC and PD will cause more confusion for people and do more "harm" in a way than good :) 

Thanks
