### ISSUE TITLE
GPU mode gets reset every time after reboot

### ISSUE THREAD

**Issue by ArnabBCA** [seerge/g-helper#2746]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

So this happens in only in ECO and Standard mode. I use ECO mode every time I use my laptop. But after rebooting or shutdown it goes back to standard mode. This is annoying as i have to manually change every time.

### How to reproduce the bug?

1. Change to ECO mode
2. Reboot or Shutdown the laptop
3. After reboot open GHelper, you will notice the GPU mode is changed to Standard mode it shoudd be in ECO mode

### Logs

[log.txt](https://github.com/user-attachments/files/15875356/log.txt)

### Device and Model

ASUS TUF Gaming FA507RE

### Additional information.

Also i have disabled fast boot in Windows,
And G-Healper is allowed to run as a startup app in Windows

### Armoury Crate

Installed

### Version

0.176.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@ArnabBCA hello,

It's not G-Helper resetting that actually. This is how BIOS is programmed on your device. It always reboots in Standard mode (most probably for a reasons only Asus knows)

You can either set ``Optimized`` mode, and then it will just automatically enable GPU (Standard) when laptop is plugged in and disable it (Eco) when it's on battery .

Or you can add
``"gpu_mode_force_set" : 1,`` to config as explained here

https://github.com/seerge/g-helper/wiki/Power-user-settings#force-last-used-gpu-mode-ie-standard-or-eco-on-app-start--restart

It will set last used mode on start 

Thanks

**Comment by ArnabBCA** [comment]
@seerge  Thank you very much the forced option worked, And thank you for creating this awesome software🔥
