### ISSUE TITLE
Flicker-free Dimming Low brightness

### ISSUE THREAD

**Issue by Deals123** [seerge/g-helper#2748]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I upgraded to v0.176, using Flicker-free Dimming to set the screen to its maximum brightness, the screen was only 70% as bright as usual. After turning off Vari-bright in AMD Softwave, the screen brightness returned to normal, but again using Flicker-free Dimming to adjust the brightness, the screen was only 70% as usual, You need to re-enter AMD Softwave to start and close Vari-bright for it to be effective.

### How to reproduce the bug?

1. Set Flicker-free Dimming to 100% on "Gamut: Native".
2. Turning off Vari-bright in AMD Softwave, screen brightness returned to normal.
3. Again using Flicker-free Dimming to adjust the brightness, screen was only 70% as usual.
4. Re-enter AMD Softwave to start and close Vari-bright for it to be effective, screen brightness returned to normal.

### Logs

[log.txt](https://github.com/user-attachments/files/15879139/log.txt)

### Device and Model

Asus Zephyrus G14 GA403

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.176

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Deals123 hello, 

G-Helper just runs ``AsusSplendid`` utility from Asus System Control Interface package under the hood to set dimming same as AC does. 

There is absolutely nothing that has changed in this regard in 0.176.

How exactly dimming is handled depends on Asus implementation of that feature in AsusSplendid. If it conflicts with VariBright I would advice not to use varibright :)

Thanks
