### ISSUE TITLE
Rebind mouse keys / Add auto toggle to mouse and gamepad mode

### ISSUE THREAD

**Issue by updawg** [seerge/g-helper#2750]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Left and right mouse click are bound to right trigger and right bumper. Additionally, the toggle for gamepad/mouse mode via hotkey doesn't select auto mode.

### Describe the solution you'd like

The ability to rebind left click and right click to gamepad buttons of my choosing.

When a hotkey is selected to toggle gamepad/mouse mode a third option can be toggled to auto. You can select auto from the gui but not the hotkey toggle.

### Device and Model

Asus Rog Ally

**Comment by seerge** [comment]
@updawg hello, 

When you use ``Mouse`` controller mode right joystick + right bumper and right trigger are reserved. And this is absolutely intentional as otherwise this mode won't make any sense.

When you are in ``Gamepad`` mode you already can rebind bumper to something else :)

Also you already can bind any button on controlled to Mouse left / Right

Thnkas

**Comment by updawg** [comment]
But the only way to go back to auto is to open the ghelper app. 

Additionally, the left and right click are swapped unless you leave windows mouse options to swap clicks, but this causes problem when you dock your unit and a real mouse clicks are swapped.

**Comment by seerge** [comment]
@updawg cause assumption is that if you use ``Auto`` - you don't switch it manually, and vice versa.

What do you mean by swapped ? Bumer is Left click, and Trigger is - Right click. Same as it happens when you use Amoury?

**Comment by updawg** [comment]
But if you do switch it manually because the auto function didn't work properly the only way to get it re-enabled is to open the application.

This must have been a leftover from Armory or HandheldCompanion but I noticed my left and right click were swapped when I connected a mouse to the ROG Ally. I then saw the option to swap buttons was checked in the windows mouse settings under the control panel. When I unchecked that option it went to the configuration that you stated, bumper is left click and trigger is right click. I assumed this was backwards as you left click on more objects so the trigger makes more sense (at least in my brain). That is what prompted me to ask for the ability to remap left and right click to the controller buttons of our choosing.

Regardless, thanks for this awesome app. I've completely abandoned Armory / Handheld Companion. These were the last two little items for my personal use case that I'd love to see addressed but I understand your viewpoints.

**Comment by seerge** [comment]
@updawg 

> But if you do switch it manually because the auto function didn't work properly the only way to get it re-enabled is to open the application.

In what circumstances it doesn't work properly ? Current logic - is as soon as app sees FPS counter reported by AMD driver to be non zero for a couple of seconds, it assumes it's a game - and sets Gamepad mode, and if it's zero - goes back to Mouse. 

I would rather improve ``Auto`` honestly

> When I unchecked that option it went to the configuration that you stated, bumper is left click and trigger is right click. 

This is default and correct behavior, same as it is in AC (and there you can't change that neither). I prefer to keep this universal and simple for Mouse mode.
