### ISSUE TITLE
RGB Keyboard Static 2-Colores

### ISSUE THREAD

**Issue by ktoootut** [seerge/g-helper#2751]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hello, would really like to see a 2-colored rgb static setting like in AC. Basically diagonaly slashed one color is on the left and another is on the right.

### Describe the solution you'd like

AC app has it so look no further

### Device and Model

Asus G512LV

**Comment by seerge** [comment]
@ktoootut hello,

I was answering this already. G-Helper shows only modes supported by your keyboard on hardware level.

If you want some exotic custom per-key color settings you can try https://openrgb.org/

Thanks

**Comment by ktoootut** [comment]
okay, thank you for your response!
