### ISSUE TITLE
stay in a refresh rate option permanently

### ISSUE THREAD

**Issue by MoInfinite** [seerge/g-helper#2752]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I prefer to keep my screen at 60hz. But it automatically switches to 165hz when i plug in my charger. For clarity, i choose the 60hz option in the middle, and it still automatically changes to 165hz when i connect the charger. If i disconnect while at 165hz option, it switches back to 60hz. Basically, the two manual options on the right are functioning like the auto option on the left

### Describe the solution you'd like

Can you make it so that the screen stays at 60/165hz when the charger is plugged in and vice versa? There is no point of having an auto button if the other two options switch between each other automatically anyway

### Describe alternatives you've considered

There is no alternative. I have to switch back to 60hz every time i plug in. I sometimes forget to change the refresh rate, which increases my temps

### Device and Model

Asus Zephyrus G14 GA402NV

**Comment by seerge** [comment]
@MoInfinite G-Helper is not changing refresh rate if you have selected 60Hz. It's some other applications do that (most likely Asus Smart Display Control), that you need to stop or uninstall.

[Please make yourself familiar with readme](https://github.com/seerge/g-helper/wiki/Requirements#recommendations-optional)

Thanks

**Comment by MoInfinite** [comment]
thank you
