### ISSUE TITLE
[G15 AE] GPU Fan Curves Not Working (not Zephyrus G15)

### ISSUE THREAD

**Issue by jacky-byte** [seerge/g-helper#2756]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Manual GPU fan curve not working. CPU fan curves works normally.

### How to reproduce the bug?

1. Set the GPU fan curve
2. Click 'Apply Custom Fan Curve'
3. RPM starts increasing higher than the fan curve, despite GPU temperatures remaining the same

### Logs

[log.txt](https://github.com/user-attachments/files/15906024/log.txt)

### Device and Model

Asus ROG Strix G15 Advantage Edition G513QY

### Additional information.

![ghelper fan curve issue](https://github.com/seerge/g-helper/assets/82864247/bf33b795-83c0-42f9-ba6c-fcfaa4b033f0)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.176.0

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@jacky-byte hello,

G-Helper does not control fans anyhow, [they are controlled by BIOS](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds) (as mentioned in [FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)). 

I see that custom fan curve that is being set is exactly same as you have entered it
```
19/06/2024 8:28:21 pm: Mode = 0 : OK
19/06/2024 8:28:22 pm: FanCPU = 1E-35-39-3D-45-49-50-56-00-01-0B-11-23-29-31-31 : OK
19/06/2024 8:28:22 pm: FanGPU = 1E-35-39-3D-45-49-50-56-00-01-0A-14-1E-29-38-38 : OK
```

If it's not followed precisely, this is how Asus has programmed system to behave :) 

You can try to use custom fan curve in ``Turbo`` mode (as in AC "Manual" mode is actually Turbo under the hood with custom fans  / power limits), may be there it will behave a bit different.

If you are not happy with the way BIOS runs fans, you can try [Experimental build with manual fan control](https://github.com/seerge/g-helper/discussions/2272) :)

Thanks
