### ISSUE TITLE
Wrong fan rpm

### ISSUE THREAD

**Issue by Arvilsy** [seerge/g-helper#2757]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Fan rpm on fx507zc4 are wrong. At 5200 it runs around 4800 on cpu and on gpu at 5000 it runs at like 5500.
Wish the calibrate button was still here. 
Also Temps range are also wrong. If I put 60° at 1800 it will run at 2000 in 65 not 60.

### How to reproduce the bug?

Go to power+fan 
Select apply custom fan curve.
Apply any fan rpm and watch it run at different speed than applied

### Logs

[log.txt](https://github.com/user-attachments/files/15906796/log.txt)

### Device and Model

Asus tuf f15 2022(fx507zc4)

### Additional information.

I tried so many other versions of ghelper, clean install of different version of windows, all drivers are up to date. Also in armory crate manual mode everything is exactly how I set it and works flawless. This is issue in ghelper

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.176

### OS

Windows 11 23h2, also tried it at windows 10 22h2 with same problem

**Comment by seerge** [comment]
@Arvilsy hello,

G-Helper does not control fans directly, [they are controlled by BIOS](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds) (as mentioned in [FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)). 

Custom fan curves are **set in % points** under the hood, how exactly they will be treated is still up to BIOS. Fan speed readings from the other side are i**n RPM**, so small discrepancies are absolutely normal.

If you are not happy with the way BIOS runs fans, you can try [Experimental build with manual fan control](https://github.com/seerge/g-helper/discussions/2272) :)

Thanks
