### ISSUE TITLE
Keyboard light automatic brightness adjustment not effective

### ISSUE THREAD

**Issue by lswlc33** [seerge/g-helper#276]
my device:
![image](https://user-images.githubusercontent.com/86835895/233344766-5804c2ec-cad8-4625-aa2b-7ef141604988.png)

Description:

All drivers from My Asus have been installed except for Armoury Crate  
![image](https://user-images.githubusercontent.com/86835895/233343118-9d8f3d13-6567-4e51-8b0e-4cb6a51dbacc.png)  
This option is already enabled  
The keyboard brightness did not change when me change the power status  
can adjust the brightness of the keyboard by using keyboard shortcuts  
log:
2023/4/20 18:38:37: Windows - Power Mode Changed
2023/4/20 18:38:37: AutoSetting for Offline
2023/4/20 18:38:37: BatteryLimit = 100 : OK
2023/4/20 18:38:37: PerformanceMode = 0 : OK
2023/4/20 18:38:37: GPUEco = 1 : OK
2023/4/20 18:38:37: USB-KB = 5D-BA-C5-C4-00
2023/4/20 18:38:37: Eco flag : 1
2023/4/20 18:38:37: Mux flag : -65536
2023/4/20 18:38:38: Screen = 60Hz : OK
2023/4/20 18:38:38: ScreenOverdrive = 0 : OK
2023/4/20 18:38:43: WMI event 88
2023/4/20 18:38:43: Windows - Power Mode Changed
2023/4/20 18:38:43: AutoSetting for Online
2023/4/20 18:38:43: BatteryLimit = 100 : OK
2023/4/20 18:38:43: PerformanceMode = 0 : OK
2023/4/20 18:38:43: USB-KB = 5D-BA-C5-C4-03
2023/4/20 18:38:43: GPUEco = 0 : OK
2023/4/20 18:38:43: Eco flag : 0
2023/4/20 18:38:43: Mux flag : -65536
2023/4/20 18:38:43: Screen = 144Hz : OK
2023/4/20 18:38:43: ScreenOverdrive = 0 : OK

**Comment by seerge** [comment]
@lswlc33 well, in log i see that it tries to set brightness ON / OFF in a log, may be that feature is not supported on your laptop at all?

``2023/4/20 18:38:43: USB-KB = 5D-BA-C5-C4-03``
``2023/4/20 18:38:37: USB-KB = 5D-BA-C5-C4-00``

**Comment by lswlc33** [comment]
@seerge 

it work well in Armoury Crate ，maybe different method

**Comment by lswlc33** [comment]
> [GHelper.zip](https://github.com/seerge/g-helper/files/11285906/GHelper.zip)
> you can try this build where i have added a brightness slider in Extra, if it doesn't work for you neither - probably your keyboard simply doesn't react on this commands at all

i will try later

**Comment by seerge** [comment]
@lswlc33 can you try this one ?
[GHelper.zip](https://github.com/seerge/g-helper/files/11286055/GHelper.zip)

**Comment by seerge** [comment]
Ok, then I will include it in 0.55
