### ISSUE TITLE
The computer's screen brightness adjustment function will fail under certain operations

### ISSUE THREAD

**Issue by tankua0** [seerge/g-helper#2760]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When the graphics card mode is in standard mode, that is, when the integrated graphics card and the independent graphics card work together, the computer's screen brightness adjustment function will be invalid and the brightness will become a fixed value.

### How to reproduce the bug?

Switch the computer to independent graphics mode, restart it, and then switch the computer graphics mode to standard mode in Ghelper, that is, the mode where the integrated graphics and independent graphics work together, and the problem will occur.

### Logs

[log.txt](https://github.com/user-attachments/files/15922642/log.txt)

### Device and Model

ASUS TUF Gaming FX607JI

### Armoury Crate

Uninstalled

### Asus Services

ASUS service is not running

### Version

0.176.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@tankua0 hello, 

When you reboot in Eco mode - Nvidia driver may be acting, and refusing to change brightness sometimes. 

You need to check ``Enable GPU on shutdown`` under ``Extra``, that helps prevent it :) Check this topic for more info https://github.com/seerge/g-helper/discussions/1042

Thanks
