### ISSUE TITLE
Run on startup doesn't work for non admin accounts

### ISSUE THREAD

**Issue by Jacinto27** [seerge/g-helper#2761]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I launch g helper from a non admin account  the run at startup option prompts the UAC and activates, but does not show in either startup apps or task manager, when I turn off the computer and boot into the account it does not work (I can tell because the app is not running, but also because my keyboard lighting stays constantly on and I cannot lower it). When I boot into my admin account it does work as intended. 

Windows 11 23H

### How to reproduce the bug?

(some of the steps here might or might not be related to the bug)
1. Create another account with admin rights (system must already have one)
2. Remove admin rights from this new account 
4. Launch g helper from within the account
5. Click Run at startup (will be promoted with pass request from precious account)
6. (Here it can be checked that it does not appear in startup apps or in the startup tab of task manager )
7. Restart PC and log in into account without privileges, g-helper would not have started 

### Logs

6/21/24 12:50:25 AM: AuraMode: AuraStatic
6/21/24 12:50:25 AM: USB 19B6: 5D-B3-00-00-00-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
6/21/24 12:50:25 AM: USB 19B6: 5D-B5-00-00-00
6/21/24 12:50:25 AM: USB 19B6: 5D-B4
6/21/24 12:50:29 AM: BatteryLimit = 85 : OK
6/21/24 12:50:30 AM: Design Capacity: 76000mWh, Full Charge Capacity: 73833mWh, Health: 0.9714868421052631578947368421%
6/21/24 1:12:05 AM: ------------
6/21/24 1:12:05 AM: App launched: ROG Zephyrus G14 GA402XV_GA402XV :0.176.0.0en-US
6/21/24 1:12:05 AM: Matrix control device was not found on your machine.
6/21/24 1:12:08 AM: NVIDIA GeForce RTX 4060 Laptop GPU
6/21/24 1:12:09 AM: CPU: 9 - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics      - AMD64 Family 25 Model 116 Stepping 1
6/21/24 1:12:10 AM: USB Version: 1049 4.19
6/21/24 1:12:10 AM: AutoSetting for Online
6/21/24 1:12:10 AM: BatteryLimit = 85 : OK
6/21/24 1:12:10 AM: Input available: \\?\hid#vid_0b05&pid_19b6&col03#7&17810770&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 64
6/21/24 1:12:10 AM: USB 19B6|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
6/21/24 1:12:10 AM: Input: \\?\hid#vid_0b05&pid_19b6&col03#7&17810770&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
6/21/24 1:12:10 AM: Init 19B6: 5D-B9
6/21/24 1:12:10 AM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
6/21/24 1:12:10 AM: Init 19B6: 5D-05-20-31-00-1A
6/21/24 1:12:10 AM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
6/21/24 1:12:10 AM: AuraMode: AuraStatic
6/21/24 1:12:10 AM: USB 19B6: 5D-B3-00-00-00-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
6/21/24 1:12:10 AM: USB 19B6: 5D-B5-00-00-00
6/21/24 1:12:10 AM: USB 19B6: 5D-B4
6/21/24 1:12:10 AM: TL140ADXP02-0 HDR: False 10 5 True
6/21/24 1:12:10 AM: Monitor Power On
6/21/24 1:12:10 AM: Lid Open
6/21/24 1:12:10 AM: Lid 19B6: 5D-BA-C5-C4-01
6/21/24 1:12:11 AM: Auto 19B6: 5D-BA-C5-C4-01
6/21/24 1:12:11 AM: Latest version 0.176.0.0
6/21/24 1:12:12 AM: TL140ADXP02-0 HDR: False 10 5 True
6/21/24 1:12:19 AM: AuraMode: AuraStatic
6/21/24 1:12:19 AM: USB 19B6: 5D-B3-00-00-80-FF-80-EB-00-00-FF-FF-FF-00-00-00-00
6/21/24 1:12:19 AM: USB 19B6: 5D-B5-00-00-00
6/21/24 1:12:19 AM: USB 19B6: 5D-B4
6/21/24 1:25:18 AM: ------------

### Device and Model

Asus ROG Zephyrus G14 2023

### Armoury Crate

Uninstalled

**Comment by seerge** [comment]
@Jacinto27 hello,

This is not G-Helper specific, but rather how Windows and it's permissions work with Task Scheduler :)

When you tick ``Run on Startup`` checkbox, app would create a task with the **same** user and permissions it's running with at the moment (i.e. with admin rights). 

If startup task already exists and already requires admin rights, app would prompt UAC in order to modify that startup task.

---

So if you want to run app from account without admin rights, I would suggest to manually open ``Task Scheduler`` in windows and delete existing G-Helper task and then run app normally (w/o admin rights) and tick ``Run on Startup`` :)

But keep in mind, that then some specific features (like GPU Clock offsets) won't be applied on startup if you had one, and they will still prompt UAC if you will try to set them later.

Thanks

**Comment by Jacinto27** [comment]
I found a setup that works, it's very convoluted and not at all recommended for others, but I like it this way:

1. Start from a regular daily use account with admin rights

2. Setup your g-helper configuration.

3. Create a new admin account with an admin password 

4.Remove admin rights from your account

This has kept my configuration including it's "enabled at startup" rights as well as having a separate admin account for security reasons. I am not sure if it affects the GPU clock access rights, but I assume it does since it is run from an administrator account and that is the configuration that stays running.

**Comment by Jacinto27** [comment]
I made the mistake of reinstalling g-helper through chocolatey to streamline updates and did it through the admin terminal but into a non admin account, which has lead to the same issues mentioned on the first post. i.e. profile with run at startup is admin but user profile doesn't have that enabled 😭😭. This is quite a combersome setup  for non admin users of a pc.

**Comment by seerge** [comment]
@Jacinto27 i don't know what exactly chocolately "reinstalls" as app is a single exe file. But I can imagine it has placed exe into some folder with admin only permissions ? or assigned some permissions to exe itself ?

I would recommend to rely on default app auto-updater here. Or just simply download a new version and replace old file. That's it.

**Comment by Jacinto27** [comment]
Yes, I ended up doing something similar, so this is what ultimately worked for me (again, I don't know which precise steps were necessary):

1. Change the installed account into admin.
2. Install an exe from the release pages.
3. Run that exe and activate run at startup
4. Substitute that exe with the one installed through chocolatey
5. Remove the admin level to that account back to the standard user. 

It seems run at startup will only stay on if it is turned on by an admin, but does not "stay" on for the profile of a standard user. 🤷‍♂️

Once the admin and the standard user are "the same account" then it launches the correct configuration for the user, even after that user is no longer admin.

I also don't know what will happen if I run Choco update, will it substitute my exe with one WITHOUT admin rights or will it just work ? I honestly don't want to revert all of what I've done just to avoid it, so I'll tell you the next time G-Helper gets a new release 😅

**Comment by seerge** [comment]
@Jacinto27 i think the only thing that matters in your case is that startup task in windows `Task Scheduler` is created from correct admin user (assuming you want to run app as admin).

The rest - is just portable exe is being started. There is no installation here :)

**Comment by Jacinto27** [comment]
Hm 🤔 I will test this task scheduler method on a buggy installation and see how it goes. Will the CPU acceleration (or lack thereof) affect me if running a non admin instance but manually turning it on through task scheduler ?

**Comment by seerge** [comment]
What is "CPU acceleration" ? And how is related to windows Task Scheduler ? :)

**Comment by Jacinto27** [comment]
OH sorry, I was confusing issues,  I was refering to the GPU Clock offsets mentioned above.

**Comment by seerge** [comment]
@Jacinto27 ah, yes, GPU Clock offsets require admin rights (unfortunately) due to Nvidia API restrictions
