### ISSUE TITLE
color space coverage

### ISSUE THREAD

**Issue by AayushV12** [seerge/g-helper#2763]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

i have all the color space profiles provided in game visual plugin folder,my laptop came with srgb and adobe coverage.the cover drop down menu is only showing default and dcip3.

### How to reproduce the bug?

open ghelper and in coverage drop down
![Untitled](https://github.com/seerge/g-helper/assets/163135158/0d6e8b61-dcb6-4242-8210-9c0f790d802d)

### Logs

[log.txt](https://github.com/user-attachments/files/15935680/log.txt)

### Device and Model

asus rog strix g15 g513rc hn062w

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.176.0

### OS

windows 11 23h2

**Comment by seerge** [comment]
@AayushV12 hello, what specific color profiles does it have ? can you post a screenshot of that folder ?

You may be mixing profiles for different display panels that exist for your model with actual ``sRGB`` or ``DisplayP3`` profiles, that are actually called like that.

**Comment by AayushV12** [comment]
![Untitled](https://github.com/seerge/g-helper/assets/163135158/ed13488f-78f4-4910-aa63-f7e1f4f9d65d)

**Comment by seerge** [comment]
@AayushV12 is that contents of `C:\ProgramData\ASUS\GameVisual` ?

Can you run this build (i have added an extra logging) and post a log from that ?
[GHelper.zip](https://github.com/user-attachments/files/15937373/GHelper.zip)

**Comment by AayushV12** [comment]
yes they were contents of game visual plugin for default icm in other folder for game visual.i ran that build but same again
![weqsf](https://github.com/seerge/g-helper/assets/163135158/e18f2e70-3c7d-4228-abf2-7157e57c3863)
[log.txt](https://github.com/user-attachments/files/15937415/log.txt)

**Comment by seerge** [comment]
@AayushV12 i think i know the reason, some of the color profiles in that folder are without ".icm" extension :) 

Can you try this build ?
[GHelper.zip](https://github.com/user-attachments/files/15937428/GHelper.zip)

**Comment by AayushV12** [comment]
bro its still showing native and dcip3

**Comment by seerge** [comment]
@AayushV12 can you run app as admin and check if it changes anything? And post a log from it.

**Comment by AayushV12** [comment]
[log.txt](https://github.com/user-attachments/files/15937529/log.txt)
same outcome

**Comment by seerge** [comment]
@AayushV12 ok, one more attempt. Try this build and post a log please

[GHelper.zip](https://github.com/user-attachments/files/15937539/GHelper.zip)

**Comment by AayushV12** [comment]
native and dcip3
[log.txt](https://github.com/user-attachments/files/15937550/log.txt)

**Comment by seerge** [comment]
@AayushV12 yeah, but I think I have found one more possible reason

Try this

[GHelper.zip](https://github.com/user-attachments/files/15937560/GHelper.zip)

**Comment by AayushV12** [comment]
same

**Comment by AayushV12** [comment]
[log.txt](https://github.com/user-attachments/files/15937565/log.txt)
same

**Comment by seerge** [comment]
@AayushV12 hm, that's strange

Can you try this build then (with a log)
[GHelper.zip](https://github.com/user-attachments/files/15937579/GHelper.zip)

And if it still does not work - just zip whole GameVisual folder and upload here please, thanks

**Comment by AayushV12** [comment]
fucking hell it worked .fucking hell thanks man love u

**Comment by seerge** [comment]
@AayushV12 great, can you check if this build still works ? Then I guess it's resolved.

What happened - is that you had 2 duplicate `*.icm` profiles for some gamut's, that was causing misbehavior 

[GHelper.zip](https://github.com/user-attachments/files/15937591/GHelper.zip)

**Comment by AayushV12** [comment]
ok thanks for the help hope you get the best in the world
