### ISSUE TITLE
The battery level slash lighting isn't working on G16 GU605MZ

### ISSUE THREAD

**Issue by RabiaHamouda** [seerge/g-helper#2765]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The battery level option within the slash lighting feature is not working for me on ASUS Zephyrus G16 GU605MZ.
I have tried it both with the adapter plugged in and unplugged, but neither is working. The slash lighting is always static when the battery level option is selected, while all other options are functioning correctly for me.

### How to reproduce the bug?

1. Open G-helper
2. Go to slash lighting
3. Select the battery level from the dropdown menu
4. The slash lighting remains static, regardless of the battery percentage

### Logs

[log.txt](https://github.com/user-attachments/files/15938232/log.txt)

### Device and Model

ASUS Zephyrus G16 GU605MZ

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.176.0

### OS

Windows 11 Home 23H2

**Comment by seerge** [comment]
@RabiaHamouda hello,

It fills the bar based on ``your current charge`` / ``your charge limit``.

I see that you have set 70% as a charge limit. Which means bar will be fully filled if actual charge is 70% or above.

Did you try it when charge is lower ? 

From the log I see that I started making last element in the bar a bit dimmer

```
22-Jun-24 11:03:03 PM: Static Data:5E-D3-00-00-07-[4C]-55-55-55-55-55-55-00-00-00-00   4c IS DIMMER ELEMENT< REST IS 55 (max)
````

**Comment by RabiaHamouda** [comment]
Hello @seerge 
Oh, I see now, you're right. Personally, I think it would be better if the slash lighting reflects the actual battery level rather than the charge limit. It just makes more sense to me. Thank you!

**Comment by seerge** [comment]
@RabiaHamouda glad to know it works :)

Battery mode is a contribution of @lgarlati , so I have just accepted it as is.

Thanks
