### ISSUE TITLE
When FN Lock On: press the FN key to use F1-F12

### ISSUE THREAD

**Issue by Jeroen-VdB** [seerge/g-helper#2768]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

No.

### Describe the solution you'd like

I come from a Dell XPS where the `FN Lock` swapped the F1-12 keys with the function keys instead of disabling the F1-12 keys.
Currently, when `FN Lock` is enabled, you can't use the F1-12 keys. It would be nice to be able to use the function keys without pressing the FN key, because I use these more often, but still be able to use the F1-12 keys when pressing the FN key whilst `FN Lock` is enabled.

Related to the FN Lock release: [GHelper v0.76](https://github.com/seerge/g-helper/releases/tag/v0.76)

### Describe alternatives you've considered

Currently, I have the FN Lock disabled and I need to keep reminding myself I have to press the FN key when I want to execute a function key or do not press it when I want to use the F1-12 row. 

### Device and Model

Asus Zephyrus G16 GU605MZ

### Additional information.

It's only a minor inconvenience but I at least wanted to share this idea. Depending on how much work this is, it would be great to have this option.

**Comment by seerge** [comment]
@Jeroen-VdB hello, I was answering this [before](https://github.com/seerge/g-helper/issues/2093). This is not possible 

G-Helper just imitates a real fn-lock by (temporarily) registering F1-F11 as own hotkeys in windows, and processing corresponding actions when you press them. Opposite can't be done.

Thanks

**Comment by Jeroen-VdB** [comment]
Oh it seems I only searched on open issues instead of all. Okay thanks for the quick and clear response!

**Comment by EminGT** [comment]
Is it possible to instead use a different key (I was thinking the "tab" key) to use F1-F12 when fn lock is enabled? Basically could G-Helper undo the fn-lock when a key (like "tab") is held down?
