### ISSUE TITLE
Zenbook S 13 OLED UM5302LA - no CPU temp and fan speed

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#2769]
Hi, some time ago you did tmp build to fix the issue. For me, it worked. Could you please add those changes in the new version too?
Thank you!

> @ke1ne can you check this build and tell if it shows CPU temp and fan speed ?
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/14733398/GHelper.zip)

_Originally posted by @seerge in https://github.com/seerge/g-helper/issues/2197#issuecomment-2016582443_

**Comment by seerge** [comment]
@ke1ne hello,

That can be problematic :)

As I have used another communication protocol to retrieve that (the one I use in [Experimental build with manual fan control](https://github.com/seerge/g-helper/discussions/2272))

I don't plan to make it part of the main app atm, sorry

**Comment by seerge** [comment]
@ke1ne I have updated Experimental build in that thread, with the changes I was doing for you (i.e. reading CPU temp and fan speeds in alternative way)

So if you will use that build - it should show readings for you (+ allow custom fan control that you didn't have on Zenbook probably anyway)

https://github.com/user-attachments/files/15956186/GHelper.zip

**Comment by ke1ne** [comment]
@seerge This build show temperature and fan speed, thank you!

So, this protocol wouldn't happen in the main app stream, and I need to use this custom build?

**Comment by seerge** [comment]
@ke1ne yep, but I'm updating experimental branch with all changes from main. So in all other regards - it's same, except fan communication (in case of custom fan curves).

**Comment by ke1ne** [comment]
@seerge Thank you!

**Comment by seerge** [comment]
@ke1ne experimental build should keep working for your device still

**Comment by ke1ne** [comment]
> @ke1ne experimental build should keep working for your device still

Do you mean the build from this thread #2272?

**Comment by seerge** [comment]
@ke1ne yes, that one uses MyASUS "endpoints" to get temps / fan speeds

**Comment by ke1ne** [comment]
> @ke1ne yes, that one uses MyASUS "endpoints" to get temps / fan speeds

Thank you very much
