### ISSUE TITLE
Screen gets dimmed while at 100% brightness

### ISSUE THREAD

**Issue by Kzmi92** [seerge/g-helper#2770]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I just got a G16.

After uninstalling AC I noticed the screen got a lot dimmer.

I played around with the G Helper settings and noticed that the screen goes full brightness whenever I change the refresh rate. After that, the brightness goes back down gradually.

I have Flicker-free Dimming/Visual Mode set to 100%
I tried all color modes and Gamuts but the issue remains.

In the FAQ I found: Make sure to turn off windows setting System -> Display -> Advanced Display -> Automatically Manage Color for Apps
This is turned off.

I disabled Overdrive in G Helper but this also did not help.

The Windows display brightness is set to 100% and the laptop does not have dynamic brightness.

### How to reproduce the bug?

- Open G-Helper
- Click on any refresh rate Auto, 60Hz or 240Hz + OD and the brightness will go up to 100%
- After a couple of seconds the brightness is a lot more dim again
- Click on any refresh rate again and it will go back to full brightness again for a couple of seconds
- (this does not reflect in the brightness slider in G helper or Windows, it's always 100%)

### Logs

[log.txt](https://github.com/user-attachments/files/15958485/log.txt)

### Device and Model

ASUS ROG Zephyrus G16 GU605MI

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.176.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Kzmi92 hello,

I don't think it's G-Helper dimming your screen :) Do you have any strange settings set in Intel Graphics Command center?

I would suggest using default Visual mode (also no custom gamuts / dimming), and then resetting all settings under Intel Command Center

![image](https://github.com/seerge/g-helper/assets/5920850/be87f62f-91d2-4556-b4f2-9e85fbe63ae3)

**Comment by Kzmi92** [comment]
Hi Serge,

Thanks for the reply.
I hadn't even touched Intel Graphics command center, but just checked and all settings are default.

I also activated Ultimate for the GPU in G-Helper now, so it does not use the Intel GPU, but having the same issue.

The color mode has also been set to Default now, but the problem is still there.

Anything else I could try?

**Comment by seerge** [comment]
@Kzmi92 

Can you also click "Restore Original Colors" under Intel ? (just to make sure)

If it doesn't help check if setting refresh rate in windows also results same behavior (i.e. brightness gets restored and dimmed again) ?

**Comment by seerge** [comment]
@Kzmi92 another thought,

Do you have any other apps running that can interfere and dim screen ? How did you uninstall AC, using official uninstaller from Asus website ? 

Cause this somehow reminds me how AC's "Target mode" works (it dims whole screen except active window). And it's handled by separate mini-app there that runs in background.

**Comment by Kzmi92** [comment]
Really no other apps, got the laptop in like 2 hours ago.
I uninstalled AC using the uninstaller.

I did reset the Intel Original colors.

Also just tried it in Windows and seems to be the same behaviour, switching the Refresh rate makes the screen bright for a couple of seconds before dimming again.

**Comment by seerge** [comment]
@Kzmi92 ok, can you quit G-Helper and change refresh rate in windows again. Does brightness drop as well?

If so - it's definitely either other application doing that or graphics driver itself.

**For other apps** - open ``Task Manager`` and search for "asus" there, if there is anything running still - try to quit it and see if it helps.

**For GPU driver** - try to do a fresh install of them using DDU https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers

**Comment by seerge** [comment]
@Kzmi92 any updates here ? :)

**Comment by Kzmi92** [comment]
Hi, unfortunately still the same issue.
It happens when G-Helper is closed aswell, closed all other Asus apps I could find but to no avail.

It must be a different app that is controlling it, but closed everything I could down in task manager so not sure where it comes from.
I also noticed it happens with darker content. When I load up control panel panel for example, which is white, the screen brightens again.

So does not seem to be a G-Helper issue.

**Comment by seerge** [comment]
@Kzmi92 strange. 

Do you have [Windows Adaptive Brightness](https://support.microsoft.com/en-us/windows/content-adaptive-brightness-control-in-windows-292d1f7f-9e02-4b37-a9c8-dab3e1727e78#:~:text=Select%20the%20Start%20button%2C%20then,contrast%20will%20not%20be%20adjusted.) toggled on by any chance ?

**Comment by seerge** [comment]
@Kzmi92 did you check that setting?

Also I have noticed that Asus has released Asus System Control Interface 3.1.31, apparently addressing washed out / dimmed colors issue on some models, mb that will help

https://rog-forum.asus.com/t5/gaming-notebooks/rog-m16-2022-washed-out-colours-display/m-p/1024850/highlight/true#M7014

**Comment by seerge** [comment]
@Kzmi92 

Control interface by itself won't do much, but it has update new ``AsusSplendid`` tool, so you can try to change Visual Mode in the app to something else and back to default to see if it helps

For color profile - you can run windows Color Management app, there you can see all available profiles, but i doubt it's the reason :)

**Comment by Kzmi92** [comment]
Asus Splendid was not installed on my device, I installed it but don't  think it's compatible.
![image](https://github.com/seerge/g-helper/assets/125756726/b4f7a1cd-6089-4cc3-84c1-bb31d5f2602a)

**Comment by seerge** [comment]
@Kzmi92 I'm talking about other AsusSplendid :) the one that comes with Asus System Control Interface. It's not a standalone app

Do I understand correctly that after getting latest 3.1.31.0 (i linked to you) and changing different Visual Modes in G-Helper your problem with dimming does not disappear ?

**Comment by Kzmi92** [comment]
![image](https://github.com/seerge/g-helper/assets/125756726/0bd7fdac-adc5-44fe-9c6e-96ae8fd0958d)

Indeed, the problem does not dissapear when changing different visual modes in G-Helper.

**Comment by seerge** [comment]
@Kzmi92 ok, thanks for checking :)

Well, on this stage I simply don't know what is the reason here. It's clearly not cause of G-Helper (cause it simply happens w/o app even running), but I was trying to suggest different things to check outside.

Did you try reinstalling GPU drivers as [I was suggesting above](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers) ?

**Comment by seerge** [comment]
Closing this as it's not related to the app in a first place. 

But if you will figure out why it was happening on your device - please let me know. I may add it to FAQ :)

Thanks.

**Comment by seerge** [comment]
@Kzmi92 hello, I had another user complaining about dimming issues on his G16. And as it turned out it was Intel ARC app responsible for that. 

Uninstalling it or stopping from running on startup has solved it for him https://github.com/seerge/g-helper/issues/2987#issuecomment-2295161793

Something you may want to try as well, if it still happens to you.

**Comment by Initialize23** [comment]
Okay after trying everything i finally i got it fixed, its in G helper, extra settings, turn off: Optimal Display Brightness.

<img width="390" alt="Image" src="https://github.com/user-attachments/assets/4fab1535-d3fb-4e19-b6d2-69ba9476308e" />

**Comment by seerge** [comment]
@Initialize23 congratulations :) It's enabled by firmware by default on each reboot. This checkbox lets you disable it.
