### ISSUE TITLE
Zephyrus S17 2021 GX703

### ISSUE THREAD

**Issue by naixx** [seerge/g-helper#2771]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Neither heatmap, nor ambient not working, limited modes available. 

### How to reproduce the bug?

Just run

### Logs

[log.zip](https://github.com/user-attachments/files/15960278/log.zip)

### Device and Model

Zephyrus S17 2021 GX703

### Additional information.

1. Missing modes can be easily added by adding the model to `AppConfig.IsAdvancedRGB()`. It's not the main issue. 
2. After playing with configuration, I see that the app reaches code at `AsusHid.WriteAura`, it writes color buffer to the stream, but nothing changes. There is no exception.
3. I've configured the app to not to have direct rgb at `IsNoDirectRGB` and ambient and heatmap partially works, in sigle color and jerky. That's like a workaround
4. I've tried OpenRGB and it also doesn't support direct write buffer mode. Non of the single keys were colored. However ArtemisRGB previously did this when I had asus services installed. May be a year ago.  

Any ideas what can be done?

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

latest master

### OS

Win 10

**Comment by seerge** [comment]
@naixx hello,

You have quite old device, and it's possible that protocol to set colors is different from all other models there.

If existing different approaches (like marking device as ``IsAdvancedRGB``) doesn't help and also OpenRGB can't do anything - it means there is no open information on how to set colors dynamically on your device.

Does something like Ambient mode exist in Armoury Crate for your model ?

**Comment by seerge** [comment]
@naixx then you can try to record payload that AC sends to keyboard

----

Posting manual from other issue

Install https://www.hhdsoftware.com/device-monitoring-studio (will require reboot)

1. Launch Monitoring Studio, pick Asus keyboard device (one with product id from the list) 
https://github.com/seerge/g-helper/blob/a33089921edbac9a49335f31c7c2cc1c117e5fb0/app/USB/AsusHid.cs#L13

2. Double click on it
![Screenshot 2024-01-20 163125](https://github.com/seerge/g-helper/assets/5920850/e9a28802-08cb-423c-812b-7b526b051a5f)

3. Add ``Packet View`` to Procesing and click ``Start``
![Screenshot 2024-01-20 163136](https://github.com/seerge/g-helper/assets/5920850/354340f0-2fcb-473b-a49f-2e01b25d00a9)

4. Go to Armoury and set some dynamic mode there

5. Check if Monitoring Studio catching a lot of data (Armoury spams it like crazy). If NOT - you probably have selected wrong Asus device on step 2 (so need to re-do it)

6. In Monitoring Studio select ``Tools`` -> ``Save to Log``, and save data
![Screenshot 2024-01-20 163247](https://github.com/seerge/g-helper/assets/5920850/ad480dcf-05bc-43a7-9a80-2984fb68e8a8)

Upload this data here.

**Comment by naixx** [comment]
I assume, it is per key RGB, since I have a rain effect working normally
Will check

**Comment by seerge** [comment]
@naixx any updates here ?

**Comment by seerge** [comment]
Due to lack of response, closed as abandoned
