### ISSUE TITLE
Simplified Chinese Translation Optimization Suggestions

### ISSUE THREAD

**Issue by Charlizsz** [seerge/g-helper#2772]
Hello, since G-Helper can't provide animated display of Slash Lighting, and ASUS's translation of some light effect names can't directly correspond to the original English names, so I've compiled this list of translations for you by referring to the official Chinese translation of Armoury Crate. You can consider adding these translations to G-Helper, which I believe will be easier for Simplified Chinese users to refer to:

Bounce -- 乒乓
Slash -- 切割
Loading -- 压力
Flow -- 流动
Transmission -- 传递
Bit Stream -- 比特流
Phantom -- 幻影
Flux -- 复古波
Specturm -- 光谱
Hazard -- 命运
Interfacing -- 连接
Ramp -- 蔓延
Game Over -- 游戏结束
Start -- 创
Buzzer -- 信号

The following two light effects do not have an official Chinese translation, I have provided a direct translation, you may also consider adding:
Static -- 静态
Battery Level -- 电池电量

Also, "Interval" officially translates to “间隔时间”, I think directly replace the original text is also a reasonable choice.

**Comment by seerge** [comment]
@Charlizsz hello, 

Translations are managed via Crowdin https://crowdin.com/project/g-helper/zh-CN
You can just join there and offer your edits.

Thanks
