### ISSUE TITLE
No control of iGPU or dGPU on G15 AMD

### ISSUE THREAD

**Issue by Speednate54** [seerge/g-helper#2773]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Just picked up an Asus G15 Advantage Edition that is an all AMD computer with the AMD 6800X and upon the install of G Helper there is no control over the GPU at all. All that is there is a button that says "STOP GPU Applications". I previously had this on my G14 and loved it but I'm not sure what went wrong here.

### How to reproduce the bug?

<img width="302" alt="G_Helper snip" src="https://github.com/seerge/g-helper/assets/173742469/b0a4c85c-6a67-48e0-b2cc-6a3a17f1a402">
<img width="302" alt="G_Helper snip" src="https://github.com/seerge/g-helper/assets/173742469/b0a4c85c-6a67-48e0-b2cc-6a3a17f1a402">

### Logs

<img width="302" alt="G_Helper snip" src="https://github.com/seerge/g-helper/assets/173742469/e83209ad-3edb-4ab8-9e59-f9bf1ef962ec">
<img width="302" alt="G_Helper snip" src="https://github.com/seerge/g-helper/assets/173742469/e83209ad-3edb-4ab8-9e59-f9bf1ef962ec">

### Device and Model

ASUS ROG STRIX G15 Advantage edition

### Additional information.

<img width="302" alt="G_Helper snip" src="https://github.com/seerge/g-helper/assets/173742469/a33e1667-3c07-405f-9d6b-a8fcb140e14d">
<img width="302" alt="G_Helper snip" src="https://github.com/seerge/g-helper/assets/173742469/a33e1667-3c07-405f-9d6b-a8fcb140e14d">

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.176

### OS

Window 11 23H2

**Comment by seerge** [comment]
@Speednate54 hello, your device does not support that (you never had those modes in AC as well). 

Please make yourself [familiar with FAQ](https://github.com/seerge/g-helper/wiki/FAQ#i-dont-see-gpu-modes-section).

Thanks.
