### ISSUE TITLE
Sync backlight static color to windows accent color

### ISSUE THREAD

**Issue by osamazakimohammed** [seerge/g-helper#2779]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

not a problem , just something i would like to have in the app

### Describe the solution you'd like

add it to the app

### Device and Model

fx505gt

**Comment by seerge** [comment]
@osamazakimohammed hello, this is a dupicate of https://github.com/seerge/g-helper/issues/1130 :) Please check my response there.

Thanks and sorry.

**Comment by osamazakimohammed** [comment]
thank you
