### ISSUE TITLE
All keyboard keys are switching power mode

### ISSUE THREAD

**Issue by OWxide** [seerge/g-helper#278]
Hello and thanks for the great job you did on g-helper !!

My problem: when the application is installed, any key on the keyboard changes the mode to "silent" then "turbo" then etc... Again, this problem occurs with absolutely all keys on my keyboard, no exceptions. But when i plug an USB keyboard in my laptop the problem is solved.

I have exactly the same problem on Armoury Crate ...

Nothing works ... even after resetting my PC several times no convincing result.

For info :
- Laptop : G513QY (Asus ROG Advantage Edition)
- OS W11 Family 64 bits 10.0.22621
- BIOS version 320 (up to date)

I thank you for your help :)!

**Comment by seerge** [comment]
@OWxide it's definitely not the app's issue, cause it happens with Armoury too. Try to reinstall Asus Control interface https://github.com/seerge/g-helper/discussions/145#discussioncomment-5431447 at least, or even the system :)
