### ISSUE TITLE
Not full translate

### ISSUE THREAD

**Issue by Minemetero** [seerge/g-helper#2781]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

![Screenshot 2024-06-27 135353](https://github.com/seerge/g-helper/assets/156386015/18636616-8395-4da7-b3c7-7e7721e3dd34)

### Describe the solution you'd like

It is better to get a full translation; some are in English, some are in Chinese, and I also suggest that users pick a language they want.

### Device and Model

ROG Zephyrus G16 GU605MV

**Comment by Minemetero** [comment]
If you could tell me where I can put the translated text, I'm glad to help you with it.

**Comment by seerge** [comment]
@Minemetero hello, translations are managed via [Crowdin](https://crowdin.com/project/g-helper). You can join there and offer your translations. Thanks
