### ISSUE TITLE
dGPU not showing up

### ISSUE THREAD

**Issue by icantfixth1s** [seerge/g-helper#2783]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Left laptop running till battery died, charged and turned on ( had a bsod video memory management) to find dgpu not showing up

Tried hard cmos reset

Tried ddu reinstall of drivers still no luck

(issue started post 6:00pm 26/7/2024)

logs have been added.

### How to reproduce the bug?

Let laptop run on battery and not on power while using dGPU till battery depletes and shut downs
Start up 

### Logs

[log.txt](https://github.com/user-attachments/files/16010024/log.txt)

### Device and Model

ASUS TUF A15 FA506IC

### Additional information.

![image](https://github.com/seerge/g-helper/assets/173996147/c505c807-b4ce-49c3-b9ed-eef8ab40d28e)

### Armoury Crate

Uninstalled

### Asus Services

1

### Version

0.176

### OS

Windows 10 22H2

**Comment by seerge** [comment]
@icantfixth1s hello, where exactly is GPU not showing up ?

Your BIOS reports that Eco mode is OFF, so UI shows everything correctly. App didn't turn it off :)

**Comment by icantfixth1s** [comment]
uhm i cant use it and an error 43 shows up dgpu i had fixed this issue in the past by following steps

Edit Power Management Settings via Regedit:

Open Regedit (Registry Editor) by pressing Win + R, typing regedit, and pressing Enter.

Navigate to the appropriate keys to modify PCI Express and Processor Power Management settings.

 

Downgrade BIOS to Version 301:

Download BIOS version 301 from the ASUS support website.

Follow the ASUS instructions to downgrade the BIOS.

 

Change Power Settings:

Go to Control Panel > Hardware and Sound > Power Options.

Select High Performance or create a custom power plan.

Graphics Settings:

In the Advanced settings window, find and expand PCI Express.

Expand Link State Power Management and set it to Off.

Processor Power Management:

Expand Processor power management.

Expand Minimum processor state and set it to 100% for both On battery and Plugged in.

Expand Maximum processor state and ensure it is set to 100% for both On battery and Plugged in.

 

Reinstall Armoury Crate and Remove GHelper:

Uninstall ASUS Armoury Crate and GHelper software.

Reinstall only Armoury Crate if needed, ensuring minimal interference with power management.

 

Use Display Driver Uninstaller ([DDU](https://www.wagnardsoft.com/)) in Safe Mode:

Download DDU.

Boot into Safe Mode (hold Shift while clicking Restart from the Start menu, then navigate to Troubleshoot > Advanced options > Startup Settings > Restart > Press F4 for Safe Mode).

Run DDU to completely remove the existing GPU driver.

 

Install GPU Driver:

Download the latest NVIDIA GPU driver for your RTX 3050 from the [NVIDIA website](https://www.nvidia.com/Download/index.aspx).

Install the driver.(custom>>fresh)

 

Update BIOS to Version 302:

Download BIOS version 302 from the ASUS support website.

Follow the ASUS instructions to update the BIOS.

 

Perform a Hard Reboot:

Shut down your laptop completely.

Hold down the power button for approximately 40 seconds. This process drains any residual power and resets the hardware components.

Wait for the laptop to restart. This hard reboot can help clear any temporary hardware glitches.

 

Toggle Power Modes:

Use Armoury Crate or BIOS settings to switch between power modes (Eco to Standard) multiple times to ensure settings are properly applied.

this time i removed armoury crate and installed ghelper and the issue showed up again

**Comment by seerge** [comment]
@icantfixth1s so GPU is not visible in device manager at all? No matter what you use AC or G-Helper or after hardware resets?

Then it's just looks like a faulty GPU honestly.

**Comment by icantfixth1s** [comment]
it shows up on device manager BUT with an error 43 i usually have to do all the steps above but the error persists or shows up again while using ghelper and it happens when there is a sudden shut down its coupled with extreme power saving mode showing up on ac

**Comment by icantfixth1s** [comment]
> @icantfixth1s so GPU is not visible in device manager at all? No matter what you use AC or G-Helper or after hardware resets?
> 
> Then it's just looks like a faulty GPU honestly.

the steps fix the issue in the past but these issues arises whenever i install ghelper  and use it on a long term

**Comment by seerge** [comment]
@icantfixth1s quick googling has led me to this
https://support.microsoft.com/en-us/windows/fix-graphics-device-problems-with-error-code-43-6f6ae1ec-0bbe-a848-142e-0c6190502842

G-Helper doesn't manager your GPU in realtime anyhow. Same as AC it gives you access to an option to disable (Eco) or enable (Standard) your GPU via AC's endpoint. That's it.

But that's not what happens in your case :) Based from your story (that is very difficult to read to be honest).

It looks more like a faulty GPU that stops working at random, or some underlying driver issues. Did you try a clean system reinstall?

**Comment by icantfixth1s** [comment]
> @icantfixth1s quick googling has led me to this https://support.microsoft.com/en-us/windows/fix-graphics-device-problems-with-error-code-43-6f6ae1ec-0bbe-a848-142e-0c6190502842
> 
> G-Helper doesn't manager your GPU in realtime anyhow. Same as AC it gives you access to an option to disable (Eco) or enable (Standard) your GPU via AC's endpoint. That's it.
> 
> But that's not what happens in your case :) Based from your story (that is very difficult to read to be honest).
> 
> It looks more like a faulty GPU that stops working at random, or some underlying driver issues. Did you try a clean system reinstall?

Whenever I'm using Ghelper and my laptop undergoes a sudden shutdown, on the next boot up I usually encounter an error 43 on dGPU Issues aren't visible while using AC even on a sudden shutdown.

The steps I sent earlier (https://github.com/seerge/g-helper/issues/2783#issuecomment-2194081455)  were the way I usually fixed error 43 and "dGPU" goes missing when I'm exclusively using GHelper which ends up with me using AC again.

I want to use Ghelper instead of AC this is a critical issue that keeps on happening and it seems most of the census just pushes the issue away stating it's a hardware issue. but I have fixed it twice already.

Hope this isn't difficult to read im just having a major anxiety attack :)

**Comment by seerge** [comment]
@icantfixth1s 

> Whenever I'm using Ghelper and my laptop undergoes a sudden shutdown, on the next boot up I usually encounter an error 43 on dGPU Issues aren't visible while using AC even on a sudden shutdown.

Do you have GPU enabled (i.e. Standard mode) when this "shutdowns" happen? At what time did this shutdown happen (so i can check it in app logs) ?

**Comment by icantfixth1s** [comment]
> @icantfixth1s
> 
> > Whenever I'm using Ghelper and my laptop undergoes a sudden shutdown, on the next boot up I usually encounter an error 43 on dGPU Issues aren't visible while using AC even on a sudden shutdown.
> 
> Do you have GPU enabled (i.e. `Standard` mode) when this "shutdowns" happen? At what time did this shutdown happen (so i can check it in app logs) ?

Yes and dGPU was on standard mode and running on battery, Post 6:00pm 26/6/2024.

**Comment by seerge** [comment]
@icantfixth1s i don't see any app restarts around 6PM. I see that you have opened your lid and plugged laptop in.

It was absolutely no interaction with GPU there , app just checked for GPU status and it was reported by BIOS to be ON (which is correct)

```
6/26/2024 12:06:58 PM: Eco flag : 0  <--- APP CHECKS ECO FLAG IS OFF (i.e. STANDARD MODE IS ON)
....
6/26/2024 12:06:58 PM: Mode = 2 : OK
6/26/2024 12:06:58 PM: Monitor Power On
6/26/2024 12:06:58 PM: Lid Open
6/26/2024 12:07:00 PM: STAPM: 34 OK
6/26/2024 12:07:00 PM: STAPM2: 34 OK
6/26/2024 12:07:00 PM: SLOW: 35 OK
6/26/2024 12:07:00 PM: FAST: 35 OK
6/26/2024 12:07:08 PM: Input device not found
6/26/2024 1:45:48 PM: Lid Closed
6/26/2024 1:45:48 PM: TUF Brightness = 128 : OK
6/26/2024 5:15:34 PM: Monitor Power Off
6/26/2024 5:15:34 PM: TUF Brightness = 128 : OK
6/26/2024 6:00:14 PM: Lid Open
6/26/2024 6:00:14 PM: TUF Brightness = 129 : OK

6/26/2024 6:00:15 PM: WMI event 123
6/26/2024 6:00:15 PM: WMI event 88
6/26/2024 6:00:16 PM: Monitor Power On <--- LAPTOP JUST WAKES UP 

6/26/2024 6:00:17 PM: AutoSetting for Online <---- IT SETS MODE FOR PLUGGED IN CASE
6/26/2024 6:00:17 PM: Boost 5
6/26/2024 6:00:17 PM: Eco flag : 0  <---- APP CHECKS FOR GPU AND IT's IS STILL ON
6/26/2024 6:00:17 PM: Mux flag : -65536
...
6/26/2024 6:00:17 PM:  HDR: False 8 0 False
6/26/2024 6:00:17 PM: Mode = 1 : OK
6/26/2024 6:00:17 PM: TUF_KB = 16712125 : OK
6/26/2024 6:00:17 PM: AuraMode: AMBIENT
6/26/2024 6:00:18 PM: HID Device Event: Checking for new ASUS Mice
6/26/2024 6:00:18 PM: TUF Brightness = 129 : OK
6/26/2024 6:00:19 PM: STAPM: 67 OK
6/26/2024 6:00:19 PM: STAPM2: 67 OK
6/26/2024 6:00:19 PM: SLOW: 67 OK
6/26/2024 6:00:19 PM: FAST: 67 OK
```

**Comment by icantfixth1s** [comment]
If you notice at 7:02 pm pc turns off forcefully due to battery discharge and restarts at 3:21 am dgpu is missing.

**Comment by seerge** [comment]
@icantfixth1s based on the log it was no app restarts  till 3:26PM :) before that app was running fine so was the system on battery.

And there it was again no interactions with GPU there.
-----

I see that you are overclocking your GPU. Try to not to do this at all (i.e. just click ``Factory Defaults`` for each mode) and see if it helps.

**Comment by icantfixth1s** [comment]
6/26/2024 7:02:53 PM: Monitor Power Off
6/26/2024 7:02:53 PM: TUF Brightness = 128 : OK

--system undergoes forced shutdown due to battery depletion---

-system turns on at 3:21 am-

6/27/2024 3:21:43 AM: Monitor Power On
6/27/2024 3:21:44 AM: AutoSetting for Offline
6/27/2024 3:21:44 AM: Mode = 2 : OK
6/27/2024 3:21:45 AM: GET GPU CLOCKS: 0, 0
6/27/2024 3:21:46 AM: GET CLOCK LIMIT: NVAPI_ERROR
6/27/2024 3:21:46 AM: Eco flag : 0
6/27/2024 3:21:46 AM: Mux flag : -65536
6/27/2024 3:21:46 AM: \\?\DISPLAY#NCP004D#5&26d69dba&8&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
6/27/2024 3:21:46 AM: \\?\DISPLAY#NCP004D#5&26d69dba&8&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
6/27/2024 3:21:46 AM:  HDR: False 8 8 False
6/27/2024 3:21:46 AM: TUF_KB = 16712125 : OK
6/27/2024 3:21:46 AM: AuraMode: AMBIENT
6/27/2024 3:21:47 AM: STAPM: 34 OK
6/27/2024 3:21:47 AM: STAPM2: 34 OK
6/27/2024 3:21:47 AM: TUF Brightness = 129 : OK
6/27/2024 3:21:47 AM: SLOW: 35 OK
6/27/2024 3:21:47 AM: FAST: 35 OK
6/27/2024 3:21:54 AM: Input device not found
6/27/2024 3:26:01 AM: ------------
6/27/2024 3:26:01 AM: App launched: ASUS TUF Gaming A15 FA506IC_FA506IC :0.176.0.0en-US.
6/27/2024 3:26:02 AM: The matrix control device was not found on your machine.
6/27/2024 3:26:04 AM: dGPU not found
6/27/2024 3:26:05 AM: CPU: 3 - AMD Ryzen 7 4800H with Radeon Graphics          - AMD64 Family 23 Model 96 Stepping 1
6/27/2024 3:26:05 AM: AutoSetting for Offline
6/27/2024 3:26:05 AM: Eco flag : 0
6/27/2024 3:26:05 AM: Mux flag : -65536

Please comment on each of the above relevant code lines I can't seem to understand it.

GPU was not overclocked it was set to default values in ghelper.

**Comment by seerge** [comment]
@icantfixth1s 

Then system didn't force shutdown. It probably went to sleep and hibernated after? Cause windows (and therefore G-Helper) was not restarted there :)  I have already commented on every relevant line. Rest is just notifications it gets from the system and your custom power limits that you set.

Anyway - my point here , is that GPU was not neither disabled nor enabled here.

----

- Try to use all defaults in the app (i.e no custom overclocking, no custom power limits - same as you would have it in AC as your device does not have limits there). Click ``Factory Defaults`` for each mode - and keep it like that for some time.

- Do you have ``Force GPU on shutdown`` checked under ``Extra`` ? If so try to uncheck it. It won't have any effect when GPU is on tho, but will enable it if you have ``Eco`` on 

And see if something changes

**Comment by icantfixth1s** [comment]
Thanks for the input can u kindly tell me what the following lines mean and possible fixes? A quick google search didn't help :)

>6/27/2024 3:21:46 AM: GET CLOCK LIMIT: NVAPI_ERROR
>6/27/2024 3:26:02 AM: The matrix control device was not found on your machine.

**Comment by seerge** [comment]
@icantfixth1s 

```
6/27/2024 3:21:46 AM: GET CLOCK LIMIT: NVAPI_ERROR
```
This is an attempt to READ current GPU overclock settings from Nvidia API
``NVAPI_ERROR`` - means GPU driver is sleeping / not responding. But it's normal (and happens a lot).

```
6/27/2024 3:26:02 AM: The matrix control device was not found on your machine.
```

Is check for Anime Matrix USB device :) you don't have it, so it's all correct.

**Comment by icantfixth1s** [comment]
ah ok whats the final verdict on this issue ( error 43 on GPU) (final comment disabling and enabling GPU in device manager removes the error) and do you know what extreme power saving means in AC?

**Comment by seerge** [comment]
@icantfixth1s 
> final comment disabling and enabling GPU in device manager removes the error

So you don't need to do all that manipulations with the bios , and simple disable / enable for GPU fixes it in fact ?

> and do you know what extreme power saving means in AC?

Usually this is how AC calls ``Eco`` mode :) (i.e. when GPU is shut down via that command I linked above, it's universal for all Asus devices). 

But I can imagine AC also saying same if it can't get GPU status at all (like with that ``NVAPI_ERROR`` thing)

**Comment by seerge** [comment]
@icantfixth1s did you try restarting after ?

**Comment by icantfixth1s** [comment]
> @icantfixth1s did you try restarting after ?

IT WORKS NOW WITHOUT THE BIOS MANIPULATION! no error 43 and other issues.

![image](https://github.com/seerge/g-helper/assets/173996147/8843d969-dff2-4164-8984-eeda12f47fde)

what might be the cause of this issue?

**Comment by seerge** [comment]
@icantfixth1s some hiccup with Nvidia driver not handling power off / hibernation properly or some underlying GPU issue that causes that.

Check your windows power plan settings, what it's set to do when battery charge is critical ?

**Comment by icantfixth1s** [comment]
![image](https://github.com/seerge/g-helper/assets/173996147/e49e4ff8-a92a-4090-bf41-be690d68c73d)

**Comment by seerge** [comment]
@icantfixth1s try to change it to ``Power Off``.

Btw, this could be the reason why it behaves differently with AC and G-Helper. AC uses other power plan (where that setting could be something else?) and G-Helper uses default windows Balanced power plan ... :)

**Comment by icantfixth1s** [comment]
changes made any other fixes i should be performing?

**Comment by seerge** [comment]
@icantfixth1s i would say no :) If you have AC installed, check what setting it had in their custom power plan ?

**Comment by seerge** [comment]
@icantfixth1s btw, you can try to manually "reproduce" your issue.

Unplug laptop and hibernate it. Does it cause same problems ?

**Comment by icantfixth1s** [comment]
> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00090020, 0) - to enable GPU

Tried hibernating, No issues seen.

**Comment by seerge** [comment]
@icantfixth1s ok :) may be it happens only at random hibernations.

Anyway try to use device with auto-hibernation turned off in power plan, to see if it helps.

**Comment by icantfixth1s** [comment]
actually ghelper is acting up, temp info is missing for dGPU now (after hibernation) , but dGPU is usable

![image](https://github.com/seerge/g-helper/assets/173996147/c054095e-ff97-4d11-a86c-29a3e815ae99)

**Comment by seerge** [comment]
@icantfixth1s it reads GPU temp from the Nvidia driver (and I actually see temp on your screenshot) :) 
It could be that Hibernation still somehow conflicts with nvidia driver in your case.

Anyway - just restart if hibernation causes some hiccups.

**Comment by icantfixth1s** [comment]
![image](https://github.com/seerge/g-helper/assets/173996147/1a7cc3ad-0fb7-4442-b197-2cf666997682)

**Comment by icantfixth1s** [comment]
> @icantfixth1s it reads GPU temp from the Nvidia driver (and I actually see temp on your screenshot) :) It could be that Hibernation still somehow conflicts with nvidia driver in your case.
> 
> Anyway - just restart if hibernation causes some hiccups.
 Wrong screenshot
![image](https://github.com/seerge/g-helper/assets/173996147/69ab6888-96cb-4ec2-962a-15f169d8e96b)

**Comment by seerge** [comment]
@icantfixth1s as I have told above, GPU temp is taken from nvidia driver. You can try to restart app or restart device :)

And just avoid hibernation in future / turn it off in power plan.

**Comment by icantfixth1s** [comment]
issues dGPU not showing up fixed.

**Comment by seerge** [comment]
Ok, i'm glad it's resolved :)
