### ISSUE TITLE
Battery charge limit not working properly randomly

### ISSUE THREAD

**Issue by anhkhoa0906** [seerge/g-helper#2785]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I wake up my laptop after let it sleep for about 15 minutes, the battery keep charging even though I set the limit at 80%. I had to change the charge limit again to fix the issue. This is happened randomly, I had faced this issue several of times.

I am very appreciated if you can look into this. Thank you!

### How to reproduce the bug?

1. Let the laptop go to sleep
2. Turn it back on from sleeping
3. Check the battery light signal and it turns into orange

### Logs

[log.txt](https://github.com/user-attachments/files/16010769/log.txt)

### Device and Model

TUF A15 FA506IHR

### Armoury Crate

Uninstalled

### Asus Services

Stopped

### Version

0.176

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@anhkhoa0906 hello,

Actually every time your device wakes up from sleep (i'ts ``Monitor Power On`` event in the log), it re-applies all settings including charge limit, like : 

```
6/27/2024 3:07:50 PM: Monitor Power On
6/27/2024 3:07:50 PM: AutoSetting for Online
6/27/2024 3:07:50 PM: BatteryLimit = 80 : OK
```

Do you have any specific time moment when it happened ?

**Comment by anhkhoa0906** [comment]
Thank you for your reply @seerge,

This is the time that the problem happened, and I had to reapply the charge limit as you can see bellow.

6/27/2024 3:06:58 PM: Monitor Dimmed
6/27/2024 3:07:14 PM: Monitor Power Off
6/27/2024 3:07:14 PM: TUF Brightness = 128 : OK
6/27/2024 3:07:50 PM: Monitor Power On
6/27/2024 3:07:50 PM: AutoSetting for Online
6/27/2024 3:07:50 PM: BatteryLimit = 80 : OK
6/27/2024 3:07:51 PM: ChargerStatus: 1
6/27/2024 3:07:51 PM: Eco flag : 0
6/27/2024 3:07:51 PM: Mux flag : -65536
6/27/2024 3:07:51 PM: \\?\DISPLAY#NCP004D#5&13780ee2&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
6/27/2024 3:07:51 PM: \\?\DISPLAY#NCP004D#5&13780ee2&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
6/27/2024 3:07:51 PM:  HDR: False 8 4 True
6/27/2024 3:07:51 PM: Mode = 0 : OK
6/27/2024 3:07:51 PM: TUF_KB = 983485 : OK
6/27/2024 3:07:51 PM: AuraMode: AuraStatic
6/27/2024 3:07:51 PM: TUF RGB = B4-00-FF-FF-FF-EB : OK
6/27/2024 3:07:51 PM: Monitor Power Off
6/27/2024 3:07:51 PM: Monitor Power On
6/27/2024 3:07:51 PM: TUF Brightness = 128 : OK
6/27/2024 3:07:52 PM: TUF Brightness = 128 : OK
6/27/2024 3:08:00 PM: Input device not found
6/27/2024 3:11:50 PM:  HDR: False 8 4 True
6/27/2024 3:11:52 PM: Design Capacity: 48001mWh, Full Charge Capacity: 34827mWh, Health: 0.7255473844294910522697443803%
6/27/2024 3:11:53 PM: BatteryLimit = 75 : OK
6/27/2024 3:11:54 PM: BatteryLimit = 80 : OK

**Comment by seerge** [comment]
@anhkhoa0906 ok, 

Actually here it has also set limit as soon as system woke up
```
6/27/2024 3:07:50 PM: Monitor Power On
6/27/2024 3:07:50 PM: AutoSetting for Online
6/27/2024 3:07:50 PM: BatteryLimit = 80 : OK
```

The only thing that confuses me a bit is this - a second after
```
6/27/2024 3:07:51 PM: Monitor Power Off
6/27/2024 3:07:51 PM: Monitor Power On
```

Do you know what action was that ? May be you have clicked power button again or something like that ?

**Comment by anhkhoa0906** [comment]
@seerge  I remember that the screen only wake up after I press enter 2 times, the first one the screen did not respond except the keyboard light up. At the second time's press enter, the laptop turn on from black screen into lock screen, and I had to press enter again to access into the windows screen. Maybe that was it.

**Comment by seerge** [comment]
@anhkhoa0906 ok, it could be that turning off / on sleep state second time makes your system reset limits (they are handled by firmware anyway)

I have added a second fallback ``BatteryLimit`` command every time screen turns on. Let me know if it helps

[GHelper.zip](https://github.com/user-attachments/files/16012646/GHelper.zip)

**Comment by anhkhoa0906** [comment]
@seerge After testing several of times, the problem was gone as far as now. Thank you a lot for all your hard work and support the community!

**Comment by seerge** [comment]
@anhkhoa0906 amazing.
