### ISSUE TITLE
FN-Lock not working properly

### ISSUE THREAD

**Issue by cashlycash** [seerge/g-helper#2792]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Some of the Function Keys fail to work without pressing the FN key when FN-Lock is enabled. These keys include
- F4 (Microphone toggle)
- F6 (Display Off)
- F12 (Airplane mode)

FN-Lock also fails to work on binds such `FN + C`, `FN + V`, `FN + KeyPadEnter`. But I am assuming that is done on purpose. 

### How to reproduce the bug?

1. Enable FN-Lock by pressing `FN+C` or whatever your defined keybind is
2. Try using the function keys F4, F6, F12.

### Logs

[log.txt](https://github.com/user-attachments/files/16039202/log.txt)

### Device and Model

ASUS TUF Gaming F15 FX506HCB_FX566HCB

### Armoury Crate

Uninstalled

### Asus Services

1

### Version

0.176.0

### OS

Windows 10 22H2

**Comment by seerge** [comment]
@cashlycash hello,

There are 3 different reasons for each button :) 

For ``F4`` - what specific setting do you have for M3 button under extra? (or just upload config.json here from the app)
For ``F6`` - it actually performs a screenshot action (as this is what it does on all new devices), isn't it better than just screen off ? :)
For ``F12`` - unfortunately you can't "bind" this key in windows, as it's reserved by system. So `FN-Lock` covers only `F1-F11`

As for `FN+C / FN + V / FN + KeypadEnter` they are not covered by `FN-Lock` and it's quite intentional, as it will just make C, V and Enter keys unusable otherwise.

**Comment by cashlycash** [comment]
@seerge thank you for taking your time out to reply
- For `F6` - I did not know that it took a screenshot, would some sort of notification or an indicator such as when used `Win + PrtSc`. Yes agreed, its def better than screen off
- For `F4` - I have it to `Mute Mic` but I have uploaded by [config.json](https://github.com/user-attachments/files/16041588/config.json) as well. Fn + F4 does mute but FN-Lock along with F4 dosn't mute the mic. 
- For `F12` - Alright. Gotcha
Yeah makes sense.

**Comment by seerge** [comment]
@cashlycash 

- I think `FN+F6` is handled on hardware / firmware level in your case :) so it can't be changed.
- For `FN+4` did you see a toast notification saying Mic is muted? 
- Can you just quit G-Helper completely and check if `FN+F4` still mutes mic ? (also to see if it happens on firmware level?)

Cause I simply don't see a single entry about muting mic in your log, and you say it works with `FN+F4`.

**Comment by cashlycash** [comment]
@seerge 
- Yeah I suppose
- FN+F4 Yes
- Yes, it works on a firmware level. My bad.

**Comment by seerge** [comment]
@cashlycash

What kind of notification do you get from FN+F4 when G-Helper is closed ?

**Comment by cashlycash** [comment]
Its just a transluncent prompt in the bottom middle of the screen. Just like the default one that comes with AC with no GHelper. I guess its on driver level only. So is the F12. Since there is a custom driver for the F12 to be airplane mode that is downloaded from the Asus website.

**Comment by seerge** [comment]
@cashlycash 

Do you have Asus services running btw ? (cause it doesn't seem to be according to the log). Can you check it under ``Extra`` and try to stop them to see if it changes the way FN+F4 / F4 work ?

**Comment by cashlycash** [comment]
When I turn off all asus services running then i get the Ghelper indicator on screen. other wise it is the default indiciator. you are right.

**Comment by seerge** [comment]
@cashlycash ok, amazing.

App intentionally skips that action when sees Asus service running (cause it will handle that otherwise)

Closed as resolved

**Comment by Thato1** [comment]
@seerge Sorry to bring this up after so many months, my FN lock shortcut (FN + C) doesn't work at all. Whether I try to turn it on, or off. I always have to open G-Helper to change it

**Comment by seerge** [comment]
@Thato1 hello, what kind of laptop do you have? I think TUF models don't support FN+C for example. You need to either bind something else to FN-Lock or click on a button in UI

**Comment by Thato1** [comment]
It is indeed a TUF A15. Additionally, the visual mode shortcut (Fn + V) also does not work, regardless of whether fn lock is on or off. And both cannot be bound to something else. They are basically useless. Should I just accept this or is there a piece of code I can change?

**Comment by seerge** [comment]
@Thato1 only certain FN+something hotkeys produce a keycode / event that can be captured and processed. 

FN+V , FN + C, M1-M4 and FN+Frow is pretty much it. You can check app log at `%appdata%\GHelper\`. If when you press hotkey - nothing is being added there, then this hotkey does not exist on your device. You can't add it.

You can bind one of macro keys, like M3 to FN-Lock :) Or turn it on in the UI and use permanently (pretty much same as any macbook works)

**Comment by Thato1** [comment]
Nothing is being logged. Okay still a lot better than Armory Crate so I'll keep using it. Thank you very much for your quick response. 

FYI: This is my first gaming PC, and before discovering g-helper, I spent 3 days non-stop, suffering from headaches looking for something that could toggle the FNs, thank you for your service. I'm South African, that's how far your service has gone.⭐⭐⭐⭐⭐

**Comment by seerge** [comment]
@Thato1 then it's not possible to add it. You can try all other hotkeys (i think FN + NUMPAD ENTER was doing something on some TUFs) to see if works ?

Thanks for a nice feedback. App is used by 160 000+ people worldwide at the moment, so no wonder :)
