### ISSUE TITLE
Keyboard Lightning Doesn't Work Properly

### ISSUE THREAD

**Issue by ZhuGene** [seerge/g-helper#2794]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

My Laptop Model is Rog Zephyrus G14 GA403UV, Keyboard Lightning Mode Heatmap & Ambient sometimes work and sometimes don't, Other Modes Work.

### How to reproduce the bug?

I don't know how to reproduce the bug. The bug appears occasionally. I used "Armoury Crate Uninstall Tool" to uninstall Armoury Crate, and in G-Helper I stopped all ASUS services.

### Logs

[log.txt](https://github.com/user-attachments/files/16042960/log.txt)

### Device and Model

ROG Zephyrus G14 GA403UV

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.177.0

### OS

Windows 11 Home Chinese 23H2 22631.3737

**Comment by seerge** [comment]
@ZhuGene hello, 

- I see that you have Asus services running in background. Can you stop them from ``Extra`` settings ? And after that check if there any other Asus apps are running in windows `Task Manager` (just type `asus` in search there) ?
- Do you have windows `Dynamic Lighting` turned on ? If so - turn it OFF 

Thanks

**Comment by nbsriharsha** [comment]
I have the same problem, the keyboard lighting doesn't work. My Dynamic Lighting is off and I have stopped Asus services, Only Asus monitor control is running.

**Comment by ZhuGene** [comment]
This can happen regardless of whether I turn off the ASUS service or not.
Sorry I should have described the issue more clearly. There are 8 keyboard lightning modes, when I use other modes such as Color Loop, the function works, then if I switch to ```Heatmap``` or ```Ambient```, it still stays the effect of the ```previous mode```.
The issue happens occasionally, when I have ASUS services running in background. After I stopped the ASUS services, and restart the laptop, the function works again. 2 days have passed and the issue has not been repeated. 
I'm going to keep watching, and now I want to close the issue. Thank you for helping.

**Comment by seerge** [comment]
@ZhuGene great
