### ISSUE TITLE
Fan Curve for Asus Vivobook S 14X OLED (Ryzen 7 6800H)

### ISSUE THREAD

**Issue by flyrobot27** [seerge/g-helper#2797]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Currently, the fancurve set under fan + power does not work, and it shows up with an Error: Model doesn't support custom fan curve
![image](https://github.com/seerge/g-helper/assets/49768539/b46a4fbb-7a6e-4dbe-9a81-cd1d3225f759)

However, there are other software (Such us AsusFanControlEnhanced: https://github.com/Darren80/AsusFanControlEnhanced) that has functional fan curve editor for my laptop model, and I have tested that it is functional.

### Describe the solution you'd like

Please consider integrating the functionalities provided by other fan control software (e.g. AsusFanControlEnhanced: https://github.com/Darren80/AsusFanControlEnhanced) so that the fan curve editor is functional on this device as well

### Device and Model

ASUS Vivobook S 14X OLED (M5402, AMD Ryzen 6000 Series)

**Comment by seerge** [comment]
@flyrobot27 hello, app says everything correctly - fans are controlled by BIOS, and your model does not support custom fan curves (you never had them in MyASUS neither)

If you want you can try an [Experimental build with manual fan control](https://github.com/seerge/g-helper/discussions/2272) :)

Thanks
