### ISSUE TITLE
[Feature Request] Independantly control CPU Boost behavior when plugged in or on battery

### ISSUE THREAD

**Issue by BlueMellon** [seerge/g-helper#2799]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

The ability to separately set CPU Boost behavior when on battery or plugged in would be a useful feature. This is possible using Windows power management however any changes are removed when changing G Helper profiles.

### Device and Model

Asus Zephyrus G14 GA403UI

### Additional information.

An example of how Windows power management implemented this feature.

![Screenshot 2024-07-01 174220](https://github.com/seerge/g-helper/assets/62859234/2c973270-3577-402d-a07c-c89c5ec39fe0)

**Comment by seerge** [comment]
@BlueMellon hello, this is already possible. 

App remembers last used Mode (Silent / Balaned / Turbo, etc) on battery and when plugged in and switches to it automatically. You can set CPU boost setting for each mode.

Thanks
