### ISSUE TITLE
[FEATURE REQUEST] / [ISSUE] Tray Icon Colour Change Based on Performance Mode / GPU Mode Doesn't Toggle on Power State

### ISSUE THREAD

**Issue by FQMR** [seerge/g-helper#28]
Hi,

Thanks for the great and continuing work.

FEATURE REQUEST
I know you just added OSD for Performance Mode changes, but if the tray icon changed colour based on the mode activated it would be a nice persistent indicator.

ISSUE
GPU Mode does not toggle between ECO and Standard when I change power states from Battery to AC or vice versa even though the box is checked.
Multiple restarts and reinstalls haven't resolved it.
I have a 2020 Zephyrus G14.

Thank you.

**Comment by seerge** [comment]
Do ECO / Standard modes change if you just click on buttons ?

**Comment by FQMR** [comment]
Yes, the buttons work.

Sorry, one more issue only in the latest release:
Discharge rate stuck at 0.3W when it's not accurate.
Previous version worked fine.
And the app is started elevated.

**Comment by seerge** [comment]
I assume hotkeys (like rog and FN f4/f5) also don't work for you ? most probably you don't have Asus Optimization service running (and it's needed for firing hotkey / charge / discharge events from asus) 

You can try to reinstall Asus System Control interface from asus website to fix

**Comment by FQMR** [comment]
Thanks for troubleshooting.

Hotkeys do work.
I tried to reinstall Asus Optimization Service but it said latest version already installed.
I ran the previous version of your app and the discharge rate works.

I also tested the GPU Mode setting. Even if set it to ECO, if I run a game it uses the dGPU.

**Comment by seerge** [comment]
Well, then it means that GPU switch is not working (even if you click on button). Is this feature supported in armory on 2020 model ?

**Comment by FQMR** [comment]
I don't have Armory installed but I'm almost certain it does have the switch, just not ULTIMATE mode which is not available for my model year.

**Comment by seerge** [comment]
Then it means if that switch exists, it's done in some different way than in 2022 model. You can use armory if it works there

**Comment by FQMR** [comment]
Copy, thank you.

**Comment by JuanDelPueblo** [comment]
Not sure if this belongs into a different issue, but in my case (Zephyrus G14 2022), when I unplug my laptop the GPU mode switches from Standard to Eco just fine, however, when I plug my laptop back in it doesn't go to Standard. This might be because I am using an USB-C charger instead of the stock one, but it is a problem nonetheless.

I tried debugging the program to see what's going on, and apparently when unplugging two event codes are outputted to the console (123, 87), but when plugging it back in only the code 123 shows up, the code 88 that's supposed to represent the plugged in state does not. My C# skills are not quite good enough to understand what is going on, but I hope this information might help a bit in understanding the bug.

**Comment by seerge** [comment]
I think you are right, and USB-C charger generates different event ID from barrel adapter, i will add that one too

**Comment by d-anez3** [comment]
> Not sure if this belongs into a different issue, but in my case (Zephyrus G14 2022), when I unplug my laptop the GPU mode switches from Standard to Eco just fine, however, when I plug my laptop back in it doesn't go to Standard. This might be because I am using an USB-C charger instead of the stock one, but it is a problem nonetheless.
> 
> I tried debugging the program to see what's going on, and apparently when unplugging two event codes are outputted to the console (123, 87), but when plugging it back in only the code 123 shows up, the code 88 that's supposed to represent the plugged in state does not. My C# skills are not quite good enough to understand what is going on, but I hope this information might help a bit in understanding the bug.

I'm having this happen on the stock charger too.

**Comment by seerge** [comment]
> I'm having this happen on the stock charger too.

Do you by any chance also have an external monitor connected ?

**Comment by d-anez3** [comment]
> > I'm having this happen on the stock charger too.
> 
> Do you by any chance also have an external monitor connected ?

Yep. If it makes a difference, it's an HDMI monitor connected through a USB-C hub, but the hub doesn't supply any form of power, that's all handled by the stock barrel plug

**Comment by seerge** [comment]
Yeah, but it may mess up with resolution switch :)

Can you guys try a test release https://github.com/seerge/g-helper/releases/download/v0.9.7/GHelper.zip and see if it changes something for you ?

At least GPU switch should work for USB-C charger now

**Comment by seerge** [comment]
> Yep. If it makes a difference, it's an HDMI monitor connected through a USB-C hub, but the hub doesn't supply any form of power, that's all handled by the stock barrel plug

Do you also have your laptop screen off (i.e. external monitor is the only one ON) at the moment you plug charger off ?

**Comment by d-anez3** [comment]
> > Yep. If it makes a difference, it's an HDMI monitor connected through a USB-C hub, but the hub doesn't supply any form of power, that's all handled by the stock barrel plug
> 
> Do you also have your laptop screen off (i.e. external monitor is the only one ON) at the moment you plug charger off ?

No I keep both screens on when plugged into the external monitor

**Comment by seerge** [comment]
Well, then for your particular case - i think external screen is the reason, as my app probably tries to switch a wrong screen on a moment of unplug. I will check if there something can be done here even .. but you can also unplug screen first, and then charger  - it should do a trick.

For others (with USB-C charging) - 0.9.7 should fix it

**Comment by d-anez3** [comment]
> Yeah, but it may mess up with resolution switch :)
> 
> Can you guys try a test release https://github.com/seerge/g-helper/releases/download/v0.9.7/GHelper.zip and see if it changes something for you ?
> 
> At least GPU switch should work for USB-C charger now

I just tested it very quickly and it does seem to work for how I usually plug into my setup at home (plug in stock charger, then USB-C hub for monitor).

**Comment by JuanDelPueblo** [comment]
> Yeah, but it may mess up with resolution switch :)
> 
> Can you guys try a test release https://github.com/seerge/g-helper/releases/download/v0.9.7/GHelper.zip and see if it changes something for you ?
> 
> At least GPU switch should work for USB-C charger now

Can confirm, GPU switching now works for me, thank you.

**Comment by TomBonnot** [comment]
Maybe, it would kinda change the basic icon but, we have blue and green and red (that I can't see because I am on 2021 which is normal), but the G color could change between Silent Balanced and Turbo mode, like the green for Silent, blue for Balanced and Red for Turbo. It is like, more than optional but could be fun !
