### ISSUE TITLE
Screen sudently turn off

### ISSUE THREAD

**Issue by LeoRH123** [seerge/g-helper#2801]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The screen turned off randomly I just switched to the browser window, if you can help me, it would be greatly appreciated in the log I saw something about display at 8:51:35 PM:

### How to reproduce the bug?

1. open some YouTube tabs on the browser
2. open file explorer
3. open excel file
4. switch back to browser 
5. the display turns off

### Logs

[log.txt](https://github.com/user-attachments/files/16076455/log.txt)

### Device and Model

ASUS TUF Gaming A15 FA506QM

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.176.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@LeoRH123 hello,

G-Helper is not a driver and it doesn't manage your screen in realtime anyhow :) If it has turned off during some browser actions - it's probably some other reasons (windows, any other app, etc).

What you see about the screen in a log - is that app just detects the internal screen from windows to check current refresh rate.

- Try to reboot, is the screen working?
- If not - try hardware reset from https://github.com/seerge/g-helper/wiki/Troubleshooting 

Closing this as it's not related to the app. Thanks.
