### ISSUE TITLE
Volume and brightness slider + TDP Slider maybe (?)

### ISSUE THREAD

**Issue by cioppz** [seerge/g-helper#2804]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

When running windows “without explorer.exe”, Rn you lose the ability to control volume and brightness without keeping AC control center running (shortcuts don’t work too).

### Describe the solution you'd like

 Would be nice to have option directly in g help To control volume and brightness. So speaking about adding sliders, would be nice to have a tdp slider just like on deck and other implementations 

### Device and Model

Asus ROG ALLY

**Comment by seerge** [comment]
@cioppz hello, i'm not a big fan of overloading UI with things you can already do with multiple different ways

- You can adjust volume with volume keys on device itself (+ with a slider in windows)
- You can adjust brightness with ``M + DPad Left / Right`` (+ with a slider in windows again)

As for TDP slider - you have it under ``Fans + Power``, also you can create as many custom profiles with custom TDPs as you want (and just switch between them with a hotkey, for example by binding ``Command Center`` button.

Also there is AutoTDP option, that would lower your TDP to desired level automatically :)

Thanks

**Comment by cioppz** [comment]
> @cioppz hello, i'm not a big fan of overloading UI with things you can already do with multiple different ways
> 
> * You can adjust volume with volume keys on device itself (+ with a slider in windows)
> * You can adjust brightness with `M + DPad Left / Right` (+ with a slider in windows again)
> 
> As for TDP slider - you have it under `Fans + Power`, also you can create as many custom profiles with custom TDPs as you want (and just switch between them with a hotkey, for example by binding `Command Center` button.
> 
> Also there is AutoTDP option, that would lower your TDP to desired level automatically :)
> 
> Thanks

The shortcut u mentioned don’t work without explorer running. That’s extacly what I was referring too. A solution could be just to fix this behavior, but please keep the idea in consideration (with some customization option to avoid the overloading of toggles, which is something I can agree with) since for example I remapped those combo to other stuff too. It’s just giving the user more choice

**Comment by cioppz** [comment]
U can reproduce the use case setting something else in this reg key (steam or playnite).
Volume buttons and ur shortcut won’t work.

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon

PLUS an option to set this key in advance feature could also be nice, looking at the use of g helper in a handheld setting.

**Comment by cioppz** [comment]
@seerge i’m recreating a “steamos like” experience, running just my favorite launcher and g helper on boot. Without running explorer I cut a lot of services and around 500mb of ram. I know it’s a particular use case, but I asked there since maybe I wasn’t alone.

**Comment by seerge** [comment]
@cioppz my point is that even if I would add sliders - most probably they won't have effect, if hotkeys don't work :|

Is it possible to keep explorer running, but disable all it's bells and whistles instead (like indexing , network, etc), may be that will keep hotkeys working but free up some memory ?

**Comment by cioppz** [comment]
@seerge that’s not true since other projects have volume control working in that setup. One of which I spoked to the dev and he explained me that using WinAPI  he got across the issue. Don’t know if they do it the same way but also Armory Crate works without explorer.
I can understand if u don’t want to, but I guess it’s doable and it has been done. 
I just wanted to keep using ur great tool, which I love for a lot of its features and lightweight, but in this use case.
Plus even without modifying the ui with slider, just changing the way u set volume with hotkeys could work.
