### ISSUE TITLE
 Question: Uninstalling Armory Crate using AC uninstall tool, leaves Services running

### ISSUE THREAD

**Issue by anodynos** [seerge/g-helper#2805]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

This is NOT a bug in G-Helper, it's only a question about fully uninstalling Armory Crate, and hence related to G-Helper. 

**After uninstalling Armory Crate, using suggested [AC uninstall tool](https://dlcdnets.asus.com/pub/ASUS/mb/14Utilities/Armoury_Crate_Uninstall_Tool.zip?model=armoury%20crate), it  still leaves few Armory Processes running**: 

- Armoury Crate Control Interface
- Armoury Crate Control Interface Monitor
- ArmouryCrateKeyControl

![image](https://github.com/seerge/g-helper/assets/856453/8ffcd29e-fc1a-4ec6-a302-a9b20a3dcd3d)

These correspond to a service still running, "Armoury Crate Control Interface" which is still on "Automatic" startup type. Services still running, after uninstalling Armoury Crate:
![image](https://github.com/seerge/g-helper/assets/856453/92756b20-290b-49e4-a766-0368b1719842)

When I click "Open File Location" on any process, it takes me to **C:\Windows\System32\ASUSACCI** where these residuals exist:

![image](https://github.com/seerge/g-helper/assets/856453/0c56d22b-1493-4a14-a8a4-66786a68e112)

I 've tried at least 3 times (after restarting each time), makes no difference.

System info: 
- On Windows 11 Home as of July 4, 
- Latest ASUS software & drivers
- I still haven't installed neither [Asus System Control Interface](https://dlcdnets.asus.com/pub/ASUS/nb/Image/CustomComponent/ASUSSystemControlInterfaceV3/ASUSSystemControlInterfaceV3.exe) nor G-Helper, cause I don't want to mess it up & I want to have it cleaned properly.

Questions:
- Is this normal and expected? Or maybe an edge/specific case of mine?
- Does anyone know how to remove them properly? I disabled "Armoury Crate Control Interface" service and restarted then deleted "C:\Windows\System32\ASUSACCI" - is this what's required?
- Will it cause problems with G-Helper if I remove them? Or if I don't remove them?

Maybe this will help to update the FAQ on installing.

Finally, the ASUS services still running in my system BEFORE installing G-Helper are 
![image](https://github.com/seerge/g-helper/assets/856453/c1390fdc-2fff-4bae-a531-7986b8ef2d30)
Are these normal? Should I leave them as they are, or do I need to uninstall / disable more services?

Thank you & let me know if you need any more info!

### How to reproduce the bug?

- Install Armory Crate, restart
- Download & execute [AC uninstall tool](https://dlcdnets.asus.com/pub/ASUS/mb/14Utilities/Armoury_Crate_Uninstall_Tool.zip?model=armoury%20crate) & restart
- The processes & service are still here ;-( 

### Logs

Not installed

### Device and Model

ASUS TUF Gaming F15 FX506HF_FX506HF

### Armoury Crate

Uninstalled

### OS

Windows 11 Home 23H2

**Comment by seerge** [comment]
@anodynos hello, it's absolutely normal that those services remain after AC uninstall.

They will keep prompting you to install AC again every time you press M4 / ROG key.

- Just go to G-Helper's ``Extra`` and click ``Stop`` services there. You can always ``Start`` services later if you need them
- Or manually stop / disable them via windows Services app :)

Thanks.

**Comment by seerge** [comment]
@anodynos 

> Does anyone know how to remove them properly? I disabled "Armoury Crate Control Interface" service and restarted then deleted "C:\Windows\System32\ASUSACCI" - is this what's required?
> Will it cause problems with G-Helper if I remove them? Or if I don't remove them?

Please do not delete any folders in System32 in your system :) **It's not needed and has never been asked** 

[Please make yourself familiar with readme](https://github.com/seerge/g-helper/wiki/Requirements)

Thanks
