### ISSUE TITLE
Flicker-free dimming

### ISSUE THREAD

**Issue by icloudvandamme** [seerge/g-helper#2806]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Flicker-free dimming setting is not showing up for my Asus Vivobook Pro 14x OLED (N7400QC) - which is available in MyAsus. 

### How to reproduce the bug?

Open main menu

### Logs

No log

### Device and Model

Asus Vivobook Pro 14x OLED (N7400QC)

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.178

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@icloudvandamme hello, try this build
[GHelper.zip](https://github.com/user-attachments/files/16102902/GHelper.zip)

**Comment by icloudvandamme** [comment]
Thank you for quick response. The issue is still there.

**Comment by seerge** [comment]
@icloudvandamme can you upload the log from the app ?

**Comment by icloudvandamme** [comment]
[log.txt](https://github.com/user-attachments/files/16102982/log.txt)
@seerge

**Comment by seerge** [comment]
@icloudvandamme well, you have typed a wrong model name, it's **M**7400 not N7400

This build should show slider then

[GHelper.zip](https://github.com/user-attachments/files/16102991/GHelper.zip)

**Comment by icloudvandamme** [comment]
Appreciated.
