### ISSUE TITLE
Flow X13 + XG Mobile 3070

### ISSUE THREAD

**Issue by Demitrix2k** [seerge/g-helper#2808]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

This software is great, everything works, but there is an issue with the XG mobile custom fan usage.
Basically, no matter what kind of profile i set to it, the RPM will go to its intended area on the set fan curve, but it will alternate to a an entirely different speed, not a crazy jump, i believe somewhere between 500-1000 rpm range difference, no matter what kind of curve i apply, i can apply an entirely straight line at high rpm or low, does not matter, it will alternate speeds so much its easily recognized hearing it, this is not the case at all with custom fan not applied.

Its as if its either sticking to 1 point of the defined curve and jumps to the next point,instead of following the curve itself in more smaller increments of rpm change, but the rpm does not suggest so, i honestly have no idea as i am completely ignorant on how it operates.
another suspicion i have is that its going back and forth between custom and default profile.

### How to reproduce the bug?

Set any custom fan curve profile for the XG Mobile
Apply custom fan profile
Consistent results across a variety of g-helper releases.

### Logs

Log in attachments due to size preventing me from making post.

### Device and Model

ROG Flow X13 GV301RC

### Additional information.

[config.json](https://github.com/user-attachments/files/16109076/config.json)
[log.txt](https://github.com/user-attachments/files/16109077/log.txt)
[Asus website info for XG Mobile 3070](https://rog.asus.com/us/external-graphic-docks/2021-rog-xg-mobile-model/wtb/)

### Armoury Crate

Uninstalled

### Asus Services

8

### Version

0.178

### OS

Windows 11

**Comment by seerge** [comment]
@Demitrix2k hello, fans (even in XGM) are controlled by firmware / BIOS. This applies even to the way they follow custom fan curves

App sets custom curve and it's accepted

```
7/5/2024 7:02:28 AM: XGM-6512|300:5E-D1-[01-1E-30-36-3E-44-49-4D]-[56-00-09-10-15-29-37-4A-64] <--- 8 temps + 8 fan speeds in payload
7/5/2024 7:02:28 AM: FanCPU = 1E-2D-37-3E-44-49-4D-54-00-01-0B-15-2D-4B-55-64 : OK
7/5/2024 7:02:28 AM: FanGPU = 1E-2D-37-3C-44-48-4C-51-00-01-0F-20-46-4E-5A-64 : OK
```

There is nothing else that can be done here. Most likely you will get same behavior in AC as it sets custom fan curves in a same way :)

**Comment by Demitrix2k** [comment]
Appreciate the fast reply!
As nothing can be done, i will try around and start by doing a complete re-installation of the services + try armory crate for comparison, Thank you.

**Comment by seerge** [comment]
@Demitrix2k ok, sure.

On a side note : `Manual` mode in AC, is actually `Turbo` under the hood + custom fan curves / power limits.

So you may try to check if customizing `Turbo` in G-Helper instead of `Balanced` (that you seem to use) makes any difference first.

Thanks
