### ISSUE TITLE
Weird gpu temp limit.

### ISSUE THREAD

**Issue by AgeStaR** [seerge/g-helper#281]
Hello!
Can you have a look at this topic? https://www.reddit.com/r/ZephyrusG15/comments/12mbvre/asus_rog_zephyrus_weird_temp_limit/
This weird temp limit makes unusable g-helper for me =(.
I've confirmed that with armory crate everything is OK, but when I completely remove AC and start g-helper I started to facing this issue with temp limit =(((

**Comment by seerge** [comment]
@AgeStaR as I literally answered under your commend - app doesn't apply any temp limits. Do you use any custom PPTs? Please upload here your log + config file.

**Comment by seerge** [comment]
Also if you completely remove armoury and don't run g-helper, does your "problem" appear? :)

**Comment by AgeStaR** [comment]
Thank you for a quick reply. Yeah, you are right. There is a temp limit when AC is uninstalled and g-helper is not run.
`Do you use any custom PPTs` - No.
How I can collect logs and config file?

**Comment by seerge** [comment]
1. Then problem is not in G-helper but in Armoury crate uninstaller (that might do something?) OR in Armoury setting some extra settings to GPU.
2. Settings and log file is stored at ``%AppData%\GHelper``

Based on what you explain - it seems like it's Nvidia driver limiting something.

I would just try to do a absolutely clean reinstall of GPU drivers (like run https://www.guru3d.com/files-details/display-driver-uninstaller-download.html as some people advice to completely cleanup nvidia driver and then install it fresh) ?

**Comment by seerge** [comment]
@AgeStaR log is ok :) app is indeed not applying anything, try to check the GPU driver from my previous message tho :)

**Comment by seerge** [comment]
@AgeStaR and let me know about the outcome :)

**Comment by seerge** [comment]
@AgeStaR hello, someone (@Neristee) in neighbour topic seem to have discovered an bios endpoint that allows to set temp limit for GPUs (currenly app doesn't touch it at all)

Can you try to run in powershell as admin following command and see if it has eny effects on you?

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x1200C2; Control_status=86}
```

**Comment by seerge** [comment]
@AgeStaR and what does poweshell command output ? Does it say result  1? 

As for drivers - you can probably reinstall  / reset it just using nvidia software itself? :) I have AMD card and there you can do a "factory reset" of all settings :)

**Comment by seerge** [comment]
@AgeStaR by the way - i just found this topic on reddit https://www.reddit.com/r/linux_gaming/comments/labvm3/nvidia_introduces_the_ability_to_set_gpu_target/

You can use try nvidia's own utility to set target temperature, try to run in powershell something like ``nvidia-smi -gtt 80`` to set target temp.

Or  ``nvidia-smi -i`` - to get current params

Just in case this tool should be located under C:\Windows\System32\DriverStore\FileRepository\nvdm*\nvidia-smi.exe or so

**Comment by AgeStaR** [comment]
> @AgeStaR and what does poweshell command output ? Does it say result 1?

The command return True as a result.

> Just in case this tool should be located under C:\Windows\System32\DriverStore\FileRepository\nvdm*\nvidia-smi.exe or so

Yeah, I've found it and I've done some tests. It is appeared that this tool does not work for laptops at all.

**Comment by seerge** [comment]
@AgeStaR how do you know that there is a temp limit in a first place then? Does HWInfo show that termal limit is 100%? :) 

![Screenshot 2023-04-25 205657](https://user-images.githubusercontent.com/5920850/234375895-00b00ea6-9fc9-4679-9f8e-a983835df680.png)

**Comment by AgeStaR** [comment]
Hm.
When I change mode to silent I see that thermal limit is 75C
When I change mode to balanced/turbo, I see that thermal limit is 87. But with Armory crate there is some another thermal limit... 
I'll try to reinstall video drivers.
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/3184746/234402098-723d6559-cbca-4c63-a5b7-eafc2f9589cd.png">

**Comment by seerge** [comment]
@AgeStaR but that sounds okay as for me ? i.e. in silent bios limits GPU a bit (which is logical) and in balanced/turbo  it sets 87 which is (imho) a very high temp :)

**Comment by AgeStaR** [comment]
Yeah, in hwinfo it is ok :)
But during furmark test in msi afterburner you can see that temp is 71C and power 76W instead of 100W (balanced) or 120W (turbo)

**Comment by seerge** [comment]
@AgeStaR mb problem is not in temp limit at all then ? :) but in power limts ? do you have nvidia dynamic boost enabled ? also try to limit CPU power a bit, may be it will give a bit of a headroom for GPU from Total power that your laptop has

**Comment by seerge** [comment]
Closing as this is not related to g-helper, rather to gpu driver settings :)
