### ISSUE TITLE
add keris II ace

### ISSUE THREAD

**Issue by Viseonn** [seerge/g-helper#2810]
### Mouse / peripheral model and version

Asus Rog Keris II ace

### Armoury Crate Screenshots

hi again can u add  keris II ace 
![Screenshot_5](https://github.com/seerge/g-helper/assets/174374682/8235173c-26a6-44f3-9ba6-916d1ce4b219)
![Screenshot_12](https://github.com/seerge/g-helper/assets/174374682/799934d2-734e-4ddb-9954-41b3e3c781bf)
![Screenshot_11](https://github.com/seerge/g-helper/assets/174374682/e013d45a-09c0-4d68-887d-b4ba641e156a)
![Screenshot_10](https://github.com/seerge/g-helper/assets/174374682/f1c2851d-4a36-4fdf-8df7-0457d0239f0a)
![Screenshot_9](https://github.com/seerge/g-helper/assets/174374682/d4ad73c4-a686-4119-83e1-c7a4631e1dfc)

### USB Details

    =========================== USB Port9 ===========================

Connection Status        : 0x01 (Device is connected)
Port Chain               : 2-9
Properties               : 0x00
 IsUserConnectable       : no
 PortIsDebugCapable      : no
 PortHasMultiCompanions  : no
 PortConnectorIsTypeC    : no
ConnectionIndex          : 0x09 (Port 9)

      ========================== Summary =========================
Vendor ID                : 0x0B05 (ASUSTek Computer Inc.)
Product ID               : 0x1B16
USB Version              : 2.0 -> but Device is Full-Speed only
Port maximum Speed       : High-Speed
Device maximum Speed     : Full-Speed
Device Connection Speed  : Full-Speed
Self powered             : yes
Demanded Current         : 500 mA
Used Endpoints           : 6

      ======================== USB Device ========================

        +++++++++++++++++ Device Information ++++++++++++++++++
Device Description       : USB Bileşik Aygıt
Device Path              : \\?\USB#VID_0B05&PID_1B16#RAMPGDD0023K#{a5dcbf10-6530-11d2-901f-00c04fb951ed} (GUID_DEVINTERFACE_USB_DEVICE)
Kernel Name              : \Device\USBPDO-9
Device ID                : USB\VID_0B05&PID_1B16\RAMPGDD0023K
Hardware IDs             : USB\VID_0B05&PID_1B16&REV_0307 USB\VID_0B05&PID_1B16
Driver KeyName           : {36fc9e60-c465-11cf-8056-444553540000}\0014 (GUID_DEVCLASS_USB)
Driver                   : \SystemRoot\System32\drivers\usbccgp.sys (Version: 10.0.19041.4474  Date: 2024-06-13  Company: Microsoft Corporation)
Driver Inf               : C:\Windows\inf\usb.inf
Legacy BusType           : PNPBus
Class                    : USB
Class GUID               : {36fc9e60-c465-11cf-8056-444553540000} (GUID_DEVCLASS_USB)
Service                  : usbccgp
Enumerator               : USB
Location Info            : Port_#0009.Hub_#0003
Address                  : 9
Location IDs             : PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(9), ACPI(_SB_)#ACPI(PCI0)#ACPI(XHC_)#ACPI(RHUB)#ACPI(HS09)
Container ID             : {7221040f-f8fa-5939-b986-e52dc946d4a0}
Manufacturer Info        : (Standart USB Ana Bilgisayar Denetleyicisi)
Capabilities             : 0x94 (Removable, UniqueID, SurpriseRemovalOK)
Status                   : 0x0180400A (DN_DRIVER_LOADED, DN_STARTED, DN_REMOVABLE, DN_NT_ENUMERATOR, DN_NT_DRIVER)
Problem Code             : 0
Address                  : 9
EnhancedPowerMgmtEnabled : 0
Power State              : D0 (supported: D0, D1, D2, D3, wake from D0, wake from D1, wake from D2)

        +++++++++++++++++ Registry USB Flags +++++++++++++++++
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\usbflags\0B051B160307
 osvc                    : REG_BINARY 00 00

        ---------------- Connection Information ---------------
Connection Index         : 0x09 (Port 9)
Connection Status        : 0x01 (DeviceConnected)
Current Config Value     : 0x01 (Configuration 1)
Device Address           : 0x06 (6)
Is Hub                   : 0x00 (no)
Device Bus Speed         : 0x01 (Full-Speed)
Number of open Pipes     : 0x05 (5 pipes to data endpoints)
Pipe[0]                  : EndpointID=1  Direction=IN   ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x40    bInterval=1   -> 718 Bits/ms = 89750 Bytes/s
Pipe[1]                  : EndpointID=1  Direction=OUT  ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x40    bInterval=1   -> 718 Bits/ms = 89750 Bytes/s
Pipe[2]                  : EndpointID=2  Direction=IN   ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x40    bInterval=1   -> 718 Bits/ms = 89750 Bytes/s
Pipe[3]                  : EndpointID=3  Direction=IN   ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x40    bInterval=1   -> 718 Bits/ms = 89750 Bytes/s
Pipe[4]                  : EndpointID=4  Direction=IN   ScheduleOffset=0  Type=Interrupt  wMaxPacketSize=0x40    bInterval=1   -> 718 Bits/ms = 89750 Bytes/s
Data (HexDump)           : 09 00 00 00 12 01 00 02 00 00 00 40 05 0B 16 1B   ...........@....
                           07 03 01 02 03 01 01 01 00 06 00 05 00 00 00 01   ................
                           00 00 00 07 05 81 03 40 00 01 00 00 00 00 07 05   .......@........
                           01 03 40 00 01 00 00 00 00 07 05 82 03 40 00 01   ..@..........@..
                           00 00 00 00 07 05 83 03 40 00 01 00 00 00 00 07   ........@.......
                           05 84 03 40 00 01 00 00 00 00                     ...@......

        --------------- Connection Information V2 -------------
Connection Index         : 0x09 (9)
Length                   : 0x10 (16 bytes)
SupportedUsbProtocols    : 0x03
 Usb110                  : 1 (yes, port supports USB 1.1)
 Usb200                  : 1 (yes, port supports USB 2.0)
 Usb300                  : 0 (no, port not supports USB 3.0)
 ReservedMBZ             : 0x00
Flags                    : 0x00
 DevIsOpAtSsOrHigher     : 0 (Device is not operating at SuperSpeed or higher)
 DevIsSsCapOrHigher      : 0 (Device is not SuperSpeed capable or higher)
 DevIsOpAtSsPlusOrHigher : 0 (Device is not operating at SuperSpeedPlus or higher)
 DevIsSsPlusCapOrHigher  : 0 (Device is not SuperSpeedPlus capable or higher)
 ReservedMBZ             : 0x00
Data (HexDump)           : 09 00 00 00 10 00 00 00 03 00 00 00 00 00 00 00   ................

    ---------------------- Device Descriptor ----------------------
bLength                  : 0x12 (18 bytes)
bDescriptorType          : 0x01 (Device Descriptor)
bcdUSB                   : 0x200 (USB Version 2.0) -> but device is Full-Speed only
bDeviceClass             : 0x00 (defined by the interface descriptors)
bDeviceSubClass          : 0x00
bDeviceProtocol          : 0x00
bMaxPacketSize0          : 0x40 (64 bytes)
idVendor                 : 0x0B05 (ASUSTek Computer Inc.)
idProduct                : 0x1B16
bcdDevice                : 0x0307
iManufacturer            : 0x01 (String Descriptor 1)
 Language 0x0409         : "ASUSTeK"
iProduct                 : 0x02 (String Descriptor 2)
 Language 0x0409         : "ROG KERIS II ACE"
iSerialNumber            : 0x03 (String Descriptor 3)
 Language 0x0409         : "RAMPGDD0023K"
bNumConfigurations       : 0x01 (1 Configuration)
Data (HexDump)           : 12 01 00 02 00 00 00 40 05 0B 16 1B 07 03 01 02   .......@........
                           03 01                                             ..

    ------------------ Configuration Descriptor -------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x02 (Configuration Descriptor)
wTotalLength             : 0x0074 (116 bytes)
bNumInterfaces           : 0x04 (4 Interfaces)
bConfigurationValue      : 0x01 (Configuration 1)
iConfiguration           : 0x04 (String Descriptor 4)
 Language 0x0409         : "Default configuration"
bmAttributes             : 0xE0
 D7: Reserved, set 1     : 0x01
 D6: Self Powered        : 0x01 (yes)
 D5: Remote Wakeup       : 0x01 (yes)
 D4..0: Reserved, set 0  : 0x00
MaxPower                 : 0xFA (500 mA)
Data (HexDump)           : 09 02 74 00 04 01 04 E0 FA 09 04 00 00 02 03 00   ..t.............
                           00 00 09 21 11 01 00 01 22 22 00 07 05 81 03 40   ...!...."".....@
                           00 01 07 05 01 03 40 00 01 09 04 01 00 01 03 01   ......@.........
                           02 00 09 21 11 01 00 01 22 52 00 07 05 82 03 40   ...!...."R.....@
                           00 01 09 04 02 00 01 03 00 00 00 09 21 11 01 00   ............!...
                           01 22 88 00 07 05 83 03 40 00 01 09 04 03 00 01   ."......@.......
                           03 00 00 00 09 21 11 01 00 01 22 47 01 07 05 84   .....!...."G....
                           03 40 00 01                                       .@..

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x00 (Interface 0)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x02 (2 Endpoints)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x00 (None)
bInterfaceProtocol       : 0x00 (None)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 00 00 02 03 00 00 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 22 00                        .!...."".
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0022 (34 bytes)
Error reading descriptor : ERROR_GEN_FAILURE (due to a obscure limitation of the Win32 USB API, see F1 Help)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x81 (Direction=IN EndpointID=1)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0040 (64 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 81 03 40 00 01                              ....@..

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x01 (Direction=OUT EndpointID=1)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0040 (64 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 01 03 40 00 01                              ....@..

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x01 (Interface 1)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x01 (1 Endpoint)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x01 (Boot Interface)
bInterfaceProtocol       : 0x02 (Mouse)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 01 00 01 03 01 02 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 52 00                        .!...."R.
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0052 (82 bytes)
Error reading descriptor : ERROR_GEN_FAILURE (due to a obscure limitation of the Win32 USB API, see F1 Help)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x82 (Direction=IN EndpointID=2)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0040 (64 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 82 03 40 00 01                              ....@..

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x02 (Interface 2)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x01 (1 Endpoint)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x00 (None)
bInterfaceProtocol       : 0x00 (None)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 02 00 01 03 00 00 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 88 00                        .!...."..
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0088 (136 bytes)
Error reading descriptor : ERROR_GEN_FAILURE (due to a obscure limitation of the Win32 USB API, see F1 Help)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x83 (Direction=IN EndpointID=3)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0040 (64 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 83 03 40 00 01                              ....@..

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x03 (Interface 3)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x01 (1 Endpoint)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x00 (None)
bInterfaceProtocol       : 0x00 (None)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 03 00 01 03 00 00 00                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0111 (HID Version 1.11)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 11 01 00 01 22 47 01                        .!...."G.
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0147 (327 bytes)
Error reading descriptor : ERROR_GEN_FAILURE (due to a obscure limitation of the Win32 USB API, see F1 Help)

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x84 (Direction=IN EndpointID=4)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0040 (64 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 84 03 40 00 01                              ....@..

    ----------------- Device Qualifier Descriptor -----------------
Error                    : ERROR_GEN_FAILURE  (because the device is Full-Speed only)

      -------------------- String Descriptors -------------------
             ------ String Descriptor 0 ------
bLength                  : 0x04 (4 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language ID[0]           : 0x0409 (English - United States)
Data (HexDump)           : 04 03 09 04                                       ....
             ------ String Descriptor 1 ------
bLength                  : 0x10 (16 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language 0x0409          : "ASUSTeK"
Data (HexDump)           : 10 03 41 00 53 00 55 00 53 00 54 00 65 00 4B 00   ..A.S.U.S.T.e.K.
             ------ String Descriptor 2 ------
bLength                  : 0x22 (34 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language 0x0409          : "ROG KERIS II ACE"
Data (HexDump)           : 22 03 52 00 4F 00 47 00 20 00 4B 00 45 00 52 00   ".R.O.G. .K.E.R.
                           49 00 53 00 20 00 49 00 49 00 20 00 41 00 43 00   I.S. .I.I. .A.C.
                           45 00                                             E.
             ------ String Descriptor 3 ------
bLength                  : 0x1A (26 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language 0x0409          : "RAMPGDD0023K"
Data (HexDump)           : 1A 03 52 00 41 00 4D 00 50 00 47 00 44 00 44 00   ..R.A.M.P.G.D.D.
                           30 00 30 00 32 00 33 00 4B 00                     0.0.2.3.K.
             ------ String Descriptor 4 ------
bLength                  : 0x2C (44 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language 0x0409          : "Default configuration"
Data (HexDump)           : 2C 03 44 00 65 00 66 00 61 00 75 00 6C 00 74 00   ,.D.e.f.a.u.l.t.
                           20 00 63 00 6F 00 6E 00 66 00 69 00 67 00 75 00    .c.o.n.f.i.g.u.
                           72 00 61 00 74 00 69 00 6F 00 6E 00               r.a.t.i.o.n.

**Comment by seerge** [comment]
@Viseonn hello, try this build please and post a log from `%appdata%\GHelper` after

Thanks

[GHelper.zip](https://github.com/user-attachments/files/16112216/GHelper.zip)

**Comment by seerge** [comment]
@Viseonn ok great, but i think cause you still have a wireless dongle in the laptop, USB data contains wireless version still :)

As for the mouse itself - do all settings work (when it's connected via wireless) ?

**Comment by seerge** [comment]
@Viseonn i understand that it's not a laptop :)

But according to the log your mouse was detected 

```
5.07.2024 20:38:07: Detected a newROG Keris II Ace . Connecting...
...
5.07.2024 20:38:08: ROG Keris II Ace synchronising. Try 1
5.07.2024 20:38:08: ROG Keris II Ace: Write took 28ms
5.07.2024 20:38:08: ROG Keris II Ace: Read took 2ms
5.07.2024 20:38:08: ROG Keris II Ace: Got Battery Percentage 100% - Charging:False
5.07.2024 20:38:08: ROG Keris II Ace: Got Auto Power Off: Minutes3 - Low Battery Warnning at: 20%
5.07.2024 20:38:08: ROG Keris II Ace: Write took 1ms
5.07.2024 20:38:08: ROG Keris II Ace: Read took 1ms
5.07.2024 20:38:08: ROG Keris II Ace: Active Profile 1, Active DPI Profile: 3
5.07.2024 20:38:08: ROG Keris II Ace: Write took 1ms
5.07.2024 20:38:08: ROG Keris II Ace: Read took 1ms
5.07.2024 20:38:08: ROG Keris II Ace: Write took 0ms
5.07.2024 20:38:08: ROG Keris II Ace: Read took 1ms
5.07.2024 20:38:08: ROG Keris II Ace: Read DPI Setting 1: DPI: 3276800, Color (255, 0, 0)
5.07.2024 20:38:08: ROG Keris II Ace: Read DPI Setting 2: DPI: 3276800, Color (255, 0, 255)
5.07.2024 20:38:08: ROG Keris II Ace: Read DPI Setting 3: DPI: 3276800, Color (0, 0, 255)
5.07.2024 20:38:08: ROG Keris II Ace: Read DPI Setting 4: DPI: 3276800, Color (0, 255, 0)
5.07.2024 20:38:08: ROG Keris II Ace: Write took 0ms
5.07.2024 20:38:08: ROG Keris II Ace: Read took 1ms
```

**Comment by seerge** [comment]
@Viseonn if it doesn't appear - try this build, i have added more verbose logging to it and upload a new log please.

[GHelper.zip](https://github.com/user-attachments/files/16112660/GHelper.zip)

Thanks

**Comment by seerge** [comment]
@Viseonn do you use Omni Receiver by any chance ?

**Comment by IceStormNG** [comment]
> @Viseonn i understand that it's not a laptop :)
> 
> But according to the log your mouse was detected
> 
> ```
> 5.07.2024 20:38:07: Detected a newROG Keris II Ace . Connecting...
> ...
> 5.07.2024 20:38:08: ROG Keris II Ace synchronising. Try 1
> 5.07.2024 20:38:08: ROG Keris II Ace: Write took 28ms
> 5.07.2024 20:38:08: ROG Keris II Ace: Read took 2ms
> 5.07.2024 20:38:08: ROG Keris II Ace: Got Battery Percentage 100% - Charging:False
> 5.07.2024 20:38:08: ROG Keris II Ace: Got Auto Power Off: Minutes3 - Low Battery Warnning at: 20%
> 5.07.2024 20:38:08: ROG Keris II Ace: Write took 1ms
> 5.07.2024 20:38:08: ROG Keris II Ace: Read took 1ms
> 5.07.2024 20:38:08: ROG Keris II Ace: Active Profile 1, Active DPI Profile: 3
> 5.07.2024 20:38:08: ROG Keris II Ace: Write took 1ms
> 5.07.2024 20:38:08: ROG Keris II Ace: Read took 1ms
> 5.07.2024 20:38:08: ROG Keris II Ace: Write took 0ms
> 5.07.2024 20:38:08: ROG Keris II Ace: Read took 1ms
> 5.07.2024 20:38:08: ROG Keris II Ace: Read DPI Setting 1: DPI: 3276800, Color (255, 0, 0)
> 5.07.2024 20:38:08: ROG Keris II Ace: Read DPI Setting 2: DPI: 3276800, Color (255, 0, 255)
> 5.07.2024 20:38:08: ROG Keris II Ace: Read DPI Setting 3: DPI: 3276800, Color (0, 0, 255)
> 5.07.2024 20:38:08: ROG Keris II Ace: Read DPI Setting 4: DPI: 3276800, Color (0, 255, 0)
> 5.07.2024 20:38:08: ROG Keris II Ace: Write took 0ms
> 5.07.2024 20:38:08: ROG Keris II Ace: Read took 1ms
> ```


Look at the DPI Readout... there are some offsets incorrect which makes the UI crash.

**Comment by seerge** [comment]
@IceStormNG that's why I have asked for a verbose log 

```
5.07.2024 21:14:29: ROG Keris II Ace: Read packet: 00 12 04 03 00 ff 00 00 ff 00 ff 00 00 ff 00 ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
5.07.2024 21:14:29: ROG Keris II Ace: Read DPI Setting 1: DPI: 3276800, Color (255, 0, 0)
5.07.2024 21:14:29: ROG Keris II Ace: Read DPI Setting 2: DPI: 3276800, Color (255, 0, 255)
5.07.2024 21:14:29: ROG Keris II Ace: Read DPI Setting 3: DPI: 3276800, Color (0, 0, 255)
5.07.2024 21:14:29: ROG Keris II Ace: Read DPI Setting 4: DPI: 3276800, Color (0, 255, 0)
```

**Comment by IceStormNG** [comment]
> @IceStormNG that's why I have asked for a verbose log (linked above)
> 
> ```
> 5.07.2024 21:14:29: ROG Keris II Ace: Read packet: 00 12 04 03 00 ff 00 00 ff 00 ff 00 00 ff 00 ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 5.07.2024 21:14:29: ROG Keris II Ace: Read DPI Setting 1: DPI: 3276800, Color (255, 0, 0)
> 5.07.2024 21:14:29: ROG Keris II Ace: Read DPI Setting 2: DPI: 3276800, Color (255, 0, 255)
> 5.07.2024 21:14:29: ROG Keris II Ace: Read DPI Setting 3: DPI: 3276800, Color (0, 0, 255)
> 5.07.2024 21:14:29: ROG Keris II Ace: Read DPI Setting 4: DPI: 3276800, Color (0, 255, 0)
> ```

It probably needs to override HasXYDPI() with true. The newer mice seem to have it all.

If it has OmniReceiver, we're screwed for now...  I haven't found a way yet to detect which mouse sits behind the Omni. It will detect every Omni mouse as Harpe Ace.

**Comment by seerge** [comment]
@Viseonn try this build with mouse connected by wire (and post a log again please) :) 

[GHelper.zip](https://github.com/user-attachments/files/16112861/GHelper.zip)

**Comment by seerge** [comment]
@Viseonn wireless may be problematic.

Since your mouse uses Omni Receiver, and it has exactly same USB Product ID as Harpe ace Aimlab . That's why you have seen it in the log.  App simply can't separate them as they identify themselves in a same way ...

**Comment by IceStormNG** [comment]
The only thing that I'm not sure about is the polling rate.. that looks super weird for this with the -96. If we could get a few read outs with the mouse set to 500Hz and 250Hz we might find what is going on

**Comment by IceStormNG** [comment]
> @seerge oh k so does the mouse need wired for to use the app ? and if I unplug the cable and start using with omni after making the settings in the app in a wired way will my settings be the same as in the app ?

The app will not change your mouse settings until you tell it to do. Wireless will detect it as Harpe Ace if it uses Omni Receiver. Most things will still work as they're not that different. But if yo do not change any settings, the mouse settings will stay the same.

**Comment by seerge** [comment]
@IceStormNG my bad, i have just used ``ParsePollingRate`` "fix" from other Keris . Apparently it's not needed here

@Viseonn try this build 
[GHelper.zip](https://github.com/user-attachments/files/16112961/GHelper.zip)

As for wireless - as @IceStormNG have said, it should remember settings done via wire at least ...

**Comment by seerge** [comment]
@Viseonn ok, can you try this build and post a log again?

[GHelper.zip](https://github.com/user-attachments/files/16113062/GHelper.zip)

**Comment by seerge** [comment]
@Viseonn ok, great :) seems like Polling Rate ID needs same fix, i.e. deducting 96 (or 0x60 in hex)

```
5.07.2024 22:01:16: ROG Keris II Ace: Read packet: 00 12 04 00 00 ff ff ff ff ff ff ff ff [63] <--- polling rate 05 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
5.07.2024 22:01:16: ROG Keris II Ace: Pollingrate: 1000 Hz (PR1000Hz)
```

Can you check if everything works as it should ?

**Comment by seerge** [comment]
@Viseonn great. Then I guess we can consider this completed and thank @IceStormNG for tips :)

Unfortunately it's not possible to do a wireless version yet. 
May be in future, if I or @IceStormNG can get access to the mouse physically.

**Comment by IceStormNG** [comment]
The reason is that your mouse has higher DPI can be much higher than the Harpe so it crashes. The battery state should be visible on the main page but if you open the settings it will crash when your DPI is higher than what the harpe can do.

**Comment by IceStormNG** [comment]
I would need Armoury to compare what battery to expect, but the packet log does show 100% (0x64) is sent by the mouse.

**Comment by IceStormNG** [comment]
Likely not. I would first ne 2-3 different mic with Omni receiver here to figure out how to tell which mouse sits behind the receiver. Those mice cost a lot of money and amazon is gonna kill me if I'm abusing their return policy for that all the time.

Back when I implemented the harpe, I somehow got the feeling that ASUS will move forward that all mice and keyboards will use the omni receiver and that it will give me a headache to implement that.

**Comment by JJVVVV** [comment]
> Likely not. I would first ne 2-3 different mic with Omni receiver here to figure out how to tell which mouse sits behind the receiver. Those mice cost a lot of money and amazon is gonna kill me if I'm abusing their return policy for that all the time.
> 
> Back when I implemented the harpe, I somehow got the feeling that ASUS will move forward that all mice and keyboards will use the omni receiver and that it will give me a headache to implement that.

Forgive me for reopening the issue. Is it possible to set the default mouse in config file when using omni ?

**Comment by seerge** [comment]
@JJVVVV if you will read a discussion here - it's not possible atm :)

**Comment by IceStormNG** [comment]
It would be possible to implement but it would be a problem long term and not easy to use for the user, except for some power users that know how to edit config files.

This has to wait until I can get a few Omni Mice here and find a way to identify them AC also can do this so it must be possible. We should make a list of "Omni-Enabled" Mice somewhere so we know which one need it
From my memory, it is the Harpe Ace, the Kerris II Ace and some other that I forgot.
