### ISSUE TITLE
Zephyrus G16 2024 Incorrect Slash Lighting Preset on Lid Close

### ISSUE THREAD

**Issue by sgDanPowell** [seerge/g-helper#2815]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Disabling Slash lighting when Lid is closed works correctly; however, if you keep the Slash lighting enabled when the lid is closed it appears to use the settings you previously had in Armory Crate rather than the setting you have in G Helper.

### How to reproduce the bug?

Keep Slash Lighting Enabled in G Helper.
Close the Laptop Lid.
Observe that the Lighting preset may be different to the one you have selected in G Helper due to it defaulting to the setting selected for closed lid in Armory crate.

### Logs

[log.txt](https://github.com/user-attachments/files/16119363/log.txt)

### Device and Model

GU605MZ-QR045W

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.178.0

### OS

Windows 11 Home 22H2

**Comment by seerge** [comment]
@sgDanPowell hello, it's not AC animation. It's most likely sleep animation that you see when lid is closed :) 

It's controlled by firmware, so you can't change that - only turn it off completely.

**Comment by sgDanPowell** [comment]
The sleep animation can be controlled in Armory Crate IIRC?

**Comment by sgDanPowell** [comment]
<img width="1219" alt="image" src="https://github.com/seerge/g-helper/assets/157390280/640143e7-6046-4726-ab38-e1d7495878b7">


If I have "Stay activate animation pattern when lid is closed"  then it seems to also play the Flux pattern I have selected when lid closed/sleep

This setting carries over even if you uninstall Armory Crate and use only G Helper - if I change to "Static" or another setting in G Helper, it keeps the above setting from armory crate

**Comment by seerge** [comment]
@sgDanPowell 
- Are you sure that it plays animation previously selected, and not just some standard "sleep animation" (same for any mode)? 
- What happens if you would uncheck `Stay activate animation pattern when lid is closed` in AC and close the lid ?

**Comment by sgDanPowell** [comment]
**Armory Crate settings examples:**


Theme is Glitch. Animation Pattern is Bounce. Show Sleep Animation Pattern is TRUE. Stay Activate Animation Pattern when Lid is Closed is set to TRUE. 

<img width="1280" alt="image" src="https://github.com/seerge/g-helper/assets/157390280/684bbcb1-0f93-4053-ae46-e38463f6fa37">



Theme is Glitch. Animation Pattern is Bounce. Show Sleep Animation Pattern is TRUE. Stay Activate Animation Pattern when Lid is Closed is set to FALSE. 

<img width="1280" alt="image" src="https://github.com/seerge/g-helper/assets/157390280/ce6122a6-5d9d-43fe-8525-e05cb3dcd3b4">



Theme is Neoretro. Animation Pattern is Flux. Show Sleep Animation Pattern is TRUE. Stay Activate Animation Pattern when Lid is Closed is set to TRUE. 

<img width="1280" alt="image" src="https://github.com/seerge/g-helper/assets/157390280/3daa75f7-d741-4b2f-b4db-b454613f8220">




Theme is Neoretro. Animation Pattern is Flux. Show Sleep Animation Pattern is TRUE. Stay Activate Animation Pattern when Lid is Closed is set to FALSE.

<img width="1280" alt="image" src="https://github.com/seerge/g-helper/assets/157390280/b332e36e-643c-43a8-86af-95f93e1d9b31">

**Comment by seerge** [comment]
@sgDanPowell great, thanks for the info. But what is the actual behavior of the SlashLighting when lid is closed in those situations ? Does setting "Stay Activate Animation Pattern" to FALSE - keep same animation as when lid is open ?

**Comment by sgDanPowell** [comment]
Just uploading some comparison videos with the above settings now :)

**Comment by sgDanPowell** [comment]
But yes, it appears that when Stay Activate Animation Pattern is flagged as True, it keeps the same pattern. When it is flagged as false, it appears to revert to a generic pulsing pattern as videos show

https://www.transfernow.net/dl/20240708WIQ2n5aT

**Comment by seerge** [comment]
@sgDanPowell ok, blinking pattern is very similar to a default "sleep" animation on any asus keyboard (they also blink).

I know a payload for ``Stay Activate Animation Pattern`` checkbox. And I can simply turn it OFF all the time . Then it will keep default pattern when lid is closed.

I'm just not 100% sure if it's desired behavior for everyone and I also don't want to overcomplicate UI (even more) with an extra checkbox .... 

What do you think ?

**Comment by seerge** [comment]
@sgDanPowell try this build, it should keep default pattern ON all the time

[GHelper.zip](https://github.com/user-attachments/files/16134046/GHelper.zip)

**Comment by sgDanPowell** [comment]
It does for the most part keep the Selected pattern on Lid closed, but it seems to revert back to the default static blinking pattern occasionally

**Comment by sgDanPowell** [comment]
https://github.com/seerge/g-helper/assets/157390280/e7c99796-d3e6-4adc-95dc-a907fe838acc


https://github.com/seerge/g-helper/assets/157390280/2d10ecfa-0804-4742-b6c0-7cd1eb651cde

**Comment by Minemetero** [comment]
How do you keep your laptop clean? I left my finger oil on the slash lighting.

**Comment by sgDanPowell** [comment]
Appears to still revert after a short period of time once the machine is Sleeping with the Lid closed

Armory Crate was uninstalled using the official Armory crate uninstaller tool; unsure what service may be hijacking it back?


https://github.com/seerge/g-helper/assets/157390280/ad98d1b5-50a9-4c6d-bfa4-037cdb7bcdee

**Comment by seerge** [comment]
@sgDanPowell it could be another animation this time - "sleeping" (when laptop goes to sleep and it starts blinking)

I'm not sure if it's a good idea of disabling this one tho, as when you see it - you know that proper hardware sleep is ON now ...
