### ISSUE TITLE
GPU Power

### ISSUE THREAD

**Issue by WinchesterBros** [seerge/g-helper#2816]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Good morning, I have a problem with Ghelper, the "GPU Power" tab does not appear and I have seen that it appears in some images that you published. I have an Asus G15- G513RM and I am very interested in this option since I use it in msi afterburner and I would like to uninstall this program and use it in Ghelper, can you help me? thank you

### How to reproduce the bug?

Good morning, I have a problem with Ghelper, the "GPU Power" tab does not appear and I have seen that it appears in some images that you published. I have an Asus G15- G513RM and I am very interested in this option since I use it in msi afterburner and I would like to uninstall this program and use it in Ghelper, can you help me? thank you

### Logs

Good morning, I have a problem with Ghelper, the "GPU Power" tab does not appear and I have seen that it appears in some images that you published. I have an Asus G15- G513RM and I am very interested in this option since I use it in msi afterburner and I would like to uninstall this program and use it in Ghelper, can you help me? thank you

### Device and Model

Asus G15- G513RM

### Additional information.

![Screenshot_1](https://github.com/seerge/g-helper/assets/174944101/5ccf5ae6-f758-48bc-a7e2-980c53c5d706)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0,179

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@WinchesterBros hello,

Only 2024 models support GPU power adjustment (and only within specific range). Your device doesn't support it - so what you see is absolutely correct :)

If you want to limit GPU power you can either reduce Dynamic Boost slider or limit GPU clocks, it will have some effect too

Thanks

**Comment by WinchesterBros** [comment]
Ok thanks
