### ISSUE TITLE
Disable Slash Lighting when the lid is closed

### ISSUE THREAD

**Issue by madeinua** [seerge/g-helper#2817]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The option to disable the Slash Lighting when closing the lid works properly when I close the lid during use. However, if the lid was closed before I turned on the laptop, the Slash Lighting isn't disabled. As a result, I have to open and then close the lid to disable the lighting.

Could it be possible to disable the Slash Lighting automatically when the laptop (running Windows) starts, even if the lid is already closed?

### How to reproduce the bug?

1. Check the option "Disable on lid close".
2. Restart the laptop with the lid closed.
3. The Slash Lighting remains on.

### Logs

07/07/2024 16:56:44: DisableLidClose True:5E-D8-00-00-02-A5-80-00-00-00-00-00-00-00-00-00-
07/07/2024 16:56:44: Matrix LidClosed: True
07/07/2024 16:56:44: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
07/07/2024 16:56:44: SlashEnable False:5E-D8-02-00-01-80-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:56:44: SleepInit:5E-D2-02-01-08-A1-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:56:44: Sleep False:5E-D3-03-01-08-A1-00-FF-00-02-FF-FF-00-00-00-00-
07/07/2024 16:57:31: ------------
07/07/2024 16:57:32: App launched: ROG Zephyrus G16 GU605MV_GU605MV :0.178.0.0en-US
07/07/2024 16:57:34: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
07/07/2024 16:57:35: C:\ProgramData\ASUS\GameVisual\ASUS_DCIP3.icm DCIP3
07/07/2024 16:57:35: C:\ProgramData\ASUS\GameVisual\ASUS_DisplayP3.icm DisplayP3
07/07/2024 16:57:35: C:\ProgramData\ASUS\GameVisual\ASUS_sRGB.icm sRGB
07/07/2024 16:57:35: NVIDIA GeForce RTX 4060 Laptop GPU
07/07/2024 16:57:36: CPU: 0 - Intel(R) Core(TM) Ultra 9 185H - Intel64 Family 6 Model 170 Stepping 4
07/07/2024 16:57:36: AutoSetting for Online
07/07/2024 16:57:36: Optimization service is running
07/07/2024 16:57:36: Power Plan 381b4222-f694-41f0-9685-ff5bb260df2e:OK
07/07/2024 16:57:36: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 00000000-0000-0000-0000-000000000000:OK
07/07/2024 16:57:36: Eco flag : 0
07/07/2024 16:57:36: Mux flag : 0
07/07/2024 16:57:36: \\?\DISPLAY#SDC41A3#5&2ff708bb&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
07/07/2024 16:57:36: \\?\DISPLAY#DEL423A#5&2ff708bb&0&UID4352#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
07/07/2024 16:57:36: \\?\DISPLAY#SDC41A3#5&2ff708bb&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY2\Monitor0
07/07/2024 16:57:36:  HDR: False 10 1 False
07/07/2024 16:57:37: Mode = 0 : OK
07/07/2024 16:57:37: Init 19B6: 5D-B9
07/07/2024 16:57:37: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
07/07/2024 16:57:37: Init 19B6: 5D-05-20-31-00-1A
07/07/2024 16:57:37: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
07/07/2024 16:57:37: AuraMode: AuraStatic
07/07/2024 16:57:37: USB 19B6: 5D-B3-00-00-00-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
07/07/2024 16:57:37: USB 19B6: 5D-B5-00-00-00
07/07/2024 16:57:37: SlashWakeUp:5E-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E-00-
07/07/2024 16:57:37: SlashWakeUp:5E-C2-00-00-00-00-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: SlashWakeUp:5E-D1-01-00-01-00-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: SlashEnable True:5E-D8-02-00-01-00-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: SlashMode:5E-D2-03-00-0C-00-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: SlashMode:5E-D3-04-00-0C-01-13-02-19-03-13-04-11-05-12-06-
07/07/2024 16:57:37: SlashOptions:5E-D3-03-01-08-AB-FF-01-01-06-55-FF-00-00-00-00-
07/07/2024 16:57:37: SlashSave:5E-D4-00-00-01-AB-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: SleepInit:5E-D2-02-01-08-A1-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: Sleep True:5E-D3-03-01-08-A1-00-FF-01-02-FF-FF-00-00-00-00-
07/07/2024 16:57:37: Monitor Power On
07/07/2024 16:57:37: Lid Open
07/07/2024 16:57:37: Lid 19B6|63: 5A-BA-C5-C4-01
07/07/2024 16:57:37: DisableLidClose True:5E-D8-00-00-02-A5-80-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: Matrix LidClosed: False
07/07/2024 16:57:37: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
07/07/2024 16:57:37: SlashWakeUp:5E-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E-00-
07/07/2024 16:57:37: SlashWakeUp:5E-C2-00-00-00-00-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: SlashWakeUp:5E-D1-01-00-01-00-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: SlashEnable True:5E-D8-02-00-01-00-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: SlashInit:5E-D7-00-00-01-AC-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: SlashInit:5E-D2-02-01-08-AB-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: SlashMode:5E-D2-03-00-0C-00-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: SlashMode:5E-D3-04-00-0C-01-13-02-19-03-13-04-11-05-12-06-
07/07/2024 16:57:37: SlashOptions:5E-D3-03-01-08-AB-FF-01-01-06-55-FF-00-00-00-00-
07/07/2024 16:57:37: SlashSave:5E-D4-00-00-01-AB-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: SleepInit:5E-D2-02-01-08-A1-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:57:37: Sleep True:5E-D3-03-01-08-A1-00-FF-01-02-FF-FF-00-00-00-00-
07/07/2024 16:57:38: Auto 19B6|63: 5A-BA-C5-C4-01
07/07/2024 16:58:08:  HDR: False 10 1 False
07/07/2024 16:58:10: Latest version 0.178.0.0
07/07/2024 16:58:14: Lid Closed
07/07/2024 16:58:14: Lid 19B6|63: 5A-BA-C5-C4-00
07/07/2024 16:58:14: DisableLidClose True:5E-D8-00-00-02-A5-80-00-00-00-00-00-00-00-00-00-
07/07/2024 16:58:14: Matrix LidClosed: True
07/07/2024 16:58:14: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
07/07/2024 16:58:14: SlashEnable False:5E-D8-02-00-01-80-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:58:14: SleepInit:5E-D2-02-01-08-A1-00-00-00-00-00-00-00-00-00-00-
07/07/2024 16:58:14: Sleep False:5E-D3-03-01-08-A1-00-FF-00-02-FF-FF-00-00-00-00-
07/07/2024 16:58:15: Display configuration changed.
07/07/2024 16:58:15: Internal screen off

### Device and Model

Asus Zephyrus G16 GU605

### Armoury Crate

Installed

### Version

0.178

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@madeinua hello, 

How exactly do you turn on the laptop when lid is closed ? If app is not running on that moment, it can't send a command to Slash Lighting to turn off obviously ... :)

**Comment by madeinua** [comment]
@seerge hi,
Scenario 1: Open the lid, press the power button, close the lid, and wait until the window is loaded.
Scenario 2: Restart Windows.

>>  If app is not running on that moment, it can't send a command to Slash Lighting to turn off obviously ... :)
Can the app check if the laptop lid is closed when the app is launched?

**Comment by seerge** [comment]
@madeinua not really, application subscribes for a windows notifications when lid is closed or opened 
https://github.com/seerge/g-helper/blob/ce765376879071c923a1cf3204d9ee7c477bb8a3/app/Settings.cs#L648

But if you start your device with lid closed already - it doesn't know the status of the lid :)

**Comment by madeinua** [comment]
Okay, if it is not possible to check the lid status when the app starts, then the issue cannot be solved..

**Comment by seerge** [comment]
@madeinua  it seems to be so. At least i'm not aware about any way to detect it on start.

All open information refers to listening to windows power-change notifications, like
https://stackoverflow.com/questions/3355606/detect-laptop-lid-closure-and-opening

And this is what app already does.

**Comment by madeinua** [comment]
Okay, thanks.
