### ISSUE TITLE
Built-in Updater

### ISSUE THREAD

**Issue by GriddyYet** [seerge/g-helper#2819]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Please add a built-in app update downloader, I would appreciate this a bunch. I hate the redirected downloads to my browser, because when I download a new version of the app, it would just give me a 'ghelper-1.zip' or 'ghelper-1.exe' and I'd have to remove the current version and rename the new one.

### Describe the solution you'd like

I'd like '.msi' installer as an option. It resonates well with my request as I don't have to go to my selected browser and decrypt '.zip' files. And because it integrates well with the system files.

### Device and Model

Asus Strix Scar G15 G533ZX

**Comment by seerge** [comment]
@GriddyYet hello, there is already a built in updater in the app.

On every new "final" release it shows you a prompt to update, and if answered Yes - downloads and replaces current app with a new build.

https://github.com/seerge/g-helper/blob/main/app/AutoUpdate/AutoUpdateControl.cs

Thanks.
