### ISSUE TITLE
UI clipping bugs

### ISSUE THREAD

**Issue by manciuszz** [seerge/g-helper#282]
I've marked the areas in different colors where the issues are in the screenshots.
<image src='https://user-images.githubusercontent.com/2539661/233730446-8fc150ab-d1e5-450f-9d9b-5861c235c340.png' width='400' /><image src='https://user-images.githubusercontent.com/2539661/233730322-1455235b-d450-4a68-98f7-f291f99a3044.png' width='400' />

Furthermore, shouldn't it be better if 'Disable screen overdrive' checkbox was a button in the 'Laptop Screen' section instead? We sort of already have that "120Hz + OD".

**Comment by seerge** [comment]
@manciuszz what windows is this and what scaling %, cause I don't have this clipping :)
And in general winforms is a big pain in terms of scaling

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11299521/GHelper.zip)
My "blind" attempt to fix

**Comment by manciuszz** [comment]
![image](https://user-images.githubusercontent.com/2539661/233748455-a1d1affc-617d-4abf-b7c9-4a5ce6db8303.png)
![image](https://user-images.githubusercontent.com/2539661/233748462-311038e9-1079-464d-9b4d-10a3a6820ba4.png)

Windows 11 22621.1344
Scaling is 100%.

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11301095/GHelper.zip)
Ok, should be better now :)

**Comment by manciuszz** [comment]
![image](https://user-images.githubusercontent.com/2539661/233793132-61ee164b-3277-4f19-87ab-02ff18ce8a93.png)
![image](https://user-images.githubusercontent.com/2539661/233793146-63582006-93f5-4c44-9889-6ce954896bfa.png)

Fans + Power window looks good. Extra Settings, however, seems like the Keyboard Backlight bottom padding/margin? could be reduced

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11301687/GHelper.zip)
I have "reduced" it a bit but it uses a windows native trackbar element, that has HUGE unremovable padding on the bottom :) so that's how it is. You may write a complain to a team developing Visual Studio tho ;)
