### ISSUE TITLE
 Bland screen after Select GPU direct connection and restart

### ISSUE THREAD

**Issue by Marvin-Jupiter** [seerge/g-helper#2825]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

when I set the display mode as GPU direct direction, the computer restart. But it showed as blank screen. I went into BIOS. And set the display mode as dynamic. The computer  showed well. How can I resolve this situation？

### How to reproduce the bug?

click on"独显直连"

### Logs

NO

### Device and Model

ROG Zephyrus G16 (2023)

### Additional information.

处理器	13th Gen Intel(R) Core(TM) i9-13900H   2.60 GHz
机带 RAM	32.0 GB (31.6 GB 可用)
设备 ID	50E3AE0E-8237-4963-A898-6545C65CF945
产品 ID	00342-30845-05842-AAOEM
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入
版本	Windows 11 家庭中文版
版本号	23H2
安装日期	‎2023/‎3/‎27
操作系统版本	22631.3737
体验	Windows Feature Experience Pack 1000.22700.1009.0

### Armoury Crate

Uninstalled

### Version

0.178.0

### OS

win11 23H2

**Comment by seerge** [comment]
@Marvin-Jupiter hello, can you upload logs from the app as it was explicitly asked in issue template?

Thanks

**Comment by Marvin-Jupiter** [comment]
日志名称:          Application
来源:            Application Error
日期:            2024/7/10 19:21:21
事件 ID:         1000
任务类别:          应用程序崩溃事件
级别:            错误
关键字:           
用户:            MARVIN\52823
计算机:           Marvin
描述:
错误应用程序名称: ASUSSmartDisplayControl.exe，版本: 1.0.0.0，时间戳: 0x660699bf
错误模块名称: ASUSSmartDisplayControl.exe，版本: 1.0.0.0，时间戳: 0x660699bf
异常代码: 0xc0000005
错误偏移量: 0x000028ff
错误进程 ID: 0x0x293C
错误应用程序启动时间: 0x0x1DAD2BB49FA4C55
错误应用程序路径: C:\Program Files (x86)\ASUS\ASUS Smart Display Control\ASUSSmartDisplayControl.exe
错误模块路径: C:\Program Files (x86)\ASUS\ASUS Smart Display Control\ASUSSmartDisplayControl.exe
报告 ID: a2495348-f813-4c49-99d0-b859ac9a1497
错误程序包全名: 
错误程序包相对应用程序 ID: 
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-07-10T11:21:21.1724803Z" />
    <EventRecordID>132635</EventRecordID>
    <Correlation />
    <Execution ProcessID="11020" ThreadID="9224" />
    <Channel>Application</Channel>
    <Computer>Marvin</Computer>
    <Security UserID="S-1-5-21-3091506693-1315481986-1012544600-1001" />
  </System>
  <EventData>
    <Data Name="AppName">ASUSSmartDisplayControl.exe</Data>
    <Data Name="AppVersion">1.0.0.0</Data>
    <Data Name="AppTimeStamp">660699bf</Data>
    <Data Name="ModuleName">ASUSSmartDisplayControl.exe</Data>
    <Data Name="ModuleVersion">1.0.0.0</Data>
    <Data Name="ModuleTimeStamp">660699bf</Data>
    <Data Name="ExceptionCode">c0000005</Data>
    <Data Name="FaultingOffset">000028ff</Data>
    <Data Name="ProcessId">0x293c</Data>
    <Data Name="ProcessCreationTime">0x1dad2bb49fa4c55</Data>
    <Data Name="AppPath">C:\Program Files (x86)\ASUS\ASUS Smart Display Control\ASUSSmartDisplayControl.exe</Data>
    <Data Name="ModulePath">C:\Program Files (x86)\ASUS\ASUS Smart Display Control\ASUSSmartDisplayControl.exe</Data>
    <Data Name="IntegratorReportId">a2495348-f813-4c49-99d0-b859ac9a1497</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>

**Comment by Marvin-Jupiter** [comment]
日志名称:          Application
来源:            Application Error
日期:            2024/7/10 19:21:41
事件 ID:         1000
任务类别:          应用程序崩溃事件
级别:            错误
关键字:           
用户:            MARVIN\52823
计算机:           Marvin
描述:
错误应用程序名称: ASUSSmartDisplayControl.exe，版本: 1.0.0.0，时间戳: 0x660699bf
错误模块名称: ASUSSmartDisplayControl.exe，版本: 1.0.0.0，时间戳: 0x660699bf
异常代码: 0xc0000005
错误偏移量: 0x000028ff
错误进程 ID: 0x0x3F84
错误应用程序启动时间: 0x0x1DAD2BB566BFC5F
错误应用程序路径: C:\Program Files (x86)\ASUS\ASUS Smart Display Control\ASUSSmartDisplayControl.exe
错误模块路径: C:\Program Files (x86)\ASUS\ASUS Smart Display Control\ASUSSmartDisplayControl.exe
报告 ID: de48e904-4e65-4e97-904b-22db26e5682b
错误程序包全名: 
错误程序包相对应用程序 ID: 
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-07-10T11:21:41.3590463Z" />
    <EventRecordID>132638</EventRecordID>
    <Correlation />
    <Execution ProcessID="17056" ThreadID="11996" />
    <Channel>Application</Channel>
    <Computer>Marvin</Computer>
    <Security UserID="S-1-5-21-3091506693-1315481986-1012544600-1001" />
  </System>
  <EventData>
    <Data Name="AppName">ASUSSmartDisplayControl.exe</Data>
    <Data Name="AppVersion">1.0.0.0</Data>
    <Data Name="AppTimeStamp">660699bf</Data>
    <Data Name="ModuleName">ASUSSmartDisplayControl.exe</Data>
    <Data Name="ModuleVersion">1.0.0.0</Data>
    <Data Name="ModuleTimeStamp">660699bf</Data>
    <Data Name="ExceptionCode">c0000005</Data>
    <Data Name="FaultingOffset">000028ff</Data>
    <Data Name="ProcessId">0x3f84</Data>
    <Data Name="ProcessCreationTime">0x1dad2bb566bfc5f</Data>
    <Data Name="AppPath">C:\Program Files (x86)\ASUS\ASUS Smart Display Control\ASUSSmartDisplayControl.exe</Data>
    <Data Name="ModulePath">C:\Program Files (x86)\ASUS\ASUS Smart Display Control\ASUSSmartDisplayControl.exe</Data>
    <Data Name="IntegratorReportId">de48e904-4e65-4e97-904b-22db26e5682b</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>

**Comment by seerge** [comment]
@Marvin-Jupiter hello, what's that ?

**Comment by Marvin-Jupiter** [comment]
Hello, thank you for your response to my question. I tried to find the log using the method mentioned in (https://github.com/seerge/g-helper/blob/main/docs/README.zh-CN.md?plain=1). Unfortunately, I couldn't find any error messages related to ghelper. Therefore, I have uploaded the error log that occurred when I encountered the problem.

**Comment by seerge** [comment]
@Marvin-Jupiter You need to upload app log from `%appdata%\GHelper`

**Comment by seerge** [comment]
As for Asus Smart Display control, it's advised to uninstall it as it will interfere and try to change refresh rate when it's not needed
https://github.com/seerge/g-helper/wiki/Requirements#recommendations-optional

You can always download and install it back from asus website just in case

**Comment by Marvin-Jupiter** [comment]
[log.txt](https://github.com/user-attachments/files/16164531/log.txt)

**Comment by seerge** [comment]
@Marvin-Jupiter ok, thanks.

I see that you were in ``Eco`` mode (with GPU disabled) and then rebooted directly into `Ultimate`

```
2024/7/10 18:27:35: App launched: ROG Zephyrus G16 GU603VV_GU603VV :0.178.0.0zh-CN
...
2024/7/10 19:20:29: Eco flag : 1 <--- Eco mode
2024/7/10 19:20:29: Mux flag : 1
..
2024/7/10 19:20:35: GPUMux = 0 : OK <-- Ultimate
```

As I have mentioned above, it's always better to set `Standard` first and only then `Ultimate` . Even tho majority of the models do that automatically anyway.

**Comment by seerge** [comment]
@Marvin-Jupiter I have added your model (GU603VV) to the list of devices where G-Helper will force `Standard` mode prior to rebooting to `Ultimate`

Try this build

[GHelper.zip](https://github.com/user-attachments/files/16164701/GHelper.zip)

**Comment by Marvin-Jupiter** [comment]
Hello, thank you for your response. This time, the execution did not encounter this issue.

**Comment by seerge** [comment]
Great. Closing as resolved then
