### ISSUE TITLE
ZenBook UX482EA_UX482EA Screen Brightness

### ISSUE THREAD

**Issue by brimwats** [seerge/g-helper#2826]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I love the g-helper over all of the ASUS things! It's bren great. The only problem is that I can't seem to adjust beightness to the high levels. I did the reset of the power config and the DISM reset in troubleshooting but it still is quite dim--I'd say it is around 80% of the maximum allowed by MyASUS

### How to reproduce the bug?

1. Increase brightness to maximum. 
2. Brightness is not at maximum
3. not sure what else to add here!

![image](https://github.com/seerge/g-helper/assets/73113656/f0ed26de-add2-4844-bc02-1a9dc95171af)
![image](https://github.com/seerge/g-helper/assets/73113656/a1d874bb-0eac-4da6-92a5-6a555616ef54)

![image](https://github.com/seerge/g-helper/assets/73113656/5d93566f-2601-4fd7-87b1-56989444bf50)
![image](https://github.com/seerge/g-helper/assets/73113656/879ff926-16ff-4de5-9bc3-384d8425bbbf)

### Logs

[log.txt](https://github.com/user-attachments/files/16166942/log.txt)

### Device and Model

ZenBook UX482EA_UX482EA

### Armoury Crate

Never installed

### Asus Services

3

### Version

0.178.0

### OS

Windows 11 Pro 23H2 22631.3737

**Comment by seerge** [comment]
@brimwats hello, but G-Helper doesn't manage your brightness :)

How do you know that your brightness is not at maximum level, when it was there last time and what happened after?

Try to go to Intel Graphics Center (or how it's called on Intel devices) and click Reset there
![image](https://github.com/seerge/g-helper/assets/5920850/34a4717c-2d63-4e1b-8ab2-eb240ee9e0c1)

May be it's some Intel driver hiccup ?

**Comment by brimwats** [comment]
That's weird, becaause when I use the "screenpad" button G-Helper gives the following popups:
Screenpad Hidden
Screenpad off
Screenpad 100%

I'm assuming it's g-helper because it doesn't pop up when g-helper is not running. The screenpad is dimmer than 100% until I press the button three times. When I re-enable Screenpad Xpert and Asus Libra Service I can control the screenpad bur the main display is still dimmer than normal despite some tweaking.

I followed the intel steps that you recommended and it reset the brightness of RGB colors but not the brightness (i,e. backlight) of the screen. It could be that I did something wrong in disabling asus services in favor of g-helper

**Comment by seerge** [comment]
@brimwats it can emit native windows media-key commands that tell windows to set brightness of the main display up / down (pretty much same as if you drag a slider). 

Screenpad is different story. It's controlled via special ASUS endpoints. That G-Helper again "tell" to go up / down in brightness. 

I didn't get it completely. Does screenpad (i.e. second screen) or main display have issues ?

**Comment by brimwats** [comment]
It's the main display! But if it's windows related then I suppose we can close the issue and I can try to figure it out!

**Comment by seerge** [comment]
@brimwats if it's the main display - then it's brightness is controlled via windows slider. If slider is at max position - it's supposed to be max brightness :)

When was it brighter last time ? And what did you change after ?

**Comment by seerge** [comment]
@brimwats the reason i asked to reset settings in Intel, is cause when you set different Visual Modes (it runs Asus utility under the hood to set them, same as MyASUS does) - that utility can change gamma / contrast / etc.

But resetting Intel Graphics settings resets all that settings all together.

**Comment by seerge** [comment]
@brimwats i'm closing this as not related to the app. But if you fill find a reasons - feel free to post. I may add it to FAQ or so :)
