### ISSUE TITLE
Custom Themes \ Visual Customization for GHelper

### ISSUE THREAD

**Issue by Samybigio** [seerge/g-helper#2828]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

It is not a problem, rather just a visual improvement request.

### Describe the solution you'd like

I'd like a solution where the main background of ghelper can be replaced with an image or a solid color, and that every profile selection overlay (the one that pops up when changing profile with keyboard shortcuts) can be customized with an image of the same size. another thing is the customization of colors used for the profile selection (the rings around selected profiles) and perhaps a layout rearranging ability but that might be asking too much.

### Describe alternatives you've considered

Not really alternative, but Armoury crate has different themes for their matching lineup of products.

### Device and Model

Asus Tuf A15 FX507ZV4

**Comment by seerge** [comment]
@Samybigio hello, thanks, but I'm not a big fan of that.

App is intentionally designed to look like a native windows app, and reflect currently active dark / light windows theme.

All 3 accent colors (red / green and blue) are also carefully picked and used across whole app, not only as a borders for each mode. So it you can't change them easily.

So I don't plan to do this . Sorry.

Thanks
