### ISSUE TITLE
Add settings that make Fn locking only affect the laptop keyboard

### ISSUE THREAD

**Issue by SeemWind** [seerge/g-helper#2829]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Fn locking will affect the external keyboard. Can we add settings that only affect the laptop keyboard

### Describe the solution you'd like

Add settings that only affect the laptop keyboard

### Device and Model

ROG G16

**Comment by seerge** [comment]
@SeemWind hello, this is a dublicate of https://github.com/seerge/g-helper/issues/918 (and couple of other issues).

I was answering this already and it's not possible. Sorry

Thanks
