### ISSUE TITLE
Anime matrix not applied after reboot

### ISSUE THREAD

**Issue by adsau59** [seerge/g-helper#283]
**Describe the bug**
after the system is rebooted, and ghelper starts automatically, anime matrix is not applied by default, I am forced to go inside g helper and reselect the option i had selected to make it work... by default it runs the Rog logo sequence

**Clear scenario to Reproduce**
1. Select an anime matrix setting (I have tried this with gif and Off)
2. reboot the system
3. notice default Rog logo sequence runs after the reboot, but the selected option in anim matrix is the one u had selected before
4. choose some other option from anime matrix, then reselect the one u had originally selected
5. notice now that you have relected the option, it starts working now

**Expected behavior**
the option you have selected before rebooting in anime matrix should be played by default

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11300409/log.txt)

**Screenshots or screencasts**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ROG Zephyrus G14 GA402RJ

**Asus software**
- Armoury crate (or it's services installed) - yes
- MyASUS installed - yes
- Other Asus services running in background - no

**Additional context**
N/A

**Comment by seerge** [comment]
@adsau59 actually app sets last mode each time it's started. Where is the GIF that you previously selected located (i.e. was it accessible after reboot?)

**Comment by seerge** [comment]
I have added some extra logging for anime matrix here, can you try to "repeat" what you explained here and upload fresh log ? also your config.json
[GHelper.zip](https://github.com/seerge/g-helper/files/11301092/GHelper.zip)

**Comment by adsau59** [comment]
> 

download folder

**Comment by adsau59** [comment]
> I have added some extra logging for anime matrix here, can you try to "repeat" what you explained here and upload fresh log ? also your config.json


thanks will try it out

**Comment by adsau59** [comment]
@seerge oh wait i just realized, i dont actually restart... I usually hibernate my laptop, then resume it... maybe thats when the issue occurs

**Comment by seerge** [comment]
@adsau59 app reapplies all settings each time it starts or power mode is changed (including waking up).

So my question still stands - reproduce it again, and post a log here.

**Comment by adsau59** [comment]
[log.txt](https://github.com/seerge/g-helper/files/11362504/log.txt)

**Comment by seerge** [comment]
@adsau59 i see 0 messages in log about enabled anime matrix, do you use build that i have sent here ? did you set picture on matrix and reproduced case again ?

**Comment by seerge** [comment]
Closed due to absense of an issue

**Comment by adsau59** [comment]
> and reproduced case again

I try to turn it off, but turns off automatically
