### ISSUE TITLE
Hope to support saving the last microphone off state

### ISSUE THREAD

**Issue by fcwys** [seerge/g-helper#2832]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hope to support saving the last microphone off state

### Describe the solution you'd like

Saving the last microphone off state

### Device and Model

ROG Zephyrus M16 GU603ZM

**Comment by seerge** [comment]
@fcwys hello, windows already saves current state of the microphone :)
