### ISSUE TITLE
Add keybind for mux switch?

### ISSUE THREAD

**Issue by ILikeLight** [seerge/g-helper#2837]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

it is not related to a problem but more of an inconvenience when i boot up rainbow six siege the mux switch doesnt switch to the gpu so i have to do it manually in the nvidia control panel

### Describe the solution you'd like

maybe ad an option for FN+F4 to switch between igpu and dgpu

### Describe alternatives you've considered

a button in the software

### Device and Model

Asus Zephyrus g16 2024 GU605MI

**Comment by seerge** [comment]
@ILikeLight hello, application does not control that what GPU is windows or game is using. That's not possible

You can go to Windows Game settings and make sure that Rainbow Six is marked to use dedicated GPU there, and do same in Nvidia Control Panel

Thanks

**Comment by ILikeLight** [comment]
ok thanks
