### ISSUE TITLE
Some suggestions for the interface

### ISSUE THREAD

**Issue by Hajime-Hajime** [seerge/g-helper#2841]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Some suggestions for the interface

### Describe the solution you'd like

1. Move functions that are rarely used to "settings": "Run on startup", "Battery limit", "Updates"
2. Rename extra to settings. 
3. Move brightness to the block with keyboard settings. 

Ideally, add the ability to hide some elements from the main window. 

### Device and Model

Asus Rog flow x13 (2021)

### Additional information.

![Screenshot 2024-07-14 090435](https://github.com/user-attachments/assets/edf0abc7-b6ba-4e40-ac38-1603964fd6e5)

**Comment by seerge** [comment]
@Hajime-Hajime hello. Thanks for your suggestions, I will take them into consideration :)

There are reasons why certain elements are where they are now. 

For example :
- App intentionally doesn't put itself to startup automatically, therefore `Startup` checkbox is intentionally prominent
- `Updates` section are being checked often by many people
- Battery charge section shows current discharge, and charge % that needs to be visible. 
- `100%` charge button is supposed to be quickly accessible
- Backlight zones section can contain much more checkboxes than you see (it depends on the model), therefore that space is reserved

Thanks :)
