### ISSUE TITLE
backlight turn on  after backlight timeout have delay 

### ISSUE THREAD

**Issue by Alidamiridev** [seerge/g-helper#2843]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

when backlight going to timeout and when i press a kay to turn it on it have delay and have lights flicker issue

### How to reproduce the bug?

1. dont wokr with kayboard and light going off
2. press a kay to turn it on
3. it have delay for 1 sec or more
4. and also flicker

### Logs

[log.txt](https://github.com/user-attachments/files/16227623/log.txt)

### Device and Model

Asus Tuf Gaming A15 FA506IC

### Additional information.

i havent this problem with armary create 

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.179.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Alidamiridev hello,

Application checks for activity status only once per second, to save resources. Therefore a delay up to 1 second is possible :) Unfortunately nothing else can be done here.

Thanks

**Comment by Alidamiridev** [comment]
> @Alidamiridev hello,
> 
> Application checks for activity status only once per second, to save resources. Therefore a delay up to 1 second is possible :) Unfortunately nothing else can be done here.
> 
> Thanks

thanks for answer. and also for great job .  ok its fine but what about flicker?

**Comment by seerge** [comment]
@Alidamiridev app just sets backlight brightness to 0 on timeout and back to last used level when windows reports activity.

Do you get same "flicker" when you just manually adjust brightness level (via hotkeys or via slider under `Extra`) ? If so - then it's probably how keyboard backlight works on your specific model.

**Comment by Alidamiridev** [comment]
no i havent this issue when manually adjust brightness level 
and  i have flicker on some color not all

**Comment by seerge** [comment]
@Alidamiridev does switching directly between 0 brightness and max brightness with slider under `Extra` behave same? As it does exactly same thing as delay timer :)
