### ISSUE TITLE
TUF 15 - Visual Mode doesn't work

### ISSUE THREAD

**Issue by qdev89** [seerge/g-helper#2844]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Visual Mode doesn't work on TUF 15
![image](https://github.com/user-attachments/assets/b29bb44e-b023-40dc-b667-28d3c3612452)
Not sure I do something wrong here but Eyecare is really important to me since my Amoury Crate totally been broken like this (can't change Visual Mode)
![image](https://github.com/user-attachments/assets/d0c0f917-a9d9-442e-9753-3fd02cfe27f6)

Thank you

### How to reproduce the bug?

Visual Mode

### Logs

[log.txt](https://github.com/user-attachments/files/16228289/log.txt)

### Device and Model

ASUS TUF 15

### Armoury Crate

Uninstalled

### OS

Win 10

**Comment by seerge** [comment]
@qdev89 hello, do I understand correctly that it didn't work in AC as well ?

**Comment by qdev89** [comment]
hi @seerge 
Thank you but after following your approach, my G-Helper can't start anymore.
Log in event viewer as crash
`Application: GHelper.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'GHelper.Program' threw an exception.
 ---> System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at AppConfig.GetBiosAndModel() in D:\a\g-helper\g-helper\app\AppConfig.cs:line 132
   at GHelper.Display.ColorProfileHelper.ProfileExists() in D:\a\g-helper\g-helper\app\Display\ColorProfileHelper.cs:line 503
   at GHelper.SettingsForm.InitVisual() in D:\a\g-helper\g-helper\app\Settings.cs:line 352
   at GHelper.SettingsForm..ctor() in D:\a\g-helper\g-helper\app\Settings.cs:line 275
   at GHelper.Program..cctor() in D:\a\g-helper\g-helper\app\Program.cs:line 30
   --- End of inner exception stack trace ---
   at GHelper.Program.Main(String[] args) in D:\a\g-helper\g-helper\app\Program.cs:line 72
`
Looks like my machine also get problem with GetBiosAndModel, even in Amoury Crate so it can working normally.
Regards

**Comment by seerge** [comment]
@qdev89 i have checked your original app log, and it looks something is generally wrong with your laptop. As it doesn't even report it's own model name from windows.

```
7/14/2024 11:53:47 PM: App launched:  :0.179.0.0en-GB  <---- model name should be here
7/14/2024 11:53:48 PM: dGPU not found
7/14/2024 11:53:48 PM: Invalid class 
7/14/2024 11:53:48 PM: CPU: 99999 -  - 
7/14/2024 11:53:48 PM: Can't connect to ASUS WMI events
```

App crash is due same reasons.

And this is (probably) same reason as Armoury Crate on your device shows nonsense too, as it can't detect what model it runs at.

Try to go through all steps in https://github.com/seerge/g-helper/wiki/Troubleshooting

And mainly [Asus System Control Interface reinstall](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-asus-system-control-interface) and [Rebuilding WMI repository](https://github.com/seerge/g-helper/wiki/Troubleshooting#rebuilding-wmi-repository)

**Comment by qdev89** [comment]
> @qdev89 i have checked your original app log, and it looks something is generally wrong with your laptop. As it doesn't even report it's own model name from windows.
> 
> ```
> 7/14/2024 11:53:47 PM: App launched:  :0.179.0.0en-GB  <---- model name should be here
> 7/14/2024 11:53:48 PM: dGPU not found
> 7/14/2024 11:53:48 PM: Invalid class 
> 7/14/2024 11:53:48 PM: CPU: 99999 -  - 
> 7/14/2024 11:53:48 PM: Can't connect to ASUS WMI events
> ```
> 
> App crash is due same reasons.
> 
> And this is (probably) same reason as Armoury Crate on your device shows nonsense too, as it can't detect what model it runs at.
> 
> Try to go through all steps in https://github.com/seerge/g-helper/wiki/Troubleshooting
> 
> And mainly [Asus System Control Interface reinstall](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-asus-system-control-interface) and [Rebuilding WMI repository](https://github.com/seerge/g-helper/wiki/Troubleshooting#rebuilding-wmi-repository)

Thanks @seerge seems something happened during Windows Update.
I will check all and get back the result.
Regards.

**Comment by qdev89** [comment]
Updated,
Unfortunately, Nothing is working for me, I still can't use G-Helper or even Armory Crate. seems my laptop is broken in software, I will try to upgrade my Windows to 11 and see if it's fixed.

Thank you again @seerge G-Helper is a god-sent

**Comment by seerge** [comment]
@qdev89 did you try rebuilding WMI repository as well ?

**Comment by qdev89** [comment]
> @qdev89 did you try rebuilding WMI repository as well ?

yep, do all thing even hard reset laptop :D

**Comment by seerge** [comment]
@qdev89 ok ... then it looks something is wrong with windows itself :) Unfortunately I can't help anyhow as this is not related to G-Helper. Therefore closing.

Good luck with resolving your problem
