### ISSUE TITLE
GPU temperature limit doesn't work in Custom and Balance modes on ROG Strix SCAR 17 (2023)

### ISSUE THREAD

**Issue by Upsolo** [seerge/g-helper#2846]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Starting from version 0.179 (or maybe earlier?) the temperature limit stopped working sometimes in all modes, and sometimes only in custom and Balance modes. The pattern could not be identified. But before, the restriction DEFINITELY worked fine.

Therefore, now instead of using temperature limits, you have to use the GPU frequency limit. The problem is relevant in all GPU modes (Eco, Standart, Ultimate, Optimized)

<img width="508" alt="image_17" src="https://github.com/user-attachments/assets/d2c5dcfa-81d7-440a-85b7-020fbfb0fbf7">

### How to reproduce the bug?

1. Start the PC
2. Load the GPU
3. Observe if the temperature limit is exceeded

### Logs

[log.txt](https://github.com/user-attachments/files/16236618/log.txt)

### Device and Model

Asus ROG Strix SCAR 17 G733PY (2023) 

### Additional information.

Recently, the laptop began to turn off when the video card is heated above 85 degrees. This has happened before in a custom mode with low fan speeds, but I was saved by the temperature limit in G-Helper. However, this limitation now doesn't work, which leads to regular shutdowns in GPU-intensive games.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.179

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@Upsolo hello, there is absolutely nothing that has changed in this regard in the last version. In what specific version does it work ?

I see that app sets limit, along other settings

```
15.07.2024 17:30:54: Mode = 4 : OK
....
15.07.2024 17:30:54: FanCPU = 1D-1E-44-48-50-54-57-5D-00-02-02-04-0B-14-18-1C : OK
15.07.2024 17:30:54: FanGPU = 1E-3C-43-48-4B-50-55-59-01-0A-0D-12-1A-21-24-2C : OK
15.07.2024 17:30:55: PowerLimit A3 = 44 : OK
15.07.2024 17:30:55: PowerLimit A0 = 50 : OK
15.07.2024 17:30:55: PowerLimit C1 = 50 : OK
15.07.2024 17:30:56: PowerLimit C0 (GPU BOOST) = 25 : OK
15.07.2024 17:30:56: PowerLimit C2 (GPU TEMP) = 87 : OK  <--- limit
```

Keep in mind, that 87C is default limit (and it's also maximum possible value), so this is pretty much same as if you wouldn't set any limit at all.

- How do you verify that it doesn't work ?
- What happens if you set exactly same settings in AC ? (i.e. power limits / fan curves and GPU limits) ?

Thanks

**Comment by seerge** [comment]
@Upsolo did it ever work ? Looks more like some BIOS issue or Nvidia GPU driver issue.  Did you update anything recently there ?

**Comment by Upsolo** [comment]
Yes, I am 100% sure that this function has worked before.

From recent changes - I only updated the ASUS System Control Interface, but I don't think that's the case.

I tried reinstalling the GPU driver using DDU on different versions (including the latest one from ASUS) - the result is the same...

Should I try to roll back to the old version of the BIOS?

**Comment by seerge** [comment]
@Upsolo you can try older BIOS or older Asus System Control Interface (it exposes in windows BIOS endpoints responsible for settings that AC and G-Helper use)

As I remember HWinfo was able to show current GPU temp limit (from nvidia driver), so you can check if it changes there when you set it in app.

**Comment by seerge** [comment]
@Upsolo if HWinfo shows it triggered, it means setting is set (and System Control Interface works).

Try older BIOS or try to lower GPU power in other ways (for example lower dynamic boost or set stronger clock limits). After all the only thing GPU temp limit does - tells GPU to drop it's power when it hits it.

I'm closing this as not planned as there is nothing to fix and it's not related to the G-Helper in a first place.

Thanks
