### ISSUE TITLE
Vivobook pro 15 N6506MV lack of control

### ISSUE THREAD

**Issue by MaxiJazzer** [seerge/g-helper#2847]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I can't opt out of MyASUS because there aren't enough features from there

### Describe the solution you'd like

Any chance to add Oled-related settings to G-Helper? (OLED care, OLED dimming)

Also, there is no optimized setting for an iGPU+dGPU, but it is in MyASUS.

No TDP control for CPU, iGPU, and dGPU in this model? (Ultra 9, RTX 4060)

Tru2Life and Target mode is needed too :)

### Device and Model

Asus Vivobook pro 15 N6506MV 185h+rtx4060

**Comment by seerge** [comment]
@MaxiJazzer hello, try this build it should show all OLED-related options (like dimming). 

[GHelper.zip](https://github.com/user-attachments/files/16240018/GHelper.zip)

I'm not sure what kind of OLED care options you had, but in AC to my best knowledge only care is ability to hide task-bar and automatically move wallpaper a bit. Both of them you can achieve with windows directly.

As for other things - your model  need to support limits / settings in BIOS level. If you don't see corresponding sliders - it means they are not supported.

What kind of settings did you have in MyASUS for iGPU / GPU ?

**Comment by MaxiJazzer** [comment]
![sadasdasd](https://github.com/user-attachments/assets/bae08369-355d-4b0e-85f3-d58deac8b7a8)
I have same Optimized feature in MyAsus, but in G-Helper not

**Comment by seerge** [comment]
@MaxiJazzer but what does it do, does dGPU get totally powered off and completely disappear from device manager with that? Do you also have Eco / Standard buttons ?

Do you see OLED dimming in the build i linked ?

**Comment by seerge** [comment]
@MaxiJazzer 

- When I was checking what Armoury Crate does for this "Pixel shift", it was running an app that was just shifting wallpaper in windows few pixels here and there (literally making copies of an image). I'm not sure if MyASUS does something different as I don't have your device and can't check directly.
- "Pixel refresh" how does it look ? What exactly it refreshes ? In Armoury pixel refresher meant just running some kind of a screensaver (in windows again).

As for GPU modes, so you actually see `Eco` and `Standard` ? Do they work ?

Can you upload a log from `%appdata%\GHelper` ?

**Comment by seerge** [comment]
@MaxiJazzer ok, then please do check and upload a log when you will have time

Actually most probably you don't see `Eco` button as well. Cause app would hide both `Eco` and `Optimized` (as it just switches between Standard / Eco when you plug in / unplug) if it doesn't see `Eco` endpoint available on the device.

It could be that Vivobook Pro 15 has some other setting for that, but then we need to do some reverse-engineering here ...

**Comment by MaxiJazzer** [comment]
I see the Eco button, the Standard button, and the Ultimate, for sure.

**Comment by MaxiJazzer** [comment]
Here is a screenshot of the MUX switch in action, along with the log file you requested.
I apologize for the confusion. In G-Helper, I have slightly different buttons for managing: "Kill GPU tasks,""Standard,"and"Ultimate."

The screenshot I provided is from MyASUS, and it functions as described.

![1](https://github.com/user-attachments/assets/70c0358d-3e25-4071-923c-28260565d949)
![2](https://github.com/user-attachments/assets/82c59c6c-54cd-40ab-9450-8a54293263ff)
![3](https://github.com/user-attachments/assets/1457f9ee-44f6-4115-8d38-61513e69f7bb)
![4](https://github.com/user-attachments/assets/05b93f0d-fec6-4cd0-9480-8a5fee28744a)
[log.txt](https://github.com/user-attachments/files/16264017/log.txt)

**Comment by seerge** [comment]
@MaxiJazzer ok, 

Can you quit app and add following line to ``%appdata%\GHelper\config.json`` 

```
"debug" : 1,
```

Save it, and start app again.

Under ``Extra`` you should see a `Scan` icon (looks like a magnifying glass).

Set GPU to `Eco` mode in MyAsus, and run a scan in G-Helper
Set GPU to `Standard` mode in MyASUS and run a scan in G-Helper again

Upload log from scan here 

Thanks

**Comment by MaxiJazzer** [comment]
1 scan - eco
2 scan - standart

[scan.txt](https://github.com/user-attachments/files/16272205/scan.txt)

**Comment by seerge** [comment]
@MaxiJazzer ok, great.

Problem is that both scan results is absolutely identical (i was expecting at least one of the endpoints to change)

For example ``90026`` - is a MUX (i.e. `Ultimate` mode) switch. 
1 stands for MUX being on (i.e. `Standard` mode), 0 would be `Ultimate)

Are you sure that Eco switch worked in MyASUS ? Can you double check if GPU disappears and appears again under Device Manager before doing a scan in G-Helper ?

**Comment by MaxiJazzer** [comment]
Yes, it's completely disappeared. You can only see it if you turn on "Show disconnected devices" in the device manager. And in the properties, it says "This device has been disconnected".

**Comment by seerge** [comment]
@MaxiJazzer ok, then there is another way to check what exactly MyASUS does to turn it off. You can check this manual https://github.com/seerge/g-helper/wiki/_ACPI-Monitoring-and-Debugging on how to monitor AC's actions (applies to MyASUS)

If you are willing to do that - let me know

You can try to test if capturing works, by setting different performance modes in MyASUS (i.e. Silent / Balnaced / Turbo as they are 100% controlled via ACPI commands, same as Ultimate mode swtich)

**Comment by MaxiJazzer** [comment]
This is result with Ultimate toggle in MyASUS
[scan.txt](https://github.com/user-attachments/files/16272920/scan.txt)

**Comment by seerge** [comment]
@MaxiJazzer yes, and as expected ``00090026`` is `0` now :)

Can you also try another thing:

Open `Extra` go to new `ACPI DEVS test` section and put ``00090020`` to the first field, `0` to the second and press `Send`. And check if GPU disappears in device manager ? (`1` should put it back then)

**Comment by MaxiJazzer** [comment]
Nope, nothing happening or not working sending command :(

**Comment by seerge** [comment]
@MaxiJazzer then the only way to check would be following steps in https://github.com/seerge/g-helper/wiki/_ACPI-Monitoring-and-Debugging (as I have proposed in a previous comment)

**Comment by seerge** [comment]
@MaxiJazzer any updates here ?

**Comment by kaciko** [comment]
Dear seerge, same issue applies to my Vivobook pro 15 N6506MU variation (there are three total variations N6506MU, MV an MJ, mine is 185h+ RTX4050)
Does latest GH version (0.181.0) applies to N6506MU as well?
Thanks!

**Comment by kaciko** [comment]
@seerge  I forgot i had "hide_visual": 1, so i removed it and now i see the dimming options.! I do have ECO mode available yes.

Irrelevant question: PL1/PL2 for this model can they be enabled? Because they are fully adjustable via 3rd party software (eg throttle stop)?

Thanks again for your work! <3

**Comment by seerge** [comment]
@kaciko ok,

1. If you couldn't change PL1/PL2 in MyASUS - you won't have that in G-Helper neither. As G-Helper uses Armoury's / MyASUS endpoints for settings. Throttlestop does that somehow differently, so i can't copy that. But you can keep using it as well.

2. For `Eco` / `Optimized` if you will read conversation here - it seem to be some new endpoint specifically for Vivobooks responsible for that. I need someone with actual laptop to help and find it :) But since topic starter has disappeared - I can't do much.

If you are willing to help, you can either follow instructions above OR try to do a DSDT dump as explained [in the Method 2 here](https://github.com/seerge/g-helper/issues/38)

**Comment by kaciko** [comment]
@seerge i followed the instructions and here are the results from ACPI Monitoring (tried few mode changes between optimized, eco and standard modes, hope i did it properly)

[MA_OPTIMIZEDtoSTANDARD_Capture.log](https://github.com/user-attachments/files/16366713/MA_OPTIMIZEDtoSTANDARD_Capture.log)
[MA_ECOtoOPTIMIZED_Capture.log](https://github.com/user-attachments/files/16366714/MA_ECOtoOPTIMIZED_Capture.log)
[MA_STANDARDtoECO_Capture.log](https://github.com/user-attachments/files/16366715/MA_STANDARDtoECO_Capture.log)
[MA_ECOtoSTANDARD_Capture.log](https://github.com/user-attachments/files/16366716/MA_ECOtoSTANDARD_Capture.log)

Additonally, here is the DSDT dump: 
[dsdt.zip](https://github.com/user-attachments/files/16366729/dsdt.zip)

Please let me know what else you might need!

Thanks again,
Lefteris

**Comment by seerge** [comment]
@kaciko ok, amazing! that was fast.

It seems like endpoint for Eco mode (i.e. disabling GPU) is ``0x00090120``. While for ROG/TUF it's ``0x00090020`` (so almost same, just 0 instead of 1)

Can you try this build and check if `Eco` mode is visible and disables GPU ?

[GHelper.zip](https://github.com/user-attachments/files/16366780/GHelper.zip)

Thanks

**Comment by seerge** [comment]
@kaciko great, can you check if this build still works same as one before ? Thanks

[GHelper.zip](https://github.com/user-attachments/files/16367904/GHelper.zip)

**Comment by kaciko** [comment]
@seerge just did, works as expected! I assume i keep this version right? Thanks again!

**Comment by seerge** [comment]
@kaciko great, do I understand that `Eco` / `Optimized` switch was the only setting from MyAsus missing in G-Helper?

**Comment by kaciko** [comment]
All settings seem to be there, the only thing that is not identical are fan speed options (please see below image). Having "TURBO" in g-helper reflects as "Performance Mode" in MyAsus. I don't have a clue what "Full-Speed Mode" is supposed to do in MyAsus though, as selecting it doesn't put fans into constant max speed - at least that was what i expected. 

![image](https://github.com/user-attachments/assets/b682dce7-78b8-4cea-b441-fc67e2c8cac4)

**Comment by seerge** [comment]
@kaciko that's cause some Vivobooks / Zenbooks have a 4th mode called "full speed". 

And app's UI is build around ROG / TUF devices (99% of the users) that have 3 modes.

You can still use it if you will follow my comment here tho https://github.com/seerge/g-helper/issues/1301#issuecomment-1715814968

You just need to add one more preset with a (+) and and make a small config change

**Comment by kaciko** [comment]
Great! I added the custom fan mode as per your instructions (even though i cant see any difference) and renamed it as-well!

Once again thanks a lot!

**Comment by seerge** [comment]
@kaciko great, closing this as resolved then and I will include changes in next release

**Comment by seerge** [comment]
@kaciko if you don't mind, can you check if this build still works correctly with all switches (including Ultimate) ?

I have just did some cleanup for Mux / GPU OFF endpoints for Vivobooks as both of them are different from "mainstream" ROG/TUF models (but they work same of course)

[GHelper.zip](https://github.com/user-attachments/files/16379506/GHelper.zip)

**Comment by kaciko** [comment]
@seerge it is working correctly (Tried all switches).
Thanks!

**Comment by seerge** [comment]
@kaciko great, thanks for confirming :)
