### ISSUE TITLE
problem G-helper

### ISSUE THREAD

**Issue by SPLiNTER-01** [seerge/g-helper#2848]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![Screenshot 2024-07-15 230030](https://github.com/user-attachments/assets/6bab8069-7b2d-4fb8-9f27-2c8797916ea4)
 I checked updates from G-helper and installed it still red and ask me to do update again?

### How to reproduce the bug?

1- open G-helper
2-check any new updates 
3- install new updates which color red
4- download updates and make updates 
5- restart laptop 
6- still need same update

### Logs

7/4/2024 10:10:12 PM: AuraMode: AuraColorCycle
7/4/2024 10:10:12 PM: TUF RGB = B4-02-FF-FF-FF-EB : OK
7/4/2024 10:10:12 PM: Monitor Power On
7/4/2024 10:10:12 PM: BatteryLimit = 80 : OK
7/4/2024 10:10:12 PM: Lid Open
7/4/2024 10:10:12 PM: TUF Brightness = 129 : OK
7/4/2024 10:10:13 PM: TUF Brightness = 129 : OK
7/4/2024 10:10:13 PM: UV: -30 OK
7/4/2024 10:10:13 PM: CPU Temp: 85 OK
7/4/2024 10:16:41 PM: Display configuration changed.
7/4/2024 10:36:12 PM: Display configuration changed.
7/4/2024 10:36:34 PM: Display configuration changed.
7/4/2024 10:39:29 PM: Display configuration changed.
7/4/2024 11:08:07 PM: ------------
7/4/2024 11:08:07 PM: App launched: ASUS TUF Gaming A15 FA507XI_FA507XI :0.178.0.0en-US.
7/4/2024 11:08:09 PM: Matrix control device was not found on your machine.
7/4/2024 11:08:10 PM: NVIDIA GeForce RTX 4070 Laptop GPU
7/4/2024 11:08:11 PM: CPU: 9 - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics      - AMD64 Family 25 Model 116 Stepping 1
7/4/2024 11:08:11 PM: AutoSetting for Online
7/4/2024 11:08:11 PM: BatteryLimit = 80 : OK
7/4/2024 11:08:11 PM: Optimization service is running
7/4/2024 11:08:11 PM: Eco flag : 0
7/4/2024 11:08:11 PM: Mux flag : 1

### Device and Model

asus tuf a15

### Armoury Crate

Uninstalled

### Version

0.179.0

### OS

windows 11 23H2

**Comment by seerge** [comment]
@SPLiNTER-01 hello. Which specific update is marked red? Its not visible neither from screenshot nor from the log that you have trimmed by some reason. So upload full log please

**Comment by SPLiNTER-01** [comment]
![Screenshot 2024-07-15 231757](https://github.com/user-attachments/assets/59f6ff35-8365-4e96-b587-c1b422b57efe)
this second time, first was on BIOS and can't update form G-helper and i using flash memory to do update

**Comment by SPLiNTER-01** [comment]
![Uploading Screenshot 2024-07-15 231940.png…]()

**Comment by SPLiNTER-01** [comment]
![Screenshot 2024-07-15 231940](https://github.com/user-attachments/assets/bda0a57b-1dac-4661-90dd-432d8a51ea49)

**Comment by seerge** [comment]
@SPLiNTER-01 it's just a strange release from asus, it installs but doesn't report correct version.

Check [this reddit topic](https://www.reddit.com/r/ASUS/comments/1e2m5fh/error_installing_asus_system_control_interface/), lots of people have same problem (no matter if they use AC or G-Helper)

So if you have installed it once - just ignore that counter for now, until asus releases one more version of it :)

Thanks

**Comment by SPLiNTER-01** [comment]
So it's not a problem with my laptop ?

**Comment by SPLiNTER-01** [comment]
but why when i was trying to update BIOS and after installed can't do update

**Comment by seerge** [comment]
@SPLiNTER-01 no, problem is that Asus System Control Interface when installed reports a wrong version (check reddit topic i linked)

You have latest BIOS already

**Comment by SPLiNTER-01** [comment]
thank you <3
