### ISSUE TITLE
Strix G17 (G713) < and ALT GR not lighting up in Heatmap, Ambient and Startup/Shutdown animations

### ISSUE THREAD

**Issue by Constrat** [seerge/g-helper#2850]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

As title. When using Heatmap or Ambient, "<" key will not light up (to the right of the left shift) and ALT GR (to the right of the spacebar) will light up only halfway.

Same thing happens when turning the computer on or off, with the Boot and Shutdown animations.

To be fair, I don't think I've ever had this issue before. I checked some older G-Helper versions (from 0.179 all the way to 0.175) but without fix. 

### How to reproduce the bug?

- Use Heatmap or Ambient -> Issue

- Make sure these two are on
![image](https://github.com/user-attachments/assets/b6077fca-15ff-4211-909f-5ceda087ce35)
During the animations the two keys will not light up.

### Logs

[log.txt](https://github.com/user-attachments/files/16246641/log.txt)

### Device and Model

ROG Strix G713RW

### Armoury Crate

Never installed

### Asus Services

0

### Version

0.179.0

### OS

Windows 11 Enterprise 23H2

**Comment by seerge** [comment]
@Constrat hello, where exactly is `<` located on your keyboard ? 

As I remember you were helping me already with identifying a keycodes. You can check current list of them here. Try to guess a missing codes from the list, and mb re-compile app and see if it suddenly lights up ?

https://github.com/seerge/g-helper/blob/8961e8df85edc043a340adc3a2a4abc1b95508f8/app/USB/Aura.cs#L408

**Comment by Constrat** [comment]
Looking at Git Blame, I was the last one to make modifications here.
![image](https://github.com/user-attachments/assets/dcf2565a-bade-4781-b1ca-81a5e3893650)

I'll see if it's something related to my hardware, as the codes and the keyboard structure seems ok.

**Comment by seerge** [comment]
@Constrat Asus System Control Interface is not related to this. G-Helper communicates directly with keyboard via USB.

You can try to guess missing key ID based on it's physical location and IDs of a neighbouring keys.
Good example is my recent addition is 120, 140, 141, 143 - that turned out to be arrow keys for Strix 2024 :))

**Comment by Constrat** [comment]
I don't think it's something related to a missing key ID. I remember having fixed this back in the day. With #1636.

I'll check with ver 0.135, as it was released with that version.

**Comment by Constrat** [comment]
Ok not good. It's an issue also directly with Armoury crate. It could really probably be something related to the board(?)

The issue comes by using the Aura Sync options. Using the simple Static Breathing etc from the keyboard page, instead of the Aura Sync works. lol. Guess I'll have to deal with it.

**Comment by seerge** [comment]
@Constrat oh, ok ... so hardware-controlled modes keep LED on, and any software-controlled setting color per-led keep it off ?

Try to https://github.com/seerge/g-helper/wiki/Troubleshooting#hardware-reset--cmos-reset mb ?

**Comment by Constrat** [comment]
Nope, unfortunately it did nothing.
I'll see if I have any intention to go the Asus store and talk to them about this.
The fact that the led itself turns on is good. But I seems like it can't be controlled by itself, only with full keyboard

**Comment by Constrat** [comment]
@seerge Fortunately I have a win11 partition where Armoury Crate resides. Apparently in C:\Program Data\ASUS\ROG Live Service\Device Content. The entire keyboard model is US, meaning that the two additional keys are no interpreted correctly. The "<" is completely missing, while the ALT GR is just a ALT, and has only one LED instead of two... To be fair it seems to be something related to keyboard firmware not being recognized correctly, but I have swapping a motherboard changes it.

I should try another fresh install, in that partition.

**Comment by Constrat** [comment]
@seerge Wanted to update you on this. I sent the laptop to the usual Asus store, this time they sent it to a bigger centre and basically they reflashed the keyboard rom (with the correct firmware this time) and now it's working as expected.

A mobo change resets that rom apparently.

**Comment by seerge** [comment]
@Constrat ah, good to know :)
