### ISSUE TITLE
Can't see GPU Mode

### ISSUE THREAD

**Issue by agustinrecoba3** [seerge/g-helper#2851]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi there, i dont know if it was a modification or what, but I can't see the GPU Mode, only cpu, Maybe this was a change from another release, but i want to know if its only me or anyone also has this problem.
![imagen](https://github.com/user-attachments/assets/9304e4d7-a687-4393-b5d6-18c347d555b4)

### How to reproduce the bug?

Only open the app.

### Logs

[log.txt](https://github.com/user-attachments/files/16254073/log.txt)

### Device and Model

Asus ROG Strix G513RM

### Armoury Crate

Uninstalled

### Asus Services

Nnoe

### Version

0.180

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@agustinrecoba3 hello,

I see that BIOS responds with zeroes / NULLs to any app requests. So it's not only GPU modes are not working :) but any settings are not working for you.

```
16/7/2024 13:47:01: Eco flag : -65536
16/7/2024 13:47:01: Mux flag : -65536
...
16/7/2024 13:47:01: Mode = 1 : 0

```

But before it seemed to work, namely on July 10 ``10/7/2024``
```
10/7/2024 16:18:31: Eco flag : 0
10/7/2024 16:18:31: Mux flag : 0
...
10/7/2024 16:18:32: Mode = 0 : OK
```

Did you change anything after that ? Like new driver updates or so ?

--

Try to do a hardware reset and reinstall Asus System Control Interface as explained in 
https://github.com/seerge/g-helper/wiki/Troubleshooting

**Comment by agustinrecoba3** [comment]
Hi Seerge thank you for answering! 
Yes, i dont know why, i've changed the battery mode to maximum performance. I think that since then i've been with this problem.
I will try that! because im playing call of duty and playing with 70-80fps and from nowhere it drops to 30 or less.. 
Thank you!!

**Comment by seerge** [comment]
@agustinrecoba3 any updates here ?

**Comment by agustinrecoba3** [comment]
Hi @seerge ,I've tried with those first options and nothing, now im playing another game and got those drops of fps..
really i dont know what else to do.. 
By the way Im experiencing a lot of BSOD but since a lot of months ago.. when I unplugg the charger: BSOD, when i reboot:BSOD,, always differents messages.. 
I think that that replacing the SSD NVME should fix this

**Comment by seerge** [comment]
@agustinrecoba3 did you try reinstalling [Asus System Control Interface ? ](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-asus-system-control-interface) 

If it doesn't help try to check if you have any windows restore points prior to 10th of July and use them mb ? (cause looks like either windows update or something else has done something to it)

As a last resort you can try a clean windows install

**Comment by agustinrecoba3** [comment]
@seerge Yes! now that you said that, I remember that between 10th and so, I did an update and since then im having that trouble..
Im going to delete that and try again!

**Comment by agustinrecoba3** [comment]
[log.txt](https://github.com/user-attachments/files/16314125/log.txt)
if you find anything weird here, let me know so I install again the OS, i can't keep like this.. or i'll try to buy a new hard drive.

**Comment by agustinrecoba3** [comment]
[CBS.log](https://github.com/user-attachments/files/16315315/CBS.log)
and this log is applying the sfc /scannow, bring me this file

**Comment by seerge** [comment]
@agustinrecoba3 looks like something is wrong with the system. For me `sfc /scannow` usually says that everything is correct (or fixed like one file, when i did a force-shutdown once).

G-Helper's log is same as before, there is no communication via ACPI / Asus System Control Interface with the device. 

Out of curiosity, is AC able to do something in your case ? (i bet no)

**Comment by agustinrecoba3** [comment]
@seerge there it go the log that i get after sfc, and about AC, i disabled it some time ago from the BIOS and haven't installed
yet.. you think i should try?

**Comment by seerge** [comment]
@agustinrecoba3 try enabling all Asus/AC related in BIOS first and see if it fixes communication with ACPI by any chance. 

If it doesn't - you can check if AC works :)

**Comment by seerge** [comment]
@agustinrecoba3 any updates here ?

**Comment by agustinrecoba3** [comment]
@seerge Hi there, I've done doing what you've said, but still wont change, tried installing AC, but it fails in the process..
So i think that the best thing  to do is change the ssd... i dont know why but I think that will solve this problem (not only this with g-helper, but with all the BSOD... today i've waited for about 30mins to get the SO running, everytime it reboots, after the ROG logo, it crashes and BSOD, so i think there's the issue).

**Comment by seerge** [comment]
@agustinrecoba3 ok I see. You can try with a clean windows install first then, may be that will help already :)

I'm closing this as it's not a problem with G-Helper in a first place, but rather something is wrong with the system.

Good luck with fixing it.

Thanks

**Comment by agustinrecoba3** [comment]
@seerge Yes, but i've already done that more than once, and the problems keeps showing.

Thank you for all the help!

**Comment by seerge** [comment]
@agustinrecoba3 ah, i see ... may be try to roll back to an older BIOS version (just to see if it makes any sizable difference ?)
