### ISSUE TITLE
Go back to ECO shortly after restart option

### ISSUE THREAD

**Issue by Frigidmoon** [seerge/g-helper#2854]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I understand that with the way the system works turning on dGPU before shutdown/sleep/hibernate is a necessity for it to be functional (and I think it is a good addition that I liked), but sometimes I find it easy to forget about swapping back to iGPU after booting from hibernation.

### Describe the solution you'd like

So I'm also wondering if there could be an extra option to switch back to ECO shortly after restart (or whatever it was previously before it went to Standard on shutdown). Thank you for your time.

### Device and Model

Asus ROG Flow X13

**Comment by seerge** [comment]
@Frigidmoon hello, 

You can already do that in a couple of ways

1. Either set `Optimized` GPU mode, and then it will automatically set `Eco` when you are on battery, and `Standard` when you are plugged in (also on start)

2. Add ``"gpu_mode_force_set" : 1,`` to config as [explained in readme](https://github.com/seerge/g-helper/wiki/Power-user-settings)

Thanks
