### ISSUE TITLE
Add Feature for External Monitor Refresh Rate Management

### ISSUE THREAD

**Issue by dlovespuddin** [seerge/g-helper#2855]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

When using my 2024 Asus Zephyrus GU605MY w/4090 with an external monitor, the pg32ucdm (32", 4k, 240hz), windows will sometimes switch the external monitor refresh rate from 240hz to 60hz when I unplug and take on the go.

### Describe the solution you'd like

g-helper has functionality for the laptop screen refresh rate, but it ignores external monitors. Would be great if a second monitor is detected to have a similar feature present so I can switch my external monitor refresh rate to from 60hz to 240hz when plugged into my laptop. 

Also the pg32ucdm specifically has the ability to plug into two laptops at the same time displaying in a few different ways on a single monitor via PIP. This feature limits the screen refresh rate to the slowest laptop capable refresh rate, so even though the 2024 Asus Zephyrus GU605MY can do 240hz, my macbook pro is limited to 60hz which limits the monitor to 60hz in this configuration. I have a feeling this also resets my external monitor refresh rate to 60hz unless I remember to go back into windows settings and reset it to 240hz.

### Device and Model

2024 Asus Zephyrus GU605MY

**Comment by seerge** [comment]
@dlovespuddin hello, 

G-Helper is a lightweight app letting you change settings on Asus **Laptops** :)

I don't plan turning it into a "Swiss knife" for everything possible. So sorry, but this is out of scope.
