### ISSUE TITLE
Add ROG Aura Monitor Light Bar ALB01 Support

### ISSUE THREAD

**Issue by dlovespuddin** [seerge/g-helper#2856]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

ROG Aura Monitor Light Bar ALB01 is coming out, I was able to preorder via drop.com. Since its so new I'm confident its not on the roadmap yet so figured I'd add a feature request.

https://rog.asus.com/us/monitors/accessories/rog-aura-monitor-light-bar-alb01/

ROG Aura Monitor Light Bar ALB01

ROG Aura Monitor Light Bar ALB01― Asymmetrical lighting bar offers three different modes and features a patented clamp and magnetic buckle design, Aura Sync compatibility, plus DisplayWidget Center software
Three lighting modes: Screen Light mode provides additional illumination for the desk area; Aura RGB Lighting mode can be synchronized with other ROG Aura-compatible products and accessories; and a combined mode that offers comprehensive, all-round lighting
Unique asymmetrical lighting design: Provides a concentrated light source for brighter on-desk illumination while minimizing onscreen reflections for comfortable viewing
Patented clamp and magnetic buckle: Works with both flat and curved monitors of varying thicknesses, and allows for easy light bar adjustment
Flexibility and convenience: Easy to install and supports DisplayWidget Center software for intuitive access to light bar settings

### Describe the solution you'd like

Add functionality in g-helper to manage this through the app rather than having to go into Aura Sync and/or DisplayWidget Center.

### Device and Model

2024 Asus Zephyrus GU605MY

**Comment by seerge** [comment]
@dlovespuddin hello.

What exactly needs to be "supported" here ? And how do you control that thing in AC ? 
Is it connected via USB to the laptop ?

Thanks

**Comment by seerge** [comment]
@dlovespuddin monitors and their refresh rates are very generic thing, and you can easily change it in windows itself :)

Proprietary accessories is a bit different thing (you mostly can't control them anyhow). So here you need an app. Either Armoury or it's satellites or G-Helper.

Currently G-Helper supports only Asus mice (but likely most of popular models), with some chances of adding Asus keyboards on the later stage if I will get my hands on some of them :)

I thought that this lightbar could be just an RGB light that has similar (color) settings to laptop own RGB, or mice RGB ? if so - it's theoretically possible to add it. If it's something different - then it could be a problem. Especially without having physical access to the device.

**Comment by dlovespuddin** [comment]
Well the device should be shipped end of August and I'll respond here on how it actually operates & is controlled. Happy to let you remote in to drive if that makes it easier should you still want to work on it.

Per the tech specs:

Light Source: Dual LED & RGB LED
Illuminance: Center Illuminance  > 800 lux  (Height 45cm)
Color Rendering Index (CRI): Ra ≥ 95
Uniformity: 60% (60cm x 40cm)

**Comment by seerge** [comment]
@dlovespuddin ah, so you don't even have it ? :D 

Specs don't say much. Main thing is what can be controlled via apps and how. 

I suggest you to fill in **[Peripheral Support template](https://github.com/seerge/g-helper/issues/new?assignees=&labels=&projects=&template=peripherals_request.yml)** on the moment you will get the device, as it contains some specific questions already.

What's wrong with DisplayWidget Center btw ? I assume you need it anyway to set some settings on your monitor ? So you will have to use it anyway ?

**Comment by seerge** [comment]
@dlovespuddin G-Helper has nothing to do with DisplayWidget Center (i didn't even know about it's existence before you) :)

You can simply quit G-Helper and run it again to verify that.  Just on a side note, check if it uses any of the asus services and if they are running (and if stopping or starting services makes a difference).

As for the light bar - you can create a new issue with the template linked above when you will get it, and only if you will be indeed not happy with default app to set some settings there.  But don't expect much  as this is not just another mouse from asus that works similar to others, and  w/o physical access to a device and some reverse engineering not much can be done anyway.

I'm closing this issue for now, as there is literally nothing to implement on this stage (and it's not clear if it's even needed) 

Thanks
