### ISSUE TITLE
Ghelper and power plans don't match

### ISSUE THREAD

**Issue by Skadino** [seerge/g-helper#2857]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I use Ghelper to set the power options, the Ghelper and power options don't match the Throttle stop's power options

### How to reproduce the bug?

When you choose to apply power limits, balance is used in the power plan, regardless of the option selected

### Logs

[log.txt](https://github.com/user-attachments/files/16261388/log.txt)

### Device and Model

Zephyrus M16 GU603HM 2021

### Armoury Crate

Installed

### Asus Services

0

### Version

0.179

### OS

win11 24H2

**Comment by Skadino** [comment]
![QQ_1721199112381](https://github.com/user-attachments/assets/1b9d335e-f722-4702-a106-fe3a0c412543)
![QQ_1721199053973](https://github.com/user-attachments/assets/34c47927-7a5b-4cd4-9c08-6003f2fa10e3)

**Comment by seerge** [comment]
@Skadino hello, 

G-Helper always uses default Balanced power plan and adjusts windows Power modes instead. So everything is absolutely correct. Please make yourself [familiar with readme ](https://github.com/seerge/g-helper?tab=readme-ov-file#rocket-performance-modes)

I'm not sure how is throttlestop is related to this. But G-Helper uses Armoury Create proprietary endpoints to set power limits (same as AC uses for it's manual mode). They are not reflected in throttlestop :)
