### ISSUE TITLE
Zephyrus G16 2024 (4080) cannot set battery limit to 90%

### ISSUE THREAD

**Issue by MrCoffee0996** [seerge/g-helper#2859]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I try to set the battery limit to 90% or 85%, the battery limit slider would get back to 100%. However settings from range of 60%-80% seems to work fine. My particular laptop is Zephyrus G16 2024 (4080 model).

### How to reproduce the bug?

1. Open G Helper main menu
2. Set the battery charge limit slider to 90%
3. The battery charge limit would go back to 100% (cannot change to 90%)

### Logs

[log.txt](https://github.com/user-attachments/files/16272797/log.txt)

### Device and Model

Asus Zephyrus G16 2024 (RTX 4080 model)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.179.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@MrCoffee0996 hello, it's absolutely intentional 

Your device does not support 90% as a charge limit. Only 60-80% range or 100% specifically as reported by numerous users here https://github.com/seerge/g-helper/discussions/2408

Thanks
