### ISSUE TITLE
Keybinding custom action not working

### ISSUE THREAD

**Issue by enzo-ca** [seerge/g-helper#2860]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I was using Ghelper version 0.141 for the longest time and just recently updated to the latest version (0.179 at the time of writing). Everything works the same except for one thing which is one custom keybinding action I have set. Attached is a screenshot of the kebindings. I have `Fn+F4` set to hibernate Windows immediately when pressed and it works great in version 0.141 (and every version I tried before that). Now in version 0.179 I have the same exact thing, but when I press the keycombo nothing happens anymore.

I tried reassigning it to other keybindings and that didn't help; the shutdown command won't execute properly. The logs show me launching the two different exe files, and with the same config in one it works and in the other it doesn't. I am out of ideas since the logs look the same between the two, but in the newest version even though it says it is executing the command it has no effect.

### How to reproduce the bug?

1. Go to "Extra"
2. Set a "custom" keybinding and set the action to "shutdown /h /f"
3. Press the corresponding key combo

### Logs

[ghelper log.txt](https://github.com/user-attachments/files/16276986/ghelper.log.txt)

### Device and Model

ROG Zephyrus G14 GA401QM

### Additional information.

![image](https://github.com/user-attachments/assets/bf44325d-e424-468d-9fe5-0e213eacafde)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.179

### OS

Windows 10 22H2

**Comment by seerge** [comment]
@enzo-ca hello, try this build

[GHelper.zip](https://github.com/user-attachments/files/16279745/GHelper.zip)

**Comment by enzo-ca** [comment]
> @enzo-ca hello, try this build
> 
> [GHelper.zip](https://github.com/user-attachments/files/16279745/GHelper.zip)

Worked perfectly! Thanks for getting to it so quickly :)

**Comment by seerge** [comment]
@enzo-ca great
