### ISSUE TITLE
Add amd igpu frequncy control

### ISSUE THREAD

**Issue by t4wefan** [seerge/g-helper#2861]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

the software can only control the power and frequncy of the nvidia gpu, but in many cases it is the amd igpu affects the performance.

### Describe the solution you'd like

add a frequncy control for amd igpu in the gpu menu. 
as far as i know ,the frequncy can be controlled with softwares like ryzenadj or universal x86 tuning util

### Device and Model

ROG Zephyrus G14 GA403UV

**Comment by seerge** [comment]
@t4wefan hello, 

G-Helper doesn't control frequencies even for Nvidia GPU. It can only set Core and Memory clock offsets via NvidiaAPI. What specific frequency to use still depends on GPU and drivers.

In case of iGPU this settings are not possible. From what I have seen - in ryzenadj / UXTU you can lock frequency for some iGPUs, but then you can't unlock it after till reboot. So it make no sense to do that. If you like ryzenadj - you can keep using it as well

Thanks
