### ISSUE TITLE
Connecting to an external display causes fans to stick at a certain RPM

### ISSUE THREAD

**Issue by CoreoftheEarth** [seerge/g-helper#2863]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Sometimes at random (or some things can cause it to manifest), my CPU and GPU fans suddenly jump up to a certain speed (instead of gently ramping up/down) and stay there when connected to an external display. 
For me, my CPU speeds stick at 4800 rpm on the Turbo power mode, and 4300 on Balanced, and my GPU speed stays at between 4700 and 4900 on either mode. Setting the computer to the silent power mode and then back to any mode fixes the issue for a while (up to a few hours), then it can start again. I also think it may ignore power limits and temperature limits, but I don't entirely know.

### How to reproduce the bug?

The bug can happen at random, but one thing that I have found that causes it to happen is to go to YouTube, click on a video, and play it in full screen, which within about 5 to 10 seconds causes the bug to happen. Also, after playing games (any game in general, I haven't found any specific one that causes it), after the computer has had some time to cool down, I've noticed it staying at the same fan speeds (as described above) because the bug happens during the game too. 

### Logs

[log.txt](https://github.com/user-attachments/files/16289748/log.txt)

### Device and Model

Asus ROG Zephyrus G14 GA402XV

### Additional information.

I do remember that there was another issue that was posted that described this issue, however I have not been able to find it. I think it was described that it was a BIOS issue, and that it could have been a faulty BIOS, but I have not been able to have the issue go way with newer BIOS'es or reverting to older ones. I have also uninstalled and reinstalled graphics drivers, ASUS System Control Interface V3 (however I don't have any ASUS services most of the time anyways), and everything else applicable (including G-Helper), and no dice there either, and I have had this issue for several months, and it only started when I got my external monitor.

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.179.0

### OS

Windows 11 23H2 Home, build number 22631.3880

**Comment by seerge** [comment]
@CoreoftheEarth hello,

G-Helper does [not control fan speeds in realtime anyhow](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds), BIOS does that. It could be that it's programmed to run fans faster when dGPU powers monitor for example. Resetting mode to something else, probably causes BIOS to reset it's behavior.

If you don't like how BIOS controls fans (and it really bothers you) you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)

Besides that I can't do anything. Thanks.

**Comment by CoreoftheEarth** [comment]
Ah, so it could be that the BIOS changes its behavior when connected to an external display? I find that weird, but eh. Anywho, thanks! I'll probably try that experimental build and see if it changes anything. Have a good one, and also you make an excellent piece of software :)

**Comment by seerge** [comment]
@CoreoftheEarth you can start with unchecking custom fan curves, and see if it makes difference.

**Comment by CoreoftheEarth** [comment]
Still exhibits the same issue unchecked as checked.
