### ISSUE TITLE
AniMe Matrix boot, shutdown and sleep animations

### ISSUE THREAD

**Issue by ashl3ycodes** [seerge/g-helper#2864]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

In the Armoury Crate app there is an option to select between two different boot/shutdown/sleep built-in animations and it would be cool to have something similar in the G-Helper app, as an example, I'm not a fan of the "See Ya" shutdown animation.

## Armoury Crate built-in animation options.
![Screenshot 2024-07-18 195324](https://github.com/user-attachments/assets/eb116073-855e-4317-853e-895b6832eb05)

### Describe the solution you'd like

Add different dropdown menus to select the desired built-in animation.

## UI concept.
![Base](https://github.com/user-attachments/assets/101a359d-777c-4fd1-af9d-489ce0da22dc)
## Boot animation dropdown.
![Boot](https://github.com/user-attachments/assets/b8a03242-83af-4a01-99f6-b16a1d277614)
## Shutdown animation dropdown.
![Shutdown](https://github.com/user-attachments/assets/5f308f17-0d3b-4af5-a353-7a052bcd7002)
## Sleep animation dropdown.
![Sleep](https://github.com/user-attachments/assets/7313c4e7-369d-48ac-a5f8-492316be26b5)

### Device and Model

Asus Zephyrus G14 GA404RK

**Comment by seerge** [comment]
@ashl3ycodes hello, 

I'm not a big fan of overloading UI with all this options, as they are quite specific. But I can add them to app config, so you can configure it there

Try this build
[GHelper.zip](https://github.com/user-attachments/files/16310294/GHelper.zip)

To change settings : quit app, open `%appdata%\GHelper\config.json` and add following params to the top and save it.

**Sleep** animation. ``0`` - BannerSwipe, ``1`` - Starfield (default)
```
"matrix_sleep" : 0,
```

**Startup** animation. ``0`` - GlitchConstruction, ``1`` - StaticEmergence (default)
```
"matrix_startup" : 0,
```

**Shutdown** animation. ``0`` - GlitchOut, ``1`` - SeeYa (default)
```
"matrix_shutdown" : 0,
```

**Comment by ashl3ycodes** [comment]
Hi, thanks for answering and also for adding the option to change the animations in the json file!

**Comment by seerge** [comment]
@ashl3ycodes does it work for you?

**Comment by ashl3ycodes** [comment]
Yes, it works perfectly

**Comment by seerge** [comment]
@ashl3ycodes great, I will add it in next release, and I have also added new params to [Power User Settings](https://github.com/seerge/g-helper/wiki/Power-user-settings#animematrix-startup-shutdown-and-sleep-animations)

**Comment by seerge** [comment]
@xwinghangar hello, those animations are baked into firmware. They can't be altered.

**Comment by orionflame** [comment]
> [@xwinghangar](https://github.com/xwinghangar) hello, those animations are baked into firmware. They can't be altered.

Btw anime vision options do not show up for 2025 asus strix 18 inch model. Any ideas? Though they also didn't show up in AC so not sure what to do with this. But I want to turn it off.
