### ISSUE TITLE
Gyro on ROG Ally

### ISSUE THREAD

**Issue by Krodity** [seerge/g-helper#2866]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Gyro on ROG Ally

### Describe the solution you'd like

How troublesome would it be to request for raw gyro input to be added into the controls section of the app for the ROG Ally so that gyro will work intended for games that have read raw input 

### Device and Model

ROG ALLY Z1 Extreme

**Comment by Krodity** [comment]
If this is out of the scope or too troublesome all is well I was just curious if it was something you had considered or what your thought was about trying it

**Comment by seerge** [comment]
@Krodity hello, it's difficult. Mainly cause I don't know how to read Gyro data atm. I know how to force built-in controller to emit stick movement commands tho :) You ca check discussion here https://github.com/seerge/g-helper/discussions/1985 

Did you try https://www.rewasd.com/ btw ?

**Comment by Krodity** [comment]
Ah understandable, thank you very much for your time and call of duty bans for using reWASD so I had to forfeit it after purchasing but thank you very much and sorry for the trouble

**Comment by seerge** [comment]
@Krodity ah, that's nasty from call of duty :) I'm closing this as not planned atm, as i simply don't know how to access gyro and if it's worth bothering. But if it will be some easy way to get data, i can try to map it to controller somewhere in future

Thanks
