### ISSUE TITLE
XGM fans do not work correctly under the customized fans curve

### ISSUE THREAD

**Issue by Li-Qirun** [seerge/g-helper#2868]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I have a XGM attached to ROG Flow Z13 with i5-12500H and no discrete GPU inside. once I applied the customized fans curve, the "GPU fan "（actually "CPU AUX. fan" as shown in AC） inside Z13 will respond to the XGM GPU instead of the fan inside the XGM.

### How to reproduce the bug?

1. Check the "Apply customized fans curve" check box
2. Attach the XGM
3. Use GPU heavily

### Logs

[log.txt](https://github.com/user-attachments/files/16325062/log.txt)

### Device and Model

ROG Flow Z13 GZ301ZA

### Additional information.

I hope this can be also solved in [Experimental]Manual Fan Control version :)

### Armoury Crate

Uninstalled

### Asus Services

Both none and 7 Asus services I have tested

### Version

0.180.0

### OS

Windows 11 24H2

**Comment by seerge** [comment]
@Li-Qirun hello,

XGM fan is controlled by it's firmware.

App sets custom fan curve every time, but rest is up to firmware.
```
2024/7/21 星期日 23:01:18: XGM-6512|300:5E-D1-01-14-28-2F-38-3F-47-50-64-00-00-01-18-35-4E-64-64
```

Experimental build can't control XGM fan as it simply doesn't support this manual fan control in a first place. Only inner fans do support that.

You can use mainstream build (where all fans will be controlled by BIOS) and see if it makes a difference or just stick to default fan curves at all.

Besides that I can'd do anything.

Thanks

**Comment by Li-Qirun** [comment]
OK. Thank you anyway

**Comment by Li-Qirun** [comment]
The XGM fan works correct under the custom fans curve now in the version 0.182.0. Thank you!

**Comment by seerge** [comment]
@Li-Qirun but 0.182 is not released yet ... also I didn't change anything related to XGM there

**Comment by Li-Qirun** [comment]
emm... In this version. Anyway, it works correct now
![image](https://github.com/user-attachments/assets/c2fec0a0-9147-4dbb-9da2-208c48ec125b)

**Comment by seerge** [comment]
@Li-Qirun ah , you are using experimental build :) ok .

Could this change https://github.com/seerge/g-helper/issues/299#issuecomment-2224819539 be related to you ? What model of XGM do you have ?

**Comment by Li-Qirun** [comment]
Maybe? I don`t know. But I`m using 3080 model, not 4090.

**Comment by seerge** [comment]
@Li-Qirun ah, then it's unrelated :) It's just 4090 model that had different ID. Anyway, despite nothing is changed specifically for your device i;m glad it's working. I can imagine it's a magical power of restarting a computer ... :)

**Comment by Li-Qirun** [comment]
🤣发送自我的盖乐世
