### ISSUE TITLE
Performance statistics monitoring

### ISSUE THREAD

**Issue by cheet0-bandit0** [seerge/g-helper#2869]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I like to run a performance monitor on second screen while starting a new game. I've used radeon Adrenalin or MSI afterburner on other computers. Running Afterburner  on my 2023 G14 - 4060 seemed to be keeping my system on integrated graphics, though Ghelper set to ultimate. Did not have any problem with Ghelper ultimate specifying dgpu prior to Afterburner. Is there real time performance monitoring stats in Ghelper or a software that runs without interfering with any settings?

<img width="708" alt="Screenshot 2024-07-21 100103" src="https://github.com/user-attachments/assets/451a3ddb-ef96-4908-899e-ab717ad2a315">

### Describe the solution you'd like

A pop out window option that shows realtime performance monitoring statistics 

### Describe alternatives you've considered

Tried MSI Afterburner but had crashes. Tried win+G but would like more statistics shown

### Device and Model

Asus Zephyrus G14 2023 RTX4060

**Comment by seerge** [comment]
@cheet0-bandit0 hello, there is plenty of tools for monitoring already. Starting from native apps like AMD Adrenaline or Nvidia Experience having own monitoring, then HWinfo has a nice overlay, etc.

Without have an expensive certificate, it's impossible to show overlay in windows for fullscreen games / apps so there are no such plans for now.

Thanks
