### ISSUE TITLE
Gpu acting weird.

### ISSUE THREAD

**Issue by DeyyuZ96** [seerge/g-helper#2870]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I have recently strted using G Helper instead of Armoury Crate (the UI lag was frustrating) and after about 2 days my gpu is only drawing less than 25w when under 100% usage. And it says that it reaches temperature limit at 56 degrees. Sometimes it evens appears that is being Temperature Volage & Power limites (using MSI Afterburner) It wasn't like this and seems like any setting will change that (changing the profile doesn nothing). And sometimes now my other monitor flickers

### How to reproduce the bug?

1.Start using G helper. 2.Get randomly limited

### Logs

There's isnt a log file. I have the .exe & WinRing0x64.dll & WinRing0x64.sys

### Device and Model

Asus Rog Strix G15 2022 G513RC

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.179

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@DeyyuZ96 hello, can you upload log from `%appdata%\GHelper`` as it was asked in issue template and screenshots of all your settings ?

Do you use any other applications / settings to restrict GPU (i hear about Afterburner) ? What app do you run to check that ? 

As G-Helper is not able to set limits for GPU power at all (unless you have a new 2024 models that suppport that in certain range)

**Comment by DeyyuZ96** [comment]
There wasn't a GHelper folder in %appdata%. And I am not sure what limited
it as it was boosting with like 25w & 100% usage with 60°C. After a couple
of hours of trying to make it not do that I've uninstalled GHelper & before
my last option of reinstalling Windows I reinstalled Armoury Crate and
switching to one of the default profiles fixed it. I'll probably go back to
GHelper but keep AC installed.

My laptop is a 2022 model.

I've tried everything in GHelper like limiting the CPU and let the gpu
loose but nothing was changing.

**Comment by seerge** [comment]
@DeyyuZ96 there is such folder in %appdata%, you can also open log by clicking on `Extra` -> `Log` icon there.

If you are customizing profiles w/o understanding what settings do - I suggest to click on `Factory Defaults` and not set any custom settings. Default profiles are baked in BIOS, and therefore same no matter where you select them in AC or G-Helper.

**Comment by DeyyuZ96** [comment]
I'll install GHelper again and look for said folder. And I've never messed
with the settings or anything. I actually like that on Silent GHelper
disables the cpu boost for when I'm on the go & on battery. But after
seeing that bug I've closed MSI Afterburner (which I'm using only for the
OSD) & switched between Silent Balanced & Turbo in hopes the gpu would kick
in but haven't got nothing. Even tried the Asus hold the power button CMOS
clear but to no avail again.

**Comment by DeyyuZ96** [comment]
I found said log file. I hop this helps
[log.txt](https://github.com/user-attachments/files/16333610/log.txt)

**Comment by DeyyuZ96** [comment]
After installing back AC and switching to any of the profiles the CPU & GPU
are working back to normal. I've switched between Silent ,Balanced & Turbo
in GHelper when I saw that it none would remove the weird low limit. The
same 25w on the GPU no matter the profile. I've fully ramped the fans not
matter the temps and slided the sliders all the way to the left & then
pressed Factory Defaults but nothing changed.

**Comment by seerge** [comment]
@DeyyuZ96 so everything is working fine now ?

**Comment by DeyyuZ96** [comment]
Yes I've switched back to GHelper.

**Comment by seerge** [comment]
Great
