### ISSUE TITLE
Change Mode Based on Detected process

### ISSUE THREAD

**Issue by mlares85** [seerge/g-helper#2872]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

A nice feature would be automatically changing the mode if a specific process is detected. 

### Describe the solution you'd like

Be in silent mode unless a process for say, call of duty is running then go into Turbo mode. Or maybe balanced for a game not so demanding or whatever the user chooses.  Then go back to silent mode once it closes.

### Device and Model

Asus Zephyrus G14 2022

**Comment by seerge** [comment]
@mlares85 hello, I was answering this few times already https://github.com/seerge/g-helper/issues/2693

G-Helper does not monitor your system and applications that you launch in realtime anyhow.

But you (already) can very easily switch between profiles (backwards and forwards) with multiple hotkeys
https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings
