### ISSUE TITLE
使用电池的情况下，显卡模式选择自动切换，切换到静音模式还在使用独立显卡

### ISSUE THREAD

**Issue by qh3001** [seerge/g-helper#2876]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

使用电池的情况下，显卡模式选择自动切换，切换到静音模式还在使用独立显卡
![企业微信截图_17217909061143](https://github.com/user-attachments/assets/df4828cc-a78a-4a2c-bcec-3967071f67a0)
![企业微信截图_17217909173645](https://github.com/user-attachments/assets/ea085f5d-dfb1-4d2d-ad11-aa9a496e127f)

### How to reproduce the bug?

1. 拔掉电源
2. 未连接任何外部设备
3. 持续观察显卡使用情况，一直都有独显的使用

### Logs

无

### Device and Model

幻14 air

### Armoury Crate

Uninstalled

**Comment by seerge** [comment]
> I made myself familiar with the [Readme](https://github.com/seerge/g-helper?tab=readme-ov-file), [FAQ](https://github.com/seerge/g-helper/wiki/FAQ) and [Troubleshooting](https://github.com/seerge/g-helper/wiki/Troubleshooting).
> I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.
