### ISSUE TITLE
Custom profiles suddenly getting wiped on Windows 11 Insider Build 26252

### ISSUE THREAD

**Issue by VanillaSylv** [seerge/g-helper#2877]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Since Windows 11 Insider build 26252 build released to the public, after every reboot g-helper wipes any existing custom profiles and defaults to the "Balanced" preset.

### How to reproduce the bug?

Install Windows Insider from the Canary channel and from wsus, or from a iso
Create a custom profile in g-helper
Reboot your system
The custom profile should be suddenly deleted and g helper reverted back to the "Balanced" profile.

### Logs

[log.txt](https://github.com/user-attachments/files/16366421/log.txt)

### Device and Model

Zephryus G15 2022, GA503RW

### Additional information.

This also seems to be quite incosistent as sometimes i've went with two reboots without it deleting the profile, and sometimes every reboot just deletes it completely.

### Armoury Crate

Never installed

### Asus Services

None

### Version

0.179.0

### OS

Windows 11 Insider build 26252, Canary channel.

**Comment by seerge** [comment]
@VanillaSylv hello,

I don't think it's directly connected with insider build , but I see that at some moment something (probably windows update) as corrupted app config located in `%appdata%\GHelper` folder erasing all settings

```
24/07/2024 15:28:33: Broken config: 
````

So app has just re-created it from scratch. So only thing you can do now - is to set settings again :)

If windows misbehaves, try to make a copy of your config and store it somewhere else as well.

Thanks

**Comment by seerge** [comment]
@VanillaSylv hello, I have added some tweaks, to improve config saving in some unpredictable situations in the latest release https://github.com/seerge/g-helper/releases/tag/v0.193 

Let me know if it improves something for you :)
