### ISSUE TITLE
Vivobook S 14 OLED M5406UA, cannot change keyboard light color (Windows 10)

### ISSUE THREAD

**Issue by Cruzys** [seerge/g-helper#2878]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The application allows me to change the color and even the way in which the backlight is working but it actually doesn't do anything. I tried running it with administrator to no avail.
The application correctly identifies the laptop and it's other options are working fine except for the **keybindings**, which do not work as well but I don't really have a need for them.

### How to reproduce the bug?

1. Go to GHelper app
2. Try to switch keyboard light color
3. ???
4. repeat step 3 until the heat death of the universe

### Logs

[log.txt](https://github.com/user-attachments/files/16366511/log.txt)

### Device and Model

Asus Vivobook S 14 OLED M5406UA

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.179.0

### OS

Windows 10 Pro Version 10.0.19045 Build 19045

**Comment by seerge** [comment]
@Cruzys does your model support different backlight colors in a first place ? How did you control that using asus apps ?

**Comment by Cruzys** [comment]
> @Cruzys does your model support different backlight colors in a first place ? How did you control that using asus apps ?

yes it does support different colored backlights but the only way that i know to do it is with windows 11 dynamic lightning.
I tried Armoury Crate, OpenRGB, the Aura application and nothing worked.

**Comment by seerge** [comment]
@Cruzys try to disable DYnamic Lighting in windows, and check if settings in G-Helper work. If they don't - it's probably supported only via dynamic lighting itself ...

**Comment by Cruzys** [comment]
> @Cruzys try to disable `Dynamic Lighting` in windows, and check if settings in G-Helper work. If they don't - it's probably supported only via dynamic lighting itself ...

well, problem is that I am on windows 10 and it doesn't have such an option, to disable dynamic lightning.Why make anything simple Asus....

**Comment by Cruzys** [comment]
> @Cruzys i think you can do that via registry flag `Software\Microsoft\Lighting` by setting `AmbientLightingEnabled` to `0`

ok will try brb

**Comment by Cruzys** [comment]
> @Cruzys i think you can do that via registry flag `Software\Microsoft\Lighting` by setting `AmbientLightingEnabled` to `0`
I changed the value and went back to the application and nothing.
I restarted and tried again, nothing.
Idk what kind of black magic did the people at ASUS use to make this simple thing so difficult for someone who doesn't want to use windows 11.

**Comment by seerge** [comment]
@Cruzys it's still possible to try "reverse engineer" how dynamic lighting controls backlight on your device (if that works there at least)

For start, can you do a DSDT dump as explained in [Method 2 here ? ](https://github.com/seerge/g-helper/issues/38)

**Comment by Cruzys** [comment]
> @Cruzys it's still possible to try "reverse engineer" how dynamic lighting controls backlight on your device (if that works there at least)
> 
> For start, can you do a DSDT dump as explained in [Method 2 here ? ](https://github.com/seerge/g-helper/issues/38)

[dsdt.zip](https://github.com/user-attachments/files/16367372/dsdt.zip)
is this ok?

**Comment by seerge** [comment]
@Cruzys ok, i see that endpoint responsible for RGB colors for Vivobooks / Zenbooks and TUF models is there - ``0x0010005a``

So it should be same as on other laptops.

There is a good chance that Dynamic Lighting from windows simply overrides color command (same happens for any model that supports dynamic lighting in a first place)

So it would be good if you can test it w/o dynamic lighting somehow ...

**Comment by Cruzys** [comment]
> @Cruzys ok, i see that endpoint responsible for RGB colors for Vivobooks / Zenbooks and TUF models is there - `0x0010005a`
> 
> So it should be same as on other laptops.
> 
> There is a good chance that Dynamic Lighting from windows simply overrides color command (same happens for any model that supports dynamic lighting in a first place)
> 
> So it would be good if you can test it w/o dynamic lighting somehow ...

would deleting the whole registry file do anything?

**Comment by seerge** [comment]
@Cruzys you don't need to delete anything, and especially registry files :)

You can just adjust a single flag in registry (the one i mentioned above) 
https://www.reddit.com/r/LogitechG/comments/1alf7td/how_do_i_disable_dynamic_lightning_on_windows_11/

If it does not work - i don't know how else you could do that. 

Since any other tools (even asus own) can't control lighting - there is literally no way to check / fix it anyhow else ...

**Comment by Cruzys** [comment]
> @Cruzys you don't need to delete anything, and especially registry files :)
> 
> You can just adjust a single flag in registry (the one i mentioned above) https://www.reddit.com/r/LogitechG/comments/1alf7td/how_do_i_disable_dynamic_lightning_on_windows_11/
> 
> If it does not work - i don't know how else you could do that.
> 
> Since any other tools (even asus own) can't control lighting - there is literally no way to check / fix it anyhow else ...

Yeah... no luck. Nothing changed after modifying again the registry flag. I will try to post this issue on the ROG forum to see if anyone has any other idea or if am simply f#cked by not using windows 11.
Thank you for the interest you've shown in trying to resolve my problem <3

**Comment by seerge** [comment]
@Cruzys ok, no worries. Closing as not planned then as there is no open-source solution atm or a way to verify if current way of setting backlight works and is just simply overwritten by dynamic lighting. 

If you will find a way to control backlight somehow (i.e. via win11 or any other app) feel free to reopen and post an update

Thanks

**Comment by Zoher15** [comment]
@Cruzys I was able to change my keyboard color through Windows dynamic lighting:Through Windows Settings (GUI - Recommended First)

This is the safest and easiest way to try and control it with Windows Dynamic Lighting.

Re-enable Dynamic Lighting: In Registry Editor, change AmbientLighting back to 0x00000001 (1).
Restart your PC.
Go to Windows Settings:
Open Settings.
Go to Personalization.
Click on Dynamic Lighting.
Check for your keyboard: You should see your laptop's keyboard listed as a "device card" at the top of this page.
Configure the color:
Select your keyboard.
Look for the Effects section. You should see options for Brightness, Effects (like static, breathing, wave, etc.), and Colors.
Choose a Static effect if available.
Then, try to select Red from the color palette. If there's an option for "Use Windows accent color," disable it if it's on.

**Comment by src-img** [comment]
Having the same issue--downgraded the Vivobook S14 to Windows 10, and can't for the life of me get the keyboard to change colors without the dynamic lighting settings pane that Windows 11 has. I scoured my registry files, but I couldn't find heads or tails of `Computer\HKEY_CURRENT_USER\Software\Microsoft\Lighting`. The issue seems pretty done and dusted as non-workable, but figured I'd mention it in case you've learned new things in the last year.
