### ISSUE TITLE
Fn-Lock won't stay enabled on reboot, despite showing as enabled in G-helper

### ISSUE THREAD

**Issue by ericswpark** [seerge/g-helper#2879]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When rebooting my GA403UV, the Fn-Lock will get disabled, and I won't be able to use the printed macro keys (brightness control, etc.) until I go into G-helper, disable Fn-Lock, and re-enable it.

### How to reproduce the bug?

1. Enable Fn-Lock
2. Reboot

### Logs

[log.txt](https://github.com/user-attachments/files/16374661/log.txt)

### Device and Model

Asus Zephyrus G14 GA403UV

### Armoury Crate

Never installed

### Asus Services

0

### Version

0.179.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@ericswpark hello,

Does `FN-Lock` button stay Blue in G-Helper's main window after you reboot ?

**Comment by ericswpark** [comment]
@seerge yes, to all three questions. It only starts working again if I unset it (gray) and then set it back to blue again.

Also thank you so much for the tool! It's really snappy and I don't like installing OEM bloatware.

**Comment by seerge** [comment]
@ericswpark hmm, if it stays Blue, it means it's enabled. 

And app should register `F1` .. `F11` as own "hotkeys" in Windows, and therefore process them windows notifies app about keypress. (`F12` is not covered by FN-Lock cause it's reserved by system)

Do all 11 keys stop working after reboot, or only some ? My guess is that you have some other app that starts AFTER G-Helper and re-registers keys as own ...

**Comment by ericswpark** [comment]
I just tried rebooting to reproduce the issue, but it's working fine now for some reason. Sorry for the false alarm -- I'll close the issue and let you know if it comes back again.

By register, do you mean the Fn-Lock functionality is not toggled through the firmware like some other options? Maybe I pressed the buttons too early after signing in, when G-Helper didn't get the chance to load in and register the hotkeys.

**Comment by seerge** [comment]
@ericswpark there is no Fn-Lock in firmware. It's a pure software emulation.

App just tells windows to notify itself when user would press F1-F11, and then runs appropriate actions.
