### ISSUE TITLE
Fans fail to kick in after booting up

### ISSUE THREAD

**Issue by sprutxz** [seerge/g-helper#2880]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

This might be a weird bug but After I shut down my laptop for the night and boot it up in the morning the fans refuse to kick in. The CPU fans run at 0 rpm at both balanced and turbo mode. Similar behavior is observed for the GPU fans. 

I have an external monitor connected through the dGPU USB-C port but I'm unsure if that is related to the bug being caused. I was also on the 3.1.31.0 update of the ASUS control interface v3 which i have now updated to the latest version. I tried multiple restarts but the fans didn't work. 

A power reset did make the fans start working like normal though. Another fix i found was running the myASUS fan diagnosis which also fixed the fans without doing a power reset.

### How to reproduce the bug?

1. Shut down laptop while connected to an external monitor
2. Boot while still being connected to the monitor

### Logs

[log.txt](https://github.com/user-attachments/files/16381148/log.txt)

### Device and Model

Asus Zephyrus G14 GA402XV

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.179.0

### OS

Windows 11, 23H2

**Comment by seerge** [comment]
@sprutxz hello, G-Helper does not control your fans, [they are controlled by BIOS. ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)

If you don't like how BIOS behaves, you can try to use [Experimental build with manual fan control.](https://github.com/seerge/g-helper/discussions/2272)

Thanks.

**Comment by sprutxz** [comment]
> @sprutxz hello, G-Helper does not control your fans, [they are controlled by BIOS. ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)
> 
> If you don't like how BIOS behaves, you can try to use [Experimental build with manual fan control.](https://github.com/seerge/g-helper/discussions/2272)
> 
> Thanks.

So this bug might be due to the BIOS glitching?

**Comment by seerge** [comment]
@sprutxz yes, most probably. Do you have latest BIOS ?

**Comment by sprutxz** [comment]
> @sprutxz yes, most probably. Do you have latest BIOS ?

Yes I do or atleast that's what it says in g-helper. I might contact ASUS for support in case this is a BIOS related issue

**Comment by seerge** [comment]
@sprutxz you can also try [Hard reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hardware-reset--cmos-reset), this can sometimes help to solve some BIOS related issues

**Comment by sprutxz** [comment]
> @sprutxz you can also try [Hard reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hardware-reset--cmos-reset), this can sometimes help to solve some BIOS related issues

I tried hard reset multiple times. Though this fixes the fans after the boot up, the issue still persists after i shut down my computer and boot it up again

**Comment by seerge** [comment]
@sprutxz i also see that asus ACPI / windows spams some WMI event notification all the time

```
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:32 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
7/25/2024 12:14:33 PM: WMI event 192
```

I don't know what 192 stands for (could be something usb-c power  related?) but it's clearly not normal that it spams that like crazy.

Try to disconnect your monitor, to see if it makes a difference

**Comment by sprutxz** [comment]
> @sprutxz i also see that asus ACPI / windows spams some WMI event notification all the time
> 
> 
> 
> ```
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:32 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> 7/25/2024 12:14:33 PM: WMI event 192
> 
> ```
> 
> 
> 
> I don't know what 192 stands for (could be something usb-c power  related?) but it's clearly not normal that it spams that like crazy.
> 
> 
> 
> Try to disconnect your monitor, to see if it makes a difference

I disconnected every peripheral and did a restart but the issue persists. This is definitely a bios problem

**Comment by seerge** [comment]
@sprutxz most likely.

You can try the experimental build i linked above. It uses MyASUS "fan testing" command to manually set fan speeds, so that one will probably work. But of course this is not a "sustainable" solution, as fans should work by default as well. And since you have a very popular model, that lots of people use and have no such issue - it would be good to look for a solution here.

I'm closing this as answered, as G-Helper can't do anything here anyway

Thanks.
