### ISSUE TITLE
Not detecting gpu temp and adjusting fan speed

### ISSUE THREAD

**Issue by the-traveler369** [seerge/g-helper#2882]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

v.180 and the beta, Both do not detect my gpu temp and adjust fan speed. I will open up ghelper because keyboard is getting toasty. it does not display temp nor fan speed. Rolled back to .179, this seems to work perfectly for my laptop. I am not super tech savy. I dont know how to bring logs into this. I am not sure if someone elses is having this issue. There are no real reproduction steps as it just doesnt show the the temp or fan speed.
I think the log files below are for the version i am running that works. 

### How to reproduce the bug?

Download net 8
Download ghelper
Open, adjust fan curves, close, Open and no gpu temp or fan speed

### Logs

[ghelper log.txt](https://github.com/user-attachments/files/16385296/ghelper.log.txt)

### Device and Model

2023 Asus Tuf A16 Advantage edition

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.179

### OS

Windows 11 Home 23H2

**Comment by seerge** [comment]
@the-traveler369 hello, I don't see you launching 0.180 anywhere in the log, only 0.179

Can you download 0.180 and run it, and post a log + screenshot of your problem here ?

There is absolutely nothing changed neither in relation to GPU temp readings, or anything else in 0.180 comparing to a previous release tho.

Also please remember, G-Helper does not control fan speeds in realtime anyhow, [BIOS does ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds). 

Thanks

**Comment by seerge** [comment]
@the-traveler369 any updates here ?

**Comment by alxolo** [comment]
Hello, 
I observer the following behavior in "Standard" and "Optimized" GPU mode:
1. Fan speed displayed always
2. GPU temperature  shown only and only if at least one process use GPU, no process which use GPU = no temperature displayed.
As I remember the same was with 0.180 version.
Do not sure if this is critical issue or some kind of feature. Sure it better to manage temperature control regardless in use GPU or do not.  If you will need any logs I will upload them.

**Comment by alxolo** [comment]
@seerge  Hello, 
I am completely agree. Was not clear, just want to point that temperature is not always available.
Even more in theory, on systems with advanced optimus, discrete graphics card should be turned off when not in use, and turned on when need on by request.
For me keyboard and fan control works just fine.
Sorry for intervention.

**Comment by seerge** [comment]
Due to lack of response, closed as abandoned
