### ISSUE TITLE
USB-C keeps powering USB-C hub (HDMI/USB) when laptop is powered off / hibernated / sleep

### ISSUE THREAD

**Issue by FelipeAlma** [seerge/g-helper#2884]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

once hibernated, the USB-C hub light stays ON forever, can the port be turned off when laptop is in any state besides ON?, this charging like behabor has caused isues with overheating external devices like USB-C external hubs.

### Describe the solution you'd like

Whenever the PC is not running, it would be nice to turn off all ports with a toggle indicating that you are not charging any external devices connected.

### Device and Model

Asus 2024 Rog strix scar 18 G834JZR

**Comment by seerge** [comment]
@FelipeAlma hello,

I believe this is controlled by BIOS. You can try to find something about "USB power saving" in BIOS menu (F2 on boot). Application in windows can't control that anyhow. 

Sorry. Thanks
