### ISSUE TITLE
Asus ROG Eye S not detected on Windows Camera - 

### ISSUE THREAD

**Issue by castipo-hub** [seerge/g-helper#2885]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

**not detected camera ROG EYE S on my Windows Camera ROG STRIX G513QY but working on Chrome/Browsers**
![image](https://github.com/user-attachments/assets/a416bc87-ce76-4288-a660-629e543c589e)

![image](https://github.com/user-attachments/assets/6a3b40a7-ead5-41c4-95cb-9f09e5a64f0e)
![image](https://github.com/user-attachments/assets/1d103240-9970-481a-9e4d-53399dfbb53a)

maybe i need to install the driver official from website but i dont want to install Armoury Crate
https://rog.asus.com/id/streaming-kits/rog-eye-s-model/helpdesk_download/

### How to reproduce the bug?

i am open windows camera the something error in the begining, but working on chrome 
i am installed driver asus rog eye s , and detected on devices manager 

![image](https://github.com/user-attachments/assets/83c0edd7-83b6-49ed-b182-89a5f1917f7e)
![image](https://github.com/user-attachments/assets/429341e9-c2cd-48a1-9a05-ca0d3e68260d)
![image](https://github.com/user-attachments/assets/d62983a6-73ee-48df-89a6-e57b58c96a84)
![image](https://github.com/user-attachments/assets/828661b2-bdb2-4e59-b3a1-4050a18e705d)
![image](https://github.com/user-attachments/assets/a9d26809-7bb9-4b26-8d60-179a1aaba972)
![image](https://github.com/user-attachments/assets/5a199910-74f3-46c5-bb4f-e21f4e10658b)
![image](https://github.com/user-attachments/assets/7b52d1c4-b990-48be-ae23-8a45ac5c8a3c)

![image](https://github.com/user-attachments/assets/e4fc99f7-4f15-468e-9f07-af4390120adf)

### Logs

[log.txt](https://github.com/user-attachments/files/16401928/log.txt)

### Device and Model

Asus ROG Strix G513QY

### Additional information.

![image](https://github.com/user-attachments/assets/d3cb7ccf-e95c-4fa2-bea3-7d3a6c33bde3)

### Armoury Crate

Uninstalled

### Asus Services

Asus Services Running: 7

### Version

Version: 0.179.0

### OS

Version 23H2 OS Build 22631.3880

**Comment by LeoRH123** [comment]
try following steps here:
[https://rog.asus.com/us/support/faq/109836/#:~:text=Use%20the%20built-in%20camera%20application%20Check%20the%20status,Point%20to%20restore%20the%20system%20Reset%20the%20system](url)
it could be camara app error because on your browsers it works correctly, I don't think it has something to do with G-helper.

**Comment by castipo-hub** [comment]
> try following steps here: https://rog.asus.com/us/support/faq/109836/#:~:text=Use%20the%20built-in%20camera%20application%20Check%20the%20status,Point%20to%20restore%20the%20system%20Reset%20the%20system
> 
> it could be camara app error because on your browsers it works correctly, I don't think it has something to do with G-helper.

i am appriciated but that step i follow , but cannot work too

**Comment by castipo-hub** [comment]
![image](https://github.com/user-attachments/assets/18370650-fa4a-4f3a-bae6-743400b67bd7)

now i install armoury crate and there's update software from there, maybe that the problem, i hope g-helper include the update of the rog eye s software too

**Comment by seerge** [comment]
@castipo-hub hello. 

I don't really understand how is this related with G-Helper ? You have a 3rd party device that works with windows. I see that it's detected and listed in device manager. So it should be available in applications as well. If not - check some webcam troubleshooting steps, or permissions in windows / browsers.

G-Helper is not controlling your webcam and is not supposed to, it's not a operating system and is not a driver.

The Aura CORE SDK on your screenshot is to my best knowledge an Armoury's own component for controlling RGB backlight, that is needed only for Armoury itself.

Thanks.
