### ISSUE TITLE
Asus rog strix g16 support 

### ISSUE THREAD

**Issue by taha29123** [seerge/g-helper#2886]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I am currently using G helper on my asus rog strix g16 but it isn't included in supported laptops list 
Does using G helper harm my laptop or have long term consequences 

### Describe the solution you'd like

Adding asus rog strix g16 support because it is one of the most popular gaming laptop in last 2 years

### Device and Model

Asus rog strix G16

**Comment by seerge** [comment]
@taha29123 hello, your model is supported same as any modern model and is mentioned on the homepage.

> Works with all popular models, such as ROG Zephyrus G14, G15, G16, M16, Flow X13, Flow X16, Flow Z13, TUF Series, Strix / Scar Series, ProArt, Vivobook, Zenbook, ROG Ally and many more!

Thanks
