### ISSUE TITLE
Is it possible to overclock the graphic memory beyond 500mhz limit

### ISSUE THREAD

**Issue by masteryf** [seerge/g-helper#2887]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

The maximum offset of video memory is only 500mhz

### Describe the solution you'd like

I hope to use g-helper to overclock the video memory more than 500mhz

### Device and Model

ASUS Zepgyrus M16 GU603ZX

**Comment by seerge** [comment]
@masteryf hello, yes it is possible. [Please check readme on how to do that.](https://github.com/seerge/g-helper/wiki/Power-user-settings#higher-maximum-and-minimum-gpu-clock--memory-offsets)

Thanks.
