### ISSUE TITLE
G713QR (2021) freezes annoyingly in battery mode.

### ISSUE THREAD

**Issue by mgodoyretamales** [seerge/g-helper#2889]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Laptop freezes between 10sec and about 5 min when unplugging. This issue began a lot of time ago after a BIOS upgrade (about version 320) when G-helper updated to version 0.179. This issue happened if I put in any Power mode, but in Turbo very less probable (but drains my battery too fast and make some noise with fans).  
I’ve tried to do some clean windows installations, in a new SSD and a default one, but in those cases my laptop freeze in 89% and 93% respectively.
I ran the entire G-Helper troubleshooting and also tried to clear video drivers and installing the last version (2022) from Asus site, didn’t work neither.
I also tried many solutions from reddit forums.
Thanks in advance. 

### How to reproduce the bug?

1.	After unplug power cable from laptop.
2.	Mostly in Eco GPU mode, and Balance and Silent mode.
3.	Laptop freezes and I have to shut down with power button. Reboot without issue.

### Logs

[config.json](https://github.com/user-attachments/files/16405513/config.json)
[log.txt](https://github.com/user-attachments/files/16405514/log.txt)

### Device and Model

Asus ROG G713QR (2021)

### Additional information.

Laptop:
•	BIOS: v330
•	AMD 5900HX with RTX 3070

Software and config.
•	Armoury crate uninstalled 
•	MyASUS uninstalled
•	Asus system control Interface installed (for services)
•	Asus services stopped
•	Adrenaline 24.7.1 (issue also happened in “minimal installation”)

Windows Configs:
•	Processor Performance Boost Mode: disable (also happened when enable)
•	Core isolation disable (also happened when enable)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.179

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@mgodoyretamales hello, does your problem happen if you just quit G-Helper ?

**Comment by mgodoyretamales** [comment]
Thanks a lot for your fast reply!
Following your steps, I put Balanced mode, then unplug the cable, closed the G-Helper and my laptop freeze almost instantly =’( (faster than usual)
With 89 and 93% I meant to windows installing process (photo attach) and when this it keep freeze, so I can’t do perform a clean installation.
![Windows clean Install](https://github.com/user-attachments/assets/175fcd07-4422-4fa9-ae9f-4449ebecef1a)

Do you have any idea about what’s going wrong?
Thanks!

**Comment by seerge** [comment]
@mgodoyretamales hello,

If your device freezes during windows install it's clearly not software related at all (as there are no apps involved here).

If you say it started happening after latest BIOS update - try to roll back a previous version from asus website. 
If it doesn't help - most likely it's some hardware problems that you have, so I would just check up with the service.

I'm closing, as this is not related to the app and i can't help you anyhow besides wishing good luck :)

Thanks
