### ISSUE TITLE
Add support for ROG Zephyrus G16 2024 AMD

### ISSUE THREAD

**Issue by ItsLucas** [seerge/g-helper#2892]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I'm currently using G-Helper, but since this laptop has just been released yesterday, some feature may not be complete.
Not working: 
No slash lighting control
Advanced CPU tuning are limited (only temp settings are available)
No curve optimizer settings (It should be available since it's an AMD laptop whatsoever)

### Describe the solution you'd like

Enable support for G16 AMD like the Intel variant. (or like Zephyrus G14, if more similar)

### Device and Model

ROG Zephyrus G16 GA605WV (as shown on G-Helper title bar)

**Comment by seerge** [comment]
@ItsLucas hello,

Do you have AMD model already? If so - can you post a log from `%appdata%\GHelper`? I will check why Slash Lighting is not there.

As for AMD undervolting, most l probably it's not possible yet at all. As for this purpose G-Helper uses [UXTU's library](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility) under the hood. 

Try to check if UXTU is able to set curve optimizations and if they really work (cause it could be that they are visible in UI but do nothing for example there)

Thanks

**Comment by seerge** [comment]
@ItsLucas and try this build, I have noticed that model name for AMD device (GA605) is different from Intel (GU605), I have added it to the Slash Lighting models list

[GHelper.zip](https://github.com/user-attachments/files/16410649/GHelper.zip)

**Comment by ItsLucas** [comment]
Hi,
I've tried your build, and slash lighting is still missing.
Here's the log attached from your build.
[log.txt](https://github.com/user-attachments/files/16414385/log.txt)

**Comment by ItsLucas** [comment]
It's ok for not having curve optimizer, since zen5 cores are already pretty efficient.
I'll gtg sleep soon, if more information is needed just leave me comments

**Comment by ItsLucas** [comment]
![image](https://github.com/user-attachments/assets/4d042b85-c029-4c8e-a0b5-7417a6a3a202)

**Comment by seerge** [comment]
@ItsLucas ok, can you download https://www.nirsoft.net/utils/usbdeview-x64.zip

And then find ASUS device with Product ID ``0x193B`` there and post it's full details ?

I'm mainly interested in Feature Report Length param

**Comment by ItsLucas** [comment]
Hi,
I didn't find any device with mentioned Product ID.
I will attach a complete list of all usb devices found below.
[listusb.txt](https://github.com/user-attachments/files/16420283/listusb.txt)

**Comment by seerge** [comment]
@ItsLucas hello, your list doesn't contain anything from asus at all. Can you please check for Asus devices with a similar product IDs ? It will be keyboard with 19b6 and something else . Thanks

![image](https://github.com/user-attachments/assets/f4fb7591-7ec0-42af-8f12-fd7fa5972614)

**Comment by ItsLucas** [comment]
This is everything I got from the output
![image](https://github.com/user-attachments/assets/adb050a4-e5af-4f34-9bde-8f107ef8b840)

**Comment by seerge** [comment]
@ItsLucas well, it has to be a device to communicate with it. Do you run USB view with admin permissions ? 
You could have some strange local edition, with messed up IDs, etc.

You can check my discussion here https://github.com/seerge/g-helper/discussions/2046 and try to figure out how AC communicates with Slash Lighting device

**Comment by ItsLucas** [comment]
1. Yes, I do run the program as admin.
2. Earlier GU605 (G16 Intel) is fine in my country, naybe they messed up only in GA605
I'll try and capture some packages

**Comment by seerge** [comment]
@ItsLucas try to search by feature report length, should be 128 for Slash

**Comment by ItsLucas** [comment]
@seerge I tried device monitoring studio, and they seems to integrate everything into the only one Asus Device (0b05) 
When I press keyboard, it logs;
When I change slash lighting mode, it logs crazily...

**Comment by ItsLucas** [comment]
[slash lighting log.txt](https://github.com/user-attachments/files/16424208/slash.lighting.log.txt)
[slash_raw.txt](https://github.com/user-attachments/files/16424212/slash_raw.txt)
I got something for you, maybe it'll help

**Comment by ItsLucas** [comment]
[Desktop.zip](https://github.com/user-attachments/files/16424293/Desktop.zip)

**Comment by seerge** [comment]
@ItsLucas check if this build sees Slash
[GHelper.zip](https://github.com/user-attachments/files/16424405/GHelper.zip)

**Comment by seerge** [comment]
@ItsLucas could be, i'm not able to check DMS Log yet, but if protocol has change it means that we need to go through all steps from https://github.com/seerge/g-helper/discussions/2046 all over again

**Comment by seerge** [comment]
@ItsLucas can you quickly look at packets in monitoring studio, and check if you see Init command somewhere similar to this one
```
5E D7 00 00 01 AC  
```

It could be that only the first byte (i.e.`5E` has changed to something else)

**Comment by ItsLucas** [comment]
5D D2 02 01 08 AC                                 ]?..?.
 5D D3 03 01 08 AC FF FF 01 05 FF FF 00 00 00 00   ]?..?........
 5D D4 00 00 01 AC 00 00 00 00 00 00 00            ]?...?.......
 5D D2 02 01 08 AB 00 00 00 00 00 00 00 00         ]?..?.........
 5D D2 01 13 40 00                                  ]?.@.

**Comment by seerge** [comment]
@ItsLucas try this build
[GHelper.zip](https://github.com/user-attachments/files/16424616/GHelper.zip)

**Comment by ItsLucas** [comment]
This build works perfectly.
Tested mode, on/off, brightness, interval, all function seems to be ok

**Comment by seerge** [comment]
Ok, amazing

**Comment by ItsLucas** [comment]
With some quick explore of related code in G-Helper
That seems just a public SlashPacket(byte[] command) : base(0x5D, 128, command)
dunno why asus's bother to change this

**Comment by ItsLucas** [comment]
Fun fact: G-Helper is the ONLY way to switch to Integrated graphics on GA605
The AC is buggy, and the button won't work

**Comment by seerge** [comment]
@ItsLucas yes, that is exactly what I have changed in the last build.

I will prepare a split in the code to support slash on other devices and yours and include in the next release then.

Thanks for testing

**Comment by ItsLucas** [comment]
I don't know how the EC is programmed, but according to my USB power meter, having the dGPU sleeping rather than turned off
leads to ~4W additional power draw in modern standby.
amazing power management, ASUS

**Comment by seerge** [comment]
@ItsLucas btw, can you test if Custom power limits work on your device without applying a Custom fan curve next to them (under Fans + Power).

But please use mainstream build (i.e. latest 0.181 or 0.179)?

Cause on some models to make power limits work you also need to set fans (same as AC does in manual mode) and on some - you don't 

In the build linked here app already silently sets fan curve if power limits are checked , cause G16 2024 with Intel required that ...

**Comment by ItsLucas** [comment]
Before reporting this issue, I've already using 0.181 and can successfully cap my CPU power without ticking the fan curve box

**Comment by seerge** [comment]
@ItsLucas ok, can you also check if a custom battery charge limits work on your device, like 90%?

**Comment by ItsLucas** [comment]
> @ItsLucas ok, can you also check if a custom battery charge limits work on your device, like 90%?   As Intel model supports only 60-80% range 

when I set charge limit to above 80% it just jumps to 100%

**Comment by ItsLucas** [comment]
I used the latest stable release, found that I can slide the slider freely.
How to check if the carge limits are actually working?

**Comment by seerge** [comment]
@ItsLucas discharge laptop below 90, set 90 an monitor if it stops charging there or not

**Comment by ItsLucas** [comment]
Hi,
It seems that the charge limiter works between 55%-80%.
Setting anything below or above will trigger charging.

**Comment by alnandr** [comment]
@seerge Let me know if I can contribute to supporting these new laptops. I have the GA405WI model (upgraded configuration with RTX 4070) from ASUS for review, but I have not switched AC for G-Helper, anticipating that support for these new models may not be available yet. Would a log file suffice for your needs?

**Comment by seerge** [comment]
@ItsLucas hello, sorry for delay. Can you check if this build **still** shows and allows control for Slash Lighting ? (I have added a switch to support "both" versions of it for other devices and GA605)

[GHelper.zip](https://github.com/user-attachments/files/16478938/GHelper.zip)

@alnandr you can try that build as well. If you will read discussion in this thread Slash Lighting was pretty much the only missing part (as it's ID has changed specifically in this model comparing to others)

**Comment by seerge** [comment]
Live in https://github.com/seerge/g-helper/releases/tag/v0.182

**Comment by alnandr** [comment]
> Live in https://github.com/seerge/g-helper/releases/tag/v0.182

This build does not see Slash Lighting on my GA405WI. Attached my log file.
[log.txt](https://github.com/user-attachments/files/16489239/log.txt)

**Comment by seerge** [comment]
@alnandr can you post a list of devices from asus (vendor id 0b05) using https://www.nirsoft.net/utils/usbdeview-x64.zip here ?

**Comment by seerge** [comment]
@alnandr and can you check if this build makes a difference ?
[GHelper.zip](https://github.com/user-attachments/files/16502894/GHelper.zip)

**Comment by Dulshad** [comment]
With the build from your last reply, I can see the slash lighting(Previous didn't), however the config does nothing to the lighting. I use G16 GA605WV-QP060W.  Same like the other user I only have one device from vendor id 0b05.

![image](https://github.com/user-attachments/assets/e5b48a42-9692-42da-a045-745cd0ee5107)

**Comment by alnandr** [comment]
> @alnandr and can you check if this build makes a difference ? [GHelper.zip](https://github.com/user-attachments/files/16502894/GHelper.zip)

Same findings as Dulshad, Slash Lighting is now visible but nothing changes when modifying the configuration.

![image](https://github.com/user-attachments/assets/7e4d92b5-b37d-4124-89cf-ef1f463093cf)

**Comment by ItsLucas** [comment]
> @alnandr and can you check if this build makes a difference ? [GHelper.zip](https://github.com/user-attachments/files/16502894/GHelper.zip)

tried this build, the slash lighting control also breaks.

**Comment by seerge** [comment]
@ItsLucas @alnandr @Dulshad 

Ok, one more attempt - can you try if this build works ?

[GHelper.zip](https://github.com/user-attachments/files/16508610/GHelper.zip)

**Comment by alnandr** [comment]
> @ItsLucas @alnandr @Dulshad
> 
> Ok, one more attempt - can you try if this build works ?
> 
> [GHelper.zip](https://github.com/user-attachments/files/16508610/GHelper.zip)

Slash Lightning disappeared from the configuration screen.

**Comment by seerge** [comment]
@alnandr that’s strange, can you post a log from this build?

**Comment by seerge** [comment]
@alnandr @Dulshad @ItsLucas one more attempt, try this build instead

[GHelper.zip](https://github.com/user-attachments/files/16513190/GHelper.zip)

**Comment by Dulshad** [comment]
@seerge Hello, it works now! Thank you for your work!

**Comment by seerge** [comment]
@ItsLucas ok, finally :)

**Comment by alnandr** [comment]
Glad to hear, I will test on my model when I get home tonight and report back that both configs are covered :) great work as usual @seerge

**Comment by seerge** [comment]
Ok, great. Pushed last tweaks into https://github.com/seerge/g-helper/releases/tag/v0.183

**Comment by HL2512** [comment]
Hello @seerge , can you please tell me how long the g16 with amd CPU last with the new build you have with the G-Helper? Thank you so much for your possitive feedback.

**Comment by seerge** [comment]
@HL2512 hello, what exactly do you mean under "last" ?

**Comment by HL2512** [comment]
Oh sorry, my English was bad. What I mean was about the battery life, like how long I can use it with something like VSCode, Discord and Brave ( a web browser). Do you have any ideas about it?

**Comment by seerge** [comment]
@HL2512 ah, I guess it really depends on actual tasks running and power consumption :) I guess if you manage everything in a 8-10W discharge rate you should fit into 7-10 hours )

**Comment by HL2512** [comment]
Oh, thank you so much for your feedback, but just one more question, is the G-helper work with the duo 16 ( the zephyrus station lol :))) ) and make it better?

**Comment by seerge** [comment]
@HL2512 yes - it does work with DUO 16 (pretty much as with any modern asus laptop / handheld)

**Comment by HL2512** [comment]
Thank you so much for your answer man, have a great day. or night in your place :>
