### ISSUE TITLE
Eco mode but - Waking up from Sleep(S3) with only black screen

### ISSUE THREAD

**Issue by lisienskenderi** [seerge/g-helper#2893]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When trying to wake up from sleep(S3), not modern standby, and having put the GPU on Eco Mode the machine only has a black screen when trying to wake it up.

### How to reproduce the bug?

1. Switch the Gpu to Eco mode
2. Put the machine to sleep
3. Wake the machine from sleep

### Logs

[log.txt](https://github.com/user-attachments/files/16414428/log.txt)

### Device and Model

Asus TUF F16 FX607JV

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.179.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@lisienskenderi hello, 

G-Helper is not managing windows sleep and not turning your screen ON :) it's not an operating system.

If having dGPU disabled (i.e. `Eco` mode) doesn't work well with S3 sleep, it's probably a side effect of the changes you did to disable modern standby.

Try to do a clean reinstall of [Intel GPU drivers (using DDU)](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers) or other [Troubleshooting](https://github.com/seerge/g-helper/wiki/Troubleshooting) steps.

Does same happen if you would disable dGPU using AC ? (i.e. set Eco there)

**Comment by seerge** [comment]
P.S. How do you wake up your device from sleep? Try clicking on power button, it usually works better than keyboard wake-up

**Comment by lisienskenderi** [comment]
Reinstalled intel drivers but still the same problem. Activating the option to enable the GPU on shutdown strangely fixes it(it switches the modes of the GPU when waking up from sleep). Sometimes though when switching from hybrid modes to Eco mode the screen goes completely black and the only way to fix it, without turning off the machine using the button, is to plug the charger.
PS. Sorry for the late reply.

**Comment by seerge** [comment]
@lisienskenderi glad to hear that enabling GPU on shutdown somehow affects it. Even tho it's a sleep not a shutdown, and G-Helper is not involved here.
