### ISSUE TITLE
Program crash and keyboard issues

### ISSUE THREAD

**Issue by Sultan-papagani** [seerge/g-helper#2895]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

1- Clicking on both Quiet and Eco modes crashes the app
2- When the app opened back and when i choose standart and balanced mode again fans doesnt spin and its stays at 0rpm (no fan noise too) i restart my computer to spin the fans again, i dont know maybe im not waiting enough
3 - When i open the app, keyboard lighting goes more dim than i can select, playing with the slider fixes this
4 - Keyboard light modes doesnt do anything expect rainbow and stationary because i think you have to select two colors to make it work (it was like that in armory create)
5 - (feature request) we cant see the gpu temp :(

Operating system: Win11 but not activated it (so there is a overlay)
Running asus tasks: 0 (i removed all of it, but asus interface and stuff shows up in the device manager also i stopped the all asus services)
Program lang: tr
Sorry for really bad english

### How to reproduce the bug?

no info

### Logs

[log.txt](https://github.com/user-attachments/files/16419358/log.txt)

### Device and Model

Asus Rog Strix G614JU 

### Additional information.

no info

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.179.0

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@Sultan-papagani hello,

> 1- Clicking on both Quiet and Eco modes crashes the app

Can you open windows Event Viewer app, look for crash logs mentioning `GHelper.exe` and post contents of the error here ? 

> 2- When the app opened back and when i choose standart and balanced mode again fans doesnt spin and its stays at 0rpm (no fan noise too) i restart my computer to spin the fans again, i dont know maybe im not waiting enough

G-Helper does not control your fans, [fans are controlled by BIOS](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds). You use default balanced mode w/o any custom fan curves, and it's absolutely normal for BIOS to keep fans  if it's not needed.

> 3 - When i open the app, keyboard lighting goes more dim than i can select, playing with the slider fixes this
When you open app it would set last used backlight brightness for plugged in / on battery states. 

> 4 - Keyboard light modes doesnt do anything expect rainbow and stationary because i think you have to select two colors to make it work (it was like that in armory create)

You have model with basic 4-zone RGB as far as I understand, so all modes that app lists should work, as they are baked into keyboard firmware. Which specific mode does not work ?

> 5 - (feature request) we cant see the gpu temp :(
If you mean GPU Temp limit - you can set it under `Fans+Power` -> `GPU` tab same as it happens in manual mode in AC.

**Comment by Sultan-papagani** [comment]
Proses C:\Users\sultan\Desktop\GHelper.exe (proses kimliği:12920) katman ilke düzenini {961cc777-2547-4f9d-8174-7d86181b8a7a}'ten {00000000-0000-0000-0000-000000000000} 'e sıfırla
Proses C:\Users\sultan\Desktop\GHelper.exe (proses kimliği:18680) katman ilke düzenini {00000000-0000-0000-0000-000000000000}'ten {961cc777-2547-4f9d-8174-7d86181b8a7a} 'e sıfırla
Proses C:\Users\sultan\Desktop\GHelper.exe (proses kimliği:18236) katman ilke düzenini {ded574b5-45a0-4f42-8737-46345c09c238}'ten {00000000-0000-0000-0000-000000000000} 'e sıfırla

I can only find these on the event viewer: (Windows Logs -> System)
nothing on the (Windows Logs -> Applications)
2, 3 4, 5th problems are solved and okay

**Comment by Sultan-papagani** [comment]
Okay i think the first issue is also solved
when i change my gpu mode its says "is being changed..." and while it changes the app wont respond to ui events so its stops responding when click on it again (and so it crashes)
when i wait to change mode its becomes responsive again and doesnt crash
![image](https://github.com/user-attachments/assets/ffa6a0a8-51f1-4cdf-89bb-005b0b6f973e)

**Comment by seerge** [comment]
@Sultan-papagani hello, that doesn’t look like a crash log. The crash log usually mentions specific lines of app code (with line numbers) related to it.

As for the UI getting unresponsive during GPU toggle - unfortunately this is how things are. When G-Helper runs command to asus interface yo do so - whole process is locked. I can’t change that :)

I assume it’s resolved for you then? Thanks

**Comment by Sultan-papagani** [comment]
yep its okay thanks 👍
