### ISSUE TITLE
Keyboard FN shortcuts + Temps on Tray

### ISSUE THREAD

**Issue by Par3aa** [seerge/g-helper#2896]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

being unable to change M4 on 5-button laptops

### Describe the solution you'd like

A few feature suggestions:
1. First thing that really bothered me in this awesome app,
my laptop's the Strix G713, it has 5 function keys, M5 being the ArmouryCrate button, M4 is straight up ommited in GHelper, used to use M4 to pause music and I miss it.
2. Being able to customize any Fn function would be awesome, like Fn+X launching some app, Fn+O pausing music etc.
3. showing temperatures as separate system tray icons, like small numbers as icons, CPU and GPU temps, maybe fan speed later on...

### Device and Model

G713RW

**Comment by seerge** [comment]
@Par3aa hello,

1. For M4 - this is a duplicate:) Fn+F5 and M4 emit same keycode, so it's impossible to separate them unfortunately
Check my answer here https://github.com/seerge/g-helper/issues/2157

2. Only few dedicated FN+ combinations emit keycodes (namely FN+C, FN+V), and app already covers all of them. It's not possible to add others as they don't produce any keycode at all.

3. G-Helper is not designed to be a hardcore system monitoring tool. There are a lot of other nice apps that have exactly that function and don't take much resources.  For example https://www.hwinfo.com/ :)

Thanks.
