### ISSUE TITLE
incorrect F2-F4 bindings on my G712LU (2020)

### ISSUE THREAD

**Issue by Anish-Sood** [seerge/g-helper#2897]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![Screenshot 2024-07-31 004805](https://github.com/user-attachments/assets/2f6c85b5-9c0d-4aef-bfbf-76add699556d)
![f](https://github.com/user-attachments/assets/aabe3483-8aba-4c7a-b260-920f1d2c5e47)

so according to my keyboard format:
these are bindings:
FN+F2 - prev
FN+F3 - pause
FN+F4 - next

so when i use g-helper's fn lock it should do the above things without fn, but without fn it does the following things:
F2 - backlit brightness down
F3 - backlit brightness up
F4 - backlit aura mode changes

### How to reproduce the bug?

...

### Logs

...

### Device and Model

Asus Rog Strix G17 G712LU (2020)

### Armoury Crate

Uninstalled

### Version

0.179

### OS

Win 11

**Comment by seerge** [comment]
@Anish-Sood hello, does your laptop support different backlight modes (i.e. "aura" modes) ? If so how do you switch between them via hotkeys ?

**Comment by seerge** [comment]
@Anish-Sood try this build it should run correct `FN+F2, FN+F3, FN+F4` actions for your device
[GHelper.zip](https://github.com/user-attachments/files/16479136/GHelper.zip)

**Comment by seerge** [comment]
@Anish-Sood changes included in https://github.com/seerge/g-helper/releases/tag/v0.182
