### ISSUE TITLE
GHelper do not startup automatically

### ISSUE THREAD

**Issue by TomBonnot** [seerge/g-helper#29]
My GHelper does not start up on log on. 
I have tried forcing it with another task in the task scheduler, but it doesn’t appear in the task Manager. I don’t know why. I have tried different triggers. Do you have any idea from where this come from ? 

And it still ask me for Administrator privileges !

**Comment by seerge** [comment]
Are you sure that you are using latest version ? 
https://github.com/seerge/g-helper/releases/tag/v0.9.4

It doesn't ask for admin privileges.

As for tasks, you can try to open Task scheduler and manually delete any task called GHelper :) and then launch app and click "run on startup" again.

**Comment by TomBonnot** [comment]
Yes I have the latest version and it still show this way : 
![image](https://user-images.githubusercontent.com/35734114/221258756-5d77a010-4f1f-40b5-b9e5-e297d12a0ecf.png)
if I quit GHelper and run it without Admin privilege, it pops and unpops instantly. 

Tho now I try to run it with privilege and it doesn’t show GPU temps. It is weird af.

**Comment by TomBonnot** [comment]
And it doesn’t show in the task manager !

**Comment by seerge** [comment]
It's definitely not the latest then. Delete and download again ?

**Comment by TomBonnot** [comment]
Ì did downloaded again and it’s the exact same thing ! Don’t know why

**Comment by seerge** [comment]
You are downloading this file and unpacking it in a fresh new folder https://github.com/seerge/g-helper/releases/download/v0.9.4/GHelper.zip right ?

**Comment by TomBonnot** [comment]
![image](https://user-images.githubusercontent.com/35734114/221361909-079b903f-c091-441f-abf6-0ef9423b5d55.png)
I have this last run result for the Task Scheduler, what does it could mean ? 

I am going to try new version you just deployed !

**Comment by TomBonnot** [comment]
![image](https://user-images.githubusercontent.com/35734114/221362357-77b917af-db13-45bf-9a2d-b74b7e904d27.png)
 This is what I found on the web, I seriously don't know why the hell it needs administrator privilege. 
 Do you think I should place GHelper elsewhere ?

**Comment by seerge** [comment]
Did you set admin permission by yourself somehow to exe ? like via compatibility settings or so ?
I would delete old task / old exe and run it fresh

**Comment by TomBonnot** [comment]
![image](https://user-images.githubusercontent.com/35734114/221363810-976d6a82-9c0c-4d6a-8fd4-df62ea538d3d.png)
Like this we agree ? 
Did it already, I don't know why from one time to another it doesn't want !

**Comment by seerge** [comment]
Again, you DON'T have to run app as administrator, neither you DON'T have to set any custom (and especially compatibility) settings for the app. It's not advised anywhere. 

If you mess up with windows settings for the app, then don't ask why it doesn't run.

**Comment by TomBonnot** [comment]
But doesn't "Run this app as administrator" gives it every right already ? 
I didn't know since I am not english I think this is a different way to say things than in my language, which seems normal to me. Then sorry. I didn't messed up, I thought it was the right was. My bad.

**Comment by TomBonnot** [comment]
And I did say this exact sentence "Run as an administrator" to a friend in our langage, and he thoughts THE SAME as me. So please, pardon me. I thought it was more serious than only that.
