### ISSUE TITLE
[Feature request] Ability to customize M1 and M2 buttons

### ISSUE THREAD

**Issue by Cessly** [seerge/g-helper#290]
It would be nice if g-helper had the option to customize the function of the M1 and M2 ROG keys, as it does currently with the M3 and M4 (and FN+F4). I would give them other uses more practical to me than turn up and down the volume, which I don't use very frequently.

Thank you for this useful program!

**Comment by seerge** [comment]
@Cessly hello, currently M1/M2 are being intercepted by Asus Optimization Service (that handles all "default" hotkeys), so app doesn't even get notification when this buttons are pressed. And since app relies on that service to work for all other hotkeys, i can't bind them internally anyhow :)
