### ISSUE TITLE
GHelper's start-up speed and charge limit

### ISSUE THREAD

**Issue by Pedrwm** [seerge/g-helper#2901]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Compared to MyASUS, G helper takes much longer to start up and apply the charge battery limit, so everytime I boot up my laptop, the limit gets exceeded by 1%. Is it possible to make the app's start up speed faster to prevent this?

### Describe the solution you'd like

Faster start-up

### Device and Model

ASUS TUF A15 2023 FA507NV

**Comment by seerge** [comment]
@Pedrwm hello, G-Helper also starts immediately as soon as you log in to windows.

Asus Optimization service starts before you log in, cause it’s a service, not an app. G-Helper can’t do that

Thanks
