### ISSUE TITLE
Remember color temperature when switching Gamut

### ISSUE THREAD

**Issue by masteryf** [seerge/g-helper#2902]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I would like to retain the color temperature upon switching between color gamuts

### Describe the solution you'd like

I would like to retain the color temperature upon switching between color gamuts, for instance, while utilizing the native gamut, my preferred color temperature is natural. Upon selecting SRGB, I aspire for the color temperature to be cooler. Currently, the process involves executing two separate actions. Could you revise the operational logic to assign a distinct color temperature to each specific gamut?

### Device and Model

ASUS Zepgyrus M16 GU603ZX

**Comment by seerge** [comment]
@masteryf hello, G-Helper (same as AC) runs AsusSplendid.exe utility from Asus System Control Interface package to set Gamuts and Color temperature (so it’s not handled by G-Helper itself)

Gamut and color temp is a separate commands for that utiliy.

As I remember special gamuts are not really intended to be altered with temps (so AsusSplendid intentionally resets temp every time you set new gamut)

How does it behave when you set those settings using AC?

**Comment by masteryf** [comment]
Thank you for your reply. When I use AC, the behavior of AC is the same as that of g-helper, but this is not convenient. I hope g-helper can automatically adjust the color temperature to the value set by the previous use of a certain gamut when switching to gamut

**Comment by seerge** [comment]
@masteryf are you sure that Color temperature doesn’t reset gamut to Native? (not in UI, but de-facto)? I just don’t have a device that would support Gamuts to verify

**Comment by masteryf** [comment]
Yes, at least on my device, gamut and color temperature are independent
You can try putting these files in the C: \ ProgramData \ ASUS \ GameVisual folder. If nothing unexpected happens, you can unlock the gamut switch function
[GameVisual.zip](https://github.com/user-attachments/files/16445719/GameVisual.zip)

**Comment by seerge** [comment]
@masteryf Color temperature is not a separate color profile, it’s just an adjustment on the level of GPU driver.

Can you set sRGB gamut (for example), then change color temp to something and then open windows Color Management app and check if sRGB ICM profile is still selected there as active?

**Comment by seerge** [comment]
@masteryf hello, ok, good to know. 

Color temperature is linked together with Visual Modes / Game visual (it's being set together in one single command for AsusSplendid.exe). So if you want to change color temperature after setting gamut - visual mode will be set as well in any case.

Does Armoury Crate allow you to change Game Visual / Color Temp when you use custom gamuts ?

**Comment by masteryf** [comment]
I didn't perceive any correlation between color gamut and color temperature. They operate independently, meaning I can employ any color temperature within any color gamut. Although, it is worth noting that toggling the color gamut does reset the color temperature to its default setting. Consequently, I have to manually adjust the color temperature every time I change the color gamut.

**Comment by seerge** [comment]
@masteryf so does AC allow to set color temp / game visual for custom gamuts, like sRGB ?

**Comment by masteryf** [comment]
of course

**Comment by seerge** [comment]
@masteryf ok, try this build.

It should set Visual mode + color temp (as they are paired) after setting gamut each time
[GHelper.zip](https://github.com/user-attachments/files/16479141/GHelper.zip)

But I'm not sure if it should be default behavior tho ...

**Comment by masteryf** [comment]
https://github.com/user-attachments/assets/c8302f1f-77ad-4e78-ad72-8434610fb1aa

It doesn't seem to work. What I want is to use neutral color temperature when switching to native color gamut and colder color temperature when using SRGB. I hope the g-helper can remember my choice when switching color gamut

**Comment by seerge** [comment]
@masteryf ah, I have misunderstood you then. I was thinking you want to re-apply last used color temp to a new gamut.

As for your usecase - I'm just afraid it's too specific, and it would rather confuse people and create more issues than it would solve

**Comment by masteryf** [comment]
You're right, my requirement is actually more like needing a preset to bind color gamut and color temperature to a certain preset. Directly associating color gamut and color temperature is indeed more likely to cause confusion

**Comment by seerge** [comment]
@masteryf i see. 

Honestly your use case is quite exotic, and if app would remember / change color temps every time this would raise more questions from regular users than solve a problem :)

So, I don't see point in changing the way everything works currently. Especially considering that AC behaves same.

Therefore closing as not planned. Sorry.

Thanks
