### ISSUE TITLE
Additional date formats, fonts and options for the AniMe Matrix clock

### ISSUE THREAD

**Issue by zaubertee** [seerge/g-helper#2903]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

As of right now the clock option in G-Helper shows the time and the date in the YY.MM.DD format. As a european the date format is pretty confusing because the norm is DD.MM.YY. Also, i would love an option to only show the time without the date with a little more space (because the font blends some digits together right now, causing worse readablilty).

### Describe the solution you'd like

So all together:
- European date formats
- Only show date / time
- Possibility to switch fonts
- Only show day and month, without year

### Device and Model

Asus Zephyrus G14 2023

**Comment by seerge** [comment]
@zaubertee hello, 

Actually app already uses local windows time settings and shows either 24 or 12
hour format.

I can add an optional param in config where you could define date format, would that be enough?

As for fonts - i’m not a big fan of making that changeable as each font is different in rendering and positioning, and most likely it simply won’t fit into current (already very limited by resolution) matrix. As literally adjusted current matrix font labels pixel by pixel…

**Comment by zaubertee** [comment]
Hi!
Good to know, i'll check my settings.
And sure, setting the date format would be excellent - or just an option to just use the time would be also perfect. :)

**Comment by seerge** [comment]
@zaubertee ok, this build should allow 2 config parameters for custom time and date formats

[GHelper.zip](https://github.com/user-attachments/files/16479066/GHelper.zip)

Quit app, add following lines to the beginning of `%appdata%\GHelper\config.json` 

```
"matrix_time" : "HH:mm",
"matrix_date" : "yy.MM.dd",
```

Save it and run app again.

It uses standard C# date and time formatting, so you can customize it to your needs
https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

**Comment by seerge** [comment]
@zaubertee changes included in https://github.com/seerge/g-helper/releases/tag/v0.182
