### ISSUE TITLE
Could you add a feature to allow users to disable LED lighting changes made by G-Helper?

### ISSUE THREAD

**Issue by Robert-W-K** [seerge/g-helper#2904]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I use a different LED color setting tool called OpenRGB which gives me many more options. G-Helper supersedes the settings that OpenRGB automatically sets for me based on my profile choices.

### Describe the solution you'd like

I'd like a flag to allow users to allow or disable G-Helper to set the LED color schemes altogether (all or nothing.)

### Device and Model

ASUS ROG Strix G15 Advantage (G513QY)

**Comment by seerge** [comment]
@Robert-W-K there is such option already 
https://github.com/seerge/g-helper/wiki/Power-user-settings#skip-keyboard-aura-initialisation-on-startup
