### ISSUE TITLE
Changing Microphone Key input in G-Helper still turns microphone on and off, press and hold seemingly not allowed?

### ISSUE THREAD

**Issue by Robert-W-K** [seerge/g-helper#2905]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I am trying to set the microphone key (M3) to be a push-to-talk solution by being the same as a current button chord I use as dictated by https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes, but holding down the M3 key does not work as expected. 

Is this a G-Helper issue?

### How to reproduce the bug?

1. Set M3 key to be two keys at once through operation code in G-Helper
2. Microphone and keystroke action happens simultaneously

### Logs

No log information?

### Device and Model

ASUS ROG Strix G15 Advantage (G513QY)

### Armoury Crate

Never installed

### Asus Services

6

### Version

0.179.0

### OS

Windows 10 Pro 22H2

**Comment by seerge** [comment]
@Robert-W-K hello, most likely you have Asus Optimization service running that mutes microphone. You need to stop it from “Extra” settings. 

>  I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

But since you have ignored issue template and did not provide any logs I can’t verify that and assist you further.
