### ISSUE TITLE
Limiting processor speed by mode

### ISSUE THREAD

**Issue by mariovojnichajduk** [seerge/g-helper#2906]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Right now, every change that I make inside G Helper is done over Balanced profile in Windows power plans and I am missing the processor speed limit because I want to have different limit of speed on Silent and Turbo modes. 

### Describe the solution you'd like

Since I want to limit not only wattage but also speed of the processor, it would be good to have that option in application. 

### Device and Model

Zephyrus GA402RK

**Comment by LeoRH123** [comment]
Maybe this solves the behavior you want to achieve, it's on the wiki page, but you have to edit the `config.json` file
[Custom windows power plans with each mode](https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-windows-power-plans-with-each-mode).

**Comment by mariovojnichajduk** [comment]
I had to edit my comment since I didn't explain best.. I don't have problem with manually connecting modes to power profiles, however limiting cpu speed would be good option inside of the application (especially for those who don't want to go through config files)

**Comment by seerge** [comment]
@mariovojnichajduk hello,

I was answering this already https://github.com/seerge/g-helper/discussions/2343

You indeed can try to set clock limits in power plan, but I don’t want to add it to the app cause it’s just too exotic and in addition it simply doesn’t work on lots of devices at all . While people will just accuse G-Helper in not working as usual then.

So it’s out of scope atm. Thanks.
