### ISSUE TITLE
Setting m3 to play/pause often does not work.

### ISSUE THREAD

**Issue by reckthaworlde** [seerge/g-helper#2909]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When setting the m3 key to play/pause in the extras settings of ghelper, I find that it only works sometimes, and usually only with ghelper open. However, all the other options to set it to work correctly.

### How to reproduce the bug?

Set m3 to play/pause. Close ghelper. Click m3. 

For it to work correctly, reopen ghelper and try again. This only works sometimes.

### Logs

[log.txt](https://github.com/user-attachments/files/16459537/log.txt)

### Device and Model

Asus  Zephyrus g16 2024 gu605mz

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.179.0

### OS

Windows Home 23h2

**Comment by seerge** [comment]
@reckthaworlde hello, can you define “sometimes”? G-Helper has to be running in order to process hotkeys (at least stay in system tray)

I see in the log, that when it gets notified about M3 press it emits PlayPause media key via windows api

Do you have Asus services running? As they might interfere

**Comment by seerge** [comment]
@reckthaworlde any updates here ?

**Comment by seerge** [comment]
Due to lack of response closed as abandoned
