### ISSUE TITLE
Asus Services Running List / More Details

### ISSUE THREAD

**Issue by justincpresley** [seerge/g-helper#2910]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

GHelper does a great job at finding ASUS-related Services running in the background of the system and providing a one click button to stop them. However, it is not transparent what those running services are nor does it provide fine-grain termination.

### Describe the solution you'd like

I would like a grey-ed out button labeled "Details" besides the Start/Stop button. If services are found, the button turns into a normal button / turns clickable. Once clicked, it opens a separate window listing the services you do have running. Besides each service running, you have a button to stop that particular service.

You could also have this Details button always active and just list all services in general, but this could be cumbersome and clutter the UI. It could also look like the "Updates" window with red/green highlights.

### Describe alternatives you've considered

I am able to find these services myself and terminate them myself being a technical user. However, I do not know of an alternative for a non-technical user.

### Device and Model

ASUS Zephyrus G14 GA403UI

**Comment by seerge** [comment]
@justincpresley hello,

I'm not Asus so I can't speak for what each of the services do. Only Asus Optimization service is handling hotkeys (but G-Helper can do that as well of course), and sets charge limiter on laptop start.  Rest are needed for MyASUS to work.

General suggestion is to keep services ON if you use MyASUS, and turn OFF if you don't.
https://github.com/seerge/g-helper/wiki/Requirements#recommendations-optional

I don't see much sense in writing some explanations, and letting people to stop things one by one. It will raise more problems and questions than it would solve.

Whole Start / Stop button is just migrated https://github.com/seerge/g-helper/blob/main/docs/debloat.bat into the app itself :)

So I don't plan to change that. Sorry. Thanks.
