### ISSUE TITLE
Windows, Shift and Ctrl lower volume

### ISSUE THREAD

**Issue by reedwhaley** [seerge/g-helper#2911]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I believe this is being caused from my M1-4 keys malfunctioning but I can't tell for certain. I have those set to custom with no input attached to "disable" them but now the Windows, Ctrl and Shift keys are lowering the volume. I have added the "skip_hotkeys":1, to the config file with no success.

### How to reproduce the bug?

Start GHelper
Press Shift, Windows or Ctrl

### Logs

[log.txt](https://github.com/user-attachments/files/16463745/log.txt)

### Device and Model

Asus TUF Dash F15 FX517ZR

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.179.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@reedwhaley hello, 

G-Helper is not handling those keys. Easiest way to verify - is to quit app and check if it still happens.

If your keyboard is malfunctioning by some unknown reasons you can try 
https://github.com/seerge/g-helper/wiki/Troubleshooting#hardware-reset--cmos-reset
