### ISSUE TITLE
The brightness flicker adjustment button causes the brightness of the external monitor to change.

### ISSUE THREAD

**Issue by KamenWong** [seerge/g-helper#2913]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I connect an external monitor to the ROG Zephyrus G14 GA403UV and adjust the low brightness anti-flicker setting, the brightness of the monitor changes as well. This didn't happen in previous versions.

### How to reproduce the bug?

1. GHelper version 0.179  
2. Connected an external monitor via the DP interface and selected "Second screen only"  
3. Adjusted the brightness anti-flicker adjustment button

### Logs

None

### Device and Model

ROG Zephyrus G14 GA403UV

### Armoury Crate

Never installed

### Asus Services

None

### Version

0.179

### OS

windows 11 23h2

**Comment by seerge** [comment]
@KamenWong hello, G-Helper is not adjusting dimming by itself, it only launches asus utility to do that. So there is no way to specify what display should be dimmed there :)

In what version did it work, can you check it again?

**Comment by seerge** [comment]
@KamenWong 

> In what version did it work, can you check it again? 

Any updates here ?

**Comment by KamenWong** [comment]
I resolved it after reinstalling the system.
