### ISSUE TITLE
Allow macro keys to map to 4-key hotkeys

### ISSUE THREAD

**Issue by phu54321** [seerge/g-helper#2916]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

G-helper provides several 4-key hotkeys. Specifically, 

```
Ctrl + Shift + Alt + F13 - Toggle Display Refresh Rate
Ctrl + Shift + Alt + F14 - Eco GPU Mode
Ctrl + Shift + Alt + F15 - Standard GPU Mode
Ctrl + Shift + Alt + F16 - Silent
Ctrl + Shift + Alt + F17 - Balanced
Ctrl + Shift + Alt + F18 - Turbo
Ctrl + Shift + Alt + F19 - Custom 1 (if exists)
Ctrl + Shift + Alt + F20 - Custom 2 (if exists)
```

Some of the options are not settable via G-helper's macro key settings. Specifically I want to set M3 key to `Toggle Display Refresh Rate`.

![image](https://github.com/user-attachments/assets/c9411a9e-4096-4bf6-bc26-e9fea297e007)

I tried to set M3 key to trigger `0x11 0xA2 0x12 0x7C`, but it doesn't work, as G-helper only supports up to 3-key hotkeys only.

https://github.com/seerge/g-helper/blob/f5964b60c7e208fae006c48c30205504c5e43d36/app/Input/InputDispatcher.cs#L219

### Describe the solution you'd like

- Make `KeyKeyKeyKeyPress` function and allow 4-key combination hotkeys.

### Describe alternatives you've considered

- Another solution would be just adding refresh change option to macro list, but I guess making 4-key presser would be much better as many other applications also use 4-key combos, and I haven't really heard of applications requiring 4-key hotkeys.

### Device and Model

ASUS Flow X16, GV601RM

### Additional information.

I could PR if requested

**Comment by seerge** [comment]
@phu54321 hello, try this build

[GHelper.zip](https://github.com/user-attachments/files/16479079/GHelper.zip)

**Comment by phu54321** [comment]
Confirmed! It works with `0xA0 0xA2 0xA4 0x7C` keystroke.
