### ISSUE TITLE
Unhandled execption 

### ISSUE THREAD

**Issue by FdbH75v1988DNAzW3miv1** [seerge/g-helper#2917]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Doesn't launch on startup, running as admin has different settings than just a regular run

### How to reproduce the bug?

No idea, happend when I updated it

### Logs

8/3/2024 1:27:24 AM: ------------
8/3/2024 1:27:24 AM: App launched: ROG Zephyrus G14 GA403UV_GA403UV :0.181.0.0en-US
8/3/2024 1:27:24 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#7&97b63eb&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
8/3/2024 1:27:24 AM: C:\ProgramData\ASUS\GameVisual doesn't exit
8/3/2024 1:27:24 AM: NVIDIA GeForce RTX 4060 Laptop GPU
8/3/2024 1:27:25 AM: CPU: 12 - AMD Ryzen 9 8945HS w/ Radeon 780M Graphics - AMD64 Family 25 Model 117 Stepping 2
8/3/2024 1:27:25 AM: AutoSetting for Online
8/3/2024 1:27:25 AM: Input available: \\?\hid#vid_0b05&pid_19b6&col05#7&2a3ab815&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 63
8/3/2024 1:27:25 AM: USB 19B6|63: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
8/3/2024 1:27:25 AM: Input: \\?\hid#vid_0b05&pid_19b6&col05#7&2a3ab815&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
8/3/2024 1:27:25 AM: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 00000000-0000-0000-0000-000000000000:OK
8/3/2024 1:27:25 AM: Eco flag : 0
8/3/2024 1:27:25 AM: Mux flag : 0
8/3/2024 1:27:25 AM: \\?\DISPLAY#SDC419C#5&e66c370&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
8/3/2024 1:27:25 AM: \\?\DISPLAY#SDC419C#5&e66c370&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
8/3/2024 1:27:25 AM: ATNA40CU05-0  HDR: False 8 1 False
8/3/2024 1:27:25 AM: Mode = 0 : OK
8/3/2024 1:27:25 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#7&97b63eb&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
8/3/2024 1:27:25 AM: Init 19B6: 5D-B9
8/3/2024 1:27:25 AM: SlashEnable False:5E-D8-02-00-01-80-00-00-00-00-00-00-00-00-00-00-
8/3/2024 1:27:25 AM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
8/3/2024 1:27:25 AM: SleepInit:5E-D2-02-01-08-A1-00-00-00-00-00-00-00-00-00-00-
8/3/2024 1:27:25 AM: Init 19B6: 5D-05-20-31-00-1A
8/3/2024 1:27:25 AM: Sleep False:5E-D3-03-01-08-A1-00-FF-00-02-FF-FF-00-00-00-00-
8/3/2024 1:27:25 AM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
8/3/2024 1:27:25 AM: AuraMode: AuraStatic
8/3/2024 1:27:25 AM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
8/3/2024 1:27:25 AM: USB 19B6: 5D-B5-00-00-00
8/3/2024 1:27:25 AM: USB 19B6: 5D-B4
8/3/2024 1:27:25 AM: ATNA40CU05-0  HDR: False 8 1 False
8/3/2024 1:27:26 AM: Monitor Power On
8/3/2024 1:27:26 AM: Lid Open
8/3/2024 1:27:26 AM: DisableLidClose True:5E-D8-00-00-02-A5-80-00-00-00-00-00-00-00-00-00-
8/3/2024 1:27:26 AM: ATNA40CU05-0  HDR: False 8 1 False
8/3/2024 1:27:26 AM: Auto 19B6|63: 5A-BA-C5-C4-01
8/3/2024 1:27:27 AM: Latest version 0.181.0.0
8/3/2024 1:27:30 AM: BatteryLimit = 100 : OK
8/3/2024 1:27:31 AM: BatteryLimit = 100 : OK
8/3/2024 1:27:32 AM: BatteryLimit = 80 : OK
8/3/2024 1:30:23 AM: ------------
8/3/2024 1:30:23 AM: App launched: ROG Zephyrus G14 GA403UV_GA403UV :0.181.0.0en-US
8/3/2024 1:30:24 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#7&97b63eb&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
8/3/2024 1:30:24 AM: C:\ProgramData\ASUS\GameVisual doesn't exit
8/3/2024 1:30:24 AM: NVIDIA GeForce RTX 4060 Laptop GPU
8/3/2024 1:30:25 AM: CPU: 12 - AMD Ryzen 9 8945HS w/ Radeon 780M Graphics - AMD64 Family 25 Model 117 Stepping 2
8/3/2024 1:30:25 AM: AutoSetting for Online
8/3/2024 1:30:25 AM: BatteryLimit = 80 : OK
8/3/2024 1:30:25 AM: Input available: \\?\hid#vid_0b05&pid_19b6&col05#7&2a3ab815&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 63
8/3/2024 1:30:25 AM: USB 19B6|63: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
8/3/2024 1:30:25 AM: Input: \\?\hid#vid_0b05&pid_19b6&col05#7&2a3ab815&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
8/3/2024 1:30:25 AM: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 00000000-0000-0000-0000-000000000000:OK
8/3/2024 1:30:25 AM: Eco flag : 0
8/3/2024 1:30:25 AM: Mux flag : 0
8/3/2024 1:30:25 AM: \\?\DISPLAY#SDC419C#5&e66c370&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
8/3/2024 1:30:25 AM: \\?\DISPLAY#SDC419C#5&e66c370&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
8/3/2024 1:30:25 AM: ATNA40CU05-0  HDR: False 8 1 False
8/3/2024 1:30:25 AM: Mode = 0 : OK
8/3/2024 1:30:25 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#7&97b63eb&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
8/3/2024 1:30:25 AM: Init 19B6: 5D-B9
8/3/2024 1:30:25 AM: SlashEnable False:5E-D8-02-00-01-80-00-00-00-00-00-00-00-00-00-00-
8/3/2024 1:30:25 AM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
8/3/2024 1:30:25 AM: SleepInit:5E-D2-02-01-08-A1-00-00-00-00-00-00-00-00-00-00-
8/3/2024 1:30:25 AM: Init 19B6: 5D-05-20-31-00-1A
8/3/2024 1:30:25 AM: Sleep False:5E-D3-03-01-08-A1-00-FF-00-02-FF-FF-00-00-00-00-
8/3/2024 1:30:25 AM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
8/3/2024 1:30:25 AM: AuraMode: AuraStatic
8/3/2024 1:30:25 AM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
8/3/2024 1:30:25 AM: USB 19B6: 5D-B5-00-00-00
8/3/2024 1:30:25 AM: USB 19B6: 5D-B4
8/3/2024 1:30:25 AM: Monitor Power On
8/3/2024 1:30:25 AM: BatteryLimit = 80 : OK
8/3/2024 1:30:25 AM: Lid Open
8/3/2024 1:30:25 AM: Lid 19B6|63: 5A-BA-C5-C4-01
8/3/2024 1:30:25 AM: DisableLidClose True:5E-D8-00-00-02-A5-80-00-00-00-00-00-00-00-00-00-
8/3/2024 1:30:26 AM: Auto 19B6|63: 5A-BA-C5-C4-01
8/3/2024 1:30:27 AM: ATNA40CU05-0  HDR: False 8 1 False
8/3/2024 1:30:28 AM: Latest version 0.181.0.0
8/3/2024 1:31:21 AM: ------------
8/3/2024 1:31:21 AM: App launched: ROG Zephyrus G14 GA403UV_GA403UV :0.181.0.0en-US
8/3/2024 1:31:22 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#7&97b63eb&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
8/3/2024 1:31:22 AM: C:\ProgramData\ASUS\GameVisual doesn't exit
8/3/2024 1:31:22 AM: NVIDIA GeForce RTX 4060 Laptop GPU
8/3/2024 1:31:23 AM: CPU: 12 - AMD Ryzen 9 8945HS w/ Radeon 780M Graphics - AMD64 Family 25 Model 117 Stepping 2
8/3/2024 1:31:23 AM: AutoSetting for Online
8/3/2024 1:31:23 AM: BatteryLimit = 80 : OK
8/3/2024 1:31:23 AM: Optimization service is running
8/3/2024 1:31:23 AM: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 00000000-0000-0000-0000-000000000000:OK
8/3/2024 1:31:23 AM: Eco flag : 0
8/3/2024 1:31:23 AM: Mux flag : 0
8/3/2024 1:31:23 AM: \\?\DISPLAY#SDC419C#5&e66c370&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
8/3/2024 1:31:23 AM: \\?\DISPLAY#SDC419C#5&e66c370&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
8/3/2024 1:31:23 AM: ATNA40CU05-0  HDR: False 8 1 False
8/3/2024 1:31:23 AM: Mode = 0 : OK
8/3/2024 1:31:23 AM: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#7&97b63eb&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
8/3/2024 1:31:23 AM: SlashEnable False:5E-D8-02-00-01-80-00-00-00-00-00-00-00-00-00-00-
8/3/2024 1:31:23 AM: SleepInit:5E-D2-02-01-08-A1-00-00-00-00-00-00-00-00-00-00-
8/3/2024 1:31:23 AM: Init 19B6: 5D-B9
8/3/2024 1:31:23 AM: Sleep False:5E-D3-03-01-08-A1-00-FF-00-02-FF-FF-00-00-00-00-
8/3/2024 1:31:23 AM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
8/3/2024 1:31:23 AM: Init 19B6: 5D-05-20-31-00-1A
8/3/2024 1:31:23 AM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
8/3/2024 1:31:23 AM: AuraMode: AuraStatic
8/3/2024 1:31:23 AM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
8/3/2024 1:31:23 AM: USB 19B6: 5D-B5-00-00-00
8/3/2024 1:31:23 AM: USB 19B6: 5D-B4
8/3/2024 1:31:23 AM: Monitor Power On
8/3/2024 1:31:23 AM: BatteryLimit = 80 : OK
8/3/2024 1:31:23 AM: Lid Open
8/3/2024 1:31:23 AM: Lid 19B6|63: 5A-BA-C5-C4-01
8/3/2024 1:31:23 AM: DisableLidClose True:5E-D8-00-00-02-A5-80-00-00-00-00-00-00-00-00-00-
8/3/2024 1:31:24 AM: ATNA40CU05-0  HDR: False 8 1 False
8/3/2024 1:31:24 AM: Auto 19B6|63: 5A-BA-C5-C4-01
8/3/2024 1:31:25 AM: Latest version 0.181.0.0
8/3/2024 1:31:26 AM: Power Mode 00000000-0000-0000-0000-000000000000 -> ded574b5-45a0-4f42-8737-46345c09c238:OK
8/3/2024 1:31:26 AM: Mode = 1 : OK
8/3/2024 1:31:27 AM: GET GPU CLOCKS: 0, 0
8/3/2024 1:31:27 AM: GET CLOCK LIMIT: 0
8/3/2024 1:31:27 AM: ReadGPUPowerBase: 55
8/3/2024 1:31:27 AM: ReadGPUPower (1): 80
8/3/2024 1:31:30 AM: BatteryLimit = 60 : OK

### Device and Model

ROG Zephyrus G14 GA403UV

### Additional information.

![image](https://github.com/user-attachments/assets/3c77a8de-cc61-474c-9733-e6276bc6d1df)

### Armoury Crate

Never installed

### Asus Services

None

### Version

0.181.0

### OS

Windows 10 21h2

**Comment by seerge** [comment]
@FdbH75v1988DNAzW3miv1 hello, can you post full contents of exception window here ?

**Comment by seerge** [comment]
@FdbH75v1988DNAzW3miv1 from the (very limited) visible info on your screenshot, your exception happens when you click on a version label that is supposed to open browser with github releases page. It happens on the system level, so i can assume that something is broken on windows / .net there in your system and you should look into that by yourself (like do you have users with some exotic permissions ?)

But try this build, it should suppress exception at least

[GHelper.zip](https://github.com/user-attachments/files/16478969/GHelper.zip)

**Comment by FdbH75v1988DNAzW3miv1** [comment]
> @FdbH75v1988DNAzW3miv1 hello, can you post full contents of exception window here ?

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x800401F5): An error occurred trying to start process 'http://github.com/seerge/g-helper/releases' with working directory 'C:\WINDOWS\system32'. Application not found
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GHelper.AutoUpdate.AutoUpdateControl.LoadReleases() in D:\a\g-helper\g-helper\app\AutoUpdate\AutoUpdateControl.cs:line 39
   at GHelper.SettingsForm.LabelVersion_Click(Object sender, EventArgs e) in D:\a\g-helper\g-helper\app\Settings.cs:line 811
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Private.CoreLib.dll
----------------------------------------
GHelper
    Assembly Version: 0.181.0.0
    Location: 
----------------------------------------
System.Runtime
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\System.Windows.Forms.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Threading.Thread.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\System.Windows.Forms.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Collections.Specialized.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Diagnostics.Process.dll
----------------------------------------
System.Collections
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Collections.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Text.Json
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Text.Json.dll
----------------------------------------
System.Threading
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Threading.dll
----------------------------------------
System.Memory
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Memory.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Text.Encoding.Extensions.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Runtime.Intrinsics.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Numerics.Vectors.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Private.Uri.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Collections.Concurrent.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Runtime.InteropServices.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\Microsoft.Win32.Primitives.dll
----------------------------------------
System.Management
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\Microsoft.Win32.Registry.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Security.Claims.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Diagnostics.TraceSource.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\System.Drawing.dll
----------------------------------------
NAudio.Wasapi
    Assembly Version: 2.1.0.0
    Location: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\Accessibility.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.ComponentModel.dll
----------------------------------------
WinForms.DataVisualization
    Assembly Version: 1.0.0.0
    Location: 
----------------------------------------
WinForms.DataVisualization.Utilities
    Assembly Version: 1.0.0.0
    Location: 
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\netstandard.dll
----------------------------------------
HidSharpCore
    Assembly Version: 2.1.0.0
    Location: 
----------------------------------------
System.Linq
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Linq.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Threading.ThreadPool.dll
----------------------------------------
Microsoft.Win32.TaskScheduler
    Assembly Version: 2.10.1.0
    Location: 
----------------------------------------
System.ObjectModel
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.ObjectModel.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Text.RegularExpressions.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Private.Xml.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Runtime.Loader.dll
----------------------------------------
NvAPIWrapper
    Assembly Version: 0.8.1.100
    Location: 
----------------------------------------
System.Diagnostics.PerformanceCounter
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\System.Diagnostics.PerformanceCounter.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Threading.Overlapped.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Collections.NonGeneric.dll
----------------------------------------
System.Net.Http
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Net.Security.dll
----------------------------------------
System.Security.Cryptography
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Security.Cryptography.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Net.Sockets.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Net.NameResolution.dll
----------------------------------------
System.Data.Common
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Data.Common.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Collections.Immutable.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.IO.Compression.dll
----------------------------------------

************** JIT Debugging **************

**Comment by seerge** [comment]
@FdbH75v1988DNAzW3miv1 exception happens when you clicked on Version label and app tried to open github url using default browser, due to some strange system restrictions on your side outside of app's control.

It says you are running app from `C:\WINDOWS\system32` directory ? Try to put exe in some standard folder, not in the `system32` :) That's probably a reason it doesn't run on startup as well.

Build I linked above will suppress this exception, but obviously github won't open from it still.

Thanks

**Comment by FdbH75v1988DNAzW3miv1** [comment]
> @FdbH75v1988DNAzW3miv1 exception happens when you clicked on Version label and app tried to open github url using default browser, due to some strange system restrictions on your side outside of app's control.
> 
> It says you are running app from `C:\WINDOWS\system32` directory ? Try to put exe in some standard folder, not in the `system32` :) That's probably a reason it doesn't run on startup as well.
> 
> Build I linked above will suppress this exception, but obviously github won't open from it still.
> 
> Thanks

Its running in a folder in documents, I have two accounts on my machine admin and my personal account, anything i run as admin requires me to enter my admin password then it runs it

**Comment by seerge** [comment]
@FdbH75v1988DNAzW3miv1 when you are scheduling app to run on startup you need to do it from your main account. As otherwise windows Task Scheduler simply won't run it .
