### ISSUE TITLE
The app does not control the fans correctly.

### ISSUE THREAD

**Issue by skwaruch** [seerge/g-helper#2921]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

They should turn on above 70 and the CPU fan works even below 60. The fans turn on above 70 by default.

You can't turn on two fans from the CPU temp, that's also standard.

![obraz](https://github.com/user-attachments/assets/8d303552-2ff7-4802-b294-3773b29a2d6b)

### How to reproduce the bug?

Everything is in the picture.

### Logs

[log.txt](https://github.com/user-attachments/files/16486750/log.txt)

### Device and Model

asus tuf F17 FX707ZR

### Armoury Crate

Never installed

### Version

0.181.0

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@skwaruch hello, G-Helper is not controlling your fans directly, [BIOS does.](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds), even when you use a custom fan curve.  Please make yourself familiar with FAQ.

If you don't like how BIOS controls fans on your device, you can try [Experimental build with a manual fan control.](https://github.com/seerge/g-helper/discussions/2272)

Thanks.

**Comment by skwaruch** [comment]
> @skwaruch hello, G-Helper is not controlling your fans directly, [BIOS does.](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds), even when you use a custom fan curve BIOS may override it when it decides so. Please make yourself familiar with FAQ.
> 
> If you don't like how BIOS controls fans on your device, you can try [Experimental build with a manual fan control.](https://github.com/seerge/g-helper/discussions/2272)
> 
> Thanks.

Thank you very much, it works!

I am very sorry for opening issue.
