### ISSUE TITLE
Mute and Unmute UI not working when pressing M3 on keyboard (Asus Zephyrus G14)

### ISSUE THREAD

**Issue by CodingGenius0001** [seerge/g-helper#2926]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

This UI does not show up when I am pressing the M3 button on the keyboard

### How to reproduce the bug?

Press M3 on keyboard on boot

### Logs

[log.txt](https://github.com/user-attachments/files/16489711/log.txt

### Device and Model

Asus Zephyrus G14 2024 GA403UI

### Additional information.

![image](https://github.com/user-attachments/assets/858dd7f3-5435-4683-9057-6f712e60391d)
This UI does not show up when I am pressing the M3 button on the keyboard

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.181.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@CodingGenius0001 hello, you have Asus services running and they handle hotkeys. You need to stop them via `Extra`, then G-Helper would take over.

[Please make yourself familiar with FAQ.](https://github.com/seerge/g-helper/wiki/FAQ#how-do-i-set-mute-microphone-to-m3)

```
05-08-2024 7:15:52 AM: Optimization service is running
```
