### ISSUE TITLE
Asus Tuf Laptop will detect it's still in sleep mode while using it

### ISSUE THREAD

**Issue by soundwaves7** [seerge/g-helper#293]
When my laptop hibernates and then I use it again the keyboard and power keep flashing as if the laptop is in sleep mode, the fans won't work on any mode even on turbo a restart fixes it but I couldn't figure out a way to fix it without a restart

The steps are exactly as follows:
1- close the laptop lid (put it to sleep)
2- sometimes I remove the power while laptop is sleeping.
3- after some time, the laptop hibernates.
4- wake the laptop again.
5- laptop is in sleep mode while I am working on it.

Logs: 
[log.txt](https://github.com/seerge/g-helper/files/11339307/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: ASUS TUF Gaming F17 FX706HE

**Asus software**
- MyASUS installed
- Other Asus services running in background

**Comment by seerge** [comment]
@soundwaves7 hello, what is "power" that keeps flashing? is it led lamp? if so - app doesn't control that in a first place.
As for keyboard settings - you can disable flashing completely under 'Extra' -> 'Sleep' checkbox. Will that stop flashing?

But what you explain in general, seems like your bios still thinks that laptop is sleeping so it keeps keyboard / power led in sleeping animation. App doesn't apply this setting when laptop wakes up / or goes to sleep, your hardware does :|

**Comment by soundwaves7** [comment]
@seerge Yes I meant the power Led, I just started using G-helper a few days ago, i didn't encounter this issue before so i thought it might be related, do you know if there might be something missing that might contribute to this issue since i uninstalled armoury crate so i can reinstall the driver responsible

**Comment by seerge** [comment]
Does checking / unchecking Sleep flag under Keyboard Extra stop flashing (immediately?) if so - i can try to add a "workaround" in an app so it will re-apply this setting on wake up.

Otherwise - i'm afraid it's something app doesn't contol

**Comment by soundwaves7** [comment]
here is a video of what happens, also i discovered the laptop doesn't need to hibernate just putting it to sleep and back awake does the same

https://user-images.githubusercontent.com/25686789/234793122-cc785ceb-961a-401a-b922-7e08a4e059ca.mp4

**Comment by seerge** [comment]
@soundwaves7 ok, but unchecking / checking sleep flag ‘fixes’ it from what i see in video?

**Comment by soundwaves7** [comment]
No it just turns off the keyboard light, the laptop is still in sleep mode

**Comment by seerge** [comment]
@soundwaves7 ah, then looks like your laptop hardware still thinks it's sleeping. I can't do much here, cause app doesn't control that.

The only thing I can suggest - is to turn off "Sleep" animation completely , if it annoys you :)

**Comment by soundwaves7** [comment]
I probably will hold off on using it for now, since the issue is the fans are not working while the laptop is in that state not just the animation issue, one thing that might help I am trying another app and it's working fine, one setting that i think is related to that is this. 
hope this helps
![image](https://user-images.githubusercontent.com/25686789/234801494-bbfceeb2-8169-476f-886e-fbd0f11d88ff.png)

**Comment by seerge** [comment]
What does this setting do ? and where is that ? :)

**Comment by soundwaves7** [comment]
this is another app called Armoury control, i am not sure what the setting actually does, but it fixes the issue when checked, 
i tested using only that app  with the setting checked and then tested with G-helper 
and same result with G-helper the laptop thinks it's in sleep mode while awake

**Comment by seerge** [comment]
That app literally has g-helper code (related to managing hardware) copy-pasted under the hood :)

As for that specific setting, the only thing it does - is disables bunch of own windows services when going to sleep (probably to try to fix buggeed windows sleep?)
``
// Disable Windows Update and Microsoft Store Service
DisableServices("UpdateOrchestrator", "wuauserv", "InstallService", "WaaSMedicSvc", "UsoSvc");
```

You can also try to disable wake-up timers in your power plan for similar effect
![Screenshot 2023-04-27 103006](https://user-images.githubusercontent.com/5920850/234805600-68381324-13b6-4353-9fa2-ff434e9d7d58.png)

**Comment by soundwaves7** [comment]
i tried everything and still can't solve this, thanks for your help.

**Comment by seerge** [comment]
@soundwaves7 just in case you can run this bat file to stop  that windows services (i wonder if it indeed helps your laptop to sleep properly?) it should be run as administartor. 

+ there is a bat file to start them again (just in case)

[stop-winservices.zip](https://github.com/seerge/g-helper/files/11341569/stop-winservices.zip)

**Comment by soundwaves7** [comment]
@seerge problem solved by installing armoury crate again, it must be something like a driver or service controlling how the laptop wakes up or something

**Comment by soundwaves7** [comment]
I wanted to share an update about this issue, so that if anyone else faces the same problem.
the issue started happening again after installing Armoury Crate, after a lot of testing and investigation I found the source of the issue, it was the latest bios update from windows (& Asus) after visiting Asus drivers website for my laptop I found out that they removed that bios version so I re-flashed the older bios that I downloaded from Asus's website (now it's the latest one) and everything is working great now. be careful because windows still push the faulty bios version, I already talked with Microsoft and Asus and reported this problem and as of now I am not receiving the faulty bios version in updates anymore.
@seerge thank you for your help, you were right after all it was a hardware (kinda) problem

**Comment by seerge** [comment]
Glad it worked out.

**Comment by vibhor7kolhe** [comment]
> I wanted to share an update about this issue, so that if anyone else faces the same problem. the issue started happening again after installing Armoury Crate, after a lot of testing and investigation I found the source of the issue, it was the latest bios update from windows (& Asus) after visiting Asus drivers website for my laptop I found out that they removed that bios version so I re-flashed the older bios that I downloaded from Asus's website (now it's the latest one) and everything is working great now. be careful because windows still push the faulty bios version, I already talked with Microsoft and Asus and reported this problem and as of now I am not receiving the faulty bios version in updates anymore. @seerge thank you for your help, you were right after all it was a hardware (kinda) problem

I AM FACING THIS ISSUE IN ARMOURY CRATE ECO MODE  SLEEP PROBLEM WHAT SHOULD I DO MY MOTHERBOARD ALSO CHANGE TWICE TIMES BUT NO SOLUTION CAN YOU CHECK IN YOUR LAPTOP BUT NOTE TAKE THIS ON ECO MODE

**Comment by DamirKx** [comment]
> Я хотел бы поделиться новостями по этой проблеме, чтобы это было актуально для тех, кто столкнулся с такой же проблемой. Проблема снова начала возникать после установки Armoury Crate. После множества тестов и исследований я нашел ее источник. Это было последнее обновление BIOS от Windows (и Asus). Зайдя на сайт драйверов Asus для моего ноутбука, я обнаружил, что они удалили эту версию BIOS, поэтому я перепрошил старую версию BIOS, которую скачал с сайта Asus (теперь она последняя), и теперь все работает отлично. Будьте осторожны, так как Windows по-прежнему устанавливает неисправную версию BIOS. Я уже связался с Microsoft и Asus и сообщил об этой проблеме, и на данный момент я больше не получаю неисправную версию BIOS в обновлениях. [@seerge](https://github.com/seerge)Спасибо за помощь, вы были правы, в конце концов, это была аппаратная проблема (своего рода)

I have the same problem. What BIOS version did you install? Have you installed a new BIOS version yet?
