### ISSUE TITLE
Ability to disable G-Helper controlled RGB

### ISSUE THREAD

**Issue by RealMrUnknownymous** [seerge/g-helper#2930]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I control all of my RGB using SignalRGB, including the keyboard lighting of my G14 2022. When waking up from sleep, G-Helper tries to take over the lighting control from SignalRGB and succeeds. 

### Describe the solution you'd like

A button that disables G-Helper from controlling the RGB in the laptop. The keyboard brightness keys work fine, even when the lighting is controlled by SignalRGB, so that can be left alone.

### Describe alternatives you've considered

When waking up from sleep, I have to disable and reenable the lighting in SignalRGB so it can take over again. 

### Device and Model

Asus Zephyrus G14 GA402RJ

**Comment by seerge** [comment]
@RealMrUnknownymous hello, 

You can already do that https://github.com/seerge/g-helper/wiki/Power-user-settings#skip-keyboard-aura-initialisation-on-startup

Thanks

**Comment by RealMrUnknownymous** [comment]
When I added the skip aura thing, all it did was reset my G-Helper settings. That was after I tried adding it in different formats, each time G-Helper would just reload and the line I added would be gone.

**Comment by seerge** [comment]
@RealMrUnknownymous it simply means you didn't add it correctly, for example you have added an extra comma or missed one. Please check instructions on how to do that[ in the beginning of the readme](https://github.com/seerge/g-helper/wiki/Power-user-settings#general-note)

**Comment by RealMrUnknownymous** [comment]
My bad, I completely missed the part where it said to add new lines at the beginning of the file. It works now, thank you!
