### ISSUE TITLE
GHelper custom profiles being deleted after computer crash

### ISSUE THREAD

**Issue by Datumz** [seerge/g-helper#2931]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Certain games make my laptop overheat even with the fan settings turned all the way up, in this case it's the game Grounded. It only happens once, so I turn my laptop on, start to play and within less than 5 minutes the laptop just shuts off. Once back into the game, this issue doesn't happen again, until next boot of the game and laptop.

I do not blame Ghelper for the overheat issue, but when the laptop overheats and crashes, about 10% of the time Ghelper will delete all my custom profiles when reopening it. Also the issue of my profiles deleting is most noticeable playing Grounded, since its consistent in overheating my laptop. Though other games have overheated like Warzone.

### How to reproduce the bug?

Have the laptop crash, and hope it doesn't delete your profiles. No real way to replicate.

### Logs

[log.txt](https://github.com/user-attachments/files/16503783/log.txt)

### Device and Model

Asus Zephyrus G16 4080

### Armoury Crate

Uninstalled

### Asus Services

Turned off

### Version

0.181.0

### OS

Windows 11

**Comment by seerge** [comment]
@Datumz hello,

Profiles got deleted cause app's config (with your settings) apparently was open for writing in exact moment when your computer crashed. Then windows may corrupt the file in that moment, and G-Helper won't be able to read it anymore - therefore it just recreates it from scratch

```
8/5/2024 8:01:22 PM: Broken config: xxx
```

There is already a "protection" in the app, when it writes config in 2 steps to prevent such things, but it can still happen time to time. If you have "unstable" laptop, you can just make a backup of `%appdata%\GHelper\config.json` for yourself somewhere and reuse it afterwards :)

Thanks and good luck.

**Comment by seerge** [comment]
@Datumz hello, I have added some tweaks, to improve config saving in some unpredictable situations in the latest release https://github.com/seerge/g-helper/releases/tag/v0.193 

Let me know if it improves something for you :)
