### ISSUE TITLE
Please add a feature to disable automatic switching of display refresh rates

### ISSUE THREAD

**Issue by ydfq7217** [seerge/g-helper#2934]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

When I unplug the power，the screen goes black for a second and then lights up ，the refresh rates switchs from 165Hz to 60Hz.
That have been confused me for a long time

### Describe the solution you'd like

A button to disable auto refresh rate switching 

### Device and Model

TUF Gaming A16 FA607PV_FA607PV

### Additional information.

Thanks

**Comment by seerge** [comment]
@ydfq7217 hello,

If you select specific refresh rate in app, and not `Auto` it won't switch refresh rates for you.

Also https://github.com/seerge/g-helper/wiki/Requirements#recommendations-optional
> It's not recommended to have "ASUS Smart Display Control" app running, as it will try to change refresh rates and fight with g-helper for the same function. You can safely uninstall it.

**Comment by ydfq7217** [comment]
Thank you for your quick response, but I have already followed the recommendations and completed the following steps: 1. Uninstalled Armoury Create 2. Set the refresh rate to 165Hz, Balanced, and Ultimate in ghleper 3. Disabled all ASUS services in your application 4. Rebooted. However, the issue still persists 
Should I try again？

**Comment by seerge** [comment]
@ydfq7217 you need to uninstall "ASUS Smart Display Control" as I mentioned above. G-Helper is not switching your refresh rate by itself, unless you have `Auto` selected

**Comment by ydfq7217** [comment]
Did it! ASUS Smart Display Control didn't show up in the Windows Control Panel's list of apps, and it wasn't registered in the registry. I thought I had uninstalled it before, but I just found it in taskmgr again. After ending its process, the issue was resolved.
Now I have deleted it manually
I would appreciate it if you could share with our friends the details about how the "ASUS Smart Display Control" application is not present in the registry for the "天选 5 Pro" model sold in China.
