### ISSUE TITLE
Battery charge limit isn't working

### ISSUE THREAD

**Issue by Covorus** [seerge/g-helper#2936]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![image_2024-08-07_014011542](https://github.com/user-attachments/assets/b16e7c52-7c68-4660-bd69-c6462a088db4)
i can't limit the charge.

### How to reproduce the bug?

open ghelper, use the battery charge limit bar, it won't work

### Logs

[log.txt](https://github.com/user-attachments/files/16516357/log.txt)

### Device and Model

Asus strix g713pv

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.181.0

### OS

W11 23H2

**Comment by Nat123-bit** [comment]
U need to Download ASUS Battery Health Charging https://apps.microsoft.com/detail/9nkcln5x4rr9?activetab=pivot%3Aoverviewtab&hl=en-us&gl=US

**Comment by seerge** [comment]
@Covorus hello, some models support [only 60-80% charge limits](https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working). You may want try to set **exactly 80%.**

Rest is up to your laptop firmware on how to hold the charge.

Keep in mind, that if laptop is already charged to full it won't magically drop it's charge unless it's unplugged of course :)

Thanks

**Comment by seerge** [comment]
P.S. On a side note, sometimes simply unplugging and plugging your device again can help as well :)
