### ISSUE TITLE
Keyboard lightning not working right

### ISSUE THREAD

**Issue by crayolaballs** [seerge/g-helper#2937]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

RGB lighting doesnt follow colour picked, it was working fine a couple days ago. I usually have breathing mode on, pink and blue. When i game with my lights off i turn the mode to static and colour red. I switch back and forth quite often. Then for some reason breathing just stayed on either colour, flashing the same colour even though ive tried changing most settings to test it, others work fine, its just breathing mode. Dynamic lighting in settings is also already turned off.

### How to reproduce the bug?

1. Go to laptop keyboard 2. Change mode to breathe 3. Pick two different colours

### Logs

[log.txt](https://github.com/user-attachments/files/16516914/log.txt)

### Device and Model

ASUS Zephyrus G16 GU605MI

### Additional information.

https://github.com/user-attachments/assets/cf175c3b-da90-4295-947a-64319f8f6b84

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.181

### OS

Windows 11 22H2

**Comment by crayolaballs** [comment]
[log.txt](https://github.com/user-attachments/files/16529195/log.txt)
IT WORKED. youre godsent. thanks a bunch

**Comment by seerge** [comment]
@crayolaballs great, just use latest [0.183](https://github.com/seerge/g-helper/releases/tag/v0.183) then.
