### ISSUE TITLE
Game Visual disable button

### ISSUE THREAD

**Issue by Nat123-bit** [seerge/g-helper#2938]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

when I put some custom color settings on the Nvidia control panel or intel command center, "Game Visual" interrupts them and I would like a deactivation button.

### Describe the solution you'd like

A "Game Visual" disable button.

### Describe alternatives you've considered

Other version of the "G-helper" app without "Game Visual"

### Device and Model

Asus ROG Strix G18

**Comment by seerge** [comment]
@Nat123-bit hello, 

If you would select visual mode "Default" G-Helper would not try to change / set anything on startup. So it's effectively disabled.

If you want to hide Visual Modes section from UI completely, you can also do that 
https://github.com/seerge/g-helper/wiki/Power-user-settings#visual-modes-section

Thanks

**Comment by Nat123-bit** [comment]
thank you very much for the answer, and for making "G-helper" you are the GOAT.

**Comment by seerge** [comment]
@Nat123-bit hello,

I have recently discovered how Armoury can completely disable Game Visual by calling `AsusSplendid.exe` (responsible for it) and added it to G-Helper as new "Disabled" Visual Mode.

It is live in latest release https://github.com/seerge/g-helper/releases/tag/v0.196

Let me know if it changes something for you

**Comment by Nat123-bit** [comment]
thank you very much, this really helps me, now I don't have any problem
with the visual.
