### ISSUE TITLE
Export/Import current settings Option

### ISSUE THREAD

**Issue by yesrab** [seerge/g-helper#2939]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

The issue is i have to configure Ghelper fan curves and other settigns every time i reinstall windows or if Ghelper settings are lost after an update

### Describe the solution you'd like

an ability to export the current settings and an ability to import settings 
Ghelper can export a config.json or config.reg as the user setting that were applied and an option to import the config file

### Device and Model

Asus Zephyrus G14 GA401IU

**Comment by seerge** [comment]
@yesrab hello, you can just save and restore `%appdata%\GHelper\config.json`. This is the only settings file it uses :) 

Thanks
