### ISSUE TITLE
Dynamic Weather AniMatrix

### ISSUE THREAD

**Issue by xwinghangar** [seerge/g-helper#2948]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

animatrix to display the current local weather with clock

### Describe the solution you'd like

integrate dynamic weather into ghelper found from these sources, 

https://www.reddit.com/r/ZephyrusG14/comments/j11kp8/finished_my_dynamic_weather_animatrix_here_are/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

https://github.com/nick-scott/g14control-r2/releases/tag/v2.1.1

https://github.com/user-attachments/assets/06b69b06-f42d-469e-8aa2-38cd30669c8a

### Device and Model

Zephyrus G14 GA402XZ

**Comment by seerge** [comment]
@xwinghangar hello, this is too much and against whole idea of g-helper being small and lightweight app. Thanks
