### ISSUE TITLE
Monitor Off/On Button?

### ISSUE THREAD

**Issue by Raychan87** [seerge/g-helper#295]
Thank you for the nice tool. 

Unfortunately, the G14 does not have a standard button to turn the monitor on and off. 

Currently I use "Dekisoft Monitor Off" with a button combination. Is it possible to add such a function for the M3/M4 button?

If it is not possible or too complicated. How do I put a key combination like "CTRL+ALT+Y" on M3?

**Comment by seerge** [comment]
@Raychan87 - since you already use app for that, i think it will be easier to bind a key. You can't bind a combination at the moment, but what you can do - is trigger some exotic keypress for M3/M4 like F13 (that doesn't even exist on default keyboard)

It's explained at https://github.com/seerge/g-helper#custom-hotkey-actions

Full list of codes that you can use is here https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

Then you can setup your Dekisoft Monitor Off to listen for that combination i think ? :)

**Comment by Raychan87** [comment]
Thank you very much for your answer.

Unfortunately, in Dekisoft Monitor Off you can't set F keys.
I also wanted to use the script function, but unfortunately the custom function does not work. 
When I type "notepad" as in your example, Notepad also opens, but any path with an "exe" or "bat" does not work.

i use the g-helper v0,55.

config.json:
  "m3_custom": "C:\\Windows-Extras\\Programme\\MonitorOff.Bat",
  "m3": "custom",
  "m4_custom": ""

**Comment by seerge** [comment]
Cause to run bat you need to tell windows with what to execute it, try

``cmd.exe /c  command C:\Windows-Extras\Programme\MonitorOff.Bat``

**Comment by Raychan87** [comment]
Unfortunately, does not work either.

even if I only enter "cmd.exe" nothing happens.

**Comment by seerge** [comment]
@Raychan87 this build should fix cmd running

Also i have simply added Laptop Screen option in dropdown that should toggle screen on / off

[GHelper.zip](https://github.com/seerge/g-helper/files/11358776/GHelper.zip)

**Comment by Raychan87** [comment]
cmd works now :)

The new function Display on/off does not work on my Asus G14 GA401QM 2021 with Windows 11 22H2.
What kind of command do you use?

My batch file has the command:

powershell (Add-Type '[DllImport(\"user32.dll\")]^public static extern int PostMessage(int hWnd, int hMsg, int wParam, int lParam);' -Name a -Pas)::PostMessage(-1,0x0112,0xF170,2)

**Comment by seerge** [comment]
@Raychan87 i use same, strange it doesn't work

```
    public const int WM_SYSCOMMAND = 0x0112;
    public const int SC_MONITORPOWER = 0xF170;
    public const int MONITOR_ON = -1;
    public const int MONITOR_OFF = 2;
    public const int MONITOR_STANDBY = 1;

    public static void ToggleMonitor()
    {
        SendMessage(-1, WM_SYSCOMMAND, SC_MONITORPOWER, MONITOR_OFF);
    }
```

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11358858/GHelper.zip)
Try this one

**Comment by Raychan87** [comment]
Yes, now it works. Thanks a lot :)

Wish you still a nice weekend
