### ISSUE TITLE
Microstutter when running on G14 2024

### ISSUE THREAD

**Issue by tonywei92** [seerge/g-helper#2951]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Microstutter happen when GHelper is running, but become smooth again if exit.

The video is here: https://www.reddit.com/r/ZephyrusG14/comments/1enletv/g14_2024_microstutters_already_tried_ddu_nothing/

### How to reproduce the bug?

1. Run GHelper
2. Drag any Window

### Logs

[log.txt](https://github.com/user-attachments/files/16561266/log.txt)

### Device and Model

G14 2024 RTX 3060

### Armoury Crate

Never installed

### Asus Services

7

### Version

0.183.0

### OS

Windows 11 Home 23H2

**Comment by seerge** [comment]
@tonywei92 hello, 

I see that you use Ambient backlight mode. It (by definition) measures average screen color and updates it few times a second. Making multiple screenshots can have impact on windows. 

Just use any other backlight mode and it will be fine.

Thanks.

**Comment by tonywei92** [comment]
> @tonywei92 hello,
> 
> I see that you use Ambient backlight mode. It (by definition) measures average screen color and updates keyboard backlight few times a second. Making constant screenshots can have impact on windows (it also depends on GPU drivers) :) it's normal.
> 
> Just use any other backlight mode and it will be fine.
> 
> Thanks.

Thanks a lot, @seerge !

I wish we could have some kind of warning/notes for people who have no idea like me!

Cool software btw, thanks!
