### ISSUE TITLE
Need more undervolting

### ISSUE THREAD

**Issue by marcelomijas** [seerge/g-helper#2952]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I've been tuning the CPU undervolting of my 2020 G14. I am suprised to see that an undervolting of -40 (mv?) is stable on my system. I've monitored CPU VID and temps while doing some benchmarks like the 7zip and Handbrake Big Buck Bunny H265 VCE and saw no performance difference whatsoever (same or better), while seeing that CPU VID was lower every time I adjusted the setting on G-Helper (this was, to check that it was doing something).

![imagen](https://github.com/user-attachments/assets/00d81695-e3da-4a60-955e-817b83a869e0)

For example, for 7zip: HWiNFO CPU VID (x8 cores):
- Undervolting -0 --> VID 7.3 V
- Undervolting -10 --> VID 7.19 V
- Undervolting -20 --> VID 7.05 V
- Undervolting -40 --> VID 6.8 V

I don't know if I am the only one. If yes, then I won the silicon lottery... and I've been wasting this gift for years...

### Describe the solution you'd like

I need the undervolting slider to go further down, like -80.

### Device and Model

Asus Zephyrus G14 G1401IV

**Comment by seerge** [comment]
@marcelomijas hello, you actually [can increase that already](https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-cpu-undervolting-limit) :)

**Comment by marcelomijas** [comment]
Oh, sorry @seerge . Thanks! :D
(I thought I had to find "min_uv" and could not find it, but I see I have to add it)
