### ISSUE TITLE
adding custom action for rog ally cc key 

### ISSUE THREAD

**Issue by ripplingsnake** [seerge/g-helper#2955]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I am trying to get the command center key to open steam menu in steam big picture mode. 
the keyboard short cut is cntl + 1  so i tried adding the hex as 0x11 0x31  and also tried VK-CONTROL 0x31 but noine of these seem to work 

### How to reproduce the bug?

open ghelp and go to extra to adjust controls actions 

### Logs

[log.txt](https://github.com/user-attachments/files/16568967/log.txt)

### Device and Model

rog ally x

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.183

### OS

windows 11

**Comment by seerge** [comment]
@ripplingsnake hello, 

`Command Center` and `ROG` keys can be binded only on "software" level. I.e. app can emit some keypresses via windows API when they are pressed. If `0x11 0x31` doesn't open Steam - then it means it simply does not support that, so I can't do anything here. You also can't rebind those buttons in AC.

If I'm not mistaken, you can make Steam open when so-called "Guide" (Xbox) button is pressed on a controller ? And you can bind any of `M + <something` combination to this button under Controller section
