### ISSUE TITLE
Integrating Asus Sound Booster from MyASUS into G-Helper

### ISSUE THREAD

**Issue by rumifloss** [seerge/g-helper#2957]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

My Vivobook has a sound utility in MyASUS called Volume Booster (advertised as ASUS Volume Booster on its webpage) that seems to flatten the highs and lows and increase the volume of the internal speakers for "louder" audio. It's very handy when I don't have any external speakers or earphones around and it would be great if G-Helper could feature a toggle for it. Surprisingly it's one of two features that work just fine with all other ASUS services disabled and MyASUS crippled, with the second feature being a proxy for the Dirac software EQ effects on the laptop. I've attached a screenshot. I would love to uninstall MyASUS for once and a for all when I find what service it actually affects.

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Device and Model

Asus Vivobook 14X K3405VF(B)

### Additional information.

![MyASUS_Volume_Booster_No_Sign-in](https://github.com/user-attachments/assets/06017ade-3fe2-4abc-9412-a931e4efb259)

**Comment by seerge** [comment]
@rumifloss hello, I honestly don't know what it is and how it works as I don't have your device.

But most likely it's just a shortcut to some audio settings that are already available either via Realtek Audio Console app (same as mic settings for ROG / TUF models) or in Dolby app ...

Besides that I'm afraid I can't help anyhow :)
