### ISSUE TITLE
Add controller input rebind.

### ISSUE THREAD

**Issue by peace20021** [seerge/g-helper#2959]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

So I would like to remind the AC key to Xbox key in the ROG Ally Z1 Extreme, but so far the app wouldn't let me do that.

### Describe the solution you'd like

Please add controller input rebind support for the ROG Ally

### Describe alternatives you've considered

I have tried searching for the windows input key code but there isn't any.

### Device and Model

Ally Z1 Extreme

**Comment by seerge** [comment]
@peace20021 hello, I was answering this already https://github.com/seerge/g-helper/issues/2955

AC / CommandCenter buttons are not part of the controller and can't be rebinded on hardware level neither in Armoury nor in G-Helper. You can only assign them to some own actions or a keyboard hotkeys via `Extra`

You can rebind any of `M + <key>` combinations to Xbox key however using Controller settings. For example `M + Menu`
