### ISSUE TITLE
New resources monitoring overlay from armory crate in Ghelper?

### ISSUE THREAD

**Issue by tavareswillian1993** [seerge/g-helper#2960]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

No problem. 

### Describe the solution you'd like

Is it in the plans to port the new resources monitoring overlay to Ghelper in the future?
![IMG_1334](https://github.com/user-attachments/assets/5ee297af-299e-44e2-802d-c0edc0541156)

### Device and Model

TUF A16 advantage edition 

### Additional information.

![IMG_1334](https://github.com/user-attachments/assets/c359af99-dc73-4090-81c0-b9785181be2b)

this is from the new A14 with the new ryzen 9.

**Comment by seerge** [comment]
@tavareswillian1993 hello, I was answering this already https://github.com/seerge/g-helper/issues/2869

>There is plenty of tools for monitoring already. Starting from native apps like AMD Adrenaline or Nvidia Experience having own monitoring, then HWinfo has a nice overlay, etc.

Thanks
