### ISSUE TITLE
Arrow lock for DUO

### ISSUE THREAD

**Issue by vladimir56r** [seerge/g-helper#2965]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I run g-helper, regardless of whether the arrow lock is on or off, g-helper duplicates the keystrokes of the home\end\PgUp\PgDown keys.

### How to reproduce the bug?

Without g-helper:
![image](https://github.com/user-attachments/assets/749d617e-541a-4c11-9c65-2e4ebfdb0c9f)
With g-helper:
![image](https://github.com/user-attachments/assets/46fe1b50-bab8-413a-87a5-ca0e6d32dccc)

pressing a key does Home/End/..., releasing it does Left-arrow/Right-arrow/...
Example: if you hold down the key right-arrow, can be seen:
![image](https://github.com/user-attachments/assets/1f8d49d5-79e2-411d-b861-9e8c98443562)

### Logs

12.08.2024 9:41:08: Latest version 0.181.0.0
12.08.2024 9:41:16: Left None
12.08.2024 9:41:16: Right None
12.08.2024 9:41:17: Up None
12.08.2024 9:41:18: Down None
12.08.2024 9:42:25: Right None
12.08.2024 9:42:26: Right None
12.08.2024 9:42:26: Right None
12.08.2024 9:42:26: Right None
12.08.2024 9:42:26: Right None
12.08.2024 9:42:26: Right None
12.08.2024 9:42:26: Right None
12.08.2024 9:42:26: Right None
12.08.2024 9:42:26: Right None
12.08.2024 9:42:26: Right None
12.08.2024 9:42:26: Right None
12.08.2024 9:42:26: Right None
12.08.2024 9:42:27: Right None
12.08.2024 9:42:27: Right None
12.08.2024 9:42:27: Right None
12.08.2024 9:42:27: Right None
12.08.2024 9:42:27: Right None
12.08.2024 9:42:27: Right None
12.08.2024 9:42:27: Right None
12.08.2024 9:42:27: Right None
12.08.2024 9:42:27: Right None
12.08.2024 9:42:27: Right None
12.08.2024 9:42:27: Right None
12.08.2024 9:42:27: Right None
12.08.2024 9:42:27: Right None
12.08.2024 9:42:27: Right None
12.08.2024 9:42:28: Right None
12.08.2024 9:42:29: Right None
12.08.2024 9:42:29: Right None
12.08.2024 9:42:29: Right None
12.08.2024 9:42:29: Right None
12.08.2024 9:42:29: Right None
12.08.2024 9:42:29: Right None
12.08.2024 9:42:29: Right None
12.08.2024 9:42:29: Right None
12.08.2024 9:42:29: Right None
12.08.2024 9:42:29: Right None
12.08.2024 9:42:29: Right None
12.08.2024 9:42:29: Right None
12.08.2024 9:42:29: Right None
12.08.2024 9:42:29: Right None
12.08.2024 9:42:29: Right None
12.08.2024 9:44:39: Miniled: 1 -65536
12.08.2024 9:44:39: NE160QDM-NM4 HDR: True 10 3 False
12.08.2024 9:44:39: Design Capacity: 90005mWh, Full Charge Capacity: 77428mWh, Health: 0,8602633187045164157546802955%
12.08.2024 9:44:43: Varibright: 0,0
12.08.2024 9:44:43: Hibernate after 2147483647

### Device and Model

Asus Zephyrus Duo 16 GX650PY

### Armoury Crate

Uninstalled

### Version

0.181.0.0

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@vladimir56r do you have asus services running? If so - stop them. 
And please upload full log as it was asked in the issue template.

**Comment by seerge** [comment]
@vladimir56r any updates here ?

**Comment by vladimir56r** [comment]
Hi! Yes, the Asus services were enabled and this caused the problem. I would like to note that this was not observed before when the Asus services were running...

[log.txt](https://github.com/user-attachments/files/16645317/log.txt)
