### ISSUE TITLE
Dynamic Lighting label on Windows 10

### ISSUE THREAD

**Issue by karabaja4** [seerge/g-helper#2966]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

There is a label saying "Please disable Windows > Dynamic Lighting" which opens Windows Settings on Windows 10.

![image](https://github.com/user-attachments/assets/4a06895b-8de3-4ab1-8f3f-10744bd5512b)

However, I don't think there is an option to control Dynamic Lighting on Windows 10 - I think it this is a feature introduced in Windows 11.

Also, I see that the app is reading this registry key:

```
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Lighting\AmbientLightingEnabled
```

Setting this key doesn't do anything on Windows 10 - the path does not exist unless created manually - which removes the label if set to 0, but still :)

If Dynamic Lighting is not supported, maybe it's a good idea to hide this label on Windows 10 so not to confuse the users?

### How to reproduce the bug?

1) Open G-Helper on Windows 10.
2) Observe the label "Please disable Windows > Dynamic Lighting"

### Logs

-

### Device and Model

ASUS ROG Strix SCAR 18 G834YJR

### Armoury Crate

Uninstalled

### Version

0.181.0

### OS

Windows 10 21H2

**Comment by seerge** [comment]
@karabaja4 hello, can you check if this build works correctly ?

[GHelper.zip](https://github.com/user-attachments/files/16581498/GHelper.zip)

**Comment by karabaja4** [comment]
@seerge The build you provided works, the label is not displayed even without the registry key.

**Comment by seerge** [comment]
@karabaja4 great!
