### ISSUE TITLE
Cannot see the icon in taskbar

### ISSUE THREAD

**Issue by Reach-Orange-CN** [seerge/g-helper#2967]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Cannot see the icon in taskbar after starting the app.
![image](https://github.com/user-attachments/assets/22cbfaa5-34b9-40e2-baa5-1c391707c3b1)

### How to reproduce the bug?

just start the app

### Logs

[log.txt](https://github.com/user-attachments/files/16582251/log.txt)

### Device and Model

ROG Zephyrus G16 GU605MV

### Armoury Crate

Uninstalled

### Asus Services

8

### Version

0.184.0

### OS

Windows 11

**Comment by seerge** [comment]
@Reach-Orange-CN 

hello, it's just some windows hiccup. If you have dragged icon to taskbar, remove it and run app again. Or try to restart windows.

Besides that i can't change anything as this is not the app's fault.

Thanks.
