### ISSUE TITLE
"updates" section not displaying Intel NPU driver for Core Ultra devices

### ISSUE THREAD

**Issue by garecrow** [seerge/g-helper#2968]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

In the updates section of the app where all bios and drivers are listed with their current version and available updates, the line for the Intel NPU driver is missing, which should be included on all Core Ultra equipped devices (though that is currently only the 2024 g16 i believe)

### How to reproduce the bug?

open g-helper, click updates, see the line is missing

### Logs

Not Applicable

### Device and Model

Zephyrus G16 2024

### Additional information.

![image](https://github.com/user-attachments/assets/8fe6a769-e51a-4d69-935f-1ad28226c11e)
![image](https://github.com/user-attachments/assets/5470e1d3-3002-4dc9-b10a-265609449f13)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.181.0

### OS

WIndows 11 24H2

**Comment by seerge** [comment]
@garecrow hello,

`Updates` section shows you a mirror of a corresponding Asus Drivers / BIOS updates from official asus website
https://rog.asus.com/laptops/rog-zephyrus/rog-zephyrus-g16-2024/helpdesk_download/

I don't see anything called "NPU" driver there :) so obviously you won't see it in the app.
There is a microsoft effect pack that seem to have it and it's listed in `Updates` too.
<img width="1180" alt="Screenshot 2024-08-12 at 16 30 08" src="https://github.com/user-attachments/assets/a5b1b8be-430f-453a-87a3-44efa7a8a26d">


If you need - you are free to download and use updates directly from Intel / AMD / Nvidia sites, etc of course.

Thanks
