### ISSUE TITLE
lightbar dosen't turn on/off when the Labtop is plugged/unplugged despite lightbar being chosen as deactivated on battery

### ISSUE THREAD

**Issue by elfi-ox** [seerge/g-helper#2969]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![image](https://github.com/user-attachments/assets/df669d6b-80ad-45d6-8cc3-3cc6249f0473)
My Lightbar is set to turn off on battery but when I unplug my Labtop it stay ON until I update it by changing anything in the Lightbar settings. same thing happen when I plug in my pc, it stays off until I change anything in the rgb settings

Note : it does the same things with the keyboard

### How to reproduce the bug?

1 - Deselect "Battery" bellow lightbar in the backlight settings
2 - Unplug the labtop
3 - Change anything in the lightbar settings to update the lightbar status
4 - plug in the labtop
5 - Change anything in the lightbar settings to update the lightbar status

### Logs

[log.txt](https://github.com/user-attachments/files/16589986/log.txt)

### Device and Model

Asus ROG Strix G15 R513RW

### Additional information.

Animation speed : Normal
Delay : 0 / 120

### Armoury Crate

Installed

### Asus Services

0

### Version

0.181.0

### OS

Windows 11 Home 23H2

**Comment by seerge** [comment]
@elfi-ox hello, most likely you have added `"skip_aura":1,` param to config cause you were asking about it https://github.com/seerge/g-helper/discussions/2898 ?

If so, G-Helper obviously skips all automated backlight commands on start / plug in / plug.

Just remove that param and G-Helper will set backlight automatically.

Thanks,.

**Comment by elfi-ox** [comment]
Oh I understand now, I didn't make the connection with that. Thanks and sorry for confusion
