### ISSUE TITLE
G834JY resetting itself while on Turbo mode in certain games

### ISSUE THREAD

**Issue by EoKc** [seerge/g-helper#2970]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Laptop is resetting itself on Turbo mode in Helldivers 2 

### How to reproduce the bug?

After couple minutes in game laptop reset itself 

### Logs

[log.txt](https://github.com/user-attachments/files/16590174/log.txt)

### Device and Model

ASUS ROG G834JY

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.181.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@EoKc hello,

G-Helper is not a driver and it's not running your [hardware in real-time anyhow](https://github.com/seerge/g-helper?tab=readme-ov-file#-important-notice)

If your device randomly reboots during gaming, it's probably either overheating or due to some other hardware / firmware / driver issues.

I see that you don't use default `Turbo` mode, but seem to have **custom fan curves** and some **GPU overclocking** set. I can only advice to try to reset all settings to defaults - i.e. click `Factory Defaults` and check if makes any difference :)

Besides that, I can't do anything else.

Thanks and good luck.

**Comment by seerge** [comment]
@EoKc P.S. I also see that you seem to disable some of the CPU cores under `Extra` ? 

```
12/08/2024 10:39:27: Cores: 0x0008
12/08/2024 10:39:27: CoresMax: 0x1008
```

I would advice to revert that back to defaults as well :)

**Comment by EoKc** [comment]
> @EoKc P.S. I also see that you seem to disable some of the CPU cores under `Extra` ?
> 
> ```
> 12/08/2024 10:39:27: Cores: 0x0008
> 12/08/2024 10:39:27: CoresMax: 0x1008
> ```
> 
> I would advice to revert that back to defaults as well :)
> 
> And of course don't forget to check https://github.com/seerge/g-helper/wiki/Troubleshooting

Hi Serge thank you for answering, i just close the Ecore on cpu. I can revert that

**Comment by EoKc** [comment]
> @EoKc P.S. I also see that you seem to disable some of the CPU cores under `Extra` ?
> 
> ```
> 12/08/2024 10:39:27: Cores: 0x0008
> 12/08/2024 10:39:27: CoresMax: 0x1008
> ```
> 
> I would advice to revert that back to defaults as well :)
> 
> And of course don't forget to check https://github.com/seerge/g-helper/wiki/Troubleshooting

Hi Serge i did the hardware reset but now mu laptop keep resetting itself when booting 😂

**Comment by seerge** [comment]
@EoKc looks like something is not right with the device itself. Is it able to boot into BIOS at least ?

**Comment by EoKc** [comment]
https://github.com/user-attachments/assets/4895efcd-cdae-4e34-bf4c-ffa8c21879f9

it is keeping doing like this

**Comment by seerge** [comment]
@EoKc try to completely shut it down, and then do a hard reset again - press and hold power button for 40 seconds
As Asus explains themselves https://www.asus.com/support/faq/1050239/

**Comment by EoKc** [comment]
> @EoKc try to completely shut it down, and then do a hard reset again - press and hold power button for 40 seconds As Asus explains themselves https://www.asus.com/support/faq/1050239/

İ can not hard reset again i dont know. I should not EC first 😁 i did not have any problem like this before

**Comment by EoKc** [comment]
https://github.com/user-attachments/assets/1a0e91b6-5928-4d00-b0f1-d955f7924629

It is like this when i first EC power indicator flash rapidly but now it is bot happening

**Comment by seerge** [comment]
@EoKc that's strange, i would turn it on after and wait for an extended time, may be it will eventually boot. My G14 2022 usually takes like an extra 30 seconds after hard reset to boot for the first time.

But generally looks like something is wrong with the laptop itself, if following official asus advices doesn't help. May be check with the service ?

Anyway, I can't really help here. As whole thing is not related to the app. 
So I can only wish you good luck here and close this. Thanks

P.S. Feel free to post an update tho, if you will figure out what was wrong :)
