### ISSUE TITLE
GPU Fan not working when XGM Connected

### ISSUE THREAD

**Issue by Purpleday1506** [seerge/g-helper#2971]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi, 
I have a ROG Flow Z13 (2022) and a XGM RTX3080. when the XGM is Connected and I Activate a coustom Fan curve the GPU Fan in the Tablet itself goes to 0% and the CPU fan appears to be spinning on the App but when i check phisicaly it isnt spinning´. THE GXM fan however is spining as per the Coustom fan curve. This gives me way worse CPU Thermals than i should have in Game since the GPU fan on the tablet is used to cool the CPU when the GXM is in use. 
When using a factory preset without a coustom fan curve it works just fine if a litte slow for my taste even ín Turbo.
Ive tried Restarting, switching from XGM to IGPU, to DGPU and Back in every combination imaginable and nothing seems to work.Pase Help an thank you for the hard work you put into this!

### How to reproduce the bug?

1. Connect XGM
2. Enaible XGM 
3. Switch from preset fan curve (any) to coustom fan curve
4. GPU fan goes to 0 + CPU Fan doesnt Phisicaly spin as opposed to what software is saying  

### Logs

[log.txt](https://github.com/user-attachments/files/16596682/log.txt)

### Device and Model

ROG Flow Z13 GZ301ZE + XG Mobile GC31S

### Additional information.

![Screenshot 2024-08-13 104349](https://github.com/user-attachments/assets/5f3d3ded-2ff7-40a1-b97a-a7ad769b6ac0)
![Screenshot 2024-08-13 104533](https://github.com/user-attachments/assets/25550b79-1b9b-44e8-a0ec-f8901a8893a2)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

Latest a of 08.204

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Purpleday1506 hello,

G-Helper does not control fans in realtime anyhow. [Fans are always controlled by BIOS](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds), even when you set a custom fan curve.

The custom fan curve for all fans is being applied and is accepted. So if BIOS decided to stop GPU fan - this is how it's programmed internally
```
13/08/2024 10:26:22: XGM-6512|300:5E-D1-01-1E-28-2E-34-3E-44-4A-64-00-19-26-32-5D-5D-5D-5D
13/08/2024 10:26:22: FanCPU = 1E-28-2E-34-3D-44-4A-64-00-19-26-32-5E-5E-5E-5F : OK
13/08/2024 10:26:22: FanGPU = 1E-28-2E-34-3E-44-4A-64-00-19-26-32-5B-5B-5B-5B : OK
```

You can try to 
- use different base mode for custom fan curves (currently you use "Balanced", try to use "Turbo" instead)
- adjust fan curve and see if it makes any difference
- also apply a power limits next to fan curve (sometimes it makes BIOS wake up)
- just use default mode

If this doesn't help, and you still want to customize fan behavior - you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)

Besides that I can't do anything else. Thanks
