### ISSUE TITLE
Can't change keyboard lightning 

### ISSUE THREAD

**Issue by Rooie100** [seerge/g-helper#2973]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

As the title says, i cant change the lightning in G-helper. Only when i click ''run Asus services'' then it works. Dynamic lightning is disabled via windows.

I'm also using the latest version of G-helper. 

### How to reproduce the bug?

Go to G-helper
Click on a different color
Keyboard stays in breathing

### Logs

[log.txt](https://github.com/user-attachments/files/16601958/log.txt)

### Device and Model

ASUS Vivobook S 15 OLED M5506NA.

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.184.0

### OS

Windows 11 H

**Comment by seerge** [comment]
@Rooie100 hello,

Is it only backlight **modes** that don't work or also backlight brightness ?

Cause I see that brightness controls seem to exist on your device and work
```
8/13/2024 5:31:08 PM: TUF Brightness = 128 : OK
8/13/2024 5:31:09 PM: WMI event 199
8/13/2024 5:31:09 PM: TUF Brightness = 129 : OK
8/13/2024 5:31:09 PM: WMI event 199
8/13/2024 5:31:09 PM: TUF Brightness = 130 : OK
8/13/2024 5:31:09 PM: WMI event 199
8/13/2024 5:31:09 PM: TUF Brightness = 131 : OK
```

While backlight modes are absent 
```
8/13/2024 5:30:27 PM: AuraMode: AuraStatic
8/13/2024 5:30:27 PM: TUF RGB = B4-00-FF-80-40-EB : 0 <-- 0 means it's not there
8/13/2024 5:30:27 PM: TUF RGB = B4-00-FF-80-40-EB : 0
``` 

What happens if you start asus services, does the backlight mode selection in G-Helper itself start suddenly working ? Or how do you change backlight otherwise ?

**Comment by Rooie100** [comment]
Hi, thanks for the response.All the backlight modes don’t work, even within windows. I also can’t change the brightness or color. When i start the asus services, the lightning control within g-helper all of a sudden starts working. If you need anymore info let me know!On 13 Aug 2024, at 17:43, Serge ***@***.***> wrote:﻿
@Rooie100 hello,
Is it only backlight modes that don't work or also backlight brightness ?
Cause I see that brightness controls seem to exist on your device and work
8/13/2024 5:31:08 PM: TUF Brightness = 128 : OK
8/13/2024 5:31:09 PM: WMI event 199
8/13/2024 5:31:09 PM: TUF Brightness = 129 : OK
8/13/2024 5:31:09 PM: WMI event 199
8/13/2024 5:31:09 PM: TUF Brightness = 130 : OK
8/13/2024 5:31:09 PM: WMI event 199
8/13/2024 5:31:09 PM: TUF Brightness = 131 : OK

While backlight modes are absent
8/13/2024 5:30:27 PM: AuraMode: AuraStatic
8/13/2024 5:30:27 PM: TUF RGB = B4-00-FF-80-40-EB : 0 <-- 0 means it's not there
8/13/2024 5:30:27 PM: TUF RGB = B4-00-FF-80-40-EB : 0

What happens if you start asus services, does the backlight mode selection in G-Helper itself start suddenly working ? Or how do you change backlight otherwise ?

**Comment by seerge** [comment]
@Rooie100 then it looks like your device is quite unique and asus services work as a proxy between actual backlight and apps that want to set it, since when they are running all backlight commands work in g-helper.

It may be very difficult to find a way to directly set backlight in your case without having access to the actual device.

Can you make a DSDT dump [as explained in Method 2](https://github.com/seerge/g-helper/issues/38) and upload it here ?

**Comment by seerge** [comment]
@Rooie100 any updates with the dump here ?

**Comment by GDisco0730** [comment]
I have this same issue with Asus ProArt P16. When Ghelper is running amd Asus service are stopped, I am unable to change backlight color, modes, or brightness just nothing happens at all when any changes made. Even when I restart services, I am now able to change backlight brightness and modes, but still not the colors.

**Comment by seerge** [comment]
@GDisco0730 does your device even support different colors? Cause Proart X13 does not for example.

As for the rest, same question please [upload DSDT dump from Method 2](https://github.com/seerge/g-helper/issues/38) here (and log from the app as well)

**Comment by Rooie100** [comment]
Hey Seerge,

Sorry to keep you waiting, i attached the dsdt in ZIP form/
[dsdt.zip](https://github.com/user-attachments/files/16625035/dsdt.zip)

**Comment by seerge** [comment]
@Rooie100 hello, thanks.

Can you check if this build makes any difference ?
[GHelper.zip](https://github.com/user-attachments/files/16625263/GHelper.zip)

**Comment by gbassani** [comment]
I have the same issues with the vivobook s 16. Testing the new zip you added.

So far, the colors are now indexing again like it was new, constantly cycling through the colors (was just static blue prior). 

I have my Asus uninstalled as well as having run the armoury crate removal tool.

**Comment by seerge** [comment]
@gbassani i  don't think that you are similar to other people here :) as they can't control backlight (due to some unknown method specific only to that devices?)

If you had static blue - that's a sign of windows Dynamic Lighting being ON and taking over. Just make sure [to disable it](https://github.com/seerge/g-helper/wiki/FAQ#backlight-doesnt-change-color-or-stays-blue) and regular mainstream build should work fine.

**Comment by gbassani** [comment]
Thank you for the info, missed that in the FAQ's. Even with dynamic lighting off (both globally and under the keyboard), the colors continue to cycle. I also tried setting both the personalization color and within G-Helper to static red. This is under the mainstream build. 

Model is the M5606WA with the AMD stack. Also checked and it isn't in the list of compatible devices, I can submit for it there.

**Comment by seerge** [comment]
@gbassani 
- How do you control backlight there in a first place w/o g-helper ? 
- You are saying that you have run AC uninstaller, but since it's not ROG or TUF you never had AC ? 
- Can you upload a log form the app?

**Comment by Rooie100** [comment]
> @Rooie100 hello, thanks.
> 
> Can you check if this build makes any difference ? [GHelper.zip](https://github.com/user-attachments/files/16625263/GHelper.zip)

Hey, 

It semi fixed it! I can control the brightness now, but not the color. It stays in breathing mode....

**Comment by seerge** [comment]
@Rooie100 ok, good news, can you try this build and post a log from it ?

[GHelper.zip](https://github.com/user-attachments/files/16630514/GHelper.zip)

**Comment by seerge** [comment]
P.S. @gbassani @GDisco0730 you both can try build above as well

**Comment by Rooie100** [comment]
Hi,

Here is the log! Thanks for the effort already, i'm happy that i can change the brightness at least. 

[log.txt](https://github.com/user-attachments/files/16635893/log.txt)

**Comment by seerge** [comment]
@Rooie100 ok, but do backlight modes work in this build or not ?

**Comment by seerge** [comment]
Cause if it does not, it looks like not only endpoint (i.e. where to set backlight setting) but also structure of the command itself is different. 

Try this build instead, to see if it makes any difference (and again post a log)
[GHelper.zip](https://github.com/user-attachments/files/16636140/GHelper.zip)

**Comment by Rooie100** [comment]
Hi,

Last build does not change a thing, can't change the lightning withing G-helper. 
Log is attached, thanks for the response again! 
[log.txt](https://github.com/user-attachments/files/16645103/log.txt)

**Comment by seerge** [comment]
@Rooie100 ok, thanks for checking. Then the only way would be to intercept actual payloads that asus service sends to the device in order to sent backlight modes as explained in https://github.com/seerge/g-helper/wiki/_ACPI-Monitoring-and-Debugging

Ideally would be good to : 
- set different modes (but keep same color) and capture that.
- then keep same mode but change colors and capture that as well :)

**Comment by kennycoder** [comment]
Try deleting %AppData%/GHelper folder. Fixed it for me. Unfortunately I didn't it backup up so I couldn't do the diff. 
Anyone still experiencing issues, please do it and see what's the difference... will be helpful.
Mine is G14 from 2023.

**Comment by seerge** [comment]
@kennycoder G14 2023 backlight control is 100% supported (and used by dozens of thousands of people). Config removal won't do anything except erasing of own G-Helper settings.

People in this thread have new (mid 2024 devices) that use different backlight controls.

**Comment by gbassani** [comment]
> P.S. @gbassani @GDisco0730 you both can try build above as well

Apologies for delay, tried this package and stuck on static white. Dynamic is disabled globally and at keyboard level. Also attempted to set to static red in personalization and in g-helper.

Attached the log.txt, screenshots of the dynamic lighting/g-helper, and the dsdt
[log.txt](https://github.com/user-attachments/files/16662715/log.txt)

[dsdt.zip](https://github.com/user-attachments/files/16662716/dsdt.zip)

[screenshots.zip](https://github.com/user-attachments/files/16662713/screenshots.zip)

**Comment by seerge** [comment]
@gbassani hello, thanks for checking. As I have explained in a [comment above](https://github.com/seerge/g-helper/issues/2973#issuecomment-2294867113) i need someone to record actual payloads asus service sends to the device. As new Vivobooks seem to use different protocol completely :)

**Comment by gbassani** [comment]
> @gbassani hello, thanks for checking. As I have explained in a [comment above](https://github.com/seerge/g-helper/issues/2973#issuecomment-2294867113) i need someone to record actual payloads asus service sends to the device. As new Vivobooks seem to use different protocol completely :)

Working on this--spinning up a sandboxed installation. I'll use that tool after clean install prior to installing MyAsus to use the windows dynamic lighting and then will try after installing MyAsus for a second file. Command Interface v3 will be installed for both prior.

**Comment by seerge** [comment]
@gbassani hello, thanks.

Your log contains only 2 commands, just for toggling backlight brightness, but both of them are already in G-Helper since the very beginning (and as I understand it works for you anyway)

```
0x0050021 -> 0x03 ON
0x0050021 -> 0x83 OFF
```

What I need is a payloads for changing backlight modes using Asus software :)

**Comment by Wyrddann** [comment]
Hi! I also have this same issue with my TUF A15 2023.

**Comment by seerge** [comment]
@Rooie100 @gbassani @Wyrddann 

Also please check if this build accidentally makes any difference (as someone in other thread has[ helped me with discovering](https://github.com/seerge/g-helper/discussions/2996#discussioncomment-10404763))

[GHelper.zip](https://github.com/user-attachments/files/16689397/GHelper.zip)

**Comment by gbassani** [comment]
@seerge From what I can tell, there is not a way to change the keyboard colors from within the MyAsus app, I have only been able to through personalization/dynamic lighting for the vivobook. 

I can try installing the ROG lighting control app and see if that lets me, otherwise I might be stuck. Tried the new build and no luck there, if I turn the dynamic lighting off I get static white regardless of settings in ghelper. 

As for the log I uploaded, that was all that was captured when toggling in dynamic lighting for colors, brightness, lighting behavior (static to breathing) and the rate of the effect (faster/slower breathing). The behavior is different with these builds, I can't even get the breathing to work on static blue like I had originally.

Going to stick without g-helper for now, let me know if there are any other logs you'd like me to attempt if anyone else is requesting the new vivobook.

**Comment by seerge** [comment]
@gbassani so you can't change backlight using Asus apps ? Then G-Helper won't be able to do that neither as it relies on Asus endpoints / protocols. You have Vivobook so ROG apps won't work on your device.

If the only "official" way to control backlight on your device is by using Dynamic Lighting - then you should just use that.

**Comment by seerge** [comment]
@gbassani P.S. What you can try to do - is to change backlight modes using Dynamic Lighting and try to capture that with the ACPI tool (in case dynamic lighting uses some asus endpoints)

**Comment by gbassani** [comment]
> @gbassani P.S. What you can try to do - is to change backlight modes using Dynamic Lighting and try to capture that with the ACPI tool (in case dynamic lighting uses some asus endpoints)

Unfortunately, that is what I had done to generate the measly 2 rows above, for some reason it only captured the brightness change when I hit the F4 key. If I get around to it later, I'll try again with no filter just to skim the output and see if there are any lines that appear at all from the driver.

Thank you for spending the time troubleshooting.

**Comment by seerge** [comment]
@gbassani if that's the only output you see - then it means that Dynamic Lighting uses some other **absolutely unknown** protocol to change backlight (since asus own apps also can't change it).

Without having physical access to your device it unrealistic to reverse-engineer that unfortunately.

Also, why exactly do you want to change backlight specifically from G-Helper if you have windows native way of doing that ?

**Comment by lazer15** [comment]
Here is a capture of pressing keyboard backlight (F4) key and the brightness keys (F5 and F6). 
[KB_BL_Monitor_BL_P16.zip](https://github.com/user-attachments/files/16694173/KB_BL_Monitor_BL_P16.zip)

I first changed screen brightness a couple times then did the keyboard backlight up and down a few times.

This is on a proart P16 with cpu 370 HX. I have the same issue as OP. If I stop MyAsus services I lose the ability to control screen brightness and keyboard backlight.

Let me know if I can help with another capture.

**Comment by seerge** [comment]
@lazer15 hello, thanks for capturing. 

I don't think that your case is same as OP's. As for him it's backlight mode toggle (i.e. breathing / color-cycle, etc) that doesn't work. He can control backlight brightness (with one small tweak) and could control screen brightness from the beginning :) 

For your case - it looks more like system doesn't notify G-Helper about hotkeys being pressed at all. 

As in the log i see only actual hotkey commands (using `0x00100021` endpoint) and G-Helper already knows and handles them
https://github.com/seerge/g-helper/blob/8b66e95b8bd2403a11a15a697152924ad796b27b/app/AsusACPI.cs#L38

- What is the native way of changing **backlight mode** on your device (using asus apps, or windows, or somehow else?)
- Can you try to **restart G-Helper after stopping asus services**, does something change for backlight brightness / screen brightness hotkeys ?
- Upload an app log from `%appdata%\GHelper`

**Comment by lazer15** [comment]
The brightness is changeable through the windows settings app in the display section using the native slider that is there. The myasus app doesn't have any brightness control sliders or toggles for the keyboard or monitor. I also checked the asus creator hub application but it doesn't have any brightness controls for monitor or keyboard.

I launched ghelper then stopped asus services. This caused the monitor brightness keys and the keyboard backlight hotkey to stop working. I then restarted ghelper. The brightness hotkeys for the monitor then started working. Keyboard backlight keys remain unresponsive. I do get the toast message popping up saying backlight off, mid, high but no physical changes to the keyboard light.
[p16_log.zip](https://github.com/user-attachments/files/16694507/p16_log.zip)

**Comment by seerge** [comment]
@lazer15 my question was if you could change **keyboard backlight mode** (i.e static or breathing) asus apps ? 

As for for backlight brightness toggle (`F4` in your case), did you try the build I was linking in this thread above ?
[GHelper.zip](https://github.com/user-attachments/files/16625263/GHelper.zip)

**Comment by lazer15** [comment]
@seerge there is no option to change backlight mode in any asus app that's preinstalled. Maybe if I install armoury crate? That's not something that comes with this model though.

I tried the ghelper version you linked. Screen brightness hotkeys work but F4 keyboard toggle doesn't work. Only the ghelper keyboard backlight messages appear when pressing F4, no actual changes.

**Comment by seerge** [comment]
@lazer15 
> there is no option to change backlight mode in any asus app that's preinstalled. Maybe if I install armoury crate? That's not something that comes with this model though.

Then most likely it doesn't support mode changing at all :) So obviously G-Helper won't make a difference here

>I tried the ghelper version you linked. Screen brightness hotkeys work but F4 keyboard toggle doesn't work. Only the ghelper keyboard backlight messages appear when pressing F4, no actual changes.

Can you post a log from it ?

**Comment by lazer15** [comment]
@seerge 
I'm only interested in changing the brightness of the keyboard light. The light patterns aren't of interest to me. Are you saying ghelper isn't able to change the keyboard brightness since this laptop model doesn't support keyboard light pattern modes? I know on startup it changes to breathing but once in windows it changes to solid. That's just how proart laptops are on boot up according to other people.
[test_log.zip](https://github.com/user-attachments/files/16694895/test_log.zip)

**Comment by seerge** [comment]
@lazer15 G-Helper should be able to change keyboard  backlight level.

The log you uploaded is not from the build I linked above tho, so no wonder it doesn't work.
Linking it again [GHelper.zip](https://github.com/user-attachments/files/16625263/GHelper.zip)

**Comment by lazer15** [comment]
@seerge 
I deleted all the ghelper versions I had. It
[log.zip](https://github.com/user-attachments/files/16695020/log.zip)
 should be the correct version now because I have no other versions anymore. I also cleared the appdata folder for ghelper.

**Comment by seerge** [comment]
@lazer15 hm, strange. Can you try this build ?

[GHelper.zip](https://github.com/user-attachments/files/16695110/GHelper.zip)

**Comment by lazer15** [comment]
@seerge 
[log.zip](https://github.com/user-attachments/files/16695137/log.zip)

**Comment by seerge** [comment]
@lazer15 ok, can you try this build instead ?

[GHelper.zip](https://github.com/user-attachments/files/16695195/GHelper.zip)

**Comment by lazer15** [comment]
> @lazer15 ok, can you try this build instead ?
> 
> [GHelper.zip](https://github.com/user-attachments/files/16695195/GHelper.zip)

@seerge 
It works! That one is a keeper. Brightness for both keyboard and screen are controllable with the hotkeys now. :thumbsup:

**Comment by seerge** [comment]
@lazer15 ok, great to hear

**Comment by seerge** [comment]
@lazer15 do I understand correctly that now everything is working as it should ?

**Comment by lazer15** [comment]
> @lazer15 do I understand correctly that now everything is working as it should ?

@seerge Fully functional now, no more issues for this P16 model.

**Comment by lazer15** [comment]
@seerge 
After restarting the laptop, keyboard light toggling stopped working. Restarting g-helper didn't have an effect. I had the asus services stopped earlier during the trial of the last test version you had me try. Not sure what happened.
[log2.zip](https://github.com/user-attachments/files/16695710/log2.zip)

**Comment by seerge** [comment]
@lazer15 can you try this build ? (and post a log)
[GHelper.zip](https://github.com/user-attachments/files/16697909/GHelper.zip)

**Comment by lazer15** [comment]
[log4.zip](https://github.com/user-attachments/files/16698050/log4.zip)

It works prior to rebooting like the last version for screen and keyboard hotkey brightness control. However the issue above is still triggered when rebooting. It remains stuck with the breathing pattern with keyboard hotkey not working (screen brightness keys fine) until launching myasus and selecting repair.

See the 12:42 onward point. That's when I installed the version you just posted.
12:51 is when I launched myasus and let it repair. The keyboard hotkey starts working again.
I then stopped the asus processes with ghelper.

**Comment by seerge** [comment]
@lazer15 the only thing repair in myasus does - is just starts asus services :)

As for the rest - it's not the hotkey not working, it's probably keyboard backlight needs some special initialization command prior to using (this is what asus service sets on start)

I have tried to copy ROG init command in last build, which apparently didn't help
Try this one 
[GHelper.zip](https://github.com/user-attachments/files/16698132/GHelper.zip)

If it doesn't work still, please check if just starting asus services via g-helper `Extra` menu fixes it in a same way as repair in myasus (to confirm assumption)

**Comment by lazer15** [comment]
@seerge 
Pressing start asus services under extras does cause breathing mode to stop and the keyboard to change to static. Brightness hotkey then starts working. If I then stop the asus services in ghelper, the hotkey continues working.

At 1:08 I installed the new version you suggested. I then restarted the computer to make the breathing problem happen again.
[log5.zip](https://github.com/user-attachments/files/16698231/log5.zip)

**Comment by seerge** [comment]
@lazer15 then we need to intercept "init" command for keyboard. Unlike Vivobooks it's controlled via USB same as on ROG devices (that's what i did in a first place to make backlight controls work for you)

Posting a guide on how to capture (from other thread)
----


Install https://www.hhdsoftware.com/device-monitoring-studio (will require reboot)

0. Boot w/o asus services running (i.e. with keyboard blinking)

1. Launch Monitoring Studio, pick **Asus** device with Product ID `0x19B6` from the list and double click on it
![Screenshot 2024-01-20 163125](https://github.com/seerge/g-helper/assets/5920850/e9a28802-08cb-423c-812b-7b526b051a5f)

2. Add ``Packet View`` to Procesing and click ``Start``
![Screenshot 2024-01-20 163136](https://github.com/seerge/g-helper/assets/5920850/354340f0-2fcb-473b-a49f-2e01b25d00a9)

3. Start Asus services (via MyASUS or G-Helper)

4. Check if Monitoring Studio catching data. If NOT - you probably have selected wrong Asus device on step 2 (so need to re-do it)

5. In Monitoring Studio select ``Tools`` -> ``Save to Log``, and save data
![Screenshot 2024-01-20 163247](https://github.com/seerge/g-helper/assets/5920850/ad480dcf-05bc-43a7-9a80-2984fb68e8a8)

Upload this data here. 

Thanks

**Comment by lazer15** [comment]
@seerge 
Do I need to turn off secure boot to use that tool?

**Comment by seerge** [comment]
@lazer15 no, it's not that low level as ACPI :) it just intercepts all USB traffic between laptop and USB device (like your internal keyboarD)

**Comment by lazer15** [comment]
@seerge 
It appears to cost $165 for standard. Or does it have a free mode that's adequate?

**Comment by seerge** [comment]
@gbassani it's a free trial, just click download. You don't need to pay anything of course

**Comment by seerge** [comment]
@lazer15 that's quite strange, as usb device is 100% there (g-helper can see it). May be try to reboot ? :|

**Comment by lazer15** [comment]
@seerge 
I think I found it. It is actually that ITE device. I just found how to get the device id information to appear. It matches step 1's id.
![Found](https://github.com/user-attachments/assets/061aa13d-975d-478d-8597-e226c0dc6319)

[Blink_service_start.zip](https://github.com/user-attachments/files/16700662/Blink_service_start.zip)

**Comment by seerge** [comment]
@lazer15 ok, great!

There is indeed some new init commands there

Try this build (and post a log)
[GHelper.zip](https://github.com/user-attachments/files/16708302/GHelper.zip)

**Comment by lazer15** [comment]
@seerge 
After rebooting it continues to be stuck on the breathing pattern.
[log_init.zip](https://github.com/user-attachments/files/16714393/log_init.zip)

**Comment by seerge** [comment]
@lazer15 hmm, strange. I have copied full payload from your capture now, try this build 

[GHelper.zip](https://github.com/user-attachments/files/16715285/GHelper.zip)

**Comment by lazer15** [comment]
@seerge 
Tried the new one. Same issue.
[loginit2.zip](https://github.com/user-attachments/files/16715340/loginit2.zip)

**Comment by seerge** [comment]
@lazer15 ok, one more attempt
[GHelper.zip](https://github.com/user-attachments/files/16715647/GHelper.zip)

As for your other questions.
- Mode is always applied on app start. When you click mode again - it applied again.
- Battery limiter resets on reboot, and is applied when app starts. It's normal that battery will be charging during boot + windows logon

**Comment by lazer15** [comment]
@seerge 
No luck with that build.
[log3.zip](https://github.com/user-attachments/files/16716841/log3.zip)

**Comment by seerge** [comment]
@lazer15 from the log it looks like you

1. Start "new" build first (it sends all init commands)
2. Reboot
3. On windows start **old build starts** (cause startup task still points to old exe) and it doesn't send init commands cause they are not there

Can either replace your usual GHelper.exe with a new build, or just run a new build from any location - but uncheck and check "Run on startup" ? (it will re-create startup task pointing to that exe)

**Comment by lazer15** [comment]
@seerge 
That was the issue. I didn't realize I should have been unchecking run at startup when switching between test versions. 

My mistake:
I had been quitting (with run at startup still checked) -> launching the new test version -> ensure run at startup was checked -> restart computer -> check if keyboard is still breathing -> push backlight buttons -> get log.

Changed to:
Uncheck g-helper run at startup -> quit g-helper -> launch new g-helper -> check run at startup -> uncheck run at startup -> quit g-helper -> restart g-helper -> check run at startup -> reboot computer -> get log


The latest version works.

> @lazer15 ok, one more attempt [GHelper.zip](https://github.com/user-attachments/files/16715647/GHelper.zip)
> 
> As for your other questions.
> 
>     * Mode is always applied on app start. When you click mode again - it applied again.
> 
>     * Battery limiter resets on reboot, and is applied when app starts. It's normal that battery will be charging during boot + windows logon

I cleared the log for this retest the EXEs from today.

> @lazer15 ok, one more attempt [GHelper.zip](https://github.com/user-attachments/files/16715647/GHelper.zip)
> 
> As for your other questions.
> 
>     * Mode is always applied on app start. When you click mode again - it applied again.
> 
>     * Battery limiter resets on reboot, and is applied when app starts. It's normal that battery will be charging during boot + windows logon

The latest version works.
[loglatest.zip](https://github.com/user-attachments/files/16719031/loglatest.zip)


> @lazer15 hmm, strange. I have copied full payload from your capture now, try this build
> 
> [GHelper.zip](https://github.com/user-attachments/files/16715285/GHelper.zip)

I also just retested this one. This one doesn't work. Stuck with the breathing pattern.
Here's a log.
[log init 2.zip](https://github.com/user-attachments/files/16719082/log.init.2.zip)



> @lazer15 ok, great!
> 
> There is indeed some new init commands there
> 
> Try this build (and post a log) [GHelper.zip](https://github.com/user-attachments/files/16708302/GHelper.zip)

Here is a log from retesting this one:
[log init 1.zip](https://github.com/user-attachments/files/16719149/log.init.1.zip)
That one works.

**Comment by seerge** [comment]
@lazer15 ok, great! To keep it simple - when you  use latest version all the time - everything works as it should?

**Comment by lazer15** [comment]
@seerge 
Yes the latest works fine. Should I use that one? I am not sure if the 1st one is preferable for some reason. "init 3" is the latest one. "init 1" was the 1st one I tried today.

[GHelper init 1.zip](https://github.com/user-attachments/files/16719199/GHelper.init.1.zip)

[GHelper init 3.zip](https://github.com/user-attachments/files/16719198/GHelper.init.3.zip)

**Comment by seerge** [comment]
@lazer15 no, you don't need to test old ones. Last one is definitely correct :)

--------

Ssince you are already can record USB. Can you try to capture one more payload (not related to backlight but to FN-Lock)

1. Start all asus services
2. Quit G-Helper
3. Capture what asus services send to keyboard when you press `FN + ESC` (that toggles hardware fn-lock on your device) ?

**Comment by lazer15** [comment]
@seerge 
Do you want me to do reboot the computer prior to pressing FN + ESC? Or does that not matter here?

**Comment by seerge** [comment]
@lazer15 it doesn't matter

**Comment by lazer15** [comment]
@seerge 
Here you go. FN+ESC is hardware fn-lock on the this device.
[FN_esc.zip](https://github.com/user-attachments/files/16719282/FN_esc.zip)

**Comment by seerge** [comment]
@lazer15 ok, amazing.

Apparently part of "init" payload you recorded before was setting FN-lock OFF on device start (logical). So I have cleaned up "init" from that and also added hardware fn-lock handling in g-helper (before it was software imitation as app can do for any other device that doesn't have native fn-lock)

Can you try this build w/o any asus services and check if
- FN lock works fine
- You can still reboot and backlight controls still work fine ?

[GHelper.zip](https://github.com/user-attachments/files/16727844/GHelper.zip)

**Comment by lazer15** [comment]
@seerge 
FN-Lock works with that new version. Backlight keys also fine.

On the prior version I was able to toggle FN-Lock on and off without issue. On reboot it would default back to FN-Lock OFF which matches up with what you described the payload said.

Here's a log if needed:
[logFN_Lock.zip](https://github.com/user-attachments/files/16730020/logFN_Lock.zip)

**Comment by seerge** [comment]
@lazer15 ok, amazing

In "old" versions FN-lock was imitated on software level. There is a downside that when it's ON and you press FN+F1 for example, it would still emit special function (mute).

In "new" version FN-lock is handled by hardware (g-helper is not involved). So I assume when it's ON an you press FN+F1 it should just emit regular F1 key.

**Comment by lazer15** [comment]
@seerge 
Great, thanks for the updates to support this model👍 

Do you know how to uninstall irpmon? When I ran the uninstaller, it said the uninstall was incomplete and components would need to be removed manually. It didn't say which components were left behind though. Maybe you've tried to uninstall it before after testing at some point?

**Comment by seerge** [comment]
@lazer15 i think that's enough. At least I did same, also got same message and never had any issues after (including gaming)

You can enable back secure boot if you want after :)

Btw in latest builds I have also added an option to udnervolt Ryzen 9 AI (migrated latest changes from the UXTU library that g-helper uses under the hood for undervolting), so if are interested you can test if it works as well.

**Comment by lazer15** [comment]
@seerge 
I see so it wasn't just me with that incomplete uninstall error. That's all I was trying to check. That's good. Yeah I put secure boot back on after uninstalling.

Sure I can try the new changes. I assumed that tab wasn't present in g-helper for me because maybe the proart line doesn't support it despite having the same processor as G14/G16. I was trying to improve battery life so some undervolting would be good.
