### ISSUE TITLE
Adding options for updates

### ISSUE THREAD

**Issue by amartyaksinha-UC** [seerge/g-helper#2976]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

First up, I absolutely love G-Helper and cannot imagine using my 2022 Flow X13 without it. Cannot thank seerge and anyone else who has helped create and maintain the project enough. The only minor annoyance I have with the software is that each time an update is available, it will remind me every other time the laptop wakes up from sleep or at each reboot. I understand updates are often important and even necessary, but thanks to the excellent changelog on its Github's releases page, I like to see if it's relevant to my device at all, and then decide to actually download the update and replace the .exe file in my local G-Helper's directory.

### Describe the solution you'd like

In the "Extra" menu, an option to toggle update reminders on/off would be helpful. I don't think disabling updates entirely is a good idea, so there could be an option to remove update reminder for a day, a week, 2 weeks, a month, 2 months and up to 3 months at most, which is a good limit in my opinion. Also, the latest available version should continue to be indicated in the G-Helper window itself through the red text.

Additionally, it would be great if the changelog for each update would show along with the dialog box informing that version 0.1xx is now available to download. Thank you!

### Device and Model

Asus ROG Flow X13 GV301RE

**Comment by seerge** [comment]
@amartyaksinha-UC hello,

You see update notification only once per each **new final release** (intermediary releases don't trigger that). If you click NO - app remembers that, and won't offer to update untill next final release (that usually happens once in 2-4 weeks atm)

This is absolutely intentional as I want everyone use latest version of the app. As majority don't read release notes or check for update on github. 

So I don't plan to change that. Sorry

Thanks
