### ISSUE TITLE
Ambient keyboard lighting mode flickering

### ISSUE THREAD

**Issue by DeyyuZ96** [seerge/g-helper#2977]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When switching the keyboard lighting mode to Ambient it works but also flickers a lot.

### How to reproduce the bug?

1. Open G Helper
2. Set Keyboard lighting mode Ambient
3. Et voila

https://github.com/user-attachments/assets/3ce59b9e-ebf7-485f-9d12-f058ded17072

### Logs

[log.txt](https://github.com/user-attachments/files/16617114/log.txt)

### Device and Model

Asus ROG Strix G15 (2022)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.184.0

### OS

Windows 11 23H2 BIOS 327

**Comment by seerge** [comment]
@DeyyuZ96 hello, this is due to hardware (or firmware) limitations of your specific model.

Unfortunately G513 series does not support dynamic changes of keyboard backlight color (so called "direct" mode). 
https://github.com/seerge/g-helper/blob/338a5e85f4e6dad40044a1d10285f592c35940b8/app/AppConfig.cs#L488

So what G-Helper is doing specifically for your model - it literally sets "Static" backlight mode few times a second each time with updated color. On some devices it flickers, on some - it doesn't.

I'm afraid i can't do anything here :) so if it flickers - don't use Ambient.

Sorry. Thanks.

**Comment by DeyyuZ96** [comment]
Hi,I have been using Ambient for a while and 2 versions ago (of GHelper) it
had not problem. I haven't got a bios update that might break it so I'm not
sure what happened.

**Comment by seerge** [comment]
@DeyyuZ96 as I mentioned on some devices it flicker on some it doesn't. 

But in the app itself nothing has changed in this regard, :) Try older versions if you like - does it behave same ?

If so - something has changed with keyboard itself, if it didn't flicker before. May be [hard reset ](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset)would help?

**Comment by DeyyuZ96** [comment]
I'll try everything you mentioned & come back with a result.

**Comment by DeyyuZ96** [comment]
Tried hard reseting,uninstalling & reinstalling the Asus System Control
Interface & went back to 3 older GHelper versions (0.179, 0.178 & 0.176)
and nothing,still flickers.

Weird as the first version I used where I firstly used ambient and it
worked properly was 0.178. It's weird but thanks for taking your time to
respond to my "issue".

Have a great day and hope I didn't disturb anyone.

**Comment by seerge** [comment]
@DeyyuZ96 it updates backlight color only when color itself changes, so if you just steer at a static screen - it won't change and won't flicker ;) Or it could be you just didn't pay attention to flickering before ...
