### ISSUE TITLE
Custom config gone/ reset to default after rebooting

### ISSUE THREAD

**Issue by MadCreeper** [seerge/g-helper#2978]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

After shutting down laptop and restarting, all config like fan curves, wattage limits, RGB settings all got reset to default.

### How to reproduce the bug?

It doesn't necessarily reset every time, but this week I reboot it every day and it happened to me twice already.

### Logs

[log.txt](https://github.com/user-attachments/files/16620990/log.txt)

### Device and Model

ROG Strix G834JZ

### Armoury Crate

Installed

### Asus Services

7

### Version

0.183

### OS

Win11 10.0.22631

**Comment by seerge** [comment]
@MadCreeper hello,

It means that system by some reason has interrupted app in the middle of saving something in own config, and therefore just making that config unreadable after.

App already has a method preventing that form happening with a backup config, but if I have extended this approach a bit, so hope it helps.

Try this build

[GHelper.zip](https://github.com/user-attachments/files/16623634/GHelper.zip)

Thanks

**Comment by seerge** [comment]
hello, I have added some tweaks, to improve config saving in some unpredictable situations in the latest release https://github.com/seerge/g-helper/releases/tag/v0.193 

Let me know if it improves something for you :)
