### ISSUE TITLE
[feature request] windows mode for performance mode

### ISSUE THREAD

**Issue by privacyonly** [seerge/g-helper#298]
**Is your feature request related to a problem? Please describe.**
in armory crate we can choose windows mode for power mode(performance mode in your program).

**Describe the solution you'd like**
please put a windows mode in your program so we can use default windows power profile.

**Describe alternatives you've considered**

**Additional context**

**Comment by seerge** [comment]
Windows mode in armory is ‘performance’ mode + default (balanced) windows power plan. Since g-helper relies on default power plan in all modes , it’s not needed. Just use ‘Balanced’ in g-helper, its same thing.
