### ISSUE TITLE
Zephyrus G14 (2022) sPPT and fPPT options

### ISSUE THREAD

**Issue by Keiszer** [seerge/g-helper#2982]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Not exactly a problem, but I have noticed that 2023 and 2024 models of the G14 have access to multiple different PPT options. These options are available in other tuning utilities (like UXTU) so I am fairly sure that the separate PPTs are available for the 2022 G14, but is simply not implemented in G-Helper.

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/a1c22db6-bb24-43c1-a1d1-0c27afde15ac)
Similar to the image above (from an older version of G-Helper on a 2023 G14), to have separate sustained and boost PPT options is what I am requesting.

### Describe alternatives you've considered

I have considered using UXTU to adjust the PPTs in conjunction with the power settings, but because G-Helper and UXTU do not use power plans in the same way (as far as I am aware) the automation does not work the way I would like it to--plus, having two sets of power limits is confusing to keep track of.

### Device and Model

Asus Zephyrus G14 GA402RJ

**Comment by seerge** [comment]
@Keiszer hello, it's simply not possible. 

G-Helper gives you access to the options already available on your device. On All-AMD models you can set Platform power limit and CPU power limit in Armoury Crate, and therefore you see same options in G-Helper.

Thanks.
