### ISSUE TITLE
G-Helper window opens out of display after move+close with external monitor

### ISSUE THREAD

**Issue by thephluxer** [seerge/g-helper#2983]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I have an external display on my Laptop and I move the G-Helper window to the secondary Monitor and then close it, it won't show up when I try to open it again with the hotkey.
It shows in the taskbar so the window opens somewhere but it's not on any of the Monitors.
Restarting G-Helper fixes the problem.

Idk if the info is relevant, but I connected the external Monitor via the HDMI port and it is an ultrawide monitor with a resolution of 3440x1440.

### How to reproduce the bug?

1. Have the Desktop extend to a secondary Monitor
2. Open G-Helper window
3. Move the G-Helper window to secondary Monitor
4. Close G-Helper window
5. Try to open G-Helper window again

### Logs

[log.txt](https://github.com/user-attachments/files/16637273/log.txt)

### Device and Model

Asus Zephyrus G16 GU605MZ

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.184.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@thephluxer hello,

I actually can't reproduce that. And I have pretty much same setup (external monitor is my main tho)

Every time main app window is shown it actually (re)-positions itself in the bottom right corner 
https://github.com/seerge/g-helper/blob/50f0c82b701ae350eb5959928e24b488be25b322/app/Program.cs#L286

How do you close and open G-Helper window ?

**Comment by thephluxer** [comment]
Hi @seerge,

it doesn't matter how I open and close it. I usually use the Armoury Crate key, but I also can't open it via the tray icon and it also breaks when I close it with the top right X-button.

My Laptop Monitor is my main though FYI.

**Comment by thephluxer** [comment]
> https://github.com/seerge/g-helper/blob/50f0c82b701ae350eb5959928e24b488be25b322/app/Program.cs#L286

I don't know the API so it's just an idea but:
If the WorkingArea.Width somehow returns the width of the second screen, but the window uses these coordinates to position the window on the main screen, it would land outside of the visible screen area.

I just tested the theory and indeed, when I set the resolution of the second monitor to a 16:9 ratio i can open and close the window without any problem.

**Comment by seerge** [comment]
@thephluxer try if this build makes a difference

[GHelper.zip](https://github.com/user-attachments/files/16638416/GHelper.zip)

**Comment by seerge** [comment]
@thephluxer i have also noticed that before your comment, so I have added second screen X coordinate into calculation
https://github.com/seerge/g-helper/commit/e6767126c93bfe96527c0ec6fa85bb81849a8ffe

**Comment by thephluxer** [comment]
> @thephluxer try if this build makes a difference
> 
> [GHelper.zip](https://github.com/user-attachments/files/16638416/GHelper.zip)

Ok funny behavior:

At first the same issue occurs, the window opens but out of bounds.
But when I close it again via hotkey and then open it again, it shows up correctly.

So it seems it still determines the coords to reopen from the screen it was on when closed.

**Comment by thephluxer** [comment]
> Theoretically it could be similar situation, if you align 2 screens vertically, so even Y coordinate needs to be included, but i'm not sure if someone is doing that ...

The screens are indeed vertically aligned, the second screen is above the main laptop screen.

**Comment by seerge** [comment]
@thephluxer ok, try this build that includes Y coordinate as well
[GHelper.zip](https://github.com/user-attachments/files/16638474/GHelper.zip)

**Comment by thephluxer** [comment]
@seerge 
I also have 125% scaling on the laptop monior and 100% scale on the secondary.
Idk if that matters but just fyi.

**Comment by seerge** [comment]
@thephluxer it looks like there is some hiccup in way windows manages forms and positions them.

I have tried to reproduce your case, and form Y position is negative here (as it's on top of main screen). I don't seem to be able to "fix" that anyhow.

But I can offer to position g-helper's window always on primary screen when you reopen it (as it's logical and next to tray icon)

**Comment by thephluxer** [comment]
> But I can offer to position g-helper's window always on primary screen when you reopen it (as it's logical and next to tray icon)

Yeah, that was the default behavior I expected tbh.
Just always reopen it at the same position bottom right on the main screen.

**Comment by seerge** [comment]
@thephluxer ok, try this build then
[GHelper.zip](https://github.com/user-attachments/files/16638664/GHelper.zip)

**Comment by thephluxer** [comment]
That works!

**Comment by seerge** [comment]
Great, thanks for spotting. Even tho it's quite exotic case.
