### ISSUE TITLE
GHelper Crashes Asus Zephyrus G14

### ISSUE THREAD

**Issue by CodingGenius0001** [seerge/g-helper#2984]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I enable AMD Display VariLight through GHelper Application, the computer BSOD's with the error phrase as "SYSTEM_SERVICE_EXCEPTION" and error code 0x0000003B

### How to reproduce the bug?

1. Open the GHelper Application
2. Click on Extra
3. Enable AMD Display VariLight
4. PC crashes

### Logs

[log.txt](https://github.com/user-attachments/files/16638056/log.txt)

### Device and Model

Asus Zephyrus G14 2024 GA403UI

### Additional information.

Error code: 0x0000003B

Description:
This BSOD means that an exception happened while executing a routine  that transitions from non-privileged code to privileged code. BSOD  error code 0x0000003B may also show "SYSTEM_SERVICE_EXCEPTION" on the  same blue screen.

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.184.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@CodingGenius0001 hello,

App uses official AMD API to read (and optionally change) Varibright setting

https://gpuopen-librariesandsdks.github.io/adl/group__DISPLAYAPI.html
https://github.com/seerge/g-helper/blob/50f0c82b701ae350eb5959928e24b488be25b322/app/Gpu/AMD/AmdGpuControl.cs#L142

So it looks more like a driver hiccup in your case

- Do you use latest AMD driver (from Asus or from AMD)? 
- Are you able to change Varibright using Adrenaline app itself ?
- Did you try reinstalling them clean [using AMD cleanup utility](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers) ?

**Comment by CodingGenius0001** [comment]
Hello again!

These are my findings...

1. I am on the latest AMD drivers (Version 31.0.22060.5000 - according to AMD's official website) and Version 23.20.60.05 on AMD Adrenaline app

2. Yes I am able to change Varibright through the app itself.

3. Yes I tried reinstalling using setup utility, but the issue persists

-------------------------
Now, after much experimentation this is what I found out:

When I am on the iGPU (AMD Radeon 780M Graphics) and enable Varibright through the GHelper application.
BUT when I switch to the dGPU (NVIDIA RTX 4070 Laptop GPU) and then enable Varibright, the laptop bluescreens with the error code I mentioned earier.

So it seems to be something with the NVIDIA GPU. I have verified that I am on the latest version according to NVIDIA's driver website.

I am still unsure what is causing this problem

**Comment by seerge** [comment]
@CodingGenius0001 what exactly do you understand under switching to dGPU ? Is it via NVida Control Panel / Optimus or just setting `Standard` / `Eco` in G-Helper ?

Cause I had G14 2024 for some time, and I didn't get any crashes. Also you are the first one to mention this.

**Comment by CodingGenius0001** [comment]
I have switched to dGPU through both methods: 
1. Through the NVIDIA control panel under the Manage Display Mode Tab and selecting NVIDIA GPU only 
2. Through GHelper by switching from iGPU (Eco) to dGPU (Standard)

Both methods successfully switch over to the GPU. So I am assuming that AMD Varibright is not supported while on the laptop GPU

I am attaching a video for evidence of this issue happening within this comment.
(This method uses the NVIDIA control panel to switch over to the dGPU and then switching on Varibright through the GHelper app)

[Issue.zip](https://github.com/user-attachments/files/16647226/Issue.zip)
P.S Had to zip the file because it was too big for GitHub 

Will try moving over to the AMD drivers from Asus and update you soon.
Hope this helps!

**Comment by seerge** [comment]
@CodingGenius0001 hello, ok.

Just in case Standard / Eco (it just enables dGPU in general) is not the same as Optimus / Nvidia Only. As I understand you need to set both Standard and Nvidia GPU at the same time.

What happens if you would try to set Varibright via Adrenaline after you select Nvidia GPU only ? Does it even allow that option?

And let me know if Asus drivers make any difference. You will need to use [AMD Cleanup utility](https://www.amd.com/en/resources/support-articles/faqs/GPU-601.html) to roll back to older driver

**Comment by CodingGenius0001** [comment]
When on iGPU, the AMD Adrenaline software shows the display tab under Gaming:
![image](https://github.com/user-attachments/assets/c1b2c536-c6d5-4e62-b1e9-25da1d5abdd3)

But when on dGPU, the AMD software does not show this tab and the option for Varibright is not seen.
![image](https://github.com/user-attachments/assets/afb079cb-0e52-4a4a-b89e-b462aa5d47fc)

I believe Varibright is not supported on dGPU and only on iGPU.

Rolling back to the older drivers does not make a difference and the issue still persists.

**Comment by seerge** [comment]
@CodingGenius0001 ok

Try this build,

I have added an extra check and it will skip VariBright call when NVidia GPU is driving internal screen (i.e. you have selected "NVidia GPU Only" in Display Mode)

[GHelper.zip](https://github.com/user-attachments/files/16647698/GHelper.zip)

**Comment by CodingGenius0001** [comment]
Yes. this build works! 

Thank you!

**Comment by seerge** [comment]
@CodingGenius0001 ok, great
