### ISSUE TITLE
"Looks like GPU is in heavy use, disable it?" while gaming with XG Mobile

### ISSUE THREAD

**Issue by moritzbeck13** [seerge/g-helper#2985]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I try to play graphic intensive games on my XG Mobile 6850XT, every other minute I get a pop-up saying `Looks like GPU is in heavy use, disable it?`. Additionally, the mode automatically changes from `Turbo` to `Balanced`, slowing my game down considerably. This happens even before I click `Yes` or `No` in the pop-up. I have to click `No` and change mode back to `Turbo`, but can then continue playing for another minute or two before the message pops up again.
It seems to be loosely related to GPU temp, but not utilization. Temp levels out around 86 °C, fan speed should be about 5000 RPM according to the fan curve.

### How to reproduce the bug?

1. Connect XGM
2. Set mode to `Turbo`
3. Start GPU heavy game
4. Wait for XGM to heat up?

### Logs

[log.txt](https://github.com/user-attachments/files/16640689/log.txt)

### Device and Model

Flow X13 2022 GV301RE, XG Mobile 6850XT

### Additional information.

Trace seems to be:
https://github.com/seerge/g-helper/blob/main/app/Program.cs#L265
https://github.com/seerge/g-helper/blob/main/app/Settings.cs#L684
https://github.com/seerge/g-helper/blob/main/app/Gpu/GPUModeControl.cs#L232
https://github.com/seerge/g-helper/blob/main/app/Properties/Strings.resx#L132
But no clue where the `PowerModeChanged` event might come from.

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

0.184.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@moritzbeck13 hello, your problem is not in this popup. Laptop constantly switches to battery power (under heavy load?), and windows notifies G-Helper about that as well

```
16.08.2024 20:48:01: WMI event 123
16.08.2024 20:48:01: WMI event 87
16.08.2024 20:48:01: AutoSetting for Offline
```

So app simply does what it's programmed to. You have `Optimized` mode, it's supposed to turn GPU off when unplugged, but since it sees GPU in heavy use it doesn't do that and just shows a warning.

I don't know why device goes to battery power. Could be either your XGM is failing to deliver enough power, or laptop uses too much ?

I see that you use quite high CPU power limits, try to lower them
```
16.08.2024 20:47:55: PowerLimit A3 = 75 : OK
16.08.2024 20:47:55: PowerLimit A0 = 75 : OK
16.08.2024 20:47:55: PowerLimit C1 = 75 : OK
```

Besides that I can't do much, as this is not a G-Helper's problem but rather hardware / firmware :)

Thanks

**Comment by moritzbeck13** [comment]
> So app simply does what it's programmed to. You have Optimized mode, it's supposed to turn GPU off when unplugged, but since it sees GPU in heavy use it doesn't do that and just shows a warning.

I don't think `Optimized` mode should try to switch to `Eco` while the XGM is connected. You can't even enable the XGM while in `Eco` mode or manually switch GPU mode while the XGM is connected. So I think it's only logical if that also wouldn't work like it currently does.

> I see that you use quite high CPU power limits, try to lower them

I have changed the power limit and boost settings, but that does not seem to fix the issue.

> I don't know why device goes to battery power. Could be either your XGM is failing to deliver enough power, or laptop uses too much ?

I think your hypothesis is right though. I can see that my device goes from charging to discharging at some point.

Would adding a `charger_delay` change this behaviour? What is the WMI event ID for going back to main power, 123?

**Comment by seerge** [comment]
@moritzbeck13 as I have mentioned problem is not in G-Helper and it's automations. If power goes off - even on firmware level performance would drop (cause on battery laptop automatically limits it's power). Even if you would stay on same mode.

I assume you didn't have this behavior before, and now it started happening ? Looks more like some hardware problem

**Comment by moritzbeck13** [comment]
> I assume you didn't have this behavior before, and now it started happening ? Looks more like some hardware problem

Possible, but I used to only play games that probably were CPU limited. I have now picked up a game where my GPU is at 100% all the time, so I think it might be more related to that.

> Does it happen if you would play on Balanced ?

Will try and report back.

> If power goes off - even on firmware level performance would drop (cause on battery laptop automatically limits it's power). Even if you would stay on same mode.

I can acknowledge that, but that wouldn't be as big of an issue for me. While not ill-intended, the pop-up is really annoying. I have to tab out, click `No` and tab back in every other minute. It really disrupts the flow of the game. I wouldn't mind dropping some frames for a second or two though.

**Comment by seerge** [comment]
For popup just keep gpu mode on `Standard` and no switching would happen.

Popup is absolutely intentional, to prevent accidental GPU switching during use on switching to battery power. And this is exactly what happens in your case due some hardware (or firmware) malfunction.

**Comment by moritzbeck13** [comment]
> For popup just keep gpu mode on `Standard` and no switching would happen.

But as I said; when the XGM is connected, no automatic switching should happen if manual switching isn't even allowed.

> Popup is absolutely intentional, to prevent accidental GPU switching during use on switching to battery power.

Isn't the `charge_delay` exactly for this scenario? It just doesn't seem to work with the XGM.

**Comment by seerge** [comment]
@moritzbeck13 it's charge**r**_delay

https://github.com/seerge/g-helper/wiki/Power-user-settings#plugged-in--on-battery-actions-delay
```
"charger_delay" : 1000,
```

But to underline again - your problem is not in this automations. Your device switches by itself runs from battery power from windows / firmware standpoint with absolutely different power settings.

**Comment by seerge** [comment]
@moritzbeck13 this build will run an extra check for a connected XGM when disabling GPU in optimized mode to prevent a popup. 

[GHelper.zip](https://github.com/user-attachments/files/16645372/GHelper.zip)
