### ISSUE TITLE
Possible to completely disable Asus Splendid?

### ISSUE THREAD

**Issue by Eckoa** [seerge/g-helper#2986]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Being someone who does art/photography and likes to calibrate my displays myself my Asus Tuf a16 has been a nightmare on windows. Asus in their wisdom felt that they should constantly override any ICC profile you apply with their own from their "splendid" profiles and prevent you from loading any other profile & vcgt which in turn breaks windows auto color management and doing anything color managed on the internal display period.

### Describe the solution you'd like

Im wondering, would it be at all possible to disable JUST splendid and not mutilate the rest of the control drivers?? Im not very familiar with how to track down the who/what of files/services in windows as its not as straight forward as linux. While i feel the answer may be no this is likely the best place to ask in regards to Asus controls and windows. Just setting default/neutral doesnt actually disable splendid it just applies a "neutral" profile which still prevents self made icc profiles from being loaded.

### Describe alternatives you've considered

Ive found a way to "fix it" by breaking the Asus System Control Interface which it is integrated into by mounting the drive in linux and chopping it out of system32, blacklisting the driver from installing using group policy, and disabling all the services which breaks the drivers and makes ghelper not work but gives back control of the display.

### Device and Model

Asus Tuf A16

**Comment by seerge** [comment]
@Eckoa hello, if keep Visual Mode on Default, it won't call AsusSplendid on start so it is already "disabled" :) 

Just set it to default and then apply back your custom color profile / etc, it won't be overriden.

Thanks.

**Comment by Eckoa** [comment]
> @Eckoa hello, if keep Visual Mode on Default, it won't call AsusSplendid on start so it is already "disabled" :)
> 
> Just set it to default and then apply back your custom color profile / etc, it won't be overriden.
> 
> Thanks.

except thats not true, it still forces a "neutral" icc profile onto the display and i have been able to verify that does absolutely nothing with a colorimeter.

**Comment by seerge** [comment]
@Eckoa did you [uninstall AC ](https://github.com/seerge/g-helper/wiki/Requirements#recommendations-optional) ?

**Comment by Eckoa** [comment]
> @Eckoa did you [uninstall AC ](https://github.com/seerge/g-helper/wiki/Requirements#recommendations-optional) ?

ive removed everything ASUS from the machine, the only way i was able to stop it was by mounting the drive in linux and deleting the Asus system driver from system32 and blacklisting their reinstall using group policy

**Comment by Eckoa** [comment]
> @Eckoa AsusSplendid doesn't run by itself, it's not a service, it's just an executable.
> 
> It is launched either by Armoury service (that i assume is not there since AC is uninstalled), or if you change Visual Mode in G-Helper.
> 
> Are you sure your problems are due to AsusSplendid or not cause some AMD driver hiccup ?
> 
> You can manually delete AsusSplendid.exe and it will be gone forever, but this is not a task for G-Helper anyway :)

Im 100% sure its due to asus splendid as once i removed it from system32 and blacklisted the  Asus System Control Interface from being installed which causes splendid to be reinstalled/activated upon reboot the issue went away. Asus splendid is preventing windows color management from doing anything to the internal display.

Im wondering is there any way to simply block/disable it without forcing the user to mount the system elsewhere and break the functionality on purpose? having the control interface running at all seems to force the app to return unless you blacklist it.

**Comment by seerge** [comment]
@Eckoa there is no way to "disable" it, just stop it from launching it as I explained above. 

Thanks

**Comment by seerge** [comment]
There is also splendid config in `C:\ProgramData\ASUS\ASUS System Control Interface\ASUSOptimization\` folder somewhere, you can try to brake or erase it :)

**Comment by Eckoa** [comment]
alright, well seeing as removing those files doesnt work as i previously explained and Ive found a way to simply break the driver Ill just close this issue if there isnt interest in the functionality/a way to do it otherwise.

**Comment by seerge** [comment]
@Eckoa if you completely disable driver that can cause more issues :) You can block AsusSplendid.exe from running in that folder i pointed out `C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_9b2f1b4e956514ee\ASUSOptimization\` 

OR 

You can just erase splendid config (usually named same as your username in windows) located in `C:\ProgramData\ASUS\ASUS System Control Interface\ASUSOptimization\` . Then AsusSplendid.exe even if launched won't do anything

**Comment by seerge** [comment]
@Eckoa hello,

I have recently discovered how Armoury can completely disable Game Visual by calling `AsusSplendid.exe` (responsible for it) and added it to G-Helper as new "Disabled" Visual Mode.

It is live in latest release https://github.com/seerge/g-helper/releases/tag/v0.196

Let me know if it changes something for you

**Comment by Eckoa** [comment]
I'll have to install windows on a separate ssd, I'm back on Linux so I'll let you know when I test it.

**Comment by Eckoa** [comment]
Its been a hot minute but i remembered to test this and the disabling of splendid does appear to work properly
