### ISSUE TITLE
fan curve not work

### ISSUE THREAD

**Issue by aikoncrime** [seerge/g-helper#2988]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

the GPU fan stops working in balance mode if enabled custom fan curve.
if you remove сгкму setting, the fan starts working. if you switch to turbo mode, the fan works.

### How to reproduce the bug?

win pow mode - balance
cpu boost - disabled
custom curve - enable

start balansed + standart mode.
change to eco mode
change to standart mode
profit

### Logs

[log.txt](https://github.com/user-attachments/files/16645087/log.txt)

### Device and Model

Asus Zephyrus G14 GA401QM

### Additional information.

![curve_off](https://github.com/user-attachments/assets/1df86a31-27de-4b15-87a9-bcd1336156c2)
![curve_on](https://github.com/user-attachments/assets/d75fec8a-c8e6-40fe-93b9-0b8d17007ef5)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.184

### OS

windows 11 home single language 23H2

**Comment by seerge** [comment]
@aikoncrime hello, G-Helper does not control your fans, [please make yourself familiar with FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)

If you don't like how BIOS controls fans you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)

**Comment by aikoncrime** [comment]
the problem is that after reboot everything works. it stops working only after changing to eco mode and back.

**Comment by seerge** [comment]
@aikoncrime it's just a hiccup of a BIOS on your device
