### ISSUE TITLE
I have no dynamic boost and gpu temp target controls on Asus ROG Zephyrus Duo 15 SE GX551QS

### ISSUE THREAD

**Issue by fluttered7** [seerge/g-helper#2990]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![Screenshot_5](https://github.com/user-attachments/assets/6d39ff1e-5e6f-45e8-9c3b-b44a11c14301)
Please help to understand why there are no  dynamic boost and gpu temp target controls in GPU section. I tried with unianstalled AC and then with installed - its same. And also with different nvidia drivers. 

### How to reproduce the bug?

Open fans+power and the GPU section

### Logs

[log.txt](https://github.com/user-attachments/files/16646285/log.txt)

### Device and Model

Asus ROG Zephyrus Duo 15 SE GX551QS

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.184.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@fluttered7 hello, most likely your device simply don't support that. Do you have those settings in Armoury ?

**Comment by fluttered7** [comment]
No i dont have it, but in asus threads they wrote  that there is such functionality for all rog laptops. Here is for example a screenshot for similar laptop from asus official page. 
![Screenshot_6](https://github.com/user-attachments/assets/91552162-ce64-4d83-b82a-a5200e262b46)

https://rog.asus.com/articles/guides/how-to-tweak-your-rog-laptops-performance-with-armoury-crates-manual-mode/

**Comment by fluttered7** [comment]
And as i remember this function was there but i am not sure)

**Comment by seerge** [comment]
@fluttered7 some devices may not support that, if you don't have it in AC, it means those functions / endpoints are not available so G-Helper also doesn't show them.

If you are 100% sure that you had them before, and now  you don't - it could be some hiccup with BIOS / drivers

You may want to do hard reset and then reinstall Asus System Control interface as explained 
https://github.com/seerge/g-helper/wiki/Troubleshooting

Besides that I can't do anything, thanks and good luck

**Comment by seerge** [comment]
P.S. I googled your deice, it's from 2021, there is a good chance it simply never had those options (especially if all other settings work fine)

**Comment by fluttered7** [comment]
Thank you much!  I found an info that it was in AC before, but then its gone with some update. My GPU has dynamic boost for sure but maybe they removed this option. Also thanks for a great software! Good luck!
