### ISSUE TITLE
side buttons problem

### ISSUE THREAD

**Issue by AayushV12** [seerge/g-helper#2991]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

there are five side buttons for my laptop :- play,pause,previous ,next,print screen.sometimes they perform abnormally.like i am in a video and i press pause and then play again but the video doesnt resume.

### How to reproduce the bug?

click buttons

### Logs

[log.txt](https://github.com/user-attachments/files/16647476/log.txt)

### Device and Model

asus rog strix g15 g513rc hn062w

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

.184

### OS

windows 11 23h2

**Comment by seerge** [comment]
@AayushV12 hello, G-Helper is not handling those buttons anyhow. They work on hardware level. Thanks
