### ISSUE TITLE
Option for varying levels of Varibright

### ISSUE THREAD

**Issue by CodingGenius0001** [seerge/g-helper#2992]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Unable to adjust the sensitivity/power of Varibright

### Describe the solution you'd like

Allow an option to adjust the slider of AMD Varibright like this attachment below:

![image](https://github.com/user-attachments/assets/17d774be-f307-436c-bcc5-d6422858a82b)

### Device and Model

Asus Zephyrus G14 2024 GA403UI

**Comment by seerge** [comment]
@CodingGenius0001 hello, what is the practical purpose of that ? 

The only reason Varibright toggle exists in G-Helper is cause some people don't even have Adrenaline installed and want to turn it OFF (as it's ON by default). 

If you really use Varibright - you can control it via Adrenaline control panel, same as you can control like dozen of other AMD-specific settings (frame gen, FSR, etc). 

So I don't want to overload UI with a setting that is easily controllable in some other way

Thanks

**Comment by seerge** [comment]
@CodingGenius0001 P.S. You have an OLED model, Varibright doesn't save any battery for you as it's designed for IPS panels making them look "brighter" on low brightness levles.

So you should just toggle it OFF forever and call it a day.
