### ISSUE TITLE
Battery Charge limit aint working.

### ISSUE THREAD

**Issue by AshKxK** [seerge/g-helper#2994]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Battery chargelimit aint working. Some days ago I have used the laptop and discharged it to around 20ish battery. The battery charge limit is set to 40. Now when I'm looking at my battery it is 100% charged, That is a problem for me because my laptop is always on power.
P.S: Fresh installed windows a month ago, and never installed armoury crate.

### How to reproduce the bug?

I dont have anything to write here, I believe

### Logs

[log.txt](https://github.com/user-attachments/files/16651183/log.txt)

### Device and Model

Asus Rog G17 713IM

### Additional information.

![image](https://github.com/user-attachments/assets/52e1cc72-191e-4d86-8aab-64df1ad55e58)

### Armoury Crate

Never installed

### Asus Services

6

### Version

0.184

### OS

Windows 11 23H2( OS Build: 22631.4037)

**Comment by seerge** [comment]
@AshKxK hello, 

You  have asus services running that override the setting. 

Please make yourself familiar with FAQ, your question is answered there.
https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working

Thanks

**Comment by AshKxK** [comment]
I'm back here. So for some days it worked, but I went away, it had around 43% battery. When I came back home it was at 92%. 0 asus services running. I will provide here a log file( [log.txt](https://github.com/user-attachments/files/16766503/log.txt) )

**Comment by seerge** [comment]
@AshKxK hello,

First of all you are setting 40% limit, it may be simply not supported by your device. Try to set 80% (the one MyAsus / asus services set).

And second - keep in mind that if you reboot, limit resets and it is applied again by the app the moment you log in to windows and app starts with system. So before that moment - it will be charging, and it's normal.

You can see charging status if battery / power led is orange, and white when it's not charging.

**Comment by AshKxK** [comment]
Ph ok
I thought it would be like in my Asus
And I think it supports it( I don't remember exactly) I remember having 3 levels in myasus.

**Comment by seerge** [comment]
@AshKxK it usually offers only "battery saver" which is 80%. On some models it can give a choice between 60 / 80 / 100

**Comment by AshKxK** [comment]
Then it supports 60
I will show a screenshot later if you need.
