### ISSUE TITLE
Model doesn't support custom fan curves

### ISSUE THREAD

**Issue by coffeemell** [seerge/g-helper#2997]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I found that I can't customize the fan speed, when I click on apply custom fan speed, it displays "Model doesn't support custom fan curves", and the main interface does not show the fan speed of the cpu and gpu
![屏幕截图 2024-08-20 175657](https://github.com/user-attachments/assets/04340ab7-bd7c-4704-8105-9b138d82883d)
![屏幕截图 2024-08-20 175921](https://github.com/user-attachments/assets/369280d7-dd01-4c95-a229-6ecef01aad88)

### How to reproduce the bug?

![屏幕截图 2024-08-20 175657](https://github.com/user-attachments/assets/89fd11d9-54e4-405b-bddc-ba0e406f0be9)

### Logs

?

### Device and Model

vivobook pro 15 ultra9

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.184

### OS

windows 11 23H2

**Comment by seerge** [comment]
@coffeemell it means that your device indeed does not support custom fan curves as you never had them in MyASUS or any other asus app as well.

If you really need them by some reason you can use [Experimental build with manual fan control](https://github.com/seerge/g-helper/discussions/2272)

**Comment by coffeemell** [comment]
thanks!!!
