### ISSUE TITLE
Feature request - Autohide window, Positions of fan dots, Aura effects speed/colors, ...

### ISSUE THREAD

**Issue by lucidnx** [seerge/g-helper#30]
Hello! First I really love you for what you have done, I am right now ~1 month without Armoury Crate and I already missed some features which are back thanks to your app :)
It's superb but anyway I think it can be better, and here is list of things that will be helpful:
1. Exact position info of dots in Fans configuration window, so I can exactly see at which temperature/fan speed the dot is set.
2. Disappear main window when it loose focus (when there is no other sub-window open like Fan profiles or so..)
3. Aura effect speed and colors (now I am able to choose rainbow, but it's really fast and I am not able to pick individual colors/gradient)
4. Option to supress Armory Crate installation window on M4 press (maybe?) 
5. Fan menu - dots can be grabbed outside of graph (left side)

**Comment by hkaancaliskan** [comment]
For 4:
I've disabled some Asus stuff in services and it's gone.
Disabled all of them except Asus Optimization and AsusCertService
![Adsız](https://user-images.githubusercontent.com/17825767/221439594-e2f6b13b-e09e-4d43-b3f5-ae07295d5ef2.png)

**Comment by lucidnx** [comment]
> For 4: I've disabled some Asus stuff in services and it's gone. Disabled all of them except Asus Optimization and AsusCertService Also there is an armoury crate setting in bios, turn it off. ![Adsız](https://user-images.githubusercontent.com/17825767/221439594-e2f6b13b-e09e-4d43-b3f5-ae07295d5ef2.png)

Actually ASUS Optimization is needed to keep hotkeys working (FN+F3, F4 for backlight etc..). Other way will be implementing hotkey support in g-helper...

**Comment by seerge** [comment]
You can try https://github.com/seerge/g-helper/releases/tag/v0.9.8

**Comment by seerge** [comment]
1. Asus bios treats fan settings quite indicatively, so precise values make no sense. In latest release axis step is 10 units, it should be good enough
2. I don't like that behavior, as often keep window open
3. I have set speed to slowest, it should suit majority and added second color for Breathe animation. Other modes don't support second color
4. That's for you to turn off manually in bios settings (armory crate control thing)
5. Should be limited to 20 degrees lowest

**Comment by lucidnx** [comment]
> 1. Asus bios treats fan settings quite indicatively, so precise values make no sense. In latest release axis step is 10 units, it should be good enough
> 2. I don't like that behavior, as often keep window open
> 3. I have set speed to slowest, it should suit majority and added second color for Breathe animation. Other modes don't support second color
> 4. That's for you to turn off manually in bios settings (armory crate control thing)
> 5. Should be limited to 20 degrees lowest

1. there are 20 fan levels, increments of 200 starting at 2000rpm, ending at 6000rpm (actually never reach 6k, it's not exact.) HWInfo app can monitor it exactly. I just don't like inaccurate values/things so you know... maybe snappy dots :)))
2. maybe simple checkbox for auto-hide? or advanced settings with more features maybe?
3. Rainbow do have few color presets, but I guess it was controller by Aura service in real time maybe?
4. good to know, last time I had look there, I did not seen that. will check.
5. it's limited correctly :)
I hope I am not bothering you with all those requests :)))

**Comment by seerge** [comment]
1. I'm glad there are 20 fan levels. It doesn't change a fact that chart displays EXACT readings from bios (for factory profiles), and at the same time bios doesn't treat settings exactly when it comes to applying them. At least not for me.  Fans on main screen are shown in % relatively to maximum (i.e. 6000 rpm)
3. App already have quite a lot of checkboxes :)
4. Linux implementation has 2 colors https://gitlab.com/asus-linux/asusctl/-/blob/main/rog-aura/src/usb.rs I'm not aware about others

As for the rest, you are free to make a fork and do your changes. It's github aftter all.

**Comment by lucidnx** [comment]
yeah, well, thank you anyway.

**Comment by lucidnx** [comment]
> I have deliberately installed AC again to check Aura colors.
> 
> There are 2 separate modes for laptop keyboard:
> 
> * Built in modes (i.e. static (1 color) / breathing (2 colors) / rainbow (predefined color)). Those are implemented in G-Helper. They are also implemented in similar linux tool.
> * "Aura service" controlled modes, all those are literally imitated by asus service running in background and setting color every X milliseconds. I have no plans to implement those, as it's literally against whole logic of G-Helper being light tool.

Yes.. as I tought. There is nothing to do then. Thanks for check.
