### ISSUE TITLE
How are the two additional low-power e-cores in the Ultra 9 (185H) handled by this setting?

### ISSUE THREAD

**Issue by jgohil** [seerge/g-helper#3000]
https://github.com/seerge/g-helper/blob/cd930cebf9585c5999e417884c78fdfa305afbf0/app/Extra.cs#L507

**Comment by jgohil** [comment]
No, I haven't noticed any way to do that in AC.  I didn't know whether you had a different approach.  Also, after a bit of additional research, it seems that disabling the e-cores is of limited utility anyway.

But thanks so much for G-helper - it's incredibly useful and well made!

**Comment by seerge** [comment]
@jgohil G-Helper just gives you access to the same settings AC offers. So approach is exactly same as in AC
