### ISSUE TITLE
Vivobook Pro 14 OLED custom fan curve

### ISSUE THREAD

**Issue by hart0x** [seerge/g-helper#3001]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I can't create a custom fan profile with G-Helper, but I can with a different program: https://github.com/Darren80/AsusFanControlEnhanced

![no_custom_fan](https://github.com/user-attachments/assets/92b6892e-9806-4e15-a1ca-2882071a49fb)

### Describe the solution you'd like

The functions of AsusFanControlEnhanced embedded in G-helper.

### Describe alternatives you've considered

If it's not possible it's not a big deal because you can run the programs at the same time.

### Device and Model

Vivobook Pro 14 OLED k3400ph

**Comment by seerge** [comment]
@hart0x hello. Sorry, but you clearly did not make yourself familiar with [FAQ](https://github.com/seerge/g-helper/wiki/FAQ)

> How does G-helper control my fan speeds?
It doesn't and can't control your fans. Your firmware / BIOS controls them in real-time. Armoury also doesn't control fans in real time anyhow.

>  If you don't like how firmware controls fans, you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)
