### ISSUE TITLE
Flip media and function keys

### ISSUE THREAD

**Issue by aayushbhatia06** [seerge/g-helper#3003]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Right now, for a lot of people if they wish to access media keys by default (instead of pressing the "fn" key everytime) they have no option. For my Zephyrus G14 G401IU there is no option in bios, no option in, "Asus keyboard hotkeys" app and nothing in "My Asus" app either.  G-helper has a function lock which helps with this on the laptop keyboard, but does not pass over to external keyboards. 

### Describe the solution you'd like

I barely use the "function" keys so having media keys be default will be awesome on my external keyboard

### Device and Model

Asus Zephyrus G14 G401IU

**Comment by seerge** [comment]
@aayushbhatia06 hello, each external keyboard has own absolutely different approach to special keys that varies by brand / model ,etc

If you want to bind F2 to perform some media action just use [Sharpkeys](https://github.com/randyrants/sharpkeys) or sometihng like that.

Thanks
