### ISSUE TITLE
Instantaneous Discharge Info

### ISSUE THREAD

**Issue by Rdpruitt** [seerge/g-helper#3006]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Right now, when I open Ghelper, it shows how much power the laptop is using, but it takes quite a while for it to update to a new number, for example after I open or close a power hungry application. This makes it difficult to troubleshoot finding exactly what is using the power.

### Describe the solution you'd like

It would be nice if the Discharge number would update truly in real time, as fast as the fan speed and CPU/GPU temp increases. I really don't know if this would be possible, maybe Windows limits how often the discharge can be reported. But if it is possible, I think it would be a great quality of life improvement. Also thank you for all the work you do!

### Device and Model

Asus Zephyrus G14 GA402RK

**Comment by seerge** [comment]
@Rdpruitt hello, 

G-Helper takes discharge rate from windows WMI every 2 seconds. The way windows reports it varies from device to device. On some models it updates very frequently, on some others (like 2022 model) it updates less frequently, but there is nothing that can be done to speed it up.

Thanks
