### ISSUE TITLE
ROG Zephyrus G16 2024 GU605MZ Having Sleep Issues When Using GHelper But Behaves Correctly With ArmoryCrate

### ISSUE THREAD

**Issue by OrsellGaming** [seerge/g-helper#3007]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I believe that something with GHelper is not working correctly with the sleeping operation of my ROG Zephyrus G16 2024 GU605MZ. Every time I close the screen lid, press the off button, or click sleep in the Start menu, the screen and keyboard shutoff and the back slash lighting also turns off, and the power light does its sleep mode flashing. However the fans and drive of the laptop still behave and act as if the laptop is still on.

I've tried many things from drivers to power settings and found that it most likely GHelper is the culprit when I tried Armoury Crate out again instead of using GHelper, and low and behold it actually fully goes to sleep. Even the keyboard actually does it sleep blinking which shows that it had fully gone to sleep. I have no clue if any of my settings in GHelper or anything else besides GHelper or Armoury Crate could be interfering, as I've gone through everything I could think of with zero results.

Hoping that this can be fixed so I don't have to rely on Armoury Crate for such a simple thing a computer should be able to do without having another piece of software being available and active. Plus I really would like to put this laptop in a bag without risking suffocating itself.

### How to reproduce the bug?

1. Disable Armoury Crate on the system if its present.
2. Make sure GHelper is enabled on the system, open and able to do its modifications.
3. So you are able to tell if the laptop is actually sleeping, have GHelper have the fans at a high speed so they make audible noise. That way if it is indeed sleeping then the fans will shut off.
4. Press the power button, or the Sleep button in the Start menu, or close the lid, to get the laptop to sleep.
5. If you hear the fans still spinning and the drive light on the back of the laptop still rapidly flashing even after a solid amount of seconds, then you are experiencing what I've been experiencing. If you don't then either this could be a problem specifically with my system.

### Logs

[log.txt](https://github.com/user-attachments/files/16703232/log.txt)

### Device and Model

ROG Zephyrus G16 2024 GU605MZ

### Additional information.

This does seem to be on and off. While my producing instructions are pretty much what I did, as well as the opposite to confirm that Armoury Crate is allowing it to sleep, most of the time the issue is occurring and other times its fine.

### Armoury Crate

Installed

### Asus Services

0

### Version

0.184.0

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@OrsellGaming hello,

G-Helper is not interacting with sleep :) This is the function of windows.

- It looks like you have `BatteryLevel` mode set for slash lighting, try to set anything else 
- If windows has sleep issues, you may want to try to reset [power plan back to defaults to see if it helps.](https://github.com/seerge/g-helper/wiki/Troubleshooting#resetting-windows-power-plan-to-defaults)
- Also you can run [sleepstudy](https://learn.microsoft.com/en-us/windows-hardware/design/device-experiences/modern-standby-sleepstudy) to see what is happening.

Besides that I can't do anything. Thanks.

**Comment by seerge** [comment]
@OrsellGaming any updates here ?

**Comment by BassemMohsen** [comment]
I have the same issue on my G16 HX370.
I had it when I used Armoury Crate and when I used GHelper.

Sometimes laptop sleeps right away. Sometimes it takes 1 minute or so to sleep. Othertimes, it doesn't and I have to open it and retry again.
Sleep function is unreliable, I'm not sure what's happening.

sleepstudy looks like a good pointer.
I can check sleepstudy by Microsoft and I will come back to the thread with some logs on this.

**Comment by seerge** [comment]
@BassemMohsen welcome to the [world of a wonderful windows sleep](https://www.youtube.com/watch?v=OHKKcd3sx2c). Anyway it's not related to G-Helper anyhow.

**Comment by BassemMohsen** [comment]
https://drive.google.com/file/d/1-osHKrHQeMXECCtzAFerBS22fxOoqFTR/view?usp=sharing

It looks like MediaTek WiFi 7 might be offensive sometime, but seems to comply after a while.

Also, there's a feature that could trigger hibernate if sleep exceed standby battery budget exceeded. battery was high 60s%
but hibernate could explains why SSD drive LED is blinking.

I'm speculating here, not sure if data is useful, Microsoft had many users report issues with smart standby feature for many years now.

**Comment by BassemMohsen** [comment]
It's quite highly reproducible. I'd say we should take this issue to Asus forums instead, and ask Asus to investigate.

It does seem to sleep a bit faster when disabling MediaTek WiFi card.

I'm not sure it's MediaTek driver issue, or if it's a Microsoft implementation of how Modern Standby actually wakes regularly to check network traffic and remains connected.

**Comment by BassemMohsen** [comment]
Could be interesting also to look at and discuss with Asus
https://learn.microsoft.com/en-us/windows-hardware/customize/power-settings/adaptive-hibernate

The trigger seems to actually happen, and the default values policy is defined and provisioned by the OEM in that case which is Asus.

I will test setting different values tomorrow or see how to disable it, and come back with the results.

**Comment by OrsellGaming** [comment]
> @OrsellGaming any updates here ? 

Hi sorry for the late response @seerge .

Ok ill try those things you suggested to see if I can get it to sleep.

**Comment by OrsellGaming** [comment]
> Could be interesting also to look at and discuss with Asus

I did actually contact ASUS too and didnt get much of any help. They suggested upgrading back to 11 and that was it.

https://rog-forum.asus.com/t5/gaming-notebooks/new-g16-zephyrus-gu605mz-will-not-go-fully-to-sleep/m-p/1036045/emcs_t/S2h8ZW1haWx8bWVudGlvbl9zdWJzY3JpcHRpb258TFpUSDI5STVKVEtKQXwxMDM2MDQ1fEFUX01FTlRJT05TfGhL#M7500

**Comment by OrsellGaming** [comment]
Does setting the Fan mode to Turbo mode intentionally keep them on when putting the computer to sleep, or do they actually shut off when the computer goes to sleep?

**Comment by seerge** [comment]
@OrsellGaming if devices goes to sleep on hardware level it usually turns fans off. But fans are always controlled by firmware / BIOS, so I can imagine if devices sees it's too hot in sleep it still may turn them on. But I doubt it's your case, cause for you it just windows refusing to sleep :)

Did you try everything I was suggesting ?

**Comment by BassemMohsen** [comment]
I also tried turning off hybrid sleep aka adaptative sleep. It didn't change the behaviour that device could take long time to sleep or not enter sleep mode sometime

`POWERCFG -SETDCVALUEINDEX SCHEME_CURRENT SUB_SLEEP HYBRIDSLEEP 0`

I'm not sure what's Microsoft or apps are writing to disk when laptop is about to go to sleep. They are probably persisting some critical user data or diagnostics to disk.
But the strange thing is CPU LED starts pulsating to indicate sleep mode before disk LED stops flashing!
I thought if CPU enters sleep mode, registers context is suspended to RAM and that's it. but clearly Modern sleep is different from what I know.

As seerge said, it's highly likely firmware issue in the BIOS itself. My laptop is not hot, it's like mid 30s. It might be something like event loop or Temp and CPU state sampling time for the fan control firmware is quite long in the BIOS.

I will come with you to Asus forums and act as angry Karin and ask for the manager :D
The support guy response is just standard turn it on and off again. He also might not have technical depth enough to support on the subject. They should fix this or help us understand it.

**Comment by seerge** [comment]
@BassemMohsen if CPU (or power led) starts pulsating - it usually means that from firmware / hardware point of view laptop is sleeping (it also runs keyboard flash animation and slash lighting sleep animation if those are ON)

**Comment by BassemMohsen** [comment]
> @BassemMohsen if CPU (or power led) starts pulsating - it usually means that from firmware / hardware point of view laptop is sleeping (it also runs keyboard flash animation and slash lighting sleep animation if those are ON)

You are right, all kind of background services and apps can wakeup and execute even if system goes to sleep or even delay sleep until they do whatever they like. even run full system updates !
https://learn.microsoft.com/en-us/windows-hardware/design/device-experiences/activators?source=recommendations

The bug is just fans are too late to stop, or device might not go to sleep because OS or Apps could be doing anything they'd like.

I wonder who asked Microsoft to not just implement a simple way to opt out from all of this.
Laptops are not tablets nor phones. why treat them as such !

**Comment by OrsellGaming** [comment]
> @OrsellGaming if devices goes to sleep on hardware level it usually turns fans off. But fans are always controlled by firmware / BIOS, so I can imagine if devices sees it's too hot in sleep it still may turn them on. But I doubt it's your case, cause for you it just windows refusing to sleep :)
> 
> Did you try everything I was suggesting ?

@seerge You could be right as it does seem after a bit they die down in their speed after sleeping. Although you could be definatly right about the BIOS/Firmware stuff as recently GHelper has reported that there is a new BIOS update for 8/19/24. So maybe possibly ASUS fixed this issue?

I did try the other things you suggested to no avail, hopefully maybe there is something to come out of the BIOS update if I do that.

**Comment by OrsellGaming** [comment]
BIOS update didn't seem to do anything, but it was worth a shot. I've never had modern Windows sleep issues like this before. Again it could very much be that when the fans are spinning high they need time to go down.

**Comment by OrsellGaming** [comment]
Ok so I guess I'll have to deal with this laptop not properly sleeping. BIOS updated didn't work, power settings are fine, drivers are up to date, I've gone through everything I could think of. Maybe that is just how the fans work with this laptop and it cools down the CPU/GPU before fully going to sleep.

If anyone else got any suggestions feel free to post, but for now I'm closing this as this is not going anywhere else.
