### ISSUE TITLE
CPU not reaching base clock speeds on heavy tasks

### ISSUE THREAD

**Issue by officialAbdii** [seerge/g-helper#3008]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

During normal tasks, the CPU Ryzen 7 4800H runs normally, and reaches high clock speeds, but during gaming i noticed that the CPU clock speed is limited drastically for some reason.

I played a game and also ran Cinebench Stress test.

The CPU is stuck at 1400 MHz clock speed and doesnt change at all during any heavy tasks
![Screenshot 2024-08-22 141721](https://github.com/user-attachments/assets/27bff126-fcf5-4d97-a31e-a2640cbf6fc3)

Edit: The CPU utilization reached 100% immediately after i unplugged the charger and plugged it in again. (It was already plugged in when i started these tests and gaming sessions)

### How to reproduce the bug?

Run heavy tasks

### Logs

dont knoww where to find the log file

### Device and Model

Asus Tuf A15 FA566IC

### Armoury Crate

Never installed

### Asus Services

6

### Version

0.184

### OS

Windows 11

**Comment by seerge** [comment]
@officialAbdii hello, 

G-Helper is not a driver it's not [managing your hardware in realtime anyhow](https://github.com/seerge/g-helper?tab=readme-ov-file#-important-notice). All modes are baked into your BIOS.

Based on screenshot you use all default settings, so there are no extra limits or restrictions done - which is fine

You can try to do a [hard reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset) and restore [power plan settings to all defaults](https://github.com/seerge/g-helper/wiki/Troubleshooting#resetting-windows-power-plan-to-defaults). 

Besides that I can't advice anything else as this is not G-Helper limiting clocks :)

Thanks
