### ISSUE TITLE
Incorrect key bindings with FN-Lock - TUF A17 FA706IHRB

### ISSUE THREAD

**Issue by amit-katyal** [seerge/g-helper#3009]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![image](https://github.com/user-attachments/assets/57b78b89-9792-4202-9199-159ed2afe353)
![IMG_20240822_144559](https://github.com/user-attachments/assets/d0952fb2-cc26-46a0-b628-e88006d4d5a2)

When the FN-Lock is on, how it is supposed to be:
F6: Screen off
F7: Decrease brightness
F8: Increase brightness

How it works, currently:
F6: Screenshot
F7: Increase brightness
F8: Decrease brightness

The brightness keys F7, F8 are reversed and F6 is being used to take a screenshot instead of turning off the screen

### How to reproduce the bug?

1. Open G-helper
2. Turn on FN-Lock

### Logs

22-08-2024 02:42:42 PM: WMI event 51
22-08-2024 02:42:42 PM: Failed to turn off screen. Error code: 0. The operation completed successfully. 
22-08-2024 02:42:42 PM: Monitor Power Off
22-08-2024 02:42:42 PM: TUF Brightness = 128 : OK
22-08-2024 02:42:43 PM: Monitor Power On
22-08-2024 02:42:43 PM: AutoSetting for Offline
22-08-2024 02:42:43 PM: BatteryLimit = 80 : OK
22-08-2024 02:42:43 PM: Eco flag : 1
22-08-2024 02:42:43 PM: Mux flag : -65536
22-08-2024 02:42:43 PM: \\?\DISPLAY#BOE0A11#5&764251f&1&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
22-08-2024 02:42:43 PM: \\?\DISPLAY#BOE0A11#5&764251f&1&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
22-08-2024 02:42:43 PM:  HDR: False 8 12 True
22-08-2024 02:42:43 PM: Mode = 0 : OK
22-08-2024 02:42:43 PM: TUF_KB = 16712125 : OK
22-08-2024 02:42:43 PM: AuraMode: AuraColorCycle
22-08-2024 02:42:43 PM: TUF RGB = B4-02-C0-C0-C0-E1 : OK
22-08-2024 02:42:44 PM: TUF Brightness = 129 : OK
22-08-2024 02:42:46 PM: Session:SessionUnlock
22-08-2024 02:42:46 PM: \\?\DISPLAY#BOE0A11#5&764251f&1&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
22-08-2024 02:42:46 PM: \\?\DISPLAY#BOE0A11#5&764251f&1&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
22-08-2024 02:42:46 PM:  HDR: False 8 12 True
22-08-2024 02:42:53 PM: Input device not found
22-08-2024 02:42:57 PM: F7 None
22-08-2024 02:42:57 PM: Brightness = 16 : OK
22-08-2024 02:42:58 PM: F7 None
22-08-2024 02:42:58 PM: Brightness = 16 : OK
22-08-2024 02:42:59 PM: F8 None
22-08-2024 02:42:59 PM: Brightness = 32 : OK
22-08-2024 02:42:59 PM: F8 None
22-08-2024 02:42:59 PM: Brightness = 32 : OK
22-08-2024 02:43:01 PM: F6 None
22-08-2024 02:43:04 PM: F6 None
22-08-2024 02:43:13 PM: F6 None
22-08-2024 02:43:14 PM: F6 None
22-08-2024 02:43:23 PM: F7 None
22-08-2024 02:43:23 PM: Brightness = 16 : OK
22-08-2024 02:43:24 PM: F7 None
22-08-2024 02:43:24 PM: Brightness = 16 : OK
22-08-2024 02:43:25 PM: F8 None
22-08-2024 02:43:25 PM: Brightness = 32 : OK
22-08-2024 02:43:26 PM: F7 None
22-08-2024 02:43:26 PM: Brightness = 16 : OK
22-08-2024 02:43:27 PM: F8 None
22-08-2024 02:43:27 PM: Brightness = 32 : OK
22-08-2024 02:43:28 PM: F7 None
22-08-2024 02:43:28 PM: Brightness = 16 : OK
22-08-2024 02:43:29 PM: F7 None
22-08-2024 02:43:29 PM: Brightness = 16 : OK
22-08-2024 02:43:30 PM: F8 None
22-08-2024 02:43:30 PM: Brightness = 32 : OK
22-08-2024 02:43:30 PM: F8 None
22-08-2024 02:43:30 PM: Brightness = 32 : OK
22-08-2024 02:43:36 PM:  HDR: False 8 12 True
22-08-2024 02:43:41 PM: Hibernate after 2147483647

### Device and Model

Asus TUF Gaming A17 FA706IHRB

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.184.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@amit-katyal hello, this build should swap brightness hotkeys for your model
[GHelper.zip](https://github.com/user-attachments/files/16708420/GHelper.zip)

As for `F6` I don't see much sense in changing that, as screenshot is much more useful than screen off (which is effectively puts device to sleep same as `F11` does). And also on all newer asus laptops `F6` does screenshot anyway :)

Thanks

**Comment by amit-katyal** [comment]
Thanks for the speedy update ) working flawlessly! This is such a fantastic tool
