### ISSUE TITLE
ASUS OLED Care Target Mode

### ISSUE THREAD

**Issue by Kiraprint** [seerge/g-helper#3010]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

In Armoury Crate we have OLED Service needed for blacking non-target windows. Would be nice to reproduce the same service in GHelper.

### Describe the solution you'd like

Just copy same service from AC to GHelper

### Device and Model

Asus Zephyrus G16 GU605MV

**Comment by seerge** [comment]
@Kiraprint hi, it can be quite difficult cause this is a whole separate task to draw a half-transparent overlay in windows around active window.

Why don't you just copy Target Mode app from AC package and use it separately ? I don't have an OLED device so can't even test it.

**Comment by Kiraprint** [comment]
How can I do it concretly?
I've just copied ASUS_TargetMode.exe to autostart, but it's not working.

**Comment by seerge** [comment]
@Kiraprint does it keep running in Task manager if you start it ?

I just don't know how to initialize it as I don't have OLED device atm, so I can't check what AC does 

You can try to do following : 

---

1. Download and launch https://learn.microsoft.com/en-us/sysinternals/downloads/procmon 
2. Go to filters in it and add 1 filter as on screenshot (with green checkbox)
![Screenshot 2024-08-30 195444](https://github.com/user-attachments/assets/f8fc8e00-a7b1-4d91-b867-5901af665259)
3. Click on [CAPTURE] icon
4. Launch AC and toggle Target mode ON and OFF
6. Check what Process Monitor captured ?

**Comment by seerge** [comment]
@Kiraprint any updates here ?

**Comment by seerge** [comment]
Due to lack of response - closed as abandoned

**Comment by Maks-gaming** [comment]
UP

<img width="1564" height="1388" alt="Image" src="https://github.com/user-attachments/assets/0390fefb-a5e9-4ade-8d7e-7f2848d5d3d6" />

**Comment by Maks-gaming** [comment]
And for enabling

<img width="1363" height="1333" alt="Image" src="https://github.com/user-attachments/assets/f53d1cb9-9f15-40e5-af7e-ab67ffea2248" />
