### ISSUE TITLE
Silent mode on battery

### ISSUE THREAD

**Issue by MikeGreninja** [seerge/g-helper#3011]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

the fans don't run at all no matter what the cpu temp is, when running on battery power.

### How to reproduce the bug?

1. unplug charger
2. turn on silent mode
3. or vice versa

### Logs

[log.txt](https://github.com/user-attachments/files/16710265/log.txt)

### Device and Model

Asus Tuf F15 fx506hm

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.184

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@MikeGreninja hello,  [please maker yourself familiar with FAQ.](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds) Thanks.
