### ISSUE TITLE
seperate 240hz and 240hz+OD

### ISSUE THREAD

**Issue by muffinized** [seerge/g-helper#3013]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

just seperate the two seperating it will allow for better battery life

### Device and Model

zephyrus g16 605m

### Additional information.

idk if it really does anything but eh

**Comment by seerge** [comment]
@muffinized hello,

You can already disable overdrive for maximum refresh rate (240hz in your case) under `Extra`.
But from what I understand you have an OLED model? If so - you don't have any overdrive at all:)

Thanks
