### ISSUE TITLE
Requesting RAM Info displayed same as Asus AC please

### ISSUE THREAD

**Issue by Abdo-El-Mobayad** [seerge/g-helper#3014]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

No, it would be great to have RAM info displayed in g helper as well

### Describe the solution you'd like

RAM usage info displayed

### Device and Model

M16 2022 3070TI

**Comment by seerge** [comment]
@Abdo-El-Mobayad hello,

G-Helper is not hardware monitoring app :) it shows only basic info that is anyway reported by asus sensors (such as temps / fan speeds), so I don't plan to overload it with extra stuff atm

There are plenty of nice and light monitoring tools like HWinfo or window native task manager or even Nvidia / AMD overlays can show that as well.

On a side note: RAM is a very subjective metric, as windows would reserve a lot of unused RAM when it can, but release it when other app needs it. So free RAM % says pretty much nothing, unless it's really full or so

Thanks
