### ISSUE TITLE
Vivobook S 15 OLED flicker-free dimming request

### ISSUE THREAD

**Issue by AJustcaTA** [seerge/g-helper#3015]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Flicker-free dimming missing from the list of the compatible laptops.

### Describe the solution you'd like

Add the flicker-free dimming feature.

### Device and Model

ASUS Vivobook S 15 M5506UA

**Comment by seerge** [comment]
@AJustcaTA hello, try this build
[GHelper.zip](https://github.com/user-attachments/files/16736832/GHelper.zip)

**Comment by AJustcaTA** [comment]
> @AJustcaTA hello, try this build [GHelper.zip](https://github.com/user-attachments/files/16736832/GHelper.zip)

Thank you so much ;]
