### ISSUE TITLE
Ghelper causes GPU fan to stop running

### ISSUE THREAD

**Issue by Ccn1026** [seerge/g-helper#3016]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

After replacing the motherboard in my laptop, the use of Ghelper mode caused the GPU fan to stop running, but the fan still did not turn when the GPU was working. The software is normal before replacing the motherboard

### How to reproduce the bug?

Manually selecting the ARMOURY CRATE mode first, and then using the Ghepper mode (whether or not to stop ASUS services does not affect) will cause the GPU fan to stop running. Selecting the ARMOURY CRATE mode again will restore normal operation

### Logs

[log.txt](https://github.com/user-attachments/files/16735588/log.txt)

### Device and Model

ROG Strix G18(2023)

### Additional information.

![屏幕截图 2024-08-24 144952](https://github.com/user-attachments/assets/21666499-a573-4592-b767-46f2737e172f)

### Armoury Crate

Installed

### Asus Services

0/8

### Version

0.184/0.185

### OS

Windows11 23H2

**Comment by seerge** [comment]
@Ccn1026 hello, 

G-Helper does not control your fans, they are always controlled by BIOS. [Please make yourself familiar with FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)

If fans behave correctly when you use default modes in Armoury, you just need to use same default modes in G-Helper. I see that you have edited them and apply custom power and fan curves. Just click `Factory Defaults` to use default again.

```
2024/8/24 14:38:24: Mode = 0 : OK
2024/8/24 14:38:24: FanCPU = 1A-27-30-39-41-4C-55-64-01-09-10-1C-2E-44-64-64 : OK
2024/8/24 14:38:24: FanGPU = 19-26-32-39-42-4A-56-64-01-09-13-22-34-48-64-64 : OK
2024/8/24 14:38:24: FanMid = 1A-29-34-3D-47-4E-57-63-02-09-17-27-39-4D-64-64 : OK
2024/8/24 14:38:26: PowerLimit A3 = 60 : OK
2024/8/24 14:38:26: PowerLimit A0 = 80 : OK
```

Thanks.

**Comment by Ccn1026** [comment]
I manually set the mode in ARMOURY CRATE today, but still encountered the problem of GPU fan stalling after application. I also need to use ASUS default mode to solve it, so this should not be a problem with Ghepper

**Comment by seerge** [comment]
> so this should not be a problem with Ghepper

Good to know
