### ISSUE TITLE
Sleep option triggered automatically if "Disable sleep on lid close when plugged in and external monitor is connected" is on

### ISSUE THREAD

**Issue by AlessandroCarella** [seerge/g-helper#3018]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

If the aforementioned option is set and an external monitor is not connected, the option for the Windows power plan is automatically set to "Sleep" for Plugged in > When the lid is closed.

### How to reproduce the bug?

I have never plugged an external monitor into my laptop, so I cannot confirm it works exactly as described. 
I tried modifying the registry values related to this option, but GHelper still overwrites them.

### Logs

[log.txt](https://github.com/user-attachments/files/16741664/log.txt)

### Device and Model

ROG Zephyrus G16 (2024) GA605

### Additional information.

My best guess is that the code just applies a default option and reverts to "Sleep" when no monitor is plugged in. I’m also guessing that the intended behavior was for the code to save the previously set value and revert back to it when a monitor is not connected.

Please note that I'm in 24H2 so maybe the issue is related to that but I do not know.

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

0.148.0

### OS

Windows 11 24H2

**Comment by seerge** [comment]
@AlessandroCarella hello, it remembered option that you had in power plan when you have enabled `Clamshell mode` for the first time. It was Sleep.

You can either uncheck `Clasmshell` checkbox completely (and then it won't touch this setting)

OR

You can specify / adjust remembered option [in config as explained here ](https://github.com/seerge/g-helper/wiki/Power-user-settings#lid-close-action-when-clamshell-mode-is-off)

Thanks
