### ISSUE TITLE
automated keyboard backlit on/off 

### ISSUE THREAD

**Issue by chege54** [seerge/g-helper#302]
Hi!
Do you think is there any possibility to automate keyboard backlit to turn on/off based on a scheduled timing (ex. from 9PM till 7AM) or light sensor? (I am not sure is there any light sensor in the zephyrus)
Thank you!

**Comment by seerge** [comment]
There is no light sensor, as for turning lights on / off - current logic of the app, is to do nothing (literally) unless main window is open. 

And to change lights with time - it means it will have to run something periodically and check for time (which means extra resources). :|

**Comment by chege54** [comment]
Thank you for the feedback!
