### ISSUE TITLE
Synchronous control of coolers

### ISSUE THREAD

**Issue by PeppyTrash** [seerge/g-helper#3026]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Is it possible to add the possibility of enabling synchronous operation of fans?

### Describe the solution you'd like

For example, a check mark in the fan graph window that makes the CPU graph a priority and makes the GPU fan run at the same speeds

### Device and Model

G14 GA401QM

**Comment by seerge** [comment]
@PeppyTrash hello, your fans are always [controlled by BIOS](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds). 

If you don't like how BIOS controls fans - you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272). 

Check **readme on that page**, you can set : 

``"fan_shift" : 100, `` - to make both fans follow maximum temp of CPU/GPU

Thanks

**Comment by PeppyTrash** [comment]
Maybe I explained it wrong. I haven't seen yet how to make the GPU fan ignore the GPU graph and take the CPU graph speed so that both fans run at the same rpm. Thank you in advance

**Comment by seerge** [comment]
@PeppyTrash please read my answer fully. You can use experimental build for that purpose.

**Comment by PeppyTrash** [comment]
![image](https://github.com/user-attachments/assets/02b70259-a919-41ba-989f-fe1fcdbe3b61)

Yes, I read it, installed the build and made changes to the config, but there is still no desired result. At the moment, the CPU temperature is 55 degrees, the fan speed is 36% and I would like that, REGARDLESS of the temperature, the GPU fan is also running at 36% 

I do not exclude that I am being stupid, please forgive me :D

**Comment by seerge** [comment]
@PeppyTrash it doesn't look you have set 
```
"fan_shift" : 100, 
```

Can you upload your config here ?

**Comment by seerge** [comment]
This is the example of how it works when fan_shift is set to 100 (and both fans follow maximum of both temps, i.e CPU temp)

![Screenshot 2024-08-28 124315](https://github.com/user-attachments/assets/8b0e40c1-7e93-4b04-a4e4-807805cba9b1)
