### ISSUE TITLE
Is the Asus System Control Interface v3 needed? 

### ISSUE THREAD

**Issue by Waingro24** [seerge/g-helper#3027]
G-Helper fails to control many features, could this be because I don't have Asus System Control Interface v3 installed or is there another reason? 

I'm asking this because I was prompted to install only .NET and nothing else.

**Comment by seerge** [comment]
@Waingro24 yes, it’s mandatory. Without it neither AC nor G-Helper won’t work.

Check readme please https://github.com/seerge/g-helper/wiki/Requirements#requirements-mandatory
