### ISSUE TITLE
G helper not Starting up and working correctly 

### ISSUE THREAD

**Issue by Jarbuyer** [seerge/g-helper#3029]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

G Helper Not Starting on Boot:
        The option to run G Helper on startup has been unchecked and rechecked, but it does not start automatically.
        Manual restart from the Task Scheduler works temporarily, but the status reverts to "Ready" instead of "Running" after a short time.

Issues:
        M1, M2, M3, and M4 keys are frequently unresponsive.
        When the above keys do work, only the increase brightness brightness and backlight buttons function properly; the decrease brightness and backlight button (F2 F7) do not work.
        Mainly while on battery or type C charging, M1, M2, M3, and M4 keys doesnt work and the G Helper app fails to start.
        On AC power m1, m2 etc keys work but the F2 and F7 keys fail to work.
        All options work inside the G Helper Window (Mode, GPU Mode work fine) but the buttons are unresponsive 
    
        No Asus services are working
        Armoury Crate has been uninstalled

Steps Taken:

    Rechecked the startup settings after Running Ghelper as admin
    Restarted the G Helper service manually from Task Scheduler

### How to reproduce the bug?

.

### Logs

[log.txt](https://github.com/user-attachments/files/16805635/log.txt)

### Device and Model

ROG Zephyrus G14 GA401QH [2021]

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.184.0

### OS

Win 10 22H2

**Comment by seerge** [comment]
@Jarbuyer hello, can you check windows Even Viewer for a crash logs mentioning GHelper.exe ?

Cause looks like you start / restart app few times in a row or app just crashes by some unknown reason (and then of course hotkeys won't work cause it handles them)

```
30-08-2024 1.48.22 AM: App launched: ROG Zephyrus G14 GA401QH_GA401QH :0.184.0.0en-US.
30-08-2024 1.48.23 AM: Matrix control device was not found on your machine.
30-08-2024 1.51.53 AM: ------------
30-08-2024 1.51.55 AM: App launched: ROG Zephyrus G14 GA401QH_GA401QH :0.184.0.0en-US.
30-08-2024 1.51.56 AM: Matrix control device was not found on your machine.
30-08-2024 1.52.45 AM: ------------
30-08-2024 1.52.45 AM: App launched: ROG Zephyrus G14 GA401QH_GA401QH :0.184.0.0en-US.
30-08-2024 1.52.45 AM: Matrix control device was not found on your machine.
30-08-2024 1.52.46 AM:  HDR: False 8 0 False

```

**Comment by Jarbuyer** [comment]
Log Name:      Application
Source:        .NET Runtime
Date:          30-08-2024 1.55.00 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      R0G-Zephyrus
Description:
Application: GHelper.exe
CoreCLR Version: 8.0.824.36612
.NET Version: 8.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'GHelper.Program' threw an exception.
 ---> System.ComponentModel.Win32Exception (87): The parameter is incorrect.
   at GHelper.Display.ScreenCCD.GetHDRStatus(Boolean log) in D:\a\g-helper\g-helper\app\Display\ScreenCCD.cs:line 19
   at GHelper.Display.VisualControl.SetVisual(SplendidCommand mode, Int32 whiteBalance, Boolean init) in D:\a\g-helper\g-helper\app\Display\VisualControl.cs:line 229
   at GHelper.SettingsForm.InitVisual() in D:\a\g-helper\g-helper\app\Settings.cs:line 392
   at GHelper.SettingsForm..ctor() in D:\a\g-helper\g-helper\app\Settings.cs:line 277
   at GHelper.Program..cctor() in D:\a\g-helper\g-helper\app\Program.cs:line 30
   --- End of inner exception stack trace ---
   at GHelper.Program.Main(String[] args) in D:\a\g-helper\g-helper\app\Program.cs:line 72

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-08-29T20:25:00.5433375Z" />
    <EventRecordID>345611</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>R0G-Zephyrus</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: GHelper.exe
CoreCLR Version: 8.0.824.36612
.NET Version: 8.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'GHelper.Program' threw an exception.
 ---&gt; System.ComponentModel.Win32Exception (87): The parameter is incorrect.
   at GHelper.Display.ScreenCCD.GetHDRStatus(Boolean log) in D:\a\g-helper\g-helper\app\Display\ScreenCCD.cs:line 19
   at GHelper.Display.VisualControl.SetVisual(SplendidCommand mode, Int32 whiteBalance, Boolean init) in D:\a\g-helper\g-helper\app\Display\VisualControl.cs:line 229
   at GHelper.SettingsForm.InitVisual() in D:\a\g-helper\g-helper\app\Settings.cs:line 392
   at GHelper.SettingsForm..ctor() in D:\a\g-helper\g-helper\app\Settings.cs:line 277
   at GHelper.Program..cctor() in D:\a\g-helper\g-helper\app\Program.cs:line 30
   --- End of inner exception stack trace ---
   at GHelper.Program.Main(String[] args) in D:\a\g-helper\g-helper\app\Program.cs:line 72
</Data>
  </EventData>
</Event>




Log Name:      Application
Source:        Application Error
Date:          30-08-2024 1.55.00 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      R0G-Zephyrus
Description:
Faulting application name: GHelper.exe, version: 0.184.0.0, time stamp: 0x666b0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4717, time stamp: 0x16b0a901
Exception code: 0xe0434352
Fault offset: 0x000000000003b699
Faulting process id: 0x2ae4
Faulting application start time: 0x01dafa51856a8fba
Faulting application path: C:\Users\yubra\Downloads\Compressed\GHelper\GHelper.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 4ec7a21f-b846-40f5-9852-98920101d8b7
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-08-29T20:25:00.6234203Z" />
    <EventRecordID>345612</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>R0G-Zephyrus</Computer>
    <Security />
  </System>
  <EventData>
    <Data>GHelper.exe</Data>
    <Data>0.184.0.0</Data>
    <Data>666b0000</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.4717</Data>
    <Data>16b0a901</Data>
    <Data>e0434352</Data>
    <Data>000000000003b699</Data>
    <Data>2ae4</Data>
    <Data>01dafa51856a8fba</Data>
    <Data>C:\Users\yubra\Downloads\Compressed\GHelper\GHelper.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>4ec7a21f-b846-40f5-9852-98920101d8b7</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by seerge** [comment]
@Jarbuyer ok,

There is some internal windows issue with screen type detection, I also see in main app log that asus driver complains about missing color profiles 
```
30-08-2024 1.52.46 AM: C:\WINDOWS\system32\DriverStore\FileRepository\asussci2.inf_amd64_ad7e5f4b857611df\ASUSOptimization\AsusSplendid.exe 22 0 50
30-08-2024 1.52.47 AM: !! ICM file not exist !!
```

So it's probably cause of that.

But I have suppressed this exception , and shouldn't crash at least.
Try this build : 

[GHelper.zip](https://github.com/user-attachments/files/16806079/GHelper.zip)

**Comment by seerge** [comment]
@Jarbuyer I would reinstall [Asus System Control Interface](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-asus-system-control-interface) and then stop all asus services from `Extra`.

Can you do that, try hotkeys and post a log **after** that ?

**Comment by seerge** [comment]
@Jarbuyer any updates here ?

**Comment by Jarbuyer** [comment]
[log.txt](https://github.com/user-attachments/files/16825408/log.txt)
Hey I re installed the interface V3 but after some extensive use the problem still persists can you check the log and suggest

**Comment by seerge** [comment]
@Jarbuyer 

From the log it looks like not a single command is working now (even the ones that worked before) in your case

```
31-08-2024 9.56.57 PM: BatteryLimit = 85 : 0 
31-08-2024 9.56.57 PM: Eco flag : -65536
31-08-2024 9.56.57 PM: Mux flag : -65536
31-08-2024 9.56.57 PM: Mode = 0 : 0  <--- even balanced mode cant be set
```

Are you sure that System Control Interface was reinstalled ? as it looks like it's gone completely or not working.

Try to use latest version from [official asus page for your model](https://dlcdnets.asus.com/pub/ASUS/GamingNB/Image/Software/SoftwareandUtility/16116/ASUSSystemControlInterfacev3_ASUS_Z_V3.1.34.0_16116.exe?model=ROG%20Zephyrus%20G14%20GA401)

**Comment by Jarbuyer** [comment]
[log.txt](https://github.com/user-attachments/files/16825511/log.txt)
Yeah did that all the profiles work now, can you check now .

**Comment by seerge** [comment]
@Jarbuyer ok, now it seem to work indeed :)

I see that you were setting backlight down (to 0 level) and app is sending this command, so it should be turning backlight OFF

It appears like this in the log
```
31-08-2024 10.41.29 PM: Backlight 19B6: 5D-BA-C5-C4-00
```

Is it only backlight **down** that is not working, or also backlight up ? 
Do both backlight buttons work when you start asus services ?

**Comment by seerge** [comment]
@Jarbuyer as for display brightness, i see that you press `FN+F8` and app runs corresponding **brightness up** command 

```
30-08-2024 1.18.26 PM: Key: 32
30-08-2024 1.18.26 PM: Brightness = 32 : 0
```

But I don't see a single press of `FN+F7` registered. Does that hotkey works in general on your keyboard ?

**Comment by seerge** [comment]
Closed as abandoned due to lack of response. Main problem (exception handling) is already resolved in latest release
