### ISSUE TITLE
New ASUS service missing from "stop all ASUS services"

### ISSUE THREAD

**Issue by d-anez3** [seerge/g-helper#3031]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

A new ASUS service seems to have been added that isn't being noticed by G-Helper's stop all services button. It's called ASUS PTP Service, and on my machine its origin is C:\Windows\System32\DriverStore\FileRepository\asusptpfilter.inf_amd64_e109b959e17d8c0b.

I tried starting all ASUS services again and then stopping them, and this one is being missed.

### How to reproduce the bug?

1. Have Task Manager open, and see that ASUS PTP service is running
2. Go to G-Helper -> Extra
3. Toggle on all ASUS services
4. See that the other services turn on
5. Toggle off all ASUS services
6. See that ASUS PTP Service is left running while the others are shut down

### Logs

[log.txt](https://github.com/user-attachments/files/16818856/log.txt)

### Device and Model

ROG Zephyrus G14 GA401QM

### Additional information.

![image](https://github.com/user-attachments/assets/efba6ccd-d2b2-406d-a090-201fb2d8b0dc)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.184

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@d-anez3 hello, can you open windows Services app, check if it's indeed a "service" (and not just app calling itself like that) and also post a full and short names of that service from there ?

Also I'm not sure if it's worth even disabling that, as it's not part of Asus System Control Interface / MyASUS package that G-Helper stops / starts.

**Comment by d-anez3** [comment]
> @d-anez3 hello, can you open windows Services app, check if it's indeed a "service" (and not just app calling itself like that) and also post a full and short names of that service from there ?
> 
> Also I'm not sure if it's worth even disabling that, as it's not part of Asus System Control Interface / MyASUS package that G-Helper stops / starts.
Yes it is a Windows service. No details
![image](https://github.com/user-attachments/assets/a12709a8-bae8-47c5-9010-929e52d554a5)

**Comment by seerge** [comment]
@d-anez3 ok, do you know what it does ?

This build should be able to count and stop / start it, so please check
[GHelper.zip](https://github.com/user-attachments/files/16820520/GHelper.zip)

**Comment by d-anez3** [comment]
> @d-anez3 ok, do you know what it does ?
> 
> This build should be able to count and stop / start it, so please check [GHelper.zip](https://github.com/user-attachments/files/16820520/GHelper.zip)

yep works fine

not sure what it does, only noticed it today. a google search says it seems to be related to the trackpad? like on ASUS laptops that have a numpad overlayed on top of the trackpad

**Comment by seerge** [comment]
@d-anez3 if it may be responsible for overlayed trackpad I actually think that it may not be a good idea to stop it at all then as G-Helper doesn't handle that anyhow.

I think it would be better if you would just stop it manually if you personally don't need it :)

**Comment by seerge** [comment]
Ok, after digesting this, i don't think it's a good idea to stop that in a bundle :) So I don't be adding this to the list for now.

You can manually disable service of course if you don't need

Thanks

**Comment by Solarriors** [comment]
ASUS Precision TouchPad service, installed when one updates the touchpad drivers from ASUS website. Most of the gestures and features are handled by windows anyway.
