### ISSUE TITLE
Fan Control RPM Temp Bug

### ISSUE THREAD

**Issue by CitrusOVA** [seerge/g-helper#3034]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

https://github.com/user-attachments/assets/1237b9f8-8003-4357-89dd-356976cec3ab

I use ghelper to set fan speed at a certain temp. But it seems ghelper ignores temp and just follows whatever RPM the 3rd point is set to. Strange issue I am having. I have posted a video of my issues along with captions. 

### How to reproduce the bug?

1. Open Ghelper fan control 
2. Adjust 3rd point to a set temperature and fan rpm
3. 3rd point rpm will be set regardless of  actual temp. 

### Logs

[log.txt](https://github.com/user-attachments/files/16821787/log.txt)

### Device and Model

ROG Zephyrus G14 GA402XY_GA402XY

### Additional information.

See video for issue. 

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.184.0

### OS

Version 10.0.22631 Build 22631

**Comment by seerge** [comment]
@CitrusOVA hello,

G-Helper does not control your fans in realtime, they are controlled by BIOS. [Please make yourself familiar with FAQ.](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)

If you don't like how BIOS behaves with the custom fan curves, you can adjust them or use [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)

Thanks
