### ISSUE TITLE
[Zephyrus G15 2021] GPU fan won't work according to the fan curve setup in G-Helper

### ISSUE THREAD

**Issue by ntphuc295** [seerge/g-helper#3038]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I noticed my laptop was hotter than it should be. I checked on the G-helper interface, and it looked like the GPU fan was not spinning according to the curve I had set, which meant that it was thermal throttling. I tried going back to default settings after changing the fan curve for the CPU and GPU, but still, only the CPU fan ran according to the setup curve while the GPU did not. 

### How to reproduce the bug?

1. Open G-Helper
2. Setup the CPU and GPU fan curve
3. Tick the "Apply Custom Fan Curve"
4. Open a GPU-intensive app

### Logs

[log.txt](https://github.com/user-attachments/files/16823805/log.txt)

### Device and Model

Asus ROG Zephyrus G15 GA503QS

### Additional information.

Expected behavior:
GPU fan should spin according to the fan curve set.
Screenshots:
![image](https://github.com/user-attachments/assets/64101da3-69d9-4d38-b75c-31d697ea1099)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.84.0

### OS

Windows 11 Pro 64-Bit (10.0, Build 22631)

**Comment by seerge** [comment]
@ntphuc295 hello, fans are controlled by BIOS, not by the app. [Please check FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)

If you don't like how firmware controls fans, you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)

> How does G-helper control my fan speeds?
>It doesn't and can't control your fans. Your firmware / BIOS controls them in real-time. Armoury also doesn't control fans in real time anyhow.

>What G-helper can do - is (optionally) set a custom fan profile to the current performance mode consisting of 8 pairs of temperature + fan speed % via the same endpoint Armoury uses when sets custom fan profile in it's Manual mode.

> How it will be interpreted - is still up to the firmware. If you don't like how firmware controls fans, you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)

Thanks
