### ISSUE TITLE
Custom Fan Curve Support is Possible on most Asus Laptops

### ISSUE THREAD

**Issue by Astra060** [seerge/g-helper#3039]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

This is a problem in a way. I have an A15 - FA506IV and it says that Custom Fan Curves is not support, but... it is through different methods. 

### Describe the solution you'd like

AsusFanControl & AsusFanControlEnhanced. They use AsusWinIO64.dll to implement custom fan control which is working. The problem with AsusFanControlEnhanced is that it resets itself every few seconds and is unstable. Custom Curves with Combination of Hardware and Software Controls can be implemented I think. AsusFanControl even offers a CLI.

### Device and Model

Asus TUF FA506IV

**Comment by seerge** [comment]
@Astra060 hello, it's [already possible](https://github.com/seerge/g-helper/discussions/2272) and your question is literally answered in [FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)

> **How does G-helper control my fan speeds?**
> It doesn't and can't control your fans. Your firmware / BIOS controls them in real-time. Armoury also doesn't control fans in real time anyhow.

>What G-helper can do - is (optionally) set a custom fan profile to the current performance mode consisting of 8 pairs of temperature + fan speed % via the same endpoint Armoury uses when sets custom fan profile in it's Manual mode.

> How it will be interpreted - is still up to the firmware. If you don't like how firmware controls fans, you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)

**Comment by Astra060** [comment]
> @Astra060 hello, it's [already possible](https://github.com/seerge/g-helper/discussions/2272) and your question is literally answered in [FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)
> 
> > **How does G-helper control my fan speeds?**
> > It doesn't and can't control your fans. Your firmware / BIOS controls them in real-time. Armoury also doesn't control fans in real time anyhow.
> 
> > What G-helper can do - is (optionally) set a custom fan profile to the current performance mode consisting of 8 pairs of temperature + fan speed % via the same endpoint Armoury uses when sets custom fan profile in it's Manual mode.
> 
> > How it will be interpreted - is still up to the firmware. If you don't like how firmware controls fans, you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)

Thanks for quick reply. I have seen this, but it wasn't on the main channel, so I was wondering why not just add it in. Plus this seems to not function as intended which my set Fan Speed being around 10% lower the amount I set it to. Will this be merged into the next release? Or any future release?

**Comment by seerge** [comment]
@Astra060 mainstream build offers same functionality as Armoury Crate does (i.e. can set a custom fan curve same as AC in Manual mode **if device supports** that in a first place)

Experimental build uses absolutely different and unofficial approach, so I don't plan to mix that atm.
