### ISSUE TITLE
A few new translations in CrowdIn?

### ISSUE THREAD

**Issue by Sontarr** [seerge/g-helper#3040]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

No, not a problem.

### Describe the solution you'd like

I would like to translate the new "Donate"-Button as well as the new strings in the update section: "legend", "can't check local version", "updated" and "update available", but I can't find them in CrowdIn.

### Device and Model

Asus Zephyrus M16 2023 GU604VY

### Additional information.

Thanks for your work on G-Helper!

**Comment by seerge** [comment]
@Sontarr hello, thanks for pointing out.

I usually add labels to translations after some time (as soon as I understand that UI won't change)

You now should be able to translate Donate, Legend and Gray / Green / Red labels via [Crowdin ](https://crowdin.com/project/g-helper/translations) now

Thanks
