### ISSUE TITLE
Use G-Helper to control ASUS Mini-Led installed in other laptops

### ISSUE THREAD

**Issue by advanced03** [seerge/g-helper#3044]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Inability to toggle between Mini-LED and single zone brightness.

### Describe the solution you'd like

Hi, the title might sound strange but it's possible to install the NE160QDM-NM7 panel used in the ASUS ROG STRIX SCAR 2024 in other laptops.

Armory crate doesn't seem to recognize the new screen, so I was wondering if you could somehow tweak the program to recognize the ASUS display so that modders can enable single display brightness in their laptops as well.

### Describe alternatives you've considered

Trying CRU to toggle it, unfortunately didn't work.

### Device and Model

Asus ROG Strix Scar 2024 / Legion 5 Pro

### Additional information.

https://panelook.com/NE160QDM-NM7_BOE_16.0_LCM_overview_63299.html

https://rog.asus.com/laptops/rog-strix/rog-strix-scar-16-2024/helpdesk_download/

**Comment by seerge** [comment]
@advanced03 hello, it's simply not possible.

Both AC and G-Helper just give you access to the features and settings already existing on your device and exposed in firmware / BIOS via Asus System Control Interface.

The Miniled toggle G-Helper shows is a single OFF / ON (or OFF / ON / STRONG in case of Strix 2024) switch. If it's not available for your model - you can't toggle anything.

Sorry and thanks

**Comment by masteryf** [comment]
Hey, have you found any solution yet? My laptop model is GU603ZX, and I have also replaced the NE160QDM-NM7 panel. Have you found a way to switch single zone brightness now?

**Comment by seerge** [comment]
@masteryf i really doubt it will be any software solution for that :) as as I explained above is based on toggle existing in BIOS and exposed to apps.

**Comment by masteryf** [comment]
Actually, I noticed that when my computer is in BIOS or booting, this panel is single zone, and it only switches to multi zone when I enter the Windows login interface. So I suspect that this panel can also switch partitions on older models, but Asus did not provide this feature in the software

**Comment by advanced03** [comment]
> Hey, have you found any solution yet? My laptop model is GU603ZX, and I have also replaced the NE160QDM-NM7 panel. Have you found a way to switch single zone brightness now?



> @masteryf i really doubt it will be any software solution for that :) as as I explained above is based on toggle existing in BIOS and exposed to apps.

No unfortunately not, only someone with a Asus laptop got it working but then again his laptop never supported mini led as well. So I don't think it's a bios thing.
