### ISSUE TITLE
Add X543UB Fan RPM

### ISSUE THREAD

**Issue by Nova9980** [seerge/g-helper#3049]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Fan RPM doesn't show on G-helper this laptop. Windows 10 21H2 64bit and G-Helper v0.187.0 (latest g-helper version as of this request)

### Describe the solution you'd like

The solution is the fan rpm should be readable and displayed in g-helper. It does show in the bios so i think it is possible to read it. Bios version is X540UBR.308.

### Device and Model

Asus Vivobook X543UB-I581GT

**Comment by seerge** [comment]
@Nova9980 hello,

Your device doesn't support custom fan curves as I understand (same as any other Vivobook), and also doesn't have standard endpoints that report fan speeds (that exist on ROG / TUF / ProArt and some other models)

You can use [Experimental build with a manual fan control ](https://github.com/seerge/g-helper/discussions/2272) - it should be able to do both - show fan RPMs and even set (optional) custom fan curves for your model.

**Comment by seerge** [comment]
@Nova9980 does the experimental build show speeds / temps for you ?
