### ISSUE TITLE
Ambient color profile Killing the Keyboard

### ISSUE THREAD

**Issue by RageMasterSlow** [seerge/g-helper#3053]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hello! I have the **ASUS ROG Zephyrus G16 2023 GU603VV _[4060 + i7 13620H]_** and I **downgraded** to Windows 10 due to personal reasons.

When I had the laptop first and downgraded to W10 the ambient lighting worked perfectly, no issues found. But when I **downgraded the second time** _[I wanted tiny 10 but, realized it removed dolby atmos so I had to go back to W11 and then downgrade again to W10]_ it just **killed the laptop's keyboard for a few seconds or a few minutes and then would just come back** _[Except the M keys and Backlight]_.

I haven't had a solution to this problem one bit but I really really love this ambient feature. Can you help me? 

### How to reproduce the bug?

1. From any color profile to Ambient
2. Use for a while
3. Keyboard dies, except the M keys and Backlight
4. Comes back after a few seconds or minutes

### Logs

[log.txt](https://github.com/user-attachments/files/16838496/log.txt)

### Device and Model

ASUS ROG Zephyrus G16 GU603VV _[4060 + i7 13620H]_

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.184.0

### OS

Windows 10 Home 22H2

**Comment by seerge** [comment]
@RageMasterSlow hello, i was answering this few times already  https://github.com/seerge/g-helper/issues/1769 https://github.com/seerge/g-helper/issues/1911 etc

Some M16 and G16 from 2023 have a **firmware** issue with keyboards, that when it is set to change color to often - it can become unresponsive. It can be triggered by pretty much any AuraSync mode in Armoury or by Ambient mode here (cause it by definition changes color)

So if your keyboard is affected - the only solution for you is use any other mode, except Ambient

Besides that I can't really do anything else . Thanks

**Comment by RageMasterSlow** [comment]
Aw, thank you for responding and for explaining me the reason. Really appreciate it and thank you for making GHelper and sorry to make a duplicate thread, I should've researched before making it.

**Comment by seerge** [comment]
@RageMasterSlow on a side note, based on feedback from people affected, it seem to happen after some keyboard inactivity btw. I.e. when you don't use it for a while - it seem to go to "sleep" and then it takes few seconds to wake up.

**Comment by RageMasterSlow** [comment]
I see, but my case **also affects when the keyboard is in use.** Example: Something that **isn't graphics demanding** game like Terraria, the keyboard would die as the reason for constant color change. Now, **prior to my knowledge** that it was Ambient causing the issue I used to **open On-Screen Keyboard** _[I have it pinned on my start menu in case the keyboard dies]_ which **sometimes** fix the issue of the dead keyboard.

**Comment by seerge** [comment]
@RageMasterSlow can you test if restarting G-Helper (i.e quitting and starting over) wakes up keyboard by any chance ? Reason is that there is some init commands that app sends to keyboard when starts, and I was curious if they have any effect on that.

**Comment by RageMasterSlow** [comment]
Sure, I'll try it as soon as the keyboard dies once again, I'll update you 👍

**Comment by RageMasterSlow** [comment]
Unfortunately restarting it had no affect unfortunately 😔

I quit GHelper from my tray menu and started it back up but it didn't bring back the keyboard's functionality.

**Comment by seerge** [comment]
@RageMasterSlow ok, good to know. My idea was to send that init commands periodically for G16/M16, but apparently it doesn't make sense.

Can you also check if changing backlight mode (or doing any other manipulation with keyboard) by any chance wakes it up ?

**Comment by RageMasterSlow** [comment]
Okay, I **can confirm one thing** is that if I **switch from Ambient to Static**, after a **few seconds the keyboard's functionality does come back**. If you would like to know how many seconds that takes I can time it if needed.

**Comment by RageMasterSlow** [comment]
Yes, the **problem would be the delay**. Normally just staying on Ambient and letting it come back after a few long seconds or minutes didn't help me. So, **previous instances I used to experiment to figure out what should be the case if I went to Static**. Surprisingly the **time it took for the keyboard to come back would be significantly faster rather than just waiting on Ambient**. Ever since that day I just stuck with Static 😔

**Comment by seerge** [comment]
@RageMasterSlow i have one more thing to test in your case, try this build. Instead of setting backlight dynamically it will just set a new "static" mode every time it needs to change color

[GHelper.zip](https://github.com/user-attachments/files/16853418/GHelper.zip)

**Comment by RageMasterSlow** [comment]
I see, I'll give it a shot 👍

**Comment by RageMasterSlow** [comment]
I believe I found something interesting? You mentioned how the **constant change of colors killed the keyboard's functionality yes?** So, **I tried something**. 

 **Multiple tabs** _[I already have multiple tabs open due to my studies]_ and **just kept CTRL + Tab through them and for a solid 10 mins the keyboard didn't die during that process**. **After it died**, I **immediately switched over to Static** and **after 3~5 seconds the keyboard was alive again**.  

The **very first attempt of me using this build**, I set some **video that changes color too often** and **again for 13 mins it did not die, set it to Static it came back after 3~5 seconds**.

**Second attempt** was me **going through multiple tabs but this time the keyboard died very fast, almost instantly**. This time **setting it to Static did not bring it's functionality, I used the old** _(basically current GHelper)_ **Static which did bring the keyboard back**.

_Third attempt is the very first thing I mentioned._

**Comment by seerge** [comment]
@RageMasterSlow it's a bit difficult to understand you tried. 

But do I understand correctly that the build I linked here still behaves same (i.e. keyboard may stop responding eventually) ?

**Comment by RageMasterSlow** [comment]
Sorry I should've explained more clearly! But, **yes the build linked here still behaves same/similar**. 

What I tried was (on the linked build) **having the keyboard change color deliberately while being on Ambient**. I had **browser tabs open so I just cycled through them continuously which forced the backlight color to change**. Did it for **10 to 13 mins until it died**. I then **decided to switch over to Static which would result for the keyboard's functionality to come back immediately/3~5 seconds**.
_Just on another attempt I had to go to the current build (old one) and use that Static for the keyboard to function_.

**Whereas**,

**On the current build (old one)** it **would take far longer for the keyboard to function after setting it to Static**.

**Comment by seerge** [comment]
@RageMasterSlow ok, but each color change is also effectively "static" command. Just when you set it manually you are obviously prevent any further color changes.

Do you know how many seconds of such intensive color changes lead to keyboard becoming unresponsive ? I can add artificial pauses in color changes like every 10 seconds or so (it won't look pretty tho, but it's better anyway)

**Comment by RageMasterSlow** [comment]
Yes, you do have a point.

I can time that out if needed if you would like me to. Before any further steps are taken if you don't mind, I would like to experiment with this current linked build's Ambient and figure out if the keyboard dies again in the long term such as gaming, multitasking, etc.

And the artificial pauses would really ruin the whole aesthetic vibes I yearn for 😭 I'll try my best to provide as much as information if you allow me to test with this linked build. Could you please?

**Comment by RageMasterSlow** [comment]
So far, it's been 43 minutes since the comment posted using Ambient and the keyboard hasn't died once so, if you don't mind I'll give a proper conclusion in 12/24 hours by using this linked build.

**Comment by RageMasterSlow** [comment]
@seerge Hello! **I bring some good news!**

The **keyboard has not died yet!** I've typed, gamed and also flat out started editing _[meaning GPU mode is not the issue]_ and the **keyboard worked flawlessly**. The **laptop hasn't been shut down or restarted in this whole period.** 

One thing I did notice w**hich happened only once** would be when **I plugged the laptop in the keyboard would stop for a few seconds and then come back**. **Same goes for when unplugging the laptop**. 
_[This event happened only once, other than that all other times of plugging it in and unplugging it didn't kill the keyboard]_.

**Comment by seerge** [comment]
@RageMasterSlow ok, so actually test build i linked here works fine for you ? Cause when I asked about that above - you mentioned that it behaves same (i.e. keyboard hangs)

**Comment by seerge** [comment]
@RageMasterSlow ok, good to know. Can you use it for a next few days and post an update here ? If so - I can add this as a "fix".

As anyway, some models (like old G15 2021 or also new G14 2024) also don't support "dynamic" color settings at all. And G-Helper already does same trick for them to imitate Ambient mode by constantly setting new "static" mode every time color needs to change.

**Comment by RageMasterSlow** [comment]
Sure! I'll use the color profile for the upcoming days and update you.

**Comment by seerge** [comment]
@RageMasterSlow hello, did you experience any unresponsiveness with keyboards over last days using new build ?

**Comment by seerge** [comment]
@RageMasterSlow ok, thanks for an update.

But when it becomes unresponsive during inactivity - can you check if restarting G-Helper (and running "init" commands) by any chance wakes it up ? I know that it didn't help when it was hanging during usage, but may be inactivity case is different ?

I'm asking cause someone else reported this to be the case, but i couldn't verify it.

**Comment by RageMasterSlow** [comment]
Sure, I'll give it a shot when it happens again

**Comment by RageMasterSlow** [comment]
As soon as I said it, it died 💀

And from what I see restarting GHelper did bring back its functionality, I could give another test if needed.

**Comment by seerge** [comment]
@RageMasterSlow ok,

Can you try and use this build instead. What it will do is send "init" command after every 10 color changes.

[GHelper.zip](https://github.com/user-attachments/files/16906949/GHelper.zip)

**Comment by RageMasterSlow** [comment]
Sure, I'll give it a shot _(sorry I was away)_.

**Comment by RageMasterSlow** [comment]
Unfortunate news, it died once again.

**Comment by seerge** [comment]
@RageMasterSlow ok, then apparently init command does not wake up keyboard :)

**Comment by RageMasterSlow** [comment]
So, is this the end...? I mean I tried my best to help and you did make an improved version! Normally it would just die 10/15 times a day and taking very long time to come back but, the frequency on these new builds came down all the way to some little has 2/3 times but not a day but in the span of 2 days and also after long hours of usage and also taking mere seconds to come back too.

**Comment by seerge** [comment]
@RageMasterSlow well, i'm honestly out of ideas :) As becoming unresponsive during inactivity - is something couple of other people with M16 or G16 reported. 

Ambient frequency is already as low as it possible - 3 times per second. Making it update color even less frequent - just kills whole purpose of the ambient, as then it just looks choppy.

Btw you can set that in config manually
```
"aura_refresh" : 300,
```

Where value - is refresh interval in milliseconds.

**Comment by RageMasterSlow** [comment]
I see 😥

While I'm using this build I'll try to figure out if I can find anything new. If not, well you gave me an improved version of the problem so, I'll be using that as its better than having to deal with the past problems. And also, Thank You Very Much.

**Comment by seerge** [comment]
@RageMasterSlow you can try to find some pattern that leads to unresponsiveness during inactivity. If it's something that can be prevented (like stopping color changes when you don't use keyboard or so) - i can try to add that.
