### ISSUE TITLE
Disable on lid close option makes no difference

### ISSUE THREAD

**Issue by amdk1** [seerge/g-helper#3054]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi there, 
I'm on version 0.187.0 of G-Helper. My strip lighting turns off when I close the lid even though the "Disable on lid close" option is unchecked. Checking it makes no difference to the behavior. 

### How to reproduce the bug?

1. uncheck "Disable on lid close"
2. close lid - slash lighting turns off

### Logs

[log.txt](https://github.com/user-attachments/files/16840908/log.txt)

### Device and Model

Asus Zephyrus G14 GA403UV

### Additional information.

I tried reinstalling armory crate. The slash lighting was working as expected with AC's settings (only when using AC lighting presets), however, once I uninstalled AC and switched back to g-helper, the slash lighting went back to turning off on lid close. 

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.187.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@amdk1 hello, i see that you use `battery level` mode. This one is custom and app manually sets slash lighting pattern based on current battery level every minute. 

What happens if you would set any other mode (that is baked into firmware) ?

**Comment by amdk1** [comment]
I just tried some of the built-in armory crate modes, the lighting still turns off on lid close.

**Comment by seerge** [comment]
@amdk1 ok, can you check if behavior is same when laptop is plugged and and on battery ?

**Comment by amdk1** [comment]
Just tried this, it's working as expected when plugged in on all lighting modes.

**Comment by seerge** [comment]
@amdk1 ok, i think it's a firmware-level behavior of a slash lighting to preserve battery actually.

Do you have `Disable on battery` checked in the app by any chance ?

**Comment by amdk1** [comment]
Disable on battery is unchecked, the lighting turns off completely when it's checked on battery. 

I just played around a bit with the lighting with the charger plugged in, the slash lighting behavior is inconsistent even on lid close while plugged in.

The lighting is behaving differently depending on when the laptop is plugged in:

scenario one: 
1. Laptop is already plugged in and the lid is open
2. Disable on lid close is unchecked 
3. Lid is now closed
4. The selected lighting mode does not play, but the slash lighting starts the breathing animation as it's charging

Scenario two:
1. The laptop is not plugged in and the lid is closed (same g-helper settings as scenario one)
2. The laptop is then plugged in while the lid is closed
3. The selected lighting mode animation plays 3 times before reverting to the breathing animation in scenario one

**Comment by seerge** [comment]
@amdk1 can you check if this build makes any difference ?

[GHelper.zip](https://github.com/user-attachments/files/16841210/GHelper.zip)

**Comment by amdk1** [comment]
It's working with the lid closed on all armory crate lighting modes now. 

"Static" and "battery level" modes only work while the lid is open. Upon closing the lid with either of these two modes, the lighting reverts to the last selected armory crate lighting mode.

Battery level also seems to not work anymore as all 5 zones are lit up while I have a charge level of 77.4%

**Comment by seerge** [comment]
@amdk1 ok,

I think in case of Static and Battery level modes - it can't be changed, as they are "software modes" (i.e. app manually sets pattern) and apparently firmware is programmed to shut it down on lid close

As for the rest - does it work in all conditions (ie. plugged in / unplugged) ? Also does `Disable on battery` action work correctly still ?

**Comment by amdk1** [comment]
Apologies for the delay, I didn't have my charger with me. All the non-software/AC modes are working both plugged in / unplugged. Disable on battery is also working as expected :)

**Comment by seerge** [comment]
@amdk1 great
