### ISSUE TITLE
Turbo Mode cannot control the GPU Fan speed

### ISSUE THREAD

**Issue by medking82** [seerge/g-helper#3058]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I play BlackMyth：WuKong，my setting turbo fan curve is not work, the GPU fan speed stay at 2800RPM, cannot fully running.

### How to reproduce the bug?

Sometimes will happen, need to manually turn the fanspeed to 100%

### Logs

[log.txt](https://github.com/user-attachments/files/16843936/log.txt)

### Device and Model

Asus ROG Zephyrus G14 GA401QM

### Armoury Crate

Uninstalled

### Version

0.187.0

**Comment by seerge** [comment]
@medking82 hello, please make yourself familiar with FAQ

> [How does G-helper control my fan speeds?](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)
> It doesn't and can't control your fans. Your firmware / BIOS controls them in real-time. Armoury also doesn't control fans in real time anyhow.

> What G-helper can do - is (optionally) set a custom fan profile to the current performance mode consisting of 8 pairs of temperature + fan speed % via the same endpoint Armoury uses when sets custom fan profile in it's Manual mode.

> How it will be interpreted - is still up to the firmware. If you don't like how firmware controls fans, you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)


Thanks

**Comment by medking82** [comment]
Thanks for your help
