### ISSUE TITLE
Fan Speed Issue with .187.0

### ISSUE THREAD

**Issue by rhinehramirez** [seerge/g-helper#3061]
### Discussed in https://github.com/seerge/g-helper/discussions/3060

<div type='discussions-op-text'>

<sup>Originally posted by **rhinehramirez** September  3, 2024</sup>
Manually updated to .187.0 and now my fan speeds show 0 RPMs. After rebooting, the fan speeds show correctly, but after short amount of time (5-10 minutes), the issue persists. See screenshot. 
![Screenshot 2024-09-03 111451](https://github.com/user-attachments/assets/b7b82554-1f4c-4f19-ba9a-baa589460c46)
</div>

**Comment by seerge** [comment]
@rhinehramirez 

1. Your fans are controlled by BIOS, [please make yourself familiar with FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)
2. Your temps are low and you are in a silent mode, so obviously fan is OFF, no reason for it to run
3. There is absolutely nothing changed in this regard in last release
4. You have demonstratively [ignored issue template](https://github.com/seerge/g-helper/issues/new/choose)
