### ISSUE TITLE
Fan Reporting Issue - 0.187.0 - when in balanced/standard profiles during light task work. 

### ISSUE THREAD

**Issue by rhinehramirez** [seerge/g-helper#3062]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

After manually updating from 0.184.0 to 0.187.0, fan speed will intermittently report 0%/0RPMs.
![Screenshot 2024-09-03 122413](https://github.com/user-attachments/assets/d2d00474-2d93-4b37-be32-d460bfed8bc6)

### How to reproduce the bug?

1. Launch G-Helper. 
2. Wait 5-10 minutes. 
3. Check fan speeds.
4. Reboot computer. 
5. Launch G-Helper. 
6. Check fan speeds.
7. Wait 5-10 minutes. 
8. Check fan speeds. 
9. Fan speeds will intermittently show 0%/0RPMs when in balanced/standard profiles.

### Logs

[log.txt](https://github.com/user-attachments/files/16853925/log.txt)

### Device and Model

Asus Zephyrus G14 GA403UI

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.187

### OS

Windows 11 23H2 (OS Build 22631.4412)

**Comment by seerge** [comment]
@rhinehramirez hello, I have already answered you in [your previous issue.](https://github.com/seerge/g-helper/issues/3061)

[Fans are controlled by BIOS, not by G-Helper.](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds). On your screenshot you have a very low temperatures, so obviously fans are turned OFF. Everything is absolutely fine.

Please stop spamming. You have created 3 posts with same question.

**Comment by rhinehramirez** [comment]
> @rhinehramirez hello, I have already answered you in [your previous issue.](https://github.com/seerge/g-helper/issues/3061)
> 
> [Fans are controlled by BIOS, not by G-Helper.](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds). On your screenshot you have a very low temperatures, so obviously fans are turned OFF. Everything is absolutely fine.
> 
> Please stop spamming. You have created 3 posts with same question.

I understand fans are controlled by BIOS, I'm saying this is a REPORTING problem. Not a control issue.

**Comment by seerge** [comment]
@rhinehramirez what exactly is reported incorrectly ? When fans are turned off, they obviously report 0RPM.

G-Helper takes fan speeds from asus endpoints (same as Armoury uses).

**Comment by rhinehramirez** [comment]
Fair enough. When I was on the previous version of G-Helper, I never saw fan speeds reported at 0%. I have not changed my workstyles/workflow in any capacity.

**Comment by seerge** [comment]
@rhinehramirez probably before your laptop was running warmer, so BIOS was turning fans on.

Changes between 0.187 and 0.184 are not related to fans settings or fan speed readings https://github.com/seerge/g-helper/compare/v0.184...v0.187
