### ISSUE TITLE
Issues with the "automatically switch to lid close mode" on the ASUS TUF Gaming F15 FX507VV laptop.

### ISSUE THREAD

**Issue by zxzxzx25** [seerge/g-helper#3064]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Whether the "automatically switch to lid close mode" is checked or not, attempting to change it will cause the notebook's Windows power management to switch to "lid close shutdown".

### How to reproduce the bug?

Attempt to change the "automatically switch to lid close mode" option.

### Logs

[log.txt](https://github.com/user-attachments/files/16862832/log.txt)

### Device and Model

ASUS TUF Gaming F15 FX507VV

### Additional information.

<img width="378" alt="屏幕截图 2024-09-04 154323" src="https://github.com/user-attachments/assets/0c2046db-1830-45f6-8673-c54380ca36ff">
<img width="839" alt="屏幕截图 2024-09-04 155133" src="https://github.com/user-attachments/assets/24c09e59-13d0-4584-9428-72278704b7b8">

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.187.0 or o.186.0

### OS

windows11 22h2

**Comment by seerge** [comment]
@zxzxzx25 hello,

When this checkbox (`Clamshell mode`) is  ON 
- it automatically sets `Lid Close` action to `None` when laptop is plugged in + has external monitor connected
- it sets `Lid Close` action back to whatever you had initially when laptop is unplugged or doesn't have external monitor

When checkbox is OFF - it sets `Lid Close` action back to whatever you had in power plan setting before

If you don't use Clamshell mode, just uncheck it and set your lid close action manually in power plan 
If you do use it - you can configure / override default behavior [as explained in readme as well](https://github.com/seerge/g-helper/wiki/Power-user-settings#lid-close-action-when-clamshell-mode-is-off)

**Comment by zxzxzx25** [comment]
Thank you very much for your reply. However, the issue I'm facing is that when the checkbox is either turned off or on, and I change it, it always gets set to "shut down when the lid is closed".

**Comment by seerge** [comment]
@zxzxzx25 as I have explained above - if you uncheck it, app would revert power plan setting you **had before**. In your case it is Shutdown.

You can adjust that in a config [as explained in readme](https://github.com/seerge/g-helper/wiki/Power-user-settings#lid-close-action-when-clamshell-mode-is-off)

**Comment by zxzxzx25** [comment]
It doesn't revert back.

**Comment by seerge** [comment]
@zxzxzx25 please read my answer, you are clearly not doing so.

**Comment by zxzxzx25** [comment]
I think I can't express my meaning clearly with the help of translation software. I'm sorry for it.
![微信图片_20240904183147](https://github.com/user-attachments/assets/d8390027-23b4-405c-9d1e-c4aeb695899b)
![微信图片_20240904183158](https://github.com/user-attachments/assets/f676fdb0-9990-43e2-84c4-3f9091c5f543)
![微信图片_20240904183208](https://github.com/user-attachments/assets/9ff1d50c-7f7f-48c1-bde3-51321a59629f)
![微信图片_20240904183216](https://github.com/user-attachments/assets/2d5a9936-9e8f-4ab7-b43d-eeb67b73f99d)

**Comment by seerge** [comment]
You can adjust that in a config [as explained in readme](https://github.com/seerge/g-helper/wiki/Power-user-settings#lid-close-action-when-clamshell-mode-is-off)

**Comment by zxzxzx25** [comment]
It was my ignorance that caused the laughter. I know too little about it. He is indeed a great software.
