### ISSUE TITLE
hope to add a right-click menu to the tray icon

### ISSUE THREAD

**Issue by lswlc33** [seerge/g-helper#307]
**Is your feature request related to a problem? Please describe.**
I found that right-clicking on the taskbar icon directly opens the main window instead of a standard right-click menu. 

I noticed that the function to exit the application is included in the main window, which is not very harmonious because there are two similar exit buttons (close button) on the same interface. It is more reasonable to exit through the right-click menu. 

**Describe the solution you'd like**
I hope there is a right-click menu as shown in the following figure or some other shortcut functions (although these functions can be achieved through keyboard shortcuts).

The advantage of a right-click menu in the tray icon is that you don't need to close the menu after making changes, the menu will disappear automatically, which is very convenient.
![image](https://user-images.githubusercontent.com/86835895/235482612-60896a25-4ec8-4b71-9bbb-778f7d562041.png)

![image](https://user-images.githubusercontent.com/86835895/235480980-65830c53-9a68-44de-b747-7ecda8fd4b9e.png)

**Comment by seerge** [comment]
I quickly checked and adding a good looking (and supporting both lighht / dark) themes context menu is a huuuge pain in .NET7 that app i using. Therefore i'm not a big fan of adding a dublicate feature, since whole app is already designed to mimic win11 native tray menu :)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11396345/GHelper.zip)
You can check basic context menu here. But, honestly, i just consider such things as extra bloat ...

**Comment by lswlc33** [comment]
That is a good beginning 。₍˄·͈༝·͈˄*₎◞ ̑̑

Recently, I discovered that the OneDrive program on WINDOWS has a tray icon that, when clicked, opens a borderless floating window. When you click anywhere outside the window, it disappears. This is a great implementation for quick control of similar programs, as it allows for changes to be made in just two steps and quickly move on to other tasks. It is highly convenient. Your control panel could benefit from adopting this idea.

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11401988/GHelper.zip)
I have added GPU modes as well, it should be enough for now :)
