### ISSUE TITLE
more anime matrix customization?

### ISSUE THREAD

**Issue by LEveLiQ** [seerge/g-helper#3073]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

ive been thinking about a few more options for anime matrix customization, i understand if these ideas do not match your design principles, but please consider these quality of life improvements that ive thought

### Describe the solution you'd like

- turning it off after certain time of inactivity
- time based automatic switch for the leds (such as 7 AM~10 PM, so that it doesnt keep flashing all the time at night)
- 180 degrees rotation while the lid is closed (this totally is not necessary, but it would be cool if it has this)

### Describe alternatives you've considered

while these features won't really be necessary, it would be cool if you add these features while you have spare time for this. i wouldve contributed if i knew C# well, but sadly i do not, so im leaving this just as a feature suggestion.

### Device and Model

Zephyrus G14 GA402XZ

**Comment by seerge** [comment]
@LEveLiQ hello, I think it's quite exotic things to be honest. And you can also achieve them (indirectly) in other ways

> turning it off after certain time of inactivity

You can just set laptop to sleep after some time of inactivity, when it sleeps it would turn matrix off (or run sleep matrix "star fall" animation) 

> time based automatic switch for the leds (such as 7 AM~10 PM, so that it doesnt keep flashing all the time at night)

This would require adding a lot of UI elements to properly configure that (as night / day differ based on actual location, time of the year, etc). 

You can easily adjust matrix brightness up to completely turning it off using hotkeys `Fn + Shift + F7 / F8`. Same as you do for screen brightness when day / night changes.

> 180 degrees rotation while the lid is closed (this totally is not necessary, but it would be cool if it has this)

- For built in animations it's simply not possible (as they are encoded into firmware). 
- For GIFs / pictures - it's also not that easy to achieve as matrix is not a rectangle with cut off diagonal part. If you rotate picture other part of it will be cut off.

So I think it's too much for current app :) Thanks.

**Comment by LEveLiQ** [comment]
> @LEveLiQ hello, I think it's quite exotic things to be honest. And you can also achieve them (indirectly) in other ways
> 
> > turning it off after certain time of inactivity
> 
> You can just set laptop to sleep after some time of inactivity, when it sleeps it would turn matrix off (or run sleep matrix "star fall" animation) 
> 
> > time based automatic switch for the leds (such as 7 AM~10 PM, so that it doesnt keep flashing all the time at night)
> 
> This would require adding a lot of UI elements to properly configure that (as night / day differ based on actual location, time of the year, etc). 
> 
> You can easily adjust matrix brightness up to completely turning it off using hotkeys `Fn + Shift + F7 / F8`. Same as you do for screen brightness when day / night changes.
> 
> > 180 degrees rotation while the lid is closed (this totally is not necessary, but it would be cool if it has this)
> 
> - For built in animations it's simply not possible (as they are encoded into firmware). 
> - For GIFs / pictures - it's also not that easy to achieve as matrix is not a rectangle with cut off diagonal part. If you rotate picture other part of it will be cut off.
> 
> So I think it's too much for current app :) Thanks.

the thing is, the "star fall" animation barely works; usually when i put it to sleep the animation just gets stuck, i tried putting it to sleep manually, closed the lid, most of the time it just gets stuck, actually it was why i opened this issue at the first place, to find a workaround

for the other 2 ideas, yeah i knew it won't match your design principles

**Comment by seerge** [comment]
@LEveLiQ 

It gets stuck cause prior to properly going into sleep windows just suspends all processes (including G-Helper that plays your GIF). 

After that, windows puts device into hardware sleep and animation will play. But that's still up to windows and it's well famous sleep issues anyway.
