### ISSUE TITLE
ROG Ally Z1E Wrong GPU Temps

### ISSUE THREAD

**Issue by Palladrian** [seerge/g-helper#3074]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hello, basically what the title says.

In armoury crate the temperature is always higher than what g-helper mentions. The higher the temps the more it is off. For example when gpu is 45 degrees then ghelper says 42 but at about 70 degrees g-helper says only 60.

### How to reproduce the bug?

1. Check armoury crate temps
2. check g-helper temps

### Logs

[log.txt](https://github.com/user-attachments/files/16915049/log.txt)

### Device and Model

ROG Ally Z1 Extreme

### Armoury Crate

Uninstalled

### Asus Services

9

### Version

0.187.0

### OS

Windows 11 23H2 Build 22631.4037

**Comment by seerge** [comment]
@Palladrian hello,

Can you post a screenshots of your observations ? Cause G-Helper just takes GPU temp from AMD driver. What does AMD overlay show as temp in those moments ?

**Comment by Palladrian** [comment]
> @Palladrian hello,
> 
> Can you post a screenshots of your observations ? Cause G-Helper just takes GPU temp from AMD driver. What does AMD overlay show as temp in those moments ?

@seerge  Don't know why the amd overlay is not showing in the screenshot but it mentioned the same temps as the armoury crate so basically 69 degrees in this case while ghelper mentioned 60 on gpu.

<img width="670" alt="ghelper" src="https://github.com/user-attachments/assets/526769f0-8e16-47b4-9b21-d8adb36b144a">

**Comment by seerge** [comment]
@Palladrian on your screenshot AC overlay shows CPU temp (69C) and G-Helper shows same 69C

**Comment by Palladrian** [comment]
@seerge yes cpu temps are fine, however the screenshot does not include the AMD overlay which I had on and GPU Temp was 60C while AMD Overlay showed 67 degrees on GPU

**Comment by seerge** [comment]
@Palladrian you are saying that temp in AC is higher. On your screenshot temp reported by AC is **CPU temp** and it is **exactly same**. So here everything is correct.

As for AMD overlay - there are multiple sensors AMD can read. If you are looking at APU temp - it's same as CPU :) You can open AMD Adrenaline monitoring settings and it lists all possible readings it can show. Most likely you will find more sensors there, incluidng the one driver reports to G-Helper :)

**Comment by seerge** [comment]
![Screenshot 2024-09-07 121941](https://github.com/user-attachments/assets/3625c68e-8bb5-4260-bcb8-ae4372d675c8)

**Comment by Palladrian** [comment]
@seerge Hello again, here is another screenshot with my issue. No it is only 3C difference but as mentioned at about 70C it is already about 10C difference. I installed the 0.188 pre-release version now to see if that would fix it but as mentioned same happened in the 0.177 version

<img width="950" alt="gh1" src="https://github.com/user-attachments/assets/bbdb80a0-f437-4406-880f-c7547600d934">

**Comment by seerge** [comment]
@Palladrian actually I was wrong when I told that GPU temp is taken from AMD driver.

There is a dedicated GPU temp sensor / endpoint from Asus that G-Helper is reading. And it takes temp there with a fallback to AMD driver only if it's not there. Same happens for CPU temp.

So what Asus reports for GPU temp can be different from AMD driver a bit indeed. 

But it's a temperature that you see in GPU label is what **Asus BIOS uses to control corresponding fan**. So I guess it's more relevant than one from AMD.

**Comment by Palladrian** [comment]
@seerge Thank you very much! That solves my issue or rather question in this case :) By chance any plans on integrating frame gen in ghelper like it is in AMD/Armoury Crate?

**Comment by seerge** [comment]
@Palladrian if you mean a AMD frame gen toggle - then I might add it, but I don't know if it's officially documented by AMD on how to access that toggle.

But that toggle exists in AMD Adrenaline anyway, why don't you use it there directly ?

**Comment by Palladrian** [comment]
@seerge That is what I am going to do just wanted to ask if there are any plans on implementing as it would be cool to have it :)
