### ISSUE TITLE
莫名出现的悬浮栏

### ISSUE THREAD

**Issue by iforgiveu** [seerge/g-helper#3076]
![屏幕截图 2024-09-08 111542](https://github.com/user-attachments/assets/8b9a556f-4156-4be2-b724-e163e68e467b)

使用该软件后，我的电脑屏幕左上角就莫名其妙出现了这个悬浮菜单，怎么都关不掉

**Comment by JohnsonRan** [comment]
ALT + R `开启/关闭`
并且 这是 NVIDIA 的 `统计数据`

**Comment by seerge** [comment]
@iforgiveu this has absolutely nothing to do with the app.
