### ISSUE TITLE
M4 key missing when trying to assign hotkeys

### ISSUE THREAD

**Issue by SriHari-15** [seerge/g-helper#3079]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### Laptop Model: ROG Strix G713RM

My laptop keyboard supports upto M5 hotkeys however in the G-Helper app the **M4 key is missing** in the hotkey section.

Picture of the issue is attached below:
![image_2024-09-08_234024745](https://github.com/user-attachments/assets/c4ba25be-c34e-4daf-89ce-d735631c7d18)

### How to reproduce the bug?

- Open the G-Helper app
- Go to "Extras" section

### Logs

[log.txt](https://github.com/user-attachments/files/16923224/log.txt)

### Device and Model

Asus ROG Strix G713RM (2022)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.187.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@SriHari-15 hello,

I was answering this multiple times already https://github.com/seerge/g-helper/issues/2022 https://github.com/seerge/g-helper/issues/2157 

M4 and Fn+F5 emit same keycode on Strix devices. This key is reserved for toggling profiles forward, and Shift + Fn + F5 for toggling profiles backwards.

So It won't be bindable under Extra :)

Thanks
