### ISSUE TITLE
Cannot set display to 60Hz mode

### ISSUE THREAD

**Issue by gantugsmk** [seerge/g-helper#308]
**Describe the bug**
Cannot set display to 60Hz mode

**Clear scenario to Reproduce**
1. Go to G-Helper
2. Click on 60Hz
3. Does not work.

**Expected behavior**
The display's refresh rate should become 60Hz

**App Logs**
2023/05/02 21:30:57: ------------
2023/05/02 21:30:57: App launched: TUF Gaming FX505DY_FX505DY
2023/05/02 21:30:59: AutoSetting for Online
2023/05/02 21:30:59: PerformanceMode = 0 : OK
2023/05/02 21:30:59: Eco flag : -65536
2023/05/02 21:30:59: Mux flag : -65536
2023/05/02 21:30:59: Monitor Power On
2023/05/02 21:31:44: PerformanceMode = 1 : OK
2023/05/02 21:31:54: Screen = 60Hz : -2
2023/05/02 21:31:54: ScreenOverdrive = 0 : OK
2023/05/02 21:31:57: Screen = 120Hz : OK
2023/05/02 21:31:57: ScreenOverdrive = 1 : OK
2023/05/02 21:32:02: TUF RGB = B4-01-FF-FF-FF-EB-00-00-00-00-00-00 : OK
2023/05/02 21:32:04: TUF RGB = B4-00-FF-FF-FF-EB-00-00-00-00-00-00 : OK
2023/05/02 21:32:05: BatteryLimit = 85 : OK
2023/05/02 21:32:06: BatteryLimit = 90 : OK
2023/05/02 21:32:06: BatteryLimit = 95 : OK
2023/05/02 21:32:07: BatteryLimit = 90 : OK
2023/05/02 21:32:07: BatteryLimit = 85 : OK
2023/05/02 21:32:07: BatteryLimit = 80 : OK
2023/05/02 21:32:07: BatteryLimit = 75 : OK
2023/05/02 21:32:07: BatteryLimit = 70 : OK
2023/05/02 21:32:07: BatteryLimit = 65 : OK
2023/05/02 21:32:08: BatteryLimit = 60 : OK
2023/05/02 21:32:08: BatteryLimit = 55 : OK
2023/05/02 21:32:08: BatteryLimit = 50 : OK
2023/05/02 21:32:08: BatteryLimit = 55 : OK
2023/05/02 21:32:08: BatteryLimit = 60 : OK
2023/05/02 21:32:08: BatteryLimit = 65 : OK
2023/05/02 21:32:08: BatteryLimit = 70 : OK
2023/05/02 21:32:08: BatteryLimit = 75 : OK
2023/05/02 21:32:08: BatteryLimit = 80 : OK
2023/05/02 21:32:08: BatteryLimit = 85 : OK
2023/05/02 21:32:08: BatteryLimit = 90 : OK
2023/05/02 21:32:08: BatteryLimit = 95 : OK
2023/05/02 21:32:08: BatteryLimit = 100 : OK
2023/05/02 21:32:08: BatteryLimit = 95 : OK
2023/05/02 21:32:08: BatteryLimit = 90 : OK
2023/05/02 21:32:10: BatteryLimit = 85 : OK
2023/05/02 21:32:11: BatteryLimit = 90 : OK
2023/05/02 21:32:23: Boost 2
2023/05/02 21:32:29: PerformanceMode = 2 : OK
2023/05/02 21:32:38: GPUEco = 1 : 0
2023/05/02 21:32:38: Eco flag : -65536
2023/05/02 21:32:38: Mux flag : -65536
2023/05/02 21:32:46: Screen = 120Hz : OK
2023/05/02 21:32:46: ScreenOverdrive = 1 : OK
2023/05/02 21:32:47: GPUEco = 1 : 0
2023/05/02 21:32:48: Eco flag : -65536
2023/05/02 21:32:48: Mux flag : -65536
2023/05/02 21:32:48: Screen = 120Hz : OK
2023/05/02 21:32:48: ScreenOverdrive = 1 : OK
2023/05/02 21:34:48: ------------
2023/05/02 21:34:49: App launched: TUF Gaming FX505DY_FX505DY
2023/05/02 21:34:49: AutoSetting for Online
2023/05/02 21:34:49: BatteryLimit = 90 : OK
2023/05/02 21:34:49: BatteryLimit = 90 : OK
2023/05/02 21:34:49: PerformanceMode = 2 : OK
2023/05/02 21:34:49: Eco flag : -65536
2023/05/02 21:34:49: Mux flag : -65536
2023/05/02 21:34:50: Screen = 120Hz : OK
2023/05/02 21:34:50: ScreenOverdrive = 1 : OK
2023/05/02 21:34:50: Monitor Power On
2023/05/02 21:34:52: PerformanceMode = 1 : OK
2023/05/02 21:34:52: Boost 2
2023/05/02 21:35:01: PerformanceMode = 2 : OK
2023/05/02 21:35:25: WMI event 174
2023/05/02 21:35:25: PerformanceMode = 0 : OK
2023/05/02 21:35:27: WMI event 174
2023/05/02 21:35:27: PerformanceMode = 1 : OK
2023/05/02 21:35:27: Boost 2
2023/05/02 21:35:28: WMI event 174
2023/05/02 21:35:28: PerformanceMode = 2 : OK
2023/05/02 21:35:30: WMI event 174
2023/05/02 21:35:30: PerformanceMode = 0 : OK
2023/05/02 21:35:30: WMI event 174
2023/05/02 21:35:30: PerformanceMode = 1 : OK
2023/05/02 21:35:30: Boost 2
2023/05/02 21:35:30: WMI event 174
2023/05/02 21:35:30: PerformanceMode = 2 : OK
2023/05/02 21:35:31: WMI event 174
2023/05/02 21:35:31: PerformanceMode = 0 : OK
2023/05/02 21:35:31: WMI event 174
2023/05/02 21:35:31: PerformanceMode = 1 : OK
2023/05/02 21:35:31: Boost 2
2023/05/02 21:35:31: WMI event 174
2023/05/02 21:35:31: PerformanceMode = 2 : OK
2023/05/02 21:35:34: WMI event 124
2023/05/02 21:35:35: WMI event 124
2023/05/02 21:35:36: WMI event 124
2023/05/02 21:35:44: GPUEco = 1 : 0
2023/05/02 21:35:45: Eco flag : -65536
2023/05/02 21:35:45: Mux flag : -65536
2023/05/02 21:35:45: Screen = 120Hz : OK
2023/05/02 21:35:45: ScreenOverdrive = 1 : OK
2023/05/02 21:35:46: GPUEco = 1 : 0
2023/05/02 21:35:47: Eco flag : -65536
2023/05/02 21:35:47: Mux flag : -65536
2023/05/02 21:35:47: Screen = 120Hz : OK
2023/05/02 21:35:47: ScreenOverdrive = 1 : OK
2023/05/02 21:35:49: Screen = 60Hz : -2
2023/05/02 21:35:49: ScreenOverdrive = 0 : OK
2023/05/02 21:35:50: Screen = 60Hz : -2
2023/05/02 21:35:50: ScreenOverdrive = 0 : OK
2023/05/02 21:35:50: Screen = 60Hz : -2
2023/05/02 21:35:50: ScreenOverdrive = 0 : OK
2023/05/02 21:35:50: Screen = 60Hz : -2
2023/05/02 21:35:50: ScreenOverdrive = 0 : OK
2023/05/02 21:35:53: TUF RGB = B4-00-FF-FF-FF-EB-00-00-00-00-00-00 : OK
2023/05/02 21:36:15: GPUEco = 1 : 0
2023/05/02 21:36:16: Eco flag : -65536
2023/05/02 21:36:16: Mux flag : -65536
2023/05/02 21:36:17: GPUEco = 1 : 0
2023/05/02 21:36:17: Eco flag : -65536
2023/05/02 21:36:17: Mux flag : -65536
2023/05/02 21:36:17: GPUEco = 1 : 0
2023/05/02 21:36:18: Eco flag : -65536
2023/05/02 21:36:18: Mux flag : -65536
2023/05/02 21:36:18: GPUEco = 1 : 0
2023/05/02 21:36:19: Eco flag : -65536
2023/05/02 21:36:19: Mux flag : -65536
2023/05/02 21:36:56: WMI event 87
2023/05/02 21:36:56: Windows - Power Mode Changed
2023/05/02 21:36:56: AutoSetting for Offline
2023/05/02 21:36:56: BatteryLimit = 90 : OK
2023/05/02 21:36:56: PerformanceMode = 2 : OK
2023/05/02 21:36:57: Eco flag : -65536
2023/05/02 21:36:57: Mux flag : -65536
2023/05/02 21:37:11: WMI event 174
2023/05/02 21:37:11: PerformanceMode = 0 : OK
2023/05/02 21:37:11: WMI event 174
2023/05/02 21:37:11: PerformanceMode = 1 : OK
2023/05/02 21:37:11: Boost 2
2023/05/02 21:37:18: Screen = 60Hz : -2
2023/05/02 21:37:18: ScreenOverdrive = 0 : OK
2023/05/02 21:37:19: Screen = 60Hz : -2
2023/05/02 21:37:19: ScreenOverdrive = 0 : OK
2023/05/02 21:37:19: Screen = 60Hz : -2
2023/05/02 21:37:19: ScreenOverdrive = 0 : OK
2023/05/02 21:37:20: Screen = 60Hz : -2
2023/05/02 21:37:20: ScreenOverdrive = 0 : OK
2023/05/02 21:37:21: Screen = 60Hz : -2
2023/05/02 21:37:21: ScreenOverdrive = 0 : OK
2023/05/02 21:37:48: Screen = 60Hz : -2
2023/05/02 21:37:48: ScreenOverdrive = 0 : OK
2023/05/02 21:37:49: Screen = 60Hz : -2
2023/05/02 21:37:49: ScreenOverdrive = 0 : OK
2023/05/02 21:37:49: Screen = 60Hz : -2
2023/05/02 21:37:49: ScreenOverdrive = 0 : OK
2023/05/02 21:37:50: Screen = 60Hz : -2
2023/05/02 21:37:50: ScreenOverdrive = 0 : OK
2023/05/02 21:41:06: GPUEco = 1 : 0
2023/05/02 21:41:07: Eco flag : -65536
2023/05/02 21:41:07: Mux flag : -65536
2023/05/02 21:41:08: GPUEco = 1 : 0
2023/05/02 21:41:08: Eco flag : -65536
2023/05/02 21:41:08: Mux flag : -65536
2023/05/02 21:45:54: Screen = 60Hz : -2
2023/05/02 21:45:54: ScreenOverdrive = 0 : OK
2023/05/02 21:46:03: WMI event 207
2023/05/02 21:46:03: WMI event 88
2023/05/02 21:46:03: Windows - Power Mode Changed
2023/05/02 21:46:03: AutoSetting for Online
2023/05/02 21:46:03: BatteryLimit = 90 : OK
2023/05/02 21:46:03: PerformanceMode = 2 : OK
2023/05/02 21:46:03: Eco flag : -65536
2023/05/02 21:46:03: Mux flag : -65536
2023/05/02 21:46:12: WMI event 174
2023/05/02 21:46:12: PerformanceMode = 0 : OK
2023/05/02 21:46:12: WMI event 174
2023/05/02 21:46:12: PerformanceMode = 1 : OK
2023/05/02 21:46:13: Boost 2
2023/05/02 21:46:20: Screen = 120Hz : OK
2023/05/02 21:46:20: ScreenOverdrive = 1 : OK
2023/05/02 21:46:23: WMI event 87
2023/05/02 21:46:23: Windows - Power Mode Changed
2023/05/02 21:46:23: AutoSetting for Offline
2023/05/02 21:46:23: BatteryLimit = 90 : OK
2023/05/02 21:46:23: PerformanceMode = 1 : OK
2023/05/02 21:46:24: Boost 2
2023/05/02 21:46:24: Eco flag : -65536
2023/05/02 21:46:24: Mux flag : -65536
2023/05/02 21:46:24: Screen = 60Hz : -2
2023/05/02 21:46:24: ScreenOverdrive = 0 : OK
2023/05/02 21:46:25: Screen = 60Hz : -2
2023/05/02 21:46:25: ScreenOverdrive = 0 : OK
2023/05/02 21:46:27: Screen = 120Hz : OK
2023/05/02 21:46:27: ScreenOverdrive = 1 : OK
2023/05/02 21:46:28: WMI event 207
2023/05/02 21:46:28: WMI event 88
2023/05/02 21:46:28: Windows - Power Mode Changed
2023/05/02 21:46:28: AutoSetting for Online
2023/05/02 21:46:28: BatteryLimit = 90 : OK
2023/05/02 21:46:28: PerformanceMode = 1 : OK
2023/05/02 21:46:29: Boost 2
2023/05/02 21:46:29: Eco flag : -65536
2023/05/02 21:46:29: Mux flag : -65536
2023/05/02 21:46:29: Screen = 120Hz : OK
2023/05/02 21:46:29: ScreenOverdrive = 1 : OK

**Screenshots or screencasts**
None.

**Desktop (please complete the following information):**
 - OS: Windows 11, バージョン22H2, OSビルド 22621.1555
 - ASUS TUF FX505DY

**Asus software**
- Armoury crate deleted
- MyASUS installed
- 
**Additional context**
Also, I think that my 120Hz display is incapable of OD. I could be wrong.

**Comment by seerge** [comment]
@gantugsmk i see 

‘’ 2023/05/02 21:31:54: Screen = 60Hz : -2’’

in the log, windows returns error on attempt. Does your screen support 60hz? can you set it manually in display settings?

**Comment by gantugsmk** [comment]
![image](https://user-images.githubusercontent.com/105220271/235817040-26bc47bf-be61-49fb-a29e-9604be5451c0.png)

It supports only 48Hz.

**Comment by gantugsmk** [comment]
I think that it is an issue of my own display now I think about it.

**Comment by seerge** [comment]
@gantugsmk that's the reason :) 48 doesnt sound as regular refresh rate. Try to reinstall video drivers + mb find display drivers, then 60hz option will appear (as it should) :)
