### ISSUE TITLE
M3 hotkey re-assigning is bugged

### ISSUE THREAD

**Issue by SriHari-15** [seerge/g-helper#3080]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I have reassigned my M3 hotkey from Mute Mic to **Play/Pause**. When I press M3, it does both the functions, it mutes/unmutes my mic **as well as** play/pause.

I've personally reassigned only the M3 hotkey so I'm not sure if this is applicable to all M hotkeys.

### How to reproduce the bug?

- Change M3 hotkey from Mute Mic to Play/Pause
- Press the button
- The default Mute Mic function as well as the new reassigned Play/Pause both will be triggered

### Logs

[log.txt](https://github.com/user-attachments/files/16923240/log.txt)

### Device and Model

Asus ROG Strix G713RM (2022)

### Additional information.

Picture of my hotkey config:
![image_2024-09-08_235034886](https://github.com/user-attachments/assets/15a549e0-8241-403c-9c65-dc53923b9fa4)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.187.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@SriHari-15 hello, you have Asus Optimization service running that handles that hotkey. 

You need to stop it from `Extra` settings and then G-Helper's action will work.

Thanks.
