### ISSUE TITLE
Mode switching in G-helper resets custom Maximum processor frequency for "On battery"

### ISSUE THREAD

**Issue by hadoooooouken** [seerge/g-helper#3084]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

By default I couldn't specify a specific frequency for the processor in Windows power plan, but with some regedit tweaks it becomes possible and works fine without g-helper.

Regedit:
For show/edit Intel E-core Maximum processor frequency:
`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\75b0ae3f-bce0-45a7-8c89-c9611c25e100
`
P-core Maximum processor frequency:
`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\75b0ae3f-bce0-45a7-8c89-c9611c25e101`

For both keys just change "**Attributes**" value to "**2**".

I set my custom frequencies for E+P cores for both modes: "Plugged in" and "On battery". But after launching and changing mode in g-helper - "Maximum processor frequency" always resets "On battery" to "0 (no limit)".  But this problem is not present for "Plugged in" (custom frequency on the spot).

### How to reproduce the bug?

1. Set custom Maximum processor frequency / On battery.
2. Switch to any mode in G-helper
3. Check again Maximum processor frequency

### Logs

[log.txt](https://github.com/user-attachments/files/16937475/log.txt)

### Device and Model

ASUS VivoBook 16 X1605ZA-MB316 (90NB0ZA2-M00H60)

### Additional information.

https://www.youtube.com/watch?v=oVMK0c6ObfQ

### Armoury Crate

Uninstalled

### Version

0.187

### OS

Windows 11

**Comment by seerge** [comment]
@hadoooooouken hello, G-Heper doesn’t change those values directly (it can’t). 

The only thing it changes when you select `Eco` - is windows Power Mode to Best Battery Efficiency 

Can you check if changing Power Mode in Windows Settings directly results in same behaviour for your custom power plan settings?

**Comment by hadoooooouken** [comment]
> Can you check if changing Power Mode in Windows Settings directly results in same behaviour for your custom power plan settings?

![image_2024-09-10_12-45-50](https://github.com/user-attachments/assets/fd84ba5c-b053-46be-9f64-13080f4a8728)
Hi, just checked with closed G-helper - same behavior. It turns out that G-helper has nothing to do with it. Sorry to bother you.

**Comment by seerge** [comment]
@hadoooooouken great, if you don't want G-Helper to change **power modes**. Just set same power mode (under `Fans+Power` for all 3 modes)
