### ISSUE TITLE
Fan RPM Curve Not Taking Effect

### ISSUE THREAD

**Issue by CodingGenius0001** [seerge/g-helper#3087]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [x] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I set a custom fan curve, the laptop does not ramp up the fans to the set rpm when the temperature is reached. The laptop ends up overheating and shuts down due to insufficient cooling.

I have set it so that at 84 degrees Celsius, the fans should ramp up to 6000RPM, but GHelper limits the fan speed to only 3700RPM and the laptop touches 94 degrees Celsius without cooling down.

---
![image](https://github.com/user-attachments/assets/644ee6bc-8fbc-4565-8138-5492dc08cb93)

### How to reproduce the bug?

1. Go to GHelper
2. Open Fans + Power
3. Apply a custom fan curve
4. Laptop

### Logs

[log.txt](https://github.com/user-attachments/files/16939791/log.txt)

### Device and Model

Asus Zephyrus G14 2024 GA403UI

### Additional information.

I believe GHelper is unable to efficiently communicate with the PC or the PC is poorly interpreting the settings given by GHelper

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.187

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@CodingGenius0001 hello, please make yourself [familiar with FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)

> **How does G-helper control my fan speeds?**
> It doesn't and can't control your fans. Your firmware / BIOS controls them in real-time. Armoury also doesn't control fans in real time anyhow.

>What G-helper can do - is (optionally) set a custom fan profile to the current performance mode consisting of 8 pairs of temperature + fan speed % via the same endpoint Armoury uses when sets custom fan profile in it's Manual mode.

> How it will be interpreted - is still up to the firmware. If you don't like how firmware controls fans, you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)

**Comment by seerge** [comment]
P.S. On your screenshot you are not using custom fan curve at all, you use default BIOS mode
