### ISSUE TITLE
Gpu fan problem

### ISSUE THREAD

**Issue by forgethekidneys** [seerge/g-helper#309]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
 I just change the cpu lower limit to 45 degrees, not the gpu limit. The gpu temperature is 38 degrees, the lower limit is 60 degrees, but the gpu fan starts to running.
It's okay if you don't put it in manual mode. But when you put it in manual mode, the fan starts to run even though the gpu temperature is not at the limit.

**Clear scenario to Reproduce**
1. clıck g helper
2. click silent mode
3. click gpu mode ultimate
4. click fans+power
5. change cpu limit 45c 1800rpm
6. apply custom fan curve

**Expected behavior**
nothing change gpu limits. Gpu temperature 38 degrees, gpu fan limit 60 degrees but still the fans start running. Gpu fan shouldn't be running but it does

**App Logs**
2.05.2023 17:50:01: ------------
2.05.2023 17:50:01: App launched: ASUS TUF Gaming A15 FA507RM_FA507RM
2.05.2023 17:50:01: AutoSetting for Online
2.05.2023 17:50:01: PerformanceMode = 0 : OK
2.05.2023 17:50:01: Eco flag : 0
2.05.2023 17:50:01: Mux flag : 0
2.05.2023 17:50:01: Monitor Power On
2.05.2023 17:50:36: ------------
2.05.2023 17:50:36: App launched: ASUS TUF Gaming A15 FA507RM_FA507RM
2.05.2023 17:50:36: AutoSetting for Online
2.05.2023 17:50:36: PerformanceMode = 0 : OK
2.05.2023 17:50:36: Eco flag : 0
2.05.2023 17:50:36: Mux flag : 0
2.05.2023 17:50:36: Monitor Power On
2.05.2023 17:50:59: BatteryLimit = 75 : OK
2.05.2023 17:50:59: BatteryLimit = 70 : OK
2.05.2023 17:50:59: BatteryLimit = 65 : OK
2.05.2023 17:51:00: BatteryLimit = 60 : OK
2.05.2023 17:51:03: PerformanceMode = 2 : OK
2.05.2023 17:51:16: FanCPU = 2D-41-42-46-47-4B-4C-62-01-0C-0C-16-16-22-22-29 : OK
2.05.2023 17:51:16: FanGPU = 3C-41-42-46-47-4B-4C-62-08-11-11-1D-1D-26-26-2D : OK
2.05.2023 17:52:26: PerfMode = 2 : OK
2.05.2023 17:52:30: PerfMode = 2 : OK
2.05.2023 21:09:12: ------------
2.05.2023 21:09:12: App launched: ASUS TUF Gaming A15 FA507RM_FA507RM
2.05.2023 21:09:13: AutoSetting for Online
2.05.2023 21:09:13: BatteryLimit = 60 : OK
2.05.2023 21:09:13: BatteryLimit = 60 : OK
2.05.2023 21:09:13: PerformanceMode = 2 : OK
2.05.2023 21:09:13: Eco flag : 0
2.05.2023 21:09:13: Mux flag : 0
2.05.2023 21:09:13: Monitor Power On
2.05.2023 21:21:37: FanCPU = 2D-41-42-46-47-4B-4C-62-02-0C-0C-16-16-22-22-29 : OK
2.05.2023 21:21:37: FanGPU = 3C-41-42-46-47-4B-4C-62-08-11-11-1D-1D-26-26-2D : OK
2.05.2023 21:23:44: ------------
2.05.2023 21:23:44: App launched: ASUS TUF Gaming A15 FA507RM_FA507RM
2.05.2023 21:23:45: AutoSetting for Online
2.05.2023 21:23:45: BatteryLimit = 60 : OK
2.05.2023 21:23:45: BatteryLimit = 60 : OK
2.05.2023 21:23:45: PerformanceMode = 2 : OK
2.05.2023 21:23:45: FanCPU = 2D-41-42-46-47-4B-4C-62-02-0C-0C-16-16-22-22-29 : OK
2.05.2023 21:23:45: FanGPU = 3C-41-42-46-47-4B-4C-62-08-11-11-1D-1D-26-26-2D : OK
2.05.2023 21:23:45: Eco flag : 0
2.05.2023 21:23:45: Mux flag : 0
2.05.2023 21:23:45: Monitor Power On

**Screenshots or screencasts**
https://prnt.sc/ETfwWxBGFRvX

**Desktop (please complete the following information):**
 - OS: windows 10
 - ASUS TUF FA507Rm (6800h & RTX3060)

**Asus software**
- ARMORY Crate deleted
- MyASUS installed
- Other Asus services running in background

**Additional context**

**Comment by seerge** [comment]
@forgethekidneys hello, i see that app applies exactly fan curve from your screenshot, and it's accepted. How it's treated and how fans are controlled - is up to your bios, so it's not much i can do here.

Try to adjust fan curve so it's at least one dot at 30 or even 20C setting 0 RPM, may be then it will listen to you? 

![Screenshot 2023-04-14 111447](https://user-images.githubusercontent.com/5920850/235796134-7eee5587-75ef-4b1c-8e0a-5e8b86c49dd1.png)

**Comment by forgethekidneys** [comment]
My problem solved when i add 0 rpm dot thank you. Are the fan curves that g helper shows at the beginning original? I wonder can i find my laptop's orginal fan curves like silent, turbo.

**Comment by seerge** [comment]
@forgethekidneys initial fan curves are ones that your bios returns to app, but from experiense i can tell that they often don't represent what is being actually used by default... this is how asus have done it. So just use that curve as a template for your own edits.
