### ISSUE TITLE
Terrible on battery performance

### ISSUE THREAD

**Issue by Vishvesh1542** [seerge/g-helper#3091]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

It works fine no power, but as soon as you put it on battery, it just works terribly. Just starting up task manager takes 20 seconds. And when you check the processor speed in task manager, it never crosses 1 Ghz, regardless of what power mode you use on Ghelper. This bug didnt happen before when I used to use AC, and now also it randomly fixes itself and randomly breaks.  

### How to reproduce the bug?

Just unplug the computer

### Logs

[log.txt](https://github.com/user-attachments/files/16964610/log.txt)

### Device and Model

ASUS TUF Gaming F15 FX506HE

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.187

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Vishvesh1542 hello,

If your computer works much slower on battery, most likely your battery has some power-related issues (i.e. it doesn't provide enough power for the device). Especially considering that it happens in any modes.

It has nothing to do with G-Helper, cause it doesn't manager your power. You are free to quit G-Helper and verify - if behavior is same, then it's not G-Helper :)

Thanks.

**Comment by Vishvesh1542** [comment]
Actually the laptop is very new and I can say that its not a battery issue as it randomly starts working normally sometimes when I run the uninstall AC tool even tho it is already uninstalled. But now that also seems to not help. As it is seeming to work while uninstalling AC, I assumed it was related to Ghelper. Anyways thanks for a quick reply, Ill try going back to AC and see if that helps

**Comment by seerge** [comment]
@Vishvesh1542 well, your model is from 2021 from what i see. I can imagine you have bought laptop recently, but if it was manufactured few years ago - battery might age anyway :)

If it starts working randomly, so I would say it's something with firmware or hardware. Try hard reset as I mentioned above.
