### ISSUE TITLE
gu604vi keyboard shortcut (f9 monitor extension, f10trackpad) doesnt work when fn is locked.

### ISSUE THREAD

**Issue by SamnnyWong** [seerge/g-helper#3094]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

when fn is locked, press f9(monitor extension) will not work(nothing pop up) while press fn + f9 will worked(monitor extension window pop up).
when fn is locked, pressed f10(trackpad toggle) will always prompt trackpad: ON (it was always prompted trackpad: off but once I plug in a mouse and turn it on in windows settings app it is now always on, so I can not replicate "always off" in this case)

### How to reproduce the bug?

just press f9 and f10 with fn-lock enabled

### Logs

2024-09-12 23:07:32: F9 None
2024-09-12 23:07:34: F9 None
2024-09-12 23:07:34: F9 None
2024-09-12 23:07:35: F9 None
2024-09-12 23:07:35: F9 None
2024-09-12 23:07:35: F9 None
2024-09-12 23:07:35: F9 None
2024-09-12 23:07:35: F9 None
2024-09-12 23:07:36: F9 None
2024-09-12 23:07:36: F9 None
2024-09-12 23:07:51: F10 None
2024-09-12 23:07:51: Touchpad status:1
2024-09-12 23:07:52: F10 None
2024-09-12 23:07:52: Touchpad status:1
2024-09-12 23:07:52: F10 None
2024-09-12 23:07:52: Touchpad status:1
2024-09-12 23:07:52: F10 None
2024-09-12 23:07:53: Touchpad status:1
2024-09-12 23:07:53: F10 None
2024-09-12 23:07:53: Touchpad status:1

### Device and Model

Zephyrus GU604vi

### Additional information.

this is happening in both v0.187 and v0.189

### Armoury Crate

Uninstalled

### Asus Services

0

### OS

Windows 11 Enterprise 23H2 22635.4169

**Comment by seerge** [comment]
@SamnnyWong hello,

For both of this hotkeys G-Helper just emits a default windows key-combinations using windows API

`FN+F9` / `F9` -> emits `WIN + P` (to open default monitor options)
`FN+F10` / `F10` -> emits `WIN + CTRL + F24` (touchpad toggle)

If they don't work - it could be some hiccup in windows or some strange permissions that prevent that. Did you try restarting or running app as admin ? 

As besides that I can't do much :)

Thanks

**Comment by seerge** [comment]
@SamnnyWong any updates here ?

**Comment by SamnnyWong** [comment]
I tried rebooting but the issue remains. Aso my os just got reinstalled, so I think maybe maybe its a hardware issue.

**Comment by seerge** [comment]
@SamnnyWong ah, but does it work after reinstalling os or still same ? Did you try starting app as admin ?

**Comment by SamnnyWong** [comment]
For those who stumble upon this issue in the future, try the following(works for me):
1. Stopping Asus services in the g-helper menu may still cause conflict which causes some keys not to work. Make sure you use the uninstall Armory Crate tool from the Asus website to completely uninstall any Asus bloatware.
2. after step 1, go to the control panel->uninstall software, and check if "Asus smart display control" is uninstalled.
3. try disabling armory crate interface support in the bios setting.

after these, g-helper works like a charm :)

**Comment by SamnnyWong** [comment]
For those who stumble upon this issue in the future, try the following(works for me):

Stopping Asus services in the g-helper menu may still cause conflict which causes some keys not to work. Make sure you use the uninstall Armory Crate tool from the Asus website to completely uninstall any Asus bloatware.
after step 1, go to the control panel->uninstall software, and check if "Asus smart display control" is uninstalled.
try disabling armory crate interface support in the bios setting.
after these, g-helper works like a charm :)

**Comment by SamnnyWong** [comment]
For those who stumble upon this issue in the future, try the following(works for me):

Stopping Asus services in the g-helper menu may still cause conflict which causes some keys not to work. Make sure you use the uninstall Armory Crate tool from the Asus website to completely uninstall any Asus bloatware.
after step 1, go to the control panel->uninstall software, and check if "Asus smart display control" is uninstalled.
try disabling armory crate interface support in the bios setting.
after these, g-helper works like a charm :)

**Comment by SamnnyWong** [comment]
> @SamnnyWong ah, but does it work after reinstalling os or still same ? Did you try starting app as admin ?

Everything is working now, I have closed this issue with my solutions.
AC is like a ghost in all asus hardware, no matter how you try to disable it or uninstalling it, it never truly leave.

**Comment by SamnnyWong** [comment]
> @SamnnyWong ah, but does it work after reinstalling os or still same ? Did you try starting app as admin ?

i just find out my shortcut issue is gone with v0.189, but with 0.187 the issue persist, is there a difference between this two version in shortcuts?

**Comment by seerge** [comment]
@SamnnyWong hmm, there is literally nothing that can affect that https://github.com/seerge/g-helper/compare/v0.187...v0.189 

Any chance you have 2 exe files in different folders with different permissions ? So in first case windows allows keycombo to be emitted and pass through and in other - no ?
