### ISSUE TITLE
Asus UX3402VA - Can't update Dolby Atmos Driver 

### ISSUE THREAD

**Issue by Arthaei** [seerge/g-helper#3097]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi guys, loving G Helper, but I cannot ever seem to successfully update the Dolby Atmos driver. The current one is version 6.0.9590.1 and the one that always says is available is version 7.1130.1524.9. I have tried everything I can think of, normal install, install with run as administrator privileges selected, I've tried running the .bat file as administrator (this runs some cmd stuff, but seems to do absolutely nothing). I've tried uninstalling the Realtek audio device sound controller that corresponds to the 6.0.9590.1 version listed above and restarting the computer and just nothing works. Is there a way to update G-Helper with a way of updating this more forcefully? or is this a bug with G Helper of some kind such that it's not possible for some reason to update this driver? 

many thanks for any help in advance. I'm currently using G Helper version 0.187.0 on Windows 11 on my Asus UX3402VA laptop. 
![g helper error](https://github.com/user-attachments/assets/65f96b45-1dad-4561-9ffd-a32aea364e82)

### How to reproduce the bug?

Update available in driver update list but it refuses to actually update to the new version even after system restart or using admin privileges. 

### Logs

I can't find this file sorry.

### Device and Model

Asus Zenbook OLED UX3402VA

### Armoury Crate

Never installed

### Asus Services

None

### Version

0.187.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Arthaei hello, G-Helper shows you a mirror of [official asus website with drivers for your model](https://www.asus.com/laptops/for-home/zenbook/zenbook-14-oled-ux3402/helpdesk_download?model2Name=zenbook-14-oled-ux3402)

<img width="1282" alt="Screenshot 2024-09-13 at 17 11 24" src="https://github.com/user-attachments/assets/d3b353aa-2df5-49bd-84a6-6a2ffc9c47fe">

Sometimes asus just incorrectly marks driver versions on their website (vs what they really are). So if you have downloaded it and installed once - **it's already good** :) You may just ignore red label there.

Thanks

**Comment by Arthaei** [comment]
Ah ok is there a way to mark it as green in g helper? It's giving me anxiety!!
________________________________
