### ISSUE TITLE
[Experimental] Manual Fan Control

### ISSUE THREAD

**Issue by wdnmd462** [seerge/g-helper#3101]
my fan cant work normal 
<img width="830" alt="屏幕截图 2024-09-14 010222" src="https://github.com/user-attachments/assets/42a183ea-2946-46e5-b015-08a732b849b6">
I don't have any red numbers
The fan curve I worked out didn't work
i Uninstall ASUS System Control Interface v3 and DeviceAttempt to remove driver
but it dont work still
![Uploading 屏幕截图 2024-09-14 010222.png…]()

**Comment by seerge** [comment]
@wdnmd462 please [fill issue template properly](https://github.com/seerge/g-helper/issues/new/choose) and include all requested info, including logs. Thanks

**Comment by seerge** [comment]
@wdnmd462 and on a side note, there is a good chance you are simply missing Asus System Control interface required for manual fan control to work.

Make sure to [reinstall it as explained here](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-asus-system-control-interface)
