### ISSUE TITLE
my fan cant work

### ISSUE THREAD

**Issue by wdnmd462** [seerge/g-helper#3102]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

my fan cant work 
and my ui have no red word
<img width="408" alt="屏幕截图 2024-09-14 011216" src="https://github.com/user-attachments/assets/13dcc5cb-3122-4966-809c-29a8fbe8da03">
i used to installed Armoury Crate,but it still cant work well.

### How to reproduce the bug?

just Normal open software

### Logs

[log.txt](https://github.com/user-attachments/files/16997320/log.txt)

### Device and Model

ASUS ROG  G713PV

### Additional information.

i used to installed Armoury Crate,but it still cant work well.
i used to installed ASUS System Control Interface v3 and DeviceAttempt to remove driver.
but it dont work still.
my ASUS System Control Interface v3 is 3.1.34.0
<img width="524" alt="屏幕截图 2024-09-14 012243" src="https://github.com/user-attachments/assets/8528a2de-1054-4320-9a1f-2d7e6ce89168">

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.182and 0.187

### OS

win11--22H2

**Comment by seerge** [comment]
@wdnmd462 hello, what exactly is not working for you? 

You use a regular (not experimental) build. I see that you are setting a custom fan curve and BIOS accepts it just fine.
```
2024/9/14 0:30:50: FanCPU = 3B-46-50-53-55-58-5A-5E-05-0B-15-23-2C-38-4D-64 : OK
2024/9/14 0:30:50: FanGPU = 20-3C-45-4D-50-53-55-56-08-09-13-24-36-43-54-64 : OK
``

But since this **is not an experimental build** BIOS controls fans still (along custom fan curves) so it will be **no red labels** anywhere.

If you want to use experimental build - you need to [download it from this thread](https://github.com/seerge/g-helper/discussions/2272)

**Comment by wdnmd462** [comment]
Thank you very much
This question has puzzled me for a long time
