### ISSUE TITLE
Keyboard backlight doesn't work

### ISSUE THREAD

**Issue by EclipseMantis** [seerge/g-helper#3103]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

My keyboard backlight works when on the Windows sign-in screen once I start my laptop from power-off. The buttons and everything are fine. Once I log in and G-Helper starts, the backlight turns off, and I cannot turn it on with either the shortcuts or through the menu. I've attached a screenshot of what the menu looks like. The light bar also doesn't work.

![image](https://github.com/user-attachments/assets/608b27ca-a1e4-4105-b25b-f2ab3480696c)

I'm using an AMD Advantage Strix G15.

### How to reproduce the bug?

Restart the device, or power it on from power-off. The backlight works. Log into Windows. The backlight stops working. If G-Helper is removed from startup apps, the backlight continues working.

### Logs

[log.txt](https://github.com/user-attachments/files/16997833/log.txt)

### Device and Model

AE Strix G15

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.187.0

### OS

Windows 11; Up-to-date

**Comment by seerge** [comment]
@EclipseMantis hello,

I see that you have explicitly unchecked `Battery` checkbox under Extra and you are using laptop on battery. So it obviously turns your keyboard completely off then as it's supposed to.

Just check it back.

Thanks

**Comment by EclipseMantis** [comment]
Oh no! I'm sorry; I guess I missed that -- I thought it might've been user error, but I still  didn't see that somehow.

Thanks for your help!
