### ISSUE TITLE
BSOD when GPU Mode is set to optmised

### ISSUE THREAD

**Issue by SerendeepR** [seerge/g-helper#3104]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Windows throws a BSOD if the GPU mode is set as Optimised and you plug in when the charge is extremely low.

### How to reproduce the bug?

1. Set GPU Mode as Optimised
2. Drain your battery to close to 10%
3. Plug in your charger
4. BSOD and reboot

### Logs

Logs from Event Viewer:
`The computer has rebooted from a bugcheck.  The bugcheck was: 0x00000113 (0x0000000000000019, 0x0000000000000002, 0x00000000000010de, 0x00000000000025a2). A dump was saved in: C:\Windows\Minidump\091224-16015-01.dmp. Report Id: 02dd5f60-4f9e-4a65-ae42-ff510d16c117.
`

Logs from %APPDATA%\GHelper\log.txt :

```
9/12/2024 7:32:59 PM: TUF Brightness = 128 : OK
9/12/2024 7:32:59 PM: Monitor Power On
9/12/2024 7:32:59 PM: Monitor Power Off
9/12/2024 7:32:59 PM: TUF Brightness = 128 : OK
9/12/2024 7:32:59 PM: Monitor Power Off
9/12/2024 7:32:59 PM: Monitor Power On
9/12/2024 7:32:59 PM: TUF Brightness = 128 : OK
9/12/2024 7:32:59 PM: Monitor Power Off
9/12/2024 7:32:59 PM: TUF Brightness = 128 : OK
9/12/2024 7:32:59 PM: Screen = 60Hz : OK
9/12/2024 7:32:59 PM:  HDR: False 8 12 True
9/12/2024 7:32:59 PM: Mode = 2 : OK
9/12/2024 7:32:59 PM: Eco flag : 1
9/12/2024 7:32:59 PM: Mux flag : -65536
9/12/2024 7:32:59 PM: \\?\DISPLAY#BOE0A11#5&ed3003e&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
9/12/2024 7:32:59 PM: \\?\DISPLAY#BOE0A11#5&ed3003e&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
9/12/2024 7:32:59 PM:  HDR: False 8 12 True
9/12/2024 7:32:59 PM: TUF_KB = 16712125 : OK
9/12/2024 7:32:59 PM: AuraMode: HEATMAP
9/12/2024 7:32:59 PM: Display configuration changed.
9/12/2024 7:33:00 PM: TUF Brightness = 131 : OK
                                                                                                                                          9/12/2024 7:33:55 PM: ------------
9/12/2024 7:33:55 PM: App launched: ASUS TUF Gaming A17 FA706IC_FA706IC :0.187.0.0en-US.
9/12/2024 7:33:55 PM: Start Count: 10
9/12/2024 7:33:56 PM: Matrix control device was not found on your machine.
9/12/2024 7:33:57 PM:  HDR: False 8 4 True
9/12/2024 7:33:57 PM: \\?\DISPLAY#BOE0A11#5&ed3003e&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
9/12/2024 7:33:57 PM: \\?\DISPLAY#BOE0A11#5&ed3003e&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
9/12/2024 7:33:57 PM: C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_dce8906ce88264fa\ASUSOptimization\AsusSplendid.exe 25 0 50
9/12/2024 7:33:58 PM: !! ICM file not exist !!
9/12/2024 7:33:58 PM: C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_dce8906ce88264fa\ASUSOptimization\AsusSplendid.exe 10  
9/12/2024 7:33:59 PM: !! ICM file not exist !!
9/12/2024 7:33:59 PM: C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_dce8906ce88264fa\ASUSOptimization\AsusSplendid.exe 25 0 50
9/12/2024 7:34:00 PM: !! ICM file not exist !!
9/12/2024 7:34:00 PM: NVIDIA GeForce RTX 3050 Laptop GPU
9/12/2024 7:34:01 PM: CPU: 3 - AMD Ryzen 7 4800H with Radeon Graphics          - AMD64 Family 23 Model 96 Stepping 1
9/12/2024 7:34:01 PM: AutoSetting for Online
9/12/2024 7:34:01 PM: Optimization service is running
9/12/2024 7:34:01 PM: Eco flag : 0
9/12/2024 7:34:01 PM: Mux flag : -65536
9/12/2024 7:34:01 PM: \\?\DISPLAY#BOE0A11#5&ed3003e&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
9/12/2024 7:34:01 PM: \\?\DISPLAY#BOE0A11#5&ed3003e&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
9/12/2024 7:34:02 PM: WMI event 174
9/12/2024 7:34:03 PM: Screen = 144Hz : OK
9/12/2024 7:34:04 PM:  HDR: False 8 4 True
9/12/2024 7:34:04 PM: Mode = 1 : OK
9/12/2024 7:34:04 PM: Mode = 2 : OK
9/12/2024 7:34:04 PM: TUF_KB = 16712125 : OK
9/12/2024 7:34:04 PM: AuraMode: HEATMAP
9/12/2024 7:34:04 PM: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
9/12/2024 7:34:04 PM: WMI event 174
9/12/2024 7:34:05 PM: TUF Brightness = 131 : OK
9/12/2024 7:34:08 PM: Monitor Power On
9/12/2024 7:34:08 PM: AutoSetting for Online
9/12/2024 7:34:08 PM: Optimization service is running
9/12/2024 7:34:08 PM: Eco flag : 0
9/12/2024 7:34:08 PM: Mux flag : -65536
9/12/2024 7:34:08 PM: \\?\DISPLAY#BOE0A11#5&ed3003e&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
9/12/2024 7:34:08 PM: \\?\DISPLAY#BOE0A11#5&ed3003e&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
9/12/2024 7:34:08 PM:  HDR: False 8 4 True
9/12/2024 7:34:08 PM: Mode = 2 : OK
9/12/2024 7:34:08 PM: Mode = 0 : OK
9/12/2024 7:34:08 PM: TUF_KB = 16712125 : OK
9/12/2024 7:34:08 PM: AuraMode: HEATMAP
9/12/2024 7:34:08 PM: Lid Open
9/12/2024 7:34:08 PM: TUF Brightness = 131 : OK
9/12/2024 7:34:08 PM: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a -> 00000000-0000-0000-0000-000000000000:OK
9/12/2024 7:34:08 PM: WMI event 174
9/12/2024 7:34:08 PM: Mode = 1 : OK
9/12/2024 7:34:08 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> ded574b5-45a0-4f42-8737-46345c09c238:OK

```

### Device and Model

ASUS TUF Gaming A17

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

0.187.0

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@SerendeepR hello,

Does it happen only when you set `Optimized` ? Or in other situations ? Cause the only thing this mode does - is sets `Eco` (i.e. disables GPU) on battery and sets `Standard` when plugged in.

Can you just check if just enabling GPU when you plug in (i.e. switching to `Standard` from `Eco`) leads to same results ?

**Comment by SerendeepR** [comment]
> @SerendeepR hello,
> 
> Does it happen only when you set `Optimized` ? Or in other situations ?
> 
> Cause the one and only thing this mode does - is sets `Eco` (i.e. disables GPU) on battery and sets `Standard` when plugged in.
> 
> Can you just check if just enabling GPU when you plug in (i.e. switching to `Standard` from `Eco`) leads to same results ?

It only happens when it is set to optimized, also something to note is that there is a known issue in some driver versions of Nvidia, where switching from igpu to dgpu causes BSOD, which might also be a potential issue.

**Comment by seerge** [comment]
@SerendeepR there is technically no difference between manually setting `Standard` and using `Optimized` .

Can you try to set `Standard` immediately after plugging in ?

Did you try getting a fresh Nvidia driver install using [DDU as explained in Troubleshooting?](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers)

**Comment by seerge** [comment]
@SerendeepR also another trick for you to try. 

You can [delay all automation that happens when you plug in / unplug](https://github.com/seerge/g-helper/wiki/Power-user-settings#plugged-in--on-battery-actions-delay) by adding following line to the beginning of `%appdata%\GHelper\config.json` (quit app before editing)

```
"charger_delay" : 1000,
```

Check if it helps you :)

**Comment by seerge** [comment]
@SerendeepR any updates here ?

**Comment by EminGT** [comment]
I'm also having BSOD issues on Optimized. (Zephyrus G16 Intel Core Ultra 9)

But I had it on all battery levels, and I usually get this problem right when I unplug the charger. I can't easily reproduce it though. I also had the problem once right when I opened my laptop and entered my password. I don't know if any of this is useful or more confusing or related to this problem at all

**Comment by seerge** [comment]
@EminGT hello, I don't think your case is directly related to what OP @SerendeepR mentioned (as he has some reproduction scenario, and it's most likely some weird BIOS power management hiccup there).

- For you I can only advice to do a clean [Nvidia driver install ](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers). 
- Also you can check `Enable GPU on shutdown` under `Extra` - as it often helps to prevent some  Nvidia driver issues in windows afterwards.

**Comment by SerendeepR** [comment]
@seerge Changing it manually doesn't cause the issue, added the delay, will drain my battery today and try the fix with the config

> @SerendeepR also another trick for you to try.
> 
> You can [delay all automation that happens when you plug in / unplug](https://github.com/seerge/g-helper/wiki/Power-user-settings#plugged-in--on-battery-actions-delay) by adding following line to the beginning of `%appdata%\GHelper\config.json` (quit app before editing)
> 
> ```
> "charger_delay" : 1000,
> ```
> 
> Check if it helps you :)

**Comment by EminGT** [comment]
I actually got the bsod when I plugged in my charger today, just like SerendeepR. But I was at around 70% battery. I have "Enable GPU on shutdown" turned on, and I do have the latest version of Nvidia drivers. I'll try adding a 5 second delay and seeing if I get the issue again in the future

**Comment by EminGT** [comment]
I should also mention that this time (when it crashed when I plugged in the charger) the bsod error code was "VIDEO_DXGKRNL_FATAL_ERROR" instead of the "VIDEO_MEMORY_MANAGEMENT_INTERNAL" that I got when it crashed on logon

**Comment by seerge** [comment]
@EminGT "VIDEO_DXGKRNL_FATAL_ERROR" is something about directX :) (by googling that it seem to happen in lots of random cases).

**Comment by SerendeepR** [comment]
@seerge adding the delay helped, didn't BSOD till now. I'll let you know if it happens again.

**Comment by EminGT** [comment]
I think the delay fixed the problem for me as well

**Comment by seerge** [comment]
@SerendeepR @EminGT ok, glad to hear. What kind of delay did you set ? 1 second (1000) ?

**Comment by EminGT** [comment]
I'm using 5000 just to make sure. Might be unnecessarily high though

**Comment by seerge** [comment]
@EminGT try something smaller, like 500ms . Even tho your situation are quite exotic (or from 150 000 users it will be a lot of complains), but i still may think about a small artificial delay to run GPU enable / disable command on power change.

**Comment by SerendeepR** [comment]
1000 was too low, and it happened again, I'll try to increase it to 5000ms

**Comment by seerge** [comment]
@SerendeepR any updates ? Does big delay before GPU enable help ?

**Comment by SerendeepR** [comment]
1500ms is the sweet spot, on increments of 500. 1000 caused BSOD, 2000 didn't, 1500 doesn't.

**Comment by seerge** [comment]
@SerendeepR ok, great to hear. Then I assume it's resolved then.

Thanks
