### ISSUE TITLE
cant use nvidea control panel to switch display mode

### ISSUE THREAD

**Issue by Pg-sadface** [seerge/g-helper#3105]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

i downloaded g helper a few days ago and it has been a very good switch but the only problem is the nvidea control panel display settings such as automatic select doesn't work now. even tho i click on only optimus(igpu), the dgpu is still active and working. its only inactive when i have my laptop on eco mode. is there any way i can use the control panel to use my desired gpu mode and not always the igpu+dgpu(on standard mode because switching to ultimate and switching back to the rest takes a lot of time)because many games like minecraft loads itself on the igpu instead of the dgpu. 

### How to reproduce the bug?

on standard mode going to the nvidea control panel display settings and switching to optimus or automatic select shows that im using igpu only but my dgpu is still active and has programs running on it.

### Logs

[log.txt](https://github.com/user-attachments/files/17000854/log.txt)

### Device and Model

asus rog strix G614JV

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.187.0

### OS

windows 11

**Comment by seerge** [comment]
@Pg-sadface hello,

Neither G-Helper nor Armoury don't interact with Nvidia Advanced Optimus. It's handled by Nvidia drivers as far as dGPU is turned ON (i.e. you are in `Standard` mode or `Optimized` and plugged in)

- When you enable Optimus - your internal display is routed to iGPU. **It does not suppose to disable dGPU**, system or apps may still use it if they need to.
- When you select NVidia GPU Only - it routes internal display directly to dGPU, speeding things up a bit and boosting FPS in games. This is a software analog of `Ultimate` mode (proprietary hardware switch from Asus)

Thanks.
