### ISSUE TITLE
overdrive application binding

### ISSUE THREAD

**Issue by AayushV12** [seerge/g-helper#3106]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

can u create a menu for the screen overdrive option to be binded to application we want to use them in . it would help as i enable it and disable it on a daily basis whether i want to play competitive games.

### Describe alternatives you've considered

can u create a menu for the screen overdrive option to be binded to application we want to use them in . it would help as i enable it and disable it on a daily basis whether i want to play competitive games.

### Device and Model

asus rog strix g15 g513rc hn062w

### Additional information.

can u create a menu for the screen overdrive option to be binded to application we want to use them in . it would help as i enable it and disable it on a daily basis whether i want to play competitive games.

**Comment by seerge** [comment]
@AayushV12 hello, what is the practical purpose of disabling overdrive on the fly at all? 

When it disabled it only saves a tiny-bit of power, which is helpful on battery but not when you are plugged in and playing games :)

I don't see reasons to overcomplicate things with extra toggles here

Thanks.

**Comment by AayushV12** [comment]
okay can another feature be added for changing power plans available in the control panel to appear like a drop down menu in g helper. can u please add this one.

**Comment by seerge** [comment]
@AayushV12 power plans are de-facto obsolete in modern windows and are substituted with Power Modes that you can already easily select / change under `Fans + Power`. If you want to assign a legacy power plans as well, you can do that via config [as explained here](https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-windows-power-plans-with-each-mode)

**Comment by AayushV12** [comment]
can u make a video tutorial  for the power plan settings for high performance and ultimate performance as whenever i followed u accordingly its resetting itself

**Comment by seerge** [comment]
@AayushV12 it's already explained, just check [Power Users settings readme](https://github.com/seerge/g-helper/wiki/Power-user-settings#general-note)

**Comment by AayushV12** [comment]
I did and tried the same but after saving and starting g helper again the json file was reverted to original default state

**Comment by seerge** [comment]
@AayushV12 it means you don't follow guide in readme. You need to quit app before editing and also maintain JSON structure, i.e. not add extra commas or not skip them. Easiest way - is just to add a new line to the beginning of the file as mentioned there.
