### ISSUE TITLE
Fans not working in parallel

### ISSUE THREAD

**Issue by HamzaY2** [seerge/g-helper#3107]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The fans don't work in parallel, the cpu fan has to overwork because the gpu fan doesn't work enough. Heat cannot be properly removed from the device.

CPU 6000 gpu 2400 is spinning, it makes a lot of noise.
But with AC they both run 3500-4000. the noise is much less.

### How to reproduce the bug?

Delete AC with TOOL, restart pc
1. open G helper
2. select turbo mode
3. (fans calibrated)
4. open multicore stress test
5. cpu fan works 4800 gpu 2500
not parallel

1. if ı delete g helper and download AC
2. turbo mode
3. cpu fan 4800 gpu fan 4600-5000
parallel works

### Logs

[log.txt](https://github.com/user-attachments/files/17001792/log.txt)

### Device and Model

Asus Rog Strix G814JI

### Additional information.

![image](https://github.com/user-attachments/assets/70235a5b-fc2a-48e2-ab3a-2792b522f7f6)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.187

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@HamzaY2 hello, G-Helper does not control your fans directly, [please make yourself familiar with FAQ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)

If you don't like how firmware controls fans, you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)

> **How does G-helper control my fan speeds?**
> It doesn't and can't control your fans. Your firmware / BIOS controls them in real-time. Armoury also doesn't control fans in real time anyhow.

> What G-helper can do - is (optionally) set a custom fan profile to the current performance mode consisting of 8 pairs of temperature + fan speed % via the same endpoint Armoury uses when sets custom fan profile in it's Manual mode.

> How it will be interpreted - is still up to the firmware. If you don't like how firmware controls fans, you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)

**Comment by HamzaY2** [comment]
it didn't happen this way in older versions, so I was curious. 

The main reason I used Ghelper was to be able to use parallel fans with Custom Power setting. Now I have to go back to AC if that's the case. Thanks for your help.

**Comment by seerge** [comment]
@HamzaY2 as I have mentioned fan behavior is same if you use AC or G-Helper as they are controlled by BIOS.

- If you want to use all defaults as you had in AC - click Factory Defaults
- If you want to use some very custom fan behavior - you can use experimental build linked to you above

**Comment by HamzaY2** [comment]
Yes you can access the bios using Api, but in older versions, when I didn't click on the Custom fan tick, it automatically used the AC's main fan layout.
And I could adjust the power without losing that parallel operation feature, that's all I'm saying.

**Comment by seerge** [comment]
@HamzaY2 what specific version behaves like that ?

**Comment by HamzaY2** [comment]
![image](https://github.com/user-attachments/assets/2a8104b2-951b-4569-88f9-1b5d6612b378)
0.179

**Comment by seerge** [comment]
@HamzaY2 there is no difference in this regard between  - you can check source code changes [0.179 and 0.187](https://github.com/seerge/g-helper/compare/v0.179...v0.187)

In both cases you use a custom Turbo mode  and in both cases **BIOS runs fans as it wants**. You may try to adjust fan curves a bit to see if it makes a difference for you.

If you want to have more precise control over fan behavior you can use Experimental build with a manual fan control.

**Comment by HamzaY2** [comment]
Sorry, its not 0.179. İts 0.165

**Comment by seerge** [comment]
@HamzaY2 ok, thanks for clarification. 

In [0.165](https://github.com/seerge/g-helper/compare/v0.165...v0.187#diff-9ad2b24a8805f56d972e7612226ae30b36f2d99c21be03ca00546d42dec940e8L556) (or older) when applying custom power limits app didn't include custom fans setting. 

But that was changed as a result of other user's report. User has reported that power limits simply didn't work at all when they were applied w/o fan settings next to them. Many models behave like that as in Armoury you simply can't apply only power limits or only fan curves, you apply all together at the same time (in Manual mode). 

To doublecheck : can you download [0.165](https://github.com/seerge/g-helper/releases/download/v0.165/GHelper.zip) now apply custom power limits (like 65W) and then run Cinebench23 and monitor actual CPU power consumption ? Does it stay on 65W or go above ? Post a screenshot of that.

Thanks

**Comment by seerge** [comment]
@HamzaY2 this is the [report I was mentioning](https://forum.gamer.com.tw/Co.php?bsn=60030&sn=2464262&subbsn=7&bPage=0) (it's on Taiwanese forum, so you can just use google translate) . But idea is that power limits don't work if not coupled with fan curves

**Comment by seerge** [comment]
@HamzaY2 did you had a chance to test if power limits work in 0.165 ?
