### ISSUE TITLE
[Feature request] Possibilities of setting memory clock speed to improve battery life

### ISSUE THREAD

**Issue by Andy312432** [seerge/g-helper#311]
As we know, windows laptops all are battery-haungry, and Honor(a laptop manufacturor) introduced a technology called "OS turbo" . One of its achievements is to decrease the memory clock speed when using battery. Is it possible for asus bios to set it ?

**Comment by seerge** [comment]
@Andy312432 hello, i don't think that's possible to set from the app, you might look into your own bios (f2 on boot) to see if you can find anything there  :)
