### ISSUE TITLE
DC Dimming Battery and AC Settings Profiles

### ISSUE THREAD

**Issue by daveholland86** [seerge/g-helper#3112]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Could you please tie the DC Dimming setting to AC power like we currently have with power profiles, or even have the setting associated with power profiles.  This will automate DC dimming screen brightness when connecting or disconnecting AC power and reduce having to manually set it each time. 

### Describe the solution you'd like

DC Dimming power dependent settings.

### Device and Model

zephyrus G14

**Comment by seerge** [comment]
@daveholland86 hello, what exactly do you mean under “DC Dimming”? :)

**Comment by daveholland86** [comment]
It's listed in GHelper as flicker free dimming.

**Comment by seerge** [comment]
@daveholland86 hello. I'm not a big fan of making this a default behavior, cause I personally hate when brightness jumps when you plug / unplug :) (which was the case in armoury for example)

But I can add an optional config param that will enable that.

Try this build
[GHelper.zip](https://github.com/user-attachments/files/17015882/GHelper.zip)

You will have to add following line to the beginning of `%appdata%\GHelper\config.json` (quit app before editing)
```
"save_dimming": 1,
```

**Comment by daveholland86** [comment]
Yes, that works perfectly for power connect and removal and auto dimming settings.  Thank you.

**Comment by daveholland86** [comment]
I have everything automated for when I connect or disconnect power.  Have a .bat file that runs in task scheduler that configures me for gaming or battery use.  It will auto launch RTSS, HWiNFO, Afterburner, and then close them automatically when disconnected.  So having this brightness was the last step as I was modifying my power profile and running PWM flicker dimming before.

**Comment by seerge** [comment]
@daveholland86 great
