### ISSUE TITLE
Automated keyboard backlight won't react to mouse/touchpad events

### ISSUE THREAD

**Issue by legwinskij** [seerge/g-helper#3113]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Not sure if this is only present on my device (Asus ProArt PX13) or whether it is a design choice, but in case I have automated keyboard backlight control enabled in G-helper, my keyboard backlight goes on whenever I use mouse/touchpad.

### Describe the solution you'd like

Automated keyboard backlight won't react to mouse/touchpad events. It will only react to keyboard events.

This implementation of automated keyboard backlight is present on Microsoft Surface devices and I like it very much. It is very beneficial when reading longer articles or watching videos, where there is often no keyboard input and mouse/touchpad inputs are very sparse (e.g. once in minutes) in this cases the current implementation in G-helper on my device causes keyboard backlight to always go on and off.

### Device and Model

Asus ProArt PX13

**Comment by seerge** [comment]
@legwinskij hello, if you mean automatic backlight timeout (i.e when it goes off when device is inactive and back when you interact with windows) - then it's impossible to separate mouse / touchpad or keyboard actions.

App checks with windows `GetLastInputInfo` method, that reports for how long system is idle and didn't get any input. Windows doesn't split what exactly is idle here :)
 
https://github.com/seerge/g-helper/blob/ef769982e0a142afd80059dd3a55d75ec9976e9e/app/Input/InputDispatcher.cs#L50

https://github.com/seerge/g-helper/blob/ef769982e0a142afd80059dd3a55d75ec9976e9e/app/NativeMethods.cs#L16

So I can't change that. Sorry.

Thanks

**Comment by legwinskij** [comment]
Hi @seerge thanks for the quick feedback.

What about using low level Windows hooks such as `WH_KEYBOARD_LL` and `WH_MOUSE_LL` (ref: https://weblogs.asp.net/jdanforth/454219)?

I'm not a C#/.NET guy, but in case you are not against the functionality itself, I could come up with proposal implementation in PR.

Thanks!

**Comment by seerge** [comment]
@legwinskij i'm not really a .NET / C# guy by myself :) 

But as I understand with those hooks app will constantly listen to all keyboard an mouse events ? (that might be resource heavy)

And also I'm not 100% sure if this is better than general inactivity. In my scenarios, I actually prefer when mouse or touchpad interaction also wakes up laptop
