### ISSUE TITLE
Battery charge limits issue.

### ISSUE THREAD

**Issue by tirth1305** [seerge/g-helper#3114]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Battery charge limits  can't coordinating with systems battery  count. but still doing smart charging.
![image](https://github.com/user-attachments/assets/d24723ff-686a-4b42-bd74-01d46d00adf2)
![image](https://github.com/user-attachments/assets/fc7b706b-3ddb-4663-9de3-ff6877324e9b)

### How to reproduce the bug?

If you set limits in G-helper and it will generate.

### Logs

[log.txt](https://github.com/user-attachments/files/17006157/log.txt)

### Device and Model

ASUS F15 

### Armoury Crate

Uninstalled

### Asus Services

8

### Version

0.187.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@tirth1305 hello, battery limit is applied as soon as app starts

```
15-09-2024 18:15:23: AutoSetting for Online
15-09-2024 18:15:23: BatteryLimit = 80 : OK
15-09-2024 18:15:23: Optimization service is running
```

Please keep in mind that if battery is already charged to 100% **it will not discharge magically** back to 80% unless you unplug. This is how any device works. Windows shows that smart charging is on - meaning that limit is set.

Also I see that you have Asus services running that may override charge limit. You need to either stop them completely from `Extra` settings or set same (80%) charge limited under MyASUS apps [as explained in FAQ](https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working).

Thanks.
