### ISSUE TITLE
Automatic stop asus services

### ISSUE THREAD

**Issue by vichugol** [seerge/g-helper#3116]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

![Captura de pantalla 2024-09-15 201335](https://github.com/user-attachments/assets/2848ed49-b927-410e-8dc7-39c42a29dc07)
This button is great, but would be awesome if this were automatic at startup.

### Describe the solution you'd like

Add a checkmark option above this button,, to "◻ Automatic stop Asus apps at startup"

### Describe alternatives you've considered

Probably would be necessery to have a "startup with administrative privileges" option to make this work.

### Device and Model

Asus Zephyrus G16 GU605

### Additional information.

My suggetion (is in spanish):
![Sin título-1](https://github.com/user-attachments/assets/c82dcdf6-f6fd-482c-87b4-e399c08fa25f)

**Comment by seerge** [comment]
@vichugol hello,

There is no need for that as button doesn't only stops **it also disables** all listed services. So they will not start again on reboot unless you start / enable them in app again :)

Thanks

**Comment by chorong761** [comment]
I noticed that after updating the Asus System Control Interface, those services would set themselves back to automatic.

Would it be possible for Ghelper to automatically disable services after the driver has been updated?

**Comment by seerge** [comment]
@chorong761 hello, i'm not a big fan of that to be honest. I don't like the idea of G-Helper messing up with services in windows by itself without explicit user action (and therefore consent) on doing so.

**Comment by chorong761** [comment]
> @chorong761 hello, i'm not a big fan of that to be honest. I don't like the idea of G-Helper messing up with services in windows by itself without explicit user action (and therefore consent) on doing so.

I see, would it be better if it could be made as an optional feature?

Thanks
