### ISSUE TITLE
ROG Strx G15 2022 RGB Starry Night Request

### ISSUE THREAD

**Issue by Jeb166** [seerge/g-helper#3120]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

In Armoury Crate, in RGB options there was an option called "Starry Night" for G15 2022 laptop. I can't see that option in the G-Helper. 

### Describe the solution you'd like

If it is possible it would be great to have Starry Night option, i was using that a lot.

### Device and Model

Asus Strix G15 G513RM

**Comment by seerge** [comment]
@Jeb166 hello, your device (G513RM) exists in 2 editions. One with per-key RGB that supports lots of RGB modes and one with more basic 4-zone RGB that doesn't support them.

Open `Extra` settings, you should see `Per Key RGB` checkbox there. Toggle it and restart app after.

**Comment by Jeb166** [comment]
> @Jeb166 hello, your device (G513RM) exists in 2 editions. One with per-key RGB that supports lots of RGB modes and one with more basic 4-zone RGB that doesn't support them.
> 
> Open `Extra` settings, you should see `Per Key RGB` checkbox there. Toggle it and restart app after.

I've just tried the Per Key RGB checkbox and half of the RGB modes that appears after enabling that doesn't work, including Starry Night option. It just stucks with a single color and doesn't do any animation at all.

**Comment by seerge** [comment]
@Jeb166 then most likely it's not supported on firmware level by your keyboard. 

Do you have per-key RGB ? Could you set individual colors for each key in AC?
How did that Starry Night look when you set it in AC and did you have to toggle Aura Sync for it to work ?

**Comment by seerge** [comment]
@Jeb166 well, then it's strange, cause all possible hardware modes are already listed (they are literally numbered by IDs, so I doubt it's more). So if "new" modes after checking option under `Extra` do nothing i don't know how that starry night worked in AC

https://github.com/seerge/g-helper/blob/5e51511df01dcb1845847356eb6b68b9d1f7eabd/app/USB/Aura.cs#L38

Can you set this mode using https://openrgb.org/ ?

**Comment by Jeb166** [comment]
>Can you set this mode using https://openrgb.org/ ?

I tried OpenRGB just now but the layout of the zones in that app is completely wrong, right side of the device is considered as keyboard and the left side is the lightbar. Also i didn't understand, what is "public enum AuraMode : int "? Do i need to set it in the OpenRGB? How can i do it? I can't find a console or terminal for that.

**Comment by seerge** [comment]
@Jeb166 ok. Most likely AC just imitates this "mode" on software level (i.e. it manually adjusts colors few times a second for each zone)

We can check how exactly it happens by capturing actual payload AC sends to the device

Posting a guide on how to capture (from other thread)

----


Install https://www.hhdsoftware.com/device-monitoring-studio (will require reboot)

0. Start AC and disable Aura Sync there

1. Launch Monitoring Studio, pick **Asus** device with Product ID `0x19B6` from the list and double click on it
![Screenshot 2024-01-20 163125](https://github.com/seerge/g-helper/assets/5920850/e9a28802-08cb-423c-812b-7b526b051a5f)

2. Add ``Packet View`` to Procesing and click ``Start``
![Screenshot 2024-01-20 163136](https://github.com/seerge/g-helper/assets/5920850/354340f0-2fcb-473b-a49f-2e01b25d00a9)

3. Open AC and turn ON `Starry Night` mode there

4. Check if Monitoring Studio catching data. If NOT - you probably have selected wrong Asus device on step 2 (so need to re-do it)

5. In Monitoring Studio select ``Tools`` -> ``Save to Log``, and save data
![Screenshot 2024-01-20 163247](https://github.com/seerge/g-helper/assets/5920850/ad480dcf-05bc-43a7-9a80-2984fb68e8a8)

Upload this data here. 

Thanks

**Comment by Constrat** [comment]
> I tried OpenRGB just now but the layout of the zones in that app is completely wrong, right side of the device is considered as keyboard and the left side is the lightbar. Also i didn't understand, what is "public enum AuraMode : int "? Do i need to set it in the OpenRGB? How can i do it? I can't find a console or terminal for that.

Regarding this I've been working with the ORGB team and with the 1.0 update, a fix for the G15 and G17 devices should come. If you want to try (experimental) this is a build with the latest changes regarding the implementation of the Asus KLM etc etc
https://gitlab.com/CalcProgrammer1/OpenRGB/-/jobs/7828735112/artifacts/download?file_type=archive (Windows x64 build)

**Comment by Jeb166** [comment]
@seerge I apologize for keeping you waiting, thank you for your support. I will install AC again and send you the log data.
@Constrat Thank you. I am going try it and return feedback.

**Comment by Jeb166** [comment]
I installed Armoury Crate again, i disabled G-Helper and restarted my computer but for some reason Aura doesn't change my RGB. It stucked on Rainbow and justs turns off and on again when i change it.

**Comment by Jeb166** [comment]
Okay i realized i actually need to turn on Aura Sync to see Starry Night option, sorry for being dumb. Should i still need to send you to the data?

**Comment by Jeb166** [comment]
I saved the data o a log file, but can't find the location of it. Where is it?

**Comment by Jeb166** [comment]
Saved the data to a log file but can't locate it, where is it exactly?

**Comment by seerge** [comment]
@Jeb166 ok, great. Thanks.

But as I expected there is no such thing as hardware / firmware "Starry Night" in a keyboard. That's why I was asking if you had to enable Aura Sync in order to make it work in a first place 

What AC does in this case - is just manually sets colors for each zone few times a second, imitating this animation.

On this stage G-Helper doesn't do this things (with the only exception of Ambient mode, and even there it's quit simplified). Main reason is cause it's quite resource heavy. And next to that I simply don't have a single RGB-device where I can experiment with this :))

**Comment by Jeb166** [comment]
> @Jeb166 ok, great. Thanks.
> 
> But as I expected there is no such thing as hardware / firmware "Starry Night" in a keyboard. That's why I was asking if you had to enable Aura Sync in order to make it work in a first place
> 
> What AC does in this case - is just manually sets colors for each zone few times a second, imitating this animation.

Oh i just understood how it works, thank you.

> On this stage G-Helper doesn't do this things (with the only exception of Ambient mode, and even there it's quit simplified). Main reason is cause it's quite resource heavy. And next to that I simply don't have a single RGB-device where I can experiment with this :))

If it’s going to make it more resource-heavy, it’s better this way. The reason I chose G-Helper over Armoury Crate is because of how lightweight it is. I want to thank you for this amazing software and your support. Have a nice day!

**Comment by seerge** [comment]
@Jeb166 ok, great.

Then I'm afraid (on this stage) i'm simply not able to recreate any "dynamic" modes in G-Helper. May be somewhere in the future, if i will find a way to do it lightly and get my hands on a device with RGB as well.

Therefore closing this as not planned for now.

Thanks and sorry.
