### ISSUE TITLE
Add an option to set separate  CPU and iGPU  power limits

### ISSUE THREAD

**Issue by Keiszer** [seerge/g-helper#3121]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

When on battery, I sometimes like to play lighter 3D games on my iGPU without switching my power profile specifically for that purpose. In this case, since I set a low CPU power limit to preserve battery, when a game is opened that power limit often isn't enough (say, 10W) because the CPU and iGPU power limits are linked in some way.

### Describe the solution you'd like

If a feature were to be added where separate CPU and iGPU power limits were exposed, it would be possible to have a CPU power limit to save battery _and_ be able to open a game at the drop of a hat and have the power limit configured to have the iGPU pull the necessary amount of power. 

### Describe alternatives you've considered

I also explored UXTU as a possibility but was not able to find any relevant power-tuning options (nothing more akin to what I mentioned than what is allowed in G-Helper, at least). If there _is_ a separate software that allows for iGPU specific power-tuning that can be used in conjunction with G-Helper, I would love to know! I wasn't able to find any...

### Device and Model

Asus Zephyrus G14 GA402RJ (6900HS/6700s)

**Comment by seerge** [comment]
@Keiszer hello, that's simply not possible

G-Helper can give you access to the settings that already exist on your system on firmware level. That's why you see pretty much same options as you had in AC.

CPU power limit affects whole APU (CPU + iGPU). Rest is up to actual hardware on how to distribute available power :)

Thanks
