### ISSUE TITLE
Eco mode not working

### ISSUE THREAD

**Issue by CodingGenius0001** [seerge/g-helper#3125]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The dGPU does not switch off when Eco mode is enabled

![image](https://github.com/user-attachments/assets/bc6f0ffc-4d02-4cde-acb4-521ad1693d72)

### How to reproduce the bug?

Switch on Eco mode in GHelper

### Logs

[log.txt](https://github.com/user-attachments/files/17031902/log.txt)

### Device and Model

Asus Zephyrus G14 2024 GA403UI

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.187.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@CodingGenius0001 hello,

I see that Eco command is accepted, and furthermore after that BIOS reports that Eco is ON (i.e. GPU is disabled)

```
17-09-2024 6:50:07 AM: Running eco command 1
17-09-2024 6:50:07 AM: GPUEco = 1 : OK <----- ECO COMMAND
...
17-09-2024 6:50:08 AM: Eco flag : 1 <---- BIOS REPORTS THAT ECO IS ON
17-09-2024 6:50:08 AM: Mux flag : 1
```

It looks like some BIOS hiccup. Do you see Nvidia GPU in windows Device Manager?

You can try to do couple of things

1. Check `Enabled GPU on shutdown` under `Extra` and then reboot device. And then try to set `Eco` again 
2. Do hard-reset [as explained in troubleshooting](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset)

**Comment by CodingGenius0001** [comment]
Option 1 worked for me. Thanks

**Comment by seerge** [comment]
@CodingGenius0001 amazing
