### ISSUE TITLE
Replaced White Backlight Keyboard with RGB on ASUS Zephyrus G15 GA503RM – Red Color Stuck, Can't Change Individual Colors with OpenRGB/Ghelper

### ISSUE THREAD

**Issue by mds2002-lk** [seerge/g-helper#3126]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I recently replaced the single-color (white) backlit keyboard on my ASUS Zephyrus G15 GA503RM with an RGB backlit keyboard, hoping to get full RGB control. While I’ve had some success, I’m running into a problem with individual color control.

I’m using OpenRGB/Ghelper, and although the RGB lighting works in color cycle and rainbow modes, I can’t change individual colors directly. The red color stays lit regardless of what I try to set. So, if I attempt to select a solid color (like blue, green, etc.), red still remains active. It seems like individual RGB control isn't functioning correctly, which is limiting my ability to fully customize the lighting.

Here are a few more details:

Laptop model: ASUS Zephyrus G15 GA503RM (originally came with a white backlit keyboard).
Replacement keyboard: Full RGB backlit keyboard.
Software used: OpenRGB/Ghelper (detected and partially working – only color cycle and rainbow modes work, but no individual color customization).
Issue: The red backlight stays on, and I can’t directly control or set individual static colors.
I’ve already tried updating OpenRGB/Ghelper and resetting the lighting, but the issue persists. I’m wondering if this might be a compatibility issue with the replacement keyboard or a limitation with OpenRGB/Ghelper's support for this specific model.

Has anyone else experienced similar problems after replacing their keyboard with an RGB one? Any advice on fixing this would be much appreciated, or recommendations for alternative software that might offer better RGB control for this laptop.

Thanks in advance!

Original Keyboard = WHITE BACKLIGHT, 1-ZONE keyboard Part Number = 90NR0802-R31UK0
Replace Keyboard = RGB, 1-ZONE Keyboard  G16 2023 Model

### How to reproduce the bug?

s

### Logs

[log.txt](https://github.com/user-attachments/files/17032150/log.txt)

### Device and Model

ASUS ZEPHYRUS G15 GA503RM RYZEN 7 6800HS RTX 3060 

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.187

### OS

Edition	Windows 11 Home Single Language Version	23H2 Installed on	‎9/‎5/‎2024 OS build	22631.4169 Experience	Windows Feature Experience Pack 1000.22700.1034.0

**Comment by seerge** [comment]
@mds2002-lk hello,

I'm afraid it depends on keyboard firmware :) You have replaced a keyboard but you still use old firmware, that is able to set only one color.

G-Helper itself tries to set colors correctly

```
9/17/2024 10:01:11 PM: AuraMode: AuraStatic
9/17/2024 10:01:11 PM: USB 19B6: 5D-B3-00-00-[FF-00-00]-EB-00-00-FF-80-C0-00-00-00-00 <--- RED
9/17/2024 10:01:11 PM: USB 19B6: 5D-B5-00-00-00
9/17/2024 10:01:11 PM: USB 19B6: 5D-B4
9/17/2024 10:01:19 PM: AuraMode: AuraStatic
9/17/2024 10:01:19 PM: USB 19B6: 5D-B3-00-00-[00-FF-00] -EB-00-00-FF-80-C0-00-00-00-00 <--- GREEN
9/17/2024 10:01:19 PM: USB 19B6: 5D-B5-00-00-00
9/17/2024 10:01:19 PM: USB 19B6: 5D-B4
```

I'm sorry, but I can't help here :) you need also to update firmware of the keyboard ... if that is even possible.
