### ISSUE TITLE
Mute Microphone shortcut does not work Zephyrus G14 2021

### ISSUE THREAD

**Issue by DanielVladu** [seerge/g-helper#3127]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The documented shortcut for mute mic:
Ctrl + Shift + F20 - Mute Microphone
does not seem to work.

### How to reproduce the bug?

Tested with:
VIA software with Nuphy keyboard

- create macro for CTRL + SHIFT + F20

PowerToys Key remapper

- remap (for example) WIN+ALT+CTRL+SHIFT+X to CTRL+SHIFT+F20

Press the macro/remapped shortcut - nothing happens.
The dedicated mute button works as intended.

### Logs

[log.txt](https://github.com/user-attachments/files/17032962/log.txt)

### Device and Model

Asus Zephyrus G14 G401QM

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.187.0

### OS

Windows 11

**Comment by seerge** [comment]
@DanielVladu hello,

I see that you have Asus Optimizatin service running and it handles all main hotkeys by itself. When G-Helper sees that it intentionally skips hotkeys, including mic-mute.

```
17.09.2024 20:36:19: Optimization service is running
```

Just stop asus services via `Extra` settings, and then this binding will work. Does it help ?

**Comment by seerge** [comment]
@DanielVladu or actually, try this build.

It should run MicMute even when OptimizationService is running for CTRL + SHIFT + F20

[GHelper.zip](https://github.com/user-attachments/files/17040619/GHelper.zip)

**Comment by DanielVladu** [comment]
Hi @seerge,

The build works fine. Amazing work and quick too. I see now that the M3 button is handled by the Asus service and the new shortcut by GHelper due to different toast notification.

Regarding the Asus services, when I first installed GHelper, some time ago, I used the "Stop" button quite a few times to stop them but some kept running again - although most of them stayed shut.
I do have Armoury Crate completely uninstalled, but I do keep MyAsus as there are some features I need. I suppose this is the cause.

If you got the time, can you please tell me what OptimizationService handles ? (besides some hotkeys)

**Comment by seerge** [comment]
@DanielVladu great. OptimizationService handles hotkeys and also sets charge limit on start.

So you need to set same limit in MyASUS and in G-Helper (i.e. 80%)
