### ISSUE TITLE
USBC power CPU power limits not set

### ISSUE THREAD

**Issue by daveholland86** [seerge/g-helper#3130]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When USBC power delivery is used, CPU power limits are not set and standard power limits from Asus are used. 

### How to reproduce the bug?

Attach USBC power and stress test the CPU changing power limits.

### Logs

[log.txt](https://github.com/user-attachments/files/17043517/log.txt)

### Device and Model

zephyrus G14 GA403UI

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.190.0

### OS

Windows 11 24H2

**Comment by daveholland86** [comment]
Power limits work both on battery and with the Asus adapter.  USBC PD seems to not set power limits but appears everything else is working.

**Comment by seerge** [comment]
@daveholland86 hello, from the log i see that app sets everything as it’s supposed to :)

Most likely firmware is intervening.

How does same settings work on USB-C if you set them using Armoury?

**Comment by daveholland86** [comment]
I don't know, I have it completely removed.  I rarely use USBC but I was today and noticed the CPU not running my lower power limits.  It does seem like something is overriding it, I will stick to the official power adapter as everything does run better with it.  Seems like USBC PD on the G14 is a makeshift solution that they don't expect people to really use. 

When launching a game, set to run on the 780m I was getting 48w power draw observed through HWiNFO.  When unplugged power dropped to 15-12w as I have set in silent.  I then ran CPUZ on USBC power and manually set 20w CPU limit and it boosted to 28w verifying that USBC power limits settings are being overridden.

**Comment by seerge** [comment]
@daveholland86 what kind of power draw metric are you looking at ? Is it CPU / APU only or something else ?

As for how power limits work : for each mode and for each plugged to barrel charge / usb-c / on battery power state there are some hard limits set in BIOS that you can't overcome moving upwards. So for example you most likely can't set CPU limit to 80W on battery.

**Comment by daveholland86** [comment]
I am looking at CPU package draw.  I have 12w set on Silent and 35w set on custom.  I am seeing 50w draw when running on USBC meaning it's bypassing my 35w limit set.

**Comment by seerge** [comment]
@daveholland86 i see. Then it's extremely likely firmware issue. Can you try to set custom power limits using `Turbo` as base ? (as in Armoury Crate it's Manual mode is actually Turbo under the good + fan curves + limits on top)

**Comment by seerge** [comment]
@daveholland86 any updates here ? did you had a chance to try custom limits using Turbo as a base mode and did you had a chance to check if AC behaves same?

**Comment by seerge** [comment]
I assume this is abandoned now + in any case it's some firmware limitation that app won't overcome. If you will have new updates feel free to reopen

**Comment by daveholland86** [comment]
Not sure what changed but running 191 USBC power limits all work to whatever is set on Standard and Custom profiles.

**Comment by seerge** [comment]
@daveholland86 what is "191 USBC" ?

**Comment by daveholland86** [comment]
Phone keyboard, it's just USBC power.
