### ISSUE TITLE
GPU working on Eco Mode

### ISSUE THREAD

**Issue by elfi-ox** [seerge/g-helper#3132]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

After sleep, GPU kick-in even if i'm on Eco Mode. I've read here that a potential solution would be to activate some GPU option under Extra in the app, or add  "gpu_mode_force_set": 1 to config.json but I didn't see much difference. Originally it switched to Performance after sleep, now it dosen't but either way it show on task manager and I can deffinitely tell by my fans and my temps that it's indeed, running.

I've tried reseting Embedded Controller, I may have done something wrong but it just booted normally. I've also read that G15 2022 gave have a bad bios and that It would work better to install the previous version and I would like to know if it's safe to do ? does this method have downsides/downgrades ?

Also, everytime I switch to Performance and switch back to Eco, G-Helper do thing in the background and it correctly disable the GPU. Would it be a potential fix to make G-Helper does theses "things" in the background every time the GPU is detected while Eco is enabled ? (well, not every, just once to avoid any mess that would be caused by a chain reaction)

### How to reproduce the bug?

enable Eco Mode
click the power button
wake it from sleep mode
check task manager to see if dGPU is running

### Logs

[log.txt](https://github.com/user-attachments/files/17047128/log.txt)

### Device and Model

Asus Rog Strix G15 2022 G513RW

### Armoury Crate

Installed

### Asus Services

None

### Version

0.187.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@elfi-ox hello, G-Helper is not enabling GPU and furthermore BIOS reports that it still stays off (i.e. it's `Eco` mode)

```
18/09/2024 12:06:57: Monitor Power Off <---- you turn display off with power button
18/09/2024 12:06:57: Backlight 19B6: 5D-BA-C5-C4-00
18/09/2024 12:07:15: Monitor Power On

....
18/09/2024 12:07:15: Eco flag : 1 <--- ECO IS STILL ON
18/09/2024 12:07:15: Mux flag : 1
```

I see that you have Armoury Crate installed, are you sure that it's not interfering ? I would try to uninstall it using official [uninstaller](https://github.com/seerge/g-helper/wiki/Requirements#recommendations-optional).

Also you can check `Enable GPU on shutdown` under `Extra` and reboot after, it can help prevent different Nvidia driver hiccups.

**Comment by elfi-ox** [comment]
I already tried "Enable GPU on shutdown" but it didn't change anything

The way I know that the GPU is still on is because of my temp (CPU is generally around 15C hotter when GPU is running) and because it's displayed in the performance section of Task Manager.
I know it's not the fault of G-Helper but because of the crappy bios of asus, it's also why I asked if there is any downside or things to know about using the older version of the Bios.

Also I can't really get rid of it because I need it to run Aura Creator (which doesn't hace any alternative unfortunately 🙁) 

But since you mentioned Armoury Crate I tried changing the GPU mode in Armoury Crate from performance to Eco, same problem except that it always wake on Eco. Choosing Optimized in Armoury Crate fixed the issue thanks.

**Comment by seerge** [comment]
@elfi-ox `Optimized` mode just automatically turns `Eco` on battery and `Standard` when plugged in.

When G-Helper sees that device wakes up from sleep or restarts  - it checks for current GPU mode, and if doesn't match with what it should be it also changes it. 

But in your case BIOS reports that it's already in `Eco` as it was before spleep : `18/09/2024 12:07:15: Eco flag : 1`, so obviously app doesn't force anything else. If I will change this logic - it will misbehave on all other devices :)

Did you try [reinstalling Nvidia drivers using DDU ? ](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers) may be that will help somehow ?

**Comment by elfi-ox** [comment]
I didn't tried reinstalling my Nvidia driver, but as I said, the problem kinda solve itself by letting the GPU on optimized in Armoury Crate. I think the problem is that putting Eco or Performance within armoury crate mess with the BIOS in a bad way. I just did some testing and now it Behave like it should.

So the thing to note here from what I understand is to let GPU settings to optimized in Armoury Crate or else it will not work well in G-Helper. (Or just uninstall it like you suggested)

**Comment by seerge** [comment]
@elfi-ox can you try to run following in powershell as admin after your laptop wakes up in Eco mode, but you suspect it's not Eco anymore ?

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00090020; Control_status=1}
```

(this is just an Eco command itself just in case)

**Comment by elfi-ox** [comment]
Interesting, I'll try this but what exactly do you mean by "turn off optimized in AC" because I don't think I can disable AC GPU management. It's why I thought it would be a solution for keeping AC. Because it's like GHelper, I can choose between Ultra, Performance, Eco or optimized, and selecting Optimized is the only one who doesn't cause any problem. So what do you mean ?

**Comment by seerge** [comment]
@elfi-ox the only mode that is "actively" changes GPU state (w/o you clicking a button) is Optimized (in both G-Helper and AC). If you just set Eco mode in AC - it won't interfere.

**Comment by elfi-ox** [comment]
Well that the thing I don't understand, it actually does interfer. 

After some testing I observed that choosing Eco in AC automatically change my GPU to Eco after sleep, regardless of which mode it was in with G-Helper. And using Performance(or standard, I don't remember what it's called) in AC, automatically change it to that when I wake up my PC (which caused my original issue)

While Optimized doesn't change anything, witch is weird but yeah, as long as I put the correct mode in GHelper it stay in that

**Comment by seerge** [comment]
@elfi-ox your comments are confusing :) First you say that it’s only Optimized mode in AC that works properly, now you say it’s Eco and Standard but not Optimized?

**Comment by elfi-ox** [comment]
That's not what I meant, I'll try to be more precise.

Eco in AC + Anything in G-Helper = When I wake up, it's set back to Eco if it wasn't already set to that : it's a problem

Standard in AC + Anything in G-Helper = When I wake up, it's set back to Standard if it wasn't already set to that : it's a problem 

Optimized in AC + Anything in G-Helper =  When I wake up, it doesn't change anything from what I selected : It's the expected Behavior

**Comment by seerge** [comment]
Ok, so AC just overrides what you have set in G-Helper ? I would just manually stop `ArmouryCrate` service in windows Services app (if you don't want to uninstall it) and check if it works fine :)

I honestly don't understand what exactly do you want from me now :)

If you want to use AC - you can do that. If you want to use G-Helper - you also can do that. But when you use both, apparently AC just overrides everything. But I can't "fix" that anyhow obviously

**Comment by elfi-ox** [comment]
Sorry if I wasn't clear with that too, It works correcty now. I just wanted to explain how I fixed it so If someone have the same problem, they can search it here and find the answer instead of opening an issue like I just did. I didn't mean to waste your time🙏
I'll close the Issue then

**Comment by seerge** [comment]
@elfi-ox no worries, good luck :)
