### ISSUE TITLE
Add the possibility to Disable GPU Fan on Eco

### ISSUE THREAD

**Issue by elfi-ox** [seerge/g-helper#3133]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

It's not really a bug because fan curve are controlled by BIOS and it does some weird things sometimes

At first when I used Eco mode, both my fan where off and passive cooling was plenty enough to cool my only CPU but some weird magic happened and my overall temps became low enough on Performance for my fan to turn Off EVEN with my GPU running. Naturally it started to annoyingly oscillate between 0RPM and 3000 because obviously, The GPU is too hot to run without fans, so I had to lower my 0rpm threshold 

The problem is that now, even when the GPU is supposedly off, its fan are still running... I don't really know why.

### Describe the solution you'd like

I do understand that G-Helper doesn't manage the black magic that is the BIOS fan controller but I thought that a good solution would be to add an checkbox or a line in config.json that allows G-Helper to apply a special curve (like 0Rpm before 70°C) when Eco Mode is enabled for the GPU

### Describe alternatives you've considered

I thought of fan profiles that changes depending on if the Labtop is plugged or on battery but it seems really annoying to integrate and make it customizable into the UI, got too many variables and seems against the purpose of G-Helper which is to be lightweight 

### Device and Model

Asus Rog Strix G15 2022 G513RW

### Additional information.

I wrote all this considering that it doesn't already exist because I didn't found a list of all the config.json settings and don't understand those who are already there but I may be wrong of course

**Comment by seerge** [comment]
@elfi-ox hello, did you try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272) ? There you should be able to create a GPU fan curve that will stay OFF for a long time.

**Comment by elfi-ox** [comment]
Oh, interesting. No I didn't tried this, when you write "Please test on your own risk" what kind of behavior should I expect for such a experimental build ?

**Comment by seerge** [comment]
@elfi-ox they are literally mentioned in the post itself :) just read it till the end.

> Potential downsides and risks
>-If you quit application incorrectly during manual fan control, fans may keep running on last used speed and will not react on temperature changes
>-No idiot-protection. If you set fan speeds to be low, they will be low and your device will heat up quickly

**Comment by elfi-ox** [comment]
Oh big sorry 🙏 I missed that

**Comment by seerge** [comment]
@elfi-ox great. Let me know if it works for you.
