### ISSUE TITLE
Music effect is missing on RGB keyboard

### ISSUE THREAD

**Issue by Minemetero** [seerge/g-helper#3134]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

![Screenshot 2024-09-19 090351](https://github.com/user-attachments/assets/83c8631b-930b-4a5f-a3d3-adf918e86140)
![Screenshot 2024-09-19 090420](https://github.com/user-attachments/assets/6bdf828d-c78f-43f1-b1b7-723d2828bda9)

### Describe the solution you'd like

I hope I'll see it on G-Helper

### Device and Model

ROG Zephyrus G16 GU605MV

**Comment by Minemetero** [comment]
Also, it will be nice if we can decide the language to use on G-Helper.

**Comment by Minemetero** [comment]
Also for aura effect, like wallpaper's aura effect

**Comment by seerge** [comment]
@Minemetero hello,

As for this "music" effect, what exactly does it do ? Change brightness based on music volume ?

To answer 2 other questions
- you can [already change language](https://github.com/seerge/g-helper/wiki/Power-user-settings#manual-app-language-setting)
- if under wallpaper aura effect you mean just animated wallpapers - [you can just use something like this ](https://apps.microsoft.com/detail/9nm8n7dq3z5f?hl=en-US&gl=US)

**Comment by Minemetero** [comment]
I'm sorry, I think it was a mistake. This is actually what Aura creates do.

**Comment by Minemetero** [comment]
But let's jump to another question :)
