### ISSUE TITLE
Possible to disable change to ghelper settings when charger added/removed

### ISSUE THREAD

**Issue by runawayjim123** [seerge/g-helper#3139]
Hi, I don't like my settings (CPU, GPU, etc.) to change each time I plug and unplug the charger. Is it possible to disable this behavior? I prefer to control it manually only.

And I cannot fix the problem by simply setting CPU/GPU to the same value in both conditions because I often change the setting based on what I am doing. 

Thank you!

**Comment by seerge** [comment]
@runawayjim123 hmm, currently whole app logic is built around remembering last used settings per on battery / plugged in cases.

Can you explain from a practical standpoint why just setting same mode (to prevent switching) doesn't suit you ?

**Comment by runawayjim123** [comment]
Because I mostly move around my home and my office, unplugging and plugging
in as I go. I don't really base my modes on being plugged and unplugged. If
I'm just tooling around the internet I set to Silent/Eco/60hz. If I'm
gaming I'll switch to Turbo/Standard/165z.

If I move from my bedroom to my kitchen, I don't want everything to change
on me, especially since changing gpu and refresh rate in the middle of a
game can have unpredictable results.

Setting same mode does not fix the problem because I don't know what same
mode to use, it depends on what I am doing. If I set them both to
Silent/Eco/60hz and then start gaming, I would have to switch them both
again (and I don't even know how to change the mode for unplugged if I am
plugged...).

**Comment by seerge** [comment]
@runawayjim123 I honestly think this is very exotic. And also don't forget that `Turbo` on battery and `Turbo` when plugged in behave differently still due to firmware limitations

I have added an optional param that you can set in `config.json` to disable whole power-change event if you need to

```
"disable_power_event": 1,
```

Try this build
[GHelper.zip](https://github.com/user-attachments/files/17083789/GHelper.zip)

**Comment by runawayjim123** [comment]
Yes, it is exotic. Admittedly I am coming from mac and ipad, and it has
been hard for me to get used to all the automated changes in Windows. But
it does mess things up for me. Yesterday when I unplugged to switch rooms
my Beam eyetracking was disabled (I believe because of the gpu change) and
I had to re-enable it.

Thank you for letting me know about Turbo. I knew Asus limited CPU
performance when unplugged, I thought you had somehow programmed around
that. Does this also mean when plugged in with a non-asus charger that the
CPU is limited in Turbo? I would assume that is also in the firmware.

Thank you for the build and the product!

**Comment by seerge** [comment]
@runawayjim123 i'm also 90% mac user. Mac also lowers it's power consumption on battery a bit :)

All modes behave differently when you are plugged in, on battery or on USB-C. Usually with much stricter restrictions on battery. All power is always managed by firmware :)

As I understand build works for you ? Then i'm closing this as completed

**Comment by runawayjim123** [comment]
Yes, thank you again!
