### ISSUE TITLE
Battery charge limit broken

### ISSUE THREAD

**Issue by 123dqwkhjk** [seerge/g-helper#3140]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Before updating to version 0.190, the 60%, 80%, 100% battery charge limit is working.

1. After I manually update to version 0.190. I set the battery charge limit to 60% and reboot. It's go back to 80%.
2. when I set the slider to 60%, it jump back to 80%.

https://github.com/user-attachments/assets/b190b087-0291-41ca-afc4-b8ae294c30a3

### How to reproduce the bug?

1. set the battery charge limit to 60% and reboot. It's go back to 80%.
2. when I set the slider to 60%, it jump back to 80%.

### Logs

[log.txt](https://github.com/user-attachments/files/17069938/log.txt)

### Device and Model

Asus Zephyrus G15 GA503RM

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.190

### OS

23H2 (22631.4169)

**Comment by Minemetero** [comment]
It will be fix in 0.192 I believe

**Comment by Minemetero** [comment]
Clone the repo and package then try again

**Comment by Minemetero** [comment]
Cuz I saw he did a commit about that
