### ISSUE TITLE
GPU Max Power

### ISSUE THREAD

**Issue by lastangel32** [seerge/g-helper#3141]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Have max GPU power too low
my video card have max power 90W but i can set GPU only to 65w
use old version and latest version, have some problem

### How to reproduce the bug?

Oper G-Helper and go to Fun/Power
![image](https://github.com/user-attachments/assets/0be8fe84-11a4-4932-9207-121dd54c3637)

this is my nvidia proprieties 
![image](https://github.com/user-attachments/assets/ea4a8836-2739-4d96-a783-c78a4b79e73a)

### Logs

[log.txt](https://github.com/user-attachments/files/17073028/log.txt)

### Device and Model

Asus ROG Zephyrus G14 GA403UI

### Armoury Crate

Uninstalled

### Version

0.191

### OS

Windows 1124h2

**Comment by seerge** [comment]
@lastangel32 hello,

On ASUS laptops this max power consists of 2 components - GPU power (65W) + Dynamic Boost (25W). Together it's exactly 90W as it should be :) **so everything is correct.**

You have exactly same ranges in Armoury Crate's Manual mode settings.

Thanks

**Comment by lastangel32** [comment]
oh perfect :D
