### ISSUE TITLE
Flash touchscreen status when using the touchsceen toggle from one of the ASUS hotkeys

### ISSUE THREAD

**Issue by switchblade34** [seerge/g-helper#3143]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Not related to any problem

### Describe the solution you'd like

On my FlowX16 I can set the M3 button to toggle the touchscreen. I was hoping is there way to add a pop-up flash similar to one that appears when changing the keyboard lighting brightness to tell the user if the touchscreen was turned on or off. 

### Device and Model

Asus Flow X16 GV601VI

**Comment by seerge** [comment]
@switchblade34 hello,

I'm not sure if I'm following you.

You can already toggle touchscreen via hotkeys (set under `Extra`). And if touchscreen toggle was successful - it already show a toast notification saying if it's ON or OFF

Please keep in mind, due to the way toggle works (it disables it via device manager) - it requires admin rights. So you need to run app as admin.

https://github.com/seerge/g-helper/blob/ab08bd8ab45774b3e1961ddff69b6281a2f6e733/app/Input/InputDispatcher.cs#L595

**Comment by seerge** [comment]
@switchblade34 does running app as admin solve your problem ?

**Comment by switchblade34** [comment]
Yep, it is running as admin. When I did the toggle the first time, it asked for admin rights which I gave. It turns the touchscreen on and off. It's just the toast that's not showing up.

**Comment by seerge** [comment]
@switchblade34 can you upload log from the app from `%appdata%\GHelper` here?

**Comment by switchblade34** [comment]
[log.txt](https://github.com/user-attachments/files/17089157/log.txt)

**Comment by seerge** [comment]
@switchblade34 ok, it looks like a toggling is indeed happening in your case. So toast notification should appear as well.  Do other notifications appear correctly ? (like backlight level)

At what moment do you press the button to toggle? Cause if you run a full-screen game then, it may not allow any notifications then.

Can you try this build and upload log from it ?

[GHelper.zip](https://github.com/user-attachments/files/17089221/GHelper.zip)

**Comment by switchblade34** [comment]
Yes, the toggle happens. It's just the toast that's not displaying. I am not in any app when switching. Doesn't show up even when I am on my desktop. Other toasts like backlight, brightness, aura modes, performance modes; all those toasts work fine. 

Tried the attached build. Still does not show the toast. But it still does toggle the touchscreen. Logs attached. 

[log.txt](https://github.com/user-attachments/files/17089799/log.txt)

**Comment by seerge** [comment]
@switchblade34 hmm, it's strange, cause toast in this case is same as in all others. 

Furthermore, i tried it on my laptop and toast appears (keep in mind it appears with like a 1-2 seconds delay, cause whole command to toggle touchpad takes time)

Can you try this build and post a log ?
[GHelper.zip](https://github.com/user-attachments/files/17089846/GHelper.zip)

**Comment by switchblade34** [comment]
Still no toast. I waited for 10sec between each toggle to give time for the toast to appear but it did not. 
Log attached: 
[log.txt](https://github.com/user-attachments/files/17089947/log.txt)

**Comment by seerge** [comment]
@switchblade34 ok. Weird :) 

Can you check this build ? I have just added a dummy touchpad toast even before actual toggle happens to see if it appears in your case or not
[GHelper.zip](https://github.com/user-attachments/files/17090193/GHelper.zip)

**Comment by switchblade34** [comment]
This build works. 

Behaviour:

Touchscreen is set to on at the start. 

1. Press M3
2. Toast appears with touchpad icon and says touchscreen on
3. Moments later it updated to touchsceen off with the same touchpad icon
4. I swipe around on the screen and the touchscreen is indeed off. 

Works the same when turning it back on as well. It works now.

**Comment by seerge** [comment]
@switchblade34 ok, glad to hear. Can you check if this build still works ?

It won't show a dummy (and incorrect) toast first, but will should show only correct one. The only difference it would show it before actually running actual toggle command (to tackle delay)

[GHelper.zip](https://github.com/user-attachments/files/17098253/GHelper.zip)

**Comment by seerge** [comment]
@switchblade34 did you had a chance to try last build  ?

**Comment by switchblade34** [comment]
Sorry, had a busy day. Just tried the latest build and it works fulll as expected including the toast. 
The only nitpick issue I would say is that the icon in the update toast is that of the touchpad. The functionality is working just an UI issue remaining I would say.

**Comment by seerge** [comment]
@switchblade34 well, i don't have an icon for a screenpad :) and since it's such a minor thing I suggest to keep it as is.

Closing as resolved then

**Comment by switchblade34** [comment]
Yea sure no worries. A quick google search got me [this](https://www.flaticon.com/free-icon/user-interface_6394562?term=touch+screen&page=1&position=4&origin=tag&related_id=6394562) icon that you could use if you like.
