### ISSUE TITLE
Strix Impact: Sensitivity seems really off

### ISSUE THREAD

**Issue by brian2lee** [seerge/g-helper#3146]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Just change from armoury crate to g-helper. Sensitivity seems really off, I had it on 1600/1000 on my old armoury crate, had it on 3200/1400 on g-helper and still feel weird. I haven't change anything with mice when changing from armoury crate to g-helper, how can I get my old sensitivity back? btw the mice settings kept going back to default when starting the computer so I had to import it back everytime, is this suppose to happen? 

### How to reproduce the bug?

Just installed as what the setup instruction says, the import problem only occuer when restarting the computer.

### Logs

[log.txt](https://github.com/user-attachments/files/17082612/log.txt)

### Device and Model

ROG Zephyrus M16 GU603HM
mice: strix impact

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.187.0

### OS

Windows 10 22h2

**Comment by seerge** [comment]
@brian2lee hello, as I understand you talking about your Strix Impact mouse here.

Your mouse reports 2 profiles with 3200 and 1400 DPI correspondingly
```
2024/9/21 上午 11:15:54: Strix Impact: Read DPI Setting 1: DPI: 3200, Color (255, 0, 0)
2024/9/21 上午 11:15:54: Strix Impact: Read DPI Setting 2: DPI: 1400, Color (255, 0, 0)
```

- Do you have any Armoury leftowers running, as they may override any settings you had. 
- Did you use official AC uninstaller ?
- Did you change mouse acceleration settings in windows ? If so - make sure to turn it OFF there https://www.lifewire.com/turn-off-mouse-acceleration-in-windows-11-5193828

**Comment by brian2lee** [comment]
@seerge I uninstalled my previous ac using the official uninstaller. However there has been many report that it does not do the job thoroughly, which I do encounter in my case. So I ran another [script](https://gist.github.com/allenk/fcbee909fbf8fb9a54d4484297a1eeba) to clean it after the official uninstaller. 
My mouse acceleration settings is off.

**Comment by seerge** [comment]
@brian2lee can you use this build (with verbose logging), try to set different DPI settings few times and post a log from it ?

[GHelper.zip](https://github.com/user-attachments/files/17083461/GHelper.zip)

**Comment by brian2lee** [comment]
@seerge The package seems the same (even has my other settings already setup on the initial launch, seems like just another launcher). And I don't understand what do you mean by verbose logging? Where can I set it up?

**Comment by seerge** [comment]
@brian2lee you need to use the build i linked to you above, and after upload log from `%appdata%\GHelper`

**Comment by brian2lee** [comment]
@seerge I meant the build seems like just another launcher (like different entrance but same content, since it has my original setup the first time I used the linked build). Here's the log after running the new build and some sens change.
[log.txt](https://github.com/user-attachments/files/17083697/log.txt)

**Comment by seerge** [comment]
May be @IceStormNG knows why mouse refuses DPI settings here ? :)

```
2024/9/21 下午 05:31:18: Strix Impact: DPI for profile 2 set to 1400
2024/9/21 下午 05:31:19: Strix Impact: Sending packet: 00 51 31 01 00 0c 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  Try 1 of 3
2024/9/21 下午 05:31:19: Strix Impact: Write took 1ms
2024/9/21 下午 05:31:19: Strix Impact: Read took 1ms
2024/9/21 下午 05:31:19: Strix Impact: Read packet: 00 51 31 01 00 0c 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
2024/9/21 下午 05:31:19: Strix Impact: Sending packet: 00 50 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  Try 1 of 3
2024/9/21 下午 05:31:19: Strix Impact: Write took 1ms
2024/9/21 下午 05:31:19: Strix Impact: Read took 1ms
2024/9/21 下午 05:31:19: Strix Impact: Read packet: 00 ff aa 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
2024/9/21 下午 05:31:19: Strix Impact: Mouse returned error (FF AA). Packet probably not supported by mouse firmware.
2024/9/21 下午 05:31:19: Strix Impact: Settings Flushed 
```

**Comment by IceStormNG** [comment]
I have a guess why this happens. @brian2lee I know you removed AC, but maybe you remember this:
When you changed DPI of the mouse in AC, do you know whether it was in 100 increments or 200 increments? My guess is that the increments are wrong in the mouse descriptor of GHelper.

**Comment by brian2lee** [comment]
@IceStormNG I don't recognize there's increment setting in ac though, at least I didn't see or touch anything increment related in the mice section in ac. Same with ghelper, I don't see there's increment in my strix impact mice setting. If 200/100 increment is the case, it explains why the new 3200 dpi feel like the old 1600, but new 1400 feel like old 1000 seems way off.

**Comment by IceStormNG** [comment]
Increment is not a setting. It's simply how large the steps are. Some mice have increments of 50 DPI some have 100, some older have 200. This mouse here has 100 currently and a minimum DPI of 200.
Reason: The mouse does not store the DPI as number, but as a factor that is multiplied by the increment.

**Comment by IceStormNG** [comment]
If you can, either install AC on a separate machine or in a virtual machine. I need some testing done with AC to see what it can do. The mouse profile is the way it is because of testing done with previous user that reported the info.

Either, there was a firmware update, which changes some settings, or the user did not properly test it.

If you don't want to install AC on your current machine, just install it into a VM, and pass through the mouse for testing purpose.

After the test is done, you can delete the VM.

**Comment by brian2lee** [comment]
I haven't change mice though, as you mentioned increments is not a setting but difference from mice to mice, shouldn't it not affect dpi setting at all since it's basically a constant?

**Comment by IceStormNG** [comment]
Correct. If your mouse was set to 1600/1000 and GHelper has not managed to overwrite that, then it should still be the same.

The problem is: can you verify that GHelper did not change any DPI settings on the mouse?

**Comment by brian2lee** [comment]
Even though I would like to test it, ac seems to have a [memory leak problem](https://www.reddit.com/r/ASUSROG/comments/1951gfy/armory_crate_service_high_memory_usage/) (the issue seems to being around for a long time and hasn't been fixed by asus with newer version), which I believed is the main issue that heavily lags computer input and lead to my ac uninstallation (recently I just post an [issue](https://superuser.com/questions/1856180/my-computer-is-lagging-all-of-a-sudden-task-manager-showed-nothing) just to find out what's causing the lag). And asus doesn't seems to provide old version ac, which eliminates the possibility of me testing with an old ac without input lagging.
I'm not sure, but as far as I can see ghelper only has dpi. Things like polling rate, click response time shouldn't be affecting dpi right? Here's the mice setting (had to zip it for upload format).
 [default.zip](https://github.com/user-attachments/files/17084124/default.zip)

**Comment by brian2lee** [comment]
And also the performance mode seems to be unstable. I had been using the default setting from the beginning (with a slightly higher fan rpm). However the fans always slow down for no reason, running at 5500 rpm despite cpu being at 95 C. Only if I tap on turbo mode again it will return to the higher speed it should have been running for a while and still slow down after a while.
[log.txt](https://github.com/user-attachments/files/17100796/log.txt) this log file is upload when it should have been running in turbo mode for at least the past hour.

**Comment by seerge** [comment]
@brian2lee can you actually check what DPI / sensitivity options you had in AC as @IceStormNG was asking? Ideally just make a screenshot of what AC offers for you.

As for fan behavior - fans are [always controlled by BIOS](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds). You can try to adjust custom fan curve to tweak that a bit.

**Comment by brian2lee** [comment]
For ac I only remember I had dpi 1 on 1600, dpi 2 on 1000, polling rate 1000 hz, button response 12 ms. The ghelper setting now is what I feel the closest to my original ac setting.
<img width="337" alt="螢幕擷取畫面 2024-09-24 083229" src="https://github.com/user-attachments/assets/92fcf414-4387-4fd4-ad79-70646d3f3c6e">

**Comment by seerge** [comment]
@brian2lee yes, but what steps of sensitivity did you have in AC ?

**Comment by brian2lee** [comment]
@seerge what are steps of sensitivity?

**Comment by seerge** [comment]
@brian2lee in what range and in what steps does Armoury Crate let you change sensitivity if your mouse ? Can you please post a screenshot ?

**Comment by brian2lee** [comment]
@seerge As I mentioned before ac was uninstalled, reinstalling will cause lags and crashes. From what I remembered the changeable dpi range was ?~5000
this is the closest image setting I could find on the internet. Difference between my old ac setting are dpi 2 being 1000, missing just the button response, which I set at the shortest possible time 12 ms
![image](https://github.com/user-attachments/assets/82a4bebc-f016-42fe-9eb6-27a39fa9c6b8)

**Comment by seerge** [comment]
@brian2lee well, since we don't know exactly neither range of DPI nor steps DPI change - I can only guess here.

Try this build and post a log from it. I have set min **DPI to 50** (as on screenshot) and DPI steps are also **set to 50**

[GHelper.zip](https://github.com/user-attachments/files/17116258/GHelper.zip)

**Comment by brian2lee** [comment]
@seerge When clicking on the strix impact in the new build, an error appears, continue the process will just run ghelper without the mice setting section.
```
如需叫用 Just-In-Time (JIT) 偵錯的詳細資料，
請參閱本訊息結尾處 (而非這個對話方塊) 的資訊。

************** 例外狀況文字 **************
System.ArgumentOutOfRangeException: '6400' 不是 'Value' 的有效值。'Value' 應該介於 'Minimum' 與 'Maximum' 之間。 (Parameter 'value')
Actual value was 6400.
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at GHelper.AsusMouseSettings.SliderDPI_ValueChanged(Object sender, EventArgs e) in C:\Users\Serge\g-helper\app\AsusMouseSettings.cs:line 407
   at GHelper.UI.Slider.set_Value(Int32 value) in C:\Users\Serge\g-helper\app\UI\Slider.cs:line 87
   at GHelper.AsusMouseSettings.VisualizeCurrentDPIProfile() in C:\Users\Serge\g-helper\app\AsusMouseSettings.cs:line 890
   at GHelper.AsusMouseSettings.VisualizeMouseSettings() in C:\Users\Serge\g-helper\app\AsusMouseSettings.cs:line 693
   at GHelper.AsusMouseSettings.RefreshMouseData() in C:\Users\Serge\g-helper\app\AsusMouseSettings.cs:line 473
   at GHelper.AsusMouseSettings..ctor(AsusMouse mouse) in C:\Users\Serge\g-helper\app\AsusMouseSettings.cs:line 114
   at GHelper.SettingsForm.ButtonPeripheral_Click(Object sender, EventArgs e) in C:\Users\Serge\g-helper\app\Settings.cs:line 1901
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)


************** 已載入的組件 **************
System.Private.CoreLib
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Private.CoreLib.dll
----------------------------------------
GHelper
    組件版本: 0.192.0.0
    位置: 
----------------------------------------
System.Runtime
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Runtime.dll
----------------------------------------
System.Windows.Forms
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.8\System.Windows.Forms.dll
----------------------------------------
System.Threading.Thread
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Threading.Thread.dll
----------------------------------------
System.ComponentModel.Primitives
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.8\System.Windows.Forms.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Collections.Specialized.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.8\Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Diagnostics.Process
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Diagnostics.Process.dll
----------------------------------------
System.Collections
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Collections.dll
----------------------------------------
System.ComponentModel.TypeConverter
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Text.Json
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Text.Json.dll
----------------------------------------
System.Threading
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Threading.dll
----------------------------------------
System.Memory
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Memory.dll
----------------------------------------
System.Text.Encoding.Extensions
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Text.Encoding.Extensions.dll
----------------------------------------
System.Text.Encodings.Web
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Runtime.Intrinsics.dll
----------------------------------------
System.Numerics.Vectors
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Numerics.Vectors.dll
----------------------------------------
System.Private.Uri
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Private.Uri.dll
----------------------------------------
System.Collections.Concurrent
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Collections.Concurrent.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Runtime.InteropServices
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Runtime.InteropServices.dll
----------------------------------------
Microsoft.Win32.Primitives
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\Microsoft.Win32.Primitives.dll
----------------------------------------
System.Management
    組件版本: 8.0.0.0
    位置: 
----------------------------------------
Microsoft.Win32.Registry
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\Microsoft.Win32.Registry.dll
----------------------------------------
System.Security.Principal.Windows
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Security.Claims.dll
----------------------------------------
System.Drawing.Common
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.8\System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Diagnostics.TraceSource.dll
----------------------------------------
GHelper.resources
    組件版本: 0.192.0.0
    位置: 
----------------------------------------
System.Resources.Extensions
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.8\System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.8\System.Drawing.dll
----------------------------------------
NAudio.Wasapi
    組件版本: 2.1.0.0
    位置: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    組件版本: 4.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.8\Accessibility.dll
----------------------------------------
System.ComponentModel
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.ComponentModel.dll
----------------------------------------
HidSharpCore
    組件版本: 2.1.0.0
    位置: 
----------------------------------------
System.Linq
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Linq.dll
----------------------------------------
System.Threading.ThreadPool
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Threading.ThreadPool.dll
----------------------------------------
Microsoft.Win32.TaskScheduler
    組件版本: 2.10.1.0
    位置: 
----------------------------------------
System.ObjectModel
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.ObjectModel.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Text.RegularExpressions
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Text.RegularExpressions.dll
----------------------------------------
System.Xml.ReaderWriter
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Private.Xml.dll
----------------------------------------
System.Runtime.Loader
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.8\zh-Hant\System.Windows.Forms.resources.dll
----------------------------------------
NvAPIWrapper
    組件版本: 0.8.1.100
    位置: 
----------------------------------------
netstandard
    組件版本: 2.1.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\netstandard.dll
----------------------------------------
System.Diagnostics.PerformanceCounter
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.8\System.Diagnostics.PerformanceCounter.dll
----------------------------------------
System.Threading.Overlapped
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Threading.Overlapped.dll
----------------------------------------
System.Collections.NonGeneric
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Collections.NonGeneric.dll
----------------------------------------
System.Net.Http
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Net.Security.dll
----------------------------------------
System.Security.Cryptography
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Security.Cryptography.dll
----------------------------------------
System.Net.Sockets
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Net.Sockets.dll
----------------------------------------
System.Net.NameResolution
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Net.NameResolution.dll
----------------------------------------
System.Diagnostics.StackTrace
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.Collections.Immutable.dll
----------------------------------------
System.IO.Compression
    組件版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\System.IO.Compression.dll
----------------------------------------

************** JIT 偵錯 **************
```

**Comment by seerge** [comment]
@brian2lee ok, and this ? (also post a log from it)

[GHelper.zip](https://github.com/user-attachments/files/17134511/GHelper.zip)

**Comment by brian2lee** [comment]
@seerge The new build feel right like my old one, no problem seems to appear for now. 
[log.txt](https://github.com/user-attachments/files/17141618/log.txt)

**Comment by seerge** [comment]
@brian2lee ok, good. 

So sensitivity settings in this build are same as in AC, while in old / mainstream version - they were not matching ? 

I still see errors from your mouse not accepting DPI tho ...  so it's strange.
```
2024/9/26 上午 09:55:21: Strix Impact: DPI for profile 2 set to 600
2024/9/26 上午 09:55:21: Strix Impact: Write took 0ms
2024/9/26 上午 09:55:21: Strix Impact: Read took 0ms
2024/9/26 上午 09:55:21: Strix Impact: Write took 1ms
2024/9/26 上午 09:55:21: Strix Impact: Read took 1ms
2024/9/26 上午 09:55:21: Strix Impact: Mouse returned error (FF AA). Packet probably not supported by mouse firmware.
2024/9/26 上午 09:55:21: Strix Impact: Settings Flushed 
```

**Comment by brian2lee** [comment]
@seerge I haven't been updating ac since new version having memory leak problem been a thing, which somehow still occurred after being on old version for such a long time. Maybe my old ac version is the reason of  sensetivity setting being same as old / mainstream version ac?
On the other hand the fan problem is getting more severe, running at low speed despite being on turbo causes overheating at 95 and serious lags. However I think it's off topic here, will post a new issue for this.

**Comment by seerge** [comment]
@brian2lee I have asked if DPI setting from build linked here is different from the existing version of G-Helper you were using, not about AC.

**Comment by brian2lee** [comment]
@seerge I don't get what you meant exactly by "DPI setting from build is different from the existing version of G-Helper you were using", but the linked build's 1600dpi feel like the official build's 3600dpi, which is similar to my old ac's 1600dpi.

**Comment by seerge** [comment]
@brian2lee but that's what i was asking :) if "new" build linked here behaves same as Armoury (i.e. correct?) and old build behaves differently - then it's good. I will push this changes live and also update Experimental manual build with that as well, as you asked in other thread.

**Comment by brian2lee** [comment]
@seerge At least for me the new build behave much like ac than the old one (difference between 3600 and 1600 is quite big so I doubt my feeling is wrong). 
I saw the the updated experimental build, will try it out first. Thanks for your help.

**Comment by seerge** [comment]
@brian2lee as for your other problem with saving profile, I either need physical access to device (which is difficult cause it's veeeery old) or someone to actually intercept an actual USB payload that Armoury sends to the mouse to save profile. It could be different here. 

And since you don't want to install AC - i can't do much :)

**Comment by brian2lee** [comment]
@seerge Have been though a lot of torture and pain when dealing with ac's lagging and all the solving procedure, I think I can live with a little more work (import setting) when booting. You've helped far more than I expected, I'm glad that I found ghelper instead of trying to stick with ac.
