### ISSUE TITLE
GA503RM 319 Ghelper experemental version swaped curves 

### ISSUE THREAD

**Issue by alxonk** [seerge/g-helper#3149]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hello, in the experimental version of Ghelper in bios 319, could you swap the values ​​of the curves, because again the curve of the GPU controls the rotation of the CPU and vice versa. In the regular version curves are correct

### How to reproduce the bug?

![{D79E5136-BFEA-4DDB-AF69-5A05D22B9737}](https://github.com/user-attachments/assets/74a774aa-4f92-4bec-b438-230b0f7ccbaa)

![{683CDA34-C744-4C5E-869A-16D67BFD13B3}](https://github.com/user-attachments/assets/291af6ea-33f1-48b4-b8da-d229e291f265)

### Logs

[log.txt](https://github.com/user-attachments/files/17084694/log.txt)

### Device and Model

Zephurus G15 GA503RM 2022

### Armoury Crate

Uninstalled

### Version

0.191.0

**Comment by seerge** [comment]
@alxonk can you try this build ?

[GHelper.zip](https://github.com/user-attachments/files/17084731/GHelper.zip)

**Comment by alxonk** [comment]
> @alxonk can you try this build ?
> 
> [GHelper.zip](https://github.com/user-attachments/files/17084731/GHelper.zip)
> 
> It's not G-Helper swapping curves just in case, it's still bugged BIOS :) I have just applied my "fix" to a new BIOS version as well

Yes, this build works fine, thank you :)

**Comment by seerge** [comment]
@alxonk great, i have also updated build in a main experimental thread
