### ISSUE TITLE
The flicker-free dimming shortcut is limited to values of 0% and 9% only

### ISSUE THREAD

**Issue by tkdk1977** [seerge/g-helper#3152]
### Rules

- [ ] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [ ] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When using the shortcut keys to adjust flicker-free dimming, Ctrl+Fn+F7 locks the parameter to 0%, and Ctrl+Fn+F8 locks it to 9%. These are the only two values available, and it is not possible to adjust to other values. The issue arose after updating to version 0.191, so I reverted to version 0.190, and everything is fine now. 

### How to reproduce the bug?

Use shortcut Ctrl+Fn+F7 or F8

### Logs

[log.txt](https://github.com/user-attachments/files/17088374/log.txt)

### Device and Model

Asus zephyrus G14 GA403UV

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.191

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@tkdk1977 hello, thanks for spotting.

This build should work fine
[GHelper.zip](https://github.com/user-attachments/files/17088791/GHelper.zip)

**Comment by tkdk1977** [comment]
Problem fixed 👍
very appropriate 😊
