### ISSUE TITLE
Config export

### ISSUE THREAD

**Issue by Flex223** [seerge/g-helper#3153]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

The app sometimes loses its configuration, especially after an update. It can be really frustrating to lose all the settings you spent 10 minutes setting up.

### Describe the solution you'd like

I would like the app to have a manual configuration export feature. This way, users can save their settings before an update and easily import them if needed, preventing the frustration of having to set everything up again.

### Describe alternatives you've considered

The app could automatically search for a saved configuration if it detects that the settings have been lost or are missing. This would allow the app to restore user settings without manual intervention.

Fix the issue of losing configuration after updates. Ideally, the app should be updated in a way that preserves the current configuration, so users don't experience any loss of settings during the update process.

### Device and Model

Asus Zephyrus M16

**Comment by seerge** [comment]
@Flex223 hello, app already has 2 staged config writing (it writes to a backup config first, and then to the main one) to prevent such things when windows does something weird with file writing

https://github.com/seerge/g-helper/blob/main/app/AppConfig.cs#L68 

Same applies to reading (it will read main config and use backup if that one is by some reason damaged)

You can also manually just copy `%appdata%\GHelper\config.json` somewhere of course

In what specific situations are you loosing config? Do you have some clear scenario to reproduce ?

**Comment by seerge** [comment]
@Flex223 any updates here ? 

On a side note, I have made a couple of small tweaks to config writing. Let me know if this build looses config in your situations
[GHelper.zip](https://github.com/user-attachments/files/17113015/GHelper.zip)

**Comment by Flex223** [comment]
It happened after I updated it. It's strange because sometimes the update takes me to the browser to download, but other times it just closes and updates automatically. It's during the latter scenario that it loses the configuration.
Thanks for the tweaks, i'll try it out.

**Comment by seerge** [comment]
@Flex223 when you auto-update, newly downloaded app terminates old one. So it could be that it was terminated in the middle of writing something to config. Changes that I did should prevent that :)

I'm closing this as resolved for now, feel free to post an updates if you will spot anything
