### ISSUE TITLE
TUF A16 FA607PI Press the Num LK key, and there is no corresponding prompt animation on the screen

### ISSUE THREAD

**Issue by USTS-lab** [seerge/g-helper#3154]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

My computer is a TUF A6 FA607PI, and when I press the Num Lk key, the numeric keypad unlocks and locks accordingly, but there is no animation on the screen.  In contrast, other function switches are animated.
![this](https://github.com/user-attachments/assets/d2228d06-16db-4d96-a721-cf338f32128d)

### How to reproduce the bug?

 When I press the Num Lk key, the numeric keypad unlocks and locks accordingly, but there is no animation on the screen. 

### Logs

[log.txt](https://github.com/user-attachments/files/17090791/log.txt)

### Device and Model

Asus TUF  Gaming A16 FA607PI 

### Additional information.

![this](https://github.com/user-attachments/assets/92201ed2-f192-4826-80a9-730e79004d7f)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.191.0

### OS

windows11 23H2

**Comment by seerge** [comment]
@USTS-lab hello,

I'm sorry but how is this related to G-Helper ? CapsLock or NumLock is absolutely standard switches on pretty much any keyboard. Devices handle them on hardware level, they are absolutely not supposed to show any notifications, there is nothing to add here :)

Thanks

**Comment by USTS-lab** [comment]
Okay, perhaps the technical implementation of G-Helper fails to offer this animation. I have this question merely because the official software of Asus will provide this switch animation. Secondly, regarding other key functions, such as increasing the brightness of the keyboard backlight, the animations provided by G-Helper are completely distinct from those accompanying the Asus service, which I previously thought were offered by G-Helper. Imagine that since G-Helper can provide prompts for adjusting the brightness of the keyboard backlight, it can also offer prompts for numeric keyboards. I suppose I was incorrect about G-Helper.
Asus provides keyboard brightness adjustment tips：
![1234](https://github.com/user-attachments/assets/141aa43d-6e7f-4309-a7fc-9dda40fa2efe)
G-Helper provides keyboard brightness adjustment tips
![12345](https://github.com/user-attachments/assets/9528cb5f-45ef-4b29-95a8-d0a8df617f56)
Asus offers tips on and off the numeric keypad
![123](https://github.com/user-attachments/assets/281e66f6-df15-40e1-ba90-65b54b5c78d0)

**Comment by USTS-lab** [comment]
> 你好
> 
> 很抱歉，这与 G-Helper 有什么关系？CapsLock 或 NumLock 绝对是几乎所有键盘上的标准开关。设备在硬件级别处理它们，它们绝对不应该显示任何通知，这里没有什么可添加的:)
> 
> 谢谢



> 你好
> 
> 很抱歉，这与 G-Helper 有什么关系？CapsLock 或 NumLock 绝对是几乎所有键盘上的标准开关。设备在硬件级别处理它们，它们绝对不应该显示任何通知，这里没有什么可添加的:)
> 
> 谢谢
Okay, perhaps the technical implementation of G-Helper fails to offer this animation. I have this question merely because the official software of Asus will provide this switch animation. Secondly, regarding other key functions, such as increasing the brightness of the keyboard backlight, the animations provided by G-Helper are completely distinct from those accompanying the Asus service, which I previously thought were offered by G-Helper. Imagine that since G-Helper can provide prompts for adjusting the brightness of the keyboard backlight, it can also offer prompts for numeric keyboards. I suppose I was incorrect about G-Helper.
Asus provides keyboard brightness adjustment tips：
![1234](https://github.com/user-attachments/assets/5403ad46-61c8-4607-ac94-078c4cbbf1b7)
G-Helper provides keyboard brightness adjustment tips
![12345](https://github.com/user-attachments/assets/999b4168-4448-4f43-8c3f-b3eb2fa60fc0)
Asus offers tips on and off the numeric keypad
![123](https://github.com/user-attachments/assets/26e81aa6-547e-4d70-abe6-659428bde36e)

**Comment by USTS-lab** [comment]
> @USTS-lab hello,
> 
> I'm sorry but how is this related to G-Helper ? CapsLock or NumLock is absolutely standard switches on pretty much any keyboard. Devices handle them on hardware level, they are absolutely not supposed to show any notifications, there is nothing to add here :)
> 
> Thanks

@seerge Okay, perhaps the technical implementation of G-Helper fails to offer this animation. I have this question merely because the official software of Asus will provide this switch animation. Secondly, regarding other key functions, such as increasing the brightness of the keyboard backlight, the animations provided by G-Helper are completely distinct from those accompanying the Asus service, which I previously thought were offered by G-Helper. Imagine that since G-Helper can provide prompts for adjusting the brightness of the keyboard backlight, it can also offer prompts for numeric keyboards. I suppose I was incorrect about G-Helper.
Asus provides keyboard brightness adjustment tips：
![1234](https://github.com/user-attachments/assets/621c59ed-01a1-4513-a64a-f41ab93a095f)
G-Helper provides keyboard brightness adjustment tips：
![12345](https://github.com/user-attachments/assets/eeef7ee3-39fc-4931-8bb8-73fb6ab13541)
Asus offers tips on and off the numeric keypad
![123](https://github.com/user-attachments/assets/9e60ea97-e198-45f6-baa5-e69541bb62c9)

**Comment by seerge** [comment]
@USTS-lab can you open `%appdata%\GHelper\log.txt` and check if pressing num-lock produces any key-code in the log ?

**Comment by USTS-lab** [comment]
> @USTS-lab can you open `%appdata%\GHelper\log.txt` and check if pressing num-lock produces any key-code in the log ?

Hi, I clicked it a few times, but I don't see anything in the log.
![123455](https://github.com/user-attachments/assets/5cc15fee-97f9-4e60-939b-0a0b0ce0eb10)

**Comment by seerge** [comment]
@USTS-lab then there is simply no easy way to get notified about num-lock state change :) 
Also I can imagine wast majority (including myself) will be only annoyed about notifications about basic things as num or caps lock.

**Comment by USTS-lab** [comment]
> @USTS-lab then there is simply no easy way to get notified about num-lock state change :) Also I can imagine wast majority (including myself) will be only annoyed about notifications about basic things as num or caps lock.

@seerge I understand.  Since the G-Helper has no means of knowing if NUM LK is pressed, there is no way to add the relevant animation, is there?

**Comment by seerge** [comment]
@USTS-lab yes, there is no way, except constantly check for it's status in windows which is resource-heavy and also as I explained above not really needed
