### ISSUE TITLE
Ctrl+Shift+F5

### ISSUE THREAD

**Issue by PhantomGamerModz** [seerge/g-helper#3155]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

so I was playing minecraft and I noticed when I pressed ctrl shift and f5 at the same time it changes my power mode so I was wondering if I could turn it off, I went to settings and saw there was no option to disable it.

### Describe the solution you'd like

Adding the option to change this to something else

### Device and Model

Asus tuf gaming a16 advantage edition

**Comment by seerge** [comment]
@PhantomGamerModz hello,

Hello, keybindings for an external keyboards [are mentioned in readme](https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings).

And you can already [re-assign it to other key as explained in power user settings](https://github.com/seerge/g-helper/wiki/Power-user-settings#toggle-performance-mode-or-toggle-app-window-key-binding).

Thanks
