### ISSUE TITLE
Functions don't work when change language

### ISSUE THREAD

**Issue by RaZer0k** [seerge/g-helper#3156]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

adding: "language": "en" to config file in a windows 11 spanish installation... make functions like keyboard ilumination or screen brightness dont work aura buttons dont work to... removing this value from config work again.  

### How to reproduce the bug?

Add "language": "en" to config.json in a none English windows installation
Then try to press some keyboard iluminations or brightness
Don't work until i remove language setting

### Logs

[log.txt](https://github.com/user-attachments/files/17092628/log.txt)

### Device and Model

Flow X13 GV301RC

### Armoury Crate

Uninstalled

### Asus Services

disabled

### Version

0.192

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@RaZer0k hello, 

I'm sorry, but I'm unable to reproduce this (I just tried to set English language in the app manually). And furthermore it's not really connected anyhow.

- Is it only backlight and brightness controls that don't work ? Or more ? 
- Does backlight control work if you drag slider under `Extra` ?
- Did you try restarting app ?

**Comment by seerge** [comment]
@RaZer0k any updates here ?

**Comment by seerge** [comment]
Due to lack of response - closed as abandoned
