### ISSUE TITLE
Shortcut keys for Flicker-Free Dimming only goes from 0-10% (G16 2024)

### ISSUE THREAD

**Issue by anventia** [seerge/g-helper#3157]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I use the Flicker-Free Dimming shortcuts, (FN+CTRL+F7/8) on my G16 2024, it can only go from 0-10% brightness. If above that brightness when I press the keys, it jumps down to 10%. (it also shows 9% on the pop-up).

This problem started occurring with this version of G-Helper (0.191.0), and was not present before update. However, before I'd _occasionally_ get a similar bug where I'd try to change the flicker-free dimming via shortcut and it'd immediately jump down to 0%, before operating normally.

(aside: it'd be cool if it'd be possible to configure it to be just (FN)+F7/8 to control flicker-free! (FN depending on if function lock is on or not)

### How to reproduce the bug?

Press FN+CTRL+F7/8 

### Logs

[log.txt](https://github.com/user-attachments/files/17093915/log.txt)

### Device and Model

G16 2024 (GU605MI)

### Additional information.

(Video too large to upload here)
https://files.catbox.moe/t2vyyb.mp4

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.191.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@anventia hello, this is a [duplicate](https://github.com/seerge/g-helper/issues/3152) and is already fixed in https://github.com/seerge/g-helper/releases/tag/v0.192 :) just update.

Thanks.
