### ISSUE TITLE
Numlock indicator for TUF laptops

### ISSUE THREAD

**Issue by GorkemKarakaya** [seerge/g-helper#3158]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

There is no Numlock indicator on TUF laptops as we know and it'd be great to have a visual indicator if it's either on or off.

### Describe the solution you'd like

A something similar indicator that we already have like keyboard light level indicator or fan speed indicator would be a great solution.

### Device and Model

Asus TUF A15 FA507NV

**Comment by seerge** [comment]
@GorkemKarakaya hello, this is a dublicate of https://github.com/seerge/g-helper/issues/3154 . As I tried to explain there, num-lock is a very general feature that is handled by hardware, not by G-Helper. In addition there is no easy (and resource-effective) way to get notified when num-lock status changes.

**Comment by GorkemKarakaya** [comment]
> @GorkemKarakaya hello, this is a dublicate of #3154 . As I tried to explain there, num-lock is a very general feature that is handled by hardware, not by G-Helper. In addition there is no easy (and resource-effective) way to get notified when num-lock status changes.

Thank you for the assistance! I didn't know that it was harder to make than I've thought. I wish you a great day.
