### ISSUE TITLE
Incorrect number of ecores

### ISSUE THREAD

**Issue by Aeoustin** [seerge/g-helper#3160]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

when i go to set the number of e-cores in the CPU core configuration popup it shows that i have 8 e-cores even though I'm running on a 13th Gen Intel(R) Core(TM) i5-13450HX that has 6 p-cores and 4 e-cores. i am unable to take a screenshot of it because it doesn't let me when g-helper is open.

### How to reproduce the bug?

open g-helper, go to extras, press on (number) Ecores.

### Logs

[log.txt](https://github.com/user-attachments/files/17102186/log.txt)

### Device and Model

Asus Rog Strix G16 (2023) G614JU-SB51-CB

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.091.0

### OS

Windows 11 Home

**Comment by Aeoustin** [comment]
that fixes it, thanks. also i sent a 5$ dono around an hour ago. have a nice rest of your day or night!

**Comment by seerge** [comment]
@Aeoustin glad to hear, thanks
