### ISSUE TITLE
Trackapad stop working after last update

### ISSUE THREAD

**Issue by panicoli0** [seerge/g-helper#3162]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

After last update trackpad stop working.
ZRThis is happening on a Asus TUF F15 FX517ZR.

### How to reproduce the bug?

1. Install last update.
2. toggle trackpad on/off.

### Logs

[log.txt](https://github.com/user-attachments/files/17111951/log.txt)

### Device and Model

Asus TUF F15 FX517ZR

### Armoury Crate

Never installed

### Asus Services

None

### Version

0.191.0

### OS

Windows 11 Home 23H2

**Comment by seerge** [comment]
@panicoli0 hello, G-Helper is not a driver it's not handling your trackpad in a first place :)

If you man hotkey action for `FN+F10` then G-Helper emits `WIN + CTRL + F24` which is a windows shortcut for touchpad.
You can also check touchpad status in windows settings directly
![image](https://github.com/user-attachments/assets/fa1f726f-72c7-471e-87ab-3a9eea1bbbec)

And according to the log it works just fine
```
9/24/2024 1:27:16 PM: WMI event 107
9/24/2024 1:27:16 PM: Touchpad status:1
9/24/2024 1:27:29 PM: WMI event 107
9/24/2024 1:27:30 PM: Touchpad status:0
9/24/2024 1:27:36 PM: WMI event 107
9/24/2024 1:27:36 PM: Touchpad status:1
9/24/2024 1:28:33 PM: WMI event 107
9/24/2024 1:28:33 PM: Touchpad status:0
9/24/2024 1:28:35 PM: WMI event 107
9/24/2024 1:28:35 PM: Touchpad status:1
```

What exactly is not working for you ?

**Comment by panicoli0** [comment]
Hey @seerge 
Thanks for your prompt reply!

Its something related to Ultimate mode.
When any of the others modes trackpad works OK.

**Comment by seerge** [comment]
@panicoli0 i think you are just missing a driver, or something happened to it :) Ultimate mode is not related to trackpad.

As I explained above FN+F10 in G-Helper can only toggle touchpad toggle in windows (if it's ON for you - then everything is good)

Try to install (again) drivers for touchpad and also check windows device manager to see if touchpad device is there and enabled.

Thanks
