### ISSUE TITLE
CPU Power Limits Not Working

### ISSUE THREAD

**Issue by EminGT** [seerge/g-helper#3163]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Setting CPU power limit to low values no longer seems to actually limit anything on my Zephyrus G16 2024 (Core Ultra 9). I believe it used to work fine a week ago when I first got G Helper but since then something might have happened that broke it.

### How to reproduce the bug?

1) Open G Helper
2) Set PL1 and PL2 to both 5W
3) Run a CPU test like https://cpux.net/cpu-stress-test-online
4) Observe that power discharge increased many times higher than +5 watts compared to idle

### Logs

[log.txt](https://github.com/user-attachments/files/17114849/log.txt)

### Device and Model

ROG Zephyrus G16 GU605MY

### Additional information.

I have only tested on battery for now

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.192.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@EminGT hello,

What exactly are you measuring (and how) ? Can you post a screenshot ?

Please keep in mind that bettery discharge rate (that you see in G-Helper) **is not power limit** . It's a total discharge that windows reports, and it includes screen, keyboard, SSD, and all other possible hardware components  you have. So it can easily be much higher that power limit that you set for CPU.

**Comment by EminGT** [comment]
I am just looking at the discharge rate. But I don't think that's useless. I am comparing the discharge rate at 80W CPU limit and 5W CPU limit and I'm not seeing much of a difference.

Idle: 5 to 8W discharge
CPU Stress Test at 80W limit: 25 to 30W discharge
CPU Stress Test at 5W limit: 25 to 28W discharge

This isn't normal right?

**Comment by EminGT** [comment]
I also want to add that there is no responsiveness difference between the 5W limited mode and 80W limited mode. Meanwhile a week ago I believe the 5W mode was insanely sluggish

**Comment by EminGT** [comment]
I got HWinfo and ran the test with 5W and 80W limits again, and whatever I do the CPU package power conspumption is always stuck at 10W. I tried plugging in, switching from Silent to Turbo, and no it's still stuck at 10W all the time.

![resim](https://github.com/user-attachments/assets/194718c2-a8db-4412-b5db-d99c45491387)

I'll try rebooting and running again

**Comment by EminGT** [comment]
After rebooting the problem is completely fixed and the power limit adjustments work correctly. But now the problem is that why does it get stuck like this from time to time? Because this isn't the first time I'm having this problem unfortunately

**Comment by seerge** [comment]
@EminGT i don't know :) may be some firmware hiccup ? You can try [to do a hard reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset).

- Do you use latest BIOS ?
- Do you have any other apps that can interfere (like Throttlestop or may be even something from Intel itself) ?

**Comment by EminGT** [comment]
Hm, I'll try doing a hard reset and see if it happens again in the future. I do have the latest bios (and all the other things g-helper has in the "Updates" section) and I don't use any other programs that can change power levels. Let's just hope it doesn't happen again I guess :p

**Comment by seerge** [comment]
@EminGT ok, good luck with that :)

Anyway, G-Helper sets power limits (if you choose so) via same endpoints as AC uses. And it's same for any Asus laptops. So it's most likely not much I can change or do here anyway.

If you will find a specific scenario that leads to this firmware missbehavior (like plugging / unplugging / going to sleep / etc) - let me know.

**Comment by EminGT** [comment]
Yeah I see, that's fair. Thank you for helping me out regardless. I'll let you know if I figure out what triggers it
