### ISSUE TITLE
Unhandled Exception Occurred

### ISSUE THREAD

**Issue by priyansh0512** [seerge/g-helper#3164]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When Opening Fans And Power, immediately pop up appears.
![{05E58AE9-BDC9-4857-A211-5C651AA7A6D8}](https://github.com/user-attachments/assets/58c6b325-e4f7-4fb1-b94d-f5da3eba27f1)

### How to reproduce the bug?

1. Fans + Power
2. Wait for 5 seconds or toggle any random setting.
3. Popup Appears

### Logs

[log.txt](https://github.com/user-attachments/files/17116689/log.txt)

### Device and Model

ASUS TUF A15 FA506IC

### Additional information.

![{9C7C24BB-AA4B-4174-A61B-525CE90B50CB}](https://github.com/user-attachments/assets/9016bb3e-df96-4c5b-8cb5-17a24d29ee4c)
I have Uninstalled and Reinstalled the latest .NET still issue persists.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.192.0 & also 0.191.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@priyansh0512 can you copy full contents  of the exception box here ?

But from first visible rows it looks like some internal windows/.NET thing

**Comment by seerge** [comment]
@priyansh0512 any updates here ?

I have updated chart-library G-Helper uses to draw fan-curve editor to the latest version, can you check if this build behaves differently ?

[GHelper.zip](https://github.com/user-attachments/files/17127760/GHelper.zip)

**Comment by priyansh0512** [comment]
Now working fine. Thank you! Sorry for the delay in response
