### ISSUE TITLE
Black Screen on Ultimate

### ISSUE THREAD

**Issue by lgarlati** [seerge/g-helper#3170]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When booting into ultimate from eco, the screen wouldn't work. It would show the white then red asus logo, but then black. However, everything else worked (windows hello, keyboard brightness, etc). But the screen would remain black. 

### How to reproduce the bug?

1. select eco
2. select ultimate
3. restart when prompted

### Logs

[log.txt](https://github.com/user-attachments/files/17132176/log.txt)

### Device and Model

Asus Zephyrus G16 GU605MZ

### Additional information.

This has only happened to me once despite doing exactly this many, many, many times before. 

The fix was to go into the bios and switch from "dGPU only" to "Dynamic" and restart.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.191.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@lgarlati hello, some models don't support setting `Ultimate` directly from `Eco`. You need to set `Standard` first.

But **G-Helper already knowns that** and sets it automatically for you (including GU605)

```
9/24/2024 8:49:35 AM: GPUEco = 0 : OK <----- ECO MODE DISABLE = STANDARD
9/24/2024 8:49:35 AM: GPUMux = 0 : OK <----- MUX OFF  = ULTIMATE
```

Does Ultimate work in general for you ? Does it turn correctly when you do it form `Eco -> Standard -> Ultimate` manually ?

**Comment by seerge** [comment]
@lgarlati P.S. I have added a 500ms delay between ECO = OFF and ULTIMATE = ON commands. Can you check if this build behaves differently ?

[GHelper.zip](https://github.com/user-attachments/files/17134543/GHelper.zip)

**Comment by lgarlati** [comment]
@seerge 
> Does Ultimate work in general for you ? 
Yes, never had any issues. 

> But G-Helper already knowns that and sets it automatically for you (including GU605)
Yep, and it's worked flawlessly the probably 50+ times I've done it thus far. 

> Does it turn correctly when you do it form Eco -> Standard -> Ultimate manually ?
Yeah, and it also worked when I go straight from eco, this issue has only happened once for me. 

> Can you check if this build behaves differently ?
I'll use this build from now on. Because this issue is so rare, I'll give it a good while and see. If the issue doesn't happen again for, say, a month with the new version, we should be able to call it a success. Does that sound reasonable?

**Comment by seerge** [comment]
@lgarlati ah, so it was working correctly all the time, but this happened only once ?

Then extra delay will make it bulletproof. 

I have also added an extra check for an ECO flag (to be off) prior to running Ultimate command

Thanks
