### ISSUE TITLE
Strix G16 2023 does not go into sleep when lid is closed after installing G-Helper

### ISSUE THREAD

**Issue by LatifSC** [seerge/g-helper#3172]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I can't get my laptop into sleep when I close the lid. Light bar never goes off. Activity light stays on and fans keep spinning. My power plans are the same.

### How to reproduce the bug?

Close lid

### Logs

[log.txt](https://github.com/user-attachments/files/17135065/log.txt)

### Device and Model

Asus ROG Strix G16 2023 G614JI

### Armoury Crate

Uninstalled

### Asus Services

8

### Version

0.191.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@LatifSC hello, 

Sleep is a windows functionality, G-Helper doesn't handle it :) and windows is notoriously known for it's unpredictable sleep as well.

Check if lid close action is set to sleep
![Screenshot 2024-09-25 185639](https://github.com/user-attachments/assets/acf9a9cf-df2a-43cc-95a5-52e34e3a2d95)

It could be that windows has decided to run some tasks before going to sleep (like updates or so), so it may sometimes take more time to calm down. 

Also you can[ run sleep study ](https://learn.microsoft.com/en-us/windows-hardware/design/device-experiences/modern-standby-sleepstudy)to check what is preventing windows from going to sleep

**Comment by LatifSC** [comment]
Hello. My lid action is the same as yours. I've checked the updates after you mentioned it and indeed I had some updates. But I have always been using my network as metered network to prevent Windows from downloading things automatically. And It sure stops downloads. After I suspended updates it is going into sleep again. Thank you!

But I'm wondering, why this happens when people switch to G-Helper or uninstall AC/MyASUS? Is It firmware releated? Does Asus forcefully put the device into sleep?

I also ran sleep study. I guess this is update releated:

![resim](https://github.com/user-attachments/assets/42d729ce-488d-4def-85e5-45aa5ca86a01)

![resim](https://github.com/user-attachments/assets/0bdbb27b-459f-47a9-ba9f-06fe2e0e6877)

**Comment by seerge** [comment]
@LatifSC i don't think it's related to G-Helper :) lots of people from memory actually mentioned that laptop sleeps better w/o lots of extra AC services running.

Did you set any sleep-related settings in power plan / control panel when you had AC ?  As in AC you use it's own power plans. And when you run G-Helper it would switch to default windows Balanced plan, so you will (probably) need to set any custom sleep-related settings again. 

But from my experience laptop sleeps just fine w/o any tweaks. I just set it to auto-hibernate 30 minutes after sleep.
