### ISSUE TITLE
keyboard lighting problems

### ISSUE THREAD

**Issue by Pg-kewl** [seerge/g-helper#3173]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

the day before yesterday i got a notification(pop up) that there is an update available for g helper. i went installed it and deleted that previous version. but after i installed this version the keyboard lighting has been flickkering and stuff. this only happens in modes like heatmap or ambient. if you see carefully you can see the flickering happening. i also cant use these lighting modes as provided in the screenshot.
![image](https://github.com/user-attachments/assets/ce9559b8-bfec-40ed-9ec8-609291a5257b)

https://github.com/user-attachments/assets/72f82e0c-61ee-4eb7-9549-f021dc1cd750

https://github.com/user-attachments/assets/73a1ecea-5348-4822-a7fd-779f435113f2

### How to reproduce the bug?

change keyboard lighting modes to one of those provided

### Logs

[log.txt](https://github.com/user-attachments/files/17142317/log.txt)

### Device and Model

asus rog stric g16 G614JV-AS74

### Armoury Crate

Uninstalled

### Asus Services

NONE

### Version

0.191.0

### OS

windows 11

**Comment by seerge** [comment]
@Pg-kewl P.S. Your device (with exact same model name "G614JV") exists in per-key RGB and 4-zone RGB variants. 

Does going to `Extra`, unchecking `Per-key RGB` option and then restarting app change something ?

**Comment by Pg-kewl** [comment]
@seerge thank you so much the per key rgb was the issue here.
