### ISSUE TITLE
Fan speed dropping in turbo mode

### ISSUE THREAD

**Issue by brian2lee** [seerge/g-helper#3179]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Fan speed dropping (5000 rpm) after running turbo mode for a while despite overheating  (95C), causing severe lagging and frame rate dropping. Clicking on turbo again will tune up the speed for a while and drop back down eventually, as if it auto-switches to silence mode occasionally.

### How to reproduce the bug?

Installed ghelper though this [build](https://github.com/seerge/g-helper/issues/3146#issuecomment-2374494206), problem occur after running turbo for a while.

### Logs

[log.txt](https://github.com/user-attachments/files/17157896/log.txt)

### Device and Model

ROG Zephyrus M16 GU603HM

### Additional information.

Had my ArmouryCrate Control Interface Support disabled in bios, not sure if it affects fan control but enable it causes lag even in silence mode.
Kinda irrelevant, but my ghelper has also another [issue ](https://github.com/seerge/g-helper/issues/3146)going on, putting it here just in case it has some connection to this one.

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.193.0

### OS

Windows 10 22h2

**Comment by seerge** [comment]
@brian2lee hello, as I have already answered you G-Helper is not controlling fans.

> [How does G-helper control my fan speeds?](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)
> It doesn't and can't control your fans. Firmware / BIOS controls them in real-time. Armoury also doesn't control fans in real time anyhow.

> What G-helper can do - is (optionally) set a custom fan profile to the current performance mode via the same endpoint Armoury uses in Manual mode.

> How it will be interpreted - is still up to the firmware. If you don't like how firmware controls fans, you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)

Next to that since you run all asus services -  stop them from `Extra` settings to make sure they don't interfere
```
2024/9/26 上午 12:15:03: Optimization service is running
```
