### ISSUE TITLE
Function keys don't work until ROG key is pressed

### ISSUE THREAD

**Issue by CodingGenius0001** [seerge/g-helper#3181]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The GHelper app does not seem to be registering my function key presses until and unless I manually open the app or press the ROG key to call the app into the foreground **even though I have it running in the background!!!**

### How to reproduce the bug?

Press any function key without the GHelper app open

```
This issue is not easily reproducible and the issue occurs at random times 
``` 

### Logs

[log.txt](https://github.com/user-attachments/files/17167049/log.txt)

### Device and Model

Asus Zephyrus G14 2024 GA403UI

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.191.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@CodingGenius0001 hello, 

What exactly am I supposed to check here ? When keyboard notifies app about keypresses - I see key presses in the log, all of them are processed. 

There is no difference if main app window is visible or not, as it's not the window that processes hotkeys.

If keyboard by itself is malfunctioning (on a hardware or firmware level) and not registering some hotkeys - app simply doesn't know about key press. Try to do a [hard reset, it may help.](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset)

**Comment by CodingGenius0001** [comment]
I don't believe it is a hardware issue as this laptop is relatively new. I will hard reset the laptop. I will send video evidence soon regarding the issue if it occurs again. This issue keeps occuring so many times. I believe that GHelper is registering the key presses but may not be communicating well from the firmware side of things. Will check again and let you know.

**Comment by seerge** [comment]
@CodingGenius0001
- hardware (or firmware) issues can happen to any device, even new :)
- I absolutely believe that it's happening to you, but my point is that if it happens due to firmware hiccups at random - it may be difficult to tackle
- App just connects to keyboard by USB and listens for notifications. It's same approach for all devices.

1. Let me know if hard reset fixes that
2. And if not - try to turn ON all asus services (then they will handle hotkey notifications instead, and pass them to G-Helper), to see if changes something

**Comment by seerge** [comment]
@CodingGenius0001 on a side note, do you have any USB devices connected to your laptop or USB hub even ?

**Comment by CodingGenius0001** [comment]
I use a Logitech M331 which has a wireless dongle

**Comment by seerge** [comment]
@CodingGenius0001 ok,

I have one small idea to test btw, check if this build behaves anyhow different
[GHelper.zip](https://github.com/user-attachments/files/17168606/GHelper.zip)

**Comment by CodingGenius0001** [comment]
Alright, will test this build soon. 

Also one more thing, when I wake the computer from sleep or right after starting the computer up from restart or hibernate or shutdown, GHelper does not launch on the lock screen so none of the function keys work there as well. This makes it mildly inconvenient for me since I am unable to use the sleep button fn key shortcut on the keyboard while  on the lock screen. Is it possible to implement a way where GHelper launches before the user unlocks or signs into Windows?

**Comment by seerge** [comment]
@CodingGenius0001 no, that's not possible unfortunately cause G-Helper is not a service :)

Btw, neglect previous build, try this one instead
[GHelper.zip](https://github.com/user-attachments/files/17168747/GHelper.zip)

**Comment by CodingGenius0001** [comment]
[log.txt](https://github.com/user-attachments/files/17174941/log.txt)

**Comment by seerge** [comment]
@CodingGenius0001 ok, but does this build change anything ? (i also see that you have reverted back to 0.191 afterwards by some reason?)

**Comment by CodingGenius0001** [comment]
I think GHelper version 0.191.0 is automatically being loaded up on system startup instead of the build you sent me. Do I need to delete version 0.191 to make sure your build is the only build that auto starts?

**Comment by seerge** [comment]
@CodingGenius0001 you need to replace old exe with a new build. 

Or use a new build from other location, but then you need to uncheck / check `Run on startup` again to reschedule task pointing to a new location,

Do hotkeys work all the time for you in a new build ?

**Comment by CodingGenius0001** [comment]
No, the issue still persists

**Comment by seerge** [comment]
@CodingGenius0001 do you know approximate time when it happens to you ?

Try this build instead, I have added (more) verbose logging here.

[GHelper.zip](https://github.com/user-attachments/files/17185949/GHelper.zip)

**Comment by CodingGenius0001** [comment]
Will try this build and post a log soon. @seerge , I have hard resetted the laptop

**Comment by CodingGenius0001** [comment]
@seerge This issue has occurred again. I have attached both the log and the video showing the problem below:
Log: [log.txt](https://github.com/user-attachments/files/17257175/log.txt)
Video: https://github.com/user-attachments/assets/7af74a82-7f6d-472e-a8c6-a06aeda92f20

**Comment by seerge** [comment]
@CodingGenius0001 hello,

On your video you don't press FN+F7/F8 - you just press F7 or F8 without FN key (but with `FN-Lock` enabled). Is that correct ? 

Is it only F7/F8 that don't work ? or also FN+F7/F8 ?

**Comment by CodingGenius0001** [comment]
Yes, FN lock is enabled while I was pressing F7 and F8. Pressing Fn + F7 or Fn + F8 also does not do anything

**Comment by seerge** [comment]
@CodingGenius0001 
- is it only brightness that doesn’t work for you, or also other functions?
- does new hotkey entries appear in the log when you press them (but they don’t work for you)?

**Comment by CodingGenius0001** [comment]
@seerge 

All function keys don't work. I have tested only brightness level in the video. I believe Windows is not able to interpret GHelper's UP/DOWN command.

**Comment by seerge** [comment]
@CodingGenius0001 try to start asus services via `Extra` then they will handle all hotkeys. Does it solve your problem ?

**Comment by seerge** [comment]
P.S. I see in a log that in the time you mentioned you have pressed `F4` and toggled Aura to the next modes, then `F5` and it switched mode to next one - `Silent` just fine
```
04-10-2024 4:21:09 PM: F4 None
04-10-2024 4:21:09 PM: AuraMode: HEATMAP
04-10-2024 4:21:09 PM: F4 None
04-10-2024 4:21:09 PM: AuraMode: GPUMODE
04-10-2024 4:21:09 PM: USB 19B6: 5D-B3-00-00-FF-FF-00-EB-00-00-FF-FF-00-00-00-00-00
04-10-2024 4:21:09 PM: USB 19B6: 5D-B4
04-10-2024 4:21:09 PM: USB 19B6: 5D-B5-00-00-00
04-10-2024 4:21:10 PM: F4 None
04-10-2024 4:21:10 PM: AuraMode: AMBIENT
04-10-2024 4:21:11 PM: F4 None
04-10-2024 4:21:11 PM: AuraMode: AuraStatic
04-10-2024 4:21:11 PM: USB 19B6: 5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
04-10-2024 4:21:11 PM: USB 19B6: 5D-B5-00-00-00
04-10-2024 4:21:11 PM: USB 19B6: 5D-B4
````


```
04-10-2024 4:22:07 PM: F5 None
04-10-2024 4:22:07 PM: Mode = 2 : OK
04-10-2024 4:22:07 PM: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
04-10-2024 4:22:07 PM: FanCPU = 1E-3C-41-42-47-4B-4C-62-00-03-0C-0C-16-22-22-29 : OK
04-10-2024 4:22:07 PM: FanGPU = 1E-3C-41-42-47-4B-4C-62-00-08-11-11-1D-26-26-2D : OK
04-10-2024 4:22:07 PM: FanMid = 1E-3C-41-42-47-4B-4C-62-00-03-0C-0C-16-22-22-29 : OK
```

**Comment by CodingGenius0001** [comment]
@seerge Yes, I was clicking all the function keys on the laptop to see if any of them would perform any action. It seems that the actions are being registered by GHelper but not actually being registered by Windows

**Comment by seerge** [comment]
@CodingGenius0001 according to the hotkeys are processed just fine. `None` is stands of absence of modifier keys (like Shift), it's all good.

Does running Asus services help you as I was asking ?

**Comment by CodingGenius0001** [comment]
Asus services crashes GHelper

**Comment by seerge** [comment]
@CodingGenius0001 how exactly it happens? Can you upload a crash details from `Event Viewer` -> Windows Logs -> Application mentioning GHelper.exe?

**Comment by CodingGenius0001** [comment]
Here is the video evidence of GHelper crashing. I will upload the crash logs soon.
https://github.com/user-attachments/assets/6683cf25-402b-4b0e-bc9f-012740d8bccb

**Comment by seerge** [comment]
@CodingGenius0001 on this video G-Helper **is not crashing**. It shows and hides windows cause M4 emits it's code twice most likely cause you started asus services not from `Extra` section but manually? If so - you need to restart app.

**Comment by CodingGenius0001** [comment]
@seerge Ah I see. Thanks for the clarification. I have started Asus services from the ```Extra``` section itself. I am unaware of any other method in which I could enable Asus services other than restarting the laptop again (which I have not done).

**Comment by seerge** [comment]
@CodingGenius0001 ok. Let me know if it resolves your problem. As when Asus Optimization service is running - it handles hotkeys, not G-Helper (you can quit app and backlight / brightness controls will still work).

**Comment by CodingGenius0001** [comment]
The issue still persists :(

[log.txt](https://github.com/user-attachments/files/17354863/log.txt)

**Comment by seerge** [comment]
@CodingGenius0001 hello, thanks for checking.

If hotkeys stop working even with Asus Optimization service running - it means most likely there is some underlying hardware or firmware issue.

As when Asus services are running they handle hotkeys. I.e. you can quit G-Helper completely and `FN+F2 / F3` will still control backlight level, or `FN+F7/F8` - brightness.

So unfortunately there is nothing that can be done here.

Thanks.
