### ISSUE TITLE
PROART STUDIOBOOK 16

### ISSUE THREAD

**Issue by B0YTR** [seerge/g-helper#3182]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I cannot disable the dGPU on this laptop. It has a constant consumption of ~15w.

### Describe the solution you'd like

Creating an eco mode so I can use the laptop longer than 4-5 hours..

### Device and Model

Asus ProArt StudioBook 16 (h7604ji)

### Additional information.

I have seen few post about the fact that it is not possible to disable it.
Is there really no solution to implement this feature ?

![Screenshot 2024-09-27 164734](https://github.com/user-attachments/assets/19de8c63-c492-49b7-af36-02907f39ad12)
![Screenshot 2024-09-27 165238](https://github.com/user-attachments/assets/111c1f0f-37b9-459a-891e-9a5ffc3c75bd)

**Comment by seerge** [comment]
@B0YTR hello,

I'm afraid that's not possible. If you don't see `Eco` mode button, it means that your device doesn't support that on hardware / firmware level as it's communicated with G-Helper by BIOS / firmware.

Option to disable dGPU exists only on ROG / TUF devices from 2021+ and on new ProArt P16 and X13 from 2024 only.

The best thing you can do is to set windows power plan `Switchable Dynamic Graphics` to Max Power savings on battery and set Nvidia Optimus ON

![image](https://github.com/user-attachments/assets/4f820e55-67e5-45f2-860f-dd758d3b176f)

**Comment by B0YTR** [comment]
I do not have this settings....

Is it not possible to done something via the BIOS ?

I do not need the graphic card to work for few weeks.

**Comment by seerge** [comment]
@B0YTR if you don't see those options - it's not possible then. 
You can set power plan adjustments to minimize GPU usage as I mentioned above.
