### ISSUE TITLE
Battery Charge Limit Doesn't Work

### ISSUE THREAD

**Issue by ChromeFalcon** [seerge/g-helper#3183]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Laptop: ROG Strix Scar 18, BIOS version 317.
The battery charge limit doesn't work. I set it to 65%, but the laptop keeps charging at 92%.

### How to reproduce the bug?

1. I downloaded MyASUS back to troubleshoot a GPU issue.
2. I uninstalled MyASUS.
3. I restarted the laptop.
4. The battery charge limit didn't work.

### Logs

[log.txt](https://github.com/user-attachments/files/17171536/log.txt)

### Device and Model

ROG Strix Scar 18 G834JZR

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.191.0

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@ChromeFalcon hello, 

Some models don't support anything but 80% charge limit, so you need to set that. How do you know that it keeps charging past 92%, does percentage keep increasing ?

I also see that you were running asus services - they can override limit. You either need to also set charge limit in MyASUS as well (so asus services apply same one) or stop them. As it's mentioned in [FAQ](https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working)

Does charge limit work if you set it in myasus?

**Comment by ChromeFalcon** [comment]
@seerge Hello,

I had set the charge limit to 60% before, and the battery charge limit had worked properly. The charge percentage doesn't exceed 92%; it only remains at 92% now. 

Yesterday, I uninstalled MyASUS and stopped the ASUS services in GHelper. Then, I restarted the laptop, but it still showed "charging 92%." 

I reinstalled MyASUS and set the charge limit to 80% today. The GHelper also showed ASUS services running, but it still showed "charging 92%."

**Comment by ChromeFalcon** [comment]
Sorry, accidentally clicked on the

**Comment by seerge** [comment]
@ChromeFalcon hello,

If it's already charged to 92% but percentage doesn't increase - **it's not charging**. So limit is working just fine, same as it worked before.

Windows may show a lightning icon (or whatever you interpret as "charting") but it means nothing :)

**Comment by ChromeFalcon** [comment]
@seerge hello,

Ok, but why could I set the battery limit to 60%, and the battery percentage was also 60% previously? And now I can't do that again. Is it because I updated the BIOS version?

**Comment by seerge** [comment]
@ChromeFalcon i don't think it's related to BIOS version. Your laptop probably just managed to charge above limit somehow (may be during tests with myasus or so) and obviously it will not magically drop it's charge back to 80% or to 60%, as this is not how limit works. You need to unplug and discharge it :)

Keep in mind that laptop resets all settings each reboot , and starts charging until windows starts and either asus services or g-helper sets limit again.

As far as I understand it's indeed not charging after limit is applied, so everything is working. Therefore closing as resolved
