### ISSUE TITLE
Battery Charge Limit Doesn't Work

### ISSUE THREAD

**Issue by ChromeFalcon** [seerge/g-helper#3184]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Laptop: ROG Strix Scar 18, BIOS version 317.
The battery charge limit doesn't work. I set it to 65%, but the laptop keeps charging at 92%.

### How to reproduce the bug?

I downloaded MyASUS back to troubleshoot a GPU issue.
I uninstalled MyASUS.
I restarted the laptop.
The battery charge limit didn't work.

### Logs

[log.txt](https://github.com/user-attachments/files/17175689/log.txt)

### Device and Model

ROG Strix Scar 18 G834JZR

### Additional information.

Sorry, I accidentally closed the report.

I had set the charge limit to 60% before, and the battery charge limit had worked properly. The charge percentage doesn't exceed 92%; it remains at 92% now.

Yesterday, I uninstalled MyASUS and stopped the ASUS services in GHelper. Then, I restarted the laptop, but it still showed "charging 92%."

I reinstalled MyASUS and set the charge limit to 80% today. The GHelper also showed ASUS services running, but it still showed "charging 92%." 

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.191.0

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@ChromeFalcon there is no need to create a dublicate issues, you could just reopen [original one](https://github.com/seerge/g-helper/issues/3183) (where I have responded to you)
