### ISSUE TITLE
Support for other Asus external Devices such as Keyboards/mouse pads

### ISSUE THREAD

**Issue by nabud** [seerge/g-helper#3185]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

ROG Claymore II keyboard is not shown under peripherals 
ROG Balteus qi is not shown under peripherals 
ROG strix Arion external NVME SSD Case not shown under peripherals 

### Describe the solution you'd like

Please add support for being able to control ROG Claymore II keyboard lights and fn keys 
Please add ROG Balteus qi light controls support
Please add support for being able to control ROG strix Arion external NVME SSD Case light

### Describe alternatives you've considered

The only alternative is using Asus Armory crate 

### Device and Model

ROG Strix g614JI

### Additional information.

of all 3 devices requested please prioritize the ROG Claymore II keyboard. I understand you are very busy and if you can only do 1 please do the keyboard. thank you very much for your consideration and hard work.

**Comment by seerge** [comment]
@nabud hello, if you need support for a peripheral you need to follow a [special template for that ](https://github.com/seerge/g-helper/issues/new?assignees=&labels=&projects=&template=peripherals_request.yml). So fill it and provide info asked there.

But since I don't have a single device from your list, chances that I will add that are minimal.
And [your SSD already has a separate topic created](https://github.com/seerge/g-helper/issues/3025)

Thanks.

**Comment by seerge** [comment]
I'm closing this as it's incomplete (and a wrong template)

**Comment by seerge** [comment]
@nabud hello, 

If you are interested you can test external keyboards support in a new build https://github.com/seerge/g-helper/discussions/5710 

Thanks!

**Comment by seerge** [comment]
Live in the latest release https://github.com/seerge/g-helper/releases
