### ISSUE TITLE
No icon/notification when mic mute button is pressed

### ISSUE THREAD

**Issue by Quandrin** [seerge/g-helper#3186]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I press the mic mute button above the keyboard, it mutes the mic (I tested it in sound recorder), but there is no visual sign/icon to notify that the mic is muted/unmuted.

### How to reproduce the bug?

1. Press the mic mute button above the keyboard.

### Logs

[log.txt](https://github.com/user-attachments/files/17178348/log.txt)

### Device and Model

ASUS TUF DASH FX516PM-HN015W

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.191.0

### OS

Windows 11 Home 23H2

**Comment by seerge** [comment]
@Quandrin hello, you need to stop asus services from `Extra` if you want G-Helper to handle hotkeys instead of them as clearly [mentioned in FAQ.](https://github.com/seerge/g-helper/wiki/FAQ#how-do-i-set-mute-microphone-to-m3)
