### ISSUE TITLE
The fan does not work after waking up from sleep mode

### ISSUE THREAD

**Issue by a68799785** [seerge/g-helper#3189]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The fan does not work after waking up from sleep mode

### How to reproduce the bug?

The fan does not work after waking up from sleep mode

### Logs

The fan does not work after waking up from sleep mode

### Device and Model

ASUS TUF Gaming A16 FA607PI

### Additional information.

<img width="311" alt="微信图片_20240930100554" src="https://github.com/user-attachments/assets/0a2dbe54-b808-47d6-a31b-b1c4e535889e">

### Armoury Crate

Installed

### Asus Services

0

### Version

0.194

### OS

windows11 23H2

**Comment by seerge** [comment]
> I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.
