### ISSUE TITLE
Battery Limit not staying at set limit 

### ISSUE THREAD

**Issue by Inaiso** [seerge/g-helper#319]
My problem is that the battery limit does not stay at the percentage I set it in Ghelper when the laptop is plugged in. 
In Ghelper I have set the limit to 60% as you can see in the log , but in windows it does not stay at 60%. 
It will stay at that limit when I have ghelper in eco mode and silent, but the moment I switch to ultimate and turbo mode the battery starts to charge up and it will stay around 76~77%.  Please see attached pictures.  I not sure what the problem is. 

I am on windows 11
No Armory Crate 
No my Asus
Laptop model : ROG Zephyrus G14 GA402RJ_GA402RJ

[log.txt](https://github.com/seerge/g-helper/files/11402411/log.txt)
![60](https://user-images.githubusercontent.com/132625303/236353808-c1b4655c-63ce-4191-8df5-634c4f1b5fc5.png)
![70](https://user-images.githubusercontent.com/132625303/236353809-c97c019a-d6b7-4e33-89ce-65c9f479cdc3.png)
![battery status](https://user-images.githubusercontent.com/132625303/236354972-941eff08-1f2d-4514-94ea-7d819a08bda9.png)
![battery hwinfo](https://user-images.githubusercontent.com/132625303/236355749-5f63a9f8-1733-4ffa-89ba-5651dbaf2579.png)

**Comment by seerge** [comment]
@Inaiso hello. From log i see that on every launch app runs a limit command and gets 1(OK) from bios, so it accepts it.

```5/4/2023 3:04:05 PM: BatteryLimit = 60 : OK```

It's not much i can do next to it :) It can be either some other leftover from asus resettting limit, or just bios acting and not following limits.

You can also set same thing without any app by hand in powershell (as admin), as this is the same thing as g-helper and myasus do 

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00120057, 60)
```

**Comment by Inaiso** [comment]
Thank you for all your work and information. 
Do you know how to make sure I have no leftover Asus stuff, I have uninstalled myAsus , deleted most of the folders except optimization and deleted most of the asus services with command prompt. 
I think it is left over myAsus stuff thats messing with it as well, but I have no way to be sure unless I reinstall OS and everything.

**Comment by seerge** [comment]
@Inaiso i know only that it's myasus app :) mb try to install / uninstall it again ? 

Anyway - command to set limit is simple as wood, and there is no bugs related to it in the app. 

I don't know what exactly causes your laptop to start charging , mb it's even bugged battery controller or something like that.

**Comment by Inaiso** [comment]
Again thanks for all your work, and thanks for the replies.

**Comment by Inaiso** [comment]
So after a little investigation, I found that it was leftover asus services that was messing with limit. For some reason the asus services that the debloat script disabled did not disable and was still running. So I properly one by one disabled them all and when into the asus folder and deleted all the possible files that could start these services. Just though you cared to know why this happened. Again thanks for all you work and help.

**Comment by seerge** [comment]
@Inaiso you need to run debloat as admin. Bug i'm glad that it was asus services not the bugged hardware :)

**Comment by musculobog** [comment]
PS C:\Windows\system32> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00120057, 60)
Exception calling "DEVS" : "Generic failure "
At line:1 char:1
+ (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x001 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WMIMethodException

Any idea what's the issue?

**Comment by Luqi21** [comment]
> @Inaiso you need to run debloat as admin. Bug i'm glad that it was asus services not the bugged hardware :)

what is the debloat tool to use?

**Comment by seerge** [comment]
@Luqi21 now it’s integrated into the app. It’s just A Stop services button under Extra
