### ISSUE TITLE
Fan speed setting

### ISSUE THREAD

**Issue by Qli52** [seerge/g-helper#3190]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Having the checkbox "apply custom fan speed curve line" selected actually won't use the custom fan speed setting.
Deselecting it now makes the fan speed controlled by custom line

### How to reproduce the bug?

Check the "应用自定义风扇曲线" and find out it won't work until you uncheck it

### Logs

no

### Device and Model

Asus Flow x13

### Armoury Crate

Uninstalled

### Version

0.191.0

**Comment by seerge** [comment]
> I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.
