### ISSUE TITLE
GPU Core clock limit slider automatically goes to default.

### ISSUE THREAD

**Issue by agent2404** [seerge/g-helper#3191]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Core clock limit slider automatically goes to default. Slider works correctly when idle. As soon as any application starts(gpu dependent), it snaps to the default position.

### How to reproduce the bug?

1.Open any application that uses the dedicated gpu.
2.In the G_helper app under the Fans + power menu, when I try to change the core clock limit, the slider snaps back to the default position.

### Logs

[log.txt](https://github.com/user-attachments/files/17185376/log.txt)

### Device and Model

Asus Zephyrus G15 GA503RM

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.191.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@agent2404 hello, thanks for posting.

When you read current or change clock limit G-Helper calls nvidia utility `nvidia-smi` to set it in powershell

And from the log I see that windows says powershell can't be found

```
22-09-2024 00:06:30: GET CLOCK LIMIT: 0
22-09-2024 00:06:30: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'powershell' with working directory 'C:\Users\MANAS\GHelper'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GHelper.Helpers.ProcessHelper.RunCMD(String name, String args) in D:\a\g-helper\g-helper\app\Helpers\ProcessHelper.cs:line 134
   at GHelper.Gpu.NVidia.NvidiaGpuControl.RunPowershellCommand(String script) in D:\a\g-helper\g-helper\app\Gpu\NVidia\NvidiaGpuControl.cs:line 118
```
Can you manually try to run `nvidia-smi` in powershell and see what it says?

Did you run any strange "cleanup" apps to remove unnecessary components from windows before ?

If you don't even have powershell at all (which should be installed by default) - try to install it https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4

**Comment by seerge** [comment]
@agent2404 ok, but log shows same error
```
30-09-2024 13:04:44: GET CLOCK LIMIT: 0
30-09-2024 13:04:44: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'powershell' with working directory 'C:\WINDOWS\system32'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GHelper.Helpers.ProcessHelper.RunCMD(String name, String args) in D:\a\g-helper\g-helper\app\Helpers\ProcessHelper.cs:line 134
   at GHelper.Gpu.NVidia.NvidiaGpuControl.RunPowershellCommand(String script) in D:\a\g-helper\g-helper\app\Gpu\NVidia\NvidiaGpuControl.cs:line 118
```

And it fails not by launching nvidia-smi itself, but by just trying to run powershell first .

Are you able to run powershell normally in windows (don't mix it with command promt, it's a different thing). Can you try to "reinstlal" it using installer from microsoft site https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4 ?

**Comment by agent2404** [comment]
@seerge I think I have fixed the issue. Powershell was installed and running normally. I just added a PATH to it and it fixed the issue. 
Can you check if everything is running properly. Thanks for your help!
[log.txt](https://github.com/user-attachments/files/17191710/log.txt)

**Comment by seerge** [comment]
@agent2404 ok, great. Then I assume it's resolved. Thanks.
