### ISSUE TITLE
ROG Ally controller gets re-enabled after sleep

### ISSUE THREAD

**Issue by dfunkt** [seerge/g-helper#3192]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

ROG Ally controller keeps getting re-enabled after sleep, even though I have ticked the "Disable Controller" box in the G-Helper settings.
I always have to untick and then retick the setting after sleep for it to work

### How to reproduce the bug?

1. Tick "Disable Controller" in G-Helper controller settings
2. Let the device go to sleep
3. Wake up the device
4. Check Device Manager and you see the controller as available

### Logs

[log.txt](https://github.com/user-attachments/files/17187773/log.txt)

### Device and Model

ROG Ally RC71L

### Armoury Crate

Never installed

### Version

0.191.0

**Comment by seerge** [comment]
@dfunkt hello, I think firmware resets status every time device wakes up.

Try this build, it should re-apply controller status every time you reboot or wake up from sleep.
[GHelper.zip](https://github.com/user-attachments/files/17188071/GHelper.zip)

**Comment by dfunkt** [comment]
I can confirm that the build linked above fixes the issue.

**Comment by seerge** [comment]
@dfunkt great! Thanks for spotting.

**Comment by dfunkt** [comment]
Nevermind, don't know why it looked like it was working the 1st time around. It seems to apply fine on reboot, but the controller still gets enabled upon waking up from sleep.
[log.txt](https://github.com/user-attachments/files/17189589/log.txt)

**Comment by seerge** [comment]
@dfunkt but app sends controller OFF command on each wake up

```
9/30/2024 3:16:39 PM: Eco flag : 1
9/30/2024 3:16:39 PM: Mux flag : -65536
9/30/2024 3:16:39 PM: Internal screen off
9/30/2024 3:16:39 PM: Input available: \\?\hid#vid_0b05&pid_1abe&mi_02&col01#8&d1252f4&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} 1ABE 64
9/30/2024 3:16:39 PM: Init 1ABE|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
9/30/2024 3:16:39 PM: Init 1ABE: 5D-B9
9/30/2024 3:16:39 PM: Init 1ABE: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
9/30/2024 3:16:39 PM: Init 1ABE: 5D-05-20-31-00-1A
9/30/2024 3:16:39 PM: Status 1ABE|64: 5A-D1-0B-01-02 <---- TURNS IT OFF
9/30/2024 3:16:39 PM: FPS Limit: 60
9/30/2024 3:16:39 PM: Controller 1ABE|64: 5A-D1-01-01-03
````

I have moved this command to be the last one from whole init (in case something else makes controller to enable agian)

Try this build
[GHelper.zip](https://github.com/user-attachments/files/17189697/GHelper.zip)

**Comment by dfunkt** [comment]
No difference, it still gets enabled.
[log.txt](https://github.com/user-attachments/files/17189799/log.txt)

**Comment by seerge** [comment]
@dfunkt that's strange cause it's literally last command in a chain

```
9/30/2024 3:36:51 PM: FPS Limit: 60
9/30/2024 3:36:51 PM: Init 1ABE|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
9/30/2024 3:36:51 PM: Init 1ABE: 5D-B9
9/30/2024 3:36:51 PM: Init 1ABE: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
9/30/2024 3:36:51 PM: Mode = 0 : OK
9/30/2024 3:36:51 PM: Init 1ABE: 5D-05-20-31-00-1A
9/30/2024 3:36:51 PM: Controller 1ABE|64: 5A-D1-01-01-03
9/30/2024 3:36:51 PM: Status 1ABE|64: 5A-D1-0B-01-02 <--- DISABLES CONTROLLER
9/30/2024 3:36:52 PM: Auto 1ABE: 5D-BA-C5-C4-01 <--- BACKLIGHT
9/30/2024 3:36:52 PM: AuraMode: AuraStatic
9/30/2024 3:36:52 PM: USB 1ABE: 5D-B3-00-00-19-19-19-EB-00-00-19-19-19-00-00-00-00
9/30/2024 3:36:52 PM: USB 1ABE: 5D-B5-00-00-00
9/30/2024 3:36:52 PM: USB 1ABE: 5D-B4
```

Can you do manual check - disable it with a checkbox, and then adjust backlight brightness or backlight mode to see if that enables it by any chance?

Also do you have asus services or Armoury services running in background ? cause if so - **they can interfere**

**Comment by dfunkt** [comment]
Just realized something, this only happens while device is plugged in for charging. If I send the device to sleep while on battery the controller gets disabled. Probably this was the reason I didn't notice it at first with the previous build.

Now, regarding your questions (keep in mind this is a fresh Windows install from a few hours ago)
1. No difference, controller stays disabled.
2. I have these, they seem to have been installed alongside Windows:
![image](https://github.com/user-attachments/assets/f918cb23-4c19-477b-8c89-0881e0721fb2)

**Comment by seerge** [comment]
@dfunkt yeah, but then it's strange and it looks like something else is enabling controller 

As whole enable / disable (what checkbox does) is literally one command, where `[02]` is disabled, and `[01]` is enabled.
```
Status 1ABE|64: 5A-D1-0B-01-[02]
```

Can you try to stop all asus services via `Extra` settings, then double check if they are all OFF via windows Services app and then test again ?

**Comment by dfunkt** [comment]
No difference
![image](https://github.com/user-attachments/assets/07ab014b-532d-4e99-a048-87319fdc16d8)
I did however notice something. If the controller gets enabled after waking up from sleep, I will stay that way unless I specifically go and untick/retick the "Disable controller" checkbox in the settings. Just quitting the app and then starting it again keeps the controller enabled.

**Comment by dfunkt** [comment]
Same issue
![image](https://github.com/user-attachments/assets/36fdb937-275d-4525-a92d-fd3c394a332b)

How about maybe setting it to the enabled and then disabling it when using the "Disable Controller" option?

**Comment by dfunkt** [comment]
^^ Finally, this version appears to work well 😄 
[log.txt](https://github.com/user-attachments/files/17193252/log.txt)

**Comment by seerge** [comment]
@dfunkt ok, this is some crazy shenanigans from asus honestly. Can you check if this build **still** works correctly ?
[GHelper.zip](https://github.com/user-attachments/files/17193541/GHelper.zip)

**Comment by dfunkt** [comment]
Yes, the build above also works fine.
[log.txt](https://github.com/user-attachments/files/17193748/log.txt)

**Comment by seerge** [comment]
@dfunkt ok, good. I have lowered delay to 500ms. But still kept it just in case it matters.
