### ISSUE TITLE
Equivalent of Fan Profile on ASUS Zenbook S 16 UM5606

### ISSUE THREAD

**Issue by ViRb3** [seerge/g-helper#3194]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The ASUS Zenbook S 16 UM5606 allows you to set Fan Profiles via MyASUS app. The modes are as follows:
- Full-speed mode
- Performance mode
- Standard mode
- Whisper mode

Neither of these profiles hit CPU thermal limit, all of them max out at ~80*C. However, Full-speed mode has ~30% performance boost, so I assume it either increases TDP or core boost.

G-Helper does not seem to expose this particular feature. I do see CPU Boost and BIOS Fan Curves, but I'm not sure how they map to the MyASUS Fan Profiles. Changing the Fan Profile from MyASUS app does not change any of the selected values in G-Helper.

Do you have any ideas? Thanks!

### How to reproduce the bug?

N/A

### Logs

N/A

### Device and Model

ASUS Zenbook S 16 UM5606

### Armoury Crate

Never installed

### Asus Services

6

### Version

0.191

### OS

Windows 11 21H2

**Comment by seerge** [comment]
@ViRb3 hello, you can actually set `Full Speed` mode but you need to add it config first
----
1. Create a new custom mode based on `Turbo` (by pressing + under `Fans+Power`)
2. Quit app
3. Open``%appdata%\GHelper\config.json`` and set following parameter to 3 (it will be 2 there) ``"mode_base_3" : 3, ``
4. Save config, and start app.

**Comment by ViRb3** [comment]
Thanks for the answer! This explains the fan part, but what about the power part? Surely making the fans spin faster doesn't impact CPU performance if in both cases the temperature is at 80*C? At least with other CPUs, thermal throttling starts to happen at around 95*C, which we're way below.

**Comment by seerge** [comment]
@ViRb3 CPU Boost setting - is just one of (many) params in windows power plan. It's **not** part of the firmware (and not changed by MyASUS at all). 

G-Helper doesn't change it by default  and shows current setting (most likely Enabled or Aggressive), unless you manually change it in a dropdown - then it's remembered per each mode and set every time you select that mode.
