### ISSUE TITLE
Mouse System.ArgumentOutOfRangeException: Index was out of range. 

### ISSUE THREAD

**Issue by fejdraus** [seerge/g-helper#3195]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When switching the lighting mode for the mouse from "All" with "Battery State" selected to another mode (where "Battery Status" is not available), I get an error about accessing a non-existent index in the list at line LightingSetting? ls = mouse.LightingSettingForZone(visibleZone); in [g-helper](https://github.com/seerge/g-helper/tree/main)/[app](https://github.com/seerge/g-helper/tree/main/app)/AsusMouseSettings.cs.

I think the issue can be resolved by adding something like:

var selectedMode = 0;
if (index >= 0 && index < lightingModes.Count)
{
    selectedMode = lightingModes[index];
}

### How to reproduce the bug?

Open the mouse settings, select the "All" lighting mode, choose the "Battery State" type, then switch the mode to "Logo"

### Logs

[log.txt](https://github.com/user-attachments/files/17192188/log.txt)

### Device and Model

Asus Rog Gladius III Willess, Asus Rog Strix G15

### Armoury Crate

Uninstalled

### Asus Services

Peripherals

### Version

0.191.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@fejdraus hello, can you post full exception text here ? 

And try this build
[GHelper.zip](https://github.com/user-attachments/files/17193083/GHelper.zip)

**Comment by fejdraus** [comment]
Full stack trace:

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at GHelper.AsusMouseSettings.ComboBoxLightingMode_DropDownClosed(Object sender, EventArgs e) in D:\a\g-helper\g-helper\app\AsusMouseSettings.cs:line 329
   at System.Windows.Forms.ComboBox.OnDropDownClosed(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at GHelper.UI.RComboBox.WndProc(Message& m) in D:\a\g-helper\g-helper\app\UI\RComboBox.cs:line 203
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Comment by fejdraus** [comment]
@seerge I believe the changes you've made should resolve the issue. However, I haven't had the chance to test it yet. Ideally, it would be great if the default mode was applied when a specific mode is unavailable, as switching modes currently might result in an empty window.

**Comment by seerge** [comment]
@fejdraus i'm not sure if this is a good idea, but try this build then
[GHelper.zip](https://github.com/user-attachments/files/17194926/GHelper.zip)

**Comment by fejdraus** [comment]
I have run your changes on my system, and everything works perfectly. Thank you.
I really like your application, and I appreciate that you continue to improve and develop it. Thank you!
