### ISSUE TITLE
Autumatically switch performance mode basing on power supply mode.

### ISSUE THREAD

**Issue by NamelessDev0000** [seerge/g-helper#3196]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Here is a scenario: I'm playing or browsing web with high performance mode then after I take out my laptop,
it changes performance mode in silence.

### Describe the solution you'd like

Add some selection menu in extra part.

### Describe alternatives you've considered

Provide an API. e.g:: http://localhost:2333/mode?=perf

### Device and Model

ASUS TUF Gaming A16 FA607PI

**Comment by NamelessDev0000** [comment]
Also, can we also automatically switch graphic card mode basing on power supply mode?

**Comment by seerge** [comment]
@NamelessDev0000 hello, this is [already the case.](https://github.com/seerge/g-helper?tab=readme-ov-file#gear-automation) 

App remembers last used mode per plugged in / on battery case and automatically sets that.

For GPU - you have `Optimized` mode that disables GPU on battery (`Eco`) and enables when plugged in (`Standard`)

Thanks.

**Comment by NamelessDev0000** [comment]
> @NamelessDev0000 hello, this is [already the case.](https://github.com/seerge/g-helper?tab=readme-ov-file#gear-automation)@NamelessDev0000你好，已经是这样了。
> 
> App remembers last used mode per plugged in / on battery case and automatically sets that.应用程序会根据插入/打开的电池盒记住上一次使用的模式，并自动设置。
> 
> For GPU - you have `Optimized` mode that disables GPU on battery (`Eco`) and enables when plugged in (`Standard`)对于GPU -你有 `Optimized` 模式禁用GPU电池( `Eco` )，并在插入时启用( `Standard` )
> 
> Thanks.

Wow, thanks a lot!!
