### ISSUE TITLE
Cpu Boost won't stay disabled on silent mode after restart

### ISSUE THREAD

**Issue by ritik1290** [seerge/g-helper#3199]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

i had set me cpu boost disabled on silent mode and balance n set efficient enable at turbo, after a restarting my laptop the balance and turbo remains the same at set settings but silent always goes back to default (Aggressive) ghelper app version is 0.191.0 n laptop is FX507VV-I7161G

### How to reproduce the bug?

set the cpu boost on disable for silent n simply restart ull c the boost going back to default aggressive while others remain the same

### Logs

[log.txt](https://github.com/user-attachments/files/17213336/log.txt)

### Device and Model

ASUS TUF Gaming F15 FX507VV-I7161G

### Armoury Crate

Installed

### Asus Services

none

### Version

0.191.0

### OS

WINDOWS 11 23H2

**Comment by seerge** [comment]
@ritik1290 hello,

When you set `Silent` app disables boost as it should
```
01/10/2024 08:51:39: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
01/10/2024 08:51:39: Boost 0 <--- BOOST OFF
01/10/2024 08:51:39: Mode = 2 : OK <--- SILENT MODE
```

I see that you have Armoury Crate running. It will just override settings on laptop restart (and do it later than G-Helper sets them).

You need to uninstall AC using official [AC uninstaller as explained in readme.](https://github.com/seerge/g-helper/wiki/Requirements#recommendations-optional)

Thanks
