### ISSUE TITLE
G-Helper randomly closing after startup

### ISSUE THREAD

**Issue by sentfromthehub** [seerge/g-helper#32]
Hello,

So I have this bug on my G401QC where, on startup, I see G-helper in the taskbar but after all my other startup apps like Discord, Wallpaper Engine etc. load up, it disappears and I have to manually start it up again. Weirdly, all of the options I've set like switching to the iGPU on battery seem to still be there and the laptop screen refresh rate are always saved

Note: I'm running it as admin.

**Comment by seerge** [comment]
You can manually  GHelper (or GSharphelper) task in TaskScheduler and then run app normallly and click "run on startup"

**Comment by sentfromthehub** [comment]
Seems to working fine now. Thanks!

> You can manually remove GHelper (or GSharphelper) task in TaskScheduler and then run app normally and click "run on startup"

**Comment by seerge** [comment]
Great.
