### ISSUE TITLE
Everytime after laptop reboot, screen label shows 165hz+OD if disabled overdrive

### ISSUE THREAD

**Issue by kuonji-arisu** [seerge/g-helper#320]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
Everytime after laptop reboot, screen label shows 165hz+OD if disabled overdrive
But button text is normal, only shows 165hz
and checkbox in more setting is normal too, stay checked, only label text shows overdrive

**Clear scenario to Reproduce**
1. set the disable overdrive checked
2. set screen mode to 165hz, screen label changed to 165hz before reboot
3. reboot and open ghelper, the label changed to 165hz + overdrive

**Expected behavior**
after reboot the label only shows 165hz

**Screenshots or screencasts**
![image](https://user-images.githubusercontent.com/29818319/236365969-2fad55f1-2838-43de-b5b2-c2be2dc79a5e.png)

**Desktop (please complete the following information):**
 - Windows11
 - FX507ZM

**Asus software**
- Armoury crate uninstalled
- MyASUS uninstalled
- no Asus services running in background  expect optimus service

**Comment by Inaiso** [comment]
I have the same problem as well 
I have the 2022 ROG Zephyrus G14 GA402RJ
same when I restart the label shows 120hz + OD even though the overdrive is disabled.

**Comment by seerge** [comment]
@kuonji-arisu can you include a log as i can't reproduce this ?

**Comment by kuonji-arisu** [comment]
@seerge 
2023/5/5 17:50:12: Screen = 165Hz : OK
2023/5/5 17:50:12: ScreenOverdrive = 1 : OK // set overdrive mode on
2023/5/5 17:50:13: Screen = 165Hz : OK 
2023/5/5 17:50:13: ScreenOverdrive = 1 : OK
2023/5/5 17:50:38: Screen = 60Hz : OK // switch the refresh rate once
2023/5/5 17:50:38: ScreenOverdrive = 0 : OK
2023/5/5 17:50:40: Screen = 165Hz : OK
2023/5/5 17:50:40: ScreenOverdrive = 1 : OK
2023/5/5 17:50:59: Screen = 165Hz : OK
2023/5/5 17:50:59: ScreenOverdrive = 0 : OK
2023/5/5 17:51:05: Screen = 165Hz : OK
2023/5/5 17:51:05: ScreenOverdrive = 0 : OK // set overdrive mode off
2023/5/5 17:52:10: ------------ // after reboot
2023/5/5 17:52:10: App launched: ASUS TUF Gaming F15 FX507ZM_FX507ZM
2023/5/5 17:52:10: AutoSetting for Online
2023/5/5 17:52:10: BatteryLimit = 100 : OK
2023/5/5 17:52:10: BatteryLimit = 100 : OK
2023/5/5 17:52:10: PerformanceMode = 1 : OK
2023/5/5 17:52:10: FanCPU = 14-3F-44-48-4C-50-54-62-11-1A-22-29-34-43-51-5A : OK
2023/5/5 17:52:10: FanGPU = 14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F : OK
2023/5/5 17:52:10: Boost 4
2023/5/5 17:52:10: Eco flag : 0
2023/5/5 17:52:10: Mux flag : 0
2023/5/5 17:52:11: PowerLimit A0 = 45 : OK
2023/5/5 17:52:11: PowerLimit A3 = 45 : OK
2023/5/5 17:52:12: Monitor Power On

maybe just a display error?
by the way, my display language is simplified chinese

**Comment by seerge** [comment]
@kuonji-arisu ok, as i understand you had display not in auto, but rather in constant 165HZ, and by default app didn't even try to set any extra settings on reboot (as windows supposed to remember settings). But looks like bios (hello asus 👋 ) just erases all overdrive settings on reboot.

In this build app will set overdrive setting on each launch no matter what :
[GHelper.zip](https://github.com/seerge/g-helper/files/11405291/GHelper.zip)

**Comment by kuonji-arisu** [comment]
> 

Thanks! I tried this build and it fixed the issue
