### ISSUE TITLE
switch touch screen function is abnormal

### ISSUE THREAD

**Issue by C-neon** [seerge/g-helper#3200]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

After setting the fn+v  to "toggle touch screen", the touch screen cannot be turned off

### How to reproduce the bug?

1. Open “more settings” and find fn+v in key bindings
2. Set fn+v to "toggle touch screen"
3. Use fn+v and found that the touch screen could not be turned off. The screen would only show "touch screen on" and ghelper would freeze for a while.

### Logs

[log.txt](https://github.com/user-attachments/files/17213415/log.txt)

### Device and Model

ROG Strix G16 (2023) G614JV

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.191.0

### OS

Windows 11 21H

**Comment by seerge** [comment]
@C-neon hello, 

You have G614JV model, it simply **does not have any touchscreens**. There is nothing to disable :)

Thanks.
