### ISSUE TITLE
"Windows power mode" options no longer correspond with settings options

### ISSUE THREAD

**Issue by Aj1234119** [seerge/g-helper#3202]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

My 2024 G16 "power mode" options in the settings menu have changed from "Best power efficiency," "balanced," and "best performance" to "recommended," "better performance," and "best performance." The Ghelper app still maintains the old options, but they no longer correctly correspond to their respective power mode settings. "Best power efficiency" in Ghelper now corresponds with a blank box in settings, "balanced" in Ghelper corresponds with "recommended" in settings, and "best performance" still corresponds to "best performance" in settings I am not sure if this change has been pushed to all 2024 G16 models, or if it is just a glitch with my machine.

New power mode settings on my laptop"
<img width="788" alt="Power modes" src="https://github.com/user-attachments/assets/a4fa5494-bb14-4cbb-9056-30cf7470ccd5">

blank box when "best power efficiency" is selected in Ghelper:
<img width="773" alt="blankpower mode" src="https://github.com/user-attachments/assets/96521e7d-e41b-4123-9228-5cd2c449a828">

### How to reproduce the bug?

1. Change "power mode" in Ghelper settings
2. Navigate to "Power and Battery" in settings and check power mode

### Logs

[log.txt](https://github.com/user-attachments/files/17237847/log.txt)

### Device and Model

Asus Zephyrus G16 (GU605MY-G16.U94090)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.191.0 (manual fan control version)

### OS

Windows 11 Home version 10.0.22631

**Comment by seerge** [comment]
@Aj1234119 hello, what are those new power modes and what exactly did you do to windows to change that list ?

**Comment by Aj1234119** [comment]
Hi Seerge,

Thank you for the response and the great app. 

Unfortunately I am not sure how the list changed, as I noticed it the other day while scrolling through power settings. I thought it might have corresponded with a windows update affecting more computers and therefore be worth making a change in Ghelper, but it sounds like it is likely just a glitch with my computer.

Also, I may be mistaken, but I believe the link you provided discusses legacy power plans whereas ghelper modifies power overlays as mentioned [here](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/customize-power-slider). This is based on the GUIDs referenced in my ghelper log file upon switching power modes, which correspond to the power overlay GUIDs in this link and not the power plan GUIDs in the link you provided. (Also interesting, I noticed that a "balanced" power mode in ghelper is given a GUID of 00000000-0000-0000-0000-000000000000, not 3af9B8d9-7c97-431d-ad78-34a8bfea439f as mentioned in the performance overlays article. This would seem to mean that the balanced overlay uses the balanced power plan with no modifications.

All of these power settings are a bit confusing, so I may just be misunderstanding! Either way, it does appear that the dropdown menu in Ghelper corresponds with the "power saving," "balanced" and "maximum performance" modes regardless of what the menu says, so we can probably close this issue.

Thanks again!

**Comment by seerge** [comment]
@Aj1234119 hello, sorry, when responding to you yesterday I linked incorrect page from google :) [This is page with power mode GUIDs app uses](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/customize-power-slider). So your link is correct.

You can check them hardcoded here 
https://github.com/seerge/g-helper/blob/3c241cafbae85de8727a964504fcf5365fac5021/app/Mode/PowerNative.cs#L75

And I know that they are correct, cause you can also read current Overlay Scheme GUID with `PowerSetActiveOverlayScheme` method 
https://github.com/seerge/g-helper/blob/3c241cafbae85de8727a964504fcf5365fac5021/app/Mode/PowerNative.cs#L165

I don't know why in your specific windows setup power modes are different, but most likely it's caused either by some modifications or by window update(?).

When you change power mode app writes to log both old and new GUID like
```
10/2/2024 6:50:17 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> ded574b5-45a0-4f42-8737-46345c09c238:OK
10/2/2024 6:50:26 PM: Power Mode 3af9b8d9-7c97-431d-ad78-34a8bfea439f -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
```
I can't adjust them to something else - cause then they will stop working for all other users of course.

And it's indeed looks like in your case `3af9b8d9-7c97-431d-ad78-34a8bfea439f ` also exists by some reason. Is it only "Balanced" option that causes dropdown in windows setting to go blank or any other as well?

**Comment by Aj1234119** [comment]
Hi Seerge,

Thank you continuing to look into this! I believe you are correct, I may have either accidentally overridden my power mode settings (I did use an app called PowerSettingsExplorer to check the values set for each mode/overlay, although I did not intentionally change anything while using it) or it might have been changed in a recent update.

Interestingly, it is the "best power efficiency" Ghelper option which causes my power mode settings to appear as blank. My computer definitely still sets the GUID to 961cc777-2547-4f9d-8174-7d86181b8a7a "efficiency mode" (as evidenced by lower benchmark scores as well as by looking at the active power overlay set in the registry) but it shows as blank in settings. 

Similarly, setting Ghelper to balanced corresponds with "recommended" power mode and the 00000000-0000-0000-0000-000000000000 GUID (no overlay) being applied, whereas setting best performance in Ghelper corresponds with "Best performance" in windows settings and a set GUID of ded574b5-45a0-4f42-8737-46345c09c238. The only way I can engage plan 3af9b8d9-7c97-431d-ad78-34a8bfea439f is by going to the power mode settings and choosing "better performance" so I will likely just ignore that one.

I noticed that you do have a line for "better performance" in the code here:

       https://github.com/seerge/g-helper/blob/3c241cafbae85de8727a964504fcf5365fac5021/app/Mode/PowerNative.cs#L78

But it is set as the same GUID as the 'maximum performance" option. In systems which haven't been messed up like mine, do you know if this is typically duplicated in the registry as well? If so, something I did or an update I received must have replaced this duplicate / inaccessible "better performance" GUID with 3af9b8d9-7c97-431d-ad78-34a8bfea439f (which is also coincidentally listed as "better performance" in the link you sent.) If all laptops do come with a hidden 3af9b8d9-7c97-431d-ad78-34a8bfea439f GUID in the registry, I wonder if you could add it as a dropdown option in Ghelper.

Thanks again for the help!

**Comment by seerge** [comment]
@Aj1234119 hello,

It is logical  that `Best Power Efficiency` causes this for you, as you don't have it listed in a dropdown. But since you have other 2 - I would just use only them. Or actually dig deeper into what exactly you did to windows to make it forget default power modes :)

As `Best Power Efficiency` is very handy, it makes windows and it's processes use much less CPU power when it's not needed and therefore preserve battery and generate less heat.

---

I don't want to add `Better Efficiency` (or any other power modes) to the list cause it's not available in settings by default and it will cause much more harm and extra questions than help. To my knowledge it existed in windows 10 (where power slider had 4 steps)

https://github.com/seerge/g-helper/blob/3c241cafbae85de8727a964504fcf5365fac5021/app/Mode/PowerNative.cs#L78 
Is not being used anywhere, it's a leftover from some other thing i was doing before.

----

Ok, I'm closing this as resolved then as this is not a problem in G-Helper in a first place.

Thanks
