### ISSUE TITLE
Keyboard lighting effects not working

### ISSUE THREAD

**Issue by Hooola23** [seerge/g-helper#3205]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Everything works perfectly. Just the keyboard lighting effects are not working. My model is GU603VI, it has only 1 light zone (white) with no rgb. The lighting effects like strobe and breathe are not working.

### How to reproduce the bug?

Just changing the effects under "Laptop Keyboard".

### Logs

[log.txt](https://github.com/user-attachments/files/17240066/log.txt)

### Device and Model

Asus Zephyrus G16 GU603VI

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.191.0

### OS

Windows 11

**Comment by seerge** [comment]
@Hooola23 hello, does your keyboard support them in a first place? 

Do those effects work when you set them in Armoury Crate ?

Thanks

**Comment by Hooola23** [comment]
Yes my keyboard supports the effects and they worked fine with armoury
crate.

**Comment by seerge** [comment]
@Hooola23 can you check if they still work in AC ? cause from what i see app changes modes as it should. Command for RGB is same for all devices, so if it works - it works.

```
03-10-2024 11:43:11: AuraMode: AuraColorCycle
03-10-2024 11:43:11: USB 19B6: 5D-B3-00-02-FF-FF-FF-F5-00-00-FF-FF-FF-00-00-00-00
03-10-2024 11:43:11: USB 19B6: 5D-B5-00-00-00
03-10-2024 11:43:11: USB 19B6: 5D-B4
03-10-2024 11:43:14: WMI event 179
03-10-2024 11:43:14: AuraMode: AuraRainbow
03-10-2024 11:43:14: USB 19B6: 5D-B3-00-03-FF-FF-FF-F5-00-00-FF-FF-FF-00-00-00-00
03-10-2024 11:43:14: USB 19B6: 5D-B5-00-00-00
03-10-2024 11:43:14: USB 19B6: 5D-B4
``

**Comment by Hooola23** [comment]
I installed AC again to check and they do work. After that uninstalled it
again and they don't work with ghelper.

Regards

**Comment by seerge** [comment]
@Hooola23 did you use official AC uninstaller app for that ? Also did you stop Asus services from `Extra` settings?

**Comment by Hooola23** [comment]
Yes, I used the official AC uninstaller. Also I have tried both, stopping
the Asus services and also running them to see if the lighting works.

They don't work in both scenarios.

**Comment by seerge** [comment]
@Hooola23 can you try one thing - set color to pure RED in a color picker. And check if makes any difference ?

**Comment by Hooola23** [comment]
Although my laptop supports only single color, setting it to red worked!
Thanks a lot for your help.

**Comment by seerge** [comment]
@Hooola23 it's a known issue of a firmware on single-color keyboards. They require only first byte (R) from 3 (R-G-B) to be set for color. That's why setting it pure RED does the trick.

Thanks

**Comment by Hooola23** [comment]
That's interesting, thanks for the help and for creating this simple yet
wonderful executable.
