### ISSUE TITLE
What's the difference between NVIDIA Control Center setting and GHelper setting for GPU selection?

### ISSUE THREAD

**Issue by andrey6060** [seerge/g-helper#3206]
NVIDIA Control Center has GPU mode setting. Is it any different than GHelper's GPU modes?

**Comment by seerge** [comment]
@andrey6060 if you speak about Nvidia Optimus / NVidia GPU only settings they are different from proprietary asus modes. Please make yourself [familiar with readme ](https://github.com/seerge/g-helper?tab=readme-ov-file#video_game-gpu-modes).

Closed as this is **not** an issue with the app.
