### ISSUE TITLE
Rog Strix G16 Ambient Light doesnt work properly

### ISSUE THREAD

**Issue by beboo330** [seerge/g-helper#3207]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The ambient lighting of the !Keyboard! doesnt work.

Only the LED Stripe on the bottom of the Laptop is on.

### How to reproduce the bug?

Change RGB lights to Ambient mode

### Logs

03.10.2024 15:47:01: App launched: ROG Strix G614JV_G614JV :0.194.0.0de-DE
03.10.2024 15:47:01: Start Count: 8
03.10.2024 15:47:02: Matrix control device was not found on your machine.
03.10.2024 15:47:03: C:\ProgramData\ASUS\GameVisual\ASUS_DCIP3.icm DCIP3
03.10.2024 15:47:03: C:\ProgramData\ASUS\GameVisual\ASUS_DisplayP3.icm DisplayP3
03.10.2024 15:47:03: C:\ProgramData\ASUS\GameVisual\ASUS_sRGB.icm sRGB
03.10.2024 15:47:03: NVIDIA GeForce RTX 4060 Laptop GPU
03.10.2024 15:47:06: CPU: -1 - 13th Gen Intel(R) Core(TM) i7-13650HX - Intel64 Family 6 Model 183 Stepping 1
03.10.2024 15:47:07: AutoSetting for Online
03.10.2024 15:47:07: Optimization service is running
03.10.2024 15:47:07: Eco flag : 0
03.10.2024 15:47:07: Mux flag : 1
03.10.2024 15:47:07: \\?\DISPLAY#BOE0B33#4&19b7370c&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
03.10.2024 15:47:07: \\?\DISPLAY#BOE0B33#4&19b7370c&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
03.10.2024 15:47:07: NE160WUM-NX2 HDR: False 8 5 True
03.10.2024 15:47:07: Mode = 1 : OK
03.10.2024 15:47:07: Init 19B6: 5D-B9
03.10.2024 15:47:07: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
03.10.2024 15:47:07: Init 19B6: 5D-05-20-31-00-1A
03.10.2024 15:47:07: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
03.10.2024 15:47:07: AuraMode: AuraColorCycle
03.10.2024 15:47:07: USB 19B6: 5D-B3-00-02-00-80-40-EB-00-00-FF-FF-FF-00-00-00-00
03.10.2024 15:47:07: USB 19B6: 5D-B5-00-00-00
03.10.2024 15:47:07: USB 19B6: 5D-B4
03.10.2024 15:47:07: NE160WUM-NX2 HDR: False 8 5 True
03.10.2024 15:47:08: NE160WUM-NX2 HDR: False 8 5 True
03.10.2024 15:47:08: Monitor Power On
03.10.2024 15:47:08: Lid Open
03.10.2024 15:47:08: Lid 19B6: 5D-BA-C5-C4-03
03.10.2024 15:47:08: Auto 19B6: 5D-BA-C5-C4-03
03.10.2024 15:47:09: Latest version 0.194.0.0
03.10.2024 15:47:09: Startup task scheduled: C:\Program Files\GHelper.exe
03.10.2024 15:47:09: Can't create a charge limit task: Zugriff verweigert (0x80070005 (E_ACCESSDENIED))
03.10.2024 15:47:15: AuraMode: AMBIENT
03.10.2024 15:47:15: Input available: \\?\hid#vid_0b05&pid_19b6&col05#6&15ae9f2&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 64
03.10.2024 15:47:46: Design Capacity: 90001mWh, Full Charge Capacity: 84725mWh, Health: 0,9413784291285652381640203998%
03.10.2024 15:47:52: Cores: 0x0806
03.10.2024 15:47:52: CoresMax: 0x0806
03.10.2024 15:47:52: Unable to load DLL 'atiadlxx.dll' or one of its dependencies: Das angegebene Modul wurde nicht gefunden. (0x8007007E)
03.10.2024 15:47:52: Hibernate after 2147483647
03.10.2024 15:47:54: USB 19B6: 5D-BD-01-F7-1F-FF-FF-FF
03.10.2024 15:47:55: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
03.10.2024 15:47:55: USB 19B6: 5D-BD-01-FD-1F-FF-FF-FF
03.10.2024 15:47:55: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
03.10.2024 15:47:56: USB 19B6: 5D-BD-01-DF-1F-FF-FF-FF
03.10.2024 15:47:56: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
03.10.2024 15:47:56: USB 19B6: 5D-BD-01-7F-1F-FF-FF-FF
03.10.2024 15:47:56: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
03.10.2024 15:47:57: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
03.10.2024 15:47:57: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
03.10.2024 15:47:58: AuraMode: AMBIENT
03.10.2024 15:48:00: AuraMode: AMBIENT
03.10.2024 15:48:02: AuraMode: AMBIENT
03.10.2024 15:48:19: Slider 19B6: 5D-BA-C5-C4-01
03.10.2024 15:48:20: Slider 19B6: 5D-BA-C5-C4-00
03.10.2024 15:48:21: Slider 19B6: 5D-BA-C5-C4-01
03.10.2024 15:48:21: Slider 19B6: 5D-BA-C5-C4-02
03.10.2024 15:48:21: Slider 19B6: 5D-BA-C5-C4-03
03.10.2024 15:48:23: Slider 19B6: 5D-BA-C5-C4-02
03.10.2024 15:48:24: Slider 19B6: 5D-BA-C5-C4-00
03.10.2024 15:48:24: Slider 19B6: 5D-BA-C5-C4-01
03.10.2024 15:48:25: Slider 19B6: 5D-BA-C5-C4-02
03.10.2024 15:48:25: Slider 19B6: 5D-BA-C5-C4-03
03.10.2024 15:48:26: Slider 19B6: 5D-BA-C5-C4-02
03.10.2024 15:48:26: Slider 19B6: 5D-BA-C5-C4-01
03.10.2024 15:48:26: Slider 19B6: 5D-BA-C5-C4-00
03.10.2024 15:48:28: Slider 19B6: 5D-BA-C5-C4-01
03.10.2024 15:48:28: Slider 19B6: 5D-BA-C5-C4-02
03.10.2024 15:48:28: Slider 19B6: 5D-BA-C5-C4-03
03.10.2024 15:48:31: USB 19B6: 5D-BD-01-F7-1F-FF-FF-FF
03.10.2024 15:48:32: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
03.10.2024 15:48:33: USB 19B6: 5D-BD-01-FB-1F-FF-FF-FF
03.10.2024 15:48:33: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
03.10.2024 15:48:34: USB 19B6: 5D-BD-01-FF-1A-FF-FF-FF
03.10.2024 15:48:34: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
03.10.2024 15:48:35: USB 19B6: 5D-BD-01-FF-1D-FF-FF-FF
03.10.2024 15:48:35: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
03.10.2024 15:48:36: USB 19B6: 5D-BD-01-FF-1F-DD-DD-FF
03.10.2024 15:48:37: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
03.10.2024 15:48:55: AuraMode: AuraRainbow
03.10.2024 15:48:55: USB 19B6: 5D-B3-00-03-00-80-40-EB-00-00-FF-FF-FF-00-00-00-00
03.10.2024 15:48:55: USB 19B6: 5D-B5-00-00-00
03.10.2024 15:48:55: USB 19B6: 5D-B4
03.10.2024 15:48:59: AuraMode: AuraStatic
03.10.2024 15:48:59: USB 19B6: 5D-B3-00-00-00-80-40-EB-00-00-FF-FF-FF-00-00-00-00
03.10.2024 15:48:59: USB 19B6: 5D-B5-00-00-00
03.10.2024 15:48:59: USB 19B6: 5D-B4
03.10.2024 15:49:00: AuraMode: AuraBreathe
03.10.2024 15:49:00: USB 19B6: 5D-B3-00-01-00-80-40-EB-00-01-FF-FF-FF-00-00-00-00
03.10.2024 15:49:00: USB 19B6: 5D-B5-00-00-00
03.10.2024 15:49:00: USB 19B6: 5D-B4
03.10.2024 15:49:02: AuraMode: AuraColorCycle
03.10.2024 15:49:02: USB 19B6: 5D-B3-00-02-00-80-40-EB-00-00-FF-FF-FF-00-00-00-00
03.10.2024 15:49:02: USB 19B6: 5D-B5-00-00-00
03.10.2024 15:49:02: USB 19B6: 5D-B4
03.10.2024 15:49:04: AuraMode: AuraRainbow
03.10.2024 15:49:04: USB 19B6: 5D-B3-00-03-00-80-40-EB-00-00-FF-FF-FF-00-00-00-00
03.10.2024 15:49:04: USB 19B6: 5D-B5-00-00-00
03.10.2024 15:49:04: USB 19B6: 5D-B4
03.10.2024 15:49:06: AuraMode: AuraColorCycle
03.10.2024 15:49:06: USB 19B6: 5D-B3-00-02-00-80-40-EB-00-00-FF-FF-FF-00-00-00-00
03.10.2024 15:49:06: USB 19B6: 5D-B5-00-00-00
03.10.2024 15:49:06: USB 19B6: 5D-B4
03.10.2024 15:50:11: HID Device Event: Checking for new ASUS Mice
03.10.2024 15:50:13: HID Device Event: Checking for new ASUS Mice
03.10.2024 15:50:15: HID Device Event: Checking for new ASUS Mice
03.10.2024 15:52:31: Display configuration changed.
03.10.2024 15:52:31: NE160WUM-NX2 HDR: False 8 5 True
03.10.2024 15:56:25: WMI event 124
03.10.2024 15:56:25: WMI event 124
03.10.2024 16:40:11: HID Device Event: Checking for new ASUS Mice
03.10.2024 16:40:13: HID Device Event: Checking for new ASUS Mice
03.10.2024 17:27:51: NE160WUM-NX2 HDR: False 8 5 True
03.10.2024 17:28:56: Design Capacity: 90001mWh, Full Charge Capacity: 84725mWh, Health: 0,9413784291285652381640203998%
03.10.2024 17:28:59: Cores: 0x0806
03.10.2024 17:28:59: CoresMax: 0x0806
03.10.2024 17:28:59: Unable to load DLL 'atiadlxx.dll' or one of its dependencies: Das angegebene Modul wurde nicht gefunden. (0x8007007E)
03.10.2024 17:28:59: Hibernate after 2147483647

### Device and Model

ASUS ROG STRIX G16 G614JV

### Additional information.

Only the bottom LED STRIPE works. the keyboard stays off.

### Armoury Crate

Uninstalled

### Asus Services

8

### Version

0.194

### OS

Windows 11

**Comment by seerge** [comment]
@beboo330 hello, your model (with exactly same name) exists in 4-zone RGB and per-key RGB options. 

By default app would assume it's 4-zone RGB. Open `Extra` settings, check 'Per-key RGB` there and restart app. Does it change anything ?

Thanks

**Comment by seerge** [comment]
@beboo330 any updates here ?

**Comment by beboo330** [comment]
Hi, yes now it works Fine !! Thank you very much !!!
