### ISSUE TITLE
Norton

### ISSUE THREAD

**Issue by oM0NG0o** [seerge/g-helper#321]
May want to fix this. Just a thought.
Filename: ghelper.exe Threat name: SONAR.ProcHijack!g47

![ghelper](https://user-images.githubusercontent.com/132635900/236372508-0ad9597e-e001-4a17-b979-deeeada12c8c.jpg)

**Comment by ramius86** [comment]
Think the best way to get rid of this is just unistall Norton and just use windows defender :)
https://www.virustotal.com/gui/file/9643deb218e8797743b26f449a998cc8416c4280e07c66466707460480ef740e?nocache=1
https://www.virustotal.com/gui/file/50900d958d807a1c1d0ff555bd2a72684b76bdac2f21924ac473461d7763f038?nocache=1
Both stable and latest release are clear and safe

**Comment by seerge** [comment]
@oM0NG0o hello, false positives can happen from any antiviral apps, you can always compile app by yourself or use a version lower from releases :)

Closing as there is nothig to "fix"
