### ISSUE TITLE
Power limits are not working 0.194.0

### ISSUE THREAD

**Issue by ZhenyaK3** [seerge/g-helper#3213]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Power sliders on Asus TUF Gaming A16 Advantage Edition FA617NT in the "Fans+Power" tab do not work
Reinstalling G-Helper does not help. Uninstalled the program with Revo Uninstaller Pro forced to search for all sorts of files and residues from the registry, rebooted the laptop many times and reinstalled G-Helper older versions (0.192 / 0.191) - no reaction. This is a serious problem, because the laptop starts to automatically adjust the limits and when entering a demanding game such as Star Wars Jedi Survivor I still on the main menu the temperature of the GPU instantly rises to 100 degrees, and the processor consumes more than 130 watts. For the experiment I installed Armoury Crate - everything worked fine. But G-Helper is much more convenient, I hope for a soon release of an update with fixes for this situation

### How to reproduce the bug?

.

### Logs

.

### Device and Model

Asus TUF Gaming A16 Advantage Edition FA617NT

### Additional information.

.

### Armoury Crate

Installed

### Asus Services

Most of them

### Version

0.194

### OS

Windows 11 Home 23H2 22631.4249 (License)

**Comment by seerge** [comment]
>  I understand that, if insufficient information **or no app logs will be provided**, my issue will be closed without an answer.
