### ISSUE TITLE
Ultimate requires restarting when it doesn't need to

### ISSUE THREAD

**Issue by Anfeket** [seerge/g-helper#3214]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Switching to Ultimate mode to drive the display with the dGPU requires a restart, while I can switch the display using the Nvidia control panel ![image](https://github.com/user-attachments/assets/94d25425-5ae6-4ae0-a91c-27e2bcf571d0) 
![image](https://github.com/user-attachments/assets/ebef6d32-72bf-407f-bdc4-a06c7e2583bf)

### Describe the solution you'd like

Using Ghelper to switch the GPU that drives the display would be nice.

### Describe alternatives you've considered

Nvidia control panel but it takes too long to load sometimes

### Device and Model

ASUS TUF Gaming A15 FA507NV

**Comment by seerge** [comment]
@Anfeket hello, 

`Ultimate` mode always requires restart. **It is exactly same as in Armoury Crate**  and this is how your asus hardware works.

Optimus / NvidiaGPU only is not Ultimate mode. It's alternative solution from nvidia.
