### ISSUE TITLE
Tuf A14 Ryzen 9 AI keeps crashing

### ISSUE THREAD

**Issue by quanticchaos** [seerge/g-helper#3217]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

TUF A14 with AMD Ryzen AI 9 HX 370 and Nvidia RTX4050. Windows 11 pro 24H2 26120.1912 Windows Feature Experience Pack 1000.26100.28.0.  
Windows keeps getting a green screen related to CPU undervoltage. Tried with and without Asus services and get the same error. 
I'll keep using Armoury Crate for now but I really appreciate your software that I use in my other Asus laps. Thanks. 

### How to reproduce the bug?

Unplugged Laptop, G-helper settings in Eco and Silent, browse the web normally.

### Logs

10/4/2024 8:32:02 AM: ------------
10/4/2024 8:32:03 AM: App launched: ASUS TUF Gaming A14 FA401WV_FA401WV :0.194.0.0en-US
10/4/2024 8:32:03 AM: Start Count: 18
10/4/2024 8:32:05 AM: Matrix control device was not found on your machine.
10/4/2024 8:32:06 AM: Stopped: ASUSSmartDisplayControl
10/4/2024 8:32:07 AM: dGPU not found
10/4/2024 8:32:08 AM: CPU: 12 - AMD Ryzen AI 9 HX 370 w/ Radeon 890M            - AMD64 Family 26 Model 36 Stepping 0
10/4/2024 8:32:08 AM: AutoSetting for Offline
10/4/2024 8:32:08 AM: Optimization service is running
10/4/2024 8:32:08 AM: Eco flag : 1
10/4/2024 8:32:08 AM: Mux flag : 1
10/4/2024 8:32:09 AM: \\?\DISPLAY#BOE0CA4#5&1479a441&1&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
10/4/2024 8:32:09 AM: \\?\DISPLAY#BOE0CA4#5&1479a441&1&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
10/4/2024 8:32:09 AM: NE140QDM-NX7 HDR: False 8 13 True
10/4/2024 8:32:09 AM: Mode = 2 : OK
10/4/2024 8:32:09 AM: TUF_KB = 13566397 : OK
10/4/2024 8:32:09 AM: AuraMode: AuraStatic
10/4/2024 8:32:09 AM: TUF RGB = B4-00-FF-FF-FF-EB : 0
10/4/2024 8:32:09 AM: TUF RGB = B3-00-FF-FF-FF-EB : OK
10/4/2024 8:32:09 AM: TUF RGB = B4-00-FF-FF-FF-EB : OK
10/4/2024 8:32:10 AM: TUF Brightness = 129 : OK
10/4/2024 8:32:11 AM: Can't create a charge limit task: Access is denied. (0x80070005 (E_ACCESSDENIED))
10/4/2024 8:32:11 AM: Monitor Power On
10/4/2024 8:32:11 AM: Lid Open
10/4/2024 8:32:11 AM: TUF Brightness = 129 : OK
10/4/2024 8:32:35 AM: NE140QDM-NX7 HDR: False 8 13 True
10/4/2024 8:32:36 AM: Can't remove charge limit task: The system cannot find the file specified. (0x80070002)
10/4/2024 8:32:37 AM: Latest version 0.194.0.0
10/4/2024 8:32:37 AM: Design Capacity: 73000mWh, Full Charge Capacity: 71135mWh, Health: 0.9744520547945205479452054795%

### Device and Model

ASUS TUF Gaming A14 FA401WV_FA401WV

### Armoury Crate

Uninstalled

### Version

0.194

### OS

Windows 11 24H2

**Comment by seerge** [comment]
@quanticchaos hello, I don’t think your problems are related to G-Helper, as it’s not a driver and it’s not managing your device in realtime. It also can’t  control any “voltage”.

I see that you use default Silent mode (that is baked in BIOS) without any customisations.

- What is green screen, and what does it say?
- Do you have AC running next to it or did you yse official AC uninstaller?

**Comment by quanticchaos** [comment]
Hello @seerge , thanks for your prompt repply, been looking at the logs in windows event viewer and the error is about Kernel-power. I uninstalled AC with the official uninstaller before using G-Helper. 
This is the log previous to reboot: 
<System>
  <Provider Name="Microsoft-Windows-Kernel-Power" Guid="{331c3b3a-2005-44c2-ac5e-77220c37d6b4}" /> 
  <EventID>125</EventID> 
  <Version>4</Version> 
  <Level>4</Level> 
  <Task>86</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000020</Keywords> 
  <TimeCreated SystemTime="2024-10-04T14:23:39.8419989Z" /> 
  <EventRecordID>27474</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="4" ThreadID="8" /> 
  <Channel>System</Channel> 
  <Computer>A14</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
<EventData>
  <Data Name="ThermalZoneDeviceInstanceLength">9</Data> 
  <Data Name="ThermalZoneDeviceInstance">\_TZ.TZ01</Data> 
  <Data Name="_PSV">0</Data> 
  <Data Name="_TC1">1</Data> 
  <Data Name="_TC2">2</Data> 
  <Data Name="_TSP">2000</Data> 
  <Data Name="_AC0">0</Data> 
  <Data Name="_AC1">0</Data> 
  <Data Name="_AC2">0</Data> 
  <Data Name="_AC3">0</Data> 
  <Data Name="_AC4">0</Data> 
  <Data Name="_AC5">0</Data> 
  <Data Name="_AC6">0</Data> 
  <Data Name="_AC7">0</Data> 
  <Data Name="_AC8">0</Data> 
  <Data Name="_AC9">0</Data> 
  <Data Name="_CRT">383</Data> 
  <Data Name="_HOT">373</Data> 
  <Data Name="MinimumThrottle">0</Data> 
  <Data Name="_CR3">0</Data> 
  <Data Name="OverThrottleThreshold">0</Data> 
  <Data Name="DescriptionLength">0</Data> 
  <Data Name="Description" /> 
  <Data Name="_TZP">0</Data> 
  </EventData>

**Comment by seerge** [comment]
@quanticchaos ok,

- Does it happen in any mode or only in `Silent` (which is also paired with windows `Best power efficiency` power mode) ?
- Does it happen if you quit G-Helper ?

**Comment by quanticchaos** [comment]
I'll try it at night (10AM at my place), sorry, I need to use the laptop to work right now so I reinstalled AC but it doesn't happen with AC even in silent state.

**Comment by seerge** [comment]
@quanticchaos in AC `Silent` is paired with `Balanced` power mode in windows (by some reasons). So that's why i asked :) 

Try to set windows power mode to `Best power efficiency` manually while in Silent in AC 
![Screenshot 2024-10-04 180817](https://github.com/user-attachments/assets/c70cb341-2782-496a-8e98-8099f13005a7)

I quickly googled your error and seem to happen randomly based on what i see 
https://answers.microsoft.com/en-us/windows/forum/all/event-id-125-kernel-power-issue/f9e0102d-5f3f-43b3-8b99-950597cba9f5
https://answers.microsoft.com/en-us/windows/forum/all/kernel-power-issue-id-125/a37a7fe5-6d20-424c-9ac6-b552eefe4acf

Do you use latest drivers / BIOS ?

**Comment by quanticchaos** [comment]
Dear @seerge, sorry for the delay. I used the laptop almost all day yesterday changing the power mode and ran without issues. Today, I just switched battery saver to always on and there was the GSOD again. My drivers are the latest. I'm sorry to have blamed G-helper for this problem albeit it was happening much more often with it (guess it was the windows power mode). Shame Asus can make such a device without fully testing it. Thank you very much for your help and for your great software that I use without issues in my Flow Z13 and my Strix G16.

**Comment by seerge** [comment]
@quanticchaos ok, so as I understand you get BSODs even with Armoury Crate as far as `Best Power Efficiency` power mode or `Battery Saver` mode (which is same) is enabled? Then it's probably some hiccups with firmware / BIOS still here or just something wrong with hardware. 

You can just `Fans + Power` settings in G-Helper and for `Silent` profile set `Power Mode` to Balanced or Best Performance (as a workaround?) 

Closing as resolved as it's not related to the app :)

Thanks

**Comment by seerge** [comment]
@quanticchaos P.S. If you will figure out some "permanent" fix for your problem - let me know. I may add it to the [Troubleshooting](https://github.com/seerge/g-helper/wiki/Troubleshooting) section.

**Comment by quanticchaos** [comment]
Of course I will but for now it seems the only solution is to keep it plugged. Thanks a lot for your help. I already reinstalled your software and I'm going to invite you a beer right now.

**Comment by seerge** [comment]
@quanticchaos thanks :) as far as I understood - you can use it unplugged as well, just keep power mode on Balanced and don't use Battery Saver in windows. Hopefully there will be some fix on firmware level or so.

**Comment by quanticchaos** [comment]
Thanks to you mate. And thanks for your hard work, your software should be installed by default on every Asus laptop. Cheers!
