### ISSUE TITLE
Keyboard backlight not working error

### ISSUE THREAD

**Issue by Louis1501** [seerge/g-helper#3218]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

If my laptop does not output to HDMI screen, the keyboard backlight still works. But if I plug in the HDMI cable, it will not work.

### Describe the solution you'd like

Please fix it. I'm using win 11 home 23H2 Os 22631.4249

### Device and Model

G713RW

**Comment by seerge** [comment]
@Louis1501 hello, it is difficult to understand what are you asking and how is it related to G-Helper ? :)

- Does same as you explain happen if you just quit G-Helper completely ?
- Are you able to change backlight brightness via app ?
- Upload a log from `%appdata%\GHelper`

**Comment by Louis1501** [comment]
[log.txt](https://github.com/user-attachments/files/17265238/log.txt)

I don't know English. I use the translation tool.
My mistake is that the laptop keyboard backlight does not appear when the external monitor is output (plugged in the charger)
When I unplug the laptop and use the battery without charging, the keyboard backlight works again

**Comment by seerge** [comment]
@Louis1501 hello,

App remembers backlight brightness separately for situations when you are plugged in and on battery. It is not connected with external monitor.

I see that when you are plugged in - you have set backlight to be OFF. If you want it to be ON - you need literally press `FN+F3` to increase backlight brightness, and it will be remembered.

Also make sure all backlight is enabled under `Extra` settings :)

Thanks.
