### ISSUE TITLE
G14 (2024) Slash Lighting Won't Show Battery Level On Lid Close

### ISSUE THREAD

**Issue by Bluerella** [seerge/g-helper#3219]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

With the 'Disable on lid close' option for slash lighting UNCHECKED, most animations are able to continue displaying into sleep. However, if the animation is changed to 'battery level', then the sleep animation is determined by the last animation that was selected before the change to 'battery level'.

I am not certain whether this is a bug or if it isn't supposed to work due to battery level not being calculated during sleep or something.

It would be very useful to be able to keep your laptop lid closed and still tell the battery level while it is charging. 

### How to reproduce the bug?

1. Set the slash lighting to a mode other than 'battery level'.
2. Change the mode to 'battery level'.
3. Ensure the 'disable on battery' option is left unchecked.

### Logs

[log.txt](https://github.com/user-attachments/files/17263091/log.txt)

### Device and Model

Asus Zephyrus G14 GA403UV

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.194.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Bluerella hello,

Unfortunately this is how Slash Lighting works on firmware level. 

`Battery Level` mode is a custom mode, and G-Helper just periodically sets a custom pattern to the lighting strip based on current battery charge level. And when you close lid - firmware just shuts down any custom patterns set. 

I can't override that anyhow. Sorry.

Thanks :)
