### ISSUE TITLE
no gpu mode selection or gpu in extras ROG G512li

### ISSUE THREAD

**Issue by Tim0t333** [seerge/g-helper#3220]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

gpu mode is igpu+dpu , no selection available, it worked before a recent nivida update, i used ddu in safe mode and reinstalled from asus website and updated with geforce exp.   

### How to reproduce the bug?

it just stuck in eco mode? idk 

### Logs

10/4/2024 5:48:56 PM: \\?\DISPLAY#NCP004D#4&322953e6&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
10/4/2024 5:48:56 PM: \\?\DISPLAY#NCP004D#4&322953e6&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
10/4/2024 5:48:56 PM:  HDR: False 8 8 False
10/4/2024 5:48:57 PM: Init 1866: 5D-B9
10/4/2024 5:48:57 PM: USB 1866|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
10/4/2024 5:48:57 PM: Input: \\?\hid#vid_0b05&pid_1866&mi_02&col01#7&1c44a3bb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
10/4/2024 5:48:57 PM: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
10/4/2024 5:48:57 PM: Init 1866: 5D-05-20-31-00-1A
10/4/2024 5:48:57 PM: USB 1866: 5D-BD-01-DF-17-FF-FF-FF
10/4/2024 5:48:57 PM: AuraMode: AuraRainbow
10/4/2024 5:48:57 PM: USB 1866: 5D-B3-00-03-FF-FF-FF-E1-00-00-FF-FF-FF-00-00-00-00
10/4/2024 5:48:57 PM: USB 1866: 5D-B5-00-00-00
10/4/2024 5:48:57 PM: USB 1866: 5D-B4
10/4/2024 5:48:58 PM: Auto 1866: 5D-BA-C5-C4-01
10/4/2024 5:49:00 PM: Display configuration changed.
10/4/2024 5:49:00 PM:  HDR: False 8 8 False
10/4/2024 5:50:24 PM: Timeout 1866: 5D-BA-C5-C4-00
10/4/2024 5:52:08 PM: Monitor Dimmed
10/4/2024 5:52:10 PM: Monitor Power On
10/4/2024 5:52:10 PM: AutoSetting for Offline
10/4/2024 5:52:10 PM: BatteryLimit = 80 : OK
10/4/2024 5:52:10 PM: Input available: \\?\hid#vid_0b05&pid_1866&mi_02&col01#7&1c44a3bb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} 1866 64
10/4/2024 5:52:10 PM: Eco flag : -65536
10/4/2024 5:52:10 PM: Mux flag : -65536
10/4/2024 5:52:10 PM: \\?\DISPLAY#NCP004D#4&322953e6&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
10/4/2024 5:52:10 PM: \\?\DISPLAY#NCP004D#4&322953e6&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
10/4/2024 5:52:10 PM:  HDR: False 8 8 False
10/4/2024 5:52:10 PM: Mode = 0 : OK
10/4/2024 5:52:10 PM: Init 1866: 5D-B9
10/4/2024 5:52:10 PM: Input: \\?\hid#vid_0b05&pid_1866&mi_02&col01#7&1c44a3bb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
10/4/2024 5:52:10 PM: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
10/4/2024 5:52:10 PM: Init 1866: 5D-05-20-31-00-1A
10/4/2024 5:52:10 PM: USB 1866: 5D-BD-01-DF-17-FF-FF-FF
10/4/2024 5:52:10 PM: AuraMode: AuraRainbow
10/4/2024 5:52:10 PM: USB 1866: 5D-B3-00-03-FF-FF-FF-E1-00-00-FF-FF-FF-00-00-00-00
10/4/2024 5:52:10 PM: USB 1866: 5D-B5-00-00-00
10/4/2024 5:52:10 PM: USB 1866: 5D-B4
10/4/2024 5:52:10 PM: Auto 1866: 5D-BA-C5-C4-01
10/4/2024 5:52:11 PM: Auto 1866: 5D-BA-C5-C4-01
10/4/2024 5:52:21 PM: WMI event 207
10/4/2024 5:52:21 PM: WMI event 88
10/4/2024 5:52:21 PM: AutoSetting for Online
10/4/2024 5:52:21 PM: BatteryLimit = 80 : OK
10/4/2024 5:52:21 PM: Input available: \\?\hid#vid_0b05&pid_1866&mi_02&col01#7&1c44a3bb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} 1866 64
10/4/2024 5:52:21 PM:  HDR: False 8 0 False
10/4/2024 5:52:21 PM: Init 1866: 5D-B9
10/4/2024 5:52:21 PM: USB 1866|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
10/4/2024 5:52:21 PM: Input: \\?\hid#vid_0b05&pid_1866&mi_02&col01#7&1c44a3bb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
10/4/2024 5:52:21 PM: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
10/4/2024 5:52:21 PM: Init 1866: 5D-05-20-31-00-1A
10/4/2024 5:52:21 PM: USB 1866: 5D-BD-01-DF-17-FF-FF-FF
10/4/2024 5:52:21 PM: AuraMode: AuraRainbow
10/4/2024 5:52:21 PM: USB 1866: 5D-B3-00-03-FF-FF-FF-E1-00-00-FF-FF-FF-00-00-00-00
10/4/2024 5:52:21 PM: USB 1866: 5D-B5-00-00-00
10/4/2024 5:52:21 PM: USB 1866: 5D-B4
10/4/2024 5:52:22 PM: Auto 1866: 5D-BA-C5-C4-01
10/4/2024 5:52:24 PM: Display configuration changed.
10/4/2024 5:52:24 PM:  HDR: False 8 0 False
10/4/2024 5:52:32 PM: WMI event 87
10/4/2024 5:52:32 PM: BatteryLimit = 80 : OK
10/4/2024 5:52:32 PM: Input available: \\?\hid#vid_0b05&pid_1866&mi_02&col01#7&1c44a3bb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} 1866 64
10/4/2024 5:52:32 PM: Mode = 0 : OK
10/4/2024 5:52:32 PM: Eco flag : -65536
10/4/2024 5:52:32 PM: Mux flag : -65536
10/4/2024 5:52:32 PM: \\?\DISPLAY#NCP004D#4&322953e6&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
10/4/2024 5:52:32 PM: \\?\DISPLAY#NCP004D#4&322953e6&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
10/4/2024 5:52:32 PM:  HDR: False 8 8 False
10/4/2024 5:52:32 PM: Init 1866: 5D-B9
10/4/2024 5:52:32 PM: USB 1866|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
10/4/2024 5:52:32 PM: Input: \\?\hid#vid_0b05&pid_1866&mi_02&col01#7&1c44a3bb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
10/4/2024 5:52:32 PM: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
10/4/2024 5:52:32 PM: Init 1866: 5D-05-20-31-00-1A
10/4/2024 5:52:32 PM: USB 1866: 5D-BD-01-DF-17-FF-FF-FF
10/4/2024 5:52:32 PM: AuraMode: AuraRainbow
10/4/2024 5:52:32 PM: USB 1866: 5D-B3-00-03-FF-FF-FF-E1-00-00-FF-FF-FF-00-00-00-00
10/4/2024 5:52:32 PM: USB 1866: 5D-B5-00-00-00
10/4/2024 5:52:32 PM: USB 1866: 5D-B4
10/4/2024 5:52:33 PM: Auto 1866: 5D-BA-C5-C4-01
10/4/2024 5:52:35 PM: Display configuration changed.
10/4/2024 5:52:35 PM:  HDR: False 8 8 False
10/4/2024 5:53:11 PM: Design Capacity: 50527mWh, Full Charge Capacity: 39124mWh, Health: 0.7743186811011934213390860332%
10/4/2024 5:53:12 PM: \\?\DISPLAY#NCP004D#4&322953e6&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
10/4/2024 5:53:12 PM: \\?\DISPLAY#NCP004D#4&322953e6&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
10/4/2024 5:53:15 PM: Screen = 144Hz : OK
10/4/2024 5:53:15 PM:  HDR: False 8 8 False
10/4/2024 5:53:15 PM: Display configuration changed.
10/4/2024 5:53:15 PM:  HDR: False 8 8 False
10/4/2024 5:54:30 PM: Timeout 1866: 5D-BA-C5-C4-00
10/4/2024 5:55:00 PM: WMI event 88
10/4/2024 5:55:00 PM: AutoSetting for Online
10/4/2024 5:55:00 PM: BatteryLimit = 80 : OK
10/4/2024 5:55:00 PM: WMI event 207
10/4/2024 5:55:00 PM: Input available: \\?\hid#vid_0b05&pid_1866&mi_02&col01#7&1c44a3bb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} 1866 64
10/4/2024 5:55:00 PM: Eco flag : -65536
10/4/2024 5:55:00 PM: Mux flag : -65536
10/4/2024 5:55:00 PM: \\?\DISPLAY#NCP004D#4&322953e6&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
10/4/2024 5:55:00 PM: \\?\DISPLAY#NCP004D#4&322953e6&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
10/4/2024 5:55:00 PM:  HDR: False 8 0 False
10/4/2024 5:55:00 PM: Mode = 0 : OK
10/4/2024 5:55:00 PM: Init 1866: 5D-B9
10/4/2024 5:55:00 PM: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
10/4/2024 5:55:00 PM: USB 1866|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
10/4/2024 5:55:00 PM: Init 1866: 5D-05-20-31-00-1A
10/4/2024 5:55:00 PM: USB 1866: 5D-BD-01-DF-17-FF-FF-FF
10/4/2024 5:55:00 PM: AuraMode: AuraRainbow
10/4/2024 5:55:00 PM: USB 1866: 5D-B3-00-03-FF-FF-FF-E1-00-00-FF-FF-FF-00-00-00-00
10/4/2024 5:55:00 PM: USB 1866: 5D-B5-00-00-00
10/4/2024 5:55:00 PM: USB 1866: 5D-B4
10/4/2024 5:55:01 PM: Auto 1866: 5D-BA-C5-C4-01
10/4/2024 5:55:21 PM: Listener stopped
10/4/2024 6:00:43 PM: Key: 174
10/4/2024 6:00:43 PM: Mode = 1 : OK
10/4/2024 6:00:43 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
10/4/2024 6:00:43 PM: Boost 4
10/4/2024 6:00:44 PM: Key: 174
10/4/2024 6:00:44 PM: Mode = 2 : OK
10/4/2024 6:00:44 PM: GET CLOCK LIMIT: NVAPI_GPU_NOT_POWERED
10/4/2024 6:00:44 PM: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
10/4/2024 6:00:44 PM: Boost 0
10/4/2024 6:00:44 PM: Key: 174
10/4/2024 6:00:44 PM: Mode = 0 : OK
10/4/2024 6:00:44 PM: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a -> 00000000-0000-0000-0000-000000000000:OK
10/4/2024 6:00:44 PM: Boost 1
10/4/2024 6:00:56 PM:  HDR: False 8 0 False
10/4/2024 6:00:59 PM: Unable to load DLL 'atiadlxx.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
10/4/2024 6:00:59 PM: Hibernate after 0
10/4/2024 6:01:09 PM: \\?\DISPLAY#NCP004D#4&322953e6&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
10/4/2024 6:01:09 PM: \\?\DISPLAY#NCP004D#4&322953e6&0&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
10/4/2024 6:01:09 PM:  HDR: False 8 0 False
10/4/2024 6:32:39 PM:  HDR: False 8 0 False
10/4/2024 6:32:50 PM: Design Capacity: 50527mWh, Full Charge Capacity: 39124mWh, Health: 0.7743186811011934213390860332%
10/4/2024 6:32:54 PM: ' or one of its dependencies: The specified module could not be found. (0x8007007E)
10/4/2024 6:32:54 PM: Hibernate after 0Unable to load DLL 'atiadlxx.dll
10/4/2024 6:36:30 PM:  HDR: False 8 0 False
10/4/2024 6:36:31 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
10/4/2024 6:36:31 PM: Boost 4
10/4/2024 6:36:31 PM: Mode = 1 : OK

### Device and Model

Asus Strix G512li

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.194.0

### OS

windows 11 23H2

**Comment by seerge** [comment]
@Tim0t333 hello, you seem to have a very old device G512li. Most likely it simply never supported any GPU modes.

Log shows that neither Eco mode nor Ultimate mode is simply not available on your system
```
10/4/2024 5:55:00 PM: Eco flag : -65536
10/4/2024 5:55:00 PM: Mux flag : -65536
```

So you are not supposed to see any GPU modes. You have your GPU always enabled and available, and it's managed by windows and Nvidia drivers :) You are not stuck in Eco mode.

Thanks
