### ISSUE TITLE
Limit power draw on USB-C

### ISSUE THREAD

**Issue by ipiegat** [seerge/g-helper#3222]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

My request isn't necessarily related to a "problem", but more or less how the computer generally functions when charging via USB-C. When completely unplugged and on "Best Power Efficiency" mode (CPU boost disabled), my laptop hovers around 2GHz; however, when plugged in via USB-C with the same profile and settings, it now boosts to around 3GHz or just below the base speed (4GHz). This creates an awkward dynamic where the computer is significantly warmer and louder when it is plugged in and doing light tasks like browsing in comparison to being unplugged. The feature I am suggesting could rectify this (if it's possible)?

### Describe the solution you'd like

I believe you could create another "extra" toggle option titled "Limit System Power Draw on USB-C" where, when checked, could manipulate the windows power settings such that the computer does not decide to boost clock speeds just because it is plugged in? I'm unsure if this could be done via limiting the "Maximum Processor State" in power plans or some other option, but a feature like this would honestly be huge to limit unnecessary noise and heat just because I want to watch youtube with my laptop plugged in via USB-C.

### Device and Model

ASUS Zephryus G14 GA403UI

**Comment by seerge** [comment]
@ipiegat hello,

Honestly, I don't want to overcomplicate app UI even more. And it's not that easy to modify power plans + lots of settings in them are obsolete and do nothing on some devices (but still have effect on others)

What you ask you can already achieve by just creating a custom mode (or adjusting existing one) by setting lower power limits or setting `power mode` to `Power Efficiency`, etc.

If you really want to - you can also create a custom power plan in windows itself (by dublicating default Balanced), restrict Max Processor State there and assign that power plan to one of the modes in G-Helper [as explained here ](https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-windows-power-plans-with-each-mode)

Thanks and good luck.
