### ISSUE TITLE
Custom profile fan curve not applied after GPU mode change.

### ISSUE THREAD

**Issue by paraschavan** [seerge/g-helper#3223]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When switching GPU modes on a custom profile, the predefined fan curve is not applied.
![Screenshot 2024-10-05 101149](https://github.com/user-attachments/assets/57760c2f-8be9-4a1b-a86e-57c06d03b89a)
![Screenshot 2024-10-05 101212](https://github.com/user-attachments/assets/3aa445f8-bf62-42c6-8b6c-0573a51b2ecb)

### How to reproduce the bug?

 Choose a custom profile and then change GPU mode will reproduce the behavior

### Logs

[log.txt](https://github.com/user-attachments/files/17265174/log.txt)

### Device and Model

ROG Zephyrus G14 GA402RJ

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.194.0

### OS

Windows 23H2

**Comment by seerge** [comment]
@paraschavan hello.

Enabling or disabling of GPU does not require applying a fan curve. Fan curve is part of performance mode - it is already set and remains set on both of your screenshots.

Everything as it should be.

Thanks.
