### ISSUE TITLE
 GHelper Crashes and enters the bios menu automatically Zephyrus G14 2021

### ISSUE THREAD

**Issue by aaronleonhart** [seerge/g-helper#3224]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Sometimes when I'm working on some heavy tasks or playing games it suddenly crashes and the bios menu will appear afterwards...

sometimes this even happens when just watching a movie

I hope you can help me Serge, thank you :)

### How to reproduce the bug?

 when I'm working on some heavy tasks  or sometimes it even happens that the laptop is idle

### Logs

[log.txt](https://github.com/user-attachments/files/17265821/log.txt)

### Device and Model

Zephyrus G14 GA401QE (2021)

### Additional information.

I have turned off Asus services

### Armoury Crate

Uninstalled

### Version

0,194

### OS

windows 11

**Comment by seerge** [comment]
@aaronleonhart hello,

I'm afraid it's not related to G-Helper, as it's [not a driver and it doesn't run your hardware in realtime](https://github.com/seerge/g-helper?tab=readme-ov-file#-important-notice).

From the log i see that you don't use any strange settings (no crazy CPU undervolting or so) and also very humble power limits (much lower than asus sets by default). So settings are fine, you can also try to click `Factory Defaults` in Turbo mode to see if changes anything.

If device reboots into bios menu - it usually means it can't detect an SSD drive to boot from. It could be that your SSD is (slowly) failing and causing the crashes in a first place or it could be some other underlying hardware thing.

- Try to run SDD test to check if it shows something
- Also try steps from [Troubleshooting](https://github.com/seerge/g-helper/wiki/Troubleshooting), like hard reset, reinstalling clean GPU drivers (just to be sure) and checking if system has corrupted files

**Comment by seerge** [comment]
@aaronleonhart any updates here ?

**Comment by seerge** [comment]
Closed as abandoned
