### ISSUE TITLE
Disable auto Refresh on Startup

### ISSUE THREAD

**Issue by EvilKilla** [seerge/g-helper#3225]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

on App-Start the Refresh Rate will change automatic to anything other than the dynamic resolution i set in the Windows setting. 

<img width="881" alt="image" src="https://github.com/user-attachments/assets/49bf8d7a-9c04-4414-b9fe-1aaf0989e1b3">

is it possible to completly disable the resolution change in the app-start  (power user settings) 
,

### How to reproduce the bug?

-quit ghelper
-change to dynamic resolution in windows settings
-start gehelper...
-dynamic resolution gone

### Logs

05.10.2024 15:44:03: ------------
05.10.2024 15:44:03: App launched: ROG Zephyrus G14 GA402XZ_GA402XZ :0.194.0.0de-DE
05.10.2024 15:44:03: Start Count: 0
05.10.2024 15:44:03: Matrix control device was not found on your machine.
05.10.2024 15:44:04: C:\ProgramData\ASUS\GameVisual doesn't exit
05.10.2024 15:44:05: NVIDIA GeForce RTX 4080 Laptop GPU
05.10.2024 15:44:06: CPU: 9 - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics      - AMD64 Family 25 Model 116 Stepping 1
05.10.2024 15:44:06: USB Version: 1049 4.19
05.10.2024 15:44:06: AutoSetting for Online
05.10.2024 15:44:07: BatteryLimit = 80 : OK
05.10.2024 15:44:07: Input available: \\?\hid#vid_0b05&pid_19b6&col03#7&17810770&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 64
05.10.2024 15:44:07: Mux flag : 1
05.10.2024 15:44:07: USB 19B6|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
05.10.2024 15:44:07: Input: \\?\hid#vid_0b05&pid_19b6&col03#7&17810770&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
05.10.2024 15:44:07: \\?\DISPLAY#AUO7CA6#5&2920693a&4&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
05.10.2024 15:44:07: \\?\DISPLAY#AUO7CA6#5&2920693a&4&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
05.10.2024 15:44:07: Screen = 165Hz : OK
05.10.2024 15:44:07: Miniled: 1 -65536
05.10.2024 15:44:07: B140QAN06.S  HDR: False 10 1 False
05.10.2024 15:44:07: Mode = 2 : OK
05.10.2024 15:44:07: Init 19B6: 5D-B9
05.10.2024 15:44:07: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
05.10.2024 15:44:07: Init 19B6: 5D-05-20-31-00-1A
05.10.2024 15:44:07: GET CLOCK LIMIT: 1400
05.10.2024 15:44:07: AuraMode: AuraStatic
05.10.2024 15:44:07: USB 19B6: 5D-B3-00-00-00-00-00-EB-00-FF-FF-FF-FF-00-00-00-00
05.10.2024 15:44:07: USB 19B6: 5D-B5-00-00-00
05.10.2024 15:44:07: USB 19B6: 5D-B4
05.10.2024 15:44:07: GET GPU CLOCKS: 240, 0
05.10.2024 15:44:08: Miniled: 1 -65536
05.10.2024 15:44:08: B140QAN06.S  HDR: False 10 1 False
05.10.2024 15:44:08: Monitor Power On
05.10.2024 15:44:08: BatteryLimit = 80 : OK
05.10.2024 15:44:08: Lid Open
05.10.2024 15:44:08: Lid 19B6: 5D-BA-C5-C4-03
05.10.2024 15:44:08: Auto 19B6: 5D-BA-C5-C4-03
05.10.2024 15:44:09: PowerLimit C0 (GPU BOOST) = 5 : OK
05.10.2024 15:44:09: PowerLimit C2 (GPU TEMP) = 87 : OK

### Device and Model

GA402XZ

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

any (incl. 194)

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@EvilKilla hello, 

You can already do that. Just select anything except `Auto` in Display section (for example 165Hz). After that - you can adjust **refresh rate in windows settings** to anything you want - G-Helper won't be changing it that.

Thanks.
