### ISSUE TITLE
api interface support

### ISSUE THREAD

**Issue by Sam5440** [seerge/g-helper#3229]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

a mini api server。

### Describe the solution you'd like

An api interface to adjust modes and performance curves via external devices and to display device status information via api

### Device and Model

Tianxuan 5 PRO

**Comment by seerge** [comment]
@Sam5440 hello,

You already can switch between performance modes and GPU modes using [special predefined hotkeys](https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings). If you want to adjust fan curves - just create more custom profiles beforehand.

If you want to control app externally - just emit this hotkeys from other application (for example by using Autohotkey app or so)

I don't plan to add any web servers in the app as it's against whole idea of being lightweight and low on resources.

Thanks.
