### ISSUE TITLE
 peripheral support

### ISSUE THREAD

**Issue by Baozaifan778** [seerge/g-helper#3230]
### Mouse / peripheral model and version

keris II ace

### Armoury Crate Screenshots

I have this rog keris II ace but it doesn't show on ghelper for some reason.... Please tell me how can I solve this 

### USB Details

can't understand

**Comment by seerge** [comment]
Closed cause none of requested in template information is provided. 

On a side note : [Keris II Ace is already supported as mentioned in readme](https://github.com/seerge/g-helper?tab=readme-ov-file#mouse-asus-mouse-and-other-peripherals-support). Just connect it over wire to USB to change settings.

Thanks
