### ISSUE TITLE
g-helper settings reset after a restart

### ISSUE THREAD

**Issue by Mb-Az** [seerge/g-helper#3232]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

After **shutting down and starting** my system again ( **ROG, windows 11**) g-helper wouldn't start automatically so I 've added it to startup apps using a shortcut. However, after it starting with the shortcut I have to manually set the settings to what it was before.

### Describe the solution you'd like

Is it possible for it to somehow remember my choices even after shutting down?

### Device and Model

Asus ROG g513rw

**Comment by seerge** [comment]
@Mb-Az hello, G-Helper already saves all it's settings immediately under `%appdata%\GHelper` folder. And reads them on each start.

You don't need to create any special shortcuts for startup. Please just check `Run on startup` checkbox in the app. It will create a correct task with all required permissions pointing to app location.

Thanks

**Comment by Mb-Az** [comment]
Hi, thanks for the quick reply! 
Actually after checking the `Run in startup` it doesn't start so I had to do it another way.
But on another Asus laptop it's working great.

**Comment by seerge** [comment]
@Mb-Az check my added comment : 

If it's not running from startup task by some reason try to place `GHelper.exe`  in a folder that does not require admin permissions to access .

If it still doesn't help - check windows Task Scheduler app, find GHelper task and check it's details. If it's pointing to correct exe location (i.e. you didn't move it somewhere) and if startup task reports any errors or says if it managed to run app.

**Comment by Mb-Az** [comment]
I'll try it, thanks again!
