### ISSUE TITLE
Screenpad issues

### ISSUE THREAD

**Issue by chockokruasan** [seerge/g-helper#3233]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hello, I have 2 issues/questions about screenpad with ghelper. I found out when I change GPU mode from "Ultimate" to "Standard" or back, after restarting touch screen doesnt work on screenpad. It can be fixed in windows Control Panel -> Tablet PC to apply touchscreen features for screenpad display again. It happens every time after changing GPU mode and restarting. I checked several times,  it never happens with Armoury Crate. I see button in AC to on/off touch screen. Maybe it has some functions to activate touch screen after changing GPU mode, but ghelper doesnt?

Also I see that when I change screenpad brightness by fn+shift F7/F8. after restarting screenpad reset brightness to default. Screenxpert software uninstalled.
Maybe other members of Zephyrus duo 16 2023 can confirm same issues?
Thanks!

### How to reproduce the bug?

Change GPU mode from Ultimate to Standard or from Standard/Optimized to Ultimate and restart.

### Logs

no

### Device and Model

Asus Zephyrus duo 16 GX650PZ

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.194

### OS

Windows 11 23H2

**Comment by chockokruasan** [comment]
@seerge 
1. No. 
2. For example. I set brightness by Ghelper for 80%. Restart laptop and the actual brightness on screenpad reseted to 50% after windows logon. I press fn+shift+F8 and brightness set to 90%. Ghelper remembers brightness seted by hotkeys, but after restart windows reset it to 50% until I press fn+shift+F7/F8 or screenpadd ON.

**Comment by seerge** [comment]
@chockokruasan 

On hardware level it's only 2 settings for Screenpad. It's an ON / OFF toggle and Brightness level (both of them you can access via hotkeys in G-Helper). 

If they don't work - it's probably some specific toggle in windows and I'm not aware about any documented way to access them. It is strange that no one else have complained about this (even tho there are a lot of DUO users). Are you sure it's not some windows hiccup ?

You can bind of the macro keys in app to `Toggle Touchscreen` under `Extra` settings (app needs to be running as admin in order for toggle to work). Can you check if that toggle wakes up screenpad controls ?

----

For Screenpad brightness - I can add an init command on app start, setting last remembered brightness. But again - are you sure that it's not something else overriding brightness here ?

**Comment by chockokruasan** [comment]
@seerge I tested on OOBE Windows 11 after removing AC and Screenxpert, I also tested on clean installed Windows 11.

> You can bind of the macro keys in app to Toggle Touchscreen under Extra settings (app needs to be running as admin in order for toggle to work). Can you check if that toggle wakes up screenpad controls ?

I can't check it now because I migrated back to AC at this time and need my laptop for work next weeks. I can check it after finishing work.

> It is strange that no one else have complained about this (even tho there are a lot of DUO users).

How can we ask other Zephyrus duo members here? :) No idea

**Comment by seerge** [comment]
@chockokruasan well, check if any existing action (like toggling touchscreen) can wake up Screenpad.

**Comment by seerge** [comment]
@chockokruasan any updates here ?

**Comment by seerge** [comment]
Closed as abandoned

**Comment by chockokruasan** [comment]
Hello, sorry for delay. Bt binding Toggle Touchscreen is it just turn off touch functions, I need to enable it in Device manager after.
But what about brightness resets after restarting?
I made a short video of issue: https://youtu.be/4RcR7WjgxaI

**Comment by seerge** [comment]
@chockokruasan Toggle Touchscreen disables and also **enables** it in device manager. So my question was if this action somehow wake it up in your case?

**Comment by chockokruasan** [comment]
@seerge no, it doesnt help =(

**Comment by seerge** [comment]
@chockokruasan well, then I'm simply not aware about how to programmatically wake up touchscreen. Are you sure it's not just a windows hiccup in your specific case ? Otherwise it will be others complaining about same thing :)

**Comment by chockokruasan** [comment]
> @chockokruasan well, then I'm simply not aware about how to programmatically wake up touchscreen. Are you sure it's not just a windows hiccup in your specific case ? Otherwise it will be others complaining about same thing :)

I found several users with the same issue, it is fixing by control panel in 3 clicks, but this issue doesnt happen with AC. I think many other users do not use mux switch often or do not use touch screen to notice issue. This is not a big problem. Maybe AC has some functions to apply touchscreen after mux switch I dont know)
