### ISSUE TITLE
Could it possible to integrate a option to enable/disable the sensor monitoring service.

### ISSUE THREAD

**Issue by RichardSK24601** [seerge/g-helper#3234]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Since the rog laptop will automatically disable the keyboard when in a vertical orientation, but sometime I would like to use my laptop while side lying on my bed.

### Describe the solution you'd like

Could it possible to integrate a option to enable/disable the sensor monitoring service.

### Device and Model

ROG flow 13

### Additional information.

Since the rog laptop will automatically disable the keyboard when in a vertical orientation, but sometime I would like to use my laptop while side lying on my bed.

**Comment by seerge** [comment]
@RichardSK24601 hello, this is handled purely by windows and firmware - G-Helper can't do that :) Sorry.
 
Why don't you just disable tablet mode in windows directly ? I will do the thing.

Thanks
