### ISSUE TITLE
Fan minimum speed hardcoded @ 1800rpm

### ISSUE THREAD

**Issue by svensvond** [seerge/g-helper#3235]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Fans cant be set lower than 1800rpm

### Describe the solution you'd like

i would like to set the fans in a range from starting at 800 rpm, which hardware wise is possible.
There is no reason beeing able to set the fans to 0rpm up to 70° but not beeing able to set the fans to 1000rpm @ 65 °C.
A quick look at the code reveals that this might be the line to change: DEFAULT_FAN_MIN = 18 / FanSensorControl.cs.
Can we make the min value configurable?

### Device and Model

ASUS G713PV

**Comment by seerge** [comment]
@svensvond hello, 

You can't do that in a normal way. Fan curve is set in percentage points, where 0% is OFF, and 1% is immediately 1600-2000RPM (depending on the model)

`DEFAULT_FAN_MIN` is for Y-axis labels in fan curve editor, so app can show that 1% is 1800RPM. It does not define actual fan speeds.

If you want more freedom - you can try E[xperimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272). There G-Helper directly sets fan speeds (still in %, but via different method) and you can try to set speed lower. Check readme on that page.

Thanks

**Comment by svensvond** [comment]
Great, thanks.
That does work actually.
For future development: Cant that be merged into main branch?

**Comment by seerge** [comment]
@svensvond Glad to hear. I don't plan to mix it up with a mainstream for now :)

**Comment by svensvond** [comment]
I see. Would it be an option to make this implementation a branch at least? 
Wonderung how the source looks like.
Iam asking because its the only working one mor me - at least if you need a range between 0 and 1800rpm.
