### ISSUE TITLE
XGMob with the latest version

### ISSUE THREAD

**Issue by bsaksham** [seerge/g-helper#3237]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hello sir!

I have X13 2021 version with xgmob 3080. It gets connected easily with Ghelper, but the lights and fans for XGMobile does not turns up, not even at a higher temperature. 

### How to reproduce the bug?

1. Connect the XG Mobile
2. Turn on the Lock on XG Mobile
3. Switch to XGMob from Ghelper
4. After the lights on lock turns on to red from white
5. The lights and fans on XG Mobile stops. 

### Logs

[log.txt](https://github.com/user-attachments/files/17284655/log.txt)

### Device and Model

ROG Flow X13

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.194

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@bsaksham hello, 

Fans on XG Mobile (same as on laptop itself) are controlled by firmware, not by the app.
How does it behave when you activate XG Mobile via Armoury ?

As for backlight on XGM, i see that you have turned it off under `Extra` settings. Check XGM backlight ON there and it should turn ON :)

**Comment by seerge** [comment]
@bsaksham any updates here ?

**Comment by bsaksham** [comment]
Hello @seerge,

Thanks a lot sir, that was helpful. I was dumb enough not to see the button for XG Mobile in extras.

Fans are now working, all i did was removed G-Helper, installed AC and then uninstalled it using the Asus uninstaller, and then did a clean setup for G-Helper and BOOM they work! 

Just a suggestion, if you can add a little more description in the Extras for XG Mobile. Instead of XG Mobile it could say Fan Light XG Mobile. 

That was all, your help is appreciated. 
Keep up the good work!
Great day to you :)

**Comment by seerge** [comment]
@bsaksham XGM checkbox is under `Backlight` section (same as all other backlight checkboxes). So I think it's good as is.

I'm glad it's working now.
