### ISSUE TITLE
Power Plan inconsistency

### ISSUE THREAD

**Issue by CommicKick69ing** [seerge/g-helper#3245]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The Power plan featured in Control Panel and G-helper are not the same and every time I seek to correct the power plan in g-helper it resets itself to "Balanced"

### How to reproduce the bug?

1. Open **Fans + Power**
2. Change **Windows Power Plan** from **Balanced** to **Best Performance**
3. Click **X** to close the **Fans + Power**
4. Reopen **Fans + Power**
5. **Windows Power Plan** is reset from **Best Performance** to **Balanced** 
6. Check **Control Panel > Power Plan**, **High Performance** is still the default power plan

### Logs

\\.\DISPLAY1\Monitor0
10/9/2024 9:38:25 PM: LQ140M1JW46 HDR: False 8 8 False
10/9/2024 9:38:25 PM: Init 1866: 5D-B9
10/9/2024 9:38:25 PM: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
10/9/2024 9:38:25 PM: Init 1866: 5D-05-20-31-00-1A
10/9/2024 9:38:25 PM: USB 1866: 5D-BD-01-FF-1F-FF-FF-FF
10/9/2024 9:38:25 PM: AuraMode: AuraStatic
10/9/2024 9:38:25 PM: USB 1866: 5D-B3-00-00-FF-00-00-EB-00-00-FF-00-00-00-00-00-00
10/9/2024 9:38:25 PM: USB 1866: 5D-B5-00-00-00
10/9/2024 9:38:25 PM: USB 1866: 5D-B4
10/9/2024 9:38:25 PM: WMI event 123
10/9/2024 9:38:26 PM: Auto 1866: 5D-BA-C5-C4-01
10/9/2024 9:38:26 PM: STAPM: 60 OK
10/9/2024 9:38:26 PM: STAPM2: 60 OK
10/9/2024 9:38:26 PM: SLOW: 60 OK
10/9/2024 9:38:26 PM: FAST: 60 OK
10/9/2024 9:38:31 PM: WMI event 207
10/9/2024 9:38:31 PM: WMI event 88
10/9/2024 9:38:31 PM: AutoSetting for Online
10/9/2024 9:38:31 PM: Input available: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} 1866 64
10/9/2024 9:38:31 PM: USB 1866|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
10/9/2024 9:38:31 PM: Input: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
10/9/2024 9:38:31 PM: Power Plan 381b4222-f694-41f0-9685-ff5bb260df2e:87
10/9/2024 9:38:31 PM: Mode = 1 : OK
10/9/2024 9:38:31 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> ded574b5-45a0-4f42-8737-46345c09c238:OK
10/9/2024 9:38:31 PM: Eco flag : -65536
10/9/2024 9:38:31 PM: Mux flag : -65536
10/9/2024 9:38:31 PM: \\?\DISPLAY#SHP14F1#5&1ed628fe&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
10/9/2024 9:38:31 PM: \\?\DISPLAY#SHP14F1#5&1ed628fe&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
10/9/2024 9:38:31 PM: LQ140M1JW46 HDR: False 8 0 False
10/9/2024 9:38:31 PM: Init 1866: 5D-B9
10/9/2024 9:38:31 PM: Init 1866: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
10/9/2024 9:38:31 PM: Init 1866: 5D-05-20-31-00-1A
10/9/2024 9:38:31 PM: USB 1866: 5D-BD-01-FF-1F-FF-FF-FF
10/9/2024 9:38:31 PM: AuraMode: AuraStatic
10/9/2024 9:38:31 PM: USB 1866: 5D-B3-00-00-FF-00-00-EB-00-00-FF-00-00-00-00-00-00
10/9/2024 9:38:31 PM: USB 1866: 5D-B5-00-00-00
10/9/2024 9:38:31 PM: USB 1866: 5D-B4
10/9/2024 9:38:31 PM: WMI event 123
10/9/2024 9:38:32 PM: Auto 1866: 5D-BA-C5-C4-01
10/9/2024 9:38:32 PM: GET GPU CLOCKS: 0, 0
10/9/2024 9:38:32 PM: GET CLOCK LIMIT: 0
10/9/2024 9:38:32 PM: STAPM: 60 OK
10/9/2024 9:38:32 PM: STAPM2: 60 OK
10/9/2024 9:38:32 PM: SLOW: 60 OK
10/9/2024 9:38:33 PM: FAST: 60 OK
10/9/2024 9:39:02 PM: LQ140M1JW46 HDR: False 8 0 False
10/9/2024 9:39:05 PM: Listener stopped
10/9/2024 9:39:24 PM: LQ140M1JW46 HDR: False 8 0 False
10/9/2024 9:39:36 PM: LQ140M1JW46 HDR: False 8 0 False
10/9/2024 9:39:37 PM: GET GPU CLOCKS: 0, 0
10/9/2024 9:39:37 PM: GET CLOCK LIMIT: 0
10/9/2024 9:45:54 PM: LQ140M1JW46 HDR: False 8 0 False
10/9/2024 9:45:56 PM: GET GPU CLOCKS: 0, 0
10/9/2024 9:45:56 PM: GET CLOCK LIMIT: 0
10/9/2024 9:45:59 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> ded574b5-45a0-4f42-8737-46345c09c238:OK

### Device and Model

ROG Zephyrus G14 GA401

### Additional information.

<img width="760" alt="Capture" src="https://github.com/user-attachments/assets/bae25401-1973-4511-bb15-41cfe62f54c3">

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.194

### OS

Windows 10 Home

**Comment by seerge** [comment]
@CommicKick69ing hello, 

This is absolutely intentional as app uses [Balanced power plan](https://github.com/seerge/g-helper/wiki/Requirements#recommendations-optional) by default and switches between [3 Power Modes instead](https://github.com/seerge/g-helper?tab=readme-ov-file#rocket-performance-modes). Power modes may not exist in custom plans.

But you can override that if you really want to use other power plan (like High Performance). [Check readme on how to do that ](https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-windows-power-plans-with-each-mode). Keep in mind, that you need to set custom power plan GUID for each mode you use.

Thanks.

**Comment by CommicKick69ing** [comment]
> @CommicKick69ing hello,
> 
> This is absolutely intentional as app uses [Balanced power plan](https://github.com/seerge/g-helper/wiki/Requirements#recommendations-optional) by default and switches between [3 Power Modes instead](https://github.com/seerge/g-helper?tab=readme-ov-file#rocket-performance-modes). Power modes may not exist in custom plans.
> 
> But you can override that if you really want to use other power plan (like High Performance). [Check readme on how to do that](https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-windows-power-plans-with-each-mode). Keep in mind, that you need to set custom power plan GUID for each mode you use.
> 
> Thanks.

Just tried out the solution given but ghelper not only still resets the power plan but resets the .json even after saving

**Comment by CommicKick69ing** [comment]
> @CommicKick69ing then it means you are not maintaining json structure (for example missing comma in the end of each line except last)
> 
> Easiest way to add new lines - is to add them to the beginning of the file. Check [general notes in power user settings](https://github.com/seerge/g-helper/wiki/Power-user-settings#general-note)

That is what I've done as far as I can tell
<img width="818" alt="Capture" src="https://github.com/user-attachments/assets/a569a76e-b030-42e9-bd7d-04baf5073720">

**Comment by seerge** [comment]
@CommicKick69ing it looks legit, but you need to quit app before saving config (as mentioned in readme), or it will override it. It reads config only on start.

**Comment by CommicKick69ing** [comment]
That is what I did. I quit out of ghelper, made the changes to .json, saved, restarted my laptop, reopened ghelper, power plan was still on balanced

**Comment by seerge** [comment]
@CommicKick69ing can you upload your config here ? You don't need to restart laptop, just starting app again after saving `config.json` is enough.

**Comment by CommicKick69ing** [comment]
I also di that too just quiting, editing, saving, reopening but that did not work either

{
  "performance_mode": 1,
  "start_count": 16,
  "clamshell_default_lid_action": 2,
  "performance_0": 0,
  "gpu_mode": 1,
  "internal_display": "LQ140M1JW46",
  "screen_max": 120,
  "max_frequency": 120,
  "frequency": -1,
  "overdrive": -65536,
  "charge_full": 0,
  "performance_1": 1,
  "mid_fan": 0,
  "xgm_fan": 0,
  "fan_profile_cpu_0": "14-30-33-36-39-3D-41-62-0B-10-13-17-1C-28-2F-35",
  "fan_profile_gpu_0": "14-30-33-36-39-3D-41-62-0E-15-19-1C-22-2C-33-3D",
  "limit_total_0": 60,
  "limit_slow_0": 60,
  "limit_cpu_0": 59,
  "limit_fast_0": 80,
  "auto_apply_power_0": 1,
  "auto_boost_0": 0,
  "powermode_0": "ded574b5-45a0-4f42-8737-46345c09c238",
  "fan_profile_cpu_1": "14-32-37-3C-41-46-4B-62-12-17-1C-23-28-2D-35-3E",
  "fan_profile_gpu_1": "14-32-37-3C-41-46-4B-62-19-1C-22-28-2C-31-3D-46",
  "limit_total_1": 60,
  "limit_slow_1": 60,
  "limit_cpu_1": 60,
  "limit_fast_1": 80,
  "auto_apply_power_1": 1,
  "auto_boost_1": 0,
  "fan_profile_cpu_2": "14-2C-2F-32-35-38-3C-62-07-0B-0E-10-13-17-1C-23",
  "fan_profile_gpu_2": "14-2C-2F-32-35-38-3C-62-0B-0E-12-15-19-1C-22-28",
  "limit_total_2": 60,
  "limit_slow_2": 60,
  "limit_cpu_2": 80,
  "limit_fast_2": 80,
  "powermode_2": "ded574b5-45a0-4f42-8737-46345c09c238",
  "auto_apply_power_2": 1,
  "scheme_0": "b7a7582d-a660-43ae-87a6-db1d929387bc",
  "scheme_1": "b7a7582d-a660-43ae-87a6-db1d929387bc",
  "scheme_2": "b7a7582d-a660-43ae-87a6-db1d929387bc",
  "donate_click": 1
}

**Comment by seerge** [comment]
@CommicKick69ing does the config stay same after you launch app? Can you upload app log here ?

Your power pan GUID `b7a7582d-a660-43ae-87a6-db1d929387bc` doesn't seem to be standard, where did you get it ?
You can get GUIDs of all available power plans by running `powercfg /l` in powershell.

**Comment by CommicKick69ing** [comment]
> @CommicKick69ing does the config stay same after you launch app? Can you upload app log here ?
> 
> Your power pan GUID `b7a7582d-a660-43ae-87a6-db1d929387bc` doesn't seem to be standard, where did you get it ? You can get GUIDs of all available power plans by running `powercfg /l` in powershell.

The .json does stay the same after I launch ghlper. 
The power plan came premade in the laptop
Log:https://pastebin.com/KyAv0k6B

<img width="516" alt="Capture" src="https://github.com/user-attachments/assets/049a91bf-1dae-4a58-b83b-54b288a6247b">

**Comment by seerge** [comment]
@CommicKick69ing ok, but from the log app sets both **power plan** to your custom plan and **power mode** to best performance : 

```
10/10/2024 4:59:49 PM: Power Plan b7a7582d-a660-43ae-87a6-db1d929387bc:OK <--- CUSTOM POWER PLAN
10/10/2024 4:59:49 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> ded574b5-45a0-4f42-8737-46345c09c238:OK <--- BEST PERFORMANCE
```

- So power plan in control panel should be yours (can you check now after starting app) ?
- As for power mode - some custom power plans may lock power modes in windows (that's one of the reasons G-Helper by default users `Balanced` power plan)

**Comment by CommicKick69ing** [comment]
Yes, the power plan in control panel still remain on "High Performance" even after starting ghelper
<img width="619" alt="Capture" src="https://github.com/user-attachments/assets/73e8f2c2-7424-4e92-ab0e-0397c25ada2f">
Will ghelper resetting my power plan to balanced will that negatively affect my performance?
No I can not I can not change power mode in windows settings directly 
<img width="850" alt="1" src="https://github.com/user-attachments/assets/49307fc8-de39-46a2-aba0-00c0b4c86b69">

**Comment by seerge** [comment]
@CommicKick69ing 

> Yes, the power plan in control panel still remain on "High Performance" even after starting ghelper

Then everything works as it should, congratulations :)

> Will ghelper resetting my power plan to balanced will that negatively affect my performance?

No, as in modern windows power modes substitute old fashioned power plans, and they can be changed in G-Helper

> No I can not I can not change power mode in windows settings directly

Then as I mentioned custom power plan just prevents power mode from changing (so windows simply falsely reporting it as "balanced" power mode, while in reality it's locked by plan)

**Comment by CommicKick69ing** [comment]
Thank you for working with me to clear this situation up it is extremely appreciated

**Comment by seerge** [comment]
@leftedz because it allows maximum flexibility in terms of choosing what really matters in windows - Power Modes

**Comment by leftedz** [comment]
I see, but do you think it will in any way affect performance of games if i do the same thing OP did?

**Comment by seerge** [comment]
@leftedz on AMD devices it doesn't seem to do anything, on some old Intel devices it might add a bit higher score for CPU-heavy tasks (like CPU benchmarks) at a cost of constantly higher clocks.

**Comment by leftedz** [comment]
Thank you yet again for clarification!
