### ISSUE TITLE
Showing remaining Wh instead of charge percentage

### ISSUE THREAD

**Issue by LavenderFela** [seerge/g-helper#3246]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

It is difficult to estimate remaining battery life when looking at G-Helper, especially when battery health changes.

Example: seeing 50% battery means 38Wh remaining (at 100% health), 30.4Wh (at 80% health). Seeing discharge rate (e.g. 12W) gives a rough idea of discharge.

### Describe the solution you'd like

Possibility to see remaining actual Wh instead of percentage and taking into account the battery health. Rough formula:
remaining Wh = design capacity * battery health * battery percentage, or, if laptop provides, remaining Wh.

This could be similarly to RPM vs. fan percentage - swapping on the click.

### Describe alternatives you've considered

I was using HWINfo's tray icon for that, found it quite useful.

### Device and Model

Asus ROG Zephyrus G14 GA402

**Comment by seerge** [comment]
@LavenderFela hello, 

That's possible but click on a charge label is already reserved for opening a Battery Report. And mouse-over is reserved for showing battery health.

Any other ideas where you would like to add it ?

**Comment by LavenderFela** [comment]
That's a great point, thank you! What about then changing discharge/charging indicator text on click?

Default: _Discharging: 10.1W_
Swapped on click: _Discharging 10.1W/36.12Wh_

Default charging: _Charging: 50.8W_
Charging and swapped on click: _Charging 50.8W/56.28Wh_

Default fully charged: no text.
Fully charged and swapped on click: _Charged, 60.8Wh_

**Comment by seerge** [comment]
@LavenderFela i think it will make whole thing even more complicated, I have tried to squeeze charge in Wh into existing label.

Try this build
[GHelper.zip](https://github.com/user-attachments/files/17342087/GHelper.zip)

**Comment by LavenderFela** [comment]
Oh yeah, that gets way too tight; thank for the build!

I've mocked up a different idea, which changes white "Charging ..." text part in Photoshop. It looks less cluttered, but also might be confusing, since it doesn't mean actually mean (dis)charging rate, rather than current battery charge.

![Default](https://github.com/user-attachments/assets/8f557777-9991-44e0-8b34-25d041429e33)
![Swapped](https://github.com/user-attachments/assets/a016776b-e12a-46df-a185-dd991722b148)

**Comment by LavenderFela** [comment]
Yup, I've been looking at it now myself, and it looks a bit overwhelming... I guess, we could call it quits here; if anything, might need to learn how to build the app and add it just for myself.

That being said, thank you for your time! Love G-Helper for daily life, grateful for all the time and effort you (and community) put into it.

**Comment by seerge** [comment]
@LavenderFela ok, try this build.

I have made that click on **discharge / charge** label toggles between % and Wh reading. It's a bit confusing (cause it changes value on neighbor label), but that's best I can come up with atm

[GHelper.zip](https://github.com/user-attachments/files/17345022/GHelper.zip)

**Comment by seerge** [comment]
Live in https://github.com/seerge/g-helper/releases/tag/v0.196

**Comment by LavenderFela** [comment]
I'm terribly sorry for forgeting to come back to this, but thank you so much! Makes the app much more convenient for me at university lectures, no longer have to take into account 80% battery life when counting actual capacity.
