### ISSUE TITLE
GPU mode not available

### ISSUE THREAD

**Issue by Toaster152** [seerge/g-helper#3248]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I just downloaded g-helper on my ASUS TUF Gaming A16 Advantage Edition FA617 with the hope of using the eco mode GPU setting to boost the terrible battery life. I assume that this is a fairly modern laptop so should I have the option to put my laptop into eco mode? Im quite despperate at this stage as ive heard eco mode can double your battery life, im only getting 3 hours when im apparently supposed to be getting 12
![image_2024-10-11_020759965](https://github.com/user-attachments/assets/8931c5c4-54aa-4c42-ac49-4527134d6487)

### How to reproduce the bug?

open app

### Logs

[log.txt](https://github.com/user-attachments/files/17336045/log.txt)

### Device and Model

ASUS TUF Gaming A16 Advantage Edition FA617 

### Armoury Crate

Uninstalled

### OS

windows 11

**Comment by seerge** [comment]
@Toaster152 hello, 

It looks like you have broken or missing Asus System Control Interface driver. As your BIOS responds with zeroes or nonsense to any communication (including a check for Eco mode)
```
16/7/2024 13:47:01: Eco flag : -65536
16/7/2024 13:47:01: Mux flag : -65536
16/7/2024 13:47:01: Mode = 1 : 0
```

Try to do [hard reset ](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset) and reinstall [Asus System Control Interface](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-asus-system-control-interface)

Thanks

**Comment by seerge** [comment]
@Toaster152 P.S. I have scrolled your log further, and you had your Asus System Control interface working before

Last time on 10/7/2024 
```
10/7/2024 16:18:32: Mode = 0 : OK
```

After that something has changed on your device (windows update or any other changes you did manually) and it stopped working.

**Comment by seerge** [comment]
@Toaster152 any updates here ?

**Comment by Toaster152** [comment]
@seerge  sorry for late reply, wont be able to try this until Sunday evening, will let you know how it goes

**Comment by Toaster152** [comment]
> @Toaster152 any updates here ?

I did what you told me to do, nothing has changed but when I reinstalled  the Asus system control interface this message popped up. 

![image_2024-10-15_182921692](https://github.com/user-attachments/assets/79ea15d2-028a-48e4-8379-9fa5cc330082)

**Comment by seerge** [comment]
@Toaster152 hello,

If Asus Control Interface is not installing properly - it means that something is wrong with the device. Without it neither Armoury nor G-Helper won't work, as it gives access to all main functionality.

If hard reset didn't change anything, try to load to BIOS menu (`F2` on boot) and load all defaults there. And after that reinstall Asus Control interface again. 

Does it change something ?

**Comment by Toaster152** [comment]
@seerge 
I got the same message when downloading Asus Control Interface, any chance this could be fixed with a factory reset?  might try loading the BIOS menu and download it again

**Comment by seerge** [comment]
@Toaster152 is it after resetting BIOS to defaults as well? Can you check windows Device Manager, if there is any unknown / broken (yellow triangle) devices there ?

You can try factory reset of course :) but i'm not sure if this is related.

**Comment by Toaster152** [comment]
@seerge 
yeah its after resetting BIOS to default, there doesnt seem to be anything wrong with device manager either.

**Comment by seerge** [comment]
@Toaster152 ok, it's strange. But since Asus Control interface is refusing to install - apps won't work either. 

I don't have any other ideas, sorry. You can try factory reset in case it's some strange windows hiccup :)

**Comment by Toaster152** [comment]
> @Toaster152 ok, it's strange. But since Asus Control interface is refusing to install - apps won't work either.
> 
> I don't have any other ideas, sorry. You can try factory reset in case it's some strange windows hiccup :)

Thanks for the help, ill try factory reset. Atleast everything else seems to work fine

**Comment by seerge** [comment]
@Toaster152 i don't think so, do I understand correctly that Armoury also can't change GPU modes (anymore) ? 

You can try to completely uninstall it [using official uninstaller](https://dlcdnets.asus.com/pub/ASUS/mb/14Utilities/Armoury_Crate_Uninstall_Tool.zip?model=armoury%20crate), but most likely it won't make any difference.

**Comment by seerge** [comment]
@Toaster152 did you manage to do a windows factory reset ?

**Comment by RevDonz** [comment]
Any update here? I have the same problem

![image](https://github.com/user-attachments/assets/e75807a9-56c1-4dff-9b70-5d7ba5df4859)

**Comment by seerge** [comment]
@RevDonz I don't think your case is same :) You have a very old device that simply does not support disabling of iGPU in a first place https://www.asus.com/laptops/for-gaming/tuf-gaming/asus-tuf-gaming-a15/techspec/  . So options that you see - are correct.

**Comment by seerge** [comment]
Since there is no response from issue starter, i assume this is not relevant anymore. 

After all as I have explained problem is in Asus Control Interface that stopped working by some unknown reasons (firmware or windows?) and not in the app.

So closing as abandoned.
