### ISSUE TITLE
ghelper window not opening up when pressing button its assigned to in keybinding when ally x boots up

### ISSUE THREAD

**Issue by jango2700** [seerge/g-helper#3249]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I'm checking "run at startup" box on ghelper but not getting any response from ghelper when I press my shortcut buttons on my ally X. helper is on the taskbar but shortcut buttons I set are not working I have to double click on desktop ghelper icon to get it to work

### How to reproduce the bug?

set "run on startup'
set shortcut buttons in keybinding section using ROG button to open ghelper window 
shutdown device 
power on device 
when on desktop pressing ROG button does not open ghelper window

### Logs

[log.txt](https://github.com/user-attachments/files/17337142/log.txt)

### Device and Model

Asus ROG ally X

### Armoury Crate

Uninstalled

### Asus Services

I uninstalled my Asus 

### Version

0.194.0

### OS

windows 11 23h2

**Comment by seerge** [comment]
@jango2700 hello,

- Does it happens on you when app runs on startup or also if you start it manually?
- Does binding other button (like command center) to toggle G-Helper window work ?
- Can you upload a screenshot of your `Extra` settings?

**Comment by jango2700** [comment]
> @seerge hello,
> 
> * Does it happens on you when app runs on startup or also if you start it manually?  only on startup
> * Does binding other button (like command center) to toggle G-Helper window work ? no , shortcut keybind buttons do not work at all until I manually load g helper
> * Can you upload a screenshot of your `Extra` settings? 
![Screenshot 2024-10-11 113648](https://github.com/user-attachments/assets/cad6325f-d00f-4455-b265-d3a6b317789f)

**Comment by seerge** [comment]
@jango2700 ok, can you run app as admin and then uncheck and check again `Run on Startup` checkbox. It will re-create startup task in Task Scheduler in case something was wrong with it and see if it helps?

**Comment by jango2700** [comment]
@seerge 

ran ghelper as administrator unchecked and checked "run at startup" still the same issue when shutdown and power on ally x :(

**Comment by seerge** [comment]
@jango2700 ok,

Can you try to run windows Task Scheduler, find GHelper task there, open it's settings and add like a 5 seconds delay to start ?

My idea to check if windows prevents main window somehow from showing, if app starts immediately, so delay may help

**Comment by jango2700** [comment]
@seerge 

unfortunately that did not fix it I also tried this last night thinking it might fix it but it didn't change anything

**Comment by seerge** [comment]
@jango2700 ok, strange. 

How exactly do you run app manually ? Do you click on a tray icon (i.e. open already running app) or launch a new app from desktop shortcut (that would kill existing process and run a new one ) ?

Can you try following : manually delete all startup tasks from Task Scheduler, then start G-Helper **not as admin** and check `Run on Startup` and see if it changes something ?

**Comment by jango2700** [comment]
@seerge  

I deleted ghelper startup task from task scheduler rechecked box still no keybind function. ghepler is on my desktop I just double click to restart process, when I boot to desktop ghelper is in Taskbar but it almost seems like controls are not active I have to use touch screen to restart ghelper process sometimes because the mouse cursor doesn't show up. most of the time the mouse does work on boot up

**Comment by seerge** [comment]
@jango2700 ok, can you try this build (make sure to replace existing GHelper.exe with this one, so it runs on startup instead). And post a log.

[GHelper.zip](https://github.com/user-attachments/files/17354909/GHelper.zip)

**Comment by jango2700** [comment]
@seerge 

well, that release seems to have worked! function restored at boot up! thank you!
here's the log you requested 
[log 2.txt](https://github.com/user-attachments/files/17355953/log.2.txt)

**Comment by seerge** [comment]
@jango2700 ok, great

Apparently due to some underlying hardware / firmware issue input controller dropped connection with the app if it starts too early after boot. I have added an option to restart connection up to 3 times in such situations

```
10/13/2024 7:15:14 AM: Listener exited: Operation failed after some time.
10/13/2024 7:15:14 AM: Restarting listener 1
```
