### ISSUE TITLE
Optimized mode not automatically switching to Eco mode on startup on 2022 G14

### ISSUE THREAD

**Issue by xzvs** [seerge/g-helper#3252]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I shut off my laptop in Optimized mode plugged into AC power, it's in iGPU + dGPU mode. But after I unplug it and start it up again, (fast startup is disabled) GHelper shows the laptop is in optimized GPU mode but it's still on iGPU + dGPU mode on battery. It does not switch to Eco automatically anymore, and it stays that way until I manually swap to Eco. How would I fix this? It was working normally a few weeks ago.

2022 G14 GA402RJ, Ryzen 9 6900HS, RX 6700s

### How to reproduce the bug?

1. Plug in laptop while powered on, set GHelper to Optimized. Make sure it shows iGPU + dGPU mode.
2. Shut laptop off
3. Unplug laptop 
4. Power laptop on while unplugged still
5. Observe that GHelper does not automatically switch to iGPU Only, and continues displaying iGPU + dGPU mode. The dGPU is still enabled in Task Manager performance tab.

### Logs

[log.txt](https://github.com/user-attachments/files/17345698/log.txt)

### Device and Model

Asus Zephyrus G14 GA402RJ

### Additional information.

G14 BIOS 319
AMD Chipset 1.2.0.119
AMD Graphics Driver 31.0.12024.2005
ASUS System Control Interface v3 3.1.37.0

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.194.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@xzvs hello, I see that `Eco` command is rejected by firmware by some reason

```
10/11/2024 12:09:12 PM: AutoSetting for Offline
10/11/2024 12:09:12 PM: BatteryLimit = 80 : OK
10/11/2024 12:09:12 PM: GPU usage: AMD Radeon RX 6700S 0%
10/11/2024 12:09:12 PM: Running eco command 1 <--- IT TRIES TO SET ECO
10/11/2024 12:09:12 PM: Mode = 2 : OK
....
10/11/2024 12:09:32 PM: GPUEco = 1 : 0 <----- ECO FAILS
```

And it happens not only in `Optimized` mode, but also when you manually press `Eco`, so something is preventing it from doing so.

Try to : 
- do [hard reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset)
- reinstall [AMD drivers](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers) using DDU, cause it could be driver preventing GPU from disabling

Thanks

**Comment by xzvs** [comment]
> @xzvs hello, I see that `Eco` command is rejected by firmware by some reason
> 
> ```
> 10/11/2024 12:09:12 PM: AutoSetting for Offline
> 10/11/2024 12:09:12 PM: BatteryLimit = 80 : OK
> 10/11/2024 12:09:12 PM: GPU usage: AMD Radeon RX 6700S 0%
> 10/11/2024 12:09:12 PM: Running eco command 1 <--- IT TRIES TO SET ECO
> 10/11/2024 12:09:12 PM: Mode = 2 : OK
> ....
> 10/11/2024 12:09:32 PM: GPUEco = 1 : 0 <----- ECO FAILS
> ```
> 
> And it happens not only in `Optimized` mode, but also when you manually press `Eco`, so something is preventing it from doing so.
> 
> Try to :
> 
> * do [hard reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset)
> * reinstall [AMD drivers](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers) using DDU, cause it could be driver preventing GPU from disabling
> 
> Thanks

Hi, I have reinstalled the graphics drivers with DDU and also hard reset it. However, the logs are still showing GPUEco = 1 : 0.
Is there any alternative solution to this? Thank you!

**Comment by seerge** [comment]
@xzvs well, it looks more like some firmware hiccup, cause GPU toggle is just an ON / OFF command.

If you will scroll through your log you will see some `Eco` commands are actually working (even last record in a log) `10/11/2024 12:10:36 PM: GPUEco = 1 : OK`, but others are refused.

Also sometimes performance mode command, or battery charge limit command is also refused
```
10/11/2024 7:59:37 AM: BatteryLimit = 80 : 0
10/11/2024 7:59:37 AM: Eco flag : -65536
10/11/2024 7:59:37 AM: Mux flag : -65536
10/11/2024 7:59:37 AM: Mode = 2 : 0
```

- Do you have anything unusual that can prevent GPU from turning off ? 
- External monitor connected, some app running and using it ?
- Do you have any pattern when this happens?

Try to [reinstall Asus System Control interface](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-asus-system-control-interface) ?

**Comment by seerge** [comment]
@xzvs P.S. You also seem to use USB-C charger ? Try the barrel plug may be ?

**Comment by seerge** [comment]
@xzvs 

- Do you have fast boot enabled or disabled in BIOS (F2 on boot) ? Try to switch it to opposite
- I see that you have "ASUSSmartDisplayControl" installed (app kills it's process on start or it will interfere with refresh rates). Can you try to uninstall it completely ?
- Do you have anything else from asus running ? Leftovers from armoury crate mb ?

**Comment by xzvs** [comment]
@seerge 
I have tried replicating the issue with fast boot enabled and fast boot disabled in UEFI, it is the same for both.
Just tried uninstalling ASUS smart display control, also doesn't work.
How would I check for leftover armoury crate things? I already uninstalled it with the tool.

**Comment by seerge** [comment]
@xzvs then there is no leftovers if you used official uninstaller. 

Can you try to replicate this manually :
1. Set GPU mode to Standard (not to Optimized)
2. Shutdown, unplug as usual
3. Boot and as soon as windows starts - try to set Eco manually

- Would it fail then?
- Do you actually shutdown laptop or put it to hibernate btw ?

If the problem is that Eco is launched too fast - you can try to delay G-Helper start by opening windows Task Scheduler, finding GHelper task there and modifying it settings to run like 10 seconds after logon instead of immediately for example

**Comment by xzvs** [comment]
@seerge 

Oh wow, you are right. It does indeed not swap to eco - I manually changed it and it reverted back to Eco 0. 
However, in Task Scheduler, it returns an error: 
![image](https://github.com/user-attachments/assets/d8adacd4-e7d7-4417-b53f-ac2dd0e12c49)
Please help! This does seem to be the issue with GHelper.

**Comment by seerge** [comment]
@xzvs if same command does not work on device start, but works like 20 seconds later it's not an issue with G-Helper, it's an issue with a firmware that handles it :)

Where exactly did you get that error ? It comes from TaskScheduler according to title. 
You just need to edit existing task called GHelper and adjust delay (it already has a delay of 1 second i think)

![image](https://github.com/user-attachments/assets/7c0fa5a9-5171-4e90-9cc7-8217ee7e74b8)

**Comment by xzvs** [comment]
@seerge 
I cannot edit the task, it returns the error as soon as I click the "OK" button. It returns the error even if I do not modify anything as well.

**Comment by seerge** [comment]
@xzvs try to run Task Scheduler as admin

**Comment by xzvs** [comment]
@seerge 

Thank you, it worked to change the task. However, now the issue is that GHelper won't even start on startup.

**Comment by seerge** [comment]
@xzvs did you adjust only delay ? or something else ? :)

**Comment by xzvs** [comment]
@seerge 
Yes, only delay. Then it won't start up again.

**Comment by seerge** [comment]
@xzvs then it's something wrong with the startup task, try to recreate it from scratch by unchecking / checking run startup checkbox.

**Comment by xzvs** [comment]
@seerge 
I tried, and the startup task created by default works. However, I cannot modify it even with administrator Task Scheduler. It is not these 2 files locking the task in task scheduler?
![image](https://github.com/user-attachments/assets/127e0c40-cfac-4a82-9643-1e40a52e6879)

**Comment by seerge** [comment]
@xzvs no, those files have nothing to do with editing startup task. Furthermore startup task is a function of windows and task scheduler, not G-Helper.

Try to restart task scheduler

**Comment by xzvs** [comment]
@seerge 

Solved it! Apparently it's a really old windows issue from 2016. To edit, first I have to type the path my user account is in under "User account". It only shows up as the username initially, which is why I couldn't change the task.

Well, now it's fixed. It auto switches after about 20 seconds. Thank you so much for helping! Really appreciate it.

**Comment by seerge** [comment]
@xzvs ok, great and glad to hear

**Comment by VincentPostmus** [comment]
Hi @seerge recently came across Ghelper and it's given my 2021 G15 a new lease of life, thank you! I'm running into the same issue of booting on battery and the dGPU not switching off automatically (GPU mode is set to 'Optimised'). I've tried the solution above to delay the start of Ghelper by 20 or more seconds but when it then launches it doesn't turn the dGPU off. If I plug in the charger and then plug it out, that does turn off the dGPU. Any other advice would be much appreciated! Thanks.

**Comment by seerge** [comment]
@VincentPostmus hello, can you upload the log from `%apppdata%\GHelper` folder to see what actually happens when app tries to turn `Eco` mode on ?

**Comment by VincentPostmus** [comment]
Thanks for the quick reply @seerge, sure! I'm not super technical so let me know if this is not what you meant.

[log.txt](https://github.com/user-attachments/files/18783447/log.txt)

**Comment by seerge** [comment]
@VincentPostmus thanks,

In a log i see that every single time app tried to turn dGPU off, it worked just fine. It looks like this in a log
```
13/02/2025 09:33:03: ------------
13/02/2025 09:33:04: App launched: ROG Zephyrus G15 GA503QM_GA503QM :0.202.0.0en-GB.
13/02/2025 09:33:04: Start Count: 140
13/02/2025 09:33:11: NVIDIA GeForce RTX 3060 Laptop GPU
13/02/2025 09:33:13: CPU: 7 - AMD Ryzen 7 5800HS with Radeon Graphics          - AMD64 Family 25 Model 80 Stepping 0
13/02/2025 09:33:13: AutoSetting for Offline  <--- You have started app, laptop is off the charger
....
13/02/2025 09:33:22: GPUEco = 1 : OK <---- OK means that firmware confirms it worked
...
13/02/2025 09:33:23: Eco flag : 1 <---- firmware says ECO mode is on now

```

Why did you decide that it's not turning your GPU off ?

**Comment by VincentPostmus** [comment]
@seerge I took a screenshot of what the system looks like right after a boot on battery (like 3 mins after booting, and having shut down on power with dGPU on):

![Image](https://github.com/user-attachments/assets/72313ff2-e682-48a2-81a7-efcf5bfe4cc4)

The dGPU is still very much on and showing in Device Manager. If I think click on 'Eco' to shut the dGPU down, that works and looks like this then:

![Image](https://github.com/user-attachments/assets/c2953df8-dc5f-4533-8ec8-4e2aba92a4e2)

I don't really understand what's going on here so hoping you have some expert insight.

**Comment by seerge** [comment]
@VincentPostmus on the screenshot it definitely stays enabled :) Do you know exact time moment when it happened (so i can check it in your existing log) ? Or did you took screenshot after uploading log ?

In short - what you should see in a log is a line like `GPUEco = 1 : OK` the moment app turns GPU off.

**Comment by VincentPostmus** [comment]
@seerge the screenshots were after the log I sent but I just recreated the issue now so attaching the new screenshots and fresh log during which they occurred. I included the PC time in the screenshot to help with identifying the issue:

[log.txt](https://github.com/user-attachments/files/18784230/log.txt)

Booting the laptop in battery mode with Optimised selected, with the fail to automatically switch off dGPU:

![Image](https://github.com/user-attachments/assets/51e04847-0d8a-4167-8f4f-6e86512add28)

Then manually clicking on Eco mode which then does switch of the dGPU:

![Image](https://github.com/user-attachments/assets/cca92293-50cb-40c5-ae59-e100796c310f)

**Comment by seerge** [comment]
@VincentPostmus in the log i see that on start app has turned GPU off
````
13/02/2025 13:00:57: App launched: ROG Zephyrus G15 GA503QM_GA503QM :0.202.0.0en-GB.
13/02/2025 13:01:00: AutoSetting for Offline <--- app start and on battery

..
13/02/2025 13:01:00: GPU usage: NVIDIA GeForce RTX 3060 Laptop GPU 0% <--- GPU WAS ON
13/02/2025 13:01:00: Mode = 2 : OK
13/02/2025 13:01:00: GET CLOCK LIMIT: 0
13/02/2025 13:01:00: Running eco command 1 <--- TURNING GPU OFF
...
13/02/2025 13:01:09: GPUEco = 1 : OK <--- SUCCESS
```

But after that in a couple of seconds you seem to turn GPU back ON manually ? did you click Standard?
```
13/02/2025 13:01:12: GPUEco = 0 : OK
```

Btw, did you do any manual modifications in app config ? Did you select `Enable GPU on shutdown` under Extra by any chance ?

**Comment by VincentPostmus** [comment]
@seerge that is so strange.. I only booted and then waited a little bit and then opened Ghelper and Device Manager to take a screenshot. Then later clicked the Eco mode to manually turn it off. Wondering where that manual switching on of the DGPU comes from... 
I don't have the 'Enable GPU on shutdown' option ticked. These are the settings I have there: 

![Image](https://github.com/user-attachments/assets/ec90c02a-6e3b-494c-869b-2be38faf1e55)

**Comment by seerge** [comment]
@VincentPostmus i think I have figured out what could be the reason in your case, can you please try this build ? Thanks

[GHelper.zip](https://github.com/user-attachments/files/18785324/GHelper.zip)
