### ISSUE TITLE
G-Helper overriding Logitech G Hub custom mouse key

### ISSUE THREAD

**Issue by RamseyKal** [seerge/g-helper#3256]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi,
First, thank you so much for G-Helper. While it is missing a few things, it is currently spectacular. It actually improves battery life by a lot! I could only get about 2-3 hours max before, even with 60hz. Now, I was able to see 5 hours and a half in a quick test.
And, it fixes the shortcut of FN+numpad enter to open the calculator. It could always open it with Armoury Crate but always in the background and not foreground so I had to move my mouse and select it from the taskbar. Now, it's in the foreground and ready to be used.

I installed G-Helper because Armoury Crate's latest update was slowing down my computer and causing crashes. What a mess Asus keeps doing. They previously caused other hotkey bugs.

Now, **my issue here** is that I experience a bug with M1 and M2 keys overriding my mouse's custom keys that I have set in Logitech G Hub and Logitech Onboard Memory Manager.

My mouse is the Logitech G502 X wired. I use G-Shift and I hold it and then rotate the mouse scroll up and down to activate volume up and down. I change volume quickly like that using just my mouse. Been doing that across Razer and Logitech mice without any issue for many years. That has been working great until I installed G-Helper this morning.

M1 is set to Brightness Down.
M2 is set to Brightness Up.

But, now when I use G-Shift with scroll up/down, it is using the M1 and M2 keys instead and is increasing brightness up and down. If I change those to any other command, it does those command, so it's not just about brightness up/down. I tried custom and it activates the custom command. Sadly, there's no custom brightness up/down keys in Windows (disappointing) :(.

For now, I figured out that if I set M1 and M2 to default vol up/down, then I can use your G-Helper shortcut ctrl+G-Shift+scroll up/down to control brightness and that's really nice as a workaround.

I'm hoping you can fix this so that your app doesn't override Logitech's both apps and that an exception is made for those (consider doing it for Razer's Synapse also, in case it happens there too).

Let me know if you need more information.

### How to reproduce the bug?

Get a Logitech mouse.
Set it up in G Hub and/or in Onboard Memory Manager.
Use G-Shift + scroll up and down to change volume.
It doesn't change volume but instead does the command that M1 and M2 keys are set to.

### Logs

[log.txt](https://github.com/user-attachments/files/17356199/log.txt)

### Device and Model

Asus ROG Strix G18 G814JZ

### Additional information.

![SnagIt - 2024-10-13 11 50 29 AM](https://github.com/user-attachments/assets/02a3b885-640a-433e-bed8-09f2b981d737)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.196

### OS

Windows 10 64-Bit 22H2

**Comment by seerge** [comment]
@RamseyKal hello,

G-Helper is not overriding anything for Logitech or Razer, it is simply not aware about existence of those devices and don't interact with them. 

But G-Helper has own hotkeys [listed in readme](https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings)

In particular 

`Ctrl + M1 / M2` - Screen brightness Down / Up
`Shift + M1 / M2` - Backlight brightness Down / Up

But this is for Asus own macro keys that you have on your laptop. `M1/M2` emit volume controls by default, and G-Helper processes `Ctrl + Volume Up/ Volume down` as brightness command for example.

You can **completely disable** all this hotkeys by adding following line to config as explained in [Power user settings](https://github.com/seerge/g-helper/wiki/Power-user-settings#disable-extra-keybindings)

```
"skip_hotkeys":1,
```

Thanks.

**Comment by RamseyKal** [comment]
Thanks for your reply.
I tried that, exited G-Helper, added it in config.php, launched G-Helper and it still does the same thing.
Logitech GShift + scroll wheel changes screen brightness. Am I missing anything?

![SnagIt - 2024-10-13 1 22 45 PM](https://github.com/user-attachments/assets/44877742-6493-4ed0-83aa-13f5c87707a0)

**Comment by seerge** [comment]
@RamseyKal you need to quit app, make changes to `config.json` and start app again after. It reads config only on start.

**Comment by RamseyKal** [comment]
That's what I said..

**Comment by seerge** [comment]
@RamseyKal ok, I think I know what could be the reason. 

Can you check what settings do you have under `Extra` in G-Helper ? You can change what does `M1` and `M2` do there. Are they assigned to default Volume Up / Down ? Or to something else ?

**Comment by RamseyKal** [comment]
I'm not sure if you read my initial support request but I mentioned the following:
M1 is set to Brightness Down.
M2 is set to Brightness Up.

And, the point is not to have them set to volume up and down but to screen brightness up/down.
In Armoury Crate, **before uninstalling it**, I always had customizable hotkeys set to:
M1 is set to Brightness Down.
M2 is set to Brightness Up.

**Same in G-Helper now and the bug occurs.**
I don't want to set M1 and M2 to volume. Of course, I have to in order to bypass the bug I am experiencing.
You can read my initial support request for all the information. It explains everything.

This is what I would like if you could add an exception to Logitech's software and Razer's so that your app doesn't try to modify those keys or even consider them. I can do a beta test if you'd like.

**Comment by seerge** [comment]
@RamseyKal 

I have misread it (sorry) and thought that your mouse wheel emits a key-combo (`Ctrl + M1/M2`) directly responsible for brightness controls. So `skip_hotkeys` is irrelevant here, you can remove it.

G-Helper can't and doesn't change what macro-keys (`M1-M5`) do on hardware level. It listens to key-codes that those buttons emit and runs assigned actions.

`M1` and `M2` emit windows media keys for volume controls. When you change that action under `Extra` - Windows will be notifying G-Helper that those keys are pressed (no matter where they are pressed, internal keyboard or any other device) and it will run other action.

In your (specific) case - both mouse wheel and M1/M2 emit exactly same key code :) 

Why don't you use `Ctrl + M1/M2` to control brightness instead ? Or just use FN-Lock and use `F7/F8` ?

**Comment by RamseyKal** [comment]
I believe that Microsoft is acting silly since they never added a key code for brightness up/down. Very strange. I tried finding one to use it as Custom and couldn't. Thus why lots of programs can't do their own brightness change.

Thanks for your reply and for reading my request.
I assume the reason why Armoury Crate works is because it has more permissions than G-Helper, correct?
I wish G-Helper would work as well in that M1/M2 function.

To answer you, it requires a habit change if I am to use ctrl+M1/M2. It forces my hand in a weird way to reach those keys. Uncomfortable And, the point of even having this Asus laptop is for me to use those M keys without holding any other key (and the 18" screen); just pressing one key. I love those M keys.
I work a lot and as a business owner in multiple businesses, including hosting and servers, often being short on time, and need shortcuts working in the fastest way possible.

The workaround I mentioned can be a solution for me (.. if I set M1 and M2 to default vol up/down, then I can use your G-Helper shortcut ctrl+G-Shift+scroll up/down to control screen brightness), but I would have preferred it working as I had it before, simply because the functionality is there and in Armoury Crate it is fine.

Do you think there's anything you can do to have this work like Armoury Crate? If not, it's okay, the benefits of using G-Helper outweigh this small negative.

**Comment by seerge** [comment]
@RamseyKal 

I honestly don't know how exactly Armoury does it at the moment :) It either has some proprietary way to force macro buttons emit something else on hardware level OR just listens to a whole internal keyboard input (which I don't want to do as it will be pretty much a key-logger and a red-flag for any antivirus)

Personally, I prefer simplicity of current software-only way to rebind buttons. Cause as soon as you quit G-Helper - everything reverts to defaults and furthermore by default M1/M2 are not even handled by the app at all (as they just do volume thing directly).

You are the first person encountering (and mentioning) this so far. If happens more often - I may try to reverse-engineer how exactly Armoury does it.

But as a workaround solution - you need to find alternative way to control brightness rather than directly setting M1/M2 to it OR alternative way to control volume rather than directly emitting VolumeUp/Down keys from the mouse wheel ...

**Comment by seerge** [comment]
@RamseyKal quick googling has led me to this app https://www.nirsoft.net/utils/volumouse.html

May be try to use it instead of G-HUB ?

**Comment by seerge** [comment]
@RamseyKal or other suggestion

Set G-HUB to emit `ALT + VolumeUP` and `ALT + VolumeDown` on mouse wheel scroll. G-Helper will ignore them then.

**Comment by RamseyKal** [comment]
Thanks. I tried that program but didn't really like it. It tends to freeze in a way and I couldn't set it up properly in G Hub. I really hope you can find a way to make this work correctly.
I even tried changing in G Hub the buttons that do vol up/down to make them macros instead and yet it causes the same issue. Very very strange that G-Helper overrides my mouse shortcuts.

**Comment by seerge** [comment]
@RamseyKal 

You can set G-HUB to emit `ALT + VolumeUP` and `ALT + VolumeDown` (as macros) on mouse wheel scroll as I mentioned above. 

I have intentionally installed G-HUB and recreated your situation to verify. It still works as volume control, and don't interfere with M1/M2.

I have more basic mouse, so I had to bind my side buttons to emit those macros, but sense doesn't change

![Screenshot 2024-10-14 210044](https://github.com/user-attachments/assets/76c2d644-547f-4226-b873-27820d84d378)

![Screenshot 2024-10-14 210116](https://github.com/user-attachments/assets/e05edb6c-75be-478f-a9f5-829343161df3)

**Comment by seerge** [comment]
@RamseyKal same as you, brightness controls

**Comment by RamseyKal** [comment]
I did the same now and yes, creating a macro with Alt+Vol up/down works (without Volumouse app) but only if we keep G Hub open and not saved to the mouse. Once saved, it doesn't even recognise those since a macro from G Hub needs the app running.
Once you save to the mouse and you use [Logitech Onboard Memory Manager](https://support.logi.com/hc/en-us/articles/360059641133-Onboard-Memory-Manager) (select the Windows version from the arrow down, very awkward lol), not all settings are saved and then we have to re-set it up. 

I don't use G Hub. I just do an initial setup there and then I use Logitech Onboard Memory Manager. That's because Logitech has buggy software and both of those are buggy and need each other. Very weird. Nonetheless, the point is that it doesn't end up working when G Hub is closed.

Since something in G-Helper is overriding M1/M2 no matter what function is used (brightness, mute, mode, etc.), then to solve this I set up brightness down to M3 and brightness up to M5, and FN+F4 to G-Helper.
It's a bit of a shame to lose the mute mic button, but I use brightness every day multiple times.

Hopefully one day it can work normally in M1/M2 :(.
Thanks for your help so far and for trying.

**Comment by seerge** [comment]
@RamseyKal then you can still keep wheel emitting volume up / down without ALT and hold ALT on keyboard to control volume :)

**Comment by RamseyKal** [comment]
Hi again, I would actually really appreciate if a solution can be found for this. I know you don't have to and I know this is free. I'm just a bothered by this.
Is there something we can do to try to make this work? A summary of what the issue here is: https://github.com/seerge/g-helper/issues/3256#issuecomment-2409063533

**Comment by seerge** [comment]
@RamseyKal as I was explaining, at the moment I'm not aware about ways to rebind M1 and M2 keys on hardware level (as there is literally no open source info about it). If I will figure out how to do this - i can change it later.
