### ISSUE TITLE
Control to activate/deactivate RGB lights for new Scar 16/18 laptops.

### ISSUE THREAD

**Issue by imavichandra** [seerge/g-helper#326]
**Is your feature request related to a problem? Please describe.**
The new Scar laptops have 3 lighting zones. 1. The front light strip and the ROG logo on the lid. (These seems to be connected as both activated in armoury crate together. 2. The rear light strip. 3. The keyboard RGB. Currently, there is no toggle to select only 1 or 2 zones to light up. The app toggles light for all at once. 

**Describe the solution you'd like**
A simple check box in extra tab to select the light zones that the user wants to activate. It would be useful if these could be linked with 'plugged in' feature to automatically toggle zone controls when connected to power.

**Describe alternatives you've considered**
No Alternative considered.

**Additional context**
I deactivated the rear Light bar with the armory crate app and now that I have uninstalled it, there is no way for me to reactivate it, or toggle off the front light bar. The keyboard and the front light bar light-up but there is no way for me to toggle off the front light bar as well. An option to toggle these on/off will be very useful.

**Comment by seerge** [comment]
@imavichandra try this build and let me know if checkboxes under Extra work

[GHelper.zip](https://github.com/seerge/g-helper/files/11415921/GHelper.zip)

**Comment by imavichandra** [comment]
@seerge The checkboxes work except the one for the Lid ( Rear Lightbar). It stays off always.

**Comment by seerge** [comment]
@imavichandra 
Do you mean this (selected) checkbox doesn't work ?
![Screenshot 2023-05-07 230118](https://user-images.githubusercontent.com/5920850/236702429-8fe2e9bd-aed6-4418-9f40-f23c36f91e1c.png)

**Comment by imavichandra** [comment]
The one marked under “Lid” does not work.
The one selected in the screenshot you have share controls the front
Lightbar for me and it works fine.

**Comment by seerge** [comment]
@imavichandra ok, so far i have added all known switches.

Does OpenRGB work for that missing zone on your laptop?

**Comment by imavichandra** [comment]
OpenRGB does not work for the zone as well.
The laptop is not mentioned in the supported devices section of the application as well.

**Comment by seerge** [comment]
@imavichandra then there is no open info about how that is controlled. Untill someone with G16/18 AND propgramming skills gets hands on that, it's not possible to add it ;)

I did last "blind" attempt to set some flags in this build , let me know if it suddenly lights up
[GHelper.zip](https://github.com/seerge/g-helper/files/11419563/GHelper.zip)

**Comment by imavichandra** [comment]
nope, still nothing.
Thanks for trying. :)

**Comment by seerge** [comment]
Then, i can’t add that, but other checkboxes work, and it was confirmed by other user, so i will push it with next release

**Comment by orionflame** [comment]
I just tried these with strix 18 2025, the logo options do not work. Should I create a new issue?
