### ISSUE TITLE
Asus ROG Headphones support

### ISSUE THREAD

**Issue by squashbond** [seerge/g-helper#3264]
### Mouse / peripheral model and version

Asus ROG Delta & Asus ROG Delta S Wireless

### Armoury Crate Screenshots

-

### USB Details

-

### Additional information.

Are you thinking about adding support for Asus ROG headphones? If I would buy one, I would have to use Armoury Crate which sux. G-Helper would be so much better.

**Comment by seerge** [comment]
@squashbond hello, i don't have any of the ROG headphones, so most likely - not :) Also from what i know there is no onboard memory or any hardware settings that you can change on them anyway.

Thanks. Closing cause this is not an actual request
