### ISSUE TITLE
Add support for Vivobook S 16 M5606WA

### ISSUE THREAD

**Issue by Mk007V2** [seerge/g-helper#3265]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Flicker-Free Dimming / Visual Mode option doesn't show up on Vivobook S 16 M5606WA. However, it does work on Vivobook Pro M6500RC and Vivobook S5402Z. 

![image](https://github.com/user-attachments/assets/1c27bd04-4bf9-4819-88ac-81a0378cde3a)

### Describe the solution you'd like

Add support for Vivobook S 16 M5606WA.

### Device and Model

ASUS Vivobook S 16 M5606WA

**Comment by seerge** [comment]
@Mk007V2 hello, this build should list OLED settings for your model

[GHelper.zip](https://github.com/user-attachments/files/17368292/GHelper.zip)
