### ISSUE TITLE
Keyboard Lag Issues on Asus Flow X16 (2022) When Using G-Helper v194

### ISSUE THREAD

**Issue by JMS1717** [seerge/g-helper#3266]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### **Description**
I'm experiencing intermittent keyboard lag on my **2022 Asus Flow X16** while using **G-Helper version 194**. The keyboard becomes unresponsive for approximately one second after a period of inactivity, requiring multiple key presses to register input. Occasionally, single key presses result in repeated characters (e.g., pressing "f" generates multiple "f"s). 

### **Expected Behavior**
- **Immediate Keyboard Response:** Keystrokes are registered instantly without delays.
- **Accurate Input:** Each key press results in a single corresponding character without repetition.

### **Actual Behavior**
- **Delayed Response:** Approximately one-second lag before keystrokes are recognized.
- **Multiple Keystrokes:** Single key presses sometimes register as multiple characters.

### **Environment**
- **Device:** Asus Flow X16 (2022 model)
- **Operating System:** Windows 11 Home, Version 24H2
- **G-Helper Version:** 194

### **Troubleshooting Attempts**
- **Uninstalled Armoury Crate:** Temporary resolution of keyboard lag, but issues have since reoccurred.
- **Updated BIOS and Drivers:** Ensured all system firmware and drivers are up-to-date.
- **Performed Clean Boot:** Disabled all non-Microsoft services and startup items; issue persists.

---
**Thank you for your attention and support!**

### How to reproduce the bug?

1. **Install G-Helper v194** on the Asus Flow X16 (2022 model).
2. **Launch G-Helper** and let it run in the background.
3. **Use the laptop normally**, allowing periods of inactivity.
4. **Begin typing** after inactivity and observe the lag and repeated keystrokes.

### Logs

[log.txt](https://github.com/user-attachments/files/17368766/log.txt)

### Device and Model

ROG Flow x16 2022

### Additional information.

na

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

194

### OS

24H2

**Comment by seerge** [comment]
@JMS1717 hello,  Why do you think it's connected with G-Helper ? 

Try to completely quit app and use device for a while, does keyboard become unresponsive ?

**Comment by JMS1717** [comment]
its based off this reddit post: https://www.reddit.com/r/ASUSROG/comments/wyxwhx/flow_x16_keyboard_lagging_sporadically/

**Comment by seerge** [comment]
@JMS1717 but that post doesn't say it's because of G-Helper ? :) from what i see OP commented there that uninstalling AC and using G-Helper actually helped him ?

> Uninstalled Armoury Crate: Temporary resolution of keyboard lag, but issues have since reoccurred.

From your comment i see that it was happening to you in AC as well ? Most likely it's some firmware issue with keyboard itself :)

**Comment by seerge** [comment]
@JMS1717 well, G-Helper is not handling keyboard input (besides processing your special hotkeys), and since problem happens also with AC it's logical that problem is not in the software :)

The only advice I can give - is to use only default backlight modes (i.e. not Ambient or Heatmap), as some keyboard firmware may act strange when color is changed too often. But you don't seem to use them anyway.

Try to set Static backlight or something simple.

**Comment by JMS1717** [comment]
Ok, thanks for looking into this for me! I appreciate all your help :)

**Comment by seerge** [comment]
@JMS1717 ok, np.

You can also try [hard reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset). It resets all hardware settings, and who knows - may be will change something in your case as well.

But besides that I can't do anything :) So closing this as not planned / not related.

Thanks.
