### ISSUE TITLE
Mid fan custom speed not working (ROG Zephyrus G16 GU605MV GU605MV). 

### ISSUE THREAD

**Issue by wang1uu** [seerge/g-helper#3267]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Although I set its maximum speed to 3400 RPM, the fan speed is not being limited as expected.

<img width="826" alt="Snipaste_2024-10-15_09-04-12" src="https://github.com/user-attachments/assets/2650051a-0ad6-4b01-ab07-f459e8e372ed">

### How to reproduce the bug?

1.Adjust custom fan speed settings.
2.Check to apply custom fan speed.

### Logs

[log.txt](https://github.com/user-attachments/files/17370880/log.txt)

### Device and Model

ROG Zephyrus G16 GU605MV GU605MV

### Additional information.

None

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.194.0

### OS

版本	Windows 11 家庭中文版 版本号	22H2 安装日期	‎2024/‎9/‎24 操作系统版本	22621.4317 体验	Windows Feature Experience Pack 1000.22700.1041.0

**Comment by seerge** [comment]
@wang1uu hello,

Fans are controlled by BIOS - and in your case BIOS decided to spin mid fan faster. You can try to set curve even lower here.
Alternatively you can try experimental build with an actual fan control.

Please make yourself familiar with FAQ

Thanks.

>  [How does G-helper control my fan speeds?](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)
**It doesn't and can't control your fans**. Firmware / BIOS controls them in real-time. Armoury also doesn't control fans in real time anyhow.

> What G-helper can do - is (optionally) set a custom fan profile to the current performance mode via the same endpoint Armoury uses in Manual mode.

> How it will be interpreted - is still up to the firmware. If you don't like how firmware controls fans, you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)
