### ISSUE TITLE
Improve Battery Life for Ryzen HX Processors

### ISSUE THREAD

**Issue by bilal-akbar-9** [seerge/g-helper#3268]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I am experiencing high battery discharge rates on my Ryzen 9 7940HX processor during normal use (web browsing, scrolling), with rates between 17 to 19W. This seems quite high and affects the overall battery life.

### Describe the solution you'd like

 I believe there might be a way to optimize the battery life through BIOS settings or other adjustments. Any guidance or solutions to reduce the power consumption would be greatly appreciated.

### Describe alternatives you've considered

 I have not yet explored other alternatives extensively, as I am unsure if this can be resolved through BIOS or other means.

### Device and Model

Asus Tuf A16 FA607PV

### Additional information.

Any help or suggestions to improve the battery life would be highly valued. Thank you!

**Comment by seerge** [comment]
@bilal-akbar-9 hello,

G-Helper is not a driver :) it doesn't and can't "optimize" anything more. You can set `Eco` + `Silent` modes in the app and `Battery Saver` in windows - that would be already lowest power profile possible.

Keep in mind that HX CPUs are very power hungry, and 17W doesn't look that bad :)

Thanks.
