### ISSUE TITLE
Ghelper wont open

### ISSUE THREAD

**Issue by johnrobledo** [seerge/g-helper#327]
Hello. Ghelper will not open. In event viewer, I see 3 information and one error notifications that say the following:
1. `Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: MsMpEng.exe
P2: 4.18.2304.8
P3: 1feba1b6
P4: mpengine.dll
P5: 1.1.20300.3
P6: f1a615b8
P7: c0000005
P8: 000000000004e6c0
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_MsMpEng.exe_219de771ae2b2c8ad271f2cc0e5acdb18c0a32f_91d88ffb_b0c9a305-6172-4a69-aa58-05a3e7939d3d

Analysis symbol: 
Rechecking for solution: 0
Report Id: ef6821ca-1c31-414d-8d3d-23a57ae44334
Report Status: 4
Hashed bucket: 
Cab Guid: 0`

and the other 2 iniformations are similar. the error is as follows:
Faulting application name: MsMpEng.exe, version: 4.18.2304.8, time stamp: 0x1feba1b6
Faulting module name: mpengine.dll, version: 1.1.20300.3, time stamp: 0xf1a615b8
Exception code: 0xc0000005
Fault offset: 0x000000000004e6c0
Faulting process id: 0x0x59A8
Faulting application start time: 0x0x1D9801C36B4A495
Faulting application path: C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2304.8-0\MsMpEng.exe
Faulting module path: C:\ProgramData\Microsoft\Windows Defender\Definition Updates\{EB004E62-D80A-4707-8C3A-571845153D42}\mpengine.dll
Report Id: 63b3aa47-7b69-4afd-af33-d443a8d37ee6
Faulting package full name: 
Faulting package-relative application ID:

**Comment by seerge** [comment]
@johnrobledo hello, the notification you copied here has nothing to do with g-helper, it's some local issues on your PC. 
If you believe it crashed  - please try to find a crash log related to ghelper.exe.

**Comment by seerge** [comment]
@johnrobledo ps next to that - check system tray for g icon

**Comment by johnrobledo** [comment]
@seerge haha my bad. Copied the wrong one. No, ghelper is not opening, and I found the proper error
Faulting application name: GHelper.exe, version: 0.55.0.0, time stamp: 0x641de100
Faulting module name: KERNELBASE.dll, version: 10.0.22621.963, time stamp: 0x766ca8ae
Exception code: 0xe0434352
Fault offset: 0x00000000000906bc
Faulting process id: 0x0x1A28
Faulting application start time: 0x0x1D9801F7C89EA4F
Faulting application path: C:\Users\ilove\Downloads\GHelper.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 57ce388a-0cae-426a-b6ab-d0abbc173bd6
Faulting package full name: 
Faulting package-relative application ID:

**Comment by seerge** [comment]
Ok :) @johnrobledo it should be one more crash log mentioning real reason of crash (usually they are next to each other)

**Comment by johnrobledo** [comment]
@seerge i am so sorry. Kinda new to modding my laptops like this lol. Ill try to find it

**Comment by johnrobledo** [comment]
@seerge Is this it?
Application: GHelper.exe
CoreCLR Version: 7.0.523.17405
.NET Version: 7.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'System.Drawing.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Drawing.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at GHelper.Program.Main()

**Comment by seerge** [comment]
@johnrobledo ok, looks like something not directly related to the app, but rather to .NET missing something.

1. What system language do you have? English or something else?
2. Try to download and install latest .NET from microsoft website https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.203-windows-x64-installer

**Comment by johnrobledo** [comment]
1. English
2. I tried that and it gave me a 2503 error. I saw a .net update in my windows update so im trying that now and ill get back to you
@seerge

**Comment by johnrobledo** [comment]
@seerge redid the ,net but still giving me the same error. Ill keep trying.

**Comment by seerge** [comment]
@johnrobledo can you try this build ?

[GHelper.zip](https://github.com/seerge/g-helper/files/11412816/GHelper.zip)

**Comment by johnrobledo** [comment]
![image](https://user-images.githubusercontent.com/90490139/236638869-f715125d-8c8a-47bc-9f1b-155746829f3f.png)
Gives me this. Oh well. I guess its a bigger issue. Ill have to use AC until i figure it out

**Comment by seerge** [comment]
Um, what gave you that? zip file ?

**Comment by johnrobledo** [comment]
Yeah the app within . I unzipped too. I have no clue what's going on lmao

**Comment by johnrobledo** [comment]
im going to factory reset my whole pc and ill let you know

**Comment by seerge** [comment]
@johnrobledo that’s quite radical, but it’s up to you of course

**Comment by johnrobledo** [comment]
Haha I'm having other issues too

**Comment by seerge** [comment]
Oke, good luck then. Closing this topic for now.
