### ISSUE TITLE
Fans stop working in middle of the task

### ISSUE THREAD

**Issue by GuptaPranjal21** [seerge/g-helper#3270]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![Screenshot (266)](https://github.com/user-attachments/assets/c9473417-2725-4e8c-bf93-3c4aef7f379c)

This is the screenshot i've attached because i've faced this Problem several times.  Fans stop working and keyboard light went to white out of no where i don't have any idea regarding this issue. Help me with the issue

### How to reproduce the bug?

Plug the charger. keyboard rgb turned to white.
put on hibernate‚ Open the lid ghelper stops responding..... in changing light modes

### Logs

[log.txt](https://github.com/user-attachments/files/17402482/log.txt)

### Device and Model

Asus Tuf f15 2021

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.194.0

### OS

Windows 10

**Comment by seerge** [comment]
@GuptaPranjal21 hello,

Fans are controlled by firmware / BIOS, not by G-Helper. [Please check FAQ.](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)

If fans stopped working and backlight changes to something random (not what you have set), it's probably some firmware hiccup.

You can try to do a [hard reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset) and also reset BIOS settings (F2 on boot) to all defauts to see if it helps.

Besides that I can't do anything.

Thanks and good luck
