### ISSUE TITLE
Alternative Overlays

### ISSUE THREAD

**Issue by SegaBoy64** [seerge/g-helper#3271]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

AMD Overlay button redundant with XG Mobile.

### Describe the solution you'd like

Can we use an alternative overlay to the AMD Overlay. Although I appreciate this will be a niche request, when using a setup of a ROG Ally and XG Mobile 4090, the current AMD Overlay button doesn't provide any functionality. A custom button feature would be ideal.

Alterantively perhaps there is another way to accomplish this?

Many thanks for your consideration.

### Device and Model

ROG ALLY + XG Mobile 4090

**Comment by seerge** [comment]
@SegaBoy64 hello, 

Since you use Nvidia XGPU, why don't you use nvida own overlay ? Or Afterburner's overlay or HWinfos overlay? There is plenty of options already.

I might try to do an own overlay **one day,** but at this moment it's too many complications (mainly with windows permissions not letting you show info on top of everything, including full-screen games that easily)

Thanks. 

So i'm closing this as not planned (for now).

**Comment by SegaBoy64** [comment]
Thanks for the reply. I do have RTSS for this, I was just trying to find a way to neatly integrate it into G-Helper as it has become my default control panel.

Appreciate all of the hard work and effort you pour into this.

**Comment by seerge** [comment]
@SegaBoy64 well, RTSS does great job imho (and it's also very lightweight). What specific metrics are you missing in AMD overlay ? is it something nvidia specific ?

**Comment by SegaBoy64** [comment]
It's probably incompetence on my behalf, however the AMD Overlay button doesnt do anything, which I attributed to running the XG Mobile. I'll have a dig around and see if I'm missing something...

**Comment by seerge** [comment]
@SegaBoy64 hello,

You can now try build with an actual overlay (`CTRL + SHIFT + ALT + O`) to toggle or via context menu

https://github.com/seerge/g-helper/pull/5164

# [GHelper.zip](https://github.com/user-attachments/files/26662348/GHelper.zip)

<img width="998" height="467" alt="Screenshot (5)" src="https://github.com/user-attachments/assets/bb2d720a-66b2-4632-879e-6a4a23b29482" />
