### ISSUE TITLE
Add fan curve support for vivobook pro 2024 ultra cpu series

### ISSUE THREAD

**Issue by V3geD4g** [seerge/g-helper#3273]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Current version does not support vivobook pro 2024 ultra cpu series fan curve control

### Describe the solution you'd like

Add fan curve support for vivobook pro 2024 ultra cpu series,hope to add new features to support, you can refer to the implementation of the project at https://github.com/Darren80/AsusFanControlEnhanced

### Device and Model

ASUS vivobook pro 2024

**Comment by seerge** [comment]
@V3geD4g hello, your device does not support custom fan curves out of the box, if you really want to try you can already try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)

Thanks
