### ISSUE TITLE
There is no tray icon in the taskbar after startup, but Ghelper is running in the background indeed.

### ISSUE THREAD

**Issue by EmpressPENG** [seerge/g-helper#3275]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Usually, the tray icon is not shown on the taskbar after the computer startup, but when you open the task manager, Ghelper is indeed running in the background, which you wouldn't have encountered before!

### How to reproduce the bug?

1.Restart PC
2.The tray icon doesn't appear in the taskbar

### Logs

2024/10/21 上午 10:42:10: App launched: ROG Zephyrus G16 GU603VV_GU603VV :0.194.0.0en.
2024/10/21 上午 10:42:10: Start Count: 23
2024/10/21 上午 10:42:22: Matrix control device was not found on your machine.
2024/10/21 上午 10:42:24: C:\ProgramData\ASUS\GameVisual\ASUS_DCIP3.icm DCIP3
2024/10/21 上午 10:42:24: C:\ProgramData\ASUS\GameVisual\ASUS_DisplayP3.icm DisplayP3
2024/10/21 上午 10:42:24: C:\ProgramData\ASUS\GameVisual\ASUS_sRGB.icm sRGB
2024/10/21 上午 10:42:24: TL160ADMP03-0 HDR: False 8 12 True
2024/10/21 上午 10:42:25: \\?\DISPLAY#TMX1603#5&2d25fbdc&1&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
2024/10/21 上午 10:42:25: \\?\DISPLAY#TMX1603#5&2d25fbdc&1&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2024/10/21 上午 10:42:25: C:\WINDOWS\system32\DriverStore\FileRepository\asussci2.inf_amd64_65474b5d0e394c04\ASUSOptimization\AsusSplendid.exe 13 0 50
2024/10/21 上午 10:42:27: ReadDataBlocklib version = 1.0.99.4 ulInOutBuffer[0]: 512 HIT: ulOutBuffer[0] = 512 > 0 this->BiosDataStatus  = 0   ReadResult  = 0  [H][D][O][C] Parsing version = 7 Use Method = 1   bios size = 57 CCTAPI_ERRORCODE = 0 ; HIT: DEF Gain E(0) W(0) ; HIT: Warm Gain E(0) W(0) ; HIT: Cold Gain E(0) W(0) ; HIT: RdW Gain E(0) W(0) ; HIT: RdS Gain E(0) W(0) CCT_Init  result = 0 ; HIT: GetGvModeLut() ReadDataBlocklib version = 1.0.99.4 ulInOutBuffer[0]: 512 HIT: ulOutBuffer[0] = 512 > 0 ; HIT: Get bios[297]: 32  scale: 1.000000, Scale TH: 0.100000, nIndex: 26 Run convert power lut with api type: 1 ; HIT: ##Enter GetCscMatrixAll()## ; HIT: ##Exit GetCscMatrixAll()## Get dll path: [C:\WINDOWS\system32\DriverStore\FileRepository\asussci2.inf_amd64_65474b5d0e394c04\ASUSOptimization\AsusCCT.DLL] Get dll folder: [C:\WINDOWS\system32\DriverStore\FileRepository\asussci2.inf_amd64_65474b5d0e394c04\ASUSOptimization] UIGain: 1.000000 lutDcModeScale: 1.000000 Interval: 1.000000 RDLevels: 5.000000 index: 0.250000 Param: 26, Gamut mode: 3 Gamut icm path : C:\ProgramData\ASUS\GameVisual\ASUS_DisplayP3.icm Description: Asus_GU603VV_10DE_B8511603_Display_P3 changeDescription() return with error code 0 ChangeDes with return code: 0 dst xy: 0.680000,0.320000, 0.265000,0.690000, 0.150000,0.060000, 0.313000,0.329000, 1.045018, -0.036333, -0.005970,  0.023461, 0.969691, 0.007342,  -0.011275, 0.013062, 0.997854,  Calculate csc matrix with return code: 0 AddMHC2tag with return code: 0 Gamut mapping process exit with return code 0
2024/10/21 上午 10:42:27: Stopped: ASUSSmartDisplayControl
2024/10/21 上午 10:42:27: NVIDIA GeForce RTX 4060 Laptop GPU
2024/10/21 上午 10:42:28: CPU: -1 - 13th Gen Intel(R) Core(TM) i9-13900H - Intel64 Family 6 Model 186 Stepping 2
2024/10/21 上午 10:42:28: AutoSetting for Offline
2024/10/21 上午 10:42:28: BatteryLimit = 75 : OK
2024/10/21 上午 10:42:28: Input available: \\?\hid#vid_0b05&pid_19b6&col03#6&19e2ad7&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 64
2024/10/21 上午 10:42:28: USB 19B6|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2024/10/21 上午 10:42:28: Input: \\?\hid#vid_0b05&pid_19b6&col03#6&19e2ad7&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
2024/10/21 上午 10:42:28: Power Plan 27fa6203-3987-4dcc-918d-748559d549ec:OK
2024/10/21 上午 10:42:28: Eco flag : 0
2024/10/21 上午 10:42:28: Mux flag : 0
2024/10/21 上午 10:42:28: \\?\DISPLAY#TMX1603#5&2d25fbdc&1&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
2024/10/21 上午 10:42:28: \\?\DISPLAY#TMX1603#5&2d25fbdc&1&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2024/10/21 上午 10:42:28: TL160ADMP03-0 HDR: False 8 12 True
2024/10/21 上午 10:42:28: Mode = 0 : OK
2024/10/21 上午 10:42:28: Init 19B6: 5D-B9
2024/10/21 上午 10:42:28: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2024/10/21 上午 10:42:28: Init 19B6: 5D-05-20-31-00-1A
2024/10/21 上午 10:42:28: USB 19B6: 5D-BD-01-DF-1F-FF-FF-FF
2024/10/21 上午 10:42:28: GET CLOCK LIMIT: 0
2024/10/21 上午 10:42:28: AuraMode: AuraColorCycle
2024/10/21 上午 10:42:28: USB 19B6: 5D-B3-00-02-00-FF-00-E1-00-00-FF-00-FF-00-00-00-00
2024/10/21 上午 10:42:28: USB 19B6: 5D-B5-00-00-00
2024/10/21 上午 10:42:28: USB 19B6: 5D-B4
2024/10/21 上午 10:42:28: powershell nvidia-smi -lgc 0,1950
2024/10/21 上午 10:42:28: FanCPU = 1E-38-3C-40-44-48-7F-80-07-12-16-16-23-41-41-41 : OK
2024/10/21 上午 10:42:29: FanGPU = 1E-38-3C-40-44-48-7F-80-07-09-11-22-32-3E-3E-3E : OK
2024/10/21 上午 10:42:29: Auto 19B6: 5D-BA-C5-C4-01
2024/10/21 上午 10:42:30: Monitor Power On
2024/10/21 上午 10:42:30: BatteryLimit = 75 : OK
2024/10/21 上午 10:42:30: Lid Open
2024/10/21 上午 10:42:30: Lid 19B6: 5D-BA-C5-C4-01
2024/10/21 上午 10:42:30: Session:SessionUnlock
2024/10/21 上午 10:42:30: \\?\DISPLAY#TMX1603#5&2d25fbdc&1&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
2024/10/21 上午 10:42:30: \\?\DISPLAY#TMX1603#5&2d25fbdc&1&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2024/10/21 上午 10:42:30: TL160ADMP03-0 HDR: False 8 12 True
2024/10/21 上午 10:42:31: GPU clocks set to "(gpuClkMin 0, gpuClkMax 1950)" for GPU 00000000:01:00.0 All done.
2024/10/21 上午 10:42:31: GET GPU CLOCKS: 0, 0
2024/10/21 上午 10:42:31: SET GPU CLOCKS: 150, 300
2024/10/21 上午 10:42:32: PowerLimit C0 (GPU BOOST) = 5 : OK
2024/10/21 上午 10:42:32: PowerLimit C2 (GPU TEMP) = 87 : OK
2024/10/21 上午 10:44:25: ------------
2024/10/21 上午 10:44:25: App launched: ROG Zephyrus G16 GU603VV_GU603VV :0.194.0.0en
2024/10/21 上午 10:44:25: Start Count: 24
2024/10/21 上午 10:44:25: Matrix control device was not found on your machine.
2024/10/21 上午 10:44:26: C:\ProgramData\ASUS\GameVisual\ASUS_DCIP3.icm DCIP3
2024/10/21 上午 10:44:26: C:\ProgramData\ASUS\GameVisual\ASUS_DisplayP3.icm DisplayP3
2024/10/21 上午 10:44:26: C:\ProgramData\ASUS\GameVisual\ASUS_sRGB.icm sRGB
2024/10/21 上午 10:44:26: TL160ADMP03-0 HDR: False 8 12 True
2024/10/21 上午 10:44:26: \\?\DISPLAY#TMX1603#5&2d25fbdc&1&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
2024/10/21 上午 10:44:26: \\?\DISPLAY#TMX1603#5&2d25fbdc&1&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2024/10/21 上午 10:44:26: C:\WINDOWS\system32\DriverStore\FileRepository\asussci2.inf_amd64_65474b5d0e394c04\ASUSOptimization\AsusSplendid.exe 13 0 50
2024/10/21 上午 10:44:26: ReadDataBlocklib version = 1.0.99.4 ulInOutBuffer[0]: 512 HIT: ulOutBuffer[0] = 512 > 0 this->BiosDataStatus  = 0   ReadResult  = 0  [H][D][O][C] Parsing version = 7 Use Method = 1   bios size = 57 CCTAPI_ERRORCODE = 0 ; HIT: DEF Gain E(0) W(0) ; HIT: Warm Gain E(0) W(0) ; HIT: Cold Gain E(0) W(0) ; HIT: RdW Gain E(0) W(0) ; HIT: RdS Gain E(0) W(0) CCT_Init  result = 0 ; HIT: GetGvModeLut() ReadDataBlocklib version = 1.0.99.4 ulInOutBuffer[0]: 512 HIT: ulOutBuffer[0] = 512 > 0 ; HIT: Get bios[297]: 32  scale: 1.000000, Scale TH: 0.100000, nIndex: 26 Run convert power lut with api type: 1 ; HIT: ##Enter GetCscMatrixAll()## ; HIT: ##Exit GetCscMatrixAll()## Get dll path: [C:\WINDOWS\system32\DriverStore\FileRepository\asussci2.inf_amd64_65474b5d0e394c04\ASUSOptimization\AsusCCT.DLL] Get dll folder: [C:\WINDOWS\system32\DriverStore\FileRepository\asussci2.inf_amd64_65474b5d0e394c04\ASUSOptimization] UIGain: 1.000000 lutDcModeScale: 1.000000 Interval: 1.000000 RDLevels: 5.000000 index: 0.250000 Param: 26, Gamut mode: 3 Gamut icm path : C:\ProgramData\ASUS\GameVisual\ASUS_DisplayP3.icm Description: Asus_GU603VV_10DE_B8511603_Display_P3 changeDescription() return with error code 0 ChangeDes with return code: 0 dst xy: 0.680000,0.320000, 0.265000,0.690000, 0.150000,0.060000, 0.313000,0.329000, 1.045018, -0.036333, -0.005970,  0.023461, 0.969691, 0.007342,  -0.011275, 0.013062, 0.997854,  Calculate csc matrix with return code: 0 AddMHC2tag with return code: 0 Gamut mapping process exit with return code 0
2024/10/21 上午 10:44:26: NVIDIA GeForce RTX 4060 Laptop GPU
2024/10/21 上午 10:44:27: CPU: -1 - 13th Gen Intel(R) Core(TM) i9-13900H - Intel64 Family 6 Model 186 Stepping 2
2024/10/21 上午 10:44:27: AutoSetting for Offline
2024/10/21 上午 10:44:27: BatteryLimit = 75 : OK
2024/10/21 上午 10:44:27: Input available: \\?\hid#vid_0b05&pid_19b6&col03#6&19e2ad7&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 64
2024/10/21 上午 10:44:27: USB 19B6|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2024/10/21 上午 10:44:27: Input: \\?\hid#vid_0b05&pid_19b6&col03#6&19e2ad7&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
2024/10/21 上午 10:44:27: Power Plan 27fa6203-3987-4dcc-918d-748559d549ec:OK
2024/10/21 上午 10:44:27: Eco flag : 0
2024/10/21 上午 10:44:27: Mux flag : 0
2024/10/21 上午 10:44:27: \\?\DISPLAY#TMX1603#5&2d25fbdc&1&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
2024/10/21 上午 10:44:27: \\?\DISPLAY#TMX1603#5&2d25fbdc&1&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2024/10/21 上午 10:44:27: TL160ADMP03-0 HDR: False 8 12 True
2024/10/21 上午 10:44:27: Mode = 0 : OK
2024/10/21 上午 10:44:27: Init 19B6: 5D-B9
2024/10/21 上午 10:44:27: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2024/10/21 上午 10:44:27: Init 19B6: 5D-05-20-31-00-1A
2024/10/21 上午 10:44:27: USB 19B6: 5D-BD-01-DF-1F-FF-FF-FF
2024/10/21 上午 10:44:27: AuraMode: AuraColorCycle
2024/10/21 上午 10:44:27: USB 19B6: 5D-B3-00-02-00-FF-00-E1-00-00-FF-00-FF-00-00-00-00
2024/10/21 上午 10:44:27: USB 19B6: 5D-B5-00-00-00
2024/10/21 上午 10:44:27: USB 19B6: 5D-B4
2024/10/21 上午 10:44:27: GET CLOCK LIMIT: 1950
2024/10/21 上午 10:44:27: GET GPU CLOCKS: 150, 300
2024/10/21 上午 10:44:27: FanCPU = 1E-38-3C-40-44-48-7F-80-07-12-16-16-23-41-41-41 : OK
2024/10/21 上午 10:44:27: FanGPU = 1E-38-3C-40-44-48-7F-80-07-09-11-22-32-3E-3E-3E : OK
2024/10/21 上午 10:44:28: Monitor Power On
2024/10/21 上午 10:44:28: BatteryLimit = 75 : OK
2024/10/21 上午 10:44:28: Lid Open
2024/10/21 上午 10:44:28: Lid 19B6: 5D-BA-C5-C4-01
2024/10/21 上午 10:44:28: Auto 19B6: 5D-BA-C5-C4-01
2024/10/21 上午 10:44:30: PowerLimit C0 (GPU BOOST) = 5 : OK
2024/10/21 上午 10:44:30: PowerLimit C2 (GPU TEMP) = 87 : OK
2024/10/21 上午 10:44:31: TL160ADMP03-0 HDR: False 8 12 True
2024/10/21 上午 10:44:33: Latest version 0.194.0.0
2024/10/21 上午 10:47:40: TL160ADMP03-0 HDR: False 8 12 True
2024/10/21 上午 10:47:41: Design Capacity: 90005mWh, Full Charge Capacity: 78887mWh, Health: 0.8764735292483750902727626243%
2024/10/21 上午 10:47:42: Cores: 0x0806
2024/10/21 上午 10:47:42: CoresMax: 0x0806
2024/10/21 上午 10:47:42: Unable to load DLL 'atiadlxx.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
2024/10/21 上午 10:47:42: Hibernate after 3600
2024/10/21 上午 10:48:14: Key: 56
2024/10/21 上午 10:49:49: Key: 56
2024/10/21 上午 10:49:49: TL160ADMP03-0 HDR: False 8 12 True
2024/10/21 上午 10:59:57: Key: 56
2024/10/21 上午 10:59:57: TL160ADMP03-0 HDR: False 8 12 True
2024/10/21 上午 10:59:59: Cores: 0x0806
2024/10/21 上午 10:59:59: CoresMax: 0x0806
2024/10/21 上午 10:59:59: Unable to load DLL 'atiadlxx.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
2024/10/21 上午 10:59:59: Hibernate after 3600

### Device and Model

Zephyrus G16 GU603VV

### Additional information.

By the way, is there something wrong from my log. Am i use Ghelper correctly?

### Armoury Crate

Installed

### Asus Services

None

### Version

0.194

### OS

Win11 23H2

**Comment by DPid-ETI** [comment]
I am experiencing this after the latest Windows update. I'm not sure how to check if this app is running in the background.

**Comment by EmpressPENG** [comment]
> I am experiencing this after the latest Windows update. I'm not sure how to check if this app is running in the background.

Taskmgr

**Comment by seerge** [comment]
@EmpressPENG hello,

- Did you change anything in your system recently ? (like windows update to **24**H2 ?)
- Try to run app normally and then uncheck and check again `Run on Startup` checkbox (it will re-create task in Task Scheduler)

**Comment by DPid-ETI** [comment]
> @EmpressPENG @DPid-ETI hello,
> 
> * Did you change anything in your system recently ? (like windows update to **24**H2 ?)
> * Try to run app normally and then uncheck and check again `Run on Startup` checkbox (it will re-create task in Task Scheduler)
> 
> There is nothing wrong with the log :)

I can confirm that check\re-check "Run on Startup" fixed the problem

**Comment by seerge** [comment]
@DPid-ETI good to know. Most likely something was wrong with the startup task (may be caused by windows update?)

@EmpressPENG can you check Task Scheduler -> GHelper task and post how it looks on your system (preferably before unchecking / checking `Run on Startup`)

Example
![image](https://github.com/user-attachments/assets/15308ee3-1337-4c21-8210-cf40cc5476a2)

**Comment by EmpressPENG** [comment]
@seerge 
First, thanks for your reply :)

- My PC is still 23H2, this condition showed up a couple weeks ago.
- I have already checked my task scheduler. The settings of the trigger are same as yours.
- I have also tried to delete Ghelper from the task scheduler, and then untick/re-tick "Run on Startup". The tray icon shows up in the first 1 or 2 Restarts. And disappears after several Restarts. 
- Whether tray icon show up or not, Ghelper always Run on Restart without any problems (I checked it in Taskmgr). So... I think it is a system bug, and I don't konw how to deal it. :( 

I can only start Ghelper.exe after Startup. XD

**Comment by seerge** [comment]
@EmpressPENG ok, can you manually edit startup task and increase Delay task from 1 second to something like 5 seconds ?

**Comment by EmpressPENG** [comment]
@seerge 
OK! Problem solved! :)
Full of gratitude to you for helping.
I will do my own research next time when facing problem. Thanks a lot!!!

**Comment by seerge** [comment]
@EmpressPENG ok, can you actually experimentally find minimum delay that still keeps tray icon ok ? 

Cause before I have added 1 second delay as well, in order to "fix" someone else having similar problem. But setting it to 5 for everyone may be too much ...

**Comment by EmpressPENG** [comment]
@seerge 
2 second is enough

**Comment by gabezal** [comment]
Just adding my 2 cents, but there's no need to guess how long it takes for explorer to start up and show it's taskbar. I think the proper fix for this is to use WM_TASKBARCREATED: https://bobobobo.wordpress.com/2009/03/30/adding-an-icon-system-tray-win32-c/. It also helps with the startup delay when creating the shell tray icon fails, not just with explorer restarting. No idea if it still works in Win11 though.

**Comment by seerge** [comment]
@gabezal it's an interesting find. But I'm not sure if the problem is only with a tray icon. 

@EmpressPENG - if you are still there, can you try to set delay back to 0 (to trigger issue again) and check if main app window appears (or not) when you press M4 key while tray icon is absent

**Comment by EmpressPENG** [comment]
@seerge The problem is only with the tray icon. I press M4 without tray icon in the taskbar, the app window can appear correctly. Ghelper run in the background correctly. 
And I don't know how to run the code in the previous comment.

**Comment by seerge** [comment]
@EmpressPENG you don't need to run the code :) what i wanted to test if app is actually in a sane state and able to show window (M4 test proves that)
