### ISSUE TITLE
Incorrect Charge Rate Variation When Charging at Low Power

### ISSUE THREAD

**Issue by Yumi0606** [seerge/g-helper#3278]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Using google translate to this issue,sorry!

我注意到充电（放电）功率被固定为一个正数，而不是充电时显示正数，放电时显示负数。
而且，现在充电中和放电中的显示完全取决于电脑是否插上了电源线，而不是实际的电量变化率。
I noticed that the charging (discharging) power is fixed to a positive number, instead of a positive number when it charges and a negative number when it is discharging .
And, the display of "charging:"  and "discharging:"  now depends entirely on whether the computer is plugged into the power cord or not.

这样会导致，当使用者插上小功率电源线并且消耗着较大的电量时，GHelper仍然显示“充电中：34.4W”，实际上电脑可能正在以34.4W的功率耗电。
This results in the GHelper still showing “Charging: 34.4W” when the user is plugged into a low-power cord and consuming a large amount of power, when in fact the computer may be consuming 34.4W of power.

![image](https://github.com/user-attachments/assets/991fe5c3-e6b6-4564-95ae-b3a11e2bb924)

所以我希望能够修复这个小错误，只需要允许充电速率显示为负数，即它显示"充电中：-12W" 表示 充电功率100W -耗电功率112W = 实际变化功率-12W。充电和放电的显示不需要修改。
So I'm hoping to fix this little bug by just allowing the charge rate display to be negative, i.e. it says “charging: -12W” which means `charging power 100W - power consumption 112W = actual change in power -12W`. The charging and discharging displays don't need to be changed.

### How to reproduce the bug?

打开电脑性能模式玩游戏，并且插上5V1A的type-c充电线。
Turn on PC performance mode to play games and plug in a 5V1A type-c charging cable.

### Logs

[log.txt](https://github.com/user-attachments/files/17455528/log.txt)

### Device and Model

ASUS FX507

### Armoury Crate

Uninstalled

### Asus Services

7

### Version

0.196.0

### OS

Windows11 23H2

**Comment by seerge** [comment]
@Yumi0606 hello, charge and discharge rate are **separate** readings.

G-Helper shows data that windows itself reports. You can get it directly by running following command in powershell:
```
Get-CimInstance -Query "SELECT * FROM BatteryStatus" -Namespace "root\WMI"
```

So if you see `Charging: 34w` (or 20w as on screenshot or any other value) - this is what windows reports. You can cross check it using HWinfo or any other similar app.

So what you see is correct according to the system. There are no other alternative readings.

Thanks.
