### ISSUE TITLE
Zenbook Duo screenpad controls not working and more

### ISSUE THREAD

**Issue by UX8402ZE** [seerge/g-helper#3281]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

1. Camera hotkey non functional, when pressed the pop up appears but doesn't affect the camera even when G-helper is ran as admin.
2. All asus services are stopped in extras but the hotkeys for the screenpad controls dont work such as Fn + Shift + F7 / F8.
3.  I've learned that the hotkey must exist for it to function which is why FN+V/C/F4 doesn't work for me but I used to have FN+F which would change performance mode. Is there a workaround to get that to work again in G-helper?

### How to reproduce the bug?

Issues are always there.

### Logs

[log.txt](https://github.com/user-attachments/files/17472796/log.txt)

### Device and Model

Asus Zenbook Pro 14 Duo UX8402ZE

### Additional information.

M1, M2, M3 and M4/ROG work but the rest of the hotkeys not.
![image](https://github.com/user-attachments/assets/3ce39267-dbd5-4189-ac03-665428b78af9)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.196.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@UX8402ZE hello,

1. Camera hotkey toggles following setting in windows (try to change it and then reopen settings page to verify)
![Screenshot 2024-10-22 104643](https://github.com/user-attachments/assets/47664a04-322b-4c9c-8421-1d4619f2d3e1)

2. ``Fn + Shift + F7 / F8.`` didn't work cause your device does not contain DUO in a model name (in windows). I have manually added your model so try this build, it should work

3. I'm not aware about keycode that `FN+F` produces (on other devices it does nothing), I can only suspect it's 157 ? Can you check what WMI event # is being added to the log when you press it ? (like ``22.10.2024 00:39:53: WMI event 157`` ?)

[GHelper.zip](https://github.com/user-attachments/files/17473094/GHelper.zip)

**Comment by UX8402ZE** [comment]
when pressing FN+F this appears under WMI Activity:
ProviderInfo for GroupOperationId = 766; Operation = Provider::CreateInstanceEnum - CIMWin32 : Win32_Process; HostID = 5140; ProviderName = CIMWin32; ProviderGuid = {d63a5850-8f16-11cf-9f47-00aa00bf345c}; Path = %systemroot%\system32\wbem\cimwin32.dll

**Comment by UX8402ZE** [comment]
the event number is 12

**Comment by UX8402ZE** [comment]
In the new build FN+F replaces the M4/ROG button so that they now do the same function. It is possible to have FN+F be default for performance mode and the ROG (MyAsus button) to open/close ghelper?

Fn + Shift + F7 / F8 still doesn't work in the build but I now have the options for screenpad brightness in the drop down menu.

![image](https://github.com/user-attachments/assets/26237fd1-f3b1-42bd-b4c9-7bb92ccf78d2)

**Comment by seerge** [comment]
@UX8402ZE 

1. You don't need to toggle that setting in windows by yourself. What I meant is that G-Helper toggles this setting when you press mic hotkey. This is the only known way to me to toggle camera ON or OFF :) When camera access is set to OFF in windows apps won't have access to it.

2. It could be that `FN + F7 / F8` by itself don't produce any keycodes on your model and just directly control windows brightness on hardware level. Do you see any entries being added to log.txt when you press them ? If no - then there is no keycode, so catching them will be impossible.

> Event number 12
ProviderInfo for GroupOperationId = 766; Operation = Provider::CreateInstanceEnum - CIMWin32 : Win32_Process; HostID = 5140; ProviderName = CIMWin32; ProviderGuid = {d63a5850-8f16-11cf-9f47-00aa00bf345c}; Path = %systemroot%\system32\wbem\cimwin32.dll

3. Where is that ? I don't see it anywhere in log.txt. But since you say that `FN+F` now does same as M4 - my initial guess that keycode is `157` was correct. This build should toggle performance modes from `FN+F` and also backwards with `FN+SHIFT+F`.

[GHelper.zip](https://github.com/user-attachments/files/17473559/GHelper.zip)

**Comment by UX8402ZE** [comment]
You are indeed right it seems that FN+F7/F8 doesn't seem to exist for my model. Is there anyway to make a custom hotkey for brightness up and down for the UX8402 model. As far as I remember the brightness of the screenpad was only adjusted with the screenxpert UI.

In the new build Fn+F lowers the screenpad brightness (which I don't mind, I'll just control the performance with M4/ROG) but I can't seem to bring the brightness back up.

Camera button does toggle the setting but when the camera is on and then the button is pressed the camera remains on. Also the red light doesn't work when disabling the camera.

**Comment by seerge** [comment]
@UX8402ZE 

> You are indeed right it seems that FN+F7/F8 doesn't seem to exist for my model. Is there anyway to make a custom hotkey for brightness up and down for the UX8402 model. As far as I remember the brightness of the screenpad was only adjusted with the screenxpert UI.

You can try to assign (available on your model) hotkeys under `Extra`. Also you have dedicated screenpad button as I remember? :)
I can try to add some custom key combos for that (like `CTRL+SHIFT+ALT+F7/F8`), but i'm not sure if this is a good idea

> In the new build Fn+F (=Fn+F4 in ghelper) lowers the screenpad brightness (which I don't mind, I'll just control the performance with M4/ROG) but I can't seem to bring the brightness back up.

My bad ... i have set it to FN+F4 instead of FN+F5  :) try this build 
[GHelper.zip](https://github.com/user-attachments/files/17473801/GHelper.zip)

> Camera button does toggle the setting but when the camera is on and then the button is pressed the camera remains on. Also the red light doesn't work when disabling the camera.

Well, it remains on but it's not accessible to apps. That's best I can do. How did it work when you toggled it via asus app ?

**Comment by seerge** [comment]
@UX8402ZE this build should control screenpad brightness also with `CTRL+SHIFT+ALT+F7/F8`

[GHelper.zip](https://github.com/user-attachments/files/17474160/GHelper.zip)

**Comment by UX8402ZE** [comment]
@seerge that is perfect!! it works wonderful

> Well, it remains on but it's not accessible to apps. That's best I can do. How did it work when you toggled it via asus app ?

previously with MyAsus the camera button would disable/enable the camera instantly (light indicator as well) however it wouldn't affect the camera in privacy settings. Here's a video:

https://github.com/user-attachments/assets/6b74c06d-3301-455a-9943-da5ae5d8ce67

**Comment by seerge** [comment]
@UX8402ZE well, if you really want to bother with that - it's possible to **try to** reverse-engineer how it was doing this (without guarantees it will work tho).

You will have to install special app to intercept ACPI calls and then run this toggle using asus tools and check what it catches
Here is a quick guide on what needs to be done https://github.com/seerge/g-helper/wiki/_ACPI-Monitoring-and-Debugging

Let me know if you want to try

**Comment by UX8402ZE** [comment]
@seerge I'm really not tech savy but I'll give it a go

**Comment by seerge** [comment]
@UX8402ZE before you do that, can you check what exactly happens to camera device in windows Device Manager ?

Does it disappear completely ? Or gets disabled ? Or just stays as is ?

**Comment by UX8402ZE** [comment]
@seerge it stays as is, the devices are still there.

**Comment by seerge** [comment]
@UX8402ZE ok, then it's probably some proprietary hardware-toggle there

**Comment by UX8402ZE** [comment]
@seerge Im most likely not going through with the reverse engineering since my laptop almost got bricked just decrypting it. Thank you very much you resolved all my issues :)

**Comment by seerge** [comment]
@UX8402ZE you mean disabling windows encryption / bitlocker? I honestly don't get why windows has it ON by default even  :)

But ok, no worries. Then I'm closing this as resolved, and will include new hotkeys in next release

**Comment by UX8402ZE** [comment]
@seerge yup its such a pain and perfect I hope this helps other DUO users!

**Comment by ImBehinYa** [comment]
Hi @seerge  UX482EA also doesnt contain DUO 


> 2\. `Fn + Shift + F7 / F8` didn't work cause your device does not contain DUO in a model name (in windows). I have manually added your model so try this build, it should work

![image](https://github.com/user-attachments/assets/44c48afb-b6d5-4e1f-a4d6-bedcdece7745)

**Comment by seerge** [comment]
@ImBehinYa hello, I have added your device to the list of DUO models too
[GHelper.zip](https://github.com/user-attachments/files/18413726/GHelper.zip)
