### ISSUE TITLE
More User friendly way to add custom Screen Refresh Rate

### ISSUE THREAD

**Issue by fayizshaffaq** [seerge/g-helper#3284]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

What a co-incidence! I was just thinking about writing a request for allowing Custom Refresh Rate Option and someone had already asked it and it was introduced in build 197. I can confirm the custom refresh rate works well after altering the config file by adding "min_rate": xx, BUT I have 3 requests 

### Describe the solution you'd like
1. Please keep the "min_rate": xx, line already written inside of the config file, users would just have to input the desired custom refresh rate and not have to remember the "min_rate": xx, line or copy paste it every time there is a new version available OR every time they do a clean install of windows. 

2. After the new refresh rate is added would it be possible to have 3 options to choose from as illustrated in the attached screen shot? Please also allow changing the max refresh rate in the config file Just to have an option of being able to do it. 
![image](https://github.com/user-attachments/assets/cb8f2e9b-c414-403c-8edf-59d371645d80)

3. Please consider adding the current Power watts being used by the CPU/ GPU it could be shown when clicking on the existing CPU/GPU Temps and switch to showing watts being used by the CPU/GPU instead.(similar to how HWinfo software tells you the current power consumption) 
![image](https://github.com/user-attachments/assets/26a8c604-61b5-49ea-8ac7-ce29ab905e91)

### Device and Model

Asus Tuf F15 2022 (FX507ZE) 

### Additional information.

Thank you For this AMAZING software!

**Comment by seerge** [comment]
@fayizshaffaq hello,

This is actually 3 separate requests

1. Power user settings are called like that on purpose. As I'm adding config-only settings when they won't be used by 99% of the users. If people have troubles editing config they will have troubles even when one of the lines will be already present there.

2. Fourth spot in the grid is already reserved for Miniled toggle (see screenshot for example). Why would you add 47Hz even? It will make everything super choppy and won't save you much power anyway.
![image](https://github.com/user-attachments/assets/e095c692-ce45-4865-8d2b-f43a98dec32f)

3. I can try to add CPU / GPU power measurements, but not to the main window and not now. I had some ideas of actually adding an overlay showing some metrics, there it would fit. Also it's quite difficult to get some measurements, as unlike temps / fan speeds they are not reported by Asus firmware, and needs to be taken from drivers - different for AMD, Nvidia and Intel.

Thanks

**Comment by fayizshaffaq** [comment]
Thanks for responding @seerge  

1. That makes sense to have a config file for only power users, if 99% of people wont use it, then it's indeed pointless. You are right! 

2. Oh I did not know the 4 spot was already occupied by Mini Led. I don't have a mini led enabled device so I didn't know. 

3. Please don't add the Power Watt measurement if it's not easily provided by the Asus firmware. G-Helper is very Lightweight along with being functional and all of it works surprisingly well, The last thing I want is for you to introduce features that somehow cause the software to not work as intended for some users given the diversity of devices with AMD/Intel chips. And adding more features might only make it bloated. right now it's perfect. 

Thank you!

**Comment by seerge** [comment]
@fayizshaffaq ok, great

Then i'm closing it as not planned as 1 and 2 are answered and 3 is a very big-separate (sub)project that I may eventually do, but not now and not in the main app UI.

Thanks
