### ISSUE TITLE
Using a keyboard key to switch GPU modes

### ISSUE THREAD

**Issue by IncognitoFawkes** [seerge/g-helper#3285]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

It'd be great if we could set one of the key binds to switch between GPU Modes. I primarily use Eco and Ultimate, and it'd be great if I could map this to my aura key and use that to switch between the iGPU and the dGPU.

### Describe the solution you'd like

Have an option in Custom Keymaps to map one of the keys to be able to switch between GPU Modes

### Device and Model

ASUS ROG Flow x16 GV601RM

**Comment by seerge** [comment]
@IncognitoFawkes hello, [this is already possible](https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings) for `Standard` and `Eco`. For `Ultimate` you still need to confirm a reboot and actually reboot after, so hotkey won't work here.

`Ctrl + Shift + Alt + F14` - Eco GPU Mode
`Ctrl + Shift + Alt + F15 `- Standard GPU Mode

If you want to bind one of macro keys to this actions, you just need to set them to emit this custom [hotkey as explained here](https://github.com/seerge/g-helper/wiki/Power-user-settings#custom-hotkey-actions)

For example code for `Eco` hotkey would be
``0x11 0x12 0xA0 0x7D``
