### ISSUE TITLE
Adding animation when switching video card modes

### ISSUE THREAD

**Issue by Edelwis** [seerge/g-helper#3286]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

When switching between Eco and Standard video card modes using hot keys with the following corresponding key codes _0x11 0x12 0xA0 0x7D_ and _0x11 0x12 0xA0 0x7E_ there is no additional information that describes what happened.

### Describe the solution you'd like

When switching processor modes such as Eco, Balance and Turbo, there is a corresponding animation with the mode name describing what happened. It would be informative to add a similar implementation when switching video card modes.

### Device and Model

Asus Zephyrus G14 GA401QM

**Comment by seerge** [comment]
@Edelwis hello, try this build. It should show a toast notification, but only when you switch GPU mode from a hotkeys.

[GHelper.zip](https://github.com/user-attachments/files/17490296/GHelper.zip)

**Comment by Edelwis** [comment]
Yes, this is what I needed. Works great.
