### ISSUE TITLE
Disable "Windows Power Mode" switching

### ISSUE THREAD

**Issue by Katzenwerfer** [seerge/g-helper#3287]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

In a recent Windows update, a button was added to the power settings to choose battery and plugged-in "Windows Power Mode" separately. Currently, G-Helper only modifies the plugged-in mode when switching profiles.

### Describe the solution you'd like

I would like to be able to disable this feature to manage it directly from the system's settings.

### Describe alternatives you've considered

Ideally, it must be possible to set modes for both cases inside G-Helper's profiles, but having the ability to disable it outright would be nice too.

### Device and Model

Asus TUF Gaming A17

### Additional information.

![image](https://github.com/user-attachments/assets/1e2f2f7a-f4a5-4ee0-b6d1-44249c254d1a)

**Comment by seerge** [comment]
@Katzenwerfer hello, is it in a new 24H2 windows update ? Cause I don't have that options in the settings.

Currently app uses windows API to set an "overlay power scheme" (this is how power modes are called there)
https://github.com/seerge/g-helper/blob/15501c78458aa7e52fda554e4825c19dd9d1fe70/app/Mode/PowerNative.cs#L72

But that doesn't separate if mode is on battery or plugged in.

Of course you already get automatic power mode changes anyway, cause G-Helper just remembers last used mode per battery / plugged in case and sets it . And this affects not only windows power mode but also "bios-mode", i.e. Silent / Blanced / Turbo

**Comment by Katzenwerfer** [comment]
> is it in a new 24H2 windows update ? Cause I don't have that option in the settings.

I would assume, I'm using an LTSC edition of Windows, so I would guess this was included in a recent quality update.

> But that doesn't separate if mode is on battery or plugged in. I can imagine it would adjust "on battery" mode when you are actually on battery ? Can you check ?

This seems to be the case, the modified scheme depends on whether the device is plugged in or not

**Comment by seerge** [comment]
@Katzenwerfer ok, so it actually already works as it should? Adjusts battery power mode when on battery?

**Comment by Katzenwerfer** [comment]
> @Katzenwerfer ok, so it actually already works as it should? Adjusts battery power mode when on battery?

Indeed it does

**Comment by Katzenwerfer** [comment]
> I would like to be able to disable this feature to manage it directly from the system's settings.

That said, I do wonder if there would be a possibility to have the former request, as to respect whatever Windows has set already.
I still want to disable the power mode switching to control both cases separately, even on a same profile.

**Comment by seerge** [comment]
@Katzenwerfer ok, even though I sincerely don't understand why you need that I have added an optional param that you can set under `%appdata%\GHelper\config.json` to skip power mode setting completely

Add
```
"skip_powermode": 1,
```

And try this build
[GHelper.zip](https://github.com/user-attachments/files/17527230/GHelper.zip)

**Comment by NatsuZoraKanata** [comment]
With the addition of the optional parameter, is Ghelper not hiding the Windows Power Mode option from the GUI?
Hopefully it will be possible to hide this option and leave it entirely up to Windows settings.

**Comment by seerge** [comment]
@NatsuZoraKanata when Power Mode switching is disabled - Fans + Power will just show currently active Power Mode in windows (it reads it. I think it's good to keep it :)
