### ISSUE TITLE
Game not detecting DGPU

### ISSUE THREAD

**Issue by sinbad1111** [seerge/g-helper#3288]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I uninstalled AC on my asus tuf laptop and installed G Helper since it is more efficient and easy to use. However, after finishing the g helper set up and ready to play Valorant, my game is just stuck on 60 fps and I can't play properly. Normally my fps ranges when not using g helper was around 180-200+fps. I even optimized my setting on valorant on the graphics setting (i chose my DGPU). I hope I can receive a solution for this since I am very eager and interested in using the G Helper. 

### How to reproduce the bug?

![Uploading Screenshot 2024-10-23 141705.png…]()

### Logs

%APPDATA%\GHelper\log.txt

### Device and Model

Asus TUF Gaming F15 FX506HC

### Additional information.

![Screenshot 2024-10-23 141705](https://github.com/user-attachments/assets/06f06a43-aced-4f0d-8721-458f9e267e4d)

### Armoury Crate

Uninstalled

### Version

0.194

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@sinbad1111 hello, G-Helper is not defining what GPU will be used by your game. It's up to the game itself, windows and Nvidia drivers.

Most likely you have some kind of a FPS limiter enabled in Nvidia control panel or Nvidia experience (for example **Whisper Mode** enabled). So make sure to turn them all OFF.

Thanks

**Comment by sinbad1111** [comment]
Really appreciate the fast response but I cant find whisper mode on my nvidia control panel

**Comment by seerge** [comment]
@sinbad1111 it's usually under Nvidia Experience settings. You can also try to reset all settings under Nvidia Control panel to defaults

**Comment by seerge** [comment]
@sinbad1111 https://www.reddit.com/r/pchelp/comments/1dhor3r/all_my_games_are_capped_at_60fps/

**Comment by sinbad1111** [comment]
Finally got the time to fix it by following your instructions and it finally worked. Thank you so much for the fast response, really appreciate it.

**Comment by seerge** [comment]
@sinbad1111 great, what exactly helped ? resetting control panel or turning off whisper mode under nvidia experience ?

**Comment by sinbad1111** [comment]
i reset all my nvidia control panel to default and i uninstalled my geforce experience (the newer version) then i downloaded the older version
