### ISSUE TITLE
Screenpad off as soon as in sleep mode

### ISSUE THREAD

**Issue by UX8402ZE** [seerge/g-helper#3289]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Screenpad on DUO device goes off as soon as i put my laptop in standby/sleep or even turn off. Is there a possibility to keep the screen on and from disconnecting? 

I already had another issue which you solved so I would like to use the same build you made.
[GHelper.zip](https://github.com/user-attachments/files/17493075/GHelper.zip)

### How to reproduce the bug?

Closing the lid, sleep, shutting down the device produces the problem

### Logs

[log.txt](https://github.com/user-attachments/files/17493030/log.txt)

### Device and Model

Asus Zenbook Pro 14 Duo UX8402ZE

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.196.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@UX8402ZE hello,

G-Helper is not controlling that and furthermore not even able to especially when device goes to sleep, so windows suspends all processes.

As I understand Screenpad is just another display from windows point of view, so it's logical windows shuts down all displays when device goes to sleep. You can't keep monitors on when laptop is sleeping.

Thanks
