### ISSUE TITLE
Clock is sized incorrectly on G14 2022 GA402RJ - AniMe Matrix

### ISSUE THREAD

**Issue by flankytingz** [seerge/g-helper#329]
The clock is sized incorrectly, the M in AM/PM is cut-off.

![WhatsApp Image 2023-05-06 at 11 06 57](https://user-images.githubusercontent.com/82509155/236639782-01e2b29e-a6a3-4aa6-bec0-4757b5421632.jpg)

- OS = Win11 22H2 22621.1555
- G-Helper = v0.57
- MyASUS installed

**Comment by seerge** [comment]
@flankytingz hello, in 0.58 it should be fine https://github.com/seerge/g-helper/releases/tag/v0.58
