### ISSUE TITLE
Increase Core Clock Offset Limit for Aggressive Undervolting on ROG Strix G18

### ISSUE THREAD

**Issue by VictorXP** [seerge/g-helper#3290]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Achieved 2280 MHz at 130W with 75-80°C temps on RTX 4080 in my ROG Strix G18 laptop using G Helper. However, the Core Clock Offset is currently limited to +250 MHz, restricting further undervolting potential. Requesting to increase this limit to enable more aggressive undervolting.

Technical Details:
- Laptop: ROG Strix G18
- Graphics Card: RTX 4080
- Current Core Clock Offset Limit: +250 MHz
- Desired Core Clock Offset Limit: +750 MHz

### Describe the solution you'd like

Desired Core Clock Offset Limit: +750 MHz

### Device and Model

ROG Strix G18

**Comment by seerge** [comment]
@VictorXP hello,

This is already possible, you can override maximum possible clock / memory clock offsets in via app config. Please check how to do it under [Power User settings ](https://github.com/seerge/g-helper/wiki/Power-user-settings#higher-maximum-and-minimum-gpu-clock--memory-offsets)

Thanks

**Comment by VictorXP** [comment]
Thank you!
