### ISSUE TITLE
Slash Lighting not disabling on lid close when "Disable on Lid Close" is checked on

### ISSUE THREAD

**Issue by kheperaptah** [seerge/g-helper#3293]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

As the title says, even though "Disable on Lid Close" is checked; occasionally there are issues when the laptop slash lighting does not disable. This is utilizing the G14 2024 model on v0.197.0.

### How to reproduce the bug?

1. Enable Disable on Lid Close
2. Close the Lid and slash lighting continues

### Logs

[log.txt](https://github.com/user-attachments/files/17497496/log.txt)

### Device and Model

ASUS ZEPHYRUS G14 GA403UV

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.197.0

### OS

Windows 11 24H2

**Comment by seerge** [comment]
@kheperaptah hello,

- What kind of animation do you see when lid is closed ? is it same one that was before or special blinking (sleep) animation?
- Did you uninstall AC using official uninstaller from Asus? Can you check Task Manager in windows if there are any Asus processes running?
- Did you set [Slash Sleep animation param in config](https://github.com/seerge/g-helper/wiki/Power-user-settings#slash-lighting-sleep-animation-on-lid-close) ? If you didn't modify config manually - answer would be - NO :)

**Comment by kheperaptah** [comment]
@seerge
Hey, thanks for the fast reply!

1. The animation is the same one that's set manually in the G-Helper UI (in this case its Flux)
2. Yeah, I uninstalled armoury crate. I checked Task manager and the only one I see active right now is ASUS PTP Service.
3. Nope!

Btw, I think I've managed to find some consistency with this bug. It seems to occur when I press the power button before closing the lid or when it falls asleep first.

**Comment by seerge** [comment]
@kheperaptah then you have your answer. You put laptop to sleep -> windows suspends all apps (including G-Helper) and when lid is closed there no one to turn Slash Lighting OFF (as this is a separate command). You need to have laptop awake in order to make this feature work :)

**Comment by kheperaptah** [comment]
I see, that makes sense; I didn't realize it a limit by nature of how the operation system works. Thank you very much!
