### ISSUE TITLE
M1, M2 buttons working incorrectly.

### ISSUE THREAD

**Issue by leftedz** [seerge/g-helper#3294]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I was in Counter Strike Global Offensive Legacy changing binds and when i press either M1 or M2 button it registers as C and B respectively for some reason. When i try to type these letters in any field though they don't respond as C or B and rather work as intended.  Also when I'm on this website https://www.keyboardtester.com/tester.html my trackpad disabler button acts as CTRL+WIN+F24 and my Volume off button as "-". What could be reason to this?

### How to reproduce the bug?

I tested this in Fortnite and CSGO Legacy binds menus. In Fortnite this bug seems to not work.

### Logs

[log.txt](https://github.com/user-attachments/files/17498422/log.txt)

### Device and Model

Asus TUF A15 FA507RE

### Additional information.

I just encountered this and don't know where this bug can be seen outside of CSGO.

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.194.0

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@leftedz hello,

M1 and M2 emit windows media volume controls on hardware level, **they are not handled by G-Helper** (unless you explicitly bind them to something else under `Extra`, which you did not). Do they work as volume controls in windows? I

Trackpad disable hotkey is indeed  CTRL+WIN+F24. It's [absolutely correct binding](https://www.reddit.com/r/Windows10/comments/nv5cdr/hidden_windows_key_hotkeys/) in windows

Volume off is also a hardware key in windows. Does it mute volume in windows when you press it ?

**Comment by leftedz** [comment]
Hello! Yes, as i mentioned in windows they perform as intended(Change volume respectively), but while i was in CSGO they were acting as C and B buttons for some reason. And i didn't bind them to anything beforehand. Also yes all buttons do work as intended in windows, it's just thing with CSGO.

**Comment by seerge** [comment]
@leftedz then it's something inside CS:GO and not related to G-Helper :)

**Comment by leftedz** [comment]
Seems to be about right. :)

**Comment by seerge** [comment]
@leftedz reason I asked if you binded M1 / M2 to something is cause i see following in the log
```
24.10.2024 1:04:47: VolumeDown None
24.10.2024 1:04:47: Launching "C:\Windows\system32\cmd.exe" /C 	0x01
````

It means that M1 (that emits VolumeDown) was mapped to some custom action (0x01) which is left mouse button i think ? So G-Helper would intercept VolumeDown in this case and emit something else.

If you would set M1 to perform default action (Volume Down) G-Helper won't intercept it at all, and let it do it's thing on hardware level

**Comment by leftedz** [comment]
Yes, i did map volumedown as left mouse button just to try "custom" feature and see how it gonna impact CSGO. But i discovered issue before i custom mapped it.

**Comment by seerge** [comment]
@leftedz ok, clear.

Then if default Volume Down (or Up) are interpreted by CSGO internal binding as as C or D i assume that's something specific to the game itself :)

**Comment by leftedz** [comment]
Thank you for quick assistance and for your wonderful app!
