### ISSUE TITLE
discharge indicator taking too long to refresh

### ISSUE THREAD

**Issue by testerrr12345** [seerge/g-helper#3295]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

laptop discharge indicator taking too long to refresh ( sometimes 1minute) instead of 2s which prevents me from checking my real time consumption 

### How to reproduce the bug?

just open ghelper

### Logs

[log.txt](https://github.com/user-attachments/files/17508155/log.txt)

### Device and Model

Asus zephyrus g16 (2024) GU605MY 

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.194

### OS

windows 11 24H2

**Comment by seerge** [comment]
@testerrr12345 hello,

App refreshes discharge rate from windows every **2 seconds**. However the reading itself that sysem provides updates much less frequently and it also depends on battery / laptop model . In some cases it could be every 10 seconds, in some 60 seconds. I can't change this anyhow.

Thanks.

**Comment by RealTadango** [comment]
Why can other apps refresh MUCH faster? When i set batteryinfoview to 2s it refreshes very fast while G-helper takes a very long time to refresh. Looks like G-helper uses the indication from Windows wich also does not refresh often. Please use a different approach like batteryinfoview does.

@seerge it really is possible, please have look because this would be a big gain for me.

**Comment by seerge** [comment]
@RealTadango hello,

I'm aware about only one way to get discharge rate - via windows WMI `SELECT * FROM BatteryStatus`. From my observations on some models windows update this metric very often (literally every second), on some - much less (like once per 30 seconds or so)

**Comment by RealTadango** [comment]
@seerge I found something. When i have batteryinfoview  running at a 2s refresh rate G-Helper updates as fast. So both use the same source but somehow batteryinfoview triggers a forced refresh. That would explain the difference in laptops and refresh rates. But if batteryinfoview can force a quick refresh i am sure G-Helper can too ;)

**Comment by seerge** [comment]
@RealTadango it could be triggering some internal system battery reading updates. So windows WMI also reports changes fast. But since it's not open-source I don't know how it does it.

On a side note - more frequent updates mean more power consumption and (actual) faster battery drain :)

**Comment by RealTadango** [comment]
Yes so only extra updates when the screen is shown ;)
