### ISSUE TITLE
Fn+C/Fn+V快捷键无效

### ISSUE THREAD

**Issue by Xuanzheng0901** [seerge/g-helper#3298]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

在GHelper中设置Fn+C为切换Fn锁定,但按下Fn+C时无反应,且无日志输出

### How to reproduce the bug?

按下Fn+C无反应

### Logs

2024/10/25 13:42:04: ------------
2024/10/25 13:42:04: App launched: ASUS TUF Gaming F16 FX607JV_FX607JV :0.194.0.0zh-CN.
2024/10/25 13:42:04: Start Count: 3
2024/10/25 13:42:05: Matrix control device was not found on your machine.
2024/10/25 13:42:06: NVIDIA GeForce RTX 4060 Laptop GPU
2024/10/25 13:42:07: CPU: -1 - 13th Gen Intel(R) Core(TM) i9-13980HX - Intel64 Family 6 Model 183 Stepping 1
2024/10/25 13:42:07: AutoSetting for Online
2024/10/25 13:42:07: Eco flag : 0
2024/10/25 13:42:07: Mux flag : 0
2024/10/25 13:42:07: \\?\DISPLAY#AUO75AC#5&88874d&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
2024/10/25 13:42:07: \\?\DISPLAY#AUO75AC#5&88874d&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2024/10/25 13:42:07: B160QAN02.7  HDR: False 8 4 True
2024/10/25 13:42:07: Mode = 2 : OK
2024/10/25 13:42:07: TUF_KB = 16712125 : OK
2024/10/25 13:42:07: AuraMode: AuraColorCycle
2024/10/25 13:42:07: TUF RGB = B4-02-FF-1E-40-EB : OK
2024/10/25 13:42:07: B160QAN02.7  HDR: False 8 4 True
2024/10/25 13:42:08: TUF Brightness = 131 : OK
2024/10/25 13:42:08: PowerLimit A3 = 30 : OK
2024/10/25 13:42:08: PowerLimit A0 = 40 : OK
2024/10/25 13:42:08: Monitor Power On
2024/10/25 13:42:08: Lid Open
2024/10/25 13:42:08: TUF Brightness = 131 : OK
2024/10/25 13:42:08: Latest version 0.194.0.0
2024/10/25 13:42:15: Design Capacity: 90005mWh, Full Charge Capacity: 87007mWh, Health: 0.9666907394033664796400199989%
2024/10/25 13:42:17: Input device not found
2024/10/25 13:42:25: BatteryLimit = 100 : OK

### Device and Model

 ASUS TUF Gaming F16 FX607JV_FX607JV

### Additional information.

其他的Fn快捷键都可用且有效

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.194.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Xuanzheng0901 hello, 

Some TUF models simply don't support FN+C on hardware level. You need to bind FN-Lock to other hotkey or use a button in the main app window.

Thanks.
