### ISSUE TITLE
RGB software off

### ISSUE THREAD

**Issue by bigggggert** [seerge/g-helper#3299]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

My problem is that g-helper blocks OpenRGB and that program has a lot more customisability for my laptop.

### Describe the solution you'd like

A button to turn the rgb software off and not the rgb.

### Device and Model

Asus Zephyrus GX501GI

**Comment by seerge** [comment]
@bigggggert hello,

This is already possible. You just nee to add following line to `%appdata%\GHelper\config.json`
```
"skip_aura" : 1,
```

As explained in [power user settings](https://github.com/seerge/g-helper/wiki/Power-user-settings#skip-keyboard-aura-initialisation-on-startup)

Thanks

**Comment by bigggggert** [comment]
@seerge Thanks
