### ISSUE TITLE
Screenpad brightness resets after restarting

### ISSUE THREAD

**Issue by chockokruasan** [seerge/g-helper#3301]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I change screenpad brightness by fn+shift F7/F8. after laptop restarting screenpad resets brightness to default. Windows ignore last Ghelper brightness level and resets it. Screenxpert software uninstalled, screenpad service stopped.
I made a short video of issue: https://youtu.be/4RcR7WjgxaI

### How to reproduce the bug?

change brightness to max or to min and restart.

### Logs

Asus Zephyrus duo 16 GX650PZ

### Device and Model

Asus Zephyrus duo 16 GX650PZ

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.194

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@chockokruasan try this build
[GHelper.zip](https://github.com/user-attachments/files/17530708/GHelper.zip)

**Comment by chockokruasan** [comment]
Work! Thanks! Will you add this fix to next regular builds?

**Comment by seerge** [comment]
@chockokruasan yes, it will be included.
