### ISSUE TITLE
Fan control not reapplying on TUF A14

### ISSUE THREAD

**Issue by craterboy1** [seerge/g-helper#3302]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi,

I just bought a TUF A14 with the hx370. I noticed often times custom fan control will not reapply. After a while, it will revert back to the default setting unless manually reapplied

Regards

### How to reproduce the bug?

1. set custom file control
2. sleep or leave on a while 
3. change power mode to silent
4. notice fan is still spinning at default speeds

### Logs

[log.txt](https://github.com/user-attachments/files/17530588/log.txt)

### Device and Model

FA401WV-AI9R4060

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.197

### OS

win 11 24H2

**Comment by seerge** [comment]
P.S. I also see that you have asus services running in background that might interfere, it's better to stop them via `Extra`. Also AC needs to be uninstalled using dedicated official uninstaller from Asus.

```
10/26/2024 6:53:08 AM: Optimization service is running
```
