### ISSUE TITLE
Anime Matrix general position

### ISSUE THREAD

**Issue by joex92** [seerge/g-helper#3304]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

All the modes but Picture/GIF mode are set in place, and sometimes, in case of clock mode, it´s not centered (this was an issue too on AC) depending on the date or time, so sometimes a bit of the clock is not seen, it's not unreadable thou...

### Describe the solution you'd like

Being able to "move" the clock or the audio visualizer to place it or scale it (I believe moving it is easier) or even rotate it.
this could work with the logo too and any other future mode added.

It would be redundant for Picture/GIF mode thou...

### Describe alternatives you've considered

none

### Device and Model

Asus ROG Zephyrus G14 GA401QC

**Comment by seerge** [comment]
@joex92 hello,

By default picture is aligned to top-right corner of the matrix and scaled to fit to it completely (i.e. by 100% height or width), but you can already pan / resize them under `Picture` settings.

As for clock - it should be centered already, can you make a photo of how it looks in your case ?

**Comment by joex92** [comment]
this is how it looks:
![WhatsApp Image 2024-10-26 at 13 35 37_2a84ad43](https://github.com/user-attachments/assets/6790fe96-f218-4e6f-a504-f0573ef92350)
it´s not unreadable, but as you can see there's a little portion of the clock that is "outise of bounds"...

also it would be great for it to not be diagonal, or to move it a bit and scale it... that's why I'm suggesting it as a general position setting, it would be redundant for the Picture Mode, but the purpose would be for the other modes...

In case of the Audio VIsualizer, it would be cool to move it a bit up or to put it diagonally, etc.
![WhatsApp Image 2024-10-26 at 13 38 57_5bcf3b90](https://github.com/user-attachments/assets/b4433e7c-775e-444a-b68c-a47cc599883a)

**Comment by joex92** [comment]
I would suggest as well that the "Picture/Gif" button be changed to "Settings" (meaning it the selected mode settings), and depending on the mode it would be clickable or not, it's confusing to be able to open that setting while not using the picture/gif mode...

**Comment by seerge** [comment]
@joex92 try this build, it should adjust clock row a bit (you have 2021 model and there matrix is a bit smaller than on 2022 where I was fitting it)

[GHelper.zip](https://github.com/user-attachments/files/17531749/GHelper.zip)

I can rename Picture/GIF button to something else when that screen will contain more settings for other modes, atm everything there is related only to Picture

**Comment by seerge** [comment]
@joex92 any updates here ?

**Comment by joex92** [comment]
@seerge yes... Here's how it looks know with the version you shared:
![IMG_20241028_102655.jpg](https://github.com/user-attachments/assets/7e0fdfa5-9a0c-4a85-ba51-e3aadc6e06a0)
Now the date is not centered xD

**Comment by seerge** [comment]
@joex92 ok, I have overdone it probably, try this build instead
[GHelper.zip](https://github.com/user-attachments/files/17545009/GHelper.zip)

**Comment by joex92** [comment]
@seerge 🤔 the clock was ok, now it's not as centered... The date is not centered thou...
![IMG_20241028_105544.jpg](https://github.com/user-attachments/assets/522576b4-b768-4526-bc11-32cf40ba3c9f)

**Comment by seerge** [comment]
@joex92 both labels are aligned to left (in order to not to jump / shift when numbers change). This is actually how I'm trying to position it. Matrix LEDs don't cover full surface of the back panel :)

**Comment by joex92** [comment]
@seerge I know it doesn't cover the whole back panel, but comparing it with the whole LEDs on, the clock is still not centered 🤔...
![IMG_20241028_105951.jpg](https://github.com/user-attachments/assets/596423b7-9260-4d27-8782-61bd45e6b866)

**Comment by seerge** [comment]
@joex92 and it should not be. Font that is being used have symbols of different width. If I would center it - every time minute changes clock would be jumping left and right cause 1 is more narrow than 2 for example

**Comment by joex92** [comment]
@seerge oohh, ok... I get it... is it planned for the future to be able to change the font? or at least hardcode other fonts?

btw, what´s the difference between the Binary Banner and ROG Logo modes?? both look the same...

and what's the size of the panel? in pixels, i want to have a template to make some gifs and/or pictures to use...

**Comment by seerge** [comment]
@joex92 
> oohh, ok... I get it... is it planned for the future to be able to change the font? or at least hardcode other fonts?

If I will do a custom text -yes, for clock - not sure. 

Keep in mind that clock is auto-adapting to your local date format, i.e. ie. it can be 12H (with AM/PM) or 24H. So 12:45 PM is much wider than 3:11 for example. I'm just trying to keep things simple and universal so same font / size will fit all variants. 

>btw, what´s the difference between the Binary Banner and ROG Logo modes?? both look the same...

Should be different, but it could be that on older devices (like yours) it's simply only 1 hardcoded mode

> and what's the size of the panel? in pixels, i want to have a template to make some gifs and/or pictures to use...

For GA401 it's

```
MaxColumns = 33;
MaxRows = 55;
LedCount = 1245;
FullRows = 5;
```

**Comment by joex92** [comment]
@seerge 

> Keep in mind that clock is auto-adapting to your local date format, i.e. ie. it can be 12H (with AM/PM) or 24H. So 12:45 PM is much wider than 3:11 for example. I'm just trying to keep things simple and universal so same font / size will fit all variants.

would it be possible to use seconds on the clock? or would it make it too long?

> Should be different, but it could be that on older devices (like yours) it's simply only 1 hardcoded mode

What is the Binary Banner then? 🤔 
 
> For GA401 it's
> 
> ```
> MaxColumns = 33;
> MaxRows = 55;
> LedCount = 1245;
> FullRows = 5;
> ```

so does that mean that I can use a 55x33 pixels image? what does the FullRows refer to?

**Comment by seerge** [comment]
@joex92 

1. Seconds don't fit and make it very annoying to watch (cause they change all the time)
2. It's probably not supported on your device as I mentioned
3. It's a checkered structure with a skewed proportions. I think you can try 99 : 55 picture. Full rows stands for a number of rows on top that don't participate in diagonal cut

You can read / google more info about matrix layout https://www.reddit.com/r/ZephyrusG14/comments/ijo1xb/anime_matrix_screen_resolution/

Closing this as resolved since clock text fits now :) 

Thanks
