### ISSUE TITLE
ROG zephyrus G16 GU605MV GPU graphics mode can't be changed (function bar is missing), and fan speed can't be displayed either

### ISSUE THREAD

**Issue by Trinley668** [seerge/g-helper#3309]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

ROG zephyrus G16 GU605MV GPU graphics mode can't be changed (function bar is missing), and fan speed can't be displayed either！Very frustrated with this problem, but this software is excellent and I hope it can be fixed, thank you very much!

### How to reproduce the bug?

No graphics card mode has been displayed since installing this software, AC and ASUS related service programs were uninstalled prior to installation.

### Logs

2024/10/27 13:49:05: ------------
2024/10/27 13:49:05: App launched: ROG Zephyrus G16 GU605MV_GU605MV :0.197.0.0zh-CN.
2024/10/27 13:49:05: Start Count: 129
2024/10/27 13:49:05: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
2024/10/27 13:49:06: C:\ProgramData\ASUS\GameVisual\ASUS_DCIP3.icm DCIP3
2024/10/27 13:49:06: C:\ProgramData\ASUS\GameVisual\ASUS_DisplayP3.icm DisplayP3
2024/10/27 13:49:06: C:\ProgramData\ASUS\GameVisual\ASUS_sRGB.icm sRGB
2024/10/27 13:49:06: NVIDIA GeForce RTX 4060 Laptop GPU
2024/10/27 13:49:07: CPU: 0 - Intel(R) Core(TM) Ultra 9 185H - Intel64 Family 6 Model 170 Stepping 4
2024/10/27 13:49:07: AutoSetting for Online
2024/10/27 13:49:07: BatteryLimit = 100 : 0
2024/10/27 13:49:07: Eco flag : -65536
2024/10/27 13:49:07: Mux flag : -65536
2024/10/27 13:49:07: Input available: \\?\hid#vid_0b05&pid_19b6&col05#6&2caf62d7&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 63
2024/10/27 13:49:07: USB 19B6|63: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2024/10/27 13:49:07: Input: \\?\hid#vid_0b05&pid_19b6&col05#6&2caf62d7&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
2024/10/27 13:49:07: USB 19B6: 5D-B3-00-00-FF-FF-00-EB-00-00-FF-FF-00-00-00-00-00
2024/10/27 13:49:07: USB 19B6: 5D-B4
2024/10/27 13:49:07: USB 19B6: 5D-B5-00-00-00
2024/10/27 13:49:07: \\?\DISPLAY#SDC41A3#5&2ff708bb&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL
2024/10/27 13:49:07: \\?\DISPLAY#SDC41A3#5&2ff708bb&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY5\Monitor0
2024/10/27 13:49:07:  HDR: False 10 1 False
2024/10/27 13:49:07: Mode = 1 : 0
2024/10/27 13:49:07: VivoMode = 2 : 0
2024/10/27 13:49:07: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
2024/10/27 13:49:07: Init 19B6: 5D-B9
2024/10/27 13:49:07: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2024/10/27 13:49:07: Init 19B6: 5D-05-20-31-00-1A
2024/10/27 13:49:07: SlashEnable False:5E-D8-02-00-01-80-00-00-00-00-00-00-00-00-00-00-
2024/10/27 13:49:07: SleepInit:5E-D2-02-01-08-A1-00-00-00-00-00-00-00-00-00-00-
2024/10/27 13:49:07: USB 19B6: 5D-BD-01-5F-1F-FF-FF-FF
2024/10/27 13:49:07: AuraMode: GPUMODE
2024/10/27 13:49:07: Sleep False:5E-D3-03-01-08-A1-00-FF-00-02-FF-FF-00-00-00-00-
2024/10/27 13:49:07: USB 19B6: 5D-B3-00-00-FF-FF-00-EB-00-00-FF-FF-00-00-00-00-00
2024/10/27 13:49:07: USB 19B6: 5D-B4
2024/10/27 13:49:07: USB 19B6: 5D-B5-00-00-00
2024/10/27 13:49:07:  HDR: False 10 1 False
2024/10/27 13:49:08: Monitor Power On
2024/10/27 13:49:08: BatteryLimit = 100 : 0
2024/10/27 13:49:08: Lid Open
2024/10/27 13:49:08: Lid 19B6|63: 5A-BA-C5-C4-00
2024/10/27 13:49:08: SlashLidCloseAnimation False:5E-D8-00-00-02-A5-00-00-00-00-00-00-00-00-00-00-
2024/10/27 13:49:08: Auto 19B6|63: 5A-BA-C5-C4-00
2024/10/27 13:49:09: Latest version 0.197.0.0
2024/10/27 13:49:09: Design Capacity: 90005mWh, Full Charge Capacity: 90817mWh, Health: 1.0090217210154991389367257375%
2024/10/27 13:49:11: Unable to load DLL 'atiadlxx.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
2024/10/27 13:49:11: Hibernate after 2147483647
2024/10/27 13:49:12: Unable to load DLL 'atiadlxx.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
2024/10/27 13:49:12: Hibernate after 2147483647

### Device and Model

ROG zephyrus G16 GU605MV

### Additional information.

![screenshot-1730008092508](https://github.com/user-attachments/assets/aebcca6e-fb1f-4cb5-b140-d66a7b1ef5d9)

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.197.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Trinley668 hello,

From the log it looks like Asus System Control Driver is either completely missing or not working on your device. So it is impossible to communicate with the device

```
2024/10/27 13:49:07: BatteryLimit = 100 : 0 <--- BATTERY LIMIT IGNORED, 
2024/10/27 13:49:07: Eco flag : -65536 <--- NONSENSE REPORTED INSTEAD OF ECO MODE
2024/10/27 13:49:07: Mux flag : -65536 <---- NONSENSE REPORTED INSTEAD OF ULTIMATE MODE
```

When this driver is not working, neither AC nor G-Helper won't work. When was the last time it was working ?

Try to reinstall [Asus System Control Interface](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-asus-system-control-interface) and do [Hard reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset) to see if helps?

**Comment by Trinley668** [comment]
2024/10/28 0:27:01: App launched: ROG Zephyrus G16 GU605MV_GU605MV :0.197.0.0zh-CN.
2024/10/28 0:27:01: Start Count: 161
2024/10/28 0:27:02: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
2024/10/28 0:27:04: C:\ProgramData\ASUS\GameVisual\ASUS_DCIP3.icm DCIP3
2024/10/28 0:27:04: C:\ProgramData\ASUS\GameVisual\ASUS_DisplayP3.icm DisplayP3
2024/10/28 0:27:04: C:\ProgramData\ASUS\GameVisual\ASUS_sRGB.icm sRGB
2024/10/28 0:27:04: NVIDIA GeForce RTX 4060 Laptop GPU
2024/10/28 0:27:05: CPU: 0 - Intel(R) Core(TM) Ultra 9 185H - Intel64 Family 6 Model 170 Stepping 4
2024/10/28 0:27:06: AutoSetting for Online
2024/10/28 0:27:06: BatteryLimit = 80 : 0
2024/10/28 0:27:06: Input available: \\?\hid#vid_0b05&pid_19b6&col05#6&2caf62d7&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 63
2024/10/28 0:27:06: USB 19B6|63: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2024/10/28 0:27:06: Input: \\?\hid#vid_0b05&pid_19b6&col05#6&2caf62d7&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
2024/10/28 0:27:06: Eco flag : -65536
2024/10/28 0:27:06: Mux flag : -65536
2024/10/28 0:27:06: USB 19B6: 5D-B3-00-00-FF-FF-00-EB-00-00-FF-FF-00-00-00-00-00
2024/10/28 0:27:06: USB 19B6: 5D-B4
2024/10/28 0:27:06: USB 19B6: 5D-B5-00-00-00
2024/10/28 0:27:06: \\?\DISPLAY#SDC41A3#5&2ff708bb&1&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL
2024/10/28 0:27:06: \\?\DISPLAY#SDC41A3#5&2ff708bb&1&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY5\Monitor0
2024/10/28 0:27:06:  HDR: False 10 1 False
2024/10/28 0:27:06: Mode = 1 : 0
2024/10/28 0:27:06: VivoMode = 2 : 0
2024/10/28 0:27:06: Matrix Device: \\?\hid#vid_0b05&pid_193b&col04#6&34883165&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} 128
2024/10/28 0:27:06: Init 19B6: 5D-B9
2024/10/28 0:27:06: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2024/10/28 0:27:06: Init 19B6: 5D-05-20-31-00-1A
2024/10/28 0:27:06: SlashEnable False:5E-D8-02-00-01-80-00-00-00-00-00-00-00-00-00-00-
2024/10/28 0:27:06: SleepInit:5E-D2-02-01-08-A1-00-00-00-00-00-00-00-00-00-00-
2024/10/28 0:27:06: USB 19B6: 5D-BD-01-5F-1F-FF-FF-FF
2024/10/28 0:27:06: AuraMode: GPUMODE
2024/10/28 0:27:06: Sleep False:5E-D3-03-01-08-A1-00-FF-00-02-FF-FF-00-00-00-00-
2024/10/28 0:27:06: USB 19B6: 5D-B3-00-00-FF-FF-00-EB-00-00-FF-FF-00-00-00-00-00
2024/10/28 0:27:06: USB 19B6: 5D-B4
2024/10/28 0:27:06: USB 19B6: 5D-B5-00-00-00
2024/10/28 0:27:07: Auto 19B6|63: 5A-BA-C5-C4-00
2024/10/28 0:27:07: Monitor Power On
2024/10/28 0:27:07: BatteryLimit = 80 : 0
2024/10/28 0:27:07: Lid Open
2024/10/28 0:27:07: Lid 19B6|63: 5A-BA-C5-C4-00
2024/10/28 0:27:07: SlashLidCloseAnimation False:5E-D8-00-00-02-A5-00-00-00-00-00-00-00-00-00-00-
2024/10/28 0:27:15:  HDR: False 10 1 False
2024/10/28 0:27:17: Latest version 0.197.0.0
2024/10/28 0:27:20: Unable to load DLL 'atiadlxx.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
2024/10/28 0:27:20: Hibernate after 2147483647
2024/10/28 0:28:31: HID Device Event: Checking for new ASUS Mice


This is after I tried the scenarios according to the troubleshooting guide, one by one, and still didn't restore the display of the graphics card mode and fan speed, can you please see what other issues could be causing this? Thanks!

**Comment by seerge** [comment]
@Trinley668 hello, Asus System Control interface still responds nonsense.

You have a high app start count, so you seem to use it for a while. Did it work before ? And if so - what changed after (windows update, BIOS update, drivers?)

**Comment by Trinley668** [comment]
It was normal for a while before, but after a few days of the computer being in a sleep state it became what it is now

**Comment by seerge** [comment]
@Trinley668 did you also try resetting BIOS settings to defaults ? I can't do anything here, as something is wrong with the driver (or communication with it) itself.

Out of curiosity - can you check how would Armoury work in this case ?

**Comment by Trinley668** [comment]
Windows 23H2、BIOS 323 、Graphics card drivers latest

**Comment by Trinley668** [comment]
Okay, I'll give it a try, thank you very much!

**Comment by Trinley668** [comment]
![image](https://github.com/user-attachments/assets/3c113d1c-aa67-4ae2-87c7-27da3ce7cb08)

And ASUSSystemControlInterfaceV3, even if it's installed, doesn't show up here

**Comment by Trinley668** [comment]
![image](https://github.com/user-attachments/assets/ce00ddbc-b2e1-45d5-94b2-c34c77845570)
This won't install either.

**Comment by Trinley668** [comment]
> @Trinley668 did you also try resetting BIOS settings to defaults ? I can't do anything here, as something is wrong with the driver (or communication with it) itself.
> 
> Out of curiosity - can you check how would Armoury work in this case ?

![image](https://github.com/user-attachments/assets/ef42ecda-3451-4d36-a4ff-41cb26c2e389)
Also no graphics card mode

**Comment by seerge** [comment]
@Trinley668 can you open BIOS menu (F2 on boot), to to Advanced Settings and check if both Armoury Control Interface and Auto Install app-service something is enabled there ?

**Comment by seerge** [comment]
@Trinley668 

> And ASUSSystemControlInterfaceV3, even if it's installed, doesn't show up here

As a last resort, may be it's not BIOS hiccups but windows hiccups. Do you have any restore points created in windows? Try to revert back to time when everything worked ...

**Comment by seerge** [comment]
@Trinley668 any updates here ?

**Comment by seerge** [comment]
@Trinley668 ok, amazing! Apparently it was some hiccup in windows. Closing as resolved then
