### ISSUE TITLE
ROG Flow Z13 back RGB window not compatible with some keyboard(?) light modes

### ISSUE THREAD

**Issue by velikidizel** [seerge/g-helper#3316]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The ROG Flow Z13 has a small window on the back, with RGB lights. G-Helper sees it as a "lightbar"...
I would like to have it showing the same things as a keyboard if that is possible, for modes "Heatmap" and "Ambient" as for those 2 modes it shows the last mode it was before putting on 1 of these 2 modes. Thanks, loving the app...

### How to reproduce the bug?

So if I was on strobe before clicking Ambient, keyboard switches to Ambient, while the back window continues strobing, or any other mode, static, rainbow etc...

### Logs

[log.txt](https://github.com/user-attachments/files/17535055/log.txt)

### Device and Model

Asus ROG Flow Z13 GZ301ZC-LD110W

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.197.0

### OS

Windows 11

**Comment by seerge** [comment]
@velikidizel hello, 

I'm afraid that's not possible (or i'm simply not aware how to individually set color for back window). As both Ambient and Heatmap modes are software-emulated – i.e. G-Helper sets color manually every time it needs to change.

Are you able to change individual color **only** for this back window with apps like OpenRGB ?

**Comment by velikidizel** [comment]
either i have mega autism not knowing how to setup openrgb or something is broken. openrgb only recognizes a monitor i have never seen in my life, let alone was connected at some point, let alone connected right now. it also said when i opened that 1 or more rgb devices wont work because of some issue with windows not loading some drivers idk i forgot what it said and it stopped popping up. either way i cannot control anything with openrgb
![Screenshot 2024-10-27 200739](https://github.com/user-attachments/assets/989dc17f-5e10-4c58-ad57-12bbcc46fd7a)

**Comment by seerge** [comment]
@velikidizel then most likely it's not possible to individually set color for the back window in general. So nothing can be done here

**Comment by velikidizel** [comment]
okay, no problem... as this ambient mode is really cool and not standard in the armoury crate, thank you for atleast implementing for keyboard. i will close this issue now...

**Comment by velikidizel** [comment]
> @velikidizel hello,
> 
> I'm afraid that's not possible (or i'm simply not aware how to individually set color for back window). As both Ambient and Heatmap modes are software-emulated – i.e. G-Helper sets color manually every time it needs to change.
> 
> Are you able to change individual color **only** for this back window with apps like OpenRGB ?

Update on this: I just noticed randomly, while in tablet mode with an external usb desktop keyboard, after resuming from S3 sleep that the back window does emulate the ambient mode, HOWEVER, just on 1 LED, the first one closest to the middle of the tablet. So, it can and does pick up, but something is bugged out.... ![WhatsApp Image 2024-11-30 at 21 54 24](https://github.com/user-attachments/assets/c3544144-4562-4a0f-a259-3c5264916dee)
