### ISSUE TITLE
Closed on its own today

### ISSUE THREAD

**Issue by RamseyKal** [seerge/g-helper#3317]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [x] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I restarted the computer today after updating Windows 10 as it had a preview update.
I used my computer afterward, put it to sleep, then came back home, used it a bit, then left it idle for hours. Came back now and found that I couldn't use 3 of the M keys. I looked and G-Helper wasn't there in taskbar icons. It closed on its own. I didn't close it.

I am noticing some issues with it. Sometimes it freezes on its own and then opens itself again. This would be a second issue.
It's not too reliable so far.
I'm noticing some random slowdowns, not sure from what. Could be anything but the first two issues are from G-Helper.

Not sure how else I can help you troubleshoot this. Hope the logs can help.

### How to reproduce the bug?

I cannot reproduce this. It's random.

### Logs

[log.txt](https://github.com/user-attachments/files/17536238/log.txt)

### Device and Model

Asus ROG Strix G18 G814JZ

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.197.0

### OS

Windows 10 64-Bit 22H2

**Comment by seerge** [comment]
@RamseyKal hello,

It means either something else has closed app or it crashed.

- Check if you have any antiviruses that might close app ? If so - add exception
- Check windows Event Viewer application log for events mentioning GHelper.exe. If you see one - please upload full contents here.

P.S. You seem to keep app in `D:\OneDrive\Apps\` folder that is synced and managed by microsoft One Drive. May be it has closed it ? Try to put exe somewhere where nothing will be trying to upload it to the cloud or delete :)

**Comment by RamseyKal** [comment]
Thank you for your reply. I never thought about OneDrive causing that so that could be a possibility. I moved it to the Desktop, which isn't synced.

I also verified Event Viewer and I do see the following 3 errors:

### **Error 1:**

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-10-27T21:04:54.4942659Z" /> 
  <EventRecordID>16939</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel>
  <Security /> 
  </System>
  </Event>

Application: GHelper.exe
CoreCLR Version: 8.0.1024.46610
.NET Version: 8.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Timers.Timer.UpdateTimer()
   at System.Timers.Timer.set_Enabled(Boolean value)
   at GHelper.Battery.BatteryControl.UnSetBatteryLimitFull() in D:\a\g-helper\g-helper\app\Battery\BatteryControl.cs:line 23
   at HardwareControl.ReadSensors() in D:\a\g-helper\g-helper\app\HardwareControl.cs:line 244
   at GHelper.SettingsForm.RefreshSensors(Boolean force) in D:\a\g-helper\g-helper\app\Settings.cs:line 1425
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### **Error 2:**
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-10-27T21:04:54.6705136Z" /> 
  <EventRecordID>16940</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Security /> 
  </System>

Faulting application name: GHelper.exe, version: 0.197.0.0, time stamp: 0x66e80000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.5072, time stamp: 0xef4f0afe
Exception code: 0xe0434352
Fault offset: 0x000000000002ba99
Faulting process ID: 0x2b00
Faulting application start time: 0x01db287d35dc690e
Faulting application path: D:\OneDrive\Apps\GHelper.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 1e012182-6531-468c-89e3-d45307bd7a2a
Faulting package full name: 
Faulting package-relative application ID: 
  </Event>
```

### **Error 3:**
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-10-27T21:04:56.2994880Z" /> 
  <EventRecordID>16941</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Security /> 
  </System>


Fault bucket 1427034547013046225, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: GHelper.exe
P2: 0.197.0.0
P3: 66e80000
P4: KERNELBASE.dll
P5: 10.0.19041.5072
P6: ef4f0afe
P7: e0434352
P8: 000000000002ba99
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7CB6.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7EDA.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7F0A.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7F18.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7F28.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_GHelper.exe_0a1d92482ec6158aaa4d3e3c70bea15e617a2_a9bd6448_fd5b5962-b3b6-449f-b20a-a573910bbf9c

Analysis symbol: 
Rechecking for solution: 0
Report Id: 1e012182-6531-468c-89e3-d45307bd7a2a
Report Status: 268435456
Hashed bucket: 6890764cba5d18f533cdd85c18ec4fd1
Cab Guid: 0
```

**Comment by seerge** [comment]
@RamseyKal ok, thanks for checking.

Try this build, i should avoid exception (and app crash) you faced
[GHelper.zip](https://github.com/user-attachments/files/17544687/GHelper.zip)

**Comment by RamseyKal** [comment]
Thanks, I hope it works out well.
Here's what happened last night when I updated the app. I exited it, and overwrote the one on my desktop, it flickered, then it launched the app, and closed my Windows explorer and removed some icons I have in my taskbar hidden icons (bottom right). It closed SnagIt and NVIDIA dynamic display mode, which is what happens each time something force closes Explorer.
I don't understand why this happened. It shouldn't bug out my system.

**Comment by seerge** [comment]
@RamseyKal it doesn't close explorer :) looks more like some windows hiccup ? or for example you had device unplugged and in Optimized mode so it has turned off GPU (as it should), that would obviously also close nvidia apps.

**Comment by seerge** [comment]
Ok, I'm closing it as resolved, as changes in this build should address exception . Thanks for spotting

**Comment by seerge** [comment]
@RamseyKal 

P.S. I checked log again, you don't even use Eco / Optimized mode it seems (at least not in the timeframe covered by the log). So it was no GPU toggling.

Also, if you have moved app to other folder - make sure to uncheck and check `Run on Startup` again (so it will re-create startup task pointing to new location). It will do that automatically if will see if exe in old location is removed, but just to make sure :)

**Comment by RamseyKal** [comment]
Thanks for your diligence in checking this :). I unchecked Run on Startup and rechecked it now. I'll keep that in mind if I move it again. Great info!

I actually always use Standard and never move it to another. I very rarely go for Ultimate but I stick to Standard because this laptop and NVIDIA 4080 are buggy on laptops with micro-stutters and such and they've never fixed it since I got it in 2023 July.

Here are latest logs since the logs I sent don't cover the crash I got yesterday when updating G-Helper.
[log.txt](https://github.com/user-attachments/files/17557074/log.txt)

**Comment by RamseyKal** [comment]
This is the Explorer crash that happened when overwriting G-Helper.

Faulting application name: Explorer.EXE, version: 10.0.19041.5073, time stamp: 0xc08ff7d3
Faulting module name: SHELL32.dll, version: 10.0.19041.5072, time stamp: 0xd947714a
Exception code: 0xc0000005
Fault offset: 0x000000000002d0a6
Faulting process ID: 0x175c
Faulting application start time: 0x01db287d347e5074
Faulting application path: C:\WINDOWS\Explorer.EXE
Faulting module path: C:\WINDOWS\System32\SHELL32.dll
Report ID: 2c73416b-aa02-41a9-87eb-f4223c65ab47

**Comment by seerge** [comment]
@RamseyKal well, log looks absolutely fine - you just seem to keep switching between Silent and Balanced default modes with some minimal GPU overclocking in Balanced `SET GPU CLOCKS: 20, 60` :)

When exactly did your explorer crash happened ? 
Explorer crash details doesn't say anything, except just the fact it crashed :) is this the only even in Event Viewer ? sometimes it could be more than one log coming together, and second may have more info

**Comment by seerge** [comment]
@RamseyKal ah, in that case it's the only way of course. But if explorer crashed by itself, it's something internal. May be windows defender somehow was trying to flag the file and crashed explorer in turn ?

**Comment by RamseyKal** [comment]
Yes, actually, when trying to run it, I did get the Windows popup about this app not being safe. It didn't happen with your normal G-Helper. Any idea why it triggered it with your test build?

**Comment by seerge** [comment]
@RamseyKal it's normal, cause for the linked build you are literally second person running (after me), so windows just automatically flags it. While builds released for everyone are downloaded by thousands of people - like last final release was downloaded 177 000 times. It increases it's reputation for windows algorithms.
