### ISSUE TITLE
keybind_profile_NR setting in config.json is missing

### ISSUE THREAD

**Issue by DominikStyp** [seerge/g-helper#3323]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

No, only missing useful setting.

### Describe the solution you'd like

You did introduce ` "keybind_profile": 109,` setting which is really cool, but there's missing `"keybind_profile_X"`, so for example if I add a custom setting like:
```
 "mode_base_4": 0,
  "mode_name_4": "QuietCool",
  "fan_profile_mid_4": "1E-32-3C-41-46-50-55-5A-00-00-00-07-15-32-45-58",
  "fan_profile_cpu_4": "1E-32-37-3C-46-4B-50-5A-00-01-02-0B-1C-3B-46-5B",
  "fan_profile_gpu_4": "1E-28-2D-32-3C-4B-50-5A-00-00-03-05-09-29-3B-50",
  "limit_total_4": 75,
  "limit_slow_4": 125,
  "limit_cpu_4": 50,
  "limit_fast_4": 125,
  "auto_apply_power_4": 1,
  "auto_apply_4": 1,
  "auto_boost_4": 3,
```
I would also like to add `"keybind_profile_4": 109,` which should switch to mode nr 4 when I click `CTRL + SHIFT + ALT + KEY`.
It should be fairly simple, no?

### Device and Model

ROG STRIX SCAR 18 (2023) G834JY

**Comment by seerge** [comment]
@DominikStyp hello, you [already have those ](https://github.com/seerge/g-helper?tab=readme-ov-file#%EF%B8%8F-keybindings)

Ctrl + Shift + Alt + F16 - Silent
Ctrl + Shift + Alt + F17 - Balanced
Ctrl + Shift + Alt + F18 - Turbo
Ctrl + Shift + Alt + F19 - Custom 1 (if exists)
Ctrl + Shift + Alt + F20 - Custom 2 (if exists)

Just use Sharpkeys or Autohotkey to bind your own hotkey to emit ``Ctrl + Shift + Alt + F20`` and it will work

**Comment by DominikStyp** [comment]
@seerge well this is not really convenient to install additional programs to just remap some combinations if this could just be a part of the UI or config, but if you really don't want to spend the time on that, OK I get it.

**Comment by seerge** [comment]
@DominikStyp if every small thing that people ask will be part of the UI - UI will look like a Boeing cockpit :) It's already very difficult to keep things simple and relatively organized. 

You already have quite a lot of flexibility in terms of profile switching (FN+F5 and FN+SHIFT+F5 to cycle through them forwards and backwards).

This special hotkeys are mainly designed for exotic use-cases where you need to set specific profile instantly. For example for game launchers like Playnite or so.

**Comment by seerge** [comment]
@DominikStyp I have thought about it a bit, and did some tweaks so it should be possible to set key bindings for the first 5 profiles (from 0 to 4) - ``keybind_profile_0`` .. ``keybind_profile_4`` in the app now.

Don't forget that 0 = Balanced, 1 = Turbo and 2 = Silent (this is native Asus enumeration)

Try this build

[GHelper.zip](https://github.com/user-attachments/files/17561749/GHelper.zip)

**Comment by DominikStyp** [comment]
@seerge thanks I already handled my case by AutoHotkey custom send scripts, I need to programatically change the G-Helper profiles, because I'm building custom solution to change the profile depending on the CPU usage, so when CPU load is small it will change the profile to Silent, if CPU has high load it will change it to Turbo or custom with increased fan speeds.
I'll check your build tomorrow.
