### ISSUE TITLE
question about dynamic boost option

### ISSUE THREAD

**Issue by kuonji-arisu** [seerge/g-helper#333]
if I turn off dynamc boost in the hide page of bios (FX507ZM: crb advanced->Thermal config->Intel dynamic tuning platform),
does the dynamic boost setting under advanced settings still work?

**Comment by kuonji-arisu** [comment]
I want to get more stable CPU power, so I unlocked the BIOS and turned off dynamic boost. I want to know if the settings in the new version of ghelper will affect it. Just in case, I set it to the lowest (5w).

**Comment by kuonji-arisu** [comment]
Oh… looks like I made a mistake about the difference between db and dptf.

**Comment by seerge** [comment]
@kuonji-arisu i have no clue what are you talking about :) What is crb-advanced / db / dptf . How is it related to app functionality ?

**Comment by kuonji-arisu** [comment]
@seerge Some ASUS notebooks can unlock some BIOS settings hidden by ASUS through grub, such as CPU voltage adjustment, memory overclocking, etc. The Intel dynamic tuning platform I mentioned above is a technology enabled by Intel that can dynamically allocate GPU/CPU power consumption. It is similar to NVIDIA’s dynamic boost function, so I confused them together.
I used to think that the dynamic boost and dptf in the advanced settings were the same option. I thought they would conflict with each other. Now I know they are not the same thing.

**Comment by seerge** [comment]
@kuonji-arisu ah,i see. 
Boost setting under advanced is just a simple shortcut to Control Panel -> Power plans -> CPU Boost dropdown. It changes that (which tells windows to use or not a cpu boost)
