### ISSUE TITLE
G-Heper overrindin closing the lid settings

### ISSUE THREAD

**Issue by eanegrin** [seerge/g-helper#3331]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

First of all, I want to say how great this app is—really appreciate the effort put into it!

Regarding the issue: I typically change the "closing the lid" settings in Windows so that when I close the lid, whether on battery or plugged in, nothing happens (i.e., the computer doesn’t enter sleep mode or anything like that). The issue is that G-Helper seems to override these settings, at least for the plugged-in power plan, because each time I turn on my computer, I find that this setting has reverted to "Sleep."

Thanks

### How to reproduce the bug?

1. Go to Power options >> Choose what closing the lid does
2. Set "Do nothing" for "When i close the lid" for both battery and plugged in plans.
3. Save changes
4. Turn off your computer and turn it back on
5. Repeat step 1 and you'll see that it was turned to "Sleep" for the plugged in plan.

### Logs

[log.txt](https://github.com/user-attachments/files/17587394/log.txt)

### Device and Model

G513RC

### Additional information.

![image](https://github.com/user-attachments/assets/6df372ba-669a-4215-ac0f-b375bfd88dd8)

### Armoury Crate

Uninstalled

### Asus Services

8

### Version

0.197.0

### OS

Windows 11 22H2

**Comment by seerge** [comment]
@eanegrin hello, 

You have `Clamshell Mode` selected under `Extra`. It sets `Lid Close` action to `Do nothing` when laptop is plugged in and is connected to external display, and sets action to previous setting when laptop is unplugged or disconnected from display.

Just disable Clamshell Mode if you don't need and this setting won't be touched.

Thanks

**Comment by eanegrin** [comment]
That worked, thanks again
