### ISSUE TITLE
G-helper for Asus TUF A15

### ISSUE THREAD

**Issue by VIG191088** [seerge/g-helper#3333]
### Mouse / peripheral model and version

ASUS TUF A15

### Armoury Crate Screenshots

![Screenshot 2024-11-01 114817](https://github.com/user-attachments/assets/f6e196b9-bcbc-4c7d-8ef1-0c23a96ecb5d)

### USB Details

![Screenshot 2024-11-01 120641](https://github.com/user-attachments/assets/a7b7ed0e-ec29-4354-878f-bda96b70c640)

### Additional information.

![Screenshot 2024-11-01 121124](https://github.com/user-attachments/assets/0c9c02ec-e2d3-4196-867f-9a971f43c59f)

**Comment by seerge** [comment]
@VIG191088 hello, 

TUF A15 is not a peripheral – it's a laptop :) And it's already supported. 

Thanks.

**Comment by VIG191088** [comment]
Dear @seerge! thank you so much for your prompt response. I was able to successfully install g-helper and remove AC :) appreciate all the hard work and effort that has gone into making this tool. Wish you all the very best.

Vignesh
