### ISSUE TITLE
For some odd reason my battery was empty

### ISSUE THREAD

**Issue by Cistmist** [seerge/g-helper#3338]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I closed my laptop lid so that it goes to sleep while i fetch food, and came back to a 0% battery when i opened my lid again which was odd as i was away for 50mins which shouldn't happen. As my battery is still good.
![Screenshot 2024-11-03 223129](https://github.com/user-attachments/assets/51916cd0-2813-43d5-a3a8-db37d54bb39a)
![Screenshot 2024-11-03 223213](https://github.com/user-attachments/assets/8ada7cda-461c-479e-b9cf-5c9c0be95c83)
added some screenshot from the battery report too.

### How to reproduce the bug?

Close lid. Leave for a while and come back?

### Logs

[log.txt](https://github.com/user-attachments/files/17611979/log.txt)

### Device and Model

ASUS TUF GAMING A15 FA506IC

### Armoury Crate

Never installed

### Asus Services

6

### Version

0.197.0

### OS

windows 11 home

**Comment by seerge** [comment]
@Cistmist hello, 

But how is this connected to G-Helper ? :) Apparently it's some hardware / firmware hiccup with the battery. So it was either reporting incorrect charge before sleep (most likely) or after waking up.

All this is handled by hardware itself and hardware reports charge levels to windows (that generates report)

**Comment by Cistmist** [comment]
I mean it's the first time this happened to me and it only happened after i installed g-helper which is why i asked here. If it was reporting incorrect charge then both the windows and g-helper were fucked no? As i rarely used the pc on battery and had it limited to 75% since it was installed. So having the battery suddenly become 0% in 1 minute is weird no?

**Comment by seerge** [comment]
@Cistmist  

Try to charge device back to full capacity (i.e. 100%) again once or twice. Then battery will re-calibrate it's **actual** capacity. It could be that since you kept battery on 75% (or 80%) all the time calibration was just very off. As system calibrates battery only when on full discharge and charge cycle.

You have 2021 device, so in 3 years battery could degrade by a lot just by itself.

**Comment by Cistmist** [comment]
alright thanks will try that out and see how it works out

**Comment by Cistmist** [comment]
@seerge one more question. I removed g-helper along with the %appdata% folder, and also reset it's fan settings from what i read. and for some reason i can no longer change the backlight of my keyboard even though it was an option before i installed g-helper by using the Fn+ left or right keys.

Tried also going into Settings>Personalization> Dynamic Lighting > Turned off "Use dynamic lighting on my device" and restarted my pc and it still wasn't working. Any idea how to fix this?

**Comment by seerge** [comment]
@Cistmist I didn't completely get your last question.

If you don't run G-Helper, it (obviously) can't handle your hotkeys. You need to start asus services instead from `Extra` settings or from windows services app directly.

If you do run G-Helper - then it will handle hotkeys, including ones for backlight levels.

Did you recharge laptop, what capacity does battery report show now ?

**Comment by seerge** [comment]
@Cistmist any updates here ?

**Comment by seerge** [comment]
Closed as abandoned
