### ISSUE TITLE
ROG Ally- use CMD center button as utility key

### ISSUE THREAD

**Issue by Hydraxonn** [seerge/g-helper#3339]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I want to use the M1 and M2 keys as discrete, mapped inputs, which G helper already supports. When I do this, I lose access to the convenient quick controls from desktop mode, like M1 + D pad left and right for brightness.

### Describe the solution you'd like

I would like an option to be able to use the CMD center key in place of the M keys for the Ally's quick controls. In a perfect world, id also like to be able to remap this modified control set entirely, and perhaps also remap the keybindings in the Mouse mode. The latter, however, may be best reserved for its own feature request. 

### Device and Model

ROG Ally Z1 Extreme 16G

### Additional information.

Using the four Ally-custom buttons as discrete inputs is already supported, which I massively appreciate. There seems to be no way, however, to change the quick controls to different keys, or to add new quick controls.

**Comment by seerge** [comment]
@Hydraxonn hello,

Unfortunately that's simply not possible. All `M1/M2 + <any button` hotkeys are handled purely by firmware, and in Armoury Crate or G-Helper you can only adjust this bindings, but not introduce a new ones.

Both CMD and ROG buttons are not part of built-in game controller, they only emit a special code when pressed, so you can process it and run certain software action (like showing G-Helper or Toggling modes, etc), but you can't turn them into modifiers as `M1` or `M2` are .

Thanks.
