### ISSUE TITLE
Clocks offset

### ISSUE THREAD

**Issue by LeonardBeu** [seerge/g-helper#334]
After update, i tried out the clocks offset for memory and core. While memory offset seems to work, clock does not change anything in any performance modes. 

No changes VS +100 to both
![image_2023-05-08_103805894](https://user-images.githubusercontent.com/125369328/236764461-380127c4-da22-45a6-9154-96118509fe65.png)

![image_2023-05-08_103723181](https://user-images.githubusercontent.com/125369328/236764300-f105bea3-ae70-4df9-b17e-9a376e5ecf78.png)

**Comment by seerge** [comment]
@LeonardBeu because it's dynamic offsets in driver settings :) you need to load GPU in both cases to see if it makes difference or not. 

How did  you change clocks before that / and how did you verify it?

**Comment by seerge** [comment]
@LeonardBeu 

1. You can double-check if clocks are applied by running msi afterburner, if it will show same offsets - it's "applied' (both g-helper / afterburner get them from driver)

2. Yes, modes are stored in bios and are same as in AC

**Comment by LeonardBeu** [comment]
msi afterburner confirms the clocks. Thank you for your help
