### ISSUE TITLE
ASUS ProArt Studiobook usb soundcard issue, not supported?

### ISSUE THREAD

**Issue by ErikMichaelSvensson** [seerge/g-helper#3341]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I recently bought a:

ASUS ProArt Studiobook 16 OLED - i9 | 32GB | 2TB | RTX 4060
H7604JV-MY071X

It runs fine with my focusrite scarlett 2 2nd gen soundcard when only running myasus.

I downloaded g helper which is supposed to increase performance slightly but whenever its open the focusrite starts making a buzzing noise after a few minutes, is this a known issue?

Replugging usb cable fixes it for a few minutes then it starts over again. Its buzzing on both speakers and headphones and i tryed 2 different usb cables plugged in 2 different usb slots.

Appreciate if someone have an idea what this could be due, closest i found googling mentioned something about grounding but that doesnt really make sense either since its only causing this on g helper.

### How to reproduce the bug?

1 open  g helper.
2 wait couple minutes for buzzing usb soundcard.
3 unplug replug works about a minute then buzzes again.
4 stops when g helper is closed down.

### Logs

N/A

### Device and Model

ASUS ProArt Studiobook 16 OLED I9 13th gen 

### Armoury Crate

Never installed

### Version

0.197

### OS

Windows 11 pro 21h2

**Comment by seerge** [comment]
@ErikMichaelSvensson hello,

G-Helpe is not interacting with your sound card. 

- Does it buzz when G-Helper window open only, or when it’s in system tray? 
- Does it stop immediately when you quit app
- Can you upload app log as it was explicitly asked in the issue template?

Thanks

**Comment by ErikMichaelSvensson** [comment]
> @ErikMichaelSvensson hello,
> 
> G-Helpe is not interacting with your sound card.
> 
> * Does it buzz when G-Helper window open only, or when it’s in system tray?
> * Does it stop immediately when you quit app
> * Can you upload app log as it was explicitly asked in the issue template?
> 
> Thanks

Sorry for waisting your time i bought a new usb cable for the soundcard and it resloved itself.

**Comment by seerge** [comment]
@ErikMichaelSvensson no problem, I suppose it was some kind of hardware hardware interference between laptop and a USB-cable :) Probably appearing only when you set specific (either lower power or higher power mode on the laptop)
