### ISSUE TITLE
add a rotate sensor disable feature for laptops that have one.

### ISSUE THREAD

**Issue by thatonehhdev** [seerge/g-helper#3342]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

when there is a rotate sensor on a laptop that has tablet mode(the hinge is 360 degrees) it thinks its in tablet mode when turned on its side even when the hinge is not folded backwards.

### Describe the solution you'd like

a button that disables the sensor device responsible for rotation detection. on my laptop, its called AMD UDMF Sensor in device manager.

### Describe alternatives you've considered

i am not sure if there is any other way to disable the tablet mode function. windows autorotate off is kinda crap and doesnt solve the problem.

### Device and Model

asus proart px13

**Comment by seerge** [comment]
@thatonehhdev hello, do you have that setting in native Asus apps? Cause if no - then it’s most likely it’s not possible, cause this toggle needs to be available on firmware level :)

**Comment by thatonehhdev** [comment]
i was thinking about something simular to disabling it in device manager on every boot, because it re enables it self. the option is not avalable in asus apps.

**Comment by seerge** [comment]
@thatonehhdev I think what you explain is just called Tablet Mode in Windows. In Win10 you could just toggle with  a button, with Win11 they have removed that setting - but it's still accessible indirectly

Check this https://www.kapilarya.com/turn-off-tablet-mode-in-windows-11
