### ISSUE TITLE
support aura sync

### ISSUE THREAD

**Issue by UnknownUser12333** [seerge/g-helper#3344]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

support aura sync

### Describe the solution you'd like

support aura sync

### Device and Model

rog strix g15 g513qm

**Comment by seerge** [comment]
@UnknownUser12333 you already can set all backlight modes supported by your hardware + few software emulated ones (like Ambient or Heatmap). Thanks.
