### ISSUE TITLE
Undervolting section

### ISSUE THREAD

**Issue by xSimone** [seerge/g-helper#3345]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

The BIOS only allows -80mv maximum, but some CPU's such as the 14900HX has shown it can go as low as -150mv and achieve fantastic results.

I think it would be awesome if G-Helper had its own section for undervolting the CPU. Perhaps a special button in the EXTRA menu, and when opened, a warning will show up saying possible risks of system instability, then you can type into the field how much of an undervolt you'd like, with a max of I'd say -150 and +50 just to be safe from mistakes.

### Describe the solution you'd like

Blorp

### Device and Model

Asus Scar 18 G834JZR

**Comment by seerge** [comment]
@xSimone hello,

I don't know how to access Intel CPU undervolting to be honest (as there is no open information about this, unlike for AMD).

Why don't you just use [Intel Extreme Tuning Utility](https://www.intel.com/content/www/us/en/download/17881/intel-extreme-tuning-utility-intel-xtu.html) ? It can do it for HX CPUs and it's official from Intel, so you know that it works as it should :)

**Comment by xSimone** [comment]
I was hoping to not have to have extra programs running in the background. XTU is crap from memory.

**Comment by seerge** [comment]
@xSimone XTU is indeed takes a lot of memory, but from what I remember you don't have to keep it running to undervolt. You just launch it once - set values, and it stays. I just don't have Intel HX device anymore to check that ... :)

**Comment by xSimone** [comment]
I was certain XTU needs to keep running in the background with autolaunch on Windows Start. 

If you are correct, then that is great, I do not want to have it running all the time.

**Comment by von-M** [comment]
An alternative is to use Throttlestop, it's very lightweight. https://www.techpowerup.com/download/techpowerup-throttlestop/

**Comment by xSimone** [comment]
> An alternative is to use Throttlestop, it's very lightweight. https://www.techpowerup.com/download/techpowerup-throttlestop/

Yeah I'm aware of that one too.. my hopes was to not have another program / tool running on my laptop which is why I wanted to try get it implemented into G-Helper.

Do you use ThrottleStop?

Does it need to always be running to have the undervolt?

**Comment by von-M** [comment]
Yes, I use it. It's quite powerful in its functionality, for example an important feature is in addition to underclocking, you can set a voltage boost at 800mhz to increase stability ate lower underlcock values. 

You don't need it running in the background, but if it's not running in the background then any other program can make changes to the values.

**Comment by xSimone** [comment]
> Yes, I use it. It's quite powerful in its functionality, for example an important feature is in addition to underclocking, you can set a voltage boost at 800mhz to increase stability ate lower underlcock values.
> 
> You don't need it running in the background, but if it's not running in the background then any other program can make changes to the values.

Hmm that makes sense.. like a BIOS update or something.

**Comment by thatonehhdev** [comment]
40mv is a little small, my proart px13 runs totally fine with the undervolting set to max.

**Comment by seerge** [comment]
@xSimone so to summarize.

Since there are existing tools for Intel undervolting (like Intel XTU or Throttlestop) and there are no open-source information on how it's done - I can't really add it. 

Sorry. Thanks.
