### ISSUE TITLE
ROG macro key opens multiple windows of the same app.

### ISSUE THREAD

**Issue by StrixLake** [seerge/g-helper#3348]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I have mapped the rog key to open windows terminal from ghelper. However, sometimes as many as 10 windows open upon pressing the key only once. If I press it again, only one terminal window opens. I was able to reproduce this bug every time I press the macro key after the device wakes up from sleep.

### How to reproduce the bug?

1. Set Key bindings from GHelper of ROG key to "C:\Users\{username}\AppData\Local\Microsoft\WindowsApps\wt.exe"
2. Put the device to sleep and wake it up again.
3. Press the ROG key.

### Logs

[log.txt](https://github.com/user-attachments/files/17655411/log.txt)

### Device and Model

Asus Zephyrus G14 GA403UI

### Armoury Crate

Uninstalled

### Asus Services

1

### Version

0.197.0

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@StrixLake hello,

In what circumstances does it happen? Cause what I see in the log, is that sometimes you seem to press a button 2 times in a row - and obviously corresponding command is being processed twice then, like

```
7/11/2024 1:55:40 PM: Key: 56 <---- app is notified about ROG key
7/11/2024 1:55:40 PM: Launching "C:\Windows\system32\cmd.exe" /C "C:\Users\yasha\AppData\Local\Microsoft\WindowsApps\wt.exe" <---- terminal opened
7/11/2024 1:55:40 PM: Key: 56 
7/11/2024 1:55:40 PM: Launching "C:\Windows\system32\cmd.exe" /C "C:\Users\yasha\AppData\Local\Microsoft\WindowsApps\wt.exe"
```

But I don't see a single time when it would be launched 10 times.

**Comment by StrixLake** [comment]
Hi,
It happens at the first button press on every time the device wakes up from sleep.
[recording](https://quickshare.samsungcloud.com/qG3PuUky5S72)
[log.txt](https://github.com/user-attachments/files/17659040/log.txt)
I have attached a screen recording as well as the log.txt for it. I recorded it right after the device woke up from sleep. I only pressed the button once, the log.txt also only registers 1 click but 3 windows opened. Usually it's 3, but sometimes 10 or 6.

**Comment by seerge** [comment]
@StrixLake ok, thanks. Can you try this build ?
[GHelper.zip](https://github.com/user-attachments/files/17659629/GHelper.zip)

**Comment by StrixLake** [comment]
This fixed the issue. Thank you so much.
Though for some reason it tripped windows defender on first launch. Seems ok now.

**Comment by seerge** [comment]
@StrixLake Great. Defender can be triggered on a fresh builds, cause you are literally the second person running it after me, while published releases are downloaded by like 180 0000 people atm ...
