### ISSUE TITLE
Whenever I open a game, the cpu boost becomes aggressive

### ISSUE THREAD

**Issue by xKatzfiell** [seerge/g-helper#3349]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

As I open any game, the closed cpu goes into boost aggressive mode, and it does not turn off unless I switch between modes.

### How to reproduce the bug?

1. Open a game
2. Cpu boost going to be aggressive
3. Switch between modes
4. Cpu boost going to be disable
5. When I open a game again this cycle become again.

### Logs

[log.txt](https://github.com/user-attachments/files/17679626/log.txt)

### Device and Model

Asus Zephyrus G16 GU603ZU

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.197.0

### OS

W11 Pro 24H2

**Comment by seerge** [comment]
@xKatzfiell hello,

Do you by any chance have leftovers from Armoury Crate ? Did you use official [dedicated AC uninstaller app ?](https://github.com/seerge/g-helper/wiki/Requirements#recommendations-optional)

**Comment by xKatzfiell** [comment]
I didn't install Armory Crate after the format, I've this problem like 1 week. I thought it would be fixed when I installed Armoury crate and then removed with AC uninstaller app it, but the problem persists.

**Comment by seerge** [comment]
@xKatzfiell 

I just see that something external is constantly overriding default "balanced" [power plan in control panel](https://learn.microsoft.com/en-us/windows/win32/power/power-policy-settings), so when you launch G-Helper or change a mode it has to set it back. And it wouldn't have to do it if that won't be changed.

```
8.11.2024 15:35:24: Power Plan 381b4222-f694-41f0-9685-ff5bb260df2e:OK 
```

Can you look into windows Task Manager for all processes containing word "asus" just to double check that ?

Also don't forger,that CPU boost setting is saved for each mode individually. Do you have it set to OFF in all modes that you use for gaming? Try to manually set it again to disbled in a dropdown there. Also please upload `config.json` from `%appdata%\GHelper` just to be sure ?

**Comment by xKatzfiell** [comment]
[config.json](https://github.com/user-attachments/files/17680221/config.json)
![image](https://github.com/user-attachments/assets/8b88c4e2-edaf-4e00-85fc-c427d9ac40c5)
Yes, I disabled it in all each mode.

**Comment by seerge** [comment]
@xKatzfiell ok, great. 

1. So when you open `Fans + Power` before launching game, you see CPU boost being disabled in a dropdown.
2. Then you launch a game, open same `Fans + Power` and without changing any modes see that boost became aggressive ?

Can you open windows Control Panel -> Power plans and see what power plan is being set there after you launch a game ?

**Comment by xKatzfiell** [comment]
Exactly, happens as you say.
I sent screenshots before and after launching the game.

![Ekran görüntüsü 2024-11-08 175820](https://github.com/user-attachments/assets/8b699494-0ab1-40f1-bbd4-484ee330f1ca)
![Ekran görüntüsü 2024-11-08 175905](https://github.com/user-attachments/assets/3bed723c-4f08-4f99-8240-5d7ade4bbd23)
![Ekran görüntüsü 2024-11-08 175934](https://github.com/user-attachments/assets/d31583f2-3222-461a-b700-9a6119bd66b7)

Nothing changing in the power plan but in the g-helper cpu mode becoming to aggressive.

**Comment by seerge** [comment]
@xKatzfiell can you refresh (or ideally re-open) Control Panel -> Power Options page ? Then one showing currently active power plan.

Cause you have already opened details of the "balanced" power plan, and I suspect that something changing power plan itself.

**Comment by xKatzfiell** [comment]
When I open the any game, razer cortex automatically changing the cpu mode to aggressive, it sucks.

**Comment by seerge** [comment]
@xKatzfiell ok, as I suspected. I have added logging of a previous power plan GUID to the app not, for easier future debugging of such cases.

But I assume it's resolved now ? :)
