### ISSUE TITLE
Disable HDR mode on Battery for better efficiency

### ISSUE THREAD

**Issue by madethisaccountcauseigotaquestion** [seerge/g-helper#3351]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Taking the laptop off of battery to take around places, the battery uses a lot more wattage when on HDR as opposed to SDR, and it takes a bit of time to go into Windows Settings and disable it manually.

### Describe the solution you'd like

A checkbox under Extra settings for laptops with HDR, that would disable HDR automatically when on-battery.

### Device and Model

Strix G18 G834JZR

**Comment by seerge** [comment]
@madethisaccountcauseigotaquestion 

Hello, I'm not sure if it's even possible to programmatically toggle HDR setting in windows somehow. Only via windows settings UI.

But from what I remember windows actually already does what you want anyway, it turns HDR off when you are unplugged. My G14 2024 that I had for some time with HDR support behaved exactly like that. Doesn't your device behave same ?

**Comment by seerge** [comment]
@madethisaccountcauseigotaquestion actually by googling a bit, it looks like you can even automate this in windows already
https://www.elevenforum.com/t/turn-on-or-off-hdr-on-battery-in-windows-11.7829/

![image](https://github.com/user-attachments/assets/b21f9ca1-9f92-4e25-96bf-cb1cdaad2240)

(i just don't have a laptop with HDR at the moment, so can't verify). Can you check ?

**Comment by seerge** [comment]
@madethisaccountcauseigotaquestion did this setting work for you ?

**Comment by madethisaccountcauseigotaquestion** [comment]
Yes this did work for me, thank you! and I apologize for the late response

**Comment by madethisaccountcauseigotaquestion** [comment]
that is all
