### ISSUE TITLE
GHelper interfieres with functionality of the ROG Falchion Low Profile RX

### ISSUE THREAD

**Issue by lcgd240** [seerge/g-helper#3355]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The key to lower volume in the Falchion Low Profile RX is Fn+T. When You activate this shortcut, instead of lowering volume as expected, the volume is muted. 

Keeping it pressed, an action that normaly escentially sends the same command over and over again, cycles the system volume between on and off very rapidly. 

Using the tactile panel at the back produces the same bug.

The issue fixes itself when you stop G-Helper

### How to reproduce the bug?

1.- Connect an ROG Falchion Low Profile with 2.4Ghz dongle
2.- Start G-Helper
3.- See how the Lower Volume shortcut becomes "Cycle mute on and off"

To fix it:
1.- Stop G-Helper

### Logs

[log.txt](https://github.com/user-attachments/files/17689619/log.txt)

### Device and Model

ROG FlowX13 - ROG Falchion Low Profile RX

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.197.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@lcgd240 hello,

As I see you have mapped `M1` key (which emits Volume Down on hardware level) under `Extra` to perform Mute action.  That's why any VolumeDown is now being interpreted as Mute (as you can't separate from where it comes from in windows)

Just set M1 action to it's default and it will work as you want again :) 

Thanks

**Comment by lcgd240** [comment]
Thank you so much!! This resolved the issue, I guess the problem was between the screen and the chair after all 😅.

**Comment by seerge** [comment]
@lcgd240 no worries, I'm glad it's resolved :) Thanks

**Comment by seerge** [comment]
@lcgd240 hello, 

If you are interested you can test external keyboards support in a new build https://github.com/seerge/g-helper/discussions/5710 

Thanks!
