### ISSUE TITLE
Multizone Control doesn't work on Mini-Led Display

### ISSUE THREAD

**Issue by TheChickeNugget** [seerge/g-helper#3356]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Next to the greybox that gives me my max refresh rate (for me, my display supports 240hz), there is a box for multizone control, however, for me, it is outlined red and the word "multizone" is greyed out. 

![image](https://github.com/user-attachments/assets/f14cf827-4e82-494a-a6a4-e0a8b6378962)

### How to reproduce the bug?

I am unable to reproduce the issue since it seems to stay there since the last 2 versions

### Logs

[log.txt](https://github.com/user-attachments/files/17690392/log.txt)

### Device and Model

ASUS ROG Flow X16

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.198.0

### OS

Windows 11 24H2

**Comment by TheChickeNugget** [comment]
To add on, HDR is inactive even thought it says so

**Comment by seerge** [comment]
@TheChickeNugget hello,

Both Miniled toggle and Visual Modes section are disabled because windows itself reports that HDR is turned ON. 

```
11/9/2024 9:44:16 PM: NE160QDM-NM4 HDR: True 10 3 False
```

It can happen because `Automatically Manage Color for Apps` is turned in the system. Can you check it's status and disable it if it's ON at `System -> Display -> Advanced Display -> Automatically Manage Color for Apps` ?

Thanks

**Comment by TheChickeNugget** [comment]
Oh it works again, thank you for the support!

**Comment by seerge** [comment]
@TheChickeNugget glad to hear

**Comment by l-tg** [comment]
Hello, sorry to dig up this thread. I'm having the same problem but I don't have _Automatically Manage Color for Apps_ in my parameters panel. Miniled are locked when I'm using iGPU only, with only dGPU enabled, there is no problem. In the nvidia panel, I tried to change color range from 10bits to 8bits but it does nothing. Any tips ? thx

**Comment by seerge** [comment]
@l-tg hello, what do you see in app's log ? Most likely windows (by some reason) reports that display is in HDR. Can you post log here ?

**Comment by l-tg** [comment]
Hey @seerge , thank you for your response. Somehow I didn't use my laptop for 2 days and it's ok now !

**Comment by TheLastAirbenderr** [comment]
> [@l-tg](https://github.com/l-tg) hello, what do you see in app's log ? Most likely windows (by some reason) reports that display is in HDR. Can you post log here ?

hi sorry to restart this but I am facing the same issue.

**Comment by seerge** [comment]
@TheLastAirbenderr then same question to you.

- Do you use HDR in windows ? Turn it off.
- Post a log
