### ISSUE TITLE
[Feature request] Change default screen refresh rate or prevent G-Helper from forcing highest screen refresh rate

### ISSUE THREAD

**Issue by Kevauz** [seerge/g-helper#3357]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I've always changed the refresh rate to 60hz, but it always changes to 144hz + OD by itself. Is there any way to prevent that? I don't play games with fps that high so its useless to me having it on 144hz + OD mode (and it actually makes things flicker on my end).

### Describe the solution you'd like

Stop forcing highest laptop screen refresh rate

### Device and Model

Asus TUF F15 FX507ZU4

**Comment by seerge** [comment]
@Kevauz hello,

Unless you have `Auto` refresh rate selected G-Helper does not force any refresh rates.

If it changes by itself - it means some other application doing this, not G-Helper. [Most likely Asus Smart Display control](https://github.com/seerge/g-helper/wiki/Requirements#recommendations-optional) that you may have installed. You need to remove it.

Thanks.

**Comment by Kevauz** [comment]
I don't have asus smart display control but have Asus monitor control, do they happen to be the same?
I never used auto on G-helper either.

**Comment by seerge** [comment]
@Kevauz most likely it does or it could be something else, you can check G-Helper's log at `%appdata%\GHelper\log.txt`. When it changes refresh rate as a result of an `Auto` option toggled or if you manually click specific refresh rate - it logs it.

You can simply quit G-Helper completely to verify what exactly changes your refresh rate :)

**Comment by Kevauz** [comment]
I uninstalled Asus monitor control and it did stop the change. My bad, I thought it was G-Helper all along.

Thanks for the help!

**Comment by seerge** [comment]
@Kevauz great to hear.

**Comment by Kevauz** [comment]
I restarted laptop again today for something and something was still changing my refresh rates. Already uninstalled everything asus though, so I'm not sure where to go now considering G-Helper doesn't have the log mentioning 144hz.

**Comment by seerge** [comment]
@Kevauz Asus System Control Interface is needed for system to function :) and it's not changing refresh rates.

Could it be something else, like a GPU driver or some other app or setting in windows ?

**Comment by Kevauz** [comment]
I already disabled asus services, and armoury crate isnt installed either. Not sure why its still in services though
![image](https://github.com/user-attachments/assets/6ce880a0-fb63-4092-b86b-a8debbb7041f)

I'll see it for another day or 2 and check again..

**Comment by Kevauz** [comment]
Theres no asus processes at all running

**Comment by seerge** [comment]
@Kevauz then may be GPU driver or something else setting that ?

**Comment by Kevauz** [comment]
I have 0 idea. I stopped Intel Graphics Command Center Service and it still changed to 144hz.

**Comment by seerge** [comment]
@Kevauz may be it’s NVidia apps doing that?

**Comment by Kevauz** [comment]
I'm suspecting the balanced power plan might be the culprit. Its the only power plan I have (w10).

But yeah will try 1 by 1 to try seeing if I can find what causes it.

**Comment by Kevauz** [comment]
Turns out it is indeed the driver. I updated the driver recently, and it stopped changing the refresh rate.
Also was buggy mess of a driver because Warframe kept having stutters with it, no longer with the newer driver (nov, the faulty one was oct).

**Comment by TheoVolk** [comment]
I've been having this exact same bug and felt like I was going crazy, i have removed ASUS smart display control, I have checked all of the NVidia settings and updated my drivers, and still when i launch Warframe (and only Warframe) the screen setting is forced from 60hz to 165 hz (I'm on the 2023 g14 with the 4050 and 7735). Any help would be amazing
