### ISSUE TITLE
Battery charge limit not working (Zephyrus g15 2022)

### ISSUE THREAD

**Issue by killer321455** [seerge/g-helper#336]
Asus armory crate and myasus not installed (uninstalled with debloat file)

the charge limit set to 90% but the laptop still charges to 100%

**Comment by seerge** [comment]
I believe this is a duplicate from https://github.com/seerge/g-helper/issues/319 

Check  log in ``%appdata/ghelper`` and if you see that app sets charge limit there to 90, it already does everything that can be done here.

Most probably it's either some leftowers from asus or bugged battery controller

**Comment by killer321455** [comment]
8.5.2023. 14:15:48: WMI event 56
8.5.2023. 14:15:49: BatteryLimit = 65 : OK
8.5.2023. 14:15:50: BatteryLimit = 70 : OK
8.5.2023. 14:15:50: BatteryLimit = 75 : OK
8.5.2023. 14:15:50: BatteryLimit = 80 : OK
8.5.2023. 14:15:50: BatteryLimit = 85 : OK
8.5.2023. 14:15:50: BatteryLimit = 90 : OK

I did the unbloat file again with admin this time

Also thank you for th quick response

**Comment by seerge** [comment]
@killer321455 well, from log it's clear that app sets limit :) what happens after is out of control :)

**Comment by killer321455** [comment]
ok thanks a lot
