### ISSUE TITLE
When charging with 100W PD, the laptop mode changes.

### ISSUE THREAD

**Issue by Sion1225** [seerge/g-helper#3367]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When using a standard 100W PD charger, it appears that, with the battery fully charged, the current supply intermittently connects and disconnects. During this, the g-helper repeatedly switches the laptop to battery mode (silent + 60Hz mode) and then reverts to the original mode (turbo + 165Hz OD mode).

During this process, the monitor also restarts.

### How to reproduce the bug?

Using a standard 100W PD charger.
Turbo mode activated.
Laptop in use.

### Logs

[log.txt](https://github.com/user-attachments/files/17711686/log.txt)

### Device and Model

Asus ROG Zephyrus G14 GA402XV

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.197

### OS

Windows 11 64bit

**Comment by seerge** [comment]
@Sion1225 hello,

This is most likely due to USB-C charger not providing enough power for your device - so it's switching to battery power as a fallback. G-Helper just listens to windows notifications about device running from the battery or being plugged in :)

You should either use regular (barrel) charger if you run heavy tasks OR reduce power usage on a laptop when you run from USB-C. Try Balanced mode, or set power limits.

Besides that - I can't do anything else here. Thanks.

**Comment by Sion1225** [comment]
@seerge Hello, 

Thank you for your response.

At the very least, I would like to improve the temporary freezing issue when switching to battery mode. How can I keep the display at 165Hz even when the computer is on battery?

Thank you.

**Comment by seerge** [comment]
@Sion1225

As far as you don't have `Auto` refresh rate enabled (and according to the log - you don't) G-Helper won't be touching your refresh rate.  I see that you have Asus Smart Display control app installed - you need to remove it, or it will interfere and try to change refresh rates when you unplug or plug in.

**Comment by Sion1225** [comment]
@seerge Thank you so much for your help! 
I hope everything goes well :)
