### ISSUE TITLE
I suggest adding the Russian language

### ISSUE THREAD

**Issue by Ilya-04** [seerge/g-helper#3374]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

The program does not have a Russian language, which complicates its use for Russian-speaking people who do not speak other languages well.

### Describe the solution you'd like

I have translated the program into Russian, I attach the file "Strings.ru.resx"
[Strings.ru.txt](https://github.com/user-attachments/files/17748475/Strings.ru.txt)
(GitHub does not allow to upload a file with the resx extension, so txt)

### Device and Model

ASUS TUF Gaming A15 FA507NU

**Comment by Ilya-04** [comment]
It's funny that you are too lazy to do Russian localization using a ready-made file... Okay, I've already added the language file and rebuilt the program. I wanted the Russian version of this wonderful program to exist in the world, but it didn't work out. Well, now I'm the only one who will have the Russian version of this program!

**Comment by ghhfffgh** [comment]
Илья поделись русской версией пожалуйста.
