### ISSUE TITLE
Constant-temperature fan curve

### ISSUE THREAD

**Issue by Matszwe02** [seerge/g-helper#3376]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

at 60C on CPU without using it I don't need fans to cool the same amount as at 60C when gaming

### Describe the solution you'd like

I suggest creating a new option for fan control, that's based on heater control algorithms, like PID or MPC. When using it, PC may be able to dynamically adjust how much it needs to run fans at, depending on the current condition (or maybe even cpu/gpu usage?).
That way laptops will have more battery life, because of not turning on fans at non-crucial temperatures, reduce noise at low-medium cpu usages and possibly extend cpu lifespan (when counting lower ΔT that's between idle and max usage).
If using MPC algorithm, fans could respond quickly to cpu usage increase, so it doesn't overshoot much at the dangerous temperatures.

### Describe alternatives you've considered

Alternative will be to have the fan control open for end-user so it can be tuned outside of the specs of this project

### Device and Model

none

### Additional information.

Let me know if that thing is even possible, or if ASUS API limits what can be done with the fan somehow. If you think this project doesn't need that, maybe I could make a fork with that functionality?

Great project, way better than standard asus software!

**Comment by seerge** [comment]
@Matszwe02 hello,

Fans are always controlled by BIOS based on it’s internal algorithms, even when you set a custom fan curve.

If you want a more precise Fan control you can try Experimental build 

https://github.com/seerge/g-helper/discussions/2272

There you can try to create a flatter fan curve.

Thanks
