### ISSUE TITLE
Dynamic Boost GPU values reset/not applied when changing profiles

### ISSUE THREAD

**Issue by edzchen747** [seerge/g-helper#338]
After setting the dynamic boost slider to 25W, GPU power increases by 25W, however if I change performance profiles, the GPU doesn't get an extra 25W and I need to click on the slider again to increase it.

Zephyrus Duo 16
GPU: RTX4080 laptop

**Comment by seerge** [comment]
@edzchen747 correct, GPU settings are not attached to profiles at all, i was planning to add that somewhere in next releases :)

**Comment by seerge** [comment]
@edzchen747 added in https://github.com/seerge/g-helper/releases/tag/v0.59

**Comment by seerge** [comment]
@edzchen747 what do you understand under power settings? GPU settings? if so - yes,i  can add a delay. As there is already a delay before applying "real" power settings (CPU PPT / and Platform PPT for supported models)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11432387/GHelper.zip)
@edzchen747 can you try this build ?
