### ISSUE TITLE
Can we add a feature that allows different modes for specific games, similar to Armoury Crate?

### ISSUE THREAD

**Issue by TheWuSi** [seerge/g-helper#3381]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

For some specific games, such as CSGO, VALORANT, automatically change the mode when starting these games

### Describe the solution you'd like

For some specific games, such as CSGO, VALORANT, automatically change the mode when starting these games

### Device and Model

ROG G713RW

**Comment by seerge** [comment]
@TheWuSi hello, I was answering this few times before. Currently G-Helper doesn’t monitor what apps are starting , so it simply can’t change any profiles based on that. As it might be quite resource heavy too.

I know that people use game launchers like Playnite, and there you can emit a corresponding G-Helper’s hotkey to select desired mode.

Also it’s actually already very easy to switch between modes using FN+F5 and Shift + FN + F5 to go forward and backwards

**Comment by TheWuSi** [comment]
thanks
