### ISSUE TITLE
Currently no exe file, Ghelper.csproj file is present (I assume instead of .exe)

### ISSUE THREAD

**Issue by TheRedFox27** [seerge/g-helper#3383]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Not sure how else to elaborate

### How to reproduce the bug?

Not a but

### Logs

 Can't run the program until exe is 

### Device and Model

Zephyrus G14 GA401IV_GA401IV

### Armoury Crate

Uninstalled

**Comment by seerge** [comment]
@TheRedFox27 you need to download exe from releases. Just click on a big bold Download link on the homepage 

https://github.com/seerge/g-helper/releases/latest/download/GHelper.zip

**Comment by TheRedFox27** [comment]
oh whoops im a dummy thanks!
