### ISSUE TITLE
G-Helper without the modes

### ISSUE THREAD

**Issue by klutzraku** [seerge/g-helper#3387]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Is there a way to remove the modes? I prefer to mix the functions of the Armoury Crate's Modes and the other versatile functions of GHelper additional functions?

### Describe the solution you'd like

Is there a possibility to have a version of the GHelper with anything just without the modes?

### Device and Model

Asus TUF F15 FX506HCB

**Comment by seerge** [comment]
@klutzraku hello, I don’t think thats possible as all optional customisations are always based on base modes.

What exactly are you trying to achieve?

**Comment by klutzraku** [comment]
I was wondering if it is possible to remove the modes (silent, balance, turbo) or disable them using the hotkey (Fn+F5)? Thank you so much for the reply

**Comment by seerge** [comment]
@klutzraku what other features do you want to use without modes?

**Comment by klutzraku** [comment]
nothing more, just that feauture. Thanks!

**Comment by seerge** [comment]
@klutzraku you did not get me, why do you need G-Helper, if you don’t need modes. What features do you use in all then?

**Comment by klutzraku** [comment]
I pretty much use all the other features, I just miss the profiles for when I play games or use specific apps

**Comment by seerge** [comment]
@klutzraku as I mentioned most of “other” fractures, depending on on this profiles. They won’t work without them

**Comment by klutzraku** [comment]
oh okay okay, thanks for the information and the help. I'll close this now
