### ISSUE TITLE
Partial screen blackout and horizontal bar with "auto" and "144hz + OD" (Zephyrus G14)

### ISSUE THREAD

**Issue by vwgeiser** [seerge/g-helper#3389]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Part of the screen goes black upon switching to "Auto" or "144hz + OD" on my Zephyrus G14.

Issue repeats every startup cycle. switching to 60hz resolves the issue.

Occasionally, after I have been using it for an hour or two I can switch back to 144 + OD without issue.

Issue persisted and got worse(?) after a hard reset. It used to only block out a small horizonal bar as seen in the MS word screenshot, after a hard reset it started blocking out the entire lower portion of the screen as seen in the other two screenshots.

### How to reproduce the bug?

Start up Zephyrus G14 when GHelper has been set to Auto or 144hz + OD or switch to these modes after start up.

### Logs

[log.txt](https://github.com/user-attachments/files/17818318/log.txt)

### Device and Model

Asus Zephyrus G14 A401QM-211

### Additional information.

![20241119_071140](https://github.com/user-attachments/assets/23799273-715a-4c33-a924-01f9acc97999)
![Screenshot_20241118_180801_Gallery](https://github.com/user-attachments/assets/9c85923b-3380-4ee4-97ed-fa820a7a729a)
![Screenshot_20241119_092731_Gallery](https://github.com/user-attachments/assets/06fbb55e-93de-4b56-a08f-ec8fa0c5fa9e)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.197.0

### OS

Windows 11

**Comment by seerge** [comment]
@vwgeiser hello, G-Helper just changes refresh rate i windows settings.

Does same happen if you would manually set 144Hz in Settings - Display in windows? Then most likely it’s something with screen itself.

**Comment by vwgeiser** [comment]
@seerge Ah dang, yeah it does. Ouch.
