### ISSUE TITLE
FX506LH - F6 key (disable screen - switch off screen light) has printscreen shortcut

### ISSUE THREAD

**Issue by VPerfeito** [seerge/g-helper#3390]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

First of all thank you for the amazing app. i am here reporting that the f6 key on the fx506lh performs a function different from the original. Instead of shutting off the screen light it makes a print screen.
Also on laptop running wind 10 the app tells that there is a LAN driver updatade avaible but that update its only for win 11 user
it woud be nice if we could choose what the Fkeys make. For exemple F11 and F12 are for hibernation and aeroplane mode. many users dont use-it and with g-helper it has happened to missclik on f11 and shut down the computer. Another funcion like blocking windows or anything else would be nice
thank you for the good work

### How to reproduce the bug?

C

### Logs

C

### Device and Model

Asus FX506LH

### Additional information.

C

### Armoury Crate

Uninstalled

### Asus Services

MYASUS

### Version

0.197

### OS

WINDOWS 10 22H2

**Comment by seerge** [comment]
@VPerfeito hello,

I was answering this few times already.

On all new (and most of the old) devices- FN+F6 does the PrintScreen. So i just mapped F6 with Fn-Lock on to do same.

Isn’t it more useful function than screen off?

As for changing default actions of FN+F[x] keys it’s not that easy, as some hotkeys are processed directly by firmware and G-Helper is not even involved there, and in some G-Helper just works as a proxy - it captures hotkey press and launches appropriate firmware action. 

So I don’t want to introduce extra confusion here and another level of complexity. 

Sorry
