### ISSUE TITLE
404 Not Found for Armoury Crate Control Interface Update

### ISSUE THREAD

**Issue by Velgus** [seerge/g-helper#3391]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The link for the Armoury Crate Control Interface driver on the ASUS Zephyrus G14 G403 is broken - it leads to an 404 Not Found: https://dlcdnets.asus.com/pub/ASUS/GamingNB/Image/Software/SoftwareandUtility/16223/ArmouryCrateControlInterface_ASUS_Z_V1.1.0.0_16223.exe?model=GA403UI

### How to reproduce the bug?

1. Go to Updates section
2. Click 1.1.0.0 next to Armoury Crate Control Interface
3. See error 404 Not Found

### Logs

N/A

### Device and Model

ASUS Zephyrus G14 GA403

### Armoury Crate

Never installed

### Asus Services

0

### Version

0.197.0

### OS

Windows 11 24H2

**Comment by seerge** [comment]
@Velgus hello, G-Helper gets list pf available downloads from official asus website for your model. 

If link is broken there - it will be same here. I can’t do anything about that. Sorry
