### ISSUE TITLE
GHelper running makes game crashed

### ISSUE THREAD

**Issue by Arkstarz2212** [seerge/g-helper#3394]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I ran Zenless Zone Zero, Ghost of Tsushima...etc. game keep crashing(stop running after 10s ) I like the way Ghelper is so useful but i can't use it since game keep crashing when running along with Ghelper. I did try to run game solo without Gh and it runs normally.

### How to reproduce the bug?

1.Ghelper opened by startup 2.Open games 3.Game crashed 4,Remove Ghelper and game will run normally

### Logs

[log.txt](https://github.com/user-attachments/files/17838710/log.txt)

### Device and Model

Zephyrus GA401QC

### Armoury Crate

Uninstalled

### Asus Services

Stopped and Uninstalled

### Version

latest

### OS

WINDOW 11 24H2

**Comment by Arkstarz2212** [comment]
im new to Ghelper and just been using asus laptop for a month or two. From an Acer Nitro laptop to Zephyrus is lots of differences for me. AC just not that good tbh. If only i could be able to use Ghelper without game crashing all the time :(

**Comment by seerge** [comment]
@Arkstarz2212 hello, 

I see that you have overclocked your GPU too much. 

Just set clock offsets back to 0 or click Factory Defaults and you will be fine.

Thanks
