### ISSUE TITLE
After deselecting the CPU power limit option, the CPU power limit is not immediately lifted.

### ISSUE THREAD

**Issue by NatsuZoraKanata** [seerge/g-helper#3395]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When the CPU power limit has been set, deselect the CPU power limit option. The CPU power limit will not be canceled immediately. You need to switch to performance mode once to cancel the limit.

### How to reproduce the bug?

1. The CPU power limit has been set.  
2. Deselect the power limit option.  
3. The power limit could not be removed.  
4. Switch the performance mode once (e.g., switch from Silent to Balanced and back to Silent mode).  
5. The CPU power limit has been lifted.  
### Logs

[log.txt](https://github.com/user-attachments/files/17841980/log.txt)

### Device and Model

Asus TUF Gaming A15 - FA507XV

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.199.0

### OS

Windows 11 24H2

**Comment by seerge** [comment]
@NatsuZoraKanata hello, 

When you uncheck Apply power limits checkbox - app would just set same default mode again (and it happens in the log).

When one of the default modes is selected - firmware resets all limits to default as well.

How do you even test that it’s working?

**Comment by NatsuZoraKanata** [comment]
> @NatsuZoraKanata hello,
> 
> When you uncheck Apply power limits checkbox - app would just set same default mode again (and it happens in the log).
> 
> When one of the default modes is selected - firmware resets all limits to default as well.
> 
> How do you even test that it’s working?

https://github.com/user-attachments/assets/b87f522a-6bbd-4280-8bb3-95065d71fb5f

**Comment by NatsuZoraKanata** [comment]
I found that when setting a power limit, this option takes effect immediately. However, as shown in the video, when canceling the power limit, it does not take effect immediately and requires switching the performance mode.

**Comment by seerge** [comment]
@NatsuZoraKanata can you check if your limit would reset if you manually click on *same* mode (not on other). Cause if not - it looks more like a firmware hiccup in your case

**Comment by NatsuZoraKanata** [comment]
> @NatsuZoraKanata can you check if your limit would reset if you manually click on _same_ mode (not on other). Cause if not - it looks more like a firmware hiccup in your case

Clicking on the same mode does not reset the limit. Is this issue only solvable through a BIOS update from ASUS?

**Comment by seerge** [comment]
@NatsuZoraKanata actually G14 2024 (GA403) suffers from a similar problem. So G-Helper already has a workaround for that case - it literally does what you did manually (sets other mode and then original mode again).

I can add your model to the list where this workaround is enabled. But i need to be sure that it’s not just a glitch on your specific device.

Can you try to manually reinstall latest BIOS for your device and also do a hard reset (hold power button for 40) seconds and check if same behaviour persists?

**Comment by NatsuZoraKanata** [comment]
> @NatsuZoraKanata actually G14 2024 (GA403) suffers from a similar problem. So G-Helper already has a workaround for that case - it literally does what you did manually (sets other mode and then original mode again).
> 
> I can add your model to the list where this workaround is enabled. But i need to be sure that it’s not just a glitch on your specific device.
> 
> Can you try to manually reinstall latest BIOS for your device and also do a hard reset (hold power button for 40) seconds and check if same behaviour persists?

I downloaded and used the latest BIOS from the official ASUS website via ASUS EZ Flash. Afterward, I held down the power button for 40 seconds until all the indicator lights turned off. Upon releasing the button, the computer automatically rebooted, which should have completed the BIOS reset. 

Unfortunately, the issue still persists. 

Additionally, I noticed that the latest AMD driver seems to conflict with the default BIOS settings. It requires enabling the motherboard's advanced settings through [UMAF](https://github.com/[DavidS95/Smokeless_UMAF](https://github.com/DavidS95/Smokeless_UMAF)) and modifying the UMA buffer size. Otherwise, resetting the BIOS and booting into the system will cause the graphics driver to crash.

**Comment by seerge** [comment]
@NatsuZoraKanata ok, i will add your model to the list where app would set other mode to reset limits. I’m just not at the laptop for the next couple of weeks, so you will have to wait a bit :)

**Comment by seerge** [comment]
@NatsuZoraKanata ok, sorry for delay.

Try this build. It should do mode switching automatically in order to fix firmware issue with resetting power limits (same as app already does for G14 2024)

[GHelper.zip](https://github.com/user-attachments/files/18060529/GHelper.zip)

**Comment by NatsuZoraKanata** [comment]
> @NatsuZoraKanata ok, sorry for delay.好的，抱歉耽误了。
> 
> Try this build. It should do mode switching automatically in order to fix firmware issue with resetting power limits (same as app already does for G14 2024)尝试一下这个构建。它应该自动进行模式切换，以便通过重置功率限制来解决固件问题（与 G14 2024 的应用程序相同）
> 
> [GHelper.zip](https://github.com/user-attachments/files/18060529/GHelper.zip)

Sorry for the delay; I haven't been using my laptop recently. I just tested the version you provided, and the issue has been resolved. Thank you!

**Comment by seerge** [comment]
@NatsuZoraKanata great
