### ISSUE TITLE
Power Limits not being correctly set

### ISSUE THREAD

**Issue by Valour549** [seerge/g-helper#3397]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

PL1 and PL2 always apply the maximum 175W to both PL1 and PL2. Curiously, this happens whether the apply box is ticked or not, and happens regardless of mode.

### How to reproduce the bug?

1. I can check PL1 and PL2 values in both Throttlestop/HWinfo. They change correctly when I select different modes in Armory Crate.
2. But once I click on any mode in G-Helper, PL1 and PL2 gets set to 175W, even though I have different values for both Turbo and Balanced mode.
3. As mentioned, even if I untick the apply box, and repeat the above, PL1 and PL2 still get set to 175W. Also tried restarting laptop and G-Helper multiple times to no avail.

### Logs

[log.txt](https://github.com/user-attachments/files/17853913/log.txt)

### Device and Model

G834JZR

### Additional information.

This did not use to happen. Three recent changes occurred.
1) I upgraded to v0.199 G-Helper from whatever the previous version was. But I just tested on v0.197 and no difference.
2) BIOS and Armory Crate Control Interface were upgraded via MyAsus. So maybe one of these is the culprit.
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/3f0249ee-0f5a-49eb-bb05-d2cd3377804c">

### Armoury Crate

Installed

### Version

0.199

### OS

Windows 11 (23H2)

**Comment by seerge** [comment]
@Valour549 hello,

If you just look at PL1/PL2 values at HWinfo it takes them from Intel driver. And Asus sets power limits somewhere on BIOS level, so that won’t be reflected there.

Correct way to test if power limits are working - is to run Cinebench or any other CPU benchmark and just monitor actual power consumption in the same HWinfo.

If consumption is on the set levels - everything is correct. Can you try that?

Thanks

**Comment by Valour549** [comment]
You're right the actual consumption level is correct. I was relying on the changes in MMIO (PL1/PL2) in Throttlestop to gauge if changes were being applied.

I've posted a video [here](https://www.youtube.com/watch?v=07J_oqU0xcA) to more clearly illustrate the issue.

**Comment by seerge** [comment]
@Valour549 

G-Helper just sets one of 3 predefined modes via Armoury’s endpoint by ID (0,1 or 2). And then firmware does the rest - it sets all limits, fan settings etc.

Same for optional  custom power limits (also via AC endpoint for them). 

And in both cases it doesn’t affect those PL MMIO values you see inn HWinfo, cause asus firmware limits it somehow on BIOS level, not there.

I don’t have an Intel device now to check if PL values are affected when you do same in AC, but while I had Strix Scar 16 with 13900HX those values always stayed on max (despite in reality power was limited). I.e. AC was doing exactly same thing - just setting mode ID, and rest is on firmware.

You use custom settings in G-Helper, can you try to reset all to defaults? As in AC modes are not customised on top with other limits.

**Comment by Valour549** [comment]
Ah yes I see what you mean now. Setting any value for the PL1/PL2 in Manual mode inside AC also yield 175/175 for MMIO.

For some reason, the MMIO only changes when using the default Silent/Performance(Balanced)/Turbo modes without changes to PL values. I had believed the MMIO values to accurately reflect the true PL values, since MMIO is dynamic while MSR is static, but it would appear that there is a third hidden variable somewhere, and the actual consumption limit is the minimum of {MSR, MMIO, hidden variable}.

**Comment by seerge** [comment]
@Valour549 can you check if when you change default modes (w/o any custom settings on top) in G-Helper MIMO PL change?

**Comment by Valour549** [comment]
> duplicates PL values via some driver settings

This must be what is causing the MMIO PL values to change. Nice observation. I think you should apply it too if possible, so we can see the de facto PL values in Throttlestop or HWinfo.

With G-Helper modes set to factory defaults, yes they affect MMIO the same way as AC modes do. Manual mode in AC, just like G-Helper modes with changed PL, do not reflect in MMIO even though they do indeed effect change.

**AC mode (G-Helper mode): MMIO PL1/PL2** on G834JZR
Silent (Silent): 90/100
Performance (Balanced): 110/120
Turbo (Turbo): 170/175

**Comment by seerge** [comment]
@Valour549 

> With G-Helper modes set to factory defaults, yes they affect MMIO the same way as AC modes do. Manual mode in AC, just like G-Helper modes with changed PL, do not reflect in MMIO even though they do indeed effect change.

Then it means that asus firmware actually also adjusts MMIO values (as same happens for both AC and G-Helper)

This means that AC itself doesn’t not override MMIO values anyhow else. So there is no need yo make things more complicated than they are :) Especially considering that there is no known to me open source way to set those values. And they could be different for different models.

It’s better to keep it on firmware as asus have designed it.

**Comment by Valour549** [comment]
"fan_min": 10,
  "fan_hysteresis": 30,
  "fan_shift": 75,
  
  These have no effect in the standard 0.199 version right?

**Comment by seerge** [comment]
@Valour549 right, only for experimental build

**Comment by seerge** [comment]
@Valour549 ok, so as discussed. 

Since MMIO values change only when you use default modes and it happens for both AC and G-Helper - then it's most likely firmware adjusts those values. And as soon as you make it "custom" firmware would just "maximize" MMIO values to give itself room for a custom power limits set inside.

This is how Asus has programmed their devices, and since AC does same thing as G-Helper, I don't see any point to interfere and change it :)

Therefore closing. Thanks for interesting finds!
