### ISSUE TITLE
I have a G 14 2024 model  Disable on Lid close isn't working correctly 

### ISSUE THREAD

**Issue by TOMGhelper** [seerge/g-helper#3398]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Disable on lid close only works if I click the check mark every time after a fresh boot, regardless of whether it's checked.

### How to reproduce the bug?

Restart Your laptop.
After a fresh boot, wait for everything to start up, then close the lid
so the light will stay on. Once you open the g-helper app in the taskbar, Disable on lid close is checked off. I will close it a few times to make sure it's repeating itself which it does. I think it has something to do with the auto start when boot does seem to keep the value that has been changing and just loads the default setup till something is clicked when then it seems to peek up the changes and sometimes my laptop temps will then start to drop meaning that those values are not being set
![Screenshot 2024-11-22 145754](https://github.com/user-attachments/assets/0a134158-3bce-44b5-814b-59b017b6e4a4)

### Logs

[log.txt](https://github.com/user-attachments/files/17875722/log.txt)

### Device and Model

Rog Zephyrus G14 GA403UI

### Additional information.

![Screenshot 2024-11-22 145946](https://github.com/user-attachments/assets/bd759825-a2d0-410c-9088-d788a3c03082)
![Screenshot 2024-11-22 145754](https://github.com/user-attachments/assets/6622b323-d82d-4e88-949f-c9d83dffa222)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.199.0

### OS

Windows 11 Pro 24H2

**Comment by seerge** [comment]
@TOMGhelper hello,

To turn Slash Lighting off on Lid Close G-Helper needs to be running (at least in system tray)

From the log I see that every time windows notifies app about Lid Close event - it sets Slash brightness to 0 (and back to 1 when it’s open)

```
11/21/2024 6:15:25 PM: Lid Closed
11/21/2024 8:53:33 PM: SlashLidCloseAnimation False:5E-D8-00-00-02-A5-00-00-00-00-00-00-00-00-00-00-
…
11/21/2024 8:53:33 PM: Lid 19B6|63: 5A-BA-C5-C4-00 <—- BRIGHTNESS LEVEL 0
```

**Comment by TOMGhelper** [comment]
Yes, the app is open at all times I have it set to start on boot I only see this problem after I use the computer for about 30 minutes, close the lid, and the light stays on no matter what but yes the app is always open while its happing

**Comment by seerge** [comment]
@TOMGhelper can you manually close the lid and then check if LidClose event and slash off command appears in the log?

Also check what action is set to Lid Close under control panel.

AC could be interfering if you didn’t use official AC uninstaller. Check windows task manager for all apps containing word “asus”

**Comment by TOMGhelper** [comment]
![Screenshot 2024-11-26 145002](https://github.com/user-attachments/assets/adb16d05-62eb-4a98-aff6-6281b42ad0e1)
![Screenshot 2024-11-26 145145](https://github.com/user-attachments/assets/aac09ee0-b7cf-4a85-aa03-36aa25ce8645)

**Comment by TOMGhelper** [comment]
It will work for a while it's only after I let the computer set for an hour or so that it stops auto shut off once closed, I have to open the g-helper app in the taskbar click the check mark uncheck, and recheck it for it to work again once doing this I see a little flash after clicking it telling me that it been set so for some reason once ide for some time the value is set to default again?

**Comment by TOMGhelper** [comment]
Version 0.197.0 does not seem to have the problem

**Comment by seerge** [comment]
@TOMGhelper 
> can you manually close the lid and then check if LidClose event and slash off command appears in the log?

Can you check the log for a lid close event when slash didn’t turn off?

**Comment by seerge** [comment]
@TOMGhelper 
> Version 0.197.0 does not seem to have the problem

can you check 0.198?

**Comment by TOMGhelper** [comment]
I spoke too early it seems to happen after I let my laptop go to standby mode or idle for 30 minutes then, once I close the laptop, the slash will stay on then I open the computer open the G-helper running in the taskbar and it's checked off to disable on lid close ill uncheck it then check it off again and it works fine till it happens again. 
[log.txt](https://github.com/user-attachments/files/17928483/log.txt)

**Comment by seerge** [comment]
@TOMGhelper and again - every single time Lid Close event is recorded - Slash is turned off in the log.

It looks like by some (unknown) reasons windows just stops notifying about lid close events , and then app won’t do anything as it’s simply not aware about it.

Unchecking and checking lid-close checkbox probably has only psychological effect (as app does not forget settings anyway. Most likely just opening app window - reminds system about it’s existence, and it starts notifying it about lid close events again.

I simply don’t know how can I help you here, since i can’t even reproduce it. For me - system notifies about lid close events all the time

**Comment by TOMGhelper** [comment]
I am not sure why this fixed the problem, but I used Wise Program uninstaller to uninstall all Asus apps, and then I downloaded Army Crate uninstaller and also ran that after all this, I don't have that problem anymore

**Comment by seerge** [comment]
@TOMGhelper then looks like some strange leftover was still running and interfering. I’m glad it’s resolved

**Comment by TOMGhelper** [comment]
Sorry, I never got back to you. I just picked up the new G14 and I've had no problems with the slash lighting. 
Thanks again for making this software. It's the best and only reason I'm still buying the G14!
