### ISSUE TITLE
"G-Helper is already running" dialog pops up on every startup

### ISSUE THREAD

**Issue by Stabilizer1071** [seerge/g-helper#3399]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I've not using my laptop for quite a long time, and after today's Windows and G-Helper updates, I noticed that the "G-Helper is already running. Check system tray for an icon" dialog (as below, in Chinese) pops up on every startup. 

![image](https://github.com/user-attachments/assets/3baafdae-578c-4474-83fd-6330315588d3)

I tried to disable and re-enable the auto-startup in G-Helper and it didn't seem to work. I also tried manually add the shortcut to the system's StartUp folder and it's kind of working -- no dialog but the G-Helper will show up on the right corner and I still have to close it just as I have to close the dialog so it's not working XD

What I found in the log file is that it seems to be related to the system api call: 
```
24/11/23 20:56:52: System.ComponentModel.Win32Exception (5): 拒绝访问。 # Access denied, in English
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at GHelper.Helpers.ProcessHelper.CheckAlreadyRunning() in D:\a\g-helper\g-helper\app\Helpers\ProcessHelper.cs:line 21
```
The system version is Windows 11 24H2 (26120.2415, latest Dev channel insider build).

### How to reproduce the bug?

1. Check the "Run on Startup" checkbox
2. Reboot
3. Enjoy the dialog

### Logs

24/11/23 20:54:08: Internal screen off
24/11/23 20:54:10: Can't remove charge limit task: 拒绝访问。 (0x80070005 (E_ACCESSDENIED))
24/11/23 20:54:10: Latest version 0.199.0.0
24/11/23 20:54:12: Startup task scheduled: D:\Tools\GHelper\GHelper.exe
24/11/23 20:54:12: Can't create a charge limit task: 拒绝访问。 (0x80070005 (E_ACCESSDENIED))
24/11/23 20:55:41: BatteryLimit = 60 : OK
24/11/23 20:56:51: ------- Startup Battery Limit 60 -------
24/11/23 20:56:52: System.ComponentModel.Win32Exception (5): 拒绝访问。
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at GHelper.Helpers.ProcessHelper.CheckAlreadyRunning() in D:\a\g-helper\g-helper\app\Helpers\ProcessHelper.cs:line 21
24/11/23 20:56:55: Matrix control device was not found on your machine.
24/11/23 20:56:59: C:\ProgramData\ASUS\GameVisual doesn't exit
24/11/23 20:56:59: Limit = 60 : OK

### Device and Model

ROG Zephyrus G14 GA401IV

### Armoury Crate

Uninstalled

### Version

0.197 & 0.199

### OS

Windows 11 24H2

**Comment by seerge** [comment]
@Stabilizer1071 hello, you seem to have scheduled app twice under different user accounts in windows.

Try to run it as admin and then uncheck and check “Run on Startup” checkbox.

**Comment by Stabilizer1071** [comment]
> @Stabilizer1071 hello, you seem to have scheduled app twice under different user accounts in windows.
> 
> Try to run it as admin and then uncheck and check “Run on Startup” checkbox.

I only have one user account on my laptop but problem solved just like magic.
Thanks for saving me from OCD ❤️
