### ISSUE TITLE
[Question] How to fully remove Armoury Crate and Asus bloat?

### ISSUE THREAD

**Issue by hotsno** [seerge/g-helper#34]
As the goal for many of us using this program is to get rid of Armoury Crate and whatever bloat that Asus has shipped with the OS, I've noticed that despite uninstalling Armoury Crate as well as several other Asus apps (from `Settings > Apps > Installed apps`) that I deemed unnecessary, my processes in Task Manager seem to still be filled with Armoury Crate/Asus related tasks. [Here](https://i.imgur.com/oAP71IG.png) are some of the processes I still see.

How can I fully remove (or maybe just disable) these? Is any of the pre-installed Asus stuff necessary/recommended to keep? I read on @seerge 's Reddit post that:
> I also recommend to keep (!) "Asus Optimization Service" running , as it keeps basic laptop hotkeys such as screen or keyboard brightness adjustment working. If you have (or had) MyASUS app installed, that service is most probably still up an running even after MyASUS uninstall.

I also found this [script](https://gist.github.com/supermitsuba/404babf56bc503bd6dbd81dfd6cfbb47) in the comments of the Reddit post for disabling some unnecessary services, which I haven't yet tried but might cover a lot of these tasks that are running automatically for me.

Sorry if this is unwanted here in the issue tracker, but I thought that other people might end up benefiting from this being here as well.

**Comment by seerge** [comment]
Did you use official Armory uninstall tool ? After that I would recommend to manually go to "Add or Remove programs" and uninstall everything that says ROG/Aura/etc.

Next to that, there is (a bit outdated), but still relevant guide https://github.com/sammilucia/ASUS-G14-Debloating :)

**Comment by hotsno** [comment]
Thanks!
