### ISSUE TITLE
Screenpad glitches and lack of support on ASUS ROG Zephyrus Duo 15 SE

### ISSUE THREAD

**Issue by edxeth** [seerge/g-helper#3402]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I'm not able to control screenpad brightness via GHelper or its keybinds (I read here it's FN + SHIFT + F7/F8). I'm able to see `screenpad brightness down` and `screenpad brightness up` in the dropdown of key bindings in the extra menu but they don't work either. Besides, everytime I restart Windows the screenpad brightness is more than often reset to 100% automatically although I previously set it to say 10/20% in ScreenXpert settings (that's the app I use to control my screenpad brightness or else I'm stuck forever with 100%).

My edited config.json:

```json
{
  "scheme_0": "381b4222-f694-41f0-9685-ff5bb260df2e",
  "scheme_1": "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c",
  "scheme_2": "381b4222-f694-41f0-9685-ff5bb260df2e",
  "scheme_3": "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c",
  "max_gpu_core": 300,
  "max_gpu_memory": 1000,
  "stop_ac": 1,
  "performance_mode": 2,
  "performance_1": 2,
  "gpu_mode": 1,
  "internal_display": "LQ156M1JW25",
  "screen_max": 300,
  "frequency": 60,
  "overdrive": 0,
  "aura_color": -65536,
  "charge_limit": 100,
  "charge_full": 0,
  "mid_fan": 0,
  "xgm_fan": 0,
  "fan_profile_cpu_1": "1E-2D-41-43-4C-4D-4C-4D-00-26-38-41-4B-4B-4B-4B",
  "fan_profile_gpu_1": "1E-2D-3E-41-48-4C-4D-4C-00-26-29-35-48-4B-4B-4B",
  "limit_total_1": 150,
  "limit_cpu_1": 80,
  "limit_fast_1": 125,
  "gpu_auto": 0,
  "screen_auto": 0,
  "fan_profile_cpu_2": "1E-37-3C-40-48-4E-54-5A-00-1F-23-26-32-32-32-32",
  "fan_profile_gpu_2": "1E-37-3C-40-4E-54-5A-60-00-1C-1F-23-2C-2C-2C-2C",
  "limit_total_2": 125,
  "limit_cpu_2": 5,
  "limit_fast_2": 150,
  "auto_apply_power_2": 0,
  "auto_apply_2": 0,
  "auto_uv_2": 0,
  "cpu_uv_2": 0,
  "igpu_uv_2": 0,
  "auto_boost_2": 0,
  "fan_profile_cpu_0": "1E-35-3C-41-45-4B-4C-4B-00-1F-26-29-3B-3E-3E-3E",
  "fan_profile_gpu_0": "1E-35-3C-43-4B-4C-4B-4C-00-1C-26-2F-41-41-41-41",
  "limit_total_0": 125,
  "limit_cpu_0": 80,
  "limit_fast_0": 125,
  "auto_boost_1": 2,
  "auto_apply_1": 1,
  "auto_apply_power_1": 1,
  "gpu_core_1": 0,
  "gpu_memory_1": 0,
  "auto_uv_1": 0,
  "cpu_temp_1": -1,
  "cpu_uv_1": 0,
  "igpu_uv_1": 0,
  "gpu_clock_limit_1": 3000,
  "gpu_boost_1": 25,
  "gpu_temp_1": 87,
  "auto_apply_0": 1,
  "auto_apply_power_0": 0,
  "auto_uv_0": 0,
  "cpu_temp_0": -1,
  "cpu_uv_0": 0,
  "igpu_uv_0": 0,
  "gpu_clock_limit_0": 3000,
  "gpu_boost_0": 25,
  "gpu_temp_0": 87,
  "gpu_core_0": 0,
  "gpu_memory_0": 0,
  "mode_base_3": 2,
  "mode_name_3": "Extreme",
  "fan_profile_cpu_3": "24-2C-3C-42-43-46-4E-50-64-64-64-64-64-64-64-64",
  "fan_profile_gpu_3": "1D-2D-3A-41-45-46-48-4A-64-64-64-64-64-64-64-64",
  "limit_total_3": 150,
  "limit_cpu_3": 40,
  "limit_fast_3": 150,
  "auto_uv_3": 1,
  "gpu_memory_3": 500,
  "auto_apply_power_3": 1,
  "powermode_3": "ded574b5-45a0-4f42-8737-46345c09c238",
  "gpu_core_3": 125,
  "auto_apply_3": 1,
  "gpu_clock_limit_3": 2990,
  "cpu_temp_3": 98,
  "cpu_uv_3": 0,
  "igpu_uv_3": 0,
  "performance_0": 2,
  "fan_max_0": 76,
  "fan_max_1": 88,
  "auto_boost_3": 2,
  "keyboard_brightness": 0,
  "aura_mode": 0,
  "screenpad": 100,
  "arrow_lock": 0,
  "limit_slow_2": 125,
  "limit_slow_0": 125,
  "limit_slow_3": 150,
  "keyboard_awake": 1,
  "keyboard_boot": 1,
  "keyboard_sleep": 0,
  "keyboard_shutdown": 1,
  "keyboard_awake_bar": 1,
  "keyboard_boot_bar": 1,
  "keyboard_sleep_bar": 1,
  "keyboard_shutdown_bar": 1,
  "keyboard_awake_lid": 1,
  "keyboard_boot_lid": 1,
  "keyboard_sleep_lid": 1,
  "keyboard_shutdown_lid": 1,
  "keyboard_awake_logo": 1,
  "keyboard_boot_logo": 1,
  "keyboard_sleep_logo": 1,
  "keyboard_shutdown_logo": 1,
  "limit_slow_1": 150,
  "aura_color_custom": "16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215-16777215",
  "keyboard_brightness_ac": 0,
  "bw_icon": 1,
  "max_frequency": 300,
  "start_count": 244,
  "fan_rpm": 1,
  "donate_click": 155,
  "visual": 11,
  "color_temp": 50,
  "no_overdrive": 0,
  "fn_lock": 0,
  "aura_speed": 1,
  "auto_boost_0": 0,
  "powermode_1": "00000000-0000-0000-0000-000000000000",
  "boot_sound": 0,
  "screenpad_toggle": 1,
  "fnv": "",
  "fnc_custom": ""
}
```

PS: ASUS special screenpad button allows to switch screenpad mode to 0% brightness (display on), 100% brightness (display on), or display off. That's probably why in the config file we see screenpad set to 100(?).

### How to reproduce the bug?

1. Set ScreenXpert brightness to any range.
2. Attempt pressing FN + SHIFT + F7/F8 to discover it's not adjustable.
3. Restart Windows to see the screenpad brightness getting reset to 100% which in turn overrides ScreenXpert set brightness.

### Logs

2024-11-23 11:29:14 PM: ------------
2024-11-23 11:29:14 PM: App launched: ROG Zephyrus Duo 15 SE GX551QM_GX551QM :0.199.0.0en-US
2024-11-23 11:29:14 PM: Start Count: 244
2024-11-23 11:29:15 PM: NVIDIA GeForce RTX 3060 Laptop GPU
2024-11-23 11:29:16 PM: CPU: 7 - AMD Ryzen 7 5800H with Radeon Graphics          - AMD64 Family 25 Model 80 Stepping 0
2024-11-23 11:29:16 PM: AutoSetting for Online
2024-11-23 11:29:16 PM: BatteryLimit = 100 : OK
2024-11-23 11:29:16 PM: ScreenpadOn = 1 : OK
2024-11-23 11:29:16 PM: Screenpad = 255 : OK
2024-11-23 11:29:16 PM: Power Plan 381b4222-f694-41f0-9685-ff5bb260df2e:OK
2024-11-23 11:29:16 PM: Eco flag : 0
2024-11-23 11:29:16 PM: Mux flag : -65536
2024-11-23 11:29:16 PM: \\?\DISPLAY#SHP152C#5&3adf75ea&c&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
2024-11-23 11:29:16 PM: \\?\DISPLAY#SHP152C#5&3adf75ea&c&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
2024-11-23 11:29:16 PM: LQ156M1JW25 HDR: False 8 4 True
2024-11-23 11:29:16 PM: Mode = 2 : OK
2024-11-23 11:29:16 PM: Input available: \\?\hid#vid_0b05&pid_19b6&mi_00&col01#8&3a080f36&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 64
2024-11-23 11:29:16 PM: Init 19B6: 5D-B9
2024-11-23 11:29:16 PM: USB 19B6|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2024-11-23 11:29:16 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
2024-11-23 11:29:16 PM: Input: \\?\hid#vid_0b05&pid_19b6&mi_00&col01#8&3a080f36&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
2024-11-23 11:29:16 PM: Init 19B6: 5D-05-20-31-00-1A
2024-11-23 11:29:16 PM: USB 19B6: 5D-BD-01-DF-1F-FF-FF-FF
2024-11-23 11:29:16 PM: AuraMode: AuraStatic
2024-11-23 11:29:17 PM: USB 19B6: 5D-B3-00-00-FF-00-00-EB-00-00-FF-FF-FF-00-00-00-00
2024-11-23 11:29:17 PM: USB 19B6: 5D-B5-00-00-00
2024-11-23 11:29:17 PM: USB 19B6: 5D-B4
2024-11-23 11:29:17 PM: Auto 19B6: 5D-BA-C5-C4-00
2024-11-23 11:29:17 PM: LQ156M1JW25 HDR: False 8 4 True
2024-11-23 11:29:18 PM: Monitor Power On
2024-11-23 11:29:18 PM: BatteryLimit = 100 : OK
2024-11-23 11:29:18 PM: Lid Open
2024-11-23 11:29:18 PM: Lid 19B6: 5D-BA-C5-C4-00
2024-11-23 11:29:19 PM: Latest version 0.199.0.0

### Device and Model

ASUS ROG Zephyrus Duo 15 SE (GX551QM)

### Additional information.

Primary display: Full HD @ 60/300Hz
Secondary display: Full HD @ 48Hz

### Armoury Crate

Uninstalled

### Asus Services

Not running / all stopped

### Version

0.199.0

### OS

Microsoft Windows 11 Pro 22H2 (version 10.0.22621, build 22621)

**Comment by seerge** [comment]
@edxeth hello,

Can you control screenpad brightness via asus own apps?

Cause the only known endpoint to set screenpad level is there, and firmware accepts brightness command

‘’’
2024-11-23 11:29:16 PM: Screenpad = 255 : OK
‘’’

It could be that your device either doesn’t support screenpad brightness adjustments or asus does it in some other way as your device is quite old.

**Comment by edxeth** [comment]
@seerge hi, thanks for the prompt response!

I wouldn't really know which ASUS app controls the brightness apart from ScreenXpert (currently on v3.1.42.0) as that's the only one I've seen featuring this particular functionality since I was own this laptop. Here's a demonstration:

https://github.com/user-attachments/assets/e1468cf2-34bf-4d9d-bf97-e1f793c53b78

**Comment by seerge** [comment]
@edxeth hello, sorry for a slow response, I was away.

From your video it seems that screenpad only shows some pre-defined proprietary content. Can you use it as a regular second display in windows as well?

If so - it could be that since your device is quite old, endpoint for setting brightness may be different on it comparing to what is publicly known atm.

Can you do a scan and DSDT dump as [explained in this issue](https://github.com/seerge/g-helper/issues/38) and upload both here ?

**Comment by edxeth** [comment]
Hi @seerge 
Yes, I'm able to use the screen as a regular second display. ScreenXpert is just an add-on application that adds extra features to the screenpad.

Method #1 output:

```shell
60023 : ffffffffffff0004 (-65532)
60024 : a36c8086 (2741796998)
60026 : 0 (0)
60061 : ffffffffffff0000 (-65536)
60094 : 3 (3)
80041 : ffffffffffff0000 (-65536)
80042 : 0 (0)
80043 : ffffffffffff0000 (-65536)
80044 : ffffffffffff0000 (-65536)
90020 : 0 (0)
90030 : 54 (84)
100051 : 1 (1)
100052 : 1 (1)
100063 : 0 (0)
110013 : 0 (0)
110014 : 0 (0)
110015 : ffffffffffff0000 (-65536)
110016 : ffffffffffff0000 (-65536)
110022 : a8 (168)
110023 : a8 (168)
Invoke-CimMethod : Generic failure
At C:\Users\mysol\OneDrive\Desktop\scan-atkacpi.ps1:5 char:20
+ ...  $result = (Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -Cl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (AsusAtkWmi_WMNB...PNP0C14\ATK_0"):CimInstance) [Invoke-CimMethod], CimExc
    eption
    + FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand
	
110024 : ffff0000 (-65536)
Invoke-CimMethod : Generic failure
At C:\Users\mysol\OneDrive\Desktop\scan-atkacpi.ps1:5 char:20
+ ...  $result = (Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -Cl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (AsusAtkWmi_WMNB...PNP0C14\ATK_0"):CimInstance) [Invoke-CimMethod], CimExc
    eption
    + FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand

110025 : ffff0000 (-65536)
110026 : ffffffffffff0000 (-65536)
110027 : ffffffffffff0000 (-65536)
120057 : 80000 (524288)
120061 : 1 (1)
12006c : 1 (1)
120075 : 3 (3)
120079 : 426 (1062)
12007a : 0 (0)
120093 : 73 (115)
120094 : 33 (51)
120095 : 4 (4)
120096 : 0 (0)
120097 : 23 (35)
1200a0 : 0 (0)
1200a1 : 0 (0)
1200a2 : 0 (0)
1200a3 : 0 (0)
130021 : 2 (2)
130022 : 0 (0)
```

Method #2 output:
[dsdt.dsl.zip](https://github.com/user-attachments/files/18052287/dsdt.dsl.zip)

**Comment by seerge** [comment]
@edxeth ok, thanks.

It's quite strange, cause Screenpad endpoints seem to be same as for other models.

https://github.com/seerge/g-helper/blob/d7202b12bf2ae4773810324dbb1b364e799a121f/app/AsusACPI.cs#L130C49-L130C54

I.e. ``0x00050032`` is ScreenPad brightness. 

And it also exists in DSDT dump
```
                    If ((IIA0 == 0x00050032))
                    {
                        TMBF [One] = IIA1 /* \_SB_.ATKD.WMNB.IIA1 */
                        TMBF [Zero] = One
                        Return (^^PCI0.SBRG.EC0.WEBC (0x1A, 0x02, TMBF))
                        Return (Zero)
                    }
```

May be just values are different (i.e. 255 can't be set ?)

Can you try to lower brightness with Shift + FN + F7 down to lowest amounts (like 0% or 10% ?), and double check app log, it should say something like  ?

```
Screenpad = 4 : OK
```

**Comment by edxeth** [comment]
@seerge I was able to get FN + SHIFT + F7/F8 to work with my laptop's keyboard. Apparently my issue it's caused by the external keyboard Keychron Q1 Pro (mapped via [VIA](https://usevia.app/) an open source tool for programming and customizing the keymap). FN + F1 and so on work but as soon as I try pressing SHIFT + FN + <SomeKey> or binding FN + V to Screenpad Brightness Up/Down the keyboard isn't able to execute the action. I don't know why, FN works for everything else lol!
This could be worked around with a screenpad brightness slider in GHelper for people in my situation who use external keyboards. It still begs the question whether the external keyboards are able to leverage such combination of keys or the issue is strictly isolated to my case(?).

**Comment by seerge** [comment]
@edxeth 

External keyboards (especially from other brands!) obviously won't work for any FN+ combinations, as internal keyboard emit a special keycode that is being processed.

Do I understand that everything works as it should for you ?

**Comment by edxeth** [comment]
@seerge gotcha, thanks anyways. Amazing app, I'll donate soon!

**Comment by seerge** [comment]
@edxeth ok, great, thanks. Closing as resolved then
