### ISSUE TITLE
Not Supported Issues.

### ISSUE THREAD

**Issue by Yograt** [seerge/g-helper#3403]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![image](https://github.com/user-attachments/assets/b38e116c-eadb-4968-9635-02b13d0de1a7)
Hello, I recently tried this project and when i try to adjust the fan and then click apply it says it doesn't support it, is this an issue I am supposed to be worried about?

Device: ASUS ZenBook Pro 14 OLED (UX6404VI)

### How to reproduce the bug?

1. Open G Helper
2. Fans + Power option
3. Apply fan curves
4. See Error

### Logs

[log.txt](https://github.com/user-attachments/files/17892245/log.txt)

### Device and Model

ASUS ZenBook Pro 14 OLED, UX6404VI

### Additional information.

![image](https://github.com/user-attachments/assets/0e5208e5-a96f-4f75-9c6f-471cad06f725)

### Armoury Crate

Never installed

### Asus Services

6

### Version

0.199.0

### OS

Windows 11 Pro 24H2

**Comment by seerge** [comment]
@Yograt hello, it’s normal cause your device doesn’t support custom fan curves as you never had them in MyAsus or any othet asus app.

If you really want a custom fan behaviour you can try experimental build with a manual fan control 

https://github.com/seerge/g-helper/discussions/2272

Thanks

**Comment by Yograt** [comment]
Got it ty
