### ISSUE TITLE
Increase GPU Memory Clock Offset Limit from 500Mhz to 1000Mhz or more.

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [seerge/g-helper#3405]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Nop, just because the 500Mhz limit now was a little bit inconvenient, I need to open MSI Afterburner to overclock.

### Describe the solution you'd like

Just raise the limit.

### Device and Model

ASUS TUF Gaming F16 FX607JV

### Additional information.

![image](https://github.com/user-attachments/assets/298ba53f-cf7b-4f62-bbd1-60ecb1070c81)

**Comment by seerge** [comment]
@Shiroiame-Kusu hello, it’s already possible. Please check how https://github.com/seerge/g-helper/wiki/Power-user-settings#higher-maximum-and-minimum-gpu-clock--memory-offsets

Thanks
