### ISSUE TITLE
Suggestion for Optimizing Silent Mode and GPU Performance with USB-C Adapters

### ISSUE THREAD

**Issue by Jo4o20** [seerge/g-helper#3407]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Yes, the feature request addresses a problem related to GPU performance when using a USB-C power adapter. Without automatically enabling WhisperMode in the NVIDIA Control Panel when Silent Mode is activated in Armory Crate, the GPU’s power and clock speeds drop significantly. This makes the laptop nearly unusable in this configuration, particularly with a 65W USB-C adapter.

### Describe the solution you'd like

I would like an option added to the "Others" section in G-Helper to automatically enable WhisperMode in the NVIDIA Control Panel whenever Silent Mode is activated. This integration would ensure stable GPU performance and clock speeds, especially when using lower-power USB-C adapters like a 65W charger.

### Describe alternatives you've considered

I believe there could also be a dedicated mode for USB-C charging, where these features would be enabled by default, or at least an option to activate them automatically.

### Device and Model

Asus Tuf Dash F15 FX516PM

### Additional information.

![image](https://github.com/user-attachments/assets/fca7fb32-96ad-4525-8abb-be8bd6203476)
![image](https://github.com/user-attachments/assets/46a8653d-c71f-47a0-8b82-7d0078ddf128)

**Comment by seerge** [comment]
@Jo4o20 hello, there is no Nvidia API to enable Whisper mode unfortunately, so it’s simply impossible. 

You can try to create a separate Mode in the app and limit GPU clocks there, it can restrict GPU power and have a similar effect to Whisper mode.

**Comment by Jo4o20** [comment]
Every modern laptop can automatically switch between battery power and the AC adapter if the adapter provides sufficient power. In my case, when the laptop is in Silent Mode with WhisperMode enabled, it consumes less than the 65W provided by my USB-C adapter. I only use the original charger when I’m at home, in my stationary setup, because when I need to take the laptop with me, it’s inconvenient to carry multiple chargers for all my devices.  

Additionally, 100W chargers are very expensive in my region, and they’ve only recently started to become more affordable. I plan to upgrade to one in the future.

**Comment by seerge** [comment]
@Jo4o20 well, in generally it's quite strange that only WhisperMode (de-facto 60FPS limit) helps you. I would say it's rather some underlying hardware/firmware/driver issue on the device cause it should not crash anyway, even if power supply is USB-C :)

But as I have mentioned, there is no known to me API to control WhisperMode , so I can't add it even if I would want to. So I can't do much here.

Thanks.
