### ISSUE TITLE
[Bug] Cropped UI items

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#341]
Well, there are cropped items:
![image](https://user-images.githubusercontent.com/8934421/236961607-9bbb12a9-e214-4789-b9a7-fba3c9be1652.png)
Maybe, there are some auto-size available for those containers, so they will contain their stuff better.
Thanks!

**Comment by seerge** [comment]
@ke1ne hello, should be fixed in https://github.com/seerge/g-helper/releases/tag/v0.59
