### ISSUE TITLE
Monitor response times higher with Basic lighting effects compared to Aura Sync with Performance mode

### ISSUE THREAD

**Issue by XzRaiderzX** [seerge/g-helper#3410]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Not exactly sure if this is a bug or a feature request, as it's a very bizarre find. I was in Armoury Crate testing the Aura Sync performance mode, I only noticed latency benefits when specifically using it in combination with Aura Sync effects and not Basic effects.
My monitor response time is almost instant going down to "Lite" from "Ultra Smooth" (Response time is the same as "Smooth" if Performance mode is off) even though I was switching between the exact same Rainbow effect, just one was in the Basic effects and one was in Aura Sync effects. 
G-Helper has the same latency as using Basic effects in Armoury Crate. 
Setting the Aura Performance mode to Lite with G-Helper and AC services stopped makes the keyboard flash constantly seemingly under fluctuating CPU load.

### Describe the solution you'd like

Hopefully somehow, someway manage to integrate the latency benefits of "Aura Performance mode" since I doubt anyone using G-Helper is using Aura Sync. 

### Describe alternatives you've considered

Alternatively maybe just a way to turn off the G-Helper lighting override, since the Aura Sync effect you choose is hard locked and can't be changed with G-Helper afterwards.

### Device and Model

ROG G17PV

### Additional information.

I've made a bug report on the ROG forum about it, but it's not a guarantee it will help with G-Helper.

**Comment by seerge** [comment]
@XzRaiderzX hello, I didn’t completely get what you mean.

G-Helper is not able to interact and is not interacting with Armoury or AuraSync apps anyhow.

It can only change backlight colors for your internal keyboard, not for monitor.

What exact backlight mode are you using?

**Comment by XzRaiderzX** [comment]
Yea I understand it's only for peripherals, I should have been clearer with my language.
The backlight mode I'm using in G-Helper is Rainbow with Normal speed. 
If I go to Armoury Crate, I can get lower system latency/ input lag if I set the exact same lighting effect through Aura Sync with Aura Performance mode to Lite. The "Basic effects" aren't effected by the performance mode. 

![Desktop Screenshot 2024 11 28 - 10 20 59 98](https://github.com/user-attachments/assets/1a321372-3fb5-4863-ba94-a8d5e1b26687)
![Desktop Screenshot 2024 11 28 - 10 33 18 85](https://github.com/user-attachments/assets/ed930f92-889c-4faf-9ee4-7e5f22dde5bb)

G-Helper has higher latency like with "Basic effects".
If I keep the Aura Sync settings with Armoury Crate closed and then use G-Helper, they conflict with one another. The backlight mode is Hardlocked and briefly flashes if I attempt to change it through G-Helper, there's no latency benefits either, like with "Basic effects".
I tested with The Finals and NFS Unbound, very CPU intensive games and the differences were most apparent there.

**Comment by seerge** [comment]
@XzRaiderzX what “latency” are you talking about, how do you measure it?

Backlight modes are controlled by firmware, you just set them one and they keep running. They have nothing to do with input latency.

**Comment by XzRaiderzX** [comment]
I don't have proper latency testing tools, but I measured it like this: a 240 FPS video of NFS Heat with an external keyboard that lights up keystrokes. I bound "Look back" to Space and rhythmically pressed as soon as I saw the in-game camera change. In the video the gap between a keystroke and the image changing is shorter.

I'm not sure then why the input latency is lower if you say it's entirely firmware bound. My best guess was that the performance mode changes the sampling rate of the backlight or something since they also mention smoothness and responsiveness.

**Comment by seerge** [comment]
@XzRaiderzX hello,

1. Backlight has absolutely nothing to do with input latency
2. External keyboard is not affected or controlled by G-Helper anyhow
3. Aura “performance” setting in AC does not affect latency either, it’s again only about how fast AC will change keyboard colors based on selected Aura mode (for example when color reflects screen contents), it does not impact “default” backlight animations as they are just hardcoded into firmware.

If you by some reason want to use AC to control backlight- you are free to do so. Just don’t change it in G-Helper afterwards – and it won’t be overridden.

You can completely disable backlight init command in G-Helper on app start by adding a config parameter as explained here:

https://github.com/seerge/g-helper/wiki/Power-user-settings#skip-keyboard-aura-initialisation-on-startup

Thanks!

**Comment by XzRaiderzX** [comment]
Yea I know that the external keyboard isn't affected by G-Helper, it was just a way to make sure it wasn't a placebo effect on my end. Either way thank you for the skip command, seems to do the trick as I don't intend to use anything else but the rainbow lighting.
