### ISSUE TITLE
Optimized Mode Cannot change screen brightness

### ISSUE THREAD

**Issue by Mahdi-zarei** [seerge/g-helper#3412]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Unless when turning off the system charger was on ( and thus, the GPU), I will not be able to change the brightness of the screen when I plug in the charger again. The brightness module does show that it is changing but nothing happens. If the charger is not plugged in and GPU is off, brightness does work. The attached log starts when I turn on my laptop and brightness does not work, then i plug in the charger, restart the laptop, and it starts working.

### How to reproduce the bug?

set GPU mode to optimized
turn off the pc when charger is not plugged in
turn on the pc
plug in the charger after system is up
try to change the brightness

### Logs

11/26/2024 6:57:21 PM: ------------
11/26/2024 6:57:29 PM: App launched: ROG Strix G18 G814JVR_G814JVR :0.197.0.0en-US.
11/26/2024 6:57:29 PM: Start Count: 73
11/26/2024 6:57:30 PM: Matrix control device was not found on your machine.
11/26/2024 6:57:30 PM: C:\ProgramData\ASUS\GameVisual\ASUS_DCIP3.icm DCIP3
11/26/2024 6:57:30 PM: C:\ProgramData\ASUS\GameVisual\ASUS_DisplayP3.icm DisplayP3
11/26/2024 6:57:30 PM: C:\ProgramData\ASUS\GameVisual\ASUS_sRGB.icm sRGB
11/26/2024 6:57:30 PM: Unable to load DLL 'atiadlxx.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
11/26/2024 6:57:30 PM: dGPU not found
11/26/2024 6:57:32 PM: CPU: -1 - Intel(R) Core(TM) i9-14900HX - Intel64 Family 6 Model 183 Stepping 1
11/26/2024 6:57:32 PM: AutoSetting for Online
11/26/2024 6:57:32 PM: BatteryLimit = 100 : OK
11/26/2024 6:57:32 PM: Mode = 0 : OK
11/26/2024 6:57:32 PM: Input available: \\?\hid#vid_0b05&pid_19b6&mi_00&col03#7&8bfce01&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 64
11/26/2024 6:57:32 PM: Init 19B6: 5D-B9
11/26/2024 6:57:32 PM: USB 19B6|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
11/26/2024 6:57:32 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
11/26/2024 6:57:32 PM: Input: \\?\hid#vid_0b05&pid_19b6&mi_00&col03#7&8bfce01&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
11/26/2024 6:57:32 PM: Init 19B6: 5D-05-20-31-00-1A
11/26/2024 6:57:32 PM: USB 19B6: 5D-BD-01-AA-1A-00-00-FF
11/26/2024 6:57:32 PM: AuraMode: AuraStatic
11/26/2024 6:57:32 PM: USB 19B6: 5D-B3-00-00-00-80-00-EB-00-00-FF-FF-FF-00-00-00-00
11/26/2024 6:57:32 PM: USB 19B6: 5D-B5-00-00-00
11/26/2024 6:57:32 PM: USB 19B6: 5D-B4
11/26/2024 6:57:32 PM: GPUEco = 0 : OK
11/26/2024 6:57:33 PM: Auto 19B6: 5D-BA-C5-C4-01
11/26/2024 6:57:34 PM: Monitor Power On
11/26/2024 6:57:36 PM: BatteryLimit = 100 : OK
11/26/2024 6:57:36 PM: Lid Open
11/26/2024 6:57:36 PM: Lid 19B6: 5D-BA-C5-C4-01
11/26/2024 6:57:36 PM: Eco flag : 0
11/26/2024 6:57:36 PM: Mux flag : 1
11/26/2024 6:57:36 PM: \\?\DISPLAY#BOE0C64#4&1a3faec7&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
11/26/2024 6:57:36 PM: \\?\DISPLAY#BOE0C64#4&1a3faec7&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
11/26/2024 6:57:36 PM: ScreenOverdrive = 0 : OK
11/26/2024 6:57:36 PM: NE180QDM-NZ4 HDR: False 8 5 True
11/26/2024 6:57:36 PM: Display configuration changed.
11/26/2024 6:57:37 PM: HID Device Event: Checking for new ASUS Mice
11/26/2024 6:57:39 PM: NVIDIA GeForce RTX 4060 Laptop GPU
11/26/2024 6:57:39 PM: HID Device Event: Checking for new ASUS Mice
11/26/2024 6:57:49 PM: Key: 16
11/26/2024 6:57:49 PM: Brightness = 16 : 0
11/26/2024 6:57:50 PM: Key: 16
11/26/2024 6:57:50 PM: Brightness = 16 : 0
11/26/2024 6:57:50 PM: Key: 16
11/26/2024 6:57:50 PM: Brightness = 16 : 0
11/26/2024 6:57:50 PM: Key: 16
11/26/2024 6:57:50 PM: Brightness = 16 : 0
11/26/2024 6:57:50 PM: Key: 16
11/26/2024 6:57:50 PM: Brightness = 16 : 0
11/26/2024 6:57:53 PM: BatteryLimit = 100 : OK
11/26/2024 6:58:34 PM: ------------
11/26/2024 6:58:38 PM: App launched: ROG Strix G18 G814JVR_G814JVR :0.197.0.0en-US.
11/26/2024 6:58:38 PM: Start Count: 74
11/26/2024 6:58:40 PM: Matrix control device was not found on your machine.
11/26/2024 6:58:41 PM: C:\ProgramData\ASUS\GameVisual\ASUS_DCIP3.icm DCIP3
11/26/2024 6:58:41 PM: C:\ProgramData\ASUS\GameVisual\ASUS_DisplayP3.icm DisplayP3
11/26/2024 6:58:41 PM: C:\ProgramData\ASUS\GameVisual\ASUS_sRGB.icm sRGB
11/26/2024 6:58:41 PM: NVIDIA GeForce RTX 4060 Laptop GPU
11/26/2024 6:58:42 PM: CPU: -1 - Intel(R) Core(TM) i9-14900HX - Intel64 Family 6 Model 183 Stepping 1
11/26/2024 6:58:42 PM: AutoSetting for Online
11/26/2024 6:58:42 PM: BatteryLimit = 100 : OK
11/26/2024 6:58:42 PM: Input available: \\?\hid#vid_0b05&pid_19b6&mi_00&col03#7&8bfce01&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030} 19B6 64
11/26/2024 6:58:42 PM: Eco flag : 0
11/26/2024 6:58:42 PM: USB 19B6|64: 5A-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
11/26/2024 6:58:42 PM: Input: \\?\hid#vid_0b05&pid_19b6&mi_00&col03#7&8bfce01&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
11/26/2024 6:58:42 PM: \\?\DISPLAY#BOE0C64#4&1a3faec7&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
11/26/2024 6:58:42 PM: \\?\DISPLAY#BOE0C64#4&1a3faec7&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
11/26/2024 6:58:42 PM: ScreenOverdrive = 0 : OK
11/26/2024 6:58:42 PM: NE180QDM-NZ4 HDR: False 8 5 True
11/26/2024 6:58:42 PM: Mode = 0 : OK
11/26/2024 6:58:42 PM: Init 19B6: 5D-B9
11/26/2024 6:58:42 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
11/26/2024 6:58:42 PM: Init 19B6: 5D-05-20-31-00-1A
11/26/2024 6:58:42 PM: USB 19B6: 5D-BD-01-AA-1A-00-00-FF
11/26/2024 6:58:42 PM: AuraMode: AuraStatic
11/26/2024 6:58:42 PM: USB 19B6: 5D-B3-00-00-00-80-00-EB-00-00-FF-FF-FF-00-00-00-00
11/26/2024 6:58:42 PM: USB 19B6: 5D-B5-00-00-00
11/26/2024 6:58:42 PM: USB 19B6: 5D-B4
11/26/2024 6:58:43 PM: Monitor Power On
11/26/2024 6:58:43 PM: BatteryLimit = 100 : OK
11/26/2024 6:58:43 PM: Lid Open
11/26/2024 6:58:43 PM: Lid 19B6: 5D-BA-C5-C4-01
11/26/2024 6:58:43 PM: Auto 19B6: 5D-BA-C5-C4-01
11/26/2024 6:59:26 PM: NE180QDM-NZ4 HDR: False 8 5 True
11/26/2024 6:59:28 PM: Latest version 0.197.0.0
11/26/2024 6:59:28 PM: \\?\DISPLAY#BOE0C64#4&1a3faec7&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
11/26/2024 6:59:28 PM: \\?\DISPLAY#BOE0C64#4&1a3faec7&0&UID8388688#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
11/26/2024 6:59:29 PM: Screen = 240Hz : OK
11/26/2024 6:59:29 PM: ScreenOverdrive = 1 : OK
11/26/2024 6:59:29 PM: NE180QDM-NZ4 HDR: False 8 5 True
11/26/2024 6:59:29 PM: Display configuration changed.
11/26/2024 6:59:29 PM: NE180QDM-NZ4 HDR: False 8 5 True
11/26/2024 6:59:31 PM: Key: 32
11/26/2024 6:59:31 PM: Brightness = 32 : 0
11/26/2024 6:59:32 PM: Key: 32
11/26/2024 6:59:32 PM: Brightness = 32 : 0
11/26/2024 6:59:32 PM: Key: 32
11/26/2024 6:59:32 PM: Brightness = 32 : 0
11/26/2024 6:59:33 PM: Key: 16
11/26/2024 6:59:33 PM: Brightness = 16 : 0
11/26/2024 6:59:33 PM: Key: 32
11/26/2024 6:59:33 PM: Brightness = 32 : 0

### Device and Model

Rox Strix G18 G814JVR

### Additional information.

If the system has charger plugged in and it is turned off, everything works as expected when i turn it on, whether with charger plugged in when starting or plugging it in later. So I assume there is a misconfiguration when the laptop shuts down with GPU disabled and does not properly detect it for brightness. I also did have this exact same problem with an updated armory crate.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.197.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Mahdi-zarei hello, 

just make sure to check “Enable GPU on shutdown” under Extra as explained here https://github.com/seerge/g-helper/discussions/1042

Thanks

**Comment by Mahdi-zarei** [comment]
Will do that. Thanks for your quick response and the great app!
