### ISSUE TITLE
xg mobile light on-off

### ISSUE THREAD

**Issue by Als5rh** [seerge/g-helper#3416]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I wan to turn on-off xg mobile light 

### Describe the solution you'd like

add a button for xg mobile light 

### Device and Model

Asus ROG Flow Z 13 GZ301ZE

**Comment by seerge** [comment]
@Als5rh hello, it already exists under Extra settings. Thanks
