### ISSUE TITLE
Undervolting

### ISSUE THREAD

**Issue by Oblivon23** [seerge/g-helper#3419]
What does memory offset do?
Do you need the igpu to be off while undervolting the dgpu?

Is it possible to do individual core undervolting rather than all the cores?

**Comment by seerge** [comment]
@Oblivon23 memory clock offset - increases or decreases dGPU default memory clock on a given value. 

You can’t disable iGPU and it doesn’t have to be off to adjust memory clocks for dGPU

Thanks
