### ISSUE TITLE
Displays incorrect model of asus laptop

### ISSUE THREAD

**Issue by Leonnn22** [seerge/g-helper#3421]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I am loving G-Helper so far but i notieced that on the top of the G Helper app window, the incorrect model of the laptop is shown. I have Asus ROG M16, however within G Helpler if shows Asus G16. I checked online and both model seem to have pretty different specifications, leading me to bealieve that if G helper has the model of my laptop mixed up, it might also cause performance instability or issues. Also, when I checked the system information on windows 11 laptop, it also displays that i have a G16. So its not only on G Helper that this issue occurs. Please find attached below of the issue. 
![image](https://github.com/user-attachments/assets/4275f551-dfd5-4767-b977-943462e938db)

### How to reproduce the bug?

Open G helper

### Logs

?

### Device and Model

Asus Zephyrus M16

### Armoury Crate

Installed

### Asus Services

0

### Version

0.197

### OS

windows 11 23H2

**Comment by seerge** [comment]
@Leonnn22 hello, model name is taken from windows. You can verify that by opening windows Settings and looking at your model there.

GU603VV is G16 tho according to Asus site
https://rog.asus.com/hk-en/laptops/rog-zephyrus/rog-zephyrus-g16-2023-series/spec/

Thanks
