### ISSUE TITLE
Switching from Standard to Eco Causing a black screen - Rog Zephyrus G14

### ISSUE THREAD

**Issue by AbiramSarvananthan** [seerge/g-helper#3422]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When switching from standard to eco, a black screen occurs flickering two times. Once the screen comes back on, the taskbar is missing and only the apps that are still open remain. If you exit out of all the open apps you end up at black screen, with 4 rectangles in the bottom left corner. You cannot do anything else but if you do Ctrl + Alt + del you are brought to a pop up with sign out options.

### How to reproduce the bug?

1. Occurs almost everytime after you take it off of charge.
2. (Maybe sometimes after setting balanced to silent)
3. Go to Ghelper and set GPU mode from standard to eco

### Logs

[log.txt](https://github.com/user-attachments/files/17964438/log.txt)

### Device and Model

ROG Zephyrus G14 GA403UV

### Additional information.

When you press CTRL + ALT + DEL in the black screen, the windows loading animation pops up with something along the lines of preparing security, although goes away immediately.

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.197.0

### OS

Newest windows 11

**Comment by seerge** [comment]
@AbiramSarvananthan hello, 

It looks more like a windows or nvidia driver misbehaviour.

Can you check what Display Mode do you have under Nvidia Control panel? And change it to Optimus there.

If it doesn’t help - try to do a fresh install of the latest GPU drivers from Nvidia website directly? and check Reset to factory defaults during installation.

Thanks

**Comment by AbiramSarvananthan** [comment]
Right now I have it to automatic select? I just change that to optimus?

**Comment by seerge** [comment]
@AbiramSarvananthan yes, try that

**Comment by iyad08** [comment]
Same happens here on a 2024 G16. It only started happening after updating to 24H2 and updating the intel graphics drivers (not the nvidia ones).

I will note that i used to very rarely have bluescreens when a change occurs to the graphics but since the update i haven't had any.

**Comment by seerge** [comment]
@AbiramSarvananthan any updates here?

**Comment by AbiramSarvananthan** [comment]
Hi, sorry. As of now I have not encountered the problem again after switching to Optimus.

**Comment by Edelwis** [comment]
> Те саме відбувається на G16 2024 року. Це почало відбуватися лише після оновлення до 24H2 та оновлення графічних драйверів intel (а не nvidia).
> 
> Зазначу, що колись у мене дуже рідко з’являлися сині екрани, коли відбувалася зміна графіки, але після оновлення у мене їх не було.

I have the same thing. After the update 24H2, a black screen started appearing for a few seconds when I switch the video card from standard mode to eco.

**Comment by seerge** [comment]
@AbiramSarvananthan 

> Hi, sorry. As of now I have not encountered the problem again after switching to Optimus.

Then we have an answer. Most likely it’s some recent changes in windows or GPU drivers that don’t like when Nvidia Display mode is driving display with dGPU.

My advice would be to ensure that you either have Optimus selected or Auto, but display is driven by iGPU (which is same as Optimus)

As I remember AC also tells you to do that.

**Comment by seerge** [comment]
@Edelwis @iyad08 same advice to you, make sure you have Nvidia Display mode set to Optimus (or Auto but it uses iGPU to drive display). 

This is most likely some resent changes in nvidia drives / windows, as from my observations even when you were on nvidia GPU only mode in nvidia settings - switching is working just fine. But since AC "recommends" to set Optimus prior to disable dGPU - it's better to do it like that :)

**Comment by seerge** [comment]
@5aumit it's not the same issue, if mouse cursor is visible - your GPU and display is good :) 

It's just something wrong with the way windows manages multiple displays. Try to open Settings -> Dispay and re-arrange displays positition while you have multiple screens connected.

**Comment by seerge** [comment]
@5aumit yes, it looks like when you disconnected second display windows just acts and doesn't re-arrange it's only one left :) So you see second one still (without taskbar) and a mouse cursor over it.

May be just rearranging displays, or chaning extend / mirror setting back and forward can help it somehow :)
