### ISSUE TITLE
auto brighntness toggle

### ISSUE THREAD

**Issue by AshishKalkandha** [seerge/g-helper#3430]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Screens brighness keep changing on based on content on display. brightness increases on white content and dim on black or dark content. no auto brightness option found on display setting on windows settings [zephrus g16] (2024)

### Describe the solution you'd like

An auto brightness toggle can be added to g-helper app

### Describe alternatives you've considered

or any other way to changes the option. brightness changing like this is irritating and feels bad for eyes.

### Device and Model

Asus Zephyrus G16 (2024)

### Additional information.

GU605MI

**Comment by seerge** [comment]
@AshishKalkandha hello,

It must be turned on in Windows somewhere still, check for the checkbox deeper, or it could be some weird setting inn GPU driver control panel. For example under Intel Command center (or how it’s called correctly), so check there.

G-Helper is not a driver and is not analysing screen contents to adjust brightness :)

Thanks

**Comment by AshishKalkandha** [comment]
it's happening after  I uninstalled armory crate and installed g-helper. before that screen brightness was working fine(normal).
installing armoury crate fixed the issue. that's why i think g-helper should also have that feature. 
keeping both software isn't recommended, right?

![Screenshot 2024-12-03 113254](https://github.com/user-attachments/assets/c1504d53-0abb-4c6e-9628-f2243ad14a8f)
what does this slider do? (please explain)

![Screenshot 2024-12-03 115419](https://github.com/user-attachments/assets/02edb16c-bfcb-407d-9dc9-ecbf9922aa92)
and what is this option in armoury crate??

**Comment by AshishKalkandha** [comment]
> @AshishKalkandha hello,
> 
> Flicker free dimming is not Auto brightness, it’s what you have under OLED settings in AC too.
> 
> As for that “Optimal Display Brightness”, what exactly does it do in AC? Does turning it off - stops auto brightness changes? If so - did you use official AC uninstaller app when removing AC? (i want to understand if it’s either just AC leftover that was changing brightness for you or is it some new hardware-toggle)

I don't have OLED Screen, it's IPS. I have Ultron 9, 32GB RAM and rtx 4070 with IPS display. 
And I don't know about AC or what it's full form or meaning. 
Is it a software or some feature/section in g-helper/armoury Crate. 

I can share more information about my hardware or software if it can help to improve the software. 

FYI: I reinstalled the Armoury Crate just to take a screenshot of that displays related option but just after installation that auto brightness stopped without changing any setting or option.

**Comment by RPochyly** [comment]
Hello @seerge
After troubleshooting for hours, I can confirm that disabling the adaptive contrast setting (referred to as "Optimal Display Brightness" in AC) is the only solution that works. 

I tried looking in Windows settings for "Change brightness based on content" setting, as mentioned on the [official ASUS support website](https://www.asus.com/support/faq/1053120/), but the option is completely missing.

I also tried searching AMD Software and NVIDIA app for similar settings. AMD has recently removed the Varibright option from their software because of the toggle in Windows settings mentioned earlier. Even after modifying the registry keys for Varibright, the adaptive contrast from ASUS was still active. 

The last thing I tried was using Linux to check if the adaptive contrast still works there. I tested various kernel parameters to disable varibright and even after uninstalling the mesa drivers, the adaptive contrast was still active, even in TTY in a minimal environment.

After all this troubleshooting, I'm fairly certain that the adaptive contrast ASUS uses isn't implemented in Windows, AMD drivers or NVIDIA drivers (Varibright setting does absolutely nothing even with the NVIDIA GPU disabled). I'm not too knowledgeable about how laptops work but I suspect that ASUS uses some kind of display controller chip for adaptive contrast. The chip appears to be controllable only via the AC setting - which could explain the missing Windows setting.

My model: ASUS A16 FA608WI
GPUs: AMD Radeon 890M and RTX 4070
CPU: Ryzen AI 9 HX 370

If you could add the Optimal Display Brightness setting to G-Helper, I would gladly donate 10€. As a computer science student, having the entire screen dim when I open an IDE with dark mode is a huge inconvenience and having this option in G-Helper would greatly improve my experience.

Merry Christmas, and thank you for your work on G-Helper!

**Comment by seerge** [comment]
@RPochyly @AshishKalkandha hello,

Most likely it's one more and new proprietary toggle that Asus has added (introduced only for latest devices, released mid-2024).

To discover endpoint responsible for this toggle I need help from someone who actually has device with it. What needs to be done.

1. Quit app and add following line to the beginning of `%appdata%\GHelper\config.json`, then save it and start app again.
```
"debug": 1,
````
2. Run app again, open `Extra` settings and click on a new `Zoom-glass` icon there, it will do endpoint scan
3. Change `Optimal Display Brightness` setting in AC to the opposite
4. Run scan under `Extra` again
5. Upload scan result here.

Also make a DSDT dump as explained [in this topic (method2)](https://github.com/seerge/g-helper/issues/38)

Thanks

**Comment by seerge** [comment]
@RPochyly ok, great!

Seems like `0005002A` endpoint has changed from 1 to 0.

Can you now open `Extra` settings and into new `DEVS` section there enter `5002A` in first field  and 1 / 0 into second. This would manually send a command.

And check if it indeed enables and disables Auto Brightness ?

**Comment by RPochyly** [comment]
Yes, it works! Setting `5002A` to `1` enables `Optimal Display Brightness` and setting it to `0` disables it. The smooth transition (of increasing/decreasing brightness while toggling ODB) which takes about 5 seconds is exactly the same as with AC.

**Comment by seerge** [comment]
@RPochyly great! Good news.

Try this build, I have added an `Optimal Display Brightness` checkbox to `Extra` settings (where app keeps rarely used stuff)
[GHelper.zip](https://github.com/user-attachments/files/18230952/GHelper.zip)

And quick question. Do I understand correctly that device remembers this settings even after reboots or shutdowns ? I.e. there is no need to "set" it manually on each start?

**Comment by RPochyly** [comment]
The toggle works! I think the device remembers the setting.
I restarted and the Optimal Display Brightness wasn't turned on (it was also disabled before the restart). Then I shut down the laptop and waited 15 minutes to (hopefully) clear the volatile memory of the display controller as I have no idea where this setting is stored. After about 15 minutes of being shut down, the ODB was still disabled, which means that the setting should be persistent.

Thank you for your help! By the way, when do you approximately expect this feature to be added to stable releases?

**Comment by seerge** [comment]
@RPochyly great, thanks for help and discovery.

It will be live in the next release. But since I just pushed 0.200, it will take some time as I usually try to accumulate a bunch of changes together unless this is something very important :)

**Comment by RPochyly** [comment]
Of course, I understand that. I'm glad that I could help. I've already sent you a donation for your kind help.

Anyway, have a wonderful Christmas!

**Comment by seerge** [comment]
@RPochyly thanks, same to you.

**Comment by RPochyly** [comment]
After further testing, it seems that the Optimal Display Brightness setting resets to "enabled" after about two hours of the laptop being shut down. So the setting is not persistent after all, it just takes quite a bit of time to reset to it's default value.

**Comment by seerge** [comment]
@RPochyly do you still have AC or leftovers running ? (mainly Armoury Crate service)

**Comment by RPochyly** [comment]
No, I uninstalled it (official installer) after you had sent me the build of GHelper with the ODB toggle. I have no other features that I would use in AC, so I decided to uninstall it. I've just checked installed programs (using control panel) and there isn't anything AC related. I still have a few ASUS services (most of them stopped) for MyASUS I think. Do you think that these would cause the setting to revert to enabled?   ![image](https://github.com/user-attachments/assets/f3513f50-cd87-4f4c-97c2-397d34c5499c)

**Comment by seerge** [comment]
@RPochyly my thought was that something else has enabled it back :) may be try to stop all other services and see if it resets back to ON? btw when it does - does checkbox under `Extra` reflect it ?

**Comment by RPochyly** [comment]
Yes, it seems to reset with all ASUS services stopped. I even tried Linux which I think has no ASUS services that could interfere and although I had no way to 100% sure, the dimming based on display content was turned on. I am certain that I disabled ODB before shutting down the laptop for several hours before booting to Linux.

Also yes, the checkbox under `Extra` reflects it correctly.

**Comment by seerge** [comment]
@RPochyly ok, try this build. It should also set last used Optimal Brightness status on app start.

[GHelper.zip](https://github.com/user-attachments/files/18254271/GHelper.zip)

**Comment by RPochyly** [comment]
After having the laptop shut down overnight, the new build correctly sets the previous setting (ODB off in this case).
I think that everything concerning Optimal Display Brightness works great as of this build.

**Comment by injkgz** [comment]
![Image](https://github.com/user-attachments/assets/0069827e-e640-4d8b-9d26-9cfe1bb53692)
Hi! @seerge why I don't have this feature?

**Comment by Emile86** [comment]
> ![Image](https://github.com/user-attachments/assets/0069827e-e640-4d8b-9d26-9cfe1bb53692) Hi! [@seerge](https://github.com/seerge) why I don't have this feature? I'm g16 2024 intel core ultra 7 155 h owner

Same here with G16 2024 core ultra 9 and Oled screen

**Comment by seerge** [comment]
@injkgz @Emile86 hello, if you don't see that option - your device does not support it. Asus has added it only for Mid 2024+ models (i.e. G16 with AMD CPU and some new TUF models)
