### ISSUE TITLE
M4 key biding missing

### ISSUE THREAD

**Issue by george971986** [seerge/g-helper#3431]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![M4](https://github.com/user-attachments/assets/b900f1c1-a4f0-4abc-b3ec-80f6b170af1c)

### How to reproduce the bug?

Extra - key bidings

### Logs

[log.txt](https://github.com/user-attachments/files/17981630/log.txt)

### Device and Model

ROG Strix SCAR 18 G834JZR

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.197.0

### OS

Windows 11 24H2

**Comment by seerge** [comment]
@george971986 hello,

I was answering this multiple times already https://github.com/seerge/g-helper/issues/2022 https://github.com/seerge/g-helper/issues/2157

M4 and Fn+F5 emit same keycode on Strix devices. This key is reserved for toggling profiles forward, and Shift + Fn + F5 for toggling profiles backwards.

So It won't be bindable under Extra :)

Thanks
