### ISSUE TITLE
Option to not change CPU mode on charger mode change

### ISSUE THREAD

**Issue by Matszwe02** [seerge/g-helper#3432]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I want to change CPU power modes, then when I plug in or unplug my charger, I need to re-do the same thing. Also disabling the turbo power mode needs to be made twice - once for charger, once for battery operation

### Describe the solution you'd like

Just add a checkbox "disable mode change on charger" or something, to merge both battery and ac power modes.
Users that want to have different modes will just remain with that feature by default, but somebody that only changes to turbo when something heavy is running don't need to ensure it's still turbo on battery as well as on charger.

### Device and Model

TUF F15

**Comment by seerge** [comment]
@Matszwe02 hello, it’s already possible.

Check Power User settings on how to do that
https://github.com/seerge/g-helper/wiki/Power-user-settings#disable-mode-switching-on-plugged-in--unplugged-events

Thanks

**Comment by Matszwe02** [comment]
> @Matszwe02 hello, it’s already possible.
> 
> Check Power User settings on how to do that https://github.com/seerge/g-helper/wiki/Power-user-settings#disable-mode-switching-on-plugged-in--unplugged-events
> 
> Thanks

Thanks! Any plans to moving it from json to main menu?

**Comment by seerge** [comment]
@Matszwe02 no, in order to not to overcomplicate UI even more i prefer to keep this and other exotic (and used by 0.1% of the users) options as config only:)
