### ISSUE TITLE
XG Mobile shortcut

### ISSUE THREAD

**Issue by jkocon** [seerge/g-helper#3437]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I have mounted my XGM station to back of my sim rig and it's very incovinient access my laptop when it's connected to activate XGM

### Describe the solution you'd like

Create shortcut for enabling/disabling XG Mobile

### Describe alternatives you've considered

activate XGM via powershell/cmd script which can be triggered remotely via SSH

### Device and Model

Asus ROG Flow X13 & X16, XGM RTX3070

**Comment by jkocon** [comment]
I've found place in InputDispatcher.cs to add shortcut, I've commited change request, I've tested it on my machine x13 and X16 and looks like it's activating fine - the problem is when XGM is not connected it's trying to launch  function ToggleXGM() but listener is stopped after a while 

_F21 Alt, Control, Shift
GPU XGM = 1 : 0
XGM SUB device not found
4
Exception thrown: 'NvAPIWrapper.Native.Exceptions.NVIDIAApiException' in NvAPIWrapper.dll
Listener stopped
2
Exception thrown: 'NvAPIWrapper.Native.Exceptions.NVIDIAApiException' in NvAPIWrapper.dll
NVIDIA GeForce RTX 3050 Ti Laptop GPU
Eco flag : 0
Mux flag : -65536_

Activating XGM Ctrl + Shift + Alt + F21 and deactivating Ctrl + Shift + Alt + F22

**Comment by seerge** [comment]
@jkocon hello,

Sorry for a slow response - I was away.

I have added an option to toggle XGM via `Ctrl+Shift+Alt+F21` (by default). Or optionally you can add following line to `%appdata%\GHelper\config.json` to change `F21` to something else

```
"keybind_xgm":  <keycode>,
```

Where `<keycode>` is a code from https://www.oreilly.com/library/view/javascript-dhtml/9780596514082/apb.html

Try this build
[GHelper.zip](https://github.com/user-attachments/files/18092760/GHelper.zip)

Thanks

**Comment by seerge** [comment]
@jkocon did it work for you ?

**Comment by jkocon** [comment]
sorry, I'll let you know when I'll be back from business travel as I don't have XGM with me currently

**Comment by jkocon** [comment]
Hi, it works great with hotkey. thanks for adding it to release.
