### ISSUE TITLE
CPU Boost Frequency selection

### ISSUE THREAD

**Issue by daveholland86** [seerge/g-helper#3438]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Feature request

### Describe the solution you'd like

Would it be possible to add a frequency selection to the CPU section that sets the current power profile max frequency option in windows power settings?  It would help stream line custom CPU settings for different profiles.  Would allow us to use boost but not fully being a good middle ground for power and heat.  

### Describe alternatives you've considered

I currently also open windows power settings or QuickCPU to adjust any settings I need for max frequency. 

### Device and Model

Zephyrus G14 GA403

**Comment by seerge** [comment]
@daveholland86 hello, I was answering this couple of times already.

I don’t want to overcomplicate UI and app with things you can achieve somehow else (via power plan settings in Control Panel), especially considering how exotic this setting is.

Also from my experience CPU frequently limit in windows power plan worked only for Intel models, while AMD ones are simply ignoring that.
