### ISSUE TITLE
Connection to the keyboard

### ISSUE THREAD

**Issue by owergame191** [seerge/g-helper#3439]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

![Снимок экрана 2024-12-04 154959](https://github.com/user-attachments/assets/4cce8a71-e5d0-462c-9b20-b3173359fb12)
Program doesn't see my keyboard

### How to reproduce the bug?

Connect keyboard by dongle method

### Logs

[log.txt](https://github.com/user-attachments/files/18009649/log.txt)

### Device and Model

Rog Strixx G713PV

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.197.0

### OS

windows 11 home

**Comment by seerge** [comment]
@owergame191 hello,

G-Helper does not support Asus keyboard settings, as I don’t have a single one to implement it.

I don’t know what model do you have, but please check existing Peripheral support Issues, and if your specific device doesn’t have existing Issue yet - post it, and use separate Peripheral template (as it asks some relevant questions and other info for it)

Thanks
