### ISSUE TITLE
Screen Mode automatically switching when launching warframe

### ISSUE THREAD

**Issue by AmenRamen** [seerge/g-helper#3443]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The screen mode automatically switches from 60hz to 165hz when launching warframe (and only warframe), I have had the laptop with GHelper for a year and this only has happened with warframe starting when I downloaded it about a week ago. I have tried updating to new gpu drivers and removing Asus software but have found no solution

### How to reproduce the bug?

1. open the warframe launcher or launch through steam
2. start the game

### Logs

[log.txt](https://github.com/user-attachments/files/18014590/log.txt)

### Device and Model

Asus Zephyrus g14 GA402NU

### Additional information.

The bug happens multiple times in the log but most recently right at the end where I change the setting back to 60hz after

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.197

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@AmenRamen hello,

If display refresh rate changes only the moment you start the game - it simply means game does that. You should check some game settings deeper or just keep it as is.

G-Helper is not changing refresh rate here, and it can’t prevent other apps from doing so.

Sorry. Thanks
