### ISSUE TITLE
Paypal - 3DS verification needed

### ISSUE THREAD

**Issue by nobubblegums** [seerge/g-helper#3446]
Hi Serge, thanks a lot for your amazing work. This is a very minor issue, but my card kept getting declined (and blocked) when I tried to donate via PayPal, with a note saying "Merchants need to send transactions through with additional security (3DS)." Stripe worked fine, but since PayPal is more commonly used, I thought it'd be better to let you know.

**Comment by seerge** [comment]
@nobubblegums hello,

Thanks for a feedback and donation. But unfortunately this is something between Paylal itself and credit card company:) I can’t influence that. May be it happens only for specific banks/cards?

That’s one of the reasons I have added Stripe recently as a backup method for people who can’t use Paypal by some reasons.

Besides that I can’t change much :) Sorry.

Thanks! 🙏
