### ISSUE TITLE
Sleep->Hibernate breaks keyboard light until GH is restarted

### ISSUE THREAD

**Issue by KelseyHigham** [seerge/g-helper#3449]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I sleep, then hibernate the laptop - e.g. by closing the lid and waiting, or Start>Sleep and waiting - the keyboard backlight modes Rainbow, Heatmap, and Ambient don't work until G-Helper is restarted. It falls back to another keyboard light mode.

### How to reproduce the bug?

1. In G-Helper, enable Static backlight.
2. In G-Helper, enable Rainbow backlight.
3. Put the laptop to sleep, either by closing the lid, or with the Start menu. (maybe pressing the physical power button works too?)
4. Wait until the laptop hibernates.
5. Turn the laptop on. 
6. In G-Helper, the Rainbow mode is selected. But the backlight is a static color.
7. Restart G-Helper.
8. Now the backlight is rainbowing, as expected.

### Logs

[log.txt](https://github.com/user-attachments/files/18041791/log.txt)

### Device and Model

Asus Zephyrus G14 GA402XZ

### Additional information.

Sleeping by itself doesn't cause the issue. Hibernating by itself doesn't cause the issue.

I've been experiencing this problem for several months, maybe a year or longer, so it's not a recent regression.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.197.0

### OS

Windows 11 Home 23H2

**Comment by seerge** [comment]
@KelseyHigham hello,

Do you have any specific time when it happened (so i can check in the log), cause G-Helper sets last used backlight mode on wake up (including hibernate).

Keep in mind that Ambient and Heatmap are not firmware controlled modes, they are dynamic and need app to be running and changing backlight color in real-time. But this does not apply to Rainbow (it's hardware mode), so it should be running by itself even w/o app.

**Comment by KelseyHigham** [comment]
I don't remember what time I slept my laptop, so I'll record a new instance and post a new log later. 

There's two similar modes, Color Cycle and Rainbow. One of them is affected by this bug, and the other isn't.

**Comment by KelseyHigham** [comment]
[log.txt](https://github.com/user-attachments/files/18050184/log.txt)
here's a log of what *might* be the same bug. 

i put my computer to sleep about 45 minutes ago. it didn't go into hibernate. when i woke the computer, the keyboard backlight was off. when i restarted G-Helper, the backlight resumed Heatmap mode.

**Comment by KelseyHigham** [comment]
[log.txt](https://github.com/user-attachments/files/18050578/log.txt)
here's the bug:
0. my G-Helper was set to Heatmap. the most recent firmware mode was the rainbow one.
1. i put my computer to sleep a few hours ago, i don't know exactly when.
2. it hibernated.
3. i turned on the computer a few minutes ago. (the windows hello camera didn't start, i'm not sure if this is related??) the keyboard was doing the firmware rainbow animation.
4. i restarted G-Helper. the Heatmap mode resumed.

**Comment by seerge** [comment]
@KelseyHigham 

From the log i see that on wake-up form hibernation (i.e. when monitor was turned on), app has run all required RGB init commands and has set backlight color according to heatmap as it should

```
12/7/2024 4:41:36 PM: Power Mode Changed:Suspend <---- HIBERNATION
12/7/2024 4:41:36 PM: Timeout 19B6: 5D-BA-C5-C4-00
...
12/7/2024 6:59:52 PM: Lid Open
12/7/2024 6:59:52 PM: Lid 19B6: 5D-BA-C5-C4-03
12/7/2024 6:59:53 PM: Monitor Power On <---- WAKE UP 
12/7/2024 6:59:53 PM: AutoSetting for Online

...
12/7/2024 6:59:54 PM: Init 19B6: 5D-B9 <--- AURA INIT COMMANDS
12/7/2024 6:59:54 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
12/7/2024 6:59:54 PM: Init 19B6: 5D-05-20-31-00-1A
12/7/2024 6:59:54 PM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF 
....
12/7/2024 6:59:54 PM: AuraMode: HEATMAP <--- SETTING HEATMAP
12/7/2024 6:59:54 PM: Init 19B6: 5D-B9 <--- AND RUNNING INIT COMMANDS AGAIN
12/7/2024 6:59:54 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
12/7/2024 6:59:54 PM: Init 19B6: 5D-05-20-31-00-1A
```

When you restart app, it literally does same thing as it already did on wake up
```
12/7/2024 7:00:21 PM: App launched: ROG Zephyrus G14 GA402XZ_GA402XZ :0.197.0.0en-US
....
12/7/2024 7:00:23 PM: Init 19B6: 5D-B9
12/7/2024 7:00:23 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
12/7/2024 7:00:23 PM: Init 19B6: 5D-05-20-31-00-1A
12/7/2024 7:00:23 PM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
....
12/7/2024 7:00:23 PM: AuraMode: HEATMAP
12/7/2024 7:00:24 PM: Auto 19B6: 5D-BA-C5-C4-03
12/7/2024 7:00:25 PM: Init 19B6: 5D-B9
12/7/2024 7:00:25 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
12/7/2024 7:00:25 PM: Init 19B6: 5D-05-20-31-00-1A
```

So I don't know what's happening on your side. Just in case I have literally same device and can't reproduce it.

Can you try this build, where I have added a bit more verbose logging and post a log from it if it happens as well ?

[GHelper.zip](https://github.com/user-attachments/files/18060780/GHelper.zip)

**Comment by KelseyHigham** [comment]
i installed it and put my laptop to sleep, so i'll report back in a while.

during all these tests, i've had my laptop in Ultimate mode; that may affect things.

**Comment by KelseyHigham** [comment]
[log.txt](https://github.com/user-attachments/files/18067828/log.txt)
i woke my computer without checking whether it started to hibernate, oops. i think it only fell asleep?
i woke it and the keyboard was off, even when i increased it to full brightness. i restarted G-Helper, and the keyboard resumed Heatmap.

**Comment by KelseyHigham** [comment]
[log.txt](https://github.com/user-attachments/files/18067901/log.txt)
i changed my computer to sleep after a minute and hibernate after a minute, so here's a very short log.
my computer hibernated. i turned it on, and the keyboard was rainbowing. i restarted G-Helper, and it resumed Heatmap.

**Comment by seerge** [comment]
@KelseyHigham ok,

I think it's not really G-Helper's fault here, but rather firmware issue, that it doesn't completely "wake up" after sleep or hibernation (i.e. power off). So it simply ignores any init commands that G-Helper would send :) But after you restart app, it sends **same** init but since it happens after some time - it is accepted.

**Comment by seerge** [comment]
@KelseyHigham try this build, I have added one more "retry" write to USB device if it's not responding after such "wake-up"

[GHelper.zip](https://github.com/user-attachments/files/18076623/GHelper.zip)

**Comment by KelseyHigham** [comment]
[log.txt](https://github.com/user-attachments/files/18088689/log.txt)
I turned off my GPU because I'm traveling soon; I can test again with Ultimate mode in a few days.
After sleeping and waking up, the keyboard light was off, even at full brightness.
After restarting G-Helper, the keyboard light turned on again, on Heatmap.

**Comment by KelseyHigham** [comment]
[log.txt](https://github.com/user-attachments/files/18089450/log.txt)
this one worked!! after sleep->hibernate->boot->login, the keyboard changed from rainbow to heatmap.

**Comment by KelseyHigham** [comment]
when i have time, i'll try it again on Ultimate, just to make sure that's not a factor. but yes, i think so.

should i file a separate Issue for the keyboard light being off when i wake from sleep?

**Comment by seerge** [comment]
@KelseyHigham did your firmware turn off backlight also with new build ? cause from the log i don't see any errors attempting to change backlight level.

**Comment by KelseyHigham** [comment]
yes, i believe the backlight is still off when resuming from sleep, even with the new build. i can double-check later.

**Comment by KelseyHigham** [comment]
actually no, i haven't seen the backlight-turning-off behavior since, so that problem seems fixed (or i haven't been able to replicate it).

**Comment by seerge** [comment]
@KelseyHigham great
