### ISSUE TITLE
 asus tuf a16 advantage edition power limit not applying 

### ISSUE THREAD

**Issue by mesery** [seerge/g-helper#3450]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

the cpu slider power limit not applying - i tested the power draw through hw monitor 

### How to reproduce the bug?

1-fans and power in g helper 
2-adjust cpu slider to desired power limit in cpu only slider 
3- press apply power limit
4-the power limit doesnt apply or take effect 

### Logs

[log.txt](https://github.com/user-attachments/files/18042049/log.txt)

### Device and Model

asus tuf a16 advantage edition FA617NT

### Armoury Crate

Uninstalled

### Asus Services

stopped

### Version

0.197

### OS

W11-24h2

**Comment by seerge** [comment]
@mesery hello,

I see that you you set 150W total power limit for (CPU + GPU) and 32W for CPU in Balanced mode, and both limits are applied

```
12/6/2024 8:11:20 PM: Mode = 0 : OK
12/6/2024 8:11:21 PM: PowerLimit A3 = 150 : OK
12/6/2024 8:11:21 PM: PowerLimit A0 = 150 : OK
12/6/2024 8:11:21 PM: PowerLimit B0 = 32 : OK
```

How do you know that they are not "applying"? What exactly do you monitor and how do you measure it ? Can you post a screenshot?

Usually - correct way to test it, would be run a CPU heavy benchmark (like Cinebench23) and monitor power consumption in HWinfo, if it stays below set limit (32W) - then it's working.

**Comment by mesery** [comment]
SRY FOR LATE REPLY - i figured out that limits didn't apply ( monitoring with hw info ) UNTIL for some reason the box at bottom ( apply custom fan curve) is marked then the limits apply i have no idea why but hope this helps anyone with same device or situation and thanks

**Comment by Ege14** [comment]
thanks, for the help i had the same problem
