### ISSUE TITLE
Windows 24h2 update changes display control – Ghelper (and Armoury Crate!) break display on G14 2022

### ISSUE THREAD

**Issue by krzyfu** [seerge/g-helper#3456]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

After startup of G-Helper the display becomes washed out (some kind of gamma curve adjustment?) with black becoming grey and everything becoming flat and with a lot of banding in the shadows. Color profiles are being applied, but gamma is totally broken. And no, it is not because "System -> Display -> Advanced Display -> Automatically Manage Color for Apps" - I don't even *have* this option at the moment. It becomes available only after installing the Adrenaline drivers directly from AMD. But then the issue comes up with or without this option enabled, and is persistent (system restart does not reset it) - once it messes up my gamma, only driver cleaning (DDU/AMD cleanup utility) can help.

What is important that the same things happens if I install Armoury Crate (the display switches to washed out while "installing Asus framework" during the installation process), so it is definitely something freshly introduced by the latest windows build. To the effect that now there is no way to control the graphics adapters on this laptop without this gamma thing getting out of hand.
The only way this doesn't happen atm is with the latest drivers that are provided directly by Microsoft through Windows Update (see screenshot - they are really new, a couple of days ago even these drivers didn't work). The vanilla drivers shipped by ASUS also don't work. No amount of cleaning up and reinstalling makes this go away (also tried new Windows profile to rule out other factors interfereing). The moment I start GHelper the display goes straight to washed-out/banding mode...

My theory is that the Windows 24H2 update, introducing ACM (Advanced Color Management) to the whole of the Windows experience, changed something in how the display is being controlled, causing this break. Can VariBright be the issue? The setting itself moved to the Windows settings, so maybe there is a conflict here, as it is still available in Ghelper. I tried a "driver only" installation thinking that maybe without the amd control center it might work, but no. This is all I was able to establish until now.

Truth is, atm my laptop is near unusable. To get a usable display I have to let go of control over special keys, keyboard backlighting, and above all - graphics swithing, so battery drain is hugo, etc. etc. Has anyone else reported/experienced that?
Here are screenshots of the Windows drivers with which starting ghelper does not require me to reinstall video drivers...
![Screenshot 2024-12-07 101624](https://github.com/user-attachments/assets/8e140abf-00b0-4463-b009-6fc7b878a6ef)
![Screenshot 2024-12-07 084725](https://github.com/user-attachments/assets/f6fb6a37-1816-4a14-be98-e3eeebe9a473)

### How to reproduce the bug?

1. remove drivers (DDU / AMD Cleanup Utility)
2. restart computer
3. let windows install drivers, or install drivers : from Asus or directly from AMD (tried all 3)
4. start Ghelper / install Armoury Crate (same effect)
5. effect: some weird gamma curve gets applied to (removed from?) the display to the effect that the colors are washed out, there are no blacks, and there is heavy banding in the shadows
6. with the drivers supplied by Windows the gamma problem goes away after restaring, with all the other drivers it is persistent, and drivers have to reinstalled to get back to normal

### Logs

[log.txt](https://github.com/user-attachments/files/18051245/log.txt)

### Device and Model

Asus Zephyrus G14 2022 (GA402RK)

### Additional information.

As already mentioned, I tried everything - Ghelper or Armoury Crate (never at the same time, of course)

### Armoury Crate

Uninstalled

### Asus Services

now 1, before it was 7, tried also turning them all off, of course, to no avail 

### Version

0.197

### OS

Windows 11 24H2

**Comment by krzyfu** [comment]
Just in case, also tried the latest build - 0.199 - with the same effect.

**Comment by seerge** [comment]
@krzyfu hello,

I have same device as you do, and also 24H2 update and don't experience that :)

I see that you use a "Scenery" Visual Mode (managed by AsusSplendid app). Did you try setting Default mode ? Most likely it's the reason of colors being different for you.

**Comment by krzyfu** [comment]
hi @seerge,

thank you for the reply! I don't think I ever used the Asus splendid app 😥 - where do I find this setting?

**Comment by seerge** [comment]
@krzyfu it's used under the hood by G-Helper / AC to change Visual Mode / Game Visual.

I see that you have `Visual Mode` set to `Scenery`, try to set it to `Default`

**Comment by krzyfu** [comment]
ok, this is embarassing 😂 – I have no idea how this got changed (maybe i scrolled the mouse over the setting somehow?). Whatever, this was the culprit. And north of 10hrs of trying to find the culprit 🤦‍♀️. THANK YOU!!

**Comment by seerge** [comment]
@krzyfu ok, amazing.
