### ISSUE TITLE
Request to disable nVidia's DB 2.0 dynamic boost.

### ISSUE THREAD

**Issue by BGzEroll** [seerge/g-helper#3457]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

My laptop is equipped with an RTX 3060 GPU, which has Dynamic Boost 2.0 (DB 2.0) enabled by default. With DB 2.0, the GPU power limit increases from 100W to 115W. However, this comes at the cost of locking the CPU's power limit at 35W. In most scenarios, the extra 15W allocated to the GPU provides negligible frame rate improvements, but it significantly hampers CPU performance, limiting its frequency to around 3.2 GHz.

### Describe the solution you'd like

Dynamic Boost 2.0 (DB 2.0) can be set to a minimum of 0W.

### Device and Model

ASUS TUF Gaming A15 FA507RM

**Comment by seerge** [comment]
@BGzEroll hello,

If your device supports Dynamic Boost adjustment you will see it under `Fans+Power` GPU section already. Asus allows to adjust it in a 5W..25W usually.

If you don't see this slider - it simply means your device does not support adjusting Dynamic Boost.

You may limit GPU power in other ways, for example by limiting GPU clock or by setting FPS limit under Nvidia Control Panel.

Thanks

**Comment by BGzEroll** [comment]
> 备支持动态增强调整，您将在`Fans+Power`GPU部分中看到它。华硕允许

My device supports Dynamic Boost 2.0 (DB 2.0), and I can see the slider in G-Helper, but the minimum setting is limited to 5W. With DB 2.0 enabled, the CPU is inevitably restricted to 35W under high GPU load. Currently, the only way I can disable DB 2.0 is by manually disabling the "NVIDIA Platform Controllers and Framework" component in Device Manager. After disabling it, my GPU's maximum power limit is capped at 100W, while the CPU's maximum power goes up to 50W+, with no noticeable drop in frame rates. However, I have to repeat this process every time the driver resets.  

Therefore, I’m wondering if it’s possible to directly set DB 2.0 to 0W via G-Helper without disabling the component.

**Comment by BGzEroll** [comment]
> @BGzEroll hello,
> 
> If your device supports Dynamic Boost adjustment you will see it under `Fans+Power` GPU section already. Asus allows to adjust it in a 5W..25W usually.
> 
> If you don't see this slider - it simply means your device does not support adjusting Dynamic Boost.
> 
> You may limit GPU power in other ways, for example by limiting GPU clock or by setting FPS limit under Nvidia Control Panel.
> 
> Thanks

My device supports Dynamic Boost 2.0 (DB 2.0), and I can see the slider in G-Helper, but the minimum setting is limited to 5W. With DB 2.0 enabled, the CPU is inevitably restricted to 35W under high GPU load. Currently, the only way I can disable DB 2.0 is by manually disabling the "NVIDIA Platform Controllers and Framework" component in Device Manager. After disabling it, my GPU's maximum power limit is capped at 100W, while the CPU's maximum power goes up to 50W+, with no noticeable drop in frame rates. However, I have to repeat this process every time the driver resets.  

Therefore, I’m wondering if it’s possible to directly set DB 2.0 to 0W via G-Helper without disabling the component.

**Comment by seerge** [comment]
@BGzEroll I don't think it's possible to set it lower than 5W (same as in Armoury) cause this is the limitation of this setting defined by Asus.

I think the only "real" way to completely turn off Nvidia dynamic power management - is what you do already in Device Manager, but I can't add it to G-Helper :)

**Comment by BGzEroll** [comment]
> @BGzEroll I don't think it's possible to set it lower than 5W (same as in Armoury) cause this is the limitation of this setting defined by Asus.
> 
> I think the only "real" way to completely turn off Nvidia dynamic power management - is what you do already in Device Manager, but I can't add it to G-Helper :)

Okay, thank you for your hard work👌

**Comment by Nagidrop** [comment]
You can also use [NVCleanstall](https://www.techpowerup.com/download/techpowerup-nvcleanstall/) to de-select "NV Platform Controllers" in driver exe before installing. Also, unless you want to play newest games, you shouldn't always update your drivers (they might introduce new issues). Instead, you should stick to the older, community-trusted stable ones e.g. 566.36 (you can find specific versions by looking or asking in forums, r/nvidia, or community Discord channels).

<img width="536" height="635" alt="Image" src="https://github.com/user-attachments/assets/aa53b0c3-d8da-46f2-8040-4b2cd5a8eabf" />
