### ISSUE TITLE
Second fan Control

### ISSUE THREAD

**Issue by MrOmega3** [seerge/g-helper#3463]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

[`ROG Strix G15, AMD Processor]
Its related to oevrheating. GHelper (although great), for some reason completely ignores my left fan. When I run a system check, both fans work, and when I use turbo mode on armoury crate, both fans work, but only the right one works when I use GHelper. I've noticed my right side remains way cooler than the left side when i'm gaming. 
Maybe I've done something wrong while setting up because I find no complaints of this online.

### Describe the solution you'd like

A way to get the fan to work. 
I'm not well versed in the software side of tech so I'm not sure how to make this work. 

### Device and Model

Asus ROG Strix G15  G513RC_G513RC

### Additional information.

ryzen 7 6800H
Nvidia 3050

**Comment by seerge** [comment]
@MrOmega3 hello, G-Helper is not controlling your fans, please make yourself familiar with FAQ. If you use custom fan curve you may reset all settings to defaults under `Fans  + Power`

> **[How does G-helper control my fan speeds?](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)**
> It doesn't and can't control your fans. Firmware / BIOS controls them in real-time. Armoury also doesn't control fans in real time anyhow.

> What G-helper can do - is (optionally) set a custom fan profile to the current performance mode via the same endpoint Armoury uses in Manual mode.

> How it will be interpreted - is still up to the firmware. If you don't like how firmware controls fans, you can try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)
