### ISSUE TITLE
Support for Vivobook S 15 OLED (S5506MA)

### ISSUE THREAD

**Issue by chertvl** [seerge/g-helper#3465]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hey, Seerge.
Just found that amazing app to control my new laptop a little bit better.
Sadly to say, some features doesnt supports on my model, or supports in special (experimental) versions.

It would be great if I will get GHelper build with that features:
1. Manual Fan Control (like in https://github.com/seerge/g-helper/discussions/2272) because my model is MyASUS only, there is no ArmorCrate or another asus software. That feature works perfecly.
2. Flicker-Free Dimming / Visual Mode (like in https://github.com/seerge/g-helper/issues/3265) because that mode have same OLED matrix
3. FN-Lock key is inverted (now its blue when its off and grey when FN keys controls volume/brightness/etc)

That all will be usefull for owners of new Vivobook S 15/16" (2024) models like S5506, S5507, S5606 (intel), M5506, M5507 (ryzen) etc.

Велике дякую зi столицi за чудовий iнструмент.

![image](https://github.com/user-attachments/assets/d3901ef9-ee82-4211-abf8-13e055017d6a)

### How to reproduce the bug?

.

### Logs

nothing usefull here

### Device and Model

Asus Vivobook S15 OLED (S5506MA)

### Armoury Crate

Uninstalled

**Comment by chertvl** [comment]
Ah, and one more dissapoint.
That models has built-in [Fn+F] to switch between 4 profiles of fan (fullspeed, performance, standart, queit),
but GHelper react for that (WMI event 157) and switching his 3 profiles (silent, balanced, turbo). 
These are 3, those are 4, so they never match. :) Is that a way to disable hotkey 157 for Ghelper? (```"skip_hotkeys":1``` didnt helps)

**Comment by chertvl** [comment]
> This build should add OLED features and re-invert FN-Lock for you. [GHelper.zip](https://github.com/user-attachments/files/18092627/GHelper.zip)
> Do they work ?

Thanks, Seerge, OLED and inverted-Fn features works as expected, it has to be implemented in future release for all ;)

> As for Experimental fan control. It won't be merged into mainstream.

Okay, so, then my tactic is waiting for new release and experimental based on new release, and I will get that all features in one build. ;)


> As for 4th (`Full Speed`?) profile. It is possible to set it as well:

The only reason why im asking for that, there is no way to disable build-in Fn+F hotkey in MyASUS app, and looks like there in to way to disable it in G-Helper. Onfortunally, both apps looks for this WMI and switching them profiles without any feedback.
Ive tried to add 4th profile (as custom) in G-Helper, but it happens that profiles doent match (Silent+Turbo,  Performance+Balanced)  [MyASUS/G-Helper].

**Comment by seerge** [comment]
@chertvl since MyAsus plays a role of Armoury Crate on Vivobooks, it will be conflicting with G-Helper. So you should use only something one. Can you explain what exactly are you using MyASUS for ?

**Comment by chertvl** [comment]
> @chertvl since MyAsus plays a role of Armoury Crate on Vivobooks, it will be conflicting with G-Helper. So you should use only something one. Can you explain what exactly are you using MyASUS for ?

Idk if is safety to delete them. Additionaly, MyASUS shows me drivers and bios updates, and that toats messages when I pressing vivobook hotkeys (keyboard brightness, mic mute, noice cancelling in dinamics) - all toats in that asus design in center of screen from ATK-Keyboard application times on older models.
There are some features that not in G-Helper, like "1 day of fullchange then limit 80% again" [checkbox].

I got acquainted with Ghelper literally a couple of days ago, and I am not ready to completely abandon the built-in software yet. Perhaps in the future, when I decide on specific functions that I will or will not use, I will reconsider the decision. For now, I would like to keep both.

**Comment by chertvl** [comment]
I have decided to remove MyАsus. :)
Thanks for this point of view.

Maybe later I will be able to formulate briefly what functions I have lost (if I need them at all) and write a new issue.
At the moment I have to close the issue as complete, I will wait for the new release and the experimental version.
Thank you very much!

**Comment by additi8n** [comment]
I also have similar request, I just started using Ghelper recently. 
I have Vivobook S14 M5406 and I have been using the experimental version to control fans but I noticed there was no flicker free dimming.
Will it be added eventually?

**Comment by chertvl** [comment]
> Will it be added eventually?

@additi8n 
You need do create an issue for adding M540 series in OLED-list (list of moleds is hardcoded). This issue is closed already.
Then you need wait like me for 0.200 release, then will be experimental version for with fan curve modes, based on 0.200 ver.

**Comment by seerge** [comment]
@additi8n it's already added as a result of separate request https://github.com/seerge/g-helper/issues/3488 :)

**Comment by seerge** [comment]
@chertvl @additi8n I have also updated [Experimental build](https://github.com/seerge/g-helper/discussions/2272) with latest changes from 0.200
