### ISSUE TITLE
Fan speeds up quickly at ~71C then drops with higher temp

### ISSUE THREAD

**Issue by Pjooo** [seerge/g-helper#3467]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Fan curve doesn't work correctyly. Laptop ramps up Fan Speed when CPU temp goes over 70C, and then drops Fan Speed.
In Armoury Crate I don't see that behavior, so it's not bios.

Also, is there a way to control fan at all speeds? At some temp there is minimum speed. And my laptop e.g. 2400 RPM in G-Helper = 3000RPM Laptop. So it's too high for me, I'd like more gentle fans.

### How to reproduce the bug?

1. Set fan curve with Fan speed at 75C at 2400 RPM
2. Load CPU so it's temp go at 71, 72, 73C slowly
3. At around 70-71C fan speeds up rapidly to 3600-4000 RPM
4. Then if you keep temp over 72C (even 90C) fan slows down to 3000 RPM

### Logs

[log.txt](https://github.com/user-attachments/files/18088082/log.txt)

### Device and Model

Zephyrus G14 GA403UI

### Armoury Crate

Uninstalled

### Asus Services

0 (redid testing with all asus stopped)

### Version

0.199

**Comment by seerge** [comment]
@Pjooo hello,

Fans are always **controlled by BIOS / firmware** not by G-Helper or AC. [Please check FAQ.](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)

From my observations 2024 models have a very high hysteresis (reaction time) on temp changes, so don't expect fan speeds to reflect temps immediately.

If you really want more "custom" fan control you can try [Experimental build with a manual fan control.](https://github.com/seerge/g-helper/discussions/2272)

Thanks
