### ISSUE TITLE
Turn the indicator lights off for the Asus ROG Strix G16? :)

### ISSUE THREAD

**Issue by Strixg16** [seerge/g-helper#3469]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hi. I'm reaching out to see if I can get the feature to disable the status leds added to the program with support for 2023 ROG Strix g16 (model number G614JI) 

### Describe the solution you'd like

I have seen comments online that allows the g18 strix laptops to disable the status light feature and was wondering if it was possible to do the same for the g16 models. 

https://www.reddit.com/r/ASUS/comments/1eqlwp3/asus_rog_strix_g16_is_there_a_way_to_turn_off_the/

This was the post that lead me to reaching out to you to see what I could get done :)

Thanks for all your hard work getting rid of big tech mandatory/proprietary  software. You're a real hero.  

### Device and Model

Asus ROG Strix g16 (2023) 13650hx/4070

**Comment by seerge** [comment]
@Strixg16 hello,

Unfortunately it's not possible for 2023 models. Asus has added an dedicated toggle for status LEDs exclusively starting from 2024 model.

G-Helper just gives access to a setting that already exists on the device :) It can't reprogram hardware anyhow

Sorry. Thanks!

**Comment by Strixg16** [comment]
Thank you so much for that info! Guess I'll just have to use some tape to block it out then. :) 

Thanks again for your support in developing this software and for the super quick response. You are amazing. :D

**Comment by seerge** [comment]
@Strixg16 np, good luck with taping :)
