### ISSUE TITLE
power button issue 

### ISSUE THREAD

**Issue by alimahran2612** [seerge/g-helper#3470]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

i got an issue with power button , its not broken but sometimes i need to press tons of times to get it turned on 

### How to reproduce the bug?

1- turn off laptop turns of normally even from power button only 1 press
2- try to turn on again it doesnt turn on need to hit the power button tons of times to work it out 

### Logs

12/11/2024 7:13:01 PM: Get-Service -Name "ASUSOptimization" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:01 PM: powershell Get-Service -Name "ASUSOptimization" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:01 PM: PowerLimit A3 = 80 : OK
12/11/2024 7:13:01 PM: PowerLimit A0 = 105 : OK
12/11/2024 7:13:01 PM: 
12/11/2024 7:13:01 PM: Get-Service -Name "AsusAppService" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:01 PM: powershell Get-Service -Name "AsusAppService" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:02 PM: 
12/11/2024 7:13:02 PM: Get-Service -Name "ASUSLinkNear" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:02 PM: powershell Get-Service -Name "ASUSLinkNear" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:02 PM: Get-Service : Cannot find any service with service name 'ASUSLinkNear'.
At line:1 char:1
+ Get-Service -Name ASUSLinkNear | Stop-Service -Force -PassThru | Set- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ASUSLinkNear:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
 

12/11/2024 7:13:02 PM: Get-Service -Name "ASUSLinkRemote" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:02 PM: powershell Get-Service -Name "ASUSLinkRemote" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:03 PM: Get-Service : Cannot find any service with service name 'ASUSLinkRemote'.
At line:1 char:1
+ Get-Service -Name ASUSLinkRemote | Stop-Service -Force -PassThru | Se ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ASUSLinkRemote:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
 

12/11/2024 7:13:03 PM: Get-Service -Name "ASUSSoftwareManager" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:03 PM: powershell Get-Service -Name "ASUSSoftwareManager" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:03 PM: 
12/11/2024 7:13:03 PM: Get-Service -Name "ASUSLiveUpdateAgent" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:03 PM: powershell Get-Service -Name "ASUSLiveUpdateAgent" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:03 PM: Unable to load DLL 'atiadlxx.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
12/11/2024 7:13:04 PM: Hibernate after 2147483647
12/11/2024 7:13:04 PM: Get-Service : Cannot find any service with service name 'ASUSLiveUpdateAgent'.
At line:1 char:1
+ Get-Service -Name ASUSLiveUpdateAgent | Stop-Service -Force -PassThru ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ASUSLiveUpdateAgent:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
 

12/11/2024 7:13:04 PM: Get-Service -Name "ASUSSwitch" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:04 PM: powershell Get-Service -Name "ASUSSwitch" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:04 PM: 
12/11/2024 7:13:04 PM: Get-Service -Name "ASUSSystemAnalysis" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:04 PM: powershell Get-Service -Name "ASUSSystemAnalysis" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:05 PM: 
12/11/2024 7:13:05 PM: Get-Service -Name "ASUSSystemDiagnosis" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:05 PM: powershell Get-Service -Name "ASUSSystemDiagnosis" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:05 PM: 
12/11/2024 7:13:05 PM: Get-Service -Name "AsusCertService" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:05 PM: powershell Get-Service -Name "AsusCertService" | Stop-Service -Force -PassThru | Set-Service -StartupType Disabled
12/11/2024 7:13:06 PM: 
12/11/2024 7:13:24 PM:  HDR: True 8 7 True

### Device and Model

Asus TUF GAMING F15

### Armoury Crate

Uninstalled

### Asus Services

3

### Version

0.199.0

### OS

Windows 11

**Comment by seerge** [comment]
@alimahran2612 hello :) 

If laptop is not turning on from the power button it looks like some physical problem with an actual button or contacts underneath. 

I'm afraid it's not related to G-Helper anyhow, since it's not even running when laptop is literally off.

I can't help you here :) Sorry.

Thanks
