### ISSUE TITLE
Fps flexibility for autotdp

### ISSUE THREAD

**Issue by Devianxe** [seerge/g-helper#3485]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Fps cap for autotdp

### Describe the solution you'd like

Make the fps cap selection increment by 5 so we can use 70fps, 80fps and such

### Device and Model

Asus ROG ally

**Comment by seerge** [comment]
@Devianxe hello,

Can you explain a practical reason for this?  As there is not much percieveable difference between 75FPS and 80FPS for example

I prefer to keep UI simple and not force people to click same button like 20 times to switch between 60FPS and 120FPS for example.

Thanks

**Comment by Devianxe** [comment]
> @Devianxe hello,
> 
> 
> 
> Can you explain a practical reason for this?  As there is not much percieveable difference between 75FPS and 80FPS for example
> 
> 
> 
> I prefer to keep UI simple and not force people to click same button like 20 times to switch between 60FPS and 120FPS for example.
> 
> 
> 
> Thanks

Hello mate ,

It's more to fill the gap between 60fps and 90fps.

Yesterday i was playing cod and at the watts set the game could run above 60fps but not reach 90fps.

**Comment by seerge** [comment]
@Devianxe hello, I think it will be an overkill to have 5FPS steps and it will force you to click button much more times to cycle through them

I have added an extra 75FPS limit to fill your "gap"

Check this build

Thanks

[GHelper.zip](https://github.com/user-attachments/files/18140307/GHelper.zip)
