### ISSUE TITLE
Requesting Flicker free dimming for Asus Vivobook S 14 Oled M5406UA

### ISSUE THREAD

**Issue by mfachrila** [seerge/g-helper#3488]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Flicker free dimming is missing with compatible laptop(oled)

### Describe the solution you'd like

Add the Flicker free dimming feature. Thank you

### Device and Model

Asus Vivobook S 14 Oled M5406UA

**Comment by seerge** [comment]
@mfachrila hello, this build should offer OLED settings for your device

[GHelper.zip](https://github.com/user-attachments/files/18140281/GHelper.zip)

**Comment by mfachrila** [comment]
Thank you, it works
