### ISSUE TITLE
Add a microphone management to prevent mic to pick up too much bg sounds.

### ISSUE THREAD

**Issue by LuzeBillan** [seerge/g-helper#3490]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

After uninstalling Armoury Crate, I noticed that during voice calls, my microphone seems to pick up sounds from all directions, making background noise (e.g., my roommate's voice) louder than mine. I suspect this is because Armoury Crate had a feature to adjust the microphone's directionality or noise suppression settings, and without it, my microphone is no longer optimized for voice calls.

### Describe the solution you'd like

The microphone should primarily pick up my voice while reducing or filtering out background noise, as it did before uninstalling Armoury Crate.

### Describe alternatives you've considered

Merely disable some of the mic is also helpful.

### Device and Model

ROG STRIX G16 2023

**Comment by squee666** [comment]
it was handled in software yes but it is completely optional when most call software has built in noise suppression
zoom,discord,teams
if that isnt strong enough nvidia broadcast has rtx voice which does this also
so does the realtek audio driver 
so imo its not needed

![image](https://github.com/user-attachments/assets/2ec82eff-7ad9-4a00-be72-024063d17e56)

**Comment by LuzeBillan** [comment]
Ah yes! I forgot it! Thanks a lot

**Comment by seerge** [comment]
@LuzeBillan hello, this is a **dublicate** of [another issue](https://github.com/seerge/g-helper/issues/18). 

Please check answers there and also as @squee666 mentioned, the only way to control sound settings outside of (unknown proprietary) access from AC - is to do it from Realtek Audio Console.

If it's possible - you will have those options there already :) 

Thanks!
