### ISSUE TITLE
"You must install or update .NET to run this application"

### ISSUE THREAD

**Issue by haakonstorm** [seerge/g-helper#3491]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

GHelper 0.199.0.0
Windows 11 Home, all latest patches

Suddenly, Ghelper starts with `"You must install or update .NET to run this application"`.
OK, so I download, and the installer asks me Repair or Uninstall.
I've tried Repair, same result. Tried Uninstall and Reinstall, same result. 
Tried uninstall, reboot, reinstall, start, same result. 

For my system `windowsdesktop-runtime-8.0.11-win-x64` is downloaded. 
Perhaps `8.0.0` or another version is needed by GHelper? 

I'm stuck in a loop :-/

### How to reproduce the bug?

1. Start G-Helper
2. Error for .NET, need to install or update .NET
3. Download, install/repair .NET succeeds
4. Repeat from 1, same error

### Logs

[log.txt](https://github.com/user-attachments/files/18169169/log.txt)

### Device and Model

Asus Zephyrus M16

### Additional information.

![image](https://github.com/user-attachments/assets/e4031984-c5c9-460b-943e-527b38a0ef5e)

![image](https://github.com/user-attachments/assets/50d3ac2c-4bf9-4801-995c-c357d82b0648)

### Armoury Crate

Uninstalled

### Asus Services

G-helper doesn't start

### Version

.199

### OS

Windows 11 (latest)

**Comment by seerge** [comment]
@haakonstorm hello,

- Try to uninstall .NET 8 runtime and then install it again.
- If it doesn't help - try to download [.NET 8 SDK](https://download.visualstudio.microsoft.com/download/pr/ba3a1364-27d8-472e-a33b-5ce0937728aa/6f9495e5a587406c85af6f93b1c89295/dotnet-sdk-8.0.404-win-x64.exe) instead (it includes all possible bells and whistles), may be that will help

Thanks

**Comment by haakonstorm** [comment]
Thank you for helping. I've uninstalled the .NET 8 runtime, and installed the .NET 8 SDK, but same results.
Anything else to try to debug?

**Comment by haakonstorm** [comment]
It specificly asks for 8.0.0 though?
![image](https://github.com/user-attachments/assets/c8976ff2-2138-4bbf-8085-e29dc1e2bb53)

**Comment by haakonstorm** [comment]
The `dotnet-sdk` is currently at version `dotnet-sdk-8.0.404-win-x64`. 
The runtime is currently at version `windowsdesktop-runtime-8.0.11-win-x64`.

**Comment by haakonstorm** [comment]
![image](https://github.com/user-attachments/assets/bfb7a972-4a33-411f-9c43-4cbb5bfd566b)

**Comment by seerge** [comment]
@haakonstorm may be try a simple reboot to see if helps? Or repair [corrupted files](https://github.com/seerge/g-helper/wiki/Troubleshooting#repair-corrupted-system-files) ? 

Cause popup that you see is not even from G-Helper code itself, it's some built in .NET existence checker ...

**Comment by haakonstorm** [comment]
Reboot didn't help, but I'll try the helpful advises in the `corrupted files` section now.

**Comment by haakonstorm** [comment]
![image](https://github.com/user-attachments/assets/51db0913-7034-4aed-9341-66c822727f6d)

- Reinstalling Asus System Control Interface, tried, but installer said same version was installed

I'm guessing this is something related the .NET sdk or runtime, but I'm not sure how to proceed. 
I just switched back to windows from macos, i'm a little rusty on windows subsystems.

**Comment by seerge** [comment]
@haakonstorm did it work before? Since what moment did it stop ? could it be some (unlucky) windows update or some other action causing it ?

**Comment by haakonstorm** [comment]
Yes, it worked perfectly for at least a year. I'm not sure what caused it, it might have been either with me installing the C# extensions for VSCode, or installing the redists via `scoop install extras/vcredist2022`.

**Comment by haakonstorm** [comment]
But weird a reinstall of the required depencies for g-helper don't work?
What can I do to debug? Are there anything in the Registry. How specifically is G-helper actually getting the dep's it is needing?

Are these dot versions of any relevance? --> 
The dotnet-sdk is currently at version dotnet-sdk-8.0.404-win-x64.
The runtime is currently at version windowsdesktop-runtime-8.0.11-win-x64.

Since it specifically asks for 8.0.0 ?

**Comment by haakonstorm** [comment]
Installing Runtime at an older version @ 8.0.0 yields same results.

**Comment by haakonstorm** [comment]
This appears to have been the problem:

![image](https://github.com/user-attachments/assets/e0a2ca4f-03df-4364-9030-58f1647b29d4)

`dotnet-sdk` as installed via scoop, installed v9.0.101 of dotnet.

I uninstalled this, uninstalled the 8 SDK and logged out and back in again, then g-helper was suddenly running as usual.
I'm tempted to try and verify this, but it's now 1am and I'm very happy to have it back working.
The only difference there is now 1 asus service that g-helper can't stop, it used to be 0, but I can live with that :)
Let me know if there is anything else I can provide in order for this to potentially help anyone else.

Here is the updated logs. Appears g-helper only now started working enough to start logging:
[log.txt](https://github.com/user-attachments/files/18172709/log.txt)

**Comment by haakonstorm** [comment]
Feel free to close this issue at will if there is nothing more I can provide from my end?

**Comment by seerge** [comment]
@haakonstorm 

> dotnet-sdk as installed via scoop, installed v9.0.101 of dotnet.

I uninstalled this, uninstalled the 8 SDK and logged out and back in again, then g-helper was suddenly running as usual.
I'm tempted to try and verify this, but it's now 1am and I'm very happy to have it back working.
The only difference there is now 1 asus service that g-helper can't stop, it used to be 0, but I can live with that :)
Let me know if there is anything else I can provide in order for this to potentially help anyone else.

I think this was the reason indeed. Your 9.0 .NET was confusing the system. Logs are not really needed here, cause if app doesn't even launch - it doesn't write any logs, but thanks :)

I'm glad it's resolved :)
