### ISSUE TITLE
Support for NumberPad (2.0)

### ISSUE THREAD

**Issue by craeckor** [seerge/g-helper#3494]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Without MyAsus, the NumberPad (2.0) on my ASUS Zenbook 14 Flip OLED doesn't work. It's a NumberPad integrated into the Touchpad.

### Describe the solution you'd like

An integration for the NumberPad (2.0) into g-helper.
The Linux-Driver currently supports 9 different version for the NumberPad. These NumberPads are available on a wide-range of ASUS-Notebooks including Gaming-Notebooks. It would be nice if all these different NumberPads were implemented into g-helper in the future.

### Describe alternatives you've considered

- Install MyAsus (Not recommended)

### Device and Model

Asus Zenbook 14 Flip OLED (UN5401QA)

### Additional information.

Linux-Driver: https://github.com/asus-linux-drivers/asus-numberpad-driver

**Comment by seerge** [comment]
@craeckor hello, this is a valid request, but since I don't have a device with Numpad it's quite difficult to add it.

What exactly can you control there ? And as I remember (at least on ROG Strix models) it was absolutely separate and standalone asus service (or app) that was handling it. So you could keep it even without Armoury or MyASUS-package.

**Comment by craeckor** [comment]
My fault.
It's just a driver. You don't need MyAsus or something else. Not even G-Helper.
