### ISSUE TITLE
Battery won't go below 100%

### ISSUE THREAD

**Issue by Kaito1877** [seerge/g-helper#3495]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I am trying to limit my laptop's battery to 80% using g helper, as that is what I have done during my time with MyAsus before uninstalling it for g helper. No matter what I do, the battery will not go below 99%. Last night I made sure to drain it near 75% and it turned out to be capped to 80% when I put on the charger but now it simply will not work because the battery went up to 99 again I suppose? 

### How to reproduce the bug?

No idea on how to show it

### Logs

[log.txt](https://github.com/user-attachments/files/18195920/log.txt)

### Device and Model

Asus ROG Strix G18 G814JZR

### Armoury Crate

Uninstalled

### Asus Services

0 stopped them all

### Version

0.199.0

### OS

Windows 11 Pro

**Comment by Kaito1877** [comment]
I have already stopped the services last night and then uninstalled MyAsus if I am not wrong before closing the laptop and going to bed eventually. I have had AC uninstalled two weeks ago and decided to keep MyAsus for driver updates but learnt that g-helper would handle that as well, so I just decided to uninstall it. My charge was capped to 80% before I went to sleep, but it wasn't when I woke up and still is not, somehow is capped to 99%?? I have already stopped all asus services before closing the laptop last night so I am not sure about what is wrong with it. Also my charge led is currently white, not yellow as it should be when the battery is below 100%
<img width="367" alt="image" src="https://github.com/user-attachments/assets/60741098-b251-4064-9d1f-aa67183cc990" />

**Comment by seerge** [comment]
@Kaito1877 if charge LED is white - it's not charging, so it's all good.

When you reboot - hardware automatically resets all settings, including charge limit. So limit needs to be applied again when windows boots and either G-Helper or Asus services start. Before that moment laptop will keep charging.

**Comment by Kaito1877** [comment]
So there is no problem if its 99% since its not charging and is white? I am planning on moving abroad to study by the next year so I wanna keep my battery healthy until then, thus the reason I am a bit concerned about whether if I am doing that right. Also I noticed that whenever I limit my battery to 80% or below, a heart sign shows up at the battery icon, any idea if that means it keeps the battery healthy even though it still is 99%?
<img width="308" alt="image" src="https://github.com/user-attachments/assets/21e49f4d-f980-43ed-bd54-da60153bc0b4" />

**Comment by seerge** [comment]
@Kaito1877 

You can manually discharge laptop to 80% and keep it like that. Battery (obviously) won't discharge magically by itself :) If after that laptop stops and doesn't charge above 80% - means limit is working. In general it's better to keep battery on this level for it's longevity, that's why whole thing exists in a first place.

Heart icon is something Asus firmware communicates with windows, so it can "cosmetically" notify about charge limit being in place :)

Thanks

**Comment by Kaito1877** [comment]
I have done it yesterday but when I opened my laptop in the morning, it reached 100% again, so what is the purpose of limiting the battery if I am going to have to decharge it back to <80% every time I open it?

**Comment by seerge** [comment]
@Kaito1877 as I have tried to explain above - most likely something else (Asus services) has overridden charge limit or limit was simply reset during reboot (as it always happens) and was not applied after cause for example didn't log in to windows, so device has started charging again.

You obviously don't have to discharge laptop every single time, cause it won't be charging above if limit is set.

Thanks.

**Comment by Kaito1877** [comment]
Thank you for your Assistance!
