### ISSUE TITLE
Possible strange behavior from apps running on the dGPU not being killed

### ISSUE THREAD

**Issue by hanmangokiwi** [seerge/g-helper#35]
It appears that unlike armory crate which forces you to close apps using the dGPU before killing it for Eco mode, g-helper just turns off the dGPU without closing the applications using it.

While it does work most of the time, I seem to be getting some issues in Firefox, namely on Google Sheets being sluggish and crashing, where I need to restart Firefox if I want it to work properly.

I'm not sure if this is the cause but I am inclined to believe that not restarting the applications is the reason for the strange behaviour.

Is there a way around this? The obvious solution is having an option to kill all applications using the dGPU like on armory crate when switching to Eco mode.

**Comment by seerge** [comment]
It can happen. For example EA launcher can hang when dGPU is plugged off (no idea why launcher uses dGPU in a first place tho).

At the same time, there are lots of apps that handle dGPU off fine, like Chrome and AMD Adrenaline software, all system windows processes, etc.

And while Armory will literally close your Chrome and other apps (usually in a sluggish manual way, and after you click "Stop" button few times), GHelper purposefully doesn't do that, as i see no sense in it. And I rather see it as a benefit :))

If your use case triggers issues, you can always restart app by hand :)

**Comment by hanmangokiwi** [comment]
Ah that makes a lot of sense. I was honestly surprised that GHelper didn't kill any apps and most things (except firefox) seemed to work perfectly.

Would an option to kill certain apps when the laptop is unplugged be a possibility in the future or is that unlikely?

**Comment by seerge** [comment]
I can't predict every scenario - so no :)
