### ISSUE TITLE
Screen reverts to 60hz on battery when 165hz option is selected

### ISSUE THREAD

**Issue by lolKaizen** [seerge/g-helper#350]
**Screen refresh rate has the "Auto" behavior even when not selected**

**Steps to reproduce the behavior:**
1. Unplug laptop
2. Open G-Helper
3. Select 165hz screen option
4. plug and unplug laptop

**Expected behavior:**
Screen refresh rate to be unchanged

**App Logs**
```
5/9/2023 12:48:30 PM: Screen = 165Hz : OK
5/9/2023 12:48:30 PM: ScreenOverdrive = 1 : OK
5/9/2023 12:48:37 PM: WMI event 123
5/9/2023 12:48:38 PM: Windows - Power Mode Changed
5/9/2023 12:48:38 PM: AutoSetting for Online
5/9/2023 12:48:38 PM: PerformanceMode = 1 : OK
5/9/2023 12:48:38 PM: FanCPU = 14-3F-44-46-4C-50-54-62-11-1A-22-45-47-63-63-63 : OK
5/9/2023 12:48:38 PM: FanGPU = 14-3F-44-46-4C-4F-54-62-16-1F-26-44-47-63-63-63 : OK
5/9/2023 12:48:39 PM: GPUEco = 0 : OK
5/9/2023 12:48:40 PM: Eco flag : 0
5/9/2023 12:48:40 PM: Mux flag : -65536
5/9/2023 12:48:40 PM: ScreenOverdrive = 1 : OK
5/9/2023 12:48:43 PM: WMI event 87
5/9/2023 12:48:43 PM: Windows - Power Mode Changed
5/9/2023 12:48:43 PM: AutoSetting for Offline
5/9/2023 12:48:43 PM: PerformanceMode = 2 : OK
5/9/2023 12:48:43 PM: WMI event 123
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - G15 GA503QR

**Comment by seerge** [comment]
@lolKaizen in a log i see only one entry ``5/9/2023 12:48:30 PM: Screen = 165Hz : OK``
So app never tried to set 60hz. 

Most probably you have ASUS Smart Display Control installed, if so - uninstall it :)

**Comment by lolKaizen** [comment]
@seerge yep that was it, how embarrassing. Thanks for the quick reply
