### ISSUE TITLE
support low power mode 

### ISSUE THREAD

**Issue by nicola-lunghi** [seerge/g-helper#3501]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

there's currently no low power mode in the app to lower the CPU and fan and turn off the gpu when on battery

### Describe the solution you'd like

a low power mode setting

### Device and Model

asus rog zephyrus g14

**Comment by seerge** [comment]
@nicola-lunghi hello, 

All modes are [baked in firmware / BIOS](https://github.com/seerge/g-helper?tab=readme-ov-file#rocket-performance-modes). The "low power" mode already exists and is called `Silent`. You can use it and also (optionally) tweak it to your needs.

Thanks.
