### ISSUE TITLE
add page up/down combination with the fn key

### ISSUE THREAD

**Issue by nicola-lunghi** [seerge/g-helper#3502]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

there's no page up and down on this laptop

### Describe the solution you'd like

can you provide a page up and down keyboard combination? and maybe a end / begin key as well

### Device and Model

asus zephyrus g14

**Comment by seerge** [comment]
@nicola-lunghi hello,

Most of `FN+<key>` combinations don't emit any keycodes, so they can not be detected or processed anyhow. 

However on G14 `FN+<arrow keys>` already emit Page Up or Page Down / Home / End keys on hardware / firmware level. If it's not happening in your case (do you have very old G14?) - most likely your device is just too old and does not support that.

Thanks
