### ISSUE TITLE
CPU Temp Limit bug

### ISSUE THREAD

**Issue by Kraska153** [seerge/g-helper#3504]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I return the cpu temperature limit slider to the default value and apply it, it is not reset, but remains at the same level. 

### How to reproduce the bug?

1. Set the temperature limit to 85 for example.
2. Click the apply button.
3. Note that the CPU temperature has decreased.
4. Return the slider to its default value.
5. Click the apply button again.
6. Note that nothing has changed, the limit has not been reset.

### Logs

20.12.2024 0:37:19: MNH301CA3-1 HDR: False 8 4 True
20.12.2024 1:41:29: HID Device Event: Checking for new ASUS Mice
20.12.2024 1:47:32: BatteryLimit = 80 : OK
20.12.2024 14:02:50: ------- Startup Battery Limit 80 -------
20.12.2024 14:02:55: Limit = 80 : OK
20.12.2024 14:02:55: ------------
20.12.2024 14:02:55: App launched: ROG Strix G713PV_G713PV :0.199.0.0ru-RU.
20.12.2024 14:02:55: Start Count: 264
20.12.2024 14:02:58: Stopped: ASUSSmartDisplayControl
20.12.2024 14:02:58: NVIDIA GeForce RTX 4060 Laptop GPU
20.12.2024 14:02:59: CPU: 10 - AMD Ryzen 9 7845HX with Radeon Graphics         - AMD64 Family 25 Model 97 Stepping 2
20.12.2024 14:02:59: AutoSetting for Online
20.12.2024 14:02:59: BatteryLimit = 80 : OK
20.12.2024 14:02:59: Optimization service is running
20.12.2024 14:02:59: Eco flag : 0
20.12.2024 14:02:59: Mux flag : 1
20.12.2024 14:02:59: \\?\DISPLAY#CSO1702#5&32361de0&2&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
20.12.2024 14:02:59: \\?\DISPLAY#CSO1702#5&32361de0&2&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
20.12.2024 14:02:59: MNH301CA3-1 HDR: False 8 4 True
20.12.2024 14:02:59: Mode = 0 : OK
20.12.2024 14:03:00: GET CLOCK LIMIT: 0
20.12.2024 14:03:00: powershell nvidia-smi -lgc 0,2170
20.12.2024 14:03:00: Init 19B6: 5D-B9
20.12.2024 14:03:00: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
20.12.2024 14:03:00: Init 19B6: 5D-05-20-31-00-1A
20.12.2024 14:03:00: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
20.12.2024 14:03:00: AuraMode: AuraRainbow
20.12.2024 14:03:00: USB 19B6: 5D-B3-00-03-FF-FF-FF-E1-00-00-FF-FF-FF-00-00-00-00
20.12.2024 14:03:00: USB 19B6: 5D-B5-00-00-00
20.12.2024 14:03:00: USB 19B6: 5D-B4
20.12.2024 14:03:00: Auto 19B6: 5D-BA-C5-C4-01
20.12.2024 14:03:00: GPU clocks set to "(gpuClkMin 0, gpuClkMax 2170)" for GPU 00000000:01:00.0 All done.
20.12.2024 14:03:00: GET GPU CLOCKS: 0, 0
20.12.2024 14:03:00: SET GPU CLOCKS: 250, 0
20.12.2024 14:03:01: Monitor Power On
20.12.2024 14:03:01: BatteryLimit = 80 : OK
20.12.2024 14:03:01: Lid Open
20.12.2024 14:03:01: Lid 19B6: 5D-BA-C5-C4-01
20.12.2024 14:03:02: PowerLimit C0 (GPU BOOST) = 25 : OK
20.12.2024 14:03:02: PowerLimit C2 (GPU TEMP) = 82 : OK
20.12.2024 14:03:10: ------------
20.12.2024 14:03:11: App launched: ROG Strix G713PV_G713PV :0.199.0.0ru-RU
20.12.2024 14:03:11: Start Count: 265
20.12.2024 14:03:12: Stopped: ASUSSmartDisplayControl
20.12.2024 14:03:12: NVIDIA GeForce RTX 4060 Laptop GPU
20.12.2024 14:03:13: CPU: 10 - AMD Ryzen 9 7845HX with Radeon Graphics         - AMD64 Family 25 Model 97 Stepping 2
20.12.2024 14:03:13: AutoSetting for Online
20.12.2024 14:03:13: BatteryLimit = 80 : OK
20.12.2024 14:03:13: Optimization service is running
20.12.2024 14:03:13: Eco flag : 0
20.12.2024 14:03:13: Mux flag : 1
20.12.2024 14:03:13: \\?\DISPLAY#CSO1702#5&32361de0&2&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
20.12.2024 14:03:13: \\?\DISPLAY#CSO1702#5&32361de0&2&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
20.12.2024 14:03:13: MNH301CA3-1 HDR: False 8 4 True
20.12.2024 14:03:13: Mode = 0 : OK
20.12.2024 14:03:13: GET CLOCK LIMIT: NVAPI_GPU_NOT_POWERED
20.12.2024 14:03:13: powershell nvidia-smi -lgc 0,2170
20.12.2024 14:03:13: Init 19B6: 5D-B9
20.12.2024 14:03:13: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
20.12.2024 14:03:13: Init 19B6: 5D-05-20-31-00-1A
20.12.2024 14:03:13: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
20.12.2024 14:03:13: AuraMode: AuraRainbow
20.12.2024 14:03:13: USB 19B6: 5D-B3-00-03-FF-FF-FF-E1-00-00-FF-FF-FF-00-00-00-00
20.12.2024 14:03:13: USB 19B6: 5D-B5-00-00-00
20.12.2024 14:03:13: USB 19B6: 5D-B4
20.12.2024 14:03:13: Auto 19B6: 5D-BA-C5-C4-01
20.12.2024 14:03:14: MNH301CA3-1 HDR: False 8 4 True
20.12.2024 14:03:14: The current user does not have permission to change clocks for GPU 00000000:01:00.0. Terminating early due to previous errors.
20.12.2024 14:03:14: GET GPU CLOCKS: 250, 0
20.12.2024 14:03:14: Monitor Power On
20.12.2024 14:03:14: BatteryLimit = 80 : OK
20.12.2024 14:03:14: Lid Open
20.12.2024 14:03:14: Lid 19B6: 5D-BA-C5-C4-01
20.12.2024 14:03:15: ------------
20.12.2024 14:03:16: App launched: ROG Strix G713PV_G713PV :0.199.0.0ru-RU.
20.12.2024 14:03:16: Start Count: 266
20.12.2024 14:03:17: NVIDIA GeForce RTX 4060 Laptop GPU
20.12.2024 14:03:18: CPU: 10 - AMD Ryzen 9 7845HX with Radeon Graphics         - AMD64 Family 25 Model 97 Stepping 2
20.12.2024 14:03:18: AutoSetting for Online
20.12.2024 14:03:18: BatteryLimit = 80 : OK
20.12.2024 14:03:18: Optimization service is running
20.12.2024 14:03:18: Eco flag : 0
20.12.2024 14:03:18: Mux flag : 1
20.12.2024 14:03:18: \\?\DISPLAY#CSO1702#5&32361de0&2&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
20.12.2024 14:03:18: \\?\DISPLAY#CSO1702#5&32361de0&2&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
20.12.2024 14:03:18: MNH301CA3-1 HDR: False 8 4 True
20.12.2024 14:03:18: Mode = 0 : OK
20.12.2024 14:03:18: GET CLOCK LIMIT: 2170
20.12.2024 14:03:18: GET GPU CLOCKS: 250, 0
20.12.2024 14:03:18: Init 19B6: 5D-B9
20.12.2024 14:03:18: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
20.12.2024 14:03:18: Init 19B6: 5D-05-20-31-00-1A
20.12.2024 14:03:18: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
20.12.2024 14:03:18: AuraMode: AuraRainbow
20.12.2024 14:03:18: USB 19B6: 5D-B3-00-03-FF-FF-FF-E1-00-00-FF-FF-FF-00-00-00-00
20.12.2024 14:03:18: USB 19B6: 5D-B5-00-00-00
20.12.2024 14:03:18: USB 19B6: 5D-B4
20.12.2024 14:03:18: Auto 19B6: 5D-BA-C5-C4-01
20.12.2024 14:03:18: MNH301CA3-1 HDR: False 8 4 True
20.12.2024 14:03:18: Startup task scheduled: C:\MyFiles\Progs\GHelper\GHelper.exe
20.12.2024 14:03:18: Charge limit task scheduled: C:\MyFiles\Progs\GHelper\GHelper.exe
20.12.2024 14:03:18: GET GPU CLOCKS: 250, 0
20.12.2024 14:03:18: GET CLOCK LIMIT: 2170
20.12.2024 14:03:19: Monitor Power On
20.12.2024 14:03:19: BatteryLimit = 80 : OK
20.12.2024 14:03:19: Lid Open
20.12.2024 14:03:19: Lid 19B6: 5D-BA-C5-C4-01
20.12.2024 14:03:19: Latest version 0.199.0.0
20.12.2024 14:03:19: PowerLimit C0 (GPU BOOST) = 25 : OK
20.12.2024 14:03:19: PowerLimit C2 (GPU TEMP) = 82 : OK
20.12.2024 15:01:08: Display configuration changed.
20.12.2024 15:23:03: Display configuration changed.
20.12.2024 20:02:34: MNH301CA3-1 HDR: False 8 4 True
20.12.2024 20:02:36: GET GPU CLOCKS: 250, 0
20.12.2024 20:02:36: GET CLOCK LIMIT: 2170
20.12.2024 20:02:44: UV: 0 OK
20.12.2024 20:02:45: iGPU UV: 0 
20.12.2024 20:02:50: UV: 0 OK
20.12.2024 20:02:50: iGPU UV: 0 
20.12.2024 20:03:01: MNH301CA3-1 HDR: False 8 4 True
20.12.2024 20:03:03: GET GPU CLOCKS: 250, 0
20.12.2024 20:03:03: GET CLOCK LIMIT: 2170
20.12.2024 20:03:14: UV: 0 OK
20.12.2024 20:03:14: iGPU UV: 0 
20.12.2024 20:03:14: CPU Temp: 85 OK
20.12.2024 20:03:31: MNH301CA3-1 HDR: False 8 4 True
20.12.2024 20:03:33: GET GPU CLOCKS: 250, 0
20.12.2024 20:03:33: GET CLOCK LIMIT: 2170
20.12.2024 20:04:12: MNH301CA3-1 HDR: False 8 4 True
20.12.2024 20:04:15: GET GPU CLOCKS: 250, 0
20.12.2024 20:04:15: GET CLOCK LIMIT: 2170
20.12.2024 20:04:21: UV: 0 OK
20.12.2024 20:04:21: iGPU UV: 0 
20.12.2024 20:06:21: UV: 0 OK
20.12.2024 20:06:21: iGPU UV: 0 
20.12.2024 20:06:21: CPU Temp: 97 OK
20.12.2024 20:06:52: MNH301CA3-1 HDR: False 8 4 True
20.12.2024 20:06:53: GET GPU CLOCKS: 250, 0
20.12.2024 20:06:53: GET CLOCK LIMIT: 2170
20.12.2024 20:07:12: MNH301CA3-1 HDR: False 8 4 True
20.12.2024 20:07:15: GET GPU CLOCKS: 250, 0
20.12.2024 20:07:15: GET CLOCK LIMIT: 2170
20.12.2024 20:09:50: MNH301CA3-1 HDR: False 8 4 True
20.12.2024 20:09:54: GET GPU CLOCKS: 250, 0
20.12.2024 20:09:54: GET CLOCK LIMIT: 2170
20.12.2024 20:12:47: MNH301CA3-1 HDR: False 8 4 True
20.12.2024 20:14:27: GET GPU CLOCKS: 250, 0
20.12.2024 20:14:27: GET CLOCK LIMIT: 2170
20.12.2024 20:19:46: UV: 0 OK
20.12.2024 20:19:46: iGPU UV: 0 
20.12.2024 20:19:47: CPU Temp: 85 OK
20.12.2024 20:19:54: UV: 0 OK
20.12.2024 20:19:55: iGPU UV: 0 
20.12.2024 20:19:55: CPU Temp: 85 OK
20.12.2024 20:21:39: UV: 0 OK
20.12.2024 20:21:39: iGPU UV: 0 
20.12.2024 20:21:43: UV: 0 OK
20.12.2024 20:21:44: iGPU UV: 0 
20.12.2024 20:23:25: UV: 0 OK
20.12.2024 20:23:25: iGPU UV: 0 
20.12.2024 20:23:25: CPU Temp: 97 OK

### Device and Model

Asus Rog Strix G17 G713PV

### Additional information.

Usually my processor runs at a temperature of 95+- under load. I specifically turned on the game in the background and set the slider to 85 first, but even after setting the slider back to default, the temperature did not change. Visually, the slider is in default mode, but I can see from the temperature sensor that nothing has changed.

![Снимок экрана 2024-12-20 203527](https://github.com/user-attachments/assets/d4130306-870e-49be-85ff-7c973310cef6)
![Снимок экрана 2024-12-20 203711](https://github.com/user-attachments/assets/cc98037a-2979-4c96-9c3e-40c36b1784b1)

### Armoury Crate

Uninstalled

### Asus Services

8

### Version

0.199.0

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@Kraska153 hello,

How do you know that it's not set ? I see in the log that everything works as expected, limit is set back to 97C

```
20.12.2024 20:23:25: CPU Temp: 97 OK
```

CPU obviously won't "magically" heat up back to 95C+. As the only thing this setting does - changes throttle temp in AMD "driver" (i.e. after reaching it CPU starts to drop power in order to cool down).

**Comment by Kraska153** [comment]
@seerge
I set 97 degrees manually when testing, when I set the slider to the default value, this line is missing in the logs.

here is an example of what happens in the logs

20.12.2024 23:32:15: UV: 0 OK
20.12.2024 23:32:15: iGPU UV: 0 
20.12.2024 23:32:15: CPU Temp: 90 OK # I set the slider to 90

20.12.2024 23:32:27: UV: 0 OK
20.12.2024 23:32:27: iGPU UV: 0 #I have set the default value here, but there is no line about it.

20.12.2024 23:32:53: UV: 0 OK
20.12.2024 23:32:53: iGPU UV: 0 
20.12.2024 23:32:53: CPU Temp: 90 OK # I set the slider to 90 again.

**Comment by seerge** [comment]
@Kraska153 ok, try this build. 

[GHelper.zip](https://github.com/user-attachments/files/18218213/GHelper.zip)

It will manually set CPU temp limit back to default 96C if a custom (non 96C) limit was applied before. But this will happen only if you drag slider back to `Default` position **without changing mode**.

Keep in mind: each time a performance mode is set (i.e. `Mode = <x>` entry in a log), firmware by itself resets CPU temp limit to defaults. So in this situation there is no need to reset it manually.

Thanks.
