### ISSUE TITLE
ROG G14 2024 - M keys are not functional

### ISSUE THREAD

**Issue by depthso** [seerge/g-helper#3506]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hey guys! I could be doing something terribly wrong here 😥

After installing Ghelper and confirmed there are no Asus services running - checked with G-helper,
the M keys (aka macro keys) are not recognised by G-helper.

On a side note, is it possible to edit the config file to manually set the Input codes for each M key?

### How to reproduce the bug?

I have uninstalled optional asus services (Armory crate and MyAsus) following this guide: 
https://www.youtube.com/watch?v=LFJcNXRPi-s

### Logs

[log.txt](https://github.com/user-attachments/files/18215357/log.txt)

### Device and Model

Asus ROG Zephyrus G14 2024 - GA403UV

### Additional information.

This software is amazing! Simple and easy compared to Armory Crate.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.199.0

### OS

Windows 11 Home 23H2

**Comment by seerge** [comment]
@depthso hello,

Did you bind M1-M4 keys manually in Armoury Crate **prior** to that ? 

Cause for example M1 and M2 (volume keys) work purely on hardware level, and G-Helper is not even involved in that. And I also don't see a single key-press of M3 (event id `124`) and M4 (event id `56`) in the log.

If you did custom bindings in AC before, then need to be reset back to defaults. For that you can either do it in AC (if you still have it) or just do a [hard reset as explained here](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset) (press power button for 40 seconds)

Thanks

**Comment by depthso** [comment]
Heya! Yes I have done this previously but reset their values back to default. Many restarts did not solve the issue BUT, after leaving the laptop in sleep overnight it somehow resolved the issue??!!

I appreciate the support!

**Comment by afiqrosliMk1** [comment]
Hi guys, this just happen to me today. I have tried reinstalling armory but it is still not working. Anyone knows what else to try?

**Comment by seerge** [comment]
@afiqrosliMk1 [hard reset as explained here](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset) (literally in my comment above)
