### ISSUE TITLE
Download Advanced Settings Plugin not functioning

### ISSUE THREAD

**Issue by emjanser** [seerge/g-helper#3509]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

As explained in title, when pressed the indicated button and confirming the administrator command window - the plugin does not get installed and the window stays the same as seen below:

![image](https://github.com/user-attachments/assets/d1692a6f-0d42-4f74-8c74-76b07d29f8ec)

### How to reproduce the bug?

1. Click on Download Advanced Settings Plugin
2. Confirm the administrator command window
3. Click on Download Advanced Settings Plugin again
4. No changes 

### Logs

n/a

### Device and Model

ROG Zephyrus G14 GA403UV_GA403UV

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.199.0

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@emjanser hello, can you upload app logs as it was asked in the issue template ? Thanks

**Comment by emjanser** [comment]
Hi, thanks for the quick response
[log.txt](https://github.com/user-attachments/files/18222291/log.txt)

**Comment by seerge** [comment]
@emjanser it seems something in your system is simply blocking access of the app to github where zip with dll is hosted.

```
22/12/2024 15:49:39: https://github.com/seerge/g-helper/releases/download/v0.150/PluginAdvancedSettings.zip
22/12/2024 15:49:39: C:\Users\emjan\Downloads\GHelper
22/12/2024 15:49:39: PluginAdvancedSettings.zip
22/12/2024 15:49:39: The requested address is not valid in its context. [::ffff:140.82.121.3]:443 (github.com:443) <---- ????
22/12/2024 15:49:39: System.Net.WebException: The requested address is not valid in its context. [::ffff:140.82.121.3]:443 (github.com:443)
 ---> System.Net.Http.HttpRequestException: The requested address is not valid in its context. [::ffff:140.82.121.3]:443 (github.com:443)
 ---> System.Net.Sockets.SocketException (10049): The requested address is not valid in its context. [::ffff:140.82.121.3]:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
--- End of stack trace from previous location ---
```

You can just manually download it https://github.com/seerge/g-helper/releases/download/v0.150/PluginAdvancedSettings.zip and unzip into same folder as GHelper.exe resides (and restart app after as admin)

**Comment by emjanser** [comment]
Turning off my VPN worked

**Comment by seerge** [comment]
@emjanser i'm not sure what exactly does NordVPN has against Github :) but i'm glad it works.
