### ISSUE TITLE
popup warning windows when restart

### ISSUE THREAD

**Issue by Meonthb** [seerge/g-helper#3515]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When "Run on Starup" checked, each time I restart my laptop, Ghelper will popup a windows:
![Screenshot 2024-12-24 163823](https://github.com/user-attachments/assets/e53a0525-db0c-4a7d-b142-dd548c0beacd)

### How to reproduce the bug?

Restart computer.

### Logs

[log.txt](https://github.com/user-attachments/files/18237737/log.txt)

### Device and Model

ROG Zephyrus G14 GA402XV

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.199.0

### OS

Windows 11 24H2

**Comment by seerge** [comment]
@Meonthb hello,

It means app was already launched from (other user?).
Just run G-Helper as admin and uncheck + check `Run on Startup` checkbox. This should re-create task.

Thanks

**Comment by Meonthb** [comment]
Thank you! I have fixed this issue.
