### ISSUE TITLE
Vivobook pro 15 N6506MV Power limits control

### ISSUE THREAD

**Issue by MaxiJazzer** [seerge/g-helper#3521]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

So far, there is no functionality to limit CPU consumption in G-helper

### Describe the solution you'd like

Really need a function to limit CPU consumption in G-helper. Currently, you have to use third-party software called ThrottleStop to do this occasionally. It's clear that the BIOS in VivoBook is quite limited, and even the ThrottleStop functionality is almost completely broken except for one very useful feature: Turbo Power Limits.

The program correctly reads, sets, and limits PL1, PL2, and the Turbo Time Limit settings.

If the "Fans+Power" section of G-helper added this functionality, we could stop using ThrottleStop.

### Device and Model

Asus Vivobook pro 15 N6506MV 185h+rtx4060

**Comment by seerge** [comment]
@MaxiJazzer hello,

G-Helper offers you access to the settings that already exist on your device and are exposed for Amoury (or any other asus software). You never had power limit settings in asus apps - so you won't have them there :)

Thanks.
