### ISSUE TITLE
FA507XI PD charge

### ISSUE THREAD

**Issue by cvixxt** [seerge/g-helper#3522]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When I found that when using PD external charging, ghepler charging showed 79.5%, but windows itself would go back and forth between the charging upper limit of 79 ~ 80%.
After testing, it was found that if you use the original charger to charge, the charging upper limit of 80% will be maintained without the upper limit of 79 ~ 80%.
The effect is shown in the video.
It is currently speculated that charging should be stopped immediately after the external power supply limit reaches 80%. If the battery power is below 80%, power will be supplied immediately. This can cause battery health issues. Please check the situation described in the current situation.
Thank you for reading.

### How to reproduce the bug?

This problem occurs when using a PD external charger to provide 100W charging.

### Logs

[log.txt](https://github.com/user-attachments/files/18244509/log.txt)

### Device and Model

TUF-A15 FA507XI

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.197 & 0.199

### OS

Windows11 24H2

**Comment by cvixxt** [comment]
This video is Used PD Charge's problem.

https://github.com/user-attachments/assets/fb2d808f-926c-4951-895c-a7e773a49bc0

**Comment by seerge** [comment]
@cvixxt hello, 

Your device doesn't have USB-passthrough and never had. When you charge it with USB it will be constantly charging and discharging, either it's 80% or even 100%. This is how your hardware works. 

It has nothing to do with the app.

Thanks.

**Comment by cvixxt** [comment]
Thanks a lot. @seerge
