### ISSUE TITLE
After my anti-malware cleans the registry....

### ISSUE THREAD

**Issue by im6705** [seerge/g-helper#3527]
After my anti-malware cleans the registry, the run and battery charging limit won't work when the system starts up.

**Comment by seerge** [comment]
@im6705 hello,

Charge limit is not stored in the registry. It's set each time you run app.

If you have specific problems please explain it properly [using issue template and include all requested details.](https://github.com/seerge/g-helper/issues/new?assignees=&labels=&projects=&template=bug_report.yml)

Thanks
