### ISSUE TITLE
GPU Mode support for Asus Vivobook Gaming K3605ZF(Asus Vivobook 16X)

### ISSUE THREAD

**Issue by AnkariArisu** [seerge/g-helper#3529]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hello Seerge, i have an ASUS Vivobook 16X but dGPU mode doesn't show on my asus vivobook 16X although TUF Gaming F15 FX506 still show the gpu mode)

### Describe the solution you'd like

Add GPU mode for Asus Vivobook 16X K3605ZF

### Describe alternatives you've considered

nothing else

### Device and Model

ASUS Vivobook 16X K3605ZF

### Additional information.

nothing more i just need the gpu mode

**Comment by seerge** [comment]
@AnkariArisu hello, if you don't see option to set different GPU modes - it simply means your device doesn't support them. Do you have them in MyASUS or any other Asus own app?

**Comment by AnkariArisu** [comment]
i think there is no
![Screenshot 2024-12-28 202626](https://github.com/user-attachments/assets/dcf854c1-3340-46df-a138-b638498aa697)

**Comment by AnkariArisu** [comment]
i only use proart creator hub and stop asus services

**Comment by seerge** [comment]
@AnkariArisu then your device simply don't support them. It's impossible to add things that don't exist in the laptop :) Sorry
