### ISSUE TITLE
Battery Saver Level and Keyboard Brightness Level

### ISSUE THREAD

**Issue by oM0NG0o** [seerge/g-helper#353]
ROG Strix G814JZ

**Describe the bug**
Battery Saver Level Set at 60% continues to Charge to 100% (Log shows set at 60%)
Keyboard Brightness Level Keyboard starts 100% when set to 33%.

Side note: I Notified "Norton" of false flag on your app. (with hex) ;)

**Expected behavior**
Battery would not continue to charge.
Keyboard would be at 33% level.

**App Logs**
5/9/2023 4:35:49 PM: App launched: ROG Strix G814JZ_G814JZ :0.59.0.0
5/9/2023 4:35:50 PM: AutoSetting for Offline
5/9/2023 4:35:50 PM: BatteryLimit = 60 : OK
5/9/2023 4:35:50 PM: BatteryLimit = 60 : OK
5/9/2023 4:35:50 PM: PerformanceMode = 1 : OK
5/9/2023 4:35:50 PM: Eco flag : 0
5/9/2023 4:35:50 PM: Mux flag : 1
5/9/2023 4:35:50 PM: ScreenOverdrive = 0 : OK
5/9/2023 4:35:50 PM: Monitor Power On
5/9/2023 4:37:02 PM: USB-KB = 5D-BA-C5-C4-02
5/9/2023 4:37:03 PM: USB-KB = 5D-BA-C5-C4-01
5/9/2023 4:37:06 PM: USB-KB = 5D-BA-C5-C4-00
5/9/2023 4:37:07 PM: USB-KB = 5D-BA-C5-C4-01
5/9/2023 5:24:24 PM: Windows - Power Mode Changed
5/9/2023 5:24:24 PM: AutoSetting for Online
5/9/2023 5:24:24 PM: BatteryLimit = 60 : OK
5/9/2023 5:24:24 PM: PerformanceMode = 1 : OK
5/9/2023 5:24:24 PM: Eco flag : 0
5/9/2023 5:24:24 PM: Mux flag : 1
5/9/2023 5:24:24 PM: ScreenOverdrive = 0 : OK

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Laptop model

**Asus software**
- Armoury crate  Y
- MyASUS installed Y
- Other Asus services running in background Y

Thanx

**Comment by seerge** [comment]
I believe this is a duplicate from https://github.com/seerge/g-helper/issues/319 

Check  log in ``%appdata/ghelper`` and if you see that app sets charge limit there to 60, it already does everything that can be done here.

Most probably it's some leftowers from asus or bugged battery controller
