### ISSUE TITLE
Full Performance mode

### ISSUE THREAD

**Issue by UX8402ZE** [seerge/g-helper#3532]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hello Seerge,

I've noticed there is a "Full speed mode" in the ProArt Creator app that comes pre installed on my UX8402ZE and all it does is just ping the CPU and GPU fan to full speed. I was wondering if something similar could be added to the mode selection in Ghelper.

### Describe the solution you'd like

A full performance mode or fan full speed mode in the app

### Device and Model

Asus Zenbook Pro 14 Duo UX8402ZE

**Comment by seerge** [comment]
@UX8402ZE hello, I was answering this already in couple of other issues https://github.com/seerge/g-helper/issues/3194 https://github.com/seerge/g-helper/issues/2589

Yyou can set `Full Speed` mode but you need to add it config first

- Create a new custom mode based on Turbo (by pressing + under `Fans+Power`)
- Quit app
- Open `%appdata%\GHelper\config.json` and set following parameter to 3 (it will be 2 there) `"mode_base_3" : 3, `
- Save config, and start app.
