### ISSUE TITLE
Support for ASUS ZenBook Pro 14 OLED

### ISSUE THREAD

**Issue by Yograt** [seerge/g-helper#3537]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

GPU Power Control support for UX6404, I think it will be useful for all UX6404 owners to have Eco or Optimized mode to improve battery life and reliability of their device.

### Describe the solution you'd like

Support for Eco & Optimized GPU Mode

### Describe alternatives you've considered

So far on this  model i had been using the experimental build to control the laptop fans it works great but that build sadly doesn't also has eco and optimized mode ofr my laptop.

### Device and Model

ASUS ZenBook Pro 14 OLED, UX6404VI

### Additional information.

![image](https://github.com/user-attachments/assets/34f028bb-406e-471a-8e14-c8fcc54b3f33)

Additional Information: Enable GPU shutdown option at extra also not available for this model too I believe

**Comment by seerge** [comment]
@Yograt hello,

You can't add settings that don't exist on your device in a first place :) You never had `Eco` mode in MyASUS or any other apps as well.

Sorry. Thanks :)
