### ISSUE TITLE
[Bug] v0.59: NVAPI_INVALID_USER_PRIVILEGE in log, and fans became turned on more often and louder

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#354]
**Describe the bug**
Just got the v0.59. After some use, I see that I'm hearing the fans almost constantly.
Also, getting the NVAPI_INVALID_USER_PRIVILEGE error in the log, when trying to reset fan curves, etc.

Version 0.58 is definitely has less noise and temperature jumps.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11437336/log.txt)

**Desktop (please complete the following information):**
 - Windows 11 22h2
 - ROG Zephyrus G15 GA503QR_GA503QR

**Comment by seerge** [comment]
No, you don't need to manually run as admin

[GHelper.zip](https://github.com/seerge/g-helper/files/11441269/GHelper.zip)

You can try upcoming 0.60 , here I have adjusted some clocking logic, it will try to set clocks only when it's needed from profile settings / etc and if they are different from current clocks. 

But as before - it will ask for admin permissions, only when needed and only if app is not running as admin.

**Comment by seerge** [comment]
@ke1ne is GPU enabled on that moment ?

**Comment by ke1ne** [comment]
> @ke1ne is GPU enabled on that moment ?

No, it's not used in that moment. I know some previous versions activated it to get the temperature. But not now.

**Comment by seerge** [comment]
@ke1ne well, you get that message cause app tried to "read" current GPU clocks (before deciding if it should apply something or not). But since it's not powered, it proceeeded as is. So it's not a "bug", as log is designed for debugging :)
