### ISSUE TITLE
[Feature Request] More keybindings for better control

### ISSUE THREAD

**Issue by coffandro** [seerge/g-helper#357]
Could we please get a CLI(Command Line Interface) for use with autohotkey, stream deck, python or other automation softwares/services?

Personally I think that having a CLI would do wonders for people wanting to automate things or similar.
for example if you wanted to changes performance modes with a physical button YOU COULD DO THAT!

hope you'll consider this option and I'm sorry for disturbing if it turns out it's not possible

**Comment by seerge** [comment]
@coffandro hello, it's not a CLI that you need, as app runs in background, and launching multiple copies of itself with each call is not how it works. What you need is generally more keybindings as i understand for existing features.

**Comment by coffandro** [comment]
yeah that's probably it, if you implement it at some point hope I you remember f13-f24

**Comment by seerge** [comment]
@coffandro what functions do you need to bind? Profiles can be already swiched with Ctrl + Shift + F5 just in case.

**Comment by johnsmith8124** [comment]
Hi, I would love a CLI option to automate profile switching and power limits based on running apps. For example, when on battery and playing indie games, cpu power can be dropped very low but this is not ideal for normal use.

**Comment by seerge** [comment]
@johnsmith8124 as mentioned above (and in readme) profiles (with all settings inside including PPTs) you can switch with FN+F5 or Ctrl + Shift + F5 (for external keyboards)

**Comment by seerge** [comment]
Closing cause author has abandoned topic.

**Comment by coffandro** [comment]
> @johnsmith8124 as mentioned above (and in readme) profiles (with all settings inside including PPTs) you can switch with FN+F5 or Ctrl + Shift + F5 (for external keyboards)

Didn't know that was a feature, that more or less does exactly what I wanted but I just thought something like a CLI would help with better customizability like, for instance, making it easier to make an AHK script or something like that to extend the functionality of G-Helper without blaoting
