### ISSUE TITLE
XG Mobile, Laptop Screen: Turned off

### ISSUE THREAD

**Issue by privacyonly** [seerge/g-helper#359]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
While on XG mobile, g-helper reported that my screen is off.

**Clear scenario to Reproduce**
1. connected to XG mobile
2. open g-helper
3. It will state Laptop Screen: Turned Off(Auto, 60hz, or 120hz button disabled)

**Expected behavior**
It will detect current hz and I can select it.

**App Logs**
5/10/2023 9:11:11 PM: ------------
5/10/2023 9:11:11 PM: App launched: ROG Flow Z13 GZ301ZC :0.60.0.0
5/10/2023 9:11:12 PM: AutoSetting for Online
5/10/2023 9:11:12 PM: PerformanceMode = 0 : OK
5/10/2023 9:11:12 PM: Eco flag : 0
5/10/2023 9:11:12 PM: Mux flag : 1
5/10/2023 9:11:12 PM: Monitor Power On

**Screenshots or screencasts**
https://pasteboard.co/lQnrpVZJBShm.png

**Desktop (please complete the following information):**
 - OS:Windows 11
 - GZ301ZC

**Asus software**
- Armoury crate installed
- MyASUS installed
- Other Asus services running in background

**Additional context**
It can detect hz if XG mobile is not connected.

**Comment by seerge** [comment]
@privacyonly try this build with more verbose logging and post a new log here please
[GHelper.zip](https://github.com/seerge/g-helper/files/11444003/GHelper.zip)

**Comment by privacyonly** [comment]
[log without xg mobile.txt](https://github.com/seerge/g-helper/files/11452707/log.without.xg.mobile.txt)
[log with xg mobile.txt](https://github.com/seerge/g-helper/files/11452709/log.with.xg.mobile.txt)

**Comment by seerge** [comment]
@privacyonly well, from log it's clear that windows is not reporting back to app device IDs, so obviously it can't access anything. I would look into windows / drivers settings and try to find whats causing this.

**Comment by privacyonly** [comment]
> @privacyonly the only thing i can come up with is setting default "DISPLAY1" ID if ID is not returned, but system still sees internal display connected.
> 
> Try this build : [GHelper.zip](https://github.com/seerge/g-helper/files/11454098/GHelper.zip)

Laptop screen is still turned off.

**Comment by seerge** [comment]
@privacyonly then i can't help :) Check what's blockind screen from modifications on your end ;)

**Comment by privacyonly** [comment]
```
$objWMi = get-wmiobject -namespace root\WMI -computername localhost -Query "Select * from WmiMonitorConnectionParams"

foreach ($obj in $objWmi)
{
    write-host "Active:" $obj.Active
    write-host "InstanceName:" $obj.InstanceName
    write-host "VideoOutputTechnology:" $obj.VideoOutputTechnology
    write-host " "
}
```
result
Active: True
InstanceName: DISPLAY\SHP154F\4&264940c8&0&UID8388688_0
VideoOutputTechnology: 2147483648
 
Active: True
InstanceName: DISPLAY\MJI0043\5&20a1b7c7&0&UID4354_0
VideoOutputTechnology: 5

```
UNINITIALIZED         = -2,
OTHER                 = -1,
HD15                  = 0,
SVIDEO                = 1,
COMPOSITE_VIDEO       = 2,
COMPONENT_VIDEO       = 3,
DVI                   = 4,
HDMI                  = 5,
LVDS                  = 6,
D_JPN                 = 8,
SDI                   = 9,
DISPLAYPORT_EXTERNAL  = 10,
DISPLAYPORT_EMBEDDED  = 11,
UDI_EXTERNAL          = 12,
UDI_EMBEDDED          = 13,
SDTVDONGLE            = 14,
MIRACAST              = 15,
internal = other than the above
```
so maybe you can select the internal monitor instead of my avr so that it can detect the active internal display and allow 60hz or 120hz?

**Comment by seerge** [comment]
@privacyonly thats what i did in a build linked here, i have enforced default display
