### ISSUE TITLE
Check ASUS for new drivers

### ISSUE THREAD

**Issue by pettijohn** [seerge/g-helper#362]
**Is your feature request related to a problem? Please describe.**
Since debloating, I don't have MyASUS installed to check for drivers for me. I go to the ASUS support web site and check periodically. Are you interested in G-helper filling this role, notifying end-customers that there are new drivers for their device?

**Describe the solution you'd like**

GET `https://rog.asus.com/support/webapi/product/GetPDBIOS?website=global&model=GA402XY&pdid=22300&cpu=GA402XI&LevelTagId=161533&systemCode=rog` 
GET `https://rog.asus.com/support/webapi/product/GetPDDrivers?website=global&model=GA402XY&pdid=22300&mode=&cpu=GA402XI&osid=52&active=&LevelTagId=161533&systemCode=rog`

The JSON response is a feed of driver releases. 

One idea I have is to simply transform that to ATOM/RSS using [SyndicationFeed ](https://learn.microsoft.com/en-us/dotnet/api/system.servicemodel.syndication.syndicationfeed?view=dotnet-plat-ext-7.0), and self-host my own little service that tells me of new releases. Advantage is I already use a feed reader (miniflux) so have all the capabilities of marking read etc from that app. 

But the better customer experience would be for G-helper to notify the end user. There might be too many permutations of model/pdid/cpu/osid that would make it too complex to try and decipher and construct the needed URI. 

Curious to see if you're interested or have other thoughts.

**Comment by seerge** [comment]
@pettijohn hello, thanks for the tip. Feed looks good, and i can try to add an update checker to the app :)

**Comment by privacyonly** [comment]
https://rog.asus.com/support/webapi/product/GetPDBIOS?website=global&model=GZ301ZC&cpu=

**Comment by Metalogic999** [comment]
This would be fantastic, I don't mind manually installing updates, but it would be very useful to get notifications of them!

**Comment by pettijohn** [comment]
Here's a quick implementation (about 50 lines of code) to produce an Atom feed from the driver & bios JSON. It requires end-users self-host; I have it working with Docker on my local raspberry pi. https://github.com/pettijohn/AsusDriverFeed 

I won't be publicly hosting this as I don't want to hammer Asus from a single IP, nor do I want to harden it for public-facing (error handling, caching, rate limiting, etc etc).

**Comment by seerge** [comment]
@pettijohn @Metalogic999 @Noisrevid @privacyonly 
added in https://github.com/seerge/g-helper/releases/tag/v0.79
