### ISSUE TITLE
Request for auto update feature

### ISSUE THREAD

**Issue by zjr954** [seerge/g-helper#364]
Thanks for the awesome project! 
It would be great if there's an option to update g-helper itself automatically (rather than download from github releases for every version)
Thx again!

**Comment by seerge** [comment]
@zjr954 currently it's intentional :) app checks for updates and proposes to update on each Final release (skipping pre-releases), and there i write down what has changed and do some announcements usually .

**Comment by zjr954** [comment]
I can receive version update notes in g-helper interface, but as I want to keep it as latest as possible, I wonder if it can support a "check periodly" feature, like check if there's a newer final release version every day, and download and replace old version automatically. 
Thanks for the reply btw!

**Comment by hkaancaliskan** [comment]
> 

this can be done via little pop up :)
auto update is a life saver hehe

**Comment by flankytingz** [comment]
> 

You could use the [.bat file](https://github.com/flankytingz/g-helper/blob/patch-1/update.bat) I created and add a task in the task scheduler to run daily/weekly to run bat file, it updates the g-helper automatically to the latest release by default.

Note: .bat file should be in the same directory as GHelper.exe

**Comment by seerge** [comment]
To everyone involved @zjr954 @hkaancaliskan @flankytingz 
I have added experimental auto update. It will show a popup offering to auto install new version on start (if it's available). If you refuse that, your choice will be remembered (in config) till next version. 

You can try a test build (with fake low version, to trigger update) 

[GHelper.zip](https://github.com/seerge/g-helper/files/11482283/GHelper.zip)

**Comment by seerge** [comment]
Pushed this changes as part of v0.63 :)

**Comment by zjr954** [comment]
WOW! Thanks very much for this feature! Wish you all the best!
