### ISSUE TITLE
Laptop keyboard rgb color random

### ISSUE THREAD

**Issue by Chikage0o0** [seerge/g-helper#367]
**Is your feature request related to a problem? Please describe.**
Can‘t set the color of some lighting effects to random in g-helper.
In armoury crate can set the color of some lighting effects to random.

**Describe the solution you'd like**
Add a random option to the color.

**Describe alternatives you've considered**
No

**Additional context**
No.

**Comment by seerge** [comment]
@Chikage0o0 random in sense of chaning ? Then it's called Color Cycle / Rainbow

**Comment by Chikage0o0** [comment]
For single button RGB, some color modes allow random colors. For example, Star mode.
![QQ截图20230512210647](https://github.com/seerge/g-helper/assets/89348590/47bb43b6-b64c-4fa3-b67e-3eff172d62d7)

**Comment by seerge** [comment]
@Chikage0o0 ah, those modes are not baked into hardware but rather emulated via software’s (i.e. armoury constantly sets different colors to keyboard and hogs resource s). I don’t plan to add it, as it’s agains g-helper’s idea of being lightweight:)

**Comment by Chikage0o0** [comment]
> @Chikage0o0 ah, those modes are not baked into hardware but rather emulated via software’s (i.e. armoury constantly sets different colors to keyboard and hogs resource s). I don’t plan to add it, as it’s agains g-helper’s idea of being lightweight:)

These random colors don't seem to be controlled by armoury, even in bios and linux, which can still display random colors.
