### ISSUE TITLE
Extra width on right click context menu

### ISSUE THREAD

**Issue by MrxSiN** [seerge/g-helper#368]
Right click G-Helper on task bar showing context menu with extra width. It has happen on a number of build. Seem nobody report it, does it just me or it was designed to be looking like this?

Screenshot below

![Untitled](https://github.com/seerge/g-helper/assets/3771363/0c5d6a15-7122-4001-a718-328131c119f7)

**Comment by seerge** [comment]
@MrxSiN is it windows 10 ?

**Comment by MrxSiN** [comment]
Windows 11

On Beta Build, if that ever make any different.

**Comment by seerge** [comment]
@MrxSiN i have asked cause for me on win 11 on any scaling it looks ok. May be something in the system affects that looks?

**Comment by seerge** [comment]
@MrxSiN actually, i have changed some settings : check i if it looks better in your conditions ?
[GHelper.zip](https://github.com/seerge/g-helper/files/11465427/GHelper.zip)

**Comment by MrxSiN** [comment]
Much better
![Untitled](https://github.com/seerge/g-helper/assets/3771363/558784dd-82e4-40f8-8c3f-7fc5a8f510d7)

**Comment by seerge** [comment]
Oke, great, I have added this adjustment to 0.61
