### ISSUE TITLE
External monitor detected as built-in

### ISSUE THREAD

**Issue by lucidnx** [seerge/g-helper#37]
Hello! After starting laptop in closed state with external 100Hz monitor connected, GHelper decided that it's my built-in monitor. At least that's what I think according to refresh rate shown on button.
Restarting GHelper without external monitor connected did not helped.
Also switching is not working as you can see on screenshot:
![image](https://user-images.githubusercontent.com/53317668/222310564-5120bb0b-254e-4854-845d-7dade29a3849.png)

**Comment by seerge** [comment]
Yeah, it's indeed can happen when external monitor is the only one, and app thinks it's a laptop :D button should auto-refresh to correct metrics, if you just open app next time when laptop screen will be ON tho

**Comment by lucidnx** [comment]
yes but it actually did not worked until reboot. I think that some asus service has failed

**Comment by lucidnx** [comment]
I have small update. When you start laptop with lid closed so external monitor is detected as internal, on reboot app will show old values and it's grayed out. I had to clean refresh rate from config to fix that.

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/10910341/GHelper.zip)
Can you check this build ?

**Comment by seerge** [comment]
For "clearer" test, please set your laptop screen to max refresh rate before start (as app reads max rate simply from actual state of the screen)

**Comment by lucidnx** [comment]
Will try later, Don't have external monitor by hand now. Is this latest v0.17.0? I see there's mentioned something.

**Comment by lucidnx** [comment]
Seems to be working now, I will watch this fre days just in case.
