### ISSUE TITLE
Add Mapping for All 5 M keys 

### ISSUE THREAD

**Issue by oM0NG0o** [seerge/g-helper#370]
### Strix has 5 M keys 
Only M3 M4 and FN/M4 are mappable in Ghelper

 Addition of  M1 - M5 would be great. 
Mapping keys In Reg. Is a PITA lol.

![asus-rog-strix-g18](https://github.com/seerge/g-helper/assets/132635900/1dc92f65-abf1-4f98-b262-8dc4c7d83b78)

**Comment by seerge** [comment]
@oM0NG0o how do you map them in Reg?

**Comment by oM0NG0o** [comment]
will send all info.
    On Friday, May 12, 2023 at 04:26:26 PM EDT, Serge ***@***.***> wrote:  
 
 


@oM0NG0o how do you map them in Reg?

**Comment by oM0NG0o** [comment]
Hey Seerge,
I use many ways to get key map value. To add to reg its a pita but use. [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout]"Scancode Map"=hex:00,00,00,00,00,00,00,00,02,00,00,00,21,e0,0a,e0,00,00,00,00
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\AppKey\18]"ShellExecute"=""C:\\Program Files (x86)\\Dopamine\Dopamine.exe""

So The P-1 button on my laptop opens a music app instead of bloatware.Normally if no media keys are used that section of reg is empty.The clip is my reg now as you can see there are 5 keys, ugh let's hope they are the right keys. lol    On Friday, May 12, 2023 at 04:51:50 PM EDT, T C ***@***.***> wrote:  
 
  
will send all info.
    On Friday, May 12, 2023 at 04:26:26 PM EDT, Serge ***@***.***> wrote:  
 
 


@oM0NG0o how do you map them in Reg?

**Comment by seerge** [comment]
Ye, but M1-M5 don't produce any scancodes. What you intercept is actually a volume up / down code generated by asus optimization service (that initially handles those hotkeys)

Problem here is to intercept M1,2 you need to completely STOP asus optimization service from working, and without it many other things will break ...

**Comment by oM0NG0o** [comment]
Got ya, No worries I 'll find a work around ;)
    On Friday, May 12, 2023 at 05:50:19 PM EDT, Serge ***@***.***> wrote:  
 
 


Ye, but M1-M5 don't produce any scancodes. What you intercept is actually a volume up / down code generated by asus optimization service (that initially handles those hotkeys)

Problem here is to intercept M1,2 you need to completely STOP asus optimization service from working, and without it many other things will break ...
