### ISSUE TITLE
Each time I update and download G Helper, a unremovable copy is added to "other system tray icos!

### ISSUE THREAD

**Issue by welshkyle123** [seerge/g-helper#371]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

[![image](https://github.com/seerge/g-helper/assets/133467300/c15ae5d0-af01-487d-a779-dd4fbea302df)
](https://imgur.com/Z95UZ5F)**Describe the bug**

you can see a lot of the g helper icons, with no way obvious way to delete them as they are not downloaded and are just exe files.

**Clear scenario to Reproduce**
4. Explanation of an error or a bug

go to taskbar settings then "other system tray icons" in windows 11.
**Expected behavior**

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Laptop model
windows 11. 2022 g15.
**Asus software**
- Armoury crate (or it's services installed)
- MyASUS installed NOT
- Other Asus services running in background

**Additional context**

**Comment by seerge** [comment]
This is a dublicate from https://github.com/seerge/g-helper/discussions/284 

Just download and unzip file into same location, and windows won't create multiple icons in systray settings :)
