### ISSUE TITLE
Control to activate/deactivate RGB lights for new ROG Ally gaming handheld

### ISSUE THREAD

**Issue by hifihedgehog** [seerge/g-helper#372]
**Is your feature request related to a problem? Please describe.**
 The new ROG Ally has two RGB zones. 1. RGB ring on the left joystick. 2. RGB ring on the right joystick. Currently, there is no toggle to select only 1 or 2 zones to light up. The app toggles light for all at once.

**Describe the solution you'd like**
Similar to #326. "A simple check box in extra tab to select the light zones that the user wants to activate. It would be useful if these could be linked with 'plugged in' feature to automatically toggle zone controls when connected to power."

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**
It is still a few weeks yet until release but the above is the information I have so far from the launch reviews and reviewers. I am connecting with some reviewers to see who can contribute in whatever manner possible. Also, I pointed the developers of Handheld Companion to G-Helper which should be useful for them if they opt to add a battery charge limiter as well.

**Comment by seerge** [comment]
@hifihedgehog looks like a topic to brag that you already have hands on Rog Ally :)))

I don't know how the zones are controlled here. If you have device - try to find all USB device IDs for manufacturer ID 0x0b05

**Comment by hifihedgehog** [comment]
> @hifihedgehog looks like a topic to brag that you already have hands on Rog Ally :)))

Haha! Thanks! I wish! I am operating on information I have gathered from those who do have direct access to the Ally like The Phawx. 

> I don't know how the zones are controlled here. If you have device - try to find all USB device IDs for manufacturer ID 0x0b05

I help moderate the r/ROGAlly Discord server who has some reviewers on there who have the Ally in hand. I will drop them a line and report back ASAP!

**Comment by hifihedgehog** [comment]
> try to find all USB device IDs for manufacturer ID 0x0b05

Thanks! What is the best way to filter and output all these USB device IDs to you? I am familiar with manually parsing through Device Manager for information but if there is a quicker way, such as via PowerShell script, that would be preferred.

**Comment by seerge** [comment]
@hifihedgehog https://www.nirsoft.net/utils/usb_devices_view.html this anciently looking app can do the job

**Comment by hifihedgehog** [comment]
> @hifihedgehog [nirsoft.net/utils/usb_devices_view.html](https://www.nirsoft.net/utils/usb_devices_view.html) this anciently looking app can do the job
[USB_Devices_List.zip](https://github.com/seerge/g-helper/files/11491676/USB_Devices_List.zip)
[USB_Devices_List.zip](https://github.com/seerge/g-helper/files/11491682/USB_Devices_List.zip)

That does the tricky quite nicely! Here is what I got from one of the reviewers. Let me know if this does the trick! [USB_Devices_List.zip](https://github.com/seerge/g-helper/files/11491676/USB_Devices_List.zip)

**Comment by seerge** [comment]
@hifihedgehog ok, thanks. I think needed IDs are already in app (that's why it affects both joysticks ) :) How does it works with armoury ? it it separate controls for each joystick ?

**Comment by hifihedgehog** [comment]
> @hifihedgehog ok, thanks. I think needed IDs are already in app (that's why it affects both joysticks ) :) How does it works with armoury ? it it separate controls for each joystick ?

It is one RGB control for both sticks.

**Comment by seerge** [comment]
@hifihedgehog well, what do you expect from g-helper then ? :) it will control it in same way as armoury does, cause this is how it's routed on hardware level
