### ISSUE TITLE
Changing from Eco to Standard bugs brightness

### ISSUE THREAD

**Issue by Carlinho21** [seerge/g-helper#374]
Changing from Eco to standard on GPU mode seems to affect my brightness of my laptop and i can not change it untill i restart my laptop.

This is not a bug from the latest version, i have had it for alittle while.

Asus Rog Strix Scar 18

**Comment by seerge** [comment]
@Carlinho21 this is because Eco mode disables dGPU (Nvidia in your case) that was drving display probably, and then intel iGPU drives it.  

Windows thinks it's a new screen and has a separate brightness slider. Just set brightness again after setting Eco, and windows should remember it.

I assume same happens when you set Eco in AC? :)

**Comment by Carlinho21** [comment]
It happens changing from Eco to standard not standard to Eco. Brightness can not be adjusted at all when i do this until i restart the laptop. I did not have this issue with Armoury Crate either. G-helper is awesome though and i will not be going back to AC lol.

**Comment by seerge** [comment]
What setting does Optimus have on Standard before going eco and after?

**Comment by Carlinho21** [comment]
I have it on Automatic

**Comment by seerge** [comment]
Well, try to change something there after you set Standard, does it affect your brightness?

What you can also do - is to ‘reload’ video driver in windows by pressing ctrl + shift + win + B

**Comment by Carlinho21** [comment]
I tried these and it didnt fix anything, but i did figure out why it does it. Its when my laptop boots up in Eco mode. When it boots up in standard mode i can change as much as i want with no issues to brightness. And it changes mode much quicker when booted up in standard too.

**Comment by seerge** [comment]
I would assume when you boot into Eco (i.e. Nvidia is completely off and invisible) your windows don't even load nvidia drivers, and when you enable dGPU (standard) it just doesn't know what to do :)

**Comment by Carlinho21** [comment]
Ok, ill just make sure not to shutdown on Eco. Thanks for the help and awesome job on G-helper :)
