### ISSUE TITLE
Keyboard Lighting broken on 0.61

### ISSUE THREAD

**Issue by zeroeightythree** [seerge/g-helper#378]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
Keyboard lighting controls seem to be broken on 0.61. 

**Clear scenario to Reproduce**
1. Go to Laptop Keyboard section of app
2. Click on dropdown and or color picker and select a preset
3. Lighting does not change

**Expected behavior**
Lighting colors change based on selected preset and/or color

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``

**Screenshots or screencasts**
- N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - G15 2022 GA503RW

**Asus software**
- Armoury crate (disabled)
- MyASUS installed but debloated
- Debloated

**Additional context**
[log.txt](https://github.com/seerge/g-helper/files/11471344/log.txt)

**Comment by seerge** [comment]
@zeroeightythree hello, in a log i don't see any atttempts to set backlight modes, but see that you also launched v0.58 and v0.60. Does keyboard work there, or in older versions?

**Comment by seerge** [comment]
@zeroeightythree P.S. On a side note, yesterday it was an issue with keyboard device not being detected if windows is not in english : https://github.com/seerge/g-helper/discussions/376 could it be your case too ? try last build from that thread

**Comment by zeroeightythree** [comment]
I tried switching light modes but somehow did not get captured in log. I rolled back to 0.58 and the light modes work with no changes made to any of my windows settings. I am running Windows in English as it is my primary language. It seems from v 0.60 onward, the backlight mode broke.

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11471385/GHelper.zip)
ok, can you check this build ? and post a log agian :)

**Comment by zeroeightythree** [comment]
Just tried but same result, lights not changing when selecting a preset.
[log.txt](https://github.com/seerge/g-helper/files/11471392/log.txt)

**Comment by seerge** [comment]
@zeroeightythree oke, can you try this one and post log again ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/11471396/GHelper.zip)

**Comment by zeroeightythree** [comment]
That fixed it. Awesome! Thank you.
[log.txt](https://github.com/seerge/g-helper/files/11471400/log.txt)

**Comment by seerge** [comment]
@zeroeightythree good, can you check if this one still works ? (i have adjusted criterias to find keyboard, and now it has found 3 in your case ... which was too much)

[GHelper.zip](https://github.com/seerge/g-helper/files/11471415/GHelper.zip)

**Comment by zeroeightythree** [comment]
Seems to be working fine. :)
[log.txt](https://github.com/seerge/g-helper/files/11471426/log.txt)

**Comment by seerge** [comment]
Oke, thanks! I will push it live with 0.62 then

**Comment by zeroeightythree** [comment]
Awesome! Thank you. Will close the ticket.
