### ISSUE TITLE
Aura Manager

### ISSUE THREAD

**Issue by tonyG433** [seerge/g-helper#380]
**Is your feature request related to a problem? Please describe.**
Being able to tweak your system without heavy apps like Armory Crate is amazing, however I would like the lighting on my mouse to be synced with my keyboard.

**Describe the solution you'd like**
An Aura extension that allows you to manage multiple Aura-compatible devices, entirely through G-helper

**Describe alternatives you've considered**
I've tried openRGB but I just cant get it to sync my mouse and keyboard

**Comment by seerge** [comment]
@tonyG433 hello, currently i don't plan that, as i don't have any asus pripherials + they are controlled in a different way from built in lights.
