### ISSUE TITLE
Clock function for the Anime Matrix is not displaying properly in G14 GA401IV

### ISSUE THREAD

**Issue by JavierFunes** [seerge/g-helper#382]
**Describe the bug**
Clock function for the Anime Matrix is not displaying properly in G14 GA401IV. 

**Screenshots or screencasts**

![WhatsApp Image 2023-05-15 at 09 50 30 (2)](https://github.com/seerge/g-helper/assets/38080342/3090fb81-0cbd-4eab-b763-a8b403bcb9a0)

Other modes display properly:

![WhatsApp Image 2023-05-15 at 09 50 29](https://github.com/seerge/g-helper/assets/38080342/71ca07df-3012-4f3d-8e50-2e749516c8e8)

![WhatsApp Image 2023-05-15 at 09 50 30](https://github.com/seerge/g-helper/assets/38080342/af5bde49-e414-4c15-8015-28fc1f679544)

Correct behaviour with past release (I think it was 0.58)

![WhatsApp Image 2023-05-15 at 10 03 27](https://github.com/seerge/g-helper/assets/38080342/472a94a5-27b4-4305-b326-5ee5ffd0a743)

**Desktop (please complete the following information):**
 - OS: W11
 - G14 GA401IV
 - GHelper version: 0.62

**Comment by JavierFunes** [comment]
I believe so!

<img width="960" alt="image" src="https://github.com/seerge/g-helper/assets/38080342/81f3eeed-4eb1-461f-97c9-c43b53c7ab04">

**Comment by seerge** [comment]
@JavierFunes does this version look ok ?
[GHelper.zip](https://github.com/seerge/g-helper/files/11476543/GHelper.zip)

**Comment by seerge** [comment]
@JavierFunes i love old models and blind style of development, when you don't have a device :))

Try this one 
[GHelper.zip](https://github.com/seerge/g-helper/files/11476716/GHelper.zip)

**Comment by JavierFunes** [comment]
Bingo! I attached two images because the ":" flashes, I don't know if it's intentional, and I don't remember how it worked before. The new font looks nice!
 
![WhatsApp Image 2023-05-15 at 12 34 13](https://github.com/seerge/g-helper/assets/38080342/18b3a8da-1e3c-4264-bd6d-a2f3470b7896)

![WhatsApp Image 2023-05-15 at 12 34 21](https://github.com/seerge/g-helper/assets/38080342/c32fdbe3-1e2e-4c8e-b439-326d49786a17)

**Comment by seerge** [comment]
@JavierFunes yes, it's intentional to indicate seconds :)) (and was so in old versions too). I will set old style of clock for old laptops, but keep new for 2022+ models, where screen is bigger and easier to manage :)
