### ISSUE TITLE
Touchpad does not turn off in when folding flow device into tablet mode

### ISSUE THREAD

**Issue by l0lGhostlxl** [seerge/g-helper#383]
**Describe the bug**
I have deleted Armoury Crate and have disabled all services that were listed safe to disable. But I have encountered a bug where when I fold my laptop where the keyboard correctly turns off but the touchpad stays turned on when it should be off.

**Clear scenario to Reproduce**
1. Fold laptop beyond 180 degrees
2. Try touching the touchpad
3. Mouse will appear and show that it is not disabled 
4. Can be counteracted by disabling the touchpad before folding although this is cumbersome

**Expected behavior**
When laptop is folde beyond a 180 degrees it should turn off the touchpad 

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11475740/log.txt)

**Screenshots or screencasts**
N/A

**Desktop (please complete the following information):**
 - OS: Edition	Windows 11 Home
Version	22H2
Installed on	‎20/‎03/‎2023
OS build	22621.1702
Experience	Windows Feature Experience Pack 1000.22641.1000.0

 - Laptop model
Device name	Flow
Processor	AMD Ryzen 9 6900HS with Radeon Graphics           3.30 GHz RTX 3070 TI

**Asus software**
- MyASUS installed
- ASUS services that are required are enabled
- Only services that are disabled are: Armoury crate control interface, ASUS link near, ASUS link remote, ASUS switch

**Additional context**
N/A

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11481960/GHelper.zip)
Try this one, and post log here please :)

**Comment by l0lGhostlxl** [comment]
This one works great thank you, here are the logs below 
[log.txt](https://github.com/seerge/g-helper/files/11484107/log.txt)

**Comment by seerge** [comment]
Great, i will release this in 0.63
