### ISSUE TITLE
The overclock feature does not work for the lower version laptop(5800H +3070)

### ISSUE THREAD

**Issue by SuperDante2022** [seerge/g-helper#389]
I can see the power adjustment feature working on others.
![image](https://github.com/seerge/g-helper/assets/133739075/fa8442bd-06a9-440b-8c0a-097592dafdc7)

but for me, it shows nothing:
![image](https://github.com/seerge/g-helper/assets/133739075/c296e66f-da2e-4cc4-abf9-184d83d1a449)

My model is FA506QR, could you please release the power adjustment feature on this model?

Thanks a lot!

**Comment by seerge** [comment]
@SuperDante2022 adjust a log so i can look at it at least, but with a good chance it's not supported there :)

**Comment by SuperDante2022** [comment]
My bad, I turned on my dGPU and at least the frequency can be adjusted. Guess power limit cannot be adjusted for my model.

Thanks!
