### ISSUE TITLE
Battery Charge Limit Not Working

### ISSUE THREAD

**Issue by Harishrao13** [seerge/g-helper#39]
The battery charge limit feature is not functioning, it also **overrides** my "MyAsus" app battery charge limitations and charges battery to 100%.

**Comment by seerge** [comment]
Great, but i don't have a prophet skills to discover the rest. What laptop do you have ?

**Comment by Harishrao13** [comment]
Zephyrus G-15 2022

**Comment by Dean084** [comment]
> Zephyrus G-15 2022

Battery charge limit works as intended on my G15 2022.

**Comment by seerge** [comment]
That's strange, as for g15 it should work. 
Alternatively you can try to run following as admin in powershell (where 80 is your desired limit). 

It's the same call myasus and ghelper does

` Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00120057; Control_status=80}`
