### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by lswlc33** [seerge/g-helper#393]
like this:

`big blank` is shown in this **page**

![image](https://github.com/seerge/g-helper/assets/86835895/1f4b0cc2-a1a9-4dcb-aeed-947bd64827c3)

```
2023/5/16 20:52:56: ------------
2023/5/16 20:52:56: App launched: ASUS TUF Gaming F15 FX506HC_FX506HC :0.63.0.0
2023/5/16 20:52:56: NVAPI_API_NOT_INITIALIZED
2023/5/16 20:52:56: AutoSetting for Offline
2023/5/16 20:52:56: BatteryLimit = 100 : OK
2023/5/16 20:52:56: BatteryLimit = 100 : OK
2023/5/16 20:52:56: PerformanceMode = 0 : OK
2023/5/16 20:52:56: Eco flag : 1
2023/5/16 20:52:56: Mux flag : -65536
2023/5/16 20:52:56: ScreenOverdrive = 1 : OK
2023/5/16 20:52:56: TUF Brightness = 128 : OK
2023/5/16 20:52:56: Monitor Power On

```

**Comment by seerge** [comment]
I assume it was empty for you before as well, right ?

try this one

[GHelper.zip](https://github.com/seerge/g-helper/files/11488153/GHelper.zip)

**Comment by lswlc33** [comment]
> I assume it was empty for you before as well, right ? try this one
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/11488153/GHelper.zip)
> 
> It's because of Eco mode, and dGPU is not available : `2023/5/16 20:52:56: NVAPI_API_NOT_INITIALIZED`
> 
> In standard mode (when dGPU is enabled) it should still show clock sliders for GPU

perfect!
