### ISSUE TITLE
Please, add support for Asus Rog Ally

### ISSUE THREAD

**Issue by xatanu** [seerge/g-helper#398]
As the subject reads, it would be great if you could add support for the Asus ROG Ally.
Thank you so much

**Comment by seerge** [comment]
@xatanu support in what sense ? profile switches and fan curves probably will work (as they are same on all asus systems)

**Comment by xatanu** [comment]
That's great, I thought it only worked for TUF and ROG laptops. I will test it as soon as I receive my Ally unit and remove all the bloat from it.
Thank you so much
