### ISSUE TITLE
UI Additions/Modifications

### ISSUE THREAD

**Issue by IanFluidd** [seerge/g-helper#400]
Hi there, I was hoping you would consider making some minor UI changes to the Ghelper interface.

1: I would love the option to be able to see CPU and GPU utilisation and average core frequency next to where the temp and fan speed is currently shown. I understand that this may cause it to look a little cluttered for some people so I think the option to enable or disable which of these four elements (cpu/gpu utilisation, frequency, fan speed, temperature) are shown could be added in the extras tab. Perhaps enabled by checkboxes?

2: I would also really appreciate if you could substantially increase the polling rate of the battery discharge, as it currently seems very slow to update. 

Thank you for all the work you have already put into this, and I would greatly appreciate if you would consider implementing these changes.

**Comment by seerge** [comment]
@IanFluidd hello,

1. I'm not a big fan of adding utilization / frequencies to UI, as it is already cluttered + reading bunch of extra sensors will make app consume more resources. After all there is dedicated and specialized apps for monitoring, like hwinfo that do it way better :) + have charts , alerts , etc.

2. Polling rate for battery is same as for the rest (2 seconds). If you have G14 - It's just a battery sensor itself being very slow there (cause it seem to be a moving average of all readings for last 30 seconds or so). On G16 for example, sensor is super responsive :)

**Comment by IanFluidd** [comment]
I understand your reasoning and thank you for taking the time to explain this. I have a G15 but the battery behaiour is exactly as you describe it for the G14.
