### ISSUE TITLE
GPU reenables when inserting type-c charger even though option is enabled in extra

### ISSUE THREAD

**Issue by bloodup12** [seerge/g-helper#406]
**Describe the bug**
Hello,

First of all, I am really thankful for what you are giving a second alternative for armoury crate :) I have seen your new option "Keep GPU disabled on USB-C Charger in optimized mode" and I really liked it. However, when I try this option, my GPU pops up in task manager even though it is not supposed to do.

To simulate this issue, I have completed following steps:

1:  In G-Helper, my settings are like this:

![image](https://github.com/seerge/g-helper/assets/74018770/48ed94ba-44ef-4a2f-a5aa-13971d3a6c94)

As you can see, GPU is deactivated right now, even in task manager.

![image](https://github.com/seerge/g-helper/assets/74018770/47e5c351-2440-4999-8811-b13642b87f08)

2:  When I plug my 100 W USB-C charger, my gpu is reactivated and I can see it in task manager as well.

![image](https://github.com/seerge/g-helper/assets/74018770/58bc2095-322a-4f3a-a915-fe7c16e2c594)

![image](https://github.com/seerge/g-helper/assets/74018770/6752ab3d-6588-479a-b636-2acd84d3910e)

However, when I try to run some GPU required programs, its usage is not increasing and staying at %0. But, it's fan speeds are getting higher as if it runs heavy tasks. You can see it below:
![image](https://github.com/seerge/g-helper/assets/74018770/8414d7a5-c30a-4eac-b19c-32ee73c33e59)

**Expected behavior**
What I expect is that I should not see my GPU is activated in task manager and as well as in G-Helper. It should  stay in the same condition which can be seen in my first image.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11503255/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - ASUS ROG  2021 G513QE
 - G-Helper Version :0.63.0.0

**Asus software**
- Armoury crate was uninstalled
- MyASUS installed
- Other Asus services running in background

**Comment by seerge** [comment]
@bloodup12 hello, it could be that on your model, laptop can't report separately if it's on usb-c or barrel charger (so it acts like it's on barrel charger)

Can you run following command in powershell (as admin) and post ouput here ?
a) when on usb-c charger
b) when on barrel charger

```(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DSTS(0x0012006C)```

**Comment by bloodup12** [comment]
Hi,

 I was out of town. Sorry for late reply. I run the command you requested. 

a) usb-c charger
![image](https://github.com/seerge/g-helper/assets/74018770/d77c3647-3566-463a-a69c-c311db48f0d0)


b) barrel charger
![image](https://github.com/seerge/g-helper/assets/74018770/9b774763-111b-417e-9b5a-124876ef474a)

**Comment by seerge** [comment]
@bloodup12 oke, looks like your laptop reports USB charger in a different way.
Try this build, that should accomodate that : 
[GHelper.zip](https://github.com/seerge/g-helper/files/11537492/GHelper.zip)

**Comment by bloodup12** [comment]
Hi again,

I have just tried the new version you sent me, it works flawlessly. Thank you so much!
