### ISSUE TITLE
Fan presets and windows Power plan auto change

### ISSUE THREAD

**Issue by lucidnx** [seerge/g-helper#41]
I have small request.. can you make option to save fan presets? maybe simple export import, I am from time changing curve to optimize it and I would like to have option to revert previous state. now I have to open appdata and copy lines containing temperature mapping.

Another one is if you can implement power plan switching when performance mode is changed. Now I am using separate app and must go to 2 apps to switch modes and well I forget to change it sometimes. QOL thing...

**Comment by seerge** [comment]
1. you can write a powershell or bat file to copy config to convenient location, that would do a thing
2. power plan switching is not in my plans at the moment

**Comment by lucidnx** [comment]
well, if power limits will be tested and working, can it be saved and applied just like fan speeds? it will then allow me to skip all plans and just use "optimized" plan with small tweaks then.
I am limiting CPU performance with power plans and well that's kinda sketchy because it does not necessarily means lower TDP...

**Comment by seerge** [comment]
yes, if PPTs will work as they should on 2021 models i will add auto-apply, at the moment it's still experimental
