### ISSUE TITLE
Timeout for backlight not working

### ISSUE THREAD

**Issue by lucidnx** [seerge/g-helper#411]
**Describe the bug**
Setting keyboard backlight timeout does not work

**Clear scenario to Reproduce**
1. Set timeout value
2. accept UAC prompt
3. wait specified time
4. nothing

**Expected behavior**
turn off backlight in specified time

**App Logs**
```
18. 5. 2023 23:07:31: PowerLimit A3 = 125 : OK
18. 5. 2023 23:07:31: PowerLimit B0 = 80 : OK
**18. 5. 2023 23:20:22: Requested registry access is not allowed.**
18. 5. 2023 23:20:22: ------------
18. 5. 2023 23:20:22: App launched: ROG Zephyrus G14 GA402RK_GA402RK :0.63.0.0A
**18. 5. 2023 23:20:22: Unable to load DLL 'nvapi64' or one of its dependencies: The specified module could not be found. (0x8007007E)**
**18. 5. 2023 23:20:22: AutoSetting for Online**
18. 5. 2023 23:20:22: BatteryLimit = 90 : OK
18. 5. 2023 23:20:22: BatteryLimit = 90 : OK
18. 5. 2023 23:20:22: PerformanceMode = 0 : OK
18. 5. 2023 23:20:22: FanCPU = 1E-31-3B-45-4F-59-63-6D-00-05-0F-19-41-55-63-63 : OK
18. 5. 2023 23:20:22: FanGPU = 1E-31-3B-45-4F-58-63-6D-00-00-05-1C-45-56-63-63 : OK
18. 5. 2023 23:20:22: Boost 3
18. 5. 2023 23:20:23: Eco flag : 0
18. 5. 2023 23:20:23: Mux flag : 1
18. 5. 2023 23:20:23: USB-KB 0x19B6:5D-BA-C5-C4-03
18. 5. 2023 23:20:23: Matrix GIF C:\path...
18. 5. 2023 23:20:23: Monitor Power On
18. 5. 2023 23:20:23: PowerLimit A0 = 125 : OK
18. 5. 2023 23:20:23: PowerLimit A3 = 125 : OK
18. 5. 2023 23:20:23: PowerLimit B0 = 80 : OK
18. 5. 2023 23:30:28: WMI event 123
18. 5. 2023 23:30:29: WMI event 207
18. 5. 2023 23:30:29: WMI event 207
18. 5. 2023 23:30:30: WMI event 123
18. 5. 2023 23:30:31: WMI event 87
18. 5. 2023 23:30:31: Windows - Power Mode Changed
**18. 5. 2023 23:30:31: AutoSetting for Offline**
18. 5. 2023 23:30:31: BatteryLimit = 90 : OK
18. 5. 2023 23:30:31: PerformanceMode = 2 : OK
18. 5. 2023 23:30:32: FanCPU = 1E-31-3B-45-4F-59-63-6D-00-00-05-0F-28-4B-63-63 : OK
18. 5. 2023 23:30:32: FanGPU = 1E-31-3B-45-4F-59-63-6D-00-00-0A-19-2D-4B-63-63 : OK
18. 5. 2023 23:30:33: Boost 0
18. 5. 2023 23:30:33: GPU usage: AMD Radeon RX 6800S 0%
18. 5. 2023 23:30:33: USB-KB 0x19B6:5D-BA-C5-C4-00
18. 5. 2023 23:30:33: Matrix Off
18. 5. 2023 23:30:41: GPUEco = 1 : OK
18. 5. 2023 23:30:41: PowerLimit A0 = 30 : OK
18. 5. 2023 23:30:41: PowerLimit A3 = 30 : OK
18. 5. 2023 23:30:41: PowerLimit B0 = 20 : OK
18. 5. 2023 23:30:41: Eco flag : 1
18. 5. 2023 23:30:41: Mux flag : 1
18. 5. 2023 23:30:41: Screen = 60Hz : OK
18. 5. 2023 23:30:41: ScreenOverdrive = 0 : OK
18. 5. 2023 23:30:50: USB-KB 0x19B6:5D-BA-C5-C4-00
18. 5. 2023 23:30:50: USB-KB 0x19B6:5D-BA-C5-C4-01
```

**Desktop (please complete the following information):**
 - Win11 22H2
 - GA402RK-L8150W

**Asus software**
- Armoury crate never installed
- MyASUS never installed
- All services disabled except optimization

**Additional context**
Maybe you can add feature to set timeout on charger too? I am keeping laptop on over night and it's just nonstop lit up.

**Comment by seerge** [comment]
@lucidnx it's controlled by asus optimization service :) it seem to pick up registry setting after some time, or try to relaunch it

**Comment by lucidnx** [comment]
argh I hate ASUS devs... such a piece of....
I guess we need to replace asus optimization..
What else is that service doing?

**Comment by seerge** [comment]
@lucidnx handles all hotkeys except FN +f4/f5, m3,m4.

**Comment by lucidnx** [comment]
and that's all? somebody else mentioned also camera switch and some other stuff. + it is putting my computer to sleep while closed and playing games, so.. There's even more I think..

**Comment by seerge** [comment]
@lucidnx what is "camera switch" ? i probably does more, but from usefull things - only hotkeys

**Comment by lucidnx** [comment]
I am trying to disassemble it with IDA, got some results but I am not sure what I am looking at :))
![image](https://github.com/seerge/g-helper/assets/53317668/6f83bd5a-94eb-45fa-a1d2-993a9bc43150)

**Comment by lucidnx** [comment]
![image](https://github.com/seerge/g-helper/assets/53317668/89d65e36-cd46-41fb-8e27-3be09e404066)

**Comment by seerge** [comment]
@lucidnx i think -  it's settings for other laptops. If you will open Regedit and check ``Computer\HKEY_LOCAL_MACHINE\SOFTWARE\ASUS\ASUS System Control Interface\AsusOptimization\ASUS Keyboard Hotkeys`` you will see lots of them, but from my tries - none had any effect :) (except backlight timeout)

**Comment by lucidnx** [comment]
Sure, it's universal for most laptops, but I think that there's more it is doing on G14. I am have asked some devs to look at that service.

**Comment by figarro** [comment]
> Author

You are right. And I thought I discovered something smart :)

**Comment by seerge** [comment]
Oke, I'm closing this "issue" for now. 

As currently app users "asus optimization service" for backlight timeouts, and it sets registry value correctly. The rest is out of control :) (unless I will re-create whole service in house eventually)
