### ISSUE TITLE
Retain same level of power draw as battery on usb c charging

### ISSUE THREAD

**Issue by hanmangokiwi** [seerge/g-helper#416]
**Is your feature request related to a problem? Please describe.**
I use usb-c charging on my power bank for the laptop often, but a large issue is that the moment the device is plugged, it starts drawing much more power. It can go from drawing 7w unplugged to something crazy like 30w when plugged in using usb-c, which is not ideal since my power bank has limited capacity

**Describe the solution you'd like**
I am unsure if this is even possible but it would be nice if there was a setting to make it so the laptop doesn't draw additional power when connected via usb-c.

**Describe alternatives you've considered**

**Additional context**

**Comment by seerge** [comment]
If you are on Optimized/Standard mode your dGPU turns on and starts drawing power.

Either set GPU to Eco all the time, or go to Extra -> "Keep GPU disabled on usb-c" to keep it off.

Besides that, there is nothing that programmatically can be done :) it depends on your hardware / bios.
