### ISSUE TITLE
[Question] Info on extra RGB controls for TUF models.

### ISSUE THREAD

**Issue by BasselMalek** [seerge/g-helper#417]
Model: Asus TUF Gaming F15 (FX506HEB).
OS: Windows 10 21H2

Hey! 
First, I wanted to say thank you for the great software, much better and more efficient than Armory Crate. Now, I had a technical question as I noticed the RGB controls in the app are identical to the ones in AC and in the code you remove certain modes and alter functions when it comes to TUF models. I was just wondering whether that is for the sake of creating a faithful recreation of the controls in AC and more advanced features being out of scope, or is it due to hardware limitations on these specific models.
Again, cheers for the awesome software!

**Comment by seerge** [comment]
@BasselMalek other modes are not supported on TUF, therefore app hides them from UI
