### ISSUE TITLE
Only show "GPU Mode: iGPU" for models that do not have a dGPU

### ISSUE THREAD

**Issue by krystean** [seerge/g-helper#419]
I'm using G-Helper on an ASUS laptop that does not have a dGPU and it works really well! With the release of v0.65, we're finally free from MyASUS. Thank you!

For devices that do not have a dGPU, can you please just show iGPU on the GPU Mode section and remove the buttons?

**Comment by seerge** [comment]
@krystean what does running following command in powershell (as admin) get you : 

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DSTS(0x00090020)

```

**Comment by krystean** [comment]
I ran it as admin and here's the output:

```
__GENUS          : 2
__CLASS          : __PARAMETERS
__SUPERCLASS     :
__DYNASTY        : __PARAMETERS
__RELPATH        :
__PROPERTY_COUNT : 1
__DERIVATION     : {}
__SERVER         :
__NAMESPACE      :
__PATH           :
device_status    : 4294967294
PSComputerName   :
```

**Comment by seerge** [comment]
@krystean ok, and what's your model name ?

**Comment by krystean** [comment]
On Settings/System and HWiNFO64, it says VivoBook_ASUSLaptop X515UA_M515UA

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11548408/GHelper.zip)
You may check this build

**Comment by krystean** [comment]
Thank you! I installed v0.69 and while the buttons are gone, the GPU Mode section title(?) is still showing. If possible, can you also please remove the GPU under the CPU temp and fan in the tooltip? Thanks again!

<img width="316" alt="image" src="https://github.com/seerge/g-helper/assets/66447871/0f357bf9-a698-4d79-becd-36cd759e2c87">

**Comment by seerge** [comment]
@krystean i didn't know you don't have a second (GPU) fan at all. Try this one

[GHelper.zip](https://github.com/seerge/g-helper/files/11559404/GHelper.zip)

**Comment by krystean** [comment]
Only one fan unfortunately lol Thank you, only relevant settings/info for my laptop model shown now!

<img width="310" alt="image" src="https://github.com/seerge/g-helper/assets/66447871/b13f5c0f-3c17-4608-8aaa-b551fdd6cd88">
