### ISSUE TITLE
[Feature Request] Rebind Aura Hotkey for non RGB model

### ISSUE THREAD

**Issue by MrxSiN** [seerge/g-helper#42]
As the title said. It would be nice if the list of the binding got expanded such as screenshot. 

M3 OSD could be change or not?

**Comment by seerge** [comment]
I have added print-screen key imitation (i think it copies screenshot to clipboard by default in windows) and binding for fn+f4
https://github.com/seerge/g-helper/releases/tag/v0.15.1
