### ISSUE TITLE
[Bug] Inconsistent character separation in Fans + Energy between modes

### ISSUE THREAD

**Issue by marcelomijas** [seerge/g-helper#420]
**Describe the bug**
Character separation of the word _Fans:_ (Ventiladores:) at the _Fans + Energy_ window is greater when _Balanced Mode_ (Equilibrado) is selected. Now, when the _Balanced Mode_ (Equilibrado) is selected, text, won't fit (see images). Affected versions: v0.64 and v0.65

Seems that only the first three characters are affected...

**Clear scenario to Reproduce**
This happens when Windows language is set to Spanish (Spain) idk if others are affected.
1. With G-Helper v0.64-v065, open the _Fans + Energy_ window.
2. Change between _Balanced_ and any other mode
3. Text at the left of CPU Boost should have different character spacing between modes (problem).

**Expected behavior**
Character separation should be constant between modes, like in v0.63.

**App Logs**
```
21/05/2023 2:30:50: ------------
21/05/2023 2:30:50: App launched: ROG Zephyrus G14 GA401IV_GA401IV :0.63.0.0
21/05/2023 2:30:50: AutoSetting for Online
21/05/2023 2:30:50: BatteryLimit = 60 : OK
21/05/2023 2:30:50: BatteryLimit = 60 : OK
21/05/2023 2:30:50: PerformanceMode = 0 : OK
21/05/2023 2:30:50: FanCPU = 14-1E-31-3C-49-50-59-64-00-00-08-18-1F-28-36-3A : OK
21/05/2023 2:30:50: FanGPU = 14-1D-32-3B-48-4C-51-64-01-01-09-10-10-22-34-3E : OK
21/05/2023 2:30:50: Boost 0
21/05/2023 2:30:50: Eco flag : -65536
21/05/2023 2:30:50: Mux flag : -65536
21/05/2023 2:30:51: Screen = 120Hz : OK
21/05/2023 2:30:51: ScreenOverdrive = 0 : 0
21/05/2023 2:30:51: Monitor Power On
21/05/2023 2:30:53: GET GPU CLOCKS: 0, 0
```

**Screenshots or screencasts**
Characters are more separated in _Balanced Mode_ (Equilibrado), so text won't fit:
![bad](https://github.com/seerge/g-helper/assets/62946623/f75c6121-a4cc-470b-973f-67be900286f0)

Characters are closer in any other mode, _Eco_, for example:
![good](https://github.com/seerge/g-helper/assets/62946623/bf22d81f-63da-4f04-b4c7-c262679e2d74)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Laptop model: G14 GA401IV

**Asus software**
- Asus Optimization Service

**Comment by seerge** [comment]
@marcelomijas most interesting that I didn't change that part in 0.65/64 :) it's probably windows scaling is acting again.
Can you try this build ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/11524027/GHelper.zip)

**Comment by marcelomijas** [comment]
This build solves the problem. Thanks!

Windows scaling seems to be a nightmare... for a 2 billion dollar company....
