### ISSUE TITLE
[Feature request] Update debloat.bat to disable Asus Optimization Service

### ISSUE THREAD

**Issue by marcelomijas** [seerge/g-helper#421]
Now that in v0.65, Asus Optimization Service is no longer needed. Can we have the debloat.bat file updated to completely disable Asus Optimization Service?

I manually tried to end Asus Optimization Service (and the startup task) in task manager to test the new OSD feature, but the tasks restarted themselves after a few seconds closed.

**Update**: I managed to get it closed, but now M3, M4 and FN+F4 keys are not working with G-Helper.

**Comment by seerge** [comment]
@marcelomijas you need to go to windows -> services. And stop + disable the service, instead of killing process.

As for M3/M4 not working - can you post a log here? (may be they have different keycodes on your system)

**Comment by seerge** [comment]
@marcelomijas and as for updating bat - sure, as soon as I will see it works well in all situations, I had an idea of simply incorporating a button in the app itself that will start / stop all asus services :)

**Comment by marcelomijas** [comment]
> @marcelomijas you need to go to windows -> services. And stop + disable the service, instead of killing process.
> 
> As for M3/M4 not working - can you post a log here? (may be they have different keycodes on your system)
> 
> P.S. App detects if it should take over hotkeys or not only on start atm. So if you stopped Asus service - you need to relaunch app ...

I've done the service disabling. Now is working! :D

Only thing is that the touchpad key enables/disables the touchpad, but the icon doesn't change when enabling/disabling. The icon that is always showing is:
![imagen](https://github.com/seerge/g-helper/assets/62946623/458df810-466c-4667-b452-518200f2a9b4)


The log correctly saves the keypresses of this function (and all the others):
```
21/05/2023 11:37:26: Key:236        # Fn
21/05/2023 11:37:27: Key:107        # F10
21/05/2023 11:37:29: Key:236
21/05/2023 11:37:29: Key:107
```

**Comment by seerge** [comment]
@marcelomijas it doesn't cause i haven't implemented that (yet?)

**Comment by seerge** [comment]
@marcelomijas added touchpad status in https://github.com/seerge/g-helper/releases/tag/v0.66 (same as brightness / backlight)

As for debloat and asus optimization, I will keep things as is for now as I want to see if this works or not :) so I don't leave people without hotkeys at all.

**Comment by rez3vil** [comment]
Hi, can we have option to turn keyboard lights on and off via app itself? I usually work in dark and keep my keyboard light off, so I want option to turn light levels in app itself. A simple dropdown menu beside colors  would be lovely!

**Comment by seerge** [comment]
@rez3vil you already have that under ‘Extra’

**Comment by rez3vil** [comment]
> @rez3vil you already have that under ‘Extra’

I didn't notice that.. thank you! I just installed it and haven't explored it fully... is there any chance we can bind M4 key with G-Helper?

**Comment by rez3vil** [comment]
> @rez3vil again it’s under extra, and it’s default behaviour

Crap.. I totally feel embarrassed now 😅 Thank you very much for assist. Your app totally changed my temps from 60 to 45 degrees. It runs a lot cooler now.

**Comment by seerge** [comment]
Updated bloat.bat and debloat.bat. Added optimization service there too. I may add it as a button in the app as well somewhere in the future.

Closing for now.
