### ISSUE TITLE
XG Mobile BSOD

### ISSUE THREAD

**Issue by privacyonly** [seerge/g-helper#423]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
1. while XG mobile is activated, GPU mode should be disabled, if you turn to Eco, XG mobile is like being deactivated(no it is not).
2. if ECO mode is on, XG mobile SHOULD NOT be activated, it will BSOD.

**Clear scenario to Reproduce**
1. GPU Mode Eco
2. Click on XG Mobile
4. BSOD "DRIVER VERIFIER DMA VIOLATION"
 
**Expected behavior**
when you click XG Mobile button, Turn GPU mode to standard and activate XG Mobile after that, and disable GPU mode selection except the XG Mobile button, when the XG mobile is deactivated enable GPU mode selection.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11524167/log.txt)

**Screenshots or screencasts**
in Asus Armory crate it will disable GPU mode when XG mobile is turned on
![Untitled](https://github.com/seerge/g-helper/assets/72265774/0e9a608d-3602-4790-b059-d062addd8641)

**Desktop (please complete the following information):**
 - OS: Windows 11
 -  ROG Flow Z13 301ZC
 - XG mobile 3070 2021

**Asus software**
- Armoury crate (or it's services installed)
- MyASUS installed
- Other Asus services running in background

**Additional context**
also MUX(Ultimate) doesn't work with XG Mobile.

edit: add comma, reword.

**Comment by seerge** [comment]
@privacyonly i won't be chaining mode switches in the app (enabling dgpu then enabling xgmobile). But app will make XGM button inactive if Eco mode is on and will make whole GPU buttons set inactive if XGMobile is on.

[GHelper.zip](https://github.com/seerge/g-helper/files/11524254/GHelper.zip)

**Comment by privacyonly** [comment]
new BSOD "Video Memory Management Internal"
wait.

**Comment by seerge** [comment]
@privacyonly I didn't get what does this mean : "disabled XG Mobile from your this GHelper but still can't select GPU eco mode?" 

If you mean that GPU section doesn't become active - try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/11524328/GHelper.zip)

I don't know what causes crashes on your side. I need to know clear scenario that leads to that, to just try to prevent it.

**Comment by privacyonly** [comment]
> @privacyonly I didn't get what "disabled XG Mobile from your this GHelper but still can't select GPU eco mode?" means :)
> 
> If you mean that GPU section doesn't become active - try this build [GHelper.zip](https://github.com/seerge/g-helper/files/11524328/GHelper.zip)
> 
> I don't know what causes crashes on your side. I need to know clear scenario that leads to that, to just try to prevent it.

yes, this enable the gpu mode, but I still crashed.

1. can you try adding delay of 20seconds before after pressing the xg mobile button before we can press eco mode, or xg mobile button again, I think I didn't wait long enough for the led to change from red to white before switching to eco
2. or it didn't close all the apps loaded using the xg mobile
3. also please add instruction on mouse over at xg mobile button when in gpu eco mode that it can only be activated on standard mode.

**Comment by seerge** [comment]
@privacyonly try this build with big delays after enabling / disabling XGM before GPU ui becomes awaialble again

[GHelper.zip](https://github.com/seerge/g-helper/files/11524595/GHelper.zip)

**Comment by privacyonly** [comment]
> @privacyonly try this build with big delays after enabling / disabling XGM before GPU ui becomes available again
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/11524595/GHelper.zip)

You know what, the delay works too perfect for someone without XG Mobile, it is like when XG Mobile is activated then just nice the button is enabled again. NO BSOD so far, but let me try gaming and disabling XG Mobile halfway to crash it later.

but unfortunately, when GPU ECO mode, and XG Mobile button is disabled, when the mouse cursor is hovering above XG mobile button, the "XG mobile toggle works only in standard mode" is not shown.

**Comment by seerge** [comment]
@privacyonly  this build should show tooltip even when XGM Button is disabled
[GHelper.zip](https://github.com/seerge/g-helper/files/11524763/GHelper.zip)

**Comment by privacyonly** [comment]
This is what I think is missing that is making the BSOD.
![deactivate](https://github.com/seerge/g-helper/assets/72265774/5df7da0e-6018-48ed-9069-aca62d6e7380)
after that is a confirmation dialog saying that all data of the apps will be lost
fyi in task manager processes tab it is shown as GPU1 - 3D or GPU1 - Copy

**Comment by seerge** [comment]
@privacyonly so you try to pull out hardware device in the middle of running heavy 3d game? :)

**Comment by privacyonly** [comment]
> @privacyonly so you try to pull out hardware device in the middle of running heavy 3d game? :)

I am just trying to make G-Helper more user friendly, like to make it not crash when users press the wrong button.

XG mobile is shown as GPU1,
3050 is shown as GPU3, when apps is running on GPU3, switching to eco mode will switch back to Standard Mode automatically, this also happens both in G-Helper and Asus Armory Crate

>What happens if you close the game properly, before disabling eGPU ?
it will still crash because I only close the game and not the launcher.

**Comment by seerge** [comment]
@privacyonly i can force kill epiclauncher on eGPU disabling (i do that for EALauncher), try this build : 

[GHelper.zip](https://github.com/seerge/g-helper/files/11532434/GHelper.zip)

**Comment by seerge** [comment]
@privacyonly killing ALL apps that use GPU is not a good idea. 

As often it contains windows own processes like explorer.exe or DWM.exe (desktop manager) or any browser (Chrome / Edge / etc). And they survive disabling GPU perfectly.

Promptless and automatic GPU switching is something lots of people actually like in G-Helper :) I'm not a fan of changing that behavior.

**Comment by privacyonly** [comment]
> @privacyonly killing ALL apps that use GPU is not a good idea.
> 
> As often it contains windows own processes like explorer.exe or DWM.exe (desktop manager) or any browser (Chrome / Edge / etc). And they survive disabling GPU perfectly.
> 
> Promptless and automatic GPU switching is something lots of people actually like in G-Helper :) I'm not a fan of changing that behavior.

yeah Asus Armory Crate Gpu switcher will sometimes prompt to kill explorer and DWM

anyway it works, if only we can see what process is actually stopping change from standard to eco or what is keeping xg mobile button from being deactivated

**Comment by seerge** [comment]
@privacyonly for AC it's any process. It just won't even try to set Eco / disable XGM if there are running processes.

Do I understand correctly that now (after killing epic launcher) you don't get your BSODs?

**Comment by privacyonly** [comment]
yes I don't get BSOD if nothing is running on XG Mobile before switching.

**Comment by seerge** [comment]
Ok! :)

**Comment by privacyonly** [comment]
edit: here comes an idea, while xg mobile is activated, display message "close all apps that is running on nvidia activity before pressing this button"

**Comment by privacyonly** [comment]
G-Helper is on the right bottom of the screen, I pressed the XG mobile button, and it is now disabled with text "XG Mobile toggle works only in standard mode", I missed the dialog opened on the center of the screen, anyway everything works perfectly. Thanks.

**Comment by seerge** [comment]
Ok, great
