### ISSUE TITLE
AniMe Matrix Audio Visualizer has too much contrast

### ISSUE THREAD

**Issue by flankytingz** [seerge/g-helper#428]
I feel like the contrast is too much for the audio visualizer. The bright (top) + dim (bottom) almost makes it that the bottom part is barely visible in normal lit environments. I'd recommend adding a customization option for the difference or reducing the contrast.

**Comment by seerge** [comment]
@flankytingz and i like it how it is :) bottom changes brightness depending on bar height

**Comment by flankytingz** [comment]
ok maybe the contrast will grow on me (it is)
