### ISSUE TITLE
The OSD function of v0.66 is invalid

### ISSUE THREAD

**Issue by oflg** [seerge/g-helper#429]
**Describe the bug**
The shortcuts and OSD function does not work.

**Clear scenario to Reproduce**
1. Turn off ASUS Optimization in the win service
2. Reboot my computer
3. Open G-Helper (Run on Startup)
4. Brightness buttons and other shortcuts functions(M1-M4, Fn+F4) do not work, and there is no OSD

**Expected behavior**
Shortcuts and OSD work after ASUS Optimization is turned off.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11529687/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/42492105/02e6cbe1-c0bd-4f74-8716-b97b1db3686b)
![image](https://github.com/seerge/g-helper/assets/42492105/ed7855eb-ebb8-4b16-904a-0488a1097633)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: ROG Flow Z13 GZ301ZC

**Asus software**
- Armoury crate uninstalled
- MyASUS uninstalled
- Other Asus services running in background: as in the screenshot above.

**Additional context**
The computer is charging (not using the battery)

Thanks😊

**Comment by seerge** [comment]
@oflg it could be that on Z13 your "external" usb keyboard has different ID. Can you try this build and post a log ?

[GHelper.zip](https://github.com/seerge/g-helper/files/11529986/GHelper.zip)

**Comment by oflg** [comment]
Thanks for the quick reply.

I tried it, the shortcuts for the brightness function and OSD don't work (manual adjustment in Extra button works), the others (M1-M4) work fine.

Here is the new [log.txt](https://github.com/seerge/g-helper/files/11530077/log.txt).

**Comment by seerge** [comment]
I checked your log, and it looks like on Z13 keys produce different "codes".

```5/22/2023 6:37:50 PM: Key:236
5/22/2023 6:37:54 PM: Key:236
5/22/2023 6:37:55 PM: Key:124
5/22/2023 6:37:55 PM: Key:124
5/22/2023 6:37:56 PM: Key:124
5/22/2023 6:37:57 PM: Key:124
5/22/2023 6:37:58 PM: Key:236
5/22/2023 6:38:00 PM: Key:124
5/22/2023 6:38:04 PM: Key:236
5/22/2023 6:38:08 PM: Key:236
5/22/2023 6:38:09 PM: Key:199
5/22/2023 6:38:09 PM: Key:199
5/22/2023 6:38:09 PM: Key:199
5/22/2023 6:38:10 PM: Key:199
````

Can you (by looking at the log) try to press fn+f2, +f3, etc and write down here which combination generates which code?

**Comment by seerge** [comment]
@oflg  (mentioning your name to trigger notification)

**Comment by seerge** [comment]
@oflg or just try this build where 236 will be backlit UP and 199 - backlit down

[GHelper.zip](https://github.com/seerge/g-helper/files/11530174/GHelper.zip)

**Comment by oflg** [comment]
```
f1: Key:236
f2: Key:236
f3: Key:124
f5: Key:174
f6: Key:236
f7: Key:16
f8: Key:32
f9: Key:236
f10: Key:107
f11: Key:199 (The only keyboard backlit key, no up and down)
f12: Key:236 (Guess all the key 236 means that it is not taken over by G-Helper and works perfectly as it should.)
```
![c369f8da8f6fd61c2f2f8ee03983e99](https://github.com/seerge/g-helper/assets/42492105/d9e94433-c527-4469-9dc0-2d32b7ee4aa9)

**Comment by seerge** [comment]
@oflg ok, and what keys don't work currently ? Also what F11 does ? it toggles backlit ON/OFF ?

**Comment by oflg** [comment]
The function of f11 is to cycle through the four levels of brightness.
```
0: Off 
1
2
3 : Brightest
```

By the way, perhaps the name fn+f4 in Key Bindings is not quite accurate (in this keyboard it is fn+f5) and should be renamed to Fan or M5, etc.?

**Comment by oflg** [comment]
> what keys don't work currently

F11

**Comment by seerge** [comment]
@oflg 
Try this build, it should cycle baklight upwards (and then back to 0)
[GHelper.zip](https://github.com/seerge/g-helper/files/11530348/GHelper.zip)

I think Z13 (with it's "separate" keyboard) is the only case that have M1-4 keys and F-row merged. For the rest (99%) Fn+F4 / Fn+F5 exist. So I don't want to make UI too specialized / complicated.

**Comment by oflg** [comment]
> Try this build

It worked perfectly this time. Thanks 😊



> So I don't want to make UI too specialized / complicated.

Okay, it does.

**Comment by seerge** [comment]
@oflg ok, great. I will push this changes with next release
