### ISSUE TITLE
Startup run issue

### ISSUE THREAD

**Issue by TYH4N** [seerge/g-helper#43]
Hello,

Thanks for the lightweight software. I've been having issues with the "run on startup" function.
Laptop Info: 2022 ROG G14 GA402RK, win 11, ghelper located in C:\

1. With the built-in "run on startup" checked. Windows task scheduler shows the "ghelper" task running, and task manager shows a "ghelper" task, but no icon appears.
2. With the built-in "run on startup" UNchecked. Setup a scheduler myself to run ghelper at startup on log on (w/wo delay). Windows task scheduler shows the "ghelper" task running, and task manager shows a "ghelper" task, but no icon appears.
3. Manually double-click ghelper after startup or with a .bat file that runs ghelper both work fine.
4. With the built-in "run on startup" UNchecked. Setup a scheduler myself to run the .bat file at startup on log on (w/wo delay). Windows task scheduler shows the "ghelper" task running, and task manager shows a "ghelper" task, but no icon appears.
5. Sometimes the ghelper icon shows up for a short period of time after startup and then disappears.

Hope this information will help.

**Comment by seerge** [comment]
I don't think it has something to do with startup tho, can you check windows Events Viewer -> Windows logs -> application for any Errors connected to GHelper ? Do you have Asus control interface installed ?

**Comment by TYH4N** [comment]
I'm not seeing any errors related. But it seems there's no issue now since I swapped 1.4 with 1.5. (I have Myasus installed but not AC.)

**Comment by seerge** [comment]
Ok, that's strange :) cause everything that you explained - is actually app crashing... 
The only reason i'm aware - it can't connect to ACPI driver (which is part of Asus control interface)

But good that it's working :)
