### ISSUE TITLE
Popup and Trojan 

### ISSUE THREAD

**Issue by luckyth13teen** [seerge/g-helper#432]
A popup asking if I would like to update was popped up and upon clicking yes windows defender blocked and quarantined a file it ID'd as Trojan:Script/Wacatac.H!ml  from the process: pid:29228,ProcessStart:133292357482720501  It verified that the process came from this application. 

I will see if I can get any more additional information but it looks like something is up with this version.

**Comment by luckyth13teen** [comment]
the popup was self identifying as a window of G-helper.

**Comment by seerge** [comment]
@luckyth13teen hello. False positives from defender can happen. Just to be sure I have re-uploaded latest build as 0.67 https://github.com/seerge/g-helper/releases/tag/v0.67 :) 

If you don't trust it - you can always recompile app by yourself ;)

**Comment by luckyth13teen** [comment]
Thanks! 

I had a suspicion that might be the case, just doing my due diligence now that I got an alert.  Figured you'd want to know regardless of likelyhood of issue.
