### ISSUE TITLE
[Bug] Incorrect "Extra" window positioning

### ISSUE THREAD

**Issue by marcelomijas** [seerge/g-helper#436]
**Describe the bug**
Since v0.66, the bottom of the "Extra" window interferes with the Windows taskbar. (Windows 10)

**Clear scenario to Reproduce**
1. Open G-Helper.
2. Open the "Extra" window-

**Expected behavior**
The bottom of the "Extra" window should not interfere with the Windows taskbar.

**App Logs**
```
22/05/2023 16:25:38: App launched: ROG Zephyrus G14 GA401IV_GA401IV :0.67.0.0es-ES
22/05/2023 16:25:38: Input Events64|6Dispositivo definido por el proveedor compatible con HID\\?\hid#vid_0b05&pid_1866&mi_02&col01#8&3397f86&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
22/05/2023 16:25:38: AutoSetting for Online
22/05/2023 16:25:38: BatteryLimit = 60 : OK
22/05/2023 16:25:38: BatteryLimit = 60 : OK
22/05/2023 16:25:38: PerformanceMode = 0 : OK
22/05/2023 16:25:38: FanCPU = 14-1E-31-3C-49-50-59-64-00-00-08-18-1F-28-36-3A : OK
22/05/2023 16:25:38: FanGPU = 14-1D-32-3B-48-4C-51-64-01-01-09-10-10-22-34-3E : OK
22/05/2023 16:25:38: Boost 0
22/05/2023 16:25:38: Eco flag : -65536
22/05/2023 16:25:38: Mux flag : -65536
22/05/2023 16:25:38: Screen = 120Hz : OK
22/05/2023 16:25:38: ScreenOverdrive = 0 : 0
22/05/2023 16:25:38: Monitor Power On
```

**Screenshots or screencasts**

![imagen](https://github.com/seerge/g-helper/assets/62946623/4e4f6863-124e-4db5-83d8-334ce9c6c3bc)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Laptop model: G14 GA401IV

**Asus software**
- None. (Asus Optimization Service is stopped)

**Additional context**
It has happened on other versions... weeks ago...

**Comment by seerge** [comment]
@marcelomijas cause Extra is now bigger to accomodate all keybinds :)

Try this build  [GHelper.zip](https://github.com/seerge/g-helper/files/11532151/GHelper.zip)

**Comment by marcelomijas** [comment]
> @marcelomijas cause Extra is now bigger to accomodate all keybinds :)
> 
> Try this build [GHelper.zip](https://github.com/seerge/g-helper/files/11532151/GHelper.zip)

Solved! :)
