### ISSUE TITLE
GA402RJ anime matrix clock doesn'work

### ISSUE THREAD

**Issue by navhawk80** [seerge/g-helper#437]
## NOTE
Hello Dear,

First run of g-helper version 0.67.0.0 on GA402RJ "clock" mode on anime matrix doesn't work. It is still showing previous selected mode "Binary Banner" or "Rog Logo" wich one was active before. Switching between "Binary Banner" and "Rog Logo" works.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11536048/log.txt)

**Desktop:**
 - OS: Windows 10 LTSC new installation without any ASUS software
 - Laptop model: GA402RJ

**Asus software**
- Armoury crate (or it's services installed) - no
- MyASUS installed - no
- Other Asus services running in background -no

**PS** On previous stable version 0.63.0.0 of g-helper there is no issue.

**Comment by seerge** [comment]
@navhawk80 hello, does 0.63 still show any mode on matrix, if you would download and run it now?

**Comment by navhawk80** [comment]
Yes. on 0.63 there is no issue as I wrote in my post. Allworks as expected

**Comment by seerge** [comment]
@navhawk80 try this build 
[GHelper.zip](https://github.com/seerge/g-helper/files/11536274/GHelper.zip)

**Comment by navhawk80** [comment]
The same issue. But static picture works and if I select "clock" after "static picture" clock on matrix shows. Changing from "Binary Banner" and "Rog Logo" still not work.

**Comment by seerge** [comment]
@navhawk80 try this build 
[GHelper.zip](https://github.com/seerge/g-helper/files/11536455/GHelper.zip)

**Comment by navhawk80** [comment]
please look at my previous comment (updated). 
On last build "Binary Banner" and "Rog Logo" to "audio vusualiser" also doesnt work

**Comment by seerge** [comment]
@navhawk80 and in this one ? 

[GHelper.zip](https://github.com/seerge/g-helper/files/11536564/GHelper.zip)

**Comment by navhawk80** [comment]
now all works. Thank you. :)
