### ISSUE TITLE
Turn of backlight when lid is closed + backlight timeout on charger

### ISSUE THREAD

**Issue by lucidnx** [seerge/g-helper#438]
**Describe the solution you'd like**
I would like to:
1. turn off backlight when lid is closed, restored when open
2. be able to set backlight brightness timeout on charger too, it is lit up forever whole night because I am leaving it on.
3. implement both on charger and on battery backlight timeout without asus optimization

**Comment by seerge** [comment]
@lucidnx not sure how to detect lid closed, but app tries to turn off backlight when screen is off 

As for timeouts - i have added them in this build
[GHelper.zip](https://github.com/seerge/g-helper/files/11548052/GHelper.zip)

**Comment by lucidnx** [comment]
Testing now, I hope there's some way to detect lid, I will try to find way too.

**Comment by seerge** [comment]
@lucidnx well, when you close lid -> monitor goes off -> that already has a trigger to turn backlight off. + on top of that backlight will go off by timeout

**Comment by navhawk80** [comment]
Hello, the author of post was asking to implement both on charger and on battery backlight timeout. On battery mode it is implemented now. Any way to do the same when on charger?

**Comment by seerge** [comment]
@navhawk80 i can, but can you explain a realistic scenario when you will need that? when plugged there is no reason to save bits of battery…

**Comment by navhawk80** [comment]
The reason is not to save a battery. For example I watch a movie in a dark room and in this case I do not touch any buttons but the keyboard light is constantly illuminates so I need to turn it off manually.

**Comment by toomuchsalt** [comment]
Having keyboard backlight timeout on charger would be a very nice feature. +1

**Comment by lucidnx** [comment]
> @lucidnx well, when you close lid -> monitor goes off -> that already has a trigger to turn backlight off. + on top of that backlight will go off by timeout

Yes, that's nice feature, but I am using laptop closed with external monitor, amd while it's being used backlight is always ON. maybe function when there's external monitor detected, turn off backlight? I guess this is not best for everyone so maybe simple checkbox in Extra would be great?

**Comment by seerge** [comment]
https://github.com/seerge/g-helper/releases/tag/v0.70

**Comment by lucidnx** [comment]
> https://github.com/seerge/g-helper/releases/tag/v0.70

Hello! Have you seen last message from me here?

**Comment by lucidnx** [comment]
@seerge yes, that apply when I am on battery, this is not always, our software is ruining battery 🗡️  (network vunerability scans, etc..)

**Comment by lucidnx** [comment]
@seerge maybe there's more knowledge now and this feature can be added?

**Comment by seerge** [comment]
@lucidnx feature is already added in the app for a while :)

**Comment by lucidnx** [comment]
how to do it? Laptop is closed but backlight is still ON.

**Comment by seerge** [comment]
@lucidnx it's automatic. Do you use latest version? Check app's log - it should say that Lid is closed and set a backlight brightness to 0 there.

Or upload a log here

**Comment by lucidnx** [comment]
In log, there's lid closed shown, but backlight is still on. 2 log lines:
Lid Closed
Lid 19b6: 5D-BA-C5-C4-00

**Comment by seerge** [comment]
@lucidnx hmm

``
Lid Closed
Lid 19b6: 5D-BA-C5-C4-[00] <--- last byte is brightness level, its OFF
```

Looks like keyboard is on due some other reasons ... not known to me. If you would just set backlight to OFF manually, does it stay off when you close the lid ?

**Comment by lucidnx** [comment]
25. 4. 2024 0:20:37: Slider 19B6: 5D-BA-C5-C4-00
25. 4. 2024 0:20:49: Lid Open
25. 4. 2024 0:20:49: Lid 19B6: 5D-BA-C5-C4-00
25. 4. 2024 0:20:49: Display configuration changed.
25. 4. 2024 0:20:50: TL140ADXP01 HDR: False 8 5 True
25. 4. 2024 0:20:55: Key: 196
25. 4. 2024 0:20:55: Key: 196
25. 4. 2024 0:20:55: HotKey 19B6: 5D-BA-C5-C4-01
25. 4. 2024 0:20:55: HotKey 19B6: 5D-BA-C5-C4-02
25. 4. 2024 0:20:55: HotKey 19B6: 5D-BA-C5-C4-03
25. 4. 2024 0:20:55: HotKey 19B6: 5D-BA-C5-C4-03
25. 4. 2024 0:20:55: HotKey 19B6: 5D-BA-C5-C4-02
25. 4. 2024 0:20:55: HotKey 19B6: 5D-BA-C5-C4-03
25. 4. 2024 0:20:55: Listener stopped
25. 4. 2024 0:20:55: Listener stopped
25. 4. 2024 0:20:55: Listener stopped
25. 4. 2024 0:20:55: Listener stopped
25. 4. 2024 0:20:55: Listener stopped
25. 4. 2024 0:20:55: Listener stopped
25. 4. 2024 0:20:55: Listener stopped
25. 4. 2024 0:20:55: Listener stopped
25. 4. 2024 0:20:55: Key: 196
25. 4. 2024 0:20:55: HotKey 19B6: 5D-BA-C5-C4-03
25. 4. 2024 0:20:55: Key: 196
25. 4. 2024 0:20:56: HotKey 19B6: 5D-BA-C5-C4-03
25. 4. 2024 0:20:56: Key: 196
25. 4. 2024 0:20:56: HotKey 19B6: 5D-BA-C5-C4-03
25. 4. 2024 0:20:56: Key: 196
25. 4. 2024 0:20:56: HotKey 19B6: 5D-BA-C5-C4-03
25. 4. 2024 0:20:58: Lid Closed
25. 4. 2024 0:20:58: Lid 19B6: 5D-BA-C5-C4-00
25. 4. 2024 0:20:59: Display configuration changed.
25. 4. 2024 0:20:59: Internal screen off


Now it's working while system is running, but it did not even changed slider before.

**Comment by seerge** [comment]
@lucidnx well, i honestly don't know what's happening there :) backlight brightness command is same for all ROG devices, and as you see it happens :)

**Comment by lucidnx** [comment]
That's weird, I will keep an eye on it. Maybe there's something running/communicating already so it's busy at the moment? Is it even possible for it to happen?

**Comment by seerge** [comment]
@lucidnx well ... asus stuff, but i guess it's not your case ? :)

**Comment by lucidnx** [comment]
nope, services are off and there's not even MyASUS installed.
