### ISSUE TITLE
Mic mute hotkey mutes sound as well (v0.15)

### ISSUE THREAD

**Issue by cam1x08** [seerge/g-helper#44]
So as the title says, I've updated my g-helper to v0.15 and with this update mic hotkey (next to rog button) now for some reason started to mute sound as well, when G-Helper is not running issue is gone. Adding video below.
https://youtube.com/shorts/NWl3l4bIoL4?feature=share

**Comment by seerge** [comment]
Cause it's set to mute sound in keyboard settings i guess ? :)  set M3 to custom  in "Extra" settings for keybpard (and leave command field empty) and it will not interfere

**Comment by cam1x08** [comment]
> Cause it's set to mute sound in keyboard settings i guess ? :) set M3 to custom in "Extra" settings for keybpard (and leave command field empty) and it will not interfere

Nope it's not. I have 2021 model and it doesn't have M1-M4 keys like 2022 does. Also on the v0.14 version there was no such thing, at least for me. And it appeared indeed only when I updated today to v0.15

**Comment by cam1x08** [comment]
> Cause it's set to mute sound in keyboard settings i guess ? :) set M3 to custom in "Extra" settings for keybpard (and leave command field empty) and it will not interfere

Ah I see, nvm, my bad, found what you was talking about! TYSM for your work

**Comment by seerge** [comment]
I will probably make default action for M3 to do nothing (i.e. not interfere with "system" action, which is myasus service muting mic)

**Comment by cam1x08** [comment]
> I will probably make default action for M3 to do nothing (i.e. not interfere with "system" action, which is myasus service muting mic)

Thanks! I'll mark my issue as closed now. Tysm for your work
