### ISSUE TITLE
Most function keys stop working after waking from sleep

### ISSUE THREAD

**Issue by d-anez3** [seerge/g-helper#443]
**Describe the bug**
When letting the computer go to sleep by itself (blinking power indicator), then waking from sleep, most function keys (F2-5, F7-8, F10-12) will become unusable and keyboard brightness is set to max. Closing and re-opening G-Helper reenables these keys and allows the brightness to be adjusted again. This is with ASUS Optimization disabled. Only F1 (volume mute), F6 (PrintScreen), and F9 (Project) work in this bugged state. I had no issue with this when ASUS Optimization was enabled.

**Steps to reproduce the behavior:**
1. Let the computer go to sleep by itself (could not reproduce by going to sleep via Start Menu)
2. Wake it up from sleep
3. Keyboard should immediately brighten up to max
4. Any of the above mentioned keys will not work.

**Expected behavior**
I expect F2-5, F7-8, and F10-12 to work as they should, and that keyboard brightness should not be changed (I never have it on).

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11538712/log.txt)

**Screenshots**
![image](https://github.com/seerge/g-helper/assets/113142829/1b5bc5c2-0891-4c06-be69-859f1ead5ba7)

**Desktop:**
 - OS: Windows 11 22H2, 22621.1702
 - Laptop model: GA401QM (G14 2021, Ryzen 9 5900HS, RTX 3060)

**Asus Software**
- Armoury crate (or it's services installed): None
- MyASUS installed: Yes but it's only been opened once
- Other Asus services running in background: All ASUS services are disabled.

**Comment by seerge** [comment]
@d-anez3 hello, does restarting app solve the problem ?

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11544429/GHelper.zip)

In this build app will re-launch own hotkey listener, this should solve your issue. Let me know if it works

**Comment by Draebor** [comment]
hmm same issue here on my 2022 Tuf Gaming F17 FX706HC.313 .  running ghelper version 0.68.0.0.  win 11 pro 2H22,  no armoury crate installed

asus optimization service turned off and disabled,  as soon as i reboot the pc or start from a shutdown no hotkeys except for volume.  Can't use the fn f5 toggle to switch profiles,  touch-pad popup doesn't work,  brightness controls at max and dont work.

**Comment by d-anez3** [comment]
In my case 0.68 seems to have fixed my issue. I'll keep the issue open for the other person

**Comment by seerge** [comment]
@Draebor your case is different, as on TUF models hotkey seem to work in absolutely different way (as usual). Your case is a dublicate of this topic https://github.com/seerge/g-helper/issues/441. Try build from there?

@d-anez3 good.

I'm closing this issue, as it seem to be fixed (TUF is another issue)
