### ISSUE TITLE
[Bug] v0.67 is slow/hanging when swhitching the power profile

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#446]
Doing usual swithing between Turbo and Balanced profiles. The app hangs, blinks, runs the Power&Fans window, and basically behaves similarly to the full app restart. Also, no error messages in the Windows Events log.

**Describe the bug**
As described. Happened randomly.

**Clear scenario to Reproduce**
1. Go to the main app window having the Turbo mode active.
2. Click on Balanced mode.
4. The app window hangs, then blinks, then runs the Power and Fans window, hangs again, and then sets the Balanced mode.

**Expected behavior**
Clear modes switching.

**App Logs**
[log067.txt](https://github.com/seerge/g-helper/files/11543331/log067.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11 hh2h
 - Laptop model GA503QR

**Asus software**

- MyASUS
- AsusAppService
- ASUSSoftwareManager
- ASUSOptimization

**Comment by ke1ne** [comment]
> @ke1ne i can't reproduce anything even close to what you explain. Can you record a video? Also I see that app was not started as admin initially, and then asked for permissions (to set GPU clocks). Does it happen after it restarted as admin as well ?

I just fully restarted a laptop. It seems to be ok now. I will mention if it repeat, etc. Thanks!

**Comment by seerge** [comment]
@ke1ne any updates? Or can i close this?

**Comment by ke1ne** [comment]
> @ke1ne any updates? Or can i close this?

v0.69 is seems to be OK. I think we can skip this. thanks
