### ISSUE TITLE
Missing PPT sliders for the CPU and the GPU Power Saver Slider.

### ISSUE THREAD

**Issue by NJinsei** [seerge/g-helper#447]
**Is your feature request related to a problem? Please describe.**
The current G-Helper software does not have the same options as my version of Armoury Crate for adjusting the SPL, SPPT, and FPPT values for the CPU, and the GPU Power Saver Slider is missing for the DGPU.

**Describe the solution you'd like**
I would like G-Helper to also have three separate sliders for the CPU power limits: SPL, SPPT, and FPPT. I would also like G-Helper to have the slider for the DGPU power saving mode.

**Screenshots or screencasts**
<img width="457" alt="image" src="https://github.com/seerge/g-helper/assets/89779681/6cfe7433-9955-4f43-8dfb-6bcacb40684f">
This is how Armoury Crate let me adjust the CPU power limits manually.

<img width="483" alt="image" src="https://github.com/seerge/g-helper/assets/89779681/93ee0c12-7880-4910-b1f4-961899c87471">

This is the slider that is missing for the DGPU power saving mode.

**Comment by NJinsei** [comment]
Ah makes sense the PPT worked for me so I was just wondering. As for the GPU Power saver it's a feature to turn on Whisper mode using Geforce Experience. So it limits frame rates and reduces fan noise and power consumption but I haven't found anything on how to control it. But since it's in geforce experience it isn't too much of hassle though.

**Comment by seerge** [comment]
@NJinsei ye, i know it exists in GF Experience, but I couldn't find if it's even (theoretically) accessible via NVidiaAPI (that app uses to set clock offsets). So for now - it's not really doable.

**Comment by NJinsei** [comment]
That's alright then, thank you for your help though
