### ISSUE TITLE
iGPU Temperature no showing in G Helper

### ISSUE THREAD

**Issue by EvilPT** [seerge/g-helper#449]
**Describe the bug**
Hello, hope you're doing well! 

For some reason the iGPU temperature showed only for about 2 seconds when I first installed G Helper, and then it just disappeared. CPU and dGPU (when active) are showing the information, task manager shows the iGPU temperature and so does the AMD software but not the G Helper. I've tried with and without Armoury Crate/Myasus, all drivers up to date and did a windows reinstall but nothing worked (G Helper 0.68, tried an older version just to check, 0.64 but no luck)

**Clear scenario to Reproduce**
Since installed G Helper and it's always missing

**Expected behavior**
To show temperature on the app like CPU or dGPU

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11546846/log.txt)

**Screenshots or screencasts**
![1](https://github.com/seerge/g-helper/assets/129112804/5baf12b1-b4c0-4b68-b919-7ed9ca0453b3)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Laptop model G14 GA402XZ BIOS 306

**Asus software**
- Armoury crate tried with and without
- MyASUS tried with and without
- Usual Asus services, haven't used the debloat file yet

**Additional context**
Do let me know if you need any more information or any more more logs. Thanks

**Comment by seerge** [comment]
@EvilPT hello, g-helper never displayed iGPU temp. It shows dGPU temp only taken from Nvidia / AMD driver (+ as a fallback takes GPU temp from asus own sensor in bios) :)

**Comment by seerge** [comment]
@EvilPT yes, this is that "fallback" temperature that i mentioned, on 2022 model it keeps reporting something (so app keeps showing it), and on 2023 (i tried it on G16 2023) asus sensor just disappears :) 

From other side - if temp is absent - then you can be 100% sure that dGPU is off ;)

**Comment by EvilPT** [comment]
Got it, thanks for explaining and yeah at least it’s definitely off! Let me know if you need any testing done in this model 👍
