### ISSUE TITLE
App GUI Cutoff (2020 G14 Windows 10 )

### ISSUE THREAD

**Issue by innoix** [seerge/g-helper#45]
I am running Windows 10 22H2 on a G14 2020 (GA401IV) and when I run the latest version (GHelper v0.15) the app popup is cutoff. I am running at 100% scaling (I have tried other scaling and it was the same issue). There is no option to resize the window so I cannot access the optoins further down.

![GHelper_GxUB2ulIQd](https://user-images.githubusercontent.com/22380677/222963769-96919b19-2f9b-443c-b3a3-4aa3c226b0fe.png)
![TSjO8dGBpf](https://user-images.githubusercontent.com/22380677/222963771-7019c518-7bcb-4aef-9e82-0beb344176e7.png)

**Comment by TomBonnot** [comment]
Same thing here for the 2021 version

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/10892423/GHelper.zip)
can you check if this build fixes it ?

**Comment by innoix** [comment]
Confirmed as working for me. Thanks for the quick patch!
![0k81rWm6Sp](https://user-images.githubusercontent.com/22380677/222976271-842da951-5f6b-4d1e-9f3b-e079cb4a2a62.png)
