### ISSUE TITLE
Auto Mode for Refresh rate does not work sometimes after cold start.

### ISSUE THREAD

**Issue by flankytingz** [seerge/g-helper#450]
**Describe the bug**
Auto mode is moody, sometimes it works when I boot from last time on battery to this time on AC and sometimes it doesn't. It fails to change the refresh rate only but activates OD?

**Clear scenario to Reproduce**
1. Use on battery. Shutdown.
2. Connect to AC and boot.
3. Check if refresh rate changed on boot.

**Expected behavior**
Well, it should change.

**App Logs**
```
5/24/2023 1:50:35 AM: App launched: ROG Zephyrus G14 GA402RJ_GA402RJ :0.67.0.0en-US
5/24/2023 1:50:35 AM: Unable to load DLL 'nvapi64' or one of its dependencies: The specified module could not be found. (0x8007007E)
5/24/2023 1:50:35 AM: Input Events64|6HID-compliant vendor-defined device\\?\hid#vid_0b05&pid_19b6&mi_00&col01#8&18c99fbc&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
5/24/2023 1:50:35 AM: Matrix Audio
5/24/2023 1:50:35 AM: AutoSetting for Online
5/24/2023 1:50:35 AM: BatteryLimit = 80 : OK
5/24/2023 1:50:35 AM: PerformanceMode = 1 : OK
5/24/2023 1:50:36 AM: Boost 2
5/24/2023 1:50:36 AM: Eco flag : 1
5/24/2023 1:50:36 AM: Mux flag : 1
5/24/2023 1:50:36 AM: Screen = 120Hz : -1
5/24/2023 1:50:36 AM: ScreenOverdrive = 1 : OK
5/24/2023 1:50:36 AM: USB-KB 64:5D-BA-C5-C4-03
5/24/2023 1:50:36 AM: Matrix Audio
5/24/2023 1:50:36 AM: Monitor Power On
5/24/2023 1:50:36 AM: PowerLimit C2 = 87 : 0
5/24/2023 1:52:47 AM: Key:236
5/24/2023 1:52:57 AM: Screen = 120Hz : OK
5/24/2023 1:52:57 AM: ScreenOverdrive = 1 : OK
```

**Screenshots or screencasts**
60 + OD ? is that even possible.
![Here you go](https://github.com/seerge/g-helper/assets/82509155/c5e3c268-67af-49ce-ab6d-2870b13b4bb7)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GA402RJ-L8170W

**Asus software**
- Bloat free!!!

**Comment by seerge** [comment]
@flankytingz i believe this is a dublicate from https://github.com/seerge/g-helper/issues/387#event-9320373310
advice stands the same, if on start laptop refuses to set refersh rate - adjust task in task manager, to run app with a small delay (like 3-5 seconds)
