### ISSUE TITLE
Default powerplan based on charging state 

### ISSUE THREAD

**Issue by githubuser6000** [seerge/g-helper#452]
**Is your feature request related to a problem? Please describe.**
It would be nice to have "default" profiles for charging vs not charging states, perhaps configured in the config.json file 

For example, having the system default to silent when on battery and to performance when plugged in makes it easy to not have to constantly remember or check what plan I am in. 

Consider, 

1. I am plugged in, use turbo to game, close game and then get back to whatever I was doing
2. Use battery mode - power plan changes to Silent
3. When I plug it in again, plan switches to "Turbo", because that was the last plan used

**Feature request**
The last step should go to "Performance" plan because that was the "default" plan for plugged in state

**Comment by githubuser6000** [comment]
My apologies, it seems I had to set what plan I want, and then "save" that for it to show up

**Comment by githubuser6000** [comment]
**Is your feature request related to a problem? Please describe.**
It would be nice to have "default" profiles for charging vs not charging states, perhaps configured in the config.json file 

For example, having the system default to silent when on battery and to performance when plugged in makes it easy to not have to constantly remember or check what plan I am in. 

Consider, 

1. I am plugged in, use turbo to game, close game and then get back to whatever I was doing
2. Use battery mode - power plan changes to Silent
3. When I plug it in again, plan switches to "Turbo", because that was the last plan used

**Feature request**
The last step should go to "Performance" plan because that was the "default" plan for plugged in state

**Comment by seerge** [comment]
Hello, app remembers your "performance mode" per battery / charged. Just set them once and they willl change.
