### ISSUE TITLE
G-Helper's GPU power sliders vs. manual tuning via Afterburner oddities

### ISSUE THREAD

**Issue by Noisrevid** [seerge/g-helper#455]
Not sure if this considered an issue, but more of a "What is going on here" kind of question..  

1) I have 3 different Asus laptops in which G-Helper works perfectly fine on. (All 3 are Nvidia Graphics)
2) If you set the GPU power sliders to the most far right max available, which is +250mhz core and +250mhz memory, you get great performance, it actually works and makes the GPU noticeably faster and hotter (Key word here, hotter).
3) These sliders are doing exactly what Armoury Crate does as i'm seeing the same behavior there.  Noticeably faster, and hotter (Key work again, hotter GPU).
4) Turns out whenever you use the slider (up from default) it is UPPING the GPU's Power Level and vCore as a result of the higher Power Level limits.   

Now it gets weirder because if you use Afterburner, you cannot adjust the power limit at all, it's grayed out and if you use a +250 core and +250 memory OC in Afterburner, it's WAY slower than the same settings in G-Helper/ArmouryCrate.      And if you set a generous +300mhz core and +1000 memory setting in Afterburner, its STILL slower but not by a large amount.. And the reason why these settings aren't able to work properly is because when you use Afterburner, it changes the Power Limit of the GPU back to stock limits and not the higher one that the manual sliders unlock in G-Helper/ArmouryCrate.

What i'm wondering/asking for is if you've seen anywhere in the reverse engineering of ArmouryCrate where it has the ability to actually change the Power Limit of Nvidia GPUs?         Hope this all makes sense, it would be an amazing feature to be able to CONTROL the Power Limits of our Nvidia GPUs and apparently it's doable since ArmouryCrate is doing it via a software mod.

Thank you!

**Comment by seerge** [comment]
@Noisrevid hello, 

1. I have no idea how afterburner works, my assumption - it's just bugged.
2. I didn't reverse engieer Armoury, In G-helper I used official nvidia API to apply clock offsets (using nvidia driver), so that's why it works.
3. Next to clock offsets, some laptops have GPU dynamic boost setting, it's controlled via asus bios, not via driver. And G-helper allows to set that as well via corresponding slider (it appears if endpoint exists)

**Comment by Noisrevid** [comment]
Thanks for the prompt reply, Seerge!    Well, it could be that Afterburner is disabling the +25 watt boost (which my laptops have) when you go to apply new GPU settings..   

Are there plans to allow for more GPU fine tuning like vCore locking (to drastically lower temps under load) and the ability to go beyond +250/+250 on the clocks?   You can undervolt an Nvidia GPU to lower temps by up to 15c while being faster than factory default.

Thank you!

**Comment by seerge** [comment]
@Noisrevid no, there are no such plans, as overclocking is "official" feature of nvidia own api, while other things are not :)
