### ISSUE TITLE
Problems with custom fan curve on gpu G14 2021

### ISSUE THREAD

**Issue by PeppyTrash** [seerge/g-helper#457]
**Describe the bug**

Hi! I apologize immediately for my English.
Found a problem related to the fan curve on G14 2021

When custom fan curve is enabled, the application does not respond to any changes except for the FIRST point of the curve. This only applies to GPU graphics. CPU graphics work perfectly and respond to all changes

Tested on versions 0.61 - 0.69. The problem repeats at all. Deleting config and log files did not solve the problem

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11562956/log.txt)

**Screenshots or screencasts**
![2023-05-25_11-42-48](https://github.com/seerge/g-helper/assets/20214383/d66e3e22-dfd3-45f0-a7cd-27af2d62eed9)
![2023-05-25_11-43-32](https://github.com/seerge/g-helper/assets/20214383/a3ccfed2-8596-4076-b0d5-11412aaefd95)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - G14 2021 GA401QM

**Asus software**
- MyASUS installed

**Comment by seerge** [comment]
@PeppyTrash hello, your fans are controlled by bios. Not by the app. From the log it's clear that app sets exactly the fan curve you have created on a chart, and bios accepts it.

Try to experiment with fan curves (for example set first dot to 30C not to 20) or reset to defaults. 
In any case, there is nothing can be done here programmatically : )

**Comment by karasek2510** [comment]
@PeppyTrash Did you resolve your issue? I have the same problem

**Comment by karasek2510** [comment]
> @PeppyTrash Did you resolve your issue? I have the same problem

BIOS update to 415 resolve issue
