### ISSUE TITLE
Addition of Default CPU Power Limiter Reset Button in PPT

### ISSUE THREAD

**Issue by Omar-Alodwan** [seerge/g-helper#459]
I would like to request the addition of a new button in PowerPoint (PPT) that allows users to easily reset the CPU power limiter to its default settings. This button would simplify the process and save time for users who frequently adjust the CPU power settings in their presentations.

This feature would be particularly useful for users like myself who may have forgotten their default PPT settings and need to delete all data in order to see what the default settings are.

**Comment by seerge** [comment]
@Omar-Alodwan hello, do you mean just resetting slider position? as if "Apply" is not checked - it has no effect anyway (and reset does exactly that - unchecks it)

**Comment by seerge** [comment]
@Omar-Alodwan depending on your laptop :) If it's G14 2022 default values are listed in readme. 

Otherwise - experimentally. Set mode (with default settings) and just run cinebench / watch how high CPU goes in HWInfo or so :)

**Comment by Omar-Alodwan** [comment]
@seerge thanks so much ill see and experiment myself :)
