### ISSUE TITLE
Regression: v0.69 breaks GPU Mode on TUF F15 (FX506LU)

### ISSUE THREAD

**Issue by thepriyamkalra** [seerge/g-helper#463]
**Describe the bug**
v0.69 fixed an issue where some hotkeys (namely -- the microphone toggle button, M3 in app and the trackpad toggle) wouldn't function without ASUSOptimization; but it seems to have broken the GPU Mode options; they just don't appear anymore.
Just an observation, GPU Mode works fine on v0.68 but the hotkeys don't.

**Clear scenario to Reproduce**
1. Have a TUF F15.
2. Update GHelper to v0.69.0.0.
3. GPU Mode options will be missing.

**Expected behavior**
GPU Mode options should appear.

**App Logs**
Doesn't seem like there's much in the logs.
[log.txt](https://github.com/seerge/g-helper/files/11575280/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/43999863/fa1147b6-25cd-491a-b27c-59d3c3161707)

**Desktop**
 - OS: Windows 11
 - Laptop model: TUF F15 (FX506LU)

**Asus software**
- Clean installed windows myself; Never installed Armoury Crate.
- MyASUS not installed.
- No ASUS Services running (Deleted all services myself; except for ASUSOptimization that I only used prior to v0.69).
- Note that everything except for the hot keys worked fine prior to version v0.69.

Thanks for this amazing utility.

**Comment by seerge** [comment]
@thepriyamkalra as mentioned in release notes, app will hide GPU mode section if GPU switching is not supported on your modelhttps://github.com/seerge/g-helper/issues/419 

I assume it was not working there before as well? (i can't verify for sure as you have trimmed log for some reason)

**Comment by thepriyamkalra** [comment]
@seerge Thanks for the quick response. I accidentally addressed this under Asus Software (my bad) but GPU Mode was infact appearing and (apparently) functional prior to v0.69. I deleted the log and restarted GHelper to keep it relevent. Attaching the old log below.
[log.txt](https://github.com/seerge/g-helper/files/11575364/log.txt)

**Comment by seerge** [comment]
@thepriyamkalra i don't think it was functional. Your laptop reports both Eco / Ultimate flags in bios as absent

```
5/26/2023 5:09:23 PM: Eco flag : -65536
5/26/2023 5:09:23 PM: Mux flag : -65536
```

What you had is just a bunch of buttons that did nothing. Did you ever try to disable dGPU and set eco mode? :)

**Comment by thepriyamkalra** [comment]
AH. That makes sense since this laptop does not provide a method to disable Optimus atall. Well that was stupid XD. Thanks for the clarification.

**Comment by thepriyamkalra** [comment]
Another (unrelated) question I had was whether it's possible to keep the display at 144hz on battery. I can switch to that when on battery but everytime I unplug from power; it switched 60 and I have to set it 144.

**Comment by seerge** [comment]
@thepriyamkalra you should uninstall asus smart display control https://github.com/seerge/g-helper#recommendations-optional

**Comment by thepriyamkalra** [comment]
![image](https://github.com/seerge/g-helper/assets/43999863/29743e97-e55e-4c40-900f-bde3b9ddf5d9)
There are only three apps starting with an A running on my computer, and I cant find anything in the control panel, Is there somewhere else I need to check?

**Comment by seerge** [comment]
@thepriyamkalra from installed apps in your system. From log that you have submitted i see only entries where app was setting 144hz to your screen :) So if something is setting 60hz - it's not g-helper .

**Comment by thepriyamkalra** [comment]
@seerge Yes, it is on 144hz and in Settings > Apps > Installed Apps there's just Alarms & Clocks with an A lol. Can't find it.
& I have noticed something strange though; I had the computer on 144hz (plugged in) then I switched to battery - the screen blinked and it switched to 60hz as usual; but when I plugged it back in, the screen blinked but it stayed on 60hz but I felt it wasnt 60hz, soI switched to 144hz the screen did not blink and it just switched. Does that mean it was already on 144hz somehow?

**Comment by seerge** [comment]
@thepriyamkalra yes it does, where it "stayed" on 60hz (if you were stil able to switch to 144)?

And again, if you have screen setting in g-helper on 144hz, it won't be trying to switch to 60hz at all. It's something else running on your computer doing that :)

**Comment by thepriyamkalra** [comment]
Yea I think something is surely messing with the app lol; Ill try to track it down.

**Comment by seerge** [comment]
@thepriyamkalra you can also just stop (quit) g-helper to exclude it from equation :)

**Comment by thepriyamkalra** [comment]
Oh man I am really missing the most obvious things today. The screen still blinks so I am assuming it is still going to 60hz; so its 100% not GHelper. You actually gave me an idea that I'll test out right now.

**Comment by thepriyamkalra** [comment]
@seerge Could you add an option where GHelper simply sets the screen to 144hz (or whatever refresh rate one has configured) always when switching to battery aswell? Right now the "AutoSetting" does not touch the refresh rate (as far as I know); so this could be an optional feature?

**Comment by seerge** [comment]
[Auto] switches refresh rates (literally what it says in description)
Fixed refresh rates don't do anything, unless you click on them

**Comment by thepriyamkalra** [comment]
@seerge Thats not what I meant.
What auto says (and does for me) is that it sets to 60hz on battery and back when plugged; I am looking for something that remembers what fixed refresh rate was set on battery (and plugged in) and re-sets that when going on battery or plugging in. This way whatever some other service has set will just be overriden.

**Comment by seerge** [comment]
@thepriyamkalra then it will be fighting with other service and conflicting :) Just figure it out on your  side. It's out of scope for the app.

**Comment by thepriyamkalra** [comment]
I just implemented it on my fork for now, dont do much C# so it was actually fun. It's definitely not ideal but it works for now until I figure something out.

**Comment by thepriyamkalra** [comment]
Since my laptop runs using iGPU + dGPU (optimus); I decided to check the intel graphics centre and in there in power settings there was a option for "Dynamic Refresh Rate" which was causing the switch to 60hz. Dropping this here incase somebody has the same issue lol.

**Comment by seerge** [comment]
Oke, good to know! As I was advising to uninstall Asus smart display control only.

**Comment by seerge** [comment]
@thepriyamkalra i wonder if there is a way to programmatically disable that thing. As all this dynamic refresh rate changes could prevent proper disabling of GPU (eco mode) in some cases. G-helper always sets refresh rate last in all chain of commands, but it obviously can't compete with other apps doing same ...

**Comment by MirazMac** [comment]
Facing the same missing GPU Mode issue and after reading the issues, it seems my GPU doesn't support the switching. However, since the GPU Mode option is missing I can't see the GPU Temp/GPU Fan options as well. Any way to enable those?

**Comment by seerge** [comment]
@MirazMac hello, did you have gpu fan readings before that?

**Comment by MirazMac** [comment]
> @MirazMac hello, did you have gpu fan readings before that?
Yes I have GPU fans and temp readings on v0.69 . Any build after that is missing the section. I have the same ASUS TUF Gaming F15 FX506LH.

Here's the working screenshot:
![image](https://github.com/seerge/g-helper/assets/13865787/dd8528d1-572a-4def-b583-3a9924ace4d6)

**Comment by seerge** [comment]
@MirazMac can you check this build ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/11642872/GHelper.zip)

**Comment by MirazMac** [comment]
> @MirazMac can you check this build ? [GHelper.zip](https://github.com/seerge/g-helper/files/11642872/GHelper.zip)


This is what I get, same with any build above 0.69
![image](https://github.com/seerge/g-helper/assets/13865787/07350c5d-4660-414d-ab51-ab1ee0d8ae60)

**Comment by seerge** [comment]
@MirazMac and this one ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/11642911/GHelper.zip)

**Comment by MirazMac** [comment]
I can't seem to open the file. It's getting quarantined by Windows Defender, any particular reason?

**Comment by MirazMac** [comment]
Identifies it as:
Trojan:Script/Wacatac.B!ml

**Comment by seerge** [comment]
@MirazMac i have no idea why your defender is acting. i have added an extra space and recompiled 

[GHelper.zip](https://github.com/seerge/g-helper/files/11642934/GHelper.zip)

**Comment by MirazMac** [comment]
> @MirazMac i have no idea why your defender is acting. i have added an extra space and recompiled
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/11642934/GHelper.zip)

![image](https://github.com/seerge/g-helper/assets/13865787/7ff5906e-6da1-416c-8b99-4cec472350ca)

Okay this one seem to work fine.

Yeah Windows Defender can be peculiar time to time.

**Comment by seerge** [comment]
@MirazMac ok great, I will add this fix into next release

**Comment by MirazMac** [comment]
> @MirazMac ok great, I will add this fix into next release

Thanks a lot for all your work man. Appreciate it. Great piece of software. Cheers!

**Comment by thepriyamkalra** [comment]
I was going to report this as a separate issue, but I guess that's no longer needed :) The build attached works for me too.

**Comment by thepriyamkalra** [comment]
By the way, Do the CPU and GPU fans ways work in sync (exact same RPM) or is it just reading one fan?

**Comment by thepriyamkalra** [comment]
Okay. Kind of funny how the GPU fans also fire up in a CPU benchmark lol. But I guess the additional cooling cant hurt.

**Comment by thepriyamkalra** [comment]
Another question: When ASCI is uninstalled, is it possible to atleast monitor stuff (fan rpm is mainly what I care about) or is nothing accessible?
Need it for some comparisons I am trying to make.

**Comment by seerge** [comment]
@thepriyamkalra what is ASCI ? asus control interface ? I don't think you can completely uninstall it, as windows will install it again.

And no - if it's not working, app can't read anything.

**Comment by thepriyamkalra** [comment]
@seerge I have, in the past "uninstalled" it to the point that GHelper refused to launch, asking me to install it. but yeah if it is required for the app to do anything then I'll just have to keep it.

I wanted to test how the fan functions without it, but cant read the RPM without it XD
