### ISSUE TITLE
2023 G16: Unable to switch back to dGPU after unplugging and plugging laptop

### ISSUE THREAD

**Issue by SlenderBender77** [seerge/g-helper#464]
**Bug Description**
After unplugging i noticed that Battery consumption is at ~20v, which is unusual since on iGPU is usually drains ~8v. The area around the dGPU also gets hot as if it was running, which it isnt according to G-Helper and Task Manager. Plugging back my G16, G-helper switches refresh rates accordingly, but it fails to switch to iGPU/dGPU Mode, regardless of whether its on "Optimized" or "Standard" mode. I try playing a game to see if it would kick in like that, but no. The only way to get it back to normal is to Force Shut down the laptop, cause otherwise it says on the "Shutting Down/Restarting" screen eternally. The strange thing is that it it only happens around half of the time.

**Reproduce**
1. Use dGPU in any form (Games, Media)
2. Unplug Laptop
3. Plug Laptop
4. dGPU doesnt show up anymore

**Expected Behavior**
For dGPU to show up after being on battery life, and for Battery consumption to be normal.

**App Logs**
Most Recent event can be found on 5/26/2023 from 2:30pm downwards
[log.txt](https://github.com/seerge/g-helper/files/11579297/log.txt)  

**Desktop**
OS: Win 11
Laptop Model: Asus Zephyrus G16 GU603VV_GU603VV

**Asus Software**
ArmouryCrate: Uninstalled
MyAsus: Installed
Other Asus Services Running: 
![image](https://github.com/seerge/g-helper/assets/90931618/c59a3a91-edf2-42d4-809f-05066ee2f249)

**Additional Context**
Im not fully sure if this is a possible issue with Advanced Optimus or if its directly related to G-Helper, but this only started happening after i switched to G-Helper.

**Comment by seerge** [comment]
That sounds more like a hikkup / glitch with the bios not being turn off (or on) the GPU. 
Try to do a hard reset, turn off laptop and press-hold power button for 40 seconds. Then boot normally.

And gived that you have so many asus stuff running, including armoury services I could guess they might interfere as well.

**Comment by seerge** [comment]
@SlenderBender77 also from the log i see that app was getting "positive" response from bios, every time it has sent a Eco mode ON/OFF commands

```
5/26/2023 2:43:18 PM: GPUEco = 0 : OK
```

```
5/26/2023 2:39:59 PM: GPUEco = 1 : OK
```

**Comment by SlenderBender77** [comment]
>How did you verify that you dGPU was not on btw, was it visible in device manager?

Nvidia Control Panel disappeared, and Task Manager also said it wasn't there

Btw, by Hard Reset you don't mean Factory reset right? Kinda lost on that terminology

**Comment by seerge** [comment]
@SlenderBender77 

1. Nvidia Control panel would disappear when you disable GPU (cause there is no "nvidia" in system anymore then). If you re-enable it, i assume it makes sense to launch it manually again or restart even.

2. Task manager has nothing to do with your GPU, you should look in Device manager (in control panel). In a log i see app was managing to get your GPU clock offsets (after you set Standard mode back), it means that nvidia driver was alive, and could access GPU (so it was enabled back)

3. By hard reset I mean resetting your hardware (by long pressing power button as I explained). It doesn't reset your data, just enables GPU, and other things . Factory reset - is reinstalling your system completely :)) that's absolutely different thing.

**Comment by SlenderBender77** [comment]
1. Yeah exactly, but when I enabled it back on it still wouldn't show, which lead me to believe it wasn't actually enabled. I'll try restarting it next time

P.S: Well that may be a factor, I have it on Advanced Optimus (auto).

I tried replicating it a while ago and nothing went wrong, I'll do a hard reset if it happens again, hopefully it doesn't continue. I don't mean to take anymore time from you, thanks for the help though!

**Comment by seerge** [comment]
@SlenderBender77 if the only reason you thought that GPU is not working is absence of Nvidia control panel, it's not really a good metric tbh :) 

On g14 with AMD GPU - Adrenaline software also quits when you go Eco (and that's logical), so you need to run it again after re-enabling GPU.

Try to install HWInfo or something similar, and monitor what happens with your system. It has lots of sensors, and definitely won't miss a GPU :)

**Comment by SlenderBender77** [comment]
Games would also just run on the iGPU, world not opening Nvidia Control Panel after enabling the dGPU cause that? If so then that could also be a factor.

**Comment by seerge** [comment]
@SlenderBender77 for games, you could check Display - Graphics settings (from my experience windows sometimes decides to run games on iGPU if it's on auto)

![Screenshot 2023-05-27 111239](https://github.com/seerge/g-helper/assets/5920850/9f1879be-5fbf-488d-93cb-ec45d74fd9bf)

**Comment by SlenderBender77** [comment]
It happened again
![image](https://github.com/seerge/g-helper/assets/90931618/6442f280-07bb-46a4-9cd8-5eb4832c42dd)

This is what the GPU showed in properties: 
![image](https://github.com/seerge/g-helper/assets/90931618/5d9d120e-ac71-48ba-831d-c4e8810e6e20)

This is what HWinfo shows
![image](https://github.com/seerge/g-helper/assets/90931618/244c0b5d-9d5c-47ea-85ca-ce5a3b2f1ba3)

**Comment by seerge** [comment]
@SlenderBender77 oke, as i understand this is already when you tried to “enable” GPU? indeed looks like bios has failed to disable it (but reported that it did)

1. Was GPU visible in device manager after you have set eco?

2. What was your “optimus” setting before you set Eco?

**Comment by SlenderBender77** [comment]
1. Yes
2. "Optimus"

I just did a hard reset, tested again and everything showed the GPU turning off/on properly, although I had to reboot the Nvidia drivers when I switched back to AC power because the system froze. I think that's just from the hard reset. Definitely something wrong with bios not disabling it, that explains the power draw and heat.

**Comment by seerge** [comment]
@SlenderBender77 oke, thanks. If after setting eco - in a log you see "eco flag : 1" then it means that bios reports that GPU is disabled, so it's definitely acting :| 

1. May be it makes sense to do a fresh nvidia driver install ? Like uninstall them with [DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html) and install latest from nvidia site again?

2. Also you can try to stop some of those asus services + uninstall "Asus monitor control" (i guess you can always download and install it from asus website later)

Most interesting, that I bought exactly G16 2023 (just with 4070) for that. And all GPU switching was working super fine there.

**Comment by SlenderBender77** [comment]
Happened Again, Eco flag : 1

1. I've reinstalled the drivers twice to no avail. So that probably isn't the issue

2. I'll try, but removing them all with the debloat bat file caused My Asus to stop working, enabled them back on just to be safe. Trying to uninstall Asus Monitor Control but i get this
![image](https://github.com/seerge/g-helper/assets/90931618/440ae09d-a1a0-435f-b593-6db6babe1531)
Going to force boot again unfortunately.

As I side note, I did just notice that a download manager (FDM) had been preventing manual switching of display modes, though I had stopped its processes before this specific event. Might just outright uninstall it, though it'd be insane if that single program could cause the bios to mess up.

**Comment by seerge** [comment]
@SlenderBender77 well, looks like something on software side sometimes prevents GPU from disabling (but at the same time bios thinks it's disabled). 

If you would figure out what it is exactly - I can add a kill command in the app, and will try to close that process before setting Eco. It already kills following things  "EADesktop", "RadeonSoftware", "epicgameslauncher"  :) (2 of them are nasty launchers)

I think in nvidia control panel you can see what apps are using GPU, mb that will help.

P.S. As for MyASUS - true, it depends on that services, correct.

**Comment by SlenderBender77** [comment]
Alright, ill let you know if I find anything

**Comment by SlenderBender77** [comment]
Okay so I believe the problem is directly linked with routing the GPU directly to the screen (Nvidia Only). Even if I set it back to Optimus before switching to battery power, G-helper stays unresponsive for like 10 seconds (won't open with ROG key). I will try to switch back to armorycrate and see if the problem is isolated to G-helper and not my laptop itself.

**Comment by seerge** [comment]
@SlenderBender77 oke, but keep in mind that AC most probably just won't switch GPU off at all in those cases. So check if it does, i'm also curious :)

**Comment by seerge** [comment]
@SlenderBender77 by the way, there is something you may want to test. This build will try to kill all nvidia GPU apps before trying to set Eco. I wonder if it will help.

But since some processes  may require admin rights to kill - run app as administrator

[GHelper.zip](https://github.com/seerge/g-helper/files/11585947/GHelper.zip)

And post a log here :)

**Comment by SlenderBender77** [comment]
@seerge 

> @SlenderBender77 oke, but keep in mind that AC most probably just won't switch GPU off at all in those cases. So check if it does, i'm also curious :)

Just installed armory crate, it does. performed the same test, switched to GPU only (AC promptly forced optimus back on), then I unplugged HWinfo shows discharge rates as normal and GPU as disabled. I will keep it on AC and keep testing it each day since this problem is incredibly inconsistent. If it happens again, I'll try that build. I dont want to have to wipe everything and uninstall AC after just installing all its components.

**Comment by SlenderBender77** [comment]
@seerge 

I tried the build, no use. Its very strange that Ghelper takes so long to make the switch, not sure what that is about. AC does it instantaneously, and all the Nvidia options in my taskbar disappear aswell, as opposed to Ghelper. 

Here is the log:
[log.txt](https://github.com/seerge/g-helper/files/11594472/log.txt)
Most recent one running in admin is at around 7pm today.
Another event occurred at around 3:40pm without admin.

I hope these logs can be of use, I think I'll switch back to AC for the time being.

**Comment by seerge** [comment]
@SlenderBender77 it could be that AC kills all nvidia own apps before disabling GPU. I can try to add that as well. can you check what nvidia processes run before swtching and after ?

**Comment by seerge** [comment]
@SlenderBender77 try this build (preferably as admin)
[GHelper.zip](https://github.com/seerge/g-helper/files/11594549/GHelper.zip)

**Comment by SlenderBender77** [comment]
> @SlenderBender77 by the way, there is something you may want to test. This build will try to kill all nvidia GPU apps before trying to set Eco. I wonder if it will help.
> 
> But since some processes may require admin rights to kill - run app as administrator
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/11585947/GHelper.zip)
> 
> And post a log here :)

Was using this one, switched properly this time. I decided to have task manager on and noticed a process called  "Open automate wrapper cache" with an Nvidia logo. It's only active when switching modes, is that relevant?

**Comment by seerge** [comment]
@SlenderBender77 that's good news in general. Can you keep it and see if it works consistently ?

As for "open automate wrapper" - according to google, this is part of nvidia experience. I can add it to the kill-list too, but let's see how it goes w/o that first.

**Comment by seerge** [comment]
@TheBestPessimist since device is in device manager (i haven't seen your screenshot when was writing previous advice), just a normal reboot will "fix" it.

**Comment by TheBestPessimist** [comment]
@serge that's interesting: it appears into device manager, but it is not found in settings, at the widows settings screen where I can choose the GPU pretty app. So something's still nok.

**Comment by TheBestPessimist** [comment]
I stopped the laptop via power button. 
As you suggested, after start it worked in dgpu only. 

Restarted into standard mode again, then switched intro optimized, then tried to switch into eco. Switching to eco did not work.

Restarted ghelper and now the mode is standard, not optimized.

**Comment by SlenderBender77** [comment]
@seerge 

Both Builds failed. It's reassuring to see I'm not the only one having issues, that rules out my laptop being the culprit. I don't think disabling more processes will do much, but i will compare to Armorycrate when I switch back. I really don't want to keep force rebooting so I'm just gonna conform with AC for now. 

Just a hunch, but maybe BIOS version might have something to do with it? Since you also have a G16 albeit a different model.

**Comment by SlenderBender77** [comment]
Hold on, i switched back to AC and after closing Cyberpunk my computer suddenly restarted. This is the first time this ever happens.

![image](https://github.com/seerge/g-helper/assets/90931618/7ab65212-daf3-4efe-86f8-a452fc505174)

I found warnings and an error log in event viewer.

**Comment by seerge** [comment]
@SlenderBender77 Bios definitely could be a reason, but I had latest bios on G16. And I actively tested app with both "bloated" version of windows with all stuff installed, as well as on clean copy of it. May be it was just luck :| 

But unfortunately I had to return laptop due to high-pitch fan noise from it. So I don't have it anymore. I will try to get G14 4080/4090 as soon as it will be avail for a reasonable price here in EU, and not 4000 EUR as it is now :)

**Comment by SlenderBender77** [comment]
@seerge I am currently reinstalling windows cause after reinstalling AC my computer has just been randomly restarting, sometimes going in a loop where it's restarts, boots, and restarts again in like 3 minutes. Hoping it's not a motherboard issue, but I've tried every possible solution except this. If a clean reinstall doesn't fix it I'll be forced to contact Asus support. Only issue is that Asus doesn't service my area so I really hope the problem is gone after that. No idea what may have caused it, but i think reinstalling/uninstalling AC repeatedly must've messed something up.

**Comment by SlenderBender77** [comment]
So it looks like the GPU took a real beating with all the force shutdowns, cause it's causing BSODs and it's drivers are missing even reinstalling windows. If anyone else has this issue they should just uninstall G-helper immediately honestly.

**Comment by seerge** [comment]
@SlenderBender77 is it with drivers from nvidia itself? I.e. does windows see your device? Does that hard reset make any difference? :|

**Comment by seerge** [comment]
@SlenderBender77 by the way, it may be irrelevant - but how did you reinstall windows? If you boot in recovery mode - there is a way to restore original image (i.e. exactly as it came "from the factory") with all asus drivers installed / etc

**Comment by SlenderBender77** [comment]
> @SlenderBender77 is it with drivers from nvidia itself? I.e. does windows see your device? Does that hard reset (with holding power button for 30-40 seconds) make any difference? :|

When it doesn't recognize the GPU (as in, doesn't appear in device manager) everything runs fine. As soon as I install AC and wake the GPU, device manager detects something, but it isn't labeled as Nvidia, it's labeled as "Microsoft Basic Display Adapter". I would install the drivers but the laptop just BSODs before anything else happens.

**Comment by SlenderBender77** [comment]
> @SlenderBender77 by the way, it may be irrelevant - but how did you reinstall windows? If you boot in recovery mode - there is a way to restore original image (i.e. exactly as it came "from the factory") with all asus drivers installed / etc

I performed a clean reinstall. Asus drivers were already being installed through Windows Updates. I didn't perform a factory reset though. I'm wary about doing any resetting since when I was reinstalling windows i had a BSOD. Thought it bricked itself but it seemed to be an issue with the GPU drivers. I had a Fatal Hardware error after that, following an install of OperaGX which i promptly uninstalled. I used a restore point ever since downloading AC and now it's back to normal, well, without the GPU

**Comment by SlenderBender77** [comment]
Okay I factory reset through "Reset PC" in the settings but I'm not getting anything different than a clean install. Driver and AC is still missing

**Comment by seerge** [comment]
@SlenderBender77 ah, ok. Well, it's not a big deal, since clean install + drivers should (theoretically) do same thing anyway. 

Out of curiosity, did you try "powering off and holding power button for 30-40 seconds" reset?

**Comment by AudreyAP** [comment]
@SlenderBender77 You can use "cloud recovery" in UEFI! 

Make a backup of your HDD, it will be completely wiped. All drives installed in the system will be nuked during this process. Unplug any drives you don't want to have windows installed on. 

Shut down the machine, then turn on and mash f2. At the top of the "advanced" menu is "myasus recovery" or something - click that

It will ask you for wifi information and will literally redownload, into RAM, a base recovery image. It'll then boot into that and create a new OEM recovery image. It'll partition your disk *exactly* how it was from factory, including the recovery partition. You can then boot straight into it as normal - it even reinstalls McAfee!

**Comment by AudreyAP** [comment]
Also @seerge For some reason, certain drivers are not installed automatically by windows and are not able to be found on Asus' site - the ICC profiles, for example, are somehow burned into the default image and they seem to be deleted after installation (empty eSupport folder). The only way to recover them seems to be cloud recovery.

**Comment by SlenderBender77** [comment]
> @SlenderBender77 You can use "cloud recovery" in UEFI!
> 
> Make a backup of your HDD, it will be completely wiped. All drives installed in the system will be nuked during this process. Unplug any drives you don't want to have windows installed on.
> 
> Shut down the machine, then turn on and mash f2. At the top of the "advanced" menu is "myasus recovery" or something - click that
> 
> It will ask you for wifi information and will literally redownload, into RAM, a base recovery image. It'll then boot into that and create a new OEM recovery image. It'll partition your disk _exactly_ how it was from factory, including the recovery partition. You can then boot straight into it as normal - it even reinstalls McAfee!

F2? You mean enter to the BIOS? Cause otherwise the Asus options in Recovery mode or Advanced startup aren't there since I reformatted my drives

**Comment by SlenderBender77** [comment]
@AudreyAP  F2? You mean enter to the BIOS? Cause otherwise the Asus options in Recovery mode or Advanced startup aren't there since I reformatted my drives

**Comment by AudreyAP** [comment]
@SlenderBender77 yes, in bios. There's a completely self contained recovery process that can be done with a completely blank drive. See instructions above :)

**Comment by SlenderBender77** [comment]
@AudreyAP I remember opening that and only finding the Diagnostics options, but I'll try again just in case

**Comment by AudreyAP** [comment]
@SlenderBender77 there are two options - you absolutely should have recovery on any 2023 g16. I know because I've done it :)

**Comment by SlenderBender77** [comment]
> @SlenderBender77 there are two options - you absolutely should have recovery on any 2023 g16. I know because I've done it :)

Omg it's there! You're an absolute lifesaver, thank you so much

**Comment by AudreyAP** [comment]
@SlenderBender77 pretty cool right? I suggest that you make a backup of the restore file that's sitting on the 21ish GB partition it'll create, you can reflash the laptop with it at a later date even without the Asus WinRE bits.

**Comment by SlenderBender77** [comment]
@AudreyAP Can I use my Ethernet btw? WiFi isn't very good here.

**Comment by AudreyAP** [comment]
@SlenderBender77 yup. Plug it in before you start the process (while in bios)

**Comment by SlenderBender77** [comment]
@AudreyAP Is the "Checking..." phase supposed to take long? It's been stuck there for awhile.

**Comment by SlenderBender77** [comment]
@AudreyAP It's still on "checking..." I think something's wrong :(

**Comment by SlenderBender77** [comment]
Forced it to shutdown. Didn't stop when I unplugged the Ethernet. I didn't want to leave it overnight, but it looks like cloud won't work for me. Booted into Windows just in case, it's fine.

**Comment by AudreyAP** [comment]
@SlenderBender77 it took like 3 hours for me. Just plug it in to power adaptor and let it run. I had a hang as well. I'd just give it another try.

**Comment by SlenderBender77** [comment]
> @SlenderBender77 it took like 3 hours for me. Just plug it in to power adaptor and let it run. I had a hang as well. I'd just give it another try.

On just that "Checking..." Part? I know it said it took 1-3 hours but i thought it meant for the actual process or partitioning and installing.

**Comment by SlenderBender77** [comment]
@AudreyAP On just that "Checking..." Part? I know it said it took 1-3 hours but i thought it meant for the actual process or partitioning and installing.

**Comment by AudreyAP** [comment]
@SlenderBender77 I had it sit on Checking for 45 minutes once. Just let it run.

**Comment by SlenderBender77** [comment]
@AudreyAP Alright so i just let it ran while I went to do some errands but when I came back home it had already booted up into Windows, but nothing had changed. I'm guess a prompt timed out or something.

**Comment by SlenderBender77** [comment]
Well I did it again and when it began to download the files it booted into Windows for some reason, then BSOD, automatic restart. My problem just got worse as I can't even stay in windows for a minute before screen freezes and then computer BSODs

**Comment by AudreyAP** [comment]
@SlenderBender77 I had a bsod as well. Try factory resetting bios settings. It's annoying but you'll get there!!!

**Comment by SlenderBender77** [comment]
@AudreyAP Still BSODing I would do another windows reinstall but I've just tried absolutely everything. Been stressing with this laptop for weeks. I'll send it to Bestbuy and if they can't fix it I'll try anything. But it's unusable rn. Thanks for the help anyways

**Comment by seerge** [comment]
@SlenderBender77 hello, just wanted to check up on you? any updates?

**Comment by SlenderBender77** [comment]
@seerge Hi, GeekSquad sent the laptop to Asus for RMA. I don't think they even bothered installing AC or anything, but i hope Asus can fix it with their OEM Image.

**Comment by seerge** [comment]
@SlenderBender77 oke! well, keeping fingers crossed then :)

**Comment by seerge** [comment]
Closing as there is nothing I can do in this case at least. 
P.S. Good luck with the things!

**Comment by AudreyAP** [comment]
@SlenderBender77 unfortunately I found the issue only after you RMA'd - "app install toggle" in bios seems to be the issue. I discovered this while walking someone else through a cloud recovery.

It tries to install myasus after windows boots, but it seems that WinPE crashes when this happens. Disabling it allows recovery to work fine.

**Comment by Henning742** [comment]
I had a similar problem today. I have the "kill dGPU apps when turned on ECO" option enabled. 

(Day 26, Afternoon)
I unplugged the power, switched to ECO  and I saw dGPU disappear in the Device Manager.

(Day 27, Morning)
I plugged on the power, switched to Standard and I saw dGPU appear in the Device Manager. But Nvidia Control panel cannot find it.

Here's the log, it might not be clean as I may have switched to standard mode once during the unplugged state?
[log.txt](https://github.com/seerge/g-helper/files/12447115/log.txt)

**Comment by seerge** [comment]
@SlenderBender77 hello, check [this topic](https://github.com/seerge/g-helper/discussions/1042) . It explains quite specific scenario (i.e. you need to power off / hibernate laptop in ECO), after which nvidia drivers may behave strange. If it applies to you - I can add G16 2023 to the list that offer a solution proposed in that topic.
