### ISSUE TITLE
Startup Bug

### ISSUE THREAD

**Issue by MihneaXB** [seerge/g-helper#466]
I encountered a problem when starting up my G15 2022, that the G-helper version downgrades, so when I enter the app it shows me the red upgrade button. And I also observed that the battery limiter only starts when the app starts, so every time the laptop powers on, it charges 1% over the limit every time.
It happens right when I start the laptop and enter the G-helper app.

 - OS: Windows 11
 - Laptop model: ROG Zephyrus G15 GA503RW
I don't have any other Asus app installed.

[log.txt](https://github.com/seerge/g-helper/files/11583034/log.txt)

**Comment by seerge** [comment]
@MihneaXB 

I think you have older version laying somewhere and it's set for startup. Just open latest version, and uncheck-check startup checkbox again.

As for power limiter, app sets it again on every run. If you have asus optimizations service running, you can disable it - so it won't overwrite charging settings.
