### ISSUE TITLE
Flow GPU fan is turned off while XG Mobile is activated

### ISSUE THREAD

**Issue by privacyonly** [seerge/g-helper#467]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
Flow GPU fan is turned off while XG Mobile is activated

**Clear scenario to Reproduce**
1. activate XG Mobile
2. GPU(not XG mobile) temperature is detected at 30C
3. GPU(not XG mobile) fan turned off 0rpm

**Expected behavior**
If XG mobile is activated GPU Temperature is replaced by CPU Temperature.

**App Logs**
App Logs not needed

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ROG Flow Z13

**Asus software**
- Armoury crate (or it's services installed)
- MyASUS installed
- Other Asus services running in background

**Additional context**

**Comment by seerge** [comment]
@privacyonly and how is it related to G-helper? :)

**Comment by privacyonly** [comment]
> @privacyonly and how is it related to G-helper? :)
> 
> Did you have custom fan profiles for Gpu/cpu ?

GHelper, Apply Custom fan profile, but the GPU fan speed is 0rpm, because the temperature of the GPU detected very low, it is supposed to read the same as CPU temperature, and the fan speed is supposed to be 6% lower than CPU fan speed(not always)

**Comment by seerge** [comment]
@privacyonly g-helper doesn't control your fans. Your bios does.

**Comment by privacyonly** [comment]
no, without custom curve both fan is working properly(seen from Armory crate)
when using custom profile I have to ramp up the fan curve to flat from 30C to 87C 5000rpm to wake the fan up.
basically it will always be detected as 30C as it is sleeping.

**Comment by seerge** [comment]
@privacyonly how does it work with armoury? if you would set a CUSTOM fan profile for GPU and for XGMobile at the same time, does it follow both?

**Comment by seerge** [comment]
@privacyonly you can also check this build, here app will apply XGM fan profile **BEFORE** CPU/GPU profiles, mb that matters for hardware ...

[GHelper.zip](https://github.com/seerge/g-helper/files/11591366/GHelper.zip)

**Comment by privacyonly** [comment]
Hold on,
in Armory Crate
1. if XG Mobile is activated the Laptop GPU fan speed is the same with CPU Fan.
2. if XG Mobile is deactivated Laptop GPU fan speed is normal

in GHelper custom fan profile
1. if XG Mobile is activated Laptop GPU fan speed is 0 rpm(read by Armory Crate)
2. if XG Mobile is deactivated Laptop GPU fan speed is normal

in GHelper default factory fan mode
1. if XG Mobile is activated Laptop GPU fan speed is normal (read by Armory Crate)
2. if XG Mobile is deactivated Laptop GPU fan speed is normal
 
this is what I think happened in Armory Crate
1. if XG Mobile is activated Laptop GPU fan speed is following CPU Fan speed
2. if XG Mobile is deactivated Laptop GPU fan speed is normal because the Laptop GPU is used normally

this is what I think happened in GHelper Custom fan profile
1. if XG Mobile is activated Laptop GPU fan speed is 0 because the Laptop GPU is sleeping
2. if XG Mobile is deactivated Laptop GPU fan speed is normal because the Laptop GPU is used normally

what I expect in GHelper Custom fan profile
1. if XG Mobile is activated Laptop GPU fan speed is following CPU Fan speed
2. if XG Mobile is deactivated Laptop GPU fan speed is normal because the Laptop GPU is used normally (DONE)

sorry If this is confusing.

**Comment by seerge** [comment]
@privacyonly the only "solution" that i see, is not to set a custom (regular)GPU fan profile if XGM custom fan profile is set. 

Try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/11592193/GHelper.zip)

**Comment by seerge** [comment]
@privacyonly and this ? Please upload a log from the run

[GHelper.zip](https://github.com/seerge/g-helper/files/11592326/GHelper.zip)

**Comment by privacyonly** [comment]
I just noticed something
while XG Mobile is activated GHelper is actually Showing GPU: 60C(this is XG Mobile temperature)
while XG Mobile is deactivated GHelper is actually Showing GPU:30C(this is Laptop GPU temperature)
[log.txt](https://github.com/seerge/g-helper/files/11592435/log.txt)

also when I apply Custom Fan profile, XG Mobile is not speeding up?

**Comment by seerge** [comment]
@privacyonly temperature that g-helper shows is taken from GPU driver / asus bios. It just shows what they provide.

As I have mentioned before - fan is controlled by bios, based on measuring bios does, not g-helper. Fan speed DOES NOT depend on what g-helper shows as temperature at all. 

As for the XGM fan, do I understand correctly that custom fan profile doesn't work anymore in this build ?

**Comment by privacyonly** [comment]
not 3080, it is 3070. btw here it is.
`
__GENUS          : 2
__CLASS          : __PARAMETERS
__SUPERCLASS     :
__DYNASTY        : __PARAMETERS
__RELPATH        :
__PROPERTY_COUNT : 1
__DERIVATION     : {}
__SERVER         :
__NAMESPACE      :
__PATH           :
device_status    : 65537
PSComputerName   :


`

**Comment by seerge** [comment]
@privacyonly thanks. I think it will change status if you would disconnect it completely.

I was testing a bit adjusted activation command for XGM (to tackle situation for some users who were getting lower power limits with XGM than normal https://github.com/seerge/g-helper/issues/729 )

Can you check this build with yours , and see if it still works / activates / deactivates (even after reboot) as it should ?

[GHelper.zip](https://github.com/seerge/g-helper/files/12546273/GHelper.zip)

**Comment by privacyonly** [comment]
> @privacyonly thanks. I think it will change status if you would disconnect it completely.
> 
> I was testing a bit adjusted activation command for XGM (to tackle situation for some users who were getting lower power limits with XGM than normal #729 )
> 
> Can you check this build with yours , and see if it still works / activates / deactivates (even after reboot) as it should ?
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/12546273/GHelper.zip)

yes, if you disconnect it, it will show device status 65536

btw, GHelper 119, BSOD, when activating xg mobile, Driver DMA violation.

**Comment by seerge** [comment]
@privacyonly ok, thanks for checking
