### ISSUE TITLE
[feature request] Undervolt amd/intel cpus

### ISSUE THREAD

**Issue by LJGJM** [seerge/g-helper#469]
**Is your feature request related to a problem? Please describe.**
I would like G-Helper to have cpu undervolt

**Describe the solution you'd like**
an option under the gpu overclock to undervolt the cpu, UXTU works for undervolting my cpu if you could import it. this option should be in the other tab

**Describe alternatives you've considered**
UXTU works, but i would like to do it from inside G-Helper

**Comment by seerge** [comment]
@LJGJM hello. I'm not a big fan of adding some hardcore tuning to the app. It's main purpose - to be lightweight and properly working replacement for AC :)

**Comment by LJGJM** [comment]
Thats fine, im just trying to maximise my battery

**Comment by seerge** [comment]
@LJGJM but how much battery do you gain if you undervolt for -15mv (from 800 or 1000mv total) ? 1-2% ? :)

**Comment by LJGJM** [comment]
I get arround 10-20% more  battery with a -30 undervolt (ryzen 5 4600h), @seerge

**Comment by ke1ne** [comment]
> @LJGJM but how much battery do you gain if you undervolt for -15mv (from 800 or 1000mv total) ? 1-2% ? :)

From my experience, it helped with cpu/igpu heat during the gaming or similar stuff

**Comment by seerge** [comment]
@LJGJM you are very lucky with your silicone then, mine goes nuts on -16 already

**Comment by seerge** [comment]
@LJGJM you can try build from this comment https://github.com/seerge/g-helper/discussions/583#discussioncomment-6200024

**Comment by seerge** [comment]
Added Live in 0.87
