### ISSUE TITLE
App scaling issue

### ISSUE THREAD

**Issue by Iapyx0** [seerge/g-helper#47]
![image](https://user-images.githubusercontent.com/122024739/222978693-bc362bb4-b1ed-4cb1-aacf-e37c6205f39a.png)

I'm having issues with app scaling on Windows 10.

This bug was introduced a few versions ago and it still hasn't been fixed in the latest release v0.15.1

My resolution is 1080p
Scaling @ 125%

**Comment by djolelp** [comment]
This is how an older version looks like
![image](https://user-images.githubusercontent.com/122024739/222978866-b62e32b9-311a-4db9-92a8-29fd5725f2f3.png)

**Comment by innoix** [comment]
#45 It looks like there is a pre-build version that fixes this issue (it fixed it for me)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/10892670/GHelper.zip)
can you try this build ?

**Comment by Iapyx0** [comment]
works fine!

**Comment by seerge** [comment]
In general, I can send a big hello to completely broken ui scaling in windows and their native tool visual studio. As a mac user I can't believe how bad things are here (still)

**Comment by seerge** [comment]
> works fine!

ok, i have just replaced a 0.15.1 with this fixed zip, and closing issue then
