### ISSUE TITLE
fans dont adhere to g helper settings

### ISSUE THREAD

**Issue by musabr274** [seerge/g-helper#472]
![image](https://github.com/seerge/g-helper/assets/131659642/b3523bf9-ed92-4e83-b1bf-01851d7f0e7e)

fan should technically be on no?

**Comment by musabr274** [comment]
48c and the fan is off but in settings its clearly supposed to be on

**Comment by seerge** [comment]
@musabr274 no, everything is exactly according to settings. Nearest dot with fans ON is 60C
