### ISSUE TITLE
[Feature request] Keyboard shortcut to open in foreground

### ISSUE THREAD

**Issue by EclipseMantis** [seerge/g-helper#473]
When I'm using an external keyboard, there is no Armory Crate button that I can use to open the G-Helper window. Instead, I have to click on the taskbar button.

Similar to how a shortcut was added to switch performance modes, I would like a shortcut to open the window so I can quickly view temps and modes that is accessible on an external keyboard.

Simply creating a shortcut to launch the .exe file does not work, because G-Helper is always running, just not in the foreground.

To me, the complexity of the shortcut is irrelevant; I'll simply create a macro and bind it to, say, an FN key.

And of course, thank you even if you don't implement this; G-Helper is so much better than AC.

**Comment by seerge** [comment]
You can check this build, Ctrl+Shift+F12 will toggle app window
[GHelper.zip](https://github.com/seerge/g-helper/files/11585533/GHelper.zip)

**Comment by EclipseMantis** [comment]
Thank you!

**Comment by TheBestPessimist** [comment]
@seerge is there a way to disable this shortcut? I'm using Intellij IDEA for development and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F12</kbd> is used in intellij quite a lot.

**Comment by seerge** [comment]
You can use and then add `` keybind_app : 0 `` entry to config.json 

[GHelper.zip](https://github.com/seerge/g-helper/files/11610446/GHelper.zip)

**Comment by TheBestPessimist** [comment]
works ✅

**Comment by aimagist** [comment]
`118` Should work for F7 but it's not happening

`  "keybind_app": 118`

**Comment by aimagist** [comment]
Oh! I supposed it would be jsut F7. Sorry!
Is there any way for it to just be F7? No ctrl alt shift

**Comment by seerge** [comment]
@aimagist if you are using latest 0.205 you can change a "modifier" [keys as explained here](https://github.com/seerge/g-helper/wiki/Power-user-settings#keybinding-modifier-keys)
