### ISSUE TITLE
Hide colour button on models of G14 that dont support colour change

### ISSUE THREAD

**Issue by goodboy10** [seerge/g-helper#474]
**Is your feature request related to a problem? Please describe.**
My laptop model has only solid white leds under the keyboard and the g-helper software still shows a colour button (I have model GA401QH)

**Describe the solution you'd like**
Check for specific model and hide the option

**Additional context**
![image](https://github.com/seerge/g-helper/assets/18133966/f3a760b1-f65a-4d16-a995-b45d86bd8f0b)

**Comment by goodboy10** [comment]
@seerge yes it does 
![image](https://github.com/seerge/g-helper/assets/18133966/7c496a5f-b536-412d-8f64-59cb4079fe5c)

**Comment by MDowski** [comment]
GA401IU (2020) - does not support.

**Comment by seerge** [comment]
As i understand 2020 model doesn't support anything keyboard related and 2021 model supports animations only? (with white color) ? Do 2021 models that support colors exist ?

**Comment by MDowski** [comment]
Only 2022 model and above support colors.

**G14 2020 models** (all): https://rog.asus.com/pl/laptops/rog-zephyrus/rog-zephyrus-g14-series/spec/
**G14 2020 models** (groups): https://rog.asus.com/laptops/rog-zephyrus/rog-zephyrus-g14-series/spec/
**G14 2021 models**: https://rog.asus.com/laptops/rog-zephyrus/2021-rog-zephyrus-g14-series/spec/

So it seems that in 2020 lineup we have: GA401IV, GA401IU, GA401II and GA401HE. On the other hand, GA401IVC may behave like 2021 model (it's ACRNM version).

In 2021 we have: GA401QM, GA401QE, GA401QC, GA401QH, and GA401HR, which seems to be 2020 model reheated in 2021 (4000 series CPU).

**Comment by seerge** [comment]
@goodboy10 @MDowski ok
this build will 
- hide color for all GA401 models
- hide mode dropdown for all GA401I models

I think this should cover all main cases. Layout (i.e. "extra" button) will stay same for now, as it's quite difficult to make it very different on the fly

[GHelper.zip](https://github.com/seerge/g-helper/files/11592148/GHelper.zip)
