### ISSUE TITLE
[Feature Request] Close window when focus is lost

### ISSUE THREAD

**Issue by djuniah** [seerge/g-helper#476]
It would be really nice if there was an option in the extras menu to allow the window to behave a bit more like the windows 11 system tray pop-up (the one with the toggles for wifi/bt/etc.).  Which basically means that if i press M4 to open g-helper, then it should close when i click off of it to a different app.  Currently, I find that if I click away from the g-helper menu, it doesn't pop back up when I press M4 again (it will either close it if it's open in the background, or if it was in the background before and was closed by the M4 button, it opens under the current window i'm using which completely hides it if the current window is maximized).  My hope is that this option would make it so that no matter what, when I press M4, the window pops up and it won't be covered by another window when it does.

**Comment by seerge** [comment]
@djuniah there is already a context menu https://github.com/seerge/g-helper/issues/307 in the app, that appears on right click of the mouse and behaves as you explained. 

So this is a duplicate request, i believe.

**Comment by seerge** [comment]
P.S. To force main app window always on top - check "Always on top" option under Extra

**Comment by djuniah** [comment]
Hello, no i don't mean for the context menu, I was referring to the main G Helper window.  Currently, if I open it with the M4 keyboard button, then click away to another window, and then press M4 again, one of two things happens:
1) The G-Helper window closes (so, in this context, I had pressed M4 because i wanted to see the g-helper window, but since it was already open, it just closed it)
2) In the instance where #1 already happened, The G-Helper main windows does re-open but it opens behind my current window so it isn't visible.

It seems like the only way to get it to reliably show when I press the M4 button is to close it via the X button in the top right beforehand.

**Comment by seerge** [comment]
@djuniah did you check "Always on top" under extra?

**Comment by djuniah** [comment]
Right, that does help with the "it opens under other windows" part of the issue, but then you have to close it with the X button.  What I was proposing is an option to have the window auto close when it loses focus.  That way it behaves like other windows system pop-ups such as those in the system tray (they all close when focus is lost).  Not really a huge issue by any means, it would just be nice to have it behave like the native windows pop-ups do.

**Comment by seerge** [comment]
@djuniah I just think that having right-click menu (that has all main modes already) and what you ask - is literally overkill (+ confusing).

1. You can "close" app by pressing M4 again (or Ctrl+Shift+F12)
2. What exactly do you change that often in the app, that you need to have a quick access too?

**Comment by djuniah** [comment]
Both very valid points. This is a super minor thing, I didn't mean to cause a ton of work/discussion over it, sorry about that.  The app is just styled in a way that closely resembles the windows pop-up quick controls menu and so i think i just expected it to behave in the same way.  I don't change things super often, but i do love that you have the current discharge wattage in there as well as fan speeds and temps, and i like to check them from time to time.

I'm a C# dev so I may just make a personal fork with that feature in it, no biggie.  Thanks for taking the time to look at the request though.

**Comment by seerge** [comment]
@djuniah every extra setting - is at least one more checkbox under "Extra" window (and there is already a bunch of such things that were added there cause someone has asked). I'm trying to keep at least some balance between tons of options, and simplicity.

Main window indeed resembles that windows popup. But hiding window after click wold make sense only for big "mode" buttons. Cause drop-downs / sliders / etc - expect multi-click interactions. Windows popup intentionally designed to avoid that. 

P.S. Did you know that system tray (G) icon has tooltip that actually shows discharge and fan speeds?

**Comment by djuniah** [comment]
Yup, i totally understand the need to balance the number of settings/options.  I didn't see the tooltip (I have all of the icons hidden except for wifi/autio/battery), but that is quite useful, thanks!

**Comment by seerge** [comment]
Just make that icon permanently visible (it's explained in readme), then you can 
1. from icon color see current GPU mode
2. have access to context menu
3. have mouseover tooltip
