### ISSUE TITLE
Full system crash due to some policy reset

### ISSUE THREAD

**Issue by jitendragarg** [seerge/g-helper#477]
**Describe the bug**
Laptop shuts down completely as if power button was pressed. Same thing happened in original armoury crate software. Last message in the system before shut down was "Process D:\Installers\GHelper.exe (process ID:7112) reset policy scheme from {381b4222-f694-41f0-9685-ff5bb260df2e} to {381b4222-f694-41f0-9685-ff5bb260df2e}". It is very similar to the error in armoury crate. Seems like a policy for lighting is getting reset causing keyboard to reset. 

**Clear scenario to Reproduce**
Steps to reproduce: 
None sadly. I can provide logs as needed, if it helps.  Video of the bug reproduced using off screen recording. https://youtu.be/TPZ0x0ezno0

**Expected behavior**
Application should not be resetting the lighting policy randomly. Unless I manually change lighting, lighting policy should stay the same.

**App Logs**
App log:
https://www.mediafire.com/file/t6n3x56prfzce0z/log.txt/file

Event Viewer log:
https://www.mediafire.com/file/t6n3x56prfzce0z/log.txt/file

**Screenshots or screencasts**
[If applicable, add screenshots to help explain your problem.](https://youtu.be/TPZ0x0ezno0)

**Desktop (please complete the following information):**
Windows 10 Pro
Asus G513QY Laptop

**Asus software**
- Armoury crate (or it's services installed) - No (cleaned with DDU)
- MyASUS installed - Yes
- Other Asus services running in background - ASUS OSD, ASUS Link, Armoury Crate Control Interface

**Additional context**
Had similar problem with Armoury crate. This happens randomly, but is reproducible enough in some games in some checkpoints. I have already tried reinstalling windows and everything else I could think of. It is possible that this bug is happening due to some lighting service conflict with some other system setting. 

If you can help me find the reason when this event is logged, I can help with debugging.

**Comment by seerge** [comment]
@jitendragarg hello, you can disable power scheme switching completely by going to Extra -> unchecking "Auto apply windows power modes".

But generally speaking, it looks like your system / hardware has some underlying serious issues, i would recommend either to reinstall system (or just install second one with dualboot) to troubleshoot. 

P.S. Your "event viewer log" is the same as app log.

**Comment by jitendragarg** [comment]
Hi, 

Apologies for adding wrong link. Here is the event viewer log. https://www.mediafire.com/file/zpbew0ctqwo6821/system_updated.xml/file
https://www.mediafire.com/file/0mawunsym158zoq/application_updated.xml/file

As you can see, this error of "reset policy scheme" shows up frequently, almost all the time closest to the crash. I have zero clue how this event is logged, and why both GUIDs are same. If there was a change in policy, I would assume the policies to have different GUIDs, which is definitely not the case with this error. 

As for resetting the policy, I agree that it should not happen at all unless I press a key to do so. But somehow it does happen unless the event being logged is an errant one. I noticed similar error in armoury crate tool as well. So, maybe you are just logging events directly sent by some other service? 

Anyway, for now, I have disabled "auto apply" option. I will update this report and close it accordingly.

**Comment by seerge** [comment]
@jitendragarg any updates on this?

**Comment by jitendragarg** [comment]
Still seeing the same error listed in event viewer. Haven't seen the crashes since uninstalling Adrenaline software, so crashes aren't related to this. But the error is definitely there. 

Latest logs https://www.mediafire.com/file/704n3dlmf6cbcrc/latest+system+log.xml/file

BTW I saw similar error when using armoury crate, so I am assuming you are using same APIs in the background to control the lighting. That might explain why this is happening.

**Comment by seerge** [comment]
@jitendragarg 

1. What do you understand under "lighting" ? 
2. Can you point out at specific line in a log that concerns you ?
3. Do those "events" appear if you don't run / quit g-helper ?

**Comment by jitendragarg** [comment]
Hi, 

I see similar event log when I switch lighting profile for keyboard and other lights (like logo in the back of the screen). So, I am assuming that this event is related to lighting profiles. E.g. if I switch from solid color to color cycle, I see similar event with different GUIDs, i.e. switching from GUID A to GUID B. 

Error message is always similar to "Process <process name> reset policy scheme from <GUID> to <GUID>".  E.g. 
<Message>Process D:\Installers\GHelper.exe (process ID:11400) reset policy scheme from {381b4222-f694-41f0-9685-ff5bb260df2e} to {381b4222-f694-41f0-9685-ff5bb260df2e}</Message> in the logs. This is a repeated event even when I don't change anything. 

Bigger concern is the GUIDs being same. If there is a change, GUIDs should be different. But, as you see, this event always tries to reset some policy without changing GUIDs, essentially changing A to A instead of A to B. So, I see a lot of "reset policy from GUID A to GUID A" logged over and over. 

As for quitting g-helper, I did the same and used the system normally for about 15 minutes. I did not see any similar events in those 15 minutes. But I will keep it off for couple hours and let you know if anything changes. For now, not seeing any logs if the application is closed. 

P.S. I am leaning towards some driver conflict at this point. Maybe some driver is crashing and recovering, causing this event to occur. It would also explain the same GUID in the events. Might also explain the laptop crashes, say if the driver failed to recover so BIOS forced a shutdown. And if it recovers, then this event gets logged. 

Anyway, I am honestly just trying to figure out when and how this event gets logged. That will help me diagnose this further on my end.

**Comment by seerge** [comment]
@jitendragarg 

1. I don't see anything mentioning lighting in event log, so still don't understand that. App communicates with USB device (keyboard) directly, it doesn't emit any events to windows logs

2. As for your policy scheme message, **it's not an error**. It literally says that `<Opcode>Info</Opcode>` It's a notification.
It's probably could be cause app sets a CPU boost setting in windows power plan based on whatever you have selected under fans+power.

I don't see any bugs here. So closing the issue for now.

**Comment by seerge** [comment]
@jitendragarg PS: If that notification bothers you so much - i have added a change in the app, and it will set new cpu boost setting only if it's currently different from what is selected in this build:

[GHelper.zip](https://github.com/seerge/g-helper/files/11624320/GHelper.zip)

So just set same boost setting in all 3 modes and it will never try to change it
