### ISSUE TITLE
Allow user to select specific aura settings to cycle through

### ISSUE THREAD

**Issue by jitendragarg** [seerge/g-helper#478]
**Is your feature request related to a problem? Please describe.**
Currently application displays all the possible aura lighting options even if they are not supported. This means user will have to select all of the options to cycle through them. 

**Describe the solution you'd like**
A menu option that allows selection of what lighting options user wants to cycle through. This will allow users to select the limited options that they prefer to use allowing cycling through the options faster.

**Describe alternatives you've considered**
No alternative as of now, as it is more of a "QoL" feature, and not a really important need.

**Comment by seerge** [comment]
@jitendragarg actually app tries to hide "not supported" modes. Please list what modes are not working for you and I can hide them for your model (family) ROG Strix G513QY_G513QY

**Comment by seerge** [comment]
This is full list of models for models containing "Strix" in the name. It could be that Strix and Strix Scar have different supported modes tho

```
        static Dictionary<int, string> _modesStrix = new Dictionary<int, string>
            {
                { 0, Properties.Strings.AuraStatic },
                { 1, Properties.Strings.AuraBreathe },
                { 2, Properties.Strings.AuraColorCycle },
                { 3, Properties.Strings.AuraRainbow },
                { 4, "Star" },
                { 5, "Rain" },
                { 6, "Highlight" },
                { 7, "Laser" },
                { 8, "Ripple" },
                { 10, Properties.Strings.AuraStrobe},
                { 11, "Comet" },
                { 12, "Flash" },
            };
```

**Comment by jitendragarg** [comment]
Hi. 

If it is already implemented, then you are right about the difference in models. In my case, Static, Breathe, Colour Cycle, Strobe and Rainbow are the only ones implemented. Rest of them just show up as Rainbow. 

Either way, if you think it is a good idea, there is a potential to implement a system to manually choose which options user would like to use.

Anyway, I will let you consider whatever is the best direction here.

Thanks.

**Comment by seerge** [comment]
@jitendragarg ok, do you know if all Strix (that are not Strix Scar) has same?

**Comment by seerge** [comment]
@jitendragarg check this build
[GHelper.zip](https://github.com/seerge/g-helper/files/11600125/GHelper.zip)

**Comment by jitendragarg** [comment]
This new build works. BTW, I tried to google for the list of available options, couldn't find any. So, I am unsure if it is for specific brand. 

Anyway, for now, I will use this new build. You can decide the next steps as needed.

**Comment by blazejkuklinski** [comment]
I have a ROG Strix G513QR and since v0.73 I only have 5 keyboard backlight options to chose from instead of 12. All of them have been working correctly before. I see no reason to remove them. 

The only problem I had was that "Star" was ignoring selected colors and always used red and white(?). 

I would love to get all those options back.

**Comment by seerge** [comment]
@blazejkuklinski I can put them back, it's just @jitendragarg who really confused me with that request. I will limit that "trimming" only to G513QY model.

Try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/11642307/GHelper.zip)

**Comment by blazejkuklinski** [comment]
Looks very good. Thanks!
