### ISSUE TITLE
2022 Flow X16 GV601RM: Screen refresh rate is stuck at 64 Hz

### ISSUE THREAD

**Issue by Jim01230** [seerge/g-helper#479]
After using G Helper, my screen's refresh is stuck at 64 Hz and I am unable to set it to 165 Hz. The options for it is completely gone under  the display settings:
![image](https://github.com/seerge/g-helper/assets/134969123/50e66a49-42ab-4f5b-b851-dda70b99059a)

The option to change the refresh on the  G Helper window is completely grayed out:
![image](https://github.com/seerge/g-helper/assets/134969123/c72b85f7-8db8-4f6b-be5e-492d8c95c2f5)

I have ran the [debloat.bat](https://raw.githubusercontent.com/seerge/g-helper/main/debloat.bat) file.

I have also uninstalled Armoury Crate. 
MyASUS is still installed.

**Comment by seerge** [comment]
@Jim01230 can you open Device Manager, and check  if your GPU is enabled and ok there ?

**Comment by LJGJM** [comment]
Just use Monitor CRU and add them back

**Comment by seerge** [comment]
@Jim01230 any updates ?

**Comment by Jim01230** [comment]
Yes, I re installed my Nvidia (which did not work) and then AMD Adrenaline software and now it is showing both 65 and 165Hz options. I was able to reinstall g helper without it affecting these settings.
