### ISSUE TITLE
G14 2022 - Fan curves aren't respected

### ISSUE THREAD

**Issue by GlaZedBelmont** [seerge/g-helper#480]
Just installed latest version, on version 69 they were also not respected, I don't have armory crate installed so I'm wondering why they just aren't using ghelper's curves

![image](https://github.com/seerge/g-helper/assets/48196637/e47fbfe1-fee9-4167-8dcc-2a604bcdf88f)

**Comment by seerge** [comment]
@GlaZedBelmont bios doesn't always "stick" to fan curve super precisely, it can fluctuate a bit  (and it's not far from what you have set) + it has hysteresis. So I don't see a problem here.

**Comment by GlaZedBelmont** [comment]
alright, thanks, just making sure
