### ISSUE TITLE
ASUS BIOS rejected fan curve

### ISSUE THREAD

**Issue by TheUnknown249** [seerge/g-helper#482]
**Is your feature request related to a problem? Please describe.**
Using your incredible app on my maybe old 2019 TUF laptop :). The problem is when I try apply custom fan curve, I get the error I said.

**Describe the solution you'd like**
Is there any way to change this? I know that there is almost nothing you can change in the app to fix this since it's a bios restriction, but is there anyway to override this bios thing?

**Comment by seerge** [comment]
@TheUnknown249 then 99% it's not supported by your laptop. I assume you didn't had custom curves in AC ?

**Comment by TheUnknown249** [comment]
Unfortunately no, i didn't have those in AC.
Do you know any other workarounds as modded bios or something?
Thanks.

**Comment by seerge** [comment]
@TheUnknown249 no, i don't think that's possible then

**Comment by TheUnknown249** [comment]
Thanks again for making this great app :)
