### ISSUE TITLE
If RTX 3060 is disabled when G-Helper starts then its clock/power controls are not available even when it is later enabled.

### ISSUE THREAD

**Issue by mikezila** [seerge/g-helper#483]
**Describe the bug**
G-Helper presents sliders to control the clocks/power of the RTX 3060 present in the GA401QM. However these sliders are only available if the RTX 3060 was powered on when G-Helper started. If the dGPU is off when you start the application, the sliders are missing even if you enable the dGPU and reload the Fans+Power panel. Additionally if you start G-Helper with the dGPU enabled, and then turn it off, the sliders will still be present, but instead of showing the GPU's correct name (such as "GeForce RTX 3060 Laptop GPU") it will just say "GPU", and the sliders will do nothing.

**Clear scenario to Reproduce**
Start G-Helper while the dGPU is powered off. You can do this easily by turning off the dGPU using G-Helper itself, then closing and reopening G-Helper.

**Expected behavior**
The clock/power sliders should be gone when the dGPU is off, but present when it is on, even if the dGPU was not on when the application started.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11594339/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GA401QM

**Asus software**
No ASUS software is currently installed, though both Armory Crate and myASUS were installed in the past.

**Comment by seerge** [comment]
@mikezila i'm actually looking at log and it reconnects to GPU driver after enabling gpu back (so clocks should be there)

It just takes a few seconds to do so in background. Do you open fans+power immediately after enabling GPU ? does it happen if you wait for a few seconds? 

```
5/29/2023 11:08:26 AM: ------------
5/29/2023 11:08:26 AM: App launched: ROG Zephyrus G14 GA401QM_GA401QM :0.69.0.0en-US.
5/29/2023 11:08:27 AM: AutoSetting for Online
5/29/2023 11:08:27 AM: BatteryLimit = 100 : OK
5/29/2023 11:08:27 AM: BatteryLimit = 100 : OK
5/29/2023 11:08:27 AM: PerformanceMode = 0 : OK
5/29/2023 11:08:27 AM: Boost 0
5/29/2023 11:08:27 AM: KB Backlight:5D-BA-C5-C4-00
5/29/2023 11:08:27 AM: Monitor Power On
5/29/2023 11:08:28 AM: GPUEco = 0 : OK
5/29/2023 11:08:28 AM: Eco flag : 0
5/29/2023 11:08:28 AM: Mux flag : -65536
5/29/2023 11:08:31 AM: GET GPU CLOCKS: 0, 0
5/29/2023 11:09:40 AM: GPUEco = 1 : OK
5/29/2023 11:09:40 AM: PerformanceMode = 2 : OK
5/29/2023 11:09:40 AM: Boost 0
5/29/2023 11:09:40 AM: Eco flag : 1
5/29/2023 11:09:40 AM: Mux flag : -65536
5/29/2023 12:15:03 PM: GPUEco = 0 : OK
5/29/2023 12:15:04 PM: Eco flag : 0
5/29/2023 12:15:04 PM: Mux flag : -65536
5/29/2023 12:15:53 PM: GPUEco = 1 : OK
5/29/2023 12:15:53 PM: Eco flag : 1
5/29/2023 12:15:53 PM: Mux flag : -65536
```

**Comment by mikezila** [comment]
It may have been that I was opening the clocks screen too quickly. If I wait ~5 seconds it looks to work normally every time. 

Though this does expose a UI inconsistency where the sliders are totally missing if the dGPU has not been "seen" since G-Helper started, but are left there if the dGPU has been seen but then later disabled.

**Comment by seerge** [comment]
@mikezila well, delay is unfortunately needed (if you try to connect to driver immediately - it will fail, as windows itself with it's device manager is not instant neither). 

I can try to add a second attempt to connect to driver on the moment you open fans+power, but there are chances that that attempt won't work if it happens too fast still :) 

Check this build

[GHelper.zip](https://github.com/seerge/g-helper/files/11594399/GHelper.zip)

**Comment by mikezila** [comment]
Everything works correctly when using the build provided. Thank you for taking a look!

**Comment by seerge** [comment]
@mikezila great, I will include it in next release then
