### ISSUE TITLE
Visual Bug: Missing space between the GPU text and Fan text

### ISSUE THREAD

**Issue by schm1dtxbox** [seerge/g-helper#486]
Bug: As of the latest G-Helper releases/commits (0.72 and 0.70 were what I tested), the GPU fan text seems to look rather unsightly, reading as "GPUFan" instead of as "GPU Fan" with a space between the two words, as can be seen below.
<img width="286" alt="image" src="https://github.com/seerge/g-helper/assets/36817325/71dd21a9-9bea-469d-b406-999a2e700601">

1. Launch the latest G-Helper releases.
2. Ensure the dGPU is on/active such that the Fan reading is available, but not that the temperature is also visible (e.g. when using Optimus with no applications using the dGPU open in the background).
3. Observe the lack of a space in the label between 'GPU' and 'Fan'.

Expected behaviour: The text should read out as "GPU Fan:" with a space in-between.

Note: Am I being a bit too nit-picky here? Maybe it's my OCD kicking in or something I assume, but this wasn't present on v0.69 and earlier I guess.

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11600129/GHelper.zip)
Try this build

**Comment by schm1dtxbox** [comment]
Yup, the bug's fixed there now it seems.
