### ISSUE TITLE
Cannot control keyboard backlight on GA402XI

### ISSUE THREAD

**Issue by tjames192** [seerge/g-helper#490]
**Describe the bug**
Cannot control keyboard backlight on GA402XI

- If I keep ASUS Optimization, keyboard backlight cannot be controlled by Fn + F2/F3, brightness slider in GHelper cannot.
- If I disabled ASUS Optimization, both Fn + F2/F3 and brightness slider in GHelper cannot control, but it does show GHelper's OSD.

**Clear scenario to Reproduce**
Either use control keyboard brightness slider in GHelper app or Fn + F2/F3

**Expected behavior**
Keyboard brightness changed acccording to the setting.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11609396/log.txt)

**Desktop (please complete the following information):**

OS: Windows 10 Pro 22H2
Laptop model G14 GA402XI
GHelper 0.67, 0.69, 0.73

**Asus software**

Armoury crate not installed
MyASUS not installed
Debloated ASUS Service and tried enabled/disabled ASUS Optimization

**Comment by seerge** [comment]
@tjames192 if you keep optimization service – it controls brightness from hotkeys. And since it doesn't work for you - i think your problem lays outside of g-helper.

Does checking / unchecking Awake flag under Extra do anything for you?

**Comment by tjames192** [comment]
Toggling awake flag does not do anything different for me.
It is quite possible that my problem is outside of g-helper since I just did a clean install of windows and drivers.

**Comment by seerge** [comment]
@tjames192 backlight control via hotkeys should work w/o anything installed, just asus optimization (that was probably installed by windows update).

You may try to do a hard reset, turn off laptop and press-hold power button for 40 seconds. Then boot normally. It should "reset" hardware components, incl keyboard.

Does keyboard blink white when you power on / power off laptop at least?

**Comment by tjames192** [comment]
resolved.

Reinstalling the esupport software fixed the backlight issue.
re-ran the debloat script

so now its just a matter of figuring out which software needs to be installed.

I'm assuming may be AURA lighting effect add-on.
Thanks for the quick response!

**Comment by seerge** [comment]
@tjames192 aura is for diffent color backlight modes (from armoury), it's not needed for backlight to work as is. But i'm glad it's resolved.
