### ISSUE TITLE
Appears to be closing then opening again (v.0.69)

### ISSUE THREAD

**Issue by Eurydicx** [seerge/g-helper#495]
The Bug
  The program seems to close really fast then open again really fast. This also occurs to me when launching armory crate (every time I close it forces itself to open on top of other apps only way I found it to stop is if I open task manager and close its background processes and then the app itself really fast) Which is why I decided to install G helper.
  I did download a pre release version but the same thing happened so I went to download the first official latest (being 0.69)

Clear scenario to Reproduce
My first time launching it and this happened (sorry I know this doesn't help much)

**App Logs**
5/31/2023 4:02:15 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:16 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:17 PM: WMI event 56
5/31/2023 4:02:18 PM: WMI event 56
5/31/2023 4:02:18 PM: WMI event 56
5/31/2023 4:02:18 PM: WMI event 56
5/31/2023 4:02:18 PM: WMI event 56
5/31/2023 4:02:18 PM: WMI event 56
5/31/2023 4:02:18 PM: WMI event 56
( It just keeps going)

Desktop 
 - OS Windows 11
 - Asus Tuf Dash 15 (2021)

*Additional context*
 I did not have Microsoft. Net 7 nor the ASUS system control interface so I downloaded them both correctly.
 I've linked a video since I thought it would clarify my problem more.

https://github.com/seerge/g-helper/assets/135170980/aca78824-0f10-4b3a-b826-fa1eafd1920f

**Comment by seerge** [comment]
@Eurydicx looks like your M4 key is stuck and keep spamming.

Can you try to stop / disable "Asus optimization service" and see if it still happens?

**Comment by Eurydicx** [comment]
@seerge Sorry I have no idea what that is im very new to this can you clarify what an m4 key is . and also how to stop or disable Asus optimization service. Thanks for the fast reply also sorry if you dont like pings first time doing this.

**Comment by seerge** [comment]
@Eurydicx M4 is a key that launches armoury on your keyboard (it could be called ROG key, or something like that)

To stop optimization service, launch Services app from start menu, find "Asus optimization service" there, and click Stop :)

Then relaunch g-helper and see if it has any effect

**Comment by Eurydicx** [comment]
@seerge Okay so it fixed the armory crate app  but not g helper 

https://github.com/seerge/g-helper/assets/135170980/de9cb630-ad65-4f50-98b7-deafb9087e1c

https://github.com/seerge/g-helper/assets/135170980/bf69c7b1-4319-4663-8175-6bf1d04c1861

**Comment by seerge** [comment]
@Eurydicx AC doesn't close on ROG-key press, so it just opens. I assume if you close AC window it instantly pops up again?

Looks like it's hardware issue with your button, it literally spams itself.

**Comment by Eurydicx** [comment]
@seerge Yes exactly it would open itself back up again but when i stoped the optimization it seems to fix the problem with AC... probalby shouldve mentioned it before but i spilled water on the keyboard and none of the keys except volume up,down and mute mic work.

**Comment by seerge** [comment]
@Eurydicx ye, but when optimization is stopped - your hotkeys won't work at all :) (that's why AC doesn't open, it's just not aware that key is spamming itself)

G-helper listens for hotkeys by itself, that's why it still opens/closes.

**Comment by Eurydicx** [comment]
Ohhh okay well thanks for the help. guess I can't use g helper. Alright thanks for the info

**Comment by Eurydicx** [comment]
I'm honestly shocked you knew all of that, I'm impressed.

**Comment by seerge** [comment]
@Eurydicx try this build, it will completely ignore your ROG key. Rest of the hotkeys should work normally
[GHelper.zip](https://github.com/seerge/g-helper/files/11619132/GHelper.zip)

**Comment by seerge** [comment]
@Eurydicx did you had a chance to try the build ? Anyway, completely disabling ROG key is maximum i can do :) that should solve your specific problem. But I would advice in a long term to look into fixing keyboard itself.

**Comment by Eurydicx** [comment]
> @Eurydicx did you had a chance to try the build ? Anyway, completely disabling ROG key is maximum i can do :) that should solve your specific problem. But I would advice in a long term to look into fixing keyboard itself.

So sorry i forgot about this as i created a github act just to comment; yes i downloaded it and it works thank you very much im not sure if your gonna answer but when stopping the asus optimization service in the services app it re enables itself after a restart. which causes AC to open and not be able to be closed unless i use task manager and stop all asus related apps then it closes AC for good but it gets tiring and its annoying as AC forces itself on top of every app even when i minimize it forces itself on top of whatever im doing. or is that part of the damage to the keyboard? in other words, is there a way to permanently stop the asus optimization service or does it force itself to start again because of the keyboard damage? i like g helper because its very minimalistic and i was hoping to replace AC for good.

**Comment by seerge** [comment]
@Eurydicx button under ``Extra`` stops and disables services. So they won't start again unless you update Asus System Control Interface.

Keep in mind, that it does not stop AC from working, only MyASUS related stuff that you can't stop anyhow else.

For AC - you can use official uninstalller
