### ISSUE TITLE
Add Language section

### ISSUE THREAD

**Issue by etylix** [seerge/g-helper#498]
**Is your feature request related to a problem? Please describe.**
User usually set Windows language as English, but may use their primary language for apps

**Describe the solution you'd like**
Add a "Language" section under extra setting

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by seerge** [comment]
@etylix hello, you can set language already, but in config by adding 
`` "language" : "vi" `` (or any appropriate locale) to the config file

**Comment by xschwi** [comment]
> @etylix hello, you can set language already, but in config by adding `"language" : "vi"` (or any appropriate locale) to the config file

When I add `"language" : "vi"` to config file and then open GHelper, nothing happens. It looks like "config.json" values getting restored, after re-opening app, and `"language" : "vi"` disappears.

I've tried to change file property to "read only", but still doesn't work

**Comment by seerge** [comment]
@xschwi try to edit config before starting g-helper, and it will be fine

**Comment by xschwi** [comment]
that's what I did, tried couple of times, and still nothing

**Comment by seerge** [comment]
Then you are missing comma probably (at the end)

**Comment by xschwi** [comment]
Yeah, now it works. Thank you!
