### ISSUE TITLE
Feature Request: Add Option to disable Vari-Bright (Color-Shifting; Solution inside)

### ISSUE THREAD

**Issue by Astorek86** [seerge/g-helper#499]
**Is your feature request related to a problem? Please describe.**
I did a fresh install on a Zephyrus G14 (2022; GA402RK, Ryzen 9 6900HS, AMD RX 6800S). I just installed the Drivers from the ASUS-Homepage (including Chipset and Graphics), but no Armory Crate or something like that. Only G-Helper.

One Problem I have: After I unplug my Battery, the colors change to a weird, "ugly" pattern, contrast ist partially fading away.

**Describe the solution you'd like**
According to [this Reddit-Post](https://redd.it/p63yct), this Problem is caused to a Feature called "Vari-Bright", which can be disabled through Registry:
`HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0001`

Descriptions reads: "Add a new DWORD (32-Bit) called `PP_VariBrightFeatureEnable`, set it to `0` and reboot."

Which - I can confirm - works! I have no Color-Shifting-Problem anymore.^^

It would be really nice if you add, for example, a Checkbox called "Vari-Bright". If the Checkbox is ticked, it sets `PP_VariBrightFeatureEnable` to `1`. If unticked, it sets this to `0`. Maybe a Messagebox like "need to restart to change your settings" could be appear after changing the Registry-Key.

**Describe alternatives you've considered**
It seems that is also possible to activate that Option through AMD Control Center, or through Armory Crate. But ASUS doesn't include any AMD-GUI to their Drivers and I really, really don't want to install Armory Crate, I want to avoid this Bloatware as much as I am able to^^.

**Additional context**
Nothing Problem-specific anymore, but I want to say "Thank you" for such a great piece of Software!^^

**Comment by seerge** [comment]
@Astorek86 for me that reg-adjust does nothing. I assume it could be controlled somehow via AMD driver API, but I can't find any reasonable documentation about this

**Comment by Astorek86** [comment]
> **I re-checked with appropriate adrenaline checkbox.**

Ah, maybe that could explain it. My fresh installed Windows 11 has never seen a GUI to configure AMD-Graphics, neither the Radeon-Software on the Microsoft Store, nor the Adrenaline-Software provided by ASUS and/or AMD...

**Comment by seerge** [comment]
@Astorek86 hello, I have found a right methods in AMD official API, and added AMD Varibright checkbox to Extra settings.

For me it works, it's even reflected inside Adrenaline software. But you need to kill "AMD software process" and run it again to see changes in realtime (as it simply doesn't re-read settings every time, it reads them only on start)

[GHelper.zip](https://github.com/seerge/g-helper/files/11645890/GHelper.zip)

**Comment by SkewelVsAll** [comment]
> [@Astorek86](https://github.com/Astorek86) hello, I have found a right methods in AMD official API, and added AMD Varibright checkbox to Extra settings.
> 
> For me it works, it's even reflected inside Adrenaline software. On change of varibright app will kill "AMD software process" so it can re-load settings (as it simply doesn't re-read settings every time, it reads them only on start)
> 
> [GHelper.zip ](https://github.com/seerge/g-helper/files/11645901/GHelper.zip)

Sorry for reviving this issue, but can the option be used on laptop's of other brands such as Lenovo, Dell or Acer?
