### ISSUE TITLE
[bug] Zephyrus G15 2021, v0.15.2 crashed: AniMe Matrix control device was not found on your machine

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#50]
Got the latest version silently crashed when started. It seems there is a need to check is AniMe Matrix available on the device.

Win 11, Zephyrus G15 2021, GH v0.15.2

```
Application: GHelper.exe
CoreCLR Version: 7.0.323.6910
.NET Version: 7.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'GHelper.Program' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'GHelper.SettingsForm' threw an exception.
 ---> System.IO.IOException: AniMe Matrix control device was not found on your machine.
   at Starlight.Communication.Platform.WindowsUsbProvider..ctor(UInt16 vendorId, UInt16 productId, Int32 maxFeatureReportLength)
   at Starlight.Communication.Device..ctor(UInt16 vendorId, UInt16 productId, Int32 maxFeatureReportLength)
   at Starlight.AnimeMatrix.AnimeMatrixDevice..ctor()
   at GHelper.SettingsForm..cctor()
   --- End of inner exception stack trace ---
   at GHelper.SettingsForm..ctor()
   at GHelper.Program..cctor()
   --- End of inner exception stack trace ---
   at GHelper.Program.Main()
```

UPD. GH v0.15.1 works OK.

**Comment by d-anez3** [comment]
Same thing here on G14 2021

Application: GHelper.exe
CoreCLR Version: 7.0.323.6910
.NET Version: 7.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'GHelper.Program' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'GHelper.SettingsForm' threw an exception.
 ---> System.IO.IOException: AniMe Matrix control device was not found on your machine.
   at Starlight.Communication.Platform.WindowsUsbProvider..ctor(UInt16 vendorId, UInt16 productId, Int32 maxFeatureReportLength)
   at Starlight.Communication.Device..ctor(UInt16 vendorId, UInt16 productId, Int32 maxFeatureReportLength)
   at Starlight.AnimeMatrix.AnimeMatrixDevice..ctor()
   at GHelper.SettingsForm..cctor()
   --- End of inner exception stack trace ---
   at GHelper.SettingsForm..ctor()
   at GHelper.Program..cctor()
   --- End of inner exception stack trace ---
   at GHelper.Program.Main()

**Comment by ONIMUSHA117** [comment]
Hi,

I have the same thing happened on my G14 2022, 6700s. However, I also got some issues with Task Scheduler. Please check belows.
>  Application: GHelper.exe
> CoreCLR Version: 7.0.323.6910
> .NET Version: 7.0.3
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.UnauthorizedAccessException: Access is denied. (0x80070005 (E_ACCESSDENIED))
>    at Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.RegisterTaskDefinition(String Path, ITaskDefinition pDefinition, Int32 flags, Object UserId, Object password, TaskLogonType LogonType, Object sddl)
>    at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String path, TaskDefinition definition, TaskCreation createType, String userId, String password, TaskLogonType logonType, String sddl)
>    at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String path, TaskDefinition definition)
>    at Startup.Schedule()
>    at GHelper.SettingsForm.checkStartup_CheckedChanged(Object sender, EventArgs e)
>    at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
>    at GHelper.SettingsForm.SetStartupCheck(Boolean status)
>    at GHelper.Program.Main()

Also this one:

> Application: GHelper.exe
> CoreCLR Version: 7.0.323.6910
> .NET Version: 7.0.3
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.TypeInitializationException: The type initializer for 'GHelper.Program' threw an exception.
>  ---> System.TypeInitializationException: The type initializer for 'GHelper.SettingsForm' threw an exception.
>  ---> System.IO.IOException: AniMe Matrix control device was not found on your machine.
>    at Starlight.Communication.Platform.WindowsUsbProvider..ctor(UInt16 vendorId, UInt16 productId, Int32 maxFeatureReportLength)
>    at Starlight.Communication.Device..ctor(UInt16 vendorId, UInt16 productId, Int32 maxFeatureReportLength)
>    at Starlight.AnimeMatrix.AnimeMatrixDevice..ctor()
>    at GHelper.SettingsForm..cctor()
>    --- End of inner exception stack trace ---
>    at GHelper.SettingsForm..ctor()
>    at GHelper.Program..cctor()
>    --- End of inner exception stack trace ---
>    at GHelper.Program.Main()

**Comment by seerge** [comment]
I have pulled our 0.15.2 for now, will add a check and upload fix later:)

**Comment by seerge** [comment]
Can you check if https://github.com/seerge/g-helper/releases/tag/v0.15.3 runs ok ?

**Comment by ONIMUSHA117** [comment]
> Can you check if https://github.com/seerge/g-helper/releases/tag/v0.15.3 runs ok ?

Hi @seerge,

The new version works well. Thank you for your quick fixes. Really awesome program you have here.

**Comment by seerge** [comment]
Ok, cool. In https://github.com/seerge/g-helper/releases/tag/v0.16 I have set that whole section dedicated to animatrix will simply disappear on models with no support. Can you guys check and tell if main form / ui looks ok after ?

**Comment by ONIMUSHA117** [comment]
> Ok, cool. In https://github.com/seerge/g-helper/releases/tag/v0.16 I have set that whole section dedicated to animatrix will simply disappear on models with no support. Can you guys check and tell if main form / ui looks ok after ?

Yeah, I don't have the animatrix. So I couldn't see it. Glad that it works out. Also could you do that with the color options? I have the white colour backlit keyboard so no RGB. 

Thanks.

**Comment by seerge** [comment]
Color options are more tricky, as I don't get feedback from a device if they are supported (unlike with animatrix). The only way is just to manually disable color button based on model name :)

**Comment by d-anez3** [comment]
> @ke1ne , @d-anez3 can you check if 0.16 runs (and looks) ok in your cases - then I will close an issue :) 

All good here

**Comment by ke1ne** [comment]
Seems to be OK. Thank you very much!
