### ISSUE TITLE
Some functions lack Chinese

### ISSUE THREAD

**Issue by zSXHY** [seerge/g-helper#500]
I am sorry that I am not very good at communicating in English, so all the content is translated with the help of translation software

I noticed that some functions in G-helper 0.74 are missing Chinese translations. I hope you can add these translations

For example:
“Backlight timeout battery”
“Backlight timeout when plugged(0 - always on)”
“Process Fn+F hotkeys without FN”
“Keep GPU disabled on USB-c charger in Optimized mode”

**Comment by kuonji-arisu** [comment]
> @zSXHY you can provide translations and I will add them

I’m not sure if he means Simplified Chinese or Traditional Chinese, but it does lack some translations in Simplified Chinese. Here are these translations I provide:
Backlight timeout battery: 使用电池时的背光超时时间
Backlight timeout when plugged(0 - always on): 插入电源时的背光超时时间 (0 - 始终开启)
Process Fn+F hotkeys without FN: 无需FN处理 Fn+F 热键
Keep GPU disabled on USB-c charger in Optimized mode: 在自动切换模式下 使用USB-C充电器时禁用GPU（Translation: I’m not sure about this, because I don’t understand the function of this feature and why it is needed.）
Stop all app used dGPU on ECO mode: 在使用集显模式时停止所有使用dGPU的应用

**Comment by seerge** [comment]
@kuonji-arisu try this one
[GHelper.zip](https://github.com/seerge/g-helper/files/11623409/GHelper.zip)

**Comment by zSXHY** [comment]
What is missing is simplified Chinese

**Comment by kuonji-arisu** [comment]
> @kuonji-arisu try this one [GHelper.zip](https://github.com/seerge/g-helper/files/11623409/GHelper.zip)
Thank you! I just edited my reply, added and corrected some translations,  and added some commas.

**Comment by seerge** [comment]
@zSXHY i have added translations that @kuonji-arisu just posted, check build from previous post

**Comment by kuonji-arisu** [comment]
> @kuonji-arisu try this one [GHelper.zip](https://github.com/seerge/g-helper/files/11623409/GHelper.zip)

Thank you! I just edited my reply, corrected some translations and added some commas.

**Comment by seerge** [comment]
@kuonji-arisu @zSXHY updated : 
[GHelper.zip](https://github.com/seerge/g-helper/files/11623533/GHelper.zip)

**Comment by kuonji-arisu** [comment]
> @kuonji-arisu @zSXHY updated : [GHelper.zip](https://github.com/seerge/g-helper/files/11623533/GHelper.zip)

Great! I see that these translations have been successfully applied to the application, thank you!

**Comment by zSXHY** [comment]
thank you

**Comment by seerge** [comment]
Oke, I will include it in next release. Closing as completed

**Comment by zSXHY** [comment]
@seerge 
Another thing I've noticed missing is the translation of the options in the CPU Boost options, which are:

“Disabled”: “禁用”
"Enabled":"启用"
"Aggressive":"激进"
"Efficient Enabled":"高效启用"
"Efficient Aggressive":"高效激进"

**Comment by seerge** [comment]
@zSXHY those settings are from windows power plan. I would prefer to keep them as system calls those modes.

**Comment by seerge** [comment]
@kuonji-arisu this.

That dropdown is not translated in any language on purpose
