### ISSUE TITLE
FN+f5 shortcut mismatch

### ISSUE THREAD

**Issue by eiirk** [seerge/g-helper#501]
I have noticed that when you have both G-Helper and Armoury Crate installed and use the FN+f5 to switch between different modes (Silent, Performance/Balanced, Turbo), the modes does not switch in the same order. If you start on "Silent" in both Armoury Crate and G-Helper it works up until "Turbo". Then Armoury Crate goes back down to "Performance" while G-Helper starts over at "Silent". I'm not shure if this is a huge problem or if it even matters, but for us who want to have both applications installed it would help to make the order the same.

What I'm asking is if you could make it switch modes like in Armoury Crate, maybe add it as an option? Then when you use the FN+f5 shortcut it switches like this: "Silent -> Performance/Balanced -> Turbo -> Performance/Balanced -> Silent -> Performance/Balanced etc.?

**Comment by seerge** [comment]
@eiirk You can always run SHIFT + FN + F5 to cycle backwards :) and FN+F5 to cycle forwards. That gives you total control ;)
