### ISSUE TITLE
Add ability to turn on keyboard backlight on sunset

### ISSUE THREAD

**Issue by plotkabytes** [seerge/g-helper#503]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Ability to turn on keyboard backlight on sunset / given hour would be great.
Maybe add button under "Laptop keyboard" section.

**Additional context**
 I have white G14 with white keyboard backlight - during day it looks awful. After sunset I'm always searching for a button to turn on keyboard backlight.

**Comment by seerge** [comment]
@plotkabytes hello, that's a good idea, but main problem is that to know WHEN sunset/sunrise happens app will have to run some kind of a timer in background all the time. I'm a bit concerned about extra resource usage in this case :|

**Comment by TomBonnot** [comment]
Or just like f.lux, you have set timer ? No need of an external app or API, maybe it is a lot for something really optional ?

**Comment by seerge** [comment]
I digested this a bit, I won't be adding this. As it's literally too much hassle (extra timer constantly running) for a small QoL change. Sorry.
