### ISSUE TITLE
Toggle Fn lock via Fn double-tap

### ISSUE THREAD

**Issue by Fatalution** [seerge/g-helper#505]
**Is your feature request related to a problem? Please describe.**
Fn lock is a godsend! Now, would be neat if we could trigger it at will and without opening up the Extra settings menu

**Describe the solution you'd like**
I would suggest this being done with Fn button double tap.

**Comment by Fatalution** [comment]
> @Fatalution Fn button by itself, doesn't emit any codes, so you can't bind anything on it. It works only in conjunction with F-row and couple of other keys.

I see. Then, would be neat if I could bind it in this menu here: 
<img width="193" alt="image" src="https://github.com/seerge/g-helper/assets/17583199/5e3802d5-5344-4491-9e0f-67ffed82078c">

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11628217/GHelper.zip)
This build should have FN+C (the only available combination next to F-row), and option to bind it to Fn-Lock switch

**Comment by Fatalution** [comment]
@seerge thank you! 

Sorry for another ping, would this feature be included in the next version of the GHelper release? :D 
Or should I just stay on this one if I want to retain the functionality you've added

**Comment by seerge** [comment]
@Fatalution ye, it will be in 0.76
