### ISSUE TITLE
Fan/Extra Menu isn't shown after alt-tabbing

### ISSUE THREAD

**Issue by moritzbeck01** [seerge/g-helper#508]
**Describe the bug**
Basically title. The main menu is shown, but not the one on the side.

**Clear scenario to Reproduce**
1. Open GHelper
2. Click on either Fan/Performance or Extra
3. A menu will open on the side
4. Alt-Tab so another window is shown and GHelper is minimized
5. Alt-Tab back

**Expected behavior**
Both the main menu and the menu on the side are shown.

**Actual behaviour**
Only the main menu is shown. I have to click on Fan/Performance or Extra respectively *twice* so that the side menu is shown again. (One for closing it in the background and then one for opening it again in the foreground?)

**App Logs**
N/A

**Screenshots or screencasts**
Will provide asap if not reproducable by description.

**Desktop**
 - Windows 11
 - X13

**Asus software**
- none
- default drivers

**Additional context**

**Comment by seerge** [comment]
@moritzbeck01 that's how windows work, you atl tab between windows, and fans+power is a separate window.

**Comment by seerge** [comment]
@moritzbeck01 there is no separate icon in task bar - yes, but there is a separate window in alt+tab menu (just hold alt after clicking tab)

**Comment by moritzbeck01** [comment]
I can assume that it should be there and I know how I would reach it - but it's not there for me.
And tbh I still think the side menu should show up when alt tabbing to the main menu (and the other way around too I guess) since it's a sub menu that's only reachable by the main menu.

**Comment by seerge** [comment]
Like in this build ? [GHelper.zip](https://github.com/seerge/g-helper/files/11634086/GHelper.zip)

**Comment by moritzbeck01** [comment]
Yes, though this introduced some new unintended behaviour: I can't close the main menu when the side menu is open. I have to first close the side menu, then the main menu. I would expect that closing the side menu only closes the side menu (which is the case) and the main menu closes both (which isn't the case).

Additionally, I noticed these things:
- when alt-tabbing, there are no icons for the GHelper windows
- only the main menu is shown in the task bar, never the side menu
- the task bar is also missing icons when you hover over it

**Comment by seerge** [comment]
@moritzbeck01 I know that, cause I didn't find a way to bring a "second" window on top when main window get's focus. It seem to be quite tricky in windows. 

I don't understand what do you mean under "task bar icons" ? Cause main window always adds itself to the taskbar. Or you mean system tray?

Anyway, i have changed some settings for fans+power window, check if it appears for you in alt tab. As for me it appeared there before as well.

[GHelper.zip](https://github.com/seerge/g-helper/files/11642893/GHelper.zip)

**Comment by seerge** [comment]
Closed due to lack of response from issue started
