### ISSUE TITLE
Fn Lock invert

### ISSUE THREAD

**Issue by moritzbeck01** [seerge/g-helper#509]
**Describe the solution you'd like**
Fn Lock is awesome. Is is possible to invert the function if enabled? So pressing F1 would still mute but pressing Fn+F1 would trigger F1 etc. Otherwise the F keys aren't reachable at all, or am I missing something?

**Describe alternatives you've considered**
- not using the feature
- always toggling in the settings
- carrying an external keyboard with me everywhere

**Additional context**

**Comment by seerge** [comment]
@moritzbeck01 that's not doable on this stage, as this is not a hardware fn+lock (as normal devices have). App just creates hotkeys for each Fx key and run corresponding action manually.

**Comment by moritzbeck01** [comment]
So how was this done before with the shortcut keys? Does the keyboard driver just send the shortcut events?

**Comment by seerge** [comment]
@moritzbeck01 "before" is when fn+fx work? they are processed either by app or by optimization service.

**Comment by moritzbeck01** [comment]
Got it, so the Fn Lock integration is a hard coded mapping of F keys to their corresponding shortcuts and the other way around can't be done because GHelper never receives the Fn+F keys, right?

**Comment by seerge** [comment]
@moritzbeck01 g-helper receives that. But it's a conjunction of how it catches normal F1-F12 hotkeys in a first place, and how it emits other events.

When Fn-Lock is on - if I catch **Fn+F2** and try to send back to windows regular **F2**, windows will ignore it and send it back to the app (as app told windows it wants to capture all **F2** hits).

P.S. Keep in mind, that even if Fn-Lock is "on", combinations like Alt+F4 or so will still work, as app intercepts only solo F-row keys, and not with modifiers.
