### ISSUE TITLE
Unresponsive for extended period after unplugging in Optimized mode

### ISSUE THREAD

**Issue by rustyspatula** [seerge/g-helper#510]
Description:
- G-Helper will become unresponsive when unplugging from power in the "Optimized" GPU mode
- Keyboard shortcuts become unresponsive
- Once the program becomes responsive again all previous keystrokes will be executed all at once (e.g. keyboard and display brightness will suddenly change according to keystrokes)
- G-Helper window will be labeled "not responding" by windows, but it will not crash

_**As of writing this I have discovered the same issue occurs when changing from Standard to Optimized modes. It seems to be an issue with the Optimized mode and may be an NVIDIA issue. I will still leave this here for reference.**_

1. Enable Optimized GPU mode
2. Unplug from AC power
3. G-Helper and all keyboard shortcuts (including brightness/power mode options) will be unresponsive for at least a full minute

Expected behavior:
- In the "Standard" GPU mode the program remains responsive throughout the unplugging process.

App Log:
[log.txt](https://github.com/seerge/g-helper/files/11630817/log.txt)

Desktop:
 - OS: Windows 11
 - 2023 ASUS Zephyrus G14 G402XV (4060)

Software:
- Armoury crate uninstalled
- MyASUS installed
- Debloat.bat has not been executed
- The normal background ASUS processes are running

**Comment by seerge** [comment]
@rustyspatula hello, when you unplug / plug using Optimized mode app will try to disable / enable your dGPU (as this is what this mode is about). Disabling dGPU goes via **asus own** command, that can lock current process doing that. I can't really change that :) 

On 2023 models it seem to take longer time than on 2022 tho. 

1. Make sure that your nvidia optimus setting is actually real "Optimus" (not auto / nvidia only)
2. Try to run app as admin + select kill GPU processes under Extra (it may help driver to release GPU faster)
3. If it still happens - you may just keep GPU mode in Standard, then it will not turn off your GPU automatically until you click Eco

**Comment by rustyspatula** [comment]
I thought it might have something to do with Optimus. That whole thing is always buggy. Thanks for the tips!

**Comment by seerge** [comment]
@rustyspatula ok, good :) Since (on this stage), I can not do anything more. I'm closing this. 

Feel free to create a new issue if you notice something.
