### ISSUE TITLE
PPT Function not Working Correctly.

### ISSUE THREAD

**Issue by XyKER1** [seerge/g-helper#511]
While playing games or doing any other GPU intensive process, the CPU on my TUF F15 2022 locks to 25 W.  In most games, this is enough wattage to run it just fine.  However, in a few, more wattage could be beneficial.  I noticed that every so often, the CPU power draw will go up to 65 W during gaming - almost like the program is testing whether this would help my FPS.  However, as soon as the CPU temperature hits 90 C, the wattage goes back down to 25 W for around the next five minutes before running another test.

To try to stop this, I changed the PPT under the fans + power tab to 45 W, hoping this would prevent the CPU from reaching 90 C while giving me more power to work with.  However, after changing this setting, the issue persists.  The CPU still goes up to 65 W when "testing," and according to HWInfo the power limits are still set at 115 W and 135 W for PL2 and PL1.
So basically I'm saying that the PPT option isn't limiting the CPU to it's correct wattage.  If you know any other fixes to stop the CPU from throttling to 25 W, help with that would also be appreciated, but I'm guessing it's probably part of the BIOS.

1. Go to fans + power tab
2. Set PPT to 45 W
3. Open a CPU intensive game
4. Open MSI Afterburner to monitor CPU power while playing

**Expected behavior**
CPU PPT should limit CPU power to 45 W no matter what.

[log.txt](https://github.com/seerge/g-helper/files/11631140/log.txt)

Video: https://www.youtube.com/watch?v=yZOnFOxK06o

Windows 11 Home
FX507ZM-ES74

**Asus software**
I uninstalled Armoury Crate using the uninstaller from the ASUS support page before opening G-Helper.  MyASUS is installed.
![asus services running](https://github.com/seerge/g-helper/assets/135291286/0aa62172-e1a5-4f69-a914-0299dd305ebd)

**Additional context**
I saw on the ASUS forum that uninstalling Armoury Crate allowed the CPU to run at the Intel spec of 45 W.  However, this didn't work for me.  Even without Armoury Crate or G-Helper installed, the problem persists.  Maybe it has something to do with the "Armoury Crate Key Control" process?

**Comment by XyKER1** [comment]
I have a small update.  I used ThrottleStop to limit the CPU wattage to 45 W, which worked successfully.  However, it turns out that the CPU still goes back to 25 W after a certain amount of time.  This seems to correspond to how much the GPU is drawing.  In one part of the game that was particularly badly optimized (GPU only drawing 40 W out of potential 115 W), the CPU stayed at 45 W for 46 seconds before dropping back down to 25 W.  The highest temperature reached was 80 C, and it didn't throttle down when it hit this.  I'll post again if I can figure out anything else.

**Comment by seerge** [comment]
> I saw on the ASUS forum that uninstalling Armoury Crate allowed the CPU to run at the Intel spec of 45 W. However, this didn't work for me. Even without Armoury Crate or G-Helper installed, the problem persists. Maybe it has something to do with the "Armoury Crate Key Control" process?

@XyKER1 do I understand correctly that same behavior was when you were using AC as well ?

**Comment by XyKER1** [comment]
Yes, the same behavior occurred with AC installed and after uninstalling AC but before opening G-Helper for the first time.

**Comment by seerge** [comment]
@XyKER1 ok, then I have to disappoint you, and looks like it's some issues with bios not being able to maintain limits or so :) Does it stay stable at least if you just use a default mode (i.e. without setting custom fan curve / ppts?)

More than that, I already have added a fix specifically for your model (by request from other user). As bios there was setting 5w CPU limits on it's own, without any reason for that.

https://github.com/seerge/g-helper/blob/ddb591b79abefa407e74cc5e6d6a725f99c65c21/app/Settings.cs#L1147

**Comment by XyKER1** [comment]
Hey there, just wanted to provide an update on this.  I still have some testing (and possible BIOS editing) to do to attempt to resolve the 25 W throttling issue, but I'm not writing to talk about that.  I saw in the changelog for 0.8.0 that you said you added support for power limits for my model.  This would be great as ThrottleStop (which I have been using to change power limits) requires you to restart every time you modify your configuration.  However, with the "apply custom power limit" box checked and the PPT set to 80 W, the CPU still goes up to its default 105 W and thermal throttles quickly.  Opening ThrottleStop after this shows an immediate drop to 80 W, meaning it is possible to throttle my CPU, but G-Helper isn't doing it.  Do you have any idea why G-Helper isn't power limiting my CPU?

**Comment by seerge** [comment]
@XyKER1 not to your model, to FX517 
Check this topic https://github.com/seerge/g-helper/issues/405

**Comment by seerge** [comment]
@XyKER1 You can verify if adjustment made in 0.80 also works for your model by adding ``"manual_mode" : 1`` in ``config.json``. And restarting the app

**Comment by seerge** [comment]
@XyKER1 did you had a chance to test if "manual_mode" setting has effect on you ?

**Comment by XyKER1** [comment]
Sorry, I've been really lazy lately.  I'm going to do it now.

**Comment by seerge** [comment]
@XyKER1 I just double checked, and this "manual' mode setting is applied (on hardware level) only if you have a custom power limits (i.e. apply power limits) checked, otherwise it would use normal turbo mode instead

+ in latest release you can create as many custom profiles as you want (i.e. custom turbo and just default turbo) so it should solve your problem

https://github.com/seerge/g-helper/releases
