### ISSUE TITLE
For 2 in 1, when rotating display to/from tablet mode, magic keys should not be sent

### ISSUE THREAD

**Issue by TheBestPessimist** [seerge/g-helper#512]
When GHelper is on and i rotate my Flow's display to tablet mode or back to laptop mode, the following keys are sent by GHelper, in this order:

```
LWin            down
LControl        down
F24             down
F24             up
LWin            up
LControl        up
```

Is it possible for GHelper to not send those extra keys?

I have implemented a workaround in my scripts which are triggered by this, but it would be nice if GHelper would not do it by default: https://github.com/thebestpessimist/autohotkey-scripts/blob/7ccb1d6eaf0fcab2c3bca3ba1492752ec6c6dfdd/AutoHotkey64.ahk#L86-L87

Keys as detected by Autohotkey, along with an explanation:
![image](https://github.com/seerge/g-helper/assets/4482210/0c4a4c4c-6545-4cbe-8c6a-910671e0fb8d)

**Comment by seerge** [comment]
@TheBestPessimist  When you enter tablet mode g-helper disables touchpad (as by same request her in "issues" by other user) as it was same in AC. I assume you mean this ? Why it shouldn't ?

**Comment by TheBestPessimist** [comment]
Is disabling the touhcpad done with keys <kbd>Ctrl</kbd> + <kbd>Win</kbd> + <kbd>F24</kbd>?

**Comment by TheBestPessimist** [comment]
NVM, answered myself and the answer is "yes". In that case, the ovious choice is to reject my request. 

Thanks for your explanation!

**Comment by seerge** [comment]
I emit a universal command to keyboard that in turn (apparently) does that https://github.com/seerge/g-helper/blob/b97a06eb569a8443f7289d3d1c13a646ca4350f0/app/AsusUSB.cs#L206
