### ISSUE TITLE
Power Profiles Do Not Match. Fan Speeds buggy

### ISSUE THREAD

**Issue by oM0NG0o** [seerge/g-helper#515]
More Power Profiles than Capable of changing.. Ghelper not changing to proper profile. "STRIX"
Click on Turbo then switch's PP to Performance^ Never meshes up properly again.
 ** Factory Profiles No Add On's**
Fan speeds Jump or do not run at all.  Low Approx.> 500 rpm also.

6/2/2023 12:40:13 PM: App launched: ROG Strix G814JZ_G814JZ :0.75.0.0en-US.
6/2/2023 12:40:13 PM: NVIDIA GeForce RTX 4080 Laptop GPU
6/2/2023 12:40:13 PM: AutoSetting for Online
6/2/2023 12:40:13 PM: BatteryLimit = 60 : OK
6/2/2023 12:40:13 PM: BatteryLimit = 60 : OK
6/2/2023 12:40:13 PM: PerformanceMode = 1 : OK
6/2/2023 12:40:13 PM: GET GPU CLOCKS: 0, 0
6/2/2023 12:40:13 PM: FanCPU = 14-21-28-2F-37-3E-45-4A-21-29-31-3C-49-55-60-63 : OK
6/2/2023 12:40:13 PM: FanGPU = 14-23-2B-33-3D-41-47-4E-20-26-31-3C-49-4F-5D-63 : OK
6/2/2023 12:40:13 PM: FanMid = 14-1E-27-2F-37-3F-47-4E-2D-35-3D-42-4D-55-5D-63 : OK
6/2/2023 12:40:13 PM: Eco flag : 0
6/2/2023 12:40:13 PM: Mux flag : 1
6/2/2023 12:40:14 PM: ScreenOverdrive = 1 : OK
6/2/2023 12:40:14 PM: Monitor Power On
6/2/2023 12:40:14 PM: KB Backlight:5D-BA-C5-C4-01
6/2/2023 12:40:14 PM: PowerLimit C0 = 25 : OK
6/2/2023 12:40:14 PM: PowerLimit C2 = 87 : OK
6/2/2023 12:40:22 PM: GET GPU CLOCKS: 0, 0
6/2/2023 12:40:40 PM: PerfMode = 1 : OK
6/2/2023 12:40:40 PM: PowerLimit C0 = 25 : OK
6/2/2023 12:40:40 PM: PowerLimit C2 = 87 : OK
6/2/2023 12:40:41 PM: FanCPU = 14-21-28-2F-37-3E-45-4A-21-29-31-3C-49-55-60-63 : OK
6/2/2023 12:40:41 PM: FanGPU = 14-23-2B-33-3D-41-47-4E-20-26-31-3C-49-4F-5D-63 : OK
6/2/2023 12:40:41 PM: FanMid = 14-1E-27-2F-37-3F-47-4E-2D-35-3D-42-4D-55-5D-63 : OK
6/2/2023 12:43:33 PM: ------------

Windows 11 Pro
ROG Strix G184JZ
All **Asus software** installed doesn't matter disabled or not.

![untitled](https://github.com/seerge/g-helper/assets/132635900/a7d72b06-19eb-4f97-944a-da925eb47735)

**Comment by oM0NG0o** [comment]
Those are Asus install MyAsus/AC power plans, the windows ones do not exist. I just Un-Hid all settings on them for pci/ssd power settings. I can send you the Power.config install file if you want. The 2023 Strix has more Media keys plan settings "windows/silent/performance/turbo/manual" power plans.The windows and silent using same plan just differ in fan speeds.I know the new models are a PITA. LOL just thought you'd like to know.

    On Friday, June 2, 2023 at 02:50:55 PM EDT, Serge ***@***.***> wrote:  
 
 


@oM0NG0o hello. App never changed windows power plans, as it's not needed and in de-facto in windows 11 they are obsolete.

I recommend to set power plan to Balanced, as it's default one and gives all flexibility needed.

If you really want to set power plans - check how to do it here https://github.com/seerge/g-helper#custom-power-plans-with-each-mode

**Comment by seerge** [comment]
@oM0NG0o 

I know that. All models have windows/silent/performance/turbo/manual "plans" in AC. But on "hardware" level (i.e. in bios) Ssus has baked only 3

1. Windows mode is same as Performance (difference in Windows AC sets "balanced" power plan, and for "performance" it set's own proprietary "performance). In G-helper there is no need in "Windows" plan, as Balanced is literally the same thing

2. Manual is same as Turbo (but it allows to set custom fans/PPTs in AC). In G-helper every mode can become "manual" if you apply custom fans+power settings ;)

**Comment by seerge** [comment]
Closing as there is nothing to "fix" here :)
