### ISSUE TITLE
More flexibility for fan speed curve control

### ISSUE THREAD

**Issue by manciuszz** [seerge/g-helper#518]
Right now, I feel like the current fan speed curve controls lack an option to adjust multiple nodes at the same time. For example, I'd like to see an option to raise/lower all nodes at the same time by 200 RPM, let's say, maybe, by holding shift and dragging a node? This would save a lot of time for situations where you reset to defaults and just want a little bit more aggressive fan speeds.

**Comment by seerge** [comment]
@manciuszz honestly it could be a bit difficult to do (as I did current editor by taking windows charts component, and writing a method to drag some dots over it). May I ask why do you edit curves so often ? may be solution for your problem lays somewhere else ? (more profiles ?)

**Comment by manciuszz** [comment]
I usually don't mess with the fan curves that much. I tend to use a bit more aggressive defaults for daily use. However, I started tinkering with very high undervolt (-165mV) @ 4.0GHz recently and experimenting with fan curves (decreasing/increasing them accordingly) and I found myself wanting to adjust every node, every single time, simply because changing one node doesn't really make sense or do anything in this current situation.

**Comment by seerge** [comment]
@manciuszz but won’t 2 separate fan presets save your problem?

**Comment by manciuszz** [comment]
I'm using the [custom power profiles with each mode](https://github.com/seerge/g-helper#custom-power-plans-with-each-mode). Each mode has vastly different results on the device performance. Switching a power plan would result in an instant instability and result in a crash at those undervolt settings. So, I mainly carry out the testing using the 'Turbo' profile and as far as I'm aware, I can only have 1 fan preset for each mode :/

**Comment by seerge** [comment]
@manciuszz what i propose is ability to create more profiles, so you can have 2 turbo’s with different fan curves

**Comment by manciuszz** [comment]
I could make do with that. Having something like low/mid/high presets for turbo would be a nice addition indeed. However, this sounds like actually more work than my original suggestion, which was to simply detect a key modifier such as shift/ctrl and simply drag all nodes up/down based on offset or something. Anyways, I'll take any solution, both sound equally good.

**Comment by seerge** [comment]
@manciuszz then I have misunderstood you probably in a first place, as I imagined ability to select group of points and move only them (but not all)

If you want to move ALL at once - it's doable (with shift modifier)

Check this build : 

[GHelper.zip](https://github.com/seerge/g-helper/files/11643106/GHelper.zip)

**Comment by manciuszz** [comment]
Awesome. This is exactly what I wanted! Works just right too 👍
