### ISSUE TITLE
Trigger Battery Health Charge when booting into Lockscreen

### ISSUE THREAD

**Issue by mirt81** [seerge/g-helper#519]
HiLow Seerge . . . Th@nks !

There is the Issue when Booting ( g513 zen3 / Tuf A15 zen2 / Windows 10/11 ) into Lockscreen the Battery Health Charge wouldnd trigger . . . and the Battery will Charged to 100% .

There is a way from other Battery Health Charge Service with Taskshedule service but thats dont work for GHelper:
( Had also tryed the Taskshedule for "ASUS Optimization Service" but no succes )

Begin the task: On an event
Basic
Log: System
Source: Kernel-Power
Event ID: 105

The Source " https://github.com/lampuiho/TUFA152021BatteryChargeLimiter " maybe its brings a Idea ;)

**Comment by mirt81** [comment]
A Semi Fix should be run https://github.com/lampuiho/TUFA152021BatteryChargeLimiter beside GHelper . . . after Lockin GHelper take the "ATKACPI handle" so set GHelper Charge Limit above the 60% set by "BatteryChargeLimiter" BatteryHealth are possible keeped ? ! .

**Comment by seerge** [comment]
@mirt81 hello.

That app you linked does literally the same thing as g-helper do (also same as myasus do) to set charge limit. Sends payload to Asus ACPI "driver" at address 0x120057 + limit. So it's already there.

Generally speaking, there is no need to "set" this limits all the time, as it's remembered by hardware on low level, and your laptop shouldn't start charging even when it's completely powered off (and obviously no apps are running at all).

But if you really want to - you can try adjust G-Helper's task in windows Task Scheduler to run system startup rather login :)

I'm closing this, as there is nothing to "fix".

**Comment by mirt81** [comment]
Unfortunately GHelper doesn't work if the start is set up for system start. On the one hand, the loading limit is not activated and on the other hand, GHelper is not active in the taskbar after login and runs in the Windows processes in idle mode! ? .

**Comment by seerge** [comment]
@mirt81 if you have asus optimization service running, try to stop and disable it

**Comment by mirt81** [comment]
Have testet with disabled asus optimization service but no change .

Before i Discovered GHelper i used OpenRGB & old Asus Battery Health WinStore App https://apps.microsoft.com/store/detail/asus-battery-health-charging/9NKCLN5X4RR9?hl=en-us&gl=us to have a debloated OS but for this to work had to be asus optimization service to be active else there no RGB Light Control and for the Asus Battery Health WinStore App i had to use the Taskshedule settings from [BatteryChargeLimiter] and manuel trigger a second extra Start even that there would a same behavior as with GHelper ( and i had runing twice the same Process : )
Now with disabled asus optimization service i have enterly no non functinal Bloated System task running .

Extra [BatteryChargeLimiter] task does not disturb ( Strangely, there is no [BatteryChargeLimiter] entry in the task manager )

GHelper can Handle booth Task and make much more possible what missed with not Installed Bloated and Buggie Hacky Cracky ArmouryCrate on g513qy & ( fa506iv i have yet not full tested )

Awesome to have with GHelper one Program & Process that handle what is to handle ! 

Th@nks !
+
