### ISSUE TITLE
[Feature request] Another box displaying the current ppt and saving the ppt limits for each performance mode

### ISSUE THREAD

**Issue by ONIMUSHA117** [seerge/g-helper#52]
Hi,
I am currently happy with the program. However, when I unplug the power or change the performance mode, my power limit changes as well. I know this is normal, but I think there are some nice features to add:

- Ability to view the current limit: Have another box showing the current limit power above the control for limit power.
- Ability to remember manual limit for each performance mode: So each mode would have the choice to overdrive the default modes with power limits and fan control. Also, the settings are saved to each mode, then whenever the users change the mode, the power limit and fan curve will change in according to the manual.
- Power drain after setting Battery Charge Limit: Currently, after you set the current charge limit, if the current battery level is higher than the charge limit, it will bypass the limit and keep charging. Could there be a tweak like what MyAsus does that have the battery charge stop at the current level if the battery level is higher than the limit?

Thank you so much for creating this program. It's way better than what I have with Armoury Crate with no bloatware. Hope these give you some ideas as well.

**Comment by seerge** [comment]
Hi

1. There is no (known to me), way to "read" default PPT for pre-built modes. Asus doesn't even report what kind of mode (!) is set currently, also for armory / linux implementations / etc. So app just sets mode (and then remembers it in settings). I know only G14 2022 "default" PPTs from experimental measurements, but for G15 or older G14 they are different (cause hardware is different)

2. Remembering (and auto applying) PPTs is something that I wanted to add a bit later, IF with a help of community I will find a way to set them for older models. As CPU PPT seem to work only on 2022 for example.

3. You sure about charge limit ? For me even if battery is already overcharged, it stops charging if limit is lower than that. Technically, there is no ON/OFF toggle for charing. There is only 1 endpoint (that you can't read as well), but just "set" a number in % which will tell BIOS to charge no higher than that %. And that endpoint is being set every time you change limit AND every time laptop is connected/disconnected/wakes up (while GHelper is running). There is not much more you can do here :)

**Comment by ONIMUSHA117** [comment]
Hi @seerge ,

Thank you for a cool update. I can see the Profile power limit saving features and auto apply working. Also my battery power charging limit works as intended, don't know why it did not work before through. 

As for the (1), I am thinking about a mini benchmark when the app first start, but that's just over complicated the process. Furthermore, I have my own preset of power limit for each profile with Auto Apply now, don't think I would ever need that again. However, a mini benchmark could be an idea for other unknown model. You can think about that.

Thank you and All the best
