### ISSUE TITLE
When Using "Nvidia GPU Only" in Advanced Optimus, Some Features Become Unavailable

### ISSUE THREAD

**Issue by ModrnJosh** [seerge/g-helper#521]
On the 2023 Asus Zephyrus G14 (7940HS / RTX 4090 / mini-LED), and when in Advanced Optimus mode, ONLY when "Nvidia GPU Only" is selected (so dGPU mode), G-Helper claims that the laptop screen is turned off and won't allow me to switch refresh rates or multi-zone toggle. When I'm in regular Optimus/Hybrid using Advanced Optimus then this functionality is fine and works great. I've attached a screenshot to better visualize the issue. Let me know if you need any more info, thanks!

<img width="310" alt="g-helper with dGPU mode" src="https://github.com/seerge/g-helper/assets/135409589/d5dba5ce-91dd-48a2-97de-190ce83bda90">

**Comment by seerge** [comment]
@ModrnJosh hello :)

Currently app looks for a display marked as "internal", and if it's not there assumes that it's off. I suspect that with Optimus it can create virtual displays, that identify themselves somehow different.

Can you try this build with verbose logging, and then upload log.txt from ``%AppData%\GHelper`` folder here ?

[GHelper.zip](https://github.com/seerge/g-helper/files/11642209/GHelper.zip)

Thanks.

**Comment by ModrnJosh** [comment]
Here you go! All I did was move the battery slider in between enabling optimus/dGPU mode: 
[log.txt](https://github.com/seerge/g-helper/files/11644263/log.txt)

**Comment by seerge** [comment]
@ModrnJosh thanks.

I see a bunch of lines mentioning external display, do you have external display connected ?

```
6/3/2023 5:08:40 PM: B140QAN06.S :DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL
6/3/2023 5:08:40 PM: \\.\DISPLAY5
```

Otherwise - looks like it's optimus identifying itself like that

**Comment by seerge** [comment]
@ModrnJosh 

Can you try this build ? What it will do, as soon as it will spot "internal" display, it will remember it's name in config. And next time, even when Optimus is set to Nvidia GPU, and real display doesn't identify itself as internal - it will spot it by name instead.

So to test :
1. You need to set optimus to actual "optimus" and let app remember it (as soon as display section will become active - it's all good)
2. Set optimus to Nvidia Only / etc and open app window again, display section should be still available

[GHelper.zip](https://github.com/seerge/g-helper/files/11644281/GHelper.zip)

Hope it helps

**Comment by ModrnJosh** [comment]
I'm happy to report that the changes you made worked!!! I am now able to use those functions without any issues no matter which mode I'm in with Advanced Optimus. Thanks!

And yes, that is correct, I did not have an external display connected at the time. Advanced Optimus works by creating I guess a "fake" external display (which is Display 1 in the screenshot below). It cannot become your main display and is only there to act as a mux switch without having to restart.
<img width="740" alt="adv optimus" src="https://github.com/seerge/g-helper/assets/135409589/a5daf590-8145-41c9-b56a-c2bf48dc897c">

**Comment by seerge** [comment]
@ModrnJosh ok, great, thanks. It's live under https://github.com/seerge/g-helper/releases/tag/v0.77

**Comment by AudreyAP** [comment]
@ModrnJosh When on nvidia only, does the windows 11 brightness bar go grey for you? I'm able to use hotkeys but the brightness slider in the control panel thing is greyed out.

**Comment by seerge** [comment]
@AudreyAP is it after you enabled GPU (i.e. left eco mode) or always ?

**Comment by AudreyAP** [comment]
@seerge I get that behavior on bone-stock Asus windows with everything running. It seems to be a common issue with a bunch of laptops including Alienware. I'll try another stock Asus revert and see if it's there still...
