### ISSUE TITLE
Optional updates check

### ISSUE THREAD

**Issue by toomuchsalt** [seerge/g-helper#522]
While update check is a nice feature, it may be useful to have the ability to turn it off

**Comment by seerge** [comment]
@toomuchsalt can you explain a realistic scenario where it will be needed?

**Comment by bankjaneo** [comment]
I can think of one. It maybe useful when the new stable version has a problem with the some laptop model. So the user can choose to stick to the old version until problem solved in future release.

**Comment by seerge** [comment]
@bankjaneo hello, you can always just click NO in popup offering update, and it will remember that and don’t open again.

**Comment by toomuchsalt** [comment]
> @toomuchsalt can you explain a realistic scenario where it will be needed?

It might just be me, but I find auto-update suggestions distracting and prefer to do the updates myself when I actually have the time to do so. Sure, I can just block ghelper in the firewall, but that would break the new version notification as well( the line at the bottom of app window ).

**Comment by seerge** [comment]
@toomuchsalt well, you can just click NO to offer, and it won't pop up again
