### ISSUE TITLE
New translation for Turkish

### ISSUE THREAD

**Issue by yesnt10** [seerge/g-helper#526]
Process Fn+F hotkeys without FN: Fn+F kısayol tuşlarını FN tuşuna basmadan çalıştır
Stop all app using dGPU on when switching to Eco: Eco'ya geçerken dGPU kullanan tüm uygulamaları durdur
Keep GPU disabled on USB-c charger in Optimized mode: Optimize edilmiş modda USB-c şarj cihazında GPU'yu devre dışı bırak
Backlight timeout battery: Pilde çalışırken ekran klavyesi ışığının kapanma süresi
Backlight timeout when plugged(0 - always on): Şarjda çalışırken ekran klavyesi ışığının kapanma süresi (0 - her zaman açık)
Auto djust Windows Power Mode: Windows Güç Modunu otomatik ayarla

**Comment by seerge** [comment]
@yesnt10 
Şarjda çalışırken ekran klavyesi ışığının kapanma süresi (0 - her zaman açık) 
this one is super long and doesn't fit, I need shorter version for it (and probably for "Pilde çalışırken ekran klavyesi ışığının kapanma süresi" to mirror it)

**Comment by yesnt10** [comment]
Backlight timeout battery: Pildeyken klavye ışığının kapanma süresi
Backlight timeout when plugged(0 - always on): Şarjdayken klavyes ışığının kapanma süresi (0 - her zaman açık)

is ok?

**Comment by yesnt10** [comment]
if not i will try to shorten it

**Comment by seerge** [comment]
@yesnt10 it's good now, thanks
[GHelper.zip](https://github.com/seerge/g-helper/files/11643147/GHelper.zip)
