### ISSUE TITLE
Text over lap the box boundary 

### ISSUE THREAD

**Issue by Inaiso** [seerge/g-helper#528]
The bottom texts in the "Extra" windows settings of "Backlight" and "Other"  are overlapping the bottom boundary of the box window.  Perhaps the box needs to be extended vertically to fit the text. 

![1](https://github.com/seerge/g-helper/assets/132625303/ba52b7e9-a5a1-4da1-bb5f-2f7aed28a549)

![2](https://github.com/seerge/g-helper/assets/132625303/49c349b7-bfa2-480b-a902-a4d6c756afa4)

![3](https://github.com/seerge/g-helper/assets/132625303/ae75ed78-4302-48e7-8bc0-4b47757ab7e0)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11643184/GHelper.zip)
Should be better here

**Comment by seerge** [comment]
@Inaiso

**Comment by Inaiso** [comment]
Thanks for the quick reply!

I tried the new version, and the overlapp of the "Other" box is fixed, but the "Backlight" overlapp still remains. 

![1](https://github.com/seerge/g-helper/assets/132625303/cf305cf6-27d4-4a8b-a3c7-9c75b4895a3b)

![2](https://github.com/seerge/g-helper/assets/132625303/cfda1689-4941-4630-be74-d7689b22012b)

**Comment by seerge** [comment]
@Inaiso ops, sorry. This one should be fine
[GHelper.zip](https://github.com/seerge/g-helper/files/11643594/GHelper.zip)

**Comment by Inaiso** [comment]
Thanks for all your work, the new version fixed the problem.
