### ISSUE TITLE
Blackout problem when changing screen Hz

### ISSUE THREAD

**Issue by yesnt10** [seerge/g-helper#529]
Hello. I use the display Hz auto when charging and on battery. But it goes black for a few seconds on screen changes. 

I install refresh rate services driver but still same. And It doesn't even remember when I select 144 while on battery. When I unplug it it still goes back to 60hz. 

[log.txt](https://github.com/seerge/g-helper/files/11643361/log.txt)

**Comment by seerge** [comment]
Uninstall asus smart display controller, it interferes and tries to do same as g-helper

**Comment by yesnt10** [comment]
Thank you so much! You are life saver!

**Comment by yesnt10** [comment]
I had to format because of the fan speed. I formatted and then uninstall asus smart display controller but still exist. Whats wrong?
[log.txt](https://github.com/seerge/g-helper/files/11646425/log.txt)

**Comment by seerge** [comment]
@yesnt10 what exists? smart display controller ?

**Comment by yesnt10** [comment]
When I take it off the charger, the screen goes black for a few seconds.

**Comment by seerge** [comment]
@yesnt10 try to "uncheck" stop GPU apps checkbox under extra

**Comment by yesnt10** [comment]
i did. but same

**Comment by seerge** [comment]
@yesnt10 then check if asus smart display running in task manager, if so - kill it :)

**Comment by yesnt10** [comment]
its not working :/

![image](https://github.com/seerge/g-helper/assets/114935167/6af8a618-4801-4103-8238-b8d3194d6726)
![image](https://github.com/seerge/g-helper/assets/114935167/c09f8bc6-4a4a-4e2e-95f1-b604be07f709)

**Comment by seerge** [comment]
@yesnt10 does screen "go black" if g-helper is not running at all?

**Comment by seerge** [comment]
@yesnt10 and btw, i noticed that you have GPU in "optimized" mode, so g-helper (obviously) turns your GPU off when you unplug. May be your screen goes black cause of that? Then try to keep GPU in standard mode :) so it's always on.

**Comment by yesnt10** [comment]
no it doesnt go black when im out g-helper

**Comment by yesnt10** [comment]
I don't need to unplug it. When it's charging, when I switch it to 60hz mode, it goes dark again anyway. I think it has something to do with the smart display lol

**Comment by seerge** [comment]
@yesnt10 as i mentioned above - if your gpu is in Optimized and you unplug - g-helper (by design) turns it off. If that's a reason for screen going black set gpu to Standard and it won't go off :)

Also check your optimus settings as i mentioned above.

**Comment by yesnt10** [comment]
I've been using these settings before and there was no problem. (just uninstalled asus smart display controller and it was ok) besides these, I did what you said, but it still continues. I will try to reinstall and uninstall Smart Display. I write results

**Comment by seerge** [comment]
@yesnt10 if so - then also run debloat.bat / uninstall other asus stuff from yours screenshot :) (you can always run bloat.bat to start it again just in case)

**Comment by yesnt10** [comment]
I did a clean install again. I ran g-helper after installing all drivers. and there seems to be no problem now.(:

**Comment by seerge** [comment]
@yesnt10 oke, great to hear :)
