### ISSUE TITLE
Keyboard lighting doesn't work properly 

### ISSUE THREAD

**Issue by Bogit11** [seerge/g-helper#530]
After loging into Windows keybord lighting turns on even if it was set to off before. To turn it off, fn+F2 is not working (turning the brightness down), but need to press fn+F3 first then fn+F2 (so turn the brightness up once and then down and it turns off).

Probably an easy fix, it was working fine before the lates update 0.76

Thank you for the application! Awesome job!

**Comment by seerge** [comment]
@Bogit11 if you have Asus Optimization service working, please stop / disable it from windows "Services" app

**Comment by C485** [comment]
Hello, 

Actually last update broke it, i've GA401II and this is what is happening with latest version:
1. Brightness down keyboard button doesn't change brightness level till brightness up button is pressed, then both work.
2. After some time keyboard lights up to level 2 of 3 brightness levels that are available.

And yes, i've only Asus Optimization service working, i've done few restarts of my laptop (deep restart as well), and it still happens.
It's not a big issue for me but yes, it's annoying :D

BTW. This should be a separate issue but i'm lazy today :D Sometimes (i've no idea how to call it, a rog zephyrus button?) that should open g-helper simply is not registered, app sits in tray and no window is opened, only restart of the app works.

**Comment by seerge** [comment]
@C485 hello, same question to you . Can you please stop optimization service, as it interfere. Then it should work ok.

**Comment by C485** [comment]
> @C485 hello, same question to you . Can you please stop optimization service, as it interfere. Then it should work ok.

Yes, super, i'll stop and will see, it takes some time and i'm not sure when it happens. My bet is when laptop goes to sleep and when it weak, maybe, there is so hook or something that is removed by windows/service.

**Comment by C485** [comment]
Ok it happened almost right away :D  
1. g-helper and Asus Optimization service were running, i disabled Asus Optimization service and keyboard "rog button" and brightness level button stopped working(lack of service health detection?). I've restarted g-helper and brightness level of keyboard went from 0 to 2 of 3 available. It was set to 0 before. Now both "rog button" and brightness works, restarting g-helper does nothing now (brightness is kept at chosen level).

For me it looks like g-helper cannot sometimes read current level of keyboard brightness or state of  Asus Optimization service, i haven't looked at sourcecode but it looks like it may be it.
In my opinion i'll go with disabling all services if everything works with g-helper - just add check in g-helper and show warning.

**Comment by seerge** [comment]
@C485 it's not possible to "read" brightness. It's possible to write it. Therefore (as i mentioned above) asus optimization service intercepts keys and adjusts brightness on it's own, w/o letting app know about that.

You say that when you run g-helper w/o optimization hotkeys don't work ? If so - can you post a log here ? as I have lost my telepathic skills.

Thanks.

**Comment by seerge** [comment]
@C485 and you can check this build, it will NOT set automatic brightness on startup if Optimization service is running (leaving all brightness controls to that).

[GHelper.zip](https://github.com/seerge/g-helper/files/11645363/GHelper.zip)

**Comment by C485** [comment]
> @C485 it's not possible to "read" brightness. It's possible to write it. Therefore (as i mentioned above) asus optimization service intercepts keys and adjusts brightness on it's own, w/o letting app know about that.
> 
> You say that when you run g-helper w/o optimization hotkeys don't work ? If so - can you post a log here ? as I have lost my telepathic skills.
> 
> Thanks.

They work but you need to restart g-helper after disabling "Asus Optimization service".
I guess, like you said, problem is with running both, g-helper and asus services at the same time.
Now everything seems to be working, i'll come back if i'll find something.
Like i said, it would be great to add warning to g-helper with detection of asus services and their state "e.g. startup type", so users wont  be confused.

**Comment by seerge** [comment]
@C485 yes, you need to restart it, as it checks if it should run hotkey listener at all on startup based on optimization service running.

**Comment by seerge** [comment]
It's live under https://github.com/seerge/g-helper/releases/tag/v0.77

**Comment by Bogit11** [comment]
> @Bogit11 if you have Asus Optimization service working, please stop / disable it from windows "Services" app . And restart g-helper after :)

Works perfectly fine now, thank you !
