### ISSUE TITLE
Ability to turn on GPU Fan Even in Eco Mode

### ISSUE THREAD

**Issue by XyKER1** [seerge/g-helper#531]
In my laptop, the heat pipes for the CPU and GPU are connected.  I regularly run CPU heavy tasks like HandBrake encodes, and I've found using Eco mode (discrete GPU disabled) allows me to get the most wattage out of the CPU.  However, in this mode, the GPU doesn't report a temperature, so the GPU fan will stay off no matter what.  Since the CPU and GPU are connected with heat pipes, turning the GPU fan on would also help cool the CPU even more, which is what Armoury Crate would do in Turbo mode even with the GPU disabled.

It would be great if there was a button to set the GPU fan to a certain speed indefinitely regardless of reported temperatures.

The only alternative I could think of would be switching back to ultimate or standard mode, which would decrease the wattage available to the CPU (since the discrete GPU consumes way more than the iGPU even when idle).

For additional context, my laptop can sustain about 60 W of CPU power without throttling with only the CPU fan on, while it could easily do 80 W with both turned on.

**Comment by seerge** [comment]
@XyKER1 There is no way to run fan on "demand". It's only possible to set a fan curve / or use default one. The rest of behavior is hardcoded in bios unfortunately. So it's not possible

Generally speaking - it's strange, cause on G14 (and i assume majority of other models) GPU fan works even when GPU is off, as they are indeed connected with vapor chamber .

**Comment by XyKER1** [comment]
Ah OK, well in that case I have another request.  Could you add the ability to have more than three custom fan curves (like Armoury Crate does)?  I used about 5 different ones before, but we can only set up to three in G-Helper (one for each of the default modes).

**Comment by seerge** [comment]
@XyKER1 yes, it's somewhere in the plans https://github.com/seerge/g-helper/discussions/525 

I'm closing this issue, as original request is not doable.

**Comment by XyKER1** [comment]
Alright, thanks! :)
