### ISSUE TITLE
ISSUE: Extras panel is getting a tad too large at certain Windows DPI scales

### ISSUE THREAD

**Issue by schm1dtxbox** [seerge/g-helper#533]
Bug: Seems like the extras panel is getting a bit too feature-packed now for users running with an effective 720p viewport on Windows 11 (e.g. 1080p with 150% Windows scaling, 1440p with 200% scaling, etc), as on my system it's managing to cover most of the height of my screen, with the title-bar getting cut off by the top of my screen. If more features/options were to get added in a vertical fashion I fear critical UI elements could get cut off for users with a similar display configuration to mine in future.

Solution: The best solution I can come up with would probably be to expand the panel horizontally somewhat, as there is a good amount of horizontal real-estate G-Helper's extras panel could use still, and rearrange the layout of some items to reduce the vertical space used by the UI. (Adding more sub-menus/splitting things up could also work but IMO could end up making things more cluttered as well, so not sure if that's a better alternative.

1. Ensure Windows is running with an 'effective 720p' screen configuration (e.g. by running at 1080p with 150% DPI scaling, 1440p with 200% scaling, etc, ideally at 16:9 aspect ratios as well). Windows 11 may be needed to reproduce this behaviour due to its larger taskbar size versus 10.
2. Load up G-Helper
3. Open the Extras screen
4. The Extras window will end up spanning most of the screen's vertical height, and have the title cut off by the screen's top edge.

Screenshot of the issue: 
![image](https://github.com/seerge/g-helper/assets/36817325/bd6e28f2-f37c-4242-a04c-9fa3945558de)

OS used: Windows 11 (may matter due to the larger taskbar size it has versus 10).
Laptop: ROG Strix G513QE with a 1080p panel, running with 150% Windows DPI scaling.

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11646067/GHelper.zip)
This build should be a bit more compact, but in general I was planning to redesign Extra page fundamentally

**Comment by seerge** [comment]
Yeah, I guess it can even survive one or two more "add some strange feature checkbox no one else would use" from users ... :)

**Comment by seerge** [comment]
@schm1dtxbox which literally happened - i have added a varibright control checkbox there :)

**Comment by seerge** [comment]
@schm1dtxbox what do you propose? adding vertical scrolling ?

**Comment by seerge** [comment]
@schm1dtxbox making wider won't help as in some languages explanation of options are very long, so they literally need a full line :) + it is very possible that screen will get more checkboxes in future :(

**Comment by schm1dtxbox** [comment]
Damn, I guess that would leave the only real choices as either splitting up the menu, or using a scroll-bar as a quick fix.

**Comment by seerge** [comment]
@schm1dtxbox I have managed to win some space by merging backlight timeouts into 1 line, but now it will cause me lots of troubles translating new label into all languages :| 
[GHelper.zip](https://github.com/seerge/g-helper/files/12016580/GHelper.zip)

**Comment by schm1dtxbox** [comment]
That did the trick it seems, the window fits completely on-screen for me now which is great!

**Comment by schm1dtxbox** [comment]
![image](https://github.com/seerge/g-helper/assets/36817325/d673379b-fbef-425a-b739-c0c966959183)
@seerge Issue is back once again after more stuff got added to the Extras panel, looks like the current setup is rather unsustainable as it is, and I assume inevitably content may start to get cut-off at this scaling level (right now the titlebar is completely invisible for me, so I can't even move the window at all). 
Best bet does seem to be to just split up this menu entirely, as about a third of it isn't tied to the keyboard/backlight, so those options should just go into a separate Settings menu (which could have a button to the left of the Updates button, as the version number could just be moved upwards, and Run on Startup be moved into the Settings menu itself).

**Comment by seerge** [comment]
@schm1dtxbox I was doing some adjustments, and moved FN-Lock indicator / toggle to the main screen (as i wanted to do that anyway)

How does extra look for you now ?

[GHelper.zip](https://github.com/seerge/g-helper/files/12321421/GHelper.zip)

**Comment by schm1dtxbox** [comment]
It's an improvement, enough space was won back that I can grip the titlebar now and move the window around, but most of the title-bar does still get obscured.

**Comment by schm1dtxbox** [comment]
Some extra space got won back thanks to your adjustments to the Windows power mode option @seerge, now the title-bar is mostly visible again, including the close button, so nice work there.

**Comment by schm1dtxbox** [comment]
@seerge Issue has returned again after the addition of the new Boot Sound toggle in Extras, btw. Ideas for solving it IMO are the same as before (split up extras as a lot of stuff isn't really keyboard-relevant anymore, and should be in a distinct/general Settings menu instead)

**Comment by schm1dtxbox** [comment]
@seerge Issue has gotten worse as of v0.144 due to another toggle being added since my last comment (that being the Enable GPU on shutdown toggle), now I can't even drag the Extras window around anymore as the title-bar is completely obscured, as can be seen here: 
![image](https://github.com/seerge/g-helper/assets/36817325/730fc795-dec9-448f-b8a9-46eee287b1ef)
Probably worth opening a new issue tbf or reopening this one, given the current state of things.

**Comment by seerge** [comment]
@schm1dtxbox well, i can add vertical scroll to that window, would that be a solution for you ?

**Comment by schm1dtxbox** [comment]
That would be the best solution I'd say, besides splitting the menu up entirely.

**Comment by seerge** [comment]
@schm1dtxbox try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/13850850/GHelper.zip)

**Comment by schm1dtxbox** [comment]
Works perfectly, like the added touch of it matching the main G-Helper window's height too!
