### ISSUE TITLE
FN-lock doesn't affect Fn hotkeys on arrow keys for PageUp, PageDown, Home and End.

### ISSUE THREAD

**Issue by Smokyyy** [seerge/g-helper#534]
## NOTE

**Describe the bug**
FN-lock doesn't affect Fn hotkeys on arrow keys for PageUp, PageDown, Home and End. 

**Clear scenario to Reproduce**
1. Open 'G-Helper'
2. Click on 'Extra' button
3. Enable 'Fn-lock' on any hotkey availabe, for example 'Fn+C'
4. Toggle 'Fn-lock' via the hotkey
5. Press on arrow keys for (PgUp, PgDn, Home, End) hotkeys or right CTRL for (right click) hotkey.

**Expected behavior**
Fn-lock should work on previously mentoned arrow keys and right CTRL on Rog Flow X16 2023 model to use the Fn functions without having to hold Fn key.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11645891/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: Rog Flow X16 2023 with RTX 4060 (GV601VV).

**Asus software**
- None

**Comment by seerge** [comment]
@Smokyyy  Hello, your FN+up/down/left/right keys are handled purely by hardware, app doesn't intercept and control them.

**Comment by seerge** [comment]
@Smokyyy + I digested it, I don't think this is a behavior majority would expect from arrow keys even with fn-lock ON (good example is how Mac OS behaves).

If you really want to achieve that - I would suggest Sharpkeys app, and manually binding arrow keys to (PgUp, PgDn, Home, End) or using Autohotkey

**Comment by FlyingFaller** [comment]
I know this is closed. Commenting to let you know this is a feature I would actually like for the M16. Will use PowerToys to recreate the behavior for now : )
