### ISSUE TITLE
fan speed stuck at %81

### ISSUE THREAD

**Issue by yesnt10** [seerge/g-helper#535]
Hello, the fans are running very loud even though I am not doing anything. When I checked the fans are running 81%. It doesn't change even when I put it in silent mode.
![image](https://github.com/seerge/g-helper/assets/114935167/7a602b47-e646-4c84-98ba-a90b79d939b5)

[log.txt](https://github.com/seerge/g-helper/files/11645902/log.txt)

**Comment by seerge** [comment]
@yesnt10 your fans are controlled by bios, not by app. Try to set different performance mode, if it doesn't help - just reboot. As it's probably bios hiccup.

**Comment by yesnt10** [comment]
i restart it works fine for a while but it gets fixed at 81% again :/ My bios settings are default...

**Comment by seerge** [comment]
@yesnt10 well, i don't know what's causing that :) try not to run g-helper on start (even tho from log i see that you have default profile and g-helper literally does nothing, besides your hotkeys).
