### ISSUE TITLE
Regression: GPU mode section shows up on v0.77 on models without dGPU

### ISSUE THREAD

**Issue by krystean** [seerge/g-helper#536]
The `GPU Mode` section that was previously hidden if a model does not have a dGPU shows up again on `v0.77`.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11646369/log.txt)

**Screenshots or screencasts**
<img width="311" alt="image" src="https://github.com/seerge/g-helper/assets/66447871/b7150e5e-9020-4aef-a23d-87e8696acc44">

**Desktop**
 - Windows 11
 - VivoBook_ASUSLaptop X515UA_M515UA

**Asus software**
None

**Other**
`GPU Mode` also appears when right-clicking the GHelper icon:
<img width="124" alt="image" src="https://github.com/seerge/g-helper/assets/66447871/c9fb4b2d-4b3a-486f-9202-9ddc8f79991c">

PS
I'm using VSCode and I tried building the app using `dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true` but I ended up with a big exe file (140MB+) while yours is only 4MB. I tried adding `/p:PublishTrimmed=true` but it says it's not supported or recommended for Windows Forms. The only change I made was on `global.json` sdk.version. I only know Python and you've inspired me to also learn C# and .NET :D

Thanks!

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11646687/GHelper.zip)
This build should fix it

**Comment by krystean** [comment]
Thanks!
