### ISSUE TITLE
Unable to set fan speed to OFF

### ISSUE THREAD

**Issue by Jakanis** [seerge/g-helper#538]
**Describe the bug**
On fan speed curves, the graph is cut from the bottom, so I can't set value for speed lower than 1800 RPM once it changed from original 'OFF'. 

**Clear scenario to Reproduce**
1. Go to 'Fans + Power'
2. Try to change the lowest fan curve, which is usually OFF by default.
3. Now try to set it to OFF.

**Expected behavior**
Should be able to set the leftmost fan curve value to OFF.

**Screenshots or screencasts**
Here I'm trying to drag value lower, but can only set it to 1800 RPM:
https://github.com/seerge/g-helper/assets/22942162/eda3936d-5174-4cce-b6a9-84225b8e565b

**System:**
 - OS: Windows 11
 - Zephyrus G15 GA503RW

**Asus software**
- Armoury crate and MyASUS uninstalled

**Additional context**
External screen is connected with 100% scaling on it and 150% scaling on internal. But I've tried with internal screen only and with different scaling.

**Comment by Jakanis** [comment]
Also, small feature request – mb it also would be convenient to be able to change RPM values with mouse scroll.

**Comment by seerge** [comment]
@Jakanis good eye, this build should fix it. Editing RPM with mouse wheel is a bit complicated, so I will leave it as is for now )

[GHelper.zip](https://github.com/seerge/g-helper/files/11646668/GHelper.zip)
