### ISSUE TITLE
Use `&`

### ISSUE THREAD

**Issue by flukejones** [seerge/g-helper#539]
https://github.com/seerge/g-helper/blob/e9060ad8c058c930db549687242d5304025527ca/app/AsusACPI.cs#L287

Re: line ref, this should be `return BitConverter.ToInt32(status, 0) & 0xf;` which will give you the first byte of the output. What you have currently may cause issues? Not sure.

**Comment by seerge** [comment]
@flukejones that's a good point. Some values here contain data in a 3rd byte. For example when I check PPT endpoint existence, I would get a payload of 00-00-01-00
