### ISSUE TITLE
After sleep on AC and wake on DC = no refresh rate change

### ISSUE THREAD

**Issue by lucidnx** [seerge/g-helper#54]
Hello! If you put your laptop to sleep on AC and wake on DC, refresh rate is not changed to 60Hz. Can you add  refresh rate check after wake up? I am using S3 sleep on my GA402RK in case it matters.

**Comment by seerge** [comment]
Power change detection is there from the beginning. I'm not able to reproduce it in latest built at all https://github.com/seerge/g-helper/releases/tag/v0.17

**Comment by lucidnx** [comment]
It happens to me when I have laptop docked, unplug USB dock (laptop immedialy go to sleep when it's closed) and then wake up without DC.

**Comment by lucidnx** [comment]
hmm I mean, maybe you can add simple check on wake-up to detect power state and re-apply settings?

**Comment by seerge** [comment]
The check is there. It means app was not informed about wake up at all by windows in this specific case.
