### ISSUE TITLE
There is a third value

### ISSUE THREAD

**Issue by flukejones** [seerge/g-helper#540]
https://github.com/seerge/g-helper/blob/e9060ad8c058c930db549687242d5304025527ca/app/AsusACPI.cs#L44

Re: ref line, for the charge mode there is another value `3`, which occurs when both the barrel and usb-c are plugged in. I think the preferred charger is then barrel, but I'll check this out a bit further in Linux.

**Comment by seerge** [comment]
@flukejones I know, but actually i have encountered one device that was reporting something like 40 on that endpoint (for USB-charger). So in the only spot where I use that I just check if it's less than 2 (for now)

https://github.com/seerge/g-helper/blob/e9060ad8c058c930db549687242d5304025527ca/app/Settings.cs#L1349

**Comment by flukejones** [comment]
Do you think that could be related to https://github.com/seerge/g-helper/issues/539 ?

Asus isn't the most reliable when it comes to acpi. In either case if you use bit-ops you can get around this easily.

**Comment by seerge** [comment]
@flukejones no, response value was within single byte range. Using bit-ops would give same result. It was just outputting something weird.
