### ISSUE TITLE
GPU Mode section is not showing on S15 2019 GX502GW

### ISSUE THREAD

**Issue by bankjaneo** [seerge/g-helper#541]
**Clear scenario to Reproduce**
1. GX502GW has MUX switch so GPU Ultimate Mode is supported but not Eco Mode. (https://rog.asus.com/my/laptops/rog-zephyrus/rog-zephyrus-s15-series/spec/)
2. From G-Helper 0.69 onward with the feature that hide GPU Mode for unsupported model also hide Ultimate Mode from this model too.
3. To enable Ultimate Mode, I need to use version 0.68 instead.

**Expected behavior**
Option to show only Standard and Ultimate. Eco and Optimized not needed since it's not support.

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/11648365/log.txt)

**Screenshots or screencasts**
0.68
![0.68](https://github.com/seerge/g-helper/assets/14077691/2a04c71d-382b-49db-9756-f674792e8289)

0.78
![0.78](https://github.com/seerge/g-helper/assets/14077691/bc1bd18b-764c-4ca8-8244-bad482651cd0)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Asus Zephyrus S15 GX502GW

**Asus software**
- Armoury crate uninstalled
- MyASUS installed
- Already run debloat.bat

Thank you so much.

**Comment by seerge** [comment]
@bankjaneo hello. Interesting, you have quite unique case. As in your log your bios reports Eco mode as absent 

```
05/06/2023 10:54:05: Eco flag : -65536
05/06/2023 10:54:05: Mux flag : 1
```

But MUX (Ultimate mode) present :)

So app has acted, as it was supposed to. I have added a fix that will hide GPU section only if both eco / mux are absent : 

[GHelper.zip](https://github.com/seerge/g-helper/files/11651048/GHelper.zip)

**Comment by JuniorWhett** [comment]
Hello i'm I have the same issue but on my ROG Strix G513QY; GPU mode section is not showing up from 0.70 onwards it's not supported right? But it shows the options when i right click on the G-Helper Logo, theres something i could do?

G-Helper 0.70
![gpu modes1](https://github.com/seerge/g-helper/assets/136101576/6c5b65d0-39b2-4bab-9414-241dcf1904d1)

![gpu modes](https://github.com/seerge/g-helper/assets/136101576/a6a1e6c8-88f3-482b-8edf-0c3dc83488c7)

**Comment by seerge** [comment]
@JuniorWhett most probably it's not supported, "options" in context menu should be gone if you would update to the latest version as it asks you to :)

**Comment by JuniorWhett** [comment]
Yeah you're right, it's not supported at all as it just disappear when i update it to the latest version :(

**Comment by looy17** [comment]
> Yeah you're right, it's not supported at all as it just disappear when i update it to the latest version :(

did your g513QY ever support the gpu mode? as mine isnt showing so im assuming its not supported
