### ISSUE TITLE
Disable Backlight Slider

### ISSUE THREAD

**Issue by IlNEOlI** [seerge/g-helper#542]
I want to be able to leave the keyboard backlight level as it is. Before the backlight slider update, when I left my backlight off and lock my laptop or shut it down, it was still turned off when I unlock it or power it on back again. Now it just adjusts itself to the level in the backlight slider in the G-Helper. The problem is, I don't use the slider in daily-driving. I just use the shortcuts on the keyboard. So when I change my keyboard backlight using shortcuts and lock my computer (I have to  do it a lot because of my job), it adjusts the keyboard backlight to the level that I've determined in the G-Helper again. It happens when I power it off and on again as well.

I just wanna be able to disable that keyboard backlight slider and be able to use my shortcuts without G-Helper interfering. 

Alternatively, a feature that will sync the backlight slider in the G-Helper and my shortcuts on the keyboard will work for me too. For example; if I use my keyboard shortcuts to change my backlight, the slider should move too so there will be no synchronization issues.

And I wanna thank you for this great app, it saved me many times! :)

**Comment by seerge** [comment]
@IlNEOlI hello, either stop and disable asus optimization service (and restart app after) or update to 0.78

**Comment by IlNEOlI** [comment]
Updating to 0.78 solved my problem, thank you.
