### ISSUE TITLE
Unable to change Aura mode

### ISSUE THREAD

**Issue by TheUnknown249** [seerge/g-helper#543]
In the latest version of GHelper, there are some problems when both GHelper and ASUS optimization service are running. Everytime I turn off my screen and turn it on again, the keyboard backlight turns on even though I had it turned of before turning mff my screen. I guess the GHelper settings for backlight gets overridden by ASUS optimization service. When I disable that service, everything works fine except that now I can't change Aura modes (static, color cycle, etc)
using the default shortcut (FN + right and left arrow keys). Key bindings in GHelper aren't helpful since I don't have any of those M1, M2, etc keys and they get binded to F2, F3, etc, changing the default action of the keys like Vol mute and Vol up. The best solution would be to add Toggle AURA in FN + C actions in GHelper, or having the FN + Arrow keys in the list so the Toggle AURA can be binded to those keys. BTW I'm using a TUF laptop so that's why I don't have those M1, M2 keys.
Thanks in advance.

**Comment by seerge** [comment]
@TheUnknown249 hello, latest 0.78 doesn’t set any brightness levels if optimization service is running. Dis you try that?

**Comment by TheUnknown249** [comment]
Just tried the new build. Problem Solved. Thanks.

**Comment by TheUnknown249** [comment]
After a reboot I can't change AURA mode again. I have ASUS optimization service enabled and GHelper running. But using FN + Arrow left or right does nothing.

**Comment by TheUnknown249** [comment]
Seems like changing AURA with those arrow keys broke down completely :/.

**Comment by seerge** [comment]
@TheUnknown249 g-helper never controlled  FN-arrow keys in a first place.
