### ISSUE TITLE
about fn + c

### ISSUE THREAD

**Issue by lswlc33** [seerge/g-helper#545]
**Describe the bug**
When I press Fn+c, the function of the F function key changes compared to the original

**Clear scenario to Reproduce**
## F10 only has an off prompt, but it does not actually take effect  
![image](https://github.com/seerge/g-helper/assets/86835895/0770eef0-2c16-4a21-8cc4-799488947ed9)
![image](https://github.com/seerge/g-helper/assets/86835895/d493962b-421d-4f83-8fca-d185518f411a)
---
F2 F3 I tested the keyboard light, but in reality, the icon display on my keyboard should be a volume adjustment
and here is my key
![image](https://github.com/seerge/g-helper/assets/86835895/cfc96b2c-3655-4c1e-8aa4-178db18c71d4)
![image](https://github.com/seerge/g-helper/assets/86835895/469f6622-c66b-4999-9d17-4ed0d8c2d85f)
![image](https://github.com/seerge/g-helper/assets/86835895/a7248f3b-0037-4f64-a453-d457e496b821)

**my laptop**
![image](https://github.com/seerge/g-helper/assets/86835895/b3b7573e-b4ce-4cb2-99a9-eee2edc22127)

**Comment by seerge** [comment]
@lswlc33 hello

I don't know how touchpad on/off is controlled on TUF laptops, so that toggle won't work w/o optimization service

As for other hotkeys, which ones are "incorrect" ? from a screenshot it looks like F2-F4 are different , rest should be same. Do you know if this layout is specific to your model only or all TUF ?

**Comment by lswlc33** [comment]
@seerge I conducted a search and found that the second and first generation of TUF are like screenshot. Starting from the third generation TUF, they are new

F12 is Airplane mode ，it not work . F6 is Turn off the screen and it open prtsc , F11 is Sleep mode instead of hibernate mode

**Comment by lswlc33** [comment]
I also think it's not necessary. People are accustomed to F1 help, F5 refresh, F11 full screen, F12 dev tools, Fn is less to use in my view

**Comment by lswlc33** [comment]
I find a chinese web of asua about the big
different of different model.it maybe help

This page may be have other languages version,I didn't find it 
https://www.asus.com.cn/support/FAQ/1045882/
