### ISSUE TITLE
Can’t set any state of Fan Curv to OFF 

### ISSUE THREAD

**Issue by TomBonnot** [seerge/g-helper#547]
**Describe the bug**
On the UI, I can’t fix any point from the Fan Curv to OFF, for exemple, in silent mode the first point is set to OFF (Factory Settings), if I move it, it does instantly to 2000RPM, not less. 

**Clear scenario to Reproduce**
1. Go to Fans + Power
2. Click on any point of Fan Curv and try to set it to OFF (all the way down)
3. It stops at min to 2000RPM
4. Maybe it come from the UI, it seems like it sticks to the edge before going into OFF line. 

**Expected behavior**
That I could set, at least the two first points to OFF

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11652591/log.txt)
At the end I did exactly as I said before

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/35734114/aeec9080-61ee-4a24-a8a9-4640edbd5ef9) Factory settings
![image](https://github.com/seerge/g-helper/assets/35734114/f7a657d9-be54-47da-95da-ec971182f67c) The lowest I can do on the first Dot
![image](https://github.com/seerge/g-helper/assets/35734114/49697a3c-7b00-490a-9997-083b9744fe84) The lowest I can do on the second Dot

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ROG Zephyrus G14 GA401QM

**Asus software**
No Asus software is running. Debloated with debloat.bat from GHelper Github 

**Additional context**
I had this issue in the latest Version : 0.77.0.0 and I had this problem yesterday but I thought that it will solve itself with a reboot so I have waited before opening this ticket 
Much love

**Comment by seerge** [comment]
@TomBonnot hello, it's a dublicate and already fixed in https://github.com/seerge/g-helper/releases/tag/v0.78
