### ISSUE TITLE
[Feature request] Merge all update features to the same dialog and button

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#548]
First at all, thank you for the driver update feature!
Currently, we have separate Update sections: for the app and for drivers. This creates a kind of a non-consistency.

I propose to replace the /releases link to the Updates button (merge them): 
- show the program updates in the same dialog, on top of the drivers list.
- change the button label color when some new version is actually available.

![image](https://github.com/seerge/g-helper/assets/8934421/11e41672-210b-4d1e-9033-f31199e0e61e)

**Comment by seerge** [comment]
@ke1ne i don't really like that idea, as it will give wrong impression that g-helper is part of asus software package (which is not the case). Also g-helper has super-light and fast update checker and own update mechanism, while asus (surprise!) responds slowly, and take time to gather it's stuff :))
