### ISSUE TITLE
Hide the `.` from laptop model

### ISSUE THREAD

**Issue by TheBestPessimist** [seerge/g-helper#553]
![image](https://github.com/seerge/g-helper/assets/4482210/b3a9d5be-56fd-49a8-ada5-fe14476f01a7)

Super minor nitpick: For some reason GHelper shows the name of the laptop as `ROG Flow X16 GV601VI.`. Can the `.` at the end be removed?

**Comment by seerge** [comment]
@TheBestPessimist hello, it's not a nitpick ;) This is how I mark (visually) that app is running as admin. For screenshots.

**Comment by TheBestPessimist** [comment]
Wouldn't it be simpler (to comprehend by anyone) to update the title of the app? `G-Helper (Administrator)` and `G-Helper` ?
