### ISSUE TITLE
Right-clicking icon after reboot always shows "Turbo" as selected mode

### ISSUE THREAD

**Issue by jontomy** [seerge/g-helper#556]
**Describe the bug**
After a reboot, the performance mode shown as selected on the flyer that appears after right-clicking tray icon is always "Turbo"

**Clear scenario to Reproduce**
1. Set G-Helper to Silent or Balanced mode
2. Reboot system
3. G-Helper remains on Silent/Balaced mode but on right-clicking tray icon the mode selected is shown as "Turbo"

**Expected behavior**
Right-clicking tray icon shows the correct mode currently in use

**App Logs**
Please include and attach log.txt from [``%AppData%\GHelper``](url)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Laptop model: Zephyrus G14 2020 (GA401IV)

**Asus software**
- Armoury crate: not installed
- MyASUS: not installed
- No other Asus services running in background

[log.txt](https://github.com/seerge/g-helper/files/11676541/log.txt)

**Comment by jontomy** [comment]
Yes, it happens if I just quit the app and reopen it manually.

After I reopen app in the main G-Helper window the correct performance mode remains selected, but if I right-click tray icon it always shows Turbo as the selected mode.

Screenshot right after manually re-opening app, having selected "Silent" mode before closing app.
![Screenshot (353)](https://github.com/seerge/g-helper/assets/135830574/d75d4c31-2c65-4d85-9627-7d69a89e29a4)

**Comment by seerge** [comment]
@jontomy can you try this build ?

[GHelper.zip](https://github.com/seerge/g-helper/files/11677060/GHelper.zip)

**Comment by jontomy** [comment]
Same behaviour, still get the visual bug showing Turbo as the selected mode.

**Comment by seerge** [comment]
@jontomy 

If this build also won't work - then i'm keen to believe that it's some sketchy behavior of windows10 with it's native context menus :| 


[GHelper.zip](https://github.com/seerge/g-helper/files/11677424/GHelper.zip)

**Comment by jontomy** [comment]
On this one when I launch the app there is no "tick" on any of the performance modes.
And once I change to another mode it works well as expected.

**Comment by jontomy** [comment]
It's working on this one, amazing! Thank you!

**Comment by seerge** [comment]
Great, closing as completed then
