### ISSUE TITLE
Keyboard brightness not working Zephyrus G15 2022 (GA503RM)

### ISSUE THREAD

**Issue by JgS7** [seerge/g-helper#559]
Hi,

First of all, thank you for your program and for all your work :)

I have a Zephyrus g15 2022 (GA503RM). Everything works fine but when I try to change the keyboard brightness (or color, effect, etc) nothing happens. 

When I press the Aura key, the order is detected by the program (It changes the effect), but it does not have any actual effect on the keyboard. Same with the brightness up/down keys.

1. Press Aura key (fn+f4 in my case) of brightness keys.
2. Confirm in G-helper the action.

Expected behavior:
The keyboard should change color/effect/brightness, but nothing happens.

Im using windows 11 and I uninstalled Armoury crate with the official uninstaller. Also MyASUS is uninstalled and I used the debloat script.

As an additional information, Im using OpenRGB to control an external mouse and keyboard (logitech). The internal keyboard is detected as an Asus Aura Core Laptop (Asus ROG Strix SCAR 15) (Actually disabled because it doesnt work well). Im also attaching a video and the G-Helper Log.

Thank you!

[log.txt](https://github.com/seerge/g-helper/files/11681587/log.txt)

https://github.com/seerge/g-helper/assets/116883652/5fe66ab8-3060-438c-9464-44c42e8bb933

**Comment by seerge** [comment]
@JgS7 hello,  do you have Asus optimization service running?
Try to uncheck/check backlight checkboxes under Extra menu.

**Comment by JgS7** [comment]
> @JgS7 hello, do you have Asus optimization service running? Can it control backlight? Try to uncheck/check backlight checkboxes under Extra menu.

Hi, actually Asus optimization service is not running. I also tried checking/unchecking the checkboxes, but nothing :(

**Comment by seerge** [comment]
@JgS7 and when it's running, does it control backlight ? (you can close g-helper to verify)

**Comment by JgS7** [comment]
Now I tried it with the service running. Still not working (now when I press the brightness keys the screen banner doesnt even appear)

**Comment by seerge** [comment]
@JgS7 then looks like something with keyboard itself (probably on software side in windows)?

When it was working last time? Can you try armoury or openRGB?

**Comment by JgS7** [comment]
@seerge The last time it worked was with Armoury crate. I tried to reinstall it a few days ago and it worked. 
In openRGB the behavior is "weird". You can change the color using Direct mode, but when you try to save the preset, the program crashes. (Thats why I have it disablet for the keyboard).

**Comment by seerge** [comment]
@JgS7 well, since even asus optimization service has no effect, then i definitely can't help anyhow. In the log it's clear that app sends payload (with brightness or modes) to keyboard, so it does everything it can .

Try to check device manager, if all USB-HID devices are "ok" there. Try to install AC and check if it will wake it up.

**Comment by JgS7** [comment]
Hi, thank you for all your help. The device manager says that everything is working correctly. I installed AC and the keyboard started working as expected. But at the moment of uninstall it... Stopped working :(

**Comment by seerge** [comment]
@JgS7 that's very stange, as it should work w/o AC too (just on myasus/optimization service)

**Comment by seerge** [comment]
@JgS7 just in case, can you try this build ?

[GHelper.zip](https://github.com/seerge/g-helper/files/11682325/GHelper.zip)

**Comment by JgS7** [comment]
@seerge Same, it isnt working
[log.txt](https://github.com/seerge/g-helper/files/11682556/log.txt)

**Comment by seerge** [comment]
@JgS7 and this? try to set backlight brightness with hotkeys or slider under Extra
[GHelper.zip](https://github.com/seerge/g-helper/files/11682610/GHelper.zip)

**Comment by JgS7** [comment]
@seerge Same result, not working
[log.txt](https://github.com/seerge/g-helper/files/11682695/log.txt)

**Comment by seerge** [comment]
@JgS7 try this one instead. 

[GHelper.zip](https://github.com/seerge/g-helper/files/11686204/GHelper.zip)

**Comment by seerge** [comment]
@JgS7 this is my last attempt (try again to check/uncheck backlight checkboxes under Extra)
[GHelper.zip](https://github.com/seerge/g-helper/files/11688815/GHelper.zip)

If this doesn't work still (most probably)

Then I would advice to go through all steps since having AC running (at backlight working) till the moment it stops.

If you uninstall AC (using own uninstaller) - backlight should still work (as this is how asus software is designed, asus optimization service can set that)

**Comment by JgS7** [comment]
@seerge Nothing, it doesnt work.

I will try to (re)reinstall AC and see if I can touch something to make it work.

Thank you for your help :)

**Comment by JgS7** [comment]
@seerge Final feedback from AC: None of the basic effects appears to work, except the Aura Sync. If I have Aura Sync selected, I can use Aura/brightness keys to control the behabior of the keyboard... Something weird.

**Comment by seerge** [comment]
@JgS7 mb hardware got stuck? try to do a hard reset by turning laptop off, then pressing and and holding power button for 40 seconds then booting normally (it will take a bit longer to boot). It doesn’t touch any data just in case

**Comment by JgS7** [comment]
@seerge Looks li eits not the case... Still not working. Looks like I have the black sheep... Thank you for all your help and your time :)
