### ISSUE TITLE
Version 0.16/0.17 run on startup doesn't work

### ISSUE THREAD

**Issue by VitMasterB** [seerge/g-helper#56]
In version 0.16/0.17 'run on startup' doesn't work.

No problem in version 0.15

**Comment by seerge** [comment]
Can you check windows Even Viewer for errors associated with Ghelper?

**Comment by navhawk80** [comment]
The same issue. No need to reboot the windows to reproduce the issue. You can reproduce it as follow:
start app and set "Run on startup" than push Quit to manually close the app. Than start it again and see that option "Run on startup" is not active after restart.

**Comment by seerge** [comment]
Should be fixed in https://github.com/seerge/g-helper/releases/tag/v0.19
@navhawk80 @VitMasterB
