### ISSUE TITLE
Can't download update v0.80, flagged as virus

### ISSUE THREAD

**Issue by jthompson05** [seerge/g-helper#560]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
I cannot download GHelper version 0.80 due to it being flagged as a virus by both Microsoft Edge and Windows. 

**Clear scenario to Reproduce**
Download GHelper v0.80 from GitHub or use the update feature in GHelper. 

**Expected behavior**
GHelper can usually update itself. Edge will typically give me warnings about GHelper, but still allows me to download it. This time I cannot download it at all. 

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11681841/log.txt)

**Screenshots or screencasts**
![Screenshot 2023-06-07 154709](https://github.com/seerge/g-helper/assets/96457853/22f461ff-7b59-4ca1-86c7-2d8a06007e44)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - 2022 G14 (GA402RJ)

**Asus software**
- MyASUS installed

**Comment by seerge** [comment]
@jthompson05 hello, false positives from defender can happen (even tho they don't trigger for me on 2 separate laptops).

You can either download 0.79 or try a very-beta of 0.81 :)) 

[GHelper.zip](https://github.com/seerge/g-helper/files/11682013/GHelper.zip)

**Comment by jthompson05** [comment]
@seerge Thanks. I was able to update it via GHelper by temporarily disabling Windows defender.
