### ISSUE TITLE
Version 0.80 flagged as Trojan:Script/Wacatac.H!ml by Windows Defender

### ISSUE THREAD

**Issue by DanWiseProgramming** [seerge/g-helper#561]
**Describe the bug**
https://github.com/seerge/g-helper/releases/download/0.80/GHelper.zip is flagged as Trojan:Script/Wacatac.H!ml.

**Clear scenario to Reproduce**
1. Download linked archive with Windows Defender turned on.

**Expected behavior**
Should not be flagged as a virus of 'Severe' threat level.

**App Logs**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by seerge** [comment]
@DanWiseProgramming  hello, false positives from defender can happen (even tho they don't trigger for me on 2 separate laptops).

You can either download 0.79 or try a very-beta of 0.81 :)) 

[GHelper.zip](https://github.com/seerge/g-helper/files/11682013/GHelper.zip)

**Comment by DanWiseProgramming** [comment]
Thanks @seerge

**Comment by TheBestPessimist** [comment]
ftr, 0.81 is also detected. i didn't find a way for us, normies, to inform microsoft that it's not malware so i guess all we can do is disable defender until we unzip.

**Comment by seerge** [comment]
@TheBestPessimist well - you are technical, so you can just do a git pull and compile app by yourself instead ;)

**Comment by pettijohn** [comment]
> so you can just do a git pull and compile app by yourself instead ;)

Thanks for this tip, I was getting Defender flags on 0.86. Easy enough to `git pull && git checkout v0.86` then run the release command below. I had to manually update the version in the `csproj` but no biggie!

Release command:
https://github.com/seerge/g-helper/blob/05aae069b47173f03b1f45b9b62074e489c5d3f0/.github/workflows/release.yml#L22
