### ISSUE TITLE
Problems with the backlit keyboard of the G14 2021 

### ISSUE THREAD

**Issue by AreyUA** [seerge/g-helper#562]
I ran into a problem and can't find a solution. When working from the battery in eco mode, after the keyboard goes out, in 99% of cases the backlight does not light up when you press the keys, at night you have to press F2 or F3 to make it count again.
Or maybe I did something wrong? Tell me please

**Comment by seerge** [comment]
@AreyUA I think you need to upload a log here first so i can look at that at least

**Comment by AreyUA** [comment]
And where is he going to ?

**Comment by AreyUA** [comment]
And where is he going to ??

**Comment by seerge** [comment]
@AreyUA who? I need a log from  ``%appdata%/ghelper``

**Comment by seerge** [comment]
@AreyUA i see, stop Asus Optimization service (from windows Services app) and then restart g-helper

**Comment by AreyUA** [comment]
I'm afraid to climb there myself, but I don't have a ready-made BAT?

**Comment by seerge** [comment]
@AreyUA you can use debloat.bat from homepage if you want

**Comment by AreyUA** [comment]
I did, it didn't help :-(

**Comment by seerge** [comment]
You need to run it as admin, and restart g-helper after

**Comment by AreyUA** [comment]
[log.txt](https://github.com/seerge/g-helper/files/11682204/log.txt)

**Comment by AreyUA** [comment]
wow, thank you very much, it seems to have worked

**Comment by seerge** [comment]
Great!
