### ISSUE TITLE
Brightness control buttons only control iGPU, not dGPU brightness

### ISSUE THREAD

**Issue by whereismybugfix** [seerge/g-helper#563]
### Description
When in "Standard" GPU mode, screen brightness control doesn't change the brightness. However, if I switch to "Eco", it's just fine. My guess is that for some reason brightness control buttons (Fn+F7, Fn+F8) only control iGPU, not dGPU. I noticed that right after G-Helper installation. I updated G-Helper to the latest version; still no luck. 

### Scenario to reproduce
1. Change GPU mode to Standard
2. Press Fn+F7 or Fn+F8 to change the brightness
3. Notice that brightness hasn't been changed

### Expected behavior
Screen brightness supposed to be under control for any GPU mode.

### App Logs
- Attached the most recent log: [log - Copy.txt](https://github.com/seerge/g-helper/files/11682015/log.-.Copy.txt)

### Laptop
 - OS: Windows 10 (yeah, that's weird for my laptop's model, but I had to downgrade it from Win11 when I bought it for compatibility purposes)
 - ROG Zephyrus M16 GU604VI

### Asus software
- all standard Asus services are running on the background out of box
- Intel Graphics Command Center

### Some words of appreciation
P.S.: thank you for this wonderful software from all Asus laptop users who discovered this hidden gem!

**Comment by seerge** [comment]
@whereismybugfix does brightness control start working if you restart windows (in standard mode) ?

**Comment by whereismybugfix** [comment]
Unfortunately, nope. It's still controlling iGPU brightness. I've found out that it's supposedly controlling iGPU by switching between "Standard" and "Eco" while noticing the difference in brightness. The only way to control dGPU brightness for me is to fully switch to "Ultimate" and reboot.

**Comment by seerge** [comment]
@whereismybugfix in standard mode you have nvidia optimus controlling your display, try to experiment with  different optimus settings ? (set it to optimus or nvidia only?)

**Comment by AudreyAP** [comment]
I have a GU604VI and don't have this issue. Keyboard controls always adjust backlight.  

Is Nvidia display mode is set to "automatic select", not "Optimus"? If it's on Optimus, try automatic select. 

Also, this may be a windows 10 problem - laptop shipped with 11 so API changes may have happened that were not backported?

**Comment by seerge** [comment]
@whereismybugfix hello, any updates? did you had a chance to check things I asked about in previous comment? :)

**Comment by whereismybugfix** [comment]
Hello everyone. Yeah, you might be right. Win10 potentially brings some stochastics. For now I solve this issue by doing the following:
1) click on GPU mode
2) reboot laptop

If I choose the mode and reboot, it controls screen brightness as expected. If I don't reboot, well, good luck controlling that.

As the issue I described might be a corner case in the presence of Win10, and seemingly there's no one else affected besides me, I'd suggest we can close this thread.

**Comment by whereismybugfix** [comment]
> As the issue I described might be a corner case in the presence of Win10, and seemingly there's no one else affected besides me, I'd suggest we can close this thread.

**Comment by fransauncion11** [comment]
hi can we reopen this one? I am experiencing the same exact issue but with Windows 11 :) Thank you!

**Comment by seerge** [comment]
@franasuncion please check this topic for a solution https://github.com/seerge/g-helper/discussions/1042

**Comment by franasuncion** [comment]
@seerge ok will follow and monitor. Thanks!
