### ISSUE TITLE
[Feature request] Identify programs using gpu, and ability to toggle gpu preference for them

### ISSUE THREAD

**Issue by digitalsignalperson** [seerge/g-helper#564]
**Is your feature request related to a problem? Please describe.**
AC had a feature that showed current programs using the GPU. That's cool to see.

Also, e.g. I wanted to force the Epic Games Launcher to not use dGPU, so had to go to windows System > Display > Graphics > Custom options for apps > Add an app (Desktop app) > Browse > and find "C:\Program Files (x86)\Epic Games\Launcher\Portal Binaries\Win64\EpicGamesLauncher.exe" > then click Options > then click "Power saving" (GPU: Intel...)

**Describe the solution you'd like**
Could have a list of programs that are running and using the GPU

If there's a way to manage the Windows Graphics "Custom options" within g-helper without going through windows settings, that would be cool to click a checkbox/radio button to force a preference. I could see a checkbox corresponding to if there is a custom option for the app or not, and radio buttons for the same options presented in windows settings (Let Windows decide, Power Saving [igpu], High performance [dgpu])

Or, could just have a "copy to clipboard" with the path of the exe file, or "open file location"

**Describe alternatives you've considered**
Sort task manager by GPU engine column, then open file location to get the path to the exe, then manually edit windows settings.

**Comment by seerge** [comment]
@digitalsignalperson are you on Nvidia or AMD? As  (somewhere) in nvidia control panel you can you can open list of apps using GPU

**Comment by ke1ne** [comment]
@digitalsignalperson With NVIDIA, you have kind of this feature built-in:
1. Run NVIDIA Control Panel.
2. Select Desktop in the menu bar then check Display GPU Activity Icon in Notification Area.
3. In Windows taskbar, mouse over (or right click) the GPU Activity icon.

**Comment by digitalsignalperson** [comment]
![image](https://github.com/seerge/g-helper/assets/45611618/2c302a36-19e9-491d-a7cb-9265c072039a)

Hmm don't see that option. Maybe not in studio driver?
With NVIDIA Control Panel open, I see the system tray icon, but doesn't show anything about activity when I launch a game.

**Comment by ke1ne** [comment]
@digitalsignalperson I have a Game driver version, so can't check the Studio version, sorry. Try to update it.

**Comment by digitalsignalperson** [comment]
no problem, thanks for pointing out that driver feature, good to know!

geforce experience says it's the latest, released 05/30/2023

**Comment by ke1ne** [comment]
@digitalsignalperson I meant trying the Game driver instead of the Studio version.

**Comment by digitalsignalperson** [comment]
ah, it only appears when in standard mode (I was on ultimate mode)

k I'll just close this request. thanks for the tips
