### ISSUE TITLE
Windows defender warning

### ISSUE THREAD

**Issue by Moorole** [seerge/g-helper#565]
am getting severe windows defender warning:
Trojan:Script/Wacatac.H!ml
the microsoft information about it is this:
https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Script/Wacatac.H!ml&threatid=2147814524
it is the first time after installing all previous versions.
Am on a g14 2020 with windows 10 22h2 with latest defender updates
Thank you for your help and I hope I was just a bit ove careful.
Thank you so much for this program and all the time you put in.
Cheers from Romania
Ole

**Comment by kuonji-arisu** [comment]
Just ignore it, this is a common false positive for C# applications, there is nothing to worry about.

**Comment by CyberGamer224466** [comment]
I have the same issue and was wondering if its really safe to ignore the warning.

Thx for all the good work on the app as it makes using my g14 2020 way easier.

Cheers

**Comment by seerge** [comment]
@Moorole @CyberGamer224466 

Hello, false positives from defender can happen. You can either download 0.79 or a 0.81 instead 
https://github.com/seerge/g-helper/releases/tag/v0.81
