### ISSUE TITLE
External monitor detection in Optimized mode

### ISSUE THREAD

**Issue by Mantas-Jakucionis** [seerge/g-helper#566]
It would be useful to have an extra option to auto enable dGPU when an external monitor is connected to HDMI (which links straight to dGPU), **even when** the options "Keep GPU disabled on USB-C charger in Optimized mode" is enabled.

**Comment by seerge** [comment]
@Mantas-Jakucionis hello, main problem here is that if dGPU is disabled, then windows don't trigger ANY events that app can listen and get notified about monitor being connected (over USB)

Like this - don't work https://stackoverflow.com/questions/11983111/detect-when-new-display-is-connected

So I'm simply not aware how to detect that. If you know - please feel free to contribute :)

**Comment by ErayOzcanUCLL** [comment]
what would be a manual work around to get it to start the 2nd monitor then? it sometimes just works and sometimes doesn't ... do you run a gpu intensive application to get it started or do you change gpu modes for it?
