### ISSUE TITLE
Layout bug and inconsistent lighting w/ XG Mobile

### ISSUE THREAD

**Issue by aLaaah** [seerge/g-helper#568]
**Describe the bug**
Since v0.80.0.0 the Ghelper layout doesn't properly display the XG mobile box (when enabled), there's a red line instead of the usual box.

Also, the XG Mobile lighting checkbox (under extra) isn't consistent, and even if set off, at every restart the XG lighting restarts again. You've to click the checkbox twice to disable the lighting again.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11685194/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/26120549/d8c317bb-f1a2-427d-8f47-53591b7e5b70)

**Comment by seerge** [comment]
@aLaaah hello, thanks for spotting. This build should fix layout

[GHelper.zip](https://github.com/seerge/g-helper/files/11686158/GHelper.zip)

As for the light, behavior was same before 0.80 as well. In this build app will send light command to XGM as soon as you enable it via button

**Comment by aLaaah** [comment]
> 
Thank you for the quick layout fix, really appreciated!

About the lighting, the issue I mentioned comes up when you don't disable the XGM.

If you enable the XGM, disable the lighting, and then power-off the laptop with the XGM still enabled, the following boot will re-enable the lighting again, despite the checkbox is set to off in the Ghelper settings.

**Comment by aLaaah** [comment]
Just tested, works great! Thank you!
