### ISSUE TITLE
GPU Undervolt feature on the G-Helper app.

### ISSUE THREAD

**Issue by INST1NCT00** [seerge/g-helper#576]
**Is your feature request related to a problem? Please describe:**
I'm always frustrated when I have to use MSI Afterburner to undervolt my dGPU as it causes a high CPU usage problem(apparently this is really common in laptops). Upon googling it, I found out that it happens due to the laptop disabling the dGPU sensors when no dedicated process is running resulting in MSI receiving an error message and repeatedly pinging the dGPU. When the user reported this to MSI, their response was that "MSI Afterburner is not meant to be used on laptops".

Having an undervolting ability in the app will definitely make it better than it already is and would be a pretty neat feature to have, if it is possible at all.

**Describe the solution you'd like:**
An undervolting feature built into the app, not dissimilar to the overclocking one already present.

**Describe alternatives you've considered:**
The only alternative is MSI Afterburner as no other software supports laptops. Even Afterburner has limited support as already mentioned above.

**Additional context:**
Here is a screenshot of the "System" process using CPU on idle:
![image](https://github.com/seerge/g-helper/assets/125669213/236ec59a-0e87-441c-9161-b5d17de6c2d2)

And how it looks without MSI Afterburner running:
![image](https://github.com/seerge/g-helper/assets/125669213/5bc0014a-cc22-4e29-8630-e3416d7eafd3)

**Comment by TheBestPessimist** [comment]
See https://github.com/seerge/g-helper/issues/469

**Comment by seerge** [comment]
@INST1NCT00 hello, I don't even have a device with nvidia gpu at the moment :) so it's not really doable (even tho it was something like that in nvidia API). Also keep in mind that afterburner is a project developed over years, and literally dedicated to that feature, expecting from me (with 3 month of experience in windows dev) to do something equal would be overestimation ;)

**Comment by Chikage0o0** [comment]
I don't support adding this feature either, obviously you can close Afterburner after the undervoltage setup is complete.

**Comment by LJGJM** [comment]
i get 15% more battery when i undervolt my ryzen 5 4600h by -30, would like this in GHelper

**Comment by MckenzieDavis** [comment]
You know you can apply profile on startup without having to run MSI afterburner on statup right? just disable run 

Enable this option
![Screenshot 2023-06-14 192506](https://github.com/seerge/g-helper/assets/82803124/25359779-3328-40a1-ad2b-b09b10cf2228)

And disable this option
![Screenshot 2023-06-14 192550](https://github.com/seerge/g-helper/assets/82803124/e0fe6c51-3ca2-447d-8a74-19740381c7f5)

Undervolt will apply even without running MSI Afterburner

**Comment by seerge** [comment]
@LJGJM 
> i get 15% more battery when i undervolt my ryzen 5 4600h by -30, would like this in GHelper

This request is about dGPU undervolting. You won't get any battery life from that (and even in that case - big doubts) unless you have GPU enabled

**Comment by seerge** [comment]
@MckenzieDavis afterburner can't control fans on laptops, undervolting is set on driver level - so you indeed don't need app running at all.

**Comment by LJGJM** [comment]
I just wanted to ask, did 0.90.0 update support power limits on tuf laptops? because i also installed nimez drivers on it and i want to know if it was normal amd or nimez

**Comment by seerge** [comment]
@LJGJM i have no idea what is "nimez drivers", but added CPU power limits in 0.90 should work for all Ryzen CPU's where it was no native armoury endpoints for power limits (i.e. if you didn't have  a power slider in fans+power before)

**Comment by INST1NCT00** [comment]
I see that the out of scope label has been removed so I just wanted to ask if this is something you are working on? Also, the CPU undervolt feature is greatly appreciated 👍

**Comment by LJGJM** [comment]
> @LJGJM i have no idea what is "nimez drivers", but added CPU power limits in 0.90 should work for all Ryzen CPU's where it was no native armoury endpoints for power limits (i.e. if you didn't have a power slider in fans+power before)

Im talking about https://www.amernimezone.com/
Thanks for adding power limits!

**Comment by seerge** [comment]
A beta with undervolting slider (under Fans+Power GPU section). You can try with a small negative values and see what happens.

If you going to test - please post a log here :) 

[GHelper.zip](https://github.com/seerge/g-helper/files/11910759/GHelper.zip)

**Comment by TheBestPessimist** [comment]
[log.txt](https://github.com/seerge/g-helper/files/11915148/log.txt)
my log, however i dont see the undervolting slider
![image](https://github.com/seerge/g-helper/assets/4482210/e7a00903-075c-4f08-b60c-3ce7d65fa60b)

**Comment by seerge** [comment]
@TheBestPessimist oke, thanks. Quick question - does undervolting work for you in Afterburner ? If so - do you have a discord? :)

**Comment by TheBestPessimist** [comment]
you can find me on discord as `thebestpessimistzzzzzzzzzzzzzzzz`.

Regarding "undervolting works". As far as i can see, increasing frequency works, so i assume undervolting should work too
![image](https://github.com/seerge/g-helper/assets/4482210/ab08f0c4-de12-4fb4-952b-6f855a97c48e)

**Comment by TheBestPessimist** [comment]
Update: i saw the slider once, then it disappeared!
the slider said `Undervolt`, but i didnt get to use it.

**Comment by ke1ne** [comment]
@seerge maybe, useful? https://github.com/JamesCJ60/nvidia-overclock

**Comment by seerge** [comment]
@ke1ne no, that's and old tool just for overclock (that g-helper app already does). 

Furthermore latest version of UXTU seem to use my implementation of overclocking https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/blob/master/Universal%20x86%20Tuning%20Utility/Scripts/GPUs/NVIDIA/NvTuning.cs

**Comment by ke1ne** [comment]
@seerge the expansion is non-negotiable! =)

**Comment by NJinsei** [comment]
<img width="508" alt="image" src="https://github.com/seerge/g-helper/assets/89779681/388e898e-13a3-46f2-8868-bf0bb9d0221f">

I see the undervolt option is there anything I should test ?

**Comment by NJinsei** [comment]
After trying it I noticed that the undervolt slider only appears when I switch to standard mode and then open the fans + power section for the first time. After that, it disappears and I can’t access it again. I tried changing the values while it was visible, but I didn’t see any difference in performance or stability.

**Comment by seerge** [comment]
@NJinsei well, then most probably it doesn't work. We have also tested it with @TheBestPessimist with no luck neither.

Main problem that I don't have a device with nvidia on hands now at all :) I just had a guess that one of the values in nvidia API could be the right one ;)

For now I have put this thing on hold, until I manage to catch G14 2023 on sale somewhere ....

**Comment by NJinsei** [comment]
Ah no worries then, thank you for your hard work and dedication to this app. I hope you can get your hands on a G14 soon :)

**Comment by seerge** [comment]
Ok @NJinsei @INST1NCT00 @TheBestPessimist and all other undervolting experts, I have a question to you (so please explain to me like i'm an idiot)

I managed to get my hands on G16 Strix with 4080, and first I want to see practical results of undervolting using Afterburner at least

SCREEN 1 : Is Voltage / Frequency curve just by "Overclocking" : 
![Screenshot 2023-07-20 181238](https://github.com/seerge/g-helper/assets/5920850/6d7d6998-2dbc-464b-92c7-2205475ffb39)

SCREEN 2: I have edited curve, as it's usually explained in undervolting guides, by picking maximum achievable clock and shifting curve in way that clock will have lower volts, rest (on the right) is flat.
![Screenshot 2023-07-20 181337](https://github.com/seerge/g-helper/assets/5920850/8d7346c8-fc71-4f4c-a20d-a304c000eb66)

Given that clock won't go higher than my desired max (2400 in my case), flat part of the chart doesn't matter (as it won't go there).

What the difference between simple overclock (that g-helper already does) and undervolting ? It seem to do same things.

I also get almost identical results in 3DMark or Furmark from this.

**Comment by TheBestPessimist** [comment]
Last updated: 2023-07-21--12-12-13

Hey, i guess i made the confusion bigger with my talk to you on discord. That is my bad. I will try to explain.

What you do in GH right now is _undervolting_ or _overclocking_ (i see both of those as just a matter of semantics): when we move the frequency slider to +10, +20, +205, etc, we increase the frequency at a particular voltage. This is exactly like you did in Picture 1.

![image](https://github.com/seerge/g-helper/assets/4482210/deea4373-ceac-4bfa-a33c-450d285fef1c)

On the other hand, if you move the frequency slider to -10, -20, -100, then you decrease the maximum frequency that the GPU cores reach at a particular voltage. Again, just like you did in Picture 1.

FTR, after a recent bios update, i use GH exclusively and don't need Afterburner anymore for GPU tweaking (only using Afterburner for the OSD).

---

Now for the confusing part: When you said you added an "Undervolting" slider, i thought you had some magical new feature which did ... _something_. 
Now, I did not know what that something was, so obviously i wanted to test it.
I updated GH to latest version, and looked for the slider which was supposed to do _something magical_.

The rest you already know: at first i did not have the slider, then _the slider_ appeared and disappeared apparently randomly, then finally when we tried on discord the custom build which always shows **the slider**... bummer. It did nothing.

So from my perspective, what GH already has now is already an _overclocking_ feature (after reading and re-reading this text for a few times, maybe the term _overclocking_ is more correct to what we do).

----

As for what would _undervolting_ do? Well, i imagine that it should work like it does in Throttlestop: Make the GPU use less Watts for the same core frequency/FPS.
Well guess what? we already have that! Just move **THE SLIDER** (not the Undervolting slider from just above, but `Core Clock Offset`) to the right. The end.

**Comment by seerge** [comment]
@TheBestPessimist my question was not what undervolting is supposed to do :) (i know that).

I wanted to say that setting positive clock offset via Afterburner/ G-Helper seem to do effectively the same as undervolting by modifying curve in Afterburner . Both just adjust curve, that higher frequencies will have a bit lower voltages :)

So looks like there is nothing to be done here, you can already achieve everything with that clock offset slider ;)

**Comment by seerge** [comment]
@RahulVivekNair well, whole point is that clock doesn't seem to go higher than some "max" value anyway (i tried to load GPU on max in both Furmark / 3dmark / some games). So generally only difference between "undervolting" by modifying and flattening curve or by just shifting curve (via OC slider) is the right part of the curve with clocks that GPU won't reach anyway :)

**Comment by RahulVivekNair** [comment]
> @RahulVivekNair well, whole point is that clock doesn't seem to go higher than some "max" value anyway (i tried to load GPU on max in both Furmark / 3dmark / some games). So generally only difference between "undervolting" by modifying and flattening curve or by just shifting curve (via OC slider) is the right part of the curve with clocks that GPU won't reach anyway :) 

Hmm,you're right,in games and these benchmarks it is not going over but when I tested,I was using stable diffusion to generate images and it did go over probably because it's more gpu bound, not sure. Anyway,if I'm understanding it correctly not much more can be done I assume.

**Comment by joe-700** [comment]
It would be good to be able to power limit the GPU. That way you could move the voltage curve up using the current slider and limit the power to hold stable frame rates at lower temps.

As it stands, the GPU will use a lot of power to generate the best frame rates and then start to bounce off the thermal throttle limit causing in game stutters. If you adjust the slider you will get better performance but it will still use as much power as it can to get highest frame rates, so the frames will be higher but the temps will still go up at the same rate until it bounces off the thermal throttle.

Nirvana would be to increase the performance using the current slider but also limit the GPU power to control temps and stay below the thermal limit, resulting in relatively high frames and stable temps with no stutters.

**Comment by seerge** [comment]
Usually you can adjust power with ``nvidia-smi`` tool, but GPU power limits are locked on driver level for most recent drivers so there is no way you can do that. Asus itself doesn't provide any endpoints / tools for it, only for dynamic boost adjustment.

**Comment by joe-700** [comment]
Ahh, ok. I have noticed that the GPU power draws change depending on the windows power mode selected... i.e. in silent profile the power draw seems to be very low (around 40-50 watts) and then the power draw goes up for normal and again for turbo. I wonder how this is being done, maybe its set by the BIOS or it could be that this is controlled by the OS. If it was windows then it would be dead simple to control.

The work around is to tune the frame rate limits for each game. That way you can get better performance using the clock speed slider and prevent the GPU from drawing the maximum allowed power, but this means setting max frames for each game in the Nvidia control panel, and re-tuning if you change the graphics settings i.e. turning up the textures or using ray tracing. Its a pain and normally you have to restart the game each time you alter the frame limits.

It would make much more sense to just set the power draw for the temps and fan noise you are happy with and let the in game frames do there thing.

**Comment by seerge** [comment]
@joe-700 per "windows" power mode ? or mode in g-helper (i.e. asus "bios" mode). If so - each mode consists of bunch of hardcoded settings (including CPU and GPU power limits, fan curve, voltages, etc). But you can customize only parts that asus allows us to (i.e. what you see editable in armoury).

**Comment by joe-700** [comment]
I'm using the g-helper power modes. I guess we may have to work with what we have in that case. At least we know that if we want lower GPU power draw then we can fine tune the silent or balanced modes in the g-helper tool.

I have found a couple of hidden windows power mode settings for things like max CPU frequency, these seem to hold if you set them for the balanced profile in windows, there is a chance that there are also hidden settings for the dGPU.

**Comment by TheBestPessimist** [comment]
> It would be good to be able to power limit the GPU.

@joe-700 wouldn't these 2 sliders be enough?
![image](https://github.com/seerge/g-helper/assets/4482210/d9a12d7e-f927-49d7-a5df-38dbc4b74186)

**Comment by mbze430** [comment]
anyone here have a 40-series mobile?  I have the 4090 mobile with the latest drivers from Nvidia but no voltage control. not even in afterburner.

are the 40-series mobile locked for voltage?

**Comment by RahulVivekNair** [comment]
> anyone here have a 40-series mobile?  I have the 4090 mobile with the latest drivers from Nvidia but no voltage control. not even in afterburner.
> only thing thta is available is the curve optimizer
> 
> are the 40-series mobile locked for voltage?
> 

I don't think any laptop gpu has unlocked voltage control

**Comment by Moorole** [comment]
I would say the curvee optimizer in msi afterburner allows you to control voltage. So as soon as curve optimizer works you cannot talk of locked voltage control...

**Comment by seerge** [comment]
Ok. So long story short. Manually editing a clock / voltage curve doesn't seem to be doable via native NVidia API. But obviously it's still possible to shift whole curve up / down with a ``Clock Offset`` slider in G-Helper already.

As far as I see, the only "difference" people do with manually adjusting a curve - is by limiting a clock from the top side (i.e. not go above X MHx)

That's actually possible to do in another way, via ``nvidia-smi`` command in power shell (as admin)

Lock GPU clock between 0 and 2000Mhz 

```
nvidia-smi -lgc 0,2000
```

Reset clock to defaults
```
nvidia-smi -lgc
```

I can incorporate this "method" inside app, by adding a "Max Core Clock" slider in GPU section.
Would that satisfy you here ?

**Comment by seerge** [comment]
@TheBestPessimist @NJinsei @INST1NCT00 @joe-700 @mbze430 @Moorole 

You can check a new build that lets you do both : set clock/voltage offsets (same as always) AND set Clock Limit

[GHelper.zip](https://github.com/seerge/g-helper/files/12328431/GHelper.zip)

With 2 sliders you can achieve same "curve" as afterburner would do with it's "undervolting"

![Frame 2 (2)](https://github.com/seerge/g-helper/assets/5920850/ba448534-6352-4ca5-aa10-7c0c7b63c3f9)

**Comment by joe-700** [comment]
I think this is a really good idea, personally this is the only thing I use afterburner for. The issue doing this in afterburner is that the curve does not always stick, you can even see it in the plot above, the curve is difficult to get straight.

I'll give it a test a bit later

**Comment by Moorole** [comment]
just wondering if, for an undervolt, i have to have a negative core frequency or a positive?

**Comment by seerge** [comment]
@Moorole positive (literally  look at picture)

- Increase Clock Offset - to get **more performance within same power limit**
- Lower Clock Limit - to **lower power consumption** (i.e. get less heat)

**Comment by Moorole** [comment]
soo if i put +100mhz it will do 100 mhz more at a certain voltage. and, to safe energy rather then overclock it i have to add a clock limiter to reach a clock of my choice with less voltage. 
Hope i am not confusing more with my question

**Comment by seerge** [comment]
@Moorole by setting Clock Offset you Overclock and Undervolt at the same time, i.e. for same voltage - it will be higher clock, and for same clock - lower voltage.

**Comment by Moorole** [comment]
nice one mate. just did unigine heaven benchmark and was able to decrease voltage at 1785 mhz (my max i guess, cannot go higher?!?) from 0,95v to 0,83v and watts from 62 to 53 which is almost 20 % with my 1650 gtx (+165mhz). with more i got instability. 
Thank you so much for this feature and the whole app
I guess with this undervolt working properly, the core frequenz limit is a bit unnesessary because i have enough heatroom now for full speed :D
Cheers :)

**Comment by Moorole** [comment]
> @TheBestPessimist @NJinsei @INST1NCT00 @joe-700 @mbze430 @Moorole @ke1ne
> 
> You can check a new build that lets you do both : set clock/voltage offsets (same as always) AND set Clock Limit
> ### [GHelper.zip](https://github.com/seerge/g-helper/files/12329675/GHelper.zip)
> 
> With 2 sliders you can achieve same "curve" as afterburner would do with it's "undervolting"
> 
> ![Undervolting (1)](https://user-images.githubusercontent.com/5920850/260314251-8553d03b-797d-451f-b60c-c42e95bc04da.png)

btw, core limiter works very good. it puts  frequency as set
maybe you could put the word "undervolt" in brakets after clock offset for people to understand quickly

**Comment by seerge** [comment]
@Moorole i wanted to show both Clock offset and Voltage offsets using label on the right. But I didn't figure out how to get that voltage anyhow (as you need to read that curve points to calculate this, and nvidia doesn't provide that anyhow)

**Comment by Moorole** [comment]
Hmm. One could make a table for each mhz which gives a certain voltage in Hwinfo. But I don't think it is important to set your undervolt by applying a negative voltage rather than a frequency which is added on the set frequency at a certain voltage. It is a little backwards and goes against the logic they tought us in school but it does the job. I remember I really took a while to understand what I am doing in msi afterburner. And it is the same story here. 
I think a little disclaimer when you put your mouse on gpu frequency and the disabled negative area will make everyone understand and use properly. 
Am actually proud that this program, from simply replacing armoury crate, becomes the toolbox tailored onto our asus rogs with everything needed. Asus should reward you as from armoury crate being a reason not buy to g-helper as a reason to buy asus!

**Comment by Moorole** [comment]
> @Moorole i wanted to show both Clock offset and Voltage offsets using label on the right. But I didn't figure out how to get that voltage anyhow (as you need to read that curve points to calculate this, and nvidia doesn't provide that anyhow)

This will be set in the bios of the gpu or in the driver but I think it is just too much effort to dig out.

**Comment by ke1ne** [comment]
> * Increase Clock Offset - to get **more performance within same power limit**
> * Lower Clock Limit - to **lower power consumption** (i.e. get less heat)

@seerge hey, thank you! just got it, trying. is it auto-applying?
![image](https://github.com/seerge/g-helper/assets/8934421/89755689-44c5-431b-a9c9-62bb4b52a082)

**Comment by seerge** [comment]
@ke1ne it is, but 2900 is quite high :) i doubt your 3070 ever reaches that, so it won't have any effect)

**Comment by ke1ne** [comment]
> @ke1ne it is, but 2900 is quite high :) i doubt your 3070 ever reaches that, so it won't have any effect)

But the default value looks even higher?
![image](https://github.com/seerge/g-helper/assets/8934421/069dd44d-8a8e-4120-97e9-51442b98707a)

**Comment by seerge** [comment]
It's a top limit, default - is no limits at all.

**Comment by ke1ne** [comment]
> It's a top limit, default - is no limits at all.

If the top limit is kind of hardcoded now, maybe, there is some way to get it via API? To avoid overload, etc.

**Comment by seerge** [comment]
Changes from latest build posted here are already live in https://github.com/seerge/g-helper/releases/tag/v0.111

Given that new clock limit slider gives you pretty much same results as you would with manually modifying clock/volt curve, I consider this as completed :)

**Comment by Abishekkarthik07** [comment]
Heyy, I have a quick doubt in the undervolting part of GPU. Just now i bought a 4060 g14 and I'm soon gonna use ghelper so before I use it I wanted to learn everything about it. So to improve my thermals I get the part of me decreasing the clock limit and increasing the clock offset to undervolt my GPU for better temps. But before testing it out with the benchmark I wanted to understand what is memory clock offset and by how much I should set it and how I should test it.

**Comment by TheBestPessimist** [comment]
> by how much

That depends from GPU to GPU. for some you can go +200, for others you can go +600 for the same GPU model in the same laptop model.

try it and see!
https://discourse.tbp.land/uploads/default/original/1X/e741730b2b41b7ecd3672f986951038ca43af531.jpeg

**Comment by Abishekkarthik07** [comment]
just now i casually ran heaven and i got a 44 avg fps on standard mode in performance. i dont know whats the problem cuz litterally ran it yesterday and i hit an avg of 150 fps. yesterday my clock speed was aroubd 2250 and today for some reason it is 1150 or something in armory crate so i guess this is what the problem is in but i didnt even install ghelper till now and tweak the undervolting settings. just was testing how stock AC was perfomrning and i didnt tweak any settings in AC also just left it to the default. idk why im not able to hit a high clock speed today for some reason. pls help me out on what i should do. i treid rstarting but it didnt solve the issue. i just now installed ghleper and ran the same standard and performncae mode stopping all asus services but still same 44 fps. anything i mightive done and need to look at which.
(Long story short, my GPU running at 1000mhz which is very low, how do I make it run higher)
Rog boost gives me a 2400 MHz but that's for like a second and then it goes to below my base clock which it shows as set to 1100 MHz. Os my base clock too low or something, is that why. If so how to increase it.
