### ISSUE TITLE
Zenbook Pro 14 GPU support

### ISSUE THREAD

**Issue by alasdairvfr** [seerge/g-helper#577]
Apologies if this has been posted before, didn't see it in the FAQ:

I think this may be a compatibility thing with the intel based Zenbooks but as it stands, the GPU config options aren't available to me.  Everything else appears to be there in the app, just the GPU shows iGPU+dGPU with no option to change settings

I used g-helper a lot on my G14 but ended up with a Zenbook Pro 14 which doesn't use armory crate but has this other app ProArt Creator hub instead.  This app doesn't have the same options as AC, not that AC is any good to begin with..

**Comment by seerge** [comment]
@alasdairvfr does your laptop support hardware disabling of GPU and mux switch ? If no - then there are no modes to show in GPU section :)

**Comment by alasdairvfr** [comment]
Hi Seerge, it does have a mux switch.  Even my old D14 without the mux allowed the choice b/w ECO | Standard | Optimized 

I ran it on Optimized before, now there are no buttons at all.

**Comment by seerge** [comment]
@alasdairvfr can you upload a log from %appdata%/ghelper here ?

**Comment by alasdairvfr** [comment]
[log.txt](https://github.com/seerge/g-helper/files/11693123/log.txt)

**Comment by alasdairvfr** [comment]
That would explain it!  I bet it can be done, just differently.  If adding this support for Zenbook Pro is something you want to do, I'm happy to help given I have the device.  I'm not much a developer, especially in C# but willing to share files and test things

**Comment by seerge** [comment]
@alasdairvfr 

Can you crate a dump as explained here and upload it here ? I will look at it, mb it's just different IDs of same thing ..

> Download ACPICA tools from here: https://acpica.org/downloads/binary-tools Extract, run `acpidump` tool, then you can use the other tool called `iasl` to decompile resulting files to something that humans can read.
> 
> Both tools include comprehensive help messages, but if all you want to achieve is dumping your DSDT and decompiling it, run `acpidump.exe -b` to dump them all to .dat files. They'll be placed in the location you ran the tool from. Then run `iasl.exe dsdt.dat` and the decompiled ACPI table will be created as `dsdt.dsl`.

**Comment by alasdairvfr** [comment]
[dsdt.txt](https://github.com/seerge/g-helper/files/11693247/dsdt.txt)
I had to rename it from .dsl to .txt in order to upload it.  Let me know if this works

**Comment by seerge** [comment]
@alasdairvfr hello, thanks.

I looked at it and it seem to be VERY different in terms of endpoints to what G14 has. I'm afraid that w/o physical device it's practically not possible to test / add any "unique" things from Zenbook Pro

**Comment by InCerryGit** [comment]
I am also using a Zenbook Pro 14. Based on the discussion above, does it mean that currently, it does not support GPU switching?

**Comment by seerge** [comment]
@InCerryGit most probably - yes :) if you start app and dont see GPU section , it's not supported

**Comment by seerge** [comment]
@InCerryGit @alasdairvfr if you really want to experiment you can try to find endpoints responsible for ECO flag by yourselves.

1. How does GPU disabling works  on your models in a first place? Does it disappear from device manager completely when disabled via asus software?

2. You can try to start with the one that actually "reports" if GPU is disabled or not . For that please run the scan script from https://github.com/seerge/g-helper/issues/38 **TWICE** First time when GPU is enabled, then disable it (using asus own software) and run script again. Post both outputs here

**Comment by InCerryGit** [comment]
> @InCerryGit @alasdairvfr if you really want to experiment you can try to find endpoints responsible for ECO flag by yourselves.
> 
> 1. How does GPU disabling works  on your models in a first place? Does it disappear from device manager completely when disabled via asus software?
> 2. You can try to start with the one that actually "reports" if GPU is disabled or not . For that please run the scan script from [Endpoint discovery for different laptop models #38](https://github.com/seerge/g-helper/issues/38) **TWICE** First time when GPU is enabled, then disable it (using asus own software) and run script again. Post both outputs here

@seerge 
Thank you very much for your suggestion. In MyAsus, there is an option called MUX Switch, which allows you to select between 
"MSHybrid" and "Discrete GPU". However, no matter how I try, the dGPU does not disappear in the Task Manager.

**Comment by seerge** [comment]
@InCerryGit MUX switch is what in Armoury (and G-helper respectively) called Ultimate mode, when you route internal display to dGPU. 

Try to change this setting, and then run scan and compare results (some value should change from 0 to 1 or vise versa)

@alasdairvfr has mentioned that he had Eco mode as well?

**Comment by alasdairvfr** [comment]
I can change performance mode and there are some fan profiles with TDP controls baked into the ASUS ProArt thing but nowhere to dynamically route all apps to integrated on battery and discrete on AC.  That's what I'm looking for.  There is a MUX option for force discrete or stick with optiimus.  I did a couple 3dmark runs and didn't find MUX to have made a difference but could be just that one bench.

I took for granted the ability to ignore dgpu unplugged but I'm (for now) in windows assigning certain apps to leverage igpu.  I don't game unplugged but one app i was using today fired up the 4070 and my power draw hit 25w.  The app doesn't need dgpu to run... I'm now sipping 9-11w with it running on the intel.

@seerge I'll run the script in a bit and post the results.

**Comment by alasdairvfr** [comment]
Not sure whats up with the formatting but here is with igpu only

60023 : ffffffffffff0004 (-65532)                                                                                       60024 : 51ec8086 (1374453894)                                                                                           60026 : 0 (0)                                                                                                           60059 : 0 (0)                                                                                                           60061 : 0 (0)                                                                                                           60068 : ffffffffffff0000 (-65536)                                                                                       60069 : ffffffffffff0000 (-65536)
60078 : 20001 (131073)
60079 : ffffffffffff0000 (-65536)
600b1 : ffffffffffff0200 (-65024)
80041 : ffffffffffff0000 (-65536)
80042 : 0 (0)
80043 : ffffffffffff0000 (-65536)
80044 : ffffffffffff0000 (-65536)
90026 : 1 (1)
100023 : 0 (0)
100054 : ffffffffffff0000 (-65536)
100063 : 1 (1)
110013 : 0 (0)
110014 : ffffffffffff0000 (-65536)
110015 : ffffffffffff0000 (-65536)
110016 : ffffffffffff0000 (-65536)
110019 : 2060001 (33947649)
11001f : 0 (0)
120057 : 880000 (8912896)
120061 : ffffffffffff0000 (-65536)
12006d : 0 (0)
120078 : ffffffffffff0000 (-65536)
130041 : 0 (0)

**Comment by alasdairvfr** [comment]
Here is with dgpu engaged.  There are some differences!  Hope this helps :)

60023 : ffffffffffff0004 (-65532)
60024 : 51ec8086 (1374453894)
60026 : 0 (0)
60059 : 0 (0)
60061 : 0 (0)
60068 : ffffffffffff0000 (-65536)
60069 : ffffffffffff0000 (-65536)
60078 : 20001 (131073)
60079 : ffffffffffff0000 (-65536)
600b1 : ffffffffffff0200 (-65024)
80041 : ffffffffffff0000 (-65536)
80042 : 0 (0)
80043 : ffffffffffff0000 (-65536)
80044 : ffffffffffff0000 (-65536)
90026 : 1 (1)
100023 : 0 (0)
100054 : ffffffffffff0000 (-65536)
100063 : 1 (1)
110013 : 14 (20)
110014 : 13 (19)
110015 : ffffffffffff0000 (-65536)
110016 : ffffffffffff0000 (-65536)
110019 : 2060001 (33947649)
11001f : 0 (0)
120057 : 880000 (8912896)
120061 : ffffffffffff0000 (-65536)
12006d : 0 (0)
120078 : ffffffffffff0000 (-65536)
130041 : 0 (0)

**Comment by seerge** [comment]
@alasdairvfr hello, thanks for the output. But as you have just wrote - there is no way to disable GPU on your case, so output of the script won't change as GPU is managed by windows. So Eco mode is definitely not supported on your devices as i understand. 

As for Ultimate mode (i.e. Mux switch) - then i need a scan results of situation when discrete graphics is forced.
