### ISSUE TITLE
stuck with broken MyAsus services, missing bloat.bat file

### ISSUE THREAD

**Issue by FELIX-exe** [seerge/g-helper#579]
yesterday i´ve downloaded the debloat.bat file and gave g-helper a try, didnt suit me, decided today to get back to default so when i came back here to look for the bloat.bat file to get my asus services back to default i didnt find it, you removed it, can you please send me the bloat.bat file back
here is my discord where you can send it please: thisuserisanillusion#6063

**Comment by NJinsei** [comment]
https://[raw.githubusercontent.com/seerge/g-helper/main/bloat.bat](https://raw.githubusercontent.com/seerge/g-helper/main/bloat.bat)

**Comment by seerge** [comment]
@FELIX-exe hello, you can literally start or stop all asus services with a single button in the app now.

If not both bloat.bat and [debloat](https://raw.githubusercontent.com/seerge/g-helper/main/debloat.bat) files are not going anywhere.
