### ISSUE TITLE
Cannot change wallpaper after G-Helper setup

### ISSUE THREAD

**Issue by samchon** [seerge/g-helper#580]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
After installing G-Helper, I never can change wallpaper, like below video.

Whatever I change, wallpaper exactly turned back to default.

https://youtu.be/BvV9-5Rk0Xc

**Clear scenario to Reproduce**
I can't describe how to reproduce, but such bug be resolved if manually closes `AsusWallpaperService`.

Of course, when the `AsusWallpaperService` re-executed, such bug be occured again.

**Expected behavior**
Do not harm wallpaper setting.

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: ASUS Rog Flow X16 2022

**Asus software**
- Armoury crate: uninstalled
- MyASUS installed: No
- Other Asus services running in background: closed every asus services in `TaskManager` except `AsusWallpaperService`

**Additional context**
In my case, solved by removing `AsusWallpaperService`.

I can't sure G-Helper and AsusWallpaperService, which one is occuring the bug, but just report it.

**Comment by seerge** [comment]
@samchon hello, how is g-helper connected to this? If you say that ``AsusWallpaperService`` doing that - then you should probably stop / disable it? :) Most probably it's part of Armoury Crate package, so g-helper deliberately won't touch it :)
