### ISSUE TITLE
Make translation/localization optional

### ISSUE THREAD

**Issue by danploeger** [seerge/g-helper#584]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A dropdown menu/list of available languages in the app OR an entry in the `config.json` to be changed, e.g. from `de-DE` to `en-US`.

**Describe alternatives you've considered**
Currently the only way to change to a different language is to change the Windows language.

**Additional context**
This is particularly helpful when the app translation is ambiguous (to compare the text in another language) or for help/discussion in GitHub/reddit, where the English text is required to really know what the discussion is about or to ask specific questions.

**Comment by danploeger** [comment]
Example: the German translation of `Auto adjust Windows Power Modes` is ambiguous. I had to look in GitHub for the English original text to understand that it's about `Windows Power Modes` and not about a `high performance profile`.

**Comment by seerge** [comment]
@danploeger hello, you already can do that https://github.com/seerge/g-helper#manual-app-language-setting :)

**Comment by danploeger** [comment]
Have missed that one. Thanks 👍 👍
