### ISSUE TITLE
Keyboard Backlight wont turn on once it sleeps due to timeout.

### ISSUE THREAD

**Issue by Twel12** [seerge/g-helper#587]
[log.txt](https://github.com/seerge/g-helper/files/11708520/log.txt)

**Describe the bug**
Once Keyboard backlight goes to sleep due to timeout by G-Helper it does lit backup on interaction with trackpad or the keyboard.

**Clear scenario to Reproduce**
1. Set G-Helper keyboard backlight keyboard to lets say 10 second.
2. Let keyboard light turn off.

**Expected behavior**
Backlight should turn on , when in interaction with trackpad or keyboard.

OS: Windows 11
Laptop : Zephryus G15 2021, GA503QM

**Asus software**
- MyASUS installed

**Comment by seerge** [comment]
@Twel12 hello, from the log i see that asus optimization service is running. You need to stop it and then restart g-helper to handle hotkeys (incl brightness) :)

**Comment by Twel12** [comment]
thanks for your reply :), really appreciate the work you do.
