### ISSUE TITLE
Problems with backlight, fn function on Zephyrus g15 2022 with Win11

### ISSUE THREAD

**Issue by Polinomio94** [seerge/g-helper#590]
**Describe the bug**
-when i disable the keyboard backlight then it doesn't reactivate with the trackpad or with any key as it happened with the asus armoury crate program (it only reactivates if I click on the key to increase the brightness).

- by activating the fn key lock, the f1,f2,..etc keys no longer work, holding or not fn it gives the same reaction.

-the program doesn't start automatically when windows starts, I flagged the relative setting and tried to manually add it to the startup programs but nothing changes.

**Desktop (please complete the following information):**
 -  Windows 11
 - Asus Zephyrus G15 2022

**Asus software**
- MyASUS installed

**Comment by seerge** [comment]
@Polinomio94 stop asus optimization service and restart app, or update to 0.82

As for fn-lock it works only in one direction, opposite is not possible 

For auto start check windows Event Viewer for possible crashes, as explained in readme

**Comment by Polinomio94** [comment]
Thank you very much, i solved  the problem with backlight

**Comment by seerge** [comment]
How is it related to g-helper? You have probably set a limit in nvidia control panel or so

**Comment by Polinomio94** [comment]
Because i have this problem only after installed g-helper and i hadn't change anything in the pc, also in nvidia panel. I thought that it could be a known problem

**Comment by seerge** [comment]
I don’t think it’s related anyhow

**Comment by seerge** [comment]
If it’s limited exactly to 60 fps its a nvidia driver limiting it (unless you have some setting afterburner or so)

So try to reset settings in nvidia
