### ISSUE TITLE
Fn-Lock feature not working on GA401IHR on G-Helper 0.76

### ISSUE THREAD

**Issue by StefanAdrian03** [seerge/g-helper#591]
**Describe the bug**
Fn-Lock feature not working on GA401IHR on G-Helper 0.76.
On my asus GA401IHR model 2021 which is having the same hardware as the 2020 model but the keyboard layout is different ,is the 2021 layout.
After they added support on version 0.76 [Extended Fn-Lock support to G14 2020 model; https://github.com/seerge/g-helper/issues/504] F2,F3,F4 are not working ,On version 0.74 or 0.75 the Fn lock feature works very well on my laptop even F2-F4.
The problem occurred after update on 0.76 and is persisiting even on the latest version

**Clear scenario to Reproduce**

Go to Laptop Keyboard > Extra
Click on Process Fn+F hotkeys without FN checkbox

**Expected behavior**
You should be able to make use of Function keys (F) without FN

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11712258/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model GA401IHR

**Asus software**
- Armoury crate uninstalled
- MyASUS installed
- All Asus services disabled as in debloat.bat

**Comment by seerge** [comment]
@StefanAdrian03 cause all models containing "GA401I" were marked as 2020 version. Is your model GA401IHR - the only one containing I in the name and being 2021 version or are there others ?

Try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/11712353/GHelper.zip)

**Comment by StefanAdrian03** [comment]
i think is the only one, it has the same spec as the 2020 but the upgraded keyboard layout of the 2021 

https://rog.asus.com/ro/laptops/rog-zephyrus/2021-rog-zephyrus-g14-series/helpdesk_download/

It is listed with the other 2021 models GA401Q and it is the only one 2021 with GA401IHR
I can confirm that the version that you have sent me it is working on all F2-F4 keys
Thanks for the solution ,hope that this problem will not occures on future releases

**Comment by seerge** [comment]
Ok, great. Closing as completed then
