### ISSUE TITLE
App crashes if the app tries to elevate rights to admin but the user cancels

### ISSUE THREAD

**Issue by danielcandea** [seerge/g-helper#593]
If the app doesn't run as admin and there is an action which requires admin rights, if the user presses No in UAC, the app crashes.

I can reproduce this on my 2021 Zephyrus G14, model GA401QM, running G-Helper v0.8.2 on an up-to-date Windows 11. Every time I go to Extra form and press the Stop button for Asus services and get the UAC prompt and press No, the app crashes.

I have a patch for this which works on my machine and would like to create a PR but can't push my branch into the repo. How can I proceed? Do I need to fork the repo and create a PR from my fork?

**Comment by seerge** [comment]
@danielcandea i will fix it by myself :) thanks for spotting.

**Comment by seerge** [comment]
@danielcandea this build should fix it
[GHelper.zip](https://github.com/seerge/g-helper/files/11713418/GHelper.zip)

**Comment by danielcandea** [comment]
@seerge The change fixed the issue, thank you!
