### ISSUE TITLE
Overlapping the boundary box

### ISSUE THREAD

**Issue by Inaiso** [seerge/g-helper#594]
In the new 0.82 version the bottom of "Fn+C" is crossing the boundary of the "Key Bindings" section of "extra". 

![1](https://github.com/seerge/g-helper/assets/132625303/c08c77cf-fe94-47c4-a7ab-51e965f903d9)

![2](https://github.com/seerge/g-helper/assets/132625303/efeee630-c9b0-4f80-90d4-9cc966849993)

**Comment by seerge** [comment]
@Inaiso hello, this one should fix it :) 
[GHelper.zip](https://github.com/seerge/g-helper/files/11714302/GHelper.zip)
