### ISSUE TITLE
UI Bug latest release (after moving the Turbo boost check)

### ISSUE THREAD

**Issue by TomBonnot** [seerge/g-helper#60]
![image](https://user-images.githubusercontent.com/35734114/224129766-86e831f1-534f-4d1f-bd28-ed5b42375b96.png)

Just so you know we can’t reach the Default button, Auto Apply check and Apply Fan Settings button.
Your work is going amazing ! Kudos

**Comment by seerge** [comment]
Can you check if it still exists in https://github.com/seerge/g-helper/releases/tag/v0.21 ?

**Comment by TomBonnot** [comment]
![image](https://user-images.githubusercontent.com/35734114/224143688-bf1911e0-d721-4c4f-a53f-7717578659b6.png)
Nope, still there ! :/ 
(tho I saw that you’ve added a server connection haha, my SimpleWall detected it)

**Comment by seerge** [comment]
@TomBonnot can you check if it looks ok here ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/10936601/GHelper.zip)

**Comment by TomBonnot** [comment]
You actually made me laugh haha 
You’ve reorganized everything  
![image](https://user-images.githubusercontent.com/35734114/224177257-fd943363-4b6d-4570-9bdf-79edea1d264e.png)
Guess it’s all fine now hehe 
GG

**Comment by seerge** [comment]
Cause windows forms, and native elements are so terribly bad, so they literally look different on different windows, and in UI editor. I had to reorganize stuff to fix it at least somehow ...
