### ISSUE TITLE
Add an option to rebind Fn+F5 to toggle Fan Overdrive

### ISSUE THREAD

**Issue by Xaymar** [seerge/g-helper#600]
**Is your feature request related to a problem? Please describe.**
Armoury Crate by default uses Fn+F5 to toggle the Fan Overdrive mode, where Fans spin at their maximum rated speed - in my Laptop this roughly ends up being 11000 RPM. This is currently not possible in G-Helper, so heavy long term workloads end up with the "limited" fan RPM of ~5000 RPM only.

**Describe the solution you'd like**
An option to rebind one of the Fn+FX combinations to toggle this mode

**Describe alternatives you've considered**
CAD designing a better cooling solution that doesn't suck so much, but that is still a bit far away.

**Additional context**
This might be yet another endpoint to control. See endpoint discovery: https://github.com/seerge/g-helper/issues/38#issuecomment-1577066939

**Comment by seerge** [comment]
@Xaymar hello, on all new models fn-f5 cycles through profiles :)

**Comment by Xaymar** [comment]
That is different from my model then. On my model, with Armoury Crate installed, Fn+F5 toggles Fan Overdrive. There is no button that cycles between profiles - that must be done manually.

**Comment by seerge** [comment]
@Xaymar well, then you are probably a rare case ;) i definitely won't be rebinding pretty much main hotkey in the app to that. 
Do you know that you can run max fan speed using powershell ?

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110014, 1)
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110013, 1)

```

**Comment by Xaymar** [comment]
Well, I didn't want to replace the functionality, I wanted an option to have the option to make it do the same as Armoury Crate does. Title was a bit misleading here, I apologize.

> Do you know that you can run max fan speed using powershell ?

Yes, but max fan speed and fan overdrive are different things. Max fan speed is roughly 5500 RPM. Fan Overdrive is 11000 RPM. A tiny difference of almost twice the speed.

**Comment by seerge** [comment]
@Xaymar that is the same thing, did you try command listed ?

**Comment by Xaymar** [comment]
> that is the same thing, did you try command listed ?

Yes, it does not trigger Fan Overdrive. Fan Overdrive is noticable due to the noise the fans will make, but the above command seems to be doing nothing at all.

**Comment by seerge** [comment]
Is it  this one ? 
```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00110018, 1)
```

**Comment by Xaymar** [comment]
Also no effect. I'll probably have to monitor what Armoury Crate does to find the proper endpoint.

**Comment by seerge** [comment]
@Xaymar then it seems to be quite unique for your case, as other models don’t have that at all :) 

So I can’t help much here

**Comment by Xaymar** [comment]
After an Armoury Crate "Driver" update, my model's Armoury Crate behavior is now identical to what you describe. Fn+F5 no longer toggles fan overdrive like the manual says it should, but instead toggles between Internal and Dedicated GPU modes.

Still haven't figured out how they did it, and I most likely can't even figure it out now anymore. Especially given that the Fan speed slider in the updated Armoury Crate have the same issue that G-Helper has. :/
