### ISSUE TITLE
Allow attaching Windows Power Policy to G-Helper "Performance Profiles"

### ISSUE THREAD

**Issue by Xaymar** [seerge/g-helper#601]
**Is your feature request related to a problem? Please describe.**
Armoury Crate ties Silent to a modified "Power Saver" policy, Balanced to "Balanced" policy, and Turbo to a modified "High Performance" policy. This results in significantly different behavior in each profile, instead of just different fan curves and power limits. For example, Silent will actually run the CPU at nearly 35°C instead of 90°C+ with the proper power policy

**Describe the solution you'd like**
A field in the configuration window for profiles to change which Windows power profile is attached to 

**Describe alternatives you've considered**
Currently using AutoHotkey to read the log file and apply the power profile.

**Additional context**
Possibly helpful:

- https://learn.microsoft.com/en-us/windows/win32/api/powrprof/nf-powrprof-getcurrentpowerpolicies
- https://learn.microsoft.com/en-us/windows/win32/api/powersetting/nf-powersetting-powersetactivescheme

**Comment by seerge** [comment]
@Xaymar hello, this is app's behavior by default (it's called windows power modes). You can de-couople them by unchecking corresponding flag under Extra

**Comment by Xaymar** [comment]
Then that feature doesn't appear to be working at all. The checkbox is checked, yet nothing is being changed in the Power Options - I'm in the Silent profile, yet High Performance is still selected. :/

Sorry.

**Comment by Xaymar** [comment]
See [video](https://share.xaymar.com/view/4d40a50f-9cb1-403d-bb8d-5f1d43d7a071) of the feature being on, yet not switching profiles at all. Probably should have reported a bug instead of a feature request in this case.

**Comment by seerge** [comment]
@Xaymar you need to have "Balanced" power plan selected (the one that allows power mode switching)

**Comment by seerge** [comment]
@Xaymar you mix power plan and power modes.

Power mode setting is here 
![powermode](https://images.idgesg.net/images/article/2021/07/windows-11-power-mode-100895295-large.jpg?auto=webp&quality=85,70)

**Comment by seerge** [comment]
If you want to set custom power plans instead (why?) you can also do that using config, just check readme first 

https://github.com/seerge/g-helper#custom-power-plans-with-each-mode

**Comment by Xaymar** [comment]
> why?

This is what Armoury Crate does, so I was hoping G-Helper would be a drop-in replacement for it. Without changing those, the device will run at 113°C in Silent mode, which - as you can hopefully agree with - is a bit high. It also draws almost 200W from the power brick without the Power Saver plan/policy, compared to the 59W it would draw with the proper plan. I'll try the .json modification.
