### ISSUE TITLE
[QUESTION] Use Windows snip instead of saving screenshot?? on press of F6

### ISSUE THREAD

**Issue by Twel12** [seerge/g-helper#602]
Modern applications mostly are great with handling clipboard consisting of images and its the default way of keybing via asus , is there anyway by which instead of saving screenshot as a file we could just open the snip and sketch tool (and you can save as image from  there if u want). I did find out the terminal command for it * ms-screenclip: * , in-case you dont like it , please let me know :).

**Comment by seerge** [comment]
@Twel12 if you talk about Fn+F6 - then it's handled by keyboard on hardware level, not by app (it literally emits windows clip on modern devices). So it's a already the case.

**Comment by seerge** [comment]
@Twel12 for me  KeyboardHook.KeyPress(Keys.Snapshot); does the same thing (opens snapshot app). This is on stock windows 11

**Comment by Twel12** [comment]
weird, for me it just saves a screenshot copy instead locally :/ .

**Comment by seerge** [comment]
@Twel12 probably because it's a setting ;)

![Screenshot 2023-06-11 151817](https://github.com/seerge/g-helper/assets/5920850/f0b70ad2-2cef-4713-917a-98bf7f12579b)

I won't be changing this behavior, as current way gives best flexibility

**Comment by Twel12** [comment]
aah , i never knew this was an option. Thanks and yes this seems a better implementation also could you share your Publish Section Configuration ? , i have never used Visual studio before so having troubles with building project as an exe.
