### ISSUE TITLE
Asus GA-502DU fn+f6 not working without the asus optimization service 

### ISSUE THREAD

**Issue by Yaksi** [seerge/g-helper#603]
Whenever I close all the asus services the fn+f6 stops working, the function for that is normally closing the screen without getting into sleep mode. Other than that normally everything works without any of the services, the mute button, key brightness and so on.

After opening the asus services, it starts working again.

It is the asus optimization services that gets the function back.

 - OS:  Windows 11
 - Asus GA-502DU

**Asus software**
- No armory create 
- No MyASUS

**Comment by seerge** [comment]
@Yaksi  Can you press fn+f6 and then upload log here from %appdata%/ghelper ? it should include corresponding key-code then

**Comment by Yaksi** [comment]
So this is the log without having the optimization service;        6/11/2023 2:41:30 PM: Key: 53 

This one is with the optimization service;
6/11/2023 2:43:16 PM: WMI event 53
6/11/2023 2:43:17 PM: Monitor Power Off
6/11/2023 2:43:17 PM: Backlight:5D-BA-C5-C4-00
6/11/2023 2:43:20 PM: Monitor Power On
6/11/2023 2:43:20 PM: AutoSetting for Online
6/11/2023 2:43:20 PM: Optimization service is running
6/11/2023 2:43:20 PM: BatteryLimit = 60 : OK
6/11/2023 2:43:20 PM: Mode = 0 : OK
6/11/2023 2:43:20 PM: 9897998c-92de-4669-853f-b7cd3ecb2790
6/11/2023 2:43:20 PM: Eco flag : -65536
6/11/2023 2:43:20 PM: Mux flag : -65536
6/11/2023 2:43:20 PM: ScreenOverdrive = 1 : OK
6/11/2023 2:43:20 PM: Auto:5D-BA-C5-C4-01

**Comment by seerge** [comment]
@Yaksi try this build 
[GHelper.zip](https://github.com/seerge/g-helper/files/11714645/GHelper.zip)

**Comment by Yaksi** [comment]
Doesn't seem to work, tried a reboot and checked the logs as well. The log is the same as this one PM: Key: 53.

**Comment by seerge** [comment]
@Yaksi hello, if optimization service is running  - then it should be handling hotkeys, not the app.

Only if it's stopped app takes over

Try this build and check if it helps
[GHelper.zip](https://github.com/seerge/g-helper/files/11714896/GHelper.zip)

**Comment by Yaksi** [comment]
The optimization service is closed (I have checked from services also the layout function works when the optimization service is closed), btw all the other asus services are also closed fyi. 

Tried the latest one, cant get it working, and the log is the same as well.

**Comment by seerge** [comment]
@Yaksi but do you see "Screen off toggle" after Key 53 in a log ? 

If so - app tries to turn off your screen, but it could be that in your case asus did some own custom trick to turn off display

**Comment by seerge** [comment]
As what i did, i just linked already existing binding to Toggle Screen to your FN+F6

![Screenshot 2023-06-11 175009](https://github.com/seerge/g-helper/assets/5920850/371afb4a-42b8-46fb-bacf-e862d47d475d)

Check if this binding work in general for you (if you set it to one of M-keys for example)

**Comment by Yaksi** [comment]
Hmm odd that it is not working still. I understood what you did. The toggle screen works on m1 m2 or any of the options but doesn't work with fn+f6. I mean it is not that big of an issue I don't want to bother you too much I just wanted to report. 

Also I am not seeing anything other than key 53 in the log so no screen of toggle.

**Comment by Yaksi** [comment]
6/11/2023 7:34:36 PM: Key: 124
6/11/2023 7:34:36 PM: Screen off toggle
6/11/2023 7:34:37 PM: Failed to turn off screen. Error code: 0. The operation completed successfully. 
6/11/2023 7:34:37 PM: Listener stopped
6/11/2023 7:34:37 PM: Failed to turn off screen. Error code: 0. The operation completed successfully. 
6/11/2023 7:34:37 PM: Monitor Power Off
6/11/2023 7:34:37 PM: Backlight:5D-BA-C5-C4-00
6/11/2023 7:34:41 PM: Monitor Power On
6/11/2023 7:34:41 PM: AutoSetting for Online
6/11/2023 7:34:41 PM: Input: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&7a61a78&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
6/11/2023 7:34:41 PM: BatteryLimit = 60 : OK
6/11/2023 7:34:41 PM: Mode = 0 : OK
6/11/2023 7:34:41 PM: 9897998c-92de-4669-853f-b7cd3ecb2790
6/11/2023 7:34:41 PM: Eco flag : -65536
6/11/2023 7:34:41 PM: Mux flag : -65536
6/11/2023 7:34:41 PM: ScreenOverdrive = 1 : OK
6/11/2023 7:34:41 PM: Auto:5D-BA-C5-C4-00

This is the log I am getting after putting m3 for toggle screen and pressing it.

**Comment by seerge** [comment]
@Yaksi if it works for m1-2 it should for fn+f6 :)) one more attempt 

[GHelper.zip](https://github.com/seerge/g-helper/files/11715210/GHelper.zip)

**Comment by Yaksi** [comment]
Yep, all good now 👍 Thanks for all the afford. :)

**Comment by seerge** [comment]
Ok
