### ISSUE TITLE
Cannot see the wattage value in slider

### ISSUE THREAD

**Issue by Inaiso** [seerge/g-helper#607]
In the new .83 version cannot see what wattage is set at in the slider of Platform and CPU. 

![1](https://github.com/seerge/g-helper/assets/132625303/d54a6835-0bb1-41e4-a031-1454b3837c37)

![2](https://github.com/seerge/g-helper/assets/132625303/f886bc5c-3272-4b56-b813-fd04f8a8062c)

**Comment by seerge** [comment]
@Inaiso should be fixed here (and i have reuploaded 0.83)
[GHelper.zip](https://github.com/seerge/g-helper/files/11716120/GHelper.zip)
