### ISSUE TITLE
Cosmetic: App sometimes opens in the bottom center of the screen

### ISSUE THREAD

**Issue by Brunnis** [seerge/g-helper#610]
**Describe the bug**
This is a minor cosmetic issue: The app will sometimes open in the bottom center instead of the bottom right. This appears to only happen the first time the app is opened after an external monitor (that has been configured as primary display) has been attached. It also only appears to occur if the laptop display has scaling configured (in my case 150%). Subsequent opens of the app result in correct alignment, i.e. bottom right.

**Clear scenario to Reproduce**
1. Set laptop display to 150% scaling.
2. Attach external monitor that has been configured to act as primary display.
3. Open G-Helper.
4. G-Helper opens centered at the bottom of the external display.
5. Press the 'X' to hide G-Helper.
6. Open G-Helper again.
7. G-Helper is now located to the bottom right.

**Expected behavior**
G-Helper should always open at the bottom right.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11718608/log.txt)

**Screenshots or screencasts**
![bild](https://github.com/seerge/g-helper/assets/20064358/2122a08b-28aa-460b-bce1-c6f0f6da21a5)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: GA402XI (G14 2023, RTX 4070)

**Asus software**
- Armoury crate (or it's services installed): No
- MyASUS installed: No
- Other Asus services running in background: None (all manually deactivated)

**Comment by Brunnis** [comment]
Thanks for the quick turn-around, but the issue remains. Each screenshot below is taken immediately after plugging in the external display and opening G-Helper.

Laptop screen set to 1920x1200 (100% scaling). External screen is set as primary and 2560x1440 (100% scaling):

![bild](https://github.com/seerge/g-helper/assets/20064358/5a969764-302a-41d8-ab75-7f81fc0251be)

Laptop screen set to 2560x1600 (150% scaling). External screen is set as primary and 2560x1440 (100% scaling):

![bild](https://github.com/seerge/g-helper/assets/20064358/2590e976-21b6-481c-aafb-36e00d94b3c2)

**Comment by seerge** [comment]
I have added second screen size check after windows is shown (not sure if it will help tho)
[GHelper.zip](https://github.com/seerge/g-helper/files/11735592/GHelper.zip)
