### ISSUE TITLE
'CPU Boost' gone on devices with no "Power Limits" support

### ISSUE THREAD

**Issue by manciuszz** [seerge/g-helper#614]
I've noticed v0.84 lacking 'CPU Boost' dropdown menu
![image](https://github.com/seerge/g-helper/assets/2539661/2712e8a9-b6ae-4c25-9655-1c80537b8201)

**Comment by seerge** [comment]
@manciuszz 

I just moved it to the left section (where all cpu / gpu sliders are) to free up space for profiles dropdown :)

And I completely forgot that it could be case when there is no power sliders (on old laptops)

This build should fix it

[GHelper.zip](https://github.com/seerge/g-helper/files/11726560/GHelper.zip)

**Comment by seerge** [comment]
@manciuszz yeah, visual studio editor seem to fail to generate ui that scales properly all the time :)

This one should be better

[GHelper.zip](https://github.com/seerge/g-helper/files/11726783/GHelper.zip)
