### ISSUE TITLE
Ghelper keybind

### ISSUE THREAD

**Issue by aLaaah** [seerge/g-helper#615]
Hello again,

I'm aware this feature is already available when you use the ROG key, but would be cool to have also a way to bring up/close the Ghelper window with a keybind combination (ie: alt+shift+G).

This would be quite useful for the Flow (as it's keyboard is frequently unavailable when the screen is rotated), or when you use an external keyboard in general.

Cheers.
A.

**Comment by seerge** [comment]
@aLaaah hello, you can already do that https://github.com/seerge/g-helper#keybinding-to-open-g-helper-from-external-keyboards

ctrl + shift + f12
