### ISSUE TITLE
Periodic update checks

### ISSUE THREAD

**Issue by GlaZedBelmont** [seerge/g-helper#617]
GHelper periodically checks for an update, only seems to do it on launch of the app, which if you're like me and don't reboot often, means I need to go kill ghelper and relaunch it manually.

Also is there a way to switch from releases to pre-releases since right now it only pulls releases.

**Comment by ryanbrue** [comment]
Maybe a manual check for update button would be better?

**Comment by GlaZedBelmont** [comment]
Yes that would work too, maybe a section for GHelper in the new Updates section? From: ryanbrueSent: June 13, 2023 8:00 PMTo: seerge/g-helperCc: Glazed_Belmont; AuthorSubject: Re: [seerge/g-helper] Periodic update checks (Issue #617) Maybe a manual check for update button would be better?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by GlaZedBelmont** [comment]
yeah that would work, or a GHelper section in the new Updates button section with  drivers and BIOS

**Comment by seerge** [comment]
I can put update trigger not on app start, but rather on main windows show (and limit to once per day)

**Comment by EvilPT** [comment]
If I may, in order to avoid a new schedule task or people complaining that G helper might or not be waking up computers from sleep mode (even tough might not be able to, people will still find a reason to complain), I would say a simple manual check for update like ryanbrue said would be the best option

**Comment by ryanbrue** [comment]
I agree with EvilPT, I think a manual check would be great for those who like to make sure they are on the most up-to-date version, and it wouldn't add any more overhead with automatic checking.

**Comment by seerge** [comment]
@ryanbrue @EvilPT manual check is kind of exists, just click on underline version number and you will see a releases page (showing if there i a new release) :)

**Comment by ryanbrue** [comment]
> @ryanbrue @EvilPT manual check is kind of exists, just click on underline version number and you will see a releases page (showing if there i a new release) :)

Could the button maybe have the same functionality as the automatic check and tell people if there is an update? If there isn't an update available maybe then it takes you to the github. Just thinking out loud, there might be a better solution out there.

**Comment by ryanbrue** [comment]
I respectfully disagree with the approach used for this issue, but I don't really feel like making a PR of my own :)
