### ISSUE TITLE
Allow custom power limits configuration based on the power input

### ISSUE THREAD

**Issue by lucas-zimerman** [seerge/g-helper#619]
The idea is to allow the "Fans and power" configuration to have custom values based on the given power input (AC/Battery/USBC or just AC/Other)

The goal is to set different values based on the given power source, I would like to have more power to the cpu/gpu when AC is on but at the same time I want to set a lower profile when Battery/USBC is used.

My main issue that made me ask for this change is that when I am using USBC with 100 Watts, the device also uses the battery to help the system have enough power to operate, I would like it to only use the usbc power. So a lower energy mode of silent mode would be helpful in this case where a normal silent mode is enough for ac mode

**Comment by seerge** [comment]
@lucas-zimerman hello, in latest few releases you can create as many custom profiles as you want https://github.com/seerge/g-helper/releases , it should solve your problem :)
