### ISSUE TITLE
Add choiche if reboot or shutdown when enabling or disabling dGPU

### ISSUE THREAD

**Issue by ramius86** [seerge/g-helper#620]
Right now when you change mode from ultimate to eco, it requires a system reboot.
A lot of time I just need to change mode for the next startup   ( working or gaming from home and next day I've to use it on the move and with battery )so I just have to wait for the system to reboot to shutdown it again.
If you can add the ability to let me choose if I just want to reboot or shutdown the device would be a time saver

**Comment by seerge** [comment]
I'm not sure if system will remember that (cause it could be cold boot, and it could reset to standard as it happens with eco-switch on some devices).

For your specific use case : it shows a small windows-own popup (about system reboot) with a cancel button. You can click cancel. As on that stage app has already sent an "ultimate" command in bios. And then power-off normally.

**Comment by ramius86** [comment]
> I'm not sure if system will remember that (cause it could be cold boot, and it could reset to standard as it happens with eco-switch on some devices).
> 
> For your specific use case : it shows a small windows-own popup (about system reboot) with a cancel button. You can click cancel. As on that stage app has already sent an "ultimate" command in bios. And then power-off normally.

I dont understand exactly, if I click on the cancel button and abort the restart and shutdown windows normally it will remember my choice on the next boot but if you let the user decide to shutdown or reboot when you switch the modes it won't remember?

Btw if I can simply abort the reboot and do this way, it will work anyway, thanks a lot for your work !

**Comment by seerge** [comment]
@ramius86 i have explained reason why I don't want to make it a option for other users (it may not work, even tho most probably it will).

But offered a (unofficial) "workaround" for you :)
