### ISSUE TITLE
Screen auto-rotate and tablet mode on flow series laptops

### ISSUE THREAD

**Issue by 444945** [seerge/g-helper#621]
After getting rid of all the asus services and software, everything works perfectly except the auto-rotate screen features and tablet mode when screen is folded, like with the asus services. Would appreciate if this got implemented as it is a fairly important feature imo, and being able to utilize it without any asus bloatware would be amazing.

**Comment by seerge** [comment]
@444945 I'm not aware if it's asus services rotate a screen, most probably windows does it by itself.

**Comment by 444945** [comment]
close

**Comment by 444945** [comment]
closed
