### ISSUE TITLE
The application will be vertically centered on the screen after reboot

### ISSUE THREAD

**Issue by kuonji-arisu** [seerge/g-helper#623]
![image](https://github.com/seerge/g-helper/assets/29818319/ff0f16bc-004b-4a0c-9f97-5e0ee4a08bd9)
This problem only appeared after updating to v0.85 (but the app shows 0.84)

**Comment by seerge** [comment]
If you close / open window (from tray icon / m4) does it appear correctly ?

**Comment by marcelomijas** [comment]
Also, another problem related to UI. Naming custom profiles is a little bit off on Windows 10:

![imagen](https://github.com/seerge/g-helper/assets/62946623/a69051ee-e190-4514-a649-70aa8bdb1595)

**Comment by kuonji-arisu** [comment]
> @kuonji-arisu If you close / open window (from tray icon / m4) does it appear correctly ?

This problem only occurs when opening for the first time after system startup

**Comment by kuonji-arisu** [comment]
> @kuonji-arisu @marcelomijas can you check if this build fixes location / mode dropdown size ?
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/11747582/GHelper.zip)

fixed, thank you

**Comment by marcelomijas** [comment]
@seerge location is solved, but mode dropdown size still bad

![imagen](https://github.com/seerge/g-helper/assets/62946623/5649fc96-8231-45fc-bd90-1e7b38877b42)

**Comment by seerge** [comment]
@marcelomijas is a combobox for cpu boost looking ok on win10? as i literally copy-pasted it

**Comment by marcelomijas** [comment]
> @marcelomijas is a combobox for cpu boost looking ok on win10? as i literally copy-pasted it

Yeah, it is perfect

![imagen](https://github.com/seerge/g-helper/assets/62946623/8e66bc99-1848-4112-aa1b-ad021bc010c0)

**Comment by seerge** [comment]
@marcelomijas but on this screenshot mode dropdown is also looking good? :|

**Comment by marcelomijas** [comment]
> @marcelomijas but on this screenshot mode dropdown is also looking good? :|

Yes, the problem is when I edit the text (naming) the custom profile

**Comment by seerge** [comment]
@marcelomijas i see now, but when i set correct size for 100% scaling, so editing looks ok there - it gets broken on 200% scaling : 
[GHelper.zip](https://github.com/seerge/g-helper/files/11750182/GHelper.zip)

So ... cheers to windows as usual :( 

![Screenshot 2023-06-14 221550](https://github.com/seerge/g-helper/assets/5920850/e1342f20-48a5-41c5-a2e2-c23abc41ef49)

**Comment by marcelomijas** [comment]
@seerge Oh, I see... Thanks anyways

I didn't bring up this before because is something that doesn't bother me too much and thinked that it has to do with Windows... So, no problem if it looks a little bit bad.

![imagen](https://github.com/seerge/g-helper/assets/62946623/8442aa53-dbdc-4ea9-81cb-0853dd0330eb)
