### ISSUE TITLE
Unable to start G-helper - Links to MS Store

### ISSUE THREAD

**Issue by solidfyre** [seerge/g-helper#625]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
Unable to start app.

**Clear scenario to Reproduce**
1. Trying to start app for the first time.

**Expected behavior**
App to start.

**App Logs**
N/A

**Screenshots or screencasts**
It prompts about something needed from the store, but just links to a broken page so I cannot figure out what.
![1](https://github.com/seerge/g-helper/assets/129062438/cee101f8-8536-49ad-aa82-a80a70456941)
![2](https://github.com/seerge/g-helper/assets/129062438/23c54c84-adfb-4894-87e2-21415928578a)

**Desktop (please complete the following information):**
Windows 11, Latest (10.0.22621 Build 22621)
Zephyrus M16 GU604VZ (2023)

**Asus software**
- Armoury crate (or it's services installed) - No
- MyASUS installed - No
- ASUSSystemControlInterfaceV3 is installed
- The following services are disabled because of me troubleshooting high DPC latency crackles/pops and system interrupts on this model. Seems one or more of these are related to my issues. Any of these need to be running for G-helper to work?
![image](https://github.com/seerge/g-helper/assets/129062438/4f70862f-3e9f-4fcc-8948-c991d3d8e155)

- Also have these installed
![image](https://github.com/seerge/g-helper/assets/129062438/f895111e-0f85-475b-855a-ad30e5c423d5)

**Additional context**
Have installed the .Net7 SDK (I guess only runtime should be required and not the whole SDK package?)

**Comment by solidfyre** [comment]
I managed to fix it using step 2 in this guide if someone else has the same error:
https://ugetfix.com/ask/how-to-fix-search-for-app-in-the-store-error-on-windows/

Aparently SmartScreen handles unsigned things differently nowadays.

**Comment by seerge** [comment]
@solidfyre. It's your windows acting. There is easier way, just right click on exe -> properties -> check Unblock

![Screenshot 2023-06-14 233846](https://github.com/seerge/g-helper/assets/5920850/ac477213-b1c7-4f24-a352-b32617d95dc1)
