### ISSUE TITLE
Can't modify Windows Power Profile when app is running

### ISSUE THREAD

**Issue by Aashishkebab** [seerge/g-helper#626]
**Is your feature request related to a problem? Please describe.**
The Armoury Crate app has a mode for the CPU that lets Windows do its thing. G-Helper does not, and I cannot use Windows power profiles when this app is running.
Why would I want to? Well.
1. My default power profile limits CPU max speed to 99% when on battery. This prevents the CPU from going over base frequency on battery, which helps preserve battery life.
2. I have a second power profile that limits the CPU speed to 37%. I have an app called Power Scheme Switcher that automatically activates this power profile when the battery dips below 30%.

**Describe the solution you'd like**
Add a "Windows" mode like in Armoury crate, or have a way to disable Performance Mode altogether as I don't really need it. With Universal x86 Tuning Utility, Power Scheme Switcher, and Windows power profiles, it works better without this interference. In fact, changing the Performance Mode interferes with the temperature limits I set in Universal Tuning Utility (where I increase the limit from 95 to 100). So an allowance to change the temperature limits for each mode would be nice as well.

**Describe alternatives you've considered**
Armoury Crate. But it's basically malware.
Also, if G-Helper could schedule based on battery level, this would also solve my issue. Actually, it would be much cooler if I could schedule Balanced on battery, but then Silent when under 30% battery. This would completely eliminate my need for using Windows power profiles.
However, I know this solution would take a lot more work.

**Additional context**
The power limit set by G-Helper on Turbo seems to be much higher than the one set by Armoury Crate. This is desireable actually, as Armoury Crate sets a hard limit at 45 W. I also like that it isn't interfering with my Curve Optimizer setting (Armoury Crate appeared to).

I also really like the refresh rate auto-switch, as Armoury Crate didn't have that option.

### Summary

- The ability to set the temperature for each Performance Mode would be nice.
- Battery percentage-based scheduler for Performance Mode would be amazing, but barring that...
- Allow disabling Performance Mode entirely OR
- Have a fourth mode that lets Windows do its thing

**Comment by seerge** [comment]
@Aashishkebab "Windows" mode in Armoury just selects "Balanced" power plan in system (and medium performance in bios).  G-Helper just uses current power plan (i.e. "balanced" as well). So it's already the case.

If you want to use different (custom made) power plans for each mode - you can also set them via config https://github.com/seerge/g-helper#custom-windows-power-plans-with-each-mode

So everything that you ask already exists

**Comment by Aashishkebab** [comment]
> So everything that you ask already exists

Maybe I didn't communicate well, but this isn't the case.

G-Helper **locks** the power profile, so I can't change it even manually.

I have another app that automatically switches power profile at a specific battery percentage, and G-Helper prevents it from functioning. Every time I try to change the power profile in Windows, it reverts back.

G-Helper cannot do any of the four bullet points of feature requests. I can't customize the CPU temperature limit (to go above 95), there is no percentage-based scheduler, I can't disable the Performance Mode feature, and there is no Windows mode that doesn't **lock** the profile.

**Comment by seerge** [comment]
@Aashishkebab 

>G-Helper locks the power plan, so I can't change it even manually.

That is simply not true. Unless you set manual power plan GUIDs in config (which is not your case as I understand) g-helper doesn't "lock" or even change power plan anyhow. It will stay on whatever power plan you have selected in control panel (i recommend balanced tho)

> I can't customize the CPU temperature limit (to go above 95), 
G-helper uses only asus own endpoints (in their driver/bios) to set settings. There is no such that sets throttle temp (same as AC can't do that neither)

> I can't disable the Performance Mode feature, and there is no Windows mode that doesn't lock the plan.
What is "disable performance mode" ? Performance mode is set in bios, and it's always one of three (silent/balanced/turbo). It has nothing to do with power plan.

**Comment by seerge** [comment]
> I am able to change this inside Universal x86 Tuning Utility. However, G-Helper will revert it when switching:

Correct, asus bios when sets one of 3 predefined modes (the ones g-helper or armoury would offer), would reset all your customizations. That's how the things are (also for armoury). You can apply temp limit after using UXTU. This is

> The ability to schedule based on battery percentage would still be nice (ie. Silent when below 30%, Balanced when above, and Turbo when plugged in). 

Silent vs Balanced won't save you much battery. But windows "battery saver" will. And you can literally configure it to kick on on any battery % 

![Screenshot 2023-06-15 210706](https://github.com/seerge/g-helper/assets/5920850/e66ee7a6-14b9-4c87-a9a7-168e74c8f6d1)

**Comment by seerge** [comment]
@Aashishkebab you can try this build for temp limit (under advanced)
[GHelper.zip](https://github.com/seerge/g-helper/files/11781545/GHelper.zip)

As for automatic mode switching based on charge, it's way too much and will create a lot of confusion. Also your strict power limits (like 7w) will save you battery ONLY if you have very heavy running that takes more than 7W in total (which should not be the case for a regular desktop use)

**Comment by Aashishkebab** [comment]
> @Aashishkebab you can try this build for temp limit (under advanced)
> [GHelper.zip](https://github.com/seerge/g-helper/files/11781545/GHelper.zip)
> 
> As for automatic mode switching based on charge, it's way too much and will create a lot of confusion. Also your strict power limits (like 7w) will save you battery ONLY if you have very heavy running that takes more than 7W in total (which should not be the case for a regular desktop use)
> 

Thanks for that! I'll check it out.

When I monitor my CPU, it _regularly_ uses well over 7w. If I don't power limit, it'll frequently jump up to 25w just from opening apps (especially if you remove the Maximum Frequency in Windows Power Plan) and is usually 10w to 15w during normal usage. The TDP of the chip is 35w (6900HS).

So respectfully, I strongly disagree with that last point. The laptop is noticeably much slower at 7w. The package idles at about 5w actually (the wattage limit also includes the iGPU).

However I'm not saying that you have to create the feature or anything, it was just a request and I appreciate the temp feature.

**Comment by seerge** [comment]
@Aashishkebab if it's idling with more than 7W, then it's something not ok with your system (i.e. too much stuff running).

But if it takes 25w for actual needed tasks, with 7W it will just take more time to complete them (resulting in a very comparable battery usage anyway) :)

**Comment by Aashishkebab** [comment]
Hello,

It idles 5w - 7w when nothing is happening and seven of the cores are parked and CPU usage is less than 2%. I'm not sure where you've seen a CPU idle less than that, because that's actually really low and really good for a CPU, _especially_ one with integrated graphics. There's a minimal amount of power it has to draw or it would shut off, since the registers and cache need power to store data.

Also, power consumption is exponential. 2 GHz uses four times as much power as 1 GHz. So it might complete the task twice as fast but use four times as much power, so the inefficiency is double. That's why processors scale frequencies in the first place and try to stay at lower frequencies.

Technically you can just limit the maximum frequency to also achieve the power limit (which is what I've done in Windows Power Plan), but it comes at a cost to user experience since when only one core is active it still can't boost to the set PPT.

This is fine with me, like I said I've been doing it this way for years anyway, since this will only happen when I'm on low battery, which will be rare.

I've done very extensive testing on stuff like this and I also have an engineering degree and have designed my own mini microprocessor before.

Like I said though, I appreciate you looking into the temp setting because now I won't have to run Universal Tuning Utility in the background (it has a setting to re-apply settings every certain number of seconds, but that uses battery and is unideal) so thanks for implementing.

One thing though: It seems the maximum is at 97. Can you raise the maximum to 100 or 105?
I also like the undervolting!

**Comment by Aashishkebab** [comment]
After the latest update, the maximum temperature is still 98 but also GHelper thinks 98 is the default (which is wrong). At least, that's what is implied by the slider.

Is there any way this limit can be upped to 100 C?
