### ISSUE TITLE
Ghelper V0.86 not working on startup

### ISSUE THREAD

**Issue by Nickthebroiler** [seerge/g-helper#630]
**Expected behavior**
It used to open on startup with no issue and now I won't unless I manually start the program. I tried uninstalling and reinstalling as well as making my own task scheduler for the program.

**App [Logs**]
[log.txt](https://github.com/seerge/g-helper/files/11758620/log.txt)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Zephyrus g14 2022 RTX6700s model.

**Asus software**
Uninstalled the software such as MyAsus and armourycrate

**Comment by seerge** [comment]
@Nickthebroiler hello, i didn't change anything that could cause that in 0.86 honestly.

1. Uncheck / check "run on startup" checkbox in the app, it will re-create a startup task (pointing to your current exe location)

If it doesn't help

2. Check windows Event viewer for possible crashes (as explained https://github.com/seerge/g-helper#app-crash-or-doesnt-work-properly-what-should-i-do- )

**Comment by seerge** [comment]
@Nickthebroiler it's most probably startup task is pointing to other location. Try to manually delete G-helper task from windows -> Task Scheduler . And then schedule it via app again normally

**Comment by Nickthebroiler** [comment]
> @Nickthebroiler it's most probably startup task is pointing to other location. Try to manually delete G-helper task from windows -> Task Scheduler . And then schedule it via app again normally

Worked! Thank you so much for all that you do! @seerge
