### ISSUE TITLE
[Request] Custom Temperature limits

### ISSUE THREAD

**Issue by OneWayGamer** [seerge/g-helper#632]
The system seems to shutdown randomly whenever the CPU temps go to 96 Degrees Celsius.

Now there is a simple solution to this and that is to disable CPU boost mode but it heavily impacts the performance in certain games.

So having the option to set the max temp before the system starts throttling to 94 or 95 degrees Celsius would be a really nice solution to this problem!

**Comment by manciuszz** [comment]
Have you tried using ThrottleStop ?

**Comment by seerge** [comment]
@OneWayGamer try this build (works only for AMD)
[WinRing0x64.zip](https://github.com/seerge/g-helper/files/11781531/WinRing0x64.zip)

**Comment by nbeh1** [comment]
Doesn't seemed to work on my G15 with 6800hs, temps still goes to 93 after limiting it to 80

There seems to be some issues when applying the limit?
[log.txt](https://github.com/seerge/g-helper/files/12136234/log.txt)

**Comment by seerge** [comment]
@nbeh1 make sure you have winring0 files (from g-helper's zip) in a same folder as exe, and then restart app (as admin).

**Comment by nbeh1** [comment]
> @nbeh1 make sure you have winring0 files (from g-helper's zip) in a same folder as exe, and then restart app (as admin).

It worked! Thanks

**Comment by phu54321** [comment]
Hello, did this go to the master? I don't really wanna use the old version.

**Comment by seerge** [comment]
@phu54321 you can set it as a parameter in config https://github.com/seerge/g-helper/wiki/Power-user-settings#custm-cpu-temp-limit :)
