### ISSUE TITLE
Release v0.86 detected as virus

### ISSUE THREAD

**Issue by tjames192** [seerge/g-helper#636]
Release v0.86 detected as virus.
A change from v0.85 to v0.86 is now being detected as virus.

**Comment by seerge** [comment]
@tjames192 

> Windows defender marks app download as malware / virus
False positives from Windows Defender (or any other similar system that uses machine learning for detection) is possible as application is not digitally signed with a certificate. You can always download a version below or compile app by yourself. All application sources are open and can be monitored from A to Z :)

https://github.com/seerge/g-helper#windows-defender-marks-app-download-as-malware--virus
