### ISSUE TITLE
Fan And Power window is overflow.

### ISSUE THREAD

**Issue by pengweiqhca** [seerge/g-helper#637]
![Weixin Screenshot_20230617073206](https://github.com/seerge/g-helper/assets/3982826/e5cf1665-115e-45c8-9d33-c7aef1934d62)

**Comment by seerge** [comment]
@pengweiqhca this build should fix it https://github.com/seerge/g-helper/files/11776144/GHelper.zip i'm separating CPU / GPU / Advanced sections in tabs
