### ISSUE TITLE
Bind custom windows power plans button

### ISSUE THREAD

**Issue by manciuszz** [seerge/g-helper#638]
Now that we have custom profiles, I think it would be nice to have an extra button near the dropdown menu that would allow us to bind custom windows power plans for each mode. This would remove the need for manual **config.json** edits, which in turn would result in less application closes and less human error that might result in a random crash due to a missing comma or something xD

![image](https://github.com/seerge/g-helper/assets/2539661/e628e1e4-6b3c-4cbb-9e3b-39428628c90c)

**Comment by seerge** [comment]
@manciuszz i don't think that's a good idea. It's a very specific feature, that will only cause extra user questions and human error :)
