### ISSUE TITLE
Crash after switching display refresh rate

### ISSUE THREAD

**Issue by t0mka14** [seerge/g-helper#639]
Hii,
I have a problem with switching to 120 Hz OD mode. When I switch to 120 Hz mode, the screen flickers, then goes black and laptop restarts. The laptop is GA503RM, Windows 10, no ASUS software installed. The problem happens every time. Did anyone else run into this issue? I think the problem was not present when I was using the Armoury Crate after the laptop was bought, but the driver configuration could have changed since that, etc.. The log should be attached, you can see two tries to switch the display and then the G-helper restart, but otherwise i think there is not much helpful info :X.
Thx for looking into this!

[log.txt](https://github.com/seerge/g-helper/files/11778674/log.txt)

**Comment by seerge** [comment]
@t0mka14 hello, I don't see any failed attempts  to set 120Hz, all of them succeded
```
6/17/2023 1:03:14 PM: Screen = 120Hz : OK
```

If you have asus smart display control installed (and running) please uninstall it. As it interferes and tries to do the same.

**Comment by t0mka14** [comment]
Hi,
thanx for the reply :) I have no asus service running. For me it looks like the screen switches, but after 1 second the laptop crashes. Maybe a problem with some drivers?

**Comment by seerge** [comment]
@t0mka14 it's not a service, it's an app ( you can reach it from add or remove programs or just see if process is running)

Try to disable auto-refresh rate switches (i.e. set fixed 120Hz). And see if problem persists.

As for your crashes, check in windows Event Viewer

**Comment by t0mka14** [comment]
@seerge yes, sorry I didnt explain it properly, i have no ASUS processes in task manager and i disabled all the service through debloat.bat and I see 0 running in G-Helper, switching to just 120 hz does the same thing. As for the system logs, there is a Kernel-Power error roughly at the same time of switching the mode. I copied the xml to attached txt. Interestingly though, i can se no bluescreen, but that could be it just doesnt get displayed, because it takes some time before i can see boot animation after the crash. I will check the minidump, to see if there is somethig and will let you know. I will also try installing all Asus stuff back to see if the switching works, and is maybe hardware or driver related...uff really didnt want to do that 🗡️ 

To other fellow GA503 owners, is there someone who has just G-Helper (no other asus service/process stuff) and the screen switching works for them? Thx :)

[trace.txt](https://github.com/seerge/g-helper/files/11778746/trace.txt)

**Comment by seerge** [comment]
@t0mka14 try to change refresh rate in windows itself, does it also crash?

**Comment by t0mka14** [comment]
@seerge it does indeed

**Comment by seerge** [comment]
@t0mka14 then g-helper can't do anything with this :) Check what's wrong with your drivers / system / etc.
