### ISSUE TITLE
[Bug] "Set Eco on battery and Standard when plugged" checkbox not sticking

### ISSUE THREAD

**Issue by JonoYang** [seerge/g-helper#64]
I am using G-Helper v 0.22 on the Zephyrus G14 2021 running Windows 10 and the "Set Eco on battery and Standard when plugged" checkbox does not work. When I check the box, the unplug my laptop, the GPU mode does not change. When I exit G-Helper and launch it again, the checkbox is unchecked again. I tried a previous version, but the GPU switching mode still does not work.

**Comment by JonoYang** [comment]
Not sure what I did, but the checkbox started working again after I tried v0.15 and checking the box using that.

**Comment by seerge** [comment]
Actually you were right, when reorganizing UI somewhere in 0.19 or 0.20 or so, visual studio have removed an action from GPU checkbox - so it stopped saving it's sate :) I have fixed it in 0.22

**Comment by JonoYang** [comment]
@seerge I downloaded v0.22 again and checking the "Set Eco on battery and Standard when plugged" checkbox seems to work and persist. Thanks for the quick response!
