### ISSUE TITLE
Unable to see gpu modes. 

### ISSUE THREAD

**Issue by jinko690** [seerge/g-helper#640]
Hey Seerge, thanks for your good work. 
I am unable to see gpu modes in the app. Any idea on what might be the issue here?

Win11, asus zephyrus g14 2020. 

![image](https://github.com/seerge/g-helper/assets/93494785/60db8720-7ee6-45ba-b171-8a0332e87782)

**Comment by seerge** [comment]
@jinko690 it's already answered in FAQ https://github.com/seerge/g-helper#i-dont-see-gpu-modes-section

**Comment by jinko690** [comment]
@seerge Thanks Seerge.
