### ISSUE TITLE
[Bug] Apply power limits, clipped text

### ISSUE THREAD

**Issue by marcelomijas** [seerge/g-helper#641]
**Describe the bug**
In v0.87, the text of "Apply power limits", which translates to "Aplicar límites de energía" in Spanish is clipped.

**Clear scenario to Reproduce**
Set Spanish as System language.
1. Open G-Helper.
2. Open "Ventiladores + Energía" window.

**Expected behavior**
The text should not be clipped, there is enough space. Like in v0.86.

**App Logs**
```
17/06/2023 18:46:35: ------------
17/06/2023 18:46:35: App launched: ROG Zephyrus G14 GA401IV_GA401IV :0.87.0.0es-ES
17/06/2023 18:46:35: NVIDIA GeForce RTX 2060 with Max-Q Design
17/06/2023 18:46:37: CPU: 3 - AMD Ryzen 7 4800HS with Radeon Graphics          - AMD64 Family 23 Model 96 Stepping 1
17/06/2023 18:46:37: AutoSetting for Online
17/06/2023 18:46:37: Input: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&3397f86&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
17/06/2023 18:46:37: BatteryLimit = 60 : OK
17/06/2023 18:46:37: BatteryLimit = 60 : OK
17/06/2023 18:46:37: Mode = 0 : OK
17/06/2023 18:46:37: GET GPU CLOCKS: 0, 0
17/06/2023 18:46:37: FanCPU = 14-1E-32-3C-49-50-59-64-00-00-09-18-1F-28-36-3D : OK
17/06/2023 18:46:37: FanGPU = 14-1D-32-3B-48-4C-51-64-01-01-09-10-10-22-34-3E : OK
17/06/2023 18:46:37: Eco flag : -65536
17/06/2023 18:46:37: Mux flag : -65536
17/06/2023 18:46:37: Screen = 120Hz : OK
17/06/2023 18:46:37: ScreenOverdrive = 0 : 0
17/06/2023 18:46:37: Auto:5D-BA-C5-C4-01
17/06/2023 18:46:37: Monitor Power On
```

**Screenshots or screencasts**
Screenshot of v0.87
![imagen](https://github.com/seerge/g-helper/assets/62946623/ceb1d903-745c-4863-a84b-371a5a574df9)

Screenshot of v0.86
![imagen](https://github.com/seerge/g-helper/assets/62946623/26e762ed-db76-489e-90a2-b011cd284746)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Laptop model: G14 GA401IV

**Asus software**
- None

**Comment by seerge** [comment]
@marcelomijas hello, this build should fix it :) thanks for spotting
[GHelper.zip](https://github.com/seerge/g-helper/files/11780141/GHelper.zip)
