### ISSUE TITLE
[Feature request] Unit of measurement in undervolting tab

### ISSUE THREAD

**Issue by marcelomijas** [seerge/g-helper#642]
**Is your feature request related to a problem? Please describe.**
Not exactly. Since v0.87, users of AMD systems have the option of CPU and iGPU undervolting. For users that are not very familiar with undervolting (like me), we don't know what the numbers represents. It is volts? Mili-volts? What?

**Describe the solution you'd like**
I would propose a measurement unit next to the number like in the GPU overclocking section, that tells the user what is it changing. In the case of the GPU overclocking, the MHz, in this case... the volts, mili-volts or whatever.

![imagen](https://github.com/seerge/g-helper/assets/62946623/c00c32eb-b612-4d53-b8e1-f8da36a75948)

**Comment by seerge** [comment]
@marcelomijas since it's not really documented way to set undervolting, i'm not 100% sure if 1 unit = 1mv (or multiple milivolts). That's why I have left it unmarked :)

**Comment by marcelomijas** [comment]
> @marcelomijas since it's not really documented way to set undervolting, i'm not 100% sure if 1 unit = 1mv (or multiple milivolts). That's why I have left it unmarked :)

@seerge Oh, I understand... no problem then. I will try to look for confirming clues and inform you if I encounter some findings.
 
> P.S. on a sidenote, since it's already using winring.dll , i can add CPU power limits for old devices that don't support setting them via AC endpoints. Is it something important for G14 2020 ?

If CPU power limits for old devices could be a thing, it would be awesome! I'm interested :) and I am aware of the poll results...

Also, one more thing. If I could ask... Where did you learn to program in C++? I'm interested on learning...

**Comment by seerge** [comment]
@marcelomijas I learned c# just on the go along using modern windows itself (like 4 months ago when i purchased this laptop and decided to do this utility). Google / stackoverflow / chatgpt should be enough to get basics if you generally understand how to program :)

**Comment by marcelomijas** [comment]
@seerge Oh, thanks for the info, I learned other languages (and also work as a Python programmer) but not C# since I thought it was very difficult and a course was mandatory, but I guess that all is on the Internet, we only have to look on the right places. I will give it a try, maybe I can help more in the project. :)

**Comment by seerge** [comment]
@marcelomijas hello, can you try this build it should 

1. Show a CPU power limit slider in fans+power
2. Set power limits if "apply power limits" is selected affecting STAMP / SLOW / FAST limits all together (i'm not sure, if you need them separated?)

Limits will work only if app runs as admin atm :) 

[GHelper.zip](https://github.com/seerge/g-helper/files/11833648/GHelper.zip)

**Comment by marcelomijas** [comment]
@seerge I could not try power limits properly. When I mark the apply power limits box (whatever the value, even at 150W) the computer becomes very very slow, while not even exceeding 10W of consumption.

```
22/06/2023 14:42:11: ------------
22/06/2023 14:42:11: App launched: ROG Zephyrus G14 GA401IV_GA401IV :0.89.0.0es-ES.
22/06/2023 14:42:12: NVIDIA GeForce RTX 2060 with Max-Q Design
22/06/2023 14:42:13: CPU: 3 - AMD Ryzen 7 4800HS with Radeon Graphics          - AMD64 Family 23 Model 96 Stepping 1
22/06/2023 14:42:13: AutoSetting for Online
22/06/2023 14:42:13: Input: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&3397f86&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
22/06/2023 14:42:13: Mode = 0 : OK
22/06/2023 14:42:13: Eco flag : -65536
22/06/2023 14:42:13: Mux flag : -65536
22/06/2023 14:42:13: Auto:5D-BA-C5-C4-01
22/06/2023 14:42:13: GET GPU CLOCKS: 0, 0
22/06/2023 14:42:14: UV: 0 OK
22/06/2023 14:42:14: iGPU UV: 0 CMD_REJECTED_PREREQ
22/06/2023 14:42:14: CPU Temp: 90 OK
22/06/2023 14:42:14: APU Temp: 90 OK
22/06/2023 14:42:14: Monitor Power On
22/06/2023 14:42:25: Mode = 0 : OK
22/06/2023 14:42:25: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
22/06/2023 14:42:38: Mode = 0 : OK
22/06/2023 14:42:38: GET GPU CLOCKS: 0, 0
22/06/2023 14:42:41: Mode = 0 : OK
22/06/2023 14:42:41: GET GPU CLOCKS: 0, 0
22/06/2023 14:42:54: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
22/06/2023 14:43:03: Mode = 0 : OK
22/06/2023 14:43:03: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
22/06/2023 14:43:05: Mode = 0 : OK
22/06/2023 14:43:05: GET GPU CLOCKS: 0, 0
```

**Comment by marcelomijas** [comment]
@seerge perfectly working now! :)

But there is another problem, not very important but... Now that the wattage is displayed next to the mode, the corresponding fan labels are cropped when RPM are displayed instead of Cº

![imagen](https://github.com/seerge/g-helper/assets/62946623/8eb2b299-674a-4974-b064-7d546708f21d)

**Comment by seerge** [comment]
I just need to rename modo de rendimiento to "modo" (as i did in other languages)

I'm still not sure if it sholuld be 3 separate sliders for power, or just 1, as main purpose of this limits is taming CPU (for heat / battery / etc), right ?

**Comment by seerge** [comment]
@marcelomijas this build should have correct label, and also ask for admin rights when needed (so you can try to start app normally)
[GHelper.zip](https://github.com/seerge/g-helper/files/11834648/GHelper.zip)

**Comment by marcelomijas** [comment]
> @marcelomijas this build should have correct label, and also ask for admin rights when needed (so you can try to start app normally) [GHelper.zip](https://github.com/seerge/g-helper/files/11834648/GHelper.zip)

@seerge Perfect!

**Comment by seerge** [comment]
@marcelomijas does admin elevating works correctly for you ? (it should auto-apply settings when app re-starts as admin)

**Comment by seerge** [comment]
Ok, great, it's live as 0.90 then

**Comment by seerge** [comment]
@MDowski btw, you with your 2020 model will also benefit from new power limits in v0.90 :)

**Comment by MDowski** [comment]
I had to stick to the Armoury Crate, because I've got ROG mouse and I had to configure it. Thankfully, once set up, this mouse holds settings in its memory. I can't wait to test those power limits. :)

**Comment by seerge** [comment]
@marcelomijas I have something else for you to test, a button that kills all processes using GPU (with intention to help it go into sleeping, but that's obviously not guaranteed in windows)

[GHelper.zip](https://github.com/seerge/g-helper/files/11856403/GHelper.zip)

**Comment by marcelomijas** [comment]
@seerge It tries to kill the process, but it doesn't work. For example, I tested it with OBS, clearly, the Stop button does something, since in task manager I see a valley. I pushed the button twice (you can see the two valleys), but the app stayed open. 

![imagen](https://github.com/seerge/g-helper/assets/62946623/88d3ca65-7a6c-4b21-8134-6119f53175e2)

Also, tried with emulators like yuzu (Nintendo Switch) that uses the dGPU and obtained the same result.

I think it's important to say that I explicitly selected to use the dGPU on those programs on the NVIDIA control panel.

**Comment by seerge** [comment]
@marcelomijas can you check log? it writes what it tries to kill there

**Comment by marcelomijas** [comment]
Tried again with OBS opened. It tries to stop Radeon Software 0_0. I searched for Radeon Software in task manager, and it shows 0% of dGPU usage. Here's the log:

```
24/06/2023 15:42:45: ------------
24/06/2023 15:42:45: App launched: ROG Zephyrus G14 GA401IV_GA401IV :0.91.0.0es-ES
24/06/2023 15:42:45: NVIDIA GeForce RTX 2060 with Max-Q Design
24/06/2023 15:42:46: CPU: 3 - AMD Ryzen 7 4800HS with Radeon Graphics          - AMD64 Family 23 Model 96 Stepping 1
24/06/2023 15:42:46: AutoSetting for Online
24/06/2023 15:42:46: Input: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&3397f86&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
24/06/2023 15:42:46: BatteryLimit = 60 : OK
24/06/2023 15:42:46: BatteryLimit = 60 : OK
24/06/2023 15:42:46: Mode = 0 : OK
24/06/2023 15:42:46: GET GPU CLOCKS: 0, 0
24/06/2023 15:42:46: FanCPU = 14-1E-32-3C-49-50-59-64-00-00-09-18-1F-28-36-3D : OK
24/06/2023 15:42:46: FanGPU = 14-1D-32-3B-48-4C-51-64-01-01-09-10-10-22-34-3E : OK
24/06/2023 15:42:46: Eco flag : -65536
24/06/2023 15:42:46: Mux flag : -65536
24/06/2023 15:42:46: Screen = 120Hz : -2
24/06/2023 15:42:46: Screen = 120Hz : -2
24/06/2023 15:42:46: ScreenOverdrive = 0 : 0
24/06/2023 15:42:46: Auto:5D-BA-C5-C4-01
24/06/2023 15:42:47: Monitor Power On
24/06/2023 15:42:53: Stopped: RadeonSoftware
```

**Comment by seerge** [comment]
@marcelomijas can you try this build instead ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/11857143/GHelper.zip)

**Comment by marcelomijas** [comment]
@seerge perfectly working in this build. Here's the log :)

```
24/06/2023 15:57:37: ------------
24/06/2023 15:57:37: App launched: ROG Zephyrus G14 GA401IV_GA401IV :0.91.0.0es-ES.
24/06/2023 15:57:37: NVIDIA GeForce RTX 2060 with Max-Q Design
24/06/2023 15:57:38: CPU: 3 - AMD Ryzen 7 4800HS with Radeon Graphics          - AMD64 Family 23 Model 96 Stepping 1
24/06/2023 15:57:38: AutoSetting for Online
24/06/2023 15:57:38: Input: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&3397f86&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
24/06/2023 15:57:38: BatteryLimit = 60 : OK
24/06/2023 15:57:38: BatteryLimit = 60 : OK
24/06/2023 15:57:38: Mode = 0 : OK
24/06/2023 15:57:38: GET GPU CLOCKS: 0, 0
24/06/2023 15:57:38: FanCPU = 14-1E-32-3C-49-50-59-64-00-00-09-18-1F-28-36-3D : OK
24/06/2023 15:57:38: FanGPU = 14-1D-32-3B-48-4C-51-64-01-01-09-10-10-22-34-3E : OK
24/06/2023 15:57:38: Eco flag : -65536
24/06/2023 15:57:38: Mux flag : -65536
24/06/2023 15:57:39: Screen = 120Hz : -2
24/06/2023 15:57:39: Screen = 120Hz : -2
24/06/2023 15:57:39: ScreenOverdrive = 0 : 0
24/06/2023 15:57:39: Auto:5D-BA-C5-C4-01
24/06/2023 15:57:39: GET GPU CLOCKS: 0, 0
24/06/2023 15:57:39: Monitor Power On
24/06/2023 15:57:40: UV: 0 OK
24/06/2023 15:57:40: iGPU UV: 0 CMD_REJECTED_PREREQ
24/06/2023 15:57:40: CPU Temp: 95 OK
24/06/2023 15:57:40: APU Temp: 95 OK
24/06/2023 15:57:53: Kill:obs64
24/06/2023 15:57:53: Stopped: obs64
24/06/2023 15:58:38: Kill:obs64
24/06/2023 15:58:38: Stopped: obs64
24/06/2023 16:00:11: Kill:yuzu
24/06/2023 16:00:11: Stopped: yuzu
```

**Comment by seerge** [comment]
@marcelomijas great :) i'm not sure if it will really help windows to put GPU asleep tho, but at least this is maximum you can do from software side.
