### ISSUE TITLE
BIOS rejected fan curve

### ISSUE THREAD

**Issue by CasualMassacre** [seerge/g-helper#644]
**Is your feature request related to a problem? Please describe.**
When setting CPU or GPU Fan Profiles, clicking "Apply Custom Fan Curve" results in 'ASUS BIOS rejected fan curve'.

**Describe the solution you'd like**
Are there plans to implement this feature for other ASUS laptop versions?

**Additional context**
I'm running an NVIDIA 3050 and Intel i5 11xx CPU setup. Asus TUF Gaming F17.

**Comment by seerge** [comment]
It’s not supported on your device
