### ISSUE TITLE
THE ETHERNET CONNECTION IS NOT WORKING AFTER WAKE UP

### ISSUE THREAD

**Issue by jozefgocik** [seerge/g-helper#647]
**Describe the bug**
THE ETHERNET CONNECTION IS NOT WORKING 
When I put my laptop into sleep mode and wake it up again, the ethernet connection is not working. Even though the cable is plugged in there's no connection detected and the system shows "No internet access" & "No connections available".

**Clear scenario to Reproduce**
1. Connect to the internet using an Ethernet cable.
2. Unplug the cable. 
3. Close the lid.
4. Wake up the device and plug in the ethernet cable.
5. Ethernet connection shouldn't be available.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11789782/log.txt) from ``%AppData%\GHelper``

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Laptop model: ROG Zephyrus G15 2022 (GA503RM)
 - CPU: AMD Ryzen 7 6800HS
 - GPU: Nvidia RTX 3060

**Asus software**
- Armoury crate is not installed
- MyASUS is installed
- 0 Asus services running in the background

**Comment by seerge** [comment]
@jozefgocik hello, g-helper has nothing to do with your internet connection. You can quit it completely and repeat your scenario again :))

**Comment by seerge** [comment]
Most probably it's something with windows / or some settings. Try to reinstall ethernet adapter driver from asus / etc
