### ISSUE TITLE
Keyboard backlight colors

### ISSUE THREAD

**Issue by simonsolberg** [seerge/g-helper#648]
**Describe the bug**
Laptop keyboard backlight colors doesn't behave as expected. 

When chosing white color and modes Static, Breathing and Strobe - everything works as expected. 

When chosing Static, Breathing and Strobe and any other color than white the color doesn't change. Light colors still light up the keyboard, but a bit dimmer. Dark colors (for example blue) dims the light noticeably / completely. 

Color Cycle and Rainbow doesn't seem to do anything, they behave like Static. 

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[logs.txt](https://github.com/seerge/g-helper/files/11790672/logs.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Laptop model: ROG Zephyrus G14 GA402RK

**Asus software**
No ASUS services running.

**Comment by simonsolberg** [comment]
Norwegian language on the OS. Might be relevant seeing as there is some norwegian text in the logs.

**Comment by seerge** [comment]
@simonsolberg may be your keyboard don't support colors then ? Do colors work in armoury ?

**Comment by simonsolberg** [comment]
They worked in Armoury.

**Comment by seerge** [comment]
@simonsolberg i looked at logs, and i see that you mostly try to set white color FF-FF-FF (it's RGB code)

![Screenshot 2023-06-19 195537](https://github.com/seerge/g-helper/assets/5920850/01790eeb-534c-40fb-97d8-767b8d68b692)

And few times tried to set something else. App sends payload in a known format every time. I honestly don't know why it doesn't work in your case. Do other open source apps (like Open RGB) set colors correctly in your case ?

**Comment by simonsolberg** [comment]
Same behaviour with that build I'm afraid. 

In "Extra" it says "Asus Services Running: 0" at the bottom. 

New log: 
[log.txt](https://github.com/seerge/g-helper/files/11793026/log.txt)

**Comment by seerge** [comment]
@simonsolberg asus services : 0 is only for myasus "package" :) g-helper doesn't monitor armoury stuff (as usually people uninstall AC using own uninstaller and it's all gone)

Try this build, but if this one doesn't work - i'm out of ideas.
[GHelper.zip](https://github.com/seerge/g-helper/files/11793066/GHelper.zip)

Given that GA402RK is pretty much "base" model for g-helper (I have literally same), and thousands users use it, and g-helper controls brightness there - it could be some specific keyboard that you personally have or some other software hiccup causing that.

**Comment by simonsolberg** [comment]
Aha, okey. Well I have uninstalled Armoury aswell. Same behaviour with that build aswell :cry:
[log.txt](https://github.com/seerge/g-helper/files/11793175/log.txt)

Oh well. Thank you for trying.

**Comment by seerge** [comment]
Just out of curiosity - try openRGB app, i wonder if it will manage to set colors (it's the only one open source that i know)

**Comment by simonsolberg** [comment]
@seerge openRGB couldnt do it either. I tried to reinstall Armoury and I can't seem to do it there either. I felt absolutely sure I have seen RGB on my keyboard before, but I must have been wrong. I'm sorry for wasting your time.
