### ISSUE TITLE
[Bug] UI wrong window size in Fans and Power

### ISSUE THREAD

**Issue by marcelomijas** [seerge/g-helper#65]
Every time Windows load, GHelper Fans and Power window size is like this:
![imagen](https://user-images.githubusercontent.com/62946623/224477641-ca301484-151c-4524-98e4-9024fff5756f.png)

I can adjust it (needs to shrink width and move up a little), but after a restart it doesn't remember the size.

Specs: Windows 10 22H2, G14 2020 (Ryzen 7 4800HS and RTX 2060); no PPT settings.

Thanks in advance.

Edit: using built in screen (1920x1080)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/10948246/GHelper.zip)
Can you check if 0.23 fixes it ?

**Comment by marcelomijas** [comment]
No. Is worse... "Factory Default" and "Apply Fan Curve" doesn't appear anymore, the height is still incorrect and now I cannot adjust the window size. But the width is ok now...

![imagen](https://user-images.githubusercontent.com/62946623/224479158-e82ab8a8-411f-41da-8be5-5f223220df7c.png)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/10948295/GHelper.zip)
And this ? 

P.S. I can only send rays of love to native windows visual studio, and all it's UI that simply doesn't look same on windows 10 and 11 ... in 2023!

**Comment by marcelomijas** [comment]
Exactly the same as the last one you gave me.

![imagen](https://user-images.githubusercontent.com/62946623/224479948-a0afbcf6-0476-4d27-b440-805e55ece4cf.png)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/10948315/GHelper.zip)

:( and this one ?

**Comment by marcelomijas** [comment]
The height still not perfect:

![imagen](https://user-images.githubusercontent.com/62946623/224480884-caa0d63b-5a1e-4c89-88c0-b38c91914d9e.png)

But at least when I move the window a little bit up, I have the options back: 

![imagen](https://user-images.githubusercontent.com/62946623/224480914-c588d26a-4e89-4b41-9487-1c0edf0dbeba.png)

**Comment by seerge** [comment]
At least form height is correct, try this - position should be better

[GHelper.zip](https://github.com/seerge/g-helper/files/10948340/GHelper.zip)

**Comment by marcelomijas** [comment]
This last one is worse, back to the problem of no options... And no way of seeing them.

![imagen](https://user-images.githubusercontent.com/62946623/224481417-c69c10aa-4b1b-4657-808d-9c18e5201804.png)

**Comment by seerge** [comment]
Pff, and now ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/10948385/GHelper.zip)

**Comment by marcelomijas** [comment]
Better than the last one, but buttons are chopped (at least can use them) and cannot modify the window size.

![imagen](https://user-images.githubusercontent.com/62946623/224482824-3e4ea9dd-9795-4429-9df5-761952406bf5.png)

**Comment by seerge** [comment]
Can you try this one [GHelper.zip](https://github.com/seerge/g-helper/files/10948423/GHelper.zip)

Crazy how bad windows is it scaling :) like 10 years behind mac os :(

**Comment by marcelomijas** [comment]
Exactly the same as this one:

> This last one is worse, back to the problem of no options... And no way of seeing them.
> 
> ![imagen](https://user-images.githubusercontent.com/62946623/224481417-c69c10aa-4b1b-4657-808d-9c18e5201804.png)

Yeah, windows scaling is very bad (suffered with Tkinter and Python)... also as sleep states, fonts rendering, UI inconsistencies, bloatware, spyware... and Microsoft first priority nowadays is to inyect ChatGPT on Bing and integrating it on Windows 11 (creating a new Bonzi Buddy, v2.0).

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/10948476/GHelper.zip)
another attempt ... i'm just on win11, and literally can't see how it will look on lower scaling and win10 (installing win10 in virtual box in background now)

**Comment by marcelomijas** [comment]
Perfect! You nailed it!

![imagen](https://user-images.githubusercontent.com/62946623/224483851-3fb867ff-5907-4190-a0da-c74096162fd4.png)

**Comment by seerge** [comment]
cool, i just forced charts to scale down, rather window to scale up :D  thanks for testing

**Comment by seerge** [comment]
Pushed it to latest release https://github.com/seerge/g-helper/releases/tag/v0.23
