### ISSUE TITLE
cli commands

### ISSUE THREAD

**Issue by flick0** [seerge/g-helper#652]
**Describe the solution you'd like**
allow interacting with ghelper through cli, similar to asusctl on linux

**Comment by seerge** [comment]
@flick0 hello, it's not that easy to add, as it means app needs to relaunch on each CLI command, which is not how it currently works. It would require creating a service/daemon that actually does things + a separate client.

As I have answered you in discord - for your specific needs (setting backlight settings) it's just easier to replicate quite basic USB commands :)
