### ISSUE TITLE
Undervolting failed on GA402RJ 

### ISSUE THREAD

**Issue by athulkrishnakr** [seerge/g-helper#656]
Tried to undervolt my G14 2022 model, the %appdata%/Roaming/Ghelper/log.txt file shows: UV -5 FAILED, same for the iGPU. I've tried undervolting with 0.87 and 0.89 versions.
[log.txt](https://github.com/seerge/g-helper/files/11802331/log.txt)

**Comment by seerge** [comment]
@athulkrishnakr You have 6800hs model, as i remember someone was reporting that undervolting doesn’t work on them.

Does it work in UXTU for you?

**Comment by seerge** [comment]
check official amd site

https://www.amd.com/en/product/11581

Unlocked for Overclocking - No

Your model don’t support it

6900hs - does support

So there is nothing i can do

**Comment by seerge** [comment]
@athulkrishnakr also do you have AMD chipset drivers or ones from Asus ?

**Comment by athulkrishnakr** [comment]
I think from AMD

**Comment by athulkrishnakr** [comment]
Yep, chipset drivers are from AMD.
