### ISSUE TITLE
Keyboard Backlight on press of Microphone Mute / ROG Key

### ISSUE THREAD

**Issue by Twel12** [seerge/g-helper#657]
When keyboard light sleeps it should wake up , it does but not via press of mic mute or ROG Key (does wake up via other keys or trackpad).

**Clear scenario to Reproduce**
1.Let keyboard backlight sleep
2. Press on mute / ROG key

**Expected behavior**
keyboard backlight wakes up

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/11806458/log.txt)

OS: Windows 11 Home
GA503QM ( Zephyrus G15 2021)

**Asus software**
- Armoury crate (or it's services installed)
- MyASUS installed
 ran the debloat script G-Helper Shows 0 services

Maybe its due to armoury crate installed but im not exaclty sure because i have 0 services running thnz to debloat script 😅.

**Comment by seerge** [comment]
@Twel12 honestly, you are nitpicking monsignor. Currently backlight timeout is based on windows very own iddle-input timer, and M3/M4 simply are not registered by windows as input. I will look if there is a way to manually reset iddle timer but no promises.

**Comment by Twel12** [comment]
true, sorry for nit-picking. Just wanted to let you know.
