### ISSUE TITLE
[Feature Request (and Bug]) Update notifs and screen refresh rate

### ISSUE THREAD

**Issue by sentfromthehub** [seerge/g-helper#66]
Hey!

So I finally was able to reproduce the refresh rate issue outlined [here](https://github.com/seerge/g-helper/issues/21) with my G401QC. For it to occur on my end, you have to unplug the laptop from AC power and wake the laptop up from lid-induced sleep mode. When unlocking, even though the GPU mode switches to Eco, the refresh rate doesn't.

For the feature request, can you add a little notif when an update is available? Sometimes I'm too busy with school and don't realize you've released 10 updates in the past week with the last one being 2 hours ago ;).

Thanks in advance

**Comment by seerge** [comment]
There is already update notifications in the app. As for your case, i'm not able to reproduce it.

**Comment by seerge** [comment]
@sentfromthehub in https://github.com/seerge/g-helper/releases/tag/v0.26 i have changed way app detects laptop wake up, you can try it
