### ISSUE TITLE
Problems with screen brightness when on dGPU (plugged in)

### ISSUE THREAD

**Issue by GibStorm** [seerge/g-helper#660]
**Describe the bug**
If I run with GHelper instead of Armory Crate (all Armory Crate/ASUS services disabled) and plug in to have the Optimized/Auto settings switch as intended to high performance modes, the brightness of my display is not adjustable and stuck in a very low brightness state. If I use GHelper to switch to "Eco" mode and thus using the iGPU (Radeon) the brightness works fine.

In order to be able to use my dGPU (RTX 4070) on full brightness, I have to switch to using Armory Crate again (start all services etc) and closing GHelper.
Using the Windows brightness slider also does nothing. Twinke Tray app is not able to change the brightness either.

**Clear scenario to Reproduce**
1. Run GHelper with Armory Crate uninstalled or all services disabled.
2. Switch everything to optimal power saving in GHelper (auto/optimized).
3. Increase screen brightness to 100%.
4. Plug in the charger.
5. Everything switches to performance mode as inteded, but screen brightness drops.
6. Unable to adjust screen brightness in this state.

**Expected behavior**
I would expect that in addition to GHelper switching everything to performance mode as intended, the screen brightness would either automatically go to max or stay at the previous brightness level. It would be expected to be able to adjust the levels as well.

**App Logs**
Logs attached.

**Screenshots or screencasts**
Would not illustrate the problem.

**Desktop (please complete the following information):**
 - OS: Windows 11 (version 22H2, build 22621.1848)
 - Laptop model: ROG Zephyrus G14 (2023) GA402NI (IPS display, 165 hz)

**Asus software**
- Armoury Crate: Yes, but services disabled when having issue.
- MyASUS installed: Yes, but services disabled when having issue.
- Other Asus services running in background: No, all disabled when having issue.

**Additional context**
Brand new laptop. Basically everything works fine using Armory Crate, but not with GHelper. I love this app, and would like to assist in fixing this issue since it is the one thing preventing me from replacing Armory Crate with it.

[log.txt](https://github.com/seerge/g-helper/files/11831042/log.txt)

**Comment by seerge** [comment]
@GibStorm hello,

I have also noticed your message on reddit, but thanks for posting it here, it's way more convenient. 

I'm keen to think that this is due to NVidia optimus (as someone else mentioned on reddit). It creates 2 screens in system configuration (1 real and 1 virtual) in order to do it's own switches of what GPU will drive screen each moment. 

And when when dGPU gets enabled without restart (i.e. when you plug in on Optimized) windows just gets confused and tries to set brightness on a wrong screen.

Can you reach the state where brightness is not controllable (i.e. disable/enable GPU?) and try following things one by one, and see if it helps (then i will be able to "implement" that in g-helper too): 

1. Change display refresh rate to 60Hz and back 
2. Change display resolution
3. Press Win+P (project settings) and try to switch things there back and forward (i.e. set single display)
4. Manually run NVidia control panel
5. Open windows Services -> and try to restart each nvidia service

Thanks for cooperation :)

**Comment by seerge** [comment]
@GibStorm also try this build that uses alternative method to control brightness from FN+F7/F8 hotkeys (to see if it makes difference?)

[GHelper.zip](https://github.com/seerge/g-helper/files/11832431/GHelper.zip)

**Comment by GibStorm** [comment]
> @GibStorm hello,
> 
> I have also noticed your message on reddit, but thanks for posting it here, it's way more convenient.
> 
> I'm keen to think that this is due to NVidia optimus (as someone else mentioned on reddit). It creates 2 screens in system configuration (1 real and 1 virtual) in order to do it's own switches of what GPU will drive screen each moment.
> 
> And when when dGPU gets enabled without restart (i.e. when you plug in on Optimized) windows just gets confused and tries to set brightness on a wrong screen.
> 
> Can you reach the state where brightness is not controllable (i.e. disable/enable GPU?) and try following things one by one, and see if it helps (then i will be able to "implement" that in g-helper too):
> 
> 1. Change display refresh rate to 60Hz and back
> 2. Change display resolution
> 3. Press Win+P (project settings) and try to switch things there back and forward (i.e. set single display)
> 4. Manually run NVidia control panel
> 5. Open windows Services -> and try to restart each nvidia service
> 
> Thanks for cooperation :)

I've tried all 5 things, without it changing anything in relation to the problem.

**Comment by GibStorm** [comment]
> @GibStorm also try this build that uses alternative method to control brightness from FN+F7/F8 hotkeys (to see if it makes difference?)
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/11832431/GHelper.zip)

The new version still doesn't enable me to change screen brightness. The Windows brightness slider changes, but visually there is no difference.

**Comment by seerge** [comment]
@GibStorm ok, thanks for trying :) 

I assume that in System -> Display settings you have 2 diplays (correct?) Each of them has a brightness slider, can you switch between displays and try to drag them and see if both have no effect on birghtness?

![Screenshot 2023-06-22 122709](https://github.com/seerge/g-helper/assets/5920850/0d985ea3-12d4-4c4c-87ca-0c67a4ee46b3)

And just to confirm - does rebooting (in a state where brightness is locked) unlock brightness?

**Comment by GibStorm** [comment]
> @GibStorm ok, thanks for trying :)
> 
> I assume that in System -> Display settings you have 2 diplays (correct?) Each of them has a brightness slider, can you switch between displays and try to drag them and see if both have no effect on birghtness?
> 
> ![Screenshot 2023-06-22 122709](https://user-images.githubusercontent.com/5920850/247902683-0d985ea3-12d4-4c4c-87ca-0c67a4ee46b3.png)
> 
> And just to confirm - does rebooting (in a state where brightness is locked) unlock brightness?

I actually don't see that overview at all. It shows no displays there at all.

![image](https://github.com/seerge/g-helper/assets/4786264/7c6bbbab-3dc7-42b4-bd90-265abd1753b7)

**Comment by seerge** [comment]
@GibStorm ok, what about my second question : 
> And just to confirm - does rebooting (in a state where brightness is locked) unlock brightness?

And can you try this build with a bit more verbose logging and post a log here again ? It won't fix brightness, i just want to see what is display configuration windows has :) 

[GHelper.zip](https://github.com/seerge/g-helper/files/11833050/GHelper.zip)

**Comment by seerge** [comment]
P.S. And can you post a screenshot of your device manager with display adapters and monitors ? (like this one)

![Screenshot 2023-06-22 125044](https://github.com/seerge/g-helper/assets/5920850/a7a2135f-820f-43af-ac12-22256c0df898)

**Comment by GibStorm** [comment]
> @GibStorm ok, what about my second question :
> 
> > And just to confirm - does rebooting (in a state where brightness is locked) unlock brightness?
> 
> And can you try this build with a bit more verbose logging and post a log here again ? It won't fix brightness, i just want to see what is display configuration windows has :)
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/11833050/GHelper.zip)

I've just made a "clean" NVIDIA driver reinstall, just to make sure. Then I wanted to test this, but oddly it all now works just fine when I switch between charger and not.

I'm running with the new debug build, and have attached the log.

![image](https://github.com/seerge/g-helper/assets/4786264/832e0515-6795-4d79-bece-52800ffc29f7)
[log.txt](https://github.com/seerge/g-helper/files/11833104/log.txt)

**Comment by seerge** [comment]
@GibStorm  May be nvidia driver was the reason then?

You are not the only one reporting this, but from reddit i also see that people had same locked brightness also using armoury (sometimes). So that's why i think it's nvidia / optimus related issue.

What I also remember from AC behavior, it won't let you turn Eco unless optimus switch is literally set to "optimus" (i.e. not Auto and not NVidia only) in nvidia control panel. G-helper doesn't check / require that.  May be the reason of locked brightness was that Eco mode was turned on with a different optimus setting in a first place? (just guessing)

**Comment by GibStorm** [comment]
I don't know, but maybe you should see if you could log stuff like that? I'm runding your debug version now, in case something pops up again 🙂

**Comment by seerge** [comment]
@GibStorm you can try to "re-create" issue now.

SCENARIO 1

1. Start with GPU set to Standard (i.e. enabled)
2. Set Nvidia control panel display mode to - "Optimus" (2nd option)
![optimus](https://nvidia.custhelp.com/rnt/rnw/img/enduser/aid_5097_01.png)
3. Set GPU to Eco -> check brightness controls
4. Set GPU to Standard again -> check brightness controls

SCENARIO 2 

1. Start with GPU set to Standard (i.e. enabled)
2. Set Nvidia control panel display mode to - **"Nvidia GPU only" (3nd option)**
3. Set GPU to Eco -> check brightness controls
4. Set GPU to Standard again -> check brightness controls (should be broken?)

**Comment by GibStorm** [comment]
I'll take a look at it later tonight and will get back to you. Thank you for your help so far :)

**Comment by GibStorm** [comment]
Adjusting brightness stopped working again. This time it was stuck at max brightness though.

So,

SCENARIO 1 (started while brightness adjustment didn't work while plugged in)
1. GPU mode was already "Standard" due to "Optimized" setting and being plugged in
2. Changed Display Mode in NVIDIA Control Panel from "Auto Select" to "Optimus" - Brightness adjustments still don't work
3. Set GPU Mode to "Eco" - Adjustments still don't work
4. Set GPU Mode to "Standard" - Adjustments still don't work


SCENARIO 2
1. Set GPU Mode to "Standard"
2. Changed Display Mode to "NVIDIA GPU Mode Only" - Brightness adjustments still don't work
3. Set GPU Mode to "Eco". Screen went black and hen came back, NVIDIA Control Panel closed itself. Brightness controls now work. (cannot open NVIDIA Control Panel in this state)
4. Set GPU Mode to "Standard" again. Brightness controls stopped working yet again,

Through all of this, your second 0.89.0.0 debug version was used. Log attached.
[log.txt](https://github.com/seerge/g-helper/files/11840676/log.txt)

**Comment by seerge** [comment]
@GibStorm ok, clear. 

But what I want to know if SCENARIO 1 breaks brightness controls or not (when it's already broken it's not much help) 

Does rebooting help to restore brighntess control? (i assume it does)

If so - can you reboot in standard mode and try to repeat SCENARIO 1 (i.e. when display mode is set to "Optimus" prior to switching GPU off), and see if it brightness works after?

**Comment by GibStorm** [comment]
Rebooting restores brightness control without doing anything else (while in "Standard" mode).

OK, so whille in "Standard" mode and brightness controls now working:

1. I opened NVIDIA CP and  Display Mode is in "NVIDIA GPU Only Mode".
2. I try to set Display Mode to "Auto Select" which gives me error about a couple of apps that need closing first.
3. I close the apps, and a message pops up from NVIDIA CP that Display Mode is now in "Optimus Mode" (Auto Select is chosen). Brightness controls still work at this point.
4. Just for good measure, I set Display Mode to "Optimus" for testing. Brightness controls still work.
5. I set GPU Mode to "Eco". NVIDIA CP closes itself. Brightness controls work.
6. I Set GPU Mode to "Standard". Brightness controls still work.

At this point I start thinking that the issue only happens in relation with actually connecting the charger.
I wanted to test this, so:
1. I set CPU Mode to "Turbo" and GPU Mode to Optimized while having the charger plugged in.
2. Tested brightness controls, which still work at this point.
3. Opened NVIDIA CP and set to "Auto Select". Brightness controls work.
4. Unplugged the charger. NVCP closed itself, CPU mode went to Silent, GPU mode to Eco (as expected). Brightness controls still work.
5. Re-inserted the charger. CPU mode went to Turbo, GPU mode to Standard (as expected). Brightness controls still work (!)

Honestly, I fail to see the culprit here.

Another log is attached.

[log.txt](https://github.com/seerge/g-helper/files/11840760/log.txt)

**Comment by GibStorm** [comment]
Please not that I **do not** have two displays detected, as you mentioned earlier. I only have one.

**Comment by seerge** [comment]
@GibStorm thanks for trying, i see that you have only 1 display and it's always main (i.e. DISPLAY1) from the log :) 

I think the key here - is that NVidia display mode has to be in Optimus (or Auto but also in "optimus"), i.e. it has to be AMD iGPU driving display **BEFORE** you turn dGPU off. 

AC literally won't let you set Eco if display mode is not Optimus, and that's probably a reason for that. 

I'm not aware about way to programmatically set Optimus setting somehow (from g-helper), i think it can be done only by hand by user. But I will try to look into if it's possible to read optimus status at least (i.e. throw a warning for user if he wants to set Eco)

For now I would just advice to either always keep nvidia display in optimus, or at least set it prior to disabling GPU (setting Eco mode) :)

**Comment by GibStorm** [comment]
I´ll keep running your debug build of G-Helper, and set Display Mode in NVCP to "Optimus" specifically. If that prevents the problem, at least we have made progress :)

**Comment by seerge** [comment]
@GibStorm oke, btw second display info doesn't come from me only . It comes from this issue https://github.com/seerge/g-helper/issues/521 :) (see a screenshot there showing 2 displays)

**Comment by GibStorm** [comment]
> @GibStorm oke, btw second display info doesn't come from me only . It comes from this issue #521 :) (see a screenshot there showing 2 displays)

I know, I've seen :) I just wanted to emphasize that it wasn't the case with my machine. Maybe that's different in the 2023 models of the Zephyrus G14's?

**Comment by seerge** [comment]
@GibStorm can you run in powershell (as admin or not) following command ? that's nvidia's own utility that outputs current gpu status

```nvidia-smi -i```

**Comment by GibStorm** [comment]
Had to be a bit more specific with the command, but here is the output :)

![image](https://github.com/seerge/g-helper/assets/4786264/1ff461e9-5687-4ab3-b957-d267a54f4e96)

**Comment by seerge** [comment]
@GibStorm and can you check if ouput changes if you set display mode to "Nvidia Only" instead of "Optimus" ?
I mainly interested in section with Bus-ID / Disp.A (it says OFF now)

**Comment by GibStorm** [comment]
The only difference as far as I can see, is that now it has apps actually running off of the dGPU. Everything else seems the same to me.

![image](https://github.com/seerge/g-helper/assets/4786264/6aaa0f8b-d235-4d30-809e-d5feea44d054)

**Comment by seerge** [comment]
Actually it says ON now (instead of OFF)
![248077437-6aaa0f8b-d235-4d30-809e-d5feea44d054](https://github.com/seerge/g-helper/assets/5920850/d9f94bb5-820b-4951-9db0-cc1a7aa2dd68)

**Comment by GibStorm** [comment]
@seerge right you are. Did't see that :) Awesome, so you can now check this state, I guess?

**Comment by seerge** [comment]
@GibStorm yes, if that's the flag. But I think it would be better to run a command that would output only that

```nvidia-smi --help-query-gpu``` - will give you full list of parameters (find display active there)
```nvidia-smi --query-gpu=<PUT DISPLAY ACTIVE NAME HERE> --format=csv ``` - to get value

**Comment by seerge** [comment]
@GibStorm or just run ``nvidia-smi -i 0 -q``

**Comment by GibStorm** [comment]
Here is the output from `nvidia-smi -i 0 -q`
[output.txt](https://github.com/seerge/g-helper/files/11841081/output.txt)

**Comment by seerge** [comment]
@GibStorm oke, thanks :) I will add a check using that and show a warning before going to eco mode if display is ACTIVE

**Comment by seerge** [comment]
Ok, i have something to test for you

This build will check for Display Mode : Enabled (from that nvidia-smi command). And if it's "Enabled" (i.e. it's nvidia driving display and optimus is off) - it will show a warning popup, asking to enable optimus and if you want to proceed as is.

[GHelper.zip](https://github.com/seerge/g-helper/files/11847745/GHelper.zip)

**Comment by GibStorm** [comment]
Installed

**Comment by seerge** [comment]
@GibStorm cool, does it show warning if display mode is set to nvidia ?

**Comment by GibStorm** [comment]
Might need a little bit of "polish" but yes, it does :)

![image](https://github.com/seerge/g-helper/assets/4786264/a9d96471-d794-4aaa-829a-8b923541aea5)

**Comment by seerge** [comment]
@GibStorm oh, i just accidentally swapped title and text fields :D 

This one should have correct ones. But i'm still not sure about proper wording.
As I don't want to complately block Eco mode in this case, but just show a warning.

[GHelper.zip](https://github.com/seerge/g-helper/files/11849044/GHelper.zip)

**Comment by seerge** [comment]
Btw, it could be that there is some way to set display mode via nvidia-smi (i just can't find it in documentation anywhere), then app can use that to switch automatically.

**Comment by GibStorm** [comment]
Yeah, that's what I thought :)

Here's what I suggest you write.

**Title:**
NVIDIA Display Mode is not set to Optimus

**Description:** 
Disabling the dGPU by going to Eco mode while Display Mode in NVIDIA Control Panel is not set to Optimus might cause problems with brightness controls until after the next reboot.

Do you still want to continue?

![image](https://github.com/seerge/g-helper/assets/4786264/a6b2602d-df42-4f74-8935-74d0dea2d2b6)

**Comment by GibStorm** [comment]
Choosing "No" in that popup causes the main application to be stuck in "Changing.." state, as seen here

![image](https://github.com/seerge/g-helper/assets/4786264/fa552626-e1f9-45dc-85d4-745f286198c6)

**Comment by seerge** [comment]
@GibStorm this build should fix it :)
[GHelper.zip](https://github.com/seerge/g-helper/files/11849230/GHelper.zip)

**Comment by seerge** [comment]
@GibStorm do we consider this as solved then?

**Comment by GibStorm** [comment]
@seerge yup :)

**Comment by AudreyAP** [comment]
@seerge I don't have any issue with brightness controls when switching from dGPU to iGPU on Intel+Nvidia M16 2023 - might want to see if the issue is only on AMD machines and not give the popup otherwise?

My windows brightness slider breaks when in advanced Optimus / mux mode but it did that on stock Asus windows, and I don't think it's related to this issue. I can still control brightness with keys (same as OEM image).

**Comment by seerge** [comment]
@AudreyAP it could be interested only on amd+nvidia setups, so you can’t “break” brightness controls on your m16 no matter what you do now?

**Comment by seerge** [comment]
@AudreyAP try this build, it should skip whole check for non-AMD CPUs

[GHelper.zip](https://github.com/seerge/g-helper/files/11872095/GHelper.zip)

**Comment by kwhychange** [comment]
Hi, I tried the new 0.91 update but the problem persists for me. I have my settings set to optimized and auto. Is there anything that I can do to fix this?

**Comment by gloglas** [comment]
I had same issue, try updating everything and then do *Clean* Nvidia driver installation. Don't forget to turn Optimus back on. It seems to help for now but we'll see.

**Comment by AudreyAP** [comment]
@seerge Just double checked:

Using latest GHelper release, being in "NVIDIA GPU only", then switching to ECO in GHelper does not result in any brightness issues on the iGPU. It does not seem that M16 2023 needs to be switched to Optimus mode before switching the GPU off. 

Certain apps (mostly games) respond very poorly though. Valorant for example will go completely unresponsive and will need to be quit via task manager if running on the GPU, then switched to ECO. 

You might want to add an option to "Optimized" mode to ask the user to confirm that they want to switch to Eco mode after unplugging if anything is being rendered by the GPU, just in case the user wants to just move their power adaptor to a new outlet or something. User should be able to switch to ECO manually (they know what they are doing), but Optimized should have an option ask for confirmation such that crashes can be avoided.

**Comment by seerge** [comment]
@AudreyAP hello.

Actually app already checks for GPU load before switching it OFF / ON in Optimized mode and shows you a warning if load is > 10% (i.e. game is running). This is done to prevent crashing your gaming session if you suddenly lose power in outlet :) You can see GPU usage % in app logs when it starts switching.

**Comment by AudreyAP** [comment]
@seerge Oh! Oops. 🤦‍♀️ 

I guess valorant loading screen in the background must just not load the GPU enough. All good then :)

**Comment by AudreyAP** [comment]
I may have been wrong here - I'm not sure why, but I can sometimes break brightness control while the GPU is enabled but not in advanced optimus mode. 

Switching to ECO mode allows me to control the brightness once again, but switching back to Standard (gpu on, but intel driving the display) results in brightness controls not working and being locked to a low-ish value. I need to reboot to get brightness control back while in standard mode.

**Comment by AudreyAP** [comment]
Restarting this service:

![image](https://github.com/seerge/g-helper/assets/130399040/abaeed3d-14df-4bb9-9eec-617e3c219b09)

fixes brightness control.

**Comment by Meglos** [comment]
@seerge Hi, sorry for the necro thread but this is still an issue on the G16 2023 (Nvidia/Intel). The fix mentioned above (restarting the Nvidia service) does work but it is kind of a pain in the ass to open up services each time I plug in my laptop. A clean install of Nvidia drivers fixed it temporarily but then it came back upon the next restart.

**Comment by AudreyAP** [comment]
@Meglos I think this is a windows/Nvidia bug tbh and I have some theories about what might be causing it. 

Do you happen to use hibernation?

**Comment by Meglos** [comment]
@AudreyAP I do, because sleep seems to have all sorts of annoying issues in Win11

**Comment by AudreyAP** [comment]
@Meglos try disabling hibernation. My theory is that for whatever reason the drivers REALLY don't like handling the GPU appearing after hibernation. The issue only ever happens after the machine comes out of hibernation for me. I'm turning off hibernation to test, maybe if we both get good results serge can implement auto-restarting the Nvidia service when the machine comes out of hibernation?

**Comment by seerge** [comment]
@Meglos hello, the official workaround is live in the app for a while https://github.com/seerge/g-helper/discussions/1042 . You need to select "Enable GPU on shutdown", then windows / nvidia drivers will always see GPU on boot and act fine :)

**Comment by AudreyAP** [comment]
@seerge I've been using it for a few weeks and the issue remains. See above for my hypothesis on why it keeps happening?

**Comment by seerge** [comment]
@AudreyAP checkbox from https://github.com/seerge/g-helper/discussions/1042 also covers hibernation (at least if it happens not while laptop is asleep). Did you try it ? :)

**Comment by AudreyAP** [comment]
@seerge yep I've been using it for at least a few weeks and while the problem is less severe, it still happens every so often. 

I think the problem may be the transition from sleep to hibernate caused by adaptive hibernation, as this issue mostly happens in the morning when I turn the laptop on after it has been hibernating overnight automatically. Maybe that transition is not being caught? I do not ever manually hibernate, it only ever happens due to adaptive hibernation.

**Comment by seerge** [comment]
@AudreyAP if hibernation happens during sleep - then all apps including G-Helper are suppressed. So if you had dGPU disabled in that moment, the workaround doesn't happen of course :) there is no solution for that.

**Comment by AudreyAP** [comment]
@seerge how about this: when ghelper becomes active, check if the machine has recently exited hibernation. If it has, and if the user has the "enable gpu on shutdown" option enabled, and if the GPU is disabled (meaning ghelper was not able to successfully enable it), enable the GPU, then restart the "Nvidia display container ls" service. Restarting that service fixes the brightness issue 100% of the time for me, no reboot necessary.

**Comment by seerge** [comment]
@AudreyAP i think it's way too complicated :| may be just add a quick batch file on desktop with a command to restart service and run it if that happens? :)

**Comment by AudreyAP** [comment]
@seerge the real solution here is making dynamic hibernate wake up the machine before it commands hibernation... I'll try to figure out if this is possible.

**Comment by seerge** [comment]
@AudreyAP and others,

I'm now testing G14 2024, and it seems like it doesn't suffer from this "Shutdown in Eco mode" issue at all https://github.com/seerge/g-helper/discussions/1042

I'm able to shutdown device in Eco, start over and switch Standard <-->Eco any number of times w/o any issues.

I run latest official Nvidia drivers tho. Can you confirm it's "fixed" now ? or is it only 2024 models

**Comment by lucas-zimerman** [comment]
> at
> 
> `nvidia-smi --help-query-gpu` - will give you full list of parameters (find display active there) `nvidia-smi --query-gpu=<PUT DISPLAY ACTIVE NAME HERE> --format=csv ` - to get value

That helped me!!!
the issue for me started when i was plugged on AC on  optimized, I removed the AC cable and later on pluged it back and brightness never worked again...
even restarting didnt fix it, but restarting this service indeed fixed it.

**Comment by Portkinov** [comment]
I got the brightness 100% issue with ghelper.

GPU: RX 6800M

any solution with it?

**Comment by Broman3100** [comment]
> I got the brightness 100% issue with ghelper.
> 
> GPU: RX 6800M
> 
> any solution with it?

As discussed previously the issue is consistent and basically unavoidable under certain cases.
Rebooting the laptop or restarting "NVIDIA Display Container LS" from services fixes it, but you will still get it in the future. Also applies to future-comers as well.

**Comment by isblu** [comment]
I also have a similar issue 
Steps to recreate 
1. From armoury crate change gpu mode to eco 
2. Shutdown the laptop
3. Turn it on 
4. Change back gpu mode to Standard mode
So far only issue I have is the inability to control brightness, it seems the brightness changes to defined value always (which is low)
Restarting the laptop in standard mode fixes the brightness.
Asus TUF F15 FX507VV
Intel i7-13700h
RTX-4060

**Comment by seerge** [comment]
@isblu check “Enable GPU on shutdown” under Extra and you should be good

**Comment by isblu** [comment]
> @isblu check “Enable GPU on shutdown” under Extra and you should be good

I was using armoury crate. And is this issue been identified?

**Comment by DaanHessen** [comment]
> Restarting this service:
> 
> ![image](https://private-user-images.githubusercontent.com/130399040/281903893-abaeed3d-14df-4bb9-9eec-617e3c219b09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTY1NDQsIm5iZiI6MTczNDk1NjI0NCwicGF0aCI6Ii8xMzAzOTkwNDAvMjgxOTAzODkzLWFiYWVlZDNkLTE0ZGYtNGJiOS05ZWVjLTYxN2UzYzIxOWIwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxMjE3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTUzNjlkYjY0MmJhODIxODJmYjQxNTZlNWMxYmE1NzFkZDNiMmY1YmU4Y2QzYmZiYjI1ZWExZjMxNWUzNjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u2RXqQ-TdIqaK8HyGP_f9E2xRMRAZxebLp9RU0AJJO8)
> 
> fixes brightness control.

this worked, thanks!

**Comment by RyabovNS** [comment]
Restarting this service helped me:

![Image](https://github.com/user-attachments/assets/997d0151-86d5-48cb-bf4a-84b5af7fd2ee)

**Comment by isblu** [comment]
> Restarting this service helped me:
> 
> ![Image](https://github.com/user-attachments/assets/997d0151-86d5-48cb-bf4a-84b5af7fd2ee)

Worked for me as well 👍👍👍

**Comment by Stensel8** [comment]
![Image](https://github.com/user-attachments/assets/261266dd-9cbd-47f7-b8ef-1cea9446449d)
Same here! Solved the brightness bug by restarting this service. However, it is a temporary fix :(
![Image](https://github.com/user-attachments/assets/e56aa277-bfd9-47e0-89f4-bb4555c6d6ee)

**Comment by seerge** [comment]
@Stensel8 @isblu - you can check `Enable GPU on shutdown` under `Extra`. Then, if device boots with GPU being on, nvidia driver starts properly and doesn't expose this problems :)

**Comment by Stensel8** [comment]
> @Stensel8 @isblu - you can check `Enable GPU on shutdown` under `Extra`. Then, if device boots with GPU being on, nvidia driver starts properly and doesn't expose this problems :) 

Aight! Didn't knew where that option was for! Thanks a lot! I will give it a try :)

**Comment by Initialize23** [comment]
Okay after trying everything i finally i got it fixed, its in G helper, extra settings, turn off: Optimal Display Brightness.

<img width="390" alt="Image" src="https://github.com/user-attachments/assets/4fab1535-d3fb-4e19-b6d2-69ba9476308e" />

**Comment by Dalkarl** [comment]
> For the sake of documentation: I ran into this issue twice already with a new ROG Zephyrus 2025 G16. Restarting NVIDIA Container service fixes it without reboot. I've now enabled the "Enable GPU on shutdown" function to hopefully prevent it.
> 
> Out of curiosity: why is that feature not defaulted and/or could we detect it being required? I did notice in NVIDIA Control Panel that this screen was broken while the issue was active:
> 
> ![Image](https://github.com/user-attachments/assets/c6ed1c8f-6cef-4c28-933d-70c8b47d10b0)
> 
> It had only the top option available and enabled, in "Integrated Graphics" mode, despite happily enabling discrete when a game launched.

Same issue on my Zephyrus G16 with AMD Ryzen 7 + RTX 5070.

**Comment by seerge** [comment]
@Dalkarl did you try selecting Enable GPU on shutdown under Extra?

Alternatively get latest release and try new "workaround" called Stop Nvidia service in Eco mode

https://github.com/seerge/g-helper/releases
