### ISSUE TITLE
Both CPU and GPU fans stop working in Balanced Mode.

### ISSUE THREAD

**Issue by DaddyK1tt3n** [seerge/g-helper#661]
**Describe the bug**
Both CPU and GPU fans stop working in Balanced Mode. When in Turbo Mode, both work. An external monitor in connected.

**Clear scenario to Reproduce**
1. Changing the Mode to Balanced automatically turns both fans off (refer to screenshot one). 
![Screenshot 1](https://github.com/seerge/g-helper/assets/122669736/0bb50ddc-e1cc-403e-a92d-e2986c5d31cf)

2. Changing to Turbo turns both fans back on (refer to screenshot 2).
![Screenshot 2](https://github.com/seerge/g-helper/assets/122669736/d624cfd2-e6fc-46a7-af25-b5c5069c364a)

3. I've added the extra line in the config.json file re: the BIOS workaround. The issue persists.
4. I've tried it with the monitor unplugged, the same issue persists. I've tried it with the internal monitor off, and the same issue persists. I tried switching to eco, then optimized, still the same.

**Expected behavior**
I expect both fans to work, especially that I didn't touch the fan curves, nor did I apply any custom ones. Both should be running at least 2200 rpm based on the graph in the options. 

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Asus ROG Strix G513QM (2021 model)

**Asus software**
- Armoury Crate uninstalled
- MyASUS uninstalled (but the driver remains installed)
- No other Asus services running in background (stopped via the new function under "Extras"

6/23/2023 10:05:31 AM: ------------
6/23/2023 10:05:31 AM: App launched: ROG Strix G513QM_G513QM :0.90.0.0en-US
6/23/2023 10:05:31 AM: NVIDIA GeForce RTX 3060 Laptop GPU
6/23/2023 10:05:32 AM: CPU: 7 - AMD Ryzen 9 5900HX with Radeon Graphics         - AMD64 Family 25 Model 80 Stepping 0
6/23/2023 10:05:32 AM: AutoSetting for Online
6/23/2023 10:05:32 AM: Input: \\?\hid#vid_0b05&pid_1866&col04#7&10042e03&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
6/23/2023 10:05:32 AM: Mode = 0 : OK
6/23/2023 10:05:32 AM: Eco flag : 0
6/23/2023 10:05:32 AM: Mux flag : -65536
6/23/2023 10:05:32 AM: Auto:5D-BA-C5-C4-01
6/23/2023 10:05:32 AM: Monitor Power On
6/23/2023 10:05:51 AM: GET GPU CLOCKS: 0, 0
6/23/2023 10:05:53 AM: Mode = 0 : OK
6/23/2023 10:05:53 AM: GET GPU CLOCKS: 0, 0
6/23/2023 10:06:00 AM: Mode = 1 : OK
6/23/2023 10:06:07 AM: GET GPU CLOCKS: 0, 0
6/23/2023 10:06:09 AM: Mode = 1 : OK
6/23/2023 10:06:09 AM: FanCPU = 14-3F-44-48-4C-50-54-62-11-1A-22-29-34-43-51-5A : OK
6/23/2023 10:06:09 AM: FanGPU = 14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F : OK
6/23/2023 10:06:09 AM: GET GPU CLOCKS: 0, 0
6/23/2023 10:06:23 AM: Mode = 0 : OK
6/23/2023 10:06:23 AM: GET GPU CLOCKS: 0, 0
6/23/2023 10:06:23 AM: GET GPU CLOCKS: 0, 0
6/23/2023 10:06:30 AM: Mode = 1 : OK
6/23/2023 10:06:30 AM: FanCPU = 14-3F-44-48-4C-50-54-62-11-1A-22-29-34-43-51-5A : OK
6/23/2023 10:06:30 AM: FanGPU = 14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F : OK
6/23/2023 10:06:30 AM: GET GPU CLOCKS: 0, 0
6/23/2023 10:07:16 AM: ------------
6/23/2023 10:07:16 AM: App launched: ROG Strix G513QM_G513QM :0.90.0.0en-US.
6/23/2023 10:07:16 AM: NVIDIA GeForce RTX 3060 Laptop GPU
6/23/2023 10:07:17 AM: CPU: 7 - AMD Ryzen 9 5900HX with Radeon Graphics         - AMD64 Family 25 Model 80 Stepping 0
6/23/2023 10:07:17 AM: AutoSetting for Online
6/23/2023 10:07:17 AM: Input: \\?\hid#vid_0b05&pid_1866&col04#7&10042e03&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
6/23/2023 10:07:18 AM: Mode = 1 : OK
6/23/2023 10:07:18 AM: FanCPU = 14-3F-44-48-4C-50-54-62-11-1A-22-29-34-43-51-5A : OK
6/23/2023 10:07:18 AM: FanGPU = 14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F : OK
6/23/2023 10:07:18 AM: Eco flag : 0
6/23/2023 10:07:18 AM: Mux flag : -65536
6/23/2023 10:07:18 AM: Monitor Power On
6/23/2023 10:07:18 AM: Auto:5D-BA-C5-C4-01
6/23/2023 10:14:16 AM: Mode = 0 : OK
6/23/2023 10:14:16 AM: GET GPU CLOCKS: 0, 0
6/23/2023 10:14:39 AM: Mode = 1 : OK
6/23/2023 10:14:39 AM: FanCPU = 14-3F-44-48-4C-50-54-62-11-1A-22-29-34-43-51-5A : OK
6/23/2023 10:14:39 AM: FanGPU = 14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F : OK
6/23/2023 10:15:08 AM: BatteryLimit = 85 : OK
6/23/2023 10:15:09 AM: BatteryLimit = 90 : OK
6/23/2023 10:15:12 AM: BatteryLimit = 85 : OK
6/23/2023 10:15:13 AM: BatteryLimit = 80 : OK
6/23/2023 10:34:12 AM: ------------
6/23/2023 10:34:12 AM: App launched: ROG Strix G513QM_G513QM :0.90.0.0en-US.
6/23/2023 10:34:12 AM: NVIDIA GeForce RTX 3060 Laptop GPU
6/23/2023 10:34:14 AM: CPU: 7 - AMD Ryzen 9 5900HX with Radeon Graphics         - AMD64 Family 25 Model 80 Stepping 0
6/23/2023 10:34:14 AM: AutoSetting for Online
6/23/2023 10:34:14 AM: Input: \\?\hid#vid_0b05&pid_1866&col04#7&10042e03&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
6/23/2023 10:34:14 AM: BatteryLimit = 80 : OK
6/23/2023 10:34:14 AM: Mode = 1 : OK
6/23/2023 10:34:14 AM: FanCPU = 14-3F-44-48-4C-50-54-62-11-1A-22-29-34-43-51-5A : OK
6/23/2023 10:34:14 AM: FanGPU = 14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F : OK
6/23/2023 10:34:14 AM: Eco flag : 0
6/23/2023 10:34:14 AM: Mux flag : -65536
6/23/2023 10:34:14 AM: Monitor Power On
6/23/2023 10:34:14 AM: Auto:5D-BA-C5-C4-01
6/23/2023 10:34:50 AM: Key: 56
6/23/2023 10:35:02 AM: Varibright: 1,3
6/23/2023 10:35:15 AM: Key: 124
6/23/2023 10:35:16 AM: Key: 124
6/23/2023 10:35:41 AM: ------------
6/23/2023 10:35:41 AM: App launched: ROG Strix G513QM_G513QM :0.90.0.0en-US
6/23/2023 10:35:41 AM: NVIDIA GeForce RTX 3060 Laptop GPU
6/23/2023 10:35:42 AM: CPU: 7 - AMD Ryzen 9 5900HX with Radeon Graphics         - AMD64 Family 25 Model 80 Stepping 0
6/23/2023 10:35:43 AM: AutoSetting for Online
6/23/2023 10:35:43 AM: Input: \\?\hid#vid_0b05&pid_1866&col04#7&10042e03&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
6/23/2023 10:35:43 AM: BatteryLimit = 80 : OK
6/23/2023 10:35:43 AM: Mode = 1 : OK
6/23/2023 10:35:43 AM: FanCPU = 14-3F-44-48-4C-50-54-62-11-1A-22-29-34-43-51-5A : OK
6/23/2023 10:35:43 AM: FanGPU = 14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F : OK
6/23/2023 10:35:43 AM: Eco flag : 0
6/23/2023 10:35:43 AM: Mux flag : -65536
6/23/2023 10:35:43 AM: Auto:5D-BA-C5-C4-01
6/23/2023 10:35:43 AM: Monitor Power On
6/23/2023 10:37:59 AM: Key: 56
6/23/2023 10:38:10 AM: Screen = 360Hz : OK
6/23/2023 10:38:10 AM: ScreenOverdrive = 1 : OK
6/23/2023 10:49:01 AM: Monitor Dimmed
6/23/2023 10:49:11 AM: WMI event 192
6/23/2023 10:49:16 AM: Monitor Power Off
6/23/2023 10:49:16 AM: Backlight:5D-BA-C5-C4-00
6/23/2023 11:12:42 AM: WMI event 192
6/23/2023 11:12:42 AM: Monitor Power On
6/23/2023 11:12:42 AM: AutoSetting for Online
6/23/2023 11:12:42 AM: Input: \\?\hid#vid_0b05&pid_1866&col04#7&10042e03&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
6/23/2023 11:12:42 AM: BatteryLimit = 80 : OK
6/23/2023 11:12:42 AM: Mode = 1 : OK
6/23/2023 11:12:42 AM: FanCPU = 14-3F-44-48-4C-50-54-62-11-1A-22-29-34-43-51-5A : OK
6/23/2023 11:12:42 AM: FanGPU = 14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F : OK
6/23/2023 11:12:42 AM: Eco flag : 0
6/23/2023 11:12:42 AM: Mux flag : -65536
6/23/2023 11:12:42 AM: Auto:5D-BA-C5-C4-01
6/23/2023 11:24:29 AM: Key: 174
6/23/2023 11:24:29 AM: Listener stopped
6/23/2023 11:24:29 AM: Mode = 2 : OK
6/23/2023 11:24:29 AM: Mode = 0 : OK
6/23/2023 11:24:29 AM: GET GPU CLOCKS: 0, 0
6/23/2023 11:25:35 AM: Mode = 1 : OK
6/23/2023 11:25:35 AM: FanCPU = 14-3F-44-48-4C-50-54-62-11-1A-22-29-34-43-51-5A : OK
6/23/2023 11:25:35 AM: FanGPU = 14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F : OK
6/23/2023 11:46:23 AM: Monitor Dimmed
6/23/2023 11:46:33 AM: WMI event 192
6/23/2023 11:46:33 AM: WMI event 192
6/23/2023 11:46:38 AM: Monitor Power Off
6/23/2023 11:46:38 AM: Backlight:5D-BA-C5-C4-00
6/23/2023 11:59:03 AM: WMI event 192
6/23/2023 11:59:04 AM: Monitor Power On
6/23/2023 11:59:04 AM: AutoSetting for Online
6/23/2023 11:59:04 AM: WMI event 192
6/23/2023 11:59:04 AM: Input: \\?\hid#vid_0b05&pid_1866&col04#7&10042e03&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
6/23/2023 11:59:04 AM: BatteryLimit = 80 : OK
6/23/2023 11:59:05 AM: Mode = 1 : OK
6/23/2023 11:59:05 AM: FanCPU = 14-3F-44-48-4C-50-54-62-11-1A-22-29-34-43-51-5A : OK
6/23/2023 11:59:05 AM: FanGPU = 14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F : OK
6/23/2023 11:59:05 AM: Eco flag : 0
6/23/2023 11:59:05 AM: Mux flag : -65536
6/23/2023 11:59:05 AM: Auto:5D-BA-C5-C4-01
6/23/2023 12:03:48 PM: Monitor Dimmed
6/23/2023 12:03:58 PM: WMI event 192
6/23/2023 12:03:58 PM: WMI event 192
6/23/2023 12:04:03 PM: Monitor Power Off
6/23/2023 12:04:04 PM: Backlight:5D-BA-C5-C4-00
6/23/2023 12:33:47 PM: WMI event 192
6/23/2023 12:33:49 PM: Monitor Power On
6/23/2023 12:33:49 PM: AutoSetting for Online
6/23/2023 12:33:49 PM: WMI event 192
6/23/2023 12:33:49 PM: Input: \\?\hid#vid_0b05&pid_1866&col04#7&10042e03&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
6/23/2023 12:33:49 PM: BatteryLimit = 80 : OK
6/23/2023 12:33:49 PM: Mode = 1 : OK
6/23/2023 12:33:49 PM: FanCPU = 14-3F-44-48-4C-50-54-62-11-1A-22-29-34-43-51-5A : OK
6/23/2023 12:33:49 PM: FanGPU = 14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F : OK
6/23/2023 12:33:49 PM: Eco flag : 0
6/23/2023 12:33:49 PM: Mux flag : -65536
6/23/2023 12:33:49 PM: Screen = 360Hz : OK
6/23/2023 12:33:49 PM: ScreenOverdrive = 1 : OK
6/23/2023 12:33:49 PM: Auto:5D-BA-C5-C4-01
6/23/2023 12:34:00 PM: Mode = 2 : OK
6/23/2023 12:34:24 PM: Mode = 0 : OK
6/23/2023 12:34:24 PM: GET GPU CLOCKS: 0, 0
6/23/2023 12:34:31 PM: GET GPU CLOCKS: 0, 0
6/23/2023 12:36:30 PM: GET GPU CLOCKS: 0, 0
6/23/2023 12:37:49 PM: Mode = 1 : OK
6/23/2023 12:37:49 PM: FanCPU = 14-3F-44-48-4C-50-54-62-11-1A-22-29-34-43-51-5A : OK
6/23/2023 12:37:49 PM: FanGPU = 14-3F-44-48-4C-50-54-62-16-1F-26-2D-39-47-55-5F : OK
6/23/2023 12:37:49 PM: GET GPU CLOCKS: 0, 0

**Comment by seerge** [comment]
@DaddyK1tt3n hello, 

I see that in balanced mode it uses default (baked in bios) fan curve. Given that your temps on a screenshot are low, i don't see anything unusual here.

If you want (by some reason) your fans to spin even on that level - set a custom fan curve covering that temps :) (as i see you do for turbo mode).
