### ISSUE TITLE
Power Limits checkbox available without other PPT options?

### ISSUE THREAD

**Issue by manciuszz** [seerge/g-helper#665]
I've been wondering why I have the "Apply Power Limits" checkbox, when I don't have any other power limit options (like CPU SPPT slider). I believe that's a bug, since G-Helper doesn't support PPTs on my device, so that checkbox and the section shouldn't be shown to me.
![image](https://github.com/seerge/g-helper/assets/2539661/635beb6b-0f04-495e-a71e-8b89098288b2)

**Comment by seerge** [comment]
@manciuszz what's your device? cause in 0.90 i have added power limits even for older devices with AMD cpus where it was no native support for limits from asus

**Comment by manciuszz** [comment]
ASUS ROG Strix G732LXS

**Comment by seerge** [comment]
@manciuszz oke, you are one of not that many who indeed doesn't have any doable way to set CPU power limits 

This build should fix UI for you

[GHelper.zip](https://github.com/seerge/g-helper/files/11852556/GHelper.zip)
