### ISSUE TITLE
run on startup with auto apply undervolt, does not show task bar icon (next to the clock)

### ISSUE THREAD

**Issue by patmok** [seerge/g-helper#668]
**Describe the bug**
0.89.0.0 with undervolting works very well thank you, but it seems run on startup with auto apply, now requires admin rights. task scheduler will fire up ghelper no problem, but it appears to be as a background process instead of an apps in task manager, meaning the ghelper icon does not appear unless i manually run ghelper myself. the manual start will actually not apply the uv, until i go into fans+power and click apply again, prompting for admin rights

**Clear scenario to Reproduce**
apply undervolt and click auto apply under fans and power. on main screen have run on startup checked

**Expected behavior**
ghelper will run on start up, with icon already in the taskbar (it seems without uv, this used to be the behaviour)

**App Logs**
24/06/2023 12:58:54: ------------    // this is run from task scheduler
24/06/2023 12:58:54: App launched: ROG Zephyrus G14 GA402XZ_GA402XZ :0.89.0.0en-GB.
24/06/2023 12:58:54: NVIDIA GeForce RTX 4080 Laptop GPU
24/06/2023 12:58:55: CPU: 9 - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics      - AMD64 Family 25 Model 116 Stepping 1
24/06/2023 12:58:57: AutoSetting for Online
24/06/2023 12:58:57: Input: \\?\hid#vid_0b05&pid_19b6&col03#7&17810770&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
24/06/2023 12:58:57: BatteryLimit = 60 : OK
24/06/2023 12:58:57: BatteryLimit = 60 : OK
24/06/2023 12:58:57: Mode = 0 : OK
24/06/2023 12:58:57: GET GPU CLOCKS: 0, 0
24/06/2023 12:58:57: Eco flag : 0
24/06/2023 12:58:57: Mux flag : 1
24/06/2023 12:58:57: Matrix Off
24/06/2023 12:58:57: Monitor Power On
24/06/2023 12:58:57: Auto:5D-BA-C5-C4-00
24/06/2023 12:58:58: PowerLimit A0 = 32 : OK
24/06/2023 12:58:58: PowerLimit A3 = 32 : OK
24/06/2023 12:58:58: PowerLimit C1 = 34 : OK
24/06/2023 12:58:58: PowerLimit C0 = 5 : OK
24/06/2023 12:58:58: PowerLimit C2 = 75 : OK
24/06/2023 12:58:58: UV: -18 OK
24/06/2023 12:58:58: iGPU UV: 0 CMD_REJECTED_PREREQ
24/06/2023 12:58:58: CPU Temp: 85 OK
24/06/2023 12:58:58: APU Temp: 85 OK
24/06/2023 13:00:34: ------------   // this is manual run
24/06/2023 13:00:34: App launched: ROG Zephyrus G14 GA402XZ_GA402XZ :0.89.0.0en-GB
24/06/2023 13:00:34: NVIDIA GeForce RTX 4080 Laptop GPU
24/06/2023 13:00:35: CPU: 9 - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics      - AMD64 Family 25 Model 116 Stepping 1
24/06/2023 13:00:35: AutoSetting for Online
24/06/2023 13:00:35: Input: \\?\hid#vid_0b05&pid_19b6&col03#7&17810770&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
24/06/2023 13:00:35: BatteryLimit = 60 : OK
24/06/2023 13:00:35: BatteryLimit = 60 : OK
24/06/2023 13:00:35: Mode = 0 : OK
24/06/2023 13:00:35: GET GPU CLOCKS: 0, 0
24/06/2023 13:00:35: Eco flag : 0
24/06/2023 13:00:35: Mux flag : 1
24/06/2023 13:00:35: Matrix Off
24/06/2023 13:00:35: Auto:5D-BA-C5-C4-00
24/06/2023 13:00:35: Monitor Power On
24/06/2023 13:00:36: PowerLimit A0 = 32 : OK
24/06/2023 13:00:36: PowerLimit A3 = 32 : OK
24/06/2023 13:00:36: PowerLimit C1 = 34 : OK
24/06/2023 13:00:36: PowerLimit C0 = 5 : OK
24/06/2023 13:00:36: PowerLimit C2 = 75 : OK
24/06/2023 13:00:56: GET GPU CLOCKS: 0, 0

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/6642379/5ae93ced-f087-40d7-8947-3f2268722d12)

**Desktop (please complete the following information):**
 - OS: Windows 11, version 22H2
 -  G14 GA402XY

**Asus software**
Asus software
Debloated completely

**Additional context**
![image](https://github.com/seerge/g-helper/assets/6642379/0f6558f6-6dc2-4af5-ae48-35aaa3627ab9)
ghelper running under apps appears to have icon, under background processes does not?

**Comment by seerge** [comment]
@patmok do you have some non-standard user setup, like your windows user doesn't have admin rights?

**Comment by eplum3** [comment]
I'm currently experiencing the same behavior, with admin rights on 1 account. M4 hotkey still works though, but the icon is nice to have. Launching the application after a reboot shows the icon.

**Comment by seerge** [comment]
@eplum3 same question to you ? do you run app from a user w/o admin rights? try to delete a task in task scheduler, then run app again - and check run on startup

**Comment by eplum3** [comment]
@seerge Looks like your recommendation worked! I killed the app via Task Manager and then went to Task Scheduler and deleted the GHelper entry. I then re-opened the application and applied the UV and checked "Run on Startup".  Steps taken on my single Windows account with Admin rights.

This time after a reboot, the application icon is showing and it appears that the UV auto-applied as well.

Thanks for your help and a great app!

**Comment by seerge** [comment]
@eplum3 ok, strange, and i wonder what was the reason in a first place then :) but I'm glad it helped.

**Comment by patmok** [comment]
> @patmok do you have some non-standard user setup, like your windows user doesn't have admin rights?

Thanks for taking a look seerge, @seerge my windows installation only has one user, and its an admin account. I am using windows 11 pro, with a local account though. what seems to happen when i launch g helper just, is that the UV apply will show a prompt to allow for changes to the computer, once approved it appears to restart the application

**Comment by seerge** [comment]
@patmok try same thing that helped @eplum3 - delete GHelper task in task scheduler, and then reschedule it again from starting app -> applying UV -> checking run on startup.

But prior to that, can you post a screenshots of a task details in task scheduler ? (i want to understand what's wrong with it in a first place)

**Comment by patmok** [comment]
![image](https://github.com/seerge/g-helper/assets/6642379/32fb4668-7a32-431f-ae19-3967866b806d)
![image](https://github.com/seerge/g-helper/assets/6642379/110d5fa3-b62e-4534-8eaf-bf35b6b6899e)
![image](https://github.com/seerge/g-helper/assets/6642379/ecabf5ef-3f8e-41c8-a5ca-87d8a2731e77)

i also just retried the same thing that helped eplum3, noticed something interesting in the logs:

```
24/06/2023 13:47:02: UV: -18 BAD
24/06/2023 13:47:02: UV Error: System.ApplicationException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Mutex.ReleaseMutex()
   at Ryzen.Smu.SendMsg(UInt32 SMU_ADDR_MSG, UInt32 SMU_ADDR_RSP, UInt32 SMU_ADDR_ARG, UInt32 msg, UInt32[]& args) in D:\a\g-helper\g-helper\app\Ryzen\RyzenSmu.cs:line 185
   at Ryzen.Smu.SendPsmu(UInt32 message, UInt32[]& arguments) in D:\a\g-helper\g-helper\app\Ryzen\RyzenSmu.cs:line 143
   at Ryzen.SendCommand.set_cogfx(Int32 value) in D:\a\g-helper\g-helper\app\Ryzen\SendCommand.cs:line 1007
   at GHelper.SettingsForm.SetUV(Boolean launchAsAdmin) in D:\a\g-helper\g-helper\app\Settings.cs:line 1166
24/06/2023 13:47:02: APU Temp: 85 OK
24/06/2023 13:47:02: Monitor Power On
24/06/2023 13:48:27: ------------
24/06/2023 13:48:27: App launched: ROG Zephyrus G14 GA402XZ_GA402XZ :0.89.0.0en-GB.
24/06/2023 13:48:27: NVIDIA GeForce RTX 4080 Laptop GPU
24/06/2023 13:48:28: CPU: 9 - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics      - AMD64 Family 25 Model 116 Stepping 1
24/06/2023 13:48:30: AutoSetting for Online
24/06/2023 13:48:30: Input: \\?\hid#vid_0b05&pid_19b6&col03#7&17810770&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
24/06/2023 13:48:30: BatteryLimit = 60 : OK
24/06/2023 13:48:30: BatteryLimit = 60 : OK
24/06/2023 13:48:30: Mode = 0 : OK
24/06/2023 13:48:30: GET GPU CLOCKS: 0, 0
24/06/2023 13:48:30: Eco flag : 0
24/06/2023 13:48:30: Mux flag : 1
24/06/2023 13:48:30: Matrix Off
24/06/2023 13:48:30: Monitor Power On
24/06/2023 13:48:31: Auto:5D-BA-C5-C4-00
24/06/2023 13:48:31: PowerLimit A0 = 32 : OK
24/06/2023 13:48:31: PowerLimit A3 = 32 : OK
24/06/2023 13:48:31: PowerLimit C1 = 34 : OK
24/06/2023 13:48:31: PowerLimit C0 = 5 : OK
24/06/2023 13:48:31: PowerLimit C2 = 75 : OK
24/06/2023 13:48:31: UV: -18 OK
24/06/2023 13:48:32: iGPU UV: 0 CMD_REJECTED_PREREQ
24/06/2023 13:48:32: CPU Temp: 85 OK
24/06/2023 13:48:32: APU Temp: 85 OK
```

**Comment by Halry** [comment]
I have this weird issue, too. I then edit the task in task scheduler and enable "delay task for" then set "10 seconds" in the "At log on" trigger's advanced setting. Then everything works.

**Comment by patmok** [comment]
@Halry does it mean without delay, ghelper runs as background, with delay, it runs as an app under task manager?

**Comment by seerge** [comment]
@patmok the first error message in logs, it's cause it tried to do UV w/o admin rights (and obviously couldn't) so after restart as admin it was all good.

**Comment by Halry** [comment]
i don't know why. Without delay , icon would not show in taskbar but still worked in the background. It will show up if I set the delay.

**Comment by patmok** [comment]
using @Halry suggestion, it seems to make the icon appear now. interestingly, ghelper is still shown as a background process. making my initial guess that app = icon, background = no icon, incorrect

**Comment by seerge** [comment]
@patmok did re-creating task (or adding a delay) solve your issue?

**Comment by patmok** [comment]
@seerge adding the delay did, re-creating did not

**Comment by seerge** [comment]
@patmok oke! good to know, I will remember that :) and if more such cases arise I may add a manual 1 sec delay to standard task as well. 

Closing it as completed then for now.

**Comment by patmok** [comment]
thanks @seerge and @Halry

**Comment by seerge** [comment]
For now I have added this as advice to FAQ https://github.com/seerge/g-helper#app-refuses-to-run-on-startup--runs-without-icon-in-tray-on-startup
