### ISSUE TITLE
[Feature Request] dGPU Sleep on 2020 G14

### ISSUE THREAD

**Issue by skanderbegv2** [seerge/g-helper#67]
I know you're putting in major efforts for the newest G14 and the community appreciates this, will give a special shoutout on the Discord server for you!

Us OGs however are still to this day having issues with our dGPUs sleeping and therefore cutting battery life from 8-10 hours down to 2-3; 3 years later!! Unfortunately 2020 models do not have MUX or iGPU option in Armory Crate.

Any chance you would be able to incorporate force sleeping dGPU for 2020 models? i.e. RTX2060MQ, GTX1060Ti, and GTX1050Ti?

Many thanks in advance!

**Comment by seerge** [comment]
Do you know how to do that ? (technically) ?

**Comment by ajamro** [comment]
Hi! Im also finding power management in my old g14 troublesome (battery drains). I was wandering if porting bbswitch from linux would be feasible https://github.com/Bumblebee-Project/bbswitch .

But still I imagine it being too troublesome, since that method might yield unexpected behavior with nvidia drivers loaded. That method would not only need admin privileges to install, but the driver would need to be signed with special certificate (slightly costly).

On the brighter side there doesn't seem to be much going on there. The code is filled with magic undocumented integers, but is pretty easy to grasp.

**Comment by seerge** [comment]
I won't be doing anything that I can't test :) Especially so far different from current implementation. 
I don't have a 2020 device.

**Comment by ajamro** [comment]
I already did. But there is a bug somewhere in the software resulting in power drain at random, seemingly unrelated occasions. With little to no CPU usage and no nvidia utilization (as reported by tray icon utility), the power draws goes from usual 8-10W up to 30W.

There is a search in the community for what might be causing that and You seem to do things differently - by using wmi call (?), so naturally we are interested if that's the way to at least mitigate the problem.

Either way development of windows drivers seem at least cumbersome. Thinking about it .. can You reveal some details of how You found out about that gpuMux feature and respective calls? Maybe I could  give it a try. Seems like a fun little side project.

**Comment by seerge** [comment]
1. I would recommend to relog windows after you switch to battery. Usually it kills all processes that could use dGPU and then windows should not turn it back. But of course it depends on your software / etc.

2. I use two ACPI calls to disable dGPU (supported on 2021+ models) and enable/disable mux (supported on 2022+ models). They tell asus bios to disable GPU (in simple words). 2020 model simply doesn't support that initially, so there is nothing can be done here.

3. I don't develop drivers :)

**Comment by skanderbegv2** [comment]
Sorry I just saw your reply here - would you benefit from volunteer(s) with 2020 models? Also maybe if you have a look through these projects? Admin from the Discord who originally built similar tools when G14 was first released :)

https://github.com/aredden?tab=repositories

**Comment by seerge** [comment]
@skanderbegv2 yes, i have looked at that https://github.com/aredden/RestartGPU that people were mentioning. But what it does (as i understand) is just disables/re-enables dGPU via device manager. This theoretically should stop all processes using dgpu. But same effect could be achieved with just logging out / in for example.

But you guys can use that app too, why not :)

**Comment by skanderbegv2** [comment]
Problem is even after using the app, dGPU will still randomly wake. Many times nothing is shown in Task Manager, Armory Crate, or nVidia's GPU monitor. Sometimes apps set to use Power-Saving Graphics will still wake and use dGPU. Just a mess overall we've been dealing with for 2 years now. :(
