### ISSUE TITLE
[Feature Request] FN+M1/M2/M3/M4 remapping

### ISSUE THREAD

**Issue by GlaZedBelmont** [seerge/g-helper#670]
![image](https://github.com/seerge/g-helper/assets/48196637/a3d839a3-cb66-47ee-9eef-4e1bb6ffabdd)

Wondering if we could get a way to trigger a custom keycode on FN+M1/M2/M3/M4. Using a G14 2022 and kinda miss not having media keys to control next, previous, play/pause but also don't want to lose volume control.

**Comment by seerge** [comment]
@GlaZedBelmont FN + M-keys don't trigger any event that can be intercepted. Only M-keys alone do :)

**Comment by GlaZedBelmont** [comment]
ahhhh, that sucks
