### ISSUE TITLE
[Feature Request] Support for desktop PC motherboards

### ISSUE THREAD

**Issue by olokos** [seerge/g-helper#672]
**Is your feature request related to a problem? Please describe.**
Armoury Crate also works with quite a lot of ASUS motherboards, but sadly g-helper only works for laptops.

**Describe the solution you'd like**
Adding in the desktop Asus motherboards, X570 series should be a good start, if it's possible at all.

**Describe alternatives you've considered**
The only other alternative I see is completely removing Armoury crate, to stay away from bloatware on Desktop.

**Additional context**
When g-helper is launched on a desktop PC with ASUS X570 mobo, the g-helper just points to download laptop driver from Asus website, which doesn't work at all on desktops.

I'm not sure how hard or feasible it would be, could be very difficult, but with support for desktop motheboards - pretty much any Asus user could replace Armoury Crate with g-helper, right now only laptop users can.

**Comment by seerge** [comment]
@olokos hello :)

Armoury for Desktops and for Laptops is pretty much 2 different applications under same umbrella . They do and control different things.

I don't have a desktop, and don't have time and resources to do a second app for that purpose, but I believe that there are some alternatives like OpenRGB for lights, and also something for fan controls :) 

Thanks.

**Comment by olokos** [comment]
Thank You very much @seerge  for Your reply, completely understandable, I thought they're the same thing, just using different device IDs.

I couldn't really find any alternative for controlling the fans for ASUS Motherboards outside of armoury crate and google searches output Your g-helper.

Do You by any chance know a viable alternative for desktop FAN control of ASUS desktop Motherboards?
I couldn't find anything that supports it properly.

Thank You very much.

**Comment by AudreyAP** [comment]
@olokos Take a look at FanControl

https://github.com/Rem0o/FanControl.Releases
