### ISSUE TITLE
A button to close all apps running/disable dGPU

### ISSUE THREAD

**Issue by MG-LSJ** [seerge/g-helper#677]
Please add a button to force close all apps running on dGPU (/ disable dGPU) when on optimized mode on battery **_when already clicked NO on heavy usage on dGPU prompt_**.

When I'm working in a GPU heavy app and the power goes out, I click NO on the prompt to turn off dGPU. When I'm done with the work, I have to manually set GPU mode to Eco then back to Optimized to turn off the dGPU. 

Also, if possible could you show what apps are utilizing the dGPU, when showing the heavy dGPU usage prompt.

**Comment by seerge** [comment]
@MG-LSJ hello, I didn't get what you want. Optimized mode on battery turns your dGPU off completely. So there is nothing to stop in that case.

**Comment by MG-LSJ** [comment]
> @MG-LSJ hello, I didn't get what you want. Optimized mode on battery turns your dGPU off completely. So there is nothing to stop in that case.

When dGPU usage is heavy this prompt is shown.
![image](https://github.com/seerge/g-helper/assets/73988826/cae16875-2581-4db6-8997-29f88bc37cfb)

If I click no, and then close the gpu using app later, the dGPU is still enabled and sipping power
![image](https://github.com/seerge/g-helper/assets/73988826/5e13a380-e429-4b44-ba1a-ce266e7a0170)

Then I have to manually cycle to eco then to optimized to disable it again.
![image](https://github.com/seerge/g-helper/assets/73988826/4851778e-5e67-4c95-96ae-b81769e518e6)

**Comment by seerge** [comment]
@MG-LSJ everything that you have shown is absolutely correct and works as intended. 

If app sees a heavy GPU usage (like running game or so) it offers to keep GPU working instead shutting it down and killing everything that use it. It's literally a feature multiple users have requested.

Of course if you keep it on -  you indeed need to turn it off manually later if you want.

**Comment by MG-LSJ** [comment]
My request is to add a button/toggle to manually turn off the GPU in Optimized (Battery) Mode

**Comment by seerge** [comment]
@MG-LSJ that button already exists, and is called Eco
