### ISSUE TITLE
Long delay/Occasional crash when switching from dGPU to iGPU

### ISSUE THREAD

**Issue by jacob-devel** [seerge/g-helper#680]
**The Issue**

Hello,

While using the Optimized GPU setting, G-helper is able to switch to my dGPU normally when I plug in AC power, but after unplugging it either takes a long time to switch back, or the program hangs and I have to force close it and try again. Steps to reproduce on my machine are simply to plug in the charger, let the laptop switch GPUs, then later unplug the adapter and wait for the program to try to switch back. With Armoury Crate this transition is very fast and reliable; I know the re-implementation might not function the same way but I just wanted to see if there was any hope of a fix on my end or yours. 

Thanks in advance for your help!

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11869292/log.txt)

**Desktop (please complete the following information):**
 - Windows 11
 - ROG Zephyrus G14 (2023, RTX 4060)
 - I should mention that I run an undervolt, but I tested with default voltages too and got the same result.

**Asus software**
No ASUS software installed or running

PS: This program is a godsend and despite this issue I am very pleased with the state of it, great work

**Comment by seerge** [comment]
@jacob-devel both AC / g-helper use the same command to turn GPU on / off. 

You can run it in powershell (as admin) by yourself even 

```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00090020, 1) - to disable GPU

(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00090020, 0) - to enable GPU
```

It could be that when nvidia display mode is not set to optimus, switching GPU off takes some time (AC just won't even let you do that case). Try to use latest https://github.com/seerge/g-helper/releases/tag/v0.91 where it will show a warning in those situations.

**Comment by Halry** [comment]
I don't think it relates to nvidia display mode. I haven't touch the nvidia driver panel, but I still occurred brightness control problem and the switching hang issue(I had checked and it was on "Auto"). All I can do is instead of control the gpu in ghelper, I use windows power option to force disable dGPU on battery and enable dGPU on AC and it works pretty good. Maybe something new on 2023 models (G14 2023 7940HS+4060) change somethings.

**Comment by seerge** [comment]
@Halry having display mode on Auto actually can drive screen with nvidia (and cause issues afterwards), that’s why Armory demands to set Otimus prior to disabling GPU

**Comment by Halry** [comment]
Oh, sorry. I must misread the issue about the brightness control. I still have these problems. 
My laptop is on battery now. I booted up with standard mode, I can change from "Standard" to "Eco" and then "Eco" to "Standard" once. Then I am not able to change back to Eco unless I restart the laptop.
<img width="855" alt="image" src="https://github.com/seerge/g-helper/assets/5312805/ed64a578-1bb9-4799-8409-8ebfcc950dd1">

Secondly, I don't know whether the brightness problem is related. I can change brightness in Eco mode or when boot up with standard mode. But I can't change brightness anymore if I try to change from Eco to Standard.

**Comment by Halry** [comment]
It seems to run the powershell command will be able to disable dGPU, but still no luck with brightness control, even with dGPU disabled. 
<img width="1096" alt="image" src="https://github.com/seerge/g-helper/assets/5312805/40509aa2-5bad-4f93-9677-bae7a0b08539">

And then will not able to wake the dGPU up.
<img width="724" alt="image" src="https://github.com/seerge/g-helper/assets/5312805/f60f537f-0010-4fca-97be-5b5fdce0bc09">

**Comment by Halry** [comment]
After I terminated the GHelper and then restarted it, it would show the laptop was in Standard mode ,but hwinfo showed dGPU was detached. However device manager showed the dGPU was still attached.

It might more easy if we can just control the nvidia control panel to force iGPU instead of control ACPI
<img width="303" alt="image" src="https://github.com/seerge/g-helper/assets/5312805/53432eaa-372b-4210-898a-e4993b6978d8">

**Comment by seerge** [comment]
@jacob-devel hello, did you had a chance to check if this is connected to using / not using optimus as i asked in first message? :)

**Comment by Halry** [comment]
> @Halry I would recommend to do a "clean" test.
> 
> Make sure you use latest version https://github.com/seerge/g-helper/releases (i.e. 0.92 or at least 0.91)
> 
> 1. Do a hard-reset of your laptop (it won't touch any data just in case). Turn it off, then press and hold power button for 30 seconds, then boot normally. It should reset all this switches into default states - i.e. enable GPU (it also helps when your wifi adapter hangs or so :)
> 2. After fresh reboot make sure GPU is in Standard mode (i.e. simply enabled).
> 3. Set NVidia display mode to "Optimus" explicitly
> 4. Then try to disable GPU, enable it back, check if brightness works :)
> 
> As according to this topic #660 and @GibStorm (who experienced it), brightness issue seem to be connected with not using Optimus (i.e. turning GPU off in a moment when it actually drives display).
> 
> P.S. I don't own 2023 device so I simply rely on what other people write here :)

Unfortunately, brightness control still won't work correctly. And then switch back to Eco mode will cause ghelper hanged then  popup a dialog ask me to restart the dGPU. However, it won't work and laptop stuck in hybrid mode. And of course dGPU still working.

I am pretty busy these days, I will install the ASUS software ASAP to try whether they disable dGPU for real or not. Seems dGPU will stuck if try to switch on and then off. Maybe the problem only occur if use nvidia dGPU together with AMD iGPU. Rarely reported by intel user.

**Comment by Halry** [comment]
Thank you, I would rather stick with GHelper than using these ASUS apps.

**Comment by Kojunwon** [comment]
good news for g14 2023,
asus updated bios 309 to 310.
this bios update fixed switching issue that was talking here.
now everything works good.
hooray!

**Comment by seerge** [comment]
@Kojunwon that's a good news!  @Halry  @jacob-devel  does it apply to you as well ?

**Comment by Halry** [comment]
> @Kojunwon that's a good news! @Halry @jacob-devel does it apply to you as well ?

Yes, all problems have gone. I think this issue can be closed.

**Comment by frackerinho** [comment]
Hi, i've the same issue on my 2022 model with bios 318 and 0.91 ver of ghelper, instantly changes to silent mode but takes time to change back to balanced, if you will try to do that "very often", in case of testing, you can simply break the switching and it will stuck on silent/balanced when it shouldn't be.

**Comment by seerge** [comment]
@frackerinho hello, i don't think your case is related:) turning gpu on or off indeed takes some time, as this is how bios works (run powershell commands from my first comment here and you will see it by yourself)

**Comment by seerge** [comment]
Closing this, as it seem to be resolved for everyone with same/similar issues on 2023 models by updating to latest bios 310 and an issue starter simply don't respond.

**Comment by Sawa-i** [comment]
Hi, I have Bios 329 on my Asus Rog Strix G713PV ( 2023 ).

I seems to have this 'Freeze and restart'  randomly at times. Suspected issue to be either 'AMD driver ( iGPU) '  related or interaction between ' iGPU & dGPU '.

Using Ultimate mode ( dGPU Exclusively) doesn't seem to cause that problem ( Though only observed for 2 days only as of now).

Wonder anyone else having related issues?

More Details:
Sometimes observed blue screen and sometimes not:
- Blue screen may had:
-- An error like this : IDEO DXGKRNL FATAL ERROR  ( Not sure exactly )
-- Sometimes : Clock WatchDog TimeOut

Also the freeze and restarts happened randomly, regardless of using dGPU, playing games, or just simply using laptop. ( Regardless of GPU Mode ( except Ultimate ofcourse )

**Comment by invcble** [comment]
> Hi, I have Bios 329 on my Asus Rog Strix G713PV ( 2023 ).
> 
> I seems to have this 'Freeze and restart' randomly at times. Suspected issue to be either 'AMD driver ( iGPU) ' related or interaction between ' iGPU & dGPU '.
> 
> Using Ultimate mode ( dGPU Exclusively) doesn't seem to cause that problem ( Though only observed for 2 days only as of now).
> 
> Wonder anyone else having related issues?
> 
> More Details: Sometimes observed blue screen and sometimes not:
> 
> * Blue screen may had:
>   -- An error like this : IDEO DXGKRNL FATAL ERROR  ( Not sure exactly )
>   -- Sometimes : Clock WatchDog TimeOut
> 
> Also the freeze and restarts happened randomly, regardless of using dGPU, playing games, or just simply using laptop. ( Regardless of GPU Mode ( except Ultimate ofcourse )

@Sawa-i Were you able to fix this somehow? I am having the same problem now after it running flawless for 3 years in GA402XV
