### ISSUE TITLE
cpu speed drop after every reboot on battery

### ISSUE THREAD

**Issue by yesnt10** [seerge/g-helper#681]
Hello. When I restart my computer while it is not charging, the cpu does not exceed 1 ghz. I have to put it back into optimized mode every time. Can you do anything to prevent this? Maybe for the computer to process it into its memory.

**Comment by yesnt10** [comment]
I know this is not a problem of g-helper. A problem of the Asus tuf f15 model. There has been a lot of discussion on Reddit. But I wanted to ask if maybe it can be solved.

**Comment by seerge** [comment]
@yesnt10 well, i'm not aware of that :) and i doubt such things can be solved on application level (looks more like a bios issue?) mb older bios for your model doesn't have that ?
