### ISSUE TITLE
[Feature Request] Add "Maximum Processor Frequency" to profile settings

### ISSUE THREAD

**Issue by secorlade** [seerge/g-helper#682]
**Is your feature request related to a problem? Please describe.**
I have a Zephyrus Duo 2023 and AMD in their infinite wisdom decided that this laptop's APU (Ryzen 9 7945HX) should always run overclocked (frequencies of 5000+ MHz)
I would like to manage the maximum frequency for the APU per profile for multiple reasons (working vs watching movies vs gaming vs etc.)

**Describe the solution you'd like**
Add a new entry to manage "Maximum Processor Frequency"

**Describe alternatives you've considered**
I tried lowering "CPU Slow" / "CPU Fast" but without success. When I reach the values I want, the laptop becomes sluggish and keeps freezing even with menial tasks (e.g. moving windows from one screen to another - using multiple displays).

**Additional context**
My suggestion would be that the new entry should go under "CPU Boost" since they're very strongly related.
![image](https://github.com/seerge/g-helper/assets/3169451/684b877b-3de3-4a86-b219-290b6594b7b2)

Apologies if this was requested before and declined, I did not have time to through all the issues.

**Comment by seerge** [comment]
@secorlade hello,

I don't think that's possible to control max frequency directly.

What you can try to do is either completely disable CPU boost (then it will stay on normal clock) or also set windows power mode to battery efficient (or just click "silent" in the app), in that mode windows tames CPU a bit.

**Comment by seerge** [comment]
Closing this one, as there is nothing I can do besides advices from previous post :)
