### ISSUE TITLE
Charge Percentage Notification/Pop-Up When Limit Reached

### ISSUE THREAD

**Issue by ahandlen** [seerge/g-helper#684]
Would it be possible to include an OSD notification for when set battery % is reached when charging through USB-C?

Due to the behavior of USB-C charging it would be nice to know when set % is reached to then unplug and not charge cycle battery when draw is too high.

**Comment by seerge** [comment]
@ahandlen hello, but I'm not a big fan of too many popups to be honest :) generally speaking charging should stop when limit is reached (but it's controlled by hardware ofc)
