### ISSUE TITLE
GPU Temperature

### ISSUE THREAD

**Issue by lucidnx** [seerge/g-helper#69]
Hello! I see CPU Temperature and both CPU and GPU fan RPM but no GPU temp. is that meant to be like that? Can you add it?

**Comment by seerge** [comment]
I was already answering this. To get GPU temps i need to incorporate https://github.com/LibreHardwareMonitor/LibreHardwareMonitor inside (i had it in early versions), but that will require admin permissions, which i don't want to do for app.

Main question why you guys want to see GPU temp in app that is not a gaming overlay? cause when not in game, GPU is usually cool. And when you are in game - you need something more dedicated like AMD/Nvidia overlay or MSI afterburner ...

**Comment by lucidnx** [comment]
I don't want to monitor temps all the time, but sometimes I do, I am using PowerToys to keep GHelper always on top. It's not something serious, I have just wondered why there is CPU and not GPU. I see now.

**Comment by ZimM-LostPolygon** [comment]
https://github.com/seerge/g-helper/pull/74

**Comment by seerge** [comment]
@lucidnx you can celebrate thanks to @ZimM-LostPolygon 's pull request https://github.com/seerge/g-helper/releases/tag/v0.26

**Comment by lucidnx** [comment]
Oh Nice! :) I can see it only when dGPU is in use, is that expected behavior?

**Comment by ZimM-LostPolygon** [comment]
Yup! Armoury Crate worked like that for me as well. dGPU needs to be at least present in device manager.

**Comment by lucidnx** [comment]
It is present in device manager, just temperature is not shown until dGPU is in use.

**Comment by ZimM-LostPolygon** [comment]
What model is it? In any case, does Armoury Crate work differently?

**Comment by lucidnx** [comment]
GA402RK-L8150W, I am not sure about Armoury crate, but I think it was shown when non-eco mode was selected. HWInfo can show these values even when GPU is not in use, it's not something mandatory, just asking, in case it's not expected.

**Comment by ZimM-LostPolygon** [comment]
Ah, so it's an AMD GPU. It is likely an easy fix, unfortunately I have the 2021 model G14, with Nvidia GPU, so I can't really fix it on my own...
