### ISSUE TITLE
Asus ROG G531GT iGPU + dGPU Support?

### ISSUE THREAD

**Issue by jaycc3000** [seerge/g-helper#691]
Core i7-9750H, Intel UDH 630, GTX 1650 (4GB) Running Windows 11 (22H2)

I see the "Stop GPU Applications" button but it does not appear to work. Is there anything I can provide to assist? I do not have any ASUS frameworks or packages installed according to Apps -> Programs. This was a clean install of Windows this past April; I believe something from Asus may have auto downloaded through Windows Updates. If so, I would have removed it.

**Comment by jaycc3000** [comment]
Added method 1 and 2 dumps:

https://github.com/seerge/g-helper/issues/38#issuecomment-1610104556

**Comment by seerge** [comment]
@jaycc3000 hello. Stop GPU applications just tries to kill all apps that use GPU according to NVidia API. 

You can check %appdata%/ghelper for log and see what apps it tries to kill :) To be sure, you may want to run g-helper as admin (as some apps that can be killed may require admin permissions)

**Comment by seerge** [comment]
@jaycc3000 as for the "rest" to "support" i think everything that can be done to your laptop should be already working :) at least i see that your laptop should support 3 main modes (+ probably fan curves) , refresh rates, some backlight controls, hotkeys, etc :) 

There is (obviously) no GPU switch for your model and no power limits, cause your model doesn't support that in a first place :)

**Comment by jaycc3000** [comment]
Thank you for taking the time to explain. I do appreciate it! Everything works as it should then.

I have the basic 60hz 1080p screen. There was a higher-end option afaik, so I do not have the refresh rate options:

![Screenshot 2023-06-27 154508](https://github.com/seerge/g-helper/assets/134714634/3b5e4787-ddb8-4cb4-8efe-d9ae627c7c74)

You can safely ignore the attached log file, just posted for posterity :-)
[log.txt](https://github.com/seerge/g-helper/files/11886672/log.txt)

**Comment by seerge** [comment]
@jaycc3000 ok, then i'm glad that UI processes  your 60hz-only screen correctly, and hides whole block then :) 

Your screenshot is probably the most trimmed version of how g-helper can look like :) but that depends on a device of course.

Do fan curves work ?

**Comment by jaycc3000** [comment]
"ASUS BIOS rejected fan curve"

clean log here:
(archived the old log and restarted G-Helper as admin, again)

[log.txt](https://github.com/seerge/g-helper/files/11886743/log.txt)

**Comment by seerge** [comment]
@jaycc3000 oke, then it's not supported :)

**Comment by jaycc3000** [comment]
Thanks again for your time and thank you for being so thorough!

I can't complain about missing features! I got this like-new with 2 OEM chargers, 1TB NVME, 32GB of DDR4 ram for $650 in 2020.
