### ISSUE TITLE
M1 Key would occasionally not work

### ISSUE THREAD

**Issue by justinlee1687** [seerge/g-helper#697]
**Describe the bug**
Ever since V0.80 (last one with this fully working was V0.79), the M1 key would occasionally not work. I've tried binding the key to other actions with no difference. 

**Clear scenario to Reproduce**
1. Play Audio
2. Occasionally try to adjust volume. At some point, the volume up and mute key will work fine but the volume down key will not work.
4. Seems to be able to mitigate by switching audio source occasionally. Usually would need to volume up then clicking a lower volume to work around problem. I have tried to toggle "process fn+f hotkeys without fn", which also fixed the bug for a day until I slept the laptop and used it the next day.

**Expected behavior**
The M1 key should perform the action specified in G-Helper, with the default action being volume down.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11900500/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Model: G14 2021, Ryzen 9 5900S, GTX 3060

**Asus software**
- Armoury crate uninstalled, all ASUS services stopped
- MyASUS installed

**Additional context**
The cut-off was determined to be v0.79 as the problem appeared the same day I installed 0.80 when it was first released. I waited to report as it was not exactly as reproducible as I wanted it to be.

**Comment by seerge** [comment]
@justinlee1687 hello, I honestly don't think it's related to g-helper by very simple reason - M1/M2 emit volume control keys on hardware level :) (so app doesn't intercept / touch them anyhow). You can simply quit g-helper and m1/m2 keys will keep working (while m3 and m4 will stop)
