### ISSUE TITLE
[Bug] "GPU Mode" "Eco" do not apply

### ISSUE THREAD

**Issue by marcelomijas** [seerge/g-helper#70]
Hi. I cannot change GPU mode from "Standard" to "Eco".

Clicking "Eco" takes effect (at least visually) for less than a second and then automatically goes back to "Standard". It doesn't matter if I am on battery or charging.

![ezgif-1-384278d3a6](https://user-images.githubusercontent.com/62946623/224518789-c81ff8e0-d761-4a92-b0be-dec90e67633f.gif)

Specs: Windows 10 22H2, G14 2020 (Ryzen 7 4800HS and RTX 2060).

Sorry for the inconvenience, again T.T

**Comment by seerge** [comment]
You have a 2020 model, there dGPU can't be disabled at all :) It didn't work for you before neither 
The only thing i have added in new version of the app, is an actual check if dGPU has switched off after button click.

There is literally other topic about https://github.com/seerge/g-helper/issues/67 :)

**Comment by marcelomijas** [comment]
Ok, I understand. :)

Thanks a lot!
