### ISSUE TITLE
Battery Charge Limit not working

### ISSUE THREAD

**Issue by ahamToxic** [seerge/g-helper#700]
I have Asus Tuf A15 (2021). I don't use any software provided by Asus except MyAsus app.
When i use debloat.bat file gives by you which works perfectly fines but after running it my battery always get fully charged. (I always set it to 80% in g-helper and myasus both)

**Comment by seerge** [comment]
@ahamToxic hello, attach a log at least.  But in general I can link you to this FAQ item
https://github.com/seerge/g-helper#battery-charge-limiter-is-not-working
