### ISSUE TITLE
Feature request: Make "Optimized" mode disable "Ultimate" mode

### ISSUE THREAD

**Issue by AudreyAP** [seerge/g-helper#703]
**Is your feature request related to a problem? Please describe.**
Exiting Ultimate mode requires that the user click on "eco" or "standard", reboot, then select "optimized" if they would like to use the optimized mode. This means a couple of extra clicks and could result in a second GPU mode swap, which can slow down the user experience. 

**Describe the solution you'd like**
When the user selects "Optimized" mode, GHelper should prompt the user to exit Ultimate mode, just like Eco and Standard do currently.

**Comment by seerge** [comment]
@AudreyAP hello, this build should do the thing 
[GHelper.zip](https://github.com/seerge/g-helper/files/11919031/GHelper.zip)

**Comment by seerge** [comment]
Live in https://github.com/seerge/g-helper/releases/tag/v0.93 :)

**Comment by AudreyAP** [comment]
Thanks once again - you're the best.
