### ISSUE TITLE
GPU memory overclock numbers

### ISSUE THREAD

**Issue by RaZer0k** [seerge/g-helper#704]
I set a 100 Mhz overclock to my Asus GV301RC but when i check the use clock memory only show 15 Mhz more, the GPU core work great but memory dont overclock with the correct value.

1. Go to 'Fans + Power' -> 'GPU'
2. Increase GPU Memory Clock 
3. Run a 3D application in parallel run GPU-Z
4. Check memory and core clock default and used to see if they apply correctly

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Laptop Flow X13 GV301RC BIOS 325

![image](https://github.com/seerge/g-helper/assets/10209770/0274d05e-6d8c-4481-bf66-5bf625bab75e)
[log.txt](https://github.com/seerge/g-helper/files/11919707/log.txt)

**Asus software**
- Armoury crate (removed)
- MyASUS installed (removed)
- debloat.bat executed

**Additional context**
I'm using Asus Xg Mobile 3070

**Comment by seerge** [comment]
@RaZer0k hello,

In a log i see that driver accepts your values and then responds with them (when app reads clocks). So it sets everything correctly. Rest is up to your system

```
30-06-2023 14:40:47: GET GPU CLOCKS: 50, 60
30-06-2023 14:40:47: SET GPU CLOCKS: 50, 150
30-06-2023 14:41:01: PowerLimit C0 = 25 : OK
30-06-2023 14:41:01: PowerLimit C2 = 87 : OK
30-06-2023 14:41:01: GET GPU CLOCKS: 50, 150
30-06-2023 14:41:01: SET GPU CLOCKS: 50, 100
30-06-2023 14:43:21: Key: 56
30-06-2023 14:49:26: GET GPU CLOCKS: 50, 100
```
How high will it go, depends on lots of things (limits in vbios, for thermals, voltage , etc) Try to do same overclock using afterburner, do you get same results?

**Comment by RaZer0k** [comment]
![image](https://github.com/seerge/g-helper/assets/10209770/0d7fb1b5-ee17-47c0-8c0b-a53422d32f33)

Yes like you say it... GPU-Z report different...Afterburner report 7100 Mhz in memory soo base is 7000 and add 100 is correct.

**Comment by seerge** [comment]
Great
