### ISSUE TITLE
Switching custom windows power plans

### ISSUE THREAD

**Issue by Ctere1** [seerge/g-helper#711]
**Describe the bug**
I want to set custom windows power plans with each mode as you [mentioned](https://github.com/seerge/g-helper#custom-windows-power-plans-with-each-mode) for setting up the max processor state but it creates a new config. I am pretty sure that config JSON is correct. (using VSCode, there is no extra or missing coma)

**Clear scenario to Reproduce**
1. Open the config JSON
2. Paste the following format (I replaced these GUIs with mine)
```
"scheme_0": "00000000-0000-0000-0000-000000000000",
"scheme_1": "ded574b5-45a0-4f42-8737-46345c09c238",
"scheme_2": "961cc777-2547-4f9d-8174-7d86181b8a7a",
```
3. Save the file
4. Try to change the power mode from GHelper
5. You can see that config is re-created and could not switch the windows power mode.

**Expected behavior**
Should be switch windows power plans with each mode

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11928468/log.txt)

**Screenshots or screencasts**
_As you can see there is no problem with JSON_     

![Screenshot 2023-07-02 051233](https://github.com/seerge/g-helper/assets/62745858/8f75751e-c15d-493e-8993-5db9c58a379e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop: Zephyrus M15
 
**Asus software**
- Armoury crate **not** installed
- MyASUS installed

**Additional context**
Or is there a point I missed for this configuration?
Also thank you so much for such a awesome tool!!

**Comment by seerge** [comment]
@Ctere1 hello, can you post your config here?

**Comment by seerge** [comment]
@Ctere1 by the way, i hope it's obvious. But before editing config you need to quit g-helper, edit file, and run it again :) as it reads config on start.

**Comment by Ctere1** [comment]
Hey @seerge I think that was the problem yes, I need to close GHelper before changing the config. Thank you very much indeed!!

**Comment by killstreak28** [comment]
@Ctere1 can you please tell me how to get the GUIs for the power plans
