### ISSUE TITLE
Asus Noise Cancellation Utility

### ISSUE THREAD

**Issue by yohannesakd** [seerge/g-helper#715]
Would it be possible to implement the Noise Cancellation Utility found in Armory Crate within this software, it would be a great feature. It's the best Noise Cancellation software I've ever used and I was sad to lose it when I dropped Armory Crate.

**Comment by seerge** [comment]
@yohannesakd hello, this is a duplicate / intersection of https://github.com/seerge/g-helper/issues/18

In short - it's not possible, as that part is proprietary. But on some newer models, you can check Realtek Control panel for possible options (if they are available there)

**Comment by yohannesakd** [comment]
Thank you for the quick response. If I could ask about the software, is the Undervolting implementation in G-Helper the same as in AATU?

**Comment by seerge** [comment]
@yohannesakd yes, g-helper uses UXTU's library for undervolting, so it should be the same theoretically :)

**Comment by yohannesakd** [comment]
Thank you!
