### ISSUE TITLE
Incorrect energy limits on G713QY

### ISSUE THREAD

**Issue by BatryXA008** [seerge/g-helper#716]
When setting a limit on gpu 150W in games, I get a limit of 120W, with 190 laid down by the manufacturer. 

In version 86, it was possible to set up to 250W on the gpu and 100 on the cpu, which was very convenient, please return this for my laptop version.

**Comment by seerge** [comment]
@BatryXA008 just realized there is a 17 inch model, not only 15th (which had different max slider values)

check this build

[GHelper.zip](https://github.com/seerge/g-helper/files/11938706/GHelper.zip)

**Comment by BatryXA008** [comment]
![image](https://github.com/seerge/g-helper/assets/138510085/201818eb-69ce-42c9-a1ab-145b0159e624)

I'll check in the games a little later, otherwise there is no opportunity now

**Comment by BatryXA008** [comment]
![image](https://github.com/seerge/g-helper/assets/138510085/3228207e-5059-4c83-a3e6-125444c6592d)
there is also a bug
that the GPU fans are not forcibly turned on, and the vrm zone is heated until the 3D application is turned on
