### ISSUE TITLE
Crash when scheduling auto-start when run without Admin privileges

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [seerge/g-helper#72]
Creating a new task in task scheduler requires admin rights. However, G-Helper doesn't do any checks and crashes at start:

![изображение](https://user-images.githubusercontent.com/928550/224662743-93d63b88-0a4d-43a5-9b86-fc4c18f1901b.png)

**Comment by seerge** [comment]
In general it doesn't require admin permissions. Do you have any special restricting policies set mb ?

**Comment by seerge** [comment]
Great,

- GSharpHelper is a leftover from old version of the app (that required admin permissions). You can safely remove that.
- I'll add a limit, thanks :)

**Comment by seerge** [comment]
Added in v0.25, also app won't run scheduler every time it starts.

**Comment by ZimM-LostPolygon** [comment]
@seerge Hm, I don't see `td.Settings.ExecutionTimeLimit = TimeSpan.Zero;` being added in the latest version :)

https://github.com/seerge/g-helper/blob/main/Startup.cs

**Comment by seerge** [comment]
Code wasn't pushed on that moment, but v0.25 has that change already :)

**Comment by ZimM-LostPolygon** [comment]
OK, I've debugged it, and yes, basically, what was happening is that GHelper tried to create the task, even when it already existed, due to the flaw in logic. The latest version fixes it :)
