### ISSUE TITLE
ROG G14 2023 GA402XV 

### ISSUE THREAD

**Issue by KizzWang** [seerge/g-helper#723]
Failed to set the Fn lock of the screenshot function.
Regardless of whether the Fn lock is on or off, the screenshot function (F6) requires pressing Fn to take a screenshot.

**Comment by seerge** [comment]
@KizzWang With FN-Lock on F6 emits a PrintScreen key (that would by default make a screenshot in your clipboard), you can adjust that in windows settings https://pureinfotech.com/set-print-screen-key-screenshot-screen-sketch-windows-10/
