### ISSUE TITLE
Update 0.91 breaks x13 tablet/tent mode

### ISSUE THREAD

**Issue by narker** [seerge/g-helper#725]
I recently updated my flow x13 from 0.84 to 0.91. The option to disable the trackpad in tent/tablet modes seems to have disappeared.

**Comment by seerge** [comment]
@narker what do you understand under "option" ? Hotkey FN+F10 that disables trackpad ?

**Comment by narker** [comment]
It seems to have been a one-off issue. I restarted the computer and it's working fine now.

**Comment by seerge** [comment]
Great 👍
