### ISSUE TITLE
2-in-1 laptops: add toggles to enable/disable keyboard, touchpad and lock / unlock rotation.

### ISSUE THREAD

**Issue by Yury-M-Leh** [seerge/g-helper#726]
**Is your feature request related to a problem? Please describe.**
Maybe it's a niche case but when I watch series on my Flow X16 I'd sometimes lie down & turn it on the side without folding it. It interprets it as going into a tablet mode and disables its keyboard, trackpad and rotates the screen which is not a desired behaviour for this usecase.

**Describe the solution you'd like**
I'd like to have a section to be shown in g-helper when it's used with convertible laptops with at least three buttons:
Keyboard on/off
Touchpad on/off
Rotation lock/unlock

Also maybe rotate clockwise & rotate counterclockwise but it might be excessive at this point although welcome

**Describe alternatives you've considered**
There's a rotation lock/unlock in the windows submenu so it can be used from there but then if you want to toggle on/off keyboard and/or touchpad you'd still open g-helper so why not have it there.

And thank you very much for this amazing tool, seerge!

**Comment by seerge** [comment]
@Yury-M-Leh hello, g-helper doesn't lock your keyboard and rotate screen when laptop goes into tablet mode. I think windows handles that. And as far as I remember you can control that via windows popup (that appears when you click on battery icon in tray).

As for disabling touchpad - on entering tablet mode. This is something that AC was indeed doing, and therefore (according to multiple requests here) i have also implemented. So as soon as app gets a notification from asus-driver that tablet mode changed, it correspondingly toggles touchpad :)

But keep in mind that you can always just enable it back by pressing FN+F10 ?

**Comment by seerge** [comment]
> Yes but there's only a rotation lock.
I see, but I also don't know how to control that :) (it's not part of asus implementation / software)
> So maybe make it a toggle-able behaviour in Extra -> Other? Add a checkbox called 'Disable touchpad on entering tablet mode'?
I can add it as an optional ``config.json`` entry (as this is very specific thing), but what the sense of having touchpad working but not keyboard? :)

**Comment by seerge** [comment]
@Yury-M-Leh can you try this build where i have (temporarily) disabled touchpad toggle thing completely ?

[GHelper.zip](https://github.com/seerge/g-helper/files/11951450/GHelper.zip)

Does keyboard still got disabled? Cause if it does, it's definitely controlled on windows or on BIOS level (not by app). So I simply don't know how to turn it back on (and therefore keeping only touchpad ON wouldn't have much sense as for me)

**Comment by Yury-M-Leh** [comment]
@seerge 
> Does keyboard still got disabled? Cause if it does, it's definitely controlled on windows or on BIOS level (not by app). So I simply don't know how to turn it back on (and therefore keeping only touchpad ON wouldn't have much sense as for me)

I can tell you that by simply exiting the app and then rotating the laptop the keyboard gets disabled but the touchpad remains enabled. 

> So I simply don't know how to turn it back on (and therefore keeping only touchpad ON wouldn't have much sense as for me)

I'd greatly appreciate if I could keep at least the touchpad on in this scenario without quitting G-helper by making it optional.

**Comment by seerge** [comment]
@Yury-M-Leh check this build

Prior to running it , add following line in the beginning of ``%appdata%\ghelper\config.json`` : 

```disable_tablet : 1,```

[GHelper.zip](https://github.com/seerge/g-helper/files/11955589/GHelper.zip)
