### ISSUE TITLE
Application Does not Launch

### ISSUE THREAD

**Issue by HiveMynd148** [seerge/g-helper#727]
Description: A .NET application failed.
Application: GHelper.exe
Path: D:\GHelper.exe
Message: A JSON parsing exception occurred in [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.7\Microsoft.WindowsDesktop.App.runtimeconfig.json], offset 0 (line 1, column 1): The document is empty.
Invalid framework config.json [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.7\Microsoft.WindowsDesktop.App.runtimeconfig.json]

This is happening out of nowhere because the software did work a few days ago.
I have Deleted and Reinstalled the application since then as well as use the .NET Repair Tool.

**Comment by seerge** [comment]
@HiveMynd148 hello, it says that .NET library (the one you have installed) can't read app config by some reason.

1. Try to delete (completely) ``config.json`` from  ``%appdata%\GHelper`` folder (and then fresh start app)
2. If it doesn't help - try to download/install latest https://dotnet.microsoft.com/en-us/download/dotnet/7.0

**Comment by HiveMynd148** [comment]
I have dome both of the above but to no effect.

**Comment by HiveMynd148** [comment]
> I have dome both of the above but to no effect.

Correction, It works now after installing .net again.

**Comment by seerge** [comment]
@HiveMynd148 Great, probably your .Net installation was corrupt in the first place.

Closing as completed then
