### ISSUE TITLE
keyboard lighting  problem on TUF Dash F15 FX517ZR.

### ISSUE THREAD

**Issue by Simon-666** [seerge/g-helper#730]
**can't control the keyboard lighting on TUF Dash F15 FX517ZR.**

**to Reproduce**
1. Go to Ghelper 
2. Click on any button to control the laptop keyboard
3. Nothing happens

**Expected behavior**
the lighting should change 

**App Logs**

5/7/2023 12:47:19 PM: USB-KB : not found
5/7/2023 12:47:19 PM: TUF RGB = B4-01-FF-FF-FF-E1-00-00-00-00-00-00 : 0
5/7/2023 12:47:20 PM: USB-KB : not found
5/7/2023 12:47:20 PM: TUF RGB = B4-00-FF-FF-FF-E1-00-00-00-00-00-00 : 0
5/7/2023 12:47:22 PM: USB-KB : not found
5/7/2023 12:47:22 PM: TUF RGB = B4-00-FF-00-00-E1-00-00-00-00-00-00 : 0

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model ASUS TUF Dash F15 FX517ZR.

**Asus software**
only Ghelper
  
**Additional context**
I know that the laptop only has one color but I want to change the mode

**Comment by seerge** [comment]
@Simon-666 hello, i see that you try to change backlight color / mode (and it doesn't seem to be supported on your model as bios doesn't accept it)

Do brightness controls work (FN+F2/F3) ?

**Comment by Simon-666** [comment]
hey there 
yeah the slider work s and the shortcut
the problem my internet is bad so I can't download Armory crate

**Comment by seerge** [comment]
@Simon-666 most probably modes are also not supported on your device. Does selecting Static or Strobe change anything ? If not - then this is how it is probably :)

**Comment by Simon-666** [comment]
@seerge Yeah it doesn't is there any way to change the mode other than armoury crate cause I can't install it because of the internet

**Comment by seerge** [comment]
@Simon-666 AC is the only reliable way as it comes from manufacturer:)

**Comment by Simon-666** [comment]
@seerge thanks man
