### ISSUE TITLE
Add tool tip for each CPU Boost type

### ISSUE THREAD

**Issue by BChip** [seerge/g-helper#731]
**Is your feature request related to a problem? Please describe.**
It would be helpful for users to have some kind of description/tooltip for each CPU boost type. Most people don't know what aggressive vs efficient enabled vs efficient aggressive means.

On reddit, someone tried describing each of these the best they could:

- enabled: Just tries to boost a little more out of your CPU, if your CPU is hot or some problem occurs, well it's back to low GHz
- aggressive: Just tries to boost a little more out of your CPU, if your CPU is hot or some problem occurs, it will make the fans go faster to get more out of your CPU. also this consumes more power EVEN when idling and your system is doing nothing.
- enabled efficient: It will do the same thing as enabled only thing is, it might try to use less power
- aggressive efficient: It will do the same thing as aggressive although try to use as less power as possible

**Describe the solution you'd like**
Add a tool tip to describe each. 

Example code (free hand):

```csharp
        comboBoost.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        comboBoost.BorderColor = Color.White;
        comboBoost.ButtonColor = Color.FromArgb(255, 255, 255);
        comboBoost.DropDownStyle = ComboBoxStyle.DropDownList;
        comboBoost.FormattingEnabled = true;
        comboBoost.Items.AddRange(new object[] { "Disabled", "Enabled", "Aggressive", "Efficient Enabled", "Efficient Aggressive", "Aggressive at Guaranteed", "Efficient at Guaranteed" });
        comboBoost.Location = new Point(13, 12);
        comboBoost.Margin = new Padding(4);
        comboBoost.Name = "comboBoost";
        comboBoost.Size = new Size(329, 40);
        comboBoost.TabIndex = 42;

        // Add a tooltip for each item
        ToolTip tt = new ToolTip();
        comboBoost.DrawItem += (s, e) =>
        {
            string tooltip = "";
            switch (e.Index)
            {
                case 1:
                    tooltip = "Just tries to boost a little more out of your CPU, if your CPU is hot or some problem occurs, well it's back to low GHz";
                    break;
                case 2:
                    tooltip = "Just tries to boost a little more out of your CPU, if your CPU is hot or some problem occurs, it will make the fans go faster to get more out of your CPU. also this consumes more power EVEN when idling and your system is doing nothing.";
                    break;
                case 3:
                    tooltip = "It will do the same thing as enabled only thing is, it might try to use less power";
                    break;
                case 4:
                    tooltip = "It will do the same thing as aggressive although try to use as less power as possible";
                    break;
                default:
                    break;
            }
            tt.SetToolTip(comboBoost, tooltip);
        };
```

**Describe alternatives you've considered**
It doesn't have to be a tooltip. I just want descriptions in the app some how to describe these different cpu boost types.

Thank you!

**Comment by BChip** [comment]
I rewrote the description of each and I think this best for the end user to understand what each are. Any suggestions are welcome!

Disabled: Least recommended. This mode does not utilize the potential performance boost of your CPU. Useful when power consumption needs to be minimized and performance is not a concern, such as in low-demand tasks or to extend battery life.

Efficient Enabled: Provides a balance between power efficiency and performance. It tries to increase CPU frequency when needed but also prioritizes power saving. This mode could be useful in typical everyday use where you need some extra performance but also care about power consumption.

Enabled: Prioritizes performance over power efficiency by allowing the CPU to boost more often. However, it will still dial back if thermal limits are reached. This could be used when performance is more important, but you still want some thermal and power management.

Efficient Aggressive: Provides boosted performance while still caring about energy efficiency. It's more aggressive than "Enabled" but tries to limit the power usage. This might be suitable for heavier tasks where performance is needed, but you want to manage power usage.

Aggressive: Most recommended for high-performance scenarios where power consumption is a lesser concern. The mode allows the CPU to boost as much as possible, and it speeds up the fans to keep the CPU cool. This mode is best suited for demanding tasks, like gaming or heavy computational work, where achieving the highest possible performance is the priority, and you're less concerned about power usage or fan noise.

**Comment by seerge** [comment]
@BChip hello, thanks for idea :) Honestly, in my personal experience (on 6900HS) all boost modes except disabled seem to behave super similar to each other in both synthetic benchmarks and real-life usage :) 

I personally was linking this reddit post here before when people asked about differences https://www.reddit.com/r/WindowsHelp/comments/u1egv5/differences_in_cpu_performance_boost_modes_in_the/

But based on feedback from different users, it seems like for different CPUs (especially Intel vs AMD) boost behavior differs and depends on how windows / chipset drivers / bios / anything else handle that. 

So I simply don't have universal and clean explanation for each case. And giving something general will lead to people coming back and reporting it as a "bug" when boost doesn't do exactly what is described
