### ISSUE TITLE
Touchpad layout shows ON when I turn it off for the first time.

### ISSUE THREAD

**Issue by kuonji-arisu** [seerge/g-helper#732]
1. turn off G-Helper with touchpad on
2. press FN+F10 
3. layout show "ON" but actually disabled

**Expected behavior**
layout shows "OFF"

**Asus software**
- Armoury crate not installed
- MyASUS not installed
- no other Asus services running in background

**App Logs**
```
2023/7/6 11:07:46: WMI event 107
2023/7/6 11:07:53: WMI event 107
2023/7/6 11:07:56: WMI event 107
2023/7/6 11:07:57: WMI event 107
2023/7/6 11:09:12: ------------
2023/7/6 11:09:12: App launched: ASUS TUF Gaming F15 FX507ZM_FX507ZM :0.95.0.0zh-CN
2023/7/6 11:09:12: NVIDIA GeForce RTX 3060 Laptop GPU
2023/7/6 11:09:13: CPU: -1 - 12th Gen Intel(R) Core(TM) i7-12700H - Intel64 Family 6 Model 154 Stepping 3
2023/7/6 11:09:13: AutoSetting for Online
2023/7/6 11:09:14: Input device not found
2023/7/6 11:09:14: Mode = 0 : OK
2023/7/6 11:09:14: Eco flag : 0
2023/7/6 11:09:14: Mux flag : 1
2023/7/6 11:09:14: ScreenOverdrive = 0 : OK
2023/7/6 11:09:14: BatteryLimit = 100 : OK
2023/7/6 11:09:14: BatteryLimit = 100 : OK
2023/7/6 11:09:14: TUF Brightness = 129 : OK
2023/7/6 11:09:14: Monitor Power On
2023/7/6 11:09:17: Latest version 0.95.0.0
2023/7/6 11:09:23: WMI event 107
2023/7/6 11:09:25: WMI event 107
```

**Desktop (please complete the following information):**
 - OS: 11
 - Laptop model: tuf gaming 15 FX507ZM

**Comment by kuonji-arisu** [comment]
Update: It seems that this problem does not only occur after the first launch of GHelper, but also after a period of time without triggering FN+F10.

**Comment by seerge** [comment]
@kuonji-arisu does a switch work in general? I thought on asus TUF models touchpad toggle were ignored ? :)

**Comment by kuonji-arisu** [comment]
@seerge This problem only occurs after the first boot or a period of time without triggering FN+F10, and then it will display normally when triggered again.

**Comment by seerge** [comment]
@kuonji-arisu my question if FN+F10 actually turn touchpad off or on ? Currently app uses USB call to do that, and that seemed to work only on ROG models, not TUF

**Comment by kuonji-arisu** [comment]
@seerge actaully works, but display wrong

**Comment by seerge** [comment]
@kuonji-arisu do you have asus optimization service running?

**Comment by kuonji-arisu** [comment]
no, all asus service are disabled

**Comment by seerge** [comment]
@kuonji-arisu oke, thanks :)
currently app "reads" touchpad status from windows registry

Can you please check what do you have under ``SOFTWARE\Microsoft\Windows\CurrentVersion\PrecisionTouchPad\Status`` (especially on a first boot) ?

It should be Enabled : 1 flag there (if it's actually enabled)

**Comment by seerge** [comment]
Or check what do you have under Settings -> Bluetooth  & Devices -> Touchpad (on first boot)

https://stackoverflow.com/questions/72819528/change-windows-11-touchpad-toggle-programmatically

**Comment by seerge** [comment]
@kuonji-arisu or you can just try this build, it will write current touchpad status (from windows registry) on the moment BEFORE toggling it: 

[GHelper.zip](https://github.com/seerge/g-helper/files/11966483/GHelper.zip)

**Comment by kuonji-arisu** [comment]
The options in the registry/settings always sync with the actual state of the touchpad( after refresh registry or re-open setting page ), only the display of GHelper sometimes deviates.
After my multiple tests, this problem does not occur every time I start up ghelper, and I have not figured out its exact rules. In addition, it not only shows “ON” when it should show “OFF”, sometimes it will also reverse - this depends on the touchpad state before closing GHelper, osd layout will show same status as last time.
btw, the new build did not solve this problem.

**Comment by seerge** [comment]
@kuonji-arisu new build is not supposed to solve anything, i have just added a log entry there :) can you try to "replicate" situation and post a log after that here ? : ) thanks

**Comment by kuonji-arisu** [comment]
I haven’t reproduced the problem in the new build for now, maybe it was solved. 
By the way, the “OFF” in the layout became “OF”.

**Comment by seerge** [comment]
@kuonji-arisu that's a typo :) sorry. In new build app will try to read touchpad status AFTER toggling it, so it should be accurate. 

The reason i didn't do that in a first place, is cause windows is sometimes slow with updating a registry -> therefore it could be that actual state is changed, but registry would report old value.

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11966798/GHelper.zip)
This one should say OFF :)

**Comment by kuonji-arisu** [comment]
The layout is displayed normally now, thank you!
