### ISSUE TITLE
Keyboard-rainbow and fn key needed for turning up brightness

### ISSUE THREAD

**Issue by finweg2** [seerge/g-helper#735]
Just a couple quick issues with the latest update 0.94 that weren't happening before:

--Can't change keyboard brightness using just the "F2 and F3" keys anymore. CAN change it using the FN key. Other F keys seem to be working without FN (with option enabled in Ghelper)

--All keyboard color cycles are working with the exception of "rainbow" -- it just stays on the last type selected

-- Something cool: with the update of the bios to 308, I can easily switch between Ultimate Mode and Standard (and back) with a restart, and also the screen doesn't dim in Standard mode anymore. Just an FYI for anyone having issues.

Asus ROG Zephryus G16 2023 
app v0.94

Love Ghelper!!! Thanks for all you do!
C

**Comment by seerge** [comment]
@finweg2 hello,

I think you need to stop asus services from Extra -> Stop services first.

Can you post a log from ``%appdata%/ghelper`` after pressing F2/F3 with FN-Lock on? As I can't reproduce it (for me brightness controls work). Does running v0.91 work work for you (if you would download and run it now) ?

Rainbow mode is not supported on some devices (or does same as color-cycle), i think G16 is one of them :) so it's always been like that

Glad that 308 fixes some issuses!

**Comment by seerge** [comment]
@finweg2 but you have actually discovered another thing. When Optimization service is running, F2/F3 indeed doesn't set backlight (in FN-Lock mode), as app simply was expecting that service to handle hotkeys before.

This build should "fix" that

[GHelper.zip](https://github.com/seerge/g-helper/files/11970892/GHelper.zip)

**Comment by finweg2** [comment]
Hey Seerge,

Just stopping the ASUS services fixed everything. Rainbow is back and the f keys control the lighting without FN now. I didn't know that made any difference except for memory and stuff. ASUS can suck a phatty with all this bloatware!!! Still can't get rid of it even after all the armoury crate stopping/uninstalling.

I guess I would vote for some kind of option to stop the ASUS services when Ghelper starts each time.

Do you still need me to send logs or install the other program?

Bravo on knowing what to do!

C

**Comment by seerge** [comment]
@finweg2 if you want - you can test build that i linked here WITH asus services running :)

**Comment by finweg2** [comment]
@seerge 

It's perfect on the new build. Works with services running or stopped too.
