### ISSUE TITLE
Asus TUF F15 keyboard RGB not working

### ISSUE THREAD

**Issue by Tyflowjin** [seerge/g-helper#737]
**Describe the bug**
The RGB lights stopped working once I uninstalled Armoury Crate. I was able to use G-Helper to change the light settings while Armoury Crate was still installed. The lights do, however, still colour cycle while the laptop is in sleep mode but at no other time.

**Expected behavior**
I expect to be able to manage my keyboard RGB using the G-Helper UI which I currently cannot do.

**Desktop (please complete the following information):**
 - OS: Windows 11 Home Single Language; Version 22H2; OS Build 22621.1848
 - Laptop model: Asus TUF F15 FX506HC_FX506HC

**Asus software**
- Armoury crate = not installed
- MyASUS = not installed
- Other Asus services running in background = 0 according to G-Helper
**Other Asus software installed**
- Asus Hotplug Controller
- RefreshRateService

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11982107/log.txt)

**Comment by seerge** [comment]
@Tyflowjin try to go to Extra and uncheck/check backlight checkboxes (especially awake one)

**Comment by Tyflowjin** [comment]
@seerge unchecking "boot" did the trick. Thanks for an awesome app.
