### ISSUE TITLE
Fn+F10 cannot close the touchpad on ASUS tuf gaming f15 FX507VV. 

### ISSUE THREAD

**Issue by SanaeKochiya114514** [seerge/g-helper#738]
<img width="482" alt="image" src="https://github.com/seerge/g-helper/assets/122459414/5b0fc606-b040-481e-83b3-b08161f26f32">

Every time i use fn+f10 i cannot close the touchpad. 
Or, there may be another program on the computer that reacts the same as this program ?

**Comment by SanaeKochiya114514** [comment]
The hologram shows "off" but the touchpad still works, for every time i use fn+f10.

**Comment by seerge** [comment]
@SanaeKochiya114514 can you post a log here?

**Comment by SanaeKochiya114514** [comment]
2023/7/7 21:31:52: App launched: ASUS TUF Gaming F15 FX507VV_FX507VV :0.95.0.0zh-CN
2023/7/7 21:31:52: NVIDIA GeForce RTX 4060 Laptop GPU
2023/7/7 21:31:53: CPU: -1 - 13th Gen Intel(R) Core(TM) i9-13900H - Intel64 Family 6 Model 186 Stepping 2
2023/7/7 21:31:53: AutoSetting for Online
2023/7/7 21:31:54: Input device not found
2023/7/7 21:31:54: Mode = 1 : OK
2023/7/7 21:31:54: GET GPU CLOCKS: 0, 0
2023/7/7 21:31:54: Eco flag : 0
2023/7/7 21:31:54: Mux flag : 1
2023/7/7 21:31:54: Screen = 165Hz : OK
2023/7/7 21:31:54: ScreenOverdrive = 1 : OK
2023/7/7 21:31:54: BatteryLimit = 95 : OK
2023/7/7 21:31:54: BatteryLimit = 95 : OK
2023/7/7 21:31:54: TUF Brightness = 129 : OK
2023/7/7 21:31:54: Monitor Power On
2023/7/7 21:32:18: WMI event 107
2023/7/7 21:32:18: WMI event 107
2023/7/7 21:32:18: WMI event 107
2023/7/7 21:32:19: WMI event 107
2023/7/7 21:32:19: WMI event 107
2023/7/7 21:32:19: WMI event 107
2023/7/7 21:32:20: WMI event 107
2023/7/7 21:32:24: WMI event 124
2023/7/7 21:32:24: WMI event 124
2023/7/7 21:32:25: WMI event 124
2023/7/7 21:32:25: WMI event 124
2023/7/7 21:32:25: WMI event 56
2023/7/7 21:32:26: WMI event 56
2023/7/7 21:32:26: WMI event 56
2023/7/7 21:32:29: WMI event 197
2023/7/7 21:32:29: TUF Brightness = 128 : OK
2023/7/7 21:32:29: WMI event 196
2023/7/7 21:32:29: TUF Brightness = 129 : OK
2023/7/7 21:32:30: WMI event 196
2023/7/7 21:32:30: TUF Brightness = 130 : OK
2023/7/7 21:32:30: WMI event 196
2023/7/7 21:32:30: TUF Brightness = 131 : OK
2023/7/7 21:32:31: WMI event 197
2023/7/7 21:32:31: TUF Brightness = 130 : OK
2023/7/7 21:32:31: WMI event 197
2023/7/7 21:32:31: TUF Brightness = 129 : OK
2023/7/7 21:32:31: WMI event 197
2023/7/7 21:32:31: TUF Brightness = 128 : OK
2023/7/7 21:32:32: WMI event 197
2023/7/7 21:32:32: TUF Brightness = 128 : OK
2023/7/7 21:32:32: WMI event 196
2023/7/7 21:32:32: TUF Brightness = 129 : OK
2023/7/7 21:32:34: WMI event 196
2023/7/7 21:32:34: TUF Brightness = 130 : OK
2023/7/7 21:32:34: WMI event 196
2023/7/7 21:32:34: TUF Brightness = 131 : OK
2023/7/7 21:32:35: WMI event 197
2023/7/7 21:32:35: TUF Brightness = 130 : OK
2023/7/7 21:32:36: WMI event 196
2023/7/7 21:32:36: TUF Brightness = 131 : OK
2023/7/7 21:32:37: WMI event 196
2023/7/7 21:32:37: TUF Brightness = 131 : OK
2023/7/7 21:32:37: WMI event 196
2023/7/7 21:32:37: TUF Brightness = 131 : OK
2023/7/7 21:32:37: WMI event 197
2023/7/7 21:32:37: TUF Brightness = 130 : OK
2023/7/7 21:32:37: WMI event 197
2023/7/7 21:32:37: TUF Brightness = 129 : OK
2023/7/7 21:32:39: WMI event 179
2023/7/7 21:32:39: TUF RGB = B4-01-39-FF-39-EB-00-00-00-00-00-00 : OK
2023/7/7 21:32:39: WMI event 179
2023/7/7 21:32:39: TUF RGB = B4-02-39-FF-39-EB-00-00-00-00-00-00 : OK
2023/7/7 21:32:40: WMI event 179
2023/7/7 21:32:40: TUF RGB = B4-0A-39-FF-39-EB-00-00-00-00-00-00 : OK
2023/7/7 21:32:41: WMI event 179
2023/7/7 21:32:41: TUF RGB = B4-00-39-FF-39-EB-00-00-00-00-00-00 : OK
2023/7/7 21:32:50: WMI event 174
2023/7/7 21:32:50: Mode = 2 : OK
2023/7/7 21:32:50: Power mode: 961cc777-2547-4f9d-8174-7d86181b8a7a
2023/7/7 21:32:51: WMI event 174
2023/7/7 21:32:51: Mode = 0 : OK
2023/7/7 21:32:51: Power mode: 00000000-0000-0000-0000-000000000000
2023/7/7 21:32:51: WMI event 174
2023/7/7 21:32:51: Mode = 1 : OK
2023/7/7 21:32:51: GET GPU CLOCKS: 0, 0
2023/7/7 21:32:51: Power mode: ded574b5-45a0-4f42-8737-46345c09c238
2023/7/7 21:33:11: WMI event 181
2023/7/7 21:33:14: WMI event 181
2023/7/7 21:33:17: WMI event 181
2023/7/7 21:35:27: WMI event 107
2023/7/7 21:35:28: WMI event 107
2023/7/7 21:35:28: WMI event 107
2023/7/7 21:35:28: WMI event 107
2023/7/7 21:35:29: WMI event 107
2023/7/7 21:35:29: WMI event 107
2023/7/7 21:35:29: WMI event 107
2023/7/7 21:35:29: WMI event 107
2023/7/7 21:35:30: WMI event 107
2023/7/7 21:35:31: WMI event 107
2023/7/7 21:35:31: WMI event 107
2023/7/7 21:35:31: WMI event 107
2023/7/7 21:35:32: WMI event 107
2023/7/7 21:35:32: WMI event 107
2023/7/7 21:35:32: WMI event 107
2023/7/7 21:35:32: WMI event 107
2023/7/7 21:35:33: WMI event 107
2023/7/7 21:37:28: WMI event 56
2023/7/7 21:37:43: WMI event 56
2023/7/7 21:37:43: WMI event 56
2023/7/7 21:37:44: WMI event 56
2023/7/7 21:37:44: WMI event 56
2023/7/7 21:37:47: BatteryLimit = 100 : OK
2023/7/7 21:37:48: BatteryLimit = 95 : OK
2023/7/7 21:37:48: BatteryLimit = 90 : OK
2023/7/7 21:37:49: BatteryLimit = 85 : OK
2023/7/7 21:37:49: BatteryLimit = 80 : OK
2023/7/7 21:37:49: BatteryLimit = 85 : OK
2023/7/7 21:37:49: BatteryLimit = 90 : OK
2023/7/7 21:37:49: BatteryLimit = 95 : OK
2023/7/7 21:37:50: BatteryLimit = 100 : OK
2023/7/7 21:37:50: BatteryLimit = 95 : OK
2023/7/7 21:38:10: WMI event 124
2023/7/7 21:38:11: WMI event 124
2023/7/7 21:38:11: WMI event 124
2023/7/7 21:38:12: WMI event 124
2023/7/7 21:38:13: WMI event 124
2023/7/7 21:38:13: WMI event 124
2023/7/7 21:38:14: WMI event 124
2023/7/7 21:38:15: WMI event 124
2023/7/7 21:38:16: WMI event 124
2023/7/7 21:38:16: WMI event 124
2023/7/7 21:38:17: WMI event 124
2023/7/7 21:38:17: WMI event 124
2023/7/7 21:39:29: WMI event 56
2023/7/7 21:39:31: WMI event 107
2023/7/7 21:39:31: WMI event 107
2023/7/7 21:39:32: WMI event 107
2023/7/7 21:39:32: WMI event 107
2023/7/7 21:39:34: WMI event 107
2023/7/7 21:39:35: WMI event 107
2023/7/7 21:39:35: WMI event 107
2023/7/7 21:39:35: WMI event 107
2023/7/7 21:39:36: WMI event 107
2023/7/7 21:40:58: WMI event 56
2023/7/7 21:43:47: WMI event 107
2023/7/7 21:43:48: WMI event 107
2023/7/7 21:44:59: WMI event 56
2023/7/7 21:50:12: WMI event 56
2023/7/7 21:51:20: WMI event 56

**Comment by SanaeKochiya114514** [comment]
<img width="916" alt="image" src="https://github.com/seerge/g-helper/assets/122459414/e39f0025-1d55-4fdc-8f6d-5571df6d00ce">
I've tried to change the source code to print twice of the touchpad state after the toggle method activated, but the touchpadState is always true before or after the method activated.

**Comment by SanaeKochiya114514** [comment]
<img width="916" alt="image" src="https://github.com/seerge/g-helper/assets/122459414/9a9a3fbf-c5c8-4338-875e-6d4627094575">
The touchpadState is still true after calling the method AsusUSB.TouchpadToggle().

**Comment by seerge** [comment]
@SanaeKochiya114514 I see, as far as I remember some TUF devices doesn't seem to support current way of toggling touchpad (i.e. via USB). So for them toggle probably won't work at all :)

In linux kernel sources I have seen another "endpoint" called "touchpad" https://elixir.bootlin.com/linux/latest/source/include/linux/platform_data/x86/asus-wmi.h#L74

Can you try to run following in powershell as admin (try to replace 0 to 1 as well) : 

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00100011; Control_status=0}
```

If even that approach won't work - then on this stage I simply don't know how to disable it in your case 

But yesterday another user with TUF had it working via USB https://github.com/seerge/g-helper/issues/732

**Comment by SanaeKochiya114514** [comment]
<img width="1062" alt="image" src="https://github.com/seerge/g-helper/assets/122459414/2783f50a-d060-4177-adbf-47f9f887ed90">
@seerge This doesnt work on my device :(

**Comment by seerge** [comment]
@SanaeKochiya114514 then, this is how it is now :)

You can try to do steps from https://github.com/seerge/g-helper/issues/38 (especially submit DSDT dump) , mb we can see something interesting there

**Comment by seerge** [comment]
I'm closing this, as there is no known way to disable touchpad w/o current USB approach and known endpoints in bios :)

**Comment by SanaeKochiya114514** [comment]
@seerge
<img width="959" alt="image" src="https://github.com/seerge/g-helper/assets/122459414/b6b43156-1424-4e09-814a-84da131a8383">
I've tried the method by running the script on windows powershell.
Having opened AsusOptimization service, I tried the script twice then found the difference after switching off the touchpad. 
<img width="292" alt="image" src="https://github.com/seerge/g-helper/assets/122459414/8bc233f7-3ec4-43fb-a8a5-5aefd7c165ef">
<img width="147" alt="image" src="https://github.com/seerge/g-helper/assets/122459414/c595ec3a-a38b-4ac8-ac15-db85d64290bb">
The only difference between two outputs is on 120094. 
After switching off the touchpad the value is 34, then i swiched on it, the value changed to 33.

**Comment by SanaeKochiya114514** [comment]
<img width="165" alt="image" src="https://github.com/seerge/g-helper/assets/122459414/d86bf456-de1b-477d-b0ca-896d5726930c">
<img width="266" alt="image" src="https://github.com/seerge/g-helper/assets/122459414/4ce835ac-7bc3-4b92-a654-8f7a4f1affb6">

**Comment by SanaeKochiya114514** [comment]
120075 : ffff0000 (-65536)
120076 : ffffffffffff0000 (-65536)
120077 : ffffffffffff0000 (-65536)
12007e : 1 (1)
120091 : ffffffffffff0000 (-65536)
120092 : 0 (0)
120093 : af (175)
120094 : 33 (51)
120097 : 0 (0)
1200a0 : 0 (0)
1200a3 : 0 (0)
1200c0 : 0 (0)
1200c2 : 0 (0)
1200d2 : 806 (2054)
1200d3 : 806 (2054)
130021 : 20004 (131076)
130024 : 1 (1)
130026 : 1 (1)



__________________________________________


120075 : ffff0000 (-65536)
120076 : ffffffffffff0000 (-65536)
120077 : ffffffffffff0000 (-65536)
12007e : 1 (1)
120091 : ffffffffffff0000 (-65536)
120092 : 0 (0)
120093 : af (175)
120094 : 34 (52)
120097 : 0 (0)
1200a0 : 0 (0)
1200a3 : 0 (0)
1200c0 : 0 (0)
1200c2 : 0 (0)
1200d2 : 806 (2054)
1200d3 : 806 (2054)
130021 : 20004 (131076)
130024 : 1 (1)
130026 : 1 (1)

**Comment by seerge** [comment]
@SanaeKochiya114514 0x120094 is your CPU temp ;) 

I'm mainly interested in Method2 from that link, with a dump.

**Comment by SanaeKochiya114514** [comment]
[Uploading dsdt.txt…]()
The github cannot upload a file with .dsl so i change the suffix of the file to txt without breaking it.

**Comment by seerge** [comment]
@SanaeKochiya114514 you can just zip it :) and link is not working

**Comment by SanaeKochiya114514** [comment]
[iasl-win-20230331_0.zip](https://github.com/seerge/g-helper/files/11990911/iasl-win-20230331_0.zip)

**Comment by seerge** [comment]
@SanaeKochiya114514 can you try (both 0 or 1 as Control_status)

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00100021; Control_status=0}
```

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00130024; Control_status=0}
```

**Comment by SanaeKochiya114514** [comment]
> @SanaeKochiya114514 can you try (both 0 or 1 as Control_status)
> 
> ```
> Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00100021; Control_status=0}
> ```
> 
> OR
> 
> ```
> Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00130024; Control_status=0}
> ```

sry there s no change on my touchpad :（

**Comment by seerge** [comment]
@SanaeKochiya114514 oke :) well then i'm out of ideas
