### ISSUE TITLE
Changelog link in update prompt

### ISSUE THREAD

**Issue by djuniah** [seerge/g-helper#739]
Was wondering if it would be possible to add a link to the changelog (or the notes themselves) for the new build in the update prompt?  I tend to check patch notes for programs before installing updates and having the notes or just a link to the github releases page be included in the pop up would be a great "nice-to-have".

**Comment by seerge** [comment]
@djuniah hello, i can't add it directly to update prompt (as it's default windows alert that can have only buttons).

But even now if you click on app version - it will open releases page (with all update notes) :)
