### ISSUE TITLE
Hibernation and Standby g513qy

### ISSUE THREAD

**Issue by mirt81** [seerge/g-helper#741]
If using the Option to turn Display of by " M - Key " Hibernation and Standby would not triggert at timeset in Windows Powerplan .

If Display turns of Indepentenly by time set in Windows Powerplan Hibernation and Standby are triggert by timeset .

This happens with Internal Display only and External display Only .

Because g513qy has no Stock key for turn of Display so i used before GHelper a AutoHotKey - Script and with execute this there is the same behaivior .

So GHelper is there not a failure source but is also affected :( 

Hopefull there is something that GHelper Developers can Rule . . . Th@nks !

**Comment by seerge** [comment]
@mirt81 hello, honestly i didn't get what you want? :) Turn off display calls (the only known) windows API method that should turn display off (so you have to enter your PIN / login with face ID again) https://stackoverflow.com/questions/713498/turn-on-off-monitor

 If it doesn't work for you in other apps (Autohotkey) i think it's some setting / limitation in your windows that prevents it. I'm afraid I won't be able to do much here :)

**Comment by mirt81** [comment]
Im self get not whats there going on ! ?

So if the Display is turned of with " Key " and the Powerplan is set to go in Hibernation or Standby after 5min Idle this  not happens . . . 

. . . when Display turns of by Powerplan setting as example Value 1min by its self after that the g513qy go to Hibernation or Standby after 5min Idle as set in Powerplan  

Im using a local account with bypasst Password .

**Comment by seerge** [comment]
But that's your windows behaviour :) how is the app connected to that? :)

I'm closing this cause this is not related to g-helper honestly.
