### ISSUE TITLE
SCAR 17 G733ZW GPU Thermal Limit Resets After SleepWake

### ISSUE THREAD

**Issue by iamtimsson** [seerge/g-helper#743]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
When the computer goes to sleep, HWINFO Alerts (when set) and shows upon wake that the GPU Thermal Limit has reset to 87c from my setting. I have 0 running asus services as per G-H

**Clear scenario to Reproduce**
Stop all Asus services in G-H with button
Make sure it says 0, restart if you have to
Set GPU Thermal Limit
Close lid/execute sleep on lappy
Wake up lappy, observe thermal limit reset

The sleep must be a "full" sleep idk what to call it but if you just do it quickly nothing changes.
The system needs to go into actual sleep mode not fake sleep idk what it is.

**Expected behavior**
Lol pls stay set where I put you ok u are very smart but v v hot ok?

**App Logs**
My app log got reset so I could make sense of it and I will post it asap
I am looking for PowerLimit C2 = 8x
I have seen it pop up a few times and now that I know what I am looking for I can post relevant info asap.

**Screenshots or screencasts**

**Desktop (please complete the following information):**
SCAR 17 G733ZW, Win 11

**Asus software**
Armoury Crate installed because Aura Creator does not work without it and unfortunately Aura has more option for lighting that are missing form the awesomefuckingdope g-h.
MyAshit installed for intermittent update checks
0 Services running as per g-h

**Additional context**
Love you buddy you fucking wonderful madperson thank you for relieving me of this disgusting badmess

**Comment by seerge** [comment]
@iamtimsson hello, app re-applies all basic settings every time its launched or every time laptop wakes up.

Given that you don’t provide a log (where it should be visible i can’t really assist you further)

**Comment by iamtimsson** [comment]
Very frustrating. I said I was gonna post the log and it got closed.

I know in .8x you updated that it resets every thirty seconds and I am telling you it does not.

https://i.ibb.co/FJX7JSX/Untitled.png

7 Jul 2023 22:27:29: Key: 124
7 Jul 2023 22:27:33: Key: 124
7 Jul 2023 22:28:07: Key: 124
7 Jul 2023 22:28:20: Key: 124
8 Jul 2023 01:37:27: Monitor Dimmed
8 Jul 2023 01:37:43: Monitor Power Off
8 Jul 2023 01:37:43: Backlight:5D-BA-C5-C4-00
8 Jul 2023 04:15:24: Monitor Power On
8 Jul 2023 04:15:24: AutoSetting for Online
8 Jul 2023 04:15:24: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&19e2ad7&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
8 Jul 2023 04:15:24: Mode = 1 : OK
8 Jul 2023 04:15:24: FanCPU = 1D-31-3C-41-46-64-65-66-0A-14-28-45-63-63-63-63 : OK
8 Jul 2023 04:15:24: FanGPU = 1D-31-3C-41-46-64-65-64-0B-13-27-46-63-63-63-63 : OK
8 Jul 2023 04:15:24: Power mode: ded574b5-45a0-4f42-8737-46345c09c238
8 Jul 2023 04:15:24: GET GPU CLOCKS: 0, 0
8 Jul 2023 04:15:24: Eco flag : 0
8 Jul 2023 04:15:24: Mux flag : 0
8 Jul 2023 04:15:24: ScreenOverdrive = 0 : OK
8 Jul 2023 04:15:24: BatteryLimit = 60 : OK
8 Jul 2023 04:15:24: Auto:5D-BA-C5-C4-01
8 Jul 2023 04:15:25: PowerLimit C0 = 25 : OK
8 Jul 2023 04:15:25: PowerLimit C2 = 75 : OK
8 Jul 2023 04:15:56: Monitor Power Off
8 Jul 2023 04:15:57: Backlight:5D-BA-C5-C4-00
8 Jul 2023 04:39:34: Monitor Power On
8 Jul 2023 04:39:34: AutoSetting for Online
8 Jul 2023 04:39:34: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&19e2ad7&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
8 Jul 2023 04:39:34: Mode = 1 : OK
8 Jul 2023 04:39:34: FanCPU = 1D-31-3C-41-46-64-65-66-0A-14-28-45-63-63-63-63 : OK
8 Jul 2023 04:39:34: FanGPU = 1D-31-3C-41-46-64-65-64-0B-13-27-46-63-63-63-63 : OK
8 Jul 2023 04:39:34: Power mode: ded574b5-45a0-4f42-8737-46345c09c238
8 Jul 2023 04:39:34: GET GPU CLOCKS: 0, 0
8 Jul 2023 04:39:34: Eco flag : 0
8 Jul 2023 04:39:34: Mux flag : 0
8 Jul 2023 04:39:34: ScreenOverdrive = 0 : OK
8 Jul 2023 04:39:34: BatteryLimit = 60 : OK
8 Jul 2023 04:39:34: Auto:5D-BA-C5-C4-01
8 Jul 2023 04:39:35: PowerLimit C0 = 25 : OK
8 Jul 2023 04:39:35: PowerLimit C2 = 75 : OK
8 Jul 2023 04:41:02: GET GPU CLOCKS: 0, 0

I told you I was gonna post this it's literally in the post itself.

**Comment by seerge** [comment]
@iamtimsson 
```
8 Jul 2023 04:39:35: PowerLimit C0 = 25 : OK
8 Jul 2023 04:39:35: PowerLimit C2 = 75 : OK

```
App sets temp limit to 75 after laptop wakes up from sleep

**Comment by iamtimsson** [comment]
Dude I posted an image.
NO. IT does NOT.

**Comment by seerge** [comment]
Then it's probably some other software (or even nvidia driver) running on your computer that overwrites it.

Does it change in HWinfo you would drag slider after?

Try to run some real-life test (like Furmark) and monitor how high temps would go until GPU starts throttling (i.e. reaches limit)

**Comment by iamtimsson** [comment]
Real life test is when I run a game it reports that the gpu temp goes to max 87c.
When i open gh and reset the slider it follows the setting until  computer sleeps again.
I have SCOURED this laptop for ANYTHING related to these settings and I can only find it in ac or gh.

The slider does NOT respect the ACTUAL limit being reported in hwinfo NOR the actual limit being sensed by or reported by games.

**Comment by seerge** [comment]
@iamtimsson 
If you have AC running then AC probably resets it then :)

**Comment by iamtimsson** [comment]
In other words. I set thermal limit with slider to 75c.
Games and sensors respect slider setting.
Computer sleeps, slider setting still reads 75c, temps go up to 87c and thermal limit on sensors reads 87.
GH is ALREADY RUNNING, NO SERVICES ARE RUNNING AS PER GH.
NO ASUS TRASH IS RUNNING.

**Comment by seerge** [comment]
@iamtimsson g-helper doesn't monitor or stop any of armoury services :) If you want to remove armoury - you need to use it's own uninstaller.

G-helper has has ability to stop /start a set of services coming with system by default (needed mainly for MyASUS) only.

**Comment by iamtimsson** [comment]
Thanks. I need AC because I cannot use Aura Creator without it.
I understand that this service may be overwriting the values.
I wonder why it is not logged accurately.
I wonder why when the application is meant to reapply the limits every thirty seconds is does not do it.

Thank you for responding immediately.
Your work and application are more than appreciated but are an unfortunate necessity in this economy of profit.

**Comment by iamtimsson** [comment]
https://i.ibb.co/QXGXQWH/Untitled.png
also it has been 30s no reapply in logs either

**Comment by seerge** [comment]
@iamtimsson I think you can install Aura Creator independently?

If you really want to keep Armoury installed, but still use G-Helper, then you will have to manually stop it's own services from windows -> Services application, but I have no idea what consequences will be :)

App doesn't apply GPU limits every 30 seconds, as it's not needed. You mix it with Ryzen CPU limits i assume.

**Comment by iamtimsson** [comment]
Aura Creator requires Armoury Crate unfortunately.

I see this but can not stop the service as I am pretty certain is has to do with Aura Creator.

I though this was updated in .8x. It was posted I will find it.
Intel- not ryzen.

**Comment by iamtimsson** [comment]
https://i.ibb.co/XCN7qwk/Untitled.png

**Comment by iamtimsson** [comment]
thatttt says cpu ok i made a mistake there
still y we no do gpu the same way

**Comment by seerge** [comment]
@iamtimsson because there is no need to constantly spam ACPI calls to BIOS every 30 seconds. I will cause extra resources usage, and only harm all other users.

In your case it's AC overwriting limits (and most probably it overwrites other settings as well, including fan profiles, etc, not only GPU temp)

**Comment by iamtimsson** [comment]
thanks for interact

**Comment by iamtimsson** [comment]
Uh oh dearest seerge!

7/8/2023 5:19:42 PM: PowerLimit C0 = 25 : OK
7/8/2023 5:19:42 PM: PowerLimit C2 = 75 : OK
7/8/2023 5:20:34 PM: ------------
7/8/2023 5:20:34 PM: App launched: ROG Strix G733ZW_G733ZW :0.95.0.0en-US
7/8/2023 5:20:34 PM: NVIDIA GeForce RTX 3070 Ti Laptop GPU
7/8/2023 5:20:35 PM: CPU: -1 - 12th Gen Intel(R) Core(TM) i9-12900H - Intel64 Family 6 Model 154 Stepping 3
7/8/2023 5:20:36 PM: AutoSetting for Online
7/8/2023 5:20:36 PM: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&19e2ad7&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
7/8/2023 5:20:36 PM: Mode = 1 : OK
7/8/2023 5:20:36 PM: FanCPU = 14-3F-44-48-4B-50-54-62-11-1A-22-29-63-63-63-63 : OK
7/8/2023 5:20:36 PM: FanGPU = 14-3F-44-48-4A-50-54-62-16-1F-26-2D-63-63-63-63 : OK
7/8/2023 5:20:36 PM: Eco flag : 0
7/8/2023 5:20:36 PM: Mux flag : 0
7/8/2023 5:20:36 PM: ScreenOverdrive = 0 : OK
7/8/2023 5:20:36 PM: BatteryLimit = 60 : OK
7/8/2023 5:20:36 PM: BatteryLimit = 60 : OK
7/8/2023 5:20:36 PM: Monitor Power On
7/8/2023 5:20:36 PM: Auto:5D-BA-C5-C4-01
7/8/2023 5:20:37 PM: PowerLimit C0 = 25 : OK
7/8/2023 5:20:37 PM: PowerLimit C2 = 75 : OK
7/8/2023 5:20:54 PM: Failed to check for updates:No such host is known. (api.github.com:443)
7/8/2023 5:20:56 PM: GET GPU CLOCKS: 0, 0

I have since fresh installed win, updated drivers and software, removed bloat, tweaked and hardened win, have no services of asus running reported in g-h, and after reboot, the setting in g-h for gpu thermal limit is not respected and reported as defaulting again to 87c sad face.

**Comment by iamtimsson** [comment]
Run on startup is enabled also! D: ty seerge

**Comment by iamtimsson** [comment]
I was doing some research into some things and found that '[g-h applies limits and settings on launch, slider adjustment, and sleep](https://github.com/seerge/g-helper/discussions/196#discussioncomment-5530182)'. It seems to be a solution to this problem, applying limits and settings after a brief sleep() count of a second or so upon wake from sleep.

Couldja wouldja dear seerge of script?

**Comment by seerge** [comment]
@iamtimsson currently app waits for 1 second before setting all limits after wake up. So far it seemed to be more than sufficient for people who use app (as no one complained).

In this build I have added one more extra 1 second delay before setting temp limit (so it's 2 seconds in total)
[GHelper.zip](https://github.com/seerge/g-helper/files/11994994/GHelper.zip)

Let me know if it helps in your case.

**Comment by iamtimsson** [comment]
Thanks, seerge. Does this build include the [fix](https://github.com/seerge/g-helper/issues/744#issuecomment-1627248107) for the audio devices you worked on recently?

**Comment by iamtimsson** [comment]
OMG SEERGE STOP IT YOU CAN ONLY DO SO MUCH GOOD IN THE WORLD STOP YOU'RE GONNA BREAK IT
(the fix works. both log and hwinfo sensors are reporting set by g-h after a reboot. Gonna try sleep cycle now.

**Comment by iamtimsson** [comment]
Seems that the delay fixed the issue. Hard sleep and boot both log g-h gpu thermal limit and sensors in hwinfo show this.

Love ya bud god damn thank you

**Comment by iamtimsson** [comment]
Still working
