### ISSUE TITLE
SCAR 17 G733ZW MKey 3, Microphone Toggle Shows Popup, but Software Can Still Hear Mic (WITH Solution)

### ISSUE THREAD

**Issue by iamtimsson** [seerge/g-helper#744]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
I was checking mic settings in wz2 and I noticed that with the mic set to disabled with the macro key, the game still responds to my mic as if it is enabled.

**Clear scenario to Reproduce**

**Expected behavior**
Pls turn off mic lol when ask mic off silly compuder

**App Logs**
App log just reset seeking other bug, will post asap

**Screenshots or screencasts**
Gonna be a bit hard but I will get one if you need it.

**Desktop (please complete the following information):**
SCAR 17 G733ZW
Win 11

**Asus software**
AC is installed for Aura Creator to work
Myashit is installed for updates
No  ashit services according to the awesome g-h

**Additional context**
I have since removed the keybind in g-h and replaced it with this bat that fixes the issue for me.
I don't know where the global mic variable is yet but this functions for now.
If you replace your microphone toggle with a path to this .bat all is well

`set key="HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone\NonPackaged"

reg query "%key%" /v Value | find "Deny"
if errorlevel 1 goto turnoff
goto turnon

:turnoff
reg add "%key%" /v Value /t REG_SZ /d Deny /f
goto :eof

:turnon
reg add "%key%" /v Value /t REG_SZ /d Allow /f
goto :eof

goto sources
https://www.tenforums.com/tutorials/80323-enable-disable-microphone-windows.html#option5
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/reg-add
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/reg-query
https://stackoverflow.com/questions/9315289/batch-file-if-registry-keys-data-is-equal-to
https://stackoverflow.com/questions/48371267/batch-file-if-registry-keys-data-equals-x
https://stackoverflow.com/questions/8526946/commenting-multiple-lines-in-dos-batch-file
:sources`

**Comment by seerge** [comment]
@iamtimsson hello,

What Mic disable is switches mic off in windows settings (see screenshot)

![Screenshot 2023-07-08 112338](https://github.com/seerge/g-helper/assets/5920850/9d7b652b-9438-4bec-be34-45a62f4ef70b)

If it's the case for you, then app does what it supposed to do :)

**Comment by iamtimsson** [comment]
Settings > Privacy and Security > Microphone > Let apps access your microphone > Let desktop apps access your microphone

**Comment by seerge** [comment]
@iamtimsson access to microphone is one of a privacy policies, it doesn't MUTE microphone.

**Comment by iamtimsson** [comment]
Nono so what I am saying is that with g-h, the standard behavior of the macro 3 key which is to mute the mic does not.

In wz2 when you test mic after you have "muted" the mic with the macro key, the vox bars still react to voice.

When I disable the mic this way, the programs do not react to the mic as it has been alternatively disabled.

**Comment by iamtimsson** [comment]
Ah so if it is adjusting access to mic not muting, it is not doing it all the way lol.
How do we make it so that the mic permissions are toggled globally by the mute mic macro key?

**Comment by seerge** [comment]
@iamtimsson does the mute button mute microphone in windows settings that I linked? Also make sure that in app you use default input device (or set default windows input device to the same one you use in game)

**Comment by iamtimsson** [comment]
Also yeah it's not doing that either. 
https://i.ibb.co/YfwKvFd/Untitled.png

**Comment by seerge** [comment]
@iamtimsson you need to re-open settings page after muting. Does it stay unmuted still?

**Comment by iamtimsson** [comment]
After reloading the ui, the mic mute toggle is not respected by the mute-unmute popup of the macro 3 mute mic key on scar 17 g733zw

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11990646/GHelper.zip)

Can you try this build and post a log from it? It will write down device name that it's muting

**Comment by iamtimsson** [comment]
on it now will post asap

**Comment by iamtimsson** [comment]
8 Jul 2023 05:32:27: ------------
8 Jul 2023 05:32:27: App launched: ROG Strix G733ZW_G733ZW :0.95.0.0en-US
8 Jul 2023 05:32:27: NVIDIA GeForce RTX 3070 Ti Laptop GPU
8 Jul 2023 05:32:28: CPU: -1 - 12th Gen Intel(R) Core(TM) i9-12900H - Intel64 Family 6 Model 154 Stepping 3
8 Jul 2023 05:32:28: AutoSetting for Online
8 Jul 2023 05:32:28: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&19e2ad7&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
8 Jul 2023 05:32:28: Mode = 1 : OK
8 Jul 2023 05:32:28: FanCPU = 1D-31-3C-41-46-64-65-66-0A-14-28-45-63-63-63-63 : OK
8 Jul 2023 05:32:28: FanGPU = 1D-31-3C-41-46-64-65-64-0B-13-27-46-63-63-63-63 : OK
8 Jul 2023 05:32:28: Power mode: ded574b5-45a0-4f42-8737-46345c09c238
8 Jul 2023 05:32:28: Eco flag : 0
8 Jul 2023 05:32:28: Mux flag : 0
8 Jul 2023 05:32:28: ScreenOverdrive = 0 : OK
8 Jul 2023 05:32:28: BatteryLimit = 60 : OK
8 Jul 2023 05:32:28: BatteryLimit = 60 : OK
8 Jul 2023 05:32:28: Auto:5D-BA-C5-C4-01
8 Jul 2023 05:32:28: Monitor Power On
8 Jul 2023 05:32:29: PowerLimit C0 = 25 : OK
8 Jul 2023 05:32:29: PowerLimit C2 = 75 : OK
8 Jul 2023 05:32:30: Latest version 0.95.0.0
8 Jul 2023 05:32:33: Key: 124
8 Jul 2023 05:32:33: AI Noise-cancelling Input (ASUS Utility):True
8 Jul 2023 05:32:35: Key: 124
8 Jul 2023 05:32:35: AI Noise-cancelling Input (ASUS Utility):False
8 Jul 2023 05:32:36: Key: 124
8 Jul 2023 05:32:37: AI Noise-cancelling Input (ASUS Utility):True
8 Jul 2023 05:32:38: Key: 124
8 Jul 2023 05:32:39: AI Noise-cancelling Input (ASUS Utility):False
8 Jul 2023 05:32:50: GET GPU CLOCKS: 0, 0
8 Jul 2023 05:32:53: PowerLimit C0 = 25 : OK
8 Jul 2023 05:32:53: PowerLimit C2 = 75 : OK
8 Jul 2023 05:32:54: PowerLimit C0 = 25 : OK
8 Jul 2023 05:32:54: PowerLimit C2 = 75 : OK

go figure this idiot computer is toggling a device I don't even fing use what an idiot.

I literally cannot even figure out how to remove this ai-sound cancelling trash.

Useless garbage.

How can we proceed?

**Comment by iamtimsson** [comment]
Also, I manually set the gpu therm limit manually out of habit now

**Comment by seerge** [comment]
@iamtimsson I think AI Noise Cancelling is selected somewhere in a system settings,

Try this build (and post a log), it will try to reach more input devies
[GHelper.zip](https://github.com/seerge/g-helper/files/11990673/GHelper.zip)

**Comment by iamtimsson** [comment]
Thanks.

Wow would you look at this fing disgusting idiocy

https://i.ibb.co/3rfKrj4/Untitled.png

Checking build now

Also no. In asuses infinite ability the idiots can't figure out that when you DISABLE things in armoury crate it should disable.

The internet says ai noise trash is in myasus it is not
It is in ac
You can disable it in ac
It does nothing 
Because asus is idiots

**Comment by iamtimsson** [comment]
I removed that stupid trash and restarted pc and still the toggle does not affect settings.

**Comment by iamtimsson** [comment]
You posted a second build to try right? Did you remove the second build?

**Comment by seerge** [comment]
@iamtimsson i didn’t remove anything, please try second build

**Comment by iamtimsson** [comment]
On it now

**Comment by iamtimsson** [comment]
8 Jul 2023 05:49:36: ------------
8 Jul 2023 05:49:36: App launched: ROG Strix G733ZW_G733ZW :0.95.0.0en-US
8 Jul 2023 05:49:36: NVIDIA GeForce RTX 3070 Ti Laptop GPU
8 Jul 2023 05:49:37: CPU: -1 - 12th Gen Intel(R) Core(TM) i9-12900H - Intel64 Family 6 Model 154 Stepping 3
8 Jul 2023 05:49:37: AutoSetting for Online
8 Jul 2023 05:49:37: Input: \\?\hid#vid_0b05&pid_19b6&col04#6&19e2ad7&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
8 Jul 2023 05:49:37: Mode = 1 : OK
8 Jul 2023 05:49:37: FanCPU = 1D-31-3C-41-46-64-65-66-0A-14-28-45-63-63-63-63 : OK
8 Jul 2023 05:49:37: FanGPU = 1D-31-3C-41-46-64-65-64-0B-13-27-46-63-63-63-63 : OK
8 Jul 2023 05:49:37: Power mode: ded574b5-45a0-4f42-8737-46345c09c238
8 Jul 2023 05:49:37: Eco flag : 0
8 Jul 2023 05:49:37: Mux flag : 0
8 Jul 2023 05:49:37: ScreenOverdrive = 0 : OK
8 Jul 2023 05:49:37: BatteryLimit = 60 : OK
8 Jul 2023 05:49:37: BatteryLimit = 60 : OK
8 Jul 2023 05:49:37: Auto:5D-BA-C5-C4-01
8 Jul 2023 05:49:37: Monitor Power On
8 Jul 2023 05:49:38: PowerLimit C0 = 25 : OK
8 Jul 2023 05:49:38: PowerLimit C2 = 75 : OK
8 Jul 2023 05:49:39: Latest version 0.95.0.0
8 Jul 2023 05:49:44: Key: 124
8 Jul 2023 05:49:44: AI Noise-cancelling Input (ASUS Utility):False
8 Jul 2023 05:49:44: Microphone Array (Realtek(R) Audio):False
8 Jul 2023 05:49:44: Microphone Array (Realtek(R) Audio):False
8 Jul 2023 05:49:44: Key: 124
8 Jul 2023 05:49:44: AI Noise-cancelling Input (ASUS Utility):True
8 Jul 2023 05:49:44: Microphone Array (Realtek(R) Audio):True
8 Jul 2023 05:49:44: Microphone Array (Realtek(R) Audio):True
8 Jul 2023 05:49:45: Key: 124
8 Jul 2023 05:49:45: AI Noise-cancelling Input (ASUS Utility):False
8 Jul 2023 05:49:45: Microphone Array (Realtek(R) Audio):False
8 Jul 2023 05:49:45: Microphone Array (Realtek(R) Audio):False
8 Jul 2023 05:49:45: Key: 124
8 Jul 2023 05:49:45: AI Noise-cancelling Input (ASUS Utility):True
8 Jul 2023 05:49:45: Microphone Array (Realtek(R) Audio):True
8 Jul 2023 05:49:46: Microphone Array (Realtek(R) Audio):True

I don't understand why that ai idiot crap is there it should be uninstalled I just uninstalled and restarted what in the hell man can nothing be good

**Comment by seerge** [comment]
Well, now it mutes all devices on your laptop, including Realtek (correct one) 
```
8 Jul 2023 05:49:45: Microphone Array (Realtek(R) Audio):False
```

So please check if Settings -> Audio in windows update accordingly (after change)

And if so - that should be it.

**Comment by iamtimsson** [comment]
The mic icon in settings now reflects and respects the mute/unmute toggle with macro key 3 for mic mute/unmute
A little sideway, is there no way to nuke that noise trash from the system?

**Comment by iamtimsson** [comment]
8 Jul 2023 05:53:11: Key: 124
8 Jul 2023 05:53:11: Headset Microphone (CORSAIR HS55 Wireless Core Receiver):True
8 Jul 2023 05:53:11: Headset Microphone (CORSAIR HS55 Wireless Core Receiver):True
8 Jul 2023 05:53:11: Headset Microphone (CORSAIR HS55 Wireless Core Receiver):True
8 Jul 2023 05:53:11: Key: 124
8 Jul 2023 05:53:11: Headset Microphone (CORSAIR HS55 Wireless Core Receiver):False
8 Jul 2023 05:53:11: Headset Microphone (CORSAIR HS55 Wireless Core Receiver):False
8 Jul 2023 05:53:11: Headset Microphone (CORSAIR HS55 Wireless Core Receiver):False
8 Jul 2023 05:53:12: Key: 124
8 Jul 2023 05:53:12: Headset Microphone (CORSAIR HS55 Wireless Core Receiver):True
8 Jul 2023 05:53:12: Headset Microphone (CORSAIR HS55 Wireless Core Receiver):True
8 Jul 2023 05:53:12: Headset Microphone (CORSAIR HS55 Wireless Core Receiver):True
8 Jul 2023 05:53:12: Key: 124
8 Jul 2023 05:53:12: Headset Microphone (CORSAIR HS55 Wireless Core Receiver):False
8 Jul 2023 05:53:13: Headset Microphone (CORSAIR HS55 Wireless Core Receiver):False
8 Jul 2023 05:53:13: Headset Microphone (CORSAIR HS55 Wireless Core Receiver):False

When I apply my headset dongle and turn on my headphones, this is what is reported in log

**Comment by seerge** [comment]
@iamtimsson ok, good. So its solved now?

I don’t know how to completely uninstall noise cancelling device, try to check device manager probably or audio settings in windows somewhere.

**Comment by iamtimsson** [comment]
Close dear seerge. The last thing I am wondering is why one press of toggle applies three entries of the headset device in logs

**Comment by seerge** [comment]
@seerge cause windows has 3 different default microphones, for communications  / multimedia / and console line. Now app will adjust all 3 settings to make sure it reaches all of them (even if it's same device like now, or not like you had before with noise cancelling + realtek at the same time)

**Comment by iamtimsson** [comment]
seerge you are the most active repo host +3 thank you for being available to apply yourself
this is a genuine solution in a world of fing problems
thank you for being something to smile about
