### ISSUE TITLE
SCAR 17 G733ZW G-H Macro Keys Misaligned

### ISSUE THREAD

**Issue by iamtimsson** [seerge/g-helper#748]
Hey seerge. There are five physical m keys on this device. In g-h extras, there are only 4 m keys. The m4 key is bound to open g-h while the physical m4 key executes a mode switch ( silent, balanced, turbo ). This does not seem to report a keypress in log. The physical m5 key opens g-h, and seems to be emulating the m4 keypress bound in g-h extras. Here is all that the log puts out.
```
7/8/2023 6:38:38 PM: Key: 56
7/8/2023 6:38:40 PM: Key: 56
```
Since our last endeavor, I have reinstalled windows, updated, removed bloat, removed asus badware (ac, myasus, even aura creator) disabled asus services, startuped g-h, hardened, done a bit of research into [another issue](https://github.com/seerge/g-helper/discussions/747#discussion-5381530), and here we are. Here's to hoping!

**Comment by seerge** [comment]
@iamtimsson hello, ``56`` is a code for [M4 key](https://github.com/seerge/g-helper/blob/e0cca33ab9efa2158063acb326505efe75f48060/app/Input/InputDispatcher.cs#L352).  

Try to press M3, M4 and M5 independently and monitor log for what code they produce (it will be recorded there even if app is not expecting it).

If there is a new code - i can add and process it.

**Comment by Himezaki** [comment]
ROG Strix G533ZW (Scar 15 2022), I have the exact same issue. M4 in G-Helper is actually M5, and the 'real' M4 is for switching modes that I cannot rebind.

**Comment by seerge** [comment]
@Himezaki same question to you - does M4 on your keyboard produce any code in a log ?

**Comment by iamtimsson** [comment]
m1 m2 m3 all work as intended and I think fn+f4 (aura) works also.
This is what the log reports when you press EXACTLY THIS:
m4, m5, m4, m5, m4, m5
```
7/9/2023 7:39:59 AM: Key: 174
7/9/2023 7:39:59 AM: Mode = 2 : OK
7/9/2023 7:39:59 AM: Power mode: 961cc777-2547-4f9d-8174-7d86181b8a7a
7/9/2023 7:39:59 AM: GET GPU CLOCKS: 0, 0
7/9/2023 7:40:00 AM: Key: 56
7/9/2023 7:40:01 AM: Key: 174
7/9/2023 7:40:01 AM: Mode = 0 : OK
7/9/2023 7:40:01 AM: Power mode: 00000000-0000-0000-0000-000000000000
7/9/2023 7:40:02 AM: Key: 56
7/9/2023 7:40:03 AM: Key: 174
7/9/2023 7:40:03 AM: Mode = 1 : OK
7/9/2023 7:40:03 AM: FanCPU = 14-3F-44-48-4B-50-54-62-11-1A-22-29-63-63-63-63 : OK
7/9/2023 7:40:03 AM: FanGPU = 14-3F-44-48-4A-50-54-62-16-1F-26-2D-63-63-63-63 : OK
7/9/2023 7:40:03 AM: Power mode: ded574b5-45a0-4f42-8737-46345c09c238
7/9/2023 7:40:04 AM: Key: 56
7/9/2023 7:40:04 AM: PowerLimit C0 = 25 : OK
7/9/2023 7:40:04 AM: PowerLimit C2 = 75 : OK

```

**Comment by Himezaki** [comment]
> 



> @Himezaki same question to you - does M4 on your keyboard produce any code in a log ?

This is what appears when I press M4 over and over, hope this helps:
```
2023-07-09 9:48:04 AM: Key: 174
2023-07-09 9:48:04 AM: Mode = 0 : OK
2023-07-09 9:48:04 AM: Power mode: 00000000-0000-0000-0000-000000000000
2023-07-09 9:48:05 AM: Key: 174
2023-07-09 9:48:05 AM: Mode = 1 : OK
2023-07-09 9:48:05 AM: Power mode: ded574b5-45a0-4f42-8737-46345c09c238
2023-07-09 9:48:05 AM: Key: 174
2023-07-09 9:48:05 AM: Mode = 2 : OK
2023-07-09 9:48:05 AM: Power mode: 961cc777-2547-4f9d-8174-7d86181b8a7a
2023-07-09 9:48:05 AM: Key: 174
2023-07-09 9:48:05 AM: Mode = 0 : OK
2023-07-09 9:48:05 AM: Power mode: 00000000-0000-0000-0000-000000000000
2023-07-09 9:48:06 AM: Key: 174
2023-07-09 9:48:06 AM: Mode = 1 : OK
2023-07-09 9:48:06 AM: Power mode: ded574b5-45a0-4f42-8737-46345c09c238
2023-07-09 9:48:06 AM: Key: 174
2023-07-09 9:48:06 AM: Mode = 2 : OK
2023-07-09 9:48:06 AM: Power mode: 961cc777-2547-4f9d-8174-7d86181b8a7a
2023-07-09 9:48:06 AM: Key: 174
2023-07-09 9:48:06 AM: Mode = 0 : OK
2023-07-09 9:48:06 AM: Power mode: 00000000-0000-0000-0000-000000000000
2023-07-09 9:48:07 AM: Key: 174
2023-07-09 9:48:07 AM: Mode = 1 : OK
2023-07-09 9:48:07 AM: Power mode: ded574b5-45a0-4f42-8737-46345c09c238
```

**Comment by iamtimsson** [comment]
@Himezaki hey dear buddy will you post a m5 log like your m4 log, please? At least for redundancy!

**Comment by seerge** [comment]
@iamtimsson @Himezaki for both of you

In your case :

M4 - does same as FN+F5 on other devices (i.e. it cycles profiles)
M5 - indeed does M4 from other devices (i.e. toggles g-helper window)

Both are already processed by app. So the only difference would be just correcting a label in UI.

There is no way to "read" how many buttons does device have, only by setting it based on model name.
I'm not sure if 5 M-buttons is typical for all ROG Scar devices or only some of them ?

**Comment by iamtimsson** [comment]
I will see if I can find a knowledge base

**Comment by Himezaki** [comment]
> @Himezaki hey dear buddy will you post a m5 log like your m4 log, please? At least for redundancy!

I have the default action bound, here you go:
```
2023-07-09 10:30:30 AM: Key: 56
2023-07-09 10:30:30 AM: Key: 56
2023-07-09 10:30:38 AM: Key: 56
2023-07-09 10:30:38 AM: Key: 56
2023-07-09 10:30:38 AM: Key: 56
2023-07-09 10:30:39 AM: Key: 56
2023-07-09 10:30:39 AM: Key: 56
2023-07-09 10:30:39 AM: Key: 56
2023-07-09 10:30:39 AM: Key: 56
```

**Comment by iamtimsson** [comment]
@Himezaki Turns out as seerge pointed out, our fn+f5 is the same keystroke as m4
I did just notice that there is no fn+f5 option in g-h though.

**Comment by seerge** [comment]
Fn+F5 is reserved for profile toggling, it can’t be reassigned to any other action. But i don’t see any issues here.

**Comment by iamtimsson** [comment]
The issue is m4 and m5 seerge.

**Comment by seerge** [comment]
@iamtimsson m4 and m5 are being processed by the app already. The only difference for you would be incorrect label (M4 instead of M5). 

I just renamed M4 to ROG for simplicity in this build 

[GHelper.zip](https://github.com/seerge/g-helper/files/11995539/GHelper.zip)

**Comment by iamtimsson** [comment]
How do we bind our m4 key?

**Comment by iamtimsson** [comment]
In the app. m4 needs to be m5 and also we need an m4 bind option because there is not one.

**Comment by seerge** [comment]
You don’t, its reserved for toggling profiles.

**Comment by iamtimsson** [comment]
I see

**Comment by iamtimsson** [comment]
physical f5 key on scar 17 g733zw is printed with fan logo
physical m4 key on scar 17 g733zw is printed with fan logo
physical m5 key on scar 17 g733zw is printed with rog logo
physical f4 key on scar 17 g733zw is printed with aura logo

love ya

**Comment by seerge** [comment]
Label adjustments from included build, will be in next release. Closing for now.

**Comment by shprd95** [comment]
> Label adjustments from included build, will be in next release. Closing for now.

can we have this for ROG Strix G16 please? there's m4 button which is toggling fan modes, and the m5 button with a rog logo that should open the g-helper window, but for now it does nothing and i can't bind to it in extra

**Comment by seerge** [comment]
@shprd95 it’s already working on your G16 (as i had same one for testing)

Rog button emits same code on all devices, and you can control this binding via m4/rog one in extras

**Comment by shprd95** [comment]
> @shprd95 it’s already working on your G16 (as i had same one for testing)
> 
> Rog button emits same code on all devices, and you can control this binding via m4/rog one in extras

yeah, i mean m4 is already in-use to toggle between fan modes, and m5 is not available to interact with

**Comment by seerge** [comment]
I have renamed M4/Rog into M5/Rog for Strix devices :) 

[GHelper.zip](https://github.com/seerge/g-helper/files/12343706/GHelper.zip)

**Comment by shprd95** [comment]
> I have renamed M4/Rog into M5/Rog for Strix devices :)
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/12343706/GHelper.zip)

Great, thanks! that makes a bit easier for me to figure out what button is responding to specific action

**Comment by Ishiharaerika** [comment]
Sorry I have to comment on this issue.
For G733ZX, factory defaults for those macro keys seemed to be the same as G-Helper's default (for G733ZX). But internal key codes were changed during recent Armoury Crate relations update.

Logs by G-Helper, in the sequence of M1/Vol DOWN, M2/Vol UP, M3/Mic Mute, M4/Fan, M5/ROG:
```
2025/03/28 11:45:37: VolumeDown None
2025/03/28 11:45:37: Key: 124
2025/03/28 11:45:38: VolumeUp None
2025/03/28 11:45:38: VolumeDown None
2025/03/28 11:45:39: Key: 124
```
My conclusion:
Physical -> Virtual
M1 -> M1
M2 -> M3
M3 -> M2
M4 -> M1
M5 -> M3

I haven't used Armoury Crate for about 2 years. Actually it was not installed due to fresh Windows installation. I've just downloaded & installed AC today. Unfortunately after clicking UpdateALL macro keys are affected.

**Comment by seerge** [comment]
@Ishiharaerika just do a [hard-reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset), and all your bindings will be returned back to defaults.

**Comment by Ishiharaerika** [comment]
> [@Ishiharaerika](https://github.com/Ishiharaerika) just do a [hard-reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset), and all your bindings will be returned back to defaults.

Ahh! That fixed it perfectly. Thank you for the support.
