### ISSUE TITLE
Push releases with a shortcut to logs

### ISSUE THREAD

**Issue by iamtimsson** [seerge/g-helper#749]
Hey yall. I know it's pretty easy to File Explorer > %APPDATA% > g-helper > logs, right?
Well, I put a shortcut named logs inside the g-h folder to access the appdata easier.
I don't store g-h in program files, though, so it may not be as applicable to others?
[Wdyt](https://i.ibb.co/tBhYCHP/image.png)?

**Comment by seerge** [comment]
@iamtimsson hello, in upcoming release I did some redesign for Extra screen, and now it simply has a [log] icon that opens log

[GHelper.zip](https://github.com/seerge/g-helper/files/12008755/GHelper.zip)
