### ISSUE TITLE
[Feature request] Allow lock battery charge limit 🔒

### ISSUE THREAD

**Issue by rainbowflesh** [seerge/g-helper#751]
I often accidentally touch the modification limit when opening the panel, If we have 2step confirm or a lock will be helpful.

**Comment by seerge** [comment]
@rainbowflesh hello,

Honestly I'm not a big fan of adding extra steps / complications to the UI. With same success any element on main window can be adjusted / clicked, not only charge limit :)

**Comment by rainbowflesh** [comment]
> @rainbowflesh hello,
> 
> Honestly I'm not a big fan of adding extra steps / complications to the UI. With same success any element on main window can be adjusted / clicked, not only charge limit :)

🤣 I agree with your design ethos, however using the Z13 as a tablet with the M$ taskbar causes too many accidents.
