### ISSUE TITLE
Can you add control funtion to another ROG devices (mouse, headphone, tws headphone...)

### ISSUE THREAD

**Issue by thaipham1410** [seerge/g-helper#752]
Can you add control funtion to another ROG devices (mouse, headphone, tws headphone...)

**Comment by Rakaveli** [comment]
+1, it would be nice to add at least a battery status indicator for a mouse, keyboard or headphones.

**Comment by seerge** [comment]
@thaipham1410 @Rakaveli hello, I don't have any of those devices in possession, and it is not realistic to add that on this stage.
