### ISSUE TITLE
Switching between portable installations doesn't apply configurations

### ISSUE THREAD

**Issue by philipjholm** [seerge/g-helper#753]
I have two different folders with G-helper with a config.json in each. They have different settings, such as color of LED and I want to be able to change between the two but it seems that portable configs are not applied when started. 

How to reproduce:
1. Open installation A (with LED color set to green) and see how it changes color to green.
2. Close installation A,
3. Open installation B (with LED color set to red). The LED is still green even though it in the settings says they should be red.
4. If I however in installation B changes something in the settings the color is correctly changed.

**Comment by philipjholm** [comment]
Not sure if this only is the case with LED color or if it also the same with the rest of the configuration.

**Comment by philipjholm** [comment]
@seerge Ah I see, so it is not considered a bug then? To me it sounds a bit strange that the settings in the program doesn't reflect what is actually set. Isn't that the whole purpose of it? 

Either way, thanks for this awesome program!

**Comment by seerge** [comment]
@philipjholm some people seem to use Armory (don't know why tho) or OpeRGB next to G-Helper, and set some custom backlight modes there. So atm app doesn't set any backlight on launch in order to not to overwrite other apps settings :) So currently it behaves as it supposed so.

**Comment by seerge** [comment]
@philipjholm what kind if problem are you actually trying to solve by having 2 separate installations ?

**Comment by seerge** [comment]
@philipjholm what the difference between "docked" and "powered" (sounds like both are powered?)

Just in case app remembers it's performance mode (with all settings inside) per plugged / on battery. So just configuring 2 separate modes should do the thing.

It doesn't include RGB / other things tho. Only performance related settings :)

**Comment by philipjholm** [comment]
@seerge Yeah, sorry meant docked / undocked 🙈 okay I see, will tinker around and see if that works for my setup :) would be nice for LEDS and especially battery charge limit though. I think we can close this one now as I understand how it is mean to work. Once again, thanks for an awesome program and also quick support!
