### ISSUE TITLE
Asus Zephyrus G15 having issues when switching the laptop to igpu from battery power.

### ISSUE THREAD

**Issue by Maneeha1234SL** [seerge/g-helper#754]
## NOTE

Model : Asus Zephyrus G15 Ryzen 7 6800HS Rtx 3060  ( GA503RM-HQ068W )

Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**

**Clear scenario to Reproduce**
4. Explanation of an error or a bug

**Expected behavior**

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/12013336/log.txt)

**Screenshots or screencasts**
If ap
<img width="350" alt="Screenshot 2023-07-11 093006" src="https://github.com/seerge/g-helper/assets/83775004/70ac893e-4b94-48c5-a69b-901d69f35eb0">
<img width="845" alt="Screenshot 2023-07-10 200543" src="https://github.com/seerge/g-helper/assets/83775004/ccefa08a-2d5f-409c-baf2-2bdf4cc6bfef">

<img width="455" alt="Screenshot 2023-07-11 153235" src="https://github.com/seerge/g-helper/assets/83775004/366fb7ab-cffe-4899-b204-60ab36d07959">

Asus Zephyrus G15 having issues when switching the laptop to igpu from battery power.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Laptop model

**Asus software**
- Armoury crate (or it's services installed)
- MyASUS installed
- Other Asus services running in background

**Additional context**

**Comment by seerge** [comment]
@Maneeha1234SL hello, G15 is known to have a very bugged bios that struggles to disable dGPU. App already offers you to restart-GPU in device manager in order to try to disable it again. That's maximum that can be done here.

You may also downgrade to older BIOS versions that seem to have less issues https://github.com/seerge/g-helper/discussions/448

**Comment by seerge** [comment]
+ I have checked log, and I see that all your recent attempts to swtch dGPU off succeeded 

```
7/11/2023 11:53:07 AM: Running eco command 1
7/11/2023 11:53:08 AM: GPUEco = 1 : OK
```
