### ISSUE TITLE
GPU is not visible after switching modes until G-Helper is restarted.

### ISSUE THREAD

**Issue by CyberMan38** [seerge/g-helper#755]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
G-Helper isn't able to recognize Nvidia GPU after switching GPU modes (standart->eco->standart) even when GPU is powered. Thus, it can't show GPU temp and apply O.C. in power profiles. Need to restart the app in order to use those functionalities. 

**Clear scenario to Reproduce**
1. Go to G-Helper
2. Click on Eco mode if it isn't already from GPU mode section.
3. Click back to standart mode. 
4. Now the app no longer be able to detect dedicated GPU even when the GPU is using at that time. It can only show GPU fan speed because it doesn't need Nvidia calls.

**Expected behavior**
I expect to GPU O.C. and Temp function properly after dedicated GPU mode switched off and on again without need to restart the app.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12015958/log.txt)

**Screenshots or screencasts**
![Ekran görüntüsü 2023-07-11 174349](https://github.com/seerge/g-helper/assets/122369995/e5538dea-cfa0-4c55-80c9-fc92b2ef5656)
![Ekran görüntüsü 2023-07-11 174449](https://github.com/seerge/g-helper/assets/122369995/642d3f4c-372b-4b2f-bba6-687d493978ab)

**Desktop (please complete the following information):**
 - OS: Windows 11 latest version (22H2)
 - Laptop model: Asus TUF Gaming F15 FX506HCB

**Asus software**
- Armoury crate is NOT installed, and the interface support is disabled from BIOS.
- MyASUS is NOT installed.
- Other Asus services aren't running in background

**Additional context**
I hope this will be an easy fix.

**Comment by seerge** [comment]
@CyberMan38 actually app tries to reconnect to your GPU driver after you enable it back, but probably in your case it's so slow and laggy, that it doesn't respond.

Can you try this build and post a log ?

[GHelper.zip](https://github.com/seerge/g-helper/files/12016254/GHelper.zip)

**Comment by CyberMan38** [comment]
@seerge of course, here it is: 
[log.txt](https://github.com/seerge/g-helper/files/12016321/log.txt)

It seems in this build; it works as intended. GPU is visible after switching power modes now.

**Comment by seerge** [comment]
@CyberMan38 oke, I will include longer delay to reconnect to driver in next release then :)

**Comment by CyberMan38** [comment]
@seerge I have another problem which is not related to G-Helper. Maybe you would have an idea, so I hope you don't mind me asking here.

Actually, it's not completely irrelevant. My laptop doesn't behave well on battery. The CPU gets stuck at certain frequency and do not respond to workload. Mostly I see cores don't go over 1.39 GHz no matter what I do. Basically, system become unusable in any means. Unless I switch GPU mode to eco or standart. It doesn't matter which one, just the "switching" makes CPU free as it can go higher frequency. I have no idea how these two unrelated components are tied into each other in some way. What do you think, what might be the culprit here? BIOS? Drivers? I researched this long ago and couldn't find any reasonable answer.

**Comment by seerge** [comment]
@CyberMan38 i have no idea, you can try to do a hardware reset https://github.com/seerge/g-helper#how-do-i-do-a-hardware-reset-on-a-laptop

And reinstall drivers to make sure it's all new

**Comment by CyberMan38** [comment]
hey @seerge I updated to latest stable version 0.98 and it's not working anymore. Is there any chance you've forgotten to add the delay or are you planning to add that later for some reason? I rolled back to 0.96 version which you gave me.

**Comment by seerge** [comment]
@CyberMan38 what exactly is not working ? i didn't change anything significant between 0.96 and 0.98 , it's mostly cosmetic / keybindings

**Comment by CyberMan38** [comment]
> @CyberMan38 actually app tries to reconnect to your GPU driver after you enable it back, but probably in your case it's so slow and laggy, that it doesn't respond.
> 
> Can you try this build and post a log ?
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/12016264/GHelper.zip)

in this build that you gave me here solved the GPU not reconnecting after switcing between gpu modes. and now it doesn't seems to working again in latest version.

**Comment by seerge** [comment]
@CyberMan38 increased delay to reconnect to GPU driver is there 
https://github.com/seerge/g-helper/blob/a31303624aca9779f9fc98b339d1451c6113d024/app/Gpu/GPUModeControl.cs#L157

it's 5 seconds, i assume (since you just bash between disabling / enabling GPU all the time) just clicked Fans+power immediately ?

**Comment by seerge** [comment]
@CyberMan38 i have changed logic and it will try to connect to driver immediately and then re-try in 5 seconds
[GHelper.zip](https://github.com/seerge/g-helper/files/12080367/GHelper.zip)

**Comment by CyberMan38** [comment]
> @CyberMan38 i have changed logic and it will try to connect to driver immediately and then re-try in 5 seconds [GHelper.zip](https://github.com/seerge/g-helper/files/12080367/GHelper.zip)

I tried with this build again but unfortunately it still does not reconnect after disable-enabling GPU. The build you made at the very beginning in this "issue" which it shows its version 0.96, the problem was gone, perfectly reconnects discrete GPU every time switch happens. There has to be something else in the play.

![Ekran görüntüsü 2023-07-18 153138](https://github.com/seerge/g-helper/assets/122369995/ea5608cd-ec03-46d3-8474-c94901cb9423)

**Comment by seerge** [comment]
@CyberMan38 can you post a log latest build ?

**Comment by CyberMan38** [comment]
@seerge oh yes, forgot to attach it in previous comment:
[log.txt](https://github.com/seerge/g-helper/files/12080488/log.txt)

**Comment by CyberMan38** [comment]
> @CyberMan38 try this build [GHelper.zip](https://github.com/seerge/g-helper/files/12080538/GHelper.zip)

I don't know that you did there, but it seems to be working again normally. 👍
And the effort you have given to this app is admirable. You are our savior. You save us from the horrendous Asus software. I couldn't pass without mentioning this :)
