### ISSUE TITLE
CPU Turbo Boost behavior

### ISSUE THREAD

**Issue by lucidnx** [seerge/g-helper#76]
Please can you add custom behavior for CPU Boosting? Per Power source and some drop down menu maybe? I am using Efficient Enabled instead of Aggressive on DC and disabled on battery as it's just running hot without reason when it's not needed. Switching between enabled <> disabled is nice tho..

**Comment by seerge** [comment]
I have literally set it to Aggressive cause someone on reddit has asked to change it from Efficient Enabled (as it was before) :(

**Comment by lucidnx** [comment]
That's why I asked for some drop-down menu because other's may need different options.

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/10961666/GHelper.zip)

**Comment by lucidnx** [comment]
I see menu, it does not change with perf. profile? I can not test battery/DC now.

**Comment by seerge** [comment]
It changes only AC, DC you can set to disabled and forget :)

**Comment by lucidnx** [comment]
Ah great! Thanks a lot :)

**Comment by seerge** [comment]
Ok, pushed live in https://github.com/seerge/g-helper/releases/tag/v0.26.1
