### ISSUE TITLE
Anime matrix control is missing @ ROG Zephyrus Duo 16

### ISSUE THREAD

**Issue by mvegetto** [seerge/g-helper#768]
**Describe the bug**
Anime Matrix control is missing.

**Expected behavior**
Anime Matrix is shown/visible

**App Logs**
``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/12030983/log.txt)

**Screenshots or screencasts**

![image](https://github.com/seerge/g-helper/assets/30373440/c635a058-603d-4b3b-bfd9-9e7da17bbc1c)

**Desktop **
 - OS: Windows 11 Home 22H2
 - Laptop model: ROG Zephyrus Duo 16 GX650PY

**Asus software**
- MyASUS installed
- Other Asus (8) services running in background

**Additional context**

**Comment by seerge** [comment]
@mvegetto you don’t have anime matrix on your device

**Comment by kxxoling** [comment]
Also not on my ROG Zephyrus G14 GA402XV laptop.

**Comment by seerge** [comment]
@kxxoling i can assume your device also doesn't have animatrix in a first place.
