### ISSUE TITLE
GPU memory clock offset 

### ISSUE THREAD

**Issue by SauronSkywalker** [seerge/g-helper#771]
gx650py，
i can set memory clock offset to 300mhz in armoury crate
Hopefully ghelper can also provide the GPU memory clock offset to 300or higher，It would be great to also provide  base clock offset over 250mhz to higher frequencies

**Comment by seerge** [comment]
@SauronSkywalker you can do that as well, but via config https://github.com/seerge/g-helper/discussions/654 :) 
I'm not a big fan for extending slier range for everyone yet, as people will eventually hang their GPUs and come blaming app on reddit :)

**Comment by SauronSkywalker** [comment]
Thank you, I have learned how to operate, thank you for providing this parameter support
