### ISSUE TITLE
Laptop Screen control vanishes when display is turned off

### ISSUE THREAD

**Issue by mvegetto** [seerge/g-helper#773]
**Describe the bug**
Laptop Screen control vanishes when display is turned off for awhile (Power Options @ windows is set to 3 minutes to turn display off. 

When I actually close the lid and open the lid and restart G-Helper it's showing the Laptop Screen Control again.

**Expected behavior**
Laptop Screen control is visible in G-Helper at all time.

**App Logs**
 ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/12037836/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/30373440/c32a9fe9-19f4-4963-9fdb-e309a7ee79b3)

Expected:
![image](https://github.com/seerge/g-helper/assets/30373440/bf637c93-6e51-44b1-bd2b-6d839b2700f8)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 22H2
 - ROG Zephyrus Duo 16 GX650PY

**Asus software**
- MyASUS installed
- Other Asus services (8) running in background

**Additional context**

**Comment by seerge** [comment]
@mvegetto can you run this build and post a log from it ?
[GHelper.zip](https://github.com/seerge/g-helper/files/12037894/GHelper.zip)

**Comment by mvegetto** [comment]
> @mvegetto can you run this build and post a log from it ? [GHelper.zip](https://github.com/seerge/g-helper/files/12037894/GHelper.zip)

Sure will do, will report my findings.

**Comment by mvegetto** [comment]
> > @mvegetto can you run this build and post a log from it ? [GHelper.zip](https://github.com/seerge/g-helper/files/12037894/GHelper.zip)
> 
> Sure will do, will report my findings.

See below the new logging:
[log.txt](https://github.com/seerge/g-helper/files/12038266/log.txt)

**Comment by seerge** [comment]
@mvegetto is this for the case when display UI is hidden only?

I just see that windows returns only 2 displays, an non of them is marked as **internal** (i.e. normal laptop screen)

```
13/07/2023 12:25:30: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
13/07/2023 12:25:30: :DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL
13/07/2023 12:25:30: \\.\DISPLAY1
13/07/2023 12:25:30: \\.\DISPLAY5
```

Can you post a log from the case when you still can change refresh rate ?

**Comment by mvegetto** [comment]
> @mvegetto is this for the case when display UI is hidden only?
> 
> I just see that windows returns only 2 displays, an non of them is marked as **internal** (i.e. normal laptop screen)
> 
> ```
> 13/07/2023 12:25:30: NE160QDM-NM4:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED
> 13/07/2023 12:25:30: :DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL
> 13/07/2023 12:25:30: \\.\DISPLAY1
> 13/07/2023 12:25:30: \\.\DISPLAY5
> ```
> 
> Can you post a log from the case when you still can change refresh rate ?

First log shows when display UI is hidden only. Second log shows the Laptop Screen.

Below the third log when I changed the refresh rates. It's now set to Auto instead of 240Hz + OD, that seems to help. I will now leave the display longer off.
[log.txt](https://github.com/seerge/g-helper/files/12038530/log.txt)

**Comment by seerge** [comment]
@mvegetto so it's working ok now ?

**Comment by mvegetto** [comment]
> @mvegetto so it's working ok now ?

When Laptop Screen is set to Auto it seems to be working fine :). Just checked again when screen was off for awhile.

![image](https://github.com/seerge/g-helper/assets/30373440/fcf87f29-9cd9-4613-878c-4c7116777588)

**Comment by seerge** [comment]
@mvegetto ok,

I have added some changes that should help app remembering which screen is internal a bit better in this build, so please try this one
[GHelper.zip](https://github.com/seerge/g-helper/files/12038757/GHelper.zip)

If it all works fine (in different scenarios) I will mark this as resolved

**Comment by mvegetto** [comment]
> @mvegetto ok,
> 
> I have added some changes that should help app remembering which screen is internal a bit better in this build, so please try this one [GHelper.zip](https://github.com/seerge/g-helper/files/12038757/GHelper.zip)
> 
> If it all works fine (in different scenarios) I will mark this as resolved

I tried it but after the display was turned off (after 3 minutes) it was vanished again. It doesn't occur when it's set to 'Auto', which is fine for me.
[log.txt](https://github.com/seerge/g-helper/files/12038844/log.txt)

**Comment by mvegetto** [comment]
> > @mvegetto ok,
> > I have added some changes that should help app remembering which screen is internal a bit better in this build, so please try this one [GHelper.zip](https://github.com/seerge/g-helper/files/12038757/GHelper.zip)
> > If it all works fine (in different scenarios) I will mark this as resolved
> 
> I tried it but after the display was turned off (after 3 minutes) it was vanished again. It doesn't occur when it's set to 'Auto', which is fine for me. Once I closed the lid with G-Helper still running in the background and open the lid again it came back once I opened G-Helper. [log.txt](https://github.com/seerge/g-helper/files/12038844/log.txt) Hold on testing different scenario's :).

Tested with 'Auto' again and the 240Hz + OD option. 'Auto' doesn't make it vanish.

**Comment by seerge** [comment]
@mvegetto auto would (try to) set correct (60hz for battery / max for charger) refresh rate every time laptop is started or wakes up. So that's why.

I still don't know why windows doesn't always return correct displays / refresh rates w/o setting them :) but glad it has worked out.
