### ISSUE TITLE
brightness controls while Fn lock is active are broken

### ISSUE THREAD

**Issue by NIGHTFURY2111** [seerge/g-helper#775]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
the brightness controls seem to be broken, i've tried it with asus optimizations on and off, also restated the pc but still its broken

**Clear scenario to Reproduce**

in my case it just doesnt work, even after a restart

**Expected behavior**
"the F7 key is supposed to reduce the brightness while the F8 should increase it"

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12040339/log.txt)

**Screenshots or screencasts**
as you can see in the recording provided, first i've used the F7 and F8 keys with Fn lock on and then with Fn lock off
https://github.com/seerge/g-helper/assets/65185393/13c233d9-b652-4c03-b2ed-17a520fbde81

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model:- ASUS TUF Gaming A15 FA506QM

**Asus software**
- Armoury crate (or it's services installed)
- MyASUS installed
- Other Asus services running in background:-
- i've tested it with asus optimizations services both on and off 

**Additional context**

**Comment by seerge** [comment]
@NIGHTFURY2111 hello, 

From log I see that app sends brightness command and it's accepted.

Even more - on your recording (bottom) notification is windows own (i.e. it's windows is supposed to change brightness and then it shows it). 

Does brightness slider (if you click on battery icon) work for you at all?  mb it's some issue with drivers / system ?
![Screenshot 2023-07-13 164147](https://github.com/seerge/g-helper/assets/5920850/dd133f96-50e4-41a0-b01c-4a4672d05832)

**Comment by NIGHTFURY2111** [comment]
@seerge Hello,
thanks for such a quick response.
yes, the brightness does change when the F7 and F8 keys are pressed, it's just that whether the brightness will increase or decrease is random.
In the video I've shared, all I have done is hold F7, and as you can see the brightness percentage is all over the place.
Even simply tapping the F7 and F8 keys, will randomly increase or decrease the brightness

**Comment by NIGHTFURY2111** [comment]
@seerge Hello,
thanks for such a quick response.
yes, the brightness does change when the F7 and F8 keys are pressed, it's just that whether the brightness will increase or decrease is random.
In the video I've shared, all I have done is hold F7, and as you can see the brightness percentage is all over the place.
Even simply tapping the F7 and F8 keys, will randomly increase or decrease the brightness

(sorry I accidentally closed the issue, I'm new to GitHub 😅)

**Comment by seerge** [comment]
@NIGHTFURY2111 i see, currently some people with TUF devices mentioned that native brightness controls didn't work for them, so i have added extra "manual" adjustments over that.

But it seems like in your case native works fine.

Can you try this build ?

[GHelper.zip](https://github.com/seerge/g-helper/files/12042870/GHelper.zip)

**Comment by NIGHTFURY2111** [comment]
@seerge i've tested the build u sent me and it works perfectly,
there's just one small issue, natively on my device, F7 decreases the brightness and F8 increases it, but when the Fn lock is on the keys switch their functions, F7 will increase and F8 will decrease the brightness.

Also F2-F4 control the volume n mute but they switch to aura controls.

Other than that, yes the original issue seems to be fixed with this new build
Thanks

**Comment by seerge** [comment]
@NIGHTFURY2111 actually app already sends Decrease brightness hotkey with F7 and increase with F8

You can even reproduce them manually in PowerShell (as admin) 

Decrease

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00100021; Control_status=0x10}
```

Increase

```
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x00100021; Control_status=0x20}
```

I can only assume that in your case they are swapped on bios level .... :| I'm not a big fan of swapping that as it may break other devices :) 

This build should have correct bindings for F2-F4

[GHelper.zip](https://github.com/seerge/g-helper/files/12043434/GHelper.zip)

**Comment by NIGHTFURY2111** [comment]
@seerge hello,
thanks, this build has the correct bindings for F2-F4
also i guess i can live with the brightness being flipped, atleast its not random

But it seems that F6, F10, F11 and F12 aren't working in this build😅
f6 is now print screen, F10 is just showing the current status of touchpad instead of toggling it, F11 is aura brightness toggle and F12 just isn't working

Also I'm sorry for bothering you this much

**Comment by seerge** [comment]
@NIGHTFURY2111 i didn't change anything related to F6 or any other keys you have mentioned.

**Comment by NIGHTFURY2111** [comment]
@seerge that explains a lot,
on my model F6 is to turn off the display, I guess printscreen is indeed better, and F10 works on the older builds, only this one is not working for some reason

**Comment by seerge** [comment]
@NIGHTFURY2111 try this build for F10
[GHelper.zip](https://github.com/seerge/g-helper/files/12044312/GHelper.zip)

**Comment by NIGHTFURY2111** [comment]
hey @seerge sorry for such a late reply,
Just wanted to let you know that the F10 is not fixed in this new build but its ok as i wouldn't want to accidently toggle it anyway
thanks for all the help :)

**Comment by seerge** [comment]
@NIGHTFURY2111 sorry, I have mistyped :) I meant that I have fixed F11 (not F10).
