### ISSUE TITLE
Maybe add a fourth or even more preset buttons that allow customization

### ISSUE THREAD

**Issue by AndreaFrederica** [seerge/g-helper#779]
**Is your feature request related to a problem? Please describe.**
Maybe add a fourth or even more preset buttons that allow customization
**Describe the solution you'd like**
Add a fourth and more preset buttons that allow customization
**Describe alternatives you've considered**

**Additional context**
None

**Comment by seerge** [comment]
@AndreaFrederica hello, I didn't completely get what you want. 

But G-Helper doesn't control fan speeds in real-time. I can set one of predefined modes (in bios, that consist of set of performance settings / limits and some default curves). You can't decouple that . In Armoury it works exactly same. 

But you you can run any other app next to it, that will set whatever custom settings it does if you need so :)

**Comment by AndreaFrederica** [comment]
I found a program called "IntlThrdSchd" that helps E-Core run better, but this program needs to be used with Windows Power Plan.
I have observed that G-Helper takes over the effect of Windows Power Plan on the CPU.
Is this how G-Helper works?
Is it possible to make G-Helper control the CPU according to Windows Power Plan?

**Comment by AndreaFrederica** [comment]
I re-read the documentation for the software just now, and I think the requirement should just be the ability to add a fourth preset button that allows customization.
Thank you very much for reading my issue!

**Comment by seerge** [comment]
@AndreaFrederica G-helper doesn't take over windows power plans. 

G-helper works with any power plan selected, and I recommend using [default (Balanced) windows power plan](https://github.com/seerge/g-helper#recommendations-optional). The only thing it adjusts is called "power mode" in windows :

![Screenshot 2023-07-14 123413](https://github.com/seerge/g-helper/assets/5920850/3e497a22-471d-4c6d-b7ce-1d5702dc3fd5)

But you can disable that by unchecking "Auto adjust windows power modes" under Extra screen.

**Comment by AndreaFrederica** [comment]
Yes I managed to redirect the GHelper to the power plan I needed and it's working fine now.
Can you add more preset options to GHelper though?
Thanks for informing me how GHelper works!

**Comment by seerge** [comment]
You can add as many presets as you want, by cloning currently selected one and pressing [+] (top right) in fans+power

**Comment by AndreaFrederica** [comment]
Thanks for your help.
