### ISSUE TITLE
Shutdown when gaming for a while

### ISSUE THREAD

**Issue by DedSecer** [seerge/g-helper#780]
**Describe the bug**
My laptop will shutdown without any sign when gaming for a while.And after it shutdown, the power button won't work(I press the button but my laptop won't open) until 3 or 5 seconds later.I think it was the overheat that makes it shutdown.

Is there something I missed to config after using g-helper?

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12048531/log.txt)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Laptop model: rog flow x13 2022

**Asus software**
- Armoury crate (or it's services installed): I have uninstalled Armoury crate using uninstall tool.
- MyASUS installed: I have uninstalled MyASUS.
- Other Asus services running in background: g-helper show that 0 Ausu services running.

**Comment by seerge** [comment]
@DedSecer hello, I don't know why your laptops shuts down :) it's controlled by your windows and hardware. Check windows Event Viewer may be ? may be it overheats or something else happens?

Try to use some default mode, like turbo or balanced without any custom limits :)

**Comment by DedSecer** [comment]
Is there any way to config in the g-helper to avoid overheats?

**Comment by seerge** [comment]
@DedSecer you can limit CPU power , disable CPU boost , and make fan curve more aggressive (i.e. set higher RPMs)

**Comment by DedSecer** [comment]
Would it be useful if I lower the temp limits?

**Comment by seerge** [comment]
@DedSecer i mean set all fan curve dots higher like 
Pro tip : you can press SHIFT key and drag one dot and it will move all of them together

![Screenshot 2023-07-14 124557](https://github.com/seerge/g-helper/assets/5920850/e619eaf5-4457-48e6-ad71-9d05e8671702)

**Comment by flankedgonerogue** [comment]
I have the same issue, I am also pretty sure it's an overheating which is absurd because I use it on balanced mode (less power). I suspect it to be LM leak out. I will contact ASUS because I have warranty otherwise I am going to re-paste with PTM. I'll let you know. Also if you are looking around in event viewer, the error code is 6008. It's also weird because my thermals never reached the 96C that this laptop can easily handle.

**Comment by DedSecer** [comment]
Thinks for you informations.I set the temp limit to 85 and play my for for a while, my laptop won't shutdown so far.

**Comment by seerge** [comment]
@DedSecer oke, good luck.

I'm closing this, as this is not an issue with an app anyway :)
