### ISSUE TITLE
Minor UI Bug in 0.96

### ISSUE THREAD

**Issue by MrxSiN** [seerge/g-helper#781]
Since nobody mention it, ill just point it out here. Just some minor UI bug in 0.96. 
Didnt happen on 0.95.

![image](https://github.com/seerge/g-helper/assets/3771363/e2506590-b9a7-4b9a-b1d9-6343c7defb3f)

![image](https://github.com/seerge/g-helper/assets/3771363/8cf2bab3-8188-469c-8a4a-8e30a39fb14a)

**Comment by seerge** [comment]
@MrxSiN hello, this boild should fix it :) 
[GHelper.zip](https://github.com/seerge/g-helper/files/12049575/GHelper.zip)
