### ISSUE TITLE
GPU does not hit the same Clock Speed or Power usage as Armoury Crate

### ISSUE THREAD

**Issue by arizotaz** [seerge/g-helper#782]
**Describe the bug**
When Running a game on the ROG Zephyrus M16, the dGPU runs at a max of 1400MHz and only reaches about 80W of power draw with all sliders cranked.  However when using the Asus Armoury Crate, the GPU turbo's to 1800MHz and reaches 120W.

**Clear scenario to Reproduce**
1. Go to MSConfig, disable the Asus Armoury Crate Service, and restart the device
2. Test a game with HWINFO or the Nvidia Performance overlay on a make note of the clock speed and power draw
3. Go back to MSConfig, enable the Asus Armoury Crate Service, and restart the device
4. Test a game with HWINFO or the Nvidia Performance overlay on a make note of the clock speed and power draw

**Expected behavior**
Using GHelper, the GPU should turbo to the same clock speed and power draw that the Armoury Crate service does

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 -  ROG Zephyrus M16 (GU603ZW)

**Asus software**
- Armoury crate - Installed but not running/Services disabled
- MyASUS - Installed but not running/Services disabled

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12050629/log.txt)

**Comment by seerge** [comment]
@arizotaz try to uncheck Apply at custom power limits that you have and just use turbo mode. Does it still behave same?

**Comment by seerge** [comment]
@arizotaz i know, but please try to uncheck CPU limits.

As there is a special tweak for a few models (incl your M16 https://github.com/seerge/g-helper/issues/405) that sets a separate "manual" mode when CPU power limits are applied (cause otherwise M16 doesn't seem to follow power limits). 

So if you will uncheck limits it will use "turbo" instead  - and i want to check if that's the reason or not.

**Comment by arizotaz** [comment]
Ok, I'm sorry, and yes that is exactly the issue.  The GPU is not at 1800MHz drawing 115W of power

**Comment by seerge** [comment]
@arizotaz that's good to know
How does it behave in AC for you if you set Manual mode (and set same CPU limits there) , does it also limit your GPU ?

Also try this build (it won't use that "manual" mode at all for your device) 
[GHelper.zip](https://github.com/seerge/g-helper/files/12050776/GHelper.zip)

Can you check if 

1. GPU is unlocked with or without CPU limits applied
2. Are CPU limits honored if applied ?

**Comment by arizotaz** [comment]
AC does not limit the GPU unless on battery power, while I have seen this issue before, I had discovered it to be a bug with AC.
AC does not include any different options than what you provide in GHelper, however, dynamic boost is set to 20W and will pull power only if the CPU is under 40W or lower.

CPU limits are honored, PL1 has a max of 60W in AC (Which sucks) and a PL2 of 135W.  It will usually prefer 60 and almost never turbo (Which is why it sucks).

I will try the Build you included now

**Comment by arizotaz** [comment]
Yes, the build works.  With CPU limit enabled the device still allows the GPU to hit the propper power limit

**Comment by seerge** [comment]
@arizotaz good, but does CPU limit work? (i.e. does it actually limit as it was before)? if so I will just remove your device from the list where this "manual" mode fix is needed :) (apparently that was needed only for M16 from 2023)

**Comment by arizotaz** [comment]
Yes, I set the CPU to 40W on turbo and it is limited to 40W while still allowing the GPU to turbo. Likewise, my other profile which sets the limit to 135 unlocks the power limit on the processor while still allowing the GPU to turbo.

Thank you and I love your work

**Comment by seerge** [comment]
@arizotaz ok, then I will include this change in next release. Closing as completed.

**Comment by seerge** [comment]
@HeroProc what exactly do you change in addition to default modes ? Do I understand correctly that same happens also in AC's "Manual" mode as well (which is just Turbo + customizations under the hood).
