### ISSUE TITLE
Adding tablet/laptop mode control for Flow x13

### ISSUE THREAD

**Issue by ShenMinX** [seerge/g-helper#785]
For flow x13 owner, the most annoying thing about this device is that it locks your keyboard and trackpad, mess up your screen oritentation everytime the device tilt slightly to left or right. Basically the tent/tablet mode is triggered without you folding the laptop over 180 degree.

Apparently this problemt is also caused by Armour Crate. A easy solution would be uninstall it, but then you lost this reasonable funtionalty completely, and this is a 2in1 device after all. Could you add a this feature to g-helper, but make the mode change activate only if device is folded to the back? I mean if its hardware-wise possible to detect that... 

If there is not way for a automatic switch, a button in the G-helper to change the manual mode would also be great solution!

**Comment by seerge** [comment]
@ShenMinX hello,

Your screen rotation / keyboard is controlled by bios / windows, not by armoury (or any other app) Check similar issue https://github.com/seerge/g-helper/issues/726

The only thing that app does - is disables a touchpad automatically when laptop enters tablet mode / and enables when it leaves it.
