### ISSUE TITLE
“面板省电”功能

### ISSUE THREAD

**Issue by WongGunWei** [seerge/g-helper#789]
Armoury Crate系统设置中有个“面板省电”功能；
如果关闭这个功能，切换电池与电源供电的时候不会闪屏，即电池供电屏幕也会保持120hz刷新率，
如果开启这个功能，切换电池与电源供电的时候不就会闪屏一下，即电池供电屏幕会切换为60hz刷新率。
希望在这个软件中增加这个功能。

**Comment by seerge** [comment]
It exists in the app from the beginning, and called [Auto] in Laptop Screen

**Comment by WongGunWei** [comment]
我希望关闭面板省电功能，即电池供电时，保持120hz刷新，
但是我使用g-helper无法实现这个功能，即使我在g-helper使用【120HZ+OD】，但是我每次切换电池供电时，还是会闪屏一下，
需要在使用Armoury Crate关闭【面板省电】后，切换电池供电才不会闪屏。

**Comment by seerge** [comment]
@WongGunWei please read readme https://github.com/seerge/g-helper#recommendations-optional :) 

> It's not recommended to have "ASUS Smart Display Control" app running, as it will try to change refresh rates and fight with g-helper for the same function. You can safely uninstall it.
