### ISSUE TITLE
program wont start

### ISSUE THREAD

**Issue by wj104** [seerge/g-helper#79]
as expected I got the windows smartscreen warning and ran anyway, but the app never launched. it shows that it's running in task manager, but I can't get into it. is this a windows 11 issue maybe?

**Comment by seerge** [comment]
It starts in system tray, just click a ^ next to your tray, and look for GHelper Icon. Alternatively you can set task bar settings to always show this icon :)

**Comment by wj104** [comment]
oh gosh thanks. I am actually stupid because I saw the "G" logo and I thought it was Grammarly despite not having it installed.
