### ISSUE TITLE
Pop to confirm if dGPU should be shut down

### ISSUE THREAD

**Issue by gokulbalram** [seerge/g-helper#790]
When the GPU Mode is set to optimized, the app shuts the dGPU down, and if I'm not wrong, the app does this if the GPU is below 5% usage. This causes an issue for me where apps I use for work such as the Adobe Suite, and Blender, which don't always use the GPU, end up immediately crashing, resulting in data loss. Is it possible to add an option for the app to prompt the user if they would like to (force) shut down the GPU?

**Comment by seerge** [comment]
@gokulbalram if you have gpu dependant apps just use Standard mode, and switch to Eco manually when you want to. Its same 1 extra click as you would do in a popup

**Comment by gokulbalram** [comment]
Wow that was quick 😮

While that does make sense, I generally make sure to save my data, and rely on the app to turn the GPU off, as I always forget to turn the dGPU off manually, the issue really is more so the fact that I often times face issues with loose connections, where I lose power for a quick second, during which the app kills off the GPU, immediately killing the apps

Even if I have an option to get a reminder in the form of a notification which would simply inform me about the state of the GPU when the charger is disconnected, would be great, even if it meant I would have to shut the GPU off manually

**Comment by seerge** [comment]
@gokulbalram i don’t want to overload ui with extra popups / checkboxes to enable those popups, etc :)

If frequent power outages are common for you - then Standard mode is the one to go.

As a reminder about GPU state just make app tray icon always visible (in taskbar settings). Its green for Eco and Blue for standard :)
