### ISSUE TITLE
Scaling & padding

### ISSUE THREAD

**Issue by lucidnx** [seerge/g-helper#80]
I have 2 small issues with UI:
1. "Applied" text is overlaping with "Power Limits (PPT)" text/zone
2. when I switch between monitors, main window width is different (wider/thinner depending on which monitor it was started) and font size remains same (not scaled). my monitors are all 2K, one ultrawide - 100% scaling, another 16:9 100% scaling and 3rd is built-in with 125% scaling set in windows.
pic of Applied text:
![image](https://user-images.githubusercontent.com/53317668/224815557-a80676ca-5ad6-49c6-b1b6-0e079dd693e9.png)

**Comment by ke1ne** [comment]
Also
![image](https://user-images.githubusercontent.com/8934421/224818780-a5a0d1c6-a2cb-480b-b221-a12348d98627.png)

**Comment by seerge** [comment]
I have just re-uploaded another https://github.com/seerge/g-helper/releases/tag/v0.26 that should fix Applied label from @lucidnx and button from @ke1ne . As for scaling in windows - it is as terrible there as it could be. I have already spent like 3 hours trying to fix form sizing for different windows ...

**Comment by lucidnx** [comment]
maybe respawn/relaunch if something like that exist, I can see how this can be a big deal on 4K screen with 200% scaling or so... When you open GHelper on one monitor, it is fine. Problem exist only when switching scaling/resolutions maybe.

**Comment by seerge** [comment]
I use 200% on 4k, it looks fine

**Comment by lucidnx** [comment]
> I use 200% on 4k, it looks fine

sure, but when it's opened on 4K with 200% scaling and you switch to 2K 125% scaling, does the window change shape?

**Comment by seerge** [comment]
You can always do a fork, and propose changes in a pull request :) it's github after all.

**Comment by lucidnx** [comment]
> You can always do a fork, and propose changes in a pull request :) it's github after all.

Yeah, I wish I will know how to do it :) I have a lot other work to do so... not that soon...

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/10962044/GHelper.zip)
Is this better ?

**Comment by lucidnx** [comment]
Seems to be, I have tried it just with enabling 2nd screen, everything normal.

**Comment by seerge** [comment]
Great, pushed live in https://github.com/seerge/g-helper/releases/tag/v0.26.1
