### ISSUE TITLE
GHelper v0.98 version, Fn+f8 function abnormal

### ISSUE THREAD

**Issue by yboy23** [seerge/g-helper#800]
Hello, in the GHelper v0.98 version, I found the following problems:
1. The Fn+f8 key combination normally turns off/on the touchpad, but in GHelper v0.98 version, pressing this key combination always displays "on", and the function does not turn off/on.
2. In recent versions of the software, I found that ARMOURY CRATE does not appear after pressing M4. I would like to know how this function is realized? Did you change the BIOS? When I no longer want to use GHelper, how should I restore the function of pressing M4 to pop up ARMORY CRATE?

**Comment by seerge** [comment]
@yboy23 given that you have ignored all details and didn't include logs, i can't help you with your touchpad button.

As for M4 button it's intercepted either by g-helper or by armoury, if you would install and run armoury with all it's services - it will open itself by m4 as well.

**Comment by yboy23** [comment]
非常抱歉，前面我说错了，应该是Fn+F10，我的型号是ASUS TUF Gaming F15 FX507VV。我的触摸板应该是没有问题的，之前通过ARMOURY软件的Fn+F10,是可以实现触摸板的关/开。但是在GHelper v0.98 version中，只会显示“触摸板 on”，不会实现相应功能。另外，我需要如何向您提供相关日志呢？
另外，在我把G-helper所有文件都删除了之后，M4仍无法弹出ARMOURY。
<img width="154" alt="image" src="https://github.com/seerge/g-helper/assets/130129509/a4794bfb-2eca-462c-a31a-b4e074d56ef5">

**Comment by seerge** [comment]
@yboy23 since you have TUF , there is no known way for me to disable touchpad there https://github.com/seerge/g-helper/issues/738

If you really need a hotkey, you can enable and start Asus Optimization Sevice and it will handle hotkeys instead (inc touchpad)
