### ISSUE TITLE
Does not always switch refresh rates when it should

### ISSUE THREAD

**Issue by Aashishkebab** [seerge/g-helper#801]
**Describe the bug**

**Clear scenario to Reproduce**
1. Set screen refresh to Auto.
2. Unplug device.
3. Hibernate Windows.
4. Plug in device.
5. Start PC.
6. The refresh rate will remain at 60hz.

**Expected behavior**
When powering on the device from sleep or hibernate in a different power state than when shut off, G-Helper should still switch the mode of the refresh rate.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12075003/log.txt)
Timestamp 9:54 is the most relevant.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: X16

**Asus software**
- No Asus apps installed except Control Interface driver.

**Comment by seerge** [comment]
@Aashishkebab hello,

I see that it tries (twice), but in both cases windows (as it uses win API to set refresh rates) refuses that 
```
7/15/2023 1:45:45 PM: Screen = 165Hz : -1
7/15/2023 1:45:46 PM: Screen = 165Hz : -1
```

Can you try latest v0.98 and post a log here ? i have changed screen device detection there a bit

**Comment by seerge** [comment]
@Aashishkebab did you had a chance to check this build ?

**Comment by Aashishkebab** [comment]
> @Aashishkebab did you had a chance to check this build ?

No not yet sorry, I'll do it today.

**Comment by Aashishkebab** [comment]
Hello,

Neither the update nor the build you sent me fix the issue:

```
7/19/2023 10:13:13 PM: Power Mode Changed
7/19/2023 10:13:13 PM: AutoSetting for Offline
7/19/2023 10:13:13 PM: Optimization service is running
7/19/2023 10:13:13 PM: Mode = 0 : OK
7/19/2023 10:13:13 PM: FanCPU = 14-2F-39-44-4A-50-5E-64-00-00-00-00-05-0C-1D-63 : OK
7/19/2023 10:13:13 PM: FanGPU = 1E-2E-38-44-4E-54-5C-64-00-00-00-00-09-11-1E-63 : OK
7/19/2023 10:13:13 PM: FanMid = 1E-3A-3D-45-4C-55-5D-64-00-00-00-01-07-12-1D-63 : OK
7/19/2023 10:13:13 PM: Boost 3
7/19/2023 10:13:13 PM: Eco flag : 0
7/19/2023 10:13:13 PM: Mux flag : 1
7/19/2023 10:13:13 PM: \\.\DISPLAY1
**7/19/2023 10:13:13 PM: Screen = 60Hz : -5**
7/19/2023 10:13:14 PM: Timeout:5D-BA-C5-C4-00
7/19/2023 10:13:14 PM: PowerLimit A0 = 17 : OK
7/19/2023 10:13:14 PM: PowerLimit A3 = 17 : OK
7/19/2023 10:13:14 PM: PowerLimit C1 = 23 : OK
**7/19/2023 10:13:14 PM: Screen = 60Hz : -1**
7/19/2023 10:13:14 PM: ScreenOverdrive = 0 : OK
7/19/2023 10:13:14 PM: BatteryLimit = 95 : OK
7/19/2023 10:13:14 PM: Auto:5D-BA-C5-C4-01
7/19/2023 10:13:14 PM: USB-KB 0x19B6:5D-BD-01-FF-1E-0F
7/19/2023 10:13:15 PM: Touchpad status:1
7/19/2023 10:13:15 PM: Tablet: False Touchpad: True
7/19/2023 10:13:15 PM: Monitor Power On
7/19/2023 10:13:15 PM: UV: -13 OK
7/19/2023 10:13:15 PM: iGPU UV: -11 OK
7/19/2023 10:13:18 PM: Auto:5D-BA-C5-C4-01
```

**Comment by Aashishkebab** [comment]
I did some of my own testing. G-Helper seems unable to change the refresh rate when the user sign-in is not unlocked. So even if I'm logged in, but the lock screen is there, G-Helper cannot change the refresh.

You can test by locking your screen with Windows + L, and then changing the power source.

**Comment by seerge** [comment]
@Aashishkebab for me it does set correct refresh rate (if it's set to Auto ofc) 

1. I have set wrong refresh rate via windows settings
2. Locked / turned off screen with WIN+L
3. Opened laptop again, and didn't login for like a minute
4. Then logged in and checked log

And I see all actions that should be done
```
7/20/2023 11:44:36 AM: WMI event 192
7/20/2023 11:44:36 AM: Monitor Power On
7/20/2023 11:44:36 AM: AutoSetting for Offline
7/20/2023 11:44:36 AM: Input: \\?\hid#vid_0b05&pid_19b6&mi_00&col01#8&18c99fbc&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
7/20/2023 11:44:36 AM: Mode = 2 : OK
7/20/2023 11:44:36 AM: Eco flag : 1
7/20/2023 11:44:36 AM: Mux flag : 1
7/20/2023 11:44:36 AM: \\.\DISPLAY1
7/20/2023 11:44:37 AM: Screen = 60Hz : OK
7/20/2023 11:44:37 AM: ScreenOverdrive = 0 : OK
7/20/2023 11:44:37 AM: BatteryLimit = 100 : OK
7/20/2023 11:44:37 AM: USB-KB 0x19B6:5D-BD-01-DF-1E-0F
7/20/2023 11:44:37 AM: USB-KB 64|32HID-compliant vendor-defined device\\?\hid#vid_0b05&pid_19b6&mi_00&col04#8&18c99fbc&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-00-FF-00-00-EB-00-00-FF-FF-FF-00-00-00-00
```

Does your windows user has administrator rights in general? May be it's some weird unknown policy settings in windows, that prevent that in your specific case . I can't really help here :)

Also keep in mind, that app runs refresh rate command literally immediately after screen is turned on. So in 99% of the cases use won't be logged in on that moment (unless you are blazing fast). But that works (or it will be millions of issues / complains on reddit about that here)

**Comment by Aashishkebab** [comment]
My user account is administrator.

Steps:
1. Unplug computer.
2. Lock computer with Windows s+ L.
3. Plug in computer.
4. 
```
7/20/2023 11:23:12 AM: Timeout:5D-BA-C5-C4-00
7/20/2023 11:23:12 AM: WMI event 207
7/20/2023 11:23:12 AM: WMI event 88
7/20/2023 11:23:12 AM: Power Mode Changed
7/20/2023 11:23:12 AM: AutoSetting for Online
7/20/2023 11:23:12 AM: Input: \\?\hid#vid_0b05&pid_19b6&mi_00&col01#8&505ba48&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
7/20/2023 11:23:12 AM: Mode = 1 : OK
7/20/2023 11:23:12 AM: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
7/20/2023 11:23:12 AM: SET GPU CLOCKS: 155, 250
7/20/2023 11:23:12 AM: WMI event 123
7/20/2023 11:23:13 AM: FanCPU = 14-3B-42-47-4D-52-57-5A-11-13-19-22-2B-36-48-63 : OK
7/20/2023 11:23:13 AM: FanGPU = 14-3F-44-48-4C-51-55-5A-16-1F-26-2B-33-43-50-63 : OK
7/20/2023 11:23:13 AM: FanMid = 14-3F-44-48-4C-51-55-59-11-1A-22-29-31-3F-4D-63 : OK
7/20/2023 11:23:13 AM: Boost 2
7/20/2023 11:23:13 AM: Eco flag : 0
7/20/2023 11:23:13 AM: Mux flag : 1
7/20/2023 11:23:13 AM: \\.\DISPLAY1
7/20/2023 11:23:13 AM: Screen = 165Hz : -1
7/20/2023 11:23:14 AM: PowerLimit A0 = 150 : OK
7/20/2023 11:23:14 AM: PowerLimit A3 = 150 : OK
7/20/2023 11:23:14 AM: PowerLimit C1 = 150 : OK
7/20/2023 11:23:14 AM: Screen = 165Hz : -1
7/20/2023 11:23:14 AM: ScreenOverdrive = 1 : OK
7/20/2023 11:23:14 AM: BatteryLimit = 95 : OK
7/20/2023 11:23:15 AM: USB-KB 0x19B6:5D-BD-01-FF-1E-0F
7/20/2023 11:23:15 AM: Auto:5D-BA-C5-C4-03
7/20/2023 11:23:15 AM: Touchpad status:1
7/20/2023 11:23:15 AM: Tablet: False Touchpad: True
7/20/2023 11:23:16 AM: UV: -13 OK
7/20/2023 11:23:16 AM: iGPU UV: -11 OK
7/20/2023 11:23:16 AM: CPU Temp: 97 OK
7/20/2023 11:23:16 AM: APU Temp: 97 OK
```

**Comment by seerge** [comment]
@Aashishkebab I tried on G14 2022 all AMD, and on G16 Strix 2023 with Nvidia :) and tried few times. This shouldn't depend on laptop model , as it uses windows API to detect screens and set refresh rates, not something specific to Asus.

Since app runs already (even when you are not logged in), it will process monitor ON event before you log in and sets refresh rate successfully.

I don't know why it happens in your case, but also have no idea how to "fix" it :) If you do know - you are free to propose a fix as PR.

**Comment by seerge** [comment]
@Aashishkebab i was looking at your first log, and i see that sometimes 60hz fails on 1st attempt, and works from second. 

Try this build with 3 second delay between attempts, mb your windows is just so slow that it doesn't allow refresh-rate changes immediately when screen is on

[GHelper.zip](https://github.com/seerge/g-helper/files/12111760/GHelper.zip)

**Comment by seerge** [comment]
@Aashishkebab can you try a 3 second delay?

**Comment by Aashishkebab** [comment]
```
7/22/2023 12:30:32 PM: WMI event 123
7/22/2023 12:30:32 PM: Monitor Power On
7/22/2023 12:30:32 PM: AutoSetting for Online
7/22/2023 12:30:32 PM: Tablet: False Touchpad: True
7/22/2023 12:30:32 PM: Input: \\?\hid#vid_0b05&pid_19b6&mi_00&col01#8&505ba48&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
7/22/2023 12:30:32 PM: Mode = 1 : OK
7/22/2023 12:30:32 PM: GET GPU CLOCKS: 0, 0
7/22/2023 12:30:32 PM: SET GPU CLOCKS: 155, 250
7/22/2023 12:30:32 PM: FanCPU = 14-3B-42-47-4D-52-57-5A-11-13-19-22-2B-36-48-63 : OK
7/22/2023 12:30:32 PM: FanGPU = 14-3F-44-48-4C-51-55-5A-16-1F-26-2B-33-43-50-63 : OK
7/22/2023 12:30:32 PM: FanMid = 14-3F-44-48-4C-51-55-59-11-1A-22-29-31-3F-4D-63 : OK
7/22/2023 12:30:32 PM: Boost 2
7/22/2023 12:30:32 PM: Eco flag : 0
7/22/2023 12:30:32 PM: Mux flag : 1
7/22/2023 12:30:32 PM: :DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
7/22/2023 12:30:33 PM: Screen = 165Hz : -1
7/22/2023 12:30:33 PM: PowerLimit A0 = 150 : OK
7/22/2023 12:30:33 PM: PowerLimit A3 = 150 : OK
7/22/2023 12:30:33 PM: PowerLimit C1 = 150 : OK
7/22/2023 12:30:36 PM: Screen = 165Hz : -1
7/22/2023 12:30:36 PM: ScreenOverdrive = 1 : OK
7/22/2023 12:30:36 PM: BatteryLimit = 95 : OK
7/22/2023 12:30:36 PM: USB-KB 0x19B6:5D-BD-01-FF-1E-0F
7/22/2023 12:30:36 PM: USB-KB 64|32HID-compliant vendor-defined device\\?\hid#vid_0b05&pid_19b6&mi_00&col04#8&505ba48&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-02-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
7/22/2023 12:30:36 PM: Touchpad status:1
7/22/2023 12:30:36 PM: Tablet: False Touchpad: True
7/22/2023 12:30:36 PM: Auto:5D-BA-C5-C4-03
7/22/2023 12:30:37 PM: UV: -11 OK
7/22/2023 12:30:37 PM: iGPU UV: -11 OK
7/22/2023 12:30:37 PM: CPU Temp: 97 OK
7/22/2023 12:30:37 PM: APU Temp: 97 OK
7/22/2023 12:30:55 PM: Listener stopped
```

Hello, it still doesn't work. The only way I can get it to work is if I quickly log in before the second attempt. Maybe it can just keep re-attempting until it succeeds?
No matter what, it will not work when Windows is locked. I can also try to test on my cousin's X13 (but I sold that to him, and if I remember correctly, it had the same issue).

**Comment by seerge** [comment]
@Aashishkebab 
I have added an extra screen refresh action to an event when app detecs session Unlock (i.e. when you login):

Let me know if it helps

[GHelper.zip](https://github.com/seerge/g-helper/files/12136945/GHelper.zip)

**Comment by Aashishkebab** [comment]
> @Aashishkebab I have added an extra screen refresh action to an event when app detecs session Unlock (i.e. when you login):
> 
> Let me know if it helps
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/12136945/GHelper.zip)

Hello,

Yes that seems to fix the issue! It changes the refresh rate upon login. Thank you!

**Comment by seerge** [comment]
Oke, then I will try to include this in next release.

Closing as completed.
