### ISSUE TITLE
Extra wattage consumption by G15

### ISSUE THREAD

**Issue by Jokerr2** [seerge/g-helper#805]
My G15 was behaving fairly normally, i normally use it on eco mode to save battery life with the best possible battery optimization settings. About 4 weeks ago, when browsing through articles or reading on a browser, made my G15 discharge about anywhere from 8.7 to 9.8 watts and media consumption made it discharge from anywhere between 10 - 15 watts. I went on vacation and came back after 2 or 3 weeks and my G15 has been discharging anywhere from 10 to 14 watts while reading articles and etc while media consumption makes it discharge about 12 - 17 watts. I didn't change any settings and it doesn't seem like a temp issue since temps are pretty much the same. I checked task manager and i didn't see anything sus that was consuming more resources than it normally used to. I think its just the result of a stupid windows update but Ghelper did get a lot of updates as well, is there any world where Ghelper is secretly stealing resources because its driving me crazy that i cannot find the issue.

**Comment by seerge** [comment]
@Jokerr2 hello,

Unless you suddenly see GHelper.exe in task manager consuming some enormous amount of resources (it shouldn't). It doesn't affect your discharge rate anyhow :)

I would rather attribute your observations to some changes in windows (may be indexing runs in background)? or anything else. Just make sure that your have Eco / Silent and "Adjust windows power modes" selected in extra (or just set windows power mode to battery efficient one manually)
