### ISSUE TITLE
Custom Power Limits (Wattage) not being respected UNLESS "Apply Custom Fan Curve" is Enabled

### ISSUE THREAD

**Issue by Noisrevid** [seerge/g-helper#809]
**In bold below:**

**Describe the bug**

******THIS IS USING THE LATEST .98 version, also existed on .95, unsure of prior/older versions******
**On Fans and Power section, the Power Limits wattage isn't respected at all UNLESS "Apply Custom Fan Curve" is enabled (This is on a 2023 G14 GA402XV**

**Clear scenario to Reproduce**
**1. Go to Fans and Power section, select 5 watts, leave fan curve on factory defaults, the CPU will boost to regular "Silent, Balanced, or Turbo" specifications (Run a CPU load test of your choice and log your watts under load to see that it's not respecting what you've chosen for a power limit)
2. Enable "Apply custom fan curve" and the wattage you choose now works (eg. 5 watts) as proven with HWInfo under load.  Using a Cinebench R23 for load testing.**  

**Expected behavior**
**I would expect that I should be able to use the factory default fan curves, but still change the power wattage of the CPU.**

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12081594/log.txt)
 

**Screenshots or screencasts**
**Pretty self explanatory, don't think we need a screenshot but let me know if you'd like one.**

**Desktop (please complete the following information):**
 **- OS:  Windows 11
 - Laptop model  2023 G14 GA402XV**

**Asus software**
**No Asus software installed (Fresh Win11 install)**

****Final notes for me personally, not a huge deal since I usually have a custom fan profile, but sometimes i'd just like the machine run it's default fan curves, but for example run at 15 watts max power to keep temps down under load.**

**Comment by seerge** [comment]
@Noisrevid some model bioses are unfortunately require that (as in Armory you can't apply only limits, they are always paired with fan profiles in manual mode).

Currently there are 2 models known to me that behave like that GA402XI and (G14 2023 4070) and G513 (G15). For them app will just automatically force custom fan profile (using default curve) when power limits are selected.

I can add your model to the list as well. Do you know if it's same for all G14 with 4060 ? Do you use latest bios (310 i think?)

Try this build 

[GHelper.zip](https://github.com/seerge/g-helper/files/12081671/GHelper.zip)

**Comment by seerge** [comment]
@Noisrevid well, so far only 1 guy with 4070 reported that. I know bunch of users with 4080 models that don't seem to have that issue. So I just manually add models to the list where "manual" curve is mandatory.

It could be that only 4050-4070 models are affected, or people just use that and don't care )

**Comment by joe-700** [comment]
I have the 4080 version BIOS 310 and this is the case for me as well. I just ensure that I apply the custom fan curves and that sets the power limit

**Comment by seerge** [comment]
@joe-700 what's your model name?

**Comment by seerge** [comment]
In this build all models containing "GA402X" in it's name will also apply fan curve under the hood :) 
[GHelper.zip](https://github.com/seerge/g-helper/files/12083713/GHelper.zip)

**Comment by Noisrevid** [comment]
New build works great for my model.. :)
