### ISSUE TITLE
[Bug] Multiple error messages in GHelper\log.txt: Failed reading sensors

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#81]
Well, as described. Got kind of 40 messages for 2 mins of app work. It seems to happen when the main window appears.
Win 11, G15 2021, v0.26.00

**Comment by seerge** [comment]
but do CPU / GPU temps  work for you ?

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/10961681/GHelper.zip)
can you check this build, and tell what sensor exactly is failing ? :)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/10961705/GHelper.zip)
Can you check this build, and tell what sensor exactly is failing ? :)

**Comment by lucidnx** [comment]
I don't see any errors in log file. @ latest pre-release

**Comment by seerge** [comment]
@ke1ne , can you check if it still happens in https://github.com/seerge/g-helper/releases/tag/v0.26.1 ?

**Comment by ke1ne** [comment]
> @ke1ne , can you check if it still happens in https://github.com/seerge/g-helper/releases/tag/v0.26.1 ?

That's OK now. Thank you!
