### ISSUE TITLE
Keyboard backlight doesn't turn back on after switching the display off then on

### ISSUE THREAD

**Issue by SampRession** [seerge/g-helper#811]
Hey,
Firstly, a huge thanks for your app ! Love it !
It does a better work than Asus ones :) While being a lot lighter !

I started using it since 0.82, after failing to solve a problem with my keyboard backlight. And it fixed it, while allowing me to uninstall all unnecessary asus softwares.

Until now, I haven't had any problems with GHelper, but today, I installed the v0.98, and the above-mentioned issue reappeard.

Here's a description :
When I switch off my screen, the keyboard BL turns off, as desired. But when I turn my screen back on, and the BL stays off. Setting the brightness level to 0 and then 1 has no effect.
I have to switch between light modes to make it reappear. 
It happens too when I wake up my pc from sleep.

So, I downloaded 0.95 again, and with this version, this issue no longer occurs.

1. Have backlight on
2. Turn off screen / make the pc sleep
3. Turn the screen back on / wake up pc
4. Backlight remains off instead of turning on again

App log : 
[log_23-07-18.txt](https://github.com/seerge/g-helper/files/12088244/log_23-07-18.txt)

 - OS: Windows 10
 - ROG Strix III - G731GU (2019)

- MyASUS installed
- Other Asus services stopped with GHelper

I hope this problem is easy to solve :)
Thanks again for your awesome app 🧡

**Comment by SampRession** [comment]
@seerge Specific to 0.98 (I mentioned it in the issue text 😊), doesn't happen with all the previous stable versions I tried.
Thanks for your quick answer !

**Comment by seerge** [comment]
@SampRession ok, can you check if this works ?
[GHelper.zip](https://github.com/seerge/g-helper/files/12088499/GHelper.zip)

**Comment by SampRession** [comment]
Wow ! I've never seen such a quick and efficient problem solving !
Yep, it works like a charm now :) Good job !

Thanks a lot ! 🧡

**Comment by seerge** [comment]
@SampRession great, I will try to include this in next release then.

**Comment by seerge** [comment]
@SampRession can you check if this build still works ? (in all possible circumstances)

[GHelper.zip](https://github.com/seerge/g-helper/files/12088610/GHelper.zip)
