### ISSUE TITLE
Fan not ramping to correct RPM 

### ISSUE THREAD

**Issue by musm** [seerge/g-helper#812]
![image](https://github.com/seerge/g-helper/assets/4319522/6d4e27c7-d779-498e-a558-52fe62977bc1)

According to the CPU fan profile at 96% the fan should be at 5800 RPM+, however clearly we see that the fan is at the lower 4900 RPM

I've observed this with other profiles as well.

**Comment by seerge** [comment]
@musm On your chart dot is set to 98C, and your CPU is at 96C so i assume it follows previous dot . 

As for RPMs, axis there are only indicational and it's up to your BIOS how to control fans (app doesn't do that)

**Comment by musm** [comment]
Ahh I think I see the issue, I should've selected "Apply Custom Fan Curve". Without selecting this the displayed fan curve does not agree with the applied fan RPM
