### ISSUE TITLE
[Feature request] Touch pad toggle

### ISSUE THREAD

**Issue by SonyStone** [seerge/g-helper#815]
Sometimes my hand hits the touchpad when typing, and getting into Armory Crate to switch the touchpad isn't very handy.

![image](https://github.com/seerge/g-helper/assets/8790196/c7926d9f-5350-4745-86b6-8594c5da699d)

**Comment by seerge** [comment]
@SonyStone that feature already exists and is under FN+F10 hotkey (or just F10 with fn-lock on) :)

**Comment by Yury-M-Leh** [comment]
God I wish it was a toggle too. So much niche stuff has been implemented.
