### ISSUE TITLE
Asus Zephyrus G16 - GU603VV

### ISSUE THREAD

**Issue by umumpaul** [seerge/g-helper#821]
![image](https://github.com/seerge/g-helper/assets/10173491/6fb26d76-b392-468d-8ecd-3ab6f4f2b42f)

CPU Intel i7-13620H

I can only see CPU Slow (SPL + sPPT) setting. Whereas in Armoury Crate I can see setting for PL1 and PL2. I am not sure if it is bug or work as intended. Thanks.

**Comment by seerge** [comment]
@umumpaul hello , SPL stands for sustained power limit (i.e. PL1 in Intel world), and sPPT is Slow PPT - (i..e PL2 for Intel), that slider just limits both values at the same time :)

**Comment by seerge** [comment]
@umumpaul I have renamed slider for Intel CPUs to PL1 + PL2, so it's more clear what it is :) 

You can check this build
[GHelper.zip](https://github.com/seerge/g-helper/files/12100376/GHelper.zip)

**Comment by umumpaul** [comment]
Thanks!

**Comment by umumpaul** [comment]
I was asking because there are 2 slides (PL1 and PL2) instead of 1 in Armoury Crate.
