### ISSUE TITLE
Add optional hotkey or action for Insert key to Key Bindings

### ISSUE THREAD

**Issue by Stormwind99** [seerge/g-helper#823]
**Is your feature request related to a problem? Please describe.**
The ROG Zephyrus G14 2023 and other notebooks are missing the Insert key on their keyboard. Some programs, such as terminal emulators, use  the Insert key or shift-Insert for actions like paste.

**Describe the solution you'd like**
Add an optional hotkey or action for Insert key to the action options for hotkeys in Key Bindings.

**Describe alternatives you've considered**
Other programs like AutoHotKey allow writing a script for a hotkey, but it involves multiple steps and another program running using power.

**Comment by seerge** [comment]
@Stormwind99 hello, you can already achieve that with any of Macro keys as explained https://github.com/seerge/g-helper#custom-hotkey-actions

Just use  ``0x2D`` as a key value in custom field

**Comment by Stormwind99** [comment]
I totally missed that in the docs! Thanks!
