### ISSUE TITLE
GV302 laptop screen state not properly detected since v0.98

### ISSUE THREAD

**Issue by ct16k** [seerge/g-helper#825]
**Describe the bug**
Versions newer than v0.97 seem to not properly detect the state and refresh rates for GV302XI built-in screen. While v0.97 would properly detect screen as being disabled in my setup (using just the one external monitor), v0.98 and v0.99 do not report the display as being off anymore and allow me to select refresh rate. (see screenshots below)

What's more, the detected refresh rates seem to be wrong as well, or at least one of them, as besides 60Hz the other refresh rate reported is 75Hz, instead of 165Hz (arguably prior versions weren't better in this regard either, showing 120Hz instead of 165Hz). Though maybe this is what that `+ OD` stands for and there's no issue here, just with the display's state.

**Clear scenario to Reproduce**
1. Download and run v0.98 or newer
2. Open main window

Laptop screen is not detected as disabled and refresh rate can be changed.

**Expected behavior**
Same as v0.97 and earlier, detect display is off and don't allow choosing refresh rate.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12098206/log.txt)
[config.json](https://github.com/seerge/g-helper/files/12098250/config.json.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/7895891/ab715d98-6d24-4a1a-8126-fb38d3d04284)
![image](https://github.com/seerge/g-helper/assets/7895891/4cdca876-37b4-45fb-a1fd-c724feb32bc8)

**Desktop (please complete the following information):**
 - Windows 11 Pro
 - GV302XI

**Asus software**
- Armoury Crate installed
- MyASUS installed
- All Asus services stopped

**Comment by seerge** [comment]
@ct16k hello, it indeed can happen if nvidia display is set to nvidia GPU (and not optimus)
I have already uploaded a hotfix over existing 0.99 https://github.com/seerge/g-helper/releases/tag/v0.99 so you can just re-downlaod it :)

**Comment by ct16k** [comment]
Can confirm issue is now fixed. Thank you!
