### ISSUE TITLE
Sleep check box doesn't restore the option - FX507ZV4 

### ISSUE THREAD

**Issue by noInk** [seerge/g-helper#827]
Hey.
I don't yet know exactly why but unchecking the "sleep" option and checking it back doesn't make the sleeping animation return.
Model: FX507ZV4
The laptop also appear to require the HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\F15576E8-98B7-4186-B944-EAFA664402D9 set to 2 on Attributes to be able to sleep on clean install WINDOWS 10. 

ASUS service stopped.

Context
Using a USB mouse on the USB2 port sometime cause a fail in the sleep transition to S0.
Using a USB storage device on the USB3 port cause the animation to return.

Is this expected? doesn't seems to happen on Armory Crate.
Awesome application, if there is anything you'll might need to get it working lemme know.
Regards

[log.zip](https://github.com/seerge/g-helper/files/12099327/log.zip)

**Comment by seerge** [comment]
@noInk hello. I see that app sends it's "payload" to bios (for tuf models) to set all RGB animations

```
19/07/2023 20:44:55: TUF_KB = 16712125 : OK
19/07/2023 20:44:55: TUF RGB = B4-01-FF-00-00-EB-00-00-00-00-00-00 : OK
19/07/2023 20:44:55: TUF Brightness = 130 : OK
```

Everything is accepted.

May be your laptop doesn't go to sleep at all ?

**Comment by seerge** [comment]
@noInk the only thing you may want to check, in recent version i have added this keyboard initialization on each app start / wake up (before it would set it only when you actually check something or uncheck)

Can you check older version https://github.com/seerge/g-helper/releases/download/v0.95/GHelper.zip if it also behaves same ?

**Comment by seerge** [comment]
@noInk I didn't really get you to be honest, what do you mean under "managed by windows" ? Is your windows having troubles going into sleep? To be honest this is not something that app controls in any way :)

**Comment by seerge** [comment]
@noInk i see, well anyway g-helper doesn't interfere with windows settings anyhow. 

The only thing it adjusts in power plan - is CPU boost (and only when user changes that in UI), but that's irrelevant to sleep.

I wish you good luck in figuring out laptop sleep issues, and closing this issue and there is nothing can be done on the app side for that :)
