### ISSUE TITLE
Dont know if its just me

### ISSUE THREAD

**Issue by ShadowGamerROG** [seerge/g-helper#829]
Hello Seerge! I used Ghelper for about a day and uninstalled becuase I was getting crazy lag on youtube. I uninstalled to see if the issue was Ghelper and after a while, yes the issue cleared. I just reinstalled Ghelper today because my laptop is always running warm, even while unpluged and watching youtube, but I still get the video lag and it drives me crazy. I am using Opera GX and idk if its just the browser that Ghelper doesnt like, but let me know please! I would love to use youre app it works great and is simple

**Comment by seerge** [comment]
@ShadowGamerROG hello.

What do you mean under "installing" and "uninstalling" ? It's just a single exe, that does nothing when does't run. 

I have no idea what happens with your opera, but g-helper doesn't have anything to do with that :) It just switches between pre-defined modes in bios, and sets some other settings.

Given that you have ignored all details asked in original issue, and didn't provide any debug info or a log, I can't help further and closing this.
