### ISSUE TITLE
Check Update Versions are blocked by Antivirus 

### ISSUE THREAD

**Issue by MuratDugan** [seerge/g-helper#83]
Check Update Versions are blocked by Antivirus 

![image](https://user-images.githubusercontent.com/111883464/224956198-155b9ae3-0875-4756-98af-44feca7f3184.png)

https://www.virustotal.com/gui/file/bdc60788c9dd19f8da2cfdd14edf4dd0746930ff700cb6c57999b77568d9bb85/detection

**Comment by MuratDugan** [comment]
I love your work btw <3

**Comment by seerge** [comment]
Hm, i'm not getting that warning from defender. But in general - defender is known for false positives :) it's not much I can do. You can always compile app from sources if you have trust issues :))

**Comment by MuratDugan** [comment]
yes, I didn't get any virus warning when I compile it myself. 
Even after deactivating the anti virus, 
extracting the archive, 
deleting the archive and running the program,
after activating the antivirus again, it did not give a virus warning :))

This may be the solution steps for those who receive false positive warnings that cannot compile themselves.

**Comment by seerge** [comment]
I usually submit stable versions to microsoft for verifications, it helps with defender sometimes too.
