### ISSUE TITLE
Pressing ROG button pops up two windows

### ISSUE THREAD

**Issue by Aashishkebab** [seerge/g-helper#830]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
Sometimes (randomly) when pressing the ROG button, this extra dialog from ArmouryCrateKeyControl.exe will pop up:
![image](https://github.com/seerge/g-helper/assets/25588487/37212e8d-27c0-4d58-b931-adfdfb7a40cc)

**Clear scenario to Reproduce**
1. Press the ROG button.

**Expected behavior**
Only G-Helper to open.

**App Logs**
`7/20/2023 4:53:15 AM: WMI event 56`

**Desktop (please complete the following information):**
 - OS: Windows 11
 - X16

**Asus software**
Only Control Interface. Which installs a lot of extra bloat with it.

**Additional context**
This is not an issue with G-Helper itself, but it may be useful for G-Helper to kill or at least warn about ArmouryCrateKeyControl.exe.

**Comment by seerge** [comment]
@Aashishkebab this is a very first item in FAQ, you need to stop AC service to prevent that
https://github.com/seerge/g-helper#how-do-i-stop-the-armory-crate-install-popup-appearing-every-time-i-press-the-m4--rog-key
