### ISSUE TITLE
Disable all LEDs on sleep mode

### ISSUE THREAD

**Issue by dewzor** [seerge/g-helper#831]
Ive disabled all lights in g-helper and set backlight to 0 through keyboard shortcuts.. Still its "breathing" in sleep mode with bright LEDs. If i can disable this in G-Helper then G-Helper is a PERFECT replacement for Armory crate.

Im currently using type C charger with power saving settings. The LEDs are eating the battery and type C cant keep up. Thanks for the app btw, its great!

**Comment by seerge** [comment]
@dewzor you need to uncheck SLEEP checkbox under Extra, that is responsible for that. 

Given that you have ignored all questions and logs originally asked when posting issue, i can't help further and closing this.
