### ISSUE TITLE
A bug about custom fans curves

### ISSUE THREAD

**Issue by Li-Qirun** [seerge/g-helper#839]
When I apply custom fans curves, the GPU fan always keep a low speed about 2000RPM no matter how high the temperature is.
My computer is ROG Zephyrus M16 GU603HM (2021).

**Comment by seerge** [comment]
@Li-Qirun i don't have extrasensory skill to guess what you apply. You didn't include any logs or any other debug information that was explicitly asked in a bugreport issue https://github.com/seerge/g-helper/issues/new?assignees=&labels=&projects=&template=bug_report.md
