### ISSUE TITLE
Power Limits issue on iGPU 

### ISSUE THREAD

**Issue by EvilKilla** [seerge/g-helper#84]
Hey seerge, I got the 2022 Version 6900HS / 6800S

I know setting PPT's is experimental, but there is something i don't really understand:

When i set On Turbo Mode Total PPT to .. let's say 50W and CPU also to 50 Watts and i run a game on iGPU, the total power consumption is limited to 20W. It's always limited on something i cannot set, when i set CPU PPT Lower than this '20W', it will consume what i set.

I made a list:

`Total PPT\Total Consumption: 40W\16W, 50W\21W, 60W\25W, 70W\30W, 80W\40W, 90W\45W...`

on dGPU no issues, only running games on iGPU

**Comment by seerge** [comment]
How does it work in armory crate ?

**Comment by EvilKilla** [comment]
i install it now, but i think i got no problems with armoury crate, be back in couple minutes

**Comment by seerge** [comment]
Well, tbh in armory it's APU (i.e. CPU + iGPU) in GHelper it's CPU only ... i can add APU too if needed

**Comment by EvilKilla** [comment]
This would be awesome. THX sserge, really

**Comment by seerge** [comment]
[GHelper (2).zip](https://github.com/seerge/g-helper/files/10972276/GHelper.2.zip)
Can you try this build ? I have quickly replaced CPU with APU

**Comment by EvilKilla** [comment]
![Bild_2023-03-14_200959634](https://user-images.githubusercontent.com/126384386/225111790-0624d2f6-3b38-41f3-8be8-30996b226bbb.png)

No Change

**Comment by seerge** [comment]
I was also looking at your screenshots, and I can't reproduce them. Even when I use latest release (that sets CPU limits), and set ECO mode on I get following readings from MSI afterburner in benchmark (do you know that afterburner's sensors are broken for CPU btw ?)

![Screenshot 2023-03-14 201035](https://user-images.githubusercontent.com/5920850/225112373-26b7a12f-ddca-42ac-b34b-84b750054e89.png)


![Screenshot 2023-03-14 200859](https://user-images.githubusercontent.com/5920850/225112179-007fa065-6eb9-4802-abcc-f44a495d2859.png)

**Comment by EvilKilla** [comment]
yes on 80W Total PPT you can get 40W for CPU, but could you change total ppt to 50W please

**Comment by seerge** [comment]
I think the problem is in your test ... i'm running cyberpunk 2077 with your exact limits - eco + 50w total / 35w cpu, and it works correctly from stock version of g-helper

<img width="1280" alt="Screenshot 2023-03-14 204307" src="https://user-images.githubusercontent.com/5920850/225119151-1f43edb5-4d7d-4217-a2b9-91269a79cc52.png">

<img width="1280" alt="Screenshot 2023-03-14 204245" src="https://user-images.githubusercontent.com/5920850/225119169-3a19949c-d7dd-41bf-b19d-ae8d2b16fcce.png">

**Comment by seerge** [comment]
> > (do you know that afterburner's sensors are broken for CPU btw ?)
> 
> Yes, i read the real consumption on my wattmeter there is a huge difference (total ppt 60W is 100W in real)

no, under CPU it shows TOTAL platform consumption,

**Comment by EvilKilla** [comment]
ok thats really strange now . i'll try cp2077 like you. did you make a clean windows install?

**Comment by seerge** [comment]
i think I have figured out why ungine doesn't work, problem is in windows power plans not in ghelper. It's not a game, and therefore windows by default doesn't always run it in max power mode, rather runs in what is set currently at 

<img width="580" alt="Screenshot 2023-03-14 205953" src="https://user-images.githubusercontent.com/5920850/225122609-9d6715e6-1462-46d4-a655-f9751b920616.png">

Make sure you have set Best Performance there. And it will run fine.

Also please make sure you use latest release https://github.com/seerge/g-helper/releases/tag/v0.27 (based on your screenshots you don't) 

I just got exact 35w in ungine with latest stock ghelper + your power limits + "Best Performance" in windows settings.

Armory sets it's own power plans, and in Turbo (Manual) it forces same "Best performance"

**Comment by seerge** [comment]
@EvilKilla or you can just install https://github.com/seerge/g-helper/releases/tag/v0.28 - it will set correct windows power mode with Turbo

**Comment by hkaancaliskan** [comment]
> Performance modes in app are now linked to Windows Power modes (same as it was in armory).

@seerge this means we can have separate CPU boost options for power modes, right?

**Comment by seerge** [comment]
@hkaancaliskan nope, boost is a separate thing. It's toggled for everyone (as it's stored in windows power plan) (don't mix with windows power mode ...)

**Comment by EvilKilla** [comment]
Perfect . 0.28 is the key <3
