### ISSUE TITLE
[Feature Request] 请求适配幻 X 背窗灯 / Request to adapt the ROG Z13 back window light.

### ISSUE THREAD

**Issue by d0j1a1701** [seerge/g-helper#843]
**Is your feature request related to a problem? Please describe.**

一旦 G-Helper 打开，背窗灯会熄灭，并且 G-Helper 灯光设置里无法将其打开。

> Once G-Helper is turned on, the back window light will turn off and it cannot be turned on in the G-Helper light settings.

**Describe the solution you'd like**

在灯光列表里添加一个“背窗灯”。

> Add a ”back window light“ in the light list.

**Comment by seerge** [comment]
@d0j1a1701 hello, check other open source apps like OpenRGB - are they able to control backlight of your window? If not - then it's probably no open information on how to do that, and I can't add it without physical access to device :)

**Comment by d0j1a1701** [comment]
> OpenRGB

OK, I Tried OpenRGB, It doesn't work... It even can't regnorize my keyboard :(

**Comment by seerge** [comment]
Then i can’t help :)

**Comment by rainbowflesh** [comment]
Fallback to version .96, rear light break since v0.97. I'm trying to figure out what going on, but there are 140 commits since .96 -> .97, will take some time.

**Comment by seerge** [comment]
@d0j1a1701 https://github.com/seerge/g-helper/issues/930#issuecomment-1657174968 added support here

**Comment by d0j1a1701** [comment]
> @d0j1a1701 [#930 (comment)](https://github.com/seerge/g-helper/issues/930#issuecomment-1657174968) added support here

ok it works.

Thanks!
