### ISSUE TITLE
Can windows automatically switch the power mode to be automatically set in the software

### ISSUE THREAD

**Issue by Border1101** [seerge/g-helper#849]
I followed your method and requirements to set Windows to automatically switch the power mode, but found that this does not work, the configuration will be replaced again, can you directly set the power mode corresponding to the performance mode in the software?

**Comment by seerge** [comment]
@Border1101 app would adjust power modes automatically, unless you uncheck corresponding checkbox under Extra.

Given that you have completely ignored all requested info and app logs - I'm closing this issue.

**Comment by Border1101** [comment]
他并没有自动切换，因为我在切换不同的性能模式的实话，我的电池计划并没有改变
