### ISSUE TITLE
[Feature Request] Make Silent, Balanced and Turbo modes Plugged-in togglable

### ISSUE THREAD

**Issue by gloatoriginal** [seerge/g-helper#85]
With the recent addition in release v0.28.0 it appears that the Silent, Balanced and Turbo profiles will be linked to the power efficiency set in the windows settings. Is there a possibility of having this be changed on unplugged/plugged in?
Example:
Unplugged: Silent + Eco mode
Plugged in: Balanced (or maybe Turbo) + Standard mode

**Comment by seerge** [comment]
App already remembers mode per plugged/battery. Just change it once, and will auto switch.
