### ISSUE TITLE
[Feature request] Set another color to the tray icon to indicate Turbo mode On

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#850]
Hi, would you mind to add some icon color for the Turbo mode too? Maybe, orange or red, some hue. Like green icon made for the Eco mode.
Thanks!

**Comment by seerge** [comment]
@ke1ne hello,

Currently tray icon color is used for GPU mode, green - eco, blue - standard, red - ultimate

**Comment by ke1ne** [comment]
@seerge Oops, didn't know about red Ultimate. No problem, thanks
