### ISSUE TITLE
GHelper window not popping up when external display connected 

### ISSUE THREAD

**Issue by xschwi** [seerge/g-helper#851]
**Description**
When my 2nd monitor is connected via HDMI port GHelper window is not popping up on any screen. Disconnecting screen and reconnecting fixes issue temporary. Selecting "PC screen only", opening GHelper, and changing to "extend" also will temporary fix problem. 

Starting GHelper or restarting when 2nd screen is connected makes the window not show up, but not allways.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12136453/log.txt)

**Desktop**
Fresh install of Windows 11 [22621.1992]
G14 2021 GA401QE-K2117T

**Asus software**
- Armoury crate (never installed)
- MyASUS (installed)
- Other Asus services running in background: all stopped

**Additional context**
Using GHelper for 2 months now, regular updates for every final release. I don't remember if the problem existed from the beginning, but I know it has been present for at least a month

**Comment by seerge** [comment]
@xschwi hello, i also use 2 screens, and for me it work’s absolutely fine on different devices even. It looks more like some issue with windows acting :)

What display do you have set as main?

**Comment by xschwi** [comment]
Yeah, i bet it's Windows, as always :)

My config:
Main: laptop integrated [2560x1440 / 175% scale]
Second: LG 29UM69G-B [2560x1080 / 100% scale]

**Comment by seerge** [comment]
@xschwi and if you would set big monitor as main?

**Comment by xschwi** [comment]
Still nothing. Even tested diffrent cables, diffrent scale options

**Comment by seerge** [comment]
@xschwi the only thing i can offer , is to disable g-helper window positioning next to tray (as it does now)

Does this build make a difference? If not then it's something not related to the app itself, but rather to windows as

[GHelper.zip](https://github.com/seerge/g-helper/files/12136783/GHelper.zip)

**Comment by seerge** [comment]
@xschwi did you had a chance to check the build ?

**Comment by xschwi** [comment]
@seerge I reinstalled all amd and nvidia graphics drivers, and for now its working fine

**Comment by seerge** [comment]
@xschwi oke, then probably drivers / display management was the issue :)

**Comment by heissonly** [comment]
I have also same issue. How did you solve which driver you reinstalled ?
