### ISSUE TITLE
Run on startup for ALL Users

### ISSUE THREAD

**Issue by sasaleese** [seerge/g-helper#852]
Dear seerge,

First of all thank you for this excellent piece of software 👌

I would like to suggest to add a "Run on startup (All users)" option to GHelper.

Currently if you activate the "Run on startup" option, GHelper will create a new startup task with the current user's credentials and this works only when the current user is logging in.
However if your laptop has multiple Windows user accounts (eg. you and your kids 😁) GHelper won't start up automatically under other Windows accounts.

Right now I manually create a startup task by using "BUILTIN\Users" and "Start on any user login" options in Task Scheduler which is able to autostart GHelper with all of the existing accounts.

(excuse me, the translation for operating system terms may be inaccurate due to using a localized version of Windows 11)

What do you thing?

Cordially,
Gábor

**Comment by seerge** [comment]
@sasaleese hello,

As you have explained, you can set it to run for all users by editing the task in Task Scheduler. But I think for default case scheduling app from current user is more than enough (cause opposite would immediately require admin permissions)
