### ISSUE TITLE
Incorrect key bindings on ASUS TUF series (and others maybe?)

### ISSUE THREAD

**Issue by thepriyamkalra** [seerge/g-helper#853]
**Describe the bug**
Since the M(1-4) buttons do not physically exist on the TUF series of laptops (atleast not on the TUF F15), I initially thought that these bindings would simply not do anything, but it seems remapping these buttons does in fact remap some Fn+F hotkeys.

For example:
Remapping
M1 actually remaps Fn+F2
M2 actually remaps Fn+F3
M3 actually remaps Fn+F4

and remapping M4, Fn+F4 does not do anything (maybe it does but I couldnt find any Fn+F keys to match these to)
while Fn+C works as expected.

**Clear scenario to Reproduce**
Simply use the key bindings feature on a TUF Series laptop.

**Expected behavior**
Ideally, GHelper should detect that it is running on a TUF series laptop and swap the M(1-4) keys for the corresponding Fn+F keys (and remove M4 & Fn+F4)

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12136633/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop Model: ASUS TUF F15 FX506LU

**Asus software**
- None

**Additional context**
This is a pretty minor issue, but is also easily fixable so just wanted to put this out here.
Thanks!

**Comment by seerge** [comment]
@thepriyamkalra hello, what do fn-fx row do by default? do those hotkeys work in g-helper?

**Comment by thepriyamkalra** [comment]
@seerge hi, here's the default mappings for fn+f keys
f1 - mute speakers
f2 - volume down
f3 - volume up
f4 - mute mic
f5 - toggle profile (silent/perf/turbo/custom)
f6 - turn off display
f7 - brightness down
f8 - brightness up
f9 - cast
f10 - toggle numpad (?)
f11 - sleep
f12 - flight mode

Out of these, f2 to f4 are configurable in ghelper via the M1-3 bindings (as in the op), and they work.
GHelper is able to switch profiles using f5 and also shows an icon on using f10 but I am not sure if it works.
all the others work fine but seem to be detached from ghelper.

**Comment by seerge** [comment]
@thepriyamkalra so the fix that you want - is actually changing labels from M1 .. M3 to Fn+F2 ... F4 , and removing M4 label completely?

**Comment by thepriyamkalra** [comment]
Yes, its pretty much the only solution I can think of.
I also discovered some more weird behavior --
the FN lock does work, and enables the "secondary functions" of the function keys, but some of them are just wrong,
for example --
with FN LOCK OFF; fn+f2 does "volume down", and with FN LOCK ON pressing f2 alone does "keyboard backlight down", when it should just do "volume down"

**Comment by seerge** [comment]
@thepriyamkalra check this build
[GHelper.zip](https://github.com/seerge/g-helper/files/12136844/GHelper.zip)

**Comment by thepriyamkalra** [comment]
@seerge Thanks, this seems to have fixed both of the issues I mentioned, the labels appear correctly and fn lock is also working now!
![image](https://github.com/seerge/g-helper/assets/43999863/84dfe670-bcc8-4076-b0e9-2bf16d0d1b41)

**Comment by thepriyamkalra** [comment]
There is still one issue though, when FN LOCK is on, using using the function keys alone works and invokes a secondary function like "volume down" with F2, but using Fn+F also invokes the same secondary function instead of the primary function like "rename file" for f2 or "refresh" for f5.

**Comment by seerge** [comment]
@thepriyamkalra because it's not a real fn-lock but rather software imitation (app just makes F1..F11 it's own hotkeys and runs appropriate commands), there is no way to do a reverse part.

Closing as completed.

**Comment by osamazakimohammed** [comment]
all tuf models should get this fixes , right ? , Mine is FX505GT and it still shows M1 , M2 , M3 , and i have the same issues like with fn lock on the volume buttons change keyboard backlight brightness and f10 doesn't change touchpad state

**Comment by soundwaves7** [comment]
@seerge can this fix be included for FX706HE as well?
