### ISSUE TITLE
2023 ASUS SCAR 16 Rear RGB control

### ISSUE THREAD

**Issue by mbze430** [seerge/g-helper#858]
I am not sure if this is a bug or a feature request.  But on the 2023 SCAR 16 the rear(fan exhaust) has RGB bar.  But using G-Helper the lights are completely off.  I haven't been able to find a way to turn them on via G-Helper

Just like the front RGB bar, please give the option to control the rear as the same as the rear.

**Comment by seerge** [comment]
I have same device, just go to extra and check all Lightbar checkboxes there

**Comment by mbze430** [comment]
> I have same device, just go to extra and check all Lightbar checkboxes there

Everything is checked.  Only the front one shows up.  The rear is completely dark. For good measure I uncheck all then re-check all

**Comment by seerge** [comment]
@mbze430 is Armoury Crate able to turn it ON ?

**Comment by mbze430** [comment]
> @mbze430 is Armoury Crate able to turn it ON ?

here is the funny part.  I reinstall Armoury Crate.  During the installation. the rear lightbar came back up.  Once Armoury Crate rebooted, everything is still working.  As soon as it got back into windows and loaded up Ghelper it stopped working.  Since then I stopped Ghelper from starting but it is still turned off.  I am about to remove Armoury Crate again and do another install while Ghelper is NOT being loaded.

**Comment by mbze430** [comment]
just verified.  After removal of Armoury Crate and stopping G-Helper from starting.  Reinstalling Amoury Crate it completely works.  While Armoury Crate is still installed starting G-Helper immediate turn off the rear lightbar.

**Comment by seerge** [comment]
@mbze430 that's strange, as I have G16 2023 as well, and my device simply don't have that rear light :) (therefore Armoury behaves same as G-Helper)

Without physical access to device it's quite difficult to figure out correct data that needs to be sent to keyboard to make it turn on right things.

Can you quickly check this build if it makes any difference ?

[Uploading GHelper.zip…]()

**Comment by mbze430** [comment]
Is your a G16 or a Scar 16?  I believe in the US there might not be a G16 model might be only in the EU.

Also this might be a different thing. But right now none of my macro key works anymore.  if I go back in to G-Helper the macro key works again, but it kills the rear light.

I will try the different ghelper and see.  will report back

**Comment by mbze430** [comment]
Good news and bad news.

Bad News first:  the version of ghelper you asked me to try does exactly the same.  it turns off the rear lightbar.

Good news:
it looks like my Scar 16 the logo, keyboard, front light bar, and rear light bar can be individually controlled(?).  
When I go to the Armoury Crate, there options to turn on/off each.  If I come back and manually turn off and then on again, the rear light bar comes back on and G Helper can control it.  It probably needs to find the register to control the same way for Ghelper.
<img width="540" alt="Screenshot 2023-07-23 123225" src="https://github.com/seerge/g-helper/assets/9736287/3e46a2d2-58d7-4348-9492-b8881acfb0ab">
if there is a way I can help you find that let me know

**Comment by seerge** [comment]
Can you check if this one makes a difference ? (i'm just sending ON flags to like all possible spots)
[GHelper.zip](https://github.com/seerge/g-helper/files/12139558/GHelper.zip)

**Comment by mbze430** [comment]
Yep that works.  The rear lightbar stays on.  However, the Extra Options "Lightbar" doesn't turn if off only the front.  So most likely there is a differet register to control the rear light.  Not sure if you want to pursue that.

**Comment by mbze430** [comment]
should I open a new bug report about losing macro keys even after stopping G-Helper and reinstalling Armour Crate?

**Comment by seerge** [comment]
@mbze430 now we need to figure out what flags are exactly rear lid

In this build I have linked checkboxes in LOGO column to a new "area". Can you check if they work ? (by checking / unchecking) ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/12139596/GHelper.zip)

Your macro keys don't work in Armoury cause you have stopped asus services probably via g-helper, as soon as you will start them back they will work.



[GHelper.zip](https://github.com/seerge/g-helper/files/12139589/GHelper.zip)

**Comment by mbze430** [comment]
okay so the new Ghelper now turns off the rear lightbar and the logo on the back of the screen. (if you need picture I can send as well)

**Comment by seerge** [comment]
@mbze430 oke, good. I think I will move "Rear" lightbar to "Lid" section then. Do I understand correctly that LID does nothing for you now (as you have no LID lights?)

Check this build, Rear controls now are under Lid

[GHelper.zip](https://github.com/seerge/g-helper/files/12139620/GHelper.zip)

--

And yes, I have G16 Strix with 4080 :) and it doesn't have neither glowing logo nor rear lightbar, only from and keyboard (but i don't mind)

**Comment by mbze430** [comment]
The Lid before did nothing before.  Even now it does nothing.  I think Lid/Logo should be the same?  and the Rear should now be Logo?  Let me try the new GHelper

**Comment by seerge** [comment]
@mbze430 no, Lid / Logo actually there cause they exist on some other Strix models, and those are separate sections.

For your case I will just reuse existing checkboxes :)

**Comment by mbze430** [comment]
Ohh okay.

So right now "Keyboard" = keyboard, "Logo" = lid's logo, "Lightbar" = front lightbar, and "Lid" = rear lightbar

**Comment by seerge** [comment]
Yes, if everything works ok - i'm closing this as completed and will include changes in next release :) 
Thanks for checking.

**Comment by mbze430** [comment]
awesome thank you for fixing it so quickly.
