### ISSUE TITLE
Laptop freezes when plugging and unplugging

### ISSUE THREAD

**Issue by nbeh1** [seerge/g-helper#860]
**Describe the bug**
Laptop freezes when plugging and unplugging, I can still hear sounds from Youtube though. This issue began when G-helper updated to version 0.100, I tried deleting it and went back to 0.98 and the issue is solved.

**Clear scenario to Reproduce**
1. Launch G-helper 0.100
2. Plug or unplug power cable from laptop.
3. Laptop freezes

**Expected behavior**
Changing power mode and gpu mode

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12138475/log.txt)

**Desktop (please complete the following information):**
 - OS: Window 11
 - GA503RM
 - AMD 6800hs with Nvidia 3060

**Asus software**
- Armoury crate uninstalled
- MyASUS uninstalled
- Asus services stopped

Additional Information
At first I thought it was an issue about optimized changing gpu modes or auto refresh rates when plugging and unplugging but keeping them to one settings doesn't help.

Thanks.

**Comment by seerge** [comment]
@nbeh1 hello,

The only thing that was changed in 0.100 vs 0.98 is that it would set aura color on startup / power change as well,

Can you check this build w/o aura init : 

[GHelper.zip](https://github.com/seerge/g-helper/files/12138514/GHelper.zip)

**Comment by nbeh1** [comment]
The issue was fixed with this build!

**Comment by seerge** [comment]
@nbeh1 oke! then it's strange. Can you try to change backlight mode drom dropdown? (as it does same command). Does it "freeze" your laptop in a same way ?

**Comment by nbeh1** [comment]
No, changing back light settings doesn't freeze it in any version. Here's a video of the difference between .98 and .100 when unplugging. Seems to be a graphics problem but I'm not sure. 

https://github.com/seerge/g-helper/assets/139955754/525d2fd1-e1df-4180-9a56-57fe3de61fcd

**Comment by seerge** [comment]
@nbeh1 ah, but then what you show is just an app window being slow, cause it wait's for an ECO command to finish. And that one can be slow sometimes (i guess cause bios waits for some apps to release GPU).

That didn't really change anyhow from 0.98 to 100. So it looks more like a conicidence that in testing 0.100 behaved differently from 0.98 or 0.101 :D 

Can you try this build (i have restored Keyboard Aura init commands back), but have made them a bit faster 

[GHelper.zip](https://github.com/seerge/g-helper/files/12138734/GHelper.zip)

**Comment by nbeh1** [comment]
Sorry for the misleading video, I could've kept the video running for longer but the whole laptop hangs completely and is unusable when this happens not just the app, I have to restart it using the power button.

This newest build also works fine without any issue.

**Comment by seerge** [comment]
@nbeh1 oke! Then issue was definitely not in Aura as I thought.

As for Eco switch, did that happen once? Or happened all the time?

**Comment by nbeh1** [comment]
Manual switching to eco mode is fine but hangs every time I unplug. However it also hangs if the gpu mode was already on eco when i unplug.

**Comment by seerge** [comment]
@nbeh1 but last build that I have published here doesn't, right ?

**Comment by nbeh1** [comment]
> @nbeh1 but last build that I have published here doesn't, right ?

yep

**Comment by seerge** [comment]
Oke, then closing this as completed :)

**Comment by YomamaNow** [comment]
I have the same likely every since the same version .and thru .142. I nearly fear it would make me return to the armoury bloat. it freezes constantly for me since my cord unplugs easily anyway. any fix?
