### ISSUE TITLE
App won't let external keyboard use its fn key.

### ISSUE THREAD

**Issue by ekinyuksel12** [seerge/g-helper#863]
**Describtion**
When using a external keyboard pressing the external keyboards fn key triggers the laptops fn key. For example I use a %60 keyboard when I press fn+2 it should activate F2 key but it triggers the laptops fn+F2 function which is lowering the keyboad brightness

**Clear scenario to Reproduce**
1. Connect a external keyboard
2. Hold down the external keyboards fn key and press a function key (F1-F12)
3. It should activate the laptops function

**Expected behavior**
External keyboards fn key should only affect the external keyboards functions. When I press fn+2 I expect to get F2 key instead of lowering the keyboard brightness. Also adding a option in the settings to couple and uncouple the fn keys can be good for customizability.

**Desktop:**
 - OS: Windows 11
 - Asus Rog Zephyrus G14

**Asus software**
- Armoury crate is not installed
- MyASUS is not installed
- No other Asus services are running in background

**Comment by seerge** [comment]
@ekinyuksel12 hello. 

External keyboard special keys should be handled by it's manufacturer's hardware / software :) It has nothing to do with G-Helper :)

**Comment by ekinyuksel12** [comment]
But this issue is not present when using armory create instead of g-helper

**Comment by seerge** [comment]
@ekinyuksel12 i really doubt that :)
