### ISSUE TITLE
Request to Add Different Screen Types to G-helper App

### ISSUE THREAD

**Issue by yesnt10** [seerge/g-helper#866]
I am a user and fan of the G-helper app, and I wanted to express my appreciation for the excellent work you've done so far in creating such a useful application.

I am reaching out to kindly request a new feature for the G-helper app. I also have been using the Armoury Crate application, and I find the different screen types it offers to be incredibly beneficial. These various screen types enhance the user experience and provide more customization options.

Hence, I would like to request the inclusion of similar different screen types in the G-helper app. I believe this addition would elevate the app's functionality to a whole new level and attract even more users.

I can adjust the screen mode when I press fn+v with Armoury Crate. I leave screenshots about it. Hope you got it

Thank you for considering my suggestion. I look forward to future updates and enhancements to G-helper.

![Ekran görüntüsü 2023-07-23 194726](https://github.com/seerge/g-helper/assets/114935167/b3af37bc-402f-4a6a-bd8b-3ce90b5ebd05)
![Ekran görüntüsü 2023-07-23 194729](https://github.com/seerge/g-helper/assets/114935167/fcf21d09-1b99-4ac9-900f-98f6534cfdc7)

![Ekran görüntüsü 2023-07-23 194736](https://github.com/seerge/g-helper/assets/114935167/3e3062c7-34d1-44fe-bb9c-c14ce2c293af)

**Comment by seerge** [comment]
@yesnt10 asus does that in some proprietary way, so i have no idea how that happens + this is literally a duplicate/intersection of https://github.com/seerge/g-helper/issues/520 :)

**Comment by seerge** [comment]
I'm closing this as dublicate :) if I will figure out something at least for sRGB I will update it in topic #520 :)
