### ISSUE TITLE
Rearrangement of UI for cleaner look

### ISSUE THREAD

**Issue by flankedgonerogue** [seerge/g-helper#867]
While the UI is super sleek and clean, it always annoyed me the extra settings button is under the "Laptop Keyboard" section. I propose to remove two checkboxes (Turn AniMe Matrix off on battery and Run on startup) and move the "Extra" button to the place of "Run on startup". The checks boxes can be added under the Other section in Extra settings.

![Screenshot 2023-07-24 033126](https://github.com/seerge/g-helper/assets/138696253/96834332-ce14-4bf1-a12f-801cd52a76ed)

Another thing could be that we split the extra settings as the other section has become fairly larger now. Keep the Extra button but it only contains Key Bindings and Laptop Backlight. Add a new button at the place of "Run on startup" that contains the other section and Run on startup.

**Comment by seerge** [comment]
@flankedgonerogue hello,

I was indeed planning to re-arrange main window a bit.

- But I believe "Run on startup" is too important to be removed to settings (as app intentionally don't set itself on startup automatically).
- Anime Matrix checkbox will be moved later, as I plan to add a separate screen with more "options" for matrix later, where checkbox will reside 

Check this build:
[GHelper.zip](https://github.com/seerge/g-helper/files/12145530/GHelper.zip)

**Comment by seerge** [comment]
I'm closing this as completed, and moving rest of discussion to this topic

https://github.com/seerge/g-helper/discussions/875
