### ISSUE TITLE
[Bug] Resume from lid open sleep isn't working properly

### ISSUE THREAD

**Issue by stuli1989** [seerge/g-helper#869]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**
When my Zephyrus G15 2022 goes into sleep with the lid open, resuming it from sleep by clicking the keyboard, mouse or even pressing the power button once doesn't work. I have to end up long pressing the power button to restart the laptop. And then Ghelper doesn't launch when that restart happens.

**Clear scenario to Reproduce**
1. Leave laptop on till it automatically goes to sleep
2. Try to resume by clicking keyboard, mouse or using power key

**Expected behavior**

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/12141295/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: Zephyrus G15 2022 (GA503RW)

**Asus software**

- Armoury crate - Uninstalled
- MyASUS installed
- Other Asus services running in background - None

**Comment by seerge** [comment]
@stuli1989 hello, i don’t think it’s related to app anyhow. You have Windows and it handles sleep :) 

Try to check online how to troubleshoot sleep ussues. You can start with making sure you use default “Balanced “ power plan and resetting all its settings to defaults as well :)
