### ISSUE TITLE
[Feature Request] Set Max CPU Frequency

### ISSUE THREAD

**Issue by EvilKilla** [seerge/g-helper#87]
Disabling boost is the easy way to save energy and heat yes, but on some apps/games it is a bottleneck and enabling boost is always instant 96 degrees :)

my idea is to set the maximum cpu frequency for each profile.

i'm using QuickCPU to change maximum CPU Frequency. Between 3,8 and 4,0 GHz is the sweetspot of efficency and power consumption.

**Comment by seerge** [comment]
You can always just lower CPU PPT, that should do same trick. I don't see point in turning G-Helper into a hardcore CPU tuning utility. You can use any extra tools next to if ofc :)
