### ISSUE TITLE
[FEATURE REQUEST] Add similar ability to add two different colors in Aura effects

### ISSUE THREAD

**Issue by mbze430** [seerge/g-helper#870]
Please add feature in Aura effect which allows the users to pick two different colors to fade or gradient to aura effects that is similar in Armoury Crate.

**Comment by seerge** [comment]
Hello, if you mean “Breathing” effect it already supports 2 color that can be set in the app, other effects don’t support second color.

**Comment by mbze430** [comment]
Besides breathing there are actually a few effects that allows two colors.  also the rainbow effects allows 3-4 diffrerent color bars.  I am not at my ASUS laptop right now but I will send some screenshots of the options per aura effects later tonight when I get home.

**Comment by seerge** [comment]
@mbze430 g-helper lists only modes supported by keyboard on hardware level (i.e. you set it - and it does that  by itself).

The rest you see in Armoury are software - i.e. app has to set new color few times a second, to imitate glowing / etc :) This is very resource intensive thing (and will kill whole purpose of G-Helper being **lightweight** AC alternative) :)

**Comment by incoming-th** [comment]
Hi,

Late in the party, but I believe this refer to the "Gradient" effect where we can choose 2 colors. I was also looking for that option in G-Helper but understand that's not possible or not the purpose of G-Helper.

![image](https://github.com/seerge/g-helper/assets/26375917/35455fbd-b7a4-4cc4-8b01-03c747c5c99c)

Windows 11 supports it but kind of buggy as it's sometime not applied when waking up from hibernation. G-Helper maintains the color as expected.
