### ISSUE TITLE
Custom colors cannot be saved

### ISSUE THREAD

**Issue by dyeer-Z** [seerge/g-helper#871]
**Describe the bug**
When using the Laptop Keyboard to change Color, the "Add to Custom Colors" button fails and Custom Colors cannot be saved.

**Clear scenario to Reproduce**
Click "color", click "define custom colors", change RGB, and finally click "add to custom colors".

**Expected behavior**
Custom colors can be saved.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12142932/log.txt)
In the last part of log.txt.

**Desktop:**
 - OS: Windows 11 Pro
 - Laptop model: G14 2023

**Asus software**
All ASUS services were shut down or deleted, MyASUS was removed, Armory crates were removed.

**Comment by seerge** [comment]
@dyeer-Z hello, it indeed doesn't save that :) but it saves custom color itself in the app and aura.

Saving those colors would require quite a few changes in the app, and i don't think it's worth an effort honestly, as this is not a photoshop :)

So it's out of scope / not needed imho.

**Comment by dyeer-Z** [comment]
> 你好，它确实没有保存那个:)但它将自定义颜色本身保存在应用程序和光环中。 你好，它确实没有保存：）但它在应用程序和光环中保存了自定义颜色本身。
> 
> 保存这些颜色需要在应用程序中进行很多更改，老实说，我认为不值得付出努力，因为这不是 photoshop :)保存这些颜色需要在应用程序中进行相当多的更改，老实说，我认为不值得努力，因为这不是Photoshop：）
> 
> 所以它超出了范围/不需要恕我直言。所以它超出了范围/不需要恕我直言。

Thank you very much for your contribution to the majority of ROG users and your attention to the issue. Indeed, the most important function of changing the keyboard color has been implemented, and the additional functions are irrelevant. I wish you a happy day.
