### ISSUE TITLE
Fn+() commands on the NumPad along with the  Fn+C command do not work on ASUS TUF Gaming A15 FA507RM.

### ISSUE THREAD

**Issue by DarkEdgeXD** [seerge/g-helper#873]
Fn+() commands on the NumPad along with the  Fn+C command do not work on ASUS TUF Gaming A15 FA507RM.

Going to extra settings and manually triggering function lock does work however the Fn+C shortcut does not toggle this. Also all Fn+() shortcuts on the NumPad do not work unless ASUS optimisation service is enabled.

 - OS: Windows 11
 - ASUS TUF Gaming A15 FA507RM

All ASUS Software disabled except ASUS Hotplug controller

[log.txt](https://github.com/seerge/g-helper/files/12145204/log.txt)

**Comment by seerge** [comment]
@DarkEdgeXD hello, do you mean delete and calculator buttons ? If so - it's not possible to do. Cause w/o FN key those keys just produce regular numbers or enter keys (that are no different from numbers / enter on main keyboard). 

And if app will intercept them - you won't be able to press enter at all.

**Comment by DarkEdgeXD** [comment]
Yes, thank you. The Fn+C toggle too however doesn't seem to work.

**Comment by seerge** [comment]
@DarkEdgeXD i think TUF models simply don't have FN+C combination (i.e. it doesn't emit any command) so app doesn't catch it.

**Comment by DarkEdgeXD** [comment]
Gotcha, Thank a lot! :)
