### ISSUE TITLE
[Feature Request] Allow up to 4 profiles for custom preset configurations

### ISSUE THREAD

**Issue by mbze430** [seerge/g-helper#880]
Please consider having a multiple user configurable profile setup.

Example.  Profile 1)  Eco mode, with 60hz and no lights
Profile 2) Balanced mode, with 240hz but no multizone and with Static lighting

This way a user can click on or macro key a profile # and switch to their most use condition.  Instead of having to reconfigure

**Comment by seerge** [comment]
@mbze430 you mix apples and oranges. Eco is GPU mode, Balanced is performance mode.

And disabling / enabling GPU (i.e. setting ECO) is quite invasive operation, so it won't be linked to performance modes anyhow.

If you just want to have 2 modes on battery / plugged - this is already done in the app, just set GPU to Optimized, and performance mode is remembered per battery / plugged case as well.
