### ISSUE TITLE
[Feature Request] Increase CPU Voltage 

### ISSUE THREAD

**Issue by blackfiz** [seerge/g-helper#884]
Hello, I love your work. Already using from 0.045 version and loving it!  

I have ASUS TUF A15 (FX506IU, Ryzen 7 4800h, GTX 1660ti) 2020 and for this post, I have a specific feature request that might some people need it. 
Is it possible to have a feature like adding increments to increase CPU voltage with a .001 value per step? 
As some people might have BSOD / Black Screen / Freezing issues (like me) while enabling TurboBoost (might motherboard / cpu problem, but trying to solve it like CPU Desktop does) at random times.
It would be great if this feature request can be applied. 

Thank you. 

Regards, 

Blackfiz

**Comment by seerge** [comment]
@blackfiz asus don't provide you with any endpoints that would allow to do that :) Are you able to increase voltage with UXTU or Ryzenadj ?

**Comment by blackfiz** [comment]
@seerge for the UXTU or ryzenadj, there is no option to increase the CPU voltage :(

**Comment by seerge** [comment]
@blackfiz then I'm afraid there is nothing can be done for you here :) Mb try to use curve optimizer in Uxtu (that is used for undervolting) and do opposite - increase value there instead of decreasing?

As for running processes to prevent from idle, this is something that you can run by yourself i guess :))

**Comment by blackfiz** [comment]
The curve optimizer in UXTU seems not working for my case. 

After researching and troubleshooting over 9 months, I have found the solution regarding random black screens and freeze issues. It's not the CPU problem, but the Nvidia Optimus is the problem in my case.
Using the [TrayPwrD3 from Jobeid ](https://github.com/jobeid/TrayPwrD3), the job is to make both GPUs stay in an idle state (preventing standby mode).
For the random BSOD as per my first post, seems the laptop has a conflict with the Realtek driver and AMD Audio CoProessor. 

Does it possible for G-helper to add a single feature for making both iGPU and dGPU run on idle mode? (it will cost the power consumption also).
