### ISSUE TITLE
[Feature/Bug?] Fn + numpad enter on Tuf devices for calculator

### ISSUE THREAD

**Issue by ronell1292k** [seerge/g-helper#885]
By default on Tuf devices or devies with a numpad, Fn + numpad enter maps to a shortcut for quick access to the calculator (I'm guessing calc.exe?). Would like the same to be implemented here if possible. Also as my device does not have the M1-M4 keys, would like a kb shortcut to quickly launch g-helper without using a mouse. Thanks!

Desktop: Windows 11
Model: Tuf A15 2020 (FA506IH)
Spec: R5 4600H + 1650
Asus sw: N/A

**Comment by ronell1292k** [comment]
Hi, the log outputs the following: 
25-07-23 21:00:12: WMI event 181

**Comment by seerge** [comment]
@ronell1292k 

Can you check this build, it should show a FN-NmEnter binding for you under extra for that hotkey

[GHelper.zip](https://github.com/seerge/g-helper/files/12163290/GHelper.zip)

**Comment by ronell1292k** [comment]
1. Got it, but could launching the calculator be the default behaviour for  FN+NmEnter as it is that way in AC? 
2. I didn't see this, my bad. That is exactly what I was looking for, thanks once again.

**Comment by seerge** [comment]
@ronell1292k I have re-used missing M4 binding for your FN+NmEnter (cause it's quite exotic case), so default action is g-helper there :) but it's fully adjustable.

I will include this addition in next release. Closing as completed.

**Comment by soundwaves7** [comment]
@seerge  Please add FX706HE as well it Has the same keyboard layout

**Comment by seerge** [comment]
@soundwaves7 do i understand that you don't have any M-keys as well ?

Check this build : 
[GHelper.zip](https://github.com/seerge/g-helper/files/12226778/GHelper.zip)

**Comment by soundwaves7** [comment]
> @soundwaves7 do i understand that you don't have any M-keys as well ?
> 
> Check this build : [GHelper.zip](https://github.com/seerge/g-helper/files/12226778/GHelper.zip)

Nope none
