### ISSUE TITLE
Attempted to divide by zero when battery is not present

### ISSUE THREAD

**Issue by PGyorgy** [seerge/g-helper#890]
**Describe the bug**

Unhandled error message: Attempted to divide by zero.
It pops up after i start program.
!!!! I dont have a battery installed on my machine !!!!!!

************** Exception Text **************
System.DivideByZeroException: Attempted to divide by zero.
   at System.Decimal.DecCalc.VarDecDiv(DecCalc& d1, DecCalc& d2)
   at System.Decimal.op_Division(Decimal d1, Decimal d2)
   at HardwareControl.GetBatteryHealth() in C:\Users\Serge\g-helper\app\HardwareControl.cs:line 167
   at HardwareControl.RefreshBatteryHealth() in C:\Users\Serge\g-helper\app\HardwareControl.cs:line 150
   at GHelper.SettingsForm.ShowBatteryWear() in C:\Users\Serge\g-helper\app\Settings.cs:line 210
   at GHelper.SettingsForm.PanelBattery_MouseEnter(Object sender, EventArgs e) in C:\Users\Serge\g-helper\app\Settings.cs:line 195
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Clear scenario to Reproduce**

I start the program. Wait a few sec.
Error message shows up ONLY ONCE after I click Continue on error message.

**Expected behavior**

No exception

**App Logs**

2023. 07. 25. 20:12:25: ------------
2023. 07. 25. 20:12:25: App launched: ROG Zephyrus G14 GA401IU_GA401IU :0.100.0.0hu-HU
2023. 07. 25. 20:12:25: NVIDIA GeForce GTX 1660 Ti with Max-Q Design
2023. 07. 25. 20:12:26: CPU: 3 - AMD Ryzen 9 4900HS with Radeon Graphics          - AMD64 Family 23 Model 96 Stepping 1
2023. 07. 25. 20:12:26: AutoSetting for Online
2023. 07. 25. 20:12:26: Optimization service is running
2023. 07. 25. 20:12:26: Mode = 2 : OK
2023. 07. 25. 20:12:26: Eco flag : -65536
2023. 07. 25. 20:12:26: Mux flag : -65536
2023. 07. 25. 20:12:26: LG ULTRAWIDE:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY12
2023. 07. 25. 20:12:26: LG ULTRAWIDE:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY13
2023. 07. 25. 20:12:26: USB-KB 0x1866:5D-BD-01-FF-1E-0F
2023. 07. 25. 20:12:26: USB-KB 64|32HID-kompatibilis, gyártó által definiált eszköz\\?\hid#vid_0b05&pid_1866&mi_02&col03#8&3397f86&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-00-FF-FF-FF-F5-00-00-FF-FF-FF-00-00-00-00
2023. 07. 25. 20:12:26: Found external screen: LG ULTRAWIDE:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL
2023. 07. 25. 20:12:26: Changed Lid Action to 0
2023. 07. 25. 20:12:26: Engaging Clamshell Mode
2023. 07. 25. 20:12:26: Monitor Power On
2023. 07. 25. 20:12:26: Auto:5D-BA-C5-C4-01
2023. 07. 25. 20:12:40: Latest version 0.100.0.0

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Win 11
 - Laptop model: GA401IU

**Asus software**
- Armoury crate (or it's services installed): YES
- MyASUS installed : NO
- Other Asus services running in background: NO

**Additional context**

**Comment by seerge** [comment]
@PGyorgy I have to admin your case is very specific :)

But this build should fix it (not the absence of a battery tho)
[GHelper.zip](https://github.com/seerge/g-helper/files/12164342/GHelper.zip)

**Comment by PGyorgy** [comment]
Thanks for the fast response.

**Comment by PGyorgy** [comment]
My case: Battery charger IC died On MB and got replaced. But my battery is not charging any more and if its plugged in to the MB then it reports 0% battery. That makes the BIOS to maximize the CPU to 200 Mhz, so windows loads in about 5 min or so... If i unplug the battery, i can use my laptop as a desktop machine (from wall plug ofc), which is fine for me right now. Dont want to change the MB.
