### ISSUE TITLE
gpu temp limits changes automatically according to the fan rpm

### ISSUE THREAD

**Issue by Kojunwon** [seerge/g-helper#891]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**

-gpu temp limits changes automatically according to the fan rpm.
ex) when the fan rpm is 5200~5800(not precise), gpu temp limit goes to 83'C if this(83'C) temperature is lower than the temp limit i set.

**Clear scenario to Reproduce**
1. Go to 'fan curve'
2. Adjust the fan speed to be consistent and be fast.
3. Put a high load on the gpu for a long time and check the temp limit using MSI afterburner.
4. Explanation of an error or a bug
-gpu temperature doesn't go up to the temperature limit i set.

**Expected behavior**
-The temperature rises up to the temp limit i set, regardless of the current fan rpm.

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``
[log2.txt](https://github.com/seerge/g-helper/files/12164650/log2.txt)

**Screenshots or screencasts**
![스크린샷 2023-07-26 021448](https://github.com/seerge/g-helper/assets/58517337/b085b659-beb4-470d-8ea3-35aea6692799)
![스크린샷 2023-07-25 200657](https://github.com/seerge/g-helper/assets/58517337/8ec08535-67ef-4345-b538-17c4d10d9e9f)
![스크린샷 2023-07-25 203301](https://github.com/seerge/g-helper/assets/58517337/44001dd2-c93d-4eef-99c3-f4d7cddc4cea)
![스크린샷 2023-07-25 205645](https://github.com/seerge/g-helper/assets/58517337/84fa3126-2747-4d15-aa8c-4ad834d965df)
![스크린샷 2023-07-25 212334](https://github.com/seerge/g-helper/assets/58517337/e3e7d68f-1c3a-498a-92e7-cd874b98938d)
![스크린샷 2023-07-25 214642](https://github.com/seerge/g-helper/assets/58517337/4b9d7550-90b9-4870-8924-96b3359b0685)
![스크린샷 2023-07-25 221053](https://github.com/seerge/g-helper/assets/58517337/1de9b9e1-8891-41aa-8427-90167e819980)
![스크린샷 2023-07-25 223218](https://github.com/seerge/g-helper/assets/58517337/0b7009e2-732b-4ded-b56d-fdb20f7200b2)
![스크린샷 2023-07-25 225612](https://github.com/seerge/g-helper/assets/58517337/cb1910bc-da45-46be-8406-6b63afbddd81)
![스크린샷 2023-07-25 232030](https://github.com/seerge/g-helper/assets/58517337/804ffc41-bbea-4c9b-904c-e15946d89e70)
![스크린샷 2023-07-25 234957](https://github.com/seerge/g-helper/assets/58517337/25e96467-e117-4940-895d-3550d9e6f223)
![스크린샷 2023-07-26 004502](https://github.com/seerge/g-helper/assets/58517337/d6bc12ac-8c26-4f04-a70b-7b2c988812e0)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11] - Windows 11 pro
 - Laptop model - GA402XZ (G14 2023, rtx 4080, none - anime matrix)

**Asus software**
- Armoury crate (or it's services installed) - N
- MyASUS installed - N
- Other Asus services running in background - N

**Additional context**
 - I wonder if this issue only happens to me or not...

**Comment by seerge** [comment]
@Kojunwon hello, it's not g-helper limiting that :)

It set's default 87 only once, when mode is changed, and after that g-helper does literally nothing to your system.
```
PowerLimit C2 = 87 : OK
```

It looks like some issue with Nvidia driver by some reason limiting temp time to time or may be even asus bios is acting ? Did you try to do a fresh install of nvidia drivers (mb after cleanup with DDU even) ? Do you have latest BIOS version ?

**Comment by Kojunwon** [comment]
i reinstalled nvidia driver, nothing changed... i think it seems to be a bios level setting,,, can your g14 load up to the temp limit you set even at high rpm? (22 ver and 23 ver have similar cooling hardware so there is a possibility that your laptop works similar as mine)

**Comment by seerge** [comment]
@Kojunwon i have G14 2022 with AMD GPU, so it might work differently. Mine easily goes up to 90C (and then starts throttling), this is independently of fan settings (see screens)

Check Nividia Temp limit in HWinfo btw (it literally shows that as a metric) ...

![Screenshot 2023-07-25 235042](https://github.com/seerge/g-helper/assets/5920850/377139c9-1fbe-46ca-8771-28573921388e)
![Screenshot 2023-07-25 235023](https://github.com/seerge/g-helper/assets/5920850/25555121-ec00-4ef6-babe-6a9080df78df)

**Comment by Kojunwon** [comment]
thank you! i appreciate your effort.

**Comment by Kojunwon** [comment]
yeah i checked temp limit
![스크린샷 2023-07-26 085521](https://github.com/seerge/g-helper/assets/58517337/b2efeae1-2274-4127-b46c-ec6e81dcec48)
3rd graph is the temp limit, you can see the limit value that is changed from 87 to 83 lol...

**Comment by seerge** [comment]
@Kojunwon i see, then it looks like it's indeed some "hidden" feature in BIOS that prevents GPU from overheating based on active fan curve :)) Cool that you have spotted it, but I can't really "fix" that tho (as it's not g-helper doing that in a first place) . 

G-helper already sets limits 1 second AFTER setting fan curves. 

I'm closing this issue as there is nothing app can do here :)
