### ISSUE TITLE
F6 (screenshot button on M16 2022) doesn't do the action like any other Fn key with lock-on

### ISSUE THREAD

**Issue by ggjiza** [seerge/g-helper#893]
**Describe the bug**
F6 doesn't do the action like any other Fn key with lock-on, it does acts normal as it works while holding Fn

**Clear scenario to Reproduce**
1. enable Fn-lock
2. f6 doesn't launch the snipping tool
3. all other buttons do their functions without holding fn except F6

**Expected behavior**
launch snipping tool

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ASUS ROG Zephyrus M16 GU603ZW (2022) 

**Asus software**
- Armoury crate (or it's services installed): deleted 
- MyASUS installed: yes
- Other Asus services running in background: no services running.

**Comment by seerge** [comment]
@ggjiza it emits PrintScreen action. 
You can adjust what print screen does in windows settings as explained in https://github.com/seerge/g-helper/issues/723
