### ISSUE TITLE
Incorrect key bindings on Zephyrus Duo 16 (2023)

### ISSUE THREAD

**Issue by moldimolt** [seerge/g-helper#906]
Hello. I believe this is the same bug as #853, and since you mentioned the need to make configs for individual models I wanted to provide the relevant info for my device. The behavior for the Zephyrus Duo 16 (2023) is as follows:

* F1: Toggle mute, already works in G-Helper
* F2: Volume Down, currently mapped to Keyboard Backlight Down in G-Helper
* F3: Volume Up, currently mapped to Keyboard Backlight Up in G-Helper
* F4: Toggle microphone, currently non-functional
* F5: Toggle fan (power?) modes, currently non-functional
* F6:  Print Screen, already works/follows Windows' settings
* F7: Brightness Down, already works in G-Helper
* F8: Brightness Up, already works in G-Helper
* F9: Display Casting, already works/follows Windows' settings
* F10: Disable Tochpad, currently non-functional
* F11: Keyboard Backlight Toggle/Modes, currently non-functional.
* F12: Airplane Mode, already works/follows Windows' settings
* ROG: Summons G-Helper, already works although sometimes G-Helper opens in the background instead of the foreground 
* Secondary Display Toggle ("usagepage code 0x6a"): Disables/enables the bottom display, currently non-functional
* [A]/PgUp ("usagepage code 0x4b"): "Toggles between PgUp/PgDn or Arrows Keys mode", currently non-functional (seems to effectively be an Fn Lock key for the arrow keys only, but a general Fn Lock key would be more useful in my opinion and probably easier to implement) 

Keyboard reference: https://i.imgur.com/psmtr6c.jpg

Thank you.

**Comment by seerge** [comment]
@moldimolt hello, are keys not working only in FN-Lock case or also when you hold FN key ?

**Comment by seerge** [comment]
In this build with FN-Lock ON (ii.e. when you just press F-key)

F2-F4 and F11 should work correctly 
I'm not sure about F5 as it's same for all models (it's cycles through modes). And I attribute to your testing error.

[GHelper.zip](https://github.com/seerge/g-helper/files/12178114/GHelper.zip)

**Comment by moldimolt** [comment]
Hello, 

In the provided build, everything now works. Only "companion display on/off" and [A]/PgUp do not work, regardless of Fn Lock mode.

Thank you,

**Comment by seerge** [comment]
@moldimolt unfortunately i don’t know how to implement those side buttons (it was already raised by other user with duo)

Closing as completed then
