### ISSUE TITLE
Optimized mode should turn on the gpu when an external monitor is connected.

### ISSUE THREAD

**Issue by MG-LSJ** [seerge/g-helper#909]
The HDMI port on my laptop is routed through the dGPU.  If want to use an external monitor I have to manually switch to standard mode.

Can a feature be added to autodetect when a monitor is connected and turn on the dGPU.

**Comment by IceStormNG** [comment]
Afaik, this does not work. When the GPU is disabled, the port is, too. So the App cannot know that something got connected there.
Do you get a notification or some info that the monitor is connected but cannot be used? If not, then there is likely no way for GHelper to tell that a monitor is connected when the GPU is disabled.

**Comment by seerge** [comment]
@MG-LSJ hello, can you check ``%appdata%/ghelper`` log for any event IDs being recorded there if you connect external display? To my knowledge there is no way to detect that when dGPU is off as @IceStormNG said :)

**Comment by MG-LSJ** [comment]
> @MG-LSJ hello, can you check `%appdata%/ghelper` log for any event IDs being recorded there if you connect external display? To my knowledge there is no way to detect that when dGPU is off as @IceStormNG said :)

I set my laptop to gpu eco, cleared the logs. Connected the HDMI cable and this was logged:

`28-07-2023 09:51:35: WMI event 192`

**Comment by IceStormNG** [comment]
I remember that the ASUS WMI sends an Event when a display gets connected or disconnected.
Can you please also try to connect the screen to the Intel iGPU while in eco mode and see whether it also logs the same WMI event number? Maybe we can do something with that.

**Comment by MG-LSJ** [comment]
> I remember that the ASUS WMI sends an Event when a display gets connected or disconnected. Can you please also try to connect the screen to the Intel iGPU while in eco mode and see whether it also logs the same WMI event number? Maybe we can do something with that.

I have a Zephyrus g15 (2022) and the HDMI port (and all usb c) are directly connected to the Nvidia dGPU.

This event ID was logged when I connected the monitor, in on eco mode with Radeon iGPU. (No display to the monitor)

**Comment by IceStormNG** [comment]
Just checked. Mine also sends 192 with or without an active GPU on that port.
Not sure whether we auto enable the GPU, but we could at least show a warning notification to tell the user that the GPU is disabled.
WMI 192 will occur every time a display is connected or disconnected.

**Comment by seerge** [comment]
@MG-LSJ @IceStormNG my G14 emits 192 even when I just plug in USB-C charger (that doesn't have any dispays).

Imho it's too specific and too complicated to do. Changing GPU modes in app is already extremely easily, and is literally 1 click. 

I don't want to overload UX with extra popup warnings about connected displays (even if it's possible to detect properly at all). It would be still 1 click to change GPU mode from popup or same 1 click to do that in main app window :)

Closing as not planned for now, sorry :)

**Comment by MG-LSJ** [comment]
> @MG-LSJ @IceStormNG my G14 emits 192 even when I just plug in USB-C charger (that doesn't have any dispays).
> 
> Imho it's too specific and too complicated to do. Changing GPU modes in app is already extremely easily, and is literally 1 click.
> 
> I don't want to overload UX with extra popup warnings about connected displays (even if it's possible to detect properly at all). It would be still 1 click to change GPU mode from popup or same 1 click to do that in main app window :)
> 
> Closing as not planned for now, sorry :)

The problem I initially faced was that I couldn't identify why I wasn't getting a signal from the HDMI port. It took me some research to find out that all outputs gets disabled and can't be routed through the iGPU.

**Comment by MG-LSJ** [comment]
> @MG-LSJ one of 2 usb-C ports on your device should be still iGPU btw (at least this is the case for G14 / G16)

Tested and it works, thanks.

**Comment by seerge** [comment]
@MG-LSJ great, that's how I use my laptop mostly when don't play games :)

Same usb-C port is also charting btw, and it's enough to power it for basic activity.

**Comment by MG-LSJ** [comment]
> @MG-LSJ great, that's how I use my laptop mostly when don't play games :)
> 
> 
> 
> Same usb-C port is also charting btw, and it's enough to power it for basic activity.

Well mine do 100w charging on both ports.

**Comment by MG-LSJ** [comment]
> 
Did some testing, and I only got `WMI event 123` when connecting a usb C charger. (tested with two different model chargers and cables)
