### ISSUE TITLE
Fn Lock Bugs: F Keys Not Usable and External Keyboard Fn Overwritten

### ISSUE THREAD

**Issue by danploeger** [seerge/g-helper#918]
**Describe the bug**
My Setup: GA402RK + external keyboard Logi MX Keys Mini (Bluetooth connected). 

#### Fn lock active in G-Helper (`28.07.2023 12:28:04: FnLock = 0 : 0`). 
Behavior:

1. Hotkeys work fine on G14 keyboard, e.g. `F1=mute`.
2. F keys do not work, when pressing `FN+F1-12`. Expected: `F1=help page`, actual behavior: `F1=still mute`.
3. Hotkeys keys on Logi MX Keys are overwritten. Expected: `F1=connect to device 1`, actual behavior: `F1=mute`.

- In all three cases, the `log.txt` output is `28.07.2023 12:30:52: F1`.
 
#### *No* Fn lock active in G-Helper ( `28.07.2023 12:31:42: FnLock = 1 : 0`)
Behavior:

1. Hotkeys work fine on G14 keyboard, e.g. `FN+F1=mute`.
2. F keys work fine, e.g. `F1=help page`.
3. Hotkeys on Logi MX Keys work fine, e.g. `F1=connect to device 1`.

- In all three cases, no output is written into `log.txt`.

**Desktop (please complete the following information):**
 - OS: Windows 11, Build 22621
 - Laptop model: GA402RK 

**Asus software**
- Armoury crate (or it's services installed): no
- MyASUS installed: yes, but not in active use.
- Other Asus services running in background: G-Helper says that 1 Service is still running. Does not stop it automatically. In the task manager, the following services associated with ASUS are running:
![image](https://github.com/seerge/g-helper/assets/1726660/167c534f-762f-431a-98d4-bf712ec5c5df)

**Comment by seerge** [comment]
@danploeger hello,

This is how the things are. It's not a real hardware FN-Lock, app just creates hotkey bindings for F1-F11 keys in windows. And processes them manually. 

- There is no way to turn things around, and emit F1 when you press FN+F1
- Your external keyboard's F-keys are same as F-keys on internal.

**Comment by toulzx** [comment]
I have the same problem on my G14 2023. 
Unfortunately `Fn+Esc` doesn't work, `MyAsus` doesn't contain the features mentioned [in this tutorial](https://www.asus.com/support/FAQ/1038312/), and the `BIOS Advance Setting` doesn't have the relevant settings either. 
It's really annoying.

**Comment by seerge** [comment]
@toulzx you can disable/enable fn-lock using fn+c on laptop keyboard or under Extra

**Comment by toulzx** [comment]
> @toulzx you can disable/enable fn-lock using fn+c on laptop keyboard or under Extra

@seerge Thanks for the tip!
That's actually what I did :-) It's just that I was aiming for the same thing as him and wanted to use F1-F12 while turning on Fn-Lock  (a real hardware FN-Lock).
