### ISSUE TITLE
Saving the selected modes after reboot

### ISSUE THREAD

**Issue by alteregokmv** [seerge/g-helper#92]
Saving the selected modes after reboot.
Why does the program switch the GPU mode after a reboot to the standard one, is it possible to make the program save the last selected one?

The new UI is just amazing.

Ready to test Asus TUF A15 2021 FA506IC

**Comment by seerge** [comment]
Program saves modes from version 0.1. Unless you set "Optimized", then by definition it will  change based on batter/power status.
