### ISSUE TITLE
'close the lid' setting

### ISSUE THREAD

**Issue by DedSecer** [seerge/g-helper#922]
**Describe the bug**
I want my laptop do nothing when I close the lid.
![图片](https://github.com/seerge/g-helper/assets/52042233/621ff810-6bef-48e6-8a4b-b687c4ed45a8)
But each time I start g-helper, it will reset my `when I close the lid(plugged in)` to sleep.
![图片](https://github.com/seerge/g-helper/assets/52042233/fd3cc322-e0e2-4776-ad37-2b3c5f5c824e)

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12205369/log.txt)

**Screenshots or screencasts**
My g-helper setting:
![setting](https://github.com/seerge/g-helper/assets/52042233/c88fb87c-6064-43b3-8dca-eeeb9796b530)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Laptop model: rog flow x13 2022

**Asus software**
- Armoury crate (or it's services installed): I have uninstalled Armoury crate using uninstall tool.
- MyASUS installed: I have uninstalled MyASUS.
- Other Asus services running in background: g-helper show that 0 Ausu services running.

**Comment by seerge** [comment]
@DedSecer hello, it's a side-effect of turned off clamshell mode.

Just update to 0.102 - it's fixed there, and won't touch your power plan when clamshell is not checked at all

**Comment by DedSecer** [comment]
@seerge I updated to 0.102 just now, but it still change my 'close the lid' setting.

**Comment by seerge** [comment]
@DedSecer do you have auto clamshell mode unchecked? right ?

If so can you post a log from 102 ?

**Comment by DedSecer** [comment]
Sorry, what is ' auto clamshell mode unchecked'?

**Comment by DedSecer** [comment]
my log from 102:
[log.txt](https://github.com/seerge/g-helper/files/12205459/log.txt)

**Comment by seerge** [comment]
@DedSecer it looks like "Auto toggle Clamshell mode" is checked under Extra. Can you uncheck it? (and then set your settings for lid) ? :)

**Comment by DedSecer** [comment]
Thanks,I havs unchecked it:
![图片](https://github.com/seerge/g-helper/assets/52042233/275e03d3-1962-4b6e-bb60-a0b08b6b0264)
but it still change my 'close the lid' setting.

**Comment by seerge** [comment]
@DedSecer can you check this build ?

[GHelper.zip](https://github.com/seerge/g-helper/files/12206798/GHelper.zip)

**Comment by DedSecer** [comment]
Yes! this build won't change the setting!

**Comment by seerge** [comment]
@DedSecer great:) closing as completed then (and will include changes in a next release)
