### ISSUE TITLE
[Quesion] No GPU Modes for GA401IU-HA247TS ? 

### ISSUE THREAD

**Issue by ameyagokhale** [seerge/g-helper#923]
First of all, thanks for creating such an amazing tool for Asus Laptops ! I was using G14Control since long and shifted to GHelper as soon as I got to know about it and saw it's potential and active development.

I just wanted to ask the possibility of having `GPU Modes` for Asus Zephyrus G14 2021, Model: `GA401IU-HA247TS`

As of now (with v0.100.0.0), I can only see `Stop GPU Application` under GPU Mode: `iGPU + dGPU`

Some logs from GHelper related to my device:
```
App launched: ROG Zephyrus G14 GA401IU_GA401IU :0.100.0.0en-GB.
NVIDIA GeForce GTX 1660 Ti with Max-Q Design
CPU: 3 - AMD Ryzen 7 4800HS with Radeon Graphics          - AMD64 Family 23 Model 96 Stepping 1
AutoSetting for Online
Input: \\?\hid#vid_0b05&pid_1866&mi_02&col0x#x&xxxxxxxx&x&xxxx#{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}
Mode = 0 : OK
Eco flag : -65536
Mux flag : -65536
:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
BatteryLimit = 80 : OK
USB-KB 0xXXXX:XX-XX-XX-XX-XX-XX
USB-KB 64|32HID-compliant vendor-defined device\\?\hid#vid_0b05&pid_1866&mi_02&col0x#x&xxxxxxxx&x&xxxx#{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}:XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX
Matrix Off
Auto:XX-XX-XX-XX-XX
Changed Lid Action to 1
Disengaging Clamshell Mode
Monitor Power On
Latest version 0.100.0.0
Design Capacity: 75998mWh, Full Charge Capacity: 71834mWh, Health: 0.9452090844495907787047027553%
Varibright: 1,2
```

GHelper UI:
<img src="https://github.com/seerge/g-helper/assets/25152074/d67805a3-ed4d-4273-85d4-bf1c96d92ff3" width="250"/>

I really liked the `Optimized` GPU Mode. I have been using it on TUF F15 and it works like a charm and so, was trying to know about the possibility of having the same for above mentioned Zephyrus model.

Thanks again!

**Comment by seerge** [comment]
@ameyagokhale hello,

Your device simply don’t support disabling GPU :)

**Comment by ameyagokhale** [comment]
@seerge ohh, that's bad, I thought all devices support that :(

Just wanted to understand how enabling/disabling is taken care by GHelper. Does it use MUX Switch ?

Before Asus (when I had Dell), I used to follow this: https://dev.to/muhammedziyad/automatically-disable-and-enable-your-gpu-or-any-other-device-when-your-laptop-power-state-changes-hf5

This used to attach a task (enable/disable GPU script) to connect/disconnect event of adapter which used to help a bit in battery mode (I also had added a scheduler on boot with delay of 15 seconds to check AC Status and run disable gpu script if state was not charging)

Maybe something on the similar lines could be added in future to support (kindof) `Optimised` GPU Mode on un-supported models too ?

Thanks anyways for the help and support!

**Comment by seerge** [comment]
@ameyagokhale disabling GPU in device manager won't stop it from using power (on contrary it will only become uncontrolled and drain as much as it can take)

Your device is literally mentioned in FAQ https://github.com/seerge/g-helper#i-dont-see-gpu-modes-section

It doesn't support powering off dGPU as new models do. This has absolutely nothing to do with MUX switch (that you device doesn't have neither)

**Comment by ameyagokhale** [comment]
> (on contrary it will only become uncontrolled and drain as much as it can take)

Understood, so I should not be doing that either.

Was thinking of saving the battery somehow. Thanks again for all the information
