### ISSUE TITLE
Breathe backlight bug

### ISSUE THREAD

**Issue by MAdimy** [seerge/g-helper#925]
From previous versions I found that the breathe backlight mode for the keyboard has an issue as it shows only one color while the other is not working

it is not that big problem but I do find it nice to use it

**Comment by seerge** [comment]
Some devices have breathing only with 1 color. Given that you have provided 0 information about your case and no logs I'm closing this issue.

**Comment by MAdimy** [comment]
I am using Zephyrus G15 2022
the breathe mode was working in the Armoury crate app with no problems

regarding log txt I don't know where to check them sorry

**Comment by seerge** [comment]
Instructions was inside bug-report template that you have erased https://github.com/seerge/g-helper/issues/new?assignees=&labels=&projects=&template=bug_report.md :)

Did you select 2 colors for breathe ?

**Comment by MAdimy** [comment]
Yes I chose two colors
but the keyboard only shows the second color, so it does act like strobe mode but with slow transition
[log.txt](https://github.com/seerge/g-helper/files/12207584/log.txt)
<img width="1280" alt="image" src="https://github.com/seerge/g-helper/assets/140903764/f5566644-0e25-4f5c-86ea-dd0c84b119f5">

**Comment by seerge** [comment]
@MAdimy in a log i see that app sends settings with 2 colors

FF-EB-00
and 
FF-80-C0

```
USB-KB 63|33HID-compliant vendor-defined device\\?\hid#vid_0b05&pid_19b6&col06#7&2635b6bc&0&0005#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-01-00-80-FF-EB-00-00-FF-80-C0-00-00-00-00
```

It could be that on G15 breathing mode doesn't support 2 colors on hardware level (for example on my G16 Strix it's also only 1 color)

I assume in Armoury you had Aura Sync enabled, then it will imitate all this animations on "software" level (i.e. set keyboard colors like 10 times each second). This is something i don't want to do in  G-Helper as this is a resource heavy operation and will kill battery fast.

G-Helper can only set modes that keyboard supports on hardware level.

**Comment by MAdimy** [comment]
ok great thanks for the info
one side question please am trying to test the fans after some updates and i sat them to reach 100% however am observing that they reach a max of 86% in the app is that an issue with new the update?

<img width="858" alt="image" src="https://github.com/seerge/g-helper/assets/140903764/24a02f78-82dc-4957-8e8f-ba11d543966d">

[log.txt](https://github.com/seerge/g-helper/files/12207606/log.txt)

I have send you the new log txt

**Comment by seerge** [comment]
No, your fans are controlled by bios. and in manual curve, they are necessarily will hit 100%.
G15 has notoriously bugged bios, and often doesn't follow custom fan curves (also in case of AC)

**Comment by MAdimy** [comment]
I see, they were hitting 100% before with no problems that's why I assumed that it is related to the app
Thank you I appreciate you work

**Comment by seerge** [comment]
@MAdimy app calculates fan % based on max observed RPM (reported by sensor in BIOS). 

And it would update this max value if it would spot fans spinning faster than previous known max. It's probably app has spotted fans spinning faster than ever before (laptop can do that sometimes), and therefore updated it's knowledge.

Real fan speed is (most probably) unchanged :)

**Comment by seerge** [comment]
@MAdimy i have actually found an alternative way to set breathing mode for some devices, and it seem to fix support of second color on my G16

You can try latest release https://github.com/seerge/g-helper/releases/tag/v0.103
