### ISSUE TITLE
Remapping Media Keys on the ASUS ROG STRIX

### ISSUE THREAD

**Issue by pipexo4961** [seerge/g-helper#926]
Thank you very much for GHelper! It works great on my ASUS ROG STRIX G15 2021 (G513QE) (except for undervolting). I forgot about ArmoryCrate like a bad dream! My laptop does not have separate PgUp, PgDn, Home, End keys. I currently use AutoHotkey to remap them to the media keys (Next Track key, Previous Track key, Stop Media key, Play/Pause Media key), it works well, but not in all applications and it's not very convenient. Is it possible to add the ability in GHelper to remap the media keys like M1-M4?

**Comment by seerge** [comment]
It's already possible to remap M1-M4 under Extra settings

**Comment by pipexo4961** [comment]
> It's already possible to remap M1-M4 under Extra settings

No, I meant that I want to remap the media keys (red rectangle). The M1-M4 keys (green rectangle) already work great with GHelper.

![ASUS-ROG-Strix-G15-G513-Original-Black-2](https://github.com/seerge/g-helper/assets/140904758/b08986f0-9689-40e2-ab74-6a5dbb2b4597)

**Comment by seerge** [comment]
@pipexo4961 ah, those buttons are already being handled by windows. So you can just use Sharpkeys app (or any similar) to rebind them same as you would rebind any other key on keyboard.

M1-M4 keys are not handled by windows, therefore only G-Helper can do that, that's why they are in the app
