### ISSUE TITLE
Every minute G-Helper logs "A service was installed in the system.  Service Name:  WinRing0_1_2_0" to the System Log..

### ISSUE THREAD

**Issue by Noisrevid** [seerge/g-helper#928]
Every ONE (each) minute I get this in the System event log:

**Event ID:  7045**
*****************************************
A service was installed in the system.

Service Name:  WinRing0_1_2_0
Service File Name:  C:\Users\redacted\Downloads\G-Helper\WinRing0x64.sys
Service Type:  kernel mode driver
Service Start Type:  demand start
Service Account:  
*****************************************

Everything works fine, but just noticed this entry being put in the System log every each minute..   Is this by design?  

Edit:  Googling similar questions about WinRing appears to be "normal" behavior of the service gathering system information.

**Comment by seerge** [comment]
@Noisrevid hello, WInRing0 is used for a low-level system access by app only to set settings available under Fans+Power -> Advanced. If you say it appears every 30 seconds, I assume you have a custom CPU temperature limit, that (unfortunately) have to be re-applied every 30 seconds, or ryzen controller will reset it eventually.

G-Helper uses a library for UXTU here (which is in turn based on winring). And there is no other ways to set undervolting / temp limit without winring.

It doesn't literally "install" it in a system anywhere, but it runs a low level commands to a device using this file. I assume windows just registers every such case of low-level access as "install" by some reason :)
