### ISSUE TITLE
[Feature Request] Free Up Memory

### ISSUE THREAD

**Issue by LeoRH123** [seerge/g-helper#929]
Is it possible to add an option to view current Memory RAM usage like MyAsus App and free up memory with a single clic? 
![image](https://github.com/seerge/g-helper/assets/33641164/d681e837-a238-4234-a88e-3a66d204a256)

**Comment by manciuszz** [comment]
Why would you want to free up memory? Usually these 'free up memory' utilities simply clear standby memory, which in turn basically makes all your application start-up times unnecessarily slow. 

Windows alone can manage memory just fine.

**Comment by blackfiz** [comment]
@LeoRH123 you might want to check this Bitsum's reference [here](https://bitsum.com/smarttrim/).

**Comment by seerge** [comment]
@LeoRH123 hello, I completely agree with @manciuszz , such feature is useless and harms performance on modern windows systems :)

If you still want - you can use external apps that do it :)
