### ISSUE TITLE
different PPT and turbo values when plugged and on battery

### ISSUE THREAD

**Issue by EvilKilla** [seerge/g-helper#93]
Hey seerge.

is it possible to remember and apply PPT and Turbo values when plugged in and on battery?

**Comment by seerge** [comment]
Hello, app remembers mode per plugged/battery (and their respective PPTs), so just use 2 different modes for that.
as for Turbo (boost?) - it's applied only to plugged in part of the windows power plan, as on battery it barely boosts anyway
