### ISSUE TITLE
[bug] Flow Z13 Rear Window Lighting break since 0.97 update.

### ISSUE THREAD

**Issue by rainbowflesh** [seerge/g-helper#930]
Follow the #843, I test all release from 0.89 to 0.100, and located .97 will make `Rear Window Lighting` break on ghelper.exe start, but can be re-enabled in Armoury Crate.

I'm trying to find commits that contain this bug, I can physically access to the device, and I'm also SoC software developer so if anything I can help I'll try my best ;)

**Describe the bug**
Z13 Rear Window Lighting (hereinafter called *RWL*) break since 0.97 update.

**Clear scenario to Reproduce**
1. Turn on RWL in Armoury Crate.
2. run 0.96, it okey nothing change.
3. run 0.97 RWL will turn off.

**Expected behavior**
Like 0.96, runing ghelper won't turn off RWL.

**App Logs**
[97_log.txt](https://github.com/seerge/g-helper/files/12208545/97_log.txt)
[96_log.txt](https://github.com/seerge/g-helper/files/12208546/96_log.txt)
```git diff
# git diff 096.log 097.log
+ 2023/7/30 13:06:50: TL134ADXP01-0:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
+ 2023/7/30 13:06:52: USB-KB 0x18C6:5D-BD-01-FF-1E-0F
+ 2023/7/30 13:06:52: Auto:5D-BA-C5-C4-03
+ 2023/7/30 13:06:52: USB-KB 0x1A30:5D-BD-01-FF-1E-0F
- 2023/7/30 13:06:30: Auto:5D-BA-C5-C4-03
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: z13

**Asus software**
- Armoury crate (or it's services installed)
- Only `AsusOptimization.exe` except Armoury Crate stuffs.

----
edit:
most suspicious commit https://github.com/seerge/g-helper/commit/e5f0d77d05f0388b5449f7361897a60aaf54a4c5

**Comment by rainbowflesh** [comment]
I build debug on commit `3ffcc53b` and everything works fine, then build `e5f0d77d05f0388b5449f7361897a60aaf54a4c5` the RWL broke 😸 seems buggy founded.

**Comment by rainbowflesh** [comment]
By comment function `AsusUSB.ApplyAuraPower()` make the light work again, which implement in `app/AsusUSB.cs`, l: 311

```csharp
// in Setting.cs
// l:860 
public void AutoKeyboard()
{
    InputDispatcher.SetBacklightAuto(true);

    //AsusUSB.ApplyAuraPower();
...
}
```

**Comment by rainbowflesh** [comment]
Here are simplest way that fix bug:
```cs
public void AutoKeyboard(){
// ...
  if (!AppConfig.ContainsModel("Z13"))
      {
          AsusUSB.ApplyAuraPower();
      }
// ...
}
```

🤤 thats work

**Comment by seerge** [comment]
@rainbowflesh hello, it's probably cause Rear window has it's own "unique" flag to turn ON or OFF. Can you try this build and test all checkboxes under Extra (mainly "awake" line) and see if any of them actually turns window ON or OFF ?

**Comment by rainbowflesh** [comment]
> @rainbowflesh hello, it's probably cause Rear window has it's own "unique" flag to turn ON or OFF. Can you try this build and test all checkboxes under Extra (mainly "awake" line) and see if any of them actually turns window ON or OFF ?
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/12209070/GHelper.zip)

None of them work.

**Comment by seerge** [comment]
@rainbowflesh can you try this one (all checkboxes)

[GHelper.zip](https://github.com/seerge/g-helper/files/12209276/GHelper.zip)

**Comment by seerge** [comment]
If it still doesn't work. 

Alternative would be installing https://www.hhdsoftware.com/device-monitoring-studio , 

Running it and monitoring all USB traffic going to AURA device there and then running AC and trying to turn backlight window ON / OFF in it. And trying to see what payload it sends.

**Comment by rainbowflesh** [comment]
> @rainbowflesh can you try this one (all checkboxes) and post log here please as well! :)
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/12209276/GHelper.zip)

On this version, `lid` option control rear window light, work very will!

**Comment by seerge** [comment]
@rainbowflesh great, can you check if this one STILL works ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/12209298/GHelper.zip)

if so I  consider this as completed and include changes in 0.103

**Comment by rainbowflesh** [comment]
> @rainbowflesh great, can you check if this one STILL works ? [GHelper.zip](https://github.com/seerge/g-helper/files/12209298/GHelper.zip)
> 
> if so I consider this as completed and include changes in 0.103

It's still work, still `lid`, `awake` to target.

**Comment by rainbowflesh** [comment]
> @rainbowflesh great, can you check if this one STILL works ? [GHelper.zip](https://github.com/seerge/g-helper/files/12209298/GHelper.zip)
> 
> if so I consider this as completed and include changes in 0.103

I also notice that rear window light speed also controlled by `laptop backlight` slide bar, thats was awesome!

**Comment by privacyonly** [comment]
break again 0.120, works with 0.118.

**Comment by rainbowflesh** [comment]
> break again 0.120, works with 0.118.

My fresh install still working but with armor crate.
