### ISSUE TITLE
[Question] Possible to add multiple keys for key bindings

### ISSUE THREAD

**Issue by mzashh** [seerge/g-helper#936]
hey first of all i would like to thank you for such a wonderful app

now my question is can we add multiple key combinations for M meys
like i want to add win + printscr to M3, like is it possible to do so do i have to add like 0x5B + 0x2C or something else

**Comment by seerge** [comment]
It's not possible to do that literally, but possible by assigning a M-key to a regular windows key , for example F14 or something else that is rarely used (check https://github.com/seerge/g-helper#custom-hotkey-actions how to do that) 

And then binding WIN+F14 or CTRL+F14 , etc via Sharkpeys /  Autohotkey , etc.

I don't want to make current app UI overcomplicated :)
