### ISSUE TITLE
TUF-A17 "ASUS BIOS rejected fan curve"

### ISSUE THREAD

**Issue by goodolLakshay** [seerge/g-helper#942]
**Describe the bug**
Trying to Apply Custom Fan Curve gives out "ASUS BIOS rejected fan curve".

**Clear scenario to Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Fans+Power'
2. Click on "Apply Custom Fan Curve."
3. "ASUS BIOS Rejected Fan Curve" appears in RED Colour.

**Expected behaviour**
the Fan curve should be successfully applied

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12209654/log.txt)

**Screenshot**
![Screenshot 2023-07-30 213713](https://github.com/seerge/g-helper/assets/92749166/d73b5b2b-d090-401a-a6a7-a556516b0dcc)

**Desktop (please complete the following information):**
 - OS: Windows 11(Ghost Spectre Custom build) (Reproducible on Original Stock Windows 11 as well)
 - Laptop model: TUF Gaming A17 FA706IC

**Asus software**
- Armoury crate NOT installed
- MyASUS NOT Installed
- Other Asus services running NOT running (used the debloat.bat and Zero-services running confirmed in the app too).

**Comment by seerge** [comment]
@goodolLakshay it's not supported by your hardware. You also don't have custom curves in armoury.

**Comment by goodolLakshay** [comment]
I just realised that I didn't have custom curves in the Armoury. I thought this might be a bug since unsupported features were not placed in the other places. Maybe you can remove the fan curve modifier from the unsupported models in the upcoming builds.

_I have been using/following your builds and bugs for quite a long time. I really appreciate you spending your time on this project, and it has been a joy to use G-Helper and its features. Armoury was very unreliable and buggy for my model(confirmed this from other users of the same model, too), and the GPU Optimised mode never worked on it; Eco was a hit or miss too. Works flawlessly with G-Helper. I absolutely love the app. I genuinely wish to support the development as well as donate as soon as I finish college and get a job. thank you @seerge_

**Comment by seerge** [comment]
@goodolLakshay there is no way to check in advance if fan curves are supported or not. Only by manually hardcoding model names / verifying with users. So it will probably stay like that for now.
