### ISSUE TITLE
[Bug] No CPU temp showing up

### ISSUE THREAD

**Issue by marcelomijas** [seerge/g-helper#946]
**Describe the bug**
No CPU temps in GHelper v103, it's not only about the temp not displaying is also that fan profiles do not work (as CPU temp is 0?). Had to manually set the CPU fan curve up from the beginning to prevent frying the laptop (XD). No problem with GPU temp.

Also, my previous settings have been erased automatically (?).

**Clear scenario to Reproduce**
Use GHelper v103 on G14 2020.

**Expected behavior**
CPU temp should be showed and fan profiles should work like in v102

**App Logs**
```
30/07/2023 21:38:09: App launched: ROG Zephyrus G14 GA401IV_GA401IV :0.103.0.0es-ES.
30/07/2023 21:38:09: NVIDIA GeForce RTX 2060 with Max-Q Design
30/07/2023 21:38:10: CPU: 3 - AMD Ryzen 7 4800HS with Radeon Graphics          - AMD64 Family 23 Model 96 Stepping 1
30/07/2023 21:38:11: AutoSetting for Online
30/07/2023 21:38:11: Input: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&3397f86&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
30/07/2023 21:38:11: Mode = 0 : OK
30/07/2023 21:38:11: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
30/07/2023 21:38:11: SET GPU CLOCKS: 0, 0
30/07/2023 21:38:11: FanCPU = 14-1B-3A-40-48-4D-51-62-12-12-12-19-22-29-30-45 : OK
30/07/2023 21:38:11: FanGPU = 1E-3A-3D-40-48-4D-51-62-00-0C-16-1D-26-2D-34-4A : OK
30/07/2023 21:38:11: Eco flag : -65536
30/07/2023 21:38:11: Mux flag : -65536
30/07/2023 21:38:11: :DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
30/07/2023 21:38:11: 19EN33:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_HDMI: \\.\DISPLAY2
30/07/2023 21:38:11: USB-KB 0x1866:5D-BD-01-FF-1E-FF-FF-FF
30/07/2023 21:38:11: Auto:5D-BA-C5-C4-01
30/07/2023 21:38:11: USB-KB 64|32Dispositivo definido por el proveedor compatible con HID\\?\hid#vid_0b05&pid_1866&mi_02&col03#8&3397f86&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}:5D-B3-00-00-FF-FF-FF-EB-00-00-FF-FF-FF-00-00-00-00
30/07/2023 21:38:12: GET GPU CLOCKS: 0, 0
30/07/2023 21:38:12: Monitor Power On
30/07/2023 21:38:13: Latest version 0.103.0.0
30/07/2023 21:38:13: Design Capacity: 75998mWh, Full Charge Capacity: 63189mWh, Health: 0,8314560909497618358377852049%
30/07/2023 21:38:17: Varibright: 1,2
```

**Screenshots or screencasts**
![imagen](https://github.com/seerge/g-helper/assets/62946623/cb086a7a-31fb-49db-82af-5cc98c4bda0e)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Laptop model: G14 GA401IV (2020)

**Asus software**
None

**Comment by seerge** [comment]
@marcelomijas hello,

I indeed removed a fallback temperature reading (from windows), and left only asus sensor. Apparently for older devices that sensor doesn't exist :)

I have returned fallback reader and re-uploaded hotfixed https://github.com/seerge/g-helper/releases/tag/v0.103

As for fan profiles - it's unchanged since the very-first version ever, app sets it ``30/07/2023 21:38:11: Mode = 0 : OK``. Fans are controlled by BIOS, not by app :) I would rather attribute it to some coincidence , try to reboot mb ?

**Comment by marcelomijas** [comment]
@seerge Thanks a lot! It is working again!

About the config reset, now I also think that is a coincidence, installed v102 and then your new v103 and settings did not reset.

**Comment by seerge** [comment]
@marcelomijas config resets, when app fails to read it (i.e. there is extra comma, quote or something like that in a structure). 

That's a dumb fallback mechanism that I have added in the very beginning :)

Unfortunately json is quite strict format (in terms of structure), and should probably go for a simple "ini" file. But it's too late to change  :)
