### ISSUE TITLE
v0.103 breaks CPU temp reading

### ISSUE THREAD

**Issue by manciuszz** [seerge/g-helper#947]
![image](https://github.com/seerge/g-helper/assets/2539661/cfe8f3b4-fe80-44c3-be18-a4aeb4ce1c45)

Tried to delete **config.json** to see if it was a config error, yet it yielded same results.

The 'heatmap' lighting feature also doesn't work because of this, I assume.

Speaking of 'heatmap' it works in v0.102, however it makes the entire RGB 'blink' every 1 second on each update. In other words, it goes from Read Temp ->Reset RGB lighting to black -> Set RGB color to CPU temp defined color, instead of Read Temp -> Update Existing RGB light to new color.

**Comment by seerge** [comment]
@manciuszz It's a dublicate of https://github.com/seerge/g-helper/issues/946 :) i have already uploaded a hotfix over 0.103 and returned a fallback CPU reading method

**Comment by seerge** [comment]
@manciuszz can you check if heatmap works in this build : ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/12210152/GHelper.zip)

**Comment by manciuszz** [comment]
I've tested this build and the 'heatmap' feature doesn't blink anymore, but it's not updating the temperature either.

**Comment by seerge** [comment]
@manciuszz can you check this build ?

It was blinking cause app was setting a static-color mode each time, and some models do blink with it. I have tried to replace it with what AC does when run's it's software-custom modes

[GHelper.zip](https://github.com/seerge/g-helper/files/12216803/GHelper.zip)

**Comment by manciuszz** [comment]
I've tested this latest build and it still behaves exactly the same like the previous one. The CPU temp is 80C and the keyboard is displaying white color, just like static mode would do. The only difference between heatmap and static is that in static both the keyboard and bottom LEDs are white, in heatmap the keyboard is white and the bottom is 'rainbow' colored.

**Comment by seerge** [comment]
@manciuszz then it looks like for some models (especially ones suffered from "blinking" in first place) there is some tricky payload that AC only knows how to send in order to set colors on the fly.

As i remember you are technical, mb you can try to catch that using https://www.hhdsoftware.com/device-monitoring-studio 

And running AC in "Aura" mode (i.e. when it doesn't use hardware modes of keyboard, but sets them programmatically)

And compare to what I do already at https://github.com/seerge/g-helper/blob/86bc0f4e5d98ef3e0ec4c3c2d2a21af09131a6a5/app/AsusUSB.cs#L464

I have literally copied all packages here (even supposedly garbage ones) that AC was sending to my G16 Strix and G14 (so both devices work well)

But again, that's purely voluntarily :D

**Comment by manciuszz** [comment]
Looks interesting. Let me try right now.

**Comment by seerge** [comment]
@manciuszz hello, thanks for checking.

`` 0xb3;`` is hardware-modes of your keyboard, g-helper supports all of them already (except i didn't add directions to the UI to keep it simple)

What I need is a "manual" mode, you can turn it on by going to Aura tab  (from your left menu) , checking your keyboard there to sync - > and setting some static color  or color cycle there for example

Payload for those modes contains 0xbc (that's what I use already)

But it could be some tricky init payloads that are different (i try to do them already, but apparently they don't work for your device)
```
                auraDevice.WriteFeatureData(LED_INIT2);
                auraDevice.WriteFeatureData(PrepareAuraMessage(new byte[] { AURA_HID_ID, 0x05, 0x20, 0x31, 0x00, 0x1A}));
                auraDevice.WriteFeatureData(PrepareAuraMessage(new byte[] { AURA_HID_ID, 0xbc, 1, 0, 0, 0 }));
                auraDevice.WriteFeatureData(PrepareAuraMessage(new byte[] { AURA_HID_ID, 0xbc, 1, 1, 4, 0 }));
```

Color-set command itself is

```
AURA_HID_ID, 0xbc, 1, 1, 4(multi-zone flag), 0, 0, 0, 0, R, G, B,R, G, B,R, G, B,R, G, B, (repeated a lot of times for each "zone")

**Comment by manciuszz** [comment]
Unfortunately, the currently installed ArmouryCreate has a borked "Aura Sync" feature on my device (I intenionally broke it when I was still using Armoury Crate, cause it was/still is redundant in my eyes), so clicking on it does nothing other than "waiting for syncing process blahblahblah..." 

So, until I fix that I can't check the packets :/

I'll see what I can do sometime in the near future, just need to reinstall AC properly first. Thanks for giving more information though, I appreciate that.
