### ISSUE TITLE
Bug with switching GPU modes

### ISSUE THREAD

**Issue by XynoCrest** [seerge/g-helper#948]
**Describe the bug**
- The bug is nothing technical, just a minor inconvenience. 
- I have a 2022 Zephyrus G15 and I usually use the Optimized GPU mode for everyday task. It works great!
- When gaming I usually switch to ultimate, it restarts and successfully switches.
- The problem occurs when you want to switch back to Optimized and you click the Optimized button under GPU Mode in Ghelper, the laptop restarts and sets itself into Standard GPU mode. 
- It doesn't switch to Optimized for which you clicked the button for, and you have to manually switch to Optimized.  

**Clear scenario to Reproduce**
1. Be in Ultimate GPU mode
2. Click on Optimized under GPU Modes 
3. If your laptop doesn't have advanced Optimus like mine, wait for it to restart
4. After restart, it will switch to Standard and not Optimized. 

**Expected behavior**
While in Ultimate, If you click the Optimized button to switch to that GPU Mode, it should switch to Optimized, not Standard. 

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12210067/log.txt)

**Desktop**
 - OS: Windows 11 64-bit
 - ROG Zephyrus G15 GA503RM

**Asus software**
- Armoury Crate not installed
- MyASUS not installed
- Other Asus services running in background - 0

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/12210235/GHelper.zip)
This build should remember Optimized mode
