### ISSUE TITLE
The scroll wheel button in the top left corner of my ROG Zephyrus S17 laptop is not functioning properly

### ISSUE THREAD

**Issue by mgulant** [seerge/g-helper#949]
The scroll wheel button in the top left corner of my ROG Zephyrus S17 laptop used to have the ability to adjust various functions such as volume and screen brightness by pressing and sliding it. However, currently it only works for adjusting the volume and the light next to the scroll wheel does not turn on when the laptop is in sleep mode, even though the keyboard backlight is still functioning.

**Comment by seerge** [comment]
> Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.
