### ISSUE TITLE
[Feature request] Keyboard bindings for external keyboards

### ISSUE THREAD

**Issue by PlayingKarrde** [seerge/g-helper#95]
Would be amazing if it were possible to add the ability to bind a keyboard shortcut to performance switching. The M4 button is great for when you are using as a laptop, but when using a keyboard and connected to an external monitor, the key is not accessible.

**Comment by seerge** [comment]
Main problem here, that then app will have to catch ALL keystrokes from keyboard (i.e. become a keylogger). And I'm afraid people will start accusing me in logging their keys then ...

**Comment by seerge** [comment]
Seems like I have managed to catch only specific key for that : Ctrl+Shift+F5 (to mimic default FN+F5 as close as possible), Ctrl+Shift is used together cause alone this keybind is used in other apps

Live in https://github.com/seerge/g-helper/releases/tag/v0.49
