### ISSUE TITLE
CPU temp limit not working

### ISSUE THREAD

**Issue by andrew-fletcher-asus** [seerge/g-helper#952]
**Sorry can you delete the other bug same name**

##Describe the bug##
I love g helper as Asus armoury create just wasn't working for me, I bough a new Asus ROG Strix G17 and installed g helper no issues and followed your instructions, but I do have an issue. When I set the CPU limit to say 85c it goes over it every time, I have to reduce the watts to control the CPU temp as it goes over 95c every time I play a game. The issue I think could be because it's the Ryzen 9-7845HX (Dragon Range) ?

##Clear scenario to Reproduce##
1.	Go to CPU Temp
2.	Click on Set Temp to 85c
3.	Open a game
4.	Temp goes over 85c

##Expected behavior##
g helper to reduce the watts back and maintain around 85c

##App Logs##
None

##Screenshots or screencasts##
I can if needed, but like I say it goes over 85c even if it's set to 85c, and it's not a little over it's 95-97c
Desktop (please complete the following information):
•	Windows 11]
•	Laptop - ASUS ROG Strix G17 AMD Ryzen 9-7845HX 16GB DDR5-SDRAM
Asus software
•	Armoury Crate removed
•	MyASUS removed
•	Other Asus services running in background only the ones you said I needed, but I can give you a screen shot again if needed?

##Additional context##
Like I say I love G helper and I'll not uninstall because of this issue I'll just reduce the watts myself, but if you could fix it that would be great :)

**Comment by seerge** [comment]
> Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Comment by seerge** [comment]
@andrew-fletcher-asus w/o logs i can't say if it works or not even, you didn't submit that. 

G-Helper uses Ryzen SMU backend from UXTU for running "advanced" settings (i.e. temp limit + undervolting). If it doesn't work in UXTU - it won't work here neither.

**Comment by andrew-fletcher-asus** [comment]
I'll will find the logs later on this evening and submit them :) again thank you @seerge  for your superb support
