### ISSUE TITLE
No access to the differents GPU modes.

### ISSUE THREAD

**Issue by DofIamingo** [seerge/g-helper#959]
Hello, 

I've just download G-Helper. I uninstalled Armoury Crate. When I open G-Helper I have this message in the GPU Mode section : Gpu's aplications have stopped". I can't choose eco, standard, ultimate nor optimized. Do you guys have ever faced this issue ? 

I'm on ASUS TUF Gaming btw. Thanks for your answers!

**Comment by seerge** [comment]
If your device doesn't support disabling dGPU on hardware level, you won't see any modes.

Cause you have completely ignored all requested details, and didn't provide any logs nor even model name I'm closing this.

**Comment by DofIamingo** [comment]
Hello Seerge, sorry I didn't realise that they were a way to describe an issue, my bad there. 

**Describe the bug**
I don't see any modes in the GPU mode. The following message appears GPU's application have stopped"

**Expected behavior**
To see different modes : eco, standard, optimized ...

**Screenshots or screencasts**
[[url=https://www.noelshack.com/2023-31-2-1690843403-ghelp.png][img]https://image.noelshack.com/minis/2023/31/2/1690843403-ghelp.png[/img][/url]](https://www.noelshack.com/2023-31-2-1690843403-ghelp.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model : ASUS TUF Gaming FX505DV

**Asus software**
- Armoury Crate uninstalled
- MyASUS installed
- No Other Asus services running in background

Hope that'll be enough informations, cheers!
