### ISSUE TITLE
Backlit Keyboard not working and other fn modes for keyboard

### ISSUE THREAD

**Issue by eun0115** [seerge/g-helper#961]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.

**Describe the bug**
backlit keyboard sometimes works, sometimes doesnt. it requires to reboot to work it again

**Clear scenario to Reproduce**
1. Go to G-helper
2. Click on Laptop Keyboard Modes to change light modes and click extra to change the backlit brightness
OR
1. FN + Arrow up / Down for backlit brightness
2. FN + Arrow left / right for keyboard light modes

**Expected behavior**
FN + Arrow up / Down for backlit brightness, it didnt work.
FN + Arrow left / right for keyboard light modes, it mutes the music instead

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12224142/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/67692232/7e55fe29-3523-4be5-994b-6375c2142fb3)
![video](https://github.com/seerge/g-helper/assets/67692232/a05d2263-cf75-40b1-b8a1-3a3ac25ab05e)

**Desktop (please complete the following information):**
 - Windows 10 LTSC 
 - TUF Gaming F15 FX506HC

**Asus software**
Asus Services are stopped
No Asus bloats are installed

**Additional context**
Check the attached photo and video

**Comment by seerge** [comment]
@eun0115 hello, this is the first time  i hear that FN + Up/Dn changing brightness. 

On most devices they emit PgUp/PgDn commands on hardware level.

Can check what codes do they emit specifically by pressing them and looking into log immediately ? As it's difficult to figure it out now

**Comment by seerge** [comment]
@eun0115 well, from log i see app sets correct backlight payloads every time you try to change it :) 

On your video it's actually a "sleeping" animation for keyboard (it's turned on by BIOS when it thinks device is sleeping). 

Why BIOS thinks so - i have no idea :) could be some issues with windows/bios, which is in any form not controlled by the app.

Try to reboot or do a hardware reset even https://github.com/seerge/g-helper#how-do-i-do-a-hardware-reset-on-a-laptop 

Do you use latest BIOS?

**Comment by eun0115** [comment]
i will try the hardware reset, and yes im using the latest bios v313 (or 311 i think). thanks for the help!

**Comment by eun0115** [comment]
i just did a hardware reset and ill let you know if the problem still occurs.

**Comment by eun0115** [comment]
update:

it still persist. its kind of terrible where backlight cant be useable until it get restarted when it enters to sleep

**Comment by seerge** [comment]
@eun0115 well, it looks like a hardware issue

Does disabling sleeping animation via Extra settings help?

**Comment by eun0115** [comment]
@seerge i tried and it fixes my issue, this might be workaround for this model and for some as well.

**Comment by seerge** [comment]
@eun0115 ok :) glad it worked out
