### ISSUE TITLE
Fn+Numpad Enter issue

### ISSUE THREAD

**Issue by DarkEdgeXD** [seerge/g-helper#963]
**Describe the bug**
 Fn+Numpad Enter follows the behaviour of the M4 key without an option to change the behaviour since v0.102 prerelease. 

**Clear scenario to Reproduce**
Pressing Fn+Numpad Enter and then the M4 key 

**Expected behavior**
A seperate Fn+Numpad Enter binding in extra

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12225574/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - ASUS TUF Gaming A15 FA507RM_FA577RM

**Screenshot**
![Screenshot 2023-08-01 123542](https://github.com/seerge/g-helper/assets/140395178/7ff57663-7b15-43a4-bdc9-19e159a04a82)

**Asus software**
Tried with both no ASUS Services running and only ASUS optimisation running.

**Comment by seerge** [comment]
@DarkEdgeXD do I understand correctly that you have M-keys row as well?

**Comment by DarkEdgeXD** [comment]
@seerge Yes, the layout is as the image shows:
![image](https://github.com/seerge/g-helper/assets/140395178/2a2c3d22-484c-4ee2-be31-1ce0a64c41a1)

**Comment by seerge** [comment]
@DarkEdgeXD try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/12228435/GHelper.zip)

**Comment by DarkEdgeXD** [comment]
@seerge Works perfectly! :) Thanks a lot!

**Comment by seerge** [comment]
Great, closing as completed then
