### ISSUE TITLE
No access to differents gpu mod

### ISSUE THREAD

**Issue by DofIamingo** [seerge/g-helper#965]
Hello , sorry I didn't realise that they were a way to describe an issue in my previous post, my bad there.

Describe the bug
I don't see any modes in the GPU mode. The following message appears GPU's application have stopped"

Expected behavior
To see different modes : eco, standard, optimized ...

Screenshots or screencasts
[[url=https://www.noelshack.com/2023-31-2-1690843403-ghelp.png][img]https://image.noelshack.com/minis/2023/31/2/1690843403-ghelp.png[/img][/url]](https://www.noelshack.com/2023-31-2-1690843403-ghelp.png)

Desktop (please complete the following information):

OS: Windows 11
Laptop model : ASUS TUF Gaming FX505DV
Asus software

Armoury Crate uninstalled
MyASUS installed
No Other Asus services running in background
Hope that'll be enough informations, cheers!

**Comment by seerge** [comment]
@DofIamingo hello, as I have answered you in previous request 

> Your device doesn't support disabling dGPU on hardware level, you won't see any modes.
