### ISSUE TITLE
Heatmap not working on ASUS ROG Strix SCAR 15 (2022)

### ISSUE THREAD

**Issue by Kowken** [seerge/g-helper#967]
## NOTE

**Describe the bug**
Setting the color scheme to heatmap will keep the previous one playing and changing again will also ignore heatmap.

**Clear scenario to Reproduce**
Switch from the current color scheme to "heatmap".

**Expected behavior**
I don't know what the heatmap looks like in GHelper, but I expected some kind of menu to get modify temps thresholds as well as colors for each of them.

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/78725741/93301def-95ee-4e37-81e0-14ffd1edecd2)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2 22621.2070
 - ASUS ROG STRIX SCAR 15 G533ZW AS94

**Logs**
Does not add any new log entry when I switch to heatmap.

**Asus software**
- Armoury Crate uninstalled
- MyASUS uninstalled
- No ASUS services working in the background

**Additional context**
Also does not work when I activate all services:
- ArmouryCrateControlInterface
- ASUSOptimization
- AsusAppService
- ASUSLinkNear
- ASUSLinkRemote
- ASUSSoftwareManager
- ASUSSwitch
- ASUSSystemAnalysis
- ASUSSystemDiagnosis
- AsusCertService

P.S: The feature works in ver 0.102 at the demerit of Turbo mode not functioning.

**Comment by Kowken** [comment]
> @Kowken can you check if this build makes any difference ? [GHelper.zip](https://github.com/seerge/g-helper/files/12232754/GHelper.zip)

I will (also not the same issue but Turbo mode is applying Silent mode or straight up shutting down fans fan curves unless one explicitely apply curves instead of applying factory settings)

**Comment by seerge** [comment]
@Kowken can you post a log at least?

**Comment by Kowken** [comment]
Build yielding te same results (no logs as well)

**Comment by seerge** [comment]
@Kowken without logs i can't help much :)

This build has an old way of setting colors for a heatmap, but that would probably blink on your device ...

[GHelper.zip](https://github.com/seerge/g-helper/files/12232838/GHelper.zip)

**Comment by Kowken** [comment]
@seerge which logs would you require ? The event of switching to the heatmap is not displayed contrary to others but maybe something else may help you. Please tell me a scenario or set of actions you want me to record and I'll post the log outputted.
Thanks in advance

**Comment by seerge** [comment]
@Kowken logs for this issue

> Turbo mode is applying Silent mode or straight up shutting down fans fan curves unless one explicitely apply curves instead of applying factory settings

Full log will work

**Comment by seerge** [comment]
@Kowken in the build linked last in this thread it should be 2 heatmap modes in your dropdown

Heatmap - is literally same from v.102
Heatmap Alt - is a new more smooth approach that I used in 103 (but it doesn't seem to be supported on some devices)

As for your modes , i see that you were switching between all 3 of them. And all of them have default fan curves . Your fans are controlled by BIOS all the time (and especially when there is no custom curve set), so I can't help here much :)

**Comment by Kowken** [comment]
> @Kowken in the build linked last in this thread it should be 2 heatmap modes in your dropdown
> 
> Heatmap - is literally same from v.102 Heatmap Alt - is a new more smooth approach that I used in 103 (but it doesn't seem to be supported on some devices)
> 
> As for your modes , i see that you were switching between all 3 of them. And all of them have default fan curves . Your fans are controlled by BIOS all the time (and especially when there is no custom curve set), so I can't help here much :)

So you mean that I have to fix the fan curves for them to work as expected ? In that case, what are the fan curves for and why do I have a more consistent experience with the balanced one than the turbo one ?

Also do you mean the build you linked 2 hours ago ? Before adding the question label ?

**Comment by seerge** [comment]
@Kowken I mean that I don't know why your fans misbehave :) App doesn't control them, and doesn't prevent them from running neither. It just sets one of 3 default modes (that you can also set w/o any app even powershell as admin) : 

```
Values: 0 - Balanced, 1 - Turbo, 2 - Silent.

(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00120075, Value)

```

The build is linked in this thread, if you have trouble finding a zip here is a link again : 
[GHelper.zip](https://github.com/seerge/g-helper/files/12233727/GHelper.zip)

**Comment by Kowken** [comment]
> @Kowken I mean that I don't know why your fans misbehave :) App doesn't control them, and doesn't prevent them from running neither. It just sets one of 3 default modes (that you can also set w/o any app even powershell as admin) :
> 
> ```
> Values: 0 - Balanced, 1 - Turbo, 2 - Silent.
> 
> (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00120075, Value)
> ```
> 
> The build is linked in this thread, if you have trouble finding a zip here is a link again : [GHelper.zip](https://github.com/seerge/g-helper/files/12233727/GHelper.zip)

Sorry I found the build:

Heatmap 1.02 works but the alt one does not, could you please remove it or show me how to so I don't mix things up ?
Also, do the fan curves stay fixed once I checked the mark in case of a reboot or do I have to set it every time ?

**Comment by seerge** [comment]
@Kowken The problem is that for some devices Heatmap works ok, and for others Heatmap Alt. And so far I didn't find an universal way to detect it reasons. Hardcoding each model name (and testing) is unrealistic, so it will stay like that for now until i figure out something

Each time app starts / wakes up from sleep / or changes mode even - it would apply a custom fan curve if "apply" is selected. 

Does quitting g-helper, and just changing modes via powershell result in same bugged fan behavior ? 

Mb Try https://github.com/seerge/g-helper#how-do-i-do-a-hardware-reset-on-a-laptop

**Comment by seerge** [comment]
@Kowken can you check if 'heatmap alt" still doesn't work in this build : ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/12233925/GHelper.zip)

**Comment by Kowken** [comment]
Sorry for the late reply.

This is the error I get when I put the command above:
![image](https://github.com/seerge/g-helper/assets/78725741/6d84c5a7-5fca-494b-a75f-84b732039087)
What am I doing wrong ?

Is there a way to get rid of the blinking with the regular heatmap ? (The one from 0.102)
I will try a hardware reset and see how it turns out.

**Comment by seerge** [comment]
@Kowken if powershell command returns error, probably it's blocked on your device :) Then you need to rely on G-Helper / AC in this case.

I was trying to eliminate blinking with new approach to set colors (in what you see as Heatmap Alt), but some devices require some other unknown (and not documented) payloads, that i can't add.

**Comment by Kowken** [comment]
Ok so do you mean that the one which is suppported on my computer cannot get rid of the blinking while the unsupported one can ? Because if that is the case then we can close this issue. I think the EC reset solved my issue anyways. Also is it possible to have a build featuring only the supported heatmap ? (Like 2 release) Or would you rather have both on the same one ? Thanks in advance and thank you for helping me.

**Comment by Constrat** [comment]
Can confirm 0.103 Heatmap not working on G17 2022 (G713RW), seems like all the G15, G17, SCAR15 and SCAR17 have the same hardware controllers.
I've tried the linked build in this thread (0.104),

- "Heatmap" is working, kinda, the lightbar flashes every 2 seconds
- "Heatmap Alt" is not working, the effect remains the one selected precedently.

The funny thing: "Heatmap" doesn't work in 0.103, but DOES work-ish in 0.104
"Heatmap Alt" doesn't work in 0.104.

I was also looking through the logs, but I can't find anything useful regarding the RGB lighting switching anyway, here is it:
[log.txt](https://github.com/seerge/g-helper/files/12237524/log.txt)

**Comment by Kowken** [comment]
> @Kowken can you check if 'heatmap alt" still doesn't work in this build : ? [GHelper.zip](https://github.com/seerge/g-helper/files/12233925/GHelper.zip)

Heatmap alt still doesn't work in this build.
Regular heatmap is a lot more stable though (no blinking of the keyboard although the lid, logo and lightbar leds to blink every second or so)

**Comment by seerge** [comment]
@Constrat @Kowken Heatmap will probably always blink in your cases, cause what app does  - is just sets a "Static" backlight each 2 seconds (with new color)

I tried to use a dynamic color setting (same as AC uses when does it's "custom" modes) in Heatmap Alt, and it works on most of the devices (including my Strix G16), but apparently not on all :) w/o knowing payload differences - it's not realistic to change here

If you want you can try to check what AC sends in your cases

1. Have AC installed and install https://www.hhdsoftware.com/device-monitoring-studio
2. Disable Aura Sync in AC (i.e. set any standard backlight modes for keyboard)
3. Run Dev Monitoring Studio, select N-Key device (19b6, i.e. Asus Aura Keyboard) and start capturing all USB traffic it gets in Packet form 
4. Enable Aura Sunc in AC, and check what AC sends to keyborad in this case

For the reference - what app sends currently https://github.com/seerge/g-helper/blob/a27906b1b74d6d37e9faba75edab6d02e8fb15b6/app/AsusUSB.cs#L479C13-L479C13 

Let me know if you are willing to check.

Thanks.

**Comment by Constrat** [comment]
Honestly, I'm good XD. The Heatmap thing is ugly af so I just wanted to give some context / info. (Let's be honest it will never stay on green for more than 30 seconds)

**Comment by seerge** [comment]
@Constrat well, I don't think it's ugly. Numerous people have asked for it.

**Comment by Constrat** [comment]
Oh really? I thought it was just completition to perfectly clone everything that AC does. Thought I wasn't the only, guess I am

**Comment by Kowken** [comment]
> 

I have log from WireShark capturing usb traffic in numerous situation for Aura (thanks to USBPC)
I will send you a mega link from which you can get all scenarios (since Github does not support pcapng files)
https://mega.nz/folder/D0FAnK5S#KJrWJYRSjWJNZq8eI4PkpQ

- ArmouryCrateInstall contains all packets exchanged during AC and Aura creator joined installation.
- AuraCreatorOpen is when I opened the app for the first time
- EnableAuraSync is probably the one you are looking for as the name suggests
- LightbarLidRestart is an interesting one: I cut all services with GHelper and tried to use OpenRGB to set lid, logo and lightbar leds only to red. It failed whereas it wouldn't before when Aura Service was active. So I recorded me setting the Aura creator color scheme to only those lights and it took a bit more time to work meaning that there may have been some additional packet transmission.
- Keyboard and LightBarLid are just profiles with either only the keyboard all in red or only the lightbar, lid and logo in red.

**Comment by seerge** [comment]
@Kowken hello, thanks. But it's tremendously difficult to find a right things among thousands of raw data, w/o knowing what happens there.

I would just need like first 5-10 packages being sent exactly after clicking AuraSync :)

I have noticed that some packages that look similar to ones i used, but have 0 instead of 1 in one spot ... try this build **(Heatmap Alt mode)**

[GHelper.zip](https://github.com/seerge/g-helper/files/12239604/GHelper.zip)

If it doesn't work still - i'm afraid i will need only specific packages :) rather trying to find a needle in a haystack

**Comment by Kowken** [comment]
> @Kowken hello, thanks. But it's tremendously difficult to find a right things among thousands of raw data, w/o knowing what happens there.
> 
> I would just need like first 5-10 packages being sent exactly after clicking AuraSync :)
> 
> I have noticed that some packages that look similar to ones i used, but have 0 instead of 1 in one spot ... try this build **(Heatmap Alt mode)**
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/12239604/GHelper.zip)
> 
> If it doesn't work still - i'm afraid i will need only specific packages :) rather trying to find a needle in a haystack

The aformentioned "Heatmap Alt" build only activates the rog keystone led and leaves it like that even when switching mode.
Do you mean to say that WireShark isn't appropriate for this kind of research or that we can't capture what we are looking for anyways ?

**Comment by seerge** [comment]
I'm just saying that I need a information about right packages to send. Currently i don't have it, not sure how many times I need to write it, as it seem to be a lingual barrier here or something.

**Comment by Kowken** [comment]
> I'm just saying that I need a information about right packages to send. Currently i don't have it, not sure how many times I need to write it, as it seem to be a lingual barrier here or something.

My bad, sorry for taking your time.
Is there anything I can do to help you out on this one ? I'm not sure what to send as well. Hence why I asked if you preferred that I used another software which you'd be sure that it would output workable data.

**Comment by seerge** [comment]
I checked how openRGB sets colors for keyboards, it seem to copy what AC does.

Check if Heatmap ALT in this build makes any difference

[GHelper.zip](https://github.com/seerge/g-helper/files/12240987/GHelper.zip)

**Comment by Constrat** [comment]
Ok so on G713RW:
Heatmap: keyboard area working as intended/expected, lightbar flashing
Heatmap Alt: keyboard area working as intended/expected, lightbar off

**Comment by seerge** [comment]
@Constrat thats good news, but for that alt mode app has to send 10 usb packets every refresh (same as openrgb does). Which is quite taxing to resources

**Comment by Constrat** [comment]
> @Constrat thats good news, but for that alt mode app has to send 10 usb packets every refresh (same as openrgb does). Which is quite taxing to resources

I never thought OpenRGB did that. But I guess we are all on the same boat...
But... The thing is. If ALT mode is that much taxing to the system (and it is) the lightbar still doesn't work, so I guess it's kinda useless, unless looking at OpenRGB code you have a way to make it work also for the lightbar

Otherwire the user would choose the Heatmap Default and deal with the strobing lightbar

**Comment by seerge** [comment]
@Constrat check if this one fires lightbar
[GHelper.zip](https://github.com/seerge/g-helper/files/12242014/GHelper.zip)

**Comment by seerge** [comment]
@Constrat can you check if this one still works?
[GHelper.zip](https://github.com/seerge/g-helper/files/12242466/GHelper.zip)

I'm trying to reduce amount of unnecessarily packages

**Comment by Constrat** [comment]
So I'm checking from A0 -1 everytime? Or from 00 +1 everytime?

**Comment by seerge** [comment]
@Constrat from 0 to (unknown value)

**Comment by Constrat** [comment]
Ok

**Comment by Constrat** [comment]
Give me some minutes, I'm installing VS... I removed a long time ago XD.

**Comment by Kowken** [comment]
> 

Sorry fr the late reply, this build fires the heatmap without blinking but also lights up the rogkey rgb while keeping it that way even after changing mode

**Comment by Kowken** [comment]
> @Constrat can you check if this one still works? [GHelper.zip](https://github.com/seerge/g-helper/files/12242466/GHelper.zip)
> 
> I'm trying to reduce amount of unnecessarily packages
> 
> If not : can you check (by compiling app from source) how many steps does your device actually in this loop: https://github.com/seerge/g-helper/blob/main/app/AsusUSB.cs#L512
> 
> it goes from 0x00 -> 0x10 -> ... ->0xA0 which theoretically stands for lightning zones, but most probably majority of them are redundant

This one only lights up the rogkey, M buttons, lid, logo and lightbar leds

**Comment by Constrat** [comment]
Yeah, I'm testing all the values
To see the lowest one that works best.

**Comment by Constrat** [comment]
@seerge
The value `A0` lights almost all of them up, except the last two arrow keys,
`B0`, lights all of them up but it keeps a red color that strobes the color of the other keys every two seconds on the top row ROG, Mute, Fan etc, and the `J` strobes with the top row, but keeping the same color

**Comment by Constrat** [comment]
https://github.com/seerge/g-helper/assets/56174894/7d11910e-2726-4f64-a6b0-76b346ac794c

**Comment by Constrat** [comment]
It's hard to explain...

**Comment by seerge** [comment]
@Constrat it's a loop of multiple commands with address from 00 to A0, each one probably lights one row, or not ?

**Comment by Constrat** [comment]
It should but... Incrementing from `00` by `01` everytime, increases the number of keys that light up. Only issue is that with A0, not all of them are on. Two arrow keys are missing.

**Comment by Kowken** [comment]
I'm sending two videos as well

**Comment by seerge** [comment]
You don't need to increment by 01 :) increment by 0x10 :)

**Comment by Constrat** [comment]
I misstyped, meant to say 10, my bad

**Comment by Constrat** [comment]
I tried 00, 10, 20, 30, 40, 50, 60, 80, 90, A0. They increasingly light almost all of the keys. At A0 there's only two missing.

**Comment by seerge** [comment]
ok, so the way i did it originally, is the minimum amount of data that you need to send then.

Each payload is per-key color setting, containing 16 kety in each, 0x00 -> 0xA0 is a number of group (i..e from where to start)

**Comment by Constrat** [comment]
Btw, I'm sorry if before I seemed rude but I thought that the heatmap was similar to the one of AC which had only 3 stupid colors, but here I'm noticing it's a shading which is really cooler!

**Comment by Constrat** [comment]
> > @Constrat check if this one fires lightbar
> > [GHelper.zip](https://github.com/seerge/g-helper/files/12242138/GHelper.zip)
> 
>  recorded-8830608731425.mp4

I don't know if you noticed but your two arrow keys are not lighting up in the heatmap alt (the bottom and the right)

**Comment by Constrat** [comment]
> @Constrat check if this one fires lightbar
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/12242138/GHelper.zip)

When you sent this one, I didn't notice that the arrow keys were not lighting up. It seems like they never do? this smells fishy

**Comment by Kowken** [comment]
> > > @Constrat check if this one fires lightbar
> > > [GHelper.zip](https://github.com/seerge/g-helper/files/12242138/GHelper.zip)
> > 
> > 
> > recorded-8830608731425.mp4
> 
> I don't know if you noticed but your two arrow keys are not lighting up in the heatmap alt (the bottom and the right)

Damn you are right ! Also you said that the non blinking heatmap was using more ressources than the blinking one right ?

**Comment by Constrat** [comment]
Yeah we were trying to reduce the "more resources" without turning off any keys

**Comment by Kowken** [comment]
> 

I have the same results as @Constrat on this one

**Comment by seerge** [comment]
@Constrat does going to 0xB0 light up remaining keys ?

**Comment by Constrat** [comment]
Yes but...

> VID_20230802_192819.mp4

**Comment by Constrat** [comment]
https://github.com/seerge/g-helper/issues/967#issuecomment-1662665599

**Comment by seerge** [comment]
Can you check if this makes a difference ?

I have a feeling it needs to stop inbetween A0 and B0 ...
[GHelper.zip](https://github.com/seerge/g-helper/files/12243460/GHelper.zip)

**Comment by Kowken** [comment]
> Can you check if this makes a difference ?
> 
> I have a feeling it needs to stop inbetween A0 and B0 ...
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/12243502/GHelper.zip)

The build crashes after Heatmap Alt is activated (can't open it again and not responding, had to delete Roaming file because it would default to Heatmap alt otherwise), it makes the fan go crazy for a short amount of time, makes the m keys blink at high speed between heatmap, red and purple and desacticate Lid, Lightbar and logo leds

**Comment by seerge** [comment]
And this ?
[GHelper.zip](https://github.com/seerge/g-helper/files/12243577/GHelper.zip)

**Comment by Kowken** [comment]
> And this ? [GHelper.zip](https://github.com/seerge/g-helper/files/12243577/GHelper.zip)

Same as before, but with some sort of universal blinking at the start (I'm recording a video)

**Comment by seerge** [comment]
I don't really need a video :) if it doesn't work - it doesn't

I have reverted all my experiments back to last working state and committed them to github :) if you want - you can experiment with numbers,


Latest build is [GHelper.zip](https://github.com/seerge/g-helper/files/12243644/GHelper.zip)

**Comment by Kowken** [comment]
> I don't really need a video :) if it doesn't work - it doesn't
> 
> I have reverted all my experiments back to last working state and committed them to github :) if you want - you can experiment with numbers,
> 
> Latest build is [GHelper.zip](https://github.com/seerge/g-helper/files/12243644/GHelper.zip)

Okay I'm sorry I couldn't be of more assistance on this one. And thank you for helping out :)

**Comment by Kowken** [comment]
Oh and just so you know, the latest build's heatmap alt makes the m keys blink between red and green, while keeping the rog key led on even after changing lighting

**Comment by Kowken** [comment]
> Oh and just so you know, the latest build's heatmap alt makes the m keys blink between red and heatmap, while keeping the rog key led on even after changing lighting

(EDIT: The rog key sometimes lit up and goes off so there is no explaining this one)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/12243768/GHelper.zip)
and this ? i have shortened last payload only to 3 buttons (the one missing probably -arrow-keys)

**Comment by Constrat** [comment]
https://github.com/seerge/g-helper/issues/967#issuecomment-1662804567
This looks perfect. No strobing, all keys lighting up (Yes, ALL of them even the arrow keys) Top ROW is the correct color (same as all the others)

**Comment by seerge** [comment]
I did a small cleanup, and removed Heatmap Alt, now for Strix devices it will run it as only option (called just Heatmap)

Functionality should be same
[GHelper.zip](https://github.com/seerge/g-helper/files/12244058/GHelper.zip)

**Comment by Constrat** [comment]
STRIX devices should do it. Considering it's made of the G15, G17, SCAR15 and SCAR17 models which all share the same hardware

**Comment by Constrat** [comment]
@seerge This should be marked as completed

**Comment by seerge** [comment]
@Kowken does it work for you as well ?

**Comment by Kowken** [comment]
> @Kowken does it work for you as well ?

Sorry for the late reply. I have run into a major issue with my computer so I will test it tomorrow if that's okay with you.
Thank you for your comprehension and have a good day.

**Comment by Kowken** [comment]
Nevermind just tested it and everything is fine except the ROGkey light is still enabled and doesn't disappear after changing mode.
OpenRGB manages to control this LED at will so maybe this is the place to begin from.

**Comment by seerge** [comment]
@Kowken what do you understand under ROG key ? M4 or M5 key in M-row? it should be affected by all built-in modes (i.e. non-heatmap)

**Comment by seerge** [comment]
Marking as completed, as it seem to be ok now. Will include this changes in v104

**Comment by Kowken** [comment]
> @Kowken what do you understand under ROG key ? M4 or M5 key in M-row? it should be affected by all built-in modes (i.e. non-heatmap)
> 
> 

I meant the ROG Keystone Led (the red led you can see in my videos)

**Comment by seerge** [comment]
@Kowken well, it's probably one of those 176 per-key color settings that app sends to device :) it's quite difficult to figure out which one . So I have to leave it as is for now ;)

**Comment by Kowken** [comment]
> @Kowken well, it's probably one of those 176 per-key color settings that app sends to device :) it's quite difficult to figure out which one . So I have to leave it as is for now ;)

OpenRGB can control this peculiar light at will, do you want me to record it with WireShark/Device Monitoring Software so you can disable it at least or do you prefer to leave it like that ? In the former case, I can do that in about 3 hours. Otherwise nevermind :)

**Comment by Kowken** [comment]
In any case, is possible to also keep the old heatmap in following builds so people with ROG keystones don't run into this issue ? Thanks in advance for your answer.

**Comment by seerge** [comment]
@Kowken but old heatmap was broken for you and blinking? :)

**Comment by Kowken** [comment]
> @Kowken but old heatmap was broken for you and blinking? :) 

Old heatmap was only blinking on the non keyboard leds and the blinking was very slight so that is totally manageable. Everything else was working as expected.

**Comment by Kowken** [comment]
Alternatively, I can try to disable one of the 176 signals one by one and give you the results, so to spare you the trouble. You just have to tell me where to meddle in the source code and I'll be good to go.

**Comment by seerge** [comment]
@Kowken 
check this build, i just removed last color setting in a list, mb keystone is literally that one 
[GHelper.zip](https://github.com/seerge/g-helper/files/12253351/GHelper.zip)

**Comment by Constrat** [comment]
Just a heads up: OpenRGB has issues with the Strix / Scar models, because they only trained the 15inch one (so for @Kowken ) shouldn't be a problem.

We are in they making of fixing the 15/17 inch issues on OpenRGB, so could I ask @Kowken to please give me this?

You hardware ID? 
![image](https://github.com/seerge/g-helper/assets/56174894/0f130ba9-5f9a-4e55-8fd1-494ab55ad0e1)
(I'm very sorry, this has pretty much nothing to do with this but it would be a great help and as of now you're the only that I saw has a SCAR15)

**Comment by Kowken** [comment]
> Just a heads up: OpenRGB has issues with the Strix / Scar models, because they only trained the 15inch one (so for @Kowken ) shouldn't be a problem.
> 
> 
> 
> We are in they making of fixing the 15/17 inch issues on OpenRGB, so could I ask @Kowken to please give me this?
> 
> 
> 
> You hardware ID? 
> 
> ![image](https://github.com/seerge/g-helper/assets/56174894/0f130ba9-5f9a-4e55-8fd1-494ab55ad0e1)
> 
> (I'm very sorry, this has pretty much nothing to do with this but it would be a great help and as of now you're the only that I saw has a SCAR15)

Please do not apologize: you're the one helping me here in the long run !

I will send and test everything you need once my clean install is done (in about an hour I think) so please bear with me until then :)

**Comment by Kowken** [comment]
> @Kowken 
> 
> check this build, i just removed last color setting in a list, mb keystone is literally that one 
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/12253351/GHelper.zip)
> 
> 
> 
> If not - you may try to unset some colors at last package being sent at 
> 
> https://github.com/seerge/g-helper/blob/31ebbc3d18ff9981d08518e5eee8b9d82661c296/app/AsusUSB.cs#L511C20-L511C20
> 
> 
> 
> OpenRGB tips that KSTN (keystone?) may be 175 (or somewhere close) https://gitlab.com/CalcProgrammer1/OpenRGB/-/blob/master/Controllers/AsusAuraCoreController/AsusAuraCoreLaptopController.cpp 

Ok I will test, report and try things on my own once my clean install is done.

May I ask you for help if I somehow need it for this task ?

**Comment by Kowken** [comment]
> @Kowken 
> 
> check this build, i just removed last color setting in a list, mb keystone is literally that one 
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/12253351/GHelper.zip)
> 
> 
> 
> If not - you may try to unset some colors at last package being sent at 
> 
> https://github.com/seerge/g-helper/blob/31ebbc3d18ff9981d08518e5eee8b9d82661c296/app/AsusUSB.cs#L511C20-L511C20
> 
> 
> 
> OpenRGB tips that KSTN (keystone?) may be 175 (or somewhere close) https://gitlab.com/CalcProgrammer1/OpenRGB/-/blob/master/Controllers/AsusAuraCoreController/AsusAuraCoreLaptopController.cpp 

Hi again, sorry for the late reply.
The build you sent me did not resolve the issue. Is this the one where you disabled the setting 175 ?

**Comment by seerge** [comment]
@Kowken yes, in that build i just shortened last color on 1 :)

**Comment by Kowken** [comment]
> @Kowken yes, in that build i just shortened last color on 1 :) 

I will ask for help to OpenRGB devs regarding the signal that is supposed to go to the Keystone LED.
I also have csv files from ROG Live Service which may be useful for the mapping of each key backlight. Would you like to have it or is it not as useful as I thought it would be ?

**Comment by Kowken** [comment]
> > @Kowken yes, in that build i just shortened last color on 1 :) 
> 
> I will ask for help to OpenRGB devs regarding the signal that is supposed to go to the Keystone LED.
> I also have csv files from ROG Live Service which may be useful for the mapping of each key backlight. Would you like to have it or is it not as useful as I thought it would be ?
> 
> Also now that I compared it to my keyboard layout, I'm pretty confident that 175 is linked to Keystone (the order is the same than my keyboard except a few oddities) but if that did not work then maybe there is an offset (so if we disable the one before and after, we'll get to something).

Finally, I'm a bit lost regarding where I can change the code to fiddle with keys in the file you linked (I'm sorry but I'm not familiar with the source code of this project)

**Comment by Kowken** [comment]
Sorry for the late reply, here are the config files for Aura Keyboards (extracted from ROG live services).
OpenRGB uses them so I thought it could help you as well.
Have a nice day.

[DeviceContent.zip](https://github.com/seerge/g-helper/files/12279811/DeviceContent.zip)
