### ISSUE TITLE
Asus Zenbook Pro 14 OLED Support

### ISSUE THREAD

**Issue by smasri09** [seerge/g-helper#968]
Hello, this new laptop released, and it seems a few features are missing from g-helper: fan control, dGPU/iGPU switch, and gpu overclock. Control system should be the same as other asus laptops, any possibility of adding this laptop in? Thanks for the good work on this app!

**Comment by seerge** [comment]
@smasri09 does Zenbook Pro Oled support custom fan curves and turning off dGPU in a first place ?

**Comment by seerge** [comment]
Closing as this seem to be abandoned by the Issue starter
