### ISSUE TITLE
Ability to adjust a frequency for a CPU

### ISSUE THREAD

**Issue by Acnologiak** [seerge/g-helper#969]
Hello everyone

I propose to add the ability to adjust frequencies for P and E cores.
As for me, this is the very interesting feature because windows or some program can use not so a lot of resources of CPU, but there will be high power consumption. CPU can keep maximum frequency for undemanding tasks. For example, I can set the maximum frequency for P-cores to 3.4 GHz(why not).

I saw that these values can be changed through the register (but there is one bug, if you change the frequencies on P cores, then the frequencies on E are changed and vice versa + when setting the frequency on E cores, it is equal to ~75% of the set value).
I found this opportunity through QuickCPU because I couldn't change the frequency on the P cores through the windows power settings.

Also, it will be nice to see the ability to adjust the maximum temperature of the processor (as on a GPU).

I have some ideas related to E cores that work incorrect (power plan options) with Windows 11, but this is not so important.

**Comment by seerge** [comment]
@Acnologiak how do you expect to adjust that if it's not working neither via power plan nor via registry as you say? :)

G-Helper uses only endpoints that asus has exposed for armoury crate, and there is nothing like that there.

**Comment by Acnologiak** [comment]
<img width="841" alt="image" src="https://github.com/seerge/g-helper/assets/31826517/e4907f71-1086-43e0-9f72-5e62aff2fb1d">
Here I can adjust frequency only for E-cores.
<img width="883" alt="image" src="https://github.com/seerge/g-helper/assets/31826517/35f37706-274f-477b-9479-502758611bb6">
But through QuickCPU I can do it for both types.

**Comment by seerge** [comment]
@Acnologiak ok :) but it's a proprietary software. Why don't you just use QuickCPU then? :)

**Comment by Acnologiak** [comment]
If I want to do that, I should to open another app because this app doesn't change power plans, but armory crate does (I don't want to go back because the laptop doesn't go to sleep with this app).

**Comment by Acnologiak** [comment]
> @Acnologiak ok :) but it's a proprietary software. Why don't you just use QuickCPU then? :)
> 
> P.S. I'm trying to understand why exactly this specific intel-only feature needs to be added to the app that intended to replace Armoury Crate (and not Intel Tuning utility)

H Intel CPUs in XTU do not support this feature but windows 11 can do it (if honest I do not know why Intel blocked it from one side)

**Comment by seerge** [comment]
@Acnologiak you can set custom power plans with g-helper as well
https://github.com/seerge/g-helper#custom-windows-power-plans-with-each-mode

**Comment by Acnologiak** [comment]
> @Acnologiak you can set custom power plans with g-helper as well https://github.com/seerge/g-helper#custom-windows-power-plans-with-each-mode

Yes, but my device won't toggle windows settings. It is necessary to do everything manually.
<img width="839" alt="image" src="https://github.com/seerge/g-helper/assets/31826517/579c3977-eb72-4396-addf-361e34738be3">
I am talking about these, since the frequencies are set in the register.

**Comment by seerge** [comment]
@Acnologiak g-helper can toggle power plans, exactly same as armoury does. You just need to set IDs in a config, as explained in a readme.

**Comment by Acnologiak** [comment]
Ok, thank. Donation from me)

I am here to offer the useful tool and whether to add it or not is up to you (there are no popular programs that can offer this option in a few clicks for Intel H series only for HX)
