### ISSUE TITLE
Battery Charge Limit doesn't work on 0.103.0 update on TUF Gaming 2021 FX506HCB

### ISSUE THREAD

**Issue by komsboymore** [seerge/g-helper#971]
Hello,
Hope to be good, and thanks for the incredible app that made me free of ASUS shit!

I guess that there is a bug on new release (0.103.0) on limiting battery charging feature. It doesn't work :D lol. My device got full charge (100%) after upgrading to this release.

Thanks agin

**Comment by seerge** [comment]
> ## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect the time of the developer. Thanks.
