### ISSUE TITLE
Incorrect mapping of brightness hotkeys on TUF F15

### ISSUE THREAD

**Issue by thepriyamkalra** [seerge/g-helper#975]
**Describe the bug**
So I retested this bug on the last v0.104 build linked in #960, and with both FnLock on and off,
Ctrl+M1 (FnF2) still increases the brightness & Ctrl+M2 (FnF3) still decreases the brightness.

**Expected behavior**
The keys should be the other way around, just like Shift+M1 reduces backlight brightness and Shift+M2 increases it.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/12243591/log.txt)

**Desktop:**
 - OS: Windows 11
 - Laptop model: TUF F15 FX506LU

**Asus software**
None

**Additional context**
Since my current log is pretty large and spans across multiple builds, let me know if you need a fresh one with only Ctrl+M1/M2 inputs.

**Comment by seerge** [comment]
@thepriyamkalra so all buttons work , just swapped? I just don't know if BIOS commands are swapped only on your device , your model or whole range of devices (i.e. FX506). Any ideas ?

**Comment by thepriyamkalra** [comment]
@seerge thats right, they are just swapped. I dont really know if this affects any other users or devices.
One possible workaround would be to make it possible to configure the Ctrl+M1/M2 and Shift+M1/M2 hotkeys via the app or the config, and then anyone affected could just swap them themselves.

**Comment by DantShanoff** [comment]
TUF F15 FX506HM, Windows 11. Works fine.

**Comment by seerge** [comment]
So it's clearly not a series then. Is it one bugged model ? Or just single device? :)

**Comment by kuonji-arisu** [comment]
TUF 15 2022  I7 3060 (FX507ZM)
Ctrl + F1 / F2 Works fine for me.


I didn't even know this feature existed. Is Ctrl + F1 controlling the brightness? Is it a hardware feature or provided by the application?

**Comment by seerge** [comment]
@kuonji-arisu cause some TUF models support "navite" brightness controls, some - don't - so purely for TUF i run both - native brightness command + i manually set +10% using windows API . So you get 20%. I can exclude your model from this "addition"

**Comment by seerge** [comment]
@thepriyamkalra @kuonji-arisu 

This build should have correct bindings for @thepriyamkalra 
And do only 1 brightness adjustment (instead of 2) for @kuonji-arisu 

[GHelper.zip](https://github.com/seerge/g-helper/files/12250437/GHelper.zip)

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/12254398/GHelper.zip)

**Comment by kuonji-arisu** [comment]
> 

Thank you! Now, this build will only trigger once when the key is pressed.
