### ISSUE TITLE
[GA402RJ] Uncorrected clock mode for AniMe Matrix

### ISSUE THREAD

**Issue by DvaMishkiLapa** [seerge/g-helper#979]
First of all, I want to sincerely thank the author for developing this app. It's beautiful, I can imagine how much effort was put into this solution, it's beyond praise. I finally found an analog of Asus software :D

## My problem

When AniMe Matrix Clock mode is selected, the clock flashes approximately every second, rather than just being displayed.

[log.txt](https://github.com/seerge/g-helper/files/12248831/log.txt)

https://github.com/seerge/g-helper/assets/18528109/cd5b3fe0-410e-47c5-998c-b591955805bb

## My steps
1. Starting G-helper;
2. Select the option to disable all Asus services;
3. Reboot;
4. Start G-helper;
5. Anime Matrix to select:
    - Brightness: any (I choose `Bright`);
    - Mode: `Clock`.

## My specs
 - OS:
   - Windows 11 Home 22H2;
   - OS buil: 22621.1992;
   - Windows Feature Experience Pack 1000.22644.1000.0.
 - Laptop model: [ROG Zephyrus G14 (2022)](https://rog.asus.com/de/laptops/rog-zephyrus/rog-zephyrus-g14-2022-series/) GA402RJ.

### Armoury Crate Diagnostic result
```
Armoury Crate UWP App           5.6.8.0
ROG Live Service                2.1.4.0
Aura Service (Lighting Service) 3.07.17
Armoury Crate service           5.6.8
Aura Wallpaper Service          Not installed
Aura SDK                        3.04.32
ASUS Aac_NBDT HAL               2.5.30.0
ENE_External_Device_HAL         1.0.12.7
```

### Other Asus programs
- G-helper ver: 0.103.0
- MyASUS installed, not launch and autostart;
- G-helper soft update dialog:
    <img width="474" alt="Screenshot 2023-08-03 103345" src="https://github.com/seerge/g-helper/assets/18528109/5eaa37fa-32a6-43c0-b5c2-983c7d589f61">

## Other terms and conditions
I recently installed Windows 11 from scratch, using only the drivers and software put out by Asus and then updating it through Asus services. Using G-helper, I didn't uninstall AC so that I could manage the features not available in G-helper in case of emergency.

I use the G-helper function to stop Asus services from interfering with me.

Other AniMe Matrix functions work without problems, just like in AC.

**Comment by seerge** [comment]
@DvaMishkiLapa you have lots of asus stuff running, that is interfering. In particular ``Aura Service (Lighting Service) 3.07.17`` just sets anime-matrix every second, overriding clock. Stop it - and it will be ok.
