### ISSUE TITLE
remember the last GPU mode

### ISSUE THREAD

**Issue by HamzaYslmn** [seerge/g-helper#98]
I want the application to remember the last GPU mode used. It can be tedious to change the GPU mode every time I turn on my computer. I usually use the iGPU mode to keep my computer cooler by preventing the fans from running.

**Comment by seerge** [comment]
App (actually asus bios) remembers GPU mode from the very first version

**Comment by HamzaYslmn** [comment]
I shut down the computer in igpu mode. But it switches back to balanced mode at boot. İDK

**Comment by seerge** [comment]
What's your laptop model ?

**Comment by HamzaYslmn** [comment]
Zephyrus G15 (2022) Bios 311

**Comment by seerge** [comment]
If it's indeed so - then your bios turns on dGPU back by some reason every time laptop boots. Do you also have asus services running ? Armory / other things?

You can set Optimized mode, it will force app to set Eco every time laptop boots and is on battery.

**Comment by HamzaYslmn** [comment]
I delete the AC app (with uninstaller tool), ı run the bat file, stop all asus bloatwares.

optimized mode works perfectly, but ı just want plugged in igpu mode at start.

**Comment by seerge** [comment]
Well, as explained, dGPU state is stored in bios.  And based on what i see - it works for others :)  

Enforcing GPU switch off every run will break logic of other things, so you can either use optimized mode, or try to investigate (what in your specific situation causes bios to set dGPU back on on every reboot?)

**Comment by HamzaYslmn** [comment]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/78810304/226171362-210be73e-e18f-4abd-a3b9-e3f6e08f9f7b.png">

if you didn't understand my request correctly. Let me explain it again with pictures.

When I shut down my computer in Eco mode, I want it to turn on in Eco mode as well. If I shut it down in standard mode, then it should turn on in standard mode.

Currently, when I shut down my computer in Eco mode, it turns on in standard mode. My request is to fix this so that the computer automatically returns to the mode it was in when it was shut down.

Thank you for your help, though. This is a great application, thank you anyway.

<img width="322" alt="image" src="https://user-images.githubusercontent.com/78810304/226171369-f7c10f01-496b-4e0e-9f7e-03e0f0902d2d.png">

**Comment by HamzaYslmn** [comment]
`public int InitGPUMode()
        {

            int eco = Program.wmi.DeviceGet(ASUSWmi.GPUEco);
            int mux = Program.wmi.DeviceGet(ASUSWmi.GPUMux);

            int GpuMode;

            if (mux == 0)
                GpuMode = ASUSWmi.GPUModeUltimate;
            else
            {
                GpuMode = Program.config.getConfig("gpu_mode");
                UltimateUI(mux == 1);
            }

            Program.config.setConfig("gpu_mode", GpuMode);

            ButtonEnabled(buttonOptimized, true);
            ButtonEnabled(buttonEco, true);
            ButtonEnabled(buttonStandard, true);
            ButtonEnabled(buttonUltimate, true);

            VisualiseGPUMode(GpuMode);

            return GpuMode;

        }`

**Comment by HamzaYslmn** [comment]
I apologize if I was rude, it just seemed to me that we were not talking about the same things.

Because when I was using the AC app, it started in standard mode and automatically switched back to Eco immediately. I was just looking for the same feature. 

Thanks anyway.
