### ISSUE TITLE
tuf f15 2022 sometimes charge when should not

### ISSUE THREAD

**Issue by d00lar** [seerge/g-helper#980]
**Describe the bug**
in my tuf f15 2022 even if i have battery charging limit set - it still charge
please see screenshot
![image](https://github.com/seerge/g-helper/assets/22784835/f138051b-6af2-4294-b560-7ada4c50cdd9)

it was charging and battery was 99% when making screenshot and still was charging
i had to slide down limit a bit and then it stopped because of new set limit probably

before that i was restarting pc / disconnecting dock / changing dock / changing monitor to new one couple times so there must be somme issue  connected with this?

**App Logs**
log from tooday

> 03.08.2023 09:18:47: WMI event 192
03.08.2023 09:18:49: WMI event 192
03.08.2023 09:18:49: WMI event 123
03.08.2023 09:18:49: WMI event 192
03.08.2023 09:18:49: WMI event 192
03.08.2023 09:18:49: Display configuration changed.
03.08.2023 09:18:50: WMI event 192
03.08.2023 09:18:51: Display configuration changed.
03.08.2023 09:18:52: WMI event 192
03.08.2023 09:18:52: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:18:52: WMI event 192
03.08.2023 09:18:52: WMI event 192
03.08.2023 09:18:52: WMI event 192
03.08.2023 09:18:52: WMI event 192
03.08.2023 09:18:52: WMI event 192
03.08.2023 09:18:52: WMI event 192
03.08.2023 09:18:52: WMI event 192
03.08.2023 09:18:54: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:18:54: WMI event 192
03.08.2023 09:18:54: WMI event 192
03.08.2023 09:18:54: WMI event 192
03.08.2023 09:18:54: WMI event 192
03.08.2023 09:18:54: WMI event 192
03.08.2023 09:18:55: WMI event 192
03.08.2023 09:19:01: WMI event 192
03.08.2023 09:19:02: WMI event 192
03.08.2023 09:19:02: Display configuration changed.
03.08.2023 09:19:02: Display configuration changed.
03.08.2023 09:19:02: Display configuration changed.
03.08.2023 09:19:03: WMI event 192
03.08.2023 09:19:03: WMI event 192
03.08.2023 09:19:03: WMI event 192
03.08.2023 09:19:08: WMI event 192
03.08.2023 09:19:08: WMI event 192
03.08.2023 09:19:08: WMI event 192
03.08.2023 09:19:08: WMI event 88
03.08.2023 09:19:08: WMI event 123
03.08.2023 09:19:09: Display configuration changed.
03.08.2023 09:19:09: Display configuration changed.
03.08.2023 09:19:11: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:19:13: WMI event 192
03.08.2023 09:19:14: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:19:14: WMI event 192
03.08.2023 09:19:14: WMI event 192
03.08.2023 09:19:14: WMI event 123
03.08.2023 09:19:14: WMI event 192
03.08.2023 09:19:14: WMI event 192
03.08.2023 09:19:14: WMI event 192
03.08.2023 09:19:15: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:19:15: WMI event 192
03.08.2023 09:19:16: WMI event 192
03.08.2023 09:19:16: WMI event 192
03.08.2023 09:20:04: WMI event 192
03.08.2023 09:20:04: WMI event 192
03.08.2023 09:20:04: Display configuration changed.
03.08.2023 09:20:04: WMI event 192
03.08.2023 09:20:04: WMI event 192
03.08.2023 09:20:06: WMI event 192
03.08.2023 09:20:06: WMI event 192
03.08.2023 09:20:06: WMI event 192
03.08.2023 09:20:06: WMI event 192
03.08.2023 09:20:06: WMI event 192
03.08.2023 09:20:06: WMI event 192
03.08.2023 09:20:06: WMI event 192
03.08.2023 09:20:06: WMI event 192
03.08.2023 09:20:06: WMI event 192
03.08.2023 09:20:06: WMI event 192
03.08.2023 09:20:07: Display configuration changed.
03.08.2023 09:20:07: WMI event 192
03.08.2023 09:20:07: WMI event 192
03.08.2023 09:20:08: WMI event 192
03.08.2023 09:20:09: Display configuration changed.
03.08.2023 09:20:13: WMI event 192
03.08.2023 09:20:14: WMI event 192
03.08.2023 09:20:14: WMI event 192
03.08.2023 09:20:14: Display configuration changed.
03.08.2023 09:20:16: WMI event 192
03.08.2023 09:20:16: WMI event 192
03.08.2023 09:20:17: Display configuration changed.
03.08.2023 09:20:17: WMI event 192
03.08.2023 09:20:17: WMI event 192
03.08.2023 09:20:18: WMI event 192
03.08.2023 09:20:19: Display configuration changed.
03.08.2023 09:20:22: WMI event 192
03.08.2023 09:20:24: WMI event 192
03.08.2023 09:20:24: WMI event 192
03.08.2023 09:20:25: Display configuration changed.
03.08.2023 09:20:25: WMI event 192
03.08.2023 09:20:25: WMI event 192
03.08.2023 09:20:27: WMI event 192
03.08.2023 09:20:27: Display configuration changed.
03.08.2023 09:20:27: WMI event 192
03.08.2023 09:20:27: WMI event 192
03.08.2023 09:20:28: WMI event 192
03.08.2023 09:20:29: Display configuration changed.
03.08.2023 09:20:33: WMI event 192
03.08.2023 09:20:35: Display configuration changed.
03.08.2023 09:20:35: WMI event 192
03.08.2023 09:20:35: WMI event 192
03.08.2023 09:20:36: WMI event 192
03.08.2023 09:20:37: Display configuration changed.
03.08.2023 09:20:37: WMI event 192
03.08.2023 09:20:37: WMI event 192
03.08.2023 09:20:38: WMI event 192
03.08.2023 09:20:39: Display configuration changed.
03.08.2023 09:20:42: WMI event 192
03.08.2023 09:20:42: WMI event 192
03.08.2023 09:23:24: WMI event 192
03.08.2023 09:23:34: WMI event 88
03.08.2023 09:23:34: WMI event 123
03.08.2023 09:23:35: Display configuration changed.
03.08.2023 09:23:37: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:23:44: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:23:46: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:23:47: Display configuration changed.
03.08.2023 09:24:03: Display configuration changed.
03.08.2023 09:24:12: Display configuration changed.
03.08.2023 09:25:24: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:26:09: Display configuration changed.
03.08.2023 09:26:26: Display configuration changed.
03.08.2023 09:26:44: Display configuration changed.
03.08.2023 09:26:53: Display configuration changed.
03.08.2023 09:27:45: Display configuration changed.
03.08.2023 09:27:48: Display configuration changed.
03.08.2023 09:36:27: ------------
03.08.2023 09:36:27: App launched: ASUS TUF Dash F15 FX517ZM_FX517ZM :0.103.0.0pl-PL.
03.08.2023 09:36:28: NVIDIA GeForce RTX 3060 Laptop GPU
03.08.2023 09:36:29: CPU: -1 - 12th Gen Intel(R) Core(TM) i7-12650H - Intel64 Family 6 Model 154 Stepping 3
03.08.2023 09:36:30: AutoSetting for Online
03.08.2023 09:36:30: Optimization service is running
03.08.2023 09:36:30: Mode = 2 : OK
03.08.2023 09:36:30: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
03.08.2023 09:36:30: SET GPU CLOCKS: -250, -250
03.08.2023 09:36:31: FanCPU = 14-3C-41-42-46-4F-59-62-00-00-00-00-05-12-24-2C : OK
03.08.2023 09:36:31: FanGPU = 14-3C-43-46-43-4E-57-62-00-00-00-03-00-0F-26-2D : OK
03.08.2023 09:36:31: Eco flag : 0
03.08.2023 09:36:31: Mux flag : 1
03.08.2023 09:36:31: MSI G272QPF:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY1
03.08.2023 09:36:31: DELL U2412M:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY2
03.08.2023 09:36:31: BatteryLimit = 60 : OK
03.08.2023 09:36:31: BatteryLimit = 60 : OK
03.08.2023 09:36:31: TUF Brightness = 128 : OK
03.08.2023 09:36:31: Monitor Power On
03.08.2023 09:36:31: TUF_KB = 445 : OK
03.08.2023 09:36:31: TUF RGB = B4-00-FF-FF-FF-EB-00-00-00-00-00-00 : 0
03.08.2023 09:36:32: PowerLimit A0 = 12 : OK
03.08.2023 09:36:32: PowerLimit A3 = 12 : OK
03.08.2023 09:36:32: PowerLimit C0 = 5 : OK
03.08.2023 09:36:32: PowerLimit C2 = 75 : OK
03.08.2023 09:36:56: Display configuration changed.
03.08.2023 09:37:03: Display configuration changed.
03.08.2023 09:37:07: Display configuration changed.
03.08.2023 09:37:12: Display configuration changed.
03.08.2023 09:37:17: Display configuration changed.
03.08.2023 09:37:22: Display configuration changed.
03.08.2023 09:37:26: Display configuration changed.
03.08.2023 09:38:13: Display configuration changed.
03.08.2023 09:38:46: Monitor Power Off
03.08.2023 09:38:46: TUF Brightness = 128 : OK
03.08.2023 09:39:37: Monitor Power On
03.08.2023 09:39:37: AutoSetting for Online
03.08.2023 09:39:37: Optimization service is running
03.08.2023 09:39:37: Mode = 2 : OK
03.08.2023 09:39:37: GET GPU CLOCKS: -250, -250
03.08.2023 09:39:37: FanCPU = 14-3C-41-42-46-4F-59-62-00-00-00-00-05-12-24-2C : OK
03.08.2023 09:39:37: FanGPU = 14-3C-43-46-43-4E-57-62-00-00-00-03-00-0F-26-2D : OK
03.08.2023 09:39:37: Eco flag : 0
03.08.2023 09:39:37: Mux flag : 1
03.08.2023 09:39:37: NOVATEK:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY1
03.08.2023 09:39:37: DELL U2412M:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY2
03.08.2023 09:39:37: BatteryLimit = 60 : OK
03.08.2023 09:39:37: TUF Brightness = 128 : OK
03.08.2023 09:39:37: TUF_KB = 445 : OK
03.08.2023 09:39:37: TUF RGB = B4-00-FF-FF-FF-EB-00-00-00-00-00-00 : 0
03.08.2023 09:39:38: PowerLimit A0 = 12 : OK
03.08.2023 09:39:38: PowerLimit A3 = 12 : OK
03.08.2023 09:39:39: PowerLimit C0 = 5 : OK
03.08.2023 09:39:39: PowerLimit C2 = 75 : OK
03.08.2023 09:39:40: Display configuration changed.
03.08.2023 09:39:45: Display configuration changed.
03.08.2023 09:39:50: Display configuration changed.
03.08.2023 09:39:55: Display configuration changed.
03.08.2023 09:40:00: Display configuration changed.
03.08.2023 09:40:04: Display configuration changed.
03.08.2023 09:40:35: Monitor Power Off
03.08.2023 09:40:35: TUF Brightness = 128 : OK
03.08.2023 09:40:36: Display configuration changed.
03.08.2023 09:40:46: Display configuration changed.
03.08.2023 09:41:21: Display configuration changed.
03.08.2023 09:41:31: Monitor Power On
03.08.2023 09:41:31: AutoSetting for Online
03.08.2023 09:41:31: Optimization service is running
03.08.2023 09:41:31: Mode = 2 : OK
03.08.2023 09:41:32: GET GPU CLOCKS: -250, -250
03.08.2023 09:41:32: FanCPU = 14-3C-41-42-46-4F-59-62-00-00-00-00-05-12-24-2C : OK
03.08.2023 09:41:32: FanGPU = 14-3C-43-46-43-4E-57-62-00-00-00-03-00-0F-26-2D : OK
03.08.2023 09:41:32: Eco flag : 0
03.08.2023 09:41:32: Mux flag : 1
03.08.2023 09:41:32: DELL U2412M:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY1
03.08.2023 09:41:32: MSI G272QPF:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY2
03.08.2023 09:41:32: BatteryLimit = 60 : OK
03.08.2023 09:41:32: TUF RGB = B4-00-FF-FF-FF-EB-00-00-00-00-00-00 : 0
03.08.2023 09:41:32: TUF Brightness = 128 : OK
03.08.2023 09:41:32: TUF_KB = 445 : OK
03.08.2023 09:41:33: PowerLimit A0 = 12 : OK
03.08.2023 09:41:33: PowerLimit A3 = 12 : OK
03.08.2023 09:41:33: PowerLimit C0 = 5 : OK
03.08.2023 09:41:33: PowerLimit C2 = 75 : OK
03.08.2023 09:42:01: Monitor Power Off
03.08.2023 09:42:01: TUF Brightness = 128 : OK
03.08.2023 09:43:23: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:43:30: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:43:31: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:43:41: Monitor Power On
03.08.2023 09:43:41: AutoSetting for Online
03.08.2023 09:43:41: Optimization service is running
03.08.2023 09:43:41: Mode = 2 : OK
03.08.2023 09:43:41: GET GPU CLOCKS: -250, -250
03.08.2023 09:43:41: FanCPU = 14-3C-41-42-46-4F-59-62-00-00-00-00-05-12-24-2C : OK
03.08.2023 09:43:41: FanGPU = 14-3C-43-46-43-4E-57-62-00-00-00-03-00-0F-26-2D : OK
03.08.2023 09:43:41: Eco flag : 0
03.08.2023 09:43:41: Mux flag : 1
03.08.2023 09:43:41: DELL U2412M:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY1
03.08.2023 09:43:41: MSI G272QPF:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY2
03.08.2023 09:43:41: BatteryLimit = 60 : OK
03.08.2023 09:43:41: TUF_KB = 445 : OK
03.08.2023 09:43:41: TUF RGB = B4-00-FF-FF-FF-EB-00-00-00-00-00-00 : 0
03.08.2023 09:43:41: TUF Brightness = 128 : OK
03.08.2023 09:43:42: PowerLimit A0 = 12 : OK
03.08.2023 09:43:42: PowerLimit A3 = 12 : OK
03.08.2023 09:43:43: PowerLimit C0 = 5 : OK
03.08.2023 09:43:43: PowerLimit C2 = 75 : OK
03.08.2023 09:44:06: Session:SessionUnlock
03.08.2023 09:44:06: DELL U2412M:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY1
03.08.2023 09:44:06: MSI G272QPF:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY2
03.08.2023 09:44:33: Display configuration changed.
03.08.2023 09:44:34: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:47:51: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:50:28: WMI event 192
03.08.2023 09:50:30: WMI event 192
03.08.2023 09:50:30: Display configuration changed.
03.08.2023 09:50:32: WMI event 192
03.08.2023 09:50:46: Display configuration changed.
03.08.2023 09:50:56: WMI event 192
03.08.2023 09:50:57: Display configuration changed.
03.08.2023 09:51:44: Display configuration changed.
03.08.2023 09:51:44: Display configuration changed.
03.08.2023 09:57:57: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:58:09: HID Device Event: Checking for new ASUS Mice
03.08.2023 09:59:25: Display configuration changed.
03.08.2023 10:01:03: HID Device Event: Checking for new ASUS Mice
03.08.2023 10:02:08: ------------
03.08.2023 10:02:08: App launched: ASUS TUF Dash F15 FX517ZM_FX517ZM :0.103.0.0pl-PL.
03.08.2023 10:02:09: NVIDIA GeForce RTX 3060 Laptop GPU
03.08.2023 10:02:10: CPU: -1 - 12th Gen Intel(R) Core(TM) i7-12650H - Intel64 Family 6 Model 154 Stepping 3
03.08.2023 10:02:10: AutoSetting for Online
03.08.2023 10:02:10: Optimization service is running
03.08.2023 10:02:10: Mode = 2 : OK
03.08.2023 10:02:10: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
03.08.2023 10:02:10: SET GPU CLOCKS: -250, -250
03.08.2023 10:02:11: FanCPU = 14-3C-41-42-46-4F-59-62-00-00-00-00-05-12-24-2C : OK
03.08.2023 10:02:11: FanGPU = 14-3C-43-46-43-4E-57-62-00-00-00-03-00-0F-26-2D : OK
03.08.2023 10:02:11: Eco flag : 0
03.08.2023 10:02:11: Mux flag : 1
03.08.2023 10:02:11: NOVATEK:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY1
03.08.2023 10:02:11: BatteryLimit = 60 : OK
03.08.2023 10:02:11: BatteryLimit = 60 : OK
03.08.2023 10:02:11: TUF Brightness = 128 : OK
03.08.2023 10:02:11: Monitor Power On
03.08.2023 10:02:11: TUF_KB = 445 : OK
03.08.2023 10:02:11: TUF RGB = B4-00-FF-FF-FF-EB-00-00-00-00-00-00 : 0
03.08.2023 10:02:12: PowerLimit A0 = 12 : OK
03.08.2023 10:02:12: PowerLimit A3 = 12 : OK
03.08.2023 10:02:13: PowerLimit C0 = 5 : OK
03.08.2023 10:02:13: PowerLimit C2 = 75 : OK
03.08.2023 10:02:14: Session:SessionUnlock
03.08.2023 10:02:14: NOVATEK:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY1
03.08.2023 10:02:41: Display configuration changed.
03.08.2023 10:02:52: Display configuration changed.
03.08.2023 10:04:04: ------------
03.08.2023 10:04:04: App launched: ASUS TUF Dash F15 FX517ZM_FX517ZM :0.103.0.0pl-PL.
03.08.2023 10:04:04: NVIDIA GeForce RTX 3060 Laptop GPU
03.08.2023 10:04:06: CPU: -1 - 12th Gen Intel(R) Core(TM) i7-12650H - Intel64 Family 6 Model 154 Stepping 3
03.08.2023 10:04:06: AutoSetting for Online
03.08.2023 10:04:06: Optimization service is running
03.08.2023 10:04:06: Mode = 2 : OK
03.08.2023 10:04:06: GET GPU CLOCKS: 0, 0
03.08.2023 10:04:06: SET GPU CLOCKS: -250, -250
03.08.2023 10:04:06: FanCPU = 14-3C-41-42-46-4F-59-62-00-00-00-00-05-12-24-2C : OK
03.08.2023 10:04:06: FanGPU = 14-3C-43-46-43-4E-57-62-00-00-00-03-00-0F-26-2D : OK
03.08.2023 10:04:06: Eco flag : 0
03.08.2023 10:04:06: Mux flag : 1
03.08.2023 10:04:06: MSI G272QPF:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY1
03.08.2023 10:04:06: BatteryLimit = 60 : OK
03.08.2023 10:04:06: BatteryLimit = 60 : OK
03.08.2023 10:04:06: TUF Brightness = 128 : OK
03.08.2023 10:04:06: Monitor Power On
03.08.2023 10:04:06: TUF RGB = B4-00-FF-FF-FF-EB-00-00-00-00-00-00 : 0
03.08.2023 10:04:07: TUF_KB = 445 : OK
03.08.2023 10:04:07: PowerLimit A0 = 12 : OK
03.08.2023 10:04:07: PowerLimit A3 = 12 : OK
03.08.2023 10:04:09: PowerLimit C0 = 5 : OK
03.08.2023 10:04:09: PowerLimit C2 = 75 : OK
03.08.2023 10:04:10: Session:SessionUnlock
03.08.2023 10:04:10: MSI G272QPF:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY1
03.08.2023 10:05:16: ------------
03.08.2023 10:05:16: App launched: ASUS TUF Dash F15 FX517ZM_FX517ZM :0.103.0.0pl-PL.
03.08.2023 10:05:16: NVIDIA GeForce RTX 3060 Laptop GPU
03.08.2023 10:05:17: CPU: -1 - 12th Gen Intel(R) Core(TM) i7-12650H - Intel64 Family 6 Model 154 Stepping 3
03.08.2023 10:05:17: AutoSetting for Online
03.08.2023 10:05:17: Optimization service is running
03.08.2023 10:05:17: Mode = 2 : OK
03.08.2023 10:05:17: GET GPU CLOCKS: 0, 0
03.08.2023 10:05:17: SET GPU CLOCKS: -250, -250
03.08.2023 10:05:17: FanCPU = 14-3C-41-42-46-4F-59-62-00-00-00-00-05-12-24-2C : OK
03.08.2023 10:05:17: FanGPU = 14-3C-43-46-43-4E-57-62-00-00-00-03-00-0F-26-2D : OK
03.08.2023 10:05:17: Eco flag : 0
03.08.2023 10:05:17: Mux flag : 1
03.08.2023 10:05:17: MSI G272QPF:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY1
03.08.2023 10:05:17: BatteryLimit = 60 : OK
03.08.2023 10:05:17: BatteryLimit = 60 : OK
03.08.2023 10:05:17: TUF Brightness = 128 : OK
03.08.2023 10:05:17: Monitor Power On
03.08.2023 10:05:17: TUF_KB = 445 : OK
03.08.2023 10:05:17: TUF RGB = B4-00-FF-FF-FF-EB-00-00-00-00-00-00 : 0
03.08.2023 10:05:18: PowerLimit A0 = 12 : OK
03.08.2023 10:05:18: PowerLimit A3 = 12 : OK
03.08.2023 10:05:19: PowerLimit C0 = 5 : OK
03.08.2023 10:05:19: PowerLimit C2 = 75 : OK
03.08.2023 10:05:57: Display configuration changed.
03.08.2023 10:07:25: ------------
03.08.2023 10:07:25: App launched: ASUS TUF Dash F15 FX517ZM_FX517ZM :0.103.0.0pl-PL.
03.08.2023 10:07:26: NVIDIA GeForce RTX 3060 Laptop GPU
03.08.2023 10:07:28: CPU: -1 - 12th Gen Intel(R) Core(TM) i7-12650H - Intel64 Family 6 Model 154 Stepping 3
03.08.2023 10:07:28: AutoSetting for Online
03.08.2023 10:07:28: Optimization service is running
03.08.2023 10:07:28: Mode = 2 : OK
03.08.2023 10:07:28: GET GPU CLOCKS:NVAPI_GPU_NOT_POWERED
03.08.2023 10:07:28: SET GPU CLOCKS: -250, -250
03.08.2023 10:07:29: FanCPU = 14-3C-41-42-46-4F-59-62-00-00-00-00-05-12-24-2C : OK
03.08.2023 10:07:29: FanGPU = 14-3C-43-46-43-4E-57-62-00-00-00-03-00-0F-26-2D : OK
03.08.2023 10:07:29: Eco flag : 0
03.08.2023 10:07:29: Mux flag : 1
03.08.2023 10:07:29: NOVATEK:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY1
03.08.2023 10:07:29: BatteryLimit = 60 : OK
03.08.2023 10:07:29: BatteryLimit = 60 : OK
03.08.2023 10:07:29: TUF Brightness = 128 : OK
03.08.2023 10:07:29: Monitor Power On
03.08.2023 10:07:29: TUF_KB = 445 : OK
03.08.2023 10:07:29: TUF RGB = B4-00-FF-FF-FF-EB-00-00-00-00-00-00 : 0
03.08.2023 10:07:30: PowerLimit A0 = 12 : OK
03.08.2023 10:07:30: PowerLimit A3 = 12 : OK
03.08.2023 10:07:30: Session:SessionUnlock
03.08.2023 10:07:30: NOVATEK:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL: \\.\DISPLAY1
03.08.2023 10:07:30: PowerLimit C0 = 5 : OK
03.08.2023 10:07:30: PowerLimit C2 = 75 : OK
03.08.2023 10:09:03: Display configuration changed.
03.08.2023 10:11:03: HID Device Event: Checking for new ASUS Mice
03.08.2023 10:11:15: Display configuration changed.
03.08.2023 10:11:55: HID Device Event: Checking for new ASUS Mice
03.08.2023 11:00:29: HID Device Event: Checking for new ASUS Mice
03.08.2023 12:07:23: Power Mode:StatusChange
03.08.2023 12:24:33: Latest version 0.103.0.0
03.08.2023 12:24:45: Design Capacity: 76000mWh, Full Charge Capacity: 72113mWh, Health: 0,9488552631578947368421052632%
03.08.2023 12:27:15: BatteryLimit = 65 : OK
03.08.2023 12:27:16: BatteryLimit = 60 : OK
03.08.2023 12:27:16: BatteryLimit = 55 : OK
03.08.2023 12:27:17: Power Mode:StatusChange

**Asus software**
- Armoury Crate - UNINSTALLED
- MyASUS - UNINSTALLED
- NO Other Asus services running in background

**Comment by seerge** [comment]
@d00lar hello,

App sets limit every time
```
03.08.2023 10:02:11: BatteryLimit = 60 : OK
```

But you clearly have Asus Optimization service running that OVERRIDES this setting
```
03.08.2023 10:07:28: Optimization service is running
```

Just stop it from Extra -> Stop asus services (and set limit in app again, it should be fine) :)

Otherwise - i can't help anyhow, as app already does what it should ;)

**Comment by d00lar** [comment]
You are right sorry for that
i had them disabled
but yesturday updated  ASUSSystemControlInterfacev3_ASUS_Z_V3.1.17.0_15273 
this must enable them
regards
