### ISSUE TITLE
Key binding label wrapping makes spacing inconsistent on extra tab

### ISSUE THREAD

**Issue by RahulVivekNair** [seerge/g-helper#981]
## Description
I'm using an ASUS TUF F15 and the label for the key bind Fn+NmEnter is too long making it wrap into the next line which makes the padding weird on the next line. It is only a visual and aesthetic issue.

1. Go to the extra tab
2. View weird spacing below the Fn+NmEnter bind

**Expected behavior**
A shorter label name should fix the problem and I believe only tuf devices are affected.

**Screenshot**
![image](https://github.com/seerge/g-helper/assets/68507071/2b55e906-cb51-42ec-b5d2-777fe56e4dbf)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ASUS TUF F15 506HM

**Comment by seerge** [comment]
@RahulVivekNair this should fix it :) 
[GHelper.zip](https://github.com/seerge/g-helper/files/12250160/GHelper.zip)

**Comment by seerge** [comment]
@RahulVivekNair this build should have it 
[GHelper.zip](https://github.com/seerge/g-helper/files/12252062/GHelper.zip)

**Comment by RahulVivekNair** [comment]
Looks good!
