### ISSUE TITLE
Incorrect (inverted) touchpad status again.

### ISSUE THREAD

**Issue by caizefeng** [seerge/g-helper#983]
Seems unbelievable but a reported issue #732 shows up again. The touchpad status displays "ON" when I actually turn it off, and "OFF" when it's actually going on. Just like #732, the values in the registry and the settings are all CORRECT.  The only inconsistency is with the on-screen display, as well as the "Touchpad status" recorded in `log.txt`.

**Clear scenario to Reproduce**
1. Press 'Fn+F10'

**Expected behavior**
The touchpad status shows "ON" when I turn it on, and "OFF" when I turn it off.

**App Logs**
When it shows "ON" (actually off)  
```
8/3/2023 9:36:30 PM: Key: 107
8/3/2023 9:36:30 PM: Touchpad status:1
```
When it shows "OFF" (actually on)
```
8/3/2023 9:40:21 PM: Key: 107
8/3/2023 9:40:21 PM: Touchpad status:0
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: Zephyrus G14 GA402XV

**Asus software**
- ASUS Hotplug Controller installed
- Armoury Crate, MyASUS, and all other services are either uninstalled or disabled.

**Additional context**
I've tried the G-Helper 0.102.0, 0.103.0, 0.104, and the one you provide in #732. All exhibit the same "inverted" behavior.

**Comment by seerge** [comment]
@caizefeng it's probably your windows not updating status fast enough for checking it after toggle

I have added 0.2seconds delay to that action

[GHelper.zip](https://github.com/seerge/g-helper/files/12251886/GHelper.zip)

**Comment by seerge** [comment]
@caizefeng i will keep it, previous delay was 50ms
