### ISSUE TITLE
Buggy system after the latest update

### ISSUE THREAD

**Issue by AnchitGupta22** [seerge/g-helper#989]
After the recent update, my laptop (TUF A15 FA506IU) has been randomly shutting down with a blue screen. It worked fine on the previous update with undervolting (-15 CPU, -10 iGPU). The same settings were working fine on the last update, even more extreme (-30 CPU, -20 iGPU) were working fine.

I can positively say that the machine was working perfectly previously with the undervolting as I got better performance in comparison to the default three modes.

**Comment by seerge** [comment]
@AnchitGupta22 if undervolting causes your system to be unstable, don't do it or use lower values:) It's mentioned quite explicitly in the UI itself. Latest "update" (of the app) has absolutely nothing to do with this

**Comment by AnchitGupta22** [comment]
But I explicitly stated that the same settings worked on the previous updates for so long. It's just the present one which is creating these crashes.

**Comment by seerge** [comment]
@AnchitGupta22 well, i can't help you here anyway :)
