### ISSUE TITLE
Mixed results with switching from Standard -> Eco while HDMI port is being used

### ISSUE THREAD

**Issue by gloatoriginal** [seerge/g-helper#99]
**Describe the bug**
I have the HDMI in use with a 3rd monitor, while plugged in I can use it. When I unplug to use battery the monitor & HDMI port should stop working once successfully switching to ECO mode. Currently G-Helper will sometimes switch to eco mode and the HDMI port & monitor stop working (what is intended). Other times it will stall on "Changing" than resort back to standard mode and the 3rd monitor & HDMI port still work.

**To Reproduce**
Have USB-C -> Display port hub plugged in and HDMI cord plugged into the left HDMI port
Have laptop plugged in and monitor works
Unplug laptop and G-Helper attempts to switch to Eco mode

**Expected behavior**
Laptop switches to Eco mode, disabling the dGPU 6700s and the HDMI port & monitor become inactive.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
Zephyrus g14 6700s 2022 model

**Additional context**
It seems like it is very mixed on how often and when it happens. I was trying to reproduce and record a video while it was continuing to stay in standard mode and not disabling the gpu but sadly I couldn't make it happen for a video at the time.

**Comment by seerge** [comment]
The fact that you see "chaning" means that app has actually sent a signal to bios (via ACPI) to shut down dGPU (it locks buttons for a brief moment to stop user from switching again in the middle). It could be that bios by some reason refuses to switch. It happens to me when I plug off my external monitor and power cable at the same time for example (and also randomly). I can't really do much here tho :) as app sends it signal when it's plugged off ...

**Comment by gloatoriginal** [comment]
Would it be possible to validate after a "Change" has occurred that the change has worked?

**Comment by seerge** [comment]
There is no guarantee second attempt will work :)

**Comment by seerge** [comment]
[GHelper (2).zip](https://github.com/seerge/g-helper/files/11012122/GHelper.2.zip)
can you try this build ? i simply added 3 seconds delay between plug off and ECO trigger

**Comment by seerge** [comment]
@gloatoriginal

**Comment by arthur-lbchn** [comment]
@seerge I think I have a similar problem. 

Asus ROG Strix SCAR 15 review (G533ZW)
Windows 11 

So when I unplug my monitor connected to HDMI and later unplug power cable, I cannot switch GPU Mode from Standard to Eco. It just says Switching... and revert back to Standard. I assume that something still holds dGPU, but I don't see anything running.

I can provide you with the logs or record the video to show you.

Thanks in advance!

**Comment by seerge** [comment]
@arthur-lbchn does it switch when you try to click button on second attempt ? Cause if it doesn't - it's not much i can do, as it's probably some hikkup with bios / system that in general prevents dGPU to go off :|

**Comment by arthur-lbchn** [comment]
@seerge yes, the same happens even trying to switch several times. But after system restart, I was not able to reproduce.

Sorry for bumping, will monitor further.
