### ISSUE TITLE
[BUG REPORT] Incorrect Bindings on Tuf A15 2020 with Fn lock enabled

### ISSUE THREAD

**Issue by ronell1292k** [seerge/g-helper#990]
**Describe the bug**
When Fn lock is disabled, all the F1-12 hotkeys work as expected, however when Fn lock is enabled the behaviour for some keys is incorrect

F1-5: works as expected
F6 should turn the display off, does nothing and double pressing it opens the snipping tool
F7 and F8 have behaviour inverted, F7 should reduce brightness but it increases it, vice versa for F8 where it should increase the brightness but reduces it
F9 works as expected
F10 shows the OSD but does not work (should enable/disable trackpad)
F11 and F12 works as expected

**Clear scenario to Reproduce**
1. Enable Fn lock with Fn+C
2. Use the Fn keys

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Tuf A15 2020 FA506IH

**Asus software**
NA

Attaching a pic of the laptop's keyboard for reference
![image](https://github.com/seerge/g-helper/assets/37792939/d280c557-1137-4738-9571-8fd3703c358b)

**Comment by seerge** [comment]
@ronell1292k hello,
F6 on all other models runs a print-screen :) isn't it a better and more useful feature? :) 
F7/F8 should work ok in this build, your model is probably one of a bugged ones where bios calls are swapped
F10 - is not supported on TUF models, as i don't know how to disable touchpad programmatically there 

[GHelper.zip](https://github.com/seerge/g-helper/files/12254310/GHelper.zip)

**Comment by ronell1292k** [comment]
Thank you, this fixed it! It's now working as intended by you, also I agree with the print screen being more useful

**Comment by ronell1292k** [comment]
Hi, as of v.0.106.0 there is a new bug with the brightness controls with Fn lock enabled

F7 and F8 both reduce the brightness and if the brightness is at 0% pressing F8 will raise the brightness to 10% ( with Ghelper's OSD displaying the brightness as 10%), however subsequently pressing F8 again brings it back to 0%

Behaviour with Fn lock disabled is perfect.

**Comment by seerge** [comment]
@ronell1292k can you check if this one fixes it ?
[GHelper.zip](https://github.com/seerge/g-helper/files/12268032/GHelper.zip)

**Comment by ronell1292k** [comment]
Thanks for the quick reply! Unfortunately, no it does not fix the issue. The behaviour is the same as I just mentioned above. The build from [here](https://github.com/seerge/g-helper/issues/990#issuecomment-1664493559) had it working fine

**Comment by seerge** [comment]
@ronell1292k and this ? 
[GHelper.zip](https://github.com/seerge/g-helper/files/12268061/GHelper.zip)

**Comment by ronell1292k** [comment]
hi, so this build gives F7 the same behaviour that F8 was having:
Pressing F7 with Fn lock on reduces the increases the brightness till it is at max, at max bright pressing F7 reduces by one step, ie 90% ans I see an OSD for that. Subsequently pressing F7 again raises it to max and then back at 90.
F8 behaviour is the same as the previous build

**Comment by seerge** [comment]
@ronell1292k can you check this one and post a log ?
[GHelper.zip](https://github.com/seerge/g-helper/files/12269524/GHelper.zip)

**Comment by ronell1292k** [comment]
Hi, this works perfectly! 

Here's a log:
Pressed F8 twice and then F7 once

```
06-08-23` 18:00:22: F8
06-08-23 18:00:22: Brightness = 16 : 0
06-08-23 18:00:23: TUF RGB = B4-00-33-99-00-00-00-00-00-00-00-00 : OK
06-08-23 18:00:23: F8
06-08-23 18:00:23: Brightness = 16 : 0
06-08-23 18:00:25: TUF RGB = B4-00-33-99-00-00-00-00-00-00-00-00 : OK
06-08-23 18:00:26: F7
06-08-23 18:00:26: Brightness = 32 : 0
06-08-23 18:00:27: TUF RGB = B4-00-33-99-00-00-00-00-00-00-00-00 : OK
06-08-23 18:00:29: TUF RGB = B4-00-33-99-00-00-00-00-00-00-00-00 : OK
06-08-23 18:00:31: TUF RGB = B4-00-3D-9E-00-00-00-00-00-00-00-00 : OK
```

**Comment by seerge** [comment]
@ronell1292k also fn+f7/8 and ctrl+m1/m2 ?

**Comment by ronell1292k** [comment]
Fn + F7/F8 works fine. My laptop doees not have the M keys. Also, I just noticed that Shift + Fn + F2/F3 increase/decrease the kb brightness. Pretty cool.

Thanks again!

**Comment by thepriyamkalra** [comment]
At some point this bug was also introduced on the TUF F15, I did test the other brightness controls Ctrl+FnF2/F3, Fn+F7/F8, but forgot to test F7/F8 with FnLock until now. The issue is also gone for me on the linked build.

**Comment by thepriyamkalra** [comment]
> Fn + F7/F8 works fine. My laptop doees not have the M keys. Also, I just noticed that Shift + Fn + F2/F3 increase/decrease the kb brightness. Pretty cool.

You should also be able to use Fn+ArrowUp/ArrowDown to control the backlight brightness and Fn+ArrowLeft/ArrowRight to cycle through it's modes.
