### ISSUE TITLE
G16 (2023) - Incorrect touchpad state (enabled/disabled) animation

### ISSUE THREAD

**Issue by nicko-woo** [seerge/g-helper#991]
## NOTE
Hi. I'm very grateful for the G-Helper - its much better than Asus native firmware.

**Describe the bug**
Touchpad state icons are mixed up - its show enabled for disabled state, and vice versa.

**Clear scenario to Reproduce**

1. Open G-Helper and make sure that all Asus services are stopped.
2. Press FN + F10 and check touchpad state.
3. Press FN + F10 and check touchpad state again.
4. Open G-Helper again and start Asus services.
5. Repeat steps 2 and 3.

**Expected behavior**
Icons should be swapped.

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``

**Screenshots or screencasts**
![зображення](https://github.com/seerge/g-helper/assets/17978376/3957f5b8-4081-4596-8ea6-eef51f1f34d1)

**Desktop (please complete the following information):**
 - OS: Windows 11 Build  22621.2070
 - Laptop model - ROG Zephyrus G16 GU603ZV

**Asus software**
- Armoury Crate (or it's services installed) - **no**
- MyASUS installed - **yes**
- Other Asus services running in background - no

**Comment by seerge** [comment]
@nicko-woo what verion do you have ? in 105 i have added a slight delay before "checking" for touchpad status after changing, as sometimes windows is slow to update it ...

**Comment by nicko-woo** [comment]
@seerge Thanks, sorry, I'm using v103. I'll try to check using v105. Thanks a lot. If I can help you with some testing in general - ping me any time.

**Comment by nicko-woo** [comment]
@seerge I've checked with last v105 and now it works as expected. Thanks
