### ISSUE TITLE
"Download App" button does not work for v0.104+

### ISSUE THREAD

**Issue by thepriyamkalra** [seerge/g-helper#995]
I have noticed that the "Download App" button on pre-releases 104 & 105 do not work (while 103, 102 still work).
Downloading the asset "GHelper.zip" works as expected.

These hyperlinks have a tiny difference which is probably the issue here,
for instance in v0.105:
"Download App" points to https://github.com/seerge/g-helper/releases/download/v0.105/GHelper.zip (Not Found)
"GHelper.zip" under Assets points to https://github.com/seerge/g-helper/releases/download/v.105/GHelper.zip (Works)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/43999863/6c70e696-4a28-4b0d-8afc-d8bfa86ca7cc)

**Comment by seerge** [comment]
@thepriyamkalra thanks for spotting, i have corrected links :) 
https://github.com/seerge/g-helper/releases/tag/v0.105
