### ISSUE TITLE
Power Settings close the lid issue.

### ISSUE THREAD

**Issue by BBeBeeBeef** [seerge/g-helper#996]
Weird issues with Windows power settings, see the screenshot for the highlighted part. Something keeps resetting the setting 'when I close the lid' in plugged in to sleep. I always have it as 'do nothing' and every time I restart the computer it is changed back to 'sleep'. It has made my laptop crash a few times now and is getting really annoying.

Never had this issue until the past couple of weeks, I don't know when it exactly started or what has exactly caused it, I'm clutching at straws that it is a setting within Ghelper.

I do not have myasus, armoury crate, or AMD/Nvidia software installed (driver only). Only ghelper.

ASUS TUF A17 2022 FA707RM

[Screenshot 2023-08-04 090141](https://github.com/seerge/g-helper/assets/132345220/73b0fa64-d6a6-4a2a-98c3-f6ef86d2134b)

[Screenshot 2023-08-04 084939](https://github.com/seerge/g-helper/assets/132345220/ca14485e-f3c1-430b-8cc8-ec57b4cba666)

[log.txt](https://github.com/seerge/g-helper/files/12258426/log.txt)

**Comment by seerge** [comment]
@BBeBeeBeef hello, do you have Auto Clamshell mode on ? it will set lid action to NONE on external monitor + power plugged, and to SLEEP when there is no external monitor.

Just uncheck this and don't touch it anymore (and set whatever lid close action as you want)

**Comment by BBeBeeBeef** [comment]
Nope, it is not on. I've already removed this. Still happens :(

**Comment by BBeBeeBeef** [comment]
I'm going to uninstall g-helper and see if it still happens, then try reinstalling ghelper and see if it happens again. I'll let you know!

**Comment by seerge** [comment]
@BBeBeeBeef in config it says that it's on

```
03/08/2023 5:46:11 PM: Changed Lid Action to 1
03/08/2023 5:46:11 PM: Disengaging Clamshell Mode
```

**Comment by BBeBeeBeef** [comment]
It isn't! :)

![Screenshot 2023-08-04 101805](https://github.com/seerge/g-helper/assets/132345220/e9f2f1fa-4754-4fac-84e2-171102b130da)

**Comment by seerge** [comment]
@BBeBeeBeef then it should not change lid action :) (check what is current setting in your control panel and just keep using laptop as usual , mb reboot to see if something else changes that ? or it stays on your desired setting?)

**Comment by BBeBeeBeef** [comment]
So, I've just removed all traces of ghelper from my system, removed everything from appdata and the downloaded files too. Re-downloaded, effectively reinstalled it and it seems to have fixed the problem. it hasn't changed the control panel setting since :) 

Might be worth having a reset appdata option somewhere in a future update? just incase something like this happens again?

**Comment by seerge** [comment]
@BBeBeeBeef appdata just contains a config :) and if checkbox is off - it's off :)

**Comment by BBeBeeBeef** [comment]
It's very strange! nevermind, hopefully, this is the end of it!

**Comment by seerge** [comment]
Great, closing this as completed then

**Comment by stanly0726** [comment]
facing this problem too here, to me the clamshell mode is really confusing and didn't really tell what it will do in the UI, maybe address this in future?

**Comment by seerge** [comment]
@stanly0726 it won’t touch anything if you have it unchecked
