### ISSUE TITLE
BIOS rejected fan curved on Zephyrus M 2019

### ISSUE THREAD

**Issue by tradao2610** [seerge/g-helper#997]
My G-helper said that ASUS BIOS rejected fan curved

I tried to make a custom fan curve for my Zephyrus M GU502GU with 307 bios version on it.

Here is my logs: 
[log.txt](https://github.com/seerge/g-helper/files/12259417/log.txt)

![image](https://github.com/seerge/g-helper/assets/112112934/1cf3150a-1e3f-4c6d-8886-87df9650512d)

 - OS: Windows 10 22H2
 - Zephyrus M GU502GU (240hz screen)
 - Only G-helper on my laptop

**Comment by seerge** [comment]
@tradao2610 Then it's not supported by your device :) most probably you didn't have fan curves in armoury crate as well? :)

**Comment by tradao2610** [comment]
I think all Asus laptop before 2019 not support custom fan curved too. At least I tried everything lol.

Thx for your reply!
